### PR TITLE
[DependencyInjection] Support autowiring env vars as closures or `Stringable` when using `#[Autowire(env: 'FOO')]`

### LINKED ISSUE #60778: [DependencyInjection] Env vars are not reset with `kernel.reset`
### Symfony version(s) affected

7.3

### Description

PR #59136 and #54666 added the ability to reset env vars. In theory it works but in practice it doesn't since all env var loaders are loaded way too early because many symfony services define them dynamically, for example, these env vars APP_RUNTIME_MODE, APP_RUNTIME_ENV, VAR_DUMPER_SERVER, maybe even more.

As such I suggest EnvVarLoaders to define the env keys that it will provide a value for, thereby, preventing loading them unnecessarily.

### How to reproduce

Create a new symfony project, define an EnvVarLoader which loads an env var whose value can change based on certain conditions like tenant id, use the env in your messenger handler, it will always use the first value since all env var loaders are loaded very early in the process, even before a messenger message is handled.

### Possible Solution

EnvVarLoaders should be loaded on demand, they should define the keys that they can provide values for.

Something like or maybe even an attribute

```php
public static function envKeys(): array
{
    return ['DATABASE_URL', 'FILESYSTEM_PATH'];
}
```

and `EnvProcessor::getEnv` shouldn't go through all EnvLoaders, it should only go through env loaders which can provide the value for current key.

For BC reasons `envKeys` cannot be added to `EnvVarLoaderInterface` but can possibly be added via phpdoc.

### Additional Context

I've created a bug ticket instead of feature, because previous PRs aren't enough to make it work as expected even though the possible solution would lead to a new feature.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #60778
| License       | MIT

Using `#[Autowire(env: 'FOO')]`, or any `#[Autowire('…%env(…)%…')]` string value, on a parameter typed `Closure` or `Stringable` injects a callable / stringable that returns the value of the env reference at call time.

Contrary to injecting an env var as a `string` (which is baked at compile time), this stays refreshable across `Container::resetEnvCache()` — i.e. the next call returns the current value of `$_ENV[*]` — as typically done between requests in worker mode.

```php
class Foo
{
    public function __construct(
        #[Autowire(env: 'DB_URL')]
        private \Closure $dbUrl,
        #[Autowire(env: 'APP_NAME')]
        private string|\Stringable $appName = 'default',
        // Embedded env vars in any string also work:
        #[Autowire('redis://%env(HOST)%:%env(PORT)%')]
        private \Stringable $redisDsn,
        // %param% references are resolved through the parameter bag:
        #[Autowire('%dsn_template%')]
        private \Stringable $dsn,
    ) {
    }
}
```

When a default value is declared, it is returned when the env var is not defined (must be a string for `Stringable`, any type for `Closure`).

This PR also adds a matching `EnvClosureArgument` (the DI counterpart of `ServiceClosureArgument`) and an `!env_closure` YAML tag — its value mirrors what you'd write inside `#[Autowire('…')]`:

```yaml
services:
    App\Foo:
        arguments:
            - !env_closure '%env(DB_URL)%'                          # Closure
            - !env_closure ['%env(APP_NAME)%']                      # Stringable, no default
            - !env_closure ['%env(APP_NAME)%', 'default']           # Stringable with default
            - !env_closure ['%env(DB_URL)%', 'sqlite://', false]    # Closure with default
            - !env_closure 'redis://%env(HOST)%:%env(PORT)%'        # template
```

In the plane to Tunis, looks like I can still code without an LLM 😆

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Attribute/AutowireEnvClosure.php [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+ */
+#[\Attribute(\Attribute::TARGET_PARAMETER)]
+class AutowireEnvClosure extends Autowire
+{
+    /**
+     * @param string $env The env var to wrap in the closure
+     */
+    public function __construct(string $env)
+    {
+        parent::__construct(new ServiceClosureArgument(new Definition('string', [$env])->setFactory([new Reference('service_container'), 'getEnv'])));
```
Comment (GromNaN) [inline src/Symfony/Component/DependencyInjection/Attribute/AutowireEnvClosure.php]: Is the `string` class relevant? `getEnv` can return any scalar type or array depending on the env var processors applied.

**Review by GromNaN — COMMENTED** [review]
> This is similar to injecting `AutowireEnv('FOO')`

I was not aware of the `AutowireEnv` class and can't find it. Do you mean `Autowire(env:'FOO')` ?

**Comment by nicolas-grekas** [comment]
Thanks @GromNaN comments addressed!

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/autowire_closure.php [hunk 2]
```diff
@@ -46,7 +48,7 @@ public function isCompiled(): bool
...
+        return $container->services['bar'] = new \Symfony\Component\DependencyInjection\Tests\Dumper\LazyClosureConsumer(#[\Closure(name: 'foo', class: 'Symfony\\Component\\DependencyInjection\\Tests\\Compiler\\Foo')] fn () => ($container->services['foo'] ??= new \Symfony\Component\DependencyInjection\Tests\Compiler\Foo()), ($container->services['baz'] ?? self::getBazService($container)), ($container->services['foo'] ??= new \Symfony\Component\DependencyInjection\Tests\Compiler\Foo())->cloneFoo(...), ($container->services['my_callable'] ??= new \Symfony\Component\DependencyInjection\Tests\Compiler\MyCallable())->__invoke(...), fn () => $container->getEnv('FOO'));
```
Comment (GromNaN) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/autowire_closure.php]: Minor optimization: You can compile with a static closure.

```suggestion
        return $container->services['bar'] = new \Symfony\Component\DependencyInjection\Tests\Dumper\LazyClosureConsumer(#[\Closure(name: 'foo', class: 'Symfony\\Component\\DependencyInjection\\Tests\\Compiler\\Foo')] fn () => ($container->services['foo'] ??= new \Symfony\Component\DependencyInjection\Tests\Compiler\Foo()), ($container->services['baz'] ?? self::getBazService($container)), ($container->services['foo'] ??= new \Symfony\Component\DependencyInjection\Tests\Compiler\Foo())->cloneFoo(...), ($container->services['my_callable'] ??= new \Symfony\Component\DependencyInjection\Tests\Compiler\MyCallable())->__invoke(...), static fn () => $container->getEnv('FOO'));
```

**Review by GromNaN — APPROVED** [review]
LGTM

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/autowire_closure.php (hunk 2 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/autowire_closure.php]: unrelated to this PR - that's PhpDumper doing its work
and also: this closure is declared in a static method: it's already static ;)

Comment (GromNaN) [reply src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/autowire_closure.php]: Ok, I hadn't noticed the static method. Thanks for pointing that out.

**Comment by bendavies** [comment]
Awesome, we need this.

My concern would be that it's not clear when to use this one over the existing Autowire.

Could it not be argued that `Autowire(env: ...)` could be fixed/improved rather than introducing a new one? I guess you are considering that a BC break.

**Comment by nicolas-grekas** [comment]
> Autowire(env: ...) could be fixed/improved rather than introducing a new one

that's a good idea, and that works! see updated PR description

**Review by faizanakram99 — APPROVED** [review]

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 3]
```diff
@@ -311,12 +313,31 @@ private function autowireMethod(\ReflectionFunctionAbstract $reflectionMethod, a
...
+                        foreach (explode('|', $type) as $t) {
+                            if (!\in_array($t, ['Closure', 'Stringable'], true)) {
+                                continue;
+                            }
+                            $value = substr($value, 5, -2);
+                            if ('Stringable' === $t && !str_starts_with($value, 'string:')) {
+                                $value = 'string:'.$value;
+                            }
+
+                            $value = new ServiceClosureArgument(new Definition('mixed', [$value])->setFactory([new Reference('service_container'), 'getEnv']));
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: Should we introduce a new kind of argument value object, to make it easier to get this behavior for packages not using autowiring (for instance open-source bundles) instead of having to make them learn this complex trick for the setup ?

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: yes, done!

File: src/Symfony/Component/DependencyInjection/Tests/Loader/YamlFileLoaderTest.php [hunk 4]
```diff
@@ -23,6 +23,7 @@
 use Symfony\Component\Config\Resource\GlobResource;
 use Symfony\Component\DependencyInjection\Argument\BoundArgument;
 use Symfony\Component\DependencyInjection\Argument\IteratorArgument;
+use Symfony\Component\DependencyInjection\Argument\EnvClosureArgument;
```
Comment (GromNaN) [inline src/Symfony/Component/DependencyInjection/Tests/Loader/YamlFileLoaderTest.php]: Alpha order spotted by fabbot.
```suggestion
use Symfony\Component\DependencyInjection\Argument\EnvClosureArgument;
use Symfony\Component\DependencyInjection\Argument\IteratorArgument;
```

File: src/Symfony/Component/DependencyInjection/CHANGELOG.md [hunk 5]
```diff
@@ -4,6 +4,8 @@ CHANGELOG
 8.1
 ---
 
+ * Support autowiring env vars as closures or `Stringable` when using `#[Autowire(env: 'FOO')]`
```
Comment (alexisLefebvre) [inline src/Symfony/Component/DependencyInjection/CHANGELOG.md:7]: Does it also change the current behaviour? Should this line also explain that with this change, it will always return "fresh" values?

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/CHANGELOG.md:7]: it doesn't: the same throws today
