### PR TITLE
[Security] Fix str_contains type mismatch in ChannelListener

### LINKED ISSUE #42300: TypeError when Forwarded header is missing
**Symfony version(s) affected**: 5.3.5

**Stack Trace**
<details>

```text
TypeError:
Argument 1 passed to str_contains() must be of the type string, null given, called in [REDACTED]/vendor/symfony/security-http/Firewall/ChannelListener.php on line 52

  at vendor/symfony/polyfill-php80/bootstrap.php:29
  at str_contains(null, 'proto=https')
     (vendor/symfony/security-http/Firewall/ChannelListener.php:52)
  at Symfony\Component\Security\Http\Firewall\ChannelListener->supports(object(Request))
     (vendor/symfony/security-bundle/Debug/WrappedLazyListener.php:38)
  at Symfony\Bundle\SecurityBundle\Debug\WrappedLazyListener->supports(object(Request))
     (vendor/symfony/security-bundle/Security/LazyFirewallContext.php:52)
  at Symfony\Bundle\SecurityBundle\Security\LazyFirewallContext->__invoke(object(RequestEvent))
     (vendor/symfony/security-bundle/Debug/TraceableFirewallListener.php:59)
  at Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener->callListeners(object(RequestEvent), object(Generator))
     (vendor/symfony/security-http/Firewall.php:86)
  at Symfony\Component\Security\Http\Firewall->onKernelRequest(object(RequestEvent), 'kernel.request', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(RequestEvent), 'kernel.request', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:230)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(RequestEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:59)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(RequestEvent), 'kernel.request')
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:151)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(RequestEvent), 'kernel.request')
     (vendor/symfony/http-kernel/HttpKernel.php:133)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:79)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:199)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:37)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:35)
  at require_once('[REDACTED]/vendor/autoload_runtime.php')
     (public/index.php:5)
```

</details>

**Description**
The PHP 8 polyfill for str_contains does not accept null in it's arguments. This problem has shown up in more than one place. e.g. #42290 and in https://github.com/symfony/symfony/blob/534e1ed986bc0a33e1093f87bb6cede887a23a79/src/Symfony/Component/Security/Http/Firewall/ChannelListener.php#L52

DumpDataCollector.php avoids the issue by checking for the existence of the header.
https://github.com/symfony/symfony/blob/61ecf9bf6a934c5df680008daa7b6642742f8bf2/src/Symfony/Component/HttpKernel/DataCollector/DumpDataCollector.php#L118

The solution is probably the same as #42290.

### PR DESCRIPTION
**Pull request by bobvandevijver**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #42300, Part of #41552
| License       | MIT
| Doc PR        | -

Also use a default empty string in the `ChannelListener` before using `str_contains`.

### CODE REVIEW

File: src/Symfony/Component/Security/Http/Tests/Firewall/ChannelListenerTest.php [hunk 1]
```diff
@@ -153,4 +155,30 @@ public function testHandleWithSecuredRequestAndHttpChannel()
...
+            ->expects($this->any())
+            ->method('getPatterns')
+            ->with($this->equalTo($request))
+            ->willReturn([[], 'https'])
+        ;
+
+        $entryPoint = $this->createMock(AuthenticationEntryPointInterface::class);
+        $logger = $this->createMock(LoggerInterface::class);
+
+        $listener = new ChannelListener($accessMap, $entryPoint, $logger);
```
Comment (derrabus) [inline src/Symfony/Component/Security/Http/Tests/Firewall/ChannelListenerTest.php]: The logger is optional.

```suggestion
        $listener = new ChannelListener($accessMap, $entryPoint);
```

**Review by derrabus — APPROVED** [review]
Just a minor comment.

**Comment by derrabus** [comment]
Context: We need this change for #41552.

File: src/Symfony/Component/Security/Http/Tests/Firewall/ChannelListenerTest.php (hunk 1 above)
Comment (bobvandevijver) [reply src/Symfony/Component/Security/Http/Tests/Firewall/ChannelListenerTest.php]: Actually, not for what I'm testing here, as that requires the logger to be set 😄 

https://github.com/symfony/symfony/blob/b45560c74620873ac04b26a2562ddee20e9a444a/src/Symfony/Component/Security/Http/Firewall/ChannelListener.php#L51

Comment (derrabus) [reply src/Symfony/Component/Security/Http/Tests/Firewall/ChannelListenerTest.php]: Oh, I see. Let's pass a `NullLogger` instead then.

Comment (bobvandevijver) [reply src/Symfony/Component/Security/Http/Tests/Firewall/ChannelListenerTest.php]: Ok, it's updated.

**Review by derrabus — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @bobvandevijver.
