### PR TITLE
[WebProfilerBundle] add debugbar on `StreamedResponse`

### LINKED ISSUE #57288: Web developer toolbar incompatible with streaming
### Symfony version(s) affected

6.4.7

### Description

HTTP streaming seems like a drop-in upgrade to not buffer the whole response, by simply replacing calls in controller actions from `$this->render()` to `$this->stream()`, except the web developer toolbar will not show up in this case.

### How to reproduce

Call `$this->stream()` in a controller action in lieu of `$this-render()`.

### Possible Solution

Don't stream LOL.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by damienfern**
| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #57288
| License       | MIT

### CODE REVIEW

File: src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php [hunk 1]
```diff
@@ -128,26 +128,59 @@ public function onKernelResponse(ResponseEvent $event): void
...
+
+            if (false !== $pos) {
+                $response->setContent(
+                    $this->renderToolbarInContent($content, $pos, $response->headers->get('X-Debug-Token'), $request, $nonces)
+                );
+            }
         }
     }
 
+    protected function renderToolbarInContent(string $content, int $pos, ?string $debugToken, Request $request, array $nonces): string
```
Comment (stof) [inline src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php]: why adding a new protected method ?

File: src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php [hunk 2]
```diff
@@ -104,7 +105,6 @@ public function onKernelResponse(ResponseEvent $event): void
                 // keep current flashes for one more request if using AutoExpireFlashBag
                 $session->getFlashBag()->setAll($session->getFlashBag()->peekAll());
             }
-
```
Comment (stof) [inline src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php:114]: I suggest keeping this empty line

File: src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php [hunk 3]
```diff
@@ -128,26 +128,59 @@ public function onKernelResponse(ResponseEvent $event): void
...
-                    'request' => $request,
-                    'csp_script_nonce' => $nonces['csp_script_nonce'] ?? null,
-                    'csp_style_nonce' => $nonces['csp_style_nonce'] ?? null,
-                ]
-            ))."\n";
-            $content = substr($content, 0, $pos).$toolbar.substr($content, $pos);
-            $response->setContent($content);
+        if ($response instanceof StreamedResponse) {
+            $callback = $response->getCallback();
+            if (false !== strripos($response->headers->get('Content-Type'), 'text/html')) {
```
Comment (stof) [inline src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php]: do we need this ? `onKernelResponse` already does a check on the content type.

File: src/Symfony/Bundle/WebProfilerBundle/Tests/EventListener/MockedStreamedResponse.php [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Bundle\WebProfilerBundle\Tests\EventListener;
+
+use Symfony\Component\HttpFoundation\StreamedResponse;
+
+class MockedStreamedResponse extends StreamedResponse
+{
+    public function getContent(): string|false
```
Comment (stof) [inline src/Symfony/Bundle/WebProfilerBundle/Tests/EventListener/MockedStreamedResponse.php]: I would not override the `getContent` method of StreamedResponse for that, as it means this MockedStreamedResponse does not actually behave like a StreamedResponse (in which you _cannot_ call `getContent` to get the actual content), which would potentially hide bugs in tests.

Instead, I would suggest writing a separate test covering the injection of the toolbar in a streamed response, which would perform this output buffering in the test (using `$response->sendContent()`).

File: src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php (hunk 1 above)
Comment (damienfern) [reply src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php]: You're right, only used at one place. Removed.

File: src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php (hunk 3 above)
Comment (damienfern) [reply src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php]: I missed that, thx !

File: src/Symfony/Bundle/WebProfilerBundle/Tests/EventListener/MockedStreamedResponse.php (hunk 4 above)
Comment (damienfern) [reply src/Symfony/Bundle/WebProfilerBundle/Tests/EventListener/MockedStreamedResponse.php]: You're right and indeed I missed a bug on StreamedResponse [here](https://github.com/symfony/symfony/pull/58789/files#diff-af937a8407173a2c929cd87fd9394095d21199f8c2cc1627eaeaa7935db0532cR109).

Let me know if it's ok for you.

File: src/Symfony/Bundle/WebProfilerBundle/CHANGELOG.md [hunk 5]
```diff
@@ -5,6 +5,7 @@ CHANGELOG
 ---
 
  * Add `ajax_replace` option for replacing toolbar on AJAX requests
+ * Show debug bar when using a streamed response
```
Comment (alexandre-daubois) [inline src/Symfony/Bundle/WebProfilerBundle/CHANGELOG.md]:
```suggestion
 * Add support for streamed responses in the debug toolbar
```

File: src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php [hunk 6]
```diff
@@ -133,26 +141,51 @@ public function onKernelResponse(ResponseEvent $event): void
...
+                ob_start(function (string $buffer, int $phase) use ($toolbarHTMLContent): string {
+                    $pos = strripos($buffer, '</body>');
+                    if (false !== $pos) {
+                        $buffer = substr($buffer, 0, $pos).$toolbarHTMLContent.substr($buffer, $pos);
+                    }
+
+                    return $buffer;
+                }, 8); // length of '</body>'
+
+                ($callback)();
```
Comment (alexandre-daubois) [inline src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php]:
```suggestion
                $callback();
```

File: src/Symfony/Bundle/WebProfilerBundle/Tests/EventListener/WebDebugToolbarStreamedResponseListenerTest.php [hunk 7]
```diff
@@ -0,0 +1,386 @@
...
+     */
+    public function testInjectToolbar(string $content, string $expected)
+    {
+        $listener = new WebDebugToolbarListener($this->getTwigMock());
+        $m = new \ReflectionMethod($listener, 'injectToolbar');
+
+        $response = new StreamedResponse($this->createCallbackFromContent($content));
+
+        $m->invoke($listener, $response, Request::create('/'), ['csp_script_nonce' => 'scripto', 'csp_style_nonce' => 'stylo']);
+        $this->assertEquals($expected, $this->getContentFromStreamedResponse($response));
```
Comment (alexandre-daubois) [inline src/Symfony/Bundle/WebProfilerBundle/Tests/EventListener/WebDebugToolbarStreamedResponseListenerTest.php]: Prefer using `assertSame()` wherever possible in the whole test class

File: src/Symfony/Bundle/WebProfilerBundle/Tests/EventListener/WebDebugToolbarStreamedResponseListenerTest.php [hunk 8]
```diff
@@ -0,0 +1,386 @@
...
+    }
+
+    public static function getInjectToolbarTests()
```
Comment (alexandre-daubois) [inline src/Symfony/Bundle/WebProfilerBundle/Tests/EventListener/WebDebugToolbarStreamedResponseListenerTest.php]:
```suggestion
    public static function provideInjectedToolbarHtml()
```

**Review by nicolas-grekas — CHANGES_REQUESTED** [review]
Branch 7.4 now uses PHPUnit attributes, can you please rebase and update accordingly? Don't miss taking comments into account while doing so.

**Comment by nicolas-grekas** [comment]
Thank you @damienfern.
