### PR TITLE
[Serializer] Fix dealing with asymmetric visilibity for properties

### LINKED ISSUE #61552: Uncaught Error: Cannot modify protected(set) property
### Symfony version(s) affected

v7.3.2

### Description

serializer for some reason it tries to write to a field with asymmetric visibility protected(set) and serializer starts to crash, although the object is completely filled.

### How to reproduce

<details>
  <summary>Code repoduce</summary>

```php
<?php

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\PropertyInfo\Extractor\PhpStanExtractor;
use Symfony\Component\PropertyInfo\PropertyInfoExtractor;
use Symfony\Component\Serializer\Attribute\DiscriminatorMap;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Mapping\ClassDiscriminatorFromClassMetadata;
use Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory;
use Symfony\Component\Serializer\Mapping\Loader\AttributeLoader;
use Symfony\Component\Serializer\NameConverter\MetadataAwareNameConverter;
use Symfony\Component\Serializer\Normalizer\ArrayDenormalizer;
use Symfony\Component\Serializer\Normalizer\DateIntervalNormalizer;
use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Normalizer\UidNormalizer;
use Symfony\Component\Serializer\Normalizer\UnwrappingDenormalizer;
use Symfony\Component\Serializer\Serializer;


enum CapsuleItemType: string
{
    case FINAL = 'FINAL';

    case PROVIDER = 'PROVIDER';

    case FINANCIAL = 'FINANCIAL';

    case USER_INPUT = 'USER_INPUT';
    case MERGED     = 'MERGED';

}


final class FinalCapsuleItem
{
    public function __construct(
        public int $id,
    ) {
    }
}



final class AddFinalCapsuleItemRequest implements AddCapsuleItemRequest
{
    protected(set) CapsuleItemType $type;

    public function __construct(
        public readonly FinalCapsuleItem $item,
    ) {
        $this->type = CapsuleItemType::FINAL;
    }
}


final class AddFinancialCapsuleItemRequest implements AddCapsuleItemRequest
{
    protected(set) CapsuleItemType $type;

    public function __construct(
        public readonly FinalCapsuleItem $item,
    ) {
        $this->type = CapsuleItemType::FINAL;
    }
}



#[DiscriminatorMap('type', [
    CapsuleItemType::FINAL->value      => AddFinalCapsuleItemRequest::class,
    CapsuleItemType::FINANCIAL->value  => AddFinancialCapsuleItemRequest::class,
])]
interface AddCapsuleItemRequest
{
    protected(set) CapsuleItemType $type {get;set;}
}



$classMetadataFactory = new ClassMetadataFactory(new AttributeLoader());

$objectNormalizer     = new ObjectNormalizer(
    $classMetadataFactory,
    new MetadataAwareNameConverter($classMetadataFactory),
    null,
    new PropertyInfoExtractor(
        [],
        [new PhpStanExtractor()],
        [],
        [],
        []
    ),
    new ClassDiscriminatorFromClassMetadata($classMetadataFactory),
);



$serializer =
    new Serializer([
        new UnwrappingDenormalizer,
        new UidNormalizer,
        new DateTimeNormalizer,
        new DateIntervalNormalizer,
        $objectNormalizer,
        new ArrayDenormalizer], [new JsonEncoder]
    );


$json = <<<JSON
   {
     "type": "FINAL",
     "item": {
       "id": 1
     }
   }
JSON;



dd(
    $serializer->deserialize($json, AddCapsuleItemRequest::class, 'json'),
);
```
</details>

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by santysisi**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #61552
| License       | MIT

### Description

This PR resolves a crash in the `Serializer` when deserializing an object with a `protected(set)` or `private(set)` property

### CODE REVIEW

**Comment by santysisi** [comment]
I think (though I might be wrong) that the pipeline errors are not relevant in the context of this PR.

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php [hunk 1]
```diff
@@ -185,6 +185,9 @@ protected function isAllowedAttribute($classOrObject, string $attribute, ?string
             } else {
                 self::$isWritableCache[$class.$attribute] = $this->propertyInfoExtractor->isWritable($class, $attribute)
                     || (($writeInfo = $this->writeInfoExtractor->getWriteInfo($class, $attribute)) && PropertyWriteInfo::TYPE_NONE !== $writeInfo->getType());
+                if (isset($writeInfo) && PropertyWriteInfo::TYPE_PROPERTY === $writeInfo->getType() && PropertyWriteInfo::VISIBILITY_PUBLIC !== $writeInfo->getVisibility()) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]: code-style wise, this should be a continuation of the previous boolean check
code-logic wise, this looks suspicious to me: L187 should more likely be made to return false instead. Otherwise this looks super specific.

File: src/Symfony/Component/Serializer/Tests/SerializerTest.php [hunk 2]
```diff
@@ -1725,6 +1726,19 @@ public function testDenormalizationFailsWithMultipleErrorsInDefaultContext()
...
+     * @requires PHP 8.4
+     */
+    public function testDeserializeObjectWithAsymmetricPropertyVisibility()
+    {
+        $serializer = new Serializer([new ObjectNormalizer()], ['json' => new JsonEncoder()]);
+        /** @var AsymmetricVisibilityDummy $object */
+        $object = $serializer->deserialize(json_encode(['type' => 'final', 'item' => 'one']), AsymmetricVisibilityDummy::class, 'json');
+
+        $this->assertSame('one', $object->item);
+        $this->assertSame('final', $object->type);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Tests/SerializerTest.php]: the values in the constructor and in the test case are the same, which means we don't know what we test

**Review by nicolas-grekas — COMMENTED** [review]
thanks for opening this!

**Comment by santysisi** [comment]
Hi 😊 I hope you're doing well!
Thank you so much for your comments ❤️
I've made the changes, please let me know if anything else needs to be adjusted :smile:

File: src/Symfony/Component/Serializer/Tests/SerializerTest.php (hunk 2 above)
Comment (santysisi) [reply src/Symfony/Component/Serializer/Tests/SerializerTest.php]: Updated the test and added comments :smile: . The test checks that the original value remains unchanged due to the `private(set)` property

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php (hunk 1 above)
Comment (santysisi) [reply src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]: I agree with you 😄
I updated the code style and slightly adjusted the logic. Let me know if any other changes are needed.
Thanks again ❤️

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php [hunk 3]
```diff
@@ -184,7 +184,10 @@ protected function isAllowedAttribute($classOrObject, string $attribute, ?string
                 self::$isWritableCache[$class.$attribute] = true;
             } else {
                 self::$isWritableCache[$class.$attribute] = $this->propertyInfoExtractor->isWritable($class, $attribute)
-                    || (($writeInfo = $this->writeInfoExtractor->getWriteInfo($class, $attribute)) && PropertyWriteInfo::TYPE_NONE !== $writeInfo->getType());
+                || (
+                    ($writeInfo = $this->writeInfoExtractor->getWriteInfo($class, $attribute)) && PropertyWriteInfo::TYPE_NONE !== $writeInfo->getType()
+                    && (PropertyWriteInfo::TYPE_PROPERTY !== $writeInfo->getType() || PropertyWriteInfo::VISIBILITY_PUBLIC === $writeInfo->getVisibility())
+                );
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]: Wouldn't this make more sense? The visibility check should have already been done on L186, isn't it?

```suggestion
                || (($writeInfo = $this->writeInfoExtractor->getWriteInfo($class, $attribute)) && !\in_array($writeInfo->getType(), [PropertyWriteInfo::TYPE_NONE, PropertyWriteInfo::TYPE_PROPERTY], true));
```

**Review by nicolas-grekas — COMMENTED** [review]
On closer review, this makes me think we also need to fix the call to isReadOnly in ReflectionExtractor on L365 - we might need to check for asym there also. Can you have a look?

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php (hunk 3 above)
Comment (santysisi) [reply src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]: I agree with you, this is much better!

**Comment by santysisi** [comment]
> On closer review, this makes me think we also need to fix the call to isReadOnly in ReflectionExtractor on L365 - we might need to check for asym there also. Can you have a look?

Thanks for pointing that out! Maybe I’m wrong, but I think it might not be necessary to update the call to `isReadOnly` on L365, since the `isAllowedProperty` method is executed beforehand and already checks for asymmetric visibility.

**Comment by nicolas-grekas** [comment]
Thank you @santysisi.
