### PR TITLE
[Cache] Remove temporary cache item file on `rename()` failure

### LINKED ISSUE #52092: [Cache] Temporary files not cleaned from filesystem
### Symfony version(s) affected

5.x, 6.x

### Description

On an open source PHP application I work on, we sometimes have issues reported by administrators related to unexpected filesystem saturation. The impacted cache namespace is supposed to contains only a dozen of items, but the directory contains 250k files located at its root. These files are temporary files generated when a cache entry is updated, and are supposed to be removed automatically.

The problem is that the target file is exists, contains stale information, but is not writable.

First, let's resume what is done by the Filesystem apadter when a cache entry is written:
1. a temporary file is created at the root of the cache directory;
2. content is written inside this file;
3. this file is renamed to its target path, using the PHP `rename()` function.

Related code: https://github.com/symfony/symfony/blob/d69ab75aa386f3135130bb7becf767c06dd067bf/src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php#L88-L114

Now, let's see what the `rename()` function do:
1. the file is copied to its target path;
2. the ownership of the target file is updated;
3. the mod of the target file is updated;
4. the source file is deleted.

If any of the 3 first steps fails, the unlink is not done.

Related code: https://github.com/php/php-src/blob/221b4fe246e62c5d59f617ee4cbe6fd4c614fb5a/main/streams/plain_wrapper.c#L1272-L1371

### How to reproduce

1. Create a cache entry with a short lifetime (1s).
2. Make the corresponding file read-only on the filesystem.
3. Update the cache entry.

-> The temporary file created on the cache directory root is not deleted.

### Possible Solution

On Symfony 4.4, a cleaning operation was always done after the rename, see #39059. I think it could be simple to put back this cleaning operation, to prevent filesystem saturation.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by cedric-anne**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #52092
| License       | MIT

The filesystem cache adapter creates a temporary file to store cache item data, then moves it to its target path using `rename()` function. If rename fails, for instance target path is not writable, the temporary file will remains.

To prevent filesystem saturation, the temporary files should be deleted if this operation is not done by the `rename()` function itself.

### CODE REVIEW

File: src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php [hunk 1]
```diff
@@ -112,7 +112,13 @@ private function write(string $file, string $data, int $expiresAt = null)
                 touch($this->tmp, $expiresAt ?: time() + 31556952); // 1 year in seconds
             }
 
-            return rename($this->tmp, $file);
+            $success = rename($this->tmp, $file);
+
+            if (true === file_exists($this->tmp)) {
```
Comment (stof) [inline src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php]:
```suggestion
            if (file_exists($this->tmp)) {
```

File: src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php [hunk 2]
```diff
@@ -112,7 +112,13 @@ private function write(string $file, string $data, int $expiresAt = null)
                 touch($this->tmp, $expiresAt ?: time() + 31556952); // 1 year in seconds
             }
 
-            return rename($this->tmp, $file);
+            $success = rename($this->tmp, $file);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php:117]: what about this instead?
```suggestion
            if (!rename($this->tmp, $file)) {
                unlink($this->tmp);
                
                return false;
            }
```

Comment (cedric-anne) [reply src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php:117]: See https://github.com/php/php-src/blob/master/main/streams/plain_wrapper.c#L1272-L1371

Internally, when using the `rename()` function, PHP will do a `copy()` + `unlink()`, but will not return false if `unlink()` fails. So it is potentially possible to get a success on rename operation, but to still have the temporary file here.

I hesitate while coding this fix. As it is really an edge case, it can be ignored, in order to optimize performances for the most common case.

**Review by nicolas-grekas — COMMENTED** [review]
I pushed a slightly different implementation, can you please confirm it works for you?

**Comment by cedric-anne** [comment]
> I pushed a slightly different implementation, can you please confirm it works for you?

I confirm it fixes the issue.

File: src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php [hunk 3]
```diff
@@ -107,14 +108,20 @@ private function write(string $file, string $data, int $expiresAt = null)
...
             }
 
-            return rename($this->tmp, $file);
+            return !$unlink = !rename($this->tmp, $file);
         } finally {
             restore_error_handler();
+
+            if ($unlink) {
+                @unlink($this->tmp);
+                $this->tmp = null;
```
Comment (stof) [inline src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php]: If we reset it to `null` here, is there any benefit at having it as an instance property rather than a local variable ?

Comment (stof) [reply src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php]: the instance property was meant to avoid re-reading random bytes, but this was a benefit only if it was kept for next usage.

Comment (nicolas-grekas) [reply src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php]: we reset to null only if rename fails

Comment (cedric-anne) [reply src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php]: I agree, there is no need to reset this property here.

If unlink silently fails, it will anyway recompute a new value to write on a new file, thanks to this code:
https://github.com/symfony/symfony/blob/f14f23b1a4ff29a2de40c8572c392aa44d474834/src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php#L99-L108

File: src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php [hunk 4]
```diff
@@ -107,14 +108,20 @@ private function write(string $file, string $data, int $expiresAt = null)
...
             fwrite($h, $data);
             fclose($h);
+            $unlink = true;
 
             if (null !== $expiresAt) {
                 touch($this->tmp, $expiresAt ?: time() + 31556952); // 1 year in seconds
             }
 
-            return rename($this->tmp, $file);
+            return !$unlink = !rename($this->tmp, $file);
```
Comment (staabm) [inline src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php]: two negations in one line. maybe split into two lines for readability?

File: src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php (hunk 3 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php]: which means this line is legit, since it allows bypassing some try/catch that we know for sure we'll hit

Comment (cedric-anne) [reply src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php]: > which means this line is legit, since it allows bypassing some try/catch that we know for sure we'll hit

We will probably not hit it, as we just unlink the temporary file.

Comment (cedric-anne) [reply src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php]: > > which means this line is legit, since it allows bypassing some try/catch that we know for sure we'll hit
> 
> We will probably not hit it, as we just unlink the temporary file.

I mean, if we reach this point, it means that we were able to create a temporary file, write something in it, but moving it fails. It is highly probable that we will be able to unlink it, as moving failure is probably due to a restriction on the target path, not on the source path.

**Comment by nicolas-grekas** [comment]
Thank you @cedric-anne.
