### PR TITLE
[Mailer] Add `retry_period` option for email transport

### LINKED ISSUE #50981: [Mailer] Make `RoundRobinTransport` `retryPeriod` configurable
### Description

I started using the `roundrobin(...)` config option of the Mailer, but I'm unable to configure the `retryPeriod` option, which would grant retries over failed connections: https://github.com/symfony/symfony/blob/80f1096fa341811f2eb530466953b612a3e7d54e/src/Symfony/Component/Mailer/Transport/RoundRobinTransport.php#L38

This is an issue while using the Messenger (which I'm doing, even if not directly) because for 60 seconds my consumer is susceptible to any kind of transport failure.

I tried overriding that, but it required decorating the transport factory and using reflection, so... adding the possibility of piloting that option would be great!

### Example

_No response_

### PR DESCRIPTION
**Pull request by sdespont**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix https://github.com/symfony/symfony/issues/50981 https://github.com/symfony/symfony/issues/52551
| License       | MIT

RoundRobinTransport constructor has retryPeriod set to 60 seconds. This cannot be configured right now.

Let's say all the transports fail (e.g. email address with domain that does not exist).
Problems:

1. When sending more than one email synchronously we can't send emails following the one that failed. We have to sleep(x) where x >= 60sec. (of course we have to handle the TransportException thrown by invalid email but this is another topic)
2. When using Messenger and async emails we don't have to worry about handling TransportException because invalid message will be sent back to the queue however the worker cannot consume another messages for the next 60 seconds. Also logs will be flooded with exceptions because in this 60s window a lot of messages could be tried.

This PR permits to specify a retry period using a new DNS option `retry_period` like `MAILER_DSN="roundrobin(postmark+api://ID@default sendgrid+smtp://KEY@default)?retry_period=15"`

### CODE REVIEW

**Comment by sdespont** [comment]
Any chance to see this PR merged in 7.2 ?

**Comment by sdespont** [comment]
Is there anything more you'd like to do before reviewing this PR? Let me know what you think.

**Comment by OskarStark** [comment]
It looks like your commiter email is not associated with your GitHub account. You may want to change that

**Comment by sdespont** [comment]
Thanks, but how can you see that? And is it a problem to review the PR?

**Comment by OskarStark** [comment]
image

There is this GitHub Pictogramm

**Comment by sdespont** [comment]
OK, I don't know why. Is this blocking the review? I don't really care whether I get credit for this PR or not.

File: src/Symfony/Component/Mailer/Transport.php [hunk 1]
```diff
@@ -115,6 +116,14 @@ private function parseDsn(#[\SensitiveParameter] string $dsn, int $offset = 0):
             'roundrobin' => RoundRobinTransport::class,
         ];
 
+        $parsedUrl = parse_url($dsn);
+        parse_str($parsedUrl['query'] ?? '', $query);
+        if (isset($query['retry_period'])) {
+            $retryPeriod = min((int)$query['retry_period'], 60);
+        } else {
+            $retryPeriod = 60;
+        }
```
Comment (MrYamous) [inline src/Symfony/Component/Mailer/Transport.php]:
```suggestion
        $retryPeriod = min((int)($query['retry_period'] ?? 60), 60);
```
WDYT about this shorter syntax ?

**Comment by sdespont** [comment]
@MrYamous Thanks, that's a good idea. Hope this PR will be accepted one day

**Review by fabpot — APPROVED** [review]
I've simplified the implementation in a second commit

**Comment by fabpot** [comment]
Thank you @sdespont.
