### PR TITLE
[Security/Http] Hash Persistent RememberMe token

### LINKED ISSUE #27910: RememberMe token should be hashed in the database
**Symfony version(s) affected**: any (since 2.0)

**Description**  
Symfony security supports two different types of rememberme cookies. Persistent rememberme tokens are stored in the database to prevent identity theft. They store a _series_ (sort of like a username for your token) and the _token_ (sort of your password). For each series/username, the token is changed on every successful rememberme login.

If someone get's access to a database dump for any reason, he can possibly manually add a rememberme cookie to his browser and be authenticated by Symfony automatically. To prevent such attach, it is recommended to hash the token value in the database (see [How to Secure Long-Term Authentication](https://paragonie.com/blog/2015/04/secure-authentication-php-with-long-term-persistence#secure-remember-me-cookies) article by Paragon IE). 

This is currently not done in Symfony, and adding it would generally improve security.

**How to reproduce**  
This is more of a theoretical issue in the security implementation, reproducing it would require manipulating your browser cookies.

**Possible Solution**  
The `PersistentTokenBasedRememberMeServices` implementation should be adjusted to store hashed passwords and authenticate for them.

**Additional context**  
I'm very much willing to create a PR for this if the Symfony security experts agree that things should be changed (and for which version). We also need to decide on whether all existing rememberme cookies will become invalid after this implementation or we should continue to support unencrypted database values (for until the user has logged in once and the token is updated).

### PR DESCRIPTION
**Pull request by guillbdx**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #27910
| License       | MIT
| Doc PR        | Not sure this enhancement needs documentation

The purpose of this PR is to enhance the Remember Me persistent token feature: instead of storing cleared token value in DB, the values will be hashed. 
To make sure that existing remember me cookies will keep being valid after this change, we prefix the new token values with 'hash_'. In case the token value doesn't match this prefix, we keep validating it the old way.

### CODE REVIEW

**Comment by lyrixx** [comment]
You need random data in the hash (nonce) to make the secret unknowable.
I would use the password API or the libsodium API for this use case.

**Comment by chalasr** [comment]
SHA256 seems good enough as per https://github.com/symfony/symfony/issues/27910#issuecomment-419451167

File: src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php [hunk 1]
```diff
@@ -29,6 +30,8 @@
  */
 class PersistentTokenBasedRememberMeServices extends AbstractRememberMeServices
 {
+    private const HASHED_TOKEN_PREFIX = 'hash_';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php]: Should we use `sha256_` as prefix, for the day we'll choose another algo?

File: src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php [hunk 2]
```diff
@@ -66,7 +69,7 @@ protected function processAutoLoginCookie(array $cookieParts, Request $request)
         list($series, $tokenValue) = $cookieParts;
         $persistentToken = $this->tokenProvider->loadTokenBySeries($series);
 
-        if (!hash_equals($persistentToken->getTokenValue(), $tokenValue)) {
+        if (!$this->isTokenValueValid($tokenValue, $persistentToken)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php]: $tokenValue can stay last :)

File: src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php [hunk 3]
```diff
@@ -125,4 +128,18 @@ protected function onLoginSuccess(Request $request, Response $response, TokenInt
...
     }
+
+    private function generateHash(string $tokenValue): string
+    {
+        return self::HASHED_TOKEN_PREFIX.hash_hmac('sha256', $tokenValue, $this->getSecret());
+    }
+
+    private function isTokenValueValid(string $tokenValue, PersistentTokenInterface $persistentToken): bool
+    {
+        if (self::HASHED_TOKEN_PREFIX === substr($persistentToken->getTokenValue(), 0, \strlen(self::HASHED_TOKEN_PREFIX))) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php]: We use strpos() in similar situations. The other option is strncmp(). Using substr() leads to memcopies, which are better avoided when possible.

**Review by nicolas-grekas — COMMENTED** [review]
Don't miss adding some tests :)

File: src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php (hunk 1 above)
Comment (guillbdx) [reply src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php]: Sure. Updated.

File: src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php (hunk 2 above)
Comment (guillbdx) [reply src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php]: Yes, done.

File: src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php (hunk 3 above)
Comment (guillbdx) [reply src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php]: Ok, updated with strpos().

File: src/Symfony/Component/Security/Http/Tests/RememberMe/PersistentTokenBasedRememberMeServicesTest.php [hunk 4]
```diff
@@ -338,4 +343,13 @@ protected function getProvider()
 
         return $provider;
     }
+
+    protected function generateHash(string $tokenValue): string
+    {
+        $service = $this->getService();
+        $r = new \ReflectionMethod($service, 'generateHash');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Http/Tests/RememberMe/PersistentTokenBasedRememberMeServicesTest.php]: It'd be more robust to compy/paste the implementation instead of using reflection:
that way, if the implementation diverges from the test, we'll see a red flag.

**Comment by guillbdx** [comment]
> Don't miss adding some tests :)

I've updated `PersistentTokenBasedRememberMeServicesTest`, so it now uses tokens with hashed values.
I also annotated the `testAutoLogin` test to be run twice: once with a hashed token value, and once with a clear token value, to make sure the old way keeps working.

File: src/Symfony/Component/Security/Http/Tests/RememberMe/PersistentTokenBasedRememberMeServicesTest.php (hunk 4 above)
Comment (guillbdx) [reply src/Symfony/Component/Security/Http/Tests/RememberMe/PersistentTokenBasedRememberMeServicesTest.php]: Ok, updated. (i hardcoded the prefix in test instead of using the constant, for the same reason)

**Review by nicolas-grekas — APPROVED** [review]
LGTM thanks

**Review by chalasr — APPROVED** [review]
The Security CHANGELOG needs to be updated.

**Review by wouterj — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @guillbdx.
