### PR TITLE
[HttpKernel] allow boolean argument support for MapQueryString

### LINKED ISSUE #53616: MapQueryString doesn't support string value for boolean type
### Symfony version(s) affected

6.3, 6.4, 7.0

### Description

MapQueryString attribute fails parsing string value for boolean type.

Problem is nicely described in this issue https://github.com/symfony/symfony/issues/42715 
But in this case we know for sure that it's a string (just like the CSV and XML types in [AbstractObjectNormalizer.php](https://github.com/symfony/symfony/blob/e34cd7dd2c6d0b30d24cad443b8f964daa841d71/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L432-L441)

Don't know if it's a bug or a feature.

### How to reproduce

I expect the following to be false, but true is returned.

Request Url
```
https://example.com?myBoolean=false
```
DTO
```
<?php

readonly class MyDTO 
{
    public function __construct(
        public bool $myBoolean
    )    
}
```
Controller
```
<?php

use Symfony\Component\HttpKernel\Attribute\MapQueryString;
use Symfony\Component\Routing\Annotation\Route;

class MyController
{
    #[Route('/')]
    public function __invoke(
        #[MapQueryString]
        MyDTO $dto
    ) {
        dd($dto->myBoolean);
    }
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Jean-Beru**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #53616
| License       | MIT

~~Add a `$filters` argument to the `MapQueryString` attribute to allow filtering parameters using `filter_var` function. It will be useful to cast "false", "0", "no" or "off" to `false` before denormalizing the request data.~~

**EDIT**

Add a `AbstractNormalizer::FILTER_BOOL` context option to cast to a boolean using the `filter_var` function with the `\FILTER_VALIDATE_BOOL` filter (see https://www.php.net/manual/fr/filter.filters.validate.php).

`MapQueryString` will use this context option when denormalizing the query string. 
`MapPayload` also but only with data coming from a form.

See the relative comment: https://github.com/symfony/symfony/pull/54153#issuecomment-1978475173

Example:
```php
final readonly class SearchDto
{
    public function __construct(public ?bool $restricted = null)
    {
    }
}

final class MyController
{
    #[Route(name: 'search', path: '/search')]
    public function __invoke(#[MapQueryString] SearchDto $search): Response
    {
        // /search?restricted=
        // "true", "1", "yes" and "on" will be cast to true
        // "false", "0", "no", "off" and "" will be cast to false
        // other will be cast to null
    }
}
```

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I'm not sure how useful this could be: the query string can be a tuple of many different type of values, while this works only of all properties of the DTO are of the same type, isn't it?

**Comment by Jean-Beru** [comment]
> I'm not sure how useful this could be: the query string can be a tuple of many different type of values, while this works only of all properties of the DTO are of the same type, isn't it?

The associative array allows to define which parameter is concerned. `#[MapQueryString(filters: ['restricted' => \FILTER_VALIDATE_BOOL])]` will only apply this filter on the `restricted` parameter.

TBH, I think that this mapping will mainly be used to cast string to boolean since other types (ex: string to int) are already handled by the Serializer.

**Comment by nicolas-grekas** [comment]
Ah OK, so "restricted" is the name of the property. This wasn't obvious to me.

It's a bit of a shame that a type that is already clearly described on the DTO need to be specified again somewhere else.

This maps to the serializer component, which could have a mode to do the cast on its own, don't you think?

**Comment by Jean-Beru** [comment]
> It's a bit of a shame that a type that is already clearly described on the DTO need to be specified again somewhere else.

I totally agree.

> This maps to the serializer component, which could have a mode to do the cast on its own, don't you think?

We could pass `[FILTER_BOOL => value]` in the context to apply this filter. Should this filter be applied by default when using `#[MapQueryString]` ? Current request parameters like `active=false` will be cast to `false` in place of `true`.

**Comment by nicolas-grekas** [comment]
Yes, that'd be better IMHO. Dunno if bool is the only concerned type of if other ones could benefit from using filter_var to do the casting. Would need to be investigated.
Then yes, I would enable that flag for MapQueryString, but also for MapRequestPayload *when the payload is a form submission*.

**Comment by Jean-Beru** [comment]
I updated this PR and its description this way with a new `AbstractNormalizer::FILTER_BOOL` context option.

File: src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php [hunk 1]
```diff
@@ -524,6 +531,23 @@ final protected function applyCallbacks(mixed $value, object|string $object, str
...
+    {
+        if (!($context[self::FILTER_BOOL] ?? false)) {
+            return $value;
+        }
+
+        if (!($parameterType = $parameter->getType()) instanceof \ReflectionNamedType || 'bool' !== $parameterType->getName()) {
+            return $value;
+        }
+
+        if (null === ($filteredData = filter_var($value, \FILTER_VALIDATE_BOOL, \FILTER_NULL_ON_FAILURE))) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php]:
```suggestion
        return filter_var($value, \FILTER_VALIDATE_BOOL, \FILTER_NULL_ON_FAILURE) ?? $value;
```

**Review by nicolas-grekas — APPROVED** [review]
I like that :)

**Review by fabpot — APPROVED** [review]

File: src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php [hunk 2]
```diff
@@ -524,6 +531,23 @@ final protected function applyCallbacks(mixed $value, object|string $object, str
...
+            return $value;
+        }
+
+        if (!($parameterType = $parameter->getType()) instanceof \ReflectionNamedType || 'bool' !== $parameterType->getName()) {
+            return $value;
+        }
+
+        return filter_var($value, \FILTER_VALIDATE_BOOL, \FILTER_NULL_ON_FAILURE) ?? $value;
+            return $value;
+        }
```
Comment (fabpot) [inline src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php]: Looks wrong :)

**Review by fabpot — CHANGES_REQUESTED** [review]

**Comment by fabpot** [comment]
Thank you @Jean-Beru.

**Comment by antoniovj1** [comment]
Will this fix apply to Symfony 7.0?

**Comment by nicolas-grekas** [comment]
It's not a fix but a new feature, so 7.1

**Comment by antoniovj1** [comment]
Makes sense, thanks!
