### PR TITLE
[DependencyInjection] Log every build parameter removed during compilation

### LINKED ISSUE #63387: Build parameter `.serializer.named_serializers` is removed without logging
### Symfony version(s) affected

8.0

### Description

The parameter `.serializer.named_serializers` is according to the naming convention (parameter name starts with a dot) a build parameter which should be available only during the container compilation and is therefore removed past compilation of the container. (Edit note: This is actually happening, contrary to previous assumptions.)

However, the parameter is apparently removed from the container without logging. `var/cache/dev/App_KernelDevDebugContainerCompiler.log` does not contain a corresponding log entry (expecting `Removing build parameter ".serializer.named_serializers"` ) unlike other build parameters (e.g. `.kernel.config_dir`).

### How to reproduce

Execute `php bin/console cache:clear` and inspect `var/cache/dev/App_KernelDevDebugContainerCompiler.log`

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ousamabenyounes**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63387
| License       | MIT

`RemoveBuildParametersPass` only logged `Removing build parameter "%s"` for dot-prefixed parameters that it actually removed from the parameter bag. When instantiated with `preserveArrays = true` — the variant registered at priority `-2048` in `PassConfig::afterRemovingPasses` — array-valued build parameters (e.g. `.serializer.named_serializers`, `.doctrine.orm.proxy_dir`, …) were skipped silently. No log entry appeared in `var/cache/<env>/App_Kernel…ContainerCompiler.log`, yet the dumped container still drops those parameters via `PhpDumper` because it excludes every name starting with `.`.

This PR emits a log line for every dot-prefixed parameter seen by the pass, with a message that accurately reflects what happens to it:

- scalar parameters are removed from the bag → `Removing build parameter "%s".` (unchanged)
- array parameters preserved for placeholder resolution → `Keeping array build parameter "%s" for placeholder resolution.` (new)

The actual removal logic is unchanged: scalar parameters are still removed here, arrays are still preserved so placeholder resolution keeps working.

### Before

```
…
RemoveBuildParametersPass: Removing build parameter ".container.dumper.inline_factories".
RemoveBuildParametersPass: Removing build parameter ".container.dumper.inline_class_loader".
# <-- no entry for .serializer.named_serializers despite it being excluded from the dumped container
```

### After

```
…
RemoveBuildParametersPass: Removing build parameter ".container.dumper.inline_factories".
RemoveBuildParametersPass: Removing build parameter ".container.dumper.inline_class_loader".
RemoveBuildParametersPass: Keeping array build parameter ".serializer.named_serializers" for placeholder resolution.
```

Test coverage extended in `RemoveBuildParametersPassTest::testArrayBuildParametersArePreservedWhenConfigured` to assert that scalar dot-prefixed parameters are logged with `Removing build parameter …` and preserved array ones with `Keeping array build parameter … for placeholder resolution.`.

Ran `./phpunit src/Symfony/Component/DependencyInjection/Tests/Compiler/` locally on `6.4`: 520 tests pass. `RemoveBuildParametersPassTest` alone: 3 tests / 13 assertions.

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/RemoveBuildParametersPassTest.php [hunk 1]
```diff
@@ -46,6 +46,13 @@ public function testArrayBuildParametersArePreservedWhenConfigured()
         $this->assertTrue($builder->hasParameter('.array'), '".array" parameter must be preserved.');
         $this->assertSame(['baz' => 'qux'], $builder->getParameter('.array'), '".array" parameter must retain its value.');
         $this->assertSame(['.scalar' => 'Bar'], $pass->getRemovedParameters(), 'Only ".scalar" parameter must be returned as removed.');
+
+        // Regression test for symfony/symfony#63387: every dot-prefixed build
```
Comment (GromNaN) [inline src/Symfony/Component/DependencyInjection/Tests/Compiler/RemoveBuildParametersPassTest.php]: We don't refer to issues in the code. The code and comments should be self-explanatory.

File: src/Symfony/Component/DependencyInjection/Compiler/RemoveBuildParametersPass.php [hunk 2]
```diff
@@ -34,12 +34,18 @@ public function process(ContainerBuilder $container)
...
                 $this->removedParameters[$name] = $value;
-
                 $parameterBag->remove($name);
-                $container->log($this, \sprintf('Removing build parameter "%s".', $name));
             }
+            // Array build parameters are kept in the container during compilation so
+            // placeholders can still resolve, but they are excluded from the dumped
+            // container. Log every dot-prefixed parameter so compilation traces
+            // record every build parameter consistently, not just the scalar ones.
+            $container->log($this, \sprintf('Removing build parameter "%s".', $name));
```
Comment (GromNaN) [inline src/Symfony/Component/DependencyInjection/Compiler/RemoveBuildParametersPass.php]: The log message "Removing build parameter" is misleading for array parameters when `$preserveArrays` is `true`: they are explicitly **not** removed by this pass — they stay in the parameter bag for placeholder resolution. Could the message be something like "Keeping array build parameter "%s" for placeholder resolution." instead?

**Review by GromNaN — CHANGES_REQUESTED** [review]
Thanks for the fix, the logging gap for array build parameters is indeed confusing!

**Comment by ousamabenyounes** [comment]
@GromNaN thanks for the review! I've addressed both comments in a96b2c3:
- Removed the issue reference from the test comment.
- Used a distinct log message `Keeping array build parameter "%s" for placeholder resolution.` for preserved array parameters, as you suggested.

Could you take another look when you have a moment?

**Comment by GromNaN** [comment]
Could you update the PR description with the new log message. Thanks

**Comment by ousamabenyounes** [comment]
@GromNaN done — PR description updated with the new `Keeping array build parameter "%s" for placeholder resolution.` log message in both the summary and the Before/After example.

**Review by GromNaN — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @ousamabenyounes.
