### PR TITLE
[Cache] Check if phpredis version is compatible with stream parameter

### LINKED ISSUE #41110: [symfony/cache] Older versions of redis are not supported
**Symfony version(s) affected**: symfony/cache v4.4.22

**Description**
After updating from symfony/cache v4.4.21 to v4.4.22, Redis suddenly stopped working. It doesn't show any message other than "Redis connection "HERE_IS_CONNECTION_STRING" failed" (it should add an error message in the end of this message).

After debugging I found out that our version of php-redis (which is 4.2.0-1) accepts 6 parameters in connect() function, while symfony/cache v4.4.22 passes 7 parameters (added TLS support). 7th parameter was added with php-redis 5.3.0 around 1 year ago.

With this change in Symfony\Component\Cache\Traits\RedisTrait, backward compability is gone. 

For example, the stable version of php-redis for Debian is set to 4.2.0-1.

**How to reproduce**
1. Install php-redis in version less than 5.3.0.
2. Run RedisAdapter::createConnection($dsn)

**Possible Solution**
Maybe we should check for php-redis version before adding 7th argument into $redis->connect()?

### PR DESCRIPTION
**Pull request by nicolassing**
| Q             | A
| ------------- | ---
| Branch?            | 5.2 
| Bug fix?            | yes
| New feature?   | no 
| Deprecations? | no
| License            | MIT

If you use phpredis <5.3.0, you can't connect to Redis since symfony/cache 5.2.7

Fixes #41110

### CODE REVIEW

File: src/Symfony/Component/Cache/Traits/RedisTrait.php [hunk 1]
```diff
@@ -189,7 +189,11 @@ public static function createConnection($dsn, array $options = [])
                 }
 
                 try {
-                    @$redis->{$connect}($host, $port, $params['timeout'], (string) $params['persistent_id'], $params['retry_interval'], $params['read_timeout'], ['stream' => $params['ssl'] ?? null]);
+                    $parameters = [$host, $port, $params['timeout'], (string) $params['persistent_id'], $params['retry_interval'], $params['read_timeout']];
+                    if (true === version_compare('5.3.0', phpversion('redis'), '<=')) {
```
Comment (stof) [inline src/Symfony/Component/Cache/Traits/RedisTrait.php]: `true === ` can be removed. There is no need to turn the boolean into itself.

**Comment by nicolas-grekas** [comment]
The issue happens on 4.4 also apparently. Can you please rebase+target for 4.4?
There might be another line to patch apparently, see https://github.com/symfony/symfony/commit/f8518ca16a1f2ccb04d750f6a5a0128e3b7ebd0e

/cc @jackthomasatl FYI

**Comment by pwbzh** [comment]
Hello, I have the same problem when I update to Symfony `v4.4.22` from `v4.4.21`.
I fallback to `v4.4.21`.

Redis version: `5.0.7`
PHP version : `7.4.3`

**Comment by nicolas-grekas** [comment]
Thank you @nicolassing.
