### PR TITLE
[FrameworkBundle] don't require fake notifier transports to be installed as non-dev dependencies

### LINKED ISSUE #58929: Installing fake-sms-notifier as a dev packages does not work
### Symfony version(s) affected

7.1.8

### Description

I wanted to use the fake notifier during testing, but don't need it on the production site, so I installed it as a `--dev` package… then spent about 45 mins & lots of step debugging, trying to work out why it wasn't working.

### How to reproduce

Install the package using composer require --dev symfony/fake-sms-notifier.

Try to send an SMS notification.

### Possible Solution

Is it possible to allow this package to be installed just in dev, since it's a primarily development style package?

Or at least lets update the docs to make this clear.  Happy to PR, but if we can make it support dev only, all the better.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58929
| License       | MIT

### CODE REVIEW

**Comment by smnandre** [comment]
🙇

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -2891,20 +2889,26 @@ private function registerNotifierConfiguration(array $config, ContainerBuilder $
             $container->removeDefinition($classToServices[NotifierBridge\Mercure\MercureTransportFactory::class]);
         }
 
-        if (ContainerBuilder::willBeAvailable('symfony/fake-chat-notifier', NotifierBridge\FakeChat\FakeChatTransportFactory::class, ['symfony/framework-bundle', 'symfony/notifier', 'symfony/mailer'])) {
-            $container->getDefinition($classToServices[NotifierBridge\FakeChat\FakeChatTransportFactory::class])
+        // don't use ContainerBuilder::willBeAvailable() as these are not needed in production
+        if (class_exists(NotifierBridge\FakeChat\FakeChatTransportFactory::class)) {
```
Comment (fabpot) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: What about using a `use` statement and simplify here to:

```suggestion
        if (class_exists(FakeChatTransportFactory::class)) {
```

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.
