### PR TITLE
[Console] Make error message more verbose

### LINKED ISSUE #38904: [Console] Too many arguments message contains an incorrect number of missing arguments
**Symfony version(s) affected**: 5.1.8 (and earlier)

**Description**  

Whenever a Symfony Console command is called with too many arguments, a "Too many arguments" error is shown on the CLI. This message also states _which_ arguments are expected. But this message always contains `"command"` as an extra argument. This can be confusing for the user, as the reported number of arguments is one off with what it should be.

**How to reproduce**  

Install the Symfony skeleton and run the following command:

```
bin/console secrets:list foo
```

It shows the following message:

```
Too many arguments, expected arguments "command".
```

This is incorrect, as the command itself expects no arguments at all.

Similarly, the command

```
bin/console secrets:set foo bar baz
```

shows the message:

```
Too many arguments, expected arguments "command" "name" "file".
```

Here I would have expected a message stating that that `"name"` and `"file"` are the expected arguments, but not `"command"`.

**Possible Solution**  

The message is thrown on [line 139 of src/Symfony/Component/Console/Input/ArgvInput.php](https://github.com/symfony/symfony/blob/v5.1.8/src/Symfony/Component/Console/Input/ArgvInput.php#L169).

Here it can be seen that keys of the `$this->definition->getArguments()` array are printed.

The simplest solution to fix this seems to remove the first key of the array when creating the exception message.

### PR DESCRIPTION
**Pull request by Nyholm**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #38904
| License       | MIT
| Doc PR        | no

This will make the error message a bit more verbose when you are using too many or too few arguments.

### CODE REVIEW

File: src/Symfony/Component/Console/Input/ArgvInput.php [hunk 1]
```diff
@@ -165,11 +165,25 @@ private function parseArgument(string $token)
         // unexpected argument
         } else {
             $all = $this->definition->getArguments();
+            $symfonyCommandName = null;
+            if (($inputArgument = $all[$key = array_key_first($all)] ?? null) && 'command' === $inputArgument->getName()) {
+                $symfonyCommandName = $this->tokens[0] ?? null;
```
Comment (jderusse) [inline src/Symfony/Component/Console/Input/ArgvInput.php]: hmm, what if people use short command name ? like `d:m:m` instead of `doctrine: migration:migrate`
Just wondering what should be the output...

Comment (Nyholm) [reply src/Symfony/Component/Console/Input/ArgvInput.php]: Good question. The output would be: 

```
Too many arguments to "d:m:m" command, expected arguments "version".  
```

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Component/Console/Input/ArgvInput.php (hunk 1 above)
Comment (stof) [inline src/Symfony/Component/Console/Input/ArgvInput.php]: The command name is not always `$this->tokens[0]`. `bin/console -v secrets:list` will have `-v` as `$this->tokens[0]`

Comment (stof) [reply src/Symfony/Component/Console/Input/ArgvInput.php]: You should use `$this->arguments['command'][0]` instead (when we reach this error, we know that the command argument has already been parsed)

Comment (Nyholm) [reply src/Symfony/Component/Console/Input/ArgvInput.php]: Awesome. 
You are correct. I've updated the PR. 

```
❯ bin/console -v secrets:list foobar

In ArgvInput.php line 186:
                                                                   
  [Symfony\Component\Console\Exception\RuntimeException]           
  No arguments expected for "secrets:list" command, got "foobar".  

```

**Review by yceruto — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Nyholm.

**Comment by Nyholm** [comment]
Thank you for all reviews and for merging.
