### PR TITLE
[RFC] Fixing Deprecation Warnings

### LINKED ISSUE #14899: CSRF deprecation, upgrade docs do not state how to upgrade CSRF service
The dev bar outputs the following in the tab for "logs".

DEPRECATED - The Symfony\Component\Form\Extension\Csrf\CsrfProvider\CsrfProviderAdapter class is deprecated since version 2.4 and will be removed in version 3.0. Use the Symfony\Component\Security\Csrf\CsrfTokenManager class instead.

It is not documented anywhere I can see how to deal with this. I upgraded a project from 2.5 to 2.7 and now I get a lot of these errors. All of which I was able to solve, but the CSRF token issue is a mystery.

The default configuration has this
```
        <service id="form.csrf_provider" class="Symfony\Component\Form\Extension\Csrf\CsrfProvider\CsrfTokenManagerAdapter">
            <argument type="service" id="security.csrf.token_manager" />
        </service>
```

But the file Symfony\Component\Form\Extension\Csrf\CsrfProvider\CsrfTokenManagerAdapter states
```
    public function getTokenManager($triggerDeprecationError = true)
    {
        if ($triggerDeprecationError) {
            trigger_error('The '.__METHOD__.' method is deprecated since version 2.4 and will be removed in version 3.0. Use the Symfony\Component\Security\Csrf\CsrfTokenManager class instead.', E_USER_DEPRECATED);
        }

        return $this->tokenManager;
    }

    /**
     * {@inheritdoc}
     */
    public function generateCsrfToken($intention)
    {
        trigger_error('The '.__METHOD__.' method is deprecated since version 2.4 and will be removed in version 3.0. Use the Symfony\Component\Security\Csrf\CsrfTokenManager class instead.', E_USER_DEPRECATED);

        return $this->tokenManager->getToken($intention)->getValue();
    }
```

Only things I can find online are suggestions to disable warnings in my php.ini etc. Considering I solved the other issues surely there is a way to appropriate fix this issue while upgrading also?

These warnings are incredibly invasive BTW, not good for DX.

### PR DESCRIPTION
**Pull request by reecefowell**
This PR address an issue that causes Symfony to vomit E_DEPRECATED warnings everywhere.

``` markdown
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #14899
| License       | MIT
```

Fixes #14899

### CODE REVIEW

**Comment by perk11** [comment]
👍 had numerous deprecated warnings after upgrading to 2.7 and this PR solved all of them.

**Comment by xabbuh** [comment]
The deprecation warnings are triggered intentionally to let you know what you need to change in your code to be forward compatible with Symfony 3.0.

You *could* silence them by changing your project's `error_reporting` level, but I'd rather update your code.

**Comment by nicolas-grekas** [comment]
This PR may be a good idea in fact don't you think?

**Comment by elnur** [comment]
The most profound PR I've ever seen. A must merge. :+1:

**Comment by xabbuh** [comment]
@nicolas-grekas Not sure if I understand. Which issue would this change actually solve?

**Comment by nicolas-grekas** [comment]
It switches deprecation notices from opt-out to opt-in

**Comment by xabbuh** [comment]
Yeah, but I'd that really a good idea? I bet that many people then will never know about this and that they will be surprised when their apps break on Symfony 3.0. Not sure if that's a good experience either.

**Comment by reecefowell** [comment]
I think it is a good idea. @deprecated tags are sufficient, but calling trigger_error() is very shouty.

Googling most of the deprecated errors that come out result in most cases with the people discussing end suggesting and / or agreeing that muting E_DEPRECATED in php.ini is the best solution.

If the intent is to get people to prepare for 3.0 then, well people aren't. Instead they are just muting the warnings. Further more, for upgraders, seeing the messages for the first time, diagnosing / solving them the correct way is very difficult as google has little to offer in the way of answers.

Perhaps some of the deprecated calls don't actually have future ready implementations in place yet. I believe this was the case with the Form components OptionResolverInterface, which my IDE informs me was deprecated in (I think it was) 2.5 or so, but no alternative was provided until something like 2.6 (with OptionResolver).

**Comment by nicolas-grekas** [comment]
Still thinking about it, I really like the idea.
Upgrading to 3.0 is also an opt in, the upgrade path is clear.

I'm :+1:
Reopening to see what others @symfony/deciders think

**Comment by nicolas-grekas** [comment]
@reecefowell can you please enhance the commit message?

File: src/Symfony/Component/HttpFoundation/Tests/JsonResponseTest.php [hunk 1]
```diff
@@ -224,7 +224,7 @@ class JsonSerializableObject implements \JsonSerializable
     {
         public function jsonSerialize()
         {
-            trigger_error('This error is expected', E_USER_WARNING);
+            @trigger_error('This error is expected', E_USER_WARNING);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Tests/JsonResponseTest.php]: This one is not a deprecation, please revert and ensure that you silence only deprecations

**Comment by stof** [comment]
@nicolas-grekas are these deprecation warnings still reported in the logs after being muted or no ?

And does the silencing add some overhead or no ?

**Comment by nicolas-grekas** [comment]
Yes, the debug handler ignores silencing for deprecations. The overhead is
not significant at all.

**Comment by fabpot** [comment]
ping @symfony/deciders 

If we agree on this one, I'd like to merge ASAP for at least two reasons:

* I want to release 2.7.1 ASAP
* Maintaining such a large patch is going to be difficult over time.

**Comment by Tobion** [comment]
So this only changes that the deprecation warnings are ignored in production, or?

**Comment by nicolas-grekas** [comment]
Yes, by default

File: src/Symfony/Component/Debug/Tests/DebugClassLoaderTest.php [hunk 2]
```diff
@@ -170,7 +170,7 @@ public function testDeprecatedSuper($class, $super, $type)
     {
         set_error_handler('var_dump', 0);
         $e = error_reporting(0);
-        trigger_error('', E_USER_DEPRECATED);
+        @trigger_error('', E_USER_DEPRECATED);
```
Comment (reecefowell) [inline src/Symfony/Component/Debug/Tests/DebugClassLoaderTest.php]: Why is this even here? It doesn't have a message. Presumably the intention is to pass to the $e var to trigger_error?

Comment (nicolas-grekas) [inline src/Symfony/Component/Debug/Tests/DebugClassLoaderTest.php]: It's a trick to reset the state of error_get_last() a few lines below. Silencing should be reverted here, as it's already done on line 172.

File: src/Symfony/Component/Debug/Tests/DebugClassLoaderTest.php [hunk 3]
```diff
@@ -200,7 +200,7 @@ public function testDeprecatedSuperInSameNamespace()
     {
         set_error_handler('var_dump', 0);
         $e = error_reporting(0);
-        trigger_error('', E_USER_NOTICE);
+        @trigger_error('', E_USER_NOTICE);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Debug/Tests/DebugClassLoaderTest.php]: To be reverted, this is not a deprecation, same below

File: src/Symfony/Component/Process/Tests/AbstractProcessTest.php [hunk 4]
```diff
@@ -24,7 +24,7 @@
 {
     public function testThatProcessDoesNotThrowWarningDuringRun()
     {
-        @trigger_error('Test Error', E_USER_NOTICE);
+        @@trigger_error('Test Error', E_USER_NOTICE);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Process/Tests/AbstractProcessTest.php]: Double silence here

**Comment by iltar** [comment]
So how would I turn on deprecation notices now?

**Comment by nicolas-grekas** [comment]
By adding a user land error handler, like the one provided by e.g. the debug component

**Comment by reecefowell** [comment]
Comments addressed in code, also tests are now passing. Somehow though I seem to have broken fabbot.io.

The patch just gave me this
```
curl http://fabbot.io/patch/symfony/symfony/14900/eb261d45b038f9af47a92b4e6b602bcf8a853816/cs.diff | patch -p0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8717  100  8717    0     0  20591      0 --:--:-- --:--:-- --:--:-- 20607
patch: **** Only garbage was found in the patch input.
```

So I applied the changes manually, but I guess maybe because I pushed another fix while fabbot.io was still running it broke it this time around.

Fabbot.io was talking about code I never touched though. So I guess those problems were already there.

Other than that. Good to go.

**Comment by weaverryan** [comment]
To summarize a few questions people had (that I also had):

A) Do you still get deprecated warnings in the web debug toolbar? YES

B) Do deprecation warnings still show up in the logs? NO

Does this have any other side effects?

If there are no other side effects, I'm +1. We can add something to the "how to get rid of deprecation warnings" section of the docs to show people how to hook up an error handler to log the deprecation warnings.

**Comment by fabpot** [comment]
Ready to be merged?

**Comment by nicolas-grekas** [comment]
To me, yes

**Comment by phansys** [comment]
Maybe I missunderstood the question or the answer, but I haven't clear enough what happen with deprecation warnings in logs.

@stof's question:
>are these deprecation warnings still reported in the logs after being muted or no ?

@nicolas-grekas' response:
>Yes, the debug handler ignores silencing for deprecations.

@weaverryan's assumption:
>Do deprecation warnings still show up in the logs? NO

**Comment by nicolas-grekas** [comment]
Ryan was talking about php logs, stof about logs in the sf toolbar

**Comment by phansys** [comment]
Nice! Thanks for the clarification @nicolas-grekas.

**Comment by Tobion** [comment]
Would it not be better to change the production error handler instead to not log by default if that is what we want? Triggering deprecations and at the same time silence them seems like a hack.

**Comment by nicolas-grekas** [comment]
@tobion this PR solves a real issue/pain users experiment with 2.7.: they must opt-out from deprecation notices. If we think this is required then we should not merge this PR.
If we think the deprecations should be opt-in, as would be migrating 3.0, then this PR is the right one.
Nobody but me voted here. Please do @symfony/deciders

**Comment by nicolas-grekas** [comment]
@reecefowell please rebase

**Comment by lsmith77** [comment]
I agree that this should have been opt-in rather than opt-out. I do not know if there is a more elegant approach as I agree with @Tobion it seems hacky to use ``@trigger_error()``.

**Comment by nicolas-grekas** [comment]
I understand how you can see this as a hack. There is an other consideration that makes me think this is really the best: performance. We could wrap the implementation of triggering "opt-in deprecation notices" behind some more semantic interface. But that would add overhead to something that needs to be as fast as possible. This is not a micro-optim when this can be called thousands of times.
Thus this raw-bare-metal-php implementation that may look hacky, but is just the right implementation for our needs. At least that's my humble opinion :)

File: UPGRADE-2.7.md [hunk 5]
```diff
@@ -5,7 +5,7 @@ Global
 ------
 
  * `E_USER_DEPRECATED` warnings -
-   `trigger_error('... is deprecated ...', E_USER_DEPRECATED)` -
+   `@trigger_error('... is deprecated ...', E_USER_DEPRECATED)` -
    are now triggered when using all deprecated functionality.
    To avoid filling up error logs, you may need to add
```
Comment (nicolas-grekas) [inline UPGRADE-2.7.md]: This sentence looks wrong now, the UPGRADE needs an update

**Comment by fabpot** [comment]
I'm going to merge this today if nobody vote otherwise.

**Comment by jakzal** [comment]
:+1: as I see people struggling with deprecation messages, especially in cli. However, we should provide clear instructions on how to enable them.

**Comment by stof** [comment]
:+1:

It also means we are much less intrusive for other libraries relying on Symfony 2.x

**Comment by matthias-chlechowitz** [comment]
:+1:

**Comment by aitboudad** [comment]
:+1:

**Comment by xabbuh** [comment]
I am still not fully convinced. How would people now see the stack trace for a triggered deprecation if it is not contained in the logs? The debug toolbar doesn't provide one.

**Comment by nicolas-grekas** [comment]
Thank you @reecefowell

**Comment by nicolas-grekas** [comment]
@xabbuh we still have to work on better deprecation reporting.
But at least, we can do it quietly now, without hurting users.

**Comment by reecefowell** [comment]
Thanks everyone :)

**Comment by craue** [comment]
Are bundle developers encouraged to do this as well?

**Comment by nicolas-grekas** [comment]
@craue I'd say yes!

**Comment by mmoreram** [comment]
:+1: Good move :)
