### PR TITLE
[DependencyInjection] Ensure deprecation detection does not trigger a PHP error

### LINKED ISSUE #62589: dependency injection 7.4.0 breaks TYPO3
### Symfony version(s) affected

7.4.0

### Description

Since Friday, I noticed that my TYPO3 projects were all breaking.
The reason behind this (i assume) is that the error tolerance of the dependency injection now checks for services that are not being used.

Here is a file from the install tool that has a dependency on the reporting extension.
[typo3/typo3/sysext/install/Classes/Report/EnvironmentStatusReport.php at main · TYPO3/typo3](https://github.com/TYPO3/typo3/blob/main/typo3/sysext/install/Classes/Report/EnvironmentStatusReport.php#L34)
It is always configured as a service:
[typo3/typo3/sysext/install/Configuration/Services.yaml at main · TYPO3/typo3](https://github.com/TYPO3/typo3/blob/main/typo3/sysext/install/Configuration/Services.yaml#L27)
If the reporting extension is not installed, then the service is also never used.

With symfony/dependency-injection:7.3, the service was either never looked into or the error was ignored.
With 7.4, it now is throwing an error.
```
Uncaught TYPO3 Exception Interface "TYPO3\CMS\Reports\StatusProviderInterface" not found
thrown in file /var/www/vendor/typo3/cms-install/Classes/Report/EnvironmentStatusReport.php
in line 34
```

I already found other reports of it: [Neue symfony/dependency-injection Paketversion 7.4 kann TYPO3 Systeme brechen – T3Bootstrap News – TYPO3 Template](https://blog.t3bootstrap.de/2025/11/neue-symfony-dependency-injection-paketversion-7-4-kann-typo3-systeme-brechen/)

And there are many TYPO3 extensions, like the headless and the SEO extension in typo3 that seem to depend on the old behavior, that unused services are never looked at.

### How to reproduce

Install a basic TYPO3 (you don't need to configure it)
```bash
composer create-project "typo3/cms-base-distribution:^13" --prefer-dist --ignore-platform-reqs
cd cms-base-distribution
vendor/bin/typo3 cache:flush
```
This results in 
```
Uncaught TYPO3 Exception Interface "TYPO3\CMS\Reports\StatusProviderInterface" not found
thrown in file /Volumes/Workspace/typo3-test-25-12-01/cms-base-distribution/vendor/typo3/cms-install/Classes/Report/EnvironmentStatusReport.php
in line 34
```

If you then downgrade:
```
composer req -W symfony/dependency-injection:7.3.x --ignore-platform-reqs
vendor/bin/typo3 cache:flush
```

You get the "no database configured", which is expected:
```
In ConnectionPool.php line 138:
                                                                              
  The requested database connection named "Default" has not been configured.  
                                                                              

cache:flush [-g|--group [GROUP]]

```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by bnf**
`Exception Interface "TYPO3\CMS\Reports\StatusProviderInterface" not found`
See https://forge.typo3.org/issues/108349

| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62589
| License       | MIT

The `class_exists` check and the condition `$definition instanceof ChildDefinition` have been swapped with #61215 in order to produce an error if a service is not available.

This error was later relaxed in #61270, but the executing order of the condition kept to be `class_exists` first, then `instanceof`.

That means, if `class_exists` fails with a PHP error (like PHP Fatal Error: Interface "My\Vendor\MyInterface" not found`) affected uses will not see the deprecation, but a fatal error instead.

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/ResolveClassPassTest.php [hunk 1]
```diff
@@ -107,4 +107,26 @@ public function testInvalidClassNameDefinition()
...
+        };
+
+        spl_autoload_register($autoloader);
+
+        $container = new ContainerBuilder();
+        $container->register('Acme\ClassImplementsUnavailableInterface');
+
+        (new ResolveClassPass())->process($container);
+
+        spl_autoload_unregister($autoloader);
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Tests/Compiler/ResolveClassPassTest.php]: this should be in a `finally` block to ensure it is not linked even in case of failure.

Alternatively, define the class in a file that can be loaded through PSR-4, removing the need for this autoloader entirely.

Comment (bnf) [reply src/Symfony/Component/DependencyInjection/Tests/Compiler/ResolveClassPassTest.php]: Ack, done. thanks!

> Alternatively, define the class in a file that can be loaded through PSR-4, removing the need for this autoloader entirely.

I initially tried that – see https://github.com/symfony/symfony/commit/e74ddd97dac4f0b7229ce0c4af5d1cf1c09592e7 – but CI complained about an invalid fixture class then.

File: src/Symfony/Component/DependencyInjection/Compiler/ResolveClassPass.php [hunk 2]
```diff
@@ -29,16 +29,23 @@ public function process(ContainerBuilder $container): void
             ) {
                 continue;
             }
-            if (class_exists($id) || interface_exists($id, false)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/ResolveClassPass.php:32]: can't we keep the existing code flow but use $container->getReflectionClass instead?

Comment (bnf) [reply src/Symfony/Component/DependencyInjection/Compiler/ResolveClassPass.php:32]: I'm not sure I can follow that idea.

While `ContainerBuilder::getReflectionClass()` uses the same condition, it does not catch erors, but only exceptions. That means it can not be used as a drop-in replacement without applying the same safety nets (`catch (\Error)`).

I guess you are concerned about the duplication of calling `class_exists($id) || interface_exists($id, false)` in two modes?

The idea to change the code flow is applied to preserve v7.3 behavior that `class_exists()` may throw when the `$definition` is a `ChildDefinition`. If you consider (I wasn't sure) this to be unnecessary, we could avoid reording the methods and apply the `try…catch` in any case..

WDYT?

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Compiler/ResolveClassPass.php:32]: the $throw argument of getReflectionClass is for this purpose

> does not catch erors, but only exceptions

the code does more (it calls `ClassExistenceResource::isFresh()`), and does deal with this situation, give it a try

**Comment by nicolas-grekas** [comment]
Thank you @bnf.
