### PR TITLE
[HttpFoundation] Check IPv6 is valid before comparing it

### LINKED ISSUE #48049: [Http-Foundation] IpUtils matches IPv6 ::1 with IPv4 0.0.0.0/8
### Symfony version(s) affected

6.1.x

### Description

The [IpUtils::checkIp6](https://github.com/symfony/http-foundation/blob/6.1/IpUtils.php) method validates that IPv6 loopback addresses ::1 are in the IPv4 0.0.0.0/8 subnet.

I don't know much about IPv6 networking and therefor I am not sure if this is expected behavior. I couldn't find any clear information if IPv4 and IPv6 subnet matching SHOULD be compatible.

### How to reproduce

```php
use Symfony\Component\HttpFoundation\IpUtils;

var_dump(IpUtils::checkIp('::1', '0.0.0.0/8')); // true
```

### Possible Solution

I'm going to be totally honest, I don't have any clue how the IPv6 net mask validation works but my guess, if this really is a bug, is that there is a logic error because ::1 implies that the first 6 bits are 0.

### Additional Context

Again, I don't understand the byte magic that is happening in [IpUtils::checkIp6](https://github.com/symfony/http-foundation/blob/6.1/IpUtils.php), but my guess is that older version of http-foundation are also affected by this.

### PR DESCRIPTION
**Pull request by PhilETaylor**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #48049
| License       | MIT

Ensure that the `checkIp6` only validates IPv6 addresses and ipv6 subnets. 

PR Assumes that IPv6 and ipv6 subnets can never have a period in them (which as far as I know, is correct).

### CODE REVIEW

**Review by chalasr — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @PhilETaylor.

File: src/Symfony/Component/HttpFoundation/IpUtils.php [hunk 1]
```diff
@@ -124,6 +124,15 @@ public static function checkIp6($requestIp, $ip)
             throw new \RuntimeException('Unable to check Ipv6. Check that PHP was not compiled with option "disable-ipv6".');
         }
 
+        // Check to see if we were given a IP4 $requestIp or $ip by mistake
+        if (str_contains($requestIp, '.') || str_contains($ip, '.')) {
```
Comment (mremi) [inline src/Symfony/Component/HttpFoundation/IpUtils.php:128]: Hi, I think it's not compliant with IP addresses like `::ffff:127.0.0.1` which is the IPv6 version of an IPv4 IP address

Comment (PhilETaylor) [reply src/Symfony/Component/HttpFoundation/IpUtils.php:128]: > PR Assumes that IPv6 and ipv6 subnets can never have a period in them (which as far as I know, is correct).

My assumption was wrong, and no one challenged it before the PR was accepted and merged. Sorry for my lack of knowledge that caused this further bug. 

see https://github.com/symfony/symfony/issues/48420 and https://github.com/symfony/symfony/issues/48421 where this has been improved. Please test that PR.

Comment (mremi) [reply src/Symfony/Component/HttpFoundation/IpUtils.php:128]: Nice, I didn't see the fix, thx for the quick answer and no worry, mistakes happen :)
