### PR TITLE
[Filesystem] Fix str_contains deprecation

### LINKED ISSUE #54291: str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated
### Symfony version(s) affected

6

### Description

Calling str_contains when there is no last error will cause deprecation warning

### How to reproduce

run integration test that you call remove method and you will have a deprecation warning with phpunit 10 on line 201 of file Filesystem.php

### Possible Solution

Add default value to last error or maybe test if there is no error first

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by NeilPeyssard**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54291
| License       | MIT

In the Filesystem component, `str_contains` is potentially called with null as a first parameter. This is deprecated since PHP 8.1.

### CODE REVIEW

File: src/Symfony/Component/Filesystem/Filesystem.php [hunk 1]
```diff
@@ -396,7 +396,7 @@ public function hardlink(string $originFile, $targetFiles)
     private function linkException(string $origin, string $target, string $linkType)
     {
         if (self::$lastError) {
-            if ('\\' === \DIRECTORY_SEPARATOR && str_contains(self::$lastError, 'error code(1314)')) {
+            if ('\\' === \DIRECTORY_SEPARATOR && str_contains((string) self::$lastError, 'error code(1314)')) {
```
Comment (stof) [inline src/Symfony/Component/Filesystem/Filesystem.php]: this change is wrong. It cannot be null here due to the surrounding `if (self::$lastError)`

File: src/Symfony/Component/Filesystem/Filesystem.php [hunk 2]
```diff
@@ -199,7 +199,7 @@ private static function doRemove(array $files, bool $isRecursive): void
 
                     throw new IOException(sprintf('Failed to remove directory "%s": ', $file).$lastError);
                 }
-            } elseif (!self::box('unlink', $file) && (str_contains(self::$lastError, 'Permission denied') || file_exists($file))) {
+            } elseif (!self::box('unlink', $file) && (str_contains((string) self::$lastError, 'Permission denied') || file_exists($file))) {
```
Comment (stof) [inline src/Symfony/Component/Filesystem/Filesystem.php]: I'd rather use `self::$lastError && str_contains(self::$lastError, 'Permission denied')` here to make the intent easier to understand here (handling the case where there is no last error)

**Review by derrabus — APPROVED** [review]

**Review by GromNaN — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you @NeilPeyssard.
