### PR TITLE
[Cache] explicitly cast boolean SSL stream options

### LINKED ISSUE #53597: [Cache] RedisAdapter::createConnection - RedisCluster context
### Symfony version(s) affected

7.0.2

### Description

The context values verify_peer and verify_peer_name must contain the boolean value. I don't know why there is the condition `...\defined('Redis::SCAN_PREFIX') ? [$params['ssl'] ?? null] : []` in the last parameter, for me does not make any sense.

### How to reproduce

```php
RedisAdapter::createConnection('rediss://redis:6379?ssl[verify_peer]=false&ssl[verify_peer_name]=false&redis_cluster=true&auth[user]=root&auth[pass]=root')
```

### Possible Solution

```php
trait RedisTrait
{
...
    $context = [];
    foreach ($params['ssl'] ?? [] as $key => $value) {
        if(in_array($value, ['true', 'false'])) {
            $context[$key] = $value === "true" ? true : false;
        }else {
            $context[$key];
        }
    }

    try {
        $redis = new $class(null, $hosts, $params['timeout'], $params['read_timeout'], (bool) $params['persistent'], $params['auth'] ?? '', $context);
    } catch (\RedisClusterException $e) {
        throw new InvalidArgumentException('Redis connection failed: '.$e->getMessage());
    }
...
}
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #53597
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/Cache/Traits/RedisTrait.php [hunk 1]
```diff
@@ -328,9 +354,15 @@ public static function createConnection(string $dsn, array $options = [])
...
-                    case 'slaves': $redis->setOption(\RedisCluster::OPT_SLAVE_FAILOVER, \RedisCluster::FAILOVER_DISTRIBUTE_SLAVES); break;
+                    case 'error':
+                        $redis->setOption(\RedisCluster::OPT_SLAVE_FAILOVER, \RedisCluster::FAILOVER_ERROR);
+                        break;
+                    case 'distribute':
+                        $redis->setOption(\RedisCluster::OPT_SLAVE_FAILOVER, \RedisCluster::FAILOVER_DISTRIBUTE);
+                        break;
+                    case 'slaves':
+                        $redis->setOption(\RedisCluster::OPT_SLAVE_FAILOVER, \RedisCluster::FAILOVER_DISTRIBUTE_SLAVES);
+                        break;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Cache/Traits/RedisTrait.php]: let's revert these changes, they will likely generate conflict with upper branches where we might use match here and above

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Cache/Traits/RedisTrait.php (hunk 1 above)
Comment (xabbuh) [reply src/Symfony/Component/Cache/Traits/RedisTrait.php]: done

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.
