### PR TITLE
[SecurityBundle] Deprecate enabling bundle and not configuring it

### LINKED ISSUE #47593: [Security][DX] Deprecate/warn having the security bundle loaded, but not having any config
### Symfony version(s) affected

5.4.11

### Description

Currently, if you don't have any security config, the Security bundle skips loading any of its conifg:

https://github.com/symfony/symfony/blob/308edb55684f7afb3670414a6a69443551bf2e4d/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L90-L92

This can lead to weird errors like:
```
Did you forget to run "composer require symfony/twig-bundle"? Unknown function "is_granted" in "template.html.twig".
```

The developer is left to debug why Twig bundle is not being loaded, why the Security bundle is not loaded (they both are) (I'd argue that this itself is a bug).

### How to reproduce

1. Create a new symfony project
2. don't define any security
3. try to use some security related feature (like the mentioned Twig function) and see the error message

### Possible Solution

- warn about security not having any config (AFAIK it needs at least one firewall)
- load some (most) services into the container even without the config

### Additional Context

This happens if you're setting up a tiny Symfony app for functional tests where you need the smallest working config, you might omit things you're not directly interested in, but that can have unintended consequences which are hard to debug.

### PR DESCRIPTION
**Pull request by alamirault**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | yes 
| Tickets       | Fix #47593 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

In order to improve DX, add Trigger deprecation when `SecurityBundle` is enable without configuration.

### CODE REVIEW

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 1]
```diff
@@ -88,6 +89,9 @@ public function prepend(ContainerBuilder $container)
     public function load(array $configs, ContainerBuilder $container)
     {
         if (!array_filter($configs)) {
+            trigger_deprecation('symfony/security-bundle', '6.2', 'Enabling bundle "%s" and not configuring it is deprecated.', SecurityBundle::class);
```
Comment (fabpot) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]: 6.3

**Review by derrabus — APPROVED** [review]

File: src/Symfony/Bundle/SecurityBundle/Tests/Functional/app/AliasedEvents/config.yml [hunk 2]
```diff
@@ -1,2 +1,10 @@
 imports:
     - { resource: ./../config/framework.yml }
+
+security:
+    providers:
+        dummy:
+            memory: ~
+    firewalls:
+        dummy:
+            security: false
```
Comment (chalasr) [inline src/Symfony/Bundle/SecurityBundle/Tests/Functional/app/AliasedEvents/config.yml]: missing EOF

**Review by chalasr — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @alamirault.
