### PR TITLE
[Validator] fix handling typed properties as constraint options

### LINKED ISSUE #37387: [Validator] Type Properties not working in Constraints
**Symfony version(s) affected**: 5.1.2 (and others too, as long as you're using PHP 7.4 and typed properties)

**Description**  
PHP 7.4 introduced typed properties, which seem to be the way forward to build type-safe applications. But due to the way the Constraint component works to validate its options, it is not possible to use typed properties in a Constraint.

**How to reproduce**  
```php
class PostCode extends Constraint {
    public string $countryCode; // This is not initialised yet.
}

/// later ///

new PostCode(['countryCode' => 'CA']); // This throws an exception saying "countryCode" is not a valid option
```

**Possible Solution**  
The issue is due to the Constraint class using `get_object_vars($this)` in its constructor to find all the available properties on the class, which won't return the uninitialised ones, as explained here https://bugs.php.net/bug.php?id=78954. One solution is to use Reflection to find out what properties are available.

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37387
| License       | MIT
| Doc PR        |

### CODE REVIEW

File: src/Symfony/Component/Validator/Constraint.php [hunk 1]
```diff
@@ -108,7 +108,7 @@ public function __construct($options = null)
         $defaultOption = $this->getDefaultOption();
         $invalidOptions = [];
         $missingOptions = array_flip((array) $this->getRequiredOptions());
-        $knownOptions = get_object_vars($this);
+        $knownOptions = get_class_vars(static::class);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraint.php:111]: Just wondering: do we have tests with static properties, and others with dynamic ones? what behavior do we want for each?

Comment (nico-incubiq) [inline src/Symfony/Component/Validator/Constraint.php:111]: it might also work with private properties as they are accessible from this scope, is that supported? maybe add a test to ensure it cannot regress

Comment (xabbuh) [reply src/Symfony/Component/Validator/Constraint.php:111]: There is a new test for static properties which ensures that they cannot be used.

Comment (xabbuh) [reply src/Symfony/Component/Validator/Constraint.php:111]: Good point, I didn't think of that.

Comment (xabbuh) [reply src/Symfony/Component/Validator/Constraint.php:111]: Dynamic properties were not supported before and still are not if I don't miss anything.

Comment (nico-incubiq) [reply src/Symfony/Component/Validator/Constraint.php:111]: I've just checked locally, actually private properties aren't accessible from this scope, only public properties are since `Constraint` is higher in the inheritance chain.
Thx for the quick fix :)

Comment (xabbuh) [reply src/Symfony/Component/Validator/Constraint.php:111]: thanks for checking 👍

**Review by nico-incubiq — APPROVED** [review]
Tested locally, it fixes the issue as described in #37387

**Comment by xabbuh** [comment]
Tests on Travis CI pass now. Failures on AppVeyor do not look related.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.
