### PR TITLE
[Validator] Add `setGroupProvider` to `AttributeLoader`

### LINKED ISSUE #57677: [Validator] GroupSequenceProvider "provider" parameter gets ignored and results in error
### Symfony version(s) affected

7.0.x

### Description

According to the docs, it should be possible to set service implementing the `GroupProviderInterface` interface through the `GroupSequenceProvider` attribute via its `provider` argument. This way, the validated class does not require to implement the `GroupSequenceProviderInterface`.
Docs (current): https://symfony.com/doc/current/validation/sequence_provider.html#advanced-validation-group-provider
Docs (6.4): https://symfony.com/doc/6.4/validation/sequence_provider.html#advanced-validation-group-provider

This functionality currently gets ignored and results in an error
```sh
Uncaught PHP Exception Symfony\Component\Validator\Exception\GroupDefinitionException: "Class "App\Model\Payload" must implement GroupSequenceProviderInterface." at ClassMetadata.php line 441
```
This works in 6.4 but not anymore in 7.0 and up
Tested in Symfony 7.1.2

### How to reproduce

Example that should work but doesn't:
```PHP
#[Assert\GroupSequenceProvider(provider: PayloadGroupProvider::class)]
final class Payload
{
    ...
}

final readonly class PayloadGroupProvider implements GroupProviderInterface
{
    public function getGroups(object $object): array|GroupSequence
    {
        return ['Payload', 'SomeOtherGroup'];
    }
}
```

### Possible Solution

In the `AttributeLoader` when checking for the `GroupSequenceProvider` attribute, also check for the `provider` argument and set the content inside the `ClassMetadata` object.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mazumba**
| Q             | A
| ------------- | ---
| Branch?       | 7.0
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #57677 
| License       | MIT

Was introduced in `AnnotationLoader` and got removed during the 6.4->7.0 switch to the `AttributeLoader`. Fixes issue [#57677](https://github.com/symfony/symfony/issues/57677).

### CODE REVIEW

**Review by yceruto — APPROVED** [review]
Thanks for reporting and fixing the issue, well done!

File: src/Symfony/Component/Validator/Tests/Mapping/Loader/AttributeLoaderTest.php [hunk 1]
```diff
@@ -210,6 +210,22 @@ public function testLoadGroupSequenceProviderAttribute()
...
+    public function testLoadExternalGroupSequenceProvider()
+    {
+        $loader = $this->createAttributeLoader();
+        $namespace = $this->getFixtureAttributeNamespace();
+
+        $metadata = new ClassMetadata($namespace.'\GroupProviderDto');
+        $loader->loadClassMetadata($metadata);
+
+        $expected = new ClassMetadata($namespace.'\GroupProviderDto');
+        $expected->setGroupProvider('Symfony\Component\Validator\Tests\Dummy\DummyGroupProvider');
```
Comment (OskarStark) [inline src/Symfony/Component/Validator/Tests/Mapping/Loader/AttributeLoaderTest.php:222]: Can we use `::class` here?

Comment (yceruto) [reply src/Symfony/Component/Validator/Tests/Mapping/Loader/AttributeLoaderTest.php:222]: It looks like the other tests use the same approach. Let’s improve them all in a separate PR. For now, let’s keep this consistent

Comment (OskarStark) [reply src/Symfony/Component/Validator/Tests/Mapping/Loader/AttributeLoaderTest.php:222]: Fine for me

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @mazumba.
