### PR TITLE
[FrameworkBundle] Fix checkboxes check assertions

### LINKED ISSUE #47830: [FrameworkBundle] `WebTestCaseTest::assertCheckboxChecked/assertCheckboxNotChecked` does not work with html5
### Symfony version(s) affected

6.1, sort of

### Description

The [`WebTestCaseTest::assertCheckboxChecked/assertCheckboxNotChecked`](https://github.com/symfony/symfony/blob/8a5b9a27250736a9b38e2bd802c394a2834e7e94/src/Symfony/Bundle/FrameworkBundle/Test/DomCrawlerAssertionsTrait.php#L88-L102) assertions do not work with html5 content.

They are only [tested with html 4 content](https://github.com/symfony/symfony/blob/8a5b9a27250736a9b38e2bd802c394a2834e7e94/src/Symfony/Bundle/FrameworkBundle/Tests/Test/WebTestCaseTest.php#L233-L246).

If the html tag in these tests with `<!DOCTYPE html>`, the tests fail.

This is because, in html5, `checked` is a [boolean attribute](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes), 
i.e this is valid:
`<input type="checkbox" name="rememberMe" checked>`
while this is not:
`<input type="checkbox" name="rememberMe" checked="checked">`

so the `new CrawlerSelectorAttributeValueSame("input[name=\"$fieldName\"]", 'checked', 'checked')` check fails.

`masterminds/html5` will parse `<input type="checkbox" name="rememberMe" checked="checked">` as  `<input type="checkbox" name="rememberMe" checked>`.

### How to reproduce

They are only [tested with html 4 content](https://github.com/symfony/symfony/blob/8a5b9a27250736a9b38e2bd802c394a2834e7e94/src/Symfony/Bundle/FrameworkBundle/Tests/Test/WebTestCaseTest.php#L233-L246)

Replace the html tag in these tests with `<!DOCTYPE html>`.

### Possible Solution

not sure, maybe modify the assertion so it works with html4 and 5 parsers
```php
LogicalOr(new CrawlerSelectorAttributeValueSame(...), new CrawlerSelectorAttributeExists(...))
```
where `CrawlerSelectorAttributeExists` is a new Constraint.

### Additional Context

We discoverd this issue while upgrading from symfony 5.4 to 6.1, because `masterminds/html5` became a mandatory dependency in 6.1: https://github.com/symfony/symfony/pull/44170, so previously on 5.4, our html in functional tests was not parsed as html5.

it should be noted that html5 is used in a default symfony project:
https://github.com/symfony/recipes/blob/f54b694258dfcb356f6c59e2ce1a4c49f3cceae9/symfony/twig-bundle/5.4/templates/base.html.twig#L1

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #47830 
| License       | MIT
| Doc PR        | N/A

The CssSelector component knows better about the `checked` state!

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/Tests/Test/WebTestCaseTest.php [hunk 1]
```diff
@@ -239,15 +239,15 @@ public function testAssertCheckboxChecked()
     {
         $this->getCrawlerTester(new Crawler('<html><body><form><input type="checkbox" name="rememberMe" checked>'))->assertCheckboxChecked('rememberMe');
```
Comment (bendavies) [inline src/Symfony/Bundle/FrameworkBundle/Tests/Test/WebTestCaseTest.php:240]: i would run all of the tests in this class with and without a html5 doctype.
so with:
1. `<html>` and
2. `<!DOCTYPE html>`

this will expose the previous bug and prevent regression

Comment (MatTheCat) [reply src/Symfony/Bundle/FrameworkBundle/Tests/Test/WebTestCaseTest.php:240]: I tested against HTML5 in `testAssertCheckboxChecked` and `testAssertCheckboxNotChecked`. Do you really think it should be done for every other test (they all pass)?

Comment (bendavies) [reply src/Symfony/Bundle/FrameworkBundle/Tests/Test/WebTestCaseTest.php:240]: well it's debatable. we're testing the 2 different parses in the DomCrawler Crawler.
There was an unexposed bug here so it might make sense to test every assertion againsts both parsers.
I'm indifferent on adding it to every test

Maybe someone else has a stronger opinion.

Comment (maxbeckers) [reply src/Symfony/Bundle/FrameworkBundle/Tests/Test/WebTestCaseTest.php:240]: @bendavies i agree with you, we should test all assertions with and without a html5 doctype. Perhaps add new tests for checked and not checked with doctype or at least add tests for the error cases.

Comment (MatTheCat) [reply src/Symfony/Bundle/FrameworkBundle/Tests/Test/WebTestCaseTest.php:240]: FTR tests were added for error cases. Waiting for a core member incentive to add them in all others.

Comment (xabbuh) [reply src/Symfony/Bundle/FrameworkBundle/Tests/Test/WebTestCaseTest.php:240]: doing that for all other tests not related to this bugfix could be done in a separate PR

**Comment by nicolas-grekas** [comment]
Thank you @MatTheCat.
