### PR TITLE
[RateLimiter] bug #42194  fix: sliding window policy to use microtime

### LINKED ISSUE #42194: [RateLimiter] SlidingWindow to use microtime() instead of time()
**Description**
`RateLimiter` uses usually full seconds:
* `time()`,
* `sleep()`,
* `\DateTimeImmutable::createFromFormat('U', [time])`.

Sometimes however, it goes with microseconds:
* `microtime(true)`,
* `usleep()`

and could use them even more widely:
* `\DateTimeImmutable::createFromFormat('U.u', [microtime])`,
* `return (float) $interval->format('%f') / 1e6   // microseconds...`,
* `public function getExpirationTime(): ?float;`.

Using `float` gives an option to set interval in milliseconds:
```php
var_dump(\DateInterval::createFromDateString('200ms')->format('%f'));
// string(6) "200000"
```
and also to shorten wait time (e.g. 1.8s instead of 2.0s).

**Example**
`SlidingWindow` uses `time()` which means that after running `->wait()` it is still considered as not expired.
```php
<?php

use Symfony\Component\RateLimiter\Policy\SlidingWindow;

require_once './vendor/autoload.php';

$window = new SlidingWindow('some_id', 2);
sleep(2); // mimic $limit->wait();
var_dump($window->isExpired()); // false - same second

$window = new class ('some_id', 2) {
    public function __construct(string $id, int $intervalInSeconds)
    {
        $this->windowEndAt = microtime(true) + $intervalInSeconds;
    }

    public function isExpired(): bool
    {
        return microtime(true) > $this->windowEndAt;
    }
};
sleep(2); // mimic $limit->wait();
var_dump($window->isExpired()); // true
```

**Summary**
Before I go with a PR I would like to know if this change/improvement sounds like something you might merge in (i.e. using integers for time is not set in stone). It works for me locally.

### PR DESCRIPTION
**Pull request by jlekowski**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #42194
| License       | MIT
| Doc PR        | symfony/symfony-docs

Other parts of `RateLimiter` use `microtime()`, while  sliding window policy uses `time()` instead. That means the window may expire only up to 0.(9) seconds after the interval. Below an example that fails (window not expired) majority of the times (window is expired only if it starts e.g. at 1634992063.4999 and is checked at 1634992065.5000 - with `time()` rounding it would be 3 seconds).

```php
<?php

use Symfony\Component\RateLimiter\Policy\SlidingWindow;

require_once './vendor/autoload.php';

$window = new SlidingWindow('some_id', 2);
sleep(2); // mimic $limit->wait();
var_dump($window->isExpired()); // false - same second
```

### CODE REVIEW

File: src/Symfony/Component/RateLimiter/Tests/Policy/SlidingWindowTest.php [hunk 1]
```diff
@@ -72,4 +72,34 @@ public function testLongIntervalCreate()
         $new = SlidingWindow::createFromPreviousWindow($window, 60);
         $this->assertFalse($new->isExpired());
     }
+
+    public function testCreateFromPreviousWindowUsesMicrotime()
```
Comment (jlekowski) [inline src/Symfony/Component/RateLimiter/Tests/Policy/SlidingWindowTest.php:76]: These tests consistently pass after the changes. The old code would inconsistently fail, though (depend on the `microtome(true)` result at the moment of running the test.

**Comment by jlekowski** [comment]
@Nyholm, @wouterj - please have a look at this PR.

File: src/Symfony/Component/RateLimiter/Policy/NoLimiter.php [hunk 2]
```diff
@@ -29,7 +29,7 @@ final class NoLimiter implements LimiterInterface
 {
     public function reserve(int $tokens = 1, float $maxTime = null): Reservation
     {
-        return new Reservation(time(), new RateLimit(\PHP_INT_MAX, new \DateTimeImmutable(), true, \PHP_INT_MAX));
+        return new Reservation(microtime(true), new RateLimit(\PHP_INT_MAX, new \DateTimeImmutable(), true, \PHP_INT_MAX));
```
Comment (Nyholm) [inline src/Symfony/Component/RateLimiter/Policy/NoLimiter.php:30]: I see this is an unrelated bugfix. 

I dont mind this one sneaking in to this PR.

**Review by Nyholm — APPROVED** [review]
Thank you

File: src/Symfony/Component/RateLimiter/Policy/NoLimiter.php (hunk 2 above)
Comment (jlekowski) [reply src/Symfony/Component/RateLimiter/Policy/NoLimiter.php:30]: True, I just wanted to make `RateLimiter` to use `microtime(true)` instead of `time()` everywhere.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jlekowski.

**Comment by chalasr** [comment]
This PR introduced a randomly failing test https://github.com/symfony/symfony/runs/3990643552?check_suite_focus=true#step:8:987. @jlekowski could you please have a look?

**Comment by jlekowski** [comment]
@chalasr, I'll have a look at it. Thanks for letting me know.
