### PR TITLE
[Validator] Fix Email validator logic

### LINKED ISSUE #48985: Constraints\EmailValidator invalid LogicException namespace in VALIDATION_MODE_STRICT
### Symfony version(s) affected

6.2

### Description

Inside `EmailValidator` in case of `!class_exists(EguliasEmailValidator::class)` there is `throw new LogicException()` which results in:

``
Attempted to load class "LogicException" from namespace "Symfony\Component\Validator\Constraints".
Did you forget a "use" statement for e.g. "Symfony\Component\VarExporter\Exception\LogicException", "Symfony\Component\Validator\Exception\LogicException", "Symfony\Component\Translation\Exception\LogicException", "Symfony\Component\Serializer\Exception\LogicException", "Symfony\Component\Security\Core\Exception\LogicException", "Symfony\Component\PasswordHasher\Exception\LogicException", "Symfony\Component\Mime\Exception\LogicException", "Symfony\Component\Messenger\Exception\LogicException", "Symfony\Component\DependencyInjection\Exception\LogicException", "Symfony\Component\Console\Exception\LogicException", "Symfony\Component\Cache\Exception\LogicException" or "JMS\Serializer\Exception\LogicException"?
``

[https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Validator/Constraints/EmailValidator.php#L77](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Validator/Constraints/EmailValidator.php#L77)

### How to reproduce

Add `Constraints\Email` in `Email::VALIDATION_MODE_STRICT` without `"egulias/email-validator"` [Email](https://symfony.com/doc/current/reference/constraints/Email.html)

### Possible Solution

I suggest we add `use Symfony\Component\Validator\Exception\LogicException;`

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by fabpot**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #48985
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

File: src/Symfony/Component/Validator/Constraints/EmailValidator.php [hunk 1]
```diff
@@ -71,7 +72,7 @@ public function validate($value, Constraint $constraint)
 
         if (null === $constraint->mode) {
             if (Email::VALIDATION_MODE_STRICT === $this->defaultMode && !class_exists(EguliasEmailValidator::class)) {
-                throw new LogicException(sprintf('The "egulias/email-validator" component is required to make the "%s" constraint default to strict mode.', EguliasEmailValidator::class));
+                throw new LogicException(sprintf('The "egulias/email-validator" component is required to make the "%s" constraint default to strict mode.', EmailValidator::class));
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/Constraints/EmailValidator.php]: Should be `Email::class` I guess

Comment (fabpot) [reply src/Symfony/Component/Validator/Constraints/EmailValidator.php]: indeed :)

**Review by xabbuh — APPROVED** [review]
