### PR TITLE
[Security] Move the badges resolution check to `AuthenticatorManager`

### LINKED ISSUE #40491: [RFC] Move PassportInterface::checkIfCompletelyResolved to service layer?
I fail to see why

https://github.com/symfony/symfony/blob/21d4c09a1c8a9b291f83573fcd251064a25604e2/src/Symfony/Component/Security/Http/Authenticator/Passport/PassportTrait.php#L46-L53

should be part of the PassportInterface contract, instead of leveraging eg. AuthenticatorManagerInterface 🤔 

can a passport really be self-checking in that regard? is it an implementation detail of the manager?

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no (BC breaks on experimental code)
| Tickets       | Fixes #40491 
| License       | MIT
| Doc PR        | -

### CODE REVIEW

File: src/Symfony/Component/Security/Http/Authenticator/Passport/PassportInterface.php [hunk 1]
```diff
@@ -42,10 +41,5 @@ public function hasBadge(string $badgeFqcn): bool;
 
     public function getBadge(string $badgeFqcn): ?BadgeInterface;
 
-    /**
-     * Checks if all badges are marked as resolved.
-     *
-     * @throws BadCredentialsException when a badge is not marked as resolved
-     */
-    public function checkIfCompletelyResolved(): void;
+    public function getBadges(): array;
```
Comment (ro0NL) [inline src/Symfony/Component/Security/Http/Authenticator/Passport/PassportInterface.php:47]: `@return BadgeInterface[]`

**Review by ro0NL — APPROVED** [review]

**Review by wouterj — APPROVED** [review]

File: src/Symfony/Component/Security/Http/Authenticator/Passport/PassportInterface.php [hunk 2]
```diff
@@ -43,9 +42,7 @@ public function hasBadge(string $badgeFqcn): bool;
     public function getBadge(string $badgeFqcn): ?BadgeInterface;
 
     /**
-     * Checks if all badges are marked as resolved.
-     *
-     * @throws BadCredentialsException when a badge is not marked as resolved
+     * @return array<string, BadgeInterface>
```
Comment (Nyholm) [inline src/Symfony/Component/Security/Http/Authenticator/Passport/PassportInterface.php]: What does the `string` represent?

That should be documented. 

I suggest changing to `list<BadgeInterface>`

Comment (ro0NL) [reply src/Symfony/Component/Security/Http/Authenticator/Passport/PassportInterface.php]: make it  `array<class-string<BadgeInterface>, BadgeInterface>` then :)

overall i agree, more info more better :+1:

Comment (Nyholm) [reply src/Symfony/Component/Security/Http/Authenticator/Passport/PassportInterface.php]: I see that the current `PassportTrait` is using a fqcn as index. But that is an implementation detail, right? If so, the contract should be simpler. 

If we really want to use the fact that the keys are a fqcn, we should add that in the contract (interface method doc block).

Comment (ro0NL) [reply src/Symfony/Component/Security/Http/Authenticator/Passport/PassportInterface.php]: it's not IMHO: `getBadge(string $badgeFqcn)`

Comment (ro0NL) [reply src/Symfony/Component/Security/Http/Authenticator/Passport/PassportInterface.php]: > we should add that in the contract

yes this is the contract ;)

Comment (Nyholm) [reply src/Symfony/Component/Security/Http/Authenticator/Passport/PassportInterface.php]: Yeah, Either `array<class-string<BadgeInterface>, BadgeInterface>` if we want the contract to include that info. Or just  `list<BadgeInterface>`. 

I prefer the latter. Especially since we never use the keys.

Comment (ro0NL) [reply src/Symfony/Component/Security/Http/Authenticator/Passport/PassportInterface.php]: OH, i do agree a list could work. The internal structure is an implementation detail indeed (regardless of how getBadge works).

But im generally fine with the structure at the contract level :+1:

Comment (Nyholm) [reply src/Symfony/Component/Security/Http/Authenticator/Passport/PassportInterface.php]: > it's not IMHO

It still is =)

That method has nothing to do with how the badges are stored internally. I can imagine at least two implementations where we don't store fqcn as keys but we would still respect this method. 


(There are some serious race conditions in these comments =) )

Comment (ro0NL) [reply src/Symfony/Component/Security/Http/Authenticator/Passport/PassportInterface.php]: a list implies multiple of the same type, im not sure that should be conveyed.

@wouterj knows best from the design POV :)

Comment (chalasr) [reply src/Symfony/Component/Security/Http/Authenticator/Passport/PassportInterface.php]: I'm for making that requirement part of the contract. Updated to `array<class-string<BadgeInterface>, BadgeInterface>` with description. Hope it's ok for everyone

File: composer.json [hunk 3]
```diff
@@ -53,7 +53,8 @@
         "symfony/polyfill-php73": "^1.11",
         "symfony/polyfill-php80": "^1.15",
         "symfony/polyfill-uuid": "^1.15",
-        "symfony/runtime": "self.version"
+        "symfony/runtime": "self.version",
+        "vimeo/psalm": "4.x-dev"
```
Comment (Nyholm) [inline composer.json]: This is not needed.

**Review by Nyholm — APPROVED** [review]
Thank you. 

Just a minor.

File: composer.json (hunk 3 above)
Comment (chalasr) [reply composer.json]: oops, leftovers from psalm local debug :) reverted

File: src/Symfony/Component/Security/Http/Authenticator/Passport/PassportInterface.php (hunk 2 above)
Comment (stof) [reply src/Symfony/Component/Security/Http/Authenticator/Passport/PassportInterface.php]: if the return type is documented as `list<BadgeInterface>`, the getter must apply `array_values`. The contract of `list` is that keys are sequential integers from 0 to `$count-1`.

Comment (chalasr) [reply src/Symfony/Component/Security/Http/Authenticator/Passport/PassportInterface.php]: thanks for confirming

**Comment by chalasr** [comment]
Thanks everyone for the discussion and reviews.
