### PR TITLE
[Validator] deprecate handling options in the base Constraint class

### LINKED ISSUE #60029: [Validator] Refactor without magic methods / class
### Description

I needed to use the symony/validator and I hoped I am not going "back" Zend Framework with all those Magic methods / Magic class generations.

Then I discovered this:

```
public function validatedBy()
    {
        return static::class.'Validator';
    }
```

And more badly this:

```
if (\is_array($options) && isset($options['value']) && !property_exists($this, 'value')) {
            if (null === $defaultOption) {
                throw new ConstraintDefinitionException(sprintf('No default option is configured for constraint "%s".', static::class));
            }

            $options[$defaultOption] = $options['value'];
            unset($options['value']);
        }
```
which ends in

```
foreach ($options as $name => $value) {
            $this->$name = $value;
        }
```

I was really shocked at the moment i saw this. Any refactoring method will fail and break code, due to unused classes. 

 
- It is not required (also right now) that the validator needs to be a different class then the constraint
- The options should just be in an option array, or better in a DTO, which can be then accessed through `getOption(): DTO` or  if it is an array `getOption(string $key): mixed`

If you can not change this, what is the reason why this was build in such a way?

br,
PrDatur

### Example

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Issues        | Fix #60029
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/Validator/Attribute/InitializesOptions.php [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\Validator\Attribute;
+
+#[\Attribute(\Attribute::TARGET_CLASS)]
+final class InitializesOptions
```
Comment (stof) [inline src/Symfony/Component/Validator/Attribute/InitializesOptions.php]: why do we need this attribute ? We already have the `HasNamedArguments` attribute on the constructor which says that the constraint supports using it as named arguments, and we already deprecated passing options in the old way in most core constraints after migrating them to this attribute.

File: src/Symfony/Component/Validator/Tests/Constraints/AtLeastOneOfValidatorTest.php [hunk 2]
```diff
@@ -49,6 +49,11 @@
  */
 class AtLeastOneOfValidatorTest extends ConstraintValidatorTestCase
 {
+    public static function setUpBeforeClass(): void
+    {
+        self::markTestSkipped();
```
Comment (stof) [inline src/Symfony/Component/Validator/Tests/Constraints/AtLeastOneOfValidatorTest.php]: why skipping those tests ?

File: src/Symfony/Component/Validator/Constraint.php [hunk 3]
```diff
@@ -110,6 +116,28 @@ public function __construct(mixed $options = null, ?array $groups = null, mixed
     {
         unset($this->groups); // enable lazy initialization
 
+        self::$checkedConstraintClasses[static::class] ??= str_starts_with(static::class, 'Symfony\Component\Validator\Constraints\\') || (new \ReflectionClass(static::class))->getAttributes(InitializesOptions::class) !== [];
```
Comment (stof) [inline src/Symfony/Component/Validator/Constraint.php]: I don't think we should have this check here. We should deprecate entirely passing non-null options.

File: src/Symfony/Component/Validator/Tests/Constraints/AtLeastOneOfValidatorTest.php (hunk 2 above)
Comment (xabbuh) [reply src/Symfony/Component/Validator/Tests/Constraints/AtLeastOneOfValidatorTest.php]: those calls were left from some debugging session and shouldn't have been pushed

File: src/Symfony/Component/Validator/Attribute/InitializesOptions.php (hunk 1 above)
Comment (xabbuh) [reply src/Symfony/Component/Validator/Attribute/InitializesOptions.php]: My initial idea was to completely deprecate the `$options` argument of the base `Constraint` class. But it turns out that this breaks when named arguments are used. I have removed the attribute again and only deprecated passing anything else than `null` for the `$options` argument.

File: src/Symfony/Component/Validator/CHANGELOG.md [hunk 4]
```diff
@@ -1,6 +1,14 @@
 CHANGELOG
 =========
 
+7.4
+---
+
+* Deprecate evaluating options in the base `Constraint`. Initialize properties in the constructor of the concrete constraint
+  class instead and add the `#[InitializesOptions]` attribute to opt-out of the deprecated behaviour.
```
Comment (stof) [inline src/Symfony/Component/Validator/CHANGELOG.md]: isn't `InitializesOptions` gone now ?

Comment (xabbuh) [reply src/Symfony/Component/Validator/CHANGELOG.md]: indeed, changelog and upgrade file updated accordingly

**Comment by xabbuh** [comment]
I think this is now ready. I have also added some more details to the changelog/upgrade files to explain how to update custom constraints around the several deprecations.

File: UPGRADE-7.4.md [hunk 5]
```diff
@@ -22,3 +22,121 @@ HttpClient
 ----------
 
  * Deprecate using amphp/http-client < 5
+
+Validator
+---------
+
+* Deprecate evaluating options in the base `Constraint` class. Initialize properties in the constructor of the concrete constraint
```
Comment (OskarStark) [inline UPGRADE-7.4.md]:
```suggestion
 * Deprecate evaluating options in the base `Constraint` class. Initialize properties in the constructor of the concrete constraint
```
Same for the others and indention for the inner data + 1 space

Comment (xabbuh) [reply UPGRADE-7.4.md]: fixed

File: UPGRADE-7.4.md [hunk 6]
```diff
@@ -22,3 +22,121 @@ HttpClient
...
+
+   ```php
+   class CustomConstraint extends Constraint
+   {
+       public $option1;
+       public $option2;
+
+       public function __construct($option1 = null, $option2 = null)
+       {
+           parent::__construct();
```
Comment (stof) [inline UPGRADE-7.4.md]: I suggest showing passing the groups to the parent in the After code (as the Before code passing the array of options supports `groups` in the options)

File: UPGRADE-7.4.md [hunk 7]
```diff
@@ -22,3 +22,121 @@ HttpClient
...
+
+   After:
+
+   ```php
+   class CustomConstraint extends Constraint
+   {
+       public $option1;
+       public $option2;
+
+       public function __construct($option1 = null, $option2 = null)
```
Comment (stof) [inline UPGRADE-7.4.md]: this missing the `HasNamedArgument` attribute that is required to make the constraint compatible with XML and Yaml file loaders (for attributes, it depends on how the constructor is used so the component attribute is not necessary, but it does not hurt and the changelog should support both cases)

Comment (stof) [reply UPGRADE-7.4.md]: this also applies to the component changelog of course.

File: UPGRADE-7.4.md (hunk 6 above)
Comment (xabbuh) [reply UPGRADE-7.4.md]: done

File: UPGRADE-7.4.md (hunk 7 above)
Comment (xabbuh) [reply UPGRADE-7.4.md]: done as well

File: UPGRADE-7.4.md [hunk 8]
```diff
@@ -39,3 +39,130 @@ Security
...
  * Deprecate `LazyFirewallContext::__invoke()`
+
+Validator
+---------
+
+ * Deprecate evaluating options in the base `Constraint` class. Initialize properties in the constructor of the concrete constraint
+   class instead.
+
+   Before:
+
```
Comment (OskarStark) [inline UPGRADE-7.4.md]:
```suggestion
   **Before**
```

that's how we use it in the 8.0 upgrade file, not a blocker

**Review by OskarStark — APPROVED** [review]

File: UPGRADE-7.4.md [hunk 9]
```diff
@@ -39,3 +39,130 @@ Security
...
+   ```php
+   class CustomConstraint extends Constraint
+   {
+       public $option1;
+       public $option2;
```
Comment (fabpot) [inline UPGRADE-7.4.md:55]: I suppose these are not needed.

Comment (xabbuh) [reply UPGRADE-7.4.md:55]: They are because these properties are populated by the parent `normalizeOptions()` method if I don't misunderstand what you mean (basically the statement `$knownOptions = get_class_vars(static::class);` is built on top of the existence of the properties).

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.
