### PR TITLE
[Serializer] Fix denormalize constructor arguments

### LINKED ISSUE #52422: [Serializer] Constructor arguments are mapped wrong if request is missing an argument
### Symfony version(s) affected

6.3.6

### Description

This issue rose while using the `MapRequestPayload`  Attribute on a request.

Consider the following DTO and Controller:

```php
final class ChangePassword
{
    #[SerializedName(serializedName: 'old_password')]
    private ?string $oldPassword = null;

    public function __construct(
        #[Assert\NotNull,
            Assert\NotBlank,
            Assert\Email]
        private string $email,
        #[Assert\NotNull,
            Assert\NotBlank]
        private string $password,
        ?string $oldPassword = null
    ) {
        $this->oldPassword = $oldPassword;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function getPassword(): string
    {
        return $this->password;
    }

    public function getOldPassword(): ?string
    {
        return $this->oldPassword;
    }
}
```
  
```php
   #[Route(path: 'api/change-password', name: 'change-password', methods: ['POST'])]
    public function changePasswordAction(#[MapRequestPayload] ChangePassword $changePassword): JsonResponse
    {
        return new JsonResponse($changePassword->getEmail());
    }
```

When calling this route with
```json
{
  "password": "abc",
  "old_password": "def"
}
```

the created object looks like this:
```
object(App\DTO\ChangePassword)#2315 (3) {
["oldPassword":"App\DTO\ChangePassword":private]=>
NULL
["email":"App\DTO\ChangePassword":private]=>
string(3) "abc"
["password":"App\DTO\ChangePassword":private]=>
string(3) "def"
}
```

the values are not correctly mapped

### How to reproduce

A simple way to reproduce it is described above.

It's also possible to use my github project: https://github.com/Havrin/symfony-payload-bug

start it and throw the following request against `https://localhost/api/change-password`
```
{
  "password": "abc",
  "old_password": "def"
}
```

### Possible Solution

While debugging I noticed, that https://github.com/symfony/serializer/blob/1197823bacefc3397fafb8f10709c1574b2f69ce/Normalizer/AbstractNormalizer.php#L376 is creating an array of values with just an index-number as key.
After creating the object in https://github.com/symfony/serializer/blob/1197823bacefc3397fafb8f10709c1574b2f69ce/Normalizer/AbstractNormalizer.php#L420 the values are wrongly mapped. Seems like the code is not correctly using the name as key but rather the index-number.

### Additional Context

The wrong mapping started occurring after this fix: https://github.com/symfony/symfony/issues/51907

### LINKED ISSUE #52499: [Serializer] Only unset data in AbstractNormalizer::instantiateObject if constructor invocation succeeded
### Symfony version(s) affected

6.3.x,5.4.x

### Description

The `AbstractNormalizer::instantiateObject` unsets the corresponding `&$data` value for a constructor argument if it believes it will be set by constructor invocation so that no `set` is called later on. However, if constructor invocation fails as it is missing arguments, the value won't be set again at a later stage, even if the object could be instantiated partially when setting the property later on.

### How to reproduce

If we have an example object

```php
class ExampleObject
{
    public function __construct(public readonly string $propertyMissing, public readonly string $propertyGiven)
    {
    }
}
```

I would expect the following test to pass:

```php
try {
    $exampleObject = $serializer->denormalize(['propertyGiven' => 'foo'],
        ExampleObject::class,
        null,
        [DenormalizerInterface::COLLECT_DENORMALIZATION_ERRORS => true]);
} catch (PartialDenormalizationException $e) {
    $exampleObject = $e->getData();
}
self::assertInstanceOf(ExampleObject::class, $exampleObject);
self::assertEquals('foo', $exampleObject->propertyGiven);
```

however it says: `$propertyGiven must not be accessed before initialization` as there was no attempt to set it later on after the constructor instantiation failed.

### Possible Solution

Remember the properties that have to be unset if the constructor instantiation succeeds and only unset them if there are no missing parameters and the instantiation actually worked.

### Additional Context

I realized this as the behaviour changed with commit [c54cfbb6f3129c41ea5b26b4e3115919132ab726](https://github.com/symfony/serializer/commit/c54cfbb6f3129c41ea5b26b4e3115919132ab726) as it now collects all missing arguments. Before it returned early and the `$data` values for later constructor arguments were not unset. So this is kind of a regression, although before it just worked "accidentially" in my use case as the first argument was already missing for my data.

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #52499, Fix #52422
| License       | MIT

Since this PR: https://github.com/symfony/symfony/pull/51907, objects with partial constructor parameters were wrongly instantiated.

This PR fixes that issue by delegating the properties values assignment, by unsetting normalized data only when the constructor has been called properly.

This might correct #50759 as well.

### CODE REVIEW

**Comment by mtarld** [comment]
fabbot errors aren't related.

File: src/Symfony/Component/Serializer/Serializer.php [hunk 1]
```diff
@@ -228,8 +228,24 @@ public function denormalize($data, string $type, string $format = null, array $c
             $context['not_normalizable_value_exceptions'] = [];
             $errors = &$context['not_normalizable_value_exceptions'];
             $denormalized = $normalizer->denormalize($data, $type, $format, $context);
+
             if ($errors) {
-                throw new PartialDenormalizationException($denormalized, $errors);
+                // merge errors so that one path has only one error
+                $uniqueErrors = [];
+                foreach ($errors as $i => $error) {
+                    if (isset($uniqueErrors[$error->getPath()])) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Serializer.php]: shouldn't this be done only when `null !== $error->getPath()`?

File: src/Symfony/Component/Serializer/Serializer.php [hunk 2]
```diff
@@ -228,8 +228,24 @@ public function denormalize($data, string $type, string $format = null, array $c
...
+                        continue;
+                    }
+
+                    if (null !== $error->getPath()) {
+                        $uniqueErrors[$error->getPath()] = $error;
+                        continue;
+                    }
+
+                    $uniqueErrors[$i] = $error;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Serializer.php]: `[]` or `[$i]`?

**Review by nicolas-grekas — APPROVED** [review]
LGTM after minor changes

**Comment by nicolas-grekas** [comment]
Thank you @mtarld.

**Comment by nicolas-grekas** [comment]
@mtarld could you please have a look at the current failures on branch 6.3 for Serializer? I need help to resolve them after the merge up :pray:

**Comment by mtarld** [comment]
Sorry @nicolas-grekas I'm in a different timezone, so I hadn't time to take of it.

But the fix provided by @xabbuh in https://github.com/symfony/symfony/pull/52665 is good (it's the one I already had on my local machine)
