### PR TITLE
[Console] Fix horizontal table top border is incorrectly rendered

### LINKED ISSUE #52101: [Console] Horizontal table top border is incorrectly rendered
### Symfony version(s) affected

6.3.3

### Description

Top border of an horizontal table (Symfony Console) won't render correctly : the wrong crossing chars are used.
This is not visible with the default style which uses '+' character for both corners and crossings, but with custom crossing chars like ┼ ┌ ┬ ┐ ┤ ┘ ┴ └ ├ for instance, the bug is visible.

### How to reproduce

The following code 
```php
$consoleOutput = new ConsoleOutput();

$tableStyle = (new TableStyle())
    ->setHorizontalBorderChars('─')
    ->setVerticalBorderChars('│')
    ->setCrossingChars('┼', '┌', '┬', '┐', '┤', '┘', '┴', '└', '├')
;

$table = (new Table($consoleOutput))
    ->setStyle($tableStyle)
    ->setHeaderTitle('Title')
    ->setHeaders(['Hello', 'World'])
    ->setRows([[1, 2], [3, 4]])
;

$table->setHorizontal(true)->render();
$table->setHorizontal(false)->render();
```
will render like this : 
```
├──── Title ┼───┤
│ Hello │ 1 │ 3 │
│ World │ 2 │ 4 │
└───────┴───┴───┘
┌──── Title ────┐
│ Hello │ World │
├───────┼───────┤
│ 1     │ 2     │
│ 3     │ 4     │
└───────┴───────┘

```
instead of what we could expect : 
```
┌──── Title ┬───┐
│ Hello │ 1 │ 3 │
│ World │ 2 │ 4 │
└───────┴───┴───┘
┌──── Title ────┐
│ Hello │ World │
├───────┼───────┤
│ 1     │ 2     │
│ 3     │ 4     │
└───────┴───────┘

```

### Possible Solution

One possible solution i found would be to modify the `render` method of `Symfony\Component\Console\Helper\Table` : 

The part that renders the first row : 
```php
if ($isFirstRow) {
    $this->renderRowSeparator(
        $isHeader ? self::SEPARATOR_TOP : self::SEPARATOR_TOP_BOTTOM,
        $hasTitle ? $this->headerTitle : null,
        $hasTitle ? $this->style->getHeaderTitleFormat() : null
    );
    $isFirstRow = false;
    $hasTitle = false;
}
```
could be modified like this to fix this issue :
```php
if ($isFirstRow) {
    $this->renderRowSeparator(
        $isHeader || $horizontal ? self::SEPARATOR_TOP : self::SEPARATOR_TOP_BOTTOM,
        $hasTitle ? $this->headerTitle : null,
        $hasTitle ? $this->style->getHeaderTitleFormat() : null
    );
    $isFirstRow = false;
    $hasTitle = false;
}
```
Since there is no header row at the top for an horizontal table, the SEPARATOR_TOP_BOTTOM should not be used for horizontal table.

Maybe that is not the right way to fix it, but it seems to work.

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #52101
| License       | MIT

cc @alainrinder

### CODE REVIEW

**Comment by OskarStark** [comment]
Fabbot is false positive

**Comment by GromNaN** [comment]
The issue might be with unicode characters. Could you add an emoji in the values?

**Comment by OskarStark** [comment]
> The issue might be with unicode characters. Could you add an emoji in the values?

Lets try the fix from the bug report

**Comment by OskarStark** [comment]
What's the difference here?
CleanShot 2023-10-18 at 11 47 39@2x

File: src/Symfony/Component/Console/Tests/Helper/TableTest.php [hunk 1]
```diff
@@ -1997,4 +1997,63 @@ public function testWithHyperlinkAndMaxWidth()
...
+
+    public function testGithubIssue52101HorizontalFalse()
+    {
+        $tableStyle = (new TableStyle())
+            ->setHorizontalBorderChars('─')
+            ->setVerticalBorderChars('│')
+            ->setCrossingChars('┼', '┌', '┬', '┐', '┤', '┘', '┴', '└', '├')
+        ;
+
+        $table = (new Table($output = $this->getOutputStream(true)))
```
Comment (gordinskiy) [inline src/Symfony/Component/Console/Tests/Helper/TableTest.php]:
```suggestion
        $table = (new Table($output = $this->getOutputStream()))
```
This will remove formatting and fix diff in assertions.

Comment (OskarStark) [reply src/Symfony/Component/Console/Tests/Helper/TableTest.php]: Thanks

File: src/Symfony/Component/Console/Tests/Helper/TableTest.php [hunk 2]
```diff
@@ -1997,4 +1997,63 @@ public function testWithHyperlinkAndMaxWidth()
...
+
+    public function testGithubIssue52101HorizontalTrue()
+    {
+        $tableStyle = (new TableStyle())
+            ->setHorizontalBorderChars('─')
+            ->setVerticalBorderChars('│')
+            ->setCrossingChars('┼', '┌', '┬', '┐', '┤', '┘', '┴', '└', '├')
+        ;
+
+        $table = (new Table($output = $this->getOutputStream(true)))
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Tests/Helper/TableTest.php]:
```suggestion
        $table = (new Table($output = $this->getOutputStream()))
```

File: src/Symfony/Component/Console/Helper/Table.php [hunk 3]
```diff
@@ -421,7 +421,7 @@ public function render()
 
                 if ($isFirstRow) {
                     $this->renderRowSeparator(
-                        $isHeader ? self::SEPARATOR_TOP : self::SEPARATOR_TOP_BOTTOM,
+                        $isHeader || $horizontal ? self::SEPARATOR_TOP : self::SEPARATOR_TOP_BOTTOM,
```
Comment (maxbeckers) [inline src/Symfony/Component/Console/Helper/Table.php]: Isn't `$isHeader` here always `false` by the logic? Or do I miss a case?
```suggestion
                        $horizontal ? self::SEPARATOR_TOP : self::SEPARATOR_TOP_BOTTOM,
```

Comment (OskarStark) [reply src/Symfony/Component/Console/Helper/Table.php]: lets check via CI

File: src/Symfony/Component/Console/Tests/Helper/TableTest.php (hunk 2 above)
Comment (OskarStark) [inline src/Symfony/Component/Console/Tests/Helper/TableTest.php]:
```suggestion
        $table = (new Table($output = $this->getOutputStream()))
```

File: src/Symfony/Component/Console/Tests/Helper/TableTest.php (hunk 1 above)
Comment (OskarStark) [inline src/Symfony/Component/Console/Tests/Helper/TableTest.php]:
```suggestion
        $table = (new Table($output = $this->getOutputStream()))
```

File: src/Symfony/Component/Console/Helper/Table.php [hunk 4]
```diff
@@ -411,7 +411,7 @@ public function render()
 
                 if ($isHeader && !$isHeaderSeparatorRendered) {
                     $this->renderRowSeparator(
-                        $isHeader ? self::SEPARATOR_TOP : self::SEPARATOR_TOP_BOTTOM,
+                        self::SEPARATOR_TOP,
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Helper/Table.php:414]: I removed this, because `$isHeader` is always true

File: src/Symfony/Component/Console/Helper/Table.php (hunk 3 above)
Comment (OskarStark) [reply src/Symfony/Component/Console/Helper/Table.php]: Looks like it is ok, thanks @maxbeckers

**Review by maxbeckers — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @OskarStark.
