### PR TITLE
[PropertyInfo] Fix phpstan extractor issues

### LINKED ISSUE #44491: [PropertyInfo] PhpStanTypeHelper doesn't support ConstTypeNode
### Description

After updating from Symfony 5.3 to Symfony 5.4, our code started to crash. This is because new PhpStanExtractor was introduced that was prioritized above older extractors. This extractor started to return `null` type and hence serializer failed to denormalize our objects.

It returns null, because this is a UnionTypeNode containing ConstTypeNode and IdentifierTypeNode (null). However PhpStanTypeHelper doesn't handle ConstTypeNode and hence symfony/property-info will return `null` only.

### Example

```php
class Foo
{
   /**
     * @return PageType::*|null
     */
    public function getDynamicPageType(): ?string
    {
        return rand(0, 1) ? PageType::FOO : null;
    }
}

class PageType {
    const FOO = 'foo';
}
```
On Symfony 5.3, this returns string|null. On Symfony 5.4, because PhpStanExtractor was added which doesn't correctly handle unions, it returns null.

### PR DESCRIPTION
**Pull request by ostrolucky**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44491
| License       | MIT
| Doc PR        | 

Since this crashes denormalization for codebase that was upgraded from 5.3 to 5.4, I am classifying this as a bugfix.

This PR fixes 2 issues. One is with docblocks like `/** @var Foo::*|null */`, where Extractor returns `null` only and afterwards Serializer fails to accept anything else. Second is `/** @var non-empty-array<...> */` where extractor doesn't recognize that `non-empty-array` is still an array and afterwards Serializer fails complaining that `array` is not an `non-empty-array`

### CODE REVIEW

**Comment by staabm** [comment]
Looking at the phpstan helper makes me think it also misses
- negative-int
- positive-int
- int<1, -0> like IntegerRanges

**Comment by ostrolucky** [comment]
I guess we could define the scope of this PR better. My goal wasn't to fix all PhpstanExtractor issues in existence here, but the ones that affected my closed-source project. Rest of the issues could be fixed in separate PR. Or, I could also fix them here, but I want to avoid someone coming here finding even more issues and hence extending the scope of this PR again and again.

**Comment by EmilMassey** [comment]
There is #44451 to introduce support for simple pseudo-types - `non-empty-array`, `positive-int`, `negative-int` etc.

**Comment by derrabus** [comment]
> This PR fixes 2 issues.

I was not aware that either syntax was actively supported in 5.3. What types did the extractor detect for those cases and how does the "crash" look like?

Sorry for being overly carefule here. I'd like to keep the changes as minimal as posssible and only restore the 5.3 behavior for your cases. This PR has the potential of sneaking in new functionality which is something we should not do in a bugfix.

**Comment by ostrolucky** [comment]
In Symfony 5.3, because PhpStanExtractor doesn't exist, it falls back to ReflectionExtractor which will extract info correctly throught reflection thanks to specified type declarations.

**Comment by derrabus** [comment]
And can we make this fallback work again?

**Comment by ostrolucky** [comment]
It does work, but only if PhpStanExtractor fails to detect the type completely. That's what I did in this PR for consttypes: Make consttypes return empty array, so that it falls back to another extractor.

File: src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/Fixtures/Foo.php [hunk 1]
```diff
@@ -16,8 +16,15 @@
...
+
     /**
      * @var string
      */
     public $bar;
+
+    /**
+     * @var string
+     */
+    public $baz;
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/Fixtures/Foo.php]: why did you change this file?

File: src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php [hunk 2]
```diff
@@ -721,6 +723,22 @@ public function testAcceptJsonNumber()
...
+
+        $extractor = new PropertyInfoExtractor([], [new PhpStanExtractor(), new PhpDocExtractor(), new ReflectionExtractor()]);
+        $normalizer = new ObjectNormalizer(null, null, null, $extractor);
+        $serializer = new Serializer([new ArrayDenormalizer(), new DateTimeNormalizer(), $normalizer]);
+
+        $this->assertSame('bar', $serializer->denormalize(['foo' => 'bar'], \get_class(new class() {
+            /** @var self::*|null */
+            public $foo;
+        }))->foo);
+    }
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php:740]: this was passing before the change on PropertyInfo, isn't it? (I'm saying that because deps=low tests still pass)
did you add the test just to increase the coveage? (which is a good thing :) )

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php (hunk 2 above)
Comment (ostrolucky) [reply src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php:740]: Yes I wanted to have some "integration" test with serializer to demonstrate the problem, so to increase coverage yes. We didn't have any tests in serializer that do use PhpStanExtractor. This test doesn't pass without my changes in propertyinfo

File: src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/Fixtures/Foo.php (hunk 1 above)
Comment (ostrolucky) [reply src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/Fixtures/Foo.php]: Yep that doesn't look right. I don't remember, could be oversight indeed. I've removed it, I hope tests still pass

File: src/Symfony/Component/PropertyInfo/Util/PhpStanTypeHelper.php [hunk 3]
```diff
@@ -161,6 +166,8 @@ private function extractTypes(TypeNode $node, NameScope $nameScope): array
                     return [new Type(Type::BUILTIN_TYPE_INT)];
                 case 'list':
                     return [new Type(Type::BUILTIN_TYPE_ARRAY, false, null, true, new Type(Type::BUILTIN_TYPE_INT))];
+                case 'non-empty-array':
```
Comment (nicolas-grekas) [inline src/Symfony/Component/PropertyInfo/Util/PhpStanTypeHelper.php:170]: I'm just wondering: why do we want to add this to 5.4 while the other pseudo-types are added on 6.1 (see #44451)?

Comment (ostrolucky) [reply src/Symfony/Component/PropertyInfo/Util/PhpStanTypeHelper.php:170]: I think root of the problem is fallback case here on L182. If PhpStanTypeHelper doesn't recognize the type, it returns object. This is what causes issues during 5.3 -> 5.4 upgrade for my second use case. Potentially we could change that to return empty array instead, but that's very aggressive change compared to just adding support for non-empty-array (it might break various cases of `@return Foo`, `@return Foo<bar>` and so on. Alternatively, in my opinion backporting changes from #44451 to 5.4 would be fine too. All of those cases that were added there were most likely working fine in 5.3, but got broken in 5.4. `non-empty-array` just happens to be more often used than the rest of them and that's what blowed up in my projects.

Comment (nicolas-grekas) [reply src/Symfony/Component/PropertyInfo/Util/PhpStanTypeHelper.php:170]: Thanks, that's exactly why I posted https://github.com/symfony/symfony/pull/44451#pullrequestreview-833806383

@derrabus WDYT?

Comment (derrabus) [reply src/Symfony/Component/PropertyInfo/Util/PhpStanTypeHelper.php:170]: I wouldn't add support for that type here. If we get a proper fallback if the PHPStan extractor reported `null` here, that's the way to go imho.

Comment (ostrolucky) [reply src/Symfony/Component/PropertyInfo/Util/PhpStanTypeHelper.php:170]: Well then any idea how to properly make a fallback here? We need a mechanism how to detect object, instead of falling back to object on everything that's not recognized.

Comment (derrabus) [reply src/Symfony/Component/PropertyInfo/Util/PhpStanTypeHelper.php:170]: Sorry, your two answers were not displayed when I posted mine which obviously does not make sense in that context. 🙈 

I agree that in that particular case, active support for `non-empty-array` (and possibly `non-empty-list` as well) would be the least invasive fix.

Comment (ostrolucky) [reply src/Symfony/Component/PropertyInfo/Util/PhpStanTypeHelper.php:170]: I've added non-empty-list :)

**Comment by nicolas-grekas** [comment]
Thank you @ostrolucky.
