### PR TITLE
[WebProfilerBundle] Fix missing indent on non php files opended in the profiler

### LINKED ISSUE #60835: [WebProfilerBundle] Missing indent on non php files opended in the profiler
### Symfony version(s) affected

4.0+

### Description

When opening a non php file in the profiler the indent is missing.

This was introduced by this commit: https://github.com/symfony/twig-bridge/commit/d8fc719e38bc784758aea01d36ba4fefe57041bb (PR: https://github.com/symfony/symfony/pull/26230)

### How to reproduce

Considering any project running at `https://127.0.0.1:8000`

Non php file: https://127.0.0.1:8000/_profiler/open?file=config/packages/framework.yaml&line=0
PHP file: https://127.0.0.1:8000/_profiler/open?file=src/Kernel.php&line=0

### Possible Solution

Removing the ending trim in `Symfony\Bundle\WebProfilerBundle\Profiler::fixCodeMarkup()` seems to fix the problem.

Processing can be differentiated according to whether the file is a PHP highlighted file or another type of file (see: https://www.php.net/manual/en/function.highlight-file.php).

A potential improvement would be to no longer highlight the file on the backend, but to transfer this responsibility to a javascript library (ex: https://highlightjs.org/).

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by phcorp**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60835
| License       | MIT

This fixes non-php files indent in profiler.

# Testing

Considering any project running at https://127.0.0.1:8000

Non-php file: https://127.0.0.1:8000/_profiler/open?file=config/packages/framework.yaml&line=0
PHP file: https://127.0.0.1:8000/_profiler/open?file=src/Kernel.php&line=0

### CODE REVIEW

**Comment by xabbuh** [comment]
The CI failures look related.

File: src/Symfony/Bundle/WebProfilerBundle/Profiler/CodeExtension.php [hunk 1]
```diff
@@ -241,7 +287,7 @@ protected static function fixCodeMarkup(string $line): string
         // missing </span> tag at the end of line
         $opening = strpos($line, '<span');
         $closing = strpos($line, '</span>');
-        if (false !== $opening && (false === $closing || $closing > $opening)) {
+        if (false !== $opening && (false === $closing || $closing < $opening)) {
```
Comment (phcorp) [inline src/Symfony/Bundle/WebProfilerBundle/Profiler/CodeExtension.php]: note: there was a double `</span`> at the end of the line ; maybe the logic was broken, it added a `</span>` at the end of the line when an opening span was found and the opening span was before the closing span which seems perfectly fine.

File: src/Symfony/Bundle/WebProfilerBundle/Profiler/CodeExtension.php [hunk 2]
```diff
@@ -119,39 +119,85 @@ public function formatArgsAsText(array $args): string
...
         }
 
-        return null;
+        if (0 > $srcContext) {
+            $srcContext = \count($lines);
+        }
+
+        return $this->formatFileExcerpt(
+            array_map(
+                static fn (string $line): string => self::fixCodeMarkup($line),
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/WebProfilerBundle/Profiler/CodeExtension.php]:
```suggestion
                self::fixCodeMarkup(...),
```

**Review by nicolas-grekas — COMMENTED** [review]
Thanks for the PR.
Since this is a bugfix, it should target the lowest affected (and maintained) branch.
Can you please check which one it is and rebase+retarget?

File: src/Symfony/Bundle/WebProfilerBundle/Profiler/CodeExtension.php (hunk 2 above)
Comment (phcorp) [reply src/Symfony/Bundle/WebProfilerBundle/Profiler/CodeExtension.php]: done.

**Comment by phcorp** [comment]
> Thanks for the PR. Since this is a bugfix, it should target the lowest affected (and maintained) branch. Can you please check which one it is and rebase+retarget?

done. There are failing tests that seem unrelated to this PR and I couldn't change the milestone that was set by the automation

File: src/Symfony/Bridge/Twig/Tests/Extension/CodeExtensionTest.php [hunk 3]
```diff
@@ -129,6 +129,101 @@ public function testFormatFileIntegration()
...
+        }
+
+        $html = html_entity_decode($html);
+
+        $this->assertEquals($expected, $html);
+    }
+
+    public static function fileExcerptIntegrationProvider()
+    {
+        $fixturesPath = realpath(__DIR__.\DIRECTORY_SEPARATOR.'..'.\DIRECTORY_SEPARATOR.'Fixtures');
```
Comment (phcorp) [inline src/Symfony/Bridge/Twig/Tests/Extension/CodeExtensionTest.php]: note: I'm not sure if using a relative path to access fixtures path is ok, this test `CodeExtensionTest.php` was moved in upper branches so it will fail if fixtures are not also moved

Comment (nicolas-grekas) [inline src/Symfony/Bridge/Twig/Tests/Extension/CodeExtensionTest.php]:
```suggestion
        $fixturesPath = \dirname(__DIR__).\DIRECTORY_SEPARATOR.'Fixtures');
```

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @phcorp.
