### PR TITLE
[PropertyInfo] convert legacy types to TypeInfo types if getType() is not implemented

### LINKED ISSUE #57360: [PropertyInfo] Version 7.1 conflicts with `symfony/doctrine-bridge` 7.0
### Symfony version(s) affected

7.1.1

### Description

I had a generic PR from dependabot to update from `bump symfony/property-info from 7.0.8 to 7.1.1` and it immediately fails to dump the container because: 

```
!!  
!!  In PropertyInfoExtractor.php line 93:
!!  
!!    Attempted to call an undefined method named "getType" of class "Symfony\Bri  
!!    dge\Doctrine\PropertyInfo\DoctrineExtractor".                                
!!    Did you mean to call "getTypes"?                                             
```

`getType` was added in 7.1 with [this PR](https://github.com/symfony/symfony/pull/53160). Is a conflict PR enough or is there another way the team would like to handle this? (like checking for method exists).

### How to reproduce

If you pin `symfony/doctrine-bridge` at `7.0.*` and then require for `symfony/property-info` at `^7.1` packages will comply with each other, but then the container cannot be built. 

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #57360
| License       | MIT

### CODE REVIEW

**Comment by xabbuh** [comment]
@hantsy FYI, if you would like to try this with your application

File: src/Symfony/Component/PropertyInfo/PropertyInfoCacheExtractor.php [hunk 1]
```diff
@@ -61,7 +62,37 @@ public function getProperties(string $class, array $context = []): ?array
      */
     public function getType(string $class, string $property, array $context = []): ?Type
     {
-        return $this->extract('getType', [$class, $property, $context]);
+        try {
+            $serializedArguments = serialize([$class, $property, $context]);
+        } catch (\Exception) {
+            // If arguments are not serializable, skip the cache
+            return $this->propertyInfoExtractor->{$method}(...$arguments);
```
Comment (stof) [inline src/Symfony/Component/PropertyInfo/PropertyInfoCacheExtractor.php]: there is no `$method`. It should be `getType` here (or rather, it should be either `getType` or the fallback, so I would suggest creating a `doGetType` private method)

File: src/Symfony/Component/PropertyInfo/Util/LegacyTypeConverter.php [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+    {
+        if (null === $legacyTypes) {
+            return null;
+        }
+
+        $types = [];
+
+        foreach ($legacyTypes as $legacyType) {
+            $typeInfoType = match ($legacyType->getBuiltinType()) {
+                LegacyType::BUILTIN_TYPE_ARRAY => Type::array(),
```
Comment (stof) [inline src/Symfony/Component/PropertyInfo/Util/LegacyTypeConverter.php]: this should use `getCollectionKeyTypes` and `getCollectionValueTypes` to avoid loosing information available in the legacy type (same for iterable).

File: src/Symfony/Component/PropertyInfo/Util/LegacyTypeConverter.php [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+                LegacyType::BUILTIN_TYPE_ITERABLE => Type::iterable(),
+                LegacyType::BUILTIN_TYPE_NULL => Type::null(),
+                LegacyType::BUILTIN_TYPE_OBJECT => Type::object($legacyType->getClassName()),
+                LegacyType::BUILTIN_TYPE_RESOURCE => Type::resource(),
+                LegacyType::BUILTIN_TYPE_STRING => Type::string(),
+                LegacyType::BUILTIN_TYPE_TRUE => Type::true(),
+            };
+
+            if ($legacyType->isNullable()) {
+                $typeInfoType = Type::union($typeInfoType, Type::null());
```
Comment (stof) [inline src/Symfony/Component/PropertyInfo/Util/LegacyTypeConverter.php]: instead of potentially nesting union types (if we have a nullable legacy type in a list with multiple values), and potentially even several ones (if we have multiple nullable types), shouldn't we rather add `Type::null()` in `$types` separately (and maybe avoiding duplicates for it) ?

**Review by stof — CHANGES_REQUESTED** [review]

**Comment by stof** [comment]
btw, the testsuite should probably have a legacy test covering the usage of a legacy extractor (not implementing the new method) inside those.

File: src/Symfony/Component/PropertyInfo/Util/LegacyTypeConverter.php (hunk 3 above)
Comment (xabbuh) [reply src/Symfony/Component/PropertyInfo/Util/LegacyTypeConverter.php]: Indeed, that's a valid point. I have changed the code around the handling of `null`.

File: src/Symfony/Component/PropertyInfo/Util/LegacyTypeConverter.php [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+                LegacyType::BUILTIN_TYPE_FLOAT => Type::float(),
+                LegacyType::BUILTIN_TYPE_INT => Type::int(),
+                LegacyType::BUILTIN_TYPE_ITERABLE => Type::iterable(),
+                LegacyType::BUILTIN_TYPE_OBJECT => Type::object($legacyType->getClassName()),
+                LegacyType::BUILTIN_TYPE_RESOURCE => Type::resource(),
+                LegacyType::BUILTIN_TYPE_STRING => Type::string(),
+                LegacyType::BUILTIN_TYPE_TRUE => Type::true(),
+            };
+
+            if (LegacyType::BUILTIN_TYPE_NULL === $legacyType->getBuiltinType() || $legacyType->isNullable()) {
```
Comment (stof) [inline src/Symfony/Component/PropertyInfo/Util/LegacyTypeConverter.php:79]: if we have `LegacyType::BUILTIN_TYPE_NULL === $legacyType->getBuiltinType()`, we will get PHP error before reaching this point because the `match` won't handle it.

**Review by stof — CHANGES_REQUESTED** [review]
Please add tests covering this BC layer

File: src/Symfony/Component/PropertyInfo/Util/LegacyTypeConverter.php (hunk 4 above)
Comment (xabbuh) [reply src/Symfony/Component/PropertyInfo/Util/LegacyTypeConverter.php:79]: should be fixed now

**Comment by xabbuh** [comment]
I have added some tests for this fix

File: src/Symfony/Component/PropertyInfo/Tests/PropertyInfoCacheExtractorTest.php [hunk 5]
```diff
@@ -76,4 +82,88 @@ public function testIsInitializable()
         parent::testIsInitializable();
         parent::testIsInitializable();
     }
+
+    /**
+     * @dataProvider provideNestedExtractourWithoutGetTypeImplementationData
+     */
+    public function testNestedExtractorWithoutGetTypeImplementation(string $property, ?Type $expectedType)
```
Comment (stof) [inline src/Symfony/Component/PropertyInfo/Tests/PropertyInfoCacheExtractorTest.php:91]: this test should be marked as `@group legacy` as it covers a BC layer (and so should be removed once we upgrade to 8.0)

File: src/Symfony/Component/PropertyInfo/Tests/PropertyInfoCacheExtractorTest.php [hunk 6]
```diff
@@ -76,4 +82,88 @@ public function testIsInitializable()
...
+        }, new ArrayAdapter());
+
+        if (null === $expectedType) {
+            $this->assertNull($propertyInfoCacheExtractor->getType(Dummy::class, $property));
+        } else {
+            $this->assertEquals($expectedType, $propertyInfoCacheExtractor->getType(Dummy::class, $property));
+        }
+    }
+
+    public function provideNestedExtractourWithoutGetTypeImplementationData()
```
Comment (stof) [inline src/Symfony/Component/PropertyInfo/Tests/PropertyInfoCacheExtractorTest.php]:
```suggestion
    public function provideNestedExtractorWithoutGetTypeImplementationData()
```

File: src/Symfony/Component/PropertyInfo/Tests/PropertyInfoExtractorTest.php [hunk 7]
```diff
@@ -11,9 +11,74 @@
...
+        }]);
+
+        if (null === $expectedType) {
+            $this->assertNull($propertyInfoExtractor->getType(Dummy::class, $property));
+        } else {
+            $this->assertEquals($expectedType, $propertyInfoExtractor->getType(Dummy::class, $property));
+        }
+    }
+
+    public function provideNestedExtractourWithoutGetTypeImplementationData()
```
Comment (stof) [inline src/Symfony/Component/PropertyInfo/Tests/PropertyInfoExtractorTest.php]:
```suggestion
    public function provideNestedExtractorWithoutGetTypeImplementationData()
```

File: src/Symfony/Component/PropertyInfo/Util/LegacyTypeConverter.php [hunk 8]
```diff
@@ -0,0 +1,69 @@
...
+        if (null === $legacyTypes || [] === $legacyTypes) {
+            return null;
+        }
+
+        $nullable = false;
+        $types = [];
+
+        foreach ($legacyTypes as $legacyType) {
+            if ($legacyType->isCollection() && !\in_array($legacyType->getBuiltinType(), [LegacyType::BUILTIN_TYPE_ARRAY, LegacyType::BUILTIN_TYPE_ITERABLE], true)) {
+                $typeInfoType = Type::collection(Type::object(\Iterator::class), self::toTypeInfoType($legacyType->getCollectionValueTypes()), self::toTypeInfoType($legacyType->getCollectionKeyTypes()));
```
Comment (stof) [inline src/Symfony/Component/PropertyInfo/Util/LegacyTypeConverter.php]: Using `Type::object(\Iterator::class)` looks wrong to me. It should be using either `Type::array()` or `Type::iterable()` depending on the builtin type.

Comment (xabbuh) [reply src/Symfony/Component/PropertyInfo/Util/LegacyTypeConverter.php]: This case here is about collections where the built-in type is neither iterable nor array. But that probably means that the built-in type is an object here. I have rewritten the check accordingly.

**Comment by xabbuh** [comment]
Status: Needs Review

**Comment by ToshY** [comment]
@stof Could you spare some time to re-review this?

File: src/Symfony/Component/PropertyInfo/PropertyInfoExtractor.php [hunk 9]
```diff
@@ -58,7 +59,23 @@ public function getLongDescription(string $class, string $property, array $conte
      */
     public function getType(string $class, string $property, array $context = []): ?Type
     {
-        return $this->extract($this->typeExtractors, 'getType', [$class, $property, $context]);
+        foreach ($this->typeExtractors as $extractor) {
+            if (!method_exists($extractor, 'getType')) {
```
Comment (mtarld) [inline src/Symfony/Component/PropertyInfo/PropertyInfoExtractor.php:63]: Maybe we should leave a comment telling that this piece of code must be removed in 8.0?

File: src/Symfony/Component/PropertyInfo/PropertyInfoCacheExtractor.php [hunk 10]
```diff
@@ -61,7 +62,40 @@ public function getProperties(string $class, array $context = []): ?array
      */
     public function getType(string $class, string $property, array $context = []): ?Type
     {
-        return $this->extract('getType', [$class, $property, $context]);
+        try {
```
Comment (mtarld) [inline src/Symfony/Component/PropertyInfo/PropertyInfoCacheExtractor.php:65]: Same here, we can tell that it might be removed in 8.0

**Review by mtarld — APPROVED** [review]

**Review by phansys — APPROVED** [review]

File: src/Symfony/Component/PropertyInfo/PropertyInfoExtractor.php (hunk 9 above)
Comment (chalasr) [reply src/Symfony/Component/PropertyInfo/PropertyInfoExtractor.php:63]: As this code uses deprecated classe it will be massively patched anyway in 8.0 so it looks safe not to add a comment

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Component/PropertyInfo/PropertyInfoCacheExtractor.php (hunk 10 above)
Comment (xabbuh) [reply src/Symfony/Component/PropertyInfo/PropertyInfoCacheExtractor.php:65]: see Robin's comment here: https://github.com/symfony/symfony/pull/57459#discussion_r1905229622
