### PR TITLE
[FrameworkBundle] fix wiring of annotations.cached_reader

### LINKED ISSUE #46202: Access the annotation_reader public service triggers an error
### Symfony version(s) affected

4.4.39+, 5.4.6+

### Description

https://github.com/symfony/symfony/commit/ca566204d34dba70e16da2d2f543523c0b0a6fd2 changed the way the cached annotation reader is managed in the late compiler pass AddAnnotationsCachedReaderPass

But making the `annotations.cached_reader` service public during optimizations and turning it private after them breaks the expectations of the optimizations themselves (a public alias pointing to a public service does not get optimized the same than a public alias pointing to a private service).
The `annotation_reader` service is the only service for which we do such weird thing to allow using that service (without caching) while the container is being built.
But we should really have a functional test ensuring that the logic does not break the public access to the service.

### How to reproduce

Put that in a WebTestCase (or change the way to get a booted kernel):

```php
        self::bootKernel();

        $annotationReader = self::$kernel->getContainer()->get('annotation_reader');
```

This is producing an error because the compiled container optimized the `annotation_reader` alias in a way relying on the fact that `annotations.cached_reader` would be public, but this changed after.

Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The "annotations.cached_reader" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #46202
| License       | MIT
| Doc PR        | -

Also fixes https://github.com/symfony/symfony/pull/26088#issuecomment-379265902

Instead of trying to hack the compilation of the container to prevent it from inlining `annotations.cached_reader`, this PR relies on an `container.do_not_inline` tag that just does that, prevent inlining so that removing passes can reliably fetch the corresponding services from the container by id or by tag.

### CODE REVIEW

**Review by chalasr — APPROVED** [review]
Nice.

**Comment by chalasr** [comment]
(would be even better with a test case if possible)

File: src/Symfony/Component/DependencyInjection/Compiler/DecoratorServicePass.php [hunk 1]
```diff
@@ -40,6 +40,10 @@ public function process(ContainerBuilder $container)
         }
         $decoratingDefinitions = [];
 
+        $tagsToKeep = $container->hasParameter('container.behavior_describing_tags')
+            ? $container->getParameter('container.behavior_describing_tags')
+            : ['container.do_not_inline', 'container.service_locator', 'container.service_subscriber'];
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Compiler/DecoratorServicePass.php:45]: should those be merged with the parameter instead ?

**Review by stof — COMMENTED** [review]
Would be great to add a test fetching the annotation reader public service from the container as a functional test

File: src/Symfony/Component/DependencyInjection/Compiler/DecoratorServicePass.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Compiler/DecoratorServicePass.php:45]: I don't think so: giving full control to the parameter is more flexible to me.

**Comment by nicolas-grekas** [comment]
Test added.

Status: needs review

File: src/Symfony/Component/DependencyInjection/Compiler/DecoratorServicePass.php (hunk 1 above)
Comment (stof) [reply src/Symfony/Component/DependencyInjection/Compiler/DecoratorServicePass.php:45]: but does it really make sense to disable core ones ? It would mean that if a project customizes the list, they would not benefit from new additions done in the core like this bugfix until they discover this internal change to the default value.

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Compiler/DecoratorServicePass.php:45]: This tag is already used in `ResolveInstanceofConditionalsPass` where is *has* to contain `container.service_locator` and other core tags. This code doesn't introduce anything new to me, convention-wise (since this parameter works by convention).

Comment (stof) [reply src/Symfony/Component/DependencyInjection/Compiler/DecoratorServicePass.php:45]: ok
