### PR TITLE
[Messenger] Alias the AMQP "user" connection option to "login"

### LINKED ISSUE #61922: AMQP messenger - User | Login param confusion
### Symfony version(s) affected

7.3

### Description

Using separate component `symfony/amqp-messenger`
Using `php8.4-amqp` version `2.1.2-5+ubuntu24.04.1+deb.sury.org+1`
On one side:

- `\Transport\Connection::fromDsn()` documentation, line 126 says: `user | login`
- `\Transport\Connection::AVAILABLE_OPTIONS`, line 44 says `user` is a valid connection option

On the other:

- `AMQPConnection` from pecl-amqp only accepts `login`, not `user`
- [`php-amqp`](https://github.com/php-amqp/php-amqp/blob/latest/amqp_connection_resource.h) source only accepts `login`, not `user`
- `fromDsn()` does set `login` param if `user` is set 
- Constructor does not set `login` param

Resulting in:

- If using constructor and setting `user` but not `login`, as documentation implies as valid, `php-amqp` interprets that no user was provided and uses default value `guest`

### How to reproduce

- Install `symfony/amqp-messenger` and required libraries
- Create a new Connection object using constructor with valid params. Use param `user` but not `login`. Set `user` param to something other than `guest`
- Debug Connection::channel(). Check line 491. See how `AmqpFactory::createConnection()` has set `login` param to `guest`

### Possible Solution

Either:

- Set `login` param when `user` para is set on `Connection::__construct()` similar to `Connection::fromDsn()`
- Change mentioned documentation to reflect that `user` is not a valid connection parameter

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lacatoire**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fixes #61922
| License       | MIT

The AMQP `Connection` documents `user` as an alias for `login` (the only credential key understood by `php-amqp`), and lists both in `AVAILABLE_OPTIONS`. However the alias is only honored by `Connection::fromDsn()` when the user is in the DSN URL part (`user@host`); if it is passed via the constructor or via `?user=…` in the DSN query string, it is stored under `user` but `php-amqp` reads it from `login` and silently falls back to the default `guest` credential, leading to authentication failures that are hard to diagnose.

Normalize `user` to `login` at the top of the constructor: when both are set, the explicit `login` wins (and the `user` entry is dropped); when only `user` is provided, it is moved to `login`. This keeps the documented `user|login` equivalence and removes the inconsistency between DSN URL and DSN query string / direct constructor usage.

Adds two unit tests covering both the alias and the precedence rule.

### CODE REVIEW

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php [hunk 1]
```diff
@@ -105,6 +105,15 @@ public function __construct(array $connectionOptions, array $exchangeOptions, ar
             throw new LogicException(\sprintf('You cannot use the "%s" as the "amqp" extension is not installed.', __CLASS__));
         }
 
+        // The "user" option is documented as an alias for "login" (which is the only key understood
+        // by php-amqp). Normalize it here so passing "user" via the constructor or via DSN query
+        // string ("?user=…") works the same as setting "login" directly. Without this, php-amqp
+        // silently falls back to the default "guest" credential.
+        if (isset($connectionOptions['user']) && !isset($connectionOptions['login'])) {
+            $connectionOptions['login'] = $connectionOptions['user'];
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php]:
```suggestion
        if (isset($connectionOptions['user'])) {
            $connectionOptions['login'] ??= $connectionOptions['user'];
```

File: src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php [hunk 2]
```diff
@@ -34,6 +34,64 @@ public function testItCannotBeConstructedWithAWrongDsn()
...
+        ]);
+
+        $r = new \ReflectionProperty(Connection::class, 'connectionOptions');
+        $options = $r->getValue($connection);
+
+        $this->assertSame('bob', $options['login']);
+        $this->assertArrayNotHasKey('user', $options);
+    }
+
+    public function testFromDsnQueryStringUserIsAliasedToLogin()
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php]: I'm not sure we need 3 test cases for this

**Comment by nicolas-grekas** [comment]
Thank you @lacatoire.
