### PR TITLE
[Cache][Messenger] Align Redis sentinel auth handling across components

### LINKED ISSUE #58727: [Cache] Redis server redis:6379 went away
### Symfony version(s) affected

*

### Description

Redis adapter won't work with redis sentinels.

### How to reproduce

1. Setup redis (password protected) with redis sentinels (password protected).
2. Use DSN: `redis:default:redisMasterPassword@?host[redis-sentinel:26379]&redis_sentinel=mymaster&auth=redisSentinelPassword`
3. Redis failed with error: Redis connection failed: Redis server redis:6379 went away

### Possible Solution

The problem is here: https://github.com/symfony/symfony/blob/7.2/src/Symfony/Component/Cache/Traits/RedisTrait.php#L290
Should be: $extra['auth'] = $auth ?? $params['auth'];

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58727
| License       | MIT

Instead of #62218 and #61783 /cc @FlashBlack and @WedgeSama
This is too heavy change for 6.4 IMHO but required bugfix for 7.4, thus the target.
This patch aligns the behavior of both components, esp. regarding sentinel auth handling.

A DSN like `redis://foo@localhost?sentinel=bar&auth=baz` will pass `foo` to the the master and `baz` to the sentinel.

### CODE REVIEW

File: src/Symfony/Component/Cache/Tests/Traits/RedisTraitTest.php [hunk 1]
```diff
@@ -204,4 +204,78 @@ public static function provideInvalidDbIndexDsnParameter(): array
...
+
+    public function testPredisMasterAuthFallsBackToQueryAuth()
+    {
+        $predisClass = new class extends \Predis\Client {
+            public static array $captured = [];
+            private object $connection;
+
+            public function __construct($parameters = null, $options = null)
+            {
+                self::$captured = [
```
Comment (ckrack) [inline src/Symfony/Component/Cache/Tests/Traits/RedisTraitTest.php]: I like the way you made this unit-testable 👍🏼 
But let's use dataproviders and test all cases, also for the other Classes to make sure the behaviour is the same?

What I am lacking:
- redis://user:pass@host
- redis://user@pass@host?auth[]=otheruser&auth[]=otherpass 
- redis://host?auth[]=user&auth[]=pass
- redis://host?auth[username]=user&auth[password]=pass
- redis://host?auth[password]=password&auth[username]=user (does not work?)
- redis://host & auth in options array
- combination of all of the above & auth in options (show and ensure precedence)

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php
Comment (ckrack) [inline src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php:1]: So we keep the partially duplicated code?
It's most likely a question of where to put this, if we were to extract it, right?
One is a component, one is a bridge. Both will be split-out in the monorepo-split?

File: src/Symfony/Component/Cache/Tests/Traits/RedisTraitTest.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Cache/Tests/Traits/RedisTraitTest.php]: thanks for the suggestion, data providers added
`auth[username/password]` was not supported and should not be part of this PR.
Not sure it'd be desired either - more options lead to confusion ;)

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php
Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php:1]: > we keep the partially duplicated code

yep. I had a look and there are too many subtle differences. We could dedup part of the logic but that wouldn't make a proper abstraction. Not worth the complexity.
