### PR TITLE
[Serializer] fix inherited properties normalization

### LINKED ISSUE #61988: [Serializer] Inherited "is"-properties are normalized incorrectly
### Symfony version(s) affected

6.4.26, 7.3.4

### Description

The changes introduced in https://github.com/symfony/symfony/pull/61097 appear not to properly handle inherited properties.

In earlier versions of the serializer, "is"-properties from both the serialized class and any parent classes were (incorrectly) normalized without the "is" prefix, if the getter had the same name as the property, as is often the case with "isser" methods. The fix introduced by the aforementioned PR currently only works when the property is declared in the normalized class itself. If the property is declared in a parent class, the old behavior still occurs.

### How to reproduce

`composer require symfony/property-access symfony/serializer`

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

class Base
{
    private bool $isTest = false;

    public function isTest(): bool
    {
        return $this->isTest;
    }

    public function setIsTest(bool $test): void
    {
        $this->isTest = $test;
    }
}

class Child extends Base {}

$serializer = new Serializer([new ObjectNormalizer()], [new JsonEncoder()]);
echo $serializer->serialize(new Base(), 'json') . PHP_EOL;
echo $serializer->serialize(new Child(), 'json') . PHP_EOL;

```

Old output (up until 6.4.25):
```
{"test":false}
{"test":false}
```

New output:
```
{"isTest":false}
{"test":false}
```

Expected output:
```
{"isTest":false}
{"isTest":false}
```

### Possible Solution

I only briefly looked at the [implementation](https://github.com/symfony/symfony/blob/7.4/src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php#L98), but I believe that `$reflClass->hasProperty(...)` returns `false` for inherited properties and should therefore be replaced with something like `$reflMethod->getDeclaringClass()->hasProperty(...)`. I am not sure if this has any other implications though.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Link1515**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #61988 
| License       | MIT

Introduce `hasParentProperty()` to detect and use properties defined in parent classes.

### CODE REVIEW

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php [hunk 1]
```diff
@@ -139,6 +139,18 @@ protected function extractAttributes(object $object, ?string $format = null, arr
         return array_keys($attributes);
     }
 
+    private function hasPropertyInHierarchy(\ReflectionClass $class, string $propName): bool
```
Comment (OskarStark) [inline src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]:
```suggestion
    private function hasParentProperty(\ReflectionClass $class, string $propName): bool
```
?

Comment (Link1515) [reply src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]: OK!

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php [hunk 2]
```diff
@@ -107,7 +107,7 @@ protected function extractAttributes(object $object, ?string $format = null, arr
                 'i' => str_starts_with($name, 'is') && isset($name[$i = 2]),
                 default => false,
             } && !ctype_lower($name[$i])) {
-                if ($reflClass->hasProperty($name)) {
+                if ($reflClass->hasProperty($name) || $this->hasParentProperty($reflClass, $name)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]:
```suggestion
                if ($this->hasProperty($reflClass, $name)) {
```

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php [hunk 3]
```diff
@@ -139,6 +139,18 @@ protected function extractAttributes(object $object, ?string $format = null, arr
...
     }
 
+    private function hasParentProperty(\ReflectionClass $class, string $propName): bool
+    {
+        while ($class) {
+            if ($class->hasProperty($propName)) {
+                return true;
+            }
+            $class = $class->getParentClass();
+        }
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]:
```suggestion
    private function hasProperty(\ReflectionClass $class, string $propName): bool
    {
        do {
            if ($class->hasProperty($propName)) {
                return true;
            }
        } while($class = $class->getParentClass());
```

**Review by nicolas-grekas — COMMENTED** [review]
LGTM, here are some minor CS suggestions

**Comment by frozenbrain** [comment]
I would suggest limiting the property lookup to the class the getter was declared in (`$reflMethod->getDeclaringClass()`) and _maybe_ its parents.

Otherwise the results could change by introducing new properties in child classes, which could cause confusion:
```php
class Base
{
    private bool $test = false;

    public function isTest(): bool
    {
        return $this->test;
    }

    public function setTest(bool $test): void
    {
        $this->test = $test;
    }
}

class Child extends Base {
    private bool $isTest = true;
}

$serializer = new Serializer([new ObjectNormalizer()], [new JsonEncoder()]);
echo $serializer->serialize(new Base(), 'json') . PHP_EOL;  // {"test":false}
echo $serializer->serialize(new Child(), 'json') . PHP_EOL; // {"isTest":false}
```
This is, of course, just a theoretical example, but I can't think of a case in which this behavior could be useful and starting at the most likely correct class would reduce the number of checks/iterations necessary considerably for classes with many inherited properties.

Another thing: I think for consistency's sake the check in [line 115](https://github.com/symfony/symfony/pull/62007/files#diff-397b4689ce56cc95e54911f6d78639bb3258a9ee9b36bfa06ec719e9635e6b1dR115) should behave the same way.

**Review by jolelievre — APPROVED** [review]
Hi, I don't have the rights to approve this, but the related bug https://github.com/symfony/symfony/issues/61988 is preventing us from updating the latest patch

So +1 on this one, it seems fine, but I'm not an expert 😅

The failing tests don't seem to be related to the PR though 🤔 Could there be some radon fails on some environments and re-running the tests would succeed?

**Comment by Link1515** [comment]
> I would suggest limiting the property lookup to the class the getter was declared in (`$reflMethod->getDeclaringClass()`) and _maybe_ its parents.
> 
> Otherwise the results could change by introducing new properties in child classes, which could cause confusion:
> ```php
> class Base
> {
>     private bool $test = false;
> 
>     public function isTest(): bool
>     {
>         return $this->test;
>     }
> 
>     public function setTest(bool $test): void
>     {
>         $this->test = $test;
>     }
> }
> 
> class Child extends Base {
>     private bool $isTest = true;
> }
> 
> $serializer = new Serializer([new ObjectNormalizer()], [new JsonEncoder()]);
> echo $serializer->serialize(new Base(), 'json') . PHP_EOL;  // {"test":false}
> echo $serializer->serialize(new Child(), 'json') . PHP_EOL; // {"isTest":false}
> ```
> This is, of course, just a theoretical example, but I can't think of a case in which this behavior could be useful and starting at the most likely correct class would reduce the number of checks/iterations necessary considerably for classes with many inherited properties.
> 
> Another thing: I think for consistency's sake the check in [line 115](https://github.com/symfony/symfony/pull/62007/files#diff-397b4689ce56cc95e54911f6d78639bb3258a9ee9b36bfa06ec719e9635e6b1dR115) should behave the same way.

@frozenbrain, thank you for the feedback, I've made the changes.

**Comment by nicolas-grekas** [comment]
Thank you @Link1515.
