### PR TITLE
[Inflector][String] Fixed pluralize "coupon"

### LINKED ISSUE #40467: EnglishInflector incorrectly pluralizes "coupon"
**Symfony version(s) affected**: 5.1.2

**Description**
The `Symfony\Component\String\Inflector\EnglishInflector` incorrectly pluralizes the string "coupon" to "coupa". English is not my first language and i've never heard the word "coupa" before. I've searched for the plural version of coupon and didn't find "coupa" anywhere.

**How to reproduce**
With these two lines the problem should be reproducable:

```php
$inflector = new EnglishInflector();
$plural = $inflector->pluralize( "coupon" )[ 0 ];
echo $plural; // echoes "coupa"
```

**Additional context**
symfony/string 5.1.2

### PR DESCRIPTION
**Pull request by Nyholm**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40467
| License       | MIT
| Doc PR        | 

The rule for "bacteria (bacterium), criteria (criterion), phenomena (phenomenon)" is producing this behaviour. I added an exception to the "criterion exception". 

"coupon" is an old French word, that is maybe why it does not follow the classic "on" rule... I dont know. The test passes and I dont think I've added any side-effects. 

This is also my first time working with the `EnglishInflector`.

### CODE REVIEW

**Comment by derrabus** [comment]
This issue needs to be fixed on 4.4 (inflector component).

**Comment by Nyholm** [comment]
You are correct. The bug existed in 4.4 in the inflector component too. I guess it will be merged up properly if I target 4.4. 

The PR is updated.

**Review by javiereguiluz — APPROVED** [review]

File: src/Symfony/Component/Inflector/Inflector.php [hunk 1]
```diff
@@ -231,6 +231,9 @@ final class Inflector
         // bacteria (bacterium), criteria (criterion), phenomena (phenomenon)
         ['noi', 3, true, true, 'ions'],
 
+        // coupon (coupons)
+        ['nopuoc', 6, true, true, 'coupons'],
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Inflector/Inflector.php]: maybe we can widen this to
`['nop', 3, true, true, 'pons'],`

**Review by derrabus — APPROVED** [review]

File: src/Symfony/Component/Inflector/Inflector.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Inflector/Inflector.php]: I confirm we should do this, see https://en.wiktionary.org/wiki/Category:English_plurals_ending_in_%22-a%22: it lists no English words that end with `pon` and have a `pa` plural.

**Review by nicolas-grekas — APPROVED** [review]
(updated)

**Comment by nicolas-grekas** [comment]
Thank you @Nyholm.

**Comment by Nyholm** [comment]
Thank you for merging.
