### PR TITLE
[Intl] Taking into account bibliographic + overlong

### LINKED ISSUE #50142: [Intl] nl language can be represented as dut and nld
### Symfony version(s) affected

6.1.4

### Description

Found an issue with ISO-3 alias

ER:
ISO-3 dut
ISO-2 nl

AR:
Couldn't read the indices [Alpha3ToAlpha2][dut] for the locale "meta" 

https://www.loc.gov/standards/iso639-2/php/langcodes-keyword.php?SearchTerm=dut&SearchType=ALL
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

### How to reproduce

1. install symfony/intl
2. 
```
Languages::getAlpha2Code('dut')
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by oleg-andreyev**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no 
| Tickets       | Fix #50142 
| License       | MIT
| Doc PR        | -

When building Alpha3 and aliases take into account `bibliographic` type.

### CODE REVIEW

**Comment by oleg-andreyev** [comment]
fabbot is failing https://fabbot.io/report/symfony/symfony/50943/a87c5067c97993d87929f8f14fdee7d8c45f9678 trying to change `dum` to `dumb`

**Comment by oleg-andreyev** [comment]
@fabpot @nicolas-grekas

File: src/Symfony/Component/Intl/Data/Generator/RegionDataGenerator.php [hunk 1]
```diff
@@ -181,7 +181,7 @@ private function generateAlpha2ToAlpha3Mapping(array $countries, ArrayAccessible
 
         foreach ($aliases as $alias => $data) {
             $country = $data['replacement'];
-            if (2 === \strlen($country) && 3 === \strlen($alias) && 'overlong' === $data['reason']) {
+            if (2 === \strlen($country) && 3 === \strlen($alias) && \in_array($data['reason'], ['overlong', 'bibliographic'], true)) {
```
Comment (ro0NL) [inline src/Symfony/Component/Intl/Data/Generator/RegionDataGenerator.php]: seems irrelevant?

File: src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php [hunk 2]
```diff
@@ -192,7 +192,7 @@ private function generateAlpha3Codes(array $languageCodes, ArrayAccessibleResour
         }));
 
         foreach ($metadataBundle['alias']['language'] as $alias => $data) {
-            if (3 === \strlen($alias) && 'overlong' === $data['reason']) {
+            if (3 === \strlen($alias) && \in_array($data['reason'], ['overlong', 'bibliographic'], true)) {
```
Comment (ro0NL) [inline src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php]: im not sure they should be included in the full list: https://en.wikipedia.org/wiki/ISO_639-2#B_and_T_codes

> In general the T codes are favored;

File: src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php [hunk 3]
```diff
@@ -209,7 +209,7 @@ private function generateAlpha2ToAlpha3Mapping(ArrayAccessibleResourceBundle $me
 
         foreach ($aliases as $alias => $data) {
             $language = $data['replacement'];
-            if (2 === \strlen($language) && 3 === \strlen($alias) && 'overlong' === $data['reason']) {
+            if (2 === \strlen($language) && 3 === \strlen($alias) && \in_array($data['reason'], ['overlong', 'bibliographic'], true)) {
```
Comment (ro0NL) [inline src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php]: seems irrelevant

we should always point alpha2 to the T code variant

File: src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php [hunk 4]
```diff
@@ -243,7 +243,7 @@ private function generateAlpha3ToAlpha2Mapping(ArrayAccessibleResourceBundle $me
 
         foreach ($metadataBundle['alias']['language'] as $alias => $data) {
             $language = $data['replacement'];
-            if (2 === \strlen($language) && 3 === \strlen($alias) && 'overlong' === $data['reason']) {
+            if (2 === \strlen($language) && 3 === \strlen($alias) && \in_array($data['reason'], ['overlong', 'bibliographic'], true)) {
```
Comment (ro0NL) [inline src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php:246]: :+1:

File: src/Symfony/Component/Intl/Data/Generator/RegionDataGenerator.php (hunk 1 above)
Comment (oleg-andreyev) [reply src/Symfony/Component/Intl/Data/Generator/RegionDataGenerator.php]: Probably not , as Alpha2 should be resolved into A variant of Alpha3

Comment (ro0NL) [reply src/Symfony/Component/Intl/Data/Generator/RegionDataGenerator.php]: i dont see any bibliographic entries in metadata under terrority, nor any changes in the compile artifacts

File: src/Symfony/Component/Intl/Resources/data/languages/meta.php [hunk 5]
```diff
@@ -654,630 +663,650 @@
         12 => 'aka',
         13 => 'akk',
         14 => 'akz',
-        15 => 'ale',
```
Comment (stof) [inline src/Symfony/Component/Intl/Resources/data/languages/meta.php]: @nicolas-grekas shouldn't we update the code generator to omit keys for those lists, so that it does not change all following lines when added a new value in the middle of the list ?

Comment (nicolas-grekas) [reply src/Symfony/Component/Intl/Resources/data/languages/meta.php]: Updated in #50955
@oleg-andreyev please rebase on branch 5.4 (and run the script to update the data to fix the conflicts)

File: src/Symfony/Component/Intl/Data/Generator/RegionDataGenerator.php (hunk 1 above)
Comment (oleg-andreyev) [reply src/Symfony/Component/Intl/Data/Generator/RegionDataGenerator.php]: reverted it.

File: src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php (hunk 2 above)
Comment (oleg-andreyev) [reply src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php]: reverted

File: src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php (hunk 3 above)
Comment (oleg-andreyev) [reply src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php]: reverted

File: src/Symfony/Component/Intl/Resources/data/languages/meta.php (hunk 5 above)
Comment (oleg-andreyev) [reply src/Symfony/Component/Intl/Resources/data/languages/meta.php]: rebased

**Review by stof — COMMENTED** [review]
shouldn't `generateAlpha3Codes` be updated to include them as well ?

**Comment by oleg-andreyev** [comment]
> shouldn't `generateAlpha3Codes` be updated to include them as well ?

I agree with @ro0NL, T codes are preferable, B are considered legacy.

https://github.com/symfony/symfony/pull/50943#discussion_r1260707120

**Comment by oleg-andreyev** [comment]
I'll squash commits before merge.

**Review by nicolas-grekas — APPROVED** [review]
(please squash if you can yes)

**Comment by oleg-andreyev** [comment]
> (please squash if you can yes)

One commit is related to update-data on MacOS (fix)
Second is actually about this ticket.

I hope it's okay (prefer more or less clean and separate history)

**Comment by nicolas-grekas** [comment]
We always squash so that one PR=one commit. This is the same topic :)

**Comment by oleg-andreyev** [comment]
> We always squash so that one PR=one commit. This is the same topic :)

Not a problem, now one commit.

**Comment by nicolas-grekas** [comment]
Thank you @oleg-andreyev.
