### PR TITLE
[Security][SecurityBundle] Add `#[IsCsrfTokenValid]` attribute

### LINKED ISSUE #52947: What about an `IsCsrfTokenValid` attribute?
### Description

POST only actions like delete actions are likely to use such kind of code:
```php
if (!$this->isCsrfTokenValid('delete_example', $request->request->getString('_token'))) {
    throw new BadRequestHttpException('This token is invalid');
}
```
What about introducing a new `IsCsrfTokenValid` attribute that takes the id and optionally the token key to avoid repeating the `if` check.

If accepted I can try a PR during the Hackday 🙂

### Example

```php
#[IsCsrfTokenValid('delete_example')]
public function deleteAction(): Response
{
    /// ...
```

### PR DESCRIPTION
**Pull request by yguedidi**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #52947
| License       | MIT

#SymfonyHackday

### CODE REVIEW

File: src/Symfony/Component/Security/Http/EventListener/IsCsrfTokenValidAttributeListener.php [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+    {
+        /** @var IsCsrfTokenValid[] $attributes */
+        if (!\is_array($attributes = $event->getAttributes()[IsCsrfTokenValid::class] ?? null)) {
+            return;
+        }
+
+        $request = $event->getRequest();
+
+        foreach ($attributes as $attribute) {
+            if (!$this->csrfTokenManager->isTokenValid(new CsrfToken($attribute->id, $request->request->getString($attribute->tokenKey)))) {
```
Comment (yguedidi) [inline src/Symfony/Component/Security/Http/EventListener/IsCsrfTokenValidAttributeListener.php:42]: should support for query parameters be added?

File: src/Symfony/Component/Security/Http/EventListener/IsCsrfTokenValidAttributeListener.php [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+                throw new InvalidCsrfTokenException('Invalid CSRF token.');
+            }
+        }
+    }
+
+    public static function getSubscribedEvents(): array
+    {
+        return [KernelEvents::CONTROLLER_ARGUMENTS => ['onKernelControllerArguments', 20]];
```
Comment (yguedidi) [inline src/Symfony/Component/Security/Http/EventListener/IsCsrfTokenValidAttributeListener.php]: should the priority be 21 to be executed before `IsGranted`?

File: src/Symfony/Component/Security/Http/EventListener/IsCsrfTokenValidAttributeListener.php (hunk 1 above)
Comment (wouterj) [reply src/Symfony/Component/Security/Http/EventListener/IsCsrfTokenValidAttributeListener.php:42]: Hmm, is there a use-case for CSRF protection on GET requests? I think we should advocate using POST/PATCH/PUT whenever your action needs CSRF protection.

File: src/Symfony/Component/Security/Http/EventListener/IsCsrfTokenValidAttributeListener.php (hunk 2 above)
Comment (wouterj) [reply src/Symfony/Component/Security/Http/EventListener/IsCsrfTokenValidAttributeListener.php]: I'm not sure. Given the current situation always runs CSRF protection after authorization, I think it's OK to keep it after, unless there is a good (security) reason to move it before.

File: src/Symfony/Component/Security/Http/EventListener/IsCsrfTokenValidAttributeListener.php (hunk 1 above)
Comment (yguedidi) [reply src/Symfony/Component/Security/Http/EventListener/IsCsrfTokenValidAttributeListener.php:42]: I agree!

File: src/Symfony/Component/Security/Http/EventListener/IsCsrfTokenValidAttributeListener.php (hunk 2 above)
Comment (yguedidi) [reply src/Symfony/Component/Security/Http/EventListener/IsCsrfTokenValidAttributeListener.php]: My questioning here was more about performance optimization than security.
As an invalid CSRF will make the request to fail anyway, maybe not executing the potentially heavy computations involved by an `IsGranted` (e.g. database calls) could be a win?

Comment (yguedidi) [reply src/Symfony/Component/Security/Http/EventListener/IsCsrfTokenValidAttributeListener.php]: Go for 25 as seen face to face :)

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Component/Security/Http/CHANGELOG.md [hunk 3]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+7.1
+---
+
+* Add `#[IsCsrfTokenValid]` attribute
```
Comment (OskarStark) [inline src/Symfony/Component/Security/Http/CHANGELOG.md]:
```suggestion
 * Add `#[IsCsrfTokenValid]` attribute
```

File: src/Symfony/Component/Security/Http/EventListener/IsCsrfTokenValidAttributeListener.php [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+use Symfony\Component\HttpKernel\KernelEvents;
+use Symfony\Component\Security\Core\Exception\InvalidCsrfTokenException;
+use Symfony\Component\Security\Csrf\CsrfToken;
+use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;
+use Symfony\Component\Security\Http\Attribute\IsCsrfTokenValid;
+
+/**
+ * Handles the IsCsrfTokenValid attribute on controllers.
+ */
+class IsCsrfTokenValidAttributeListener implements EventSubscriberInterface
```
Comment (OskarStark) [inline src/Symfony/Component/Security/Http/EventListener/IsCsrfTokenValidAttributeListener.php]: Do we want to make it final?

File: src/Symfony/Component/Security/Http/Attribute/IsCsrfTokenValid.php [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+ *
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\Security\Http\Attribute;
+
+#[\Attribute(\Attribute::IS_REPEATABLE | \Attribute::TARGET_CLASS | \Attribute::TARGET_METHOD | \Attribute::TARGET_FUNCTION)]
```
Comment (OskarStark) [inline src/Symfony/Component/Security/Http/Attribute/IsCsrfTokenValid.php:14]: I am not sure what's the difference between METHOD and FUNCTION, but it looks like we only have tests for methods, do we? 🤔

Comment (yguedidi) [reply src/Symfony/Component/Security/Http/Attribute/IsCsrfTokenValid.php:14]: @OskarStark I inspired from the IsGranted attribute that apparently supports FUNCTION in addition to METHOD. And FUNCTION wasn't tested for IsGranted case.
Should I add test for it? or better remove the support of FUNCTION for now?

Comment (OskarStark) [reply src/Symfony/Component/Security/Http/Attribute/IsCsrfTokenValid.php:14]: If we have a use case add a test case, we should ofc provide a test case for the `IsGranted` in an extra PR too.

File: src/Symfony/Component/Security/Http/EventListener/IsCsrfTokenValidAttributeListener.php (hunk 4 above)
Comment (chalasr) [reply src/Symfony/Component/Security/Http/EventListener/IsCsrfTokenValidAttributeListener.php]: I think so 👍 The container wouldn't be able to properly handle any potential extra capacity added to a child attribute, hence extending autoconfigured attributes isn't supported basically.

**Review by dsdeboer — APPROVED** [review]
Nicely done 👏

File: src/Symfony/Component/Security/Http/Attribute/IsCsrfTokenValid.php (hunk 5 above)
Comment (chalasr) [reply src/Symfony/Component/Security/Http/Attribute/IsCsrfTokenValid.php:14]: I do agree there should be a test ideally, at least to avoid regressions especially. But, I'd be fine moving forward without one: here the use case for `TARGET_FUNCTION`  is that controllers can be any callable. Since controllers as callables are test-covered and there is no target-specific behavior with this attribute. We have plently of attributes in the same case including validator constraints.

Comment (OskarStark) [reply src/Symfony/Component/Security/Http/Attribute/IsCsrfTokenValid.php:14]: I am fine then 👍

Comment (wouterj) [reply src/Symfony/Component/Security/Http/Attribute/IsCsrfTokenValid.php:14]: I agree, imho we don't necessarily need to test this. This is by-design for all controller argument listeners and the controller argument event has tests to check if we support callables.

**Comment by chalasr** [comment]
I know the name of the proposed attribute is inline with the `#[IsGranted]` one and I'm fundamentally fine with it, yet I'm wondering if some more imperative name wouldn't read better  e.g. `#[ValidateCsrfToken]`, `#[ValidCsrfToken]`  or even `#[RequireValidCsrfToken`. Thoughts?

**Review by wouterj — APPROVED** [review]

**Comment by OskarStark** [comment]
> I know the name of the proposed attribute is inline with the #[IsGranted] one and I'm fundamentally fine with it, yet I'm wondering if some more imperative name wouldn't read better e.g. #[ValidateCsrfToken], #[ValidCsrfToken] or even #[RequireValidCsrfToken. Thoughts?

`#[HasValidCsrfToken]` ?

File: src/Symfony/Component/Security/Http/Attribute/IsCsrfTokenValid.php (hunk 5 above)
Comment (yguedidi) [reply src/Symfony/Component/Security/Http/Attribute/IsCsrfTokenValid.php:14]: then this is ready for final review 🙂

**Comment by yguedidi** [comment]
@chalasr it's more inline with the `AbstractController` helper function `->isCsrfTokenValid()`, like the `#[IsGranted]` is with `->isGranted()`

**Comment by wouterj** [comment]
> @chalasr it's more inline with the AbstractController helper function ->isCsrfTokenValid(), like the #[IsGranted] is with ->isGranted()

Sounds valid to me :+1: (I honestly didn't know we had this helper method in the abstract controller)

**Comment by fabpot** [comment]
@yguedidi Can you have a look at the tests, they seem broken by this PR.

**Comment by OskarStark** [comment]
Let's go with the name then 👍🏻

Thanks for the explanation ℹ️

**Comment by yguedidi** [comment]
> Can you have a look at the tests, they seem broken by this PR.

@fabpot Indeed low deps unit tests are broken by this PR!
I checked and I'm wondering what is the right fix.
Issue is that SecurityBundle will install security/http 6.4, so without the new listener.
Should I just upgrade the requirement to 7.1 or conditionally add the service if the class exists? or something else?

**Comment by fabpot** [comment]
> > Can you have a look at the tests, they seem broken by this PR.
> 
> @fabpot Indeed low deps unit tests are broken by this PR! I checked and I'm wondering what is the right fix. Issue is that SecurityBundle will install security/http 6.4, so without the new listener. Should I just upgrade the requirement to 7.1 or conditionally add the service if the class exists? or something else?

You need to bump the minimum version in SecurityBundle.

**Comment by yguedidi** [comment]
@fabpot SecurityBundle tests now pass! other failures seems unrelated

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @yguedidi.
