### PR TITLE
[Security] forward multiple attributes voting flag

### LINKED ISSUE #36280: Passing more than one Security attribute to "Symfony\Component\Security\Core\Authorization\AccessDecisionManager::decide()" is not supported.
**Symfony version(s) affected**: 5.0.7

**Description**  
I just updated from 5.0.6 to 5.0.7 and now I'm running into this Exception after Log in. That happens only when in dev environment. It also does not happen if the access control lists only one role.
For example, when
````

        - { path: "^/admin/", roles: [ROLE_ADMIN, ROLE_PROJECTMANAGER, ROLE_ASSISTANT, ROLE_ACCOUNTANT] }
        - { path: "^/kunden/", roles: [ROLE_CLIENT] }
````
everything's fine for clients, but not for admins

symfony

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36280
| License       | MIT
| Doc PR        |

### CODE REVIEW

File: src/Symfony/Component/Security/Core/Authorization/TraceableAccessDecisionManager.php [hunk 1]
```diff
@@ -48,7 +48,7 @@ public function __construct(AccessDecisionManagerInterface $manager)
     /**
      * {@inheritdoc}
      */
-    public function decide(TokenInterface $token, array $attributes, $object = null): bool
+    public function decide(TokenInterface $token, array $attributes, $object = null/*, bool $allowMultipleAttributes = false*/): bool
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Core/Authorization/TraceableAccessDecisionManager.php]: we need to also explicitly add the `@param` annotation to opt-out from the deprecation that will be triggered otherwise.

Comment (xabbuh) [reply src/Symfony/Component/Security/Core/Authorization/TraceableAccessDecisionManager.php]: added

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Comment by chq81** [comment]
@nicolas-grekas Thanks! Will this be merged in 5.0 as well? I am having the same issue in 5.0.7.

**Comment by nicolas-grekas** [comment]
Sure it will, we merge 4.4 into 5.0 periodically.

**Comment by chq81** [comment]
@nicolas-grekas Great, thanks!
