### PR TITLE
[FrameworkBundle] Fix `lint:container --resolve-env-vars`

### LINKED ISSUE #59028: lint:container --resolve-env-vars fails on new project
### Symfony version(s) affected

7.2

### Description

Resolved value of "default:kernel.runtime_mode:" did not result in an array value.

image

### How to reproduce

```bash
symfony new --webapp env-var-demo
cd  env-var-demo
bin/console lint:container --resolve-env-vars
```

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59028
| License       | MIT

7.2 EOL is around the corner :timer_clock: 

:warning: `--resolve-env-vars` still won’t work if you have parameters with two escaped percent signs.

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ContainerLintCommandTest.php [hunk 1]
```diff
@@ -24,27 +24,30 @@ class ContainerLintCommandTest extends AbstractWebTestCase
...
+        $this->assertSame($expectedExitCode, $exitCode);
         $this->assertStringContainsString($expectedOutput, $tester->getDisplay());
     }
 
     public static function containerLintProvider(): array
     {
         return [
-            'default container' => ['config.yml', 'The container was linted successfully'],
-            'missing dump file' => ['no_dump.yml', 'The container was linted successfully'],
+            ['escaped_percent.yml', false, 0, 'The container was linted successfully'],
```
Comment (MatTheCat) [inline src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ContainerLintCommandTest.php:46]: Cannot lint `escaped_percent.yml` with `--resolve-env-vars` yet.

**Comment by nicolas-grekas** [comment]
fabbot failure should be fixed now

File: src/Symfony/Bundle/FrameworkBundle/Command/ContainerLintCommand.php [hunk 2]
```diff
@@ -49,8 +50,10 @@ protected function execute(InputInterface $input, OutputInterface $output): int
         $io = new SymfonyStyle($input, $output);
         $errorIo = $io->getErrorStyle();
 
+        $resolveEnvVars = (bool) $input->getOption('resolve-env-vars');
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Command/ContainerLintCommand.php]: the cast is not needed, isn't it?

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Bundle/FrameworkBundle/Command/ContainerLintCommand.php (hunk 2 above)
Comment (MatTheCat) [reply src/Symfony/Bundle/FrameworkBundle/Command/ContainerLintCommand.php]: Maybe it was used to make a static analysis tool happy? I’ll remove it.

**Comment by nicolas-grekas** [comment]
Thank you @MatTheCat.
