### PR TITLE
[2.3][EventDispatcher] make listeners removable from an executed listener

### LINKED ISSUE #13972: [TraceableEventDispatcher] incorrect removeListener behavior.
If we try to remove the listener from the dispatcher while dispatching an event, the listener wount be removed.
Simple example:
```php
$eventDispatcher = new TraceableEventDispatcher(new EventDispatcher(), new Stopwatch());
$listener = function ($event, $eventName, $dispatcher) use (&$listener) {
    $dispatcher->removeListener('foo', $listener);
};
$eventDispatcher->addListener('foo', $listener);
$eventDispatcher->dispatch('foo');
$result = count($eventDispatcher->getListeners('foo'));
// expected, that $result == 0, but actually $result == 1
```
That's why, starting from 380d8052ac4f4329c60bb82caed5ed8bf3f6cebe ContextListener works  incorrectly in the debug enviroment.

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #13972 |
| License | MIT |
| Doc PR |  |

This fixes #13972 for Symfony 2.3. On Symfony 2.6 and higher, this has already been fixed with #14355.

### CODE REVIEW

File: src/Symfony/Component/HttpKernel/Tests/Debug/TraceableEventDispatcherTest.php [hunk 1]
```diff
@@ -12,6 +12,7 @@
 namespace Symfony\Component\HttpKernel\Tests\Debug;
 
 use Symfony\Component\EventDispatcher\EventDispatcher;
+use Symfony\Component\EventDispatcher\EventDispatcherInterface;
```
Comment (fabpot) [inline src/Symfony/Component/HttpKernel/Tests/Debug/TraceableEventDispatcherTest.php]: This one is not needed AFAICS

Comment (xabbuh) [inline src/Symfony/Component/HttpKernel/Tests/Debug/TraceableEventDispatcherTest.php]: indeed

**Comment by fabpot** [comment]
Thank you @xabbuh.
