### PR TITLE
[Console] Fixes question input encoding on Windows

### LINKED ISSUE #35842: German Umlauts in Console
**Symfony version(s) affected**: 5.0.4

**Description**  
German Umlauts ignored in Console Question Helper

**How to reproduce**  

```
protected function execute(InputInterface $objInput, OutputInterface $objOutput)
{
	$objHelper = $this->getHelper('question');

	$objQuestion = new Question('Title: ');

	$strTitle = $objHelper->ask($objInput, $objOutput, $objQuestion);

	$objOutput->writeln($strTitle);

        return 0;
}
```

If i type "aaaöäübbb" in console i just get "aaa\\\bbb" as outout. If i just type umlauts like "öäü" the output is empty.

### LINKED ISSUE #36324: [Console] Special characters on asking question
**Symfony version(s) affected**: 5.0.7

**Description**  
In a command, when the user answers a question with special characters with accents (é, è, à, ...); the output doesn't consider these characters and removes them from the string.

**How to reproduce**  
1. Create a command
2. In the `execute` method, write the code below:
```php
$io = new SymfonyStyle($input, $output);
$userInput = $io->ask('Type here');
$io->writeln($userInput);
return 0;
```
3. Execute the command and type such as `Bonjour à tous !`
4. The output should be `Bonjour \ tous !`
> I've reproduced the project in a [repository](https://github.com/YaFou/symfony-bug-console).

**Possible Solution**  
It's possibly the encoding of my terminal or in the source code.

**Additional context**  
I use the Windows Terminal Preview with Git Bash. And I've tested on the Windows terminal.
image

### LINKED ISSUE #37278: [Console] - Special characters encoding issues
**Symfony version**
Symfony Console 5.0 (only this bundle). 

**Description**
I'm only using Symfony Console to generate PHP code and I have to ask informations to the user. When I run my script, I must use special characters to display a question, and it is displayed nicely. But when I submit informations with special characters, all of them are replaced by blank spaces.

**Example**
``` bash
Please write the value for the field "Libellé" : # The character rendering is fine there
> My favourite libellé # User input
The following libellé has been defined : My favourite libell  # Only the answer has been "sanitized"
```

**Possible solutions**
I tried to add `setTrimmable(false)` to the Question object, but it didn't help. I also tried to create a `validate` function, to see if I could get the input in it raw form, but the input is still sanitized. I also tried to save the input in a variable and convert it to UTF-8 but it couldn't change something about it. I tried the PHP functions `iconv` and `mb_convert_encoding` and none of them could solve the issue.

Do you guys have an idea about the issue origin and if there is a way to fix it ?

### LINKED ISSUE #37495: QuestionHelper input breaks UTF-8 characters
**Symfony version(s) affected**: 5.1.0

**Description**  
When an UTF-8 character is confirmed in a console as a response to QuestionHelper's question, it gets replaced by `'\'` or `''`.
E.g. `'Čeština'` > `'e\tina'`. My OS is Windows 10.

**How to reproduce**  
```
// inside Command::execute

$response = $questionHelper->ask($input, $output,
    new Question("Write something containing UTF-8 characters")
);
// response contains UTF-8 characters replaced by '\' or removed
```

### PR DESCRIPTION
**Pull request by YaFou**
| Q             | A
| ------------- | ---
| Branch?       | 3.4 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #35842, Fix #36324, Fix #37495 and Fix #37278 
| License       | MIT
| Doc PR        | no 

To ask a question to a user, the [QuestionHelper](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Helper/QuestionHelper.php) use [`fgets`](https://www.php.net/manual/en/function.fgets.php). However, special characters are not supported on Windows with this function (like accents: `é`, `à`, `ö`). The solution is to set a special encoding with [`sapi_windows_cp_get`](https://www.php.net/manual/en/function.sapi-windows-cp-get).

> Before
```php
$stream = fopen('php://stdin', 'r');
$input = fgets($stream);
echo $input;

// input: "Bonjour à tous"
// output: 'Bonjour \ tous" or "Bonjour   tous"
```

> After
```php
// Check if the function exists because it only exists on Windows
if(function_exists('sapi_windows_cp_set')) {
    sapi_windows_cp_get(437);
}

$stream = fopen('php://stdin', 'r');
$input = fgets($stream);
echo $input;

// input: "Bonjour à tous"
// output: 'Bonjour à tous"
```

*Thanks to @bnjmnfnk for the solution 😉*

### CODE REVIEW

**Comment by chalasr** [comment]
Can you please add a test for this? It should run on windows only.

**Comment by YaFou** [comment]
> 
> 
> Can you please add a test for this? It should run on windows only.

Is there a group in PHPUnit to run only on Windows (like `@group windows`)? Else, how I can do it?

**Comment by chalasr** [comment]
If the function exists only on windows, it should be enough yes.
If you aren't sure, you can use a `'\\' === DIRECTORY_SEPARATOR` additional check for both code and tests, see e.g. https://github.com/symfony/symfony/blob/3308b25fe47d4c95e7c6eb2ca38e47173b2f789d/src/Symfony/Component/Console/Tests/Helper/QuestionHelperTest.php#L418-L420

**Comment by YaFou** [comment]
Ok thank you! I'm writing it.

**Comment by YaFou** [comment]
It's difficult to test it because the stream used for QuestionHelper tests is the PHP memory `php://memory`. However, this issue is only present in the console with `php://stdin`.
Does anyone have any idea?

**Comment by ostrolucky** [comment]
You can try php test case similar as https://github.com/symfony/symfony/blob/80d1f449831fbceefd481544c82f8244759eda4d/src/Symfony/Component/Console/Tests/phpt/uses_stdin_as_interactive_input.phpt

**Comment by YaFou** [comment]
> 
> 
> You can try phpt test case similar as https://github.com/symfony/symfony/blob/80d1f449831fbceefd481544c82f8244759eda4d/src/Symfony/Component/Console/Tests/phpt/uses_stdin_as_interactive_input.phpt

This solution does not work 😞

**Comment by chalasr** [comment]
Can you try the following test locally? Without your patch at first, in order to make sure it breaks under your setup.

```
--TEST--
QuestionHelper should parse special chars on windows input.
--STDIN--
à é
--FILE--
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Helper\QuestionHelper;
use Symfony\Component\Console\Question\Question;

$vendor = __DIR__;
while (!file_exists($vendor.'/vendor')) {
    $vendor = dirname($vendor);
}
require $vendor.'/vendor/autoload.php';

$output = new ConsoleOutput();
$output->write((new QuestionHelper())->ask(new ArgvInput(), $output, new Question("Special chars\n")));
exit(0);
?>
--EXPECTF--
Special chars
à é
```

**Comment by YaFou** [comment]
> 
> 
> Can you try the following test locally? Without your patch at first, in order to make sure it breaks under your setup.
> 
> ```
> --TEST--
> QuestionHelper should parse special chars on windows input.
> --STDIN--
> à é
> --FILE--
> <?php
> 
> use Symfony\Component\Console\Input\ArgvInput;
> use Symfony\Component\Console\Output\ConsoleOutput;
> use Symfony\Component\Console\Helper\QuestionHelper;
> use Symfony\Component\Console\Question\Question;
> 
> $vendor = __DIR__;
> while (!file_exists($vendor.'/vendor')) {
>     $vendor = dirname($vendor);
> }
> require $vendor.'/vendor/autoload.php';
> 
> $output = new ConsoleOutput();
> $output->write((new QuestionHelper())->ask(new ArgvInput(), $output, new Question("Special chars\n")));
> exit(0);
> ?>
> --EXPECTF--
> Special chars
> à é
> ```

No more results... I think PHPUnit ***simulate*** and standard input but does not take all behaviors of the `fgets` function.

**Review by chalasr — APPROVED** [review]
Works for me as is.

File: src/Symfony/Component/Console/Helper/QuestionHelper.php [hunk 1]
```diff
@@ -158,6 +158,10 @@ private function doAsk(OutputInterface $output, Question $question)
         $inputStream = $this->inputStream ?: STDIN;
         $autocomplete = $question->getAutocompleterValues();
 
+        if (\function_exists('sapi_windows_cp_set')) {
+            sapi_windows_cp_get(437);
```
Comment (fabpot) [inline src/Symfony/Component/Console/Helper/QuestionHelper.php:162]: Is it possible to add a comment to document what 437 means?

Comment (YaFou) [reply src/Symfony/Component/Console/Helper/QuestionHelper.php:163]: 👍 fixed

File: src/Symfony/Component/Console/Helper/QuestionHelper.php [hunk 2]
```diff
@@ -158,6 +158,11 @@ private function doAsk(OutputInterface $output, Question $question)
         $inputStream = $this->inputStream ?: STDIN;
         $autocomplete = $question->getAutocompleterValues();
 
+        if (\function_exists('sapi_windows_cp_set')) {
+            // Codepage used by cmd.exe on Windows to allow special characters (éàüñ).
+            sapi_windows_cp_get(437);
```
Comment (ostrolucky) [inline src/Symfony/Component/Console/Helper/QuestionHelper.php:163]: That doesn't look right. `function_exists` checks for `sapi_windows_cp_set`, but `sapi_windows_cp_get` is being used.

**Review by ostrolucky — CHANGES_REQUESTED** [review]

**Comment by nicolas-grekas** [comment]
[CP1252](https://en.wikipedia.org/wiki/Windows-1252) allows more diacritics and is already the default on my French VM. [CP850](https://en.wikipedia.org/wiki/Code_page_850) would be an alternate possibility.

Can you try and take 1252 if possible, 850 otherwise?

**Comment by nicolas-grekas** [comment]
Oh, note that [codepage 65001](https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers) is UTF-8, it would be even better. Can you give it a try?

**Comment by YaFou** [comment]
> 
> 
> [CP1252](https://en.wikipedia.org/wiki/Windows-1252) allows more diacritics and is already the default on my French VM. [CP850](https://en.wikipedia.org/wiki/Code_page_850) would be an alternate possibility.
> 
> Can you try and take 1252 if possible, 850 otherwise?



> 
> 
> Oh, note that [codepage 65001](https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers) is UTF-8, it would be even better. Can you give it a try?

Only 1252 and 850 work (and 437 of course). I think the better code page is 1252 because it provides a better characters support.

**Comment by nicolas-grekas** [comment]
Does the function return false is your case with 65001?
If yes, we could set(65001) ?: set(1252) maybe?

**Comment by YaFou** [comment]
> 
> 
> Does the function return false is your case with 65001?
> If yes, we could set(65001) ?: set(1252) maybe?

No it returns true but replaces `à` by nothing or `\`.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by chalasr** [comment]
Thanks for fixing this bug @YaFou.

**Comment by lpj145** [comment]
I'm facing this issue again in 5.2.x-dev, i'm using windows 10, before i ask question, all utf8 chars are wrong.

**Comment by YaFou** [comment]
> I'm facing this issue again in 5.2.x-dev, i'm using windows 10, before i ask question, all utf8 chars are wrong.

Thank you for your feedback @lpj145. Can you provide a screenshot from your terminal? Are you on Windows?

**Comment by vaites** [comment]
With this change, the value returned by the helper on Windows is a binary string. Take this example command:

```php
<?php

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\Question;

class TestCommand extends Command
{
    protected static $defaultName = 'app:test';

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $helper = $this->getHelper('question');
        $question = new Question('What? ');

        dump($helper->ask($input, $output, $question));

        return Command::SUCCESS;
    }
}
```

This is the output for the input *martínez*:

```
C:\Develop\htdocs\testing\symfony>php bin\console app:test
What? martínez
^ b"martÃ­nez"
```

If I remove the call to `sapi_windows_cp_get()` the result is this:

```
C:\Develop\htdocs\testing\symfony>php bin\console app:test
What? martínez
^ "mart\x00nez"
```

This issue was initially reported [here](https://github.com/statamic/cms/issues/2574), but after some tests I think the issue is caused by this change. I tested it using three terminal emulators: CMD, PowerPhell and Git Bash:

symfony-ask-encoding

**Comment by r3sist** [comment]
I have a similar issue on Windows 10, Symfony 5.2.6, Hungarian OS environment and chars like áíűőüöúóé.

After first ansfer output gets wrong charset even if I don't use any special characters in questions or answers. And it's not just the output, all the inner encoding settings become strange, e.g. `An exception has been thrown during the rendering of a template ("Invalid UTF-8 string.")` exception during execution.

Works:

```php
$command = $this->getApplication()->find('generate');

$generateArguments = [
    'project' => 'local',
];

return $command->run(new ArrayInput($generateArguments), $output);
```

Error:

```php
$helper = $this->getHelper('question');

$projectQuestion = new Question("Projekt: </> \n", 'local');
$project = $helper->ask($input, $output, $projectQuestion);

$command = $this->getApplication()->find('generate');

$generateArguments = [
    'project' => $project,
];

return $command->run(new ArrayInput($generateArguments), $output);
```
