### PR TITLE
[Yaml] drop comments while lexing unquoted strings

### LINKED ISSUE #59785: [Yaml] Incorrect parsing of objects with inline comments
### Symfony version(s) affected

6.4.18

### Description

The Yaml Component (**6.4.18**) has an issue parsing objects with inline comments. 

ℹ️ This issue is **not** present in version **6.4.13**.

### How to reproduce

```php
use Symfony\Component\Yaml\Yaml;

$yml = <<<'YML'
arguments:
  - {
      connect_timeout: 3, # Float describing the number of seconds to wait while trying to connect to a server
      timeout: 30 # Float describing the timeout of the request in seconds
  }
YML;

var_dump(Yaml::parse($yml));
```

Output:
```
array(1) {
  ["arguments"]=>
  array(1) {
    [0]=>
    array(2) {
      ["connect_timeout"]=>
      int(3)
      ["timeout"]=>
      string(59) "30 # Float describing the timeout of the request in seconds"
    }
  }
}
```

✅ **Expected:** integer value `30` in second element of array:

```php
[
    "arguments" => [
        [
            "connect_timeout" => 3,
            "timeout" => 30
        ]
     ]
]
```

❌  **Actual:** string value `30 # Float describing the timeout of the request in seconds`  in second element of array:

```php
[
    "arguments" => [
        [
            "connect_timeout" => 3,
            "timeout" => "30 # Float describing the timeout of the request in seconds"
        ]
     ]
]
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59785
| License       | MIT

### CODE REVIEW

**Comment by stof** [comment]
IIRC, a Yaml comment starts with a `#` that is either at the beginning of the line or is following a whitespace, but `url: http://example.com/#about` would not treat `about` as a comment.
Can you add more tests covering such cases ?

**Comment by xabbuh** [comment]
hm indeed

Status: Needs work

**Comment by xabbuh** [comment]
should be good now

Status: Needs Review

File: src/Symfony/Component/Yaml/Tests/ParserTest.php [hunk 1]
```diff
@@ -1751,6 +1751,19 @@ public function testParseMultiLineUnquotedString()
         $this->assertSame(['foo' => 'bar baz foobar foo', 'bar' => 'baz'], $this->parser->parse($yaml));
     }
 
+    public function testParseMultiLineUnquotedStringWithTrailingComment()
+    {
+        $yaml = <<<YAML
+{
+    foo: 3, # comment
+    bar: example.com/#about,
+    baz: 30 # comment
```
Comment (ro0NL) [inline src/Symfony/Component/Yaml/Tests/ParserTest.php]: `    #comment` for more variance?

File: src/Symfony/Component/Yaml/Parser.php [hunk 2]
```diff
@@ -1158,7 +1158,18 @@ private function lexInlineQuotedString(int &$cursor = 0): string
...
     {
         $offset = $cursor;
-        $cursor += strcspn($this->currentLine, '[]{},:', $cursor);
+
+        while ($cursor < strlen($this->currentLine)) {
+            if (in_array($this->currentLine[$cursor], ['[', ']', '{', '}', ',', ':'], true)) {
+                break;
+            }
+
+            if (' ' === $this->currentLine[$cursor] && '#' === ($this->currentLine[$cursor + 1] ?? '')) {
```
Comment (mtarld) [inline src/Symfony/Component/Yaml/Parser.php]: Shouldn't we handle `\t` as well?

Comment (stof) [reply src/Symfony/Component/Yaml/Parser.php]: According to https://yaml.org/spec/1.2.0/#id2577376, tabs are indeed valid as separate spaces too.

**Review by mtarld — APPROVED** [review]

File: src/Symfony/Component/Yaml/Tests/ParserTest.php (hunk 1 above)
Comment (xabbuh) [reply src/Symfony/Component/Yaml/Tests/ParserTest.php]: added

File: src/Symfony/Component/Yaml/Parser.php (hunk 2 above)
Comment (xabbuh) [reply src/Symfony/Component/Yaml/Parser.php]: Indeed, added as well.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.
