### PR TITLE
[Notifier][Slack] Error trown when having more than 10 fields specified #36346 

### LINKED ISSUE #36346: [Notifier][Slack] Error trown when having more than 10 fields specified
**Symfony version(s) affected**: 5.0

**Description**  
As written in [docs](https://api.slack.com/reference/block-kit/blocks#section) of Section block, for fields we have to had maximum 10 items specified.

**How to reproduce**  
Specifying more than 10 fields would introduce an error from Slack endpoint: `Unable to post the Slack message: invalid_blocks`

### PR DESCRIPTION
**Pull request by birkof**
| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #36346 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

As written in [docs](https://api.slack.com/reference/block-kit/blocks#section) of Section block, for fields we have to had maximum 10 items specified.

### CODE REVIEW

File: src/Symfony/Component/Notifier/Bridge/Slack/Block/SlackSectionBlock.php [hunk 1]
```diff
@@ -44,6 +44,9 @@ public function field(string $text, bool $markdown = true): self
             'text' => $text,
         ];
 
+        // Maximum number of items is 10
+        $this->options['fields'] = \array_slice($this->options['fields'], 0, 10);
```
Comment (fabpot) [inline src/Symfony/Component/Notifier/Bridge/Slack/Block/SlackSectionBlock.php:48]: Instead of silently removing items, I would throw an exception.

**Review by fabpot — CHANGES_REQUESTED** [review]

**Comment by fabpot** [comment]
@birkof Have you seen my comment? Do you agree?

File: src/Symfony/Component/Notifier/Bridge/Slack/Block/SlackSectionBlock.php (hunk 1 above)
Comment (birkof) [reply src/Symfony/Component/Notifier/Bridge/Slack/Block/SlackSectionBlock.php:48]: Yeap, you're right! ( seems this doesn't pop up on my notifications :-( )
I'll take care of this right away!

Comment (birkof) [reply src/Symfony/Component/Notifier/Bridge/Slack/Block/SlackSectionBlock.php]: @fabpot, agree with exception message?

**Review by fabpot — APPROVED** [review]

File: src/Symfony/Component/Notifier/Bridge/Slack/Block/SlackSectionBlock.php [hunk 2]
```diff
@@ -44,6 +44,11 @@ public function field(string $text, bool $markdown = true): self
             'text' => $text,
         ];
 
+        // Maximum number of items is 10
+        if (10 <= \count($this->options['fields'])) {
```
Comment (guilliamxavier) [inline src/Symfony/Component/Notifier/Bridge/Slack/Block/SlackSectionBlock.php:48]: should be `<`, with `<=` you throw not only for `count > 10` but also for `count == 10`

Comment (fabpot) [reply src/Symfony/Component/Notifier/Bridge/Slack/Block/SlackSectionBlock.php:48]: Good catch, fixed in 7bac792328

Comment (birkof) [reply src/Symfony/Component/Notifier/Bridge/Slack/Block/SlackSectionBlock.php:48]: @guilliamxavier you're right! I have tested more over [here](https://app.slack.com/block-kit-builder/T5JPWDX2T#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22text%22:%22A%20message%20*with%20some%20bold%20text*%20and%20_some%20italicized%20text_.%22,%22type%22:%22mrkdwn%22%7D,%22fields%22:%5B%7B%22type%22:%22mrkdwn%22,%22text%22:%221%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%222%22%7D,%7B%22type%22:%22plain_text%22,%22text%22:%223%22%7D,%7B%22type%22:%22plain_text%22,%22text%22:%224%22%7D,%7B%22type%22:%22plain_text%22,%22text%22:%225%22%7D,%7B%22type%22:%22plain_text%22,%22text%22:%226%22%7D,%7B%22type%22:%22plain_text%22,%22text%22:%227%22%7D,%7B%22type%22:%22plain_text%22,%22text%22:%228%22%7D,%7B%22type%22:%22plain_text%22,%22text%22:%229%22%7D,%7B%22type%22:%22plain_text%22,%22text%22:%2210%22%7D,%7B%22type%22:%22plain_text%22,%22text%22:%2211%22%7D%5D%7D%5D%7D) and you're right!

**Comment by dankirkd** [comment]
@fabpot @birkof - can you explain why there is this limitation?  It is exceptionally restrictive.
