### PR TITLE
[DependencyInjection] Fix importing PHP configs in the prepend extension method

### LINKED ISSUE #57936: [DependencyInjection] Import config inside of a bundle does not work anymore
### Symfony version(s) affected

7.1.0

### Description

Since Symfony 7.1 `prependExtension` with `$container->import`  ignores the passed configuration.

In documentation it is mentioned:

> Starting from Symfony 7.1, calling the [import()](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/DependencyInjection/Loader/Configurator/ContainerConfigurator.php#:~:text=function%20import) method inside prependExtension() will prepend the given configuration. In previous Symfony versions, this method appended the configuration.

But the configuration of the file is completely ignored.

As example we use a bundle to share configuration for the messenger component.

Part of output of `bin/console debug:config framework` with `symfony/dependency-injection: ^7.1`

```
    messenger:
        enabled: true
        routing: {  }
        serializer:
            default_serializer: messenger.transport.native_php_serializer
            symfony_serializer:
                format: json
                context: {  }
        transports: {  }
```

Part of output of `bin/console debug:config framework` with `symfony/dependency-injection: <7.1`

```
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: {  }
        transports:
            example:
                dsn: '%env(RABBITMQ_URL)%/%2f/messages'
                options:
                    exchange:
                        name: example.exchange
                        type: direct
                    queues:
                        example.queue:
                            binding_keys:
                                - example
                serializer: null
                failure_transport: null
                retry_strategy:
                    service: null
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
                rate_limiter: null
```

### How to reproduce

A bundle wich imports a PHP config file.

```php
// src/ExampleBundle.php
use Symfony\Component\HttpKernel\Bundle\AbstractBundle;

class ExampleBundle extends AbstractBundle
{
    public function prependExtension(ContainerConfigurator $container, ContainerBuilder $builder): void
    {
        $container->import('../config/packages/messenger.php');
    }
```

Example config file:

```php
// config/packages/messenger.php
return static function (FrameworkConfig $framework, ContainerConfigurator $container): void {
    $messenger = $framework->messenger();

    $messenger
        ->transport('example')
        ->dsn(env('RABBITMQ_URL') . '/%2f/messages')
        ->options([
            'exchange' => [
                'name' => 'example.exchange',
                'type' => 'direct',
            ],
            'queues' => [
                'example.queue' => [
                    'binding_keys' => ['example']
                ],
            ],
        ])
    ;
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by yceruto**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #57936
| License       | MIT

I missed this nesting case during https://github.com/symfony/symfony/pull/52843.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thank you @yceruto.

File: src/Symfony/Component/DependencyInjection/Loader/FileLoader.php [hunk 1]
```diff
@@ -92,6 +92,7 @@ public function import(mixed $resource, ?string $type = null, bool|string $ignor
             }
         } finally {
             --$this->importing;
+            $this->loadExtensionConfigs();
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Loader/FileLoader.php:95]: why do we need this here (even in case of exception) ?

Comment (yceruto) [reply src/Symfony/Component/DependencyInjection/Loader/FileLoader.php:95]: because there is a return statement inside the try block, so there is no other chance to load the collected ext config after `--$this->importing;` instruction

Comment (yceruto) [reply src/Symfony/Component/DependencyInjection/Loader/FileLoader.php:95]: btw, it's not about the exception at all, but if it happens I guess it doesn't matter if we try to prepend some configs afterward

**Comment by jfsenechal** [comment]
It doesn't work for more than one bundle 

Only the last bundle is taken into account

```bash
bin/console doctrine:mapping:info
 Found 3 mapped entities:

 [OK]   AcMarche\Cap\Entity\Commercant
 [OK]   AcMarche\Cap\Entity\CommercantGallery
 [OK]   AcMarche\Cap\Entity\CommercioBottin
```

**ABundle**

```php
class ABundle extends AbstractBundle
{
    public function getPath(): string
    {
        return \dirname(__DIR__);
    }

    public function loadExtension(array $config, ContainerConfigurator $container, ContainerBuilder $builder): void
    {
        $container->import('../config/services.php');
    }

    public function prependExtension(ContainerConfigurator $container, ContainerBuilder $builder): void
    {
        $container->import('../config/packages/doctrine.php');
    }
}
```

```php
//doctrine.php
return static function (DoctrineConfig $doctrine) {
    $doctrine->dbal()
        ->connection('default')
        ->url(env('DATABASE_URL')->resolve());
    $em = $doctrine->orm()->entityManager('default');
    $doctrine->dbal()->defaultConnection('default');
    $em->connection('default');

    $em->mapping('AcMarcheBottin')
        ->isBundle(false)
        ->type('attribute')
        ->dir('%kernel.project_dir%/src/AcMarche/Bottin/src/Entity')
        ->prefix('AcMarche\Bottin')
        ->alias('AcMarcheBottin');
};
```

**BBundle**
```php
class ABundle extends AbstractBundle
{
//...
//the same as above
}
```

```php
//doctrine.php
return static function (DoctrineConfig $doctrine) {
    $doctrine->dbal()
        ->connection('cap')
        ->url(env('DATABASE_URL_CAP')->resolve());

    $em = $doctrine->orm()->entityManager('cap');
    $em->connection('cap');

    $em->mapping('AcMarcheCap')
        ->isBundle(false)
        ->type('attribute')
        ->dir('%kernel.project_dir%/src/AcMarche/Cap/src/Entity')
        ->prefix('AcMarche\Cap')
        ->alias('AcMarcheCap');
};
```

**Comment by yceruto** [comment]
@jfsenechal can you open a new issue with details so I can take a look?
