### PR TITLE
[DomCrawler] Cache discovered namespaces

### LINKED ISSUE #39067: [DomCrawler] Terrible perfomance filterXpath - new Crawler
**Symfony version(s) affected**: 3.4 // 4.4

**Description**  
I have terrible performance issue when I follow documentation to parse quiet large XML (3Mo) with nested query.

**How to reproduce**  
```php
$crawler = new Crawler();
$crawler->addXmlContent(file_get_contents(__DIR__.'/rfc1767_33000.xml'));

foreach ($crawler->filterXPath('//transaction') as $nodeTransaction) {
    $crawlerTransaction = new Crawler($nodeTransaction);
    $actionCode = $crawlerTransaction->filterXPath('transaction/documentCommand/documentCommandHeader/@type')->text();
    $transactionId = $crawlerTransaction->filterXPath('transaction/transactionIdentification/entityIdentification')->text();

    foreach ($crawlerTransaction->filterXPath('//catalogue_item_notification:catalogueItemNotification') as $nodeItem) {
        $crawlerItem = new Crawler($nodeItem);
        $documentId = $crawlerItem->filterXPath('//catalogueItemNotificationIdentification/entityIdentification')->text();
        $recipientGln = $crawlerItem->filterXpath('//catalogue_item_notification:catalogueItemNotification/catalogueItem/dataRecipient')->text();
        $highestLevelGtin = $crawlerItem->filterXPath('//catalogue_item_notification:catalogueItemNotification/catalogueItem/tradeItem/gtin')->text();
        $targetMarket = $crawlerItem->filterXPath('//catalogue_item_notification:catalogueItemNotification/catalogueItem/tradeItem/targetMarket/targetMarketCountryCode')->text();
        $documentStatusCode = strtolower($crawlerItem->filterXPath('//catalogue_item_notification:catalogueItemNotification/documentStatusCode')->text());

        foreach ($crawlerItem->filterXPath('catalogue_item_notification:catalogueItemNotification//catalogueItem') as $nodeCatalogueItem) {
            $crawlerCatalogueItem = new Crawler($nodeCatalogueItem);
            $gtin = $crawlerCatalogueItem->filterXPath('//catalogueItem/tradeItem/gtin')->text();
            dump($gtin);
        }
    }
}
```
=> Memory used **1.2Go**  **30sec** for execution

Only With Php \Dom
```php
$dom = new \DOMDocument('1.0');
$dom->validateOnParse = true;
@$dom->loadXML(file_get_contents(__DIR__.'/rfc1767_33000.xml'), \LIBXML_NONET);
$xpath = new \DOMXpath($dom);

foreach ($xpath->query('transaction') as $nodeTransaction) {
    $actionCode = $xpath->query('documentCommand/documentCommandHeader/@type', $nodeTransaction)->item(0)->nodeValue;
    $transactionId = $xpath->query('transactionIdentification/entityIdentification', $nodeTransaction)->item(0)->nodeValue;

    /** @var \DOMNode $nodeItem */
    foreach ($xpath->query('.//catalogue_item_notification:catalogueItemNotification', $nodeTransaction) as $nodeItem) {
        $documentId = $xpath->query('//catalogueItemNotificationIdentification/entityIdentification', $nodeItem)->item(0)->nodeValue;
        $recipientGln = $xpath->query('//catalogue_item_notification:catalogueItemNotification/catalogueItem/dataRecipient', $nodeItem)->item(0)->nodeValue;
        $highestLevelGtin = $xpath->query('//catalogue_item_notification:catalogueItemNotification/catalogueItem/tradeItem/gtin', $nodeItem)->item(0)->nodeValue;
        $targetMarket = $xpath->query('//catalogue_item_notification:catalogueItemNotification/catalogueItem/tradeItem/targetMarket/targetMarketCountryCode', $nodeItem)->item(0)->nodeValue;
        $documentStatusCode = $xpath->query('//catalogue_item_notification:catalogueItemNotification/documentStatusCode', $nodeItem)->item(0)->nodeValue;

        /** @var \DOMNode $nodeCatalogueItem */
        foreach ($xpath->query('.//catalogueItem', $nodeItem) as $nodeCatalogueItem) {
            $gtin = $xpath->query('tradeItem/gtin', $nodeCatalogueItem)->item(0)->nodeValue;
            dump($gtin);
        }
    }
}
```
=> Memory used **20Mo**, **500ms** for execution

**Possible Solution**  
I don't know where is the memory leak. It seems to be Crawler initializations.

**Additional context**  
Did I miss something when using Crawler ?

Thanks in advance

### PR DESCRIPTION
**Pull request by simonberger**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Address #39067
| License       | MIT

Discovering namespaces is by far the most expensive task when filtering for nodes and the xpath contains prefixes.
When `Crawler::filterRelativeXPath` is called multiple times with (identical) prefixes the slowdown is huge.

This fix brings the runtime of the linked ticket down from 27 seconds to 9 seconds in my test. Compared to a pure PHP version which takes < 0.5 seconds the design of the crawler API is the limiting factor. There are still many repeated namespace queries caused by new Crawler instances. Ideas to solve this are discussed in the ticket.

### CODE REVIEW

File: src/Symfony/Component/DomCrawler/Crawler.php [hunk 1]
```diff
@@ -1325,4 +1336,9 @@ private function isValidHtml5Heading(string $heading): bool
     {
         return 1 === preg_match('/^\x{FEFF}?\s*(<!--[^>]*?-->\s*)*$/u', $heading);
     }
+
+    private function clearCachedNamespaces(): void
```
Comment (jderusse) [inline src/Symfony/Component/DomCrawler/Crawler.php]: this method is used once and contains a single line of code. It content could be moved to `clean` method

File: src/Symfony/Component/DomCrawler/Crawler.php [hunk 2]
```diff
@@ -968,6 +974,7 @@ public function setDefaultNamespacePrefix($prefix)
     public function registerNamespace($prefix, $namespace)
     {
         $this->namespaces[$prefix] = $namespace;
+        $this->cachedNamespaces[$prefix] = $namespace;
```
Comment (stof) [inline src/Symfony/Component/DomCrawler/Crawler.php]: maybe `cachedNamespaces` should contain only the ones loaded from the namespace discovery rather than also duplicating `$this->namespaces`

Comment (simonberger) [reply src/Symfony/Component/DomCrawler/Crawler.php]: I knew this'll come up. 😆 
Yeah I was not sure about it. I liked more to have all namespaces in one array, but sure a second check on the namespace array would be still cheap. 
It's just another (small) hurdle developers have to taken into account when the prefixes are used in another place. The namespace duplication is a one time adjustment.
The reason I did it like this at the end was that I don't think registering the namespaces manually is a much used feature. I might be wrong here though.

Separating the cache from the manually registered namespaces is also just necessary because the namespaces are not removed in the `clear` call. Otherwise we could build the cache just in the one object too.

File: src/Symfony/Component/DomCrawler/Crawler.php [hunk 3]
```diff
@@ -1235,6 +1244,7 @@ private function createDOMXPath(\DOMDocument $document, array $prefixes = []): \
             $namespace = $this->discoverNamespace($domxpath, $prefix);
             if (null !== $namespace) {
                 $domxpath->registerNamespace($prefix, $namespace);
+                $this->cachedNamespaces[$prefix] = $namespace;
```
Comment (stof) [inline src/Symfony/Component/DomCrawler/Crawler.php]: I would do this caching in `discoverNamespace` instead, so that the caching management is centralized in the place doing memoization (and it could cache `null` values too)

File: src/Symfony/Component/DomCrawler/Crawler.php (hunk 2 above)
Comment (stof) [reply src/Symfony/Component/DomCrawler/Crawler.php]: Well, explicitly registered namespaces are not removed on `clear` on purpose, because they don't depend on the nodes being in the crawler.

Keeping separate lists would only require checking both in `discoverNamespace` indeed, but that's a `O(1)` check as it checks by key, not by iteration. but it would simplify other places where we would not have to remember to avoid loosing entries from `$this->namespaces`

Comment (simonberger) [reply src/Symfony/Component/DomCrawler/Crawler.php]: Your argument is I should change it because otherwise we possibly need to remember the namespaces on more places (before that problem may appear we have to empty the cached namespaces on another place, which was one of the reasons I left the private function `clearCachedNamespace` in).

My argument to do it the current way was to not need to remember to do double checks for namespaces in all places that might be added in the future. I didn't even raise the performance card for the additional isset check. It's really really negligible.

For me it's hard to weight which implementation detail is more sensitive. It is also really a detail to me anyway and I'll just make the change if you still prefer it and there is no other opinion.

File: src/Symfony/Component/DomCrawler/Crawler.php (hunk 3 above)
Comment (simonberger) [reply src/Symfony/Component/DomCrawler/Crawler.php]: Good point. Moved caching in and also store null results.

File: src/Symfony/Component/DomCrawler/Crawler.php (hunk 2 above)
Comment (stof) [reply src/Symfony/Component/DomCrawler/Crawler.php]: but `cachedNamespaces` is about memoizing the work done by `discoverNamespace`. So there is no reason to access it in more places, as these places must use `discoverNamespace` (they cannot assume that the cache is already populated). There is a single place that reads that array (not counting copying it to sub-crawlers)

File: src/Symfony/Component/DomCrawler/Crawler.php [hunk 4]
```diff
@@ -1034,6 +1041,8 @@ private function filterRelativeXPath(string $xpath)
             $crawler->add($domxpath->query($xpath, $node));
         }
 
+        $crawler->cachedNamespaces = $this->cachedNamespaces;
```
Comment (stof) [inline src/Symfony/Component/DomCrawler/Crawler.php]: Rather than copying the cached namespaced a second time to account for changes done in `createDOMXPath`, I'd rather ensure that the changes are done before creating the subcrawler.
This can be done by creating a single `$domxpath` thanks to the invariant that `$node->ownerDocument === $this->document` in Symfony 4+ (that was not enforced in Symfony 3), which could allow us to create a single `$domxpath` before the `createSubCrawler` call and use it in the loop.

File: src/Symfony/Component/DomCrawler/Crawler.php (hunk 2 above)
Comment (simonberger) [reply src/Symfony/Component/DomCrawler/Crawler.php]: Ok valid point, there should be no reason to check for namespaces outside of the discoverNamespace function. I'll change it later.

File: src/Symfony/Component/DomCrawler/Crawler.php [hunk 5]
```diff
@@ -1250,10 +1258,17 @@ private function discoverNamespace(\DOMXPath $domxpath, string $prefix): ?string
             return $this->namespaces[$prefix];
         }
 
+        if (array_key_exists($prefix, $this->cachedNamespaces)) {
```
Comment (derrabus) [inline src/Symfony/Component/DomCrawler/Crawler.php]:
```suggestion
        if (\array_key_exists($prefix, $this->cachedNamespaces)) {
```

To make fabbot happy. 😃

Comment (simonberger) [reply src/Symfony/Component/DomCrawler/Crawler.php]: Just noticed, thanks.

File: src/Symfony/Component/DomCrawler/Crawler.php (hunk 4 above)
Comment (stof) [reply src/Symfony/Component/DomCrawler/Crawler.php]: @simonberger why is this marked as resolved ?

**Comment by simonberger** [comment]
Is the ticket (still) auto-closed by this PR? If so can I write it differently? Otherwise I just remove it.

**Comment by stof** [comment]
@simonberger don't put `fix` just before the issue number

**Comment by stof** [comment]
this PR looks good to me.

the last potential improvement is the one I suggested in https://github.com/symfony/symfony/issues/39067#issuecomment-730279448 to make *all* subcrawlers share their namespace cache with the main crawler (instead of copying the parent cache at instantiation time), which helps when the subcrawlers are the one making the discovery.

**Comment by simonberger** [comment]
Yeah I tested to use an ArrayIterator instead of an array which seems to solve that shared namespace issue.
I'll push a solution like this tomorrow.

File: src/Symfony/Component/DomCrawler/Crawler.php [hunk 6]
```diff
@@ -1025,12 +1031,10 @@ public static function xpathLiteral($s)
      */
     private function filterRelativeXPath(string $xpath)
     {
-        $prefixes = $this->findNamespacePrefixes($xpath);
-
+        $domxpath = $this->createDOMXPath($this->document, $this->findNamespacePrefixes($xpath));
```
Comment (jderusse) [inline src/Symfony/Component/DomCrawler/Crawler.php]: are we sure all nodes share the same document? 

note: Travis test is failing here

File: src/Symfony/Component/DomCrawler/Crawler.php [hunk 7]
```diff
@@ -1278,6 +1289,7 @@ private function createSubCrawler($nodes)
         $crawler->isHtml = $this->isHtml;
         $crawler->document = $this->document;
         $crawler->namespaces = $this->namespaces;
+        $crawler->cachedNamespaces = $this->cachedNamespaces;
```
Comment (jderusse) [inline src/Symfony/Component/DomCrawler/Crawler.php:1233]: give a try to `$crawler->cachedNamespaces = &$this->cachedNamespaces;` to share the same cache as suggested in https://github.com/symfony/symfony/pull/39097#issuecomment-730349079

File: src/Symfony/Component/DomCrawler/Crawler.php (hunk 6 above)
Comment (simonberger) [reply src/Symfony/Component/DomCrawler/Crawler.php]: There is not necessarily a document on that point. In the tests (mainly) because of an empty content. This isn't hard to handle. I'll check tests and all the possible paths tomorrow.

File: src/Symfony/Component/DomCrawler/Crawler.php (hunk 7 above)
Comment (simonberger) [reply src/Symfony/Component/DomCrawler/Crawler.php:1233]: Good idea too. It's just not very intransparent and tricky to allow for example a subcrawler to clear the cache and build a new one without affecting the parent crawlers. Works out of the box with an ArrayIterator.

File: src/Symfony/Component/DomCrawler/Crawler.php [hunk 8]
```diff
@@ -73,6 +73,7 @@ public function __construct($node = null, string $uri = null, string $baseHref =
         $this->uri = $uri;
         $this->baseHref = $baseHref ?: $uri;
         $this->html5Parser = class_exists(HTML5::class) ? new HTML5(['disable_html_ns' => true]) : null;
+        $this->cachedNamespaces = new \ArrayIterator();
```
Comment (stof) [inline src/Symfony/Component/DomCrawler/Crawler.php]: should be `ArrayObject` rather than `ArrayIterator` IMO

File: src/Symfony/Component/DomCrawler/Crawler.php [hunk 9]
```diff
@@ -1254,15 +1259,15 @@ private function discoverNamespace(\DOMXPath $domxpath, string $prefix): ?string
...
+        if ($this->cachedNamespaces->offsetExists($prefix)) {
+            return $this->cachedNamespaces->offsetGet($prefix);
         }
 
         // ask for one namespace, otherwise we'd get a collection with an item for each node
         $namespaces = $domxpath->query(sprintf('(//namespace::*[name()="%s"])[last()]', $this->defaultNamespacePrefix === $prefix ? '' : $prefix));
 
         $namespace = ($node = $namespaces->item(0)) ? $node->nodeValue : null;
-        $this->cachedNamespaces[$prefix] = $namespace;
+        $this->cachedNamespaces->offsetSet($prefix, $namespace);
```
Comment (stof) [inline src/Symfony/Component/DomCrawler/Crawler.php]: using `this->cachedNamespaces[$prefix] = $namespace;` is fine. that's what `ArrayAccess` is for.

Comment (simonberger) [reply src/Symfony/Component/DomCrawler/Crawler.php]: I am thankful for your valuable improvement ideas but please let us not discuss every unimportant detail of my implementation. I know I have an ArrayIterator here in opposite to most public ArrayIterator|array|... usages so I decided to directly take its functions.

**Comment by fabpot** [comment]
Rebase on 5.x (we don't introduce new features in 4.4, and caching is a new feature). I've also made some cosmetic changes.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @simonberger.

**Comment by simonberger** [comment]
@fabpot Not a really big thing but this change https://github.com/symfony/symfony/pull/39097/commits/a8e85ecbbd52bc2aaa50d58daf02afb8b4764e9d#diff-940b51ffa31dedac17aa49cd8e04e44aa8b3747782c7f9f27457b0510587c05dR1201 does not find the also cached null results of prefixes. One of the reasons I preferred to stick to the method usage everywhere.
