### PR TITLE
Tweak error/exception handler registration

### LINKED ISSUE #46692: PHP deprecations output to the response on 1st non-debug mode call
### Symfony version(s) affected

5.4

### Description

I recently stumbled upon an issue on the CI of one of our projects relying on a Symfony CLI server running in test env **without debug mode** enabled: 

one of the third party libraries triggers some PHP 8 deprecations, 
**which are output to the response of the 1st call** made to the running application and making the test fail.

### How to reproduce

A simple reproducer is available here: https://github.com/ogizanagi/sf-deprec-issue-reproducer

Use:

```shell
rm -rf var/cache
APP_DEBUG=0 symfony serve
```

and go to [localhost:8000](http://localhost:8000) to observe the deprecation output to the response:

Capture d’écran 2022-06-16 à 10 19 14

### Possible Solution

The following patch to the `GenericRuntime`:

```diff
diff --git a/src/Symfony/Component/Runtime/GenericRuntime.php b/src/Symfony/Component/Runtime/GenericRuntime.php
index 1d77529dfa..bb7455641d 100644
--- a/src/Symfony/Component/Runtime/GenericRuntime.php
+++ b/src/Symfony/Component/Runtime/GenericRuntime.php
@@ -71,15 +71,15 @@ class GenericRuntime implements RuntimeInterface
         if ($debug) {
             umask(0000);
             $_SERVER[$debugKey] = $_ENV[$debugKey] = '1';
-
-            if (false !== $errorHandler = ($options['error_handler'] ?? BasicErrorHandler::class)) {
-                $errorHandler::register($debug);
-                $options['error_handler'] = false;
-            }
         } else {
             $_SERVER[$debugKey] = $_ENV[$debugKey] = '0';
         }
 
+        if (false !== $errorHandler = ($options['error_handler'] ?? BasicErrorHandler::class)) {
+            $errorHandler::register(false);
+            $options['error_handler'] = false;
+        }
+
         $this->options = $options;
     }
```

aims to register the error handler, regardless of the `$debug` flag (but still passing it to the error handler which will account for it)

which solves the issues and the deprecation is properly absent from the response & logged:

```shell
[Application] Jun 16 08:23:06 |INFO   | DEPREC Deprecated: Return type of App\Foo::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

But I'm unaware if this solution could be wrong or not, since not registering at all an error handler in non-debug mode was clearly intended from the code.

The issue is mitigated as well on production servers for which `display_errors` should be disabled.

### Additional Context

_No response_

### LINKED ISSUE #53812: [Framework bundle] Cleanup error and exception handlers on Kernel shutdown
### Symfony version(s) affected

7.0.0

### Description

PHPUnit 11 checks for any leftovers in error handlers https://github.com/sebastianbergmann/phpunit/pull/5619

### How to reproduce

Run `FrameworkBundle->boot()` in phpunit test.

https://github.com/symfony/symfony/blob/815df931dca4663a6375e205b0fdf6e546ebfa75/src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php#L98

It results in `Test code or tested code did not remove its own exception handlers` thrown by phpunit.

### Possible Solution

Introduce `FrameworkBundle::shutdown()` that would cleanup error handler set in `boot()`. IMO it's reasonable to have some cleanup in shutdown() of things initiated in boot().

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #53812, Fix #46692
| License       | MIT

This should allow removing the custom bootstrap file from #58370 /cc @xabbuh 

The change on FrameworkBundle leads to a tweaked behavior: we don't override the previous error handler in case it's not the Symfony one. This shouldn't change anything in practice since the error handler is already registered by the runtime component.

The rest is closer to bug fixes.

### CODE REVIEW

**Comment by xabbuh** [comment]
@derrabus FYI as you used the same workaround for Twig

**Comment by nicolas-grekas** [comment]
I'm wondering about merging this in 6.4 :thinking:

**Comment by nicolas-grekas** [comment]
Rebased on 6.4

File: src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php [hunk 1]
```diff
@@ -104,11 +104,11 @@ public function onKernelException(ExceptionEvent $event)
 
         $throwable = $event->getThrowable();
 
-        if ($exceptionHandler = set_exception_handler(var_dump(...))) {
-            restore_exception_handler();
-            if (\is_array($exceptionHandler) && $exceptionHandler[0] instanceof ErrorHandler) {
-                $throwable = $exceptionHandler[0]->enhanceError($event->getThrowable());
-            }
+        $exceptionHandler = set_exception_handler('var_dump');
+        restore_exception_handler();
```
Comment (lyrixx) [inline src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php]: We need a PHP RFC to get `get_exception_handler()` 👀

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you. I'm a bit reluctant to merge this as a bugfix because of the change in behavior though.

**Comment by derrabus** [comment]
Then again, not having this change on 6.4 means we need to keep those bootstrap files for low-deps testing. Difficult decision. 🙈

File: src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php [hunk 2]
```diff
@@ -91,7 +91,16 @@ class FrameworkBundle extends Bundle
...
-        ErrorHandler::register(null, false)->throwAt($this->container->getParameter('debug.error_handler.throw_at'), true);
+        if (class_exists(ErrorHandler::class, false)) {
+            $handler = set_error_handler('var_dump');
+            restore_error_handler();
+        } else {
+            $handler = ErrorHandler::register(null, false);
+        }
+
+        if (\is_array($handler) && $handler[0] instanceof ErrorHandler) {
+            $handler->throwAt($this->container->getParameter('debug.error_handler.throw_at'), true);
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php]:
```suggestion
            $handler[0]->throwAt($this->container->getParameter('debug.error_handler.throw_at'), true);
```

File: src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php [hunk 3]
```diff
@@ -91,7 +92,16 @@ class FrameworkBundle extends Bundle
 {
     public function boot()
     {
-        ErrorHandler::register(null, false)->throwAt($this->container->getParameter('debug.error_handler.throw_at'), true);
+        if (class_exists(SymfonyRuntime::class)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php:95]: When symfony/runtime is installed, we assume it will register the ErrorHandler when appropriate.
That's not the case right now, but this PR fixes it.

File: src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php [hunk 4]
```diff
@@ -91,7 +92,16 @@ class FrameworkBundle extends Bundle
...
+            $handler = set_error_handler('var_dump');
+            restore_error_handler();
+        } else {
+            $handler = [ErrorHandler::register(null, false)];
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php:99]: When symfony/runtime is not found, the index.php file registers ErrorHandler only in debug mode, so we need to register it to not break prod mode.

File: src/Symfony/Bundle/FrameworkBundle/composer.json [hunk 5]
```diff
@@ -86,6 +86,7 @@
         "symfony/mime": "<4.4",
         "symfony/property-info": "<4.4",
         "symfony/property-access": "<5.3",
+        "symfony/runtime": "<5.4.45|>=6.0,<6.4.13|>=7.0,7.1.6",
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/composer.json]: ensures that we symfony/runtime is installed, it's a version that always registers ErrorHandler

Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/composer.json]:
```suggestion
        "symfony/runtime": "<5.4.45|>=6.0,<6.4.13|>=7.0,<7.1.6",
```

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Runtime/GenericRuntime.php [hunk 6]
```diff
@@ -71,15 +71,15 @@ public function __construct(array $options = [])
...
-
-            if (false !== $errorHandler = ($options['error_handler'] ?? BasicErrorHandler::class)) {
-                $errorHandler::register($debug);
-                $options['error_handler'] = false;
-            }
         } else {
             $_SERVER[$debugKey] = $_ENV[$debugKey] = '0';
         }
 
+        if (false !== $errorHandler = ($options['error_handler'] ?? BasicErrorHandler::class)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Runtime/GenericRuntime.php:78]: untightening the error_handler option from the debug one

File: src/Symfony/Component/Runtime/Internal/SymfonyErrorHandler.php [hunk 7]
```diff
@@ -24,12 +24,31 @@ class SymfonyErrorHandler
...
+        } elseif (!filter_var(\ini_get('log_errors'), \FILTER_VALIDATE_BOOL) || \ini_get('error_log')) {
+            // CLI - display errors only if they're not already logged to STDERR
+            ini_set('display_errors', 1);
+        }
+
+        if (0 <= \ini_get('zend.assertions')) {
+            ini_set('zend.assertions', 1);
+            ini_set('assert.active', $debug);
+            ini_set('assert.exception', 1);
+        }
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Runtime/Internal/SymfonyErrorHandler.php]: inlining what `BasicErrorHandler::register()` does currently (prevents the call to `restore_error_handler();`, removed below)

**Review by nicolas-grekas — COMMENTED** [review]
I rebased this on 5.4 and did a fix on symfony/runtime so that we have simpler setup of the error-handler register.
This should unlock moving to phpunit11 (deps=low included)

File: src/Symfony/Bundle/FrameworkBundle/composer.json (hunk 5 above)
Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/composer.json]: all fixed thanks

File: src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php (hunk 4 above)
Comment (stof) [reply src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php:99]: shouldn't we check whether it is already registered ? Maybe some devs have changed the index.php file.

And wouldn't this still cause issues with PHPUnit 11 then when booting a kernel during tests ?

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php:99]: The `false` argument is here to skip registering if `ErrorHandler` is already registered.
This line preserves the current behavior when symfoy/runtime isn't installed so I wouldn't add more logic here.

File: src/Symfony/Component/Runtime/Internal/SymfonyErrorHandler.php (hunk 7 above)
Comment (stof) [reply src/Symfony/Component/Runtime/Internal/SymfonyErrorHandler.php]: should we create an internal public method in the BasicErrorHandler that we could reuse instead of duplicating the logic ?

Comment (nicolas-grekas) [reply src/Symfony/Component/Runtime/Internal/SymfonyErrorHandler.php]: I wondered about this and thought this wasn't necessary: maintaining these duplicated lines shouldn't be a problem. Inlining prevents loading one more class on the hotpath.

**Review by stof — APPROVED** [review]

**Comment by xabbuh** [comment]
The test failures are related, aren't they?

**Comment by nicolas-grekas** [comment]
> The test failures are related, aren't they?

yes they are, this line is deprecated indeed when $debug = false: `ini_set('assert.active', $debug);`

PR updated

File: src/Symfony/Component/Runtime/Internal/SymfonyErrorHandler.php [hunk 8]
```diff
@@ -24,12 +24,31 @@ class SymfonyErrorHandler
...
+
+        if (!\in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
+            ini_set('display_errors', $debug);
+        } elseif (!filter_var(\ini_get('log_errors'), \FILTER_VALIDATE_BOOL) || \ini_get('error_log')) {
+            // CLI - display errors only if they're not already logged to STDERR
+            ini_set('display_errors', 1);
+        }
+
+        if (0 <= \ini_get('zend.assertions')) {
+            ini_set('zend.assertions', (int) $debug);
```
Comment (NoiseByNorthwest) [inline src/Symfony/Component/Runtime/Internal/SymfonyErrorHandler.php:43]: @nicolas-grekas why are you disabling assertions in non-debug mode ? We are relying on assertions in production  mode and this change breaks our application.

File: src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php (hunk 3 above)
Comment (lyrixx) [reply src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php:95]: Hello, On the app I'm working on :

* Symfony 6.4
* Flex ^2.6
* *no* symfony/runtime
* phpunit ^12
* `tests` recipes is up to date.
* in test, the current error handler before theses lines is `PHPUnit\Runner\ErrorHandler`

I get the reported error. If comment the condition on runtime, the error disappear. 

So, I'm not sure the condition is correct.

Comment (derrabus) [reply src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php:95]: I can confirm. On a project that does not use the Runtime component, the problem is stell present.

File: src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php (hunk 4 above)
Comment (homersimpsons) [reply src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php:99]: I also have this issue. But digging into this I'm not entirely sure about what is happening.
> Test code or tested code did not remove its own exception handlers

### Commenting out this call

1. This registering is the first call to `\Symfony\Component\ErrorHandler\ErrorHandler::register`
2. Commenting out this call makes phpunit not raise this warning anymore
3. Using Xdebug, I can confim that after the first call we still have the `\PHPUnit\Runner\ErrorHandler` as it is restored after:
https://github.com/symfony/symfony/blob/a1f8660822d2c7476b130d343ca2918c1df55b33/src/Symfony/Component/ErrorHandler/ErrorHandler.php#L132-L135

### Why is the warning message triggered?

That said, without commenting the warning message still is triggered from:
https://github.com/sebastianbergmann/phpunit/blob/a7f77612de78009288b1b86b4265433456e4d7bb/src/Framework/TestCase.php#L1957-L1961

In particular I observe those values:
```php
$activeExceptionHandlers = [[\Symfony\Component\ErrorHandler\ErrorHandler, "handleException"]];
$this->backupGlobalExceptionHandlers = [];
```

But, interestingly, at the last line of my tests there still is only the `\PHPUnit\Runner\ErrorHandler` registered, same at the last line of my `tearDown`, and similarly when I navigate into PHPUnit's internals.

### Lead on `reRegister`?

`\Symfony\Component\ErrorHandler\ErrorHandler::reRegister` is called also, but at no point it goes into `set_error_handler` in my observations.

Comment (lyrixx) [reply src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php:99]: Please, open a new issue. We do not track closed PR/issue.
Thanks
