### PR TITLE
[Messenger] Fix transporting non-UTF8 payloads by encoding them using base 64

### LINKED ISSUE #33913: [Messenger / Mailer] Sending an email with binary attachment async fails
**Symfony version(s) affected**: 4.3.5

**Description**
When trying to send an email with a binary attachment asynchronously, Symfony encounters an exception and fails.

**How to reproduce**  
- set up async sending using the Messenger component
- attach a PDF to the email being formed. Mine is templated, and I'm attachin the PDF as a string, but I doubt it matters.

**Possible Solution**  

**Additional context**  
I tried attaching the first 20 bytes of the PDF, here's the code extract just in case:
```php
$email = new TemplatedEmail();
$fileName = sprintf('%s.pdf', $object->getName());
$email
  ->to($recipient)
  ->subject('Subject')
  ->htmlTemplate('email/template.html.twig')
  ->context([
    'some_var' => $someVar,
    'other_var' => $otherVar,
  ])
  // $pdf is a TCPDF object
  ->attach(substr($pdf->output($fileName, 'S'), 0, 20), $fileName, 'application/pdf');

$this->mailer->send($email);
```
and here's the resulting crash log from docker output:
```
php_1    | 2019-10-08T14:59:19+00:00 [debug] INSERT INTO messenger_messages (body, headers, queue_name, created_at, available_at) VALUES(?, ?, ?, ?, ?)
php_1    | 2019-10-08T14:59:19+00:00 [critical] Uncaught PHP Exception Symfony\Component\Messenger\Exception\HandlerFailedException: "An exception occurred while executing 'INSERT INTO messenger_messages (body, headers, queue_name, created_at, available_at) VALUES(?, ?, ?, ?, ?)' with params ["\x4f\x3a\x33\x36\x3a\x5c\x22\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x65\x73\x73\x65\x6e\x67\x65\x72\x5c\x5c\x45\x6e\x76\x65\x6c\x6f\x70\x65\x5c\x22\x3a\x32\x3a\x7b\x73\x3a\x34\x34\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x65\x73\x73\x65\x6e\x67\x65\x72\x5c\x5c\x45\x6e\x76\x65\x6c\x6f\x70\x65\x5c\x30\x73\x74\x61\x6d\x70\x73\x5c\x22\x3b\x61\x3a\x32\x3a\x7b\x73\x3a\x34\x36\x3a\x5c\x22\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x65\x73\x73\x65\x6e\x67\x65\x72\x5c\x5c\x53\x74\x61\x6d\x70\x5c\x5c\x42\x75\x73\x4e\x61\x6d\x65\x53\x74\x61\x6d\x70\x5c\x22\x3b\x61\x3a\x31\x3a\x7b\x69\x3a\x30\x3b\x4f\x3a\x34\x36\x3a\x5c\x22\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x65\x73\x73\x65\x6e\x67\x65\x72\x5c\x5c\x53\x74\x61\x6d\x70\x5c\x5c\x42\x75\x73\x4e\x61\x6d\x65\x53\x74\x61\x6d\x70\x5c\x22\x3a\x31\x3a\x7b\x73\x3a\x35\x35\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x65\x73\x73\x65\x6e\x67\x65\x72\x5c\x5c\x53\x74\x61\x6d\x70\x5c\x5c\x42\x75\x73\x4e\x61\x6d\x65\x53\x74\x61\x6d\x70\x5c\x30\x62\x75\x73\x4e\x61\x6d\x65\x5c\x22\x3b\x73\x3a\x32\x31\x3a\x5c\x22\x6d\x65\x73\x73\x65\x6e\x67\x65\x72\x2e\x62\x75\x73\x2e\x64\x65\x66\x61\x75\x6c\x74\x5c\x22\x3b\x7d\x7d\x73\x3a\x34\x33\x3a\x5c\x22\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x65\x73\x73\x65\x6e\x67\x65\x72\x5c\x5c\x53\x74\x61\x6d\x70\x5c\x5c\x53\x65\x6e\x74\x53\x74\x61\x6d\x70\x5c\x22\x3b\x61\x3a\x31\x3a\x7b\x69\x3a\x30\x3b\x4f\x3a\x34\x33\x3a\x5c\x22\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x65\x73\x73\x65\x6e\x67\x65\x72\x5c\x5c\x53\x74\x61\x6d\x70\x5c\x5c\x53\x65\x6e\x74\x53\x74\x61\x6d\x70\x5c\x22\x3a\x32\x3a\x7b\x73\x3a\x35\x36\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x65\x73\x73\x65\x6e\x67\x65\x72\x5c\x5c\x53\x74\x61\x6d\x70\x5c\x5c\x53\x65\x6e\x74\x53\x74\x61\x6d\x70\x5c\x30\x73\x65\x6e\x64\x65\x72\x43\x6c\x61\x73\x73\x5c\x22\x3b\x73\x3a\x36\x34\x3a\x5c\x22\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x65\x73\x73\x65\x6e\x67\x65\x72\x5c\x5c\x54\x72\x61\x6e\x73\x70\x6f\x72\x74\x5c\x5c\x44\x6f\x63\x74\x72\x69\x6e\x65\x5c\x5c\x44\x6f\x63\x74\x72\x69\x6e\x65\x54\x72\x61\x6e\x73\x70\x6f\x72\x74\x5c\x22\x3b\x73\x3a\x35\x36\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x65\x73\x73\x65\x6e\x67\x65\x72\x5c\x5c\x53\x74\x61\x6d\x70\x5c\x5c\x53\x65\x6e\x74\x53\x74\x61\x6d\x70\x5c\x30\x73\x65\x6e\x64\x65\x72\x41\x6c\x69\x61\x73\x5c\x22\x3b\x73\x3a\x35\x3a\x5c\x22\x61\x73\x79\x6e\x63\x5c\x22\x3b\x7d\x7d\x7d\x73\x3a\x34\x35\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x65\x73\x73\x65\x6e\x67\x65\x72\x5c\x5c\x45\x6e\x76\x65\x6c\x6f\x70\x65\x5c\x30\x6d\x65\x73\x73\x61\x67\x65\x5c\x22\x3b\x4f\x3a\x35\x31\x3a\x5c\x22\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x61\x69\x6c\x65\x72\x5c\x5c\x4d\x65\x73\x73\x65\x6e\x67\x65\x72\x5c\x5c\x53\x65\x6e\x64\x45\x6d\x61\x69\x6c\x4d\x65\x73\x73\x61\x67\x65\x5c\x22\x3a\x32\x3a\x7b\x73\x3a\x36\x30\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x61\x69\x6c\x65\x72\x5c\x5c\x4d\x65\x73\x73\x65\x6e\x67\x65\x72\x5c\x5c\x53\x65\x6e\x64\x45\x6d\x61\x69\x6c\x4d\x65\x73\x73\x61\x67\x65\x5c\x30\x6d\x65\x73\x73\x61\x67\x65\x5c\x22\x3b\x43\x3a\x33\x39\x3a\x5c\x22\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x42\x72\x69\x64\x67\x65\x5c\x5c\x54\x77\x69\x67\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x54\x65\x6d\x70\x6c\x61\x74\x65\x64\x45\x6d\x61\x69\x6c\x5c\x22\x3a\x31\x35\x34\x39\x3a\x7b\x61\x3a\x34\x3a\x7b\x69\x3a\x30\x3b\x73\x3a\x33\x38\x3a\x5c\x22\x65\x6d\x61\x69\x6c\x2f\x73\x68\x61\x72\x65\x5f\x73\x65\x73\x73\x69\x6f\x6e\x5f\x70\x6c\x61\x6e\x5f\x70\x64\x66\x2e\x68\x74\x6d\x6c\x2e\x74\x77\x69\x67\x5c\x22\x3b\x69\x3a\x31\x3b\x4e\x3b\x69\x3a\x32\x3b\x61\x3a\x32\x3a\x7b\x73\x3a\x31\x31\x3a\x5c\x22\x73\x68\x61\x72\x65\x72\x5f\x6e\x61\x6d\x65\x5c\x22\x3b\x73\x3a\x31\x37\x3a\x5c\x22\x49\x4c\x47\x20\x41\x64\x6d\x69\x6e\x69\x73\x74\x72\x61\x74\x6f\x72\x5c\x22\x3b\x73\x3a\x39\x3a\x5c\x22\x70\x6c\x61\x6e\x5f\x6e\x61\x6d\x65\x5c\x22\x3b\x73\x3a\x31\x35\x3a\x5c\x22\x50\x69\x72\x6d\x61\x73\x69\x73\x20\x70\x6c\x61\x6e\x61\x73\x5c\x22\x3b\x7d\x69\x3a\x33\x3b\x61\x3a\x36\x3a\x7b\x69\x3a\x30\x3b\x4e\x3b\x69\x3a\x31\x3b\x4e\x3b\x69\x3a\x32\x3b\x4e\x3b\x69\x3a\x33\x3b\x4e\x3b\x69\x3a\x34\x3b\x61\x3a\x31\x3a\x7b\x69\x3a\x30\x3b\x61\x3a\x34\x3a\x7b\x73\x3a\x34\x3a\x5c\x22\x62\x6f\x64\x79\x5c\x22\x3b\x73\x3a\x32\x30\x3a\x5c\x22\x25\x50\x44\x46\x2d\x31\x2e\x37\x0a\x25\xe2\xe3\xcf\xd3\x0a\x37\x20\x30\x20\x6f\x5c\x22\x3b\x73\x3a\x34\x3a\x5c\x22\x6e\x61\x6d\x65\x5c\x22\x3b\x73\x3a\x31\x39\x3a\x5c\x22\x50\x69\x72\x6d\x61\x73\x69\x73\x20\x70\x6c\x61\x6e\x61\x73\x2e\x70\x64\x66\x5c\x22\x3b\x73\x3a\x31\x32\x3a\x5c\x22\x63\x6f\x6e\x74\x65\x6e\x74\x2d\x74\x79\x70\x65\x5c\x22\x3b\x73\x3a\x31\x35\x3a\x5c\x22\x61\x70\x70\x6c\x69\x63\x61\x74\x69\x6f\x6e\x2f\x70\x64\x66\x5c\x22\x3b\x73\x3a\x36\x3a\x5c\x22\x69\x6e\x6c\x69\x6e\x65\x5c\x22\x3b\x62\x3a\x30\x3b\x7d\x7d\x69\x3a\x35\x3b\x61\x3a\x32\x3a\x7b\x69\x3a\x30\x3b\x4f\x3a\x33\x37\x3a\x5c\x22\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x48\x65\x61\x64\x65\x72\x5c\x5c\x48\x65\x61\x64\x65\x72\x73\x5c\x22\x3a\x32\x3a\x7b\x73\x3a\x34\x36\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x48\x65\x61\x64\x65\x72\x5c\x5c\x48\x65\x61\x64\x65\x72\x73\x5c\x30\x68\x65\x61\x64\x65\x72\x73\x5c\x22\x3b\x61\x3a\x32\x3a\x7b\x73\x3a\x32\x3a\x5c\x22\x74\x6f\x5c\x22\x3b\x61\x3a\x31\x3a\x7b\x69\x3a\x30\x3b\x4f\x3a\x34\x37\x3a\x5c\x22\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x48\x65\x61\x64\x65\x72\x5c\x5c\x4d\x61\x69\x6c\x62\x6f\x78\x4c\x69\x73\x74\x48\x65\x61\x64\x65\x72\x5c\x22\x3a\x35\x3a\x7b\x73\x3a\x35\x38\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x48\x65\x61\x64\x65\x72\x5c\x5c\x4d\x61\x69\x6c\x62\x6f\x78\x4c\x69\x73\x74\x48\x65\x61\x64\x65\x72\x5c\x30\x61\x64\x64\x72\x65\x73\x73\x65\x73\x5c\x22\x3b\x61\x3a\x31\x3a\x7b\x69\x3a\x30\x3b\x4f\x3a\x33\x30\x3a\x5c\x22\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x41\x64\x64\x72\x65\x73\x73\x5c\x22\x3a\x31\x3a\x7b\x73\x3a\x33\x39\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x41\x64\x64\x72\x65\x73\x73\x5c\x30\x61\x64\x64\x72\x65\x73\x73\x5c\x22\x3b\x73\x3a\x31\x37\x3a\x5c\x22\x72\x69\x6d\x61\x73\x40\x6e\x6f\x72\x64\x63\x6f\x64\x65\x2e\x69\x6f\x5c\x22\x3b\x7d\x7d\x73\x3a\x35\x30\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x48\x65\x61\x64\x65\x72\x5c\x5c\x41\x62\x73\x74\x72\x61\x63\x74\x48\x65\x61\x64\x65\x72\x5c\x30\x6e\x61\x6d\x65\x5c\x22\x3b\x73\x3a\x32\x3a\x5c\x22\x54\x6f\x5c\x22\x3b\x73\x3a\x35\x36\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x48\x65\x61\x64\x65\x72\x5c\x5c\x41\x62\x73\x74\x72\x61\x63\x74\x48\x65\x61\x64\x65\x72\x5c\x30\x6c\x69\x6e\x65\x4c\x65\x6e\x67\x74\x68\x5c\x22\x3b\x69\x3a\x37\x36\x3b\x73\x3a\x35\x30\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x48\x65\x61\x64\x65\x72\x5c\x5c\x4
php_1    | 1\x62\x73\x74\x72\x61\x63\x74\x48\x65\x61\x64\x65\x72\x5c\x30\x6c\x61\x6e\x67\x5c\x22\x3b\x4e\x3b\x73\x3a\x35\x33\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x48\x65\x61\x64\x65\x72\x5c\x5c\x41\x62\x73\x74\x72\x61\x63\x74\x48\x65\x61\x64\x65\x72\x5c\x30\x63\x68\x61\x72\x73\x65\x74\x5c\x22\x3b\x73\x3a\x35\x3a\x5c\x22\x75\x74\x66\x2d\x38\x5c\x22\x3b\x7d\x7d\x73\x3a\x37\x3a\x5c\x22\x73\x75\x62\x6a\x65\x63\x74\x5c\x22\x3b\x61\x3a\x31\x3a\x7b\x69\x3a\x30\x3b\x4f\x3a\x34\x38\x3a\x5c\x22\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x48\x65\x61\x64\x65\x72\x5c\x5c\x55\x6e\x73\x74\x72\x75\x63\x74\x75\x72\x65\x64\x48\x65\x61\x64\x65\x72\x5c\x22\x3a\x35\x3a\x7b\x73\x3a\x35\x35\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x48\x65\x61\x64\x65\x72\x5c\x5c\x55\x6e\x73\x74\x72\x75\x63\x74\x75\x72\x65\x64\x48\x65\x61\x64\x65\x72\x5c\x30\x76\x61\x6c\x75\x65\x5c\x22\x3b\x73\x3a\x34\x36\x3a\x5c\x22\x43\x72\x69\x63\x6b\x65\x74\x20\x70\x72\x61\x63\x74\x69\x63\x65\x20\x70\x6c\x61\x6e\x20\x68\x61\x73\x20\x62\x65\x65\x6e\x20\x73\x68\x61\x72\x65\x64\x20\x77\x69\x74\x68\x20\x79\x6f\x75\x5c\x22\x3b\x73\x3a\x35\x30\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x48\x65\x61\x64\x65\x72\x5c\x5c\x41\x62\x73\x74\x72\x61\x63\x74\x48\x65\x61\x64\x65\x72\x5c\x30\x6e\x61\x6d\x65\x5c\x22\x3b\x73\x3a\x37\x3a\x5c\x22\x53\x75\x62\x6a\x65\x63\x74\x5c\x22\x3b\x73\x3a\x35\x36\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x48\x65\x61\x64\x65\x72\x5c\x5c\x41\x62\x73\x74\x72\x61\x63\x74\x48\x65\x61\x64\x65\x72\x5c\x30\x6c\x69\x6e\x65\x4c\x65\x6e\x67\x74\x68\x5c\x22\x3b\x69\x3a\x37\x36\x3b\x73\x3a\x35\x30\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x48\x65\x61\x64\x65\x72\x5c\x5c\x41\x62\x73\x74\x72\x61\x63\x74\x48\x65\x61\x64\x65\x72\x5c\x30\x6c\x61\x6e\x67\x5c\x22\x3b\x4e\x3b\x73\x3a\x35\x33\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x48\x65\x61\x64\x65\x72\x5c\x5c\x41\x62\x73\x74\x72\x61\x63\x74\x48\x65\x61\x64\x65\x72\x5c\x30\x63\x68\x61\x72\x73\x65\x74\x5c\x22\x3b\x73\x3a\x35\x3a\x5c\x22\x75\x74\x66\x2d\x38\x5c\x22\x3b\x7d\x7d\x7d\x73\x3a\x34\x39\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x69\x6d\x65\x5c\x5c\x48\x65\x61\x64\x65\x72\x5c\x5c\x48\x65\x61\x64\x65\x72\x73\x5c\x30\x6c\x69\x6e\x65\x4c\x65\x6e\x67\x74\x68\x5c\x22\x3b\x69\x3a\x37\x36\x3b\x7d\x69\x3a\x31\x3b\x4e\x3b\x7d\x7d\x7d\x7d\x73\x3a\x36\x31\x3a\x5c\x22\x5c\x30\x53\x79\x6d\x66\x6f\x6e\x79\x5c\x5c\x43\x6f\x6d\x70\x6f\x6e\x65\x6e\x74\x5c\x5c\x4d\x61\x69\x6c\x65\x72\x5c\x5c\x4d\x65\x73\x73\x65\x6e\x67\x65\x72\x5c\x5c\x53\x65\x6e\x64\x45\x6d\x61\x69\x6c\x4d\x65\x73\x73\x61\x67\x65\x5c\x30\x65\x6e\x76\x65\x6c\x6f\x70\x65\x5c\x22\x3b\x4e\x3b\x7d\x7d", "[]", "default", "2019-10-08T14:59:19", "2019-10-08T14:59:19"]:
php_1    | SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xE2\xE3\xCF\xD3\x0A7...' for column `icc`.`messenger_messages`.`body` at row 1" at /srv/app/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php line 82
```
I tried changing the `body` and `headers` fields of the `messenger_messages` DB table to `longblob`, but it didn't fix the issue. I suppose encoding the body in b64 or qp before attempting to store it could help.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #33913
| License       | MIT
| Doc PR        | -

Replaces #33920

When using the Doctrine transport, sending emails with binary attachments currently requires a custom Messenger serializer because the "body" column is created for UTF-8 only.

In #33920, it is proposed to change the TEXT type to a BLOB. It leaves at least one problem unhandled: the conversion of existing messenger tables.

This PR takes a more conservative approach, by encoding messages to base 64, only if they are non-UTF8.

Compatibility with the existing format is preserved.

The drawback of this approach is that the size of eg email attachments is going to increase by 33% because of the extra encoding. I think this drawback is acceptable for 4.4, and that this PR is the most pragmatic way to make attachments just work.

### CODE REVIEW

**Review by fabpot — APPROVED** [review]

**Review by jderusse — APPROVED** [review]

**Comment by rimas-kudelis** [comment]
> The drawback of this approach is that the size of eg email attachments is going to increase by 33% because of the extra encoding. I think this drawback is acceptable for 4.4, and that this PR is the most pragmatic way to make attachments just work.

When you wrote this, did you mean it will increase the size of our messages in the storage, or did you refer to emails that are later sent out? From the code it looks like the former, but your comment almost implies the latter.

File: src/Symfony/Component/Messenger/Transport/Serialization/PhpSerializer.php [hunk 1]
```diff
@@ -29,6 +29,10 @@ public function decode(array $encodedEnvelope): Envelope
             throw new MessageDecodingFailedException('Encoded envelope should have at least a "body".');
         }
 
+        if (false === strpos($encodedEnvelope['body'], '}', -1)) {
```
Comment (OskarStark) [inline src/Symfony/Component/Messenger/Transport/Serialization/PhpSerializer.php:32]: Isn't this check a bit errorprone, what about wrapping the base64 encoded content or prefix it with a special key which we can check against later when retrieving the message?

**Comment by nicolas-grekas** [comment]
> it will increase the size of our messages in the storage

yes, that's what I meant.

File: src/Symfony/Component/Messenger/Transport/Serialization/PhpSerializer.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Transport/Serialization/PhpSerializer.php:32]: I don't think it's error-prone: the php serialization format is likely more stable than this very class.

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by sroze** [comment]
Nice change @nicolas-grekas !
