### PR TITLE
[DomCrawler] Fix converting HTML5 trees to DOM nodes

### LINKED ISSUE #62176: [DomCrawler] Native HTML5 parser on PHP 8.4 b/c change with alpinejs
Just a note/heads up for others that find themselves here... 

I upgraded to v7.4.0-BETA1 - ran my unit tests, which worked in 7.3.x - and now they fail :) 

Messages like: 

```
Warning: DOMDocument::loadXML(): Failed to parse QName ':class' in Entity, line: 17 in /Users/phil/Sites/symfony-7.4-alpine-reproducer/vendor/symfony/dom-crawler/Crawler.php on line 1116

Warning: DOMDocument::loadXML(): error parsing attribute name in Entity, line: 21 in /Users/phil/Sites/symfony-7.4-alpine-reproducer/vendor/symfony/dom-crawler/Crawler.php on line 1116
```

A reproducer is here https://github.com/PhilETaylor/symfony-7.4-alpine-reproducer

I think this is a `wont fix` ...

_Originally posted by @PhilETaylor in https://github.com/symfony/symfony/issues/61475#issuecomment-3450794658_

Alpine JS is well known for not having valid HTML tags :( https://github.com/alpinejs/alpine/issues/433

## The Issue

**PHP 8.4+** introduced a native HTML5 DOM parser. **Symfony 7.4** automatically uses this native parser instead of the `masterminds/html5` library.

However, the native parser is **stricter about XML syntax** and throws warnings when encountering Alpine.js shorthand attributes:

- `@click` → `error parsing attribute name`
- `:class` → `Failed to parse QName ':class'`
- `@keydown.enter` → `error parsing attribute name`
- Other Alpine.js shorthands → Various XML parsing errors

## Why This Matters

In **PHPUnit integration tests** with `failOnWarning="true"`:

1. Test uses `KernelBrowser` to request a page
2. Response contains HTML with Alpine.js attributes
3. Symfony's `AbstractBrowser` automatically creates `Crawler` from response
4. PHP 8.4's DOM parser emits warnings about Alpine.js attributes
5. PHPUnit converts warnings → test failures ❌

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62176
| License       | MIT

Much better than #62180

### CODE REVIEW

**Comment by PhilETaylor** [comment]
Thanks for taking a second look. I have applied this PR to my live site and the unit tests are passing again, meaning the b/c break has been resolved.

File: src/Symfony/Component/DomCrawler/Crawler.php [hunk 1]
```diff
@@ -1258,6 +1249,49 @@ private function isValidHtml5Heading(string $heading): bool
         return 1 === preg_match('/^\x{FEFF}?\s*(<!--[^>]*?-->\s*)*$/u', $heading);
     }
 
+    private function copyFromHtml5ToDom(\Dom\Node $source, \DOMDocument $target): void
+    {
+        /** @var list<array{0: iterable<\Dom\Node>, 1: ?\DOMNode}> $stack */
```
Comment (stof) [inline src/Symfony/Component/DomCrawler/Crawler.php:1254]: can the key `1` really be nullable ? The code does not handle null values when using it.

Comment (nicolas-grekas) [reply src/Symfony/Component/DomCrawler/Crawler.php:1254]: right, I forgot to clean this up from a previous iteration, I'll do a [hotpatch](https://github.com/symfony/symfony/commit/a2812bd1ca1f7896a98e0457d8d56956c2fafd81)
