### PR TITLE
[DependencyInjection] Fixing autowiring bug when some args are set

### LINKED ISSUE #17724: Autowiring confuses argument order in some cases
Hi guys!

Take the following class:

```php
class ProductRepository
{
    private $client;
    private $logger;

    public function __construct(Client $client, LoggerInterface $logger)
    {
        $this->client = $client;
        $this->logger = $logger;
    }
}
```

Since `LoggerInterface` can't be injected yet (we're waiting on a MonologBundle tag), I wired it like this:

```yml
services:
    product_repository:
        class: AppBundle\Repository\ProductRepository
        autowire: true
        arguments:
            1: '@logger'
```

Sure, it's weird to have the "1" in there, but I thought it would work. It *almost* did, but it reversed the arguments. In the cached container, this becomes:

```php
new ProductRepository($this->get('logger'), $this->get('api_client'));
```

In YAML, I believe this is the only way to set *one* specific argument, without specifying *all* of them, and it looks like a bug :).

Especially because non-services can't be autowired yet, this probably the biggest issue left with autowiring (along with not being able to globally map a class/interface to a specific service id).

ping @dunglas 

Thanks!

### PR DESCRIPTION
**Pull request by weaverryan**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #17724, #17878 |
| License | MIT |
| Doc PR | todo |

This fixes #17724 & #17878.

**#17724**

I've set this against the 2.8 branch because imo it's a bug fix. The [test](https://github.com/symfony/symfony/compare/2.8...weaverryan:auto-wiring-individuals?expand=1#diff-d124c3d39cd5f7c732fb3d3be7a8cb42R298) illustrates the bug - having _some_ arguments set beforehand caused auto-wired arguments to be set on the wrong index.

**#17878**

I've also included this fix just to get all the weird ordering problems taken care of at once. I don't think this is a behavior change - autowiring with scalars only worked previously if the argument was optional (still works now) or if you specified that argument explicitly (still works). Otherwise, your argument ordering would have gotten messed up.

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php [hunk 1]
```diff
@@ -397,3 +512,28 @@ public function __construct(A $k)
...
+    public function __construct(A $a, Lille $lille, $foo = 'some_val')
+    {
+    }
+}
+class MultipleArgumentsOptionalScalarNotReallyOptional
+{
+    public function __construct(A $a, $foo = 'default_val', Lille $lille)
+    {
+    }
+}
```
Comment (dunglas) [inline src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php]: New line

**Comment by dunglas** [comment]
:+1:

Just a minor thing, this block https://github.com/weaverryan/symfony/blob/auto-wiring-individuals/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L74-L77 can now be inlined (the `$argumentExists` variable is not needed anymore).

Thank for fixing this!

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 2]
```diff
@@ -78,6 +78,14 @@ private function completeDefinition($id, Definition $definition)
 
             try {
                 if (!$typeHint = $parameter->getClass()) {
+                    // no default value? Then fail
+                    if (!$parameter->isOptional()) {
+                        throw new RuntimeException(sprintf('Unable to autowire argument index %s ($%s) for the service "%s". If this is an object, give it a type-hint. Otherwise, specify this argument\'s value explicitly.', $index, $parameter->name, $id));
+                    }
+
+                    // specifically pass the default value
+                    $arguments[$index] = $parameter->getDefaultValue();
```
Comment (xabbuh) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: I think we need to omit the default value when no required parameter without a default values is following. PHP populates how many arguments the user passed to a method/constructor (we use this in some places when method parameters get deprecated as `func_num_args()` exposes the number of arguments passed by the caller).

Comment (weaverryan) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: We can do this, but it's tricky. For example:

```php
public function __construct($foo = 'foo', LoggerInterface $logger = null)
```

In this case, `$foo` is optional. If we omit it but then `$logger` becomes mapped because of autowiring, we suddenly *will* need to pass the `$foo` value. This means we'll need to not set optional values here, but keep track of them and add them at the end if we detect that they are suddenly needed. Does that make sense? I was waiting to see if anyone asked about this.

Comment (dunglas) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: Your current implementation is easier to read and maintain. Anyway, it's probably a bad idea to use autowiring for classes using tricks like the one with `func_num_args()`.

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 3]
```diff
@@ -78,6 +78,14 @@ private function completeDefinition($id, Definition $definition)
 
             try {
                 if (!$typeHint = $parameter->getClass()) {
+                    // no default value? Then fail
+                    if (!$parameter->isOptional()) {
+                        throw new RuntimeException(sprintf('Unable to autowire argument index %s ($%s) for the service "%s". If this is an object, give it a type-hint. Otherwise, specify this argument\'s value explicitly.', $index, $parameter->name, $id));
```
Comment (javiereguiluz) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: Very minor comment: if `$index` is always a positive integer, should we replace this:

```php
"... argument index %s ($%s) ..."
```

by this?

```php
"... argument index %d ($%s) ..."
```

**Comment by weaverryan** [comment]
Ping @symfony/deciders - failure on appveyor is unrelated :)

**Comment by fabpot** [comment]
Thank you @weaverryan.
