### PR TITLE
[DependencyInjection] Fix inlining when public services are involved

### LINKED ISSUE #54294: [DependencyInjection] Service incorrectly inlined
### Symfony version(s) affected

5.4.37-7.0.4

### Description

Under certain circumstances, services can be incorrectly inlined in the compiled service container. This causes the error message:

```
The "App\Service1" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
```

This can be reproduced even when the entire application uses dependency injection and there is no direct use of the container.

The exact circumstances required aren't clear to me, but I've provided a fairly minimal reproduction repo below.

### How to reproduce

I've created a repository to allow reproducing here: https://github.com/edsrzf/symfony-di-repro

Steps:
* Run `composer install`
* Run `bin/console app:repro`

### Possible Solution

_No response_

### Additional Context

As a workaround, affected service(s) can be made public.

### LINKED ISSUE #58087: [DI] falsely removes a service in some conditions
### Symfony version(s) affected

6.4.10

### Description

The problem in short: DI removes doctrine repository, which is used in non-shared services, and throws an exception "You have requested a non-existent service "App\Repository\ChannelRepository"" under certain circumstances.

I stumbled upon this issue on working project, got rid of everything unrelated and tried to minimize the code. So, I have a Console command, which uses `CheckEmail` service:
```php
#[AsCommand('app:check-inbox', 'Check inbox and process emails')]
class CheckInboxCommand extends Command
{
    protected CheckEmail $action;

    public function __construct(
        CheckEmail $command
    )
    {
        parent::__construct();
    }
}
```

`CheckEmail` is a public non-shared service, which depends on two another services (processors):
```php
<?php
namespace App\Action;

use App\Processor;

class CheckEmail
{
    public function __construct(
        \App\Processor\FirstProcessor $firstProcessor,
        \App\Processor\SecondProcessor $secondProcessor,
    ) {
    }
}
```
And two similar processors, which uses service `ChannelRepository`:
```php
<?php
namespace App\Processor;

use App\Repository\ChannelRepository;
use Psr\Log\LoggerInterface;

class FirstProcessor
{
    public function __construct(
        LoggerInterface $logger,
        ChannelRepository $channelRepository,
    ) {
    }

}
```
```php
<?php
namespace App\Processor;

use App\Repository\ChannelRepository;
use Psr\Log\LoggerInterface;

class SecondProcessor
{
    public function __construct(
        //LoggerInterface $logger,
        ChannelRepository $channelRepository,
    ) {
    }
}
```

If I try to build container (clear cache or open `/` in browser), I get error "You have requested a non-existent service "App\Repository\ChannelRepository"". But there are some changes (any of them), when everything starts working:
* If `App\Action\CheckEmail` is made shared (remove "shared: false" in services.yaml), the error dissappears.
* If I comment `$logger` in `FirstProcessor` constructor https://github.com/unnamed777/project_issue/blob/master/src/Processor/FirstProcessor.php#L10, the error disappears.
* If I use `CheckEmail` in constructor of another service (and keep it in constructor of `CheckInboxCommand`), the error disappears. For instance https://github.com/unnamed777/project_issue/blob/master/src/Controller/DevController.php#L11, uncommenting `$action` in `DevController` resolves problem.
* If I remove `CheckEmail` from `CheckInboxCommand` constructor and add it in `DevController` constructor, the error disappears.

### How to reproduce

PHP 8.1 is required
* Clone https://github.com/unnamed777/project_issue
* `symfony composer install`. You'll get the the same error, but it's ok for now.
* `symfony serve`
* Open link provided by Symfony CLI. The error is appeared.
* Open `src/Processor/FirstProcesssor.php` and comment line with `$logger` in constructor. Refresh page, the error is gone.
* Undo previous change. Open `src/Controller/DevController.php` and uncommend line 11 (`CheckEmail $action`). The error is gone.
* Try other actions from description part.

### Possible Solution

_No response_

### Additional Context

Comparison of a log of `Symfony\Component\DependencyInjection\Compiler` shows the difference only in one line (it exists when the problem is here):
```
Symfony\Component\DependencyInjection\Compiler\InlineServiceDefinitionsPass: Inlined service "App\Repository\ChannelRepository" to "App\Processor\FirstProcessor".
```

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54294, fix #58087
| License       | MIT

I can't come up with a simple reproducer that'd fit in a test case :disappointed:

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/UnusedTagsPass.php [hunk 1]
```diff
@@ -32,6 +32,7 @@ class UnusedTagsPass implements CompilerPassInterface
         'chatter.transport_factory',
         'config_cache.resource_checker',
         'console.command',
+        'container.decorator',
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/UnusedTagsPass.php]: unrelated but found while inspecting the compiler logs

**Comment by MatTheCat** [comment]
Nice! Would that fix #58087 as well?

**Comment by nicolas-grekas** [comment]
That looks quite likely. Can you give the repro a try?

**Comment by MatTheCat** [comment]
Can confirm it was fixed as well :+1:
