### PR TITLE
[Security] Add a method in the security helper to ease programmatic login (#40662)

### LINKED ISSUE #40662: [Security][DX] RFC: A simple way to do programmatic login
**Description**
There are various reasons why an app may need to login a user without the user having to go through the configured authenticators. A few examples I ran into are logging the user in after a password reset, or after the registration confirmation email was clicked.

**Example**
IMO a great API to have would be [`Security`](https://github.com/symfony/symfony/blob/f963ae476a6534b29b638f47d19dc076a0afebd5/src/Symfony/Component/Security/Core/Security.php)`::programmaticLogin(Request $request, UserInterface $user, ?AuthenticatorInterface $authenticator = null)`

After discussing this with @wouterj - it appears that the main complexity here is in choosing which Token class should be used. IMO it'd be fine to by default, pick the default authenticator for the current firewall, and make that one authenticate the user via createAuthenticatedToken. If that's not ok the developer can optionally pass the correct authenticator.

**Why?**
I had to figure this out myself and it took some help from @wouterj + some trial and error to arrive at this code:

```
        try {
            $this->userChecker->checkPreAuth($event->getUser());
        } catch (AuthenticationException $e) {
            // skip authenticating if any pre-auth check does not pass
            return;
        }
        if (($response = $this->userAuthenticator->authenticateUser($event->getUser(), $this->myPreferredAuthenticator, $event->getRequest()))) {
            return $response;
        }
```

Now as you can see, you have to know about [UserAuthenticatorInterface](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Security/Http/Authentication/UserAuthenticatorInterface.php) to get that service injected, you then have to also figure out what the class name of your preferred authenticator is to get that injected, and then I also had to remember to call the user checker otherwise inactive users were being logged in under some circumstances which is not good.

Not too bad, I survived, but I can imagine this would be a bigger roadblock for others less familiar with the framework, so having some easier API in a more visible location would be nice.

### PR DESCRIPTION
**Pull request by johnkrovitch**
| Q             | A
| ------------- | ---
| Branch?       | 6.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #40662
| License       | MIT
| Doc PR        | 

This PR aims to ease the programmatic login using the Security helper, to fix (#40662).

A simple method has been added to the Security helper. It take a user and an optional Authenticator. If no authenticator is passed, we find all authenticators for the current firewall. Then if only one is matching we use this one. If several authenticators are found, an exception is thrown to avoid any magic (by choosing the first for example), the user HAS to provide an authenticator.

Thanks

### CODE REVIEW

**Comment by emancypage** [comment]
Hello @johnkrovitch!
I tried to use your code in my environment and I noticed one issue here. In case of this configuration for firewall security:
```
firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
```
I've got an error message:
image

You are assuming that we always will have fourth parameter from \Symfony\Bundle\SecurityBundle\DependencyInjection\SecurityExtension::createFirewall() but please look into this line of code: https://github.com/symfony/symfony/blob/2fe4442a1a28ea0d78bfe8d00476229e84ccf19c/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L365 
This also should be adjusted in your code I think.

**Comment by johnkrovitch** [comment]
Thanks for your response. It is fixed.

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 1]
```diff
@@ -317,6 +321,10 @@ private function createFirewalls(array $config, ContainerBuilder $container)
             $contextRefs[$contextId] = new Reference($contextId);
             $map[$contextId] = $matcher;
         }
+        $container
+            ->getDefinition('security.helper')
+            ->replaceArgument(0, $authenticators)
```
Comment (chalasr) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]: Authenticators need to be lazy loaded:
```suggestion
            ->replaceArgument(0, ServiceLocatorTagPass::register($container, $authenticators))
```

File: src/Symfony/Component/Security/Core/Security.php [hunk 2]
```diff
@@ -69,4 +77,35 @@ public function getToken(): ?TokenInterface
...
+
+            if (null === $firewall) {
+                throw new LogicException('No firewall found as the current route is not covered by any firewall.');
+            }
+            $firewallName = $firewall->getName();
+
+            if (!\array_key_exists($firewallName, $this->authenticators) || 0 === \count($this->authenticators[$firewallName])) {
+                throw new LogicException(sprintf('No authenticators found for the firewall "%s".', $firewallName));
+            }
+            $firewallAuthenticators = $this->authenticators[$firewallName];
```
Comment (chalasr) [inline src/Symfony/Component/Security/Core/Security.php]: once my previous suggestion applied, this will be a `ServiceProviderInterface` instance. You can use `getProvidedServices()` to access the authenticator identifiers for the selection logic below

**Review by chalasr — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Security/Core/Security.php [hunk 3]
```diff
@@ -30,8 +32,14 @@ class Security implements AuthorizationCheckerInterface
 
     private $container;
 
-    public function __construct(ContainerInterface $container)
+    /**
+     * @var array
+     */
+    private $authenticators;
+
+    public function __construct(array $authenticators, ContainerInterface $container)
```
Comment (chrishalbert) [inline src/Symfony/Component/Security/Core/Security.php]: Should `$authenticators` be an optional second parameter rather? That way changes to this core class can be backwards compatible, which would avoid necessitating a major release.

File: src/Symfony/Component/Security/Core/Tests/SecurityTest.php [hunk 4]
```diff
@@ -33,7 +41,7 @@ public function testGetToken()
 
         $container = $this->createContainer('security.token_storage', $tokenStorage);
 
-        $security = new Security($container);
+        $security = new Security([], $container);
```
Comment (chrishalbert) [inline src/Symfony/Component/Security/Core/Tests/SecurityTest.php]: This should be undone, illustrating backwards compatibility. Similarly below.

File: src/Symfony/Component/Security/Core/Tests/SecurityTest.php [hunk 5]
```diff
@@ -81,10 +89,62 @@ public function testIsGranted()
...
+            ->method('authenticateUser')
+            ->with($user, $authenticator, $request)
+        ;
+        $userChecker
+            ->expects($this->once())
+            ->method('checkPreAuth')
+            ->with($user)
+        ;
+
+        $security = new Security([
```
Comment (chrishalbert) [inline src/Symfony/Component/Security/Core/Tests/SecurityTest.php]: Swap the arguments.

**Review by chrishalbert — COMMENTED** [review]
I have a few suggestions regarding backwards compatibility and semantic versioning.

File: src/Symfony/Component/Security/Core/Security.php (hunk 3 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Security.php]: Thanks ! Changes done.

File: src/Symfony/Component/Security/Core/Tests/SecurityTest.php (hunk 4 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Tests/SecurityTest.php]: Thanks ! Changes done.

File: src/Symfony/Component/Security/Core/Tests/SecurityTest.php (hunk 5 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Tests/SecurityTest.php]: Thanks ! Changes done.

File: src/Symfony/Component/Security/Core/Security.php [hunk 6]
```diff
@@ -57,4 +66,39 @@ public function getToken(): ?TokenInterface
     {
         return $this->container->get('security.token_storage')->getToken();
     }
+
+    public function autoLogin(UserInterface $user, AuthenticatorInterface $authenticator = null, string $firewallName = null): void
```
Comment (chalasr) [inline src/Symfony/Component/Security/Core/Security.php]: I guess we can call it `login()` for the same reasoning as the `logout()` one.

File: src/Symfony/Component/Security/Core/Security.php [hunk 7]
```diff
@@ -57,4 +66,39 @@ public function getToken(): ?TokenInterface
...
+            /** @var ServiceProviderInterface $firewallAuthenticatorLocator */
+            $firewallAuthenticatorLocator = $this->authenticators[$firewallName];
+            $authenticatorIds = array_keys($firewallAuthenticatorLocator->getProvidedServices());
+
+            if (!$authenticatorIds) {
+                throw new LogicException('No authenticator was found for the firewall "%s".');
+            }
+
+            if (1 < \count($authenticatorIds)) {
+                throw new LogicException(sprintf('Too much authenticators were found for the current firewall "%s". You must provide an instance of "%s" to allow an auto login. The available authenticators for the firewall "%s" are "%s".', $firewallName, AuthenticatorInterface::class, $firewallName, implode('" ,"', $authenticatorIds)));
```
Comment (chalasr) [inline src/Symfony/Component/Security/Core/Security.php]:
```suggestion
                throw new LogicException(sprintf('Too much authenticators were found for the current firewall "%s". You must provide an instance of "%s" to login programatically. The available authenticators for the firewall "%s" are "%s".', $firewallName, AuthenticatorInterface::class, $firewallName, implode('" ,"', $authenticatorIds)));
```

**Review by chalasr — CHANGES_REQUESTED** [review]
Some comments. A CHANGELOG entry will be needed also

File: src/Symfony/Component/Security/Core/Security.php (hunk 6 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Security.php]: Changed. Thank you !

File: src/Symfony/Component/Security/Core/Security.php (hunk 7 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Security.php]: Changed. Thank you !

**Comment by johnkrovitch** [comment]
The security change log has been updated

File: src/Symfony/Component/Security/Core/CHANGELOG.md [hunk 8]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+6.1
+---
+
+ * Add `Security::login()` to logout programmatically
```
Comment (1ed) [inline src/Symfony/Component/Security/Core/CHANGELOG.md]: `logout` -> `login`

File: src/Symfony/Component/Security/Core/Security.php [hunk 9]
```diff
@@ -57,4 +66,39 @@ public function getToken(): ?TokenInterface
     {
         return $this->container->get('security.token_storage')->getToken();
     }
+
+    public function login(UserInterface $user, AuthenticatorInterface $authenticator = null, string $firewallName = null): void
+    {
```
Comment (1ed) [inline src/Symfony/Component/Security/Core/Security.php]: I think it would be nice if the authenticator could be a string, like `form_login`.
Maybe we should add multiple methods like `login(UserInterface $user, ?string $authenticatorName = null, ?string $firewallName = null)` and loginWithAuthenticator(UserInterface $user, AuthenticatorInterface $authenticator)`. What do you think?

File: src/Symfony/Component/Security/Core/Security.php [hunk 10]
```diff
@@ -57,4 +66,39 @@ public function getToken(): ?TokenInterface
...
+        $request = $this->container->get('request_stack')->getCurrentRequest();
+
+        if (null === $authenticator) {
```
Comment (1ed) [inline src/Symfony/Component/Security/Core/Security.php]: These could be refactored to private getters, something like:
```php
$request = $this->getRequest();
$authenticator = $authenticator ?? $this->getAuthenticator($firewallName ?? $this->getFirewallName($request));
```

File: src/Symfony/Component/Security/Core/Security.php (hunk 9 above)
Comment (chalasr) [reply src/Symfony/Component/Security/Core/Security.php]: Sounds good to me. I'd rather keep only `login(UserInterface $user, ?string $authenticatorName = null, ?string $firewallName = null)`, passing the authenticator name/id is enough for the case at hand and avoids the need for retrieving it first

**Comment by chalasr** [comment]
Same as #41406, we need to require security-http as a dev dependency to make tests pass, and throw an exception if it's not installed.

File: src/Symfony/Component/Security/Core/CHANGELOG.md (hunk 8 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/CHANGELOG.md]: Thanks for your feedback. Changes done.

File: src/Symfony/Component/Security/Core/Security.php (hunk 9 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Security.php]: Done

File: src/Symfony/Component/Security/Core/Security.php (hunk 10 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Security.php]: Done

File: src/Symfony/Component/Security/Core/Security.php [hunk 11]
```diff
@@ -57,4 +67,58 @@ public function getToken(): ?TokenInterface
     {
         return $this->container->get('security.token_storage')->getToken();
     }
+
+    public function login(UserInterface $user, string $authenticatorName = null, string $firewallName = null): void
```
Comment (weaverryan) [inline src/Symfony/Component/Security/Core/Security.php]: The authenticatorName would be the “key” from the firewall - like form_login? What about custom_authenticators? Are they included in this list? And would the user pass the service id to the custom authenticator?

**Review by weaverryan — COMMENTED** [review]
I like this - it adds one level of “easy” that is currently lacking (especially if you are trying to use the current user authenticator to authenticate against a built-in authenticator like form_login - that requires some expert digging currently)

**Comment by wouterj** [comment]
Hi! Thanks for these 2 PRs and sorry for the long wait, @johnkrovitch.
I very much like this feature from a usage point. Whenever programmatic login/logout code is complex to use, there is a chance an application forgets one important bit and creates a security issue. These 2 PRs seem to make things simpler to use, and thus safer!

But I've been silent in this PR because I'm afraid the implementation is not that optimal. I've been discussing this internally with some core team members during last SymfonyWorld online, but we cannot easily come up with a good alternative.

I'm concerned about 2 main things, which are also shared by #41406:

1. The duplicated code between `Security` and `AuthenticatorManager`. With security code in particular, duplicating the same code can create unwanted vulnerabilities (e.g. whenever we fix a CVE in one place, but forget there was a duplicate piece somewhere else).
2. The `Security` class was already a "black sheep" in the Security Core component, given it relies on service names configured in the SecurityBundle. The changes in these 2 PRs make this coupling issue even more visible (not only coupling to service names, but also classes from SecurityBundle and Security Http). To clarify: this is not an issue with the code you wrote, but an issue with the original design of this class.

In short, I would really love to merge these 2 PRs from a DX point of view - but I can't from a maintainer perspective. Does anyone have great insights in how to overcome these issues? :)

File: src/Symfony/Component/Security/Core/Security.php (hunk 11 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Security.php]: Thanks for your response. The key is the firewall name as defined in the security.yaml. The firewalls are build in the SecurityExtension with the `createFirewall` method. I'm not sure if this takes account of custom authenticators. I would say no.

**Comment by johnkrovitch** [comment]
@wouterj Thanks for your response ! No problem about the wait.

I totally forgot about the csrf logout indeed in the other PR. I choose to use the `Security`class from a developer point of view : I generally use this class because it as all the required methods to handle the security process we need. So it make senses for me to add the login/logout features in this one. But i totally understand your point of view about this class.

But I don't know what should we do ? :) Create a new class to only handle the login/logout ? Maybe create a "context" like "UserContext" with a getUser method, like Sylius does, to get rid of this `Security` class ? The good point about the Security class is that you do not have to inject several classes to handle common case such as retreving user, then checking permissions...

And yes the coupling is so visible that I had to add the require http to the composer of the Security component :)

**Comment by wouterj** [comment]
I'm happy to tell that we've moved the `Security` class to the SecurityBundle in the 6.2 branch: https://github.com/symfony/symfony/pull/46094 This means we have unlocked the biggest blocker in these 2 PRs: depending on SecurityBundle from this "facade" class.

@johnkrovitch I know this PR is in the brewing stage for a long time, do you have time to rebase on these recent changes and unlock this PR? If you no longer have time, please tell us and I'll continue this PR with your commits :)

**Comment by johnkrovitch** [comment]
@wouterj Hi thanks for the changes and thank @chalasr . I try to rebase this evening.

**Comment by johnkrovitch** [comment]
@wouterj The pr is rebased with the last changes from 6.2

File: src/Symfony/Bundle/SecurityBundle/Security/Security.php [hunk 12]
```diff
@@ -31,4 +35,58 @@ public function getFirewallConfig(Request $request): ?FirewallConfig
     {
         return $this->container->get('security.firewall.map')->getFirewallConfig($request);
     }
+
+    public function login(UserInterface $user, string $authenticatorName = null, string $firewallName = null): void
+    {
+        $request = $this->container->get('request_stack')->getCurrentRequest();
+
+        if (!class_exists(AuthenticatorInterface::class)) {
```
Comment (chalasr) [inline src/Symfony/Bundle/SecurityBundle/Security/Security.php]: unlikely to happen I think

File: src/Symfony/Component/Security/Core/CHANGELOG.md [hunk 13]
```diff
@@ -6,6 +6,12 @@ CHANGELOG
 
 * Deprecate the `Security` class, use `Symfony\Bundle\SecurityBundle\Security\Security` instead
 
+6.1
```
Comment (chalasr) [inline src/Symfony/Component/Security/Core/CHANGELOG.md]:
```suggestion
6.2
```

**Review by chalasr — CHANGES_REQUESTED** [review]

File: src/Symfony/Bundle/SecurityBundle/Security/Security.php (hunk 12 above)
Comment (johnkrovitch) [reply src/Symfony/Bundle/SecurityBundle/Security/Security.php]: Hehe, indeed. So, should I remove the class_exists ?

Comment (chalasr) [reply src/Symfony/Bundle/SecurityBundle/Security/Security.php]: Please yes

**Comment by chalasr** [comment]
Now with a functional test. Remaining comments addressed. PR ready

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Component/Security/Core/Security.php (hunk 11 above)
Comment (chalasr) [reply src/Symfony/Component/Security/Core/Security.php]: It just missed a few bits for custom authenticators to be handled properly! It's ok now (and tested)
```php
$security->login($user, ApiKeyAuthenticator::class);
```

**Review by kbond — APPROVED** [review]

File: src/Symfony/Bundle/SecurityBundle/Security/Security.php [hunk 14]
```diff
@@ -31,4 +35,60 @@ public function getFirewallConfig(Request $request): ?FirewallConfig
...
+            throw new LogicException(sprintf('No authenticators found for firewall "%s".', $firewallName));
+        }
+        /** @var ServiceProviderInterface $firewallAuthenticatorLocator */
+        $firewallAuthenticatorLocator = $this->authenticators[$firewallName];
+
+        if (!$authenticatorName) {
+            $authenticatorIds = array_keys($firewallAuthenticatorLocator->getProvidedServices());
+
+            if (!$authenticatorIds) {
+                throw new LogicException('No authenticator was found for the firewall "%s".');
```
Comment (fabpot) [inline src/Symfony/Bundle/SecurityBundle/Security/Security.php]:
```suggestion
                throw new LogicException(sprintf(('No authenticator was found for the firewall "%s".', $firewallName));
```

**Review by fabpot — APPROVED** [review]

File: src/Symfony/Bundle/SecurityBundle/Security/Security.php (hunk 14 above)
Comment (chalasr) [reply src/Symfony/Bundle/SecurityBundle/Security/Security.php]: 👍 fixed

**Comment by chalasr** [comment]
It took time, but here we go, this is in now. Thank you very much @johnkrovitch.

**Comment by hellomedia** [comment]
Thanks for this.

The `authenticate` method can return a redirect response - when redirection logic is defined in `onAuthenticationSuccess`.

Shouldn't the `login` method return the same - by returning the return value of  `authenticate` ?
