### PR TITLE
[Translation] Allow using dashes in locale when linting Xliff files

### LINKED ISSUE #40170: [Translation] XliffLintCommand complains about using locales with language and region with dash separator in file name
**Symfony version(s) affected**: 4.4.19

**Description**  

I am working on a Symfony application where I prefer to use full locales with language and region where language and region are separated by a dash (`de-DE`) instead of an underscore as a separator (`de_DE`).

The format using dashes

- conforms with https://tools.ietf.org/html/bcp47
- is widely used for identifying locales in frontend technologies
- is also supported by `ext/intl` (see https://www.php.net/manual/en/class.locale.php)

So far, the application works fine with locales in this format, except for the `XliffLintCommand`.

**How to reproduce**  

Running

```
$ bin/console lint:xliff translations/example.de-DE.xml
```

when an example file with the file name `translations/example.de-DE.xml` contains

```xml
<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file source-language="de-DE" target-language="de-DE"  datatype="plaintext" original="file.ext">
    <header>
      <tool tool-id="symfony" tool-name="Symfony"/>
    </header>
    <body>
    </body>
  </file>
</xliff>
```

yields a misleading error message

```
  ERROR  in translations/example.de-DE.xlf
 * There is a mismatch between the language included in the file name ("example.de-DE.xlf") and the "de-DE" value used in the "target-language" attribute of the file.


 [WARNING] 0 XLIFF files have valid syntax and 1 contain errors.
```

As far as I can tell, there is no mismatch.

**Possible Solution**  

From here on I have the following options:

- I do not run the linting command anymore, possibly resulting in invalid translations.
- I rename the file from `translations/example.de-DE.xml` to `translations/example.de_DE.xml. This has the consequence that the translations are not loaded anymore.
- I stop using locales that use a dash (`de-DE`) instead of an underscore as a separator (`de_DE`).
- I propose a pull request that fixes the problem.

❓ Would you accept a pull request that adjusts the `XliffLintCommand` to account for users who prefer locales with a dash as a separator?

### PR DESCRIPTION
**Pull request by localheinz**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | fixes #40170
| License       | MIT
| Doc PR        | n/a

This pull request

* [x] asserts that the `XliffLintCommand` succeeds linting an Xliff file where both the the target language and the locale in the file name use dashes as separators
* [x] adjusts the `XliffLintCommand` to allow using the same value for target language and locale in the corresponding file name

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]
Thanks, I am just not sure if this should be considered a bugfix or a new feature 🧐

**Comment by localheinz** [comment]
@OskarStark 

A bug fix would be great, since the corresponding application can not yet upgrade to `symfony/translation:^5`.

🤓

**Comment by OskarStark** [comment]
I know, from my perspective it can be considered a bugfix, as you explained it is conform with the spec 👍🏻

File: src/Symfony/Component/Translation/Command/XliffLintCommand.php [hunk 1]
```diff
@@ -129,12 +129,16 @@ private function validate(string $content, string $file = null): array
         $document->loadXML($content);
 
         if (null !== $targetLanguage = $this->getTargetLanguageFromFile($document)) {
-            $normalizedLocale = preg_quote(str_replace('-', '_', $targetLanguage), '/');
+            $normalizedLocalePattern = sprintf(
+                '(%s|%s)',
+                $targetLanguage,
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Command/XliffLintCommand.php]: missing preg_quote about, isn't it?
can you also please keep the call on one line?

Comment (localheinz) [reply src/Symfony/Component/Translation/Command/XliffLintCommand.php]: @nicolas-grekas 

Adjusted!

**Review by OskarStark — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @localheinz.

**Comment by localheinz** [comment]
Thank you, @derrabus, @fabpot, @nicolas-grekas, and @OskarStark!

**Comment by sschueller** [comment]
Will this change validate ```de-x-app123``` or ```de-x-app123-a``` as valid? According to xliff 1.2 (```urn:oasis:names:tc:xliff:document:1.2```) this should be validated with ```xsd:language``` which is ```[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*```

**Comment by OskarStark** [comment]
Open for a PR including a testcase so we can talk about code and an example?
