### PR TITLE
SMTP Transport to provide the (final) Message-ID if available

### LINKED ISSUE #46323: [Mailer][Amazon] SMTP transport does not provide the (final) Message-ID
### Symfony version(s) affected

6.1.0

### Description

In #33967 multiple Mailer Transports were adapted to use `$sentMessage->setMessageId(<final Message ID>);`.
Among them `SesApiTransport` and `SesHttpTransport` **but `SesSmtpTranspor` was not**: It still provides the **original** Message-id (set by Symfony itself).

Since `symfony/mailer` is often used to abstract transport-specific logic it may easily result in errors where the return value is not the expected one. (In my case I need to check for actual deliverability against AWS SNS service what can only work if I stored the AWS-issued Message-ID)

### How to reproduce

`MAILER_DSN=ses+smtp://foo:bar@default?region=eu-west-1`
```php
$mailer->send($message);
echo $mailer->getMessageId();
```

### Possible Solution

As per https://docs.aws.amazon.com/ses/latest/dg/troubleshoot-smtp.html
The Message-Id is returned as part of the `250 Ok` response to the `DATA` SMTP command.

### PR DESCRIPTION
**Pull request by drzraf**
bug #46323 [Mailer] SMTP transport does not provide the (final) Message-ID

| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #46323
| License       | MIT
| Doc PR        | symfony/symfony-docs#

Questions / Answers:
- **Q**: Why storing 250 inside **`$mtaResult`** instead of using the already available `$message->getDebug()`?
- A: Because the later may be huge (especially in case of attachment) and running a regexp over it would be less than safe. Instead `$mtaResult` only contains one line
- **Q**: Why a new **`public`** method?
- A: Because child SMTP Transport may make other assumptions about the return `250 Ok` value and provide a custom logic / regexp.
- **Q**: Why **regexp**?
- A: Because there is no official standard for this line (other than the `250 Ok` prefix)

Additionally (see https://symfony.com/releases):
- [ ] Always add tests and ensure they pass. _I can't. Don't have the time. Left to maintainers / other contributors_
- [x] Bug fixes must be submitted against the lowest maintained branch where they apply (lowest branches are regularly merged to upper ones so they get the fixes too.)
- [x] Features and deprecations must be submitted against the latest branch.
- [x] Changelog entry should follow https://symfony.com/doc/current/contributing/code/conventions.html#writing-a-changelog-entry
- [x] Never break backward compatibility (see https://symfony.com/bc).

### CODE REVIEW

File: src/Symfony/Component/Mailer/Transport/Smtp/SmtpTransport.php [hunk 1]
```diff
@@ -146,11 +147,33 @@ public function send(RawMessage $message, Envelope $envelope = null): ?SentMessa
...
     }
 
+    public function parseMessageId(SentMessage $message): void
+    {
+        $regexps = [
+            '/250 Ok (?P<id>[0-9a-f-]+)\r?$/mis',
+            '/250 Ok:? queued as (?P<id>[A-Z0-9]+)\r?$/mis'
+        ];
+
+        if (empty($this->mtaResult)) {
```
Comment (stof) [inline src/Symfony/Component/Mailer/Transport/Smtp/SmtpTransport.php]: use `if ($this->mtaResult === '')` instead of `empty()`

File: src/Symfony/Component/Mailer/Transport/Smtp/SmtpTransport.php [hunk 2]
```diff
@@ -146,11 +147,33 @@ public function send(RawMessage $message, Envelope $envelope = null): ?SentMessa
             throw $e;
         }
 
+        $this->parseMessageId($message);
         $this->checkRestartThreshold();
 
         return $message;
     }
 
+    public function parseMessageId(SentMessage $message): void
```
Comment (stof) [inline src/Symfony/Component/Mailer/Transport/Smtp/SmtpTransport.php]: if the goal is to allow child classes to customize it, it should be protected, not public

Comment (stof) [reply src/Symfony/Component/Mailer/Transport/Smtp/SmtpTransport.php]: and if the child classes should customize it, it should receive `$this->mtaResult` as argument instead of accessing the private property inside it (which child classes cannot do), and I would rather return the message id than expect the method to mutate a provided SentMessage.

**Review by stof — CHANGES_REQUESTED** [review]

**Comment by drzraf** [comment]
ping @stof 

(Review addressed)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @drzraf.
