### PR TITLE
[Scheduler] Fix stateful scheduler

### LINKED ISSUE #51646: [Scheduler] Intermittent Runs
### Symfony version(s) affected

6.3.4

### Description

When using the scheduler with a single daily recurring message we are often seeing days where the scheduler appears to have not run. 

Here is the schedule config:

```php
return (new Schedule())
    ->add(RecurringMessage::every('1 day', new OurDailyMessage(), from: '10:30'))
    ->stateful($this->cache)
;
```

We have configured caching for the scheduler provider using the database, to allow it to catchup if the task was to crash.  The servers run in UTC.

We have added some middleware to attempt to give some visibility to scheduler activity, which just logs when each message is dispatched on the schedule.

```php
class SchedulerLoggingMiddleware implements MiddlewareInterface
{
    public function __construct(
        private readonly Connection $connection,
    ) {
    }

    public function handle(Envelope $envelope, StackInterface $stack): Envelope
    {
        if (null !== $envelope->last(ScheduledStamp::class)) {
            $this->connection->insert('scheduler_log', [
                'date_created' => new \DateTimeImmutable(),
                'message' => $envelope->getMessage()::class,
            ], [
                Types::DATETIME_IMMUTABLE,
                \PDO::PARAM_STR,
            ]);
        }

        return $stack->next()->handle($envelope, $stack);
    }
}
```

This is then run in production alongside our other Messenger transports (eg. `async another_transport`) with an ECS task.

```bash
bin/console messenger:consume scheduler_default async another_transport etc --limit=1000 --time-limit=3600 
```

As you can see from the logs it appears some days are missing (ie. 10th and 7th in this example).

image

I know this is a tricky one, as I don't have an exact reproduction, or really know where to start debugging this. I'm hoping in raising an issue perhaps there's something obvious which is incorrectly configured, or someone can indicate an area to look at to attempt to debug or reproduce this.

### How to reproduce

As indicated above I do not have a reproduction, running the scheduler locally on shorter timeframes seems to behave as intended, and debugging a daily job is hard so I'm hoping for some pointers before beginning on that.

### Possible Solution

Unsure if this is related: https://github.com/symfony/symfony/issues/51384

### Additional Context

 1. Is running the scheduler in the same command as other messenger transports a valid use? I thought the cache should allow the scheduler to catch up if it happens to be busy at that moment...  but should the scheduler always be run as the sole transport?

### PR DESCRIPTION
**Pull request by valtzu**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #51646, #51384
| License       | MIT

Stateful scheduler seems rather broken at the moment, see https://github.com/symfony/symfony/issues/51384#issuecomment-1703915652.

Let's fix it by storing the original first run start time, that way it's always possible to recalculate the state.

Catching-up works now:
```
[23:14:11.709710] Worker started
[23:14:11.759318] every 2 seconds
[23:14:11.760291] every 2 seconds
[23:14:11.761257] every 2 seconds
[23:14:11.763244] every 2 seconds
[23:14:12.637054] every 2 seconds
[23:14:14.620595] every 2 seconds
[23:14:16.632170] every 2 seconds
```

Whereas before it would only start on from the current item, possibly skipping previous items like stated in #51646. _(is this a bc break?)_

I will be waiting for input from authors of the related issues.

---

One test is failing because because `getNextRunDate` is called with `2020-02-20T01:59:00+02:00` and then next run date is expected at `2020-02-20T02:09:00+02:00` but we get `2020-02-20T02:00:00+02:00` because that's set as `from`. I don't quite get the logic, I would assume that it is expected to be run immediately on `from` :thinking:

### CODE REVIEW

File: src/Symfony/Component/Scheduler/Trigger/PeriodicalTrigger.php [hunk 1]
```diff
@@ -85,19 +86,24 @@ public function __toString(): string
...
 
-            $fromDate = min($this->from, $run);
-            $from = $fromDate->format('U.u');
+            $fromDate = $this->from;
+            $from = (float) $fromDate->format('U.u');
             $delta = $run->format('U.u') - $from;
             $recurrencesPassed = floor($delta / $this->intervalInSeconds);
             $nextRunTimestamp = sprintf('%.6F', ($recurrencesPassed + 1) * $this->intervalInSeconds + $from);
-            $nextRun = \DateTimeImmutable::createFromFormat('U.u', $nextRunTimestamp, $fromDate->getTimezone());
+            $nextRun = \DateTimeImmutable::createFromFormat('U.u', $nextRunTimestamp)->setTimezone($fromDate->getTimezone());
```
Comment (fabpot) [inline src/Symfony/Component/Scheduler/Trigger/PeriodicalTrigger.php]: It looks like this change is not needed, is it?

File: src/Symfony/Component/Scheduler/Generator/CheckpointInterface.php [hunk 2]
```diff
@@ -18,6 +18,8 @@ interface CheckpointInterface
 {
     public function acquire(\DateTimeImmutable $now): bool;
 
+    public function from(): \DateTimeImmutable;
```
Comment (fabpot) [inline src/Symfony/Component/Scheduler/Generator/CheckpointInterface.php:18]: Not a BC break as the component is experimental in 6.3, but this should be described in the component CHANGELOG file.

File: src/Symfony/Component/Scheduler/Trigger/PeriodicalTrigger.php [hunk 3]
```diff
@@ -133,6 +140,6 @@ private function canBeConvertedToSeconds(\DateInterval $interval): bool
 
     private function calcInterval(\DateInterval $interval): float
     {
-        return $this->from->setTimestamp(0)->add($interval)->format('U.u');
+        return (new \DateTimeImmutable('@0'))->add($interval)->format('U.u');
```
Comment (fabpot) [inline src/Symfony/Component/Scheduler/Trigger/PeriodicalTrigger.php]: Why do we need this change?
We might add `(float) ` to make Psalm happy :)

**Review by fabpot — CHANGES_REQUESTED** [review]
I was working on the same.
The failing test must be updated as the current one is broken and does not make sense as you already noticed.

File: src/Symfony/Component/Scheduler/Trigger/PeriodicalTrigger.php (hunk 1 above)
Comment (valtzu) [reply src/Symfony/Component/Scheduler/Trigger/PeriodicalTrigger.php]: From my testing, UTC is always forced in the DateTime instance when it is created from unix timestamp (timezone constructor arg has no effect), so to have the same timezone, it must be set after the instance is created.

But you are right in that this fix is not related to the issue and can/should probably be excluded here.

File: src/Symfony/Component/Scheduler/Trigger/PeriodicalTrigger.php (hunk 3 above)
Comment (valtzu) [reply src/Symfony/Component/Scheduler/Trigger/PeriodicalTrigger.php]: I originally made this because $this->from was not always available at this point, I'm not sure if that's the case anymore

Comment (fabpot) [reply src/Symfony/Component/Scheduler/Trigger/PeriodicalTrigger.php:143]: ok, can you submit a PR on this change on 6.3?

**Comment by fabpot** [comment]
This must be merged on 6.4 (because of the BC break, which is allowed in 6.4 for experimental components, but not for a patch release).

**Comment by valtzu** [comment]
> I was working on the same. 

@fabpot Would you like to take over this, or if you had done work on this already, discard this MR as you probably have better knowledge in this :sweat_smile:

File: src/Symfony/Component/Scheduler/Trigger/PeriodicalTrigger.php (hunk 1 above)
Comment (fabpot) [reply src/Symfony/Component/Scheduler/Trigger/PeriodicalTrigger.php]: Can you submit another PR on 6.3 for this change then?

**Comment by fabpot** [comment]
> > I was working on the same.
> 
> @fabpot Would you like to take over this, or if you had done work on this already, discard this MR as you probably have better knowledge in this 😅

Actually, I like your code better, so if you take into account my few comments, I will be able to merge it fast.

File: src/Symfony/Component/Scheduler/Generator/CheckpointInterface.php (hunk 2 above)
Comment (stof) [reply src/Symfony/Component/Scheduler/Generator/CheckpointInterface.php:18]: Well, technically it is a BC break, but an allowed one. the changelog needs to explicitly mark it as a BC break.

Comment (valtzu) [reply src/Symfony/Component/Scheduler/Generator/CheckpointInterface.php:18]: If we didn't want this BC break, we could store 2 checkpoints, one for the start state (I guess index would always be -1) and other for latest state (=the current). Let me know if you'd prefer that

Comment (fabpot) [reply src/Symfony/Component/Scheduler/Generator/CheckpointInterface.php:18]: As we will merge this PR in 6.4, adding a new method is acceptable, so no worries.

**Comment by valtzu** [comment]
Sorry I think I misunderstood your comment @fabpot and retargeted this to 6.4 :sweat_smile: 

The triggers have changed quite much between the 6.3&6.4  branches, but I should still target 6.3 and leave conflict resolution to someone else?

Oh my, I think I have notified everyone... sorry guys!

I will finish for today not to cause any more trouble.

**Review by fabpot — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @valtzu.
