### PR TITLE
[FrameworkBundle] Fix framework bundle lock configuration not working as expected

### LINKED ISSUE #31197: [FrameworkBundle] Lock configuration not working as expected
**Symfony version(s) affected**: >=3.4

**Description**  
I've found two issues with the framework bundle lock configuration:
1) When you don't have the full stack framework but only certain components, eg flex
2) When xml is used

**How to reproduce**

1) Add the following configuration to a symfony installation that's **NOT** a full stack one:

```yaml
    lock:
        invoice: 'flock'
        report: 'semaphore'
```

You'll get the following error:

```sh
In Configuration.php line 955:

  Notice: Undefined index: enabled 
```

The problem is with the following configuration:

```php
// src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
    ->{!class_exists(FullStack::class) && class_exists(Lock::class) ? 'canBeDisabled' : 'canBeEnabled'}()
    ->beforeNormalization()
        ->ifTrue(function ($v) { return \is_array($v) && !isset($v['resources']); })
        ->then(function ($v) {
            $e = $v['enabled'];
            unset($v['enabled']);

            return ['enabled' => $e, 'resources' => $v];
        })
    ->end()
```

When you have a full stack symfony installation  `canBeEnabled` adds an `enabled` flag:

```php
// src/Symfony/Component/Config/Definition/Builder/ArrayNodeDefinition.php
    ->beforeNormalization()
        ->ifArray()
        ->then(function ($v) {
            $v['enabled'] = isset($v['enabled']) ? $v['enabled'] : true;
    
            return $v;
        })
    ->end()
```

`canBeDisabled` however does not do this, but the `beforeNormalization` configuration code assumes that `enabled` always exists (the `$e = $v['enabled'];` part).

2) I've tried using the xml from [the original PR](https://github.com/symfony/symfony/blob/b4b00c9c6f7fb10e02eaa6faf34291261c5e5e59/src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/Fixtures/xml/lock_named.xml) but I got the foloowing error:

```sh
  Invalid type for path "framework.lock.resources.resource.0". Expected scalar, but got array.

```

The reason for this is cause `->fixXmlConfig('resource')` happenes after all the `beforeNormalization` rules, one of which is:

```php
    ->beforeNormalization()
        ->ifTrue(function ($v) { return \is_array($v) && !isset($v['resources']); })
        ->then(function ($v) {
            $e = $v['enabled'];
            unset($v['enabled']);

            return ['enabled' => $e, 'resources' => $v];
        })
    ->end()
```

so you get:

```php
    'resources' => [
        'resource' => [
            [
                'name'  => 'foo',
                'value' => 'semaphore',
            ],
            [
                'name'  => 'bar',
                'value' => 'flock',
            ],
        ],
    ],
```

Also, adding `->useAttributeAsKey('name')` doesn't help cause of the following `beforeNormalization` rule which is run first:

```php
    ->beforeNormalization()
        ->ifTrue(function ($v) { return \is_array($v) && array_keys($v) === range(0, \count($v) - 1); })
        ->then(function ($v) { return ['default' => $v]; })
    ->end()
```

so you get:

```php
    'resources' => [
        'default' => [
            [
                'name'  => 'foo',
                'value' => 'semaphore',
            ],
            [
                'name'  => 'bar',
                'value' => 'flock',
            ],
        ],
    ],
```

**Possible Solution**

1) I've added a `beforeNormalization` rule that adds an `enabled` flag if it's missing:

```php
    ->beforeNormalization()
        ->ifTrue(function ($v) { return \is_array($v) && !isset($v['enabled']); })
        ->then(function ($v) { return $v + ['enabled' => true]; })
    ->end()
```

2) I've added a `beforeNormalization` rule for xml files since the `fixXmlConfig` and `useAttributeAsKey` options didn't work in this case:

```php
    ->beforeNormalization()
        ->ifTrue(function ($v) { return \is_array($v) && isset($v['resource']); })
        ->then(function ($v) {
            $resources = [];
            foreach ($v['resource'] as $resource) {
                $resources = array_merge_recursive(
                    $resources,
                    \is_array($resource) ? [$resource['name'] => $resource['value']] : ['default' => $resource]
                );
            }

            return [
                'enabled' => $v['enabled'],
                'resources' => $resources,
            ];
        })
    ->end()
```

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #31197
| License       | MIT
| Doc PR        | https://github.com/symfony/symfony-docs/pull/11465 & https://github.com/symfony/symfony-docs/pull/11466

This fixes #31197 and makes the lock configuration work with installations that are not full stack ones and configurations that use xml files.

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 1]
```diff
@@ -938,7 +959,6 @@ private function addLockSection(ArrayNodeDefinition $rootNode)
                         })
                     ->end()
                     ->addDefaultsIfNotSet()
-                    ->fixXmlConfig('resource')
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: won't this prevent using `<resource>` tags in xml configuration files?

**Comment by nicolas-grekas** [comment]
ping @jderusse

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php (hunk 1 above)
Comment (HypeMC) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: @nicolas-grekas As I mentioned in the issue:

The reason for this is cause `->fixXmlConfig('resource')` happenes after all the `beforeNormalization` rules, one of which is:

```php
    ->beforeNormalization()
        ->ifTrue(function ($v) { return \is_array($v) && !isset($v['resources']); })
        ->then(function ($v) {
            $e = $v['enabled'];
            unset($v['enabled']);

            return ['enabled' => $e, 'resources' => $v];
        })
    ->end()
```

so you get:

```php
    'resources' => [
        'resource' => [
            [
                'name'  => 'foo',
                'value' => 'semaphore',
            ],
            [
                'name'  => 'bar',
                'value' => 'flock',
            ],
        ],
    ],
```

Since I added a new `beforeNormalization` rule, `fixXmlConfig` is no longer required.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 2]
```diff
@@ -948,7 +968,7 @@ private function addLockSection(ArrayNodeDefinition $rootNode)
                             ->end()
                             ->beforeNormalization()
                                 ->ifTrue(function ($v) { return \is_array($v) && array_keys($v) === range(0, \count($v) - 1); })
-                                ->then(function ($v) { return ['default' => $v]; })
+                                ->then(function ($v) { return ['default' => 1 === \count($v) && isset($v[0]) && \is_array($v[0]) ? $v[0] : $v]; })
```
Comment (jderusse) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: what is the use case that this solves?

**Review by jderusse — COMMENTED** [review]
I'm not an expert on symfony configuration, but it's look like we've re-implemented `fixXmlConfig` + `useAttributeAsKey('name')` and got the feeling that business logic is dupliacted in "resource" and "resources".


Side appart that comment, I'm :+1: with the test suite: which is the expected behavior.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php (hunk 2 above)
Comment (HypeMC) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: @jderusse This covers the following test case:

```php
yield [null, ['enabled' => true, 'resources' => ['default' => [class_exists(SemaphoreStore::class) && SemaphoreStore::isSupported() ? 'semaphore' : 'flock']]]];
```

In other words if someone did something like:

```php
    $container->loadFromExtension('framework', [
        'lock' => [
            'enabled' => true,
            ['redis://r1.docker', 'redis://r2.docker'],
        ],
    ]);
```

Comment (HypeMC) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: @jderusse Copied the wrong test case, fixed it now.

**Comment by HypeMC** [comment]
@jderusse Yep, I agree with you, this is pretty much a re-implementation of fixXmlConfig + useAttributeAsKey('name'), however because of the beforeNormalization rules that were here before, I haven't been able to find a better solution. If anyone has any ideas please, let me know. Regardless, the fact remains that currently xml configurations don't work at all.

**Review by Simperfit — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by stof** [comment]
I would rather add a check for the singular `resource` key in the existing normalization condition rather than reimplementing all other features.

**Comment by HypeMC** [comment]
@stof Tried your approach & you were right, the end result is now a bit cleaner https://github.com/HypeMC/symfony/commit/662d394c34b2575f9f33802f9bd56f1a292d67a4 . Not sure whether to update this PR since it's already approved or to open a new one.

**Comment by nicolas-grekas** [comment]
Please update!

**Comment by HypeMC** [comment]
@nicolas-grekas Done.

**Review by javiereguiluz — APPROVED** [review]

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 3]
```diff
@@ -929,7 +929,11 @@ private function addLockSection(ArrayNodeDefinition $rootNode)
                         ->ifString()->then(function ($v) { return ['enabled' => true, 'resources' => $v]; })
                     ->end()
                     ->beforeNormalization()
-                        ->ifTrue(function ($v) { return \is_array($v) && !isset($v['resources']); })
+                        ->ifTrue(function ($v) { return \is_array($v) && !isset($v['enabled']); })
+                        ->then(function ($v) { return $v + ['enabled' => true]; })
+                    ->end()
+                    ->beforeNormalization()
+                        ->ifTrue(function ($v) { return \is_array($v) && !isset($v['resources']) && !isset($v['resource']); })
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: ` && !isset($v['resources'])` is duplicated right?

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: oh no, extra `s`...

**Comment by nicolas-grekas** [comment]
Thank you @HypeMC.
