### PR TITLE
[PropertyInfo] Add support for property hook settable types

### LINKED ISSUE #61163: [PropertyInfo] In PHP 8.4, an expanded setter type is ignored when determining property type.
### Symfony version(s) affected

7.3.1

### Description

I'm in the process of migrating my codebase from using getter/setter methods to using property hooks as it greatly improves the conciseness of my code. In some cases, I have properties that are quite a bit more permissive in what they accept from setters than what their getters return. Historically, PropertyInfo extractors like `ReflectionExtractor` look for mutators first, and then return their types preferentially over those of getters or the property itself; this has the side effect of making denormalization target the (more permissive) setter's types.

Currently, `ReflectionExtractor` doesn't appear to look at the new `ReflectionProperty::getSettableType` type at all. This means that the same code written with property hooks instead of getters/setters yields different type results, which may affect downstream code in unexpected ways.

### How to reproduce

Without property hooks:

```php
<?php
class Foo {
  private string $bar;

  public function getBar(): string {
    return $this->bar;
  }

  public function setBar(string|null $value): void {
    $this->bar = $value ?? 'Some Default';
  }
}

$reflectionExtractor = new Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor();
var_dump($reflectionExtractor->getType(Foo::class, 'bar'));
```

Yields a `NullableType` accepting both string and null.

With property hooks:

```php
<?php
class Foo {
  public string $bar {
    set (string|null $value) => $value ?? 'Some Default';
  }
}

$reflectionExtractor = new Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor();
var_dump($reflectionExtractor->getType(Foo::class, 'bar'));
```

Yields a `BuiltinType` of string with no nullable, as the setter hook is never checked.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #61163
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php [hunk 1]
```diff
@@ -171,6 +171,14 @@ public function getType(string $class, string $property, array $context = []): ?
             }
         }
 
+        try {
+            $reflectionProperty = (new \ReflectionClass($class))->getProperty($property);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php]: can't we create only one reflector? this method is already creating some

**Review by nicolas-grekas — COMMENTED** [review]
see failure on PHP 8.4

**Review by mtarld — APPROVED** [review]

**Comment by alexandre-daubois** [comment]
8.4 is green now 👍

**Comment by nicolas-grekas** [comment]
Thank you @alexandre-daubois.
