### PR TITLE
[Serializer] Fix normalization relying on allowed attributes only

### LINKED ISSUE #52744: [Sf 6.4 RC2] Serialization problem
### Symfony version(s) affected

6.4 RC2

### Description

Hello, I have an API Platform route which returns a collection : 

```
[
  {
    "id": 2,
    "type": "snippet",
    "name": "Test if a Doctrine entity is already persisted in the database",
    "datePublished": "2018-09-11T00:00:00+02:00",
    "dateModified": "2018-09-23T00:00:00+02:00",
    "author": "COil"
  },
```

It works well with Symfony 6.4 RC1, but with RC2 it returns an empty list : 

```
[[],[],[],[],[],[],[],[],[],[]]
```

It comes from the serializer component, I get the bug when only updating this component : 

```
composer up symfony/serializer                           ✔   39s  ⬢ 18.17.0   8.2.12  19:26:00
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "6.4.*"
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading symfony/serializer (v6.4.0-RC1 => v6.4.0-RC2)
```

### How to reproduce

up / down

### Possible Solution

serializer component

### Additional Context

* PHP 8.2
* Symfony 6.4 RC2
* API Patform 3.1.7

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #52744
| License       | MIT

### CODE REVIEW

**Review by chalasr — APPROVED** [review]

**Review by soyuka — APPROVED** [review]

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php [hunk 1]
```diff
@@ -458,9 +458,39 @@ public function testNormalizeEmptyObject()
...
+        $normalizer = new ObjectNormalizer($classMetadataFactory);
 
-        $this->assertSame(['foo' => 'foo'], $serializer->normalize(new ObjectDummyWithIgnoreAnnotationAndPrivateProperty()));
+        $this->assertSame(['foo' => 'foo'], $normalizer->normalize(new ObjectDummyWithIgnoreAnnotationAndPrivateProperty()));
+    }
+
+    public function testNormalizeBasedOnAllowedAttributes()
+    {
+        $normalizer = new class extends AbstractObjectNormalizer {
+            protected function getAllowedAttributes($classOrObject, array $context, bool $attributesAsString = false): array|false
```
Comment (xabbuh) [inline src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]:
```suggestion
            protected function getAllowedAttributes($classOrObject, array $context, bool $attributesAsString = false)
```

**Review by xabbuh — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php (hunk 1 above)
Comment (mtarld) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: Indeed, nice catch thanks!

**Comment by nicolas-grekas** [comment]
Thank you @mtarld.
