### PR TITLE
[Config][Routing] Fix exclude option being ignored for non-glob and PSR-4 resources

### LINKED ISSUE #39588: [Routing] "exclude" option ignored when "resource" doesn't end with "*?{["
**Symfony version(s) affected**: 4.4.*

**Description**  

As described in [Routing docs (v4.4)](https://symfony.com/doc/4.4/routing.html#route-groups-and-prefixes), adding the `exclude` option should be possible when defining routes as annotations.
But, looking at https://github.com/symfony/config/blob/4.4/Loader/FileLoader.php#L81, it seems that `exclude` option is handled only when `resource` options ends with `*?{[`

To note:
- I encountered this (to be confirmed) bug during development, I didn't run many tests
- code in branch [FileLoader.php v5.*](https://github.com/symfony/config/blob/5.x/Loader/FileLoader.php#L85) has changed, so I don't know if the bug still exists in `5.*`

**How to reproduce**  
Very simple routes configuration:
```
# config/routes/annotations.yaml
app:
    resource: '../../src/Controller/'
    type: annotation
    exclude: '../../src/Controller/ExcludedController.php'
```

### LINKED ISSUE #54212: All resource exclude paths are completely ignored
### Symfony version(s) affected

6.4.3

### Description

Given the example in [the documentation](https://symfony.com/doc/current/routing.html#route-groups-and-prefixes):

```yaml
# config/routes/attributes.yaml
controllers:
    resource: '../../src/Controller/'
    type: attribute
    # this is added to the beginning of all imported route URLs
    prefix: '/blog'
    # this is added to the beginning of all imported route names
    name_prefix: 'blog_'
    # these requirements are added to all imported routes
    requirements:
        _locale: 'en|es|fr'

    # An imported route with an empty URL will become "/blog/"
    # Uncomment this option to make that URL "/blog" instead
    # trailing_slash_on_root: false

    # you can optionally exclude some files/subdirectories when loading attributes
    # (the value must be a string or an array of PHP glob patterns)
    # exclude: '../../src/Controller/{Debug*Controller.php}'
```

If one were to actually uncomment the `exclude` line, it would have no effect whatsoever.

### How to reproduce

Uncomment the exclude line.

```yaml
# config/routes/attributes.yaml
controllers:
    resource: '../../src/Controller/'
    type: attribute
    # this is added to the beginning of all imported route URLs
    prefix: '/blog'
    # this is added to the beginning of all imported route names
    name_prefix: 'blog_'
    # these requirements are added to all imported routes
    requirements:
        _locale: 'en|es|fr'

    # An imported route with an empty URL will become "/blog/"
    # Uncomment this option to make that URL "/blog" instead
    # trailing_slash_on_root: false

    # you can optionally exclude some files/subdirectories when loading attributes
    # (the value must be a string or an array of PHP glob patterns)
    exclude: '../../src/Controller/{Debug*Controller.php}'
```

### Possible Solution

This appears to be because of [this line](https://github.com/symfony/symfony/blob/5dbc82d477c684f69803044e282f1b54e368d10d/src/Symfony/Component/Config/Loader/FileLoader.php#L75), and more specifically, this condition:

```php
\strlen($resource) !== ($i = strcspn($resource, '*?{['))
```

This seems to imply that if the resource itself is not a glob then all exclusion processing will be dropped. This is not documented anywhere nor does it make any particular sense to me.

### Additional Context

Relates to #39588.

### PR DESCRIPTION
**Pull request by NeilPeyssard**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54212, fix #39588
| License       | MIT

Hello,

In the [routing configuration](https://symfony.com/doc/5.x/routing.html#route-groups-and-prefixes), the `exclude` parameter is ignored if the the `resource` is not a path which can be used by the `glob` function. This PR is a starting point to work on this issue.

For example, if I have these controllers:

* `src/Controller/DebugController`
* `src/Controller/DebugFooController`
* `src/Controller/HelloController`

And the following route configuration:

```yaml
# config/routes/annotations.yaml
controllers:
    resource: '../../src/Controller/'
    type: annotation
    exclude: '../../src/Controller/{Debug*Controller.php}'
```

I expect to only see routes in `HelloController` active, but actually routes in `DebugController` and `DebugFooController` are also imported.

In this PR, I decided to transform all resource paths to a path which can be used by the glob function, only if there is an exclude parameter in the configuration. Not really sure if it's the good way to approach it, so do not hesitate to challenge it.

### CODE REVIEW

**Comment by xabbuh** [comment]
Will this also fix #39588?

**Comment by NeilPeyssard** [comment]
> Will this also fix #39588?

Yes it will !

To describe more in depth the behavior of this PR, let's take these controllers

* `src/Controller/Foo/BarController`
* `src/Controller/DebugController`
* `src/Controller/DebugFooController`
* `src/Controller/HelloController`

The following configurations will exclude `DebugController` and `DebugFooController`

```yaml
# config/routes/annotations.yaml

controllers:
    resource: '../../src/Controller/'
    type: annotation
    exclude: '../../src/Controller/{Debug*Controller.php}'

# or

controllers:
    resource: '../../src/Controller/**/*'
    type: annotation
    exclude: '../../src/Controller/{Debug*Controller.php}'
```

And the following configuration will exclude `DebugController`, `DebugFooController` and `Foo\BarController`:

```yaml
# config/routes/annotations.yaml
controllers:
    resource: '../../src/Controller/*'
    type: annotation
    exclude: '../../src/Controller/{Debug*Controller.php}'
```

File: src/Symfony/Component/Config/Loader/FileLoader.php [hunk 1]
```diff
@@ -72,16 +72,24 @@ public function getLocator()
...
     {
-        if (\is_string($resource) && \strlen($resource) !== ($i = strcspn($resource, '*?{[')) && !str_contains($resource, "\n")) {
-            $excluded = [];
-            foreach ((array) $exclude as $pattern) {
-                foreach ($this->glob($pattern, true, $_, false, true) as $path => $info) {
-                    // normalize Windows slashes and remove trailing slashes
-                    $excluded[rtrim(str_replace('\\', '/', $path), '/')] = true;
-                }
+        $excluded = [];
+        $isGlobPattern = \strlen($resource) !== strcspn($resource, '*?{[');
```
Comment (smnandre) [inline src/Symfony/Component/Config/Loader/FileLoader.php]: Will throw if $resource is not a string

Comment (NeilPeyssard) [reply src/Symfony/Component/Config/Loader/FileLoader.php]: > Will throw if $resource is not a string

Yes, something was missing here... I added a condition to apply the exclude only if `resource` is a string, and is not an existing class FQCN.

**Comment by NeilPeyssard** [comment]
Hello,

Unfortunately, I realized the following exclude condition will not work in version 6.4:

```yaml
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    exclude: '../src/Controller/{Debug*Controller.php}'
    type: attribute
```

This declaration will be handled by the `Symfony\Component\Routing\Loader\Psr4DirectoryLoader`, which hasn't access to the exclude parameter.

After digging a little deeper, I have the feeling there is a bad design here. In an ideal world each loader will have access to this exclude parameter, and deal with it to load or not their routes. But adding such a big change will involve some BC break...

What do you think guys ?

**Review by nicolas-grekas — APPROVED** [review]
I rebased and completed the PR

**Comment by nicolas-grekas** [comment]
Thank you @NeilPeyssard.
