### PR TITLE
[Form] validate subforms in all validation groups

### LINKED ISSUE #36852: [Validator] GroupSequence stopping at first group, never using the second
**Symfony version(s) affected**: v3.4.40

**Description**  

I'm using Symfony v3.4.37 and tried to upgrade to v3.4.40, but it looks like the GroupSequence validation_groups is not working as expected anymore.

**How to reproduce**  

Here is a simple test to reproduce:

```php
<?php

namespace Tests\AppBundle\Controller;

use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\GroupSequence;
use Symfony\Component\Validator\Constraints\Length;

class GroupSequenceTest extends WebTestCase
{
    public function testWithoutSequence()
    {
        parent::createClient();

        $formBuilder = self::$kernel->getContainer()->get('form.factory')->createBuilder(FormType::class, [], [
            'csrf_protection' => false,
            'validation_groups' => ['First', 'Second']
        ]);

        /** @var FormInterface $form */
        $form = $formBuilder
            ->add('foobar', EmailType::class, [
                'constraints' => [
                    new Email([
                        'strict' => true,
                        'groups' => ['First'],
                    ]),
                    new Length([
                        'groups' => ['Second'],
                        'max' => 3
                    ]),
                ],
            ])
            ->getForm();

        $form->submit(['foobar' => 'test@example.org']);

        $this->assertFalse($form->isValid());
    }

    public function testWithGroupSequence()
    {
        parent::createClient();

        $formBuilder = self::$kernel->getContainer()->get('form.factory')->createBuilder(FormType::class, [], [
            'csrf_protection' => false,
            'validation_groups' => new GroupSequence(['First', 'Second'])
        ]);

        /** @var FormInterface $form */
        $form = $formBuilder
            ->add('foobar', EmailType::class, [
                'constraints' => [
                    new Email([
                        'strict' => true,
                        'groups' => ['First'],
                    ]),
                    new Length([
                        'groups' => ['Second'],
                        'max' => 3
                    ]),
                ],
            ])
            ->getForm();

        $form->submit(['foobar' => 'test@example.org']);

        $this->assertFalse($form->isValid());
    }
}
```

The first one use two groups, the form is not valid which is what we expect.

The second test use the sames groups in a GroupSequence, this is where I see a difference between Symfony version:

- on Symfony v3.4.37 the test is green, the two validators are checked
- on Symfony v3.4.40 the test is red, only the first validator is checked

**Possible Solution**  

None.

**Additional context**  

Tested on (yes, I know :grimacing:):

```
PHP 7.0.33 (cli) (built: Dec  7 2018 16:18:01) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.28.4~linux-musl-x64-non_zts70, https://blackfire.io, by Blackfire
```

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36852
| License       | MIT
| Doc PR        |

### CODE REVIEW

File: src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php [hunk 1]
```diff
@@ -86,7 +86,8 @@ public function validate($form, Constraint $formConstraint)
                             // sequence recursively, thus some fields could fail
                             // in different steps without breaking early enough
                             $this->resolvedGroups[$field] = (array) $group;
-                            $validator->atPath(sprintf($fieldPropertyPath, $field->getPropertyPath()))->validate($field, $formConstraint);
+                            $fieldFormConstraint = new Form();
```
Comment (xabbuh) [inline src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php:89]: This is needed for now to prevent hash collisions (see also #36415).

File: src/Symfony/Component/Form/Extension/Validator/ValidatorExtension.php [hunk 2]
```diff
@@ -37,7 +38,7 @@ public function __construct(ValidatorInterface $validator)
 
         /* @var $metadata ClassMetadata */
         $metadata->addConstraint(new Form());
-        $metadata->addPropertyConstraint('children', new Valid());
+        $metadata->traversalStrategy = TraversalStrategy::NONE;
```
Comment (xabbuh) [inline src/Symfony/Component/Form/Extension/Validator/ValidatorExtension.php:41]: traversal happens explicitly inside the `FormValidator`

**Comment by xabbuh** [comment]
This is ready to be reviewed.

File: src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php [hunk 3]
```diff
@@ -125,6 +127,19 @@ public function validate($form, Constraint $formConstraint)
...
+                        $this->resolvedGroups[$field] = $groups;
+                        $fieldFormConstraint = new Form();
+                        $validator->atPath(sprintf($fieldPropertyPath, $field->getPropertyPath()))->validate($field, $fieldFormConstraint);
+                    }
+                }
+            }
+
+            if ($hasChildren && $form->isRoot()) {
+                // destroy storage to avoid memory leaks
+                $this->resolvedGroups = null;
```
Comment (stof) [inline src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php:142]: maybe we should create a new SplObjectStorage rather than `null` to avoid the issues about illegal offsets ?

File: src/Symfony/Component/Form/Extension/Validator/ValidatorExtension.php [hunk 4]
```diff
@@ -37,7 +37,7 @@ public function __construct(ValidatorInterface $validator)
...
```
Comment (stof) [inline src/Symfony/Component/Form/Extension/Validator/ValidatorExtension.php:40]: Based on the comment preceding this, don't we need to do a similar change in the XML file ?

Comment (xabbuh) [reply src/Symfony/Component/Form/Extension/Validator/ValidatorExtension.php:40]: Indeed, that missing sync was also the root cause for the issue reported by @lyrixx in https://github.com/symfony/symfony/issues/36852#issuecomment-634635009.

File: src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php (hunk 3 above)
Comment (xabbuh) [reply src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php]: agreed, it doesn't hurt but can potentially prevent some PHP errors

**Comment by lyrixx** [comment]
Hello,

I ran our full test suite and I confirm this patch fixed everything. It's all :green_heart: 

Thanks @xabbuh and @stof

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Comment by bendavies** [comment]
This breaks property mapping in some way.
Investigating.

**Comment by xabbuh** [comment]
Maybe the same as #37027?

**Comment by bendavies** [comment]
@xabbuh yes looks like it. also https://github.com/symfony/symfony/issues/37025
