### PR TITLE
[Stopwatch] Fixed a bug in StopwatchEvent::getStartTime

### LINKED ISSUE #34088: [Stopwatch] StopwatchEvent->getStartTime() is incorrect
**Symfony version(s) affected**: ^4.3

**How to reproduce**  
```php
$event = new \Symfony\Component\Stopwatch\StopwatchEvent(0, null, true);

$event->start();
usleep(100000);
var_dump($event->getStartTime());
$event->stop();
var_dump($event->getStartTime());
```

Output:
```
int(0); // But should not be 0
float(1571838784644.8)
```

**Possible solutions**

Bug lives here https://github.com/symfony/stopwatch/blob/9e2c41817c3e3d506e5db1d052cbfbbc6f685199/StopwatchEvent.php#L157

```php
     public function getStartTime()
    {
        return isset($this->periods[0]) ? $this->periods[0]->getStartTime() : 0;
    }
```

Should be
```php
    public function getStartTime()
    {
        if (isset($this->periods[0])) {
            return $this->periods[0]->getStartTime();
        }
        if (\count($this->started)) {
            return $this->started[0];
        }
        return 0;
    }
```

### PR DESCRIPTION
**Pull request by TimoBakx**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34088
| License       | MIT
| Doc PR        | N/A

When using a `StopwatchEvent` with an `$origin` that's smaller than the first start time, calling `getStartTime()` before ending the event will give `0` instead of the correct number.

The proposed fix in #34088 fixes this.

### CODE REVIEW

File: src/Symfony/Component/Stopwatch/StopwatchEvent.php [hunk 1]
```diff
@@ -154,7 +154,15 @@ public function getPeriods()
      */
     public function getStartTime()
     {
-        return isset($this->periods[0]) ? $this->periods[0]->getStartTime() : 0;
+        if (isset($this->periods[0])) {
+            return $this->periods[0]->getStartTime();
+        }
+
+        if (\count($this->started)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Stopwatch/StopwatchEvent.php]: `if ($this->started) {`

Comment (TimoBakx) [reply src/Symfony/Component/Stopwatch/StopwatchEvent.php]: I've updated the code.

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @TimoBakx.
