### PR TITLE
[Mailer] Restore X-Transport after failure

### LINKED ISSUE #44741: [Mail][Messenger] losing email's transport header on error
### Symfony version(s) affected

5.4

### Description

When an email is sent through the messenger using alternative mail transport and if this mail transport fails then modified email is pushed to the queue for the next try (without X-Transport header). The second try takes default mail transport whether you want it or not.

### How to reproduce

https://github.com/Nommyde/mailer-messenger-bug

run:

```
php bin/console app:send-email -vvv              # an email pushed to the queue
php bin/console mes:consume async --limit=1 -vvv # error on the second transport
php bin/console mes:consume async --limit=1 -vvv # success on the first transport
```

### Possible Solution

In this case I believe the method \Symfony\Component\Mailer\Transport\Transports::send should clone a message before modifying and sending it.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by zenas1210**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44741
| License       | MIT
| Doc PR        |

Restores X-Transport header for retries after failure.

### CODE REVIEW

File: src/Symfony/Component/Mailer/Tests/Transport/TransportsTest.php [hunk 1]
```diff
@@ -64,4 +65,28 @@ public function testTransportDoesNotExist()
...
+
+        $headers = (new Headers())->addTextHeader('X-Transport', 'foo');
+        $email = new Message($headers, new TextPart('...'));
+
+        $this->expectExceptionObject($exception);
+
+        try {
+            $transport->send($email);
+        } finally {
+            $this->assertEquals('foo', $email->getHeaders()->getHeaderBody('X-Transport'));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mailer/Tests/Transport/TransportsTest.php]: assertSame

File: src/Symfony/Component/Mailer/Tests/Transport/TransportsTest.php [hunk 2]
```diff
@@ -64,4 +65,28 @@ public function testTransportDoesNotExist()
         $this->expectExceptionMessage('The "foobar" transport does not exist (available transports: "foo", "bar").');
         $transport->send($email);
     }
+
+    public function testTransportRestoredAfterFailure()
+    {
+        $exception = new Exception();
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mailer/Tests/Transport/TransportsTest.php]: `\Exception` (and the use should be removed)

File: src/Symfony/Component/Mailer/Transport/Transports.php [hunk 3]
```diff
@@ -59,7 +60,13 @@ public function send(RawMessage $message, Envelope $envelope = null): ?SentMessa
             throw new InvalidArgumentException(sprintf('The "%s" transport does not exist (available transports: "%s").', $transport, implode('", "', array_keys($this->transports))));
         }
 
-        return $this->transports[$transport]->send($message, $envelope);
+        try {
+            return $this->transports[$transport]->send($message, $envelope);
+        } catch (Throwable $throwable) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mailer/Transport/Transports.php]: `\Throwable` (and the use should be removed)

**Review by nicolas-grekas — COMMENTED** [review]
Thanks for the PR.
Here are some minor comments.

**Comment by zenas1210** [comment]
Done.

File: src/Symfony/Component/Mailer/Transport/Transports.php [hunk 4]
```diff
@@ -59,7 +59,13 @@ public function send(RawMessage $message, Envelope $envelope = null): ?SentMessa
             throw new InvalidArgumentException(sprintf('The "%s" transport does not exist (available transports: "%s").', $transport, implode('", "', array_keys($this->transports))));
         }
 
-        return $this->transports[$transport]->send($message, $envelope);
+        try {
+            return $this->transports[$transport]->send($message, $envelope);
+        } catch (\Throwable $throwable) {
+            $headers->addTextHeader('X-Transport', $transport);
+
+            throw $throwable;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mailer/Transport/Transports.php]: the variable should be named `$e`

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Mailer/Transport/Transports.php (hunk 4 above)
Comment (zenas1210) [reply src/Symfony/Component/Mailer/Transport/Transports.php]: done

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @zenas1210.
