### PR TITLE
[Messenger][Redis] Adding support for lazy connect

### LINKED ISSUE #38558: [Messenger] Automatic schema updates with redis transport requires redis to run during database migrations
**Symfony version(s) affected**: 5.1.7

**Description**  
The event subscriber for [Automatic schema updates](https://symfony.com/blog/new-in-symfony-5-1-automatic-schema-updates) will loop over the messenger transports and check if they are Doctrine transports, if yes then it will run the schema update, great feature! However, we're having some issues with the Redis transport.

Locally, we're using redis as messenger transport. The automatic schema update subscriber instantiates all messenger transports to check if they're a Doctrine transport or not, the `Symfony\Component\Messenger\Bridge\Redis\Transport\Connection` is attempting to connect to redis in its constructor which breaks our migrations if redis isn't running.

The way around it, is to make sure that redis is running while trying to migrate the database, but I create this issue because IMHO it feels "wrong" that this messenger transport not related to the database breaks the migrations.

**How to reproduce**  
- Setup messenger transport to use redis
- DO NOT start redis service
- Run database migrations

**Possible Solution**  
Do not try to connect to redis in the `Connection` constructor but only when trying to interact with redis.

### PR DESCRIPTION
**Pull request by Nyholm**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #38558
| License       | MIT
| Doc PR        | Should be added

With inspiration from the CacheComponent. This PR makes it possible to make the connection to Redis only when you first use it.

### CODE REVIEW

**Comment by natepage** [comment]
@Nyholm Thank you for the quick reply + patch!

```diff
- MESSENGER_NOTIFICATIONS_TRANSPORT_DSN=redis://redis:6379/messages
+ MESSENGER_NOTIFICATIONS_TRANSPORT_DSN=redis://redis:6379/messages?lazy=1
```

Working like a charm!

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php [hunk 1]
```diff
@@ -61,23 +62,42 @@ public function __construct(array $configuration, array $connectionCredentials =
...
+        $serializer = $redisOptions['serializer'] ?? \Redis::SERIALIZER_PHP;
+        $dbIndex = $configuration['dbindex'] ?? self::DEFAULT_OPTIONS['dbindex'];
         $auth = $connectionCredentials['auth'] ?? null;
         if ('' === $auth) {
             $auth = null;
         }
 
-        if (null !== $auth && !$this->connection->auth($auth)) {
-            throw new InvalidArgumentException('Redis connection failed: '.$this->connection->getLastError());
+        $initializer = function ($redis) use ($host, $port, $auth, $serializer, $dbIndex) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: the closure should be static, to save a circular ref

**Review by nicolas-grekas — APPROVED** [review]
(with one comment to fix before merging)

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php (hunk 1 above)
Comment (Nyholm) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: Sure. Fixed!

**Review by chalasr — APPROVED** [review]
👍

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Nyholm.

**Comment by Nyholm** [comment]
Thank you for the reviews, tests and merge.
