### PR TITLE
[HttpKernel] Fix regression where Store does not return response body correctly

### LINKED ISSUE #37174: [HttpKernel] HttpCache\Store does not return response body correctly
**Symfony version(s) affected**: 4.4.* / 5.0.* / 5.1.* (probably others)

**Description**  
While using `Symfony\Component\HttpClient\CachingHttpClient` with a `Symfony\Component\HttpKernel\HttpCache\Store` we found that responses returned from the cache did not yield the correct response bodies.

I checked the source and found the following snippet:

https://github.com/symfony/symfony/blob/749380a399a792f140ca3b8cf1490c5fcc559b72/src/Symfony/Component/HttpKernel/HttpCache/Store.php#L153-L155

This seems rather odd to me because after executing `$body = $this->getPath($headers['x-content-digest'][0])` `$body` contains the path to the cached response body file and not the cached response body itself. But `$body` (containing the path and not the response body) is then fed into `Symfony\Component\HttpKernel\HttpCache\Store::restoreResponse()` where it's used to populate the `Symfony\Component\HttpFoundation\Response` content. So the returned response contains the path to the cached response body file in its body instead of the actual response content.

**How to reproduce**  
Just use a  `Symfony\Component\HttpClient\CachingHttpClient` configured with a `Symfony\Component\HttpKernel\HttpCache\Store` and fetch the same HTTP resource twice.

**Possible Solution**  
I might be wrong, but to me it looks like there's a `file_get_contents()` missing.

### PR DESCRIPTION
**Pull request by mpdude**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37174
| License       | MIT
| Doc PR        | 

Since #36833, the `Store` no longer uses or trusts the `X-Content-Digest` header present on a response, since that may come (in the case of using `CachingHttpClient`) from upstream HTTP sources. Instead, the `X-Content-Digest` is re-computed every time a response is written by the `Store`.

Additionally, the `Store` is implemented in a way that when restoring responses, it does _not_ actually load the response body, but just keeps the file path to the content on disk in another internal header called `X-Body-File`. It is up to others (`HttpCache`, for example) to actually load the content from there. For reasons I could not determine, the file path is also set as the response body.

When the `HttpCache` performs revalidations, it may happen that it wants the `Store` to persist a previously restored response. In that case, the `Store` fails to honor its own `X-Body-File` header. Instead, it would compute (since #36833) the `X-Content-Digest`, which now is a hash of the cache file path. 

So, we end up with a response that still carries `X-Body-File` for the original, correct response. Since the `HttpCache` honors this value, we don't immediately notice that. But inside the `Store`, the request is now associated with the _new_ (bogus) content entry. 

It takes another round of looking up the content in the `Store` to now get a response where the `X-Body-File` _also_ points to the wrong content entry. 

Although I feel a bit uncomfortable with trusting headers that seemingly need to be evaluated in different classes and may come from elsewhere, my suggestion is to skip the write inside `Store` if `X-Body-File` and `X-Content-Digest` are both present and consistent with each other. 

Additionally, a `file_exists` check could be added to provide additional assertions, at the cost of accessing the filesystem.

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/HttpKernel/Tests/HttpCache/StoreTest.php [hunk 1]
```diff
@@ -118,6 +118,39 @@ public function testWritesResponseEvenIfXContentDigestIsPresent()
...
     }
 
+    public function testWritingARestoredResponseDoesNotCorruptCache()
+    {
+        /*
+         * This covers the regression reported in https://github.com/symfony/symfony/issues/37174.
+         *
+         * A restored response does *not* load the body, but only keep the file path in a special X-Body-File
+         * header. For reasons (?), the file path was also used as the restored response body.
+         * It would be up to others (HttpCache...?) to hohor this header and actually load the response content
```
Comment (fabpot) [inline src/Symfony/Component/HttpKernel/Tests/HttpCache/StoreTest.php:128]: honor

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @mpdude.

File: src/Symfony/Component/HttpKernel/HttpCache/Store.php [hunk 2]
```diff
@@ -477,19 +490,19 @@ private function persistResponse(Response $response)
      * Restores a Response from the HTTP headers and body.
      *
      * @param array  $headers An array of HTTP headers for the Response
-     * @param string $body    The Response body
+     * @param string $path    Path to the Response body
```
Comment (GrahamCampbell) [inline src/Symfony/Component/HttpKernel/HttpCache/Store.php:493]: string|null
