### PR TITLE
[FrameworkBundle] Make `ConfigDebugCommand` use its container to resolve env vars

### LINKED ISSUE #62554: Unable to obtain symfony vault secret DATABASE_PASSWORD for use in doctrine.yaml
### Symfony version(s) affected

6.4.27

### Description

Currently I have something like:

`DATABASE_URL="mysql://user:password@host:3306/databaseName?serverVersion=8.0.30&charset=utf8mb4"`

the doctrine yaml documents say that the `url` key overrides the others including password

Through the symfony env processor I thought it would be possible to extract out each of the parameters from the url, then ensuring that the password from the url can overridden by the env variable that can then go into the vault:

```yaml
# start of url parameters
#driver: mapping to the url scheme has issues with differences in naming pdo_mysql vs mysql
dbname: '%env(string:key:path:url:resolve:DATABASE_URL)%'
host: '%env(string:key:host:url:resolve:DATABASE_URL)%'
port: '%env(int:key:port:url:resolve:DATABASE_URL)%'
user: '%env(string:key:user:url:resolve:DATABASE_URL)%'
# use the env variable (hence could be a vault secret) in preference to the value in the url
# neither value works
password: '%env(DATABASE_PASSWORD)%'
# password: '%env(string:default:password_from_url:password_from_vault)%'
charset: '%env(string:key:charset:query_string:resolve:DATABASE_URL)%'
server_version: '%env(string:key:serverVersion:query_string:resolve:DATABASE_URL)%'
# end of url parameters
# replacing the current doctrine.yaml url: '%env(DATABASE_URL)%'
```

testing the above does work when DATABASE_PASSWORD is in an env file (e.g. `bin/console secrets:set DATABASE_PASSWORD --local`), from running the command:

`bin/console debug:config doctrine --resolve-env`, 

however when placing DATABASE_PASSWORD into the vault (from running `bin/console secrets:set DATABASE_PASSWORD` and removing from the env.local) I am getting a   `Environment variable not found: "DATABASE_PASSWORD".   error.`

despite the fact `bin/console secrets:list --reveal` shows the secret and the symfony docs say secrets can be used in config via the `%env(DATABASE_PASSWORD)%` notation. literally using that env variable as the example.

I've tried across various --env=dev|test|staging to rule out some dotenv quirk.

### How to reproduce

* new symfony project with doctrine bundle
* replace in config/doctrine.yaml the .yaml given above
* generate secret public/private key
* set secret with `bin/console secrets:set DATABASE_PASSWORD`
* run bin/console debug:config doctrine --resolve-env to see how the env processor and secrets have resolved 

### Possible Solution

My guess is the resolution order of env variables and that the secrets are being added too late? I'd tried doing something like the default config has for ` env(DATABASE_URL): ''` but for DATABASE_PASSWORD however that just resulted in doctrine defaulting to an empty string password instead of using the secret from the vault

### Additional Context

```
bin/console about
 -------------------- --------------------------------- 
  Symfony                                               
 -------------------- --------------------------------- 
  Version              6.4.27                           
  Long-Term Support    Yes                              
  End of maintenance   11/2026 (in +367 days)           
  End of life          11/2027 (in +732 days)           
 -------------------- --------------------------------- 
  Kernel                                                
 -------------------- --------------------------------- 
  Type                 App\Kernel                       
  Environment          staging                          
  Debug                true                             
  Charset              UTF-8                            
  Cache directory      ./var/cache/staging (12.0 MiB)   
  Build directory      ./var/cache/staging (12.0 MiB)   
  Log directory        ./var/log (355.8 MiB)            
 -------------------- --------------------------------- 
  PHP                                                   
 -------------------- --------------------------------- 
  Version              8.3.25                           
  Architecture         64 bits                          
  Intl locale          en_US                            
  Timezone             UTC (2025-11-28T16:11:20+00:00)  
  OPcache              true                             
  APCu                 false                            
  Xdebug               false                            
 -------------------- --------------------------------- 
```

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62554
| License       | MIT

The `ConfigDebugCommand` currently cannot use the `SodiumVault` to load env vars because its `$secretsDir` depends on one, so calling it with `--resolve-env-vars` fails if an env var is only present in the vault. I’m not sure if it’s for the same reason but compiling the container with `$resolveEnvPlaceholders` suffers from the same issue.

I didn’t find a way to fix this so this PR works around it by setting the new container’s env var processors as the command’s so that the vault (and anything that could be used to resolve env vars) is correctly initialized.

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php [hunk 1]
```diff
@@ -39,6 +40,12 @@
 #[AsCommand(name: 'debug:config', description: 'Dump the current configuration for an extension')]
 class ConfigDebugCommand extends AbstractConfigCommand
 {
+    public function __construct(
+        private ContainerInterface $envVarProcessors,
```
Comment (GromNaN) [inline src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: We can't add a required parameter in a bug fix version. You can make this parameter optional so that it's not a breaking change.

**Review by GromNaN — CHANGES_REQUESTED** [review]

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php (hunk 1 above)
Comment (MatTheCat) [reply src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: Done. That counts as a deprecation right?

Comment (GromNaN) [reply src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: The deprecation can come in 8.1.

**Comment by GromNaN** [comment]
Is there a way to test this fix?

**Comment by MatTheCat** [comment]
> Is there a way to test this fix?

Couldn’t figure out how; looks like the issue also impact functional tests :confused:

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @MatTheCat.

**Comment by MatTheCat** [comment]
Thanks for the test :pray:
