### PR TITLE
[Translations] Throw exception if xFileLoader dependencies don't exist.

### LINKED ISSUE #36658: [Translation] As a standalone component, XmlUtils::class not found when using XliffFileLoader
**Symfony version(s) affected**: All?

**Description**  
When using `symfony/translation` as a stand alone component, `XliffFileLoader::class` requires `Symfony\Component\Config\Util\XmlUtils::class`. As `symfony/config` is a `require-dev` dependency, the `XmlUtils` is not found unless you explicitly require `symfony/config`

**How to reproduce**  
```
// test.php

<?php

require __DIR__.'/vendor/autoload.php';

use \Symfony\Component\Translation\Loader\XliffFileLoader;

$loader = new XliffFileLoader();
$loader->load('file.xlf', 'en');
```
```
?> php test.php

Fatal error: Uncaught Error: Class 'Symfony\Component\Config\Util\XmlUtils' not found in /var/htdocs/vendor/symfony/translation/Loader/XliffFileLoader.php:54
```

**Possible Solution**  
Move the `"symfony/config": "^4.4|^5.0",` from `require-dev` to `require` in `composer.json`

**Additional context**  
While it's not your average use case to use translations as a standalone component - I ran into this when creating a CLI app to auto-magically create translation files for me using a 3rd party translation service.

I'm more than happy to submit a PR with the aforementioned solution. Thoughts?

### PR DESCRIPTION
**Pull request by jrushlow**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #36658
| License       | MIT
| Doc PR        |

`XliffFileLoader` & `QtFileLoader` both require `XmlUtils::class` from the `Config` component. This PR throws a friendly exception is the `Config` component does not exist.

Original idea by @xabbuh was to throw the exception from the __constructor. This PR throws the exception from the `load()` method to be consistent with the `YamlFileLoader::class`.  But that can easily be changed.

### CODE REVIEW

File: src/Symfony/Component/Translation/Loader/QtFileLoader.php [hunk 1]
```diff
@@ -29,6 +30,10 @@ class QtFileLoader implements LoaderInterface
      */
     public function load($resource, string $locale, string $domain = 'messages')
     {
+        if (!class_exists('Symfony\Component\Config\Util\XmlUtils')) {
```
Comment (xabbuh) [inline src/Symfony/Component/Translation/Loader/QtFileLoader.php:33]:
```php
if (!class_exists(XmlUtils::class)) {
    // ...
}
```

File: src/Symfony/Component/Translation/Loader/XliffFileLoader.php [hunk 2]
```diff
@@ -30,6 +31,10 @@ class XliffFileLoader implements LoaderInterface
      */
     public function load($resource, string $locale, string $domain = 'messages')
     {
+        if (!class_exists('Symfony\Component\Config\Util\XmlUtils')) {
```
Comment (xabbuh) [inline src/Symfony/Component/Translation/Loader/XliffFileLoader.php:34]: same here

**Comment by jrushlow** [comment]
@xabbuh should we fix the `XmlUtil::class` reference in:
https://github.com/symfony/symfony/blob/eebb3efa2cbe1d08283180ccd6edbe303bfd4918/src/Symfony/Component/Translation/Loader/YamlFileLoader.php#L35
in this PR for consistency?

File: src/Symfony/Component/Translation/Loader/QtFileLoader.php (hunk 1 above)
Comment (jrushlow) [reply src/Symfony/Component/Translation/Loader/QtFileLoader.php]: done

File: src/Symfony/Component/Translation/Loader/XliffFileLoader.php (hunk 2 above)
Comment (jrushlow) [reply src/Symfony/Component/Translation/Loader/XliffFileLoader.php]: done

**Review by javiereguiluz — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jrushlow.
