### PR TITLE
[FrameworkBundle] Deprecate container parameters router.request_context.scheme and .host

### LINKED ISSUE #53919: Configuring framework.router.default_uri has no impact on request context parameters
### Symfony version(s) affected

6.4

### Description

The `framework.router.default_uri` config is used to define the request context as fallback for the case that no HTTP request is available. But it does not affect the container params

- `router.request_context.base_url`
- `router.request_context.host`
- `router.request_context.scheme`

They still use the defaults, which are defined in the routing.php config file of the framework bundle.

This leads to inconsistency and confusion if a third party bundle relies on the container parameters instead of the request context service (for example at the Sulu CMS in [this](https://github.com/sulu/sulu/blob/e160828f94181a8eab539afba5ae7eca40dedba2/src/Sulu/Bundle/CoreBundle/Resources/config/webspace.xml#L44) file).

### How to reproduce

Define the `framework.router.default_uri` config for example with the value `https://example.com`. And then do 

     bin/console debug:container --parameters | grep request_context

in the console. You'll see that the host is still `localhost` and the scheme `http`.

### Possible Solution

I am not sure. Either the mentioned container params should be replaced by the values of the default_uri or they should be deprecated in favor of the request context service.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by stollr**
| Q             | A
| ------------- | ---
| Branch?       | 7.4 
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Issues        | Fix #53919
| License       | MIT

The `framework.router.default_uri` config is used to define the request context as fallback for the case that no HTTP request is available. But it does not affect the container params

- `router.request_context.base_url`
- `router.request_context.host`
- `router.request_context.scheme`

They still use the defaults, which are defined in the routing.php config file.

This leads to inconsistency and confusion if a third party bundle relies on the container parameters instead of the request context service.

This PR deprecates those container params like proposed in #53919.

### CODE REVIEW

**Comment by stof** [comment]
This is not marking the parameters as deprecated to warn places using them.

**Comment by stollr** [comment]
You mean that the `!isset($config['default_uri'])` should be removed from the condition? Or is there a better way?

**Comment by stof** [comment]
I mean actually deprecating the parameters: https://symfony.com/blog/new-in-symfony-6-3-dependency-injection-improvements#deprecating-container-parameters

**Comment by stollr** [comment]
Thanks for the hint. I have updated the patch.

**Comment by nicolas-grekas** [comment]
I wouldn't deprecate `router.request_context.base_url` (the others I would).
Instead, I'd fix it this way:

```diff
--- a/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
+++ b/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
@@ -1334,8 +1334,7 @@ class FrameworkExtension extends Extension
         $container->setParameter('request_listener.https_port', $config['https_port']);
 
         if (null !== $config['default_uri']) {
-            $container->getDefinition('router.request_context')
-                ->replaceArgument(0, $config['default_uri']);
+            $container->setParameter('router.request_context.base_url', $config['default_uri']);
         }
     }
```

**Comment by stollr** [comment]
Wouldn't this be a potential source of confusion? If a user sets `router.request_context.base_url` to "example.com", the `default_url` (maybe via an ENV variable) to something else and at the end, `base_url` will have another value than what he defined?

And what would be the advantage?

**Comment by nicolas-grekas** [comment]
The advantage is not breaking things (deprecating first but still) and allowing bundles to read the value also.
The confusion would be the responsibility of the app, not ours.

**Comment by stollr** [comment]
Historically the `router.request_context.base_url` was used to specify only the URL path (for example [here](https://stackoverflow.com/a/26219739/1119601) or in the older version of the [symfony doc](https://symfony.com/doc/4.x/routing.html#generating-urls-in-commands)).

Imho overwriting the base_url with the default_uri, which is always an absolute URI containing scheme and host, could lead to a hidden BC break.

**Comment by nicolas-grekas** [comment]
This was later improved to support full URI, see https://github.com/symfony/symfony/pull/36651
This also matches the fact that the config value is injected at the same position as the param, which means that today already, one can set `router.request_context.base_url` and basically configure the default_uri

**Comment by stollr** [comment]
Okay, I have applied your suggestion ;-)

**Review by nicolas-grekas — DISMISSED** [review]

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -1307,6 +1307,9 @@ private function registerRouterConfiguration(array $config, ContainerBuilder $co
 
         $loader->load('routing.php');
 
+        $container->deprecateParameter('router.request_context.scheme', 'symfony/framework-bundle', '7.4', 'Parameter "router.request_context.scheme" is deprecated, use "router.request_context.base_url" or the "framework.router.default_uri" config option instead.');
+        $container->deprecateParameter('router.request_context.host', 'symfony/framework-bundle', '7.4', 'Parameter "router.request_context.host" is deprecated, use "router.             request_context.base_url" or the "framework.router.default_uri" config option instead.');
```
Comment (stollr) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: @nicolas-grekas Looks like the whitespaces in the message were added by accident (line 1311).

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: oops, fixed thanks

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 2]
```diff
@@ -1334,8 +1337,7 @@ private function registerRouterConfiguration(array $config, ContainerBuilder $co
         $container->setParameter('request_listener.https_port', $config['https_port']);
 
         if (null !== $config['default_uri']) {
-            $container->getDefinition('router.request_context')
-                ->replaceArgument(0, $config['default_uri']);
+            $container->setParameter('router.request_context.base_url', $config['default_uri']);
```
Comment (OskarStark) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:1354]: What if the `router.request_context.base_url'` was also set with a different value? Shouldn't we only set it if `null`?

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:1354]: I don't think it makes sense to have these two diverge.

Comment (stollr) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:1354]: Then we'll end up with `base_url` being different from `default_url` leading to inconsistence when bundles use the container param instead of the RequestContext.

**Comment by nicolas-grekas** [comment]
After looking at the test failures, I realize `request_listener.http_port` and `request_listener.https_port` should likely also be deprecated, alongside with the corresponding config options.
I'm also not sure how to fix deprecations, since we of course have to still use these parameters for BC.
Any ideas?

Status: needs work

**Comment by stollr** [comment]
Where do we have to use these parameters and why can't `framework.router.default_uri` be used to fix the deprecations?

**Review by nicolas-grekas — APPROVED** [review]
I was wrong about `request_listener.http_port` and `request_listener.https_port`, they're for something else.
I rebased the PR on branch 8.1 and figured out a way to work around triggering the deprecations.

**Comment by nicolas-grekas** [comment]
Thank you @stollr.

**Comment by stollr** [comment]
@nicolas-grekas I have to thank you ;-)
