### PR TITLE
[String] bytesAt() and codePointsAt()

### LINKED ISSUE #33923: [String] Should UnicodeString return all code points for a given grapheme?
**Symfony version(s) affected**: 5.0

**Description**  
While documenting the new String component in https://github.com/symfony/symfony-docs/pull/12440 I found something which doesn't make sense to me.

A "grapheme cluster" is a series of one or more code points.

Then, why does our "grapheme string" return a single code point (the first one) instead of all of them for a given cluster?

**How to reproduce**  
Take for example the Hindi word "hello", which is `नमस्ते`.

```php
$bString = b('नमस्ते');

echo "Bytes: ";
for ($i = 0; $i < $bString->length(); $i++) {
    echo $bString->byteCode($i)." ";
}

$cString = $bString->toCodePointString();
echo "Code Points: ";
for ($i = 0; $i < $cString->length(); $i++) {
    echo $cString->codePoint($i)." ";
}

$uString = $bString->toUnicodeString();
echo "Grapheme Code Points: ";
for ($i = 0; $i < $uString->length(); $i++) {
    echo $uString->codePoint($i)." ";
}
```

The output is:

```
Bytes: 224 164 168 224 164 174 224 164 184 224 165 141 224 164 164 224 165 135

Code Points: 2344 2350 2360 2381 2340 2375

Grapheme Code Points: 2344 2350 2360 2340
```

However, I expected the output to be:

```
// ...

Grapheme Code Points: 2344 2350 [2360, 2381] [2340, 2375]
```

**Possible Solution**  
`UnicodeString` should not return `?int` but `?array` (the other classes should keep returning `?int`).

### PR DESCRIPTION
**Pull request by gharlan**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #33923
| License       | MIT
| Doc PR        | symfony/symfony-docs/pull/12440

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]

File: src/Symfony/Component/String/UnicodeString.php [hunk 1]
```diff
@@ -84,6 +84,16 @@ public function chunk(int $length = 1): array
         return $chunks;
     }
 
+    /**
+     * @return int[]|null
+     */
+    public function codePoints(int $offset = 0): ?array
```
Comment (nicolas-grekas) [inline src/Symfony/Component/String/UnicodeString.php]: What about moving this to AbstractUnicodeString? I'd rename it `codePointsAt` and make the argument mandatory: that might make it easier to discover what this is about.
Also, this should return the empty array instead of null when the offset is out of bound.

Comment (nicolas-grekas) [reply src/Symfony/Component/String/UnicodeString.php]: > For me it does not make sense to use this method in a CodePointString, since every offset is representing a single code point.

It does because it's at the abstract level: abstract means it should generic enough to cover the domain, which is what this would provide. Putting the method at the abstract level is way better than forcing one to rely on more specialized methods.

>  But I think then we should also rename codePoint to codePointAt for consistency.

I would remove codePointAt entirely

> I don't agree. Imo it is better to distinguish 'the array of codepoints for the grapheme at requested offset' from 'the offset does not exist'.

sorry but I insist, having a nullable return type doesn't make sense, the more specific the better.

Comment (gharlan) [reply src/Symfony/Component/String/UnicodeString.php]: > It does because it's at the abstract level: abstract means it should generic enough to cover the domain, which is what this would provide. Putting the method at the abstract level is way better than forcing one to rely on more specialized methods.

> I would remove codePointAt entirely

ok

> sorry but I insist, having a nullable return type doesn't make sense, the more specific the better.

Ok, will change the return type (while still disagreeing, but that's ok ;) )

Comment (stof) [reply src/Symfony/Component/String/UnicodeString.php]: should we actually return null or empty array for an out of bound index, or throw an `\OutOfBoundsException` ?

Comment (gharlan) [reply src/Symfony/Component/String/UnicodeString.php]: I think `\OutOfBoundsException` would be better indeed. What do you think @nicolas-grekas ?

Comment (nicolas-grekas) [reply src/Symfony/Component/String/UnicodeString.php]: I tried to avoid throwing unnecessary exception as much as possible so throwing wouldn't be consistent with the rest of the component to me.

Comment (gharlan) [reply src/Symfony/Component/String/UnicodeString.php]: Ok, I will work on it

File: src/Symfony/Component/String/ByteString.php [hunk 2]
```diff
@@ -43,11 +43,11 @@ public static function fromRandom(int $length = 16): self
         return new static(substr($string, 0, $length));
     }
 
-    public function byteCode(int $offset = 0): ?int
+    public function bytesAt(int $offset): array
```
Comment (gharlan) [inline src/Symfony/Component/String/ByteString.php]: `bytesAt` or `byteCodesAt`?

Comment (nicolas-grekas) [reply src/Symfony/Component/String/ByteString.php]: `bytesAt` :)

**Review by nicolas-grekas — APPROVED** [review]
Perfect thank you!

File: src/Symfony/Component/String/AbstractUnicodeString.php [hunk 3]
```diff
@@ -149,6 +149,13 @@ public function ascii(array $rules = []): self
         return $str;
     }
 
+    public function bytesAt(int $offset): array
```
Comment (nicolas-grekas) [inline src/Symfony/Component/String/AbstractUnicodeString.php]: this implementation could be moved to `AbstractString` since it's generic (and we'd keep the optimized version in `ByteString`)

File: src/Symfony/Component/String/UnicodeString.php [hunk 4]
```diff
@@ -84,6 +84,13 @@ public function chunk(int $length = 1): array
         return $chunks;
     }
 
+    public function codePointsAt(int $offset): array
```
Comment (nicolas-grekas) [inline src/Symfony/Component/String/UnicodeString.php]: could be moved to AbstractUnicodeString with same reasoning as bytesAt on AbstractString

**Comment by nicolas-grekas** [comment]
Thank you @gharlan.
