### PR TITLE
[DoctrineBridge] Determine attribute or annotation type for directories

### LINKED ISSUE #43753: [DoctrineBridge] Attribute notation for entity in bundles is not recognized
### Symfony version(s) affected

5.3

### Description

When loading a bundle with a Doctrine entity, this entity is automatically recognized if `auto_mapping: true` is set in the Doctrine DBAL configuration. If you use annotations (`/** @ORM\Entity */`), this will work well. However, if you use the new Attributes to define the entity and its properties (`#[ORM\Entity]`) this is not recognized by the DoctrineBridge.

### How to reproduce

Create an entity in a bundle and define its Entity status with an attribute:

```
<?php

declare(strict_types=1);

namespace RedAnt\EventSourcingBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use RedAnt\EventSourcingBundle\Entity\Repository\ProjectionsRepository;

#[ORM\Entity(repositoryClass: ProjectionsRepository::class)]
final class ProjectionState
{
 // ...
}
```

This entity class is then not picked up by the Doctrine schema upgrade tool.

### Possible Solution

The AbstractDoctrineExtension in the DoctrineBridge already has a method for detecting the correct annotation type for entities in a folder (using a regex on the entity classes). We should separate this out into a new method `detectMappingType` and also using it when detecting the metadataDriver for that bundle directory.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by cinamo**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #43753
| License       | MIT

When loading a bundle with a Doctrine entity, this entity is automatically recognized if auto_mapping: true is set in the Doctrine DBAL configuration. This currently only works if your entity class uses annotations, not attributes; this pull request adds that possibility.

### CODE REVIEW

**Comment by derrabus** [comment]
Can you add a test please?

**Comment by cinamo** [comment]
> Can you add a test please?

@derrabus I would love to. However, the original functionality doesn't have a test to begin with. Also, this test would necessarily need to refer to external files and I don't have any idea how to do that in your test suite. Can you give me a pointer how you would go about this?

File: src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php [hunk 1]
```diff
@@ -280,13 +265,44 @@ protected function detectMetadataDriver(string $dir, ContainerBuilder $container
             }
             $container->fileExists($resource, false);
 
-            return $container->fileExists($dir.'/'.$this->getMappingObjectDefaultName(), false) ? 'annotation' : null;
+            if ($container->fileExists($dir.'/'.$this->getMappingObjectDefaultName(), false)) {
+                return (\PHP_VERSION_ID < 80000) ? 'annotation' : $this->detectMappingType($dir, $container);
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php]: shouldn't the check be moved to detectMappingType?

File: src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php [hunk 2]
```diff
@@ -280,13 +265,44 @@ protected function detectMetadataDriver(string $dir, ContainerBuilder $container
...
 
         return $driver;
     }
 
+    /**
+     * Detects what mapping type to use for the supplied directory.
+     *
+     * @return string A mapping type 'attribute' or 'annotation'
+     */
+    protected function detectMappingType(string $directory, ContainerBuilder $container): string
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php]: let's make it private

**Comment by nicolas-grekas** [comment]
Writing tests could be done by adding a directory with fixtures in a test folder.

File: src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php (hunk 1 above)
Comment (cinamo) [reply src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php]: Done!

File: src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php (hunk 2 above)
Comment (cinamo) [reply src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php]: Done!

**Comment by cinamo** [comment]
> Writing tests could be done by adding a directory with fixtures in a test folder.

Thanks for the suggestion, have made a new folder with an attribute annotation entity and added a test to detect the different kind of types.

**Review by derrabus — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @cinamo.
