### PR TITLE
[Security] Readd deprecated methods to the interfaces

### LINKED ISSUE #41470: A critical interface method was just removed in 5.3.0
**Symfony version(s) affected**: 5.3.0

**Description**
Regression in minor release.
https://github.com/symfony/security-core/compare/v5.2.8...v5.3.0#
A critical interface method was just removed instead of normal deprecation workflow and removal in next major.

**How to reproduce**
Implement UserInterface on vendor or project level, code against interface and now find yourself missing this contract (to be sure that method is available and implemented properly.

**Possible Solution**
Keep it in with deprecation only or add this method as soft annotation at least (as implementing code cannot do that post-factum now for the vendor interface).

**Additional context**
```
 ------ ------------------------------------------------------------------------
  Line   SprykerShop/Yves/CustomerPage/Plugin/Provider/CustomerUserProvider.php
 ------ ------------------------------------------------------------------------
  58     Call to an undefined method
         Symfony\Component\Security\Core\User\UserInterface::getUsername().
  115    Call to an undefined method
         Symfony\Component\Security\Core\User\UserInterface::getUsername().
 ------ ------------------------------------------------------------------------
```
The same seems to be true for `Authentication/RememberMe/PersistentTokenInterface.php` class.

### PR DESCRIPTION
**Pull request by wouterj**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41470
| License       | MIT
| Doc PR        | n/a

Readd the deprecated methods to the interface, to make sure third party packages <5.3 work with objects created using the 5.3+ interfaces.

I've tested in a project and the deprecation is not triggered when implementing the method, only when calling. So this should still allow applications to be deprecation free in 5.4.

### CODE REVIEW

**Review by pamil — APPROVED** [review]

File: src/Symfony/Bridge/Doctrine/Security/User/UserLoaderInterface.php [hunk 1]
```diff
@@ -29,4 +29,8 @@
  */
 interface UserLoaderInterface
 {
+    /**
+     * @deprecated since Symfony 5.3, use loadUserByIdentifier() instead
```
Comment (stof) [inline src/Symfony/Bridge/Doctrine/Security/User/UserLoaderInterface.php:35]: The phpdoc documenting the return type is missing

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Bridge/Doctrine/Security/User/UserLoaderInterface.php (hunk 1 above)
Comment (wouterj) [reply src/Symfony/Bridge/Doctrine/Security/User/UserLoaderInterface.php:35]: Thanks! Fixed.

File: src/Symfony/Component/Security/Core/User/UserProviderInterface.php [hunk 2]
```diff
@@ -57,4 +57,11 @@ public function refreshUser(UserInterface $user);
      * @return bool
      */
     public function supportsClass(string $class);
+
+    /**
+     * @return UserInterface
```
Comment (stof) [inline src/Symfony/Component/Security/Core/User/UserProviderInterface.php:62]: this one is missing the `@throws`

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Component/Security/Core/User/UserInterface.php [hunk 3]
```diff
@@ -78,4 +78,11 @@ public function getSalt();
      * the plain-text password is stored on this object.
      */
     public function eraseCredentials();
+
+    /**
+     * @return string
+     *
+     * @deprecated since Symfony 5.3, use getUserIdentifier() instead
```
Comment (chalasr) [inline src/Symfony/Component/Security/Core/User/UserInterface.php:85]: I fear this will trigger a deprecation notice that is impossible to fix for end users. Can you please confirm it does not before we merge?

Comment (wouterj) [reply src/Symfony/Component/Security/Core/User/UserInterface.php:85]: See the PR description. Is there a situation I didn't test you think will result in a deprecation?

Comment (chalasr) [reply src/Symfony/Component/Security/Core/User/UserInterface.php:85]: Thanks. I just checked out your PR, RAS.

**Review by stof — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @wouterj.

**Comment by Pixelshaped** [comment]
In my User I had to readd the old method:
```
    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated in Symfony 5.3
     */
    public function getUsername(): string
    {
        return $this->getUserIdentifier();
    }
```
As I understand it, I could remove the new method that will be re-introduced for the 6.0 BC?

**Comment by stof** [comment]
yeah, the `getUsername` will be removed from the interface in 6.0 (and so you will be able to remove it from your class implementing the interface). Deprecation-free code won't use this method in 5.3+ (using `getUserIdentifier` instead)

**Comment by derrabus** [comment]
> As I understand it, I could remove the new method that will be re-introduced for the 6.0 BC?

Don't remove the new method. Keep both methods for now and drop `getUsername()` once you migrate to Symfony 6.
