### PR TITLE
[Messenger] [Redis] Fixed problem where worker stops handling messages on first empty message

### LINKED ISSUE #48166: [Messenger][Redis] Worker stops handling messages on first empty message
### Symfony version(s) affected

5.4, 6.* and probably others

### Description

We're using messenger with redis transport in one of our projects. On one of our staging environments, we trimmed one queue (probably in parallel, the consumer of that queue failed). This led us to a strange situation, having a message in `XPENDING` while not having it in the corresponding stream. As only IDs are being stored in `XPENDING`, while consuming, messenger can't decode the body. The whole problem is of course our fault and most probably should not happen, anyway the way messenger behaves is weird – it is returning an empty array, like there are no messages in the queue, while not `XACK`-ing that message, so it hangs in a strange loop. In my opinion, it should either `XACK` that message or throw an exception with enough information so that someone using the library can handle it manually. It took us a long time to discover what was going on, while messenger was hung in a strange situation, not consuming messages from the queue – because there are no errors being logged anywhere.

### How to reproduce

I don't have a quick way to reproduce, but the problem lies in [RedisReceiver.php](https://github.com/symfony/redis-messenger/blob/5.4/Transport/RedisReceiver.php):

```php
    public function get(): iterable
    {
        $message = $this->connection->get();

        if (null === $message) {
            return [];
        }

        $redisEnvelope = json_decode($message['data']['message'] ?? '', true);

        if (null === $redisEnvelope) {
            return [];
        }
```
In my opinion, when `$redisEnvelope` is null, the library should either throw an exception with message ID or ACK this message, so it won't be handled any more.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rafal-tobola**
| Q             | A
| ------------- | ---
| Branch?       |5.4 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? |  no 
| Tickets       | Fix #48166 
| License       | MIT
| Doc PR        | n/a 

Fixed problem where worker stops handling messages on first empty message.

### CODE REVIEW

File: src/Symfony/Component/Messenger/Bridge/Redis/Tests/Transport/RedisExtIntegrationTest.php [hunk 1]
```diff
@@ -318,6 +322,30 @@ public function testGetAfterReject()
...
+    {
+        $redisReceiver = new RedisReceiver($this->connection, new Serializer());
+
+        $this->connection->add('{"message": "Hi1"}', ['type' => DummyMessage::class]);
+        $this->connection->add('{"message": "Hi2"}', ['type' => DummyMessage::class]);
+
+        $redisReceiver->get();
+        $this->redis->xtrim('messages', 1);
+
+        // CONSUMER DIED DURING HANDLING MESSAGE WHILE PERFORMING XTRIM IN PARALLEL PROCESS
```
Comment (OskarStark) [inline src/Symfony/Component/Messenger/Bridge/Redis/Tests/Transport/RedisExtIntegrationTest.php]: No need for screaming 😄

**Review by OskarStark — COMMENTED** [review]
Please associate your commiter email with your Github account

File: src/Symfony/Component/Messenger/Bridge/Redis/Tests/Transport/RedisExtIntegrationTest.php (hunk 1 above)
Comment (rafal-tobola) [reply src/Symfony/Component/Messenger/Bridge/Redis/Tests/Transport/RedisExtIntegrationTest.php]: You are absolutely right :smile:.

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/RedisReceiver.php [hunk 2]
```diff
@@ -47,6 +48,15 @@ public function get(): iterable
...
 
         if (null === $redisEnvelope) {
+            if (null !== $message['id']) {
+                try {
+                    $this->connection->ack($message['id']);
+                } catch (TransportException $e) {
+                }
+
+                return $this->get();
+            }
```
Comment (rafal-tobola) [inline src/Symfony/Component/Messenger/Bridge/Redis/Transport/RedisReceiver.php]: Forgotten to mention here. I don't have a better idea, as there is no possibility to change connection setting `deleteAfterAck` from outside the connection, and there is no possibility to perform `xack` directly from this class. If anyone has an idea how to make it more elegant, feel free to suggest how to do it.

File: src/Symfony/Component/Messenger/Bridge/Redis/Tests/Transport/RedisExtIntegrationTest.php [hunk 3]
```diff
@@ -318,6 +322,30 @@ public function testGetAfterReject()
         $redis->del('messenger-rejectthenget');
     }
 
+    public function testItProperlyHandlesEnptyMessages()
```
Comment (kotbehemot53) [inline src/Symfony/Component/Messenger/Bridge/Redis/Tests/Transport/RedisExtIntegrationTest.php]: Typo: "enpty"

**Review by nicolas-grekas — COMMENTED** [review]
I've rebased + squashed your PR to have a clean git history. Don't forget to fetch before working again on the patch if needed.
About the patch itself, I don't know the topic well enough. Anyone else willing to review in depth?

**Comment by chalasr** [comment]
Will do yes. Ping @alexander-schranz also since you provided some guidance in the linked issue (no hurry)

**Comment by Gregory-Gerard** [comment]
Is there anything I (or anyone else) can do to help with this PR?

I'm having the same problem, and this problem is also present in case of an invalid message (can't decode a JSON for example), it should never happen but I have an external system that can push in a stream read by Symfony Messenger, so it would be better if the transport to expect the possibility of an invalid or empty message and rejects this message.

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/RedisReceiver.php (hunk 2 above)
Comment (alexander-schranz) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/RedisReceiver.php]: I'm not sure if we should catch the `TransportException` here. Would that not hide an error if connection get lost? /cc @chalasr 

Also maybe it would be better ro call `$this->connection->reject` as we are doing nothing with that message.

If somebody has `deleteAfterAck=false&deleteAfterReject=true` that message would stay in the stream for other consumers, which I think would make more sense then using ack here?

**Comment by tourze** [comment]
Same problem, any update?

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/RedisReceiver.php (hunk 2 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/RedisReceiver.php]: > maybe it would be better ro call $this->connection->reject as we are doing nothing with that message

what about this proposal @jvmanji ?

**Review by nicolas-grekas — APPROVED** [review]
I updated the PR to use reject.

**Comment by nicolas-grekas** [comment]
Thank you @jvmanji.
