### PR TITLE
[Messenger] Filter out non-consumable receivers when registering `ConsumeMessagesCommand`

### LINKED ISSUE #51556: [Messenger] messenger:consume offers sync transports to consume from and then immediately throws an exception
### Symfony version(s) affected

6.3.3

### Description

When running `messenger:consume` without a transport, it asks to select which transport to consume from.

```
$ bin/console messenger:consume

                                                                                                                        
 Which transports/receivers do you want to consume?                                                                     
                                                                                                                        

Choose which receivers you want to consume messages from in order of priority.
Hint: to consume from multiple, use a list of their names, e.g. async, default

 Select receivers to consume: [async]:
  [0] async
  [1] default
```

But, if I select `default` (which is sync), it immediately throws

```
In SyncTransport.php line 37:
                                                                 
  You cannot receive messages from the Messenger SyncTransport.  
                                                                 
```

making this choice superfluous because the only possible selection is `async`.

### How to reproduce

See above.

### Possible Solution

Filter out sync transports and, if only one item remains, consume that immediately.

### Additional Context

I guess this could be considered an UX bug.

### PR DESCRIPTION
**Pull request by wazum**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #51556
| License       | MIT

This pull request enhances the `MessengerPass` in the Symfony Framework Bundle to automatically filter out non-consumable receivers when registering the `ConsumeMessagesCommand`. The key changes are:

The FrameworkExtension has been updated to mark the "sync" transport as non-consumable by default, without requiring the user to explicitly set the `is_consumable` attribute.

The `MessengerPass` then checks the `is_consumable` attribute on the `messenger.receiver` tags. If the attribute is set to `false`, the receiver is considered non-consumable and will not be added to the list of receivers for the consume command.
If there is only one consumable receiver, the consume command will automatically use that receiver without prompting the user to select one (I added this as a separate commit if this is too implicit).

These changes improve the user experience by removing unnecessary (and non-functioning) options.

This is my first pull request for the _Symfony_ project, so please let me know what I can improve.

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -2280,14 +2280,18 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
         $transportRateLimiterReferences = [];
         foreach ($config['transports'] as $name => $transport) {
             $serializerId = $transport['serializer'] ?? 'messenger.default_serializer';
+            $receiverTagAttributes = [
+                'alias' => $name,
+                'is_failure_transport' => \in_array($name, $failureTransports),
```
Comment (dkarlovi) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:2287]: Add the `is_consumable` here in either case.

File: src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php [hunk 2]
```diff
@@ -404,4 +414,9 @@ private function getServiceClass(ContainerBuilder $container, string $serviceId)
             return $definition->getClass();
         }
     }
+
+    private function isReceiverConsumable(array $tag): bool
+    {
+        return !isset($tag['is_consumable']) || false !== $tag['is_consumable'];
```
Comment (dkarlovi) [inline src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php]: Since you now have the `is_consumable`, this can be replaced with just `return $tag['is_consumable']`, making this method not really required, you can check the condition directly where the method is used.

**Review by dkarlovi — CHANGES_REQUESTED** [review]
Can simplify a little bit.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 3]
```diff
@@ -2286,6 +2286,7 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
                 ->addTag('messenger.receiver', [
                     'alias' => $name,
                     'is_failure_transport' => \in_array($name, $failureTransports),
+                    'is_consumable' =>!str_starts_with($transport['dsn'], 'sync://'),
```
Comment (dkarlovi) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]:
```suggestion
                    'is_consumable' => !str_starts_with($transport['dsn'], 'sync://'),
```

File: src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php [hunk 4]
```diff
@@ -289,6 +290,9 @@ private function registerReceivers(ContainerBuilder $container, array $busIds):
                         $failureTransportsMap[$tag['alias']] = $receiverMapping[$id];
                     }
                 }
+                if (isset($tag['is_consumable']) && $tag['is_consumable']) {
```
Comment (dkarlovi) [inline src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php]:
```suggestion
                if ($tag['is_consumable']) {
```

Comment (dkarlovi) [inline src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php]: We should now be able to assume `is_consumable` is always set, no? No need for `isset`, AFAIK.

Maybe if you set the tag manually, but then it applies to the alias too. :thinking: Not sure, somebody else will pitch in, but other than that, LGTM.

**Review by dkarlovi — CHANGES_REQUESTED** [review]
Small tweaks.

File: src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php (hunk 4 above)
Comment (wazum) [reply src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php]: I took an example from the code above/around.
Personally, I prefer more checks than fewer.

**Comment by wazum** [comment]
@dkarlovi  How can I change the wrong milestone? Should be `6.4`, right? And do I need to change anything else to get the `Reviewed` tag?

**Comment by dkarlovi** [comment]
@wazum a Symfony core team member needs to review too.

About your
> Bug fix: yes (kind of)

IMO there's no "kind of" about it, the current behavior is faulty since there's no value in offering a sync transport and then immediately crashing when it's selected, this is definitely a bugfix.

**Review by dkarlovi — APPROVED** [review]

File: src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php (hunk 4 above)
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php]: the way this is implemented at the moment breaks BC: a receiver should be considered consumable unless specified otherwise (currently it's the other way around)
then all changes on existing test cases should be reverted (the ones adding "is_consumable: true")

maybe the vocabulary needs to be reversed to make it clear? "is_synchronous"?

Comment (dkarlovi) [reply src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php]: IMO I'd leave `is_consumable`, but switch the default to keep BC as you suggested.

Keeping `is_consumable` is OK because it's future proof, you might want to make other receivers non-consumable in the future, not just sync ones.

**Comment by nicolas-grekas** [comment]
Friendly up @wazum

**Comment by wazum** [comment]
I need some help here, I don't quite understand why the tests fail.

**Comment by fabpot** [comment]
> I need some help here, I don't quite understand why the tests fail.

You can ignore the failing tests that are not related to your PR.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @wazum.
