### PR TITLE
[FrameworkBundle][HttpKernel] Let `RequestPayloadValueResolver` consider mapped argument type

### LINKED ISSUE #54617: MapQueryString/MapRequestPayload skips validation when empty request is sent.
### Symfony version(s) affected

6.4.6

### Description

It seems to be impossible to validate request properly when sent empty. For both query string and request payload mapper will return `null` and skip validation. Using default value makes callable being called with object which may be invalid.

### How to reproduce

```php
final class ApiDTO
{
    #[Assert\NotBlank]
    public string $foo = '';
}
```

```php
class FooController extends AbstractController
{
    #[Route("/foo", methods: ["GET"])]
    public function __invoke(#[MapQueryString(validationFailedStatusCode: 400)] ApiDTO $dto = new ApiDTO()): JsonResponse {
        dd($dto);
    }
}
```

```
expected behavior
GET /foo?foo= -> 400

validation skipped
GET /foo -> ApiDTO {
    +foo: ""
}
```

### Possible Solution

Possible solution would be to make mapper method return default value if defined instead of returning `null`

```php
// symfony/http-kernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php:162
private function mapQueryString(Request $request, string $type, MapQueryString $attribute): ?object
{
    if (!$data = $request->query->all()) {
        return $attribute->metadata->hasDefaultValue() ? $attribute->metadata->getDefaultValue() : null;
    }

    return $this->serializer->denormalize($data, $type, null, $attribute->serializationContext + self::CONTEXT_DENORMALIZE);
}

// symfony/http-kernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php:185
if ('' === $data = $request->getContent()) {
    return $attribute->metadata->hasDefaultValue() ? $attribute->metadata->getDefaultValue() : null;
}
```

```
GET /foo?foo= -> 400
GET /foo -> 400
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by unixslayer**
| Q | A |
| --- | --- |
| Branch? | 7.2 |
| Bug fix?| no |
| New feature?| yes |
| Deprecations? | no |
| Issues | Fix #54617 |
| License |MIT |

resolves #54617

In case of sending empty request, `RequestPayloadValueResolver` should consider argument type. In case empty request is considered invalid, having attribute as non-nullable without default value will cause to perform denormalization using empty input resulting with proper error message in response.

### CODE REVIEW

File: src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php [hunk 1]
```diff
@@ -185,7 +185,7 @@ public static function getSubscribedEvents(): array
 
     private function mapQueryString(Request $request, ArgumentMetadata $argument, MapQueryString $attribute): ?object
     {
-        if (!$data = $request->query->all()) {
+        if (!($data = $request->query->all()) && ($attribute->metadata->isNullable() || $attribute->metadata->hasDefaultValue())) {
```
Comment (yceruto) [inline src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php]: Note that in 7.2 the metadata argument is passed to this method, so this statement can be shortened:
```suggestion
        if (!($data = $request->query->all()) && ($argument->isNullable() || $argument->hasDefaultValue())) {
```

File: src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php [hunk 2]
```diff
@@ -212,7 +212,7 @@ private function mapRequestPayload(Request $request, ArgumentMetadata $argument,
             return $this->serializer->denormalize($data, $type, null, $attribute->serializationContext + self::CONTEXT_DENORMALIZE + ('form' === $format ? ['filter_bool' => true] : []));
         }
 
-        if ('' === $data = $request->getContent()) {
+        if ('' === ($data = $request->getContent()) && ($attribute->metadata->isNullable() || $attribute->metadata->hasDefaultValue())) {
```
Comment (yceruto) [inline src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php]:
```suggestion
        if ('' === ($data = $request->getContent()) && ($argument->isNullable() || $argument->hasDefaultValue())) {
```

**Review by yceruto — COMMENTED** [review]
Thanks! minor comments

**Comment by yceruto** [comment]
To help others understand the context of this PR, it would be great if you update the title as a new proposal, rather than focusing on it as an issue. Also, a good description is very appreciated, as it will help document the feature later on.

File: src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ApiAttributesTest.php [hunk 3]
```diff
@@ -365,7 +674,17 @@ public function __invoke(#[MapQueryString] ?QueryString $query): Response
     }
 }
 
-class WithMapRequestPayloadController
+class WithMapQueryStringWithDefaultValueController
+{
+    public function __invoke(#[MapQueryString] QueryString $query = new QueryString(new Filter('approved', 5))): Response
```
Comment (yceruto) [inline src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ApiAttributesTest.php:1020]: To ensure clarity, it’s not the default value that makes this work, but the argument type itself (`QueryString $query`). I think your PR title/description is not yet clear about this. In fact, having a empty query string + default value will skip the validation.

**Comment by yceruto** [comment]
I think what you have achieved here is a better error message when an empty query string or an empty request payload is sent, and the targeted parameter is not nullable and doesn’t have a default value. In this case, the Serializer denormalizes the empty input as an empty object instead of just returning null, thus triggering the validation with a detailed error message.​

This is the critical code:
```php
class Controller
{
    public function __invoke(#[MapQueryString] FooDto $foo) {}
}
```
Before -> Exception without message
After -> Exception with detailed message

**Comment by unixslayer** [comment]
@yceruto your last comment made me realize I may not achieved what I was hoping for. I have to clear out test cases and get back to you next week.

**Comment by unixslayer** [comment]
Hi @yceruto, sorry for delay and possible confusion. I had to review test cases if they cover expected scenarios.

**Review by yceruto — APPROVED** [review]

**Comment by unixslayer** [comment]
@yceruto how do you guys deal with random test fails (8.4) or tests that fails only with one pipeline (8.2, low-deps)?

**Review by yceruto — CHANGES_REQUESTED** [review]
The `symfony/framework-bundle` package currently requires `"symfony/http-kernel": "^6.4|^7.0"`, which causes issues when the FWB runs tests with an older `symfony/http-kernel` version (v6.4).

In these cases, we update the FWB `composer.json` file to require the newest `symfony/http-kernel` version instead, i.e. `^7.2`, so the CI will use that version in the `low-deps` job.

However, I'm not sure it makes sense in this case where the only changes in FWB here are about tests. Actually, the FWB is still compatible with `symfony/http-kernel: 6.4`. Let's ask @symfony/mergers to be sure.

File: src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ApiAttributesTest.php [hunk 4]
```diff
@@ -84,12 +143,78 @@ public static function mapQueryStringProvider(): iterable
...
+
+        yield 'empty query string mapping non-nullable attribute without default value' => [
+            'uri' => '/map-query-string-to-non-nullable-attribute-without-default-value.json',
+            'query' => [],
+            'expectedResponse' => <<<'JSON'
+                {
+                    "type": "https:\/\/symfony.com\/errors\/validation",
+                    "title": "Validation Failed",
+                    "status": 404,
+                    "detail": "filter: This value should be of type Symfony\\Bundle\\FrameworkBundle\\Tests\\Functional\\Filter.",
```
Comment (GromNaN) [inline src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ApiAttributesTest.php:153]: This text can be changed depending of the version of the framework bundle. Using `Composer\InstalledVersions`, so that the test pass for all supported version.

**Comment by unixslayer** [comment]
@yceruto @GromNaN what about 8.4? Is that fail irrelevant for now?

File: src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ApiAttributesTest.php [hunk 5]
```diff
@@ -348,32 +498,590 @@ public static function mapRequestPayloadProvider(): iterable
...
+                {
+                  "type":"https:\/\/tools.ietf.org\/html\/rfc2616#section-10",
+                  "title":"An error occurred",
+                  "status":400,
+                  "detail":"Bad Request"
+                }
+                JSON;
+
+        $httpKernelVersion = InstalledVersions::getVersion('symfony/http-kernel');
+        if ($httpKernelVersion && version_compare($httpKernelVersion, '7.0.0', '<')) {
```
Comment (yceruto) [inline src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ApiAttributesTest.php]: is it possible to check for 7.2.0 instead?

**Review by yceruto — APPROVED** [review]

**Comment by yceruto** [comment]
>@yceruto @GromNaN what about 8.4? Is that fail irrelevant for now?

They are unrelated, so you can ignore them.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @unixslayer.
