### PR TITLE
[Security] Throw an explicit error when refreshing a token with a null user

### LINKED ISSUE #59559: [Security-Http] ContextListener.refreshUser does not handle null users
### Symfony version(s) affected

7.3.0

### Description

I have a custom security token implementation that returns `null` in `getUser` when the underlying token has expired. This is allowed by `TokenInterface`.

The method `refreshUser` of the `ContextListener` class contains this code:

```php
        $user = $token->getUser();

        $userNotFoundByProvider = false;
        $userDeauthenticated = false;
        $userClass = $user::class;
```

When `$user` is null, this code fails. Perhaps this method should just return null when `$user` is null.

It may very well be that I shouldn't return `null` from `getUser`, but the fact that the interface allows it and `refreshUser` doesn't handle it, might constitute a bug anyway.

### How to reproduce

1. Create a custom token class and use it in an authenticator.
2. Open a secured page in Symfony that triggers `ContextListener.authenticate()`.

### Possible Solution

Return `null` early in `ContextListener.refreshUser` when `$user` is `null`.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59559
| License       | MIT

Follwing https://github.com/symfony/symfony/pull/59560#issuecomment-2606603618, to prevent the code to simply fail and return an explicit message to the user.

### CODE REVIEW

**Comment by chalasr** [comment]
Could we act earlier and prevent user-less token creation instead?

**Comment by alexandre-daubois** [comment]
Moved the condition as early as possible, when we know we deal with a `TokenInterface`

File: src/Symfony/Component/Security/Http/Firewall/ContextListener.php [hunk 1]
```diff
@@ -123,6 +123,10 @@ public function authenticate(RequestEvent $event): void
         ]);
 
         if ($token instanceof TokenInterface) {
+            if (null === $token->getUser()) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Http/Firewall/ContextListener.php]:
```suggestion
            if (!$token->getUser()) {
```

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @alexandre-daubois.
