### PR TITLE
[PropertyAccess] Fix checking for missing properties

### LINKED ISSUE #48970: [VarExporter][DoctrineBundle] Accessing unknown properties on lazy ghost objects generates notices instead exceptions
### Symfony version(s) affected

6.2.4

### Description

Initially this bug looked like an issue with EasyAdmin Bundle, as it is triggered by its code. The simplest way to do it is to add a field which doesn't exist on an entity, e.g.:

```
        yield TextField::new('type.thresholds_matches', 'Thresholds')
                       ->setVirtual(true)
                       ->setTemplatePath('admin/field/measurement_threshold.html.twig');
```

When `enable_lazy_ghost_objects` is disabled this works correctly and simply renders an empty field/custom template. However, the issue isn't actually in EAB but in `LazyGhostTrait` breaking the `PropertyAccessorInterface` promise:

https://github.com/symfony/symfony/blob/991c2bad292c4c4af17328c331507a5a7789512c/src/Symfony/Component/PropertyAccess/PropertyAccessorInterface.php#L69-L74

`->getValue()` should produce an exception when a given property doesn't exist, which EAB relies on: https://github.com/EasyCorp/EasyAdminBundle/blob/4db1860871809ca0be610ba5dab9be26ba165351/src/Field/Configurator/CommonPreConfigurator.php#L49-L53

### How to reproduce

PoC reproducer, pick your own entity of course. In my case the `type` field is configured as:

```php
    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?MeasurementType $type = null;
```

The test code I used:
```php
<php declare(strict_types=1);

#[AsCommand(name: 'app:sandbox')]
class SandboxCommand extends Command
{
    public function __construct(private ManagerRegistry $doctrine, private PropertyAccessorInterface $propertyAccessor)
    {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $repo = $this->doctrine->getRepository(InanimateObjectMeasurement::class);
        $ent = $repo->findOneBy([]);

        dump($ent);
        dump($this->propertyAccessor->getValue($ent, 'value'));
        dump($this->propertyAccessor->getValue($ent, 'type.thresholds_matches'));
        
        return 0;
    }
```


With `enable_lazy_ghost_objects=false`:
```
 % bin/console app:sandbox -v
"183/88"

In PropertyAccessor.php line 453:
                                                                                                                               
  [Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException]                                                         
  Can't get a way to read the property "thresholds_matches" in class "Proxies\__CG__\App\Entity\Measurement\MeasurementType". 
```

With `enable_lazy_ghost_objects=true`:
```
 % bin/console app:sandbox -v
"183/88"

In LazyGhostTrait.php line 191:
                                                                                                                                                                                                                                       
  [ErrorException]                                                                                                                                                                                                                     
  User Notice: Undefined property: Proxies\__CG__\App\Entity\Measurement\MeasurementType::$thresholds_matches in /app/vendor/symfony/property-access/PropertyAccessor.php on line 428  
                                                                                                                                                                                                                                       
```

### Possible Solution

_No response_

### Additional Context

_No response_

### LINKED ISSUE #51919: [PropertyAccess][VarExporter] `PropertyAccessor::isReadable()` triggers an error when called on a lazy object’s missing property
### Symfony version(s) affected

≥ 6.2

### Description

Calling `PropertyAccessor::isReadable()` on a lazy object’s missing property will trigger an error, even if the object is fully loaded.

This is because `PropertyAccessor::getReadInfo()` will return the property as public as its class has a `__get` method, and trying to access it will call `trigger_error`: https://github.com/symfony/symfony/blob/3147082e35faadd873a801a4011bc8cbb79807e0/src/Symfony/Component/VarExporter/LazyGhostTrait.php#L193
### How to reproduce

Call `PropertyAccessor::isReadable()` on a lazy object’s (like a Doctrine proxy) missing property. Instead of `false`, you’ll get an `ErrorException`.

### Possible Solution

_No response_

### Additional Context

_No response_

### LINKED ISSUE #53972: [Serializer][ORM] enable_lazy_ghost_objects with Serializer doesn't work
### Symfony version(s) affected

5.4.34

### Description

enable_lazy_ghost_objects is set to true

have a Class with Complex Structure and Collections

```php

use Doctrine\Common\Collections\Collection;
interface PageInterface
{
    /**
     * @return Collection<array-key, PageInterface>
     */
    public function getChildren(): Collection;
    /**
     * @return Collection<array-key, BlockInterface>
     */
    public function getBlocks(): Collection;
}

```

```php

use Doctrine\Common\Collections\Collection;
interface BlockInterface
{
    /**
     * @return Collection<int, BlockInterface>
     */
    public function getChildren(): Collection;
}
```

### How to reproduce

```yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
```

have entity classes that implement this interfaces:

```php

use Doctrine\Common\Collections\Collection;
interface PageInterface
{
    /**
     * @return Collection<array-key, PageInterface>
     */
    public function getChildren(): Collection;
    /**
     * @return Collection<array-key, BlockInterface>
     */
    public function getBlocks(): Collection;
}

```

```php

use Doctrine\Common\Collections\Collection;
interface BlockInterface
{
    /**
     * @return Collection<int, BlockInterface>
     */
    public function getChildren(): Collection;
}
```

now use Symfony Normalizer to try to normalize the Page object when the Collections aren't fully loaded yet

This ErrorException happened:
```
ErrorException:
User Notice: Undefined property: Proxies\__CG__\App\Entity\SonataPageBlock::$lazyObjectState in D:\*****\******\******\sonata\private\vendor\symfony\property-access\PropertyAccessor.php on line 488

  at D:\*****\******\******\sonata\private\vendor\symfony\var-exporter\LazyGhostTrait.php:193
  at Proxies\__CG__\App\Entity\SonataPageBlock->__get('lazyObjectState')
     (D:\*****\******\******\sonata\private\vendor\symfony\property-access\PropertyAccessor.php:488)
  at Symfony\Component\PropertyAccess\PropertyAccessor->readProperty(array(object(SonataPageBlock)), 'lazyObjectState', false)
     (D:\*****\******\******\sonata\private\vendor\symfony\property-access\PropertyAccessor.php:154)
  at Symfony\Component\PropertyAccess\PropertyAccessor->getValue(object(SonataPageBlock), 'lazyObjectState')
     (D:\*****\******\******\sonata\private\vendor\symfony\serializer\Normalizer\ObjectNormalizer.php:136)
  at Symfony\Component\Serializer\Normalizer\ObjectNormalizer->getAttributeValue(object(SonataPageBlock), 'lazyObjectState', null, array('datetime_format' => 'U', 'skip_null_values' => true, 'callbacks' => array('blocks' => object(Closure), 'parent' => object(Closure)), 'cache_key' => false, 'circular_reference_limit_counters' => array('00000000000005400000000000000000' => 1, '00000000000008a70000000000000000' => 1)))
     (D:\*****\******\******\sonata\private\vendor\symfony\serializer\Normalizer\AbstractObjectNormalizer.php:190)
  at Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize(object(SonataPageBlock), null, array('datetime_format' => 'U', 'skip_null_values' => true, 'callbacks' => array('blocks' => object(Closure), 'parent' => object(Closure)), 'cache_key' => false, 'circular_reference_limit_counters' => array('00000000000005400000000000000000' => 1, '00000000000008a70000000000000000' => 1)))
     (D:\*****\******\******\sonata\private\vendor\symfony\serializer\Serializer.php:161)
  at Symfony\Component\Serializer\Serializer->normalize(object(SonataPageBlock), null, array('datetime_format' => 'U', 'skip_null_values' => true, 'callbacks' => array('blocks' => object(Closure), 'parent' => object(Closure)), 'cache_key' => false, 'circular_reference_limit_counters' => array('00000000000005400000000000000000' => 1)))
     (D:\*****\******\******\sonata\private\vendor\symfony\serializer\Serializer.php:179)
  at Symfony\Component\Serializer\Serializer->normalize(array(object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock)), null, array('datetime_format' => 'U', 'skip_null_values' => true, 'callbacks' => array('blocks' => object(Closure), 'parent' => object(Closure)), 'cache_key' => false, 'circular_reference_limit_counters' => array('00000000000005400000000000000000' => 1)))
     (D:\*****\******\******\sonata\private\vendor\symfony\serializer\Normalizer\AbstractObjectNormalizer.php:224)
  at Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize(object(SonataPagePage), null, array('datetime_format' => 'U', 'skip_null_values' => true, 'callbacks' => array('blocks' => object(Closure), 'parent' => object(Closure)), 'cache_key' => false, 'circular_reference_limit_counters' => array('00000000000005400000000000000000' => 1)))
     (D:\*****\******\******\sonata\private\vendor\symfony\serializer\Serializer.php:161)
  at Symfony\Component\Serializer\Serializer->normalize(object(SonataPagePage), null, array('datetime_format' => 'U', 'skip_null_values' => true, 'callbacks' => array('blocks' => object(Closure), 'parent' => object(Closure))))

```

### Possible Solution

calling `Collection->getValues()` might not be enough, the 'blocks' Closure already does it

```php
AbstractNormalizer::CALLBACKS => [
    'blocks' => static fn (Collection $collection, PageInterface $object, string $attribute, ?string $format = null, array $context = []) => $collection->filter(static fn (BlockInterface $block) => !$block->hasParent())->getValues(),
]
```           

### Additional Context

Related Sonata Issue:
https://github.com/sonata-project/SonataPageBundle/issues/1747

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #48970, fix #53972, fix #51919
| License       | MIT

PropertyAccess and PropertyInfo make a few assumptions when magic methods are involved.
Namely they assume that if a `__get` method is defined, then any property name is accessible.
This assumption is generally wrong, and this becomes more evident with the introduction of lazy objects.
The linked issue gives some more details.

In this PR, I tweak these assumptions in order to make less of them.
Note that there is no bullet-proof way to decide if a *virtual* property exists in PHP. We're missing an `__exists()` magic method for that. Because of this, I'm submitting this PR to 6.4 and not 5.4. Let 5.4 end its life quietly and ensure 6.4 works at its best with lazy ghosts, where they're mainstream.

### CODE REVIEW

**Comment by chalasr** [comment]
Is there a way to test this?

**Comment by nicolas-grekas** [comment]
I think I did add tests, do you have something more in mind?

**Comment by chalasr** [comment]
Something must have blinded me 👀 Sorry!

**Review by chalasr — APPROVED** [review]
Is the `__exists()` your next RFC?

**Comment by nicolas-grekas** [comment]
I don't think so :)

**Review by mtarld — APPROVED** [review]

**Comment by alexandre-le-borgne** [comment]
I tested this fix but it doesn't work for me

I use PhpDocExtractor to be able to denormalize objects with properties like this:

```
class Form // Not a doctrine entity
{
    /**
     * @var Step[]
     */
    private array $steps;
}

class Step // Not a doctrine entity
{
}
```

However I still get the same error when I serialize this kind objects :

```
class FormOutput // Not a doctrine entity
{
    /**
     * @var IndicatorType                                    <--- A Doctrine entity
     */
    private IndicatorType $indicatorType;
}
```

User Notice: Undefined property: Proxies\__CG__\App\Entity\IndicatorType::$lazyObjectState in /home/.../src/Serializer/PropertyAccessor.php on line 419

**Comment by xabbuh** [comment]
@alexandre-le-borgne Can you please open a new issue and provide a small example application that allows to reproduce your issue?

**Comment by alexandre-le-borgne** [comment]
@xabbuh https://github.com/symfony/symfony/issues/54393

File: src/Symfony/Component/PropertyAccess/PropertyAccessor.php [hunk 1]
```diff
@@ -411,8 +411,18 @@ private function readProperty(array $zval, string $property, bool $ignoreInvalid
                         throw $e;
                     }
                 } elseif (PropertyReadInfo::TYPE_PROPERTY === $type) {
-                    if ($access->canBeReference() && !isset($object->$name) && !\array_key_exists($name, (array) $object) && !(new \ReflectionProperty($class, $name))->hasType()) {
```
Comment (sbuerk) [inline src/Symfony/Component/PropertyAccess/PropertyAccessor.php:414]: Is there a reason why the `$access->canBeReference()` check has been dropped here ?

Comment (nicolas-grekas) [reply src/Symfony/Component/PropertyAccess/PropertyAccessor.php:414]: yes: that check was just wrong - `__get` can return by reference, so this was an unrelated check

Comment (sbuerk) [reply src/Symfony/Component/PropertyAccess/PropertyAccessor.php:414]: Thanks for the information.

**Comment by vsoroka** [comment]
I guess that a better sollution will be to create an interface for classes that will ckeck existance of magic properties, e.g. MagicPropertyExistanceExtractorInterface, and if Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor implements this interface delegate the existance check to it. It will allow to implement application depended logic related to magic properties without workarounds.
Unfortutattely since version 6.4.6 I have to configure the property accessor to ignore invalid properties in my application and try to find a way to do this check outside the property accessor.

**Comment by craigh** [comment]
This change broke my tests. They work with 6.4.4 and not with 6.4.6.
I get the error `Can\'t get a way to read the property "%s" in class "%s".'`

I use magic getters in one of my entities like so:
```php
    public function __get(string $arg)
    {
        if (preg_match('/custom_checkbox_(\d+)_entry(_other)?/', $arg, $matches)) {
            if (isset($matches[2])) {
                return $this->getCustomCheckboxEntryOther((int) $matches[1]);
            }

            return $this->getCustomCheckboxEntryForCheckbox((int) $matches[1]);
        }
        if (preg_match('/customCheckboxEntryValueByCheckboxId(\d+)/', $arg, $matches)) {
            return $this->getCustomCheckboxEntryValueByCheckboxId((int) $matches[1]);
        }
    }
```

my tests use `liip/test-fixtures-bundle` (if this matters).

**Comment by nicolas-grekas** [comment]
@craigh you might have a broken implementation of `__isset`, please have a look and try to fix it.

**Comment by craigh** [comment]
@nicolas-grekas I don't have an `__isset` method at all. Must I have one?

**Comment by craigh** [comment]
@nicolas-grekas of course, you are correct 🎉 thank you for your keen insight and quick response!

**Comment by fmonts** [comment]
This is a BC break, I'm now getting:

> [NoSuchPropertyException]
> Can't get a way to read the property "offerFallback" in class "App\Entity\Offer".

Even if I have this, to access dynamic properties stored in a json column:

    public function __get(string $name): mixed
    {
        if (property_exists(Offer::class, $name)) {
            return $this->$name;
        }
        return $this->getSetting($name) ?? null;
    }

It's look like the magic getter is never called

**Comment by nicolas-grekas** [comment]
@fmonts same as above: you likely have a broken implementation of __isset, please have a look and try to fix it.

**Comment by fmonts** [comment]
> @fmonts same as above: you likely have a broken implementation of __isset, please have a look and try to fix it.

I don't have any `__isset()`, I accept virtually any name, this would require me to add 

    public function __isset(string $name): bool
    {
        return true;
    }

to many entities...

**Comment by nicolas-grekas** [comment]
That's why then. You relied on a specific behavior of PropertyAccess, which is broken in the generic case (eg the `??` operator should be broken with you objects, etc).

**Comment by barryvdh** [comment]
This seems to break access to properties in Laravel Eloquent models when the value is `null`. This is because __isset() returns false if the value is `null` and no actual property exists on the model. And if a model is not loaded from the database yet, it will have no properties. So it's impossible to check if it will be allowed. 

I'm not sure if there is a 'standard' way to check for access there, because of the way ActiveRecord works (at least in Laravel). In Laravel it is always possible to set or get a property on the model..
Eg. when setting `$model->name = 'Foo';` it will set `$model->attributes['name']` (and perform additional actions when setting/getting) using the magic __get() and __set() methods. If an attribute is requested that does not exist, it will return null.

**Comment by u03c1** [comment]
Hi all,

I faced an issue today trying to upgrade a SF 6.4 project regarding this point.

I have a Dto with a property _foo as an array.

` public array $_foo = [];`

I have also a magic getter on this Dto like that.
```

    public function __get(string $name)
    {
        if (isset($this->_foo[$name])) {
            return $this->_foo[$name];
        }

        throw new \Exception('Invalid property');
    }
```

Now with this PR, code break because of the`   $r = new \ReflectionProperty($class, $name);` as obviously if I try to access a property name bar not existing in the Dto class, ReflexionProperty just throw an exception (it does not try to know if a magic method will allow to get this value).

PHP documentation said:

[__get()](https://www.php.net/manual/en/language.oop5.overloading.php#object.get) is utilized for reading data from inaccessible (protected or private) or non-existing properties.

In regards of the php doc, I should be able to read this property using the magic method, so I'm confused with this "can't get a way to read the property" error.

Is this because I'm wrong with my understanding on how I'm allowed to work with magic getter, or because this fix is now too strict and can results in false error on some edge cases like mine ?

**Comment by xabbuh** [comment]
@u03c1 You also need to implement the `__isset()` method accordingly.

**Comment by u03c1** [comment]
> @u03c1 You also need to implement the `__isset()` method accordingly.

Well, I have seen this same answer 2 or 3 times on this thread before I post, but my brain didn't connect and search an isset in my __get(), not an __isset(). :facepalm: 

Thanks again.
