### PR TITLE
[DependencyInjection] Respect original service class when a proxy is defined

### LINKED ISSUE #60765: [DependencyInjection] Proxy does not work well with inheritance
### Symfony version(s) affected

all?

### Description

I have an application ([castor](https://github.com/jolicode/castor)) that recently has stopped building.

The failure is only with PHP 8.4. We use Symfony 7.2.* but it's broken also on Symfony 7.3

I get the following error, when the application starts

```
The real instance class RepackedApplication is not compatible with the proxy class App\Application. The proxy must be a instance of the same class as the real instance, or a sub-class with no additional properties, and no overrides of the __destructor or __clone methods
```

### How to reproduce

I made a [reproducer, available in the following repo](https://github.com/lyrixx/test/tree/symfony/symfony/issues/60765)

I also tried the following line, instead of the faulty line:

```
$services->get(Application::class)->class(RepackedApplication::class);
```

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60765
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 1]
```diff
@@ -322,6 +322,9 @@ private function autowireMethod(\ReflectionFunctionAbstract $reflectionMethod, a
                     if ($attribute instanceof AutowireCallable) {
                         $value = $attribute->buildDefinition($value, $type, $parameter);
                     } elseif ($lazy = $attribute->lazy) {
+                        if ($this->container->has($type)) {
+                            $type = $this->container->findDefinition($type)->getClass();
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: I don't think this should be done for the case where `lazy` is an array specifying the exact interfaces that should be proxied

**Review by stof — COMMENTED** [review]
We should have tests preventing regressions

**Comment by lyrixx** [comment]
@nicolas-grekas Is it the way to go? If yes, I'll finish this PR asap

**Review by nicolas-grekas — COMMENTED** [review]
Yes, this needs to be fixed, good catch.
The class name should be extracted from $value instead I think, after the call to $getValue().

**Comment by lyrixx** [comment]
I updated the PR

* Added test
* Used `$value`
* change the base branch to 7.3. Actually, the bug does not exist in 6.4. Only on 7.0 and higher.

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/ProxyAndInheritance/Application.php [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\DependencyInjection\Tests\Fixtures\ProxyAndInheritance;
+
+class Application
+{
+    public function __construct(
+        private Foo $foo,
+        private string $name = 'my-app',
```
Comment (OskarStark) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/ProxyAndInheritance/Application.php:18]: Do we need this prop or can we return my-app directly in getName()?

Comment (lyrixx) [reply src/Symfony/Component/DependencyInjection/Tests/Fixtures/ProxyAndInheritance/Application.php:18]: yes, it's needed. If I hardcode the name, and revert my patch, the test pass.

**Comment by nicolas-grekas** [comment]
Good catch, thanks @lyrixx.
