### PR TITLE
[ObjectMapper] Add `targetClass` on `MapCollection` transform

### LINKED ISSUE #61957: [ObjectMapper] Maping Collection from?
### Symfony version(s) affected

7.4

### Description

Hi there,

I'm not sure, if it's really a bug or I'm using it wrong.
Into an Controller I'll get as JSON an object of arrays of objects. If not understand what I mean, an example is in the additional context, controller and DTO is in how to reproduce.
Sending an request to this, I'll get an exception: `Symfony\Component\ObjectMapper\ObjectMapper::map(): Argument #1 ($source) must be of type object, array given, called in /var/www/html/project/vendor/symfony/object-mapper/Transform/MapCollection.php on line 39`
Of course, I understand the mapper tries to map an array to an ArrayCollection of Entites. But how should this work, what was the programmer thinking?

### How to reproduce

```
class ManySpecsDTO
{
    public function __construct(

        #[Map(target: "spec_1", transform: new MapCollection())]
        /** @var Spec1[] */
        public readonly array $spec_1,
        
        #[Map(target: "spec_2", transform: new MapCollection())]
        /** @var Spec2[] */
        public readonly array $spec_2,
    )
    {
        
    }
}
```

```
public function controllerMethod(
#[MapRequestPayload] ManySpecsDTO $manySpecsDTO)
{

}
```

### Possible Solution

I wish to get two behaviors:
- In the RequestPayload-DTO an array of DTOs (without mapper?)
- in the Mapper-Target-Object an ArrayCollection of the request objects

With the [documentation](https://symfony.com/doc/7.4/object_mapper.html#mapping-collections)  I don't get how this should work. 

### Additional Context

JSON Object of Request:
```
{
  spec_1: [
    {
      spec_1_id: 1,
      spec_1_name: "Test"
    },
    {
      spec_1_id: 2,
      spec_1_name: "Test 2"
    }
  ],
spec_2: [
    {
      spec_2_id: 1,
      spec_2_name: "Test"
    },
    {
      spec_2_id: 2,
      spec_2_name: "Test 2"
    }
  ],
}
```

Could someone help here please?

Thank you

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #61957
| License       | MIT

Fixes #61957 (also reimplementing #62254) 

Needs a doc PR

This allows to change the target class of a mapped collection without having to add a `Map` attribute on the collection's class: 

```php
#[Map(target: OrderTarget::class)]
class OrderSource
{
    #[Map(transform: new MapCollection(targetClass: LineItemTarget::class))]
    public array $items = [];
}
```

### CODE REVIEW

File: src/Symfony/Component/ObjectMapper/Transform/MapCollection.php [hunk 1]
```diff
@@ -15,19 +15,26 @@
...
  *
  * @implements TransformCallableInterface<object, T>
  */
-class MapCollection implements TransformCallableInterface
+class MapCollection implements TransformCallableInterface, TransformObjectMapperAwareInterface
 {
     public function __construct(
         private ObjectMapperInterface $objectMapper = new ObjectMapper(),
+        public readonly ?string $targetClass = null,
     ) {
```
Comment (Grafikart) [inline src/Symfony/Component/ObjectMapper/Transform/MapCollection.php:30]: The $objectMapper is not required anymore since it will be set every time (constructing an object for nothing is not great imo)

Comment (soyuka) [reply src/Symfony/Component/ObjectMapper/Transform/MapCollection.php:30]: but it breaks BC layer

File: src/Symfony/Component/ObjectMapper/Transform/MapCollection.php [hunk 2]
```diff
@@ -36,7 +43,7 @@ public function __invoke(mixed $value, object $source, ?object $target): mixed
 
         $values = [];
         foreach ($value as $k => $v) {
-            $values[$k] = $this->objectMapper->map($v);
+            $values[$k] = $this->objectMapper->map($v, $this->targetClass);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/Transform/MapCollection.php]:
```suggestion
            $values[$k] = $objectMapper->map($v, $this->targetClass);
```

and before: `$objectMapper = $this->objectMapper ??= new ObjectMapper();` to address @Grafikart's concern?

File: src/Symfony/Component/ObjectMapper/TransformObjectMapperAwareInterface.php [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\ObjectMapper;
+
+interface TransformObjectMapperAwareInterface
+{
+    public function setObjectMapper(ObjectMapperInterface $objectMapper): void;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/TransformObjectMapperAwareInterface.php]: what about shortening the name ?
And also returning a clone instead of making the service mutable?

```suggestion
interface ObjectMapperAwareInterface
{
    /**
     * Returns a clone of the original instance, configured with the given object mapper.
     */
    public function withObjectMapper(ObjectMapperInterface $objectMapper): static;
```

File: src/Symfony/Component/ObjectMapper/Transform/MapCollection.php [hunk 4]
```diff
@@ -15,17 +15,23 @@
...
  *
  * @implements TransformCallableInterface<object, T>
  */
-class MapCollection implements TransformCallableInterface
+class MapCollection implements TransformCallableInterface, TransformObjectMapperAwareInterface
 {
     public function __construct(
-        private ObjectMapperInterface $objectMapper = new ObjectMapper(),
-    ) {
+        private ObjectMapperInterface $objectMapper,
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/Transform/MapCollection.php]: can be readonly if you follow my suggestion on the interface

File: src/Symfony/Component/ObjectMapper/CHANGELOG.md [hunk 5]
```diff
@@ -6,6 +6,9 @@ CHANGELOG
 
  * Add reverse class-map based on Map attribute
  * Merge nested properties when targeting the same class
+ * Add a `targetClass` option to `MapCollection`
+ * Add a `TransformObjectMapperAwareInterface` to inject the current object
+   mapper instance to transformers
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/CHANGELOG.md]: we like long lines (and wide screens) :)


```suggestion
 * Add a `TransformObjectMapperAwareInterface` to inject the current object mapper instance to transformers
```

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @soyuka.
