### PR TITLE
[Messenger] Resend failed retries back to failure transport

### LINKED ISSUE #51815: [Messenger] Requeue failed retries
### Description

Given `messenger:failed:retry`, it seems sane if a retry failure is put back on the failure queue, till either manually deleted or the retry succeeds.

I tried using a recursive failure transport:

```yaml
failed:
  dsn: ...
  failure_transport: failed
```

but it didnt make any changes.

### Example

_No response_

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | 6.4 / 5.4
| Bug fix?      | yes
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #51815 
| License       | MIT

i want to argue this is a bugfix :)

i can confirm with this fix, you can indefinitely retry failures, till they succeed, are deleted manually, or are handled explicitly by other means. What should NOT happen is systems implicitly rejecting/acking messages without any confirmation whatsoever.

cc @fabpot, @weaverryan

### CODE REVIEW

**Comment by weaverryan** [comment]
That code goes all the way back to the original PR for the failure transport system. I can't remember why I had this, however. Since we're dealing with the failure transport, this seems like a safe area, but I'd still probably do it for 6.4.

File: src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php [hunk 1]
```diff
@@ -52,11 +52,6 @@ public function onMessageFailed(WorkerMessageFailedEvent $event)
 
         $envelope = $event->getEnvelope();
 
-        // avoid re-sending to the failed sender
-        if (null !== $envelope->last(SentToFailureTransportStamp::class)) {
-            return;
-        }
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php:58]: If we have the `SentToFailureTransportStamp`, should we avoid adding the stamps below?

Comment (ro0NL) [reply src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php:58]: i thought it was a nice semantic to keep for future purposes maybe

Comment (weaverryan) [reply src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php:58]: I can't really think of a downside, other than more and more stamps stacked on each other, but these stamps are tiny...

**Review by weaverryan — APPROVED** [review]

File: src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php (hunk 1 above)
Comment (ro0NL) [reply src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php:58]: actually it remains used: https://github.com/symfony/symfony/blob/9767270b34e97d1bbf340f9ab3358a0178dccb8a/src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php#L119

Comment (ro0NL) [reply src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php:58]: oh sorry, i misunderstood. We don't need to stack them per se, i agree

edit: i think i'd keep them for now to keep the flow transparent

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @ro0NL.
