### PR TITLE
[HttpFoundation] get currently session.gc_maxlifetime if ttl doesnt exists

### LINKED ISSUE #34659: [HttpFoundation component] Possible RedisSessionHandler and Session maxlifetime differents
**Symfony version(s) affected**: 4.4.0

**Description** 

Option `gc_maxlifetime` doesn't work well, because RedisSessionHandler use a different variable for this purpose. 

`session.gc_maxlifetime` will set on `setOptions` method of `Session/Storage/NativeSessionStorage` called on `___construct` method, but `Session/Storage/Handler/RedisSessionHandler` set `ttl` property on his `__construct`, called before `NativeSessionStorage::__construct`.

**How to reproduce** 
 
```php
use Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage;

ini_set('session.gc_maxlifetime',  60); // set session.gc_maxlifetime to 60

$handler = new RedisSessionHandler($predis); // $this->ttl = 60;

$storage = new NativeSessionStorage(['gc_maxlifetime' => 360], $handler); // set session.gc_maxlifetime = 360

$session = new Session($storage);
$session->start();
$session->set('uid', 1); // set expire on redis to 60
```

**Possible Solution**  
```php
// Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler;
class RedisSessionHandler extends AbstractSessionHandler
{
    private $redis;
    /**
     * @var string Key prefix for shared environments
     */
    private $prefix;
    /**
     * @var int Time to live in seconds
     */
    private $ttl;
    /**
     * List of available options:
     *  * prefix: The prefix to use for the keys in order to avoid collision on the Redis server
     *  * ttl: The time to live in seconds.
     *
     * @param \Redis|\RedisArray|\RedisCluster|\Predis\ClientInterface|RedisProxy|RedisClusterProxy $redis
     *
     * @throws \InvalidArgumentException When unsupported client or options are passed
     */
    public function __construct($redis, array $options = [])
    {
       //...
        $this->redis = $redis;
        $this->prefix = $options['prefix'] ?? 'sf_s';
        // $this->ttl = $options['ttl'] ?? (int) ini_get('session.gc_maxlifetime');
        $this->ttl = $options['ttl'] ?? 0;
    }
    // ...
    /**
     * {@inheritdoc}
     */
    protected function doWrite($sessionId, $data): bool
    {
       $ttl = $this->ttl > 0?  $this->ttl : (int) ini_get('session.gc_maxlifetime');
        $result = $this->redis->setEx($this->prefix.$sessionId, $ttl, $data);
        return $result && !$result instanceof ErrorInterface;
    }
    // ...
}

### PR DESCRIPTION
**Pull request by rafaeltovar**
| Q             | A
| ------------- | ---
| Branch?       | master / 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no
| Tickets       | Fix #34659 
| License       | MIT

If option `ttl` was not defined in RedisSessionHandler, this got the default `session.gc_maxlifetime`. With this fixed, RedisSessionHandler get the currently `session.gc_maxlifetime`.

### CODE REVIEW

**Review by nvdbeek — APPROVED** [review]

File: src/Symfony/Component/HttpFoundation/Session/Storage/Handler/RedisSessionHandler.php [hunk 1]
```diff
@@ -63,7 +63,15 @@ public function __construct($redis, array $options = [])
...
-        $this->ttl = $options['ttl'] ?? (int) ini_get('session.gc_maxlifetime');
+        $this->ttl = $options['ttl'] ?? null;
+    }
+
+    /**
+     * {@inheritdoc}
+     */
+    private function getTtl(): int
+    {
+        return $this->ttl ?? ini_get('session.gc_maxlifetime');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Session/Storage/Handler/RedisSessionHandler.php]: let's inline this, no need for the method
we'd rther use `(int) ($options['ttl'] ?? ini_get('session.gc_maxlifetime'))` btw

Comment (rafaeltovar) [reply src/Symfony/Component/HttpFoundation/Session/Storage/Handler/RedisSessionHandler.php]: Are you reason with the type (int), and if you prefer inline, i dont have any problem with.

**Comment by rafaeltovar** [comment]
@nicolas-grekas is it ok?

**Review by nicolas-grekas — APPROVED** [review]
(for 4.4)

**Comment by nicolas-grekas** [comment]
Thank you @rafaeltovar.

**Comment by rafaeltovar** [comment]
You're welcome @nicolas-grekas :)
