### PR TITLE
[ErrorHandler][FrameworkBundle] better error messages in failing tests

### LINKED ISSUE #32752: Better error messages in failing tests
**Description**  
Recently, when running some PHPUnit tests in a CI service, I saw these failing tests:

```
1) App\Tests\Controller\SomeControllerTest::testSomething with data set #0 ('...', '..', '...')
Failed asserting that the Response has header "Content-Type" with value "application/pdf".
```

I spent some time debugging the problem because I recently fixed this feature and I knew it worked on my local computer, on the server, etc. So, why was it failing only in the CI service? I had to SSH-login into it, debug things manually, etc. At the end, a simple `dd($this->client->getResponse())` showed the real problem:

```
<title>An exception has been thrown during the rendering of a template
("file_get_contents(/home/circleci/project/public/build/some-file.css):
failed to open stream: No such file or directory"). (500 Internal Server Error)</title>
```

As you can see, the Symfony exception message is perfect and tells you the problem instantly .. while the PHPUnit error message only confuses you.

**Possible solution**

All these would have been solved if PHPUnit failing tests showed the real exception message from Symfony. Could we add that to the error messages shown by PHPUnit? Thanks!

### PR DESCRIPTION
**Pull request by guillbdx**
| Q             | A
| ------------- | ---
| Branch?       | master for features
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #32752 
| License       | MIT
| Doc PR        | 

Purpose of this PR is to enhance tests by giving a way to report an exception that occured during the processing of the request.

The ErrorHandler will add an X-Debug-Exception, and the assertThat() method of WebTestCase will throw an exception if this header exists and status code is 5xx.

In practice, this adds the "Caused by" section in this example:

```
Time: 374 ms, Memory: 20.00 MB

There was 1 failure:

1) App\Tests\Controller\HomeControllerTest::testC
Failed asserting that the Response has header "Content-Type" with value "application/json".

/srv/symfony/src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php:132
/srv/symfony/src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php:66
/srv/blog/tests/Controller/HomeControllerTest.php:29

Caused by
Exception: This a test exception. in /the/file.php:139
Stack trace:
[...]
```

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php [hunk 1]
```diff
@@ -58,4 +59,18 @@ protected static function createClient(array $options = [], array $server = [])
 
         return self::getClient($client);
     }
+
+    /**
+     * @throws \Exception
+     */
+    public static function assertThat($value, $constraint, $message = ''): void
```
Comment (guillbdx) [inline src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php]: Not sure if I should type `$onstraint` and `$message`, for BC reasons, because they are typed starting from PHPUnit 7.

File: src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php [hunk 2]
```diff
@@ -66,9 +66,12 @@ public function __construct($debug = false, string $charset = null, $fileLinkFor
      */
     public function render(\Throwable $exception): FlattenException
     {
-        $exception = FlattenException::createFromThrowable($exception, null, [
-            'Content-Type' => 'text/html; charset='.$this->charset,
-        ]);
+        $headers = ['Content-Type' => 'text/html; charset='.$this->charset];
+        if (\is_bool($this->debug) ? $this->debug : ($this->debug)($exception)) {
+            $headers['X-Debug-Exception'] = $exception->getMessage();
```
Comment (guillbdx) [inline src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php]: Another option would be to add X-Debug-Exception header only for 5xx exceptions (instead of any kind of exception).

File: src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php [hunk 3]
```diff
@@ -124,6 +126,19 @@ public static function assertRouteSame($expectedRoute, array $parameters = [], s
         self::assertThat(self::getRequest(), $constraint, $message);
     }
 
+    public static function assertThatForResponse(Response $response, Constraint $constraint, string $message = ''): void
+    {
+        try {
+            self::assertThat($response, $constraint, $message);
+        } catch (ExpectationFailedException $exception) {
+            if ($response->headers->has('X-Debug-Exception')) {
+                throw new \Exception($response->headers->get('X-Debug-Exception'));
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: I would expect an `ExpectationFailedException` to be thrown.
we should also preserve the previous exception.
and we could merge the previous and the `X-Debug-Exception` message.

Comment (guillbdx) [reply src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: Ok, done. I create a new `ExpectationFailedException` (not possible to just re set the message of an existing one) with merged messages.

File: src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md [hunk 4]
```diff
@@ -13,6 +13,7 @@ CHANGELOG
  * The `TemplateController` now accepts context argument
  * Deprecated *not* setting the "framework.router.utf8" configuration option as it will default to `true` in Symfony 6.0
  * Added tag `routing.expression_language_function` to define functions available in route conditions
+ * Added `assertThatForResponse` method to `BrowserKitAssertionsTrait` to throw an exception in test case on server exception.
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md]: because `assertThatForResponse` might be too low level:
- Made `BrowserKitAssertionsTrait` report the original error message in case of a failure

File: src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php [hunk 5]
```diff
@@ -124,6 +126,22 @@ public static function assertRouteSame($expectedRoute, array $parameters = [], s
         self::assertThat(self::getRequest(), $constraint, $message);
     }
 
+    public static function assertThatForResponse(Response $response, Constraint $constraint, string $message = ''): void
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: no need for the first argument:
`$response = self::getResponse();`

File: src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php [hunk 6]
```diff
@@ -124,6 +126,22 @@ public static function assertRouteSame($expectedRoute, array $parameters = [], s
...
+    {
+        try {
+            self::assertThat($response, $constraint, $message);
+        } catch (ExpectationFailedException $exception) {
+            if ($serverExceptionMessage = $response->headers->get('X-Debug-Exception')) {
+                $exception = new ExpectationFailedException(
+                    $exception->getMessage().PHP_EOL.'Server Exception: '.$serverExceptionMessage,
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: I fear that changing the message might break existing test suites that expect a specific message.
Can you try this? How does it look like when a test fails?
```php
$exception->__construct($exception->getMessage(), $exception->getComparisonFailure(), new \Exception($serverExceptionMessage));
```

Comment (guillbdx) [reply src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: That produces:

`Time: 374 ms, Memory: 20.00 MB

There was 1 failure:

1) App\Tests\Controller\HomeControllerTest::testC
Failed asserting that the Response has header "Content-Type" with value "application/json".

/srv/symfony/src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php:132
/srv/symfony/src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php:66
/srv/blog/tests/Controller/HomeControllerTest.php:29

Caused by
Exception: This a test exception. in /srv/symfony/src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php:139
Stack trace:
#0 /srv/symfony/src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php(66): Symfony\Bundle\FrameworkBundle\Test\WebTestCase::assertThatForResponse(Object(Symfony\Component\HttpFoundation\Test\Constraint\ResponseHeaderSame), '')
#1 /srv/blog/tests/Controller/HomeControllerTest.php(29): Symfony\Bundle\FrameworkBundle\Test\WebTestCase::assertResponseHeaderSame('Content-Type', 'application/jso...')
#2 /srv/blog/bin/.phpunit/phpunit-7.5-0/src/Framework/TestCase.php(1155): App\Tests\Controller\HomeControllerTest->testC()
etc...

File: src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md (hunk 4 above)
Comment (guillbdx) [reply src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md]: Done.

File: src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php (hunk 6 above)
Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: Great, that looks nice!

File: src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php [hunk 7]
```diff
@@ -124,6 +126,19 @@ public static function assertRouteSame($expectedRoute, array $parameters = [], s
         self::assertThat(self::getRequest(), $constraint, $message);
     }
 
+    public static function assertThatForResponse(Constraint $constraint, string $message = ''): void
+    {
+        try {
+            self::assertThat(self::getResponse(), $constraint, $message);
+        } catch (ExpectationFailedException $exception) {
+            if ($serverExceptionMessage = self::getResponse()->headers->get('X-Debug-Exception')) {
+                $exception->__construct($exception->getMessage(), $exception->getComparisonFailure(), new \Exception($serverExceptionMessage));
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: so, let's improve this a bit with an ErrorException now, and let ErrorHandler report the file and the line too, to populate ErrorException's constructor with file+line info.

File: src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php (hunk 5 above)
Comment (guillbdx) [reply src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: Done.

File: src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php (hunk 7 above)
Comment (guillbdx) [reply src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: Updated.

File: src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php [hunk 8]
```diff
@@ -124,6 +126,33 @@ public static function assertRouteSame($expectedRoute, array $parameters = [], s
...
 
+    public static function assertThatForResponse(Constraint $constraint, string $message = ''): void
+    {
+        try {
+            self::assertThat(self::getResponse(), $constraint, $message);
+        } catch (ExpectationFailedException $exception) {
+            if (($serverExceptionMessage = self::getResponse()->headers->get('X-Debug-Exception'))
+                && ($serverExceptionFile = self::getResponse()->headers->get('X-Debug-Exception-File'))) {
+
+                $serverExceptionFile = explode(':', $serverExceptionFile);
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: this should split at the last occurrence of a `:` - but here this is the first

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: oh, nevermind: since we expected the string to be urlencoded, there can be no previous `:`

File: src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php [hunk 9]
```diff
@@ -124,6 +126,33 @@ public static function assertRouteSame($expectedRoute, array $parameters = [], s
...
+
+                $exception->__construct(
+                    $exception->getMessage(),
+                    $exception->getComparisonFailure(),
+                    new \ErrorException(
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: on one line please

File: src/Symfony/Component/ErrorHandler/CHANGELOG.md [hunk 10]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+5.1.0
+-----
+
+ * The `HtmlErrorRenderer` and `SerializerErrorRenderer` add a `X-Debug-Exception` header with the exception message in debug mode.
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ErrorHandler/CHANGELOG.md]: an `X-Debug-Exception` (missing "n")

File: src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php (hunk 9 above)
Comment (guillbdx) [reply src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: Done.

File: src/Symfony/Component/ErrorHandler/CHANGELOG.md (hunk 10 above)
Comment (guillbdx) [reply src/Symfony/Component/ErrorHandler/CHANGELOG.md]: Fixed.

**Review by nicolas-grekas — APPROVED** [review]
Cool! No more blind errors when using this testing API \o/

File: src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php [hunk 11]
```diff
@@ -124,6 +126,21 @@ public static function assertRouteSame($expectedRoute, array $parameters = [], s
...
 
+    public static function assertThatForResponse(Constraint $constraint, string $message = ''): void
+    {
+        try {
+            self::assertThat(self::getResponse(), $constraint, $message);
+        } catch (ExpectationFailedException $exception) {
+            if (($serverExceptionMessage = self::getResponse()->headers->get('X-Debug-Exception'))
+                && ($serverExceptionFile = self::getResponse()->headers->get('X-Debug-Exception-File'))) {
+                $serverExceptionFile = explode(':', $serverExceptionFile);
+                $exception->__construct($exception->getMessage(), $exception->getComparisonFailure(), new \ErrorException(rawurldecode($serverExceptionMessage), 0, 1, rawurldecode($serverExceptionFile[0]), $serverExceptionFile[1]));
```
Comment (yceruto) [inline src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: I wonder if it's correct to override the previous exceptions and change the stacktrace order... at least we should pass the `$exception->getPrevious()` to the new `\ErrorException()` instance to keep the history, but I still think this new exception should be on top.

File: src/Symfony/Component/ErrorHandler/CHANGELOG.md [hunk 12]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+5.1.0
+-----
+
+ * The `HtmlErrorRenderer` and `SerializerErrorRenderer` add an `X-Debug-Exception` header with the exception message in debug mode.
```
Comment (yceruto) [inline src/Symfony/Component/ErrorHandler/CHANGELOG.md]: missing `X-Debug-Exception-File` mention

**Review by yceruto — COMMENTED** [review]
I added some comments, thank you!

File: src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php (hunk 11 above)
Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: I cannot be on top: that be a BC break, and that'd change the expectations ppl have when they pass the $message argument.
Also logically, this is the cirrect order: the previous is the nested one.

Comment (yceruto) [reply src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: or merged with actual.

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: That'd also be a BC break.
I think the current code is what produces the best experience, see example in the description.
We're not building a design here, but a reporting experience.

Comment (yceruto) [reply src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: at least shouldn't we pass the `$exception->getPrevious()` to the new \ErrorException() instance to keep the previous stacktrace?

Comment (yceruto) [reply src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: I'm refering to the "Cause by" Stack trace, which is not in the current description `[...]`. not sure how it look.

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/Test/BrowserKitAssertionsTrait.php]: Oh, but this is a "remote" process - how would you forward the stack from the ErrorHandler component to this one? It looks to heavy for a header to me...

File: src/Symfony/Component/ErrorHandler/CHANGELOG.md (hunk 12 above)
Comment (guillbdx) [reply src/Symfony/Component/ErrorHandler/CHANGELOG.md]: Done.

**Review by yceruto — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @guillbdx.

**Comment by sstok** [comment]
Nice! This was the one thing missing from the new testing assertions. Thanks for working on this.

**Comment by eng1neer** [comment]
I'm getting an nginx error caused by a too large X-Debug-Exception header (`upstream sent too big header while reading response header from upstream`). This happens with a moderately large exception text (few kilobytes) and default nginx fastcgi buffer size settings. Is there any way to disable the X-Debug-Exception header population without disabling Symfony's debug mode altogether?

**Comment by derrabus** [comment]
Hello @eng1neer and thank you for reaching out.

This tracker is meant for tracking bugs and feature requests. If you are looking for support, you'll get faster responses by using one of our official support channels:

* StackOverflow: https://stackoverflow.com/questions/tagged/symfony
* Slack: https://symfony.com/slack

See https://symfony.com/support for more support options.

**Comment by eng1neer** [comment]
Hey, @derrabus thanks for taking the time to flag my message as off-topic.

I would argue that this is actually a bug. Stuffing data of an arbitrary length into HTTP headers is a bad idea. Most of the web servers impose a limit on the amount of data that can be transmitted in HTTP headers and this limit is not too big (4-8KB for Apache or Nginx). You can easily exceed it with a few kilobytes of text in the exception message which leads to an unexpected error page generated by the webserver.

There should be other, more appropriate ways to pass exception information in tests that will not intervene with the usual development workflow.

**Comment by derrabus** [comment]
@eng1neer All right then, please file a bug report.
