### PR TITLE
[DependencyInjection][Translator] Silent deprecation triggered by libxml_disable_entity_loader

### LINKED ISSUE #39040: Cache:clear giving XML parsing issues
**Symfony version(s) affected**: 4.4.16

**Description**  
XML Parsing issue when running cache:clear

**How to reproduce**  
The problem happens when executing the cache:clear command. Both when it's trigger automatically after a composer install/update or when triggered manually

Environment: Docker container running PHP 7.4 and Symfony 4.4.16

When running composer install --no-scripts and then subsequently running php bin/console cache:clear -v ... I get the following:

```
root@5c1f66038bd0:/var/www# php bin/console cache:clear -v

 // Clearing the cache for the dev environment with debug true

 // Clearing outdated warmup directory...

 // Cache is fresh.

 // Warming up optional cache...


In XliffFileLoader.php line 61:
                                                                                                                              
  [Symfony\Component\Translation\Exception\InvalidResourceException]                                                          
  Invalid resource provided: "/var/www/vendor/symfony/validator/Resources/translations/validators.en.xlf"; Errors: [ERROR 15  
  49] failed to load external entity "file:////var/www/vendor/symfony/translation/Util/../Resources/schemas/xml.xsd" (in n/a  
   - line 0, column 0)                                                                                                        
  [ERROR 3084] Element '{http://www.w3.org/2001/XMLSchema}import': Failed to locate a schema at location 'file:////var/www/v  
  endor/symfony/translation/Util/../Resources/schemas/xml.xsd'. Skipping the import. (in in_memory_buffer - line 33, column   
  0)                                                                                                                          
  [ERROR 3004] attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}lang' does n  
  ot resolve to a(n) attribute declaration. (in in_memory_buffer - line 1661, column 0)                                       
  [ERROR 3004] attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}space' does   
  not resolve to a(n) attribute declaration. (in in_memory_buffer - line 1676, column 0)                                      
  [ERROR 3004] attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}lang' does n  
  ot resolve to a(n) attribute declaration. (in in_memory_buffer - line 1770, column 0)                                       
  [ERROR 3004] attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}space' does   
  not resolve to a(n) attribute declaration. (in in_memory_buffer - line 1879, column 0)                                      
  [ERROR 3004] attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}space' does   
  not resolve to a(n) attribute declaration. (in in_memory_buffer - line 1925, column 0)                                      
  [ERROR 3004] attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}lang' does n  
  ot resolve to a(n) attribute declaration. (in in_memory_buffer - line 1964, column 0)                                       
  [ERROR 3004] attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}lang' does n  
  ot resolve to a(n) attribute declaration. (in in_memory_buffer - line 1987, column 0)                                       
  [ERROR 3004] attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}lang' does n  
  ot resolve to a(n) attribute declaration. (in in_memory_buffer - line 2013, column 0)                                       
  [ERROR 3004] attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}lang' does n  
  ot resolve to a(n) attribute declaration. (in in_memory_buffer - line 2053, column 0)                                       
  [ERROR 3004] attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}space' does   
  not resolve to a(n) attribute declaration. (in in_memory_buffer - line 2056, column 0)                                      
                                                                                                                              

Exception trace:
  at /var/www/vendor/symfony/translation/Loader/XliffFileLoader.php:61
 Symfony\Component\Translation\Loader\XliffFileLoader->extract() at /var/www/vendor/symfony/translation/Loader/XliffFileLoader.
php:42
 Symfony\Component\Translation\Loader\XliffFileLoader->load() at /var/www/vendor/symfony/translation/Translator.php:437
 Symfony\Component\Translation\Translator->doLoadCatalogue() at /var/www/vendor/symfony/framework-bundle/Translation/Translator
.php:133
 Symfony\Bundle\FrameworkBundle\Translation\Translator->doLoadCatalogue() at /var/www/vendor/symfony/translation/Translator.php
:329
 Symfony\Component\Translation\Translator->initializeCatalogue() at /var/www/vendor/symfony/framework-bundle/Translation/Transl
ator.php:125
 Symfony\Bundle\FrameworkBundle\Translation\Translator->initializeCatalogue() at /var/www/vendor/symfony/translation/Translator
.php:363
 Symfony\Component\Translation\Translator->dumpCatalogue() at /var/www/vendor/symfony/translation/Translator.php:348
 Symfony\Component\Translation\Translator->Symfony\Component\Translation\{closure}() at /var/www/vendor/symfony/config/Resource
CheckerConfigCacheFactory.php:43
 Symfony\Component\Config\ResourceCheckerConfigCacheFactory->cache() at /var/www/vendor/symfony/translation/Translator.php:349
 Symfony\Component\Translation\Translator->initializeCacheCatalogue() at /var/www/vendor/symfony/translation/Translator.php:317
 Symfony\Component\Translation\Translator->loadCatalogue() at /var/www/vendor/symfony/framework-bundle/Translation/Translator.p
hp:107
 Symfony\Bundle\FrameworkBundle\Translation\Translator->warmUp() at /var/www/vendor/symfony/translation/DataCollectorTranslator
.php:110
 Symfony\Component\Translation\DataCollectorTranslator->warmUp() at /var/www/vendor/symfony/framework-bundle/CacheWarmer/Transl
ationsCacheWarmer.php:46
 Symfony\Bundle\FrameworkBundle\CacheWarmer\TranslationsCacheWarmer->warmUp() at /var/www/vendor/symfony/http-kernel/CacheWarme
r/CacheWarmerAggregate.php:97
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at /var/www/vendor/symfony/framework-bundle/Command/Ca
cheClearCommand.php:120
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /var/www/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/vendor/symfony/console/Application.php:1027
 Symfony\Component\Console\Application->doRunCommand() at /var/www/vendor/symfony/framework-bundle/Console/Application.php:97
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /var/www/vendor/symfony/framework-bundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /var/www/bin/console:42```

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39040
| License       | MIT
| Doc PR        | -

The XML entity loader is disabled by default since libxml 2.9
But, since PHP 8.0, calling the method `libxml_disable_entity_loader` triggers a deprecation which has been solved in symfony by calling `libxml_disable_entity_loader` only for libxml < 2.9

The issue is, some dependencies, enable the entity loader and does not restore the initial state afterward, leading to exceptions triggered by Symfony iteself.

In previous versions symfony was resilient by disabling the flag before working, which is not the case anymore to avoid the deprecation.

This PR restore the resiliency of Symfony for PHP < 8.0, which is not yet deprecated.

But we have no way to check the status of the entity loader without triggering a deprecation with Symfony 8.

### CODE REVIEW

**Comment by stof** [comment]
could we suffer from issues on PHP 8 due to other libraries changing such global state too ? Or is PHP 8 turning that into a no-op ?

**Comment by jderusse** [comment]
@stof I don't think so, we will suffer from the same issue. 

a solution could be to implement a method by our self that check the status of the entity loader and use this instead of checking the version.
note: `libxml_disable_entity_loader` is used in 5 components

**Comment by derrabus** [comment]
> could we suffer from issues on PHP 8 due to other libraries changing such global state too ?

Yes, this change only buys us some time. The main problem is that php 8 triggers a seprecation without offering us an alternative.

> Or is PHP 8 turning that into a no-op ?

As far as I understood it, the functionality is the same.

@jderusse The PR title tells quite the opposite of what this PR is doing. 😉

**Comment by stof** [comment]
> Yes, this change only buys us some time. The main problem is that php 8 triggers a seprecation without offering us an alternative.

Then this should be reported to PHP *before* the release of PHP 8. Deprecating an API without an alternative is not OK.

**Comment by jderusse** [comment]
> > Yes, this change only buys us some time. The main problem is that php 8 triggers a seprecation without offering us an alternative.
> 
> Then this should be reported to PHP _before_ the release of PHP 8. Deprecating an API without an alternative is not OK.

This is deprecated, because nobody should call it in PHP >= 8.
BUT if somebody call it, you have to revert the call, and you can't do it without triggering a deprecation.

**Comment by stof** [comment]
> This is deprecated, because nobody should call it in PHP >= 8.
> BUT if somebody call it, you have to revert the call, and you can't do it without triggering a deprecation.

That's precisely the issue. As it is deprecated without being a no-op, it still affects the global state for everyone. And so shared libraries (which cannot know what else is running in the project) cannot assume the global state and so are forced to keep calling the deprecated API. And that makes the deprecation warning an issue.
In practice, Symfony on PHP 8 is still not reliably working even after this PR, because it assumes that no other code is using the deprecated API.

File: src/Symfony/Component/Config/Tests/Util/XmlUtilsTest.php [hunk 1]
```diff
@@ -221,7 +221,7 @@ public function testLoadWrongEmptyXMLWithErrorHandler()
             error_reporting($errorReporting);
         }
 
-        if (\LIBXML_VERSION < 20900) {
```
Comment (jderusse) [inline src/Symfony/Component/Config/Tests/Util/XmlUtilsTest.php]: This is wrong, we should check the version of the LIB when disabling the entity loader (calling with `true`)

same below

**Comment by jderusse** [comment]
Bug opened https://bugs.php.net/bug.php?id=80357

**Review by derrabus — APPROVED** [review]
I'm okay with the change because it fixes the regression for now. We can iterate further when we have feedback from PHP.

**Comment by derrabus** [comment]
> Bug opened https://bugs.php.net/bug.php?id=80357

Thank you. 😃

**Comment by jderusse** [comment]
I changed the patch to 

1. let previous code about `libxml_disable_entity_loader(true)` 

Disabling entity loaded is not needed sin libXml 2.9 (this is the reason on the deprecation in PHP 8 by the way). 
We don't have to disable it on our side (whether or not it's previously disabled, it won't changed our code).

2. Silent deprecation triggered by `libxml_disable_entity_loader(false)`

`FALSE` is default value, and Symfony need it (cf #39040). Given we can't do it without triggering a deprecation we shoud silent it, as suggested in  https://bugs.php.net/bug.php?id=80357

3. Stop calling `libxml_disable_entity_loader(false)` after PHP 9

Because the method is deprecated in 8.0 and we are still calling it with `@` sign, we should prevent calling it afterward.

**Comment by derrabus** [comment]
So, it's silencing now according to the feedback we've received? Well okay, let's silence the error then.

File: src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php [hunk 2]
```diff
@@ -634,10 +634,10 @@ public function validateSchema(\DOMDocument $dom)
 EOF
         ;
 
-        if (\LIBXML_VERSION < 20900) {
-            $disableEntities = libxml_disable_entity_loader(false);
+        if (\PHP_VERSION_ID < 90000) {
```
Comment (derrabus) [inline src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php]: We don't know anything about a potential php 9. I'd either remove the check completely or use `function_exists()` instead.

**Review by derrabus — CHANGES_REQUESTED** [review]

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Our deprecation error handler still triggers during tests if the deprecation is silenced. :-(

**Comment by jderusse** [comment]
I don't know if PHP 8 will fix the issue, I the meantime, I suggest this patch that check if the entity loader is disabled by trying to validate a wellknown document

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
PHP won't fix the issue as PHP 8 is now released. Let's merge this one then.

**Comment by fabpot** [comment]
Thank you @jderusse.

**Comment by JarJak** [comment]
There may be more places that require a fix, i.e. 
- https://github.com/symfony/config/blob/5.x/Util/XmlUtils.php#L55
- https://github.com/symfony/dom-crawler/blob/5.x/Crawler.php#L233

**Comment by jderusse** [comment]
These 2 lines are about disabling the `entity_loader` which is not needed, because disabled by default since LIBXML_VERSION 2.9

This PR is about enabling the `entity_loader` in case somebody disabled it.
