### PR TITLE
[HttpFoundation][HttpKernel] Configure `session.cookie_secure` earlier

### LINKED ISSUE #40221: In auto mode, `cookie_secure` may not be set properly in a secure environment if session starts too soon
**Symfony version(s) affected**: 4.4.19

**Description**  

Recently I stumbled upon an issue that PHP isn't writing my cookie as "secure" in the output even when I
1. am accessing the website through HTTPS;
2. have `session.cookie_secure` explicitly set to "On" in `php.ini`, and 
3. have `cookie_secure` set to `auto` in Symfony 4.4 (which is the default).

I found this weird, because
1. this seems to only affect the PHP session ID cookie but not those written by the `sendHeaders()` method in Symfony's `Response` object, so obviously Symfony knows it is a secure connection,
2. this doesn't happens all time - in my setup it only affects the frontend but not the backend, and 
3. the problem goes away if I explicitly set `cookie_secure` to `true` in `framework.yaml`.

After several hours of debugging, I have tracked down the cause. Here's how it happens:

1. When `NativeSessionStorage` is created, it [calls ini_set() to replace the session-related configurations with those defined in the framework config](https://github.com/symfony/http-foundation/blob/c771f3befa0973850d4a55984eef665ece4e1876/Session/Storage/NativeSessionStorage.php#L392). The values are written as-is, so when `cookie_secure` is set to `auto` in `framework.yaml`, this `auto` will be passed to `ini_set`. Here's the problem - `auto` is not a valid value for this configuration, and will probably be treated as `Off` or `False`. Which is why having `session.cookie_secure` set to "On" in `php.ini` won't help in my situation.
2. Fortunately, this invalid value `auto` normally won't stay forever. The problem is fixed by `Symfony\Component\HttpKernel\EventListener\SessionListener`, [which is activated when the framework's `cookie_secure` is set to `auto`](https://github.com/symfony/symfony/blob/c1c20860e51620e258dc0787c9e85e633ad4e9a8/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L938). `SessionListener` checks if the request is a secure one and if yes, it [sets the `cookie_secure` PHP option to true, thus overriding the previous incorrect value](https://github.com/symfony/http-kernel/blob/a3050e057bf581a50f5af755b5cb841ff1feb9e7/EventListener/SessionListener.php#L47) that will be intepretated as `false`.

Here is the tricky part. The reason the session ID cookie isn't properly written as `secure` even when the website is accessed through HTTPS is because in the frontend, I have an Authenticator that checks for a specific session key in the [`supports` method](https://github.com/symfony/symfony/blob/6ae59a9a171695ddef5294898681c060e8c1f3fe/src/Symfony/Component/Security/Guard/AuthenticatorInterface.php#L42). This method is executed so early in the request cycle such that the session is started before `SessionListener` is run. When this happens, it is too late for `SessionListener` to set the `cookie_secure` PHP option to `true` because [NativeSessionStorage's setOption() will exit immediately if the session has been started](https://github.com/symfony/http-foundation/blob/c771f3befa0973850d4a55984eef665ece4e1876/Session/Storage/NativeSessionStorage.php#L368). Now the `auto` value will stay till the end, which I believe will be treated as `false` by PHP, so the PHPSESSID's cookie will not have the `secure` attribute.

I don't see any warning that one should not access the session in the guard authenticator's `supports()` method. In fact I can find suggestion of ["only return true in supports() if the user is on the correct URL and if that session key exists"](https://symfonycasts.com/screencast/symfony-security) in the comment section of a SymfonyCasts page, which is exactly what I was doing (the website I work on contains a frontend and backend which operate with different authenticators, and I need a bridge between them, thus the need for checking a particular session value). So I believe I am not doing something unwise.

I understand that I may have stumbled upon an edge case, and probably not much people will be affected by this. Also it's not difficult to work around this problem, I just need to defer the session checking until `getUser()` is called. Or I can just explicitly set `cookie_secure` to `true` to avoid this glitch. But since the consequence is security related (`cookie_secure` flag is not turned on even when it should), I think it would be better for me to report this issue anyway and mark it as a bug report first and let your team decide what to do with it.

Thank you!

---

## Update 19 Feb

After some more tests, it looks like the problem is probably a more wide-spreaded one. `session.cookie_secure` isn't set properly (i.e. stays in "auto") even for the following controller code in a newly set up Symfony 4.4 and 5.2 project:

```php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

class MainController
{
    private $session;

    public function __construct(SessionInterface $session)
    {
        $this->session = $session;
    }

    /**
     * @Route("/")
     */
    public function index(): Response
    {
        $this->session->set('foo', 'bar');

        return new Response(ini_get('session.cookie_secure'));
    }
}
```

### PR DESCRIPTION
**Pull request by tamcy**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40221
| License       | MIT
| Doc PR        | N/A

This PR does what @stof had suggested in #40221, allow me to quote him directly:

> 1. avoid setting auto as a value for the ini setting in the NativeSessionStorage initialization
> 2. ensuring that SessionListener resolves the auto value by the time the SessionListener runs, and not by the time the getSession() method is called in the Request session factory callback

### CODE REVIEW

File: src/Symfony/Component/HttpKernel/EventListener/SessionListener.php [hunk 1]
```diff
@@ -33,10 +34,12 @@ public function __construct(ContainerInterface $container)
         $this->container = $container;
     }
 
-    protected function getSession(): ?SessionInterface
+    public function onKernelRequest(GetResponseEvent $event)
```
Comment (jderusse) [inline src/Symfony/Component/HttpKernel/EventListener/SessionListener.php:37]: I don't see how this change fix anything?
In the previous implementation, the `AbstractSessionListener::onKernelRequest` calls the `getSession` method which setup the storage. Doing the same thing in an overriden `onKernelRequest` ends to the same behavior right?

**Review by jderusse — COMMENTED** [review]
I think this PR works in your case because your php.ini file has `cookie_secure=on` and this PR prevent overriding the .ini value with `"auto"`.

But what if your .ini is set to `on` and you call the page with `http` does it removes the `cookie_secure` flag? Or what if the .ini is set to `off` and the page is called with `https` is it re-added?

I believe we should disable the .ini setting when value is `auto` then the SessionListener will re-enabled it if the request is secured.

Are you sure that your Code/EventListener has a lower priority than the `SessionListener` and you are not reading the session before the flag is correctly sets?

Note: In Symfony 5.3, injecting the session in your service will be deprecated and you'll have to use the RequestStack to get a session. So this will not be an issue anymore, as you won't be able to manipulate the session before the SessionListener initialize the storage and inject the session in the request.

File: src/Symfony/Component/HttpKernel/EventListener/SessionListener.php (hunk 1 above)
Comment (stof) [reply src/Symfony/Component/HttpKernel/EventListener/SessionListener.php:37]: @jderusse no it does not. `getSession` is called inside the callable set in `Request::setSessionFactory`, not in `onKernelRequest`

**Comment by tamcy** [comment]
> I think this PR works in your case because your php.ini file has `cookie_secure=on` and this PR prevent overriding the .ini value with `"auto"`.

But 'auto' is not a valid value for this ini setting. Yes, setting `cookie_secure=auto` via ini_set does have the same effect as setting it to false/off/0, but the question is whether this is an intended behavior. For this I agree with @stof that the value 'auto' shouldn't be passed as-is to the session storage.

> But what if your .ini is set to `on` and you call the page with `http` does it removes the `cookie_secure` flag? Or what if the .ini is set to `off` and the page is called with `https` is it re-added?

You are correct that this PR missed the scenario when the page is accessed through http, not https. The code only sets cookie_secure to `true` for https, but didn't set it to `false` for http traffic. In this case the `onKernelRequest` callback could be changed to something like this:

```php
        if ($this->container->has('session_storage')
            && ($storage = $this->container->get('session_storage')) instanceof NativeSessionStorage
            && ($masterRequest = $this->container->get('request_stack')->getMasterRequest())
        ) {
            $storage->setOptions(['cookie_secure' => $masterRequest->isSecure()]);
        }
```

> I believe we should disable the .ini setting when value is auto then the SessionListener will re-enabled it if the request is secured.

Personally I don't have preference on whether the setting is set in one place, or is first disabled then enabled if the traffic in https. But again, I think the value passed to ini_set shouldn't be 'auto'.

> Are you sure that your Code/EventListener has a lower priority than the SessionListener and you are not reading the session before the flag is correctly sets?
> Note: In Symfony 5.3, injecting the session in your service will be deprecated and you'll have to use the RequestStack to get a session. So this will not be an issue anymore, as you won't be able to manipulate the session before the SessionListener initialize the storage and inject the session in the request.

I need to confess that my experience with Symfony internals isn't deep enough for me to guarantee that people will be immune from similar situations. They may still able to register an event listener which accesses the session before SessionListener is called, causing it to fail to properly set the `cookie_secure` flag (actually there might even be a need to tell the developer that the service cannot set the flag properly, given this is a security related thing). But, for my case, what I did was just registering a guard authenticator which accesses session data in the `supports()` method. I didn't change the priority of any of the involved services. And by default the authenticator's `supports()` is called before `SessionListener`.

**Comment by stof** [comment]
> And by default the authenticator's `supports()` is called before `SessionListener`.

no it is not. And that's precisely why this PR will fix the issue by making sure that the `auto` value is resolved by the time `SessionListener` is called (rather than by the time the session is retrieved from the Request object for the first time)

**Comment by tamcy** [comment]
@stof is right. I forgot to update my mind when writing the reply.

The PR has been updated. In this PR,

1. Instead of letting `NativeSessionStorage` to check for this `auto` value in the `cookie_secure` key and act differently, the framework will create another set of options that does not contain the `secure_cookie` option if it is set to `auto`, and the `NativeSessionStorage` will receive this special set of options in the constructor.

2. The `SessionListener` class is updated to set the `cookie_secure` value properly in `onKernelRequest`, no matter the request is secure or not. This fixes the issue in the previous PR that `cookie_secure` won't be set if the request is not secure.

Two related notes:

1. The scope of the issue is actually larger then I anticipated. Just create a new application, [add a simple controller action that accesses the session](https://github.com/tamcy/symfony-secure-cookie-test-4.4/blob/master/src/Controller/MainController.php). The auto secure cookie won't work because of the reason explained by @stof.

2. I have also verifitied that after the PR, user can still "invalidate" the `SessionListener` by creating an event listener that accesses the session with priority equal to or higher than that of `SessionListener` [like this](https://github.com/tamcy/symfony-secure-cookie-test-4.4/blob/master/src/EventListener/NullifyAutoCookieSecureEventListener.php).

**Review by nicolas-grekas — APPROVED** [review]
(implem updated a bit)

**Comment by nicolas-grekas** [comment]
Thank you @tamcy.

**Comment by stof** [comment]
>     2\. I have also verifitied that after the PR, user can still "invalidate" the `SessionListener` by creating an event listener that accesses the session with priority equal to or higher than that of `SessionListener` [like this](https://github.com/tamcy/symfony-secure-cookie-test-4.4/blob/master/src/EventListener/NullifyAutoCookieSecureEventListener.php).

this is fine to me. On future versions where accessing the session as a service is not possible anymore, you won't be able to access the session before it is initialized in the Request by SessionListener (which is also why it runs at priority 100)

**Comment by tamcy** [comment]
@nicolas-grekas Thank you. May I know if it is intentional to use my first pull request, rather than the second one? I ask this because besides the difference in approach, the second PR includes a fix in the `SessionListener` which is missing in the first PR. In the first (merged) PR, the code reads:
```php
        if ($this->container->has('session_storage')
            && ($storage = $this->container->get('session_storage')) instanceof NativeSessionStorage
            && ($masterRequest = $this->container->get('request_stack')->getMasterRequest())
            && $masterRequest->isSecure()
        ) {
            $storage->setOptions(['cookie_secure' => true]);
        }
```

In this code, if the request is not https, the storage option will not be set. Consequently, the default PHP value will be used. If the default ini value is set to On (forcing secure cookie), the cookie will not work in an auto environment. Which is why the the code in the second PR, the code is changed to:

```php
       if ($this->container->has('session_storage')
            && ($storage = $this->container->get('session_storage')) instanceof NativeSessionStorage
            && ($masterRequest = $this->container->get('request_stack')->getMasterRequest())
        ) {
            $storage->setOptions(['cookie_secure' => $masterRequest->isSecure()]);
        }
```

Please advise what could be done. Shall I create another PR for this? Thank you!

**Comment by nicolas-grekas** [comment]
Yes, I reverted that part because I thought it was not desired: the goal here is to upgrade to ssl when possible. Never to downgrade to no-ssl, which is what the change you're mentioning would do to me.

**Comment by tamcy** [comment]
I see, thank you, this makes sense. Do we need a warning to users though? As this kind of downgrade does happen before the patch (the value is always set to "auto" at first, which effectively turns off the secure cookie flag).
