### PR TITLE
[Cache] give 100ms before starting the expiration countdown

### LINKED ISSUE #31573: [symfony/cache] Big time shifting for items with small TTL
**Description**  
Recently we've faced problem with memcached expiry time shifting by +-1 second. This problem corresponds [with fact that there is no resolution clock in memcached](https://github.com/memcached/memcached/issues/307). So if I set cache with expire time 3 seconds, it will be there at least 2. But when I use symfony/cache wrapper, I as a rule get result with less than 2 seconds. And I don't know why yet. One of the reason may be long execution stack, another is that in Memcached there are two ways to set expiration time: in seconds less than seconds in 30 days, and in timestamp. In symfony/cache wrapper, expiry always sets as time() + expiry_seconds (second option) here: `symfony/cache/CacheItem.php:97`.

**How to reproduce**  
put following code inside test.php:
```php
<?php

require_once 'vendor/autoload.php';

use Symfony\Component\Cache\Adapter\MemcachedAdapter;

$m = new Memcached();
$m->addServer('localhost', 11211);

$m->set('test', true, (int)$argv[1]);

$time = 0;
while ($m->get('test')) {
    usleep(100 * 1000);
    $time += 0.1;
    var_dump("Memcached: $time");
}

$cacheClient = MemcachedAdapter::createConnection(['memcached://localhost:11211']);
$cache = new MemcachedAdapter($cacheClient);

$item = $cache->getItem('test');
$item->expiresAfter((int)$argv[1]);
$cache->save($item);

$time = 0;
while ($cache->getItem('test')->isHit()) {
    usleep(100 * 1000);
    $time += 0.1;
    var_dump("Symfony: $time");
}
```

`docker run -p 11211:11211 -d memcached`
`docker run -it --rm --network=host -v $PWD:/src -w /src chialab/php:7.3 php test.php 3`

**Example output**
```
string(14) "Memcached: 0.1"                                                                                                                                             
string(14) "Memcached: 0.2"                                                                                                                                             
string(14) "Memcached: 0.3"                                                                                                                                             
string(14) "Memcached: 0.4"                                                                                                                                             
...                                                                                                                                    
string(14) "Memcached: 2.6"                                                                                                                                             
string(14) "Memcached: 2.7"                                                                                                                                             
string(14) "Memcached: 2.8"                                                                                                                                             
string(12) "Symfony: 0.1"                                                                                                                                               
string(12) "Symfony: 0.2"                                                                                                                                               
string(12) "Symfony: 0.3"                                                                                                                                               
...                                                                                                                                    
string(12) "Symfony: 1.7"                                                                                                                                               
string(12) "Symfony: 1.8"
```

You can run it hundred times and through symfony/cache, cache will not leave at least 2 seconds.

### LINKED ISSUE #33837: Cache stampede prevention fails when calculation time is less than a second
**Symfony version(s) affected**: 4.3.4

**Description**  
When using cache contracts, if the callback that generates the data to cache takes less than a second to run, the stampede prevention logic will never fire.

**How to reproduce**
I'm not quite sure how to demonstrate this as a unit test, but I was able to reproduce it using a console command.  You can see from the output, the stampede protection doesn't start firing until the delay reaches 1 second.

```php
    <?php

    namespace App\Command;

    use Psr\Log\LoggerInterface;
    use Symfony\Component\Cache\Adapter\FilesystemAdapter;
    use Symfony\Component\Console\Command\Command;
    use Symfony\Component\Console\Input\InputInterface;
    use Symfony\Component\Console\Output\OutputInterface;
    use Symfony\Contracts\Cache\ItemInterface;

    class TestStampede extends Command
    {
        protected static $defaultName = 'test:stampede';
        protected $logger;

        public function __construct(LoggerInterface $logger)
        {
            parent::__construct();
            $this->logger = $logger;
        }

        protected function execute(InputInterface $input, OutputInterface $output)
        {
            $cache = new FilesystemAdapter(
                'test',
                0,
                '/tmp/test'
            );

            $cache->setLogger($this->logger);

            foreach ([100000, 500000, 900000, 1000000] as $delay) {
                $this->logger->info('running with a {delay}s delay', [
                    'delay' => sprintf('%0.2f', $delay / 1000000.0)
                ]);

                $key = 'test-' . random_int(1, PHP_INT_MAX);
                for ($x = 0; $x < 1000000; $x++) {
                    $value = $cache->get($key, function (ItemInterface $item) use ($delay) {
                        $item->expiresAfter(15);
                        usleep($delay);
                        return 'test.data';
                    });
                }
            }
        }
    }
```

run with `bin/console -vv test:stampede`

Note that this will push load up on your machine, because we're brute forcing our way in to the stampede protection.

**Possible Solution**  
The easiest way I've found to fix this is to adjust the math that calculates CTIME in `Symfony\Component\Cache\Traits\ContractsTrait`.

Replace

```php
$item->newMetadata[CacheItem::METADATA_CTIME] = $metadata[CacheItem::METADATA_CTIME] = 1000 * (int) ($endTime - $startTime);
```

with

```php
$item->newMetadata[CacheItem::METADATA_CTIME] = $metadata[CacheItem::METADATA_CTIME] = (int) (1000 * ($endTime - $startTime));
```

**Additional context**  
The stampede prevention math in `Symfony\Contacts\Cache\CacheTrait` is where the other half of this bug lives; the `0` value in `$ctime` short-circuits the formula that otherwise works brilliantly.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #31573, Fix #33837
| License       | MIT
| Doc PR        | -

Because the expiration count-down starts immediately after calling `CachItem::expiresAfter(N)`, it's impossible to actually cache items for more than `N-1` seconds.

This PR adds a 0.1s grace period so that backends that have a second-level resolution can store the items for `N` seconds, provided the time between calling `CachItem::expiresAfter(N)` and saving the value to the backend is lower than 0.1s.

This PR also fixes the calculation of the computation time in `ContractsTrait`.

### CODE REVIEW

File: src/Symfony/Component/Cache/Adapter/AbstractAdapter.php [hunk 1]
```diff
@@ -76,15 +76,15 @@ static function ($deferred, $namespace, &$expiredIds) use ($getId) {
                     $key = (string) $key;
                     if (null === $item->expiry) {
                         $ttl = 0 < $item->defaultLifetime ? $item->defaultLifetime : 0;
-                    } elseif (0 >= $ttl = (int) ($item->expiry - $now)) {
+                    } elseif (0 >= $ttl = (int) (0.1 + $item->expiry - $now)) {
```
Comment (javiereguiluz) [inline src/Symfony/Component/Cache/Adapter/AbstractAdapter.php]: This could look like a "magic number" in the future and people won't understand why we use it. We could add a very brief comment explaining "why" ... or we could move this to a self-explanatory private constant (e.g. `self::MINIMUM_CACHE_TTL` or something better).

Comment (nicolas-grekas) [reply src/Symfony/Component/Cache/Adapter/AbstractAdapter.php]: The value is spread in many unrelated adapters, a private constant doesn't work.
I'm not sure this deserves more honestly, `git blame` can tell why if anyone wonders.
