### PR TITLE
[Serializer] Fix configuration of the cache key

### LINKED ISSUE #35574: [Serializer]  Typed property Proxies\__CG__\App\Entity\File::$ must not be accessed before initialization (in __sleep)
**Symfony version(s) affected**: 4.4.2 (PHP 7.4.2)

**Description**  
Bug when normalizing a entity: `Typed property Proxies\__CG__\App\Entity\File::$ must not be accessed before initialization (in __sleep)`

Also, I have no idea what the property `File::$` means or why is it trying to access it...

**How to reproduce**  
No idea

**Possible Solution**  
Modifying `AbstractObjectNormalizer.php:getCacheKey()` to also handle `\Throwable`s:
```php
    private function getCacheKey(?string $format, array $context)
    {
        foreach ($context[self::EXCLUDE_FROM_CACHE_KEY] ?? $this->defaultContext[self::EXCLUDE_FROM_CACHE_KEY] as $key) {
            unset($context[$key]);
        }
        unset($context[self::EXCLUDE_FROM_CACHE_KEY]);
        unset($context['cache_key']); // avoid artificially different keys

        try {
            return md5($format.serialize([
                'context' => $context,
                'ignored' => $this->ignoredAttributes,
                'camelized' => $this->camelizedAttributes,
            ]));
        } catch (\Exception $exception) {
            // The context cannot be serialized, skip the cache
            return false;
        } catch (\Throwable $e) {
            return false; // <-- THIS
        }
    }
```

**Additional context**  
Stack trace:
```
Error:
Typed property Proxies\__CG__\App\Entity\File::$ must not be accessed before initialization (in __sleep)

  at vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:626
  at serialize(array('context' => array('groups' => array('partnership:write'), 'operation_type' => 'item', 'item_operation_name' => 'patch', 'api_allow_update' => true, 'resource_class' => 'App\\Entity\\Partnership', 'input' => null, 'output' => null, 'request_uri' => '/api/partnerships/1', 'uri' => 'http://localhost:8000/api/partnerships/1', 'skip_null_values' => true, 'object_to_populate' => object(Partnership), 'api_denormalize' => true), 'ignored' => array(), 'camelized' => array()))
     (vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:626)
  at Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->getCacheKey('json', array('groups' => array('partnership:write'), 'operation_type' => 'item', 'item_operation_name' => 'patch', 'api_allow_update' => true, 'resource_class' => 'App\\Entity\\Partnership', 'input' => null, 'output' => null, 'request_uri' => '/api/partnerships/1', 'uri' => 'http://localhost:8000/api/partnerships/1', 'skip_null_values' => true, 'object_to_populate' => object(Partnership), 'api_denormalize' => true))
     (vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:327)
  at Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denormalize(array('userTerms' => '/api/files/35993dd1-41b8-4fdb-8350-8fc47f61b41e'), 'App\\Entity\\Partnership', 'json', array('groups' => array('partnership:write'), 'operation_type' => 'item', 'item_operation_name' => 'patch', 'api_allow_update' => true, 'resource_class' => 'App\\Entity\\Partnership', 'input' => null, 'output' => null, 'request_uri' => '/api/partnerships/1', 'uri' => 'http://localhost:8000/api/partnerships/1', 'skip_null_values' => true, 'object_to_populate' => object(Partnership), 'api_denormalize' => true))
     (vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php:222)
  at ApiPlatform\Core\Serializer\AbstractItemNormalizer->denormalize(array('userTerms' => '/api/files/35993dd1-41b8-4fdb-8350-8fc47f61b41e'), 'App\\Entity\\Partnership', 'json', array('groups' => array('partnership:write'), 'operation_type' => 'item', 'item_operation_name' => 'patch', 'api_allow_update' => true, 'resource_class' => 'App\\Entity\\Partnership', 'input' => null, 'output' => null, 'request_uri' => '/api/partnerships/1', 'uri' => 'http://localhost:8000/api/partnerships/1', 'skip_null_values' => true, 'object_to_populate' => object(Partnership), 'api_denormalize' => true))
     (vendor/api-platform/core/src/Serializer/ItemNormalizer.php:69)
  at ApiPlatform\Core\Serializer\ItemNormalizer->denormalize(array('userTerms' => '/api/files/35993dd1-41b8-4fdb-8350-8fc47f61b41e'), 'App\\Entity\\Partnership', 'json', array('groups' => array('partnership:write'), 'operation_type' => 'item', 'item_operation_name' => 'patch', 'api_allow_update' => true, 'resource_class' => 'App\\Entity\\Partnership', 'input' => null, 'output' => null, 'request_uri' => '/api/partnerships/1', 'uri' => 'http://localhost:8000/api/partnerships/1', 'skip_null_values' => true, 'object_to_populate' => object(Partnership)))
     (vendor/symfony/serializer/Serializer.php:191)
  at Symfony\Component\Serializer\Serializer->denormalize(array('userTerms' => '/api/files/35993dd1-41b8-4fdb-8350-8fc47f61b41e'), 'App\\Entity\\Partnership', 'json', array('groups' => array('partnership:write'), 'operation_type' => 'item', 'item_operation_name' => 'patch', 'api_allow_update' => true, 'resource_class' => 'App\\Entity\\Partnership', 'input' => null, 'output' => null, 'request_uri' => '/api/partnerships/1', 'uri' => 'http://localhost:8000/api/partnerships/1', 'skip_null_values' => true, 'object_to_populate' => object(Partnership)))
     (vendor/symfony/serializer/Serializer.php:142)
  at Symfony\Component\Serializer\Serializer->deserialize(array('userTerms' => '/api/files/35993dd1-41b8-4fdb-8350-8fc47f61b41e'), 'App\\Entity\\Partnership', 'json', array('groups' => array('partnership:write'), 'operation_type' => 'item', 'item_operation_name' => 'patch', 'api_allow_update' => true, 'resource_class' => 'App\\Entity\\Partnership', 'input' => null, 'output' => null, 'request_uri' => '/api/partnerships/1', 'uri' => 'http://localhost:8000/api/partnerships/1', 'skip_null_values' => true, 'object_to_populate' => object(Partnership)))
     (vendor/api-platform/core/src/EventListener/DeserializeListener.php:106)
  at ApiPlatform\Core\EventListener\DeserializeListener->onKernelRequest(object(RequestEvent), 'kernel.request', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:126)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(RequestEvent), 'kernel.request', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:264)
  at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(RequestEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:239)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(RequestEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:73)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(RequestEvent), 'kernel.request')
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:168)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(RequestEvent), 'kernel.request')
     (vendor/symfony/http-kernel/HttpKernel.php:122)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:28)              
```

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #35574 doctrine/orm#8030 (partially)
| License       | MIT
| Doc PR        | n/a

Currently, a bug prevents to configure the context keys to exclude from the cache key computation. The value is always replaced in the constructor. This PR fixes the problem.

### CODE REVIEW

**Comment by alanpoulain** [comment]
It's only an issue if the default context for the cache key is changed by a child class and if the constructor is called afterwards, doesn't it?

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 1]
```diff
@@ -359,7 +359,7 @@ public function denormalize($data, $type, $format = null, array $context = [])
             try {
                 $this->setAttributeValue($object, $attribute, $value, $format, $context);
             } catch (InvalidArgumentException $e) {
-                throw new NotNormalizableValueException(sprintf('Failed to denormalize attribute "%s" value for class "%s": %s.', $attribute, $type, $e->getMessage()), $e->getCode(), $e);
+                throw new NotNormalizableValueException(sprintf('Failed to denormalize attribute "%s" value for class "%s": "%s".', $attribute, $type, $e->getMessage()), $e->getCode(), $e);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php:362]: should be reverted, that a false positive - we could even remove the final dot - and use a concat to prevent future false positives

**Comment by nicolas-grekas** [comment]
A test case would be nice if you can.

**Comment by dunglas** [comment]
@alanpoulain it's even the case if you just pass the key to exclude as parameters of the constructor.
@nicolas-grekas test added and exception message fixed

**Comment by fabpot** [comment]
Is this one still relevant? I see that the original issue has been closed as the problem has been fixed in PHP itself IIUC? /cc @dunglas @nicolas-grekas

**Comment by dunglas** [comment]
AFAIK it's still an issue.

**Comment by fabpot** [comment]
@dunglas  Ok, can you rebase so that we can merge?

**Comment by fabpot** [comment]
Thank you @dunglas.
