### PR TITLE
Workaround disabled "var_dump"

### LINKED ISSUE #46881: [HttpClient] and assumption about var_dump with PHP8.x
### Symfony version(s) affected

5.4 & others

### Description

Some production setups set `disable_functions` to include `var_dump` (and `exec`, `shell_exec`, `phpinfo`, etc) for security purposes. This means that `var_dump()` may not be always be callable. This becomes relevant here:

https://github.com/symfony/symfony/blob/26338772ed47afd38d7fa7b53cafd6c8af3aba9c/src/Symfony/Component/HttpClient/HttpClientTrait.php#L123-L126

The most common case is that `on_progress` is not set, so `is_callable('var_dump')` is the most common pattern.

This is a problem from PHP 8.0+ because the behaviour changed for `is_callable('var_dump')` when the function is disabled.

### How to reproduce

```
$ # PHP 7.4
$ php -d'disable_functions=var_dump' -r 'var_export(is_callable("var_dump"));'
true
```

```
$ # PHP 8.0
$ php -d'disable_functions=var_dump' -r 'var_export(is_callable("var_dump"));'
false
```

### Possible Solution

Perhaps switch `var_dump` to something innocuous like `is_int`?

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #46881
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Component/Debug/ErrorHandler.php [hunk 1]
```diff
@@ -355,7 +355,7 @@ public function screamAt($levels, $replace = false)
     private function reRegister(int $prev)
     {
         if ($prev !== $this->thrownErrors | $this->loggedErrors) {
-            $handler = set_error_handler('var_dump');
+            $handler = set_error_handler('is_int');
             $handler = \is_array($handler) ? $handler[0] : null;
             restore_error_handler();
```
Comment (guilliamxavier) [inline src/Symfony/Component/Debug/ErrorHandler.php:360]: If ever `is_int` was called, it would throw an `ArgumentCountError`, so a few questions:
- Is that actually a good thing?
- Are there reasons for not passing `null` here? or e.g. `function () {}`?
- Would it be safer to move up the `restore_{error|exception}_handler();` immediately after the `set_{error|exception}_handler` call, with no operation in-between?
- Should https://github.com/php/php-src/pull/969 be revived?

Comment (nicolas-grekas) [reply src/Symfony/Component/Debug/ErrorHandler.php:360]: > Should https://github.com/php/php-src/pull/969 be revived?

Maybe. For your other questions, they're mostly theoretical at the moment so I wouldn't care much :)
