### PR TITLE
[Cache] Fix undefined array key when tag save fails in AbstractTagAwareAdapter

### LINKED ISSUE #63729: [Cache][AbstractTagAwareAdapter] Undefined array key if failed to save tag
### Symfony version(s) affected

8.0.0

### Description

[This](https://github.com/symfony/symfony/blob/8.1/src/Symfony/Component/Cache/Adapter/AbstractTagAwareAdapter.php#L204C17-L204C85) code returns entries that can't be saved in pipeline (may be Redis failed or something else). 
Finally with Redis Adapter I have got the error on production:
```
ErrorException: Warning: Undefined array key "tagsentity_filter" in /var/www/vendor/symfony/cache/Adapter/AbstractTagAwareAdapter.php:213
Stack trace:
#0 /var/www/vendor/symfony/cache/Traits/AbstractAdapterTrait.php(239): Symfony\Component\Cache\Adapter\AbstractTagAwareAdapter->commit()
```
Looks like it has been failed to save tag, but not values as expected on [this](https://github.com/symfony/symfony/blob/8.1/src/Symfony/Component/Cache/Adapter/AbstractTagAwareAdapter.php#L213) line 

Image

### How to reproduce

Values success to save, but tags - no

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Amoifr**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63729
| License       | MIT

When `doSave()` returns failed IDs, the code in `commit()` assumes all IDs are cache value keys. However, `doSave()` can also return tag IDs (prefixed with `\1tags\1`) when tag persistence fails (e.g., Redis timeout).

Since tags are passed separately via `$addTagData`/`$removeTagData` and not stored in `$values`, accessing `$values[$id]` throws an "Undefined array key" warning.

**The fix:** Check if the ID exists in `$values` before accessing it. If it doesn't exist, it's a failed tag save, which we now log appropriately and skip.

### CODE REVIEW

File: src/Symfony/Component/Cache/Tests/Fixtures/FailingTagFilesystemAdapter.php [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+        $failed = parent::doSave($values, $lifetime, $addTagData, $removeTagData);
+
+        // Simulate tag save failure by returning tag IDs as failed
+        foreach ($addTagData as $tagId => $ids) {
+            $failed[] = $tagId;
+        }
+
+        return $failed;
+    }
+}
```
Comment (stof) [inline src/Symfony/Component/Cache/Tests/Fixtures/FailingTagFilesystemAdapter.php]: please add the final EOL there (probably not returning by fabbot as it disables CS checks in `Fixtures` folders as those might need to match generated files)

Comment (Amoifr) [reply src/Symfony/Component/Cache/Tests/Fixtures/FailingTagFilesystemAdapter.php]: Done! Apparently my keyboard's Enter key was on a coffee break. ☕

**Comment by nicolas-grekas** [comment]
Thank you @Amoifr.
