### PR TITLE
[Validator] bad value on AbstractComparison constructor using array parameter

### LINKED ISSUE #61900: [Validator] Invalid value on AbstractComparison using options array as first parameter
### Symfony version(s) affected

7.4

### Description

When using the legacy constraint constructor parameters (i.e. use an array of options instead of the value), the property `AbstractComparison->value` will be set to the option array instead of the `value` option of the array.

### How to reproduce

```php
(new \Symfony\Component\Validator\Constraints\GreaterThanOrEqual(['value' => 42]))->value; // Will be ['value' => 42] instead of 42
```

### Possible Solution

Set `$value` to null after merging it to with `$options` on `AbstractComparison` constructor

```diff
    public function __construct(mixed $value = null, ?string $propertyPath = null, ?string $message = null, ?array $groups = null, mixed $payload = null, ?array $options = null)
    {
        if (\is_array($value)) {
            trigger_deprecation('symfony/validator', '7.3', 'Passing an array of options to configure the "%s" constraint is deprecated, use named arguments instead.', static::class);

            $options = array_merge($value, $options ?? []);
+           $value = null;
        } elseif (null !== $value) {
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by vincent4vx**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #61900
| License       | MIT

On the AbstractComparison constraint the value parameter is directly used to fill the value property, so when an array of options is used, the value is not correctly extracted.
This change simply let the parent constructor extracts the value option, and fill the property with the correct value.

### CODE REVIEW

**Comment by stof** [comment]
Based on the deprecation message, it seems the change has been done in 7.3, so I doubt 7.4 is the oldest impacted version.

**Comment by vincent4vx** [comment]
This bug has been introduced by this commit : https://github.com/symfony/symfony/commit/ee9112431cc044b9cf92ddb5b5424e0728a69c91
When the statement `$this->value = $value ?? $this->value;` has been added.
Before that (in 7.3), the value is only set by the parent constructor, so by extracting the options array.

File: src/Symfony/Component/Validator/Tests/Constraints/AbstractComparisonTest.php [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+namespace Symfony\Component\Validator\Tests\Constraints;
+
+use PHPUnit\Framework\Attributes\IgnoreDeprecations;
+use PHPUnit\Framework\TestCase;
+use Symfony\Component\Validator\Constraints\AbstractComparison;
+
+class AbstractComparisonTest extends TestCase
+{
+    #[IgnoreDeprecations]
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/Tests/Constraints/AbstractComparisonTest.php:21]: We also need to add it to the legacy group:


```suggestion
    #[IgnoreDeprecations]
    #[Group('legacy')]
```

File: src/Symfony/Component/Validator/Tests/Constraints/AbstractComparisonTest.php [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+ *
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\Validator\Tests\Constraints;
+
+use PHPUnit\Framework\Attributes\IgnoreDeprecations;
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/Tests/Constraints/AbstractComparisonTest.php:15]:
```suggestion
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\Attributes\IgnoreDeprecations;
```

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @vincent4vx.
