### PR TITLE
[Translator] fix handling plural for floating numbers

### LINKED ISSUE #30215: [Translation] Floating number plural broken
**Symfony version(s) affected**: 4.2.3

**Description**  
Decimal number between 1 and 2 produces incorrect plural in English.

**How to reproduce**  
```php

$t = new \Symfony\Component\Translation\Translator('en');

$t->addLoader('array', new \Symfony\Component\Translation\Loader\ArrayLoader());
$t->addResource('array', [
    'liter' => '%count% liter|%count% liters',
], 'en');

echo $t->trans('liter', ['%count%' => 1.5]);

echo "\n";

$t = new \Symfony\Component\Translation\Translator('fr');

$t->addLoader('array', new \Symfony\Component\Translation\Loader\ArrayLoader());
$t->addResource('array', [
    'liter' => '%count% litre|%count% litres',
], 'fr');

echo $t->trans('liter', ['%count%' => 1.5]);
```

It outputs:
```
1.5 liter
1.5 litre
```

It should output:
```
1.5 liters
1.5 litre
```

**Possible Solution**
int typing here should be removed, it's a float, numbers should not be truncated:
https://github.com/symfony/symfony/blob/32aa969dfff52adfc8f8efac8e7cd21b719f9ac0/src/Symfony/Component/Translation/IdentityTranslator.php#L57

**Related to** #16256

### PR DESCRIPTION
**Pull request by kylekatarnls**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #30215
| License       | MIT

### CODE REVIEW

**Review by welcoMattic — APPROVED** [review]

File: src/Symfony/Component/Translation/Tests/TranslatorTest.php [hunk 1]
```diff
@@ -612,6 +612,11 @@ public function getTransChoiceTests()
 
             // Override %count% with a custom value
             ['Il y a quelques pommes', 'one: There is one apple|more: There are %count% apples', 'one: Il y a %count% pomme|more: Il y a quelques pommes', 2, ['%count%' => 'quelques'], 'fr', ''],
+
+            // Floating values
+            // https://github.com/symfony/symfony/issues/30215
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Tests/TranslatorTest.php]: we don't put links to github in the source

**Review by nicolas-grekas — DISMISSED** [review]

File: src/Symfony/Component/Translation/Tests/TranslatorTest.php (hunk 1 above)
Comment (kylekatarnls) [inline src/Symfony/Component/Translation/Tests/TranslatorTest.php]:
```suggestion
```

**Comment by kylekatarnls** [comment]
If I have time this week, I'll also check negative numbers and add tests for them.

✔️ done

**Comment by kylekatarnls** [comment]
Hum, as a first sight, I can't tell how the test output could be different from PHP 7.1 and 8 while 7.4 succeed in between.

**Comment by jderusse** [comment]
> Hum, as a first sight, I can't tell how the test output could be different from PHP 7.1 and 8 while 7.4 succeed in between.

The Symfony test suites are very complexe and does not perform the same thing. ie. One of the tests suite tries each component with the minimal requirements version. Another tries the previous version of the component with dependencies patched with your PR. 
That's why some passed and other failed. You have to make all of theme green ;-)

**Comment by kylekatarnls** [comment]
Depending on the version we either fall into `PluralizationRules.php` or into `TranslatorTrait.php`, I hope we can soon get rid of this duplicated code 😸 Now both are fixed.

**Comment by kylekatarnls** [comment]
AppVeyor failure is clearly unrelated:
```
Fatal error: Interface 'Symfony\Contracts\Service\ResetInterface' not found
```

**Comment by kylekatarnls** [comment]
👋 @nicolas-grekas would you mind to review the new changes `$number = abs($number)` to also handle negative numbers properly.

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Translation/PluralizationRules.php [hunk 2]
```diff
@@ -25,13 +25,15 @@ class PluralizationRules
...
      *
-     * @param int    $number The number
+     * @param float  $number The number
      * @param string $locale The locale
      *
      * @return int The plural position
      */
     public static function get($number, $locale/*, bool $triggerDeprecation = true*/)
     {
+        $number = abs($number);
```
Comment (xabbuh) [inline src/Symfony/Component/Translation/PluralizationRules.php:35]: Is that something that works for all languages? I.e. could it be that there are languages where a number is treated differently when either being positive or negative?

File: src/Symfony/Contracts/Translation/TranslatorTrait.php [hunk 3]
```diff
@@ -136,8 +136,10 @@ public function trans($id, array $parameters = [], $domain = null, $locale = nul
      * which is subject to the new BSD license (http://framework.zend.com/license/new-bsd).
      * Copyright (c) 2005-2010 Zend Technologies USA Inc. (http://www.zend.com)
      */
-    private function getPluralizationRule(int $number, string $locale): int
+    private function getPluralizationRule(float $number, string $locale): int
     {
+        $number = abs($number);
```
Comment (xabbuh) [inline src/Symfony/Contracts/Translation/TranslatorTrait.php:141]: same here

Comment (xabbuh) [inline src/Symfony/Contracts/Translation/TranslatorTrait.php:141]: same here

File: src/Symfony/Component/Translation/PluralizationRules.php (hunk 2 above)
Comment (kylekatarnls) [reply src/Symfony/Component/Translation/PluralizationRules.php:35]: A sure thing is majority of the languages handle it the same way and currently they get wrong results. as the rules assume having a positive number. This will actually ensure that the assertion taken until then is met.

You can see ignoring the sign is the path taken by CLDR:
http://cldr.unicode.org/index/cldr-spec/plural-rules

If there is different rules for negative numbers, we can still add them at this moment: create `$absoluteNumber = abs($number)` so a given language can use the absolute number or the signed one.

But:
- We sure have negative plural currently broken for most languages and get it fixed with this change.
- If there is edge-cases, they very unlikely match the current implementation (they have way more chances to be broken too because rules don't take it into account)

Comment (kylekatarnls) [reply src/Symfony/Component/Translation/PluralizationRules.php:35]: To get an overview, we could grep all languages from angular/angular for instance that have a `Math.abs()` in their plural rule:
https://github.com/angular/angular/blob/master/packages/common/locales/fr.ts#L15
https://github.com/angular/angular/blob/master/packages/common/locales/en.ts#L15

Actually by looking at some random I couldn't find any that don't have it but I will extract an exhaustive list from it.

Comment (kylekatarnls) [reply src/Symfony/Component/Translation/PluralizationRules.php:35]: Angular rules parses CLDR data to get their rules and this input data is:
https://github.com/papandreou/node-cldr/blob/master/3rdparty/cldr/common/supplemental/plurals.xml

Where `i` is `floor(abs(n))` so first all rules based on `i` are guaranteed to be symmetric and this is the majority of them. I'm investigating on other ones because I identified yet very probable mistakes:

- wae "Walser" (Suisse) => -1 should be singular
- vo "Volapük" => It comes from German so -1 is likely singular too
- ar "Arabic" => Negatives numbers declension is symmetric to the positive ones according to the speakers I know.

So I think most of the rules here using `n` (the raw number) use it to handle properly the decimal part while it does not take the sign into account and would just output the "other" form for every negative number as a fallback for unknown rule.

**Comment by nicolas-grekas** [comment]
Thank you @kylekatarnls.
