### PR TITLE
[Security] Decouple `SameOriginCsrfTokenManager` from event listening

### LINKED ISSUE #62881: Failed to replace CsrfTokenManagerInterface service in test
### Symfony version(s) affected

7.2

### Description

Hello, 

I'm working on an application that uses CSRF tokens through the form component, but also without it (manual generation). 

I need to re-define the `security.csrf.token_manager` service globally for the `test` environment (with a Stub) to fake its behavior. This is necessary due to the use of  manually generated CSRF tokens that need the service to be defined. 

In some tests I replace this dependency to mock its behavior. 

That's working fine without stateless CSRF tokens. 

But from the moment I wanted to use stateless tokens I encounter the following error when running those tests: 

`Error: Call to undefined method App\Security\Csrf\StubTokenManager::onKernelResponse()`


This is due to the fact that the `security.csrf.token_manager` is decorated by the `security.csrf.same_origin_token_manager` .
The `security.csrf.same_origin_token_manager` service is attached to the `Symfony\Component\Security\Csrf\SameOriginCsrfTokenManager` class which implements the  `Symfony\Component\Security\Csrf\CsrfTokenManagerInterface` interface but, it is also provide an `onKernelResponse()` method that act as a listener (because the service is listening to the `kernel.response` event). 


### How to reproduce

A controller checking a manually generated token:

```php
class FooController extends AbstractController
{
    public function __invoke(Request $request): Response {
        if (!$this->isCsrfTokenValid('foo', $request->request->getString('_token')) {
            // ...
        }

        // ...
    }
}
```

A stub Token manager:

```php
class StubTokenManager implements CsrfTokenManagerInterface
{
    public function __construct(private bool $isValid = true)
    {
    }

    public function getToken(string $tokenId): CsrfToken
    {
        return new CsrfToken($tokenId, null);
    }

    public function refreshToken(string $tokenId): CsrfToken
    {
        return new CsrfToken($tokenId, null);
    }

    public function removeToken(string $tokenId): ?string
    {
        return null;
    }

    public function isTokenValid(CsrfToken $token): bool
    {
        return $this->isValid;
    }
}
```

Some configuration: 

```yaml
# config/packages/csrf.yaml
when@test:
  framework:
    form:
      csrf_protection:
        enabled: false # We don't want to send CSRF token when submitting forms in tests
```


```yaml
# config/services.yaml

when@test:
    'security.csrf.token_manager': '@App\Security\Csrf\StubTokenManager'
```


A dedicated test case:

```php
class FooTest extends WebTestCase
{
    public function testSuccess(): void
    {
        $client = self::createClient();
        $client->request('POST', '/foo');

        $this->assertResponseStatusCodeSame(200);
    }

    public function testInvalidCsrfToken(): void
    {
        $client = self::createClient();
        
        self::getContainer()->set('security.csrf.token_manager', new StubTokenManager(false));

        $client->request('POST', '/foo');

        $this->assertResponseStatusCodeSame(400);
    }
}
```

**-> When running these tests, everything is green.**  


Adding the lines below in the `config/packages/csrf.yaml` 

```yaml
framework:
  csrf_protection:
    stateless_token_ids:
      - 'foo'

# ...
```

**-> and the following error occurred while running the tests:** 

```console
...
Error: Call to undefined method App\Security\Csrf\StubTokenManager::onKernelResponse()
...
``` 


### Possible Solution

A possible solution could be to move the code related of the `onKernelResponse()` method in a dedicated class. This should decouple responsibility between the listener and the manager.

### Additional Context

**Here is the result of the `debug:container` command with no stateless CSRF token enabled:**

```console
/var/www/project $ APP_ENV=test bin/console debug:container security.csrf.token_manager

 // This service is a private alias for the service App\Security\Csrf\StubTokenManager                                  

Information for Service "App\Security\Csrf\StubTokenManager"
============================================================

 ---------------- --------------------------------------------------------------------------------------------- 
  Option           Value                                                                                        
 ---------------- --------------------------------------------------------------------------------------------- 
  Service ID       App\Security\Csrf\StubTokenManager                                                           
  Class            App\Security\Csrf\StubTokenManager                                                           
  Tags             -                                                                                            
  Public           no                                                                                           
  Synthetic        no                                                                                           
  Lazy             no                                                                                           
  Shared           yes                                                                                          
  Abstract         no                                                                                           
  Autowired        yes                                                                                          
  Autoconfigured   yes                                                                                          
  Usages           Symfony\Component\Security\Csrf\CsrfTokenManagerInterface                                    
                   security.csrf.token_manager 

```

**Here is the result of the `debug:container` command with a stateless CSRF token enabled:**

```console
/var/www/project $ APP_ENV=test bin/console debug:container security.csrf.token_manager

 // This service is a private alias for the service security.csrf.same_origin_token_manager                             

Information for Service "security.csrf.same_origin_token_manager"
=================================================================

 This CSRF token manager uses a combination of cookie and headers to validate non-persistent tokens.

 ---------------- --------------------------------------------------------------------------------------------- 
  Option           Value                                                                                        
 ---------------- --------------------------------------------------------------------------------------------- 
  Service ID       security.csrf.same_origin_token_manager                                                      
  Class            Symfony\Component\Security\Csrf\SameOriginCsrfTokenManager                                   
  Tags             monolog.logger (channel: request)                                                            
                   kernel.event_listener (event: kernel.response, method: onKernelResponse)                     
                   container.hot_path                                                                           
  Public           no                                                                                           
  Synthetic        no                                                                                           
  Lazy             no                                                                                           
  Shared           yes                                                                                          
  Abstract         no                                                                                           
  Autowired        no                                                                                           
  Autoconfigured   no                                                                                           
  Arguments        Service(request_stack)                                                                       
                   Service(monolog.logger.request)                                                              
                   Service(App\Security\Csrf\StubTokenManager)                                                  
                   Array (1 element(s))                                                                         
                                                                                                                
                   csrf-token                                                                                   
  Usages           Symfony\Component\Security\Csrf\CsrfTokenManagerInterface                                    
                   security.csrf.token_manager                                                                  
```

### PR DESCRIPTION
**Pull request by jprivet-dev**
| Q             | A          
|---------------|------------
| Branch?       | 8.1        
| Bug fix?      | yes        
| New feature?  | no         
| Deprecations? | yes        
| Issues        | Fix #62881 
| License       | MIT        

Here is the result after we exchanged ideas with @syl20b 🚀

## Description

The `SameOriginCsrfTokenManager` currently violates the Single Responsibility Principle by handling both CSRF token management and listening to the `kernel.response` event to manage cookies.

This causes issues when testing: if a developer replaces the `security.csrf.token_manager` service with a Stub or Mock that implements `CsrfTokenManagerInterface` (but does not implement `onKernelResponse`), tests fail because the container expects the manager to also act as a listener.

Error encountered:

```
Error: Call to undefined method App\Security\Csrf\StubTokenManager::onKernelResponse()
```

This PR extracts the event listening logic (cookie clearing and persistence) into a dedicated `SameOriginCsrfListener`. This decouples the infrastructure logic from the token management logic, allowing for proper mocking of the TokenManager in tests.

## Reproduction Case

I have provided a full reproduction case with a minimal application structure in the linked issue. Please see the detailed comments in #62881.

## Backward Compatibility

To ensure backward compatibility in 8.1, the methods `onKernelResponse`, `clearCookies`, and `persistStrategy` have been kept in `SameOriginCsrfTokenManager`. They are marked as `@deprecated` and trigger a deprecation notice.

### CODE REVIEW

File: src/Symfony/Component/Security/Csrf/Tests/SameOriginCsrfTokenManagerTest.php [hunk 1]
```diff
@@ -232,84 +215,98 @@ public function testCheckOnlyHeader()
...
         $response = new Response();
 
-        $csrfTokenManager->clearCookies($request, $response);
+        $this->csrfTokenManager->clearCookies($request, $response);
 
         $this->assertTrue($response->headers->has('Set-Cookie'));
     }
 
+    /**
+     * @group legacy
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Csrf/Tests/SameOriginCsrfTokenManagerTest.php]: these should be removed, we don't use them anymore

**Review by nicolas-grekas — COMMENTED** [review]
please target branch 8.1, that's not a bugfix but an improvement

File: src/Symfony/Component/Security/Csrf/SameOriginCsrfListener.php [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+    {
+        if (!$event->isMainRequest()) {
+            return;
+        }
+
+        $this->clearCookies($event->getRequest(), $event->getResponse());
+        $this->persistStrategy($event->getRequest());
+    }
+
+    public function clearCookies(Request $request, Response $response): void
```
Comment (syl20b) [inline src/Symfony/Component/Security/Csrf/SameOriginCsrfListener.php]: Do we need this method to be public :thinking: ?

File: src/Symfony/Component/Security/Csrf/SameOriginCsrfListener.php [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+        $cookieName = ($request->isSecure() ? '__Host-' : '').$this->cookieName;
+
+        foreach ($request->cookies->all() as $name => $value) {
+            if ($this->cookieName === $value && str_starts_with($name, $cookieName.'_')) {
+                $response->headers->clearCookie($name, '/', null, $request->isSecure(), false, 'strict');
+            }
+        }
+    }
+
+    public function persistStrategy(Request $request): void
```
Comment (syl20b) [inline src/Symfony/Component/Security/Csrf/SameOriginCsrfListener.php]: Same as above (public method ?)

**Comment by stof** [comment]
This must target PHP 8.1. Adding new deprecations cannot happen in patch versions.

File: src/Symfony/Component/Security/Csrf/SameOriginCsrfListener.php (hunk 2 above)
Comment (jprivet-dev) [reply src/Symfony/Component/Security/Csrf/SameOriginCsrfListener.php]: I simply transferred this `clearCookies` method, which was historically public, to the `SameOriginCsrfTokenManager` class. I don't know why it was public. If you don't mind, I'll make it private. I'll adapt the relevant tests.

File: src/Symfony/Component/Security/Csrf/SameOriginCsrfListener.php (hunk 3 above)
Comment (jprivet-dev) [reply src/Symfony/Component/Security/Csrf/SameOriginCsrfListener.php]: I simply transferred this `persistStrategy` method, which was historically public, to the `SameOriginCsrfTokenManager` class. I don't know why it was public. If you don't mind, I'll make it private. I'll adapt the relevant tests.

**Comment by jprivet-dev** [comment]
> please target branch 8.1, that's not a bugfix but an improvement

> This must target PHP 8.1. Adding new deprecations cannot happen in patch versions.

Done!

File: src/Symfony/Component/Security/Csrf/SameOriginCsrfListener.php (hunk 3 above)
Comment (jprivet-dev) [reply src/Symfony/Component/Security/Csrf/SameOriginCsrfListener.php]: Done!

File: src/Symfony/Component/Security/Csrf/SameOriginCsrfListener.php (hunk 2 above)
Comment (jprivet-dev) [reply src/Symfony/Component/Security/Csrf/SameOriginCsrfListener.php]: Done!

File: src/Symfony/Component/Security/Csrf/Tests/SameOriginCsrfTokenManagerTest.php (hunk 1 above)
Comment (jprivet-dev) [reply src/Symfony/Component/Security/Csrf/Tests/SameOriginCsrfTokenManagerTest.php]: Done!

**Review by Spomky — APPROVED** [review]
Lokks good to me.
Many thnaks 👍

File: src/Symfony/Component/Security/Csrf/composer.json [hunk 4]
```diff
@@ -17,7 +17,8 @@
     ],
     "require": {
         "php": ">=8.4",
-        "symfony/security-core": "^7.4|^8.0"
+        "symfony/security-core": "^7.4|^8.0",
+        "symfony/deprecation-contracts": "^2.5|^3"
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Csrf/composer.json]: alpha order

File: src/Symfony/Component/Security/Csrf/SameOriginCsrfListener.php [hunk 5]
```diff
@@ -0,0 +1,64 @@
...
+
+use Symfony\Component\HttpFoundation\Request;
+use Symfony\Component\HttpFoundation\Response;
+use Symfony\Component\HttpFoundation\Session\Session;
+use Symfony\Component\HttpKernel\Event\ResponseEvent;
+
+final class SameOriginCsrfListener
+{
+    public function __construct(private readonly string $cookieName = 'csrf-token')
+    {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Csrf/SameOriginCsrfListener.php]:
```suggestion
    public function __construct(
        private readonly string $cookieName = 'csrf-token',
    ) {
```

**Review by nicolas-grekas — APPROVED** [review]

**Review by nicolas-grekas — COMMENTED** [review]
Wait, this misses changelog+upgrade files entries!

**Comment by Spomky** [comment]
> Way, this misses changelog+upgrade files entries!

Correct.
Also I've just noticed the [deprecation message](https://github.com/symfony/symfony/pull/63097/changes#diff-86e46aeb57d4884cab464c32d2677b881e0d6c651d1f8af2e2a2b86e8d5d241aR218) proposes the use of `SameOriginCsrfListener::persistStrategy()`, but the method is [`private`](https://github.com/symfony/symfony/pull/63097/changes#diff-cf6b8b8bf6de622ec7630dfce5cb9487fb682cedad6a4a8aa32c521c99d3c407R50).

Furthermore, are we certain that the two services will not be triggered simultaneously? This could lead to a conflict.

File: src/Symfony/Component/Security/Csrf/composer.json (hunk 4 above)
Comment (jprivet-dev) [reply src/Symfony/Component/Security/Csrf/composer.json]: Done!

File: src/Symfony/Component/Security/Csrf/SameOriginCsrfListener.php (hunk 5 above)
Comment (jprivet-dev) [reply src/Symfony/Component/Security/Csrf/SameOriginCsrfListener.php]: Done!

**Comment by jprivet-dev** [comment]
> Wait, this misses changelog+upgrade files entries!

Done!

**Comment by jprivet-dev** [comment]
> Also I've just noticed the [deprecation message](https://github.com/symfony/symfony/pull/63097/changes#diff-86e46aeb57d4884cab464c32d2677b881e0d6c651d1f8af2e2a2b86e8d5d241aR218) proposes the use of `SameOriginCsrfListener::persistStrategy()`, but the method is [`private`](https://github.com/symfony/symfony/pull/63097/changes#diff-cf6b8b8bf6de622ec7630dfce5cb9487fb682cedad6a4a8aa32c521c99d3c407R50).

Well spotted! I've adjusted the deprecation messages  for `clearCookies()`, `persistStrategy()` and `onKernelResponse()`:

```
 @deprecated since Symfony 8.1, logic is handled by SameOriginCsrfListener.
```

**Comment by jprivet-dev** [comment]
> Furthermore, are we certain that the two services will not be triggered simultaneously? This could lead to a conflict.

Indeed! I've checked the logic to ensure we avoid any conflict or race condition.

### Dependency Injection Configuration

As seen in the updated `security_csrf.php`, I have removed the `kernel.event_listener` tag from `SameOriginCsrfTokenManager`. By default, only the new `SameOriginCsrfListener` will be triggered on `kernel.response`. The Manager is no longer an active listener:

```php
return static function (ContainerConfigurator $container) {
    $container->services()
        // ...
        ->set('security.csrf.same_origin_token_manager', SameOriginCsrfTokenManager::class)
            ->decorate('security.csrf.token_manager')
            ->args([
                service('request_stack'),
                service('logger')->nullOnInvalid(),
                service('.inner'),
                abstract_arg('framework.csrf_protection.stateless_token_ids'),
                abstract_arg('framework.csrf_protection.check_header'),
                abstract_arg('framework.csrf_protection.cookie_name'),
            ])
            ->tag('monolog.logger', ['channel' => 'request'])

        ->set('security.csrf.same_origin_listener', SameOriginCsrfListener::class)
            ->args([
                abstract_arg('framework.csrf_protection.cookie_name'),
            ])
            /* NEW TRIGGER */
            ->tag('kernel.event_listener', ['event' => 'kernel.response', 'method' => 'onKernelResponse'])
    ;
};
```

### Idempotency

In the edge case where a developer manually calls the deprecated methods (or manually registers the Manager as a listener in their own config), the logic relies on `$response->headers->setCookie()`. Since both classes implement the exact same logic, the operation is idempotent: the second call would simply overwrite the cookie with the same value, causing no data corruption.

### Deprecation Notice

If this edge case occurs, the developer will immediately trigger the deprecation notice added to `onKernelResponse()`, warning them that the logic is now handled automatically by the Listener.

Does this approach suit you?

**Comment by nicolas-grekas** [comment]
Thank you @jprivet-dev.

File: src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php [hunk 6]
```diff
@@ -190,8 +190,13 @@ public function isTokenValid(CsrfToken $token): bool
         return true;
     }
 
+    /**
+     * @deprecated since Symfony 8.1, logic is handled by SameOriginCsrfListener.
+     */
     public function clearCookies(Request $request, Response $response): void
     {
+        trigger_deprecation('symfony/security-csrf', '8.1', 'The "%s()" method is deprecated and will be removed in 9.0, use "%s::clearCookies()" instead.', __METHOD__, SameOriginCsrfListener::class);
```
Comment (Spomky) [inline src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php:198]: This message should be in accordance with the `@deprected`.
Same for `persistStrategy`

File: src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php [hunk 7]
```diff
@@ -190,8 +190,13 @@ public function isTokenValid(CsrfToken $token): bool
         return true;
     }
 
+    /**
+     * @deprecated since Symfony 8.1, logic is handled by SameOriginCsrfListener.
```
Comment (Spomky) [inline src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php:194]:
```suggestion
     * @deprecated since Symfony 8.1 and will be removed in 9.0. The logic is handled by SameOriginCsrfListener.
```

File: src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php (hunk 6 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php:198]: ah sorry I merged before you could post this comment

Comment (syl20b) [reply src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php:198]: The deprecation message indicates to call a private method instead.

Comment (jprivet-dev) [reply src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php:198]: Zut! I missed it!

Comment (jprivet-dev) [reply src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php:198]: New PR https://github.com/symfony/symfony/pull/63243 for that.

File: src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php (hunk 7 above)
Comment (jprivet-dev) [reply src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php:194]: New PR https://github.com/symfony/symfony/pull/63243 for that.
