### PR TITLE
[TypeInfo] Fix type resolution when called class is in other namespace

### LINKED ISSUE #62922: [PropertyInfo] PhpstanExtractor leads to wrong/invalid type for property of child class, when type is declared as static in parent class
### Symfony version(s) affected

7.4.3 of symfony/property-info it becomes problematic, underlying issues exists in older versions too.

### Description

When a property is declared as static in a parent class via docblock, then trying to retrieve the type in a sub class that is in a different namespace than the parent, resolves to an invalid (non-existing) class.

PR #62717 for 7.4.3 made the phpstanextractor active for @phpstan-var without constructor, so that issue became obvious. The flawed mechanism exists in older versions too; it is just not triggered.

### How to reproduce

Take some simple class structure like

```php

namespace App\Entity\Base;

class BaseEntity {
     /** @phpstan-var static */
     protected BaseEntity $property;
}
```

and 

```php

namespace App\Entity\OtherNamespace;

class OtherEntity {
     /* Additional declarations */
     protected BaseEntity $property;
}
```

Then calling PHPStanExtractor::getType() returns the non-existing `App\Entity\Base\OtherEntity`

### Possible Solution

The problem is the TypeContext class, uses a common "namespace" property for the `calledClassName` and the `declaredClassName`, which is derived from the `declaredClassName`
If the namespaces of `declaredClassName` and `calledClassName` differ, then it leads to invalid results, as the TypeContext::getCalledClass() leads then to an invalid name.

A solution would be store the namespace independently for each class, or include the namespaces directly in the calledClassName.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62922
| License       | MIT

When resolving `static` return type for a child class in a different namespace than the parent class where the method is declared, the wrong namespace was used.

The fix adds the called class to the uses array when its namespace differs from the declaring class, allowing `normalize()` to resolve it correctly.

### CODE REVIEW

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 1]
```diff
@@ -66,11 +66,18 @@ public function createFromClassName(string $calledClassName, ?string $declaringC
             $this->collectUses($calledClassNameReflection),
         );
 
+        $uses = $this->collectUses($declaringClassReflection);
+
+        // add called class to uses if its namespace differs from the declaring class
```
Comment (stof) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: This change looks suspicious to me. Resolving a `static` keyword should not involve defining a fake use statement (which will impact other resolutions in the phpdoc if the short class name of that called class is used for something else).
The TypeContextFactory always has a FQCN as input anyway.

I think the proper fix would involve using FQCN as called class name and declaring class name in the TypeContext (and then not calling `normalize` on them) instead of converting them to short class names that require resolution (and thus require creating a fake use statement for them, which would be very complex to do safely to avoid conflict with actual relative names used in the code)

Comment (stof) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: thus, this would solve the confusion where the **public** property `declaringClassName` returns a different thing than the getter `getDeclaringClassName()` (with the getter returning the useful info)

**Comment by nicolas-grekas** [comment]
Thank you @mtarld.
