### PR TITLE
[Console] Fix ANSI when stdErr is not a tty

### LINKED ISSUE #38981: console: Ansi stripped on stdout when stderr is redirected
**Symfony version(s) affected**: 5.1.8

**Description**  
ANSI color is stripped (command behaves if run with `--no-ansi` flag) from standard output when standard error is redirected.

**How to reproduce**  
Pick any console app that issues output with ANSI color, and in a POSIX shell such as `sh` or `bash`, redirect standard error, e.g.:

`bin/console some:command 2> /dev/null`

**Possible Solution**  
I would guess the `*_isatty()` check is being done on both stdout and stderr file descriptors and if either is not a TTY, the ANSI flag is wrongly cleared for both.  Solution would be to check and manage the 2 file streams or descriptors separately.

**Additional context**  
Explicitly adding the `--ansi` flag makes it work, e.g.:
`bin/console --ansi some:command 2> /dev/null` 
correctly outputs the stdout text, such as `[OK] message`, in ANSI color.

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38981
| License       | MIT
| Doc PR        | -

Taking the @wouterj 's comment into account (https://github.com/symfony/symfony/issues/38981#issuecomment-721915428)

This PR prevents using the same Formatter for stdOut and stdErr when possible.

When user send a custom formatter (or call `setFormatter`) the previous logic is kept.
Otherwise, symfony is asked to create the Formatter, and thus is able to clone the formatter.

In a future PR targeting 5.3, we could improve the constructor to let people inject 2 distinguished formatters

### CODE REVIEW

**Comment by wouterj** [comment]
Thanks for your quick response! This solution works for me, it should be BC (the `OutputFormatter` is clonable). I've quickly verified this fix and it indeed fixes the cases described in the issue.

I think it's a good idea to add a test for this, to make sure we don't break it in a later patch version. And maybe add a code comment that this is only done when `$formatter === null` for BC reasons?

File: src/Symfony/Component/Console/Output/ConsoleOutput.php [hunk 1]
```diff
@@ -41,6 +41,12 @@ public function __construct(int $verbosity = self::VERBOSITY_NORMAL, bool $decor
     {
         parent::__construct($this->openOutputStream(), $verbosity, $decorated, $formatter);
 
+        if (null === $formatter) {
+            $this->stderr = new StreamOutput($this->openErrorStream(), $verbosity, $decorated, $formatter);
```
Comment (stof) [inline src/Symfony/Component/Console/Output/ConsoleOutput.php]: I suggest using `null` or omitting the argument rather than passing `$formatter`, to make the code easier to understand.

Comment (jderusse) [reply src/Symfony/Component/Console/Output/ConsoleOutput.php]: fixed

**Comment by jderusse** [comment]
> I think it's a good idea to add a test for this

Added unit tests.

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @jderusse.
