### PR TITLE
[Messenger] prevent reflection usages when classes do not exist

### LINKED ISSUE #41748: [Serializer] Class "Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpReceivedStamp" does not exist
**Symfony version(s) affected**: 5.3.*, 5.4.*

**Description**
Caused by
ReflectionException: Class "Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpReceivedStamp" does not exist

**How to reproduce**
Download https://github.com/Warxcell/files and run tests.

**Possible Solution**
Move https://github.com/symfony/symfony/blob/5.3/src/Symfony/Component/Messenger/Middleware/RejectRedeliveredMessageMiddleware.php to https://github.com/symfony/symfony/tree/5.3/src/Symfony/Component/Messenger/Bridge/Amqp namespace, so it will be registered only if AMQP Bridge Package is installed.

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41748
| License       | MIT
| Doc PR        |

### CODE REVIEW

File: src/Symfony/Component/Messenger/Envelope.php [hunk 1]
```diff
@@ -127,6 +127,6 @@ private function resolveAlias(string $fqcn): string
     {
         static $resolved;
 
-        return $resolved[$fqcn] ?? ($resolved[$fqcn] = (new \ReflectionClass($fqcn))->getName());
+        return $resolved[$fqcn] ?? ($resolved[$fqcn] = class_exists($fqcn) ? (new \ReflectionClass($fqcn))->getName() : $fqcn);
```
Comment (Warxcell) [inline src/Symfony/Component/Messenger/Envelope.php:130]: isn't `$fqcn` === `(new \ReflectionClass($fqcn))->getName()` ?

Comment (derrabus) [reply src/Symfony/Component/Messenger/Envelope.php:130]: Not if `$fcqn` is a class alias.

**Review by derrabus — APPROVED** [review]

**Review by chalasr — APPROVED** [review]
