### PR TITLE
[SecurityBundle] Make firewalls event dispatcher traceable on debug mode

### LINKED ISSUE #42973: [Firewall dispatcher] Traceable Event Dispatcher
**Symfony version(s) affected**: 5.3.7

**Description**
I was using in the past the general TraceableEventDispatcher in debug mode to track my user actions during dev.
It is not fully possible anymore since version 5.3.7.
The security dispatcher is only a EventDispatcher class.

NB: Therefore, the profiler is pretending security events are not triggered

**How to reproduce**
```
<?php 

// SecuritySubscriber.php
namespace xKzl\MyBundle\Subscriber;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;

use Symfony\Component\DependencyInjection\Argument\ServiceLocator;
use Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher;

class SecuritySubscriber implements EventSubscriberInterface
{
    /**
     * @var array[TraceableEventDispatcher]
     */
    private $dispatchers = [];

    public function __construct(
        ServiceLocator $dispatcherLocator) {

        $this->dispatcherLocator = $dispatcherLocator;
        foreach($this->dispatcherLocator->getProvidedServices() as $dispatcherId => $_) {

            $dispatcher = $this->dispatcherLocator->get($dispatcherId);
            if (!$dispatcher instanceof TraceableEventDispatcher) continue;

            $dispatchers[] = $this->dispatcherLocator->get($dispatcherId);
        }

        dump($dispatchers);
    }

    public static function getSubscribedEvents()
    {
        return [];
    }
}
```

I declared my subscriber as following:
```
        <service id="xKzl\MyBundle\Subscriber\SecuritySubscriber">
            <tag name="kernel.event_subscriber" />
            <argument type="tagged_locator" tag="event_dispatcher.dispatcher" index-by="name"/>
        </service>
```

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #42973
| License       | MIT
| Doc PR        | N/A

This PR decorates firewalls event dispatcher with `TraceableEventDispatcher` on debug mode. This will display security events and listeners in the profiler’s `time` panel.

<details><summary>Before</summary>

</details>
<details><summary>After</summary>

</details>

They still won’t appear in the `events` panel (because the `EventDataCollector` is only injected `debug.event_dispatcher`) but I think it will be best handled in a separate PR.

### CODE REVIEW

**Comment by chalasr** [comment]
Could you illustrate what this brings to userland with e.g. a screenshot?

**Comment by MatTheCat** [comment]
@chalasr done!

**Review by chalasr — DISMISSED** [review]

**Comment by chalasr** [comment]
Can you add some test?  Also can you double check that there is no existing compiler pass that could be patched instead of adding a new one?

**Comment by MatTheCat** [comment]
> Can you add some test

[Done](https://github.com/symfony/symfony/pull/49021/commits/9c737cebb29e1bc4da6c813db9ec5dcbed578f4c)

> can you double check that there is no existing compiler pass that could be patched instead of adding a new one

Did not find anything related, which kind of surprised me because what I’m doing here feels like it could be generic :thinking:

**Review by chalasr — APPROVED** [review]

**Comment by MatTheCat** [comment]
Damn I broke `low-deps` tests. Investigating.

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/MakeFirewallsEventDispatcherTraceablePass.php [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+ */
+class MakeFirewallsEventDispatcherTraceablePass implements CompilerPassInterface
+{
+    public function process(ContainerBuilder $container)
+    {
+        if (!$container->has('event_dispatcher') || !$container->hasParameter('security.firewalls')) {
+            return;
+        }
+
+        if (!$container->getParameter('kernel.debug') || !class_exists(Stopwatch::class) || !$container->has('debug.stopwatch')) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/MakeFirewallsEventDispatcherTraceablePass.php]: do we really need the class_exists check?

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/MakeFirewallsEventDispatcherTraceablePass.php [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+use Symfony\Component\DependencyInjection\ContainerBuilder;
+use Symfony\Component\DependencyInjection\ContainerInterface;
+use Symfony\Component\DependencyInjection\Reference;
+use Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher;
+use Symfony\Component\Stopwatch\Stopwatch;
+
+/**
+ * @author Mathieu Lechat <mathieu.lechat@les-tilleuls.coop>
+ *
+ * @internal
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/MakeFirewallsEventDispatcherTraceablePass.php]: not needed IMHO

File: src/Symfony/Bundle/SecurityBundle/SecurityBundle.php [hunk 3]
```diff
@@ -92,5 +93,8 @@ public function build(ContainerBuilder $container)
             AuthenticationEvents::ALIASES,
             SecurityEvents::ALIASES
         )));
+
+        // must be registered before DecoratorServicePass
+        $container->addCompilerPass(new MakeFirewallsEventDispatcherTraceablePass(), PassConfig::TYPE_OPTIMIZE, 1);
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/SecurityBundle/SecurityBundle.php]: can't we find another priority that would allow some holes in the numbering of priorities?

**Review by nicolas-grekas — COMMENTED** [review]
LGTM once tests are green :)

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/MakeFirewallsEventDispatcherTraceablePass.php (hunk 1 above)
Comment (MatTheCat) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/MakeFirewallsEventDispatcherTraceablePass.php]: I copied it from https://github.com/symfony/symfony/blob/8278947d0af670c5cf6aabfda23368b1f98e2b6a/src/Symfony/Component/HttpKernel/DependencyInjection/ControllerArgumentValueResolverPass.php#L39 but it indeed seems like [one implies the other.](https://github.com/symfony/symfony/blob/8278947d0af670c5cf6aabfda23368b1f98e2b6a/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1079-L1080)

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/MakeFirewallsEventDispatcherTraceablePass.php (hunk 2 above)
Comment (MatTheCat) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/MakeFirewallsEventDispatcherTraceablePass.php]: Copied from `RegisterGlobalSecurityEventListenersPass` but can remove it!

File: src/Symfony/Bundle/SecurityBundle/SecurityBundle.php (hunk 3 above)
Comment (MatTheCat) [reply src/Symfony/Bundle/SecurityBundle/SecurityBundle.php]: If I’m not mistaken any number greater than zero would be good.

Comment (nicolas-grekas) [reply src/Symfony/Bundle/SecurityBundle/SecurityBundle.php]: let's use 10 then?

**Comment by MatTheCat** [comment]
Looks like https://github.com/symfony/symfony/pull/49021#discussion_r1087838248 was the cause of the failing test, which is weird? How could it register `debug.stopwatch` if `Stopwatch` does not exist :thinking:

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @MatTheCat.
