### PR TITLE
[PropertyInfo] Fix `ReflectionExtractor` handling of underscore-only property names

### LINKED ISSUE #61425: [PropertyInfo] ReflectionExtractor::getReadInfo returns null for property `_`
### Symfony version(s) affected

5.1.0+

### Description

In my project I have some generated classes (for SOAP operations). Many of those generated classes include a property named `$_` and a getter named `get_()`. When serializing such a class, it won't include the `_` property.

Example Class:
```php
class Amount
{
    private float $_;

    private string $currencyCode;

    public function get_() : float
    {
        return $this->_;
    }

    public function with_(float $_) : static
    {
        $new = clone $this;
        $new->_ = $_;

        return $new;
    }

    public function getCurrencyCode() : string
    {
        return $this->currencyCode;
    }

    public function withCurrencyCode(string $currencyCode) : static
    {
        $new = clone $this;
        $new->currencyCode = $currencyCode;

        return $new;
    }
}
```

### How to reproduce

1. Add this `src/Controller/UnderscoreSerializerDemoController.php` to your project:
```php
<?php

declare(strict_types=1);

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

final class UnderscoreSerializerDemoController extends AbstractController
{
    #[Route('/underscore/serializer/demo', name: 'app_underscore_serializer_demo')]
    public function index(
        NormalizerInterface $normalizer,
    ): Response {
        $amount = (new Amount())
            ->with_(100.0)
            ->withCurrencyCode('EUR');
        $amountArray = $normalizer->normalize($amount);

        return new JsonResponse($amountArray);
    }
}

class Amount
{
    private float $_;

    private string $currencyCode;

    public function get_(): float
    {
        return $this->_;
    }

    public function with_(float $_): static
    {
        $new = clone $this;
        $new->_ = $_;

        return $new;
    }

    public function getCurrencyCode(): string
    {
        return $this->currencyCode;
    }

    public function withCurrencyCode(string $currencyCode): static
    {
        $new = clone $this;
        $new->currencyCode = $currencyCode;

        return $new;
    }
}
```
2. Go to route http://127.0.0.1:8000/underscore/serializer/demo
3. See, that it returns `{"currencyCode":"EUR"}`, the amount is lost!

I would expect it to return `{"_": 100, "currencyCode":"EUR"}`

### Possible Solution

Changing this method:
https://github.com/symfony/symfony/blob/f2acd82e7372b5d59685f996b8d70159d803f2cb/src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php#L900-L903

to
```php
private function camelize(string $string): string
{
    return $string === '_'
        ? $string
        : str_replace(' ', '', ucwords(str_replace('_', ' ', $string)));
}
```

fixes the issue.

Then `$camelProp` will be `'_'` instead of `''` (empty string) as the underscore is kept. Thus it can find the correct accessor (`get_`) in the loop:
The reason can be found here: https://github.com/symfony/symfony/blob/f2acd82e7372b5d59685f996b8d70159d803f2cb/src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php#L376-L387

### Additional Context

I'm open to do a PR. I'm not sure against which branch though. It exists since Symfony 5.1, it was introduced with the commit https://github.com/symfony/symfony/commit/fc250863a8825f8f47a77ded13eff812bbf79f2c

### PR DESCRIPTION
**Pull request by yoeunes**
| Q | A
|---|---
| Branch? | 6.4
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Issues | Fixes #61425
| License | MIT

This PR fixes a bug in `ReflectionExtractor::camelize` where property names consisting only of underscores (e.g., `$_`) were incorrectly transformed into an empty string.

This caused `getReadInfo` to fail when finding the corresponding accessor (e.g., `get_()`), preventing the property from being detected, which impacts serialization and other component usages.

### CODE REVIEW

File: src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php [hunk 1]
```diff
@@ -757,6 +757,11 @@ private function isMethodAccessible(\ReflectionClass $class, string $methodName,
      */
     private function camelize(string $string): string
     {
+        // Do not camelize strings that are only underscores
+        if ('' === str_replace('_', '', $string)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php]:
```suggestion
        if ('' === ltrim($string, '_')) {
```

**Review by nicolas-grekas — COMMENTED** [review]
please remove most/all comments, unless they really provide value

File: src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php (hunk 1 above)
Comment (yoeunes) [reply src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php]: Hi @nicolas-grekas thanks for your review 🙏🏼, I've updated the code and removed some comments

File: src/Symfony/Component/PropertyInfo/Tests/Fixtures/UnderscoreDummy.php [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\PropertyInfo\Tests\Fixtures;
+
+/**
+ * Fixture class for testing underscore-only properties (issue #61425).
```
Comment (OskarStark) [inline src/Symfony/Component/PropertyInfo/Tests/Fixtures/UnderscoreDummy.php]:
```suggestion
 * Fixture class for testing underscore-only properties.
```

**Comment by nicolas-grekas** [comment]
Thank you @yoeunes.

File: src/Symfony/Component/PropertyInfo/Tests/Fixtures/UnderscoreDummy.php (hunk 2 above)
Comment (yoeunes) [reply src/Symfony/Component/PropertyInfo/Tests/Fixtures/UnderscoreDummy.php]: Hi @OskarStark, thank you, I forget this one 🙏🏼
