### PR TITLE
[Cache] Wrap `DoctrineDbalAdapter::doSave()` in savepoint to prevent transaction poisoning

### LINKED ISSUE #63417: [Cache] DoctrineDbalAdapter silently poisons PostgreSQL transactions when cache save fails
### Symfony version(s) affected

7.x

### Description

When DoctrineDbalAdapter is used within an active PostgreSQL transaction (e.g., inside a Symfony Messenger middleware), a cache save failure silently corrupts the transaction. The
  AbstractAdapter::commit() method catches \Exception from doSave() (line 164), but in PostgreSQL, any failed SQL command permanently marks the transaction as aborted (SQLSTATE
  25P02). All subsequent SQL queries within the same transaction fail with:

```
  SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted,
  commands ignored until end of transaction block
```

  The caller receives the computed value from the callback and has no indication that the transaction is now unusable.

### Expected behavior

  Either:
  1. The cache save failure should not corrupt the enclosing transaction, or
  2. The exception should propagate to the caller so it can handle it

### Actual behavior

  - doSave() throws an exception (e.g., constraint violation on cache_items)
  - AbstractAdapter::commit() catches \Exception silently (line 162-165)
  - The computed value is returned to the caller as if nothing happened
  - The PostgreSQL transaction is permanently in "aborted" state
  - All subsequent SQL commands fail with SQLSTATE 25P02

### Root cause

```
  In AbstractAdapter::commit():

  // src/Cache/Adapter/AbstractAdapter.php:161-165
  foreach ($byLifetime as $lifetime => $values) {
      try {
          $e = $this->doSave($values, $lifetime);
      } catch (\Exception $e) {
          // Exception swallowed — but PostgreSQL transaction is now failed
      }
```

  PostgreSQL (unlike MySQL) does not allow any further operations in a transaction after a command fails. The only valid command is ROLLBACK. By catching the exception silently, the
  adapter hides a fatal transaction state from the caller.

  ### Impact in our case

  In a Symfony Messenger worker with a transactional middleware:

  1. TransactionalMiddleware begins a DB transaction
  2. Handler logic calls a service that uses DoctrineDbalAdapter cache (same DBAL connection)
  3. Cache miss → callback computes value → doSave() INSERT fails (deadlock, lock contention, etc.)
  4. Exception silently caught, handler continues with the computed value
  5. Next DB query in the handler → SQLSTATE 25P02
  6. The worker crashes with a misleading error pointing at an unrelated query

  This is especially problematic because:
  - The error appears to come from a completely unrelated query
  - The real cause (cache save failure) is silently swallowed
  - It's intermittent (depends on cache misses and concurrent writes)

### How to reproduce

```
use Doctrine\DBAL\Connection;
  use Symfony\Component\Cache\Adapter\DoctrineDbalAdapter;

  // Assume $connection is a Doctrine DBAL Connection to PostgreSQL

  $cache = new DoctrineDbalAdapter($connection, 'test');

  // Warm up: ensure cache table exists
  $cache->get('warmup', fn () => 'value');

  // Start a transaction (simulates Messenger's TransactionalMiddleware)
  $connection->beginTransaction();

  // Make cache INSERT fail (e.g., CHECK constraint, deadlock, disk full...)
  $connection->executeStatement(
      'ALTER TABLE cache_items ADD CONSTRAINT fail_insert CHECK (false) NOT VALID'
  );

  // Cache miss → callback runs → doSave INSERT fails → exception silently caught
  $value = $cache->get('new_key', fn () => 'computed_value');

  assert($value === 'computed_value'); // ✅ Value returned normally

  // But the transaction is now poisoned:
  $connection->executeQuery('SELECT 1'); // 💥 SQLSTATE 25P02
```

### Possible Solution

Wrap doSave() and doDelete() in a SAVEPOINT when inside an active transaction. If the operation fails, ROLLBACK TO SAVEPOINT restores the transaction to a healthy state:

```
  // In DoctrineDbalAdapter::doSave()
  protected function doSave(array $values, int $lifetime): array|bool
  {
      if ($this->conn->getTransactionNestingLevel() > 0) {
          $this->conn->createSavepoint('cache_save');
          try {
              $result = parent::doSave($values, $lifetime);
              $this->conn->releaseSavepoint('cache_save');
              return $result;
          } catch (\Throwable $e) {
              $this->conn->rollbackSavepoint('cache_save');
              throw $e;
          }
      }

      return parent::doSave($values, $lifetime);
  }

```
  This preserves the existing behavior (exceptions are still caught by AbstractAdapter::commit()) while preventing PostgreSQL transaction poisoning.

### Additional Context

Environment

  - Symfony Cache 7.x
  - Doctrine DBAL 4.x
  - PostgreSQL 15+
  - PHP 8.4

### PR DESCRIPTION
**Pull request by lacatoire**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63417
| License       | MIT

## Summary

When `DoctrineDbalAdapter` is used within an active PostgreSQL transaction (e.g. inside a Symfony Messenger transactional middleware), a cache save failure silently corrupts the transaction. `AbstractAdapter::commit()` catches the exception, but PostgreSQL marks the transaction as aborted (`SQLSTATE 25P02`) — all subsequent queries fail with a misleading error.

## Fix

When a transaction is active, wrap the `doSave()` operation in a `SAVEPOINT`. If the save fails, `ROLLBACK TO SAVEPOINT` restores the transaction to a healthy state before the exception propagates.

The original `doSave()` logic is extracted into a private `doSaveInner()` method, called either directly (no transaction) or within the savepoint wrapper.

The DBAL `createSavepoint()` / `releaseSavepoint()` / `rollbackSavepoint()` methods are available in all supported DBAL versions (2.13+, 3.x, 4.x).

## Reproduction scenario

```php
$connection->beginTransaction();
// Cache miss → doSave() INSERT fails (deadlock, constraint, etc.)
$value = $cache->get('key', fn () => 'computed');
// $value is returned fine, but...
$connection->executeQuery('SELECT 1'); // 💥 SQLSTATE 25P02
```

With this fix, the savepoint absorbs the failed INSERT and the transaction remains usable.

### CODE REVIEW

File: src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php [hunk 1]
```diff
@@ -244,6 +244,25 @@ protected function doSave(array $values, int $lifetime): array|bool
             return $failed;
         }
 
+        if ($this->conn->isTransactionActive()) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php]: we should also verify that the platform supports save points

**Comment by nicolas-grekas** [comment]
Thank you @lacatoire.
