### PR TITLE
[Console] Fixed #29835: ConfirmationQuestion with default true for answer '0'

### LINKED ISSUE #29835: ConfirmationQuestion normalizer may behave unexpectedly for Y/N question
**Symfony version(s) affected**: 4.2

**Description**  
When using the ConfirmationQuestion class to ask a yes / no question, if the default is true, and the answer regex is '/^y/i', then any value not starting with [yY] is considered false - except "0"

**How to reproduce**  
Create a console application, and in the execute method:
```
    $question = new ConfirmationQuestion("Yes or No?", true);
    $ans = $this->io->askQuestion($question); 
    echo $ans ? 'true' : 'false';
```
Then run it, and observe the output:
Input: "yes", "y", "YES", "Y", "" (empty string) etc
Output: "true"
Input "no", "No", "foo", "Bar", "1", "true" etc
Output: "false"
Input: "0"
Output: "true" <- I would expect false, as the string does not match the regex

**Possible Solution**
https://github.com/symfony/console/blob/4a5d48d2ca2422c5c02ed37e4146fb65591369d5/Question/ConfirmationQuestion.php
```
    private function getDefaultNormalizer()
    {
        $default = $this->getDefault();
        $regex = $this->trueAnswerRegex;
        return function ($answer) use ($default, $regex) {
            if (\is_bool($answer)) {
                return $answer;
            }
            $answerIsTrue = (bool) preg_match($regex, $answer);
            if (false === $default) {
                return $answer && $answerIsTrue;
            }
            return !$answer || $answerIsTrue;
        };
    }
```
Change [line 56](https://github.com/symfony/console/blob/4a5d48d2ca2422c5c02ed37e4146fb65591369d5/Question/ConfirmationQuestion.php#L56:) (last return) to:
```
return strlen($answer) === 0 ? $default : $answerIsTrue;
```

### PR DESCRIPTION
**Pull request by mrthehud**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | Almost all, one failure on appveyor?
| Fixed tickets | #29835 
| License       | MIT
| Doc PR        | n/a

When using the ConfirmationQuestion class to ask a yes / no question,
if the default is true, and the answer regex is '/^y/i', then any
value not starting with [yY] is considered false.

This must include "0", which previously would return true, producing results such as:
```
$ php bin/console do:stuff
$ Do you want to continue? 0 <enter>
$ Ok, continuing!
```

### CODE REVIEW

**Review by ro0NL — APPROVED** [review]

File: src/Symfony/Component/Console/Tests/Question/ConfirmationQuestionTest.php [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+{
+    /**
+     * @dataProvider normalizerUsecases
+     */
+    public function testDefaultRegexUsecases($default, $answers, $expected, $message)
+    {
+        $sut = new ConfirmationQuestion('A question', $default);
+
+        foreach ($answers as $answer) {
+            $actual = $sut->getNormalizer()($answer);
```
Comment (chalasr) [inline src/Symfony/Component/Console/Tests/Question/ConfirmationQuestionTest.php]: 3.4 supports PHP 5.5, the result of `getNormalizer()` needs to be assigned before being called (see travis)

**Review by chalasr — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Console/Tests/Question/ConfirmationQuestionTest.php (hunk 1 above)
Comment (ro0NL) [reply src/Symfony/Component/Console/Tests/Question/ConfirmationQuestionTest.php]: ouch :) nice catch.

**Comment by mrthehud** [comment]
That Appveyor test that's failing looks completely unrelated, and passes locally. Any ideas chaps?

**Comment by chalasr** [comment]
@mrthehud that's unrelated indeed, don't worry about it.

File: src/Symfony/Component/Console/Tests/Question/ConfirmationQuestionTest.php [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+        return [
+            [
+                true,
+                ['y', 'Y', 'yes', 'YES', 'yEs', ''],
+                true,
+                'When default is true, the normalizer must return true for "%s"',
+            ],
+            [
+                true,
+                ['n', 'N', 'no', 'NO', 'nO', 'foo', '1', '0'],
```
Comment (chalasr) [inline src/Symfony/Component/Console/Tests/Question/ConfirmationQuestionTest.php]: IMO `1` should keep being considered as `true` in all cases, and making it `false` now feels risky for existing apps. 
I suggest to change ConfirmationQuestion:51 so that it takes it into account e.g.
`$answerIsTrue =  '1' == $answer || preg_match($regex, $answer);`

Comment (mrthehud) [reply src/Symfony/Component/Console/Tests/Question/ConfirmationQuestionTest.php]: I can see where you're coming from, but `1` never was considered true when the default is true - anything that wasn't an empty string or 'y' would be considered a falsely answer (I am only testing the default regex here) - so changing this now would be altering behaviour and increasing risk.
The only change made to this test to support my change in `ConfirmationQuestion` was the addition of '0' on the line above, so I think it would be safer to leave it as it is.

Comment (chalasr) [reply src/Symfony/Component/Console/Tests/Question/ConfirmationQuestionTest.php]: Indeed, you're right.

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @mrthehud.
