### PR TITLE
#20411 fix Yaml parsing for very long quoted strings

### LINKED ISSUE #20411: PREG_BACKTRACK_LIMIT_ERROR in Yaml parser
A YAML string with too many backslash escapes can trigger a `PREG_BACKTRACK_LIMIT_ERROR ` error in the Yaml parser.

## Steps to reproduce:

Run the following unit test:

```php
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\Yaml\Yaml;

class YamlParserBacktrackLimitTest extends WebTestCase
{
    public function testYamlQuotedString() {

        $foo = str_repeat("x\r\n\\\"x\"x", 1000);
        $yamlString = Yaml::dump(["foo" => $foo]);

        $arrayFromYaml = Yaml::parse($yamlString);

        $this->assertEquals($foo, $arrayFromYaml['foo']);
    }
}
```

## Observed behaviour

This test will pass if you reduce the "1000" constant to "100", and fail as-is.

The reported exception is:
```
Malformed inline YAML string ("x\r\n\\\ ...
at n/a
        in ...\vendor\symfony\symfony\src\Symfony\Component\Yaml\Inline.php line 344
```

The relevant source [is here](https://github.com/symfony/symfony/blob/172d0a4c08f11e1f1e1f9ad28302d3a8bda51492/src/Symfony/Component/Yaml/Inline.php#L344): 

```
       const REGEX_QUOTED_STRING = '(?:"([^"\\\\]*(?:\\\\.[^"\\\\]*)*)"|\'([^\']*(?:\'\'[^\']*)*)\')';
...
        if (!preg_match('/'.self::REGEX_QUOTED_STRING.'/Au', substr($scalar, $i), $match)) {
            throw new ParseException(sprintf('Malformed inline YAML string: %s.', substr($scalar, $i)));
        }

```

## Expected behaviour

1. The test should pass, i.e. the YAML should be parseable, since it fits in memory and is well formed.

2. The exception thrown by Symfony if the `preg_match` fails due to `PREG_BACKTRACK_LIMIT_ERROR` should indicate that the op failed due to resource exhaustion and not incorrectly blame invalid YAML.

## Suggested fix

I suspect that changing the `REGEX_QUOTED_STRING` regex to use [possessive qualifiers](http://www.regular-expressions.info/possessive.html) will probably fix bug 1 above without otherwise changing the YAML parser's behaviour.

Fixing bug 2 above needs a call to `preg_last_error()` after each "`preg_match`" call in Symfony code, which will be tedious.

### PR DESCRIPTION
**Pull request by RichardBradley**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20411
| License       | MIT
| Doc PR        | no

This fixes #20411, a YAML string with too many backslash escapes can trigger a `PREG_BACKTRACK_LIMIT_ERROR` error in the Yaml parser.

There should be no behavioural change other than the bug fix

I have included a test which fails before this fix and passes after this fix.

### CODE REVIEW

File: src/Symfony/Component/Yaml/Tests/InlineTest.php [hunk 1]
```diff
@@ -410,4 +410,14 @@ public function testNotSupportedMissingValue()
     {
         Inline::parse('{this, is not, supported}');
     }
+
+    public function testVeryLongQuotedStrings()
+    {
+        $longStringWithQuotes = str_repeat("x\r\n\\\"x\"x", 1000);
+
+        $yamlString = Inline::dump(['longStringWithQuotes' => $longStringWithQuotes]);
```
Comment (stof) [inline src/Symfony/Component/Yaml/Tests/InlineTest.php]: the short array syntax does not work on PHP 5.3, which is still supported by Symfony 2.7. Please change it.

**Review by stof — CHANGES_REQUESTED** [review]

**Comment by stof** [comment]
👍 (once the PHP 5.3 compat is fixed of course)

File: src/Symfony/Component/Yaml/Tests/InlineTest.php (hunk 1 above)
Comment (RichardBradley) [inline src/Symfony/Component/Yaml/Tests/InlineTest.php]: Sorry, good point. 
I've pushed a new version.

**Review by stof — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you @RichardBradley.
