### PR TITLE
[FrameworkBundle][HttpKernel] Fix resources loading for bundles with custom structure

### LINKED ISSUE #18563: Serializer and Validator mappings don't use Bundle#getPath()
## Description

The bundle class has a `getPath()` method, allowing you to override the path of the bundle. However, inside the FrameworkExtension, `$reflection->getFileName()` is used to get the path to the bundle. This means that `getPath()` is ignored.
## Use-case

In my case, my bundle directory structure looks like:

``` php
MyBundle/
  src/
    MyBundle.php
    ...
  Resources/
    config/
      serializer.yml
      validator.yml
```

In the `MyBundle` class, I override `getPath()` to return `MyBundle/`. This way, I would expect the serializer and validator configuration to be loaded. However, since they use reflection they're looking for `MyBundle/src/Resources/config/serializer.yml`.
## Possible Solution

The auto-discovery of config files should be moved to a compiler pass. These have access to the bundle class instance (instead of FQCN) and can call `->getPath()` on this instance instead of simulating the default behaviour of this method.

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/issues/18563
| License       | MIT
| Doc PR        |  n/a

This fixes twig/translator/validator/serializer resource loading for bundles overriding `Bundle::getPath()`, adding a kernel parameter containing the bundle metadata (i.e. `path`, `namespace` and `parent`).

Fixes #18563 and unlocks https://github.com/symfony/symfony/pull/19586

### CODE REVIEW

**Comment by ogizanagi** [comment]
I hope this can be accepted as a bugfix rather than a new feature though :/

**Comment by xabbuh** [comment]
The minimum required version of the HttpKernel component in the FrameworkBundle must be updated from `~2.7.15|~2.8.8` to `~2.7.23|~2.8.16`.

**Comment by chalasr** [comment]
@xabbuh thanks, done

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -692,12 +692,11 @@ private function registerTranslatorConfiguration(array $config, ContainerBuilder
             $dirs[] = dirname(dirname($r->getFileName())).'/Resources/translations';
         }
         $rootDir = $container->getParameter('kernel.root_dir');
-        foreach ($container->getParameter('kernel.bundles') as $bundle => $class) {
-            $reflection = new \ReflectionClass($class);
-            if (is_dir($dir = dirname($reflection->getFileName()).'/Resources/translations')) {
+        foreach ($container->getParameter('kernel.bundles_metadata') as $name => $bundle) {
+            if (is_dir($dir = dirname($bundle['path']).'/Resources/translations')) {
```
Comment (xabbuh) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Calling `dirname()` here (and in all places below) looks wrong to me as the `path` key should already just refer to directory in which the bundle is stored.

Comment (chalasr) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: indeed, fixed

Comment (xabbuh) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Maybe it would be good to have a dedicated test case working with a bundle that follows the default behaviour to detect a similar issue in the future?

**Comment by chalasr** [comment]
Tests are green

File: src/Symfony/Component/HttpKernel/Kernel.php [hunk 2]
```diff
@@ -531,8 +531,11 @@ protected function initializeContainer()
     protected function getKernelParameters()
     {
         $bundles = array();
+        $bundlesMetadata = array();
+
         foreach ($this->bundles as $name => $bundle) {
             $bundles[$name] = get_class($bundle);
+            $bundlesMetadata[$name] = array('parent' => $bundle->getParent(), 'path' => $bundle->getPath(), 'namespace' => $bundle->getNamespace());
```
Comment (xabbuh) [inline src/Symfony/Component/HttpKernel/Kernel.php]: To make this more readable I would change the code style to this:

```php
$bundlesMetadata[$name] = array(
    'parent' => $bundle->getParent(),
    'path' => $bundle->getPath(),
    'namespace' => $bundle->getNamespace(),
);
```

**Comment by xabbuh** [comment]
👍 

Status: Reviewed

**Comment by xabbuh** [comment]
ping @symfony/deciders

**Comment by stof** [comment]
This should also update the TwigBundle path registration

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 1 above)
Comment (chalasr) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Sorry, I missed this comment. I think the test you have in mind already exists, the one added here is a copy paste: https://github.com/symfony/symfony/pull/21113/files#diff-b0c828e732d3d31f0b2bfb2378bd1011R340 
Correct me if I'm wrong

**Comment by chalasr** [comment]
@stof done

File: src/Symfony/Bundle/TwigBundle/composer.json [hunk 3]
```diff
@@ -21,7 +21,7 @@
         "symfony/twig-bridge": "~2.7",
         "twig/twig": "~1.28|~2.0",
         "symfony/http-foundation": "~2.5",
-        "symfony/http-kernel": "~2.7"
+        "symfony/http-kernel": "~2.7.23"
```
Comment (fabpot) [inline src/Symfony/Bundle/TwigBundle/composer.json]: This forbids using 2.8, you should add `|~2.8.16`.

Comment (chalasr) [inline src/Symfony/Bundle/TwigBundle/composer.json]: fixed

**Comment by fabpot** [comment]
Thank you @chalasr.
