### PR TITLE
[Messenger] Add `TransportNamesStamp` to change the transport while dispatching a message

### LINKED ISSUE #38200: [Messenger] Defining transport dynamically
**Description**  
Current implementation forces applications to define which transport(s) to use with a class in configuration file. It would be great if it was possible to dictate transport in business logic.

This might be a common problem for other developers, that's why I thought it would be good to make it part of symfony/messenger instead of overriding a Symfony class in business application. 

**Example**

Before:
```yml
framework:
    messenger:
        transports:
            normal_queue: ...
            important_queue: ...
        routing:
            App\Message\SmsNotification': normal_queue
```

```php
<?php
// comments, trademark, use statements and constructor removed for PR description
namespace Symfony\Component\Messenger\Transport\Sender;

class SendersLocator implements SendersLocatorInterface
{
    public function getSenders(Envelope $envelope): iterable
    {
        $seen = [];

        foreach (HandlersLocator::listTypes($envelope) as $type) {
            foreach ($this->sendersMap[$type] ?? [] as $senderAlias) {
                if (!\in_array($senderAlias, $seen, true)) {
                    if (!$this->sendersLocator->has($senderAlias)) {
                        throw new RuntimeException(sprintf('Invalid senders configuration: sender "%s" is not in the senders locator.', $senderAlias));
                    }

                    $seen[] = $senderAlias;
                    $sender = $this->sendersLocator->get($senderAlias);
                    yield $senderAlias => $sender;
                }
            }
        }
    }
}
```

After:
```php
<?php
// comments, trademark, use statements and constructor removed for PR description
namespace Symfony\Component\Messenger\Transport\Sender;

class SendersLocator implements SendersLocatorInterface
{
    public function getSenders(Envelope $envelope): iterable
    {
        if ($envelope->all(OverrideSendersStamp::class)) {
            $overrideSendersStamp = $envelope->last(OverrideSendersStamp::class);

            foreach ($overrideSendersStamp->getSenders() as $senderAlias) {
                yield from $this->getSenderFromAlias($senderAlias);
            }
        } else {
            $seen = [];
    
            foreach (HandlersLocator::listTypes($envelope) as $type) {
                foreach ($this->sendersMap[$type] ?? [] as $senderAlias) {
                    if (!\in_array($senderAlias, $seen, true)) {
                        $seen[] = $senderAlias;

                        yield from $this->getSenderFromAlias($senderAlias);
                    }
                }
            }
        }
    }

    private function getSenderFromAlias(string $senderAlias): iterable
    {
        if (!$this->sendersLocator->has($senderAlias)) {
            throw new RuntimeException(sprintf('Invalid senders configuration: sender "%s" is not in the senders locator.', $senderAlias));
        }

        $sender = $this->sendersLocator->get($senderAlias);
        yield $senderAlias => $sender;
    }
}
```

In applications, developers can use it like below

```php
// This will be in normal_queue
$bus->dispatch(new SmsNotification('...'));
```

For overridden behaviour:
```php
// This will be in important_queue
$bus->dispatch(new Envelope(new SmsNotification('...'), [
  new OverrideSendersStamp(['important_queue'])
]));
```

### PR DESCRIPTION
**Pull request by abarkine**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #38200, Fix #39306
| License       | MIT
| Doc PR        | https://github.com/symfony/symfony-docs/issues/17113

This feature will allow developers to choose transport layer while dispatching a message. Normally, we define transport layer in configuration. As a result, developer doesn't have any power to modify it after the deployment. This PR aims to allow overriding already defined transport layer for a message and rerouting it to different transport per dispatch request.

If newly added stamp is not used, default configuration will be used for choosing transport.

Since I've added a new stamp, there shouldn't be any BC change.

### CODE REVIEW

File: src/Symfony/Component/Messenger/Transport/Sender/SendersLocator.php [hunk 1]
```diff
@@ -41,20 +42,33 @@ public function __construct(array $sendersMap, ContainerInterface $sendersLocato
...
-        foreach (HandlersLocator::listTypes($envelope) as $type) {
-            foreach ($this->sendersMap[$type] ?? [] as $senderAlias) {
-                if (!\in_array($senderAlias, $seen, true)) {
-                    if (!$this->sendersLocator->has($senderAlias)) {
-                        throw new RuntimeException(sprintf('Invalid senders configuration: sender "%s" is not in the senders locator.', $senderAlias));
-                    }
+            foreach ($overrideSendersStamp->getSenders() as $senderAlias) {
+                yield from $this->getSenderFromAlias($senderAlias);
+            }
+        } else {
```
Comment (jderusse) [inline src/Symfony/Component/Messenger/Transport/Sender/SendersLocator.php]: You could use early return here and remove this `else` statement. That would simplify the diff

File: src/Symfony/Component/Messenger/Transport/Sender/SendersLocator.php [hunk 2]
```diff
@@ -41,20 +42,33 @@ public function __construct(array $sendersMap, ContainerInterface $sendersLocato
      */
     public function getSenders(Envelope $envelope): iterable
     {
-        $seen = [];
+        if (\count($envelope->all(OverrideSendersStamp::class)) > 0) {
+            $overrideSendersStamp = $envelope->last(OverrideSendersStamp::class);
```
Comment (jderusse) [inline src/Symfony/Component/Messenger/Transport/Sender/SendersLocator.php]: Would be great to have tests for this section section

**Review by jderusse — COMMENTED** [review]
Thank you for this contribution.

What if people want keeping the original senders?.

I wonder if we couldn't use something similar to the `BusNameStamp`:
- use a middleware that initialize the envelope with a `SenderNamesStamp` 
- send the envelope to the senders contained in the last `SenderNamesStamp`

File: src/Symfony/Component/Messenger/Transport/Sender/SendersLocator.php (hunk 2 above)
Comment (abarkine) [reply src/Symfony/Component/Messenger/Transport/Sender/SendersLocator.php]: Once we finalize the approach, I will add the tests

**Comment by abarkine** [comment]
> BusNameStamp and using middleware to insert Stamp

Wouldn't it add an overhead? In current way, Envelope will not include OverrideStamp if not necessary. What do you think?

**Comment by diimpp** [comment]
On naming note, public stamp name shouldn't be derived from this moment internal implementation, so something like `SendersOverride` is not very suitable in my opinion.

As library user, who is not privy to all the internals, first naming choice would be `TransportRouteStamp`, but I do see that the  `routing` is the framework-bundle config concept, rather than messenger concept, so maybe `TransportSendersStamp`

**Comment by abarkine** [comment]
> On naming note, public stamp name shouldn't be derived from this moment internal implementation, so something like `SendersOverride` is not very suitable in my opinion.
> 
> As library user, who is not privy to all the internals, first naming choice would be `TransportRouteStamp`, but I do see that the `routing` is the framework-bundle config concept, rather than messenger concept, so maybe `TransportSendersStamp`

@diimpp , thanks for your input, I will change the name, what do you think about the implementation?

**Comment by diimpp** [comment]
@asilelik looks alright to me, but I'm not a messenger specialist.

One more thing, I don't why there are multiple senders routing in the messenger and what is the use case, but maybe you will want to allow to have both behaviors to override/extend senders config with bool flag at Stamp class.

**Comment by abarkine** [comment]
> @asilelik looks alright to me, but I'm not a messenger specialist.
> 
> One more thing, I don't why there are multiple senders routing in the messenger and what is the use case, but maybe you will want to allow to have both behaviors to override/extends senders config with bool flag at Stamp class.

Do you mean to send envelope to both configured transport and overridden one?

**Comment by diimpp** [comment]
> > @asilelik looks alright to me, but I'm not a messenger specialist.
> > One more thing, I don't why there are multiple senders routing in the messenger and what is the use case, but maybe you will want to allow to have both behaviors to override/extends senders config with bool flag at Stamp class.
> 
> Do you mean to send envelope to both configured transport and overridden one?

For example if somebody already have their transports setup, but want conditionally to specify `audit` transport for certain messages.

Then they will want to keep their original transports list and just add another one, e.g. `new TransportSendersStamp(['audit'], $extendSenders = true)`

My personal use case is quite different, I need to conditionally send messeges to sync or async transports, so I will need to override original transports routing if preset, e.g. `new TransportSendersStamp(['async'], $overrideSenders = true)`

**Comment by abarkine** [comment]
> > > @asilelik looks alright to me, but I'm not a messenger specialist.
> > > One more thing, I don't why there are multiple senders routing in the messenger and what is the use case, but maybe you will want to allow to have both behaviors to override/extends senders config with bool flag at Stamp class.
> > 
> > 
> > Do you mean to send envelope to both configured transport and overridden one?
> 
> For example if somebody already have their transports setup, but want conditionally to specify `audit` transport for certain messages.
> 
> Then they will want to keep their original transports list and just add another one, e.g. `new TransportSendersStamp(['audit'], $extendSenders = true)`
> 
> My personal use case is quite different, I need to conditionally send messeges to sync or async transports, so I will need to override original transports routing if preset, e.g. `new TransportSendersStamp(['async'], $overrideSenders = true)`

Good point. It will make SendersLocator class a bit complex but I guess it will add a great value to the Stamp.

**Comment by abarkine** [comment]
@jderusse , can you take a second look at this PR and comment on suggestions? If you are fine with current implementation, I will create the tests to finalize PR.

**Comment by r6rob** [comment]
My use case is very similar to @diimpp. Building a job queue and would love to specify whether a job will be handled as sync or async programatically.

This would be very helpful, eagerly awaiting PR.

**Comment by chalasr** [comment]
@asilelik Thank you for the PR. Please go ahead with the missing tests, this looks good to me.

**Comment by abarkine** [comment]
@chalasr I've added the test. Apart from `git rebase` error, how can I fix other failures? They don't seem like related errors to my PR.

File: src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+
+/**
+ * Apply this stamp to change sender to be used instead of the one from configuration file.
+ */
+final class OverrideSendersStamp implements StampInterface
+{
+    private array $senders;
+
+    /**
+     * @param array $senders New senders to be used with message
```
Comment (chalasr) [inline src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php]: `string[] $senders`

File: src/Symfony/Component/Messenger/CHANGELOG.md [hunk 4]
```diff
@@ -7,6 +7,7 @@ CHANGELOG
  * Add `SerializedMessageStamp` to avoid serializing a message when a retry occurs.
  * Automatically resolve handled message type when method different from `__invoke` is used as handler.
  * Allow `#[AsMessageHandler]` attribute on methods.
+ * Added capability for modifying transport layer while dispatching message
```
Comment (chalasr) [inline src/Symfony/Component/Messenger/CHANGELOG.md]:
```suggestion
 * Add `OverrideSendersStamp` to change the transport while dispatching a message
```

**Comment by chalasr** [comment]
Yes, the failing test is unrelated.

**Comment by abarkine** [comment]
@chalasr what is the preferred way for getting rid of merge commit? Can I force push or is there any other suggestion?

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+ * Apply this stamp to change sender to be used instead of the one from configuration file.
+ */
+final class OverrideSendersStamp implements StampInterface
+{
+    private array $senders;
+
+    /**
+     * @param string[] $senders New senders to be used with message
+     */
+    public function __construct(array $senders)
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php]: we could use constructor property promotion here

File: src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php [hunk 6]
```diff
@@ -0,0 +1,33 @@
...
+    {
+        $this->senders = $senders;
+    }
+
+    public function getSenders(): array
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php]: instead of accepting several sender, what about accepting one? multiple senders could still be defined by adding several `ViaSenderStamp` (proposed name :) )

File: src/Symfony/Component/Messenger/Transport/Sender/SendersLocator.php [hunk 7]
```diff
@@ -41,20 +42,35 @@ public function __construct(array $sendersMap, ContainerInterface $sendersLocato
      */
     public function getSenders(Envelope $envelope): iterable
     {
+        if (\count($envelope->all(OverrideSendersStamp::class)) > 0) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Transport/Sender/SendersLocator.php]: this can be simplified to (reusing my previous proposal):
`if ($senders = $envelope->all(ViaSenderStamp::class)) {

File: src/Symfony/Component/Messenger/Transport/Sender/SendersLocator.php [hunk 8]
```diff
@@ -41,20 +42,35 @@ public function __construct(array $sendersMap, ContainerInterface $sendersLocato
...
         foreach (HandlersLocator::listTypes($envelope) as $type) {
             foreach ($this->sendersMap[$type] ?? [] as $senderAlias) {
                 if (!\in_array($senderAlias, $seen, true)) {
-                    if (!$this->sendersLocator->has($senderAlias)) {
-                        throw new RuntimeException(sprintf('Invalid senders configuration: sender "%s" is not in the senders locator.', $senderAlias));
-                    }
-
                     $seen[] = $senderAlias;
-                    $sender = $this->sendersLocator->get($senderAlias);
-                    yield $senderAlias => $sender;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Transport/Sender/SendersLocator.php:55]: what does this provide? if this is pure refacto (as it looks to me at the moment), then this should be reverted

**Review by nicolas-grekas — COMMENTED** [review]
Thanks for the PR. It looks good to me, I just have minor questions/proposals.

File: src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php (hunk 6 above)
Comment (abarkine) [reply src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php]: My first use case was for simple sender change but I guess it would be healthier to keep multiple senders in same Stamp. I don't have a strong opinion, open for suggestion :)

File: src/Symfony/Component/Messenger/Transport/Sender/SendersLocator.php (hunk 8 above)
Comment (abarkine) [reply src/Symfony/Component/Messenger/Transport/Sender/SendersLocator.php:55]: To reuse the logic in above if condition, I've separated this part into another method. What is your concern, why it should be removed?

Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Transport/Sender/SendersLocator.php:55]: got it thanks

File: src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php [hunk 9]
```diff
@@ -0,0 +1,30 @@
...
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\Messenger\Stamp;
+
+/**
+ * Apply this stamp to change sender to be used instead of the one from configuration file.
+ */
+final class ViaSenderStamp implements StampInterface
```
Comment (chalasr) [inline src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php]: The class name doesn't match the filename anymore

File: src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php (hunk 6 above)
Comment (chalasr) [reply src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php]: no strong opinion either but if we only look at the stamp, it's less clear to me that adding one `ViaSenderStamp` is going to erase all senders set via the framework config

**Comment by nicolas-grekas** [comment]
> if we only look at the stamp, it's less clear to me that adding one ViaSenderStamp is going to erase all senders set via the framework config

This maps to @jderusse's comment:
> What if people want keeping the original senders?.

What about conflicting when both are sent? Aka throw if a sender is configured while the stamp is also used? That'd make the situation impossible.

File: src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php (hunk 9 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php]: any opinion about the best name `ViaSenderStamp`? `SenderNamesStamp`? (`OverrideSendersStamp` wouldn't fit if we go with [my proposal](https://github.com/symfony/symfony/pull/39306#issuecomment-1084588686) to not allow senders to be set via both config and stamps)

**Comment by chalasr** [comment]
I missed that Jérémy's comment, thanks.

> What about conflicting when both are sent?

Given the originally proposed name, I suppose one may want to configure the sender the regular way and use the stamp to change the sender under certain circumstances only. 
Maybe the stamp could take a flag controlling whether to replace existing senders or not?

**Comment by tg-mvooges** [comment]
> > if we only look at the stamp, it's less clear to me that adding one ViaSenderStamp is going to erase all senders set via the framework config
> 
> This maps to @jderusse's comment:
> 
> > What if people want keeping the original senders?.
> 
> What about conflicting when both are sent? Aka throw if a sender is configured while the stamp is also used? That'd make the situation impossible.

I've not read the full thread (just the last few messages) but I would not for for a "when both are set". I would expect an either/or situation: You either use the default symfony-sender-decider-logic, OR the specified ones. If you would override the default configed target queue via a Stamp I think that could be made obvious with a clear name.

To add a little insight on how we would like to use this: We have a few microservices which listen to the queue via the normal config. The failed messages all get send to a central located microservice which has logic to place them back on their respective queues.
But that could be any queue, the central micro doesnt perse know everything. It has to now, which is inconvinient

**Comment by TCM-dev** [comment]
I'm also of the opinion that this should either use the default configured ones OR the specified ones (which I believe makes sense with the stamp name **OverrideSendersStamp**)

I personnaly need this because in my application, I need to have the same message/handler to have a different priority depending on some context. (I can provide real world example if needed)

Unless I'm mistaken, the only way I could do this right now would require me to duplicate the message/handlers with another name and configure them with another transport which is not ideal.

Adding one stamp to decide if a message has an higher priority than another on the fly makes perfect sense to me and I was persuaded that it was actually a feature in messenger.

Are the unsuccessful checks the only things preventing this to be merged or is this still open to discussion?

File: src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php (hunk 9 above)
Comment (fabpot) [reply src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php]: `SenderNamesStamp` seems more consistent with `BusNameStamp`

File: src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php (hunk 6 above)
Comment (fabpot) [reply src/Symfony/Component/Messenger/Stamp/OverrideSendersStamp.php]: I like it this way.

**Review by fabpot — COMMENTED** [review]
I've rebased this PR and made some naming changes to finish it.

**Comment by tg-mvooges** [comment]
> I've rebased this PR and made some naming changes to finish it.

I'm not 100% sure, but does this now ADD senders instead of overwriting? That might be slightly limiting. Not for my case, but supose you have a message default send to queueA and you want to CHANGE that to queueB. If you can only ADD, that might be problematic. Using an Override of some kind might be a more broad solution. Or some other method to reset the current senders.

Again, doesnt bother me, I'm looking forward for this feature either way ^_^

**Comment by fabpot** [comment]
@tg-mvooges That's the case. See https://github.com/symfony/symfony/pull/39306/files#diff-357beebf345f58f777f74eb1127331b8107de09438ff78435093085a531c52beR52, if the stamp is set, we return and bypass the default configuration. Did I miss something?

**Comment by TCM-dev** [comment]
> @tg-mvooges That's the case. See https://github.com/symfony/symfony/pull/39306/files#diff-357beebf345f58f777f74eb1127331b8107de09438ff78435093085a531c52beR52, if the stamp is set, we return and bypass the default configuration. Did I miss something?

Looks perfect to me and more consistent with other stamp names.
I'm just wondering if "sender" is the correct word, the documentation talks about "transport", this issue talk about being able to change "transport" and yet we name it sender.
I may be wrong but wouldn't it be even better if it was named TransportsStamp/TransportNamesStamp ?

**Comment by fabpot** [comment]
> > @tg-mvooges That's the case. See https://github.com/symfony/symfony/pull/39306/files#diff-357beebf345f58f777f74eb1127331b8107de09438ff78435093085a531c52beR52, if the stamp is set, we return and bypass the default configuration. Did I miss something?
> 
> Looks perfect to me and more consistent with other stamp names. I'm just wondering if "sender" is the correct word, the documentation talks about "transport", this issue talk about being able to change "transport" and yet we name it sender. I may be wrong but wouldn't it be even better if it was named TransportsStamp/TransportNamesStamp ?

Even if Sender is the right word, I think you're right that using Transport is easier to understand. Updated accordingly.

**Comment by fabpot** [comment]
Thank you @asilelik.

**Comment by tg-mvooges** [comment]
> @tg-mvooges That's the case. See https://github.com/symfony/symfony/pull/39306/files#diff-357beebf345f58f777f74eb1127331b8107de09438ff78435093085a531c52beR52, if the stamp is set, we return and bypass the default configuration. Did I miss something?

Ah, with the focus on that snippet, yes that seems perfect! I'm fairly new to this message concept, I'm still getting used to this 'Stamps' logic and how it works. Great feature coming up, looking forward to be able to use it, good job!
