### PR TITLE
[HttpFoundation] Set content-type header in RedirectResponse

### LINKED ISSUE #54434: RedirectResponse is sent with invalid content-type when route has non-html default format
### Symfony version(s) affected

5.x.x, probably even earlier

### Description

When a route has a default format set to smth else than html, and a redirect happens, the response format gets set on the redirect response incorrectly (because RedirectResponse [always has html as content](https://github.com/symfony/symfony/blob/f3403517d8f5c61bd19c5b057ee4ac22f538b2c2/src/Symfony/Component/HttpFoundation/RedirectResponse.php#L73-L88))

This isn't a huge problem in practice as the browser typically does not render this intermediate page's content, but it is nonetheless incorrect.

### How to reproduce

```php
#[Route('/test', name: 'test', defaults: ['_format' => 'json'])]
public function testAction()
{
        return $this->redirect('/test2');
}
```

Load /test, check the response headers of the 302:

```
HTTP/1.1 302 Found
Content-Type: application/json
Location: /test2
[...]
```

If the `_format=>json` is removed from the Route, then it uses the correct default:

```
Content-Type: text/html; charset=UTF-8
```

### Possible Solution

Perhaps the _format response listener should not mess with RedirectResponse instances?

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by smnandre**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54434
| License       | MIT

The RedirectResponse has no content-type set, leading to the response using the "current" one (see issue #54434)

As `setTargetUrl` set response body with HTML/UTF-8 content, it seems fair to add the matching header at this moment.

(not sure if really a _bug_ or not so i'm targetting 7.1 for now)

### CODE REVIEW

File: src/Symfony/Component/HttpFoundation/RedirectResponse.php [hunk 1]
```diff
@@ -85,6 +85,7 @@ public function setTargetUrl(string $url): static
 </html>', htmlspecialchars($url, \ENT_QUOTES, 'UTF-8')));
 
         $this->headers->set('Location', $url);
+        $this->headers->set('Content-Type', 'text/html; charset=UTF-8');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/RedirectResponse.php]:
```suggestion
        $this->headers->set('Content-Type', 'text/html; charset=utf-8');
```

**Review by nicolas-grekas — APPROVED** [review]
Looks like a bugfix to me :)

**Comment by smnandre** [comment]
> Looks like a bugfix to me :)

So i target 5.4 ?

**Review by xabbuh — APPROVED** [review]

**Comment by smnandre** [comment]
🤦  sorry guys for the notifications .... @xabbuh @nicolas-grekas if you can target 5.4 ... or i think i will make more mess....

File: src/Symfony/Component/HttpFoundation/Tests/RedirectResponseTest.php [hunk 2]
```diff
@@ -44,6 +44,14 @@ public function testGenerateLocationHeader()
         $this->assertEquals('foo.bar', $response->headers->get('Location'));
     }
 
+    public function testGenerateContentTypeHeader()
+    {
+        $response = new RedirectResponse('foo.bar');
+
+        $this->assertTrue($response->headers->has('Content-Type'));
+        $this->assertEquals('text/html; charset=utf-8', $response->headers->get('Content-Type'));
```
Comment (dunglas) [inline src/Symfony/Component/HttpFoundation/Tests/RedirectResponseTest.php]:
```suggestion
        $this->assertSame('text/html; charset=utf-8', $response->headers->get('Content-Type'));
```

File: src/Symfony/Component/HttpFoundation/Tests/RedirectResponseTest.php [hunk 3]
```diff
@@ -44,6 +44,14 @@ public function testGenerateLocationHeader()
         $this->assertEquals('foo.bar', $response->headers->get('Location'));
     }
 
+    public function testGenerateContentTypeHeader()
+    {
+        $response = new RedirectResponse('foo.bar');
+
+        $this->assertTrue($response->headers->has('Content-Type'));
```
Comment (dunglas) [inline src/Symfony/Component/HttpFoundation/Tests/RedirectResponseTest.php]: This assertion can be removed as it is redundant with the next one.

**Review by dunglas — APPROVED** [review]
+1 as a bug fix too.

File: src/Symfony/Component/HttpFoundation/Tests/RedirectResponseTest.php (hunk 3 above)
Comment (smnandre) [reply src/Symfony/Component/HttpFoundation/Tests/RedirectResponseTest.php]: Done! Thank you

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @smnandre.
