### PR TITLE
[Messenger][AMQP] Use delivery_mode=2 by default

### LINKED ISSUE #34685: [Messenger] Looks like the delivery_mode=2 is missing
**Description**  

I was working on an application that uses Swarrot and I notice it does not publish (by default)  messages with `delivery_mode=2`. 

It's very important to set this property if you don't want to loose messages.

Durable queue is not enough!
TL;DR:
* Durable queue means the queue will be persisted after a crash (but content will be lost)
* Message with delivery_mode=2 will be persisted after a crash

So I looked into the Messager component to be sure we did not make the same mistake.
And ... It looks like we made the same error. I did not deeply search for delivery_mode=2 but at the first glance I was not able to find it. 

~~More over, it looks like it's not possible at all to to set the delivery_mode :/~~ 
**EDIT**: it looks like [is possible](https://github.com/sroze/messenger-enqueue-transport#setting-custom-configuration-on-your-message)

I'm not an expert of Messenger Component, this is why I'm opening this issue to be 100% sure we did not miss anything.

Thanks

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34685
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by lyrixx** [comment]
I have tested it:

```php
<?php

use Symfony\Component\Messenger\Transport\AmqpExt\AmqpStamp;
use Symfony\Component\Messenger\Transport\AmqpExt\Connection;

require __DIR__.'/vendor/autoload.php';

$connection = Connection::fromDsn('amqp://rabbitmq-3.lxd?exchange[name]=test');
$connection->publish('body', [], 0, new AmqpStamp('test'));
```

I have created an exchange (fanout) and a queue by hand.

---

This is not related, but I notice something strange: The component created the a queue `messages` for me :/ Why? Where does "messages" comes? I know it's the default exchange name but in my case, I forced the exchange name to `test` and my routing key was `test`. More over the exchange was in a fanout mode, so IMHO it does really make sens here to create the queue since a queue is already bound. Is there a way to avoid that?

File: src/Symfony/Component/Messenger/Transport/AmqpExt/Connection.php [hunk 1]
```diff
@@ -230,6 +230,7 @@ private function publishOnExchange(\AMQPExchange $exchange, string $body, string
     {
         $attributes = $amqpStamp ? $amqpStamp->getAttributes() : [];
         $attributes['headers'] = array_merge($attributes['headers'] ?? [], $headers);
+        $attributes['delivery_mode'] = $attributes['delivery_mode'] ?? 2;
```
Comment (nikophil) [inline src/Symfony/Component/Messenger/Transport/AmqpExt/Connection.php]: for readability purpose, shouldn't we use `\AMQP_DURABLE` instead of an arbitrary int?

Comment (lyrixx) [reply src/Symfony/Component/Messenger/Transport/AmqpExt/Connection.php]: I'm not sure `AMQP_DURABLE` means `delivery_mode=2`. 
`AMQP_DURABLE` is for the queue & exchange durability. Not the data
See the [documentation](https://github.com/pdezwart/php-amqp/blob/master/stubs/AMQP.php#L16-L19)

**Comment by pyrech** [comment]
Shouldn't this PR be considered as a bug fix? If not, that means that Symfony 4.4 & 5.0 will provide an AMQP connection that is not safe to use by default.

**Comment by lyrixx** [comment]
I agree with @pyrech here. 

To be really clear : Right now if you restart rabbitmq, you will loose all messages. This is really not safe.

@fabpot Are you OK to treat this PR as a bug fix ?

**Review by nicolas-grekas — APPROVED** [review]
As bug fix on 4.4/4.3 as it fits.

**Comment by lyrixx** [comment]
I updated the PR to targets 4.3

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Comment by weaverryan** [comment]
About the “messages” queue being created, you could create a separate issue for that. There is a queues config option and I think you could set it to an empty array to avoid this (but I could be wrong). In general, there are many different ways for using Amqp - and so we need to make it work as smoothly as possible for as many cases as we can.

**Comment by Tobion** [comment]
Seems fine to do this by default as many people don't know the default settings of AMQP it seems. But it will make the AMQP way slower. I used a transport decorator for this so far when I needed it.

```
/**
 * Decorates a transport and makes all messages getting sent persistent.
 */
class PersistentMessagesTransportDecorator implements TransportInterface, SetupableTransportInterface
{
    private const DELIVERY_MODE_PERSISTENT = 2;

    /**
     * @var TransportInterface
     */
    private $decoratedTransport;

    public function __construct(TransportInterface $decoratedTransport)
    {
        $this->decoratedTransport = $decoratedTransport;
    }

    public function setup(): void
    {
        if ($this->decoratedTransport instanceof SetupableTransportInterface) {
            $this->decoratedTransport->setup();
        }
    }

    public function get(): iterable
    {
        return $this->decoratedTransport->get();
    }

    public function ack(Envelope $envelope): void
    {
        $this->decoratedTransport->ack($envelope);
    }

    public function reject(Envelope $envelope): void
    {
        $this->decoratedTransport->reject($envelope);
    }

    public function send(Envelope $envelope): Envelope
    {
        return $this->decoratedTransport->send($this->addPersistentDeliveryModeToEnvelope($envelope));
    }

    private function addPersistentDeliveryModeToEnvelope(Envelope $envelope): Envelope
    {
        /** @var AmqpStamp|null $amqpStamp */
        $amqpStamp = $envelope->last(AmqpStamp::class);
        $attributes = $amqpStamp ? $amqpStamp->getAttributes() : [];
        $attributes['delivery_mode'] = self::DELIVERY_MODE_PERSISTENT;

        $amqpStampWithDeliveryMode = new AmqpStamp(
            $amqpStamp ? $amqpStamp->getRoutingKey() : null,
            $amqpStamp ? $amqpStamp->getFlags() : \AMQP_NOPARAM,
            $attributes
        );

        return $envelope->with($amqpStampWithDeliveryMode);
    }
}
```
