### PR TITLE
[Mailer] Fix string-cast of exceptions thrown by authenticator in EsmtpTransport

### LINKED ISSUE #45308: [Mailer] EsmtpTransport throws too much information into TransportException
### Symfony version(s) affected

4.3-6.1

### Description

When throwing a `TransportException` during authentication in `EsmtpTransport`, multiple authenticators are tried and their exceptions are collected in an array.
To generate the exception message for the resulting `TransportException`, this array is iterated and the exception is cast to string, leading to a full stack trace being passed inside the exception message.

```php
        # https://github.com/symfony/mailer/blob/6.1/Transport/Smtp/EsmtpTransport.php:190
        $message = sprintf('Failed to authenticate on SMTP server with username "%s" using the following authenticators: "%s".', $this->username, implode('", "', $authNames));
        foreach ($errors as $name => $error) {
            $message .= sprintf(' Authenticator "%s" returned "%s".', $name, $error);
        }
```

When displaying the exception message to a user, there is way too much information about the backend inside and it is unreadable.

### How to reproduce

Use a mailer with SMTPS, with invalid credentials and catch the resulting exception.
`echo $exception->getMessage()`

### Possible Solution

Instead of the exception being cast to a string, $error->getMessage() should be used.

```diff
        $message = sprintf('Failed to authenticate on SMTP server with username "%s" using the following authenticators: "%s".', $this->username, implode('", "', $authNames));
        foreach ($errors as $name => $error) {
-            $message .= sprintf(' Authenticator "%s" returned "%s".', $name, $error);
+            $message .= sprintf(' Authenticator "%s" returned "%s".', $name, $error->getMessage());
        }
```

### Additional Context

I'm happy to provide a PR.

### PR DESCRIPTION
**Pull request by wikando-ck**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45308 
| License       | MIT

Replace an exception that was being cast to string with a call to `getMessage()`.
This prevents information about the system leaking into the exception, (files/directories, stack trace).

Additionally (see https://symfony.com/releases):

I wasn't able to inject mocked authenticators, as they are instantiated in the constructor.
This makes unit testing very hard.
I was able to reproduce the problem with this test, but it will hit a real smtp server and should not be added to a testsuite.

```php
   // EsmtpTransportTest.php
   
    public function testAuthExceptionContainsNoStackTrace()
    {
        $transport = new EsmtpTransport('smtp.ionos.de', 465, true);
        $transport->setUsername("test");
        $transport->setPassword("test");
        $message = new Message();
        $message->setHeaders(new Headers(
            new MailboxListHeader("From", [Address::create('test@gmail.com')]),
            new MailboxListHeader("To", [Address::create('test@gmail.com')]))
        );
        try {
            $transport->send($message);
            $this->fail("Expected TransportException");
        } catch (TransportExceptionInterface $e) {
            $this->assertStringNotContainsString("Stack trace:", $e->getMessage());
            $this->assertStringNotContainsString('Symfony\Component\Mailer\Transport\Smtp', $e->getMessage());
        }
    }
```

### CODE REVIEW

File: src/Symfony/Component/Mailer/Transport/Smtp/EsmtpTransport.php [hunk 1]
```diff
@@ -183,7 +183,7 @@ private function handleAuth(array $modes): void
 
         $message = sprintf('Failed to authenticate on SMTP server with username "%s" using the following authenticators: "%s".', $this->username, implode('", "', $authNames));
         foreach ($errors as $name => $error) {
-            $message .= sprintf(' Authenticator "%s" returned "%s".', $name, $error);
+            $message .= sprintf(' Authenticator "%s" returned "%s".', $name, $error->getMessage());
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mailer/Transport/Smtp/EsmtpTransport.php]: better do this on L176, isn't it?

Comment (wikando-ck) [reply src/Symfony/Component/Mailer/Transport/Smtp/EsmtpTransport.php]: Hi Nicolas, yeah, i agree - it's better to do it there because we can be sure to have an exception within a try-catch block and the comment suggests that only the message is kept, too.
I have moved it there.

**Review by nicolas-grekas — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @wikando-ck.
