### PR TITLE
[MonologBridge] FirePHPHandler::onKernelResponse throws PHP 8.1 deprecation when no user agent is set

### LINKED ISSUE #49392: [MonologBridge] FirePHPHandler::onKernelResponse throws PHP 8.1 deprecation when no user agent is set
### Symfony version(s) affected

5.4.20 and above

### Description

When no user agent is set `FirePHPHandler::onKernelResponse` throws 

`Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated`

in PHP 8.1 and above

https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bridge/Monolog/Handler/FirePHPHandler.php#L44

### How to reproduce

I have no reproducer but it is an obvious potential problem because `HeaderBag::get` is allowed to return null.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by juagarc4**
| Q             | A
| ------------- | ---
| Branch?       |  5.4
| Bug fix?      | yes/no
| New feature?  no
| Deprecations? no
| Tickets       | Fix #49392  
| License       | MIT

- Add casting to the second parameter to pass always the right type.

**PHPstan before:**

 ------ -------------------------------------------------------------------------------------------------------- 
  Line   FirePHPHandler.php                                                                                      
 ------ -------------------------------------------------------------------------------------------------------- 
  27     Property Symfony\Bridge\Monolog\Handler\FirePHPHandler::$headers has no type specified.                 
  37     Method Symfony\Bridge\Monolog\Handler\FirePHPHandler::onKernelResponse() has no return type specified.  
  **44     Parameter #2 $subject of function preg_match expects string, string|null given.**                         
  68     If condition is always true.                                                                            
 ------ -------------------------------------------------------------------------------------------------------- 

**PHPstan after:**

 ------ -------------------------------------------------------------------------------------------------------- 
  Line   FirePHPHandler.php                                                                                      
 ------ -------------------------------------------------------------------------------------------------------- 
  27     Property Symfony\Bridge\Monolog\Handler\FirePHPHandler::$headers has no type specified.                 
  37     Method Symfony\Bridge\Monolog\Handler\FirePHPHandler::onKernelResponse() has no return type specified.  
  68     If condition is always true.                                                                            
 ------ --------------------------------------------------------------------------------------------------------

### CODE REVIEW

File: src/Symfony/Bridge/Monolog/Handler/FirePHPHandler.php [hunk 1]
```diff
@@ -41,7 +41,7 @@ public function onKernelResponse(ResponseEvent $event)
         }
 
         $request = $event->getRequest();
-        if (!preg_match('{\bFirePHP/\d+\.\d+\b}', $request->headers->get('User-Agent'))
+        if (!preg_match('{\bFirePHP/\d+\.\d+\b}', (string) $request->headers->get('User-Agent'))
```
Comment (Arman-Hosseini) [inline src/Symfony/Bridge/Monolog/Handler/FirePHPHandler.php]:
```suggestion
        if (!preg_match('{\bFirePHP/\d+\.\d+\b}', $request->headers->get('User-Agent', ''))
```

**Comment by nicolas-grekas** [comment]
Can you please add a test case?

**Comment by nicolas-grekas** [comment]
Thank you @juagarc4.
