### PR TITLE
[Security] [DataCollector] Remove allows anonymous information in datacollector

### LINKED ISSUE #40907: [Security][Profiler] “Allows anonymous” always false with enable_authenticator_manager
**Symfony version(s) affected**: ≥ 5.1.0

**Description**
In the profiler’s security panel there is an “Allows anonymous” box.

firewall

Since anonymous users no longer exist using the new authentication system it will always show a red cross.

**How to reproduce**
1. Enable `security.enable_authenticator_manager`
2. Load any page
3. Go to the profiler’s security panel

**Possible Solution**
Should we remove that box? It seems `FirewallConfig::allowsAnonymous` won’t make sense when `anonymous` is no longer allowed in firewalls configuration?

### PR DESCRIPTION
**Pull request by ismail1432**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | no
| New feature?  | yes/no 
| Deprecations? | yes/no 
| Tickets       | Fix #40907
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

As mentioned In https://github.com/symfony/symfony/issues/40907 there is no longer anonymous users no longer in the new authentication system. This PR remove this information **if the new system is used** as it always a red cross 

With  `enable_authenticator_manager` at `false`
image

With  `enable_authenticator_manager` at `true` 
image

### CODE REVIEW

**Comment by chalasr** [comment]
Thanks for the PR. 
I think this first has to be a bugfix for 5.2.

As you pointed out, this info is only relevant when the new authenticator system is not in use.
Could you update your patch to remove it only if `enable_authenticator_manager` is `true`? And revert the removal of `FirewallConfig::allowsAnonymous()`, as it will need to be deprecated first when the old system will been removed (in 6.x).

**Comment by ismail1432** [comment]
Thanks @chalasr for the feedback, Yes I'll do :+1:

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 1]
```diff
@@ -137,6 +137,7 @@ public function load(array $configs, ContainerBuilder $container)
             $loader->load('templating_twig.php');
         }
 
+        $container->setParameter('security.enable_authenticator_manager', $this->authenticatorManagerEnabled);
```
Comment (ismail1432) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]: I don't find a better way to "store" the information once fetched from the config file parsing

File: src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php [hunk 2]
```diff
@@ -219,6 +221,7 @@ public function reset()
 
     public function lateCollect()
     {
+        $this->data['authenticator_manager_enabled'] = $this->authenticatorManagerEnabled;
```
Comment (ismail1432) [inline src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php]: FYI doesn't works if this line is in `collect`

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php (hunk 1 above)
Comment (wouterj) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]: I prefer doing `$container->getDefinition('data_collector.security')->addArgument($this->authenticatorManagerEnabled);` instead of exposing this parameter to everyone.

Comment (ismail1432) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]: Thanks It works with `addArgument` :tada: 
I tried with `setArgument()` without success, I guess you should respect the parameters order with `addArgument`? Or it can be resolved with Type hint ?

File: src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php (hunk 2 above)
Comment (stof) [reply src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php]: what do you mean by "doesn't work" ?

File: src/Symfony/Bundle/SecurityBundle/Resources/views/Collector/security.html.twig [hunk 3]
```diff
@@ -159,10 +159,12 @@
                     <span class="value">{{ include('@WebProfiler/Icon/' ~ (collector.firewall.stateless ? 'yes' : 'no') ~ '.svg') }}</span>
                     <span class="label">Stateless</span>
                 </div>
+                {% if collector.authenticatorManagerEnabled == false %}
```
Comment (stof) [inline src/Symfony/Bundle/SecurityBundle/Resources/views/Collector/security.html.twig:162]: I'd rather write it as `{% if not collector.authenticatorManagerEnabled %}`

File: src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php (hunk 2 above)
Comment (ismail1432) [reply src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php]: it- seems that `collect()` is not called when we render the profiler panel.

File: src/Symfony/Bundle/SecurityBundle/Resources/views/Collector/security.html.twig (hunk 3 above)
Comment (ismail1432) [inline src/Symfony/Bundle/SecurityBundle/Resources/views/Collector/security.html.twig:162]:
```suggestion
                {% if not collector.authenticatorManagerEnabled %}
```

Comment (ismail1432) [reply src/Symfony/Bundle/SecurityBundle/Resources/views/Collector/security.html.twig:162]: done https://github.com/symfony/symfony/pull/41139/commits/9dc446038fcbb27d479c217201d1cffe9a8853b8

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php (hunk 1 above)
Comment (wouterj) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]: Yes, `addArgument()` adds arguments after the already defined arguments (from the config).

File: src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php (hunk 2 above)
Comment (wouterj) [reply src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php]: That is correct, data collectors are meant to collect the state in the request. The profiler panel then loads the state for a request you want to display information.

So this should be moved to `collect()` afaics.

Comment (ismail1432) [reply src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php]: >So this should be moved to collect() afaics.

Done 

>what do you mean by "doesn't work"?

Maybe it came from the way that I inject the information (parameter). With the current way addArgument it work like a charm :tada:

**Review by chalasr — APPROVED** [review]
LGTM for 5.2 (be careful when merging, target branch is incorrect)

**Review by wouterj — APPROVED** [review]

**Comment by wouterj** [comment]
Thank you @ismail1432 for fixing the profiler & testing your changes :)

File: src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php [hunk 4]
```diff
@@ -44,8 +44,9 @@ class SecurityDataCollector extends DataCollector implements LateDataCollectorIn
     private $firewallMap;
     private $firewall;
     private $hasVarDumper;
+    private $authenticatorManagerEnabled;
 
-    public function __construct(TokenStorageInterface $tokenStorage = null, RoleHierarchyInterface $roleHierarchy = null, LogoutUrlGenerator $logoutUrlGenerator = null, AccessDecisionManagerInterface $accessDecisionManager = null, FirewallMapInterface $firewallMap = null, TraceableFirewallListener $firewall = null)
+    public function __construct(TokenStorageInterface $tokenStorage = null, RoleHierarchyInterface $roleHierarchy = null, LogoutUrlGenerator $logoutUrlGenerator = null, AccessDecisionManagerInterface $accessDecisionManager = null, FirewallMapInterface $firewallMap = null, TraceableFirewallListener $firewall = null, $authenticatorManagerEnabled = false)
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php:49]: the new argument is missing a type-hint, I'm adding it now

Comment (wouterj) [reply src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php:49]: Sorry!

Comment (nicolas-grekas) [reply src/Symfony/Bundle/SecurityBundle/DataCollector/SecurityDataCollector.php:49]: no worries, I added the comment for traceability :)
