### PR TITLE
[Form] Use !isset for checks cause this doesn't falsely include 0

### LINKED ISSUE #40999: [Form] Passing a reference date causes the DateTimeToArrayTransformer to set minutes/hours when the stored value is 0
**Symfony version(s) affected**: 5.2.6 (probably others)

**Description**
If you pass a reference time to a TimeType field with input type array it will assume the time properties of the reference date when the field value was 0

**How to reproduce**
1. Get a TimeType form field
2. Set input to array
3. Add a reference_date
4. Try to set it to 0

**Possible Solution**
It's caused by https://github.com/symfony/form/blob/8822890bdb6267f8d1c027f697db4bd83c2afc55/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php#L170 cause empty views 0 as empty value and will thus take the value of the reference date

### PR DESCRIPTION
**Pull request by KDederichs**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #40999
| License       | MIT

By using isset 0 won't falsely included anymore

### CODE REVIEW

**Comment by derrabus** [comment]
Can you add a test for this issue?

Question: `empty()` also filters out empty strings while `!isset()` doesn't. Is this relevant here?

**Comment by Nyholm** [comment]
Excellent PR. Thank you. 

If you add a small test for this I'll be happy to merge.

**Comment by KDederichs** [comment]
> Excellent PR. Thank you.
> 
> If you add a small test for this I'll be happy to merge.

I'm kinda waiting on a reply in the mentioned issue tbh.
Cause it's really only a bug in that specific usecase, which I'm not 100% sure should be valid anyways.

**Comment by KDederichs** [comment]
Sorry took me a while to get to it but I got some tests that would fail without the changes on both PRs

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php [hunk 1]
```diff
@@ -167,12 +167,12 @@ public function reverseTransform($value)
         try {
             $dateTime = new \DateTime(sprintf(
                 '%s-%s-%s %s:%s:%s',
-                empty($value['year']) ? $this->referenceDate->format('Y') : $value['year'],
-                empty($value['month']) ? $this->referenceDate->format('m') : $value['month'],
-                empty($value['day']) ? $this->referenceDate->format('d') : $value['day'],
-                empty($value['hour']) ? $this->referenceDate->format('H') : $value['hour'],
-                empty($value['minute']) ? $this->referenceDate->format('i') : $value['minute'],
-                empty($value['second']) ? $this->referenceDate->format('s') : $value['second']
+                !isset($value['year']) ? $this->referenceDate->format('Y') : $value['year'],
```
Comment (jderusse) [inline src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php]: This fix the `0` case, but breaks the empty string case .

Comment (KDederichs) [reply src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php]: I mean that does get filtered by:
```
        if ('' === implode('', $value)) {
            return null;
        }
```
anyways doesn't it?
I can't come up with any input that would reach it.

Comment (ostrolucky) [inline src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php]: instead, use null coalescing operator everywhere
```suggestion
                $value['year'] ?? $this->referenceDate->format('Y'),
```

Comment (KDederichs) [reply src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php]: Ah, was thinking about that but wasn't sure anymore when they did introduce that but seems it was in 7.0?

**Review by derrabus — APPROVED** [review]

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php [hunk 2]
```diff
@@ -167,12 +167,12 @@ public function reverseTransform($value)
...
                 '%s-%s-%s %s:%s:%s',
-                empty($value['year']) ? $this->referenceDate->format('Y') : $value['year'],
-                empty($value['month']) ? $this->referenceDate->format('m') : $value['month'],
-                empty($value['day']) ? $this->referenceDate->format('d') : $value['day'],
-                empty($value['hour']) ? $this->referenceDate->format('H') : $value['hour'],
-                empty($value['minute']) ? $this->referenceDate->format('i') : $value['minute'],
-                empty($value['second']) ? $this->referenceDate->format('s') : $value['second']
+                $value['year'] ?? $this->referenceDate->format('Y'),
+                $value['month'] ?? $this->referenceDate->format('m'),
+                $value['day'] ?? $this->referenceDate->format('d'),
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php]: For day and month, zero doesn't mean anything, so that we should keep using the fallback when this happens. For BC at least. I think for year too, even if year zero exists.

Comment (KDederichs) [reply src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php]: Fair point, I'll change those back

**Comment by xabbuh** [comment]
This applies to `4.4` too, right?

**Comment by KDederichs** [comment]
Yeah it's actually a thing in all symfony versions I think.

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php [hunk 3]
```diff
@@ -170,9 +170,9 @@ public function reverseTransform($value)
                 empty($value['year']) ? $this->referenceDate->format('Y') : $value['year'],
                 empty($value['month']) ? $this->referenceDate->format('m') : $value['month'],
                 empty($value['day']) ? $this->referenceDate->format('d') : $value['day'],
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php:172]: can you please ensure we have a test case using `0` for year+month+day?

Comment (KDederichs) [reply src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php:172]: Added it as test for DateType.

**Comment by nicolas-grekas** [comment]
Thank you @KDederichs.
