### PR TITLE
[HttpClient] reject malformed URLs with a meaningful exception

### LINKED ISSUE #57976: [HttpClient] CurlHttpClient::createRedirectResolver(): Argument #2 ($host) must be of type string, null given
### Symfony version(s) affected

6.4.10, 5.4.41

### Description

When $url is missing a / like `$url = 'https:/www.example.org';`
`$client->request('GET', $url);`
exits with  
```
6.4.10
In CurlHttpClient.php line 407:
Symfony\Component\HttpClient\CurlHttpClient::createRedirectResolver(): Argument #2 ($host) must be of type string, 
null given, called in /var/www/vendor/symfony/http-client/CurlHttpClient.php on line 326

5.4.41
In CurlHttpClient.php line 408:
Argument 2 passed to Symfony\Component\HttpClient\CurlHttpClient::createRedirectResolver() must be of the type string,
null given, called in /var/www/vendor/symfony/http-client/CurlHttpClient.php on line 322
```
shouldnt it throw a Symfony\Component\HttpClient\Exception\InvalidArgumentException?

### How to reproduce

```
use Symfony\Component\HttpClient\HttpClient;

$url = 'https:/www.example.org';
$client = HttpClient::create();
$client->request('GET', $url);
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #57976
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/HttpClient/CurlHttpClient.php [hunk 1]
```diff
@@ -103,6 +103,11 @@ public function request(string $method, string $url, array $options = []): Respo
         [$url, $options] = self::prepareRequest($method, $url, $options, $this->defaultOptions);
         $scheme = $url['scheme'];
         $authority = $url['authority'];
+
+        if (null === $authority) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CurlHttpClient.php]: could this check be shared with all implementations somehow? something in prepareRequest for example? I don't remember the details of this method :)

Comment (xabbuh) [reply src/Symfony/Component/HttpClient/CurlHttpClient.php]: makes sense indeed, moving the test without applying the patch there led to errors in most of the other implementations

File: src/Symfony/Component/HttpClient/HttpClientTrait.php [hunk 2]
```diff
@@ -165,6 +165,7 @@ private static function prepareRequest(?string $method, ?string $url, array $opt
             }
 
             // Validate and resolve URL
+            $givenUrl = $url;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/HttpClientTrait.php]: leftover?

File: src/Symfony/Component/HttpClient/HttpClientTrait.php [hunk 3]
```diff
@@ -498,6 +499,10 @@ private static function resolveUrl(array $url, ?array $base, array $queryDefault
             $url['query'] = null;
         }
 
+        if (null === $url['authority']) {
+            throw new InvalidArgumentException('Invalid URL: host is missing.');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/HttpClientTrait.php]: let's make the message closer in style to the existing ones?

Comment (xabbuh) [reply src/Symfony/Component/HttpClient/HttpClientTrait.php]: What do you suggest instead?

Comment (derrabus) [reply src/Symfony/Component/HttpClient/HttpClientTrait.php]:
```suggestion
            throw new InvalidArgumentException(sprintf('Missing host in "%s".', $givenUrl));
```

**Review by derrabus — APPROVED** [review]

File: src/Symfony/Component/HttpClient/HttpClientTrait.php (hunk 3 above)
Comment (xabbuh) [reply src/Symfony/Component/HttpClient/HttpClientTrait.php]: The thing is we don’t have access to the original URL here and the mechanism that we use for the other error messages produces wrong results here (e.g. it would be https://example.com for the added test).

Comment (derrabus) [reply src/Symfony/Component/HttpClient/HttpClientTrait.php]: I see. Well, the current message would be fine for me then.

Comment (xabbuh) [reply src/Symfony/Component/HttpClient/HttpClientTrait.php]: I think I found a way to improve the message.

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.
