### PR TITLE
[DoctrineBridge] deprecate doctrine schema subscribers in favor of listeners

### LINKED ISSUE #49387: Symfony 6.3@dev Unexpected ini_set(): Session ini settings cannot be changed after headers have already been sent
### Symfony version(s) affected

6.3.0@dev (6.2.*@dev works)

### Description

Something seems to be merged into Symfony 6.3 branch which currently let our CI fail on it with:

> **Warning**
> PHP Warning:  ini_set(): Session ini settings cannot be changed after headers have already been sent in /home/runner/work/sulu/sulu/vendor/symfony/http-foundation/Session/Storage/Handler/NativeFileSessionHandler.php on line 48  
> PHP Warning:  ini_set(): Session ini settings cannot be changed after headers have already been sent in /home/runner/work/sulu/sulu/vendor/symfony/http-foundation/Session/Storage/Handler/NativeFileSessionHandler.php on line 49

So it looks some changes in the Session handling. Not sure what it could be, shortly looked at the merged Pull Requests I didn't see why it is happening.

I tested out `6.2.*@dev` there all seems to work still like expected.

If somebody have a hint which PR could have introduced the error let me know, happy to test it out.

### How to reproduce

```bash
git clone git@github.com:sulu/sulu.git
cd sulu

composer config minimum-stability dev
composer update

env DATABASE_URL="mysql://root:ChangeMe@127.0.0.1:3306/sulu?serverVersion=8.0.27&charset=utf8mb4" composer bootstrap-test-env
env DATABASE_URL="mysql://root:ChangeMe@127.0.0.1:3306/sulu?serverVersion=8.0.27&charset=utf8mb4" composer test
```

### Possible Solution

Workaround see: https://github.com/symfony/symfony/issues/49387#issuecomment-1600546860

### Additional Context

<details>
<summary>The change need to be somewhere between Januaray 25 and February 6 and only Symfony 6.3:</summary>

Bildschirmfoto 2023-02-15 um 11 33 19

</details>

### PR DESCRIPTION
**Pull request by alli83**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | yes
| Tickets       | Fix #49387 
| License       | MIT
| Doc PR        | 

As @nicolas-grekas explained in https://github.com/symfony/symfony/issues/49387#issuecomment-1442179095 : 

" Because PdoSessionHandlerSchemaSubscriber is registered as a subscriber, ContainerAwareEventManager must instantiate it to know which events should be listened for. This triggers the instantiation of the session.handler service, which is a NativeFileSessionHandler, and this notice when this is done after headers have been sent."

It was therefore decided to change all the doctrine schema subscribers in favor of listeners in order to avoid this kind of problem. 

Being already present before Symfony 6.3, 
`MessengerTransportDoctrineSchemaSubscriber`, `DoctrineDbalCacheAdapterSchemaSubscriber` and `RememberMeTokenProviderDoctrineSchemaSubscriber`have been deprecated. 

TODO:
- [x] : update DoctrineBundle => in progress

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php [hunk 1]
```diff
@@ -11,27 +11,11 @@
...
-use Doctrine\Common\EventSubscriber;
 use Doctrine\DBAL\Connection;
 use Doctrine\DBAL\Exception\TableNotFoundException;
-use Doctrine\ORM\Tools\Event\GenerateSchemaEventArgs;
-use Doctrine\ORM\Tools\ToolEvents;
 
-abstract class AbstractSchemaSubscriber implements EventSubscriber
+abstract class AbstractSchemaListener
 {
-    abstract public function postGenerateSchema(GenerateSchemaEventArgs $event): void;
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php:22]: we could keep this one here

File: src/Symfony/Bridge/Doctrine/SchemaListener/DoctrineDbalCacheAdapterSchemaSubscriber.php [hunk 2]
```diff
@@ -11,16 +11,20 @@
...
+use Doctrine\ORM\Tools\ToolEvents;
 use Symfony\Component\Cache\Adapter\DoctrineDbalAdapter;
 
 /**
  * Automatically adds the cache table needed for the DoctrineDbalAdapter of
  * the Cache component.
  *
  * @author Ryan Weaver <ryan@symfonycasts.com>
+ *
+ * @deprecated since Symfony 6.3
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/SchemaListener/DoctrineDbalCacheAdapterSchemaSubscriber.php]: `, use DoctrineDbalCacheAdapterSchemaListener instead.`
& let's trigger a deprecation before the class declaration
(same in the other deprecated classes)

File: src/Symfony/Bridge/Doctrine/SchemaListener/DoctrineDbalCacheAdapterSchemaListener.php [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+ * the Cache component.
+ */
+class DoctrineDbalCacheAdapterSchemaListener extends AbstractSchemaListener
+{
+    private $dbalAdapters;
+
+    /**
+     * @param iterable<mixed, DoctrineDbalAdapter> $dbalAdapters
+     */
+    public function __construct(iterable $dbalAdapters)
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/SchemaListener/DoctrineDbalCacheAdapterSchemaListener.php]:
```php
public function __construct(private iterable $dbalAdapters)
{
}
```

File: src/Symfony/Bridge/Doctrine/SchemaListener/MessengerTransportDoctrineSchemaListener.php [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+class MessengerTransportDoctrineSchemaListener extends AbstractSchemaListener
+{
+    private const PROCESSING_TABLE_FLAG = self::class.':processing';
+
+    private iterable $transports;
+
+    /**
+     * @param iterable<mixed, TransportInterface> $transports
+     */
+    public function __construct(iterable $transports)
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/SchemaListener/MessengerTransportDoctrineSchemaListener.php]: `private iterable $transports`

File: src/Symfony/Bridge/Doctrine/SchemaListener/RememberMeTokenProviderDoctrineSchemaListener.php [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+ * Automatically adds the rememberme table needed for the {@see DoctrineTokenProvider}.
+ */
+class RememberMeTokenProviderDoctrineSchemaListener extends AbstractSchemaListener
+{
+    private iterable $rememberMeHandlers;
+
+    /**
+     * @param iterable<mixed, RememberMeHandlerInterface> $rememberMeHandlers
+     */
+    public function __construct(iterable $rememberMeHandlers)
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/SchemaListener/RememberMeTokenProviderDoctrineSchemaListener.php]: `private iterable $rememberMeHandlers`

File: src/Symfony/Bridge/Doctrine/Tests/SchemaListener/DoctrineDbalCacheAdapterSchemaSubscriberTest.php [hunk 6]
```diff
@@ -37,7 +38,9 @@ public function testPostGenerateSchema()
             ->method('configureSchema')
             ->with($schema, $dbalConnection);
 
-        $subscriber = new DoctrineDbalCacheAdapterSchemaSubscriber([$dbalAdapter]);
+        $subscriber = class_exists(DoctrineDbalCacheAdapterSchemaListener::class) ?
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Tests/SchemaListener/DoctrineDbalCacheAdapterSchemaSubscriberTest.php]: why this check? shouldn't we always create the listener? (same question in other similar places)

File: src/Symfony/Bridge/Doctrine/SchemaListener/MessengerTransportDoctrineSchemaSubscriber.php [hunk 7]
```diff
@@ -11,18 +11,22 @@
...
 
 /**
  * Automatically adds any required database tables to the Doctrine Schema.
  *
  * @author Ryan Weaver <ryan@symfonycasts.com>
+ *
+ * @deprecated since Symfony 6.3
  */
-final class MessengerTransportDoctrineSchemaSubscriber extends AbstractSchemaSubscriber
+final class MessengerTransportDoctrineSchemaSubscriber extends MessengerTransportDoctrineSchemaListener implements EventSubscriber
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/SchemaListener/MessengerTransportDoctrineSchemaSubscriber.php:27]: we should also remove the methods from the class, relying on the parent implementations when possible (same in other similar classes)

**Review by nicolas-grekas — COMMENTED** [review]
Nice, thanks :)

File: src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php [hunk 8]
```diff
@@ -11,27 +11,11 @@
...
 namespace Symfony\Bridge\Doctrine\SchemaListener;
 
-use Doctrine\Common\EventSubscriber;
 use Doctrine\DBAL\Connection;
 use Doctrine\DBAL\Exception\TableNotFoundException;
-use Doctrine\ORM\Tools\Event\GenerateSchemaEventArgs;
-use Doctrine\ORM\Tools\ToolEvents;
 
-abstract class AbstractSchemaSubscriber implements EventSubscriber
+abstract class AbstractSchemaListener
```
Comment (derrabus) [inline src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php:18]: Userland code might have extended `AbstractSchemaSubscriber` directly. I think we need to keep the class for BC and deprecate it instead.

Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php:18]: This class is new to 6.3 ;)

File: src/Symfony/Bridge/Doctrine/Tests/SchemaListener/DoctrineDbalCacheAdapterSchemaSubscriberTest.php (hunk 6 above)
Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Tests/SchemaListener/DoctrineDbalCacheAdapterSchemaSubscriberTest.php]: Indeed, I got confused with the situation before when there were no listeners , but it has nothing to do with that

File: src/Symfony/Bridge/Doctrine/SchemaListener/MessengerTransportDoctrineSchemaSubscriber.php (hunk 7 above)
Comment (alli83) [reply src/Symfony/Bridge/Doctrine/SchemaListener/MessengerTransportDoctrineSchemaSubscriber.php:27]: If I understand correctly I remove all duplicate in subscribers and keep only the getSubscribedEvents in case the parent already define the method ? it makes more sense indeed.

Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/SchemaListener/MessengerTransportDoctrineSchemaSubscriber.php:27]: correct!

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @alli83.
