### PR TITLE
[Serializer] Allow AbstractNormalizer to use null for non-optional nullable constructor parameters without default value

### LINKED ISSUE #40511: Allow AbstractNormalizer to use null for nullable constructor parameters without default value
**Symfony version(s) affected**: All versions until 5.1 (but I guess 5.2 is too)

**Description**

Serializer component AbstractNormalizer attemps to guess constructor parameters, and falls back using default values when possible, which is good. Yet, it misses one use case: when you specify nullable non-optional parameter, case in which null is a valid value, not the default one, yet still valid.

It's a matter a choice, either we consider that the incoming data should explicitly set null here, or we consider that it might come from a dynamic language such as JavaScript that may remove undefined values from sent JSON: case in which we might want to fix that and consider that undefined is null.

**How to reproduce**

Simply write a class with a constructor as such:

```php
class Foo
{
    public function __construct(string $foo, ?string $bar)
    {
    }
}
```

And attempt to denormalize using this incoming array:

```php
$input = [
    'foo' => 'any value',
];
```

In this specific case, `null` is an allowed value for `$bar`, and value is not set in `$input`, why not simply give it null ? Actual behaviour is that the exception for missing constructor argument is raised and prevents the object from being denormalized.

**Possible Solution**

Easy two-line fix, in `AbstractNormalizer::instantiateObject()` as such:

Replace:

```php
                } elseif (\array_key_exists($key, $this->defaultContext[self::DEFAULT_CONSTRUCTOR_ARGUMENTS][$class] ?? [])) {
                    $params[] = $this->defaultContext[self::DEFAULT_CONSTRUCTOR_ARGUMENTS][$class][$key];
                } elseif ($constructorParameter->isDefaultValueAvailable()) {
                    $params[] = $constructorParameter->getDefaultValue();
                } else {
                    throw new MissingConstructorArgumentsException(sprintf('Cannot create an instance of "%s" from serialized data because its constructor requires parameter "%s" to be present.', $class, $constructorParameter->name));
                }
```

Using:

```php
                } elseif (\array_key_exists($key, $this->defaultContext[self::DEFAULT_CONSTRUCTOR_ARGUMENTS][$class] ?? [])) {
                    $params[] = $this->defaultContext[self::DEFAULT_CONSTRUCTOR_ARGUMENTS][$class][$key];
                } elseif ($constructorParameter->isDefaultValueAvailable()) {
                    $params[] = $constructorParameter->getDefaultValue();
                } elseif ($constructorParameter->hasType() && $constructorParameter->getType()->allowsNull()) {
                    $params[] = null;
                } else {
                    throw new MissingConstructorArgumentsException(sprintf('Cannot create an instance of "%s" from serialized data because its constructor requires parameter "%s" to be present.', $class, $constructorParameter->name));
                }
```

I just added those two lines:

```php
                } elseif ($constructorParameter->hasType() && $constructorParameter->getType()->allowsNull()) {
                    $params[] = null;
```

Compatible for all PHP version from 7.0 if I read correctly https://www.php.net/manual/en/reflectiontype.allowsnull.php

### PR DESCRIPTION
**Pull request by pounard**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40511
| License       | MIT

Serializer component AbstractNormalizer attemps to guess constructor parameters, and falls back using default values when possible. Yet, it misses one use case: nullable non-optional parameter with value not being present in incoming input, case in which null is a valid value, not the default one, yet still valid.

This PR introduce a two-line fix that forcefully set null as value for missing from input non-optional nullable constructor parameters values.

### CODE REVIEW

**Comment by pounard** [comment]
Build failure seems to be unrelated, am I misreading it ?

**Review by ro0NL — APPROVED** [review]

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractNormalizerTest.php [hunk 1]
```diff
@@ -132,6 +132,14 @@ public function testObjectWithNullableConstructorArgument()
         $this->assertNull($dummy->getFoo());
     }
 
+    public function testObjectWithNullableNonOptionalConstructorArgument()
```
Comment (ro0NL) [inline src/Symfony/Component/Serializer/Tests/Normalizer/AbstractNormalizerTest.php:137]: `NullableNonOptional` = `RequiredNullable` which ideally is also conveyed by `NullableConstructorArgumentDummy` (thus `RequiredNullableConstructorArgumentDummy`). As it potentially can invalidate this test.

Perhaps if the rename is a hassle, add a class_alias instead?

Comment (pounard) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractNormalizerTest.php:137]: That's true, I hesitated to create a new dummy class for the test, but since the other one was exactly the same I decided not to copy it, but I can add it if it makes sense.

Comment (pounard) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractNormalizerTest.php:137]: I wouldn't use `class_alias` for this, it's a little magic that can end up as a big WTF for debugging.

Comment (ro0NL) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractNormalizerTest.php:137]: we could try updating the signature of the current dummy class to see what tests do (eg. `= null`), if all good then add a new `RequiredNullableConstructorArgumentDummy` specifically for this test.

Comment (pounard) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractNormalizerTest.php:137]: How about I add a class whose parameter has a default value of null, and I duplicate both tests so that each one is testing both classes to complete the test matrix ? That way all use case would be covered.

Comment (ro0NL) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractNormalizerTest.php:137]: alternatively `?string $required, ?string $optional = null` in the current fixture may work :)

Comment (pounard) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractNormalizerTest.php:137]: Yes, probably, it'll do less tests, but would be less explicit. I don't know if there's any guideline about that in Symfony, I personally am more comfortable with unit tests (unit as in atomic unit) for this kind of use case, so if no one steps up and ask me to do otherwise, I'll do the 4 tests / 2 classes variant :)

Comment (pounard) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractNormalizerTest.php:137]: Done !

File: src/Symfony/Component/Serializer/Tests/Fixtures/NullableOptionalConstructorArgumentDummy.php [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\Serializer\Tests\Fixtures;
+
+class NullableOptionalConstructorArgumentDummy
+{
+    private $foo;
+
+    public function __construct(?\stdClass $foo = null)
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Tests/Fixtures/NullableOptionalConstructorArgumentDummy.php]: please remove the leading `?`, per our current codestyle

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Serializer/Tests/Fixtures/NullableOptionalConstructorArgumentDummy.php (hunk 2 above)
Comment (pounard) [reply src/Symfony/Component/Serializer/Tests/Fixtures/NullableOptionalConstructorArgumentDummy.php]: The whole point is to test it works with `?`.

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Tests/Fixtures/NullableOptionalConstructorArgumentDummy.php]: `?` doesn't matter if the argument defaults to null, from the pov of reflection.
Don't you want to add a test case that has a nullable argument with *no default* instead?

Comment (pounard) [reply src/Symfony/Component/Serializer/Tests/Fixtures/NullableOptionalConstructorArgumentDummy.php]: I added it, actually, there was one test, now there are 4 which tests the full matrix, with a default, with a value, with no default, with no value, with a default with no value, with no default, with a value.

**Comment by pounard** [comment]
@ro0NL @nicolas-grekas thank you. I hope it will land in next 5.2 release, I have to maintain a patch in the meantime.

**Comment by nicolas-grekas** [comment]
I rebased on 4.4, where bugfixes should be merged.

**Comment by pounard** [comment]
> I rebased on 4.4, where bugfixes should be merged.

Oh, nice ! Thank you very much.

**Review by maxhelias — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @pounard.
