### PR TITLE
[ObjectMapper] Add `ObjectMapperAwareInterface` to set the owning object mapper instance

### LINKED ISSUE #61119: [ObjectMapper] Mapping to existing entity doesn't work always
### Symfony version(s) affected

7.3

### Description

Hi there,

I'm using Symfony as an Backend-API and have changed the last weeks to use the ObjectMapper.
At updating existing entitys is a problem it doesn't work always. To create an new entity it always works fine. At first I thought it cause of nested entitys, but it's also an "top level" entity. I have two examples for that.

### How to reproduce

**First example** (nested entity)
```php
#Controller.php
#[Route('/klasse-turnier-zuord/{klasse_turnier_zuord_id}/edit', name: "turnier-work-klasse-turnier-klasse-zuord-edit", methods: ["PATCH"], format: "json")]
public function klasseEdit(
    #[MapRequestPayload] KlasseMitTurnierZuordDTO $klasseMitTurnierZuordDTO,
    int $klasse_turnier_zuord_id, ): JsonResponse
{
    $klasseTurnierZuordAktuell = $this->klasseTurnierZuordRepos->findOneBy([
        'turnier'       =>  $this->turnier,
        'id'            =>  $klasse_turnier_zuord_id]);
    
    if ($klasseTurnierZuordAktuell instanceof KlasseTurnierZuord)
    {
        $klAkt = $klasseTurnierZuordAktuell->getKlasse();
        $klDTO = $klasseMitTurnierZuordDTO->klasse;
        // just shorten for the comparison bellow
        $genAkt = [];
        
        foreach ($klAkt->getGender() as $gen)
        {
            $genAkt[] = $gen->getId();
        }
        
        if (($klAkt->getStandard())
            && (($klAkt->getName() != $klDTO->name)
                || ($klAkt->getBogentyp()->getId() != $klDTO->bogentyp_id)
                || ($klAkt->getAltersklasseVon()->getId() != $klDTO->altersklasse_von_id)
                || ($klAkt->getAltersklasseBis()->getId() != $klDTO->altersklasse_bis_id)
                || ($klAkt->getApollonKlasseNr() != $klDTO->apollon_klasse_nr)
                || ($genAkt != $klDTO->gender_id)))
        {
            $this->objectMapper->map($klasseMitTurnierZuordDTO->klasse, $klasseTurnierZuordAktuell->getKlasse());
            $klasseTurnierZuordAktuell->getKlasse()->unsetId();
            $klasseTurnierZuordAktuell->getKlasse()->setStandard(false);
        }
        else
        {
            $this->objectMapper->map($klasseMitTurnierZuordDTO->klasse, $klasseTurnierZuordAktuell->getKlasse());
        }
    }

    return $this->json([]);
}
```
```php
#KlasseMitTurnierZuordDTO.php
class KlasseMitTurnierZuordDTO
{
    public function __construct(

        public readonly KlasseDTO $klasse,

        public readonly KlasseTurnierZuordDTO $klasse_turnier_zuord,
        )
    {
        
    }
}
```
```php
#KlasseDTO.php
#[Map(target: Klasse::class)]
class KlasseDTO
{
    public function __construct(

        public readonly bool $standard,

        #[Map(target: "inter_nat", transform: KlasseInterNatTransformer::class)]
        public readonly array $inter_nat,

        public readonly ?int $gueltig_von,

        public readonly ?int $gueltig_bis,

        public readonly string $name,

        #[Map(target: 'bogentyp', transform: BogentypTransformer::class)]
        public readonly ?int $bogentyp_id,

        #[Map(target: 'altersklasse_von', transform: AltersklasseVonTransformer::class)]
        public readonly ?int $altersklasse_von_id,
        
        #[Map(target: 'altersklasse_bis', transform: AltersklasseBisTransformer::class)]
        public readonly ?int $altersklasse_bis_id,

        public readonly ?int $apollon_klasse_nr,

        #[Map(target: 'gender', transform: GenderTransformer::class)]
        public readonly array $gender_id,

        #[Map(target: 'klasse_turniertyp_zuord', transform: KlasseTurniertypZuordTransformer::class)]
        public readonly ?array $turniertyp_zuord = null, )
    {
        
    }
}
```
On dumping the DTO-object there's the new value, but it isn't mapped to the entity.
I also have tested to don't get the Klasse entity from the $klasseTurnierZuordAktuell, load it with the entity manager by id, but some result.

**second example** ("top level" entity)
```php
#Controller
#[Route('/einstellungen', name: "turnier-work-meldung-einstellungen", methods: ["PATCH"], format: "json")]
public function einstellungen(
#[MapRequestPayload] TurnierMeldungEinstellungenDTO $turnierMeldungEinstellungenDTO): JsonResponse
{
    try
    {
        $this->objectMapper->map($turnierMeldungEinstellungenDTO, $this->turnier);
        
        $this->eM->persist($this->turnier);
        $this->eM->flush();
        $this->eM->refresh($this->turnier);
        
        $this->subscriber->setResponseSuccess(true);

        return $this->json($this->turnier->getArrayOwner());
    }
    catch (Exception $e)
    {
        dump($e);
        $this->subscriber->setResponseError([1, 43, 1, 1]);
    }

    return $this->json([]);
}
```
```php
#TurnierMeldungEinstellungenDTO.php
#[Map(target: Turnier::class)]
class TurnierMeldungEinstellungenDTO
{


    public function __construct(
        #[Map(target: 'meldeschluss_date', transform: DateTimeTransformer::class)]
        public readonly string $meldeschluss_date,
        
        public readonly string $meldung_neu_nach_meldeschluss,
        
        public readonly bool $meldung_edit_nach_meldeschluss,
        
        public readonly bool $meldung_delete_nach_meldeschluss,
        
        public readonly bool $delete_meldung_autoremove_startliste,
        
        public readonly bool $mehrfach_meldung_moeglich,
        
        public readonly bool $meldung_ohne_eindeutig_klassenzuordnung,

        public readonly bool $meldung_klassenzuordnung_melder_manuell,

        public readonly bool $melden_mannschaft,

        public readonly bool $meldung_ohne_quali,

        public readonly bool $meldung_ohne_datenpruefung,

        public readonly bool $meldung_ohne_startberechtigung,

        public readonly bool $meldung_check_hoeherstufung,
        )
    {
        
    }
}
```
The TurnierMeldungEinstellungenDTO isn't an DTO of the full target, there are only properties how would be changed some settings.

### Possible Solution

_No response_

### Additional Context

I have shorten the controller codes for easier to read and understand here. I also have tested the shorten codes, but there's the some problem, so it's not caused on the code around the mapper.
If I exchange the existing entities with empty entities the mapping works well.

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Feature?      | yes
| Issues        | Fix #61119
| License       | MIT

Because the Object Mapper calls itself and we don't offer the possibility to change the owning object mapper, its hard to change the behavior on embedded objects (you could with a transform callable but it is redundant and adds lots of complexity). 
With this change the ObjectMapper can use a decorated instance and we can easily provide a way to make things like #61119 work. Inside API Platform we have the same issue where we want to re-use values that have been previously mapped to existing entities, we don't want to create new classes. This is achievable with decorating the ObjectMapper but works on relations only if the called mapper inside the mapper is configurable.

Let me know how I should write the DI in the FrameworkBundle for this as it'd be nice if it worked with decoration pattern without user interactions.

### CODE REVIEW

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php [hunk 1]
```diff
@@ -40,7 +40,11 @@ public function __construct(
         private readonly ?PropertyAccessorInterface $propertyAccessor = null,
         private readonly ?ContainerInterface $transformCallableLocator = null,
         private readonly ?ContainerInterface $conditionCallableLocator = null,
+        private ?ObjectMapperInterface $objectMapper = null,
     ) {
+        if (!$objectMapper) {
+            $objectMapper = $this;
+        }
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/ObjectMapper.php]:
```suggestion
```

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php [hunk 2]
```diff
@@ -203,7 +207,7 @@ private function getSourceValue(object $source, object $target, mixed $value, \S
             } elseif ($objectMap->contains($value)) {
                 $value = $objectMap[$value];
             } else {
-                $value = $this->map($value, $mapTo->target);
+                $value = $this->objectMapper->map($value, $mapTo->target);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/ObjectMapper.php]: let's save a circular reference:
```suggestion
                $value = ($this->objectMapper ?? $this)->map($value, $mapTo->target);
```

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php [hunk 3]
```diff
@@ -319,4 +323,9 @@ private function getSourceReflectionClass(object $source, \ReflectionClass $targ
 
         return $targetRefl;
     }
+
+    public function setObjectMapper(ObjectMapperInterface $objectMapper): void
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/ObjectMapper.php]: can't we get rid of the setter and the interface?

Comment (soyuka) [reply src/Symfony/Component/ObjectMapper/ObjectMapper.php]: Indeed I assumed this was easier to introduce injection in the framework bundle but if we can do it without that I'm +1

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php [hunk 4]
```diff
@@ -319,4 +321,13 @@ private function getSourceReflectionClass(object $source, \ReflectionClass $targ
 
         return $targetRefl;
     }
+
+    #[Required]
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/ObjectMapper.php]: I'm wondering if this is allowed or if I should add something to the framework bundle, I could not find any other occurence of something like this in the current code base.

Comment (nicolas-grekas) [reply src/Symfony/Component/ObjectMapper/ObjectMapper.php]: this should be removed IMHO: this attribute marks a method that should be called just after the constructor
but here, the constructor already accepts a mapper, so that calling this method is not needed to have the object fully instantiated

**Comment by soyuka** [comment]
I guess we should consider this as a new feature though as we added a new interface and a public method, I rebased on 7.4.

**Review by nicolas-grekas — APPROVED** [review]
Can you please add a line to the changelog of the component?

**Review by dunglas — APPROVED** [review]

**Comment by soyuka** [comment]
done

File: src/Symfony/Component/ObjectMapper/CHANGELOG.md [hunk 5]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+7.4
+---
+
+ * ObjectMapperAwareInterface to set the owning object mapper instance
```
Comment (OskarStark) [inline src/Symfony/Component/ObjectMapper/CHANGELOG.md]:
```suggestion
 * Add `ObjectMapperAwareInterface` to set the owning object mapper instance
```

**Comment by soyuka** [comment]
let me resolve the conflicts

**Comment by nicolas-grekas** [comment]
Thank you @soyuka.
