### PR TITLE
[Security] Added login throttling feature

### LINKED ISSUE #37266: Login throttling
Hi :)

It would be great to have an option for the connection to limit the number of failed login attempts over a period of time.

Thanks :)

### PR DESCRIPTION
**Pull request by wouterj**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #37266
| License       | MIT
| Doc PR        | tbd

This "recreates" #37444 based on the RateLimiter component from #37546 <s>(commits are included in this branch atm)</s>.

Login throttling can be enabled on any user-based authenticator (thanks to the `UserBadge`) with this configuration:

```yaml
security:
    firewalls:
        default:
            # default limits to 5 login attempts per minute, the number can be configured via "max_attempts"
            login_throttling: ~

            # or you can define your own RateLimiter on framework.rate_limiter and configure it instead:
            login_throttling:
                limiter: login
```

### CODE REVIEW

File: src/Symfony/Component/Security/Http/EventListener/LoginThrottlingListener.php [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+        return [
+            CheckPassportEvent::class => ['checkPassport', 64],
+            LoginSuccessEvent::class => 'onSuccessfulLogin',
+        ];
+    }
+
+    private function createLimiterKey($username, Request $request): string
+    {
+        return $username.$request->getClientIp();
+    }
```
Comment (weaverryan) [inline src/Symfony/Component/Security/Http/EventListener/LoginThrottlingListener.php:76]: I wonder if/how users might want to configure what goes into the limiter key 🤔 

And... this wouldn't rate limit (I don't know if it should or not) a more sophisticated attack that uses many ip addresses to try to log in as the same user.

Note: as a sanity check, Laravel does exactly this: username + ip address.

File: src/Symfony/Component/Security/Http/EventListener/LoginThrottlingListener.php [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+        $limiter = $this->limiter->create($limiterKey);
+        if (!$limiter->consume()) {
+            throw new SessionLockedException();
+        }
+    }
+
+    public function onSuccessfulLogin(LoginSuccessEvent $event): void
+    {
+        $limiterKey = $this->createLimiterKey($event->getAuthenticatedToken()->getUsername(), $event->getRequest());
+        $limiter = $this->limiterFactory->createLimiter($limiterKey);
```
Comment (weaverryan) [inline src/Symfony/Component/Security/Http/EventListener/LoginThrottlingListener.php:60]: This still references limiterFactory

**Review by weaverryan — COMMENTED** [review]
This looks really nice :).

Due to the architecture, I understand why there is config needed under `framework` and `security`. However, could we avoid this? From a user's perspective, I think:

> I need login throttling!

And I would expect that I can enable that easily in security.yaml. Could we allow the user to create a "rate limiter" inline in the security config? If we need to, we could make it less configurable (and if you need a more configurable limiter, then you could define it properly under framework and reference that limiter from here).

File: src/Symfony/Component/Security/Http/EventListener/LoginThrottlingListener.php (hunk 1 above)
Comment (wouterj) [reply src/Symfony/Component/Security/Http/EventListener/LoginThrottlingListener.php:76]: Yeah, it seems quite common to include the IP address in the limiter key. Tbh, I'm not sure about both: this still allows enumeration attacks with many usernames. So maybe it's indeed a good idea to make this configurable (but how :thinking:)

File: src/Symfony/Component/Security/Core/Exception/SessionLockedException.php [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+
+namespace Symfony\Component\Security\Core\Exception;
+
+/**
+ * This exception is thrown if there where too many failed login attempts in
+ * this session.
+ *
+ * @author Wouter de Jong <wouter@wouterj.nl>
+ */
+class SessionLockedException extends AuthenticationException
```
[the remark this answers is not in the document]
Comment (wouterj) [reply src/Symfony/Component/Security/Core/Exception/SessionLockedException.php:20]: It's a "login session", it has nothing to do with browser session. I'm not sure about the name of the class as well, but I couldn't find a better name yet

File: src/Symfony/Component/Security/Http/EventListener/LoginThrottlingListener.php (hunk 1 above)
Comment (fabpot) [reply src/Symfony/Component/Security/Http/EventListener/LoginThrottlingListener.php:76]: The main question is how would you decide on what to use as a key? Why would I use something different from the default? Attacks are the same for all websites, right? I would not make it confiugurable at first and see how it goes.

File: src/Symfony/Component/Security/Core/Exception/SessionLockedException.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (weaverryan) [reply src/Symfony/Component/Security/Core/Exception/SessionLockedException.php:20]: What about `TooManyLoginAttemptsAuthenticationException`? Or `LoginThrottleAuthenticationException`?

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 4]
```diff
@@ -1737,7 +1737,8 @@ private function addRateLimiterSection(ArrayNodeDefinition $rootNode)
                             ->arrayPrototype()
                                 ->children()
                                     ->scalarNode('lock')->defaultValue('lock.factory')->end()
-                                    ->scalarNode('storage')->defaultValue('cache.app')->end()
+                                    ->scalarNode('cache_pool')->defaultValue('cache.app')->end()
+                                    ->scalarNode('storage_service')->defaultNull()->end()
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:1741]: We need validation to prevent both from being set.

And I would LOVE an `info()` on all of these

Comment (wouterj) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:1741]: `cache_pool` will always be set (as it has a default value). So I think we should just document that `storage_service` has precedence on `cache_pool`?

Comment (weaverryan) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:1741]: Oh, duh, yes. Hmm, yea, that works!

**Comment by wouterj** [comment]
This PR is now ready to merge imho.

Based on suggestions from @weaverryan, the SecurityBundle now configures a "default" limiter for login throttling. A user can override this by configuring the `limiter` setting. This required some changes in the RateLimiter configuration - which is probably now a bit easier to understand and less magic than before.

File: src/Symfony/Component/Security/Http/EventListener/LoginThrottlingListener.php [hunk 5]
```diff
@@ -0,0 +1,77 @@
...
+use Symfony\Component\Security\Http\Event\CheckPassportEvent;
+use Symfony\Component\Security\Http\Event\LoginSuccessEvent;
+
+/**
+ * @author Wouter de Jong <wouter@wouterj.nl>
+ *
+ * @final
+ * @experimental in 5.2
+ */
+class LoginThrottlingListener implements EventSubscriberInterface
```
Comment (fabpot) [inline src/Symfony/Component/Security/Http/EventListener/LoginThrottlingListener.php:29]: final?

**Review by fabpot — APPROVED** [review]

File: src/Symfony/Component/Security/Http/EventListener/LoginThrottlingListener.php (hunk 5 above)
Comment (wouterj) [reply src/Symfony/Component/Security/Http/EventListener/LoginThrottlingListener.php:29]: When should we use `@final` and when `final`? IIRC, I've used `@final` for all experimental Security classes and not the PHP `final` keyword. And I remember mostly seeing `@final` in the Symfony code.

(I'm fine with both, but I want to prevent wasting your time with such comments in future PRs of mine)

File: src/Symfony/Component/Security/Http/Tests/EventListener/LoginThrottlingListenerTest.php [hunk 6]
```diff
@@ -0,0 +1,105 @@
...
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\Security\Http\Tests\EventListener;
+
+use PHPUnit\Framework\TestCase;
+use Symfony\Component\HttpFoundation\Request;
+use Symfony\Component\HttpFoundation\RequestStack;
+use Symfony\Component\RateLimiter\FixedWindowLimiter;
```
Comment (fabpot) [inline src/Symfony/Component/Security/Http/Tests/EventListener/LoginThrottlingListenerTest.php:17]: Can be removed (not used)

File: src/Symfony/Component/Security/Http/EventListener/LoginThrottlingListener.php (hunk 5 above)
Comment (fabpot) [reply src/Symfony/Component/Security/Http/EventListener/LoginThrottlingListener.php:29]: We should only use `@final` for existing classes for which adding `final` would be a BC break. Then, in the next major version, we can convert the annotation to a real final class.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 7]
```diff
@@ -1736,12 +1736,30 @@ private function addRateLimiterSection(ArrayNodeDefinition $rootNode)
...
+                                        ->isRequired()
+                                        ->values(['fixed_window', 'token_bucket'])
+                                    ->end()
+                                    ->integerNode('limit')
+                                        ->info('The maximum allowed hits in a fixed interval or burst')
+                                        ->isRequired()
+                                    ->end()
+                                    ->scalarNode('interval')->info('Configures the fixed interval if "strategy" is set to "fixed_window"')->end()
                                     ->arrayNode('rate')
+                                        ->info('Configures the fill rate if "strategy" is set to "token_bucket"')
```
Comment (javiereguiluz) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:1762]: Same here: `Configures the fill rate` + `in percent, from 0.0 to 1.0` or something like that?

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 8]
```diff
@@ -1736,12 +1736,30 @@ private function addRateLimiterSection(ArrayNodeDefinition $rootNode)
...
+                                    ->enumNode('strategy')
+                                        ->info('The rate limiting algorithm to use for this rate')
+                                        ->isRequired()
+                                        ->values(['fixed_window', 'token_bucket'])
+                                    ->end()
+                                    ->integerNode('limit')
+                                        ->info('The maximum allowed hits in a fixed interval or burst')
+                                        ->isRequired()
+                                    ->end()
+                                    ->scalarNode('interval')->info('Configures the fixed interval if "strategy" is set to "fixed_window"')->end()
```
Comment (javiereguiluz) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:1760]: Could we modify this -> `Configures the fixed interval` to mention if it's in minutes, seconds, ...? Example:

```
Configures the fixed interval in seconds if "strategy" is set to "fixed_window"
```

Comment (wouterj) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:1760]: Hmm, I agree that we have to mention to format. However, I'm open for suggestions on how to briefly describe this. It's a human readable time string. More precisely it's a number followed by any `unit` documented in https://www.php.net/datetime.formats.relative

Comment (weaverryan) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:1760]: Linking there would be good. Adding an example also would be super great - I'm still confused after following that link.

Comment (wouterj) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: Hmm, I've now made it a bit more simple and explicit (more syntax is allowed, but this is probably the most used):

> The value must be a number followed by "second", "minute", "hour", "day", "week" or "month" (or their plural equivalent)

**Comment by fabpot** [comment]
Thank you @wouterj.
