### PR TITLE
[HttpFoundation] add support for X_FORWARDED_PREFIX header

### LINKED ISSUE #36809: Support X_FORWARDED_PREFIX HTTP request header
**Description**  

Some HTTP reverse-proxy (at least Traefik), send a X_FORWARDED_PREFIX header to backend (here, a Symfony application running on Nginx), if routing configuration use a Path prefix.

But Symfony ignores it, hence, all routes are broken.

(Or I missed something about how to configure Symfony behind a reverse-proxy with a path prefix).

**Example**  

Symfony is behind ``/admin/(.*)`` routes, so a URL ``/admin/login/`` must match ``/login`` route.

### PR DESCRIPTION
**Pull request by jeff1985**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #36809 
| License       | MIT

Add support for `X-Forwarded-Prefix` header added by the popular Traefik HTTP LoadBalancer and Reverse Proxy. This ensures that the links rendered by symfony application deployed behind LB are valid even if the application is deployed via prefix URL.   

Example routing setup:
route `/admin/(.*)` => symfony backend `/$1`
in this case links rendered by symfony backend must start with `/admin/` 

To accept traefik prefix in your symfony app, you must modify index.php to allow accepting this header:

    Request::setTrustedProxies(explode(',', $trustedProxies), Request::HEADER_X_FORWARDED_TRAEFIK ^ Request::HEADER_X_FORWARDED_HOST );`

### CODE REVIEW

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 1]
```diff
@@ -46,6 +46,7 @@ class Request
     const HEADER_X_FORWARDED_PORT = 0b10000;
     const HEADER_X_FORWARDED_ALL = 0b11110; // All "X-Forwarded-*" headers
     const HEADER_X_FORWARDED_AWS_ELB = 0b11010; // AWS ELB doesn't send X-Forwarded-Host
+    const HEADER_X_FORWARDED_PREFIX = 0b11011;
```
Comment (stof) [inline src/Symfony/Component/HttpFoundation/Request.php:49]: this value is wrong. `X_FORWARDED_PREFIX` is a separate header, so it should use a separate bit in the bit mask, not a value equal to `HEADER_X_FORWARDED_AWS_ELB | HEADER_FORWARDED`

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 2]
```diff
@@ -1839,6 +1841,12 @@ protected function prepareBaseUrl()
             return $prefix;
         }
 
+        if ($this->isFromTrustedProxy() && $trustedPrefix = $this->getTrustedValues(self::HEADER_X_FORWARDED_PREFIX)) {
+            $trustedPrefix = rtrim($trustedPrefix[0], '/');
+
+            return $trustedPrefix;
```
Comment (stof) [inline src/Symfony/Component/HttpFoundation/Request.php:1847]: AFAICT, the proxy prefix must be prepended to any prefix being needed at the webserver level, rather than replacing it entirely. Otherwise, this breaks things when the webserver itself expects a prefix too.

**Review by stof — CHANGES_REQUESTED** [review]

**Comment by stof** [comment]
btw, `HEADER_X_FORWARDED_ALL` should not be updated to whitelist the new traefik-only header, as that would make it trusted by all projects using that constant today while being behind proxies that don't know support that header, which would be a potential security issue for them (the bitmask about which headers are trusted is precisely meant to avoid a security issue).

A new `HEADER_X_FORWARDED_TRAEFIK` constant might be added with the bitmask of headers support by Traefik though for easy config.

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 1 above)
Comment (jeff1985) [reply src/Symfony/Component/HttpFoundation/Request.php]: Thanks for that hint! In that case we must change the bitmask length, right? I have adjusted the value to `HEADER_X_FORWARDED_PREFIX=0b100000`.

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 2 above)
Comment (jeff1985) [reply src/Symfony/Component/HttpFoundation/Request.php]: Good point! This actually turned out to be a little more complex. We actually need both values baseURL with and without proxy prefix to make everything work fine for custom scenarios like deploying code in a subdir. 

I have added a test for that and adjusted code accordingly. Please have a look!

**Comment by jeff1985** [comment]
> btw, `HEADER_X_FORWARDED_ALL` should not be updated to whitelist the new traefik-only header, as that would make it trusted by all projects using that constant today while being behind proxies that don't know support that header, which would be a potential security issue for them (the bitmask about which headers are trusted is precisely meant to avoid a security issue).
> 
> A new `HEADER_X_FORWARDED_TRAEFIK` constant might be added with the bitmask of headers support by Traefik though for easy config.

Agree! I added the required midifications.

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 3]
```diff
@@ -39,13 +39,15 @@ class_exists(ServerBag::class);
...
-    const HEADER_X_FORWARDED_AWS_ELB = 0b11010; // AWS ELB doesn't send X-Forwarded-Host
+    const HEADER_FORWARDED = 0b000001; // When using RFC 7239
+    const HEADER_X_FORWARDED_FOR = 0b000010;
+    const HEADER_X_FORWARDED_HOST = 0b000100;
+    const HEADER_X_FORWARDED_PROTO = 0b001000;
+    const HEADER_X_FORWARDED_PORT = 0b010000;
+    const HEADER_X_FORWARDED_ALL = 0b011110; // All "X-Forwarded-*" headers sent by "usual" reverse proxy
+    const HEADER_X_FORWARDED_AWS_ELB = 0b011010; // AWS ELB doesn't send X-Forwarded-Host
+    const HEADER_X_FORWARDED_TRAEFIK = 0b111110; // All "X-Forwarded-*" headers sent by Traefik reverse proxy
+    const HEADER_X_FORWARDED_PREFIX = 0b100000;
```
Comment (stof) [inline src/Symfony/Component/HttpFoundation/Request.php:50]: please move that one before `HEADER_X_FORWARDED_ALL`, so we first have the constants defining individual headers and then the convenience constants defining pre-defined masks for specific use cases (I would even add an empty line between them)

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 4]
```diff
@@ -894,6 +897,24 @@ public function getBasePath()
...
+        return $trustedPrefix.$this->getBaseUrlReal();
+    }
+
+    /**
+     * Returns the real base URL received by the webserver from which this request is executed.
+     * The URL does not include trusted reverse proxy prefix.
+     *
+     * @return string The raw URL (i.e. not urldecoded)
+     */
+    protected function getBaseUrlReal()
```
Comment (stof) [inline src/Symfony/Component/HttpFoundation/Request.php:917]: should be private, as there is no reason to make it an extension point.

File: src/Symfony/Component/HttpFoundation/Tests/RequestTest.php [hunk 5]
```diff
@@ -2278,6 +2278,34 @@ public function testTrustedHost()
...
+        //test with index deployed under root
+        $request = Request::create('/method');
+        $request->server->set('REMOTE_ADDR', '1.1.1.1');
+        $request->headers->set('X-Forwarded-Prefix', '/myprefix');
+        $request->headers->set('Forwarded', 'host=localhost:8080');
+
+        $this->assertSame('/myprefix', $request->getBaseUrl());
+        $this->assertSame('/method', $request->getPathInfo());
+
+        //test with index file deployed in subdir, i.e. local dev server (insecure!!)
```
Comment (stof) [inline src/Symfony/Component/HttpFoundation/Tests/RequestTest.php:2294]: I suggest to split the 2 tests in separate test methods rather than bundling them in the same method and hiding that we actually run 2 separate tests.

**Comment by stof** [comment]
`getBasePath` also needs to account for the proxy prefix

**Comment by jeff1985** [comment]
Hi @stof,

do you have any idea, why the integration tests are failing? The error does not seem to be related to my changes.

File: src/Symfony/Component/HttpFoundation/Tests/RequestTest.php (hunk 5 above)
Comment (jeff1985) [reply src/Symfony/Component/HttpFoundation/Tests/RequestTest.php]: done

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 4 above)
Comment (jeff1985) [reply src/Symfony/Component/HttpFoundation/Request.php]: fixed

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 3 above)
Comment (jeff1985) [reply src/Symfony/Component/HttpFoundation/Request.php]: done

**Comment by jeff1985** [comment]
> `getBasePath` also needs to account for the proxy prefix

Do you have any special condition in mind that we should take care of? I checked the code, and actually `getBasePath` uses `getBaseUrl` internally, so it should work without modifications. I added a check in the tests to make sure it works as expected.

**Comment by stof** [comment]
hmm, I forgot that `prepareBasePath` uses `getBaseUrl`. So this might be a matter of adding an assertion in the tests to avoid regressions there, but there might indeed not need any change in the code.

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 6]
```diff
@@ -894,6 +898,24 @@ public function getBasePath()
      * @return string The raw URL (i.e. not urldecoded)
      */
     public function getBaseUrl()
+    {
+        $trustedPrefix = '';
+
+        // the proxy prefix must be prepended to any prefix being needed at the webserver level
+        if ($this->isFromTrustedProxy() && $trustedPrefix = $this->getTrustedValues(self::HEADER_X_FORWARDED_PREFIX)) {
```
Comment (stof) [inline src/Symfony/Component/HttpFoundation/Request.php:905]: The error in tests is because of an `Array to string conversion` notice at line 909. This is caused by this assignment, where you override the `$trustedPrefix` variable with an empty array when the request is from a trusted proxy but without any trusted value for the prefix.
The solution is simple: use a different variable name for the array of trusted values.

**Review by stof — CHANGES_REQUESTED** [review]

**Comment by jeff1985** [comment]
> hmm, I forgot that `prepareBasePath` uses `getBaseUrl`. So this might be a matter of adding an assertion in the tests to avoid regressions there, but there might indeed not need any change in the code.

Yep, ok. The assertion in tests is already done.

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 6 above)
Comment (jeff1985) [reply src/Symfony/Component/HttpFoundation/Request.php]: I've added a fix and also a test for empty values. However this does not seem to help, integration is still failing. 
Locally I dont have such errors. Could you have a second look?

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 7]
```diff
@@ -1910,11 +1932,16 @@ protected function preparePathInfo()
             $requestUri = '/'.$requestUri;
         }
 
-        if (null === ($baseUrl = $this->getBaseUrl())) {
+        if (null === ($baseUrl = $this->getBaseUrlReal())) {
             return $requestUri;
         }
 
-        $pathInfo = substr($requestUri, \strlen($baseUrl));
+        if (!empty($baseUrl) && 0 === strpos($requestUri, $baseUrl)) {
```
Comment (stof) [inline src/Symfony/Component/HttpFoundation/Request.php:1939]: why are you changing that code ? Is this related to your change ?

Comment (jeff1985) [reply src/Symfony/Component/HttpFoundation/Request.php]: good point. this was originally needed fix for length before I realized we need a separate `getBaseUrlReal` function. now it's not needed any more. I reverted it back to the original state.

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 6 above)
Comment (stof) [reply src/Symfony/Component/HttpFoundation/Request.php]: The tests which failed previously are now passing. The remaining failure is unrelated to your PR and already fails in master (this is being solved in https://github.com/symfony/symfony/pull/37728)

Comment (jeff1985) [reply src/Symfony/Component/HttpFoundation/Request.php]: ok thank you for clarifying that!

**Comment by jeff1985** [comment]
Hi @stof 

as far as I see all issues are now resolved, right? Are there any todos to get this merged?

**Review by fabpot — APPROVED** [review]

File: src/Symfony/Component/HttpFoundation/CHANGELOG.md [hunk 8]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+5.3.0
```
Comment (maxhelias) [inline src/Symfony/Component/HttpFoundation/CHANGELOG.md:4]: Isn't it rather 5.2?
