### PR TITLE
[Notifier] unsupported options exception

### LINKED ISSUE #59120: Streamline one more exception for the bridges regarding option classes
Take for example the [GoIpTransport](https://github.com/symfony/symfony/blob/7.3/src/Symfony/Component/Notifier/Bridge/GoIp/GoIpTransport.php), it contains the following lines:

https://github.com/symfony/symfony/blob/c98b02aff916ac864f3dc140dd84fac7029a7a39/src/Symfony/Component/Notifier/Bridge/GoIp/GoIpTransport.php#L65-L67

I would like to have a dedicated exception class `UnsupportedOptionsException`, basically the same as I did in 
* https://github.com/symfony/symfony/pull/39365

This could be done for all bridges which already use options.

> [!NOTE]  
> It is important to also raise the notifier version to `7.3` in the `composer.json` files where this new exception is used.

### PR DESCRIPTION
**Pull request by raphael-geffroy**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59120 
| License       | MIT

Streamline one more exception for the bridges regarding option classes.

### CODE REVIEW

**Comment by OskarStark** [comment]
Thanks, you need to raise the minimum `symfony/notifier` version to `7.3` for those bridges, using the new exception class

**Review by OskarStark — APPROVED** [review]

**Comment by raphael-geffroy** [comment]
@OskarStark like this ? 🤔

File: src/Symfony/Component/Notifier/Exception/UnsupportedOptionsException.php [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+{
+    public function __construct(string $transport, string $supported)
+    {
+        $message = \sprintf(
+            'The "%s" transport only supports instances of "%s" for options.',
+            $transport,
+            $supported
+        );
+
+        parent::__construct($message);
```
Comment (xabbuh) [inline src/Symfony/Component/Notifier/Exception/UnsupportedOptionsException.php]:
```suggestion
        parent::__construct(\sprintf('The "%s" transport only supports instances of "%s" for options.', $transport, $supported));
```

**Comment by xabbuh** [comment]
maybe we should also add the type that was actually passed as part of the exception message

**Comment by raphael-geffroy** [comment]
I did it at first, inspired by the \Symfony\Component\Notifier\Exception\UnsupportedMessageTypeException and then I saw that all the existing exception had the same format so I reused it.
But I agree with you, I'll revert to this step then !

**Comment by raphael-geffroy** [comment]
@xabbuh Done ✅ (reused the format of the \Symfony\Component\Notifier\Exception\UnsupportedMessageTypeException)

File: src/Symfony/Component/Notifier/Exception/UnsupportedOptionsException.php [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+use Symfony\Component\Notifier\Message\MessageOptionsInterface;
+
+/**
+ * @author Raphaël Geffroy <raphael@geffroy.dev>
+ */
+class UnsupportedOptionsException extends LogicException
+{
+    public function __construct(string $transport, string $supported, MessageOptionsInterface $given)
+    {
+        parent::__construct(\sprintf(
```
Comment (xabbuh) [inline src/Symfony/Component/Notifier/Exception/UnsupportedOptionsException.php]: please keep the call on one line

Comment (raphael-geffroy) [reply src/Symfony/Component/Notifier/Exception/UnsupportedOptionsException.php]: Sorry, did not understand that the first time. Done ✅

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @raphael-geffroy.

**Comment by raphael-geffroy** [comment]
Thanks to you @OskarStark @xabbuh @fabpot 🫶
