### PR TITLE
[Process] Fix executable finder when the command starts with a dash

### LINKED ISSUE #53479: [Process] ExecutableFinder::find() method will execute `exec()` by passed the name parameter
### Symfony version(s) affected

v6.4.2

### How to reproduce

In my Laravel project composer.json file, script defined a few script like that 

```json
"post-update-cmd": [
            "@php -r \"file_put_contents('storage/local/last-composer-lock-hash', md5_file('composer.lock'));\""
        ],
```

when I run `composer run script post-update-cmd` the composer package will remove the prefix `@php ` and extract `-r` to determine if the file is executable, and then the `exec('command -v')` will execute `-r` that `exec('command -v -r')` and output a message that "sh: line 0: command: -r: invalid option
command: usage: command [-pVv] command [arg ...]
"
 

### Possible Solution

I want to pull a PR to update the `exec()` function, What do you think about that?

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by kayw-geek**
| Q             | A
| ------------- | ---
| Branch?       |  5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #53479 
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/Process/ExecutableFinder.php [hunk 1]
```diff
@@ -69,7 +69,7 @@ public function find(string $name, string $default = null, array $extraDirs = []
         }
 
         $command = '\\' === \DIRECTORY_SEPARATOR ? 'where' : 'command -v';
-        if (\function_exists('exec') && ($executablePath = strtok(@exec($command.' '.escapeshellarg($name)), \PHP_EOL)) && @is_executable($executablePath)) {
+        if (\function_exists('exec') && !str_starts_with($name,'-') &&($executablePath = strtok(@exec($command.' '.escapeshellarg($name)), \PHP_EOL)) && @is_executable($executablePath)) {
```
Comment (xabbuh) [inline src/Symfony/Component/Process/ExecutableFinder.php]: this looks wrong to me, if `$name` is not an executable it shouldn't be passed to `find()` in the first place

**Review by xabbuh — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Process/ExecutableFinder.php (hunk 1 above)
Comment (kayw-geek) [reply src/Symfony/Component/Process/ExecutableFinder.php]: In order to avoid users who do not understand the specific implementation of the following error, I think we should avoid similar problems, although the current method's responsibility is to find the executable file, but in the current implementation of the use of exec to execute command -v command to find, I think that to avoid the exec output error also belongs to the function needs to be implemented responsibilities
```bash 
sh: line 0: command: -r: invalid option
command: usage: command [-pVv] command [arg ...]
```

Comment (xabbuh) [reply src/Symfony/Component/Process/ExecutableFinder.php]: I am sorry but I do not understand what you mean.

Comment (kayw-geek) [reply src/Symfony/Component/Process/ExecutableFinder.php]: I believe that since the current method uses the `exec()` function, then the `find()` method should have the responsibility to prevent exceptions from occurring with `exec()`.

File: src/Symfony/Component/Process/ExecutableFinder.php [hunk 2]
```diff
@@ -69,7 +69,7 @@ public function find(string $name, string $default = null, array $extraDirs = []
         }
 
         $command = '\\' === \DIRECTORY_SEPARATOR ? 'where' : 'command -v';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Process/ExecutableFinder.php]: instead of the proposed change, I'd suggest this:
```suggestion
        $command = '\\' === \DIRECTORY_SEPARATOR ? 'where' : 'command -v --';
```

Comment (kayw-geek) [reply src/Symfony/Component/Process/ExecutableFinder.php]: @nicolas-grekas missed a blank space?

Comment (nicolas-grekas) [reply src/Symfony/Component/Process/ExecutableFinder.php]: The space is added on the line below

**Comment by nicolas-grekas** [comment]
Thank you @kayw-geek.
