### PR TITLE
[Lock] Fix StoreFactory to accept same DSN syntax as AbstractAdapter

### LINKED ISSUE #35350: Lock Component - multiple host DSN
Hello,

StoreFactory shouldn't check 
```
redis:\\
rediss:\\
```

because when we want to use multiple hosts we should use 
```
redis:?host[localhost]&host[localhost:6379]&host[/var/run/redis.sock:]&auth=my-password&redis_cluster=1
```

Source:
https://raw.githubusercontent.com/symfony/lock/master/Store/StoreFactory.php

### PR DESCRIPTION
**Pull request by Jontsa**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35350
| License       | MIT
| Doc PR        |

Updates `Symfony\Component\Lock\Store\StoreFactory` to accept same DSN syntax as `Symfony\Component\Cache\Adapter\AbstractAdapter` which is used to create Redis class instance.

### CODE REVIEW

**Review by jderusse — COMMENTED** [review]
I'm fine with this PR form a technical point of view. 

But you have to keep in mind that using Lock with a cluster of Redis/memcached is not reliable: by default [replication is asynchronous](https://redis.io/topics/replication), meaning, one process is able to acquire a Lock, which may not be propagated to replica, and, if primary has a failure, another process will be able to acquire the same lock .

You should use a CombineStore to achieve a HA with multiple Memcached/Redis

nb: This is already recommended in Documentation: https://symfony.com/doc/current/components/lock.html#id6

I think we should open a PR to add a [WAIT](https://redis.io/commands/wait) in RedisStore that assure that a least 50%+1 servers in the cluster are synchronized

File: src/Symfony/Component/Lock/Store/RedisStore.php [hunk 1]
```diff
@@ -38,7 +38,7 @@ class RedisStore implements StoreInterface
      */
     public function __construct($redisClient, float $initialTtl = 300.0)
     {
-        if (!$redisClient instanceof \Redis && !$redisClient instanceof \RedisArray && !$redisClient instanceof \RedisCluster && !$redisClient instanceof \Predis\ClientInterface && !$redisClient instanceof RedisProxy) {
+        if (!$redisClient instanceof \Redis && !$redisClient instanceof \RedisArray && !$redisClient instanceof \RedisCluster && !$redisClient instanceof \Predis\ClientInterface && !$redisClient instanceof RedisProxy && !$redisClient instanceof RedisClusterProxy) {
```
Comment (jderusse) [inline src/Symfony/Component/Lock/Store/RedisStore.php]: That were missing on purpose. see my previous comment. 
From a concurrency point of view, using a cluster is less reliable than a single node.

Comment (Jontsa) [reply src/Symfony/Component/Lock/Store/RedisStore.php:41]: I understand and using CombinedStore would remain as the recommended way in documentation. But from a point of consistency, one would expect RedisStore and StoreFactory to work with same DSN syntax as AbstractAdapter since that is being used in the background. For me this seems like unexpected behaviour.

Comment (stof) [reply src/Symfony/Component/Lock/Store/RedisStore.php:41]: Well, if the RedisStore does not support clusters on purpose, I don't see why we should add it just for consistency. Consistency is good when you want that 2 implementations supporting clusters do it with the same DSN syntax. But it is not a reason to support non-working features IMO.

Comment (jderusse) [reply src/Symfony/Component/Lock/Store/RedisStore.php:41]: I will be happy to review and approve a PR that add `WAIT` in RedisStore. 
That would fix the reliability issue, and allows us to use RedisCluster connection.

Comment (Jontsa) [reply src/Symfony/Component/Lock/Store/RedisStore.php:41]: As I understood, lock store will work even when using a cluster but it just is not as reliable in case of failrue? This is already documented and user has been warned but they would have the option.

**Comment by jderusse** [comment]
fixed by #37590

**Comment by fabpot** [comment]
@jderusse Shall we close then? Should we also close #35350?

**Comment by Jontsa** [comment]
#37590 partially fixes this issue. StoreFactory still does not support the same exact DSN syntax as Symfony\Component\Cache\Adapter\AbstractAdapter for Redis connections.

But this PR can be closed if we do not want to allow DSN with multiple Redis hosts for Locks.

**Comment by jderusse** [comment]
You're right @Jontsa  can you rebase your PR and keep the part about DSN pattern?

**Comment by fabpot** [comment]
@Jontsa Do you time to finish this PR?

**Comment by fabpot** [comment]
@Jontsa I think you will need to rebase on the current 4.4 branch as there are some conflicts.

File: src/Symfony/Component/Lock/Tests/Store/StoreFactoryTest.php [hunk 2]
```diff
@@ -58,12 +58,14 @@ public function validConnections()
         }
         if (class_exists(\Memcached::class) && class_exists(AbstractAdapter::class)) {
             yield ['memcached://server.com', MemcachedStore::class];
+            yield ['memcached:?host[localhost]&host[localhost:12345]', MemcachedStore::class];
         }
-        if (class_exists(\Redis::class) && class_exists(AbstractAdapter::class)) {
+        if ((class_exists(\Redis::class) || class_exists(\Predis\Client::class)) && class_exists(AbstractAdapter::class)) {
```
Comment (jderusse) [inline src/Symfony/Component/Lock/Tests/Store/StoreFactoryTest.php:63]: Revert this.

The purpose of this check is to avoid failing tests when the extension is not installed.

By checking if Predis is installed (which is always true because in require-dev) this breaks the initial check.

**Review by jderusse — COMMENTED** [review]
A small comment about change in tests.

Then, I'm :+1: with the PR

**Review by fabpot — APPROVED** [review]
Taking over

**Comment by fabpot** [comment]
Thank you @Jontsa.

File: src/Symfony/Component/Lock/Tests/Store/StoreFactoryTest.php (hunk 2 above)
Comment (xabbuh) [reply src/Symfony/Component/Lock/Tests/Store/StoreFactoryTest.php:63]: fixed in 6a79f3e06fb9560ed3ec9f57983415a50e883887
