### PR TITLE
[PhpUnitBridge] Fix deprecation handler with PHPUnit 10

### LINKED ISSUE #41580: [phpunit-bridge] getPhpUnitErrorHandler doesn't support PHPUnit10
**Symfony version(s) affected**: 5.3.0

**Description**
Method [getPhpUnitErrorHandler](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L348) 

Method checks if `PHPUnit\Util\ErrorHandler` class exists. However in PHPUnit 10 they changed the name of that class to: `PHPUnit\Util\Error\Handler`

This is why you should add one more condition to check if you are between 8.3 and 10 version of PHPUnit. Then you have to create a proper error `Handler`.

Some dirty fix:

```php
use PHPUnit\Util\Error\Handler;
private static $isAtLeastPhpUnit100;

...

if (!isset(self::$isAtLeastPhpUnit83)) {
    self::$isAtLeastPhpUnit83 = class_exists(ErrorHandler::class) && method_exists(ErrorHandler::class, '__invoke');
}

if (!isset(self::$isAtLeastPhpUnit100)) {
    self::$isAtLeastPhpUnit100 = class_exists(Handler::class) && method_exists(Handler::class, '__invoke');
}

...
if (!self::$isAtLeastPhpUnit100) {
    return new ErrorHandler();
} else {
    return new Handler();
}

### PR DESCRIPTION
**Pull request by YaFou**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41580
| License       | MIT
| Doc PR        | 

With PHPUnit 10, a lot of classes and methods were refactored. This PR adds the support of PHPUnit 10 into the deprecation handler.

### CODE REVIEW

File: src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Deprecation.php [hunk 1]
```diff
@@ -100,7 +102,7 @@ public function __construct($message, array $trace, $file)
             return;
         }
 
-        $test = isset($line['args'][0]) ? $line['args'][0] : null;
+        $test = $line['args'][0] ?? null;
```
Comment (derrabus) [inline src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Deprecation.php]: Should be reverted.

File: src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Deprecation.php [hunk 2]
```diff
@@ -193,11 +195,15 @@ public function isLegacy()
 
         $method = $this->originatingMethod();
 
+        $groups = class_exists(Handler::class) ?
```
Comment (derrabus) [inline src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Deprecation.php]:
```suggestion
        $groups = class_exists(Groups::class) ?
```

File: src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Deprecation.php [hunk 3]
```diff
@@ -313,7 +319,7 @@ private static function getVendors()
             foreach (get_declared_classes() as $class) {
                 if ('C' === $class[0] && 0 === strpos($class, 'ComposerAutoloaderInit')) {
                     $r = new \ReflectionClass($class);
-                    $v = \dirname(\dirname($r->getFileName()));
+                    $v = \dirname($r->getFileName(), 2);
```
Comment (derrabus) [inline src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Deprecation.php]: Should be reverted.

File: src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php [hunk 4]
```diff
@@ -339,12 +341,20 @@ private static function getPhpUnitErrorHandler()
             self::$isAtLeastPhpUnit83 = class_exists(ErrorHandler::class) && method_exists(ErrorHandler::class, '__invoke');
         }
         if (!self::$isAtLeastPhpUnit83) {
-            return 'PHPUnit\Util\ErrorHandler::handleError';
+            if (!isset(self::$isAtLeastPhpUnit100)) {
```
Comment (derrabus) [inline src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php]: Why is this nested inside the other `if`?

**Review by derrabus — CHANGES_REQUESTED** [review]

File: src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Deprecation.php (hunk 1 above)
Comment (YaFou) [reply src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Deprecation.php]: Fabbot threw me an exception.

Comment (nicolas-grekas) [reply src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Deprecation.php]: the bridge must remain compatible with PHP 7.1
fabbot doesn't know about that, but we do

Comment (derrabus) [reply src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Deprecation.php]: 5.5 actually. 🤓

**Comment by nicolas-grekas** [comment]
Thank you @YaFou.
