### PR TITLE
[Serializer] fix denormalization of string-arrays with only one element

### LINKED ISSUE #33731: Symfony serializer does not map string-collections correctly in XML
**Symfony version(s) affected**: 3.4, 4.4

**Description**  
When there is a collection with a single item which shall be deserialized to a string array, the serializer produces an error instead of an array with one string.

A very simliar bug, but for collections of objects, was already reported in #27279 and fixed in https://github.com/symfony/symfony/commit/ac70edf8cd6e63919129584108dadf327c18669a

```
Fatal error: Uncaught Symfony\Component\Serializer\Exception\NotNormalizableValueException: The type of the "offices" attribute for class "App\Entities\Buildings" must be one of "array" ("string" given). in .../symfony-collection-serializer-bug/Normalizer/AbstractObjectNormalizer.php:298
Stack trace:
#0 .../symfony-collection-serializer-bug/Normalizer/AbstractObjectNormalizer.php(202): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->validateAndDenormalize('App\\Entities\\Bu...', 'offices', 'only one office...', 'xml', Array)
#1 .../symfony-collection-serializer-bug/Serializer.php(172): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denormalize(Array, 'App\\Entities\\Bu...', 'xml', Array)
#2 .../symfony-collection-serializer-bug/Serializer.php(123): Symfony\Component\Serializer\Serializer->denormalize(Array, 'App\\Entities\\Bu...', 'xml', Array)
#3 .../symfony-collection-serializer-bug/Normalizer/AbstractObjectNormalizer.php on line 298
```

**How to reproduce**  
https://github.com/mkrauser/symfony-collection-serializer-bug
Just run php src/serialize.php

**Possible Solution**  
Just like in https://github.com/symfony/symfony/commit/ac70edf8cd6e63919129584108dadf327c18669a, I'll create a PR

**Additional context**  
Tested with php 7.2

### PR DESCRIPTION
**Pull request by mkrauser**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  |no
| Deprecations? |no
| Tickets       | Fix #33731
| License       | MIT
| Doc PR        | 

This PR does almost the same as https://github.com/symfony/symfony/commit/ac70edf8cd6e63919129584108dadf327c18669a, just not only for arrays of objects.

### CODE REVIEW

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 1]
```diff
@@ -257,6 +257,12 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
                 if (null !== $collectionKeyType = $type->getCollectionKeyType()) {
                     $context['key_type'] = $collectionKeyType;
                 }
+            } elseif ($type->isCollection() && null !== $type->getCollectionValueType()) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: I'd suggest merging these conditions with the next if:
`if ('xml' === $format && !\is_array($data) && $type->isCollection() && null !== $type->getCollectionValueType()) {`

**Review by darielopper — APPROVED** [review]

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php (hunk 1 above)
Comment (mkrauser) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: Thank you for your feedback and all your work! Done...

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php [hunk 2]
```diff
@@ -121,16 +121,54 @@ private function getDenormalizerForDummyCollection()
...
-                    new Type(
-                        'array',
-                        false,
-                        null,
-                        true,
-                        new Type('int'),
-                        new Type('object', false, DummyChild::class)
-                    ),
-                ],
+                [new Type('array', false, null, true, new Type('int'), new Type('object', false, DummyChild::class))],
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: I just did some CS fixes, including this one :)

**Review by nicolas-grekas — APPROVED** [review]

**Review by dunglas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @mkrauser.
