### PR TITLE
[DependencyInjection] Fix issue between decorator and service locator index

### LINKED ISSUE #53174: [DIC] Decorator + TaggedLocator does not play well
### Symfony version(s) affected

6.4.x

### Description

according to the docs, you can use a serviceLocator to load a workflow using  a taggedlocater.
` #[TaggedLocator('workflow')]`, e.g.
The WorkflowDebugPass.php introduced in 6.4 however prefixes all the workflow keys with 'debug.' when `kernel->isDebug()` and this makes it unwieldy to get a workflow by key.

### How to reproduce

The following class allows me to load a workflow dynamically, without specifically injecting a certain workflow.  It avoids injecting the registry, as recommended in the Symfony docs. This still works in 6.3, but no longer in 6.4.

````php
#WorkflowLoader.php

WARNING: this no longer works as of Symfony 6.4

use Psr\Container\ContainerExceptionInterface;
use Psr\Container\ContainerInterface;
use Psr\Container\NotFoundExceptionInterface;
use Symfony\Component\DependencyInjection\Attribute\TaggedLocator;
use Symfony\Component\Workflow\WorkflowInterface;
use RuntimeException;

class WorkflowLoader
{
    public function __construct(
        #[TaggedLocator('workflow')] private readonly ContainerInterface $serviceLocator
    )
    {
    }

    public function getWorkflow($workflowName): WorkflowInterface
    {
        try {
            if (!$workflow = $this->serviceLocator->get('state_machine.' . $workflowName)) {
                $workflow = $this->serviceLocator->get('workflow.' . $workflowName);
            }
        } catch (NotFoundExceptionInterface|ContainerExceptionInterface $e) {
            throw new RuntimeException("Process Workflow $workflowName could not be loaded. \n" . $e->getMessage());
        }
        return $workflow;
    }
}
````

### Possible Solution

As a workaround, I can test for the environment in my class, but I think the WorkflowDebugPass should not be called automatically, but only by specific configuration. It is also should be documented.

In general, It would be great to be able to lazyload Workflows dynamically. If you don't know which workflow you need in advance, then a service can't know which one to inject. 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #53174
| License       | MIT

This PR is not finished yet. I want to gather feedback before writing tests.

To explain what is wrong, I create a [reproducer](https://github.com/lyrixx/test/tree/symfony/symfony/pull/58000).

Basically, when we decorates a services, we replace the old ID with a new ID in the DIC.

Then, when we build a service locator, we use the new ID. This is really not handy because our code
is dependant on the new name or old name, depending if the decorator is here or not!

This issue discribe very well the issue: https://github.com/symfony/symfony/issues/53174

So in this PR, I save the original ID in the decorator definition. Then I used this initial ID to build the `$index` of the 
service locator.

---

With this PR and the reproducer, I got what would be expected

image

* Original ID in the locator
* But we retrieve the decorated
* Works well with decorator of decorator (etc)

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
The patch is nice, but in 6.4, we already have infrastructure in place to pass the inner around, see #49625 and #50710.

Can't we leverage this? Or backport if that's needed for the fix on 5.4?

**Comment by lyrixx** [comment]
@nicolas-grekas Thanks for the review ; ✅

File: src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php [hunk 1]
```diff
@@ -82,7 +82,8 @@ private function findAndSortTaggedServices($tagName, ContainerBuilder $container
                 } elseif (null === $defaultIndex && $defaultPriorityMethod && $class) {
                     $defaultIndex = PriorityTaggedServiceUtil::getDefault($container, $serviceId, $class, $defaultIndexMethod ?? 'getDefaultName', $tagName, $indexAttribute, $checkTaggedItem);
                 }
-                $index = $index ?? $defaultIndex ?? $defaultIndex = $serviceId;
+                $decorated = $definition->getTag('container.decorator')[0]['id'] ?? null;
+                $index = $index ?? $defaultIndex ?? $defaultIndex = ($decorated ?? $serviceId);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php]:
```suggestion
                $index = $index ?? $defaultIndex ?? $defaultIndex = $decorated ?? $serviceId;
```

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php (hunk 1 above)
Comment (lyrixx) [reply src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php]: BTW, I don't understand why there is an assignation here. If I remove it, tests are still okay

---

anyway, fixed, thanks

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php]: The assignation is to compute the default index only once since we're in a foreach loop

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @lyrixx.
