### PR TITLE
[DoctrineBridge] Fix `Connection::createSchemaManager()` for Doctrine DBAL v2

### LINKED ISSUE #58955: [DoctrineBridge] Fix Connection::createSchemaManager() for Doctrine DBAL v2
### Symfony version(s) affected

6.4

### Description

As the 6.4 symfony/doctrine-bridge is compatible with doctrine/dbal 2.13 we need to check for createSchemaManager existance and use getSchemaManager instead if necessary (like it's already done in the messenger component for instance)

### How to reproduce

With a Symfony 6.4 project using :

"doctrine/dbal": "<3.0",
"doctrine/doctrine-bundle": "<2.8",
"doctrine/doctrine-migrations-bundle": "^3.3",
"doctrine/orm": "<3.0",

### Possible Solution

https://github.com/symfony/symfony/pull/58956

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by neodevcode**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58955
| License       | MIT

As the 6.4 symfony/doctrine-bridge is compatible with doctrine/dbal 2.13  we need to check for createSchemaManager existance and use getSchemaManager instead if necessary (like it's already done in the messenger component for instance)

### CODE REVIEW

**Comment by xabbuh** [comment]
Can we cover this with a test to prevent regressions?

**Comment by neodevcode** [comment]
I guess I can !

File: src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php [hunk 1]
```diff
@@ -24,7 +24,9 @@ abstract public function postGenerateSchema(GenerateSchemaEventArgs $event): voi
     protected function getIsSameDatabaseChecker(Connection $connection): \Closure
     {
         return static function (\Closure $exec) use ($connection): bool {
-            $schemaManager = $connection->createSchemaManager();
+            $schemaManager = method_exists($connection, 'createSchemaManager')
+            ? $connection->createSchemaManager()
+            : $connection->getSchemaManager();
```
Comment (OskarStark) [inline src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php]:
```suggestion
                ? $connection->createSchemaManager()
                : $connection->getSchemaManager();
```

Comment (xabbuh) [reply src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php]: I would actually put it on one line:

```php
            $schemaManager = method_exists($connection, 'createSchemaManager') ? $connection->createSchemaManager() : $connection->getSchemaManager();
```

Comment (neodevcode) [reply src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php]: I let you guys decide, but here it's on two lines : https://github.com/symfony/symfony/blob/992a6a05fa4788da21871210e62ed3948d895b92/src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php#L608

**Comment by nicolas-grekas** [comment]
Thank you @neodevcode.
