### PR TITLE
[Lock] Use plain text (vs. hash) for short key names with database stores

### LINKED ISSUE #57906: [Lock] MySQL reports deadlocks which are difficult to investigate
### Symfony version(s) affected

6.4.6 but I guess it happens with newest ones too as there are no changes according to the changelog

### Description

MySQL reports deadlocks like this one when using the Lock component:
```
------------------------
LATEST DETECTED DEADLOCK
------------------------
2024-08-02 02:42:39 125380545455680
*** (1) TRANSACTION:
TRANSACTION 2755326397, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
LOCK WAIT 3 lock struct(s), heap size 1128, 2 row lock(s)
MySQL thread id 610443, OS thread handle 125380125038144, query id 23603665462 10.10.13.8 app-read-write update
INSERT INTO lock_keys (key_id, key_token, key_expiration) VALUES ('c0c39cdb26e264f91ea3628f2ab2c87b04cee54fa6dc5bc2e75a499d022110a9', 'iyNOnmWrqJBjkAh5C77LMZjFKFDBQIBEntYf+RmzDVY=', UNIX_TIMESTAMP() + 300)

*** (1) HOLDS THE LOCK(S):
RECORD LOCKS space id 191 page no 180 n bits 192 index PRIMARY of table `bbwzm3n4u`.`lock_keys` trx id 2755326397 lock mode S locks rec but not gap
Record lock, heap no 63 PHYSICAL RECORD: n_fields 5; compact format; info bits 32
 0: len 30; hex 633063333963646232366532363466393165613336323866326162326338; asc c0c39cdb26e264f91ea3628f2ab2c8; (total 64 bytes);
 1: len 6; hex 0000a43af1bc; asc    :  ;;
 2: len 7; hex 01000054532ef0; asc    TS. ;;
 3: len 30; hex 77556d4f3542534134744e6c417766436445397a6c727863467a666b4c4d; asc wUmO5BSA4tNlAwfCdE9zlrxcFzfkLM; (total 44 bytes);
 4: len 4; hex 66ac48cb; asc f H ;;


*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 191 page no 180 n bits 192 index PRIMARY of table `bbwzm3n4u`.`lock_keys` trx id 2755326397 lock_mode X locks rec but not gap waiting
Record lock, heap no 63 PHYSICAL RECORD: n_fields 5; compact format; info bits 32
 0: len 30; hex 633063333963646232366532363466393165613336323866326162326338; asc c0c39cdb26e264f91ea3628f2ab2c8; (total 64 bytes);
 1: len 6; hex 0000a43af1bc; asc    :  ;;
 2: len 7; hex 01000054532ef0; asc    TS. ;;
 3: len 30; hex 77556d4f3542534134744e6c417766436445397a6c727863467a666b4c4d; asc wUmO5BSA4tNlAwfCdE9zlrxcFzfkLM; (total 44 bytes);
 4: len 4; hex 66ac48cb; asc f H ;;


*** (2) TRANSACTION:
TRANSACTION 2755326398, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
LOCK WAIT 3 lock struct(s), heap size 1128, 2 row lock(s)
MySQL thread id 624364, OS thread handle 125379871249984, query id 23603665471 10.10.13.10 app-read-write update
INSERT INTO lock_keys (key_id, key_token, key_expiration) VALUES ('c0c39cdb26e264f91ea3628f2ab2c87b04cee54fa6dc5bc2e75a499d022110a9', 'bT4yW/bpDThzAgHWxqjc0IEzJA7oCofHoKXqrTac808=', UNIX_TIMESTAMP() + 300)

*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 191 page no 180 n bits 192 index PRIMARY of table `bbwzm3n4u`.`lock_keys` trx id 2755326398 lock mode S locks rec but not gap
Record lock, heap no 63 PHYSICAL RECORD: n_fields 5; compact format; info bits 32
 0: len 30; hex 633063333963646232366532363466393165613336323866326162326338; asc c0c39cdb26e264f91ea3628f2ab2c8; (total 64 bytes);
 1: len 6; hex 0000a43af1bc; asc    :  ;;
 2: len 7; hex 01000054532ef0; asc    TS. ;;
 3: len 30; hex 77556d4f3542534134744e6c417766436445397a6c727863467a666b4c4d; asc wUmO5BSA4tNlAwfCdE9zlrxcFzfkLM; (total 44 bytes);
 4: len 4; hex 66ac48cb; asc f H ;;


*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 191 page no 180 n bits 192 index PRIMARY of table `bbwzm3n4u`.`lock_keys` trx id 2755326398 lock_mode X locks rec but not gap waiting
Record lock, heap no 63 PHYSICAL RECORD: n_fields 5; compact format; info bits 32
 0: len 30; hex 633063333963646232366532363466393165613336323866326162326338; asc c0c39cdb26e264f91ea3628f2ab2c8; (total 64 bytes);
 1: len 6; hex 0000a43af1bc; asc    :  ;;
 2: len 7; hex 01000054532ef0; asc    TS. ;;
 3: len 30; hex 77556d4f3542534134744e6c417766436445397a6c727863467a666b4c4d; asc wUmO5BSA4tNlAwfCdE9zlrxcFzfkLM; (total 44 bytes);
 4: len 4; hex 66ac48cb; asc f H ;;

*** WE ROLL BACK TRANSACTION (2)
```

### How to reproduce

I don't know how to reproduce it because I don't know which key my application is trying to lock.

My understanding is that, somehow, the lock component first MySQL-wise locks the record with a `SELECT` statement before the `INSERT` statement.

That shared lock would come from a call to the `PersistingStoreInterface::exists()` method from a call to the `Lock::isAcquired()` method.

### Possible Solution

This bug is about investigating what lock usage is causing this in my application.

Right now, it is difficult because `lock_id` obfuscates the locked key:
image

It comes from `\Symfony\Component\Lock\Store\DatabaseTableTrait::getHashedKey()` that hashes the key.

I understand this hash is useful when the key is longer than 64 chars.

An alternative may be
```
private function getHashedKey(Key $key): string
{
	$keyAsString = (string) $key;
	if (64 <= strlen($keyAsString)) {
		return $keyAsString;
	}
	return hash('sha256', $keyAsString);
}
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by sylfabre**
| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #57906
| License       | MIT

Use plain text for key names when they are short enough.

It helps to understand where inserted locks come from when looking at the database.

See https://github.com/symfony/symfony/issues/57906 for examples of how the locks look like in the database.

### CODE REVIEW

**Comment by sylfabre** [comment]
I'm not sure how to test this change, any feedback/tips are welcome!

File: src/Symfony/Component/Lock/Store/DatabaseTableTrait.php [hunk 1]
```diff
@@ -48,8 +48,12 @@ private function init(array $options, float $gcProbability, int $initialTtl): vo
     /**
      * Returns a hashed version of the key.
```
Comment (OskarStark) [inline src/Symfony/Component/Lock/Store/DatabaseTableTrait.php]: Needs to be adjusted

**Comment by stof** [comment]
This creates collisions for keys, as a long key is not considered the same resource than its hash.

File: src/Symfony/Component/Lock/Store/DatabaseTableTrait.php [hunk 2]
```diff
@@ -48,8 +48,12 @@ private function init(array $options, float $gcProbability, int $initialTtl): vo
...
      */
-    private function getHashedKey(Key $key): string
+    private function getKeyName(Key $key): string
     {
+        $keyAsString = (string) $key;
+        if (strlen($keyAsString) <= 64) {
+            return $keyAsString;
+        }
         return hash('sha256', (string) $key);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Lock/Store/DatabaseTableTrait.php]: It'd keep the original name + leverage PHP to do the cast:
```suggestion
    private function getHashedKey(string $key): string
    {
        return strlen($keyAsString) <= 64 ? $key : hash('sha256', $key);
```

**Review by nicolas-grekas — COMMENTED** [review]
I'm not sure I see what you mean @stof, can you please expand a bit?

Is there a reasonable case where the key could contain something binary? Shouldn't we hash it when it happens?

File: src/Symfony/Component/Lock/Store/DatabaseTableTrait.php (hunk 1 above)
Comment (sylfabre) [reply src/Symfony/Component/Lock/Store/DatabaseTableTrait.php]: Good catch, thanks!

File: src/Symfony/Component/Lock/Store/DatabaseTableTrait.php (hunk 2 above)
Comment (sylfabre) [reply src/Symfony/Component/Lock/Store/DatabaseTableTrait.php]: Thanks!

**Comment by sylfabre** [comment]
@stof May you please elaborate on your comment?
> This creates collisions for keys, as a long key is not considered the same resource than its hash.

Before this change, collisions were possible if two keys shared the same hash (very unlikely, but still possible).

With this change, collisions are possible if:
* Two large keys shared the same hash (very unlikely, but still possible) => Same as before
* [New] Or, a 64-character key matches the hash of a large key

Was your comment about this last point?

**Comment by stof** [comment]
@sylfabre yes, my comment is indeed about that point.

File: src/Symfony/Component/Lock/CHANGELOG.md [hunk 3]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+7.4
+---
+
+ * Use plain text (vs hash) for short key names with database stores
```
Comment (OskarStark) [inline src/Symfony/Component/Lock/CHANGELOG.md]:
```suggestion
 * Use plain text (vs. hash) for short key names with database stores
```

File: src/Symfony/Component/Lock/Store/DatabaseTableTrait.php [hunk 4]
```diff
@@ -46,11 +46,12 @@ private function init(array $options, float $gcProbability, int $initialTtl): vo
     }
 
     /**
-     * Returns a hashed version of the key.
+     * Returns the key name in the database.
+     * It returns a sha256 hash if the original key name is longer than 64 chars.
```
Comment (OskarStark) [inline src/Symfony/Component/Lock/Store/DatabaseTableTrait.php]:
```suggestion
     * It returns a sha256 hash, if the original key name is longer than 64 chars.
```

**Comment by sylfabre** [comment]
Thanks @stof 

I changed the PR
* <64 chars => I use the plain string
* \>= 64 => I use the hash

This prevents a 64-character plain string from colliding with a hashed large string.

This addresses the issue you pointed out, right?

**Comment by sylfabre** [comment]
Thanks @OskarStark for spotting the typos 👍

**Comment by nicolas-grekas** [comment]
Thank you @sylfabre.
