### PR TITLE
[Messenger] Setup queues once in AMQP

### LINKED ISSUE #32172: [Messenger][AQMP] Setup is called every time accessing the queue
**Symfony version(s) affected**: All since Messenger release

**Description**  
Messenger AMQP call setup method on each call to the queue like: `get`, `publish`, `publishWithDelay`.

**How to reproduce**  
```yaml
framework:
    messenger:
        transports:
             async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queues:
                        '':
                            binding_keys:
                              - pubsub
                            flags: 8
                    exchange:
                        name: pubsub
                        type: fanout
```

I am running modified code which don't sets name if queue name is empty:

```php
public function queue(string $queueName): \AMQPQueue
    {
        if (!isset($this->amqpQueues[$queueName])) {
            $queueConfig = $this->queuesOptions[$queueName];

            $amqpQueue = $this->amqpFactory->createQueue($this->channel());
            if ($queueName !== '') {
                $amqpQueue->setName($queueName);
            }

            $amqpQueue->setFlags($queueConfig['flags'] ?? AMQP_DURABLE);

            if (isset($queueConfig['arguments'])) {
                $amqpQueue->setArguments($queueConfig['arguments']);
            }

            $this->amqpQueues[$queueName] = $amqpQueue;
        }

        return $this->amqpQueues[$queueName];
    }
```

**Possible Solution**  
Have a flag in `Connection` object which says that setup has run and only run if AMQP returns 404 like in

https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Messenger/Transport/AmqpExt/Connection.php#L321

**Additional context**  
I am working on implementing pubsub on AMQP and getting into issues that with the random queue name messenger tries to call declareQueue on each call which leads to 403 because you can't define queue with `amq.*` prefix in normal cases it's alright as it just redefines it.

### LINKED ISSUE #38092: Messenger - AMQP Extension - auto_setup:true leads to poor performance on RabbitMq consumers
**Symfony version(s) affected**: 5.*
**Description**  
The transport configuration - auto_setup: true (that is the default) will try to create the exchange, the queue(s) and try to bind them, for every message retrieved from the queue, leading to low get/acknowledge rate. 

AmqpExt\Connection.php
```
 /**
     * Gets a message from the specified queue.
     *
     * @throws \AMQPException
     */
    public function get(string $queueName): ?\AMQPEnvelope
    {
        $this->clearWhenDisconnected();

        **if ($this->shouldSetup()) {
            $this->setupExchangeAndQueues();
        }**
```

**Possible Solution**  
```
if ($this->shouldSetup() && !in_array($queueName, $this->setupQueues)) {
            $this->setupExchangeAndQueues();
            array_push($this->setupQueues, $queueName);
        }
```

This means $this->setupExchangeAndQueues() will be called only once when starting the consumer instance.

If queue / exchange are deleted while consumer is running
 ```
/**
     * Gets a message from the specified queue.
     *
     * @throws \AMQPException
     */
    public function get(string $queueName): ?\AMQPEnvelope
    {
     ..........
     } catch (\AMQPQueueException $e) {
            if (404 === $e->getCode() && $this->shouldSetup()) {

                 $this->clearWhenDisconnected();
                // If we get a 404 for the queue, it means we need to set up the exchange & queue.
                $this->setupExchangeAndQueues();

                return $this->get($queueName);
            }

            throw $e;
        } 
........
```

**Additional context**  
Not sure if there are any cases when this issue can occur.
This issue is very possible to occur when sending messages also.

### LINKED ISSUE #39605: amqp-transport does auto setup for each get/publish message
**Symfony version(s) affected**: 5.2

**Description**  
The transport `Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection` trying to create and declare queues and exchanges for each publish/get message. I suspect it's not necessary, it is enough to do it only once.

https://github.com/symfony/amqp-messenger/blob/a7f681b022f9cfb88febc12face05b12a47232c1/Transport/Connection.php#L422

**Possible Solution**  
I think it's need to add a flag that the setup already done and do not call it again.

_Sorry for my english._

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #39605, Fix #38092, Fix #32172
| License       | MIT
| Doc PR        | -

To ease the setup, this PR also merge setup of exchange AND delayExchange. 

/cc @Nyholm

### CODE REVIEW

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php [hunk 1]
```diff
@@ -418,18 +423,18 @@ public function get(string $queueName): ?\AMQPEnvelope
...
         try {
             if (false !== $message = $this->queue($queueName)->get()) {
                 return $message;
             }
         } catch (\AMQPQueueException $e) {
-            if (404 === $e->getCode() && $this->shouldSetup()) {
+            if (404 === $e->getCode() && $this->autoSetup) {
                 // If we get a 404 for the queue, it means we need to set up the exchange & queue.
-                $this->setupExchangeAndQueues();
+                $this->setup();
```
Comment (TheHett) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php]: This call looks like unreacheable. 
By this if `autoSetup` was `true` - setup was called at line 427 and `autoSetup` now became `false` yet.

Comment (TheHett) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php]: It might be will be better ro remove this catch ?
~I suspect that it lead to infinity loop and stackoveflowing.~

Comment (jderusse) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php]: > This call looks like unreacheable

hmm.. you're right. This should hav been setup at the beggining of the method

**Comment by chalasr** [comment]
Should also fix #38092 and maybe #32172.

File: src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php [hunk 2]
```diff
@@ -285,7 +285,7 @@ public function testItSetupsTheConnectionWithDefaults()
             $amqpExchange = $this->createMock(\AMQPExchange::class)
         );
 
-        $amqpExchange->expects($this->once())->method('declareExchange');
+        $amqpExchange->expects($this->exactly(2))->method('declareExchange');
```
Comment (TheHett) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php]: Would you explain, why this method call two times?
It would be nice to add an explanation in the code.

File: src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php [hunk 3]
```diff
@@ -463,7 +481,7 @@ public function testAutoSetupWithDelayDeclaresExchangeQueuesAndDelay()
         $amqpQueue->expects($this->once())->method('declareQueue');
 
         $delayExchange->expects($this->once())->method('setName')->with('delays');
-        $delayExchange->expects($this->once())->method('declareExchange');
+        $delayExchange->expects($this->once(2))->method('declareExchange');
```
Comment (TheHett) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php]: `once(2)` looks strange

Comment (jderusse) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php]: good catch

File: src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php (hunk 2 above)
Comment (jderusse) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php]: because the `setup` method declares 2 exchanges

Comment (TheHett) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php]: I saw that the `delayExchage` declares alwas now, even it was not accessed.
maybe it would be better to declare it here https://github.com/symfony/symfony/blob/0db080e9fcdd2e021846280071ef29aa3cbaa372/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php#L364

Comment (jderusse) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php]: This won't work, at this point you wan't know if user disabled `auto_setup`.

I've update the PR to use 2 flags that distinguish autosetup for standard exchange and delayed exchange

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php [hunk 4]
```diff
@@ -347,8 +353,8 @@ private function publishOnExchange(\AMQPExchange $exchange, string $body, string
 
     private function setupDelay(int $delay, ?string $routingKey)
     {
-        if ($this->shouldSetup()) {
-            $this->setup(); // setup delay exchange and normal exchange for delay queue to DLX messages to
+        if ($this->autoSetupDelay) {
+            $this->setupDelayExchange(); // setup delay exchange and normal exchange for delay queue to DLX messages to
```
Comment (jderusse) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php]: ping @Nyholm is it OK? here, I setup ONLY the delay exchange, while previously you setup delayed Exchange +  normal Exchange+Queues, but it looks like this part of the code does not use the standard queues.

Comment (TheHett) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php]: hi,
I think that setup `delayExchange` still not be delayed really.
is it maybe need to call this method `setupDelayExchange` only when we getting delay exchange in this condition https://github.com/symfony/symfony/blob/f4054c1003cf97aef837cf2db5a349a87a5de5bf/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php#L371

Comment (TheHett) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php]: in a normal situation the method `declareExchange` should be called one, I purpose.

Comment (jderusse) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php]: Hmm. I'm not sure to understand what you mean.

Comment (jderusse) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php]: @Nyholm I got my answer thanks to the comment on the same line :)

Comment (TheHett) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php]: > Hmm. I'm not sure to understand what you mean.

Ops, sorry, yesterday I misunderstood the code

**Review by chalasr — APPROVED** [review]
Looks good to me, Thanks

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jderusse.

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php [hunk 5]
```diff
@@ -452,8 +447,11 @@ public function nack(\AMQPEnvelope $message, string $queueName, int $flags = \AM
 
     public function setup(): void
     {
-        $this->setupExchangeAndQueues();
+        if ($this->autoSetupExchange) {
```
Comment (Tobion) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:450]: The setup seems broken now. The setup method is public because it's called by SetupableTransportInterface. Now if you disable auto_setup and want to setup the transports manually, then it does not actually setup the exchanges and queues anymore. But that is the whole point of the setup method: being able to setup manually when autosetup is not used.

Comment (Tobion) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:450]: Fixed in https://github.com/symfony/symfony/pull/40966
