### PR TITLE
[Security] Fix loading user from UserBadge

### LINKED ISSUE #50511: UserLoader Not Called
### Symfony version(s) affected

6.3

### Description

Always using the default userLoader.

AccessTokenHandler:

```
readonly class AccessTokenHandler implements AccessTokenHandlerInterface
{
    public function __construct(private UserRepository $userRepo, private JWT $jwt)
    {
    }

    public function getUserBadgeFrom(#[\SensitiveParameter] string $accessToken): UserBadge
    {
        $userId = $this->decodeJWT($accessToken)['id'];
        $user = $this->userRepo->find($userId);

        return new UserBadge($userId, fn () => $user);
    }
    ....
}
```

### How to reproduce

```
class UserRepository extends ApiServiceEntityRepository implements PasswordUpgraderInterface, UserLoaderInterface
{
    public function loadUserByIdentifier(string|int $identifier): ?User
    {
        $q = $this->createQueryBuilder('q');

        if (is_numeric($identifier)) {
            $q->where('q.phone = :identity')->setParameter('identity', (int) $identifier);
        } else {
            $q->where('q.email = :identity')->setParameter('identity', $identifier);
        }

        return $q->getQuery()->getOneOrNullResult();
    }
    ....
}

```

### Possible Solution

Before:
`
if (null === $userBadge->getUserLoader() && $this->userProvider) {
`

New Code:
https://github.com/vincentchalamon/symfony/blob/99a35f0fc32a7b5250aab5530129bae318c95209/src/Symfony/Component/Security/Http/Authenticator/AccessTokenAuthenticator.php#LL62C35-L62C35

Feature:
https://github.com/symfony/symfony/pull/48272

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by guillaumesmo**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #50511
| License       | MIT
| Doc PR        | none

Fixed a breaking change from https://github.com/symfony/symfony/pull/48272/files#diff-de9707bb338188f62878f2ebd42e7a7bf9547f6d0bf07a4fcd9c386c263c601b

### CODE REVIEW

**Comment by guillaumesmo** [comment]
The fix is less clean than expected because the new OIDC feature relies on this bug.

The Badge user loader used to have priority over the firewall user provider. This was changed so that the OIDC Badge user loader only kicks in when no user provider is set (not sure how, however).

So the priorities are now as follows:
1. Provided user loader in the new Badge constructor
2. Firewall user provider
3. OIDC user loader

Alternative solutions:
- add a configuration to oidc to enable the default user loader
- add a property to UserBadge to indicate the loader must not override the firewall user loader, instead of the callable wrapper

**Comment by nicolas-grekas** [comment]
Can you add a test case please?

@vincentchalamon can you have a look please?

File: src/Symfony/Component/Security/Http/AccessToken/Oidc/OidcTokenHandler.php [hunk 1]
```diff
@@ -93,7 +94,7 @@ public function getUserBadgeFrom(string $accessToken): UserBadge
             }
 
             // UserLoader argument can be overridden by a UserProvider on AccessTokenAuthenticator::authenticate
-            return new UserBadge($claims[$this->claim], fn () => $this->createUser($claims), $claims);
+            return new UserBadge($claims[$this->claim], new FallbackUserLoader(fn () => $this->createUser($claims)), $claims);
```
Comment (vincentchalamon) [inline src/Symfony/Component/Security/Http/AccessToken/Oidc/OidcTokenHandler.php:97]: Might need the same fix on [OidcUserInfoTokenHandler](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Security/Http/AccessToken/Oidc/OidcUserInfoTokenHandler.php)

File: src/Symfony/Component/Security/Http/Authenticator/FallbackUserLoader.php [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+
+/**
+ * This wrapper serves as a marker interface to indicate badge user loaders that should not be overridden by the
+ * default user provider.
+ *
+ * @internal
+ */
+final class FallbackUserLoader
+{
+    public function __construct(private $inner)
```
Comment (vincentchalamon) [inline src/Symfony/Component/Security/Http/Authenticator/FallbackUserLoader.php:24]:
```suggestion
    public function __construct(private callable $inner)
```

File: src/Symfony/Component/Security/Http/Authenticator/FallbackUserLoader.php [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+    {
+    }
+
+    public function __invoke()
```
Comment (vincentchalamon) [inline src/Symfony/Component/Security/Http/Authenticator/FallbackUserLoader.php]:
```suggestion
    public function __invoke(): ?UserInterface
```

**Review by vincentchalamon — CHANGES_REQUESTED** [review]
Nice catch! (and sorry for the bug introduced in my PR)

In addition to my review, can you also add a non-regression functional test on [AccessTokenTest](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Bundle/SecurityBundle/Tests/Functional/AccessTokenTest.php) please?

File: src/Symfony/Component/Security/Http/Authenticator/FallbackUserLoader.php (hunk 2 above)
Comment (derrabus) [reply src/Symfony/Component/Security/Http/Authenticator/FallbackUserLoader.php:24]: That does not work because `callable` must not be used as a property type. `Closure` would work though.

File: src/Symfony/Component/Security/Http/Authenticator/FallbackUserLoader.php [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+    {
+        return ($this->inner)(...\func_get_args());
+    }
```
Comment (derrabus) [inline src/Symfony/Component/Security/Http/Authenticator/FallbackUserLoader.php]:
```suggestion
    public function __invoke(mixed ...$args): mixed
    {
        return ($this->inner)(...$args);
    }
```

**Comment by guillaumesmo** [comment]
Hi all, what can I do to move this PR forward?

**Comment by nicolas-grekas** [comment]
"BC break" is not a proper description when fixing a regression. It doesn't tell which case is solved.
Can you please figure out something a bit more descriptive?

**Comment by guillaumesmo** [comment]
> "BC break" is not a proper description when fixing a regression. It doesn't tell which case is solved. Can you please figure out something a bit more descriptive?

Sure, done

**Review by wouterj — APPROVED** [review]
Looks good to me.

**Comment by fabpot** [comment]
Thank you @guillaumesmo.
