### PR TITLE
[DependencyInjection] Fallback to default value when autowiring undefined parameters for optional arguments

### LINKED ISSUE #50020: Dependency Injection Autowiring throws exception for nullable parameters that don't exist
### Symfony version(s) affected

all?

### Description

I get a ParameterNotFoundException `"You have requested a non-existent parameter "myclass.optional_parameter"` with the below code.

`ExistentClass $requiredToExist` appropriately throws an exception when ExistentClass is not found in the container.
`?NonExistentClass $optionalNotExist` appropriately is set to null when the NonExistentClass is not found in the container.

I have not tested on any version other than 6.2, so I don't know if this bug exists in other versions.

### How to reproduce

```
namespace App\Service;

class MyServiceClass
{
    public function __construct(
        private ExistentClass $requiredToExist,
        private ?NonExistentClass $optionalNotExist = null,
        #[Autowire('%myclass.optional_parameter%')]
        private ?string $optionalParameter = null,
    ) {}

    public function doStuff()
    {
        if ('value1' == $this->optionalParameter) {
            // do something
        } elseif ('value2' == $this->optionalParameter) {
            // do something else
        }
    }
}
```

Register App\Service\MyServiceClass as a service, and request it as a parameter to a controller method.

### Possible Solution

Naive update to the `$attribute instanceof Autowire` case of the [processAttribute method in Symfony/Component/DependencyInjection/Compiler/AutowirePass.php](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L165):

```
try {
    $value = $this->container->getParameterBag()->resolveValue($attribute->value);
    return $value instanceof Reference && $isOptional ? new Reference($value, ContainerInterface::NULL_ON_INVALID_REFERENCE) : $value;
} catch (ParameterNotFoundException $ex) {
    return $isOptional ? null : throw $ex;
}
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by radar3301**
| Q             | A
| ------------- | ---
| Branch?       | 6.2 / 6.3
| Bug fix?      | yes
| New feature?  | yes 
| Deprecations? | no 
| Tickets       | Fix #50020 
| License       | MIT
| Related       | PR #50023

Allows autowiring of undefined nullable parameters, similar to existing behavior for non-parameter values. See related issue for more detail.

### CODE REVIEW

**Comment by radar3301** [comment]
Grr... Tried renaming local patch to https://github.com/radar3301/symfony/tree/autowire-undefined-nullable-6.2

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 1]
```diff
@@ -166,9 +167,12 @@ private function processAttribute(object $attribute, bool $isOptional = false):
     {
         switch (true) {
             case $attribute instanceof Autowire:
-                $value = $this->container->getParameterBag()->resolveValue($attribute->value);
-
-                return $value instanceof Reference && $isOptional ? new Reference($value, ContainerInterface::NULL_ON_INVALID_REFERENCE) : $value;
+                try {
+                    $value = $this->container->getParameterBag()->resolveValue($attribute->value);
+                    return $value instanceof Reference && $isOptional ? new Reference($value, ContainerInterface::NULL_ON_INVALID_REFERENCE) : $value;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: should be outside the try/catch, isn't it?

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 2]
```diff
@@ -166,9 +167,12 @@ private function processAttribute(object $attribute, bool $isOptional = false):
...
+                } catch (ParameterNotFoundException $ex) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: $ex should be renamed to $e

**Review by nicolas-grekas — COMMENTED** [review]
Can you add a test case please?

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php (hunk 1 above)
Comment (radar3301) [reply src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: Sorry, which statement should be outside the try/catch?

Comment (radar3301) [reply src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: Resolved, after thinking about it more.

**Comment by radar3301** [comment]
> Can you add a test case please?

I don't understand any of the test suite stuff...

I'm not even sure that the existing `AutowirePassTest::testAutowireAttribute()` even passes.
I don't see an `AutowireAttribute` class defined in `Symfony/Component/DependencyInjection/Tests/Compiler`, nor does a `use` alias exist for it.
I'm not even sure how `$this->assertCount(9, $definition->getArguments());` on a non-existent class passes...

**Comment by radar3301** [comment]
> non-existent AutowireAttribute class

Nevermind, I found it...

Test cases submitted.

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php [hunk 3]
```diff
@@ -1216,6 +1216,57 @@ public function testAutowireAttribute()
...
+            ->setPublic(true)
+        ;
+
+        (new AutowirePass())->process($container);
+
+        $definition = $container->getDefinition(AutowireAttributeNullFallback::class);
+
+        $this->assertCount(2, $definition->getArguments());
+        $this->assertEquals(new Reference('required.parameter', ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE), $definition->getArgument(0));
+        $this->assertEquals(new Reference('optional.parameter', ContainerInterface::NULL_ON_INVALID_REFERENCE), $definition->getArgument(1));
```
Comment (radar3301) [inline src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php]: Might need to be `$this->assertEquals(null, $definition->getArgument(1));` ?

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php [hunk 4]
```diff
@@ -1216,6 +1216,57 @@ public function testAutowireAttribute()
...
+        
+        $container->setParameter('required.parameter', 'foo');
+        
+        (new AutowirePass())->process($container);
+
+        $definition = $container->getDefinition(AutowireAttributeNullFallback::class);
+
+        $this->assertCount(2, $definition->getArguments());
+        $this->assertEquals(new Reference('required.parameter', ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE), $definition->getArgument(0));
+        $this->assertEquals(new Reference('optional.parameter', ContainerInterface::NULL_ON_INVALID_REFERENCE), $definition->getArgument(1));
```
Comment (radar3301) [inline src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php]: Same as above, might need to be `$this->assertEquals(null, $definition->getArgument(1));` ?

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php (hunk 3 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php]: Likely so, but for now there is this:
Cannot use null as default value for parameter $required of type string in /home/runner/work/symfony/symfony/src/Symfony/Component/DependencyInjection/Tests/Fixtures/includes/autowiring_classes_80.php on line 61

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php]: should be assertNull BTW !

Comment (radar3301) [reply src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php]: Fixed.

**Review by nicolas-grekas — APPROVED** [review]
LGTM (I made some tweaks to the patch)

**Comment by nicolas-grekas** [comment]
Thank you @radar3301.
