### PR TITLE
[Serializer] Prevent `Cannot traverse an already closed generator` error by materializing Traversable input

### LINKED ISSUE #60141: [CsvEncoder] Impossible to use with Traversable
### Symfony version(s) affected

7.2

### Description

CsvEncoder accepts iterator to `encode` function, but it doesn't work properly with Traversable or any non-simple-array iterators

### How to reproduce

```
class Example
{
    public function build()
    {
        $encoder = new CsvEncoder();
        $csv = $encoder->encode($this->getLineIterator(), CsvEncoder::FORMAT);
    }

    private function getLineIterator(): Traversable
    {
        for ($i=0;$i< 1000; $i++) {
            yield [(string) $i];
        }
    }
}

```

I get an exception
`Cannot traverse an already closed generator`

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by santysisi**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60141 
| License       | MIT

### ✅ Pull Request description:
This PR addresses the issue reported in the linked ticket, specifically the error:
`Cannot traverse an already closed generator`

The fix involves converting `Traversable` input into an array using `iterator_to_array($data)`, in order to allow multiple traversals of generator-based inputs.

At first glance, it might seem that this approach significantly increases memory usage, since all generator values are stored in memory. However, this is not the case. In the current logic, the following [loop](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Serializer/Encoder/CsvEncoder.php#L82-L86) already forces all values from the generator into memory:
```php
foreach ($data as &$value) {
    $flattened = [];
    $this->flatten($value, $flattened, $keySeparator, '', $escapeFormulas);
    $value = $flattened;
}
```
Therefore, materializing the generator with `iterator_to_array() `does not increase peak memory usage in any meaningful way.
As an example, here's the comparison of peak memory usage (measured with [memory_get_peak_usage](https://www.php.net/manual/en/function.memory-get-peak-usage.php)) when processing an array of 1 million integers:
* **With the fix**: 90,044,272 bytes
* **Without the fix**: 89,936,680 bytes

The difference is negligible, confirming that the fix does not introduce a meaningful performance cost in terms of memory.

### CODE REVIEW

**Comment by mtarld** [comment]
Hey @santysisi , thanks for this PR!

Indeed I'm a bit worried about the memory usage. Could you give it a try with more complex and filled rows?

At least, I think this behavior should be opt-in (using a context option) to let applications needing to be really memory efficient work properly.

**Comment by santysisi** [comment]
Hi @mtarld , thanks for your comment :smile: ,  I really appreciate it!

I agree with your concern, and I think it's a really good idea. Yes, I can give it a try with more complex and filled row. I’d be happy to do that if you want! 😄
That said, I believe such a refactor should go into the 7.4 branch, since this PR is just a fix. Also, from what I can tell, the current fix doesn’t significantly impact memory usage, but maybe I’m wrong.

File: src/Symfony/Component/Serializer/Tests/Encoder/CsvEncoderTest.php [hunk 1]
```diff
@@ -710,4 +710,16 @@ public function testEndOfLinePassedInConstructor()
...
+    {
+        $this->assertSame("0\n1\n2\n3\n4\n5\n", $this->encoder->encode($this->getLineIterator(), CsvEncoder::FORMAT));
+    }
+
+    private function getLineIterator(): \Generator
+    {
+        for ($i = 1; $i <= 5; ++$i) {
+            yield [(string) $i];
+        }
+    }
```
Comment (GromNaN) [inline src/Symfony/Component/Serializer/Tests/Encoder/CsvEncoderTest.php]: I didn't see your PR before commenting the issue, you can get the test from my comment to be more exhaustive: https://github.com/symfony/symfony/issues/60141#issuecomment-2870057566

File: src/Symfony/Component/Serializer/Encoder/CsvEncoder.php [hunk 2]
```diff
@@ -65,6 +65,12 @@ public function encode(mixed $data, string $format, array $context = []): string
         } elseif (empty($data)) {
             $data = [[]];
         } else {
+            // TODO: Remove this check once PHP 8.2+ is the minimum supported version.
+            // In PHP 8.2, iterator_to_array() accepts iterable, so this instanceof check becomes unnecessary.
```
Comment (GromNaN) [inline src/Symfony/Component/Serializer/Encoder/CsvEncoder.php]: The condition avoids the method call when it's not necessary: you can remove this comment.

**Review by GromNaN — COMMENTED** [review]
LGTM after some minor changes.

> Indeed I'm a bit worried about the memory usage. Could you give it a try with more complex and filled rows?
> At least, I think this behavior should be opt-in (using a context option) to let applications needing to be really memory efficient work properly.

@mtarld the `$data` is iterated recursively multiple times during the encoding, so all the data must be in-memory to find the column names. 
If the iterator is able to re-generate each item on-demand, the memory usage could be lower, but the CPU or network would be more stressed.

File: src/Symfony/Component/Serializer/Tests/Encoder/CsvEncoderTest.php (hunk 1 above)
Comment (santysisi) [reply src/Symfony/Component/Serializer/Tests/Encoder/CsvEncoderTest.php]: Hi :vulcan_salute: , thanks a lot for your comment!
I've made the changes as suggested, i really appreciate the input :heart:.

File: src/Symfony/Component/Serializer/Encoder/CsvEncoder.php (hunk 2 above)
Comment (santysisi) [reply src/Symfony/Component/Serializer/Encoder/CsvEncoder.php]: Hi :vulcan_salute: , thanks a lot for your comment!
I've made the changes as suggested, i really appreciate the input :heart:.

File: src/Symfony/Component/Serializer/Tests/Encoder/CsvEncoderTest.php [hunk 3]
```diff
@@ -710,4 +710,28 @@ public function testEndOfLinePassedInConstructor()
...
+    {
+        $this->assertEquals(<<<'CSV'
+            foo,bar
+            hello,"hey ho"
+            hi,"let's go"
+
+            CSV, $this->encoder->encode($data, 'csv'));
+    }
+
+    public function provideIterable()
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Tests/Encoder/CsvEncoderTest.php]:
```suggestion
    public static function provideIterable(): iterable
```

**Review by mtarld — APPROVED** [review]
@GromNaN, indeed you're right, didn't see about the column names. Then LGTM after a minor suggestion.

**Review by dunglas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @santysisi.
