### PR TITLE
[Serializer] Add support for discriminator map in property normalizer

### LINKED ISSUE #60214: [Serializer] Discriminator is removed when `#[Ignore]` attribute used on unrelated method
### Symfony version(s) affected

7.2.5

### Description

Today I noticed something weird with the Serializer. I have a `LoaderInterface` that defines a discriminator mapping dynamically. This works great.

As soon as I start using the `#[Ignore]` attribute in an unrelated method, the discriminator is no longer added to the serialized result.

I created a small isolated reproducer that explains the problem.

### How to reproduce

```php
<?php

declare(strict_types=1);

use Symfony\Component\PropertyAccess\PropertyAccess;
use Symfony\Component\PropertyInfo\Extractor\PhpStanExtractor;
use Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor;
use Symfony\Component\PropertyInfo\PropertyInfoExtractor;
use Symfony\Component\Serializer\Attribute\Ignore;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Mapping\ClassDiscriminatorFromClassMetadata;
use Symfony\Component\Serializer\Mapping\ClassDiscriminatorMapping;
use Symfony\Component\Serializer\Mapping\ClassMetadataInterface;
use Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory;
use Symfony\Component\Serializer\Mapping\Loader\AttributeLoader;
use Symfony\Component\Serializer\Mapping\Loader\LoaderChain;
use Symfony\Component\Serializer\Mapping\Loader\LoaderInterface;
use Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter;
use Symfony\Component\Serializer\NameConverter\MetadataAwareNameConverter;
use Symfony\Component\Serializer\Normalizer\ArrayDenormalizer;
use Symfony\Component\Serializer\Normalizer\BackedEnumNormalizer;
use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Normalizer\PropertyNormalizer;
use Symfony\Component\Serializer\Normalizer\UnwrappingDenormalizer;
use Symfony\Component\Serializer\Serializer;

include 'vendor/autoload.php';

final class DiscriminatorLoader implements LoaderInterface
{
    #[Override]
    public function loadClassMetadata(ClassMetadataInterface $classMetadata) : bool
    {
        if (!in_array($classMetadata->getName(), [ParentInterface::class, ParentWithIgnoreAttributeInterface::class], true)) {
            return false;
        }

        $classMetadata->setClassDiscriminatorMapping(
            new ClassDiscriminatorMapping(
                'discriminator',
                ['Foo1' => Foo1::class, 'Foo2' => Foo2::class],
            ),
        );

        return true;
    }
}

$loader = new LoaderChain([
    new DiscriminatorLoader(),
    new AttributeLoader(),
]);

$classMetadataFactory = new ClassMetadataFactory($loader);
$propertyAccessor = PropertyAccess::createPropertyAccessor();
$reflectionExtractor = new ReflectionExtractor();
$nameConverter = new MetadataAwareNameConverter($classMetadataFactory, new CamelCaseToSnakeCaseNameConverter());
$propertyTypeExtractor = new PropertyInfoExtractor(
    listExtractors: [$reflectionExtractor],
    typeExtractors: [new PhpStanExtractor(), $reflectionExtractor],
    accessExtractors: [$reflectionExtractor],
    initializableExtractors: [$reflectionExtractor],
);
$classDiscriminatorResolver = new ClassDiscriminatorFromClassMetadata($classMetadataFactory);

$serializer = new Serializer(
    [
        new UnwrappingDenormalizer($propertyAccessor),
        new DateTimeNormalizer(),
        new BackedEnumNormalizer(),
        new PropertyNormalizer(
            $classMetadataFactory,
            $nameConverter,
            $propertyTypeExtractor,
            $classDiscriminatorResolver,
            null,
            [],
        ),
        new ArrayDenormalizer(),
        new ObjectNormalizer(
            $classMetadataFactory,
            $nameConverter,
            $propertyAccessor,
            $propertyTypeExtractor,
            $classDiscriminatorResolver,
        ),
    ],
    [new JsonEncoder()],
);

interface ParentWithIgnoreAttributeInterface
{
    #[Ignore]
    public function getDisplayName() : string;
}

final class Foo1 implements ParentWithIgnoreAttributeInterface
{
    #[Override]
    public function getDisplayName() : string
    {
        return 'Some title';
    }

    public function __construct(
        public int $id,
    ) {
    }
}

// When `#[Ignore]` is used on the `getDisplayName` method in ParentWithIgnoreAttributeInterface, it does not show the discriminator:
// result: {"context":{"id":1}}
dump($serializer->serialize(new Foo1(1), 'json'));

interface ParentInterface
{
    // #[Ignore] commented out
    public function getDisplayName() : string;
}

final class Foo2 implements ParentInterface
{
    #[Override]
    public function getDisplayName() : string
    {
        return 'Some title';
    }

    public function __construct(
        public int $id,
    ) {
    }
}

// When `#[Ignore]` is removed from `getDisplayName` method in ParentInterface, it does show the discriminator:
// result: "{"context":{"discriminator":"Foo2","id":1}}
dump($serializer->serialize(new Foo2(1), 'json'));
```

### Possible Solution

I have the feeling this is related to the `PropertyNormalizer`. When I remove that from the Serializer it works. But since this is a default normalizer, I'd like to keep this. 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ruudk**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #60214
| License       | MIT

Currently it's not possible to serialize an object using the PropertyNormalizer when a DiscriminatorMap attribute is used.

It produces the following error:

> Symfony\Component\Serializer\Exception\NotNormalizableValueException: Type property "type" not found
> for the abstract object "Symfony\Component\Serializer\Tests\Fixtures\DummyMessageInterface".

The ObjectNormalizer overrides the `getAllowedAttributes` from AbstractNormalizer and adds support for discriminators. But the PropertyNormalizer does not do this. Therefore it doesn't work.

For now, we copy the logic from ObjectNormalizer to PropertyNormalizer and the problem goes away.

### CODE REVIEW

**Comment by ruudk** [comment]
@derrabus You're probably very busy, but I'm really curious to hear your feedback on this 😊

**Comment by ruudk** [comment]
@mtarld @nicolas-grekas Friendly ping to pick your brain on this topic, since you worked on the discriminator mapping in #52681. I'm curious to hear if my approach makes sense, or that I should investigate time in finding an alternative solution. Any advice is much appreciated, thanks 😊

File: src/Symfony/Component/Serializer/Tests/Fixtures/DummyMessageNumberFour.php [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+    #[Ignore]
+    public function getDescription()
+    {
+        return 'Hello, World!';
+    }
+}
+
+/**
+ * @author Samuel Roze <samuel.roze@gmail.com>
+ */
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Tests/Fixtures/DummyMessageNumberFour.php]: Can be removed :slightly_smiling_face:

File: src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php [hunk 2]
```diff
@@ -221,4 +222,28 @@ private function getReflectionProperty(string|object $classOrObject, string $att
             }
         }
     }
+
+    protected function getAllowedAttributes(string|object $classOrObject, array $context, bool $attributesAsString = false): array|bool
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php]: Maybe it worth adding this method in `AbstractObjectNormalizer` instead?

File: src/Symfony/Component/Serializer/Tests/SerializerTest.php [hunk 3]
```diff
@@ -504,6 +505,29 @@ public function testDeserializeAndSerializeNestedAbstractAndInterfacedObjectsWit
         $this->assertEquals($example, $deserialized);
     }
 
+    public function testDeserializeAndSerializeConstructorAndIgnoreAndInterfacedObjectsWithTheClassMetadataDiscriminator()
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Tests/SerializerTest.php]: What about a test in `PropertyNormalizerTest` (or maybe `AbstractObjectNormalizerTest`)?

File: src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php (hunk 2 above)
Comment (ruudk) [reply src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php]: That already exists there, so if we modify the existing one, it will be a BC break.

File: src/Symfony/Component/Serializer/Tests/SerializerTest.php (hunk 3 above)
Comment (ruudk) [reply src/Symfony/Component/Serializer/Tests/SerializerTest.php]: Good idea, I moved the test to PropertyNormalizerTest instead.

File: src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php (hunk 2 above)
Comment (mtarld) [reply src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php]: AFAIK, `AbstractObjectNormalizer::getAllowedAttributes` is not implemented, no?

So if we implement it, all the children will be fixed (`PropertyNormalizer`, `ObjectNormalizer`, and `GetSetNormalizer`). And we'll be able to remove `ObjectNormalizer::getAllowedAttributes` as well (if it's the very same code).

Comment (ruudk) [reply src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php]: You're right. I did not see you mentioned Abstract**Object**Normalizer.

I moved the method. But I'm still worried it's a BC issue as `AbstractObjectNormalizer` now changes behavior without it being marked as internal.

Comment (ruudk) [reply src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php]: It's exactly the same code indeed.

Comment (ruudk) [reply src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php]: @mtarld I made the change. I like this approach better, but as I said I'm worried it might be a BC issue. @nicolas-grekas Do you think this is fine?

File: src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php [hunk 4]
```diff
@@ -13,6 +13,7 @@
 
 use Symfony\Component\PropertyAccess\Exception\UninitializedPropertyException;
 use Symfony\Component\PropertyInfo\PropertyTypeExtractorInterface;
+use Symfony\Component\Serializer\Mapping\AttributeMetadata;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php]: should be reverted

**Review by nicolas-grekas — APPROVED** [review]
Works for me. BC is not affected since no API changes. The behavior change is the bug fix so no regression either to me.

File: src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php (hunk 4 above)
Comment (ruudk) [reply src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php]: Removed.

File: src/Symfony/Component/Serializer/Tests/Normalizer/PropertyNormalizerTest.php [hunk 5]
```diff
@@ -516,6 +518,25 @@ public function testDenormalizeWithDiscriminator()
 
         $this->assertEquals($denormalized, $normalizer->denormalize(['type' => 'two', 'url' => 'url'], PropertyDummyInterface::class));
     }
+
+    public function testDeserializeAndSerializeConstructorAndIgnoreAndInterfacedObjectsWithTheClassMetadataDiscriminator()
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Tests/Normalizer/PropertyNormalizerTest.php]: Might be under `AbstractObjectNormalizerTest`.

**Review by mtarld — APPROVED** [review]
One last thing, otherwise, LGTM!

File: src/Symfony/Component/Serializer/Tests/Normalizer/PropertyNormalizerTest.php (hunk 5 above)
Comment (ruudk) [reply src/Symfony/Component/Serializer/Tests/Normalizer/PropertyNormalizerTest.php]: Done!

**Comment by ruudk** [comment]
Thanks for the help @mtarld and @nicolas-grekas 🎉 

The failing test is unrelated to these changes.

**Comment by nicolas-grekas** [comment]
Thank you @ruudk.

**Comment by VitekSkrip** [comment]
Hi @nicolas-grekas 

I probably got similar problem at symfony 7.1.5

Test Case:

```
<?php

declare(strict_types=1);

namespace App\Test;

use Symfony\Component\Serializer\Attribute\DiscriminatorMap;
use Symfony\Component\Serializer\Attribute\Ignore;

#[DiscriminatorMap(
    typeProperty: 'type',
    mapping: [
        'base_payload' => BasePayload::class,
        'new_payload' => ExamplePayload::class,
    ],
)]
readonly class BasePayload
{
    public function __construct(
        protected string $a,
    ) {
    }

    public function getA(): string
    {
        return $this->a;
    }

    #[Ignore]
    public function isAString(): bool
    {
        return is_string($this->a);
    }

}

<?php

declare(strict_types=1);

namespace App\Test;

final readonly class ExamplePayload extends BasePayload
{
    public function __construct(
        string $a,
        protected string $b,
    ) {
        parent::__construct($a);
    }

    public function getB(): string
    {
        return $this->b;
    }
}

```

Runs this:
$payload = new BasePayload('string');

$serialized = $this->serializer->serialize($payload, 'json');
        
        I got 
image


But then i drop Ignore attribute - it passes!!

{"type":"base_payload","a":"string","aString":true}

**Comment by nicolas-grekas** [comment]
@VitekSkrip please give this PR a try and create a new issue if it doesn't fix it for you then.

**Comment by VitekSkrip** [comment]
> @VitekSkrip please give this PR a try and create a new issue if it doesn't fix it for you then.

what version of symfony or symfony/serializer should i use then?

**Comment by ruudk** [comment]
@VitekSkrip This was just merged to 6.4.x.dev. It will take some time before it is merged to 7.2 and 7.3. Since you are on 7.1 you won't get it, unless you upgrade.

**Comment by nafetsrybak** [comment]
Hi, when will it be available in the rest of the versions? For example, ^7.4?
