### PR TITLE
[PhpUnitBridge] Improve dirname usage

### LINKED ISSUE #36499: phpunit-bridge breaks with phpunit 9.1.2
Hi,

Since phpunit 9.1.2, the bridge fails with this error:

```
PHP Fatal error:  Uncaught Error: Access to undeclared static property: PHPUnit\Util\Blacklist::$blacklistedClassNames in /dir/bin/.phpunit/phpunit-9.1-0/phpunit:13
Stack trace:
#0 /dir/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php(343): include()
#1 /dir/bin/phpunit(13): require('/home/jmsche/Si...')
#2 {main}
  thrown in /dir/bin/.phpunit/phpunit-9.1-0/phpunit on line 13
```

After a little research, I found the commit that breaks it: https://github.com/sebastianbergmann/phpunit/commit/2b4d7b8bb3fd052095e64999990cc36b63aa0771

So phpunit switches from a public static var to a private constant.

### PR DESCRIPTION
**Pull request by Jean85**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36499
| License       | MIT

This is a very small performance improvement on top of #36539

### CODE REVIEW

File: src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php [hunk 1]
```diff
@@ -49,7 +49,7 @@ public function __construct(array $mockedNamespaces = array())
             \PHPUnit_Util_Blacklist::$blacklistedClassNames[__CLASS__] = 2;
         } elseif (method_exists(Blacklist::class, 'addDirectory')) {
             (new BlackList())->getBlacklistedDirectories();
-            Blacklist::addDirectory(\dirname(\dirname((new \ReflectionClass(__CLASS__))->getFileName())));
+            Blacklist::addDirectory(\dirname((new \ReflectionClass(__CLASS__))->getFileName(), 2));
```
Comment (javiereguiluz) [inline src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php:52]: Could we really use this? The second argument of `dirname()` was added in PHP 7.0.0 (https://www.php.net/dirname) and Symfony 3.4 requires PHP 5.5. (https://github.com/symfony/symfony/blob/3.4/composer.json).

Comment (Jean85) [reply src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php:52]: If the namespaced class exists and that method too, as we're sure in this if branch, that means that we're on PHPUnit >9.1.2, so we're on PHP 7.2 at least.

Comment (javiereguiluz) [reply src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php:52]: Cool. Then this is fine! Thanks!

**Review by nicolas-grekas — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Jean85.
