### PR TITLE
[DoctrineBridge] don't call `EntityManager::initializeObject()` with scalar values

### LINKED ISSUE #58906: UniqueEntityValidator not working on DTOs on doctrine/orm >=3.3.0
### Symfony version(s) affected

7.1.x

### Description

when using the UniqueEntity constraint on a dto, as explained here https://symfony.com/blog/new-in-symfony-7-1-expanding-uniqueentity-constraint-to-any-php-class  i get

```
Doctrine\\ORM\\EntityManager::initializeObject(): Argument #1 ($obj) must be of type object, int given, called in \/home\/vagrant\/code\/my-project\/vendor\/symfony\/doctrine-bridge\/Validator\/Constraints\/UniqueEntityValidator.php on line 113
```
it happens on doctrine/orm >=3.3.0 
on doctrine/orm 2.X it does not happen even if the same line of code is executed.

### How to reproduce
```
#[Immutable]
#[UniqueEntity(fields: ['name', 'relatedId' => 'relation'], entityClass: MyEntity::class)]
class MyDto
{
    /**
     * @param positive-int          $relatedId
     * @param non-empty-string      $name
     * @param non-empty-string|null $description
     * @param non-empty-string      $date
     */
    public function __construct(
        #[Assert\Positive]
        public readonly int     $relatedId,

        public readonly string  $name,

        public readonly ?string $description,

        #[Assert\Date]
        public readonly string  $date,
    ) {
    }
}
```

entities
```
#[ORM\Entity]
class MyEntity
{
    #[ORM\ManyToOne(targetEntity: RelatedEntity::class)]
    protected RelatedEntity $related;
}

#[ORM\Entity]
class RelatedEntity
{
    #[ORM\OneToMany(targetEntity: RelatedEntity::class)]
    protected array $myEntities;
}
```
then just use a validator to validate an object of MyDto

### Possible Solution

_No response_

### Additional Context

with the following object
```
{
	"name": "my-name",
	"description": "desc",
	"date": "2027-02-02",
	"relatedId": 2
}
```

the error happens at
```$em->initializeObject($criteria[$fieldName]);```
where 
```
$fieldName = 'relatedId';
$criteria = ['name' => 'my-name', 'relatedId' => 2];
```

so

```$em->initializeObject($criteria[$fieldName]); -> $em->initializeObject(2);```

and 2 is not an object indeed.

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58906
| License       | MIT

Calling `initializeObject()` with a scalar value (e.g. the id of the associated entity) was a no-op call with Doctrine ORM 2 where no type was set with the method signature. The `UnitOfWork` which was called with the given argument ignored anything that was not an `InternalProxy` or a `PersistentCollection` instance.

Calls like these now break with Doctrine ORM 3 as the method's argument is typed as object now.

### CODE REVIEW

**Review by alexandre-daubois — APPROVED** [review]

File: src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php [hunk 1]
```diff
@@ -104,7 +104,7 @@ public function validate($entity, Constraint $constraint)
 
             $criteria[$fieldName] = $fieldValue;
 
-            if (null !== $criteria[$fieldName] && $class->hasAssociation($fieldName)) {
+            if (null !== $criteria[$fieldName] && is_object($criteria[$fieldName]) && $class->hasAssociation($fieldName)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php]:
```suggestion
            if (\is_object($criteria[$fieldName]) && $class->hasAssociation($fieldName)) {
```

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.
