### PR TITLE
[Messenger] Allow SQS to handle its own retry/DLQ

### LINKED ISSUE #45104: Symfony SQS Transport not compatible with SQS-DLQs
### Symfony version(s) affected

5.4.*

### Description + Reproduction

Given the following system:
 * 1: A SQS queue that will be configured as a Dead-Letter-Queue
 * 2: A SQS queue that a symfony consumer should consume from, configured with 1) as DLQ 
 * 3: A symfony transport consumer configured to read from the queue from 2. It's AWS permissions are the minimal permissions of a queue consumer:

```
{
            "Effect": "Allow",
            "Action": [
                "sqs:ReceiveMessage",
                "sqs:ChangeMessageVisibility",
                "sqs:GetQueueUrl",
                "sqs:DeleteMessage",
                "sqs:GetQueueAttributes"
            ],
            "Resource": "arn:aws:sqs:eu-central-1:1111111111:foobarqueue"
        }
   
```

If I have a message that causes an exception to be thrown on the consumer and can't be processed, according to AWS docs, the consumer should not call `DeleteMessage`, but instead simply leave the message in the queue. After a configured VisibilityTimeout (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html) the message will be made visible again and the consumer will try to process it again. This will happen for as long until the configured maximum amount of receives is reached and then the message is moved to the DLQ.

Symfony's consumer behaviour breaks with this assumption by orchestrating the retry logic on the consumer side, which isn't great in multiple ways:
 * A: The consumer also needs to be able to send messages into the queue.
 * B: it breaks with the idea of SQS DLQs as the receives of the message in SQS won't increase.
 * C: If the consumer can't send the message for any reason (permissions, errors, networking issues, process crashes etc.) the message might be lost.
 
I am wondering if the transport implementation can be configured in a way that makes it compatible again with what the expected usage of SQS is, so that DLQs will work properly again. If not, how does the implementation need to change to make the symfony consumer behaviour compatible with SQS DLQs again?
Could there be an Exception type that would cause the message to simply not be deleted and re-added to the queue so that we'll fall back to SQS' model of retries?

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by maxbaldanza**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #45104
| License       | MIT

As mentioned on the linked issue this has a number of benefits but mainly

* The consumer no longer needs to be able to send messages into the queue.
* Less chance of message loss

Allow SQS to handle retries rather then handling this by Symfony.
This allows applications to use the retry strategy from SQS rather then Symfony.
The default is for the message to be deleted from SQS at which point Symfony
will handle the retry by then adding back in to the queue.
If `delete_on_rejection` is set to `false` instead it will change the message
visibility of the message on SQS and thus SQS to handle the retry mechanism

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html

### CODE REVIEW

File: src/Symfony/Component/Messenger/Bridge/AmazonSqs/Transport/Connection.php [hunk 1]
```diff
@@ -101,6 +102,7 @@ public function __destruct()
      * * wait_time: long polling duration in seconds (Default: 20)
      * * poll_timeout: amount of seconds the transport should wait for new message
      * * visibility_timeout: amount of seconds the message won't be visible
+     * * delete_on_rejection: Whether to delete message on rejection or allow SQS to handle retries. (Default: true). If set to false then the `retry_strategy` should be set to `max_retries: 0`
```
Comment (maxbaldanza) [inline src/Symfony/Component/Messenger/Bridge/AmazonSqs/Transport/Connection.php]: Ideally we should throw an error if setting `delete_on_rejection` and the `retry_strategy` doesn't have `max_retries` set as `0` as this option should only be used if SQS is fully responsible for the retries/DLQ but we don't have access to that so was hoping documentation is enough to cover that.

Would love to hear thoughts here

**Comment by maxbaldanza** [comment]
> Hey!
> 
> Thanks for your PR. You are targeting branch "7.4" but it seems your PR description refers to branch "7.4 for features". Could you update the PR description or change target branch? This helps core maintainers a lot.
> 
> Cheers!
> 
> Carsonbot

Thanks Carsonbot I fixed the mistake

File: src/Symfony/Component/Messenger/Bridge/AmazonSqs/Transport/Connection.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Bridge/AmazonSqs/Transport/Connection.php]: why should it be set to `0`? what happens if that's not set as documented?

Comment (maxbaldanza) [reply src/Symfony/Component/Messenger/Bridge/AmazonSqs/Transport/Connection.php]: You'd end up with a duplicate message in SQS. 
When the message is rejected we'd change the visibility of the message meaning it will reappear in the queue after the timeout period but then the `SendFailedMessageForRetryListener` would then also resend the message back to SQS meaning you'd end up with 2 of the same messages in SQS.

If the transports had access to the retry strategy then an exception could be thrown if this configuration was setup but I didn't want to introduce adding the retry strategy to transports before first making sure that was the route to take. You may also have a better way to solve that

Comment (deguif) [reply src/Symfony/Component/Messenger/Bridge/AmazonSqs/Transport/Connection.php]: setting `max_retries` to `0` won't disable resending another message to the queue as `RecoverableExceptionInterface` and some other cases are always retried even if `max_retries` is 0 or reached its max.

Comment (maxbaldanza) [reply src/Symfony/Component/Messenger/Bridge/AmazonSqs/Transport/Connection.php]: Yes your right @deguif, thanks for pointing that out 🙌 

I've just pushed a change that should solve that, instead now the transport checks if the message is being resent using the `RedeliveryStamp` and if so we don't send it to the sender. 

Let me know what you think

**Review by stanislav-erokhin — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @maxbaldanza.
