### PR TITLE
 Keep body size limit for AMP redirects

### LINKED ISSUE #62314: AmpHttpClient resets body size limit on redirect
### Symfony version(s) affected

7.3.4

### Description

AMP's default body size limit of 10 MiB is disabled when making a request: https://github.com/symfony/http-client/blob/439032bdff3a5bd07f4e68ef6a93b51bb477400f/AmpHttpClient.php#L128

However, when a redirect happens a new request is created that does _not_ disable this limit: https://github.com/symfony/http-client/blob/439032bdff3a5bd07f4e68ef6a93b51bb477400f/Response/AmpResponseV5.php#L325

This means that a > 10 MiB page/file that requires a redirect will not finish downloading.

### How to reproduce

A real life example of a file that will not download with a fresh client is https://github.com/sapics/ip-location-db/raw/main/geolite2-city/geolite2-city-ipv4-num.csv.gz. Code to reproduce:

```php
$client = new AmpHttpClient();
$response = $client->request('https://github.com/sapics/ip-location-db/raw/main/geolite2-city/geolite2-city-ipv4-num.csv.gz');
$response->getContent(); // warning/exception
```

### Possible Solution

https://github.com/symfony/symfony/pull/62315

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by villermen**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no 
| Issues        | Fix #62314
| License       | MIT

Copies over body size limit when following redirects in `AmpHttpClient`. See https://github.com/symfony/symfony/issues/62314

### CODE REVIEW

**Comment by stof** [comment]
The fix looks good to me, but we need to apply it in the 6.4 branch as that branch already disables the body size limit.

**Comment by villermen** [comment]
@stof Thanks for the pointer. I changed the base to 6.4 now. Note that this version still included just the one version of `AmpResponse`. Should I open a second PR to apply it to the split `AmpResponseV4` and `AmpResponseV5` in 7.3 as well?

**Comment by stof** [comment]
yes please.

Edit: might not be worth it depending on how the merge-up will go.

**Review by stof — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @villermen.

File: src/Symfony/Component/HttpClient/Response/AmpResponse.php [hunk 1]
```diff
@@ -329,6 +329,7 @@ private static function followRedirects(Request $originRequest, AmpClientState $
             $request->setTcpConnectTimeout($originRequest->getTcpConnectTimeout());
             $request->setTlsHandshakeTimeout($originRequest->getTlsHandshakeTimeout());
             $request->setTransferTimeout($originRequest->getTransferTimeout());
+            $request->setBodySizeLimit($originRequest->getBodySizeLimit());
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/Response/AmpResponse.php:332]: FTR I changed it this way after merging:
```diff
-            $request->setBodySizeLimit($originRequest->getBodySizeLimit());
+            $request->setBodySizeLimit(0);
+            if (method_exists($request, 'setInactivityTimeout')) {
+                $request->setInactivityTimeout(0);
+            }
```

**Comment by nicolas-grekas** [comment]
Now merged into 7.3
