### PR TITLE
[Validator] new email validation option to match with w3c official specification

### LINKED ISSUE #47712: [Validator] EmailValidator in html5 mode does not match actual html validator
### Symfony version(s) affected

6.1.4, but actually every version since html5 mode introduction

### Description

There is a small mismatch between the html5 regex in symfony/validator and the example regex listed on MDN (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email#basic_validation) or whatwg (https://html.spec.whatwg.org/dev/input.html#email-state-(type=email)).

https://github.com/symfony/validator/blob/14ec426b9c8ca8cf02bd863a645fb0cc0d73db79/Constraints/EmailValidator.php#L27

It's only the last quantifier. While MDN and whatwg both use an asterisk (*) as last quantifier, the EmailValidator uses a plus (+).
This causes html to allow email addresses without a tld, while the EmailValidator disallows them.

### How to reproduce

Just compare the tests of both regexes:
https://3v4l.org/aRdqA#v8.1.10

The mdn regex allowed email addresses without a tld, such as "test@localhost". The one in the EmailValidator disallows them.

### Possible Solution

Since email addresses with a tld-less domain are actually valid, I propose to update the regex for the html5 validator.

I have not created a PR yet, but might create one. Reasoning for not creating it yet is, I'm unsure about the target version.
In my opinion this would be a bugfix, but it's also a breaking change, since it would allow email addresses which were disallowed until now.
Also I would propose to allow domains without tld for loose mode, but I'd like to discuss that first.

So my questions are:
Which branch should a PR target?
Is anyone against allowing tld-less domains when using "loose" mode?

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by guillemfondin**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #47712
| License       | MIT
| Doc PR        | symfony/symfony-docs#17360

## WHAT
Email validator no matches with w3c official specication (that allow no tld) see #47712 for details.

## WHY
In general, for public common usage, developers may not need to give users this liberty. 
Except for specific use case, (internal email for eg) in companies...

## HOW
Add an option for accept tld (already exist `Email::VALIDATION_MODE_HTML5`) or not (official spec `Email::VALIDATION_MODE_HTML5_ALLOW_NO_TLD`)

### CODE REVIEW

**Comment by maxbeckers** [comment]
@guillemfondin could you please add some unit tests for the change.

**Comment by guillemfondin** [comment]
@maxbeckers Of course :)

**Review by nicolas-grekas — COMMENTED** [review]
This approach makes sense to me. Accepting emails with no TLD by default would likely make more bad than good in practice. We'd better allow this in an opt-in way. The alternative could be to just do nothing BTW. The motivation for changes in Symfony should be based on real-world use cases.

File: src/Symfony/Component/Validator/Constraints/Email.php [hunk 1]
```diff
@@ -18,13 +18,15 @@
...
  * @Annotation
+ *
  * @Target({"PROPERTY", "METHOD", "ANNOTATION"})
  *
  * @author Bernhard Schussek <bschussek@gmail.com>
  */
 #[\Attribute(\Attribute::TARGET_PROPERTY | \Attribute::TARGET_METHOD | \Attribute::IS_REPEATABLE)]
 class Email extends Constraint
 {
+    public const VALIDATION_MODE_HTML5_ALLOW_NO_TLD = 'no-tld';
```
Comment (stof) [inline src/Symfony/Component/Validator/Constraints/Email.php]: I would change the value of the constant. The current value makes it looks like it forbids having a TLD (which is not what it does)

Comment (guillemfondin) [reply src/Symfony/Component/Validator/Constraints/Email.php]: Do you prefer `allow-no-tld` ?

**Comment by Sajito** [comment]
Weird having discussion in two seperate places, thanks @guillemfondin for notifying me :)

Personally I feel a bit uncomfortable with this change. Not because I need the ability to allow emails without a tld, actually I don't have an use-case for this feature. I have filed the issue only because during some tests I got to the point, where the browser validator said the email is fine, while the backend validator said it's invalid and that made me curious.

Having a validator, which claims it does the same check as the browser and is also named to represent this, but actually having a difference is weird. It get's even more weird, when the html5 mode (named after the html5 validator), does something different than the actual html5 validator and the "real" html5 validator has a name not even related to html5.

I'd say the naming should move to something like "html5" and "html5-force-tld". The only issue is the BC implication.
But changing this really feels hacky and I can understand, if that's not the way to go. I've pushed my proposal into my fork, just to make them visible. [Commit is here](https://github.com/Sajito/symfony/commit/fef5b082b7d165006814fb3bdecccab67a7f0f5e).
Alternatively this new mode should make clear it's actually html5. Maybe `strict-html5` or something like that.

File: src/Symfony/Component/Validator/CHANGELOG.md [hunk 2]
```diff
@@ -4,6 +4,7 @@ CHANGELOG
 6.2
 ---
 
+ * Add option `Email::VALIDATION_MODE_HTML5_ALLOW_NO_TLD` with "allow-no-tld" e-mail validation mode, to match with the w3c official specification
```
Comment (PhilETaylor) [inline src/Symfony/Component/Validator/CHANGELOG.md]:
```suggestion
 * Add option `Email::VALIDATION_MODE_HTML5_ALLOW_NO_TLD` with "allow-no-tld" e-mail validation mode, to match with the W3C official specification
```

File: src/Symfony/Component/Validator/Constraints/Email.php [hunk 3]
```diff
@@ -18,13 +18,15 @@
 
 /**
  * @Annotation
+ *
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraints/Email.php]: please revert this as it's unrelated

File: src/Symfony/Component/Validator/Constraints/Email.php [hunk 4]
```diff
@@ -18,13 +18,15 @@
...
  * @Target({"PROPERTY", "METHOD", "ANNOTATION"})
  *
  * @author Bernhard Schussek <bschussek@gmail.com>
  */
 #[\Attribute(\Attribute::TARGET_PROPERTY | \Attribute::TARGET_METHOD | \Attribute::IS_REPEATABLE)]
 class Email extends Constraint
 {
+    public const VALIDATION_MODE_HTML5_ALLOW_NO_TLD = 'allow-no-tld';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraints/Email.php]: html5-allow-no-tld

File: src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php [hunk 5]
```diff
@@ -84,6 +84,7 @@ public function getValidEmails()
 
     /**
      * @group legacy
+     *
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php]: please revert all added blank lines

File: src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php [hunk 6]
```diff
@@ -125,6 +126,7 @@ public function getValidEmailsWithWhitespaces()
...
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php]: drop

File: src/Symfony/Component/Validator/Constraints/Email.php (hunk 3 above)
Comment (guillemfondin) [reply src/Symfony/Component/Validator/Constraints/Email.php]: Suggested by fabbot in CI... If I remove, fabbot will failed, is it an issue ?

File: src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php (hunk 5 above)
Comment (guillemfondin) [reply src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php]: Same, fabbot

File: src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php (hunk 6 above)
Comment (guillemfondin) [reply src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php]: Same, fabbot

Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php]: let's ignore fabbot on this one

**Review by welcoMattic — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]
I think this approach makes sense.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @guillemfondin.
