### PR TITLE
[Security] Add an easier way to get the current firewall configuration

### LINKED ISSUE #46015: [Security] Add an easier way to get the current firewall name
### Description

Depending on the used firewall I want to implement some logic. Currently there is no good way to get the current name of the firewall. 

The firewall listener does set a attribute called `_firewall_context` which is for example firewall name `extranet` something like `security.firewall.map.context.extranet` so it would be something like `if  (str_ends_with(...` check which feels very strange.

Also in my case the `_firewall_context` attribute is not set at the time I need to register mycustom listener. I need to control a custom `$request->attribute` depending on the firewall name before the `UserProvider` is called. It seems the listener which calls the UserProvider and is setting the `_firewall_context` is the same. So no way to inject between.

The current workaround here I found:

 - https://stackoverflow.com/questions/67794325/how-to-get-firewall-name-from-request-in-symfony-5

This requires to inject the `FirewallMap` and call a method which is not part of the `FirewallMapInterface` and so can make problems if is somebody would decorate that service (logger).

What would be the expected behaviour. I think the best would be have first a listener which would set the a `_firewall_name` attribute on the `$request` object. With a higher priority then the `FirewallListener` itself. So somebody can create a listener between matching of the firewall and calling firewall specific logic (userprovider, login, logout, ...).

Another way would providing an additoinal method on the [`Security`](https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Security/Core/Security.php) service to return the current `FirewallName`.

### Example

<details>
<summary>Custom Listener</summary>

This shows the following example of such a listener

```php
<?php

declare(strict_types=1);

namespace App\Access\Infrastructure\Sulu\Security;

use App\Access\Infrastructure\Sulu\Admin\ExtranetAdmin;
use Sulu\Bundle\SecurityBundle\System\SystemStoreInterface;
use Symfony\Bundle\SecurityBundle\Security\FirewallMap;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\Security\Http\FirewallMapInterface;

class SecuritySystemSubscriber implements EventSubscriberInterface
{
    private FirewallMap $map;

    private SystemStoreInterface $systemStore;

    public function __construct(
        SystemStoreInterface $systemStore,
        FirewallMapInterface $map,
    ) {
        $this->systemStore = $systemStore;

        if (!$map instanceof FirewallMap) {
            throw new \LogicException(\sprintf('Expected "%s" but got "%s".', FirewallMap::class, \get_class($map)));
        }

        $this->map = $map;
    }

    public static function getSubscribedEvents(): array
    {
        return [
            KernelEvents::REQUEST => [
                // need to be after @see \Sulu\Bundle\SecurityBundle\EventListener\SystemListener::getSubscribedEvents
                // need to be before @see \Symfony\Bundle\SecurityBundle\EventListener\FirewallListener::getSubscribedEvents
                ['processSecuritySystem', 9],
            ],
        ];
    }

    public function processSecuritySystem(RequestEvent $event): void
    {
        if (!$event->isMainRequest()) {
            return;
        }

        // this is strange as it is not part of the FirewallMapInterface
        $config = $this->map->getFirewallConfig($event->getRequest());
        if (!$config) {
            return;
        }

        if ('extranet' === $config->getName()) {
            $this->systemStore->setSystem(ExtranetAdmin::SYSTEM);
        }
    }
}
```

</details>

### PR DESCRIPTION
**Pull request by Kocal**
| Q             | A
| ------------- | ---
| Branch?       | 6.1 
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Tickets       | Fix #46015 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Added a new method `Security#getFirewallConfig($request)` to easily get the firewall configuration associated to the `Request`.

The firewall name can be accessed through `$security->getFirewallConfig($request)?->getName()`.

### CODE REVIEW

File: src/Symfony/Component/Security/Core/Security.php [hunk 1]
```diff
@@ -57,4 +59,9 @@ public function getToken(): ?TokenInterface
     {
         return $this->container->get('security.token_storage')->getToken();
     }
+
+    public function getFirewallConfig(Request $request): ?FirewallConfig
+    {
+        return $this->container->get('security.firewall.map')->getFirewallConfig($request);
```
Comment (chalasr) [inline src/Symfony/Component/Security/Core/Security.php]: The `security.helper` service definition needs to be updated for this service to be available

File: src/Symfony/Component/Security/Core/CHANGELOG.md [hunk 2]
```diff
@@ -1,6 +1,12 @@
 CHANGELOG
 =========
 
+6.1
```
Comment (chalasr) [inline src/Symfony/Component/Security/Core/CHANGELOG.md]: 6.1 is feature-frozen
```suggestion
6.2
```

File: src/Symfony/Component/Security/Core/Security.php (hunk 1 above)
Comment (Kocal) [reply src/Symfony/Component/Security/Core/Security.php]: Fixed, thanks! I've also added tests.

File: src/Symfony/Component/Security/Core/CHANGELOG.md (hunk 2 above)
Comment (Kocal) [reply src/Symfony/Component/Security/Core/CHANGELOG.md]: Updated, thanks.

**Comment by Kocal** [comment]
What's the best way to make the low-deps check passing?

**Comment by wouterj** [comment]
> What's the best way to make the low-deps check passing?

By requiring `^6.2` in the composer.json (or skipping the test on lower versions).

However, this does signal the design flaw of the current implementation (which is a flaw with the `Security` class as a whole, but highlighted more by this change): We now have a class in `Security\Core` that depends on a `FirewallMap` and `FirewallConfig` class from `SecurityBundle`, which depend on a `FirewallMap` from `Security\Http`. Imho, that sadly is a no go, so :-1: for the moment.

Please note that this is purely a -1 for the implementation, I think the DX problem highlighted in the issue is worth fixing.

@chalasr this is the second time we have a nice DX improvement that introduces lots of coupling through the `Security` helper class (ref https://github.com/symfony/symfony/pull/41274#issuecomment-1046967394). What do you think about deprecating this helper class in `Security\Core` and moving it completely to the SecurityBundle? That directly resolves coupling issues, and only reduces DX for standalone users (all methods in the class are little helpers to retrieve information more easily, none add missing functionality), which - to be honest - already suffer from a bad DX. And given the currently coupling to SecurityBundle service names in the class, I don't expect standalone users are using the class at the moment.

**Comment by Kocal** [comment]
Having the `Security` class in the `SecurityBundle` makes more sense to me, I was dubitative when working on the feature.

**Comment by chalasr** [comment]
Big 👍 for moving the helper to SecurityBundle.

**Comment by wouterj** [comment]
The merge tool was a bit trigger happy closing this PR when #46094 got merged, reopening.

@Kocal do you have time to rebash and finish this PR for 6.2, now the helper is moved to the security bundle?

**Comment by Kocal** [comment]
I'm glad that #46094 has been merged, nice work @chalasr :) 

@wouterj the PR has been rebased and modified in consequence.

File: src/Symfony/Bundle/SecurityBundle/Security/Security.php [hunk 3]
```diff
@@ -25,4 +26,9 @@ public function __construct(ContainerInterface $container)
     {
```
Comment (wouterj) [inline src/Symfony/Bundle/SecurityBundle/Security/Security.php:26]: If we make the constructor `__construct(private ContainerInterface $container)`, we can get rid of the protected `getContainer()` method (which is there only to communicate with the BC layer).

**Review by wouterj — APPROVED** [review]
I like it, thanks @Kocal!

File: src/Symfony/Bundle/SecurityBundle/Security/Security.php (hunk 3 above)
Comment (Kocal) [reply src/Symfony/Bundle/SecurityBundle/Security/Security.php:26]: Yeah I wasn't sure about adding a new field, I've updated the code.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Kocal.

**Comment by alexander-schranz** [comment]
@Kocal Nice work. Thx for implementing this 👍

File: src/Symfony/Bundle/SecurityBundle/Tests/Security/SecurityTest.php [hunk 4]
```diff
@@ -82,6 +85,32 @@ public function testIsGranted()
...
+        $firewallMap = $this->createMock(FirewallMap::class);
+
+        $firewallMap->expects($this->once())
+            ->method('getFirewallConfig')
+            ->with($request)
+            ->willReturn($expectedFirewallConfig);
+
+        $container = $this->createContainer('security.firewall.map', $firewallMap);
+
+        $security = new \Symfony\Component\Security\Core\Security($container);
```
Comment (chalasr) [inline src/Symfony/Bundle/SecurityBundle/Tests/Security/SecurityTest.php:102]: Bad rebase :) See #46619

Comment (Kocal) [reply src/Symfony/Bundle/SecurityBundle/Tests/Security/SecurityTest.php:102]: Thx!
