### PR TITLE
[DoctrineBridge] Restore compatibility with Doctrine ODM

### LINKED ISSUE #60921: [DoctrineBridge] DC break with Doctrine ODM integration
### Symfony version(s) affected

6.4.20

### Description

The following commit introduced a breaking change for Doctrine ODM integration:
https://github.com/symfony/doctrine-bridge/commit/7205dbc642bac2ecbf108fadbf9a04aa08290a2a

The problematic code is:

```php
if (property_exists(OrmClassMetadata::class, 'propertyAccessors')) {
    $fieldValue = $class->propertyAccessors[$fieldName]->getValue($entity);
} else {
    $fieldValue = $class->reflFields[$fieldName]->getValue($entity);
}
```
The issue arises because the check only verifies whether the propertyAccessors property exists on the OrmClassMetadata class, but $class is actually an instance of [Doctrine\ODM\MongoDB\Mapping\ClassMetadata](https://github.com/doctrine/mongodb-odm/blob/2.11.x/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php), not `Doctrine\ORM\Mapping\ClassMetadata` when both ODM and ORM are installed on the same project.

Doctrine ODM does not define the propertyAccessors property, so this results in an error when the bridge tries to access a non-existent property.

### How to reproduce

Install the latest ODM and ORM bundles in the same project, and then the Unique validator

```php
<?php
use Doctrine\Bundle\MongoDBBundle\Validator\Constraints\Unique;

#[Document]
#[Unique(fields: ['name'])]
class User
{
    #[Field]
    private string $name;
    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }
}
```

### Possible Solution

Ensure that the metadata class being inspected is an instance of Doctrine\ORM\Mapping\ClassMetadata (or similar), not just that the OrmClassMetadata::class defines the property. For example:

```php
if ($class instanceof \Doctrine\ORM\Mapping\ClassMetadata && property_exists($class, 'propertyAccessors')) {
   ...
}

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by pepeh**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60921
| License       | MIT

Ensure that the metadata class being inspected is an instance of Doctrine\ORM\Mapping\ClassMetadata to fix ODM integration when both ODM and ORM packages are installed in the same Symfony project.

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php [hunk 1]
```diff
@@ -93,7 +93,7 @@ public function validate(mixed $entity, Constraint $constraint)
                 throw new ConstraintDefinitionException(sprintf('The field "%s" is not mapped by Doctrine, so it cannot be validated for uniqueness.', $fieldName));
             }
 
-            if (property_exists(OrmClassMetadata::class, 'propertyAccessors')) {
+            if ($class instanceof OrmClassMetadata && property_exists($class, 'propertyAccessors')) {
```
Comment (GromNaN) [inline src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php]: MongoDB ODM will most likely implement the same thing in the near future. We can make it future-proof by not checking the class of the metadata:

```suggestion
            if (property_exists($class, 'propertyAccessors')) {
```

The check is more contextual, which is more resilient.

Comment (stof) [reply src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php]: @GromNaN I suggest doctrine/persistence should add an API covering that need to allow writing code against the doctrine/persistence abstraction (right now, those `$class->propertyAccessors` or `$class->reflFields` are implementation-specific, which worked until now because all Doctrine projects were implementing the same approach, but it is not enforced by the doctrine/persistence abstraction).

Comment (GromNaN) [reply src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php]: Thanks for your review @stof. I created https://github.com/doctrine/persistence/issues/426 to track this.

Also, I've remembered that both ORM and ODM has a `ClassMetadata::getFieldValue` method that should be used here (when it exists). An interface need to be added in doctrine/persistence to help detecting when this feature is implemented.

**Comment by pepeh** [comment]
Is this change planned to be included in 6.4 in the near future?

**Review by GromNaN — APPROVED** [review]

File: src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php [hunk 2]
```diff
@@ -93,7 +93,7 @@ public function validate(mixed $entity, Constraint $constraint)
                 throw new ConstraintDefinitionException(sprintf('The field "%s" is not mapped by Doctrine, so it cannot be validated for uniqueness.', $fieldName));
             }
 
-            if (property_exists(OrmClassMetadata::class, 'propertyAccessors')) {
```
Comment (stof) [inline src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php:96]: Please also remove the use statement for OrmClassMetadata (no idea why fabbot does not detect it)

Comment (pepeh) [reply src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php:96]: Removed

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @pepeh.
