### PR TITLE
[Messenger] Fix time-limit check exception

### LINKED ISSUE #48196: messenger:consume async --time-limit=# always rise an error
### Symfony version(s) affected

4.4.49-DEV

### Description

969f19b16e55f01598ed540c7a83e0259e155dda commit (or maybe other?) makes --time-limit=# to always rise an error.
4.4.47 is checked as fine.

### How to reproduce

php bin/console messenger:consume async -t 3600

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alamirault**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #48196  
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Check on `time-limit` was invalid.

(Unrelated fabbot failure)

### CODE REVIEW

File: src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php [hunk 1]
```diff
@@ -179,7 +179,7 @@ protected function execute(InputInterface $input, OutputInterface $output)
         }
 
         if (null !== ($timeLimit = $input->getOption('time-limit'))) {
-            if (!is_numeric($timeLimit) || 0 >= $limit) {
+            if (!is_numeric($timeLimit) || 0 >= $timeLimit) {
```
Comment (maxbeckers) [inline src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php:182]: Can you add a test to cover that?

Comment (alamirault) [reply src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php:182]: See my Pr description, is slow test is acceptable ?

Comment (alamirault) [reply src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php:182]: Test added

**Review by maxbeckers — APPROVED** [review]
Good catch! And thanks for the test.

Please have a look at the fabbot.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @alamirault.
