### PR TITLE
[Translation] Fix extracting qualified `t()` function calls

### LINKED ISSUE #53835: [Translation] Extraction of translations does not work (from method `trans`and `t`)
### Symfony version(s) affected

6.4.3

### Description

PR https://github.com/symfony/symfony/pull/53624 ([Translation] Fix constant domain resolution in PhpAstExtractor) Introduces a new visitor for the PhpAstExtractor, that resolves methods and constant name spaces. [See](https://github.com/symfony/symfony/pull/53624/files#diff-71dc68035d7ce0be9042076467f4cdc6fd1a0146095b7875b5230770dbf019aeR51)

The problem is that the [TransMethodVisitor](https://github.com/symfony/symfony/blob/97b6064d988ce682397d3be004928bf67b8e6bf3/src/Symfony/Component/Translation/Extractor/Visitor/TransMethodVisitor.php#L44) is unable to handle these namespaces. It is only aware of matching method names.

### How to reproduce

1) Checkout symonfy/symfony 
2) Run composer update
3) Go to `src/Symfony/Component/Translation/Tests/Fixtures/extractor-ast/translatable-short.html.php` and replace the second line 
```php
 - <?php t('translatable-short single-quoted key'); ?>
+ <?php use function Symfony\Component\Translation\t; t('translatable-short single-quoted key'); ?>
```
 (e.g. importing the function that is used like people would do it in reallife. Just having `t()` would result in an undefined function 't' and therefore this test case as it is at the moment does not reflect real life)

4) Run the corresponding tests with `php ./phpunit symfony src/Symfony/Component/Translation/Tests/Extractor/PhpAstExtractorTest.php`

### Possible Solution

There are technically two solutions:

1) Revert this pull request which breaks the extraction https://github.com/symfony/symfony/pull/53624
2) Fix the [TransMethodVisitor](https://github.com/symfony/symfony/blob/97b6064d988ce682397d3be004928bf67b8e6bf3/src/Symfony/Component/Translation/Extractor/Visitor/TransMethodVisitor.php) so it can handle the fully qualified namespace of the detected method.

I am happy to invest my time to tackle solution 2, but obiously only if that would be the way to go. Please let me know ASAP

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rvanvelzen**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #53835
| License       | MIT

`t()` calls are generally qualified. The visitor used to look at the full name for the function call, but since #53624 this is replaced by the qualified name.

This PR adjusts the comparison to only look at the last part of the qualified name.

### CODE REVIEW

**Review by VincentLanglet — APPROVED** [review]

File: src/Symfony/Component/Translation/Extractor/Visitor/TransMethodVisitor.php [hunk 1]
```diff
@@ -39,7 +39,7 @@ public function leaveNode(Node $node): ?Node
             return null;
         }
 
-        $name = (string) $node->name;
+        $name = $node->name instanceof Node\Name ? $node->name->getLast() : (string) $node->name;
```
Comment (VincentLanglet) [inline src/Symfony/Component/Translation/Extractor/Visitor/TransMethodVisitor.php:42]: If I understand correctly, because I added 
```
$nameResolver = new NodeVisitor\NameResolver();
            $traverser->addVisitor($nameResolver);
```
now, the namespace is resolved and the `name` doesn't match `trans` or `t` anymore but the full name instead.

This change seems legit to get back the previous behavior.

But does it means that if someone write:
```
use function Foo\Bar\t;

t('foo');
```
we're considering `'foo`' as a translation key too ?

Best fix would check for the namespace too (now we have it), but it might be more complex.

Comment (rvanvelzen) [reply src/Symfony/Component/Translation/Extractor/Visitor/TransMethodVisitor.php:42]: I did consider including the namespace, but that would be a BC break for any project that relies on any `t()` function being extracted. That should probably be deprecated first.

This PR only restores the original behaviour.

Comment (VincentLanglet) [reply src/Symfony/Component/Translation/Extractor/Visitor/TransMethodVisitor.php:42]: Seems legit, and nobody reported an issue with the old behavior so far. So let's go with this!

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @rvanvelzen.
