### PR TITLE
[Mime] handle passing custom mime types as string

### LINKED ISSUE #36715: MimeTypes::getMimeTypes() errors on custom mimetypes.
**Symfony version(s) affected**: looks like 4.2+

**Description**  
`Type error:  Type error: Return value of Symfony\Component\Mime\MimeTypes::getMimeTypes() must be of the type array, string returned` when passing custom map through constructor.

**How to reproduce**  
`$type =(new MimeTypes([
        'application/octet-stream' => ['rrd']
    ]))->getMimeTypes('rrd')`

**Possible Solution**  
Add `[]`'s around `$mimeType` in constructor

### PR DESCRIPTION
**Pull request by mcneely**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36715
| License       | MIT
| Doc PR        | none
Fix's issue where custom mimetypes were failing

### CODE REVIEW

File: src/Symfony/Component/Mime/MimeTypes.php [hunk 1]
```diff
@@ -48,10 +48,12 @@ final class MimeTypes implements MimeTypesInterface
     public function __construct(array $map = [])
     {
         foreach ($map as $mimeType => $extensions) {
+            $extensions = \is_string($extensions) ? [$extensions] : $extensions;
             $this->extensions[$mimeType] = $extensions;
```
Comment (xabbuh) [inline src/Symfony/Component/Mime/MimeTypes.php:52]: What about `$this->extensions[$mimeType] = (array) $extensions;` instead?

**Comment by xabbuh** [comment]
I am not sure that this qualifies as a bug fix. Reading the code it clear that the constructor expects a list of extensions not a single one.  Maybe we should clarify that by adding a docblock?

Like this:

```php
/**
 * @param array<string, array<int, string>> $map
 */
public function __construct(array $map = [])
{
    // ...
}
```

**Comment by mcneely** [comment]
@xabbuh 
The bugfix is on line 56, right now it's setting the mimetype for an extension as a string and not an array. getMimeTypes is expected to return an array but when it gets the extension it's a string and throws an error.

**Comment by xabbuh** [comment]
What I wanted to say is that this was probably not supposed to work:

```php
$mt = new MimeTypes([
    'text/bar' => 'foo',
]);
```

It should have been written like this instead:

```php
$mt = new MimeTypes([
    'text/bar' => ['foo'],
]);
```

**Comment by mcneely** [comment]
What's wrong with adding that in?

**Comment by xabbuh** [comment]
There's nothing wrong with it. I am just questioning whether this has been an intended usage. Depending on the answer this patch would either be a bugfix or a new feature.

**Comment by mcneely** [comment]
@xabbuh I have removed the line of convenience code you're so caught up on. Now it's only a bug fix.

**Comment by mcneely** [comment]
@nicolas-grekas I think the 7.1 integration just needs to be rerun, some sort of hiccup, probably because of 2 commits back to back.

**Comment by nicolas-grekas** [comment]
At least there is a bug that *if* you pass a string, is explodes.
I'm fine merging as a bugfix for this reason on my side.

**Comment by xabbuh** [comment]
> @xabbuh I have removed the line of convenience code you're so caught up on. Now it's only a bug fix.

I think there is a misunderstanding here. My concern whether or not that line is important, but whether or not we want to treat the whole patch as a bugfix or as a new feature. I can see good reasons for both that's why I wanted to discuss that.

File: src/Symfony/Component/Mime/MimeTypes.php [hunk 2]
```diff
@@ -51,7 +51,8 @@ public function __construct(array $map = [])
...
 
             foreach ($extensions as $extension) {
-                $this->mimeTypes[$extension] = $mimeType;
+                $this->mimeTypes[$extension] = $this->mimeTypes[$extension] ?? [];
+                array_push($this->mimeTypes[$extension], $mimeType);
```
Comment (xabbuh) [inline src/Symfony/Component/Mime/MimeTypes.php:55]: You can shorten the patch a bit by using `[]`:

```php
$this->mimeTypes[$extension][] = $mimeType;
```

**Review by xabbuh — APPROVED** [review]
with a minor change

File: src/Symfony/Component/Mime/MimeTypes.php (hunk 2 above)
Comment (mcneely) [reply src/Symfony/Component/Mime/MimeTypes.php]: done.

**Review by javiereguiluz — APPROVED** [review]

File: src/Symfony/Component/Mime/MimeTypes.php [hunk 3]
```diff
@@ -51,7 +51,8 @@ public function __construct(array $map = [])
             $this->extensions[$mimeType] = $extensions;
 
             foreach ($extensions as $extension) {
-                $this->mimeTypes[$extension] = $mimeType;
+                $this->mimeTypes[$extension] = $this->mimeTypes[$extension] ?? [];
```
Comment (fabpot) [inline src/Symfony/Component/Mime/MimeTypes.php:54]: This line is unnecessary and can be removed.

**Review by fabpot — CHANGES_REQUESTED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @mcneely.
