### PR TITLE
[HtmlSanitizer] Fix access to undefined keys in UrlSanitizer

### LINKED ISSUE #59524: [HtmlSanitizer] Access to undefined key in UrlSanitizer
### Symfony version(s) affected

6.1.0 and above

### Description

Hello,

I'm getting an error when sanitizing a text with urls. I have multiple allowed hosts in my config, and thus html sanitization for urls fails with access to undefined keys when calling `UrlSanitizer->matchAllowedHostParts`.

<details>
<summary>Here are details about narrowing down the issue to `UrlSanitizer->matchAllowedHostParts`</summary>
This becomes quite obvious that when looking at `matchAllowedHostParts`

```php
# src/Symfony/Component/HtmlSanitizer/TextSanitizer/UrlSanitizer.php
private static function matchAllowedHostParts(array $uriParts, array $trustedParts): bool
    {
        // Check each chunk of the domain is valid
        foreach ($trustedParts as $key => $trustedPart) {
            if ($uriParts[$key] !== $trustedPart) {
                return false;
            }
        }

        return true;
    }
```

when `$trustedParts` is longer than `$uriParts`. It eventually ends with a warning : `Warning: Undefined array key 2`.
</details>

### How to reproduce

Here is a way to reproduce the issue through HtmlSanitizer unit tests : 

1. Open `src/Symfony/Component/HtmlSanitizer/Tests/TextSanitizer/UrlSanitizerTest.php`
2. Add the following test case :
   ```php
        yield [
            'input' => 'https://trusted.com/link.php',
            'allowedSchemes' => ['http', 'https'],
            'allowedHosts' => ['subdomain.trusted.com', 'trusted.com'],
            'forceHttps' => false,
            'allowRelative' => false,
            'expected' => 'https://trusted.com/link.php',
        ];
  ```
3. Test fails with : 

```
4) Symfony\Component\HtmlSanitizer\Tests\TextSanitizer\UrlSanitizerTest::testSanitize with data set #27 ('https://trusted.com/link.php', array('http', 'https'), array('subdomain.trusted.com', 'trusted.com'), false, false, 'https://trusted.com/link.php')
Undefined array key 2

/home/stoakes/dev/symfony/src/Symfony/Component/HtmlSanitizer/TextSanitizer/UrlSanitizer.php:135
/home/stoakes/dev/symfony/src/Symfony/Component/HtmlSanitizer/TextSanitizer/UrlSanitizer.php:123
/home/stoakes/dev/symfony/src/Symfony/Component/HtmlSanitizer/TextSanitizer/UrlSanitizer.php:63
/home/stoakes/dev/symfony/src/Symfony/Component/HtmlSanitizer/Tests/TextSanitizer/UrlSanitizerTest.php:24
```

### Possible Solution

I would check that key exists before accessing it. Roughly : 

```php
private static function matchAllowedHostParts(array $uriParts, array $trustedParts): bool
    {
        // Check each chunk of the domain is valid
        foreach ($trustedParts as $key => $trustedPart) {
            if (array_key_exists($key, $uriParts) && $uriParts[$key] !== $trustedPart) {
                return false;
            }
        }

        return true;
    }
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Stoakes**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no 
| Issues        | Fix #59524 
| License       | MIT

This PR fixes the bug highlighted in #59524 and adds the unit test used to prove the error.

### CODE REVIEW

File: src/Symfony/Component/HtmlSanitizer/TextSanitizer/UrlSanitizer.php [hunk 1]
```diff
@@ -132,7 +132,7 @@ private static function matchAllowedHostParts(array $uriParts, array $trustedPar
     {
         // Check each chunk of the domain is valid
         foreach ($trustedParts as $key => $trustedPart) {
-            if ($uriParts[$key] !== $trustedPart) {
+            if (array_key_exists($key, $uriParts) && $uriParts[$key] !== $trustedPart) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HtmlSanitizer/TextSanitizer/UrlSanitizer.php]: shouldn't this fail if they don't match?
```suggestion
            if (!array_key_exists($key, $uriParts) || $uriParts[$key] !== $trustedPart) {
```

Comment (Stoakes) [reply src/Symfony/Component/HtmlSanitizer/TextSanitizer/UrlSanitizer.php]: That's indeed better.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @Stoakes.
