### PR TITLE
[HttpFoundation] Add support for all core response http control directives

### LINKED ISSUE #35720: add support for appending no-cache to Cache-Control header
**Description**  
While using Symphony in Laravel, we set response headers for GET requests through a middleware `cache.headers`

```(php)
Route::resource('blogs', 'BlogPostController')->except('create','edit')->middleware('cache.headers:private;max_age=86400;etag');
```
If I add `no_cache` then it breaks the response, and I get the error 

`Response does not support the following options: "no-cache".`

The error led me to following block of code in `Symfony\Component\HttpFoundation`

```
if ($diff = array_diff(array_keys($options), ['etag', 'last_modified', 'max_age', 's_maxage', 'private', 'public', 'immutable'])) {
throw new \InvalidArgumentException(sprintf('Response does not support the following options: "%s".', implode('", "', $diff)));
}
```

adding `no_cache` support will be really helpful.

### PR DESCRIPTION
**Pull request by azjezz**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no 
| Tickets       | Fix #35720
| License       | MIT
| Doc PR        | N/A

Add support for all core cache-control directives

see : https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

### CODE REVIEW

File: src/Symfony/Component/HttpFoundation/Response.php [hunk 1]
```diff
@@ -82,6 +82,24 @@ class Response
     const HTTP_NOT_EXTENDED = 510;                                                // RFC2774
     const HTTP_NETWORK_AUTHENTICATION_REQUIRED = 511;                             // RFC6585
 
+    const HTTP_RESPONSE_CACHE_CONTROL_DIRECTIVES = [
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Response.php]: `// see developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control` on top would be helpful

File: src/Symfony/Component/HttpFoundation/Response.php [hunk 2]
```diff
@@ -968,6 +986,16 @@ public function setCache(array $options): object
             $this->setImmutable((bool) $options['immutable']);
         }
 
+        foreach (['proxy_revalidate', 'must_revalidate', 'no_cache', 'no_store', 'no_transform'] as $directive) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Response.php]: what's this list about?

**Review by nicolas-grekas — COMMENTED** [review]
Please add tests.

File: src/Symfony/Component/HttpFoundation/Response.php (hunk 2 above)
Comment (azjezz) [reply src/Symfony/Component/HttpFoundation/Response.php]: cases the are not handled above, these directives don't have values so they are either set or not.

File: src/Symfony/Component/HttpFoundation/Response.php (hunk 1 above)
[the remark this answers is not in the document]
Comment (azjezz) [reply src/Symfony/Component/HttpFoundation/Response.php]: i think that's not part of symfony CS.

/cc @nicolas-grekas ?

Comment (azjezz) [reply src/Symfony/Component/HttpFoundation/Response.php]: P.S : `last-modified` and `etag` are not http cache control directives but they are used in `setCache`. should we remove them from this array ? also, should we add `stale-while-revalidate` and `stale-if-error` ( extensions, not part of core )

Comment (azjezz) [reply src/Symfony/Component/HttpFoundation/Response.php]: note: if we remove `last-modified` and `etag` we would still need to support both in `setCache` otherwise that would be considered a BC-break. but maybe we can deprecate setting these two via `setCache` and suggest using `setLastModified` and `setETag` in the future instead ?

File: src/Symfony/Component/HttpFoundation/Response.php (hunk 2 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/Response.php]: then the const above should describe this instead of inlining this line here
directives could be used as keys, and values would be booleans

File: src/Symfony/Component/HttpFoundation/Response.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/Response.php]: no need to change something that works

File: src/Symfony/Component/HttpFoundation/Response.php (hunk 2 above)
Comment (azjezz) [reply src/Symfony/Component/HttpFoundation/Response.php]: >directives could be used as keys 

all directives are passed to `setCache` as keys not values.
the value is either an `int` representing "seconds" or `boolean` describing whether or not to use the cache control directive.

`immutable` is handled as : 
```
if (isset($options['immutable'])) {
  $this->setImmutable((bool) $options['immutable']);
}
```

where `setImmutable` does exactly what we are doing here in the `foreach` loop.

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/Response.php]: I was talking about the value of the const.

File: src/Symfony/Component/HttpFoundation/Response.php (hunk 1 above)
[the remark this answers is not in the document]
Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/Response.php]: private would be a better fit actually, isn't it?

[the remark this answers is not in the document]
Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/Response.php]: actually, this would be better inline to me: one less indirection 1000-line when reading the code...

**Review by nicolas-grekas — COMMENTED** [review]
Maybe some tests, a changelog entry?

**Comment by azjezz** [comment]
Added tests and a changelog entry.

**Comment by nicolas-grekas** [comment]
@azjezz thanks. What about https://github.com/symfony/symfony/pull/35748#discussion_r401165779 ?

File: src/Symfony/Component/HttpFoundation/Tests/ResponseTest.php [hunk 3]
```diff
@@ -659,6 +659,19 @@ public function testSetCache()
 
         $response->setCache(['immutable' => false]);
         $this->assertFalse($response->headers->hasCacheControlDirective('immutable'));
+
+        $directives = ['proxy_revalidate', 'must_revalidate', 'no_cache', 'no_store', 'no_transform'];
+        foreach ($directives as $directive) {
+            $response->setCache([$directive => true]);
+
+            $this->assertTrue($response->headers->hasCacheControlDirective(str_replace('_', '-', $directive)));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Tests/ResponseTest.php]: we don't need the str_replace here, do we? (same below)

Comment (azjezz) [reply src/Symfony/Component/HttpFoundation/Tests/ResponseTest.php]: fixed :+1:

File: src/Symfony/Component/HttpFoundation/Response.php (hunk 2 above)
Comment (azjezz) [reply src/Symfony/Component/HttpFoundation/Response.php]: you mean : 
```
cosnt NAME = [
  'foo' => false,
  'bar' => true
]
```
( where true indicates that it has a value ? )

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/Response.php]: yes!

File: src/Symfony/Component/HttpFoundation/Response.php [hunk 4]
```diff
@@ -967,8 +972,29 @@ public function setCache(array $options): object
...
+     * Sets the ETag value.
+     *
+     * @param string|null $etag The ETag unique identifier or null to remove the header
+     * @param bool        $weak Whether you want a weak ETag or not
+     *
+     * @return $this
+     *
+     * @final
+     */
+    public function setEtag(string $etag = null, bool $weak = false): object
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Response.php:988]: can you please move this back were it was located in the file?

File: src/Symfony/Component/HttpFoundation/Response.php [hunk 5]
```diff
@@ -951,6 +944,18 @@ public function setCache(array $options): object
             $this->setSharedMaxAge($options['s_maxage']);
         }
 
+        foreach (self::HTTP_RESPONSE_CACHE_CONTROL_DIRECTIVES as $directive => $hasValue) {
+            if (!$hasValue) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Response.php:948]: `if ($hasValue || !isset($options[$directive])) => continue`

File: src/Symfony/Component/HttpFoundation/Tests/ResponseTest.php (hunk 3 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/Tests/ResponseTest.php:667]: why fixed? the str_replace is still here :)

Comment (azjezz) [reply src/Symfony/Component/HttpFoundation/Tests/ResponseTest.php:667]: `response->headers->hasCacheControlDirective` uses `-` ( correct way ), but setCache uses `_`, changing `setCache` to use `-` as well would be a BC-break.

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/Tests/ResponseTest.php:667]: > changing setCache to use - as well would be a BC-break.

would it?

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/Tests/ResponseTest.php:667]: This looks inconsistent to me, shouldn't we improve this?

Comment (azjezz) [reply src/Symfony/Component/HttpFoundation/Tests/ResponseTest.php:667]: setCache(['last_modified' => $value]); wouldn't work anymore since it only works with `last-modified`, unless we reindex the directives array and replace all _ with -, this way we can support both.

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/Tests/ResponseTest.php:667]: OK, unrelated anyway.

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @azjezz.
