### PR TITLE
[DependencyInjection] add $lazyLoad context to the generated code for lazy non-shared service by PhpDumper

### LINKED ISSUE #29930: [DI] The generated factory code for lazy non-shared services doesn't have access to the $lazyLoad flag
**Symfony version(s) affected**: 4.2 and 4.1

**Description**  
When a service is declared as non-shared, the generated compiled factory wraps its the initialization in a closure. The problem is that the new function doesn't get access to the $lazyLoad parameter which leads to errors if the generated lazy loading code (for example symfony/proxy-manager-bridge) needs to use it. 

**How to reproduce**  
```php
<?php
class MyClass {};

$container = new ContainerBuilder();

$container->register('non_shared_foo', \MyClass::class)->setShared(false)->setLazy(true)->setPublic(true);
$container->compile();

$dumper = new PhpDumper($container);

print_r($dumper->dump(['as_files' => true));
```
The generated getNonSharedFooService.php looks like this:
```php
<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

$this->factories['non_shared_foo'] = function () {
    // Returns the public 'non_shared_foo' service.

    return new \MyClass();
};

return $this->factories['non_shared_foo']();
```
This would preclude any implementation of a lazy proxy dumper to check whether the service should be lazy or not. For example if the symfony/proxy-manager-bridge is used:
```php
<?php
$container = new ContainerBuilder();

$container->register('non_shared_foo', \MyClass::class)->setShared(false)->setLazy(true)->setPublic(true);
$container->compile();
$dumper = new PhpDumper($container);
$dumper->setProxyDumper(new \Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\ProxyDumper());

print_r($dumper->dump(['as_files' => true]));
```
the generated getNonSharedFooService.php would look something like this:
```php
<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

$this->factories['non_shared_foo'] = function () {
    // Returns the public 'non_shared_foo' service.

    if ($lazyLoad) {
        return $this->createProxy('MyClass_c5258b3', function () {
            return \MyClass_c5258b3::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
                $wrappedInstance = $this->load('getNonSharedFooService.php', false);

                $proxy->setProxyInitializer(null);

                return true;
            });
        });
    }

    return new \MyClass();
};

return $this->factories['non_shared_foo']();
```

**Possible Solution**  

add `'use ($lazyLoad)` to the generated function signature

### PR DESCRIPTION
**Pull request by XuruDragon**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #29930 
| License       | MIT
| Doc PR        | n/a

Fix #29930  by adding $lazyLoad context to the generated code for lazy non-shared service by PhpDumper

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Nice. Could you please add a test case with a fixture in `PhpDumperTest.php` please (see calls to `assertStringEqualsFile` for inspiration)

**Comment by nicolas-grekas** [comment]
Please rebase for 4.2 also as 4.1 is EOLed.

**Comment by XuruDragon** [comment]
> Nice. Could you please add a test case with a fixture in `PhpDumperTest.php` please (see calls to `assertStringEqualsFile` for inspiration)

I'll add it

File: src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php [hunk 1]
```diff
@@ -223,6 +223,26 @@ public function testDumpAsFiles()
...
+        $container = include self::$fixturesPath.'/containers/container9.php';
+        $container->getDefinition('bar')->addTag('hot');
+        $container->register('non_shared_foo', \Bar\FooLazyClass::class)
+            ->setFile(realpath(self::$fixturesPath.'/includes/foo_lazy.php'))
+            ->setShared(false)
+            ->setPublic(true)
+            ->setLazy(true);
+        $container->compile();
+        $dumper = new PhpDumper($container);
+        $dump = print_r($dumper->dump(['as_files' => true, 'file' => __DIR__, 'hot_path_tag' => 'hot']), true);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php]: as_file should be off (there is only one test case where it's enabled, you picked that one :) )
please also don't take container9.php as the base but a much smaller one created for the purpose (see existing ones also)

Comment (XuruDragon) [reply src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php]: I know that there is only one test case. 
I really need the as_files option enabled otherwise we don't rh issue requierments...

I'll check to use a smaller container file

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php]: > I really need the as_files option enabled otherwise we don't match the issue requierments...

Oh, right! Looking forward to the smaller fixture then thanks :)

Comment (XuruDragon) [reply src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php]: ok

Comment (XuruDragon) [reply src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php]: done

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_non_shared_lazy_as_files.txt [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+
+use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
+use Symfony\Component\DependencyInjection\Exception\RuntimeException;
+
+// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
+// Returns the public 'non_shared_foo' service.
+
+include_once ($this->targetDirs[0].'/Fixtures/includes/foo_lazy.php');
+
+$this->factories['non_shared_foo'] = function () use ($lazyLoad) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_non_shared_lazy_as_files.txt]: `$this->factories['non_shared_foo'] = function ($lazyLoad) {`

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_non_shared_lazy_as_files.txt [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+    return new \Bar\FooLazyClass();
+};
+
+return $this->factories['non_shared_foo']();
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_non_shared_lazy_as_files.txt]: `return $this->factories['non_shared_foo']($lazyLoad);`

**Review by nicolas-grekas — COMMENTED** [review]
small tweak

**Comment by nicolas-grekas** [comment]
Another tweak: in PhpDumper on L690:
`$factoryCode = $asFile ? ($definition->isShared() ? "\$this->load('%s.php', false)" : "\$this->factories['%s'](false)") : '$this->%s(false)';`

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @XuruDragon.
