### PR TITLE
[Validator] Fix required options check when extending a constraint with a simplified constructor

### LINKED ISSUE #63594: [Validation][regression] Extends a Constrainst with required option throw MissingOptionsException
### Symfony version(s) affected

7.4.6

### Description

The code above throws a "MissingOptionsException" => `The options "pattern" must be set for constraint "App\Validator\CustomRegex".`

```php
#[\Attribute(\Attribute::TARGET_PROPERTY | \Attribute::TARGET_METHOD)]
class CustomRegex extends Regex
{
    public function __construct(
        ?array $groups = null,
    ) {
        parent::__construct(
            pattern: '/^xxxxx$/',
            message: 'Lorem ipsum ...',
            groups: $groups,
        );
    }
}
```

This MR causes this issue => https://github.com/symfony/symfony/pull/63463

### How to reproduce

.

### Possible Solution

Temporary fix : (overwrite the function getRequiredOptions)

```php
#[\Attribute(\Attribute::TARGET_PROPERTY | \Attribute::TARGET_METHOD)]
class CustomRegex extends Regex
{

    // ...

    public function getRequiredOptions(): array
    {
        return [];
    }
}
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63594
| License       | MIT

When a constraint extends another constraint that has required options (e.g. `CustomRegex extends Regex`) and simplifies the constructor by hardcoding those options, `areRequiredOptionsHandledByChildConstructor()` incorrectly throws a `MissingOptionsException`.

This happens because the method inspects the leaf class's constructor parameters via `new \ReflectionMethod($this, '__construct')`. When `CustomRegex::__construct` doesn't have a `$pattern` parameter (it hardcodes it and delegates to `Regex::__construct`), the check fails, even though `Regex::__construct` already validates `pattern`.

This is a regression introduced in #63463.

### CODE REVIEW

File: src/Symfony/Component/Validator/Tests/ConstraintTest.php [hunk 1]
```diff
@@ -359,4 +360,11 @@ public function testRequiredOptionsValidatedWhenConstructorCallsParentWithNull()
 
         new ConstraintWithRequiredOptionAndConstructor();
     }
+
+    public function testChildConstraintCanSatisfyRequiredOptionsOfParent()
+    {
+        $constraint = new CustomRegex();
```
Comment (stof) [inline src/Symfony/Component/Validator/Tests/ConstraintTest.php:366]: This `CustomRegex` class is not found, breaking the testsuite.

Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/Tests/ConstraintTest.php:366]: oops, fixed in 74843ada0a4
