### PR TITLE
[Validator] Fix support of Enum to `ConstraintValidator::formatValue`

### LINKED ISSUE #50000: Make ConstraintValidator->formatValue aware of enums
### Description

The `Symfony\Component\Validator\ConstraintValidator->formatValue()` method transforms values of a form into strings so they can be used in the error message. Now, if it is an object it checks if it's `Stringable` to convert it correctly, and if it isn't, it will use the value `"Object"`.

When the value is an enum, it will consider it as an object and check if it implements Stringable, the problem is that enums can't implement the magic method `__toString()` so it will be always "Object" which isn't too useful.

I propose to make it enum aware by adding a check to see if it's an enum and in that case use the name as value (or a concatenation of Enum-{name} to represent it.

### Example

For example, with the next code for validation of a form model:

```lang=php
// EnumNiceClass.php
enum EnumNiceClass: int {
    case DoSomething = 2;
    case NothingToDo = 3;
}

// FormModel.php
class FormModel {

Assert\NotIdenticalTo(
        value: EnumNiceClass::DoSomething,
)]
public EnumNiceClass $whatWillDo;

}
```

You will get the next message if it is invalid (with the default message `This value should not be identical to {{ compared_value_type }} {{ compared_value }}.`:

```
This value should not be identical to EnumNiceClass Object.
```

But changing the code to something like this:

```lang=php
    protected function formatValue(mixed $value, int $format = 0): string
    {

// ...

        if (\is_object($value)) {
            if (($format & self::OBJECT_TO_STRING) && $value instanceof \Stringable) {
                return $value->__toString();
            }
            
            if ($value instanceof \UnitEnum) {
                return $value->name;
            }

            return 'object';
        }
// ...
```

It would be:

```
This value should not be identical to EnumNiceClass NothingToDo.
```

That I think is more useful for debugging (and users in general).

### PR DESCRIPTION
**Pull request by PhoneixS**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #50000
| License       | MIT

I have added a simple check in the `formatValue` to see if the object is an enum and in that case, return the name of the enum instead of the "object" string.

### CODE REVIEW

**Comment by PhoneixS** [comment]
> Hey!
> 
> Thanks for your PR. You are targeting branch "6.3" but it seems your PR description refers to branch "6.2". Could you update the PR description or change target branch? This helps core maintainers a lot.
> 
> Cheers!
> 
> Carsonbot

Sorry, first time making a PR. I think it's changed now.

**Comment by stof** [comment]
I'm wondering whether this should be done only when the `OBJECT_AS_STRING` flag is passed

File: src/Symfony/Component/Validator/ConstraintValidator.php [hunk 1]
```diff
@@ -93,6 +93,10 @@ protected function formatValue(mixed $value, int $format = 0): string
                 return $value->__toString();
             }
 
+            if ($value instanceof \UnitEnum) {
+                return $value->name;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/ConstraintValidator.php]: I'd suggest going with `$value::class.'::'.$value->name`.
can you please add a test case about it?

**Comment by PhoneixS** [comment]
I have changed so enums are treated more like objects, if there isn't an OBJECT_TO_STRING flag they are displayed as "enum"; if the flag is present it returns the enum name.

I have also added both test cases (with or without the flag).

File: src/Symfony/Component/Validator/ConstraintValidator.php (hunk 1 above)
Comment (PhoneixS) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: I don't see why it is better to check it with your code `$value::class.'::'.$value->name`. I think it is more readable with `instanceof`. Is there a case in which it can fail?

**Comment by PhoneixS** [comment]
Tests passed but failed because of unrelated  `Error: KO src/Symfony/Component/HttpClient`.

File: src/Symfony/Component/Validator/ConstraintValidator.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: I'm not commenting on the check but on the return value.
We should return the name of the class + the name of case, not only the former.
`$value::class.'::'.$value->name`

File: src/Symfony/Component/Validator/ConstraintValidator.php [hunk 2]
```diff
@@ -88,6 +88,14 @@ protected function formatValue(mixed $value, int $format = 0): string
             return $value->format('Y-m-d H:i:s');
         }
 
+        if (\is_object($value) && $value instanceof \UnitEnum) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/ConstraintValidator.php]: is_object check is not needed, instanceof in enough

File: src/Symfony/Component/Validator/ConstraintValidator.php (hunk 1 above)
Comment (PhoneixS) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: ohhh, I see it now. I will change it.

File: src/Symfony/Component/Validator/ConstraintValidator.php (hunk 2 above)
Comment (PhoneixS) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: Correct, I'll remove it.

File: src/Symfony/Component/Validator/ConstraintValidator.php (hunk 1 above)
Comment (PhoneixS) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: Mmm, with that change it's a bit too verbose as it returns the full qualified class name. Although as this is more of a developer thing than something which would be seen by clients it could be ok.

File: src/Symfony/Component/Validator/ConstraintValidator.php [hunk 3]
```diff
@@ -88,6 +88,14 @@ protected function formatValue(mixed $value, int $format = 0): string
             return $value->format('Y-m-d H:i:s');
         }
 
+        if ($value instanceof \UnitEnum) {
+            if ($format & self::OBJECT_TO_STRING) {
+                return $value::class.'::'.$value->name;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/ConstraintValidator.php]: On a closer look, my advice was wrong I think, since the message already contains the class of the enum.
Let's make this be `return 'case '.$value->name;` so that messages looks like this?
"This value should not be identical to Symfony\Component\Validator\Tests\TestEnum case FirstCase"

Comment (PhoneixS) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: In my opinion, we shouldn't add the 'case ' text, as it would be better added in the message itself.

Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: but how can the message know about this? or maybe we should change the type to make it report "enum" and keep this as is?

Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: Or maybe formatTypeOf should be changed instead to return `$value::class.'::'.$value->name`?

Comment (PhoneixS) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: > Or maybe formatTypeOf should be changed instead to return `$value::class.'::'.$value->name`?

I see your point, however, I think that the function should only return the type (the class is the type and is enough for debugging) the same way the formatValue should only return the value (and the name is the textual representation of the enum value). Making each method return one thing whatever is called for. This is why I initially only return the name and probably we could just return to my initial implementation of returning the name of the enum.

Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: OK, let's do this.

File: src/Symfony/Component/Validator/ConstraintValidator.php [hunk 4]
```diff
@@ -88,6 +88,14 @@ protected function formatValue(mixed $value, int $format = 0): string
             return $value->format('Y-m-d H:i:s');
         }
 
+        if ($value instanceof \UnitEnum) {
+            if ($format & self::OBJECT_TO_STRING) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/ConstraintValidator.php]: I would remove this check personally, I don't see its value.

Comment (PhoneixS) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: The first it's to check if it's an enum instead of a generic object.  The second is to maintain the same behavior as with objects, if the flag is set you return a value if not set, you return the string of what it is, an "enum" in this case and "object" in the object case.

I think we should keep them to maintain a similar functionality as with objects.

Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: I don't see the link with OBJECT_TO_STRING flag here. This is unrelated to calling `__toString`. This method is creating a representation of the value. "enum" is not accurate enough, independently from any flag.

Comment (PhoneixS) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: It's true that it could be better to have another flag like `self::NAME_OF_ENUM` specific for the enums (the same way objects have `self::OBJECT_TO_STRING` and `self::PRETTY_DATE` for dates. As this is my first PR I wanted to change the less possible but I can add it if it fits.

Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: No need for any flag IMHO.

Comment (PhoneixS) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: So you say to always return the name? In my opinion is better to let the developer decide what they want. Maybe someone wants to hide the actual value because it's shown to the user but others prefer to see it for debugging proposed. Isn't it the same reasoning as for dates and objects?

Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: We display strings and numbers, so why not enums? I see each flag as a complication. The class of the enum is already exposed, not saying which case is concerned just worsen DX to me, this is not something that devs want to opt-in for, nor disable.

Comment (PhoneixS) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: Ok, I will remove the flag and return always the name

Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/ConstraintValidator.php]: Thanks, and sorry for the confusion :)

**Comment by nicolas-grekas** [comment]
Thank you @PhoneixS.

**Comment by PhoneixS** [comment]
You’re welcome. It's always nice to return a little bit to a great project.
