### PR TITLE
[TypeInfo] Fix collectUses() to support grouped use imports

### LINKED ISSUE #63917: [TypeInfo] collectUses() does not support grouped use imports, causing wrong PHPDoc type resolution
### Symfony version(s) affected

7.4

### Symfony version(s) affected

7.4.x (reproduced on 7.4.3 and 7.4.8)

### Description

`Symfony\Component\TypeInfo\TypeContext\TypeContextFactory::collectUses()` does not correctly parse grouped `use` statements, especially multiline grouped imports.

This causes wrong alias resolution for PHPDoc types (`@var`, `@param`, `@return`) when PropertyInfo uses `PhpStanExtractor`.

### Minimal reproduction 

```php
<?php

namespace App\Example;

use Vendor\Package\{
    AlphaType,
    BetaType,
};
use App\Domain\{
    FooType,
    BarType,
};

final class ExampleData
{
    /** @var list<FooType> */
    public array $fooList = [];

    /** @var list<BarType> */
    public array $barList = [];
}
When resolving property types with PropertyInfo + PhpStanExtractor:

Expected: FooType -> App\Domain\FooType, BarType -> App\Domain\BarType
Actual: aliases can be unresolved or misresolved because grouped imports are not properly collected.
Suspected root cause
Current code in collectUses() parses line-by-line with a naive use detection and does not parse grouped syntax ({...}):

https://github.com/symfony/symfony/blob/v7.4.3/src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php#L156-L180

PhpStanExtractor builds and uses this TypeContextFactory:

https://github.com/symfony/symfony/blob/v7.4.3/src/Symfony/Component/PropertyInfo/Extractor/PhpStanExtractor.php#L95

In FrameworkBundle, phpstan extractor is prioritized before phpdoc extractor:

https://github.com/symfony/symfony/blob/v7.4.3/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L2270-L2279

So incorrect type resolution from PhpStanExtractor is used first.

Workarounds
Replace grouped imports with one import per line, or
disable/override PhpStanExtractor in the PropertyInfo extractor chain.


### Possible Solution

### Possible correction

Update `TypeContextFactory::collectUses()` to properly parse grouped imports:

- handle single-line grouped imports:
  - `use Foo\Bar\{Baz, Qux};`
- handle multiline grouped imports:
  - `use Foo\Bar\{`
  - `    Baz,`
  - `    Qux as LocalQux,`
  - `};`
- keep support for normal imports and `as` aliases
- ignore trait-use statements inside class bodies (current behavior should remain)

Suggested parsing approach:
1. Trim each line.
2. Detect start of top-level `use ` statement.
3. If `{` is present, enter a grouped-use state and store prefix (`Foo\Bar\`).
4. Parse comma-separated members until `}` is reached, applying `as` alias per member.
5. Build `$uses[$alias] = $fqcn` for each member.
6. Continue normal parsing for non-grouped `use`.

This should preserve current behavior while fixing grouped-import alias resolution.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Amoifr**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63917
| License       | MIT

`TypeContextFactory::collectUses()` did not parse grouped `use` statements (`use Foo\{Bar, Baz};`), causing wrong PHPDoc type resolution when PropertyInfo uses PhpStanExtractor.

This adds support for both single-line (`use Foo\{Bar, Baz};`) and multiline grouped imports, including `as` aliases within groups.

### CODE REVIEW

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 1]
```diff
@@ -166,14 +166,57 @@ private function collectUses(\ReflectionClass $reflection): array
...
+            if ($inGroupedUse) {
+                foreach (explode(',', $trimmed) as $member) {
+                    $member = trim($member, " \t\n\r\0\x0B};");
+                    if ('' === $member) {
+                        continue;
+                    }
+
+                    $parts = preg_split('/\s+as\s+/', $member, 2);
+                    $fqcn = $groupPrefix.$parts[0];
+                    $alias = isset($parts[1]) ? $parts[1] : substr($fqcn, false !== ($p = strrpos($fqcn, '\\')) ? 1 + $p : 0);
```
Comment (mtarld) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]:
```suggestion
                    $alias = $parts[1] ?? substr($fqcn, false !== ($p = strrpos($fqcn, '\\')) ? 1 + $p : 0);
```

File: src/Symfony/Component/TypeInfo/Tests/Fixtures/DummyWithGroupedUses.php [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+
+namespace Symfony\Component\TypeInfo\Tests\Fixtures;
+
+use Symfony\Component\TypeInfo\{
+    Type,
+    TypeIdentifier,
+};
+use \DateTimeImmutable as DateTime;
+
+final class DummyWithGroupedUses
```
Comment (mtarld) [inline src/Symfony/Component/TypeInfo/Tests/Fixtures/DummyWithGroupedUses.php]: Could you also add a test for an alias inside a grouped use?
```php
use Symfony\Component\TypeInfo\{
    Type,
    TypeIdentifier as TI,
};
```

File: src/Symfony/Component/TypeInfo/Tests/TypeContext/TypeContextFactoryTest.php [hunk 3]
```diff
@@ -104,6 +106,28 @@ public function testCollectUses()
...
+        $uses = [
+            'Type' => 'Symfony\\Component\\TypeInfo\\Type',
+            'TypeIdentifier' => 'Symfony\\Component\\TypeInfo\\TypeIdentifier',
+            'DateTime' => '\\'.\DateTimeImmutable::class,
+        ];
+
+        $this->assertSame($uses, $this->typeContextFactory->createFromClassName(DummyWithGroupedUses::class)->uses);
+    }
+
+    public function testCollectSingleLineGroupedUses()
```
Comment (mtarld) [inline src/Symfony/Component/TypeInfo/Tests/TypeContext/TypeContextFactoryTest.php]: Instead of having to new fixtures, what about adding new uses in `DummyWithUses`, then merge these two tests in `testCollectUses`?

File: src/Symfony/Component/TypeInfo/Tests/TypeContext/TypeContextFactoryTest.php [hunk 4]
```diff
@@ -104,6 +106,28 @@ public function testCollectUses()
         $this->assertEquals($uses, $this->typeContextFactory->createFromReflection(new \ReflectionParameter([DummyWithUses::class, 'setCreatedAt'], 'createdAt'))->uses);
     }
 
+    public function testCollectGroupedUses()
+    {
+        $uses = [
+            'Type' => 'Symfony\\Component\\TypeInfo\\Type',
+            'TypeIdentifier' => 'Symfony\\Component\\TypeInfo\\TypeIdentifier',
```
Comment (mtarld) [inline src/Symfony/Component/TypeInfo/Tests/TypeContext/TypeContextFactoryTest.php]:
```suggestion
            'Type' => Type::class,
            'TypeIdentifier' => TypeIdentifier::class,
```

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 5]
```diff
@@ -166,14 +166,57 @@ private function collectUses(\ReflectionClass $reflection): array
...
+            if (str_starts_with($trimmed, 'use ')) {
+                $inUseSection = true;
+                $body = substr($trimmed, 4);
+
+                if (str_contains($body, '{')) {
+                    $groupPrefix = substr($body, 0, strpos($body, '{'));
+                    $inGroupedUse = !str_contains($body, '}');
+                    $segment = trim(substr($body, strpos($body, '{')), " \t\n\r\0\x0B{};");
+
+                    foreach (explode(',', $segment) as $member) {
```
Comment (mtarld) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: The logic is duplicated. Could you extract it into a private method?
(`$inGroupedUse` continuation block, initial `{` detection block, non-grouped use statement)

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 6]
```diff
@@ -166,14 +166,57 @@ private function collectUses(\ReflectionClass $reflection): array
...
+                            continue;
+                        }
+
+                        $parts = preg_split('/\s+as\s+/', $member, 2);
+                        $fqcn = $groupPrefix.$parts[0];
+                        $alias = isset($parts[1]) ? $parts[1] : substr($fqcn, false !== ($p = strrpos($fqcn, '\\')) ? 1 + $p : 0);
+                        $uses[$alias] = $fqcn;
+                    }
+                } else {
+                    $use = explode(' as ', rtrim($body, ';'), 2);
```
Comment (mtarld) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]:
```suggestion
                    $use = preg_split('/\s+as\s+/', $member, 2);
```
To be consistent.

**Review by mtarld — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php (hunk 1 above)
Comment (Amoifr) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: Done! Using `??` operator now.

File: src/Symfony/Component/TypeInfo/Tests/Fixtures/DummyWithGroupedUses.php (hunk 2 above)
Comment (Amoifr) [reply src/Symfony/Component/TypeInfo/Tests/Fixtures/DummyWithGroupedUses.php]: Done! Added `TypeIdentifier as TI` alias in the grouped use of `DummyWithUses`.

File: src/Symfony/Component/TypeInfo/Tests/TypeContext/TypeContextFactoryTest.php (hunk 3 above)
Comment (Amoifr) [reply src/Symfony/Component/TypeInfo/Tests/TypeContext/TypeContextFactoryTest.php]: Done! Merged everything into `DummyWithUses` and `testCollectUses`, removed the two extra fixtures.

File: src/Symfony/Component/TypeInfo/Tests/TypeContext/TypeContextFactoryTest.php (hunk 4 above)
Comment (Amoifr) [reply src/Symfony/Component/TypeInfo/Tests/TypeContext/TypeContextFactoryTest.php]: Done! Using `Type::class` directly. For `TypeIdentifier` the FQCN string is used since the alias is `TI` in the test.

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php (hunk 5 above)
Comment (Amoifr) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: Done! Extracted into a `parseGroupedUseMembers()` private method.

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php (hunk 6 above)
Comment (Amoifr) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: Done! Using `preg_split` for non-grouped uses too.

**Comment by Amoifr** [comment]
All feedback addressed in the latest push! Fixtures merged, logic deduplicated, syntax cleaned up.

@mtarld thank you for this excellent review — every single point was spot on and the code is much cleaner now. Really appreciate the time you took to go through it so thoroughly! 🙏

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 7]
```diff
@@ -166,14 +166,36 @@ private function collectUses(\ReflectionClass $reflection): array
...
-                $alias = 1 === \count($use) ? substr($use[0], false !== ($p = strrpos($use[0], '\\')) ? 1 + $p : 0) : $use[1];
-                $uses[$alias] = $use[0];
+                if (str_contains($trimmed, '}')) {
+                    $inGroupedUse = false;
+                }
+
+                continue;
+            }
+
+            if (str_starts_with($trimmed, 'use ')) {
```
Comment (mtarld) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: This should use `$line` instead of `$trimmed` to preserve the distinction between top-level use imports (unindented) and trait use statements (indented inside a class body). For example, consider a class with no imports but a trait:
```php
namespace App;

class Foo {
    use SomeTrait;
}
```

With `$trimmed`, "`    use SomeTrait;`" matches and `SomeTrait` gets incorrectly collected as a namespace import.

**Review by mtarld — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php (hunk 7 above)
Comment (Amoifr) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: Great catch @mtarld! You're absolutely right — using `$trimmed` here lost the distinction between top-level `use` imports and trait `use` statements inside class bodies. Switched back to `$line` to preserve the original behavior. Thanks for the sharp eye! 🙏

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 8]
```diff
@@ -166,14 +166,36 @@ private function collectUses(\ReflectionClass $reflection): array
...
-                $use = explode(' as ', substr($line, 4, -1), 2);
-
-                $alias = 1 === \count($use) ? substr($use[0], false !== ($p = strrpos($use[0], '\\')) ? 1 + $p : 0) : $use[1];
-                $uses[$alias] = $use[0];
+                $body = substr($trimmed, 4);
+
+                if (str_contains($body, '{')) {
+                    $groupPrefix = substr($body, 0, strpos($body, '{'));
+                    $inGroupedUse = !str_contains($body, '}');
+                    $segment = trim(substr($body, strpos($body, '{')), " \t\n\r\0\x0B{};");
```
Comment (nicolas-grekas) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: why this specific list of chars? is that what the PHP parser does?

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 9]
```diff
@@ -187,6 +209,24 @@ private function collectUses(\ReflectionClass $reflection): array
...
     }
 
+    /**
+     * @param array<string, string> $uses
+     */
+    private function parseGroupedUseMembers(string $segment, string $prefix, array &$uses): void
+    {
+        foreach (explode(',', $segment) as $member) {
+            $member = trim($member, " \t\n\r\0\x0B};");
+            if ('' === $member) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: nit, but also same question about the list of trimmed chars
```suggestion
            if ('' === $member = trim($member, " \t\n\r\0\x0B};")) {
```

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php (hunk 8 above)
Comment (Amoifr) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: Good point! `" \t\n\r\0\x0B"` is simply PHP's default `trim()` character list — I added `{`, `}` and `;` on top to strip the grouped-use syntax delimiters in one pass. I can simplify this to just `trim(trim(...), '{};')` to make the intent clearer — would that work for you?

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php (hunk 9 above)
Comment (Amoifr) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: Same answer as above for the char list. And yes, the inline assignment is cleaner — I'll apply your suggestion, thanks!

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php (hunk 8 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: I'd rather stick to the list of what PHP considers whitespace - not sure `\0` is part of it (dunno about `\x0B`)

Comment (Amoifr) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: Good point, thanks! Switched to `" \t\r\n{};"` — aligned with the PHP parser's whitespace set (T_WHITESPACE), dropping `\0` and `\x0B`. Simplified as requested 🙏

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php (hunk 9 above)
Comment (Amoifr) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: Same simplification applied here: `trim($member, " \t\r\n};")`. Sticking to the PHP parser's whitespace list (T_WHITESPACE) as you suggested, no more `\0` / `\x0B`. Thanks! 🙌

File: src/Symfony/Component/TypeInfo/Tests/TypeContext/TypeContextFactoryTest.php [hunk 10]
```diff
@@ -92,6 +92,7 @@ public function testCollectUses()
 
         $uses = [
             'Type' => Type::class,
+            'TI' => 'Symfony\\Component\\TypeInfo\\TypeIdentifier',
             \DateTimeInterface::class => '\\'.\DateTimeInterface::class,
             'DateTime' => '\\'.\DateTimeImmutable::class,
```
Comment (stof) [inline src/Symfony/Component/TypeInfo/Tests/TypeContext/TypeContextFactoryTest.php]: Why is this test enforcing a leading `\` on some classes but not on all of them ? This looks suspicious to me.

Comment (Amoifr) [reply src/Symfony/Component/TypeInfo/Tests/TypeContext/TypeContextFactoryTest.php]: Good eye! Those two entries were already in the fixture before this PR (added in f419f0ac — "Fix resolving use statements with line breaks"), intentionally covering the `use \Foo;` form. The parser currently stores the FQCN verbatim, leading `\` included, which is why the expected values reflect that.

Happy to normalize it by stripping a leading `\` in `collectUses()` if you think it's worth cleaning up in this PR — otherwise I'd rather keep it out of scope to stay focused on the grouped-use fix. Let me know what you prefer! 🙏

Comment (nicolas-grekas) [reply src/Symfony/Component/TypeInfo/Tests/TypeContext/TypeContextFactoryTest.php]: bugfix or not? @mtarld WDYT?

Comment (mtarld) [reply src/Symfony/Component/TypeInfo/Tests/TypeContext/TypeContextFactoryTest.php]: I think it's a bug, yes.

`TypeContext::normalize()` strips the leading `\` when received as input, but returns it as-is when it comes from the `uses` array. Therefore we have inconsistent class names downstream: for instance, `ObjectType` may store `\DateTimeImmutable` or `DateTimeImmutable` for the same class depending on how the `use` statement was written in the source file.

**Comment by Amoifr** [comment]
Thanks both for clarifying! 🙏

Pushed f68fc41 to address it: `collectUses()` now strips the leading `\` so that the values stored in `$uses` always match what `TypeContext::normalize()` produces for inline class names. Updated the two test expectations that were encoding the old (inconsistent) behavior — `TypeContextFactoryTest::testCollectUses`, `testCollectUsesWindowsLineEndings`, and `TypeContextTest::testNormalize`.

Let me know if you'd prefer this in a separate PR instead — happy to split it if it helps the bugfix vs feature classification.

**Comment by nicolas-grekas** [comment]
Thank you @Amoifr.
