### PR TITLE
[Validator] Fix translation of AtLeastOneOf constraint message

### LINKED ISSUE #41317: [Validator] AtLeastOneOf default message property is not translated.
**Symfony version(s) affected**: 5.2.8

**Description**
When default locale of the framework is set on for example **dutch** the following example will be returned:
`This value should satisfy at least one of the following constraints: [1] Deze waarde moet leeg zijn. [2] Deze waarde is te lang. Hij mag maximaal 100 tekens bevatten.`
As you can see the languages are mixed. 

**How to reproduce**
Set the locale of framework to the language dutch. I think this also problem with other languages. 

**Code example**
```php
new AtLeastOneOf(
  [
    'constraints' => [
            new Blank(),
            new Length(
                [
                    'max' => 100,
                ]
            ),
        ],
    ]
);
```

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41317
| License       | MIT
| Doc PR        | _NA_

New try after Nicolas' hint on https://github.com/symfony/symfony/pull/41325.
This is a much simpler solution using execution context to get the base message of the constraint translated.

~I tried to create the relevant test case, but other locales doesn't seem to be available in validators test cases.~ I'm having a look at a test case in a dummy locale after https://github.com/symfony/symfony/pull/49484#issuecomment-1439118960

When using another locale, the base message of the constraint is actually translated now:

image

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Can't we have a test with dummy translations in any locale?

**Comment by alexandre-daubois** [comment]
I'll have a look at it 👍

**Comment by alexandre-daubois** [comment]
The test has been added with a dummy translator 👍

File: src/Symfony/Component/Validator/Tests/Constraints/AtLeastOneOfValidatorTest.php [hunk 1]
```diff
@@ -258,6 +262,36 @@ public function testNestedConstraintsAreNotExecutedWhenGroupDoesNotMatch()
...
     }
+
+    public function testTranslatorIsCalledOnConstraintBaseMessage()
+    {
+        $translator = new class() implements TranslatorInterface, LocaleAwareInterface {
+            use TranslatorTrait;
+
+            public function trans(?string $id, array $parameters = [], string $domain = null, string $locale = null): string
+            {
+                if ($id === 'This value should satisfy at least one of the following constraints:') {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Tests/Constraints/AtLeastOneOfValidatorTest.php]: let's add another case to also translate "This value should be null."?

**Review by nicolas-grekas — COMMENTED** [review]
see fabbot :)

File: src/Symfony/Component/Validator/Tests/Constraints/AtLeastOneOfValidatorTest.php (hunk 1 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/Validator/Tests/Constraints/AtLeastOneOfValidatorTest.php]: This should be it! Also renamed the test case to be more relevant 🙂

**Comment by nicolas-grekas** [comment]
Thank you @alexandre-daubois.
