### PR TITLE
[Ldap] Make the Adapter resettable

### LINKED ISSUE #53442: symfony/ldap fails eventually in worker mode
### Symfony version(s) affected

6.4.0

### Description

For reference, this issue started from here https://github.com/dunglas/frankenphp/issues/457
In worker mode, the https://github.com/symfony/ldap/blob/6.4/Adapter/ExtLdap/Connection.php is persistent between executions.
So `__destruct()` and `disconnect()` are not executed for the lifetime of the worker.
After some time the bind session inevitably gets invalidated by the network, LDAP server, or any other participant.
At this point symfony/ldap will use the invalid bind and throw an error for all login attempts from this point.

### How to reproduce

Run Symfony in worker mode, for example run https://github.com/dunglas/symfony-docker in production mode.
Setup symfony/ldap authentication.
Notice that on authentication (after some execution so workers will start to get reused) you stop seeing new binding but only existing connections get used.
Wait for the session to get invalid or find a way to invalidate it.
From this point, all authentication on the worker will fail with:
`"message": "Uncaught PHP Exception Symfony\\Component\\Ldap\\Exception\\ConnectionException: \"Can't contact LDAP server\" at Connection.php line 86",`

### Possible Solution

If the desired setup is that in worker mode we keep using the same connection then the code needs to recover it and rebind when it stops working eventually.
Or if we want it to work as it works now not in worker mode then there needs to be something to `disconnect()` it somehow when the request ends (as `__destruct()` not executed between requests).

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by kira0269**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #53442 
| License       | MIT

As described in #53442 , the `Adapter` service in the Ldap component holds a `Connection` object, and with the FrankenPHP worker mode, the ldap connection never rebind correctly.

The solution would be to add a method in the `Adpater` service to trigger the `_destruct` of the `Connection` object.
In this MR, I added the `ResetInterface`, but I can be removed it's considered as a BC. In this case, developers would have to tag the adapter with the `kernel.reset` tag to trigger the reset.

Of course, the `_destruct` method would be called only if there is no remaining reference of it in the app. But I guess it's ok since it shouldn't be stored anywhere but only accessed through the Adapter.

### CODE REVIEW

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Adapter.php [hunk 1]
```diff
@@ -16,14 +16,15 @@
 use Symfony\Component\Ldap\Adapter\EntryManagerInterface;
 use Symfony\Component\Ldap\Adapter\QueryInterface;
 use Symfony\Component\Ldap\Exception\LdapException;
+use Symfony\Contracts\Service\ResetInterface;
```
Comment (stof) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Adapter.php]: No need to add a hard dependency on a separate package (which is not even declared properly in composer.json) for that interface. Our `kernel.reset` wiring does not require using that interface. Any method without required arguments can be registered.

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Adapter.php [hunk 2]
```diff
@@ -16,14 +16,15 @@
...
 /**
  * @author Charles Sarrazin <charles@sarraz.in>
  */
-class Adapter implements AdapterInterface
+class Adapter implements AdapterInterface, ResetInterface
 {
-    private ConnectionInterface $connection;
-    private EntryManagerInterface $entryManager;
+    private ?ConnectionInterface $connection;
+    private ?EntryManagerInterface $entryManager;
```
Comment (stof) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Adapter.php]: I would keep them non-nullable, and unset them on reset. No need to have 3 states: uninitialized, null and properly initialized.

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Adapter.php [hunk 3]
```diff
@@ -65,4 +65,9 @@ public function escape(string $subject, string $ignore = '', int $flags = 0): st
 
         return $value;
     }
+
+    public function reset(): void
+    {
+        unset($this->entryManager, $this->connection);
+    }
```
Comment (alexandre-daubois) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Adapter.php:74]: You need to manually register the function in the DI. As pointed out by stof, you can check other `kernel.reset` declarations

**Comment by nicolas-grekas** [comment]
Thank you @kira0269.
