### PR TITLE
[Mime] Add `TemplatedEmail::$locale` to the serialized props

### LINKED ISSUE #52718: [Mime]TemplatedEmail::$locale is not serialized
### Symfony version(s) affected

6.4

### Description

In https://github.com/symfony/symfony/pull/51690 the locale-property was added to TemplatedEmail, but this property is not serialized.

If Mails are sent asynchronously via the Messenger-Component, the locale-value is not available, once the TemplatedEmail is rendered. 

### How to reproduce

Create and sent a TemplatedEmail with a locale and send it via a message queue. The locale-property is not serialized to the message-queue

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mkrauser**
| Q             | A
| ------------- | ---
| Branch?       | 6.4 
| Bug fix?      | yes
| New feature?  |no
| Deprecations? | no 
| Issues        | Fix #52718
| License       | MIT

To use the locale-property when working with Symfony Messenger asynchronously it has to be serialized.

### CODE REVIEW

File: src/Symfony/Bridge/Twig/Mime/TemplatedEmail.php [hunk 1]
```diff
@@ -100,15 +100,15 @@ public function markAsRendered(): void
      */
     public function __serialize(): array
     {
-        return [$this->htmlTemplate, $this->textTemplate, $this->context, parent::__serialize()];
+        return [$this->htmlTemplate, $this->textTemplate, $this->context, $this->locale, parent::__serialize()];
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Twig/Mime/TemplatedEmail.php]:
```suggestion
        return [$this->htmlTemplate, $this->textTemplate, $this->context, parent::__serialize(), $this->locale];
```

File: src/Symfony/Bridge/Twig/Mime/TemplatedEmail.php [hunk 2]
```diff
@@ -100,15 +100,15 @@ public function markAsRendered(): void
...
     }
 
     /**
      * @internal
      */
     public function __unserialize(array $data): void
     {
-        [$this->htmlTemplate, $this->textTemplate, $this->context, $parentData] = $data;
+        [$this->htmlTemplate, $this->textTemplate, $this->context, $this->locale, $parentData] = $data;
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Twig/Mime/TemplatedEmail.php]:
```suggestion
        [$this->htmlTemplate, $this->textTemplate, $this->context, $this->locale, $parentData] = $data;
        $this->locale = $data[5] ?? null;
`````

**Review by nicolas-grekas — COMMENTED** [review]
Here are some suggestions that should help provide some compat with previously serialized payloads

File: src/Symfony/Bridge/Twig/Mime/TemplatedEmail.php (hunk 2 above)
Comment (mkrauser) [reply src/Symfony/Bridge/Twig/Mime/TemplatedEmail.php]: Thank you, but the 5 should be a 4, right?
And is the assignment in the line before still necessary then?

```suggestion
        [$this->htmlTemplate, $this->textTemplate, $this->context, $parentData] = $data;
        $this->locale = $data[4] ?? null;
```

Comment (nicolas-grekas) [reply src/Symfony/Bridge/Twig/Mime/TemplatedEmail.php]: correct it should be 4

**Review by OskarStark — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @mkrauser.
