### PR TITLE
[Console] fix emojis messing up the line width

### LINKED ISSUE #37904: Console with emoji mess up the formatting
**Symfony version(s) affected**: 5.1.3

**Description**  

Emoji mess up the formatting. The border is not even.

**How to reproduce**  

```
protected function execute(InputInterface $input, OutputInterface $output)
{
    $io = new SymfonyStyle($input, $output);
    $io->error("Some error message \u{1F625}");
    return Command::FAILURE;
}
```

Screen shot 2020-08-21 09-02-27

**Possible Solution**  

Something with string length count and encoding 

**Additional context**

### PR DESCRIPTION
**Pull request by MarionLeHerisson**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix https://github.com/symfony/symfony/issues/37904
| License       | MIT

Description
========

The emojis, because they take as much space as two characters, would cause the console to display too many spaces to complete a line, which made it uneven, as described in the issue.

The fix uses the `width` function instead of `strlen`. To answer @ogizanagi's comment, yes it does work with "composed" emojis.

Before : 

image

After : 

image

Other changes
==========

Removed two unused lines of code, the value of `$messageLineLength` was never used.

Note
====
I'd like to add some tests, but I don't know how since I think this depends on console client width ?

Thanks for your reviews :pray:

### CODE REVIEW

**Comment by chalasr** [comment]
Do we really need a new method? Can't we update `strlenWithoutDecoration()` instead? (I may miss some potential issues due to the behavior change.)
The name of the new method does not make it obvious that it is all about strings. 
So if we cannot just update `strlenWithoutDecoration()`, we should try to find a more meaningful name. Perhaps `stringWidthWithoutDecoration()` or similar?

**Comment by MarionLeHerisson** [comment]
Hello @chalasr, thanks for the feedback. Since the method is used in 13 other places in the code, I was afraid it would break something. But after trying it and running the tests, it seems it doesn't :+1:

**Comment by MarionLeHerisson** [comment]
Hello @chalasr, thanks for the feedback. Since the method is used in 13 other places in the code, I was afraid it would break something. But after trying it and running the tests, it seems it doesn't :+1:

File: src/Symfony/Component/Console/Helper/Helper.php [hunk 1]
```diff
@@ -118,7 +119,7 @@ public static function formatMemory(int $memory)
 
     public static function strlenWithoutDecoration(OutputFormatterInterface $formatter, $string)
     {
-        return self::strlen(self::removeDecoration($formatter, $string));
+        return (new UnicodeString(self::removeDecoration($formatter, $string)))->width();
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Helper/Helper.php]: I'd suggest patching the strlen method instead, and to use `UnicodeString` only `if (preg_match('//u', $string))`

**Review by nicolas-grekas — APPROVED** [review]
(I applied my own review comment and fixed a few more things found meanwhile)

**Comment by nicolas-grekas** [comment]
Thank you @MarionLeHerisson.

**Comment by Nyholm** [comment]
I like this feature, however, it caused some regressions. I will revert this an add it as a new feature in 5.3 instead. 

See #40697
