### PR TITLE
[Form] Fix handling of empty_data's \Closure value in Date/Time form types

### LINKED ISSUE #33188: [Form] Cannot use object of type Closure as array
**Symfony version(s) affected**: 4.2.11

**How to reproduce**  

Have type defined like this:

```php
class MyDateAndTimeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('time', TimeType::class, $options);

        $builder->addModelTransformer(new MyDateAndTimeToDateTimeTransformer());
    }

    public function getBlockPrefix()
    {
        return 'data_and_time';
    }
}
```

You get this error when creating the form:

```
Cannot use object of type Closure as array

  at vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/TimeType.php:80
```

The problem is passing options to `$builder->add('time', TimeType::class, $options)` which carries:

```
  "empty_data" => Closure(FormInterface $form) {#2763 ▼
    class: "Symfony\Component\Form\Extension\Core\Type\FormType"
    this: FormType {#2569 …}
    parameters: {▶}
    file: "vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/FormType.php"
    line: "140 to 142"
  }
```

This used to work in 4.1

**Additional context**  
Suspected changeset https://github.com/symfony/symfony/pull/29182.

### PR DESCRIPTION
**Pull request by yceruto**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #33188
| License       | MIT
| Doc PR        | -

Basically this would solve the posibility to pass a `\Closure` to the `empty_data` option for Date/Time form types.

> https://symfony.com/doc/current/reference/forms/types/form.html#empty-data
> If a form is compound, you can set empty_data as an array, object or **closure**. See the [How to Configure empty Data](https://symfony.com/doc/current/form/use_empty_data.html) for a Form Class article for more details about these options.

Also related to https://github.com/symfony/symfony/pull/29182

### CODE REVIEW

File: src/Symfony/Component/Form/Extension/Core/Type/DateTimeType.php [hunk 1]
```diff
@@ -107,7 +107,17 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                 'invalid_message_parameters',
             ]));
 
-            if (isset($emptyData['date'])) {
+            if ($emptyData instanceof \Closure) {
+                $lazyEmptyData = static function ($option) use ($emptyData) {
```
Comment (xabbuh) [inline src/Symfony/Component/Form/Extension/Core/Type/DateTimeType.php]: I was a bit confused why we would define a closure here if we just call it one the next line until I realised that it is reused later on. I think we should move the closure declaration outside the `if` block to avoid this confusion. Having it being used outside the block it is defined in should be avoided.

File: src/Symfony/Component/Form/Extension/Core/Type/DateType.php [hunk 2]
```diff
@@ -81,14 +81,28 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
-            if (isset($emptyData['year'])) {
-                $yearOptions['empty_data'] = $emptyData['year'];
-            }
-            if (isset($emptyData['month'])) {
-                $monthOptions['empty_data'] = $emptyData['month'];
-            }
-            if (isset($emptyData['day'])) {
-                $dayOptions['empty_data'] = $emptyData['day'];
+            if ($emptyData instanceof \Closure) {
+                $lazyEmptyData = static function ($option) use ($emptyData) {
```
Comment (xabbuh) [inline src/Symfony/Component/Form/Extension/Core/Type/DateType.php]: same here

File: src/Symfony/Component/Form/Extension/Core/Type/TimeType.php [hunk 3]
```diff
@@ -76,7 +76,17 @@ public function buildForm(FormBuilderInterface $builder, array $options)
             // so we need to handle the cascade setting here
             $emptyData = $builder->getEmptyData() ?: [];
 
-            if (isset($emptyData['hour'])) {
+            if ($emptyData instanceof \Closure) {
+                $lazyEmptyData = static function ($option) use ($emptyData) {
```
Comment (xabbuh) [inline src/Symfony/Component/Form/Extension/Core/Type/TimeType.php]: and here

**Review by xabbuh — CHANGES_REQUESTED** [review]

**Comment by yceruto** [comment]
@xabbuh done, thanks!

**Comment by yceruto** [comment]
@xabbuh done, thanks!

File: src/Symfony/Component/Form/Extension/Core/Type/DateTimeType.php [hunk 4]
```diff
@@ -126,7 +136,9 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                 'invalid_message_parameters',
             ]));
 
-            if (isset($emptyData['time'])) {
+            if ($emptyData instanceof \Closure) {
```
Comment (xabbuh) [inline src/Symfony/Component/Form/Extension/Core/Type/DateTimeType.php]: What about doing the same as what you did in the `DateType` then?

```php
if ($emptyData instanceof \Closure) {
    $lazyEmptyData = static function ($option) use ($emptyData) {
        return static function (FormInterface $form) use ($emptyData, $option) {
            $emptyData = $emptyData($form->getParent());
            return isset($emptyData[$option]) ? $emptyData[$option] : '';
        };
    };
    $dateOptions['empty_data'] = $lazyEmptyData('date');
} else {
    if (isset($emptyData['date'])) {
        $dateOptions['empty_data'] = $emptyData['date'];
    }

    if (isset($emptyData['time'])) {
        $timeOptions['empty_data'] = $emptyData['time'];
    }
}
```

**Review by HeahDude — APPROVED** [review]

File: src/Symfony/Component/Form/Extension/Core/Type/DateTimeType.php (hunk 4 above)
Comment (HeahDude) [reply src/Symfony/Component/Form/Extension/Core/Type/DateTimeType.php]: To do that the `$timeOptions` initialization should be moved before the first empty data definition.

Comment (HeahDude) [reply src/Symfony/Component/Form/Extension/Core/Type/DateTimeType.php]: I can see there are conflicting comments from Nicolas and Christian, so maybe we should always set `$lazyEmptyData` base on the instance of once, then test if `$lazyEmptyData` is null to define the options.

**Review by fabpot — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @yceruto.
