### PR TITLE
[Serializer] fix support for lazy/unset properties

### LINKED ISSUE #44273: [Serializer] Serializer tries to access initializer property when serializing a Doctrine Proxy object
### Symfony version(s) affected

5.3.11

### Description

After upgrading `symfony/serializer` from `5.3.10` to `5.3.11` Seralizer starts to access special `$initializer<id>` property in proxies generated by Doctrine instead of letting the proxy initialize with actual objects.

### How to reproduce

**Edit:** Use this repository to reproduce: https://github.com/IonBazan/serializer-proxy-bug

When Serializing a Doctrine ODM document with `ReferenceMany` or `ReferenceOne`, `PropertyAccessor` is trying to access a special `$initializer<id>` property.

Create 2 documents and make one of them reference the other. Now try to serialize the referencing document.
Following error should occur:
```
Undefined property: App\Domain\Document\Security\User::$initializer426f5 in /<redacted>/vendor/symfony/property-access/PropertyAccessor.php on line 473
```

```
ErrorException:
User Notice: Undefined property: App\Domain\Document\Security\User::$initializer426f5 in /<redacted>/vendor/symfony/property-access/PropertyAccessor.php on line 473

  at var/cache/dev/doctrine/odm/mongodb/Proxies/MongoDBODMProxies__PM__AppDomainDocumentSecurityUserGenerated0ca55a35e3ea298c1fbe2a3466d2e5dc.php:210
  at MongoDBODMProxies\__PM__\App\Domain\Document\Security\User\Generated0ca55a35e3ea298c1fbe2a3466d2e5dc->__get('initializer426f5')
     (vendor/symfony/property-access/PropertyAccessor.php:473)
  at Symfony\Component\PropertyAccess\PropertyAccessor->readProperty(array(object(Generated0ca55a35e3ea298c1fbe2a3466d2e5dc)), 'initializer426f5', false)
     (vendor/symfony/property-access/PropertyAccessor.php:154)
  at Symfony\Component\PropertyAccess\PropertyAccessor->getValue(object(Generated0ca55a35e3ea298c1fbe2a3466d2e5dc), 'initializer426f5')
     (vendor/symfony/serializer/Normalizer/ObjectNormalizer.php:148)
  at Symfony\Component\Serializer\Normalizer\ObjectNormalizer->getAttributeValue(object(Generated0ca55a35e3ea298c1fbe2a3466d2e5dc), 'initializer426f5', 'json', array('cache_key' => '8bae177454fb7ad4c74be899646036e2', 'circular_reference_limit_counters' => array('00000000046ab22e000000000059cf16' => 1, '00000000046a84a4000000000059cf16' => 1)))
     (vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:179)
  at Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize(object(Generated0ca55a35e3ea298c1fbe2a3466d2e5dc), 'json', array('cache_key' => '8bae177454fb7ad4c74be899646036e2', 'circular_reference_limit_counters' => array('00000000046ab22e000000000059cf16' => 1, '00000000046a84a4000000000059cf16' => 1)))
     (vendor/symfony/serializer/Serializer.php:154)
  at Symfony\Component\Serializer\Serializer->normalize(object(Generated0ca55a35e3ea298c1fbe2a3466d2e5dc), 'json', array('cache_key' => '8bae177454fb7ad4c74be899646036e2', 'circular_reference_limit_counters' => array('00000000046ab22e000000000059cf16' => 1)))
     (vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:207)
  at Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize(object(Log), 'json', array('cache_key' => '8bae177454fb7ad4c74be899646036e2', 'circular_reference_limit_counters' => array('00000000046ab22e000000000059cf16' => 1)))
     (vendor/symfony/serializer/Serializer.php:154)
  at Symfony\Component\Serializer\Serializer->normalize(object(Log), 'json', array())
     (vendor/symfony/serializer/Serializer.php:168)
  at Symfony\Component\Serializer\Serializer->normalize(array(object(Log), object(Log), object(Log), object(Log), object(Log), object(Log), object(Log), object(Log), object(Log), object(Log)), 'json', array())
     (vendor/symfony/serializer/Serializer.php:127)
  at Symfony\Component\Serializer\Serializer->serialize(array(object(Log), object(Log), object(Log), object(Log), object(Log), object(Log), object(Log), object(Log), object(Log), object(Log)), 'json')
     (src/Http/Controller/DashboardController.php:20)
  at App\Http\Controller\DashboardController->__invoke(object(LogRepository), object(Serializer))
     (vendor/symfony/http-kernel/HttpKernel.php:156)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:78)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:199)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:37)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:35)
```

### Possible Solution

_No response_

### Additional Context

_No response_

### LINKED ISSUE #44283: [Serializer]
### Symfony version(s) affected

4.4.35

### Description

After migrating from v4.4.31 to v4.4.35 broke some functionality for private variables.

### How to reproduce

```
        $x = new class
        {
            private ArrayCollection $__loaders;

            public function __setLoaders(ArrayCollection $loaders)
            {
                $this->__loaders = $loaders;
            }

            public function __call($name, $arguments)
            {
                if ($this->__loaders && ($loader = $this->__loaders->get($name)) !== null) {
                    return $loader->load();
                }

                throw new \BadMethodCallException(static::class . '->' . $name . '() method not found');
            }

            public function __get(string $name)
            {
                if ($this->__loaders && $this->__loaders->get($name) !== null) {
                    return $this->__call($name, []);
                }

                if (strpos($name, 'get') !== 0) {
                    $name = 'get' . ucfirst($name);
                }

                return $this->__call($name, []);
            }
        };
        $x->__setLoaders(new ArrayCollection([
            'a' => new class {
                public function load()
                {
                    return 'a';
                }
            },
        ]));
        $x->a(); // works
        $this->serializer->serialize($x, 'json'); // error
```
Occurs an error:
"class@anonymous\/home\/docker\/sample\/src\/Sample.php:51$901a0->get__loaders() method not found"
because in previous version private variables was not supposed to be serialized

### Possible Solution

_No response_

### Additional Context

It most likely related to this [commit](https://github.com/symfony/serializer/commit/36b95b004073cc176031c7cc22c9163cf03910a5) because removed
```
            if (!$isPublic) {
                continue;
            }
```
but you can see [full changes](https://github.com/symfony/serializer/compare/v4.4.31...v4.4.35) for this migration that arises error.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44273 #44283
| License       | MIT
| Doc PR        | -

This basically backports #43469 into 4.4, which is the way to go to fix #44273.
The code that exists to handle uninitialized properties is broken anyway (it was before the recent changes.)

### CODE REVIEW

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 1]
```diff
@@ -181,7 +182,23 @@ public function normalize($object, $format = null, array $context = [])
                 continue;
             }
 
-            $attributeValue = $this->getAttributeValue($object, $attribute, $format, $context);
+            try {
+                $attributeValue = $this->getAttributeValue($object, $attribute, $format, $context);
+            } catch (AccessException $e) {
+                if (sprintf('The property "%s::$%s" is not initialized.', \get_class($object), $attribute) === $e->getMessage()) {
```
Comment (stof) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php:188]: rather than detecting the error message (which could easily be broken if we reword the message, especially as there is no tests covering this), shouldn't we use a subclass of the AccessException instead ?
The rule until now is that the exception _messages_ are not covered by any BC rules and should not be relied upon to catch exceptions.
And this is a cross-component dependency, which would require actually changing the BC rules to allow the current pattern

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php:188]: Yes I agree, that's what we've done on 5.3 already, but introducing a new class in 4.4 doesn't look like a good idea to me...
