### PR TITLE
[Validator] Dump Valid constraints on debug command

### LINKED ISSUE #46544: incomplete result of debug:validator command
### Symfony version(s) affected

5.4.0

### Description

On a just created Sylius project, when I run the command `symfony console debug:validator 'App\Entity\Order\Order'` only 2 constraints have been found.

The XML configuration file contains some other property and class constraints

### How to reproduce

```
composer create-project sylius/sylius-standard acme
cd acme
php bin/console debug:validator 'App\Entity\Order\Order'
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by macintoshplus**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #46544
| License       | MIT

The command `debug:validator` doesn't dump the `Valid` constraints with the default group.

The `Valid` constraints with default group change the property `CascadingStrategy` and the `TraversalStrategy` on property metadata.

This patch adds the `Valid` constraint on debug output if the `CascadingStrategy` is the same as `CASCADE`.

### CODE REVIEW

File: src/Symfony/Component/Validator/Command/DebugCommand.php [hunk 1]
```diff
@@ -168,6 +171,14 @@ private function getPropertyData(ClassMetadataInterface $classMetadata, string $
                     'options' => $this->getConstraintOptions($constraint),
                 ];
             }
+            if (CascadingStrategy::CASCADE === $metadata->getCascadingStrategy()) {
+                $constraint = new Valid([], [], null, TraversalStrategy::IMPLICIT === $metadata->getTraversalStrategy());
+                $data[] = [
+                    'class' => Valid::class,
+                    'groups' => [$constraint::DEFAULT_GROUP],
+                    'options' => $this->getConstraintOptions($constraint),
+                ];
```
Comment (WebMamba) [inline src/Symfony/Component/Validator/Command/DebugCommand.php]: Hey, @macintoshplus thanks for your this PR! It's working great! But are we sure only Valid constraints have the CascadingStrategy::CASCADE? For example, if you create custom constraints that extend the Valid constraint you gonna have this CascadingStrategy::CASCADE, but you don't want to add here the Valid constraint but the custom one.

Comment (macintoshplus) [reply src/Symfony/Component/Validator/Command/DebugCommand.php]: It's true, if you extend `Valid` annotation without changing anything, the behavior is the same as using the `Valid` constraint. And, your custom constraint is changed to `Valid` on debug command. The debug command cannot know the original constraint class name because Symfony has removed it.

See the code https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Validator/Mapping/GenericMetadata.php#L145-L155

But if you add some options or groups, the original constraint is kept by Symfony and can be displayed on the dump command output.

Symfony changes property mapping configuration with `EnableAutoMapping` and `DisableAutoMapping` (I cannot add the constraint in debug command output because the `getAutoMappingStrategy` function is not defined in `MetadataInterface`).

Comment (loic425) [reply src/Symfony/Component/Validator/Command/DebugCommand.php]: @macintoshplus Maybe you can check if the metadata is an instance of ClassMetadata and then getAutoMappingStragegy

Comment (HeahDude) [reply src/Symfony/Component/Validator/Command/DebugCommand.php]: It is the same for `Cascade` and `ClassMetadata` https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Validator/Mapping/ClassMetadata.php#L210

Comment (macintoshplus) [reply src/Symfony/Component/Validator/Command/DebugCommand.php]: @loic425 Yes, I can.

During the investigation (thank @HeahDude), I found some other constraints with a particular behavior.

Without trying to retrieve the original constraint to display, it's possible to display class or property metadata properties differently? How?

**Comment by alexisLefebvre** [comment]
Nitpicking: the title of this PR mentions “constaints” instead of “constraints”.

**Comment by nicolas-grekas** [comment]
What can we do here to unlock the PR?

**Comment by macintoshplus** [comment]
> What can we do here to unlock the PR?

Hi Nicolas, 

Thank you for your interest in this PR.

What way to display the validation constraint that changes parameters and has been removed by Symfony?

I have tried to display `Valid` assert in the dump command but, some others constraint is in the same situation.

IMHO two choices:
- display parameters on top
- display the Symfony native constraints used to change the parameters (my first choice in this PR)

I'm available on Symfony Slack (Jean-Baptiste N.) or Twitter (@jbnahan69) to discuss this in French if you want.

**Comment by macintoshplus** [comment]
Hi @nicolas-grekas, @loic425,

I have changed the property options displayed on debug output.

The 3 options (cascadeStrategy, autoMappingStrategy, traversalStrategy) it's now visible before property validators.

```
Symfony\Component\Validator\Tests\Dummy\DummyClassOne
-----------------------------------------------------

+---------------+----------------------------------------------------+---------+------------------------------------------------------------+
| Property      | Name                                               | Groups  | Options                                                    |
+---------------+----------------------------------------------------+---------+------------------------------------------------------------+
| -             | Symfony\Component\Validator\Constraints\Expression | Default | [                                                          |
|               |                                                    |         |   "expression" => "1 + 1 = 2",                             |
|               |                                                    |         |   "message" => "This value is not valid.",                 |
|               |                                                    |         |   "payload" => null,                                       |
|               |                                                    |         |   "values" => []                                           |
|               |                                                    |         | ]                                                          |
| firstArgument | property options                                   |         | [                                                          |
|               |                                                    |         |   "cascadeStrategy" => "Cascade",                          |
|               |                                                    |         |   "autoMappingStrategy" => "Not supported",                |
|               |                                                    |         |   "traversalStrategy" => "Implicit"                        |
|               |                                                    |         | ]                                                          |
| firstArgument | Symfony\Component\Validator\Constraints\NotBlank   | Default | [                                                          |
|               |                                                    |         |   "allowNull" => false,                                    |
|               |                                                    |         |   "message" => "This value should not be blank.",          |
|               |                                                    |         |   "normalizer" => null,                                    |
|               |                                                    |         |   "payload" => null                                        |
|               |                                                    |         | ]                                                          |
| firstArgument | Symfony\Component\Validator\Constraints\Email      | Default | [                                                          |
|               |                                                    |         |   "message" => "This value is not a valid email address.", |
|               |                                                    |         |   "mode" => null,                                          |
|               |                                                    |         |   "normalizer" => null,                                    |
|               |                                                    |         |   "payload" => null                                        |
|               |                                                    |         | ]                                                          |
+---------------+----------------------------------------------------+---------+------------------------------------------------------------+
```

**Comment by loic425** [comment]
@nicolas-grekas I think we need [this PR first](https://github.com/symfony/symfony/pull/50935) to be sure of the behaviour.

**Comment by macintoshplus** [comment]
@loic425, @nicolas-grekas I have rebased this PR and update tests.

**Comment by nicolas-grekas** [comment]
Thank you @macintoshplus.
