### PR TITLE
[Messenger][AmazonSqs] Add test for default queue_name when not set in DSN path or options

### LINKED ISSUE #44254: [AmazonSqsMessenger] DSN queue name overrides queue_name from options
### Symfony version(s) affected

5.3

### Description

As example I want to configure transport like

(messenger.yaml)
``` 
framework:
    messenger:
        transports:
            queue1:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
            queue2:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                  queue_name: queue2
            queue3:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                  queue_name: queue3
```
and my dsn string looks like 
`https://sqs.us-west-1.amazonaws.com/111111111111/my_queue?access_key=***&secret_key=***`

Currently for this case all 3 transports will work with queue named `my_queue` from dsn string.

I expects what options will override dsn values.

Code: https://github.com/symfony/amazon-sqs-messenger/blob/5.3/Transport/Connection.php#L160-L163

### How to reproduce

Use code config snippet from description and try to work with it.

### Possible Solution

Check if queue_name option passed and use it instead of name from dsn string.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aderiyenko**
| Q             | A
| ------------- | ---
| Branch?       | 5.3 
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44254 
| License       | MIT

Suggesting to change the precedence of `queue_name` option to `config -> DSN -> default ("messages")` instead of current `DSN -> config -> default ("messages")`

### CODE REVIEW

File: src/Symfony/Component/Messenger/Bridge/AmazonSqs/Tests/Transport/ConnectionTest.php [hunk 1]
```diff
@@ -342,7 +355,8 @@ public function testLoggerWithDebugOption()
 
     private function getMockedQueueUrlResponse(): MockResponse
     {
-        return new MockResponse(<<<XML
```
Comment (jderusse) [inline src/Symfony/Component/Messenger/Bridge/AmazonSqs/Tests/Transport/ConnectionTest.php:372]: not related. to be reverted

**Review by jderusse — CHANGES_REQUESTED** [review]
The DSN takes precedence over the options on purpose.

ie. PROD and PRE_PROD share the same configuration (and same `queue_name` in the messenger.yaml) but they use 2 differents DSN to define the targeted queue.

If you want to share the same DSN across different configurations, you can either:
- remove the queue name from the ENV variabnle, in that way, the connection will fallback to the option
- make the queue name part the DSN. ie. `dsn : "%env(MESSENGER_TRANSPORT_DSN)%/my_queue"`

File: src/Symfony/Component/Messenger/Bridge/AmazonSqs/Tests/Transport/ConnectionTest.php (hunk 1 above)
Comment (aderiyenko) [reply src/Symfony/Component/Messenger/Bridge/AmazonSqs/Tests/Transport/ConnectionTest.php:372]: reverted, thanks!

**Comment by aderiyenko** [comment]
Thanks for your review @jderusse !

In this case I'll let the reporter [here](https://github.com/symfony/symfony/issues/44254) know to just remove the queue name from the DSN and specify it explicitly in the options. 

And then I just left a test for the default message name == 'messages' as I haven't found such a test in the suite.

LMK if it makes sense and thanks again!

**Comment by nicolas-grekas** [comment]
Thank you @aderiyenko.
