### PR TITLE
[PropertyInfo] PhpStanExtractor namespace missmatch issue

### LINKED ISSUE #44431: [PropertyInfo] PhpStan FQSEN error
### Symfony version(s) affected

5.4, 6.*

### Description

PhpStanExtractor incorrect detect class with different namespace. PhpDocExtractor work correct.

#40457

### How to reproduce

```php
<?php

namespace {
    require_once __DIR__ . '/vendor/autoload.php';

    use Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor;
    use Symfony\Component\PropertyInfo\Extractor\PhpStanExtractor;

    $phpDocExtractor = new PhpDocExtractor();
    $phpStanExtractor = new PhpStanExtractor();


    dump(
        $phpDocTypes = $phpDocExtractor->getTypes(B\Dummy::class, 'property'),
        $phpStanTypes = $phpStanExtractor->getTypes(B\Dummy::class, 'property')
    );

    assert($phpStanTypes[0]->getClassName() === 'A\Property');
    assert($phpDocTypes[0]->getClassName() === $phpStanTypes[0]->getClassName());
}


namespace A {
    class Property {

    }

    class Dummy {
        /**
         * @var Property
         */
        public $property;
    }
}

namespace B {
    class Dummy extends \A\Dummy {

    }
}

```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Korbeil**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44431 
| License       | MIT
| Doc PR        | N/A

Thanks to @isypov-andrey report, we found out an issue with namespace matching and the PhpStanExtractor.
In this PR I'm fixing this issue.

- [x] Test to validate the issue
- [x] Fix

### CODE REVIEW

File: src/Symfony/Component/PropertyInfo/Extractor/PhpStanExtractor.php [hunk 1]
```diff
@@ -226,11 +229,11 @@ private function getDocBlockFromProperty(string $class, string $property): ?PhpD
         $phpDocNode = $this->phpDocParser->parse($tokens);
         $tokens->consumeTokenType(Lexer::TOKEN_END);
 
-        return $phpDocNode;
+        return [$phpDocNode, $reflectionProperty->getDeclaringClass()->name];
```
Comment (nicolas-grekas) [inline src/Symfony/Component/PropertyInfo/Extractor/PhpStanExtractor.php]: `$reflectionProperty->class` (same below)

File: src/Symfony/Component/PropertyInfo/PhpStan/NameScopeFactory.php [hunk 2]
```diff
@@ -20,16 +20,19 @@
...
-        [$namespace, $uses] = $this->extractFromFullClassName($reflection);
+        $declaringClassName = $declaringClassName ?? $calledClassName;
 
-        $uses = array_merge($uses, $this->collectUses($reflection));
+        $path = explode('\\', $calledClassName);
+        $calledClassName = array_pop($path);
 
-        return new NameScope($className, $namespace, $uses);
+        $declaringReflection = new \ReflectionClass($declaringClassName);
+        $path = explode('\\', $declaringClassName);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/PropertyInfo/PhpStan/NameScopeFactory.php]: what is this line for?

Comment (Korbeil) [reply src/Symfony/Component/PropertyInfo/PhpStan/NameScopeFactory.php]: useless indeed :+1:

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @Korbeil.
