### PR TITLE
[DI] Fix CheckTypeDeclarationPass

### LINKED ISSUE #35863: Symfony `lint:container` fails to match callable created by factory
**Symfony version(s) affected**: 4.4.4

**Description**  
When calling the `lint:container` on _complex_ setup of services when one is creating `callable` that is passed as argument to another it fails in strange way.

**How to reproduce**  
```bash
bin/console lint:container

In CheckTypeDeclarationsPass.php line 263:

  Invalid definition for service "Some\Service": argument 1 of "GuzzleHttp\HandlerStack::push" accepts "callable", "call
  able" passed.
```

```xml
        <service id="Some\Service">
            <argument type="service" id="guzzle_client"/>
        </service>

        <service id="guzzle_client" class="GuzzleHttp\Client">
            <argument type="collection">
                <argument key="handler" type="service" id="some.guzzle.stack" />
            </argument>
        </service>

        <service id="some.guzzle.stack" class="GuzzleHttp\HandlerStack">
            <factory class="GuzzleHttp\HandlerStack" method="create" />
            <call method="push">
                <argument type="service" id="some.guzzle.logger" />
            </call>
        </service>

        <service id="some.guzzle.logger" class="callable">
            <factory class="Guzzle\Middleware\JsonFormatterMiddleware" method="log" />
            <argument type="service" id="some.logger" />
            <argument>100</argument>
        </service>

        <service id="some.logger" class="Symfony\Bridge\Monolog\Logger">
            <argument index="0">log_name</argument>
            <call method="pushHandler">
                <argument type="service" id="logger_handler" />
            </call>
        </service>
```
Factory class:
```php
class JsonFormatterMiddleware
{
    public static function log(LoggerInterface $logger, string $logLevel = LogLevel::INFO): callable
    {
        return static function (callable $handler) use ($logger, $logLevel) {
            return static function ($request, array $options) use ($handler, $logger, $logLevel) {
                return $handler($request, $options)->then(
                    static function ($response) use ($logger, $request, $logLevel) {
                        $logger->log($logLevel, static::getMessage($request));

                        return $response;
                    },
                    static function ($reason) use ($logger, $request) {
                        $logger->log(
                            $reason instanceof RequestException ? LogLevel::ERROR : LogLevel::NOTICE,
                            static::getMessage($request)
                        );

                        return rejection_for($reason);
                    }
                );
            };
        };
    }

    private static function getMessage(RequestInterface $request): string
    {
        return \trim($request->getMethod().' '.$request->getRequestTarget()).' HTTP/'.$request->getProtocolVersion();
    }
}
```

**Possible Solution**  
`lint:container` call should not report this as issue or should be able to determine that `callable` from factory call is `callable`.

**Additional context**  
In overall that setup works well since really old versions of Symfony, the service & callables are created, handled & proceed correctly, without any issue.

### PR DESCRIPTION
**Pull request by guillbdx**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35863 and #35972
| License       | MIT
| Doc PR        | 

Bug 1: The lint container threw an error if a class buit with a factory was declared as callable while this factory method returne a callabe (#35863)

Bug 2: Sodium Exception was not caught in the CheckTypeDeclarationsPass. We have extended the exception caught to \Exception, instead of EnvNotFoundException and RuntimeException only.

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php [hunk 1]
```diff
@@ -242,7 +241,7 @@ private function checkType(Definition $checkedDefinition, $value, \ReflectionPar
             return;
         }
 
-        if ('callable' === $type && (\Closure::class === $class || method_exists($class, '__invoke'))) {
+        if ('callable' === $type && (\Closure::class === $class || method_exists($class, '__invoke') || 'callable' === $class)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php]: let's move it first

**Review by nicolas-grekas — COMMENTED** [review]
Thanks.
The 'iterable' case looks similar, we should add `'iterable' === $class` there also

File: src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php (hunk 1 above)
Comment (stloyd) [inline src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php]:
```suggestion
        if (\in_array($type, ['callable', 'callable'], true) && (\Closure::class === $class || method_exists($class, '__invoke'))) {
```

Comment (stloyd) [inline src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php]:
```suggestion
        if (\in_array($class, ['callable', 'callback', 'iterable'], true) {
            return;
        }

        if ('callable' === $type && (\Closure::class === $class || method_exists($class, '__invoke'))) {
```

**Review by stloyd — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php (hunk 1 above)
Comment (guillbdx) [reply src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php]: Done.

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php]: not the same...

File: src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php [hunk 2]
```diff
@@ -249,7 +249,11 @@ private function checkType(Definition $checkedDefinition, $value, \ReflectionPar
             return;
         }
 
-        if ('iterable' === $type && (\is_array($value) || is_subclass_of($class, \Traversable::class))) {
+        if ('iterable' === $type && (\is_array($value) || 'iterable' === $class || is_subclass_of($class, \Traversable::class))) {
+            return;
+        }
+
+        if ('array' === $type && ('array' === $class)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php]: let's have a generic case the: `if ($type === $class)`

File: src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php [hunk 3]
```diff
@@ -249,7 +249,11 @@ private function checkType(Definition $checkedDefinition, $value, \ReflectionPar
             return;
         }
 
-        if ('iterable' === $type && (\is_array($value) || is_subclass_of($class, \Traversable::class))) {
+        if ('iterable' === $type && (\is_array($value) || 'iterable' === $class || is_subclass_of($class, \Traversable::class))) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php]: the new check would be covered by the suggestion I made in the other comment + this should be replaced by `'array' === $class`, which is missing right now.

**Comment by guillbdx** [comment]
> Thanks.
> The 'iterable' case looks similar, we should add `'iterable' === $class` there also

Done, with a few minor additions.

**Review by nicolas-grekas — APPROVED** [review]

**Review by stloyd — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @guillbdx.

**Comment by Antek013** [comment]
I had the same problem with 4.4. 
I created a local repository with secrets then i push on the server and when i done a cache:clear i get the same error. 

!!    keypair size should be SODIUM_CRYPTO_BOX_KEYPAIRBYTES bytes
