### PR TITLE
[DoctrineBridge] do not depend on the QueryBuilder from the ORM

### LINKED ISSUE #34581: 4.4 and MongoDB ODM DoctrineType
**Symfony version(s) affected**: 4.4 (4.3 was ok)

**Description**  
Argument 1 passed to Symfony\Bridge\Doctrine\Form\Type\DoctrineType::getQueryBuilderPartsForCachingHash() must be an instance of Doctrine\ORM\QueryBuilder, instance of Doctrine\ODM\MongoDB\Query\Builder given, called in /usr/local/www/vendor/symfony/doctrine-bridge/Form/Type/DoctrineType.php on line 125

**How to reproduce**  
Create FormType with ODM entity extending DoctrineType

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34581
| License       | MIT
| Doc PR        |

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/Form/Type/EntityType.php [hunk 1]
```diff
@@ -68,10 +68,12 @@ public function getBlockPrefix()
      * We consider two query builders with an equal SQL string and
      * equal parameters to be equal.
      *
+     * @param QueryBuilder $queryBuilder
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Form/Type/EntityType.php]: should we add `|Builder` from the ODM to ensure someone else won't readd the type later on? (same above)

Comment (stof) [reply src/Symfony/Bridge/Doctrine/Form/Type/EntityType.php]: well, the thing is, the EntityType is specific to ORM. But DoctrineType is not.

Comment (HeahDude) [reply src/Symfony/Bridge/Doctrine/Form/Type/EntityType.php]: Then we should update the phpdoc in the `DoctrineType` too, and throw an exception in the EntityType to ensure the query builder class is from ORM. What about a test?

Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/Form/Type/EntityType.php]: I agree with @HeahDude - the test should reject anything that is not a `QueryBuilder` of course.
At least we need something that will prevent us from adding the type by mistake again :)

Comment (kasp3r) [reply src/Symfony/Bridge/Doctrine/Form/Type/EntityType.php]: Can you please release this fix and decide later on other stuff, because this bug is breaking my application. Thanks.

Comment (xabbuh) [reply src/Symfony/Bridge/Doctrine/Form/Type/EntityType.php]: > Then we should update the phpdoc in the DoctrineType too, and throw an exception in the EntityType to ensure the query builder class is from ORM. What about a test?

This is already done by the options resolver. I don't think we need more.

> At least we need something that will prevent us from adding the type by mistake again

I added a comment in the docblock

Comment (HeahDude) [reply src/Symfony/Bridge/Doctrine/Form/Type/EntityType.php]: Fair enough, but the normalizer handling the exception might be overridden by `EntityType` children. So I would still enforce the check inside the methods `getLoader()` and `getQueryBuilderPartsForCachingHash` of the `EntityType`.

Also we need another PR targeting 5.0 because the type hint is also present for the abstract method `getLoader` there, do you want me to open it @xabbuh or can you take care of that too? Thanks

Comment (xabbuh) [reply src/Symfony/Bridge/Doctrine/Form/Type/EntityType.php]: fair enough, checks added in both methods

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.
