### PR TITLE
[Validator] Fix comparison validator crash on extreme dates

### LINKED ISSUE #63266: [Validator] Comparison Validator breaks when handling extreme dates
### Symfony version(s) affected

7.4.5

### Description

I'm trying to prevent users from entering values into DateTimeImmutable annotated fields like: `185449-12-31 23:00:00.000000` using a `LessThanOrEqual` constraint.

Sadly this causes exceptions cause it doesn't seem to handle these kinds of dates well.

### How to reproduce

Try to Validate the mentioned date with a less than validator

### Possible Solution

_No response_

### Additional Context

```
{\n
    "@context": "/contexts/Error",\n
    "@id": "/errors/500",\n
    "@type": "Error",\n
    "title": "An error occurred",\n
    "detail": "Failed to parse time string (185449-12-31 23:00:00.000000) at position 13 (2): Double time specification",\n
    "status": 500,\n
    "type": "/errors/500",\n
    "description": "Failed to parse time string (185449-12-31 23:00:00.000000) at position 13 (2): Double time specification",\n
    "trace": [\n
        {\n
            "file": "/app/vendor/symfony/validator/ConstraintValidator.php",\n
            "line": 79,\n
            "function": "__construct",\n
            "class": "DateTimeImmutable",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/validator/Constraints/AbstractComparisonValidator.php",\n
            "line": 74,\n
            "function": "formatValue",\n
            "class": "Symfony\\Component\\Validator\\ConstraintValidator",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/validator/Validator/RecursiveContextualValidator.php",\n
            "line": 748,\n
            "function": "validate",\n
            "class": "Symfony\\Component\\Validator\\Constraints\\AbstractComparisonValidator",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/validator/Validator/RecursiveContextualValidator.php",\n
            "line": 593,\n
            "function": "validateInGroup",\n
            "class": "Symfony\\Component\\Validator\\Validator\\RecursiveContextualValidator",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/validator/Validator/RecursiveContextualValidator.php",\n
            "line": 506,\n
            "function": "validateGenericNode",\n
            "class": "Symfony\\Component\\Validator\\Validator\\RecursiveContextualValidator",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/validator/Validator/RecursiveContextualValidator.php",\n
            "line": 297,\n
            "function": "validateClassNode",\n
            "class": "Symfony\\Component\\Validator\\Validator\\RecursiveContextualValidator",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/validator/Validator/RecursiveContextualValidator.php",\n
            "line": 647,\n
            "function": "validateObject",\n
            "class": "Symfony\\Component\\Validator\\Validator\\RecursiveContextualValidator",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/validator/Validator/RecursiveContextualValidator.php",\n
            "line": 506,\n
            "function": "validateGenericNode",\n
            "class": "Symfony\\Component\\Validator\\Validator\\RecursiveContextualValidator",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/validator/Validator/RecursiveContextualValidator.php",\n
            "line": 297,\n
            "function": "validateClassNode",\n
            "class": "Symfony\\Component\\Validator\\Validator\\RecursiveContextualValidator",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/validator/Validator/RecursiveContextualValidator.php",\n
            "line": 127,\n
            "function": "validateObject",\n
            "class": "Symfony\\Component\\Validator\\Validator\\RecursiveContextualValidator",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/validator/Validator/RecursiveValidator.php",\n
            "line": 81,\n
            "function": "validate",\n
            "class": "Symfony\\Component\\Validator\\Validator\\RecursiveContextualValidator",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/api-platform/core/src/Symfony/Validator/Validator.php",\n
            "line": 56,\n
            "function": "validate",\n
            "class": "Symfony\\Component\\Validator\\Validator\\RecursiveValidator",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/api-platform/core/src/Symfony/Validator/State/ValidateProvider.php",\n
            "line": 42,\n
            "function": "validate",\n
            "class": "ApiPlatform\\Symfony\\Validator\\Validator",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/api-platform/core/src/Symfony/Security/State/AccessCheckerProvider.php",\n
            "line": 62,\n
            "function": "provide",\n
            "class": "ApiPlatform\\Symfony\\Validator\\State\\ValidateProvider",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/api-platform/core/src/Symfony/Validator/State/ParameterValidatorProvider.php",\n
            "line": 101,\n
            "function": "provide",\n
            "class": "ApiPlatform\\Symfony\\Security\\State\\AccessCheckerProvider",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/api-platform/core/src/State/Provider/ParameterProvider.php",\n
            "line": 102,\n
            "function": "provide",\n
            "class": "ApiPlatform\\Symfony\\Validator\\State\\ParameterValidatorProvider",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/api-platform/core/src/State/Provider/ContentNegotiationProvider.php",\n
            "line": 56,\n
            "function": "provide",\n
            "class": "ApiPlatform\\State\\Provider\\ParameterProvider",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/api-platform/core/src/Symfony/Controller/MainController.php",\n
            "line": 94,\n
            "function": "provide",\n
            "class": "ApiPlatform\\State\\Provider\\ContentNegotiationProvider",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/http-kernel/HttpKernel.php",\n
            "line": 183,\n
            "function": "__invoke",\n
            "class": "ApiPlatform\\Symfony\\Controller\\MainController",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/http-kernel/HttpKernel.php",\n
            "line": 76,\n
            "function": "handleRaw",\n
            "class": "Symfony\\Component\\HttpKernel\\HttpKernel",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/http-kernel/Kernel.php",\n
            "line": 193,\n
            "function": "handle",\n
            "class": "Symfony\\Component\\HttpKernel\\HttpKernel",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/http-kernel/HttpKernelBrowser.php",\n
            "line": 62,\n
            "function": "handle",\n
            "class": "Symfony\\Component\\HttpKernel\\Kernel",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/framework-bundle/KernelBrowser.php",\n
            "line": 180,\n
            "function": "doRequest",\n
            "class": "Symfony\\Component\\HttpKernel\\HttpKernelBrowser",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/browser-kit/AbstractBrowser.php",\n
            "line": 398,\n
            "function": "doRequest",\n
            "class": "Symfony\\Bundle\\FrameworkBundle\\KernelBrowser",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/zenstruck/browser/src/Browser/Session/Driver/BrowserKitDriver.php",\n
            "line": 88,\n
            "function": "request",\n
            "class": "Symfony\\Component\\BrowserKit\\AbstractBrowser",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/zenstruck/browser/src/Browser/Session/Driver/BrowserKitDriver.php",\n
            "line": 712,\n
            "function": "{closure:Zenstruck\\Browser\\Session\\Driver\\BrowserKitDriver::request():87}",\n
            "class": "Zenstruck\\Browser\\Session\\Driver\\BrowserKitDriver",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/zenstruck/browser/src/Browser/Session/Driver/BrowserKitDriver.php",\n
            "line": 87,\n
            "function": "wrapRequest",\n
            "class": "Zenstruck\\Browser\\Session\\Driver\\BrowserKitDriver",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/zenstruck/browser/src/Browser/Session.php",\n
            "line": 91,\n
            "function": "request",\n
            "class": "Zenstruck\\Browser\\Session\\Driver\\BrowserKitDriver",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/zenstruck/browser/src/Browser/KernelBrowser.php",\n
            "line": 312,\n
            "function": "request",\n
            "class": "Zenstruck\\Browser\\Session",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/zenstruck/browser/src/Browser/KernelBrowser.php",\n
            "line": 338,\n
            "function": "request",\n
            "class": "Zenstruck\\Browser\\KernelBrowser",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/tests/FunctionalTests/BoxOrder/CreateBoxOrderTest.php",\n
            "line": 2990,\n
            "function": "post",\n
            "class": "Zenstruck\\Browser\\KernelBrowser",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/bin/.phpunit/phpunit-12-0/src/Framework/TestCase.php",\n
            "line": 1326,\n
            "function": "testNonPrivateSignatureWithChangeInvalidDate",\n
            "class": "App\\Tests\\FunctionalTests\\BoxOrder\\CreateBoxOrderTest",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/bin/.phpunit/phpunit-12-0/src/Framework/TestCase.php",\n
            "line": 519,\n
            "function": "runTest",\n
            "class": "PHPUnit\\Framework\\TestCase",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/bin/.phpunit/phpunit-12-0/src/Framework/TestRunner/TestRunner.php",\n
            "line": 99,\n
            "function": "runBare",\n
            "class": "PHPUnit\\Framework\\TestCase",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/bin/.phpunit/phpunit-12-0/src/Framework/TestCase.php",\n
            "line": 359,\n
            "function": "run",\n
            "class": "PHPUnit\\Framework\\TestRunner",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/bin/.phpunit/phpunit-12-0/src/Framework/TestSuite.php",\n
            "line": 374,\n
            "function": "run",\n
            "class": "PHPUnit\\Framework\\TestCase",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/bin/.phpunit/phpunit-12-0/src/Framework/TestSuite.php",\n
            "line": 374,\n
            "function": "run",\n
            "class": "PHPUnit\\Framework\\TestSuite",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/bin/.phpunit/phpunit-12-0/src/TextUI/TestRunner.php",\n
            "line": 64,\n
            "function": "run",\n
            "class": "PHPUnit\\Framework\\TestSuite",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/bin/.phpunit/phpunit-12-0/src/TextUI/Application.php",\n
            "line": 229,\n
            "function": "run",\n
            "class": "PHPUnit\\TextUI\\TestRunner",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/bin/.phpunit/phpunit-12-0/phpunit",\n
            "line": 104,\n
            "function": "run",\n
            "class": "PHPUnit\\TextUI\\Application",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php",\n
            "line": 460,\n
            "function": "include"\n
        },\n
        {\n
            "file": "/app/vendor/symfony/phpunit-bridge/bin/simple-phpunit",\n
            "line": 13,\n
            "function": "require"\n
        },\n
        {\n
            "file": "/app/vendor/bin/simple-phpunit",\n
            "line": 119,\n
            "function": "include"\n
        }\n
    ]\n
}
```

### PR DESCRIPTION
**Pull request by lacatoire**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #63266
| License       | MIT

When using a `LessThanOrEqual` constraint on a `DateTimeImmutable` field with an extreme date (e.g. year 185449), the validator throws an unhandled `\Exception` ("Failed to parse time string") instead of producing a validation violation.

The crash occurs in `ConstraintValidator::formatValue()` which re-creates a `DateTimeImmutable` from the formatted string to normalize the timezone for `IntlDateFormatter`. Extreme years produce strings that PHP's date parser cannot handle.

This PR wraps the `DateTimeImmutable` construction in a try/catch and falls back to the simple `Y-m-d H:i:s` format when parsing fails.

### CODE REVIEW

File: src/Symfony/Component/Validator/ConstraintValidator.php [hunk 1]
```diff
@@ -76,10 +76,14 @@ protected function formatValue(mixed $value, int $format = 0): string
             if (class_exists(\IntlDateFormatter::class)) {
                 $formatter = new \IntlDateFormatter(\Locale::getDefault(), \IntlDateFormatter::MEDIUM, \IntlDateFormatter::SHORT, 'UTC');
 
-                return $formatter->format(new \DateTimeImmutable(
-                    $value->format('Y-m-d H:i:s.u'),
-                    new \DateTimeZone('UTC')
-                ));
+                try {
+                    return $formatter->format(new \DateTimeImmutable(
+                        $value->format('Y-m-d H:i:s.u'),
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/ConstraintValidator.php]:
```suggestion
                        ($value->format('y') > 0 ? '+' : '').$value->format('Y-m-d H:i:s.u'),
```

according to https://github.com/doctrine/dbal/issues/7307#issuecomment-3860586618 this should be enough to make it work

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @lacatoire.
