### PR TITLE
[Translation][Lokalise] fix "Project too big for sync export"

### LINKED ISSUE #62207: [Translations] Lokalize - "Project too big for sync export. Please use our async export endpoint instead
### Symfony version(s) affected

6.4

### Description

When using the command `symfony console translation:pull loco` to sync my project translations files with Lokalize, I've now the following error : `  Unable to export translations from Lokalise: "{"error":{"message":"Project too big for sync export. Please use our async export endpoint instead. (\/files\/async-download)","code":413}}".`

### How to reproduce

Have Lokalize with hundreds of translation keys and run the command "symfony console translation:pull loco"

### Possible Solution

Increase the limit, which seems so low to me, or offer an alternative via a command.

It's possible to go directly through the Lokalize website and build it ourselves, but that's not ideal, especially when the expected format differs.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by santysisi**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62207
| License       | MIT

This fix follows this [recommendation](https://github.com/symfony/symfony/issues/62207#issuecomment-3461150462)

Since this fix adds a new request for a different path, I'm not sure whether to use branch 6.4 or perhaps 8.1. Please let me know.

This fix requires the `zip` extension because the returned file is a ZIP archive, and this extension is needed to extract the contents. This fix does not add that extension as a dependency; instead, it only uses `extension_loaded` to check if it is loaded in the project.

### CODE REVIEW

**Comment by santysisi** [comment]
Status: needs work

Its necessary add new tests for the new request.

I tested this solution with a test account and a very simple example.

I will wait for @bastien70's confirmation that it works in his environment before add the new tests.

**Comment by bastien70** [comment]
Hello, it works! Congratulations et thank you! :)

**Comment by santysisi** [comment]
Status: needs review

Bastien has already checked this solution in his environment (Thanks Bastien for the check!), and the test has been added.

Edit: I believe the errors are not relevant in the context of the PR

File: src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php [hunk 1]
```diff
@@ -176,6 +188,109 @@ private function exportFiles(array $locales, array $domains): array
...
+                $downloadUrl = $process['details']['download_url'];
+                break;
+            }
+            ++$attempt;
+            usleep(500000 * $attempt);
+        }
+
+        $newfile = \sprintf('%s%s%s.zip', sys_get_temp_dir(), \DIRECTORY_SEPARATOR, uniqid());
+        $extractPath = \sprintf('%s%s%s', sys_get_temp_dir(), \DIRECTORY_SEPARATOR, uniqid());
+        if (!copy($downloadUrl, $newfile)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php]: this should use the http-client instead of the http stream wrapper that copy uses internally

File: src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php [hunk 2]
```diff
@@ -176,6 +188,109 @@ private function exportFiles(array $locales, array $domains): array
...
+                }
+            } finally {
+                $zip->close();
+            }
+
+            $fileContents = $this->getFileContents($extractPath);
+
+            // Lokalise returns languages with "-" separator, we need to reformat them to "_" separator.
+            /** @var array<array-key, array-key> $reformattedLanguages */
+            $reformattedLanguages = array_map(function ($language) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php]:
```suggestion
            $reformattedLanguages = array_map(static fn ($language) => 
```

File: src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php]: if you want to write directly to the target file, use the `buffer` option BTW

File: src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php [hunk 3]
```diff
@@ -31,6 +32,10 @@
 final class LokaliseProvider implements ProviderInterface
 {
     private const LOKALISE_GET_KEYS_LIMIT = 5000;
+    private const PROJECT_TOO_BIG_STATUS_CODE = 413;
+    /** @var list<string> */
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php]: this is not needed

File: src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php [hunk 4]
```diff
@@ -165,6 +170,13 @@ private function exportFiles(array $locales, array $domains): array
         }
 
         if (200 !== $response->getStatusCode()) {
+            if (($errorCode = $responseContent['error']['code'] ?? null) && self::PROJECT_TOO_BIG_STATUS_CODE === $errorCode) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php]:
```suggestion
            if (self::PROJECT_TOO_BIG_STATUS_CODE !== ($responseContent['error']['code'] ?? null)) {
                throw ...
```

File: src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php [hunk 5]
```diff
@@ -176,6 +188,113 @@ private function exportFiles(array $locales, array $domains): array
...
+            $process = $response->toArray()['process'];
+            if (\in_array($process['status'], self::FAILED_PROCESS_STATUS, true)) {
+                throw new ProviderException(\sprintf('Unable to export translations from Lokalise: "%s".', $response->getContent(false)), $response);
+            }
+            if (self::SUCESS_PROCESS_STATUS === $process['status']) {
+                $downloadUrl = $process['details']['download_url'];
+                break;
+            }
+            ++$attempt;
+            usleep(500000 * $attempt);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php]: Is this retry strategy recommended anywhere? Why not just hit every 500ms without increasing the delay?

File: src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php [hunk 6]
```diff
@@ -176,6 +188,113 @@ private function exportFiles(array $locales, array $domains): array
...
+        }
+
+        $response = $this->client->request('GET', $downloadUrl, ['buffer' => true]);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php]: no need to buffer since we write by chunk:
```suggestion
        $response = $this->client->request('GET', $downloadUrl, ['buffer' => false]);
```

(the alternative would be to pass a file handler instead of a boolean, then wait for the last chunk below, but it's also fine as you wrote it)

File: src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php [hunk 7]
```diff
@@ -176,6 +188,113 @@ private function exportFiles(array $locales, array $domains): array
...
+        if (200 !== $response->getStatusCode()) {
+            throw new ProviderException(\sprintf('Unable to download translations file from Lokalise: "%s".', $response->getContent(false)), $response);
+        }
+        $newfile = \sprintf('%s%s%s.zip', sys_get_temp_dir(), \DIRECTORY_SEPARATOR, uniqid());
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php]:
```suggestion
        $zipFile = tempnam(sys_get_temp_dir(), 'lokalise');
        $extractPath = $zipFile.'.dir';
```

File: src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php [hunk 8]
```diff
@@ -176,6 +188,113 @@ private function exportFiles(array $locales, array $domains): array
...
+        $extractPath = \sprintf('%s%s%s', sys_get_temp_dir(), \DIRECTORY_SEPARATOR, uniqid());
+        try {
+            $fileHandler = fopen($newfile, 'w');
+            foreach ($this->client->stream($response) as $chunk) {
+                fwrite($fileHandler, $chunk->getContent());
+            }
+            fclose($fileHandler);
+
+            $zip = new \ZipArchive();
+            if (!$zip->open($newfile, \ZipArchive::CREATE)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php]:
```suggestion
            if (!$zip->open($zipFile)) {
```

File: src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php [hunk 9]
```diff
@@ -176,6 +188,113 @@ private function exportFiles(array $locales, array $domains): array
...
+                throw new LogicException(\sprintf('failed to open zip file "%s".', $newfile));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php]: same below:
```suggestion
                throw new LogicException(\sprintf('Failed to open zip file "%s".', $zipFile));
```

File: src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php [hunk 10]
```diff
@@ -176,6 +188,113 @@ private function exportFiles(array $locales, array $domains): array
...
+    }
+
+    private function getFileContents(string $dir, string $baseDir = ''): array
+    {
+        $fileContents = [];
+        foreach (scandir($dir) as $filename) {
+            if (\in_array($filename, ['.', '..'])) {
+                continue;
+            }
+            $path = \sprintf('%s%s%s', $dir, \DIRECTORY_SEPARATOR, $filename);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php]:
```suggestion
            $path = $dir.'/'.$filename;
```

File: src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php [hunk 11]
```diff
@@ -176,6 +188,113 @@ private function exportFiles(array $locales, array $domains): array
...
+            unlink($newfile);
+            $this->removeDir($extractPath);
+        }
+    }
+
+    private function getFileContents(string $dir, string $baseDir = ''): array
+    {
+        $fileContents = [];
+        foreach (scandir($dir) as $filename) {
+            if (\in_array($filename, ['.', '..'])) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php]:
```suggestion
            if (\in_array($filename, ['.', '..'], true)) {
```

File: src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php [hunk 12]
```diff
@@ -176,6 +188,113 @@ private function exportFiles(array $locales, array $domains): array
...
+                continue;
+            }
+            $path = \sprintf('%s%s%s', $dir, \DIRECTORY_SEPARATOR, $filename);
+            if (is_dir($path)) {
+                $fileContents = array_merge($fileContents, $this->getFileContents($path, $filename));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php]: Let's change the implementation of the method and let's not pretend this can handle arbitrary recursive unzipped content
we can do a two levels read of the dir: level 1 = languages, str_replace included, level 2 = content

**Comment by nicolas-grekas** [comment]
Thank you @santysisi.

File: src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php [hunk 13]
```diff
@@ -176,6 +187,115 @@ private function exportFiles(array $locales, array $domains): array
...
+            $response = $this->client->request('GET', \sprintf('processes/%s', $processId));
+            $process = $response->toArray()['process'];
+            if (\in_array($process['status'], self::FAILED_PROCESS_STATUS, true)) {
+                throw new ProviderException(\sprintf('Unable to export translations from Lokalise: "%s".', $response->getContent(false)), $response);
+            }
+            if (self::SUCESS_PROCESS_STATUS === $process['status']) {
+                $downloadUrl = $process['details']['download_url'];
+                break;
+            }
+            usleep(500000);
```
Comment (xabbuh) [inline src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php:221]: Shouldn’t we have some kind of timeout in case the API never responds with any of the codes we use to detect success and failure?
