### PR TITLE
[FrameworkBundle] Fix CommandDataCollector is always registered

### LINKED ISSUE #52210: Help Wanted: fix failure on WebProfilerBundle 5.4 loaded with higest deps
On 5.4, we have a failure to fix:
https://github.com/symfony/symfony/actions/runs/6590102626/job/17912208613#step:7:393

I can reproduce it by going into the `src/Symfony/Bundle/WebProfilerBundle` folder on branch 5.4, then running composer up and
`SYMFONY_DEPRECATIONS_HELPER=weak ../../../../phpunit --filter testPanelActionWithLatestToken$`

Help welcome to figure out the issue and fix it!

### PR DESCRIPTION
**Pull request by smnandre**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #52210 
| License       | MIT

Another attempt at fixing #52210, allowing to revert #52218 and leave the conflict constraints untouched

CommandDataCollector was always registered, and not always removed from the container when not needed/invalid.

### CODE REVIEW

**Comment by smnandre** [comment]
cc @nicolas-grekas

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/console_debug.php [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+ */
+
+namespace Symfony\Component\DependencyInjection\Loader\Configurator;
+
+use Symfony\Component\Console\DataCollector\CommandDataCollector;
+
+return static function (ContainerConfigurator $container) {
+    $container->services()
+        ->set('.data_collector.command', CommandDataCollector::class)
+        ->tag('data_collector', ['template' => '@WebProfiler/Collector/command.html.twig', 'id' => 'command', 'priority' => 335])
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/console_debug.php]:
```suggestion
            ->tag('data_collector', ['template' => '@WebProfiler/Collector/command.html.twig', 'id' => 'command', 'priority' => 335])
```

**Review by nicolas-grekas — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thanks @smnandre

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 2]
```diff
@@ -922,7 +923,7 @@ private function registerProfilerConfiguration(array $config, ContainerBuilder $
             $container->removeDefinition('console_profiler_listener');
         }
 
-        if (!class_exists(CommandDataCollector::class)) {
+        if (!$container->getParameter('kernel.debug') || !class_exists(CliRequest::class) || !class_exists(CommandDataCollector::class)) {
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:926]: why this check for kernel.debug ? If you enable the profiler in non-debug mode (for instance in tests), you will need this.

Comment (smnandre) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:926]: Good question, i’ll digg tomorrow

Comment (xabbuh) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:926]: This line will also be reverted in #52274.

Comment (smnandre) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:926]: Let's continue discussion (or stop it) on #52274  then

Comment (smnandre) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:926]: Found it: it was because then (non-debug mode), there is something not working, but this is not directly related to the composer conflit, and i'll open a dedicated issue.
