### PR TITLE
[Security][Ldap] Fixed issue with password attribute containing an array of values.

### LINKED ISSUE #18401: LDAP User Provider wrong handling of passwords
Hi, trying to use the new LDAP component I think I have found a bug on the Component\Security\Core\User\LDAPUserProvider.

Concretely, LDAP on successful authentication retrieves an array with each user parameter, and each of this have at the same time another array. Due to this on this new version, among other improvements, the Entry class was introduced to handle this situation, but on the method loadUser, when it creates a new user it gives as a password the Entry for the password field, without taking into consideration that at the same time is an array of passwords. It is needed to get the first one - which should be the only one as we only authenticate one user at a time -.
This problem makes LDAP fail to completely authenticate the user. Also it doesn't allow symfony to store the remember me cookies correctly. This is because the token generator requires requires a single element not an array on the password parameter.

And there is a second bug on the same class, on the method refreshUser, when it creates the User instance giving a null as a password, instead of calling $user->getPassword() as it looks like it should do. 

I have done a quick and not necessarily good fix on my own fork to check this issue, and it worked fine just with this small changes.

To reproduce, install a LDAP server, configure it using this doc as a reference: http://symfony.com/blog/new-in-symfony-2-8-ldap-component
Except the part of the service definition, that as mentioned on https://github.com/symfony/symfony-docs/issues/5756#issuecomment-204075790 on the new version has to be defined like this:

```yaml
app.ldap:
        class: Symfony\Component\Ldap\Ldap
        factory: ['Symfony\Component\Ldap\Ldap', 'create']
        arguments:
            - 'ext_ldap'
            - host: 'host.mydomain.com' 
```

And after an initial successful authentication you should be getting a redirection loop to the authentication layer, as LDAP constantly fails to authenticate the user given that it tries to authenticate with a null password.

If someone else has the same problem and this bug can be confirmed, I can make a pull request with a fix.
Also, on this side, I'm not sure what the rules on fixes are on symfony, but it would be nice to add a fix for the 2.8 branch as well, which had the same issue and the bug is solved pretty much in the same way.

### PR DESCRIPTION
**Pull request by csarrazi**
| Q | A |
| --- | --- |
| Branch? | 3.1 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #18401 |
| License | MIT |
| Doc PR |  |

This PR fixes #18401, as well as other possible issues:
- First, the user provider no longer requires a password attribute by default. While this is not mandatory, it is more explicit to not set a password when using the `form_login_ldap` or `http_basic_ldap`, as these two providers don't use a password comparison mechanism, but `ldap_bind()` instead.
- Second, the attribute is now configurable. Some implementations actually use different properties to store the user's password attribute. This will enable some users to correctly work with specific configurations.
- Third, the user provider normalises the attribute array into a single string. Also, if the attribute has more than one value (which should not be possible), or if is not set, an exception will be thrown, with a clear error message.

### CODE REVIEW

File: src/Symfony/Component/Security/Core/User/LdapUserProvider.php [hunk 1]
```diff
@@ -99,8 +102,42 @@ public function supportsClass($class)
...
+     *
+     * @param string $username
+     * @param Entry  $entry
+     *
+     * @return User
+     */
     private function loadUser($username, Entry $entry)
     {
-        return new User($username, $entry->getAttribute('userpassword'), $this->defaultRoles);
+        $password = $this->getPassword($entry);
```
Comment (fabpot) [inline src/Symfony/Component/Security/Core/User/LdapUserProvider.php]: Could be inlined

**Comment by fabpot** [comment]
Thank you @csarrazi.

File: src/Symfony/Component/Security/Core/User/LdapUserProvider.php [hunk 2]
```diff
@@ -99,8 +102,42 @@ public function supportsClass($class)
...
+
+    /**
+     * Fetches the password from an LDAP entry.
+     *
+     * @param null|Entry $entry
+     */
+    private function getPassword(Entry $entry)
+    {
+        if (null === $this->passwordAttribute) {
+            return;
```
Comment (lsmith77) [inline src/Symfony/Component/Security/Core/User/LdapUserProvider.php]: under what circumstance does it make sense to return ``null`` here? from my testing this then eventually leads to an error with password hashing not allowing a null parameter. so my question is, should we not consider this an exception?

Comment (csarrazi) [inline src/Symfony/Component/Security/Core/User/LdapUserProvider.php]: It makes sense when you use LDAP Bind based authentication mechanisms, which do not rely on the password being provided as an LDAP attribute.
