### PR TITLE
[ObjectMapper] Correctly manage constructor initialization

### LINKED ISSUE #60797: [ObjectMapper] Allow constructor to be called when there are no mapped constructor parameters.
### Description

A constructor is not called when there are no constructor arguments.
However there are cases where you would want it to be able to be called such as mapping to a doctrine entity that has a collection so the collection is initialised:

```
class Article
{
    #[ORM\ManyToMany(targetEntity: Tag::class, cascade: ['persist'])]
    private Collection $tags;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }
}
```
It results in this error:
```
<!-- The property App\Entity\Article::$tags is not readable because it is typed Doctrine\Common\Collections\Collection. You should initialize it or declare a default value instead. (500 Internal Server Error) -->
```

### Example

_No response_

### LINKED ISSUE #60807: [ObjectMapper] Class-Level Transformation and Public Constructors
### Symfony version(s) affected

7.3.0

### Description

While checking out #60797 and writing a fix for it, I ran into an issue with regard to [Class-Level Transformation](https://symfony.com/doc/current/object_mapper.html#class-level-transformation) and the `InstanceCallback` test case https://github.com/symfony/symfony/tree/7.3/src/Symfony/Component/ObjectMapper/Tests/Fixtures/InstanceCallback.

The documentation stats that the callback "must return a correctly initialized instance of the target class" and the example code shows a private constructor with the comment "uses a private constructor to avoid direct instantiation". The `InstanceCallback`, however, has a public constructor which is only not called because `$ctorArguments` is empty (`A` only has property `$name` and `B::__constructor()` expects `$id`, thus  `$ctorArguments` is empty), see condition

https://github.com/symfony/symfony/blob/e568dabcbb1c30f9f6c0081886c6261eb8b90394/src/Symfony/Component/ObjectMapper/ObjectMapper.php#L149

### How to reproduce

Currently, the test case passes, but when changing `public ?string $name = null` to a promoted property in `\Symfony\Component\ObjectMapper\Tests\Fixtures\InstanceCallback\B`, the test case fails:

```
1) Symfony\Component\ObjectMapper\Tests\ObjectMapperTest::testMapToWithInstanceHook
ArgumentCountError: Symfony\Component\ObjectMapper\Tests\Fixtures\InstanceCallback\B::__construct(): Argument #1 ($id) not passed

…/src/Symfony/Component/ObjectMapper/Tests/Fixtures/InstanceCallback/B.php:16
…//src/Symfony/Component/ObjectMapper/ObjectMapper.php:151
…//src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php:152
```

showing that the constructor would be called but is only not called in the original example due to `$ctorArguments` being empty. 

### Possible Solution

As the class-level transformation is expected to return a full initialized objects, never call the constructor of the target object in `ObjectMapper` if level-class transformation is used.

Alternatively, if calling the constructor is correct, the documentation could be clearer and constructor argument validation could be improved because `\Symfony\Component\ObjectMapper\ObjectMapperInterface::map` is not expected to throw a `ArgumentCountError` (though only catching `\ReflectionException` here might be an issue on its own?).

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alanpoulain**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60797 Fix #60807
| License       | MIT

Currently the ObjectMapper cannot support empty constructor initialization, which is particularly useful for Doctrine collections:

```php
class Article
{
    #[ORM\ManyToMany(targetEntity: Tag::class)]
    private Collection $tags;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    public function addTag($tag)
    {
         // ...
    }

    public function removeTag($tag)
    {
         // ...
    }
}
```

This kind of error is thrown by the PropertyAccessor:

> Symfony\Component\PropertyAccess\Exception\UninitializedPropertyException: The property "Symfony\Component\ObjectMapper\Tests\Fixtures\InitializedConstructor\B::$tags" is not readable because it is typed "array". You should initialize it or declare a default value instead.

This PR fixes this but also another related issue (#60807): since an "empty" (no constructor arguments) constructor is always called, the class-level transformation test does not pass anymore:

> Symfony\Component\ObjectMapper\Tests\ObjectMapperTest::testMapToWithInstanceHook
ArgumentCountError: Too few arguments to function Symfony\Component\ObjectMapper\Tests\Fixtures\InstanceCallback\B::__construct(), 0 passed in /home/workspace/symfony/symfony/src/Symfony/Component/ObjectMapper/ObjectMapper.php on line 151 and exactly 1 expected

To solve this, a check is done on `map?->transform`.

### CODE REVIEW

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php [hunk 1]
```diff
@@ -146,7 +146,7 @@ public function map(object $source, object|string|null $target = null): object
             }
         }
 
-        if (!$mappingToObject && $ctorArguments && $constructor) {
+        if (!$mappingToObject && !$map?->transform && $constructor) {
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/ObjectMapper.php:149]: This is because in case of a transform we should've already built the object is that right?

**Review by soyuka — APPROVED** [review]

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php (hunk 1 above)
Comment (alanpoulain) [reply src/Symfony/Component/ObjectMapper/ObjectMapper.php:149]: Yes, that's right.

**Review by alexandre-daubois — APPROVED** [review]

**Review by mtarld — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @alanpoulain.
