### PR TITLE
[DependencyInjection] Fixed incorrect report for private services if required service does not exist

### LINKED ISSUE #29359: [DI] Incorrect service id report for non-existent services
**Symfony version(s) affected**: 4.0.14 and above

**Description**  
Imagine there are two services _A_ and _B_ in the container. The _A_ service depends on non-existent service _X_, the _B_ service depends on _A_. If the _A_ is declared as _public=false_, then container compilation reports, that service _B_ has requested non-existent service _X_. If the _A_ service is _public=true_, the report message will be correct.

**How to reproduce**  
Try to compile container with such definition:
```xml
<?xml version="1.0" ?>

<container xmlns="http://symfony.com/schema/dic/services"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
    <services>
        <service id="AppBundle\Service\Child" public="false">
            <argument type="service" id="serializer" /> <!-- Missed service -->
        </service>

        <service id="AppBundle\Service\ParentA" public="true">
            <argument type="service" id="AppBundle\Service\Child" />
        </service>
    </services>
</container>
```
Reproducing application: https://github.com/edefimov/symfony-reproduce/tree/eea1edabc1ab944603cf773d570e51ed0357f37d/

**Additional context**  
The output when service _AppBundle\Service\Child_ is _public=false_
```
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 31:
                                                                                                    
  The service "AppBundle\Service\ParentA" has a dependency on a non-existent service "serializer".                                                                                                 
```

Correct output when service _AppBundle\Service\Child_ is _public=true_ 
```
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 31:
                                                                                                  
  The service "AppBundle\Service\Child" has a dependency on a non-existent service "serializer".                                  
```

### PR DESCRIPTION
**Pull request by fu22ybear**
…does not exist

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #29359
| License       | MIT
| Doc PR        | no

looks like `CheckExceptionOnInvalidReferenceBehaviorPass` can be moved to `beforeRemovingPasses` section without any consequences. this solves the problem and all tests still pass

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php [hunk 1]
```diff
@@ -88,7 +89,6 @@ public function __construct()
         ]];
 
         $this->afterRemovingPasses = [[
-            new CheckExceptionOnInvalidReferenceBehaviorPass(),
```
Comment (jderusse) [inline src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php:91]: Are we sure that services removed by previous passes (defied in $this->removingPasses or by user).
Won't trigger such exception?

I don't know if it make send to duplicate the pass, in before-removing + after-removing. But I believe cheking invalid reference should be performed after removal of services.

Comment (fu22ybear) [reply src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php:91]: > Are we sure that services removed by previous passes (defied in $this->removingPasses or by user).
> Won't trigger such exception?

sounds like possible situation. but there is no suitable test case to check

can I give a try to add some test cases to check the need to duplicate the `CheckExceptionOnInvalidReferenceBehaviorPass` in before-removing + after-removing sections?

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php:91]: I agree with @jderusse, this can break apps with incomplete but unused services.
What about moving this pass just after `RemoveUnusedDefinitionsPass`?

Comment (fu22ybear) [reply src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php:91]: looks better, thank you

File: src/Symfony/Component/DependencyInjection/Tests/ContainerBuilderTest.php [hunk 2]
```diff
@@ -1316,6 +1316,47 @@ public function testNoClassFromNsSeparatorId()
...
+            ->setPublic(true)
+            ->addArgument([
+                'child_service' => new Reference('child_service'),
+            ])
+        ;
+
+        $container->compile();
+    }
+
+    public function testUnusedServiceRemovedByPassAndServiceNotFoundExceptionWasNotThrown()
```
Comment (fu22ybear) [inline src/Symfony/Component/DependencyInjection/Tests/ContainerBuilderTest.php:1341]: added one more test case, it fails if `CheckExceptionOnInvalidReferenceBehaviorPass` is called before removing passes (before `RemoveUnusedDefinitionsPass`, to be exact)

File: src/Symfony/Component/DependencyInjection/Tests/ContainerBuilderTest.php [hunk 3]
```diff
@@ -1316,6 +1316,47 @@ public function testNoClassFromNsSeparatorId()
...
+            ])
+        ;
+
+        try {
+            $container->compile();
+        } catch (ServiceNotFoundException $e) {
+            $this->fail('Should not be thrown');
+        }
+
+        $this->assertTrue(true);
```
Comment (jderusse) [inline src/Symfony/Component/DependencyInjection/Tests/ContainerBuilderTest.php]: you can use either `$this->expectNotToPerformAssertions()` or `$this->addToAssertionCount(1)`

File: src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php [hunk 4]
```diff
@@ -82,13 +82,13 @@ public function __construct()
             new ReplaceAliasByActualDefinitionPass(),
             new RemoveAbstractDefinitionsPass(),
             new RemoveUnusedDefinitionsPass(),
+            new CheckExceptionOnInvalidReferenceBehaviorPass(),
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php:86]: this requires running `AnalyzeServiceReferencesPass` just before

File: src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php [hunk 5]
```diff
@@ -82,13 +82,13 @@ public function __construct()
             new ReplaceAliasByActualDefinitionPass(),
             new RemoveAbstractDefinitionsPass(),
             new RemoveUnusedDefinitionsPass(),
-            new InlineServiceDefinitionsPass(new AnalyzeServiceReferencesPass()),
             new AnalyzeServiceReferencesPass(),
+            new CheckExceptionOnInvalidReferenceBehaviorPass(),
+            new InlineServiceDefinitionsPass(new AnalyzeServiceReferencesPass()),
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php:87]: `new AnalyzeServiceReferencesPass()` should still and also be listed after, because `InlineServiceDefinitionsPass` changes the graph

Comment (fu22ybear) [reply src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php:87]: but `CheckExceptionOnInvalidReferenceBehaviorPass` can not be listed after `InlineServiceDefinitionsPass`, because this is the reason why current bug occurs

File: src/Symfony/Component/DependencyInjection/Tests/ContainerBuilderTest.php (hunk 3 above)
Comment (fu22ybear) [reply src/Symfony/Component/DependencyInjection/Tests/ContainerBuilderTest.php]: done

File: src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php (hunk 5 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php:87]: `AnalyzeServiceReferencesPass` should be listed twice

**Review by nicolas-grekas — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you @Islam93.
