### PR TITLE
Fix the :only-of-type pseudo class selector

### LINKED ISSUE #33773: [CssSelector] Incorrect XPath for :only-of-type
**Symfony version(s) affected**: 4.3.4

**Description**  
The XPath expression returned by, e.g., `CssSelectorConverter::toXPath("span:only-of-type")` is `descendant-or-self::span[last() = 1]`.  This will only match a `<span>` element if it is the only one in the entire HTML (not just among its siblings).

**How to reproduce**
```php
$converter = new \Symfony\Component\CssSelector\CssSelectorConverter();
$xPathExpression = $converter->toXPath("span:only-of-type");
$domXPath = new \DOMXPath($domDocument);
$nodeList = $domXPath->query($xPathExpression);
```
where `$domDocument` is a `\DOMDocument` containing the following HTML:
```html
<html>
  <body>
    <p>
      <span></span>
    </p>
    <p>
      <span></span>
      <span></span>
    </p>
  </body>
</html>
```
`$nodeList` will be empty but should contain the `<span>` from the first paragraph.  If the second paragraph is removed, the behaviour is as expected (`$nodeList` will contain the `<span>` from the first paragraph), becuase there is only one `<span>` element in the entire document.

### PR DESCRIPTION
**Pull request by jakzal**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #33773
| License       | MIT
| Doc PR        | -

### CODE REVIEW

File: src/Symfony/Component/CssSelector/Tests/XPath/TranslatorTest.php [hunk 1]
```diff
@@ -116,7 +116,7 @@ public function testHtmlIds($css, array $elementsId)
         $this->assertCount(\count($elementsId), $elementsId);
         foreach ($elements as $element) {
             if (null !== $element->attributes()->id) {
-                $this->assertTrue(\in_array($element->attributes()->id, $elementsId));
+                $this->assertContains((string) $element->attributes()->id, $elementsId);
```
Comment (jakzal) [inline src/Symfony/Component/CssSelector/Tests/XPath/TranslatorTest.php]: This is not strictly related,  but it improves an error message shown when the test fails. Before the change, the message would say "expected true, got false". Now it will indicate what's the missing id.

**Review by stof — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jakzal.
