### PR TITLE
[ObjectMapper] skip reading uninitialized values

### LINKED ISSUE #60786: [ObjectMapper] Allow to skip mapping non-initialized source values
### Description

For `PATCH` requests, only the values that will get provided will get handled (read: updated on an entity). It is valid to leave out values in the request's payload that did not change, and solely the values that get provided will have to be processed.

When working with an input dto - after proper denormalization - this will result in not having all the input's values initialized based on the PATCH payload.

Side-note; some implementations would consider using `null` as default value on an input dto, which imho is incorrect when you don't want to get that value processed, as `null` *should* be considered as actual value for the target fields.

## Current situation

* The normalization will lead to an input dto that does not have all it's fields instantiated. Or, in case of a constructor will lead to an exception that not all the constructor's arguments are provided.
* In case that the normalization did pass; an exception on `ObjectMapper:170` that the value cannot be retrieved, or in case of a default value on the input dto (e.g. `null`) that value will be set on the target.
* The `stdClass` mode is not preferred as it does not allow adding assert attributes for the validation https://symfony.com/doc/current/object_mapper.html#mapping-from-stdclass
* Adding `#[Map(if: 'isset')]` on each input dto field is not preferred either: https://symfony.com/doc/current/object_mapper.html#configuring-property-mapping
* The `ObjectMapper::getRawValue` gets called on line 129 before the `if` callable on line 130 would be able to check if it's value is instantiated. In other words; getting an uninitialized value would already crash on line 129.

```php

foreach ($mappings as $mapping) {
    # ... 

    $value = $this->getRawValue($source, $sourcePropertyName);
    if ($if && ($fn = $this->getCallable($if, $this->conditionCallableLocator)) && !$this->call($fn, $value, $source, $mappedTarget)) {
        continue;
 }
```

## Expected situation

* To properly support `PATCH` requests, having a mode that does not handle uninitialized fields on the source would be really helpful.
* Could be helpful to have the `$mapAttribute` available on the `call` method. That way the user's callable can keep additional logic into account in userland.
```diff
-    private function call(callable $fn, mixed $value, object $source, ?object $target = null): mixed
+    private function call(callable $fn, mixed $value, object $source, ?object $target = null, Mapping $mapAttribute): mixed 
    {
        if (\is_string($fn)) {
            return \call_user_func($fn, $value);
        }

-        return $fn($value, $source, $target);
+        return $fn($value, $source, $target, $mapAttribute);
    }
```

### Example

```php
<?php

final class FooPatchInput
{
    #[Assert\Length(min: 3, max: 255, minMessage: 'Name must be at least 3 characters long', maxMessage: 'Name cannot be longer than 255 characters')]
    public string $name;

    #[Assert\Email(message: 'The email {{ value }} is not a valid email.')]
    public string $email;

    #[Assert\Url(message: 'The website {{ value }} is not a valid URL.')]
    public string $website;
}
```

```php

// Additional field on the atrribute
#[Map(... , ignore_when_uninitialized: true)
// or
#[Map(... , skip_when_uninitialized: true)
// or
#[Map(... , optional: true)
```

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| Issues        | Fix #60786 
| License       | MIT

The mapper would read uninitialized properties, for example this would throw trying to read `name`:

```php
#[Map(target: FinalInput::class)]
class PartialInput
{
    public string $uuid;
    public string $name;
    public ?string $email;
    public ?string $website;
}

$p = new PartialInput;
$p->uuid = '6a9eb6dd-c4dc-4746-bb99-f6bad716acb2';
$p->website = 'https://updated.website.com';

$mapper = new ObjectMapper();
$mapper->map($p);
```

### CODE REVIEW

**Comment by mttsch** [comment]
@soyuka As the description will be part of the commit message, there is a small typo:

```php
$mapper->map($);
```

->

```php
$mapper->map($p);
```

File: src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php [hunk 1]
```diff
@@ -402,4 +404,46 @@ public function testMapInitializesNativePhp84LazyObject()
...
+    /**
+     * @dataProvider validPartialInputProvider
+     */
+    public function testMapPartially(PartialInput $actual, FinalInput $expected)
+    {
+        $mapper = new ObjectMapper();
+        $this->assertEquals($expected, $mapper->map($actual));
+    }
+
+    public static function validPartialInputProvider(): iterable {
```
Comment (mttsch) [inline src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php]:
```suggestion
    public static function validPartialInputProvider(): iterable
    {
```

**Review by alexandre-daubois — APPROVED** [review]

**Review by rvanlaak — APPROVED** [review]
Can confirm this implementation resolves our problems. Thanks for addressing our issue @soyuka 🙌

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @soyuka.
