### PR TITLE
[Serializer] Fix access to private properties/getters when using the `@Ignore` annotation

### LINKED ISSUE #52673: [Serializer] All fields are not included by default, but upon adding any attribute, all fields are then required
### Symfony version(s) affected

6.3.8

### Description

According to https://symfony.com/doc/current/components/serializer.html#ignoring-attributes all properties are included by default, which makes sense. However, this doesn't seem to be the case at least for traits and abstract classes.

When we don't add the `#[Ignore]` attribute in the `TestTrait` in the reproducer, everything works fine. However, adding that attribute causes all of the other properties to now be seen by the serializer and then fail because there is no public access to them via getters or via public properties.

### How to reproduce

https://github.com/nesl247/symfony-serialization-ignore-bug

1) git clone https://github.com/nesl247/symfony-serialization-ignore-bug.git
2) composer install
3) bin/console test:command

### Possible Solution

_No response_

### Additional Context

```[critical] Error thrown while running command "test:command". Message: "Can't get a way to read the property "testProperty2" in class "App\TestMessage"."

In PropertyAccessor.php line 456:
                                                                                    
  Can't get a way to read the property "testProperty2" in class "App\TestMessage".  
                                                                                    
```

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #52673 #49710
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php [hunk 1]
```diff
@@ -484,6 +493,16 @@ class EmptyDummy
 {
 }
 
+class ObjectDummyWithIgnoreAttributeAndPrivateProperty
```
Comment (OskarStark) [inline src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: Annotation instead of Attribute?

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php [hunk 2]
```diff
@@ -444,6 +445,14 @@ public function testNormalizeEmptyObject()
         $normalizedData = $normalizer->normalize(new EmptyDummy(), 'any', ['preserve_empty_objects' => true]);
         $this->assertEquals(new \ArrayObject(), $normalizedData);
     }
+
+    public function testNormalizeWithIgnoreAttributeAndPrivateProperties()
```
Comment (OskarStark) [inline src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]:
```suggestion
    public function testNormalizeWithIgnoreAnnotationAndPrivateProperties()
```
Sorry, I missed it on my first review

Comment (mtarld) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: Aha, it's ok, I missed that as well!

**Comment by nesl247** [comment]
@mtarld am I misunderstanding the documentation though? It says

> All attributes are included by default when serializing objects. There are two options to ignore some of those attributes.

Which to mean means even private and protected. While I think the fix here makes sense, it doesn't align with the documentation. Should the documentation also be updated to say only publicly accessible attributes are included? Or is that what `attribute` means and I am missing the definition?

**Comment by stof** [comment]
Private or protected properties are included if they have getters to access them publicly.

**Comment by nesl247** [comment]
> Private or protected properties are included if they have getters to access them publicly.

That's what I thought. Then the documentation should be updated to specify that instead of all attributes correct?

**Comment by mtarld** [comment]
Indeed, we could go with something like: "All **accessible** attributes are included by default when serializing objects.".

WDYT? Up for a PR?

**Comment by nesl247** [comment]
> Indeed, we could go with something like: "All **accessible** attributes are included by default when serializing objects.".
> 
> WDYT? Up for a PR?

Yes. I’m out of the office until Tuesday, but when I get back I’m happy to submit a PR.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
> PHP Parse error:  syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/runner/work/symfony/symfony/src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php on line 498

**Comment by mtarld** [comment]
Failures should be fixed in https://github.com/symfony/symfony/pull/52713

**Comment by nicolas-grekas** [comment]
Thank you @mtarld.
