### PR TITLE
[Security] fix #41891 Save hashed tokenValue in RememberMe cookie

### LINKED ISSUE #41891: Refreshed RememberMe cookie contains invalid data
**Symfony version(s) affected**: 5.3.2 (with symfony/security-http 5.3.x-dev 81c183fd1527a2d09bd3b5c69bca3fc24ce18527 for another fix in rememberme)

**Description**

The rememberme cookie returned when a rememberme session is renewed is not properly formatted. This causes it to be rejected when it is used again.

**How to reproduce**

1. Given a setup with rememberme enabled
2. Login with remember me
3. Remove session cookie
4. Refresh
5. Remove session cookie again
6. There is no new session

**Possible Solution**

I pulled two cookies from my installation (a development version, see Additional context), the first one is the original REMEMBERME cookie and the second one is the one received after refreshing. In the first one the last value is base64 encoded and in the second one it isn't.

(originally I had these two mixed up)
 

**Additional context**

```
REMEMBERME=Q3NyRGVsZnRcZW50aXR5XHNlY3VyaXR5XEFjY291bnQ6TVRNME5RPT06MTYyNjEyNjUzOTpVUzNCS2lhNUpsV2hpT2hPSmZ2UWExWGxSNmRNMWJtR2NHRThuZzhQalRsYWFuMDNhM0ZISU9hOXVVYmo5VkVlbWptemVMTlU1cXA4SGVLSFYxVng0UT09Ojc0OWRjN2VkZTU3MzFhODRiZmVmMzIxYzQyZjgxNDI0ZDY2MDAzNTRkNTljMzI2MDQyNTA1ZGY2OTA4NTUyMTA%3D
url & base64 decoded: CsrDelft\entity\security\Account:MTM0NQ==:1626126539:US3BKia5JlWhiOhOJfvQa1XlR6dM1bmGcGE8ng8PjTlaan03a3FHIOa9uUbj9VEemjmzeLNU5qp8HeKHV1Vx4Q==:749dc7ede5731a84bfef321c42f81424d6600354d59c326042505df690855210

REMEMBERME=Q3NyRGVsZnRcZW50aXR5XHNlY3VyaXR5XEFjY291bnQ6TVRNME5RPT06MTYyNjEyNjUzOTpVUzNCS2lhNUpsV2hpT2hPSmZ2UWExWGxSNmRNMWJtR2NHRThuZzhQalRsYWFuMDNhM0ZISU9hOXVVYmo5VkVlbWptemVMTlU1cXA4SGVLSFYxVng0UT09OnFVWHRIVWJHR01QQXBwbVdmSkFGWjRlS1QyRElOY0VLRHhvaDFHM2JmVUxtMmhGSExDdVcwT1dGd0FrcExUdlloTzFLaGora2dadmltQ01XL0xPYzB3PT0%3D
url & base64 decoded: CsrDelft\entity\security\Account:MTM0NQ==:1626126539:US3BKia5JlWhiOhOJfvQa1XlR6dM1bmGcGE8ng8PjTlaan03a3FHIOa9uUbj9VEemjmzeLNU5qp8HeKHV1Vx4Q==:qUXtHUbGGMPAppmWfJAFZ4eKT2DINcEKDxoh1G3bfULm2hFHLCuW0OWFwAkpLTvYhO1Khj+kgZvimCMW/LOc0w==
```

### PR DESCRIPTION
**Pull request by qurben**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #41891 
| License       | MIT

The hashed tokenValue is expected in the RememberMe cookie. This was not the case when this branch was executed.

### CODE REVIEW

File: src/Symfony/Component/Security/Http/RememberMe/PersistentRememberMeHandler.php [hunk 1]
```diff
@@ -89,13 +89,12 @@ public function processRememberMe(RememberMeDetails $rememberMeDetails, UserInte
         // if a token was regenerated less than a minute ago, there is no need to regenerate it
         // if multiple concurrent requests reauthenticate a user we do not want to update the token several times
         if ($persistentToken->getLastUsed()->getTimestamp() + 60 < time()) {
-            $tokenValue = base64_encode(random_bytes(64));
-            $tokenValueHash = $this->generateHash($tokenValue);
```
Comment (jderusse) [inline src/Symfony/Component/Security/Http/RememberMe/PersistentRememberMeHandler.php:93]: not related to this PR, but if both `tokenProvider` and `Cookie` stores the same random value, why do we "salt" the token with a secret? ping @wouterj

**Comment by qurben** [comment]
I am not sure if it is possible to create a test for this. `testConsumeRememberMeCookieValid` could test that the value that is passed to the tokenProvider mock is also found in the cookie, but when the mock is called the cookie is not yet set.

**Review by Seldaek — APPROVED** [review]

**Review by jderusse — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thanks for fixing this bug @qurben.
