### PR TITLE
[Console] fixed corrupt error output for unknown multibyte short option

### LINKED ISSUE #28320: [Console] Corrupt error output for unknown multibyte short option
**Symfony version(s) affected**: 4.1.4

**Description**

Error contains only first byte of multibyte short option

**How to reproduce**

1. `composer require symfony/console:4.1.4`
2. Create `application.php` with simple command. Example:

```php
#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

$application = new Application();

$application->add(new class extends Command {
    public function getName() {
        return 'do';
    }

    public function execute(InputInterface $input, OutputInterface $output) {
    }
});

$application->run();
```

3. `./application.php do -С 10` (where `С` is Cyrillic; you can use another letter, e.g. `Щ`)

**Possible Solution**

Use `mb_substr` instead of index access in `\Symfony\Component\Console\Input\ArgvInput::parseShortOptionSet`

**Additional context**

### PR DESCRIPTION
**Pull request by downace**
| Q             | A
| ------------- | ---
| Branch?       | 2.8 
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #28320   
| License       | MIT
| Doc PR        | - 

[Console] Fixed #28320 by using mb_substr instead of index access

### CODE REVIEW

File: src/Symfony/Component/Console/Input/ArgvInput.php [hunk 1]
```diff
@@ -119,9 +119,10 @@ private function parseShortOption($token)
     private function parseShortOptionSet($name)
     {
         $len = \strlen($name);
+        $encoding = \mb_detect_encoding($name);
```
Comment (chalasr) [inline src/Symfony/Component/Console/Input/ArgvInput.php]: `mb_detect_encoding` might return `false`, see e.g. https://github.com/symfony/symfony/blob/e81285249b780a11ed209a79fa77c1f6ea6da67b/src/Symfony/Component/Console/Helper/Helper.php#L68.  The code should keep relying on `$name[$i]` in this case

File: src/Symfony/Component/Console/Input/ArgvInput.php [hunk 2]
```diff
@@ -119,9 +119,10 @@ private function parseShortOption($token)
...
         for ($i = 0; $i < $len; ++$i) {
             if (!$this->definition->hasShortcut($name[$i])) {
-                throw new RuntimeException(sprintf('The "-%s" option does not exist.', $name[$i]));
+                throw new RuntimeException(sprintf('The "-%s" option does not exist.', \mb_substr($name, $i, 1, $encoding)));
```
Comment (chalasr) [inline src/Symfony/Component/Console/Input/ArgvInput.php]: we put the `\` only for compiler optimized functions (full list available here https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.12/src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php#L350)

**Review by chalasr — CHANGES_REQUESTED** [review]
thanks for contributing

File: src/Symfony/Component/Console/Input/ArgvInput.php (hunk 2 above)
Comment (downace) [reply src/Symfony/Component/Console/Input/ArgvInput.php]: Oh, I thought it works for all global functions. Thanks!

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Component/Console/Input/ArgvInput.php [hunk 3]
```diff
@@ -121,7 +121,8 @@ private function parseShortOptionSet($name)
         $len = \strlen($name);
         for ($i = 0; $i < $len; ++$i) {
             if (!$this->definition->hasShortcut($name[$i])) {
-                throw new RuntimeException(sprintf('The "-%s" option does not exist.', $name[$i]));
+                $encoding = mb_detect_encoding($name);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Input/ArgvInput.php]: we muse use strict mode, otherwise the detection is useless: `mb_detect_encoding($name, null, true);`

**Review by javiereguiluz — APPROVED** [review]
@downace a nice first contribution to Symfony. Thanks!

**Comment by chalasr** [comment]
Thank you @downace.
