### PR TITLE
[Ldap] LDAP authentication should return a meaningful error when the LDAP server is unavailable

### LINKED ISSUE #44089: LDAP authentication should return a meaningful error when the LDAP server is unavailable
### Symfony version(s) affected

5.3

### Description

In case the configured LDAP server is not currently reachable, the `json_login_ldap` authenticator returns this to the user:

```
{
    "code": 401,
    "message": "Invalid credentials."
}
```

Internally, a PHP notice is logged:

```
Warning: ldap_bind(): Unable to bind to server: Can't contact LDAP server
```

and `symfony/ldap` throws `Symfony\Component\Security\Core\Exception\BadCredentialsException`, which doesn't seem quite right.

I think it would make more sense for the server to return a `500` stating something went wrong while attempting to verify credentials.

### How to reproduce

- Have a working LDAP authentication setup
- Introduce connectivity issues (firewall, stop the ldap server, what have you)
- Try to authenticate using valid credentials

### Possible Solution

When `ldap_bind()` finds it is `Unable to bind to server: Can't contact LDAP server`, instead of throwing a `BadCredentialsException` we could throw something else to indicate there was an issue while attempting to verify credentials. Various authenticators (like `json_login_ldap` could then return meaningful errors to the user.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Jayfrown**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #44089
| License       | MIT

Return a 500 ISE if the LDAP server is unreachable.

I have tested the following scenarios:

<details>
<summary>LDAP server unreachable</summary>

`Adapter/ExtLdap/Connection.php` throws a `ConnectionException` which is not caught, and this results in a 500 ISE shown to the user. In development mode, you see a relevant trace and the correct error hinting to an unreachable LDAP server, and in production mode this wouldn't be shown to the user, and would be logged.
</details>

<details>
<summary>LDAP server reachable, with invalid search bind credentials</summary>

The `LdapUserProvider` tries to search the LDAP directory for the provided user. To search, it tries to authenticate using the (invalid) bind credentials, resulting in `Adapter/ExtLdap/Connection.php` throwing an `InvalidCredentialsException` which is not caught. As this is indicative of a misconfiguration within the application (ie. the app's search bind credentials are wrong, and searching for any user will always fail) I believe a 500 ISE is appropriate.

We could opt to catch the `InvalidCredentialsException` inside the `LdapUserProvider` and throw something more specific, to indicate it is the applications search bind credentials that are invalid, as opposed to the credentials the user provided during authentication.
</details>

<details>
<summary>LDAP server reachable, with valid search bind credentials, authenticating as an unknown user</summary>

As the search bind credentials are valid, the `LdapUserProvider` searches the LDAP directory, finds no entries, and throws a `UserNotFoundException` which results in the authenticator returning `{"code":401,"message":"Invalid credentials."}`. I believe this is good / expected behavior.
</details>

<details>
<summary>LDAP server reachable, with valid search bind credentials, using known user with invalid password</summary>

The `ldap/Adapter/ExtLdap/Connection.php` throws an `InvalidCredentialsException`. The `ldap/Security/CheckLdapCredentialsListener.php` now catches the `InvalidCredentialsException` (instead of the `ConnectionException`) and throws a `BadCredentialsException` such that the authenticator returns `{"code":401,"message":"Invalid credentials."}` 
</details>

<details>
<summary>LDAP server reachable, with valid search bind credentials, using known user with valid password</summary>

The credentials are validated and the user is logged in, everything works as expected
</details>

### CODE REVIEW

File: src/Symfony/Component/Ldap/Security/LdapUserProvider.php [hunk 1]
```diff
@@ -73,17 +72,10 @@ public function loadUserByUsername(string $username): UserInterface
...
-            $identifier = $this->ldap->escape($identifier, '', LdapInterface::ESCAPE_FILTER);
-            $query = str_replace(['{username}', '{user_identifier}'], $identifier, $this->defaultSearch);
-            $search = $this->ldap->query($this->baseDn, $query, ['filter' => 0 == \count($this->extraFields) ? '*' : $this->extraFields]);
-        } catch (ConnectionException $e) {
-            $e = new UserNotFoundException(sprintf('User "%s" not found.', $identifier), 0, $e);
-            $e->setUserIdentifier($identifier);
-
-            throw $e;
-        }
+        $this->ldap->bind($this->searchDn, $this->searchPassword);
```
Comment (Jayfrown) [inline src/Symfony/Component/Ldap/Security/LdapUserProvider.php]: We could opt to catch `InvalidCredentialsException` here in order to throw something more-specific that would indicate it is the search bind credentials (used during enumeration) that are invalid, as opposed to the credentials that the user has provided.

**Comment by Jayfrown** [comment]
@wouterj FWIW, I have the following docker-compose setup for a local LDAP:

<details>
<summary>docker-compose.yml:</summary>

```yaml
services:

  openldap:
    image: osixia/openldap:1.5.0
    restart: unless-stopped
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: ${LDAP_ORGANISATION:-Example Inc.}
      LDAP_DOMAIN: ${LDAP_DOMAIN:-example.org}
      LDAP_BASE_DN: ${LDAP_BASE_DN:-"dc=example,dc=org"}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-admin}
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD:-config}
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ldap_certs:/container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap

volumes:
  ldap_data:
  ldap_config:
  ldap_certs:
```
</details>

And the following configuration in Symfony:

<details>
<summary>services.yaml:</summary>

```yaml
    Symfony\Component\Ldap\Ldap:
        arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']
        tags: ['ldap']
    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments:
            - host: '%env(resolve:LDAP_HOST)%'
              port: '%env(resolve:LDAP_PORT)%'
              encryption: '%env(resolve:LDAP_ENCRYPTION)%'
              options:
                  protocol_version: 3
                  referrals: false
```
</details>

<details>
<summary>security.yaml:</summary>

```yaml
    providers:
        app_ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: '%env(resolve:LDAP_BASE_DN)%'
                search_dn: '%env(resolve:LDAP_SEARCH_DN)%'
                search_password: '%env(resolve:LDAP_SEARCH_PASSWORD)%'
                default_roles: ROLE_USER
                uid_key: uid
                
    firewalls:
        main:
            provider: app_ldap
```
</details>

<details>
<summary>.env:</summary>

```
LDAP_HOST="openldap"
LDAP_PORT="389"
LDAP_ENCRYPTION="none"
LDAP_SEARCH_DN="cn=admin,dc=example,dc=org"
LDAP_SEARCH_PASSWORD="admin"
LDAP_BASE_DN="ou=Users,dc=example,dc=org"
```
</details>

You'd have to create the rest of the schema by hand, if needed I can try to provide an LDIF.

**Comment by Jayfrown** [comment]
@wouterj if there's anything I can do to make reviewing easier, let me know

File: src/Symfony/Component/Ldap/CHANGELOG.md [hunk 2]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+6.1
+---
+
+ * Return a 500 ISE if LDAP server in unavailable during user enumeration / authentication
```
Comment (stof) [inline src/Symfony/Component/Ldap/CHANGELOG.md]: please don't use the `ISE` abbrevation in the changelog

**Comment by stof** [comment]
CheckLdapCredentialsListener has 2 modes. Your PR description lets me think that you tested only one of them.

**Comment by Jayfrown** [comment]
> CheckLdapCredentialsListener has 2 modes. Your PR description lets me think that you tested only one of them.

@stof Thanks. It is very possible I might have missed something, as I'm not familiar with the two modes you mention. Could you expand on this or send some documentation my way?

**Comment by stof** [comment]
I'm not familiar with the ldap part either. But for those 2 modes, see the if/else inside the try/catch you changed

File: src/Symfony/Component/Ldap/Security/LdapUserProvider.php (hunk 1 above)
Comment (Jayfrown) [reply src/Symfony/Component/Ldap/Security/LdapUserProvider.php]: Same in `CheckLdapCredentialsListener.php` line 77

Point being that throwing the `InvalidCredentialsException` can be ambiguous in either meaning "user-provided credentials are invalid" or "configured search credentials are invalid"

**Comment by Jayfrown** [comment]
@stof Thanks. If I understand correctly the difference is when [`query_string`](https://symfony.com/doc/current/security/ldap.html#query-string) is set, which, according to the documentation:

> makes the user provider search for a user and then use the found DN for the bind process

Basically allowing the LDAP component to search for a given user in multiple OUs instead of simply interpolating the username into the `dn_string`.

<details>
<summary>Expand default behavior</summary>

- Interpolate the user-provided username in the `dn_string`, eg. `uid={username},dc=example,dc=com` becomes `uid=jayfrown,dc=example,dc=com` 
- Use the user-provided password to bind as the interpolated `dn_string`
  - If the bind is successful, the credentials are accepted and log-in continues
  - If the bind is not successful, the credentials are rejected and log-in is prohibited
</details>

<details>
<summary>Expand query_string behavior</summary>

- Interpolate the user-provided username in the `query_string`, eg. `(&(uid={username}))` becomes `(&(uid=jayfrown))`
- Bind with the configured search credentials
- Perform an LDAP search inside the `dn_string` using the `query_string`, eg. if `dn_string` is `dc=example,dc=com`, this can return `uid=jayfrown,dc=companyA,dc=example,dc=com` or `uid=jayfrown,dc=companyB,dc=example,dc=com`, etc.
  - If the search does not yield exactly one result, throw a `BadCredentialsException` indicating that the user-provided username is invalid
  - If the search yields exactly one result, use the user-provided password to bind as the found DN
      - If the bind is successful, the credentials are accepted and log-in continues
      - If the bind is not successful, the credentials are rejected and log-in is prohibited
</details>
      
Having said all that, my changes should not impact either scenario apart from what I've already described. However, when I have some more time I will set up a configuration using `query_string` and test with that as well.

**Comment by Jayfrown** [comment]
I made an [example application](https://github.com/Jayfrown/symfony-ldap-example/) to make it easier to test and verify behavior. The repository includes a docker-compose configuration that spins up an OpenLDAP container, seeds it with some users, and exposes the ports such that the local application can communicate with it.

There are a couple of branches to test all permutations (with/without `query_string` as well as with/without this PR applied)

- The [`master` branch](https://github.com/Jayfrown/symfony-ldap-example/tree/master) uses the normal configuration, without this PR applied
- The [`query_string` branch](https://github.com/Jayfrown/symfony-ldap-example/tree/query_string) uses the [`query_string` configuration](https://symfony.com/doc/current/security/ldap.html#query-string) without this PR applied
- The [`44898` branch](https://github.com/Jayfrown/symfony-ldap-example/tree/44898) uses the normal configuration, with this PR applied
- The [`44898_query_string` branch](https://github.com/Jayfrown/symfony-ldap-example/tree/44898_query_string) uses the [`query_string` configuration](https://symfony.com/doc/current/security/ldap.html#query-string), with this PR applied

Branches with this PR applied require [`Jayfrown/ldap dev-ldap-server-unavailable`](https://github.com/Jayfrown/ldap/tree/ldap-server-unavailable) which is a clone of the `symfony/ldap` repository which includes the work in this PR.

Note that after switching to/from branches with this PR applied it is necessary to run `composer install`.

----

@stof I've tested the same scenarios as mentioned in the OP with the `query_string` configuration and the behavior remains the same.

File: src/Symfony/Component/Ldap/Security/LdapUserProvider.php (hunk 1 above)
Comment (Jayfrown) [reply src/Symfony/Component/Ldap/Security/LdapUserProvider.php]: https://github.com/symfony/symfony/pull/44898/commits/7ab0611440472173a604b35e1eaaa7791a0569f7 introduces an `InvalidSearchCredentialsException` which is thrown when binding fails when using the configured search credentials.

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Jayfrown.
