### PR TITLE
[Mime] Throw exception when body in Email attach method is not ok

### LINKED ISSUE #45350: [Mailer] Attaching files with fopen from a remote url occasionally crashes SmtpTransport
### Symfony version(s) affected

^5.2

### Description

This is a bug I've been trying to track for more than a year now, since it happens only occasionally. In the beginning I thought this was an issue with our SMTP server (you will see why below), but I am finally able to pin it down.

We occasionally send a large number (>200) transactional e-mails containing a PDF that we attach from our cdn:

```
$email = (new TemplatedEmail())
  ->...

foreach ($pdfUrls as $url) {
  $email->attach(fopen($url, 'r'), $generatedName.'.pdf', 'application/pdf');
}

$this->mailer->send($email);
```

Out of, say 250, emails we occasionally get a very small percentage (e.g. 4/250) that fail and go to failure transport.

When we inspect the first of the failed messages, we see that attachment->body is false. Apparently, this is the problem. How come ->attach method proceeds forward when fopen returns false?

Now, this is the smaller issue. We can probably solve that by retrying 5 times to get the file with fopen (maybe there is an issue with our CDN, throttling, etc.) 

The bigger issue is that this situation apparently crashes the whole SmtpTransport, as we get the following error immediately after:

`Email transport "Symfony\Component\Mailer\Transport\Smtp\SmtpTransport" stopped`

And it crashes in such a way that it somehow breaks the smtp server connection. The next message in the queue fails as well with Connection timeout. We checked the SMTP server logs (it is our own) and apparently symfony sends unexpected data (e.g., starting a new message w/out properly closing the previous transaction; not really sure, e-mail in general is blackbox for most).

So, the result is the problematic email fails and it also breaks the next one in the queue. We know that because a side issue is that the body => false message fails every time it is retried (normal, as the message in the queue holds the same data). I don't think the message should go to the queue at all with attachment->body->false, while the next in queue, which initially failed, works fine on retry.

Any thoughts or suggestions?

### How to reproduce

Try sending a large number (>300) e-mails with attachments from an external link with fopen(); 

### Possible Solution

Don't just set attachment body to false, give a meaningful error where the failure occurred.

### Additional Context

```
...
          -isDirty: false
          #collection: Doctrine\Common\Collections\ArrayCollection^ {
            -elements: []
          }
          #initialized: false
        }
        -photo: null
      },
      "content" => "concrete content",
      "notificationAddonBusiness" => "bla bla",
      "notificationAddonCompany" => """
        bla bla
        """
    ]
    -text: "bla bla bla"
    -textCharset: "utf-8"
    -html: null
    -htmlCharset: null
    -attachments: [
      [
        "body" => false,
        "name" => "9000004479.pdf",
        "content-type" => "application/pdf",
        "inline" => false
      ]
    ]
...
```

See how attachment body is false.

### PR DESCRIPTION
**Pull request by alamirault**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45350
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

As proposed in #45350, throw exception when calling `(new Email())->attach($badBodyType);` when type is not supported

### CODE REVIEW

File: src/Symfony/Component/Mime/Exception/UnexpectedTypeException.php [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+ *
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\Mime\Exception;
+
+class UnexpectedTypeException extends InvalidArgumentException
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mime/Exception/UnexpectedTypeException.php]: Adding a new class is a new feature, so cannot be part of a bugfix.
I'd suggest throwing a TypeError instead, as `TextPart` does already.

**Review by nicolas-grekas — COMMENTED** [review]
A few more methods would need the check, eg `embed()`

File: src/Symfony/Component/Mime/Email.php [hunk 2]
```diff
@@ -272,12 +272,16 @@ public function getPriority(): int
     }
 
     /**
-     * @param resource|string $body
+     * @param resource|string|null $body
```
Comment (alamirault) [inline src/Symfony/Component/Mime/Email.php:275]: Was not documented before but null car be pass

File: src/Symfony/Component/Mime/Email.php [hunk 3]
```diff
@@ -272,12 +272,16 @@ public function getPriority(): int
...
      *
      * @return $this
      */
     public function text($body, string $charset = 'utf-8')
     {
+        if (null !== $body && !\is_string($body) && !\is_resource($body)) {
+            throw new \TypeError(sprintf('The body must be a string, a resource or null (got "%s").', \is_object($body) ? \get_class($body) : \gettype($body)));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mime/Email.php]: we can use get_debug_type instead of the ternary op thanks to the php80 polyfill that is already required by the component \o/

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @alamirault.
