### PR TITLE
[HttpFoundation] Fix AcceptHeader overwrites items with different parameters

### LINKED ISSUE #62282: AcceptHeader::fromString() not fully compliant with the related RFC9110?
### Symfony version(s) affected

7.4, 7.3, most likely earlier versions as well (did not check, but I doubt that valid behavior was broken later on)

### Description

The mentioned method is "loosing" important negotiation information when there is more than one accepted type given with different additional attributes/parameters. Think of `text/plain;format=flowed` and `text/plain;format=fixed;q=0.4` (example from RFC9110, https://www.rfc-editor.org/rfc/rfc9110.html#name-accept). AcceptHeader::fromString() will contain solely `text/plain;format=fixed;q=0.4` and forget/ignore `text/plain;format=flowed` with its quality of `1.0` (fallback value if not specified).

The reason for that is that internally, the AcceptHeader::add() method is using solely $item->getValue() as the array key of AcceptHeaderItems added, ignoring any other attributes. So the last "value" overwrites all others. 

Fixing that might lead to a BC break potentially, as the behavior would change for such cases. But as it seems that this issue has not been raised before, the question is if it still could/should be fixed? Also the aspect of "Media ranges can be overridden by more specific media ranges or specific media types. If more than one media range applies to a given type, the most specific reference has precedence." would be needed to be taken into account 🤔 

### How to reproduce

I've copied some example Accept headers from the related RFC9110 and its predecessor RFC7231 into the available unit tests in a created branch: https://github.com/symfony/symfony/compare/7.4...andesk:symfony:bug-reproduction/accept-header-from-string The misalignment should be visible with the according tests breaking.

### Possible Solution

Creating a different array key appending attribute key+value pairs to its string representation somehow to avoid overriding existing value expectations for other attribute combinations.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by yoeunes**
| Q | A
|---|---
| Branch? | 6.4
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Issues | Fixes #62282
| License | MIT

This PR fixes a bug in `AcceptHeader` where items with the same media type but different parameters (e.g., `text/plain;format=flowed` and `text/plain;format=fixed`) would overwrite each other.

The `add()` method now uses a canonical key that includes all parameters (except `q`), ensuring distinct items are stored correctly.

Consequently, the `get()` method has been updated to perform proper content negotiation (as described in RFC 9110), including matching parameters and sorting by specificity (e.g., `text/plain` > `text/*` > `*/*`). New tests are added to cover these cases.

### CODE REVIEW

File: src/Symfony/Component/HttpFoundation/Tests/AcceptHeaderTest.php [hunk 1]
```diff
@@ -109,7 +111,12 @@ public static function provideSortingData()
     public function testDefaultValue($acceptHeader, $value, $expectedQuality)
     {
         $header = AcceptHeader::fromString($acceptHeader);
-        $this->assertSame($expectedQuality, $header->get($value)->getQuality());
+        $item = $header->get($value);
+        if (null === $expectedQuality) {
+            $this->assertNull($item);
+        } else {
+            $this->assertSame($expectedQuality, $item->getQuality());
+        }
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Tests/AcceptHeaderTest.php]:
```suggestion
        $this->assertSame($expectedQuality, $item->getQuality());
```

File: src/Symfony/Component/HttpFoundation/AcceptHeader.php [hunk 2]
```diff
@@ -73,15 +73,39 @@ public function __toString(): string
      */
     public function has(string $value): bool
     {
-        return isset($this->items[$value]);
+        return null !== $this->get($value);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/AcceptHeader.php]:
```suggestion
        return isset($this->items[$value]) || null !== $this->get($value);
```

File: src/Symfony/Component/HttpFoundation/Tests/AcceptHeaderTest.php (hunk 1 above)
Comment (yoeunes) [reply src/Symfony/Component/HttpFoundation/Tests/AcceptHeaderTest.php]: Thanks, @nicolas-grekas ! I've applied the suggestions

File: src/Symfony/Component/HttpFoundation/AcceptHeader.php (hunk 2 above)
Comment (yoeunes) [reply src/Symfony/Component/HttpFoundation/AcceptHeader.php]: 🙏🏼

**Comment by Spomky** [comment]
Hi @yoeunes,

From what I understand, this looks more like an enhancement of the existing behaviour rather than a bug fix. Is that correct?
If it is indeed a bug fix, it should probably target 6.4 instead of 7.4.

Thanks!

**Comment by yoeunes** [comment]
Hi @Spomky, I consider this a bug fix because the current implementation incorrectly overwrites header items (e.g., `text/plain;format=flowed` (q=1.0) is lost if `text/plain;format=fixed` (q=0.4) is also present) which breaks content negotiation

If it's confirmed as a bug fix, should I rebase this onto 6.4 instead? Let me know your thoughts or if more details are needed

File: src/Symfony/Component/HttpFoundation/AcceptHeader.php [hunk 3]
```diff
@@ -73,15 +73,39 @@ public function __toString(): string
...
      * Returns given value's item, if exists.
      */
     public function get(string $value): ?AcceptHeaderItem
     {
-        return $this->items[$value] ?? $this->items[explode('/', $value)[0].'/*'] ?? $this->items['*/*'] ?? $this->items['*'] ?? null;
+        $queryItem = AcceptHeaderItem::fromString($value.';q=1');
+        $baseValue = $queryItem->getValue();
+        $queryAttributes = $queryItem->getAttributes();
+        $parametersString = $this->buildCanonicalParams($queryAttributes);
+        $canonicalKey = $baseValue.($parametersString ? ';'.$parametersString : '');
```
Comment (andesk) [inline src/Symfony/Component/HttpFoundation/AcceptHeader.php]:
```suggestion
        $parametersString = $this->buildCanonicalParams($queryItem->getAttributes());
        $canonicalKey = $queryItem->getValue().($parametersString ? ';'.$parametersString : '');
```

File: src/Symfony/Component/HttpFoundation/AcceptHeader.php [hunk 4]
```diff
@@ -91,7 +115,16 @@ public function get(string $value): ?AcceptHeaderItem
      */
     public function add(AcceptHeaderItem $item): static
     {
-        $this->items[$item->getValue()] = $item;
+        $baseValue = $item->getValue();
+        $itemAttributes = $item->getAttributes();
+
+        // Canonicalize parameters: sort by name, format as 'name=value' or 'name'
+        $parametersString = $this->buildCanonicalParams($itemAttributes);
+        $canonicalKey = $baseValue.($parametersString ? ';'.$parametersString : '');
```
Comment (andesk) [inline src/Symfony/Component/HttpFoundation/AcceptHeader.php]:
```suggestion
        // Canonicalize parameters: sort by name, format as 'name=value' or 'name'
        $parametersString = $this->buildCanonicalParams($item->getAttributes());
        $canonicalKey = $item->getValue().($parametersString ? ';'.$parametersString : '');
```

Comment (andesk) [inline src/Symfony/Component/HttpFoundation/AcceptHeader.php]:
```suggestion
        // Canonicalize parameters: sort by name, format as 'name=value' or 'name'
        $parametersString = $this->buildCanonicalParams($item->getAttributes());
        $canonicalKey = $item->getValue().($parametersString ? ';'.$parametersString : '');
```

File: src/Symfony/Component/HttpFoundation/AcceptHeader.php (hunk 3 above)
Comment (andesk) [reply src/Symfony/Component/HttpFoundation/AcceptHeader.php]: It might be even easier to rename the `buildCanonicalParams` to `buildCanonicalKey` and change the method signature to expect an AcceptHeaderItem? Seems to be a simpler and more readable encapsulation to me.

File: src/Symfony/Component/HttpFoundation/AcceptHeader.php [hunk 5]
```diff
@@ -147,4 +180,145 @@ private function sort(): void
...
+    /**
+     * Builds a canonical string representation of attributes.
+     *
+     * @param array<string, mixed> $attributes
+     */
+    private function buildCanonicalParams(array $attributes): string
+    {
+        $normalizedAttributes = [];
+        foreach ($attributes as $name => $value) {
+            $lowerName = strtolower($name);
```
Comment (andesk) [inline src/Symfony/Component/HttpFoundation/AcceptHeader.php]: I am not sure whether the according RFC says anything about case-(in)sensitivity of parameter names. Should we do a `strtolower()` therefore?

File: src/Symfony/Component/HttpFoundation/AcceptHeader.php [hunk 6]
```diff
@@ -147,4 +180,145 @@ private function sort(): void
...
+            if ('q' === $lowerName) {
+                continue;
+            }
+            $normalizedAttributes[$lowerName] = $value;
+        }
```
Comment (andesk) [inline src/Symfony/Component/HttpFoundation/AcceptHeader.php]: Then we could simplify to: 
```suggestion
        unset($attributes['q]);
```

File: src/Symfony/Component/HttpFoundation/AcceptHeader.php [hunk 7]
```diff
@@ -147,4 +180,145 @@ private function sort(): void
...
+        ksort($normalizedAttributes);
+        $parameterParts = [];
+        foreach ($normalizedAttributes as $name => $value) {
+            if (null === $value) {
+                $parameterParts[] = $name;
+            } else {
+                $quotedValue = \is_string($value) && str_contains($value, ' ') ? '"'.addslashes($value).'"' : $value;
+                $parameterParts[] = $name.'='.$quotedValue;
```
Comment (andesk) [inline src/Symfony/Component/HttpFoundation/AcceptHeader.php]: Which cases does this "quoting" try to mitigate? 🤔 boolean true = string "true"?

File: src/Symfony/Component/HttpFoundation/AcceptHeader.php [hunk 8]
```diff
@@ -147,4 +180,145 @@ private function sort(): void
...
+            if ($a->getQuality() !== $b->getQuality()) {
+                return $b->getQuality() <=> $a->getQuality();
+            }
+            $parameterCountA = \count($this->getMediaParams($a));
+            $parameterCountB = \count($this->getMediaParams($b));
+            if ($parameterCountA !== $parameterCountB) {
+                return $parameterCountB <=> $parameterCountA;
+            }
+
+            return $a->getIndex() <=> $b->getIndex();
```
Comment (andesk) [inline src/Symfony/Component/HttpFoundation/AcceptHeader.php]: To all I know, the `<=>` comparison allows to simplify two custom checks into a check on an array of values, with the most important comparison criteria sorted first:
```suggestion
                $comparison = [$this->getSpecificity($b, $queryItem), $b->getQuality(), count($this->getMediaParams($b)] <=> [$this->getSpecificity($a, $queryItem), $a->getQuality(), count($this->getMediaParams($a)];
                if ($comparison !== 0) {
                    return $comparison;
                }
                return $a->getIndex() <=> $b->getIndex();
            }
```

File: src/Symfony/Component/HttpFoundation/AcceptHeader.php [hunk 9]
```diff
@@ -147,4 +180,145 @@ private function sort(): void
...
+        return implode(';', $parameterParts);
+    }
+
+    /**
+     * Checks if a given header item (range) matches a queried item (value).
+     *
+     * @param AcceptHeaderItem $item      The item from the Accept header (e.g., text/*;format=flowed)
+     * @param AcceptHeaderItem $queryItem The item being queried (e.g., text/plain;format=flowed;charset=utf-8)
+     */
+    private function matches(AcceptHeaderItem $item, AcceptHeaderItem $queryItem): bool
```
Comment (andesk) [inline src/Symfony/Component/HttpFoundation/AcceptHeader.php]: This whole method feels hard to read and understand. You tend to create temporary variables a lot, I made some suggestions above that try to reduce that. It might be worth revisiting this method for such cases as well? 🙂

File: src/Symfony/Component/HttpFoundation/AcceptHeader.php [hunk 10]
```diff
@@ -147,4 +180,145 @@ private function sort(): void
...
+    {
+        $requestedValue = $queryItem->getValue();
+        if (!str_contains($requestedValue, '/')) {
+            // Charset/Language: exact or *
+            $rangeValue = $item->getValue();
+
+            return strtolower($rangeValue) === strtolower($requestedValue) || '*' === strtolower($rangeValue) || '*/*' === strtolower($rangeValue);
```
Comment (andesk) [inline src/Symfony/Component/HttpFoundation/AcceptHeader.php]: Again, can we be 100% sure that strtolower is the expected behavior of RFC9110? Also, what value does a string have, so that it's return value of `strtolower` equals `*` or '*/*'? 😇 😁

File: src/Symfony/Component/HttpFoundation/AcceptHeader.php (hunk 9 above)
Comment (andesk) [reply src/Symfony/Component/HttpFoundation/AcceptHeader.php]: Trying to comply the RFC adds quite some complexity to this class, which is demonstrated particularly in this method...

File: src/Symfony/Component/HttpFoundation/AcceptHeader.php (hunk 10 above)
Comment (andesk) [reply src/Symfony/Component/HttpFoundation/AcceptHeader.php]: Same for below...

**Review by andesk — COMMENTED** [review]
Thanks for taking the time to look into the issue I've created yesterday! 👍 

It feels like the implementation might be a bit brittle in regards of some assumptions made on the case-(in)sensitivity comparison of two media type strings? Also, certainly having more data to take into account for matching makes things harder. Having test coverage is great, maybe we can improve/simplify the logic still in some areas?

**Comment by yoeunes** [comment]
Hi @andesk, I'm consolidating my responses to your comments here to keep the thread tidy.

Thanks for the detailed review. I've pushed a full refactor that applies your suggestions, makes the code more readable, and adds explanatory comments.

Regarding case-insensitivity, you are correct. I'm now normalizing parameter names using `strtolower()` when building the canonical key. This aligns with RFC 9110 (Section 5.6.6) and correctly handles duplicates (e.g., `Charset` vs `charset`).
[https://www.rfc-editor.org/rfc/rfc9110.html#section-5.6.6](https://www.rfc-editor.org/rfc/rfc9110.html#section-5.6.6)

The PR should be ready for another look. Thanks!

File: src/Symfony/Component/HttpFoundation/AcceptHeader.php [hunk 11]
```diff
@@ -147,4 +164,159 @@ private function sort(): void
...
+
+        foreach ($this->getMediaParams($item) as $name => $value) {
+            if (null === $value) {
+                $parts[] = $name; // Flag parameter (e.g., "flowed")
+                continue;
+            }
+
+            // Quote values containing spaces, commas, semicolons, or equals per RFC 9110
+            // This handles cases like 'format="value with space"' or similar.
+            $quotedValue = (\is_string($value) && preg_match('/[\s;,=]/', $value))
```
Comment (derrabus) [inline src/Symfony/Component/HttpFoundation/AcceptHeader.php]:
```suggestion
            $quotedValue = (\is_string($value) && 1 === preg_match('/[\s;,=]/', $value))
```

File: src/Symfony/Component/HttpFoundation/Tests/AcceptHeaderTest.php [hunk 12]
```diff
@@ -128,5 +130,69 @@ public static function provideDefaultValueData()
...
+        $header = AcceptHeader::fromString($headerString);
+
+        $start = microtime(true);
+        for ($j = 0; $j < 1000; ++$j) {
+            $header->get('text/plain;param50=value');
+        }
+        $duration = microtime(true) - $start;
+
+        // No assert, just for manual check; should be < 1s
+        $this->assertLessThan(1.0, $duration, 'Performance test for large header');
```
Comment (derrabus) [inline src/Symfony/Component/HttpFoundation/Tests/AcceptHeaderTest.php]: Not sure if we want to have this kind of test. It does not test functionality and will certainly slow down our test suite.

**Review by derrabus — COMMENTED** [review]
Thank you for working on this issue.

I think, we should add additional tests for `Request::getAcceptableContentTypes()` and `Request::getPreferredFormat()` because they're directly impacted by this change.

**Comment by yoeunes** [comment]
Hi @derrabus, thank you for your review and feedback!

I've just pushed an update to add the requested tests for `Request::getAcceptableContentTypes()` and `Request::getPreferredFormat()`, covering scenarios with parameters, quality sorting, wildcards, case-insensitivity

Let me know if anything else is needed.

**Review by derrabus — APPROVED** [review]

**Review by Spomky — APPROVED** [review]
👍 Many thanks!

**Comment by nicolas-grekas** [comment]
Thank you @yoeunes.

**Comment by nicolas-grekas** [comment]
This fails on 7.4, with some implicit dependency:
- fail: ./phpunit src/Symfony/Component/HttpFoundation/
- pass: ./phpunit src/Symfony/Component/HttpFoundation/ --filter testGetPreferredFormatRfc9110 

We missed something.

Could you please have a look @yoeunes?

Not related to the failure, but this would be nicer than an array_map:
```diff
--- a/src/Symfony/Component/HttpFoundation/AcceptHeader.php
+++ b/src/Symfony/Component/HttpFoundation/AcceptHeader.php
@@ -48,16 +48,19 @@ class AcceptHeader
     {
         $parts = HeaderUtils::split($headerValue ?? '', ',;=');

-        return new self(array_map(function ($subParts) {
-            static $index = 0;
+        $items = [];
+        $index = 0;
+        foreach ($parts as $subParts) {
             $part = array_shift($subParts);
             $attributes = HeaderUtils::combine($subParts);

             $item = new AcceptHeaderItem($part[0], $attributes);
             $item->setIndex($index++);

-            return $item;
-        }, $parts));
+            $items[] = $item;
+        }
+
+        return new self($items);
     }
```

**Comment by nicolas-grekas** [comment]
FYI I'm having a look at my own previous comment.
