### PR TITLE
[Finder]  use proper keys to not override appended files

### LINKED ISSUE #40022: [Finder] BC: Manuelly added files are missing
**Symfony version(s) affected**: 4.4.19

**Description**  
Finder lists only one manuelly added file

**How to reproduce**  
```php
$finder = new Finder();
        $finder
            ->sortByName()
            ->files()
            ->followLinks()
            ->name('*.php');

        $finder->append([__DIR__ . '/Context.php']);
        $finder->append([__DIR__ . '/Logger.phpp']);
        $finder->append([__DIR__ . '/Serializer.php']);

        foreach ($finder as $item) {
            var_dump($item->getPathname());
        }
 ````

Output: v4.4.19:
string(59) "/var/www/html/vendor/zircote/swagger-php/src/Serializer.php"

Output: v4.4.18
string(56) "/var/www/html/vendor/zircote/swagger-php/src/Context.php"
string(56) "/var/www/html/vendor/zircote/swagger-php/src/Logger.phpp"
string(59) "/var/www/html/vendor/zircote/swagger-php/src/Serializer.php"

        

**Possible Solution**  
Revert https://github.com/symfony/finder/commit/94a9b864774d7d20635607c975e3d92a7d3b1ba9

**Additional context**

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40022
| License       | MIT
| Doc PR        |

### CODE REVIEW

File: src/Symfony/Component/Finder/Finder.php [hunk 1]
```diff
@@ -669,7 +669,8 @@ public function append($iterator)
         } elseif ($iterator instanceof \Traversable || \is_array($iterator)) {
             $it = new \ArrayIterator();
             foreach ($iterator as $file) {
-                $it->append($file instanceof \SplFileInfo ? $file : new \SplFileInfo($file));
+                $file = $file instanceof \SplFileInfo ? $file : new \SplFileInfo($file);
+                $it[$file->getRealPath()] = $file;
```
Comment (xabbuh) [inline src/Symfony/Component/Finder/Finder.php]: This won't work for non-existing files. Not sure if that's an issue though.

**Review by shyim — APPROVED** [review]
Our Swagger page does load again with this fix

File: src/Symfony/Component/Finder/Finder.php (hunk 1 above)
Comment (stof) [reply src/Symfony/Component/Finder/Finder.php]: Instead of `getRealPath()`, I suggest using`getPathname()`, which would also work for stream wrappers not supporting `realpath()`.

Non-existent files are OK to me. I don't think this is an expected supported case for the Finder anyway.

**Review by jderusse — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.
