### PR TITLE
[Mime] Fix TextPart using an unknown File

### LINKED ISSUE #57258: [Mime] TextPart does not check for file path
### Symfony version(s) affected

All current versions

### Description

When using DataPartFile with a wrong path (file does not exists) and then calling `->getBody()` it returns an empty string instead of an error.

### How to reproduce

`(new DataPartFile('/some/wrong/path/to/file.md'))->getBody() === ''; // true`.

### Possible Solution

It is because Symfony does not use strict types. When calling `file_get_contents` in this code : 
```php
public function getBody(): string
    {
        if ($this->body instanceof File) {
            return file_get_contents($this->body->getPath());
        }

        if (null === $this->seekable) {
            return $this->body;
        }

        if ($this->seekable) {
            rewind($this->body);
        }

        return stream_get_contents($this->body) ?: '';
    }
```

It automatically converts the `false` to `''`.

Maybe wirth checking if false then throw `throw new InvalidArgumentException(sprintf('Path "%s" is not readable.', $path));` like in `__construct`.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by fabpot**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #57258 
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/Mime/Tests/Part/TextPartTest.php [hunk 1]
```diff
@@ -55,6 +55,16 @@ public function testConstructorWithFile()
         $this->assertSame('content', implode('', iterator_to_array($p->bodyToIterable())));
     }
 
+    public function testConstructorWithUnknownFile()
+    {
+        $p = new TextPart(new File(\dirname(__DIR__).'/Fixtures/unknown.txt'));
+
+        // Exception should be thrown only when the body is accessed
+        $this->expectException(InvalidArgumentException::class);
```
Comment (xabbuh) [inline src/Symfony/Component/Mime/Tests/Part/TextPartTest.php:64]: the class is missing a `use` statement for this exception

Comment (fabpot) [reply src/Symfony/Component/Mime/Tests/Part/TextPartTest.php:64]: oops
