### PR TITLE
[Serializer] fix decoding float XML attributes starting with 0

### LINKED ISSUE #38666: XmlEncoder: unexpected type of decoded float attributes which start with zero
**Symfony version(s) affected**: 3.4

**Description**  
If an XML attribute contains a positive float value which starts with `0`, e.g. `0.123`, XmlEncoder will decode it as a string.
If a float value starts with some other number, or is negative, then it is decoded as a float.

**How to reproduce**  
```php
<?php
require_once __DIR__.'/vendor/autoload.php';
use Symfony\Component\Serializer\Encoder\XmlEncoder;

$encoder = new XmlEncoder();

$xml = '<document value="0.123">...</document>';
$result = $encoder->decode($xml, 'xml');
var_dump($result);
// array(2) {
//   ["@value"]=>
//   string(5) "0.123"        <-- a float was expected, but it's a string
//   ["#"]=>
//   string(3) "..."
// }
```

Note that:
```php
$xml = '<document value="1.123">...</document>';
$result = $encoder->decode($xml, 'xml');
var_dump($result);
// array(2) {
//   ["@value"]=>
//   float(1.123)        <-- float, as expected
//   ["#"]=>
//   string(3) "..."
// }

$xml = '<document value="-1.123">...</document>';
$result = $encoder->decode($xml, 'xml');
var_dump($result);
// array(2) {
//   ["@value"]=>
//   float(-1.123)        <-- negative values are also fine
//   ["#"]=>
//   string(3) "..."
// }

$xml = '<document value="-0.123">...</document>';
$result = $encoder->decode($xml, 'xml');
var_dump($result);
// array(2) {
//   ["@value"]=>
//   float(-0.123)        <-- ...even if negative value starts with 0
//   ["#"]=>
//   string(3) "..."
// }
```

**Possible Solution**  
It looks like this behaviour was introduced in #32438 (as suggested [here](https://github.com/symfony/symfony/pull/23122#discussion_r121886667)).
The naive approach would be to just extend [the added check](https://github.com/symfony/symfony/blob/1eead3f2af67049f3701e51f098f6bc8c6e7d204/src/Symfony/Component/Serializer/Encoder/XmlEncoder.php#L307) with the "_but zero is not followed by a dot_" condition, like in #38669.
Seems to work, but it feels like a nasty workaround, not a proper solution. And probably someone will find another case where it fails to produce a reasonable result.
Also, this section of code, i.e. trying to decode floats, has already been changed and fixed several times before (#22478, 8f6e67d3199453bc8b7fbdbe92e9e02fb4d0bf00 and #32438), so it's not that easy to get it right and consider all edge cases. Maybe it would be better to try a different approach, something like #36482 or similar?
Btw, I assume we don't want to support comma as decimal separator.

**Additional context**  
Normally I would say it's a limitation of the XmlEncoder, but returning a string only for floats which start with zero - it might be super confusing and difficult to debug.
For example (actually, that's how I found it), if you have a method which accepts floats (type hinting it) and receives as arguments values decoded by XmlEncoder, and the XML data looks like this:
```
...
<foo bar="1.9558"/>
<foo bar="25.653"/>
<foo bar="7.4615"/>
<foo bar="0.86828"/>
<foo bar="317.62"/>
...
```
The process will be sometimes failing, but it will look very randomly. Looking at the data, everything seems to be valid.

### PR DESCRIPTION
**Pull request by marcin-kruk**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38666
| License       | MIT
| Doc PR        | n/a

This is a naive approach to fix #38666, assuming it is something worth fixing.

I checked different cases and it seems to be fixing all of them, but I bet there will be some other edge cases which still won't be covered properly.

### CODE REVIEW

File: src/Symfony/Component/Serializer/Tests/Encoder/XmlEncoderTest.php [hunk 1]
```diff
@@ -268,10 +268,10 @@ public function testDecodeFloatAttribute()
     {
         $source = <<<XML
 <?xml version="1.0"?>
-<document index="-12.11">Name</document>
```
Comment (Nyholm) [inline src/Symfony/Component/Serializer/Tests/Encoder/XmlEncoderTest.php:271]: Let's not change this test. But feel free to add assertions for `12.11` and `0.123` in the `testDecodeFloatAttribute`

File: src/Symfony/Component/Serializer/Encoder/XmlEncoder.php [hunk 2]
```diff
@@ -304,7 +304,9 @@ private function parseXmlAttributes(\DOMNode $node, array $context = [])
         $typeCastAttributes = $this->resolveXmlTypeCastAttributes($context);
 
         foreach ($node->attributes as $attr) {
-            if (!is_numeric($attr->nodeValue) || !$typeCastAttributes || (isset($attr->nodeValue[1]) && '0' === $attr->nodeValue[0])) {
+            if (!is_numeric($attr->nodeValue) ||
+                !$typeCastAttributes ||
+                (isset($attr->nodeValue[1]) && '0' === $attr->nodeValue[0] && '.' !== $attr->nodeValue[1])) {
```
Comment (Nyholm) [inline src/Symfony/Component/Serializer/Encoder/XmlEncoder.php]: Will this also work for XML like this?

```xml
<document index="0">Name</document>
```

**Review by Nyholm — COMMENTED** [review]
Thank you for this PR. I see you added tests and everything. Well done!

I have some questions that I would like your help answering.

File: src/Symfony/Component/Serializer/Encoder/XmlEncoder.php (hunk 2 above)
Comment (marcin-kruk) [reply src/Symfony/Component/Serializer/Encoder/XmlEncoder.php]: I'd assume so, there is `isset($attr->nodeValue[1])` check

Comment (Nyholm) [reply src/Symfony/Component/Serializer/Encoder/XmlEncoder.php]: Oh. I missed that. Thank you

File: src/Symfony/Component/Serializer/Tests/Encoder/XmlEncoderTest.php (hunk 1 above)
Comment (marcin-kruk) [reply src/Symfony/Component/Serializer/Tests/Encoder/XmlEncoderTest.php:271]: I've decided to change it because this test was exactly the same as the next one, `testDecodeNegativeFloatAttribute`, i.e. the same values.

So do you suggest keeping `-12.11` here, adding `12.11` and `0.123` in this xml, **and** still keeping the `testDecodeNegativeFloatAttribute` method (with `-12.11` repeated)?
Fine with me, I just want to clarify it.

**Comment by marcin-kruk** [comment]
It seems that fabbot is asking me to fix something I didn't change - an exception message formatting in a different method.
I updated my branch with upstream and it's up to date, so it's not the reason.
Any ideas why it failed and how to sort it out?

File: src/Symfony/Component/Serializer/Tests/Encoder/XmlEncoderTest.php (hunk 1 above)
Comment (Nyholm) [reply src/Symfony/Component/Serializer/Tests/Encoder/XmlEncoderTest.php:271]: I didn’t see that we have the exact same test. Modifying existing tests is usually something that should be avoided in a big fix PR. 

I want to make sure all three cases are covered. Exactly where does not matter too much.

File: src/Symfony/Component/Serializer/Encoder/XmlEncoder.php [hunk 3]
```diff
@@ -304,7 +304,9 @@ private function parseXmlAttributes(\DOMNode $node, array $context = [])
         $typeCastAttributes = $this->resolveXmlTypeCastAttributes($context);
 
         foreach ($node->attributes as $attr) {
-            if (!is_numeric($attr->nodeValue) || !$typeCastAttributes || (isset($attr->nodeValue[1]) && '0' === $attr->nodeValue[0])) {
+            if (!is_numeric($attr->nodeValue) ||
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Encoder/XmlEncoder.php]: please keep everything on one line

**Review by nicolas-grekas — APPROVED** [review]
(with one minor comment)

File: src/Symfony/Component/Serializer/Encoder/XmlEncoder.php [hunk 4]
```diff
@@ -304,7 +304,7 @@ private function parseXmlAttributes(\DOMNode $node, array $context = [])
         $typeCastAttributes = $this->resolveXmlTypeCastAttributes($context);
 
         foreach ($node->attributes as $attr) {
-            if (!is_numeric($attr->nodeValue) || !$typeCastAttributes || (isset($attr->nodeValue[1]) && '0' === $attr->nodeValue[0])) {
+            if (!is_numeric($attr->nodeValue) || !$typeCastAttributes || (isset($attr->nodeValue[1]) && '0' === $attr->nodeValue[0] && '.' !== $attr->nodeValue[1])) {
```
Comment (jderusse) [inline src/Symfony/Component/Serializer/Encoder/XmlEncoder.php:307]: what's about negative numbers? `-01` ?

Comment (marcin-kruk) [reply src/Symfony/Component/Serializer/Encoder/XmlEncoder.php:307]: We still get `-1.0` as float. Exactly how it is now, without this change.

But to be honest I'm not sure what I would expect to receive after decoding it. Considering #32438, probably `"-01"` as a string, but I'm not sure.
Also, one can always use the `xml_type_cast_attributes` context option to force getting a string back.

Comment (Nyholm) [reply src/Symfony/Component/Serializer/Encoder/XmlEncoder.php:307]: "-01" looks like a string to me.

**Review by Nyholm — APPROVED** [review]
I am happy to merge after @jderusse is happy

**Review by jderusse — APPROVED** [review]
Thank you

**Review by dunglas — APPROVED** [review]
good catch!

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @marcin-kruk.
