### PR TITLE
[BrowserKit] Improve the error message when `submitForm()` can't find the form

### LINKED ISSUE #49826: [Tests] Improve the error message when submitForm() can't find the form
### Description

I was creating a test that uses the `submitForm()` method (https://symfony.com/doc/current/testing.html#submitting-forms):

```php
$client->submitForm('Save changes', [
    'form[foo]' => '...',
    'form[bar]' => '...',
]);
```

However, this form didn't have the `Save changes` button (it was a copy-paste mistake).

The problem is that tests showed this error:

```
1) App\Tests\Controller\FooControllerTest::testSomething
InvalidArgumentException: The current node list is empty.
```

I'd like to see a more useful error message. For example:

```
1) App\Tests\Controller\FooControllerTest::testSomething
InvalidArgumentException: The form doesn't contain any button with "Save changes" as its content, id, value or name.
```

### Example

_No response_

### PR DESCRIPTION
**Pull request by alamirault**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #49826 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

When form is not found, error message is now `The form doesn't contain any button with "Save changes" as its content, id, value or name.` instead of `The current node list is empty.`

### CODE REVIEW

File: src/Symfony/Component/BrowserKit/Tests/AbstractBrowserTest.php [hunk 1]
```diff
@@ -358,6 +358,7 @@ public function testSubmitFormNotFound()
             $this->fail('->submitForm() throws a \InvalidArgumentException if the form could not be found');
         } catch (\Exception $e) {
             $this->assertInstanceOf(\InvalidArgumentException::class, $e, '->submitForm() throws a \InvalidArgumentException if the form could not be found');
+            $this->assertSame('The form doesn\'t contain any button with "Register" as its content, id, value or name.', $e->getMessage());
```
Comment (stof) [inline src/Symfony/Component/BrowserKit/Tests/AbstractBrowserTest.php]: I suggest using `expectException` and `expectExceptionMessage` to write this test instead of those manual assertions on a caught exception.

File: src/Symfony/Component/BrowserKit/AbstractBrowser.php [hunk 2]
```diff
@@ -333,6 +333,11 @@ public function submitForm(string $button, array $fieldValues = [], string $meth
         }
 
         $buttonNode = $this->crawler->selectButton($button);
+
+        if (0 === $buttonNode->count()) {
+            throw new \InvalidArgumentException(sprintf('The form doesn\'t contain any button with "%s" as its content, id, value or name.', $button));
```
Comment (javiereguiluz) [inline src/Symfony/Component/BrowserKit/AbstractBrowser.php]: @alamirault thanks a lot for working on this!

After proposing the new error message in #49826 I realized that I was missing that a page can contain more than one form. So, I think we should tweak the message like:

```
There are no forms that contain a button with ...
```

Let's hear if others have other suggestions to make this message as clear as possible. Thanks!

Comment (stof) [reply src/Symfony/Component/BrowserKit/AbstractBrowser.php]: Note that this query looks for buttons even outside forms. If the button with than name is not in a form, the failure will be in the `->form()` method.

This should probably say `There is no button with...` here

Comment (alamirault) [reply src/Symfony/Component/BrowserKit/AbstractBrowser.php]: Agreed with you @stof. I updated PR

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @alamirault.
