### PR TITLE
[Cache] fix compatibility with redis extension 6.0.3+

### LINKED ISSUE #57884: Redis6Proxy incompatible with phpredis
### Symfony version(s) affected

7.1

### Description

After update https://github.com/phpredis/phpredis/commit/6ea5b3e08bdbf8cbe93e0dc56b18e8316d65097c

Get error:

```
 Declaration of Symfony\Component\Cache\Traits\Redis6Proxy::hSet($key, $member, $value): Redis|int|false must be compatible with Redis::hSet(string $key, mixed ...$fields_and_vals): Redis|int|false {"file":"/app/vendor/symfony/cache/Traits/Redis6Proxy.php","exception":"[object] (ErrorException(code: 0): Declaration of Symfony\\Component\\Cache\\Traits\\Redis6Proxy::hSet($key, $member, $value): Redis|int|false must be compatible with Redis::hSet(string $key, mixed ...$fields_and_vals): Redis|int|false at /app/vendor/symfony/cache/Traits/Redis6Proxy.php:519)"
````

### How to reproduce

Create a symfony web project and inside it a Dockerfile with a php container which installs redis
...
FROM php:8.3.8-cli-alpine
...
RUN apk add --no-cache lz4-dev \
    && mkdir /tmp/phpredis \
    && cd /tmp/phpredis \
    && git clone --recurse-submodules https://github.com/phpredis/phpredis "php-redis" \
    && cd php-redis \
    && phpize \
    && ./configure --enable-redis-igbinary --enable-redis-lz4 --with-liblz4=/usr/lib \
    && make \
    && make install \
    && make clean \
    && docker-php-ext-enable redis \
    && rm -rf /tmp/phpredis
...

Run the docker container and open the website

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #57884
| License       | MIT

see the differences in the `redis.stub.php` and `redis_cluster.stub.php` files at https://github.com/phpredis/phpredis/compare/6.0.2...develop

### CODE REVIEW

File: src/Symfony/Component/Cache/Traits/RedisCluster6ProxyTrait.php [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+        {
+        }
+
+        public function publish($channel, $message): \RedisCluster|bool|int
+        {
+            return ($this->lazyObjectState->realInstance ??= ($this->lazyObjectState->initializer)())->publish(...\func_get_args());
+        }
+
+        public function waitaof($key_or_address, $numlocal, $numreplicas, $timeout): \RedisCluster|array|false
+        {
```
Comment (stof) [inline src/Symfony/Component/Cache/Traits/RedisCluster6ProxyTrait.php:31]: why aren't those calling the real instance ?

File: src/Symfony/Component/Cache/Traits/Redis6ProxyTrait.php [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+ *
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\Cache\Traits;
+
+if (version_compare(phpversion('redis'), '6.0.2', '>')) {
```
Comment (xabbuh) [inline src/Symfony/Component/Cache/Traits/Redis6ProxyTrait.php]: I wonder if we should compare with `6.1.0` instead (because of phpredis/phpredis#2530)

File: src/Symfony/Component/Cache/Traits/RedisCluster6ProxyTrait.php (hunk 1 above)
Comment (xabbuh) [reply src/Symfony/Component/Cache/Traits/RedisCluster6ProxyTrait.php:31]: copy and paste mistake

File: src/Symfony/Component/Cache/Traits/Redis6ProxyTrait.php (hunk 2 above)
Comment (xabbuh) [reply src/Symfony/Component/Cache/Traits/Redis6ProxyTrait.php]: A first RC for 6.1 has been tagged. I have updated the version tag accordingly here.

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Comment by derrabus** [comment]
I'm having a hard time merging this change from 7.1 to 7.2. Can you have a look, @xabbuh?

**Comment by xabbuh** [comment]
@derrabus done
