### PR TITLE
[Filesystem] better distinguish URL schemes and Windows drive letters

### LINKED ISSUE #45485: [Filesystem] Path::isAbsolute() returns false if repetitive forward slashes are encountered exactly after driver for Windows paths
### Symfony version(s) affected

5.4.0, 6.0.0

### Description

If an absolute path has more than one forward slashes exactly next to the Windows drive, the path is detected as not being absolute. Backward slashes are not problematic at all, and also forward slashes, except the current case.

For instance, calling `Path::isAbsolute()` on `'C://users/'` will return `false`, but for both `'C:/users//'` and `'C:\\\\users/'`, `true` is returned.

### How to reproduce

Run the following PHP codes:

```php
Path::isAbsolute('E://test');
```

```php
Path::isAbsolute('C:///windows');
```

```php
Path::isAbsolute(
    Path::join('C:', '\\users')
);
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #45485
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/Filesystem/Path.php [hunk 1]
```diff
@@ -368,7 +368,7 @@ public static function isAbsolute(string $path): bool
         }
 
         // Strip scheme
-        if (false !== $schemeSeparatorPosition = strpos($path, '://')) {
+        if ((false !== $schemeSeparatorPosition = strpos($path, '://')) && !preg_match('#^[A-Z]://#', $path)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Filesystem/Path.php]: let's be more lenient?
```suggestion
        if (false !== $schemeSeparatorPosition = strpos($path, '://') && 1 !== $schemeSeparatorPosition) {
```

Comment (xabbuh) [reply src/Symfony/Component/Filesystem/Path.php]: works for me as well

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.
