### PR TITLE
[Validator] Add the `format` option to the `Ulid` constraint to allow accepting different ULID formats

### LINKED ISSUE #57398: [Uid] isValid fails when passing non Rfc4122 IDs
### Symfony version(s) affected

7.1.1

### Description

When trying to validate UUIDs in a format that's not Rfc4122 it'll always fail.

### How to reproduce

```php
Uuid::isValid("1CCD2w4mK2m455S2BAXFht"); //should be true since it's a valid UUIDv7 in base58 format.
```

### Possible Solution

The `isValid` seems to contain a regex that checks for the Rfc4122 structure, probably should be expanded to check the other representations as well.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | -
| License       | MIT

Related to #51540 and #57398

### CODE REVIEW

File: src/Symfony/Component/Validator/Constraints/Ulid.php [hunk 1]
```diff
@@ -35,20 +35,27 @@ class Ulid extends Constraint
...
+    public const VALIDATE_BASE_32 = 'base32';
+    public const VALIDATE_BASE_58 = 'base58';
+
     public string $message = 'This is not a valid ULID.';
+    public string $format = self::VALIDATE_BASE_32;
 
     /**
      * @param array<string,mixed>|null $options
      * @param string[]|null            $groups
+     * @param self::VALIDATE_*|null    $format
```
Comment (stof) [inline src/Symfony/Component/Validator/Constraints/Ulid.php]: shouldn't the constants be named `FORMAT_*` instead as they represent the available formats ?

File: src/Symfony/Component/Validator/Tests/Constraints/UlidValidatorTest.php [hunk 2]
```diff
@@ -81,6 +96,31 @@ public static function getInvalidUlids()
...
+
+        $this->validator->validate($ulid, $constraint);
+
+        $this->buildViolation('testMessage')
+            ->setParameter('{{ value }}', '"'.$ulid.'"')
+            ->setCode($code)
+            ->assertRaised();
+    }
+
+    public static function getInvalidBase58Ulids()
```
Comment (OskarStark) [inline src/Symfony/Component/Validator/Tests/Constraints/UlidValidatorTest.php]:
```suggestion
    public static function getInvalidBase58Ulids(): array
```

Comment (alexandre-daubois) [reply src/Symfony/Component/Validator/Tests/Constraints/UlidValidatorTest.php]: Updated

File: src/Symfony/Component/Validator/Constraints/Ulid.php (hunk 1 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/Validator/Constraints/Ulid.php]: Right! It's updated

File: src/Symfony/Component/Validator/CHANGELOG.md [hunk 3]
```diff
@@ -6,6 +6,7 @@ CHANGELOG
 
  * Make `PasswordStrengthValidator::estimateStrength()` public
  * Add the `Yaml` constraint for validating YAML content
+ * Add `Ulid::FORMAT_BASE_32` and `Ulid::FORMAT_BASE_58` to the `Uuid` constraint
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/CHANGELOG.md]:
```suggestion
 * Add the `format` option to the `Uuid` constraint to allow accepting different ULID formats
```

File: src/Symfony/Component/Validator/Constraints/Ulid.php [hunk 4]
```diff
@@ -35,20 +35,27 @@ class Ulid extends Constraint
...
         ?array $options = null,
         ?string $message = null,
         ?array $groups = null,
         mixed $payload = null,
+        ?string $format = null,
     ) {
         parent::__construct($options, $groups, $payload);
 
         $this->message = $message ?? $this->message;
+        $this->format = $format ?? $this->format;
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/Constraints/Ulid.php:60]: we should also validate that the selected format is valid

File: src/Symfony/Component/Validator/Constraints/UlidValidator.php [hunk 5]
```diff
@@ -39,17 +39,27 @@ public function validate(mixed $value, Constraint $constraint): void
...
 
         $value = (string) $value;
+        $requiredLength = match ($constraint->format) {
+            Ulid::FORMAT_BASE_32 => 26,
+            Ulid::FORMAT_BASE_58 => 22,
+            default => throw new \InvalidArgumentException(sprintf('The "%s" validation format is not supported.', $constraint->format)),
+        };
 
-        if (26 !== \strlen($value)) {
+        $requiredCharset = match ($constraint->format) {
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/Constraints/UlidValidator.php]: I wonder if we shouldn't merge both `match` blocks (using `switch` then)

File: src/Symfony/Component/Validator/Constraints/Ulid.php (hunk 4 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/Validator/Constraints/Ulid.php:60]: I did validate in the validator but indeed it may be a little late. Better to do it in the constructor 👍

File: src/Symfony/Component/Validator/Constraints/UlidValidator.php (hunk 5 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/Validator/Constraints/UlidValidator.php]: Makes sense

File: src/Symfony/Component/Validator/Constraints/Ulid.php [hunk 6]
```diff
@@ -35,20 +35,31 @@ class Ulid extends Constraint
...
+
+        if (!\in_array($this->format, [self::FORMAT_BASE_32, self::FORMAT_BASE_58], true)) {
+            throw new \InvalidArgumentException(sprintf('The "%s" validation format is not supported.', $format));
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/Constraints/Ulid.php]:
```suggestion
            throw new ConstraintDefinitionException(sprintf('The "%s" validation format is not supported.', $format));
```

File: src/Symfony/Component/Validator/Constraints/UlidValidator.php [hunk 7]
```diff
@@ -40,16 +40,28 @@ public function validate(mixed $value, Constraint $constraint): void
...
                 ->setParameter('{{ value }}', $this->formatValue($value))
-                ->setCode(26 > \strlen($value) ? Ulid::TOO_SHORT_ERROR : Ulid::TOO_LONG_ERROR)
+                ->setCode($requiredLength > \strlen($value) ? Ulid::TOO_SHORT_ERROR : Ulid::TOO_LONG_ERROR)
                 ->addViolation();
 
             return;
         }
 
-        if (\strlen($value) !== strspn($value, '0123456789ABCDEFGHJKMNPQRSTVWXYZabcdefghjkmnpqrstvwxyz')) {
+        if (\strlen($value) !== strspn($value, $requiredCharset)) {
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/Constraints/UlidValidator.php:60]: Should we add the format used to validate as a parameter to the violation as well? This way users can reuse it in their custom validation error messages.

File: src/Symfony/Component/Validator/Constraints/Ulid.php (hunk 6 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/Validator/Constraints/Ulid.php]: I wasn't aware of this exception class, thanks!

File: src/Symfony/Component/Validator/Constraints/UlidValidator.php (hunk 7 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/Validator/Constraints/UlidValidator.php:60]: Totally agree

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

File: src/Symfony/Component/Validator/CHANGELOG.md [hunk 8]
```diff
@@ -6,6 +6,7 @@ CHANGELOG
 
  * Make `PasswordStrengthValidator::estimateStrength()` public
  * Add the `Yaml` constraint for validating YAML content
+ * Add the `format` option to the `Uuid` constraint to allow accepting different ULID formats
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/CHANGELOG.md]: (please rebase also)
```suggestion
 * Add the `format` option to the `Ulid` constraint to allow accepting different ULID formats
```

Comment (alexandre-daubois) [reply src/Symfony/Component/Validator/CHANGELOG.md]: Indeed!

**Comment by nicolas-grekas** [comment]
IIUC, this doesn't fix #57398, which is about allowing base58 UUIDs. Did I miss something?

**Comment by alexandre-daubois** [comment]
That's right, I think I mixed up the issues. But I guess this opens up the way to accepting multiple formats in Uuid and Ulid constraints. I guess it would worth on or two follow-up PRs:

- Supporting RFC4122 in Ulid
- Supporting Base58 in Uuid

What do you think?

**Comment by nicolas-grekas** [comment]
Apparently there is a need for that yes :)

File: src/Symfony/Component/Validator/Constraints/UlidValidator.php [hunk 9]
```diff
@@ -40,31 +40,54 @@ public function validate(mixed $value, Constraint $constraint): void
...
+            case Ulid::FORMAT_BASE_32:
+                $requiredLength = 26;
+                $requiredCharset = '0123456789ABCDEFGHJKMNPQRSTVWXYZabcdefghjkmnpqrstvwxyz';
+                break;
+            case Ulid::FORMAT_BASE_58:
+                $requiredLength = 22;
+                $requiredCharset = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
+                break;
+                // no default, the constraint constructor already ensures a valid format
+        }
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraints/UlidValidator.php]: what about this?
```suggestion
        [$requiredLength, $requiredCharset] = match ($constraint->format) {
            Ulid::FORMAT_BASE_32 => [26, '0123456789ABCDEFGHJKMNPQRSTVWXYZabcdefghjkmnpqrstvwxyz'],
            Ulid::FORMAT_BASE_58 => [22, '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'],
        };
```

Comment (alexandre-daubois) [reply src/Symfony/Component/Validator/Constraints/UlidValidator.php]: I keep forgetting about this syntax, it is indeed better

**Comment by nicolas-grekas** [comment]
Thank you @alexandre-daubois.
