### PR TITLE
[Validator] fix handling named arguments in `Existence` constraint

### LINKED ISSUE #62705: [Validator] Required and Optional Field Constraints in YAML
### Symfony version(s) affected

7

### Description

Hi,

We're seeing following deprecations when testing 7.4

```
   * 1x: Since symfony/validator 7.3: Using constraints not supporting named arguments is deprecated. Try adding the HasNamedArguments attribute to \Symfony\Component\Validator\Constraints\Optional.
        in /app/vendor/symfony/deprecation-contracts/function.php:25
   * 1x: Since symfony/validator 7.4: Passing an array of options to configure the "Symfony\Component\Validator\Constraints\Optional" constraint is deprecated, use named arguments instead.
        in /app/vendor/symfony/deprecation-contracts/function.php:25
   * 1x: Since symfony/validator 7.4: Support for evaluating options in the base Constraint class is deprecated. Initialize properties in the constructor of Symfony\Component\Validator\Constraints\Optional instead.
        in /app/vendor/symfony/deprecation-contracts/function.php:25
```

But it seems they cannot be solved, as the options from yaml will always be `[value => ...]` or `[constraints => ...]` at https://github.com/symfony/symfony/blob/120a6abe9b593752a91ee06c3e0174cd519a41e0/src/Symfony/Component/Validator/Constraints/Composite.php#L56-L58

### How to reproduce

https://symfony.com/doc/current/reference/constraints/Collection.html#required-and-optional-field-constraints

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62705
| License       | MIT

### CODE REVIEW

**Review by stof — APPROVED** [review]

File: src/Symfony/Component/Validator/Constraints/Existence.php [hunk 1]
```diff
@@ -20,6 +21,7 @@ abstract class Existence extends Composite
 {
     public array|Constraint $constraints = [];
 
+    #[HasNamedArguments]
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/Constraints/Existence.php:24]: we deprecated support for constraints having a constructor without the `#[HasNamedArguments]` attribute in 7.3, but we added the constructor here only in 7.4 when we deprecated passing option arrays to the base constraint

**Review by ro0NL — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.
