### PR TITLE
[Validator] Simplify `When::$expression`’s closure PHPDoc

### LINKED ISSUE #64073: [Assert] better PHPStan support for static closure expression
### Symfony version(s) affected

8.0.8

### Description

You can use static closure for expression in `Assert\When` https://symfony.com/doc/current/reference/constraints/When.html but PHPStan is not satisfied with a typed object.

```
Parameter $expression of attribute class                            
         Symfony\Component\Validator\Constraints\When constructor expects    
         (Closure(object):                                                   
         bool)|string|Symfony\Component\ExpressionLanguage\Expression,       
         Closure(App\Model\Discount): bool     
         given.              
```

How to ignore error
```neon
  ignoreErrors:
    -
      message: '#Parameter \$expression of attribute class [a-zA-Z0-9\\_]+ constructor expects \(Closure\(object\): bool\)\|string\|Symfony\\Component\\ExpressionLanguage\\Expression, Closure\([a-zA-Z0-9\\_]+\): bool given#'
```

### How to reproduce

```php
namespace App\Model;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

class Discount
{
    #[Assert\When(
        expression: static function (Discount $discount) {
            return $discount->getType() === 'percent';
        },
        constraints: [new Assert\Callback('doComplexValidation')],
    )]
    private ?string $type = null;

    public function doComplexValidation(ExecutionContextInterface $context, $payload): void
    {
        // ...
    }
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #64073
| License       | MIT

(Closure support for `When` was added to 7.3 by #59800.)

### CODE REVIEW

File: src/Symfony/Component/Validator/Constraints/When.php [hunk 1]
```diff
@@ -22,6 +22,8 @@
  * Conditionally apply validation constraints based on an expression using the ExpressionLanguage syntax.
  *
  * @see https://symfony.com/doc/current/components/expression_language.html
+ *
+ * @template T of object
```
Comment (derrabus) [inline src/Symfony/Component/Validator/Constraints/When.php]: If I don't use a closure, static analyzers won't be able to resolve this template variable.

**Review by derrabus — COMMENTED** [review]
Using generics here does not feel right. I wonder if this shouldn't be solved in the PHPStan-Symfony plugin instead. The type of the payload that the closure has to accept cannot be determined without additional logic. Your change will certainly silence false positives, but PHPStan would not know if the parameter type of the closure is actually correct.

File: src/Symfony/Component/Validator/Constraints/When.php (hunk 1 above)
Comment (MatTheCat) [reply src/Symfony/Component/Validator/Constraints/When.php]: Is that a problem if it’s only used by the closure?

Comment (derrabus) [reply src/Symfony/Component/Validator/Constraints/When.php]: Yes, because the static analyzer doesn't know the type of the `When` instance. This might cause false positives downstream.

**Comment by MatTheCat** [comment]
So I guess if we want to provide the right type through a plugin we should just type `\Closure` in the PHPDoc? That way people who don’t have the plugin won’t get false negatives?

**Comment by stof** [comment]
For now, we should indeed probably use `\Closure` without describing the signature, as a quick fix.
I don't think there is a way to describe in phpdoc that this closure must accept a type corresponding to the place where the attribute is used (also hard when using the constraints not as an attribute btw).

File: src/Symfony/Component/Validator/Constraints/When.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/Constraints/When.php]: so this should be removed, right?

Comment (MatTheCat) [reply src/Symfony/Component/Validator/Constraints/When.php]: Yes just did it

**Comment by nicolas-grekas** [comment]
Thank you @MatTheCat.
