### PR TITLE
Escape all special characters for parse_mode MARKDOWN_V2

### LINKED ISSUE #42697: [Notifier] [Telegram] Escaping special characters with MarkdownV2
**Symfony version(s) affected**: 5.3.6 and below

**Description**
When sending notification to Telegram that contains any special characters from the list  _ * [ ] ( ) ~` > # + - = | { } . ! ,  except dot which is already escaped, throws exception:

``` 
Message: "Handling "Symfony\Component\Notifier\Message\ChatMessage" failed: Unable to post the Telegram message: Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\' (code 400)
```
It is for **default** `parse_mode` or `TelegramOptions::PARSE_MODE_MARKDOWN_V2`

**How to reproduce**

Send a notification via telegram with any of the special characters listed above using **default** `parse_mode` or `TelegramOptions::PARSE_MODE_MARKDOWN_V2`

**Possible Solution**
In the documentation of Telegram Bot API https://core.telegram.org/bots/api#markdownv2-style we can see that we need to escape those characters. I have prepared a Regex for this which we can put here https://github.com/symfony/telegram-notifier/blob/5.3/TelegramTransport.php#L85 , replace `str_replace` with `preg_replace` that will escape those characters with `\`.

If you think this is a good solution please let me know, I will Pull a request.

### PR DESCRIPTION
**Pull request by thomas2411**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #42697
| License       | MIT

In the documentation of Telegram Bot API https://core.telegram.org/bots/api#markdownv2-style we can see that we need to escape more characters _ * [ ] ( ) ~ ` > # + - = | { } . !. 
I have prepared a Regex for this and replaced https://github.com/symfony/telegram-notifier/blob/5.3/TelegramTransport.php#L85
I have also changed test used for escaping dot to a test that checks escaping all those characters.

### CODE REVIEW

File: src/Symfony/Component/Notifier/Bridge/Telegram/TelegramTransport.php [hunk 1]
```diff
@@ -82,7 +82,7 @@ protected function doSend(MessageInterface $message): SentMessage
 
         if (!isset($options['parse_mode']) || TelegramOptions::PARSE_MODE_MARKDOWN_V2 === $options['parse_mode']) {
             $options['parse_mode'] = TelegramOptions::PARSE_MODE_MARKDOWN_V2;
-            $options['text'] = str_replace('.', '\.', $message->getSubject());
+            $options['text'] = preg_replace('/([\[_\*\[\]\(\)~`>#\+-=\|{}\.!])/m', '\\\\$1', $message->getSubject());
```
Comment (jderusse) [inline src/Symfony/Component/Notifier/Bridge/Telegram/TelegramTransport.php]: `\[` is referenced twice.
IIRC you don't have to escape everything
the `m` could be removed

File: src/Symfony/Component/Notifier/Bridge/Telegram/TelegramTransport.php [hunk 2]
```diff
@@ -98,7 +98,7 @@ protected function doSend(MessageInterface $message): SentMessage
         if (200 !== $statusCode) {
             $result = $response->toArray(false);
 
-            throw new TransportException('Unable to post the Telegram message: '.$result['description'].sprintf(' (code %s).', $result['error_code']), $response);
+            throw new TransportException('Unable to post the Telegram message: '.$result['description'].sprintf(' (code "%s").', $result['error_code']), $response);
         }
```
Comment (jderusse) [inline src/Symfony/Component/Notifier/Bridge/Telegram/TelegramTransport.php]: revert

File: src/Symfony/Component/Notifier/Bridge/Telegram/TelegramTransport.php (hunk 1 above)
Comment (thomas2411) [reply src/Symfony/Component/Notifier/Bridge/Telegram/TelegramTransport.php]: Oh, indeed, I will remove it.

File: src/Symfony/Component/Notifier/Bridge/Telegram/TelegramTransport.php (hunk 2 above)
Comment (thomas2411) [reply src/Symfony/Component/Notifier/Bridge/Telegram/TelegramTransport.php]: Why should I revert it? It has been shown on automatic test and it was written that I just pathc this (from fabpot bot) or something. So in this should I should skip it and revert this change?

Comment (fabpot) [reply src/Symfony/Component/Notifier/Bridge/Telegram/TelegramTransport.php]: This is a false positive from fabbot, so it should be reverted.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @thomas2411.

**Comment by belmeopmenieuwesim** [comment]
this PR broke the Telegram formatting entirely for markdown V2. Literally everything stays escaped. If I comment this preg_match the formatting is exactly as it should be. The current code gives this::

image

**Comment by nicolas-grekas** [comment]
Fixed in #58636
