### PR TITLE
[FrameworkBundle] set NamespacedPoolInterface alias to cache.app

### LINKED ISSUE #60583: [Cache] Autowiring type-hint for namespaced caches
### Symfony version(s) affected

7.3.0

### Description

Symfony 7.3 has a great improvement on cache component https://symfony.com/blog/new-in-symfony-7-3-namespaced-caches

additional `assert($this->cache instanceof NamespacedPoolInterface);` required before calling the `$this->cache->withSubNamespace('sub-ns');` even all caches adapters implement NamespacedPoolInterface, otherwise phpstan will complain about `call to undefined method`

### How to reproduce

had tried to use intersection types

```php
public function __construct(
        private CacheInterface&NamespacedPoolInterface $appCache
    )
```

but get this error

```sh
In DefinitionErrorExceptionPass.php line 48:
                                                                                                                                                                                                                      
  [Symfony\Component\DependencyInjection\Exception\RuntimeException]                                                                                                                                                  
  Cannot autowire service "App\Command\TestCommand": argument "$appCache" of method "__construct()" has type "Symfony\Contracts\Cache\CacheInterface&Symfony\Contracts\Cache\NamespacedPoolInterface" but this class  
   was not found.
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by IndraGunawan**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #60583
| License       | MIT

autowiring `CacheInterface|NamespacedPoolInterface` intersection type for cache pool works well but it does not work for `cache.app`

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -2652,6 +2652,10 @@ private function registerCacheConfiguration(array $config, ContainerBuilder $con
                 }
             }
 
+            if ('cache.app' === $name && interface_exists(NamespacedPoolInterface::class)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: `cache.system` could also benefit from the fix, isn't it?

```suggestion
            } elseif (interface_exists(NamespacedPoolInterface::class)) {
```

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: NVM! :facepalm:

**Comment by nicolas-grekas** [comment]
Thank you @IndraGunawan.

**Comment by VincentLanglet** [comment]
I'm not sure this is the right fix @IndraGunawan @nicolas-grekas cause this enforce the cache.app to implements the NamespacedPoolInterface or you'll get error like

```
{"message":"Error thrown while running command \"lint:container --env=prod\". Message: \"Invalid alias definition: alias \"Symfony\\Contracts\\Cache\\NamespacedPoolInterface\" is referencing class \"Sentry\\SentryBundle\\Tracing\\Cache\\TraceableCacheAdapter\" but this class does not implement \"Symfony\\Contracts\\Cache\\NamespacedPoolInterface\". Because this alias is an interface, \"Sentry\\SentryBundle\\Tracing\\Cache\\TraceableCacheAdapter\" must implement \"Symfony\\Contracts\\Cache\\NamespacedPoolInterface\".\"","context":{"exception":{"class":"Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException","message":"Invalid alias definition: alias \"Symfony\\Contracts\\Cache\\NamespacedPoolInterface\" is referencing class \"Sentry\\SentryBundle\\Tracing\\Cache\\TraceableCacheAdapter\" but this class does not implement \"Symfony\\Contracts\\Cache\\NamespacedPoolInterface\". Because this alias is an interface, \"Sentry\\SentryBundle\\Tracing\\Cache\\TraceableCacheAdapter\" must implement \"Symfony\\Contracts\\Cache\\NamespacedPoolInterface\".","code":0,"file":"/app/vendor/symfony/dependency-injection/Compiler/CheckAliasValidityPass.php:44"},"command":"lint:container --env=prod","message":"Invalid alias definition: alias \"Symfony\\Contracts\\Cache\\NamespacedPoolInterface\" is referencing class \"Sentry\\SentryBundle\\Tracing\\Cache\\TraceableCacheAdapter\" but this class does not implement \"Symfony\\Contracts\\Cache\\NamespacedPoolInterface\". Because this alias is an interface, \"Sentry\\SentryBundle\\Tracing\\Cache\\TraceableCacheAdapter\" must implement \"Symfony\\Contracts\\Cache\\NamespacedPoolInterface\"."}
```

Implementing NamespacedPoolInterface shouldn't be mandatory, or it's basically a BC break

**Comment by xabbuh** [comment]
@VincentLanglet Can you please open a new issue and provide a small example application that allows to reproduce it?

**Comment by VincentLanglet** [comment]
Done in https://github.com/symfony/symfony/issues/61045
