### PR TITLE
[Cache] Stop defaulting to `igbinary` in `DefaultMarshaller`

### LINKED ISSUE #52391: [Cache] `igbinary_serialize` is not compatible with `serialize` anymore
### Symfony version(s) affected

5.x, 6.x

### Description

As of PHP 7.4.6 (https://github.com/doctrine/common/issues/886#issuecomment-618263326), PHP's `serialize` function ignores uninitialized properties and no longer triggers an error. The same change was not (yet) made in igbinary's `igbinary_serialize`, there is a [ticket](https://github.com/igbinary/igbinary/issues/273) to change this though.

Symfony Cache `DefaultMarshaller` still treats `igbinary_serialize` as a drop-in replacement for `serialize` but this is no longer true. Trying to serialize entities with igbinary installed now results in the same error we used to get with `serialize`.

```
Typed property Proxies_CG_\App\Entity\EntityName::$ must not be accessed before initialization (in __sleep)
```

### How to reproduce

Serialize an object with an uninitialised property through Symfony cache with the default marshaller config.

### Possible Solution

It is possible to disable igbinary through the `cache.default_marshaller` service but Symfony may want to consider disabling it by default as it no longer is a drop-in replacement.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by martijnc**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? |no
| Issues        | Fix #52391
| License       | MIT

igbinary used to be a drop in replacement for PHP's `serialize` but recent changes (in PHP 7.4) to the handling of uninitialized properties in `serialize` have not made it into igbinary, so it no longer is a simple drop in replacement.

This only removes igbinary as the default serializer, code can still opt-in through the first constructor argument.

This may result in a performance regression on systems with igbinary as it would no longer be used by default.

Fixes #52391

### CODE REVIEW

**Comment by derrabus** [comment]
Changing the default behavior silently in a bugfix release on an LTS branch sounds like a bad idea, tbh.

If we want to do this, we should target 7.2 and deprecate not setting this option first.

**Comment by nicolas-grekas** [comment]
The code is able to auto-detect if igbinary was used when serializing so that payloads are compatible with either flags (if igbinary is installed).
This means changing the default behavior is fine without further precautions.
We could even do this on 5.4 if we think the state of igbinary is too bad.

**Comment by xabbuh** [comment]
> This means changing the default behavior is fine without further precautions.

I am not convinced that this is always true. What if other PHP projects not using Symfony read the serialised data? They may not have the same mechanism to detect if igbinary was used.

**Comment by nicolas-grekas** [comment]
> What if other PHP projects not using Symfony read the serialised data? They may not have the same mechanism to detect if igbinary was used.

This would be an unsupported use case. Cached items are certainly not meant for interop. We already changed their format without caring in the past.

This change is desired to me.

**Review by nicolas-grekas — APPROVED** [review]
Works for me on 7.2. I'd also be fine on 5.4/6.4: igbinary is not safe anymore, ppl are at risk when using it, and the fact that it's not opt-in when the extension is installed adds to the risk.

**Comment by nicolas-grekas** [comment]
See eg comments in https://github.com/igbinary/igbinary/issues/273

**Review by chalasr — APPROVED** [review]
👍 for 5.4

**Comment by derrabus** [comment]
> Works for me on 7.2.

I think, 7.2 is the compromise we can all settle on. And please let's add a remark to the upgrade guide for 7.2 and the Cache component's change log.

> I'd also be fine on 5.4/6.4: igbinary is not safe anymore, ppl are at risk when using it, and the fact that it's not opt-in when the extension is installed adds to the risk.

I understand that and maybe it was even a mistake to enable igbinary serialization automatically. But I believe that there are enough projects out there that don't hit those issues and still rely on the performance gain they get from leveraging igbinary. Maybe I'm too conservative here, but I wouldn't want to lure those apps into a performance degradation with an innocent bugfix release.

**Review by derrabus — APPROVED** [review]

File: src/Symfony/Component/Cache/Marshaller/DefaultMarshaller.php [hunk 1]
```diff
@@ -25,9 +25,8 @@ class DefaultMarshaller implements MarshallerInterface
 
     public function __construct(?bool $useIgbinarySerialize = null, bool $throwOnSerializationFailure = false)
     {
-        if (null === $useIgbinarySerialize) {
-            $useIgbinarySerialize = \extension_loaded('igbinary') && version_compare('3.1.6', phpversion('igbinary'), '<=');
-        } elseif ($useIgbinarySerialize && (!\extension_loaded('igbinary') || version_compare('3.1.6', phpversion('igbinary'), '>'))) {
+        $useIgbinarySerialize = true === $useIgbinarySerialize;
```
Comment (xabbuh) [inline src/Symfony/Component/Cache/Marshaller/DefaultMarshaller.php]: I would remove this line

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @martijnc.
