### PR TITLE
[Console] Add support for managing exit code while handling signals

### LINKED ISSUE #48340: [Console] Unexpected behavior on CONTROL-C
### Symfony version(s) affected

6.1.x

### Description

Unexpected behavior on CONTROL-C in symfony/console & symfony/messenger

### How to reproduce

Before testing, I modified a few files:

1. `\Symfony\Component\Messenger\Worker::run` added to the bottom `fwrite(\STDOUT, PHP_EOL . 'worker stop' . PHP_EOL);`
2. `\Symfony\Component\Messenger\Command\ConsumeMessagesCommand::execute` before return `$io->comment('Quit');`

Next run:

```
$ docker-compose exec php bin/console messenger:consume async -vvv
                                                                                                                      
 [OK] Consuming messages from transports "async".                                                                       
                                                                                                                        

 // The worker will automatically exit once it has received a stop signal via the messenger:stop-workers command.       

 // Quit the worker with CONTROL-C.   
 ```
 
and pay attention to the phrase "Quit the worker with CONTROL-C."

After that, in the same terminal, I press CONTROL-C. and the consumer terminates unexpectedly without outputting to stdout, which I modified above in the source code. There will be only `^C` in the console. Full log:

```
$ docker-compose exec php bin/console messenger:consume async -vvv

                                                                                                                        
 [OK] Consuming messages from transports "async".                                                                       
                                                                                                                        

 // The worker will automatically exit once it has received a stop signal via the messenger:stop-workers command.       

 // Quit the worker with CONTROL-C.                                                                                     

^C
```

And if you open a second terminal with `docker-compose exec php sh` and call `kill pid`, then the consumer will exit:

```
13:08:59 INFO      [app] Received SIGTERM signal.
[
  "transport_names" => [
    "async"
  ]
]
[
  "uid" => "b66f4c45f3bba98ac04cd5dcc3db6968"
]
13:08:59 INFO      [messenger] Stopping worker.
[
  "transport_names" => [
    "async"
  ]
]
[
  "uid" => "b66f4c45f3bba98ac04cd5dcc3db6968"
]

worker stop
 // Quit  
```

Full log:

```
$ docker-compose exec php bin/console messenger:consume async -vvv

                                                                                                                        
 [OK] Consuming messages from transports "async".                                                                       
                                                                                                                        

 // The worker will automatically exit once it has received a stop signal via the messenger:stop-workers command.       

 // Quit the worker with CONTROL-C.                                                                                     

13:08:59 INFO      [app] Received SIGTERM signal.
[
  "transport_names" => [
    "async"
  ]
]
[
  "uid" => "b66f4c45f3bba98ac04cd5dcc3db6968"
]
13:08:59 INFO      [messenger] Stopping worker.
[
  "transport_names" => [
    "async"
  ]
]
[
  "uid" => "b66f4c45f3bba98ac04cd5dcc3db6968"
]

worker stop
 // Quit   
```

---

Is this the expected behavior for us?

For example, the event WorkerStoppedEvent will never be called (and ConsoleTerminateEvent).

---

The reason is `exit(0)` in `\Symfony\Component\Console\Application::doRunCommand` in this section::

```php
            if (null !== $this->dispatcher) {
                foreach ($this->signalsToDispatchEvent as $signal) {
                    $event = new ConsoleSignalEvent($command, $input, $output, $signal);

                    $this->signalRegistry->register($signal, function ($signal, $hasNext) use ($event) {
                        $this->dispatcher->dispatch($event, ConsoleEvents::SIGNAL);

                        // No more handlers, we try to simulate PHP default behavior
                        if (!$hasNext) {
                            if (!\in_array($signal, [\SIGUSR1, \SIGUSR2], true)) {
                                exit(0);
                            }
                        }
                    });
                }
            }
```

If you remove `exit(0)`, the result will be the same as with `kill pid`.

---

Thanks!

If this is legal behavior, then how do I solve the problem of missing `WorkerStoppedEvent/ConsoleTerminateEvent` events?

### Possible Solution

_No response_

### Additional Context

docker-image — php:8.1.11-fpm-alpine
symfony/console — 6.1.7
symfony/messenger — 6.1.6

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | yes
| Deprecations? | yes (new method in interrface)
| Tickets       | Fix #48340
| License       | MIT
| Doc PR        |

Signal handling is hard! This commit fixes an issue introduced in bb7779d2627e170cdb8433e7d4491d86967d0b74, see this [comment](https://github.com/symfony/symfony/pull/48299#issuecomment-1442442641) for more information.

Symfony registers by default 4 signals, the most common ones: `SIGINT`,
`SIGTERM`, `SIGUSR1`, and `SIGUSR2`.

When no signal handler are registered, the default behavior is to stop the
execution of the current script, to replication PHP default behavior.

That's why we had a call to exit(0), before
bb7779d2627e170cdb8433e7d4491d86967d0b74 and that's why it must be restored.

However, the concerns raised in the
[issue](https://github.com/symfony/symfony/issues/47809) are valid, and we
should provided a solution for this.

Now we have the following features:

* By default, we exit, like PHP does by default on `SIGINT`, `SIGTERM`;
* It's possible to tell via the event to not exit, by calling
  `$event->abortExit()`;
* It's possible to tell via the event to exit with a custom code, by calling
  `$event->setExitCode($code)`;
* It's possible, via the `SignalableCommandInterface` to tell via the command to
  not exit, by returning `int|false` from `handleSignal()` method
* Fixed case when there is not event to dispatch at all, but the command register some

I think we have all we need now. I added more tests to ensure we don't break
anything in the future.

---

Sorry for the massive ping here, but this is bit like an a house of cards to
make it work in any case. I hope I didn't miss anything.

ping @akuzia @lcobucci @GromNaN @olegpro

### CODE REVIEW

File: src/Symfony/Component/Console/Application.php [hunk 1]
```diff
@@ -1004,34 +1004,51 @@ protected function doRunCommand(Command $command, InputInterface $input, OutputI
...
                     foreach ([\SIGINT, \SIGTERM] as $signal) {
-                        $this->signalRegistry->register($signal, static function () use ($sttyMode) {
-                            shell_exec('stty '.$sttyMode);
-                        });
+                        $this->signalRegistry->register($signal, static fn () => shell_exec('stty '.$sttyMode));
                     }
                 }
             }
 
+            $exitCode = 0;
```
Comment (lyrixx) [inline src/Symfony/Component/Console/Application.php]: And I think I have something even more flexible:

```php
            if ($this->dispatcher) {
                // We register application signal, so that we can dispatch the event
                foreach ($this->signalsToDispatchEvent as $signal) {
                    $event = new ConsoleSignalEvent($command, $input, $output, $signal, 0);

                    $this->signalRegistry->register($signal, function ($signal) use ($event, $command, $commandSignals) {
                        $this->dispatcher->dispatch($event, ConsoleEvents::SIGNAL);
                        $exitCode = $event->getExitCode();

                        if (in_array($signal, $commandSignals)) {
                            $command->handleSignal($signal);
                            $exitCode = $command->getExitCode($signal, $exitCode);
                        }
                        if (null !== $exitCode) {
                            exit($exitCode);
                        }
                    });
                }

                // then we register command signal, but not if already handled by the dispatcher
                foreach (array_diff($this->signalsToDispatchEvent, $commandSignals) as $signal) {
                    $this->signalRegistry->register($signal, function (int $signal) use ($command): void {
                        $command->handleSignal($signal);
                        $exitCode = $command->getExitCode($signal, 0);
                        if (null !== $exitCode) {
                            exit($exitCode);
                        }
                    });
                }
            } else {
                foreach ($commandSignals as $signal) {
                    $this->signalRegistry->register($signal, function (int $signal) use ($command): void {
                        $command->handleSignal($signal);
                        $exitCode = $command->getExitCode($signal, 0);
                        if (null !== $exitCode) {
                            exit($exitCode);
                        }
                    });
                }
            }
        }
```



WDYT?

Comment (lyrixx) [reply src/Symfony/Component/Console/Application.php]: Applied! Tests are coming (next week I guess)

**Comment by lcobucci** [comment]
This was the BC-break I referred to when I brought up the initial issue 😅

@lyrixx thanks for your work here, there are indeed many factors to take into account when tweaking signal handling. 

For my use case, the solution will work fine. It feels a bit cumbersome to modify the event state buuuut it's fine. 

It's really important to document the nuances and what's expected from each different use case 👍

**Comment by lyrixx** [comment]
Yes, it's not so cool to have to edit the event, but we must do it since we cannot now if the end user will stop / exit / return itself.

So by default we should mimic PHP, and the user can opt-in for managing exit themself.

**Comment by fabpot** [comment]
@lyrixx You can rebase this one (I've merged up the other 2 PRs).

**Comment by lyrixx** [comment]
Rebase ✅

**Review by chalasr — CHANGES_REQUESTED** [review]
👍 for this. The CHANGELOG should mention the BC break though

**Comment by lyrixx** [comment]
What bc break are you talking about? The new method in the interface? I should update the upgrade.md too!

**Comment by chalasr** [comment]
Yes!

**Comment by lyrixx** [comment]
Fixed

File: src/Symfony/Component/Console/Command/SignalableCommandInterface.php [hunk 2]
```diff
@@ -15,6 +15,8 @@
  * Interface for command reacting to signal.
  *
  * @author Grégoire Pineau <lyrixx@lyrix.info>
+ *
+ * @method ?int getExitCode(int $signal, ?int $previousExitCode) Returns whether to automatically exit with $exitCode after command handling, or not with null.
```
Comment (GromNaN) [inline src/Symfony/Component/Console/Command/SignalableCommandInterface.php]: I don't like the DX of this 3rd method. I would prefer to be able to change `exitCode` directly to `handleSignal` by changing the signature, adding `&$exitCode` by reference.

```
public function handleSignal(int $signal, ?int &$exitCode = null): void;
```

File: src/Symfony/Component/Console/Event/ConsoleSignalEvent.php [hunk 3]
```diff
@@ -21,15 +21,34 @@
...
+        $this->exitCode = $exitCode;
     }
 
     public function getHandlingSignal(): int
     {
         return $this->handlingSignal;
     }
+
+    /**
+     * Sets whether to automatically exit with $exitCode after command handling, or not with null.
```
Comment (GromNaN) [inline src/Symfony/Component/Console/Event/ConsoleSignalEvent.php]: The main feature is to exit, the code is secondary.
```suggestion
     * Sets whether to automatically exit after command handling with $exitCode, or not exit with null.
```

The method could be renamed to `function exit(int|bool $exitCode = true)`:

```php
// No exit
$event->exit(false);

// Exit with success (code=0)
$event->exit();

// Exit with custom code
$event->exit(1);
```

**Review by GromNaN — COMMENTED** [review]
👍🏻 for adding a way to control if the command exits or not. This is what I mentioned in https://github.com/symfony/symfony/issues/47809#issuecomment-1314937992.

I think we can improve the DX with some changes.

File: src/Symfony/Component/Console/Command/SignalableCommandInterface.php (hunk 2 above)
Comment (lyrixx) [reply src/Symfony/Component/Console/Command/SignalableCommandInterface.php]: Me too! But I would love the following API:
```
public function handleSignal(int $signal, ?int &previousExitCode = null): ?int;
```

where you must to return the new exit code, but this is a BC break.

With your solution, we can avoid the BC break, but using a reference is not really common, and I (we?) tend to avoid it.

Is there a way to change the return type of an interface? (adding a new method and deprecated this one is the only way, isnt't?)

File: src/Symfony/Component/Console/Event/ConsoleSignalEvent.php (hunk 3 above)
Comment (akuzia) [reply src/Symfony/Component/Console/Event/ConsoleSignalEvent.php]: This may lead to some poor implementations (`$event->exit(1)` for example) and typecasting bugs. IMO multitype arguments is evil. I suggest logic more like `stopPropagation` on standart events.

We can call something like `$event->setExitCode(int)` / `$event->abortExit()` and leave developer to decide whenether to exit and with wich code and default this params to 0 and false respectively

File: src/Symfony/Component/Console/Application.php [hunk 4]
```diff
@@ -1000,37 +1000,61 @@ protected function doRunCommand(Command $command, InputInterface $input, OutputI
...
+                    $this->signalRegistry->register($signal, function ($signal) use ($event, $command, $commandSignals) {
                         $this->dispatcher->dispatch($event, ConsoleEvents::SIGNAL);
+                        $exitCode = $event->getExitCode();
+
+                        // If the command is signalable, we call the handleSignal() method
+                        if (\in_array($signal, $commandSignals, true)) {
+                            $command->handleSignal($signal);
+                            // BC layer for Symfony <5.3
+                            if (method_exists($command, 'getExitCode')) {
+                                $exitCode = $command->getExitCode($signal, $exitCode);
```
Comment (akuzia) [inline src/Symfony/Component/Console/Application.php]: Can we rely on `ConsoleEvents::TERMINATE` at this stage? If doing so there is an option to handle exit code there. So there will not be a BC (if dispatcher is available). In any case I think there is a TERMINATE event in need of dispatching here

File: src/Symfony/Component/Console/Application.php [hunk 5]
```diff
@@ -1000,37 +1000,61 @@ protected function doRunCommand(Command $command, InputInterface $input, OutputI
...
+                $this->signalRegistry->register($signal, function (int $signal) use ($command): void {
+                    $command->handleSignal($signal);
+                    $exitCode = 0;
+                    // BC layer for Symfony <5.3
+                    if (method_exists($command, 'getExitCode')) {
+                        $exitCode = $command->getExitCode($signal, $exitCode);
+                    }
+
+                    if (null !== $exitCode) {
+                        exit($exitCode);
```
Comment (akuzia) [inline src/Symfony/Component/Console/Application.php:1056]: If no dispatcher is available do we realy need to add this logic? Command will be run and exit code will be decided by the `Command::execute` method return. So perhaps it is ok to `exit()` it handleSignal after all?

---
nvm. I if handleSignal exits control flow might be not out of execute yet.

File: src/Symfony/Component/Console/Event/ConsoleSignalEvent.php (hunk 3 above)
Comment (lyrixx) [reply src/Symfony/Component/Console/Event/ConsoleSignalEvent.php]: This API could work with the event, but not with the SignalableCommandInterface. I prefer to have the same API on both way to deal with signals.

File: src/Symfony/Component/Console/Application.php (hunk 4 above)
Comment (lyrixx) [reply src/Symfony/Component/Console/Application.php]: I guess there is some confusion here. It's not about the `$event->getExitCode()`, but about `$command->getExitCode()`. (event vs command)

I introduced a new method in the `SignalableCommandInterface`, but with a BC layer. So at runtime, this method might not exist (yet).

File: src/Symfony/Component/Console/Event/ConsoleSignalEvent.php (hunk 3 above)
Comment (lyrixx) [reply src/Symfony/Component/Console/Event/ConsoleSignalEvent.php]: But having two method is OK 👍🏼

**Comment by lyrixx** [comment]
Hmm, I broke something here. The PHPUnit output is truncated 🤔 don't know why ! 
```
>…regoire/dev/github.com/lyrixx/symfony(console-fix-signal-handling *) ./phpunit src/Symfony/Component/Console/Tests/ 
PHPUnit 9.6.3 by Sebastian Bergmann and contributors.

Testing /home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Console/Tests
.............................................................   61 / 1238 (  4%)
.....................................................😊
  [0] y
 > ........  122 / 1238 (  9%)
.............................................................  183 / 1238 ( 14%)
.............................................................  244 / 1238 ( 19%)
.............................................................  305 / 1238 ( 24%)
.............................................................  366 / 1238 ( 29%)
.............................................................  427 / 1238 ( 34%)
.............................................................  488 / 1238 ( 39%)
.............................................................  549 / 1238 ( 44%)
.............................................................  610 / 1238 ( 49%)
.............................................................  671 / 1238 ( 54%)
.............................................................  732 / 1238 ( 59%)
.............................................................  793 / 1238 ( 64%)
.............................................................  854 / 1238 ( 68%)
.............................................................  915 / 1238 ( 73%)
...............................F.............................  976 / 1238 ( 78%)
............................................................. 1037 / 1238 ( 83%)
............................................................. 1098 / 1238 ( 88%)
..........................................................
Legacy deprecation notices (2)
>…regoire/dev/github.com/lyrixx/symfony(console-fix-signal-handling *) 
```

(Note: I edited a test to make it fails)

**Comment by lyrixx** [comment]
Thanks for the review!

I pushed a new version  without the new method on the interface!

The new API is even simpler!

**Review by GromNaN — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Console/Application.php [hunk 6]
```diff
@@ -1000,37 +1000,62 @@ protected function doRunCommand(Command $command, InputInterface $input, OutputI
...
 
-        if ($this->signalsToDispatchEvent) {
-            $commandSignals = $command instanceof SignalableCommandInterface ? $command->getSubscribedSignals() : [];
-
-            if ($commandSignals || null !== $this->dispatcher) {
-                if (!$this->signalRegistry) {
-                    throw new RuntimeException('Unable to subscribe to signal events. Make sure that the `pcntl` extension is installed and that "pcntl_*" functions are not disabled by your php.ini\'s "disable_functions" directive.');
-                }
+        $commandSignals = $command instanceof SignalableCommandInterface ? $command->getSubscribedSignals() : [];
+        if ($commandSignals || null !== $this->dispatcher && $this->signalsToDispatchEvent) {
```
Comment (phansys) [inline src/Symfony/Component/Console/Application.php]:
```suggestion
        if ([] !== $commandSignals || null !== $this->dispatcher && $this->signalsToDispatchEvent) {
```

File: src/Symfony/Component/Console/Application.php [hunk 7]
```diff
@@ -1000,37 +1000,62 @@ protected function doRunCommand(Command $command, InputInterface $input, OutputI
...
-                            shell_exec('stty '.$sttyMode);
-                        });
-                    }
+                foreach ([\SIGINT, \SIGTERM] as $signal) {
+                    $this->signalRegistry->register($signal, static fn () => shell_exec('stty '.$sttyMode));
                 }
             }
 
-            if (null !== $this->dispatcher) {
+            if ($this->dispatcher) {
```
Comment (phansys) [inline src/Symfony/Component/Console/Application.php:1017]: Why the stricter check was removed?

File: src/Symfony/Component/Console/Event/ConsoleSignalEvent.php [hunk 8]
```diff
@@ -21,15 +21,36 @@
...
 
     public function getHandlingSignal(): int
     {
         return $this->handlingSignal;
     }
+
+    public function setExitCode(int $exitCode): void
+    {
+        if ($exitCode < 0 || $exitCode > 255) {
+            throw new \InvalidArgumentException('Exit code must be between 0 and 255 or null.');
```
Comment (phansys) [inline src/Symfony/Component/Console/Event/ConsoleSignalEvent.php]: This message seems weird to me, as the parameter `$exitCode` is not allowing `null` here.

File: src/Symfony/Component/Console/Application.php (hunk 6 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Console/Application.php]: not needed and not our cs

File: src/Symfony/Component/Console/Application.php (hunk 7 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Console/Application.php:1017]: more aligned with our cs

File: src/Symfony/Component/Console/Event/ConsoleSignalEvent.php (hunk 8 above)
Comment (lyrixx) [reply src/Symfony/Component/Console/Event/ConsoleSignalEvent.php]: Thanks, fixed

File: src/Symfony/Component/Console/Tests/SignalRegistry/SignalRegistryTest.php [hunk 9]
```diff
@@ -22,8 +22,15 @@ class SignalRegistryTest extends TestCase
     protected function tearDown(): void
     {
         pcntl_async_signals(false);
-        pcntl_signal(\SIGUSR1, \SIG_DFL);
-        pcntl_signal(\SIGUSR2, \SIG_DFL);
+        if (\function_exists('pcntl_signal')) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Tests/SignalRegistry/SignalRegistryTest.php]: can be removed, thanks to `requires extension pcntl`

File: src/Symfony/Component/Console/Event/ConsoleSignalEvent.php [hunk 10]
```diff
@@ -21,15 +21,36 @@
...
         $this->handlingSignal = $handlingSignal;
+        $this->exitCode = $exitCode;
     }
 
     public function getHandlingSignal(): int
     {
         return $this->handlingSignal;
     }
+
+    public function setExitCode(int $exitCode): void
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Event/ConsoleSignalEvent.php:38]: `int|false`?

Comment (lyrixx) [reply src/Symfony/Component/Console/Event/ConsoleSignalEvent.php:38]: See `abortExit`

**Comment by nicolas-grekas** [comment]
Thank you @lyrixx.
