### PR TITLE
[Serializer] Fix for method named `get()`

### LINKED ISSUE #58012: [Serializer] ObjectNormalizer throws exception normalizing classes with the method `get`
### Symfony version(s) affected

\>= 6.4.x

### Description

If a class has a method called `get` that method will get confused for an accessor and it will go through logic relating to property-access for the property named `substr('get', 3)`.

Eventually a new `PropertyPath` instance will be created with an empty path which will trigger an exception.

### How to reproduce

```php
$serializer->serialize(new class { 
    public function get() {} 
}, 'json');
```

### Possible Solution

A naive solution  `ObjectNormalizer::isAllowedAttribute()` at line 193
```diff
-                self::$isReadableCache[$class.$attribute] = (\is_object($classOrObject) && $this->propertyAccessor->isReadable($classOrObject, $attribute)) || $this->propertyInfoExtractor->isReadable($class, $attribute) || $this->hasAttributeAccessorMethod($class, $attribute);
+                self::$isReadableCache[$class.$attribute] = (\is_object($classOrObject) && !empty($attribute) && $this->propertyAccessor->isReadable($classOrObject, $attribute)) || $this->propertyInfoExtractor->isReadable($class, $attribute) || $this->hasAttributeAccessorMethod($class, $attribute);
```

But most likely this object would need to be skipped earlier in the normalization process, perhaps here:

```diff
-            if (str_starts_with($name, 'get') || str_starts_with($name, 'has') || str_starts_with($name, 'can')) {
+            if ($name !== 'get' && str_starts_with($name, 'get')
+            || $name !== 'has' && str_starts_with($name, 'has')
+            || $name !== 'can' && str_starts_with($name, 'can')) {
                // getters, hassers and canners
                $attributeName = substr($name, 3);

                if (!$reflClass->hasProperty($attributeName)) {
                    $attributeName = lcfirst($attributeName);
                }
-            } elseif (str_starts_with($name, 'is')) {
+            } elseif ($name !== 'is' && str_starts_with($name, 'is')) {
                // issers
                $attributeName = substr($name, 2);

                if (!$reflClass->hasProperty($attributeName)) {
                    $attributeName = lcfirst($attributeName);
                }
            }
```

### Additional Context

Exception is triggered around here `$propertyAccessor->isReadable()` instantiates a `PropertyPath`.

```php
// ObjectNormalizer::isAllowedAttribute() line 193
        if ($context['_read_attributes'] ?? true) {
            if (!isset(self::$isReadableCache[$class.$attribute])) {
                self::$isReadableCache[$class.$attribute] = (\is_object($classOrObject) && $this->propertyAccessor->isReadable($classOrObject, $attribute)) || $this->propertyInfoExtractor->isReadable($class, $attribute) || $this->hasAttributeAccessorMethod($class, $attribute);
            }

            return self::$isReadableCache[$class.$attribute];
        }
```

### PR DESCRIPTION
**Pull request by mihai-stancu**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58012 
| License       | MIT

During normalization, if a class has a method called `get` that method will get confused for an accessor and it will go through logic relating to property-access for the property named `substr('get', 3)`.

Eventually a new PropertyPath instance will be created with an empty path which will trigger an exception.
```php
$serializer->serialize(new class { 
    public function get() {} 
}, 'json');
```

### CODE REVIEW

**Comment by mihai-stancu** [comment]
I'll add a test for this tomorrow.

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php [hunk 1]
```diff
@@ -100,14 +100,16 @@ protected function extractAttributes(object $object, ?string $format = null, arr
             $name = $reflMethod->name;
             $attributeName = null;
 
-            if (str_starts_with($name, 'get') || str_starts_with($name, 'has') || str_starts_with($name, 'can')) {
+            if ($name !== 'get' && str_starts_with($name, 'get')
+            || $name !== 'has' && str_starts_with($name, 'has')
+            || $name !== 'can' && str_starts_with($name, 'can')) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]:
```suggestion
            if (3 < \strlen($name) && (...)) {
```

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php [hunk 2]
```diff
@@ -100,14 +100,16 @@ protected function extractAttributes(object $object, ?string $format = null, arr
...
                 // getters, hassers and canners
                 $attributeName = substr($name, 3);
 
                 if (!$reflClass->hasProperty($attributeName)) {
                     $attributeName = lcfirst($attributeName);
                 }
-            } elseif (str_starts_with($name, 'is')) {
+            } elseif ($name !== 'is' && str_starts_with($name, 'is')) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]:
```suggestion
            } elseif ('is' !== $name && str_starts_with($name, 'is')) {
```

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php (hunk 1 above)
Comment (dunglas) [inline src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]: Ad it's on the hot path, we should test if a regex wouldn't be faster (same for `is`).

**Comment by nicolas-grekas** [comment]
Thank you @mihai-stancu.
