### PR TITLE
[HttpClient] Fix CachingHttpClient compatibility with decorator clients on 304 responses

### LINKED ISSUE #63553: [HttpClient] TraceableHttpClient::stream() rejects MockResponse returned by CachingHttpClient from cache when server returns a 304
### Symfony version(s) affected

7.4.6

### Description

Hi

When using a scoped HTTP client with HTTP caching enabled, calling toArray() or getStatusCode() on a response intermittently throws a fatal type error. The error only occurs when the server returns a 304 Not Modified response.

`"Symfony\Component\HttpClient\TraceableHttpClient::stream()" expects parameter 1  to be an iterable of TraceableResponse objects, "Symfony\Component\HttpClient\Response\MockResponse" given.`

I tried to disable the profiler in the dev environment, but I encountered a different yet similar issue : 

`Symfony\\Component\\HttpClient\\Response\\CurlResponse::schedule(): Argument #1 ($response) must be of type Symfony\\Component\\HttpClient\\Response\\CurlResponse, Symfony\\Component\\HttpClient\\Response\\MockResponse given`

Or maybe I forgot something ?

Thx

### How to reproduce

Configuration

#### config/packages/framework.yaml
```
  framework:
      http_client:
          scoped_clients:
              place.client:
                  base_uri: 'https://place-api'
                  caching:
                      cache_pool: app.cache.http
```

#### config/packages/cache.yaml
```
  framework:
      cache:
          pools:
              app.cache.http:
                  adapter: cache.adapter.filesystem
                  tags: true
                  default_lifetime: 0
```

#### config/services.yaml
```
    app.cache.http.filesystem:
        parent: cache.adapter.filesystem
        arguments:
            $directory: '%kernel.share_dir%/http_client'
```

#### endpoint API
```
            $response = $this->json($result);
            $response->setMaxAge(300);
            $response->setPublic();
            $response->setEtag(md5(serialize($result)));
            $response->isNotModified($request);

            return $response;
```

#### client
```
class PlaceAPIService
{
    public function __construct(
        #[Autowire(env: 'PLACE_API_URL')]
        private string $placeApiUrl,
        private HttpClientInterface $placeClient,
    ) {
    }

    public function getPlaceData(int|array $placeIds): ?array
    {
        try {
            $url = $this->placeApiUrl . '/places/' . $placeIds;
            $response = $this->placeClient->request('GET', $url);

            if ($response->getStatusCode() === 200) {
                return $response->toArray();
            }

            return null;
        } catch (\Throwable $e) {
            $this->logger->error('Request to Place API failed', [
                'placeId' => $placeIds,
                'error' => $e->getMessage(),
            ]);

            return null;
        }
    }
}
```
  1. Configure a scoped HTTP client with caching.cache_pool as above.
  2. Make an HTTP request through the client, response gets cached.
  3. Make the same request again, response is served from cache as a MockResponse.
  4. Call stream() on the response.

### Possible Solution

_No response_

### Additional Context

```
[2026-03-03T14:34:01.598273+01:00] http_client.INFO: Request: "GET http://place-api:8080/places/12933,12935" [] []
[2026-03-03T14:34:01.675133+01:00] http_client.INFO: Response: "304 http://place-api:8080/places/12933,12935" 0.0742 seconds {"http_code":304,"url":"http://place-api:8080/places/12933,12935","total_time":0.0742} []
[2026-03-03T14:34:01.676616+01:00] cache.INFO: Lock acquired, now computing item "metadata_Srqq8wQwCqwbXQo2e+m54DLtSpwwBWXl6qOu_K_xglk=_47DEQpj8HBSa+_TImW+5JCeuQeRkm5NMpJWZG3hSuFU=" {"key":"metadata_Srqq8wQwCqwbXQo2e+m54DLtSpwwBWXl6qOu_K_xglk=_47DEQpj8HBSa+_TImW+5JCeuQeRkm5NMpJWZG3hSuFU="} []
[2026-03-03T14:34:01.686236+01:00] request.CRITICAL: Uncaught PHP Exception TypeError: ""Symfony\Component\HttpClient\TraceableHttpClient::stream()" expects parameter 1 to be an iterable of TraceableResponse objects, "Symfony\Component\HttpClient\Response\MockResponse" given." at TraceableResponse.php line 171 {"exception":"[object] (TypeError(code: 0): \"Symfony\\Component\\HttpClient\\TraceableHttpClient::stream()\" expects parameter 1 to be an iterable of TraceableResponse objects, \"Symfony\\Component\\HttpClient\\Response\\MockResponse\" given. at /var/www/pap/vendor/symfony/http-client/Response/TraceableResponse.php:171)"} []
[2026-03-03T14:34:01.688497+01:00] app.ERROR: An exception occured, transforming to an Error resource. {"exception":"[object] (TypeError(code: 0): \"Symfony\\Component\\HttpClient\\TraceableHttpClient::stream()\" expects parameter 1 to be an iterable of TraceableResponse objects, \"Symfony\\Component\\HttpClient\\Response\\MockResponse\" given. at /var/www/pap/vendor/symfony/http-client/Response/TraceableResponse.php:171)","operation":{"ApiPlatform\\Metadata\\GetCollection":[]}} []
```

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63553
| License       | MIT

When `CachingHttpClient` is wrapped by `TraceableHttpClient` (or any other decorator), and the upstream server returns a `304 Not Modified`, a `TypeError` is thrown because `AsyncResponse::stream()` tries to re-stream the replacement `MockResponse` through the inner HTTP client, which cannot handle it.

The root cause is that `CachingHttpClient::request()` passes `$this->client` (the inner transport) to `AsyncResponse`. When the passthru callback calls `context->replaceResponse(MockResponse)`, the `AsyncResponse` outer loop restarts and calls `$innerClient->stream([MockResponse])`, but the inner client only knows how to stream its own response type.

The fix passes `$this` (the `CachingHttpClient` itself) as the client to `AsyncResponse`, with a recursion guard to avoid infinite loops. This way, when `replaceResponse(MockResponse)` triggers re-streaming, it goes through `CachingHttpClient::stream()`, which already knows how to route `MockResponse` instances to `MockResponse::stream()`.

Best review [ignoring whitespaces](https://github.com/symfony/symfony/pull/63573/files?w=1).

### CODE REVIEW

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 1]
```diff
@@ -401,26 +408,40 @@ public function stream(ResponseInterface|iterable $responses, ?float $timeout =
 
         $mockResponses = [];
         $asyncResponses = [];
+        $clientResponses = [];
 
         foreach ($responses as $response) {
             if ($response instanceof MockResponse) {
                 $mockResponses[] = $response;
-            } else {
+            } elseif ($response instanceof AsyncResponse) {
```
Comment (stof) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php:416]: what if the inner client is also using AsyncResponse as implementation ?

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php:416]: @stof this cannot happen because the case of `$clientResponses` is split from the case of `$asyncResponses`: both cannot be populated at the same time.
But your comment made me realize this wasn't always the case and another fix was needed, see https://github.com/symfony/symfony/pull/63588
