### PR TITLE
[Yaml] Fix regression handling blank lines in unquoted scalars

### LINKED ISSUE #62581: [YAML] Line number incorrect for `ParseException` when failing to parse YAML
### Symfony version(s) affected

7.4.0 (arguably earlier as well)

### Description

When failing to parse a YAML file, the line number is incorrect - and changed in 7.4.0.

### How to reproduce

Have invalid YAML, for example:

```yaml
en:
  NONAMESPACE: Include Entity without Namespace
  Invalid: Foo
    About: 'About us'
    - Invalid

```

Parse with the following code:

```php
use Symfony\Component\Yaml\Parser;

$path = 'path/to/the/file.yaml';

$parser = new Parser();
$parser->parse(file_get_contents($path));
```

Note the line should probably be "4" for the above (i.e. the line where the offending colon lives), but for 7.3.5 it reported as line "5" and as of 7.4.0 it reports as line "6".

Note also that if you remove the empty line at the bottom of the file, it reports as line "5" again - but the empty line at the end of the file shouldn't affect which line the error is reported for.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by yoeunes**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62581
| License       | MIT

This PR fixes a regression introduced in #62359 regarding unquoted multiline scalars.

A check for blank lines was incorrectly added, causing the parser to bypass indentation checks and consume trailing newlines. This resulted in incorrect line numbers being reported in exceptions (e.g. when a colon is used in an unquoted value).

### CODE REVIEW

**Review by stof — APPROVED** [review]

File: src/Symfony/Component/Yaml/Tests/ParserTest.php [hunk 1]
```diff
@@ -1829,6 +1829,77 @@ public function testUnquotedMultilineScalarThrowsOnOrphanedLineAfterComment()
...
+        $this->expectExceptionMessage($message);
+        $this->expectExceptionMessage(\sprintf('at line %d', $expectedLine));
+
+        $this->parser->parse($yaml);
+    }
+
+    public static function provideInvalidYamlFiles(): iterable
+    {
+        yield 'invalid_nested_under_scalar' => [
+            5,
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Tests/ParserTest.php]: Shouldn't this be `4`?

Comment (yoeunes) [reply src/Symfony/Component/Yaml/Tests/ParserTest.php]: Hi @xabbuh, you are right. I updated the parser to fail earlier when it detects a colon in an indented block. It now correctly reports line 4 instead of 5

**Comment by nicolas-grekas** [comment]
Thank you @yoeunes.
