### PR TITLE
[Serializer] Need to clear cache when updating Annotation Groups on Entities

### LINKED ISSUE #40034: [Serializer] Need to clear cache when updating Annotation Groups on Entities
**Symfony version(s) affected**: 5.1/5.2

**Description**  
Serializer Groups Annotations not updating when updated, need to `cache:clear` on each `@Groups` modification. In `dev` environment at least (not tested in `prod`).

Changing a arbitrary `.yaml` config updates cache and the Group is updated too.

**How to reproduce**  
Create an app in ~~5.0~~ 5.1-5.2 with Doctrine entities, add Serializer group and call the Serializer on this group : 

```php
    /**
     * @ORM\Column(type="string", length=70)
     * @Assert\NotBlank
     * @Groups("movies_get")
     */
    private $title;
```

Call the URL, all the JSON fields are OK.
Remove or add a Group annotation, reload the URL, the JSON fields are not updated.
Clear the cache in any way, the JSON fields are OK.

**Possible Solution**  
Possible link with : https://github.com/symfony/symfony/issues/39988 ?
As the issue seems similar but at a _higher_ level :nerd_face: 

Or, when switching from 5.0 to 5.1, Doctrine packages has changes, need code updates, so perhaps the issue comes from here ?

**Additional context**  
If you have any questions, let me know.

### PR DESCRIPTION
**Pull request by monteiro**
| Q             | A
| ------------- | ---
| Branch?       | 5.3 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #40034 
| License       | MIT

Sample project that mimics this behavior: https://github.com/monteiro/PR-40856

The solution was suggested by @nicolas-grekas [here](https://github.com/symfony/symfony/pull/40856).

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -1705,6 +1705,9 @@ private function registerSecurityCsrfConfiguration(array $config, ContainerBuild
     private function registerSerializerConfiguration(array $config, ContainerBuilder $container, PhpFileLoader $loader)
     {
         $loader->load('serializer.php');
+        if ($container->getParameter('kernel.debug')) {
+            $loader->load('serializer_debug.php');
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: No need for a new file to load, let's remove in this class directly.

Comment (monteiro) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Good point!

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @monteiro.
