### PR TITLE
[Form] RepeatedType should always have inner types mapped

### LINKED ISSUE #36410: [Form] RepeatedType with not mapped fields allows to have different values
**Symfony version(s) affected**: 3.4

**Description**  
If one (or both) fields in RepeatedType is not mapped the form allows to have different values

**How to reproduce**  
Add to `Tests/Extension/Core/Type/RepeatedTypeTest.php`
```php
public function testSubmitUnequalNotMapped(): void
{
    $input = ['first' => 'foo', 'second' => 'bar'];

    $form = $this->factory->create(static::TESTED_TYPE, null, [
        'type' => TextTypeTest::TESTED_TYPE,
        'first_options' => ['mapped' => false],
        'second_options' => ['mapped' => false],
    ]);

    $form->submit($input);

    $this->assertSame('foo', $form['first']->getViewData());
    $this->assertSame('bar', $form['second']->getViewData());
    $this->assertFalse($form->isSynchronized());
    $this->assertSame($input, $form->getViewData());
    $this->assertNull($form->getData());
}
```

Happens because `\Symfony\Component\Form\Extension\Core\DataTransformer\ValueToDuplicatesTransformer` is called with `value === null` on unmapped field.

### PR DESCRIPTION
**Pull request by biozshock**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Doc PR| https://github.com/symfony/symfony-docs/pull/13519 |
| Tickets       | Fix #36410
| License       | MIT

Always set mapped=true to override inner type mapped setting.
Throw an exception if inner types of RepeatedType has mapped=false

### CODE REVIEW

File: src/Symfony/Component/Form/Extension/Core/Type/RepeatedType.php [hunk 1]
```diff
@@ -36,8 +37,8 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                 $options['first_name'],
                 $options['second_name'],
             ]))
-            ->add($options['first_name'], $options['type'], array_merge($options['options'], $options['first_options']))
-            ->add($options['second_name'], $options['type'], array_merge($options['options'], $options['second_options']))
+            ->add($options['first_name'], $options['type'], $this->mergeOptions($options['options'], $options['first_options']))
```
Comment (HeahDude) [inline src/Symfony/Component/Form/Extension/Core/Type/RepeatedType.php:40]: Instead of adding a private method I would add above:
```php
// children fields must always be mapped
$defaultOptions = ['mapped' => false];
```
Then do the following:
```suggestion
            ->add($options['first_name'], $options['type'], array_merge($options['options'], $options['first_options'], $defaultOptions))
```

File: src/Symfony/Component/Form/Tests/Extension/Core/Type/RepeatedTypeTest.php [hunk 2]
```diff
@@ -105,6 +120,29 @@ public function testSetInvalidSecondOptions()
         ]);
     }
 
+    /**
+     * @param string $configurationKey
+     * @dataProvider notMappedConfigurationKeys
+     */
+    public function testNotMappedInner($configurationKey)
```
Comment (HeahDude) [inline src/Symfony/Component/Form/Tests/Extension/Core/Type/RepeatedTypeTest.php:127]: Then this could be removed.

**Review by HeahDude — COMMENTED** [review]
Great! I was about to suggest you to create PR to do so, thanks!

It adds complexity to validate the option, but we can easily enforce the expected behavior so I'm 👍 for targeting 3.4 with this fix.

File: src/Symfony/Component/Form/Extension/Core/Type/RepeatedType.php (hunk 1 above)
Comment (stof) [reply src/Symfony/Component/Form/Extension/Core/Type/RepeatedType.php:40]: Well, with `true` rather than `false` of course :smile:

Comment (HeahDude) [reply src/Symfony/Component/Form/Extension/Core/Type/RepeatedType.php:40]: Edited, thanks x)

Comment (biozshock) [reply src/Symfony/Component/Form/Extension/Core/Type/RepeatedType.php:40]: Keep in mind that removing this will hide the behavior when developer specify `mapped => false` to one of the inner fields.

File: src/Symfony/Component/Form/Tests/Extension/Core/Type/RepeatedTypeTest.php (hunk 2 above)
Comment (HeahDude) [reply src/Symfony/Component/Form/Tests/Extension/Core/Type/RepeatedTypeTest.php:127]: Or better, adapted to have the same behavior as the other.

File: src/Symfony/Component/Form/Extension/Core/Type/RepeatedType.php (hunk 1 above)
Comment (HeahDude) [reply src/Symfony/Component/Form/Extension/Core/Type/RepeatedType.php:40]: Yes but we need a consistent fix. Either throw in all case or override in all case.
I say this PR deserves a doc update, adding a note in the `RepeatedType` reference to tell about that overriding as a requirement for this type to work properly. WDYT? Are you up to it too :) or should we take care of this one?

Comment (HeahDude) [reply src/Symfony/Component/Form/Extension/Core/Type/RepeatedType.php:40]: Also note that it would be a lot more complex to try to throw in all cases.

Comment (stof) [reply src/Symfony/Component/Form/Extension/Core/Type/RepeatedType.php:40]: I'm fine with silently overriding in all cases here (we might add a note in the doc saying the inner fields cannot be unmapped, and that you should use `mapped => false` on the RepeatedType itself if needed).

File: src/Symfony/Component/Form/Extension/Core/Type/RepeatedType.php [hunk 3]
```diff
@@ -31,13 +31,24 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
+        $defaultOptions = ['mapped' => true];
+
         $builder
             ->addViewTransformer(new ValueToDuplicatesTransformer([
                 $options['first_name'],
                 $options['second_name'],
             ]))
-            ->add($options['first_name'], $options['type'], array_merge($options['options'], $options['first_options']))
-            ->add($options['second_name'], $options['type'], array_merge($options['options'], $options['second_options']))
+            ->add(
```
Comment (HeahDude) [inline src/Symfony/Component/Form/Extension/Core/Type/RepeatedType.php:42]: Please keep in on one line to follow our standards, this also reduces the diff.

**Review by HeahDude — APPROVED** [review]
Thanks! (minor comment)

File: src/Symfony/Component/Form/Extension/Core/Type/RepeatedType.php (hunk 3 above)
Comment (biozshock) [reply src/Symfony/Component/Form/Extension/Core/Type/RepeatedType.php:42]: Thought fabbot will complain about 120 symbols line.

File: src/Symfony/Component/Form/Tests/Extension/Core/Type/RepeatedTypeTest.php (hunk 2 above)
Comment (biozshock) [reply src/Symfony/Component/Form/Tests/Extension/Core/Type/RepeatedTypeTest.php]: done

File: src/Symfony/Component/Form/Extension/Core/Type/RepeatedType.php (hunk 1 above)
Comment (biozshock) [reply src/Symfony/Component/Form/Extension/Core/Type/RepeatedType.php]: done

**Comment by biozshock** [comment]
Added doc PR.

File: src/Symfony/Component/Form/Tests/Extension/Core/Type/RepeatedTypeTest.php [hunk 4]
```diff
@@ -78,6 +79,42 @@ public function testSetRequired()
...
+        $form = $this->factory->create(static::TESTED_TYPE, null, [
+            'type' => NotMappedType::class,
+        ]);
+
+        $this->assertTrue($form['first']->getConfig()->getMapped());
+        $this->assertTrue($form['second']->getConfig()->getMapped());
+    }
+
+    /**
+     * @param string $configurationKey
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Tests/Extension/Core/Type/RepeatedTypeTest.php:96]: please remove this line

Comment (biozshock) [reply src/Symfony/Component/Form/Tests/Extension/Core/Type/RepeatedTypeTest.php]: Done!

Just a side question in case you have time: Wouldn't such comments ease moving to typehinted scalar types when 3.4 will be EOL and 4.4 will require 7.1?

Comment (HeahDude) [reply src/Symfony/Component/Form/Tests/Extension/Core/Type/RepeatedTypeTest.php]: Tests are not covered by BC promise, we do add those in the code base though.

Comment (nicolas-grekas) [reply src/Symfony/Component/Form/Tests/Extension/Core/Type/RepeatedTypeTest.php]: We already added all possible types in 5.0, we should not forget to add it here also that true; but if we do, that's no big deal (and eventually someone will figure out :) )

**Comment by xabbuh** [comment]
Wouldn't it make sense to check if we could make the type work with the `mapped` option set to `false`?

**Comment by HeahDude** [comment]
You mean ignoring the option or config setting? It could if we target master with a new feature as the mapping is a requirement for the transformer to do the proper validation. I think that trying to do otherwise will lead to adding unnecessary complexity. Unless you see a simple way to do it?

**Comment by xabbuh** [comment]
What about something like #36430?

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @biozshock.
