### PR TITLE
[Messenger] Check for all serialization exceptions during message dec…

### LINKED ISSUE #35446: [Messenger] Symfony serializer does not check all serializer failures
**Symfony version(s) affected**: 4.4|5.0

**Description**  
When the serialization of a message fails a `MessageDecodingFailedException` should be thrown. 
But this only happens for `UnexpectedValueException` in the [transport serializer](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/Transport/Serialization/Serializer.php#L82).
This means that any other exceptions from the serializer like `MissingConstructorArgumentsException` do not result in a `MessageDecodingFailedException` from the messenger transport serializer.

Because this is not the case, the worker crashes and does not reject the message. This also means that the message stays in the queue, resulting in a crash loop of the worker.

**How to reproduce**  

1. Create a message in the bus without a worker running.
2. Add an extra field to the constructor of the created message
3. Run the worker
4. Message is not rejected because no `MessageDecodingFailedException` was thrown.

**Possible Solution**  
Instead of checking for `Symfony\Component\Serializer\Exception\UnexpectedValueException` check for `Symfony\Component\Serializer\Exception\ExceptionInterface` in `Symfony\Component\Messenger\Transport\Serialization\Serializer`

### PR DESCRIPTION
**Pull request by waaghals**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35446 
| License       | MIT

Makes it so that the Messenger Serializer throws a `MessageDecodingFailedException` for any serializer exception.

### CODE REVIEW

File: src/Symfony/Component/Messenger/Tests/Transport/Serialization/SerializerTest.php [hunk 1]
```diff
@@ -207,7 +207,40 @@ public function testEncodedSkipsNonEncodeableStamps()
...
+
+        $serializer->decode([
+            'body' => '{}',
+            'headers' => ['type' => DummySymfonySerializerInvalidConstructor::class],
+        ]);
+    }
+
+    public function testDecodingStampFailedDeserialization()
+    {
+        $this->expectException(MessageDecodingFailedException::class);
```
Comment (Nyholm) [inline src/Symfony/Component/Messenger/Tests/Transport/Serialization/SerializerTest.php]: Move this down one line. 

This test is used to prove that `MessageDecodingFailedException` is thrown when running `$serializer->decode`. But currently, I can no be sure if the exception is thrown at `$serializer = new Serializer();` or `$serializer->decode`.

**Review by Nyholm — CHANGES_REQUESTED** [review]
Thank you. Just a minor fix and I'll be happy to approve.

**Comment by Nyholm** [comment]
Also, make sure that fabbot.io is happy. =)

File: src/Symfony/Component/Messenger/Tests/Transport/Serialization/SerializerTest.php (hunk 1 above)
Comment (waaghals) [reply src/Symfony/Component/Messenger/Tests/Transport/Serialization/SerializerTest.php]: I've done this for my changes.
I noticed this is the case for other tests as well in the same file. I left those as-is for now.
Let me know if I should update these as well.

Comment (Nyholm) [reply src/Symfony/Component/Messenger/Tests/Transport/Serialization/SerializerTest.php]: Thank you. 
One should never do unrelated changes in a PR. That will make reviews more difficult and possibly delay the merge of the feature you intended. 

Feel free to submit a new PR with those changes and we can discuss them separately.

**Review by Nyholm — APPROVED** [review]
Thank you

**Review by Tobion — APPROVED** [review]
Should be merged in 4.3

**Comment by Tobion** [comment]
Thank you @waaghals.
