### PR TITLE
[Ldap] Deprecate the `sizeLimit` query option

### LINKED ISSUE #58514: [Ldap] Unused 'sizeLimit' option
### Symfony version(s) affected

7.1.x

### Description

Looking at the AbstractQuery option `'sizeLimit'`, it seems that this option is never used.

```php
        $resolver->setDefaults([
            'filter' => '*',
            'maxItems' => 0,
            'sizeLimit' => 0,
            'timeout' => 0,
            'deref' => static::DEREF_NEVER,
            'attrsOnly' => 0,
            'scope' => static::SCOPE_SUB,
            'pageSize' => 0,
        ]);
```

This is the only place where `'sizeLimit'` is referenced in the whole `ldap` component

### How to reproduce

:point_up: 

### Possible Solution

Remove unused option not to confuse the folks

### Additional Context

image

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Issues        | Fix #58514
| License       | MIT

The `sizeLimit` option is never used, it is actually calculated with the `maxItems` option in `Query`. I propose to deprecate the option that is currently no-op anyway.

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

File: src/Symfony/Component/Ldap/Tests/Adapter/AbstractQueryTest.php [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+class AbstractQueryTest extends TestCase
+{
+    use ExpectDeprecationTrait;
+
+    /**
+     * @group legacy
+     */
+    public function testSizeLimitIsDeprecated()
+    {
+        $this->expectDeprecation('Since symfony/ldap 7.2: The "sizeLimit" option is deprecated and will be removed in Symfony 8.0.');
```
Comment (xabbuh) [inline src/Symfony/Component/Ldap/Tests/Adapter/AbstractQueryTest.php]:
```suggestion
        $this->expectUserDeprecation('Since symfony/ldap 7.2: The "sizeLimit" option is deprecated and will be removed in Symfony 8.0.');
```

Comment (xabbuh) [reply src/Symfony/Component/Ldap/Tests/Adapter/AbstractQueryTest.php]: see #54593

Comment (alexandre-daubois) [reply src/Symfony/Component/Ldap/Tests/Adapter/AbstractQueryTest.php]: Nice! Noted for the next ones, thanks!

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @alexandre-daubois.
