### PR TITLE
[Controller][ServiceValueResolver] Making method access case insensitive

### LINKED ISSUE #28254: Confusing exception when using action injection + casing mismatch in routing file
Having such action:
```php
public function index(Request $request, PostRepository $posts): Response
```
and such routing:
```yaml
index:
    path: /en/blog
    controller: App\Controller\BlogController::Index
```

yields
> Controller "App\Controller\BlogController::Index()" requires that you provide a value for the "$posts" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one.

This is because user made a typo in routing and used BlogController::**I**ndex, instead of BlogController::**i**ndex

### PR DESCRIPTION
**Pull request by nicoweb**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #28254 
| License       | MIT
| Doc PR        | -

Fix #28254 by making the method access insensitive in `ServiceValueResolver`.

### CODE REVIEW

File: src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php [hunk 1]
```diff
@@ -47,6 +47,8 @@ public function supports(Request $request, ArgumentMetadata $argument)
             $controller = ltrim($controller, '\\');
         }
 
+        $controller = $this->normalizeMethod($controller);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php]: I you don't mind, I'd like to propose an alternative implementation instead of this method:
```diff
a/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php
+++ b/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php
@@ -47,6 +47,10 @@ final class ServiceValueResolver implements ArgumentValueResolverInterface
             $controller = ltrim($controller, '\\');
         }
 
+        if (!$this->container->has($controller) && false !== $i = strrpos($controller, ':')) {
+            $controller = substr($controller, 0, $i).strtolower(substr($controller, $i));
+        }
+
         return $this->container->has($controller) && $this->container->get($controller)->has($argument->getName());
     }
 
@@ -63,6 +67,11 @@ final class ServiceValueResolver implements ArgumentValueResolverInterface
             $controller = ltrim($controller, '\\');
         }
 
+        if (!$this->container->has($controller)) {
+            $i = strrpos($controller, ':');
+            $controller = substr($controller, 0, $i).strtolower(substr($controller, $i));
+        }
+
         yield $this->container->get($controller)->get($argument->getName());
     }
```

Comment (nicoweb) [reply src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php]: Ok, good idea..

Comment (nicoweb) [reply src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php]: Updated.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by ostrolucky** [comment]
Does this handle older AppBundle:Blog:list notation (notice no `::` in there)?

**Comment by nicolas-grekas** [comment]
@ostrolucky the attached patch searches for only one `:` so it will work equally well with one or two `:`.
Also, I don't think the old notation ever hits the `ServiceValueResolver`: it is resolved before.
