### PR TITLE
[Mailer] Fix mandrill raw http request setting from email/name

### LINKED ISSUE #36879: [Mailer] Invalid Mandrill send raw api with named addresses
**Symfony version(s) affected**: 4.4.8

**Description**  
Sending emails with the Mandrill (MailChimp) API doesn't work when using named addresses for `from` options. With https://github.com/symfony/symfony/issues/33993 setting address is fixed for api `/api/1.0/messages/send.json` but my mails are send via `MandrillHttpTransport::doSendHttp()` which will use `/api/1.0/messages/send-raw.json`. here we still set wrong `from_email`. More docs about send-raw are on mandrill see https://mandrillapp.com/api/docs/messages.curl.html#method-send-raw

**How to reproduce**  
```
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\Mailer\Mailer;
use Symfony\Component\Mime\Address;
use Symfony\Component\Mailer\Transport;

$transport = Transport::fromDsn(sprintf('api://%s@mandrill', 'YOUR_KEY'));
$mailer = new Mailer($transport);

$email = new TemplatedEmail();
$email
    ->from(new Address('test@example.com', 'My Name'))
    ->subject('Subject')
    ->text('Message')
    ->to(
        new Address('recipient@example.com', 'Recipient Name')
    )
;

$mailer->send($email);
```

**Possible Solution**  
The solution that was done for `send` will also apply for `send-raw` see https://github.com/symfony/symfony/issues/33993

Let me know if i should make a pull request to fix this.

### PR DESCRIPTION
**Pull request by JohJohan**
| Q             | A
| ------------- | ---
| Branch?       | 4.4, 5.0, 5.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no 
| Tickets       | Fix #36879 
| License       | MIT
| Doc PR        | None

As describe in https://github.com/symfony/symfony/issues/36879 there is a bug in sending raw http request to mandrill it will not set from email/name correct.

As you can see i make sure to set `from_email` and `from_name` correct now and changed the unit test to check correct you can see the doc that the format is correct https://mandrillapp.com/api/docs/messages.curl.html#method-send-raw

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Mailer/Bridge/Mailchimp/Transport/MandrillHttpTransport.php [hunk 1]
```diff
@@ -49,7 +49,8 @@ protected function doSendHttp(SentMessage $message): ResponseInterface
                 'to' => array_map(function (Address $recipient): string {
                     return $recipient->getAddress();
                 }, $envelope->getRecipients()),
-                'from_email' => $envelope->getSender()->toString(),
+                'from_email' => $envelope->getSender()->getAddress(),
+                'from_name' => $envelope->getSender()->getName(),
```
Comment (fabpot) [inline src/Symfony/Component/Mailer/Bridge/Mailchimp/Transport/MandrillHttpTransport.php:53]: A sender in the envelope does not have a name. If that works, it is by chance and won't work anymore in 5.0 anyway. I haven't time right now to investigate, but we need to find another way.

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Mailer/Bridge/Mailchimp/Transport/MandrillHttpTransport.php (hunk 1 above)
Comment (JohJohan) [reply src/Symfony/Component/Mailer/Bridge/Mailchimp/Transport/MandrillHttpTransport.php:53]: Do you mean that https://github.com/symfony/symfony/blob/017420b5119578ae45adb58dc9118c701b4d2b7f/src/Symfony/Component/Mailer/Envelope.php doesn't set the name when creating new Address objects?

Also i just tested this and in gmail i see correct name i set via Address object like:
`->from(new Address('test@example.nl', 'Testing'))`

I will get `Testing` as name in my mail

Comment (JohJohan) [reply src/Symfony/Component/Mailer/Bridge/Mailchimp/Transport/MandrillHttpTransport.php:53]: Is there anything i can do?

Comment (JohJohan) [reply src/Symfony/Component/Mailer/Bridge/Mailchimp/Transport/MandrillHttpTransport.php:53]: I have looked again and i'm doing the same thing as in Sendgrid see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mailer/Bridge/Sendgrid/Transport/SendgridApiTransport.php#L78 the only difference here is we check if name is not empty i can also add that to my pull request?

I also see the same code is used in Mailchimp transporter which makes sence as Mandrill and Mailchimp are one see code https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mailer/Bridge/Mailchimp/Transport/MandrillHttpTransport.php#L54 do you want me to make changes here as well?

Comment (fabpot) [reply src/Symfony/Component/Mailer/Bridge/Mailchimp/Transport/MandrillHttpTransport.php:53]: It now works as expected (refs #37580).

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @JohJohan.
