### PR TITLE
[Security] Lazily load the user during the check passport event

### LINKED ISSUE #37436: [RFC][Security] Load user during CheckPassportEvent
## Current situation

The authenticators load a user in the `authenticate(Request $request): PassportInterface` method and return a passport with the user instance and any credentials/badges.

```php
public function authenticate(Request $request): PassportInterface
{
    $user = $this->userRepository->findOneByUsername($request->get('_username'));
    if (!$user) {
        throw new UsernameNotFoundException();
    }

    return new Passport($user, ...);
}
```

This method was chosen as it allowed to merge the `getCredentials()`, `getUser()` and `checkCredentials()` methods of Guard into 1 method, making things easier to understand and use.

## The limitations

However, while working on some new features, I found a major limitation of this idea: **The first place to hook into the authentication process is *after* the user is loaded.**
This prevents things like checking CSRF or login throttling before interacting with the database (preventing server load in spam requests) and allowing login throttling to work for invalid usernames (currently, a login throttling listener on CheckPassportEvent needs a valid username in order to be called).

## The solution

A possible solution I can think of is also making user loading part of the badge system, creating 2 default ways to load users:

1. Using the preconfigured `UserProviderInterface`:
    ```php
    public function authenticate(Request $request): PassportInterface
    {
        return new Passport(
            new UserFromProvider($request->get('_username')),
            new PasswordCredentials($request->get('_password')),
            [new LoginThrottlingBadge($request->get('_username')]
        );
    }
    ```
2. Using a closure:
    ```php
    public function authenticate(Request $request): PassportInterface
    {
        return new Passport(
            new UserFromClosure($request->get('_username'), [$this, 'loadUser']),
            new PasswordCredentials($request->get('_password')),
            [new LoginThrottlingBadge($request->get('_username')]
        );
    }

    public function loadUser(string $username): UserInterface
    {
        return $this->userRepository->findOneByUsername($username);
    }
    ```

### PR DESCRIPTION
**Pull request by wouterj**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | yes
| Tickets       | Fix #37436 
| License       | MIT
| Doc PR        | tbd

**Before**
```php
class ApiKeyAuthenticator extends AbstractAuthenticator
{
    // ...

    public function authenticate(Request $request): PassportInterface
    {
        $email = $request->headers->get('X-USER-EMAIL');
        if (false === strpos($email, '@')) {
            throw new BadCredentialsException('Email is not a valid email address.');
        }

        $user = $this->userRepository->findOneBy(['email' => $email]);
        if (null === $user) {
            throw new UsernameNotFoundException();
        }

        return new SelfValidatingPassport($user);
    }
}
```

**After**
```php
class ApiKeyAuthenticator extends AbstractAuthenticator
{
    // ...

    public function authenticate(Request $request): PassportInterface
    {
        $email = $request->headers->get('X-USER-EMAIL');
        if (false === strpos($email, '@')) {
            throw new BadCredentialsException('Email is not a valid email address.');
        }

        // a global ChainUserProvider (or firewall provider if explicitly configured) will be
        // used to load the User with $email as username
        return new SelfValidatingPassport($email);

        // or a custom closure to load the user
        return new SelfValidatingPassport(new UserBadge($email, function ($username) {
            return $this->userRepository->findOneBy(['email' => $username]);
        });
    }
}
```

Doing it this way has a couple advantages (some of which are already mentioned in the issue):

* Some listeners on `CheckPassportEvent` need to execute *before* loading the user - to reduce resources (e.g. CSRF protection, if CSRF fails, no DB call should be made to load user - and also login throttling);
* Some listeners require knowing the username of the login action (e.g. login throttling on IP and username);
* The `UserProviderListener` allows to remove yet another centralized action in the authentication process from the authenticator class to the Symfony framework.

Automatic User Provider integration
---

Instead of passing the credentials and a closure to `UserBadge`, you can also just pass a (string) username. The user provider will then be used to load the user. This only works for `custom_authenticators` as of this moment.

* By default, a chain user provider with all configured `user_providers` will be used as the user provider;
* However, if you explicitly configure a `provider` for that firewall, that provider will be used (using a listener with higher priority).

### CODE REVIEW

**Comment by fabpot** [comment]
I like this very much.

**Comment by wouterj** [comment]
Thank you @fabpot :smiley: 

This PR is ready for a review now, I've added some functional tests to make sure things are working.

**Comment by fabpot** [comment]
I think you 2 additional changes you mentioned are worth investigating.

File: src/Symfony/Component/Security/Http/Authenticator/Passport/Passport.php [hunk 1]
```diff
@@ -31,13 +32,24 @@ class Passport implements UserPassportInterface
...
+    public function __construct($usernameOrBadge, CredentialsInterface $credentials, array $badges = [])
     {
-        $this->user = $user;
+        if ($usernameOrBadge instanceof UserInterface) {
+            trigger_deprecation('symfony/security-http', '5.2', 'The user argument of "%s" must be a "%s" or a string containing the username.', __CLASS__, UserBadge::class);
+
+            $this->user = $usernameOrBadge;
+        } elseif ($usernameOrBadge instanceof UserBadge) {
+            $this->addBadge($usernameOrBadge);
+        } elseif (\is_string($usernameOrBadge)) {
```
Comment (fabpot) [inline src/Symfony/Component/Security/Http/Authenticator/Passport/Passport.php:48]: I'm wondering if we should only allow `UserBadge` instances. Using `new UserBadge($username)` is a bit more explicit than `$username` and still quite simple to understand IMHO.

**Review by fabpot — APPROVED** [review]
I've made a small suggestion, not sure if that makes sense. What do you think about it?

File: src/Symfony/Component/Security/Http/Authenticator/Passport/Badge/UserBadge.php [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+use Symfony\Component\Security\Core\User\UserInterface;
+use Symfony\Component\Security\Http\EventListener\UserProviderListener;
+
+class UserBadge implements BadgeInterface
+{
+    private $username;
+    private $userLoader;
+    private $user;
+
+    public function __construct(?string $username, ?callable $userLoader = null)
```
Comment (weaverryan) [inline src/Symfony/Component/Security/Http/Authenticator/Passport/Badge/UserBadge.php:24]: We should probably document both of these, because:

1) We need to communicate that `$username` is not necessarily a username... but just some "identifier". We probably need to communicate its *purpose*. For example, suppose I have a login form that has an `email` field AND a `company ` drop-down. So, when I query the database for the user, the query is something like:

> SELECT * FROM user WHERE email = :email AND company_id = :companyId

Obviously, I would probably make the query and load the user by passing a 2nd argument to `new UserBadge()` with a callback that makes the custom query.

The question is: what value should I pass as the `$username`? Should it just be `$email`? Probably not. Should it be `['email' => $email, 'companyId' => $companyId]`? Well, right now, the first argument must be a string... and probably (?) we want to keep it that way. So, should the user pass `$email'._'.$companyId`... because the purpose of this argument is to be some "unique string identifier" of the user?

2) We should document that the 2nd arg is optional, must return `UserInterface` or `null` and will be passed the `$username`.

File: src/Symfony/Component/Security/Http/Authenticator/Passport/Badge/UserBadge.php [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+    {
+        $this->username = $username;
+        $this->userLoader = $userLoader;
+    }
+
+    public function getUsername(): string
```
Comment (weaverryan) [inline src/Symfony/Component/Security/Http/Authenticator/Passport/Badge/UserBadge.php:30]: As it's written now, this could be nullable. But do we want to allow the first arg to the constructor to be nullable?

File: src/Symfony/Component/Security/Http/Authenticator/Passport/Badge/UserBadge.php [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+        if (null === $this->userLoader) {
+            throw new \LogicException(sprintf('No user loader is configured, did you forget to register the "%s" listener?', UserProviderListener::class));
+        }
+
+        $this->user = ($this->userLoader)($this->username);
+        if (null === $this->user) {
+            throw new UsernameNotFoundException();
+        }
+
+        return $this->user;
```
Comment (weaverryan) [inline src/Symfony/Component/Security/Http/Authenticator/Passport/Badge/UserBadge.php:46]: We're setting the User into a `user` property but not really relying on that. If we called `getUser()` twice, it would execute our callback twice. I'm not sure which is the desired behavior :)

File: src/Symfony/Bundle/SecurityBundle/Resources/config/security_authenticator.php [hunk 5]
```diff
@@ -73,6 +75,18 @@
             ])
             ->tag('kernel.event_subscriber')
 
+        ->set('security.listener.user_provider', UserProviderListener::class)
+            ->args([
+                service('security.user_providers'),
+            ])
+            ->tag('kernel.event_listener', ['event' => CheckPassportEvent::class, 'priority' => 1024, 'method' => 'checkPassport'])
```
Comment (weaverryan) [inline src/Symfony/Bundle/SecurityBundle/Resources/config/security_authenticator.php:82]: Is this first service used? I may just be missing it

File: src/Symfony/Component/Security/Guard/Authenticator/GuardBridgeAuthenticator.php [hunk 6]
```diff
@@ -62,14 +63,11 @@ public function authenticate(Request $request): PassportInterface
...
-        $user = $this->guard->getUser($credentials, $this->userProvider);
-
-        if (null === $user) {
-            throw new UsernameNotFoundException(sprintf('Null returned from "%s::getUser()".', get_debug_type($this->guard)));
-        }
-
-        if (!$user instanceof UserInterface) {
-            throw new \UnexpectedValueException(sprintf('The "%s::getUser()" method must return a UserInterface. You returned "%s".', get_debug_type($this->guard), get_debug_type($user)));
+        if (class_exists(UserBadge::class)) {
+            $user = new UserBadge(null, function () use ($credentials) { return $this->getUser($credentials); });
```
Comment (weaverryan) [inline src/Symfony/Component/Security/Guard/Authenticator/GuardBridgeAuthenticator.php:67]: If this is the reason why we've made the first arg to `UserBadge` null, then we *could* work around that by using `'guard_credentials'.md5($credentials)` or something like that.

File: src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php [hunk 7]
```diff
@@ -69,7 +70,7 @@ public function __construct(iterable $authenticators, TokenStorageInterface $tok
     public function authenticateUser(UserInterface $user, AuthenticatorInterface $authenticator, Request $request, array $badges = []): ?Response
     {
         // create an authenticated token for the User
-        $token = $authenticator->createAuthenticatedToken($passport = new SelfValidatingPassport($user, $badges), $this->firewallName);
+        $token = $authenticator->createAuthenticatedToken($passport = new SelfValidatingPassport(new UserBadge(null, function () use ($user) { return $user; }), $badges), $this->firewallName);
```
Comment (weaverryan) [inline src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php:73]: `new UserBadge($user->getUsername(),`?

Again, we need to be really clear about the *purpose* of this first argument to `new UserBadge()`. That will make these decisions more clear.

File: src/Symfony/Component/Security/Http/EventListener/UserProviderListener.php [hunk 8]
```diff
@@ -0,0 +1,45 @@
...
+            return;
+        }
+
+        /** @var UserBadge $badge */
+        $badge = $passport->getBadge(UserBadge::class);
+        if (null !== $badge->getUserLoader()) {
+            return;
+        }
+
+        $badge->setUserLoader([$this->userProvider, 'loadUserByUsername']);
```
Comment (weaverryan) [inline src/Symfony/Component/Security/Http/EventListener/UserProviderListener.php:43]: That's a nice implementation

**Review by fabpot — APPROVED** [review]

File: src/Symfony/Component/Security/Http/Authenticator/Passport/SelfValidatingPassport.php [hunk 9]
```diff
@@ -25,11 +26,20 @@
...
     /**
+     * @param UserBadge        $userBadge
      * @param BadgeInterface[] $badges
      */
-    public function __construct(UserInterface $user, array $badges = [])
+    public function __construct($userBadge, array $badges = [])
     {
-        $this->user = $user;
+        if ($userBadge instanceof UserInterface) {
+            trigger_deprecation('symfony/security-http', '5.2', 'The user argument of "%s" must be a "%s" or a string containing the username.', __CLASS__, UserBadge::class);
```
Comment (chalasr) [inline src/Symfony/Component/Security/Http/Authenticator/Passport/SelfValidatingPassport.php:35]: Given it was experimental in 5.1, is it really worth adding a BC Layer?

**Review by chalasr — COMMENTED** [review]
Nice one, 1 minor comment. Should we add a CHANGELOG entry?

File: src/Symfony/Component/Security/Http/Authenticator/Passport/SelfValidatingPassport.php (hunk 9 above)
Comment (fabpot) [reply src/Symfony/Component/Security/Http/Authenticator/Passport/SelfValidatingPassport.php:35]: I have a mixed feeling about this one. I think one should accept/expect BC breaks for experimental features. If it's well documented in the CHANGELOG, I think we should remove the deprecation notice and fail hard.

Comment (wouterj) [reply src/Symfony/Component/Security/Http/Authenticator/Passport/SelfValidatingPassport.php:35]: Hmm, as this class is used in every custom authenticator made by early-adapters and the BC layer was very small, I decided to avoid the hard break. Would it help any if we remove the BC break in 5.3 already? (and adding that as part of the error message)

File: src/Symfony/Component/Security/Http/Authenticator/Passport/Passport.php [hunk 10]
```diff
@@ -31,13 +32,22 @@ class Passport implements UserPassportInterface
...
      * @param CredentialsInterface $credentials the credentials to check for this authentication, use
      *                                          SelfValidatingPassport if no credentials should be checked
      * @param BadgeInterface[]     $badges
      */
-    public function __construct(UserInterface $user, CredentialsInterface $credentials, array $badges = [])
+    public function __construct($userBadge, CredentialsInterface $credentials, array $badges = [])
     {
-        $this->user = $user;
+        if ($userBadge instanceof UserInterface) {
+            trigger_deprecation('symfony/security-http', '5.2', 'The user argument of "%s" must be a "%s" or a string containing the username.', __CLASS__, UserBadge::class);
```
Comment (chalasr) [inline src/Symfony/Component/Security/Http/Authenticator/Passport/Passport.php:43]: > or a string containing the username.

Strings don't seem to be allowed here, isn't it?

File: src/Symfony/Component/Security/Http/Authenticator/Passport/SelfValidatingPassport.php (hunk 9 above)
Comment (fabpot) [reply src/Symfony/Component/Security/Http/Authenticator/Passport/SelfValidatingPassport.php:35]: @wouterj your plan sounds good to me.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @wouterj.
