### PR TITLE
[Serializer] make XmlEncoder stateless thus reentrant

### LINKED ISSUE #37354: [Serializer] paralell XMLEncoder::encode can cause "Wrong Document Error"
**Symfony version(s) affected**: 5.0

**Description**  
If you start an XMLEncode::encode process in the middle of a normalization (you need to create an base64 encoded XML sub document), cause an "Wrong Document Error" DomDocument exception at:
https://github.com/symfony/symfony/blob/3e57f1f49f993b275fc014e029fc542ead2c15fb/src/Symfony/Component/Serializer/Encoder/XmlEncoder.php#L448

Here is the call stack:
- The app call the serialize with: $serializer->serialize($data, "xml", [...context...]);
- The first serialize call the createDomDocument at:
https://github.com/symfony/symfony/blob/3e57f1f49f993b275fc014e029fc542ead2c15fb/src/Symfony/Component/Serializer/Encoder/XmlEncoder.php#L93
- The XMLEncoder call normalizer at:
https://github.com/symfony/symfony/blob/3e57f1f49f993b275fc014e029fc542ead2c15fb/src/Symfony/Component/Serializer/Encoder/XmlEncoder.php#L415
- In CustomNormalizer::normalize we call 
$serializer->serialize($otherdata, "xml", [...other context...]);
- Second serialize override dom at:
https://github.com/symfony/symfony/blob/3e57f1f49f993b275fc014e029fc542ead2c15fb/src/Symfony/Component/Serializer/Encoder/XmlEncoder.php#L93
- When we done the normalization the encoder fails here because the second serializer did override the dom:
https://github.com/symfony/symfony/blob/3e57f1f49f993b275fc014e029fc542ead2c15fb/src/Symfony/Component/Serializer/Encoder/XmlEncoder.php#L448

**How to reproduce**  
Create an XML with an base64 encoded xml subcontent:
```
<?xml version="1.0"?>
<node>...base64encoded xml...</node>
```

xml to base64 encode:
```
<?xml version="1.0"?>
<node2>test</node2>
```

**Possible Solution**  
DOMDocument of XMLEncoder should stackable. 

**Additional context**  
I will post repo, test and PR later.

### PR DESCRIPTION
**Pull request by connorhu**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37354 
| License       | MIT

Changing dom property of XmlEncoder to stackable. It fixes a DOMException "Wrong document error". When you calling XmlEncoder->encode() in parallel createDomDocument replaces the DomDocument object.
Test code:
https://github.com/connorhu/symfony-serializer/blob/master/test.php

### CODE REVIEW

File: src/Symfony/Component/Serializer/Encoder/XmlEncoder.php [hunk 1]
```diff
@@ -102,7 +121,10 @@ public function encode($data, string $format, array $context = [])
             $this->appendNode($this->dom, $data, $xmlRootNodeName);
         }
 
-        return $this->dom->saveXML($ignorePiNode ? $this->dom->documentElement : null);
+        $encodedString = $this->dom->saveXML($ignorePiNode ? $this->dom->documentElement : null);
+        $this->popDom();
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Encoder/XmlEncoder.php]: no need for new methods imho, this can be done inline

**Review by nicolas-grekas — COMMENTED** [review]
can you please add a test case and rebase+target the lowest branch where this issue exists (3.4 I suppose?)

File: src/Symfony/Component/Serializer/Encoder/XmlEncoder.php (hunk 1 above)
Comment (connorhu) [reply src/Symfony/Component/Serializer/Encoder/XmlEncoder.php]: @nicolas-grekas I can change popDom to inline, but should pushDom also inline?

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Encoder/XmlEncoder.php]: yes please

File: src/Symfony/Component/Serializer/Encoder/XmlEncoder.php [hunk 2]
```diff
@@ -77,6 +78,24 @@ public function __construct(array $defaultContext = [])
...
+        if (null !== $this->dom) {
+            $this->domStack[] = $this->dom;
+        }
+
+        $this->dom = $this->createDomDocument($context);
+    }
+
+    private function popDom(): void
+    {
+        if (0 === \count($this->domStack)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Encoder/XmlEncoder.php]:
```php
if ($this->domStack) {
    $this->dom = array_pop($this->domStack);
}
```

**Comment by stof** [comment]
Rather than maintaining a stack of current document (which is not properly maintained in case of errors btw, as the unstacking should be done in a `finally` block), a better solution could be to avoid the need for the state at all, by removing `$this->dom`. Instead, the `\DOMDocument` could be passed as argument to private methods needing it (and a bunch of the existing private methods might use `$node->ownerDocument` instead of `$this->dom` to avoid the need to add an argument in their signature).

**Comment by connorhu** [comment]
@stof I have tested the ownerDocument method. It seems to be a working solution and the tests are running but. At the appendNode method the $parentNode argument can be DomDocument so the onwerDocument is null:
https://github.com/connorhu/symfony/commit/a6f0be318752a230058316a039c5ba2f6a939bb0#diff-b031dbb2186367839adfe20696612866da91513dd315f00ad6df23b5d38fca74L467-R452

**Comment by stof** [comment]
@connorhu if the parentNode is already a DomDocument, you already have the DomDocument. That's fine to me.

**Comment by stof** [comment]
If we want to make the encoder re-entrant, I think the state in `$this->context` is also an issue, not only `$this->dom`

**Comment by nicolas-grekas** [comment]
I rebased the PR for branch 3.4 but there are some failure to fix, could you please have a look?

**Comment by connorhu** [comment]
@nicolas-grekas Of course! Thank you!

**Comment by connorhu** [comment]
I think my original bug is now fixed. The current version of XmlEncoder in symfony 3.4 is not so complex. I don't see how can cause the context property a bug like the dom did.

**Comment by stof** [comment]
@connorhu the issue is exactly the same that with `$this->dom` actually: if you call the serializer again during serialization, sotring the call-specific state in the instance will break as the encoder won't be re-entrant (it handles only one state at a time), and it might end up using the wrong state.
The reason you don't see an issue in your reproducing code is because you use an empty context for both calls, so using the wrong empty context is not an issue.

**Comment by connorhu** [comment]
@stof I see the possibility of the context bug, but If you use nothing from context after initialization it can't cause a bug. Safer to remove context property instead of making a note for the future code changes.

**Comment by stof** [comment]
@connorhu the thing is, the XmlEncoder *is* using the context in some of the private methods.

**Comment by connorhu** [comment]
@stof Should I merge the context property remove patch into in this PR? The referred bug only describes the bug about the dom property.

**Review by nicolas-grekas — APPROVED** [review]
(I rebased and implemented the remaining)

**Comment by nicolas-grekas** [comment]
Thank you @connorhu.
