### PR TITLE
[Form] Use reference date in reverse transform

### LINKED ISSUE #40997: [Form] Inconsistant display in TimeType (array mode)
**Symfony version(s) affected**: 5.2.6 (at least)
**Description**
When you use the `TimeType` in forms with the `input` type set to `array` and then you set different `view_timezone` and `model_timezone` options the conversion will be inconsistant. When you load save it the timezone is correct but when you load it it's off.

**How to reproduce**

1. Get a TimeType form field
2. Set input to array
3. Set model_timezone to UTC
4. Set view_timezone to Europe/Berlin
5. Enter a date and save it to a database
6. Navigate away and reload that value

**Possible Solution**
https://github.com/symfony/form/blob/8822890bdb6267f8d1c027f697db4bd83c2afc55/Extension/Core/Type/TimeType.php#L208 is not set like it's in line 193, set it and it will work

### PR DESCRIPTION
**Pull request by KDederichs**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #40997
| License       | MIT

Use reference time in reverse transform to fix the display inconsistancies

### CODE REVIEW

**Comment by xabbuh** [comment]
Can you add a test case that would fail without this patch?

**Comment by KDederichs** [comment]
> Can you add a test case that would fail without this patch?

Let me see if I can make a good one

**Comment by KDederichs** [comment]
hmmm, maybe it's more of an issue of if should be a valid setting for that input anyways (maybe help me out with thinking here).
Does the timezone need to be applied to an array field that only stores hours and minutes in the first place? The more I think about it the answer is: probably not.
Cause tbh it's a bit of strange and undefined behaviour which probably also relates to the other thing I ran into:
https://github.com/symfony/symfony/pull/41000

Maybe it would me more sense to disable the model and view timezone options for the array input all together and throw a logic exception when you try it?

**Comment by xabbuh** [comment]
Does this apply to 4.4 too?

**Comment by KDederichs** [comment]
Yes, this changed line is present in 4.4 as well

File: src/Symfony/Component/Form/Tests/Extension/Core/Type/TimeTypeTest.php [hunk 1]
```diff
@@ -978,6 +978,27 @@ public function testSubmitNullUsesDefaultEmptyData($emptyData = [], $expectedDat
...
+
+        $form = $this->factory->create(static::TESTED_TYPE, $input, [
+            'model_timezone' => 'UTC',
+            'view_timezone' => 'Europe/Berlin',
+            'reference_date' => new \DateTimeImmutable('01-05-2021 12:34:56', new \DateTimeZone('UTC')),
+            'input' => 'array',
+        ]);
+
+        $this->assertEquals($input, $form->getData());
+        $this->assertEquals([
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Tests/Extension/Core/Type/TimeTypeTest.php:1009]: please use assertSame as much as possible

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @KDederichs.
