### PR TITLE
[DoctrineBridge] Fixed submitting invalid ids when using queries with limit

### LINKED ISSUE #31559: [Form] EntityType: 'query_builder' and 'setMaxResults' weird behavior
**Symfony version(s) affected**: 4.2.7

**Description**  
I'm not sure this is a bug. It might be a simple question, but surely about a behavior I consider like weird.
In some Form, in some `EntityType` with `'multiple' => true`, if you interfer with the `query_builder` and call `setMaxResults(x)` on the builder, then `x` will also enter in validation flow: the form field will be invalid if the number of submitted entities is greater than `x`.

**How to reproduce**  
Let's consider this:
```php
public function buildForm(FormBuilderInterface $builder, array $options): void
{
    $builder
        ->add('authors', EntityType::class, [
            'required' => false,
            'class' => User::class,
            'query_builder' => function (EntityRepository $r) {

            return $r
                ->createQueryBuilder('user')
                ->setMaxResults(2)
            ;
        },
   ;
}
```
From this point, nothing stops the frontend from sending more than 2 entities. You could imagine Select2 field with its own AJAX request. And this will lead to the form being invalid.

One could argue this makes no sense to limit the query to 2 results then sending 3 entities. While I could agree with this, my concern is not about the logic behind the behavior, but the fact that I think it's not the role of the `query_builder` option to define parallel constraints on its way or have any influence upon form validation. It is not documented, it raises very generic error messages, in one word it is rather unpredictable.

**Possible Solution**  
If it's a bug, well it's a bug, happy for having reported it. I did not have any time to dig into the code and understand the behavior, though, so I did not come out with a fix. I could try finding some time for this if you ask. (:

If it's a wanted behavior, I won't debate the choice itself, but I think it could be better documented or at least raise a more accurate error message on the form field.

### PR DESCRIPTION
**Pull request by HeahDude**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #31559 
| License       | MIT
| Doc PR        | ~

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php [hunk 1]
```diff
@@ -55,6 +55,26 @@ public function getEntities()
      */
     public function getEntitiesByIds($identifier, array $values)
     {
+        if (null !== $this->queryBuilder->getMaxResults()) {
+            $metadata = $this->queryBuilder->getEntityManager()->getClassMetadata(current($this->queryBuilder->getRootEntities()));
```
Comment (HeahDude) [inline src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php]: The only other way I see to fix this is to throw an exception here and to catch it in the `DoctrineChoiceLoader` to let it fall back on loading the list. But I would prefer to have it part of the `EntityLoaderInterface` contract rather than leaking too much in there.

File: src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php [hunk 2]
```diff
@@ -55,6 +55,26 @@ public function getEntities()
      */
     public function getEntitiesByIds($identifier, array $values)
     {
+        if (null !== $this->queryBuilder->getMaxResults()) {
```
Comment (HeahDude) [inline src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php]: Usage of offset might be an issue too

File: src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php [hunk 3]
```diff
@@ -55,6 +55,21 @@ public function getEntities()
...
     public function getEntitiesByIds($identifier, array $values)
     {
+        if (null !== $this->queryBuilder->getMaxResults() || null !== $this->queryBuilder->getFirstResult()) {
+            // an offset or a limit would apply on results including the where clause with submitted id values
+            // that could make invalid choices valid
+            $choices = [];
+            $metadata = $this->queryBuilder->getEntityManager()->getClassMetadata(current($this->queryBuilder->getRootEntities()));
+
+            foreach ($this->getEntities() as $entity) {
+                if (false !== array_search(current($metadata->getIdentifierValues($entity)), $values, true)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php]: in_array()

**Comment by nicolas-grekas** [comment]
We could also consider the original issue an unsupported: doing a LIMIT query for a choice list looks very strange to me.

**Comment by HeahDude** [comment]
I agree, I also felt that way. But we might consider some kind of "paginated" choices as a valid use case, or whatever reason leading to open the related issue.
Moreover is there any reason to forbid it since this has the cost of a BC break?

Finally the expected behavior covered here by the test seems a legit bug fix to me, but we could still deprecate that `if` in master and get back to simple code in 6.0, also documenting the limitations this time. WDYT?

**Comment by HeahDude** [comment]
Also note that preventing the optimization in such does lead to adding complexity and/or throwing or new specialised exception form the entity loader to catch in the DoctrineChoiceLoader as I propose in my comment above.

**Comment by HeahDude** [comment]
If we were to forbid it purely and simply I think this should better be done when normalizing the `query_builder` option to throw as soon as possible a configuration exception.

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @HeahDude.

File: src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php [hunk 4]
```diff
@@ -55,6 +55,21 @@ public function getEntities()
...
     public function getEntitiesByIds($identifier, array $values)
     {
+        if (null !== $this->queryBuilder->getMaxResults() || null !== $this->queryBuilder->getFirstResult()) {
+            // an offset or a limit would apply on results including the where clause with submitted id values
+            // that could make invalid choices valid
+            $choices = [];
+            $metadata = $this->queryBuilder->getEntityManager()->getClassMetadata(current($this->queryBuilder->getRootEntities()));
+
+            foreach ($this->getEntities() as $entity) {
+                if (\in_array(current($metadata->getIdentifierValues($entity)), $values, true)) {
```
Comment (jirinapravnik) [inline src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php]: Is it ok with strict in_array? There is comming string variable from EntityType, but getIdentifierValues return integer from entity (if I am using strict_types). Then I get always error by comparing string vs integer.

Comment (HeahDude) [reply src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php]: Thank you @jirinapravnik, I've opened #35609 to fix this.
