### PR TITLE
[Messenger] Fix `DeduplicateStamp` serialization

### LINKED ISSUE #60659: [Messenger] DeduplicateMiddleware using Symfony Serializer
### Symfony version(s) affected

7.3

### Description

When using the symfony serializer component to save messages data in a database, the deserializer is not able to deserialize the DeduplicateStamp.

Error :  Could not decode stamp: The type of the "key" attribute for class "Symfony\Component\Messenger\Stamp\DeduplicateStamp" must be one of "string" ("array" given).

### How to reproduce

Reproduction Repo : https://github.com/or-benjamin/Symfony-Messenger-DeduplicateMiddleware-Bug

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by VincentLanglet**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #60659
| License       | MIT

7.4 for bugfix since it requires the LockKeyNormalizer

### CODE REVIEW

File: src/Symfony/Component/Messenger/Stamp/DeduplicateStamp.php [hunk 1]
```diff
@@ -19,20 +19,27 @@ final class DeduplicateStamp implements StampInterface
...
 
     public function onlyDeduplicateInQueue(): bool
     {
-        return $this->onlyDeduplicateInQueue;
+        trigger_deprecation('symfony/messenger', '7.4', 'The "onlyDeduplicateInQueue()" method is deprecated, use "isOnlyDeduplicatedInQueue()" instead.');
+
+        return $this->isOnlyDeduplicatedInQueue();
+    }
+
+    public function isOnlyDeduplicatedInQueue(): bool
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Stamp/DeduplicateStamp.php]: we should be able to skip adding a new method by adding an annotation on the current one, isn't it?

File: src/Symfony/Component/Messenger/Transport/Serialization/Serializer.php [hunk 2]
```diff
@@ -53,7 +55,17 @@ public static function create(): self
         }
 
         $encoders = [new XmlEncoder(), new JsonEncoder()];
-        $normalizers = [new DateTimeNormalizer(), new ArrayDenormalizer(), new ObjectNormalizer()];
+        $normalizers = [
+            new DateTimeNormalizer(),
+            new ArrayDenormalizer(),
+            new ObjectNormalizer(
+                propertyTypeExtractor: new ReflectionExtractor(),
+            ),
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Transport/Serialization/Serializer.php]:
```suggestion
            new ObjectNormalizer(propertyTypeExtractor: new ReflectionExtractor()),
```

File: src/Symfony/Component/Messenger/Stamp/DeduplicateStamp.php (hunk 1 above)
Comment (VincentLanglet) [reply src/Symfony/Component/Messenger/Stamp/DeduplicateStamp.php]: Tests are failing without this method.
If I tried something like `#[SerializedName()]` on the previous method it's ignored.
Did you have something else in mind ?

The ObjectNormalizer is just looking at method/property without checking attributes https://github.com/symfony/symfony/blob/e880e531a5aef3b9523703eb7a5634df6951bd0f/src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php#L64-L128

Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Stamp/DeduplicateStamp.php]: is there no way to split the Serializer concern from the exact API of the stamp? I doesn't feel right to me to add a deprecation to fit some external constraints.

Comment (VincentLanglet) [reply src/Symfony/Component/Messenger/Stamp/DeduplicateStamp.php]: I understand but currently I didn't find one.

If I start parsing Attribute with
```
new ObjectNormalizer(
                classMetadataFactory: new ClassMetadataFactory(new AttributeLoader()),
                propertyTypeExtractor: new ReflectionExtractor()
            ),
```
I get the following exception:
https://github.com/symfony/symfony/blob/e880e531a5aef3b9523703eb7a5634df6951bd0f/src/Symfony/Component/Serializer/Mapping/Loader/AttributeLoader.php#L173

So in order to serialize stamps, they must respect some constraints.
This is documented here: https://symfonycasts.com/screencast/messenger/serializer-headers-options#shouldnt-we-always-use-the-symfony-serializer

> The reason is that the Symfony serializer requires your classes to follow a few rules in order to be serialized and unserialized correctly - like each property needs a setter method or a constructor argument where the name matches the property name. If your class doesn't follow those rules, you can end up with a property that is set on the original object, but suddenly becomes null when it's read from the transport. No fun.

Comment (VincentLanglet) [reply src/Symfony/Component/Messenger/Stamp/DeduplicateStamp.php]: I checked at the other stamps and all of them are either implementing `NonSendableStampInterface` or exposing correctly named getter for all the properties.

The DeduplicateStamp is the only one with an exception for onlyDeduplicateInQueue. 

The deprecation shouldn't be a big deal since no-one except the Middleware should call the `onlyDeduplicateInQueue` method.

Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Stamp/DeduplicateStamp.php]: Hum, won't this concern be fixed after https://github.com/symfony/symfony/pull/62772?

Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Stamp/DeduplicateStamp.php]: Self-answering: nope, but this still reminds us about the `enable_getter_setter_extraction` context option. Maybe that's the way to go?

Comment (VincentLanglet) [reply src/Symfony/Component/Messenger/Stamp/DeduplicateStamp.php]: Not sure how you want to pass enable_getter_setter_extraction ; I tried multiple way without effect.

If you look at the ObjectNormalizer, https://github.com/symfony/symfony/blob/e880e531a5aef3b9523703eb7a5634df6951bd0f/src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php#L77-L125, it only extract public method get/is/has/can and public property

As soon as I pass a classMetadataFactory with an attribute loader, I also encounter the exception because the method is not is/set/get/has/can https://github.com/symfony/symfony/blob/e880e531a5aef3b9523703eb7a5634df6951bd0f/src/Symfony/Component/Serializer/Mapping/Loader/AttributeLoader.php#L144

I'm far away to be expert with Serializer, so maybe you have some code suggestion (you can even try my branch, test is executable with `./phpunit src/Symfony/Component/Messenger/Tests/Transport/Serialization/SerializerTest.php --filter=testEncodedWithStampsIsDecodable`) but so far I really don't see the way to avoid the method renaming @nicolas-grekas ; is it really a big deal ?

Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Stamp/DeduplicateStamp.php]: OK. All those extraction rules are wild to me. Some parts accept only prefixed accessors, others are fine with same-name method/properties. I don't know the reasons, this is blurry to me...
What about a normalizer/denormalizer instead? That could help fix both the issues with Key and onlyDeduplicateInQueue, isn't it? For Key, I mean fix the issue on 7.3 without LockKeyNormalizer.

Comment (VincentLanglet) [reply src/Symfony/Component/Messenger/Stamp/DeduplicateStamp.php]: > All those extraction rules are wild to me. Some parts accept only prefixed accessors, others are fine with same-name method/properties. I don't know the reasons, this is blurry to me...

Honestly, to me too.

> What about a normalizer/denormalizer instead? That could help fix both the issues with Key and onlyDeduplicateInQueue, isn't it? For Key, I mean fix the issue on 7.3 without LockKeyNormalizer.

While I understand the idea (and the why), isn't it kinda too-specific/overcomplicated:
- The DeduplicateStamp will be the only one with a Normalizer, while all the over stamps are working great alone.
- People instantiating manually "custom" serializer (like it's done here: https://github.com/symfony/symfony/blob/e880e531a5aef3b9523703eb7a5634df6951bd0f/src/Symfony/Component/Messenger/Transport/Serialization/Serializer.php#L56) will need to add the Normalizer themself
- We will need to auto-register this normalizer and add it too the create method https://github.com/symfony/symfony/blob/e880e531a5aef3b9523703eb7a5634df6951bd0f/src/Symfony/Component/Messenger/Transport/Serialization/Serializer.php#L56
- I feel like the DeduplicateInQueue will re-implement the logic from the LockKeyNormalizer

I feel like we're searching for a complex solution to avoir renaming a method ; issue I would have avoid if I have thought about the Serializer when implementing the DeduplicateStamp.

But if it's ok to create a new Normalizer in 7.3, it would be better to backport the LockKeyNormalizer in 7.3 then

Comment (VincentLanglet) [reply src/Symfony/Component/Messenger/Stamp/DeduplicateStamp.php]: Friendly ping @nicolas-grekas, I'm really stuck with this serialization bug ; can we find a working solution satisfying you ?

Comment (VincentLanglet) [reply src/Symfony/Component/Messenger/Stamp/DeduplicateStamp.php]: I found a way to avoid renaming the method, but it requires to modify the ObjectNormalizer to add here
https://github.com/symfony/symfony/blob/5edcbd02d77c5456edf96e76e9bace5a58138046/src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php#L107
```
 elseif ($this->hasProperty($reflMethod, $name)) {
     $attributeName = $name;
}
```
This will allows to serialize public method which has the same name than a private property.

But it would means
- That now the serializer serialize more methods (which is maybe not a bad things, but I dunno who knows the serializer good enough to juge it)
- Either introducing this in 7.4 (as a bug fix ?), either doing it in 8.1 (as a feature) but having to introduce the getter in 7.4 and deprecating it in 8.1

Comment (VincentLanglet) [reply src/Symfony/Component/Messenger/Stamp/DeduplicateStamp.php]: https://github.com/symfony/symfony/pull/62838

**Comment by nicolas-grekas** [comment]
Rebase unlocked

**Comment by VincentLanglet** [comment]
> Rebase unlocked

Thanks ! PR is updated without the renaming/deprecation.

But seems like the 7.4 branch Ci already have a lot of failure
https://github.com/symfony/symfony/commits/7.4/

**Comment by nicolas-grekas** [comment]
And failures are related to the fix on Serializer. See https://github.com/symfony/symfony/pull/62971

**Comment by nicolas-grekas** [comment]
(now merged up)

**Comment by nicolas-grekas** [comment]
Thank you @VincentLanglet.
