### PR TITLE
[Security] Allow custom scheme to be used as redirection URIs

### LINKED ISSUE #50500: [Security] `DefaultAuthenticationSuccessHandler` crashes if the target URL is wrongly considered as a route name
### Symfony version(s) affected

≥ 5.4

### Description

Because `HttpUtils::generateUri` considers `$path` a route name if it does not start with `http` or `/`,  `DefaultAuthenticationSuccessHandler` will crash for any target URL whose scheme does not start with `http`.

### How to reproduce

Simplest way to reproduce is to create a login form configured with `always_use_default_target_path` and `default_target_path` as a URL whose scheme does not start with `http`, like `android-app://com.google.android.gm/` (see #50385).

### Possible Solution

I think `HttpUtils::generateUri` should consider any URL as one, whatever its scheme.

Then, maybe `DefaultAuthenticationSuccessHandler` could expose a mechanism to confirm whether to redirect to the referrer?

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Spomky**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #50500
| License       | MIT
| Doc PR        | not needed

ping @sdespont and @MatTheCat

This PR aims at fixing the redirection issue where only URLs starting with `http` are allowed.
With the modified behavior, it is now allowed to use any URL scheme. It will be possible to redirect to `android-app://com.google.android.gm/`.

~In addition, it prevents the redirection to the following URLs:~

* ~With path traversal e.g. `https://example.com/foo/../../.htpasswd`~
* ~With protocol-relative e.g. `//malicious.app/foo/bar`~

### CODE REVIEW

**Comment by Spomky** [comment]
The support for URNs could be removed. It looks like it is not part of the current best practices (see [RFC8252](https://datatracker.ietf.org/doc/html/rfc8252)); custom scheme like `android-app` is now prefered.

File: src/Symfony/Component/Security/Http/HttpUtils.php [hunk 1]
```diff
@@ -148,7 +148,11 @@ public function checkRequestPath(Request $request, string $path)
      */
     public function generateUri(Request $request, string $path)
     {
-        if (str_starts_with($path, 'http') || !$path) {
+        $parsedUrl = parse_url($path);
+        $uriScheme = $parsedUrl['scheme'] ?? null;
+        $uriHost = $parsedUrl['host'] ?? null;
+        $uriPath = $parsedUrl['path'] ?? '';
+        if (('urn' === $uriScheme && null === $uriHost && null !== $uriPath) || (null !== $uriScheme && null !== $uriHost)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Http/HttpUtils.php]:
```suggestion
        if (isset($url['scheme']) && (isset($url['host']) || ('urn' === $url['scheme'] && isset($url['path'])))) {
```

Comment (Spomky) [reply src/Symfony/Component/Security/Http/HttpUtils.php]: Many thanks!

File: src/Symfony/Component/Security/Http/HttpUtils.php [hunk 2]
```diff
@@ -148,7 +148,11 @@ public function checkRequestPath(Request $request, string $path)
      */
     public function generateUri(Request $request, string $path)
     {
-        if (str_starts_with($path, 'http') || !$path) {
+        $parsedUrl = parse_url($path);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Http/HttpUtils.php]:
```suggestion
        $url = parse_url($path);
```

+ remove the net lines :)

File: src/Symfony/Component/Security/Http/HttpUtils.php [hunk 3]
```diff
@@ -148,7 +148,11 @@ public function checkRequestPath(Request $request, string $path)
      */
     public function generateUri(Request $request, string $path)
     {
-        if (str_starts_with($path, 'http') || !$path) {
+        $url = parse_url($path);
+        $uriScheme = $parsedUrl['scheme'] ?? null;
+        $uriHost = $parsedUrl['host'] ?? null;
+        $uriPath = $parsedUrl['path'] ?? '';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Http/HttpUtils.php]:
```suggestion
```

**Review by nicolas-grekas — APPROVED** [review]
(don't miss syncing the PR description with latest changes)

File: src/Symfony/Component/Security/Http/HttpUtils.php [hunk 4]
```diff
@@ -148,7 +148,20 @@ public function checkRequestPath(Request $request, string $path)
...
+        $url = parse_url($path);
+
+        // Prevent path traversal (ex: https://example.com/../../file)
+        if (preg_match('#/\.\.?(/|$)#', $url['path'])) {
+            return $request->getUriForPath('/');
+        }
+
+        // Prevent protocol-relative redirection (ex: //example.com/file)
+        if (!isset($url['scheme']) && isset($url['host'], $url['path'])) {
+            return $request->getUriForPath('/');
```
Comment (stof) [inline src/Symfony/Component/Security/Http/HttpUtils.php]: this is not the same behavior than before your PR

**Review by chalasr — CHANGES_REQUESTED** [review]
See stof's review. Also keeping existing tests untouched makes the patch easier to review, which makes me much more confident to merge on security-related topics especially. Please avoid any refactoring if possible :)

**Comment by Spomky** [comment]
Hi @chalasr,

Many thanks for your comment. I restored the previous tests and keep the one I created. Let me know if you agree with the modifications.

Regarding the behavior of paths starting with `//`, the change is intentional. I took the opportunity of this PR to fix the comment `Protocol-relative redirection should not be supported for security reasons`. There is now reason for a developer to redirect to such path and could be considered as an open redirect in some situation.
I can revert the change and open another PR if you prefer. At some point, it should be addressed and it seems to be the perfect moment for me.

**Review by nicolas-grekas — APPROVED** [review]
I removed the part about supposedly security hardening, which are unproven to me and change the behavior.

**Comment by Spomky** [comment]
Agreed. Let's keep it simple and without any BC.

File: src/Symfony/Component/Security/Http/HttpUtils.php [hunk 5]
```diff
@@ -148,7 +148,10 @@ public function checkRequestPath(Request $request, string $path)
      */
     public function generateUri(Request $request, string $path)
     {
-        if (str_starts_with($path, 'http') || !$path) {
+        $url = parse_url($path);
+
+        // absolute URL
+        if ('' === $path || isset($url['scheme'], $url['host'])) {
```
Comment (stof) [inline src/Symfony/Component/Security/Http/HttpUtils.php:153]: `'' === $path` is not really an absolute URL. The comment is misleading.

Comment (nicolas-grekas) [reply src/Symfony/Component/Security/Http/HttpUtils.php:153]: comment removed

**Comment by nicolas-grekas** [comment]
Thank you @Spomky.
