### PR TITLE
[Form] Add missing TranslatableMessage support to choice_label option of ChoiceType

### LINKED ISSUE #40622: Choice label containing a TranslatableMessage will strip its parameters
**Symfony version(s) affected**: 5.2.*

**Description**
Using TranslatableMessage as choice label will result in its `__toString()` being used to display it, not its `trans()` representation

**How to reproduce**
Create a form with a ChoiceType using
```
                'choice_label' => function ($choice, $key, $value) {
                    return new TranslatableMessage('my_choice', ['%foo%' => $value, '%bar%' => $key], 'form');
                },
```
The rendered page will contain the translation of `my_choice`, yet without considering the parameters. Reason is that the TranslatableMessage will be casted to string before it can be translated.

**Possible Solution**
Remove the string typecast in vendor/symfony/form/ChoiceList/Factory/DefaultChoiceListFactory.php:180
```
            $label = false === $dynamicLabel ? false : (string) $dynamicLabel;
```
..or at least if the $dynamicLabel does not implement `Symfony\Contracts\Translation\TranslatableInterface`

**Additional context**
none

### PR DESCRIPTION
**Pull request by alexandre-daubois**
It leads to loss of information because it'll use `__toString` to cast, which is incompatible with newly added `TranslatableMessage`, for example.

| Q             | A
| ------------- | ---
| Branch?       | 5.2 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #40622 
| License       | MIT
| Doc PR        | _none_

So this one's a bit tricky in my mind. I didn't want to check if `$dynamicLabel instanceof TranslatableMessage`, because of course it doesn't belong to the same component.

Aside, it would sound so strange to me to add `|object` to `$label` here: https://github.com/symfony/symfony/blob/bb1e1e58aea5318e96d1c22cc8a91668ed7baaaa/src/Symfony/Component/Form/ChoiceList/View/ChoiceView.php#L40

But maybe that's the way to go? Requiring your help here. I'm fully open to your ideas, as we're loosing a big feature here by losing `TranslatableMessage` translation parameters.

If the passed object doesn't implement `__toString`, it'll lead to an exception during template rendering, as expected.

### CODE REVIEW

File: src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php [hunk 1]
```diff
@@ -177,7 +177,7 @@ private static function addChoiceView($choice, string $value, $label, array $key
             // If "choice_label" is set to false and "expanded" is true, the value false
             // should be passed on to the "label" option of the checkboxes/radio buttons
             $dynamicLabel = $label($choice, $key, $value);
-            $label = false === $dynamicLabel ? false : (string) $dynamicLabel;
+            $label = false === $dynamicLabel ?: (\is_object($dynamicLabel) ? $dynamicLabel : (string) $dynamicLabel);
```
Comment (yceruto) [inline src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php]: Nested ternary operator should not be used (maintainability issues)

Comment (yceruto) [inline src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php]:
```suggestion
            if (false === $dynamicLabel) {
                $label = false;
            } elseif ($dynamicLabel instanceof TranslatableMessage) {
                $label = $dynamicLabel;
            } else {
                $label = (string) $dynamicLabel;
            }
```

**Review by yceruto — CHANGES_REQUESTED** [review]
Adding a specific check against TranslatableMessage wouldn't a problem from my point of view and it would be better than allowing non-stringable objects from here.

**Comment by yceruto** [comment]
https://github.com/symfony/symfony/blob/bb1e1e58aea5318e96d1c22cc8a91668ed7baaaa/src/Symfony/Component/Form/ChoiceList/View/ChoiceView.php#L40

and yes, I would update the docblock to add TranslatableMessage too.

**Comment by alexandre-daubois** [comment]
Thank you so much @yceruto for your advice. I updated the code thanks to your suggestions and edited the PR title as well.

**Review by nicolas-grekas — APPROVED** [review]
(I fixed deps=low tests by skipping the test case there)

**Comment by nicolas-grekas** [comment]
Thank you @alexandre-daubois.
