### PR TITLE
[Doctrine][Messenger] Oracle sequences are suffixed with `_seq`

### LINKED ISSUE #58504: [Doctrine][Messenger] Fix Identity columns not supported by Oracle driver
### Symfony version(s) affected

6.4.12

### Description

**Error Message**
IdentityColumnsNotSupported > DriverException > TransportException : An exception occurred in the driver: The driver does not support identity columns.

**Context**
Usage of async symfony/messenger with doctrine as transport

**Explanation**

When dealing with an Oracle database, the dispatched message is well inserted into the database but an exception is encountered when trying to get the last inserted id. That exception lead to a **rollback** and therefore a failing process of queing the messages.
IDs are generated with sequence instead of identity column as you have it with MySQL database for exemple.
A specific treatment is needed as done for PostgreSQL database

### How to reproduce

**Environment**
- PHP 8.3
- Symfony 6.4.12
- OS : Windows
- DB : Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0
- Extensions: oci_8_19, ...

**How to reproduce**
1. Set up a project

- Create a symfony web project
- Create a Controller/route to use as test

2. Check symfony/messenger works well as sync

- Install symfony/messenger if not installed
- Create a message and it's handler and test the dispatch and execution of the hander

3. Test symfony/messenger works well as **async**
- Install symfony/doctrine-messenger
- Set the process as async

When testing the async process, the error should appear as the message can't be recorded into the database

[Stack-Traces.txt](https://github.com/user-attachments/files/17299722/stack-traces.txt)

### Possible Solution

Target the OraclePlatform to get the last inserted id as needed for that database :

```
...
    elseif ($this->driverConnection->getDatabasePlatform() instanceof OraclePlatform) {
          $sequenceName = strtoupper($this->configuration['table_name'].'_seq');

          $this->driverConnection->executeStatement($sql, $parameters, $types);
                
          $result = $this->driverConnection->fetchOne('select last_number from user_sequences where sequence_name = \''.$sequenceName.'\'');

          $id = (int) $result;

          if (!$id) {
              throw new TransportException('no id was found in Oracle for sequence: '.$sequenceName);
          }
    }
...
```

_Important_ :
- On GitHub, for the [6.4.x](https://github.com/symfony/doctrine-messenger/blob/6.4/Transport/Connection.php) version, a solution is implemented but doesn't work and produce an error (ORA-02289). Should be adapted as shown above
  - Maybe it is in beta as the deployed version on my machine doesn't have that elseif block !
- Fix should also be ported to symfony/doctrine-messenger 7.1.x

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by devloop42**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58504
| License       | MIT

Generated sequences, by doctrine or in this case by the auto_setup of messenger, are suffixed with `_seq`.

### CODE REVIEW

File: src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php [hunk 1]
```diff
@@ -542,9 +542,9 @@ private function addTableToSchema(Schema $schema): void
 
         // We need to create a sequence for Oracle and set the id column to get the correct nextval
         if ($this->driverConnection->getDatabasePlatform() instanceof OraclePlatform) {
-            $idColumn->setDefault('seq_'.$this->configuration['table_name'].'.nextval');
+            $idColumn->setDefault($this->configuration['table_name'].'_seq'.'.nextval');
```
Comment (alexandre-daubois) [inline src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php]:
```suggestion
            $idColumn->setDefault($this->configuration['table_name'].'_seq.nextval');
```

**Review by alexandre-daubois — COMMENTED** [review]
Could this be covered by tests to avoid regressions?

File: src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php (hunk 1 above)
Comment (devloop42) [reply src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php]: @alexandre-daubois : I updated that portion of code for consistency.
@rjd22 : Is this if block really needed as messenger in it's auto config process already create a sequence and trigger in case of id not specified ?

Comment (rjd22) [reply src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php]: Yes, for Oracle installations the default block is needed. Else the field won't use the sequence on some installations.

**Comment by rjd22** [comment]
@xabbuh Since you looked at mine can you take a look at this one? It looks good to me. If we merge this before the next release we avoid a breaking change.

**Review by xabbuh — APPROVED** [review]
works for me

**Review by alexandre-daubois — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @devloop42.
