### PR TITLE
[DependencyInjection] Fix `TypeError` when using a custom container base class with typed `$parameterBag`

### LINKED ISSUE #63495: Cannot assign null to property Container::$parameterBag of type ParameterBagInterface in compiled container
### Symfony version(s) affected

7.4.x

### Description

Since Symfony 7, I am no longer able to use an extended `Symfony\Component\DependencyInjection\Container` as the container.
After the container compilation, the following TypeError is thrown:
```
Fatal error: Uncaught TypeError: Cannot assign null to property Symfony\Component\DependencyInjection\Container::$parameterBag of type Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface in /opt/project/var/cache/dev/ContainerDCrHDxr/MyApp_KernelDevDebugContainer.php:26
Stack trace:
#0 /opt/project/var/cache/dev/MyApp_KernelDevDebugContainer.php(17): ContainerDCrHDxr\MyApp_KernelDevDebugContainer->__construct(Array, '/opt/project/va...')
#1 /opt/project/vendor/symfony/http-kernel/Kernel.php(533): require('/opt/project/va...')
#2 /opt/project/vendor/symfony/http-kernel/Kernel.php(762): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#3 /opt/project/vendor/symfony/http-kernel/Kernel.php(122): Symfony\Component\HttpKernel\Kernel->preBoot()
#4 /opt/project/console(12): Symfony\Component\HttpKernel\Kernel->boot()
#5 {main}
  thrown in /opt/project/var/cache/dev/ContainerDCrHDxr/MyApp_KernelDevDebugContainer.php on line 26
```

This happens during container initialization, before any userland code is executed.

The error might come from the `Symfony\Component\DependencyInjection\Dumper\PhpDumper` : the `$parameterBag` property is explicitly set to `null` [here](https://github.com/symfony/dependency-injection/blob/7.4/Dumper/PhpDumper.php#L1291), but in `Symfony\Component\DependencyInjection\Container` ([here](https://github.com/symfony/dependency-injection/blob/7.4/Container.php#L53)) it is not declared as nullable.

The strict type declaration on `$parameterBag` was introduced in [this commit](https://github.com/symfony/dependency-injection/commit/c81d9be5bd35d0946d50db9097e0ec6b1f3fa326)

In my case, I only extend the base Container class, keep the same constructor signature, and forward the parameter bag to the parent constructor.

### How to reproduce

Extend the base Container class
```php
<?php

namespace MyApp;

use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

class MyContainer extends \Symfony\Component\DependencyInjection\Container
{
    public function __construct(?ParameterBagInterface $parameterBag = null)
    {
        parent::__construct($parameterBag);

        // Some custom initialization here
    }

// [...]
}
```

Configure the kernel to use the custom container class
```php
<?php

namespace MyApp;

class Kernel extends \Symfony\Component\HttpKernel\Kernel
{
// [...]

    protected function getContainerBaseClass(): string
    {
        return MyContainer::class;
    }

// [...]
}
```

Boot the application
```php
<?php

use MyApp\Kernel;

require_once __DIR__ . '/vendor/autoload.php';

$kernel = new Kernel('dev', true);
$kernel->boot();
```

The container is compiled, then the error is thrown.

### Possible Solution

_No response_

### Additional Context

Here is the compiled container constructor
```php
// [...]
class MyApp_KernelDevDebugContainer extends \MyApp\Container
{
    protected $targetDir;
    protected $parameters = [];

    public function __construct(private array $buildParameters = [], protected string $containerDir = __DIR__)
    {
        $this->targetDir = \dirname($containerDir);
        parent::__construct();
        $this->parameterBag = null;

        $this->parameters = $this->getDefaultParameters();

        $this->services = $this->privates = [];

        $this->aliases = [];
    }
// [...]
}
```

Here is the `composer.json` I used
```json
{
    "require": {
        "php": "^8.5",
        "ext-ctype": "*",
        "symfony/http-kernel": "^7.4",
        "symfony/config": "^7.4",
        "symfony/dependency-injection": "^7.4"
    },
    "autoload": {
        "psr-4": {
            "MyApp\\": "src/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*"
    }
}
```

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63495
| License       | MIT

When using `getContainerBaseClass()` to provide a custom container class that declares `$parameterBag` with a type (e.g. `protected ParameterBagInterface $parameterBag`), booting the application throws TypeError: Cannot assign null to property.

`PhpDumper` generates compiled container constructors that call `parent::__construct()` followed by `$this->parameterBag = null`. The intent is to signal "not yet initialized" so that the generated `getParameterBag()` (which checks `!isset($this->parameterBag)`) lazily builds a `FrozenParameterBag`. However, assigning `null` to a non-nullable typed property is a `TypeError`.

This PR replaces the `null` assignment with `unset()`, achieving the same lazy-init behaviour without violating any type constraint.

### CODE REVIEW

**Comment by stof** [comment]
Should this target 6.4 or 7.4 ? The property is not typed in 6.4.

**Comment by nicolas-grekas** [comment]
Works either way, no strong opinion on this.

**Review by stof — APPROVED** [review]

**Comment by stof** [comment]
> The intent is to signal "not yet initialized" so that the generated `getParameterBag()` (which checks `!isset($this->parameterBag)`) lazily builds a `FrozenParameterBag`.

I see no such generated method doing the check in the fixtures edited in this PR. Are you sure this fix works ?

File: src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php [hunk 1]
```diff
@@ -179,6 +179,24 @@ public function testDumpCustomContainerClassWithOptionalArgumentLessConstructor(
...
+        $code = $dumper->dump(['base_class' => 'ContainerWithTypedParameterBag', 'class' => 'CompiledContainerWithTypedParameterBag', 'namespace' => 'Symfony\Component\DependencyInjection\Tests\Fixtures\Container']);
+
+        // The compiled container must not assign null to a potentially typed $parameterBag property
+        $this->assertStringNotContainsString('$this->parameterBag = null', $code);
+        $this->assertStringContainsString('unset($this->parameterBag)', $code);
+
+        // Verify the compiled container can actually be instantiated without TypeError
+        eval('?>'.$code);
+        $compiledContainer = new \Symfony\Component\DependencyInjection\Tests\Fixtures\Container\CompiledContainerWithTypedParameterBag();
+        $this->assertTrue($compiledContainer->isCompiled());
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php:198]: I suggest also asserting that `$compiledContainer->getParameterBag()` works fine.

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php:198]: Test added
