### PR TITLE
[Finder] Fix `Finder::append()` breaking generic typing contract

### LINKED ISSUE #62734: [Finder] getIterator() type issue
### Symfony version(s) affected

6.4.24, 7.3.5, thus probably all ?

### Description

When working with Finder, I need to be explicitly sure about type it will provide.

When looking at docs, I see that:
- [getIterator()](https://github.com/symfony/symfony/blob/8.1/src/Symfony/Component/Finder/Finder.php#L660) returns `\Iterator<non-empty-string, SplFileInfo>`
- Finder itself [implements](https://github.com/symfony/symfony/blob/8.1/src/Symfony/Component/Finder/Finder.php#L40) `\IteratorAggregate<non-empty-string, SplFileInfo>`

Note that this is non-rooted SplFileInfo - which is `Symfony\Component\Finder\SplFileInfo` in this context. There is no explicit import, as both files are in very same Finder's namespace.

Then, I call the item from the iterator and I got surprised to get `\SplFileInfo` instead of `\Symfony\Component\Finder\SplFileInfo`.

Can you clarify what is expected behaviour?
Is it issue somewhere in code, and one shall always get `\Symfony\Component\Finder\SplFileInfo` ?
Or it's issue in docs, and thus documented type shall be `\SplFileInfo` ?

### How to reproduce

```php
<?php

include 'vendor/autoload.php';

/////

$finder = \Symfony\Component\Finder\Finder::create()
    ->in(__DIR__)
    ->append([__FILE__]);

$files = iterator_to_array($finder->getIterator());
var_dump(get_class(array_pop($files))); // \Symfony\Component\Finder\SplFileInfo

/////

$finder = \Symfony\Component\Finder\Finder::create()
    ->append([__FILE__]);

$files = iterator_to_array($finder->getIterator());
var_dump(get_class(array_pop($files))); // \SplFileInfo , !!!

```

### Possible Solution

depends on intention how code should behave

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jack-worman**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62734 
| License       | MIT

Updated Finder::append() to ensure the iterable items are SplFileInfo (symfony's version).

### CODE REVIEW

File: src/Symfony/Component/Finder/Finder.php [hunk 1]
```diff
@@ -701,26 +702,32 @@ public function getIterator(): \Iterator
...
-        if ($iterator instanceof \IteratorAggregate) {
-            $this->iterators[] = $iterator->getIterator();
-        } elseif ($iterator instanceof \Iterator) {
-            $this->iterators[] = $iterator;
-        } elseif (is_iterable($iterator)) {
-            $it = new \ArrayIterator();
-            foreach ($iterator as $file) {
-                $file = $file instanceof \SplFileInfo ? $file : new \SplFileInfo($file);
+        $it = new \ArrayIterator();
+        foreach ($iterator as $file) {
```
Comment (stof) [inline src/Symfony/Component/Finder/Finder.php]: should we optimize the case where the argument being appended is a Finder, to avoid iterating over it eagerly ?

Comment (jack-worman) [reply src/Symfony/Component/Finder/Finder.php]: Done

File: src/Symfony/Component/Finder/Finder.php [hunk 2]
```diff
@@ -701,25 +702,36 @@ public function getIterator(): \Iterator
...
-     * @return $this
+     * @param iterable<SplFileInfo|\SplFileInfo|string> $iterator
      *
-     * @throws \InvalidArgumentException when the given argument is not iterable
+     * @return $this
      */
     public function append(iterable $iterator): static
     {
-        if ($iterator instanceof \IteratorAggregate) {
+        if ($iterator instanceof static) {
```
Comment (stof) [inline src/Symfony/Component/Finder/Finder.php]: should be `instanceof self` instead. When using a child class of the finder, we can still optimize this for any Finder, as we know it will already iterate over the appropriate SplFileInfo.

Comment (jack-worman) [reply src/Symfony/Component/Finder/Finder.php]: true!

File: src/Symfony/Component/Finder/Finder.php [hunk 3]
```diff
@@ -701,25 +702,36 @@ public function getIterator(): \Iterator
...
             foreach ($iterator as $file) {
-                $file = $file instanceof \SplFileInfo ? $file : new \SplFileInfo($file);
-                $it[$file->getPathname()] = $file;
+                if ($file instanceof SplFileInfo) {
+                    $it[$file->getPathname()] = $file;
+                } elseif ($file instanceof \SplFileInfo) {
+                    $it[$file->getPathname()] = new SplFileInfo(
+                        $file->getPathname(),
+                        $file->getPath(),
+                        $file->getPathname(),
```
Comment (keradus) [inline src/Symfony/Component/Finder/Finder.php]: I do not believe this produces proper results.
While the Symfony\Finder\SplFileInfo interface would now be respected, produced content is different than when using only `->in(...)`.

I run following script in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer repo:


```php
<?php

declare(strict_types=1);

use Symfony\Component\Finder\Finder;

include 'vendor/autoload.php';

$FILE = './src/Linter/LinterInterface.php';
$f = new \SplFileInfo($FILE);

var_dump([ # 1
    "---" => "RAW_FILE",
    "getPathname" => $f->getPathname(),
    "getPath" => $f->getPath(),
]);

var_dump("/////");

$finder = Finder::create()
    ->in(__DIR__.'/src/')
    // ->append([$FILE]) << no, let it be found by `->in(...)`
;

$files = iterator_to_array($finder->getIterator());
$f = $files[realpath($FILE)];

var_dump([ # 2
    "::class" => get_class($f), // \Symfony\Component\Finder\SplFileInfo
    "getPathname" => $f->getPathname(),
    "getRelativePath" => $f->getRelativePath(),
    "getRelativePathname" => $f->getRelativePathname(),
]);

var_dump("/////");

$finder = Finder::create()
    ->in(__DIR__.'/src/')
    ->append([$FILE])
;

$files = iterator_to_array($finder->getIterator());
$f = $files[$FILE];

var_dump([ # 3
    "::class" => get_class($f), // \SplFileInfo
    "getPathname" => $f->getPathname(),
    "getRelativePath (mocked)" => $f->getPath(),
    "getRelativePathname (mocked)" => $f->getPathname(),
]);

```


as you can see, var_dump#3 is failing to recognise `relativePath` in context of `->in(__DIR__.'/src/'), while var_dump#2 is not having this problem
```sh
keradus@machine PHP-CS-Fixer_3 % php -f x.php
array(3) {
  ["---"]=>
  string(8) "RAW_FILE"
  ["getPathname"]=>
  string(32) "./src/Linter/LinterInterface.php"
  ["getPath"]=>
  string(12) "./src/Linter"
}
string(5) "/////"
array(4) {
  ["::class"]=>
  string(36) "Symfony\Component\Finder\SplFileInfo"
  ["getPathname"]=>
  string(76) "/Users/keradus/github/PHP-CS-Fixer_3/src/Linter/LinterInterface.php"
  ["getRelativePath"]=>
  string(6) "Linter"
  ["getRelativePathname"]=>
  string(26) "Linter/LinterInterface.php"
}
string(5) "/////"
array(4) {
  ["::class"]=>
  string(11) "SplFileInfo"
  ["getPathname"]=>
  string(32) "./src/Linter/LinterInterface.php"
  ["getRelativePath (mocked)"]=>
  string(12) "./src/Linter"
  ["getRelativePathname (mocked)"]=>
  string(32) "./src/Linter/LinterInterface.php"
}

```

Comment (jack-worman) [reply src/Symfony/Component/Finder/Finder.php]: When given just a string filepath or \SplFileInfo without any context, we cannot discern a relative path without guess work, that may not be intuitive to users.

There are problems with using `->in()` to determine the relative path:
1. `->in()` does not have to be called (only `->append()` used)
2. `->in()` can be passed multiple directories, so then we would have to arbitrarily choose which one to use for the relative path

**Comment by OskarStark** [comment]
Please add a meaningful PR title, thanks

File: src/Symfony/Component/Finder/Finder.php (hunk 3 above)
Comment (keradus) [reply src/Symfony/Component/Finder/Finder.php]: > `->in()` can be passed multiple directories, so then we would have to arbitrarily choose which one to use for the relative path

I would recommend mimicking current behaviour

```
$finder = Finder::create()
    ->in(__DIR__.'/src/')
    ->in(__DIR__.'/tests/')


$files = iterator_to_array($finder->getIterator());
$f = $files[realpath($FILE)];

$f->getRelativePath() // Linter/LinterInterface.php
```

Comment (keradus) [reply src/Symfony/Component/Finder/Finder.php]: > `->in()` does not have to be called (only ->append() used)

agree this is the tricky part.
yet, if behaviour is different, in case we cannot unify it - it should be at least documented.

Comment (jack-worman) [reply src/Symfony/Component/Finder/Finder.php]: I think how it currently is makes the most sense, but I made a test that snapshots the current behavior. Please add comments telling me what the expected results should be.

**Comment by jack-worman** [comment]
The `DateRangeFilterIteratorTest::testAccept()` failure seems unrelated. It fails for me even when I switch to the master 6.4 branch. Any ideas what is going on?

File: src/Symfony/Component/Finder/Finder.php (hunk 3 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Finder/Finder.php]: For this relative path aspect, it'd be best to preserve the existing behavior.
If you have a test case that fails after your patch, please attach it to the PR.
And let's figure out a fix to make it pass.

For the date-related failure, can you please add this?

```diff
--- a/src/Symfony/Component/Finder/Tests/Iterator/RealIteratorTestCase.php
+++ b/src/Symfony/Component/Finder/Tests/Iterator/RealIteratorTestCase.php
@@ -72,8 +72,9 @@ abstract class RealIteratorTestCase extends IteratorTestCase
         file_put_contents(self::toAbsolute('test.php'), str_repeat(' ', 800));
         file_put_contents(self::toAbsolute('test.py'), str_repeat(' ', 2000));

-        touch(self::toAbsolute('foo/bar.tmp'), strtotime('2005-10-15'));
-        touch(self::toAbsolute('test.php'), strtotime('2005-10-15'));
+        $oneYearAgo = strtotime('-1 year');
+        touch(self::toAbsolute('foo/bar.tmp'), $oneYearAgo);
+        touch(self::toAbsolute('test.php'), $oneYearAgo);
```

File: src/Symfony/Component/Finder/Tests/FinderTest.php [hunk 4]
```diff
@@ -1296,6 +1297,65 @@ public function testAppendWithAnArray()
...
+    {
+        $finder1 = $this->buildFinder();
+        $finder1->files()->in(self::$tmpDir.\DIRECTORY_SEPARATOR.'foo');
+
+        $finder2 = $this->buildFinder();
+        $finder2->directories()->in(self::$tmpDir);
+
+        $finder1->append($finder2);
+        $finder1->append($this->toAbsolute(['foo']));
+        $finder1->append(array_map(fn (string $item): \SplFileInfo => new \SplFileInfo($item), $this->toAbsolute(['toto'])));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Finder/Tests/FinderTest.php]:
```suggestion
        $finder1->append(array_map(static fn ($item) => new \SplFileInfo($item), $this->toAbsolute(['toto'])));
```

File: src/Symfony/Component/Finder/Tests/FinderTest.php [hunk 5]
```diff
@@ -1296,6 +1297,65 @@ public function testAppendWithAnArray()
...
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Finder/Tests/FinderTest.php]:
```suggestion
        $finder1->append(array_map(static fn ($item) => new \SplFileInfo($item), $this->toAbsolute(['toto'])));
```

File: src/Symfony/Component/Finder/Tests/FinderTest.php [hunk 6]
```diff
@@ -1296,6 +1297,65 @@ public function testAppendWithAnArray()
...
+                self::$tmpDir . '/foo/bar.tmp' => 'bar.tmp',
+                // $finder2's ->in()
+                self::$tmpDir . '/qux' => 'qux',
+                // new \SplFileInfo('toto')
+                self::$tmpDir . '/toto' => self::$tmpDir . '/toto',
+                // 'foo'
+                self::$tmpDir . '/foo' => self::$tmpDir . '/foo',
+            ],
+            array_map(
+                fn (SplFileInfo $item) => $item->getRelativePathname(),
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Finder/Tests/FinderTest.php]:
```suggestion
                self::$tmpDir.'/foo/bar.tmp' => 'bar.tmp',
                // $finder2's ->in()
                self::$tmpDir.'/qux' => 'qux',
                // new \SplFileInfo('toto')
                self::$tmpDir.'/toto' => self::$tmpDir.'/toto',
                // 'foo'
                self::$tmpDir.'/foo' => self::$tmpDir.'/foo',
            ],
            array_map(
                static fn ($item) => $item->getRelativePathname(),
```

File: src/Symfony/Component/Finder/Tests/FinderTest.php [hunk 7]
```diff
@@ -1296,6 +1297,65 @@ public function testAppendWithAnArray()
...
+        );
+
+        $finder3 = $this->buildFinder();
+        $finder3->append($this->toAbsolute(['foo']));
+        $this->assertSame(
+            [
+                self::$tmpDir . '/foo' =>  self::$tmpDir . '/foo'
+            ],
+            array_map(
+                fn (SplFileInfo $item) => $item->getRelativePathname(),
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Finder/Tests/FinderTest.php]:
```suggestion
                self::$tmpDir.'/foo' =>  self::$tmpDir.'/foo'
            ],
            array_map(
                static fn ($item) => $item->getRelativePathname(),
```

**Review by nicolas-grekas — COMMENTED** [review]
Ah, I'm now seeing that testRelativePathOfAppendedItems is your failing test case 👀

File: src/Symfony/Component/Finder/Tests/FinderTest.php (hunk 5 above)
Comment (keradus) [reply src/Symfony/Component/Finder/Tests/FinderTest.php]: @nicolas-grekas , maybe let's formalise this?
https://github.com/symfony/symfony/pull/62783

**Comment by nicolas-grekas** [comment]
I spent quite some time on this PR trying to help, here is the patch I currently have (on top of yours). Let me know what you think of the result, please borrow it of course.

About the test case for relative paths, we should look for another one if we want to cover what @keradus raised: the test should pass on 6.4, and should fail with an improper fix. At the moment, the test fails, but it doesn't work on 6.4, which means we cannot consider it being a regression test.

<details>

<summary>My patch</summary>

```diff
diff --git a/src/Symfony/Component/Finder/Finder.php b/src/Symfony/Component/Finder/Finder.php
index 58a520851e2..f1558eeb5df 100644
--- a/src/Symfony/Component/Finder/Finder.php
+++ b/src/Symfony/Component/Finder/Finder.php
@@ -59,7 +59,6 @@ class Finder implements \IteratorAggregate, \Countable
     private int $ignore = 0;
     private array $dirs = [];
     private array $dates = [];
-    /** @var list<\Iterator<string, SplFileInfo>> */
     private array $iterators = [];
     private array $contains = [];
     private array $notContains = [];
@@ -667,27 +666,39 @@ class Finder implements \IteratorAggregate, \Countable
      */
     public function getIterator(): \Iterator
     {
-        if (0 === \count($this->dirs) && 0 === \count($this->iterators)) {
+        if (!$this->dirs && !$this->iterators) {
             throw new \LogicException('You must call one of in() or append() methods before iterating over a Finder.');
         }
 
-        if (1 === \count($this->dirs) && 0 === \count($this->iterators)) {
+        if (1 === \count($this->dirs) && !$this->iterators) {
             $iterator = $this->searchInDirectory($this->dirs[0]);
-
-            if ($this->sort || $this->reverseSorting) {
-                $iterator = (new Iterator\SortableIterator($iterator, $this->sort, $this->reverseSorting))->getIterator();
+        } else {
+            $iterator = new \AppendIterator();
+            foreach ($this->dirs as $dir) {
+                $iterator->append(new \IteratorIterator(new LazyIterator(fn () => $this->searchInDirectory($dir))));
             }
 
-            return $iterator;
-        }
-
-        $iterator = new \AppendIterator();
-        foreach ($this->dirs as $dir) {
-            $iterator->append(new \IteratorIterator(new LazyIterator(fn () => $this->searchInDirectory($dir))));
-        }
-
-        foreach ($this->iterators as $it) {
-            $iterator->append($it);
+            $yielded = [];
+
+            foreach ($this->iterators as $it) {
+                $iterator->append((static function () use ($it, &$yielded) {
+                    foreach ($it as $file) {
+                        if (!$file instanceof \SplFileInfo) {
+                            $file = new \SplFileInfo($file);
+                        }
+                        if (isset($yielded[$key = $file->getPathname()])) {
+                            continue;
+                        }
+                        if (!$file instanceof SplFileInfo) {
+                            $file = new SplFileInfo($key, $file->getPath(), $key);
+                        } else {
+                            $yielded[$key] = true;
+                        }
+
+                        yield $key => $file;
+                    }
+                })());
+            }
         }
 
         if ($this->sort || $this->reverseSorting) {
@@ -708,31 +719,7 @@ class Finder implements \IteratorAggregate, \Countable
      */
     public function append(iterable $iterator): static
     {
-        if ($iterator instanceof self) {
-            $this->iterators[] = $iterator->getIterator();
-        } else {
-            /** @var \ArrayIterator<string, SplFileInfo> $it */
-            $it = new \ArrayIterator();
-            foreach ($iterator as $file) {
-                if ($file instanceof SplFileInfo) {
-                    $it[$file->getPathname()] = $file;
-                } elseif ($file instanceof \SplFileInfo) {
-                    $it[$file->getPathname()] = new SplFileInfo(
-                        $file->getPathname(),
-                        $file->getPath(),
-                        $file->getPathname(),
-                    );
-                } else {
-                    $file = new \SplFileInfo($file);
-                    $it[$file->getPathname()] = new SplFileInfo(
-                        $file->getPathname(),
-                        $file->getPath(),
-                        $file->getPathname(),
-                    );
-                }
-            }
-            $this->iterators[] = $it;
-        }
+        $this->iterators[] = $iterator;
 
         return $this;
     }
diff --git a/src/Symfony/Component/Finder/Tests/Iterator/RealIteratorTestCase.php b/src/Symfony/Component/Finder/Tests/Iterator/RealIteratorTestCase.php
index 943c9ad0b38..dc9414a750d 100644
--- a/src/Symfony/Component/Finder/Tests/Iterator/RealIteratorTestCase.php
+++ b/src/Symfony/Component/Finder/Tests/Iterator/RealIteratorTestCase.php
@@ -72,8 +72,9 @@ abstract class RealIteratorTestCase extends IteratorTestCase
         file_put_contents(self::toAbsolute('test.php'), str_repeat(' ', 800));
         file_put_contents(self::toAbsolute('test.py'), str_repeat(' ', 2000));
 
-        touch(self::toAbsolute('foo/bar.tmp'), strtotime('2005-10-15'));
-        touch(self::toAbsolute('test.php'), strtotime('2005-10-15'));
+        $oneYearAgo = strtotime('-1 year');
+        touch(self::toAbsolute('foo/bar.tmp'), $oneYearAgo);
+        touch(self::toAbsolute('test.php'), $oneYearAgo);
 
         if (FinderTest::class === static::class) {
             $fs = new Filesystem();
```

</details>

**Comment by jack-worman** [comment]
> About the test case for relative paths, we should look for another one if we want to cover what @keradus raised: the test should pass on 6.4, and should fail with an improper fix. At the moment, the test fails, but it doesn't work on 6.4, which means we cannot consider it being a regression test.

This test case is not a regression test. The main 6.4 branch does not have a concept of relative paths because the types are not the `Symfony\Component\Finder\SplFileInfo`. The actual regression test is `testAppendStandardizesItemsToBeSymfonySplFileInfo()`.

`testRelativePathOfAppendedItems()` is adding a snapshot of what the "new" behavior should be for relative paths. I have updated that test to show the relative path behavior more clearly.

File: src/Symfony/Component/Finder/Finder.php (hunk 3 above)
Comment (jack-worman) [reply src/Symfony/Component/Finder/Finder.php]: > For this relative path aspect, it'd be best to preserve the existing behavior.

There is no current behavior though. There was no concept of a relative path because it wasn't using `Symfony\Component\Finder\SplFileInfo`

> For the date-related failure, can you please add this?
> 
> ```diff
> --- a/src/Symfony/Component/Finder/Tests/Iterator/RealIteratorTestCase.php
> +++ b/src/Symfony/Component/Finder/Tests/Iterator/RealIteratorTestCase.php
> @@ -72,8 +72,9 @@ abstract class RealIteratorTestCase extends IteratorTestCase
>          file_put_contents(self::toAbsolute('test.php'), str_repeat(' ', 800));
>          file_put_contents(self::toAbsolute('test.py'), str_repeat(' ', 2000));
> 
> -        touch(self::toAbsolute('foo/bar.tmp'), strtotime('2005-10-15'));
> -        touch(self::toAbsolute('test.php'), strtotime('2005-10-15'));
> +        $oneYearAgo = strtotime('-1 year');
> +        touch(self::toAbsolute('foo/bar.tmp'), $oneYearAgo);
> +        touch(self::toAbsolute('test.php'), $oneYearAgo);
> ```

The test is still failing after this patch.

**Review by nicolas-grekas — APPROVED** [review]
That's the way to go to me.
The concept of relative path already doesn't make sense once `->append()` is used, since we then don't know which base path is in use to resolve the relative path.

**Comment by nicolas-grekas** [comment]
Thank you @jack-worman.
