### PR TITLE
[Intl] Optionally allow Kosovo as a component region

### LINKED ISSUE #32482: BIC validation for Kosovo bank accounts
I have noticed a possible issue with the BIC validation of bank accounts from Kosovo. Kosovo is not included in the standard ISO country list and it doesn't enforce the use of IBAN bank accounts. Yet if you use the BIC validator on a correct Kosovo BIC code the validation fails. It checks the country code and since Kosovo is not in the list of ISO countries the validation fails.

But if you validate the same bank account on any online validator tool, their validation works fine.

So I was wondering if there were any plans on fixing this issue. If not I will write a work around for this issue.

### LINKED ISSUE #40020: [Intl] Missing Kosovo (XK) country name
**Symfony version(s) affected**: 4.4.17 and 5.5.2 for sure but I think also other versions

**Description**  

When trying to get Kosovo (XK) country name the following fatal error occurs:

```
PHP Fatal error:  Uncaught Symfony\Component\Intl\Exception\ResourceBundleNotFoundException: The resource bundle "/private/tmp/test/vendor/symfony/intl/Resources/data/regions/root.json" does not exist. in /private/tmp/test/vendor/symfony/intl/Data/Bundle/Reader/JsonBundleReader.php:39
Stack trace:
#0 /private/tmp/test/vendor/symfony/intl/Data/Bundle/Reader/BufferedBundleReader.php(45): Symfony\Component\Intl\Data\Bundle\Reader\JsonBundleReader->read('/private/tmp/te...', 'root')
#1 /private/tmp/test/vendor/symfony/intl/Data/Bundle/Reader/BundleEntryReader.php(88): Symfony\Component\Intl\Data\Bundle\Reader\BufferedBundleReader->read('/private/tmp/te...', 'root')
#2 /private/tmp/test/vendor/symfony/intl/ResourceBundle.php(58): Symfony\Component\Intl\Data\Bundle\Reader\BundleEntryReader->readEntry('/private/tmp/te...', 'en', Array, true)
#3 /private/tmp/test/vendor/symfony/intl/Countries.php(94): Symfony\Component\Intl\ResourceBundle::readEntry(Array, NULL)
#4 /private/tmp/test/test.php(9): Symfony\Component\Intl\Countries::getNa in /private/tmp/test/vendor/symfony/intl/Data/Bundle/Reader/BundleEntryReader.php on line 175
```

**How to reproduce**  

Execute the following script after a `composer require symony/intl`:

```php
<?php

require('vendor/autoload.php');

use Symfony\Component\Intl\Countries;

\Locale::setDefault('en');

var_dump(Countries::getName('XK'));
```

### LINKED ISSUE #54711: Intl has Kosovo in DENYLIST
### Symfony version(s) affected

*

### Description

Intl component has Kosovo in DENYLIST. Why is that?  We rely on this component to populate country selection but we need Kosovo to be also included

### How to reproduce

Just call: `Countries::getNames()` and see that Kosovo is not in the result

### Possible Solution

remove Kosovo from DENYLIST: https://github.com/symfony/intl/blob/510a40cbf59244af027905cdb838eb7b57447752/Data/Generator/RegionDataGenerator.php#L59

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by llupa**
| Q             | A
| ------------- | ---
| Branch?       | 7.4 
| Bug fix?      | yes
| New feature?  | yes
| Deprecations? | no 
| Issues        | Fix #32482, Fix #40020, Fix #54711
| License       | MIT

### CODE REVIEW

**Comment by llupa** [comment]
Edit:

In the past I attempted at one solution in this PR: https://github.com/symfony/symfony/pull/59693 where I got great feedback. 

In the meantime, I tried to make something that: 

- No need to regenerate the data set as this can take a very long time
- Tried to keep the size of generated data set as small as possible
  - looking at helper methods that even compress the already existing data set
- This solution while not revolutionary, keeps happy both _aspects_ of the static functions: `listing` and `targeting`
  - When trying to find a _smart_ approach to use `meta.php` to make the `get*` specific country data this would break the listing methods and vice versa. I am aware that I might have missed a very obvious solution, please let me know!
- Added a separate test class that includes `XK` and re-tests the entire data set with this code in it. Adapted certain tests to check both for backward compatibility and specifically for `XK`

**Left to do: Update Changelog!** 
I wanted to know if this approach is good to begin with, but a documentation of the new ENV var is to follow. 
_Sidenote:_ Is the env var name enough? Needs to be renamed?  

cc: @nicolas-grekas @ro0NL @connorhu my followup after trying very hard not re-writing the bundle readers.

**Review by ro0NL — COMMENTED** [review]
LGTM. some tests for `SYMFONY_ALLOW_OPTIONAL_USER_ASSIGNED` would be nice.

File: src/Symfony/Component/Intl/Countries.php [hunk 1]
```diff
@@ -174,4 +245,11 @@ protected static function getPath(): string
     {
         return Intl::getDataDirectory().'/'.Intl::REGION_DIR;
     }
+
+    private static function ensureOptionalUserAssignedResolved(): void
+    {
+        if (!isset(self::$optionalUserAssigned)) {
+            self::$optionalUserAssigned = filter_var(getenv('SYMFONY_ALLOW_OPTIONAL_USER_ASSIGNED'), FILTER_VALIDATE_BOOLEAN);
+        }
+    }
```
Comment (GromNaN) [inline src/Symfony/Component/Intl/Countries.php]: This method should return the value directly.

```suggestion
    private static function optionalUserAssigned(): bool
    {
        return self::$optionalUserAssigned ??= filter_var(getenv('SYMFONY_ALLOW_OPTIONAL_USER_ASSIGNED'), FILTER_VALIDATE_BOOLEAN);
    }
```

File: src/Symfony/Component/Intl/Countries.php [hunk 2]
```diff
@@ -35,7 +37,13 @@ final class Countries extends ResourceBundle
      */
     public static function getCountryCodes(): array
     {
-        return self::readEntry(['Regions'], 'meta');
+        self::ensureOptionalUserAssignedResolved();
+
+        if (!self::$optionalUserAssigned) {
```
Comment (GromNaN) [inline src/Symfony/Component/Intl/Countries.php]: If the method returns the value, the code is shorter.
```suggestion
        if (!self::optionalUserAssigned()) {
```

File: src/Symfony/Component/Intl/Countries.php [hunk 3]
```diff
@@ -174,4 +245,11 @@ protected static function getPath(): string
     {
         return Intl::getDataDirectory().'/'.Intl::REGION_DIR;
     }
+
+    private static function ensureOptionalUserAssignedResolved(): void
+    {
+        if (!isset(self::$optionalUserAssigned)) {
+            self::$optionalUserAssigned = filter_var(getenv('SYMFONY_ALLOW_OPTIONAL_USER_ASSIGNED'), FILTER_VALIDATE_BOOLEAN);
```
Comment (GromNaN) [inline src/Symfony/Component/Intl/Countries.php]: I find this env var name not very explicit. It should mention "intl" for the component and "country" for the feature.

`SYMFONY_INTL_ADD_COUNTRIES`

This variable could contain a list of country codes if we add some others (`XA`, `XA`, `XO`, `XI`, `XN`, `XU`, `XV`, `XX`). That would let the developers pick what they need instead of being binary all or nothing.

It was proposed the other way with the deny list: https://github.com/symfony/symfony/pull/59693#issuecomment-2634034852

File: src/Symfony/Component/Intl/Countries.php (hunk 1 above)
Comment (ro0NL) [inline src/Symfony/Component/Intl/Countries.php]: what about `isOptionalUserAssigned(): bool`, and return here already

File: src/Symfony/Component/Intl/Countries.php (hunk 3 above)
Comment (llupa) [reply src/Symfony/Component/Intl/Countries.php]: > I find this env var name not very explicit. It should mention "intl" for the component and "country" for the feature. 

I can get by adding `_INTL_` but I really want to add some context, because I am noticing that the user assigned part is interpreted differently by different people when talking about this specific issue. 

The `User-Assigned` codes are always from entities that have the _power_ to assign them, this in turn for this component means that the ISO team in Geneva that maintains ISO 3166-1 will allocate them, then someone puts them in ICU and in turn we distill it further. That means an Alpha 2, Alpha 3 and Numeric code, all three, need to exist so that the getters that find each other (2-3-Nr.) work. If a developer wants to add custom codes, they need to add all three and we need to resolve the values correctly.

For Kosovo, because of reasons (I am happy to expand with relevant comments in this repo), the team decided to add it in `DENYLIST` which in turn through the years has caused issues. People working for projects that have a Spanish-centric view of country codes were happy since Spain does not recognize Kosovo, but users that worked for say a German-centric view of country codes and allowed purchases from Kosovo needed the code.

The _user_ for this specific code (XK) is the European Commission [ref](https://github.com/symfony/symfony/issues/54711#issuecomment-2249736718) and the implementation focuses on enabling the most recurring issue. 

I am generally opposed to the idea to let developers add codes because from personal experience none usually really checks if the code(s) they want to assign is in use or not from `User Assigned` or if it collides with other ISO norms. As en example my former Product Owner started to use `ERK` for `Erklärvideo`, until we had the issue that ERK is the language code for [Nafsan](https://en.wikipedia.org/wiki/Nafsan_language) (ISO 639-3). 

With that said, I am not opposed to implement this in a separate PR, I just really would like to have the confirmation from multiple core devs that this indeed OK and when custom _User Assigned_ are introduced how do we validate if they are in actuality OK to be used? Maybe even have an RFC first.

File: src/Symfony/Component/Intl/Countries.php (hunk 1 above)
Comment (llupa) [reply src/Symfony/Component/Intl/Countries.php]: This is great! Going to push an update tomorrow. Thanks <3

File: src/Symfony/Component/Intl/Countries.php (hunk 3 above)
Comment (javiereguiluz) [reply src/Symfony/Component/Intl/Countries.php]: @llupa I don't fully understand your comment.

Is Kosovo the only territory/country in that "not official yet" status? If there are more (or there will be more) then I think @GromNaN's idea makes sense so people can enable one or more of those "not official countries" in their apps.

I don't understand either the fear that people can make up codes and territories/copuntries. That's a risk/mistake on their side and I don't think we need to protect against that.

File: src/Symfony/Component/Intl/Countries.php [hunk 4]
```diff
@@ -21,6 +21,8 @@
  */
 final class Countries extends ResourceBundle
 {
+    private static bool $optionalUserAssigned;
```
Comment (javiereguiluz) [inline src/Symfony/Component/Intl/Countries.php]: I think the `$optionalUserAssigned` name is a bit problematic:

* `optional` feels redundant. If they are enabled explicitly by the user, it's clear that they are optional
* `user assigned` feels a bit misleading. Users (developers) are not assigning these territory/country codes. They are only enabling them to show them in the list of official countries.

File: src/Symfony/Component/Intl/Countries.php (hunk 3 above)
Comment (ro0NL) [reply src/Symfony/Component/Intl/Countries.php]: > `SYMFONY_INTL_ADD_COUNTRIES` 

the feature here is to allow existing ISO/ICU _user-assgined_ codes, not give full control to developers

in that sense im fine with the current naming

AFAIK there's no real convention currently in SF on env keys, unless we find another example

for full explicity, maybe `SYMFONY_INTL_ALLOW_ISO_USER_ASSIGNED=1`

File: src/Symfony/Component/Intl/Countries.php (hunk 4 above)
Comment (ro0NL) [reply src/Symfony/Component/Intl/Countries.php]: user-assigned is an ISO term, and somewhat internal detail (`private`)

optional is indeed a bit weird; maybe `$allowUserAssigned` is better

File: src/Symfony/Component/Intl/Countries.php (hunk 3 above)
Comment (llupa) [reply src/Symfony/Component/Intl/Countries.php]: @javiereguiluz I want to be sure that this ENV param will only enable similar codes to Kosovo's case. As of now Kosovo is the only one that has this need, the other user assigned codes are `Outlying Oceania`, `Pseudo-Accents`, and `Pseudo-Bidi`. 

If the "allow" is for these then for me it is fine. ✅ 

If it is for completely made up codes, then I would strongly recommend to have an RFC 🤓, because we need to have an agreement for value setting (XA, XAA, 999) and how do we tie them together at runtime as these will probably need their own new BundleReader implementation. 

Edit: 

> I don't understand either the fear that people can make up codes and territories/copuntries. That's a risk/mistake on their side and I don't think we need to protect against that. 

Honestly, we can do it, but it seems like a new functionality for this component for me, and I am already imagining the bug reports because their sf-intl allows it but it collides with some other OS intl or even php intl 😅

Comment (ro0NL) [reply src/Symfony/Component/Intl/Countries.php]: i agree with @llupa to be conservative by default

**Comment by connorhu** [comment]
I still think that this direction is over-engineered. We just need a setter method where the developer can specify where their custom files are. That way the developer can set the data in boot time. If the developer wants to make a list that includes Kosovo, or if they want to display historical things (e.g. Czechoslovakia), that's up to them.

**Comment by llupa** [comment]
@connorhu For `formerly used` codes I would open an RFC and a proposal of how to implement it. 

They have an ALPHA-4 standard on top and this component does not support the format. Some of the formerly used codes collide with current ones too. For example today's Slovakia and former Sikkim share the same code.

File: src/Symfony/Component/Intl/Countries.php (hunk 3 above)
Comment (llupa) [reply src/Symfony/Component/Intl/Countries.php]: Hey all, so I implemented the following: 
- ENV param name is more INTL explicit and keeps ISO glossar
- there is no _optional_ anywhere left, now only refer to UserAssigned.
- dropped the `ensure` function and adopted the `??=` proposal in a single method. 

If you think this PR fixes the 3 linked issues above you could approve it. If you want something changed for specifically handling on those issues, let me know. 

For the other topic of letting people create their own standard on top of ISO standard, I want to make a separate RFC and put some ideas how to approach this as I am certain at least one new BundleReader class needs to be created to support that. 

Thanks ❤️

File: src/Symfony/Component/Intl/Countries.php [hunk 5]
```diff
@@ -21,7 +21,7 @@
  */
 final class Countries extends ResourceBundle
 {
-    private static bool $optionalUserAssigned;
+    private static ?bool $allowUserAssigned = null;
```
Comment (javiereguiluz) [inline src/Symfony/Component/Intl/Countries.php]: Maybe this is technically required for some reasons, but I'd prefer to not have nullable booleans. Can we make this option truly binary and give it a `false` default value?

Comment (GromNaN) [reply src/Symfony/Component/Intl/Countries.php]: It should not be initialized by default. So that if it's used directly, an error will occur.

```suggestion
    private static bool $allowUserAssigned;
```

Comment (ro0NL) [reply src/Symfony/Component/Intl/Countries.php]: when it's null, we populate it from the env var

Comment (llupa) [reply src/Symfony/Component/Intl/Countries.php]: This was so that I could write [this test](https://github.com/symfony/symfony/pull/61024/files#diff-ac1ae93f940a0511a00c36b9093cf58f706ca3708575dd20113ff6498b7a13ceR800) that does in fact "simulate" env var behavior. 

I am also not a fan of the nullable but I could not find a way to write a test that was clear what it was testing. Open to ideas as Roland was the one who wanted that test, and I also agree it is good to have.

Edit: I see the link does not work when UI is collapsed. I meant: 

```php
    public function testEnvVariableAllowsUserAssigned(): void
    {
        // when env param is not set
        $ref = new \ReflectionProperty(Countries::class, 'allowUserAssigned');
        $ref->setValue(null, null);

        $this->assertFalse(Countries::exists('XK'));

        // when env param is set to false
        $ref = new \ReflectionProperty(Countries::class, 'allowUserAssigned');
        $ref->setValue(null, null);

        putenv('SYMFONY_INTL_ALLOW_USER_ASSIGNED=false');

        $this->assertFalse(Countries::exists('XK'));

        // when env param is set to true
        $ref = new \ReflectionProperty(Countries::class, 'allowUserAssigned');
        $ref->setValue(null, null);

        putenv('SYMFONY_INTL_ALLOW_USER_ASSIGNED=true');

        $this->assertTrue(Countries::exists('XK'));
    }
```

**Review by ro0NL — APPROVED** [review]

File: src/Symfony/Component/Intl/Tests/CountriesWithUserAssignedTest.php [hunk 6]
```diff
@@ -0,0 +1,1037 @@
...
+        'ZM' => '894',
+        'ZW' => '716',
+        'XK' => '983',
+    ];
+
+    public static function setUpBeforeClass(): void
+    {
+        // other tests might or might not call Countries first and set SYMFONY_INTL_ALLOW_USER_ASSIGNED
+        $ref = new \ReflectionProperty(Countries::class, 'allowUserAssigned');
+        $ref->setValue(null, true);
```
Comment (ro0NL) [inline src/Symfony/Component/Intl/Tests/CountriesWithUserAssignedTest.php]: why not just set the env var (`putenv`) to enable the new feature

File: src/Symfony/Component/Intl/Countries.php [hunk 7]
```diff
@@ -246,10 +228,8 @@ protected static function getPath(): string
         return Intl::getDataDirectory().'/'.Intl::REGION_DIR;
     }
 
-    private static function ensureOptionalUserAssignedResolved(): void
+    private static function allowUserAssigned(): bool
     {
-        if (!isset(self::$optionalUserAssigned)) {
-            self::$optionalUserAssigned = filter_var(getenv('SYMFONY_ALLOW_OPTIONAL_USER_ASSIGNED'), FILTER_VALIDATE_BOOLEAN);
-        }
+        return self::$allowUserAssigned ??= filter_var(getenv('SYMFONY_INTL_ALLOW_USER_ASSIGNED'), FILTER_VALIDATE_BOOLEAN);
```
Comment (GromNaN) [inline src/Symfony/Component/Intl/Countries.php]: `ALLOW` indicates a permission, but the "intl" package is only about giving a local representation. Here, we mean that "user assigned" are included: `SYMFONY_INTL_INCLUDE_USER_ASSIGNED` or `SYMFONY_INTL_WITH_USER_ASSIGNED`

File: src/Symfony/Component/Intl/Tests/CountriesWithUserAssignedTest.php (hunk 6 above)
Comment (llupa) [reply src/Symfony/Component/Intl/Tests/CountriesWithUserAssignedTest.php]: Because there are other tests that run before this one, and they set it to false permanently. If we keep the nullable property, I can set it back to null, putenv and then the test do its thing, yes.

File: src/Symfony/Component/Intl/Countries.php (hunk 7 above)
Comment (llupa) [reply src/Symfony/Component/Intl/Countries.php]: I like `SYMFONY_INTL_WITH_USER_ASSIGNED ` as I also naturally called my test class like that.

File: src/Symfony/Component/Intl/Countries.php (hunk 5 above)
Comment (GromNaN) [reply src/Symfony/Component/Intl/Countries.php]: There is a design issue that leads to use the reflection. The environment variable should not be the only way to define this configuration. We could add a static method to assign the value. 

```php
public static function setWithUserAssigned(bool $withUserAssigned): ?bool
{
    $previous = self::$withUserAssigned;

    self::$withUserAssigned = $withUserAssigned;

    return $previous;
}
```

The class being final, we can change the parameter type later to accept a list of code, we we decides to do so.

Comment (Pierstoval) [reply src/Symfony/Component/Intl/Countries.php]: Maybe you could keep the value as non-nullable and uninitialized, and (unfortunately for perfs) run each tests related to this var in a separate process, so that the var is truly reset every time. It is also closer to what happens in a real execution environment.

Comment (llupa) [reply src/Symfony/Component/Intl/Countries.php]: I am going with GromNaN's recommendation because it is something I considered myself. This could also cover cases when the country list you need to use is tied to a sf-user-account, so for some you have it with-user-assigned and for some without-user-assigned

Comment (llupa) [reply src/Symfony/Component/Intl/Countries.php]: So, I found a way to implement all ideas from all three. 

- the internal property now is `bool` only, not nullable
- there is a public method to change this property at runtime if you wish to do so
- changed GHA a bit 🤏 so I can run the ENV tests in isolation (this can be done easier with PHPUnit 11)

Let me know. But I will have to pick up next Monday, as work calls now :)

File: src/Symfony/Component/Intl/Countries.php [hunk 8]
```diff
@@ -223,13 +223,30 @@ public static function getAlpha3Names(?string $displayLocale = null): array
         return $alpha3Names;
     }
 
+    /**
+     * Sets the internal `withUserAssigned` flag, overriding the default `SYMFONY_INTL_WITH_USER_ASSIGNED` value
```
Comment (OskarStark) [inline src/Symfony/Component/Intl/Countries.php]:
```suggestion
     * Sets the internal `withUserAssigned` flag, overriding the default `SYMFONY_INTL_WITH_USER_ASSIGNED` value.
```

File: src/Symfony/Component/Intl/Countries.php (hunk 5 above)
Comment (OskarStark) [reply src/Symfony/Component/Intl/Countries.php]: > changed GHA a bit 🤏 so I can run the ENV tests in isolation (this can be done easier with PHPUnit 11)

cc @xabbuh as you are working on
* #58370

File: src/Symfony/Component/Intl/Countries.php [hunk 9]
```diff
@@ -170,8 +223,30 @@ public static function getAlpha3Names(?string $displayLocale = null): array
...
+    }
+
     protected static function getPath(): string
     {
         return Intl::getDataDirectory().'/'.Intl::REGION_DIR;
     }
+
+    private static function withUserAssigned(): bool
+    {
+        return self::$withUserAssigned ??= filter_var(getenv('SYMFONY_INTL_WITH_USER_ASSIGNED'), FILTER_VALIDATE_BOOLEAN);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Intl/Countries.php]:
```suggestion
        return self::$withUserAssigned ??= filter_var($_ENV['SYMFONY_INTL_WITH_USER_ASSIGNED'] ?? $_SERVER['SYMFONY_INTL_WITH_USER_ASSIGNED'] ?? getenv('SYMFONY_INTL_WITH_USER_ASSIGNED'), FILTER_VALIDATE_BOOLEAN);
```

File: src/Symfony/Component/Intl/Countries.php [hunk 10]
```diff
@@ -170,8 +223,30 @@ public static function getAlpha3Names(?string $displayLocale = null): array
         return $alpha3Names;
     }
 
+    /**
+     * Sets the internal `withUserAssigned` flag, overriding the default `SYMFONY_INTL_WITH_USER_ASSIGNED` value.
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Intl/Countries.php]:
```suggestion
     * Sets the internal `withUserAssigned` flag, overriding the default `SYMFONY_INTL_WITH_USER_ASSIGNED` env var.
```

File: src/Symfony/Component/Intl/Countries.php [hunk 11]
```diff
@@ -170,8 +223,30 @@ public static function getAlpha3Names(?string $displayLocale = null): array
...
+     *
+     * The ISO 3166/MA has received information that the CE Commission has allocated the alpha-2 user-assigned code "XK"
+     * to represent Kosovo in the interim of being recognized by the UN as a member state.
+     *
+     * Set `$withUserAssigned` to true to have `XK`, `XKK` and `983` available in the other functions of this class.
+     */
+    public static function setWithUserAssigned(bool $withUserAssigned): bool
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Intl/Countries.php]: given that this is both a setter and a getter, would it make sense to merge the two added methods?

```suggestion
    public static function withUserAssigned(?bool $withUserAssigned = null): bool
```

and we always return the current value (after setting it when $withUserAssigned is not null)?

**Review by nicolas-grekas — COMMENTED** [review]
Works for me with minor comments

File: src/Symfony/Component/Intl/Countries.php (hunk 9 above)
Comment (llupa) [reply src/Symfony/Component/Intl/Countries.php]: Do you want dedicated tests checking for `$_ENV` and `$_SERVER`?

Comment (nicolas-grekas) [reply src/Symfony/Component/Intl/Countries.php]: no need to

**Review by nicolas-grekas — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @llupa.
