### PR TITLE
[Console] Specify types of interactive question choices

### LINKED ISSUE #61122: [Console] PHP deprecation when question value is NULL
### Symfony version(s) affected

6.4

### Description

I get this deprecation notice, when I start typing in the console:

deprecation.INFO: Deprecated: str_starts_with(): Passing null to parameter #1 ($haystack) of type string is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: str_starts_with(): Passing null to parameter #1 ($haystack) of type string is deprecated at /data/vendor/symfony/console/Helper/QuestionHelper.php:357)"} {"token":null}

The value of the ChoiceQuestion array should not be NULL, but I can happen. When I initate the command with "bin/console app:task", and press for example 2, I will get the deprecation notice (before pressing enter).

### How to reproduce

```php
#[AsCommand(name: 'app:task', description: 'Execute task for module')]
final class TaskCommand extends Command
{
    protected function configure(): void
    {
        $this
            ->addOption('moduleId', null, InputOption::VALUE_REQUIRED, 'The "id" of the module?');
    }

    protected function interact(InputInterface $input, OutputInterface $output): void
    {
        $moduleId = $input->getOption('moduleId');

        if (null !== $moduleId) {
            return;
        }

        $data = [
            1 => 'Foo',
            2 => 'Bar',
            3 => null,
        ];

        $question = new ChoiceQuestion('Please select a module:', $data);
        $question->setMaxAttempts(2);
        $question->setValidator(function (string $answer): string {
            if (0 === preg_match('/^\d+$/', $answer)) {
                throw new RuntimeException('Unknown module');
            }

            return $answer;
        });

        $answer = $this->getHelper('question')->ask($input, $output, $question);

        $input->setOption('moduleId', $answer);
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        return Command::SUCCESS;
    }
}
```

### Possible Solution

Add nullsafe

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by GromNaN**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #61122
| License       | MIT

Passing a non-string value results in a deprecation message when the value is passed to `str_starts_with`.

Replace #61123

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]
Dunno if that's enough, but still works for me.

/cc @willemverspyck WDYT?

File: src/Symfony/Component/Console/Question/ChoiceQuestion.php [hunk 1]
```diff
@@ -26,9 +26,9 @@ class ChoiceQuestion extends Question
     private string $errorMessage = 'Value "%s" is invalid';
 
     /**
-     * @param string                     $question The question to ask to the user
-     * @param array                      $choices  The list of available choices
-     * @param string|bool|int|float|null $default  The default answer to return
+     * @param string                      $question The question to ask to the user
+     * @param list<string|bool|int|float> $choices  The list of available choices
```
Comment (stof) [inline src/Symfony/Component/Console/Question/ChoiceQuestion.php]: `getDefaultValidator` has some logic determining whether choices are an associative array, so using `list<>` is wrong. Please use `array<>` instead to match the actual behavior.

And please also add the phpdoc for the `getChoices` method to return the same type

File: src/Symfony/Component/Console/Question/ChoiceQuestion.php [hunk 2]
```diff
@@ -44,7 +44,7 @@ public function __construct(string $question, array $choices, string|bool|int|fl
     }
 
     /**
-     * Returns available choices.
+     * @return array<string|bool|int|float> The list of available choices
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Question/ChoiceQuestion.php:47]:
```suggestion
     * @return array<string|bool|int|float>
```

**Comment by nicolas-grekas** [comment]
Thank you @GromNaN.
