### PR TITLE
[DependencyInjection] Fix cloned lazy services not sharing their dependencies when dumped with PhpDumper

### LINKED ISSUE #59706: [DependencyInjection] PhpDumper does not share single-use dependencies when a lazy service is cloned
### Symfony version(s) affected

7.x

### Description

PhpDumper inlines dependencies when they are private, used only once and non-lazy. When `clone`-ing a lazy service using one of these dependencies, this check is not sufficient and the dependency is constructed twice with the cloned services not sharing the dependency.

This is a regression compared to the old method through symfony/proxy-manager-bridge available in 6.x. Using the container directly without using PhpDumper also correctly shares the dependency.

The blog post introducing the new implementation (https://symfony.com/blog/revisiting-lazy-loading-proxies-in-php) explicitly calls out support for clone and wither methods, so I believe the current behaviour where the dependency is not shared is a bug.

### How to reproduce

The following script showcases the issue. The last two asserts fail. The asserts pass when the compiled container is used directly without using PhpDumper or when using 6.x with symfony/proxy-manager-bridge.

```
<?php
require_once "vendor/autoload.php";

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Dumper\PhpDumper;
use Symfony\Component\DependencyInjection\Reference;

class Dependency {
	public static int $construction_count = 0;

	public function __construct() {
		++self::$construction_count;
	}
}

class Service {
	public function __construct(
		public readonly mixed $argument,
	) {}
}

function assert_construction_count(int $expected): void {
	assert(
		Dependency::$construction_count === $expected,
		sprintf('Construction count. Expected=%d, Actual=%d', $expected, Dependency::$construction_count)
	);
}

$container = new ContainerBuilder();
$container->register('dependency', Dependency::class);
$container->register('service', Service::class)
	->setArgument('$argument', new Reference('dependency'))
	->setLazy(true)
	->setPublic(true);

$container->compile();

// Dump and reconstruct the container.
$dumper = new PhpDumper($container);
file_put_contents('./container.php', $dumper->dump([
	'class' => 'DumpedContainer',
]));
include './container.php';
$container = new \DumpedContainer();

assert_construction_count(0);

// The service is lazy and will not yet be constructed.
$service = $container->get('service');
assert_construction_count(0);

// Cloning has no impact.
$first_cloned_service = clone $service;
$second_cloned_service = clone $service;
assert_construction_count(0);

// Construction of the first clone creates the clone and the internal argument.
$first_arg = $first_cloned_service->argument;
assert_construction_count(1);

// Construction of the second clone should only create the clone and reuse the dependency. Currently this fails and the dependency is constructed twice.
$second_arg = $second_cloned_service->argument;
assert_construction_count(1);
assert($first_arg === $second_arg);
```

### Possible Solution

Ideally I would expect the service to be constructed when the object is cloned. I don't think PHP offers any method to hook into this process before the clone occurs (`__clone` is only called afterwards) and afterwards is too late.

An alternative approach is to make the inlining behaviour more conservative. Currently the assignment to `singleUsePrivateIds` through `isSingleUsePrivateNode()` in the `PhpDumper` controls the inlining of service factories. This already checks a lazy flag which considers the target service.

I'm unsure what the best solution would be. The check could be expanded to also check incoming edges. Another approach would be to mark the edge as lazy if the source definition is lazy in `AnalyseServiceReferencesPass` instead of only checking the target (possible through reordering when `$this->lazy` is reset).

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by pvandommelen**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59706
| License       | MIT

Fixes referenced services not being shared when lazy services are cloned before being initialized. Adds tests for both the ghost and proxy scenario's. 

This makes the inlining behaviour more conservative, which impacts the outputs of some other test cases.

First commit adds a test, second commit has the fix. Third commit also considers the proxy case, which is also affected. I can squash if necessary.

Targeted 6.4, but this also applies to 7.x.

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Compiler/InlineServiceDefinitionsPass.php [hunk 1]
```diff
@@ -224,6 +224,7 @@ private function isInlineableDefinition(string $id, Definition $definition): boo
             return false;
         }
 
-        return $this->container->getDefinition($srcId)->isShared();
+        $source_definition = $this->container->getDefinition($srcId);
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Compiler/InlineServiceDefinitionsPass.php]: please name it `$sourceDefinition` (or `$srcDefinition` to use the same prefix than `$srcId`). We use camelCased variable names in Symfony.

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_wither_lazy.php [hunk 2]
```diff
@@ -61,7 +61,7 @@ protected static function getWitherService($container, $lazyLoad = true)
 
         $instance = new \Symfony\Component\DependencyInjection\Tests\Compiler\Wither();
 
-        $a = new \Symfony\Component\DependencyInjection\Tests\Compiler\Foo();
+        $a = (new \Symfony\Component\DependencyInjection\Tests\Compiler\Foo());
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_wither_lazy.php]: why is this adding parenthesis ?

File: src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php [hunk 3]
```diff
@@ -2186,9 +2186,9 @@ private function isSingleUsePrivateNode(ServiceReferenceGraphNode $node): bool
                 return false;
             }
 
-            // When the source node is a ghost, it will use its references only when constructed.
-            // Since a ghost can be cloned, we do not know how often its references are constructed.
-            if ($this->getProxyDumper()->isProxyCandidate($value, $asGhostObject) && $asGhostObject) {
+            // When the source node is a proxy or ghost, it will construct its references only when the node itself is constructed.
+            // Since the node can be cloned before being fully constructed, we do not know how often its references are used.
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php]: `before being initialized`

File: src/Symfony/Component/DependencyInjection/Compiler/InlineServiceDefinitionsPass.php (hunk 1 above)
Comment (pvandommelen) [reply src/Symfony/Component/DependencyInjection/Compiler/InlineServiceDefinitionsPass.php]: Renamed to `$srcDefinition`

File: src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php (hunk 3 above)
Comment (pvandommelen) [reply src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php]: Like this? Reworded "fully constructed" to "initialized" to make the distinction between creating the reference and initializing it clearer.
> // When the source node is a proxy or ghost, it will construct its references only when the node itself is initialized.
            // Since the node can be cloned before being fully initialized, we do not know how often its references are used.

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_wither_lazy.php (hunk 2 above)
Comment (pvandommelen) [reply src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_wither_lazy.php]: This line is changed in the next commit when proxies are also considered, that case probably makes the parenthesis more acceptable. Quite a few container dumps contain unnecessary parenthesis, though I don't think in this particular configuration (and this one is also gone again).

This remains a good question though. What I think happens:
PhpDumper adds these on the normal path for "trivial" instances (`PhpDumper::getServiceCall`). I assume because the statement can then be wrapped in other code more easily. But when considering arguments of nontrivial instances, these are not wrapped (`PhpDumper::dumpValue`).

The change in `InlineServiceDefinitionsPass` makes the `Foo` class non-inlinable where it was inlined before. It is considered trivial, so these parenthesis were added.

**Comment by pvandommelen** [comment]
Updated. I don't think the failing tests are related.

File: src/Symfony/Component/DependencyInjection/Compiler/InlineServiceDefinitionsPass.php [hunk 4]
```diff
@@ -224,6 +224,7 @@ private function isInlineableDefinition(string $id, Definition $definition): boo
             return false;
         }
 
-        return $this->container->getDefinition($srcId)->isShared();
+        $srcDefinition = $this->container->getDefinition($srcId);
+        return $srcDefinition->isShared() && !$srcDefinition->isLazy();
```
Comment (GromNaN) [inline src/Symfony/Component/DependencyInjection/Compiler/InlineServiceDefinitionsPass.php:229]:
```suggestion

        return $srcDefinition->isShared() && !$srcDefinition->isLazy();
```

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_almost_circular_private.php [hunk 5]
```diff
@@ -572,13 +598,13 @@ protected static function getMailerInline_TransportFactory_AmazonService($contai
      */
     protected static function getManager4Service($container, $lazyLoad = true)
     {
-        $a = new \stdClass();
+        $a = ($container->privates['connection4'] ?? self::getConnection4Service($container));
```
Comment (GromNaN) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_almost_circular_private.php:601]: Side question: why `$a` is not inlined in the `new \stdClass`?

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_almost_circular_private.php:601]: This happens when circular loops are found: instantiating connection4 could create manager4 before we exit this function.

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/DependencyContainerInterface.php [hunk 6]
```diff
@@ -0,0 +1,9 @@
+<?php
+
+namespace Symfony\Component\DependencyInjection\Tests\Fixtures;
+
+interface DependencyContainerInterface
+{
+
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/DependencyContainerInterface.php]:
```suggestion
```

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/DependencyContainerInterface.php [hunk 7]
```diff
@@ -0,0 +1,9 @@
+<?php
+
+namespace Symfony\Component\DependencyInjection\Tests\Fixtures;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/DependencyContainerInterface.php:12]: please add the licence header

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/DependencyContainer.php [hunk 8]
```diff
@@ -0,0 +1,19 @@
+<?php
+
+namespace Symfony\Component\DependencyInjection\Tests\Fixtures;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/DependencyContainer.php:12]: please add the licence header

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/DependencyContainer.php [hunk 9]
```diff
@@ -0,0 +1,19 @@
...
+
+class DependencyContainer implements DependencyContainerInterface
+{
+
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/DependencyContainer.php]:
```suggestion
```

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/DependencyContainer.php [hunk 10]
```diff
@@ -0,0 +1,19 @@
...
+        public mixed $dependency,
+    )
+    {
+    }
+
+    public function getDependency(): mixed
+    {
+        return $this->dependency;
+    }
+
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/DependencyContainer.php]:
```suggestion
```

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/DependencyContainer.php [hunk 11]
```diff
@@ -0,0 +1,19 @@
...
+namespace Symfony\Component\DependencyInjection\Tests\Fixtures;
+
+class DependencyContainer implements DependencyContainerInterface
+{
+
+    public function __construct(
+        public mixed $dependency,
+    )
+    {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/DependencyContainer.php]:
```suggestion
    ) {
```

**Review by nicolas-grekas — APPROVED** [review]
LGTM thanks, just some CS tweaks needed.

**Comment by pvandommelen** [comment]
Resolved style comments

**Review by GromNaN — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Note that when using native proxies, cloning will trigger initialization.
You should not rely on the current behavior when cloning.

(The patch is still fixing a valid concern since we're not coupled to one implementation)

**Comment by nicolas-grekas** [comment]
Thank you @pvandommelen.

**Comment by pvandommelen** [comment]
Thanks for the quick reviews!
