### PR TITLE
[Serializer] Fix is/has/can accessor naming to strip prefix unless colliding

### LINKED ISSUE #62353: [Serializer] Regression in ObjectNormalizer: boolean `is*` getters now produce `isXxx` instead of `xxx` after upgrade to 7.3.5
## Symfony version(s) affected
`7.3.5` (regression since `7.3.2`)

---

## Description
After upgrading from **symfony/serializer v7.3.2** to **v7.3.5**,  
the `ObjectNormalizer` started producing **different field names** for boolean getters.

Before the update, a getter like `isAuthorized()` produced the field `authorized`.  
After the update, the field became `isAuthorized`.

This change silently breaks serialized API responses and introduces a **backward-incompatible change** between patch versions, which is unexpected and potentially critical for projects with stable API contracts.

---

## How to reproduce
```php
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Encoder\JsonEncoder;

final class PartnerAuthorizationInfo
{
    public function __construct(
        private bool $isAuthorized = false,
    ) {}

    public function isAuthorized(): bool
    {
        return $this->isAuthorized;
    }
}

$serializer = new Serializer([new ObjectNormalizer()], [new JsonEncoder()]);
echo $serializer->serialize(new PartnerAuthorizationInfo(true), 'json');
```

## Output before (v7.3.2)
```json
{"authorized": true}
```

## Output after (v7.3.5)
```json
{"isAuthorized": true}
```

## Expected behavior

Boolean getters using the `is*` pattern should produce property names **without** the `is` prefix, e.g.:

- `isAuthorized() → "authorized"`

This was the behavior up to 7.3.2 and should remain stable in patch releases.

## Actual behavior

Since `7.3.5`, the `ObjectNormalizer` now includes the is prefix in serialized property names, producing:

- `isAuthorized() → "isAuthorized"`

## Possible cause

Recent changes in the serializer’s `ObjectNormalizer` logic around method-to-property name resolution seem to have caused this.

Likely related to or introduced by:

- [61096](https://github.com/symfony/symfony/issues/61096)
- [61097]https://github.com/symfony/symfony/pull/61097
- [61988](https://github.com/symfony/symfony/issues/61988)

Those PRs refactored the internal handling of accessors and may have altered how is* accessors map to property names.

## Why this is problematic

- Introduces **breaking API changes** even in patch-level updates.
- Affects any DTOs or models with boolean `is*` accessors.
- Causes inconsistencies between environments running slightly different patch versions.
- Breaks compatibility with existing clients relying on the previous field names.

## Suggested resolution

- Restore previous behavior for boolean `is*` accessors (`isAuthorized()` → `"authorized"`).
- If the new behavior is intentional, introduce **an explicit configuration flag** to opt into it.
- Maintain **backward compatibility** for serialization naming in patch versions.

## Environment

| Component               | Version |
|--------------------------|----------|
| PHP                      | 8.3 |
| symfony/serializer       | 7.3.5 |
| symfony/framework-bundle | 7.3.5 |
| Configuration            | Default (no custom name converter) |

---

## Additional context

This issue appeared immediately after upgrading an existing production project from **v7.3.2** to **v7.3.5**.  
No configuration or code changes were made — only dependency updates via Composer.

This regression can have a significant impact in API-based applications where serialized DTO field names are part of a public contract.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62353
| License       | MIT

Before PR #61097 (Symfony 6.4.26/7.3.5), methods like `isPublished()` would serialize using the base name "published" by default.

PR #61097 fixed an issue where objects with both `$isPublished` property and `isPublished()` method couldn't round-trip properly. However, it caused a regression: ALL is/has/can accessors started using the prefixed form ("isPublished") when a matching property exists, even when there's no actual collision.

This PR fixes the regression by:

1. Only using the full method name (e.g., "isPublished") when there's an actual collision - another property or accessor that would map to the same base name ("published")
2. Keeping the base name ("published") when no collision exists, matching pre-6.4.26 behavior for the common case
3. Extracting shared collision detection logic into `AccessorCollisionResolverTrait` to ensure consistent behavior between `ObjectNormalizer` and `AttributeLoader`

### CODE REVIEW

**Comment by RafaelKr** [comment]
@nicolas-grekas Thanks for iterating over this, besides from #63187 to me it looks like this is the way to go. Now de- and serialization should behave deterministically, also fixing the initial problem (https://github.com/symfony/symfony/pull/61097#issuecomment-3248593068).
Also it's nice, that this is now available via trait.

File: src/Symfony/Component/Serializer/Mapping/Loader/AccessorCollisionResolverTrait.php [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+            's' => $andMutator && str_starts_with($methodName, 'set') ? 3 : null,
+            'g' => str_starts_with($methodName, 'get') ? 3 : null,
+            'h' => str_starts_with($methodName, 'has') ? 3 : null,
+            'c' => str_starts_with($methodName, 'can') ? 3 : null,
+            'i' => str_starts_with($methodName, 'is') ? 2 : null,
+            default => null,
+        };
+
+        // ctype_lower check to find out if method looks like accessor but actually is not, e.g. hash, cancel
+        if (null === $i || ctype_lower($methodName[$i] ?? 'a') || $method->isStatic()) {
```
Comment (digilist) [inline src/Symfony/Component/Serializer/Mapping/Loader/AccessorCollisionResolverTrait.php:37]: @nicolas-grekas is there a reason for ignoring static methods here? This introduces a regression when using serialization groups with static methods (a use case for this when there are different implementations for an interface and more details about the implementation are available via a static method)

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Mapping/Loader/AccessorCollisionResolverTrait.php:37]: please submit a PR to remove that limitation, this case wasn't covered by a test and I didn't think it was use.

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php [hunk 2]
```diff
@@ -87,37 +90,10 @@ protected function extractAttributes(object $object, ?string $format = null, arr
...
-                    $attributeName = substr($name, $i);
-
-                    if (!$reflClass->hasProperty($attributeName)) {
-                        $attributeName = lcfirst($attributeName);
-                    }
-                }
-            } elseif ($this->hasProperty($reflMethod->getDeclaringClass(), $name)) {
+            $attributeName = $this->getAttributeNameFromAccessor($reflClass, $reflMethod, false);
+
+            if ($this->hasPropertyForAccessor($reflMethod->getDeclaringClass(), $name) && (null === $attributeName || $this->hasAttributeNameCollision($reflClass, $attributeName, $name))) {
```
Comment (solverat) [inline src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php:96]: @nicolas-grekas with that, static methods like `public static function select()` will be passed to normalization which is probably something we don't want to?

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php:96]: I'd be happy to review a failing test case
