### PR TITLE
[HttpFoundation]  filter out empty HTTP header parts

### LINKED ISSUE #54868: [HttpFoundation] Fatal Error Parsing Empty Accept Header
### Symfony version(s) affected

7.0.7

### Description

A fatal error occurs when parsing the Accept header if it only consists of semi-colons.
```
Fatal error: Uncaught TypeError: Symfony\Component\HttpFoundation\AcceptHeaderItem::__construct(): Argument #1 ($value) must be of type string, null given, called in /Users/reza/Code/http-foundation-bug/vendor/symfony/http-foundation/AcceptHeader.php on line 56 and defined in /Users/reza/Code/http-foundation-bug/vendor/symfony/http-foundation/AcceptHeaderItem.php on line 26

TypeError: Symfony\Component\HttpFoundation\AcceptHeaderItem::__construct(): Argument #1 ($value) must be of type string, null given, called in /Users/reza/Code/http-foundation-bug/vendor/symfony/http-foundation/AcceptHeader.php on line 56 in /Users/reza/Code/http-foundation-bug/vendor/symfony/http-foundation/AcceptHeaderItem.php on line 26

Call Stack:
    0.0001     497448   1. {main}() /Users/reza/Code/http-foundation-bug/src/run.php:0
    0.0015     704056   2. Symfony\Component\HttpFoundation\AcceptHeader::fromString($headerValue = ';;;') /Users/reza/Code/http-foundation-bug/src/run.php:8
    0.0018     739616   3. array_map($callback = class Closure {  }, $array = [0 => []]) /Users/reza/Code/http-foundation-bug/vendor/symfony/http-foundation/AcceptHeader.php:51
    0.0018     739936   4. Symfony\Component\HttpFoundation\AcceptHeader::Symfony\Component\HttpFoundation\{closure:/Users/reza/Code/http-foundation-bug/vendor/symfony/http-foundation/AcceptHeader.php:51-60}($subParts = []) /Users/reza/Code/http-foundation-bug/vendor/symfony/http-foundation/AcceptHeader.php:51
    0.0024     741184   5. Symfony\Component\HttpFoundation\AcceptHeaderItem->__construct($value = NULL, $attributes = []) /Users/reza/Code/http-foundation-bug/vendor/symfony/http-foundation/AcceptHeader.php:56
```

### How to reproduce

```
<?php

include "../vendor/autoload.php";

use Symfony\Component\HttpFoundation\AcceptHeader;

var_dump(
    AcceptHeader::fromString(";;;")
);

````

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54868
| License       | MIT

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/HttpFoundation/HeaderUtils.php [hunk 1]
```diff
@@ -289,6 +289,6 @@ private static function groupParts(array $matches, string $separators, bool $fir
             $parts[] = '' === $separators ? self::unquote($matches[0][0]) : self::groupParts($matches, $separators, false);
         }
 
-        return $parts;
+        return array_filter($parts);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/HeaderUtils.php]: well, shouldn't we do a strict comparision, so that we don't filter out he `"0"` string? is that a possible situation?

Comment (xabbuh) [reply src/Symfony/Component/HttpFoundation/HeaderUtils.php]: makes sense, I have rewritten the patch a bit

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.
