### PR TITLE
[Config] Fix generated comment for multiline "info"

### LINKED ISSUE #60317: symfony/config does not support multiline text
### Symfony version(s) affected

5.3 - 7.3

### Description

The symfony/config component formats phpdoc comments very poorly, and does not support multiple hyphenated text. Example below

### How to reproduce

**Repoduce stand**:

```php
<?php

declare (strict_types = 1);

use Symfony\Component\Config\Builder\ConfigBuilderGenerator;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

require_once __DIR__.'/vendor/autoload.php';

final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('temporal');

        $treeBuilder->getRootNode()
            ->children()
                ->scalarNode('foo')
                    ->defaultValue('bar')
                    ->info(
                        <<<STRING
                          Sets the rate limiting on number of activities that can be
                          executed per second per worker. This can be used to limit resources used by the worker.

                          Notice that the number is represented in float, so that you can set it
                          to less than 1 if needed. For example, set the number to 0.1 means you
                          want your activity to be executed once for every 10 seconds. This can be
                          used to protect down stream services from flooding.
                        STRING
                    )
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}


$builder = new ConfigBuilderGenerator(__DIR__ . '/dump');

$builder->build(new Configuration);
```

Output:
```php
<?php

namespace Symfony\Config;

use Symfony\Component\Config\Loader\ParamConfigurator;
use Symfony\Component\Config\Definition\Exception\InvalidConfigurationException;

/**
 * This class is automatically generated to help in creating a config.
 */
class TemporalConfig implements \Symfony\Component\Config\Builder\ConfigBuilderInterface
{
    private $foo;
    private $_usedProperties = [];

    /**
     *   Sets the rate limiting on number of activities that can be
      executed per second per worker. This can be used to limit resources used by the worker.

      Notice that the number is represented in float, so that you can set it
      to less than 1 if needed. For example, set the number to 0.1 means you
      want your activity to be executed once for every 10 seconds. This can be
      used to protect down stream services from flooding.
     * @default 'bar'
     * @param ParamConfigurator|mixed $value
     * @return $this
     */
    public function foo($value): static
    {
        $this->_usedProperties['foo'] = true;
        $this->foo = $value;

        return $this;
    }

    public function getExtensionAlias(): string
    {
        return 'temporal';
    }

    public function __construct(array $value = [])
    {
        if (array_key_exists('foo', $value)) {
            $this->_usedProperties['foo'] = true;
            $this->foo = $value['foo'];
            unset($value['foo']);
        }

        if ([] !== $value) {
            throw new InvalidConfigurationException(sprintf('The following keys are not supported by "%s": ', __CLASS__).implode(', ', array_keys($value)));
        }
    }

    public function toArray(): array
    {
        $output = [];
        if (isset($this->_usedProperties['foo'])) {
            $output['foo'] = $this->foo;
        }

        return $output;
    }

}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by GromNaN**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60317
| License       | MIT

Instead of fixing the multiline comment formatting only for the "info" part, the `* ` is now prepended to every line of the generated comment block.
`nette/code-generator` uses almost the same transformation: https://github.com/nette/php-generator/blob/42806049a7774a2bd316c958f5dcf01c6b5c56fa/src/PhpGenerator/Helpers.php#L60

### CODE REVIEW

File: src/Symfony/Component/Config/Builder/ConfigBuilderGenerator.php [hunk 1]
```diff
@@ -413,39 +413,43 @@ private function getComment(BaseNode $node): string
...
             }
 
             if ('' !== $default = $node->getDefaultValue()) {
-                $comment .= ' * @default '.(null === $default ? 'null' : var_export($default, true))."\n";
+                $comment .= '@default '.(null === $default ? 'null' : var_export($default, true))."\n";
             }
 
             if ($node instanceof EnumNode) {
-                $comment .= sprintf(' * @param ParamConfigurator|%s $value', implode('|', array_unique(array_map(fn ($a) => !$a instanceof \UnitEnum ? var_export($a, true) : '\\'.ltrim(var_export($a, true), '\\'), $node->getValues()))))."\n";
+                $comment .= sprintf('@param ParamConfigurator|%s $value', implode('|', array_unique(array_map(fn ($a) => !$a instanceof \UnitEnum ? var_export($a, true) : '\\'.ltrim(var_export($a, true), '\\'), $node->getValues()))))."\n";
```
Comment (GromNaN) [inline src/Symfony/Component/Config/Builder/ConfigBuilderGenerator.php:429]: When up-merging into 7.2, a backslash is added before `sprintf` by https://github.com/symfony/symfony/commit/6ce530c5e90397d88e3a76a56db266c74d651584#diff-2aaa94a5e0cdde514853eddaf724fb3724c0501ddc5285af115bc1fe9c04d7ce

File: src/Symfony/Component/Config/Builder/ConfigBuilderGenerator.php [hunk 2]
```diff
@@ -413,39 +413,43 @@ private function getComment(BaseNode $node): string
     {
         $comment = '';
         if ('' !== $info = (string) $node->getInfo()) {
-            $comment .= ' * '.$info."\n";
+            $comment .= $info."\n";
```
Comment (GromNaN) [inline src/Symfony/Component/Config/Builder/ConfigBuilderGenerator.php:416]: If we want a smaller fix applied only to the `$info` part, it would be:
```php
$comment .= ' * '.str_replace("\n", "\n * ", $info)."\n";
```

**Comment by alexandre-daubois** [comment]
Could we edit existing fixtures to cover this (like `src/Symfony/Component/Config/Tests/Builder/Fixtures/AddToList.php` or any of the same folder) ?

**Comment by GromNaN** [comment]
Thanks @alexandre-daubois, I hadn't found where to test.

**Review by alexandre-daubois — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @GromNaN.
