### PR TITLE
[Security][SecurityBundle] User authorization checker

### LINKED ISSUE #43372: Using isGranted() without a Session
**Description**
`isGranted()` assumes that it's checking against the currently logged in user. It would be great to be able to use something similar to check against another user or during times when there isn't a session (cronjobs/commands, message queue, etc.).

I would see this as a `userIsGranted()` function to make a distinction. There's cases we'd have to consider, such as if `IS_AUTHENTICATED_*` is used in conjunction with this method, as those are based on sessions. Return false, or throw a logic exception, etc.

Having this functionality would allow for removing the dependency on sessions entirely for services reducing the number of issues that come up during a project because some underlying function was session dependent.

I'm assuming we'd also want to create a new Token class to represent checking against a non-logged in user.

**Example**
Checking to see if you could assign another user to review an article:

```php
$security->userIsGranted($reviewer, ArticleVoter::REVIEW, $article);
```

### PR DESCRIPTION
**Pull request by natewiebe13**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #43372
| License       | MIT
| Doc PR        | https://github.com/symfony/symfony-docs/pull/18033

`isGranted()` assumes that it's checking against the currently logged in user. This provides the same functionality to check against a user during times when there isn't a session (cronjobs/commands, message queue, etc.) or for a different user than the one logged in.

Having this functionality allows for removing the dependency on sessions entirely for services reducing the number of issues that come up during a project because some underlying function was session dependent.

### CODE REVIEW

File: src/Symfony/Component/Security/Core/Tests/Authentication/Token/UserAuthorizationCheckerTokenTest.php [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+use PHPUnit\Framework\TestCase;
+use Symfony\Component\Security\Core\Authentication\Token\UserAuthorizationCheckerToken;
+use Symfony\Component\Security\Core\User\InMemoryUser;
+
+class UserAuthorizationCheckerTokenTest extends TestCase
+{
+    public function testConstructor()
+    {
+        $token = new UserAuthorizationCheckerToken($user = new InMemoryUser('foo', 'bar', ['ROLE_FOO']), ['ROLE_FOO']);
+        $this->assertEquals(['ROLE_FOO'], $token->getRoleNames());
```
Comment (OskarStark) [inline src/Symfony/Component/Security/Core/Tests/Authentication/Token/UserAuthorizationCheckerTokenTest.php]: assertSame please whenever possible

File: src/Symfony/Component/Security/Core/Authentication/Token/UserAuthorizationCheckerToken.php [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+namespace Symfony\Component\Security\Core\Authentication\Token;
+
+use Symfony\Component\Security\Core\User\UserInterface;
+
+/**
+ * UserAuthorizationCheckerToken implements a token used for checking authorization.
+ *
+ * @author Nate Wiebe <nate@northern.co>
+ */
+class UserAuthorizationCheckerToken extends AbstractToken
```
Comment (derrabus) [inline src/Symfony/Component/Security/Core/Authentication/Token/UserAuthorizationCheckerToken.php]: This token implementation should be `@internal` because it's meant to be used by `UserAuthorizationChecker` only. We could also make it `final` for that matter.

File: src/Symfony/Component/Security/Core/Authentication/Token/UserAuthorizationCheckerToken.php [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+{
+    /**
+     * @param string[] $roles
+     */
+    public function __construct(UserInterface $user, array $roles = [])
+    {
+        parent::__construct($roles);
+
+        $this->setUser($user);
+    }
```
Comment (derrabus) [inline src/Symfony/Component/Security/Core/Authentication/Token/UserAuthorizationCheckerToken.php]: Why does the constructor have a `$roles` parameter? We always use the user's roles anyway.

```suggestion
    public function __construct(UserInterface $user)
    {
        parent::__construct($user->getRoles());

        $this->setUser($user);
    }
```

File: src/Symfony/Component/Security/Core/Authorization/UserAuthorizationChecker.php [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+     *
+     * @param mixed $attribute A single attribute to vote on (can be of any type, string and instance of Expression are supported by the core)
+     */
+    final public function userIsGranted(UserInterface $user, mixed $attribute, mixed $subject = null): bool
+    {
+        if (AuthenticatedVoter::IS_AUTHENTICATED_FULLY === $attribute
+            || AuthenticatedVoter::IS_AUTHENTICATED_REMEMBERED === $attribute
+            || AuthenticatedVoter::IS_AUTHENTICATED === $attribute
+            || AuthenticatedVoter::IS_IMPERSONATOR === $attribute
+            || AuthenticatedVoter::IS_REMEMBERED === $attribute) {
```
Comment (derrabus) [inline src/Symfony/Component/Security/Core/Authorization/UserAuthorizationChecker.php]:
```suggestion
            || AuthenticatedVoter::IS_REMEMBERED === $attribute
        ) {
```

File: src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+    {
+        $this->accessDecisionManager = $this->createMock(AccessDecisionManagerInterface::class);
+
+        $this->authorizationChecker = new UserAuthorizationChecker($this->accessDecisionManager);
+    }
+
+    /**
+     * @dataProvider isGrantedProvider
+     */
+    public function testIsGranted($decide)
```
Comment (derrabus) [inline src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php]:
```suggestion
    public function testIsGranted(bool $decide)
```

File: src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php [hunk 6]
```diff
@@ -0,0 +1,89 @@
...
+    {
+        $user = new InMemoryUser('username', 'password', ['ROLE_USER']);
+
+        $this->accessDecisionManager
+            ->expects($this->once())
+            ->method('decide')
```
Comment (derrabus) [inline src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php:42]: The test should make sure the right parameters are passed to the `decide()` method.

File: src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php [hunk 7]
```diff
@@ -0,0 +1,89 @@
...
+            ->with($this->isInstanceOf($token::class), $this->identicalTo([$attribute]))
+            ->willReturn(true);
+        $this->assertTrue($this->authorizationChecker->userIsGranted($token->getUser(), $attribute));
+    }
+
+    /**
+     * @dataProvider unsupportedAttributeProvider
+     */
+    public function testUnsupportedAttribute($attribute)
```
Comment (derrabus) [inline src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php]:
```suggestion
    public function testUnsupportedAttribute(string $attribute)
```

File: src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php [hunk 8]
```diff
@@ -0,0 +1,89 @@
...
+    {
+        $user = new InMemoryUser('username', 'password', ['ROLE_USER']);
+
+        $this->expectException(InvalidArgumentException::class);
+
+        $this->authorizationChecker->userIsGranted($user, $attribute);
+    }
+
+    public function unsupportedAttributeProvider()
```
Comment (derrabus) [inline src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php]:
```suggestion
    public function unsupportedAttributeProvider(): array
```

File: src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php [hunk 9]
```diff
@@ -0,0 +1,89 @@
...
+        $user = new InMemoryUser('username', 'password', ['ROLE_USER']);
+
+        $this->accessDecisionManager
+            ->expects($this->once())
+            ->method('decide')
+            ->willReturn($decide);
+        $this->assertSame($decide, $this->authorizationChecker->userIsGranted($user, 'ROLE_FOO'));
+    }
+
+    public function isGrantedProvider()
```
Comment (derrabus) [inline src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php]:
```suggestion
    public function isGrantedProvider(): array
```

File: src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php [hunk 10]
```diff
@@ -0,0 +1,89 @@
...
+use Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface;
+use Symfony\Component\Security\Core\Authorization\UserAuthorizationChecker;
+use Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter;
+use Symfony\Component\Security\Core\Exception\InvalidArgumentException;
+use Symfony\Component\Security\Core\User\InMemoryUser;
+
+class UserAuthorizationCheckerTest extends TestCase
+{
+    private $accessDecisionManager;
+    private $authorizationChecker;
```
Comment (derrabus) [inline src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php]:
```suggestion
    private AccessDecisionManagerInterface&MockObject $accessDecisionManager;
    private UserAuthorizationChecker $authorizationChecker;
```

File: src/Symfony/Component/Security/Core/Authorization/UserAuthorizationChecker.php [hunk 11]
```diff
@@ -0,0 +1,50 @@
...
+use Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter;
+use Symfony\Component\Security\Core\Exception\InvalidArgumentException;
+use Symfony\Component\Security\Core\User\UserInterface;
+
+/**
+ * UserAuthorizationChecker is used to check user authorization without a session.
+ *
+ * @author Nate Wiebe <nate@northern.co>
+ */
+class UserAuthorizationChecker
```
Comment (derrabus) [inline src/Symfony/Component/Security/Core/Authorization/UserAuthorizationChecker.php]: We have an interface for `AuthorizationChecker`. Should we do the same for `UserAuthorizationChecker`? This would also allow us to finalize this class.

**Review by derrabus — CHANGES_REQUESTED** [review]
Thank you for your PR.

File: src/Symfony/Bundle/SecurityBundle/Resources/config/security.php [hunk 12]
```diff
@@ -65,6 +66,12 @@
             ])
         ->alias(AuthorizationCheckerInterface::class, 'security.authorization_checker')
 
+        ->set('security.user_authorization_checker', UserAuthorizationChecker::class)
+            ->args([
+                service('security.access.decision_manager'),
+            ])
+        ->alias(UserAuthorizationChecker::class, 'security.user_authorization_checker')
```
Comment (derrabus) [inline src/Symfony/Bundle/SecurityBundle/Resources/config/security.php]: We need a functional test that makes sure that the service is wired properly. We should also have a test that makes sure, the new `UserAuthorizationChecker` checks the permissions of the given user instead of the authenticated user.

File: src/Symfony/Component/Security/Core/Authorization/UserAuthorizationChecker.php [hunk 13]
```diff
@@ -0,0 +1,50 @@
...
+     * @param mixed $attribute A single attribute to vote on (can be of any type, string and instance of Expression are supported by the core)
+     */
+    final public function userIsGranted(UserInterface $user, mixed $attribute, mixed $subject = null): bool
+    {
+        if (AuthenticatedVoter::IS_AUTHENTICATED_FULLY === $attribute
+            || AuthenticatedVoter::IS_AUTHENTICATED_REMEMBERED === $attribute
+            || AuthenticatedVoter::IS_AUTHENTICATED === $attribute
+            || AuthenticatedVoter::IS_IMPERSONATOR === $attribute
+            || AuthenticatedVoter::IS_REMEMBERED === $attribute) {
+            throw new InvalidArgumentException(sprintf('"%s" cannot decide on attribute "%s" as it requires checking the session. Use "%s" instead.', self::class, $attribute, AuthorizationCheckerInterface::class));
```
Comment (stof) [inline src/Symfony/Component/Security/Core/Authorization/UserAuthorizationChecker.php]: This check should probably be done in the AuthenticatedVoter when passing it a UserAuthorizationCheckerToken instead of making a special case here (which would not work if a custom voter uses a delegated check on the authentication level as part of their logic, as this would pass the UserAuthorizationCheckerToken to the AuthenticatedVoter without going through this UserAuthorizationChecker)

File: src/Symfony/Component/Security/Core/Security.php [hunk 14]
```diff
@@ -79,6 +79,15 @@ public function isGranted(mixed $attributes, mixed $subject = null): bool
             ->isGranted($attributes, $subject);
     }
 
+    /**
+     * Checks if the attributes are granted against the user and optionally supplied subject.
```
Comment (stof) [inline src/Symfony/Component/Security/Core/Security.php]: this should explicitly document the differences with `isGranted()` IMO, to make its limitation clear

File: src/Symfony/Component/Security/Core/Authentication/Token/UserAuthorizationCheckerToken.php (hunk 2 above)
Comment (stof) [reply src/Symfony/Component/Security/Core/Authentication/Token/UserAuthorizationCheckerToken.php]: If we make the token class internal, we should at least have a non-internal marker interface to distinguish special tokens that don't correlate to the current logged in user, to allow voters to distinguish them in case they cannot support that case (the special case done for AuthenticatedVoter permissions might also have an equivalent in a 2FA voter for instance). Otherwise, voters will have to do a `$token instanceof UserAuthorizationCheckerToken` check, which will get warned about if the class is internal (because it would rely on an internal API)

Comment (derrabus) [reply src/Symfony/Component/Security/Core/Authentication/Token/UserAuthorizationCheckerToken.php]: Good point.

File: src/Symfony/Component/Security/Core/Authentication/Token/UserAuthorizationCheckerToken.php (hunk 3 above)
Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Authentication/Token/UserAuthorizationCheckerToken.php]: As to why, it was to line up closer to the other tokens, but it makes more sense to just grab from the user instead. Will be updated with the next push.

File: src/Symfony/Component/Security/Core/Authorization/UserAuthorizationChecker.php (hunk 13 above)
Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Authorization/UserAuthorizationChecker.php]: Next push will include the voter abstaining if the token is marked with the interface. I feel like it's probably still useful to know if you're using the checker improperly, rather than getting unexpected results. Any concerns with leaving this check in as well?

File: src/Symfony/Component/Security/Core/Security.php (hunk 14 above)
Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Security.php]: Updated, is this what you were looking for?

File: src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php (hunk 6 above)
Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php:42]: Updated.

File: src/Symfony/Component/Security/Core/Authentication/Token/UserAuthorizationCheckerToken.php (hunk 2 above)
Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Authentication/Token/UserAuthorizationCheckerToken.php]: Went with `OfflineTokenInterface`. Let me know if you have a better name.

File: src/Symfony/Component/Security/Core/Authorization/UserAuthorizationChecker.php (hunk 11 above)
Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Authorization/UserAuthorizationChecker.php]: Updated.

File: src/Symfony/Component/Security/Core/Authorization/UserAuthorizationChecker.php (hunk 13 above)
Comment (stof) [reply src/Symfony/Component/Security/Core/Authorization/UserAuthorizationChecker.php]: I'm not sure abstaining is always the right answer either though (the final decision won't ever be an abstain)

Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Authorization/UserAuthorizationChecker.php]: True, I guess technically since the token is internal, it really shouldn't get this far. I'm good with moving the exception into the voter.

Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Authorization/UserAuthorizationChecker.php]: Updated

File: src/Symfony/Bundle/SecurityBundle/Resources/config/security.php (hunk 12 above)
Comment (natewiebe13) [reply src/Symfony/Bundle/SecurityBundle/Resources/config/security.php]: Added a functional test for checking that the correct user is being checked against. I don't see a test for autowiring for the current `UserAuthorizationChecker`. Do you have an example of what you're wanting for that test?

File: src/Symfony/Component/Security/Core/Authorization/UserAuthorizationChecker.php [hunk 15]
```diff
@@ -0,0 +1,33 @@
...
+ * @author Nate Wiebe <nate@northern.co>
+ */
+final class UserAuthorizationChecker implements UserAuthorizationCheckerInterface
+{
+    private AccessDecisionManagerInterface $accessDecisionManager;
+
+    public function __construct(AccessDecisionManagerInterface $accessDecisionManager)
+    {
+        $this->accessDecisionManager = $accessDecisionManager;
+    }
```
Comment (derrabus) [inline src/Symfony/Component/Security/Core/Authorization/UserAuthorizationChecker.php]:
```suggestion
    public function __construct(
        private readonly AccessDecisionManagerInterface $accessDecisionManager,
    ) {
    }
```

Let's use CPP whenever we can.

File: src/Symfony/Bundle/SecurityBundle/Resources/config/security.php (hunk 12 above)
Comment (derrabus) [reply src/Symfony/Bundle/SecurityBundle/Resources/config/security.php]: I didn't say "_auto_-wiring". 😉  Your test is fine. 👍🏻

Comment (HeahDude) [inline src/Symfony/Bundle/SecurityBundle/Resources/config/security.php]:
```suggestion
        ->alias(UserAuthorizationCheckerInterface::class, 'security.user_authorization_checker')
```

**Review by HeahDude — COMMENTED** [review]
Nice feature, thanks!

File: src/Symfony/Bundle/SecurityBundle/Resources/config/security.php (hunk 12 above)
Comment (natewiebe13) [reply src/Symfony/Bundle/SecurityBundle/Resources/config/security.php]: Nice catch

**Comment by VincentLanglet** [comment]
This would be a great feature. What is missing to this PR @natewiebe13 @derrabus @stof ?

**Comment by derrabus** [comment]
> What is missing to this PR

Another round of reviews, I suppose. I'd very much like to see this feature shipped as well.

File: src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php [hunk 16]
```diff
@@ -0,0 +1,66 @@
...
+
+        $this->authorizationChecker = new UserAuthorizationChecker($this->accessDecisionManager);
+    }
+
+    /**
+     * @dataProvider isGrantedProvider
+     */
+    public function testIsGranted(bool $decide)
+    {
+        $token = new UserAuthorizationCheckerToken(new InMemoryUser('username', 'password', ['ROLE_USER']));
```
Comment (derrabus) [inline src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php]: The test does not need the token object. You merely create it just to unwrap the user from it later on.

File: src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php [hunk 17]
```diff
@@ -0,0 +1,66 @@
...
+
+        $this->accessDecisionManager
+            ->expects($this->once())
+            ->method('decide')
+            ->with($this->isInstanceOf($token::class), $this->identicalTo(['ROLE_FOO']))
```
Comment (derrabus) [inline src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php]: Sorry if I'm picky here, but this assertion still does not check if the ADM is called with the right user. Instead it checks for the token class which is somewhat irrelevant for this functionality.

**Review by derrabus — COMMENTED** [review]
Looks good, just two minor remarks.

File: src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php (hunk 16 above)
Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php]: Updated

File: src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php (hunk 17 above)
Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php]: Updated, I believe it should now better reflect what we actually want to verify.

**Comment by VincentLanglet** [comment]
@natewiebe13 There are conflict on the branch. Do you have time to solve them ?

**Comment by natewiebe13** [comment]
> @natewiebe13 There are conflict on the branch. Do you have time to solve them ?

Resolved!

**Comment by VincentLanglet** [comment]
> > @natewiebe13 There are conflict on the branch. Do you have time to solve them ?
> 
> Resolved!

Nice, I think it just need a @derrabus review then ! :)

File: src/Symfony/Component/Security/Core/Security.php [hunk 18]
```diff
@@ -73,6 +73,16 @@ public function isGranted(mixed $attributes, mixed $subject = null): bool
...
+     * This should be used over isGranted() when checking permissions against a user that is not currently logged in.
+     */
+    public function userIsGranted(UserInterface $user, mixed $attributes, mixed $subject = null): bool
```
Comment (jdreesen) [inline src/Symfony/Component/Security/Core/Security.php]: Here the parameter is called `$attributes`, while in `UserAuthorizationCheckerInterface` it is called `$attribute` (singular) and the `UserAuthorizationChecker` wraps it in an array. Is that correct?

Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Security.php]: This was to match the `isGranted()` function that already exists. Looking at the `AuthorizationCheckerInterface`, the parameter name was singular. I've updated both functions to use singular.

@derrabus looking at the [BC promise](https://symfony.com/doc/current/contributing/code/bc.html) updating the param name isn't considered a BC break, but let me know if you'd like me to revert the param name change for `isGranted()`. For the new function, I agree that it makes sense to use the singular.

Comment (jdreesen) [reply src/Symfony/Component/Security/Core/Security.php]: I see. The PhpDoc of both methods probably also needs to be updated, as it still says "attributes are".

Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Security.php]: Updated.

Comment (derrabus) [reply src/Symfony/Component/Security/Core/Security.php]: > @derrabus looking at the [BC promise](https://symfony.com/doc/current/contributing/code/bc.html) updating the param name isn't considered a BC break, but let me know if you'd like me to revert the param name change for `isGranted()`. For the new function, I agree that it makes sense to use the singular.

I'd revert that. We can debate renaming that parameter in another PR, but for this one, this is just an unnecessary and unrelated change. Please let's keep this PR focused.

File: src/Symfony/Component/Security/Core/Security.php [hunk 19]
```diff
@@ -65,12 +66,22 @@ public function getUser(): ?UserInterface
...
+
+    /**
+     * Checks if the attribute is granted against the user and optionally supplied subject.
+     * This should be used over isGranted() when checking permissions against a user that is not currently logged in.
+     */
+    public function userIsGranted(UserInterface $user, mixed $attribute, mixed $subject = null): bool
+    {
+        return $this->container->get('security.user_authorization_checker')
+            ->userIsGranted($user, $attribute, $subject);
     }
```
Comment (derrabus) [inline src/Symfony/Component/Security/Core/Security.php]: The `Security` class in the SecurityCore component is supposed to die. It only exists for BC. There's a new `Security` class in SecurityBundle which is meant to be the replacement. I think, if we introduce a new method, it should go into the new class.

File: src/Symfony/Component/Security/Core/Security.php (hunk 18 above)
Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Security.php]: Sounds good @derrabus, on that note, would it be preferred to use singlar or plural in the new function (`userIsGranted()`)? The decision would really be around consistency vs accuracy.

Comment (derrabus) [reply src/Symfony/Component/Security/Core/Security.php]: No, let's keep the singular for the new method.

**Comment by OskarStark** [comment]
Can you please open a PR in `symfony/symfony-docs` repository and update the CHANGELOG? Thanks

**Comment by natewiebe13** [comment]
> Can you please open a PR in `symfony/symfony-docs` repository and update the CHANGELOG? Thanks

Done.

**Review by kbond — COMMENTED** [review]
Great feature!

File: src/Symfony/Bundle/SecurityBundle/Security.php [hunk 20]
```diff
@@ -36,7 +37,7 @@
  *
  * @final
  */
-class Security extends LegacySecurity
+class Security extends LegacySecurity implements UserAuthorizationCheckerInterface
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/SecurityBundle/Security.php]: This class should definitely implement ServiceSubscriberInterface also, to describe what it consumes from the injected container. Can you update it to do so?

File: src/Symfony/Bundle/SecurityBundle/CHANGELOG.md [hunk 21]
```diff
@@ -11,6 +11,7 @@ CHANGELOG
  * Make `Security::login()` return the authenticator response
  * Deprecate the `security.firewalls.logout.csrf_token_generator` config option, use `security.firewalls.logout.csrf_token_manager` instead
  * Make firewalls event dispatcher traceable on debug mode
+ * Add `Security::userIsGranted()` to test user authorization without relying on the session. For example, users not currently logged in, or while processing a message from a message queue.
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/SecurityBundle/CHANGELOG.md]: no final dot

File: src/Symfony/Bundle/SecurityBundle/Security.php [hunk 22]
```diff
@@ -117,6 +118,16 @@ public function logout(bool $validateCsrfToken = true): ?Response
         return $logoutEvent->getResponse();
     }
 
+    /**
+     * Checks if the attribute is granted against the user and optionally supplied subject.
+     * This should be used over isGranted() when checking permissions against a user that is not currently logged in.
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/SecurityBundle/Security.php]: missing blank line before

File: src/Symfony/Bundle/SecurityBundle/Security.php (hunk 20 above)
Comment (natewiebe13) [reply src/Symfony/Bundle/SecurityBundle/Security.php]: Added.

File: src/Symfony/Bundle/SecurityBundle/Security.php [hunk 23]
```diff
@@ -151,4 +163,11 @@ private function getAuthenticator(?string $authenticatorName, string $firewallNa
 
         return $firewallAuthenticatorLocator->get($authenticatorId);
     }
+
+    public static function getSubscribedServices(): array
+    {
+        return [
+            'security.user_authorization_checker' => UserAuthorizationCheckerInterface::class,
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/SecurityBundle/Security.php:209]: this should list them all :)
see `service_locator()` in `services.php`

**Review by nicolas-grekas — COMMENTED** [review]
When reviewing the code, I feel like all this can be reduced to using 
`$accessDecisionManager->decide(new UserAuthorizationCheckerToken($user), [$attribute], $subject)`.

What about removing everything but the token class? (and maybe name it `OfflineToken` and remove the interface also, while making it non-final+non-internal?)

File: src/Symfony/Bundle/SecurityBundle/Security.php (hunk 23 above)
Comment (natewiebe13) [reply src/Symfony/Bundle/SecurityBundle/Security.php:209]: I think I've done this correctly.

**Comment by natewiebe13** [comment]
> When reviewing the code, I feel like all this can be reduced to using `$accessDecisionManager->decide(new UserAuthorizationCheckerToken($user), [$attribute], $subject)`.
> 
> What about removing everything but the token class? (and maybe name it `OfflineToken` and remove the interface also, while making it non-final+non-internal?)

Just so I'm on the same page, you're suggestion to just remove the token interface correct? Or are you suggesting to remove more than that?

**Comment by VincentLanglet** [comment]
> When reviewing the code, I feel like all this can be reduced to using `$accessDecisionManager->decide(new UserAuthorizationCheckerToken($user), [$attribute], $subject)`.
> 
> What about removing everything but the token class? (and maybe name it `OfflineToken` and remove the interface also, while making it non-final+non-internal?)

Personally I never used a call 
```
$accessDecisionManager->decide()
```
and always used one of
```
$security->isGranted()
$authorizationChecker->isGranted()
```
so I would feel more natural having a service with a `isGranted`-like method, rather than having to play with token and access decision manager.

**Comment by natewiebe13** [comment]
I would tend to agree. Once we have this in 6.3, we plan to use this exclusively and deprecate using `isGranted()` outside of controllers to avoid issues with code expecting a session where there isn't one. Having the interface will allow us to quickly migrate code while not requiring the full security bundle, and the bundle class having the helper function is great when we're already using other helpers.

**Comment by natewiebe13** [comment]
@derrabus wondering what next steps are here.

File: src/Symfony/Bundle/SecurityBundle/Security.php [hunk 24]
```diff
@@ -117,6 +125,17 @@ public function logout(bool $validateCsrfToken = true): ?Response
         return $logoutEvent->getResponse();
     }
 
+    /**
+     * Checks if the attribute is granted against the user and optionally supplied subject.
+     *
+     * This should be used over isGranted() when checking permissions against a user that is not currently logged in.
```
Comment (94noni) [inline src/Symfony/Bundle/SecurityBundle/Security.php]:
```suggestion
     * This should be used over isGranted() when checking permissions against a user that is not currently logged in or a cli context for example.
```

File: src/Symfony/Component/Security/Core/Authentication/Token/OfflineTokenInterface.php [hunk 25]
```diff
@@ -0,0 +1,21 @@
...
+ */
+
+namespace Symfony\Component\Security\Core\Authentication\Token;
+
+/**
+ * Interface used for marking tokens that do not represent the currently logged-in user.
+ *
+ * @author Nate Wiebe <nate@northern.co>
+ */
+interface OfflineTokenInterface extends TokenInterface
```
Comment (94noni) [inline src/Symfony/Component/Security/Core/Authentication/Token/OfflineTokenInterface.php:19]: the word offline is weird as first PR read

- AnonymousToken?
- UnknownToken?
- UnawareToken?

File: src/Symfony/Component/Security/Core/Authorization/UserAuthorizationCheckerInterface.php [hunk 26]
```diff
@@ -0,0 +1,29 @@
...
+ * Interface is used to check user authorization without a session.
+ *
+ * @author Nate Wiebe <nate@northern.co>
+ */
+interface UserAuthorizationCheckerInterface
+{
+    /**
+     * Checks if the attribute is granted against the user and optionally supplied subject.
+     *
+     * @param mixed $attribute A single attribute to vote on (can be of any type, string and instance of Expression are supported by the core)
```
Comment (94noni) [inline src/Symfony/Component/Security/Core/Authorization/UserAuthorizationCheckerInterface.php:26]: Cant use union type here?

File: src/Symfony/Bundle/SecurityBundle/Security.php (hunk 24 above)
Comment (natewiebe13) [reply src/Symfony/Bundle/SecurityBundle/Security.php]: Added similar wording

File: src/Symfony/Component/Security/Core/Authentication/Token/OfflineTokenInterface.php (hunk 25 above)
Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Authentication/Token/OfflineTokenInterface.php:19]: I feel like offline is still the most understandable word here, but open to suggestions. Token in my head is the representation of the user, and in this context they would be offline as far as the app is concerned. I could maybe see something like `SessionlessTokenInterface` or `StatelessTokenInterface`, but then that might get confused with stateless firewalls, which is different.

File: src/Symfony/Component/Security/Core/Authorization/UserAuthorizationCheckerInterface.php (hunk 26 above)
Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Authorization/UserAuthorizationCheckerInterface.php:26]: This matches `AuthorizationCheckerInterface`. Looking at how it's used, it does support multiple types, also depending on how people are currently using the decision maker, it might extend outside of a simple string or Expression. I'm thinking this might be the most appropriate for now.

**Comment by natewiebe13** [comment]
Also to add on if this should just be a token or should include the `userIsGranted()` method, I do plan on following this up with a twig function as well, which I feel the twig function shouldn't call the ADM directly. Using the authorization checker instead is a better approach imo

**Review by derrabus — APPROVED** [review]
LGTM after a rebase to solve conflicts.

File: src/Symfony/Component/Security/Core/Authentication/Token/OfflineTokenInterface.php (hunk 25 above)
Comment (HeahDude) [reply src/Symfony/Component/Security/Core/Authentication/Token/OfflineTokenInterface.php:19]: `RuntimeTokenInterface`?

File: src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php [hunk 27]
```diff
@@ -0,0 +1,70 @@
...
+        $this->accessDecisionManager
+            ->expects($this->once())
+            ->method('decide')
+            ->with($this->callback(fn (UserAuthorizationCheckerToken $token): bool => $user === $token->getUser()), $this->identicalTo(['ROLE_FOO']))
+            ->willReturn($decide);
+
+        $this->assertSame($decide, $this->authorizationChecker->userIsGranted($user, 'ROLE_FOO'));
+    }
+
+    public function isGrantedProvider(): array
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Core/Tests/Authorization/UserAuthorizationCheckerTest.php]:
```suggestion
    public static function isGrantedProvider(): array
```

File: src/Symfony/Component/Security/Core/Tests/Authorization/Voter/AuthenticatedVoterTest.php [hunk 28]
```diff
@@ -85,6 +87,29 @@ public function testSupportsType()
...
+    public function testOfflineToken(string $attribute)
+    {
+        $voter = new AuthenticatedVoter(new AuthenticationTrustResolver());
+
+        $this->expectException(InvalidArgumentException::class);
+
+        $voter->vote($this->getToken('offline'), null, [$attribute]);
+    }
+
+    public function unsupportedOfflineAttributeProvider(): array
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Core/Tests/Authorization/Voter/AuthenticatedVoterTest.php]:
```suggestion
    public static function unsupportedOfflineAttributeProvider(): array
```

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Security/Core/Authentication/Token/OfflineTokenInterface.php (hunk 25 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Security/Core/Authentication/Token/OfflineTokenInterface.php:19]: I'm personally fine with `OfflineTokenInterface`

**Comment by natewiebe13** [comment]
@derrabus rebased and conflicts resolved

File: src/Symfony/Component/Security/Core/Authentication/Token/OfflineTokenInterface.php (hunk 25 above)
Comment (HeahDude) [reply src/Symfony/Component/Security/Core/Authentication/Token/OfflineTokenInterface.php:19]: `OfflineTokenInterface` implies no connection at all, which could be wrong.
Use case: an admin logged in during a request, sends mails synchronously to a list of users, and the email template displays links depending on permissions of the recipient user.

File: src/Symfony/Component/Security/Core/Authorization/Voter/AuthenticatedVoter.php [hunk 29]
```diff
@@ -46,6 +48,10 @@ public function vote(TokenInterface $token, mixed $subject, array $attributes):
             return VoterInterface::ACCESS_GRANTED;
         }
 
+        if ($token instanceof OfflineTokenInterface) {
```
Comment (stof) [inline src/Symfony/Component/Security/Core/Authorization/Voter/AuthenticatedVoter.php]: this should not be done here. It should only be done when we identify an attribute on which we would not abstain. Otherwise, this voter would prevent any offline check that would be supported by a listener with a lower priority.

This must go inside the loop, after the initial checking for supported attributes.

File: src/Symfony/Component/Security/Core/Tests/Authorization/Voter/AuthenticatedVoterTest.php [hunk 30]
```diff
@@ -85,6 +87,29 @@ public function testSupportsType()
         $this->assertTrue($voter->supportsType(get_debug_type(new \stdClass())));
     }
 
+    /**
+     * @dataProvider unsupportedOfflineAttributeProvider
+     */
+    public function testOfflineToken(string $attribute)
```
Comment (stof) [inline src/Symfony/Component/Security/Core/Tests/Authorization/Voter/AuthenticatedVoterTest.php]: We should add 2 other tests for offline tokens besides the test covering the unsupported case:

- 1 test for `PUBLIC_ACCESS` being granted
- 1 test for an unsupported attribute being abstained.

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Security/Core/Authentication/Token/OfflineTokenInterface.php (hunk 25 above)
Comment (sstok) [reply src/Symfony/Component/Security/Core/Authentication/Token/OfflineTokenInterface.php:19]: - RetrieveOnlyToken / ProvideOnlyToken
- RetrieverToken
- QueryToken (which could be a bit misleading)
- HolderToken
- DifferentUserToken

Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Authentication/Token/OfflineTokenInterface.php:19]: How about one of these?
- StatelessToken (I'm leaning towards this one if we change it)
- SessionlessToken
- UserRepresentationToken

File: src/Symfony/Component/Security/Core/Authorization/Voter/AuthenticatedVoter.php (hunk 29 above)
Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Authorization/Voter/AuthenticatedVoter.php]: @stof looking at your comment below, are you also suggesting to abstain rather than throw an invalid argument exception? 

Personally I feel like that could create confusion as to why access isn't being provided and not being able to see specifically why. The exception makes it more obvious that a mistake is being made, rather than the user not having permissions that you'd otherwise expect them to have.

For example, if some service function works fine during testing in a controller or some session based context, if you try to run that same function when there isn't a session, it's not clear as to what the issue is. If there's an exception, the developer would be able to more easily identify that they're misusing the system.

Thoughts?

**Review by 94noni — APPROVED** [review]

**Comment by VincentLanglet** [comment]
What's the status of this ? How to help ?
There are multiple approval and some unfinished discussions, this is not clear.

Thanks

**Comment by natewiebe13** [comment]
> What's the status of this ? How to help ? There are multiple approval and some unfinished discussions, this is not clear.

I'm not so sure. I just rebased to 7.1. I'm guessing the team was busy with the 7.0 release. But it would be great to get this merged for 7.1.

**Review by 94noni — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Friendly ping @stof is there any blocker ?

File: src/Symfony/Bundle/SecurityBundle/CHANGELOG.md [hunk 31]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+7.1
```
Comment (OskarStark) [inline src/Symfony/Bundle/SecurityBundle/CHANGELOG.md]:
```suggestion
7.2
```
as we are in feature freeze right now

File: src/Symfony/Component/Security/Core/Authorization/Voter/AuthenticatedVoter.php (hunk 29 above)
Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Authorization/Voter/AuthenticatedVoter.php]: @stof revisiting this I see what you're saying now, I've made the change for this.

**Comment by ozahorulia** [comment]
@stof is there any chance to proceed with this PR?

**Review by 94noni — APPROVED** [review]
Would love to see this land on 7.2 :)

**Review by jeremyjaouen — APPROVED** [review]

File: src/Symfony/Component/Security/Core/Authentication/Token/OfflineTokenInterface.php (hunk 25 above)
Comment (mleczakm) [reply src/Symfony/Component/Security/Core/Authentication/Token/OfflineTokenInterface.php:19]: SessionlessToken sounds best to me.

**Comment by natewiebe13** [comment]
Rebased for 7.3 :crossed_fingers:

File: src/Symfony/Component/Security/Core/Tests/Authorization/Voter/AuthenticatedVoterTest.php (hunk 30 above)
Comment (natewiebe13) [reply src/Symfony/Component/Security/Core/Tests/Authorization/Voter/AuthenticatedVoterTest.php]: Added.

File: src/Symfony/Component/Security/Core/Authentication/Token/OfflineTokenInterface.php (hunk 25 above)
Comment (stof) [reply src/Symfony/Component/Security/Core/Authentication/Token/OfflineTokenInterface.php:19]: SessionLessToken and StatelessToken are both confusing, because the token of the current user stored in the TokenStorage might also be session-less (if your configure your firewall as stateless, it does not store the current token in the session).
Having 2 different meaning for `stateless` inside the component is a bad idea IMO.

I would also keep `OfflineTokenInterface` (it might not be a perfect name, but I don't have a better idea, and I still prefer it over other names suggested here).

**Review by stof — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
It took time, but here we go, this is in now. Thank you very much @natewiebe13.

File: src/Symfony/Bundle/SecurityBundle/Security.php [hunk 32]
```diff
@@ -148,6 +155,17 @@ public function logout(bool $validateCsrfToken = true): ?Response
         return $logoutEvent->getResponse();
     }
 
+    /**
+     * Checks if the attribute is granted against the user and optionally supplied subject.
+     *
+     * This should be used over isGranted() when checking permissions against a user that is not currently logged in or while in a CLI context.
+     */
+    public function userIsGranted(UserInterface $user, mixed $attribute, mixed $subject = null): bool
```
Comment (smnandre) [inline src/Symfony/Bundle/SecurityBundle/Security.php:163]: isUserGranted no ?

Comment (chalasr) [reply src/Symfony/Bundle/SecurityBundle/Security.php:163]: 👍 discussed internally, either this or `isGrantedForUser()`

Comment (xabbuh) [reply src/Symfony/Bundle/SecurityBundle/Security.php:163]: see #59214
