### PR TITLE
[Cache] Use the default expiry when saving (not when creating) items

### LINKED ISSUE #37263: [Cache] Incompatibility between ChainCache and ChainAdapter
**Symfony version(s) affected**: 4.4+

**Description**
Default lifetime handling in underlying caches of chain cache differs in ChainCache and ChainAdapter. It's not clear for me if this is bug or intended change.

**How to reproduce**  
Let assume that we have several caches with default lifetime is set and these caches are chained and chain cache has no default lifetime.

In case of ChainCache, when some value is saved its lifetime in underlying cache is set to corresponding cache default lifetime.

```
$cache1 = new ArrayCache(0);
$cache2 = new ArrayCache(2);

$chainCache = new ChainCache([$cache1, $cache2]);

$chainCache->set("key", "test");
```

Lifetime of "key" in $cache1 will be 0, and lifetime in $cache2 will be 2.

In case of ChainAdapter, lifetime of item in all underlying caches will be set to lifetime of first item found.

```
$adapter1 = new ArrayAdapter(0);
$cache1 = new Psr16Cache($adapter1);

$adapter2 = new ArrayAdapter(2);
$cache2 = new Psr16Cache($adapter2);

$chainCache = new Psr16Cache(new ChainAdapter([$adapter1, $adapter2]));

$chainCache->set("key", "test");
```

Lifetime of "key" in all caches will be 2.

```
$adapter1 = new ArrayAdapter(0);
$cache1 = new Psr16Cache($adapter1);

$adapter2 = new ArrayAdapter(2);
$cache2 = new Psr16Cache($adapter2);

$cache1->set("key", "test1");

$chainCache = new Psr16Cache(new ChainAdapter([$adapter1, $adapter2]));

$chainCache->set("key", "test");

```

Lifetime of "key" in all caches will be 0 because it was set in $cache1 earlier.

Here (https://github.com/philipp-kolesnikov/cachetest) is sample test. I'd expect that all test cases shall be passed.

### PR DESCRIPTION
**Pull request by philipp-kolesnikov**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no
| Tickets       | Fix #37263
| License       | MIT
| Doc PR        | 

This PR is for align expiration handling in ChainAdapter with ChainCache as proposed in #37263.

### CODE REVIEW

File: src/Symfony/Component/Cache/Adapter/TagAwareAdapter.php [hunk 1]
```diff
@@ -90,8 +89,7 @@ static function ($deferred) {
         $this->invalidateTags = \Closure::bind(
             static function (AdapterInterface $tagsAdapter, array $tags) {
                 foreach ($tags as $v) {
-                    $v->defaultLifetime = 0;
-                    $v->expiry = null;
+                    $v->expiry = 0;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Cache/Adapter/TagAwareAdapter.php:92]: Does "0" mean "infinity"? then there is a small glitch if one sets `0` as the timestamp for expiry, which will be confused with "infinity".
Should/can we use "-1" for this instead?

Comment (philipp-kolesnikov) [reply src/Symfony/Component/Cache/Adapter/TagAwareAdapter.php:92]: Yes, according to \Symfony\Component\Cache\Traits\AbstractTrait::doSave() "0" means "infinity". Also, $defaultLifetime = 0 in adapter's constructors mean the same. 

From a user point of view there are only ways to specify expiration:
- $defaultLifetime in adapter. And there 0 is already mean "infinity"
- CacheItemInterface::expiresAfter(). There 0 means number of seconds, so I guess it shouldn't confuse user.
- CacheItemInterface::expiresAt(). Its impossible to pass 0 here.

BTW, this is only place where $item->expiry is set to "0" explicitly, because we want to ignore adapter's default lifetime here if any is set when store tags.

Comment (nicolas-grekas) [reply src/Symfony/Component/Cache/Adapter/TagAwareAdapter.php:92]: > CacheItemInterface::expiresAt(). Its impossible to pass 0 here.

got it: the unix epoch time here is `0.0`, not `0`.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @philipp-kolesnikov.

**Comment by nicolas-grekas** [comment]
If you have some time before I do, I merged this in branch 5.1 but forgot some things apparently since tests fail:
https://travis-ci.org/github/symfony/symfony/jobs/707354918

**Comment by philipp-kolesnikov** [comment]
This patch will fix failed tests:
```
--- a/src/Symfony/Component/Cache/Adapter/ArrayAdapter.php
+++ b/src/Symfony/Component/Cache/Adapter/ArrayAdapter.php
@@ -205,7 +205,7 @@ class ArrayAdapter implements AdapterInterface, CacheInterface, LoggerAwareInter
             return false;
         }
         if (null === $expiry && 0 < $this->defaultLifetime) {
-            $expiry = microtime(true) + $this->defaultLifetime;
+            $expiry = $this->defaultLifetime;
             $expiry = $now + ($expiry > ($this->maxLifetime ?: $expiry) ? $this->maxLifetime : $expiry);
         } elseif ($this->maxLifetime && (null === $expiry || $expiry > $now + $this->maxLifetime)) {
             $expiry = $now + $this->maxLifetime;
```

**Comment by nicolas-grekas** [comment]
@philipp-kolesnikov thanks again, fixed.

**Comment by dmaicher** [comment]
@philipp-kolesnikov unfortunately this breaks invalidating items by tags for me. See https://github.com/symfony/symfony/issues/37667

The cause is this change: https://github.com/symfony/symfony/commit/49e9f3229c1441398f30d45393a1a99219b65f1c#diff-2fe2f12a84197b6987fbd5e133cd09aeR92

Do you have an idea whats happening or how to fix it? :blush: Thanks in advance.

**Comment by philipp-kolesnikov** [comment]
@dmaicher sorry for this regression. 
This should fix it
```
--- a/src/Symfony/Component/Cache/Adapter/ArrayAdapter.php
+++ b/src/Symfony/Component/Cache/Adapter/ArrayAdapter.php
@@ -124,6 +124,10 @@ class ArrayAdapter implements AdapterInterface, CacheInterface, LoggerAwareInter
         $value = $item["\0*\0value"];
         $expiry = $item["\0*\0expiry"];

+        if ($expiry === 0) {
+            $expiry = PHP_INT_MAX;
+        }
+
         if (null !== $expiry && $expiry <= microtime(true)) {
             $this->deleteItem($key);
```
I'll make a PR with test case from #37667 included.
