### PR TITLE
[PropertyAccessor] Add missing TypeError catch

### LINKED ISSUE #45199: [PropertyAccessor] Missing TypeError catch
### Symfony version(s) affected

6.0.2

### Description

I stumbled upon a TypeError: `Cannot assign string to property App\Api\Model\Request\CoordsCheckerRequest::$latitude of type float`.

Browsing the code, I see there is a TypeError -> InvalidArgumentException wrapper:
https://github.com/symfony/symfony/blob/6.0/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L206-L217

Looks like another one should be added there.

### How to reproduce

```php
class CoordsCheckerRequest {
    public float $longitude;
}

$accessor = new PropertyAccessor();
$request = new CoordsCheckerRequest();
$accessor->setValue($request, 'longitude', 'foo');
```

### Possible Solution

```php
if (preg_match('/^Cannot assign (\S+) to property \S+::\$\S+ of type (\S+)$/', $message, $matches)) {
    [, $actualType, $expectedType] = $matches;

    throw new InvalidArgumentException(sprintf('Expected argument of type "%s", "%s" given at property path "%s".', $expectedType, 'NULL' === $actualType ? 'null' : $actualType, $propertyPath), 0, $previous);
}
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by b1rdex**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #45199 
| License       | MIT

This bugfix wraps `TypeError: Cannot assign TYPE to property *::$* of type TYPE` with `InvalidArgumentException`.

### CODE REVIEW

**Review by fancyweb — APPROVED** [review]

File: src/Symfony/Component/PropertyAccess/Tests/Fixtures/TestClassTypedProperty.php [hunk 1]
```diff
@@ -0,0 +1,10 @@
+<?php
+
+declare(strict_types=1);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/PropertyAccess/Tests/Fixtures/TestClassTypedProperty.php]: should be removed and replaced by the license header, see other fixture files

Comment (b1rdex) [reply src/Symfony/Component/PropertyAccess/Tests/Fixtures/TestClassTypedProperty.php]: Fixed

**Comment by nicolas-grekas** [comment]
Thank you @b1rdex.
