### PR TITLE
[Form] Fix handling empty data in ValueToDuplicatesTransformer

### LINKED ISSUE #47013: RepeatedType does not respect the "options.empty_data" option
### Symfony version(s) affected

5.4.10

### Description

RepeatedType sets NULL even though the "empty_data" option is set to the empty string.

### How to reproduce

AccountType.php

```
<?php declare(strict_types = 1);

namespace App\Form\Type;

use App\Form\Data\AccountData;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AccountType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('password', RepeatedType::class, [
            'type' => PasswordType::class,
            'required' => false,
            'empty_data' => '', // Does not work
            'options' => [
                'empty_data' => '', // Does not work
            ],
        ]);

        // Hack: RepeatedType does not respect empty_data option
        //$builder->get('password')->addEventListener(FormEvents::SUBMIT, function (FormEvent $event): void {
        //    if (null === $event->getData()) {
        //        $event->setData('');
        //    }
        //});
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => AccountData::class,
        ]);
    }
}
```

AccountData.php

```
<?php declare(strict_types = 1);

namespace App\Form\Data;

class AccountData
{
    public string $password = '';
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #47013
| License       | MIT

The transformer receives the data of child forms that have already been through the transformation schema. If no custom view transformer was used on that child form the empty would already have been changed to null. Thus, receiving an empty string here means that the child form explicitly asked for it and the value must not be exchanged with null.

### CODE REVIEW

File: src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/ValueToDuplicatesTransformerTest.php [hunk 1]
```diff
@@ -70,7 +70,7 @@ public function testReverseTransformCompletelyEmpty()
             'c' => '',
         ];
 
-        $this->assertNull($this->transformer->reverseTransform($input));
+        $this->assertSame('', $this->transformer->reverseTransform($input));
```
Comment (alexandre-daubois) [inline src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/ValueToDuplicatesTransformerTest.php:73]:
```suggestion
        $this->assertEmpty($this->transformer->reverseTransform($input));
```
?

Comment (xabbuh) [reply src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/ValueToDuplicatesTransformerTest.php:73]: I prefer to be precise here. The fact that we were precise before made me spot that we had this test and reconsider if I really did a desired change.

**Review by yceruto — APPROVED** [review]
It makes sense to me. Simple, thanks!

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.
