### PR TITLE
[Messenger] Fix cloned TraceableStack not unstacking the stack independently 

### LINKED ISSUE #51564: cloned TraceableStack operates differently than StackMiddleware
### Symfony version(s) affected

6.x

### Description

The `StackMiddleware` has it's own state (`$offset` field), which changes during the operation flow. Therefore, if at some point of time we clone this stack, we get a completely different instance, which may be safely used.

The problem lies in the absence of `TraceableStack::__clone()` method . 
It is not possible to use cloned stack after main stack _has been iterated over_, since internally it references the same object.

See provided test for details.

### How to reproduce

Below two tests are provided. First passess (`StackMiddleware`), second fails (`TraceableStack`).

```php
class_exists(TraceableMiddleware::class);

final class TraceableStackCloneTest extends TestCase
{
    /** @dataProvider stackDataProvider */
    public function testClonedStackFramesFollowOriginalFrames(StackInterface $stack): void
    {
        $clonedStack = clone $stack;

        $nextFrame = $stack->next();
        $clonedStackNextFrame = $clonedStack->next();

        self::assertSame($nextFrame, $clonedStackNextFrame);
    }

    public function stackDataProvider(): array
    {
        $middlewareIterator = [
            $this->createMock(MiddlewareInterface::class),
            $this->createMock(MiddlewareInterface::class),
        ];

        return [
            [new StackMiddleware($middlewareIterator)], // passes
            [new TraceableStack(new StackMiddleware($middlewareIterator), $this->createMock(Stopwatch::class), 'command.bus', 'test')], // fails
        ];
    }
}
```

### Possible Solution

I guess adding `__clone` method to `TraceableStack` would fix the issue:

```php
    public function __clone(): void
    {
        $this->stack = clone $this->stack;
    }
```

### Additional Context

PHP version: 8.2.8
Symfony messenger version: 6.2.7

### PR DESCRIPTION
**Pull request by krciga22**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #51564
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Fixed a bug with cloned `TraceableStack` not unstacking the stack independently from the original due to the __clone() method not yet being implemented. Clones of `StackMiddleware` currently unstack the stack independently, but not `TraceableStack`.

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Review by maxbeckers — APPROVED** [review]

File: src/Symfony/Component/Messenger/Tests/Middleware/TraceableMiddlewareTest.php [hunk 1]
```diff
@@ -140,4 +141,92 @@ public function handle(Envelope $envelope, StackInterface $stack): Envelope
         $traced->handle($envelope, new StackMiddleware(new \ArrayIterator([null, $middleware])));
         $this->assertSame(1, $middleware->calls);
     }
+
+    public function testClonedTraceableStackUnstacksIndependently()
+    {
+        // import TraceableStack
+        class_exists(TraceableMiddleware::class);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Tests/Middleware/TraceableMiddlewareTest.php:148]: why is this needed?

Comment (krciga22) [reply src/Symfony/Component/Messenger/Tests/Middleware/TraceableMiddlewareTest.php:148]: @nicolas-grekas, I added this test method to test if a clone can be unstacked independently. I noticed that the existing method `testHandle()` in the same file does test `TraceableStack` unstacking via the use of `TraceableMiddleware`, but it doesn't test if a cloned version will unstack the stack independently, so I was thinking their could be a new test for that as well?

Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Tests/Middleware/TraceableMiddlewareTest.php:148]: I meant the class_exists check, why is it needed?

Comment (krciga22) [reply src/Symfony/Component/Messenger/Tests/Middleware/TraceableMiddlewareTest.php:148]: Right, without it I get the following error: 
`Error: Class 'Symfony\Component\Messenger\Middleware\TraceableStack' not found`

To fix the error, I tried to import `TraceableStack` at the top of the test file, but I can't get it to work because it's located within `TraceableMiddleware.php` instead of within its own file.

**Comment by nicolas-grekas** [comment]
Thank you @krciga22.
