### PR TITLE
[Messenger] Improve deadlock handling on `ack()` and `reject()`

### LINKED ISSUE #54103: [Messenger][Doctrine] Deadlock when deleting message
### Symfony version(s) affected

6.4

### Description

We started getting this deadlock recently. It has happened only twice so far under high load.

```
SQLSTATE[40P01]: Deadlock detected: 7 ERROR:  deadlock detected
DETAIL:  Process 221664 waits for ShareLock on transaction 59539641; blocked by process 221671.
Process 221671 waits for AccessExclusiveLock on tuple (77,27) of relation 16455 of database 16385; blocked by process 221605.
Process 221605 waits for ShareLock on transaction 59539646; blocked by process 221606.
Process 221606 waits for AccessExclusiveLock on tuple (69,16) of relation 16455 of database 16385; blocked by process 221664.
HINT:  See server log for query details.
CONTEXT:  while deleting tuple (69,16) in relation "messenger_messages"
Process 221664 waits for ShareLock on transaction 59539641;
blocked by process 221671.
```

Here are the queries for each process:

```
Process 221664 waits for ShareLock on transaction 59539641;
blocked by process 221671.

221671
SELECT m.* FROM messenger_messages m WHERE (m.queue_name = $1) AND (m.delivered_at is null OR m.delivered_at < $2) AND (m.available_at <= $3) ORDER BY available_at ASC LIMIT 1 FOR UPDATE

221605
SELECT m.* FROM messenger_messages m WHERE (m.queue_name = $1) AND (m.delivered_at is null OR m.delivered_at < $2) AND (m.available_at <= $3) ORDER BY available_at ASC LIMIT 1 FOR UPDATE

221606
SELECT m.* FROM messenger_messages m WHERE (m.queue_name = $1) AND (m.delivered_at is null OR m.delivered_at < $2) AND (m.available_at <= $3) ORDER BY available_at ASC LIMIT 1 FOR UPDATE

221664
DELETE FROM messenger_messages WHERE id = $1
```

Is something we can can improve in the Doctrine messenger implementation to detect when a deadlock exception occurs and retry the delete? Or is it possible to eliminate the potential for deadlocks entirely?

### How to reproduce

It is hard to reproduce this because it only happens with high volume.

### Possible Solution

Catch the deadlock exception and retry the delete. I am happy to make this PR if we think it is the right way to address the issue.

### Additional Context

I started to look at the existing code, and we handle deadlocks on `get()` but not on `reject()` or `ack()`.

### PR DESCRIPTION
**Pull request by jwage**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54103
| License       | MIT

We started getting this deadlock recently. It has happened only twice so far under high load.

```
SQLSTATE[40P01]: Deadlock detected: 7 ERROR:  deadlock detected
DETAIL:  Process 221664 waits for ShareLock on transaction 59539641; blocked by process 221671.
Process 221671 waits for AccessExclusiveLock on tuple (77,27) of relation 16455 of database 16385; blocked by process 221605.
Process 221605 waits for ShareLock on transaction 59539646; blocked by process 221606.
Process 221606 waits for AccessExclusiveLock on tuple (69,16) of relation 16455 of database 16385; blocked by process 221664.
HINT:  See server log for query details.
CONTEXT:  while deleting tuple (69,16) in relation "messenger_messages"
Process 221664 waits for ShareLock on transaction 59539641;
blocked by process 221671.
```

Here are the queries for each process:

```
Process 221664 waits for ShareLock on transaction 59539641;
blocked by process 221671.

221671
SELECT m.* FROM messenger_messages m WHERE (m.queue_name = $1) AND (m.delivered_at is null OR m.delivered_at < $2) AND (m.available_at <= $3) ORDER BY available_at ASC LIMIT 1 FOR UPDATE

221605
SELECT m.* FROM messenger_messages m WHERE (m.queue_name = $1) AND (m.delivered_at is null OR m.delivered_at < $2) AND (m.available_at <= $3) ORDER BY available_at ASC LIMIT 1 FOR UPDATE

221606
SELECT m.* FROM messenger_messages m WHERE (m.queue_name = $1) AND (m.delivered_at is null OR m.delivered_at < $2) AND (m.available_at <= $3) ORDER BY available_at ASC LIMIT 1 FOR UPDATE

221664
DELETE FROM messenger_messages WHERE id = $1
```

Open for discussion if this is the right way to handle this or not.

TODO:

- [x] Should there be a retry delay/exponential backoff/jitter? Retrying the failed delete that deadlocked immediately may not help.
- [x] Should `skip_locked` even be an option or should we always use skip locked?
- [x] Should we add `SKIP LOCKED` to the `FOR UPDATE`? It will reduce contention further. I was looking at how SolidQueue in Ruby On Rails handles this and it appears they use `SKIP LOCKED FOR UPDATE` https://github.com/basecamp/solid_queue/blob/fe57349a126efc381fe0adf4c1ec444bd8a4f53f/app/models/solid_queue/record.rb#L11

### CODE REVIEW

File: src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php [hunk 1]
```diff
@@ -210,6 +212,11 @@ public function get(): ?array
                 $sql .= ' '.$this->driverConnection->getDatabasePlatform()->getWriteLockSQL();
             }
 
+            if ($this->configuration['skip_locked']) {
+                // TODO add exception for drivers that do not support SKIP LOCKED
```
Comment (stof) [inline src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php]: to me, the right way to handle that cross-platform would be to add a feature in DBAL, similar to the `QueryBuilder::forUpdate` method, which would then make the DBAL platforms responsible for knowing whether this is supported (and the exact syntax as some platforms may use a different one). Or maybe as an argument passed to `forUpdate` if this is not an independent clause.

According to https://www.2ndquadrant.com/en/blog/what-is-select-skip-locked-for-in-postgresql-9-5/, SQL Server and DB2 have equivalent features with a different syntax than Postgresql and Oracle, which makes it a good candidate for the usage of the platform abstraction. MySQL does not support this feature. Support in sqlite is unknown to me.

Comment (jwage) [reply src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php]: I will see about getting this added to doctrine/dbal. Do you think it is worth having a bug fix version of this to reduce the chances of a deadlock and then replace it with the DBAL feature later once it is available in a separate change?

Comment (jwage) [reply src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php]: Looks like this was added here https://github.com/doctrine/dbal/pull/6191

I will modify the PR to use this.

Comment (jwage) [reply src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php]: Updated!

**Review by dunglas — APPROVED** [review]

**Comment by jwage** [comment]
After discussing this with Nicolas, I am going to remove the `skip_locked` option. We will always use `FOR UPDATE SKIP LOCKED`. In addition to that, I will make a change to add a delay to the retries and a jitter since we are getting deadlocks caused by contention, immediately retrying with no delay may cause more contention and cause us to repeatedly get deadlocks.

File: src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/DoctrineReceiver.php [hunk 2]
```diff
@@ -150,4 +146,32 @@ private function createEnvelopeFromData(array $data): Envelope
             new TransportMessageIdStamp($data['id'])
         );
     }
+
+    private function withRetryableExceptionRetry(callable $callable): void
```
Comment (jwage) [inline src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/DoctrineReceiver.php:150]: This code makes me think we need a `symfony/retry` component for handling retry logic. There are a few places in the symfony codebase that do this sort of thing now. And in my own application code, I have my own class that I use for handling retries. It would be cool to have one component to handle it.

Comment (alcohol) [reply src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/DoctrineReceiver.php:150]: Different contexts can make that complicated though maybe? There is https://github.com/symfony/http-client/blob/7.0/Retry/RetryStrategyInterface.php already for example (though of course tailored more specifically for the `HttpClient` component right now).

File: src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/DoctrineReceiver.php [hunk 3]
```diff
@@ -150,4 +146,32 @@ private function createEnvelopeFromData(array $data): Envelope
...
+        $multiplier = 2;
+        $jitter = 0.1;
+        $retries = 0;
+
+        retry:
+        try {
+            $callable();
+        } catch (RetryableException $exception) {
+            if (++$retries <= self::MAX_RETRIES) {
+                $delay = $delay * $multiplier;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/DoctrineReceiver.php]:
```suggestion
                $delay *=  $multiplier;
```

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php [hunk 4]
```diff
@@ -21,6 +21,7 @@
 use Doctrine\DBAL\Platforms\MySQLPlatform;
 use Doctrine\DBAL\Platforms\OraclePlatform;
 use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
+use Doctrine\DBAL\Query\ForUpdate\ConflictResolutionMode;
```
Comment (bendavies) [inline src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php:24]: as far as i can see, this was added in dbal 3.8, but we support versions prior to that
https://github.com/symfony/doctrine-messenger/blob/6.4/composer.json#L20C10-L20C23

Comment (bendavies) [reply src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php:24]: may have to manually construct the sql, as is done below with the `method_exists(QueryBuilder::class, 'forUpdate')` checks?

Comment (jwage) [reply src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php:24]: I will see. The sql for each platform is not as simple as just appending SKIP LOCKED. And in fact now that you point it out, I suspect this code might be broken for other platforms when you are using older versions of doctrine/dbal where the forUpdate() abstraction does not exist yet.

File: src/Symfony/Component/Messenger/Bridge/Doctrine/Tests/Transport/DoctrineReceiverTest.php [hunk 5]
```diff
@@ -128,6 +128,188 @@ public function testFind()
...
+            $deadlockException = new DeadlockException($driverException, null);
+        } else {
+            $deadlockException = new DeadlockException('Deadlock', $driverException);
+        }
+
+        $connection
+            ->expects($this->exactly(2))
+            ->method('ack')
+            ->with('1')
+            ->willReturnOnConsecutiveCalls(
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Bridge/Doctrine/Tests/Transport/DoctrineReceiverTest.php:168]: :boom: https://github.com/sebastianbergmann/phpunit/issues/5425

Comment (jdreesen) [reply src/Symfony/Component/Messenger/Bridge/Doctrine/Tests/Transport/DoctrineReceiverTest.php:168]: But the deprecation has been reversed, hasn't it?

See: https://github.com/sebastianbergmann/phpunit/commit/77ca5cb23d0db87215ef556aab6eb73e48e0746e

Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Bridge/Doctrine/Tests/Transport/DoctrineReceiverTest.php:168]: Really!? @sebastianbergmann maybe a comment on https://github.com/sebastianbergmann/phpunit/issues/5425 could be useful?

Comment (sebastianbergmann) [reply src/Symfony/Component/Messenger/Bridge/Doctrine/Tests/Transport/DoctrineReceiverTest.php:168]: https://github.com/sebastianbergmann/phpunit/issues/5425#issuecomment-1996588577

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jwage.
