### PR TITLE
[SecurityBundle] Make security schema deterministic

### LINKED ISSUE #57463: [SecurityBundle] libxml ≥ 2.12 reports invalid XSD
### Symfony version(s) affected

all

### Description

From [libxml 2.12 release announcement](https://discourse.gnome.org/t/libxml2-2-12-0-released/18063):

> Several bugs in the regex determinism checks were fixed. Invalid XML Schemas which previous versions erroneously accepted will now be rejected.

This impacts the `http://symfony.com/schema/dic/security` schema.

### How to reproduce

Run the SecurityBundle’s `XmlCompleteConfigurationTest` with an up-to-date PHP’s libxml version (check `php -i | grep libxml`):
```
./phpunit src/Symfony/Bundle/SecurityBundle/Tests/DependencyInjection/XmlCompleteConfigurationTest.php
```

It will fail/error with
```
[ERROR 3070] complex type 'provider': The content model is not determinist.
[ERROR 3070] complex type 'firewall': The content model is not determinist.
```

### Possible Solution

This issue comes from the fact `provider` and `firewall` must allow custom elements besides Symfony’s using `xsd:any`. Unfortunately that means that a parser cannot know if e.g. a `memory` provider comes from Symfony’s security schema or another.

Setting the `xsd:any`’s `namespace` attribute to `##other` fixes it (see https://www.w3.org/TR/xmlschema-0/#ref34), at the price that any custom provider or authenticator would need its own namespace. That being said, `xsd:any`’s `processContents="lax"` allows to not link it to an XSD.

```diff
<provider name="default">
-    <my-provider />
+    <custom:my-provider xmlns:custom="whatever" />
</provider>
```

The `XmlFileLoader` would have to be updated. Looking into it.

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #57463
| License       | MIT

Currently you cannot put a namespace on custom providers/authenticators because the `XmlFileLoader` will ignore every element whose namespace is not its parent’s. This means the only way to configure e.g. [SymfonyConnect](https://github.com/symfonycorp/connect)’s provider is

```xml
<provider name="connect_memory">
    <connect_memory>
        <user username="whatever">ROLE_ADMIN</user>
    </connect_memory>
</provider>
```

This requires providers and authenticators `xsd:any`’s `namespace` to be `##any`, which is no longer possible with libxml ≥ 2.12 (already available on Alpine 3.20 and Arch Linux e.g.) because it will report their content model as non-determinist.

> Unable to parse file "/srv/backend/config/packages/security.xml": [ERROR 3070] complex type 'provider': The content model is not determinist. (in file:////srv/backend/vendor/symfony/security-bundle/DependencyInjection/../Resources/config/schema//security-1.0.xsd - line 88, column 0)
[ERROR 3070] complex type 'firewall': The content model is not determinist. (in file:////srv/backend/vendor/symfony/security-bundle/DependencyInjection/../Resources/config/schema//security-1.0.xsd - line 134, column 0) in /srv/backend/config/packages/security.xml (which is being imported from "/srv/backend/src/Kernel.php").

As a result, any XML security config will fail to be loaded once libxml is updated.

Fixing this issue requires to change `xsd:any`s’ `namespace` to `##other` so that content models become deterministic.
A side-effect is that any custom providers/authenticators XML configuration will become invalid.

> Unable to parse file "/srv/backend/config/packages/security.xml": [ERROR 1871] Element '{http://symfony.com/schema/dic/security}connect_memory': This element is not expected. Expected is one of ( {http://symfony.com/schema/dic/security}chain, {http://symfony.com/schema/dic/security}memory, {http://symfony.com/schema/dic/security}ldap, ##other{http://symfony.com/schema/dic/security}* ). (in /srv/backend/public/ - line 13, column 0) in /srv/backend/config/packages/security.xml (which is being imported from "/srv/backend/src/Kernel.php").

To avoid a BC break this PR allows such errors to occur. A deprecation will have to be triggered on 7.2 for users to namespace their custom providers/authenticators elements, e.g.

```xml
<provider name="symfony_connect">
    <connect_memory xmlns="whatever">
        <user username="whatever">ROLE_ADMIN</custom:user>
    </connect_memory>
</provider>
```

Because custom providers/authenticators’ `processContents` is `lax` there won’t be any validation if the namespace has no schema. If it has, it will be better to provide it:

```diff
<srv:container xmlns="http://symfony.com/schema/dic/security"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns:srv="http://symfony.com/schema/dic/services"
+              xmlns:custom="whatever"
               xsi:schemaLocation="http://symfony.com/schema/dic/services
        https://symfony.com/schema/dic/services/services-1.0.xsd
        http://symfony.com/schema/dic/security
        https://symfony.com/schema/dic/security/security-1.0.xsd
+       whatever the/schema.xsd">

    <config>
        <provider name="symfony_connect">
-           <connect_memory xmlns="whatever">
-               <user username="whatever">ROLE_ADMIN</custom:user>
-           </connect_memory>
+           <custom:connect_memory>
+               <custom:user username="whatever">ROLE_ADMIN</custom:user>
+           </custom:connect_memory>
        </provider>
</srv:container>
```

### CODE REVIEW

**Comment by wouterj** [comment]
Uh-oh, this sounds like a really tricky situation. Breaking changes on an LTS version is a no-go, but we have to fix this somehow.

While searching for `xsd:any` in the code-base, as I'm sure more places are affected, I came across the Xliff 1.2 schema. It uses `<xsd:any maxOccurs="unbounded" minOccurs="0" namespace="##other" processContents="skip"/>` (processContent=skip is the relevant bit). Can you maybe verify if this could fix the issue in a BC way?

**Comment by MatTheCat** [comment]
I clarified the PR description: BC break would impact users configuring custom user providers and/or authenticators using XML, while the issue will impact users configuring security using XML (meaning e.g. `XmlCompleteConfigurationTest` will always fail once it is tested against an up-to-date libxml).

`processContents="skip"` is the same than `lax` when you don’t have an XSD so that wouldn’t change anything (confirmed after testing).

For completeness, I thought about two others solutions which would keep BC (in a sub-optimal way):

- remove all provider and authenticator types from the XSD. You wouldn’t get any validation or code autocompletion anymore but this would allow to keep `namespace="##any"` while being deterministic.
- disable validation in the `XmlFileLoader`. No validation => no validation error… Config would still be validated though.

**Comment by nicolas-grekas** [comment]
If there is no other choice than this BC break, then at least it happens at compile time so that it's going to be easy to spot, isn't it?
Then, we should make the solution super obvious, with clear explanations, before/after example, anything that can help make the situation actionable. Can you think of ways to do that?

**Comment by MatTheCat** [comment]
I clarified that the two other solutions I thought of (removing types from the XSD or disabling XML validation) would keep BC, so maybe they should be preferred?

If not, the simplest fix is to add a namespace to custom providers/authenticators, like

```diff
<provider name="default">
-    <my-provider />
+    <custom:my-provider xmlns:custom="my.custom.namespace" />
</provider>
```

Thanks to `processContents="lax"` you don’t need an XSD, but thanks to this PR you could now reference one:

```diff
+ xmlns:custom="my.custom.namespace"
  xsi:schemaLocation="http://symfony.com/schema/dic/services
     https://symfony.com/schema/dic/services/services-1.0.xsd
     http://symfony.com/schema/dic/security
-    https://symfony.com/schema/dic/security/security-1.0.xsd">
+    https://symfony.com/schema/dic/security/security-1.0.xsd
+    my.custom.namespace
+    /path/to/my.xsd

    <config>
        <provider name="default">
-          <my-provider />
+          <custom:my-provider  />
        </provider>
    </config>
</srv:container>
```

Don’t really know how to advertise this; I guess the upgrade guide and a blog post would be a good start. Surely there have been similar cases in the past?

**Comment by stof** [comment]
Given that any bundle can register extra settings for the security-bundle configuration (it has an extension config) and we were not requiring a custom namespace until now (and they probably never documented using one), I don't think we can require one (especially not in a patch version of an old LTS)

**Comment by wouterj** [comment]
I'm leaning towards going for "remove all provider and authenticator types from the XSD". This means we'll loose validation and autocompletion of build-in user provider configuration, but it is not a BC break.

Then, maybe we can find a nice upgrade path to reintroduce this in Symfony 8 (e.g. first deprecating custom user providers/authenticators without namespace?).

**Comment by stof** [comment]
note that we don't loose all validation. We loose the XSD-based validation, but we still process the config with the Configuration class.

**Comment by MatTheCat** [comment]
I guess I can split my ideas like this if it’s helpful:

| solution | Valid XSD | IDE XML support | Symfony XML validation | BC |
| - | - | - | - | - |
| Set `any`s’ `namespace` to `##other` (this PR) | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: BC break |
| Remove types from XSD | :heavy_check_mark: | :x: | :heavy_check_mark: | :heavy_check_mark: no BC Break |
| Remove Symfony XML validation | :x: | :heavy_check_mark: | :x: | :heavy_check_mark: no BC Break |

**Comment by MatTheCat** [comment]
In fact if we’re going to disable validation, we can make our XSD valid as well. That way there is no BC break and users are free to make their config valid or not. Updated the PR this way.

It would be even better to check for validation errors related to custom providers/authenticators (and trigger a deprecation?) but I’m not sure it is possible yet.

**Comment by stof** [comment]
I don't think disabling XML validation in the XmlFileLoader is a good idea (this won't be only for the SecurityBundle configuration but for any configuration). And I don't think the answer about IDEs is right: they would report any configuration for third-party providers as invalid, which will confuse developers.

This would also make it even more likely to have outdated XSD files for our bundle configuration schemas as they would not be validated anymore (which would also lead to bad IDE support for them if they are based on XSD files).

**Comment by MatTheCat** [comment]
> [IDEs] would report any configuration for third-party providers as invalid, which will confuse developers.

Only as long as they stay invalid. Once we offer the possibility to namespace them, developers should update them so that they aren’t invalid anymore. But this means we must support these invalid.

If we can detect these cases when validating, we could allow them and trigger a deprecation or something to tell the user to update its config (for now I managed to detect invalid providers from the exception message, but not authenticators yet).

Would that be a viable solution?

**Comment by stof** [comment]
@MatTheCat you disabled validation for **all** XML configuration affecting **all** bundles of the ecosystem.

**Comment by MatTheCat** [comment]
@stof yes this is the PR actual state while I’m investigating how to implement the idea I presented.

**Comment by MatTheCat** [comment]
Okay I re-enabled Symfony’s XML validation while allowing invalid providers/authenticators; these will only trigger a deprecation.

Not sure this is the best way and it’s missing tests, but do you agree with this solution?

File: src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php [hunk 1]
```diff
@@ -404,7 +404,32 @@ private function parseFileToDOM(string $file): \DOMDocument
...
+            if ($invalidSecurityElements) {
+                $dom = XmlUtils::loadFile($file);
+
+                foreach ($invalidSecurityElements as $errorIndex => $tagName) {
+                    foreach ($dom->getElementsByTagName($tagName) as $element) {
+                        if (!$parent = $element->parentElement) {
+                            continue;
+                        }
+                        if ('provider' === $parent->tagName || 'firewall' === $parent->tagName) {
+                            trigger_deprecation('symfony/security-bundle', '5.4.41', 'Third-party %s must now be namespaced; please update your security configuration "%s" tag.', 'provider' === $parent->tagName ? 'providers' : 'authenticators', $tagName);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php]: let's move the deprecation to 7.2, we don't need to report it in 5.4, do we?

Comment (MatTheCat) [reply src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php]: The issue is related to libxml rather than Symfony so it would be best to fix and report for as many users as possible.

**Comment by MatTheCat** [comment]
Ubuntu will join impacted systems on October 10 when 24.10 is released.

File: src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php]: we still shouldn't add new deprecations to 5.4, they are exclusively for 7.2
since we can deal with the situation, all is fine for 5.4/6.4

**Review by nicolas-grekas — COMMENTED** [review]
LGTM, let's add some tests?

File: src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php (hunk 1 above)
Comment (MatTheCat) [reply src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php]: Okay, removing the call to `trigger_deprecation` :ok_hand:

**Comment by MatTheCat** [comment]
Will add some

**Comment by MatTheCat** [comment]
Hmm I managed to make the new tests pass on my local environment, but the CI doesnʼt agree 🤔
I donʼt know when Iʼll be able to fix them so feel free to give a look in the meantime..!

**Comment by MatTheCat** [comment]
Hm not sure what to do because there are changes both in `symfony/dependency-injection` and `symfony/security-bundle` :thinking: 

Should I make `symfony/security-bundle` a dev dependency of `symfony/dependency-injection`, or is there a way to restrict the version of `symfony/dependency-injection` when testing `symfony/security-bundle`?

**Comment by OskarStark** [comment]
Just for testing or in general? In this case a conflict rule could help, or do I miss sth?

**Comment by MatTheCat** [comment]
This PR’s SecurityBundle changes require the DependencyInjection’s (but not the other way around), so I would need a way to force this dependency to be up-to-date, even though those changes are not part of any version yet (I think high and low-deps failures are related) :thinking:

**Comment by stof** [comment]
Bumping the min version of the `symfony/dependency-injection` requirement in security-bundle is valid as a way to fix the lowest-deps job (this is usually the way to go). The highest-deps job will probably be solved once the change in DI is merged up in 6.4.

**Comment by MatTheCat** [comment]
> Bumping the min version of the `symfony/dependency-injection` requirement in security-bundle is valid as a way to fix the lowest-deps job (this is usually the way to go).

But here the required changes are not part of any release yet; how can I bump the min version to “this PR”?

**Comment by xabbuh** [comment]
use the next patch release version (i.e. `^5.4.43|^6.4.11`)

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php [hunk 2]
```diff
@@ -404,7 +404,33 @@ private function parseFileToDOM(string $file): \DOMDocument
...
+                            continue;
+                        }
+                        if ('provider' === $parent->localName || 'firewall' === $parent->localName) {
+                            unset($errors[$errorIndex]);
+                        }
+                    }
+                }
+            }
+            if ($errors) {
+                throw new InvalidArgumentException(sprintf('Unable to parse file "%s": ', $file) . implode("/n", $errors), $e->getCode(), $e);
```
Comment (fabpot) [inline src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php]:
```suggestion
                throw new InvalidArgumentException(sprintf('Unable to parse file "%s": ', $file).implode("/n", $errors), $e->getCode(), $e);
```

**Review by fabpot — APPROVED** [review]
Minor CS issue.

**Comment by fabpot** [comment]
Thank you @MatTheCat.

File: src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php (hunk 2 above)
Comment (OskarStark) [reply src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php]: Should we add `concat_space` rule then to PHP-CS-Fixer config?

cc @keradus
