### PR TITLE
[HttpKernel] Refine Vary header check to skip special handling of 'Accept-Language' when it's the only entry and '_vary_by_language' is `true`  in `CacheAttributeListener`

### LINKED ISSUE #61229: CacheAttributeListener overrides custom Vary headers when set_locale_from_accept_language is enabled
### Symfony version(s) affected

\>=7.4

### Description

The `Vary` header(s), defined with the `@Cache` attributes are ignored when used in conjunction with the feature `set_locale_from_accept_language`.
However, the [documentation](https://symfony.com/doc/current/reference/configuration/framework.html#set-locale-from-accept-language) doesn't mention any impact on `Vary` response header enabling this feature:

> If this option is set to true, the Request locale will automatically be set to the value of the Accept-Language HTTP header.
> 
> When the _locale request attribute is passed, the Accept-Language header is ignored.

The possible cause is [at this line](https://github.com/symfony/symfony/blob/72ccba7791e9ef04812b218087110db9b25062c7/src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php#L153), looks like the `Symfony\Component\HttpKernel\EventListener\CacheAttributeListener` listener overwrites the `Vary` header(s) passed by `@Cache` attributes, instead of adding to it — which may break expected behavior when custom Vary headers are required.

### How to reproduce

`./src/Controller/TestController.php`
```php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\Cache;

class TestController
{
    #[Cache(vary: ['X-Custom-Header'], public: true)]
    public function __invoke(): Response
    {
        return new Response('Hello world');
    }
}

``` 

`./config/packages/framework.yaml`
```php
framework:
    set_locale_from_accept_language: true
``` 
```shell
curl --location 'http://localhost:8000/test'
``` 
**Vary response header: Accept-Language**

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by santysisi**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #61229 
| License       | MIT

### Summary
Refine Vary header check to skip special handling of 'Accept-Language' when it's the only entry and '_vary_by_language' is true in CacheAttributeListener

### Reason
Previously, the `CacheAttributeListener` was executed after the `ResponseListener`. When the `set_locale_from_accept_language` option is enabled in `framework.yaml`, the `ResponseListener` sets a Vary header on the response. Because `CacheAttributeListener` checks if a Vary header already exists before modifying it, its logic was being bypassed if it ran after the `ResponseListener`.

### References
* [LocaleListener](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/HttpKernel/EventListener/LocaleListener.php#L69-L76)
* [ResponseListener](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/HttpKernel/EventListener/ResponseListener.php#L55-L57)
* [CacheAttributeListener](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php#L126)

### CODE REVIEW

**Comment by santysisi** [comment]
If we want to avoid changing the priority, we can add a condition to check whether the request has the _vary_by_language attribute set to true, and the response's Vary header contains only Accept-Language.

**Comment by nicolas-grekas** [comment]
> check whether the request has the _vary_by_language

let's do this, so that this won't interfere with app's listeners

**Comment by santysisi** [comment]
status: needs work

There is a problem, i will try to resolve that problem tomorrow

**Comment by santysisi** [comment]
status: needs review

The problem was resolved by sending the 'Accept-Language' header at the end

**Comment by Spomky** [comment]
Many thanks @santysisi.
Looks good to me. I have just one question: how `Vary: *` is covered?

**Comment by santysisi** [comment]
Thanks for the review! 🙌

Regarding [`Vary: *`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Vary#sect), I don't think it's currently covered.

I tested it locally, and it seems that when the response includes `Vary: *`, it still gets cached. I'm not sure if that's a bug or expected behavior, but it happens regardless of this PR, so it doesn't appear to be introduced by these changes.

**Comment by Spomky** [comment]
I found in [RFC9111 section4.1](https://datatracker.ietf.org/doc/html/rfc9111#section-4.1) the following sentence: `A stored response with a Vary header field value containing a member "*" always fails to match.`.
So I understand `Vary *` should be treated as a relevant case and left untouched (no append).

May I suggest to add 2 test cases.

```php
    yield 'vary * (no append) — vary_by_language=true' => [
        'responseVary'   => ['*'],
        'cacheVary'      => ['X-Foo'],
        'varyByLanguage' => true,
        'expectedVary'   => ['*'],
    ];

    yield 'vary * (no append) — vary_by_language=false' => [
        'responseVary'   => ['*'],
        'cacheVary'      => ['X-Foo'],
        'varyByLanguage' => false,
        'expectedVary'   => ['*'],
    ];
```

Edit: and `hasRelevantVaryHeader` to directly return `true` if `*` is present.

**Comment by santysisi** [comment]
Hey, thanks a lot for your suggestions! The change has been made

Edit: I'm not sure if it's necessary to add the modification to the `hasRelevantVaryHeader` method to directly return `true` when `*` is present. With the current condition, I believe it already returns true in that case (your suggested test seems to confirm that behavior, thanks again for the suggestion! :heart: ). But if you still think the change is needed, I'm happy to update it! :smile:

**Review by Spomky — APPROVED** [review]
Looks good. No additional comment.
Many thanks!

**Comment by cdaguerre** [comment]
This should also fix: https://github.com/symfony/symfony/issues/58663

File: src/Symfony/Component/HttpKernel/Tests/EventListener/CacheAttributeListenerTest.php [hunk 1]
```diff
@@ -318,6 +318,76 @@ public function testAttribute()
...
 
+    /**
+     * @dataProvider provideVaryHeaderScenarios
+     */
+    public function testHasRelevantVaryHeaderBehavior(
+        array $responseVary,
+        array $cacheVary,
+        bool $varyByLanguage,
+        array $expectedVary,
+    ): void {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/EventListener/CacheAttributeListenerTest.php]:
```suggestion
    public function testHasRelevantVaryHeaderBehavior(array $responseVary, array $cacheVary, bool $varyByLanguage, array $expectedVary)
    {
```

File: src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php [hunk 2]
```diff
@@ -159,6 +159,12 @@ public function onKernelResponse(ResponseEvent $event)
             }
         }
 
+        if (($vary = $response->getVary()) && \in_array('Accept-Language', $vary)) {
+            // Ensure 'Accept-Language' is included at the end of the Vary header
+            $vary = array_filter($vary, fn (string $value) => 'Accept-Language' !== $value);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]:
```suggestion
            $vary = array_filter($vary, static fn ($value) => 'Accept-Language' !== $value);
```

File: src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php [hunk 3]
```diff
@@ -159,6 +159,12 @@ public function onKernelResponse(ResponseEvent $event)
             }
         }
 
+        if (($vary = $response->getVary()) && \in_array('Accept-Language', $vary)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]:
```suggestion
        if (($vary = $response->getVary()) && \in_array('Accept-Language', $vary, true)) {
```

File: src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php [hunk 4]
```diff
@@ -194,4 +200,16 @@ private function toSeconds(int|string $time): int
...
     }
+
+    private function hasRelevantVaryHeader(Response $response, Request $request): bool
+    {
+        // Check if the response has a Vary header that should be considered,
+        // ignoring cases where it's only 'Accept-Language' and the request has the attribute '_vary_by_language' in true.
+        return $response->hasVary()
+            && !(
+                1 === \count($response->getVary())
+                && \in_array('Accept-Language', $response->getVary())
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]:
```suggestion
['Accept-Language'] === $response->getVary()
```

File: src/Symfony/Component/HttpKernel/Tests/EventListener/CacheAttributeListenerTest.php [hunk 5]
```diff
@@ -318,6 +318,76 @@ public function testAttribute()
...
+        $event = new ResponseEvent($this->getKernel(), $request, HttpKernelInterface::MAIN_REQUEST, $response);
+        $listener->onKernelResponse($event);
+
+        $this->assertSame($expectedVary, $response->getVary());
+    }
+
+    public static function provideVaryHeaderScenarios(): array
+    {
+        return [
+            'no vary headers at all' => [
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/EventListener/CacheAttributeListenerTest.php]: could be yield statements

**Review by nicolas-grekas — APPROVED** [review]
LGTM, just some nitpicking

**Comment by santysisi** [comment]
Hi! Thanks a lot for your suggestions. I’ve made the changes you recommended.
Please let me know if there’s anything else needed.
Thanks again! ❤️

File: src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php [hunk 6]
```diff
@@ -194,4 +200,15 @@ private function toSeconds(int|string $time): int
...
+
+    private function hasRelevantVaryHeader(Response $response, Request $request): bool
+    {
+        // Check if the response has a Vary header that should be considered,
+        // ignoring cases where it's only 'Accept-Language' and the request has the attribute '_vary_by_language' in true.
+        return $response->hasVary()
+            && !(
+                ['Accept-Language'] === $response->getVary()
+                && $request->attributes->get('_vary_by_language')
+            );
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]: let's inline the method and the comment above?
```suggestion
        return ['Accept-Language'] === $response->getVary() ? !$request->attributes->get('_vary_by_language') : $response->hasVary()
```

File: src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php [hunk 7]
```diff
@@ -159,6 +159,12 @@ public function onKernelResponse(ResponseEvent $event)
             }
         }
 
+        if (($vary = $response->getVary()) && \in_array('Accept-Language', $vary, true)) {
+            // Ensure 'Accept-Language' is included at the end of the Vary header
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]: Why is this necessary BTW?

**Review by nicolas-grekas — COMMENTED** [review]
LGTM, I'm just wondering about these.

File: src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php (hunk 7 above)
Comment (santysisi) [reply src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]: This is necessary because when you have multiple requests with different headers listed in the Vary response header, if Accept-Language is not included in the final response, the cache will not be used for subsequent requests. Each request will be treated as unique, and the previously cached response won't apply.

**Comment by santysisi** [comment]
Hi Nicolas, thanks a lot for your suggestions! :heart:
The changes have been made. Please let me know if there's anything else you'd like to adjust

File: src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php (hunk 7 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]: my question was about the ordering: why do we need to reorder?

File: src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php (hunk 6 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]: I meant this sorry:
```diff
--- a/src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php
+++ b/src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php
@@ -123,7 +123,10 @@ class CacheAttributeListener implements EventSubscriberInterface
 
         unset($this->lastModified[$request]);
         unset($this->etags[$request]);
-        $hasVary = $this->hasRelevantVaryHeader($response, $request);
+
+        // Check if the response has a Vary header that should be considered, ignoring cases where
+        // it's only 'Accept-Language' and the request has the '_vary_by_language' attribute
+        $hasVary = ['Accept-Language'] === $response->getVary() ? !$request->attributes->get('_vary_by_language') : $response->hasVary();
 
         foreach (array_reverse($attributes) as $cache) {
             if (null !== $cache->smaxage && !$response->headers->hasCacheControlDirective('s-maxage')) {
@@ -200,13 +203,4 @@ class CacheAttributeListener implements EventSubscriberInterface
 
         return $time;
     }
-
-    /**
-     * Check if the response has a Vary header that should be considered
-     * ignoring cases where it's only 'Accept-Language' and the request has the attribute '_vary_by_language' in true.
-     */
-    private function hasRelevantVaryHeader(Response $response, Request $request): bool
-    {
-        return ['Accept-Language'] === $response->getVary() ? !$request->attributes->get('_vary_by_language') : $response->hasVary();
-    }
```

File: src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php (hunk 7 above)
Comment (santysisi) [reply src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]: Sorry, my previous comment was incorrect. What I meant to say is:

The issue occurs if `Accept-Language` is not included at the end of the Vary header in the response , not if `Accept-Language` is missing from the response itself.

I haven't tested this with many servers yet, but I noticed this behavior using the Symfony local server (started via `symfony server:start`). I'm not sure whether it's an issue with Symfony itself (I don't think so), or something related to the local web server.

I'll try to test with other servers over the weekend and will update here

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]: Would you have some reproducer I could run with the Symfony local server?

Comment (santysisi) [reply src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]: Sure! I’ll create a reproducer this weekend (most likely on Sunday ) and share it with you then. Sorry I can’t provide it right away, I just don’t have enough time at the moment 🙏

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]: ~Could this be related to HttpCache not ordering headers in the vary-list?~ (I guess not)

Comment (santysisi) [reply src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]: Hi Nicolas, I hope you're doing well 😄
I've created a [reproducer](https://github.com/santysisi/http_cache_bug_reproducer), sorry for the delay, it’s been a busy week 😅

The reproducer depends on the original Symfony repository, so you’ll need to modify the `CacheAttributeListener` directly. However, if you prefer, I can package the code from the PR into a separate to make testing easier. just let me know! 🙂

Thanks again for your help! 😄

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]: thanks, then the issue is clear: that's a bug HttpCache / Store
we should remove the hack from this PR and create a new one with a fix HttpCache
up to give it a try?

**Comment by nicolas-grekas** [comment]
Thank you @santysisi.

File: src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php (hunk 7 above)
Comment (santysisi) [reply src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]: Sure, I’ll give it a try as soon as possible :smile:

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]: in case you're up to having a look: ping @philpichet ;)

Comment (santysisi) [reply src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]: Hi! I hope you're doing well 😊
I tried to reproduce the error yesterday and today, but I haven’t been able to 🤔
I’m not sure if it was something specific to my computer or environment at the time, but I'm now using the same machine and the same reproducer and everything is working fine.

I’m really not sure what happened. Sorry for the confusion 🙏

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]: @philpichet did some changes in #61518 on the topic, this might have fixed it!

Comment (santysisi) [reply src/Symfony/Component/HttpKernel/EventListener/CacheAttributeListener.php]: Oh, got it! 😄 Thanks for the explanation, and big thanks to @philpichet for the fix ❤️
