### PR TITLE
[Console] handles multi-byte characters in autocomplete

### LINKED ISSUE #29966: QuestionHelper with AutoComplete mangles multi byte characters on output
**Symfony version(s) affected**: master

**Description**  
We're using the QuestionHelper to read input. The Helper has an Auto Complete, and some of what we're inputting is multibyte characters like `é`. 

When we do this, `é` becomes: `��` on the command line. (In the screenshot below, I included a `d` after the `é`).

1__root_ip-10-38-167-243____docker_

I understand this to be because of the use of `fread`: https://github.com/symfony/console/blob/master/Helper/QuestionHelper.php#L214.

The actual recorded value is correct, but the content put on the command line is not.

Removing the auto complete resolves the problem, but obviously then removes the auto complete functionality.

**How to reproduce**  
I believe this is a minimal test case:

```
class QuestionAsker extends Command
{
    protected function configure()
    {
        $this->setName("app:question-asker");
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $helper = $this->getHelper('question');

        $question = new Question('Enter something multi byte:');
        $question->setAutocompleterValues(
            ["a", "b", "c"]
        );

        // Write out the current content so it's easier to edit
        //$output->write($currentContent);
        $data = $helper->ask($input, $output, $question);

        $output->writeln("This is incorrect ^");
        $output->writeln("This data is correct:");
        $output->writeln($data);
    }
}
```

**Possible Solution**  
I'm not sure 😞 

**Additional context**  
We did this on a Mac, running either Terminal or ITerm2 (same output in both cases).

### PR DESCRIPTION
**Pull request by jls-esokia**
fixes #29966 

| Q             | A
| ------------- | ---
| Branch?       | 3.4 
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #29966   
| License       | MIT
| Doc PR        | - 

I used the `mb_ord` to detect whether the amount of bytes read is valid before proceeding.  I limit the number of bytes read to 4 before giving up because characters can use at most 4 bytes.
The test passes with or without the fix though.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Using `mb_ord()` requires PHP 7.2, but the lowest supported version for branch 3.4 is PHP 5.5.
We could use the 7.2 polyfill to make this work, but I don't think the polyfill implements the case where it should return `false` on invalid characters.
That'd be great if someone could have a look at the polyfill to fix it.

For this PR, we could use that map:
`$lengthMask = array("\xC0" => 2, "\xD0" => 2, "\xE0" => 3, "\xF0" => 4);`
Then, for a byte `$b`, knowing the length of the utf8 character it starts is done with:
`$length = $b < "\x80" ? 1 : $lengthMask[$b & "\xF0"];`

**Comment by jls-esokia** [comment]
My bad, I saw `mb_ord` was listed in the polyfill-mbstring library which is a dependency of the console component.  Ok made the necessary correction.

File: src/Symfony/Component/Console/Helper/QuestionHelper.php [hunk 1]
```diff
@@ -308,6 +308,12 @@ private function autocomplete(OutputInterface $output, Question $question, $inpu
 
                 continue;
             } else {
+                $lengthMask = ["\xC0" => 2, "\xD0" => 2, "\xE0" => 3, "\xF0" => 4];
+                $length = $c < "\x80" ? 1 : $lengthMask[$c & "\xF0"];
+                if (1 < $length) {
+                    $c .= fread($inputStream, $length - 1);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Helper/QuestionHelper.php]:
```php
                if ("\x80" <= $c) {
                    $c .= fread($inputStream, ["\xC0" => 1, "\xD0" => 1, "\xE0" => 2, "\xF0" => 3][$c & "\xF0"]);
                 }
```

File: src/Symfony/Component/Console/Tests/Helper/QuestionHelperTest.php [hunk 2]
```diff
@@ -237,6 +237,43 @@ public function testAskWithAutocompleteWithExactMatch()
...
+            '𐍈' => '4 bytes character',
+        ];
+
+        $dialog = new QuestionHelper();
+        $dialog->setHelperSet(new HelperSet([new FormatterHelper()]));
+
+        $question = new ChoiceQuestion('Please select a character', $possibleChoices);
+        $question->setMaxAttempts(1);
+
+        $this->assertSame($character, $dialog->ask($this->createStreamableInputInterfaceMock($inputStream), $this->createOutputInterface(), $question));
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Tests/Helper/QuestionHelperTest.php]:
```suggestion
        $this->assertSame(
            $character,
            $dialog->ask($this->createStreamableInputInterfaceMock($inputStream), $this->createOutputInterface(), $question)
        );
```

Comment (nicolas-grekas) [reply src/Symfony/Component/Console/Tests/Helper/QuestionHelperTest.php]: we usually prefer long lines so not sure about that :)

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @jls-esokia.
