### PR TITLE
[HttpClient] Fix caching client decorating scoping client

### LINKED ISSUE #62166: [HttpClient] Scoped clients doesn't work with Caching HTTP Client
### Symfony version(s) affected

7.4

### Description

When using the Caching HTTP Client with a scoped client, an exception `Invalid URL: scheme is missing` is thrown on the request

### How to reproduce

Either creating the scoped client manually:

```php
$client = new CachingHttpClient(
    ScopingHttpClient::forBaseUri(HttpClient::create(), 'https://api.github.com'),
    new TagAwareAdapter(new ArrayAdapter()),
);

$release = $client->request('GET', '/repos/symfony/symfony/releases/latest');
```

or using the framework.yaml config:

```yaml
framework:
    http_client:
        scoped_clients:
            github.client:
                base_uri: 'https://api.github.com'
                caching:
                    cache_pool: cache.app.taggable
```

When doing a request without the scheme and domain (E.G `$release = $client->request('GET', '/repos/symfony/symfony/releases/latest');`), the following exception is thrown:

> Invalid URL: scheme is missing in "/repos/symfony/symfony/releases/latest". Did you forget to add "http(s)://"?

This is because the `CachingHttpClient` calls `self::prepareRequest` first thing in the request method, which validated the URL and throws the exception before giving the ScopingHttpClient a chance to set the base uri

https://github.com/symfony/symfony/blob/929e82eeb7cab85912257067c6059ee263f02f51/src/Symfony/Component/HttpClient/CachingHttpClient.php#L152

cc: @Lctrs 

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by pierredup**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62166
| License       | MIT

When registering a scoped client and enabling caching, the scoping client should decorate the caching one, while currently it's registered the wrong way around. This causes `Invalid URL` exceptions, since the URL is not resolved first by the scoping client

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I checked out the code on a test app and figured your initial patch didn't work. I force-pushed a new one.
Can you please have a look and fix tests? 🙏

**Comment by nicolas-grekas** [comment]
Thank you @pierredup.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -2877,39 +2877,45 @@ private function registerHttpClientConfiguration(array $config, ContainerBuilder
             $retryOptions = $scopeConfig['retry_failed'] ?? ['enabled' => false];
             unset($scopeConfig['retry_failed']);
 
+            $transport = $name.'.transport';
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:2880]: instead of introducing this separate service, we could register `$name` with the initial service (which could even be a DI alias instead of this `current()` hack in the factory) and then registering ScopingHttpClient as a decorator of that service, allowing to configure the decoration priority even for cases where ScopingHttpClient should not be the outer one (see UriTemplateHttpClient which is still on the outside).
