### PR TITLE
[HttpClient] fix PHP warning + accept status code >= 600

### LINKED ISSUE #36717: [HttpClient] Invalid HTTP status codes raise a warning using CurlHttpClient
**Symfony version(s) affected**: 5.0.8

**Description**  
When sending a GET request that is answered with a `999` status code (which is horrible behavior, no doubt), a warning is raised.

Is there a way to prevent this?

```
Warning: curl_multi_exec(): Could not call the CURLOPT_HEADERFUNCTION in /vendor/symfony/http-client/Response/CurlResponse.php on line 261

[...]

Fatal error: Uncaught Symfony\Component\HttpClient\Exception\TransportException: Invalid or missing HTTP status line. in /vendor/symfony/http-client/Response/ResponseTrait.php on line 273

Symfony\Component\HttpClient\Exception\TransportException: Invalid or missing HTTP status line. in /vendor/symfony/http-client/Response/ResponseTrait.php on line 273
```

At least I *think* it is the `999` that breaks things, I am using Symfony's HttpClient within a crawler and a link similar to https://www.linkedin.com/company/linkedin/ made it break.

**How to reproduce**  

```
$client = new \Symfony\Component\HttpClient\CurlHttpClient();

$response = $client->request('GET', 'https://www.linkedin.com/company/linkedin/');
$contents = $response->getContent();
```

If that LinkedIn link does not return a `999` for you, you will probably need to manually set up a site that does to encounter the error. Not sure how they decide when to respond with `999`. While gathering information for this report it returned the `999` in Chrome for me as well but eventually also worked once or twice. Probably security measures based on User-Agent and IP.

More people plagued by this over here: https://stackoverflow.com/questions/27231113/999-error-code-on-head-request-to-linkedin.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36717
| License       | MIT
| Doc PR        | -

This fixes the PHP warning reported in the linked issue.

This also relaxes the accepted status codes, with https://www.linkedin.com/company/linkedin/ as an example that returns a non-conformant one (`999`). Some more at https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

These are now handled as 5xx codes, ie they trigger a ServerException.

### CODE REVIEW

File: src/Symfony/Component/HttpClient/Response/ResponseTrait.php [hunk 1]
```diff
@@ -253,7 +253,7 @@ private static function initialize(self $response): void
     private static function addResponseHeaders(array $responseHeaders, array &$info, array &$headers, string &$debug = ''): void
     {
         foreach ($responseHeaders as $h) {
-            if (11 <= \strlen($h) && '/' === $h[4] && preg_match('#^HTTP/\d+(?:\.\d+)? ([12345]\d\d)(?: |$)#', $h, $m)) {
+            if (11 <= \strlen($h) && '/' === $h[4] && preg_match('#^HTTP/\d+(?:\.\d+)? ([123456789]\d\d)(?: |$)#', $h, $m)) {
```
Comment (apfelbox) [inline src/Symfony/Component/HttpClient/Response/ResponseTrait.php:256]:
```suggestion
            if (11 <= \strlen($h) && '/' === $h[4] && preg_match('#^HTTP/\d+(?:\.\d+)? ([1-9]\d\d)(?: |$)#', $h, $m)) {
```

A bit easier to read

**Review by javiereguiluz — APPROVED** [review]

**Comment by gmponos** [comment]
Does this allow also status codes like `1`, `9` or `50`.. meaning below `100` ?

**Comment by nicolas-grekas** [comment]
Nope it doesn't. Those will trigger a TransportExceptionInterface
