### PR TITLE
[Console] Ensure terminal is usable after termination signal

### LINKED ISSUE #61732: [Console] Ctrl-C can break the terminal when selecting input from a list
### Symfony version(s) affected

7.3.3

### Description

When using Symfony QuestionHelper and selecting input from a list of choices (ChoiceQuestion), Ctrl-C can leave the terminal in a broken state on Unixy platforms under certain conditions:

* When a signal handler is installed and calls `exit`
* When xdebug-handler restarts a process https://github.com/composer/composer/issues/12526

The terminal does not show any input and requires a Ctrl-Break and Enter to restart it.

When calling other QuestionHelper functions, Ctrl-C works okay.

### Further info
When using a signal handler, this causes the terminal to break:

```php
pcntl_signal(SIGINT, function ($signal) {
    echo 'CRTL_C received, exiting', PHP_EOL;
    exit(2;)
});
```
But this is okay:

```php
pcntl_signal(SIGINT, function ($signal) {
    echo 'CRTL_C received - continuing', PHP_EOL;
});
```

When using a restart, SIGINT is set to be ignored in the parent process, then set to its default action in the restarted (child) process because it inherited the ignored state.

```php
if (!self::$inRestart) {
    // Restarting, so ignore SIGINT in parent
    pcntl_signal(SIGINT, SIG_IGN);
} elseif (is_int(pcntl_signal_get_handler(SIGINT))) {
    // Restarted, no handler set so force default action
    pcntl_signal(SIGINT, SIG_DFL);
}
```

### How to reproduce

Demo/reproducer: https://github.com/johnstevenson/sigbug

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by johnstevenson**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no 
| Issues        | Fix #61732
| License       | MIT

This PR introduces a new helper `TerminalInputHelper` that restores the terminal to its original state after it has been modified when reading using input. This ensures that the terminal is not broken when a terminating signal, like Ctrl-C, is received.

QuestionHelper.php disables `icanon` and `echo` when accepting input from a selection, and disables `echo` when accepting hidden input. If these are not restored before termination, the user's terminal can end up in a broken state.

Usage:
```php

$inputHelper = new TerminalInputHelper($inputStream);

// Change terminal settings then wait for input before all input reads
$inputHelper->waitForInput();

// Read the input then call finish to restore terminal settings and signal handlers
$inputHelper->finish()
```

The helper creates its own signal handlers (for `SIGINT`, `SIGQUIT`,  and `SIGTERM`) that restore the original terminal settings then call any original handler callback. If the original handler callback does not terminate the process then the current terminal settings are restored.

If there is no original signal handler callback and the signal's disposition is set to the default action (`SIG_DFL`), then that action is invoked by a `posix_kill` call.

The `finish` method restores the terminal settings and replaces the new signal handlers with the original ones.

### CODE REVIEW

**Comment by chalasr** [comment]
Do you have a use case for using this helper in your own commands whether coming from a Symfony application or a reusable bundle? Elsewhere than in core I mean.

**Comment by johnstevenson** [comment]
> Do you have a use case for using this helper in your own commands...

Not at all. The helper is to fix the issues with Symfony/Console.

**Comment by johnstevenson** [comment]
I've just noticed this issue https://github.com/symfony/symfony/issues/61852 (that has been closed). This PR fixes the problem described, which is having to hit Enter after a Ctrl-C to send the signal (when submitting hidden input).

**Comment by chalasr** [comment]
Please inline back the logic into Application and QuestionHelper. Helpers in this namespace are part of Console's public API, but I can't think of a use case for this helper in userland either and I looking at it, I don't think it's worth it. Expanding the public API is a feature also while this PR is a bugfix targeting a branch that is in maintenance mode, so please do the minimum changes to fix the bug at hand. Thanks

**Comment by stof** [comment]
Given the need for extra state in this input helper, I'm fine with using a separate class. But it should be `@internal`

File: src/Symfony/Component/Console/Helper/QuestionHelper.php [hunk 1]
```diff
@@ -434,22 +428,29 @@ private function getHiddenResponse(OutputInterface $output, $inputStream, bool $
...
-            $sttyMode = shell_exec('stty -g');
+            $inputHelper = new TerminalInputHelper($inputStream);
             shell_exec('stty -echo');
         } elseif ($this->isInteractiveInput($inputStream)) {
             throw new RuntimeException('Unable to hide the response.');
         }
 
+        if (null !== $inputHelper) {
+            $inputHelper->waitForInput();
+        }
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Helper/QuestionHelper.php]:
```suggestion
        $inputHelper?->waitForInput();
```

File: src/Symfony/Component/Console/Helper/QuestionHelper.php [hunk 2]
```diff
@@ -434,22 +428,29 @@ private function getHiddenResponse(OutputInterface $output, $inputStream, bool $
...
             $errOutput = $output instanceof ConsoleOutputInterface ? $output->getErrorOutput() : $output;
             $errOutput->warning('The value was possibly truncated by your shell or terminal emulator');
         }
 
-        if (self::$stty && Terminal::hasSttyAvailable()) {
-            shell_exec('stty '.$sttyMode);
+        // Restore the terminal so it behaves normally again
+        if (null !== $inputHelper) {
+            $inputHelper->finish();
         }
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Helper/QuestionHelper.php]:
```suggestion
        $inputHelper?->finish();
```

**Comment by chalasr** [comment]
The non-obvious name of that helper annoys me but probably fine if it’s internal. Works for me

File: src/Symfony/Component/Console/Helper/TerminalInputHelper.php [hunk 3]
```diff
@@ -0,0 +1,142 @@
...
+ *
+ *     ...change terminal settings
+ *
+ *     // Wait for input before all input reads
+ *     $inputHelper->waitForInput();
+ *
+ *     ...read input
+ *
+ *     // Call finish to restore terminal settings and signal handlers
+ *     $inputHelper->finish()
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Helper/TerminalInputHelper.php:31]:
```suggestion
 *
 * @internal
```

**Review by nicolas-grekas — COMMENTED** [review]
Here's some nitpicking.

File: src/Symfony/Component/Console/Helper/QuestionHelper.php (hunk 1 above)
Comment (johnstevenson) [reply src/Symfony/Component/Console/Helper/QuestionHelper.php]: Fixed

File: src/Symfony/Component/Console/Helper/QuestionHelper.php (hunk 2 above)
Comment (johnstevenson) [reply src/Symfony/Component/Console/Helper/QuestionHelper.php]: Fixed

File: src/Symfony/Component/Console/Helper/TerminalInputHelper.php (hunk 3 above)
Comment (johnstevenson) [reply src/Symfony/Component/Console/Helper/TerminalInputHelper.php:31]: Fixed

**Comment by johnstevenson** [comment]
> The non-obvious name of that helper annoys me ....

I tried several before choosing the least annoying. Feel free to suggest an alternative.

**Comment by valx76** [comment]
> > The non-obvious name of that helper annoys me ....
> 
> I tried several before choosing the least annoying. Feel free to suggest an alternative.

I can think of `InputSignalHelper` or `SignalSafeTerminalInputHelper`.
Don't know if it's any better, what do you think?

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @johnstevenson.
