### PR TITLE
[Validator] Validate SVG ratio in Image validator

### LINKED ISSUE #45269: [Validator] Feat: Support SVGs when validating image dimensions
### Description

If any image dimension validation is added with Image validation, it will fail with SVGs as the image size is detected using `getimagesize`. See: https://github.com/symfony/validator/blob/5.4/Constraints/ImageValidator.php#L56

Would there be a want from the community if I were to create a PR to detect SVG images and grab the file size from the XML? With this, we could skip the width/height validation all together, but still be able to implement features such as portrait/landscape/ratio validation.

I guess with the mime type, I could work out that it is an SVG, parse the content, and skip the width/size validation (it shouldn't matter with SVGs really.. or I could add an option?) I could implement other dimension validation still and return the same error if we still cannot detect the image size.

### Example

_No response_

### PR DESCRIPTION
**Pull request by maximecolin**
| Q             | A
| ------------- | ---
| Branch?       | 7.3 
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #45269
| License       | MIT

Implement ratio check for SVG images. Checking SGV size is not relevant as a SVG image can be enlarged without loss, but ratio can be important to check.

Currently, the validator add a violation with `SIZE_NOT_DETECTED_ERROR` in case of SVG image.

SVG size is guessed from viewbox, width and height attributes. Viewbox will provides default size, width and height can override viewbox size if they are number. Width and height as percentage are ignored as the final size will depend on the container.

I use `preg_match` instead of `\DomDocument` or `simplexml` functions to extract viewBox, width and height in order to avoid new dependencies on `ext-dom` or `ext-simplexml`.

In case of SVG, `minWidth`, `maxWidth`, `minHeight`, `maxHeight`, `minPixels` and `maxPixels` are ignored because not relevant. Only `maxRatio`, `minRatio`, `allowSquare`, `allowLandscape` and `allowPortrait` can generate violations, like suggested in the comments of the abandoned #45486.

### CODE REVIEW

File: src/Symfony/Component/Validator/Constraints/ImageValidator.php [hunk 1]
```diff
@@ -231,4 +239,65 @@ public function validate(mixed $value, Constraint $constraint): void
             imagedestroy($resource);
         }
     }
+
+    /**
+     * Check whether a value is an SVG image
+     *
+     * @param mixed $value
+     *
+     * @return bool
```
Comment (stof) [inline src/Symfony/Component/Validator/Constraints/ImageValidator.php]: those phpdoc annotations don't provide any value over the native signature and so should be removed.

File: src/Symfony/Component/Validator/Constraints/ImageValidator.php [hunk 2]
```diff
@@ -231,4 +239,65 @@ public function validate(mixed $value, Constraint $constraint): void
...
+     * <b>TRUE</b> if <i>value</i> is an SVG, <b>FALSE</b> if it's not, or if we can't detect its MimeType;
```
Comment (stof) [inline src/Symfony/Component/Validator/Constraints/ImageValidator.php]: We don't use HTML in our phpdoc.

File: src/Symfony/Component/Validator/Constraints/ImageValidator.php [hunk 3]
```diff
@@ -231,4 +239,65 @@ public function validate(mixed $value, Constraint $constraint): void
...
+
+    /**
+     * Extract width and height from an SVG image
+     *
+     * @param mixed $value
+     *
+     * @return array|false
+     * Index 0 and 1 contains respectively the width and the height of the image. <i>FALSE</b> if size can be found.
+     */
+    private function getSvgSize(mixed $value): array|false
```
Comment (stof) [inline src/Symfony/Component/Validator/Constraints/ImageValidator.php]: please use `null` to represent the absence of value, not `false`

File: src/Symfony/Component/Validator/Constraints/ImageValidator.php [hunk 4]
```diff
@@ -231,4 +239,59 @@ public function validate(mixed $value, Constraint $constraint): void
...
+            $mime = (new File($value))->getMimeType();
+        }
+
+        return 'image/svg+xml' === $mime;
+    }
+
+    /**
+     * Extract width and height from an SVG image.
+     *
+     * @return array|false Index 0 and 1 contains respectively the width and the height of the image. <i>FALSE</b> if size can be found.
```
Comment (stof) [inline src/Symfony/Component/Validator/Constraints/ImageValidator.php]: this should describe the proper type: `@return array{int, int}|null` (assuming my other comment is taken into account)

**Review by stof — CHANGES_REQUESTED** [review]

**Comment by maximecolin** [comment]
Thanks @stof, I fixed the code according to your comments.

File: src/Symfony/Component/Validator/Constraints/ImageValidator.php [hunk 5]
```diff
@@ -231,4 +239,59 @@ public function validate(mixed $value, Constraint $constraint): void
...
+            $mime = (new File($value))->getMimeType();
+        }
+
+        return 'image/svg+xml' === $mime;
+    }
+
+    /**
+     * Extract width and height from an SVG image.
+     *
+     * @return array{int, int}|null Index 0 and 1 contains respectively the width and the height of the image, false if size can't be found.
```
Comment (stof) [inline src/Symfony/Component/Validator/Constraints/ImageValidator.php]:
```suggestion
     * @return array{int, int}|null Index 0 and 1 contains respectively the width and the height of the image, null if size can't be found.
```

**Review by stof — APPROVED** [review]

File: src/Symfony/Component/Validator/CHANGELOG.md [hunk 6]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+7.3
+---
+
+* Allow `Image` constraint to check SVG ratio
```
Comment (OskarStark) [inline src/Symfony/Component/Validator/CHANGELOG.md]:
```suggestion
 * Allow `Image` constraint to check SVG ratio
```

File: src/Symfony/Component/Validator/Constraints/ImageValidator.php [hunk 7]
```diff
@@ -231,4 +239,59 @@ public function validate(mixed $value, Constraint $constraint): void
             imagedestroy($resource);
         }
     }
+
+    /**
+     * Check whether a value is an SVG image.
+     *
+     * Return true if value is an SVG, false if it's not, or if we can't detect its MimeType.
```
Comment (OskarStark) [inline src/Symfony/Component/Validator/Constraints/ImageValidator.php]:
```suggestion
     * @return bool Return true if value is an SVG, false if it's not, or if we can't detect its MimeType.
```

File: src/Symfony/Component/Validator/Constraints/ImageValidator.php [hunk 8]
```diff
@@ -231,4 +239,59 @@ public function validate(mixed $value, Constraint $constraint): void
...
+        if ($value instanceof File) {
+            $content = $value->getContent();
+        } elseif (!class_exists(File::class)) {
+            return null;
+        } else {
+            $content = (new File($value))->getContent();
+        }
+
+        if (1 === preg_match('/<svg[^<>]+width="([0-9]+)"[^<>]*>/', $content, $widthMatches)) {
+            $width = (int) $widthMatches[1];
```
Comment (OskarStark) [inline src/Symfony/Component/Validator/Constraints/ImageValidator.php]: What about using capturing groups instead of numbers?

File: src/Symfony/Component/Validator/Tests/Constraints/ImageValidatorTest.php [hunk 9]
```diff
@@ -498,4 +498,138 @@ public static function provideInvalidMimeTypeWithNarrowedSet()
...
+    public function testSvg(string $image, Image $constraint, ?string $violation, array $parameters = [])
+    {
+        $this->validator->validate($image, $constraint);
+
+        if ($violation) {
+            $this->buildViolation('myMessage')
+                ->setCode($violation)
+                ->setParameters($parameters)
+                ->assertRaised();
+        } else {
```
Comment (OskarStark) [inline src/Symfony/Component/Validator/Tests/Constraints/ImageValidatorTest.php]: What about two testcases and a valid and invalid provider?

**Comment by maximecolin** [comment]
Thanks @OskarStark, I applied your suggestions.

File: src/Symfony/Component/Validator/CHANGELOG.md [hunk 10]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+7.3
+---
+
+ * Allow `Image` constraint to check SVG ratio
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/CHANGELOG.md]:
```suggestion
 * Add support for ratio checks for SVG files to the `Image`
```

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @maximecolin.
