### PR TITLE
[Console] Add silent verbosity suppressing all output, including errors

### LINKED ISSUE #52777: Allow disabling exception rendering
### Description

When using Datadog and Docker, it is recommended to only ever print JSON (for Datadog) to the output (because the output of the main process is the output of the whole container). Datadog documents how to properly configure a Symfony application to fulfill that requirement: https://docs.datadoghq.com/logs/log_collection/php/?tab=phpmonolog

They don't mention it, but you should probably also use `--quiet` when running a command in production, so that only the json logs show up in the output.

There's one thing that you can't however prevent, and that is the exception rendering done by https://github.com/symfony/symfony/blob/c8b962a0bf4ec24ef405222d66f3ae8e9eea94f6/src/Symfony/Component/Console/Application.php#L820-L830

Because of it, what you will see on Datadog is:
- a properly formatted, CRITICAL datadog line thanks to the monolog configuration
- one INFO line for each line in the unformatted output. 

### Example

It might be nice to have something like 
```yaml
framework:
    render_errors: '%kernel.debug%'
```
to configure this.

### PR DESCRIPTION
**Pull request by wouterj**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | yes
| Issues        | Fix #52777 
| License       | MIT

<details>
<summary>Original PR description</summary>

Alternative to #53126

In Symfony 2.8, we decided to still show exceptions/errors when running a command with `--quiet` or `SHELL_VERBOSITY=-1` (#15680).

Since that time, we've introduced the ConsoleLogger and 12-factor app logic. In todays landscape, it's more common to run commands that only output computer-readable text (e.g. JSON), which is ingested and displayed by services like Datadog and Kibana.
Our decision from 2.8 breaks this, as the JSON is interrupted by human-readable exception output that users can't disable. At the same time, this information is duplicated as errors are always logged (and thus shown as JSON).

I think we should revert the 2.8 decision, rather than adding a new "extremely quiet" verbosity mode. As far as I'm aware, this is also more consistent with normal unix commands which also don't output anything when passing `--quiet`.
I don't think this warrants as a BC break, as the errors are human readable and we don't promise BC on human readable console output (afaik, we don't promise BC on any console output, but I think we should be careful when changing e.g. the JSON logging).

</details>

This updated PR adds a new `--silent` verbosity mode that suppresses all output, including exceptions caught by the Application.

I went back and forth between simply passing `NullOutput` to the command in silent mode or not ignoring everything written to silent mode in `Output`. In the end, I've decided for the last to avoid bug reports from people silently expecting a `ConsoleOutputInterface` in their commands (e.g. for sections) without properly guarding it.

The new `isSilent()` methods can be used by commands to e.g. write important messages to the logger instead of command output when running in silent mode.

### CODE REVIEW

**Review by chalasr — APPROVED** [review]
Makes sense to me. Should we document it as a BC break given the behavior change is not opt-in?

**Comment by wouterj** [comment]
I'm not sure, I don't think we want to call this a BC break (or tag it as such) to give the wrong impression that command output is considered within the BC promise.

Let's also friendly ping @Seldaek who implemented the existing logic of showing errors during quiet verbosity. Do you remember a use-case for this? (something with Composer maybe?) Is there something we should take in mind before merging this PR?

**Comment by Seldaek** [comment]
IMO it is better to keep displaying it at least if you have a ConsoleOutputInterface where you can output on stderr. Any machine readable output would generally be expected on stdout. By default it will output to stderr so it won't disturb anything.

So I personally would close this, because yes when running quiet in some script/CI and something major breaks and you do not see it at all, it sucks. But that's just my view of course.

**Comment by Seldaek** [comment]
Note: I see the point about logging duplicating things, that's not great indeed. I am not sure how else this could be mitigated. I don't really see a way to safely do this, and IMO duplicating uncaught exception sure not great but still better as not seeing them at all.

**Comment by wouterj** [comment]
I get your point about stderr, however both stderr and stdout of processes are redirected to a container's output. So in hosting relying on containers, this is still an issue.

There are utils/techniques you can apply to hide the output of a command, but still get errors (based on exit codes). E.g. in the past, I've used the little [`chronic`](https://joeyh.name/code/moreutils/) bash utility for this in our CI. And you can also use bash one-liners like ``output=`mycommand 2>&1` || echo $output`` to accomplish this.

**Comment by Seldaek** [comment]
Ok, then I guess all I can ask is to maybe make this optional so that apps that are pure CLI apps like Composer and not 12-factor style symfony envs with full logger config could maybe retain the quiet-level output?

**Comment by ro0NL** [comment]
maybe we can detect if a logger is available?

**Comment by ro0NL** [comment]
see also 

```
bin/console messenger:consume test --quiet

09:55:32 CRITICAL  [messenger] Error thrown while handling message
```

**Comment by nicolas-grekas** [comment]
Let's resume this PR?

**Comment by wouterj** [comment]
Yes please :)

We need to make a decision (@symfony/mergers):

A) **Make `--quiet` completely silent, also for errors** (the current state of this PR).
This is a bit troubling for applications currently relying on seeing errors when running with quiet verbosity.
It however is much more compatible with 99% of the CLI tools in the world. Only getting output on error is still possible using the techniques I shared before.

B) **Add a new verbosity (e.g. `SHELL_VERBOSITY=-2`) that disables error output**.
No change of existing behavior, but introduces more work (and also requires discoverability) to get truly silent output like you get with other CLI tools.
Optionally, we might add some code in the `bin/console` recipe to default to `-2` when using `--quiet` to remove this extra barrier for upgraded applications.

**Comment by stof** [comment]
@wouterj using `2 > &1` and then complaining that it screws the processing of the output is void, as the screwing comes from the `2 > &1`, not from using stderr propertly in the first place.

Thus, cases that want to process the command output programmatically are probably not using `--quiet` anyway (as there would be not output to process)

**Comment by javiereguiluz** [comment]
@wouter I looked in other projects and some commands use special options for this:

* Google Cloud command has `--quiet` to hide interactive messages and `--no-user-output-enabled` to suppress printing anything in stdout or stderr (https://cloud.google.com/sdk/gcloud#suppressing_prompting_writing_to_the_terminal_and_logging)
* AWS commands have `--quiet` to not output information and `--only-show-errors` to suppress all output except errors and warnings (https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/cp.html?highlight=quiet)

About your proposals, I like this one --> **Add a new verbosity (e.g. SHELL_VERBOSITY=-2) that disables error output**

But, I wouldn't do this:

> Optionally, we might add some code in the bin/console recipe to default to -2 when using --quiet to remove this extra barrier for upgraded applications.

Having `--quiet` silently associated to a new verbosity different than quiet might look convenient but it might bite us in the future.

About possible naming of this new constant, AI suggested `silent` because "quiet" means that makes little or no noise and "silent" means that all noise is suppressed:

| Console option | SHELL_VERBOSITY value | Equivalent PHP constant
| -------------- | --------------------- | -----------------------
| `--silent` | `-2` | `OutputInterface::VERBOSITY_SILENT`
| `-q` or `--quiet` | `-1` | `OutputInterface::VERBOSITY_QUIET`
| (none) | `0` | `OutputInterface::VERBOSITY_NORMAL`
| `-v` | `1` | `OutputInterface::VERBOSITY_VERBOSE`
| `-vv` | `2` | `OutputInterface::VERBOSITY_VERY_VERBOSE`
| `-vvv` | `3` | `OutputInterface::VERBOSITY_DEBUG`

**Comment by kbond** [comment]
> About possible naming of this new constant, AI suggested silent because "quiet" means that makes little or no noise and "silent" means that all noise is suppressed:

This makes sense to me. +1 for `--silent` from me.

**Comment by fabpot** [comment]
Funnily enough, I encountered this issue yesterday. I was annoyed by the fact `--quiet` still displays the error. I wanted to remove all output and just rely on `$?/$status` to understand if the command failed. 

Having a new `--silent` flag sounds like a good compromise. I'm 👍

**Comment by OskarStark** [comment]
silent 🤫 is better wording 👌🏻

**Comment by wouterj** [comment]
Thanks for the feedback everyone!

PR is now updated with a new `--silent` option. Decided to not add a shortcut (`-s`), as this can be quite conflicting with shortcut options defined by commands (and Symfony itself already uses it in the `CompleteCommand`). Besides, when reading this discussion, the new mode is a special programmatic case anyways and we recommend people running commands manually to keep using `-q` instead.

**Review by javiereguiluz — APPROVED** [review]

**Comment by wouterj** [comment]
Low deps failure is unrelated, flipped test failure will be fixed by #58320 if I understand correctly.

**Review by kbond — COMMENTED** [review]
This is still considered a BC break?

**Comment by wouterj** [comment]
@kbond adding a new global option is always a BC break, as it'll break commands that defined this option before (you'll get an exception when registering that command).
I consider it a "minor backwards compatibility" that we allow in minor versions, but I thought it was good to flag it as BC break in the UPGRADE guide for better visibility.

**Review by kbond — APPROVED** [review]

File: src/Symfony/Component/Console/Style/OutputStyle.php [hunk 1]
```diff
@@ -78,6 +78,12 @@ public function getFormatter(): OutputFormatterInterface
         return $this->output->getFormatter();
     }
 
+    public function isSilent(): bool
+    {
+        // @deprecated since Symfony 7.2, change to $this->output->isSilent() in 8.0
+        return method_exists($this->output, 'isSilent') ? $this->output->isSilent() : false;
```
Comment (stof) [inline src/Symfony/Component/Console/Style/OutputStyle.php]: this should rather use `$this->output->getVerbosity() === self::VERBOSITY_SILENT` as fallback.

File: src/Symfony/Component/Console/Output/Output.php [hunk 2]
```diff
@@ -74,6 +75,11 @@ public function getVerbosity(): int
         return $this->verbosity;
     }
 
+    public function isSilent(): bool
+    {
+        return 8 === $this->verbosity;
```
Comment (stof) [inline src/Symfony/Component/Console/Output/Output.php]: please use the constant here

File: src/Symfony/Component/Console/Application.php [hunk 3]
```diff
@@ -1082,7 +1088,8 @@ protected function getDefaultInputDefinition(): InputDefinition
         return new InputDefinition([
             new InputArgument('command', InputArgument::REQUIRED, 'The command to execute'),
             new InputOption('--help', '-h', InputOption::VALUE_NONE, 'Display help for the given command. When no command is given display help for the <info>'.$this->defaultCommand.'</info> command'),
-            new InputOption('--quiet', '-q', InputOption::VALUE_NONE, 'Do not output any message'),
+            new InputOption('--silent', null, InputOption::VALUE_NONE, 'Do not output any message'),
+            new InputOption('--quiet', '-q', InputOption::VALUE_NONE, 'Only errors are displayed. All other output is suppressed'),
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Application.php:1092]:
```suggestion
            new InputOption('--quiet', '-q', InputOption::VALUE_NONE, 'Suppress all output, except errors'),
```
?

File: src/Symfony/Component/Console/Output/Output.php [hunk 4]
```diff
@@ -17,13 +17,14 @@
...
- * There are five levels of verbosity:
+ * There are six levels of verbosity:
  *
  *  * normal: no option passed (normal output)
  *  * verbose: -v (more output)
  *  * very verbose: -vv (highly extended output)
  *  * debug: -vvv (all debug output)
- *  * quiet: -q (no output)
+ *  * quiet: -q (only output errors)
+ *  * silent: --silent (no output)
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Output/Output.php:27]:
```suggestion
 *  * silent: (no output)
```
As the second column only shows shortcuts, we should not add `--silent` here, should we?

File: src/Symfony/Component/Console/Tests/Command/ListCommandTest.php [hunk 5]
```diff
@@ -80,7 +80,8 @@ public function testExecuteListsCommandsOrder()
 
 Options:
   -h, --help            Display help for the given command. When no command is given display help for the list command
-  -q, --quiet           Do not output any message
+      --silent          Do not output any message
+  -q, --quiet           Only errors are displayed. All other output is suppressed
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Tests/Command/ListCommandTest.php:84]: If you use the suggestion in my previous comment, this text should be changed accordingly

File: src/Symfony/Component/Console/Tests/Fixtures/application_1.json [hunk 6]
```diff
@@ -29,13 +29,22 @@
                         "description": "Display help for the given command. When no command is given display help for the <info>list</info> command",
                         "default": false
                     },
+                    "silent": {
+                        "name": "--silent",
+                        "shortcut": "",
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Tests/Fixtures/application_1.json:34]: Why don't we add `-s`? Is the chance to high to break an existing option which is shortcut to `s`?

File: src/Symfony/Component/Console/Tests/Fixtures/application_1.json [hunk 7]
```diff
@@ -29,13 +29,22 @@
...
+                        "default": false
+                    },
                     "quiet": {
                         "name": "--quiet",
                         "shortcut": "-q",
                         "accept_value": false,
                         "is_value_required": false,
                         "is_multiple": false,
-                        "description": "Do not output any message",
+                        "description": "Only errors are displayed. All other output is suppressed",
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Tests/Fixtures/application_1.json:47]: Same for this text

File: src/Symfony/Component/Console/Tests/Fixtures/application_1.json [hunk 8]
```diff
@@ -150,13 +159,22 @@
...
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Tests/Fixtures/application_1.json:177]: same for this text

File: src/Symfony/Component/Console/Tests/Fixtures/application_1.json [hunk 9]
```diff
@@ -262,13 +280,22 @@
...
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Tests/Fixtures/application_1.json:298]: same for this text

File: src/Symfony/Component/Console/Tests/Fixtures/application_1.json [hunk 10]
```diff
@@ -365,13 +392,22 @@
...
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Tests/Fixtures/application_1.json:410]: same for this text

File: src/Symfony/Component/Console/Tests/Fixtures/application_1.md [hunk 11]
```diff
@@ -58,6 +58,16 @@ Do not output any message
 * Is negatable: no
 * Default: `false`
 
+#### `--quiet|-q`
+
+Only errors are displayed. All other output is suppressed
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Tests/Fixtures/application_1.md:63]: same for this text

File: src/Symfony/Component/Console/Tests/Fixtures/application_1.md [hunk 12]
```diff
@@ -169,6 +179,16 @@ Do not output any message
...
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Tests/Fixtures/application_1.md:184]: same here

File: src/Symfony/Component/Console/Tests/Fixtures/application_1.md [hunk 13]
```diff
@@ -296,6 +316,16 @@ Do not output any message
...
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Tests/Fixtures/application_1.md:321]: same here

File: src/Symfony/Component/Console/Tests/Fixtures/application_1.txt [hunk 14]
```diff
@@ -5,7 +5,8 @@ Console Tool
 
 <comment>Options:</comment>
   <info>-h, --help</info>            Display help for the given command. When no command is given display help for the <info>list</info> command
-  <info>-q, --quiet</info>           Do not output any message
+  <info>    --silent</info>          Do not output any message
+  <info>-q, --quiet</info>           Only errors are displayed. All other output is suppressed
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Tests/Fixtures/application_1.txt:9]: same here

File: src/Symfony/Component/Console/Tests/Fixtures/application_1.xml [hunk 15]
```diff
@@ -32,9 +32,12 @@
         <option name="--help" shortcut="-h" accept_value="0" is_value_required="0" is_multiple="0">
           <description>Display help for the given command. When no command is given display help for the &lt;info&gt;list&lt;/info&gt; command</description>
         </option>
-        <option name="--quiet" shortcut="-q" accept_value="0" is_value_required="0" is_multiple="0">
+        <option name="--silent" shortcut="" accept_value="0" is_value_required="0" is_multiple="0">
           <description>Do not output any message</description>
         </option>
+        <option name="--quiet" shortcut="-q" accept_value="0" is_value_required="0" is_multiple="0">
+          <description>Only errors are displayed. All other output is suppressed</description>
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Tests/Fixtures/application_1.xml:39]: same here

File: src/Symfony/Component/Console/Tests/Fixtures/application_1.xml [hunk 16]
```diff
@@ -71,9 +74,12 @@
...
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Tests/Fixtures/application_1.xml:81]: Ok same for the following other text's 😄 ...

File: src/Symfony/Component/Console/Tests/Fixtures/application_1.json (hunk 6 above)
Comment (Seldaek) [reply src/Symfony/Component/Console/Tests/Fixtures/application_1.json:34]: Yeah let's please not do that. Too much BC risk and this is something you don't need often enough to justify a shortcut imo.

Comment (OskarStark) [reply src/Symfony/Component/Console/Tests/Fixtures/application_1.json:34]: Agree 👍

Comment (wouterj) [reply src/Symfony/Component/Console/Tests/Fixtures/application_1.json:34]: Yep, that was exactly my reasoning as well: https://github.com/symfony/symfony/pull/53632#issuecomment-2360876787

File: src/Symfony/Component/Console/Output/Output.php (hunk 4 above)
Comment (wouterj) [reply src/Symfony/Component/Console/Output/Output.php:27]: This is a list of the available verbosities and how to activate them using CLI options. Not showing one because there is no single-letter variant is much worse than showing one longer option imho.

File: src/Symfony/Component/Console/Application.php (hunk 3 above)
Comment (wouterj) [reply src/Symfony/Component/Console/Application.php:1092]: I've copy pasted the original from the AWS CLI, I have no strong opinion between the two.

Unless someone has a strong opinion, I would prefer not to have to update it 100 times in the test suite again :wink:

Comment (OskarStark) [reply src/Symfony/Component/Console/Application.php:1092]: Fine then

**Review by OskarStark — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @wouterj.
