### PR TITLE
[Webhook] decouple the Webhook component from the Serializer component

### LINKED ISSUE #57567: [Webhook] SerializerInterface is not actually needed
### Symfony version(s) affected

7.x

### Description

```
You cannot use the "webhook transport" service since the Serializer component is not installed. Try running "composer require symfony/serializer-pack". 
```
A quick search shows that this line is the only place where the serializer is used in the webhook component.

https://github.com/symfony/webhook/blob/67762b59de4b9e3c6918c44a345f59030923b82d/Server/JsonBodyConfigurator.php#L24

To be fair I don't think this is a bug, however serializer is not really needed to encode the event payload since it's always `array`, `json_encode` is fine.

### How to reproduce

Create a  new `SendWebhookMessage` then dispatch it without installing the serializer

### Possible Solution

Remove `SerializerInterface` and replace 

```php
$body = $this->serializer->serialize($event->getPayload(), 'json');
```
with
```php
$body = \json_encode($event->getPayload());
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #57567
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/Webhook/Server/JsonPayloadEncoder.php [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\Webhook\Server;
+
+final class JsonPayloadEncoder implements PayloadEncoderInterface
+{
+    public function encode(array $payload): string
+    {
+        return json_encode($payload);
```
Comment (derrabus) [inline src/Symfony/Component/Webhook/Server/JsonPayloadEncoder.php]:
```suggestion
        return json_encode($payload, \JSON_THROW_ON_ERROR);
```

File: src/Symfony/Component/Webhook/Tests/Server/JsonBodyConfiguratorTest.php [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+        $httpOptions->setHeaders([
+            'Webhook-Event' => 'event-name',
+            'Webhook-Id' => 'event-id',
+        ]);
+
+        $configurator = new JsonBodyConfigurator($payloadEncoder);
+        $configurator->configure(new RemoteEvent('event-name', 'event-id', $payload), 's3cr3t', $httpOptions);
+    }
+
+    public function testPayloadWithSerializer()
```
Comment (derrabus) [inline src/Symfony/Component/Webhook/Tests/Server/JsonBodyConfiguratorTest.php:44]: Shall we test that the encoded payload returned by the serializer is actually used?

File: src/Symfony/Component/Webhook/Server/JsonBodyConfigurator.php [hunk 3]
```diff
@@ -20,14 +20,22 @@
...
-        private readonly SerializerInterface $serializer,
-    ) {
+    private PayloadEncoderInterface $payloadEncoder;
+
+    public function __construct(SerializerInterface|PayloadEncoderInterface|null $payloadEncoder = null)
+    {
+        if (null === $payloadEncoder) {
+            $this->payloadEncoder = new JsonPayloadEncoder();
+        } elseif ($payloadEncoder instanceof SerializerInterface) {
+            $this->payloadEncoder = new SerializerPayloadEncoder($payloadEncoder);
```
Comment (derrabus) [inline src/Symfony/Component/Webhook/Server/JsonBodyConfigurator.php]: We could consider deprecating passing a serializer instance, now that we have a dedicated contract for this dependency.

File: src/Symfony/Component/Webhook/CHANGELOG.md [hunk 4]
```diff
@@ -1,6 +1,9 @@
 CHANGELOG
 =========
 
+7.2
+---
+
```
Comment (derrabus) [inline src/Symfony/Component/Webhook/CHANGELOG.md:6]: 🙃

File: src/Symfony/Component/Webhook/Tests/Server/JsonBodyConfiguratorTest.php (hunk 2 above)
Comment (xabbuh) [reply src/Symfony/Component/Webhook/Tests/Server/JsonBodyConfiguratorTest.php:44]: done

File: src/Symfony/Component/Webhook/Server/JsonBodyConfigurator.php (hunk 3 above)
Comment (xabbuh) [reply src/Symfony/Component/Webhook/Server/JsonBodyConfigurator.php]: I thought about that as well, but as I don't see any downside in using the serializer directly I didn't want to impose the need to change anything on users of the component.

File: src/Symfony/Component/Webhook/CHANGELOG.md [hunk 5]
```diff
@@ -1,6 +1,11 @@
...
+ * Add `PayloadEncoderInterface` with and implementations to decouple the remote event handling from the Serializer component
```
Comment (derrabus) [inline src/Symfony/Component/Webhook/CHANGELOG.md]:
```suggestion
 * Add `PayloadEncoderInterface` with implementations to decouple the remote event handling from the Serializer component
```

File: src/Symfony/Component/Webhook/Server/JsonBodyConfigurator.php [hunk 6]
```diff
@@ -20,14 +20,22 @@
...
+
+    public function __construct(SerializerInterface|PayloadEncoderInterface|null $payloadEncoder = null)
+    {
+        if (null === $payloadEncoder) {
+            $this->payloadEncoder = new NativeJsonPayloadEncoder();
+        } elseif ($payloadEncoder instanceof SerializerInterface) {
+            $this->payloadEncoder = new SerializerPayloadEncoder($payloadEncoder);
+        } else {
+            $this->payloadEncoder = $payloadEncoder;
+        }
```
Comment (yceruto) [inline src/Symfony/Component/Webhook/Server/JsonBodyConfigurator.php]: Can we compute all these conditionals externally and inject the appropriate service instead? This would also remove the null type in the constructor and the notion that this configurator requires an optional encoder

File: src/Symfony/Component/Webhook/Server/JsonBodyConfigurator.php [hunk 7]
```diff
@@ -20,14 +20,22 @@
  */
 final class JsonBodyConfigurator implements RequestConfiguratorInterface
 {
-    public function __construct(
-        private readonly SerializerInterface $serializer,
-    ) {
+    private PayloadEncoderInterface $payloadEncoder;
+
+    public function __construct(SerializerInterface|PayloadEncoderInterface|null $payloadEncoder = null)
```
Comment (yceruto) [inline src/Symfony/Component/Webhook/Server/JsonBodyConfigurator.php]: should we also deprecate passing an instance of SerializerInterface? I think the final signature in 8.0 could be just `PayloadEncoderInterface $payloadEncoder`

File: src/Symfony/Component/Webhook/Server/JsonBodyConfigurator.php (hunk 6 above)
Comment (xabbuh) [reply src/Symfony/Component/Webhook/Server/JsonBodyConfigurator.php]: yes indeed, good idea 👍

File: src/Symfony/Component/Webhook/Server/JsonBodyConfigurator.php (hunk 7 above)
Comment (xabbuh) [reply src/Symfony/Component/Webhook/Server/JsonBodyConfigurator.php]: see https://github.com/symfony/symfony/pull/57881#discussion_r1696559863

**Review by nicolas-grekas — APPROVED** [review]

**Review by yceruto — APPROVED** [review]

**Review by fabpot — APPROVED** [review]
Out of curiosity, why use `encoder` instead of `serializer`?

**Comment by xabbuh** [comment]
@fabpot I didn't want to confuse readers of the code by using the term serializer for two different things (the Serializer component and the part that I named encoder here). But I am open for other names.

**Comment by fabpot** [comment]
Serialization and encoding are two different concepts. Having `SerializerInterface|PayloadEncoderInterface` looks weird to me. I would use `PayloadSerializerInterface` instead.

**Comment by xabbuh** [comment]
@fabpot I renamed the new classes

**Review by stof — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 8]
```diff
@@ -548,7 +548,7 @@ public function load(array $configs, ContainerBuilder $container): void
         $this->registerProfilerConfiguration($config['profiler'], $container, $loader);
 
         if ($this->readConfigEnabled('webhook', $container, $config['webhook'])) {
-            $this->registerWebhookConfiguration($config['webhook'], $container, $loader);
+            $this->registerWebhookConfiguration($config['webhook'], $container, $loader, $this->readConfigEnabled('serializer', $container, $config['serializer']));
 
             // If Webhook is installed but the HttpClient or Serializer components are not available, we should throw an error
```
Comment (faizanakram99) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:553]: outdated comment

Comment (OskarStark) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:553]: * https://github.com/symfony/symfony/pull/58026
