### PR TITLE
[ObjectMapper] mapping of nested classes with promoted read-only properties

### LINKED ISSUE #62442: [ObjectMapper] Lazy loading breaks mapping of nested classes with promoted read-only properties
### Symfony version(s) affected

7.4.x-dev

### Description

The lazy loading feature added by [1e22b511d1a219099c89d39c2c4d6ce340566cf7](https://github.com/symfony/object-mapper/commit/1e22b511d1a219099c89d39c2c4d6ce340566cf7) prevents ObjectMapper from setting property values in nested classes when the properties themselves are promoted + read-only.

### How to reproduce

1. Create an empty project directory
2. `composer require symfony/object-mapper:7.4.x-dev#1e22b511d1a219099c89d39c2c4d6ce340566cf7`
3. Run the following test script:

```php
<?php

declare(strict_types=1);

use Symfony\Component\ObjectMapper\Attribute\Map;
use Symfony\Component\ObjectMapper\ObjectMapper;

require __DIR__ . '/vendor/autoload.php';

final readonly class BMapped {
    public function __construct(
        public string $var2,
    ) {}
}

final readonly class AMapped {
    public function __construct(
        public BMapped $b,
        public string $var1,
    ) {}
}

#[Map(target: BMapped::class)]
final readonly class B {
    public function __construct(
        public string $var2,
    ) {}
}

#[Map(target: AMapped::class)]
final readonly class A {
    public function __construct(
        public B $b,
        public string $var1,
    ) {}
}

/** @var AMapped $out */
$out = new ObjectMapper()->map(
    source: new A(
        b: new B(
            var2: 'bar',
        ),
        var1: 'foo',
    ),
);
var_dump($out);
echo $out->b->var2;
```

4. Observe the error:

```
class AMapped#9 (2) {
  public readonly BMapped $b =>
  class BMapped#22 (1) {
    public readonly string $var2 =>
    *uninitialized*
  }
  public readonly string $var1 =>
  string(3) "foo"
}
PHP Fatal error:  Uncaught Error: Cannot modify readonly property BMapped::$var2 in /home/meinemitternacht/projects/symfony-object-mapper-test-1e22b511/vendor/symfony/object-mapper/ObjectMapper.php:189
Stack trace:
#0 /home/meinemitternacht/projects/symfony-object-mapper-test-1e22b511/vendor/symfony/object-mapper/ObjectMapper.php(49): Symfony\Component\ObjectMapper\ObjectMapper->doMap()
#1 /home/meinemitternacht/projects/symfony-object-mapper-test-1e22b511/vendor/symfony/object-mapper/ObjectMapper.php(253): Symfony\Component\ObjectMapper\ObjectMapper->map()
#2 /home/meinemitternacht/projects/symfony-object-mapper-test-1e22b511/test.php(48): Symfony\Component\ObjectMapper\ObjectMapper->{closure:Symfony\Component\ObjectMapper\ObjectMapper::getSourceValue():249}()
#3 {main}
  thrown in /home/meinemitternacht/projects/symfony-object-mapper-test-1e22b511/vendor/symfony/object-mapper/ObjectMapper.php on line 189
```

5. `composer require symfony/object-mapper:7.4.x-dev#640f739151985e5618e61a6b043859c627b1b255` (previous commit)

6. Observe a successful result:

```
class AMapped#9 (2) {
  public readonly BMapped $b =>
  class BMapped#19 (1) {
    public readonly string $var2 =>
    string(3) "bar"
  }
  public readonly string $var1 =>
  string(3) "foo"
}
bar
```

7. Optionally, provide `symfony/property-access` to get a different error message:

```
class AMapped#22 (2) {
  public readonly BMapped $b =>
  class BMapped#37 (1) {
    public readonly string $var2 =>
    *uninitialized*
  }
  public readonly string $var1 =>
  string(3) "foo"
}
PHP Fatal error:  Uncaught Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: The property "var2" in class "BMapped" is a promoted readonly property.. in /home/meinemitternacht/projects/symfony-object-mapper-test-1e22b511/vendor/symfony/property-access/PropertyAccessor.php:542
Stack trace:
#0 /home/meinemitternacht/projects/symfony-object-mapper-test-1e22b511/vendor/symfony/property-access/PropertyAccessor.php(120): Symfony\Component\PropertyAccess\PropertyAccessor->writeProperty()
#1 /home/meinemitternacht/projects/symfony-object-mapper-test-1e22b511/vendor/symfony/object-mapper/ObjectMapper.php(189): Symfony\Component\PropertyAccess\PropertyAccessor->setValue()
#2 /home/meinemitternacht/projects/symfony-object-mapper-test-1e22b511/vendor/symfony/object-mapper/ObjectMapper.php(49): Symfony\Component\ObjectMapper\ObjectMapper->doMap()
#3 /home/meinemitternacht/projects/symfony-object-mapper-test-1e22b511/vendor/symfony/object-mapper/ObjectMapper.php(253): Symfony\Component\ObjectMapper\ObjectMapper->map()
#4 /home/meinemitternacht/projects/symfony-object-mapper-test-1e22b511/test.php(56): Symfony\Component\ObjectMapper\ObjectMapper->{closure:Symfony\Component\ObjectMapper\ObjectMapper::getSourceValue():249}()
#5 {main}
  thrown in /home/meinemitternacht/projects/symfony-object-mapper-test-1e22b511/vendor/symfony/property-access/PropertyAccessor.php on line 542
  ```

### Possible Solution

Perhaps `#[Map]` can have an option added to disable lazy loading for a particular source+target pair, or another attribute can be added at the class-level that directs the mapper to use the previous behavior.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62442
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/ObjectMapper/Tests/Fixtures/ReadOnlyPromotedProperty/ReadOnlyPromotedPropertyA.php [hunk 1]
```diff
@@ -0,0 +1,16 @@
+<?php
+
+declare(strict_types=1);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/Tests/Fixtures/ReadOnlyPromotedProperty/ReadOnlyPromotedPropertyA.php]: please remove them all

File: src/Symfony/Component/ObjectMapper/Tests/Fixtures/ReadOnlyPromotedProperty/ReadOnlyPromotedPropertyA.php [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+
+use Symfony\Component\ObjectMapper\Attribute\Map;
+
+#[Map(target: ReadOnlyPromotedPropertyAMapped::class)]
+final class ReadOnlyPromotedPropertyA
+{
+    public function __construct(
+        public ReadOnlyPromotedPropertyB $b,
+        public string $var1,
+    ) {}
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/Tests/Fixtures/ReadOnlyPromotedProperty/ReadOnlyPromotedPropertyA.php]: same below
```suggestion
    ) {
    }
```

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @soyuka.

File: src/Symfony/Component/ObjectMapper/Tests/Fixtures/ReadOnlyPromotedProperty/ReadOnlyPromotedPropertyA.php (hunk 1 above)
Comment (lrynek) [reply src/Symfony/Component/ObjectMapper/Tests/Fixtures/ReadOnlyPromotedProperty/ReadOnlyPromotedPropertyA.php]: @nicolas-grekas just out of curiosity - why is that required to be removed? 🤔

Comment (nicolas-grekas) [reply src/Symfony/Component/ObjectMapper/Tests/Fixtures/ReadOnlyPromotedProperty/ReadOnlyPromotedPropertyA.php]: because we don't use strict types in the codebase
you might want to read some discussion about this in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/8877
