### PR TITLE
[Form] read form values using the chain data accessor

### LINKED ISSUE #48167: [Form] Overriding only `getter` causes exceptions while submitting
### Symfony version(s) affected

5.2.0 upwards

### Description

Symfony 5.2 introduced the `getter` and `setter` options for form types, but the separation is not complete causing exceptions during form submission.

### How to reproduce

Consider this use case on an object tree inheriting settings:
```php
    private ?int $value;
    
    public function setValue(?int $newValue): void
    {
        $this->value = $newValue;
    }

    public function getConfiguredValue(): ?int
    {
        return $this->value;
    }

    public function getActualValue(): int
    {
        return $this->value ?? $this->parent->getActualValue();
    }
```
In this case, the getter is not called `getValue` on purpose, to avoid confusion with programmers calling the wrong one. Since Symfony 5.2 I can now map this in a form:
```php
    $builder
        ->add('value', IntegerType::class, [
            'getter' => fn($object) => $object->getConfiguredValue(),
        ])
```
This works *fine* to render the form. Submitting it however crashes with a `NoSuchPropertyException`, stating `Can't get a way to read the property "value" in class XXX`. Note that it doesn't know how to *read* the property: this is because there is no `setter` defined, as the default works fine, and as such the `PropertyPathAccessor` is used to set the value, which reads the property to detect changes first, is blissfully unaware of the `getter` option, and therefore tries to read the propery via the accessor.

### Possible Solution

Right now the only working solution without modifying the original object is to add a `setter` as well, which is pure boilerplate as it does nothing special:
```php
          'setter' => function($object, ?int $newValue) {
              $object->setValue($newValue);
          },
```

So solutions we could implement are:
 - Make `getter` and `setter` mandatory in pairs - setting one requires the other. This is currently in practice enforced by the implementation, yet it does not throw an error if you don't. Seems weak as in the given example the setter is completely obsolete.
 - Make the DataAccessor properly aware of the existence of a `getter` when defaulting the set behavior, bypassing default PropertyAccess behavior that tries to read the property for changes.

Obviously the second solution is far more correct and better, it is also more complex and may introduce new edge cases.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #48167
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/Form/Extension/Core/Type/FormType.php [hunk 1]
```diff
@@ -33,10 +33,13 @@ class FormType extends BaseType
...
     {
-        $this->dataMapper = new DataMapper(new ChainAccessor([
+        $propertyPathAccessor = new PropertyPathAccessor($propertyAccessor ?? PropertyAccess::createPropertyAccessor());
+        $dataAccessor = new ChainAccessor([
             new CallbackAccessor(),
-            new PropertyPathAccessor($propertyAccessor ?? PropertyAccess::createPropertyAccessor()),
-        ]));
+            $propertyPathAccessor,
+        ]);
+        $propertyPathAccessor->setReadAccessor($dataAccessor);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Extension/Core/Type/FormType.php]: Too bad this creates a circular ref. Any way around?

(don't miss adding a test case of course ;) )

**Review by yceruto — APPROVED** [review]
LGTM, can you add a test case covering this scenario?

File: src/Symfony/Component/Form/Extension/Core/Type/FormType.php (hunk 1 above)
Comment (yceruto) [reply src/Symfony/Component/Form/Extension/Core/Type/FormType.php]: I thought about it too, but it's only possible if someone configures the chain on their own; otherwise, it will call the getter accessor (which is detached from the setter).

**Comment by xabbuh** [comment]
test added

File: src/Symfony/Component/Form/Extension/Core/Type/FormType.php (hunk 1 above)
Comment (xabbuh) [reply src/Symfony/Component/Form/Extension/Core/Type/FormType.php]: With the current architecture there is no way around it. If we were to design the interface again with the knowledge we have now, we would probably do something like optionally passing a read accessor around when calling `setValue()`.

Comment (xabbuh) [reply src/Symfony/Component/Form/Extension/Core/Type/FormType.php]: I think I found a better solution that does not involve creating the circular reference

**Review by nicolas-grekas — APPROVED** [review]

**Review by yceruto — APPROVED** [review]
