### PR TITLE
[Form] Fix ICU 72+ whitespace handling in `DateTimeToLocalizedStringTransformer`

### LINKED ISSUE #60178: [Form] compatibility with ICU > 7.1 in `DateTimeToLocalizedStringTransformer`
### Symfony version(s) affected

6.4, 7.2, 7.3

### Description

Up to ICU 71.1 a user could submit a date like `Feb 3, 2010, 04:05 AM` which was properly handled by the `DateTimeToLocalizedStringTransformer`. With ICU 72+ this no longer works as the format ICU expects has slightly changed for many different date formats (for example, in the example string it expects a "thin space" before `AM`).

### How to reproduce

see the `DateTimeToLocalizedStringTransformerTest::testReverseTransformFromDifferentLocale()` test

### Possible Solution

_No response_

### Additional Context

[ICU 72 release notes](https://icu.unicode.org/download/72)

### PR DESCRIPTION
**Pull request by roukmoute**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60178
| License       | MIT

## Summary

ICU 72+ uses Unicode whitespace characters (such as U+202F narrow no-break space) in formatted date strings instead of regular ASCII spaces. This caused parsing failures when users typed dates with regular spaces.

This fix:
- Normalizes `transform()` output to use regular ASCII spaces for consistent display
- Makes `reverseTransform()` accept both regular spaces and ICU 72+ whitespace by trying both formats when parsing fails

## How it works

1. **`transform()`**: After formatting with `IntlDateFormatter`, the output is normalized to replace special Unicode whitespace (U+00A0, U+202F, U+2009) with regular ASCII spaces (U+0020).

2. **`reverseTransform()`**: A new `parse()` method tries to parse the input as-is first. If parsing fails and the input contains regular spaces, it retries by replacing regular spaces with U+202F (the narrow no-break space used by ICU 72+).

This ensures:
- Users can type dates with regular spaces
- Copy-pasted dates from older ICU versions work
- The displayed output is consistent across ICU versions

## Test

The previously skipped test `testReverseTransformFromDifferentLocale` now works with all ICU versions.

### CODE REVIEW

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php [hunk 1]
```diff
@@ -177,4 +182,48 @@ protected function isPatternDateOnly(): bool
...
+
+        // If parsing failed and the value contains regular spaces, try with ICU 72+ whitespace
+        if ((false === $timestamp || 0 !== intl_get_error_code()) && str_contains($value, ' ')) {
+            $icuValue = str_replace(' ', self::NARROW_NO_BREAK_SPACE, $value);
+            intl_get_error_code(); // Clear previous error
+
+            try {
+                $timestamp = @$dateFormatter->parse($icuValue);
+            } catch (\IntlException) {
+                // Ignore, we'll use the original error below
```
Comment (stof) [inline src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php:239]: there is no place using it

Comment (roukmoute) [reply src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php:239]: Thanks @stof\! You're right, `intl_get_error_code()` only returns the error code, it doesn't clear it. Removed the useless line.

File: src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformerTest.php [hunk 2]
```diff
@@ -235,15 +234,11 @@ public function testReverseTransformFullTime()
...
-        if (version_compare(Intl::getIcuVersion(), '71.1', '>')) {
-            $this->markTestSkipped('ICU version 71.1 or lower is required.');
-        }
-
         \Locale::setDefault('en_US');
 
         $transformer = new DateTimeToLocalizedStringTransformer('UTC', 'UTC');
 
-        $this->assertDateTimeEquals($this->dateTimeWithoutSeconds, $transformer->reverseTransform('Feb 3, 2010, 04:05 AM'));
+        $this->assertDateTimeEquals($this->dateTimeWithoutSeconds, $transformer->reverseTransform('Feb 3, 2010, 4:05 AM'));
```
Comment (xabbuh) [inline src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformerTest.php]:
```suggestion
        $this->assertDateTimeEquals($this->dateTimeWithoutSeconds, $transformer->reverseTransform('Feb 3, 2010, 04:05 AM'));
```

I suggest to keep it as is since users also won't change what they type just because the ICU version on the application side changes.

Comment (roukmoute) [reply src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformerTest.php]: I've made the correction, thank you for your keen eye!

**Review by nicolas-grekas — APPROVED** [review]
rebased for 6.4 since that's the oldest maintained version affected

**Comment by nicolas-grekas** [comment]
Thank you @roukmoute.
