### PR TITLE
[Validator] Add ValidatorBuilder::enablePropertyMetadataExistenceCheck()

### LINKED ISSUE #62198: Validator - validateProperty() and validatePropertyValue() give no feedback if the property does not exist
### Symfony version(s) affected

7.3.5

### Description

Hi folks,

I have tests that execute code like this:
```
$violations = $validator->validatePropertyValue($object, 'someProperty', $value);
```
and I noticed that if `someProperty` does not exist, there is no warning or error raised. This leads me to mistakenly believe my test is working, when actually it's not performing any checks at all.

The same issue exists with the `validateProperty()` method:
```
$violations = $validator->validateProperty($object, 'someProperty');
```

If a property is removed or renamed, and associated tests are not updated, then I would like to see a warning, error, violation, or _something_.

Thanks

### How to reproduce

```
$object = new stdClass();
$violations = $validator->validatePropertyValue($object, 'propertyThatDoesNotExist', 'test');
$violations = $validator->validateProperty($object, 'propertyThatDoesNotExist');
```

### Possible Solution

In `RecursiveContextualValidator.php` for both the `validateProperty` and `validatePropertyValue` methods, add a check for the property. For example:

```
if (!$classMetadata->hasPropertyMetadata($propertyName)) {
    throw new ValidatorException(\sprintf('The property "%s" does not exist.', $propertyName));
}
```

I would also be happy with a `trigger_error()` or any other appropriate notification.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lacatoire**
| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Issues        | Fix #62198
| License       | MIT

As suggested by @nicolas-grekas in #62198, this PR adds an opt-in `ValidatorBuilder::enablePropertyMetadataExistenceCheck()` method.

When enabled, `validateProperty()` and `validatePropertyValue()` throw a `ValidatorException` if the given property has no metadata (i.e. no constraints defined), instead of silently returning zero violations. This helps catch typos or renamed properties in tests.

The check is opt-in to avoid BC breaks, since "no metadata" currently means "no constraints" rather than "property is invalid".

### CODE REVIEW

**Review by nicolas-grekas — COMMENTED** [review]
Thanks for this.
Reading the description and the name makes me wonder if `enablePropertyMetadataExistenceCheck` wouldn't be more appropriate?

File: src/Symfony/Component/Validator/Tests/Validator/RecursiveValidatorTest.php [hunk 1]
```diff
@@ -2375,4 +2376,46 @@ public function validate($value, Constraint $constraint): void
             ->validate($value, null, new GroupSequence(['should_pass']))
             ->validate($value, null, new GroupSequence(['should_fail']));
     }
+
+    public function testValidatePropertyWithExistenceCheckThrowsOnNonExistentProperty()
+    {
+        $this->expectException(ValidatorException::class);
+        $this->expectExceptionMessage('The property "nonExistent" does not exist');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Tests/Validator/RecursiveValidatorTest.php]:
```suggestion
        $this->expectExceptionMessage('The property "nonExistent" has not metadata associated and may not exist.');
```

File: src/Symfony/Component/Validator/ValidatorBuilder.php [hunk 2]
```diff
@@ -324,6 +325,20 @@ public function disableTranslation(): static
         return $this;
     }
 
+    /**
+     * Enables checking that a property exists when using validateProperty()
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/ValidatorBuilder.php]: should be tweaked

**Review by nicolas-grekas — COMMENTED** [review]
let's also add a line about this in the changelog of the component

**Comment by nicolas-grekas** [comment]
Thank you @lacatoire.

**Comment by stof** [comment]
this PR misses the FrameworkBundle wiring to allow using the feature in the framework.
