### PR TITLE
[Routing] Disallow object usage inside Route

### LINKED ISSUE #27723: [Routing] PhpMatcherDumper produces bad code with objects exports
**Symfony version(s) affected**: all ?

**Description**  
The `PhpMatcherDumper::export` method creates invalid code when a route attribute is an object.

**How to reproduce**  

In symfony repository, run : 
```bash
php -r 'include __DIR__."/vendor/autoload.php"; class A { private $a; }; $export = \Symfony\Component\Routing\Matcher\Dumper\PhpMatcherDumper::export(new A); echo "$export\n"; eval("${export};");'
```
And it will produce 
```php
A::__set_state(array('."\n".'   'a' => NULL,'."\n".'))
```
```
PHP Parse error:  syntax error, unexpected ''a'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in Command line code(1) : eval()'d code on line 1
```

**Possible Solution**  

[A patch is available here](https://github.com/symfony/symfony/compare/master...paxal:fix/php_matcher_dumper_export_class) and a pull request can be done.

The patch might break the formatting rules inside the `export` method, and I don't know why it's there.

**Additional context**  
I don't know if the patch is a good idea, because a lot of solutions exist to deal with the issue : 
* serialize the object (using `serialize` or `var_export`) before setting the attribute to the route, thus setting it to a string value ;
* use a reference and get the value in a cache pool or provider service ;
* the object creation at each request might not be a good idea for mem/cpu perfs ‒ that's why I preferred to use another way to get my object, only when needed.

### PR DESCRIPTION
**Pull request by paxal**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | ?
| Fixed tickets | #27723 
| License       | MIT
| Doc PR        | ✘

As discussed in #27723 the `Route` object should not support nested objects as attributes (`requirements`, `defaults`, ...).

Thus, if detected, an `\InvalidArgumentException` will be thrown.

Will fix #27723

### CODE REVIEW

**Review by stof — APPROVED** [review]

File: src/Symfony/Component/Routing/Matcher/Dumper/PhpMatcherDumper.php [hunk 1]
```diff
@@ -746,6 +746,10 @@ public static function export($value): string
             return 'null';
         }
         if (!\is_array($value)) {
+            if (\is_object($value)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Routing/Matcher/Dumper/PhpMatcherDumper.php]: `if (\is_object($value) && !method_exists($value, '__set_state')) {`

File: src/Symfony/Component/Routing/Matcher/Dumper/PhpMatcherDumper.php [hunk 2]
```diff
@@ -746,6 +746,10 @@ public static function export($value): string
...
+                throw new \InvalidArgumentException('Symfony\Component\Routing\Route cannot contain objects');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Routing/Matcher/Dumper/PhpMatcherDumper.php]: missing dot at end of message

**Review by nicolas-grekas — COMMENTED** [review]
For 4.1 as bug fix? the issue also exists on 2.8, but there we don't have an "export" method as we rely only on `var_export()`.

File: src/Symfony/Component/Routing/Matcher/Dumper/PhpMatcherDumper.php (hunk 1 above)
Comment (stof) [reply src/Symfony/Component/Routing/Matcher/Dumper/PhpMatcherDumper.php]: even objects with `__set_state` are broken, as the logic currently replaces new lines by a concatenation with `"\n"` instead (because when var_export-ing a scalar, new lines appear only inside strings).

If we want to keep support for objects with `__set_state`, it should be handled as a separate case (and I would put it before the `if (!is_array())` case then, rather than nesting in it)

Comment (nicolas-grekas) [reply src/Symfony/Component/Routing/Matcher/Dumper/PhpMatcherDumper.php]: > even objects with __set_state are broken

indeed, then let's keep it unsupported :)

Comment (paxal) [reply src/Symfony/Component/Routing/Matcher/Dumper/PhpMatcherDumper.php]: The purpose of this PR is to disallow object usage, and avoid to export objects (via `var_export`). Thus, the fact that `__set_state` exists or not is not relevant. The dumped file does not work when we export an object (because of `\n` replacements).

File: src/Symfony/Component/Routing/Matcher/Dumper/PhpMatcherDumper.php (hunk 2 above)
Comment (paxal) [reply src/Symfony/Component/Routing/Matcher/Dumper/PhpMatcherDumper.php]: Fixed and squashed.

**Review by nicolas-grekas — APPROVED** [review]
(for 4.1)

**Comment by nicolas-grekas** [comment]
Thank you @paxal.
