### PR TITLE
[Console] Improve Table rendering performance

### LINKED ISSUE #63630: Performance bottlenecks on table-rendering
### Symfony version(s) affected

5.4.47

### Description

when rendering [tables with 30.000+ rows in PHPStan](https://github.com/phpstan/phpstan/issues/14232) we see performance bottlenecks in symfony/console.

Image

in PHPStan we now "workaround" this problem by only rendering 1000 errors when print results in a end-user friendly format.
this changed saved us 20 seconds when printing a result table with 30.000 rows.

we did not try running on newer symfony versions, as we currently cannot update because of the php min-version we need to support for PHPStan.

### How to reproduce

- checkout wordpress-develop https://github.com/WordPress/wordpress-develop.git on commit 9b8960334b93b66f4d1004ce2d1b4beb72a5c203
- `composer install`
- make sure you are using PHPStan 2.1.40 (newer versions have a fix)
- adjust the `phpstan.neon.dist` to the following
```
parameters:
    level: 9
    phpVersion: 80000
    paths:
        - src
        - tests
    excludePaths:
        - src/js
    tmpDir: /tmp/phpstan
```
- run `vendor/bin/phpstan analyze` to let it build up its caches
- run `vendor/bin/phpstan analyze` again (it will need no time for analysis, because no sources changes. it will only print the results which alone takes 20-30 seconds - depending on the used computer)

### Possible Solution

maybe there is some room for perf improvements. just wanted to leave this here in case someone is interessted in improving it.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Amoifr**
| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63630
| License       | MIT

This PR improves table rendering performance by ~90% for large tables (30K+ rows).

| Rows   | Before  | After   | Improvement |
|--------|---------|---------|-------------|
| 1,000  | 0.69s   | 0.055s  | -92%        |
| 5,000  | 2.74s   | 0.29s   | -89%        |
| 10,000 | 7.15s   | 0.56s   | -92%        |
| 30,000 | 17.6s   | 1.74s   | -90%        |

Changes:
- Refactor `calculateColumnsWidth()` from O(columns × rows) to O(rows) by using a single pass
- Add fast path in `Helper::removeDecoration()` for strings without formatting markers
- Add fast path in `Helper::width()` for ASCII-only strings (avoids `UnicodeString` instantiation)

### CODE REVIEW

**Comment by stof** [comment]
Refactoring for performance improvement is generally not treated as a bugfix, so this should target the 8.1 branch.

**Comment by Amoifr** [comment]
Done, rebased on 8.1. Thanks @stof!

File: src/Symfony/Component/Console/Helper/Table.php [hunk 1]
```diff
@@ -879,17 +893,19 @@ private function getColumnSeparatorWidth(): int
...
 
         if (isset($row[$column])) {
             $cell = $row[$column];
-            $cellWidth = Helper::width(Helper::removeDecoration($this->output->getFormatter(), $cell));
+            $cellWidth = Helper::width(Helper::removeDecoration($formatter ?? $this->output->getFormatter(), $cell));
         }
 
         $columnWidth = $this->columnWidths[$column] ?? 0;
-        $cellWidth = max($cellWidth, $columnWidth);
+        if ($columnWidth > $cellWidth) {
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Helper/Table.php]: So we really need this change here?

Comment (Amoifr) [reply src/Symfony/Component/Console/Helper/Table.php]: You're right, `max()` is cleaner and the performance gain here is negligible compared to the algorithm refactoring. I'll revert this to keep it readable. Thanks for the review\! 🙏

Comment (OskarStark) [reply src/Symfony/Component/Console/Helper/Table.php]: We should also keep the diff as small as possible

Comment (Amoifr) [reply src/Symfony/Component/Console/Helper/Table.php]: I don not share totally this point of view ... but ok.

File: src/Symfony/Component/Console/Helper/Table.php [hunk 2]
```diff
@@ -879,13 +893,13 @@ private function getColumnSeparatorWidth(): int
         return Helper::width(\sprintf($this->style->getBorderFormat(), $this->style->getBorderChars()[3]));
     }
 
-    private function getCellWidth(array $row, int $column): int
+    private function getCellWidth(array $row, int $column, ?OutputFormatterInterface $formatter = null): int
```
Comment (staabm) [inline src/Symfony/Component/Console/Helper/Table.php]: whats the point of the optional new parameter? is `$this->output->getFormatter()` expensive?

in case we need the new parameter, it seems it can be non-optional and we don't need the fallback to `?? $this->output->getFormatter()` as it is used only used once in this class and already fed by `$this->output->getFormatter()`?

**Comment by Amoifr** [comment]
@staabm Good catch! You're right, the fallback was unnecessary since the parameter is always provided from `calculateColumnsWidth()`. Fixed in 200cceea8b – made the parameter non-optional.

File: src/Symfony/Component/Console/Helper/Table.php [hunk 3]
```diff
@@ -845,32 +846,45 @@ private function getRowColumns(array $row): array
...
-                                foreach ($contentColumns as $position => $content) {
-                                    $row[$i + $position] = $content;
-                                }
+                // Process TableCell colspan splitting once per row
+                foreach ($row as $i => $cell) {
+                    if ($cell instanceof TableCell && $cell->getColspan() > 1) {
+                        $textContent = Helper::removeDecoration($formatter, $cell);
+                        $textLength = Helper::width($textContent);
+                        if ($textLength > 0) {
+                            $contentColumns = mb_str_split($textContent, (int) ceil($textLength / $cell->getColspan()));
```
Comment (GromNaN) [inline src/Symfony/Component/Console/Helper/Table.php:867]: Would it make the code too complex to skip the content split when `$textLength <= array_sum(array_slice($maxColumnWidths, $i, $cell->getColspan()))`, and only store `null` instead.

Also, instead of setting arbitrary text inside the rows, that will be remeasured later, you can store the `(int) ceil($textLength / $cell->getColspan()` somewhere.

File: src/Symfony/Component/Console/Helper/Helper.php
Comment (GromNaN) [inline src/Symfony/Component/Console/Helper/Helper.php]: This can be merged into a single PCRE call that returns `null` when the string isn't a valid UTF-8:

```php
    if (null !== $clean = preg_replace('/[\p{Cc}\x7F]++/u', '', $string, -1, $count)) {
        return (new UnicodeString($clean))->width(false) + $count;
    }
```

File: src/Symfony/Component/Console/Helper/Helper.php [hunk 4]
```diff
@@ -152,10 +161,18 @@ public static function formatMemory(int $memory): string
 
     public static function removeDecoration(OutputFormatterInterface $formatter, ?string $string): string
     {
+        $string ??= '';
+
+        // Fast path: if string contains no formatting markers, return as-is
+        // Check for: < (tags), \033 (ANSI escape), ]8;; (hyperlink in test fixtures)
```
Comment (GromNaN) [inline src/Symfony/Component/Console/Helper/Helper.php]: Why does the comment mention "in test fixtures"?

**Review by GromNaN — COMMENTED** [review]
That looks good to me, but I have a question about a comment in the code. I also have two additional optimization suggestions that I’ve benchmarked.

**Comment by Amoifr** [comment]
Thanks @GromNaN for the detailed review and the optimization suggestions! 🙏

I've applied the PCRE optimization and fixed the comment. Here are the benchmark results:

### Helper::width() micro-benchmark (10,000 iterations)
| Input type | Before (µs) | After (µs) |
|------------|-------------|------------|
| ASCII string | 0.098 | 0.094 |
| Unicode string | 20.367 | 20.149 |
| Control chars | 2.829 | 2.920 |

### Table rendering benchmark
| Scenario | Before (ms/iter) | After (ms/iter) |
|----------|------------------|-----------------|
| Simple table (4 rows) | 0.0687 | 0.0628 |
| Large table (100 rows) | 1.159 | 1.085 |
| Colspan table | 0.0752 | 0.0695 |

The PCRE optimization is elegant but the gain is within statistical noise - the main benefit is cleaner code by avoiding the redundant UTF-8 validity check.

Regarding the colspan split optimization: I tried implementing the "skip when content fits" approach, but it broke some edge cases in the test suite. The interaction between `maxColumnWidths` initialization and the iterative width calculation made it tricky to get right without a more significant refactor. Happy to revisit if you have specific guidance on how to approach it!

File: src/Symfony/Component/Console/Helper/Helper.php (hunk 4 above)
Comment (Amoifr) [reply src/Symfony/Component/Console/Helper/Helper.php]: done

File: src/Symfony/Component/Console/Helper/Helper.php
Comment (Amoifr) [reply src/Symfony/Component/Console/Helper/Helper.php]: done

**Comment by nicolas-grekas** [comment]
Thank you @Amoifr.

File: src/Symfony/Component/Console/Helper/Table.php (hunk 3 above)
Comment (GromNaN) [reply src/Symfony/Component/Console/Helper/Table.php:867]: We might need to add 3*(colspan-1) to account for the character between the columns.
But that’s probably not significant in real-world use. So I’m closing this thread.

**Comment by staabm** [comment]
thank you!
