### PR TITLE
[FrameworkBundle][ObjectMapper] Add automatic class-map array based on map attributes

### LINKED ISSUE #62357: [ObjectMapper] Subobjects are not mapped
### Symfony version(s) affected

7.2.3

### Description

We have a DTO that needs to be mapped to a Resource Object, using target-Attributes inside the DTO.
The DTO has a nested object, which isn't handled by the object mapper.

### How to reproduce

```
#[Map(target: BankDataResource::class)]
class BankDataDto
{
    #[Map(target: 'iban')
    public string $iban;
        
    public BankDto $bank;
}

class BankDto
{
    #[Map(target: 'bic')
    public string $bic;
    #[Map(target: 'bankCode')
    public string $code;
    #[Map(target: 'bankName')
    public string $name;
}

class BankDataResource
{
    public string $iban;
    public string $bic;
    public string $bankCode;
    public string $bankName;
}

// $dto = new BankDataDto();
// ...
$bankdata = $objectMapper->map($dto, BankDataResource::class);
```

The values from BankDto are not mapped, I tried a lot of different attribute configurations. And the docs don't say anything about this. But I think this should be possible.

Right now I do this ugly version to get my result:

```
// $dto = new BankDataDto();
// ...
$bankdata = $objectMapper->map($dto, BankDataResource::class);
$bankdata = $objectMapper->map($dto->bank, $bankdata);
```

But this feels counterintuitive...

### Possible Solution

It should be possible to give the mapper a hint to handle sub-objects.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Orkin**
| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #62357
| License       | MIT

Create automatic class map array to allow Hexagonal Architecture and map object from the target class in Infrastructure layer

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/object_mapper.php [hunk 1]
```diff
@@ -19,6 +19,9 @@
 return static function (ContainerConfigurator $container) {
     $container->services()
         ->set('object_mapper.metadata_factory', ReflectionObjectMapperMetadataFactory::class)
+            ->args([
+                param('object_mapper.map_classes'),
```
Comment (soyuka) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/object_mapper.php]: should we `->ignoreOnInvalid()`? really not sure what the rule is inside the framework bundle for new arguments.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 2]
```diff
@@ -618,6 +619,12 @@ public function load(array $configs, ContainerBuilder $container): void
                 ->addTag('object_mapper.transform_callable');
             $container->registerForAutoconfiguration(ConditionCallableInterface::class)
                 ->addTag('object_mapper.condition_callable');
+            $container->registerAttributeForAutoconfiguration(Map::class, static function (ChildDefinition $definition, Map $attribute): void {
+                $definition->addResourceTag('object_mapper.map', [
+                    'source' => $attribute->source ?? null,
+                    'target' => $attribute->target ?? null,
+                ]);
```
Comment (soyuka) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:626]: I think that we could also get the `ReflectionClass` and get the source or target from the class the attribute is defined on.

File: src/Symfony/Component/ObjectMapper/DependencyInjection/MapResourcesPass.php [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+class MapResourcesPass implements CompilerPassInterface
+{
+    public function process(ContainerBuilder $container): void
+    {
+        $classes = [];
+        foreach ($container->getDefinitions() as $definition) {
+            if ($definition->hasTag('object_mapper.map')) {
+                $attributes = $definition->getTag('object_mapper.map')[0];
+
+                if (isset($attributes['source'], $attributes['target'])) {
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/DependencyInjection/MapResourcesPass.php]: this condition is not optimal as often we release either a source either a target

File: src/Symfony/Component/ObjectMapper/Metadata/ReflectionObjectMapperMetadataFactory.php [hunk 4]
```diff
@@ -18,12 +18,17 @@
  * @internal
  *
  * @author Antoine Bluchet <soyuka@gmail.com>
+ * @author Florent Blaison <florent.blaison@gmail.com>
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/Metadata/ReflectionObjectMapperMetadataFactory.php]: do we add these usually on the codebase?

File: src/Symfony/Component/ObjectMapper/Metadata/ReflectionObjectMapperMetadataFactory.php [hunk 5]
```diff
@@ -18,12 +18,17 @@
...
  */
 final class ReflectionObjectMapperMetadataFactory implements ObjectMapperMetadataFactoryInterface
 {
     private array $reflectionClassCache = [];
     private array $attributesCache = [];
 
+    public function __construct(private readonly array $classMap)
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/Metadata/ReflectionObjectMapperMetadataFactory.php]:
```suggestion
    public function __construct(private readonly array $classMap = [])
```

should have a default value for bc layer

File: src/Symfony/Component/ObjectMapper/Tests/Fixtures/ClassMap/QuoteRequestView.php [hunk 6]
```diff
@@ -0,0 +1,16 @@
...
+namespace Symfony\Component\ObjectMapper\Tests\Fixtures\ClassMap;
+
+use Symfony\Component\ObjectMapper\Attribute\Map;
+
+#[Map(source: Quote::class)]
+final class QuoteRequestView
+{
+    public string $id;
+
+    #[Map(target: CostRequestView::class)]
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/Tests/Fixtures/ClassMap/QuoteRequestView.php]:
```suggestion
```

Comment (soyuka) [reply src/Symfony/Component/ObjectMapper/Tests/Fixtures/ClassMap/QuoteRequestView.php]: we should remove this, a target can not be a `class-string` when mapped to a property

File: src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php [hunk 7]
```diff
@@ -597,7 +601,7 @@ public function testSkipLazyGhostWithClassTransform()
         $service = new LoadedValueService();
         $service->load();
 
-        $metadataFactory = new ReflectionObjectMapperMetadataFactory();
+        $metadataFactory = new ReflectionObjectMapperMetadataFactory([]);
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php]: revert previous tests modification

File: src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php [hunk 8]
```diff
@@ -651,4 +655,23 @@ public function testBugReportLazyLoadingPromotedReadonlyProperty()
         $this->assertSame('foo', $out->var1);
         $this->assertSame('bar', $out->b->var2);
     }
+
+    public function testClassMap()
+    {
+        $classMap = [
+            Cost::class => CostRequestView::class,
+            Quote::class => QuoteRequestView::class,
+        ];
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php:666]: I see why it's working, I think we need a test in the framework bundle also as currently it won't work there (though the component's logic is okay).

**Review by soyuka — CHANGES_REQUESTED** [review]

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 9]
```diff
@@ -618,6 +619,12 @@ public function load(array $configs, ContainerBuilder $container): void
                 ->addTag('object_mapper.transform_callable');
             $container->registerForAutoconfiguration(ConditionCallableInterface::class)
                 ->addTag('object_mapper.condition_callable');
+            $container->registerAttributeForAutoconfiguration(Map::class, static function (ChildDefinition $definition, Map $attribute, \ReflectionClass|\ReflectionMethod $reflector): void {
```
Comment (soyuka) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]:
```suggestion
            $container->registerAttributeForAutoconfiguration(Map::class, static function (ChildDefinition $definition, Map $attribute, \ReflectionClass|\ReflectionMethod $reflector): void {
                if (!$reflector instanceof \ReflectionClass) {
                    return;
                }
```

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 10]
```diff
@@ -618,6 +619,12 @@ public function load(array $configs, ContainerBuilder $container): void
...
+                $definition->addResourceTag('object_mapper.map', [
+                    'source' => $attribute->source ?? null,
+                    'target' => $reflector->name,
+                ]);
```
Comment (soyuka) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:626]:
```suggestion
                $definition->addResourceTag('object_mapper.map', [
                    'source' => $attribute->source ?? $reflector->name,
                    'target' => $attribute->target ?? $reflector->name,
                ]);
```

File: src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php [hunk 11]
```diff
@@ -0,0 +1,40 @@
...
+ * Registers map classes from {@see Map} attribute.
+ *
+ * @author Florent Blaison <florent.blaison@gmail.com>
+ */
+class MapResourcesPass implements CompilerPassInterface
+{
+    public function process(ContainerBuilder $container): void
+    {
+        $classes = [];
+        foreach ($container->getDefinitions() as $definition) {
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php]:
```suggestion
        foreach ($container->findTaggedServiceIds('has_tag') as $serviceId => $attributes) {

```

File: src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php [hunk 12]
```diff
@@ -0,0 +1,40 @@
...
+
+/**
+ * Registers map classes from {@see Map} attribute.
+ *
+ * @author Florent Blaison <florent.blaison@gmail.com>
+ */
+class MapResourcesPass implements CompilerPassInterface
+{
+    public function process(ContainerBuilder $container): void
+    {
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php:23]: check if the ObjectMapperInterface exists if not early return to prevent this from running when the ObjectMapper is not installed

File: src/Symfony/Component/ObjectMapper/DependencyInjection/MapResourcesPass.php [hunk 13]
```diff
@@ -0,0 +1,40 @@
...
+use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
+use Symfony\Component\DependencyInjection\ContainerBuilder;
+use Symfony\Component\ObjectMapper\Attribute\Map;
+
+/**
+ * Registers map classes from {@see Map} attribute.
+ *
+ * @author Florent Blaison <florent.blaison@gmail.com>
+ */
+class MapResourcesPass implements CompilerPassInterface
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/DependencyInjection/MapResourcesPass.php]: final

File: src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php [hunk 14]
```diff
@@ -0,0 +1,40 @@
...
+        $classes = [];
+        foreach ($container->getDefinitions() as $definition) {
+            if ($definition->hasTag('object_mapper.map')) {
+                $attributes = $definition->getTag('object_mapper.map')[0];
+
+                if (isset($attributes['source'])) {
+                    $classes[$attributes['source']] = $attributes['target'];
+                }
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php:35]: you also need to add `->addTag('container.excluded', ['source' => 'because it's a mapping configuration attribute'])`

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php [hunk 15]
```diff
@@ -35,7 +35,7 @@ final class ObjectMapper implements ObjectMapperInterface, ObjectMapperAwareInte
     private ?\WeakMap $objectMap = null;
 
     public function __construct(
-        private readonly ObjectMapperMetadataFactoryInterface $metadataFactory = new ReflectionObjectMapperMetadataFactory(),
+        private readonly ObjectMapperMetadataFactoryInterface $metadataFactory = new ReflectionObjectMapperMetadataFactory([]),
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/ObjectMapper.php]:
```suggestion
        private readonly ObjectMapperMetadataFactoryInterface $metadataFactory = new ReflectionObjectMapperMetadataFactory(),
```

**Review by soyuka — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php (hunk 14 above)
Comment (Orkin) [reply src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php:35]: The method `addResourceTag` method in `FrameworkExtension` did already that, do I have to add it here too ?

File: src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php (hunk 11 above)
Comment (Orkin) [reply src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php]: I did the same thing than api-platform for api resource : https://github.com/api-platform/core/blob/325a04c8303c25f04fd0cc107664965bc46b0c16/src/Symfony/Bundle/DependencyInjection/Compiler/AttributeResourcePass.php.

And I think it's not `'has_tag'` but `'object_mapper.map'` instead ?

Comment (soyuka) [reply src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php]: yes I copy pasted that from somewhere else, could you need to check what the method does and maybe it's not appropriate for what we're trying? Maybe we can just keep what you did it's probably fine :)

File: src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php (hunk 14 above)
Comment (soyuka) [reply src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php:35]: Oh indeed my bad forgot that these were resources.

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/object_mapper.php [hunk 16]
```diff
@@ -19,6 +19,9 @@
 return static function (ContainerConfigurator $container) {
     $container->services()
         ->set('object_mapper.metadata_factory', ReflectionObjectMapperMetadataFactory::class)
+            ->args([
+                '%object_mapper.map_classes%',
+            ])
```
Comment (soyuka) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/object_mapper.php:30]: After a discussion at the hackday, can we create a new `ObjectMapperMetadataFactory` (`ReverseClassObjectMapperMetadataFactory`). This one will decorate the `object_mapper.metadata_factory` service.

File: src/Symfony/Component/ObjectMapper/DependencyInjection/MapResourcesPass.php [hunk 17]
```diff
@@ -0,0 +1,45 @@
...
+            if ($definition->hasTag('object_mapper.map')) {
+                $attributes = $definition->getTag('object_mapper.map')[0];
+
+                if (isset($attributes['source'])) {
+                    $classes[$attributes['source']] = $attributes['target'];
+                }
+            }
+        }
+
+        $container->setParameter('object_mapper.map_classes', $classes);
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/DependencyInjection/MapResourcesPass.php]: instead of using a parameter we can just add the argument to the service in this pass. Indeed a parameter should be shared to other bundles but I don't think we want to share this today (unless another bundle has a use case but I doubt it).

File: src/Symfony/Component/ObjectMapper/Metadata/ReflectionObjectMapperMetadataFactory.php [hunk 18]
```diff
@@ -41,6 +45,10 @@ public function create(object $object, ?string $property = null, array $context
                 $mappings[] = new Mapping($map->target, $map->source, $map->if, $map->transform);
             }
 
+            if (null === $property && isset($this->classMap[$object::class])) {
+                $mappings[] = new Mapping($this->classMap[$object::class], $object::class);
+            }
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/Metadata/ReflectionObjectMapperMetadataFactory.php]: let's do this in a decorator instead

**Review by soyuka — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/ObjectMapper/CHANGELOG.md [hunk 19]
```diff
@@ -1,6 +1,10 @@
 CHANGELOG
 =========
 
+8.1
+---
+ * Automatic class-map based on Map attribute
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/CHANGELOG.md]:
```suggestion
 * reverse class-map based on Map attribute
```

**Review by soyuka — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php [hunk 20]
```diff
@@ -0,0 +1,45 @@
...
+            return $this->attributesCache[$key];
+        }
+
+        $mappings = $this->objectMapperMetadataFactory->create($object, $property, $context);
+
+        if (null === $property && isset($this->classMap[$object::class])) {
+            $mappings[] = new Mapping($this->classMap[$object::class], $object::class);
+        }
+
+        return $this->attributesCache[$key] = $mappings;
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php]:
```suggestion
		if (null !== $property) {
		    return $this->objectMapperMetadataFactory->create($object, $property, $context);
		}
		
		$class = $object::class;
		if (isset($this->attributesCache[$class])) {
		    return $this->attributesCache[$class];
		}
		
		$mappings = $this->objectMapperMetadataFactory->create($object, null, $context);
		
		if (isset($this->classMap[$class])) {
		    $mappings[] = new Mapping($this->classMap[$class], $class);
		}
		
		return $this->attributesCache[$class] = $mappings;
```

File: src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php [hunk 21]
```diff
@@ -0,0 +1,47 @@
...
+/**
+ * Registers map classes from {@see Map} attribute.
+ *
+ * @author Florent Blaison <florent.blaison@gmail.com>
+ */
+final class ReverseMappingPass implements CompilerPassInterface
+{
+    public function process(ContainerBuilder $container): void
+    {
+        if (!interface_exists(ObjectMapperInterface::class) || !$container->hasDefinition('object_mapper.metadata_factory.reverse_class')) {
```
Comment (stof) [inline src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php]: the interface will always exist as it is in the same package.

File: src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php [hunk 22]
```diff
@@ -0,0 +1,47 @@
...
+            return;
+        }
+
+        $reverseClassObjectMapperMetadataFactory = $container->getDefinition('object_mapper.metadata_factory.reverse_class');
+
+        $classes = [];
+        foreach ($container->getDefinitions() as $definition) {
+            if ($definition->hasTag('object_mapper.map')) {
```
Comment (stof) [inline src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php]: Use `$container->findTaggedResourceIds()` instead of reimplementing it manually. The 8.1 branch does not need to care for support for `symfony/dependency-injection < 7.2` IMO.

File: src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php [hunk 23]
```diff
@@ -0,0 +1,47 @@
...
+                $attributes = $definition->getTag('object_mapper.map')[0];
```
Comment (stof) [inline src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php]: shouldn't we process _all_ the tags instead of just the first one, in case we have multiple tags ?

File: src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php [hunk 24]
```diff
@@ -0,0 +1,49 @@
...
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\ObjectMapper\Metadata;
+
+/**
+ * @internal
```
Comment (stof) [inline src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php]: The fact that FrameworkBundle registers this class as service tells me that this class is not actually internal, as configuring the component involves instantiating.

File: src/Symfony/Component/ObjectMapper/Tests/Fixtures/ClassMap/Cost.php [hunk 25]
```diff
@@ -0,0 +1,15 @@
+<?php
+
+declare(strict_types=1);
```
Comment (stof) [inline src/Symfony/Component/ObjectMapper/Tests/Fixtures/ClassMap/Cost.php]: we don't use strict types in Symfony.

File: src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php [hunk 26]
```diff
@@ -651,4 +656,39 @@ public function testBugReportLazyLoadingPromotedReadonlyProperty()
...
+
+        $quote = new Quote(id: 'foo', cost: new Cost(amount: 10, tax: 20));
+
+        $mapper = new ObjectMapper(metadataFactory: new ReverseClassObjectMapperMetadataFactory(new ReflectionObjectMapperMetadataFactory(), $classMap));
```
Comment (stof) [inline src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php]: this should rather use the public API (parameter names are not part of it) as this gives a chance to notice unintended BC breaks in case we have to edit tests to keep them working.

File: src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php (hunk 24 above)
Comment (Orkin) [reply src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php]: I used the same than `ReflectionObjectMapperMetadataFactory` but ok I'll fix it 😉

File: src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php (hunk 21 above)
Comment (Orkin) [reply src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php]: Indeed 😅

File: src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php (hunk 24 above)
Comment (soyuka) [reply src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php]: Indeed this is probably a mistake btw `ReflectionObjectMapperMetadataFactory` shouldn't be internal.

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/object_mapper.php [hunk 27]
```diff
@@ -21,6 +22,10 @@
         ->set('object_mapper.metadata_factory', ReflectionObjectMapperMetadataFactory::class)
         ->alias(ObjectMapperMetadataFactoryInterface::class, 'object_mapper.metadata_factory')
 
+        ->set('object_mapper.metadata_factory.reverse_class', ReverseClassObjectMapperMetadataFactory::class)
+            ->decorate('object_mapper.metadata_factory')
+            ->args([service('.inner'), []])
```
Comment (mtarld) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/object_mapper.php]:
```suggestion
            ->args([
                service('.inner'),
                abstract_arg('class map'),
            ])
```

File: src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php [hunk 28]
```diff
@@ -0,0 +1,44 @@
...
+        if (!$container->hasDefinition('object_mapper.metadata_factory.reverse_class')) {
+            return;
+        }
+
+        $reverseClassObjectMapperMetadataFactory = $container->getDefinition('object_mapper.metadata_factory.reverse_class');
+
+        $classes = [];
+        foreach ($container->findTaggedResourceIds('object_mapper.map') as $tags) {
+            foreach ($tags as $tag) {
+                if (isset($tag['source'])) {
```
Comment (mtarld) [inline src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php]:
```suggestion
                if (isset($tag['source']) && isset($tag['target'])) {
```

File: src/Symfony/Component/ObjectMapper/Metadata/Mapping.php [hunk 29]
```diff
@@ -22,4 +22,8 @@
  */
 final class Mapping extends Map
 {
+    public function __construct(?string $target = null, ?string $source = null, mixed $if = null, mixed $transform = null, public ?string $propertyName = null)
```
Comment (mtarld) [inline src/Symfony/Component/ObjectMapper/Metadata/Mapping.php]: Can you make it multiline? It'll later diffs

File: src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php [hunk 30]
```diff
@@ -0,0 +1,65 @@
...
+namespace Symfony\Component\ObjectMapper\Metadata;
+
+use Symfony\Component\ObjectMapper\Attribute\Map;
+
+/**
+ * @author Florent Blaison <florent.blaison@gmail.com>
+ */
+final class ReverseClassObjectMapperMetadataFactory implements ObjectMapperMetadataFactoryInterface
+{
+    private array $attributesCache = [];
```
Comment (mtarld) [inline src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php:26]: Can you add some phpdoc here?

File: src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php [hunk 31]
```diff
@@ -0,0 +1,65 @@
...
+
+    public function __construct(
+        private readonly ObjectMapperMetadataFactoryInterface $objectMapperMetadataFactory,
+        private readonly array $classMap,
```
Comment (mtarld) [inline src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php:33]: Same for that property

File: src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php [hunk 32]
```diff
@@ -0,0 +1,65 @@
...
+    ) {
+    }
+
+    public function create(object $object, ?string $property = null, array $context = []): array
+    {
+        $class = $object::class;
+        $key = $class.($property ?? '');
```
Comment (mtarld) [inline src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php]: It might be great to add a separator like `.` to avoid unexpected collisions

File: src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php [hunk 33]
```diff
@@ -0,0 +1,65 @@
...
+            return $this->attributesCache[$key];
+        }
+
+        $mappings = $this->objectMapperMetadataFactory->create($object, $property, $context);
+
+        if (!$targetClass = $this->classMap[$class] ?? null) {
+            return $mappings;
+        }
+
+        if (null === $property) {
```
Comment (mtarld) [inline src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php]:
```suggestion
        if (!$property) {
```

File: src/Symfony/Component/ObjectMapper/CHANGELOG.md [hunk 34]
```diff
@@ -1,6 +1,10 @@
 CHANGELOG
 =========
 
+8.1
+---
+ * Reverse class-map based on Map attribute
```
Comment (mtarld) [inline src/Symfony/Component/ObjectMapper/CHANGELOG.md]:
```suggestion
 * Add reverse class-map based on Map attribute
```

**Review by mtarld — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/ObjectMapper/Metadata/Mapping.php (hunk 29 above)
Comment (soyuka) [reply src/Symfony/Component/ObjectMapper/Metadata/Mapping.php]: we can remove this change :)

**Review by soyuka — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php (hunk 32 above)
Comment (stof) [reply src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php]: Class `Foo` with a `barbaz` property and class `Foobar` with a `baz` property.

File: src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php [hunk 35]
```diff
@@ -0,0 +1,69 @@
...
+
+use Symfony\Component\ObjectMapper\Attribute\Map;
+
+/**
+ * @author Florent Blaison <florent.blaison@gmail.com>
+ */
+final class ReverseClassObjectMapperMetadataFactory implements ObjectMapperMetadataFactoryInterface
+{
+    /**
+     * @var array<string, Mapping[]>
```
Comment (mtarld) [inline src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php]:
```suggestion
     * @var array<string, list<Mapping>>
```
To fit with `ObjectMapperMetadataFactoryInterface` documentation

File: src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php [hunk 36]
```diff
@@ -0,0 +1,69 @@
...
+     */
+    private array $attributesCache = [];
+
+    public function __construct(
+        private readonly ObjectMapperMetadataFactoryInterface $objectMapperMetadataFactory,
+        /** @param array<int, class-string> $classMap */
```
Comment (mtarld) [inline src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php]:
```suggestion
        /** @param array<class-string, class-string> $classMap */
```
Makes more sense to me.
Also, can you put it on top of the constructor?

**Review by mtarld — COMMENTED** [review]
Almost good to me 😉

File: src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php (hunk 32 above)
Comment (soyuka) [reply src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php]: https://github.com/symfony/symfony/blob/8.1/src/Symfony/Component/ObjectMapper/Metadata/ReflectionObjectMapperMetadataFactory.php#L30 we need also to fix it there then at some point

**Review by soyuka — APPROVED** [review]

**Review by mtarld — APPROVED** [review]

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 37]
```diff
@@ -618,6 +619,16 @@ public function load(array $configs, ContainerBuilder $container): void
                 ->addTag('object_mapper.transform_callable');
             $container->registerForAutoconfiguration(ConditionCallableInterface::class)
                 ->addTag('object_mapper.condition_callable');
+            $container->registerAttributeForAutoconfiguration(Map::class, static function (ChildDefinition $definition, Map $attribute, \ReflectionClass|\ReflectionMethod $reflector): void {
+                if (!$reflector instanceof \ReflectionClass) {
+                    return;
+                }
+
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]:
```suggestion
            $container->registerAttributeForAutoconfiguration(Map::class, static function (ChildDefinition $definition, Map $attribute, \ReflectionClass $reflector) {
```

File: src/Symfony/Component/ObjectMapper/CHANGELOG.md [hunk 38]
```diff
@@ -1,6 +1,10 @@
 CHANGELOG
 =========
 
+8.1
+---
+ * Add reverse class-map based on Map attribute
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/CHANGELOG.md:7]:
```suggestion

 * Add reverse class-map based on Map attribute
```

File: src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php [hunk 39]
```diff
@@ -0,0 +1,71 @@
...
+ */
+final class ReverseClassObjectMapperMetadataFactory implements ObjectMapperMetadataFactoryInterface
+{
+    /**
+     * @var array<string, list<Mapping>>
+     */
+    private array $attributesCache = [];
+
+    /**
+     * @param array<class-string, class-string $classMap
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php]:
```suggestion
     * @param array<class-string, class-string> $classMap
```

File: src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php [hunk 40]
```diff
@@ -0,0 +1,44 @@
...
+
+namespace Symfony\Component\ObjectMapper\DependencyInjection;
+
+use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
+use Symfony\Component\DependencyInjection\ContainerBuilder;
+use Symfony\Component\ObjectMapper\Attribute\Map;
+
+/**
+ * Registers map classes from {@see Map} attribute.
+ *
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/DependencyInjection/ReverseMappingPass.php]: The code doesn't care about the php attribute so that this title isn't accurate enough:

```suggestion
```

File: src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php [hunk 41]
```diff
@@ -0,0 +1,71 @@
...
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\ObjectMapper\Metadata;
+
+use Symfony\Component\ObjectMapper\Attribute\Map;
+
+/**
+ * @author Florent Blaison <florent.blaison@gmail.com>
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php:19]:
```suggestion
 * Maps classes based on attributes found on the target's properties.
 *
 * @author Florent Blaison <florent.blaison@gmail.com>
```

**Comment by nicolas-grekas** [comment]
Thank you @Orkin.

**Comment by pierrelemee** [comment]
Hi ! I'm late in the game but this actually fixes [this issue](https://github.com/symfony/symfony/issues/62499) that I encountered in my project.

Could this be injected as a bug fix also in previous versions ?
