### PR TITLE
[Security][SecurityBundle] Show user account status errors

### LINKED ISSUE #50028: Locked account produces "Invalid credentials" message
### Symfony version(s) affected

5.4.21+

### Description

When using the 'hide_user_not_found' feature (enabled by default), a user who tries to login with the proper credentials and has a locked or disabled account, will receive the "Invalid credentials" message. This is unexpected as the user is found, but the account is locked or disabled. The exception thrown for these cases are either the LockedException, DisabledException, or AccountExpiredException. One would expect this message only for a UsernameNotFoundException, not including cases where the user is found, but is inactive or locked out in some way. This used to provide useful feedback for our clients so they would not waste time trying to reset their password. I guess some could argue it is better to obfuscate the error in all cases, but this seems a bit paranoid, and again the feature seems improperly named. I would propose to either rename this or better yet, separate this into two features: e.g. hideUserNotFoundExceptions and hideAllAuthExceptions.

### How to reproduce

Setup the application as normal. Implement a UserCheckerInterface on the main secured firewall. Throw an AccountStatusException in the checkPostAuth function. The exception can be the LockedException, DisabledException, or AccountExpiredException. Notice the message to the user is "Invalid (or Bad) credentials".

### Possible Solution

Looking at the code in AuthenticatorManager#[handleAuthenticationFailure:271](https://github.com/symfony/symfony/blob/7f9c726f539739637a7ffcbc6bf1062e2a432160/src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php#L271) it does seem like a bug or at least a feature with a misleading name: hideUserNotFoundExceptions.

Replacing that conditional block with this made it work as expected and as previously:
```
if ($this->hideUserNotFoundExceptions && ($authenticationException instanceof UsernameNotFoundException 
		|| $authenticationException instanceof UserNotFoundException)) {
	$authenticationException = new BadCredentialsException('Bad credentials.', 0, $authenticationException);
}
```

I believe this block of code is also in a few other classes in the codebase, so this would also would be nice to address.

This is similar to this previously discussed here #42793, but has already been closed.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by core23**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | no
| New feature? | yes 
| Deprecations? | no
| Issues        | Fix #50028
| License       | MIT

According to the `hideUserNotFoundExceptions` flag, only `UserNotFoundException` should be hidden, but the implementation was also silencing account specific errors.

To fix the issue in a BC way, a new `hide_account_status_exceptions` config key was introduced to show account exceptions. 

This key should be changed to **false** with an upcoming version (7.3 or 7.4?), so that the existing `hide_user_not_found` config key works as intended with the upcoming symfony 8 release.

### CODE REVIEW

**Comment by chalasr** [comment]
From https://github.com/symfony/symfony/pull/56830#pullrequestreview-2309647166

> This should target 7.2 as this is a new feature.
@chalasr can you please have another look?
I don't like adding new options so if there's a way without, suggestions welcome :)

@nicolas-grekas unless we decide to revert a security fix we cannot avoid the option I think

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 1]
```diff
@@ -155,6 +155,7 @@ public function load(array $configs, ContainerBuilder $container): void
         }
 
         $container->setParameter('security.authentication.hide_user_not_found', $config['hide_user_not_found']);
+        $container->setParameter('security.authentication.show_account_status_exceptions', $config['show_account_status_exceptions']);
```
Comment (chalasr) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]:
```suggestion
        $container->setParameter('.security.authentication.show_account_status_exceptions', $config['show_account_status_exceptions']);
```

So that the parameter is compile-time only.

File: src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php [hunk 2]
```diff
@@ -257,4 +258,21 @@ private function handleAuthenticationFailure(AuthenticationException $authentica
...
+    {
+        if (!$this->hideUserNotFoundExceptions) {
+            return false;
+        }
+
+        if ($exception instanceof UserNotFoundException) {
+            return true;
+        }
+
+        if ($this->showAccountStatusExceptions) {
```
Comment (chalasr) [inline src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php]: I would expect `CustomAuthenticationMessageExceptions` to show up even if `showAccountStatusExceptions` is false, as it's the case today with `hideUserNotFoundExceptions`

File: src/Symfony/Bundle/SecurityBundle/Resources/config/security_authenticator.php [hunk 3]
```diff
@@ -44,6 +44,7 @@
                 param('security.authentication.manager.erase_credentials'),
                 param('security.authentication.hide_user_not_found'),
                 abstract_arg('required badges'),
+                param('security.authentication.show_account_status_exceptions'),
```
Comment (chalasr) [inline src/Symfony/Bundle/SecurityBundle/Resources/config/security_authenticator.php]:
```suggestion
                param('.security.authentication.show_account_status_exceptions'),
```

File: src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php [hunk 4]
```diff
@@ -58,6 +58,7 @@ public function __construct(
         private bool $eraseCredentials = true,
         private bool $hideUserNotFoundExceptions = true,
         private array $requiredBadges = [],
+        private bool $showAccountStatusExceptions = false,
```
Comment (chalasr) [inline src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php]: should it rather be `hideAccountStatusExceptions` to be consistent with `hideUserNotFoundExceptions`?

**Review by chalasr — CHANGES_REQUESTED** [review]
We need an entry in both SecurityBundle and Security\Http's CHANGELOG files

**Comment by wouterj** [comment]
>  I don't like adding new options so if there's a way without, suggestions welcome :)

Maybe an unpopular opinion: I'm not sure if I would implement this feature in Symfony at all.

This is part of code that was released with the [user enumeration CVE](https://symfony.com/blog/cve-2021-21424-prevent-user-enumeration-in-authentication-mechanisms). With the new option set to true, you'll reintroduce the possibility of user enumeration based on error messages as you now get "Invalid credentials" (user does not exists) or "This account is locked" (account status error).

The `hide_user_not_found` option name might be a bit of a vague name, but it determines whether you want some default user enumeration prevention or not. If a business decides it wants partial user enumeration (by hiding only user not found exceptions), you can already achieve this by setting `hide_user_not_found: false` and implementing your own authentication failure handler that hides only `UserNotFoundException`.

I'm not convinced we need to provide an extra option to achieve this (especially because we consider the new feature less secure).

**Comment by ChristianGripp** [comment]
> This is part of code that was released with the [user enumeration CVE](https://symfony.com/blog/cve-2021-21424-prevent-user-enumeration-in-authentication-mechanisms). With the new option set to true, you'll reintroduce the possibility of user enumeration based on error messages as you now get "Invalid credentials" (user does not exists) or "This account is locked" (account status error).

I agree, in theory you could use this to enumerate all users that have an *account status* error, but *user does not exist* errors are still silenced with solution. But you may also enumerate users by the time it takes to generate the response at all, if you want to use all possible ways ;)

The current solution looks broken to me. You either expose ALL user information or no user feedback at all. There is no way to inform the user, that it is currently not possible to login with the user. The current solution resulted in several service desk tickets that I need to check every time.

What about creating a new enum config key with three different states like: `expose_security_errors: none|account|all`?

**Comment by chalasr** [comment]
Renaming/changing the existing option looks sensible to me as account status errors means that a user is actually found.

**Comment by ChristianGripp** [comment]
Changed the config key to `hide_account_status_exceptions` and applied the proposed changes.

File: src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php (hunk 2 above)
Comment (ChristianGripp) [reply src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php]: Not sure how to deal with the `CustomAuthenticationMessageExceptions` as this is no account specific exception (extends `AccountStatusException`), but a general authentication exception (extends `AuthenticationException`). 

The new key is named `hide_account_status_exceptions`, so this might be confusing.

**Comment by ChristianGripp** [comment]
Anything left to do @chalasr ?

**Comment by chalasr** [comment]
Sorry for the back and forths but I think there is confusion about my last comment:

> Renaming/changing the existing option looks sensible to me as account status errors means that a user is actually found.

I agree with Wouter this is not worth a dedicated option, but I do think it's worth renaming the existing `hide_user_not_found_exceptions` option for clarity to make it take an enum as you proposed in https://github.com/symfony/symfony/pull/58300#issuecomment-2358711714. It should still handle true/false and behave the same as today for BC until 8.0.

**Comment by ChristianGripp** [comment]
So you're fine with deprecating the existing `hide_user_not_found_exceptions` option in favor of something like `expose_security_errors` with the states `none`, `account `, `all`? 

And if you are using the new `option`, it should override the `hide_user_not_found_exceptions` setting?

**Comment by chalasr** [comment]
Yes. The new option should win over the to-be-deprecated one when it's explicitly set (to not change the behavior of apps explicitly setting the old option to false). The new option should default to `all` to keep the same default behavior as today.

@wouterj are you ok with the proposed plan?

**Comment by wouterj** [comment]
Ok, let's go with an enum option with these conditions (maybe worth calling the middle one `account_status` to be super clear on what errors are exposed).

I guess the easiest BC way would be removing the default value from the current option adding adding the new option with an `'all'` default value. Then, in the extension use the old option if it's defined (which means the user has configured it explicitly) + a deprecation notice. Otherwise - if the old option was not configured - use the new option.
When the old option is used, the extension can then transform true to `'all'` and false to `'none'`.

**Comment by chalasr** [comment]
Sounds good 👍

**Comment by ChristianGripp** [comment]
Done with the renaming, please recheck :)

Not sure about the `Unit Tests (8.2, low-deps)` error, because the config uses the constants. Should I remove the constant usage and replace it with strings or should I bump the dependency?

**Comment by ChristianGripp** [comment]
Friendly ping @chalasr

**Comment by ChristianGripp** [comment]
@wouterj Maybe you can answer the open question regarding the constant usage?

**Comment by stof** [comment]
@core23 you need to bump the min version of the component supported by security-bundle in the security-bundle composer.json to be `7.3`, so that the new constants are available.

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 5]
```diff
@@ -156,6 +157,12 @@ public function load(array $configs, ContainerBuilder $container): void
 
         $container->setParameter('security.authentication.hide_user_not_found', $config['hide_user_not_found']);
```
Comment (stof) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]: shouldn't this parameter be set to a boolean value derived from `$config['expose_security_errors']` instead of setting it to `null` to avoid BC breaks for code using this parameter once the project migrates to the new config ?

File: src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php [hunk 6]
```diff
@@ -46,8 +46,13 @@
  */
 class AuthenticatorManager implements AuthenticatorManagerInterface, UserAuthenticatorInterface
 {
+    public const NONE = 'none';
+    public const ACCOUNT_STATUS = 'account_status';
+    public const ALL = 'all';
```
Comment (stof) [inline src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php]: If the constants are on `AuthenticatorManager`, I would suggest to prefix their name with `EXPOSE_` because `AuthenticatorManager::ALL` is not clear about the meaning of the constant (is it hiding all, exposing it, managing all, authenticating all ?)

File: src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php [hunk 7]
```diff
@@ -56,9 +61,13 @@ public function __construct(
         private string $firewallName,
         private ?LoggerInterface $logger = null,
         private bool $eraseCredentials = true,
-        private bool $hideUserNotFoundExceptions = true,
+        private ?bool $hideUserNotFoundExceptions = null,
         private array $requiredBadges = [],
+        private string $exposeSecurityErrors = self::ACCOUNT_STATUS,
     ) {
+        if (null !== $this->hideUserNotFoundExceptions) {
```
Comment (stof) [inline src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php]: This is not the proper way to migrate that, because there is no way to stop passing the 8th argument (and we cannot remove that `$hideUserNotFoundExceptions` argument in 8.0 as it would shift argument positions for following ones).

Instead, we need to update the 8th argument to support a union type of the new values and a boolean. And we should **not** use a promoted property anymore for that argument, so that the private property can use the new values exclusively (having a different type and value than the constructor argument)

File: src/Symfony/Component/Security/Http/Tests/Authentication/AuthenticatorManagerTest.php [hunk 8]
```diff
@@ -365,28 +450,32 @@ public function log($level, $message, array $context = []): void
...
 
-        $manager = $this->createManager([$authenticator], 'main', true, [], $logger);
+        $manager = $this->createManager([$authenticator], 'main', \true, [], $logger, hideUserNotFoundExceptions: \true);
         $response = $manager->authenticateRequest($this->request);
         $this->assertSame($this->response, $response);
         $this->assertStringContainsString($authenticator::class, $logger->logContexts[0]['authenticator']);
     }
 
-    private function createAuthenticator(?bool $supports = true)
+    private function createAuthenticator(?bool $supports = \true)
```
Comment (stof) [inline src/Symfony/Component/Security/Http/Tests/Authentication/AuthenticatorManagerTest.php]: prefixing `true` does not make sense. This must be reverted.

File: src/Symfony/Component/Security/Http/Tests/Authentication/AuthenticatorManagerTest.php [hunk 9]
```diff
@@ -365,28 +450,32 @@ public function log($level, $message, array $context = []): void
...
 
-    private function createManager($authenticators, $firewallName = 'main', $eraseCredentials = true, array $requiredBadges = [], ?LoggerInterface $logger = null)
+    private function createManager($authenticators, $firewallName = 'main', $eraseCredentials = \true, array $requiredBadges = [], ?LoggerInterface $logger = null, string $exposeSecurityErrors = AuthenticatorManager::ACCOUNT_STATUS, ?bool $hideUserNotFoundExceptions = null)
     {
-        return new AuthenticatorManager($authenticators, $this->tokenStorage, $this->eventDispatcher, $firewallName, $logger, $eraseCredentials, true, $requiredBadges);
+        if (true === $hideUserNotFoundExceptions) {
+            $this->expectUserDeprecationMessage('Since symfony/security-http 7.2: Setting the "hideUserNotFoundExceptions" parameter is deprecated, use "exposeSecurityErrors" instead.');
+        }
+
+        return new AuthenticatorManager($authenticators, $this->tokenStorage, $this->eventDispatcher, $firewallName, $logger, $eraseCredentials, $hideUserNotFoundExceptions, $requiredBadges, exposeSecurityErrors: $exposeSecurityErrors);
```
Comment (stof) [inline src/Symfony/Component/Security/Http/Tests/Authentication/AuthenticatorManagerTest.php]: Don't use named arguments. Our BC policy does not guarantee BC for argument names. If we write tests using named arguments, it will hide cases where we break BC for positional arguments as tests will keep working without any change, which is a bad outcome.

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php [hunk 10]
```diff
@@ -56,9 +63,16 @@ public function __construct(
...
         private ?LoggerInterface $logger = null,
         private bool $eraseCredentials = true,
-        private bool $hideUserNotFoundExceptions = true,
+        string|bool $exposeSecurityErrors = self::EXPOSE_ACCOUNT_STATUS,
         private array $requiredBadges = [],
     ) {
+        if (\is_bool($exposeSecurityErrors)) {
+            trigger_deprecation('symfony/security-http', '7.3', 'Passing a boolean as "exposeSecurityErrors" parameter is deprecated, use string value instead.');
+
+            $exposeSecurityErrors = self::EXPOSE_NONE;
```
Comment (stof) [inline src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php]: This is wrong. Not all booleans should become `self::EXPOSE_NONE`. `true` and `false` have different meaning.

File: src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php [hunk 11]
```diff
@@ -56,9 +63,16 @@ public function __construct(
         private string $firewallName,
         private ?LoggerInterface $logger = null,
         private bool $eraseCredentials = true,
-        private bool $hideUserNotFoundExceptions = true,
+        string|bool $exposeSecurityErrors = self::EXPOSE_ACCOUNT_STATUS,
```
Comment (stof) [inline src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php]: the default value needs to be `EXPOSE_NONE`, to not change the existing behavior.

File: src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php [hunk 12]
```diff
@@ -46,8 +46,15 @@
  */
 class AuthenticatorManager implements AuthenticatorManagerInterface, UserAuthenticatorInterface
 {
+    public const EXPOSE_NONE = 'expose_none';
+    public const EXPOSE_ACCOUNT_STATUS = 'expose_account_status';
+    public const EXPOSE_ALL = 'expose_all';
```
Comment (stof) [inline src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php]: @wouterj suggested using an enum in the discussion. I would also prefer that instead of string constants, as it allows more precise types for our API (yes, I know that we have lots of places in Symfony that use such string constants in places where enums would make sense, but they are generally places that were added in Symfony at a time enums were not an option for us and replacing them with an enum is not worth the BC break)

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 13]
```diff
@@ -154,7 +155,13 @@ public function load(array $configs, ContainerBuilder $container): void
                 ));
         }
 
-        $container->setParameter('security.authentication.hide_user_not_found', $config['hide_user_not_found']);
+        if (true === $config['hide_user_not_found']) {
```
Comment (stof) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]: I think the BC layer should instead of handled in the MainConfiguration class, by making `beforeNormalization` set the `expose_security_errors` value when it is not set while `hide_user_not_found` is set (keeping `hide_user_not_found` as a known property without default value, just for the deprecation reporting part).
This way, things will keep working when merging multiple configurations together, where some of them are migrated but not all. The current implementation makes any `hide_user_not_found` win, even if it is specified in the first config and `expose_security_errors` is defined in a later config that should win over it.

File: src/Symfony/Component/Security/Http/Tests/Authentication/AuthenticatorManagerTest.php [hunk 14]
```diff
@@ -384,9 +469,13 @@ private static function createDummySupportsAuthenticator(?bool $supports = true)
         return new DummySupportsAuthenticator($supports);
     }
 
-    private function createManager($authenticators, $firewallName = 'main', $eraseCredentials = true, array $requiredBadges = [], ?LoggerInterface $logger = null)
+    private function createManager($authenticators, $firewallName = 'main', $eraseCredentials = true, array $requiredBadges = [], ?LoggerInterface $logger = null, bool|string $exposeSecurityErrors = AuthenticatorManager::EXPOSE_ACCOUNT_STATUS)
     {
-        return new AuthenticatorManager($authenticators, $this->tokenStorage, $this->eventDispatcher, $firewallName, $logger, $eraseCredentials, true, $requiredBadges);
+        if (true === $exposeSecurityErrors) {
```
Comment (stof) [inline src/Symfony/Component/Security/Http/Tests/Authentication/AuthenticatorManagerTest.php]: `false` should also expect a deprecation

File: src/Symfony/Component/Security/Http/Tests/Authentication/AuthenticatorManagerTest.php [hunk 15]
```diff
@@ -328,11 +371,53 @@ public function testAuthenticateRequestHidesInvalidUserExceptions()
...
+            ->with($this->equalTo($this->request), $this->callback(fn ($e) => $e instanceof BadCredentialsException && $invalidUserException === $e->getPrevious()))
+            ->willReturn($this->response);
+
+        $manager = $this->createManager([$authenticator], exposeSecurityErrors: true);
+        $response = $manager->authenticateRequest($this->request);
+        $this->assertSame($this->response, $response);
+    }
+
+    /**
+     * @group legacy
```
Comment (stof) [inline src/Symfony/Component/Security/Http/Tests/Authentication/AuthenticatorManagerTest.php]: This should not be a legacy test, as we don't want to remove that test when removing the deprecated code.

File: src/Symfony/Component/Security/Http/Tests/Authentication/AuthenticatorManagerTest.php [hunk 16]
```diff
@@ -78,9 +84,12 @@ public static function provideSupportsData()
         yield [[], false];
     }
 
+    /**
+     * @group legacy
```
Comment (stof) [inline src/Symfony/Component/Security/Http/Tests/Authentication/AuthenticatorManagerTest.php]: We cannot make all tests legacy. when removing deprecations, we remove legacy tests as well.

Tests that are not specifically about ensuring that the BC layer works fine should be migrated to use the non-deprecated API.
Some tests might be duplicated to test the same case with the old and the new configuration way, when it is about covering specifically the feature for which we have a BC layer.

For instance, `supports` is unrelated to the deprecation you introduce, so its tests have no reason to become legacy.

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Security/Http/Tests/Authentication/AuthenticatorManagerTest.php (hunk 16 above)
Comment (ChristianGripp) [reply src/Symfony/Component/Security/Http/Tests/Authentication/AuthenticatorManagerTest.php]: I've duplicated the test, so that the normal test is only testing the new logic and the `BCTest` is testing the new behavior.

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php (hunk 13 above)
Comment (ChristianGripp) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]: Moved the BC handling to the `MainConfiguration` as proposed.

**Comment by ChristianGripp** [comment]
Not sure how to fix the deprecation warnings :/

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/MainConfiguration.php [hunk 17]
```diff
@@ -54,13 +55,32 @@ public function getConfigTreeBuilder(): TreeBuilder
         $rootNode = $tb->getRootNode();
 
         $rootNode
+            ->beforeNormalization()
+                ->always()
+                ->then(function ($v) {
+                    if (isset($v['hide_user_not_found']) && !isset($v['expose_security_errors'])) {
+                        $v['expose_security_errors'] = $v['hide_user_not_found'] ? ExposeSecurityLevel::None : ExposeSecurityLevel::All;
+                    } elseif (!isset($v['expose_security_errors'])) {
+                        $v['expose_security_errors'] = ExposeSecurityLevel::None;
```
Comment (stof) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/MainConfiguration.php]: This should **not** be the case. If a config does not configure the setting at all (neither through the old nor the new name), we should not force it to configure it as NONE, which would override a setting coming from a previous config file during merging.

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/MainConfiguration.php [hunk 18]
```diff
@@ -54,13 +55,32 @@ public function getConfigTreeBuilder(): TreeBuilder
...
+            ->end()
             ->children()
                 ->scalarNode('access_denied_url')->defaultNull()->example('/foo/error403')->end()
                 ->enumNode('session_fixation_strategy')
                     ->values([SessionAuthenticationStrategy::NONE, SessionAuthenticationStrategy::MIGRATE, SessionAuthenticationStrategy::INVALIDATE])
                     ->defaultValue(SessionAuthenticationStrategy::MIGRATE)
                 ->end()
-                ->booleanNode('hide_user_not_found')->defaultTrue()->end()
+                ->booleanNode('hide_user_not_found')
+                    ->defaultNull()
```
Comment (stof) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/MainConfiguration.php]: `->defaultNull()` should be removed. We don't need a default at all as the DI extension won't need to use it.

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/MainConfiguration.php [hunk 19]
```diff
@@ -54,13 +55,32 @@ public function getConfigTreeBuilder(): TreeBuilder
...
+                    ->setDeprecated('symfony/security-bundle', '7.3', 'The "%node%" option is deprecated and will be removed in 8.0. Use the "expose_security_errors" option instead.')
+                ->end()
+                ->enumNode('expose_security_errors')
+                    ->values(ExposeSecurityLevel::cases())
+                    ->defaultNull()
```
Comment (stof) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/MainConfiguration.php]: The default should be `ExposeSecurityLevel::None` (matching the existing default)

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 20]
```diff
@@ -154,7 +155,8 @@ public function load(array $configs, ContainerBuilder $container): void
                 ));
         }
 
-        $container->setParameter('security.authentication.hide_user_not_found', $config['hide_user_not_found']);
+        $container->setParameter('security.authentication.hide_user_not_found', ExposeSecurityLevel::None !== $config['expose_security_errors']);
```
Comment (stof) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]: This is wrong. The level that is not hiding errors is `All`, not `None`

File: src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php [hunk 21]
```diff
@@ -56,9 +58,17 @@ public function __construct(
...
         private ?LoggerInterface $logger = null,
         private bool $eraseCredentials = true,
-        private bool $hideUserNotFoundExceptions = true,
+        ExposeSecurityLevel|bool $exposeSecurityErrors = ExposeSecurityLevel::None,
         private array $requiredBadges = [],
     ) {
+        if (\is_bool($exposeSecurityErrors)) {
+            trigger_deprecation('symfony/security-http', '7.3', 'Passing a boolean as "exposeSecurityErrors" parameter is deprecated, use %s value instead.', ExposeSecurityLevel::class);
+
+            // The old parameter had an inverted meaning ($hideUserNotFoundExceptions), for that reeason the current name does not reflect the behavior
```
Comment (stof) [inline src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php]:
```suggestion
            // The old parameter had an inverted meaning ($hideUserNotFoundExceptions), for that reason the current name does not reflect the behavior
```

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/MainConfiguration.php [hunk 22]
```diff
@@ -54,13 +55,32 @@ public function getConfigTreeBuilder(): TreeBuilder
...
                     ->values([SessionAuthenticationStrategy::NONE, SessionAuthenticationStrategy::MIGRATE, SessionAuthenticationStrategy::INVALIDATE])
                     ->defaultValue(SessionAuthenticationStrategy::MIGRATE)
                 ->end()
-                ->booleanNode('hide_user_not_found')->defaultTrue()->end()
+                ->booleanNode('hide_user_not_found')
+                    ->defaultNull()
+                    ->setDeprecated('symfony/security-bundle', '7.3', 'The "%node%" option is deprecated and will be removed in 8.0. Use the "expose_security_errors" option instead.')
+                ->end()
+                ->enumNode('expose_security_errors')
+                    ->values(ExposeSecurityLevel::cases())
```
Comment (stof) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/MainConfiguration.php:79]: This node should have a `beforeNormalization` turning strings into enum instances, to allow using the backing value of the enum in the config (which is simpler in XML for instance)

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/MainConfiguration.php [hunk 23]
```diff
@@ -54,13 +55,32 @@ public function getConfigTreeBuilder(): TreeBuilder
...
                 ->enumNode('session_fixation_strategy')
                     ->values([SessionAuthenticationStrategy::NONE, SessionAuthenticationStrategy::MIGRATE, SessionAuthenticationStrategy::INVALIDATE])
                     ->defaultValue(SessionAuthenticationStrategy::MIGRATE)
                 ->end()
-                ->booleanNode('hide_user_not_found')->defaultTrue()->end()
+                ->booleanNode('hide_user_not_found')
+                    ->defaultNull()
+                    ->setDeprecated('symfony/security-bundle', '7.3', 'The "%node%" option is deprecated and will be removed in 8.0. Use the "expose_security_errors" option instead.')
+                ->end()
+                ->enumNode('expose_security_errors')
```
Comment (stof) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/MainConfiguration.php:77]: You need to add the `expose-security-errors` attribute in the XSD as well, to make this setting usable in XML config files.

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Bundle/SecurityBundle/CHANGELOG.md [hunk 24]
```diff
@@ -6,6 +6,7 @@ CHANGELOG
 
  * Allow configuring the secret used to sign login links
  * Allow passing optional passport attributes to `Security::login()`
+ * Add `expose_security_errors` config option to display `AccountStatusException`
```
Comment (stof) [inline src/Symfony/Bundle/SecurityBundle/CHANGELOG.md]: This must go in a new `7.3` section in the changelog, not in the `7.2` section.

File: src/Symfony/Component/Security/Http/CHANGELOG.md [hunk 25]
```diff
@@ -8,6 +8,7 @@ CHANGELOG
  * Deprecate argument `$secret` of `RememberMeAuthenticator`
  * Deprecate passing an empty string as `$userIdentifier` argument to `UserBadge` constructor
  * Allow passing passport attributes to the `UserAuthenticatorInterface::authenticateUser()` method
+ * Replace `$hideAccountStatusExceptions` argument with `$exposeSecurityErrors` in `AuthenticatorManager` constructor
```
Comment (stof) [inline src/Symfony/Component/Security/Http/CHANGELOG.md]: This must go in a new `7.3` section in the changelog, not in the `7.2` section.

**Comment by ChristianGripp** [comment]
Thanks for the review @stof :)

Applied your suggestions and the build is passing

**Comment by chalasr** [comment]
@core23 Can you please update the UPGRADE-7.3 file about the deprecated option? And add a line about that deprecation in the already updated CHANGELOG file also?

**Comment by ChristianGripp** [comment]
Done :)

File: src/Symfony/Bundle/SecurityBundle/CHANGELOG.md [hunk 26]
```diff
@@ -5,6 +5,8 @@ CHANGELOG
 ---
 
  * Add `Security::isGrantedForUser()` to test user authorization without relying on the session. For example, users not currently logged in, or while processing a message from a message queue
+ * Add `expose_security_errors` config option to display `AccountStatusException`
+* Deprecate the `security.hide_user_not_found` config option in favor of `security.expose_security_errors`
```
Comment (chalasr) [inline src/Symfony/Bundle/SecurityBundle/CHANGELOG.md]:
```suggestion
 * Deprecate the `security.hide_user_not_found` config option in favor of `security.expose_security_errors`
```

File: UPGRADE-7.3.md [hunk 27]
```diff
@@ -8,6 +8,12 @@ Read more about this in the [Symfony documentation](https://symfony.com/doc/7.3/
 
 If you're upgrading from a version below 7.1, follow the [7.2 upgrade guide](UPGRADE-7.2.md) first.
 
+
+SecurityBundle
+--------------
+
+* Deprecate the `security.hide_user_not_found` config option in favor of `security.expose_security_errors`
```
Comment (chalasr) [inline UPGRADE-7.3.md]:
```suggestion
 * Deprecate the `security.hide_user_not_found` config option in favor of `security.expose_security_errors`
```

**Comment by ChristianGripp** [comment]
Any chance to get this merge soon-ish? @chalasr

**Review by chalasr — APPROVED** [review]
Can you please rebase?

**Comment by ChristianGripp** [comment]
Done. The failing tests look unrelated to the changes

**Comment by chalasr** [comment]
Thank you @core23.
