### PR TITLE
[Filesystem] Strengthen the check of file permissions in `dumpFile`

### LINKED ISSUE #54444: Filesystem dumpFile creates file with chmod 0 because fileperms fails
### Symfony version(s) affected

7

### Description

Running Prestashop (it's use Symfony framework) on a very busy web site, after we clear cache (rm var/cache) from Prestashop admin, any HTTP call to Prestashop frontend create cache file using Symfony Filesystem dumpFile method.

Files created have a chmod 0, hence this gives fatal error "cannot include appParameters.php, permissions denied".

## Affected version

Tested on Symfony 4 but should affect all versions.

## Root cause

`file_exists` function will use opcache but `fileperms` not, so this code at https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Filesystem/Filesystem.php#L665:

```php
self::box('chmod', $tmpFile, file_exists($filename) ? fileperms($filename) : 0666 & ~umask());
```

Creates file with chmod 0

### How to reproduce

With opcache settings:

```
opcache.validate_timestamps=0
opcache.enable_file_override=1
```

I use apache web server but this should work with nginx / php-fpm too.

1. Create a file "existing.php", cache it in opcache: `curl localhost/existing.php`
2. Create a bug.php, call it `curl localhost/bug.php` --> this is working as expected
3. Remove existing.php file `rm existing.php`
4. `curl localhost/bug.php` will create the file `----------. 1 www-data www-data 26 Mar 30 17:54 existing.php`

Capture d’écran, le 2024-03-30 à 13 57 15

bug.php

```php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Filesystem\Filesystem;

$file = __DIR__ . '/existing.php';

echo "File $file" . PHP_EOL;

echo "File exists: " . strize(file_exists($file)) . PHP_EOL;

echo "fileperms: " . strize(fileperms($file)) . PHP_EOL;

(new Filesystem())->dumpFile($file, '<?php echo "hello world"; ');

function strize($bool): string {
    if ($bool === true) return 'true';
    if ($bool === false) return 'false';
    return $bool;
}
```

### Possible Solution

In method https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Filesystem/Filesystem.php#L665, use this code block to get the chmod:

```php
        $chmod = 0666 & ~umask();

        if (file_exists($filename)) {
            $existingChmod = fileperms($filename);

            if ($existingChmod !== false) {
                $chmod = $existingChmod;
            }
        }

        chmod($tmpFile, $chmod);
```

`clearstatcache(true, $file);` didnt help.

### Additional Context

Related issues:
- https://github.com/PrestaShop/PrestaShop/issues/17390
- https://engineering.facile.it/blog/eng/realpath-cache-is-it-all-php-opcache-s-fault/

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54444
| License       | MIT

`fileperms()` can fail and return `false`, I think we should strengthen the checks on its return value when using it to avoid undesirable behavior.

### CODE REVIEW

File: src/Symfony/Component/Filesystem/Filesystem.php [hunk 1]
```diff
@@ -691,7 +691,8 @@ public function dumpFile(string $filename, $content)
                 throw new IOException(sprintf('Failed to write file "%s": ', $filename).self::$lastError, 0, null, $filename);
             }
 
-            self::box('chmod', $tmpFile, file_exists($filename) ? fileperms($filename) : 0666 & ~umask());
+            $perms = @fileperms($filename);
+            self::box('chmod', $tmpFile, file_exists($filename) && false !== $perms ? $perms : 0666 & ~umask());
```
Comment (rosier) [inline src/Symfony/Component/Filesystem/Filesystem.php]:
```suggestion
            self::box('chmod', $tmpFile, file_exists($filename) && false !== ($perms = fileperms($filename)) ? $perms : 0666 & ~umask());
```

Comment (alexandre-daubois) [reply src/Symfony/Component/Filesystem/Filesystem.php]: This isn't permitted by PHP, `$perms` is undefined in the first branch of the ternary expression with this syntax.

Comment (rosier) [reply src/Symfony/Component/Filesystem/Filesystem.php]: Ah yes, it needs () around the perms part.

Another option might be to shorten it to:
```
self::box('chmod', $tmpFile, @fileperms($filename) ?: 0666 & ~umask());
```

File: src/Symfony/Component/Mime/Tests/AbstractMimeTypeGuesserTestCase.php [hunk 2]
```diff
@@ -116,7 +116,8 @@ public function testGuessWithNonReadablePath()
         touch($path);
         @chmod($path, 0333);
 
-        if (str_ends_with(sprintf('%o', fileperms($path)), '0333')) {
+        $perms = @fileperms($path);
+        if (false !== $perms && str_ends_with(sprintf('%o', $perms), '0333')) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mime/Tests/AbstractMimeTypeGuesserTestCase.php]: just adding the `@` would provide the same behavior - but this is a test case so I'd rather see the warning, unless it shows up too often?

Comment (alexandre-daubois) [reply src/Symfony/Component/Mime/Tests/AbstractMimeTypeGuesserTestCase.php]: I agree with you, let's revert until someone actually complains about it

File: src/Symfony/Component/Filesystem/Filesystem.php (hunk 1 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/Filesystem/Filesystem.php]: Good catch, I updated accordingly. Thanks!

**Comment by nicolas-grekas** [comment]
Thank you @alexandre-daubois.

**Comment by ebuildy** [comment]
Fantastic this is merged ! Thanks you guys

**Comment by oojacoboo** [comment]
So, somehow this change has broken our container caching layer.  Looked into it a bit and I'm not even seeing any permissions issues with the actual files being dumped/written.  They have user write permissions (644) and the proper user ownership.

```
fileperms(): stat failed for /tmp/cache/apiDevProjectContainer.php in /srv/www/vendor/symfony/filesystem/Filesystem.php:689 ErrorException called
```

**Comment by acoulton** [comment]
@oojacoboo we're getting that too - I assume you have a custom error handler registered and it's intercepting the (expected) error generated when writing a non-existent file. I've proposed a fix in #54878

**Comment by oojacoboo** [comment]
@acoulton yep, custom error handler.  Not quite sure why that makes a difference though.  Is Symfony framework just ignoring it?

**Comment by xabbuh** [comment]
@oojacoboo Your custom error handler does not seem to honour if an error is silenced.

**Comment by oojacoboo** [comment]
@xabbuh thanks.  We actually had error suppression handled.  PHP8 changed the return on `error_reporting`, and it now returns the value of a bitwise operation.

https://www.php.net/manual/en/language.operators.errorcontrol.php

Was able to get it resolved.  Thanks for the tip.

**Comment by shakaran** [comment]
Related #57077 for 7.0.7
