### PR TITLE
[FrameworkBundle] Dont store cache misses on warmup

### LINKED ISSUE #38694: SF 5.2 doctrine/persistence
**Symfony version(s) affected**: 5.2

**Description**  
Hi,

Just to point out that with each update of 5.2 via composer, I am forced after to redo a composer req doctrine/persistence, otherwise I have errors with the default user registration system. The login is fine, but each time it has an impact on the registration and the lost password.

**How to reproduce**  
composer update
I suspect updating dbal

**Possible Solution**  
composer req doctrine/persistence

**Additional context**  
If needed at the next update

### PR DESCRIPTION
**Pull request by Nyholm**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38694
| License       | MIT
| Doc PR        | symfony/symfony-docs#15172

When we are warming the annotation cache, we are reading all annotation into an `ArrayAdapter`. When we are done we move the values to a `PhpArrayAdapter` to store them in a file. 

@Seldaek [found out](https://github.com/symfony/symfony/issues/38694#issuecomment-810501066) that when you are using a custom constraint with a `Symfony\Component\Validator\Constraints\Callback`, there is a strange error like: 

> Can use "yield from" only with arrays and Traversables

That is because the `Closure` in the `Symfony\Component\Validator\Constraints\Callback` cannot be serialised and saved to cache. But since the `ArrayAdapter` is also [storing misses as null](https://github.com/symfony/symfony/pull/35362), the null values are understood as real values. 

When all values are moved to the `PhpArrayAdapter` and we ask the cache for a value (via Doctrine's `CacheProvider`), it will return `null` as a value instead of `false` as a cache miss. And `null` is not something one could "yield from".

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/Tests/CacheWarmer/AnnotationsCacheWarmerTest.php [hunk 1]
```diff
@@ -120,6 +121,36 @@ public function testClassAutoloadExceptionWithUnrelatedException()
...
+        $warmer->method('doWarmUp')->willReturnCallback(function ($cacheDir, ArrayAdapter $arrayAdapter) {
+            $arrayAdapter->getItem('foo_miss');
+
+            $item = $arrayAdapter->getItem('bar_hit');
+            $item->set('data');
+            $arrayAdapter->save($item);
+
+            $item = $arrayAdapter->getItem('baz_hit_null');
+            $item->set(null);
+            $arrayAdapter->save($item);
```
Comment (Nyholm) [inline src/Symfony/Bundle/FrameworkBundle/Tests/CacheWarmer/AnnotationsCacheWarmerTest.php:141]: If we are storing `null` in the cache, then we would still get this error. However, I consider that potential scenario as a separate bug.

**Comment by Nyholm** [comment]
@carsonbot could you find me a reviewer please?

**Comment by Nyholm** [comment]
Oh. I guess it was too long ago @dmaicher wrote this class =)

David, do you mind having a look at this PR?

**Comment by Seldaek** [comment]
Thanks for the quick fix :)

If I understand correctly though, this means using lambdas like that will prevent caching of the resolved config and it'll reload on every request needing it. I guess it's thus worth avoiding lambda callbacks..

**Comment by Nyholm** [comment]
Yes, that is correct.

**Comment by Nyholm** [comment]
I updated the docs with this observation: https://github.com/symfony/symfony-docs/pull/15172

**Comment by nicolas-grekas** [comment]
Storing misses is an important part of the performance provided by system caches.
We should look for another solution if possible.

**Comment by Nyholm** [comment]
Yes, but these "misses" are interpreted as "hits". A "hit" with null is not the same as a miss. There should never be "null" stored in **this** cache. 

I have two alternative solutions. The first would be to find a way to serialize a `\Closure`. The second one is to throw an exception on cache warmup when you fail to save a value in cache.

**Comment by nicolas-grekas** [comment]
The test case passes even without the change if I didn't mess up :)

> Yes, but these "misses" are interpreted as "hits". A "hit" with null is not the same as a miss. There should never be "null" stored in this cache.

For system caches, aka the ones sourced by the code itself, we can do this - cache misses.
We built this logic because it saves CPU cycles, eg you don't want to read the annotations again on methods that don't have any annotation.

> I have two alternative solutions. The first would be to find a way to serialize a \Closure. The second one is to throw an exception on cache warmup when you fail to save a value in cache.

Why a closure ends up in the cache? That's the main question I have here indeed. An annotation should not lead to a closure because then of course it cannot be cached - while the source is a plain descriptive annotation.

The second solution would be a major regression actually.

Can you try this patch instead? It tries to not store misses for failures-to-save().
```
--- a/src/Symfony/Component/Cache/Traits/ArrayTrait.php
+++ b/src/Symfony/Component/Cache/Traits/ArrayTrait.php
@@ -145,6 +145,7 @@ trait ArrayTrait
             try {
                 $serialized = serialize($value);
             } catch (\Exception $e) {
+                unset($this->values[$key]);
                 $type = \is_object($value) ? \get_class($value) : \gettype($value);
                 $message = sprintf('Failed to save key "{key}" of type %s: ', $type).$e->getMessage();
                 CacheItem::log($this->logger, $message, ['key' => $key, 'exception' => $e]);
```

**Comment by Nyholm** [comment]
> The test case passes even without the change if I didn't mess up :)

You did mess up =)

```
❯ ./phpunit src/Symfony/Bundle/FrameworkBundle/Tests/CacheWarmer 
#!/usr/bin/env php
PHPUnit 9.5.3 by Sebastian Bergmann and contributors.

Testing /src/Symfony/Bundle/FrameworkBundle/Tests/CacheWarmer
....F..............                                               19 / 19 (100%)

Time: 00:00.091, Memory: 16.00 MB

There was 1 failure:

1) Symfony\Bundle\FrameworkBundle\Tests\CacheWarmer\AnnotationsCacheWarmerTest::testWarmupRemoveCacheMisses
Failed asserting that actual size 3 matches expected size 2.

/src/Symfony/Bundle/FrameworkBundle/Tests/CacheWarmer/AnnotationsCacheWarmerTest.php:149
```

> Why a closure ends up in the cache?

Because we cache an object of `Symfony\Component\Validator\Constraint\Callback`. That object is given a closure by the user in its constructor. 

> Can you try this patch instead? It tries to not store misses for failures-to-save().

I think that would work. But the end result would be the same. We would reread the annotations at runtime. 
Note that we still cache the empty array. Which means "we have read the annotations, and there weren't any".

**Comment by nicolas-grekas** [comment]
> You did mess up =)

I confirm :P

> Because we cache an object of Symfony\Component\Validator\Constraint\Callback. That object is given a closure by the user in its constructor.

I just read the doc PR, nice one.

> I think that would work. But the end result would be the same. We would reread the annotations at runtime.

True, but we would still store misses, and this is important for the other system caches.

> Note that we still cache the empty array. Which means "we have read the annotations, and there weren't any".

OK great, then I suppose other system caches need this. Annotations are not the only system caches, but the current patch changes the behavior for all of them.

File: src/Symfony/Bundle/FrameworkBundle/CacheWarmer/ValidatorCacheWarmer.php [hunk 2]
```diff
@@ -79,8 +79,12 @@ protected function doWarmUp($cacheDir, ArrayAdapter $arrayAdapter)
 
     protected function warmUpPhpArrayAdapter(PhpArrayAdapter $phpArrayAdapter, array $values)
     {
+        $values = array_filter($values, function ($val) {
+            return $val !== null;
+        });
+
         // make sure we don't cache null values
-        parent::warmUpPhpArrayAdapter($phpArrayAdapter, array_filter($values));
+        parent::warmUpPhpArrayAdapter($phpArrayAdapter, $values);
```
Comment (Nyholm) [inline src/Symfony/Bundle/FrameworkBundle/CacheWarmer/ValidatorCacheWarmer.php]: `array_filter($values)` will also remove everything that is `empty`.

https://3v4l.org/0m3In

There is no test for this code and I am not sure why `null` should be removed. I can only assume it is because of the callback =)

**Comment by Nyholm** [comment]
I was wrong patching `AbstractPhpFileCacheWarmer`. What I really wanted to do is to only modify the behaviour of the `AnnotationCacheWarmer`. 

> Can you try this patch instead? It tries to not store misses for failures-to-save().

This is not reliable. If a user does something like this, the bug will occur again. 

```php
$i = $cache->getItem('foo');
$i->set('data');
$cache->save($i); // Save failed for some reason.

// ...
$cache->getItem('foo');
```

File: src/Symfony/Bundle/FrameworkBundle/CacheWarmer/AnnotationsCacheWarmer.php [hunk 3]
```diff
@@ -76,6 +77,16 @@ protected function doWarmUp($cacheDir, ArrayAdapter $arrayAdapter)
         return true;
     }
 
+    protected function warmUpPhpArrayAdapter(PhpArrayAdapter $phpArrayAdapter, array $values)
+    {
+        $values = array_filter($values, function ($val) {
+            return null !== $val;
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/CacheWarmer/AnnotationsCacheWarmer.php]: could be on one line (same below)

File: src/Symfony/Bundle/FrameworkBundle/CacheWarmer/AnnotationsCacheWarmer.php [hunk 4]
```diff
@@ -76,6 +77,16 @@ protected function doWarmUp($cacheDir, ArrayAdapter $arrayAdapter)
...
+        });
+
+        // make sure we don't cache null values
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/CacheWarmer/AnnotationsCacheWarmer.php:82]: could be moved before the call to array_filter (same below)

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Bundle/FrameworkBundle/CacheWarmer/AnnotationsCacheWarmer.php (hunk 4 above)
Comment (Nyholm) [reply src/Symfony/Bundle/FrameworkBundle/CacheWarmer/AnnotationsCacheWarmer.php:82]: Fixed

File: src/Symfony/Bundle/FrameworkBundle/CacheWarmer/AnnotationsCacheWarmer.php (hunk 3 above)
Comment (Nyholm) [reply src/Symfony/Bundle/FrameworkBundle/CacheWarmer/AnnotationsCacheWarmer.php]: Fixed

**Comment by Nyholm** [comment]
The PR is updated

**Comment by dmaicher** [comment]
> Oh. I guess it was too long ago @dmaicher wrote this class =)
> 
> David, do you mind having a look at this PR?

I think my work on that was related to https://github.com/symfony/symfony/pull/23558

But now I see you changed the PR anyway :blush:

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @Nyholm.
