### PR TITLE
[FrameworkBundle] Add `exit` option to `secrets:decrypt-to-local` command

### LINKED ISSUE #57539: secrets:decrypt-to-local always exits successfully, even when there were errors
### Description

The `secrets:decrypt-to-local` command exits successfully, even when there are errors.
This seems to be by design, and was changed here:
https://github.com/symfony/symfony/pull/43137

Steps to reproduce:
1. Do not set an env for the decryption key
2.  Run `bin/console secrets:decrypt-to-local --force --env=prod`
3. Errors are printed, saying decryption failed.
4. Inspect exit code (echo $?), it is 0.

This makes it very hard to have reliable usage in deployment scripts, as no matter if the command fails or not, it exits with code 0 (e.g. missing decryption key) -- for the moment I'm grepping the output to work around this.

I propose either that an appropriate exit code is returned when secrets are not decrypted properly.
This can be opt in, via a CLI flag (e.g. bin/console secrets:decrypt-to-local --force --env=prod **--fail-on-errors**).

### Example

```
bin/console secrets:decrypt-to-local --force --env=prod **--fail-on-errors**
echo $? // prints 1 if there were errors

OR

bin/console secrets:decrypt-to-local --force --env=prod
echo $? // prints 1 if there were errors
```

### PR DESCRIPTION
**Pull request by dciprian-petrisor**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #57539 
| License       | MIT

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/Command/SecretsDecryptToLocalCommand.php [hunk 1]
```diff
@@ -38,6 +38,7 @@ public function __construct(
     protected function configure(): void
     {
         $this
+            ->addOption('strict', 's', InputOption::VALUE_NONE, 'Returns a non-zero exit code if any errors are encountered')
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Command/SecretsDecryptToLocalCommand.php]: What about naming this `--exit`? Strict doesn't tell what it does

Comment (dciprian-petrisor) [reply src/Symfony/Bundle/FrameworkBundle/Command/SecretsDecryptToLocalCommand.php]: Agreed, I updated the MR.

File: src/Symfony/Bundle/FrameworkBundle/Command/SecretsDecryptToLocalCommand.php [hunk 2]
```diff
@@ -38,6 +38,7 @@ public function __construct(
     protected function configure(): void
     {
         $this
+            ->addOption('exit', 'e', InputOption::VALUE_NONE, 'Returns a non-zero exit code if any errors are encountered')
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Command/SecretsDecryptToLocalCommand.php]: -e is already taken so better define no alias

Comment (dciprian-petrisor) [reply src/Symfony/Bundle/FrameworkBundle/Command/SecretsDecryptToLocalCommand.php]: done

File: src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md [hunk 3]
```diff
@@ -8,6 +8,7 @@ CHANGELOG
  * Derivate `kernel.secret` from the decryption secret when its env var is not defined
  * Make the `config/` directory optional in `MicroKernelTrait`, add support for service arguments in the
    invokable Kernel class, and register `FrameworkBundle` by default when the `bundles.php` file is missing
+ * Add exit mode option for `secrets:decrypt-to-local` command
```
Comment (OskarStark) [inline src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md]:
```suggestion
 * Add `exit` option for `secrets:decrypt-to-local` command
```

File: src/Symfony/Bundle/FrameworkBundle/Command/SecretsDecryptToLocalCommand.php [hunk 4]
```diff
@@ -47,6 +48,10 @@ protected function configure(): void
 When the option <info>--force</info> is provided, secrets that already exist in the local vault are overriden.
 
     <info>%command.full_name% --force</info>
+
+When the option <info>--exit</info> is provided, the command will return a non-zero exit code if any errors are encountered.
```
Comment (OskarStark) [inline src/Symfony/Bundle/FrameworkBundle/Command/SecretsDecryptToLocalCommand.php]:
```suggestion
When the <info>--exit</info> option is provided, the command will return a non-zero exit code if any errors are encountered.
```

same for the option above, thanks

**Review by nicolas-grekas — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @dciprian-petrisor.
