### PR TITLE
Messenger multiple failed transports

### LINKED ISSUE #34911: [Messenger][Feature] Failed queue per transport
**Description**  
Currently we can only set one failed queue that is available for every transport.

What happens if we want different behaviours? 

Like, one queue that we just want to discard the failed queue and others where we care and want to use the failed queue (a specific one or the same global one)?

**Example**  

```yaml
# config/packages/messenger.yaml
framework:
    # no need to set failed transport globally if I want a specific behaviour per transport.
    messenger:
        transports:
            failed: 'doctrine://default?queue_name=failed'
            failed_important: 'doctrine://default?queue_name=failed_important'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failure_transport: failed
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
            async_no_failure_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
            async_send_specific_failure_queue:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failure_transport: failed_important
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
```

This feature covers for example cases where you need to make distinguish between:
- Events that are constantly being generated and you don't care if they fail after the number of retries
- Events that you need to be absolutely sure that they need to be executed, and moved to a different failed queue (to be debugged by a specific team related with a specific queue. It could even be a very important queue, and you need to prioritise the debug of those events)

I don't mind to try to implement this behaviour. 
Just wanted to know your feedback.

### PR DESCRIPTION
**Pull request by monteiro**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Tickets       | Fix #34911 
| License       | MIT
| Doc PR        | symfony/symfony-docs#13489

## Strategy applied

- Pass a map of transports and failed transports to the `SendFailedMessageToFailureTransportListener`. This way we re-use the same listener.
- Local failed transport has more priority than a global failed transport defined. 

## Configuration example

```yaml
# config/packages/messenger.yaml
framework:
    # no need to set failed transport globally if I want a specific behaviour per transport.
    failure_transport: failed # all transports have this failed transport
    messenger:
        transports:
            failed: 'doctrine://default?queue_name=failed'
            failed_important: 'doctrine://default?queue_name=failed_important'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failure_transport: failed # takes precedence over the global defined "failed_transport"
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
            async_no_failure_transport: # it will use the global defined transport if no one is defined.
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
            async_send_specific_failure_queue:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failed_transport: failed_important # takes precedence over the global defined "failed_transport"
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
```

You can test this feature easily on a [demo project](https://github.com/monteiro/messenger-multiple-failed-transports-pr34979). Just follow the [README](https://github.com/monteiro/messenger-multiple-failed-transports-pr34979).

**More information on issue #34911** 

## What needs to be done so this can be merged:
- [x] validate strategy 
- [ ] update src/**/CHANGELOG.md files
- [x] update tests to cover all cases
- [x] create doc PR

### CODE REVIEW

**Comment by monteiro** [comment]
@weaverryan i have removed some of the tests because of merging conflicts.. since this is still being changed a lot... after we agree on an implementation it’s easy to fix them.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -1865,25 +1869,53 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
...
+                ->replaceArgument(0, $globalFailureReceiver);
             $container->getDefinition('console.command.messenger_failed_messages_show')
-                ->replaceArgument(0, $config['failure_transport']);
+                ->replaceArgument(0, $globalFailureReceiver);
             $container->getDefinition('console.command.messenger_failed_messages_remove')
-                ->replaceArgument(0, $config['failure_transport']);
+                ->replaceArgument(0, $globalFailureReceiver);
+
+            $failureTransportsByTransportNameServiceLocator = ServiceLocatorTagPass::register($container, $failureTransportsByTransportName, $failureTransportsByTransportNameServiceLocatorId);
+            $container->getDefinition($failureTransportsByTransportNameServiceLocatorId)
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: I don't *think* that we need this `$failureTransportsByTransportNameServiceLocatorId` variable - most of the time, we don't pass a 3rd argument to `ServiceLocatorTagPass::register()`. But I'm not actually sure what you're needing to accomplish here. Why do we need to replace the first (0) argument on the next line?

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 2]
```diff
@@ -1865,25 +1869,53 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
...
+                ->replaceArgument(0, $failureTransportsByTransportName);
+            $container->getDefinition('messenger.failure.send_failed_message_to_failure_transport_listener')
+                ->replaceArgument(0, $failureTransportsByTransportNameServiceLocator);
         } else {
-            $container->removeDefinition('messenger.failure.send_failed_message_to_failure_transport_listener');
             $container->removeDefinition('console.command.messenger_failed_messages_retry');
             $container->removeDefinition('console.command.messenger_failed_messages_show');
             $container->removeDefinition('console.command.messenger_failed_messages_remove');
+            $container->removeDefinition('messenger.failure.send_failed_message_to_failure_transport_listener');
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: this line just moved down 5 lines. We can revert to make the diff smaller.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 1 above)
Comment (weaverryan) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Related, I'm not sure that we need to manually create a `messenger.failure_transports_by_transport_name.locator` service in the `messenger.php` file. I think (?) usually when we call `ServiceLocatorTagPass::register()`, THAT registers a service locator service for us - it doesn't ned to be already-registered somewhere.

Comment (monteiro) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: This has already been fixed in this [commit](https://github.com/symfony/symfony/pull/38468/commits/19ed68cb764cebd6cd6a19e0fea420eb25c2dfc1)

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 3]
```diff
@@ -1865,20 +1869,45 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
...
 
         if ($config['failure_transport']) {
             if (!isset($senderReferences[$config['failure_transport']])) {
                 throw new LogicException(sprintf('Invalid Messenger configuration: the failure transport "%s" is not a valid transport or service id.', $config['failure_transport']));
             }
 
-            $container->getDefinition('messenger.failure.send_failed_message_to_failure_transport_listener')
-                ->replaceArgument(0, $senderReferences[$config['failure_transport']]);
+            $hasFailureTransports = true;
+            $failureTransports[$config['failure_transport']] = $senderReferences[$config['failure_transport']];
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: I think this is an undefined variable?

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/console.php [hunk 4]
```diff
@@ -176,14 +176,14 @@
         ->set('console.command.messenger_failed_messages_show', FailedMessagesShowCommand::class)
             ->args([
                 abstract_arg('Receiver name'),
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/console.php]: Maybe now "Default failure receiver name"

File: src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php [hunk 5]
```diff
@@ -251,9 +252,24 @@ private function guessHandledClasses(\ReflectionClass $handlerClass, string $ser
...
         $receiverMapping = [];
+        $failureTransportsMap = [];
+
+        $globalFailureTransportId = 'messenger.failure_transports.default';
+        if ($container->hasAlias($globalFailureTransportId)) {
+            $globalFailureTransport = (string) $container->getAlias($globalFailureTransportId);
+            if (null !== $globalFailureTransport) {
+                $failureTransportsMap[$globalFailureTransport] = new Reference('messenger.transport.'.$globalFailureTransport);
+            }
+        }
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php:265]: I'm not sure what this section is going. Is it... setting the "failure transport" of the "global failure transport" to itself? If so, why?

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 6]
```diff
@@ -1805,7 +1805,11 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
             $transportDefinition = (new Definition(TransportInterface::class))
                 ->setFactory([new Reference('messenger.transport_factory'), 'createTransport'])
                 ->setArguments([$transport['dsn'], $transport['options'] + ['transport_name' => $name], new Reference($serializerId)])
-                ->addTag('messenger.receiver', ['alias' => $name])
+                ->addTag('messenger.receiver', [
+                        'alias' => $name,
+                        'failure_transport' => $transport['failure_transport'] ?? null,
+                    ]
+                )
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:1949]: I think we can simplify (the complication is based off of my original, not perfect understanding), which will *really* simplify things in MessengerPass.

On a high level, what we care about is this: "can this receiver also be used as a failure receiver?". And we care about this for one simple (not-that-important) reason: so that we know if it can be used on the `messenger:failed:*` commands with the new `--failure-transport=` option.

So, instead of setting `failure_transport => 'some string'`, which communicates which failure transport this receiver is assigned to (I think we don't actually care about that), what if the new attribute is just `failure_transport => true/false` (and it would default to false if not set).

Basically, we would determine if this receiver is being used as a failure transport or not. If it is, we add `failure_transport = true`. Then, in `MessengerPass`, we can read this option. We would use the `alias` to know the *name* of this failure transport.

To do this, we'll need to do some more work here in `FrameworkExtension`. I think we may need move the 2nd `foreach ($config['transports'] as $name => $transport) {` that you have below to be ABOVE this section, so that we can create a map/array of which transports have at least one other transport using them as a `failure_transport` (taking into account, of course, the global failure transport). Then, inside this loop, we can use that map/array to set the `failure_transport = true/false` alias option.

THEN, way over in `MessengerPass`, we would create the `$failureTransportsMap` a bit more like how we currently create the `$receiverMapping` variable inside the `foreach ($container->findTaggedServiceIds($this->receiverTag) as $id => $tags) {` - something like this:

```diff
$receiverMapping[$id] = new Reference($id);
foreach ($tags as $tag) {
    if (isset($tag['alias'])) {
        $receiverMapping[$tag['alias']] = $receiverMapping[$id];

+         // I'm requiring the "alias" to be set for failure_transport to work
+         // that's probably ok... but we could also be smarter and use
+         // $tag['alias'] OR fallback to $id, like is done with $receiverMapping
+         if (isset($tag['failure_transport']) && null !== $tag['failure_transport']) {
+             $failureTransportsMap[$tag['alias']] = $receiverMapping[$id];
+         }
    }
}
```

**Comment by monteiro** [comment]
@weaverryan I just uploaded a working version of your proposal. Feel free to review, before I do the tests. Thanks!

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 7]
```diff
@@ -1836,6 +1863,19 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
...
+                if (!isset($config['transports'][$transport['failure_transport']])) {
+                    throw new LogicException(sprintf('Invalid Messenger configuration: the failure transport "%s" is not a valid transport or service id.', $transport['failure_transport']));
+                }
+
+                $failureTransportsByTransportName[$name] = $senderReferences[$transport['failure_transport']];
+            } else {
+                $failureTransportsByTransportName[$name] = $senderReferences[$config['failure_transport']] ?? null;
+            }
+        }
+
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:1991]: Could this entire block be moved up to the first `foreach ($config['transports'] as $name => $transport) {`?

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 8]
```diff
@@ -1797,15 +1797,42 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
...
+                $isFailureTransport = true;
+            }
+
             $transportDefinition = (new Definition(TransportInterface::class))
                 ->setFactory([new Reference('messenger.transport_factory'), 'createTransport'])
                 ->setArguments([$transport['dsn'], $transport['options'] + ['transport_name' => $name], new Reference($serializerId)])
-                ->addTag('messenger.receiver', ['alias' => $name])
+                ->addTag('messenger.receiver', [
+                        'alias' => $name,
+                        'failure_transport' => $isFailureTransport,
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: No `$isFailureTransport` variable needed - we can do:

`failure_transport => \in_array($name, $failureTransports)`

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 9]
```diff
@@ -1866,19 +1906,19 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
         $container->getDefinition('messenger.retry_strategy_locator')
             ->replaceArgument(0, $transportRetryReferences);
 
-        if ($config['failure_transport']) {
-            if (!isset($senderReferences[$config['failure_transport']])) {
-                throw new LogicException(sprintf('Invalid Messenger configuration: the failure transport "%s" is not a valid transport or service id.', $config['failure_transport']));
-            }
+        if (\count($failureTransports) > 0) {
+            $globalFailureReceiver = $config['failure_transport'] ?? null;
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: `$globalFailureReceiverName`

File: src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php [hunk 10]
```diff
@@ -251,9 +252,17 @@ private function guessHandledClasses(\ReflectionClass $handlerClass, string $ser
     private function registerReceivers(ContainerBuilder $container, array $busIds)
     {
         $receiverMapping = [];
+        $failureTransportsMap = [];
+
+        $globalFailureTransportId = 'messenger.failure_transports.default';
+        if ($container->hasAlias($globalFailureTransportId)) {
+            $globalFailureTransport = (string) $container->getAlias($globalFailureTransportId);
+            $failureTransportsMap[$globalFailureTransport] = new Reference('messenger.transport.'.$globalFailureTransport);
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php]: This looks odd to me. If I understand it correctly, `$globalFailureTransport` will equal `messenger.failure_transports.default`, right? Why do we want that?

I understand that we're passing the "global failure receiver/transport" name to the 1st argument of the commands. And I understand that the service locator we're creating here will need to contain a receiver with that name. So, if my global failure receiver is called "failure_main", then `failure_main` will be passed as the first argument to the commands and we *also* want this `$failureTransportsMap` to have a `failure_main` key inside it, right?

If so, I think this isn't quite right yet. It's a bit odd, but could we instead actually fetch one of the command definitions - e.g. `console.command.messenger_failed_messages_retry` and *read* the `0` argument and use *that* as the key? So if the 0 argument is set to `failure_main`, then we would read that and use `failure_main` here. Also, for the `$value, we can just use the `messenger.failure_transports.default` alias. So something like:

```php
$commandDefinition = $container->getDefinition('console.command.messenger_failed_messages_retry');
$failureTransportsMap[$commandDefinition->getArgument(0)] = new Reference('messenger.failure_transports.default');
```

File: src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php [hunk 11]
```diff
@@ -299,6 +311,10 @@ private function registerReceivers(ContainerBuilder $container, array $busIds)
 
         $container->getDefinition('messenger.receiver_locator')->replaceArgument(0, $receiverMapping);
 
+        $failureTransportsLocator = (new Definition(ServiceLocator::class))
+            ->addArgument($failureTransportsMap)
+            ->addTag('container.service_locator');
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php]: I think we can use `ServiceLocatorTagPass::register()` here again.

**Review by weaverryan — COMMENTED** [review]
Getting close...

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 7 above)
Comment (monteiro) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:1991]: Not really, because if you see I depend on `$senderReferences` which depend on `$senderAliases` being generated on that first  `foreach ($config['transports'] as $name => $transport)`, and it depends exactly on the transport id factory:

```php
$transportDefinition = (new Definition(TransportInterface::class))
                ->setFactory([new Reference('messenger.transport_factory'), 'createTransport'])
                ->setArguments([$transport['dsn'], $transport['options'] + ['transport_name' => $name], new Reference($serializerId)])
                ->addTag('messenger.receiver', [
                        'alias' => $name,
                        'failure_transport' => $isFailureTransport,
                    ]
                )
            ;
            $container->setDefinition($transportId = 'messenger.transport.'.$name, $transportDefinition);
            $senderAliases[$name] = $transportId;
```

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/console.php [hunk 12]
```diff
@@ -165,7 +165,7 @@
 
         ->set('console.command.messenger_failed_messages_retry', FailedMessagesRetryCommand::class)
             ->args([
-                abstract_arg('Receiver name'),
+                abstract_arg('Default failure receiver name'),
                 abstract_arg('Receiver'),
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/console.php]: should this now also be "Receivers"?

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 13]
```diff
@@ -1797,15 +1797,36 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
             $container->setAlias('messenger.default_serializer', $config['serializer']['default_serializer']);
         }
 
+        $failureTransports = [];
+        if ($config['failure_transport']) {
+            if (!isset($config['transports'][$config['failure_transport']])) {
+                throw new LogicException(sprintf('Invalid Messenger configuration: the failure transport "%s" is not a valid transport or service id.', $config['failure_transport']));
+            }
+
+            $container->setAlias('messenger.failure_transports.default', $config['failure_transport']);
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Wait... shouldn't the target service id here (the 2nd argument) be `'messenger.transport.'.$config['failure_transport']`?

I don't love hard-coding that `'messenger.transport.'.$transportName` id pattern in 2 places (it's main place is below)m but I think we'll need to.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 14]
```diff
@@ -1836,6 +1857,19 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
             $senderReferences[$serviceId] = new Reference($serviceId);
         }
 
+        $failureTransportsByTransportName = [];
+        foreach ($config['transports'] as $name => $transport) {
+            if ($transport['failure_transport']) {
+                if (!isset($config['transports'][$transport['failure_transport']])) {
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: I think this should be checking `$senderReferences` instead of `$config['transports']` - see the old code.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 15]
```diff
@@ -1797,15 +1797,36 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
...
+            if (!isset($config['transports'][$config['failure_transport']])) {
+                throw new LogicException(sprintf('Invalid Messenger configuration: the failure transport "%s" is not a valid transport or service id.', $config['failure_transport']));
+            }
+
+            $container->setAlias('messenger.failure_transports.default', $config['failure_transport']);
+            $failureTransports[] = $config['failure_transport'];
+        }
+        foreach ($config['transports'] as $name => $transport) {
+            if (isset($transport['failure_transport']) && !isset($config['transports'][$transport['failure_transport']])) {
+                throw new LogicException(sprintf('Invalid Messenger configuration: the failure transport "%s" is not a valid transport or service id.', $transport['failure_transport']));
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: I think we can remove this LogicException and the one above it. We already have this check down below around line 1860. And, it's not *completely* correct up here, because we really want to check `$senderReferences` and not just `$config['transports']`.

Well, actually, below, there is not a check for the "global" transport, but we could add one if we follow my comment below about creating a `$failureTransportsByName` array.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 16]
```diff
@@ -1797,15 +1797,36 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
...
+            }
+            if ($transport['failure_transport']) {
+                $failureTransports[] = $transport['failure_transport'];
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:1931]: What if we create a 2nd array right here?

```
if ($transport['failure_transport']) {
    $failureTransports[] = $transport['failure_transport'];
    $failureTransportsByName[$name] = $transport['failure_transport'];
} elseif ($config['failure_transport']) {
    // no need to add it to $failureTransports, as we will always set it above
    $failureTransportsByName[$name] = $config['failure_transport'];
}
```

The advantage is that, below, around 1860, instead of looping again over `$config['transports']`, we could loop over `$failureTransportsByName[$name]`. This would allow us to remove most of the logic from that foreach, except for the part that uses the `$senderReferences`. And the `LogicException` down there would check the validity of *all* of the failure transports, including the global one (because as long as the global transport should be used for 1 transport, it will already be in `$failureTransportsByName`.

Heck, the `foreach` around 1860 could probably just be an `array_map` :p (notice I renamed the `$failureTransportsByName` variable from around 1860 to `$failureTransportReferencesByTransportName`. Also, that logic could now possibly go down around line 1913 - it's only needed for the `ServiceLocatorTagPass::register` call.

```
$failureTransportReferencesByTransportName = array_map(function () {...}, $failureTransportsByName);
```

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 17]
```diff
@@ -1866,19 +1900,19 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
         $container->getDefinition('messenger.retry_strategy_locator')
             ->replaceArgument(0, $transportRetryReferences);
 
-        if ($config['failure_transport']) {
-            if (!isset($senderReferences[$config['failure_transport']])) {
-                throw new LogicException(sprintf('Invalid Messenger configuration: the failure transport "%s" is not a valid transport or service id.', $config['failure_transport']));
-            }
+        if (\count($failureTransports) > 0) {
+            $globalFailureReceiverName = $config['failure_transport'] ?? null;
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: I think (?) based on old code that this will always be set or `null`? So maybe the `??` isn't needed? And maybe we could just use `$config['failure_transport']` directly like before?

**Comment by escees** [comment]
How long it will take to be merged into master? @monteiro are you still working on it? :)

**Comment by monteiro** [comment]
Waiting for Ryan to help me.
He has been reviewing my PR since the beginning.

Let me talk with him, to see what can we do.

Thanks for pinging.

**Comment by escees** [comment]
Sure, I've deleted previous comment because I wasn't sure if it's appropriate place to ask :) But I appreciate for answering. For me and I see that not only for me it's really important feature that is missing from core.

**Comment by monteiro** [comment]
@escees no worries. I already talked with @weaverryan to help me during this 2021 to merge this missing feature.

**Comment by rkazaniszyn** [comment]
Fingers crossed for this to be completed and merged :)

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 18]
```diff
@@ -1797,15 +1797,38 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
...
         foreach ($config['transports'] as $name => $transport) {
             $serializerId = $transport['serializer'] ?? 'messenger.default_serializer';
-
             $transportDefinition = (new Definition(TransportInterface::class))
                 ->setFactory([new Reference('messenger.transport_factory'), 'createTransport'])
                 ->setArguments([$transport['dsn'], $transport['options'] + ['transport_name' => $name], new Reference($serializerId)])
-                ->addTag('messenger.receiver', ['alias' => $name])
+                ->addTag('messenger.receiver', [
+                        'alias' => $name,
+                        'failure_transport' => \in_array($name, $failureTransports),
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Maybe `is_failure_transport`?

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 19]
```diff
@@ -1836,6 +1859,25 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
             $senderReferences[$serviceId] = new Reference($serviceId);
         }
 
+        $failureTransportReferencesByTransportName = array_map(function($failureTransportName) use ($senderReferences) {
+            return $senderReferences[$failureTransportName];
+        }, $failureTransportsByName);
+
+
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: extra line break here

File: src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php [hunk 20]
```diff
@@ -263,6 +272,9 @@ private function registerReceivers(ContainerBuilder $container, array $busIds)
             foreach ($tags as $tag) {
                 if (isset($tag['alias'])) {
                     $receiverMapping[$tag['alias']] = $receiverMapping[$id];
+                    if (isset($tag['failure_transport']) && null !== $tag['failure_transport']) {
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php]: I suggested renaming this to `is_failure_transport`. Also, it's a boolean, so I think we can do something like:

```suggestion
                    if ($tag['failure_transport']) ?? false) {
```

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 21]
```diff
@@ -1797,15 +1797,38 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
             $container->setAlias('messenger.default_serializer', $config['serializer']['default_serializer']);
         }
 
+        $failureTransports = [];
+        if ($config['failure_transport']) {
+            if (!isset($config['transports'][$config['failure_transport']])) {
+                throw new LogicException(sprintf('Invalid Messenger configuration: the failure transport "%s" is not a valid transport or service id.', $config['failure_transport']));
+            }
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:1922]: This error looks effectively redundant with the one later that checks `$senderReferences` (and that is also where we do the valid check for the individual, non-default failure transports).

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 22]
```diff
@@ -1836,6 +1859,25 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
...
+        }
+        
+        foreach ($config['transports'] as $name => $transport) {
+            if ($transport['failure_transport']) {
+                if (!isset($senderReferences[$transport['failure_transport']])) {
+                    throw new LogicException(sprintf('Invalid Messenger configuration: the failure transport "%s" is not a valid transport or service id.', $transport['failure_transport']));
+                }
+            }
+        }
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:1986]: These last 12 lines should probably be above the `array_map` line, right? Otherwise the `array_map` could be trying to use an undefined index on `$senderReferences`?

Also... would it be possible to loop over `$failureTransports` to do the check? Instead of have the first if for the global failure transport and then the foreach right below?

Full disclosure: I could be reading the code incorrectly and am giving you bad recommendations. Please push back if you think that's the case :).

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 23]
```diff
@@ -1866,19 +1908,19 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
         $container->getDefinition('messenger.retry_strategy_locator')
             ->replaceArgument(0, $transportRetryReferences);
 
-        if ($config['failure_transport']) {
-            if (!isset($senderReferences[$config['failure_transport']])) {
-                throw new LogicException(sprintf('Invalid Messenger configuration: the failure transport "%s" is not a valid transport or service id.', $config['failure_transport']));
-            }
+        if (\count($failureTransports) > 0) {
+            $globalFailureReceiverName = $config['failure_transport'];
```
Comment (weaverryan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: We could omit this new variable to reduce the diff. Having `$config['failure_transport']` below is no big deal.

File: src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php [hunk 24]
```diff
@@ -29,20 +30,25 @@
...
+    private $failureTransports;
 
-    public function __construct(string $receiverName, ReceiverInterface $receiver)
+    public function __construct(?string $globalFailureReceiverName, $failureTransports)
     {
-        $this->receiverName = $receiverName;
-        $this->receiver = $receiver;
+        $this->failureTransports = $failureTransports;
+        $this->globalFailureReceiverName = $globalFailureReceiverName;
+        if (!$failureTransports instanceof ServiceLocator) {
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php:47]: We should probably move this up ONE line so it's right after `$this->failureTransports`.

File: src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php [hunk 25]
```diff
@@ -29,20 +30,25 @@
...
+            trigger_deprecation('symfony/messenger', '5.2', 'Passing failureTransports should now pass a ServiceLocator', __METHOD__);
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php]: 5.3 now - same as anywhere else in this PR

For the wording, check out these examples:

https://github.com/symfony/symfony/blob/7754beddfc6be3a66aa5dc561051efabd2aaee8f/src/Symfony/Component/HttpFoundation/InputBag.php#L33

File: src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php [hunk 26]
```diff
@@ -29,20 +30,25 @@
...
+
+            $this->failureTransports = new ServiceLocator([$this->globalFailureReceiverName => function () use ($failureTransports) { return $failureTransports; }]);
+        }
 
         parent::__construct();
     }
 
-    protected function getReceiverName(): string
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php:49]: This is a BC break. We need to leave the old method but trigger a deprecation in it.

File: src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php [hunk 27]
```diff
@@ -147,9 +153,9 @@ protected function printPendingMessagesMessage(ReceiverInterface $receiver, Symf
         }
     }
 
-    protected function getReceiver(): ReceiverInterface
+    protected function getReceiver(string $name): ReceiverInterface
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php]: The new argument is a BC break also :p. If the user sub-classes this, and currently has `protected function getReceiver()` with no args, suddenly their signature is wrong.

The fix is... pretty nuts :). Here is an example: https://github.com/symfony/symfony/pull/31249/files#diff-c9a47747d9fe6a39e79059518d9216e550ee0b0723802330a50438f36013c5fbL201

File: src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php [hunk 28]
```diff
@@ -25,12 +26,19 @@
...
+     */
+    private $failureSenders;
     private $logger;
 
-    public function __construct(SenderInterface $failureSender, LoggerInterface $logger = null)
+    public function __construct($failureSenders, LoggerInterface $logger = null)
     {
-        $this->failureSender = $failureSender;
+        if (!$failureSenders instanceof ServiceLocator) {
+            trigger_deprecation('symfony/messenger', '5.2', 'Passing failureSenders should now pass a ServiceLocator with all the failure transports', __METHOD__);
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php]: 5.3 and tweak the wording like I mention in the other spot :)

File: src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php [hunk 29]
```diff
@@ -40,6 +48,11 @@ public function onMessageFailed(WorkerMessageFailedEvent $event)
             return;
         }
 
+        $hasFailureTransports = $this->hasFailureTransports($event);
+        if (!$hasFailureTransports) {
+            return;
+        }
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php:58]: Is this quite right? I looks like `hasFailureTransports()` doesn't use the `$event` argument. Should we instead use the code below around like 69-70 to covers this? We could make `$this->getFailureSender` use `$this->failureSenders->has()` and return `null` if none is fond.

File: src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php [hunk 30]
```diff
@@ -39,14 +39,16 @@ class FailedMessagesRetryCommand extends AbstractFailedMessagesCommand
     private $eventDispatcher;
     private $messageBus;
     private $logger;
+    private $globalReceiverName;
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php]: Is this argument ever used?

File: src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php (hunk 27 above)
Comment (weaverryan) [reply src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php]: Hmm, I think we need some error checking here. What if a bogus `$name` is passed? We should check `if (!$this->failureTransports->has($name))` and throw an exception if it's not found (this would cover people passing us a bad `--failure-transport` option.

**Review by weaverryan — COMMENTED** [review]
Thanks for you work on this - we're getting ever close - so many little details :)

File: src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php (hunk 30 above)
Comment (monteiro) [reply src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php]: This is to not to break BC, so we know which is the global transport if it's defined, to keep previous behavior if you don't pass any arguments like before.

Comment (weaverryan) [reply src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php]: But, this property is never *used* in this class. If you look at the final source of this class, and search for `$this->globalReceiverName`, we set it in the constructor, but never reference it again. Or am I missing something?

File: src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php [hunk 31]
```diff
@@ -153,9 +167,18 @@ protected function printPendingMessagesMessage(ReceiverInterface $receiver, Symf
...
+    protected function getReceiver(/* string $name */): ReceiverInterface
     {
-        return $this->receiver;
+        if (\func_num_args() < 3 && __CLASS__ !== \get_class($this) && __CLASS__ !== (new \ReflectionMethod($this, __FUNCTION__))->getDeclaringClass()->getName() && !$this instanceof \PHPUnit\Framework\MockObject\MockObject && !$this instanceof \Prophecy\Prophecy\ProphecySubjectInterface) {
+            @trigger_error(sprintf('The "%s()" method will have a new "string $name" argument in version 5.3, not defining it is deprecated since Symfony 5.2.', __METHOD__), E_USER_DEPRECATED);
+        }
+        $name = 2 < \func_num_args() ? \func_get_arg(2) : '';
+
+        if (!$this->failureTransports->has($name)) {
+            throw new InvalidArgumentException('The failure transport with name "%s" was not found', $name);
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php]: Missing a sprintf here - so the `$name` is being passed as arg 2 to the exception

File: src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php [hunk 32]
```diff
@@ -153,9 +167,18 @@ protected function printPendingMessagesMessage(ReceiverInterface $receiver, Symf
...
     }
 
-    protected function getReceiver(): ReceiverInterface
+    protected function getReceiver(/* string $name */): ReceiverInterface
     {
-        return $this->receiver;
+        if (\func_num_args() < 3 && __CLASS__ !== \get_class($this) && __CLASS__ !== (new \ReflectionMethod($this, __FUNCTION__))->getDeclaringClass()->getName() && !$this instanceof \PHPUnit\Framework\MockObject\MockObject && !$this instanceof \Prophecy\Prophecy\ProphecySubjectInterface) {
+            @trigger_error(sprintf('The "%s()" method will have a new "string $name" argument in version 5.3, not defining it is deprecated since Symfony 5.2.', __METHOD__), E_USER_DEPRECATED);
+        }
+        $name = 2 < \func_num_args() ? \func_get_arg(2) : '';
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php]: This part isn't right yet. It should be `func_get_arg(0)` and looking for a length greater than 0. And in the if statement above, it's similar - it should be looking for the number of args to be less than 1, not 3.

Also, I *think* the default (if the argument is not passed) should be `$this-> globalFailureReceiverName` to match the "old" behavior (where we would use the first arg to the constructor as the receiver name here).

AND, there is an edge case where I think we can throw an exception:

If this method is called with NO argument AND `null` is passed to the first argument of this class's constructor, then it will mean that `$name` will be `null`. In that case, throw an exception. This logic should go up inside of the deprecation `if` statement. This would be a situation where they are calling this method using the old way (not passing an argument) but are using the new constructor (optional 1st arg). That's not allowed - they have partially upgraded their code :).

**Comment by monteiro** [comment]
@weaverryan I have done all changes, including fixing all the tests:
- Most code is from the "legacy" tests. I have added the annotation so we support both ways until the switch (moving from SenderInterface to a ServiceLocator) for the major version.
- There is a psalm error:
```
Run ./vendor/bin/psalm.phar --output-format=github --no-progress
Error: Class or interface Prophecy\Prophecy\ProphecySubjectInterface does not exist
Error: Process completed with exit code 2.
```
which I don't know how to fix, related to that weird extra parameter code in https://github.com/symfony/symfony/pull/38468/files#diff-9213ec846d94497cc34a4b922373cb52e0d53015604427a4aec0661289c58ac8R177

- Feel free to test! Now it's ready!

File: src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php [hunk 33]
```diff
@@ -153,9 +172,18 @@ protected function printPendingMessagesMessage(ReceiverInterface $receiver, Symf
...
+    protected function getReceiver(/* string $name */): ReceiverInterface
     {
-        return $this->receiver;
+        if (1 > \func_num_args() && __CLASS__ !== static::class && __CLASS__ !== (new \ReflectionMethod($this, __FUNCTION__))->getDeclaringClass()->getName() && !$this instanceof \PHPUnit\Framework\MockObject\MockObject && !$this instanceof \Prophecy\Prophecy\ProphecySubjectInterface) {
+            @trigger_error(sprintf('The "%s()" method will have a new "string $name" argument in version 5.3, not defining it is deprecated since Symfony 5.2.', __METHOD__), \E_USER_DEPRECATED);
+        }
+
+        $name = \func_num_args() > 0 ? func_get_arg(0) : $this->globalFailureReceiverName;
+        if (!$this->failureTransports->has($name)) {
+            throw new InvalidArgumentException(sprintf('The failure transport with name "%s" was not found.', $name));
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php]:
```suggestion
            throw new InvalidArgumentException(sprintf('The failure transport with name "%s" was not found. Available transports are: %s', $name, implode(', ', array_keys($this->failureTransports->getProvidedServices()))));```

File: src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php [hunk 34]
```diff
@@ -96,10 +99,15 @@ protected function execute(InputInterface $input, OutputInterface $output)
             $io->comment('Re-run the command with a -vv option to see logs about consumed messages.');
         }
 
-        $receiver = $this->getReceiver();
+        $failureTransportName = $input->getOption('failure-transport');
+        if (null === $failureTransportName) {
+            $failureTransportName = $this->getGlobalFailureReceiverName();
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php]: In this situation - where they are running the command without the `--failure-transport=` option, I think we need to advertise that there are other failure transports. So, if there ARE other failure transports, we would say (at the top of the command output):

```
> Lading messages from the <comment>global</comment> failure transport. 
> To use a different failure transport, pass`--failure-transport=`.
> Available failure transports are: foo_failure, bar_failure

There are 2 messages pending in the failure transport.
```

We would need to play around with the formatting... I was thinking maybe the `$io->comment()` functionality for the new message (the last line already exists, I was just showing where the new message would fit in).

File: src/Symfony/Component/Messenger/Command/FailedMessagesShowCommand.php [hunk 35]
```diff
@@ -122,10 +129,10 @@ private function listMessages(SymfonyStyle $io, int $max)
         $io->comment('Run <comment>messenger:failed:show {id} -vv</comment> to see message details.');
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Command/FailedMessagesShowCommand.php]: this line (and a few other ones in this command... and maybe other commands, like`:retry` and `:remove`) now needs to include `--failure-transport=` if that option was passed. Otherwise, you will be looking for the message in the wrong transport.

Btw, with Doctrine as your failure transport, forgetting the `--failure-transport=` option actually DOES work... but due to a bug I just discovered (that we should fix, in a different PR). The `find()` method in the Doctrine connection class incorrectly does NOT include the `AND queue_name = ?` part. https://github.com/symfony/symfony/blob/2da27bbd2751f51480e49f6b9132fa45e2a14f9e/src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php#L278-L281

File: src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php [hunk 36]
```diff
@@ -59,6 +61,7 @@ protected function configure(): void
             ->setDefinition([
                 new InputArgument('id', InputArgument::IS_ARRAY, 'Specific message id(s) to retry'),
                 new InputOption('force', null, InputOption::VALUE_NONE, 'Force action without confirmation'),
+                new InputOption('failure-transport', null, InputOption::VALUE_OPTIONAL, 'Use a specific failure transport'),
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php]: WDYT about just `--transport=`? `failure-transport` is more descriptive, but quite a lot to write!

File: src/Symfony/Component/Messenger/Command/FailedMessagesShowCommand.php [hunk 37]
```diff
@@ -39,6 +39,7 @@ protected function configure(): void
             ->setDefinition([
                 new InputArgument('id', InputArgument::OPTIONAL, 'Specific message id to show'),
                 new InputOption('max', null, InputOption::VALUE_REQUIRED, 'Maximum number of messages to list', 50),
+                new InputOption('failure-transport', null, InputOption::VALUE_OPTIONAL, 'Use a specific failure transport'),
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Command/FailedMessagesShowCommand.php]: You have`VALUE_OPTIONAL`. That means I can pass simply `--failure-transport=` with no value. We should make this `VALUE_REQUIRED`. Another option would be to interactively ask which transport they want if they pass no value.

**Review by weaverryan — COMMENTED** [review]
**EDIT**

The below issue is NOT  an issue. It's caused by the retry commands being allowed to query the wrong transport. Basically, the fix in #40588 closes this possibility. There is no problem here.

~I've been playing with this, and it's looking really good - it's close.~

~But I just hit one major problem. Suppose this setup"~

```yml
framework:
    messenger:
        failure_transport: failure_transport1

        transports:
            transport2:
                dsn: doctrine://default
                options:
                    queue_name: transport2
                failure_transport: failure_transport2

            failure_transport1:
                dsn: doctrine://default
                options:
                    queue_name: failure_transport1
            failure_transport2:
                dsn: doctrine://default
                options:
                    queue_name: failure_transport2

        routing:
            App\Message\ILikeToFail: transport2
```

The `ILikeToFail` fail message is routed to `transport2`. So if it fails, it is sent to `failure_transport2`. Great! Now, if I retry that message from `failure_transport2` and it fails, it is sent to `failure_transport1`. That is not correct.

It makes sense why it's doing this. `failure_transport2` is a normal transport. So when the message fails, it actually looks at its *own* "failure transport" config and determines that the message should go to the "global failure transport", which is `failure_transport1`. But I don't think this is the behavior we want: the message should go back to `failure_transport2` after failing. That is THIS message's failure transport, and it should remain here until it is successful or removed because it hits the retry limit.

tl;dr We need a way to respect the original failure transport that message was routed to. We probably need (if we don't have this already) a stamp to save the "failure transport name" onto a message, so it can be read when being re-delivered after the messages fails a retry from the failure queue.

File: src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php (hunk 24 above)
Comment (monteiro) [reply src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php:47]: but if we do that it's replaced afterwards. Better to put like this to avoid the else right? Am I missing something?

File: src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php (hunk 36 above)
Comment (monteiro) [reply src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php]: Perfect to me. It's clear the language, because in the end it's a transport.

File: src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php (hunk 34 above)
Comment (monteiro) [reply src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php]: I did for the retry and show commands. The remove, doesn't make sense because id is required.

File: src/Symfony/Component/Messenger/Command/FailedMessagesShowCommand.php (hunk 37 above)
Comment (monteiro) [reply src/Symfony/Component/Messenger/Command/FailedMessagesShowCommand.php]: is it ok for BC to make it REQUIRED?

**Comment by monteiro** [comment]
Pending to fix the console command tests after adding the list of transports and the warning.

File: src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php (hunk 32 above)
Comment (monteiro) [reply src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php]: This is fixed.

File: src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php [hunk 38]
```diff
@@ -153,9 +173,18 @@ protected function printPendingMessagesMessage(ReceiverInterface $receiver, Symf
         }
     }
 
-    protected function getReceiver(): ReceiverInterface
+    protected function getReceiver(/* string $name */): ReceiverInterface
     {
-        return $this->receiver;
+        if (1 > \func_num_args() && __CLASS__ !== static::class && __CLASS__ !== (new \ReflectionMethod($this, __FUNCTION__))->getDeclaringClass()->getName() && !$this instanceof \PHPUnit\Framework\MockObject\MockObject && !$this instanceof \Prophecy\Prophecy\ProphecySubjectInterface) {
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php:177]: UPDATE:

I see this was more common in 4.4... it just happens that there are not many instances in the code base at this moment.

-------------------------

This was taken from https://github.com/symfony/symfony/blob/0d08a2127c37fc2013c667515a9df7cd33324355/src/Symfony/Component/Routing/RouteCollection.php#L79-L81

I have no idea if this is the right way to do things - I can't find anything else like it in the code, other than the above link. It's @nicolas-grekas code originally :)

File: src/Symfony/Component/Messenger/Tests/Command/FailedMessagesRetryCommandTest.php [hunk 39]
```diff
@@ -45,4 +49,101 @@ public function testBasicRun()
...
+        );
+        $tester = new CommandTester($command);
+        $tester->setInputs([0]);
+        $tester->execute(['--force' => true]);
+
+        $expectedLadingMessage = <<<EOF
+> Loading messages from the global failure transport failure_receiver.
+> To use a different failure transport, pass --transport=.
+> Available failure transports are: failure_receiver, failure_receiver_2, failure_receiver_3
+EOF;
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Tests/Command/FailedMessagesRetryCommandTest.php:114]: I don't think we need to assert the entire, exact string. Probably the most important part is `failure transports are: failure_receiver, failure_receiver_2, failure_receiver_3`

**Review by weaverryan — APPROVED** [review]
This is ready! I've tested it on a project and it works beautifully! It just needs one more technical review. fabbot failures look false.

File: src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php [hunk 40]
```diff
@@ -25,12 +26,19 @@
  */
 class SendFailedMessageToFailureTransportListener implements EventSubscriberInterface
 {
-    private $failureSender;
+    /**
+     * @var ServiceLocator|SenderInterface
+     */
+    private $failureSenders;
```
Comment (chalasr) [inline src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php:29]: should be moved as `@param ContainerInterface $failureSenders` in the constructor docblock.

File: src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php [hunk 41]
```diff
@@ -11,6 +11,7 @@
 namespace Symfony\Component\Messenger\EventListener;
 
 use Psr\Log\LoggerInterface;
+use Symfony\Component\DependencyInjection\ServiceLocator;
```
Comment (chalasr) [inline src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php]: Should be `Psr\Container\ContainerInterface`.

File: src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php [hunk 42]
```diff
@@ -35,20 +38,37 @@
...
+        $this->failureTransports = $failureTransports;
+        if (!$failureTransports instanceof ServiceLocator) {
+            trigger_deprecation('symfony/messenger', '5.3', 'Passing a non-scalar value as 2nd argument to "%s()" is deprecated, pass a ServiceLocator instead.', __METHOD__);
+
+            if (null === $globalFailureReceiverName) {
+                throw new InvalidArgumentException(sprintf('The argument "globalFailureReceiver" from method "%s()" must be not null if 2nd argument is not a ServiceLocator.', __METHOD__));
+            }
+
+            $this->failureTransports = new ServiceLocator([$globalFailureReceiverName => function () use ($failureTransports) { return $failureTransports; },
+            ]);
```
Comment (chalasr) [inline src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php]: should be on one-line

**Review by chalasr — DISMISSED** [review]

**Review by chalasr — CHANGES_REQUESTED** [review]
Great work. Some comments above

**Comment by monteiro** [comment]
Thanks @chalasr. Already fixed with your suggestions.

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
It took time, but here we go, this is in now. Thank you very much @monteiro.

**Comment by monteiro** [comment]
Thanks @chalasr again!
