### PR TITLE
[Process] Fix Permission Denied error when writing sf_proc_00 lock files on Windows

### LINKED ISSUE #37294: [Process] Permission Denied writing to sf_proc_00.out.lock when file is generated by a different AppPoolIdentity User
**Symfony version(s) affected**: 4.4.8|5.1.2

- OS: Windows 10
- Server: IIS version 10
- PHP version 7.3
- Laravel version 6.18

Note: Bug originally encountered on Laravel 6.18 using symfony/process 4.4.8. I have replicated the issue on a fresh symfony/skeleton 5.1.2 base with the process package required through composer.

**Description**  

When two or more sites are running IIS / FastCGI as different AppPoolIdentity users with limited group permissions to the sys_temp_dir, the first to write sf_proc_00.* files used by the Process class takes ownership, however any additional sites that attempt to write to this file will receive the following error:

`A temporary file could not be opened to write the process output: fopen(C:\WINDOWS\TEMP\sf_proc_00.out.lock): failed to open stream: Permission denied`

Our permissions are configured to prevent one site from modifying temporary files that are created by another.

**How to reproduce**  

1. In IIS: Add two sites using the Symfony\Process component with different Application Pools
2. In IIS Application Pools: For both application pools used, select "Advanced Settings" and confirm the "Identity" field is set to the built-in "ApplicationPoolIdentity" account,
3. In IIS Feature Panel: For both sites, select "Authentication" > "Anonymous Authentication", ensure it is enabled and click "Edit..." then select "Application Pool Identity" and click OK.
4. Set limited permissions for the IIS_IUSRS group on the sys_temp_dir (this is C:\Windows\Temp on my machine). Verify the Users group does not exceed these permissions.
   - Permissions used in testing: List folder / read data, Read attributes, Read extended attributes, Create files / write data, Read permissions
5. For both sites, create some code that uses the Process class to run a command. (See Additional Context for the sample code I used to test)
6. In Site A, run the code using the Process class and check the sys_temp_dir to confirm sf_proc_00 files were generated.
7. In Site B, attempt to run the code using the Process class to throw the Permission Denied error.

**Possible Solution**  

Perhaps a solution could be incrementing the filename when the lock files exist, but cannot be opened for writing, and removing the sf_proc_## files used in the WindowsPipes destructor.

I have limited experience in using the Process class, I'll post the code that has fixed it in my particular instance, however I do not know if it is ideal for all use cases.

symfony\process\Pipes\WindowsPipes.php, Line 58: (Try next iteration if lock file exists)
```php
                    if (!$h = fopen($file.'.lock', 'w')) {
                        if (file_exists($file.'.lock'))
                            continue 2;

                        restore_error_handler();
                        throw new RuntimeException('A temporary file could not be opened to write the process output: '.$lastError);
                    }
```

symfony\process\Pipes\WindowsPipes.php, Line 88: (Remove files on destruct)
```php
    public function __destruct()
    {
        $this->close();

        foreach ($this->files as $file) {
            unlink($file);
            unlink($file.'.lock');
        }
    }
```

**Additional context**  

During replication, I made a simple controller that dumps output of the `dir` command for testing:

src\Controller\HomeController.php:
```php
<?php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Process\Process;

class HomeController
{
    public function index()
    {
        $process = new Process(['dir']);
        $process->run();

        if(!$process->isSuccessful())
            throw new ProcessFailedException($process);

        return new Response($process->getOutput());
    }
}
```

And attached it to the base route:

config\routes.yaml:
```yaml
index:
    path: /
    controller: App\Controller\HomeController::index
```

The same code was used on both Site A and B.

### PR DESCRIPTION
**Pull request by JasonStephensTAMU**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  |no
| Deprecations? | no
| Tickets       | Fix #37294
| License       | MIT
| Doc PR        | 

Passes current Process unit tests.

On Windows systems, a new set of sf_proc_## files are generated in the system temp directory for each WindowsPipes object. These files are removed when the WindowsPipes object is destroyed.

This avoids receiving a permission denied error when attempting to write to sf_proc_## files between multiple sites running as different users, when the users do not have permissions to modify each others files.

Changes
- [Process] WindowsPipes always creates new sf_proc_## files in constructor
- [Process] WindowsPipes removes its sf_proc_## files in destructor

### CODE REVIEW

File: src/Symfony/Component/Process/Pipes/WindowsPipes.php [hunk 1]
```diff
@@ -88,6 +91,16 @@ public function __construct($input, $haveReadSupport)
     public function __destruct()
     {
         $this->close();
+
+        foreach ($this->files as $file) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Process/Pipes/WindowsPipes.php:95]: this should be removed: unlinking creates race conditions
there's no way to cleanup these

File: src/Symfony/Component/Process/Pipes/WindowsPipes.php [hunk 2]
```diff
@@ -55,6 +55,9 @@ public function __construct($input, $haveReadSupport)
                 foreach ($pipes as $pipe => $name) {
                     $file = sprintf('%s\\sf_proc_%02X.%s', $tmpDir, $i, $name);
 
+                    if (file_exists($file.'.lock')) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Process/Pipes/WindowsPipes.php:58]: Since we cannot remove these files (see comment on the descriptor), this will lead to a huge amount of .lock files.
Instead, we should figure out how to `continue 2` when the fopen fails for access error reasons. An idea: if fopen fails, try to unlink. Then if unlink fails, `continue 2`.

File: src/Symfony/Component/Process/Pipes/WindowsPipes.php (hunk 1 above)
Comment (JasonStephensTAMU) [reply src/Symfony/Component/Process/Pipes/WindowsPipes.php:95]: I see, is there a simple scenario I can produce a race condition to test against? I'd like to attempt to cover a race condition if it exists, in addition to exploring your suggestion in the constructor comment.

I appreciate your input, thanks!

Comment (nicolas-grekas) [reply src/Symfony/Component/Process/Pipes/WindowsPipes.php:95]: mm dunno sorry, race conditions are the worst to test :)

Comment (JasonStephensTAMU) [reply src/Symfony/Component/Process/Pipes/WindowsPipes.php:95]: Absolutely! Allow me to revise my question: how does unlinking create a race condition?

WindowsPipes A will exclusively use and unlink sf_proc_00 files on destruct, while a concurrent WindowsPipes B instance will operate using sf_proc_01 files, C with sf_proc_02 files and so forth, a race condition between WindowsPipes seems improbable. 

I must be overlooking something, I'd like to know more about the race condition you are seeing to help develop a satisfactory fix for this issue and avoid creating similar race conditions in the future, thanks!

Comment (nicolas-grekas) [reply src/Symfony/Component/Process/Pipes/WindowsPipes.php:95]: e.g. unlink below can succeed between the fopen and flock of another process
or unlink can fail if the file is locked by a concurrent process.
All logic involving two functions (file_exists+unlink) can fail if anything happens between the calls.
We need to carefully review each of them to be sure this cannot lead to bad side effects (either failures or filling the directory with an ever growing number of files).

Did you consider my suggestion above?

**Review by nicolas-grekas — APPROVED** [review]
(I updated the implem)

**Comment by nicolas-grekas** [comment]
Thank you @JasonStephensTAMU.

**Comment by JasonStephensTAMU** [comment]
@nicolas-grekas Thanks, and I apologize for the lack of communication over the weekend, It was Independence day weekend in the states.

To answer your question in the review: I began working on some code that implemented your suggestion, I hadn't yet settled on the actions to take if/when unlinking the lock file succeeds.

With the current changes, does the test `ProcessTest::testGetExitCodeIsNullOnWhenStartingAgain` fail?

I attempted the same change, and after seeing the failed test I worked towards the changes that were initially submitted in the PR, though it may just be my machine.

**Comment by nicolas-grekas** [comment]
@JasonStephensTAMU no worries. Not sure what you about `testGetExitCodeIsNullOnWhenStartingAgain`: tests are green on appveyor. Dunno what to tell you next :)

**Comment by JasonStephensTAMU** [comment]
@nicolas-grekas Ah, must be just on my machine. All good, carry on!
