### PR TITLE
[Cache] improve perf of pruning for fs-based adapters

### LINKED ISSUE #32701: [Cache] Purging takes forever with new FilesystemTagAwareAdapter
**Symfony version(s) affected**: 4.3.*

**Description**  

With the new optimized `FilesystemTagAwareAdapter` tags are now stored as symlinks.
See https://github.com/symfony/symfony/pull/30370.

Now when you have a considerable number of cache entries or especially tags, `$cache->prune()` will take forever because there's no special `prune()` implementation in that new adapter. It just uses the `prune()` of the `FilesystemTrait` which loops over all the files and is doing an `fopen()` (https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Cache/Traits/FilesystemTrait.php#L31).

So imagine you have 10 000 cache entries and 100 000 tags, that's going to take quite a while.
I'm not even sure if tags can expire? So maybe we should implement `prune()` in such a way that it excludes the `tags` folder?

**How to reproduce**  

1. `mkdir test && cd test`
2. `composer require symfony/cache symfony/filesystem`
3. `mkdir cache`
4. Add the following `test.php` and run it using `php test.php`:

```php
<?php

use Symfony\Component\Cache\Adapter\FilesystemTagAwareAdapter;
use Symfony\Contracts\Cache\ItemInterface;

require_once 'vendor/autoload.php';

$cache = new FilesystemTagAwareAdapter('', 0, __DIR__ . '/cache');

for ($i = 0;$i < 10000; $i++) {
    $value = $cache->get(bin2hex(random_bytes(4)), function (ItemInterface $item) {
        $item->expiresAfter(3600);

        for ($j = 0;$j < 10; $j++) {
            $item->tag(bin2hex(random_bytes(4)));
        }

        return 'foobar';
    });
}

echo 'Generated entries and tags. Now pruning...' . "\n";

$cache->prune(); // now you should be feeling how long it takes
```

**Possible Solution**  

Maybe just exclude the `tags` folder from pruning. But if we can, we should also clean up tags that do not point to any valid cache entry anymore so we don't have any orphan tag symlinks.

Gonna cc @andrerom here because he implemented the new optimized adapter which is otherwise working perfectly so thanks again! 😄

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #32701
| License       | MIT
| Doc PR        | -

Thank you [Blackfire.io](https://blackfire.io)

https://blackfire.io/profiles/compare/8044c3cf-1541-4a24-9804-5670c63fcb4c/graph

image

image

### CODE REVIEW

**Review by stof — APPROVED** [review]

File: src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php [hunk 1]
```diff
@@ -123,6 +123,33 @@ private function getFileKey(string $file): string
         return '';
     }
 
+    private function scanHashDir(string $directory): \Generator
+    {
+        if (!file_exists($directory)) {
+            return;
+        }
+
+        $chars = '+-ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
```
Comment (javiereguiluz) [inline src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php]: I guess you'll disagree 😝  but I'd define a `$charsLength = 38;` variable (or, ideally, `$charsLength = \strlen($chars);`) to avoid repeating this "magic number" in the code. Thanks.

Comment (nicolas-grekas) [reply src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php]: you've been right :) this is purely internal, adding an indirection for the very next line is not worth it.

**Comment by Toflar** [comment]
Thank you @nicolas-grekas!! <3
