### PR TITLE
[VarDumper] Use unique identifier for `RequestContextProvider`

### LINKED ISSUE #61130: [VarDumper] `spl_object_hash($request)` is identical leading to hidden information for sections
### Symfony version(s) affected

7.3.x

### Description

**Problem**

I'm trying to use the `server:dump` command to debug some endpoints. While I initially used the CLI, it lacks the ability to open nested objects and inspect them more easily. So using the following command, I dumped it to HTML.

```shell
bin/console server:dump --format=html > /app/dump.html

Symfony Var Dumper Server
=========================


 [OK] Server listening on tcp://127.0.0.1:9912


 // Quit the server with CONTROL-C.
```

> [!IMPORTANT]  
> This above command is run inside a PHP-FPM 8.4.10 docker container (with Apache web server and Traefik reverse proxy; no caching on Apache, Traefik or Symfony kernel).

The outputted HTML shows the following.

Image

While the request are made to different controllers (and different URLs) at different times, it only shows the first section URL, controller and datetime.

**Debug**

While debugging, I found this is due the `data-dedup-id` attribute in the generated HTML, which gets hidden with javascript by the `htmlDescriptor.js` when it was already present, therefore hiding the `<header>` with class `hidden` on it. (so it's not visible in the screenshot above but the information is present in the HTML, it's just hidden).

The problem is that the `data-dedup-id` is the same. When inspecting the `HtmlDescriptor` (and `CliDescriptor`), it shows using `$request['identifier']`, that it retrieves from the `RequestContextProvider`. The `identifier` is set to `spl_object_hash($request)`, which apparently is the same regardless of the new requests.

### How to reproduce

`config/packages/debug.yaml`
```yaml
when@dev:
  debug:
    # Forwards VarDumper Data clones to a centralized server allowing to inspect dumps on CLI or in your browser.
    # See the "server:dump" command to start a new server.
    dump_destination: "tcp://%env(VAR_DUMPER_SERVER)%"
```

<details><summary><code>cli</code></summary>

The CLI also misses the URL information for new/different requests (most likeley also due to same `identifier`).

```text
Symfony Var Dumper Server
=========================


 [OK] Server listening on tcp://127.0.0.1:9912


 // Quit the server with CONTROL-C.


GET https://example.local/search
--------------------------------------

 ------------ ------------------------------------------------
  date         Tue, 15 Jul 2025 21:49:34 +0200
  controller   "App\Controller\SearchController::index"
  source       SearchController.php on line 31
  file         src/Controller/SearchController.php
 ------------ ------------------------------------------------

"hello"

 ------------ -----------------------------------------
  date         Tue, 15 Jul 2025 21:49:38 +0200
  controller   "App\Controller\IndexController::index"
  source       IndexController.php on line 27
  file         src/Controller/IndexController.php
 ------------ -----------------------------------------

"world"

 ------------ ------------------------------------------------
  date         Tue, 15 Jul 2025 21:49:40 +0200
  controller   "App\Controller\SearchController::index"
  source       SearchController.php on line 31
  file         src/Controller/SearchController.php
 ------------ ------------------------------------------------

"hello"

 ------------ -----------------------------------------
  date         Tue, 15 Jul 2025 21:49:41 +0200
  controller   "App\Controller\IndexController::index"
  source       IndexController.php on line 27
  file         src/Controller/IndexController.php
 ------------ -----------------------------------------

"world"

 ------------ ------------------------------------------------
  date         Tue, 15 Jul 2025 21:49:43 +0200
  controller   "App\Controller\SearchController::index"
  source       SearchController.php on line 31
  file         src/Controller/SearchController.php
 ------------ ------------------------------------------------

"hello"
```

</details> 

<details><summary><code>dump.html</code></summary>

[scratch_405.txt](https://github.com/user-attachments/files/21242842/scratch_405.txt)

</details> 

### Possible Solution

Maybe hash/md5 combining e.g. uri, method, query and request parameters, instead of `spl_object_hash`?

### Additional Context

I initially thought this might be a feature  request, but after looking at blog post ["VarDumper server"](https://symfony.com/blog/new-in-symfony-4-1-vardumper-server), it shows a screenshot where it dumps with the expected behavior as it was in `4.1`.

### PR DESCRIPTION
**Pull request by ToshY**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #61130  
| License       | MIT

Creates unique identifier for vardumper when running `bin/console server:dump` / `bin/console server:dump --format=html`. The fix in the `RequestContextProvider` now uses `hash('crc32b')` in combination with `$_SERVER['REQUEST_TIME_FLOAT']`, which is the same as the `CliContextProvider`.

### CODE REVIEW

**Comment by ToshY** [comment]
> Hey!
> 
> Thanks for your PR. You are targeting branch "7.4" but it seems your PR description refers to branch "6.4". Could you update the PR description or change target branch? This helps core maintainers a lot.
> 
> Cheers!
> 
> Carsonbot

Accidently clicked to fast on create PR. As it's a bug, based and targeted on `6.4`, so label should be `6.4`.

File: src/Symfony/Component/VarDumper/Dumper/ContextProvider/RequestContextProvider.php [hunk 1]
```diff
@@ -45,7 +45,7 @@ public function getContext(): ?array
             'uri' => $request->getUri(),
             'method' => $request->getMethod(),
             'controller' => $controller ? $this->cloner->cloneVar($controller) : $controller,
-            'identifier' => spl_object_hash($request),
+            'identifier' => hash('crc32b',  spl_object_hash($request).$_SERVER['REQUEST_TIME_FLOAT']),
```
Comment (Spomky) [inline src/Symfony/Component/VarDumper/Dumper/ContextProvider/RequestContextProvider.php]: @nicolas-grekas  `xxh128` is already used elsewhere in Symfony for its excellent performance, low collision risk, and suitability for non-cryptographic identifiers.
Should we switch to `xxh128` here and in `CliContextProvider` as well?

Comment (nicolas-grekas) [reply src/Symfony/Component/VarDumper/Dumper/ContextProvider/RequestContextProvider.php]: that'd make sense to me. Also we could use spl_object_id

Comment (nicolas-grekas) [inline src/Symfony/Component/VarDumper/Dumper/ContextProvider/RequestContextProvider.php]:
```suggestion
            'identifier' => hash('xxh128',  spl_object_id($request).'@'.$_SERVER['REQUEST_TIME_FLOAT']),
```

**Comment by nicolas-grekas** [comment]
Thank you @ToshY.
