### PR TITLE
[Console] Fix Windows code page support

### LINKED ISSUE #35842: German Umlauts in Console
**Symfony version(s) affected**: 5.0.4

**Description**  
German Umlauts ignored in Console Question Helper

**How to reproduce**  

```
protected function execute(InputInterface $objInput, OutputInterface $objOutput)
{
	$objHelper = $this->getHelper('question');

	$objQuestion = new Question('Title: ');

	$strTitle = $objHelper->ask($objInput, $objOutput, $objQuestion);

	$objOutput->writeln($strTitle);

        return 0;
}
```

If i type "aaaöäübbb" in console i just get "aaa\\\bbb" as outout. If i just type umlauts like "öäü" the output is empty.

### LINKED ISSUE #36324: [Console] Special characters on asking question
**Symfony version(s) affected**: 5.0.7

**Description**  
In a command, when the user answers a question with special characters with accents (é, è, à, ...); the output doesn't consider these characters and removes them from the string.

**How to reproduce**  
1. Create a command
2. In the `execute` method, write the code below:
```php
$io = new SymfonyStyle($input, $output);
$userInput = $io->ask('Type here');
$io->writeln($userInput);
return 0;
```
3. Execute the command and type such as `Bonjour à tous !`
4. The output should be `Bonjour \ tous !`
> I've reproduced the project in a [repository](https://github.com/YaFou/symfony-bug-console).

**Possible Solution**  
It's possibly the encoding of my terminal or in the source code.

**Additional context**  
I use the Windows Terminal Preview with Git Bash. And I've tested on the Windows terminal.
image

### LINKED ISSUE #37278: [Console] - Special characters encoding issues
**Symfony version**
Symfony Console 5.0 (only this bundle). 

**Description**
I'm only using Symfony Console to generate PHP code and I have to ask informations to the user. When I run my script, I must use special characters to display a question, and it is displayed nicely. But when I submit informations with special characters, all of them are replaced by blank spaces.

**Example**
``` bash
Please write the value for the field "Libellé" : # The character rendering is fine there
> My favourite libellé # User input
The following libellé has been defined : My favourite libell  # Only the answer has been "sanitized"
```

**Possible solutions**
I tried to add `setTrimmable(false)` to the Question object, but it didn't help. I also tried to create a `validate` function, to see if I could get the input in it raw form, but the input is still sanitized. I also tried to save the input in a variable and convert it to UTF-8 but it couldn't change something about it. I tried the PHP functions `iconv` and `mb_convert_encoding` and none of them could solve the issue.

Do you guys have an idea about the issue origin and if there is a way to fix it ?

### LINKED ISSUE #37495: QuestionHelper input breaks UTF-8 characters
**Symfony version(s) affected**: 5.1.0

**Description**  
When an UTF-8 character is confirmed in a console as a response to QuestionHelper's question, it gets replaced by `'\'` or `''`.
E.g. `'Čeština'` > `'e\tina'`. My OS is Windows 10.

**How to reproduce**  
```
// inside Command::execute

$response = $questionHelper->ask($input, $output,
    new Question("Write something containing UTF-8 characters")
);
// response contains UTF-8 characters replaced by '\' or removed
```

### PR DESCRIPTION
**Pull request by orkan**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37385, Fix #35842, Fix #36324, Fix #37495, Fix #37278
| License       | MIT

Corrects previous fixes that dealt with the mojibake problem on Windows where an OEM code page was applied to an input string and then messed with PHP.internal_encoding setting used by the script. This caused strings with different encodings to be displayed on the console output.

### CODE REVIEW

**Comment by chalasr** [comment]
Thanks for the PR. 
This should target the 4.4 branch as the logic is the same there. Can you rebase and change the PR base branch accordingly?

**Comment by orkan** [comment]
Well, at first I was thinking the same as the PR guide says all bug fixes should adress 4.4 branch, but here I'm fixing a method that was introduced later in 352aed3

**Comment by chalasr** [comment]
Ok got it, yet this patch changes somethig that exists on 4.4:
https://github.com/symfony/symfony/blob/beca6894129ebf34165a10a08adcede3d8e5e750/src/Symfony/Component/Console/Helper/QuestionHelper.php#L111-L114.
So I guess we need an equivalent PR for 4.4. It'd be great if you could submit one. Otherwise, no worries, someone else will do (maybe me).

Also, can you fix the CS issues reported by fabbot (see failing CI builds)?

**Comment by orkan** [comment]
I think this is beyond my knowledge of git, but applying this fix against 4.4 will result in conflicts with 352aed3 changes... An equivalent would be to not change anything ;)

Btw, I fixed CS issues but why fabbot wants me to remove these lines?
```
      *
      * @param int    $cp Code page in IBM/EBCDIC format
      * @param string $in User input
-     *
-     * @return string
      */
     private function resetIOCodepage(int $cp, string $in): string
     {
```

**Comment by Nyholm** [comment]
If Fabbot suggest to do CS fix on a unrelated line, you should just ignore it.

**Comment by orkan** [comment]
It's actually related but where's the problem? Should I add description to the returned string?

File: src/Symfony/Component/Console/Helper/QuestionHelper.php [hunk 1]
```diff
@@ -523,16 +522,55 @@ private function readInput($inputStream, Question $question)
...
+    }
+
+    /**
+     * Set console I/O to the specified code page.
+     * Also make string conversion.
+     *
+     * @param int    $cp Code page in IBM/EBCDIC format
+     * @param string $in User input
+     *
+     * @return string
```
Comment (Nyholm) [inline src/Symfony/Component/Console/Helper/QuestionHelper.php]: You dont need these two lines.
One will understand the return type form the signature.

**Comment by chalasr** [comment]
Symfony omits some annotations (`@return`, `@param`) when they don't provide more value that type declarations already provide. 
Here `@return string` states something already known thanks to the `string` return type, so the patch can be applied :)

**Comment by orkan** [comment]
OK. Got it! Thanks

**Comment by nicolas-grekas** [comment]
Thank you @orkan.

**Comment by nicolas-grekas** [comment]
PR for 4.4 welcome btw!

**Comment by Nyholm** [comment]
Great work @orkan. Thank you and congratulations to your first contribution. 

As Nicolas says, could you do a similar PR to the 4.4 branch? Robin [said](https://github.com/symfony/symfony/pull/41113#issuecomment-833549300) the bug exists there to but the logic has been moved around.

**Comment by orkan** [comment]
Hi @Nyholm.
Can you describe me please, what's the workflow here? I can see from the git history, that 4.4 is regulary merged into 5.2, right? So, if I remove something in 5.2 that existed in 4.4 and later introduce it again as a PR for 4.4, doesn't it mean it'll show up in 5.2 too?
That's the thing here. I don't want my fix for 4.4 to show up in 5.2... They'll be incompatible!

**Comment by Nyholm** [comment]
Of course. 

Normally, bug fixes are merged in 4.4 (or the lowest branch they exists in). Every few days we merge 4.4 -> 5.2 -> 5.x. 

> later introduce it again as a PR for 4.4

I dont understand. We should create a PR to 4.4 to add `setIOCodepage` and `resetIOCodepage`, right?

> They'll be incompatible!

Could you elaborate how they are incompatible? I dont really understand.

**Comment by orkan** [comment]
Ok. Nevermind. I pushed fix #41210 for 4.4. "I am going to sit back now and..." see what will be the result code after 4.4 > 5.2

**Comment by nicolas-grekas** [comment]
Resolving merge conflicts is our maintainer's duty. This one was easy ;)
