### PR TITLE
[Serializer] Handle default context in Serializer

### LINKED ISSUE #58628: [Serializer] Setting COLLECT_DENORMALIZATION_ERRORS in default_context of framework config has no effect
### Symfony version(s) affected

7.1.*

### Description

Adding `COLLECT_DENORMALIZATION_ERRORS` to the `framework.default_context` has no effect if you want to collect denormalization errors for all `->denormalize` calls. It only works, if it is added to each `->denormalize` call as an extra argument.

### How to reproduce

Framework Config
```
# config/packages/framework.yaml
framework:
    # ...
    serializer:
        default_context:
            !php/const Symfony\Component\Serializer\Normalizer\DenormalizerInterface::COLLECT_DENORMALIZATION_ERRORS: true
```
Object
```
final readonly class Foo
{
    public function __construct(
        public string $bar,
    ) {}
}
```
Denormalize call:
```
public function __construct(
        private DenormalizerInterface $denormalizer,
    ) {
    }

    public function __invoke(): void
    {
        $this->denormalizer->denormalize(
            data: [],
            type: Foo::class,
        );
    }
```

Expected: `\Symfony\Component\Serializer\Exception\PartialDenormalizationException` is thrown
Actual: `\Symfony\Component\Serializer\Exception\MissingConstructorArgumentsException` is thrown

### Possible Solution

If this is intended behaviour, I would suggest to add this to the documentation [here](https://symfony.com/doc/current/components/serializer.html#collecting-type-errors-while-denormalizing), that it cannot be set as a default.  

If this is not an intended behaviour, maybe there is a way to get the context of the used `$normalizer` at this [line](https://github.com/symfony/serializer/blob/7.1/Serializer.php#L214) in the Serializer Class and use it as another check if it is not set in `$context`.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Valmonzo**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  |  no
| Deprecations? | no
| Issues        | Fix #58628
| License       | MIT

This fixes the default context not taken into account by the Serializer class.

### CODE REVIEW

**Review by chalasr — DISMISSED** [review]

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.php [hunk 1]
```diff
@@ -60,7 +60,7 @@
 
     $container->services()
         ->set('serializer', Serializer::class)
-            ->args([[], []])
+            ->args([[], [], []])
```
Comment (mtarld) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.php:63]: You can revert that change

File: src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php [hunk 2]
```diff
@@ -54,7 +54,7 @@ public function process(ContainerBuilder $container)
                 $definition = $container->getDefinition($service);
                 $definition->setBindings(['array $defaultContext' => new BoundArgument($defaultContext, false)] + $definition->getBindings());
             }
-
+            $container->getDefinition('serializer')->replaceArgument(2, $defaultContext);
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php]:
```suggestion
            $container->getDefinition('serializer')->setArgument(2, $defaultContext);
```

**Review by mtarld — CHANGES_REQUESTED** [review]

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.php (hunk 1 above)
Comment (Valmonzo) [reply src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.php:63]:
```suggestion
            ->args([[], []])
```

File: src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php [hunk 3]
```diff
@@ -77,17 +77,20 @@ public function testServicesAreOrderedAccordingToPriority()
 
     public function testBindSerializerDefaultContext()
     {
+        $context = ['enable_max_depth' => true];
+
         $container = new ContainerBuilder();
         $container->setParameter('kernel.debug', false);
-        $container->register('serializer')->setArguments([null, null]);
-        $container->setParameter('serializer.default_context', ['enable_max_depth' => true]);
+        $container->register('serializer')->setArguments([null, null, null]);
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php]:
```suggestion
        $container->register('serializer')->setArguments([null, null]);
```
 To stick with the initial service definition

Comment (Valmonzo) [reply src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php]: I just saw that, thanks 👍🏽

**Review by mtarld — APPROVED** [review]

File: src/Symfony/Component/Serializer/Serializer.php [hunk 4]
```diff
@@ -84,10 +84,12 @@ class Serializer implements SerializerInterface, ContextAwareNormalizerInterface
     /**
      * @param array<NormalizerInterface|DenormalizerInterface> $normalizers
      * @param array<EncoderInterface|DecoderInterface>         $encoders
+     * @param array<string, mixed>                             $defaultContext
      */
     public function __construct(
         private array $normalizers = [],
         array $encoders = [],
+        private array $defaultContext = [],
```
Comment (chalasr) [inline src/Symfony/Component/Serializer/Serializer.php:92]: Adding a new optional parameter to the constructor is expanding the public API. This can only happen as part of a new minor version as per semver. This should target 7.3 I think, even though it means not fixing this bug on lower branches.

Comment (chalasr) [reply src/Symfony/Component/Serializer/Serializer.php:92]: And then we need an entry in the Serializer's CHANGELOG

Comment (mtarld) [reply src/Symfony/Component/Serializer/Serializer.php:92]: And then you can update back the changes on `serializer.php` so that the service definition handles the default context.

**Comment by Valmonzo** [comment]
Thanks @chalasr and @mtarld for your help 👍🏽

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php [hunk 5]
```diff
@@ -58,6 +58,7 @@ public function process(ContainerBuilder $container): void
             $defaultContext = $container->getParameter('serializer.default_context');
             $this->bindDefaultContext($container, array_merge($normalizers, $encoders), $defaultContext);
             $container->getParameterBag()->remove('serializer.default_context');
+            $container->getDefinition('serializer')->setArgument(2, $defaultContext);
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php]: I would have set
```suggestion
            $container->getDefinition('serializer')->replaceArgument(2, $defaultContext);
```
 And updated the definition in `serializer.php`

File: src/Symfony/Component/Serializer/Serializer.php [hunk 6]
```diff
@@ -149,17 +151,16 @@ public function normalize(mixed $data, ?string $format = null, array $context =
         if ($normalizer = $this->getNormalizer($data, $format, $context)) {
             return $normalizer->normalize($data, $format, $context);
         }
-
```
Comment (dunglas) [inline src/Symfony/Component/Serializer/Serializer.php]: Unrelated CS change to be reverted.

File: src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php [hunk 7]
```diff
@@ -83,17 +83,20 @@ public function testServicesAreOrderedAccordingToPriority()
 
     public function testBindSerializerDefaultContext()
     {
+        $context = ['enable_max_depth' => true];
+
         $container = new ContainerBuilder();
         $container->setParameter('kernel.debug', false);
-        $container->register('serializer')->setArguments([null, null]);
```
Comment (dunglas) [inline src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php:82]: These changes shouldn't be necessary.

**Review by dunglas — CHANGES_REQUESTED** [review]
LGTM! I just left some minor CS-related comments.

File: src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php (hunk 7 above)
Comment (mtarld) [reply src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php:82]: Because of `replaceArgument`, I think that having 3 arguments is necessary here.

File: src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php [hunk 8]
```diff
@@ -83,17 +83,20 @@ public function testServicesAreOrderedAccordingToPriority()
...
+        $container->register('serializer')->setArguments([null, null, []]);
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php:84]:
```suggestion
        $container->register('serializer')->setArguments([null, null, null]);
```

File: src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php [hunk 9]
```diff
@@ -467,7 +470,7 @@ public function testNamedSerializersCreateNewServices(
             'api' => $namedSerializerConfig,
         ]);
 
-        $container->register('serializer')->setArguments([null, null]);
+        $container->register('serializer')->setArguments([null, null, []]);
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php]:
```suggestion
        $container->register('serializer')->setArguments([null, null, null]);
```

File: src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php [hunk 10]
```diff
@@ -553,7 +556,7 @@ public function testBindSerializerDefaultContextToNamedSerializers()
             'api' => ['default_context' => $defaultContext = ['enable_max_depth' => true]],
         ]);
 
-        $container->register('serializer')->setArguments([null, null]);
+        $container->register('serializer')->setArguments([null, null, []]);
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php]:
```suggestion
        $container->register('serializer')->setArguments([null, null, null]);
```

**Review by mtarld — APPROVED** [review]

**Comment by mtarld** [comment]
Handling that as a feature won't fix the bug for the older branches.

Maybe we can create a new PR aiming to fix the bug that:
- Add an internal setter on the `Serializer` class to set the default context
- Call that setter from the `SerializerPass`

File: src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php [hunk 11]
```diff
@@ -58,6 +58,7 @@ public function process(ContainerBuilder $container): void
             $defaultContext = $container->getParameter('serializer.default_context');
             $this->bindDefaultContext($container, array_merge($normalizers, $encoders), $defaultContext);
             $container->getParameterBag()->remove('serializer.default_context');
+            $container->getDefinition('serializer')->replaceArgument(2, $defaultContext);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php]: instead of a positional argument, let's use a named one:
```suggestion
            $container->getDefinition('serializer')->setArgument('$defaultContext', $defaultContext);
```

this will make the container fail at compile-time in case the `serrializer` service is overriden. Better than a runtime error.

**Comment by chalasr** [comment]
rebase+retarget on 6.4 needed also

File: src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php (hunk 8 above)
Comment (chalasr) [reply src/Symfony/Component/Serializer/Tests/DependencyInjection/SerializerPassTest.php:84]: as the parameter actually expects an array, this is correct. What's wrong is to pass `null` to both previous arguments which expect arrays as well. We may want to fix this or not, I wouldn't care much tbh

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @Valmonzo.
