### PR TITLE
[Validator] [Choice] Fix callback option if not array returned

### LINKED ISSUE #58610: [Validator] Fix choice callback option if not array or iterable returned
### Symfony version(s) affected

5.4.x

### Description

When using the Choice validator `callback` option : If the method provided in the callback does not return an array or iterable, it causes the following PHP error:
```
TypeError: in_array(): Argument #2 ($haystack) must be of type array
```

### How to reproduce

```php
<?php

use Symfony\Component\Validator\Constraints\Choice;
use Symfony\Component\Validator\Validation;

class Entity
{
    public function callbackMethod()
    {
        return null;
    }
}

$validator = Validation::createValidator();
$entity = new Entity();
$violations = $validator->validate($entity, [
    new Choice(['callback' => [$entity, 'callbackMethod']]),
]);
// should throw a TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given
```

### Possible Solution

Ideally, the Choice Validator should handle such cases more gracefully ? With an exception ?

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by symfonyaml**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58610
| License       | MIT

### Issue
When using the Choice validator `callback` option, and the callback method provided does not return an array or iterable, it causes a PHP error.
See all details and how to reproduce it in the issue https://github.com/symfony/symfony/issues/58610

### Solution
In this PR
 - Add some checks if the callback method provided returns an array or iterable
 - Add tests for exception and iterable

________________
**NOTE** : This PR replaces [the old one](https://github.com/symfony/symfony/pull/58611) _(I messed up with the branch rebase)_

### CODE REVIEW

File: src/Symfony/Component/Validator/Constraints/ChoiceValidator.php [hunk 1]
```diff
@@ -55,6 +55,12 @@ public function validate($value, Constraint $constraint)
                 throw new ConstraintDefinitionException('The Choice constraint expects a valid callback.');
             }
             $choices = $choices();
+            if ($choices instanceof \Traversable) {
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/Constraints/ChoiceValidator.php]: What is the reason for this? What about using `is_iterable()` below (instead of `is_array()`) instead?

Comment (symfonyaml) [reply src/Symfony/Component/Validator/Constraints/ChoiceValidator.php]: The reason for this is to handle iterables like collections, yields etc...  in callbacks ([see specific test](https://github.com/symfony/symfony/pull/58615/files#diff-545064a584d44be8aef15f493fc5d8fed17cb1552bffeb19458140d0a6207cb1R42))

That's right I can use `is_iterable()` though.

Comment (symfonyaml) [reply src/Symfony/Component/Validator/Constraints/ChoiceValidator.php]: @xabbuh [done](https://github.com/symfony/symfony/pull/58615/commits/e4fba8e42ff91de831bb7c4429abcdbd15953a08#diff-d5a06a06b90acea359eabcd7589da0a955d0852c5b26b7417eb2a95aaa55ec65R59)

File: src/Symfony/Component/Validator/Constraints/ChoiceValidator.php [hunk 2]
```diff
@@ -55,6 +55,12 @@ public function validate($value, Constraint $constraint)
                 throw new ConstraintDefinitionException('The Choice constraint expects a valid callback.');
             }
             $choices = $choices();
+            if (!is_array($choices)) {
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/Constraints/ChoiceValidator.php:58]: I checked what we document for the `callback` option and we indeed do not document anything else than returning an array. We should therefore drop the `iterator_to_array()` part as adding that would be a new feature. 

The aded code can then be simplified like this:

```php
if (!is_array($choices)) {
    throw new ConstraintDefinitionException(sprintf('The Choice constraint callback "%s" is expected to return an array, but returned "%s".', trim($this->formatValue($constraint->callback), '"'), get_debug_type($choices)));
}
```

Comment (symfonyaml) [reply src/Symfony/Component/Validator/Constraints/ChoiceValidator.php:58]: ok makes sense, I removed the `iterator_to_array()` part and the test associated.

**Review by xabbuh — APPROVED** [review]

File: src/Symfony/Component/Validator/Constraints/ChoiceValidator.php (hunk 2 above)
Comment (ro0NL) [reply src/Symfony/Component/Validator/Constraints/ChoiceValidator.php:58]: what is documented exactly?

https://github.com/symfony/symfony/blob/e59f035c0a389a83f6ac7fe3325a0e5cb6c18071/src/Symfony/Component/Validator/Constraints/Choice.php#L54

Comment (ro0NL) [reply src/Symfony/Component/Validator/Constraints/ChoiceValidator.php:58]: oh the in_array check would fail for iterables

**Comment by nicolas-grekas** [comment]
Thank you @symfonyaml.
