### PR TITLE
[HttpClient] CachingHttpClient must run after UriTemplate and Scoping

### LINKED ISSUE #62590: [HttpClient] Invalid URL with scoped client defined with base_uri and caching
### Symfony version(s) affected

7.4.0

### Description

When defining a scoped client with a `base_uri` and `caching`, an `InvalidArgumentException` exception is thrown when making a request.

```
Invalid URL: scheme is missing in "/posts". Did you forget to add "http(s)://"?
```

Without caching, the request is perform as normal.

### How to reproduce

[Reproducer](https://github.com/ker0x/symfony-reproducer/tree/bug/issue-62590)

```yaml
framework:
  http_client:
    scoped_clients:
      example.client:
        base_uri: 'https://jsonplaceholder.typicode.com'
        headers:
          Accept: 'application/json'
        caching:
          cache_pool: example_cache_pool

    cache:
        pools:
            example_cache_pool:
              default_lifetime: 3600
              tags: true
```

```php
$response = $exampleClient->request('GET', '/posts');

echo $response->getContent();
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Lctrs**
| Q             | A
| ------------- | ---
| Branch?       |7.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #62590 
| License       | MIT

CachingHttpClient needs the final resolved URL (base_uri from ScopingHttpClient + expanded URI templates) to compute correct cache keys.

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -2871,9 +2871,9 @@ private function registerHttpClientConfiguration(array $config, ContainerBuilder
...
             // This "transport" service is decorated in the following order:
             // 1. ThrottlingHttpClient (30) -> throttles requests
-            // 2. UriTemplateHttpClient (25) -> expands URI templates
-            // 3. ScopingHttpClient (20) -> resolves relative URLs and applies scope configuration
-            // 4. CachingHttpClient (15) -> caches responses
+            // 2. CachingHttpClient (25) -> caches responses
+            // 3. UriTemplateHttpClient (20) -> expands URI templates
+            // 4. ScopingHttpClient (15) -> resolves relative URLs and applies scope configuration
             // 5. RetryableHttpClient (10) -> retries requests
             // 6. TraceableHttpClient (5) -> traces requests
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Looks like I completely messed up the decoration order
I think the left side numbering is the right one:
- first we want to throttle
- then resolve URI
- pass resolved URIs to scoping
- cache
- retry failures
- trace real requests with everything resolved

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]:
```diff
diff --git a/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php b/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
index 2f9748cf9b3..71893737681 100644
--- a/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
+++ b/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
@@ -2870,12 +2870,12 @@ class FrameworkExtension extends Extension
             unset($scopeConfig['retry_failed']);

             // This "transport" service is decorated in the following order:
-            // 1. ThrottlingHttpClient (30) -> throttles requests
-            // 2. UriTemplateHttpClient (25) -> expands URI templates
-            // 3. ScopingHttpClient (20) -> resolves relative URLs and applies scope configuration
-            // 4. CachingHttpClient (15) -> caches responses
-            // 5. RetryableHttpClient (10) -> retries requests
-            // 6. TraceableHttpClient (5) -> traces requests
+            // 1. ThrottlingHttpClient (5) -> throttles requests
+            // 2. UriTemplateHttpClient (10) -> expands URI templates
+            // 3. ScopingHttpClient (15) -> resolves relative URLs and applies scope configuration
+            // 4. CachingHttpClient (20) -> caches responses
+            // 5. RetryableHttpClient (25) -> retries requests
+            // 6. TraceableHttpClient (100) -> traces requests
             $container->register($name, HttpClientInterface::class)
                 ->setFactory('current')
                 ->setArguments([[new Reference('http_client.transport')]])
@@ -2883,7 +2883,7 @@ class FrameworkExtension extends Extension
             ;

             $scopingDefinition = $container->register($name.'.scoping', ScopingHttpClient::class)
-                ->setDecoratedService($name, null, 20)
+                ->setDecoratedService($name, null, 15)
                 ->addTag('kernel.reset', ['method' => 'reset', 'on_invalid' => 'ignore']);

             if (null === $scope) {
@@ -2912,7 +2912,7 @@ class FrameworkExtension extends Extension

             $container
                 ->register($name.'.uri_template', UriTemplateHttpClient::class)
-                ->setDecoratedService($name, null, 25)
+                ->setDecoratedService($name, null, 10)
                 ->setArguments([
                     new Reference('.inner'),
                     new Reference('http_client.uri_template_expander', ContainerInterface::NULL_ON_INVALID_REFERENCE),
@@ -2951,7 +2951,7 @@ class FrameworkExtension extends Extension

         $container
             ->register($name.'.caching', CachingHttpClient::class)
-            ->setDecoratedService($name, null, 15)
+            ->setDecoratedService($name, null, 20)
             ->setArguments([
                 new Reference('.inner'),
                 new Reference($options['cache_pool']),
@@ -2976,7 +2976,7 @@ class FrameworkExtension extends Extension

         $container
             ->register($name.'.throttling', ThrottlingHttpClient::class)
-            ->setDecoratedService($name, null, 30)
+            ->setDecoratedService($name, null, 5)
             ->setArguments([new Reference('.inner'), new Reference($name.'.throttling.limiter')]);
     }

@@ -3008,7 +3008,7 @@ class FrameworkExtension extends Extension

         $container
             ->register($name.'.retryable', RetryableHttpClient::class)
-            ->setDecoratedService($name, null, 10)
+            ->setDecoratedService($name, null, 25)
             ->setArguments([new Reference('.inner'), $retryStrategy, $options['max_retries'], new Reference('logger')])
             ->addTag('monolog.logger', ['channel' => 'http_client']);
     }
diff --git a/src/Symfony/Component/HttpClient/DependencyInjection/HttpClientPass.php b/src/Symfony/Component/HttpClient/DependencyInjection/HttpClientPass.php
index b07af272722..30e641ef050 100644
--- a/src/Symfony/Component/HttpClient/DependencyInjection/HttpClientPass.php
+++ b/src/Symfony/Component/HttpClient/DependencyInjection/HttpClientPass.php
@@ -27,7 +27,7 @@ final class HttpClientPass implements CompilerPassInterface

         foreach ($container->findTaggedServiceIds('http_client.client') as $id => $tags) {
             $container->register('.debug.'.$id, TraceableHttpClient::class)
-                ->setDecoratedService($id, null, 5)
+                ->setDecoratedService($id, null, 100)
                 ->setArguments([new Reference('.inner'), new Reference('debug.stopwatch', ContainerInterface::IGNORE_ON_INVALID_REFERENCE), new Reference('profiler.is_disabled_state_checker', ContainerInterface::IGNORE_ON_INVALID_REFERENCE)])
                 ->addTag('kernel.reset', ['method' => 'reset']);
```

**Review by nicolas-grekas — APPROVED** [review]
(I applied my suggestion)

**Review by stof — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @Lctrs.

**Comment by Lctrs** [comment]
@nicolas-grekas Caching should occur after Retry to handle potential cache inconsistencies.

Also, is it worth Throttling a request if we have a cache entry for it ? 🤔

**Comment by nicolas-grekas** [comment]
If there's a separate concern, we can discuss it on another PR/issue. The linked issue is now fixed, with the originally intended order :)
