### PR TITLE
[Messenger] Fix ignored options in redis transport

### LINKED ISSUE #33425: [Messenger] [Redis] options object is not used
**Symfony version(s) affected**: 4.3.4

**Description**  
According to the documentation, Redis should be configurable using the `options` object, but this seems not to work. 

**How to reproduce**  
```yaml
framework:
  messenger:
    transports:
      mytransport:
        dsn: "redis://localhost:6379"
        options:
          stream: "stream-name"
          group: "worker-group"
          auto_setup: true
```
Messages should be posted into the `stream-name` stream, and consumed using `worker-group` group. However, messages are posted into `messages` stream, and consumed using `symfony` group name - you can check this on redis-cli: `XPENDING messages worker-group`  yields `"NOGROUP No such key 'messages' or consumer group 'worker-group'"`.

Using querystring parameters to configure the same options works just fine.

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #33425 
| License       | MIT
| Doc PR        | -

Also fixes redis authentication failure handling (inline with invalid db index handling, borrowed from symfony/cache).
/cc @alexander-schranz

### CODE REVIEW

File: src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php [hunk 1]
```diff
@@ -52,8 +53,8 @@ public function __construct(array $configuration, array $connectionCredentials =
         $this->connection->connect($connectionCredentials['host'] ?? '127.0.0.1', $connectionCredentials['port'] ?? 6379);
         $this->connection->setOption(\Redis::OPT_SERIALIZER, $redisOptions['serializer'] ?? \Redis::SERIALIZER_PHP);
 
-        if (isset($connectionCredentials['auth'])) {
-            $this->connection->auth($connectionCredentials['auth']);
+        if (isset($connectionCredentials['auth']) && !$this->connection->auth($connectionCredentials['auth'])) {
+            throw new InvalidArgumentException(sprintf('Redis connection failed: %s', $redis->getLastError()));
```
Comment (alexander-schranz) [inline src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php]: @chalasr mostlywe did:

```
if ($error = $this->connection->getLastError() ?: null) {
    $this->connection->clearLastError();
}
```

Should we do the same here?

**Review by alexander-schranz — COMMENTED** [review]
@chalasr should we clear the last error after getting it like we do it on other places?

File: src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php (hunk 1 above)
Comment (chalasr) [reply src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php]: @alexander-schranz I don't think so because we don't throw a `TransportException` here but a logic one, it is not meant to be caught by the worker

Comment (alexander-schranz) [reply src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php]: @chalasr Sounds reasonable 👍 . Thank you for your fix!

**Review by alexander-schranz — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @chalasr.
