### PR TITLE
Fix #19531 [Form] DateType fails parsing when midnight is not a valid time

### LINKED ISSUE #19531: [Form] DateType fails parsing when midnight is not a valid time
In some timezones, **midnight may not be a valid date**; this happens when the DST change was done on midnight. It's a poor choice, and it was done only in the past. If you enter those dates in a `DateType`, it gets rejected as invalid. 

Under the hood, the issue is with the `\IntlDateFormatter` that is initialized with the current timezone, when with a simple date it can be avoided... Here: https://github.com/symfony/symfony/blob/3.1/src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php#L119

Maybe decoupling between DateType and DateTimeType could be a solution?

In my case, TZ is `Europe/Rome` and one of the infamous date is `1978-05-28`; I can reproduce the issue in this 3val: https://3v4l.org/NDnbm
DateTime doesn't suffer this bug: https://3v4l.org/ZmQ1q

Mainly, the Form uses the intl extension, that uses ICU, and that assumes midnight as the hour if not specified, which is what happens when  you use a `DateType` field.

I tried to open a bug on https://bugs.php.net/bug.php?id=72649 but it got closed... What can we do about it?

PS: this issue surfaced already multiple times: #18267 #16518 #16368

### PR DESCRIPTION
**Pull request by mbeccati**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #19531 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by Jean85** [comment]
Thanks for fixing this so fast!

Status: reviewed

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php [hunk 1]
```diff
@@ -163,4 +175,25 @@ protected function getIntlDateFormatter()
...
+    /**
+     * Checks if the pattern contains only a date.
+     *
+     * @param string $pattern The input pattern
+     *
+     * @return bool
+     */
+    protected function isPatternDateOnly()
+    {
+        // the default pattern includes time
```
Comment (javiereguiluz) [inline src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php]: Maybe this comment is unnecessary?

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php [hunk 2]
```diff
@@ -163,4 +175,25 @@ protected function getIntlDateFormatter()
...
+        if (null === $this->pattern) {
+            return false;
+        }
+
+        // strip escaped text
```
Comment (javiereguiluz) [inline src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php]: And this comment may be unnecessary too?

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php [hunk 3]
```diff
@@ -117,20 +117,30 @@ public function reverseTransform($value)
...
+            }
+
+            // read timestamp into DateTime object - the formatter delivers a timestamp
+            $dateTime = new \DateTime(sprintf('@%s', $timestamp), new \DateTimeZone($this->outputTimezone));
         } catch (\Exception $e) {
             throw new TransformationFailedException($e->getMessage(), $e->getCode(), $e);
         }
 
-        if ('UTC' !== $this->inputTimezone) {
+        // perform the conversion only when necessary
```
Comment (javiereguiluz) [inline src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php]: Maybe this comment is unnecessary?

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php (hunk 2 above)
Comment (mbeccati) [inline src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php]: I don't know - ICU escaping is not very common and it might not be clear what we're doing here.

**Comment by mbeccati** [comment]
@javiereguiluz Pushed comment amendments + additional test w/ escaped text

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php [hunk 4]
```diff
@@ -163,4 +174,24 @@ protected function getIntlDateFormatter()
...
+     * @return bool
+     */
+    protected function isPatternDateOnly()
+    {
+        if (null === $this->pattern) {
+            return false;
+        }
+
+        // strip escaped text
+        $pattern = preg_replace("#'(.*?)'#", '', $this->pattern);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php]: Can you add a test with escaped ICU data?

Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php]: oh, it's there, I had to right scroll :)

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @mbeccati.
