### PR TITLE
[RateLimiter] Fix infinite values with NoLimiter

### LINKED ISSUE #39899: [RateLimiter] TypeError when using "no_limit" policy
**Symfony version(s) affected**: 5.2

**Description**  
When using "no_limit" policy with rate limiter, for example during tests, [NoLimiter](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/RateLimiter/Policy/NoLimiter.php#L37) passes `\INF` as constructor argument to [RateLimit](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/RateLimiter/RateLimit.php#L28) which expects integer and this will result in TypeError.

`TypeError: Argument 1 passed to Symfony\Component\RateLimiter\RateLimit::__construct() must be of the type int, float given, called in /home/jontsa/Code/demo/vendor/symfony/rate-limiter/Policy/NoLimiter.php on line 37`

**How to reproduce**  
Install symfony/rate-limiter component and configure limit using no_limit policy

```
# config/packages/rate_limiter.yaml
framework:
  rate_limiter:
    anonymous_api:
      policy: 'no_limit'
      limit: 10
      interval: '1 minute'
```

Then attempt to consume one token using this limiter:

```
    private function checkAnonymousRateLimit(Request $request, RateLimiterFactory $anonymousApiLimiter) : void
    {
        $limiter = $anonymousApiLimiter->create($request->getClientIp());
        $limit = $limiter->consume(1);
        if (false === $limit->isAccepted()) {
            throw new TooManyRequestsHttpException();
        }
    }
```

**Possible Solution**  

**Additional context**

### PR DESCRIPTION
**Pull request by YaFou**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39899
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

See #39899. I don't find any solution to convert `\INF` constant (which is a float value) to an integer.

### CODE REVIEW

File: src/Symfony/Component/RateLimiter/Policy/NoLimiter.php [hunk 1]
```diff
@@ -29,12 +29,12 @@ final class NoLimiter implements LimiterInterface
 {
     public function reserve(int $tokens = 1, ?float $maxTime = null): Reservation
     {
-        return new Reservation(time(), new RateLimit(\INF, new \DateTimeImmutable(), true, \INF));
```
Comment (OskarStark) [inline src/Symfony/Component/RateLimiter/Policy/NoLimiter.php:32]: I am not into the code nor the component, but couldn't we use "-1" like for example done in memory_limit setting in PHP instead of a very large number? 🧐

cc @wouterj

**Comment by YaFou** [comment]
@OskarStark, currently the only use of the `remainingTokens` and `limit` properties is for the developer to know how many requests the user can send. This is not used internally in the RateLimiter component.

File: src/Symfony/Component/RateLimiter/Policy/NoLimiter.php (hunk 1 above)
Comment (YaFou) [reply src/Symfony/Component/RateLimiter/Policy/NoLimiter.php:32]: Currently the only use of the remainingTokens and limit properties is for the developer to know how many requests the user can send. This is not used internally in the RateLimiter component.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @YaFou.
