### PR TITLE
[Yaml] Add support for dumping `null` as an empty value by using the `Yaml::DUMP_NULL_AS_EMPTY` flag

### LINKED ISSUE #58155: [Yaml] Dumping with no value (like Docker Compose volumes section) isn't supported
### Symfony version(s) affected

7.1

### Description

There is no way to dump  a YAML section "without values".

### How to reproduce

Dumping the following "Docker Compose volumes section":

```php
$yaml = Yaml::dump([
  'volumes' => [
    'db-data' => null,
  ],
]);
```

Will result in:

```yaml
volumes:
    db-data: null
```

Using an empty string istead will result in:

```yaml
volumes:
    db-data: ''
```

There is actually no way to dump "without value" like:

```yaml
volumes:
    db-data:
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #58155
| License       | MIT

Another try after #58232. I went for the second solution from @stof (https://github.com/symfony/symfony/pull/58232#issuecomment-2344319568), namely dumping empty value as null just in expanded sequences and mappings. When the inline limit of the dumper is reached, it fallbacks on using `null` (examples in tests).

I'm not 100% happy about the name of the constant, `DUMP_NULL_AS_EMPTY_IN_EXPANDED_NOTATION`. It's verbose. I'm open to suggestions!

### CODE REVIEW

File: src/Symfony/Component/Yaml/Dumper.php [hunk 1]
```diff
@@ -55,7 +55,7 @@ public function dump(mixed $input, int $inline = 0, int $indent = 0, int $flags
         }
 
         if ($inline <= 0 || (!\is_array($input) && !$input instanceof TaggedValue && $dumpObjectAsInlineMap) || !$input) {
-            $output .= $prefix.Inline::dump($input, $flags);
+            $output .= $prefix.(0 <= $inline && null === $input && $flags & Yaml::DUMP_NULL_AS_EMPTY_IN_EXPANDED_NOTATION ? '' : Inline::dump($input, $flags));
```
Comment (stof) [inline src/Symfony/Component/Yaml/Dumper.php]: The location of this code change looks weird to me. What happens when `$inline >= 0` (i.e. we haven't reached the level where we force inline values yet) ? All you test put `null` on the second level of nesting, while switching to inline mode at depth 2 or less (there is a case putting `null` on the first level, but it has the inline depth set at `1` as well).

I'm quite sure this will *not* dump null values as empty content properly in expanded maps that are less nested than the limit. And on the other hand, it looks like it could dump a top-level `null` as empty value with the default value for `$inline` (which is not covered by your tests)

**Review by stof — CHANGES_REQUESTED** [review]

**Comment by xabbuh** [comment]
The name of the constant makes me think that we stills should improve the parser to try to support all possible inline notations. Do you have a list of examples that would currently not be parsed properly?

**Comment by alexandre-daubois** [comment]
@xabbuh by taking into account the cases we don't want to support as listed by @stof in https://github.com/symfony/symfony/pull/58232#issuecomment-2344252559, I would say that the only unsupported feature we may want to add support to is empty values in sequences, i.e. `[foo, , bar]`. Currently, the second value is ignored, where the spec says it should be handled as null.

**Comment by xabbuh** [comment]
see #58279

**Comment by alexandre-daubois** [comment]
I just pushed a new approach that takes into account @xabbuh's PR on supporting empty values in sequences.

File: src/Symfony/Component/Yaml/Dumper.php [hunk 2]
```diff
@@ -39,13 +39,18 @@ public function __construct(int $indentation = 4)
...
-     * @param int                       $indent The level of indentation (used internally)
-     * @param int-mask-of<Yaml::DUMP_*> $flags  A bit field of Yaml::DUMP_* constants to customize the dumped YAML string
+     * @param mixed                     $input        The PHP value
+     * @param int                       $inline       The level where you switch to inline YAML
+     * @param int                       $indent       The level of indentation (used internally)
+     * @param int-mask-of<Yaml::DUMP_*> $flags        A bit field of Yaml::DUMP_* constants to customize the dumped YAML string
+     * @param int                       $nestingLevel The level of nesting (used internally)
      */
-    public function dump(mixed $input, int $inline = 0, int $indent = 0, int $flags = 0): string
+    public function dump(mixed $input, int $inline = 0, int $indent = 0, int $flags = 0, int $nestingLevel = 0): string
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Dumper.php]: I would prefer to not expose the nesting level. We could instead move the current code of the `dump()` method into a new (`private`) `doDump()` method which gets this new argument, call it everywhere inside this class and pass `0` when being called from the new `dump()` method.

Comment (alexandre-daubois) [reply src/Symfony/Component/Yaml/Dumper.php]: I like it very much. Updated with your suggestion. Thanks!

**Comment by alexandre-daubois** [comment]
Status: Needs review

File: src/Symfony/Component/Yaml/Tests/DumperTest.php [hunk 3]
```diff
@@ -216,6 +216,63 @@ public function testObjectSupportDisabledWithExceptions()
...
+    {
+        $this->expectException(\InvalidArgumentException::class);
+        $this->expectExceptionMessage('The Yaml::DUMP_NULL_AS_EMPTY and Yaml::DUMP_NULL_AS_TILDE flags cannot be used together.');
+
+        $this->dumper->dump(['foo' => 'bar'], 0, 0, Yaml::DUMP_NULL_AS_EMPTY | Yaml::DUMP_NULL_AS_TILDE);
+    }
+
+    public function testDumpNullAsEmptyInExpandedMapping()
+    {
+        $expected = "qux:\n    foo: bar\n    baz: \n";
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Tests/DumperTest.php:229]: Can we ensure to not dump with trailing whitespaces so that this line would become this:

```suggestion
        $expected = "qux:\n    foo: bar\n    baz:\n";
```

Comment (alexandre-daubois) [reply src/Symfony/Component/Yaml/Tests/DumperTest.php:229]: Because of how the code is designed, it's complicated. This is the line that handles adding a blank space is this one:

https://github.com/symfony/symfony/blob/cb16097fc5ecf194401d0930f69a883a1c2b2755/src/Symfony/Component/Yaml/Dumper.php#L128

We would have to check for the flag and the value to be dumped at this place, which seems very specific and not sure it would worth the extra complexity here for removing the blank space (which is still valid YAML). What do you think?

**Review by xabbuh — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]
For 7.3

**Comment by xabbuh** [comment]
Thank you @alexandre-daubois.
