### PR TITLE
[BrowserKit] Allow wrapping response content to give proper context when fetching fragments

### LINKED ISSUE #62834: [DomCrawler]: 7.4 does not handle fragments
### Symfony version(s) affected

7.4.x

### Description

In symfony 7.4 the domcrawler uses the new \Dom\HTMLDocument::createFromString()  method. 

The problem arises if you want to test flows where the backend returns fragments to be injected into an existing page - for example multiple rows of a table. The crawler will fail because the fragment is not a valid html document.

IMHO this is a regression from the current behaviour and comes at a time when returning fragments like this is more used (f.x with HTMX ).

### How to reproduce

NB, AI generated reproducer:

```php
class CrawlerHtml5RegressionTest extends WebTestCase
{
    private string $trFragment = '<tr class="my-row" id="row-1">
  <td>Column 1</td>
  <td class="data-cell"><abbr title="2025-12-22">22.12.25</abbr></td>
</tr>';

    public function testTrFragmentWithHtml5ParserEnabled(): void
    {
        // Default behavior in Symfony 7.4 + PHP 8.4
        $crawler = new Crawler($this->trFragment);

        // These assertions fail on Symfony 7.4 + PHP 8.4
        // The <tr> and <td> elements are stripped by the HTML5 parser
        $this->assertEquals(1, $crawler->filter('tr')->count(), 'Expected 1 <tr> element');
        $this->assertEquals(1, $crawler->filter('.data-cell')->count(), 'Expected 1 .data-cell element');
        $this->assertEquals(1, $crawler->filter('.data-cell abbr')->count(), 'Expected 1 abbr inside .data-cell');
        $this->assertEquals('22.12.25', $crawler->filter('.data-cell abbr')->text());
    }

    public function testTrFragmentWithHtml5ParserDisabled(): void
    {
        // Legacy behavior - works but deprecated in Symfony 7.4
        $crawler = new Crawler($this->trFragment, useHtml5Parser: false);

        // These assertions pass with HTML5 parser disabled
        $this->assertEquals(1, $crawler->filter('tr')->count(), 'Expected 1 <tr> element');
        $this->assertEquals(1, $crawler->filter('.data-cell')->count(), 'Expected 1 .data-cell element');
        $this->assertEquals(1, $crawler->filter('.data-cell abbr')->count(), 'Expected 1 abbr inside .data-cell');
        $this->assertEquals('22.12.25', $crawler->filter('.data-cell abbr')->text());
    }

    public function testTrFragmentWrappedInTable(): void
    {
        // Workaround: wrap fragment in proper table structure
        $wrappedFragment = '<table><tbody>' . $this->trFragment . '</tbody></table>';
        $crawler = new Crawler($wrappedFragment);

        // These assertions pass when properly wrapped
        $this->assertEquals(1, $crawler->filter('tr')->count(), 'Expected 1 <tr> element');
        $this->assertEquals(1, $crawler->filter('.data-cell')->count(), 'Expected 1 .data-cell element');
        $this->assertEquals(1, $crawler->filter('.data-cell abbr')->count(), 'Expected 1 abbr inside .data-cell');
        $this->assertEquals('22.12.25', $crawler->filter('.data-cell abbr')->text());
    }

    public function testDemonstratesHtml5FosterParenting(): void
    {
        $crawler = new Crawler($this->trFragment);

        // Show what the HTML5 parser actually produces
        $html = $crawler->html();

        // On PHP 8.4 + Symfony 7.4, the output is:
        // <head></head><body>\n  Column 1\n  <abbr title="2025-12-22">22.12.25</abbr>\n</body>
        //
        // The <tr>, <td> elements and their classes are completely stripped!
        // Only the text content and nested non-table elements survive.

        if (PHP_VERSION_ID >= 80400) {
            $this->assertStringNotContainsString('<tr', $html, 'HTML5 parser strips <tr> elements');
            $this->assertStringNotContainsString('<td', $html, 'HTML5 parser strips <td> elements');
            $this->assertStringNotContainsString('data-cell', $html, 'HTML5 parser strips class attributes on table elements');
            $this->assertStringContainsString('<abbr', $html, 'Non-table elements survive');
        }
    }
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Jean-Beru**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #62834
| License       | MIT

This PR adds a new `wrapContent` method to `AbstractBrowser` to wrap response content. The PR target 7.4 to allow tests migration before definitive native HTML parser adoption.

Example with a controller which returns `<tr><td>Cell content</td></tr>`:
```php
// Will display "<head></head><body>Cell content</body>" due to native HTML5 parser
// Note that tr and td tags are removed since they are not inside a table tag
echo $client->xmlHttpRequest('GET', 'http://example.com/segment')->html();

// Will display "<table><tbody><tr><td>Cell content</td></tr></tbody></table>" since this HTML is valid
// Note that tr and td tags are preserved
echo $client->wrapContent('<table>%s</table>')->xmlHttpRequest('GET', 'http://example.com/segment')->html();
```

### CODE REVIEW

File: src/Symfony/Component/BrowserKit/AbstractBrowser.php [hunk 1]
```diff
@@ -404,7 +405,7 @@ public function request(string $method, string $uri, array $parameters = [], arr
             return $this->crawler = $this->followRedirect();
         }
 
-        $this->crawler = $this->createCrawlerFromContent($this->internalRequest->getUri(), $this->internalResponse->getContent(), $this->internalResponse->getHeader('Content-Type') ?? '');
+        $this->crawler = $this->createCrawlerFromContent($this->internalRequest->getUri(), $this->internalResponse->getContent(), $this->internalResponse->getHeader('Content-Type') ?? '', $wrapContentFormat);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/BrowserKit/AbstractBrowser.php]: what about wrapping before the call to createCrawlerFromContent?

File: src/Symfony/Component/BrowserKit/AbstractBrowser.php [hunk 2]
```diff
@@ -332,15 +332,16 @@ public function submitForm(string $button, array $fieldValues = [], string $meth
...
+     * @param string      $uri               The URI to fetch
+     * @param array       $parameters        The Request parameters
+     * @param array       $files             The files
+     * @param array       $server            The server parameters (HTTP headers are referenced with an HTTP_ prefix as PHP does)
+     * @param string|null $content           The raw body data
+     * @param bool        $changeHistory     Whether to update the history or not (only used internally for back(), forward(), and reload())
+     * @param string|null $wrapContentFormat Wrap the response content using the given format
      */
-    public function request(string $method, string $uri, array $parameters = [], array $files = [], array $server = [], ?string $content = null, bool $changeHistory = true): Crawler
+    public function request(string $method, string $uri, array $parameters = [], array $files = [], array $server = [], ?string $content = null, bool $changeHistory = true, ?string $wrapContentFormat = null): Crawler
```
Comment (nicolas-grekas) [inline src/Symfony/Component/BrowserKit/AbstractBrowser.php]: instead of adding a new argument, what about adding a method to configure the wrapper?
something like `AbstractBrowser::wrapContent(string|false $pattern)`?
that'd be easier also in terms of BC (here, there's a missing BC layer)

Comment (Jean-Beru) [reply src/Symfony/Component/BrowserKit/AbstractBrowser.php]: Indeed, much easier like that.

**Review by nicolas-grekas — APPROVED** [review]
Please add a 'ine in the changelog of the component, and in the upgrade-7.4 file, that'd help discovering this.

File: src/Symfony/Component/BrowserKit/Tests/AbstractBrowserTest.php [hunk 3]
```diff
@@ -108,6 +108,19 @@ public function testGetResponseNull()
         $client->getResponse();
     }
 
+    /**
+     * @see https://github.com/symfony/symfony/issues/62834
+     */
```
Comment (nicolas-grekas) [inline src/Symfony/Component/BrowserKit/Tests/AbstractBrowserTest.php]:
```suggestion
```

File: src/Symfony/Component/BrowserKit/CHANGELOG.md [hunk 4]
```diff
@@ -7,6 +7,7 @@ CHANGELOG
  * Add `isFirstPage()` and `isLastPage()` methods to the History class for checking navigation boundaries
  * Add PHPUnit constraints: `BrowserHistoryIsOnFirstPage` and `BrowserHistoryIsOnLastPage`
  * Deprecate `AbstractBrowser::useHtml5Parser()`; Symfony 8 will unconditionally use the native HTML5 parser
+ * Add `AbstractBrowser::wrapContent()` method to wrap response content and control tag deletion
```
Comment (nicolas-grekas) [inline src/Symfony/Component/BrowserKit/CHANGELOG.md]:
```suggestion
 * Add `AbstractBrowser::wrapContent()` method to wrap response content and give proper context when fetching fragments
```

File: UPGRADE-7.4.md [hunk 5]
```diff
@@ -12,6 +12,7 @@ BrowserKit
 ----------
 
  * Deprecate `AbstractBrowser::useHtml5Parser()`; Symfony 8 will unconditionally use the native HTML5 parser
+ * Add `AbstractBrowser::wrapContent()` method to wrap response content and control tag deletion
```
Comment (nicolas-grekas) [inline UPGRADE-7.4.md]:
```suggestion
 * Add `AbstractBrowser::wrapContent()` method to wrap response content and give proper context when fetching fragments
```

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @Jean-Beru.
