### PR TITLE
[Form] Provide string keys when iterating on a form

### LINKED ISSUE #46698: FormInterface is reported as `\Traversable<string, FormInterface>` but can return int as key.
### Symfony version(s) affected

5.0.0 and more

### Description

Because the formBuilder use name as key, and because php is casting int-string like `'0'` to int, we sometimes ends with form name which is integer and this cannot be directly used by method like `FormInterface::remove`.

### How to reproduce

The following code 
```
foreach ($form as $name => $child) {
     $form->remove($name);
}
```
is not working when the form was build this way
```
$formBuilder->add('0', ...)
```
Because the name is casted to an int when used as an array key here:
https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Form/FormBuilder.php#L71-L72

There are some situation  in the Symfony code where the form names can be int and passed to method expecting string. One of them is the `ChoiceType` with expanded option.
https://github.com/symfony/form/blob/6.1/Extension/Core/Type/ChoiceType.php#L407-L419

So far this code is working because `declare(strict_types=1);` is not used.

But for my first example
```
foreach ($form as $name => $child) {
     $form->remove($name);
}
```
if it's written in the userland with strict_types, it won't work even if all the phpdoc make believe it will:
- FormInterface is a `\Traversable<string, FormInterface>`
- remove accepts `string`

### Possible Solution

I see at least four solutions here:
- Changing some of the typehint in https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Form/FormInterface.php to accepts `int|string` (since it's a BC-break, this might wait for 7.0)
- Changing the phpdoc to `\Traversable<int|string, FormInterface>` with some comments; at least static-analysis user will be warned.
- Deprecating passing an integer-as-string as a form name ; this might be the smoother solution. Instead of `$formBuilder->add('0')` it should be `$formBuilder->add('prefix_0')`. And in SF 7.0, this will throw an exception.
- Doing nothing

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by VincentLanglet**
| Q             | A
| ------------- | ---
| Branch?       | 6.2  as recommended by https://github.com/symfony/symfony/issues/46698#issuecomment-1169942792
| Bug fix?      | no (?)
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #46698
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

cc @derrabus

### CODE REVIEW

File: src/Symfony/Component/Form/Form.php [hunk 1]
```diff
@@ -962,7 +962,10 @@ public function offsetUnset(mixed $name): void
      */
     public function getIterator(): \Traversable
     {
-        return $this->children;
+        // We cast to string every key to avoid issue with keys like `'0'`, `'1'`, ...
```
Comment (xabbuh) [inline src/Symfony/Component/Form/Form.php]:
```suggestion
        // the explicit string type-cast is necessary as digit-only keys would be returned as integers otherwise
```

File: src/Symfony/Component/Form/Form.php [hunk 2]
```diff
@@ -962,7 +962,10 @@ public function offsetUnset(mixed $name): void
...
+        foreach ($this->children as $key => $value) {
```
Comment (HeahDude) [inline src/Symfony/Component/Form/Form.php]: Could it lead to a BC break given that the returned iterator is not rewindable anymore?

Comment (VincentLanglet) [reply src/Symfony/Component/Form/Form.php]: I would believe that the BC-policy is only about the typehint which is `\Traversable`.

But do you see another way to type-cast the keys to string and still keep the rewindable feature ?

File: src/Symfony/Component/Form/Form.php (hunk 1 above)
Comment (VincentLanglet) [reply src/Symfony/Component/Form/Form.php]: Done

**Comment by nicolas-grekas** [comment]
We'd rather patch `OrderedHashMap` and `OrderedHashMapIterator` to make *them* cast to string. I'd also remove the template on `TKey` and declare it to be always `string`.

File: src/Symfony/Component/Form/Util/OrderedHashMap.php [hunk 3]
```diff
@@ -96,12 +95,13 @@ class OrderedHashMap implements \ArrayAccess, \IteratorAggregate, \Countable
     /**
      * Creates a new map.
      *
-     * @param array<TKey, TValue> $elements The elements to insert initially
+     * @param array<string, TValue> $elements The elements to insert initially
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Util/OrderedHashMap.php]: should be just `array<TValue>` here as we accept any kind of array-key here, and we don't need to make it explicit

File: src/Symfony/Component/Form/Util/OrderedHashMap.php [hunk 4]
```diff
@@ -64,25 +64,24 @@
...
+ * @implements \ArrayAccess<string, TValue>
+ * @implements \IteratorAggregate<string, TValue>
  */
 class OrderedHashMap implements \ArrayAccess, \IteratorAggregate, \Countable
 {
     /**
      * The elements of the map, indexed by their keys.
      *
-     * @var array<TKey, TValue>
+     * @var array<string, TValue>
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Util/OrderedHashMap.php]: `array<TValue>` would be enough

File: src/Symfony/Component/Form/Util/OrderedHashMapIterator.php [hunk 5]
```diff
@@ -18,30 +18,29 @@
...
- * @template-covariant TKey of array-key
  * @template-covariant TValue
  *
- * @implements \Iterator<TKey, TValue>
+ * @implements \Iterator<string, TValue>
  */
 class OrderedHashMapIterator implements \Iterator
 {
-    /** @var array<TKey, TValue> */
+    /** @var array<string, TValue> */
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Util/OrderedHashMapIterator.php]: `array<TValue>`

File: src/Symfony/Component/Form/Util/OrderedHashMapIterator.php [hunk 6]
```diff
@@ -18,30 +18,29 @@
...
-    /** @var list<TKey> */
+    /** @var list<string> */
     private array $orderedKeys;
     private int $cursor = 0;
     private int $cursorId;
     /** @var array<int, int> */
     private array $managedCursors;
-    /** @var TKey|null */
-    private string|int|null $key = null;
+    /** @var string|null */
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Util/OrderedHashMapIterator.php]: can be removed

File: src/Symfony/Component/Form/Util/OrderedHashMapIterator.php [hunk 7]
```diff
@@ -18,30 +18,29 @@
...
+    private string|null $key = null;
     /** @var TValue|null */
     private mixed $current = null;
 
     /**
-     * @param array<TKey, TValue> $elements       The elements of the map, indexed by their
+     * @param array<string, TValue> $elements     The elements of the map, indexed by their
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Util/OrderedHashMapIterator.php]: `array<TValue>`

**Review by nicolas-grekas — APPROVED** [review]
Looks much cleaner thanks :)
Here are some nitpickings.
Please check fabbot also (please ignore the "exception message formatting")

File: src/Symfony/Component/Form/Util/OrderedHashMap.php (hunk 3 above)
Comment (stof) [reply src/Symfony/Component/Form/Util/OrderedHashMap.php]: Which we generally write as `TValue[]`

Comment (VincentLanglet) [reply src/Symfony/Component/Form/Util/OrderedHashMap.php]: Changed

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @VincentLanglet.
