### PR TITLE
[Validator] Fix validation for single level domains

### LINKED ISSUE #43868: [Validator] After update to 5.3.10 before valid urls are now marked as invalid
### Symfony version(s) affected

5.3.10

### Description

After update to symfony/validator 5.3.10 https://github.com/symfony/symfony/pull/43388 the Url Validator marks urls like `http://internal-api` as invalid. This url was fine in version 5.3.8 and the PR seems to be fixing a different issue, so it seems like unwanted consequence. The hyphen seems to be the problem. Urls like this one are commonly used for  docker-compose services.

### How to reproduce

```php
$validator = Symfony\Component\Validator\Validation::createValidator();
$errors = $validator->validate('http://internal-api', [new Url()]);
var_dump($errors);
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #43868, #44252
| License       | MIT
| Doc PR        | -

Not sure if there are any other test cases that could be added, but this seems to fix the problem.

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
This looks strange to me because this means that `['http://☎a']` is a valid domain name, while `['http://☎']` is invalid...

**Comment by welcoMattic** [comment]
> This looks strange to me because this means that `['http://☎a']` is a valid domain name, while `['http://☎']` is invalid...

@nicolas-grekas wasn't this case fixed by https://github.com/symfony/symfony/pull/44119?

**Comment by nicolas-grekas** [comment]
#44119 is on HttpClient+Mime, this one is on Validator, so I'm not sure.

**Comment by welcoMattic** [comment]
Yes you are right, at the Validator level maybe we don't have to worry about the `xn--` URL format?
If so, your concern is still legitimate

**Comment by HypeMC** [comment]
@nicolas-grekas Sorry, I missed your earlier comment, will check it out later today.

**Comment by nicolas-grekas** [comment]
Looks like #44252 could provide us with another test case, can you please incorporate it here also?

File: src/Symfony/Component/Validator/Constraints/UrlValidator.php [hunk 1]
```diff
@@ -26,7 +26,7 @@ class UrlValidator extends ConstraintValidator
             (%s)://                                 # protocol
             (((?:[\_\.\pL\pN-]|%%[0-9A-Fa-f]{2})+:)?((?:[\_\.\pL\pN-]|%%[0-9A-Fa-f]{2})+)@)?  # basic auth
             (
-                ([\pL\pN\pS\-\_]+\.)*(([\pL\pN]|xn\-\-[\pL\pN-]+)+\.?) # a domain name
+                ([\pL\pN\pS\-\_]+\.?)*(([\pL\pN]|xn\-\-[\pL\pN-]+)+\.?) # a domain name
```
Comment (stof) [inline src/Symfony/Component/Validator/Constraints/UrlValidator.php]: making this dot option makes this regex subject to ReDoS, as it will need to backtrack exponentially in case of non-match, due to the nested repetitions that can now be satisfied by any shorer length for the inner repetition.

to me, the right fix is rather to fix the second part of the line, adding `-` and `_` as allowed in the `[\pL\pN]` we have right now.

**Comment by HypeMC** [comment]
I've split the domain part into two cases:

1) single-level domain, the assumption here is that since there's no TLD, it's an internal domain, allows symbols, hyphens etc..
1) multi-level domain, has a TLD. Since I haven't been able to find any clear information on which characters are allowed in a TLD I went with hyphens allowed, but not at the end, no symbols

Of course, this won't work if you have a multi-level internal domain, eg `subdomain.internal☎`. Any suggestions would be appreciated.

**Review by GromNaN — APPROVED** [review]

**Review by welcoMattic — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]
I've update the regexp to not allow unicode chars in local domain names
I've also split it to deal with punycode separately from unicode global domain names,
and ensured that `http://বিডিআইএ.বাংলা` is accepted (adding `\pM` to the regexp) for unicode global domain names, since this host exists.

**Comment by nicolas-grekas** [comment]
Thank you @HypeMC.
