### PR TITLE
[Process] Fix backwards compatibility for invalid commands

### LINKED ISSUE #57946: [symfony/process] BC break with Process::isTerminated() when a process fail at start
### Symfony version(s) affected

7.1.0

### Description

Before 7.1, when a process failed at start because the command does not exists, nothing was different from a process who failed because of the exit code of the command.

Since 7.1, when the command does not exists (example: `unknown-command`), a new `ProcessStartFailedException` is throwned. It's interesting, why not, but then, `$process->isTerminated()` always return `false`. Before 7.1 (7.0, 6.x and before), in this particular case, `$process->isTerminated()` returned `true`.

From my point of view, it's a huge bc break, because we can't just try / catch the new exception, all the code who use `$process->isTerminated()` should be modified.

### How to reproduce

```php
$process = new Process(['unkown-command']);
try {
    $process->run();
// This exception is throwned in 7.1, but doesn't exists before (7.0, 6.x etc)
} catch (\Symfony\Component\Process\Exception\ProcessStartFailedException) {
}

var_dump(
    $process->isStarted(), // all versions : true
    $process->isTerminated(), // 7.0 and before : true, 7.1 : false
    $process->isSuccessful() // all versions : false
);
```

See https://github.com/steevanb/symfony-issue-57946

### Possible Solution

To be honnest, i don't know. Since `Process::isTerminated()` do not return a stored property, but call `updateStatus()` then check `$this->status`, I don't know how to fix it.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ausi**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | maybe?
| Issues        | Fix #57946
| License       | MIT

As discussed in https://github.com/symfony/symfony/issues/57946#issuecomment-2332184584

### CODE REVIEW

File: src/Symfony/Component/Process/Process.php [hunk 1]
```diff
@@ -358,6 +358,11 @@ public function start(?callable $callback = null, array $env = []): void
 
         try {
             $process = @proc_open($commandline, $descriptors, $this->processPipes->pipes, $this->cwd, $envPairs, $this->options);
+
+            // Backwards compatibility. To be removed in version 8.0
+            if (!\is_resource($process) && \is_array($commandline)) {
+                $process = @proc_open($this->buildShellCommandline($commandline), $descriptors, $this->processPipes->pipes, $this->cwd, $envPairs, $this->options);
+            }
```
Comment (ausi) [inline src/Symfony/Component/Process/Process.php]: Should we trigger a deprecation here like this?

```php
if (\is_resource($process)) {
    trigger_deprecation('symfony/process', '7.1', 'Executing non-existent commands will no longer start the process and instead throw a "%s" exception in 8.0.', ProcessStartFailedException::class);
}
```

Comment (ausi) [reply src/Symfony/Component/Process/Process.php]: Or just document it in the UPGRADE-7.1.md?

File: src/Symfony/Component/Process/Process.php [hunk 2]
```diff
@@ -358,6 +358,11 @@ public function start(?callable $callback = null, array $env = []): void
 
         try {
             $process = @proc_open($commandline, $descriptors, $this->processPipes->pipes, $this->cwd, $envPairs, $this->options);
+
+            // Backwards compatibility. To be removed in version 8.0
+            if (!\is_resource($process) && \is_array($commandline)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Process/Process.php]:
```suggestion
            if (!$process && \is_array($commandline)) {
```

File: src/Symfony/Component/Process/Process.php [hunk 3]
```diff
@@ -358,6 +358,11 @@ public function start(?callable $callback = null, array $env = []): void
 
         try {
             $process = @proc_open($commandline, $descriptors, $this->processPipes->pipes, $this->cwd, $envPairs, $this->options);
+
+            // Backwards compatibility. To be removed in version 8.0
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Process/Process.php]: I wouldn't change the behavior in 8.0, it's fins e as is.
```suggestion
            // Ensure array vs string commands behave the same
```

File: src/Symfony/Component/Process/Process.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Process/Process.php]: there's nothing to do IMHO, just revert to the previous behavior

File: src/Symfony/Component/Process/Tests/ProcessTest.php [hunk 4]
```diff
@@ -72,13 +72,8 @@ public function testInvalidCwd()
...
     public function testInvalidCommand(Process $process)
     {
-        try {
-            $this->assertSame('\\' === \DIRECTORY_SEPARATOR ? 1 : 127, $process->run());
-        } catch (ProcessStartFailedException $e) {
-            // An invalid command might already fail during start since PHP 8.3 for platforms
-            // supporting posix_spawn(), see https://github.com/php/php-src/issues/12589
-            $this->assertStringContainsString('No such file or directory', $e->getMessage());
-        }
+        // An invalid command should not fail during start (since PHP 8.3) to keep backwards compatibility
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Process/Tests/ProcessTest.php]:
```suggestion
        // An invalid command should not fail during start
```

File: src/Symfony/Component/Process/Process.php [hunk 5]
```diff
@@ -358,6 +358,11 @@ public function start(?callable $callback = null, array $env = []): void
...
+            if (!\is_resource($process) && \is_array($commandline)) {
+                $process = @proc_open($this->buildShellCommandline($commandline), $descriptors, $this->processPipes->pipes, $this->cwd, $envPairs, $this->options);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Process/Process.php]: we should also prefix with `exec`, either here or in buildShellCommandline I suppose (not on Windows of course)

Comment (ausi) [reply src/Symfony/Component/Process/Process.php]: Done in 1941795d8ab8320b61332ec447457cae5678b6a0

Windows can never reach here because `$commandline` is never an array at this point there.

File: src/Symfony/Component/Process/Process.php (hunk 1 above)
Comment (ausi) [reply src/Symfony/Component/Process/Process.php]: We lose a great deal of performance for cases where `proc_open()` fails. That’s why I’d prefer to remove this in a future version.

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Process/Process.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Process/Process.php]: > We lose a great deal of performance for cases where proc_open() fails

Sure but do we have a use case where failures are on the hot path?
If not, things are fine as is. If yes, we should make this opt-in.

Comment (ausi) [reply src/Symfony/Component/Process/Process.php]: I’m not sure. If someone has that use case they could probably make a pull request then.

I’d still like the behavior better that an invalid command throws an exception (like an invalid cwd already does). This would be the better API design I think. But that’s your decision of course :)

Comment (nicolas-grekas) [reply src/Symfony/Component/Process/Process.php]: Forward plan looks fine to me. We are tightly bound by BC concerns :)

**Comment by nicolas-grekas** [comment]
Thank you @ausi.

File: src/Symfony/Component/Process/Process.php (hunk 1 above)
Comment (stof) [reply src/Symfony/Component/Process/Process.php]: If we want to throw again an exception on invalid command in 8.0, we need to provide an opt-in in 7.x (but not 7.1 as new deprecations cannot be introduced in patch versions) with a deprecation when you keep using the old error handling behavior. We cannot just change the behavior in 8.0.
