### PR TITLE
[Messenger] Add FlattenException Normalizer

### LINKED ISSUE #32719: [Messenger] Message retried in failure transport dropped on exception
**Symfony version(s) affected**: 4.3.2

**Description**  
Message retried in failure transport dropped on exception

**How to reproduce**  
I configured a failure transport on symfony messenger (like explain here: https://symfony.com/blog/new-in-symfony-4-3-messenger-failure-transport)
I throw an error on my handler, the message is retried 3 times, and then sent to the failure transport.

Then, I retry the failed message with `bin/console messenger:consume failed` or `bin/console messenger:failed:retry {id}`.
The message handling fail again and the message is dropped.

Is it the normal behaviour ? Or is it a bug ?

### PR DESCRIPTION
**Pull request by monteiro**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Tickets       | Fix #32719  ... 
| License       | MIT
| Doc PR        | No docs ... 

I have just duplicated the PR https://github.com/symfony/symfony/pull/33650 (from @skalpa) but using the new component ErrorHandler and removing the priority.

Project that reproduces the bug on Symfony 5.2: https://github.com/monteiro/serializer-pr37087 (all steps are on the README).

Since this adds a new class and changes behavior, we add this new feature on the 5.2 branch.

### CODE REVIEW

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+     */
+    public function normalize($object, $format = null, array $context = [])
+    {
+        if (!$object instanceof FlattenException) {
+            throw new InvalidArgumentException(sprintf('The object must be an instance of "%s".', FlattenException::class));
+        }
+        /* @var FlattenException $object */
+
+        $normalized = [
+            'detail' => $object->getMessage(),
```
Comment (ro0NL) [inline src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:40]: why not 'message'?

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+            'code' => $object->getCode(),
+            'headers' => $object->getHeaders(),
+            'class' => $object->getClass(),
+            'file' => $object->getFile(),
+            'line' => $object->getLine(),
+            'previous' => null === $object->getPrevious() ? null : $this->normalize($object->getPrevious(), $format, $context),
```
Comment (ro0NL) [inline src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:46]: shouldnt this actually use the chained normalizer? Thus make it normalizer aware

**Comment by monteiro** [comment]
I still need to test well the priority, because it works on my symfony 5.0 (without it), but I want to try it on Symfony 4.4 to see if I have the same behavior.

**Review by ro0NL — COMMENTED** [review]
API platform normalizes FlattenException at a very low prio, is it an issue?

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+use Symfony\Component\ErrorHandler\Exception\FlattenException;
+use Symfony\Component\Serializer\Exception\InvalidArgumentException;
+use Symfony\Component\Serializer\Exception\NotNormalizableValueException;
+
+/**
+ * Normalizes FlattenException instances.
+ *
+ * @author Pascal Luna <skalpa@zetareticuli.org>
+ *
+ * @experimental
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:23]: this doesn't work, it should be removed before merging
why was it addded?

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php (hunk 1 above)
Comment (monteiro) [reply src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php]: changed, tks

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php (hunk 2 above)
Comment (monteiro) [reply src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:45]: Can you give me an example here?

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php (hunk 3 above)
Comment (monteiro) [reply src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php]: Hi @nicolas-grekas , just removed the experimental tag.

I also added a project where you can reproduce this exact bug:  https://github.com/monteiro/serializer-pr37087

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php (hunk 2 above)
Comment (ro0NL) [reply src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:44]: see `NormalizerAwareTrait + Interface` :) (i believe injecting leads to all sort of recursion issues).

So then you can leverage `$this->normalizer->normalize(..)` instead.

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php [hunk 4]
```diff
@@ -0,0 +1,116 @@
...
+     * {@inheritdoc}
+     *
+     * @throws InvalidArgumentException
+     */
+    public function normalize($object, $format = null, array $context = [])
+    {
+        if (!$object instanceof FlattenException) {
+            throw new InvalidArgumentException(sprintf('The object must be an instance of "%s".', FlattenException::class));
+        }
+        /* @var FlattenException $object */
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:35]: let's remove this also, IDEs should be able to figure out by looking at the previous "if"

File: src/Symfony/Component/Serializer/Tests/Normalizer/FlattenExceptionNormalizerTest.php [hunk 5]
```diff
@@ -0,0 +1,159 @@
...
+     * @var FlattenExceptionNormalizer
+     */
+    private $normalizer;
+
+    protected function setUp(): void
+    {
+        $this->normalizer = new FlattenExceptionNormalizer();
+    }
+
+    public function testSupportsNormalization(): void
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Tests/Normalizer/FlattenExceptionNormalizerTest.php:35]: please remove all `void` to test methods

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php (hunk 4 above)
Comment (ro0NL) [reply src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:35]: another alternative is to use @param, and remove the safeguard as well :)

**Comment by monteiro** [comment]
just trying the 2 unit tests failing:

```
There were 2 errors:
1) Symfony\Component\Serializer\Tests\Normalizer\FlattenExceptionNormalizerTest::testNormalize with data set "instance from constructor" (Symfony\Component\ErrorHandler\Exception\FlattenException Object (...))
TypeError: Return value of Symfony\Component\ErrorHandler\Exception\FlattenException::getMessage() must be of the type string, null returned
/home/travis/build/symfony/symfony/src/Symfony/Component/ErrorHandler/Exception/FlattenException.php:190
/home/travis/build/symfony/symfony/src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:37
/home/travis/build/symfony/symfony/src/Symfony/Component/Serializer/Tests/Normalizer/FlattenExceptionNormalizerTest.php:46
2) Symfony\Component\Serializer\Tests\Normalizer\FlattenExceptionNormalizerTest::testDenormalizeValidData
TypeError: Return value of Symfony\Component\ErrorHandler\Exception\FlattenException::getMessage() must be of the type string, null returned
/home/travis/build/symfony/symfony/src/Symfony/Component/ErrorHandler/Exception/FlattenException.php:190
/home/travis/build/symfony/symfony/src/Symfony/Component/Serializer/Tests/Normalizer/FlattenExceptionNormalizerTest.php:93
```

@nicolas-grekas Maybe you can help me with this. I know that on the FlattenException unit tests [FlattenException](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/ErrorHandler/Tests/Exception/FlattenExceptionTest.php) you never use the constructor without arguments.

You did the change in the [past](https://github.com/symfony/symfony/commit/810e4a136fd2c6e5f290a17c11d68041d687f3d2) adding typehints to the methods, which makes total sense when you are creating this exception from throwable. But what can we do in this specific case? 

Should I use the empty constructor? If I use it, the unit tests fail, because they have different typehints from the getters (Example: message is null in the empty constructor, but getMessage() has a string typehint). 

Or should I follow the FlattenException unit tests and remove the empty constructor test?

Note: This does not happen in this specific feature, because the normalizer does not call any getter without a full FlattenException.

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php [hunk 6]
```diff
@@ -0,0 +1,115 @@
...
+class FlattenExceptionNormalizer implements NormalizerInterface, DenormalizerInterface, CacheableSupportsMethodInterface
+{
+    /**
+     * {@inheritdoc}
+     *
+     * @throws InvalidArgumentException
+     */
+    public function normalize($object, $format = null, array $context = [])
+    {
+        if (!$object instanceof FlattenException) {
```
Comment (fabpot) [inline src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:32]: This can be removed as the supports method is here to check whether to call `normalize` or not.

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php (hunk 2 above)
Comment (fabpot) [reply src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:43]: Not sure it's worth it as we know that previous is a `FlattenException` exception anyway.

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php [hunk 7]
```diff
@@ -0,0 +1,115 @@
...
+ */
+
+namespace Symfony\Component\Serializer\Normalizer;
+
+use Symfony\Component\ErrorHandler\Exception\FlattenException;
+use Symfony\Component\Serializer\Exception\InvalidArgumentException;
+use Symfony\Component\Serializer\Exception\NotNormalizableValueException;
+
+/**
+ * Normalizes FlattenException instances.
```
Comment (fabpot) [inline src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:19]: I would add a warning about the danger of using it outside of a debugging/development context.

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php [hunk 8]
```diff
@@ -0,0 +1,115 @@
...
+    {
+        return $data instanceof FlattenException;
+    }
+
+    /**
+     * {@inheritdoc}
+     */
+    public function denormalize($data, $type, $format = null, array $context = [])
+    {
+        if (!\is_array($data)) {
```
Comment (fabpot) [inline src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:67]: This condition can be removed (again, it should always be the case).

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php [hunk 9]
```diff
@@ -0,0 +1,115 @@
...
+        $object = new FlattenException();
+
+        $object->setMessage($data['message'] ?? null);
+        $object->setCode($data['code'] ?? null);
+        $object->setStatusCode($data['status'] ?? null);
+        $object->setClass($data['class'] ?? null);
+        $object->setFile($data['file'] ?? null);
+        $object->setLine($data['line'] ?? null);
+
+        if (isset($data['headers'])) {
```
Comment (fabpot) [inline src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:80]: Not needed as always set.

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php [hunk 10]
```diff
@@ -0,0 +1,115 @@
...
+            $object->setHeaders((array) $data['headers']);
+        }
+        if (isset($data['previous'])) {
+            $object->setPrevious($this->denormalize($data['previous'], $type, $format, $context));
+        }
+        if (isset($data['trace'])) {
```
Comment (fabpot) [inline src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:86]: Not needed as always set.

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php [hunk 11]
```diff
@@ -0,0 +1,115 @@
...
+            $property = new \ReflectionProperty(FlattenException::class, 'trace');
+            $property->setAccessible(true);
+            $property->setValue($object, (array) $data['trace']);
+        }
+        if (isset($data['trace_as_string'])) {
```
Comment (fabpot) [inline src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:91]: Not needed as always set.

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php [hunk 12]
```diff
@@ -0,0 +1,115 @@
...
+     */
+    public function denormalize($data, $type, $format = null, array $context = [])
+    {
+        if (!\is_array($data)) {
+            throw new NotNormalizableValueException(sprintf('The normalized data must be an array, got "%s".', \is_object($data) ? \get_class($data) : \gettype($data)));
+        }
+
+        $object = new FlattenException();
+
+        $object->setMessage($data['message'] ?? null);
```
Comment (fabpot) [inline src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:73]: `?? null` can be removed as it's always set (same below except for `status`).

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.xml [hunk 13]
```diff
@@ -82,6 +82,10 @@
             <tag name="serializer.normalizer" priority="-1000" />
         </service>
         <service id="Symfony\Component\Serializer\Normalizer\ObjectNormalizer" alias="serializer.normalizer.object" />
+        
+        <service id="serializer.normalizer.flatten_exception" class="Symfony\Component\Serializer\Normalizer\FlattenExceptionNormalizer">
+            <tag name="serializer.normalizer" />
```
Comment (fabpot) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.xml:87]: I would use `-915` as a priority to be consistent with the above specific normalizers.

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php (hunk 2 above)
Comment (ro0NL) [reply src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:43]: yes, but if you write a custom decorating normalizer you want the inheritance to be taken care of i figured.

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php [hunk 14]
```diff
@@ -0,0 +1,115 @@
...
+use Symfony\Component\ErrorHandler\Exception\FlattenException;
+use Symfony\Component\Serializer\Exception\InvalidArgumentException;
+use Symfony\Component\Serializer\Exception\NotNormalizableValueException;
+
+/**
+ * Normalizes FlattenException instances.
+ *
+ * @author Pascal Luna <skalpa@zetareticuli.org>
+ */
+class FlattenExceptionNormalizer implements NormalizerInterface, DenormalizerInterface, CacheableSupportsMethodInterface
```
Comment (fabpot) [inline src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:23]: Can you mark this class as final?

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php (hunk 2 above)
Comment (fabpot) [reply src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:43]: Fair enough.

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.xml [hunk 15]
```diff
@@ -82,6 +82,10 @@
             <tag name="serializer.normalizer" priority="-1000" />
         </service>
         <service id="Symfony\Component\Serializer\Normalizer\ObjectNormalizer" alias="serializer.normalizer.object" />
+        
+        <service id="serializer.normalizer.flatten_exception" class="Symfony\Component\Serializer\Normalizer\FlattenExceptionNormalizer">
```
Comment (YaFou) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.xml:86]: You should move this configuration to PHP.

Comment (monteiro) [reply src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.xml:86]: Thanks! I will do it.

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php (hunk 7 above)
Comment (monteiro) [reply src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:19]: This is currently used by Messenger to serialize exceptions into the Transport Headers (e.g. The error happens when you serialize to json the exception). Should I add that warning still?

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php (hunk 2 above)
Comment (monteiro) [reply src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:40]: Already added the trait.

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.xml [hunk 16]
```diff
@@ -82,6 +82,10 @@
...
+            <tag name="serializer.normalizer" priority="-800" />
```
Comment (monteiro) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.xml:87]: I had to put -800 so it is called before ObjectNormalizer. If I put -915 as suggested, the right normalized it's not called, so it will be creating a wrong json.

File: src/Symfony/Component/Messenger/EventListener/SendFailedMessageForRetryListener.php [hunk 17]
```diff
@@ -67,7 +68,7 @@ public function onMessageFailed(WorkerMessageFailedEvent $event)
             }
 
             // add the delay and retry stamp info
-            $retryEnvelope = $this->withLimitedHistory($envelope, new DelayStamp($delay), new RedeliveryStamp($retryCount));
+            $retryEnvelope = $this->withLimitedHistory($envelope, new DelayStamp($delay), new RedeliveryStamp($retryCount, $throwable->getMessage(), FlattenException::createFromThrowable($throwable)));
```
Comment (monteiro) [inline src/Symfony/Component/Messenger/EventListener/SendFailedMessageForRetryListener.php:71]: @fabpot @weaverryan This will avoid the FlattenException to be null when retrying, in order to accommodate the changes on FlattenExceptionNormalizer.

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.xml (hunk 13 above)
Comment (monteiro) [reply src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.xml]: I need to put -800 in order for the normalize method to be executed.

File: src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php (hunk 2 above)
Comment (fabpot) [reply src/Symfony/Component/Serializer/Normalizer/FlattenExceptionNormalizer.php:40]: But here, you are using `$this`, you should use `$this->normalizer`, right?

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Messenger/Transport/Serialization/Serializer.php [hunk 18]
```diff
@@ -40,7 +41,7 @@ public function __construct(SymfonySerializerInterface $serializer = null, strin
     {
         $this->serializer = $serializer ?? self::create()->serializer;
         $this->format = $format;
-        $this->context = $context;
+        $this->context = $context + [self::MESSENGER_SERIALIZATION_CONTEXT => true];
```
Comment (fabpot) [inline src/Symfony/Component/Messenger/Transport/Serialization/Serializer.php:44]: I see that you changed your mind about this, but I would revert this. We should support normalization for all FlattenException instances.

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.xml [hunk 19]
```diff
@@ -82,7 +82,6 @@
             <tag name="serializer.normalizer" priority="-1000" />
         </service>
         <service id="Symfony\Component\Serializer\Normalizer\ObjectNormalizer" alias="serializer.normalizer.object" />
-
```
Comment (fabpot) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.xml:85]: Can be reverted

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/messenger.xml [hunk 20]
```diff
@@ -29,6 +29,10 @@
         </service>
         <service id="Symfony\Component\Messenger\Transport\Serialization\SerializerInterface" alias="messenger.default_serializer" />
 
+        <service id="serializer.normalizer.flatten_exception" class="Symfony\Component\Messenger\Transport\Serialization\Normalizer\FlattenExceptionNormalizer">
+            <tag name="serializer.normalizer" priority="-880" />
+        </service>
```
Comment (fabpot) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/messenger.xml:34]: I didn't realize that it was on 4.4. As this is a new feature, it should be moved to master instead, where the configuration should be moved to the new PHP config file.

**Review by fabpot — CHANGES_REQUESTED** [review]

**Comment by monteiro** [comment]
@fabpot , after talking with @weaverryan we agreed:
- Move the FlattenNormalizer to the Messenger component, because it is only used there
- Added specific context on the Messenger Serializer, so the normalizer knows when it's being used on a Messenger context, in favor of [ProblemNormalizer](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/ProblemNormalizer.php#L65), which also normalizes FlattenExceptions, but specific for APIs (not background processes) - That's why the priority is set to be higher than ProblemNormalizer.

Using this strategy:
- We don't affect the normal behavior of the default Symfony Serializer, because the normalizer is only executed by the Symfony Messenger serializer which sets a specific context.
- The normalizer will be instantiated if Messenger is installed.

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/messenger.xml (hunk 20 above)
Comment (monteiro) [reply src/Symfony/Bundle/FrameworkBundle/Resources/config/messenger.xml:34]: I considered this as a fix, because this breaks one of the Messenger commands, but I can move it to master if you consider this to be a feature.

File: src/Symfony/Component/Messenger/Transport/Serialization/Serializer.php (hunk 18 above)
Comment (monteiro) [reply src/Symfony/Component/Messenger/Transport/Serialization/Serializer.php:44]: I explained the why here: https://github.com/symfony/symfony/pull/37087#issuecomment-678079420

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/messenger.xml (hunk 20 above)
Comment (fabpot) [reply src/Symfony/Bundle/FrameworkBundle/Resources/config/messenger.xml:34]: This is a new feature as we are adding a class and changing behavior.

File: src/Symfony/Component/Messenger/Transport/Serialization/Serializer.php [hunk 21]
```diff
@@ -30,6 +30,7 @@
  */
 class Serializer implements SerializerInterface
 {
+    const MESSENGER_SERIALIZATION_CONTEXT = 'MESSENGER_SERIALIZATION';
```
Comment (fabpot) [inline src/Symfony/Component/Messenger/Transport/Serialization/Serializer.php:33]: should be `public const` and the value should probably be something lke `messenger_serialization`.

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/messenger.xml [hunk 22]
```diff
@@ -29,6 +29,10 @@
         </service>
         <service id="Symfony\Component\Messenger\Transport\Serialization\SerializerInterface" alias="messenger.default_serializer" />
 
+        <service id="serializer.normalizer.flatten_exception" class="Symfony\Component\Messenger\Transport\Serialization\Normalizer\FlattenExceptionNormalizer">
```
Comment (fabpot) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/messenger.xml:32]: This should be registered only if the messenger component is available.

**Review by fabpot — CHANGES_REQUESTED** [review]
I understand the reasoning. That works for me.

**Review by fabpot — APPROVED** [review]
Tests are broken because of the constraints in composer.json. I will fix it while merging.
