### PR TITLE
[DoctrineBridge] use non-reserved keyword as key column name, quote key value

### LINKED ISSUE #61699: [DoctrineBridge] doctrine:migrations:diff throws syntax error with mysql server
### Symfony version(s) affected

7.4.x-dev

### Description

Recent changes (#61582) broke `doctrine:migrations:diff` command for mysql.
Mysql throws syntax error, because word [key](https://dev.mysql.com/doc/refman/8.4/en/keywords.html#keywords-8-4-detailed-K) is reserved.

```
INSERT INTO _schema_subscriber_check (key) VALUES (:key)
```

```
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key) VALUES ('123')' at line 1
```

### How to reproduce

`bin/console doctrine:migrations:diff`with mysql

### Possible Solution

Use different column name

### Additional Context

bash-4.4# mysql --version
mysql  Ver 8.3.0 for Linux on x86_64 (MySQL Community Server - GPL)

Even if I manually change `key` to `mykey`, there is another error related to PDO parameters

```
In AbstractSchemaListener.php line 57:

  [ArgumentCountError]
  PDO::exec() expects exactly 1 argument, 3 given


Exception trace:
  at /var/www/html/vendor/symfony/doctrine-bridge/SchemaListener/AbstractSchemaListener.php:57
 PDO->exec() at /var/www/html/vendor/symfony/doctrine-bridge/SchemaListener/AbstractSchemaListener.php:57
 Symfony\Bridge\Doctrine\SchemaListener\AbstractSchemaListener::{closure:Symfony\Bridge\Doctrine\SchemaListener\AbstractSchemaListener::getIsSameDatabaseChecker():31}() at /var/www/html/vendor/symfony/http-foundation/Session/Storage/Handler/PdoSessionHandler.php:189
 Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler->configureSchema() at /var/www/html/vendor/symfony/doctrine-bridge/SchemaListener/PdoSessionHandlerSchemaListener.php:36
 Symfony\Bridge\Doctrine\SchemaListener\PdoSessionHandlerSchemaListener->postGenerateSchema() at /var/www/html/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:56
 Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent() at /var/www/html/vendor/doctrine/orm/src/Tools/SchemaTool.php:391
 Doctrine\ORM\Tools\SchemaTool->getSchemaFromMetadata() at /var/www/html/vendor/doctrine/migrations/src/Provider/OrmSchemaProvider.php:39
 Doctrine\Migrations\Provider\OrmSchemaProvider->createSchema() at /var/www/html/vendor/doctrine/migrations/src/Generator/DiffGenerator.php:129
 Doctrine\Migrations\Generator\DiffGenerator->createToSchema() at /var/www/html/vendor/doctrine/migrations/src/Generator/DiffGenerator.php:66
 Doctrine\Migrations\Generator\DiffGenerator->generate() at /var/www/html/vendor/doctrine/migrations/src/Tools/Console/Command/DiffCommand.php:142
 Doctrine\Migrations\Tools\Console\Command\DiffCommand->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:331
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Application.php:1124
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:123
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:359
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:77
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:194
 Symfony\Component\Console\Application->run() at /var/www/html/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /var/www/html/vendor/autoload_runtime.php:32
 require_once() at /var/www/html/bin/console:11
```

```
# composer show (deleted entries not related to doctrine/symfony)
doctrine/collections                      2.3.0             PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                           3.5.0             PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support, proxies and...
doctrine/dbal                             3.10.2            Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/deprecations                     1.1.5             A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to disable all deprecations or selectively for packages.
doctrine/doctrine-bundle                  2.16.1            Symfony DoctrineBundle
doctrine/doctrine-migrations-bundle       3.4.2             Symfony DoctrineMigrationsBundle
doctrine/event-manager                    2.0.1             The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                        2.1.0             PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of words.
doctrine/instantiator                     2.0.0             A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                            3.0.1             PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                       3.9.4             PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database schema and easily deployi...
doctrine/orm                              3.5.2             Object-Relational-Mapper for PHP
doctrine/persistence                      3.4.0             The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/sql-formatter                    1.5.2             a PHP SQL highlighting library
symfony/apache-pack                       1.0.1             A pack for Apache support in Symfony
symfony/asset                             7.4.x-dev 0f7bccb Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/asset-mapper                      7.4.x-dev 3779fc8 Maps directories of assets & makes them available in a public directory with versioned filenames.
symfony/browser-kit                       7.4.x-dev abec2fa Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/cache                             7.4.x-dev db34764 Provides extended PSR-6, PSR-16 (and tags) implementations
symfony/clock                             7.4.x-dev 9a2e07a Decouples applications from the system clock
symfony/config                            7.4.x-dev 3163c6f Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                           7.4.x-dev c5f6472 Eases the creation of beautiful and testable command line interfaces
symfony/contracts                         3.6.0             A set of abstractions extracted out of the Symfony components
symfony/css-selector                      7.4.x-dev 57500fe Converts CSS selectors to XPath expressions
symfony/debug-bundle                      7.4.x-dev b9ba1bf Provides a tight integration of the Symfony VarDumper component and the ServerLogCommand from MonologBridge into the Symfony full-stack framework
symfony/dependency-injection              7.4.x-dev 3f96eaa Allows you to standardize and centralize the way objects are constructed in your application
symfony/doctrine-bridge                   7.4.x-dev 7ba04b1 Provides integration for Doctrine with various Symfony components
symfony/doctrine-messenger                7.4.x-dev 6579fe2 Symfony Doctrine Messenger Bridge
symfony/dom-crawler                       7.4.x-dev d4e84f3 Eases DOM navigation for HTML and XML documents
symfony/dotenv                            7.4.x-dev 4a53037 Registers environment variables from a .env file
symfony/error-handler                     7.4.x-dev 9463892 Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher                  7.4.x-dev c511634 Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/expression-language               7.4.x-dev b53192c Provides an engine that can compile and evaluate expressions
symfony/filesystem                        7.4.x-dev 633c6fd Provides basic utilities for the filesystem
symfony/finder                            7.4.x-dev 57861c3 Finds files and directories via an intuitive fluent interface
symfony/flex                              2.8.2             Composer plugin for Symfony
symfony/form                              7.4.x-dev 9e63e78 Allows to easily create, process and reuse HTML forms
symfony/framework-bundle                  7.4.x-dev 3e27438 Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/html-sanitizer                    7.4.x-dev f975cb5 Provides an object-oriented API to sanitize untrusted HTML input for safe insertion into a document's DOM.
symfony/http-client                       7.4.x-dev 9a33f2d Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-foundation                   7.4.x-dev 3a978ec Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                       7.4.x-dev 696a0bc Provides a structured process for converting a Request into a Response
symfony/intl                              7.4.x-dev b6a7f63 Provides access to the localization data of the ICU library
symfony/mailer                            7.4.x-dev 676b5e6 Helps sending emails
symfony/maker-bundle                      1.64.0            Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/messenger                         7.4.x-dev beb743d Helps applications send and receive messages to/from other applications or via message queues
symfony/mime                              7.4.x-dev ece5f0d Allows manipulating MIME messages
symfony/monolog-bridge                    7.4.x-dev a1f3b4f Provides integration for Monolog with various Symfony components
symfony/monolog-bundle                    3.10.0            Symfony MonologBundle
symfony/options-resolver                  7.4.x-dev 3324bca Provides an improved replacement for the array_replace PHP function
symfony/password-hasher                   7.4.x-dev aa075ce Provides password hashing utilities
symfony/phpunit-bridge                    7.3.3             Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-intl-grapheme            1.33.0            Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu                 1.33.0            Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn                 1.33.0            Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer          1.33.0            Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-php83                    1.33.0            Symfony polyfill backporting some PHP 8.3+ features to lower PHP versions
symfony/polyfill-php85                    1.33.0            Symfony polyfill backporting some PHP 8.5+ features to lower PHP versions
symfony/polyfill-uuid                     1.33.0            Symfony polyfill for uuid functions
symfony/process                           7.4.x-dev c61e87d Executes commands in sub-processes
symfony/property-access                   7.4.x-dev 5376261 Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info                     7.4.x-dev 4702a9b Extracts information about PHP class' properties using metadata of popular sources
symfony/psr-http-message-bridge           7.4.x-dev 1f92ca7 PSR HTTP message bridge
symfony/rate-limiter                      7.4.x-dev 5c6df5b Provides a Token Bucket implementation to rate limit input and output in your application
symfony/requirements-checker              2.0.3             Check Symfony requirements and give recommendations
symfony/routing                           7.4.x-dev 02f4eef Maps an HTTP request to a set of configuration variables
symfony/runtime                           7.4.x-dev be29914 Enables decoupling PHP applications from global state
symfony/security-acl                      3.3.4             Symfony Security Component - ACL (Access Control List)
symfony/security-bundle                   7.4.x-dev 064663d Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core                     7.4.x-dev ab924e5 Symfony Security Component - Core Library
symfony/security-csrf                     7.4.x-dev d747f30 Symfony Security Component - CSRF Library
symfony/security-http                     7.4.x-dev 34c139d Symfony Security Component - HTTP Integration
symfony/serializer                        7.4.x-dev a20610c Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/stimulus-bundle                   2.30.0            Integration with your Symfony app & Stimulus!
symfony/stopwatch                         7.4.x-dev 8a24af0 Provides a way to profile code
symfony/string                            7.4.x-dev 7c89aba Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                       7.4.x-dev cfd2401 Provides tools to internationalize your application
symfony/twig-bridge                       7.4.x-dev e9c4ff3 Provides integration for Twig with various Symfony components
symfony/twig-bundle                       7.4.x-dev 0c1ce54 Provides a tight integration of Twig into the Symfony full-stack framework
symfony/type-info                         7.4.x-dev 52d5a7f Extracts PHP types information.
symfony/uid                               7.4.x-dev 70ab8ca Provides an object-oriented API to generate and represent UIDs
symfony/ux-autocomplete                   2.30.0            JavaScript Autocomplete functionality for Symfony
symfony/ux-icons                          2.30.0            Renders local and remote SVG icons in your Twig templates.
symfony/ux-leaflet-map                    2.30.0            Symfony UX Map Leaflet Bridge
symfony/ux-live-component                 2.30.0            Live components for Symfony
symfony/ux-map                            2.30.0            Easily embed interactive maps in your Symfony application
symfony/ux-turbo                          2.30.0            Hotwire Turbo integration for Symfony
symfony/ux-twig-component                 2.30.0            Twig components for Symfony
symfony/ux-vue                            2.30.0            Integration of Vue.js in Symfony
symfony/validator                         7.4.x-dev 0d123f3 Provides tools to validate values
symfony/var-dumper                        7.4.x-dev 243a83b Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter                      7.4.x-dev 8b01877 Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                          7.4.x-dev c62edd6 Manages links between resources
symfony/web-profiler-bundle               7.4.x-dev 36bfe58 Provides a development tool that gives detailed information about the execution of any request
symfony/yaml                              7.4.x-dev 87fee1e Loads and dumps YAML files
```

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #61699
| License       | MIT

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php [hunk 1]
```diff
@@ -54,7 +54,8 @@ protected function getIsSameDatabaseChecker(Connection $connection): \Closure
             $connection->executeStatement('INSERT INTO _schema_subscriber_check (key) VALUES (:key)', ['key' => $key], ['key' => Types::STRING]);
 
             try {
-                $exec('DELETE FROM _schema_subscriber_check WHERE key == :key', ['key' => $key], ['key' => Types::STRING]);
+                $platform = $connection->getDatabasePlatform();
+                $exec(\sprintf("DELETE FROM _schema_subscriber_check WHERE %s == %s", $platform->quoteSingleIdentifier('key'), $platform->quoteStringLiteral($key)));
```
Comment (xabbuh) [inline src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php]: we need to build the full SQL here as we don't have control about how the closure referenced with `$exec` is shaped, e.g. it can be `PDO::exec()`:https://github.com/symfony/symfony/blob/608e126bcc6fa58eac68d49cff47ab23c913dc47/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php#L189)

**Review by GromNaN — APPROVED** [review]
Good point, thank you.

File: src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php (hunk 1 above)
Comment (stof) [reply src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php]: I suggest adding phpdoc describing the signature of the expected callback, to make our expectation clearer:

```
@return \Closure(\Closure(string): mixed): bool
```

Psalm might even be able to ensure that future contributions will respect the correct usage.

**Review by fbuchlak — APPROVED** [review]

File: src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php (hunk 1 above)
Comment (xabbuh) [reply src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php]: good idea, done

File: src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php [hunk 2]
```diff
@@ -51,15 +54,16 @@ protected function getIsSameDatabaseChecker(Connection $connection): \Closure
...
 
             try {
-                $exec('DELETE FROM _schema_subscriber_check WHERE key == :key', ['key' => $key], ['key' => Types::STRING]);
+                $exec(\sprintf('DELETE FROM _schema_subscriber_check WHERE %s = %s', $platform->quoteSingleIdentifier('key'), $platform->quoteStringLiteral($key)));
             } catch (DatabaseObjectNotFoundException|ConnectionException) {
             }
 
             try {
-                return !$connection->executeStatement('DELETE FROM _schema_subscriber_check WHERE key == :key', ['key' => $key], ['key' => Types::STRING]);
+                return !$connection->executeStatement(\sprintf('DELETE FROM _schema_subscriber_check WHERE %s = %s', $platform->quoteSingleIdentifier('key'), $platform->quoteStringLiteral($key)));
```
Comment (stof) [inline src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php]: as `$connection` is known to be a DBAL connection, we should keep using a prepared parameter for the value rather than concatenating a literal in the SQL here IMO.

Comment (stof) [reply src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php]: same for the `INSERT` above btw.

Comment (GromNaN) [reply src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php]: The `key` need to be escaped. But we can change to an other field name to avoid the "reserved word" issue.

Comment (stof) [reply src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php]: I'm talking about the field value here, not the field name.

But indeed, for the field name, we could simplify things by using a field name that is not reserved.

Comment (xabbuh) [reply src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php]: Any preference?

Comment (GromNaN) [reply src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php]: Anything that will not a reserved keyword: `random_key`?

**Review by GromNaN — APPROVED** [review]

**Review by mtarld — APPROVED** [review]

File: src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php (hunk 2 above)
Comment (andersonamuller) [reply src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php]: How about `token`?

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

File: src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php (hunk 2 above)
Comment (GromNaN) [reply src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php]: @andersonamuller That would work too, but it doesn't matter.
