### PR TITLE
[Form] Fixed: Filter non-integers when selecting entities by int ID

### LINKED ISSUE #14583: [form] error when submitting empty value in for using model choice list
I think that's happening only on propel + postgres after @webmozart removed empty/null checks from ChoiceToValueTransformer in https://github.com/symfony/symfony/commit/1d89922782922fe3bcacb09f91e8c3c992d29d3f

ModelChoiceList->getChoicesForValues allows to create Propel query with empty string values which are not accepted, so I'm getting:
```
Unable to execute SELECT statement [SELECT (...) FROM twilio_number WHERE twilio_number.id IN (:p1)] [wrapped: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: ""]
```

the code below (for propel bridge) seems to do the trick, but I'm not sure if I can create PR for the Propel1Bridge repository. Will appreciate any help.

```
class ModelChoiceList extends ObjectChoiceList

    public function getChoicesForValues(array $values)
    {
        if (empty($values) || empty($first = reset($values))) {
            return array();
        }
```

### PR DESCRIPTION
**Pull request by webmozart**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14583 (for Doctrine, not Propel) |
| License | MIT |
| Doc PR | - |

This PR fixes #14583 for Doctrine. Non-integer values (like `""`) are not passed to the database anymore when selecting entities by integer PK, which causes an error on some DBMSs (like PostgreSQL).

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php [hunk 1]
```diff
@@ -99,6 +99,13 @@ public function getEntitiesByIds($identifier, array $values)
         $metadata = $qb->getEntityManager()->getClassMetadata($entity);
         if (in_array($metadata->getTypeOfField($identifier), array('integer', 'bigint', 'smallint'))) {
             $parameterType = Connection::PARAM_INT_ARRAY;
+
+            // Filter out non-integer values (e.g. ""). If we don't, some
+            // databases such as PostgreSQL fail.
+            // https://github.com/symfony/symfony/issues/14583
```
Comment (fabpot) [inline src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php]: This reference should be removed. It will be part of the merge commit anyway with the full discussion.

**Comment by fabpot** [comment]
Does it replace #14617?

**Comment by webmozart** [comment]
Yes, I closed that issue. The PR is updated now.

**Comment by fabpot** [comment]
Thank you @webmozart.

**Comment by althaus** [comment]
It's a pity that this fix isn't part of the 2.7.1 release. So there's still a BC break. :disappointed:

**Comment by nicolas-grekas** [comment]
Shouldn't this one go in 2.6 also?
BTW, this broke the tests on the 2.7 branch: for some reason, older versions of DBAL can't handle an empty list of identifiers. We should workaround.

**Comment by stof** [comment]
an empty list of identifiers should skip the DB query entirely anyway, even if newer DBAL versions can handle them. We already know it won't return anything

**Comment by webmozart** [comment]
@nicolas-grekas Good point, can you work on a backport? Handling empty arrays properly across DBMS should be a Doctrine issue no?

**Comment by nicolas-grekas** [comment]
See #15027

**Comment by stof** [comment]
@webmozart this has been solved in DBAL. But not backported to EOMed versions

**Comment by murilolobato** [comment]
My symfony requirement in composer.json is "~2.7", after a composer update I received symfony 2.7.1, and I'm still experiencing this issue, of sql error when submit the entity field blank. This problem is solved in which version of symfony?

**Comment by althaus** [comment]
@murilolobato The fix is merged, but not released yet. :disappointed:

**Comment by zefrog** [comment]
Can we have a release for this? At least an expected release date? This is quite annoying...

**Comment by matudelatower** [comment]
@zefrog already in the new version 2.7.2

**Comment by murilolobato** [comment]
How the release process works? Fabien is who generates the new tag? There is any documentation for this? So we can follow more precisely the process.

**Comment by phansys** [comment]
@murilolobato, please read this doc entry about the [release process](https://symfony.com/doc/current/contributing/community/releases.html).

**Comment by murilolobato** [comment]
My fault to not give the correct attention to [Contributing to Symfony](http://symfony.com/doc/current/contributing/index.html) part of documentation. I read it completely now, and all my doubts are answered now.
