### PR TITLE
[Console] add support for catching `\Throwable` errors

### LINKED ISSUE #46596: No catch Throwable errors
### Symfony version(s) affected

6.0

### Description

```       try {
            $exitCode = $this->doRun($input, $output);
        } catch (\Exception $e) {
            if (!$this->catchExceptions) {
                throw $e;
            }
```

Current code: https://github.com/symfony/console/blob/c9646197ef43b0e2ff44af61e7f0571526fd4170/Application.php#L172

Command exception handler skips type errors Throwable

### How to reproduce

Raise an exception that throws an exception not of type Exception

### Possible Solution

Change type to Throwable 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #46596
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by ghost** [comment]
Historical question: were all the `try..catch` blocks in the Symfony code base modified from `\Exception` to `\Throwable` after the latter had been introduced? I can still see blocks that catch \Exception and I wonder if this is just an oversight or there is a reason behind this.

**Review by maxbeckers — APPROVED** [review]
LGTM

**Review by chalasr — CHANGES_REQUESTED** [review]
The broken test covers the behavior for which we cannot just do this unfortunately. Check https://github.com/symfony/symfony/pull/22690 for background (tldr  errors must keep reaching custom error handlers).

**Comment by lyrixx** [comment]
Hmm, When using the component directly without the error handler, a command can crash badly :/ 

What about adding a flag to choose if we should handle throwable or not?

**Comment by chalasr** [comment]
Sounds like a good idea 👍

**Comment by nicolas-grekas** [comment]
The very lines before the try/catch setup a global error/exception handler, why does this crash badly as you write, while we have this in place?

**Comment by lyrixx** [comment]
@nicolas-grekas let's say you are building a project that run commands, when someone makes an error in the command, it will produces theses outputs:


### Without this patch:

```
>/tmp/foobar foobar  hello
PHP Fatal error:  Uncaught Error: Call to undefined function hello2() in /tmp/foobar/foobar.php:9
Stack trace:
#0 [internal function]: hello()
#1 /home/gregoire/dev/github.com/jolicode/foobar/src/Console/Command/TaskCommand.php(152): ReflectionFunction->invoke()
#2 /home/gregoire/dev/github.com/jolicode/foobar/vendor/symfony/console/Command/Command.php(326): Foobar\Console\Command\TaskCommand->execute()
#3 /home/gregoire/dev/github.com/jolicode/foobar/vendor/symfony/console/Application.php(1063): Symfony\Component\Console\Command\Command->run()
#4 /home/gregoire/dev/github.com/jolicode/foobar/src/Console/Application.php(57): Symfony\Component\Console\Application->doRunCommand()
#5 /home/gregoire/dev/github.com/jolicode/foobar/vendor/symfony/console/Application.php(320): Foobar\Console\Application->doRunCommand()
#6 /home/gregoire/dev/github.com/jolicode/foobar/src/Console/Application.php(45): Symfony\Component\Console\Application->doRun()
#7 /home/gregoire/dev/github.com/jolicode/foobar/vendor/symfony/console/Application.php(174): Foobar\Console\Application->doRun()
#8 /home/gregoire/dev/github.com/jolicode/foobar/src/Console/ApplicationFactory.php(28): Symfony\Component\Console\Application->run()
#9 /home/gregoire/dev/github.com/jolicode/foobar/bin/foobar(14): Foobar\Console\ApplicationFactory::run()
#10 {main}
  thrown in /tmp/foobar/foobar.php on line 9

Fatal error: Uncaught Error: Call to undefined function hello2() in /tmp/foobar/foobar.php:9
Stack trace:
#0 [internal function]: hello()
#1 /home/gregoire/dev/github.com/jolicode/foobar/src/Console/Command/TaskCommand.php(152): ReflectionFunction->invoke()
#2 /home/gregoire/dev/github.com/jolicode/foobar/vendor/symfony/console/Command/Command.php(326): Foobar\Console\Command\TaskCommand->execute()
#3 /home/gregoire/dev/github.com/jolicode/foobar/vendor/symfony/console/Application.php(1063): Symfony\Component\Console\Command\Command->run()
#4 /home/gregoire/dev/github.com/jolicode/foobar/src/Console/Application.php(57): Symfony\Component\Console\Application->doRunCommand()
#5 /home/gregoire/dev/github.com/jolicode/foobar/vendor/symfony/console/Application.php(320): Foobar\Console\Application->doRunCommand()
#6 /home/gregoire/dev/github.com/jolicode/foobar/src/Console/Application.php(45): Symfony\Component\Console\Application->doRun()
#7 /home/gregoire/dev/github.com/jolicode/foobar/vendor/symfony/console/Application.php(174): Foobar\Console\Application->doRun()
#8 /home/gregoire/dev/github.com/jolicode/foobar/src/Console/ApplicationFactory.php(28): Symfony\Component\Console\Application->run()
#9 /home/gregoire/dev/github.com/jolicode/foobar/bin/foobar(14): Foobar\Console\ApplicationFactory::run()
#10 {main}
  thrown in /tmp/foobar/foobar.php on line 9
```

### With this patch (there is color, and Symfony styling):
```
>/tmp/foobar foobar  hello

In foobar.php line 9:
                                       
  Call to undefined function hello2()  
                                       

hello

```

And if the developer wants more output, they can run the same command with `-v` flags

**Comment by lyrixx** [comment]
Very simple reproducer : 

take only symfony/console, then run:

```php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\SingleCommandApplication;

(new SingleCommandApplication())
    ->setCode(function () {
        echo "AAA";
        foobar();
    })
    ->run()
;
```

**Comment by lyrixx** [comment]
I have rebased the PR, restored BC, added a new flag to handle errors, and added some tests.

I think it's ready ✅

File: src/Symfony/Component/Console/Application.php [hunk 1]
```diff
@@ -172,10 +173,13 @@ public function run(InputInterface $input = null, OutputInterface $output = null
 
         try {
             $exitCode = $this->doRun($input, $output);
-        } catch (\Exception $e) {
+        } catch (\Throwable $e) {
             if (!$this->catchExceptions) {
                 throw $e;
             }
+            if (!$e instanceof \Exception && !$this->catchErrors) {
```
Comment (GromNaN) [inline src/Symfony/Component/Console/Application.php:180]: Instead of the `instanceof`, why not having 2 `catch`?

```php
try {
} catch (\Exception $e) {
    if (!$this->catchExceptions) {
        throw $e;
    }
} catch (\Throwable $e) {
    if (!$this->catchErrors) {
        throw $e;
    }
}
```

Someone may want to catch errors but not exceptions, who knows.

File: src/Symfony/Component/Console/CHANGELOG.md [hunk 2]
```diff
@@ -6,6 +6,7 @@ CHANGELOG
 
  * Add `SignalMap` to map signal value to its name
  * Multi-line text in vertical tables is aligned properly
+ * The application can also catch `\Throwable` exceptions
```
Comment (GromNaN) [inline src/Symfony/Component/Console/CHANGELOG.md]:
```suggestion
 * The application can also catch errors with `Application::setCatchErrors(true)`
```

File: src/Symfony/Component/Console/Application.php (hunk 1 above)
Comment (lyrixx) [reply src/Symfony/Component/Console/Application.php:180]: But we want the exception handling in the `} catch (\Exception $e) {` part. With your code we loose this feature.

File: src/Symfony/Component/Console/CHANGELOG.md (hunk 2 above)
Comment (lyrixx) [reply src/Symfony/Component/Console/CHANGELOG.md]: Thanks

File: src/Symfony/Component/Console/Application.php (hunk 1 above)
Comment (GromNaN) [reply src/Symfony/Component/Console/Application.php:180]: Indeed, I didn't pay much attention to that. You could factor the error handling into a function, but that wouldn't be any better. Let's keep it that way.

**Review by GromNaN — APPROVED** [review]

File: src/Symfony/Component/Console/CHANGELOG.md [hunk 3]
```diff
@@ -6,6 +6,7 @@ CHANGELOG
 
  * Add `SignalMap` to map signal value to its name
  * Multi-line text in vertical tables is aligned properly
+ * The application can also catch errors with `Application::setCatchErrors(true)`
```
Comment (chalasr) [inline src/Symfony/Component/Console/CHANGELOG.md:9]: It would be nice to describe a bit in which case it is useful, here and on the setter docblock

**Review by derrabus — APPROVED** [review]

File: src/Symfony/Component/Console/CHANGELOG.md (hunk 3 above)
Comment (lyrixx) [reply src/Symfony/Component/Console/CHANGELOG.md:9]: For the PHP Docs, I copied the one from `setCatchExceptions()`. And usually, we don't put description about usages in CHANGELOG, does'nt?

File: src/Symfony/Component/Console/Application.php [hunk 4]
```diff
@@ -172,10 +173,13 @@ public function run(InputInterface $input = null, OutputInterface $output = null
 
         try {
             $exitCode = $this->doRun($input, $output);
-        } catch (\Exception $e) {
+        } catch (\Throwable $e) {
             if (!$this->catchExceptions) {
```
Comment (chalasr) [inline src/Symfony/Component/Console/Application.php]: what if `$e` is an `\Error` and `$this->catchErrors` is `true`?

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @lyrixx.

**Comment by chalasr** [comment]
@Seldaek FYI

**Comment by Seldaek** [comment]
@chalasr thanks for the ping, see https://github.com/composer/composer/commit/f4738d97b (I guess that's why you pinged me :)
