### PR TITLE
[HttpKernel] Skip corrupted CSV data in FileProfilerStorage

### LINKED ISSUE #50942: Web Profiler inconsistent error - Undefined array key 4
### Symfony version(s) affected

6.3.1

### Description

Very occassionally, when navigating '/logout' (302 redirect) '/' (302 redirect) '/login, I get the following errors:

```
ErrorException:
Warning: Undefined array key 4

  at symfony\http-kernel\Profiler\FileProfilerStorage.php:312
  at Symfony\Component\HttpKernel\Profiler\FileProfilerStorage->removeExpiredProfiles()
  at Symfony\Component\HttpKernel\Profiler\FileProfilerStorage->write()
  at Symfony\Component\HttpKernel\Profiler\Profiler->saveProfile()
  at Symfony\Component\HttpKernel\EventListener\ProfilerListener->onKernelTerminate()
``` and ```
BadMethodCallException:
Symfony\Component\VarDumper\Cloner\Data objects are immutable.

in symfony\var-dumper\Cloner\Data.php (line 152)
Data->offsetSet() in symfony\http-kernel\DataCollector\EventDataCollector.php (line 92)
EventDataCollector->setCalledListeners() in symfony\http-kernel\DataCollector\EventDataCollector.php (line 74)
EventDataCollector->lateCollect() in symfony\http-kernel\Profiler\Profiler.php (line 100)
Profiler->saveProfile() in symfony\http-kernel\EventListener\ProfilerListener.php (line 135)
ProfilerListener->onKernelTerminate() in symfony\event-dispatcher\Debug\WrappedListener.php (line 116)
WrappedListener->__invoke() in symfony\event-dispatcher\EventDispatcher.php (line 220)
```

The interesting thing (maybe?) is that '/login' returns HTTP 200, but it looks like the AJAX request is failing? But I don't have any entries in the developer console for any ajax requests... And yet the page output looks like this:
image

### How to reproduce

No idea how to reproduce, as it's inconsistent. I'm assuming it's a delay with the file system, maybe? I don't know.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by radar3301**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Partially fixes #50942, improves/fixes on PR #50913, partially fixes #50816
| License       | MIT

Technically, part of this fix could go all the way back to 2.1, but since we're not sure why/how exactly the index.csv file is being corrupted in the first place, this PR should just serve as a stop-gap measure until the root cause can be identified.

A corrupted index.csv file is especially noticeable since 6.3, when the "Remove Expired Profiles" feature was added by #47352 .

RE: improves/fixes on PR #50913:
Warnings are (usually?) only escalated to errors in debug mode, so having a try/catch is a bit more overhead than I think is actually needed, and I believe just checking that the line read from the csv is not corrupted is the better/faster option. Granted, the profiler should really only be active in debug/non-production modes anyway, but "should" and reality usually don't align...

@alamirault @MatTheCat @benjaminfunk @Pelagoss @derrabus

### CODE REVIEW

**Comment by derrabus** [comment]
Thank you. Please pick a more meaningful PR title and add a test.

**Comment by radar3301** [comment]
> Thank you. Please pick a more meaningful PR title

Done. No idea how I didn't see that.

> and add a test.

Sorry, but I'm not going to write 50+ lines of code of unit test for such a trivial 2 LoC sanity check...

File: src/Symfony/Component/HttpKernel/Profiler/FileProfilerStorage.php [hunk 1]
```diff
@@ -56,6 +56,12 @@ public function find(?string $ip, ?string $url, ?int $limit, ?string $method, in
         $result = [];
         while (\count($result) < $limit && $line = $this->readLineFromFile($file)) {
             $values = str_getcsv($line);
+
+            if (count($values) < 7) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Profiler/FileProfilerStorage.php]:
```suggestion
            if (\count($values) < 7) {
```

File: src/Symfony/Component/HttpKernel/Profiler/FileProfilerStorage.php [hunk 2]
```diff
@@ -309,7 +315,14 @@ private function removeExpiredProfiles(): void
         }
 
         while ($line = fgets($handle)) {
-            [$csvToken, , , , $csvTime] = str_getcsv($line);
+            $values = str_getcsv($line);
+
+            if (count($values) < 4) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Profiler/FileProfilerStorage.php]: 7 is still the correct number of items in a well formatted:
```suggestion
            if (\count($values) < 7) {
```

**Comment by nicolas-grekas** [comment]
Thank you @radar3301.
