### PR TITLE
[DependencyInjection] Fix "Cannot replace arguments" errors caused by ResolveAutowireInlineAttributesPass

### LINKED ISSUE #54823: [DependencyInjection] Can not replace arguments if none have been configured yet - InlineAutowire
### Symfony version(s) affected

7.1

### Description

Cache clear drops: 

```
  [Symfony\Component\DependencyInjection\Exception\OutOfBoundsException]
  Service "ApiPlatform\Tests\Behat\DoctrineContext": Cannot replace arguments for class "ApiPlatform\Tests\Behat\DoctrineContext" if none have been configured yet.

Exception trace:
  at /symfony/dependency-injection/Definition.php:257
 Symfony\Component\DependencyInjection\Definition->replaceArgument() at /symfony/dependency-injection/Compiler/ResolveChildDefinitionsPass.php:167
 Symfony\Component\DependencyInjection\Compiler\ResolveChildDefinitionsPass->doResolveDefinition() at /symfony/dependency-injection/Compiler/ResolveChildDefinitionsPass.php:63
 Symfony\Component\DependencyInjection\Compiler\ResolveChildDefinitionsPass->resolveDefinition() at /symfony/dependency-injection/Compiler/ResolveChildDefinitionsPass.php:46
 Symfony\Component\DependencyInjection\Compiler\ResolveChildDefinitionsPass->processValue() at /symfony/dependency-injection/Compiler/AbstractRecursivePass.php:84
 Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() at /symfony/dependency-injection/Compiler/ResolveChildDefinitionsPass.php:37
 Symfony\Component\DependencyInjection\Compiler\ResolveChildDefinitionsPass->processValue() at /symfony/dependency-injection/Compiler/AbstractRecursivePass.php:45
 Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process() at /symfony/dependency-injection/Compiler/Compiler.php:73
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /symfony/dependency-injection/ContainerBuilder.php:752
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /symfony/http-kernel/Kernel.php:495
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /symfony/http-kernel/Kernel.php:732
 Symfony\Component\HttpKernel\Kernel->preBoot() at /symfony/http-kernel/Kernel.php:120
 Symfony\Component\HttpKernel\Kernel->boot() at /symfony/http-kernel/Kernel.php:135
 Symfony\Component\HttpKernel\Kernel->reboot() at /symfony/framework-bundle/Command/CacheClearCommand.php:229
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at /symfony/framework-bundle/Command/CacheClearCommand.php:141
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /symfony/console/Command/Command.php:279
 Symfony\Component\Console\Command\Command->run() at /symfony/console/Application.php:1047
 Symfony\Component\Console\Application->doRunCommand() at /symfony/framework-bundle/Console/Application.php:123
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /symfony/console/Application.php:316
 Symfony\Component\Console\Application->doRun() at /symfony/framework-bundle/Console/Application.php:77
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /symfony/console/Application.php:167
 Symfony\Component\Console\Application->run() at tests/Fixtures/app/console:36

cache:clear [--no-warmup] [--no-optional-warmers]
```

### How to reproduce

```
git clone git@github.com:api-platform/core
composer config minimum-stability dev
php -d memory_limit=-1 tests/Fixtures/app/console cache:clear --ansi
```

But actually the service declaration is as simple as:

```
services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    ApiPlatform\Tests\Behat\DoctrineContext:
        $doctrine: '@doctrine'
```

### Possible Solution

I tracked the bug to:

https://github.com/symfony/symfony/blob/820382cf9148356bb5f0acd4526030f60373009d/src/Symfony/Component/DependencyInjection/Compiler/ResolveAutowireInlineAttributesPass.php#L50-L52

Probably that this pass should be done later on? Not sure what AutowireInline actually tries to fix. 

If I may also the code change at https://github.com/symfony/symfony/commit/b9a838e61b297cca95b4ad0bd14d0617b2b55eb6#diff-a0f563695b61a31b6e2bee8d55d019b52326c245667db02ba878a2a878d78b98 should be commented as it's hard to know why the sudden change of testing for `.` as first char of the service name

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54823
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Compiler/ResolveAutowireInlineAttributesPass.php [hunk 1]
```diff
@@ -52,18 +52,13 @@ protected function processValue(mixed $value, bool $isRoot = false): mixed
             }
         }
 
-        $dummy = $value;
-        while (null === $dummy->getClass() && $dummy instanceof ChildDefinition) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/ResolveAutowireInlineAttributesPass.php:56]: this is dead code: definitions with no class are already skipped before (and that's legit for child definitions too)

File: src/Symfony/Component/DependencyInjection/Compiler/ResolveAutowireInlineAttributesPass.php [hunk 2]
```diff
@@ -89,19 +84,14 @@ private function registerAutowireInlineAttributes(\ReflectionFunctionAbstract $m
         if ($method->isVariadic()) {
             array_pop($parameters);
         }
-        $dummyContainer = new ContainerBuilder($this->container->getParameterBag());
+        $paramResolverContainer = new ContainerBuilder($this->container->getParameterBag());
 
         foreach ($parameters as $index => $parameter) {
             if ($isChildDefinition) {
                 $index = 'index_'.$index;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/ResolveAutowireInlineAttributesPass.php:91]: Renaming of indexes for child definitions is what caused the issue.
The patch fixes this using named arguments instead, which means using Definition::setArgument() instead of replaceArgument() when resolving child definitions.

**Review by GromNaN — APPROVED** [review]
This fixes the issue and the test is perfect.

**Review by derrabus — APPROVED** [review]
This patch fixes the issue for me. Thank you!

**Comment by derrabus** [comment]
Thank you Nicolas for taking care of this regression.
