### PR TITLE
[FrameworkBundle] Fix config builder with extensions extended in `build()`

### LINKED ISSUE #53987: FirewallConfig::customAuthenticators() method does not exist: cannot configure CustomAuthenticator via PHP
### Symfony version(s) affected

5.4.x

### Description

The `customAuthenticators()` method does not exist on `FirewallConfig`. I can use yaml with `custom_authenticator`, but it seems impossible via PHP config using the `FirewallConfig` object. If you simply pass an array configuration to ContainerConfig with `custom_authenticators` it works, but there are benefits to using the config objects. I’ve tried the verbatim config from the documentation and it doesn’t work:

https://symfony.com/doc/5.x/security/custom_authenticator.html

I see no `customAuthebticators()` method anywhere in symfony core. The `FirewallConfig` I’m using is under `var/cache/dev/Symfony/Config/`

### How to reproduce

Use the exact code from documentation

```
use App\Security\ApiKeyAuthenticator;
use Symfony\Config\SecurityConfig;

return static function (SecurityConfig $security) {
    $security->enableAuthenticatorManager(true);
    // ....

    $security->firewall('main')
        ->customAuthenticators([ApiKeyAuthenticator::class])
    ;
};
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #53987
| License       | MIT

The problem is caused by the fact that the Security bundle configuration can be extended in any `Bundle::build()` or the `Kernel::build()` methods.

### CODE REVIEW

**Comment by arderyp** [comment]
@HypeMC this solves the bug for me!  Thank you so much for the quick fix!

File: src/Symfony/Bundle/FrameworkBundle/CacheWarmer/ConfigBuilderCacheWarmer.php [hunk 1]
```diff
@@ -47,14 +47,17 @@ public function __construct(KernelInterface $kernel, ?LoggerInterface $logger =
...
+            $containerBuilder = $this->getContainerBuilder();
+            $this->prepareContainer($containerBuilder);
 
-        foreach ($this->kernel->getBundles() as $bundle) {
-            $extension = $bundle->getContainerExtension();
-            if (null === $extension) {
-                continue;
-            }
+            return $containerBuilder;
+        }, $this->kernel, \get_class($this->kernel))();
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/CacheWarmer/ConfigBuilderCacheWarmer.php]:
```suggestion
        }, null, $this->kernel)($this->kernel);
```

Comment (HypeMC) [reply src/Symfony/Bundle/FrameworkBundle/CacheWarmer/ConfigBuilderCacheWarmer.php]: Done

**Comment by arderyp** [comment]
@HypeMC @nicolas-grekas I think the latest change is throwing an error for me.  On cache clear:

```
./bin/console cache:clear
Symfony\Component\ErrorHandler\Error\ClassNotFoundError^ {#213
  #message: """
    Attempted to load class "AddExpressionLanguageProvidersPass" from namespace "Symfony\Component\Routing\DependencyInjection".\n
    Did you forget a "use" statement for e.g. "Symfony\Bundle\SecurityBundle\DependencyInjection\Compiler\AddExpressionLanguageProvidersPass" or "Sensio\Bundle\FrameworkExtraBundle\DependencyInjection\Compiler\AddExpressionLanguageProvidersPass"?
    """
  #code: 0
  #file: "./vendor/symfony/framework-bundle/FrameworkBundle.php"
  #line: 149
  trace: {
    ./vendor/symfony/framework-bundle/FrameworkBundle.php:149 { …}
    ./vendor/symfony/http-kernel/Kernel.php:676 { …}
    ./vendor/symfony/http-kernel/Kernel.php:647 { …}
    ./vendor/symfony/http-kernel/Kernel.php:545 { …}
    ./vendor/symfony/http-kernel/Kernel.php:789 { …}
    ./vendor/symfony/http-kernel/Kernel.php:128 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:179 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:71 { …}
    ./vendor/symfony/console/Application.php:171 { …}
    ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54 { …}
    ./vendor/autoload_runtime.php:35 { …}
    ./bin/console:11 {
      › 
      › require_once dirname(__DIR__).'/vendor/autoload_runtime.php';
      › 
      arguments: {
        "/home/arderyp/code/git/coeadmin/cee-sf-admin/vendor/autoload_runtime.php"
      }
    }
  }
}
2024-02-19T18:54:29+00:00 [critical] Uncaught Error: Class "Symfony\Component\Routing\DependencyInjection\AddExpressionLanguageProvidersPass" not found
```

**Comment by arderyp** [comment]
@HypeMC @nicolas-grekas I think the latest change is throwing an error for me.  On cache clear:

```
./bin/console cache:clear
Symfony\Component\ErrorHandler\Error\ClassNotFoundError^ {#213
  #message: """
    Attempted to load class "AddExpressionLanguageProvidersPass" from namespace "Symfony\Component\Routing\DependencyInjection".\n
    Did you forget a "use" statement for e.g. "Symfony\Bundle\SecurityBundle\DependencyInjection\Compiler\AddExpressionLanguageProvidersPass" or "Sensio\Bundle\FrameworkExtraBundle\DependencyInjection\Compiler\AddExpressionLanguageProvidersPass"?
    """
  #code: 0
  #file: "./vendor/symfony/framework-bundle/FrameworkBundle.php"
  #line: 149
  trace: {
    ./vendor/symfony/framework-bundle/FrameworkBundle.php:149 { …}
    ./vendor/symfony/http-kernel/Kernel.php:676 { …}
    ./vendor/symfony/http-kernel/Kernel.php:647 { …}
    ./vendor/symfony/http-kernel/Kernel.php:545 { …}
    ./vendor/symfony/http-kernel/Kernel.php:789 { …}
    ./vendor/symfony/http-kernel/Kernel.php:128 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:179 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:71 { …}
    ./vendor/symfony/console/Application.php:171 { …}
    ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54 { …}
    ./vendor/autoload_runtime.php:35 { …}
    ./bin/console:11 {
      › 
      › require_once dirname(__DIR__).'/vendor/autoload_runtime.php';
      › 
      arguments: {
        "/home/arderyp/repo/vendor/autoload_runtime.php"
      }
    }
  }
}
2024-02-19T18:54:29+00:00 [critical] Uncaught Error: Class "Symfony\Component\Routing\DependencyInjection\AddExpressionLanguageProvidersPass" not found
```

**Comment by arderyp** [comment]
Sorry I made a comment and then deleted it.  The error was on my side.

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Bundle/FrameworkBundle/CacheWarmer/ConfigBuilderCacheWarmer.php [hunk 2]
```diff
@@ -47,14 +47,17 @@ public function __construct(KernelInterface $kernel, ?LoggerInterface $logger =
      */
     public function warmUp(string $cacheDir)
     {
-        $generator = new ConfigBuilderGenerator($this->kernel->getBuildDir());
+        /** @var ContainerBuilder $container */
+        $container = \Closure::bind(function (KernelInterface $kernel) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/CacheWarmer/ConfigBuilderCacheWarmer.php]: psalm is right, we're hardcoding the logic against Kernel:
```suggestion
        $container = \Closure::bind(function (Kernel $kernel) {
```

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/CacheWarmer/ConfigBuilderCacheWarmer.php]: would it make sense to accept kernels that don't extend Kernel BTW? (using the previous logic for them)

Comment (HypeMC) [reply src/Symfony/Bundle/FrameworkBundle/CacheWarmer/ConfigBuilderCacheWarmer.php]: Done, though Psalm still isn't happy. I've also added a case for kernels not extending the Kernel class.

**Comment by nicolas-grekas** [comment]
Thank you @HypeMC.

**Comment by nicolas-grekas** [comment]
@HypeMC I failed to merge the test case into 6.4, could you please submit it there?

**Comment by HypeMC** [comment]
@nicolas-grekas Done, see #54040
