### PR TITLE
[TypeInfo] Add result cache to `TypeContextFactory`

### LINKED ISSUE #61725: [TypeInfo] TypeContextFactory::createFromClassName() needs a result cache
### Symfony version(s) affected

7.3.3

### Description

When validating a form on a DoctrineMongoDB ODM Document with many `Collection` fields, the `TypeContextFactory::createFromClassName()` method is called several times to parse:

- [ClassMetadata.php](https://github.com/doctrine/mongodb-odm/blob/ace03963b011f92e5e4bb25b03b6b1a6d2890d1c/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php)
- [UnitOfWork.php](https://github.com/doctrine/mongodb-odm/blob/ace03963b011f92e5e4bb25b03b6b1a6d2890d1c/lib/Doctrine/ODM/MongoDB/UnitOfWork.php)
- [PersistentCollection.php](https://github.com/doctrine/mongodb-odm/blob/2.11.x/lib/Doctrine/ODM/MongoDB/PersistentCollection.php).

It uses PHPStan Property extractor to parse the docblocks. `UnitOfWork` and `ClassMetadata` docblocks are huge. This slows the form validation.

### How to reproduce

Call:

```php
for($i=0; $i < 20; $i++) {
$this->typeContextFactory->createFromClassName("Doctrine\ODM\MongoDB\PersistentCollection","Doctrine\ODM\MongoDB\PersistentCollection\PersistentCollectionTrait");
}
```

### Possible Solution

Please add a cache to `TypeContextFactory::createFromClassName()` to limit resource usage due to running PHPStan property extractor on already parsed classes.

### Additional Context

PHPStan Property extractor also has a resource issue when parsing type declarations with `<` (arrays, generics, collections). It always tries to determine if its an HTML tag, regardless of the type declaration context.

### PR DESCRIPTION
**Pull request by landure**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #61725
| License       | MIT

Add caches to `TypeContextFactory` method to prevent multiple parsing of the same classes by PHPStan property extractor.

1. Add cache to intermediate `TypeContext` creation from `createFromClassName()` and `createFromReflection()` by adding:

   - `intermediateTypeContextCache` proprety.
   - `createIntermediateTypeContext()` create the intermediate `TypeContext` if not found in cache.

2. Add cache to `createFromClassName()` by:

   - `typeContextCache` proprety.
   - extracting `TypeContext` creation to private `createNewInstanceFromClassName()` method.
   - refactoring `createFromClassName()` to get the `TypeContext` from `$this->typeContextCache`, or creating it by calling `createNewInstanceFromClassName()` method.

3. Add a test to check that the results are cached.

This optimize deserialization and form validation.

### CODE REVIEW

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 1]
```diff
@@ -113,6 +108,56 @@ public function createFromReflection(\Reflector $reflection): ?TypeContext
...
+
+        self::$intermediateTypeContextCache[$declaringClassName][$calledClassShortName] ??= $this->createIntermediateTypeContext(
+            $calledClassShortName,
+            $declaringClassReflection,
+        );
+
+        return self::$intermediateTypeContextCache[$declaringClassName][$calledClassShortName];
+    }
+
+    private function createIntermediateTypeContext(
```
Comment (nicolas-grekas) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: I'd rather inline the code than adding this method

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 2]
```diff
@@ -113,6 +108,56 @@ public function createFromReflection(\Reflector $reflection): ?TypeContext
...
+            $typeContext->uses,
+            $this->collectTemplates($declaringClassReflection, $typeContext),
+            $this->collectTypeAliases($declaringClassReflection, $typeContext),
+        );
+    }
+
+    private function getIntermediateTypeContext(
+        string $calledClassShortName,
+        \ReflectionClass $declaringClassReflection,
+    ): TypeContext {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: our CS is to always have function signatures on one line (except for constructor using CPP)
```suggestion
    ): TypeContext
    {
```

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 3]
```diff
@@ -113,6 +108,56 @@ public function createFromReflection(\Reflector $reflection): ?TypeContext
         );
     }
 
+    private function createNewInstanceFromClassName(
+        string $calledClassName,
+        string $declaringClassName,
+    ): TypeContext {
+        $calledClassPath = explode('\\', $calledClassName);
+        $declaringClassPath = explode('\\', $declaringClassName);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: deadcode?

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 4]
```diff
@@ -41,6 +42,16 @@ final class TypeContextFactory
      */
     private static array $reflectionClassCache = [];
 
+    /**
+     * @var array<string,array<string,TypeContext>
+     */
+    private static array $intermediateTypeContextCache = [];
```
Comment (stof) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: Please don't make the cache static. We don't need that global state (thus, this global state would be flawed if we have different string type resolvers in 2 instances of the factory).

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php (hunk 1 above)
Comment (landure) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: I'm not sure if I understood you correctly, but I merged `getIntermediateTypeContext()` in `createIntermediateTypeContext()`.

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php (hunk 2 above)
Comment (landure) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: fixed

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php (hunk 3 above)
Comment (landure) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: Well found. I removed `$declaringClassPath` since it's now replaced by `$declaringClassReflection->getShortName()` in `createIntermediateTypeContext()`.

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php (hunk 4 above)
Comment (landure) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: fixed

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 5]
```diff
@@ -113,6 +102,38 @@ public function createFromReflection(\Reflector $reflection): ?TypeContext
...
+            $this->collectTemplates($declaringClassReflection, $typeContext),
+            $this->collectTypeAliases($declaringClassReflection, $typeContext),
+        );
+    }
+
+    private function createIntermediateTypeContext(string $calledClassShortName, \ReflectionClass $declaringClassReflection): TypeContext
+    {
+        $declaringClassName = $declaringClassReflection->getName();
+
+        self::$intermediateTypeContextCache[$declaringClassName][$calledClassShortName] ??= new TypeContext(
```
Comment (nicolas-grekas) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]:
```suggestion
        return self::$intermediateTypeContextCache[$declaringClassName][$calledClassShortName] ??= new TypeContext(
```

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 6]
```diff
@@ -53,26 +64,9 @@ public function createFromClassName(string $calledClassName, ?string $declaringC
...
-
-        $declaringClassReflection = self::$reflectionClassCache[$declaringClassName] ??= new \ReflectionClass($declaringClassName);
-
-        $typeContext = new TypeContext(
-            end($calledClassPath),
-            end($declaringClassPath),
-            trim($declaringClassReflection->getNamespaceName(), '\\'),
-            $this->collectUses($declaringClassReflection),
-        );
+        $this->typeContextCache[$declaringClassName][$calledClassName] ??= $this->createNewInstanceFromClassName($calledClassName, $declaringClassName);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]:
```suggestion
        return $this->typeContextCache[$declaringClassName][$calledClassName] ??= $this->createNewInstanceFromClassName($calledClassName, $declaringClassName);
```

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php (hunk 5 above)
Comment (landure) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: fixed

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php (hunk 6 above)
Comment (landure) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: fixed

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]
For 7.4 as this is a performance improvement.

**Comment by fabpot** [comment]
Thank you @landure.
