### PR TITLE
[Yaml] Fix parsing of unquoted strings in Parser::lexUnquotedString() to ignore spaces

### LINKED ISSUE #59299: Symfony YAML parsing yaml results are incorrect
### Symfony version(s) affected

7.2.0

### Description

As demo below, there are 2 spaces between letter "A" and "B".
But Symfony Yaml only parsed as 1 space.

### How to reproduce

```
<?php

include __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Yaml\Yaml;

$payload = <<<EOF
names:
  - {name: A  B}
EOF;

// Using Symfony Yaml
$content1 = Yaml::parse($payload);
var_dump($content1['names'][0]['name']);
// string(3) "A B"

// Using yaml pecl extension
$content2 = yaml_parse($payload);
var_dump($content2['names'][0]['name']);
// string(4) "A  B"
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Link1515**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59299
| License       | MIT

I modified the `strcspn()` call in the `lexUnquotedString()` method of the `Parser` class to exclude the space character (' ') from the list of delimiters. This ensures that spaces are no longer considered while parsing unquoted strings.

### CODE REVIEW

File: src/Symfony/Component/Yaml/Tests/ParserTest.php [hunk 1]
```diff
@@ -1710,6 +1710,32 @@ public function testBackslashInQuotedMultiLineString()
         $this->assertSame($expected, $this->parser->parse($yaml));
     }
 
+    /**
+     * @dataProvider WrappedUnquotedStrings
+     */
+    public function testWrappedUnquotedStringWithMultipleSpacesInValue(string $yaml, array $expected)
+    {
+        $this->assertSame($expected, $this->parser->parse($yaml));
+    }
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Tests/ParserTest.php:1719]: please add a blank line after the closing curly brace

File: src/Symfony/Component/Yaml/Tests/ParserTest.php [hunk 2]
```diff
@@ -1710,6 +1710,32 @@ public function testBackslashInQuotedMultiLineString()
...
+    public static function WrappedUnquotedStrings() {
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Tests/ParserTest.php]:
```suggestion
    public static function wrappedUnquotedStringsProvider()
    {
```

File: src/Symfony/Component/Yaml/Tests/ParserTest.php [hunk 3]
```diff
@@ -1710,6 +1710,32 @@ public function testBackslashInQuotedMultiLineString()
         $this->assertSame($expected, $this->parser->parse($yaml));
     }
 
+    /**
+     * @dataProvider WrappedUnquotedStrings
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Tests/ParserTest.php]:
```suggestion
     * @dataProvider wrappedUnquotedStringsProvider
```

File: src/Symfony/Component/Yaml/Tests/ParserTest.php [hunk 4]
```diff
@@ -1710,6 +1710,32 @@ public function testBackslashInQuotedMultiLineString()
...
+     */
+    public function testWrappedUnquotedStringWithMultipleSpacesInValue(string $yaml, array $expected)
+    {
+        $this->assertSame($expected, $this->parser->parse($yaml));
+    }
+    public static function WrappedUnquotedStrings() {
+        return [
+            'CurlyBraces' => [
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Tests/ParserTest.php]:
```suggestion
            'mapping' => [
```

File: src/Symfony/Component/Yaml/Tests/ParserTest.php [hunk 5]
```diff
@@ -1710,6 +1710,32 @@ public function testBackslashInQuotedMultiLineString()
...
+                '{ foo: bar  bar, fiz: cat      cat }',
+                [
+                    'foo' => 'bar  bar',
+                    'fiz' => 'cat      cat',
+                ]
+            ],
+            'SquareBraces' => [
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Tests/ParserTest.php]:
```suggestion
            'sequence' => [
```

**Review by xabbuh — APPROVED** [review]
with some minor CS remarks

**Comment by Link1515** [comment]
@xabbuh Thank you for taking the time to review my PR! I really appreciate your feedback and have made the suggested changes. Let me know if there's anything else to adjust!

**Review by xabbuh — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you @Link1515.
