### PR TITLE
[PropertyInfo] Check if property is nullable when using `ReflectionExtractor`

### LINKED ISSUE #57707: [PropertyInfo] ReflectionExtractor::getType incorrectly reports nullable typed array of objects as a non-nullable CollectionType
### Symfony version(s) affected

5.4+

### Description

Using ReflectionExtractor::getType on a property typed with `?array` and an adder typed with an object incorrectly returns the type as non nullable. 

This issue can lead to problems using symfony/serializer during denormalization for example, causing it to fail since the denormalizer expect the fetched type from the ReflectionExtractor to be non-nullable even when given property is properly declared as such

### How to reproduce

An example using a `Video` class with an array of `Comment` class on a `$comments` property (phpDoc is only indicative here for clarity purposes)

```php
class Video
{
    public ?string $title = null;

    /**
     * @var Comment[]|null
     */
    public array|null $comments;

    private function setTitle(?string $title): void
    {
        $this->title = $title;
    }

    private function addComment(Comment $comment): void
    {
        $this->comments[] = $comment;
    }
}
```

```php
class Comment
{
    public string $content;
}
```

```php
$extractor = new ReflectionExtractor();

$property = $extractor->getType(Video::class, 'comments');

$property->isNullable();
// returns false
```

Practical example with Xdebug :

image

### Possible Solution

#57708 & #57802

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by benjilebon**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #57707 
| License       | MIT

When `$type` was resolved into a `CollectionType` with an adder mutator on the given `$class`, the replaced $type ignored if the actual property was nullable or not, causing the returned Type to always report as non nullable even when given property was declared with a `null` union type or a `?` (`?array` for example)

See issue for more information and an example case

### CODE REVIEW

File: src/Symfony/Component/PropertyInfo/Tests/Fixtures/Php74Dummy.php [hunk 1]
```diff
@@ -23,11 +23,18 @@ class Php74Dummy
     private ?int $nullableWithDefault = 1;
     public array $collection = [];
 
+    /** @var Dummy[]|null  */
```
Comment (xabbuh) [inline src/Symfony/Component/PropertyInfo/Tests/Fixtures/Php74Dummy.php:26]: Does the `PhpDocExtractor` handle the described use case properly? Do we have a test covering it or would it be worth to add one?

Comment (benjilebon) [reply src/Symfony/Component/PropertyInfo/Tests/Fixtures/Php74Dummy.php:26]: PhpDocExtractor works correctly for this use case, I've added tests covering that specifically

File: src/Symfony/Component/PropertyInfo/Tests/Extractor/PhpDocExtractorTest.php [hunk 2]
```diff
@@ -548,6 +548,7 @@ public static function typeProvider(): iterable
         yield ['collection', Type::list(Type::object(\DateTimeImmutable::class)), null, null];
         yield ['nestedCollection', Type::list(Type::list(Type::string())), null, null];
         yield ['mixedCollection', Type::array(), null, null];
+        yield ['nullableTypedCollection', Type::nullable(Type::list(Type::object(Dummy::class))), null, null];
```
Comment (xabbuh) [inline src/Symfony/Component/PropertyInfo/Tests/Extractor/PhpDocExtractorTest.php:552]: we should expand `provideLegacyTypes()` in the same way to ensure that the behaviour of the old and new type system matches

File: src/Symfony/Component/PropertyInfo/Tests/Extractor/ReflectionExtractorTest.php [hunk 3]
```diff
@@ -865,6 +868,7 @@ public function testTypedProperties()
         $this->assertEquals(Type::list(Type::string()), $this->extractor->getType(Php74Dummy::class, 'stringCollection'));
         $this->assertEquals(Type::nullable(Type::int()), $this->extractor->getType(Php74Dummy::class, 'nullableWithDefault'));
         $this->assertEquals(Type::array(), $this->extractor->getType(Php74Dummy::class, 'collection'));
+        $this->assertEquals(Type::nullable(Type::list(Type::object(Dummy::class))), $this->extractor->getType(Php74Dummy::class, 'nullableTypedCollection'));
```
Comment (xabbuh) [inline src/Symfony/Component/PropertyInfo/Tests/Extractor/ReflectionExtractorTest.php:871]: we should expand `testTypedPropertiesLegacy()` in the same way to ensure that the behaviour of the old and new type system matches

**Comment by benjilebon** [comment]
After testing, it seems the legacy type system is also affected by the same problem reported in linked issue #57707, which means this issue also affects 6.4

@xabbuh do you have any advice on how to proceed ? Should i open another PR based on 6.4 and provide the fix for the old type system here ?

**Comment by xabbuh** [comment]
Yes please, maybe even 5.4 instead of 6.4 if that’s affected too.

File: src/Symfony/Component/PropertyInfo/Tests/Extractor/PhpDocExtractorTest.php (hunk 2 above)
Comment (benjilebon) [reply src/Symfony/Component/PropertyInfo/Tests/Extractor/PhpDocExtractorTest.php:552]: Done, amended to my last commit

**Comment by benjilebon** [comment]
> Yes please, maybe even 5.4 instead of 6.4 if that’s affected too.

Done on #57802, i've updated the relevant issue to correct the affected versions

**Comment by fabpot** [comment]
Thank you @benjilebon.

**Review by fabpot — APPROVED** [review]
