### PR TITLE
[Notifier] Add exception for deprecated slack dsn

### LINKED ISSUE #39204: Slack notifier SlackTransport doesn't parse Slack DSN correctly
**Symfony version(s) affected**: 5.1.*

**Description**  
When I set my webhook url as DSN like this : 

`SLACK_DSN=slack://hooks.slack.com/services/xxxxx/xxxxx/xxxxx`

Slack notification doesn't work as the post URL in SlackTransport.php becomes: 

https://hooks.slack.com/services/services/xxxxx/xxxxx/xxxxx

A confusing exception is thrown as Slack responds with HTTP 200 and the content of the https://api.slack.com page.
"Unable to post the Slack message: <!DOCTYPE html><html lang="en-US" class="">..." 

**How to reproduce**  
- Install symfony/slack-notifier
- Set Slack DSN as (no https unless an other error will trigger)  : 
`SLACK_DSN=slack://hooks.slack.com/services/YOUR/CUSTOM/WEBHOOK-URL`
- Try to send a Slack notification. 

**Possible Solution**  

The only way to make it work is to remove "/services" from the webhook URL in DSN  as: 

 `SLACK_DSN=slack://hooks.slack.com/xxxxx/xxxxx/xxxxx`

Another solution would be to fix symfony/slack-notifier by modifying SlackTransport.php: 

```
        $response = $this->client->request('POST', sprintf('https://%s/services/%s', $this->getEndpoint(), $id), [
            'json' => array_filter($options),
        ]);
```
to 
```
        $response = $this->client->request('POST', sprintf('https://%s/%s', $this->getEndpoint(), $id), [
            'json' => array_filter($options),
        ]);
```

**Additional information**   
The main issue is that the correct syntax for Slack DSN with webhook is unclear in the documentation. 
I had to guess the syntax by myself. Maybe this issue just requires a documentation update.

### PR DESCRIPTION
**Pull request by malteschlueter**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Tickets       | Fix #39204 
| License       | MIT
| Doc PR        | -

The DSN for the Slack integration changed again from 5.1 to 5.2. There was the idea to output an exception for that.

### CODE REVIEW

File: src/Symfony/Component/Notifier/Bridge/Slack/SlackTransportFactory.php [hunk 1]
```diff
@@ -28,17 +29,21 @@ final class SlackTransportFactory extends AbstractTransportFactory
      */
     public function create(Dsn $dsn): TransportInterface
     {
-        $scheme = $dsn->getScheme();
+        if ('slack' !== $dsn->getScheme()) {
+            throw new UnsupportedSchemeException($dsn, 'slack', $this->getSupportedSchemes());
+        }
+
+        if ('/' !== $dsn->getPath()) {
+            $message = sprintf('Invalid "%s" notifier DSN: Using a dsn for slack webhooks is deprecated (maybe you haven\'t update the DSN when upgrading from 5.1).', $dsn->getOriginalDsn());
```
Comment (derrabus) [inline src/Symfony/Component/Notifier/Bridge/Slack/SlackTransportFactory.php]: Wording: "deprecated" means that the feature is still available, but we will stop supporting it in the future. This is not the case here, because the feature has actually been removed already.

Also, please inline `$message`.

**Comment by derrabus** [comment]
Thank you for working on this issue!

File: src/Symfony/Component/Notifier/Bridge/Slack/SlackTransportFactory.php (hunk 1 above)
Comment (malteschlueter) [reply src/Symfony/Component/Notifier/Bridge/Slack/SlackTransportFactory.php]: What do you think now? My english isn't very well ^^

File: src/Symfony/Component/Notifier/Bridge/Slack/SlackTransportFactory.php [hunk 2]
```diff
@@ -28,17 +29,20 @@ final class SlackTransportFactory extends AbstractTransportFactory
      */
     public function create(Dsn $dsn): TransportInterface
     {
-        $scheme = $dsn->getScheme();
+        if ('slack' !== $dsn->getScheme()) {
+            throw new UnsupportedSchemeException($dsn, 'slack', $this->getSupportedSchemes());
+        }
+
+        if ('/' !== $dsn->getPath()) {
+            throw new InvalidArgumentException(sprintf('Invalid "%s" notifier DSN: Using a dsn for slack webhooks has been removed (maybe you haven\'t update the DSN when upgrading from 5.1).', $dsn->getOriginalDsn()));
```
Comment (evertharmeling) [inline src/Symfony/Component/Notifier/Bridge/Slack/SlackTransportFactory.php]: Maybe better to use `throw new IncompleteDsnException('Support for slack webhook dsn has been dropped since 5.2 (maybe you haven\'t updated the DSN when upgrading from 5.1).');`?

**Review by jderusse — COMMENTED** [review]
LGTM. Just the small wording suggested by @evertharmeling

File: src/Symfony/Component/Notifier/Bridge/Slack/SlackTransportFactory.php [hunk 3]
```diff
@@ -28,17 +29,20 @@ final class SlackTransportFactory extends AbstractTransportFactory
      */
     public function create(Dsn $dsn): TransportInterface
     {
-        $scheme = $dsn->getScheme();
+        if ('slack' !== $dsn->getScheme()) {
+            throw new UnsupportedSchemeException($dsn, 'slack', $this->getSupportedSchemes());
+        }
+
+        if ('/' !== $dsn->getPath()) {
```
Comment (fabpot) [inline src/Symfony/Component/Notifier/Bridge/Slack/SlackTransportFactory.php:36]: The check looks fragile to me. I would check for the whole pattern instead via a regex.

File: src/Symfony/Component/Notifier/Bridge/Slack/SlackTransportFactory.php (hunk 2 above)
Comment (fabpot) [reply src/Symfony/Component/Notifier/Bridge/Slack/SlackTransportFactory.php]: I agree.

Please, change "webhook dsn" to "webhook DSN".

**Review by fabpot — CHANGES_REQUESTED** [review]
Could you also add the format DSN information in the README? We are doing this for almost all other providers and we forgot to do it here.

File: src/Symfony/Component/Notifier/Bridge/Slack/SlackTransportFactory.php (hunk 2 above)
Comment (OskarStark) [reply src/Symfony/Component/Notifier/Bridge/Slack/SlackTransportFactory.php]: But Incomplete... is missleading, it's a wrong DSN... 🧐

Comment (malteschlueter) [reply src/Symfony/Component/Notifier/Bridge/Slack/SlackTransportFactory.php]: @OskarStark That was also my first thought but i wasn't sure if it is okay if i a add a new exception.

File: src/Symfony/Component/Notifier/Bridge/Slack/SlackTransportFactory.php (hunk 3 above)
Comment (malteschlueter) [reply src/Symfony/Component/Notifier/Bridge/Slack/SlackTransportFactory.php:36]: I have thought for a regex but i couldn't think of any which makes sense for me, sorry :(

At the end i think it's just not allowed to add a path to the DSN. It wouldn't be processed anyway.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @malteschlueter.
