### PR TITLE
[DependencyInjection] Process PHP configs using the ContainerConfigurator

### LINKED ISSUE #54852: [Config] ParamConfigurator is not longer respected as scalar-string-value
### Symfony version(s) affected

7.1.0-BETA1

### Description

After update to BETA released version, I got an error for configuration, where `ParamConfigurator` is not anymore respected as `scalar` value.

I don't know what changes cause this issue.

### How to reproduce

One of: 

```php
use Symfony\Config\FrameworkConfig;

use function Symfony\Component\DependencyInjection\Loader\Configurator\param;

return static function (FrameworkConfig $frameworkConfig): void {
    $frameworkConfig->phpErrors()
        ->log(value: param(name: 'kernel.debug'));
};
```

### Possible Solution
Cast `ParamConfigurator` to string anyway, when the configuration allows you to pass an object.
```php
use Symfony\Config\FrameworkConfig;

use function Symfony\Component\DependencyInjection\Loader\Configurator\param;

return static function (FrameworkConfig $frameworkConfig): void {
    $frameworkConfig->phpErrors()
        ->log(value: (string) param(name: 'kernel.debug'));
};
```

### Additional Context

obraz
obraz

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54852
| License       | MIT

Since #52843, `ContainerConfigurator::extension` is not called anymore which means `ParamConfigurator`s are no longer processed and converted to strings, and makes nodes validation fail: e.g. `framework.secret` would receive an `EnvConfigurator` and throw because it is not a scalar.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thank you @MatTheCat.

**Comment by MatTheCat** [comment]
…that was fast!

@yceruto does this PR seem okay to you?

File: src/Symfony/Component/DependencyInjection/Loader/PhpFileLoader.php [hunk 1]
```diff
@@ -145,16 +145,8 @@ class_exists(ContainerConfigurator::class);
...
-    }
-
-    /**
-     * @param iterable<ConfigBuilderInterface> $configBuilders
-     */
-    private function loadFromExtensions(iterable $configBuilders): void
-    {
         foreach ($configBuilders as $configBuilder) {
-            $this->loadExtensionConfig($configBuilder->getExtensionAlias(), $configBuilder->toArray());
+            $containerConfigurator->extension($configBuilder->getExtensionAlias(), $configBuilder->toArray(), $this->prepend);
```
Comment (yceruto) [inline src/Symfony/Component/DependencyInjection/Loader/PhpFileLoader.php:149]: I still need to do some config prepending tests, but I feel that we've missed something here as the previous `$this->loadExtensionConfig()` is currently doing more things when prepend argument is `true`, e.g. the nested importing might be broken...

**Comment by yceruto** [comment]
@MatTheCat thanks for the ping, I'm checking deeper... but AFAIR we don't resolve env var during prepending phase before, it's done during the merging process (aka loadExtension) when all configs were merged.

File: src/Symfony/Component/DependencyInjection/Loader/PhpFileLoader.php (hunk 1 above)
Comment (MatTheCat) [reply src/Symfony/Component/DependencyInjection/Loader/PhpFileLoader.php:149]: I saw you made the `ContainerConfigurator` able to prepend in #52636 so I assumed it was okay but it is indeed missing this part: https://github.com/symfony/symfony/blob/7c956d84af558313657e25b39bf098281206cd5d/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php#L238-L245

Don’t know if it is an issue at all though :sweat:

**Comment by MatTheCat** [comment]
@yceruto thanks for looking!

Not sure what you call “resolving” env vars but this PR essentially stringify `ParamConfigurator`s, which happens before replacing said parameters with their actual value.

**Comment by yceruto** [comment]
>but AFAIR we don't resolve env var during prepending phase before, it's done during the merging process (aka loadExtension) when all configs were merged.

Nevemind, I got it, it's about processing the configurator as before https://github.com/symfony/symfony/pull/52843/files#diff-1cd56b329433fc34d950d6eeab9600752aa84a76cbe0693d3fab57fed0f547d3L150

File: src/Symfony/Component/DependencyInjection/Loader/PhpFileLoader.php (hunk 1 above)
Comment (yceruto) [reply src/Symfony/Component/DependencyInjection/Loader/PhpFileLoader.php:149]: Yes, it'll be an issue when want to prepend nested configs using imports

Comment (yceruto) [reply src/Symfony/Component/DependencyInjection/Loader/PhpFileLoader.php:149]: After some quick tests, the root issue should be mitigated by processing only the config value this way:
```php
$this->loadExtensionConfig($configBuilder->getExtensionAlias(), ContainerConfigurator::processValue($configBuilder->toArray()));
```
that will keep the prepending strategy working again. Would you mind creating another PR to update it? I can do it otherwise

Comment (MatTheCat) [reply src/Symfony/Component/DependencyInjection/Loader/PhpFileLoader.php:149]: If you already have the tests I think you’re more reading than I am; go ahead :grin: 

Would `ContainerConfiguration::extension` serve a purpose then?

Comment (yceruto) [reply src/Symfony/Component/DependencyInjection/Loader/PhpFileLoader.php:149]: https://github.com/symfony/symfony/pull/54977

Comment (yceruto) [reply src/Symfony/Component/DependencyInjection/Loader/PhpFileLoader.php:149]: > Would ContainerConfiguration::extension serve a purpose then?

It should be avoided internally where recursive importing is involved, as now importing from `prependExtension()` is supported (which requires an specific holding strategy to keep the importing order). However, you can still use it on your end for trivial array config importing (either in the `prependExtension()` or `loadExtension()` methods).

Comment (MatTheCat) [reply src/Symfony/Component/DependencyInjection/Loader/PhpFileLoader.php:149]: Okaaay thanks; glad I asked your review 😄
