### PR TITLE
[Translation] [Lokalise] Fix `base_uri`

### LINKED ISSUE #42234: Mistype in url | symfony/lokalise-translation-provider
**Symfony version(s) affected**: 5.3

**Description**
Wrong slug in lokalise provider url

**How to reproduce**
php bin/console translation:pull --force --locales= --domains=

**Possible Solution**
```
 $client = $this->client->withOptions([
            'base_uri' => 'https://'.$endpoint.'/projects/'.$this->getUser($dsn).'/api2/',
            'headers' => [
                'X-Api-Token' => $this->getPassword($dsn),
            ],
        ]);
```

replace with 

```
$client = $this->client->withOptions([
            'base_uri' => 'https://'.$endpoint.'/api2/projects/'.$this->getUser($dsn),
            'headers' => [
                'X-Api-Token' => $this->getPassword($dsn),
            ],
        ]);
```
in file **LokaliseProviderFactory.php**

### PR DESCRIPTION
**Pull request by welcoMattic**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix https://github.com/symfony/symfony/issues/42234 
| License       | MIT
| Doc PR        |

It fixes the Lokalise `base_uri` value.

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Can you please add a testcase to expect the correct url?

File: src/Symfony/Component/Translation/Bridge/Lokalise/Tests/LokaliseProviderFactoryTest.php [hunk 1]
```diff
@@ -32,6 +35,23 @@ public function incompleteDsnProvider(): iterable
         yield ['lokalise://default'];
     }
 
+    public function testBaseUri()
+    {
+        $httpClient = $this->createMock(MockHttpClient::class);
```
Comment (welcoMattic) [inline src/Symfony/Component/Translation/Bridge/Lokalise/Tests/LokaliseProviderFactoryTest.php]: I'm not 100% sure about this one :smile:

File: src/Symfony/Component/Translation/Bridge/Lokalise/Tests/LokaliseProviderFactoryTest.php [hunk 2]
```diff
@@ -32,6 +34,23 @@ public function incompleteDsnProvider(): iterable
...
```
Comment (OskarStark) [inline src/Symfony/Component/Translation/Bridge/Lokalise/Tests/LokaliseProviderFactoryTest.php]:
```suggestion
        $httpClient = $this->createMock(HttpClientInterface::class);
```

Comment (Nyholm) [reply src/Symfony/Component/Translation/Bridge/Lokalise/Tests/LokaliseProviderFactoryTest.php]: Oh no.. here I am trying to help but I only make things worse. 

I committed this, it should be reverted. 


-----

What one can do is to instantiate a new MockClient. Then make the LokaliseProvider to send a request. Then we run assertion on the request. 

```php
// Psudo code. 

$client = new MockHttpClient([new Response(200)]);
$factory = new LokaliseProviderFactory($httpClient, $this->getLogger(), $this->getDefaultLocale(), $this->getLoader());

// Make Lokalise send a HTTP request
$request = $client->getLastRequest(); // Or a similar named method
$this->assertSame('https://api.lokalise.com/api2/projects/PROJECT_ID/', $request->getUri());
```

Comment (welcoMattic) [reply src/Symfony/Component/Translation/Bridge/Lokalise/Tests/LokaliseProviderFactoryTest.php]: HttpClientInterface doesn't know about `withOptions` method, so we can't use it to create the mock.

@Nyholm I can't find any similar method like `getLastRequest`, are you sure it exists in HttpClient?

Comment (Nyholm) [reply src/Symfony/Component/Translation/Bridge/Lokalise/Tests/LokaliseProviderFactoryTest.php]: > HttpClientInterface doesn't know about withOptions method, so we can't use it to create the mock.

Yes. That is why the change I committed (suggested by Oskar) was wrong. 

---

> @Nyholm I can't find any similar method like getLastRequest, are you sure it exists in HttpClient?

Oops, Im slightly wrong again. I've checked the sources now.. =)
You create a `MockResponse` and after the request is "sent" the `Response` object will have URL, HTTP method and response options. 

```php
// Psudo code. 

$response = new MockResponse('body');
$client = new MockHttpClient([$response]);
$factory = new LokaliseProviderFactory($httpClient, $this->getLogger(), $this->getDefaultLocale(), $this->getLoader());

// Make Lokalise send a HTTP request

$this->assertSame('https://api.lokalise.com/api2/projects/PROJECT_ID/', $response->getRequestUrl());
```

Comment (welcoMattic) [reply src/Symfony/Component/Translation/Bridge/Lokalise/Tests/LokaliseProviderFactoryTest.php]: My last commit should work better. Thanks for the tip to do a real HTTP request

**Review by OskarStark — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @welcoMattic.
