### PR TITLE
[HttpClient] Fix retrying requests with `Psr18Client` and NTLM connections

### LINKED ISSUE #59489: [HttpClient] Streaming request changes in HttplugClient result in curl error  CURLE_SEND_FAIL_REWIND
### Symfony version(s) affected

7.2.2+

### Description

Since this change in 7.2.2 that allows for streaming the HTTP request body with `CURLOPT_READFUNCTION` instead of  `CURLOPT_POSTFIELDS`: https://github.com/symfony/symfony/commit/bbdf0e0ca2745c890ee37717b58602b0e218f313 (introduced by @nicolas-grekas)

We are receiving: CURLE_SEND_FAIL_REWIND (65)
> When doing a send operation curl had to rewind the data to retransmit, but the rewinding operation failed. 

```
  Unable to read stream contents: Necessary data rewind wasn't possible for "http://xxxx"

Exception trace:
  at /app/vendor/symfony/http-client/Response/CurlResponse.php:319
 Symfony\Component\HttpClient\Response\CurlResponse::perform() at /app/vendor/symfony/http-client/Response/TransportResponseTrait.php:167
 Symfony\Component\HttpClient\Response\CurlResponse::stream() at /app/vendor/symfony/http-client/Response/StreamWrapper.php:123
 Symfony\Component\HttpClient\Response\StreamWrapper->stream_read() at n/a:n/a
 stream_get_contents() at /app/vendor/nyholm/psr7/src/Stream.php:270
 Nyholm\Psr7\Stream->getContents() at /app/vendor/nyholm/psr7/src/StreamTrait.php:23
 Nyholm\Psr7\Stream->__toString() at /app/vendor/php-soap/psr18-transport/src/HttpBinding/Psr7Converter.php:41
```

This happens on the second request. The first request gets handled as expected.

The server is private and cannot be shared.
Some details:

* It's a SOAP 1.1 server
* It has NTLM authentication (meaning curl will perform additional NTLM authentication requests / responses internally)

This happens on:

* PHP 8.3
* curl version 8.11.0

Our best guess is that using `CURLOPT_READFUNCTION` in combination with NTLM is resulting in this specific error inside `curl`. 
When we use this code-change on other endpoints, it works as expected. 

We found following issues on the web which might or might not be related:

* https://bugs.php.net/bug.php?id=80518
* https://discussions.unity.com/t/curl-error-65-neccessary-data-rewind-wasnt-possible/849943/5

### How to reproduce

As mentioned, the server is private and cannot be shared.

The configuration of the client is straight forward and looks like this:

```php
use Symfony\Component\HttpClient\CurlHttpClient;
use Symfony\Component\HttpClient\HttplugClient;

$client = new HttplugClient(
    new CurlHttpClient([
        'auth_ntlm' => 'user:password',
    ])
)
```

ℹ️  The first request that is sent over the shared connection will succeed as usual. The second request will fail with the error ` Unable to read stream contents: Necessary data rewind wasn't possible`

The request is a SOAP request that looks like this:

```
$headers = [
    0 => "Host: host:port"
    1 => "SOAPAction: "..."
    2 => "Content-Type: text/xml; charset="utf-8""
    3 => "Content-Length: 376"
    4 => "Accept: */*"
    5 => "User-Agent: Symfony HttpClient (Curl)"
    6 => "Accept-Encoding: gzip"
    7 => "expect:"
    8 => "Transfer-Encoding:"
];

$body = <<<EOXML
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Body xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
        <tns:AppInitialise xmlns:tns="uri:foo">
            <tns:useragent>foo</tns:useragent>
            <tns:languagecode>NLB</tns:languagecode>
        </tns:AppInitialise>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
EOXML;
```

which results in following curl options:

```
^ array:31 [
  10002 => "http://..."
  121 => true
  181 => 3
  182 => 3
  52 => true
  68 => 20
  10031 => ""
  13 => 0
  10004 => null
  10177 => ""
  64 => true
  81 => 2
  10065 => null
  10097 => null
  10083 => null
  10025 => null
  10087 => null
  10026 => null
  172 => false
  32 => 6
  107 => 8
  84 => 2
  10005 => "user:password"
  91 => false
  229 => 1
  10036 => "POST"
  47 => true
  10023 => array:9 [
    0 => "Host: horst:port"
    1 => "SOAPAction: "action""
    2 => "Content-Type: text/xml; charset="utf-8""
    3 => "Content-Length: 376"
    4 => "Accept: */*"
    5 => "User-Agent: Symfony HttpClient (Curl)"
    6 => "Accept-Encoding: gzip"
    7 => "expect:"
    8 => "Transfer-Encoding:"
  ]
  20012 => Closure($ch, $fd, $length)^ {#39732
    class: "Symfony\Component\HttpClient\CurlHttpClient"
    use: {
      $body: Closure(int $size)^ {#39649 …}
      $eof: false
      $buffer: ""
    }
  }
  14 => 502
  10100 => CurlShareHandle {#39677}
]
```

Let me know if I can add anything to this issue report to make it easier for you to reproduce or figure out what is going wrong.

### Possible Solution

We are not sure what is causing this specific error. It might be an issue in `curl` instead of symfony/http-client.

Following configuration got us around the actual issue, but seems like a bad idea performance-wise.

> CURLOPT_FORBID_REUSE - make connection get closed at once after use 

```php
$client = new HttplugClient(
    new CurlHttpClient([
        'auth_ntlm' => 'user:password',
        'extra' => [
            'curl' => [
                \CURLOPT_FORBID_REUSE => true,
            ]
        ]
    ])
);
```

Another option around the problem would be to introduce a new `CurlHttpClient` option.
Something like `$options['stream_request']` which has a default of true to use the `CURLOPT_READFUNCTION` implementation, but can be set to false for using the `CURLOPT_POSTFIELDS` logic.

### Additional Context

_No response_

### LINKED ISSUE #59629: http-client retry issue
### Symfony version(s) affected

symfony/http-client:7.2.0

### Description

When upgrading library `symfony/http-client` from 7.1.9 to 7.2.0, the `RetryableHttpClient` using `CurlHttpClient` and `GenericRetryStrategy`  won't work. (v7.2.0-RC1 works fine)

It produces an Exception on second http call (first retry http call) with:

```text
PHP Fatal error:  Uncaught Symfony\Component\HttpClient\Exception\TransportException: Idle timeout reached for "http://localhost:8098/test/500". in /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Response/AsyncResponse.php:70
Stack trace:
#0 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Response/CommonResponseTrait.php(144): Symfony\Component\HttpClient\Response\AsyncResponse::Symfony\Component\HttpClient\Response\{closure}(Object(Symfony\Component\HttpClient\Response\AsyncResponse), -0.0)
#1 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Response/AsyncResponse.php(98): Symfony\Component\HttpClient\Response\AsyncResponse::initialize(Object(Symfony\Component\HttpClient\Response\AsyncResponse))
#2 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Internal/HttplugWaitLoop.php(114): Symfony\Component\HttpClient\Response\AsyncResponse->getStatusCode()
#3 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Psr18Client.php(112): Symfony\Component\HttpClient\Internal\HttplugWaitLoop::createPsr7Response(Object(Nyholm\Psr7\Factory\Psr17Factory), Object(Nyholm\Psr7\Factory\Psr17Factory), Object(Symfony\Component\HttpClient\RetryableHttpClient), Object(Symfony\Component\HttpClient\Response\AsyncResponse), false)
#4 /nt/my_projects/symfony-http-client-issue/bin/http_client.php(34): Symfony\Component\HttpClient\Psr18Client->sendRequest(Object(Nyholm\Psr7\Request))
#5 {main}

Next Symfony\Component\HttpClient\Exception\TransportException: Idle timeout reached for "http://localhost:8098/test/500". in /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Chunk/ErrorChunk.php:55
Stack trace:
#0 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Response/AsyncResponse.php(71): Symfony\Component\HttpClient\Chunk\ErrorChunk->isFirst()
#1 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Response/CommonResponseTrait.php(144): Symfony\Component\HttpClient\Response\AsyncResponse::Symfony\Component\HttpClient\Response\{closure}(Object(Symfony\Component\HttpClient\Response\AsyncResponse), -0.0)
#2 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Response/AsyncResponse.php(98): Symfony\Component\HttpClient\Response\AsyncResponse::initialize(Object(Symfony\Component\HttpClient\Response\AsyncResponse))
#3 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Internal/HttplugWaitLoop.php(114): Symfony\Component\HttpClient\Response\AsyncResponse->getStatusCode()
#4 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Psr18Client.php(112): Symfony\Component\HttpClient\Internal\HttplugWaitLoop::createPsr7Response(Object(Nyholm\Psr7\Factory\Psr17Factory), Object(Nyholm\Psr7\Factory\Psr17Factory), Object(Symfony\Component\HttpClient\RetryableHttpClient), Object(Symfony\Component\HttpClient\Response\AsyncResponse), false)
#5 /nt/my_projects/symfony-http-client-issue/bin/http_client.php(34): Symfony\Component\HttpClient\Psr18Client->sendRequest(Object(Nyholm\Psr7\Request))
#6 {main}

Next Symfony\Component\HttpClient\Psr18NetworkException: Idle timeout reached for "http://localhost:8098/test/500". in /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Psr18Client.php:118
Stack trace:
#0 /nt/my_projects/symfony-http-client-issue/bin/http_client.php(34): Symfony\Component\HttpClient\Psr18Client->sendRequest(Object(Nyholm\Psr7\Request))
#1 {main}
  thrown in /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Psr18Client.php on line 118

Fatal error: Uncaught Symfony\Component\HttpClient\Exception\TransportException: Idle timeout reached for "http://localhost:8098/test/500". in /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Response/AsyncResponse.php:70
Stack trace:
#0 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Response/CommonResponseTrait.php(144): Symfony\Component\HttpClient\Response\AsyncResponse::Symfony\Component\HttpClient\Response\{closure}(Object(Symfony\Component\HttpClient\Response\AsyncResponse), -0.0)
#1 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Response/AsyncResponse.php(98): Symfony\Component\HttpClient\Response\AsyncResponse::initialize(Object(Symfony\Component\HttpClient\Response\AsyncResponse))
#2 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Internal/HttplugWaitLoop.php(114): Symfony\Component\HttpClient\Response\AsyncResponse->getStatusCode()
#3 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Psr18Client.php(112): Symfony\Component\HttpClient\Internal\HttplugWaitLoop::createPsr7Response(Object(Nyholm\Psr7\Factory\Psr17Factory), Object(Nyholm\Psr7\Factory\Psr17Factory), Object(Symfony\Component\HttpClient\RetryableHttpClient), Object(Symfony\Component\HttpClient\Response\AsyncResponse), false)
#4 /nt/my_projects/symfony-http-client-issue/bin/http_client.php(34): Symfony\Component\HttpClient\Psr18Client->sendRequest(Object(Nyholm\Psr7\Request))
#5 {main}

Next Symfony\Component\HttpClient\Exception\TransportException: Idle timeout reached for "http://localhost:8098/test/500". in /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Chunk/ErrorChunk.php:55
Stack trace:
#0 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Response/AsyncResponse.php(71): Symfony\Component\HttpClient\Chunk\ErrorChunk->isFirst()
#1 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Response/CommonResponseTrait.php(144): Symfony\Component\HttpClient\Response\AsyncResponse::Symfony\Component\HttpClient\Response\{closure}(Object(Symfony\Component\HttpClient\Response\AsyncResponse), -0.0)
#2 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Response/AsyncResponse.php(98): Symfony\Component\HttpClient\Response\AsyncResponse::initialize(Object(Symfony\Component\HttpClient\Response\AsyncResponse))
#3 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Internal/HttplugWaitLoop.php(114): Symfony\Component\HttpClient\Response\AsyncResponse->getStatusCode()
#4 /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Psr18Client.php(112): Symfony\Component\HttpClient\Internal\HttplugWaitLoop::createPsr7Response(Object(Nyholm\Psr7\Factory\Psr17Factory), Object(Nyholm\Psr7\Factory\Psr17Factory), Object(Symfony\Component\HttpClient\RetryableHttpClient), Object(Symfony\Component\HttpClient\Response\AsyncResponse), false)
#5 /nt/my_projects/symfony-http-client-issue/bin/http_client.php(34): Symfony\Component\HttpClient\Psr18Client->sendRequest(Object(Nyholm\Psr7\Request))
#6 {main}

Next Symfony\Component\HttpClient\Psr18NetworkException: Idle timeout reached for "http://localhost:8098/test/500". in /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Psr18Client.php:118
Stack trace:
#0 /nt/my_projects/symfony-http-client-issue/bin/http_client.php(34): Symfony\Component\HttpClient\Psr18Client->sendRequest(Object(Nyholm\Psr7\Request))
#1 {main}
  thrown in /nt/my_projects/symfony-http-client-issue/vendor/symfony/http-client/Psr18Client.php on line 118
```

Looks like an issue with reading response body, from [change](https://github.com/symfony/http-client/compare/v7.2.0-RC1...v7.2.0#diff-8edf2fe6cfcff5ee2f5f0ae5b2c84c1a7f6cc43c6dc47b8d4b9f5fb13ec29e9aR103) in Psr18Client.php.
From
```php
'body' => $body->getContents(),
```
to:
```php
'body' => static fn (int $size) => $body->read($size),
```
because when I change this directly in vendor library it works fine.

### How to reproduce

I created an example [here](https://github.com/icarus94/symfony-http-client-issue).
To reproduce execute:
```bash
composer install
```
Then on one terminal run:
```bash
php -S localhost:8098 -t public/
```
And the on other terminal:
```bash
bin/http_client.php
```
Which will produce an error like described.

If you downgrade `symfony/http-client` to 7.1.9, this error will be gone and retry will work fine.

----------------------------
From repo ⬆

Important files:
`bin/http_client.php`
```php 
#!/usr/bin/env php
<?php

declare(strict_types=1);

use Nyholm\Psr7\Factory\Psr17Factory;
use Symfony\Component\HttpClient\CurlHttpClient;
use Symfony\Component\HttpClient\Psr18Client;
use Symfony\Component\HttpClient\Retry\GenericRetryStrategy;
use Symfony\Component\HttpClient\RetryableHttpClient;

require_once __DIR__ . '/../vendor/autoload.php';

set_time_limit(0);
ini_set('display_errors', '1');


$client = new Psr18Client(
    new RetryableHttpClient(
        new CurlHttpClient(),
        new GenericRetryStrategy(
            [500], // <- retrying HTTP Status Code 500
            100
        ),
        2 // <- maxRetries
    ),
    new Psr17Factory()
);

$uri = 'http://localhost:8098/test/500';

$request = $client->createRequest('POST', $uri);
$request->getBody()->write(json_encode(['test']));
$response = $client->sendRequest(
    $request
        ->withHeader('Accept', 'application/json')
        ->withAddedHeader('Content-Type', 'application/json')
);

dump($response->getStatusCode());
dump((string) $response->getBody());
```
and

`public/index.php`
```php
<?php

declare(strict_types=1);

use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Slim\Factory\AppFactory;

require_once __DIR__ . '/../vendor/autoload.php';

set_time_limit(0);
ini_set('display_errors', '1');

$app = AppFactory::create();

$app->addErrorMiddleware(true, true, true);

// Add routes
$app->get('/', function (Request $request, Response $response) {
    $response->getBody()->write((string) json_encode(['OK']));
    return $response;
});

$app->post('/test/500', function (Request $request, Response $response, array $args) {
    $response = $response->withStatus(500, 'Server error');
    $response->getBody()->write((string) json_encode(['Error']));
    return $response;
});

$app->run();
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59489, Fix #59629
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/HttpClient/Psr18Client.php [hunk 1]
```diff
@@ -98,13 +98,26 @@ public function sendRequest(RequestInterface $request): ResponseInterface
...
-            if (!$request->hasHeader('content-length') && 0 <= $size = $body->getSize() ?? -1) {
+            $size = $request->getHeader('content-length')[0] ?? -1;
+            if (-1 === $size && 0 <= $size = $body->getSize() ?? -1) {
                 $headers['Content-Length'] = [$size];
             }
 
             $options = [
                 'headers' => $headers,
-                'body' => static fn (int $size) => $body->read($size),
+                'body' => 0 <= $size && $size < 1 << 21 ? $body->getContents() : static function (int $size) use ($body) {
```
Comment (veewee) [inline src/Symfony/Component/HttpClient/Psr18Client.php]: Can this logic also be applied to `HttplugClient`?

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpClient/Psr18Client.php]: sure, updated !

**Comment by nicolas-grekas** [comment]
Thank you @ajgarlag.
