### PR TITLE
[Mailer] Set default crypto method

### LINKED ISSUE #31105: [Mailer] stream_socket_enable_crypto php warning about crypto type
**Symfony version(s) affected**:
4.3-dev

**Description**  
When using the `EsmtpTransport` transport with `tls` encryption I receive a PHP warning:
````
PHP Warning:  stream_socket_enable_crypto(): When enabling encryption you must specify the crypto type in .../vendor/symfony/mailer/Transport/Smtp/Stream/SocketStream.php on line 156
````

**How to reproduce**  
````
$transport = (new EsmtpTransport('example.com', 587, 'tls'))
    ->setUsername('...')
    ->setPassword('...');
````

**Possible Solution**  
Honestly I have no clue on how `stream_socket_enable_crypto` should work, sorry.

### PR DESCRIPTION
**Pull request by bpolaszek**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #31105
| License | MIT
| Doc PR | -

This PR fixes #31105 by providing `STREAM_CRYPTO_METHOD_TLS_CLIENT | STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT | STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT` as  default crypto method when none is defined in user options and TLS is enabled.

### CODE REVIEW

File: src/Symfony/Component/Mailer/Transport/Smtp/Stream/SocketStream.php [hunk 1]
```diff
@@ -140,6 +140,9 @@ public function initialize(): void
         if ($this->streamContextOptions) {
             $options = array_merge($options, $this->streamContextOptions);
         }
+        if ($this->isTLS()) {
+            $options['ssl']['crypto_method'] = $options['ssl']['crypto_method'] ?? STREAM_CRYPTO_METHOD_TLS_CLIENT;
```
Comment (stof) [inline src/Symfony/Component/Mailer/Transport/Smtp/Stream/SocketStream.php]: this only enables TLS 1.0, which is not good for server compatibility.

Comment (stof) [reply src/Symfony/Component/Mailer/Transport/Smtp/Stream/SocketStream.php]: a better default might be `STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT | STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT | STREAM_CRYPTO_METHOD_TLSv1_0_CLIENT`  (or maybe without TLS 1.0)

Comment (stof) [reply src/Symfony/Component/Mailer/Transport/Smtp/Stream/SocketStream.php]: see https://www.php.net/manual/fr/function.stream-socket-enable-crypto.php#119122

Comment (stof) [reply src/Symfony/Component/Mailer/Transport/Smtp/Stream/SocketStream.php]: actually, using `STREAM_CRYPTO_METHOD_TLS_CLIENT | STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT | STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT` is even better, as `STREAM_CRYPTO_METHOD_TLS_CLIENT` has saner defaults in PHP 7.3+ (https://wiki.php.net/rfc/improved-tls-constants) so this supports both 7.3+ with proper TLS (including TLS 1.3 once supported) but also older versions (by forcing TLS 1.1 and 1.2 support)

Comment (bpolaszek) [reply src/Symfony/Component/Mailer/Transport/Smtp/Stream/SocketStream.php]: @stof I totally trust you on that point :simple_smile:

**Comment by fabpot** [comment]
@bpolaszek Looks like an unrelated commit is part of your PR now (from a PR I've just merged).

**Comment by bpolaszek** [comment]
@fabpot Yes, since travis and appveyor failed on my 2nd commit, I tried to rebase and it looks like it's all messed up... I'm trying again.

**Comment by bpolaszek** [comment]
Well, builds are still failing but I don't think it's related.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @bpolaszek.

**Comment by xavismeh** [comment]
Works now like a charm using Amazon SES transport — which relays on (e)smtp transport. Thank you @bpolaszek !
