### PR TITLE
[TypeInfo] Fix type alias resolving

### LINKED ISSUE #60598: [PropertyInfo][TypeInfo] Unable to validate doctrine/orm v2 PersistentCollection
### Symfony version(s) affected

7.3

### Description

The TypeInfo component seems to be unable to parse a `Doctrine\ORM\PersistentCollection` object when using doctrine/orm v2. I am seeing the following exception thrown when attempting to validate an object with a PersistentCollection as a property:

```
In StringTypeResolver.php line 88:
                                                                                                                                                                                                                                                            
  [Symfony\Component\TypeInfo\Exception\UnsupportedException]                                                                                                                                                                                               
  Cannot resolve "array{cache?: array, cascade: array<string>, declared?: class-string, fetch: mixed, fieldName: string, id?: bool, inherited?: class-string, indexBy?: string, inversedBy: (string | null), isCascadeRemove: bool, isCascadePersist: bool  
  , isCascadeRefresh: bool, isCascadeMerge: bool, isCascadeDetach: bool, isOnDeleteCascade?: bool, isOwningSide: bool, joinColumns?: array<JoinColumnData>, joinColumnFieldNames?: array<string, string>, joinTable?: array, joinTableColumns?: list<mixed  
  >, mappedBy: (string | null), orderBy?: array, originalClass?: class-string, originalField?: string, orphanRemoval?: bool, relationToSourceKeyColumns?: array, relationToTargetKeyColumns?: array, sourceEntity: class-string, sourceToTargetKeyColumns?  
  : array<string, string>, targetEntity: class-string, targetToSourceKeyColumns?: array<string, string>, type: int, unique?: bool}".                                                                                                                        
                                                                                                                                                                                                                                                            

Exception trace:
  at /app/my_project/vendor/symfony/type-info/TypeResolver/StringTypeResolver.php:88
 Symfony\Component\TypeInfo\TypeResolver\StringTypeResolver->resolve() at /app/my_project/vendor/symfony/type-info/TypeContext/TypeContextFactory.php:207
 Symfony\Component\TypeInfo\TypeContext\TypeContextFactory->collectTypeAliases() at /app/my_project/vendor/symfony/type-info/TypeContext/TypeContextFactory.php:74
 Symfony\Component\TypeInfo\TypeContext\TypeContextFactory->createFromClassName() at /app/my_project/vendor/symfony/type-info/TypeContext/TypeContextFactory.php:217
 Symfony\Component\TypeInfo\TypeContext\TypeContextFactory->collectTypeAliases() at /app/my_project/vendor/symfony/type-info/TypeContext/TypeContextFactory.php:74
 Symfony\Component\TypeInfo\TypeContext\TypeContextFactory->createFromClassName() at /app/my_project/vendor/symfony/property-info/Extractor/PhpStanExtractor.php:209
 Symfony\Component\PropertyInfo\Extractor\PhpStanExtractor->getType() at /app/my_project/vendor/symfony/property-info/PropertyInfoExtractor.php:70
 Symfony\Component\PropertyInfo\PropertyInfoExtractor->getType() at /app/my_project/vendor/symfony/validator/Mapping/Loader/PropertyInfoLoader.php:193
 Symfony\Component\Validator\Mapping\Loader\PropertyInfoLoader->getPropertyTypes() at /app/my_project/vendor/symfony/validator/Mapping/Loader/PropertyInfoLoader.php:70
 Symfony\Component\Validator\Mapping\Loader\PropertyInfoLoader->loadClassMetadata() at /app/my_project/vendor/symfony/validator/Mapping/Loader/LoaderChain.php:48
 Symfony\Component\Validator\Mapping\Loader\LoaderChain->loadClassMetadata() at /app/my_project/vendor/symfony/validator/Mapping/Factory/LazyLoadingMetadataFactory.php:96
 Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory->getMetadataFor() at /app/my_project/vendor/symfony/validator/Validator/RecursiveContextualValidator.php:290
 Symfony\Component\Validator\Validator\RecursiveContextualValidator->validateObject() at /app/my_project/vendor/symfony/validator/Validator/RecursiveContextualValidator.php:126
 Symfony\Component\Validator\Validator\RecursiveContextualValidator->validate() at /app/my_project/vendor/symfony/validator/Validator/RecursiveValidator.php:81
 Symfony\Component\Validator\Validator\RecursiveValidator->validate() at /app/my_project/vendor/symfony/validator/Validator/TraceableValidator.php:58
 Symfony\Component\Validator\Validator\TraceableValidator->validate() at /app/my_project/src/Command/ValidateCommand.php:30
```

### How to reproduce

Run the following commands to create a new project:

```console
symfony new --webapp my_project
cd my_project
composer require doctrine/orm:2.20.3 -W
bin/console make:command app:validate
```

Update the ValidateCommand as follows:

```php
<?php

namespace App\Command;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\PersistentCollection;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

#[AsCommand(name: 'app:validate')]
class ValidateCommand extends Command
{
    public function __construct(
        private readonly ValidatorInterface     $validator,
        private readonly EntityManagerInterface $entityManager
    )
    {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $persistentCollection = new PersistentCollection($this->entityManager, new ClassMetadata(''), new ArrayCollection());

        $this->validator->validate($persistentCollection);

        return Command::SUCCESS;
    }
}
```

Run the following:

```console
bin/console app:validate
```

And see this error:

```
In StringTypeResolver.php line 88:
                                                                                                                                                                                                                                                            
  Cannot resolve "array{cache?: array, cascade: array<string>, declared?: class-string, fetch: mixed, fieldName: string, id?: bool, inherited?: class-string, indexBy?: string, inversedBy: (string | null), isCascadeRemove: bool, isCascadePersist: bool  
  , isCascadeRefresh: bool, isCascadeMerge: bool, isCascadeDetach: bool, isOnDeleteCascade?: bool, isOwningSide: bool, joinColumns?: array<JoinColumnData>, joinColumnFieldNames?: array<string, string>, joinTable?: array, joinTableColumns?: list<mixed  
  >, mappedBy: (string | null), orderBy?: array, originalClass?: class-string, originalField?: string, orphanRemoval?: bool, relationToSourceKeyColumns?: array, relationToTargetKeyColumns?: array, sourceEntity: class-string, sourceToTargetKeyColumns?  
  : array<string, string>, targetEntity: class-string, targetToSourceKeyColumns?: array<string, string>, type: int, unique?: bool}".                                                                                                                        
                                                                                                                                                                                                                                                            

In StringTypeResolver.php line 295:
                                          
  Unhandled "JoinColumnData" identifier.                           

app:validate
```


### Possible Solution

_No response_

### Additional Context

_No response_

### LINKED ISSUE #60657: [TypeInfo] Fails to parse types defined in class
### Symfony version(s) affected

7.3.0

### Description

In 7.3 type info crashes when it encounters a doc block referencing other types.

The types are only for PHPStan or IDE auto completion and shouldn't have any significance to Symfony. The error occurs in a live component that has a service injected with such annotations.

```
Symfony\Component\TypeInfo\Exception\UnsupportedException
Cannot resolve "list<MyType>".

DomainException
Unhandled "MyType" identifier.
```

### How to reproduce

Have type info parse the doc block of this class:

```php
<?php

/**
 * @phpstan-type MyType array{
 *     key1: string,
 *     key2?: bool,
 * }
 * 
 * @phpstan-type TypesList list<MyType>
 */
readonly class Example
{
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fixes #60598, fixes #60657
| License       | MIT

Take other type aliases into account when resolving type aliases, no matter the order they're defined.

### CODE REVIEW

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 1]
```diff
@@ -199,32 +199,82 @@ private function collectTypeAliases(\ReflectionClass $reflection, TypeContext $t
...
+                $resolved[$alias] = $this->stringTypeResolver->resolve($type, $typeContext);
+                unset($toResolve[$alias]);
+                $succeeded = true;
+            } catch (UnsupportedException $lastFailure) {
+                $lastFailingAlias = $alias;
             }
+        }
+
+        // nothing has succeeded, the result won't be different from the
+        // previous time, we can stop here.
```
Comment (OskarStark) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]:
```suggestion
        // previous one, we can stop here.
```

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 2]
```diff
@@ -199,32 +199,82 @@ private function collectTypeAliases(\ReflectionClass $reflection, TypeContext $t
...
-            if (!$tag->value instanceof TypeAliasTagValueNode) {
+        $resolvedAliases = [];
+
+        foreach ($this->getPhpDocNode($rawDocNode)->getTagsByName('@psalm-import-type') + $this->getPhpDocNode($rawDocNode)->getTagsByName('@phpstan-import-type') as $tag) {
+            if (!$tag->value instanceof TypeAliasImportTagValueNode) {
                 continue;
             }
 
-            $aliases[$tag->value->alias] = $this->stringTypeResolver->resolve((string) $tag->value->type, $typeContext);
+            /** @var ObjectType $importedFromType */
```
Comment (stof) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: should we use a `@var` to tell Psalm that our assumption is true here, or should we rather check it for real ?

Valid phpdoc tags for a type import will indeed have an object type here. But should we trigger a fatal error on next line when calling `$importedFromType->getClassName()` for an invalid tag, or should we rather skip invalid tags (or report a meaningful error) ?

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 3]
```diff
@@ -199,32 +199,82 @@ private function collectTypeAliases(\ReflectionClass $reflection, TypeContext $t
...
+
+        // nothing has succeeded, the result won't be different from the
+        // previous one, we can stop here.
+        if (!$succeeded) {
+            throw new LogicException(\sprintf('Cannot resolve "%s" type alias.', $lastFailingAlias), 0, $lastFailure);
+        }
 
-            $aliases[$tag->value->importedAs ?? $tag->value->importedAlias] = $typeAlias;
+        if ([] !== $toResolve) {
+            return $this->resolveTypeAliases($toResolve, $resolved, $typeContext);
```
Comment (stof) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php:277]: how does this recursive call behave if someone creates a circular reference between type aliases ? Will it do an infinite loop or will it be detected properly by the previous exception ?

Comment (stof) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php:277]: btw, it might be great to have a test covering this behavior.

Comment (mtarld) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php:277]: I just made a test to make sure that there is no infinite loop, and it seems to be ok:
```
/**
 * @phpstan-type Foo = array{0: Bar}
 * @phpstan-type Bar = array{0: Foo}
 */
final class Dummy {}
```

results in:
```
There was 1 error:
Symfony\Component\TypeInfo\Exception\LogicException: Cannot resolve "Bar" type alias.
Caused by Symfony\Component\TypeInfo\Exception\UnsupportedException: Cannot resolve "array{0: Foo}".
Caused by DomainException: Unhandled "Foo" identifier.
```

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php (hunk 2 above)
Comment (mtarld) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: You're right, I updated the code to throw a `LogicException` with the following message: `Type alias "%s" is not imported from a valid class name.`

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php (hunk 3 above)
Comment (mtarld) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php:277]: I'll add that test

**Review by stof — APPROVED** [review]

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 4]
```diff
@@ -199,32 +199,85 @@ private function collectTypeAliases(\ReflectionClass $reflection, TypeContext $t
...
+
+    /**
+     * @param array<string, string> $toResolve
+     * @param array<string, Type>   $resolved
+     *
+     * @return array<string, Type>
+     */
+    private function resolveTypeAliases(array $toResolve, array $resolved, TypeContext $typeContext): array
+    {
+        if ([] === $toResolve) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]:
```suggestion
        if (!$toResolve) {
```

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php [hunk 5]
```diff
@@ -199,32 +199,85 @@ private function collectTypeAliases(\ReflectionClass $reflection, TypeContext $t
...
+        }
+
+        // nothing has succeeded, the result won't be different from the
+        // previous one, we can stop here.
+        if (!$succeeded) {
+            throw new LogicException(\sprintf('Cannot resolve "%s" type alias.', $lastFailingAlias), 0, $lastFailure);
+        }
 
-            $aliases[$tag->value->importedAs ?? $tag->value->importedAlias] = $typeAlias;
+        if ([] !== $toResolve) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]:
```suggestion
        if ($toResolve) {
```

**Review by nicolas-grekas — APPROVED** [review]
empty value comparisons... :gun:

File: src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php (hunk 4 above)
Comment (mtarld) [reply src/Symfony/Component/TypeInfo/TypeContext/TypeContextFactory.php]: :sweat_smile:

**Comment by nicolas-grekas** [comment]
Thank you @mtarld.

**Comment by Seldaek** [comment]
This looks nice but any chance of loading type aliases defined in the phpstan.neon file? :s I get a crash in cache warmup on 7.3.1 because it doesn't know some type that is defined in there like:

```
parameters:
    typeAliases:
        \Type\Language: 'value-of<\App\Locale\Languages::LOCALES>'
```

Then on user class we have:

```
/**
 * @phpstan-type UserAttributes array{
 *     language?: \Type\Language
 * }
 */
```
