### PR TITLE
Fix Integration tests skipped with Redis cluster

### LINKED ISSUE #49285: Integration tests skipped with Redis cluster should be fixed
Our integration tests skip many Redis tests with:
`Failed to retrieve master information from master name "" and address "127.0.0.1:7006".`

See latest jobs on https://github.com/symfony/symfony/actions/workflows/integration-tests.yml?query=branch%3A6.3

### PR DESCRIPTION
**Pull request by maxbeckers**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49285
| License       | MIT
| Doc PR        | n/a

It seems to me, that the `getenv('MESSENGER_REDIS_SENTINEL_MASTER')` in the `setUp()` might return `false` because it's unset. To ignore the sentinel, it must be null:
https://github.com/symfony/symfony/blob/090033332fa4eb5e7475111136b1cce260edffa4/src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php#L95-L100

### CODE REVIEW

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php [hunk 1]
```diff
@@ -154,7 +154,7 @@ private static function initializeRedis(\Redis|Relay $redis, string $host, int $
      */
     private static function initializeRedisCluster(?\RedisCluster $redis, array $hosts, string|array|null $auth, array $params): \RedisCluster
     {
-        $redis ??= new \RedisCluster(null, $hosts, $params['timeout'], $params['read_timeout'], (bool) $params['persistent'], $auth, ...\defined('Redis::SCAN_PREFIX') ? [$params['ssl'] ?? null] : []);
+        $redis ??= new \RedisCluster(null, $hosts, $params['timeout'], $params['read_timeout'], isset($params['persistent_id']), $auth, ...\defined('Redis::SCAN_PREFIX') ? [$params['ssl'] ?? null] : []);
```
Comment (maxbeckers) [inline src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: Here I changed it to `isset($params['persistent_id'])` because `persistent` is not a default option and this option seems to be for me for this case. Otherwise I'd have do add the default option for `persistent`.

File: .github/workflows/integration-tests.yml [hunk 2]
```diff
@@ -49,7 +49,7 @@ jobs:
         ports:
           - 16379:6379
       redis-cluster:
-        image: grokzen/redis-cluster:latest
+        image: grokzen/redis-cluster:6.0.0
```
Comment (maxbeckers) [inline .github/workflows/integration-tests.yml]: I guess using `latest` is not always the best way, because you don't know with which version the tests were running. In this image the `latest` tag should be `7.0.7` for now, but it doesn't match that version. And we are using redis 6.0.0 for all of our redis tests, so we should do it here this way as well.

Edit: The `latest` tag was added in #48761

**Comment by maxbeckers** [comment]
For now there are failing 5 tests with `Invalid HELLO reply, Redis Server version may be too old (RELAY_ERR_COMPAT; commands.c:6660)`. I'll need to investigate a bit more of time to that or maybe someone else has an idea.

File: src/Symfony/Component/Messenger/Bridge/Redis/Tests/Transport/RelayExtIntegrationTest.php [hunk 3]
```diff
@@ -21,8 +21,45 @@
...
+    public const SKIP_TEST_NOT_RUNNING_WITH_RELAY = 'This test doesn\'t work with relay.';
+
     protected function createRedisClient(): \Redis|Relay
     {
         return new Relay();
     }
+
+    public function testConnectionSendAndGetDelayed()
+    {
+        self::markTestSkipped(self::SKIP_TEST_NOT_RUNNING_WITH_RELAY);
```
Comment (maxbeckers) [inline src/Symfony/Component/Messenger/Bridge/Redis/Tests/Transport/RelayExtIntegrationTest.php]: For now I added a skip to the tests not working with relay. Could be another issue to fix this tests working with relay. In this PR i focussed on the topic of the ticket, that cluster tests were not running. This problems came up after enabling this.

File: .github/workflows/integration-tests.yml (hunk 2 above)
Comment (stof) [reply .github/workflows/integration-tests.yml]: We should probably use 6.2.8 instead of 6.0.0. According to https://relay.so/docs/1.x/installation#requirements, Relay requires Redis 6.2.7+

Comment (maxbeckers) [reply .github/workflows/integration-tests.yml]: Then we should update redis and redis-cluster to this version IMHO. Maybe this fixes the skipped relay tests, I'll try this tomorrow.

Comment (maxbeckers) [reply .github/workflows/integration-tests.yml]: I updated to 6.2.8. But the skipped tests are still failing.

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: `$params['persistent'] ?? false`?

File: src/Symfony/Component/Messenger/Bridge/Redis/Tests/Transport/RelayExtIntegrationTest.php [hunk 4]
```diff
@@ -21,8 +21,45 @@
  */
 class RelayExtIntegrationTest extends RedisExtIntegrationTest
 {
+    public const SKIP_TEST_NOT_RUNNING_WITH_RELAY = 'This test doesn\'t work with relay.';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Bridge/Redis/Tests/Transport/RelayExtIntegrationTest.php]: no need for the const, let's inline

**Comment by nicolas-grekas** [comment]
I suppose we should merge this on 5.4?

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php (hunk 1 above)
Comment (maxbeckers) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: fine with that one.

File: src/Symfony/Component/Messenger/Bridge/Redis/Tests/Transport/RelayExtIntegrationTest.php (hunk 4 above)
Comment (maxbeckers) [reply src/Symfony/Component/Messenger/Bridge/Redis/Tests/Transport/RelayExtIntegrationTest.php]: Ok

**Comment by maxbeckers** [comment]
@nicolas-grekas yes, i didn't check this, in the issue was mentioned the 6.3 branch. Is it possible to handle this during the merge or should I rebase it?

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php [hunk 5]
```diff
@@ -154,7 +154,7 @@ private static function initializeRedis(\Redis|Relay $redis, string $host, int $
      */
     private static function initializeRedisCluster(?\RedisCluster $redis, array $hosts, string|array|null $auth, array $params): \RedisCluster
     {
-        $redis ??= new \RedisCluster(null, $hosts, $params['timeout'], $params['read_timeout'], (bool) $params['persistent'], $auth, ...\defined('Redis::SCAN_PREFIX') ? [$params['ssl'] ?? null] : []);
+        $redis ??= new \RedisCluster(null, $hosts, $params['timeout'], $params['read_timeout'], (bool) $params['persistent'] ?? false, $auth, ...\defined('Redis::SCAN_PREFIX') ? [$params['ssl'] ?? null] : []);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: `(bool) ($params['persistent'] ?? false)`

**Comment by nicolas-grekas** [comment]
Please submit another PR for 5.4, I'll use this one when merging up.

**Comment by nicolas-grekas** [comment]
Thank you @maxbeckers.
