### PR TITLE
[AssetMapper] Deprecate unused method `splitPackageNameAndFilePath`

### LINKED ISSUE #54123: [AssetMapper] Remove unused method / BC break ?
### Symfony version(s) affected

7.0

### Description

This method ([ImportMapConfigReader::splitPackageNameAndFilePath](https://github.com/symfony/symfony/blob/f8611cf821f8ab19c3d5f1984473847ad774c45e/src/Symfony/Component/AssetMapper/ImportMap/ImportMapConfigReader.php#L175)) is unused, is it OK to delete it or is it covered by BC ?

(i do believe it stayed here by accident)

### How to reproduce

The method has been moved to https://github.com/symfony/symfony/blob/7.0/src/Symfony/Component/AssetMapper/ImportMap/ImportMapEntry.php#L69

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by smnandre**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Issues        | Fix #54123
| License       | MIT

This method is not used in the codebase, and duplicates` ImportMapEntry::splitPackageNameAndFilePath()`

### CODE REVIEW

**Review by maxbeckers — APPROVED** [review]

File: src/Symfony/Component/AssetMapper/ImportMap/ImportMapConfigReader.php [hunk 1]
```diff
@@ -174,6 +174,8 @@ private function getRootDirectory(): string
 
     public static function splitPackageNameAndFilePath(string $packageName): array
```
Comment (xabbuh) [inline src/Symfony/Component/AssetMapper/ImportMap/ImportMapConfigReader.php:178]: We should also add a `@deprecated` annotation on the method.

**Review by xabbuh — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/AssetMapper/ImportMap/ImportMapConfigReader.php [hunk 2]
```diff
@@ -174,6 +174,8 @@ private function getRootDirectory(): string
...
     {
+        trigger_deprecation('symfony/asset-mapper', '7.1', 'The method "%s()" is deprecated and will be removed in 8.0.', __METHOD__);
```
Comment (stof) [inline src/Symfony/Component/AssetMapper/ImportMap/ImportMapConfigReader.php]: This should mention the replacement

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/AssetMapper/CHANGELOG.md [hunk 3]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+7.1
+---
+
+ * Deprecate `ImportMapConfigReader::splitPackageNameAndFilePath()`, use `ImportMapEntry::splitPackageNameAndFilePath()` instead
```
Comment (xabbuh) [inline src/Symfony/Component/AssetMapper/CHANGELOG.md:7]: this should also be added to `UPGRADE-7.1.md`

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @smnandre.
