### PR TITLE
[HttpKernel][FrameworkBundle] fix compat with Debug component

### LINKED ISSUE #36009: Deprecation Notices Missing from Toolbar and Logs
**Symfony version(s) affected**: 4.4.*

**Description**  
All deprecation notices are somehow being suppressed intermittently.  Some symfony deprecation notices show up but none from my own app show up in the symfony toolbar.  When I look at the logs there are no logs for `php.INFO`.  

**How to reproduce**  
**config/packages/dev/monolog.yaml**
```
monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['!event']
```

**Anywhere in src/**
```
trigger_error('Something is deprecated.', E_USER_DEPRECATED);
```

Expected output in dev.log:
```
[YYYY-MM-DD hh:mm:ss] php.INFO: User Deprecated: Something is deprecated. {}[]
````

Actual output: nothing

**Possible Solution**  
None that I'm aware.

**Additional context**  
This all happened after I changed my configs from the Symfony 3 style to the Symfony 4 style.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36009
| License       | MIT
| Doc PR        | -

Fixes the issue as described by @stof in #36009

### CODE REVIEW

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

File: src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php [hunk 1]
```diff
@@ -89,6 +90,9 @@ class FrameworkBundle extends Bundle
     public function boot()
     {
         ErrorHandler::register(null, false)->throwAt($this->container->getParameter('debug.error_handler.throw_at'), true);
+        if (class_exists(LegacyErrorHandler::class, false)) {
+            LegacyErrorHandler::register(null, false)->throwAt($this->container->getParameter('debug.error_handler.throw_at'), true);
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php:94]: doesn't this mean that the legacy one wins when both component are installed ?

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php:94]: nope, because of the 2nd argument: `$replace = false`
