### PR TITLE
 [AssetMapper] Fix exception if assets directory is missing in production

### LINKED ISSUE #53669: [AssetMapper] Asset Mapper fail after deleting "assets" folder
### Symfony version(s) affected

7.*

### Description

After compiling assets, if we delete the original assets folder (I don't want it on prod), symfony crash with :

An exception has been thrown during the rendering of a template ("The asset mapper directory "assets/" does not exist.").

`{% block importmap %}{{ importmap('app') }}{% endblock %}`

### How to reproduce

- Setup a new symfony project
- create a controller to display a page
- compile assets
- check your application (it's works)
- delete the assets folder
- check your application (it's don't work anymore)

```
symfony new --webapp assetmappertest .
symfony console make:controller home
symfony console assets:install public
symfony console importmap:install
symfony console asset-map:compile
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rynhndrcksn**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #53669 
| License       | MIT

During deployment some people will compile their assets with Asset Mapper then delete the root `assets/` directory. This causes Asset Mapper to throw an exception, and a common work around people mentioned in the issue is to create an empty `assets/` directory.

This PR makes it so the exception is only thrown while `kernel.debug` is equal to true, letting developers know locally that there's an issue, but allowing people to safely do this in their `production` environments.

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -1348,11 +1348,13 @@ private function registerAssetMapperConfiguration(array $config, ContainerBuilde
...
             $excludedPathPatterns[] = Glob::toRegex($path, true, false);
         }
+        $strictMode = $container->getParameter('kernel.debug');
 
         $container->getDefinition('asset_mapper.repository')
             ->setArgument(0, $paths)
             ->setArgument(2, $excludedPathPatterns)
-            ->setArgument(3, $config['exclude_dotfiles']);
+            ->setArgument(3, $config['exclude_dotfiles'])
+            ->setArgument(4, $strictMode);
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: can be reverted, the change on the config is enough

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/asset_mapper.php [hunk 2]
```diff
@@ -75,6 +75,7 @@
                 param('kernel.project_dir'),
                 abstract_arg('array of excluded path patterns'),
                 abstract_arg('exclude dot files'),
+                abstract_arg('strict mode'),
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/asset_mapper.php]:
```suggestion
                param('kernel.debug'),
```

File: src/Symfony/Component/AssetMapper/AssetMapperRepository.php [hunk 3]
```diff
@@ -161,7 +162,9 @@ private function getDirectories(): array
                 continue;
             }
 
-            throw new \InvalidArgumentException(sprintf('The asset mapper directory "%s" does not exist.', $path));
+            if ($this->strictMode) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/AssetMapper/AssetMapperRepository.php]: we need this check on line 152 also, don't we?

File: src/Symfony/Component/AssetMapper/CHANGELOG.md [hunk 4]
```diff
@@ -18,6 +18,7 @@ CHANGELOG
  * Add a `importmap:audit` command to check for security vulnerability advisories in dependencies
  * Add a `importmap:outdated` command to check for outdated packages
  * Change the polyfill used for the importmap renderer from a URL to an entry in the importmap
+ * Fix exception if assets directory is missing in production environment
```
Comment (nicolas-grekas) [inline src/Symfony/Component/AssetMapper/CHANGELOG.md]: should be removed, this file is only for new features (changelog for bug fixes is generated automatically)

File: src/Symfony/Component/AssetMapper/AssetMapperRepository.php [hunk 5]
```diff
@@ -34,6 +34,7 @@ public function __construct(
         private readonly string $projectRootDir,
         private readonly array $excludedPathPatterns = [],
         private readonly bool $excludeDotFiles = true,
+        private readonly bool $strictMode = false
```
Comment (nicolas-grekas) [inline src/Symfony/Component/AssetMapper/AssetMapperRepository.php]: or just $debug? "strict" sounds like a promise with no definition to me :)

File: src/Symfony/Component/AssetMapper/AssetMapperRepository.php (hunk 3 above)
Comment (rynhndrcksn) [reply src/Symfony/Component/AssetMapper/AssetMapperRepository.php]: Line 166 is what threw when the application was set to `prod` and the `assets/` directory was missing. I erred on the side of caution and only put the check around that, rather than around both. I can put this check on line 152 as well though!

File: src/Symfony/Component/AssetMapper/AssetMapperRepository.php (hunk 5 above)
Comment (smnandre) [reply src/Symfony/Component/AssetMapper/AssetMapperRepository.php]: The problem here is there is some counter-intuitive logic.... Beeing strict when in dev and allowing to bypass some checks in PROD feels a bit weird.

And i don't think we should set "not strict" per default in prod.

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/asset_mapper.php (hunk 2 above)
Comment (weaverryan) [reply src/Symfony/Bundle/FrameworkBundle/Resources/config/asset_mapper.php]: Yup, Nicolas is right - I gave too complex of a recommendation. Do this, then no change needed in `FrameworkExtension`.

**Comment by smnandre** [comment]
With this PR, if someone runs the following command what would happen, exceptions would not be thrown if some directory is missing ? 

```
APP_ENV=prod sf asset-map:compile
```

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 1 above)
Comment (rynhndrcksn) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Done!

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/asset_mapper.php (hunk 2 above)
Comment (rynhndrcksn) [reply src/Symfony/Bundle/FrameworkBundle/Resources/config/asset_mapper.php]: Done!

File: src/Symfony/Component/AssetMapper/AssetMapperRepository.php (hunk 3 above)
Comment (rynhndrcksn) [reply src/Symfony/Component/AssetMapper/AssetMapperRepository.php]: I've added the check to line 152 as well!

File: src/Symfony/Component/AssetMapper/CHANGELOG.md (hunk 4 above)
Comment (rynhndrcksn) [reply src/Symfony/Component/AssetMapper/CHANGELOG.md]: Removed!

File: src/Symfony/Component/AssetMapper/AssetMapperRepository.php (hunk 5 above)
Comment (rynhndrcksn) [reply src/Symfony/Component/AssetMapper/AssetMapperRepository.php]: I agree that `$debug` is a better choice. That has been changed!

**Comment by rynhndrcksn** [comment]
@smnandre I've attached 2 screenshots of what happens when the `APP_ENV=prod symfony console asset-map:compile` command is ran.

__If the `assets/` directory is in place, then this is the output (as expected)__:

APP_ENV=prod symfony console asset-map:compile being ran with an assets/ directory

__If the `assets/` directory is missing, then this is the output__:

APP_ENV=prod symfony console asset-map:compile being ran with no assets/ directory

So during the deployment/asset compilation process people will still be notified if the `assets/` directory is missing :)

**Comment by smnandre** [comment]
> @smnandre I've attached 2 screenshots of what happens when `APP_ENV=prod symfony console asset-map:compile` command is ran.
> So during the deployment/asset compilation process people will still be notified if the `assets/` directory is missing :)

Perfect for me, thank you very much 👍

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @rynhndrcksn.

File: src/Symfony/Component/AssetMapper/AssetMapperRepository.php [hunk 6]
```diff
@@ -34,6 +34,7 @@ public function __construct(
         private readonly string $projectRootDir,
         private readonly array $excludedPathPatterns = [],
         private readonly bool $excludeDotFiles = true,
+        private readonly bool $debug = false
```
Comment (nicolas-grekas) [inline src/Symfony/Component/AssetMapper/AssetMapperRepository.php:37]: I set this to true by default in aa469d9fb1

Comment (rynhndrcksn) [reply src/Symfony/Component/AssetMapper/AssetMapperRepository.php:37]: When I did that locally while my project was set to `prod` mode, it causes Symfony to crash and return a 500 error.

Screenshot of a 500 internal server error

Is it possible that `param('kernel.debug'),` ([link to line](https://github.com/rynhndrcksn/symfony/blob/962a04450591a0c84bc1b5a0b0131217c406d907/src/Symfony/Bundle/FrameworkBundle/Resources/config/asset_mapper.php#L78)) isn't passing in `false` when the site is in `prod` mode, making `AssetMapperRepository.php` default to true, making it so the `$this->debug` checks succeed while the site is in `prod` mode?

Comment (stof) [reply src/Symfony/Component/AssetMapper/AssetMapperRepository.php:37]: you can still use the prod environment in debug mode if you want locally. The prod environment _defaults_ to non-debug mode, but the `APP_DEBUG` env variable still wins over this default.
