### PR TITLE
[Console] Re-enable hyperlinks in Konsole/Yakuake

### LINKED ISSUE #31809: [Console] Hyperlinks broken on Konsole and PhpStorm terminal
**Symfony version(s) affected**: 4.3.0

**Description**  
On Konsole and Yakuake  the visualization of `<href>` tag is broken, and the output is shown enclosed by backslashes.
On PhpStorm terminal the output "crashes": at the first escape sequence the terminal stops printing the text, but the execution terminates smoothly.
On the same machine (Kubuntu Disco Dingo) XTerm and system console work well, ignoring the unrecognized escape sequences.

**How to reproduce**  
Just run a command who outputs links. For me it was a simple `bin/console debug:router` in a Symfony Framework project, as I integrated the source linking to PhpStorm.

**Possible Solution**  
I've debugged all the way and found that the check for unsupported terminal emulators is on line 189 of `Formatter/OutputFormatterStile.php`:
```php
if (null === $this->handlesHrefGracefully) {
    $this->handlesHrefGracefully = 'JetBrains-JediTerm' !== getenv('TERMINAL_EMULATOR');
}
```
I understand thas is the correct point to work on, but I really don't know anything about terminal emulators. If someone points me in the correct direction I can create a pull request.

**Additional context**  
The output on PhpStorm terminal:
image

The output on a Yakuake terminal (same engine of Konsole); cut because long output:
image

### PR DESCRIPTION
**Pull request by OndraM**
| Q             | A
| ------------- | ---
| Branch?       | 4.4 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #31809 
| License       | MIT

Hyperlinks feature was broken in KDE's Konsole/Yakuake (#31809) and thus disabled by #31849.

But the feature has been recently [implemented](https://invent.kde.org/utilities/konsole/-/merge_requests/138), and is about to be released in KDE 20.12 on December 10th 2020, see [release notes](https://community.kde.org/Releases/20.12_Release_Notes#Konsole). 

obrazek

Tested in RC version and seems to be working fine. The feature is disabled by default (as per security concerns), but even when disabled, it just gracefully don't show the links.

### CODE REVIEW

File: src/Symfony/Component/Console/Formatter/OutputFormatterStyle.php [hunk 1]
```diff
@@ -166,7 +166,7 @@ public function apply($text)
         $unsetCodes = [];
 
         if (null === $this->handlesHrefGracefully) {
-            $this->handlesHrefGracefully = 'JetBrains-JediTerm' !== getenv('TERMINAL_EMULATOR') && !getenv('KONSOLE_VERSION');
```
Comment (jderusse) [inline src/Symfony/Component/Console/Formatter/OutputFormatterStyle.php:169]: if it doesn't work with older versions of use, shouldn't you check the version here, instead of enabling it for everyone?

Comment (OndraM) [reply src/Symfony/Component/Console/Formatter/OutputFormatterStyle.php:169]: Right, good idea!

**Review by chalasr — APPROVED** [review]

**Review by jderusse — APPROVED** [review]

**Comment by chalasr** [comment]
Good catch, thanks @OndraM.
