### PR TITLE
Fix #37740: Cast all Request parameter values to string

### LINKED ISSUE #37740: It is possible to pass request parameters of any type to the Symfony web crawler
**Symfony version(s) affected**: 5.1

**Description**  
It is possible to pass request parameters of any type to the Symfony web crawler, something that's not possible in actual requests.

**How to reproduce**  
On the sending end:
```
        $client = static::createClient();
        $client->request('POST', '/endpoint', [
            'foo' => 'bar',
            'baz' => 1.1,
            'boz' => Uuid::uuid4(),
        ]);
```
On the receiving end:
```
        var_dump($request->get('foo')); // 'bar'
        var_dump($request->get('baz')); // 1.1
        var_dump($request->get('boz')); // object(Ramsey\Uuid\Lazy\LazyUuidFromString)
```

**Possible Solution**  
Values in the request parameters should be restricted to strings. Any other type should result in an error.

### PR DESCRIPTION
**Pull request by rgeraads**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37740| License       | MIT

This fix ensures that all parameter values in Browserkit\Request are received as strings on the receiving end.

### CODE REVIEW

**Comment by stof** [comment]
This is not the right fix for the issue. For instance, `->attributes` is perfectly allowed to hold other types (for instance booleans) and that would be a BC break.

The right fix must be implemented in the conversion layer between BrowserKit and HttpFoundation, for the query and request parameters only.

**Comment by rgeraads** [comment]
Do you mean here? https://github.com/symfony/symfony/blob/786ba109d0a26b8bf7ada4aeb2d639da6599a586/src/Symfony/Component/HttpFoundation/Request.php#L391-L396

I can put the casting right before the switch/case

**Comment by stof** [comment]
No. This place is still in the HttpFoundation request object itself (which might add overhead the handling of actual web requests btw).

This should either be done when creating the BrowserKit request (might make sense as other BrowserKit implementations would also not be able to submit non-string values), or when converting from one to the other in https://github.com/symfony/symfony/blob/e1cfbd20feb1fabfa8a691795ee7a8080bced384/src/Symfony/Component/HttpKernel/HttpKernelBrowser.php#L131-L133

**Comment by rgeraads** [comment]
It would make most sense to put it in BrowserKit\Kernel then.

File: src/Symfony/Component/BrowserKit/Request.php [hunk 1]
```diff
@@ -113,4 +113,13 @@ public function getContent()
     {
         return $this->content;
     }
+
+    private static function convertAllValuesToString(array $parameters): array
```
Comment (fabpot) [inline src/Symfony/Component/BrowserKit/Request.php:117]: Could be inline.

**Review by fabpot — CHANGES_REQUESTED** [review]
Should target master.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @rgeraads.

**Comment by kernio** [comment]
Am I just wondering in addition to fix the "null" issue (that is good), why this modified behavior for parameters I passed as POST request?

Input request parameters 
array:8 [
  "profileId" => 1000
]

After
 array_walk_recursive($parameters, static function (&$value) {
            $value = (string) $value;
        });

array:8 [
  "profileId" => "1000"
]


Input validation for request
    /**
     * @Assert\Type(type="integer")
     * @Assert\NotNull
     */


Response:
Error: profileId should be "int"

**Comment by kernio** [comment]
> Am I just wondering in addition to fix the "null" issue (that is good), why this modified behavior for parameters I passed as POST request?
> 

And answer to my own question (for anyone who had the same issue) is not using "params" here that used for application/x-www-form-urlencoded, but using a body with JSON encoded parameters and a proper header. 


Before:

```
        $this->client->request(
            'POST',
            $uri,
            $parameters,
            [],
            array_merge(['HTTP_AUTHORIZATION' => sprintf('Bearer %s', $this->jwtToken)], $headers)
        );
```

After:

```
        $this->client->request(
            'POST',
            $uri,
            [],
            [],
            array_merge(
                ['HTTP_AUTHORIZATION' => sprintf('Bearer %s', $this->jwtToken), 'CONTENT_TYPE' => 'application/json'],
                $headers
            ),
            json_encode($parameters, JSON_THROW_ON_ERROR)
        );
```
