### PR TITLE
[Form] Do not fix URL protocol for relative URLs

### LINKED ISSUE #42329: [Form] Skipped URL protocol "//~" is normal but not valid by FixUrlProtocolListener
**Symfony version(s) affected**: <=5.3

**Description**

It is normal to use links without absolute protocol, just: [//symfony.com](//symfony.com) 

After following a link without a protocol (only with double slashes), browsers will automatically detect the protocol. So it is correct to use these links. Try and see: [//symfony.com](//symfony.com) 

But Symfony Form UrlType adds a default protocol to these URLs (//symfony.com => http:////symfony.com).

**How to reproduce**
Paste ```//symfony.com``` to Form UrlType, submit the form and see what happens. 

**Possible Solution**
In **Symfony\Component\Form\Extension\Core\EventListener\FixUrlProtocolListener**
Find:
```php
if ($this->defaultProtocol && $data && \is_string($data) && !preg_match('~^[\w+.-]+://~', $data)) {
```

Replace to:
```php
if ($this->defaultProtocol && $data && \is_string($data) && !preg_match('~^[\w+.-]+://~', $data) && 0 !== strpos($data, '//')) {
```

### PR DESCRIPTION
**Pull request by bogkonstantin**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Tickets | Fix #42329
| Deprecations? | no
| License       | MIT

Example when it doesn't work correctly:
/relative/path
The data will be changed to "http:///relative/path" (3 slashes)

### CODE REVIEW

**Comment by OskarStark** [comment]
Can you please add a test case?

Is this bug present in `4.4`? If yes, please target `4.4` branch, thank you

**Comment by bogkonstantin** [comment]
@OskarStark sure, done.

File: src/Symfony/Component/Form/Tests/Extension/Core/EventListener/FixUrlProtocolListenerTest.php [hunk 1]
```diff
@@ -44,6 +44,18 @@ public function testSkipKnownUrl()
...
+    public function testSkipRelativeUrl()
+    {
+        $data = '/relative/url';
+        $form = new Form(new FormConfigBuilder('name', null, new EventDispatcher()));
+        $event = new FormEvent($form, $data);
+
+        $filter = new FixUrlProtocolListener('http');
+        $filter->onSubmit($event);
+
+        $this->assertEquals('/relative/url', $event->getData());
```
Comment (OskarStark) [inline src/Symfony/Component/Form/Tests/Extension/Core/EventListener/FixUrlProtocolListenerTest.php]:
```suggestion
        $this->assertSame('/relative/url', $event->getData());
```
please, thanks

File: src/Symfony/Component/Form/Extension/Core/EventListener/FixUrlProtocolListener.php [hunk 2]
```diff
@@ -36,7 +36,7 @@ public function onSubmit(FormEvent $event)
     {
         $data = $event->getData();
 
-        if ($this->defaultProtocol && $data && \is_string($data) && !preg_match('~^[\w+.-]+://~', $data)) {
+        if ($this->defaultProtocol && $data && \is_string($data) && !preg_match('~^[\w+.-]+://~', $data) && false === strpos($data, '/')) {
```
Comment (94noni) [inline src/Symfony/Component/Form/Extension/Core/EventListener/FixUrlProtocolListener.php]: A recent PR for v4.4 replaces using « str_contains() »
Maybe leverage the same way
Also adding this check before the preg as it is « faster » :)

Comment (bogkonstantin) [reply src/Symfony/Component/Form/Extension/Core/EventListener/FixUrlProtocolListener.php]: Done

**Comment by bogkonstantin** [comment]
AppVeyor build is failed with:
```
Symfony\Component\VarDumper\Tests\Server\ConnectionTest::testDump
Symfony\Component\Process\Exception\ProcessTimedOutException: The process "c:\php\php.exe" exceeded the timeout of 9 seconds.
```

Seems like the Form is not the reason. Can you try to rerun it, guys?

**Comment by OskarStark** [comment]
You can ignore the AppVeyor build in this case, thanks

File: src/Symfony/Component/Form/Extension/Core/EventListener/FixUrlProtocolListener.php [hunk 3]
```diff
@@ -36,7 +36,7 @@ public function onSubmit(FormEvent $event)
     {
         $data = $event->getData();
 
-        if ($this->defaultProtocol && $data && \is_string($data) && !preg_match('~^[\w+.-]+://~', $data)) {
+        if ($this->defaultProtocol && $data && \is_string($data) && !str_contains($data, '/') && !preg_match('~^[\w+.-]+://~', $data)) {
```
Comment (ro0NL) [inline src/Symfony/Component/Form/Extension/Core/EventListener/FixUrlProtocolListener.php]: im not sure, but do we have a test for `domain.com/path`?

Comment (xabbuh) [reply src/Symfony/Component/Form/Extension/Core/EventListener/FixUrlProtocolListener.php]: What about checking instead if the the data starts with a slash?

Comment (ro0NL) [reply src/Symfony/Component/Form/Extension/Core/EventListener/FixUrlProtocolListener.php]: there's another issue actually :sweat_smile: #42329

im not sure for "protocol-relative URLs" we should apply `defaultProtocol` :confused:  however, i think it makes sense. esp. since protocol-relative URLs are an anti-pattern.

Comment (xabbuh) [reply src/Symfony/Component/Form/Extension/Core/EventListener/FixUrlProtocolListener.php]: I guess that issue would be fixed by this PR as well if I read the code correctly.

Comment (ro0NL) [reply src/Symfony/Component/Form/Extension/Core/EventListener/FixUrlProtocolListener.php]: correct. I was considering for `//domain` a default protocol should be applied, but it's a new feature also :)

**Review by nicolas-grekas — APPROVED** [review]
(I rebased and fixed the remaining)

File: src/Symfony/Component/Form/Tests/Extension/Core/EventListener/FixUrlProtocolListenerTest.php [hunk 4]
```diff
@@ -20,10 +20,25 @@
 
 class FixUrlProtocolListenerTest extends TestCase
 {
+    /**
+     * @dataProvider provideUrlToFix
+     */
+    public function testFixUrl($data)
```
Comment (stof) [inline src/Symfony/Component/Form/Tests/Extension/Core/EventListener/FixUrlProtocolListenerTest.php:26]: I suggest avoiding to swap the test and its provider, to avoid merge conflicts between branches

Comment (nicolas-grekas) [reply src/Symfony/Component/Form/Tests/Extension/Core/EventListener/FixUrlProtocolListenerTest.php:26]: I'm going to deal with the conflicts :)

**Comment by nicolas-grekas** [comment]
Thank you @bogkonstantin.
