### PR TITLE
[RemoteEvent][Webhook] fix SendgridPayloadConverter category support

### LINKED ISSUE #59374: [Webhook][RemoteEvent] SendgridPayloadConverter does not support string category
### Symfony version(s) affected

6.4.17

### Description

When sending an email using Sendgrid and the "category" field as a string, the webhook parser fails :

```
AbstractMailerEvent::setTags(): Argument #1 ($tags) must be of type array, string given, called in vendor/symfony/sendgrid-mailer/RemoteEvent/SendgridPayloadConverter.php on line 54
```

According to Sendgrid's documentation (https://www.twilio.com/docs/sendgrid/for-developers/tracking-events/event#json-objects) :
> category - Categories are custom tags that you set for the purpose of organizing your emails. If you send single categories as an array, they will be returned by the webhook as an array. If you send single categories as a string, they will be returned by the webhook as a string.

### How to reproduce

- Have a Symfony app with the sendgrid webhook installed
- Send an email with the sendgrid category as a string

=> the SendgridPayloadConverter should fails when calling `setTags` (which expects an array)

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ericabouaf**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59374 
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/Mailer/Bridge/Sendgrid/RemoteEvent/SendgridPayloadConverter.php [hunk 1]
```diff
@@ -51,7 +51,14 @@ public function convert(array $payload): AbstractMailerEvent
...
         $event->setMetadata([]);
-        $event->setTags($payload['category'] ?? []);
+
+        $tags = [];
+        // If you send single categories as an array, they will be returned by the webhook as an array.
+        // If you send single categories as a string, they will be returned by the webhook as a string.
+        if (isset($payload['category'])) {
+            $tags = \is_array($payload['category']) ? $payload['category'] : [$payload['category']];
+        }
+        $event->setTags($tags);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mailer/Bridge/Sendgrid/RemoteEvent/SendgridPayloadConverter.php]:
```suggestion
        $event->setTags((array) ($payload['category'] ?? []));
```

**Comment by nicolas-grekas** [comment]
(please rebase to resolve the conflict also)

**Comment by nicolas-grekas** [comment]
Thank you @ericabouaf.
