### PR TITLE
[VarDumper] Fix dumper selection for Accept: */* requests

### LINKED ISSUE #62787: [VarDumper] Wrong dumper detection for `Accept: */*` requests
### Symfony version(s) affected

>=7.4.0

### Description

Calling `dd()` or `dump()`  in a HTTP request with `Accept: */*` will not output `$vars`, even though `*/*` should accept any media type.

Instead of the `HtmlDumper` [VarDumper](https://github.com/symfony/var-dumper/blob/7.4/VarDumper.php#L83) incorrectly attributes the request to the `CliDumper`, therefore the dumped data is sent to the wrong output stream.

### How to reproduce

Just added a `dd()` call to `public/index.php`:

```php
<?php

use App\Kernel;

require_once dirname(__DIR__).'/vendor/autoload_runtime.php';

dd();

return function (array $context) {
    return new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);
};
```

### Possible Solution

The logic is getting too complex for a one-liner, it should be moved to a separate method.
The new method could look something like this:

```php
    private function getDumper(): DataDumperInterface
    {
        if (\array_key_exists('HTTP_ACCEPT', $_SERVER)) {
            if (str_contains($_SERVER['HTTP_ACCEPT'], 'html') || str_contains($_SERVER['HTTP_ACCEPT'], '*/*')) {
                return new HtmlDumper();
            }
        } elseif (!\in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
            return new HtmlDumper();
        } else {
            return new CliDumper();
        }
    }
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by apoca**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62787
| License       | MIT

## What does this fix?

Fixes incorrect dumper selection when `Accept: */*` header is present in HTTP requests, causing `dd()` and `dump()` output to disappear in browsers.

## The Problem

Since version 7.4.0 (PR #58070), when an HTTP request includes `Accept: */*` header, the dumper selection logic incorrectly chooses `CliDumper` instead of `HtmlDumper`. This causes dumps to be sent to STDOUT instead of being rendered in the browser response.

**Affected scenario:**
```php
// Browser makes request with Accept: */*
// dd(['test' => 123]) produces blank page instead of showing dump
```

Common with:
- AJAX requests without explicit Accept header
- API clients (Postman, Insomnia) 
- cURL without `-H "Accept: text/html"`
- PHP-FPM environments

## Root Cause

Current code only checks if Accept contains literal string `'html'`:
```php
str_contains($_SERVER['HTTP_ACCEPT'], 'html') ? new HtmlDumper() : new CliDumper()
```

According to [RFC 9110 Section 12.5.1](https://www.rfc-editor.org/rfc/rfc9110.html#section-12.5.1), `*/*` means "accept any media type", including `text/html`.

## Solution

Added explicit check for wildcard pattern:
```php
$accept = $_SERVER['HTTP_ACCEPT'] ?? (\in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'txt' : 'html');
$dumper = (str_contains($accept, 'html') || str_contains($accept, '*/*')) ? new HtmlDumper() : new CliDumper();
```

**Before:** `Accept: */*` → ❌ CliDumper (blank page)  
**After:** `Accept: */*` → ✅ HtmlDumper (dump visible)

## Backward Compatibility

✅ Fully backward compatible - only fixes broken behavior introduced in 7.4.0

**Test coverage:**
- `Accept: text/html` → HtmlDumper (unchanged)
- `Accept: */*` → HtmlDumper (fixed)
- `Accept: application/json` → CliDumper (unchanged)
- CLI SAPI → CliDumper (unchanged)

### CODE REVIEW

File: src/Symfony/Component/VarDumper/VarDumper.php [hunk 1]
```diff
@@ -76,11 +76,13 @@ private static function register(): void
             case 'server' === $format:
             case $format && 'tcp' === parse_url($format, \PHP_URL_SCHEME):
                 $host = 'server' === $format ? $_SERVER['VAR_DUMPER_SERVER'] ?? '127.0.0.1:9912' : $format;
-                $dumper = str_contains($_SERVER['HTTP_ACCEPT'] ?? (\in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'txt' : 'html'), 'html') ? new HtmlDumper() : new CliDumper();
+                $accept = $_SERVER['HTTP_ACCEPT'] ?? (\in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'txt' : 'html');
+                $dumper = (str_contains($accept, 'html') || str_contains($accept, '*/*')) ? new HtmlDumper() : new CliDumper();
```
Comment (nicolas-grekas) [inline src/Symfony/Component/VarDumper/VarDumper.php]:
```suggestion
                $dumper = str_contains($accept, 'html') || str_contains($accept, '*/*') ? new HtmlDumper() : new CliDumper();
```

File: src/Symfony/Component/VarDumper/VarDumper.php [hunk 2]
```diff
@@ -76,11 +76,13 @@ private static function register(): void
...
                 $dumper = new ServerDumper($host, $dumper, self::getDefaultContextProviders());
                 break;
             default:
-                $dumper = str_contains($_SERVER['HTTP_ACCEPT'] ?? (\in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'txt' : 'html'), 'html') ? new HtmlDumper() : new CliDumper();
+                $accept = $_SERVER['HTTP_ACCEPT'] ?? (\in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'txt' : 'html');
+                $dumper = (str_contains($accept, 'html') || str_contains($accept, '*/*')) ? new HtmlDumper() : new CliDumper();
```
Comment (nicolas-grekas) [inline src/Symfony/Component/VarDumper/VarDumper.php]:
```suggestion
                $dumper = str_contains($accept, 'html') || str_contains($accept, '*/*') ? new HtmlDumper() : new CliDumper();
```

**Review by nicolas-grekas — COMMENTED** [review]
works for me, can you add a test case please?

File: src/Symfony/Component/VarDumper/Tests/VarDumperTest.php [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+namespace Symfony\Component\VarDumper\Tests;
+
+use PHPUnit\Framework\TestCase;
+use Symfony\Component\VarDumper\Cloner\VarCloner;
+use Symfony\Component\VarDumper\Dumper\CliDumper;
+use Symfony\Component\VarDumper\Dumper\ContextualizedDumper;
+use Symfony\Component\VarDumper\Dumper\HtmlDumper;
+use Symfony\Component\VarDumper\VarDumper;
+
+class VarDumperTest extends TestCase
```
Comment (nicolas-grekas) [inline src/Symfony/Component/VarDumper/Tests/VarDumperTest.php]: ah sorry I should have told you: this is tested using phpt, see src/Symfony/Component/VarDumper/Tests/Dumper/functions/dump_with_accept_header_html.phpt

Comment (apoca) [reply src/Symfony/Component/VarDumper/Tests/VarDumperTest.php]: Well this `phpt` was new for me :)

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @apoca.
