### PR TITLE
[HttpFoundation] Prevent accepted rate limits with no remaining token to be preferred over denied ones

### LINKED ISSUE #47282: [Security] login_throttling un-blocking for *one* attempt at "5 * max_attempts"
### Symfony version(s) affected

6.1.3

### Description

I have this in my `security.php`:
```php
$security->provider('foo_provider')->entity()->class(Foo::class)->property('token');
$mainFirewall->loginThrottling()->maxAttempts(1)->interval('1 hour');
```
`Foo::$token` is a self-created random string for magic link login.

This happens when requesting the **same** inexistent token URL (after `cache:clear`):
1. attempt => "Invalid link"
2. attempt => "You're blocked" // As expected with `->maxAttempts(1)`
3. attempt => "You're blocked"
4. attempt => "You're blocked"
5. attempt => "Invalid link" // **Why??**
6. through 20. attempt => "You're blocked"

So to me this looks like either a bug, or the documentation at https://symfony.com/doc/5.4/security.html#limiting-login-attempts is missing something:
> Login attempts are limited on `max_attempts` (default: 5) failed requests for IP address + username and 5 * max_attempts failed requests for IP address.

When changing `max_attempts` to 2, the unexptected "Invalid link" happens at the 10th attempt, so it's probably related to the "5 * max_attempts" rule.

### How to reproduce

If you're telling me that this is the expected behavior, then let's try to improve the docs. If you say that this is unexpected, I can try to investigate it further or create a reproducer.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #47282
| License       | MIT
| Doc PR        | N/A

When a rate limit is first accepted with no remaining token, following rejected rate limits will be ignored because they also will have no remaining token. The request would then be processed.

### CODE REVIEW

File: src/Symfony/Component/HttpFoundation/RateLimiter/AbstractRequestRateLimiter.php [hunk 1]
```diff
@@ -35,7 +35,7 @@ public function consume(Request $request): RateLimit
         foreach ($limiters as $limiter) {
             $rateLimit = $limiter->consume(1);
 
-            if (null === $minimalRateLimit || $rateLimit->getRemainingTokens() < $minimalRateLimit->getRemainingTokens()) {
+            if (null === $minimalRateLimit || $rateLimit->getRemainingTokens() < $minimalRateLimit->getRemainingTokens() || !$rateLimit->isAccepted()) {
```
Comment (wouterj) [inline src/Symfony/Component/HttpFoundation/RateLimiter/AbstractRequestRateLimiter.php]: I think we can take this one step further and always return the most "minimal" rate limit. I.e. in case both `$rateLimit` and `$minimalRateLimit` do not accept, return the one with the longest wait time.

**Review by wouterj — CHANGES_REQUESTED** [review]
Thanks for the blazing fast bug fix, @MatTheCat!

Can you please add a test case for this fix, so we can be sure not to break it in the future?

**Comment by MatTheCat** [comment]
@wouterj thanks! What should I do to make my test pass? Seems my changes are missing from them :thinking:

**Comment by wouterj** [comment]
See https://symfony.com/doc/current/contributing/code/pull_requests.html#automated-tests for more information about our test suite.

The failing checks are checking each individual package, rather than the monorepo. So it'll download rate limiter in the current  available version, rather than the version of your PR.

Ideally, we would have a test for this abstract class' behavior in the HttpFoundation component itself. If you have some time, it would be great to create a `MockRequestRateLimiter` and add this specific test case there (based on the test that you've added).

**Comment by MatTheCat** [comment]
Okay, remaining failures seem unrelated :ok_hand:

**Review by wouterj — APPROVED** [review]
Looking good!

**Comment by fabpot** [comment]
Thank you @MatTheCat.
