### PR TITLE
[Serializer] Improve displaying of non-normalizable value type during denormalization

### LINKED ISSUE #63318: [Serializer][Normalizer] NotNormalizableValueException::getCurrentType() returns `array` instead of actual value type when PropertyAccessor throws InvalidTypeException
### Symfony version(s) affected

5.4 (not sure) - 8.1

### Description

When `AbstractObjectNormalizer` catches a `PropertyAccessInvalidArgumentException` during denormalization and creates a `NotNormalizableValueException`, it incorrectly passes the entire input data array (`$data`) instead of the specific attribute value (`$value`).

https://github.com/symfony/serializer/blob/561cf251ce269f0e6aa681841ad99ca0c711a33b/Normalizer/AbstractObjectNormalizer.php#L401-L406

This causes `NotNormalizableValueException::getCurrentType()` to return `array` instead of the actual type of the problematic value (e.g., `int`, `string`, `stdClass`).

Impact:
- API error messages show incorrect type information
- Difficult debugging for developers  
- Poor user experience when validation errors are displayed to clients

### How to reproduce

I didn't just create an additional test in the https://github.com/symfony/serializer project, because several packages are needed to demonstrate the issue:
- `symfony/serializer`
- `symfony/property-access`
- `symfony/property-info`

I created a small reproducer repository: https://github.com/VBelozyorov/serializer-bug-reproducer,
It contains a single test with 22 data samples to demonstrate the issue described above. 4 of those 22 samples look fine, 18 are failing.

You just need to run the following commands to execute that test:
```
composer install
composer test
```

### Possible Solution

I suggest either:
```
--- vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php
+++ vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php
@@ -403,7 +403,7 @@
             } catch (PropertyAccessInvalidArgumentException $e) {
                 $exception = NotNormalizableValueException::createForUnexpectedDataType(
                     \sprintf('Failed to denormalize attribute "%s" value for class "%s": '.$e->getMessage(), $attribute, $resolvedClass),
-                    $data,
+                    $data[$attribute],
                     $e instanceof InvalidTypeException ? [$e->expectedType] : ['unknown'],
                     $attributeContext['deserialization_path'] ?? null,
                     false,
```

or:
```
--- vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php
+++ vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php
@@ -403,7 +403,7 @@
             } catch (PropertyAccessInvalidArgumentException $e) {
                 $exception = NotNormalizableValueException::createForUnexpectedDataType(
                     \sprintf('Failed to denormalize attribute "%s" value for class "%s": '.$e->getMessage(), $attribute, $resolvedClass),
-                    $data,
+                    $data[$attribute] ?? $value,
                     $e instanceof InvalidTypeException ? [$e->expectedType] : ['unknown'],
                     $attributeContext['deserialization_path'] ?? null,
                     false,
```

### Additional Context

See also the suggested fix in #63320.

### PR DESCRIPTION
**Pull request by VBelozyorov**
| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63318
| License       | MIT

When `AbstractObjectNormalizer `catches a `PropertyAccessInvalidArgumentException` during denormalization and creates a `NotNormalizableValueException`, it incorrectly passes the entire input data array (`$data`) instead of the specific attribute value (`$value`).

This PR fixes that.

### CODE REVIEW

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 1]
```diff
@@ -416,7 +416,7 @@ public function denormalize(mixed $data, string $type, ?string $format = null, a
             } catch (PropertyAccessInvalidArgumentException $e) {
                 $exception = NotNormalizableValueException::createForUnexpectedDataType(
                     \sprintf('Failed to denormalize attribute "%s" value for class "%s": '.$e->getMessage(), $attribute, $type),
-                    $data,
+                    $data[$attribute] ?? $value,
```
Comment (VBelozyorov) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: I'm not 100% sure about using `$data[$attribute] ?? $value` vs. `$value` or `$data[$attribute]`.

I plan to check more versions and, probably, add some more tests.

### Why not `$value`?

In my project where I first encountered this issue, I have 
```
"symfony/serializer": "7.4.5",
"symfony/property-access": "7.4.4",
"symfony/property-info": "7.4.5"
```

And it looks like the behavior is slightly different from what I tested while creating this PR.

In my project I got `null` in the `$value` after `filter_var()` for integer and string values for a `boolean` field, so `NotNormalizableValueException#getCurrentType()` would still return incorrect type.

Comment (VBelozyorov) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: I just added this commit: https://github.com/VBelozyorov/serializer-bug-reproducer/commit/ac1d8eb076a2e3f3c87435143689c157f67fabb5 to my reproducer repository to demonstrate cases where passing just `$value` isn't sufficient.

Please tell me if it is acceptable to create here in tests the Serializer object like that: https://github.com/VBelozyorov/serializer-bug-reproducer/commit/ac1d8eb076a2e3f3c87435143689c157f67fabb5#diff-6ce3dc7998c8f1ab250d1bffa0cc0004f4e8637f5b3779c9d646145f87591f75R24-R49 (`createSerializerHeavy()` function)?

**Comment by nicolas-grekas** [comment]
I'm seeing many other calls to `NotNormalizableValueException::createForUnexpectedDataType()` which works the same as the patched line.
This makes wonder if the concern would apply there also.

Note that this wouldn't be a bugfix but an improvement, thus for branch 8.1

**Comment by VBelozyorov** [comment]
> I'm seeing many other calls to `NotNormalizableValueException::createForUnexpectedDataType()` which works the same as the patched line. This makes wonder if the concern would apply there also.

For example, these three calls of `NotNormalizableValueException::createForUnexpectedDataType()`: 
https://github.com/symfony/symfony/blob/5063fee4265f5be0830d865526af0268b17fe144/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L508-L529

are inside `validateAndDenormalize()`, and `$data` there is the `$value` inside `denormalize()`:
https://github.com/symfony/symfony/blob/5063fee4265f5be0830d865526af0268b17fe144/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L402

**Comment by VBelozyorov** [comment]
> Note that this wouldn't be a bugfix but an improvement, thus for branch 8.1

Could you please elaborate a bit why this isn't a bugfix? Do you see any BC breaks?
I'm not trying to argue, just want to understand for myself 🙂

**Comment by nicolas-grekas** [comment]
> why this isn't a bugfix?

because it improves something, as noted in the PR title - making the error message better ;)

**Comment by VBelozyorov** [comment]
> > why this isn't a bugfix?
> 
> because it improves something, as noted in the PR title - making the error message better ;)

Perhaps it's my inaccuracy in the commit message and the PR title.

As you can see, before this change, the exception was already about a particular attribute, but its `getCurrentType()` method simply returned the wrong type — not the attribute’s type, but the type of the attribute’s parent structure.

```php
$exception = NotNormalizableValueException::createForUnexpectedDataType(
    \sprintf(
        'Failed to denormalize attribute "%s" value for class "%s": '.$e->getMessage(), 
        $attribute, // <-- attribute's name
        $type
    ),
    $data,
    ['unknown'],
    $attributeContext['deserialization_path'] ?? null, // <-- attribute's path
    false,
    $e->getCode(),
    $e
);
```

**Review by nicolas-grekas — APPROVED** [review]
I reworked this to keep the change minimal and focused on semantics.

This confirms the issue is an improvement, not a behavioral bugfix to me: denormalization behavior is unchanged, only the diagnostic payload used by `NotNormalizableValueException::getCurrentType()` is made more accurate (it wasn't really wrong either before).

Using `$value` is more precise than `$data[$attribute] ?? $value`, because this exception is raised when assigning the final denormalized value to the property. So the reported current type should match the value that actually reaches assignment (including callbacks), not the raw input structure.

I also reduced the tests to 2 focused cases:
- one baseline case confirming we report the attribute value type (not the parent data structure),
- one callback case proving the reported type matches the post-callback value used at assignment time.

**Comment by nicolas-grekas** [comment]
Thank you @VBelozyorov.

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php [hunk 2]
```diff
@@ -1439,6 +1440,41 @@ protected function isAllowedAttribute($classOrObject, string $attribute, ?string
...
+
+    public function testNotNormalizableValueExceptionCurrentTypeUsesAttributeValue()
+    {
+        $serializer = new Serializer([new ObjectNormalizer(propertyAccessor: PropertyAccess::createPropertyAccessor())]);
+
+        $this->expectException(NotNormalizableValueException::class);
+        $this->expectExceptionMessage('bool');
+
+        try {
+            $serializer->denormalize(['field' => ['value']], DummyBoolField::class);
```
Comment (VBelozyorov) [inline src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php:1452]: Because of both `['field' => ['value']]` and `['value']` are arrays this test would pass even without the change in the PR 🙂

Comment (VBelozyorov) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php:1452]: But I think this thread can be resolved

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php:1452]: arf, follow up PR always welcome if you're up to :)
