### PR TITLE
[Yaml] Allow tabs as separators between tokens

### LINKED ISSUE #40507: symfony/yaml does not parse tabs after colon
**Symfony version(s) affected**: 4.4.19

**Description**
`symfony/yaml` throws a `Symfony\Component\Yaml\Exception\ParseException` if it encounters a tab instead of space(s) after a colon, while tabs are valid as separation between tokens within a line according to the yaml spec: https://yaml.org/spec/1.2/spec.html#id2778241

> Outside indentation and scalar content, YAML uses white space characters for separation between tokens within a line. **Note that such white space may safely include tab characters.**

(Emphasis mine)

**How to reproduce**
Use `symfony/yaml` to parse a yaml file with a tab after the colon of a key/value pair on a line.

For example:
```
'00D24000000JRFx:0012400000R6XYH':	95290dcc-8d1d-4b9f-952e-496562f53e35
```

**Possible Solution**
Allow tabs for separation between tokens within a line, as described in the yaml spec.
If I find some time I might look into a possible fix and make a PR myself unless someone else beats me to it.

**Additional context**
It has been mentioned in other issues like #15674 that tabs are not allowed in yaml files. But this is only the case for indentation.

While I'm not a huge fan of it personally, it's an issue when a different linter tells us that a given YAML file with content that we have little control over has valid syntax in an unrelated check, and then our app crashes because it cannot be parsed after all.

### PR DESCRIPTION
**Pull request by bertramakers**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40507
| License       | MIT
| Doc PR        | None

As described in #40507, the Yaml spec allows tabs as whitespace characters between tokens. However, the Yaml parser crashes on this as it only expects spaces after the colon. https://yaml.org/spec/1.2/spec.html#id2778241

While I'm not a huge fan of it personally, it's an issue when a different linter tells us that a given YAML file with content that we have little control over has valid syntax in an unrelated check, and then our app crashes because it cannot be parsed after all.

### CODE REVIEW

**Comment by bertramakers** [comment]
~Not sure how I can fix the coding standard suggestions reported on fabbot.io, since it changes the tab characters that are needed to actually test this.~
Edit: I misread and it suggested to use single quotes instead of double quotes, so I did that in https://github.com/symfony/symfony/pull/40514/commits/5f35e8902a444b4d8e64cbb1d46a26c6fcae5832.

The exception message formatting suggested on fabbot.io is unrelated to my changes. Not sure if I should fix that then.
Edit: I don't think the suggested exception message formatting changes make sense in this context. For example, the exception message `Numeric keys are not supported. [...]` would become `"Numeric" keys are not supported. [...]`

**Comment by bertramakers** [comment]
The tests failing on Appveyor also seem unrelated to me, so again I'm not sure how to make those green.

**Comment by stof** [comment]
> The exception message formatting suggested on fabbot.io is unrelated to my changes. Not sure if I should fix that then.
> Edit: I don't think the suggested exception message formatting changes make sense in this context. For example, the exception message `Numeric keys are not supported. [...]` would become `"Numeric" keys are not supported. [...]`

The check about the formatting of exception message has some false positive (where we explicitly decide not to wrap in quotes as we are using placeholders for a different reason).

File: src/Symfony/Component/Yaml/Tests/ParserTest.php [hunk 1]
```diff
@@ -66,14 +66,28 @@ public function testTabsInYaml()
...
             }
         }
     }
 
+    public function testTabsAsSeparationBetweenTokensInYaml()
+    {
+        // test tabs as separation between tokens
+        $yamls = [
+            'foo:	bar', // tab after colon
+            'foo: 	bar', // space and tab after colon
```
Comment (stof) [inline src/Symfony/Component/Yaml/Tests/ParserTest.php]: I suggest writing those using a double-quoted string and a `\t` escape sequence to put the tab character. It will make the code a lot more readable (and the comments describing the strings won't bee needed anymore).

File: src/Symfony/Component/Yaml/Tests/ParserTest.php [hunk 2]
```diff
@@ -66,14 +66,28 @@ public function testTabsInYaml()
...
+        ];
+
+        foreach ($yamls as $yaml) {
```
Comment (stof) [inline src/Symfony/Component/Yaml/Tests/ParserTest.php]: this would be better implemented as 2 separate tests IMO

Comment (bertramakers) [reply src/Symfony/Component/Yaml/Tests/ParserTest.php]: I'm open to splitting it up, but I based it on the existing test for tabs as indentation. Should I also change that one then for consistency?

And would a dataprovider also be okay, or do you prefer separate tests?

File: src/Symfony/Component/Yaml/Tests/ParserTest.php (hunk 1 above)
Comment (bertramakers) [reply src/Symfony/Component/Yaml/Tests/ParserTest.php]: Thanks for the tip, I changed it in https://github.com/symfony/symfony/pull/40514/commits/463a1c9948e978c1be7fa73c652924b291943660

File: src/Symfony/Component/Yaml/Tests/ParserTest.php (hunk 2 above)
Comment (xabbuh) [reply src/Symfony/Component/Yaml/Tests/ParserTest.php]: a data provider is fine

Comment (stof) [reply src/Symfony/Component/Yaml/Tests/ParserTest.php]: tests of the YAML component are quite old (that component actually comes from symfony 1 originally), and so they don't really follow PHPUnit best practices. But ideally, new tests should follow them

Comment (bertramakers) [reply src/Symfony/Component/Yaml/Tests/ParserTest.php]: Alright, thanks for clarifying! I haven't had much time to change it so far but I still intend to follow up on this somewhere in the coming days.

Comment (bertramakers) [reply src/Symfony/Component/Yaml/Tests/ParserTest.php]: Out of curiosity, why should tests not have a `: void` return type?

**Review by xabbuh — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you @bertramakers.

File: src/Symfony/Component/Yaml/Parser.php [hunk 3]
```diff
@@ -200,7 +200,7 @@ private function doParse(string $value, int $flags)
                     array_pop($this->refsBeingParsed);
                 }
             } elseif (
-                self::preg_match('#^(?P<key>(?:![^\s]++\s++)?(?:'.Inline::REGEX_QUOTED_STRING.'|(?:!?!php/const:)?[^ \'"\[\{!].*?)) *\:( ++(?P<value>.+))?$#u', rtrim($this->currentLine), $values)
+                self::preg_match('#^(?P<key>(?:![^\s]++\s++)?(?:'.Inline::REGEX_QUOTED_STRING.'|(?:!?!php/const:)?[^ \'"\[\{!].*?)) *\:(( |\t)++(?P<value>.+))?$#u', rtrim($this->currentLine), $values)
```
Comment (rentalhost) [inline src/Symfony/Component/Yaml/Parser.php:203]: Why group (`( |\t)`) insteand of list (`[ \t]`)? Lists are a bit faster.

Comment (bertramakers) [reply src/Symfony/Component/Yaml/Parser.php:203]: No specific reason except that I didn't know that there was a performance difference. Is it significant though?
I have no strong opinion about one or the other, but this PR is merged so it'd require a new PR.

Comment (rentalhost) [reply src/Symfony/Component/Yaml/Parser.php:203]: @bertramakers I did a benchmark, and list is 1% faster. I do not know if it is considered a micro-optimization, but since it's a parser, maybe it's something significant.

Comment (bertramakers) [reply src/Symfony/Component/Yaml/Parser.php:203]: I have no idea either, I just discovered this bug while using the Yaml component in my own app and reported and fixed it to the best of my ability 😄 I think you can always open another PR to optimize it if you think it's worth it!

Comment (rentalhost) [reply src/Symfony/Component/Yaml/Parser.php:203]: @bertramakers yeah, no problem! The fix works.
