### PR TITLE
[Worflow] Fixed GuardListener when using the new Security system

### LINKED ISSUE #39505: [Workflow] There are no tokens available for workflow "%s" (new security system)
**Symfony version(s) affected**: 5.2.0

**Description**  
After migration to the new security system, it looks that it's not possible anymore to apply transition as an anonymous because no token is available (previously we had the AnonymousToken).

**How to reproduce**  

- Use the new security system.

- Had a workflow like:

```
framework:
    workflows:
        user_account:
            type: 'workflow'
            supports:
                - Lugosium\Bundle\InpulsarBundle\Entity\UserAccount
            initial_marking: pending_activation
            places:
                pending_activation: ~
                enabled: ~
            transitions:
                pending_activation_to_enabled:
                    from: pending_activation
                    to: enabled
```

Apply transition `pending_activation_to_enabled` as anonymous.

**Possible Solution**  
Support null token in:

https://github.com/symfony/workflow/blob/5.x/EventListener/GuardListener.php#L80

**Additional context**  
User registers and his account is marked as pending_activation. 
When he clicks email link to activate account, i used to apply transition pending_activation_to_enabled and then redirect user to the login page.

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 5.2 
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39505
| License       | MIT
| Doc PR        |

### CODE REVIEW

File: src/Symfony/Component/Workflow/EventListener/GuardListener.php [hunk 1]
```diff
@@ -77,7 +80,13 @@ private function getVariables(GuardEvent $event): array
         $token = $this->tokenStorage->getToken();
 
         if (null === $token) {
-            throw new InvalidTokenConfigurationException(sprintf('There are no tokens available for workflow "%s".', $event->getWorkflowName()));
+            if (!$this->useAuthenticatorManager) {
+                throw new InvalidTokenConfigurationException(sprintf('There are no tokens available for workflow "%s".', $event->getWorkflowName()));
+            }
+            if (!class_exists(NullToken::class)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Workflow/EventListener/GuardListener.php]: Instead of the check, can't we rely on the fact that useAuthenticatorManager is set to true only when the NullToken class exists? WHat about doing this check in the DI extension? I'm not comfortable with telling about a DI parameter in a standalone component...

**Comment by lyrixx** [comment]
I choose a totally different approach, like suggested by Wouter [there](https://github.com/symfony/symfony/issues/39505#issuecomment-753328926)

**Comment by fabpot** [comment]
@wouterj Can you review this one please?

**Comment by wouterj** [comment]
I'm not so sure about the 5.2 target for this PR:

* It's changing behavior, so it does need a CHANGELOG entry
* It's remove an (exception) class, I don't think we are allowed to do so in any 5.x release?

We may be able to work around (1) by only doing this in the new system. Maybe we should set a parameter (e.g. `security.exception_on_no_token`) that is true when the new system is used and false otherwise. We [already have some services depending on this knowledge](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L118-L123), by using a parameter we can also depend on it in the `GuardListener`.

**Comment by lyrixx** [comment]
I'm not sure we must do something more about the BC. We open a door here, we don't close one.
Previously, a user MUST put a token in the token storage to make it work.
So we can be 100% sure a token is present.
So removing this check is dead code for current code. We only allow new security system to work

But maybe, I should let the removed exception, and deprecate it...

**Comment by chalasr** [comment]
> We open a door here, we don't close one.

Looking at the code, I agree here. This stops throwing an undocumented exception, which is fine for me as a bugfix.

> But maybe, I should let the removed exception, and deprecate it...

I think so :) it's a hard break, we can do it smoothly on 5.x.

**Comment by wouterj** [comment]
What I was meaning is that expressions now need to handle `token` and `user` being `null`, whereas it always was `TokenInterface` and `UserInterface` before the changes in this PR, right? <s>I haven't used Workflow at all, so I can't judge whether this is a blocker.</s> On a second thought, as it only happens when using the experimental system (and it doesn't work at all for the new system), it's probably OK for a patch release.

**Comment by lyrixx** [comment]
yes and yes :) an anyway, without talking about the new security system, I think the patch is valid anyway.
When we look at [why](https://github.com/symfony/symfony/pull/23906) this exception has been added, when understand that this exception is not really required, and the new code seems more natural

**Comment by chalasr** [comment]
no approval, not good! :) See #40201

**Comment by lyrixx** [comment]
@chalasr I know there are no approval, but the more than one month, without a clear direction of what I must do. So I do what I think is the best and I merged it 11 days later :) 

Anyway, thanks for taking care of the BC
