### PR TITLE
[Console] Preserve `--help` option when a command is not found

### LINKED ISSUE #62618: [Console] `--help` is not preserved when a command is not found, and a proposition is made
### Symfony version(s) affected

all, I guess

### Description

```console
$ php index.php  command --help

                                     
  Command "command" is not defined.  
                                     

 Do you want to run "my:command" instead?  (yes/no) [no]:
 > yes

Hello, World!
```

* Here, I passed the `--help` flag on a command that does not exist.
* Symfony find the real command, and made a proposition.
* I type `yes`, to the proposition
* Symfony runs the command, but without the `--help` flag

I think the --help should be preserved 

### How to reproduce

```php
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;

require __DIR__ . '/vendor/autoload.php';

$app = new Application('My Console App', '1.0.0');
$command = new Command();
$command->setName('my:command')
    ->setDescription('This is my custom command.')
    ->setCode(function () {
        echo "Hello, World!\n";

        return 1;
    });

$app->addCommand($command);

$app->run();
```

Then, execute:

```
php index.php  command --help
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by santysisi**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62618 
| License       | MIT

This PR resolves 3 issues:

1. The first one is the commented in the issue. The `--help` is not preserved when a command is not found
2. The second issue this pull request resolves is that hidden commands are currently being displayed if the `--help` option is present and the original command is not found.
3. The final issue this pull request resolves is that the "Did you mean?" prompt is not displayed if no alternative command is present.

### CODE REVIEW

**Comment by Maxcastel** [comment]
In a shorter way:

```diff
if ($this->wantHelps) {
    $this->wantHelps = false;

    $helpCommand = $this->get('help');
    $helpCommand->setCommand($command);

+    $this->wantHelps = true;

    return $helpCommand;
}
```

**Comment by Maxcastel** [comment]
You added tests, but even without changing `Application.php`, the tests pass, and I think they shouldn’t pass.

**Comment by santysisi** [comment]
Hi @Maxcastel, thank you so much for your feedback :smile:

> You added tests, but even without changing `Application.php`, the tests pass, and I think they shouldn’t pass.

You're right, the `testDoesNotFindHiddenCommandAsAlternativeIfHelpOptionIsPresent` test pass correctly without the new changes (my fault). The other tests didn't work correctly without the changes in my local. Could you give me an example of the problem, please, so I can try to fix it? :smile:


> In a shorter way:

I'm not sure about that change :thinking:

**Comment by santysisi** [comment]
> the `testDoesNotFindHiddenCommandAsAlternativeIfHelpOptionIsPresent` test pass correctly without the new changes (my fault)

I modified the test `testDoesNotFindHiddenCommandAsAlternativeIfHelpOptionIsPresent` for tests correctly the new behavior

Thanks again for your feedback :)

**Comment by Maxcastel** [comment]
I didn’t run the right tests :sweat_smile: Sorry @santysisi for the inconvenience.

File: src/Symfony/Component/Console/Application.php [hunk 1]
```diff
@@ -732,15 +732,20 @@ public function find(string $name)
...
-                    $message .= "\n\nDid you mean this?\n    ";
-                } else {
-                    $message .= "\n\nDid you mean one of these?\n    ";
+                if ($alternatives) {
+                    if (1 == \count($alternatives)) {
+                        $message .= "\n\nDid you mean this?\n    ";
+                    } else {
+                        $message .= "\n\nDid you mean one of these?\n    ";
+                    }
+                    $message .= implode("\n    ", $alternatives);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Application.php]: while at it:
```suggestion
                if ($alternatives) {
                    $message .= \sprintf("\n\nDid you mean %s?\n    %s", 1 === \count($alternatives) ? 'this' : 'one of these', implode("\n    ", $alternatives));
```

**Comment by nicolas-grekas** [comment]
Thank you @santysisi.
