### PR TITLE
[VarDumper] Use documentElement instead of body for JS flag

### LINKED ISSUE #50487: using var-dumper as standalone, expand or collapse not working
### Symfony version(s) affected

n/a

### Description

after upgrading var-dumper to 6.3, when using `dump()` or `dd()`, expand or collapse for object/array/string suddenly not working.

image

https://github.com/symfony/symfony/assets/6737021/240856c0-3a7e-40c5-89c3-505115154cea

### How to reproduce

- `composer init` then install `symfony/var-dumper` v6.3
- open `index.php` in browser
- expand or collapse not working

[composer.json.txt](https://github.com/symfony/symfony/files/11607410/composer.json.txt)
[index.php.txt](https://github.com/symfony/symfony/files/11607411/index.php.txt)

### Possible Solution

_No response_

### Additional Context

- browser: Chrome
- platform: Windows
- user agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`

### PR DESCRIPTION
**Pull request by ohader**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #50487
| License       | MIT
| Doc PR        | ---

Fixes: #50487

Using `document.documentElement` allows to use the dumper outside of a `<html><body>...</body></html>` scenario.

### CODE REVIEW

File: src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php [hunk 1]
```diff
@@ -163,8 +163,8 @@ protected function getDumpHeader()
 <script>
 Sfdump = window.Sfdump || (function (doc) {
 
-if (doc.body instanceof HTMLElement) {
-    doc.body.classList.add('sf-js-enabled');
+if (doc.documentElement) {
```
Comment (MatTheCat) [inline src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php]: Can this value ever be falsy?

Comment (ohader) [reply src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php]: Browsers usually "fix" it, however I don't know about all browser tweaks - that's why I added the check here.

Comment (ohader) [reply src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php]: https://developer.mozilla.org/en-US/docs/Web/API/Document/documentElement?retiredLocale=de#notes

> For any non-empty HTML document, documentElement will always be an [<html>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html) element. For any non-empty XML document, documentElement will always be whatever element is the root element of the document.

Comment (ohader) [reply src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php]: ... and I forgot to mention Selenium, WebDriver & Co

Comment (MatTheCat) [reply src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php]: What does it have to do with Selenium?

Anyways if documentElement is falsy I don't think the following script will serve any purpose since the dump won't appear to work. Maybe it would then easier to debug if an error is logged in the console 🤔

(Also the code would crash if documentElement is truthy but not an HTMLElement.)

Comment (ohader) [reply src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php]: I've remove the check. @MatTheCat are you happy with this?

Comment (MatTheCat) [reply src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php]: LGTM, thanks 👍

**Review by MatTheCat — APPROVED** [review]

File: src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php (hunk 1 above)
Comment (ohader) [reply src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php]: Merci! 👍

**Comment by nicolas-grekas** [comment]
Thank you @ohader.
