### PR TITLE
[FrameworkBundle] Fix setting default context for certain normalizers

### LINKED ISSUE #56875: [Serializer] Serializing empty class without properties serializes to `[]` when `preserve_empty_objects` is enabled
### Symfony version(s) affected

7.1-RC1

### Description

While testing 7.1-RC1 I noticed a change in behavior.

I have a test suite that serializes all commands (for a command bus) and confirms that they can be deserialized.

There is a command that does not have any properties:
```php
final class DoSomethingCommand {}
```

When this is serialized with Symfony 7.0, it produces `{}`.

But with Symfony 7.1-RC1 it becomes `[]`.

### How to reproduce

See above.

### Possible Solution

While debugging the situation, I notice that in 7.0 the empty object gets normalized into ArrayObject (empty). 
Screenshot 2024-05-22 at 09 29 47@2x

But on 7.1-RC1 it becomes an empty array.
Screenshot 2024-05-22 at 09 31 35@2x

### Additional Context

_No response_

### LINKED ISSUE #57316: ObjectNormalizer is not provided with serializer default_context
### Symfony version(s) affected

6.4.8

### Description

When ```default_context``` is set in framework.yaml globally - Symfony\Component\Serializer\Normalizer\ObjectNormalizer is missing them in specific circumstances. I have declared this in ```framework.yaml``` 

image

```Symfony\Component\Serializer\DependencyInjection\SerializerPass.php``` does the binding 

https://github.com/symfony/symfony/blob/cf4ef922301b0906f94efa0a2ab0249885d8fc5c/src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php#L55

But after ```bin/console c:c``` ObjectNormalizer has an empty array passed to $defaultContext

`new \Symfony\Component\Serializer\Normalizer\ObjectNormalizer($c, $d, $b, $e, new \Symfony\Component\Serializer\Mapping\ClassDiscriminatorFromClassMetadata($c), NULL, [], $e)`

That's what is passed after cache clearing in ```App_KernelDevDebugContainer.php```.

If I manually enable autowiring in ```services.yaml``` like this:

image

binding works and defaultContext is passed there. But looks like generally the issue is that bindings conflict with arguments setting somewhere during building process. Because, for example, ProblemNormalizer has $defaultContext passed correctly and it is not autowired by default as well.

My expectation is to have defaultContext passed there by default if it is configured globally for ObjectNormalizer

### How to reproduce

1. Setup clean symfony 6.4.8. ```symfony new 64lts --version="6.4.8"```
2. Install via composer serializer and property-access. ```composer require symfony/serializer```, ```composer require symfony/property-access```
3. Set ```dev``` environment and ```APP_DEBUG=true```
4. Add this to ```framework.yaml```
    ```
     serializer:
        default_context:
            disable_type_enforcement: true
            skip_null_values: true
4. ```bin/console c:c```

Check ObjectNormalizer declaration in container. $defaultContext is empty.

### Possible Solution

I see several options to solve this.

1. https://github.com/symfony/symfony/blob/cf4ef922301b0906f94efa0a2ab0249885d8fc5c/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L2004

Looks like on this line we already have $defaultContext variable containing empty array or globally set default_context if configured. And it is a bit weird that $defaultContext variable will be considered only if `circular_reference_handler` or `max_depth_handler` exist.

![image](https://github.com/symfony/symfony/assets/28899131/0b9027af-102d-429e-a206-d6dfbd436404)

And in case if these two options are missing - empty $context variable is set to ObjectNormalizer 6th argument. if we set $defaultContext here instead of declaring empty $context - it will work. 

```
        $defaultContext = $config['default_context'] ?? [];

        if ($defaultContext) {
            $container->setParameter('serializer.default_context', $defaultContext);
        }

        $arguments = $container->getDefinition('serializer.normalizer.object')->getArguments();

        if (isset($config['circular_reference_handler']) && $config['circular_reference_handler']) {
            $defaultContext += ($arguments[6] ?? $defaultContext) + ['circular_reference_handler' => new Reference($config['circular_reference_handler'])];
            $container->getDefinition('serializer.normalizer.object')->setArgument(5, null);
        }

        if ($config['max_depth_handler'] ?? false) {
            $defaultContext += ($arguments[6] ?? $defaultContext) + ['max_depth_handler' => new Reference($config['max_depth_handler'])];
        }

        $container->getDefinition('serializer.normalizer.object')->setArgument(6, $defaultContext);
```
2. Make ObjectNormalizer autowired by default

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #56875, fix #57316
| License       | MIT

Caused by #54791. The main problem is that `$context` defaults to `[]` instead of `$defaultContext`. There's a test to check this, but it didn't work when `circular_reference_handler` or `max_depth_handler` were not `null`.

I also found an issue with `serializer.normalizer.property`. Since it’s not tagged with `serializer.normalizer`, which, to my understanding, is intentional, it would never have the default context bound to it.

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/Tests/Functional/SerializerTest.php [hunk 1]
```diff
@@ -52,20 +53,29 @@ public function testNormalizersAndEncodersUseDefaultContextConfigOption(string $
...
+            if (null === $reflectionConstructor = (new \ReflectionClass($class))->getConstructor()) {
+                continue;
+            }
+            foreach ($reflectionConstructor->getParameters() as $reflectionParam) {
+                if ('array $defaultContext' === $reflectionParam->getType().' $'.$reflectionParam->getName()) {
+                    yield [$serviceId.'.alias'];
+                    break;
+                }
+            }
+        }
```
Comment (HypeMC) [inline src/Symfony/Bundle/FrameworkBundle/Tests/Functional/SerializerTest.php]: I made this dynamic in case new normalizers/encoders were added. Is it worth it, no idea.

File: src/Symfony/Bundle/FrameworkBundle/Tests/Functional/app/Serializer/default_context.yaml
Comment (HypeMC) [inline src/Symfony/Bundle/FrameworkBundle/Tests/Functional/app/Serializer/default_context.yaml:1]: I moved this into a separate config were `circular_reference_handler` and `max_depth_handler` are not set.

**Comment by ruudk** [comment]
@HypeMC I just tested it and it does indeed solve my problem. Thanks!

@fabpot Just a heads up. It would be great to have this fix also in 7.1.1.

**Review by dbu — APPROVED** [review]
i just ran into this regression with Symfony 6.4.

maybe the maintainers could merge just the BC break fix quickly and look into the expanded tests separately, to at least fix the problem? meanwhile i will need to lock onto version 6.4.7 to prevent the bug. 5.4.39 and ~7.0 would be versions without the bug - 7.1.0 has the bug so if you are on 7.1 you are out of luck.

but i also like the idea of adding the missing tests to prevent the regression from re-occurring.

**Comment by dbu** [comment]
the ci failures seem unrelated to the changes: fabbot seems to look at the DI extension class because it is touched, but the complaints are not about the changes in this PR, and appveyor fails on something completely unrelated. 

if the latest 5.4 branch is green, this PR could be rebased on 5.4 to get them green.

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @HypeMC.

**Comment by ruudk** [comment]
Thanks @HypeMC for all the work fixing this 🥳

**Comment by ruudk** [comment]
@fabpot Could this be tagged for 7.1?

**Comment by fabpot** [comment]
As it was merged in 5.4, it will indeed be part of the next 7.1 release.
