### PR TITLE
[PropertyAccess] use bitwise flags to configure when the property accessor should throw

### LINKED ISSUE #31126: [PropertyAccessor] [DX] - Use bitmask arguments to set up throwExceptionOnInvalidIndex and throwExceptionOnInvalidPropertyPath
**Description**  
I'd like to have a bitmask argument in the `PropertyAccessor` constructor. Currently, it's hard to understand on the first sight what each argument means while initializing `PropertyAccessor`. I know that PropertyAccessor intended not to be used in the application code, but it doesn't prevent to use it anyway.

**Example**  

***Before***:
```php
new PropertyAccessor(
	$magicCall = false, 
	$throwExceptionOnInvalidIndex = false, 
	$cacheItemPool = null, 
	$throwExceptionOnInvalidPropertyPath = false
);
```
***After***:
- By default:
```php
new PropertyAccessor(
	$magicCall = false, 
	$bitmask = 0,
	$cacheItemPool = null
);
```

- To throw an exception on the invalid index:
```php
new PropertyAccessor(
	$magicCall = false, 
	$bitmask = PropertyAccessor::THROW_EXCEPTION_ON_INVALID_INDEX, /* 1 */
	$cacheItemPool = null
);
```

- To throw an exception on the invalid property path:
```php
new PropertyAccessor(
	$magicCall = false, 
	$bitmask = PropertyAccessor::THROW_EXCEPTION_ON_INVALID_PROPERTY_PATH, /* 2 */
	$cacheItemPool = null
);
```

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Tickets       | Fix #31126
| License       | MIT
| Doc PR        |

### CODE REVIEW

File: src/Symfony/Component/PropertyAccess/PropertyAccessor.php [hunk 1]
```diff
@@ -82,22 +86,56 @@ class PropertyAccessor implements PropertyAccessorInterface
...
+
+            $throw = $throw ? self::THROW_ON_INVALID_INDEX : self::DO_NOT_THROW;
+
+            if (!\is_bool($readInfoExtractor)) {
+                $throw |= self::THROW_ON_INVALID_PROPERTY_PATH;
+            }
+        }
+
+        if (\is_bool($readInfoExtractor)) {
+            trigger_deprecation('symfony/property-access', '5.3', 'Passing a boolean as the fourth argument to "%s()" is deprecated. Pass a %s instance instead.', __METHOD__, PropertyReadInfoExtractorInterface::class);
```
Comment (ogizanagi) [inline src/Symfony/Component/PropertyAccess/PropertyAccessor.php]: I think this message is misleading: the 4th argument was about throwing on invalid property path. The "instead" part regarding the intent is not passing an instance of `PropertyReadInfoExtractorInterface`, but using a proper combination of bitwise flags as second argument.

Comment (xabbuh) [reply src/Symfony/Component/PropertyAccess/PropertyAccessor.php]: updated

**Review by jderusse — COMMENTED** [review]
would be great to provide tests that cover the legacy paths

File: src/Symfony/Component/PropertyAccess/PropertyAccessor.php [hunk 2]
```diff
@@ -96,10 +104,40 @@ public function __construct(/*int */$magicMethods = self::MAGIC_GET | self::MAGI
...
+        if (\is_bool($readInfoExtractor)) {
+            trigger_deprecation('symfony/property-access', '5.3', 'Passing a boolean as the fourth argument to "%s()" is deprecated. Pass a combination of bitwise flags as the second argument instead (i.e an integer).', __METHOD__);
+
+            if ($readInfoExtractor) {
+                $throw |= self::THROW_ON_INVALID_PROPERTY_PATH;
+            }
+
+            $readInfoExtractor = $writeInfoExtractor;
+
+            if (null !== $readInfoExtractor && !$readInfoExtractor instanceof PropertyReadInfoExtractorInterface) {
```
Comment (stof) [inline src/Symfony/Component/PropertyAccess/PropertyAccessor.php]: this check must be outside the `\is_bool($readInfoExtractor)` condition  (after it) otherwise the type is not checked anymore when migrating to the new signature (as there is no typehints due to the argument removal)

Comment (xabbuh) [reply src/Symfony/Component/PropertyAccess/PropertyAccessor.php]: fixed

**Comment by xabbuh** [comment]
@jderusse tests added

**Review by maxhelias — APPROVED** [review]

**Review by ogizanagi — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

File: UPGRADE-5.3.md [hunk 3]
```diff
@@ -61,6 +61,12 @@ PhpunitBridge
 
  * Deprecated the `SetUpTearDownTrait` trait, use original methods with "void" return typehint
 
+PropertyAccess
+--------------
+
+* Deprecated passing a boolean as the second argument of `PropertyAccessor::__construct()`.
+  Pass a combination of bitwise flags instead.
```
Comment (chalasr) [inline UPGRADE-5.3.md]:
```suggestion
* Deprecate passing a boolean as the second argument of `PropertyAccessor::__construct()`,
  pass a combination of bitwise flags instead.
```

File: UPGRADE-6.0.md [hunk 4]
```diff
@@ -147,6 +147,8 @@ PhpUnitBridge
 PropertyAccess
 --------------
 
+ * Dropped support for booleans as the second argument of `PropertyAccessor::__construct()`.
+   Pass a combination of bitwise flags instead.
```
Comment (chalasr) [inline UPGRADE-6.0.md]:
```suggestion
 * Drop support for booleans as the second argument of `PropertyAccessor::__construct()`,
   pass a combination of bitwise flags instead.
```

File: src/Symfony/Component/PropertyAccess/CHANGELOG.md [hunk 5]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+5.3.0
+-----
+
+ * deprecated passing a boolean as the second argument of `PropertyAccessor::__construct()`, expecting a combination of bitwise flags instead
```
Comment (chalasr) [inline src/Symfony/Component/PropertyAccess/CHANGELOG.md]:
```suggestion
 * deprecate passing a boolean as the second argument of `PropertyAccessor::__construct()`, expecting a combination of bitwise flags instead
```

**Review by chalasr — CHANGES_REQUESTED** [review]

**Comment by xabbuh** [comment]
@chalasr fixed

**Review by chalasr — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you Christian.
