### PR TITLE
[Process] intersect with getenv() to populate default envs

### LINKED ISSUE #44066: [Process] defaultEnv not properly generated in PHP build-in webserver
### Symfony version(s) affected

process 5.3.7

### Description

The php-doc says 
https://github.com/symfony/symfony/blob/f7d70f1ab4be3bd98432cf9eccc4fa53f9fd36c4/src/Symfony/Component/Process/Process.php#L137
With `$env = null` it will take the Enviroment of the current process. This is not allways true. 
Using the [PHP Build-In Webserver](https://www.php.net/manual/en/features.commandline.webserver.php) (`php -S localhost:80`) `$_ENV` is empty (but `getenv()` is not), so 
https://github.com/symfony/symfony/blob/f7d70f1ab4be3bd98432cf9eccc4fa53f9fd36c4/src/Symfony/Component/Process/Process.php#L1672 
gives unexpected result. Especially the PATH variable remains unset, which leads to unfound binaries 

### How to reproduce

Use php build in webserver (see above) and use e.g
```php
$p = new Process(['pdflatex'], __DIR__, null)
```
(set `$env = null`)
-> PATH Variable is not set in `$_ENV` only in `getenv()`

### Possible Solution

Use `getEnv()` instead of `$_ENV` or check for
```php 
if (php_sapi_name() === 'cli-server') {
```

### Additional Context

`php -S` is (often) used in local development environments. Missing PATH Variables can be a big issue there.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44066
| License       | MIT
| Doc PR        | -

### CODE REVIEW

File: src/Symfony/Component/Process/Process.php [hunk 1]
```diff
@@ -1671,13 +1671,8 @@ private function replacePlaceholders(string $commandline, array $env)
...
     {
-        $env = [];
-
-        foreach ($_SERVER as $k => $v) {
-            if (\is_string($v) && false !== $v = getenv($k)) {
-                $env[$k] = $v;
-            }
-        }
+        $env = getenv();
+        $env = array_intersect_key(getenv(), $_SERVER) ?: $env;
```
Comment (stof) [inline src/Symfony/Component/Process/Process.php]: why calling `getenv()` a second time rather than using `$env` ?

Comment (nicolas-grekas) [reply src/Symfony/Component/Process/Process.php]: indeed, removed

File: src/Symfony/Component/Process/Process.php [hunk 2]
```diff
@@ -1671,13 +1671,8 @@ private function replacePlaceholders(string $commandline, array $env)
...
     {
-        $env = [];
-
-        foreach ($_SERVER as $k => $v) {
-            if (\is_string($v) && false !== $v = getenv($k)) {
-                $env[$k] = $v;
-            }
-        }
+        $env = getenv();
+        $env = array_intersect_key($env, $_SERVER) ?: $env;
```
Comment (Seldaek) [inline src/Symfony/Component/Process/Process.php:1675]: This means if the current running process has added env vars putenv(), they still won't be detected though. One has to update $_SERVER + do putenv() for it to be taken into account.

Comment (nicolas-grekas) [reply src/Symfony/Component/Process/Process.php:1675]: That's right, we are intentionally not compatible with putenv() here, because using putenv leads to blank pages in Windows

File: src/Symfony/Component/Process/Process.php [hunk 3]
```diff
@@ -1671,13 +1671,8 @@ private function replacePlaceholders(string $commandline, array $env)
 
     private function getDefaultEnv(): array
     {
-        $env = [];
-
-        foreach ($_SERVER as $k => $v) {
-            if (\is_string($v) && false !== $v = getenv($k)) {
```
Comment (devsi) [inline src/Symfony/Component/Process/Process.php:1677]: Removal of the is_string check seems to be allowing arrays to get in to the env array as values. This causes an error "ErrorException Array to string conversion" when the env vars are read as a string in the start() method()

Comment (nicolas-grekas) [reply src/Symfony/Component/Process/Process.php:1677]: Already fixed, see https://github.com/symfony/symfony/pull/44208
Please create issue instead of commenting on closed PRs to report issue btw.
