### PR TITLE
[Translation] Fix default value for locales in translation push|pull commands

### LINKED ISSUE #41501: [Translation] Push command error
**Symfony version(s) affected**: 5.3.x

**Description**
Error message about missing config when config in place.

Edit: Config does not seem to be read properly for domains and locales at all, it only uses the command line inputs

**How to reproduce**
Copy the example from https://symfony.com/doc/current/translation.html#translation-providers and run `php bin/console translation:push loco --force`

**Possible Solution**
This either needs to check `framework.translator.providers.%s.locales` or remove it from the error message.

Edit: Add config checks for domains and locales 

**Additional context**
https://github.com/symfony/translation/blob/251de0d921c42ef0a81494d8f37405421deefdf6/Command/TranslationPushCommand.php#L97-L99

Edit: https://github.com/symfony/translation/blob/251de0d921c42ef0a81494d8f37405421deefdf6/Command/TranslationPushCommand.php#L103-L105

### PR DESCRIPTION
**Pull request by welcoMattic**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #41501 
| License       | MIT
| Doc PR        | 

This PR ensures that `$locales` are always defined either `framework.translator.enabled_locales` or `framework.translator.providers.(loco|lokalise|crowdin).locales` is defined. Until now, the code expected `framework.translator.enabled_locales` to be defined, now if it's not, we merge all `framework.translator.providers.(loco|lokalise|crowdin).locales` values and pass them to `console.command.translation_pull` and `console.command.translation_push` definitions.

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -1360,24 +1360,30 @@ private function registerTranslatorConfiguration(array $config, ContainerBuilder
...
+
         foreach ($config['providers'] as $name => $provider) {
-            if (!$config['enabled_locales'] && !$provider['locales']) {
-                throw new LogicException(sprintf('You must specify one of "framework.translator.enabled_locales" or "framework.translator.providers.%s.locales" in order to use translation providers.', $name));
+            if (!$config['enabled_locales']) {
+                if (!$provider['locales']) {
+                    throw new LogicException(sprintf('You must specify one of "framework.translator.enabled_locales" or "framework.translator.providers.%s.locales" in order to use translation providers.', $name));
+                }
+
+                $locales = array_merge($locales, $provider['locales']);
```
Comment (DevScyu) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Is array_merge really the intended way here? Shouldn't the locale options for the provider be what controls what locales get sent to the provider, even if we have more locales enabled?

File: src/Symfony/Component/Translation/Command/TranslationPushCommand.php [hunk 2]
```diff
@@ -94,13 +94,13 @@ protected function configure()
      */
     protected function execute(InputInterface $input, OutputInterface $output): int
     {
+        $provider = $this->providers->get($input->getArgument('provider'));
+
         if (!$this->enabledLocales) {
-            throw new InvalidArgumentException('You must define "framework.translator.enabled_locales" or "framework.translator.providers.%s.locales" config key in order to work with translation providers.');
+            throw new InvalidArgumentException(sprintf('You must define "framework.translator.enabled_locales" or "framework.translator.providers.%s.locales" config key in order to work with translation providers.', parse_url($provider, \PHP_URL_SCHEME)));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Command/TranslationPushCommand.php:100]: the scheme doesn't always match the key, does it?

Comment (welcoMattic) [reply src/Symfony/Component/Translation/Command/TranslationPushCommand.php:100]: For the 3 existing providers, yes it does, but you are right, it might not match for future providers.

Comment (nicolas-grekas) [reply src/Symfony/Component/Translation/Command/TranslationPushCommand.php:100]: let's make it a convention and they should all match :)

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 1 above)
Comment (welcoMattic) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Actually we want to pass to the commands all locales supported by all configured providers, in order to read local translations. That's why the `locales` property of the `TranslationPushCommand` has `enabledLocales` as default value (https://github.com/symfony/symfony/pull/41504/files#diff-a00f86baf85c337ee61148e5fff8d189edf224ef40382518307359f579f40e6aR66).

Then, the `FilteringProvider` class is a decorator for each actual provider, and in its `read` method, we intersect domains and locales : the ones come from the provider configurations, the others come from the `read` call from the command class.

But I'm ok, we need to review this part, to make it more explicit and more logical. One of the solution might be to use only locales of providers configuration, make this parameter mandatory? WDYT @nicolas-grekas, in terms of design?

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: I've no strong opinion. I'm fine with the current design.
But if someone disagrees, I'd be happy to know why.

Comment (welcoMattic) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Are @OskarStark or @Nyholm has an opinion on it?

**Comment by welcoMattic** [comment]
I just figured out there no relevant reason that `enabled_locales` was related to the locales passed to the push and pull commands. In fact, someone could need to pull/push translation for a locales which is not (yet) enabled. 

WDTY about not set locales for Providers from `enabled_locales`?

**Comment by nicolas-grekas** [comment]
It's true that this line might be strange:
https://github.com/welcoMattic/symfony/blob/94a451dcd1dd44a20a1b8038d1a12b80255460f6/src/Symfony/Component/Translation/Command/TranslationPushCommand.php#L100

I don't see how the 2nd DI parameter that ismentionned in the message relates to the command.
Maybe the command should default to the list of locales of each provider? Is that doable?

**Comment by welcoMattic** [comment]
It's pretty much what I thought to do, and make the following behaviour:

A provider will treat all locales (`framework.translator.enabled_locales`) by default, unless we pass explicit locales via CLI options.

Are we agree on it?

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 1 above)
Comment (welcoMattic) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: ping @OskarStark @Nyholm

**Comment by welcoMattic** [comment]
I've just pushed an update to use `enabled_locales` by default, and append all `framework.translator.providers.(loco|lokalise|crowdin).locales` values, then `array_unique` the result. It will allow users to defined a common list of locales for push/pull commands, and specify additional locales (for instance, a not yet enabled locale) for one or more provider.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @welcoMattic.
