### PR TITLE
[VarDumper] fixed DateCaster not displaying additional fields

### LINKED ISSUE #35699: [VarDumper] dumping DateTime instance with additionnel properties
**Description**  

The VarDumper component is shipped with a [DateCaster](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/VarDumper/Caster/DateCaster.php) class that cast `DateTimeInterface` objects.
When dumping a child class of `DateTime` with additional properties, those properties will not be displayed.

**Example**  

I recently worked with [azuyalabs/yasumi](https://github.com/azuyalabs/yasumi) which introduce a [Holiday](https://github.com/azuyalabs/yasumi/blob/develop/src/Yasumi/Holiday.php) class extending `DateTime`. 
Here's the result when I dump a `Holiday` instance:

Capture d’écran 2020-02-12 à 17 59 31

I've started on a PR to have the following result:

Capture d’écran 2020-02-12 à 17 59 41

But before submitting it, I would like to know if hiding child properties is intended ?

### PR DESCRIPTION
**Pull request by Veridis**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35699
| License       | MIT
| Doc PR        | ~

----

Here's the result with [Holiday](https://github.com/azuyalabs/yasumi/blob/develop/src/Yasumi/Holiday.php) class 

| before  | after
| ------- | -----
| before | after

### CODE REVIEW

File: src/Symfony/Component/VarDumper/Caster/DateCaster.php [hunk 1]
```diff
@@ -31,7 +37,11 @@ public static function castDateTime(\DateTimeInterface $d, array $a, Stub $stub,
             .($location ? ($d->format('I') ? "\nDST On" : "\nDST Off") : '')
         ;
 
-        $a = [];
+        $a = array_filter($a, static function ($key) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/VarDumper/Caster/DateCaster.php]: no need for this: the while logic can be replaced by 3 unset, isn't it?

Comment (Veridis) [reply src/Symfony/Component/VarDumper/Caster/DateCaster.php]: Agreed, this should also fix the CI :)

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @Veridis.
