### PR TITLE
[DoctrineBridge] Fix circular loop with EntityManager

### LINKED ISSUE #39619: Segmentation fault on cache clear
**Symfony version(s) affected**: 5.2.1

**Description**  
Update symfony from 5.2.0 to 5.2.1:
composer update symfony/*
Then error on cache:clear:
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /var/www/.../var/cache/dev/ContainerEOpepOZ/App_KernelDevDebugContainer.php on line 19176

Increasing memory limit to 512M. Segmentation fault error appears. Increasing imit to 2048M - the same error.
After downgrading the error disappears:
Package operations: 0 installs, 52 updates, 1 removal
  - Removing symfony/proxy-manager-bridge (v5.2.1)
  - Downgrading symfony/http-foundation (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/event-dispatcher (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/var-dumper (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/error-handler (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/http-kernel (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/doctrine-bridge (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/dependency-injection (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/string (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/console (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/filesystem (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/config (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/routing (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/finder (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/var-exporter (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/cache (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/framework-bundle (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/stopwatch (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/process (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/expression-language (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/uid (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/twig-bridge (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/twig-bundle (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/translation (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/security-core (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/property-info (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/property-access (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/security-http (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/security-guard (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/security-csrf (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/security-bundle (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/intl (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/options-resolver (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/form (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/asset (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/templating (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/mime (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/http-client (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/dom-crawler (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/browser-kit (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/css-selector (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/web-profiler-bundle (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/monolog-bridge (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/debug-bundle (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/dotenv (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/lock (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/maker-bundle (v1.26.1 => v1.25.0): Extracting archive
  - Downgrading symfony/orm-pack (v2.1.0 => v2.0.0): Extracting archive
  - Downgrading symfony/phpunit-bridge (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/serializer (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/validator (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/web-link (v5.2.1 => v5.2.0): Extracting archive
  - Downgrading symfony/yaml (v5.2.1 => v5.2.0): Extracting archive

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | fix #39619
| License       | MIT
| Doc PR        | -

This PR fix a segfault in EntityManager by making the LazyEventManager handle EventSubscriber in a lazy way.

Maybe #34200 too

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/Tests/ContainerAwareEventManagerTest.php [hunk 1]
```diff
@@ -166,3 +225,21 @@ public function foo()
...
+{
+    public $calledSubscribedEventsCount = 0;
+    private $listenedEvents;
+
+    public function __construct(array $listenedEvents)
+    {
+        $this->listenedEvents = $listenedEvents;
+    }
+
+    public function getSubscribedEvents()
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Tests/ContainerAwareEventManagerTest.php]: `: array`

**Review by nicolas-grekas — APPROVED** [review]
Somuch needed!

File: src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php [hunk 2]
```diff
@@ -136,16 +149,47 @@ public function removeEventListener($events, $listener)
         }
     }
 
+    /**
+     * Adds an EventSubscriber by its identifier in the ServiceLocator injected in the constructor.
+     */
+    public function addEventSubscriberId(string $subscriber): void
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php]: oh, one question: can't we provided the $ids to the constructor instead of adding a method?

File: src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php [hunk 3]
```diff
@@ -136,16 +149,47 @@ public function removeEventListener($events, $listener)
...
+    {
+        $this->initializedSubscribers = false;
+        $this->subscribers[$subscriber] = $subscriber;
+    }
+
+    /**
+     * Removes an EventSubscriber from its identifier in ServiceLocator injected in the constructor.
+     */
+    public function removeEventSubscriberId(string $subscriber): void
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php]: should be removed, since we don't use it

**Review by nicolas-grekas — CHANGES_REQUESTED** [review]

File: src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php (hunk 2 above)
Comment (jderusse) [reply src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php]: Hmm.. we can, but the benefit of adding a method is: it's also compatible with class that extends `ContainerAwareEventManager` and override the constructor.

Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php]: Child classes can also use the constructor argument. Also, this is a bug fix. Not adding any API is best.

File: src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php (hunk 3 above)
Comment (jderusse) [reply src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php]: done

File: src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php (hunk 2 above)
Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php]: Let's forget about classes that extend this.

Comment (jderusse) [reply src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php]: done

**Review by chalasr — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @jderusse.
