### PR TITLE
[symfony/mailjet-mailer] Fix invalid mailjet error managment

### LINKED ISSUE #45420: [symfony/mailjet-mailer] Error message is not processed correctly
### Symfony version(s) affected

5.4.4

### Description

When sending a mail via the mailjet api, the transport checks if the response code is 200. If it is not, it tries to fetch the error message from the response and throws an exception. At the moment, the code looks for `$result['Message']` which does not exist.

Instead, `$result` has a Messages (plural) array which is structured as follows:
image

I am not sure if this is a change in the api or if both variants can occur depending on the situation.

### How to reproduce

Simply send an invalid mail to the api. For example we tried to send a mail with a "from" header (lowercase).

### Possible Solution

Probably just grab the first error in the array.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alamirault**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45420 
| License       | MIT
| Doc PR        |

When mailjet API status code is not 200, response [is structured](https://dev.mailjet.com/email/guides/send-api-v31/) (see-below) and is not currently well managed.

Example of bad request response:

```JSON
{
  "Messages": [
    {
      "Status": "error",
      "Errors": [
        {
          "ErrorIdentifier": "8e28ac9c-1fd7-41ad-825f-1d60bc459189",
          "ErrorCode": "mj-0005",
          "StatusCode": 400,
          "ErrorMessage": "The To is mandatory but missing from the input",
          "ErrorRelatedTo": ["To"]
        }
      ]
    }
  ]
}
```

This PR fix `Undefined index: Message` and add unit tests.

### CODE REVIEW

File: src/Symfony/Component/Mailer/Bridge/Mailjet/Tests/Transport/MailjetApiTransportTest.php [hunk 1]
```diff
@@ -85,6 +91,273 @@ public function testPayloadFormat()
         $this->assertEquals('Qux', $replyTo['Name']);
     }
 
+    public function testDoSendApiSuccess()
+    {
+        $responseStub = $this->createMock(ResponseInterface::class);
```
Comment (fancyweb) [inline src/Symfony/Component/Mailer/Bridge/Mailjet/Tests/Transport/MailjetApiTransportTest.php]: Could this be a `MockResponse` instead? To avoid mocks.

File: src/Symfony/Component/Mailer/Bridge/Mailjet/Tests/Transport/MailjetApiTransportTest.php [hunk 2]
```diff
@@ -85,6 +91,273 @@ public function testPayloadFormat()
...
+            ]);
+        $responseStub
+            ->expects(self::once())
+            ->method('getHeaders')
+            ->with(false)
+            ->willReturn([
+                'x-mj-request-guid' => ['baz'],
+            ]);
+
+        $clientStub = $this->createMock(HttpClientInterface::class);
```
Comment (fancyweb) [inline src/Symfony/Component/Mailer/Bridge/Mailjet/Tests/Transport/MailjetApiTransportTest.php]: `MockHttpClient`?

File: src/Symfony/Component/Mailer/Bridge/Mailjet/Tests/Transport/MailjetApiTransportTest.php [hunk 3]
```diff
@@ -85,6 +89,185 @@ public function testPayloadFormat()
...
+        $responseHeaders = [
+            'x-mj-request-guid' => ['baz'],
+        ];
+
+        $response = new MockResponse($json, ['response_headers' => $responseHeaders]);
+
+        $client = new MockHttpClient($response);
+
+        $transport = new MailjetApiTransport(self::USER, self::PASSWORD, $client);
+        $method = new \ReflectionMethod(MailjetApiTransport::class, 'doSendApi');
```
Comment (fancyweb) [inline src/Symfony/Component/Mailer/Bridge/Mailjet/Tests/Transport/MailjetApiTransportTest.php]: Thanks for the changes. I think we can go further and use the public API, can you check https://github.com/alamirault/symfony/pull/1 and apply it if it looks good for you? Thanks.

Comment (alamirault) [reply src/Symfony/Component/Mailer/Bridge/Mailjet/Tests/Transport/MailjetApiTransportTest.php]: Indeed, it's clearer !

**Review by fancyweb — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @alamirault.
