### PR TITLE
[Messenger] gracefully handle missing event dispatchers

### LINKED ISSUE #34852: [Messenger] missing dependency symfony/event-dispatcher
**Symfony version(s) affected**: symfony/messenger: ^5

**Description**  
Currently the `symfony/messenger` has no dependency in composer.json to `symfony/event-dispatcher`, but the Code internally relies on `Symfony\Component\EventDispatcher\LegacyEventDispatcherProxy` and is not replaceable by e.G. just using the `event-dispatcher-contracts` as dependency.

See:

* `Symfony\Component\Messenger\Worker` - https://github.com/symfony/messenger/blob/39444584eaec8a351da331e519d705931aa97235/Worker.php#L50
* `Symfony\Component\Messenger\Middleware\SendMessageMiddleware` - https://github.com/symfony/messenger/blob/5c2a1563ad7cae9f4b51a7d968f179a576ae840e/Middleware/SendMessageMiddleware.php#L38

**How to reproduce**  
Send a Message asynchronously without having `symfony/event-dispatcher` as dependency. 💥 

**Possible Solution**  

v1: Add `symfony/event-dispatcher` as `require` in `composer.json`

v2 (prefered): Use the injected `Symfony\Contracts\EventDispatcher\EventDispatcherInterface` correctly without relying on the `LegacyEventDispatcherProxy`-class to be there.

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34852
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by weaverryan — APPROVED** [review]

File: src/Symfony/Component/Messenger/Middleware/SendMessageMiddleware.php [hunk 1]
```diff
@@ -39,7 +39,11 @@ class SendMessageMiddleware implements MiddlewareInterface
     public function __construct(SendersLocatorInterface $sendersLocator, EventDispatcherInterface $eventDispatcher = null)
     {
         $this->sendersLocator = $sendersLocator;
-        $this->eventDispatcher = LegacyEventDispatcherProxy::decorate($eventDispatcher);
+
+        if (null !== $eventDispatcher) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Middleware/SendMessageMiddleware.php]: maybe also add a class_exists check?
in master, could replace the contracts by PSR-14 if that makes sense btw

Comment (xabbuh) [reply src/Symfony/Component/Messenger/Middleware/SendMessageMiddleware.php]: I found some other places where we could make use of that too.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.
