### PR TITLE
[SecurityBundle] Empty line starting with dash under "access_control" causes all rules to be skipped

### LINKED ISSUE #40235: Empty line starting with dash under "access_control" causes all rules to be skipped
**Symfony version(s) affected**: 4.4.16

**Description**  
In my security.yaml, I had added a comment under the access_control entries. My editor automatically prepended the line with a dash, which I didn't notice. Suddenly my acceptance tests started failing and my application started to behave weirdly.

After hours of debugging and figuring out why the AccessListener wasn't throwing an AccessDenied exception anymore when logged out, I finally found the problematic line in the security.yml.

I think this is a big issue, because this tiny typo opened up my entire application to the public. I think there should be some kind of validation on the access_control lines, it should at least have an object with a path on the line, or something like that. See below for an easy reproduction:

**How to reproduce**  
```yaml
access_control:
    # This makes the logout route available during two-factor authentication, allows the user to cancel
    - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }

    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/reset-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - # some comment about what is happening here
    - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
    - { path: ^/login_check, role: IS_AUTHENTICATED_FULLY }
    - { path: ^/admin, roles: ROLE_ADMIN_MENU }
    - { path: ^/support, roles: ROLE_NO_ACCESS }
    - { path: ^/bewind, role: ROLE_SOMEROLE }
    - { path: ^/(meldingen|profile), roles: ROLE_USER}
    - { path: ^/(?!login|logout|login_check|api), roles: ROLE_SOMEOTHERROLE }
 ```
If you now logout, the security listeners will not throw an access denied exception and will not redirect you to /login, therefore all security lines AFTER the comment will not be adhered to and are fully accessible by an anonymous user.

**Possible Solution**  
Validation on the access_control lines, it should at least contain an object with the "path" key (I guess?)

### PR DESCRIPTION
**Pull request by monteiro**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #40235 ... 
| License       | MIT

When the IDE by mistake puts an empty line in `access_control` in security.yaml there is no warning that we have an empty row, making the rest of routes defined, to be ignored and possible to be accessed by anyone that can authenticate no matter the role.

# How to reproduce the issue

- git clone git@github.com:monteiro/symfony-issue-40235.git
- composer install
- symfony server:start
- open 127.0.0.1:8000/admin with username: "john_user" and password "123456"
- Since that user has only ROLE_USER should not be able to access the route... but because there is an empty line in "access_control" in `security.yaml`, "by mistake" it is possible to access the protected `ROLE_ADMIN` route.

### CODE REVIEW

File: src/Symfony/Bundle/SecurityBundle/Tests/DependencyInjection/SecurityExtensionTest.php [hunk 1]
```diff
@@ -415,6 +415,31 @@ public function testSwitchUserWithSeveralDefinedProvidersButNoFirewallRootProvid
         $this->assertEquals(new Reference('security.user.provider.concrete.second'), $container->getDefinition('security.authentication.switchuser_listener.foobar')->getArgument(1));
     }
 
+    public function testInvalidAccessControlWithEmptyRow()
+    {
+        $this->expectException(InvalidConfigurationException::class);
+        $this->expectExceptionMessage('There is an empty access control attributes set.');
```
Comment (derrabus) [inline src/Symfony/Bundle/SecurityBundle/Tests/DependencyInjection/SecurityExtensionTest.php]: Those to lines should be moved downwards, right above the line that we expect to trigger the exception.

**Review by derrabus — APPROVED** [review]
Looks good, I'm merely nit-picking here. 🙂

File: src/Symfony/Bundle/SecurityBundle/Tests/DependencyInjection/SecurityExtensionTest.php (hunk 1 above)
Comment (monteiro) [reply src/Symfony/Bundle/SecurityBundle/Tests/DependencyInjection/SecurityExtensionTest.php]: Done!

**Review by OskarStark — APPROVED** [review]

**Comment by wouterj** [comment]
Thank you for creating this PR including tests and a reproducer, @monteiro! That's perfect!

After looking at the changes, I'm wondering whether we qualify this as a BC break. More precisely, people may have been using the "empty attributes" feature to exclude some routes from the access control (e.g. a login form). However, this was never documented behavior.

Let's wait a bit for more comments from the core team whether or not this is a BC break. If we qualify it as such, I think it makes all sense to deprecate this in 5.x instead (and introducing this exception in 6.0). `IS_AUTHENTICATED_ANONYMOUSLY` or `PUBLIC_ACCESS` should be used instead of an empty array of attributes imho.

**Comment by derrabus** [comment]
> After looking at the changes, I'm wondering whether we qualify this as a BC break.

I thought about that as well and could live with going through the deprecation process for that.

> More precisely, people may have been using the "empty attributes" feature to exclude some routes from the access control (e.g. a login form). However, this was never documented behavior.

My current understanding of the behavior (please correct me if I'm wrong) is that the empty line simply matches every request without applying any access restrictions. The result is effectively that any subsequent line would become unreachable. That behavior is dangerously surprising imho.

Can we come up with a scenario where this change breaks an application that is not dangerously misconfigured?

**Comment by wouterj** [comment]
> Can we come up with a scenario where this change breaks an application that is not dangerously misconfigured?

```yaml
access_control:
  - { path: ^/login }
  - { path: ^/, roles: ROLE_USER }
```

I haven't verified it, but as far as I understand the code, this yaml file is equal to doing `- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }`.

The diff is checking `$attributes`, which are the `roles` + `allow_if` statements from access control.

**Comment by derrabus** [comment]
@wouterj With your example, the exception in this PR should not be triggered. The case that is caught here is this one:

```YAML
access_control:
  -
  - { path: ^/, roles: ROLE_USER }
```

**Comment by wouterj** [comment]
@derrabus as indicated with my last sentence, this case *is* caught by this PR, as the check is done over `$attributes`, which only contains the values of `roles` and `allow_if`. So maybe we should do this check over `$access`? (not sure how that works, as most options have a default value of `null`.

**Comment by derrabus** [comment]
> @derrabus as indicated with my last sentence, this case _is_ caught by this PR

Okay, that's indeed an issue then.

**Review by derrabus — CHANGES_REQUESTED** [review]
We need to make sure that @wouterj's example still works.

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 2]
```diff
@@ -191,6 +191,10 @@ private function createAuthorization(array $config, ContainerBuilder $container)
                 $attributes[] = $this->createExpression($container, $access['allow_if']);
             }
 
+            if (!$attributes) {
```
Comment (xabbuh) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]: What about instead checking that at least one of the keys in `$access` is not `null`?

Comment (xabbuh) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]: or the empty array in case of `method`, `ips` and `roles`

**Comment by monteiro** [comment]
Following @xabbuh advice I fixed this specific edge case and added @wouterj example to the test, so we are sure it is not breaking old behaviour. Let me know what you think.

Thanks for the help!

**Review by maxhelias — APPROVED** [review]

**Review by wouterj — APPROVED** [review]

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 3]
```diff
@@ -191,6 +191,14 @@ private function createAuthorization(array $config, ContainerBuilder $container)
                 $attributes[] = $this->createExpression($container, $access['allow_if']);
             }
 
+            $isEmptyAccess = 0 === \count(array_filter($access, function ($v) {
+                return !empty($v);
+            }));
+
+            if ($isEmptyAccess) {
+                throw new InvalidConfigurationException('There is an empty access control attributes set.');
```
Comment (wouterj) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]:
```suggestion
                throw new InvalidConfigurationException('One or more access control items are empty. Did you accidentally add lines only containing a "-" under "security.access_control"?');
```

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 4]
```diff
@@ -191,6 +191,14 @@ private function createAuthorization(array $config, ContainerBuilder $container)
                 $attributes[] = $this->createExpression($container, $access['allow_if']);
             }
 
+            $isEmptyAccess = 0 === \count(array_filter($access, function ($v) {
+                return !empty($v);
+            }));
+
+            if ($isEmptyAccess) {
```
Comment (wouterj) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]:
```suggestion
            $emptyAccess = array_filter($access, function ($v) {
                return array_filter($v);
            });

            if ($emptyAccess) {
```

I'm not sure, but I think this suggestion works. I believe we try to avoid `empty()` where possible in Symfony.

**Review by wouterj — COMMENTED** [review]
Maybe I was a bit too fast with my approval. I'm not 100% sure if my suggestions make sense.

**Comment by monteiro** [comment]
Let me know if there is anything I can do to help here.

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you @monteiro.

**Comment by monteiro** [comment]
Thanks to you @derrabus
