### PR TITLE
[SecurityBundle] fix accepting env vars in remember-me configurations

### LINKED ISSUE #36271: [Security] Cannot use env in RememberMe config
**Symfony version(s) affected**: 3.4.39

**Description**  
This is working until today's 3.4.39 update. using `env` in `security.yaml` causes this error.

```
Invalid type for path "security.firewalls.main.remember_me.lifetime". Expected int, but got string.
```

**How to reproduce**  
inside of security.yaml
```yaml
lifetime: '%env(int:REMEMBER_ME_COOKIE_LIFETIME)%'
```

**Possible Solution**  
Remove these lines
https://github.com/symfony/symfony/pull/35910/files#diff-63961cbd5c56cdeb2e94e6024d58327fR148-R149

**Additional context**  
image

### PR DESCRIPTION
**Pull request by zek**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36271
| License       | MIT
| Doc PR        | -

As @wouterj explained we cannot use env variables after #35910 merged. 

> Hmm, so I'm guessing this is what happens:
> 
> * `lifetime` is now an `integerNode()`
> * For the Config component (which IIRC doesn't know anything about env variables), you're passing a string: `"%env(int:REMEMBER_ME_COOKIE_LIFETIME)%"`
> * This throws an error, although if it wouldn't, the DI component would sucessfully process the string into a integer before it's used by any PHP class.
> 
> So we either make Config aware of environment variables (that's probably a huge feature) or we revert the `integerNode()` changes (as you suggested).
> 
> @HeahDude am I mislooking something, or would reverting these 2 lines not result in much harm? (only a little less strict config processor)

### CODE REVIEW

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/RememberMeFactory.php [hunk 1]
```diff
@@ -143,11 +143,10 @@ public function addConfiguration(NodeDefinition $node)
             ->booleanNode('catch_exceptions')->defaultTrue()->end()
         ;
 
+        // Be carefull! We should call scalarNode otherwise can't use `env variables` in configuration.
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/RememberMeFactory.php:146]: should be removed and replaced by a non-regression test instead :)

**Comment by nicolas-grekas** [comment]
Thank you @zek.
