### PR TITLE
[PropertyAccess] Fix handling property names with a `.`

### LINKED ISSUE #58100: Property Access fails on properties with a dot (.)
### Symfony version(s) affected

6.4.8 and 7.1.1

### Description

When serializing an object which has properties with a dot in the name, a NoSuchPropertyException is thrown.

### How to reproduce

Run this on PHP 8.3

composer.json for 6.4.8
```json
{
    "require": {
        "symfony/property-access": "^6",
        "symfony/serializer": "^6",
        "phpdocumentor/reflection-docblock": "^5.4"
    }
}
```

composer.json for 7.1.1
```json
{
    "require": {
        "symfony/property-access": "^7.1",
        "symfony/serializer": "^7.1",
        "phpdocumentor/reflection-docblock": "^5.4"
    }
}
```
test.php
```php
<?php
declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor;
use Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor;
use Symfony\Component\PropertyInfo\PropertyInfoExtractor;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer;
use Symfony\Component\Serializer\Normalizer\ArrayDenormalizer;
use Symfony\Component\Serializer\Normalizer\BackedEnumNormalizer;
use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;
use Symfony\Component\Serializer\Normalizer\JsonSerializableNormalizer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

$stdclass = (object) ['bankAccount.iban' => 'NL16TEST0436169118', 'bankSummary' => ''];

$reflectionExtractor   = new ReflectionExtractor();
$phpDocExtractor       = new PhpDocExtractor();
$propertyTypeExtractor = new PropertyInfoExtractor([$reflectionExtractor], [$phpDocExtractor, $reflectionExtractor], [$phpDocExtractor], [$reflectionExtractor], [$reflectionExtractor]);
$normalizers           = [
    new BackedEnumNormalizer(),
    new DateTimeNormalizer([DateTimeNormalizer::FORMAT_KEY => 'Y-m-d\TH:i:sP', DateTimeNormalizer::TIMEZONE_KEY => 'Z']),
    new ArrayDenormalizer(),
    new JsonSerializableNormalizer(),
    new ObjectNormalizer(
        null,
        null,
        null,
        $propertyTypeExtractor,
        null,
        null,
        [
            AbstractObjectNormalizer::SKIP_NULL_VALUES       => true,
            AbstractObjectNormalizer::PRESERVE_EMPTY_OBJECTS => true,
        ]
    ),
];

$encoders = [
    new JsonEncoder(),
];

$serializer = new Serializer($normalizers, $encoders);
$serializer->serialize($stdclass, 'json');
```

### Possible Solution

_No response_

### Additional Context

> Fatal error: Uncaught Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: Can't get a way to read the property "bankAccount" in class "stdClass". in /sites/property-access/vendor/symfony/property-access/PropertyAccessor.php on line 442
> 
> Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: Can't get a way to read the property "bankAccount" in class "stdClass". in /sites/property-access/vendor/symfony/property-access/PropertyAccessor.php on line 442
> 
> Call Stack:
>     0.0003     980096   1. {main}() /sites/property-access/test.php:0
>     0.0150    3787888   2. Symfony\Component\Serializer\Serializer->serialize($data = class stdClass { public $bankAccount.iban = 'NL16TEST0436169118'; public $bankSummary = '' }, $format = 'json', $context = ???) /sites/property-access/test.php:47
>     0.0150    3788264   3. Symfony\Component\Serializer\Serializer->normalize($data = class stdClass { public $bankAccount.iban = 'NL16TEST0436169118'; public $bankSummary = '' }, $format = 'json', $context = []) /sites/property-access/vendor/symfony/serializer/Serializer.php:129
>     0.0150    3789232   4. Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize($object = class stdClass { public $bankAccount.iban = 'NL16TEST0436169118'; public $bankSummary = '' }, $format = 'json', $context = []) /sites/property-access/vendor/symfony/serializer/Serializer.php:150
>     0.0150    3790360   5. Symfony\Component\Serializer\Normalizer\ObjectNormalizer->getAttributeValue($object = class stdClass { public $bankAccount.iban = 'NL16TEST0436169118'; public $bankSummary = '' }, $attribute = 'bankAccount.iban', $format = 'json', $context = ['_read_attributes' => TRUE, 'cache_key' => 'ecc5fabac235bf8e878a40312bf42ca4', 'circular_reference_limit_counters' => ['00000000000000160000000000000000' => 1]]) /sites/property-access/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:194
>     0.0150    3790360   6. Symfony\Component\PropertyAccess\PropertyAccessor->getValue($objectOrArray = class stdClass { public $bankAccount.iban = 'NL16TEST0436169118'; public $bankSummary = '' }, $propertyPath = 'bankAccount.iban') /sites/property-access/vendor/symfony/serializer/Normalizer/ObjectNormalizer.php:134
>     0.0153    3821504   7. Symfony\Component\PropertyAccess\PropertyAccessor->readPropertiesUntil($zval = [0 => class stdClass { public $bankAccount.iban = 'NL16TEST0436169118'; public $bankSummary = '' }], $propertyPath = class Symfony\Component\PropertyAccess\PropertyPath { private array $elements = [0 => 'bankAccount', 1 => 'iban']; private int $length = 2; private array $isIndex = [0 => FALSE, 1 => FALSE]; private array $isNullSafe = [0 => FALSE, 1 => FALSE]; private string $pathAsString = 'bankAccount.iban' }, $lastIndex = 2, $ignoreInvalidIndices = TRUE) /sites/property-access/vendor/symfony/property-access/PropertyAccessor.php:107
>     0.0153    3821720   8. Symfony\Component\PropertyAccess\PropertyAccessor->readProperty($zval = [0 => class stdClass { public $bankAccount.iban = 'NL16TEST0436169118'; public $bankSummary = '' }], $property = 'bankAccount', $ignoreInvalidProperty = FALSE, $isNullSafe = FALSE) /sites/property-access/vendor/symfony/property-access/PropertyAccessor.php:309
>

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58100
| License       | MIT

If the property path contains a dot, it is considered to be an access to an underlying property. However, some edge cases allow to have dots in property names, especially with `stdClass`.

Minimal reproducer:

```php
$stdclass = (object) ['bankAccount.iban' => 'NL16TEST0436169118', 'bankSummary' => ''];
$accessor = PropertyAccess::createPropertyAccessor();

dump($accessor->getValue($stdclass, 'bankAccount.iban')); // returns "NL16TEST0436169118"

$accessor->setValue($stdclass, 'bankAccount.iban', 'value');
dump($accessor->getValue($stdclass, 'bankAccount.iban')); // returns "value"
```

### CODE REVIEW

**Comment by xabbuh** [comment]
Shouldn't the dot be escaped in the property path instead?

**Comment by alexandre-daubois** [comment]
For the minimal reproducer, yes, but it doesn't help with the original issue where the author uses Serializer and doesn't have the hand on the underlying property paths.

Inevitably, this is closely linked to stdClass, hence the hard check in the code to make sure you're dealing with stdClass.

**Comment by xabbuh** [comment]
Can this not be fixed inside the Serializer component?

**Comment by alexandre-daubois** [comment]
Actually, escaping the dot seems only to work with array accesses. The following code breaks:

```php
$stdclass = (object) ['bankAccount.iban' => 'NL16TEST0436169118', 'bankSummary' => ''];
$accessor = PropertyAccess::createPropertyAccessor();

dump($accessor->getValue($stdclass, 'bankAccount\.iban')); // throws NoSuchPropertyException
```

Or maybe I'm using the wrong syntax?

File: src/Symfony/Component/PropertyAccess/PropertyAccessor.php [hunk 1]
```diff
@@ -150,7 +150,7 @@ public function getValue($objectOrArray, $propertyPath)
             self::VALUE => $objectOrArray,
         ];
 
-        if (\is_object($objectOrArray) && false === strpbrk((string) $propertyPath, '.[')) {
+        if (\is_object($objectOrArray) && (false === strpbrk((string) $propertyPath, '.[') || property_exists($objectOrArray, $propertyPath))) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/PropertyAccess/PropertyAccessor.php]: let's make this specific to stdClass?
this can be true for any object with dynamic properties but I don't think we need to support that, esp. if that costs too much, CPU-wise. Can you check this aspect.

Comment (alexandre-daubois) [reply src/Symfony/Component/PropertyAccess/PropertyAccessor.php]: I've made it specific to `stdClass`. Here a quick benchmark, testing both accessing stdClass and other objects:

```php
<?php

use Symfony\Component\PropertyAccess\PropertyAccess;

require 'vendor/autoload.php';

class Foo
{
    public $iban = 'NL16TEST0436169118';
    public $bankSummary = '';
}

$stdclass = (object) ['iban' => 'NL16TEST0436169118', 'bankSummary' => ''];
$accessor = PropertyAccess::createPropertyAccessor();

dump("Testing with stdClass");
foreach (range(1, 5) as $i) {
    $start = microtime(true);

    for ($j = 0; $j < 100000; $j++) {
        $accessor->setValue($stdclass, 'iban', 'value');
        $accessor->getValue($stdclass, 'iban');
    }

    $end = microtime(true);

    dump('Elapsed time: ' . ($end - $start) . ' seconds');
}

dump("\nTesting with Foo");
$foo = new Foo();
foreach (range(1, 5) as $i) {
    $start = microtime(true);

    for ($j = 0; $j < 100000; $j++) {
        $accessor->setValue($foo, 'iban', 'value');
        $accessor->getValue($foo, 'iban');
    }

    $end = microtime(true);

    dump('Elapsed time: ' . ($end - $start) . ' seconds');
}
```

Above is **with** the patch, below it 5.4 as is:

image

The difference is low for 100 000 iterations. After running the script several times, the time differences are explained more by external tasks that take up some CPU during execution.

**Review by xabbuh — APPROVED** [review]
LGTM

**Comment by nicolas-grekas** [comment]
Thank you @alexandre-daubois.
