### PR TITLE
[Validator] Fix required options not validated when constructor calls parent with null

### LINKED ISSUE #63362: [Validator] Deprecation BC-break: mandatory constraint options not validated when no options passed
### Symfony version(s) affected

7.4

### Description

In Symfony Validator 7.4 passing an array with options is deprecated in favor of using named constructor arguments. However, due to the deprecation logic being added, the constraint options are not being normalized anymore when no options are passed and the constructor is overriden. The normalization takes care of checking the mandatory options, and thus now it is possible to construct the constraint without all mandatory options passed.

The `normalizeOptions()` call in 7.3, always executed:
https://github.com/symfony/symfony/blob/7.3/src/Symfony/Component/Validator/Constraint.php#L113

The `normalizeOptions()` call in 7.4 is bypassed due to the early return above it in case of no options passed:
https://github.com/symfony/symfony/blob/7.4/src/Symfony/Component/Validator/Constraint.php#L124

### How to reproduce

**Steps to reproduce:** 
1. Create a custom constraint with mandatory options and override the constructor (with parent call)
2. Construct the custom constraint without passing any options

**Expected result:**
An `MissingOptionsException` being thrown

**Actual result:**
Constraint is constructed without exception being thrown and validator possibly breaking due to missing options

```php
#[\Attribute(\Attribute::TARGET_PROPERTY | \Attribute::TARGET_METHOD | \Attribute::IS_REPEATABLE)]
class MyConstraint extends Constraint
{
    public array $foo;

    public function __construct(mixed $options = null, ?array $groups = null, mixed $payload = null)
    {
        parent::__construct($options, $groups, $payload);
        
        // ...
    }

    public function getRequiredOptions(): array
    {
        return ['foo'];
    }
}
```
```php
new MyConstraint();
```

### Possible Solution

Make sure the options are always normalized, or fix the check that causes the issue by mismatching the class names when the constructor is overriden:
https://github.com/symfony/symfony/blob/7.4/src/Symfony/Component/Validator/Constraint.php#L113

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lacatoire**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63362
| License       | MIT

When a custom constraint overrides the constructor and calls `parent::__construct(null, $groups, $payload)`, the `\func_num_args() > 0` check in `Constraint::__construct()` caused an early return **before** `normalizeOptions()` could validate required options via `getRequiredOptions()`.

This meant that constraints with required options (returned by `getRequiredOptions()`) silently accepted missing options instead of throwing `MissingOptionsException`.

**Fix**: Remove the `\func_num_args() > 0` short-circuit from the condition. The remaining `self::class === (new \ReflectionMethod(...))->getDeclaringClass()->getName()` check correctly determines whether `getRequiredOptions()` is overridden:
- Not overridden → early return (no required options to validate)
- Overridden → fall through to `normalizeOptions()` which validates required options

**Test**: Added a test with a constraint fixture that has required options and a custom constructor calling `parent::__construct(null)`, verifying that `MissingOptionsException` is thrown.

### CODE REVIEW

File: src/Symfony/Component/Validator/Constraint.php [hunk 1]
```diff
@@ -132,6 +132,44 @@ public function __construct(mixed $options = null, ?array $groups = null, mixed
...
 
+    /**
+     * Checks whether the child class constructor has named parameters for each
+     * required option, meaning it handles their validation itself.
+     */
+    private function areRequiredOptionsHandledByChildConstructor(): bool
+    {
+        $constructor = new \ReflectionMethod($this, '__construct');
+
+        if (self::class === $constructor->getDeclaringClass()->getName()) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraint.php]:
```suggestion
        if (self::class === $constructor->class) {
```

File: src/Symfony/Component/Validator/Constraint.php [hunk 2]
```diff
@@ -132,6 +132,44 @@ public function __construct(mixed $options = null, ?array $groups = null, mixed
...
+            return false;
+        }
+
+        $requiredOptionsMethod = new \ReflectionMethod($this, 'getRequiredOptions');
+
+        if (self::class === $requiredOptionsMethod->getDeclaringClass()->getName()) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraint.php]:
```suggestion
        if (self::class === $requiredOptionsMethod->class) {
```

File: src/Symfony/Component/Validator/Constraint.php [hunk 3]
```diff
@@ -110,7 +110,7 @@ public function __construct(mixed $options = null, ?array $groups = null, mixed
     {
         unset($this->groups); // enable lazy initialization
 
-        if (null === $options && (\func_num_args() > 0 || self::class === (new \ReflectionMethod($this, 'getRequiredOptions'))->getDeclaringClass()->getName())) {
+        if (null === $options && ($this->areRequiredOptionsHandledByChildConstructor() || self::class === (new \ReflectionMethod($this, 'getRequiredOptions'))->getDeclaringClass()->getName())) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraint.php]: I suppose the 2nd part it not needed anymore:
```suggestion
        if (null === $options && $this->areRequiredOptionsHandledByChildConstructor()) {
```

File: src/Symfony/Component/Validator/Constraint.php [hunk 4]
```diff
@@ -132,6 +132,44 @@ public function __construct(mixed $options = null, ?array $groups = null, mixed
...
+
+        $requiredOptionsMethod = new \ReflectionMethod($this, 'getRequiredOptions');
+
+        if (self::class === $requiredOptionsMethod->getDeclaringClass()->getName()) {
+            return true;
+        }
+
+        $requiredOptions = $this->getRequiredOptions(false);
+
+        if (!$requiredOptions) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraint.php]:
```suggestion
        if (!$requiredOptions = $this->getRequiredOptions(false)) {
```

File: src/Symfony/Component/Validator/Constraint.php [hunk 5]
```diff
@@ -132,6 +132,44 @@ public function __construct(mixed $options = null, ?array $groups = null, mixed
...
+            return true;
+        }
+
+        $paramNames = [];
+        foreach ($constructor->getParameters() as $param) {
+            $paramNames[$param->getName()] = true;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraint.php]:
```suggestion
            $paramNames[$param->name] = true;
```

File: src/Symfony/Component/Validator/Constraint.php [hunk 6]
```diff
@@ -132,6 +132,46 @@ public function __construct(mixed $options = null, ?array $groups = null, mixed
         }
     }
 
+    /**
+     * Checks whether the child class constructor has named parameters for each
+     * required option, meaning it handles their validation itself.
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraint.php]: let's remove all comments, they're not really helpful

File: src/Symfony/Component/Validator/Constraint.php [hunk 7]
```diff
@@ -132,6 +132,46 @@ public function __construct(mixed $options = null, ?array $groups = null, mixed
...
+     */
+    private function areRequiredOptionsHandledByChildConstructor(): bool
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraint.php]: private method = should be after public/protected ones

**Review by nicolas-grekas — COMMENTED** [review]
One last nitpicking

**Comment by nicolas-grekas** [comment]
Thank you @lacatoire.

**Comment by acantepie** [comment]
Now, you have an error 500 if you extends Regex constraint without override `getRequiredOptions()` in symfony 7.4 ...

Exemple :
```
<?php

namespace App\Validator;

use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Validator\Constraints\RegexValidator;

#[\Attribute(\Attribute::TARGET_PROPERTY | \Attribute::TARGET_METHOD)]
class CustomRegex extends Regex
{
    public function __construct(
        ?array $groups = null,
    ) {
        parent::__construct(
            pattern: '/^xxxxx$/',
            message: 'Lorem ipsum ...',
            groups: $groups,
        );
    }

    public function validatedBy(): string
    {
        return RegexValidator::class;
    }
}
```

Throw 500 => `The options "pattern" must be set for constraint "App\Validator\CustomRegex".`
