### PR TITLE
[HttpFoundation] Allow Request::setFormat() to override predefined formats

### LINKED ISSUE #62226: [HttpFoundation] Regression in Request::getFormat() where new MIME types were already registered
### Symfony version(s) affected

7.4.0-BETA1

### Description

Drupal registers the MIME type `application/vnd.api+json` as format `api_json`.

#61267 also added `application/vnd.api+json` as format `jsonapi`.

After upgrading to Symfony 7.4 this causes routing failures where we specified routes that respond to the `api_json` format.

### How to reproduce

Symfony 7.3:
```
> $request = Symfony\Component\HttpFoundation\Request::create('/');
> $request->setFormat('api_json', 'application/vnd.api+json');
> $request->getFormat('application/vnd.api+json');
= "api_json"
```

Symfony 7.4:
```
> $request = Symfony\Component\HttpFoundation\Request::create('/');
> $request->setFormat('api_json', 'application/vnd.api+json');
> $request->getFormat('application/vnd.api+json');
= "jsonapi"
```

### Possible Solution

A workaround for this is to explicitly deregister the `jsonapi` format, but we shouldn't need to do this:

```
> $request = Symfony\Component\HttpFoundation\Request::create('/');
> $request->setFormat('api_json', 'application/vnd.api+json');
> $request->setFormat('jsonapi', []);
> $request->getFormat('application/vnd.api+json');
= "api_json"
```

Maybe `Request::getFormat()` should start looking from the newest entries first?

```
-        foreach (static::$formats as $format => $mimeTypes) {
+        foreach (array_reverse(static::$formats) as $format => $mimeTypes) {
```
or similarly `setFormat()` could prepend to `static::$formats` instead of appending?

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by longwave**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62226 
| License       | MIT

Since #61267 some additional MIME formats are predefined; in order to override the predefined formats you must explictly deregister them. This PR changes the order so formats added later take precedence.

### CODE REVIEW

**Comment by longwave** [comment]
Psalm failed because $format is nullable, but why is this allowed? What does it mean to pass null?

Perhaps this was a mistake in https://github.com/symfony/symfony/pull/33088/files#diff-779a02ff90f6fc60228d531d684382d3b585b3c823ba53028ff8d2a9e03a2ea0R1314

**Review by nicolas-grekas — APPROVED** [review]
I rebased the PR on branch 6.4 because the root issue exists there: the last calls to setFormat should replace the previous ones.
I also updated the implementation to fix this in getFormat instead.

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 1]
```diff
@@ -1298,15 +1298,22 @@ public function getFormat(?string $mimeType): ?string
             static::initializeFormats();
         }
 
+        $exactFormat = null;
+        $canonicalFormat = null;
+
         foreach (static::$formats as $format => $mimeTypes) {
```
Comment (longwave) [inline src/Symfony/Component/HttpFoundation/Request.php:1304]: Or just `array_reverse()` here?

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/Request.php:1304]: more memory copies we can prevent :)

**Comment by stof** [comment]
I have no idea why `setFormat` supports `null` as format. This should probably be deprecated (in a separate PR as we cannot deprecate things in 6.4)

**Comment by stof** [comment]
This looks like a mistake when adding the native type, as the old code was using `@param string $format`: https://github.com/symfony/symfony/blob/9fec71ea34c069c582c24878f0e1499789b8bf81/src/Symfony/Component/HttpFoundation/Request.php#L1327-L1330

**Comment by nicolas-grekas** [comment]
Thank you @longwave.
