### PR TITLE
[ObjectMapper] mapping on target (reverse-side mapping)

### LINKED ISSUE #60058: [ObjectMapper] Reverse side mapping and reflection property
### Symfony version(s) affected

7.3

### Description

Hello, 

I wanted to test the new experimental feature ObjectMapper by trying to Map from the reverse side of the mapped object (like that : 
```
class A
{
    public ?\DateTimeImmutable $beginAt;
}

#[Map(target: self::class, source: A::class)]
class B
{
    public ?\DateTimeImmutable $beginAt;
}
```
) which is maybe not supported for the moment I guess.

Anyway, the problem is that it is throwing a `MappingException`:

```
Property App\A::$Property [ public ?DateTimeImmutable $beginAt ] does not exist

in vendor/symfony/object-mapper/Metadata/ReflectionObjectMapperMetadataFactory.php (line 42)
in[ vendor/symfony/object-mapper/ObjectMapper.php ](file:///app/vendor/symfony/object-mapper/ObjectMapper.php#L301)-> create (line 301)
....
```

I think it is because of the method `ReflectionObjectMapperMetadataFactory::create` which is waiting a `?string $property = null` , but in my specific case i have a ReflectionProperty type (which may transform it to string to `Property App\A::$Property [ public ?DateTimeImmutable $beginAt ]`).

It seems to work when I use `$property->name` instead on ObjectMapper.php#L301, but i'm not sure if it's the awaited solution neither if the reverse side mapping is an intended feature.

(btw thanks for this awesome future component !)

### How to reproduce

```
class A
{
    public ?\DateTimeImmutable $beginAt;
}

#[Map(target: self::class, source: A::class)]
class B
{
    public ?\DateTimeImmutable $beginAt;
}
```

### Possible Solution

Check if the property is instance of `ReflectionProperty` and if so use `$property->name` instead 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60058
| License       | MIT

This allows to configure mapping on the target instead of the source:

```php
<?php

#[Map(target: self::class, source: A::class)]
class B
{
    public function __construct(#[Map(source: 'source')] public string $target)
    {
    }
}
```

### CODE REVIEW

File: src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php [hunk 1]
```diff
@@ -262,4 +264,13 @@ public function testTransformToWrongObject()
...
         $mapper->map($u);
     }
+
+    public function testMapTargetToSource()
+    {
+        $a = new MapTargetToSourceA('str');
+        $mapper = new ObjectMapper();
+        $b = $mapper->map($a, MapTargetToSourceB::class);
+        $this->assertInstanceOf(MapTargetToSourceB::class, $b);
+        $this->assertEquals('str', $b->target);
```
Comment (OskarStark) [inline src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php]: assertSame

File: src/Symfony/Component/ObjectMapper/Tests/Fixtures/MapTargetToSource/B.php [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\ObjectMapper\Tests\Fixtures\MapTargetToSource;
+
+use Symfony\Component\ObjectMapper\Attribute\Map;
+
+#[Map(target: self::class, source: A::class)]
```
Comment (fabpot) [inline src/Symfony/Component/ObjectMapper/Tests/Fixtures/MapTargetToSource/B.php]: Would it be possible to infer the target in such a case?

```suggestion
#[Map(source: A::class)]
```

Comment (soyuka) [reply src/Symfony/Component/ObjectMapper/Tests/Fixtures/MapTargetToSource/B.php]: sure, removed

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @soyuka.
