### PR TITLE
[Mailer][Sendgrid] Add support for `global` region

### LINKED ISSUE #61706: [Mailer] SendGrid's `global` region is hot handled correctly in `SendgridSmtpTransport`
### Symfony version(s) affected

7.3.2

### Description

This concerns the [sendgrid-mailer](https://github.com/symfony/sendgrid-mailer) component.

When a region is given, it results in the following address: `smtp.{region}.sendgrid.net`

However, for the `global` region, it must result in `smtp.sendgrid.net` (as if no region was given). `smtp.global.sendgrid.net` does not exist.

### How to reproduce

Use the following DSN: `sendgrid+smtp://{api_key}@default?region=global`

It results in the following error:
> Connection could not be established with host `ssl://smtp.global.sendgrid.net:465`

### Possible Solution

Treat the `global` region differently from other regions.

Of course, the workaround is not to provide a region at all. But not being able to always define a region  complicates configuration of the DSN somewhat (when it's assembled from different parts).

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by sonnymilton**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #61706 
| License       | MIT

This PR ensures that when the `global` region is provided to `SendgridSmtpTransport`, 
the correct host `smtp.sendgrid.net` is used.  

Previously, passing `region=global` resulted in the host being built as 
`smtp.global.sendgrid.net`, which does not exist.

### Why
- DSNs like `sendgrid+smtp://KEY@default?region=global` failed to connect.
- SendGrid documentation specifies that the "global" region is just `smtp.sendgrid.net` 
  (same as when no region is provided).

### How
- Updated `SendgridSmtpTransport` to special-case the `global` region.
- Added a unit test to cover this scenario.

### CODE REVIEW

File: src/Symfony/Component/Mailer/Bridge/Sendgrid/Transport/SendgridSmtpTransport.php [hunk 1]
```diff
@@ -27,7 +27,13 @@ class SendgridSmtpTransport extends EsmtpTransport
 {
     public function __construct(#[\SensitiveParameter] string $key, ?EventDispatcherInterface $dispatcher = null, ?LoggerInterface $logger = null, private ?string $region = null)
     {
-        parent::__construct(null !== $region ? \sprintf('smtp.%s.sendgrid.net', $region) : 'smtp.sendgrid.net', 465, true, $dispatcher, $logger);
+        $host = 'smtp.sendgrid.net';
+
+        if (null !== $region && 'global' !== strtolower($region)) {
```
Comment (fabpot) [inline src/Symfony/Component/Mailer/Bridge/Sendgrid/Transport/SendgridSmtpTransport.php]:
```suggestion
        if (null !== $region && 'global' !== $region) {
```

I don't think we need to make it case insensitive.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @sonnymilton.

**Comment by ivan-wolf** [comment]
Hi @sonnymilton, thank you for providing a fix to #61706!

Did you also check the `SendgridApiTransport`? It might be affected by the same problem.
