### PR TITLE
[DoctrineBridge] Use a single table in isSameDatabaseChecker

### LINKED ISSUE #54348: Doctrine Bridge creating random tables prevents fine grained database permissions
### Symfony version(s) affected

7.1.0

### Description

When running a database migration, a table `schema_subscriber_check_ <RANDOM-STRING>` is created and immediately dropped again.

This prevents us from setting restrictive database permissions where the Symfony application is only allowed to access a select subset of tables, but does not have the permission to create (and drop) arbitrary tables.

The corresponding code is located in [AbstractSchemaListener->getIsSameDatabaseChecker](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php#L22):

```php
$checkTable = 'schema_subscriber_check_'.bin2hex(random_bytes(7));
$connection->executeStatement(sprintf('CREATE TABLE %s (id INTEGER NOT NULL)', $checkTable));

try {
    $exec(sprintf('DROP TABLE %s', $checkTable));
} catch (\Exception) {
    // ignore
}
```

I was granting the following permissions for a single table in MySQL 5.7 to the Symfony application:

```
my_db.my_table:CREATE,DROP,SELECT,INSERT,UPDATE,DELETE
```

MySQL does not support granting permissions on table names with wild cards (`schema_subscriber_check_*`).

### How to reproduce

I don't seem to be able to trigger the call of `getIsSameDatabaseChecker` in a dummy application.

### Possible Solution

I am not 100% sure what the purpose of the "same database checker" is, so I can't propose an appropriate solution.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by GromNaN**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #54348
| License       | MIT

The `isSameDatabaseChecker` feature of the SchemaListener detect if 2 DBAL connections are connected to the same server and database by creating a temporary table with one connection and checking if the table exists using the other connection.

Creating a temporary table with a random name cause an issue to configure permissions, as an exhaustive list of table names can be required.

I propose to modify the implementation to always use the same table name, but insert a row with a random key with one connection and try to delete it with the other connection.
The table is dropped only if it is empty, to prevent concurrence issues.

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php [hunk 1]
```diff
@@ -28,32 +31,48 @@ protected function getIsSameDatabaseChecker(Connection $connection): \Closure
     {
         return static function (\Closure $exec) use ($connection): bool {
             $schemaManager = method_exists($connection, 'createSchemaManager') ? $connection->createSchemaManager() : $connection->getSchemaManager();
-            $checkTable = 'schema_subscriber_check_'.bin2hex(random_bytes(7));
+            $checkTable = 'schema_subscriber_check';
```
Comment (fabpot) [inline src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php]:
```suggestion
            $checkTable = '_schema_subscriber_check';
```

Having a `_` prefix is kind of a convention to signal this table is "internal" and to avoid name clashes (even if very unprobable).

File: src/Symfony/Bridge/Doctrine/CHANGELOG.md [hunk 2]
```diff
@@ -5,6 +5,7 @@ CHANGELOG
 ---
 
  * Deprecate `UniqueEntity::getRequiredOptions()` and `UniqueEntity::getDefaultOption()`
+ * Use a single table named `schema_subscriber_check` in schema listeners to detect same database connections
```
Comment (fabpot) [inline src/Symfony/Bridge/Doctrine/CHANGELOG.md]:
```suggestion
 * Use a single table named `_schema_subscriber_check` in schema listeners to detect same database connections
```

**Review by fabpot — CHANGES_REQUESTED** [review]
LGTM

**Review by OskarStark — APPROVED** [review]

**Review by mtarld — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
(rebase needed)

**Comment by GromNaN** [comment]
Rebased. I also added a functional test using 2 in-memory sqlite databases. Other tests use mocks.

**Comment by nicolas-grekas** [comment]
Thank you @GromNaN.
