### PR TITLE
[Form] Improve exception for unsubmitted form

### LINKED ISSUE #49619: Improve error exception for unsubmitted form
### Description

I was helping another Symfony user in a community, he was stuck with a form and he posted the following screenshot

image

So I explained to him the reason for this failure, but then I realized that indeed the exception message is misleading. As we know, it's not sufficient to call the `Form::isSubmitted()` method to ensure that the form is actually submitted.

The message should be changed to something like this: 

>Cannot check if an unsubmitted form is valid. Call Form::isSubmitted() and ensure that it's true before calling Form::isValid().

### Example

_No response_

### PR DESCRIPTION
**Pull request by KThiebault**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49619
| License       | MIT
| Doc PR        | -

This PR improves the error message when a form is submitted but its submission is not verified.

### CODE REVIEW

File: src/Symfony/Component/Form/Form.php [hunk 1]
```diff
@@ -646,7 +646,9 @@ public function isEmpty(): bool
     public function isValid(): bool
     {
         if (!$this->submitted) {
-            throw new LogicException('Cannot check if an unsubmitted form is valid. Call Form::isSubmitted() before Form::isValid().');
+            throw new LogicException(
+                'Cannot check if an unsubmitted form is valid. Call Form::isSubmitted() and ensure that it\'s true before calling Form::isValid().'
+            );
```
Comment (yceruto) [inline src/Symfony/Component/Form/Form.php]: According to Coding standard, you have to put it all together in one line: https://fabbot.io/report/symfony/symfony/49667/f01a2e80d29f94fcdd854c881dffa81b6f8179ca

**Review by yceruto — CHANGES_REQUESTED** [review]

**Comment by yceruto** [comment]
I think the new error message is better! Thanks for contributing to the project.

File: src/Symfony/Component/Form/Form.php (hunk 1 above)
Comment (KThiebault) [reply src/Symfony/Component/Form/Form.php]: Sorry for that, I'm fixing it ;)

**Review by yceruto — APPROVED** [review]

**Review by lyrixx — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @KThiebault.
