### PR TITLE
[Translation] [Loco] Fix idempotency of LocoProvider write method

### LINKED ISSUE #43953: [Translation] Loco provider fails when pushing for multiple domains
### Symfony version(s) affected

5.3.6

### Description

Given:

- non-empty Loco project.
- multiple translation domains

When pushing multiple domains to Loco, exception is thrown:

```
php bin\console translation:push loco --domains forms --domains messages --domains validators --force
12:31:09 INFO      [http_client] Request: "POST https://localise.biz/api/assets"
12:31:09 INFO      [http_client] Request: "POST https://localise.biz/api/assets"
12:31:09 INFO      [http_client] Request: "POST https://localise.biz/api/assets"
12:31:09 INFO      [http_client] Request: "POST https://localise.biz/api/assets"
12:31:10 INFO      [http_client] Response: "201 https://localise.biz/api/assets"
12:31:10 INFO      [http_client] Response: "201 https://localise.biz/api/assets"
12:31:10 INFO      [http_client] Response: "201 https://localise.biz/api/assets"
12:31:10 INFO      [http_client] Response: "201 https://localise.biz/api/assets"
12:31:10 INFO      [http_client] Request: "GET https://localise.biz/api/tags.json"
12:31:11 INFO      [http_client] Response: "200 https://localise.biz/api/tags.json"
12:31:11 INFO      [http_client] Request: "POST https://localise.biz/api/tags/forms.json"
12:31:11 INFO      [http_client] Response: "200 https://localise.biz/api/tags/forms.json"
12:31:11 INFO      [http_client] Request: "GET https://localise.biz/api/locales"
12:31:11 INFO      [http_client] Response: "200 https://localise.biz/api/locales"
12:31:11 INFO      [http_client] Request: "GET https://localise.biz/api/assets?filter=forms"
12:31:11 INFO      [http_client] Response: "200 https://localise.biz/api/assets?filter=forms"

In LocoProvider.php line 78:
                                                                                                        
  [ValueError]                                                                                          
  array_combine(): Argument #1 ($keys) and argument #2 ($values) must have the same number of elements  
                                                                                                        

Exception trace:
  at C:\work\jtmweb\vendor\symfony\loco-translation-provider\LocoProvider.php:78
 array_combine() at C:\work\jtmweb\vendor\symfony\loco-translation-provider\LocoProvider.php:78
 Symfony\Component\Translation\Bridge\Loco\LocoProvider->write() at C:\work\jtmweb\vendor\symfony\translation\Provider\FilteringProvider.php:47
 Symfony\Component\Translation\Provider\FilteringProvider->write() at C:\work\jtmweb\vendor\symfony\translation\Command\TranslationPushCommand.php:116
 Symfony\Component\Translation\Command\TranslationPushCommand->execute() at C:\work\jtmweb\vendor\symfony\console\Command\Command.php:299
 Symfony\Component\Console\Command\Command->run() at C:\work\jtmweb\vendor\symfony\console\Application.php:996
 Symfony\Component\Console\Application->doRunCommand() at C:\work\jtmweb\vendor\symfony\framework-bundle\Console\Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at C:\work\jtmweb\vendor\symfony\console\Application.php:295
 Symfony\Component\Console\Application->doRun() at C:\work\jtmweb\vendor\symfony\framework-bundle\Console\Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at C:\work\jtmweb\vendor\symfony\console\Application.php:167
 Symfony\Component\Console\Application->run() at C:\work\jtmweb\vendor\symfony\runtime\Runner\Symfony\ConsoleApplicationRunner.php:56
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at C:\work\jtmweb\vendor\autoload_runtime.php:35
 require_once() at C:\work\jtmweb\bin\console:11

translation:push [--force] [--delete-missing] [--domains [DOMAINS]] [--locales [LOCALES]] [--] [<provider>]


Process finished with exit code 255
```

### How to reproduce

1. Have empty Loco project.
2. Run this command once:
`php bin\console translation:push loco --domains forms --domains messages --domains validators --force`
3. Run same command again:
`php bin\console translation:push loco --domains forms --domains messages --domains validators --force`
Error occurs.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by welcoMattic**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #43953 
| License       | MIT
| Doc PR        | 

This PR fix the exception thrown when we push translations twice, with existing translations on Loco.

Explanation of the fix:

To translate an "asset" (a translation key in Loco vocabulary), we need its Loco `id`. But Loco does not allow us to retrieve an id from a key. So, we fetch all ids for the current domain. Then, we build a map with `key` as key, and `id` as value. After that, we can intersect the keys of this map and our messages array to get all Loco ids of the currently processed messages.

```php
foreach ($catalogue->all() as $domain => $messages) {
    $keysIdsMap = [];

    foreach ($this->getAssetsIds($domain) as $id) {
        $keysIdsMap[$this->retrieveKeyFromId($id, $domain)] = $id;
    }

    $ids = array_intersect_key($keysIdsMap, $messages);

    $this->translateAssets(array_combine(array_values($ids), array_values($messages)), $locale);
}
```

Todo:

- [x] Make some real tests to be 100% sure there is no BC
- [x] Add tests to guarantee the fix

### CODE REVIEW

File: src/Symfony/Component/Translation/Bridge/Loco/LocoProvider.php [hunk 1]
```diff
@@ -75,7 +75,12 @@ public function write(TranslatorBagInterface $translatorBag): void
             }
 
             foreach ($catalogue->all() as $domain => $messages) {
-                $ids = $this->getAssetsIds($domain);
+                $keysFromLoco = array_map(function ($id) use($domain) {
+                    return $this->retrieveKeyFromId($id, $domain);
+                }, $this->getAssetsIds($domain));
+
+                $ids = array_intersect($keysFromLoco, array_keys($messages));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Bridge/Loco/LocoProvider.php]: there's something strange from a logical pov:
the array combine below need the same cardinality in both argument
yet this intersection would mean that ids could have a lower cardinality
Do I miss something?

Comment (welcoMattic) [reply src/Symfony/Component/Translation/Bridge/Loco/LocoProvider.php]: You are right, I did something wrong here. I'm reworking on it in the coming days.

**Comment by welcoMattic** [comment]
Ready for review /cc @nicolas-grekas @OskarStark

File: src/Symfony/Component/Translation/Bridge/Loco/LocoProvider.php [hunk 2]
```diff
@@ -75,8 +75,15 @@ public function write(TranslatorBagInterface $translatorBag): void
...
-                $this->translateAssets(array_combine($ids, array_values($messages)), $locale);
+                $keysIdsMap = [];
+
+                foreach ($this->getAssetsIds($domain) as $id) {
+                    $keysIdsMap[$this->retrieveKeyFromId($id, $domain)] = $id;
+                }
+
+                $ids = array_intersect_key($keysIdsMap, $messages);
+
+                $this->translateAssets(array_combine(array_values($ids), array_values($messages)), $locale);
```
Comment (stof) [inline src/Symfony/Component/Translation/Bridge/Loco/LocoProvider.php:86]: what if some keys don't have an asset id ? This would fail in `array_combine` AFAICT due to the different number of items.

Comment (welcoMattic) [reply src/Symfony/Component/Translation/Bridge/Loco/LocoProvider.php:86]: The case could not happen, Loco generate an asset for every asset.

Comment (welcoMattic) [reply src/Symfony/Component/Translation/Bridge/Loco/LocoProvider.php:86]: As we just create assets for new keys, they mandatory have an asset id

**Review by stof — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @welcoMattic.
