### PR TITLE
[FrameworkBundle] Fix Router Cache

### LINKED ISSUE #35932: After a fresh install, a cache:clear is required and it's not effective without a wget + sleep before.
**Symfony version(s) affected**: 5.0.x

**Description**  

After a fresh install of  `symfony/skeleton` + `annotations` + a minimal code that do a simple route, a cache:clear is required. Moreover, the cache:clear fails if we don't do a previous wget or the equivalent and then sleep a bit before clearing the cache. 

**How to reproduce**  

This occurs on Ubuntu 19.10.  I put this code in `.../www/bug_app_ressources/src/Controller/TestController.php`

```
<?php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;

class TestController extends AbstractController
{
    /**
     * @Route("/test", name="test")
     */
    public function test()
    {
        return new Response(
            '<html><body>It\'s a test</body></html>'
        ); 
    }
}

```
and used this script to experiment:

```
cd /home/working/www
composer create-project symfony/skeleton bug_app
cd bug_app
composer require annotations
symfony server:ca:install
cp -p /home/working/www/bug_app_ressources/src/Controller/TestController.php ./src/Controller/
symfony serve -d 
# Issue: The app does not work unless we do a cache:clear.  
# Moreover, a wget followed by sleep is required for the cache:clear to be 
# effective.  Remove any of the three following commands to see that the 
# app will always fail. Depending on your environment, you might need to 
# increase the sleeping time to make it work.
wget https://localhost:8000/test
sleep .5
bin/console cache:clear -vvv
# After wget + sleep + cache:clear, depending on your environment, the next 
# wget to work might not occur immediately.
wget https://localhost:8000/test
sleep .05
wget https://localhost:8000/test
sleep .05
wget https://localhost:8000/test
sleep .05
wget https://localhost:8000/test
sleep .05
wget https://localhost:8000/test
sleep .05
wget https://localhost:8000/test
sleep .05
wget https://localhost:8000/test
symfony server:stop

```
**Additional context**  

It's only bugging me when I write a script to install different environments from scratch to experiment with Symfony. The work around is already in the script that is given above.

### PR DESCRIPTION
**Pull request by guillbdx**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35932
| License       | MIT

RouteCollection config cache didn't have the container file in the tracked resources. If container was recompiled, routes cache was not regenerated. This PR adds the container file to the route collection resources.

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/Routing/Router.php [hunk 1]
```diff
@@ -71,6 +72,14 @@ public function getRouteCollection()
             $this->collection = $this->container->get('routing.loader')->load($this->resource, $this->options['resource_type']);
             $this->resolveParameters($this->collection);
             $this->collection->addResource(new ContainerParametersResource($this->collectedParameters));
+
+            try {
+                $containerFile = ($this->paramFetcher)('kernel.cache_dir').'/'.($this->paramFetcher)('kernel.container_class').'.php';
+                if (file_exists($containerFile)) {
+                    $this->collection->addResource(new FileResource($containerFile));
+                }
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Routing/Router.php]: else $this->collection->addResource(new FileExistenceResource($containerFile));

Comment (guillbdx) [reply src/Symfony/Bundle/FrameworkBundle/Routing/Router.php]: Done.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @guillbdx.
