### PR TITLE
[Workflow] Deprecate `Event::getWorkflow()` method

### LINKED ISSUE #59748: [Workflow][Profiler] No information from chainned transition
### Symfony version(s) affected

6.4.18

### Description

In the workflow profiler, I have information for calls `can` and `apply` about the transition `to_state2` but no information about `to_state3` transition.

### How to reproduce

Workflow:

```yaml
my_workflow:
  type: state_machine
  marking_store:
      type: method
      property: state
  supports:
    - MyClass
  places:
    - state1
    - state2
    - state3
  
  transitions:
    to_state2:
      from: state1
      to: state2
    to_state3:
      from: state2
      to: state3
```

Event listener/subscriber:

```php
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class ContinueToState3 implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
            'workflow.my_workflow.completed.to_state2' => ['terminateOrder', \PHP_INT_MIN],
        ];
    }

    public function terminateOrder(Event $event): void
    {
        $workflow = $event->getWorkflow();
        $subject = $event->getSubject();
        if ($workflow->can($subject, 'to_state3')) {
            $workflow->apply($subject, 'to_state3');
        }
    }
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | kind of
| New feature?  | no
| Deprecations? | yes
| Issues        | Fix #59748
| License       | MIT

```diff
+use Symfony\Component\DependencyInjection\Attribute\Target;
 
 class ContinueToState3 implements EventSubscriberInterface
 {
+    public function __construct(
+        #[Target('your_workflow_name')]
+        private readonly WorkflowInterface $workflow,
+    ) {
+    }
 
     public static function getSubscribedEvents(): array
     {
         return [
             'workflow.your_workflow_name.completed.to_state2' => ['terminateOrder', \PHP_INT_MIN],
         ];
     }
 
     public function terminateOrder(Event $event): void
     {
         $subject = $event->getSubject();
-        if ($event->getWorkflow()->workflow->can($subject, 'to_state3')) {
-            $event->getWorkflow()->apply($subject, 'to_state3');
+        if ($this->workflow->can($subject, 'to_state3')) {
+            $this->workflow->apply($subject, 'to_state3');
         }
     }
 }
```

If one has a listener able to run on many workflow, it need to inject a locator

```php
   use Symfony\Component\DependencyInjection\ServiceLocator;
   use Symfony\Component\DependencyInjection\Attribute\AutowireLocator;
   use Symfony\Component\Workflow\Attribute\AsTransitionListener;
   use Symfony\Component\Workflow\Event\TransitionEvent;

   class GenericListener
   {
       public function __construct(
           #[AutowireLocator('workflow', 'name')]
           private ServiceLocator $workflows
       ) {
       }

       #[AsTransitionListener()]
       public function doSomething(TransitionEvent $event): void
       {
           $workflow = $this->workflows->get($event->getWorkflowName());
       }
   }
```

### CODE REVIEW

File: src/Symfony/Component/Workflow/Event/Event.php [hunk 1]
```diff
@@ -46,8 +46,14 @@ public function getTransition(): ?Transition
         return $this->transition;
     }
 
+    /**
+     * @deprecated since Symfony 7.3, inject the workflow in the constructor where you need it
+     */
+    #[\Deprecated(since: 'symfony/workflow 7.3')]
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Workflow/Event/Event.php]: can't we also add the same hint as below in this one?

File: src/Symfony/Component/Workflow/Event/Event.php [hunk 2]
```diff
@@ -46,8 +46,14 @@ public function getTransition(): ?Transition
...
     public function getWorkflow(): WorkflowInterface
     {
+        trigger_deprecation('symfony/workflow', '7.4', 'The "%s()" method is deprecated, inject the workflow in the constructor where you need it.', __METHOD__);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Workflow/Event/Event.php]:
```suggestion
        if (\PHP_VERSION_ID < 80400) {
            trigger_deprecation('symfony/workflow', '7.4', 'The "%s()" method is deprecated, inject the workflow in the constructor where you need it.', __METHOD__);
        }
```

**Review by nicolas-grekas — COMMENTED** [review]
Looks like my comment about `#[Deprecated]` would apply to the few other cases where we use it.
Alternatively, we could ban it from the codebase. It's not better than the annotation anyway.
We should maybe postpone using it to Symfony 8+, where we won't have to duplicate the runtime notice for PHP <8.4.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by stof** [comment]
> Alternatively, we could ban it from the codebase. It's not better than the annotation anyway.

The benefit of the native attribute is that PHP will report the deprecation in the place doing the call, not in the method being deprecated, so it gives a better location for the warning (in our system using `trigger_deprecation`, identifying the most useful location requires investigating the trace, which is not displayed by default by PHP for warnings IIRC, even though it is included when using `symfony/error-handler`).
But I agree we can delay its usage in our codebase until Symfony 8.x when we won't need a fallback anymore.

File: UPGRADE-7.3.md [hunk 3]
```diff
@@ -249,3 +249,54 @@ VarExporter
...
+       {
+           $subject = $event->getSubject();
+           if ($event->getWorkflow()->can($subject, 'to_state3')) {
+               $event->getWorkflow()->apply($subject, 'to_state3');
+           }
+       }
+   }
+   ```
+
+   After:
```
Comment (stof) [inline UPGRADE-7.3.md:277]: shouldn't the `after` show both alternatives, as done in your PR description ?

**Review by alexandre-daubois — APPROVED** [review]

File: UPGRADE-7.3.md (hunk 3 above)
Comment (lyrixx) [reply UPGRADE-7.3.md:277]: I added it (and fixed typo on naming + added use stmt)

**Comment by ro0NL** [comment]
```
$this->workflows->get($event->getWorkflowName());
```

im wondering if we can avoid `$this` and `$event` mixing to get a workflow, eg. is the deprecation really legit?

cant we fix `getWorkflow` instead? using the same solution (leveraging the actual DI target object)

**Comment by lyrixx** [comment]
> cant we fix `getWorkflow` instead? using the same solution (leveraging the actual DI target object)

I means injecting a locator in every workflow. IMHO this is not the respectability of the workflow to do that.

I already thought about using a custom event dispatcher, but a bit overkill IMHO.

More over, having a generic listener is really rare, so this use case is really limited

**Comment by nicolas-grekas** [comment]
Thank you @lyrixx.
