### PR TITLE
[Mailer] Remove line breaks in email attachment content with Sendgrid API

### LINKED ISSUE #33671: [Mailer] Attachments fail with Sendgrid transport due to base64 encoding format
**Symfony version(s) affected**: 4.3

**Description**  
When using the Sendgrid HTTP transport; Sending an email with an attachment results in an error 400 "The attachment content must be base64 encoded." Exception.

The Sendgrid API does not like line breaks in the base64 encoded attachment content it appears, but the Base64Encoder in Mime do.

**How to reproduce**  
Create a new `Symfony\Component\Mime\Email`, attach some arbitrary content and send the email.

**Possible Solution**  
In `Symfony\Component\Mailer\Bridge\Sendgrid\Http\Api\SendgridTransport::getAttachments`, replace the `\r\n` in the content returned from `$attachment->bodyToString`.

I have created a PR #33672

### PR DESCRIPTION
**Pull request by fyfey**
Line breaks are not allowed in attachment content when sending over the
API.

| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #33671, Closes #32645
| License       | MIT
| Doc PR        |

This is a fix for #33671. Send grid's API throws a 400 error when sending email attachments with default base64 encoding.
Removing the line breaks resolves this issue.

### CODE REVIEW

File: src/Symfony/Component/Mailer/Bridge/Sendgrid/Tests/Http/Api/SendgridTransportTest.php [hunk 1]
```diff
@@ -58,4 +58,51 @@ public function testSend()
 
         $mailer->send($email);
     }
+
+    public function testAttachmentEncoding()
+    {
+        $email = new Email();
+        $email->from('foo@example.com')
+            ->to('bar@example.com')
+            ->attach('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod', 'lorem.txt');
```
Comment (stof) [inline src/Symfony/Component/Mailer/Bridge/Sendgrid/Tests/Http/Api/SendgridTransportTest.php]: There is no line-break in this content, so this is not testing your patch.

Comment (chalasr) [reply src/Symfony/Component/Mailer/Bridge/Sendgrid/Tests/Http/Api/SendgridTransportTest.php]: @stof it does, line-breaks are added by the MIME-compliant base64 encoder: https://github.com/symfony/symfony/blob/7788612c3cb63cc44b2cabb4644a7fbd75c61e97/src/Symfony/Component/Mime/Encoder/Base64Encoder.php#L39

File: src/Symfony/Component/Mailer/Bridge/Sendgrid/Tests/Http/Api/SendgridTransportTest.php [hunk 2]
```diff
@@ -58,4 +58,51 @@ public function testSend()
 
         $mailer->send($email);
     }
+
+    public function testAttachmentEncoding()
```
Comment (javiereguiluz) [inline src/Symfony/Component/Mailer/Bridge/Sendgrid/Tests/Http/Api/SendgridTransportTest.php]: Maybe rename it to `testLineBreaksInEncodedAttachment()` ?

File: src/Symfony/Component/Mailer/Bridge/Sendgrid/Tests/Http/Api/SendgridTransportTest.php (hunk 1 above)
Comment (javiereguiluz) [reply src/Symfony/Component/Mailer/Bridge/Sendgrid/Tests/Http/Api/SendgridTransportTest.php]: This is so confusing that we should add a comment before the `->attach()` method. Something like:

```php
// even it content doesn't include new lines, the Base64 encoding performed later may add them
->attach('...)
```

**Comment by stof** [comment]
Maybe the actual issue is the usage of `bodyToString` on the DataPart, relying on the base64 encoding built for SMTP while this is sent to an HTTP API.

Btw, this may also impact other API providers.

**Comment by chalasr** [comment]
The SendGrid HTTP API requires attachments to be base64 encoded though (but with "strict" base64 i.e. no line-break). But API transports could indeed bypass the encoding system and use `base64_encode()` directly if needed, that's what I propose in #32645 for the very same bug.

**Comment by nicolas-grekas** [comment]
Thank you @fyfey.
