### PR TITLE
[JsonStreamer] Fix nested generated foreach loops

### LINKED ISSUE #60984: [JsonStreamer] Selialization brokes on multilevel collections
### Symfony version(s) affected

7.3.1

### Description

If I try to serialize collection of objects which have embedded collection, I get `Undefined property` error. 
The problem is in vendor/symfony/json-streamer/Write/StreamWriterGenerator.php:186, which generate code like
```
foreach ($value->events as $value)
```
and redefine $value with embedded object.

### How to reproduce

```
namespace App\Dto;

use Symfony\Component\JsonStreamer\Attribute\JsonStreamable;

#[JsonStreamable]
class User
{
    public array $names;
}
```

```
namespace App\Controller;

use App\Dto\User;
use App\Repository\UserRepository;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Symfony\Component\JsonStreamer\StreamWriterInterface;
use Symfony\Component\TypeInfo\Type;

class UserController
{
    public function retrieveUsers(StreamWriterInterface $jsonStreamWriter): StreamedResponse
    {
        $user1 = new User();
        $user1->names = ['John', 'Alex'];

        $user2 = new User();
        $user1->names = ['Mark', 'Andre'];

        $users = [$user1, $user2];

        $type = Type::list(Type::object(User::class));

        $json = $jsonStreamWriter->write($users, $type);

        return new StreamedResponse($json);
    }
}
```

### Possible Solution

Replace in vendor/symfony/json-streamer/Write/StreamWriterGenerator.php:186
```
                $this->createDataModel($type->getCollectionValueType(), new VariableDataAccessor('value'), $options, $context),

```
to
```
                $this->createDataModel($type->getCollectionValueType(), new VariableDataAccessor('value' . rand()), $options, $context),

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mttsch**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60984
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/JsonStreamer/Tests/Fixtures/stream_writer/nullable_object_dict.php [hunk 1]
```diff
@@ -5,13 +5,13 @@
         if (\is_array($data)) {
             yield '{';
             $prefix = '';
-            foreach ($data as $key => $value) {
+            foreach ($data as $key => $value1) {
```
Comment (mttsch) [inline src/Symfony/Component/JsonStreamer/Tests/Fixtures/stream_writer/nullable_object_dict.php]: In principle, nested loops with a key will have the same issue of the nested key variable having the same name as the outer one(s). However, as the key will be printed first/before a nested loop is entered and is not be used anymore after a nested loop is completed, this same name causes no issue as for the value name.

May-be if others see it as an issue, a new bug issue can be opened for it to keep this PR with the original issue fixing the reported bug.

File: src/Symfony/Component/JsonStreamer/Write/StreamWriterGenerator.php [hunk 2]
```diff
@@ -109,12 +109,12 @@ private function getPath(Type $type): string
      * @param array<string, mixed> $options
      * @param array<string, mixed> $context
      */
-    private function createDataModel(Type $type, DataAccessorInterface $accessor, array $options = [], array $context = []): DataModelNodeInterface
+    private function createDataModel(Type $type, DataAccessorInterface $accessor, array $options = [], array $context = [], int $recursionLevel = 1): DataModelNodeInterface
```
Comment (mtarld) [inline src/Symfony/Component/JsonStreamer/Write/StreamWriterGenerator.php]: What about adding a depth in `$context`? To be consistent with https://github.com/symfony/symfony/blob/7.3/src/Symfony/Component/JsonStreamer/Write/PhpAstBuilder.php#L212

File: src/Symfony/Component/JsonStreamer/Tests/JsonStreamWriterTest.php [hunk 3]
```diff
@@ -107,6 +109,12 @@ public function testWriteCollection()
             new \ArrayObject([new ClassicDummy(), new ClassicDummy()]),
             Type::iterable(Type::object(ClassicDummy::class), Type::int()),
         );
+
+        $this->assertWritten(
+            '[{"dummies":[{"id":1,"name":"dummy"}],"customProperty":"customProperty1"},{"dummies":[{"id":1,"name":"dummy"}],"customProperty":"customProperty2"}]',
+            [new DummyWithArray([new JsonStreamableDummy()], 'customProperty1'), new DummyWithArray([new JsonStreamableDummy()], 'customProperty2')],
+            Type::list(Type::object(DummyWithArray::class)),
```
Comment (mtarld) [inline src/Symfony/Component/JsonStreamer/Tests/JsonStreamWriterTest.php:125]: Can you test `DummyWithNestedArray` as well?

File: src/Symfony/Component/JsonStreamer/Tests/Fixtures/stream_writer/nullable_object_dict.php (hunk 1 above)
Comment (mtarld) [reply src/Symfony/Component/JsonStreamer/Tests/Fixtures/stream_writer/nullable_object_dict.php]: I'd have done the same for `$key` (using `$context['depth']) right away in order to be safe.

File: src/Symfony/Component/JsonStreamer/Tests/Fixtures/Model/JsonStreamableDummy.php [hunk 4]
```diff
@@ -0,0 +1,12 @@
+<?php
+
+namespace Symfony\Component\JsonStreamer\Tests\Fixtures\Model;
+
+use Symfony\Component\JsonStreamer\Attribute\JsonStreamable;
+
+#[JsonStreamable]
+class JsonStreamableDummy
```
Comment (mtarld) [inline src/Symfony/Component/JsonStreamer/Tests/Fixtures/Model/JsonStreamableDummy.php]: This is the same as `ClassicDummy` and therefore can be removed.

File: src/Symfony/Component/JsonStreamer/Tests/Fixtures/Model/DummyWithNestedArray.php [hunk 5]
```diff
@@ -0,0 +1,8 @@
+<?php
+
+namespace Symfony\Component\JsonStreamer\Tests\Fixtures\Model;
+
+class DummyWithNestedArray
+{
+    public function __construct(/** @var DummyWithArray[] */public array $dummies, public string $customProperty) {}
```
Comment (mtarld) [inline src/Symfony/Component/JsonStreamer/Tests/Fixtures/Model/DummyWithNestedArray.php]:
```suggestion
    /** @var DummyWithArray[] */
    public array $dummiesWithArray;
    
    public string $customProperty;
```

File: src/Symfony/Component/JsonStreamer/Tests/Fixtures/Model/DummyWithArray.php [hunk 6]
```diff
@@ -0,0 +1,8 @@
+<?php
+
+namespace Symfony\Component\JsonStreamer\Tests\Fixtures\Model;
+
+class DummyWithArray
+{
+    public function __construct(/** @var JsonStreamableDummy[] */public array $dummies, public string $customProperty) {}
```
Comment (mtarld) [inline src/Symfony/Component/JsonStreamer/Tests/Fixtures/Model/DummyWithArray.php]:
```suggestion
    /** @var ClassicDummy[] */
    public array $dummies;
    
    public string $customProperty;
```

**Review by mtarld — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/JsonStreamer/Write/StreamWriterGenerator.php (hunk 2 above)
Comment (mttsch) [reply src/Symfony/Component/JsonStreamer/Write/StreamWriterGenerator.php]: I thought about it but was unsure about a line like this

https://github.com/symfony/symfony/blob/7.3/src/Symfony/Component/JsonStreamer/Write/PhpAstBuilder.php#L84

which would result in a `depth` context being provided from the outside (for whatever reason) being overridden. But if it is already used there, then I will also use it here.

File: src/Symfony/Component/JsonStreamer/Tests/Fixtures/stream_writer/nullable_object_dict.php (hunk 1 above)
Comment (mttsch) [reply src/Symfony/Component/JsonStreamer/Tests/Fixtures/stream_writer/nullable_object_dict.php]: For `$key`, it was not as trivial as for `$value` on first sight but I will have a look.

File: src/Symfony/Component/JsonStreamer/Tests/Fixtures/Model/DummyWithArray.php (hunk 6 above)
Comment (mttsch) [reply src/Symfony/Component/JsonStreamer/Tests/Fixtures/Model/DummyWithArray.php]: Is that really necessary? These properties are actively only used when creating the objects, thus making it easier to construct the objects inline.

**Comment by mttsch** [comment]
@mtarld Except for the constructor property promotion comment (see my response above), your notes have been implemented.

File: src/Symfony/Component/JsonStreamer/DataModel/Write/CollectionNode.php [hunk 7]
```diff
@@ -27,6 +27,7 @@ public function __construct(
         private DataAccessorInterface $accessor,
         private CollectionType $type,
         private DataModelNodeInterface $item,
+        private null|DataModelNodeInterface $key = null,
```
Comment (mtarld) [inline src/Symfony/Component/JsonStreamer/DataModel/Write/CollectionNode.php]:
```suggestion
        private DataModelNodeInterface $key,
```
Can't we make it mandatory?

File: src/Symfony/Component/JsonStreamer/Tests/Fixtures/Model/DummyWithArray.php (hunk 6 above)
Comment (mtarld) [reply src/Symfony/Component/JsonStreamer/Tests/Fixtures/Model/DummyWithArray.php]: Is it mostly to be consistent. At the moment, this component is supposed to work with plain old PHP objects with public properties and without constructor. The fact that it works during encoding is fortunate, but not intentional. In the other way, it won't work. So I'd rather keep these classes without constructor to avoid any confusion.

File: src/Symfony/Component/JsonStreamer/DataModel/Write/CollectionNode.php (hunk 7 above)
Comment (mttsch) [reply src/Symfony/Component/JsonStreamer/DataModel/Write/CollectionNode.php]: Yes, done.

File: src/Symfony/Component/JsonStreamer/Tests/Fixtures/Model/DummyWithArray.php (hunk 6 above)
Comment (mttsch) [reply src/Symfony/Component/JsonStreamer/Tests/Fixtures/Model/DummyWithArray.php]: Done and I also renamed one of the string properties because them having different names again (indirectly) tests that if the inner value would leak out as the other value, the test would fail because the second property of the other value does not exist on the inner value.

**Review by mtarld — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @mttsch.
