### PR TITLE
[Workflow] Make method signature compatible with 4.4

### LINKED ISSUE #35615: [Workflow] Regression from 4.4.4
**Symfony version(s) affected**: 5.0.0+

**Description**  

In 5.0.0 the signature of the `getMetadata` method was changed in one place to be non-nullable and require an object. This breaks backwards-compatibility without going through a deprecation cycle.

The underlying method signature hasn't changed and continues to accept - and work with - a null value.

**How to reproduce**  
```php
<?php

namespace App\Event\Subscriber;

use App\Entity\Application;
use App\Entity\Setting\ApplicationStatus;
use App\Lib\ApplicationMinder;
use App\Workflow\ApplicationWorkflow;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Workflow\Event\Event;
use Symfony\Component\Workflow\Event\GuardEvent;

/**
 * This is a general class for hooking into events. It's experimental and should be refactored later on
 *
 * Class ApplicationWorkflowEvents
 * @package App\Event\Subscriber
 */
class ApplicationWorkflowEvents implements EventSubscriberInterface
{
    public function __construct()
    {
    }

    public static function getSubscribedEvents()
    {
        return [
            // workflow.[workflow name].guard.[transition name]
            'workflow.' . ApplicationWorkflow::NAME . '.entered' => 'setApplicationStatus',
        ];
    }

    /**
     * Set the Application Status dropdown (the one staff see) to a new value based on metadata
     * attached to the Workflow transition.
     *
     * @param Event $event
     *
     * @throws \Doctrine\ORM\ORMException
     */
    public function setApplicationStatus(Event $event)
    {
        // @ERROR The line below works on 4.4.4, fails on 5.0.0 when $event->getTransition() === null
        if ($status = $event->getMetadata('applicationStatus', $event->getTransition())) {
            // Do stuff
        }
    }
}
```

**Possible Solution**  

Alter the method signature change in https://github.com/symfony/workflow/commit/680d6f264315964e86db035f794f68ffd8576fe3, which changed
```php
public function getMetadata(string $key, $subject)
```
to
```php
public function getMetadata(string $key, object $subject)
```
and make it nullable to match all other `getMetadata` method signatures.

### PR DESCRIPTION
**Pull request by pbowyer**
| Q             | A
| ------------- | ---
| Branch?       | 5.0 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #35615  
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

A method signature changed in a non-backwards-compatible way in 5.0.0 - and in only one class. This commit fixes that - and has been tested.

For full details see ticket #35615.

### CODE REVIEW

File: src/Symfony/Component/Workflow/Event/Event.php [hunk 1]
```diff
@@ -60,7 +60,7 @@ public function getWorkflowName()
         return $this->workflow->getName();
     }
 
-    public function getMetadata(string $key, object $subject)
+    public function getMetadata(string $key, ?object $subject)
```
Comment (lyrixx) [inline src/Symfony/Component/Workflow/Event/Event.php]: Actually, the type hint should be removed.

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Workflow/Metadata/MetadataStoreInterface.php#L34-L37

Comment (pbowyer) [reply src/Symfony/Component/Workflow/Event/Event.php]: Thanks, pushed a commit to remove it.

**Review by nicolas-grekas — APPROVED** [review]

**Review by lyrixx — APPROVED** [review]

**Comment by lyrixx** [comment]
Good catch, thanks Peter.
