### PR TITLE
[Security] Do not overwrite already stored tokens for REMOTE_USER authentication

### LINKED ISSUE #43648: [Security] User is loaded on every request
**Symfony version(s) affected**: 5.3.9

**Description**
After upgrading my application to Symfony 5.3 I tried to enable the new security system. Everything seems to work well. However, I discovered that a fresh user object is loaded by the UserProvider on **every request** (although it is still beeing loaded from the session).
I'm using REMOTE_USER authentication and a custom User and UserProvider implementation.

**How to reproduce**
I created a small dummy project to reproduce the problem: https://github.com/stlrnz/test-new-symfony-security

As you can see, there is nothing special in my implementation/configuration:

```php
<?php

declare(strict_types=1);

namespace App\Security;

use Symfony\Component\Security\Core\User\UserInterface;

class User implements UserInterface
{
    private $username;


    public function __construct(string $username)
    {
        $this->username = $username;
    }


    public function getRoles()
    {
        return ['ROLE_USER'];
    }


    public function getPassword()
    {
        return null;
    }


    public function getSalt()
    {
        return null;
    }


    public function eraseCredentials()
    {
    }


    public function getUsername()
    {
        return $this->username;
    }


    public function getUserIdentifier()
    {
        return $this->getUsername();
    }
}
```

```php
<?php

declare(strict_types=1);

namespace App\Security;

use Psr\Log\LoggerInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;

final class UserProvider implements UserProviderInterface
{
    private $logger;


    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }


    public function refreshUser(UserInterface $user)
    {
        $this->logger->debug('Refreshing user ' . $user->getUserIdentifier());

        return $user;
    }


    public function supportsClass(string $class)
    {
        return $class === User::class;
    }


    public function loadUserByUsername(string $username)
    {
        $this->logger->debug('Loading user ' . $username);

        return new User($username);
    }


    public function loadUserByIdentifier(string $username)
    {
        return $this->loadUserByUsername($username);
    }
}
```

```yaml
security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        custom_remote_user_provider:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            remote_user:
                provider: custom_remote_user_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
```

**Additional context**
As you can see the UserProvider writes two log messages for debugging.
When using the new security system the user is loaded on the first request:
> Loading user stlrnz

and refreshed **and** loaded on the following:
> Refreshing user stlrnz
> Loading user stlrnz

When using the old system by configuring
```yaml
security:
    enable_authenticator_manager: false
```
the user is still loaded on the first request
> Loading user stlrnz

and refreshed on the following (no loading as expected).
> Refreshing user stlrnz

Im my real application, loading a user is a very complex operation (requires some webservice calls etc.). And therfore it should not be done on every request. Is there a way to achive this?

I tried to understand why this happens in the new system. It seems that the Authenticator always triggers the load of the user through the passport to create an Authenticated Token.
https://github.com/symfony/symfony/blob/9f43121357bfdba3209de6bb974384ff36d8506f/src/Symfony/Component/Security/Http/Authenticator/AbstractPreAuthenticatedAuthenticator.php#L105

### PR DESCRIPTION
**Pull request by stlrnz**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #43648
| License       | MIT

As described in #43648 the user is currently loaded on every request for REMOTE_USER authentication.
Thanks to @wouterj for confirming me on Slack that this seems weird. So, I looked deeper into this.

I found out that other Authenticators tell the AuthenticatorManager only under special conditions (like matching route etc.) that they support the current request. However, the `AbstractPreAuthenticatedAuthenticator` is not so picky. In consequence, the user is authenticated again on every request.

Inspired by `RememberMeAuthenticator`, this PR adds an addition check to `AbstractPreAuthenticatedAuthenticator` to solve this issue.
https://github.com/symfony/symfony/blob/07a891f6c57d9da513d75402f2aa2da73d897044/src/Symfony/Component/Security/Http/Authenticator/RememberMeAuthenticator.php#L63

### CODE REVIEW

**Comment by wouterj** [comment]
This looks like a correct change, although I'm wondering if we should apply this always (i.e. never check if authenticators support the request if there already is a token) instead of letting the authenticator decide. But I'm not sure if this would be the correct fix (happy to hear other ideas on this topic).

Is it possible for you to add a test for this behavior? (e.g. in the `RemoteUserAuthenticatorTest`)

**Comment by stlrnz** [comment]
> Is it possible for you to add a test for this behavior? (e.g. in the `RemoteUserAuthenticatorTest`)

I've done that. The test is inspired by `RememberMeAuthenticatorTest`.
https://github.com/symfony/symfony/blob/07a891f6c57d9da513d75402f2aa2da73d897044/src/Symfony/Component/Security/Http/Tests/Authenticator/RememberMeAuthenticatorTest.php#L39


> This looks like a correct change, although I'm wondering if we should apply this always (i.e. never check if authenticators support the request if there already is a token) instead of letting the authenticator decide. But I'm not sure if this would be the correct fix (happy to hear other ideas on this topic).

I think this is the right question to ask. Looking at `HttpBasicAuthenticator` I assume there is the same check missing.
https://github.com/symfony/symfony/blob/07a891f6c57d9da513d75402f2aa2da73d897044/src/Symfony/Component/Security/Http/Authenticator/HttpBasicAuthenticator.php#L57

It's easy to forget that scenario when writing an Authenticator. In my opinion the Authenticator is _lying_ when returning false for the question "do you support this request?". It _can_ support/authenticate this request, but we dont _want_ it to do.
So for me it would be a better solution to check for the token on a more centralized position. But I dont know if there is any scenario where this would be wrong. The current solution is more flexible.

**Comment by Nyholm** [comment]
Thank you for the PR issue and the reproducer. Great job!

Im also hesitant that this is the correct fix. But Im not sure what else is. Im wondering what a system like kerberos would do on logout and if the user changes without logging out first. Then this fix will break applications (depending on kerberos or others behavior). 

Im not sure who would like to read this but one can do a workaround by creating your own RemoteUserAuthentication and override the `supports` method. See here for more info: https://symfony.com/doc/current/security/custom_authenticator.html

**Comment by stlrnz** [comment]
Thank you for the feedback, @Nyholm!

> Im wondering what a system like kerberos would do on logout and if the user changes without logging out first.

That's a really good question. In our environment, this cannot happen. But I mocked this scenario in my demo application and found a flaw in the original PR. So I pushed an updated version which checks for the user identifier before making a decision.
Now the new firewall does the same as the old: if the user changes, the new user is logged in.

But this implementation does not invalidate the session of the first user. In consequence the second user may have access to sensible data and/or the application will break anyway.
However, I checked this scenario using the old firewall, too. The same thing is happening here. So this PR neither worsen nor improved that special case. But since this never seemed to be an issue, I dont know how critical it really is.


> I'm wondering if we should apply this always (i.e. never check if authenticators support the request if there already is a token) instead of letting the authenticator decide

I think this is still a really good idea, @wouterj! It may solve the problem with the session, too?
But this would be a more dangerous change. Maybe we should separate that discussion from this PR?

File: src/Symfony/Component/Security/Http/Authenticator/AbstractPreAuthenticatedAuthenticator.php [hunk 1]
```diff
@@ -79,6 +79,17 @@ public function supports(Request $request): ?bool
             return false;
         }
 
+        // do not overwrite already stored tokens from the same user (i.e. from the session)
+        $token = $this->tokenStorage->getToken();
+
+        if (null !== $token && $token->getUserIdentifier() === $username) {
```
Comment (wouterj) [inline src/Symfony/Component/Security/Http/Authenticator/AbstractPreAuthenticatedAuthenticator.php]: What about reproducing the check in the legacy security system exactly?

https://github.com/symfony/symfony/blob/c143be5b2c8c91e139abfd086f482cea18c0c896/src/Symfony/Component/Security/Http/Firewall/AbstractPreAuthenticatedListener.php#L89-L94

```suggestion
        if ($token instanceof PreAuthenticatedToken && $this->firewallName === $token->getFirewallName() && $token->getUserIdentifier() === $username) {
```

**Review by wouterj — APPROVED** [review]
Thank you for working on this!

I've created a minimal app and checked your findings. The legacy security system indeed did not load the user if the token contained the same user (checked by username and firewall name).

If we add the precise checks of the old system, let's merge this :+1: . We can always improve things as a feature in an upcoming version.

File: src/Symfony/Component/Security/Http/Authenticator/AbstractPreAuthenticatedAuthenticator.php (hunk 1 above)
Comment (stlrnz) [reply src/Symfony/Component/Security/Http/Authenticator/AbstractPreAuthenticatedAuthenticator.php]: Yes, this looks more solid. I can confirm that using this check the Authenticator still works as expected.

**Review by Nyholm — APPROVED** [review]
Thank you @stlrnz and @wouterj

**Comment by nicolas-grekas** [comment]
Thank you @stlrnz.
