### PR TITLE
[Config] Fix merging node that canBeDisable()/canBeEnabled()

### LINKED ISSUE #62945: [Config] canBeDisabled() and canBeEnabled() overwrite enabled value if not set for merged configuration
### Symfony version(s) affected

7.4, 8.0

### Description

When merging multiple configurations, the `enabled` state is constantly overwritten when it wasn't set for a configuration. This happens since #62123, the `beforeNormalization()` ensures the `enabled` value is always set (for this set, as it's nor merged yet).

When I remove 

```php
->beforeNormalization()
                ->ifArray()
                ->then(static function ($v) {
                    $v['enabled'] ??= false;

                    return $v;
                })
            ->end()
```

Everything works as expected again.

### How to reproduce

Create a configuration class with an enable configuration, and use multiple configurations.

```yaml
# file1 loaded first

framework:
    session:
        enabled: true
```

```yaml
# file 2, loaded second

framework:
    session:
        storage_factory_id: session.storage.factory.mock_file
```

The final state should be:

```yaml
framework:

    session:
        enabled: true
        storage_factory_id: session.storage.factory.mock_file
```

But instead it's:

```yaml
framework:

    session:
        enabled: false # The second file didn't specify this configuration, so the `beforeNormalization()` part added it. making it look like the config was provided explicitly
        storage_factory_id: session.storage.factory.mock_file
```

Even when the ad-hock value is changed (to null or false), this will still not produce the expected result as the last value will always overwrite any previous one.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62945
| License       | MIT

This issue was brought by #62123

### CODE REVIEW

**Comment by sstok** [comment]
I can confirm this works, no other failures on my side. Thanks.

Status: Reviewed

File: src/Symfony/Component/Config/Definition/Builder/ArrayNodeDefinition.php [hunk 1]
```diff
@@ -370,7 +362,7 @@ public function canBeEnabled(/* ?string $info = null */): static
             $disabledNode->info($info);
         }
 
-        return $this;
+        return $this->attribute('auto_enable', true);
```
Comment (stof) [inline src/Symfony/Component/Config/Definition/Builder/ArrayNodeDefinition.php]: I would put the `attribute ` call in the existing chain on configuration calls instead of putting it on the return statement for the fluent API.

Comment (nicolas-grekas) [reply src/Symfony/Component/Config/Definition/Builder/ArrayNodeDefinition.php]: updated!
