### PR TITLE
[DI] Fix Preloader exception when preloading a class with an unknown parent/interface

### LINKED ISSUE #38693: Opcache fails because of uncaught Preloader exception
**Symfony version(s) affected**: 5.1.7

**Description**  
I couldn't manage to get opcache working for a small application that uses api-platform. The only thing that I got was php exiting with error code 70.

After some digging I found the following:
Preloader catches \ReflectionException, but in some cases a parent exception can be thrown.
https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/DependencyInjection/Dumper/Preloader.php#L109-L111

I added a `catch (\Throwable $e) { var_dump($e) }` and got the following when trying to load `Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener`:
```
object(Error)#19 (7) {
  ["message":protected]=>
  string(94) "Interface 'Symfony\Component\ExpressionLanguage\ExpressionFunctionProviderInterface' not found"
  ["string":"Error":private]=>
  string(0) ""
  ["code":protected]=>
  int(0)
  ["file":protected]=>
  string(78) "/app/vendor/symfony/security-core/Authorization/ExpressionLanguageProvider.php"
  ["line":protected]=>
  int(22)
```

Stacktrace:
```
#0 /app/vendor/composer/ClassLoader.php(444): include()
#1 /app/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/app/vendor/com...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#3 [internal function]: spl_autoload_call('Symfony\\Compone...')
#4 /app/vendor/symfony/security-core/Authorization/ExpressionLanguage.php(18): class_exists('Symfony\\Compone...')
#5 /app/vendor/composer/ClassLoader.php(444): include('/app/vendor/sym...')
#6 /app/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/app/vendor/com...')
#7 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#8 /app/vendor/sensio/framework-extra-bundle/src/Security/ExpressionLanguage.php(21): spl_autoload_call('Symfony\\Compone...')
#9 /app/vendor/composer/ClassLoader.php(444): include('/app/vendor/sen...')
#10 /app/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/app/vendor/com...')
#11 [internal function]: Composer\Autoload\ClassLoader->loadClass('Sensio\\Bundle\\F...')
#12 [internal function]: spl_autoload_call('Sensio\\Bundle\\F...')
#13 /app/vendor/symfony/dependency-injection/Dumper/Preloader.php(84): ReflectionClass->__construct('Sensio\\Bundle\\F...')
#14 /app/vendor/symfony/dependency-injection/Dumper/Preloader.php(128): Symfony\Component\DependencyInjection\Dumper\Preloader::doPreload('Sensio\\Bundle\\F...', Array)
#15 /app/vendor/symfony/dependency-injection/Dumper/Preloader.php(109): Symfony\Component\DependencyInjection\Dumper\Preloader::preloadType(Object(ReflectionNamedType), Array)
#16 /app/vendor/symfony/dependency-injection/Dumper/Preloader.php(65): Symfony\Component\DependencyInjection\Dumper\Preloader::doPreload('Sensio\\Bundle\\F...', Array)
#17 /app/var/cache/prod/App_KernelProdContainer.preload.php(389): Symfony\Component\DependencyInjection\Dumper\Preloader::preload(Array)
#18 /app/config/preload.php(4): require('/app/var/cache/...')
#19 {main}"
```

debug_print_backtrace:
```
#0  Symfony\Component\DependencyInjection\Dumper\Preloader::doPreload(Sensio\Bundle\FrameworkExtraBundle\Security\ExpressionLanguage, Array ([Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener] => 1,[Sensio\Bundle\FrameworkExtraBundle\Request\ArgumentNameConverter] => 1,[Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadataFactoryInterface] => 1,[Symfony\Component\HttpKernel\Event\ControllerArgumentsEvent] => 1,[Symfony\Component\HttpKernel\HttpKernelInterface] => 1,[Symfony\Component\HttpFoundation\Request] => 1,[Symfony\Component\HttpFoundation\Session\SessionInterface] => 1,[Symfony\Component\HttpFoundation\Session\SessionBagInterface] => 1,[Sensio\Bundle\FrameworkExtraBundle\Security\ExpressionLanguage] => 1)) called at [/app/vendor/symfony/dependency-injection/Dumper/Preloader.php:128]
#1  Symfony\Component\DependencyInjection\Dumper\Preloader::preloadType(ReflectionNamedType Object (), Array ([Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener] => 1,[Sensio\Bundle\FrameworkExtraBundle\Request\ArgumentNameConverter] => 1,[Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadataFactoryInterface] => 1,[Symfony\Component\HttpKernel\Event\ControllerArgumentsEvent] => 1,[Symfony\Component\HttpKernel\HttpKernelInterface] => 1,[Symfony\Component\HttpFoundation\Request] => 1,[Symfony\Component\HttpFoundation\Session\SessionInterface] => 1,[Symfony\Component\HttpFoundation\Session\SessionBagInterface] => 1,[Sensio\Bundle\FrameworkExtraBundle\Security\ExpressionLanguage] => 1)) called at [/app/vendor/symfony/dependency-injection/Dumper/Preloader.php:109]
#2  Symfony\Component\DependencyInjection\Dumper\Preloader::doPreload(Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener, Array ([Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener] => 1,[Sensio\Bundle\FrameworkExtraBundle\Request\ArgumentNameConverter] => 1,[Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadataFactoryInterface] => 1,[Symfony\Component\HttpKernel\Event\ControllerArgumentsEvent] => 1,[Symfony\Component\HttpKernel\HttpKernelInterface] => 1,[Symfony\Component\HttpFoundation\Request] => 1,[Symfony\Component\HttpFoundation\Session\SessionInterface] => 1,[Symfony\Component\HttpFoundation\Session\SessionBagInterface] => 1,[Sensio\Bundle\FrameworkExtraBundle\Security\ExpressionLanguage] => 1)) called at [/app/vendor/symfony/dependency-injection/Dumper/Preloader.php:65]
#3  Symfony\Component\DependencyInjection\Dumper\Preloader::preload(Array ([0] => Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener)) called at [/app/var/cache/prod/App_KernelProdContainer.preload.php:389]
#4  require(/app/var/cache/prod/App_KernelProdContainer.preload.php) called at [/app/config/preload.php:4]
```

**Possible Solution**  
Change `catch (\ReflectionException $e)` to `catch (\Throwable $e)`

### PR DESCRIPTION
**Pull request by rgeraads**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38693
| License       | MIT

Fixes Preloader exception when preloading a class with an unknown parent/interface.

### CODE REVIEW

**Comment by derrabus** [comment]
Did you check if this problem exists on 4.4 as well? If yes, we need to fix it there.

**Comment by rgeraads** [comment]
@derrabus looks like it! https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/DependencyInjection/Dumper/Preloader.php#L90-L92

File: src/Symfony/Component/DependencyInjection/Tests/Dumper/PreloaderTest.php [hunk 1]
```diff
@@ -27,8 +27,11 @@ public function testPreload()
         $preloaded = [];
 
         $r->invokeArgs(null, ['Symfony\Component\DependencyInjection\Tests\Fixtures\Preload\Dummy', &$preloaded]);
-
         self::assertTrue(class_exists('Symfony\Component\DependencyInjection\Tests\Fixtures\Preload\Dummy', false));
+
+        $r->invokeArgs(null, ['Symfony\Component\DependencyInjection\Tests\Fixtures\Preload\DummyWithInterface', &$preloaded]);
+        self::assertFalse(class_exists('Symfony\Component\DependencyInjection\Tests\Fixtures\Preload\DummyWithInterface', false));
+
```
Comment (derrabus) [inline src/Symfony/Component/DependencyInjection/Tests/Dumper/PreloaderTest.php]: I'd create a separate test for this case instead of merging it into the two existing tests.

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/Preload/DummyWithInterface.php [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+        return null;
+    }
+
+    public function noTypes($foo)
+    {
+    }
+
+    public function builtinTypes(int $foo): ?string
+    {
+    }
```
Comment (derrabus) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/Preload/DummyWithInterface.php]:
```suggestion
```

This is just noise. What we want to assert is that the preloader does not choke on the missing `NonExistentDummyInterface`, so we don't need the rest of the class body.

**Review by derrabus — CHANGES_REQUESTED** [review]
The change looks correct to me. Just some remarks on the test setup.

**Comment by derrabus** [comment]
> @derrabus looks like it!

Can you rebase your changes on 4.4 then? If not, that's okay as well. I can do that while merging.

**Comment by derrabus** [comment]
Oh, and thank you very much for your PR, of course. 😃

**Comment by rgeraads** [comment]
> Can you rebase your changes on 4.4 then? If not, that's okay as well. I can do that while merging.

I rebased it now. Will you port the fix to 5.1 then?

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
> Will you port the fix to 5.1 then?

The branches are merged periodically. Changes merged to the 4.4 branch will also be shipped with the next 5.1 release.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @rgeraads.
