### PR TITLE
[Workflow] Fixed case when the marking store is not defined

### LINKED ISSUE #39242: [Workflow, bug] After Upgrade to Symfony 5.2, omitting marking_store.type leads to an error message
**Symfony version(s) affected**: 5.2.0

**Description**  
After upgrading my application to Symfony 5.2.0, I got an error when clearing the cache or calling `php bin/console debug:autowiring workflow`:

> Argument 2 of service "state_machine.abstract" is abstract: marking store.

I have a single (and very simple) workflow:

````
framework:
    workflows:
        report_monthly:
            type: state_machine
            marking_store: ~
            supports:
                - App\Entity\MyWorkflowedEntityWithAMarkingProperty
            initial_marking: my_initial_marking
            places:
                - my_initial_marking
                - another_marking
            transitions:
                finalize_data:
                    from:  my_initial_marking
                    to:    another_marking
````

When I configure the `marking_store.type` explicitly to its only valid value 'method', the error messages disappears. This stands in contrast to the documentation https://symfony.com/doc/current/workflow.html :

> The marking_store.type (the default value depends on the type value) and property (default value ['marking']) attributes of the marking_store option are optional. If omitted, their default values will be used. It’s highly recommended to use the default value.

**How to reproduce**  
Configure a workflow of type `state_machine` without setting `marking_store` type explicitly.

**Possible Solution**  
Besides configuring the `marking_store.type` explicitly, adding a default value to `marking_store.type` in `symfony/framework-bundle/DependencyInjection/Configuration.php` also solves the problem (at least for cases, where `marking_store` is set to `~` as in the example, cases where `marking_store` isn't set at all still don't work):

````
->arrayNode('marking_store')
    ->children()
        ->enumNode('type')
            ->values(['method'])
            ->defaultValue('method') // added a default value
        ->end()
        ->scalarNode('property')
            ->defaultValue('marking')
        ->end()
        ->scalarNode('service')
            ->cannotBeEmpty()
        ->end()
    ->end()
->end()
````

**Additional context**  
Note: This code hasn't changed from Symfony 5.1 to 5.2, so the problem causing the error must be at another point.

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39242
| License       | MIT
| Doc PR        |

---

Since we are using `abstract_arg()` in the [service definition](https://github.com/symfony/symfony/blob/v5.2.0/src/Symfony/Bundle/FrameworkBundle/Resources/config/workflow.php#L25) (where we used `null` before), and since there is a validation mechanism that ensure all abstract arg are resolved, the container compilation failed. 
But if the marking store is not defined (which is legit), we want to fallback on the raw PHP implementation.
That's why, now, I replace the abstract arg by null, and everything seems OK

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -812,6 +812,8 @@ private function registerWorkflowConfiguration(array $config, ContainerBuilder $
             $workflowDefinition->replaceArgument(0, new Reference(sprintf('%s.definition', $workflowId)));
             if (isset($markingStoreDefinition)) {
                 $workflowDefinition->replaceArgument(1, $markingStoreDefinition);
+            } else {
+                $workflowDefinition->replaceArgument(1, null);
             }
```
Comment (derrabus) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]:
```suggestion
            $workflowDefinition->replaceArgument(1, $markingStoreDefinition ?? null);
```

**Review by jderusse — APPROVED** [review]

**Comment by xabbuh** [comment]
Can we add a test case?

**Comment by lyrixx** [comment]
@xabbuh done
