### PR TITLE
[Cache] Add support for using DSN with `PDOAdapter`

### LINKED ISSUE #52460: [Cache] Using DSN with PDOAdapter
### Symfony version(s) affected

`>=5.4`

### Description

According to [the docs](https://symfony.com/doc/5.4/cache.html) it should be possible to use DSN to configure the PDOAdapter, how an exception is thrown instead:

```
  Unsupported DSN: it does not start with "redis[s]:", "memcached:" nor "couchbase:".
```

This happens because the `AbstractAdapter::createConnection()` supports only certain adapters:

https://github.com/symfony/symfony/blob/58353d12dabe6c5aba30866f8e693d1ce0949126/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php#L127-L144

I'm not sure if this is a bug in the documentation (and possible new feature) or a bug in the code.

### How to reproduce

```yaml
framework:
  cache:
    pools:
      my.cache:
        adapter: cache.adapter.pdo
        provider: "pgsql:host=localhost;port=5432;dbname=postgres;user=postgres;password=pass"
```

```php
#[AsCommand('app:test')]
class TestCommand extends Command
{
    public function __construct(
        #[Autowire(service: 'my.cache')] private CacheInterface $cache,
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        return Command::SUCCESS;
    }
}
```

### Possible Solution

Add the necessary logic to `AbstractAdapter::createConnection()`.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #52460
| License       | MIT

Adds support for using DSN with the `PDOAdapter`:

```yaml
framework:
  cache:
    pools:
      my.cache:
        adapter: cache.adapter.pdo
        provider: "pgsql:host=localhost;port=5432;dbname=postgres;user=postgres;password=pass"
```

### CODE REVIEW

File: src/Symfony/Component/Cache/Adapter/PdoAdapter.php [hunk 1]
```diff
@@ -89,6 +89,18 @@ public function __construct(#[\SensitiveParameter] \PDO|string $connOrDsn, strin
         parent::__construct($namespace, $defaultLifetime);
     }
 
+    public static function createConnection(#[\SensitiveParameter] string $dsn, array $options = []): \PDO|string
+    {
+        if ($options['lazy'] ?? false) {
+            return $dsn;
```
Comment (HypeMC) [inline src/Symfony/Component/Cache/Adapter/PdoAdapter.php:95]: I think it makes the most sense to just return the DSN when `lazy` is `true` since the adapter itself supports this and creates the connection lazily.

File: src/Symfony/Component/Cache/Adapter/AbstractAdapter.php [hunk 2]
```diff
@@ -124,8 +124,17 @@ public static function createConnection(#[\SensitiveParameter] string $dsn, arra
 
             return CouchbaseCollectionAdapter::createConnection($dsn, $options);
         }
+        if (
+            str_starts_with($dsn, 'mysql:')
```
Comment (stloyd) [inline src/Symfony/Component/Cache/Adapter/AbstractAdapter.php]: Wouldn't preg_match be faster than 5 calls?

Comment (HypeMC) [reply src/Symfony/Component/Cache/Adapter/AbstractAdapter.php]: Good idea, done

File: src/Symfony/Component/Cache/Adapter/PdoAdapter.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Cache/Adapter/PdoAdapter.php:95]: this should be the default to me

**Review by stloyd — APPROVED** [review]

File: src/Symfony/Component/Cache/Adapter/PdoAdapter.php (hunk 1 above)
Comment (HypeMC) [reply src/Symfony/Component/Cache/Adapter/PdoAdapter.php:95]: Done

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @HypeMC.
