### PR TITLE
[Form] Ignoring invalid forms from delete_empty behavior in CollectionType

### LINKED ISSUE #37660: [Form] collection of choices with delete_empty ignores invalid items
**Symfony version(s) affected**: 4.4.10+, 5.2.3

**Description**  
When submitting invalid data to a form for a collection of choices, there's no error if the `delete_empty` option is enabled.

**How to reproduce**  

First, run `composer require symfony/form`
Then, execute this file:

```php
<?php
require __DIR__.'/vendor/autoload.php';
use Symfony\Component\Form\Forms;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

$name = 'items';
$choices = [
    'foo',
    'bar',
    'qux',
];
$form = Forms::createFormFactory()->createBuilder()
    ->add($name, CollectionType::class, [
        'allow_add' => true,
        'delete_empty' => true, // *** THIS LINE
        'entry_type' => ChoiceType::class,
        'entry_options' => [
            'choices' => array_combine($choices, $choices),
        ],
    ])
    ->getForm();

$form->submit([
    $name => [
        'foo',
        'x', // *** INVALID
        'qux',
        '', // empty
    ],
]);

echo preg_replace('/( => )\n +/', '$1', var_export($form->getData(), true)), "\n";
var_dump($form->isValid());
echo $form->getErrors(true, false);
```

Output:

```
array (
  'items' => array (
    0 => 'foo',
    2 => 'qux',
  ),
)
bool(true)
```

i.e. the invalid item isn't there in the final data (like the empty one), the form says it's valid, no errors.

(Precision: I'm not sure about the fact that the invalid item is "missing", but I would have expected a form error.)

To compare, if I disable/remove the `delete_empty` option, then the output is:

```
array (
  'items' => array (
    0 => 'foo',
    2 => 'qux',
    3 => NULL,
  ),
)
bool(false)
items:
    1:
        ERROR: This value is not valid.
```

i.e. the invalid item is still not there (unlike the empty one now), but the form says it's not valid, with an error.

### PR DESCRIPTION
**Pull request by yceruto**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37660
| License       | MIT
| Doc PR        | -

As expained on linked issue, empty forms cannot be removed if they are invalid upon submitting (e.g. transformation failures). Thus, form errors can be displayed properly to the end user.

### CODE REVIEW

File: src/Symfony/Component/Form/Tests/Extension/Core/EventListener/ResizeFormListenerTest.php [hunk 1]
```diff
@@ -255,7 +255,7 @@ public function testOnSubmitDeleteEmptyNotCompoundEntriesIfAllowDelete()
 
         $data = [0 => 'first', 1 => ''];
         foreach ($data as $child => $dat) {
-            $this->form->get($child)->setData($dat);
+            $this->form->get($child)->submit($dat);
```
Comment (yceruto) [inline src/Symfony/Component/Form/Tests/Extension/Core/EventListener/ResizeFormListenerTest.php:258]: this change (and the next below in this file) are related to `$child->isValid()` check inside `onSubmit()` method. It's expected anyway.

Comment (xabbuh) [reply src/Symfony/Component/Form/Tests/Extension/Core/EventListener/ResizeFormListenerTest.php:258]: Wouldn't it make more sense if we called `submit()` on `$this->form` instead?

Comment (yceruto) [reply src/Symfony/Component/Form/Tests/Extension/Core/EventListener/ResizeFormListenerTest.php:258]: Normally yes, but we can't in this test case because this exception "You cannot remove children from a submitted form." when calling to `$listener->onSubmit($event)` (some lines below).

Comment (xabbuh) [reply src/Symfony/Component/Form/Tests/Extension/Core/EventListener/ResizeFormListenerTest.php:258]: We could remove the `onSubmit()` call as it will be called implicitly when `submit()` is called, isn't it?

Comment (yceruto) [reply src/Symfony/Component/Form/Tests/Extension/Core/EventListener/ResizeFormListenerTest.php:258]: It won't be called, it's not the CollectionType form test.

Comment (yceruto) [reply src/Symfony/Component/Form/Tests/Extension/Core/EventListener/ResizeFormListenerTest.php:258]: This test case is simulating only the usage of the ResizeFormListener::onSubmit() on any compound form submittion.

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @yceruto.
