### PR TITLE
[Form][TwigBridge] Prevent cached block prefixes from leaking across nested collections

### LINKED ISSUE #59962: [Form] Wrong block prefix used in nested collections
### Symfony version(s) affected

7.1.3, 7.2.4

### Description

Provided that you have nested collections in a form,
and if the parent `FormType` have changed the `getParent` method,
all childs are using the parent `block_prefix` even though it is not applicable.

I have noted `7.1.3` and `7.2.4`, because I had the issue on a `7.1.3`, and reproduced on `7.2.4`, but it may appear in more versions.

### How to reproduce

I created a reproducer project
https://github.com/yann-eugone/symfony-nested-collection-block-prefixes

It is based on an example taken from the documentation
https://symfony.com/doc/current/form/form_themes.html#fragment-naming-for-collections

There is a `TaskManagerType` that has a `CollectionType<TaskListType>` in a `taskLists` field.
There is a `TaskListType` that has a `CollectionType<TaskType>` in a `tasks` field.
And finally a `TaskType` that has a `StringType` in a `name` field.

The `TaskListType` has overriden the `getParent` method, and set it to `EmbeddedType` (an other, empty form type created for the project)

The problem occurs when you try to customize the rendering of `EmbeddedType`.
The block `embedded_row` seems to be applied to all children, even though the `embedded` prefix is not part of the `block_prefixes` list.

Image

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59962
| License       | MIT

Cache entries now track whether they originate from real template blocks or from a fallback lookup so only safe entries are propagated between FormViews; this prevents parent-specific blocks (like embedded_row) from leaking into nested collections and other views with different prefix hierarchies.

### CODE REVIEW

**Review by yceruto — APPROVED** [review]

File: src/Symfony/Bridge/Twig/Tests/Form/TwigRendererEngineTest.php [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+
+        $engine = new TwigRendererEngine(['form_layout.html.twig'], $twig);
+
+        return new FormRenderer($engine);
+    }
+}
+
+class TaskManagerType extends AbstractType
+{
+    public function buildForm(FormBuilderInterface $builder, array $options)
```
Comment (xabbuh) [inline src/Symfony/Bridge/Twig/Tests/Form/TwigRendererEngineTest.php]:
```suggestion
    public function buildForm(FormBuilderInterface $builder, array $options): void
```

to satisfy the job running with patched return types (and there’s other places needing the same)

Comment (nicolas-grekas) [reply src/Symfony/Bridge/Twig/Tests/Form/TwigRendererEngineTest.php]: fixed thanks
