### PR TITLE
[Messenger] Avoid skipping batch handlers on flush

### LINKED ISSUE #59958: [Messenger] Messages stuck in unack state in the queue when 2 batch handlers are involved
### Symfony version(s) affected

6.4.18

### Description

When dispatching messages for more than 1 batch handler, messages get stuck in the queue, not being acknowledged.

Possibly related to https://github.com/symfony/symfony/pull/58433

### How to reproduce

```yaml
framework:
    messenger:
        routing:
            'App\Message\Command\FirstCommand': main_normal_priority
            'App\Message\Command\SecondCommand': main_normal_priority
```

First handler:
```php
#[AsMessageHandler(bus: 'command.bus')]
class FirstCommandHandler implements BatchHandlerInterface
{
    use BatchHandlerTrait;
    private LoggerInterface $logger;

    public function __construct(
        ?LoggerInterface $logger = null,
    ) {
        $this->logger = $logger ?: new NullLogger();
    }

    public function __invoke(FirstCommand $message, ?Acknowledger $ack = null)
    {
        return $this->handle($message, $ack);
    }

    protected function process(array $jobs): void
    {
        foreach ($jobs as [$message, $ack]) {
            try {
                $this->logger->info('First handler');
                $ack->ack($message);
            } catch (\Throwable $e) {
                $ack->nack($e);
            }
        }
    }
}
```

Second handler:
```php
#[AsMessageHandler(bus: 'command.bus')]
class SecondCommandHandler implements BatchHandlerInterface
{
    use BatchHandlerTrait;
    private LoggerInterface $logger;

    public function __construct(
        ?LoggerInterface $logger = null,
    ) {
        $this->logger = $logger ?: new NullLogger();
    }

    public function __invoke(SecondCommand $message, ?Acknowledger $ack = null)
    {
        return $this->handle($message, $ack);
    }

    protected function process(array $jobs): void
    {
        foreach ($jobs as [$message, $ack]) {
            try {
                $this->logger->info('Second handler');

                $ack->ack($message);
            } catch (\Throwable $e) {
                $ack->nack($e);
            }
        }
    }
}
```

Dispatch a message for each handler:
```php
        $this->commandBus->dispatch(new FirstCommand());
        $this->commandBus->dispatch(new SecondCommand());
```

Resulting output from consumer:
```
15:01:30 INFO      [messenger] Received message App\Message\Command\FirstCommand ["class" => "App\Message\Command\FirstCommand"]
15:01:30 INFO      [messenger] Message App\Message\Command\FirstCommand handled by App\MessageHandler\Command\FirstCommandHandler::__invoke ["class" => "App\Message\Command\FirstCommand","handler" => "App\MessageHandler\Command\FirstCommandHandler::__invoke"]
15:01:30 INFO      [messenger] Received message App\Message\Command\SecondCommand ["class" => "App\Message\Command\SecondCommand"]
15:01:30 INFO      [messenger] Message App\Message\Command\SecondCommand handled by App\MessageHandler\Command\SecondCommandHandler::__invoke ["class" => "App\Message\Command\SecondCommand","handler" => "App\MessageHandler\Command\SecondCommandHandler::__invoke"]
15:01:30 INFO      [messenger] Received message App\Message\Command\FirstCommand ["class" => "App\Message\Command\FirstCommand"]
15:01:30 INFO      [app] First handler
15:01:30 INFO      [messenger] App\Message\Command\FirstCommand was handled successfully (acknowledging to transport). ["class" => "App\Message\Command\FirstCommand"]
```

Message for the Second handler is now stuck in the queue in an Unacked state.

Restarting the consumer now would consume it:
```
15:15:52 WARNING   [messenger] Error thrown while handling message App\Message\Command\SecondCommand. Sending for retry #1 using 1000 ms delay. Error: "Redelivered message from AMQP detected that will be rejected and trigger the retry logic." ["class" => "App\Message\Command\SecondCommand","retryCount" => 1,"delay" => 1000,"error" => "Redelivered message from AMQP detected that will be rejected and trigger the retry logic.","exception" => Symfony\Component\Messenger\Exception\RejectRedeliveredMessageException^ { …}]
15:15:53 INFO      [messenger] Received message App\Message\Command\SecondCommand ["class" => "App\Message\Command\SecondCommand"]
15:15:53 INFO      [messenger] Message App\Message\Command\SecondCommand handled by App\MessageHandler\Command\SecondCommandHandler::__invoke ["class" => "App\Message\Command\SecondCommand","handler" => "App\MessageHandler\Command\SecondCommandHandler::__invoke"]
15:15:53 INFO      [messenger] Received message App\Message\Command\SecondCommand ["class" => "App\Message\Command\SecondCommand"]
15:15:53 INFO      [app] Second handler
15:15:53 INFO      [messenger] App\Message\Command\SecondCommand was handled successfully (acknowledging to transport). ["class" => "App\Message\Command\SecondCommand"]
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ehoutsma**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59958
| License       | MIT

When using multiple Batch handlers, the situation can occur that there are multiple batch handlers that have messages that aren't processed and therefor not acked yet. The issue is caused by a optimalization that unsets the current batch handler in a foreach loop.

"The acknowledger was not called by the ... batch handler." is thrown when a worker is stopped and the batch isn't handled. 

The issue is reproducable and testable with the attached unit test.

### CODE REVIEW

File: src/Symfony/Component/Messenger/Worker.php [hunk 1]
```diff
@@ -254,15 +254,17 @@ private function flush(bool $force): bool
...
             [$envelope, $transportName] = $unacks[$batchHandler];
             try {
                 $this->bus->dispatch($envelope->with(new FlushBatchHandlersStamp($force)));
                 $envelope = $envelope->withoutAll(NoAutoAckStamp::class);
-                unset($unacks[$batchHandler], $batchHandler);
             } catch (\Throwable $e) {
                 $this->acks[] = [$transportName, $envelope, $e];
             }
+            $unacks->next();
+            $unacks->detach($batchHandler);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Worker.php]: This means that we now don't call the destructor of the $batchHandler (if any) inside the try/catch.
Is that the fix or a regression?

Comment (ehoutsma) [reply src/Symfony/Component/Messenger/Worker.php]: Thank you for your review.

The fix is that we unset the batchHandler after we set the iterator to the next batchHandler. Before it would unset the current batchHandler, and then tries to proceed to the next batchHandler but can't find the current index because it was unset.

See this comment: https://www.php.net/manual/en/splobjectstorage.detach.php#97644

Catching a Throwable of the unset, has nothing to do with the handling of the batch.

Comment (ehoutsma) [reply src/Symfony/Component/Messenger/Worker.php]: @nicolas-grekas Do you have enough information to accept this PR or do you need more information. It would help us a lot if this bug is fixed.

**Comment by rairlie** [comment]
I've also encountered this issue, and use a similar fix locally.

As @ehoutsma says, the problem is simply that `$unacks` is modified within the loop, messing up the iteration:
```php
foreach ($unacks as $batchHandler) {
    ...
    try {
        ...
        unset($unacks[$batchHandler], $batchHandler); // <<-- $unacks modified while being iterated
    } catch (\Throwable $e) {
        ...
    }
}
```

Working example:
```php
$handler1 = new stdClass();
$handler1->val = 1;

$handler2 = new stdClass();
$handler2->val = 2;

$unacks = new SplObjectStorage();
$unacks->attach($handler1);
$unacks->attach($handler2);

foreach ($unacks as $handler) {
    var_dump($handler);
    unset($unacks[$handler]);
}
```

Results in only one handler being processed:
```
object(stdClass)#1 (1) {
  ["val"]=>
  int(1)
}
```

**Comment by ehoutsma** [comment]
I understand this issue doesn't occur with a lot of users. Leaving this issue unsolved, makes the use of batchhandling with multiple batchhandlers on the same queue unreliable.

@nicolas-grekas, Is it possible to merge this issue, since this is an issue that is still available even in version 7 of symfony?

**Comment by wazum** [comment]
I've analyzed this issue and while this PR fixes the bug, there might be a simpler solution (it looks like the code changed too in the meantime).

Since `$this->unacks` is replaced with a new `SplObjectStorage` at the beginning of the method, the local `$unacks` variable becomes the only reference to the old storage. Once the method completes, this storage will be garbage collected.

Therefore, we could simply remove the problematic `unset()` line entirely (only change necessary):

```diff
diff --git a/src/Symfony/Component/Messenger/Worker.php b/src/Symfony/Component/Messenger/Worker.php
index 68510c33b3..1a282dabf6 100644
--- a/src/Symfony/Component/Messenger/Worker.php
+++ b/src/Symfony/Component/Messenger/Worker.php
@@ -258,7 +258,6 @@ class Worker
             try {
                 $this->bus->dispatch($envelope->with(new FlushBatchHandlersStamp($force)));
                 $envelope = $envelope->withoutAll(NoAutoAckStamp::class);
-                unset($unacks[$batchHandler], $batchHandler);
             } catch (\Throwable $e) {
                 $this->acks[] = [$transportName, $envelope, $e];
             }
```

This would:
- Fix the `SplObjectStorage` iteration bug
- Avoid unnecessary operations on a storage that's about to be garbage collected
- Keep the code simpler with fewer changes

The current PR's approach works but adds **unnecessary complexity** with the manual iterator management and `detach()` call.

@ehoutsma  what do you think? Would you modify your pull request?

**Comment by khaperets** [comment]
any updates?

**Comment by averatec1337** [comment]
This bug recently occured in my app, because I implemented multiple batch message handlers.

**Review by nicolas-grekas — APPROVED** [review]
I rebased a made some tweaks

**Review by HypeMC — APPROVED** [review]
Been experiencing this since #62872. I tried reproducing it locally but didn't think to test with multiple batch handlers.

Anyway, can confirm this fixes the problem, thanks 🙂

**Comment by nicolas-grekas** [comment]
Thank you @ehoutsma.
