### PR TITLE
[Serializer] Fix denormalization of nested array with key types

### LINKED ISSUE #60036: [Serializer] array<string, list<Foo>> cannot be denormalized if nested under list<Bar>
### Symfony version(s) affected

5.4, 6.x, 7.x

### Description

If array with string key but list is nested under object with a list (like in a reproducer), Denormalizer seems to skew the key from string into int, resulting into error:

```
Symfony\Component\Serializer\Exception\NotNormalizableValueException : The type of the key "something" must be "int" ("string" given).
```

### How to reproduce

Phpunit reproducer at https://github.com/symfony/symfony/compare/7.3...ostrolucky:list-nesting-reproducer?expand=1

In comment form:

```php
class Foo {
    /** @param array<string, list<\stdClass>> $operators */
    public function __construct(public array $operators = []) {}
}

class Bar {
    /** @param list<Foo> $foos */
    public function __construct(public array $foos = []) {}
}
```

```php
public function testPropertyPhpDocWithKeyTypes()
{
        $json = <<<JSON
    {
    "foos": [{"operators": {"something": [{}]}}]
    }
    JSON;
    $serializer = new Serializer([
        new ObjectNormalizer(null, null, null, new PhpDocExtractor()),
        new ArrayDenormalizer(),
    ], ['json' => new JsonEncoder()]);

    $serializer->deserialize($json, Bar::class, 'json');
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60036
| License       | MIT

The nested-array branch in `AbstractObjectNormalizer::validateAndDenormalize` did not propagate `key_type`/`value_type` into the context, unlike the non-nested branch. This caused the parent collection's `key_type` to leak into child properties.

The fix propagates these context keys in `AbstractObjectNormalizer` and advances them to the next nesting level in `ArrayDenormalizer`.

### CODE REVIEW

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 1]
```diff
@@ -554,6 +554,12 @@ private function validateAndDenormalize(array $types, string $currentClass, stri
                         // the builtinType is the inner one and the class is the class followed by []...[]
                         $builtinType = $innerType->getBuiltinType();
                         $class = $innerType->getClassName().$dimensions;
+
+                        if (\count($collectionKeyType = $type->getCollectionKeyTypes()) > 0) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: I'm doing it, but for future PRs:
```suggestion
                        if ($collectionKeyType = $type->getCollectionKeyTypes()) {
```

**Comment by nicolas-grekas** [comment]
Thank you @mtarld.
