### PR TITLE
[DependencyInjection] Add test case to ensure XML parse exception message includes filename and position

### LINKED ISSUE #61572: Add test case to ensure XML parse exceptions include filename and position
### Description

Currently, XML parse exceptions already include the filename at the beginning of the message. However, there is no automated test to ensure that the filename and position are consistently included in the exception message.

To prevent regressions, I propose adding a dedicated test in
XmlFileLoaderTest that asserts the exception message contains:

The filename (e.g., services31.xml)

The error details (This element is not expected)

The position (line X, column Y)

This would cover the case discussed in #61493.

I’d be happy to prepare a PR adding this test

### PR DESCRIPTION
**Pull request by xersion22**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #61572
| License       | MIT

## Summary

This PR adds a dedicated test to `XmlFileLoaderTest` to ensure that XML parse exceptions include the filename, error details, and position (line and column) in their messages.

## What it does and why it's needed

- Ensures error messages from XML parse exceptions always contain:
  - The XML filename (e.g., `services31.xml`)
  - The error details (e.g., "This element is not expected")
  - The position (line X, column Y)
- Prevents regressions by automatically checking this behavior in tests
- Improves consistency and debuggability of XML parsing errors

## Example

When an invalid XML file (such as `services31.xml`) is loaded, the exception message will now contain:
- The filename: `services31.xml`
- The error detail: "This element is not expected"
- The position: `line X, column Y`

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Tests/Loader/XmlFileLoaderTest.php [hunk 1]
```diff
@@ -1286,4 +1286,26 @@ public function testLoadServicesWithEnvironment()
...
+        try {
+            $loader->load($invalidXMLFileName);
+            $this->fail('Expected an InvalidArgumentException due to invalid XML.');
+        } catch (\InvalidArgumentException $e) {
+            $message = $e->getMessage();
+
+            $this->assertStringContainsString($invalidXMLFileName, $message, 'Exception message should contain the filename.');
+            $this->assertStringContainsString('This element is not expected', $message, 'Exception message should contain XML error details.');
+            $this->assertMatchesRegularExpression('/line \d+, column \d+/', $message, 'Exception message should contain line and column information.');
+        }
```
Comment (junaidbinfarooq) [inline src/Symfony/Component/DependencyInjection/Tests/Loader/XmlFileLoaderTest.php]: Instead of _try-catch_, we could use `$this->expectException`, `$this->expectExceptionMessage`, etc.

Comment (xersion22) [reply src/Symfony/Component/DependencyInjection/Tests/Loader/XmlFileLoaderTest.php]: @junaidbinfarooq 
Yes we can use expectException. Are there any issue with try catch approach ?

Comment (stof) [reply src/Symfony/Component/DependencyInjection/Tests/Loader/XmlFileLoaderTest.php]: it makes the test harder to read (and depending on what you use in the `catch` clause, it can even break the test when writing it this way, as `$this->fail()` also uses an exception).

using the dedicated PHPUnit feature to assert exceptions make the test more maintainable.

Comment (xersion22) [reply src/Symfony/Component/DependencyInjection/Tests/Loader/XmlFileLoaderTest.php]: Thanks @stof

Comment (xersion22) [reply src/Symfony/Component/DependencyInjection/Tests/Loader/XmlFileLoaderTest.php]: Done

**Comment by nicolas-grekas** [comment]
Thank you @xersion22.

File: src/Symfony/Component/DependencyInjection/Tests/Loader/XmlFileLoaderTest.php (hunk 1 above)
Comment (junaidbinfarooq) [reply src/Symfony/Component/DependencyInjection/Tests/Loader/XmlFileLoaderTest.php]: @xersion22 
Guess I have nothing to explain as the reason is well explained by @stof already :smile:
