### PR TITLE
[Form] CollectionType apply prototypeOptions to ResizeFormListener new fields

### LINKED ISSUE #49786: Symfony/form CollectionType prototype_options not applied to new fields
### Symfony version(s) affected

6.1+

### Description

The CollectionType from Symfony/form core allows setting prototype_options since 6.1. However new fields in the collection don't get the prototype_options applied. The option does exactly what it says, it applies options to the prototype and that part works well. Those prototype options won't get passed to the ResizeFormListener, which means new fields won't get the prototype_options applied.

This isn't a problem in the case mentioned in the testcase, where a help text gets applied to new fields. This doesn't change the way the field is handled, so not a problem.
But in the blog another case is mentioned where existing fields get disabled and new fields will be enabled. This allows the user to add new data, but not edit existing data. This was exactly my use case, but I found out it doesn't work. When the fields get rendered for the user, the behavior is correct, the existing fields are disabled and the new fields are enabled. But when submitting the form, the new fields aren't being applied to the data.

The reason is in the ResizeFormListener new fields get added in the preSubmit event and uses entry_options instead of prototype_options. Since disabled is set to true in entry_options, the new fields get added as being disabled and won't accept the Request data.

As an aside, the blog post is also incorrect where the disabled key is missing from the prototype_options. Since prototype_options works as an override to entry_options, all the fields would be disabled.

See
 - https://github.com/symfony/form/commit/1d88387fa4aeb497bcc8122137f9168c0a6cea76
 - https://symfony.com/blog/new-in-symfony-6-1-customizable-collection-prototypes

### How to reproduce

```
$builder->add('names', CollectionType::class, [
    'allow_add' => true,
    'entry_type'   => TextType::class,

    // this is used when editing items in the collection
    'entry_options'  => [
        'attr' => ['class' => 'item-edit'],
        'help'  => 'You cannot edit existing names.',
        'disabled' => true,
    ],

    // this is used when adding new items to the collection
    'prototype_options'  => [
        'attr' => ['class' => 'item-add'],
        'help'  => 'Check out the <a href="...">rules to create new names</a>',
        'help_html' => true,
        'disabled' => false,
    ],
]);
```

### Possible Solution

The ResizeFormListener should be passed both the entry_options as the prototype_options arrays and use the prototype_options array when adding new lines.

See: https://github.com/symfony/form/blob/6.2/Extension/Core/EventListener/ResizeFormListener.php#L99

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Thorry84**
Fixes issue 49786

| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49786
| License       | MIT

This pull request provides a fix for issue 49786.

By passing the prototypeOptions to the ResizeFormListener from the CollectionType and applying it to new fields it makes the prototypeOptions function as intended. Otherwise the use case such as in this blog aren't possible: https://symfony.com/blog/new-in-symfony-6-1-customizable-collection-prototypes

I've updated the existing ResizeFormListener tests to handle the new signature and added a new test to the CollectionType which would fail without this fix and pass with the fix.

### CODE REVIEW

File: src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php [hunk 1]
```diff
@@ -25,18 +25,20 @@
...
-    protected $options;
+    protected $entryOptions;
+    protected $prototypeOptions;
     protected $allowAdd;
     protected $allowDelete;
 
     private \Closure|bool $deleteEmpty;
 
-    public function __construct(string $type, array $options = [], bool $allowAdd = false, bool $allowDelete = false, bool|callable $deleteEmpty = false)
+    public function __construct(string $type, array $entryOptions = [], array $prototypeOptions = [], bool $allowAdd = false, bool $allowDelete = false, bool|callable $deleteEmpty = false)
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php]: the new argument should be added last in order to not break BC

**Comment by Thorry84** [comment]
Yeah good point. Fixed!

File: src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php [hunk 2]
```diff
@@ -25,19 +25,21 @@
 class ResizeFormListener implements EventSubscriberInterface
 {
     protected $type;
-    protected $options;
+    protected $entryOptions;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php]: because this is protected, its name must be kept
let's also keep the same name on the constructor argument

File: src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php [hunk 3]
```diff
@@ -25,19 +25,21 @@
...
-    public function __construct(string $type, array $options = [], bool $allowAdd = false, bool $allowDelete = false, bool|callable $deleteEmpty = false)
+    public function __construct(string $type, array $entryOptions = [], bool $allowAdd = false, bool $allowDelete = false, bool|callable $deleteEmpty = false, array $prototypeOptions = [])
     {
         $this->type = $type;
         $this->allowAdd = $allowAdd;
         $this->allowDelete = $allowDelete;
-        $this->options = $options;
+        $this->entryOptions = $entryOptions;
         $this->deleteEmpty = \is_bool($deleteEmpty) ? $deleteEmpty : $deleteEmpty(...);
+        $this->prototypeOptions = $prototypeOptions;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php]: `$this->prototypeOptions = array_replace($options, $prototypeOptions);` (and remove the array_replace below)

File: src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php (hunk 2 above)
Comment (Thorry84) [reply src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php]: You are totally correct, sorry I didn't think about that. Fixed!

File: src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php (hunk 3 above)
Comment (Thorry84) [reply src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php]: Hmmm that seems not right?

I feel like the way the CollectionType gets its prototype options is by doing the array merge on the entry options (line 30 in the CollectionType). But that isn't by definition the way the ResizeFormListener should do it as well?
I'm not sure how it was decided for the CollectionType to handle the prototype options this way. I feel like it would be just as valid to have the prototype options be completely independent of the entry options.

I think it's also important to have the way the options are used in the CollectionType and the way it's passed to the ResizeFormListener be the same. Maybe I should have prevented the double merge? That way if it is decided that behavior is to change, it's always the same for both the CollectionType and the ResizeFormListener.

What do you think?

Thanks so much for the feedback :)

Comment (nicolas-grekas) [reply src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php]: then we should fallback to $options when no prototype options are given, to preserve the current behavior:

`$this->prototypeOptions = $prototypeOptions ?? $options;`

and change the argument to `array $prototypeOptions = null`

Comment (Thorry84) [reply src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php]: Yes totally correct. I've changed the default value for the prototypeOptions and fallback to options.
I've also changed the CollectionType constructor to prevent the double merge.

Thanks so much for your help, I'm not very good at this.

**Comment by nicolas-grekas** [comment]
Thank you @Thorry84.

**Comment by AlexeyKosov** [comment]
@Thorry84 

Not sure how exactly, but this fix has crashed some functionality on my sites.
It now throws a Entity has to be managed or scheduled for removal for single computation error since entities loaded in the forms are no longer managed by ORM's Unit of Work.

It's not a bug report, just wanted to let you know it's a possible BC though.

**Comment by Thorry84** [comment]
Hmmm that's not good. I'm not sure how my changes could be a BC break.

However the previous implementation was inherently broken. As I pointed out the example given in the blog post was simply not possible. So in the past the functionality not working might have masked any issues with unmanaged entities.

As far as I can see I don't know of any way the ResizeFormListener could cause Entities to become unmanaged. I would suspect an issue with the wrong transformers being applied to the form fields?

If you have any code to share I would love to help you investigate the issue.

**Comment by AlexeyKosov** [comment]
@Thorry84 

It must have been because I used an unmanaged empty Doctrine entity as prototype data

```
        $builder->add('items', CollectionType::class, [
            'entry_type' => ItemType::class,
            'allow_add' => true,
            'by_reference' => true,
            'label' => false,
            'prototype' => true,
            'prototype_data' => new ItemEntity(),
        ]);
```

In 6.2.7, the empty detached entity was used only for prototyping. The `ResizeFormListener`'s options looked like

```
array:1 [▼
  "block_name" => "entry"
]
```

But now, in 6.2.8, the `$prototypeOptions` used instead of `$options`, looks this way:


```
array:4 [▼
  "required" => true
  "label" => "__name__label__"
  "block_name" => "entry"
  "data" => App\Entity\ItemEntity
]
```

So the blank detached entity comes into play instead of being discarded as before.

In other words - does it make sense to use prototype data for populating new collection elements rather than only for prototyping? And even if so, it has not been used until 6.2.8, which seems to be an explicit BC.

**Comment by Thorry84** [comment]
That explains the error you've been getting.

In my opinion the previous behavior where all the options were discarded was incorrect. So passing along the options to the new fields is a bug fix and not a BC break.

However the `prototype_data` field is maybe an exception to this rule. Would someone expect new fields to be populated with data?

Discussions about this in the past I've been able to find point out the data is for initialization only and not on submit. However in the past when passing `data` to `options` this would be applied to new fields, which is incorrect in my opinion. Applying the `prototype_data` would make more sense than applying `data`.

So I'm not really sure if this would be considered a BC break or a bugfix? Either case sounds valid to me.
My 2 cents is that this is a bugfix.

---

In your code, why isn't the new data handled? If there are new entries in the form, there are new entities to be persisted?

**Comment by AlexeyKosov** [comment]
> In your code, why isn't the new data handled? If there are new entries in the form, there are new entities to be persisted?

The actual entities are loaded by ID from a repository first in a preSubmit hook, and only then updated.
So there's no need to persist them, since all the entities are existing, not new. I.e. the collection is used for updating records, not adding.

> In my opinion the previous behavior where all the options were discarded was incorrect. So passing along the options to the new fields is a bug fix and not a BC break.

Ok, no problem, I just wanted you to be aware of that possible issue.
Anyway, thank you for adding new features!

**Comment by Thorry84** [comment]
Thanks for letting me know. Happy to help :)

**Comment by Thorry84** [comment]
If somebody comes across this issue from Google: It doesn't work for the use case stated in the blog and my fix didn't solve the issue fully for that use case.

The problem is, the prototype options are used for new fields, but only when creating new fields in the UI. So when you have a form, you can disable fields for existing data and have new fields available. This part now works with my fix, but whenever there is a validation error in the form, the submitted data is seen as "old" data and the fields are now disabled. This means the user can't even fix the validation errors and is in a sense soft-locked. 

So even though the fix did technically fix the functionality, the supposed use-case simply isn't possible using only this feature. YMMV

Tagging @javiereguiluz to maybe edit the blog post to point this out.
