### PR TITLE
[HttpKernel] Fix compatibility with php bridge and already started php sessions

### LINKED ISSUE #44553: "Cannot change the ID of an active session." after upgrading to 5.4
### Symfony version(s) affected

5.4.0, 5.4.1

### Description

We have a legacy application that we are slowly migrating to Symfony, which we did following this guide with good results since 5.0: https://symfony.com/doc/current/session/php_bridge.html

Since we upgraded to 5.4.0 from 5.3.*, we are observing a `Cannot change the ID of an active session.` intermitently.

### How to reproduce

I've been able to reproduce in an isolated project: https://github.com/devnix/symfony-sessions-messed-up

`master` branch is running `5.4.*` and branch `5.3` is showing how it works.

### Possible Solution

I've been able to track down the code affecting the sessions this way here: https://github.com/symfony/symfony/commit/b3e4f6657c0c47e1b5ba85e4554a3c273ee61066

https://github.com/symfony/symfony/blob/v5.4.0/src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php#L72-L87
https://github.com/symfony/symfony/blob/v5.4.0/src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php#L136-L183

Monkey patching the class without these portions of code makes it work again.

I understand that this is a neat solution for new runtimes like Roadrunner, but it's breaking compatibility with how sessions worked. Maybe the solution would be to be able to opt-in to this functionality? Should the documentation about migrating legacy applications be updated?

### Additional Context

_No response_

### LINKED ISSUE #44616: Session id/cookie keeps being generated if session is empty
### Symfony version(s) affected

5.4.1, 6.0.0, 6.0.1

### Description

When sessions are enabled, and read for example by the "app.flashes('notice')" twig extension Symfony keeps creating and deleting session cookies.

```
Call1:
Set-Cookie PHPSESSID=2dgen0hsf54p1bkoajfaigcm9e; path=/; httponly; samesite=lax

Call2:
Set-Cookie: PHPSESSID=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; HttpOnly; SameSite=lax
Set-Cookie: PHPSESSID=deleted; expires=Mon, 14-Dec-2020 13:58:11 GMT; Max-Age=0; path=/; httponly; samesite=lax

Call3:
Set-Cookie: PHPSESSID=6d79a702tkpjhkbu0bhl6gm2kc; path=/; httponly; samesite=lax

Call4:
Set-Cookie: PHPSESSID=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; HttpOnly; SameSite=lax
Set-Cookie: PHPSESSID=deleted; expires=Mon, 14-Dec-2020 13:58:53 GMT; Max-Age=0; path=/; httponly; samesite=lax

Call5: 
Set-Cookie: PHPSESSID=t4con28ia2r06rdvebko32roua; path=/; httponly; samesite=lax
```

And so on.

This is caused by this change: https://github.com/symfony/http-kernel/commit/8983be5ffb4701f61bb24cefcf1207dbe2b77cd5#diff-f78b66c251522e67fb27c1dbea2a7e22f210e7d0427f6c5654e87d7a3f54a40c

The following code deletes the session cookie if the session is empty which is the case in this example because it is only read by the flashes twig extension:

```
   if ($requestSessionCookieId && $session->isEmpty()) {
                $response->headers->clearCookie(
                    $sessionName,
                    $sessionCookiePath,
                    $sessionCookieDomain,
                    $sessionCookieSecure,
                    $sessionCookieHttpOnly,
                    $sessionCookieSameSite
                );
            }
```

Maybe I'm missing something but this code causes other problems, too: https://github.com/symfony/symfony/discussions/44609

### How to reproduce

- Setup Symfony project: symfony new test
- Install twig bundle: composer require symfony/twig-bundle
- Add route to example project to render base template:
  ```
  #[Route('/')]
  public function test() {
    return $this->render('base.html.twig', [
    ]);
  }
  ```
- Read flashes in base template:
   ```
   {% for message in app.flashes('notice') %}
                <div class="flash-notice">
                    {{ message }}
                </div>
            {% endfor %}
   ```
- Enable sessions in framework config:
  ```
  session:
          enabled: true
          handler_id: null
          cookie_secure: false
          cookie_samesite: lax
          storage_factory_id: session.storage.factory.native
  ```
- Call the route multiple times

I also created a Docker container to reproduce the problem: https://gist.github.com/johannes85/4ca8c660c7643b01d35aeb0fd43e77fe
Run it like that: ```docker build . -t symtest && docker run --rm -it symtest```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q             | A
| ------------- | ---
| Branch?       | 5.4 for bug fixes 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #44553, Fix #44616 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Fix compatibility to PHPBridge with new session handling.

TODO:

 - [x] Test

### CODE REVIEW

**Comment by devnix** [comment]
Hi! I think the following lines would have to be deleted. It just does not make sense to remove the cookie if the session bags are empty, because that does not mean the session is empty (and used by other application): https://github.com/symfony/symfony/blob/v5.4.0/src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php#L154-L162

**Comment by alexander-schranz** [comment]
@devnix this lines can not be removed as they handles the correct handling of a logout when running swoole and roadrunner. I'm currently thinking about check if the PHP bridge is activated and then go with the old behaviour and let PHP handle the session cookie then again. Means that swoole and roadrunner could not be used with that applications correctly but I think that this application don't even use the symfony/runtime so I think that would be fine.

**Comment by devnix** [comment]
@alexander-schranz alright, that's what I feared (I didn't make directly a PR because I suspected I was going to miss a fact like that).

Speaking from ignorance: maybe the listener could call a method defined by `SessionStorageInterface`, so each session storage would know how they have to handle by implementing that method?

**Comment by alexander-schranz** [comment]
@devnix the `isEmpty` is currently a way to know if `invalidate` was called: https://github.com/symfony/symfony/blob/0d6e859db236e37b8baa2b2bf4c8b7d14d151570/src/Symfony/Component/HttpFoundation/Session/Session.php#L175
 As example the logout listener does it by default:
 https://github.com/symfony/symfony/blob/d17ae344e79919caba2f19bb0cb23bf24c1f773d/src/Symfony/Component/Security/Http/EventListener/SessionLogoutListener.php#L29
So what is missing is to know if a session is invalid or not at current state. But I did avoided to extend the SessionInterface with new methods which are not required currently and so did go with isEmpty. Personaly I think a session which is empty can savely be removed. So I would maybe we should adjust the `isEmpty` in the PHPBridge to check if there are not other values in the `$_SESSION` variable beside the empty symfony storage variable. Or find another way to check for invalid session or as said above let PHP handle the session cookie when the php bridge is used.

**Comment by alexander-schranz** [comment]
@devnix found that I can check if the session was even changed using the session usage index. Can you check this change with your application?

**Comment by devnix** [comment]
I will be able to check it next monday!

I have a wild guess: if a session is started by another application, and later a Symfony controller is called without touching the session, will not be deleted because the usage index would be zero?

This can even happen with coexisting, separated web applications, not only with legacy applications integrating Symfony

File: src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php [hunk 1]
```diff
@@ -152,7 +154,8 @@ public function onKernelResponse(ResponseEvent $event)
             $request = $event->getRequest();
             $requestSessionCookieId = $request->cookies->get($sessionName);
 
-            if ($requestSessionCookieId && $session->isEmpty()) {
+            $isSessionEmpty = $session->isEmpty();
+            if ($requestSessionCookieId && $isSessionEmpty && $session->getUsageIndex() > 0) {
```
Comment (jderusse) [inline src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]: why the check on usageIndex?

Comment (alexander-schranz) [reply src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]: To know if a session was destroyed by example [`invalidate`](https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/HttpFoundation/Session/Session.php#L179) or [`migrate`](https://github.com/symfony/symfony/blob/4274a1f04707948dd0826ee37e1821154f4597af/src/Symfony/Component/HttpFoundation/Session/Session.php#L187). 

There is currently no other identicator currently to know if a session was destroyed.

The other way would be we to extend the `Session` with a new method `isDestroyed` to know when we need to clear the session cookie.

Comment (alexander-schranz) [reply src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]: But as mention by @devnix this does not solve the problem for native session being started and written without a session being used in symfony.

**Comment by alexander-schranz** [comment]
@devnix Thank you for the feedback. Make sense. I tried to create test cases for it and check now also for `$_SESSION` to avoid these problems with other native sessions variables written before.

/cc @jderusse

**Comment by devnix** [comment]
I will try the patch ASAP, as I don't have access to the repository right now. Thank you so much, @alexander-schranz

File: src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php [hunk 2]
```diff
@@ -152,7 +154,8 @@ public function onKernelResponse(ResponseEvent $event)
             $request = $event->getRequest();
             $requestSessionCookieId = $request->cookies->get($sessionName);
 
-            if ($requestSessionCookieId && $session->isEmpty()) {
+            $isSessionEmpty = $session->isEmpty() && empty($_SESSION); // checking native $_SESSION to keep compatibility to php bridge sessions
```
Comment (jderusse) [inline src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]: check on global véritable`$_SESSION` sounds dubious..
why this check is not part of the method `isEmpty()`?

Comment (alexander-schranz) [reply src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]: Not sure if thats a good idea. As $_SESSION should only be kept in mind here. As $_SESSION is only correctly updated after the `save` method is called (some lines above). If we move it to HttpFoundation component to handle keep $_SESSION in mind for isEmpty the check will not end in a correct result for not yet saved bags yet.

Comment (devnix) [reply src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]: Would be a good idea to have a method like `isDestroyaable(): bool` on each session handler implementation? In that case, each handler could call his own `isEmpty()` implementation, and in the case of the php bridge it could call `isEmpty()` and `empty($_SESSION)`

Comment (alexander-schranz) [reply src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]: The difficulty is that would extend the public API, which Symfony is very strict about it and doing only in minor releases. When we would do that we could also directly store the $destroy state in the Session instance of the HttpFoundation component. And then go with Session::isDestroyed(): bool.
Personally would like that lifetime and other things also live on the Session Object and not on some options, but that's another topic.
Still our other option would be skip the whole things when the PHPBridge Session is active and so go with the behaviour of Symfony 5.3 where php will write and remove the session headers. Disadvantage is that the php bridge session not work then in CLI context (session based tests, runtimes like swoole roadrunner not working). To skip that we would need have a boolean flag injected which is set when php session bridge is active to another value.

Comment (jderusse) [reply src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]: `isDestroyable` is a good idea, but cannot be used for a bug fix (this PR)

I don't like checking `$_SESSION` (It sounds weird to check the global variable in case somebody changed it), but I don't know how to fix this case without it. 

ping @symfony/mergers

Comment (chalasr) [reply src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]: Works for me as-is, `$_SESSION` is already used in `reset()` l174.

**Review by jderusse — APPROVED** [review]

File: src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php [hunk 3]
```diff
@@ -77,8 +77,10 @@ public function onKernelRequest(RequestEvent $event)
                 /*
                  * For supporting sessions in php runtime with runners like roadrunner or swoole the session
                  * cookie need read from the cookie bag and set on the session storage.
+                 *
+                 * Do not set it when example the PHPBridge for session is used which already starts a session.
```
Comment (chalasr) [inline src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]: Seems like a word is missing around `example`?

Comment (alexander-schranz) [inline src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]:
```suggestion
                 * Do not set it when for example the PHPBridge for session is used which already starts a session.
```

**Review by chalasr — APPROVED** [review]

**Comment by johannes85** [comment]
I know, I'm late to the conversation but I think it would be a good idea to give the person, implementing the session handling  a way to control the behavior of creating/deleting the session cookie (as @devnix suggested).

In my case we have a centralized login which creates a session (in Redis) and writes the cookie.
Our applications (around 20) are using this already created session.

Now we want to migrate those applications away from the current framework to Symfony, so I implemented a custom authenticator for this session but also wanted to reuse this session in a custom SessionStorage.

This worked up until Symfony 5.4 which now kills the externally generated session cookie.
So, a way for my SessionStorage to tell Symfony: "don't mess with the session cookie" would be nice.

My solution now is to have two sessions. One created by our login application and one created by Symfony, using one Redis connection (singleton via DI).
This also doesn't work as intended because of https://github.com/symfony/symfony/issues/44616 but is fixed with https://github.com/symfony/symfony/pull/44657

**Comment by alexander-schranz** [comment]
@johannes85 as discussed in https://github.com/symfony/symfony/pull/44634#discussion_r776405949 there would be better options. But are not possible in a bugfix as a bugfix is not allowed to extend the public API.

**Comment by nicolas-grekas** [comment]
Thank you @alexander-schranz.

**Comment by alexander-schranz** [comment]
Thx all for helping, testing and providing feedback!

**Comment by nicolas-grekas** [comment]
@alexander-schranz could you please have a look at branch 6.0?
I feel like my merge is wrong there :grimacing:  (tests of HttpKernel are failing).

**Comment by alexander-schranz** [comment]
@nicolas-grekas see https://github.com/symfony/symfony/pull/45192
