### PR TITLE
[HttpClient] disable debug log with curl 7.64.0

### LINKED ISSUE #35975: [HttpClient] Add option to disable debug buffer in CurlResponse
**Description**  
I'm in need for an option to disable usage of debug buffer in `CurlResponse`. `CurlResponse::getInfo()` loads debug buffer to memory. Exceptions using  `HttpExceptionTrait` triggers this method and sometimes this triggers memory size error:
```
Sentry\Exception\FatalErrorException: Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 236911944 bytes)
#0 /vendor/symfony/http-client/Response/CurlResponse.php(167): null
```
It is hard to debug actual reason of this since this is happening from time to time and on production server only. I don't need this debug information at all. Just HTTP status code would be enough and some response content. How can I disable this?

```
$ composer show | grep http-client 
psr/http-client                     1.0.0   Common interface for HTTP clients
symfony/http-client                 v4.3.5  Symfony HttpClient component
symfony/http-client-contracts       v1.1.7  Generic abstractions related to HTTP clients
```

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35975
| License       | MIT
| Doc PR        | -

Works around https://curl.haxx.se/mail/archive-2019-02/0013.html

### CODE REVIEW

File: src/Symfony/Component/HttpClient/Response/CurlResponse.php [hunk 1]
```diff
@@ -37,15 +37,19 @@ final class CurlResponse implements ResponseInterface
...
     {
         $this->multi = $multi;
 
         if (\is_resource($ch)) {
             $this->handle = $ch;
             $this->debugBuffer = fopen('php://temp', 'w+');
-            curl_setopt($ch, CURLOPT_VERBOSE, true);
-            curl_setopt($ch, CURLOPT_STDERR, $this->debugBuffer);
+            if (0x074000 === $curlVersion) {
+                fwrite('Due to a bug in curl 7.64.0, the debug log is disabled; use another version to work around the issue.');
```
Comment (norkunas) [inline src/Symfony/Component/HttpClient/Response/CurlResponse.php]: Missing handle?

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpClient/Response/CurlResponse.php]: fixed thanks
