### PR TITLE
[TwigBridge] don't use deprecated and internal Twig functions

### LINKED ISSUE #52987: [TwigBridge] function `twig_test_empty` is deprecated in Twig 3.9
### Symfony version(s) affected

5.4.31, 6.4.0, 7.0.0, 7.1

### Description

The `twig_*` global functions are deprecated in Twig 3.9 https://github.com/twigphp/Twig/pull/3883, and removed in Twig 4.0 https://github.com/twigphp/Twig/pull/3937

The function `twig_test_empty` is used in `Symfony\Bridge\Twig\Node\SearchAndRenderBlockNode`:

https://github.com/symfony/symfony/blob/228a275ddcc1a4301fc8865945c0686b56658135/src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php#L53

https://github.com/symfony/symfony/blob/228a275ddcc1a4301fc8865945c0686b56658135/src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php#L100

### How to reproduce

```
composer create-project symfony/demo
composer require "twig/twig: 3.x-dev"
```

Go to `https://localhost:8000/fr/admin/post/1/edit`

Deprecation message:

```
Since twig/twig 3.9.0: Using the internal "twig_test_empty" function is deprecated.
```

### Possible Solution

Duplicate the function as a static method in `SearchAndRenderBlockNode`.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #52987
| License       | MIT

`twig_test_empty()` and `twig_escape_filter()` are deprecated since Twig 3.9

### CODE REVIEW

File: src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php [hunk 1]
```diff
@@ -97,7 +98,7 @@ public function compile(Compiler $compiler): void
 
                         // Check at runtime whether the label is empty.
                         // If not, add it to the array at runtime.
-                        $compiler->raw('(twig_test_empty($_label_ = ');
+                        $compiler->raw('(FormExtension::testEmpty($_label_ = ');
```
Comment (GromNaN) [inline src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php]: I guess the FQCN should be used?

File: src/Symfony/Bridge/Twig/Extension/FormExtension.php [hunk 2]
```diff
@@ -158,6 +158,26 @@ public function getFieldChoices(FormView $view): iterable
         yield from $this->createFieldChoicesList($view->vars['choices'], $view->vars['choice_translation_domain']);
     }
 
+    /**
+     * @internal
```
Comment (GromNaN) [inline src/Symfony/Bridge/Twig/Extension/FormExtension.php]: Maybe we can put a comment that this function has been copied from `twig_test_empty`, to help track changes.

**Comment by OskarStark** [comment]
The same seems to be needed for `twig_escape_filter `

>  11x: Since twig/twig 3.9.0: Using the internal "twig_escape_filter" function is deprecated.
>    11x in WebProfilerExtensionTest::testDumpHeaderIsDisplayed from Symfony\Bundle\WebProfilerBundle\Tests\Twig

File: src/Symfony/Bridge/Twig/Extension/FormExtension.php (hunk 2 above)
Comment (derrabus) [reply src/Symfony/Bridge/Twig/Extension/FormExtension.php]: Or maybe we use `CoreExtension::testEmpty()` if it exists?

Comment (GromNaN) [reply src/Symfony/Bridge/Twig/Extension/FormExtension.php]: [`CoreExtension::testEmpty()` is internal](https://github.com/twigphp/Twig/blob/3.x/src/Extension/CoreExtension.php#L1322), its signature could change, or it could be moved or renamed.

Comment (derrabus) [reply src/Symfony/Bridge/Twig/Extension/FormExtension.php]: Given that we intend to migrate Twig into a Symfony component, I think it's fine to access `@internal` functions.

Comment (stof) [reply src/Symfony/Bridge/Twig/Extension/FormExtension.php]: Even in Symfony components, it is not fine to use `@internal` APIs of a *different* component, as components relies on semver ranges in their inter-component requirements.

File: src/Symfony/Bridge/Twig/Extension/FormExtension.php [hunk 3]
```diff
@@ -158,6 +158,26 @@ public function getFieldChoices(FormView $view): iterable
...
+     */
+    public static function testEmpty($value)
```
Comment (stof) [inline src/Symfony/Bridge/Twig/Extension/FormExtension.php]:
```suggestion
    public static function testEmpty($value): bool
```

File: src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php [hunk 4]
```diff
@@ -107,4 +113,24 @@ public function compile(Compiler $compiler): void
 
         $compiler->raw(')');
     }
+
+    /**
+     * @see \Twig\Extension\CoreExtension::testEmpty()
+     */
+    private static function isEmpty($value): bool
```
Comment (GromNaN) [inline src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php]: If we rely on the internal twig function for the compiled template, we can do the same for the compilation step and avoid duplicating the code.

But I'm still not sure this is a sane solution to rely on the internal function.

File: src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php [hunk 5]
```diff
@@ -97,7 +98,12 @@ public function compile(Compiler $compiler): void
 
                         // Check at runtime whether the label is empty.
                         // If not, add it to the array at runtime.
-                        $compiler->raw('(twig_test_empty($_label_ = ');
+                        if (method_exists(CoreExtension::class, 'testEmpty')) {
+                            $compiler->raw('(Twig\Extension\CoreExtension::testEmpty($_label_ = ');
```
Comment (fabpot) [inline src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php]: No need to use the fully qualified class name here: https://github.com/twigphp/Twig/blob/4.x/src/Node/ModuleNode.php#L146

File: src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php (hunk 4 above)
Comment (fabpot) [reply src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php]: I agree, let's use the Twig method instead.

File: src/Symfony/Bundle/WebProfilerBundle/Twig/WebProfilerExtension.php [hunk 6]
```diff
@@ -116,4 +116,49 @@ public function getName()
     {
         return 'profiler';
     }
+
+    /**
+     * @see \Twig\Extension\EscaperExtension::escape()
+     */
+    private static function escape(string $s, string $charset): string
```
Comment (fabpot) [inline src/Symfony/Bundle/WebProfilerBundle/Twig/WebProfilerExtension.php]: I would also use the Twig internal method instead.

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php (hunk 4 above)
Comment (GromNaN) [reply src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php]: Maybe these methods shouldn't be `@internal` then?

File: src/Symfony/Bundle/WebProfilerBundle/Twig/WebProfilerExtension.php (hunk 6 above)
Comment (xabbuh) [reply src/Symfony/Bundle/WebProfilerBundle/Twig/WebProfilerExtension.php]: done

File: src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php [hunk 7]
```diff
@@ -49,8 +50,14 @@ public function compile(Compiler $compiler): void
                         // of variables at compile time.
                         $labelIsExpression = false;
 
+                        if (method_exists(CoreExtension::class, 'testEmpty')) {
```
Comment (GromNaN) [inline src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php]:
```suggestion
                        // twig_test_empty is deprecated in Twig 3.9
                        if (method_exists(CoreExtension::class, 'testEmpty')) {
```
Adding such comment helps when we remove compatibility with older versions years after.

Comment (xabbuh) [reply src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php]: add comments (slightly reworded)

File: src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php [hunk 8]
```diff
@@ -49,8 +50,15 @@ public function compile(Compiler $compiler): void
...
+                            $isEmpty = CoreExtension::testEmpty($label->getAttribute('value'));
+                        } else {
+                            // to be removed when support for Twig 3 is dropped
+                            $isEmpty = twig_test_empty($label->getAttribute('value'));
+                        }
+
                         // Only insert the label into the array if it is not empty
-                        if (!twig_test_empty($label->getAttribute('value'))) {
+                        if (!$isEmpty) {
```
Comment (stof) [inline src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php]: Can we use `$label !== null && $label !== ''` as condition instead ? We don't need to handle cases about checking emptiness for other kind of values here.

Comment (xabbuh) [reply src/Symfony/Bridge/Twig/Node/SearchAndRenderBlockNode.php]: done

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.
