### PR TITLE
Fix/Rewrite .gitignore regex builder

### LINKED ISSUE #39257: [Finder]: GitIgnore unable to exclude a directory and its content
**Symfony version(s) affected**: >=4.4.12

**Description**  

I'm trying to exclude a directory and its content. I have a configuration similar to the one described in #37560. I'm trying to keep all the content in `/example/test/`.

```
/example/**
!/example/example.txt
!/example/packages
!/example/packages/example.yaml
!/example/test/
```

This configuration will only retain the `/example/test` directory, but not its content. If I try a `.gitignore` like the one below, PCRE breaks completely:

```
/example/**
!/example/example.txt
!/example/packages
!/example/packages/example.yaml
!/example/test*
```
PCRE doesn't handle lookbehind that don't have a fixed length. So the above `.gitignore` file will cause `preg_match(): Compilation failed: lookbehind assertion is not fixed length` warnings. This, in turn, causes the whole `.gitignore` regex to not work and none of the rules get enforced.

### PR DESCRIPTION
**Pull request by mvorisek**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | fix #39257
| License       | MIT
| Doc PR        | no

This PR fixes `.gitignore` with exclude wildcard ignore rules like `!a/*/b` were failing with `preg_match(): Compilation failed: lookbehind assertion is not fixed length at offset` PHP error.

Functionality/performance was verified against large `.gitignore` files:
- https://github.com/PrestaShop/PrestaShop/blob/1.7.7.3/.gitignore
- https://github.com/dotnet/installer/blob/v5.0.202/.gitignore
- https://github.com/dotnet/runtime/blob/v5.0.5/.gitignore

This PR also improves the testing cases.

### CODE REVIEW

File: src/Symfony/Component/Finder/Gitignore.php [hunk 1]
```diff
@@ -14,120 +14,78 @@
...
+        $gitignoreLines = preg_split('~\r\n?|\n~', $gitignoreFileContent);
 
-        $positives = [];
-        $negatives = [];
+        $res = self::lineToRegex('');
         foreach ($gitignoreLines as $i => $line) {
-            $line = trim($line);
-            if ('' === $line) {
-                continue;
+            if (\strlen($line) < 2 || '\\' !== substr($line, -2, 1)) {
```
Comment (jderusse) [inline src/Symfony/Component/Finder/Gitignore.php]: What's about `foo\\ `?

File: src/Symfony/Component/Finder/Finder.php [hunk 2]
```diff
@@ -721,7 +721,7 @@ private function searchInDirectory(string $dir): \Iterator
         }
 
         if (static::IGNORE_VCS_IGNORED_FILES === (static::IGNORE_VCS_IGNORED_FILES & $this->ignore)) {
-            $gitignoreFilePath = sprintf('%s/.gitignore', $dir);
+            $gitignoreFilePath = $dir.'/.gitignore';
```
Comment (jderusse) [inline src/Symfony/Component/Finder/Finder.php]: revert: this change nothing and is the single diff of this file

File: src/Symfony/Component/Finder/Gitignore.php [hunk 3]
```diff
@@ -14,120 +14,78 @@
...
      *
-     * @return string The regexp
+     * Format specification: https://git-scm.com/docs/gitignore#_pattern_format
      */
     public static function toRegex(string $gitignoreFileContent): string
     {
-        $gitignoreFileContent = preg_replace('/^[^\\\r\n]*#.*/m', '', $gitignoreFileContent);
-        $gitignoreLines = preg_split('/\r\n|\r|\n/', $gitignoreFileContent);
+        $gitignoreFileContent = preg_replace('~(?<!\\\\)#[^\n\r]*~', '', $gitignoreFileContent);
+        $gitignoreLines = preg_split('~\r\n?|\n~', $gitignoreFileContent);
```
Comment (jderusse) [inline src/Symfony/Component/Finder/Gitignore.php:30]: I found `\r\n|\r|\n` more readable/maintainable

File: src/Symfony/Component/Finder/Gitignore.php [hunk 4]
```diff
@@ -14,120 +14,78 @@
...
 
-        $positives = [];
-        $negatives = [];
+        $res = self::lineToRegex('');
         foreach ($gitignoreLines as $i => $line) {
-            $line = trim($line);
-            if ('' === $line) {
-                continue;
+            if (\strlen($line) < 2 || '\\' !== substr($line, -2, 1)) {
+                $line = rtrim($line, ' ');
```
Comment (jderusse) [inline src/Symfony/Component/Finder/Gitignore.php]: what's about tabs?

File: src/Symfony/Component/Finder/Gitignore.php [hunk 5]
```diff
@@ -14,120 +14,78 @@
...
-            $negatives[$i] = null;
-            $positives[$i] = self::getRegexFromGitignore($line);
-        }
-
-        $index = 0;
-        $patterns = [];
-        foreach ($positives as $pattern) {
-            if (null === $pattern) {
-                continue;
+            if (0 === strpos($line, '!')) {
```
Comment (jderusse) [inline src/Symfony/Component/Finder/Gitignore.php]:
```suggestion
            if ($line[0] === '!') {
```

File: src/Symfony/Component/Finder/Gitignore.php [hunk 6]
```diff
@@ -14,120 +14,78 @@
...
+                $line = substr($line, 1);
+                $isNegative = true;
+            } elseif ('' !== $line) {
```
Comment (jderusse) [inline src/Symfony/Component/Finder/Gitignore.php]:
```php
if ($line === '') {
    continue;
}
```

File: src/Symfony/Component/Finder/Gitignore.php [hunk 7]
```diff
@@ -14,120 +14,78 @@
...
-                    $regex .= $c;
+        $slashPos = strpos($gitignoreLine, '/');
+        if (false !== $slashPos && \strlen($gitignoreLine) - 1 !== $slashPos) {
+            if (0 === $slashPos) {
+                $gitignoreLine = substr($gitignoreLine, 1);
             }
+            $isAbsolute = true;
+        } else {
+            $isAbsolute = false;
         }
```
Comment (jderusse) [inline src/Symfony/Component/Finder/Gitignore.php]: What if thr string contains several occurences of `/`? like `/foo/` or `./bar/baz`?
Shouldn't it be? 
```suggestion
        if ($gitignoreLine[0] === '/') {
            $gitignoreLine = substr($gitignoreLine, 1);
            $isAbsolute = true;
        } else {
            $isAbsolute = false;
        }
```

File: src/Symfony/Component/Finder/Tests/GitignoreTest.php [hunk 8]
```diff
@@ -13,136 +13,313 @@
...
+            ],
+            [
+                ['/*'],
+                ['a', 'a/b', 'a/b/c', 'aa', 'm.txt', '.txt'],
+                [],
+            ],
+            [
+                ['/a', 'm/*'],
+                ['a', 'a/b', 'a/b/c', 'm/'],
+                ['aa', 'm', 'b/m', 'b/m/'],
```
Comment (jderusse) [inline src/Symfony/Component/Finder/Tests/GitignoreTest.php:93]: why `m/` and not `b/m/`?

File: src/Symfony/Component/Finder/Gitignore.php (hunk 4 above)
Comment (mvorisek) [reply src/Symfony/Component/Finder/Gitignore.php:35]: `.gitignore` spec says `spaces` explicitly

File: src/Symfony/Component/Finder/Gitignore.php (hunk 5 above)
Comment (mvorisek) [reply src/Symfony/Component/Finder/Gitignore.php]: no - I do not use strings as arrays

File: src/Symfony/Component/Finder/Tests/GitignoreTest.php (hunk 8 above)
Comment (mvorisek) [reply src/Symfony/Component/Finder/Tests/GitignoreTest.php:93]: by spec, citing:

> If there is a separator at the beginning or middle (or both) of the pattern, then the pattern is relative to the directory level of the particular .gitignore file itself. Otherwise the pattern may also match at any level below the .gitignore level.

File: src/Symfony/Component/Finder/Gitignore.php (hunk 4 above)
Comment (mvorisek) [reply src/Symfony/Component/Finder/Gitignore.php]: by spec, citing:

> Trailing spaces are ignored unless they are quoted with backslash ("\").

File: src/Symfony/Component/Finder/Gitignore.php (hunk 7 above)
Comment (mvorisek) [reply src/Symfony/Component/Finder/Gitignore.php]: No, by spec, citing:

> If there is a separator at the beginning or middle (or both) of the pattern, then the pattern is relative to the directory level of the particular .gitignore file itself. Otherwise the pattern may also match at any level below the .gitignore level.

File: src/Symfony/Component/Finder/Gitignore.php (hunk 1 above)
Comment (mvorisek) [reply src/Symfony/Component/Finder/Gitignore.php]: You are right, I must use regex here.

File: src/Symfony/Component/Finder/Gitignore.php (hunk 3 above)
Comment (mvorisek) [reply src/Symfony/Component/Finder/Gitignore.php:30]: No, `~` regex delimiter is now used here solely which is much better when working with paths as `/` does not need to be backslashed. Greatly improves readability.

File: src/Symfony/Component/Finder/Finder.php (hunk 2 above)
Comment (mvorisek) [reply src/Symfony/Component/Finder/Finder.php]: done

File: src/Symfony/Component/Finder/Gitignore.php (hunk 6 above)
Comment (mvorisek) [reply src/Symfony/Component/Finder/Gitignore.php]: fixed

File: src/Symfony/Component/Finder/Gitignore.php (hunk 4 above)
Comment (mvorisek) [reply src/Symfony/Component/Finder/Gitignore.php]: I now verified `spaces` term in the spec is used for tabs as well. Will add test case and fix the code. Thanks!

File: src/Symfony/Component/Finder/Gitignore.php (hunk 1 above)
Comment (mvorisek) [reply src/Symfony/Component/Finder/Gitignore.php]: done incl. tests

File: src/Symfony/Component/Finder/Gitignore.php (hunk 4 above)
Comment (mvorisek) [reply src/Symfony/Component/Finder/Gitignore.php]: addressed incl. tests

File: src/Symfony/Component/Finder/Gitignore.php (hunk 5 above)
Comment (jderusse) [reply src/Symfony/Component/Finder/Gitignore.php]: well, looking for the position of `!` in the entire string when only the first char matters is not efficient, and a waste of CPU time.
I could suggest using `if (substr($line, 0, 1) === '!')` to fix this, but then, people will suggest replacing the call to the `substr method` by `[0]` which is more efficient. 
So given we know the string is not empty, please, use `$line[0]`. this is not about dealing with array vs string. But using the most effective way allowed by PHP to check the first char of a string.

Comment (jderusse) [reply src/Symfony/Component/Finder/Gitignore.php]: well, looking for the position of `!` in the entire string when only the first char matters is not efficient, and a waste of CPU time.
I could suggest using `if (substr($line, 0, 1) === '!')` to fix this, but then, people will suggest replacing the call to the `substr method` by `[0]` which is more efficient. 
So given we know the string is not empty, please, use `$line[0]`. this is not about dealing with array vs string. But using the most effective way allowed by PHP to check the first char of a string.

Comment (mvorisek) [reply src/Symfony/Component/Finder/Gitignore.php]: It can be empty, `substr($line, 0, 1) === '!'` is good. Code updated.

**Comment by Jeroeny** [comment]
With `.gitignore`:

```
/config/**
!/config/packages
!/config/packages/something.yaml
```

It seems to give an invalid result:
given: `config/packages/foo.yaml`
actual: git-ignored
regex result: 0 (no match, not git-ignored)

**Comment by mvorisek** [comment]
@Jeroeny I can confirm this issue. The issue is following:

`/config/**` rule is canceled by `!/config/packages` rule now, because the later rule does not end with `/`. Any idea how to fix this?

File: src/Symfony/Component/Finder/Gitignore.php (hunk 3 above)
Comment (stof) [reply src/Symfony/Component/Finder/Gitignore.php:30]: @mvorisek the comment was not about the delimiter

**Comment by mvorisek** [comment]
@Jeroeny `/config/**` rule is canceled by `!/config/packages` rule now. Any idea how to fix this?

I think the issue comes from the spec how paths are evaluated:

> It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined. 

Currently, the regex is generated for one shot (full path) evaluation. Do you have an idea how to fix the matching and keep it one shot?

**Comment by mvorisek** [comment]
@Jeroeny `/config/**` rule was wrongly "canceled" by `!/config/packages` rule. Now fixed in 13179f8fd2225ce414e91d2303f6486ba2830bb4.

**Comment by mvorisek** [comment]
This PR is complete and passing all tests, the Appveyor CI error is irrelevant.

**Comment by mvorisek** [comment]
@stof @fabpot can you please review this PR?

**Comment by mvorisek** [comment]
This PR is hanging here for 3 weeks, AppVeyor build error is irrelevant, can someone please review it?

**Review by maxhelias — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @mvorisek.
