### PR TITLE
[SecurityBundle] Link UserProviderListener to correct firewall dispatcher

### LINKED ISSUE #40158: [Security][Authenticator-based] Multiple providers
**Symfony version(s) affected**: 5.2.3

**Description**  
When using the new Authenticator-based Security with multiple providers, the `UserBadge` do not use the provider config in the firewall.

```yml
security:
    enable_authenticator_manager: true

    encoders:
        App\Entity\User:
            algorithm: auto
        Symfony\Component\Security\Core\User\User: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

        logbook_user_provider:
            memory:
                users:
                    logbook:
                        password: '%env(APP_LOGBOOK_USER_PASSWORD)%'
                        roles: 'ROLE_LOGBOOK_USER'

    firewalls:
        logbook:
            host: '%logbook_subdomain%'
            pattern: ^/logbook-entry
            provider: logbook_user_provider
            http_basic: ~

        main:
            provider: app_user_provider
            custom_authenticators:
                - App\Security\AppLoginAuthenticator
            logout:
                path: app_logout
```

In that exemple, when I use the `UserBadge` in `App\Security\AppLoginAuthenticator`, the Badge try to retrieve the user in the `logbook_user_provider` and not in `app_user_provider`.

I can use a callback as second argument in the `UserBadge`, and it works. But I think, because we define the Entity provider as provider in the firewall, we expect to use automatically that provider.

### LINKED ISSUE #41474: SF 5.3 Event listener listens to the same event twice
**Symfony version(s) affected**: 5.3

**Description**
I'm not sure if it's a bug or not, but it looks like the `Symfony\Component\Security\Http\Event\CheckPassportEvent` is listen twice by the same event listener.

I can submit a PR If you have some guidelines to help me

**How to reproduce**

With symfony binary (php 8.0.5)

```sh
symfony new --full test && cd test && bin/console debug:event-dispatcher "Symfony\Component\Security\Http\Event\CheckPassportEvent"
```
Output: 

```

Registered Listeners for "Symfony\Component\Security\Http\Event\CheckPassportEvent" Event
=========================================================================================

 ------- ----------------------------------------------------------------------------------------- ---------- 
  Order   Callable                                                                                  Priority  
 ------- ----------------------------------------------------------------------------------------- ---------- 
  #1      Symfony\Component\Security\Http\EventListener\UserProviderListener::checkPassport()       2048      
  #2      Symfony\Component\Security\Http\EventListener\UserProviderListener::checkPassport()       1024      
  #3      Symfony\Component\Security\Http\EventListener\CsrfProtectionListener::checkPassport()     512       
  #4      Symfony\Component\Security\Http\EventListener\CheckCredentialsListener::checkPassport()   0         
 ------- ----------------------------------------------------------------------------------------- ---------- 

```

### PR DESCRIPTION
**Pull request by Matth--**
| Q             | A
| ------------- | ---
| Branch?       | 5.2 
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no 
| Tickets       | Fix #40158 , Fix #41474
| License       | MIT
| Doc PR        | /

When using the new AuthenticationManager, an incorrect UserProvider could be attached to the UserBadge when having multiple providers defined in `security.yaml`.

The `UserProviderListener` was tagged to the global event dispatcher instead of the dispatcher for the specific firewall.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Can you please add a test case if possible?

**Comment by Matth--** [comment]
@nicolas-grekas I added some functional tests (Feel like this was the better way to get failing tests first). 
The tests were failing without the change to the `SecurityExtension` class.

Do you have a suggestion to fix the Travis ci bugs? I feel like it used the Symfony 5.4 branch to run tests against.

**Comment by derrabus** [comment]
> Do you have a suggestion to fix the Travis ci bugs?

I'd say, the Travis failure is unrelated to your changes.

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 1]
```diff
@@ -358,14 +366,6 @@ private function createFirewall(ContainerBuilder $container, string $id, array $
 
         $config->replaceArgument(5, $defaultProvider);
 
-        // Register Firewall-specific event dispatcher
-        $firewallEventDispatcherId = 'security.event_dispatcher.'.$id;
-        $container->register($firewallEventDispatcherId, EventDispatcher::class);
```
Comment (stof) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:363]: I would keep the registration of the dispatcher service here instead of moving it up (you only moved it partially anyway). Move only the `firewallEventDispatcherId` variable up.

Comment (Matth--) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:363]: 👍

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @Matth--.
