### PR TITLE
[ObjectMapper] initialize lazy objects

### LINKED ISSUE #61050: [ObjectMapper] Cannot map doctrine proxy objects due to reflection not finding map attributes
### Symfony version(s) affected

7.3

### Description

the 7.3 ObjectMapper component cannot handle objects like doctrine proxies reliably, specificially the
ObjectMapper::getSourceReflectionClass(object $source, \ReflectionClass $targetRefl): \ReflectionClass will reflect the proxy itself and not the underlying entity and its properties

It will fail with an error like

`Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: Can't get a way to read the property "identifier" in class "Proxies\__CG__\App\Entity\Foo".`

(Only checked with < PHP 8.4, its not using the php internal proxy objects)

### How to reproduce

I created an Reproducer

https://github.com/tandev/doctrine_proxy_object_mapper_reproducer/blob/main/tests/DoctrineProxyMappingTest.php

```php
 public function test(): void
    {
        $objectMapper = new ObjectMapper(new ReflectionObjectMapperMetadataFactory(),
            new PropertyAccessor(),
        );

        $foo = new Foo();
        $foo->setName('bar');

        $fooDto = $objectMapper->map($foo, FooDto::class);
        self::assertInstanceOf(FooDto::class, $fooDto);

// works

        $this->entityManager->persist($foo);
        $this->entityManager->flush();

        $proxy = $this->entityManager->getProxyFactory()->getProxy(Foo::class, ['id' => 1])->setName('bar');

        $fooDto = $objectMapper->map($proxy, FooDto::class);
        self::assertInstanceOf(FooDto::class, $fooDto);

//fails
    }
```

fails with 
```
1) App\Tests\DoctrineProxyMappingTest::test
Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: Can't get a way to read the property "identifier" in class "Proxies\__CG__\App\Entity\Foo".
```

### Possible Solution

Look at parent reflection 

like for example some component like PropertyNormalizer does to be able to handle that

https://github.com/symfony/symfony/blob/7.4/src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php#L190

The following commit i made might be a possible fix.

I failed to create an appropriate test case due to not understanding how the proxy object hinders reflection

https://github.com/symfony/symfony/commit/3ef6365c1253c4d3e53610e7c03b2e29655bea01

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| Deprecations? | no
| Issues        | Fix #61050
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php [hunk 1]
```diff
@@ -300,6 +300,15 @@ private function getCallable(string|callable $fn, ?ContainerInterface $locator =
      */
     private function getSourceReflectionClass(object $source, \ReflectionClass $targetRefl): \ReflectionClass
     {
+        if ($source instanceof \Symfony\Component\VarExporter\LazyObjectInterface) {
+            $source->initializeLazyObject();
+        } elseif (\PHP_VERSION_ID >= 80400) {
+            $refl = new \ReflectionClass($source);
+            if ($refl->isUninitializedLazyObject($source)) {
+                $refl->initializeLazyObject($source);
+            }
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/ObjectMapper.php]:
```suggestion
            (new \ReflectionClass($source))->initializeLazyObject($source);
```

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php [hunk 2]
```diff
@@ -300,6 +300,15 @@ private function getCallable(string|callable $fn, ?ContainerInterface $locator =
      */
     private function getSourceReflectionClass(object $source, \ReflectionClass $targetRefl): \ReflectionClass
     {
+        if ($source instanceof \Symfony\Component\VarExporter\LazyObjectInterface) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/ObjectMapper.php]: with proper `use`:
```suggestion
        if ($source instanceof LazyObjectInterface) {
```

**Review by nicolas-grekas — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Review by xabbuh — CHANGES_REQUESTED** [review]
The failure is related?

**Comment by soyuka** [comment]
I shuld skip the test for versions lower then 8.4

**Comment by soyuka** [comment]
I was using the wrong trait, I've rebased and fixed, now we have an expected deprecation for php < 8.4, do you have a baseline for these?

File: src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php [hunk 3]
```diff
@@ -52,8 +53,12 @@
 use Symfony\Component\ObjectMapper\Tests\Fixtures\MultipleTargetProperty\C as MultipleTargetPropertyC;
 use Symfony\Component\ObjectMapper\Tests\Fixtures\MultipleTargets\A as MultipleTargetsA;
 use Symfony\Component\ObjectMapper\Tests\Fixtures\MultipleTargets\C as MultipleTargetsC;
+<<<<<<< HEAD
 use Symfony\Component\ObjectMapper\Tests\Fixtures\PromotedConstructor\Source as PromotedConstructorSource;
 use Symfony\Component\ObjectMapper\Tests\Fixtures\PromotedConstructor\Target as PromotedConstructorTarget;
+=======
+use Symfony\Component\ObjectMapper\Tests\Fixtures\MyProxy;
+>>>>>>> 4ab986d3c9 ([ObjectMapper] initialize lazy objects)
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php]: bad merge ;)

Comment (soyuka) [reply src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php]: whoopsy :)

File: src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php [hunk 4]
```diff
@@ -368,4 +370,37 @@ public static function objectMapperProvider(): iterable
...
+        $mapper = new ObjectMapper();
+        $mapper->map($lazy, \stdClass::class);
+        $this->assertTrue($lazy->isLazyObjectInitialized());
+    }
+
+    public function testMapInitializesNativePhp84LazyObject()
+    {
+        if (\PHP_VERSION_ID < 80400) {
+            $this->markTestSkipped('Native lazy objects require PHP 8.4 or higher.');
+        }
```
Comment (OskarStark) [inline src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php]: Is it possible to use `@requires PHP 8.4` instead?

Comment (soyuka) [reply src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php]: Thanks I wasn't aware this was a thing :)

**Comment by nicolas-grekas** [comment]
Thank you @soyuka.
