### PR TITLE
[Messenger] Fix Redis Transport when username is empty

### LINKED ISSUE #43306: BC Break when using Redis transport with an empty username
**Symfony version(s) affected**: 5.3.8

**Description**

I'm using Symfony Messenger with Redis transport (it's Redis 5.x), and when upgrading `symfony/redis-messenger` 5.3.8, my current setup is broken. 

The errors are: 

```
Symfony\Component\Messenger\Exception\InvalidArgumentException
Redis connection failed: ERR wrong number of arguments for 'auth' command
```

```
ErrorException
Warning: Redis::auth() expects parameter 1 to be string, array given
```

---

It **used to work** with the following configuration:

```
MESSENGER_TRANSPORT_DSN="redis://:password@host/messages/symfony/consumer"
```

There are some changes between 5.3.7 and 5.3.8 that might explain the bug 

https://github.com/symfony/redis-messenger/compare/v5.3.7...v5.3.8

**How to reproduce**

Configure Redis transport with the following env var: 

```
MESSENGER_TRANSPORT_DSN="redis://:password@host/messages/symfony/consumer"
```

### PR DESCRIPTION
**Pull request by villfa**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #43306
| License       | MIT
| Doc PR        | n/a

Checking the username and the password with `isset` is not enough. We also need to check they're not empty strings.
This fixes the BC break introduced by #43124.

See also https://3v4l.org/iASnE

### CODE REVIEW

**Comment by derrabus** [comment]
I think, we need to fix this on 4.4 again.

**Comment by villfa** [comment]
@derrabus The PR is rebased onto 4.4.

**Comment by chalasr** [comment]
@villfa Thank you for the PR. Can you please force-push again to trigger the CI?

**Comment by derrabus** [comment]
@chalasr I closed and reopened the PR and that did the trick apparently.

File: src/Symfony/Component/Messenger/Tests/Transport/RedisExt/ConnectionTest.php [hunk 1]
```diff
@@ -133,6 +133,8 @@ public function provideAuthDsn(): \Generator
     {
         yield 'Password only' => ['password', 'redis://password@localhost/queue'];
         yield 'User and password' => [['user', 'password'], 'redis://user:password@localhost/queue'];
+        yield 'User and colon' => ['user', 'redis://user:@localhost/queue'];
+        yield 'Colon and password' => ['password', 'redis://:password@localhost/queue'];
```
Comment (welcoMattic) [inline src/Symfony/Component/Messenger/Tests/Transport/RedisExt/ConnectionTest.php:137]: It's kind of strange to put a `:` before the password here. It's totally ok to pass the password only : `yield 'Password only' => ['password', 'redis://password@localhost/queue'];`

Comment (villfa) [reply src/Symfony/Component/Messenger/Tests/Transport/RedisExt/ConnectionTest.php:137]: I think you're right but there are situations where supporting this format is handy:
Imagine a configuration file containing something like that: `redis://{env.USER}:{env.PWD}@{env.HOST}/queue`. You see that depending on the environment this line could start by a colon.

Comment (welcoMattic) [reply src/Symfony/Component/Messenger/Tests/Transport/RedisExt/ConnectionTest.php:137]: Indeed, it's a real case (which could happen to me :D )

File: src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php [hunk 2]
```diff
@@ -93,12 +93,14 @@ public static function fromDsn(string $dsn, array $redisOptions = [], \Redis $re
...
         $consumer = $pathParts[3] ?? $redisOptions['consumer'] ?? null;
+        $pass = isset($parsedUrl['pass']) && '' !== $parsedUrl['pass'] ? $parsedUrl['pass'] : null;
+        $user = isset($parsedUrl['user']) && '' !== $parsedUrl['user'] ? $parsedUrl['user'] : null;
 
         $connectionCredentials = [
             'host' => $parsedUrl['host'] ?? '127.0.0.1',
             'port' => $parsedUrl['port'] ?? 6379,
             // See: https://github.com/phpredis/phpredis/#auth
-            'auth' => isset($parsedUrl['pass']) && isset($parsedUrl['user']) ? [$parsedUrl['user'], $parsedUrl['pass']] : $parsedUrl['pass'] ?? $parsedUrl['user'] ?? null,
+            'auth' => null !== $pass && null !== $user ? [$user, $pass] : ($pass ?: $user),
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php]: `($pass ?? $user)` instead (and let's add a test where `pass` is `0` to cover this.)

File: src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php [hunk 3]
```diff
@@ -93,12 +93,14 @@ public static function fromDsn(string $dsn, array $redisOptions = [], \Redis $re
         $stream = $pathParts[1] ?? $redisOptions['stream'] ?? null;
         $group = $pathParts[2] ?? $redisOptions['group'] ?? null;
         $consumer = $pathParts[3] ?? $redisOptions['consumer'] ?? null;
+        $pass = isset($parsedUrl['pass']) && '' !== $parsedUrl['pass'] ? $parsedUrl['pass'] : null;
+        $user = isset($parsedUrl['user']) && '' !== $parsedUrl['user'] ? $parsedUrl['user'] : null;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php]: `$user = '' !== ($parsedUrl['user'] ?? '') ? $parsedUrl['user'] : null;` (same for pass)

File: src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php (hunk 2 above)
Comment (villfa) [reply src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php]: Done

File: src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php (hunk 3 above)
Comment (villfa) [reply src/Symfony/Component/Messenger/Transport/RedisExt/Connection.php]: Done

**Review by chalasr — APPROVED** [review]

**Review by welcoMattic — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @villfa.
