### PR TITLE
[HttpKernel] Introduce `ExceptionEvent::isKernelTerminating()` to skip error rendering when kernel is terminating

### LINKED ISSUE #51912: [HttpKernel] ErrorListener::onKernelException should ignore exception thrown after `kernel.terminate`
### Symfony version(s) affected

all

### Description

Related to https://github.com/symfony/symfony/issues/45205 issue, which was ignored...

When an exception is thrown in a `kernel.terminate` event,
- `kernel.exception` is thrown
- the Symfony ErrorListener::onKernelException handler the exception
- `$response = $event->getKernel()->handle($request, HttpKernelInterface::SUB_REQUEST, false);` is called
- this trigger the `ErrorController` and then the `TwigErrorRenderer`

1) The response rendered seems useless since the response was already sent before the terminate event. (cf https://symfony.com/doc/current/components/http_kernel.html#8-the-kernel-terminate-event) 
2) It can produce extra-useless exception, in my case I have a custom view `TwigBundle/Exception/error.html.twig`
which use the session and/or flashbag and I'm getting some `Failed to start the session because headers have already been sent`.

Introducing a `kernel.terminate_exception` and using it instead of `kernel.exception` could even appear as a BC break for `kernel.exception` listeners or a bugfix because according to the schema in the doc https://symfony.com/doc/current/components/http_kernel.html#handling-exceptions-the-kernel-exception-event, we can see the order `Exception -> Response -> Terminate`.

### How to reproduce

- Throw an exception in a `kernel.terminate` listener -> You'll get extra code executed for no reason
- Add `app.session.flashbag.get('success')` call in a custom `TwigBundle/Exception/error.html.twig` template. -> You'll get failed to start the session error in your logs.

### Possible Solution

Either throw a different event for exception thrown after the terminate exception

Either, at least provide a `ExceptionEvent::isTerminated` or `TerminableInterface::isTerminated`, which would allow to write
```
if ($thing->isTerminated()) {
     return;
}
```
at the beginning of some ExceptionListener like the ErrorListener

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by VincentLanglet**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #51912
| License       | MIT

### CODE REVIEW

**Review by nicolas-grekas — COMMENTED** [review]
I likely misunderstood your proposal but I was expecting the new method on class `ExceptionEvent`.

**Comment by VincentLanglet** [comment]
> I likely misunderstood your proposal but I was expecting the new method on class `ExceptionEvent`.

Indeed I thought about it first, then I saw the kernel was accessible in the ExceptionEvent, this would have avoid an extra param. Also, it would have avoid having to think about passing both the kernel and the terminated state.

I updated the PR to follow this strategy if it's preferred @nicolas-grekas

File: src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php [hunk 1]
```diff
@@ -102,6 +102,13 @@ public function onKernelException(ExceptionEvent $event)
             return;
         }
 
+        if (
+            !$this->debug
+            && $event->isKernelTerminated()
+        ) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php]:
```suggestion
        if (!$this->debug && $event->isKernelTerminated()) {
```

File: src/Symfony/Component/HttpKernel/HttpKernel.php [hunk 2]
```diff
@@ -112,6 +113,7 @@ public function handle(Request $request, int $type = HttpKernelInterface::MAIN_R
      */
     public function terminate(Request $request, Response $response)
     {
+        $this->terminated = true;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/HttpKernel.php]: This adds state to the kernel - please check when this state can be reset in case the kernel is reused after calling this method. Or maybe a try/finally + rename this `terminating`?

**Comment by nicolas-grekas** [comment]
Don't miss adding a line to the changelog of the component.

**Comment by VincentLanglet** [comment]
> Don't miss adding a line to the changelog of the component.

Should it be in the 6.4 changelog or should I create a 7.1 one ?

**Comment by nicolas-grekas** [comment]
7.1 indeed now

File: src/Symfony/Component/HttpKernel/Tests/EventListener/ErrorListenerTest.php [hunk 3]
```diff
@@ -244,6 +244,19 @@ public function testCSPHeaderIsRemoved()
         $this->assertFalse($response->headers->has('content-security-policy'), 'CSP header has been removed');
     }
 
+    public function testTerminated(): void
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/EventListener/ErrorListenerTest.php]:
```suggestion
    public function testTerminating(): void
```

File: src/Symfony/Component/HttpKernel/Tests/EventListener/ErrorListenerTest.php [hunk 4]
```diff
@@ -244,6 +244,19 @@ public function testCSPHeaderIsRemoved()
...
+    {
+        $listener = new ErrorListener('foo', $this->createMock(LoggerInterface::class));
+
+        $kernel = $this->createMock(HttpKernelInterface::class);
+        $kernel->expects($this->never())->method('handle');
+
+        $request = Request::create('/');
+
+        $event = new ExceptionEvent($kernel, $request, HttpKernelInterface::MAIN_REQUEST, new \Exception('foo'), true);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/EventListener/ErrorListenerTest.php:256]:
```suggestion
        $event = new ExceptionEvent($kernel, $request, HttpKernelInterface::MAIN_REQUEST, new \Exception('foo'), isKernelTerminating: true);
```

File: UPGRADE-7.1.md [hunk 5]
```diff
@@ -0,0 +1,7 @@
+UPGRADE FROM 7.0 to 7.1
+=======================
+
+HttpKernel
+-----
+
+* `ExceptionEvent` now takes an optional `$isKernelTerminating` parameter
```
Comment (nicolas-grekas) [inline UPGRADE-7.1.md]:
```suggestion
 * `ExceptionEvent` now takes an optional `$isKernelTerminating` parameter
```

File: UPGRADE-7.1.md [hunk 6]
```diff
@@ -0,0 +1,7 @@
+UPGRADE FROM 7.0 to 7.1
+=======================
+
+HttpKernel
+-----
```
Comment (nicolas-grekas) [inline UPGRADE-7.1.md]:
```suggestion
----------
```

**Review by nicolas-grekas — APPROVED** [review]

File: UPGRADE-7.1.md (hunk 5 above)
Comment (VincentLanglet) [reply UPGRADE-7.1.md]: Done

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @VincentLanglet.

File: UPGRADE-7.1.md [hunk 7]
```diff
@@ -0,0 +1,7 @@
+UPGRADE FROM 7.0 to 7.1
+=======================
+
+HttpKernel
+----------
+
+ * `ExceptionEvent` now takes an optional `$isKernelTerminating` parameter
```
Comment (OskarStark) [inline UPGRADE-7.1.md:7]: Shouldn't we add this to the CHANGELOG instead to the upgrade guide, as this is an optional one?
