### PR TITLE
[Workflow] Added `Registry::has()` to check if a workflow exists

### LINKED ISSUE #34584: Workflow component should allow to check if object has a workflow defined
**Description**  
Currently `Symfony\Component\Workflow\Registry` allows one to `get` a workflow associated with an object, but throws an exception if there is none.

In my case, I'd like to create a `Normalizer` for all my objects that have a workflow to add additional data to them. However, this check requires me to either mark all entities with workflow enabled with an additional interface (which is fine for me as a workaround) or accept the cost of creating exceptions all the time.

**Example**  
I've got a `Normalizer` class:
```php
<?php declare(strict_types=1);

namespace App\Serializer\Normalizer;

use ApiPlatform\Core\JsonLd\Serializer\ItemNormalizer;
use Symfony\Component\Serializer\Normalizer\ContextAwareNormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Workflow\Registry;
use Symfony\Component\Workflow\Transition;

class WorkflowEnabledNormalizer implements NormalizerInterface, NormalizerAwareInterface, ContextAwareNormalizerInterface
{
    use NormalizerAwareTrait;

    private const WORKFLOW_CHECKED_ALREADY = 'WORKFLOW_CHECKED_ALREADY';

    /**
     * @var Registry
     */
    private $workflowRegistry;

    public function __construct(Registry $workflowRegistry)
    {
        $this->workflowRegistry = $workflowRegistry;
    }

    public function supportsNormalization($data, $format = null, array $context = [])
    {
        return $data instanceof WorkflowEnabledInterface && !($context[self::WORKFLOW_CHECKED_ALREADY] ?? false);
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $normalized = $this->normalizer->normalize($object, $format, $context + [self::WORKFLOW_CHECKED_ALREADY => true]);

        if (is_array($normalized)) {
            $workflow = $this->workflowRegistry->get($object);
            $transitions = $workflow->getEnabledTransitions($object);
            $transitions = array_map(function (Transition $transition): string {
                return $transition->getName();
            }, $transitions);
            switch ($format) {
                case ItemNormalizer::FORMAT:
                    $normalized['@transitions'] = $transitions;
                    break;
                default:
                    $normalized['__transitions'] = $transitions;
                    break;
            }
        }

        return $normalized;
    }
}
```

I'd like to have `supportsNormalization` method to become instead (or similar):
```
public function supportsNormalization($data, $format = null, array $context = [])
{
   return !($context[self::WORKFLOW_CHECKED_ALREADY] ?? false) && $this->workflowRegistry->has($data);
}
```

Is it worthwile?

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #34584
| License       | MIT
| Doc PR        |

---

Allow to use
```php
$registry->has($subject);
// or 
$registry->has($subject, 'workflow_a')
```

### CODE REVIEW

File: src/Symfony/Component/Workflow/Registry.php [hunk 1]
```diff
@@ -27,14 +27,25 @@ public function addWorkflow(WorkflowInterface $workflow, WorkflowSupportStrategy
...
+
     /**
      * @return Workflow
      */
     public function get(object $subject, string $workflowName = null)
     {
         $matched = [];
 
-        foreach ($this->workflows as list($workflow, $supportStrategy)) {
+        foreach ($this->workflows as [$workflow, $supportStrategy]) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Workflow/Registry.php]: cs changes are for lower branches

Comment (lyrixx) [reply src/Symfony/Component/Workflow/Registry.php]: Fixed

**Comment by javiereguiluz** [comment]
@lyrixx thanks for this contribution. In order to make this ready to be documented, could you please add some little example to the pull request description. Also, please tell us if there are some things to keep in mind about this feature (e.g. edge cases where it doesn't work, etc.) Thanks!

**Comment by lyrixx** [comment]
@javiereguiluz I'm not sure it worth documenting it. This method is discoverable easily with autocomplete and It make what it is supposed to without edge case. Anyway I added a s mall example
