### PR TITLE
[FrameworkBundle] ensure that all supported e-mail validation modes can be configured

### LINKED ISSUE #60352: Error 500 if "framework.validation.email_validation_mode" is set to "html5-allow-no-tld"
### Symfony version(s) affected

7.2.5

### Description

According to the docs (https://symfony.com/doc/current/reference/configuration/framework.html#email-validation-mode), the default validation mode can be changed to one of the values supported by the email validator, which are (according to this page: https://symfony.com/doc/current/reference/constraints/Email.html#mode) `html5`, `html5-allow-no-tld`, `strict`.

But when I try to change the default value to `html5-allow-no-tld`, I get a 500 error with this message:

> The value "html5-allow-no-tld" is not allowed for path "framework.validation.email_validation_mode". Permissible values: "html5", "loose", "strict"

I think there is probably a mismatch between the values expected by the validator and the ones allowed by the framework config.

### How to reproduce

Change the `framework.validation.email_validation_mode` config to `html5-allow-no-tld`.

### Possible Solution

I believe this line might be the problem: https://github.com/symfony/symfony/blob/f6385e959096abc9aa1d40866c03ffea1ee738e1/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L1021

### Additional Context

Image

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60352
| License       | MIT

this update was forgotten when adding the `html5-allow-no-tld` e-mail validation mode in #47872

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 1]
```diff
@@ -1066,7 +1067,7 @@ private function addValidationSection(ArrayNodeDefinition $rootNode, callable $e
                             ->validate()->castToArray()->end()
                         ->end()
                         ->scalarNode('translation_domain')->defaultValue('validators')->end()
-                        ->enumNode('email_validation_mode')->values(['html5', 'loose', 'strict'])->end()
+                        ->enumNode('email_validation_mode')->values(Email::VALIDATION_MODES)->end()
```
Comment (GromNaN) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: `loose` is no longer allowed in the config, but this value is already rejected by the constraint class.

https://github.com/symfony/symfony/blob/ed0a2358835f87ae188cebee042009fedea2cc32/src/Symfony/Component/Validator/Constraints/Email.php#L28-L30

But this value is still used by default: https://github.com/symfony/symfony/blob/6b4f603edbd2bee7d340bdb6e57cf2b9c656096b/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1660-L1662

Is there a bug here that makes this config required?

Comment (xabbuh) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: This depends on the Symfony version you are browsing. The `loose` mode was deprecated in 6.2 that's why you don't see it anymore in the `7.3` branch. And yes, I think being able to still configure it through the semantic configuration also is a bug.

Comment (xabbuh) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: but we should probably indeed make sure that applications still using `loose` don't break with the next patch release (as long as you don't use the `Email` constraint that's probably not a real issue today)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 2]
```diff
@@ -1066,7 +1067,7 @@ private function addValidationSection(ArrayNodeDefinition $rootNode, callable $e
                             ->validate()->castToArray()->end()
                         ->end()
                         ->scalarNode('translation_domain')->defaultValue('validators')->end()
-                        ->enumNode('email_validation_mode')->values(['html5', 'loose', 'strict'])->end()
+                        ->enumNode('email_validation_mode')->values(Email::VALIDATION_MODES + ['loose'])->end()
```
Comment (Kocal) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:1070]: I think we must check if class `Email` exists before using it, it broke our dev-tests suite on Symfony UX https://github.com/symfony/ux/actions/runs/14882498252/job/41793658394?pr=2714

Comment (Kocal) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:1070]: Opened https://github.com/symfony/symfony/pull/60373
