### PR TITLE
[HttpKernel] Do not override max_redirects option in HttpClientKernel

### LINKED ISSUE #38207: Http redirects are not followed when using caching http client
**Symfony version(s) affected**: `^4.3.0`

**Description**  

I use the http client for a `GET` request. By default an instance of `Symfony\Component\HttpClient\HttpClient` follows redirects (by default up to 20). When using the `Symfony\Component\HttpClient\CachingHttpClient` every redirect leads to an exception.

The issue is caused by the `Symfony\Component\HttpKernel\HttpClientKernel` which overrides the `max_redirects` option:

https://github.com/symfony/symfony/blob/9c8cd0827f6fab9bf840b7fd2940bcbe1b16e75e/src/Symfony/Component/HttpKernel/HttpClientKernel.php#L53-L57

**How to reproduce**  
```php
<?php

$client = Symfony\Component\HttpClient\HttpClient::create();
$cachingClient = new Symfony\Component\HttpClient\CachingHttpClient(
    $client,
    new Symfony\Component\HttpKernel\HttpCache\Store('/path/to/the/cache') 
);

// Work as expectede
$client->request(
    'GET', 
    // Redirect to https://api.github.com/repositories/109533757/git/matching-refs/tags/ happens here
    'https://api.github.com/repos/humbug/box/git/matching-refs/tags/', 
    ['headers' => ['Authorization' => 'token XXX']
);

// Throws Symfony\Component\HttpClient\Exception\RedirectionException
$cachingClient->request(
    'GET', 
    // Redirect to https://api.github.com/repositories/109533757/git/matching-refs/tags/ happens here
    'https://api.github.com/repos/humbug/box/git/matching-refs/tags/', 
    ['headers' => ['Authorization' => 'token XXX']
);

```

**Additional context**  

* https://github.com/symfony/symfony/pull/30625

### PR DESCRIPTION
**Pull request by dmolineus**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38207
| License       | MIT
| Doc PR        | -

As [proposed](https://github.com/symfony/symfony/issues/38207#issuecomment-693382336) by @nicolas-grekas this pull request removes the `max_redirects` setting in the `\Symfony\Component\HttpKernel\HttpClientKernel::handle` method.

It solves the issue that requests made by the `\Symfony\Component\HttpClient\CachingHttpClient` wouldn't follow redirects as described in the linked issue.

### CODE REVIEW

File: src/Symfony/Component/HttpKernel/Tests/HttpClientKernelTest.php [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+{
+    public function testHandlePassesMaxRedirectsHttpClientOption()
+    {
+        $request = new Request();
+        $request->attributes->set('http_client_options', ['max_redirects' => 50]);
+
+        $response = $this->getMockBuilder(ResponseInterface::class)->getMock();
+        $response->expects($this->once())->method('getStatusCode')->willReturn(200);
+
+        $client = $this->getMockBuilder(HttpClientInterface::class)->getMock();
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/HttpClientKernelTest.php:30]: in order to use these classes, you need to list symfony/http-client in the composer.json file of HttpKernel (this should fix tests, they fail currently)

Comment (dmolineus) [reply src/Symfony/Component/HttpKernel/Tests/HttpClientKernelTest.php:30]: Thanks for pointing it out. First time that I contribute to symfony. :-)

**Comment by dmolineus** [comment]
Failing integration test `AmqpExtIntegrationTest` seems to be unrelated.

File: src/Symfony/Component/HttpKernel/Tests/HttpClientKernelTest.php (hunk 1 above)
Comment (dmolineus) [reply src/Symfony/Component/HttpKernel/Tests/HttpClientKernelTest.php:30]: I only added `symfony/http-client-contracts` as the real implementation isn't required for the test.

File: src/Symfony/Component/HttpKernel/composer.json [hunk 2]
```diff
@@ -19,6 +19,7 @@
         "php": ">=7.1.3",
         "symfony/error-handler": "^4.4",
         "symfony/event-dispatcher": "^4.4",
+        "symfony/http-client-contracts": "^4.4",
```
Comment (fabpot) [inline src/Symfony/Component/HttpKernel/composer.json:22]: Constraint is wrong here, should be `^1.1|^2`

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/HttpKernel/HttpClientKernel.php [hunk 3]
```diff
@@ -35,7 +35,7 @@ final class HttpClientKernel implements HttpKernelInterface
 
     public function __construct(HttpClientInterface $client = null)
     {
-        if (!class_exists(HttpClient::class)) {
+        if (null === $client && !class_exists(HttpClient::class)) {
```
Comment (fabpot) [inline src/Symfony/Component/HttpKernel/HttpClientKernel.php:38]: This should be reverted, right?

File: src/Symfony/Component/HttpKernel/composer.json (hunk 2 above)
Comment (dmolineus) [reply src/Symfony/Component/HttpKernel/composer.json]: Fixed with 1cc8fc2.

File: src/Symfony/Component/HttpKernel/HttpClientKernel.php (hunk 3 above)
Comment (dmolineus) [reply src/Symfony/Component/HttpKernel/HttpClientKernel.php:38]: Don't think so. There isn't any reason to force an instance of the `HttpClient` when the constructor allows any implementation of the `HttpClientInterface`.

Same check exists here, btw:
https://github.com/symfony/symfony/blob/8d450130e0422a8e056a0667dd730300f6be7a73/src/Symfony/Component/BrowserKit/HttpBrowser.php#L33-L35

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/HttpKernel/HttpClientKernel.php (hunk 3 above)
Comment (fabpot) [reply src/Symfony/Component/HttpKernel/HttpClientKernel.php:38]: Understood, thanks.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @dmolineus.
