### PR TITLE
[HttpKernel] Refine `ControllerEvent::getAttributes()` and `ControllerArgumentsEvent::getAttributes()` return types

### LINKED ISSUE #61722: [HttpKernel] Weak return type definition for method `ControllerEvent::getAttributes()` when passing non-null argument
### Symfony version(s) affected

6.4.25

### Description

To get controller attributes via the `ControllerEvent::getAttributes()` method passing the class name of the requested attribute, the result is described as `list<object>`. Although the method has an extended description of types and the result can be described more precisely.

### How to reproduce

```php
class ExampleEventListener
{
    #[Symfony\Component\EventDispatcher\Attribute\AsEventListener]
    public function onKernelController(Symfony\Component\HttpKernel\Event\ControllerEvent $event): void
    {
        foreach ($event->getAttributes(Symfony\Component\Routing\Attribute\Route::class) as $route) {
            $route->getName(); // PHPStan error: Call to an undefined method object::getName().
        }
    }
}
```

A more interactive example with simplified models:
https://phpstan.org/r/70b4d523-1efb-4503-8110-5895a65618f9

### Possible Solution

Change the method PHPDoc so that the return type is more strict.

### Additional Context

This is not an error. It is a type description issue.

### PR DESCRIPTION
**Pull request by 7-zete-7**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #61722
| License       | MIT

The return type for the `Symfony\Component\HttpKernel\Event\ControllerEvent::getAttributes()` method is refined so that when the `$className` argument is passed, the return type matches the passed list of objects of the passed class.

### CODE REVIEW

**Comment by stof** [comment]
This should also be done on `ControllerArgumentsEvent`, which has a proxy method

**Comment by stof** [comment]
And as this is not fixing a bug but improving type declarations for static analysis, it should target the 7.4 branch.

File: src/Symfony/Component/HttpKernel/Event/ControllerEvent.php [hunk 1]
```diff
@@ -79,13 +79,13 @@ public function setController(callable $controller, ?array $attributes = null):
...
-     * @template T of class-string|null
+     * @template T of object
      *
-     * @param T $className
+     * @param class-string<T>|null $className
      *
      * @return array<class-string, list<object>>|list<object>
      *
-     * @psalm-return (T is null ? array<class-string, list<object>> : list<object>)
+     * @psalm-return ($className is null ? array<class-string, list<object>> : list<T>)
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Event/ControllerEvent.php]: let's merge this line with the existing `@return` one also while rebasing on 7.4

**Comment by 7-zete-7** [comment]
Thanks for the review!

I'll make the suggested edits tomorrow.

File: src/Symfony/Component/HttpKernel/Event/ControllerEvent.php (hunk 1 above)
Comment (7-zete-7) [reply src/Symfony/Component/HttpKernel/Event/ControllerEvent.php]: Merged the tags

**Comment by nicolas-grekas** [comment]
Thank you @7-zete-7.
