### PR TITLE
[Messenger] Route decode failures through failure handling

### LINKED ISSUE #44117: [Messenger] MessageDecodingFailedException should not delete message from queue
### Symfony version(s) affected

All

### Description

`MessageDecodingFailedException` should not delete a message from the queue.

```
try {
    $envelope = $this->serializer->decode([
        'body' => $sqsEnvelope['body'],
        'headers' => $sqsEnvelope['headers'],
    ]);
} catch (MessageDecodingFailedException $exception) {
    $this->connection->delete($sqsEnvelope['id']);

    throw $exception;
}
```

### Issues it causes

- Since decoding is not exactly reverse of encoding with arrays (int vs string keys), legitimate messages end up being dropped.
- Any other kind of dev ops error can mess up the decoding temporarily.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #44117, also related to #39622
| License       | MIT

Previously, when a transport could not decode a message, `MessageDecodingFailedException` was thrown inside receivers' `get()`, causing the message to be deleted from the queue with no retry or DLQ routing.

This PR routes decode failures through the normal failure-handling path instead of silently losing messages.

This changes a bit the contracts of serializers: they should now return `Envelope<MessageDecodingFailedException>` on decode failure, wrapping the raw encoded envelope. Throwing is still supported for BC with custom serializers - receivers catch and wrap it as a fallback.

A new `DecodeFailedMessageMiddleware` sits early in the default middleware stack (before `failed_message_processing_middleware`). When it encounters an envelope whose message is a `MessageDecodingFailedException`, it:

1. Determines the original transport name to look up the correct serializer.
2. Re-decodes the raw payload; if decoding still fails, the `MessageDecodingFailedException` is thrown so that standard retry/DLQ handling kicks in.
3. If decoding succeeds (e.g. after a deployment that adds the missing class), merges all stamps from the wrapping envelope onto the freshly decoded one and continues through the stack normally.

Receivers no longer delete-then-throw. Instead they yield the wrapped envelope with the same stamps as a successful decode, so `ack()`/`reject()` work correctly downstream. The old catch-and-throw path is kept only as a BC fallback for custom serializers that still throw.

A message that cannot be decoded is therefore no longer lost. It travels through the bus as a `MessageDecodingFailedException`, hits the failure/retry infrastructure like any other failed message, and is automatically retried (triggering `DecodeFailedMessageMiddleware` again) once the serializer or class definition is fixed.

### CODE REVIEW

**Comment by alex-dev** [comment]
### Implementation issue

Failed message will be serialized wrapped in `SerializedEnvelopeMessage` by the failure transport, which will make it impossible to handle in the future. Sure the message was not deleted, it is still unusable by the application.

### About the approach

This feels like we are trying to bridge two approaches.
1 - `TransportInterface` serializing
2 - Middleware serialization
Even if we don't implement the full middleware based serialization, being sure we want to go this way would ensure we are not adding more complexity in a component showing design issues.

Lets consider what we now need to add a new transport: a `TransportInterface` implementation which must now use a `SerializerInterface`. Previously, it wasn't required.
Lets consider all the potential states an envelope can now have: full PHP object with non-sendable stamps, serialized, full PHP object with sendable stamps only. These states can all transit through the middleware stack without being properly documented.

I worry we are adding accidental complexity rather than reducing it.

**Comment by nicolas-grekas** [comment]
Thanks for the review @alex-dev this should be improved now. Can you please have a second look?

File: src/Symfony/Component/Messenger/Bridge/AmazonSqs/Transport/AmazonSqsReceiver.php [hunk 1]
```diff
@@ -38,32 +40,32 @@ public function __construct(
...
         } catch (HttpException $e) {
             throw new TransportException($e->getMessage(), 0, $e);
         }
-        if (null === $sqsEnvelope) {
-            return;
-        }
+
+        $stamps = [
+            new AmazonSqsReceivedStamp($sqsEnvelope['id']),
+            new TransportMessageIdStamp($sqsEnvelope['id']),
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Bridge/AmazonSqs/Transport/AmazonSqsReceiver.php:51]: was likely forgotten

**Comment by nicolas-grekas** [comment]
Now ready for close human review, I did my part :)

**Review by alex-dev — COMMENTED** [review]
It will work. Separation of responsibility is a bit odd. Would it be possible to handle failures all in the serializer rather than in the transport?

**Comment by nicolas-grekas** [comment]
The serializer can't route failures through the bus on its own: it has no access to that infrastructure. What it can do is throw, which is what it already does. The transport is the natural catch point since it owns the `decode()` call and the raw payload. The result (`FailedEnvelopeDecodingMessage`) is a thin value object with no transport knowledge; the actual re-decode logic lives in the middleware, which does have bus context. So responsibility is actually well separated: transport catches + wraps, middleware re-decodes + continues.

The only way to move this concern really self-contained in the serializer would be to make it return an `Envelope<FailedEnvelopeDecodingMessage>` on failure instead of throwing. That'b be a BC break to `SerializerInterface`, and that'd force all custom serializers to know about `FailedEnvelopeDecodingMessage`. It'd conflate "I decoded this" with "I failed to decode this" in the same return type. That'd be worse separation IMHO, not better.

**Comment by alex-dev** [comment]
I still think a clean result type would be cleaner than an exception. Something like `Envelope<object{...}|object{error:Throwable,raw:string}>` would be good enough. No existing transport need to care about that one. Only the middleware throwing the throwable and the serializer need to care about these changes.

So library adding transports don't need to update, library adding serializer only need to update if they care about decoding failure in theory.

Also, I'd argue `PhpSerializer` is already shipping decoding failures on the `Envelope` in some cases: https://github.com/symfony/symfony/blob/8c1ab342d3ee5dc53a2c33f222a1ea5331e11106/src/Symfony/Component/Messenger/Transport/Serialization/PhpSerializer.php#L110C1-L111C1
Standardizing this behaviour would be a good simplification.

**Comment by nicolas-grekas** [comment]
@alex-dev thanks for the push back. I've now implement both strategies together, so that we get the best of both worlds. See also updated PR description.

**Comment by B-Galati** [comment]
Thank you for this! It will make Symfony Messenger more reliable :+1:
