### PR TITLE
[Serializer] Fix caching context-aware encoders/decoders in ChainEncoder/ChainDecoder

### LINKED ISSUE #38270: [Serializer] ChainEncoder does not honor context support check if called repeatedly
`ChainEncoder#getEncoder` method reads:

```php
        if (isset($this->encoderByFormat[$format])
            && isset($this->encoders[$this->encoderByFormat[$format]])
        ) {
            return $this->encoders[$this->encoderByFormat[$format]];
        }

        foreach ($this->encoders as $i => $encoder) {
            if ($encoder->supportsEncoding($format, $context)) {
                $this->encoderByFormat[$format] = $i;

                return $encoder;
            }
        }
```

If that method is called more than once with different `$context` arguments the wrong encoder could be returned because `$encoder->supportsEncoding($format, $context)` is not called again.

Hence, I disabled the first check and `return` statement and things worked like a charm.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38270
| License       | MIT
| Doc PR        | -

As proposed in https://github.com/symfony/symfony/pull/43231#issuecomment-1202259776
Will require #47150 on 6.1 until a proper solution is implemented, hopefully in 6.2.

### CODE REVIEW

File: src/Symfony/Component/Serializer/Encoder/ChainDecoder.php [hunk 1]
```diff
@@ -67,9 +67,13 @@ private function getDecoder(string $format, array $context): DecoderInterface
             return $this->decoders[$this->decoderByFormat[$format]];
         }
 
+        $cache = true;
         foreach ($this->decoders as $i => $decoder) {
+            $cache = $cache && !$decoder instanceof ContextAwareDecoderInterface;
```
Comment (Guite) [inline src/Symfony/Component/Serializer/Encoder/ChainDecoder.php:72]: Sure you want to override the value defined in the outer scope? Then it would result in `false` for all decoders after it has been `false` for one.

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Encoder/ChainDecoder.php:72]: Sure: as soon as a non-context-aware decoder is found, we cannot cache any of them for the specified $format.

Comment (Guite) [reply src/Symfony/Component/Serializer/Encoder/ChainDecoder.php:72]: Okay.

**Review by chalasr — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @nicolas-grekas & @Guite
