### PR TITLE
[Translation] Throw exception if symfony/finder is not installed for PhpExtractor

### LINKED ISSUE #42788: [Translation] Can not use PhpExtractor standalone (missing symfony/finder)
**Symfony version(s) affected**: N/A

**Description**
`PhpExtractor#extractFromDirectory()` uses `Symfony\Component\Finder\Finder` class which is not present if `symfony/translation` is used standalone and no other dependency requires `symfony/finder`. That's because `symfony/finder` is only a dev dependency of `symfony/translation`.

**How to reproduce**
Install `symfony/translation` and try to use `PhpExtractor#extract()`.

**Possible Solution**
Move `symfony/finder` from `require-dev` to `require` in `composer.json`.

**Workaround**

Require `symfony/finder` in my application.

### PR DESCRIPTION
**Pull request by dakur**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | #42788 
| License       | MIT
| Doc PR        | N/A

Closes #42788

### CODE REVIEW

**Comment by dakur** [comment]
Oh, according to @carsonbot I should target 4.4. Is that right? If so, I will make new PR, but just to be sure I've understood it well.

File: src/Symfony/Component/Translation/Extractor/PhpExtractor.php [hunk 1]
```diff
@@ -329,6 +329,10 @@ protected function canBeExtracted(string $file)
      */
     protected function extractFromDirectory($directory)
     {
+        if (!class_exists(Finder::class)) {
+            throw new \LogicException('You cannot use "Symfony\Component\Finder\Finder" as the "symfony/finder" package is not installed. Try running "composer require symfony/finder".');
```
Comment (stof) [inline src/Symfony/Component/Translation/Extractor/PhpExtractor.php]: this should rather say that we cannot use the PhpExtractor IMO, as this is what the dev tried to use.

Comment (dakur) [reply src/Symfony/Component/Translation/Extractor/PhpExtractor.php]: @stof When you need to use `PhpExtractor`, seeing a message "You can't use `PhpExtractor`" is not much helpful (you already know it from that you see an error). You need to know what to do – thus this sentence. If you look to the related issue, you see that someone pointed me that this message is already used throughout Symfony.

Comment (stof) [reply src/Symfony/Component/Translation/Extractor/PhpExtractor.php]: Well, the message should say `You cannot use ...\PhpExtractor as the "symfony/finder" package is not installed. Try running "composer require symfony/finder".`. What the user is trying to use is not the Finder class, so telling them they cannot use the Finder class would confuse them about why we tell them they cannot use it.
See the search link given by @ro0NL in the issue. My suggestion is consistent with all other usages. We always tell you that you cannot use the current class, not the dependent class (that Symfony tries to use but cannot find)

Comment (dakur) [reply src/Symfony/Component/Translation/Extractor/PhpExtractor.php]: I see, I was stuck inside the problem and didn't see the context from above anymore, sorry.

Can you please answer me also [my question](https://github.com/symfony/symfony/pull/42808#issuecomment-909148560) about branches so that I could fix the message in already correct branch? Thank you.

**Comment by OskarStark** [comment]
Yes, a bugfix should target 4.4

**Comment by derrabus** [comment]
> Oh, according to @carsonbot I should target 4.4. Is that right? If so, I will make new PR, but just to be sure I've understood it well.

No, let's keep 5.4 as target. I'd not file this as a bug but as a DX improvement.

File: src/Symfony/Component/Translation/Extractor/PhpExtractor.php (hunk 1 above)
Comment (dakur) [reply src/Symfony/Component/Translation/Extractor/PhpExtractor.php]: Fixed in 78341cd933aa192a51d07e29621efb5b2cff3afe. By the way wouldn't it be better to use `self::class` instead of manually typing whole class name?

**Review by OskarStark — APPROVED** [review]

File: src/Symfony/Component/Translation/Extractor/PhpExtractor.php [hunk 2]
```diff
@@ -329,6 +329,10 @@ protected function canBeExtracted(string $file)
      */
     protected function extractFromDirectory($directory)
     {
+        if (!class_exists(Finder::class)) {
+            throw new \LogicException('You cannot use "Symfony\Component\Translation\Extractor\PhpExtractor" as the "symfony/finder" package is not installed. Try running "composer require symfony/finder".');
```
Comment (derrabus) [inline src/Symfony/Component/Translation/Extractor/PhpExtractor.php]:
```suggestion
            throw new \LogicException(sprintf('You cannot use "%s" as the "symfony/finder" package is not installed. Try running "composer require symfony/finder".', static::class));
```

**Comment by derrabus** [comment]
Would it make sense to do the same in the `TranslationReader` class?

**Review by derrabus — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @dakur.
