### PR TITLE
[Console] Fix ConsoleEvents::SIGNAL subscriber dispatch

### LINKED ISSUE #45332: [Console] ConsoleEvents::SIGNAL subscriber not called
### Symfony version(s) affected

5.2+

### Description

The (awesome) console signal handling introduced in #33729 and #37827 seems to have some issues (or maybe it's just me :smiley_cat: ) with subscriber events:

- Subscriber `ConsoleEvents::SIGNAL` events do not get called, but events such as `ConsoleEvents::TERMINATE` do
- Listener events (command implementing `SignalableCommandInterface`) work, with one caveat;
  - if a **subscriber** exists, it will be called and the command's discrete handler ignored

### How to reproduce

1. Create a Symfony project `symfony new --webapp symfony-pcntl-test `

2. Build the following classes

```php
// src/Command/AbstractSignalCommand.php

abstract class AbstractSignalCommand extends Command
{
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $io->title("Starting {$this->getName()} command execution");

        for ($i = 0; $i <10; ++$i) {
            $io->writeln('Tick ' . $i);
            sleep(1);
        }

        $io->success('Normal exit from command.');

        return Command::SUCCESS;
    }
}
```

```php
// src/Command/SignalListenerCommand.php

#[AsCommand(
    name: 'app:signal:listener',
)]
class SignalListenerCommand extends AbstractSignalCommand implements SignalableCommandInterface
{
    public function getSubscribedSignals(): array
    {
        return [SIGINT];
    }

    public function handleSignal(int $signal): void
    {
        if (SIGINT === $signal) {
            dump('Caught a listener SIGINT');
            exit;
        }
    }
}
```

```php
// src/Command/SignalSubscriberCommand.php

#[AsCommand(
    name: 'app:signal:subscriber',
)]
class SignalSubscriberCommand extends AbstractSignalCommand
{
}
```

```php
// src/EventSubscriber/CommandSignalSubscriber.php

class CommandSignalSubscriber implements EventSubscriberInterface
{
    public function onConsoleSignal(ConsoleSignalEvent $event): void
    {
        if ($event->getHandlingSignal() === SIGINT) {
            dump('Caught a !!!subscriber!!! SIGINT');
            exit;
        }
    }

    public function onConsoleTerminate(ConsoleTerminateEvent $event)
    {
        dump('Handling normal termination event');
    }

    public static function getSubscribedEvents(): array
    {
        return [
            ConsoleEvents::SIGNAL => 'onConsoleSignal',
            ConsoleEvents::TERMINATE => 'onConsoleTerminate',
        ];
    }
}
```

3. Check event dispatcher

```shell
$ bin/console debug:event-dispatcher console.signal
# ...
 ------- ---------------------------------------------------------------- ---------- 
  Order   Callable                                                         Priority  
 ------- ---------------------------------------------------------------- ---------- 
  #1      App\EventSubscriber\CommandSignalSubscriber::onConsoleSignal()   0         
 ------- ---------------------------------------------------------------- -----------
```

4. Run the listener enabled command and emit a CTRL+c
```shell
$ bin/console app:signal:listener

Starting app:signal:listener command execution
==============================================

Tick 0
Tick 1
^C"Caught a !!!subscriber!!! SIGINT"
```

**NOTE:** The handling of the signal is done in the **subscriber** here, but removing `ConsoleEvents::SIGNAL` from `CommandSignalSubscriber::getSubscribedEvents` will cause the handling to be done by the listener.

5. Run the subscriber enabled command and emit a CTRL+c
```shell
$ bin/console app:signal:subscriber

Starting app:signal:subscriber command execution
================================================

Tick 0
Tick 1
^C
```

**NOTE:** Nothing handles the signal.

### Possible Solution

_No response_

### Additional Context

- Tested on Symfony v6.0.4

### PR DESCRIPTION
**Pull request by GwendolenLynch**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45332
| License       | MIT

### CODE REVIEW

**Comment by derrabus** [comment]
Thank you for your PR! Can you please add a test hat covers your change?

**Comment by GwendolenLynch** [comment]
Added @derrabus. The act of writing the tests showed up some missing bits, so thank you for the nudge.

Changed
- Move extracted code back into method and change some of the selection logic.
- For tests, use `SIGUSRx` instead of `SIGALRM` as the later will cause an exit when there are no more listeners, and we only need to test that the signal was processed by the listener.

Please let me know what changes you'd like made.

File: src/Symfony/Component/Console/Tests/ApplicationTest.php [hunk 1]
```diff
@@ -2000,3 +2084,33 @@ protected function execute(InputInterface $input, OutputInterface $output): int
...
+        return SignalRegistry::isSupported() ? [\SIGUSR1] : [];
+    }
+
+    public function handleSignal(int $signal): void
+    {
+        $this->signaled = true;
+    }
+}
+
+class SignalEventSubscriber implements EventSubscriberInterface {
```
Comment (derrabus) [inline src/Symfony/Component/Console/Tests/ApplicationTest.php]:
```suggestion
class SignalEventSubscriber implements EventSubscriberInterface
{
```

Comment (GwendolenLynch) [reply src/Symfony/Component/Console/Tests/ApplicationTest.php]: Oops! :smile:

File: src/Symfony/Component/Console/Application.php [hunk 2]
```diff
@@ -1005,10 +1014,6 @@ protected function doRunCommand(Command $command, InputInterface $input, OutputI
                     });
                 }
             }
-
-            foreach ($command->getSubscribedSignals() as $signal) {
```
Comment (lyrixx) [inline src/Symfony/Component/Console/Application.php:1009]: Now it's not possible to register to a signal if the main application hasn't already registered some signals or I missed something?

Comment (GwendolenLynch) [reply src/Symfony/Component/Console/Application.php:1009]: One, or both, of us might be :thinking: :woman_shrugging: :smiley_cat: 

The loop & call to `$this->signalRegistry->register($signal, [$command, 'handleSignal']);` is still present above (on lines 996-998). 

What I have been struggling with is how to test exactly the scenario you describe … As I will happily include said test, and it can contribute to outcome of this debate/question. Help/suggestions most welcome!

Comment (fabpot) [reply src/Symfony/Component/Console/Application.php:1009]: @lyrixx Can you have a look at this one?

Comment (lyrixx) [reply src/Symfony/Component/Console/Application.php:1009]: I tested many scenario and everything seems OK. Sorry for the very long delay!

**Review by lyrixx — APPROVED** [review]
All good 👍🏼

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @GwendolenLynch.

File: src/Symfony/Component/Console/Application.php [hunk 3]
```diff
@@ -974,22 +974,31 @@ protected function doRunCommand(Command $command, InputInterface $input, OutputI
             }
         }
 
-        if ($command instanceof SignalableCommandInterface && ($this->signalsToDispatchEvent || $command->getSubscribedSignals())) {
-            if (!$this->signalRegistry) {
-                throw new RuntimeException('Unable to subscribe to signal events. Make sure that the `pcntl` extension is installed and that "pcntl_*" functions are not disabled by your php.ini\'s "disable_functions" directive.');
-            }
+        if ($this->signalsToDispatchEvent) {
+            $commandSignals = $command instanceof SignalableCommandInterface ? $command->getSubscribedSignals() : [];
+            $dispatchSignals = $this->dispatcher && $this->dispatcher->hasListeners(ConsoleEvents::SIGNAL);
```
Comment (helhum) [inline src/Symfony/Component/Console/Application.php:979]: $this->dispatcher is typed to be a `\Symfony\Contracts\EventDispatcher\EventDispatcherInterface`, but `hasListeners` is not part of that contract. 

This leads to our package breaking with the current branch version (5.4.x-dev in our case), since it does not fulfill the `\Symfony\Component\EventDispatcher\EventDispatcherInterface`

**Comment by helhum** [comment]
@GwendolenLynch @nicolas-grekas I added a comment regarding using `hasListeners`. Not sure if this was an intentional change, but wanted to let you know, that it breaks our package, that implements an event dispatcher that fulfills the PSR and SF contract interfaces.

**Comment by nicolas-grekas** [comment]
This should be fixed. Up for a PR?

File: src/Symfony/Component/Console/Application.php [hunk 4]
```diff
@@ -974,22 +974,31 @@ protected function doRunCommand(Command $command, InputInterface $input, OutputI
...
+                    $sttyMode = shell_exec('stty -g');
+
+                    foreach ([\SIGINT, \SIGTERM] as $signal) {
+                        $this->signalRegistry->register($signal, static function () use ($sttyMode) {
+                            shell_exec('stty '.$sttyMode);
+                        });
+                    }
+                }
+
+                foreach ($commandSignals as $signal) {
```
Comment (GromNaN) [inline src/Symfony/Component/Console/Application.php:996]: Is there any specific reason why the order of registration of signal handlers have been modified? This caused an issue https://github.com/symfony/symfony/issues/48205#issuecomment-1312839109

Comment (GwendolenLynch) [reply src/Symfony/Component/Console/Application.php:996]: I  can't remember my approach/reason at the time, but the test added in this PR should cover the use-case problem I had. 

Your fix #48210 is most probably correct.

Comment (GromNaN) [reply src/Symfony/Component/Console/Application.php:996]: Thanks you for reviewing.
