### PR TITLE
[DependencyInjection] Target Attribute must fail if the target does not exist

### LINKED ISSUE #48555: [DependencyInjection] Target Attribute must fail if the target does not exist
### Description

see: https://symfony.com/blog/new-in-symfony-5-3-service-autowiring-with-attributes#selecting-autowire-alias-with-attributes

If I create an http client: 
```yaml
    http_client:
        scoped_clients:
            githubApi:
                scope: 'https://api\.github\.com'
                headers:
                    Accept: 'application/vnd.github.v3+json'
```

And I want to inject it into my service, I can do:

```php

    public function __construct(
        #[Target('githubApi2')]
        private HttpClientInterface $something,
    ) {
    }
```

But oups, I made a typo. I wrote `githubApi2` instead of `githubApi`. But for Symfony it's OK. Instead it injects a new "blank" HttpClient (with no sane default configuration - no timeout for example).

IMHO, if one want to inject a specific target, the target **must** be validated. And if the target does not exist, because another developer renamed it, you **want** an exception. for this.

see this [comments](https://github.com/symfony/symfony/pull/40800#issuecomment-821301587) for a previous discussion.

But IMHO, if the naming is not exactly the same as the autowire alias, it's fine to not raise an exception. But in this very use case, you really want this alias. Not another one.

So I would expect an exception.

WDYT?

### Example

_No response_

### PR DESCRIPTION
**Pull request by rodmen**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #48555 
| License       | MIT
| Doc PR        | -

This change checks if an attribute is a Target to not auto bind with a new default object if the target name does not exists.
The existent behavior should be in charge of suggest possible options for a typo on the Target name.

I can't mark `allow edit by maintainers` I think because I'm open the PR from a organization repo.

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 1]
```diff
@@ -379,7 +378,6 @@ private function getAutowiredReference(TypedReference $reference, bool $filterTy
     {
         $this->lastFailure = null;
         $type = $reference->getType();
-
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: should be kept

**Review by nicolas-grekas — COMMENTED** [review]
Thanks for tackling this!
Here is my review as a diff.
(`TypeReference::getAttributes()` should return a collection of PHP attributes.)


<details>

```diff
diff --git a/src/Symfony/Component/DependencyInjection/Attribute/Target.php b/src/Symfony/Component/DependencyInjection/Attribute/Target.php
index 7751b3813b..560f7fe2f8 100644
--- a/src/Symfony/Component/DependencyInjection/Attribute/Target.php
+++ b/src/Symfony/Component/DependencyInjection/Attribute/Target.php
@@ -28,13 +28,16 @@ final class Target
         $this->name = lcfirst(str_replace(' ', '', ucwords(preg_replace('/[^a-zA-Z0-9\x7f-\xff]++/', ' ', $name))));
     }
 
-    public static function parseName(\ReflectionParameter $parameter): string
+    public static function parseName(\ReflectionParameter $parameter, self &$attribute = null): string
     {
+        $attribute = null;
+
         if (!$target = $parameter->getAttributes(self::class)[0] ?? null) {
             return $parameter->name;
         }
 
-        $name = $target->newInstance()->name;
+        $attribute = $target->newInstance();
+        $name = $attribute->name;
 
         if (!preg_match('/^[a-zA-Z_\x7f-\xff]/', $name)) {
             if (($function = $parameter->getDeclaringFunction()) instanceof \ReflectionMethod) {
diff --git a/src/Symfony/Component/DependencyInjection/CHANGELOG.md b/src/Symfony/Component/DependencyInjection/CHANGELOG.md
index d058d01e14..74e04a5713 100644
--- a/src/Symfony/Component/DependencyInjection/CHANGELOG.md
+++ b/src/Symfony/Component/DependencyInjection/CHANGELOG.md
@@ -8,6 +8,7 @@ CHANGELOG
  * Deprecate `PhpDumper` options `inline_factories_parameter` and `inline_class_loader_parameter`
  * Add `RemoveBuildParametersPass`, which removes parameters starting with a dot during compilation
  * Fail is Target attribute does not exists during compilation
+
 6.2
 ---
 
diff --git a/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php b/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php
index 03f3bd4aeb..cdf3ed470b 100644
--- a/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php
+++ b/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php
@@ -110,7 +110,7 @@ class AutowirePass extends AbstractRecursivePass
                     return $this->processAttribute($attribute, ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE !== $value->getInvalidBehavior());
                 }
 
-                $value = new TypedReference($value->getType(), $value->getType(), $value->getInvalidBehavior(), $attribute->name);
+                $value = new TypedReference($value->getType(), $value->getType(), $value->getInvalidBehavior(), $attribute->name, [$attribute]);
             }
             if ($ref = $this->getAutowiredReference($value, true)) {
                 return $ref;
@@ -320,7 +320,9 @@ class AutowirePass extends AbstractRecursivePass
             }
 
             $getValue = function () use ($type, $parameter, $class, $method) {
-                if (!$value = $this->getAutowiredReference($ref = new TypedReference($type, $type, ContainerBuilder::EXCEPTION_ON_INVALID_REFERENCE, Target::parseName($parameter), ['is_target_attr' => isset($parameter->getAttributes(Target::class)[0])]), false)) {
+                $name = Target::parseName($parameter, $target);
+
+                if (!$value = $this->getAutowiredReference($ref = new TypedReference($type, $type, ContainerBuilder::EXCEPTION_ON_INVALID_REFERENCE, $name, $target ? [$target] : []), false)) {
                     $failureMessage = $this->createTypeNotFoundMessageCallback($ref, sprintf('argument "$%s" of method "%s()"', $parameter->name, $class !== $this->currentId ? $class . '::' . $method : $method));
                     if ($parameter->isDefaultValueAvailable()) {
                         $value = clone $this->defaultArgument;
@@ -407,7 +409,7 @@ class AutowirePass extends AbstractRecursivePass
                 }
             }
 
-            if ($reference->getAttributes()['is_target_attr'] ?? false && !$this->container->has($name)) {
+            if ($reference->getAttributes()) {
                 return null;
             }
         }
@@ -534,9 +536,9 @@ class AutowirePass extends AbstractRecursivePass
             }
 
             $message = sprintf('has type "%s" but this class %s.', $type, $parentMsg ? sprintf('is missing a parent class (%s)', $parentMsg) : 'was not found');
-        } elseif ($reference->getAttributes()['is_target_attr'] ?? false) {
+        } elseif ($reference->getAttributes()) {
             $message = $label;
-            $label = sprintf('"#[Target(\'%s\')" on ', $reference->getName());
+            $label = sprintf('"#[Target(\'%s\')" on', $reference->getName());
         } else {
             $alternatives = $this->createTypeAlternatives($this->container, $reference);
             $message = $this->container->has($type) ? 'this service is abstract' : 'no such service exists';
diff --git a/src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php b/src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php
index 0039496d72..ace42c97b8 100644
--- a/src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php
+++ b/src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php
@@ -178,7 +178,7 @@ class ResolveBindingsPass extends AbstractRecursivePass
 
                 $typeHint = ltrim(ProxyHelper::exportType($parameter) ?? '', '?');
 
-                $name = Target::parseName($parameter);
+                $name = Target::parseName($parameter, $target);
 
                 if ($typeHint && \array_key_exists($k = preg_replace('/(^|[(|&])\\\\/', '\1', $typeHint).' $'.$name, $bindings)) {
                     $arguments[$key] = $this->getBindingValue($bindings[$k]);
```

</details>

**Comment by rodmen** [comment]
> Thanks for tackling this! Here is my review as a diff. (`TypeReference::getAttributes()` should return a collection of PHP attributes.)

Thanks for the clarification @nicolas-grekas .
I think of it that way, but I preferred not to modify the Target class on my first try.
I've apply the suggested changes.

Regarding the `if ($reference->getAttributes())` check in `AutowirePass::getAutowiredReference`, what do you think to pass `$parameter->getAttributes()` ([]ReflectionAttributes) as `TypedReference::$attributes` as create the TypedReference for that method using the object's class in the ID parameter?
That way, we allow you to use the attributes for other purposes if needed.

File: src/Symfony/Component/DependencyInjection/CHANGELOG.md [hunk 2]
```diff
@@ -7,7 +7,7 @@ CHANGELOG
  * Add options `inline_factories` and `inline_class_loader` to `PhpDumper::dump()`
  * Deprecate `PhpDumper` options `inline_factories_parameter` and `inline_class_loader_parameter`
  * Add `RemoveBuildParametersPass`, which removes parameters starting with a dot during compilation
-
+ * Fail is Target attribute does not exists during compilation
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/CHANGELOG.md]: please rebase and keep the blank line after this one while doing so

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 3]
```diff
@@ -320,9 +320,9 @@ private function autowireMethod(\ReflectionFunctionAbstract $reflectionMethod, a
             }
 
             $getValue = function () use ($type, $parameter, $class, $method) {
-                if (!$value = $this->getAutowiredReference($ref = new TypedReference($type, $type, ContainerBuilder::EXCEPTION_ON_INVALID_REFERENCE, Target::parseName($parameter)), false)) {
-                    $failureMessage = $this->createTypeNotFoundMessageCallback($ref, sprintf('argument "$%s" of method "%s()"', $parameter->name, $class !== $this->currentId ? $class.'::'.$method : $method));
-
+                $name = Target::parseName($parameter, $target);
+                if (!$value = $this->getAutowiredReference($ref = new TypedReference($type, $type, ContainerBuilder::EXCEPTION_ON_INVALID_REFERENCE, $name, $target ? [$target] : []), false)) {
+                    $failureMessage = $this->createTypeNotFoundMessageCallback($ref, sprintf('argument "$%s" of method "%s()"', $parameter->name, $class !== $this->currentId ? $class . '::' . $method : $method));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: please revert the changes on this line, cs is wrong

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 4]
```diff
@@ -532,6 +536,9 @@ private function createTypeNotFoundMessage(TypedReference $reference, string $la
             }
 
             $message = sprintf('has type "%s" but this class %s.', $type, $parentMsg ? sprintf('is missing a parent class (%s)', $parentMsg) : 'was not found');
+        } elseif ($reference->getAttributes()) {
+            $message = $label;
+            $label = sprintf('"#[Target(\'%s\')" on ', $reference->getName());
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: space after "on" must be removed

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 5]
```diff
@@ -408,6 +408,10 @@ private function getAutowiredReference(TypedReference $reference, bool $filterTy
                     }
                 }
             }
+
+            if ($reference->getAttributes() && !$this->container->has($name)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: I'm not sure about the `has()` check. Why is it needed?

**Comment by nicolas-grekas** [comment]
> Regarding the if ($reference->getAttributes()) check in AutowirePass::getAutowiredReference

I'm not sure that the situation you anticipate can exist so I wouldn't bother until it does.

BTW, it looks to me that the change near L110 that I proposed previously is needed. Is there a reason why you didn't borrow it?

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php (hunk 5 above)
Comment (rodmen) [reply src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: Fixed! was necessary on a previous version of my fix

File: src/Symfony/Component/DependencyInjection/CHANGELOG.md [hunk 6]
```diff
@@ -9,6 +9,7 @@ CHANGELOG
  * Add `RemoveBuildParametersPass`, which removes parameters starting with a dot during compilation
  * Add support for nesting autowiring-related attributes into `#[Autowire(...)]`
  * Deprecate undefined and numeric keys with `service_locator` config
+ * Fail is Target attribute does not exists during compilation
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/CHANGELOG.md]: typo: is => if and exists => exist

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 7]
```diff
@@ -332,9 +332,9 @@ private function autowireMethod(\ReflectionFunctionAbstract $reflectionMethod, a
             }
 
             $getValue = function () use ($type, $parameter, $class, $method) {
-                if (!$value = $this->getAutowiredReference($ref = new TypedReference($type, $type, ContainerBuilder::EXCEPTION_ON_INVALID_REFERENCE, Target::parseName($parameter)), false)) {
+                $name = Target::parseName($parameter, $target);
+                if (!$value = $this->getAutowiredReference($ref = new TypedReference($type, $type, ContainerBuilder::EXCEPTION_ON_INVALID_REFERENCE, $name, $target ? [$target] : []), false)) {
                     $failureMessage = $this->createTypeNotFoundMessageCallback($ref, sprintf('argument "$%s" of method "%s()"', $parameter->name, $class !== $this->currentId ? $class.'::'.$method : $method));
-
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php:337]: should be kept

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php [hunk 8]
```diff
@@ -1142,6 +1142,22 @@ public function testArgumentWithTarget()
...
+    public function testArgumentWithTypoTarget()
+    {
+        $container = new ContainerBuilder();
+
+        $container->register(BarInterface::class, BarInterface::class);
+        $container->register(BarInterface::class.' $iamgeStorage', BarInterface::class);
+        $container->register('with_target', WithTarget::class)
+            ->setAutowired(true);
+
+            try {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php]: bad indentation

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php [hunk 9]
```diff
@@ -1142,6 +1142,22 @@ public function testArgumentWithTarget()
...
+                (new AutowirePass())->process($container);
+            } catch (AutowiringFailedException $e) {
+                $this->assertSame('Cannot autowire service "with_target": "#[Target(\'imageStorage\')" on argument "$bar" of method "Symfony\Component\DependencyInjection\Tests\Fixtures\WithTarget::__construct()"', (string) $e->getMessage());
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php]: this should be replaced by a call to $this->expectException* before the call

File: src/Symfony/Component/DependencyInjection/CHANGELOG.md (hunk 6 above)
Comment (rodmen) [reply src/Symfony/Component/DependencyInjection/CHANGELOG.md]: thanks!

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 10]
```diff
@@ -332,9 +332,10 @@ private function autowireMethod(\ReflectionFunctionAbstract $reflectionMethod, a
...
+
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: white space must be removed :)

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php (hunk 10 above)
Comment (rodmen) [reply src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: Thanks for your patience and all comments!!!
Not my best day, but the next PR should be better

**Comment by nicolas-grekas** [comment]
(there's one test to fix though)

**Comment by rodmen** [comment]
> (there's one test to fix though)

Sorry @nicolas-grekas , I'm not realized on the approve and just pushed a commit for the test.

**Comment by nicolas-grekas** [comment]
One more change from https://fabbot.io/report/symfony/symfony/48707/9562119c360e8f00379181700559fbd7f053dc9c

Note that I would have happily made those simple changes myself but since I can't push to your fork, I must rely on you do to them.
It might be great to figure out a way to allow this for future PRs.

**Comment by nicolas-grekas** [comment]
Oh, and one last thing: please squash your PR so that it has only one commit.

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 11]
```diff
@@ -321,7 +321,7 @@ private function autowireMethod(\ReflectionFunctionAbstract $reflectionMethod, a
                     $type = ProxyHelper::exportType($parameter);
                     $type = $type ? sprintf('is type-hinted "%s"', preg_replace('/(^|[(|&])\\\\|^\?\\\\?/', '\1', $type)) : 'has no type-hint';
 
-                    throw new AutowiringFailedException($this->currentId, sprintf('Cannot autowire service "%s": argument "$%s" of method "%s()" %s, you should configure its value explicitly.', $this->currentId, $parameter->name, $class !== $this->currentId ? $class.'::'.$method : $method, $type));
+                    throw new AutowiringFailedException($this->currentId, sprintf('Cannot autowire service "%s": argument "$%s" of method "%s()" "%s", you should configure its value explicitly.', $this->currentId, $parameter->name, $class !== $this->currentId ? $class.'::'.$method : $method, $type));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: arf sorry, this change from fabbot should be ignored (same in tests + please squash)

**Comment by nicolas-grekas** [comment]
Thank you @rodmen.
