### PR TITLE
[Messenger] Add idle timeout option to `BatchHandlerTrait`

### LINKED ISSUE #63205: [Messenger] BatchHandler no longer flushes on idle
### Symfony version(s) affected

6.4.32 7.3.10 7.4.4 8.0.4

### Description

Since the release of the latest symfony version the batch handling has changed it behavior.

After our testing on 7.3.10, we've found that the default behavior is altered where the batch handling is now waiting for the batchsize to be filled before processing the batch. In the case described by @wazum this is unwanted behavior, but for our case that is very much wanted behavior.

We have an fluctuating workload which we batch handle to improve efficiency, but when the worker is idle it should handle the message asap. Otherwise it would wait until the batch is filled or the worker is reaching it's timeout limit.

This is also the behavior of the batch processing according to the manual: https://symfony.com/doc/current/messenger.html#process-messages-by-batches

By default, pending batches are flushed when the worker is idle as well as when it is stopped.

I think this should be an opt-in feature, since batch sizes are most of the time random and waiting for a specific amount of messages to be handled can be very unstable and cause for other, unwanted behavior.

This is caused by the following PR https://github.com/symfony/symfony/pull/62872

### How to reproduce

The same testscenario as https://github.com/symfony/symfony/issues/61292 but now reversed.

Here's a test project: https://github.com/wazum/symfony-messenger-batch

Start the consumer first (with a limit of 20) and then call the command (with a batch size of 12) and you will see a random output like:

```
 // The worker will automatically exit once it has processed 20 messages or received a stop signal via the
 // messenger:stop-workers command.

 // Quit the worker with CONTROL-C.

 // Re-run the command with a -vv option to see logs about consumed messages.

Processed new batch of cat facts
------------------------------------------------------------
1. Blue-eyed, white cats are often prone to deafness.
2. Cat's urine glows under a black light.
3. A queen (female cat) can begin mating when she is between 5 and 9 months old.
4. It has been scientifically proven that stroking a cat can lower one's blood pressure.
5. The claws on the cat’s back paws aren’t as sharp as the claws on the front paws because the claws in the back don’t retract and, consequently, become worn.
6. Cats must have fat in their diet because they can't produce it on their own.
7. A kitten will typically weigh about 3 ounces at birth.  The typical male housecat will weigh between  7 and 9 pounds, slightly less for female housecats.
8. In contrast to dogs, cats have not undergone major changes during their domestication process.
9. Cats prefer to remain non-confrontational. They will not fight to show dominance, but rather to stake their territory. Cats will actually go to extremes to avoid one another in order to prevent a possible confrontation.
…
```

 ```
// The worker will automatically exit once it has processed 20 messages or received a stop signal via the
 // messenger:stop-workers command.

 // Quit the worker with CONTROL-C.

 // Re-run the command with a -vv option to see logs about consumed messages.

Processed new batch of cat facts
------------------------------------------------------------
1. The female cat reaches sexual maturity within 6 to 10 months; most veterinarians suggest spaying the female at 5 months, before her first heat period. The male cat usually reaches sexual maturity between 9 and 12 months.
2. While it is commonly thought that the ancient Egyptians were the first to domesticate cats, the oldest known pet cat was recently found in a 9,500-year-old grave on the Mediterranean island of Cyprus. This grave predates early Egyptian art depicting cats by 4,000 years or more.
3. The first cat show was organized in 1871 in London. Cat shows later became a worldwide craze.


Processed new batch of cat facts
------------------------------------------------------------
1. Blue-eyed, white cats are often prone to deafness.
2. Cat's urine glows under a black light.
3. A queen (female cat) can begin mating when she is between 5 and 9 months old.
4. It has been scientifically proven that stroking a cat can lower one's blood pressure.
5. The claws on the cat’s back paws aren’t as sharp as the claws on the front paws because the claws in the back don’t retract and, consequently, become worn.
6. Cats must have fat in their diet because they can't produce it on their own.
7. A kitten will typically weigh about 3 ounces at birth.  The typical male housecat will weigh between  7 and 9 pounds, slightly less for female housecats.


Processed new batch of cat facts
------------------------------------------------------------
1. In contrast to dogs, cats have not undergone major changes during their domestication process.
2. Cats prefer to remain non-confrontational. They will not fight to show dominance, but rather to stake their territory. Cats will actually go to extremes to avoid one another in order to prevent a possible confrontation.
3. There are up to 60 million feral cats in the United States alone.
4. Cats lose almost as much fluid in the saliva while grooming themselves as they do through urination.
instead of the expected
```

### Possible Solution

Make the BatchHandlerTrait handling of batches during idle an opt-out feature, so that the current behavior stays the same as it was before this release.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | maybe?
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #63205
| License       | MIT

This PR adds a `getIdleTimeout()` method to `BatchHandlerTrait`, allowing batches to be flushed after a configured idle time when the required batch size is not reached.

This ensures that low-throughput workloads are processed regardless of batch size, rather than waiting indefinitely for the batch to fill up.

For older Symfony versions, users can copy this updated `BatchHandlerTrait` implementation and use it directly in their projects.

### CODE REVIEW

**Comment by dmiedev** [comment]
I'm no contributor of Symfony (sorry for any potential confusion), but shouldn't this be also included as a fix for older Symfony versions? (after all, https://github.com/symfony/symfony/pull/62872 may have introduced unintended logic into 6.4 for some people)

**Comment by nicolas-grekas** [comment]
I agree we might prefer reverting the behavior on 6.4 and introduce this on 8.1 with the current code. And we might prefer also keep the previous behavior by default, aka idle timeout = 0. Up to follow this idea?

**Comment by HypeMC** [comment]
@nicolas-grekas Yes, I think this makes sense. The old behavior is even mentioned in [the docs](https://symfony.com/doc/6.4/messenger.html#process-messages-by-batches), which I didn't notice before:

> By default, pending batches are flushed when the worker is **idle** as well as when it is stopped.

I'll open a PR to revert #62872 and reintroduce this behavior in 8.1 as you suggested.

**Comment by nicolas-grekas** [comment]
Rebase unlocked

**Comment by HypeMC** [comment]
> Rebase unlocked

@nicolas-grekas Done

File: src/Symfony/Component/Messenger/Handler/BatchHandlerTrait.php [hunk 1]
```diff
@@ -69,4 +85,12 @@ private function getBatchSize(): int
     {
         return 10;
     }
+
+    /**
+     * @return int|null The idle timeout in seconds
+     */
+    private function getIdleTimeout(): ?int
+    {
+        return 1;
```
Comment (HypeMC) [inline src/Symfony/Component/Messenger/Handler/BatchHandlerTrait.php:94]: @nicolas-grekas I set 1 second as the default because with 0, the message would be processed immediately, which would defeat the purpose of batching.

File: src/Symfony/Component/Messenger/Tests/Middleware/HandleMessageMiddlewareTest.php [hunk 2]
```diff
@@ -320,6 +320,54 @@ private function process(array $jobs): void
...
+        $middleware = new HandleMessageMiddleware(new HandlersLocator([
+            DummyMessage::class => [new HandlerDescriptor($handler)],
+        ]));
+
+        $ack = static function () {};
+
+        $message = new DummyMessage('Hey');
+        $envelope = $middleware->handle(new Envelope($message, [new AckStamp($ack)]), new StackMiddleware());
+
+        $this->assertEmpty($handler->processedMessages);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Tests/Middleware/HandleMessageMiddlewareTest.php]: empty is banned :) (same below)
```suggestion
        $this->assertSame([], $handler->processedMessages);
```

**Review by nicolas-grekas — APPROVED** [review]
just minor cs things then GTM

File: src/Symfony/Component/Messenger/Tests/Middleware/HandleMessageMiddlewareTest.php (hunk 2 above)
Comment (HypeMC) [reply src/Symfony/Component/Messenger/Tests/Middleware/HandleMessageMiddlewareTest.php]: Done https://github.com/symfony/symfony/compare/6679a451f7cb765108e1b115ddfbe6b8b2de08d0..93ae755cd84d4af95b999f2dd293d83f8d1d1675

**Comment by nicolas-grekas** [comment]
Thank you @HypeMC.
