### PR TITLE
[Console] Fix color support for TTY output

### LINKED ISSUE #53693: [console] ansi support detection is broken
### Symfony version(s) affected

v6.4.3

### Description

When running a symfony CLI app, the output is in black and white. I was in color before.

### How to reproduce

I updates symfony/console on [castor](https://github.com/jolicode/castor/commit/d6f4d57f84d9b311b4f0bf3dca53a869a7c77ac1) and now when I run `castor` is output is without colors 

Note: I use ubuntu 22.04.3 LTS, up to date + tmux. It's broken only in tmux or screen

### Possible Solution

#53576 is realated ? cc @theofidry

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by theofidry**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #53693
| License       | MIT

Prior to https://github.com/symfony/symfony/pull/53576, the output being a TTY was sufficient to consider the output as supporting colors. This is not enough but as a result, we are missing some additional checks.

This PR:

- Adds a check for the `COLORTERM` environment variable. From what I've found it does not look this variable is ever set if there is no color support.
- Adds a check for the `screen-*` `TERM` values. Similar to the check we already for `xterm`, you have `screen-256color`, `screen-256color-bce`, `screen.xterm-256color` or more.

### CODE REVIEW

File: src/Symfony/Component/Console/Output/StreamOutput.php [hunk 1]
```diff
@@ -106,10 +107,18 @@ protected function hasColorSupport()
...
             || 'ON' === getenv('ConEmuANSI')
-            || str_starts_with((string) getenv('TERM'), 'xterm');
+        ) {
+            return true;
+        }
+
+        $term = (string) getenv('TERM');
+
+        return str_ends_with($term, 'screen')
+            || str_ends_with($term, 'xterm');
```
Comment (stof) [inline src/Symfony/Component/Console/Output/StreamOutput.php]: why changing from `str_starts_with` to `str_ends_with` ?

**Comment by stof** [comment]
The `supports-color` npm package has [2 different kind of checks] (https://github.com/chalk/supports-color/blob/d4f413efaf8da045c5ab440ed418ef02dbb28bf1/index.js#L153-L159) for `TERM`:

- whether it ends with `-256` or `-256color` (in which case it reports color support for what we call the Ansi8 mode)
- whether it starts with a bunch of prefixes (more than just `screen-` and `xterm-`)

Should we take the full list there ?

File: src/Symfony/Component/Console/Output/StreamOutput.php (hunk 1 above)
Comment (theofidry) [reply src/Symfony/Component/Console/Output/StreamOutput.php]: damn, mistake

File: src/Symfony/Component/Console/Output/StreamOutput.php [hunk 2]
```diff
@@ -106,10 +107,22 @@ protected function hasColorSupport()
...
+        }
+
+        $term = (string) getenv('TERM');
+
+        if ('dumb' === $term) {
+            return false;
+        }
+
+        // See https://github.com/chalk/supports-color/blob/d4f413efaf8da045c5ab440ed418ef02dbb28bf1/index.js#L157
+        return 1 === @preg_match('/^((xterm|screen|putty|rxvt|linux).*)|(.*-256color(-bce)?)$/', $term);
```
Comment (stof) [inline src/Symfony/Component/Console/Output/StreamOutput.php]: why not taking the full list of prefixes from the chalk code ?

And for the suffix, you support `-256color` but not `-256`

File: src/Symfony/Component/Console/Output/StreamOutput.php [hunk 3]
```diff
@@ -13,6 +13,7 @@
 
 use Symfony\Component\Console\Exception\InvalidArgumentException;
 use Symfony\Component\Console\Formatter\OutputFormatterInterface;
+use function preg_match;
```
Comment (stof) [inline src/Symfony/Component/Console/Output/StreamOutput.php]: we don't use `use function` in Symfony.

File: src/Symfony/Component/Console/Output/StreamOutput.php (hunk 2 above)
Comment (theofidry) [reply src/Symfony/Component/Console/Output/StreamOutput.php]: The handling is a bit different for windows (and I don't have a windows machine so I can't easily test it); so I do not know if `vt100` and co. should be in there.

That said it is missing `ansi` at the very least.

File: src/Symfony/Component/Console/Output/StreamOutput.php (hunk 3 above)
Comment (theofidry) [reply src/Symfony/Component/Console/Output/StreamOutput.php]: it was done automatically by the IDE; I expect fabbot CS to fix it so I didn't worry about it

**Comment by stof** [comment]
@theofidry any chance to finish this PR ?

**Comment by theofidry** [comment]
@stof done

**Review by stof — APPROVED** [review]
Please apply the fabbot coding standard patch (we use qualified function calls only for compiler-optimized functions in Symfony).

But other than that, this PR is good to me.

**Comment by theofidry** [comment]
I thought I already did, I applied it again although no clue what the diff is 😅 looks like it's happy now at least

**Comment by stof** [comment]
@theofidry for the diff, see the diff of your force-push: https://github.com/symfony/symfony/compare/76e89cb21a56a42a95c0dbaf1b75438441ee4410..50b0051c78f853d605cbc57209e065b9a7a3e357

This was about removing the `\` qualifying the `preg_match` function name.

File: src/Symfony/Component/Console/composer.json [hunk 4]
```diff
@@ -17,6 +17,7 @@
     ],
     "require": {
         "php": ">=7.2.5",
+        "ext-pcre": "*",
```
Comment (chalasr) [inline src/Symfony/Component/Console/composer.json]: Does it really belong to this PR? Console and many other components require PCRE but none require it explicitly

Comment (stof) [reply src/Symfony/Component/Console/composer.json]: I would remove it here. We don't define this requirement in all our components

Comment (chalasr) [reply src/Symfony/Component/Console/composer.json]: done

**Review by chalasr — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @theofidry.

**Comment by melroy89** [comment]
Sorry this was a regression in 6.4.x as well right? Is this now merged into 5.4? I don't understand.

**Comment by wouterj** [comment]
We up merge older branches into newer ones. Since the merge of this PR, 5.4 has been merged in 6.4 (and 7.0 + 7.1-dev). All supported versions will get a release at the end of the month.

**Comment by melroy89** [comment]
> We up merge older branches into newer ones. Since the merge of this PR, 5.4 has been merged in 6.4 (and 7.0 + 7.1-dev). All supported versions will get a release at the end of the month.

ah OK. got it!
