### PR TITLE
[Messenger] Allow password in redis dsn when using sockets

### LINKED ISSUE #47393: Password not working with an unix socket for Messenger redis transport
### Symfony version(s) affected

6.1.3, 5.4.11

### Description

When a messenger async transport is configured with Redis (unix socket with a password), it gives DSN parsing errors.
After looking at the code, the password is properly parsed only when a host is used.
It's also the same for the password option, it's not used in case of a socket.

The redis cache adapter doesn't seem to be affected by this problem. It allows DSN like that :
`redis[s]://[pass@][ip|host|socket[:port]][/db-index]`

### How to reproduce

Use a DSN like that for an async messenger queue :
`redis://password@/var/run/redis.sock`

It gives the following error :

> The given Redis DSN is invalid

### Possible Solution

Add support for passwords with redis socket in the same way the redis cache adapter does.

I can propose a PR for that.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by PhilETaylor**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Tickets       | Fix #47393 @Arakmar 
| License       | MIT
| Doc PR        | 

When a messenger async transport is configured with Redis (unix socket with a password), it gives DSN parsing errors.

Using a Bunch of copy and pasted code blocks from the Redis cache adapter, this PR fixes the bug that doesn't parse a DSN such as 

`redis://password@/var/run/redis.sock`

Replaces bad rebased #47475

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php [hunk 1]
```diff
@@ -203,13 +204,14 @@ public static function fromDsn(string $dsn, array $options = [], \Redis|\RedisCl
             };
         }
 
+        $pass = '' !== ($parsedUrl['pass'] ?? '') ? urldecode($parsedUrl['pass']) : null;
+        $user = '' !== ($parsedUrl['user'] ?? '') ? urldecode($parsedUrl['user']) : null;
+        // See: https://github.com/phpredis/phpredis/#auth
```
Comment (chalasr) [inline src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: the link is likely to age badly, I'd remove it

Comment (PhilETaylor) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: I just moved it :) but I have removed it now - thanks.

**Comment by nicolas-grekas** [comment]
Thank you @PhilETaylor.
