### PR TITLE
[VarDumper] Fix dumping twig templates found in exceptions

### LINKED ISSUE #27921: [VarDumper] Exception Caster Crashes on Twig Template Inspection
**Symfony version(s) affected**: 4.1 (maybe as low as 3.x)

**Description**  
While collecting information for profiler exceptions and errors are converted to arrays. One of the errors in my log crashes `ExceptionCaster`, since it contains stacktrace frame **with** `class` referencing abstract class and in the same time **without** `object`. 

`ExceptionCaster` blindly assumes that if something is a child of `Twig_Template`/`Twig\Template` it can be instantiated. However in reality I stepped into case where it's not true and stack trace contains direct reference to abstract class `Vendor\Custom\TwigTemplate` (which extends `\Twig_Template`) with method name referencing `__toString()`. `ExceptionCaster` attempts to initialize object of this class which leads to complete hard to debug crash.

**How to reproduce**  
~~So far I'm unable to provide reproducer, since even stepping around the code with XDebug crashes PHP without any errors.~~ The last frame received by `\Symfony\Component\VarDumper\Caster\ExceptionCaster::castFrameStub` contains reference class set as `base_template_class` and call to `__toString()`. The only special thing about this class is it contains call to `@trigger_error(..., E_USER_DEPRECATED)` within `__toString()`.

The easiest way to reproduce this which I was able to find was to start with fresh 4.1 installation. Then:
1. Configure  `base_template_class` to point to custom class, e.g. `base_template_class: \App\FooTwigBase`
2. Create custom base class:
```php
abstract class FooTwigBase extends \Twig_Template
{
    public function __toString()
    {
        \trigger_error('Message reprimanding users to not cast templates to string etc...', \E_USER_DEPRECATED); //This is crucial part of the story!

        //In actual code I actually return template code
        return parent::__toString();
    }
}
```
3. Execute `(string)$te->loadTemplate('base.html.twig');` from e.g. controller action
4. Scratch your head:
image

**Possible Solution**  
The easiest solution is to ensure no code calls `loadTemplate()` but recommended `load()`. This is however not possible since in some cases template code must be available for use (don't even ask...). This will mask the problem since `is_subclass_of()` in caster will never return true with abstract class, however I think the proper fix is actually simple. Another hack is to never ever trigger any errors in `__toString`, but this makes monitoring internal deprecations impossible.

I understand this is a massive edge-case from my side, however I think fixing it will be very easy from upstream.
 `\Symfony\Component\VarDumper\Caster\ExceptionCaster::castFrameStub` contains the following code:
https://github.com/symfony/symfony/blob/8c70b3939c8e69df40055fa74fc1d23e36e6a610/src/Symfony/Component/VarDumper/Caster/ExceptionCaster.php#L215

When replaced with the following code safely skips problematic frame:
```php
$template = null;
if (isset($f['object'])) {
    $template = $f['object'];
} elseif ((new \ReflectionClass($f['class']))->isInstantiable()) {
    $template = unserialize(sprintf('O:%d:"%s":0:{}', strlen($f['class']), $f['class']));
}
if (isset($template)) {
    $ellipsis = 0;
    //...
```

//Edit: provided way to reproduce

### PR DESCRIPTION
**Pull request by event15**
Fix for `Cannot instantiate abstract class on (...)` in `ExceptionCaster` in VarDumper.
| Q             | A
| ------------- | ---
| Branch?       | 4.4 (and olders?)
| Bug fix?      | yes
| New feature?  |no
| Deprecations? | no
| Tickets       | Fix #27921
| License       | MIT

In this issue #27921 @nicolas-grekas said that this affects very old versions - even 2.8. I created a branch from 4.4 according to the CONTRIBBUTING guide.

### CODE REVIEW

File: src/Symfony/Component/VarDumper/Caster/ExceptionCaster.php [hunk 1]
```diff
@@ -214,18 +214,24 @@ public static function castFrameStub(FrameStub $frame, array $a, Stub $stub, $is
...
-                            if ($templateSrc) {
-                                $src = self::extractSource($templateSrc, $templateInfo[$f['line']], self::$srcContext, 'twig', $templatePath, $f);
-                                $srcKey = ($templatePath ?: $template->getTemplateName()).':'.$templateInfo[$f['line']];
+                        $template = null;
+                        if (isset($f['object'])) {
+                            $template = $f['object'];
+                        } elseif ((new \ReflectionClass($f['class']))->isInstantiable()) {
+                            $template = unserialize(sprintf('O:%d:"%s":0:{}', \strlen($f['class']), $f['class']));
+                        }
+                        if (isset($template)) {
```
Comment (stof) [inline src/Symfony/Component/VarDumper/Caster/ExceptionCaster.php]: use `if ($template !== null)` instead as a null check

Comment (event15) [reply src/Symfony/Component/VarDumper/Caster/ExceptionCaster.php]: Done

**Comment by event15** [comment]
I noticed that appveyor reports a mismatch between `$expectedDump` in tests and what the Windows returns. This is a minor error, but still, the test on Windows is red. Should I looking for any better way to test this? 

I don't quite understand the problem with failing tests on version 7.4 high-deps. There is a suggestion in the documentation that it may be BC. 

On the other hand, I see that merged PRs are also failing this steps (for example: https://github.com/symfony/symfony/actions/runs/1367057090 was merged)  - so I don't know what it depends on.

File: src/Symfony/Component/VarDumper/Tests/Caster/ExceptionCasterTest.php [hunk 2]
```diff
@@ -114,16 +116,43 @@ public function testNoSrcContext()
...
+      __TwigTemplate_VarDumperFixture_abstractBug->provideError()
+      › {
+      ›     return $this->createError();
+      › }
+    }
+    %sExceptionCasterTest.php%s%d { …}
+%A
+EODUMP;
+
+        $this->assertStringMatchesFormat($expectedDump, $dump);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/VarDumper/Tests/Caster/ExceptionCasterTest.php]: you should use assertDumpMatchesFormat instead, that would also fix the failure on Windows

File: src/Symfony/Component/VarDumper/Tests/Fixtures/ConcreteBug.php [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+    }
+
+    public function provideError()
+    {
+        return $this->createError();
+    }
+}
+
+/* foo_abstract.twig */
+class __TwigTemplate_VarDumperFixture_concreteBug extends __TwigTemplate_VarDumperFixture_abstractBug
```
Comment (nicolas-grekas) [inline src/Symfony/Component/VarDumper/Tests/Fixtures/ConcreteBug.php]: please make this class auto-loadable instead, by naming it according to PSR4
please also clean it up, removing anything that is not required by the test case
and please name the class according to the test case as `ConcreteBug` is not helpful right now

**Review by nicolas-grekas — COMMENTED** [review]
Thanks, the fix LGTM.
Here are some comments for the tests.

**Comment by nicolas-grekas** [comment]
Thank you @event15

**Comment by event15** [comment]
@nicolas-grekas great! Thanks so much for your patience and help.
