### PR TITLE
[Form] error if the input string couldn't be parsed as a date

### LINKED ISSUE #40597: Form DateType accepts random strings as valid value and converts it to 1970-01-01
**Symfony version(s) affected**:5.2

**Description**
\Symfony\Component\Form\Extension\Core\Type\DateType when using widget "single_text" accepts incorrect date string for example "dsfsdfds" and transform it before mapping to form-data (data_class object) to 1970-01-01. It should give an error that date is invalid. Even adding constraint \Symfony\Component\Validator\Constraints\Date to the date field is not working, because the field validator checks value after transforming (1970-01-01), so the value is valid.

**How to reproduce**

1. Create a form with DateType|BirthdayType field:
`$builder->add('birthDate', BirthdayType::class, [
                'label' => "Birthdate",
                'widget' => 'single_text',
                'html5' => false,
                'format' => 'yyyy-MM-dd',
                'input' => 'string',
                'input_format' => 'Y-m-d',
                'constraints' => [
                    new NotBlank(),
                    new Date()
                ]
            ])`
2. Submit form with some incorrect value in the field
image

3. After submitting form and rendering it again you can see value 1970-01-01 and no error
image

Here are dump of form array input from the Request object after submit:
`array:1 [▼
  "birthDate" => "dsfsdfdsdsdsfdsf"
]`

and dump of associated form-data object after form->handleSubmit():
`App\UI\Web\Form\Profile\ProfileCreateRequest {#548 ▼
  +birthDate: "1970-01-01"
}`

**Possible Solution**
My research showed that \Symfony\Component\Form\Extension\Core\DataTransformer\DateTimeToLocalizedStringTransformer does that incorrect transition without any error.

It uses \IntlDateFormatter, which converts every incorrect date string to timestamp=false in:
symfony/form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php:123
line 123: `$timestamp = @$dateFormatter->parse($value);`

XDebug output:
image

I've added some test var $someTestVar to the DateTimeToLocalizedStringTransformer, only to show in xdebug output of int_get_error_code().
As you can see dateFormatter has errorCode => 9 and U_PARSE_ERROR, but whole function is run using silent mode with "@" so there is no exception thrown. Another strange thing that **intl_get_error_code()** gives 0 code, so also condition in line 130 is not TRUE, and an exception in line 131 is not thrown.

image

After that **$timestamp** var is false, which is converting to 0, when DateTime object is creating after that, so it gives a date with 1970-01-01 :) 
image

**Additional context**
The same problem occurs when you're using, but `   'input' => 'string',
                'input_format' => 'Y-m-d',`
it transforms incorrect value to DateTime('1970-01-01') object then.

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40597
| License       | MIT
| Doc PR        | 

When the Intl polyfill is used instead of the PHP intl extension, the
intl_get_error_code() function always returns 0 no matter if the input
string could be parsed.

### CODE REVIEW

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php [hunk 1]
```diff
@@ -130,6 +130,10 @@ public function reverseTransform($value)
         } elseif ($timestamp > 253402214400) {
             // This timestamp represents UTC midnight of 9999-12-31 to prevent 5+ digit years
             throw new TransformationFailedException('Years beyond 9999 are not supported.');
+        } elseif (false === $timestamp) {
+            // the value couldn't be parsed but the Intl extension didn't report an error code, this
+            // could be the case when the Intl polyfill is used which always returns 0 as the error code
```
Comment (OskarStark) [inline src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php:135]:
```suggestion
            // could be the case when the Intl polyfill is used which always returns 0 as error code
```

**Review by OskarStark — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Would there be a way to improve the polyfill in this regard?

**Review by kamil-jakubowski — APPROVED** [review]
That workaround works when using Symfony Intl Polyfill (with intl ext uninstalled) on Symfony 5.2
image

Although, there is a bug still in Symfony Intl Polyfill :)

**Review by kamil-jakubowski — APPROVED** [review]

**Review by kamil-jakubowski — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by xabbuh** [comment]
@kamil-jakubowski I was looking into fixing the Intl polyfill package, but I actually couldn't reproduce the behaviour that you experienced. Which exact version of the polyfill package do you use? Can you debug why the error code isn't stored correctly?

**Comment by emilylark** [comment]
When the Intl polyfill is used instead of the PHP intl extension, the
intl_get_error_code() function always returns 0 no matter if the input
string could be parsed.

For more guidelines visit my site [essay writer](https://www.collegeessay.org/)

**Comment by emilylark** [comment]
When the Intl polyfill is used instead of the PHP intl extension, the
intl_get_error_code() function always returns 0 no matter if the input
string could be parsed.

For more guidelines visit my site [essay writer](https://www.collegeessay.org/)
