### PR TITLE
[Translation] Add support for calling 'trans' with ICU formatted messages

### LINKED ISSUE #37228: Messages in ICU format are not handled
**Symfony version(s) affected**: 5.1.0

**Description**  
Messages written in the ICU format are not being translated properly. By this I mean that the ICU format string itself is returned. I assume I'm doing something wrong, since I ran the tests in `symfony/translation` and they all pass, and I saw that some tested for what I'm trying to do.

I used the example from [the documentation](https://symfony.com/doc/current/translation/message_format.html#pluralization). I tried it in tests and in a controller.

**How to reproduce**  
tests:

```
static::bootKernel();
$translator = static::$container->get(TranslatorInterface::class);
static::assertSame('2 apples', $translator->trans('{{count}, plural, =1 {1 apple} other {{count} apples}}', ['{count}' => 2]));
```

controller:

```
echo $translator->trans('{{count}, plural, =1 {1 apple} other {{count} apples}}', ['{count}' => 0]);
echo $translator->trans('{{count}, plural, =1 {1 apple} other {{count} apples}}', ['{count}' => 0], 'foo+intl-icu');
echo $translator->trans('num_of_apples', ['apples' => 1], 'foo+intl-icu');
```
and `foo+intl-icu.en.yaml` has (from [this doc page](https://symfony.com/doc/current/translation/message_format.html#pluralization))

```
num_of_apples: >-
    {apples, plural,
        =0    {There are no apples}
        one   {There is one apple...}
        other {There are # apples!}
    }
```

(different on purpose to make sure the file was being loaded)

**Additional context** 

The outputs from the controller are:

```
{0, plural, =1 {1 apple} other {0 apples}}
{0, plural, =1 {1 apple} other {0 apples}}
{1, plural, =0 {There are no 1} one {There is one apple...} other {There are # 1!} }
```

I also tested on a new project.

### PR DESCRIPTION
**Pull request by someonewithpc**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | maybe, see https://github.com/symfony/symfony/issues/37228
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #37228
| License       | MIT
| Doc PR        | symfony/symfony-docs#13875

Motivation:

```
$apples = [0 => 'No apples', 1 => '1 apple', '# apples'];
echo _m($apples, ['count' => 0]); // Outputs 'No apples'
echo _m($apples, ['count' => 2]); // Outputs '2 apples'
```

where `_m` is a wrapper my application is using, but we obviously don't want to replicate many of the effort of the translation component, so it relies on `trans`.

This wrapper itself could be integrated into Symfony, if deemed appropriate.

See #37228

### CODE REVIEW

**Comment by someonewithpc** [comment]
The AppVeyor failure doesn't seem to be related to this change, outputting: `Cannot parse message translation: please install the "intl" PHP extension`.

**Comment by nicolas-grekas** [comment]
> Cannot parse message translation: please install the "intl" PHP extension

this is totally related - and we're apparently missing some tests that should highlights that this changes the default behavior.

This looks like a BC break to me. It also forces installing the intl extension by default.
Why don't you change the default domain in you case?

**Comment by someonewithpc** [comment]
> > Cannot parse message translation: please install the "intl" PHP extension
> 
> this is totally related - and we're apparently missing some tests that should highlight that this changes the default behavior.
> 
> This looks like a BC break to me. It also forces installing the intl extension by default.
> Why don't you change the default domain in you case?

Unless I'm misunderstanding something, I did change the default and it doesn't do what I need, since it checks if it contains it with the domain + suffix and then gets it with only the domain, therefore whether I set my domain to have the suffix or not, it doesn't do what I need.

I see the problem of requiring the intl extension, how could I make it be a setting, or something?

**Comment by nicolas-grekas** [comment]
My previous comment was confusing. The existing code reads as:
`if ($this->hasIntlFormatter && $catalogue->defines($id, $domain.MessageCatalogue::INTL_DOMAIN_SUFFIX)) {`

This means that the *catalog* needs to be named with the intl+icu suffix.
Then having the intl extension will use the intl format.

**Comment by someonewithpc** [comment]
Okay... But I have the intl extension enabled and I can't pass icu strings directly to trans, it seems to only work for id messages which are then defined in a file. Is it that I just need to dump the translations to a file? (since, again, I'm using a different system)

**Comment by stof** [comment]
@someonewithpc they are not forced to come from a file. You could build custom loaders using different sources (core loaders are all about files, indeed).

**Comment by someonewithpc** [comment]
No, but I don't want a loader, I don't think. Can you check the linked issue above?

**Comment by wouterj** [comment]
In this issue, you describe you want to use the Translator component like this:

```php
$translator->trans('{{count}, plural, =1 {1 apple} other {{count} apples}}', ['{count}' => 2])
```

This has nothing to do with translation. It's pure message formatting. That's not what the Translation component is created for. Instead, use Intl's [`MessageFormatter`](https://php.net/messageformatter) directly:

```php
MessageFormatter::formatMessage("en_US", "{{count}, plural, =1 {1 apple} other {{count} apples}}", ['count' => 2]);
```

**Comment by someonewithpc** [comment]
@wouterj It has everything to do with translation. I still want it to translate into different languages

**Comment by wouterj** [comment]
If you want to translate it, you'll have translation files like:

```yaml
# translations/messages+intl-icu.en.yaml
apples_count: {{count}, plural, =1 {1 apple} other {{count} apples}}
```

And then use it as:

```php
$translator->trans('apples_count', ['count' => 2], 'messages'); // 3rd argument not needed as "messages" is the default
```

**Comment by someonewithpc** [comment]
@wouterj That's the point, I don't want to use ids, I want to use it like I showed above.

**Comment by someonewithpc** [comment]
I updated the code and the relevant tests seem to pass. Could this get merged, or should I create a separate function?

File: src/Symfony/Component/Translation/Translator.php [hunk 1]
```diff
@@ -214,7 +214,9 @@ public function trans(?string $id, array $parameters = [], string $domain = null
             }
         }
 
-        if ($this->hasIntlFormatter && $catalogue->defines($id, $domain.MessageCatalogue::INTL_DOMAIN_SUFFIX)) {
+        if ($this->hasIntlFormatter
+            && ($catalogue->defines($id, $domain.MessageCatalogue::INTL_DOMAIN_SUFFIX)
+                || false != strstr($domain, MessageCatalogue::INTL_DOMAIN_SUFFIX))) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Translator.php:219]: Instead of using `strstr()`, I'd suggest using `substr_compare()` with a negative offset

**Review by nicolas-grekas — COMMENTED** [review]
Works for me this way. Can you please add some tests?

File: src/Symfony/Component/Translation/CHANGELOG.md [hunk 2]
```diff
@@ -4,6 +4,7 @@ CHANGELOG
 5.1.0
 -----
 
+ * added support for calling `trans` with ICU formatted messages
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/CHANGELOG.md:7]: this should be moved in a new 5.2.0 section

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @someonewithpc.
