### PR TITLE
[FrameworkBundle] Bugfixes in buildDir in the CacheClear command

### LINKED ISSUE #38547: Exception while clearing cache in 5.2.0-BETA1
**Symfony version(s) affected**:5.2.0-BETA1

**Description**  
Exception  `Cannot rename because the target ".../var/cache/de~" already exists.`

**How to reproduce**  
Every second run `bin/console c:c` will fail

**Possible solution**  
The problem is in

https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php#L164-L173

```php
if ($oldBuildDir) { // /var/cache/de~
    $fs->rename($realBuildDir, $oldBuildDir);
} else {
    $fs->remove($realBuildDir);
}
if ($oldCacheDir) { // /var/cache/de~
    $fs->rename($realCacheDir, $oldCacheDir); // Exception
} else {
    $fs->remove($realCacheDir);
}
```

`$oldBuildDir` and `$oldCacheDir` is [equal](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/HttpKernel/Kernel.php#L343)

**Additional context**  
This bug was introduced in https://github.com/symfony/symfony/pull/36515
/cc @mnapoli

### PR DESCRIPTION
**Pull request by Nyholm**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38547
| License       | MIT
| Doc PR        | n/a

Making sure one can clear cache with and without a buildDir

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php [hunk 1]
```diff
@@ -141,7 +141,7 @@ protected function execute(InputInterface $input, OutputInterface $output): int
             }
 
             if (!$fs->exists($warmupDir.'/'.$containerDir)) {
-                $fs->rename($realCacheDir.'/'.$containerDir, $warmupDir.'/'.$containerDir);
+                $fs->rename($realBuildDir.'/'.$containerDir, $warmupDir.'/'.$containerDir);
```
Comment (Nyholm) [inline src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:152]: If we have a separate buildDir and warming the cache. The container will never be located in $warmupDir. It will always be in `$readBuildDir`.

If we dont have a separate buildDir. Then $readBuildDir === $readCacheDir`

File: src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php [hunk 2]
```diff
@@ -166,14 +166,21 @@ protected function execute(InputInterface $input, OutputInterface $output): int
             } else {
                 $fs->remove($realBuildDir);
             }
-            if ($oldCacheDir) {
-                $fs->rename($realCacheDir, $oldCacheDir);
-            } else {
-                $fs->remove($realCacheDir);
+
+            if ($oldBuildDir !== $oldCacheDir) {
```
Comment (Nyholm) [inline src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php]: We should not try to rename or remove `$realCacheDir` again.

File: src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php [hunk 3]
```diff
@@ -166,14 +166,21 @@ protected function execute(InputInterface $input, OutputInterface $output): int
...
+                }
             }
+
             $fs->rename($warmupDir, $realCacheDir);
-            // Copy the content of the warmed cache in the build dir
-            $fs->copy($realCacheDir, $realBuildDir);
+
+            if ($realCacheDir !== $realBuildDir) {
+                // Copy the content of the warmed cache in the build dir
+                $fs->mirror($realCacheDir, $realBuildDir);
```
Comment (Nyholm) [inline src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:182]: This was just a typo: `copy()` is for files, `mirror()` is for directories.

**Comment by nicolas-grekas** [comment]
Funny, you submitted at the same time as #38549 :)
Could you compare both implementations and borrow the best of them, please?

File: src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php [hunk 4]
```diff
@@ -141,7 +149,7 @@ protected function execute(InputInterface $input, OutputInterface $output): int
             }
 
             if (!$fs->exists($warmupDir.'/'.$containerDir)) {
-                $fs->rename($realCacheDir.'/'.$containerDir, $warmupDir.'/'.$containerDir);
+                $fs->rename(($useBuildDir ? $realBuildDir : $realCacheDir).'/'.$containerDir, $warmupDir.'/'.$containerDir);
```
Comment (BoShurik) [inline src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php]: I think `$realBuildDir` is enough as it equals `$realCacheDir` for `!$useBuildDir`

Comment (Nyholm) [reply src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php]: Yes, you are correct. 

Thank you

**Review by BoShurik — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @Nyholm.

**Comment by Nyholm** [comment]
Thank you @BoShurik and @nicolas-grekas
