### PR TITLE
[Mailer] Adds `assertEmailSubjectContains` and `assertEmailSubjectNotContains` methods

### LINKED ISSUE #49939: Create `EmailSubjectContains` constraint for emails
### Description

In a `WebTestCase` I would like to be able to test the subject on emails as well as the body:

```php
self::assertEmailSubjectContains($email, 'This is the subject');
```

Here's my own version of the constraint right now:

```php
<?php

declare(strict_types=1);

namespace App\Tests\Constraint;

use PHPUnit\Framework\Constraint\Constraint;
use Symfony\Component\Mime\Email;

final class EmailSubjectContains extends Constraint
{
    private string $expectedText;

    public function __construct(string $expectedText)
    {
        $this->expectedText = $expectedText;
    }

    public function toString(): string
    {
        return sprintf('contains "%s"', $this->expectedText);
    }

    protected function matches($other): bool
    {
        if (!$other instanceof Email) {
            throw new \LogicException('Can only test a message subject on an Email instance');
        }

        return str_contains((string) $other->getSubject(), $this->expectedText);
    }

    protected function failureDescription($other): string
    {
        $message = 'the email subject ' . $this->toString();
        if ($other instanceof Email) {
            $message .= sprintf('. The subject was: "%s"', $other->getSubject() ?? '<empty>');
        }

        return $message;
    }
}
```

If this is good enough I can make a PR with it :)

### Example

_No response_

### PR DESCRIPTION
**Pull request by JohJohan**
> Adds assertEmailSubjectContains and assertEmailSubjectNotContains

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | No
| New feature?  | yes
| Deprecations? | No
| Tickets       | Fix #49939
| License       | MIT
| Doc PR        | symfony/symfony-docs#18269

### CODE REVIEW

**Comment by ghost** [comment]
Sorry the labels are incorrect as i posted the pull request before updating the default message.

**Comment by OskarStark** [comment]
Please rebase on 6.3 branch, we can merge this later in 6.4 once the branch is created. Thanks

**Comment by JohJohan** [comment]
> Please rebase on 6.3 branch, we can merge this later in 6.4 once the branch is created. Thanks

Okay will do why can i not target 5.4 as this is still maintained branch? https://symfony.com/doc/current/contributing/code/pull_requests.html#choose-the-right-branch or is it because this is seen as new feature?

**Comment by OskarStark** [comment]
Exactly, this is a new feature and must target the latest branch 👍

**Review by ndench — APPROVED** [review]
Thanks!

File: src/Symfony/Component/Mime/Test/Constraint/EmailSubjectContains.php [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+use Symfony\Component\Mime\Email;
+
+final class EmailSubjectContains extends Constraint
+{
+    private $expectedSubjectValue;
+
+    public function __construct(string $expectedSubjectValue)
+    {
+        $this->expectedSubjectValue = $expectedSubjectValue;
+    }
```
Comment (OskarStark) [inline src/Symfony/Component/Mime/Test/Constraint/EmailSubjectContains.php]: Please use constructor property promotion, thanks

Comment (JohJohan) [reply src/Symfony/Component/Mime/Test/Constraint/EmailSubjectContains.php]: Done pushed it

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @JohJohan.
