### PR TITLE
[Amqp] Add amqps support

### LINKED ISSUE #37002: Add (amqp) ssl capacity to messenger DSN
**Description**  
I tried using Amazon MQ and this error poped :
`Uncaught PHP Exception Symfony\Component\Messenger\Exception\InvalidArgumentException: "No transport supports the given Messenger DSN "amqps://private-ip:5671/ouag"." at /var/task/vendor/symfony/messenger/Transport/TransportFactory.php line 40`

I don't know what's needed to handle SSL on this protocol but it would be cool !

Here's the PHP amqp integration https://github.com/php-amqp/php-amqp/pull/205/files

### PR DESCRIPTION
**Pull request by vasilvestre**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Tickets       | Fix #37002
| License       | MIT
| Doc PR        | https://github.com/symfony/symfony-docs/pull/14250
### Cases

_Case 1 (simple):_ 
I want to set up my app with a locally installed amqp broker supporting SSL. No auth is needed, no vhost, only SSL certificate file located at /etc/ssl/cafile.
'amqps://'

_Case 2 (complex):_ 
I use a special port, special file locations for SSL. I pass it through php.ini or configuration.

### Questions

1) Actually AmqpTransportFactory use `supports` function to see if 'amqp://' is contained in dsn string and accept cacert argument to use SSL 
How are we supposed to cover AMQPS's case in your opinion?

cacert argument is settable through php.ini and code.

### Observations

I think this PR should aim at:

- Having correct defaults ssl values in case of 'amqps://' eg : case 1
- Being able to pass cacert file path and verify argument. eg : case 2
- Test: but test what?

#### EDIT
 
As discuted with @nicolas-grekas, we should check that cacert is existing in php.ini or is passed in configuration and throw an exception to give a nice feedback about what's wrong. Php amqp lib isn't actually precise about why it fails when you forget it.

### Steps

- [x] Ensure AMQPS can be used out of the box without DSN.
- [x] If not, try to modify vendor directly to fix it.
- [x] Modify vendor to make AMQPS works with DSN.
- [x] Check cacert to throw a better exception.
- [x] Add test related to last point.
- [x] Pass CI

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Can you make it work currently using only `php.ini` settings?

**Comment by vasilvestre** [comment]
> Can you make it work currently using only `php.ini` settings?

I do not really understand, wdym? Connect to amqp with ssl ?
If yes, it do actually work, this just allow amqps string (aws actually give you an amqps string only)

**Comment by nicolas-grekas** [comment]
In https://github.com/php-amqp/php-amqp/pull/205, it looks like setting the `amqp.cacert` ini setting is enought to use SSL, isn't it?

**Comment by vasilvestre** [comment]
> In [php-amqp/php-amqp#205](https://github.com/php-amqp/php-amqp/pull/205), it looks like setting the `amqp.cacert` ini setting is enought to use SSL, isn't it?

It is.  Why ?

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php [hunk 1]
```diff
@@ -259,6 +265,11 @@ private static function normalizeQueueArguments(array $arguments): array
         return $arguments;
     }
 
+    private static function hasCaCertConfigured(): bool
```
Comment (andrew-demb) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:268]: Missed option argument?

**Comment by vasilvestre** [comment]
It's wip ! :)

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php (hunk 1 above)
Comment (vasilvestre) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:268]: Its wip, I end it tomorrow

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php [hunk 2]
```diff
@@ -214,6 +217,10 @@ public static function fromDsn(string $dsn, array $options = [], AmqpFactory $am
             return $queueOptions;
         }, $queuesOptions);
 
+        if ($useAmqps && !self::hasCaCertConfigured($amqpOptions)) {
+            throw new SSLConnectionException("No ca certificate has been provided, set it in php files configuration 'amqp.cacert' or through DSN with cacert parameter to use SSL.");
```
Comment (fabpot) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:221]: No CA certificate
PHP files
via the 'cacert' parameter

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php [hunk 3]
```diff
@@ -258,6 +265,11 @@ private static function normalizeQueueArguments(array $arguments): array
         return $arguments;
     }
 
+    private static function hasCaCertConfigured(array $amqpOptions): bool
+    {
+        return (isset($amqpOptions['cacert']) && !empty($amqpOptions['cacert'])) || 0 !== (int) ini_get('amqp.cacert');
```
Comment (fabpot) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:270]: we try to avoid using empty.

**Review by fabpot — CHANGES_REQUESTED** [review]
Cosmetic review.

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php (hunk 3 above)
Comment (vasilvestre) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:270]: Could fabbot detect it ?
(I will fix it anyway, it's just a proposal)

**Comment by vasilvestre** [comment]
> Cosmetic review.

I actually have added a new exception, I'm not sure it is useful and require to have a new PR merged first. The SSLException class, what do you think about it? Should I use a RuntimeException, a LogicException, or the new one?

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php (hunk 2 above)
Comment (stof) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:221]: I would read better as such:

```
No CA certificate has been provided. Set "amqp.cacert" in the PHP configuration files or pass the "cacert" parameter in the DSN to use SSL.
```

Note that I'm using quotes rather than apostrophs in the message to quote the parameter names. this has 2 benefits:
- it is semantically correct (`'` is called a quote only by devs, not by human languages AFAIK)
- it matches the convention used in the WebProfilerBundle UI to emphasis such parts of error messages

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php [hunk 4]
```diff
@@ -258,6 +265,11 @@ private static function normalizeQueueArguments(array $arguments): array
         return $arguments;
     }
 
+    private static function hasCaCertConfigured(array $amqpOptions): bool
+    {
+        return (isset($amqpOptions['cacert']) && !'' === $amqpOptions['cacert']) || 0 !== (int) ini_get('amqp.cacert');
```
Comment (stof) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:270]: use `'' !==` rather than `!'' ===`. It will be more readable.

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php (hunk 2 above)
Comment (stof) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:221]: This should use `InvalidArgumentException` like other validation errors during the DSN parsing.

Comment (vasilvestre) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:221]: That was one of my question. Thank you !

Comment (vasilvestre) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php]: Ok, I've been using backslash to escape quotes, is it the correct one usage ?

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php [hunk 5]
```diff
@@ -216,6 +218,10 @@ public static function fromDsn(string $dsn, array $options = [], AmqpFactory $am
             return $queueOptions;
         }, $queuesOptions);
 
+        if ($useAmqps && !self::hasCaCertConfigured($amqpOptions)) {
+            throw new InvalidArgumentException('No CA certificate has been provided. Set "amqp.cacert" in the PHP configuration files or pass the "cacert" parameter in the DSN to use SSL.');
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:222]:
```suggestion
            throw new InvalidArgumentException('No CA certificate has been provided. Set "amqp.cacert" in your php.ini or pass the "cacert" parameter in the DSN to use SSL. Alternatively, you can use amqp:// to use without SSL.');
```

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php [hunk 6]
```diff
@@ -260,6 +266,11 @@ private static function normalizeQueueArguments(array $arguments): array
         return $arguments;
     }
 
+    private static function hasCaCertConfigured(array $amqpOptions): bool
+    {
+        return (isset($amqpOptions['cacert']) && '' !== $amqpOptions['cacert']) || 0 !== (int) ini_get('amqp.cacert');
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:271]: Why the casting of `ini_get('amqp.cacert')` to an int? What *is* `amqp.cacert` supposed to be - a path to the certificate?

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/AmqpTransportFactory.php [hunk 7]
```diff
@@ -29,7 +29,7 @@ public function createTransport(string $dsn, array $options, SerializerInterface
 
     public function supports(string $dsn, array $options): bool
     {
-        return 0 === strpos($dsn, 'amqp://');
+        return 0 === strpos($dsn, 'amqp://') || 0 === strpos($dsn, 'amqps://');
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Transport/AmqpTransportFactory.php:32]: In your original issue-  #37002 - you had been using `amqp+ssl`. Is that also valid?

**Review by weaverryan — COMMENTED** [review]
Minor comments - looks good to me, though I have zero experience with this!

I've seen some confusion around people using `amqps://` and it not working, which is partially why I suggest changing the message to also notify people that `amqp://` IS a valid option. For CloudAMQP, I think they are now showing `amqps://` by default, which is confusing some people when it doesn't work (especially beginners).

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php (hunk 6 above)
Comment (vasilvestre) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:271]: Reading documentation to answer you, I just say that ini_get can't read array (pdo.foo or amqp.cacert for eg..) I need another method so

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/AmqpTransportFactory.php (hunk 7 above)
Comment (vasilvestre) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Transport/AmqpTransportFactory.php:32]: Definitly not, it's a mistake. Thanks for input, I've edited it 🤦

**Comment by vasilvestre** [comment]
> Minor comments - looks good to me, though I have zero experience with this!
> 
> I've seen some confusion around people using `amqps://` and it not working, which is partially why I suggest changing the message to also notify people that `amqp://` IS a valid option. For CloudAMQP, I think they are now showing `amqps://` by default, which is confusing some people when it doesn't work (especially beginners).

nicolas-grekas recommanded me to add an exception because AMQPS doesn't enforce TSL usage. I think the doc PR will be important !

File: src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php [hunk 8]
```diff
@@ -506,6 +560,23 @@ public function testObfuscatePasswordInDsn()
...
+        $this->expectExceptionMessage('No CA certificate has been provided. Set "amqp.cacert" in your php.ini or pass the "cacert" parameter in the DSN to use SSL. Alternatively, you can use amqp:// to use without SSL.');
+
+        $factory = new TestAmqpFactory(
+            $amqpConnection = $this->createMock(\AMQPConnection::class),
+            $amqpChannel = $this->createMock(\AMQPChannel::class),
+            $amqpQueue = $this->createMock(\AMQPQueue::class),
+            $amqpExchange = $this->createMock(\AMQPExchange::class)
+        );
+
+        ini_set('amqp.cacert', '');
```
Comment (fabpot) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php:575]: That changes a global state, so the current value should be stored and restored after the test.

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php [hunk 9]
```diff
@@ -260,6 +266,11 @@ private static function normalizeQueueArguments(array $arguments): array
         return $arguments;
     }
 
+    private static function hasCaCertConfigured(array $amqpOptions): bool
+    {
+        return (isset($amqpOptions['cacert']) && '' !== $amqpOptions['cacert']) || '' !== ini_get('amqp.cacert');
```
Comment (fabpot) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:271]: I don't understand where the value of amqp.cacert is used.

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php (hunk 9 above)
Comment (vasilvestre) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:271]: The value of amqp.cacert is used by php amqp library, in fact it does load parameter from env, conf or ini. One of least should be specificed and they are loaded in $amqpOptions['cacert']

File: src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php (hunk 8 above)
Comment (vasilvestre) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php:575]: Nice to know, I will modify it :)

File: src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php [hunk 10]
```diff
@@ -506,6 +560,24 @@ public function testObfuscatePasswordInDsn()
...
+        $factory = new TestAmqpFactory(
+            $amqpConnection = $this->createMock(\AMQPConnection::class),
+            $amqpChannel = $this->createMock(\AMQPChannel::class),
+            $amqpQueue = $this->createMock(\AMQPQueue::class),
+            $amqpExchange = $this->createMock(\AMQPExchange::class)
+        );
+
+        $oldCaCertValue = ini_set('amqp.cacert', '');
+
+        Connection::fromDsn('amqps://', [], $factory);
```
Comment (fabpot) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php:577]: Must be wrapped in a try/finally block so that ini_set is executed.

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php (hunk 10 above)
Comment (vasilvestre) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php]: Oh fine, thank you

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
@vasilvestre Can you check the tests please? They seem to be broken by the changes introduced by this PR.

**Comment by vasilvestre** [comment]
> @vasilvestre Can you check the tests please? They seem to be broken by the changes introduced by this PR.

Yes I'm actualling trying to search why the exception is thrown.

**Comment by vasilvestre** [comment]
@fabpot it will pass this time :)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @vasilvestre.

**Comment by vasilvestre** [comment]
@fabpot should I create a documentation PR?

**Comment by weaverryan** [comment]
That would be awesome :). A docs issue has already been created

**Comment by vasilvestre** [comment]
here we are : https://github.com/symfony/symfony-docs/pull/14250

**Comment by stof** [comment]
To make this easier, should we automatically provide the cacert option to AMPQ if not configured, based on the CA file used by everything else in PHP (basically emulating what is suggested in https://github.com/php-amqp/php-amqp/issues/311 as a better API) ? The `amqps` scheme is enough for us to be sure that the encrypted connection is being requested.
Of course, an explicit `cacert` config for AMQP should still be allowed in case of needing a weird CA file.

**Comment by vasilvestre** [comment]
If this seem fine to you, I would love working with queuing systems in future so I would love to work on this. :)

File: src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php [hunk 11]
```diff
@@ -506,6 +563,27 @@ public function testObfuscatePasswordInDsn()
...
+        $this->expectExceptionMessage('No CA certificate has been provided. Set "amqp.cacert" in your php.ini or pass the "cacert" parameter in the DSN to use SSL. Alternatively, you can use amqp:// to use without SSL.');
+
+        $factory = new TestAmqpFactory(
+            $amqpConnection = $this->createMock(\AMQPConnection::class),
+            $amqpChannel = $this->createMock(\AMQPChannel::class),
+            $amqpQueue = $this->createMock(\AMQPQueue::class),
+            $amqpExchange = $this->createMock(\AMQPExchange::class)
+        );
+
+        $oldCaCertValue = ini_set('amqp.cacert', '');
```
Comment (OskarStark) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php:578]: This must be ini_get() I guess

Comment (vasilvestre) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php:578]: ini_set return previous value :) See documentation there https://www.php.net/manual/en/function.ini-get.php

Comment (OskarStark) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/ConnectionTest.php:578]: TIL thanks 🙂
