### PR TITLE
[Mailer] Fix mailer signer configuration issues

### LINKED ISSUE #59854: [Mailer] Mailer dkim and smime misconfiguration
### Symfony version(s) affected

7.3

### Description

While writing the docs for the S/Mime and Dkim signers configuration, I realized a couple of errors:

```
The service "mailer.dkim_signer.listener" has a dependency on a non-existent service "Symfony\Component\Mime\Crypto\DkimSigner".``` 
```
Explanation. The DkimSigner is not injected at this point so it should be set by its service id

```
Failed to sign S/Mime message. Error: "error:1E08010C:DECODER routines::unsupported".
```

Explanation: The argument position for certificate and key are wrong. 

### How to reproduce

On a fresh symfony 7.3 installation 
```
symfony local:new --version=next --webapp symfony-with-mailer
```
Create a new mailer configuration

```yaml
#config/mailer.yaml
framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        dkim_signer:
            key: 'file://%kernel.project_dir%/var/certificates/dkim.pem'
            domain: 'symfony.com'
            select: 's1'
        smime_signer:
            key: 'var/certificates/smime.key'
            certificate: '%kernel.project_dir%/var/certificates/smime.crt'
            passphrase: ''
```

With valid certificates and keys. Then run the mailer test:

```
bin/console mailer:test test@symfony.com
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by eliasfernandez**
| Q             | A
| ------------- | ---
| Branch?       | 7.3 
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59854
| License       | MIT

Explanation here: https://github.com/symfony/symfony/issues/59854

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -2879,8 +2879,8 @@ private function registerMailerConfiguration(array $config, ContainerBuilder $co
                 throw new LogicException('SMIME signed messages support cannot be enabled as this version of the Mailer component does not support it.');
             }
             $smimeSigner = $container->getDefinition('mailer.smime_signer');
-            $smimeSigner->setArgument(0, $config['smime_signer']['key']);
-            $smimeSigner->setArgument(1, $config['smime_signer']['certificate']);
+            $smimeSigner->setArgument(0, $config['smime_signer']['certificate']);
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:2882]: the abstract args in `mailer.smime_signer` are describing `key` as the first argument. Are those descriptions wrong as well ?

Comment (eliasfernandez) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:2882]: > the abstract args in `mailer.smime_signer` are describing `key` as the first argument. Are those descriptions wrong as well ?

Yes, I think so. Looks like the abstract_arg is not affecting in the scenario case described in the PR but probably is worth changing it in the Configuration and schema files.

Comment (stof) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:2882]: the description in `abstract_arg` is used if you forget to configure the argument to replace the abstract arg. As this line overrides the argument, you won't get an error message saying you forget to configure the `key`. But it is weird if descriptions don't match.

Comment (stof) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:2882]: Configuration and schema don't need to change. Those don't describe service definitions with ordered parameters. The order is not relevant there.

Comment (eliasfernandez) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:2882]: Thanks for the clarification. I'll rollback Configuration and schema changes.

**Review by Spomky — APPROVED** [review]
Last changes look good to me.
Many thanks.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @eliasfernandez.
