### PR TITLE
[FrameworkBundle] Add missing `useAttributeAsKey` calls

### LINKED ISSUE #63252: [FrameworkBundle][Messenger] Wrong array shape for transport options
### Symfony version(s) affected

7.4.3

### Description

The field `["messenger"]["transports"]` of the psalm type `FrameworkConfig` in the auto-generated `config/reference.php` looks like this:

```php
 *         transports?: array<string, string|array{ // Default: []
 *             dsn?: scalar|null|Param,
 *             serializer?: scalar|null|Param, // Service id of a custom serializer to use. // Default: null
 *             options?: list<mixed>,
 *             failure_transport?: scalar|null|Param, // Transport name to send failed messages to (after all retries have failed). // Default: null
 *             retry_strategy?: string|array{
 *                 service?: scalar|null|Param, // Service id to override the retry strategy entirely. // Default: null
 *                 max_retries?: int|Param, // Default: 3
 *                 delay?: int|Param, // Time in ms to delay (or the initial value when multiplier is used). // Default: 1000
 *                 multiplier?: float|Param, // If greater than 1, delay will grow exponentially for each retry: this delay = (delay * (multiple ^ retries)). // Default: 2
 *                 max_delay?: int|Param, // Max time in ms that a retry should ever be delayed (0 = infinite). // Default: 0
 *                 jitter?: float|Param, // Randomness to apply to the delay (between 0 and 1). // Default: 0.1
 *             },
 *             rate_limiter?: scalar|null|Param, // Rate limiter name to use when processing messages. // Default: null
 *         }>,
```

`options?: list<mixed>` is used although according to the docs the options array is not necessarily a list: https://symfony.com/doc/current/messenger.html#prioritized-transports.

### How to reproduce

Install `symfnny/framework-bundle` together with `symfony/messenger` and take a look into the auto-generated file `config/reference.php`.

### Possible Solution

Change the array shape to something like `options?: array<mixed>` instead.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63252
| License       | MIT

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
We might miss a corresponding XSD update?

**Comment by nicolas-grekas** [comment]
Thank you @MatTheCat.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 1]
```diff
@@ -494,6 +494,7 @@ private function addWorkflowSection(ArrayNodeDefinition $rootNode): void
                                                     ->cannotBeEmpty()
                                                 ->end()
                                                 ->arrayNode('metadata')
+                                                    ->useAttributeAsKey('key')
```
Comment (KevinVanSonsbeek) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:497]: @nicolas-grekas Back in august last year i proposed this same change in https://github.com/symfony/symfony/pull/61533/changes where you mentioned this would be a problem for a bugfix, as it would break existing configs. 

Is there a specific reason for the change of heart on this matter?

Comment (KevinVanSonsbeek) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:497]: As a small sidenote, this did indeed break our existing workflow configs. (Hence why i found this PR)
