### PR TITLE
Fix getTranslationNodeVisitor() return type

### LINKED ISSUE #37686: [TwigBridge] TranslationExtension constructor takes implementation but getter returns concrete class
**Symfony version(s) affected**: ^5.0

**Description**  
`Symfony\Bridge\Twig\Extension\TranslationExtension::__construct()` has and optional `NodeVisitorInterface` as a second argument. This argument is stored in the `$translationNodeVisitor` property which has a getter `public function getTranslationNodeVisitor(): TranslationNodeVisitor`.

When constructing the `TranslationExtension` with any `NodeVisitorInterface` other than `TranslationNodeVisitor`, you will get a type error when calling `getTranslationNodeVisitor()`

**How to reproduce**  
```
$translationExtension = new \Symfony\Bridge\Twig\Extension\TranslationExtension(
    null, 
    new \Symfony\Bridge\Twig\NodeVisitor\TranslationDefaultDomainNodeVisitor()
);

$translationExtension->getTranslationNodeVisitor();
```

**Possible Solution**  
Create a new interface that defines the public TranslationNodeVisitor methods and return that.
```
interface TranslationNodeVisitorInterface extends NodeVisitorInterface
{
    public function enable(): void;
    public function disable(): void;
    public function getMessages(): array;
}
```

**Additional context**

### PR DESCRIPTION
**Pull request by dbrekelmans**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37686
| License       | MIT
| Doc PR        | -

When constructing the `TranslationExtension` with any `NodeVisitorInterface` other than `TranslationNodeVisitor`, you will get a type error when calling `getTranslationNodeVisitor()`. This PR fixes that by extracting a new `TranslationNodeVisitorInterface`.

### CODE REVIEW

File: src/Symfony/Bridge/Twig/Extension/TranslationExtension.php [hunk 1]
```diff
@@ -34,7 +34,7 @@ final class TranslationExtension extends AbstractExtension
     private $translator;
     private $translationNodeVisitor;
 
-    public function __construct(TranslatorInterface $translator = null, NodeVisitorInterface $translationNodeVisitor = null)
+    public function __construct(TranslatorInterface $translator = null, TranslationNodeVisitorInterface $translationNodeVisitor = null)
```
Comment (fabpot) [inline src/Symfony/Bridge/Twig/Extension/TranslationExtension.php:37]: Let's not create a new interface and type hint with `TranslationNodeVisitor` instead.

**Review by fabpot — CHANGES_REQUESTED** [review]
This change should be for master.

File: src/Symfony/Bridge/Twig/Extension/TranslationExtension.php (hunk 1 above)
Comment (dbrekelmans) [reply src/Symfony/Bridge/Twig/Extension/TranslationExtension.php:37]: That would limit flexibility without much benefit.

I have a use case for passing a different node visitor into this class (basically overwriting the trans function and adding an extra parameter). That was possible in symfony 4.4, because there was no return typehint on the getter. I came across this trying to upgrade to symfony ^5.0.

It's up to you. If you still prefer the concrete class typehint then I will change it. Let me know @fabpot 👍

**Comment by fabpot** [comment]
Not a big fan of adding such an interface TBH. Your implementation extends the core one, right? In which case, type hinting with the class is not an issue.

**Comment by dbrekelmans** [comment]
My implementation does not extend the core one as the core one is declared final.

As it stands we've already had to copy and modify a few core classes (TransNode for example) to make our implementation work, so to upgrade to symfony 5 we could do the same with TranslationExtension.

I will change the typehint to `TranslationNodeVisitor` and target master.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Looks like there is an unrelated commit in the PR. Can you get rid of it?

**Comment by dbrekelmans** [comment]
> Looks like there is an unrelated commit in the PR. Can you get rid of it?

Done 👍

**Comment by fabpot** [comment]
Thank you @dbrekelmans.
