### PR TITLE
[DoctrineBridge] Fix `UniqueEntityValidator` with proxy object

### LINKED ISSUE #57075: [DoctrineBridge] issues with UniqueEntityValidator on 7.1-RC1
### Symfony version(s) affected

7.1 RC1

### Description

I just tested 7.1 RC1 on my biggest app and I noticed this error:

```
ReflectionException:
Property Proxies\__CG__\CA\Core\UserBundle\Entity\User::$email does not exist

  at vendor/symfony/doctrine-bridge/Validator/Constraints/UniqueEntityValidator.php:298
``` 

### How to reproduce

~~Unfortunately I cannot reproduce this issue yet on a smaller app like `symfony-demo`. Still looking into it :confused:~~
See https://github.com/symfony/symfony/issues/57075#issuecomment-2127108177

### Possible Solution

use `PropertyAccessor` to get the value [here](https://github.com/symfony/symfony/blob/46b9158159a1af12dfcd1aa0706fce75cce1c95d/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php#L300)?

### Additional Context

Downgrading DoctrineBridge and PropertyInfo to 7.0.7 solves the issue for me.

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #57075
| License       | MIT

Before #38662, `$fieldValue = $class->reflFields[$fieldName]->getValue($entity);` was used to get the value of a property, so it makes sense to keep using it when the object is an entity.

### CODE REVIEW

**Review by dmaicher — APPROVED** [review]
Thanks for looking into it :+1: 

LGTM

File: src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php [hunk 1]
```diff
@@ -287,7 +287,9 @@ private function getFieldValues(mixed $object, ClassMetadata $class, array $fiel
                 throw new ConstraintDefinitionException(sprintf('The field "%s" is not a property of class "%s".', $fieldName, $objectClass));
             }
 
-            $fieldValues[$entityFieldName] = $this->getPropertyValue($objectClass, $fieldName, $object);
+            $fieldValues[$entityFieldName] = $isValueEntity && $object instanceof ($class->getName())
```
Comment (dmaicher) [inline src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php:290]: Hm could we potentially have the same problem in case `$isValueEntity` is true but `$object instanceof ($class->getName())` is false? 

When is that the case actually :thinking: Is it if I just pass a different `entityClass` on the constraint?

Comment (HypeMC) [reply src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php:290]: According to the tests, when that happens, an exception is thrown, see:

https://github.com/symfony/symfony/blob/99f279b3383efd4f88ac79f1ad0572cf7b9bf1de/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php#L133-L139

Comment (dmaicher) [reply src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php:290]: Ok got it :+1:

**Review by wkania — APPROVED** [review]

File: src/Symfony/Bridge/Doctrine/Tests/Validator/Constraints/UniqueEntityValidatorTest.php [hunk 2]
```diff
@@ -109,6 +115,10 @@ protected function createEntityManagerMock($repositoryMock)
         $classMetadata = $this->createMock(
             class_exists(ClassMetadataInfo::class) ? ClassMetadataInfo::class : ClassMetadata::class
         );
+        $classMetadata
+            ->method('getName')
+            ->willReturn($repositoryMock->getClassName())
+        ;
```
Comment (xabbuh) [inline src/Symfony/Bridge/Doctrine/Tests/Validator/Constraints/UniqueEntityValidatorTest.php:121]: This change does not seem to be needed.

File: src/Symfony/Bridge/Doctrine/Tests/Validator/Constraints/UniqueEntityValidatorTest.php [hunk 3]
```diff
@@ -90,12 +91,17 @@ protected function createRegistryMock($em = null)
...
-    protected function createRepositoryMock()
+    protected function createRepositoryMock(string $className)
     {
-        return $this->getMockBuilder(MockableRepository::class)
+        $repositoryMock = $this->getMockBuilder(MockableRepository::class)
             ->disableOriginalConstructor()
             ->onlyMethods(['find', 'findAll', 'findOneBy', 'findBy', 'getClassName', 'findByCustom'])
             ->getMock();
+
+        $repositoryMock->method('getClassName')
```
Comment (xabbuh) [inline src/Symfony/Bridge/Doctrine/Tests/Validator/Constraints/UniqueEntityValidatorTest.php:101]: This change does not seem to be needed.

File: src/Symfony/Bridge/Doctrine/Tests/Validator/Constraints/UniqueEntityValidatorTest.php (hunk 2 above)
Comment (HypeMC) [reply src/Symfony/Bridge/Doctrine/Tests/Validator/Constraints/UniqueEntityValidatorTest.php:121]: @xabbuh Actually, this is need to pass lowest deps: https://github.com/HypeMC/symfony/actions/runs/9289115507/job/25562199480 . The reason it fails is because of the following logic: https://github.com/symfony/symfony/blob/31c597fe3ed692dcbd8dbe2f6e2af63cd4a1c679/src/Symfony/Bridge/Doctrine/Tests/Validator/Constraints/UniqueEntityValidatorTest.php#L109-L111

The `ClassMetadataInfo::getName()` method [doesn't have a return type](https://github.com/doctrine/orm/blob/4a01a76a17f10851393db48efddcbf3377938a3d/src/Mapping/ClassMetadataInfo.php#L3575-L3578) so `null` is returned, while `ClassMetadata::getName()` [does](https://github.com/doctrine/orm/blob/9d4f54b9a476f13479c3845350b12c466873fc42/src/Mapping/ClassMetadata.php#L2456-L2459), so an empty string is returned which doesn't cause an error.

**Review by xabbuh — APPROVED** [review]

**Review by stof — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you @HypeMC.
