### PR TITLE
[Validator] Add BC layer for notInRangeMessage when min and max are set

### LINKED ISSUE #36133: [Validation][Range] Message not properly translated
**Symfony version(s) affected**: 4.4.5

**Description**  
When upgrading an application from 4.3 to 4.4, I've noticed that for the only Range constraint that I use the ConstraintViolation message which was the translated on 4.3 is now replaced by the default message.

**How to reproduce**
reproducer :
```php
<?php
require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Validator\Validation;
use Symfony\Component\Validator\Constraints;
use Symfony\Component\Translation\Translator;
use Symfony\Component\Translation\Loader\ArrayLoader;

$translator = new Translator('en_GB');
$translator->addLoader('array', new ArrayLoader());
$translator->addResource('array', [
    'violation.minMessage' => 'Bad guy !',
    'violation.maxMessage' => 'really really really bad guy !',
], 'en_GB');

$rangeConstraint = new Constraints\Range([
	'min' => 0,
	'max' => 2,
	'minMessage' => 'violation.minMessage',
	'maxMessage' => 'violation.maxMessage'
]);
$validatorBuilder = Validation::createValidatorBuilder();
$validatorBuilder->setTranslator($translator);
$validator = $validatorBuilder->getValidator();

$violations = $validator->validate(-1, [
    $rangeConstraint
]);

foreach ($violations as $violation) {
	dump($violation->getMessage());	
}

$violations = $validator->validate(3, [
    $rangeConstraint
]);

foreach ($violations as $violation) {
	dump($violation->getMessage());	
}
```
composer.json :
```json
{
	"require": {
		"symfony/validator" : "4.4.*",
		"symfony/translation": "4.4.*",
		"symfony/var-dumper": "4.4.*"
	}
}
```

this, displays the following :
```
"This value should be between 0 and 2."
"This value should be between 0 and 2."
```

Instead of displaying :
```
"Bad guy !"
"really really really bad guy !"
```

**Possible Solution**  

No idea for the moment.

**Additional context**

### PR DESCRIPTION
**Pull request by l-vo**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36133
| License       | MIT
| Doc PR        | 

According to #36133, the improvement added in  #32435 may lead to a BC break when the developer pass `min` and `max` options and a custom `minMessage` or `maxMessage`. In this case it's expected to receive a `minMessage`/`maxMessage` in the violation but a `notInRangeMessage` is received instead.

So in the following conditions:
- `min` and `max` options are set
- `minMessage` or `maxMessage` is set

A deprecation is triggered. If a limit is violated and matches to the min/max message passed as option (`minMessage` for `min` violated and `maxMessage` for `max` violated), `minMessage/maxMessage` is used in the violation instead of `notInRangeMessage`.

### CODE REVIEW

**Comment by dmaicher** [comment]
Also see https://github.com/symfony/symfony/issues/33700

I also noticed that and back then we decided to document this small behavior change.

File: src/Symfony/Component/Validator/Constraints/RangeValidator.php [hunk 1]
```diff
@@ -157,7 +170,7 @@ private function getLimit($propertyPath, $default, Constraint $constraint)
         try {
             return $this->getPropertyAccessor()->getValue($object, $propertyPath);
         } catch (NoSuchPropertyException $e) {
-            throw new ConstraintDefinitionException(sprintf('Invalid property path "%s" provided to "%s" constraint: %s.', $propertyPath, \get_class($constraint), $e->getMessage()), 0, $e);
+            throw new ConstraintDefinitionException(sprintf('Invalid property path "%s" provided to "%s" constraint: "%s".', $propertyPath, \get_class($constraint), $e->getMessage()), 0, $e);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraints/RangeValidator.php]: not sure about this change

File: src/Symfony/Component/Validator/Tests/Constraints/RangeTest.php [hunk 2]
```diff
@@ -40,4 +43,31 @@ public function testThrowsNoDefaultOptionConfiguredException()
...
+    }
+
+    /**
+     * @group legacy
+     * @dataProvider provideDeprecationTriggeredIfMinMaxAndMinMessageOrMaxMessageSet
+     */
+    public function testDeprecationTriggeredIfMinMaxAndMinMessageOrMaxMessageSet(array $options, bool $expectedDeprecatedMinMessageSet, bool $expectedDeprecatedMaxMessageSet, bool $expectedDeprecation)
+    {
+        if ($expectedDeprecation) {
+            $this->expectDeprecation('Since symfony/validator 4.4: minMessage and maxMessage are deprecated when min and max options are set together. Use notInRangeMessage instead.');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Tests/Constraints/RangeTest.php]: 4.4 should still use the annotation

File: src/Symfony/Component/Validator/Constraints/Range.php [hunk 3]
```diff
@@ -46,6 +46,17 @@ class Range extends Constraint
     public $max;
     public $maxPropertyPath;
 
+    // BC layer, to remove in 6.0
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraints/Range.php]: why not 5.0?

File: src/Symfony/Component/Validator/Constraints/RangeValidator.php (hunk 1 above)
Comment (l-vo) [reply src/Symfony/Component/Validator/Constraints/RangeValidator.php]: Fabbot fails on it: Capture d’écran 2020-03-19 à 21 39 20

Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/Constraints/RangeValidator.php]: This rule has false positives, this looks one of them.

Comment (l-vo) [reply src/Symfony/Component/Validator/Constraints/RangeValidator.php]: Ok 👌

File: src/Symfony/Component/Validator/Tests/Constraints/RangeTest.php (hunk 2 above)
Comment (l-vo) [reply src/Symfony/Component/Validator/Tests/Constraints/RangeTest.php]: Indeed, my bad ! Thanks.

File: src/Symfony/Component/Validator/Constraints/Range.php (hunk 3 above)
Comment (l-vo) [reply src/Symfony/Component/Validator/Constraints/Range.php]: Indeed the new behavior is already present in 5.0.0, changed.

**Comment by chalasr** [comment]
Adding a BC layer on a maintenance branch feels wrong to me, you shouldn't get new deprecation notices in a patch release. The BC break should either be reverted or documented instead.

File: src/Symfony/Component/Validator/Constraints/Range.php [hunk 4]
```diff
@@ -46,6 +46,17 @@ class Range extends Constraint
     public $max;
     public $maxPropertyPath;
 
+    // BC layer, to remove in 5.0
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/Constraints/Range.php]: [...] to be removed in 5.0

File: src/Symfony/Component/Validator/Constraints/Range.php [hunk 5]
```diff
@@ -60,6 +71,15 @@ public function __construct($options = null)
             if ((isset($options['minPropertyPath']) || isset($options['maxPropertyPath'])) && !class_exists(PropertyAccess::class)) {
                 throw new LogicException(sprintf('The "%s" constraint requires the Symfony PropertyAccess component to use the "minPropertyPath" or "maxPropertyPath" option.', static::class));
             }
+
+            if (isset($options['min']) && isset($options['max'])) {
+                $this->deprecatedMinMessageSet = isset($options['minMessage']);
+                $this->deprecatedMaxMessageSet = isset($options['maxMessage']);
+
+                if ($this->deprecatedMinMessageSet || $this->deprecatedMaxMessageSet) {
+                    @trigger_error('Since symfony/validator 4.4: minMessage and maxMessage are deprecated when min and max options are set together. Use notInRangeMessage instead.', E_USER_DEPRECATED);
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/Constraints/Range.php]: [...] when the "min" and "max" options are both set [...]

Comment (l-vo) [reply src/Symfony/Component/Validator/Constraints/Range.php]: Fixed, thanks !

**Comment by nicolas-grekas** [comment]
> The BC break should either be reverted or documented instead

Reverting would mean breaking BC on 5.0 - Documenting is what this PR is about.
If we missed triggering a deprecation while something has been deprecated, adding this deprecation is a bug fix to me.

Note that I didn't get the patch so I'm just commenting on the process :)

File: src/Symfony/Component/Validator/Constraints/Range.php [hunk 6]
```diff
@@ -60,6 +71,15 @@ public function __construct($options = null)
             if ((isset($options['minPropertyPath']) || isset($options['maxPropertyPath'])) && !class_exists(PropertyAccess::class)) {
                 throw new LogicException(sprintf('The "%s" constraint requires the Symfony PropertyAccess component to use the "minPropertyPath" or "maxPropertyPath" option.', static::class));
             }
+
+            if (isset($options['min']) && isset($options['max'])) {
+                $this->deprecatedMinMessageSet = isset($options['minMessage']);
+                $this->deprecatedMaxMessageSet = isset($options['maxMessage']);
+
+                if ($this->deprecatedMinMessageSet || $this->deprecatedMaxMessageSet) {
+                    @trigger_error('Since symfony/validator 4.4: "minMessage" and "maxMessage" are deprecated when the "min" and "max" options are both set. Use "notInRangeMessage" instead.', E_USER_DEPRECATED);
```
Comment (HeahDude) [inline src/Symfony/Component/Validator/Constraints/Range.php:80]: It means we also miss an exception here in 5.0, and maybe that should be part of the message.

Comment (l-vo) [reply src/Symfony/Component/Validator/Constraints/Range.php:80]: I'm not sure to understand, what should be part of the message please ?

Comment (HeahDude) [reply src/Symfony/Component/Validator/Constraints/Range.php:80]: ```Since symfony/validator 4.4: "minMessage" and "maxMessage" are deprecated when the "min" and "max" options are both set. You should use "notInRangeMessage" instead or an exception will be thrown in 5.0.`

Comment (dmaicher) [reply src/Symfony/Component/Validator/Constraints/Range.php:80]: But we cannot add an Exception here in a patch release of 5.0.x, right? This would be quite a BC break

Comment (stof) [reply src/Symfony/Component/Validator/Constraints/Range.php:80]: well, we have a default `notInRangeMessage` in 5.0. So 5.0 will not throw an exception. It will use the built-in message even you you might have intended to use a custom one.

Comment (HeahDude) [reply src/Symfony/Component/Validator/Constraints/Range.php:80]: >even if you might have intended to use a custom one

Sounds like a silent failure, the deprecation should be replaced by an exception in 5.0 or master IMO because the intended message won't be used.

**Comment by fabpot** [comment]
@l-vo What's the status here?

**Comment by l-vo** [comment]
@fabpot from my point of view the fix itself is finished, the blocking point is more a discussion between contributors/core members about what should be done here.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @l-vo.

**Comment by fabpot** [comment]
@l-vo I've merge 4.4 into 5.1, can you create a PR for 5.1 where you remove the BC layer?

**Comment by l-vo** [comment]
Of course, I'm AFAK today but I'm doing it tomorrow.

**Comment by l-vo** [comment]
@fabpot Do we really want to remove the BC layer in 5.x ? In the early 5.0 and 5.1 versions, the behavior of `Range` changed but no deprecations was triggered. If the BC layer is removed now, some users of 5.0 and 5.1 will never be noticed that the behavior has changed. Removing it in 6.0 will allow all the users to be noticed. What is your point of view about that please ? All users must be noticed or it's and edge case with minor impact and it can be removed right now ?

**Comment by fabpot** [comment]
@l-vo Right, let's remove it for 6.0.
