### PR TITLE
[Console] Handle calls to mb_ functions with non string arguments

### LINKED ISSUE #40200: Call to mb_* functions on a null string (PHP8.1-incompatible)
**Symfony version(s) affected**: (at least) 4.4.19

**Description**  
`Symfony\Component\Console\Helper::strlen` calls `mb_detect_encoding`
`$string` argument is typed as string in phpdoc, but this function is sometimes called with a null argument (in the "reproduce" case, it's the getShortcut() of a command definition option)

In the mbstring polyfill, `mb_detect_encoding` requires first argument to be string.

But in fact, despite what is said the documentation, in the real mbstring implementation, `mb_detect_encoding` accepts a first argument which is null.

**How to reproduce**  
With a php8.0 binary **with php8.0-mbstring NOT installed**, run `bin/console help`.

> Description:
>   Displays help for a command
> 
> Usage:
>   help [options] [--] <command> [<command_name>]
> 
> [error] Error thrown while running command "help". Message: "mb_detect_encoding(): Argument #&#8203;1 ($string) must be of type string, null given, called in /data/sources/sites/mmeb2/vendor/symfony/console/Helper/Helper.php on line 54"
> 
> [critical] Uncaught Error: mb_detect_encoding(): Argument #&#8203;1 ($string) must be of type string, null given, called in /data/sources/sites/mmeb2/vendor/symfony/console/Helper/Helper.php on line 54
> 
> 
> **In bootstrap80.php line 48:**
>                                                                                                                                                                            
> **mb_detect_encoding(): Argument #&#8203;1 ($string) must be of type string, null given, called in /data/sources/sites/mmeb2/vendor/symfony/console/Helper/Helper.php on line 54 **
>                                                                                                                                                                            
> 
> help [--format FORMAT] [--raw] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<command_name>]

**Proposed solution (part 1) : Fix the polyfill**
In bootstrap80.php, don't typehint the first argument, so has to have the same behaviour than the mbstring php extension.

**Proposed solution (part 2) : Workaround for the use of a null argument**
In Symfony\Component\Console\Helper::strlen, test if `$string` is null, and if so return 0 (or set `$string = ''`, but it's not really necessary)

**Proposed solution (part 3) : Deprecate the use of a null argument**
- Mark calls with a null argument as deprecated, and check calls in Symfony code
- For next major version, hard type `$string` as string, and remove test added in part 2.

**Additional context**  
Can't be reproduced in online sandbox testers, as they've got installed mbstring.
Must be checked in other php versions.

### PR DESCRIPTION
**Pull request by Yopai**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40200
| License       | MIT
| Doc PR        | no

In PHP8.1, a number of functions who were accepting null arguments will only accept
string ones.
(see https://wiki.php.net/rfc/deprecate_null_to_scalar_internal_arg)

In the polyfill, mb_* functions are already declared with a strict type checking of "string".

Therefore, it is necessary to get rid of the use of non string arguments when calling mb_* functions,
so that it won't break when either using the polyfill,or future php8 versions.

In every call where the argument may not be a string, this commit enforces the string type of the argument (with transtyping)

--- For reviewers
* I generally don't like transtyping, but found it was the more "secure" way (on a non-BC point of view) here.
Specially in Console/Helper/Table.php, where $cell can be an object (there are 2 "$cell instanceof ... tests)
However, where the argument can already be either null or string (and not anything else), there may a beter approach ?

* It's the first time I send a PR on symfony, so don't hesitate pointing me to thinks I've forgotten to done.

### CODE REVIEW

File: src/Symfony/Component/Console/Helper/Helper.php [hunk 1]
```diff
@@ -47,6 +47,9 @@ public function getHelperSet()
      */
     public static function strlen($string)
     {
+        if ( ! \is_string($string)) {
+            $string = (string)$string;
+        }
```
Comment (derrabus) [inline src/Symfony/Component/Console/Helper/Helper.php]:
```suggestion
        $string = (string) $string;
```

There are more places than this. We don't need to type-check here because a string cast on a string should be a no-op anyway.

File: src/Symfony/Component/Console/Helper/Table.php [hunk 2]
```diff
@@ -512,9 +512,11 @@ private function renderCell(array $row, int $column, string $cellFormat): string
...
         }
 
-        // str_pad won't work properly with multi-byte strings, we need to fix the padding
-        if (false !== $encoding = mb_detect_encoding($cell, null, true)) {
-            $width += \strlen($cell) - mb_strwidth($cell, $encoding);
+        if ( ! is_null($cell)) {
+            // str_pad won't work properly with multi-byte strings, we need to fix the padding
+            if (false !== $encoding = mb_detect_encoding((string)$cell, null, true)) {
+                $width += \strlen((string)$cell) - mb_strwidth((string)$cell, $encoding);
+            }
```
Comment (derrabus) [inline src/Symfony/Component/Console/Helper/Table.php]:
```suggestion
        // str_pad won't work properly with multi-byte strings, we need to fix the padding
        if (null !== $cell && false !== $encoding = mb_detect_encoding((string)$cell, null, true)) {
            $width += \strlen((string)$cell) - mb_strwidth((string)$cell, $encoding);
```

**Review by derrabus — CHANGES_REQUESTED** [review]

**Comment by derrabus** [comment]
Please also have a look at the CS errors fabbot reported.

**Comment by Yopai** [comment]
Thanks.
I fixed not-useful tests, and fix CS for what I modified.
And then I fixed use of shorttag, that fabbot indicated too.
(I pushed the commits again, is there anything else I have to do ?)

File: src/Symfony/Component/Mime/Test/Constraint/EmailHtmlBodyContains.php [hunk 3]
```diff
@@ -43,7 +43,7 @@ protected function matches($message): bool
             throw new \LogicException('Unable to test a message HTML body on a RawMessage or Message instance.');
         }
 
-        return false !== mb_strpos($message->getHtmlBody(), $this->expectedText);
+        return false !== mb_strpos((string) ($message->getHtmlBody()), $this->expectedText);
```
Comment (derrabus) [inline src/Symfony/Component/Mime/Test/Constraint/EmailHtmlBodyContains.php]:
```suggestion
        return false !== mb_strpos((string) $message->getHtmlBody(), $this->expectedText);
```

File: src/Symfony/Component/Mime/Test/Constraint/EmailTextBodyContains.php [hunk 4]
```diff
@@ -43,7 +43,7 @@ protected function matches($message): bool
             throw new \LogicException('Unable to test a message text body on a RawMessage or Message instance.');
         }
 
-        return false !== mb_strpos($message->getTextBody(), $this->expectedText);
+        return false !== mb_strpos((string) ($message->getTextBody()), $this->expectedText);
```
Comment (derrabus) [inline src/Symfony/Component/Mime/Test/Constraint/EmailTextBodyContains.php]:
```suggestion
        return false !== mb_strpos((string) $message->getTextBody(), $this->expectedText);
```

**Review by derrabus — CHANGES_REQUESTED** [review]
Sorry, I should've been more precise. You don't need to fix fabbot errors you haven't caused. In this case, the short tags were a false positive. Can you restore them?

**Comment by Yopai** [comment]
No worry (that's why I made it in a separate commit :) )
Done !

File: src/Symfony/Component/Form/Tests/Util/StringUtilTest.php [hunk 5]
```diff
@@ -34,7 +34,7 @@ public function testTrimUtf8Separators($hex)
         $binary = pack('H*', $hex);
 
         // Convert UCS-2BE to UTF-8
-        $symbol = mb_convert_encoding($binary, 'UTF-8', 'UCS-2BE');
+        $symbol = mb_convert_encoding((string) $binary, 'UTF-8', 'UCS-2BE');
```
Comment (derrabus) [inline src/Symfony/Component/Form/Tests/Util/StringUtilTest.php]: Do we need this change? `pack()` should always return a string, shouldn't it?

**Review by derrabus — APPROVED** [review]

File: src/Symfony/Component/Form/Tests/Util/StringUtilTest.php (hunk 5 above)
Comment (Yopai) [reply src/Symfony/Component/Form/Tests/Util/StringUtilTest.php]: From the doc : it can return false on error. As I'm not sure if/how such an error is handled, I've prefered transtyping it too. But I can remove it if you think it's unnecessary.

Comment (derrabus) [reply src/Symfony/Component/Form/Tests/Util/StringUtilTest.php]: > it can return false on error

On PHP 8, we should get a `ValueError` instead. So on PHP 8.1 we can be certain that `$binary` is a string. So yes, please revert this line.

File: src/Symfony/Component/Console/Helper/Table.php [hunk 6]
```diff
@@ -513,8 +513,8 @@ private function renderCell(array $row, int $column, string $cellFormat): string
         }
 
         // str_pad won't work properly with multi-byte strings, we need to fix the padding
-        if (false !== $encoding = mb_detect_encoding($cell, null, true)) {
-            $width += \strlen($cell) - mb_strwidth($cell, $encoding);
+        if (null !== $cell && false !== $encoding = mb_detect_encoding((string) $cell, null, true)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Helper/Table.php]: `$cell` can't be null here
if the cast to string is needed, let's make it happen once

File: src/Symfony/Component/HttpFoundation/BinaryFileResponse.php [hunk 7]
```diff
@@ -155,6 +155,8 @@ public function setAutoEtag()
      */
     public function setContentDisposition($disposition, $filename = '', $filenameFallback = '')
     {
+        $filename = (string) $filename;
+
         if ('' === $filename) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/BinaryFileResponse.php]: if ('' === ($filename ?? '')) {

File: src/Symfony/Component/Mime/Test/Constraint/EmailHtmlBodyContains.php [hunk 8]
```diff
@@ -43,7 +43,7 @@ protected function matches($message): bool
             throw new \LogicException('Unable to test a message HTML body on a RawMessage or Message instance.');
         }
 
-        return false !== mb_strpos($message->getHtmlBody(), $this->expectedText);
+        return false !== mb_strpos((string) $message->getHtmlBody(), $this->expectedText);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mime/Test/Constraint/EmailHtmlBodyContains.php]: can't happen, only RawMessage is allowed

File: src/Symfony/Component/Mime/Test/Constraint/EmailTextBodyContains.php [hunk 9]
```diff
@@ -43,7 +43,7 @@ protected function matches($message): bool
             throw new \LogicException('Unable to test a message text body on a RawMessage or Message instance.');
         }
 
-        return false !== mb_strpos($message->getTextBody(), $this->expectedText);
+        return false !== mb_strpos((string) $message->getTextBody(), $this->expectedText);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mime/Test/Constraint/EmailTextBodyContains.php]: can't happen

File: src/Symfony/Component/Translation/Dumper/IcuResFileDumper.php [hunk 10]
```diff
@@ -42,6 +42,8 @@ public function formatCatalogue(MessageCatalogue $messages, $domain, array $opti
         $keyTop = $this->getPosition($data);
 
         foreach ($messages->all($domain) as $source => $target) {
+            $target = (string) $target;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Dumper/IcuResFileDumper.php]: can really the target be null?

File: src/Symfony/Component/VarDumper/Dumper/CliDumper.php [hunk 11]
```diff
@@ -185,6 +185,8 @@ public function dumpScalar(Cursor $cursor, $type, $value)
      */
     public function dumpString(Cursor $cursor, $str, $bin, $cut)
     {
+        $str = (string) $str;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/VarDumper/Dumper/CliDumper.php]: cannot be null

File: src/Symfony/Component/HttpFoundation/BinaryFileResponse.php (hunk 7 above)
Comment (Yopai) [reply src/Symfony/Component/HttpFoundation/BinaryFileResponse.php]: Why not simplier `if (!$filename)` ?

Or `if (empty($filename))` ?

File: src/Symfony/Component/Console/Helper/Table.php (hunk 6 above)
Comment (Yopai) [reply src/Symfony/Component/Console/Helper/Table.php]: Done.

File: src/Symfony/Component/HttpFoundation/BinaryFileResponse.php (hunk 7 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/BinaryFileResponse.php]: it wouldn't be the same, as `'0'` is false|empty

Comment (Yopai) [reply src/Symfony/Component/HttpFoundation/BinaryFileResponse.php]: (We could also assume that filename is necessarily a string, as phpdoc doesn't allow it to be null, is it right ?)

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/BinaryFileResponse.php]: I believe so yes

File: src/Symfony/Component/Console/Helper/Table.php [hunk 12]
```diff
@@ -513,8 +513,9 @@ private function renderCell(array $row, int $column, string $cellFormat): string
         }
 
         // str_pad won't work properly with multi-byte strings, we need to fix the padding
-        if (false !== $encoding = mb_detect_encoding($cell, null, true)) {
-            $width += \strlen($cell) - mb_strwidth($cell, $encoding);
+        $cellstr = (string) $cell;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Helper/Table.php]: $cell as name would save renaming below,thus save merge conflicts, please keep the name

File: src/Symfony/Component/Form/Tests/Util/StringUtilTest.php (hunk 5 above)
Comment (Yopai) [reply src/Symfony/Component/Form/Tests/Util/StringUtilTest.php]: Done.

File: src/Symfony/Component/Console/Helper/Table.php (hunk 12 above)
Comment (Yopai) [reply src/Symfony/Component/Console/Helper/Table.php]: I would have done it if `$cell` wasn't used below :
`$cell instanceof TableSeparator`

Do you prefer that I store `$cell instanceof TableSeparator` in a variale, so I can rewrite this as

	$isTableSeparator = ($cell instanceof TableSeparator)

	$cell = (string) $cell;
	if (false !== $encoding = mb_detect_encoding($cell, null, true)) {
		$width += \strlen($cell) - mb_strwidth($cell, $encoding);
	}

	$style = $this->getColumnStyle($column);

	if ($isTableSeparator) {
		return sprintf($style->getBorderFormat(), str_repeat($style->getBorderChars()[2], $width));
	}

Comment (nicolas-grekas) [reply src/Symfony/Component/Console/Helper/Table.php]: Oh, I missed this.
But: is this needed at all? $cell cannot be null here.

Comment (Yopai) [reply src/Symfony/Component/Console/Helper/Table.php]: I must have missed something, I wonder how you can be sure ?
In fact, addRow is public, and can take an array of anything, since nothing enforces the type of the elements. So, IMHO, in renderRow, you can't assume anything on the type of elements of row. And, therefore, you can't assume anything on the type of $cell.

BTW, even if it was right, the aim of this PR is to avoid errors when upgrading to PHP8.1 (or to the usage of the polyfill) by transtyping _before_ the call to the mb_ function, rather than relying on the implict cast done until php8.0

I originally had the problem with a null value, you're right, but the problem is not related with the value being null, it is related with the value being anything else than a string.
Arguments of mb_* functions _must_ be a string (in PHP8.1, and therefore it has been coded in the polyfill). Passing them an object won't be good.

So :
- In any way, it can be an object (since code is testing for it)
- It comes from a public method, with no type checking - not even in phpdoc -, so I don't see how you can assume anything about its type.

(All that being said, I am perfectly conscious about the work you provide, and the very good knowledge of this code you have. That's why you're reviewers and I'm just a first-time request-puller :) )

Comment (nicolas-grekas) [reply src/Symfony/Component/Console/Helper/Table.php]: Passing them a Stringable object will continue to work, isn't it?
That's how this piece of code is designed to me, and it's fine as is.

File: src/Symfony/Component/Mime/Test/Constraint/EmailHtmlBodyContains.php (hunk 8 above)
Comment (Yopai) [reply src/Symfony/Component/Mime/Test/Constraint/EmailHtmlBodyContains.php]: The type hinting of getHtmlBody() says "null|resource|string".

In fact, looking for the type of $message (assuming the phpdoc type is respected - even if it is not strictly enforced with type hinting), we can assume :
- that $message is an "instanceof" RawMessage 
- but not directly a RawMessage or a Message.
Nothing ensures its getText/HtmlBody method returns a string. Nor it even exists.

Maybe this classes would require a refactoring, with creation of an interface ?

Comment (Yopai) [reply src/Symfony/Component/Mime/Test/Constraint/EmailHtmlBodyContains.php]: (but it's outside the scope of this PR)

File: src/Symfony/Component/HttpFoundation/BinaryFileResponse.php (hunk 7 above)
Comment (Yopai) [reply src/Symfony/Component/HttpFoundation/BinaryFileResponse.php]: Ok, I'll remove the typecast.

File: src/Symfony/Component/VarDumper/Dumper/CliDumper.php (hunk 11 above)
Comment (Yopai) [reply src/Symfony/Component/VarDumper/Dumper/CliDumper.php]: You're right, didn't see the phpdoc on interface.
Fixed.

File: src/Symfony/Component/Translation/Dumper/IcuResFileDumper.php (hunk 10 above)
Comment (Yopai) [reply src/Symfony/Component/Translation/Dumper/IcuResFileDumper.php]: Strictly speaking, there's no type hinting on MessageCatalogue::$messages
But... Okay, there are supposed to be strings.
Fixed

File: src/Symfony/Component/Mime/Test/Constraint/EmailHtmlBodyContains.php (hunk 8 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Mime/Test/Constraint/EmailHtmlBodyContains.php]: I'm for fixing things that are actual issues.
If you can add a test case for this, I'm fine :)
But then, we should also handle the case where a resource is returned.

File: src/Symfony/Component/Console/Helper/Table.php (hunk 12 above)
Comment (Yopai) [reply src/Symfony/Component/Console/Helper/Table.php]: AFAIK, the prototype of the mb_ functions is marked (in the php documentation) as "string", not "string|Stringable"

And if I undesrtand correctly https://php.watch/versions/8.0/stringable, this has been implemented this way (I mean, a type hinting of "string" doesn't seem to mean "string|Stringable")

But I'm not really sure, it would require the advice of an expert.

Well, wait a minute... I just saw the author of he RFC for Stringable is nobody else than you...
So it seems you're an expert :)

It's up to you to see : if I'm wrong, and mb_ functions accept string|Stringable although their prototype says "string", then you're right, and I can remove the cast.

Comment (nicolas-grekas) [reply src/Symfony/Component/Console/Helper/Table.php]: > mb_ functions accept string|Stringable although their prototype says "string"

Yes, that works, because we don't use strict mode (and we don't want to).

Comment (derrabus) [reply src/Symfony/Component/Console/Helper/Table.php]: > mb_ functions accept string|Stringable although their prototype says "string"

They do, unless you enable `strict_types`. 🙃

Comment (Yopai) [reply src/Symfony/Component/Console/Helper/Table.php]: Okay, then.
Fixed

File: src/Symfony/Component/Mime/Test/Constraint/EmailHtmlBodyContains.php (hunk 8 above)
Comment (Yopai) [reply src/Symfony/Component/Mime/Test/Constraint/EmailHtmlBodyContains.php]: For the case a resource is returned, the difference is: it won't break _more_ with PHP8.1 or the polyfill, because it will _already_ break.

Again: I checked (at your demand!) what could be checked, i.e when the type error could occur with PHP8.1 although it doesn't occur with previous PHP versions. Even if someone "misuse" the code, like calling addRow with an array of whatever he wants.

All my edits had to reduce inconsistency between current and future php versions / polyfill. I'm just sorry it wouldn't have been understood like that.

File: src/Symfony/Component/ErrorHandler/Resources/views/exception.html.php [hunk 13]
```diff
@@ -16,7 +16,7 @@
 
     <div class="exception-message-wrapper">
         <div class="container">
-            <h1 class="break-long-words exception-message<?= mb_strlen($exceptionMessage) > 180 ? ' long' : ''; ?>"><?= $this->formatFileFromText(nl2br($exceptionMessage)); ?></h1>
+            <h1 class="break-long-words exception-message<?= mb_strlen((string) $exceptionMessage) > 180 ? ' long' : ''; ?>"><?= $this->formatFileFromText(nl2br($exceptionMessage)); ?></h1>
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ErrorHandler/Resources/views/exception.html.php]: can be removed also, the exception message cannot be null

Comment (Yopai) [reply src/Symfony/Component/ErrorHandler/Resources/views/exception.html.php]: done

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @Yopai.
