### PR TITLE
[HttpKernel] Fix handling of `MapRequest*` attributes

### LINKED ISSUE #50120: [HttpKernel] `#[MapRequestPayload]` is "handled" before `#[IsGranted]`
### Symfony version(s) affected

6.3

### Description

After playing a bit with [this new feature](https://symfony.com/blog/new-in-symfony-6-3-mapping-request-data-to-typed-objects), I noticed that the payload is getting mapped/validated **before** ensuring that the user is actually allowed to access the resource.

This seems odd to me and I'd like to know your opinion about that. 

### How to reproduce

1. create a route and its payload.
2. use the `#[MapRequestPayload]` attribute on the payload argument (in the controller)
3. secure the route using the `#[IsGranted]` attribute
4. access the route by posting some data (voluntarily malformed data) but without being logged-in
5. see the error message related to the malformed data (and not because the user is not logged-in)

### Possible Solution

Few years ago, I created a bundle to achieve the same thing that this feature is offering, and I encountered the same problem. 
I played around with the "priority" option but without luck. So my only solution was to create a listener on the [ControllerArgumentsEvent](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/HttpKernel/Event/ControllerArgumentsEvent.php) instead of using an ArgumentResolver. That way, the `#[IsGranted]` attribute would always be fired before my listener. No clue if I did things right at the time, but that's what worked for me.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #50120
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by artyuum** [comment]
@nicolas-grekas I cloned your repo, checked out your branch and used the `link` script to copy that specific version of Symfony into a working Sf project and I'm having the following error (even after nuking the cache):
> Attempted to call an undefined method named "onKernelControllerArguments" of class "Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver".

<details><summary>Stacktrace</summary>

```text
Symfony\Component\ErrorHandler\Error\UndefinedMethodError:
Attempted to call an undefined method named "onKernelControllerArguments" of class "Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver".

  at /var/www/html/test/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:116
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
     (/var/www/html/test/vendor/symfony/event-dispatcher/EventDispatcher.php:220)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
     (/var/www/html/test/vendor/symfony/event-dispatcher/EventDispatcher.php:56)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
     (/var/www/html/test/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:139)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
     (/var/www/html/test/vendor/symfony/http-kernel/HttpKernel.php:161)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (/var/www/html/test/vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (/var/www/html/test/vendor/symfony/http-kernel/EventListener/ErrorListener.php:108)
  at Symfony\Component\HttpKernel\EventListener\ErrorListener->onKernelException()
     (/var/www/html/test/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:116)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
     (/var/www/html/test/vendor/symfony/event-dispatcher/EventDispatcher.php:220)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
     (/var/www/html/test/vendor/symfony/event-dispatcher/EventDispatcher.php:56)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
     (/var/www/html/test/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:139)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
     (/var/www/html/test/vendor/symfony/http-kernel/HttpKernel.php:224)
  at Symfony\Component\HttpKernel\HttpKernel->handleThrowable()
     (/var/www/html/test/vendor/symfony/http-kernel/HttpKernel.php:117)
  at Symfony\Component\HttpKernel\HttpKernel->terminateWithException()
     (/var/www/html/test/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php:74)
  at Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::Symfony\Component\HttpKernel\EventListener\{closure}()
     (/var/www/html/test/vendor/symfony/error-handler/ErrorHandler.php:537)
  at Symfony\Component\ErrorHandler\ErrorHandler->handleException()
```

</details> 

Do you have the same error?

**Comment by nicolas-grekas** [comment]
Yes, I do. This should now be fixed. Can you please try again?

**Comment by artyuum** [comment]
@nicolas-grekas it works. I commented on the issue.

**Comment by Koc** [comment]
We should be careful with usage of the payload as Subject from Controller Arguments in [`#[IsGranted`](https://symfony.com/doc/current/security/expressions.html) Attribute

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/web.php [hunk 1]
```diff
@@ -63,14 +63,24 @@
...
             ->tag('controller.argument_value_resolver', ['priority' => 100, 'name' => DateTimeValueResolver::class])
 
-        ->set('argument_resolver.request_payload', RequestPayloadValueResolver::class)
+        ->set('request_payload_value_resolver', RequestPayloadValueResolver::class)
             ->args([
                 service('serializer'),
                 service('validator')->nullOnInvalid(),
                 service('translator')->nullOnInvalid(),
             ])
+            ->lazy()
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/web.php]: I made this lazy to prevent instantiating the serialize+validator+translator tuple on controllers that don't use `MapRequest*`.

**Review by nicolas-grekas — COMMENTED** [review]
> We should be careful with usage of the payload as Subject from Controller Arguments in [#[IsGranted](https://symfony.com/doc/current/security/expressions.html) Attribute

Accessing unserialized payloads in `#[IsGranted]` directly contradicts the expectations described in #50120: the expectation there is that a payload shouldn't be parsed if we can rule out access to some route before said parsing happens, which makes sense to me.

One way to solve this would be to allow registering an IsGranted attribute for late evaluation, aka after other controller argument listeners. There might be others.

Let's merge this PR and solve late the case of accessing the parsed subject from IsGranted?

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/web.php (hunk 1 above)
Comment (Koc) [reply src/Symfony/Bundle/FrameworkBundle/Resources/config/web.php]: but why do we need this workaround with `current` and array?

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/Resources/config/web.php]: > we need this workaround with current

I had to do this because I needed to register the service as both a listener and a resolver, which is something that was not allowed by the way traceable resolvers were wired. I fixed this so I could remove the special definitions.

**Comment by nicolas-grekas** [comment]
I updated the way traceable resolvers and serializers are wired so that we don't rely on service decoration, but use standard decoration instead. This preserves the definition of the original decorated service, so that we can e.g. use several tags on them without conflicts.

**Comment by nicolas-grekas** [comment]
PR rebased on top of #50158 to split the concern of decoration apart.

**Comment by nicolas-grekas** [comment]
PR rebased and ready.

**Review by derrabus — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thanks @nicolas-grekas.
