### PR TITLE
[SecurityBundle] Do not pass traceable authenticators to `security.helper`

### LINKED ISSUE #59341: [SecurityBundle] Login programmatically fails since 7.2.2 when passing authenticator name
### Symfony version(s) affected

7.2.2

### Description

Since https://github.com/symfony/symfony/pull/59278 I cannot login users programmatically anymore when passing an authenticator name and when in debug mode.

### How to reproduce

Works on 7.2.1 (for debug and also non-debug mode):

```php
/** @var \Symfony\Bundle\SecurityBundle\Security $security */
$security->login($user, authenticatorName: 'security.authenticator.remember_me.main');
```

but fails on 7.2.2 with
```
Unable to find an authenticator named "security.authenticator.remember_me.main" for the firewall "main". Available authenticators: "debug.security.authenticator.login_link.main", "debug.security.authenticator.remember_me.main".
``` 

### Possible Solution

Seems to be caused by https://github.com/symfony/symfony/pull/59278 

cc @MatTheCat 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59341
| License       | MIT

Since #59278 authenticators are no longer aliases for their traceable version, which means calling `Security::login` with an authenticator ID won’t match its traceable ID, and fail.

Plus, `Security::login` using the traceable authenticators meant the profiler could show them as successful while not supporting the request:

This PR fixes these issues by passing the original authenticators to `security.helper`, using their ID as name.

### CODE REVIEW

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 1]
```diff
@@ -501,7 +500,7 @@ private function createFirewall(ContainerBuilder $container, string $id, array $
         $configuredEntryPoint = $defaultEntryPoint;
 
         // authenticator manager
-        $authenticators = array_map(fn ($id) => new Reference($id), $firewallAuthenticationProviders);
+        $authenticators = array_map(fn ($id) => new Reference($id), $firewallAuthenticationProviders, []);
```
Comment (MatTheCat) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:504]: The added array’s purpose is to reset `$authenticators`’s key (cf https://www.php.net/manual/en/function.array-map.php#refsect1-function.array-map-returnvalues) so that `testConfigureCustomAuthenticator` doesn’t fail.

**Review by maxbeckers — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @MatTheCat.
