### PR TITLE
[TypeInfo] Return bound type as base type in `TemplateType`

### LINKED ISSUE #58031: Exception deserializing class with generic property
### Symfony version(s) affected

7.1.*

### Description

An excepion occurs in the `AbstractObjectNormalizer` when deserializing a class containing a generic property.

Exception: `Cannot get base type on "T" template type.`

Stacktrace:
```
Symfony\Component\TypeInfo\Exception\LogicException:
Cannot get base type on "T" template type.

  at C:\github\symfony-bug-normalizer\bug_app\vendor\symfony\type-info\Type\TemplateType.php:36
  at Symfony\Component\TypeInfo\Type\TemplateType->getBaseType()
     (C:\github\symfony-bug-normalizer\bug_app\vendor\symfony\serializer\Normalizer\AbstractObjectNormalizer.php:670)
  at Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->validateAndDenormalize()
     (C:\github\symfony-bug-normalizer\bug_app\vendor\symfony\serializer\Normalizer\AbstractObjectNormalizer.php:380)
  at Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denormalize()
     (C:\github\symfony-bug-normalizer\bug_app\vendor\symfony\serializer\Serializer.php:238)
  at Symfony\Component\Serializer\Serializer->denormalize()
     (C:\github\symfony-bug-normalizer\bug_app\src\Serializer\WrapperDenormalizer.php:32)
  at App\Serializer\WrapperDenormalizer->denormalize()
     (C:\github\symfony-bug-normalizer\bug_app\vendor\symfony\serializer\Serializer.php:238)
  at Symfony\Component\Serializer\Serializer->denormalize()
     (C:\github\symfony-bug-normalizer\bug_app\vendor\symfony\serializer\Serializer.php:143)
  at Symfony\Component\Serializer\Serializer->deserialize()
     (C:\github\symfony-bug-normalizer\bug_app\src\Controller\MyController.php:21)
  at App\Controller\MyController->index()
     (C:\github\symfony-bug-normalizer\bug_app\vendor\symfony\http-kernel\HttpKernel.php:183)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (C:\github\symfony-bug-normalizer\bug_app\vendor\symfony\http-kernel\HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (C:\github\symfony-bug-normalizer\bug_app\vendor\symfony\http-kernel\Kernel.php:182)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (C:\github\symfony-bug-normalizer\bug_app\vendor\symfony\runtime\Runner\Symfony\HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (C:\github\symfony-bug-normalizer\bug_app\vendor\autoload_runtime.php:29)
  at require_once('C:\\github\\symfony-bug-normalizer\\bug_app\\vendor\\autoload_runtime.php')
     (C:\github\symfony-bug-normalizer\bug_app\public\index.php:5)       
```

Note that the exception only occurs when `phpdocumentor/reflection-docblock` has been added.

### How to reproduce

Reproducer: https://github.com/ArieGato/symfony-issue-58031

start the symfony server and navigate to the root address

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by valtzu**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58031
| License       | MIT

This supersedes #58033 as simpler approach.

### CODE REVIEW

File: src/Symfony/Component/TypeInfo/Type/TemplateType.php [hunk 1]
```diff
@@ -33,7 +33,7 @@ public function __construct(
 
     public function getBaseType(): BuiltinType|ObjectType
     {
-        throw new LogicException(sprintf('Cannot get base type on "%s" template type.', $this));
```
Comment (mtarld) [inline src/Symfony/Component/TypeInfo/Type/TemplateType.php:36]: The `Symfony\Component\TypeInfo\Exception\LogicException` use must be removed I guess

**Review by mtarld — COMMENTED** [review]
Nice :+1:

**Review by mtarld — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @valtzu.
