### PR TITLE
[DependencyInjection][FrameworkBundle] Fix precedence of `App\Kernel` alias and ignore `container.excluded` tag on synthetic services

### LINKED ISSUE #60191: Symfony 7.3 cannot boot if the kernel implements CompilerPassInterface
### Symfony version(s) affected

7.3.latest

### Description

If the kernel implements CompilerPassInterface, Symfony cannot boot (only in HTTP, cli is OK)

```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException:
Service "kernel" not found: the container inside "Symfony\Component\DependencyInjection\Argument\ServiceLocator" is a smaller service locator that only knows about the "security.route_loader.logout" service.

  at /home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/DependencyInjection/ServiceLocator.php:137
  at Symfony\Component\DependencyInjection\ServiceLocator->createNotFoundException()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Contracts/Service/ServiceLocatorTrait.php:48)
  at Symfony\Component\DependencyInjection\ServiceLocator->doGet()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/DependencyInjection/ServiceLocator.php:43)
  at Symfony\Component\DependencyInjection\ServiceLocator->get()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/DependencyInjection/Argument/ServiceLocator.php:34)
  at Symfony\Component\DependencyInjection\Argument\ServiceLocator->get()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Routing/Loader/ContainerLoader.php:37)
  at Symfony\Component\Routing\Loader\ContainerLoader->getObject()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Routing/Loader/ObjectLoader.php:45)
  at Symfony\Component\Routing\Loader\ObjectLoader->load()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php:37)
  at Symfony\Component\Config\Loader\DelegatingLoader->load()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Bundle/FrameworkBundle/Routing/DelegatingLoader.php:65)
  at Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader->load()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php:72)
  at Symfony\Bundle\FrameworkBundle\Routing\Router->getRouteCollection()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Routing/Router.php:282)
  at Symfony\Component\Routing\Router->getMatcherDumperInstance()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Routing/Router.php:218)
  at Symfony\Component\Routing\Router->Symfony\Component\Routing\{closure}()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Config/ResourceCheckerConfigCacheFactory.php:34)
  at Symfony\Component\Config\ResourceCheckerConfigCacheFactory->cache()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Routing/Router.php:216)
  at Symfony\Component\Routing\Router->getMatcher()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Routing/Router.php:182)
  at Symfony\Component\Routing\Router->matchRequest()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:101)
  at Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:115)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:206)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:56)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:122)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:159)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/HttpKernel/Kernel.php:182)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/home/gregoire/dev/tmp/sf.7.3/vendor/autoload_runtime.php')
     (public/index.php:5)           
```

### How to reproduce

```
symfony new --webapp sf.7.3
cd sf.7.3
/home/gregoire/dev/github.com/lyrixx/symfony/link 
code src/Kernel.php 
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60191
| License       | MIT

Autoconfiguration cannot make a service abstract so I'm removing the related calls, they're confusing.

Then, I'm moving the definition of the `App\Kernel` alias after loading `services.yaml`, so that the alias overrides the discovered corresponding class.

And I make instance-of-conditionals ignore `container.excluded` tags on synthetic services. An alternative could be to check if the class implements `KernelInterface` like proposed in https://github.com/symfony/symfony/issues/60191#issuecomment-2858889476 but I think the rule I'm proposing here is more generic.

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -791,34 +791,34 @@ static function (ChildDefinition $definition, AsPeriodicTask|AsCronTask $attribu
...
-            $definition->addTag('container.excluded', ['source' => 'because it\'s a messenger message'])->setAbstract(true);
+            $definition->addTag('container.excluded', ['source' => 'because it\'s a messenger message']);
         });
         $container->registerAttributeForAutoconfiguration(\Attribute::class, static function (ChildDefinition $definition) {
-            $definition->addTag('container.excluded', ['source' => 'because it\'s an attribute'])->setAbstract(true);
+            $definition->addTag('container.excluded', ['source' => 'because it\'s an attribute']);
         });
         $container->registerAttributeForAutoconfiguration(Entity::class, static function (ChildDefinition $definition) {
-            $definition->addTag('container.excluded', ['source' => 'because it\'s a doctrine entity'])->setAbstract(true);
+            $definition->addTag('container.excluded', ['source' => 'because it\'s a doctrine entity']);
```
Comment (OskarStark) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]:
```suggestion
            $definition->addTag('container.excluded', ['source' => 'because it\'s a Doctrine entity']);
```

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 2]
```diff
@@ -791,34 +791,34 @@ static function (ChildDefinition $definition, AsPeriodicTask|AsCronTask $attribu
...
         });
         $container->registerAttributeForAutoconfiguration(Embeddable::class, static function (ChildDefinition $definition) {
-            $definition->addTag('container.excluded', ['source' => 'because it\'s a doctrine embeddable'])->setAbstract(true);
+            $definition->addTag('container.excluded', ['source' => 'because it\'s a doctrine embeddable']);
```
Comment (OskarStark) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]:
```suggestion
            $definition->addTag('container.excluded', ['source' => 'because it\'s a Doctrine embeddable']);
```

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 3]
```diff
@@ -791,34 +791,34 @@ static function (ChildDefinition $definition, AsPeriodicTask|AsCronTask $attribu
...
         });
         $container->registerAttributeForAutoconfiguration(MappedSuperclass::class, static function (ChildDefinition $definition) {
-            $definition->addTag('container.excluded', ['source' => 'because it\'s a doctrine mapped superclass'])->setAbstract(true);
+            $definition->addTag('container.excluded', ['source' => 'because it\'s a doctrine mapped superclass']);
```
Comment (OskarStark) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]:
```suggestion
            $definition->addTag('container.excluded', ['source' => 'because it\'s a Doctrine mapped superclass']);
```

File: src/Symfony/Component/DependencyInjection/Compiler/ResolveInstanceofConditionalsPass.php [hunk 4]
```diff
@@ -149,6 +149,11 @@ private function processDefinition(ContainerBuilder $container, string $id, Defi
                 ->setAbstract(true);
         }
 
+        if ($definition->isSynthetic()) {
+            // Ignore container.excluded tag on synthetic services
```
Comment (OskarStark) [inline src/Symfony/Component/DependencyInjection/Compiler/ResolveInstanceofConditionalsPass.php:153]: Not sure the comment is needed 😃

**Review by GromNaN — APPROVED** [review]

File: src/Symfony/Component/DependencyInjection/Compiler/ResolveInstanceofConditionalsPass.php (hunk 4 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Compiler/ResolveInstanceofConditionalsPass.php:153]: I added it to make it more explicit that this is the desired behavior.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: addressed thanks

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 5]
```diff
@@ -791,34 +791,34 @@ static function (ChildDefinition $definition, AsPeriodicTask|AsCronTask $attribu
...
         $container->registerForAutoconfiguration(\UnitEnum::class)
-            ->addTag('container.excluded', ['source' => 'because it\'s an enum'])->setAbstract(true);
+            ->addTag('container.excluded', ['source' => 'because it\'s an enum']);
         $container->registerAttributeForAutoconfiguration(AsMessage::class, static function (ChildDefinition $definition) {
-            $definition->addTag('container.excluded', ['source' => 'because it\'s a messenger message'])->setAbstract(true);
+            $definition->addTag('container.excluded', ['source' => 'because it\'s a messenger message']);
         });
         $container->registerAttributeForAutoconfiguration(\Attribute::class, static function (ChildDefinition $definition) {
-            $definition->addTag('container.excluded', ['source' => 'because it\'s an attribute'])->setAbstract(true);
+            $definition->addTag('container.excluded', ['source' => 'because it\'s an attribute']);
```
Comment (welcoMattic) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]:
```suggestion
            $definition->addTag('container.excluded', ['source' => 'because it\'s a PHP attribute']);
```

"attribute" could be several stuff nowadays 😄

**Review by welcoMattic — APPROVED** [review]

**Comment by adpeyre** [comment]
Hello @nicolas-grekas ,
I feel like these additions introduce a bug ?
With doctrine-bundle v2.14.0

`Doctrine\ORM\Mapping\Embeddable" has already been autoconfigured and merge() does not support merging autoconfiguration for the same attribute`

**Comment by nicolas-grekas** [comment]
@adpeyre I don't know, please provide a reproducer in a new issue if you can (I installed doctrine-bundle with Symfony 7.3 successfully, which means I cannot reproduce).

**Comment by nicolas-grekas** [comment]
Note that this error message is not found anywhere in Symfony 7.3 so I'm skeptical.

**Comment by adpeyre** [comment]
I think the person in my team hasn't updated their symfony properly to test 7.3.... This appears to be symfony 7.2 code... Sorry Nicolas.

**Comment by kedarkhaire** [comment]
Hi @nicolas-grekas 
We are getting issue on Symfony 7.2.6 & Drupal 11 
Symfony\Component\DependencyInjection\Exception\RuntimeException: You have requested a synthetic service ("kernel"). The DIC does not know how to construct this service. in Symfony\Component\DependencyInjection\ContainerBuilder->createService() (line 1093 of vendor/symfony/dependency-injection/ContainerBuilder.php).
https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/733

Any plans to release this fix for Symfony 7.2 ?

**Comment by nicolas-grekas** [comment]
You might experience something else. The attached patch is for 7.3.

**Comment by kedarkhaire** [comment]
Yes, I am experiencing this error on Symfony 7.2 & Drupal 11

Symfony\Component\DependencyInjection\Exception\RuntimeException: You have requested a synthetic service ("kernel"). The DIC does not know how to construct this service. in Symfony\Component\DependencyInjection\ContainerBuilder->createService() (line 1093 of vendor/symfony/dependency-injection/ContainerBuilder.php).

I am asking, can we look for this issue in Symfony7.2 ?
Do you want me to create a issue for this ?

**Comment by nicolas-grekas** [comment]
You'd better ask Drupal before, I don't see how this can be related to Symfony itself. It'd rather look like a bug in the way Symfony is used.

**Comment by kedarkhaire** [comment]
Thanks @nicolas-grekas for clarifying things here.
