### PR TITLE
[Console] don't discard existing aliases when constructing Command

### LINKED ISSUE #62557: [Console] BC break in 7.4.0: declaring aliases before calling parent::__construct() does not work anymore
### Symfony version(s) affected

7.4.0

### Description

Before 7.4.0 calling the `setAliases` function before `parent::__construct` on a custom `Command`  was working, now aliases are not defined when doing this.

I'm not sure such thing is in the BC policy ? Close it if not.

### How to reproduce

Having a command like this

```php
class MyCommand extends Command 
{
    public function __construct()
    {
        $this->setAliases(['alias']);
        parent::__construct('my-command');
    }
}
```

### Possible Solution

Alias should be declared after parent : 

```php
class MyCommand extends Command 
{
    public function __construct()
    {
        parent::__construct('my-command');
        $this->setAliases(['alias']);
    }
}
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by henderkes**
| Q             | A
| ------------- | ---
| Branch?       | 7.4 
| Bug fix?      | yes
| New feature?  no
| Deprecations? | no 
| Issues        | Fix #62557 
| License       | MIT

Contributor guidelines:
- [x] Add tests and ensure they pass
- [x] Bug fixes must target the **lowest maintained** branch where they apply
  https://symfony.com/releases#maintained-symfony-branches
- [x] New features and deprecations must target the **feature** branch
  and must add an entry to the changelog file of the patched component:
  https://symfony.com/doc/current/contributing/code/conventions.html#writing-a-changelog-entry
- [x] Do not break backward compatibility:
  https://symfony.com/bc

### CODE REVIEW

File: src/Symfony/Component/Console/Command/Command.php [hunk 1]
```diff
@@ -120,6 +120,12 @@ public function __construct(?string $name = null, ?callable $code = null)
                 $name = array_shift($aliases);
             }
 
+            // we must not overwrite existing aliases, combine new ones with existing ones
+            $aliases = array_unique([
```
Comment (xabbuh) [inline src/Symfony/Component/Console/Command/Command.php:124]: I think I would rather guard the `setAliases()` call below to not call it with an empty array.

Comment (andesk) [reply src/Symfony/Component/Console/Command/Command.php:124]: What's the intended behavior most likely?

Adding aliases from $name being split by `|` seems to be the latest change. Merging those into the array of existing ones feels most BC-safe over overwriting it if aliases here are not an empty array? 🤔

Comment (henderkes) [reply src/Symfony/Component/Console/Command/Command.php:124]: > I think I would rather guard the `setAliases()` call below to not call it with an empty array.

```php
            if ($aliases !== []) {
                $this->setAliases($aliases);
            }
```

Like this? That alone wouldn't fix the issue of existing aliases, because if $name was 'name|newalias', it would still overwrite the existing ones.

Comment (xabbuh) [reply src/Symfony/Component/Console/Command/Command.php:124]: I thought about that too and then I wondered if it is really realistic that someone updates the name to make use of the new opportunity to define name and aliases at once and then additionally also calls `setAlias()`. 🤷

Comment (xabbuh) [reply src/Symfony/Component/Console/Command/Command.php:124]: Though if we say that's something we want to keep we can indeed remove the `if` again.

Comment (henderkes) [reply src/Symfony/Component/Console/Command/Command.php:124]: Perhaps not realistic, but entirely possible.

**Review by nicolas-grekas — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Review by yceruto — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @henderkes.
