### PR TITLE
[AssetMapper] Remove `async` from the polyfill loading script

### LINKED ISSUE #59547: [AssetMapper] ImportMap render w3c validator error
### Symfony version(s) affected

7.2.2

### Description

Hi,

I've run a test with w3c validator and I get an error in the script tags generated by importMap :

```
Error: Element script must not have attribute async unless attribute src is also specified or unless attribute type is specified with value module.
From line 48, column 10; to line 48, column 23
</script><script async>↩if (!
```

The class concerned is ImportMapRender.php, line 128 :

```php
$output .= <<<HTML
                <script async$scriptAttributes>
                if (!HTMLScriptElement.supports || !HTMLScriptElement.supports('importmap')) (function () {
                    const script = document.createElement('script');
                    script.src = '{$this->escapeAttributeValue($polyfillPath, \ENT_NOQUOTES)}';
                    script.setAttribute('async', 'async');
                    {$this->createAttributesString($polyfillAttributes, "script.setAttribute('%s', '%s');", "\n    ", \ENT_NOQUOTES)}
                    document.head.appendChild(script);
                })();
                </script>
                HTML;
```

async in the script tag seems to be a problem.

### How to reproduce

Use the import map in your symfony  project.

In base.html.twig file, add this lines :

```
       {% block javascripts %}
            {% block importmap %}
                {{ importmap('app') }}
            {% endblock %}
        {% endblock %}
```

Generate the html page and pas code in W3C validator : https://validator.w3.org/nu/#textarea

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59547
| License       | MIT

From https://javascript.info/script-async-defer:

> the `async` attribute is ignored if the `<script>` tag has no `src`.

and

> Dynamic scripts behave as “async” by default.

### CODE REVIEW

File: src/Symfony/Component/AssetMapper/ImportMap/ImportMapRenderer.php [hunk 1]
```diff
@@ -125,11 +125,10 @@ public function render(string|array $entryPoint, array $attributes = []): string
             }
 
             $output .= <<<HTML
-                <script async$scriptAttributes>
+                <script$scriptAttributes>
                 if (!HTMLScriptElement.supports || !HTMLScriptElement.supports('importmap')) (function () {
                     const script = document.createElement('script');
                     script.src = '{$this->escapeAttributeValue($polyfillPath, \ENT_NOQUOTES)}';
-                    script.setAttribute('async', 'async');
```
Comment (smnandre) [inline src/Symfony/Component/AssetMapper/ImportMap/ImportMapRenderer.php:132]: This is not what Mozilla doc states 🤔 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#notes

> Scripts without [async](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#async), [defer](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#defer) or type="module" attributes, as well as inline scripts without the type="module" attribute, **are fetched and executed immediately** before the browser continues to parse the page.


And this seems to match html spec chart here

HTMLSPEC


Not found either in [the spec](https://html.spec.whatwg.org/multipage/scripting.html#dom-script-async) something that would suggest async is default (but i may have missed it)

Comment (MatTheCat) [reply src/Symfony/Component/AssetMapper/ImportMap/ImportMapRenderer.php:132]: It’s from https://html.spec.whatwg.org/multipage/scripting.html#script-force-async:

> A [`script`](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element) element has a **force async** boolean, initially true. It is set to false by the [HTML parser](https://html.spec.whatwg.org/multipage/parsing.html#html-parser) […] on [`script`](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element) elements [it inserts], and when the element gets an [`async`](https://html.spec.whatwg.org/multipage/scripting.html#attr-script-async) content attribute added.

The polyfill script is not parser-inserted, but MDN only mentions these :confused: 

You can easily check a script-inserted script is async by default though: https://jsfiddle.net/nL509xph/

Comment (smnandre) [reply src/Symfony/Component/AssetMapper/ImportMap/ImportMapRenderer.php:132]: > It is set to false by the [HTML parser](https://html.spec.whatwg.org/multipage/parsing.html#html-parser) and the [XML parser](https://html.spec.whatwg.org/multipage/xhtml.html#xml-parser) on [script](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element) elements they insert

Comment (MatTheCat) [reply src/Symfony/Component/AssetMapper/ImportMap/ImportMapRenderer.php:132]: > The polyfill script is not parser-inserted

Did you check [the fiddle](https://jsfiddle.net/nL509xph/)?

Comment (smnandre) [reply src/Symfony/Component/AssetMapper/ImportMap/ImportMapRenderer.php:132]: I did check the fiddle :) 

I'm just not entirely sure this is enough to state how the browsers will behave. 

Your fiddle code "console log" attributes... this is not granted to be the behaviour off the parsers when they will start to load this (external) script.

And I think you will agree the MDN docs claims are something that creates doubts here.

I'm thinking except if we have a 100.00% insurance the script will _always_ be loaded after the main JS files, the async attribute in the generated script does not cost us much, is perfectly W3 valid, and could be a safe bet.

:)

Comment (MatTheCat) [reply src/Symfony/Component/AssetMapper/ImportMap/ImportMapRenderer.php:132]: If you don’t trust the browsers nor the spec I fear you cannot be sure of anything.

But then why would we trust the W3 validator? And are we really 100% sure removing the `async` attribute from the inline script won’t have any unattended consequence?

Comment (smnandre) [reply src/Symfony/Component/AssetMapper/ImportMap/ImportMapRenderer.php:132]: > If you don’t trust the browsers nor the spec I fear you cannot be sure of anything.

Not what i tried to say, nevermind :) If you're sure .. i don"t need to be convinced here 😅 

My point was just a small fear I had this would have unwanted consequences.. that's all :)

**Review by nicolas-grekas — APPROVED** [review]
works for me
implicit async on script inserted elements is safe to me by the nature of JS, which is async itself

**Comment by nicolas-grekas** [comment]
Note that this is not a bugfix so it's for 7.3

**Comment by nicolas-grekas** [comment]
Thank you @MatTheCat.
