### PR TITLE
[HttpClient] Allow using multiple base_uri as array for retries

### LINKED ISSUE #43327: [HttpClient] Add support for client pool
**Description**

Let's consider the following use case:

* I have a cluster of elasticsearch server `[a .. z]`
* My application got the list of some server  `[a .. c]`
* If a request fails on `a`, then retry on `b`, then `c`, then throw an exception.

So it could be nice to have something in the core that allow us to give a list of endpoint instead of one endpoint.

### PR DESCRIPTION
**Pull request by Tiriel**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #43327 
| License       | MIT
| Doc PR        | TBD

This pull request enhances the `RetryableHttpClient` by allowing the use of an array of URLs as the `base_uri` option. This enables retries on different base URIs for each retry attempt, providing increased reliability and flexibility for making HTTP requests.

Basic usage :
```php
use Symfony\Component\HttpClient\RetryableHttpClient;

$client = new RetryableHttpClient(
    HttpClient::create(),
    new GenericRetryStrategy([500], 0),
    1
);

$response = $client->request('GET', 'foo-bar', [
    'base_uri' => [
        'http://example.com/a/', // first request will use this base uri
        'http://example.com/b/', // if first request fails, the second base uri will be used
    ],
]);
```

Usage with base uri shuffling :
```php
use Symfony\Component\HttpClient\RetryableHttpClient;

$client = new RetryableHttpClient(
    HttpClient::create(),
    new GenericRetryStrategy([500], 0),
    3
);

$response = $client->request('GET', 'foo-bar', [
    'base_uri' => [
        'http://example.com/a/',
        [
            'http://example.com/b/', // base uri passed inside a nested array will be shuffled
            'http://example.com/c/',
        ]
        'http://example.com/d/', // the order of the non-nested base uris is preserved
    ],
]);
```

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
ghanks for starting this. We should also support default options, as is possible when using `$retryable->withOptions()`.

About what you say @GromNaN, it should also be possible to pass a list of per-hosts IPs to the resolve option, and rotate them as fits. This could be done either in this PR if @Tiriel is up to, or in a later one. Of course, that'd need resolving the many IPs outside of the client.

One thing I'm wondering in both cases: shouldn't we shuffle the base URIs (and IPs later on?)

**Comment by Tiriel** [comment]
@nicolas-grekas Sure thing, going to work on the default options!
For you last question, I wonder if it would be a good idea to leave it open and give an option. Like, if `base_uri` is an array, you can pass a `'shuffle' => true` option defaulting to false, otherwise it doesn't do anything? Or maybe it's too much? Because I can clearly see use cases where you wouldn't want to shuffle, and some people seem to have use cases for the contrary.

As for the IPs, I thought it would be better in another PR since the resolve doesn't take place at the same level, but maybe we can work something out. So I'd say that's up to @GromNaN , if you want to work on the feature yourself or not.

**Comment by Tiriel** [comment]
Made an attempt to make it work with `withOptions`, it's working, but quite frankly I'm not sure if my code is ok or "dirty", so any advice would be appreciated.

Haven't tried yet on the shuffling part, I'd like opinion on wether to shuffle by default or not, or on adding an option for this.

**Comment by nicolas-grekas** [comment]
About shuffling, we could to it this way:

`$hosts = ['h1', 'h2', ['h3', h4']]`

Nested arrays would define shuffle groups, and first level values would be used in order.
Up for implementing this?

**Comment by Tiriel** [comment]
That's a great idea, thanks!
Will work on it asap!

**Comment by Tiriel** [comment]
Forgot to ping, but this has been updated with a shuffling attempt and tests accordingly.

**Review by nicolas-grekas — APPROVED** [review]
I simplified a bit the implementation, see https://github.com/symfony/symfony/compare/90b2027189ff18ca4957567e2252f570e3276d6d..b63ad4025ffbc4f1e513dd34650a34a50712afe4

I also removed the exception when the URL is absolute and a base URI is still provided because this is not an erroneous situation.

Lastly, I ensured that if the number of retries is higher than the number of base URIs, we stick retrying to the last one (possibly randomizing from a list).

**Comment by nicolas-grekas** [comment]
Thank you @Tiriel.

**Comment by Tiriel** [comment]
Looks more than a bit simplified to me, this is awesome work to look at and learn from! Thanks!

**Comment by lyrixx** [comment]
@Tiriel Can you update the PR description with some code, please? It'll help Javier to write the [living-on-the-edge](https://symfony.com/blog/category/living-on-the-edge) articles

**Comment by Tiriel** [comment]
@lyrixx Will do this evening!

**Comment by Tiriel** [comment]
Updated PR description with usage, let me know if more is needed!

File: src/Symfony/Component/HttpClient/RetryableHttpClient.php [hunk 1]
```diff
@@ -168,4 +190,14 @@ private function passthru(AsyncContext $context, ?ChunkInterface $firstChunk, st
 
         yield $lastChunk;
     }
+
+    private static function shiftBaseUri(array $options, array &$baseUris): array
+    {
+        if ($baseUris) {
+            $baseUri = 1 < \count($baseUris) ? array_shift($baseUris) : current($baseUris);
+            $options['base_uri'] = \is_array($baseUri) ? $baseUri[array_rand($baseUri)] : $baseUri;
```
Comment (Tiriel) [inline src/Symfony/Component/HttpClient/RetryableHttpClient.php:198]: @nicolas-grekas I just noticed something odd here, but maybe it's intentional?
The provided array to be shuffled is ditched after only one randomized URI is extracted. Is it normal or should I make a fix to use `current` instead of `array_shift` for nested arrays?

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpClient/RetryableHttpClient.php:198]: We have two different expectations apparently: mine is to pick one randomly. Yours is to shuffle and flatten.
The doc PR tells about my way. I don't know how to decide between both approaches honestly.

Comment (Tiriel) [reply src/Symfony/Component/HttpClient/RetryableHttpClient.php:198]: That's a tough one indeed. I honestly don't have enough use cases on my own to decide if it's truly needed to try all the URIs from the array or just one.
Maybe @lyrixx you have an opinion, since the base issue was yours? (even if the shuffling part was not in the original need)

Comment (lyrixx) [reply src/Symfony/Component/HttpClient/RetryableHttpClient.php:198]: I'm 👍🏼 with @nicolas-grekas

Comment (Tiriel) [reply src/Symfony/Component/HttpClient/RetryableHttpClient.php:198]: Thanks for the opinion! Leaving it like that then.

**Comment by ptica** [comment]
hi, thank you for the feature!
there is still a validation that prevents configuring the base_uri as an array in `framework.yaml` config,
is that intentional?

https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L1861

Screenshot 2023-12-18 at 15 58 46

**Comment by Tiriel** [comment]
Hi! Thanks for the feedback!
> is that intentional?

Not on my part. Going to write a fix for this asap!
