### PR TITLE
[DI] ignore extra tags added by autoconfiguration in PriorityTaggedServiceTrait

### LINKED ISSUE #35916: [dependency-injection] does not autoconfigure my form extension when another form extension is configured manually in services.yaml
**Symfony version(s) affected**: 4.4.5

**Description**  
After updating `symfony/dependency-injection` from 4.4.4 to 4.4.5 my one form extension is not autoconfigured (tagged) by Symfony framework. If I remove manual configuration of another form extension from `services.yaml`, the first one is properly autoconfigured (tagged).

**How to reproduce**  
1. Clone my project: https://github.com/TomaszGasior/RadioLista-v3. Chechout 44f1ef41f1dd115f3405730bc8eaee512d10d325 commit where all dependencies except `symfony/dependency-injection` are up to date at the moment where I write this text.
2. `bin/phpunit` -> tests should pass
3. Update symfony/dependency-injection to 4.4.5.
4. `bin/phpunit` -> Tests related to adding, removing and editing radio stations should fail. Twig templates of these pages rely on variable from RadioStationEditExtension form extension which is not autoconfigured.
5. Remove manual configuration of `App\Form\Extension\ValidationFlashErrorExtension` from `services.yaml`. (My app contains two form extensions. ValidationFlashErrorExtension needs to be set up manually to get special priority.)
6. `bin/phpunit` -> tests should pass

### LINKED ISSUE #35953: Numerical keys used with tagged_iterator/tagged_locator reset to 0..n-1
**Symfony version(s) affected**: 5.0

**Description**  
When !tagged_iterator have index_by set, and the corresponding tag property values are numeric, the keys actually reset to 0-based index. See repro PR

**How to reproduce**  
See PR #35954

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35916, Fix #35953
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by alex-dev** [comment]
Seems to work but...
- There are no TypedReference anymore. It may or may not matter.
- Reflection are reloaded everytime rather than at first time needed. Worst case is two calls to `$container->getReflectionClass()`, `$container->getParameterBag()->resolveValue()`. It should not matter much.
- `$index` will always have a value: line 89 - 91 are redundant. This will cause all service iterables to have service id as key (assuming they don't have a better key).

**Comment by nicolas-grekas** [comment]
Thanks for the review

> There are no TypedReference anymore. It may or may not matter.

Yep, doesn't matter.

> Reflection are reloaded everytime

`$container->getReflectionClass()` already has a cache

> $index will always have a value: line 89 - 91 are redundant

nope, see line 70

**Comment by alex-dev** [comment]
> nope, see line 70
Doh! Everything seems good.

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/PriorityTaggedServiceTraitTest.php [hunk 1]
```diff
@@ -85,6 +87,38 @@ public function testWithEmptyArray()
...
+
+        $priorityTaggedServiceTraitImplementation = new PriorityTaggedServiceTraitImplementation();
+
+        $expected = [
+            new Reference('service2'),
+            new Reference('service1'),
+        ];
+        $this->assertEquals($expected, $priorityTaggedServiceTraitImplementation->test('my_custom_tag', $container));
+
+        $tag = new TaggedIteratorArgument('my_custom_tag', 'foo');
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Tests/Compiler/PriorityTaggedServiceTraitTest.php]: The case of indexed and non-indexed arguments should be split into separate tests, so that they both run even if the first one fails. It also makes it easier to understand what these tests are covering, making the testsuite easier to maintain.

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Tests/Compiler/PriorityTaggedServiceTraitTest.php]: works for me, updated.

**Comment by Jamesking56** [comment]
Can we expect a release of this soon? We've had to hold upgrading to `4.4.5` due to this
