### PR TITLE
[FrameworkBundle] fix `lint:container` command

### LINKED ISSUE #60920: [FrameworkBundle] Can't use container:lint command
### Symfony version(s) affected

7.4.x-dev

### Description

After updating symfony/framework-bundle `bin/console container:lint` command fails to run due to undefined method `isDebug` on container.

### How to reproduce

```
symfony new --no-git --version=next test
cd test
bin/console lint:container -vvv
```

### Possible Solution

_No response_

### Additional Context

```
```
> symfony new --no-git --version=next test
* Creating a new Symfony 7.4.x@dev project with Composer
  WARNING: Detected Composer file (/home/frederik/.nix-profile/bin/composer) is not a valid PHAR or PHP script.
  Downloading Composer for you, but it is recommended to install Composer yourself, instructions available at https://getcomposer.org/download/
  (running php /home/frederik/.symfony5/composer/composer.phar create-project symfony/skeleton /home/frederik/test 7.4.x@dev --no-interaction)

                                                                                                                        
 [OK] Your project is now ready in /home/frederik/test                                                                  
                                                                                                                        

> cd test
> bin/console lint:container
[critical] Error thrown while running command "lint:container". Message: "Call to undefined method Container9IAgk5f\App_KernelDevDebugContainer::isDebug()"
[critical] Uncaught Error: Call to undefined method Container9IAgk5f\App_KernelDevDebugContainer::isDebug()

In ContainerLintCommand.php line 83:
                                                                                                                  
  Attempted to call an undefined method named "isDebug" of class "Container9IAgk5f\App_KernelDevDebugContainer".  
                                                                                                                  

lint:container [--resolve-env-vars]

> vi
> bin/console lint:container -vvv
[critical] Error thrown while running command "lint:container -vvv". Message: "Call to undefined method Container9IAgk5f\App_KernelDevDebugContainer::isDebug()"
[debug] Command "lint:container -vvv" exited with code "1"
[critical] Uncaught Error: Call to undefined method Container9IAgk5f\App_KernelDevDebugContainer::isDebug()

In ContainerLintCommand.php line 83:
                                                                                                                  
  [Symfony\Component\ErrorHandler\Error\UndefinedMethodError]                                                     
  Attempted to call an undefined method named "isDebug" of class "Container9IAgk5f\App_KernelDevDebugContainer".  
                                                                                                                  

Exception trace:
  at /home/frederik/test/vendor/symfony/framework-bundle/Command/ContainerLintCommand.php:83
 Symfony\Bundle\FrameworkBundle\Command\ContainerLintCommand->getContainerBuilder() at /home/frederik/test/vendor/symfony/framework-bundle/Command/ContainerLintCommand.php:53
 Symfony\Bundle\FrameworkBundle\Command\ContainerLintCommand->execute() at /home/frederik/test/vendor/symfony/console/Command/Command.php:343
 Symfony\Component\Console\Command\Command->run() at /home/frederik/test/vendor/symfony/console/Application.php:1108
 Symfony\Component\Console\Application->doRunCommand() at /home/frederik/test/vendor/symfony/framework-bundle/Console/Application.php:123
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /home/frederik/test/vendor/symfony/console/Application.php:343
 Symfony\Component\Console\Application->doRun() at /home/frederik/test/vendor/symfony/framework-bundle/Console/Application.php:77
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/frederik/test/vendor/symfony/console/Application.php:194
 Symfony\Component\Console\Application->run() at /home/frederik/test/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /home/frederik/test/vendor/autoload_runtime.php:29
 require_once() at /home/frederik/test/bin/console:15

lint:container [--resolve-env-vars]                                                                                                                                                                                                                                       
```

### PR DESCRIPTION
**Pull request by santysisi**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60920
| License       | MIT

This PR resolves two issues related to the `lint:container` command:

1) Incorrect use of `isDebug()` method: The `isDebug() `method was being called on the `$container`, but this method does not exist there. The correct call should be on the `$kernel` instance.

2) Issue during container unserialization: When unserializing the dumped container to retrieve the `ContainerBuilder`,  problem was with the service aliases. The `public` property was not correctly initialized because the constructor is bypassed during unserialization.

### CODE REVIEW

**Comment by santysisi** [comment]
status: needs work

**Comment by santysisi** [comment]
status: needs review

File: src/Symfony/Component/DependencyInjection/Alias.php [hunk 1]
```diff
@@ -17,12 +17,14 @@ class Alias
...
 
+    private bool $public = false;
     private array $deprecation = [];
 
     public function __construct(
         private string $id,
-        private bool $public = false,
+        bool $public = false,
     ) {
+        $this->public = $public;
```
Comment (santysisi) [inline src/Symfony/Component/DependencyInjection/Alias.php:27]: If we want to avoid changing the `__constructor`, we can use the magic `__unserialize` method instead:

```php
public function __unserialize(array $data): void
{
    $this->id = $data['id'];
    $this->public = $data['public'] ?? false;
    $this->deprecation = $data['deprecation'] ?? [];
}
```

**Comment by santysisi** [comment]
I'll try to add some tests as soon as possible.

**Comment by nicolas-grekas** [comment]
Thank you @santysisi.
