### PR TITLE
[Security/Http] call auth listeners/guards eagerly when they "support" the request

### LINKED ISSUE #34614: Symfony authenticator's no longer called with anonymous: lazy
**Symfony version(s) affected**: 4.4.0

**Description**  
Until now, if you have a Guard authenticator, its `supports()` method will be called on every request. However, with `anonymous: lazy` under your firewall, that no longer happens.

Maybe that's intended? If it is, I think `anonymous: lazy` can't be used as the default config in the `security.yaml` recipe, as it creates a very different experience.

**How to reproduce**  
Reproducer: https://github.com/weaverryan/symfony-anonymous-lazy-reproducer

Basically, create an authenticator on a new project and access any URL. It will not be executed (because `anonymous: lazy` is the default setting in the recipe).

**Possible Solution**  
I'm not sure if this is a bug with `anonymous: lazy` or if we should revert the recipe back to `anonymous: true`.

**Additional context**  
Caught by MakerBundle tests :)

### LINKED ISSUE #34679: Remember me not working with anonymous: lazy
**Symfony version(s) affected**: 5.0.0

**Description**  

When defining:

```
    firewalls:
        main:
            anonymous: lazy
```

The remember me functionality does not work. To be precise: https://github.com/symfony/security-guard/blob/5.0/Firewall/GuardAuthenticationListener.php#L167 is never executed.

**How to reproduce**  

Follow the Security documentation at https://symfony.com/doc/4.4/security.html to set up a basic login form with authentication, except configure `anonymous: lazy`. Then follow https://symfony.com/doc/4.4/security/remember_me.html and try to log in with the remember me checkbox ticked. You will see that the `REMEMBERME` cookie is not set.

Then change the security configuration to `anonymous: true`, clear cache and try logging in  again. This time you will get the `REMEMBERME` cookie.

**Additional context**  

- Not my post, but this StackOverflow user is running into the same: https://stackoverflow.com/questions/59086076/symfony-4-remember-me-cookie-not-set/59086599#59086599
- It might be related to #34614 , but I am not sure.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34614, Fix #34679
| License       | MIT
| Doc PR        | -

This fixes the form authenticator linked to #34614.
Since laziness is here to provide compatibility with HTTP caching, it should be disabled when the request cannot be cached.

Tests don't pass yet, but I'm on the path to something here.

The PR now introduces a new `AbstractListener` that splits the handling logic in two:
- `supports(Request): ?bool` is always called eagerly and tells whether the listener matches the request for an earger call or a lazy call
- `authenticate(RequestEvent)` does the rest of the job when `supports()` allows so - lazily or not depending on the return value of `supports()`.

Of course, this remains compatible with non-lazy logics, see `AbstractListener::__invoke()`.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Not that we might consider always calling guard's "supports()" methods non-lazily, but I don't think the current design allows it easily. Let me check.

**Comment by stof** [comment]
> In this case, it looks legit to me to require either the corresponding firewall to be stateless or anonymous to be set to `true` (both options disabling laziness).

maybe we should allow to define a list of path for which you want to disable lazyness (the check paths of your OAuth callbacks could then be registered there)

**Comment by weaverryan** [comment]
> Not that we might consider always calling guard's "supports()" methods non-lazily, but I don't think the current design allows it easily. Let me check

I was wondering about this too. On a high-level, with `anonymous: lazy`, it "should" be ok to call `supports()` on authentiicators. If the request should truly remain anonymous, then they authenticator will do nothing (i.e. return false from `supports()`). In other words: the authenticators would always be called, but then they could decide to allow the lazy anonymous to continue by doing nothing *or* to authenticate. However, I realize on a technical level, that might be difficult :).

> Here's another problematic example: OAuth. When an OAuth server redirects back to my site... 

> In this case, it looks legit to me to require either the corresponding firewall to be stateless or 
> anonymous to be set to true (both options disabling laziness).

Also, what about the `json_login` example @dunglas gave here: https://github.com/symfony/symfony/issues/34614#issuecomment-558356111 - I use `json_login` on stateful firewalls as a simple way to allow my JavaScript to authenticate. Would this also still require manually changing to `anonymous: true`?

Thanks :)

**Comment by nicolas-grekas** [comment]
Tests don't pass yet, but I'm on the path to something here.

The PR now introduces a new `AbstractListener` that splits the handling logic in two:
- `supports(Request): ?bool` is always called eagerly and tells whether the listener matches the request for an earger call or a lazy call
- `authenticate(RequestEvent)` does the rest of the job when `supports()` allows so - lazily or not depending on the return value of `supports()`.

Of course, this remains compatible with non-lazy logics, see `AbstractListener::__invoke()`.

While I'm working on tests, I'd happily accept early feedbacks on the approach.

**Comment by nicolas-grekas** [comment]
PR green in a minute :)

**Comment by nicolas-grekas** [comment]
PR ready, now with functional tests.

**Comment by nicolas-grekas** [comment]
PR updated, last change: laziness now mandates extending `AbstractListener`.
This makes things more BC/FC - one needs to explicitly opt-in to benefit from laziness.
We might consider deprecating *not* extending `AbstractListener` in 5.1.

File: src/Symfony/Component/Security/Http/Firewall/AbstractListener.php [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+use Symfony\Component\HttpFoundation\Request;
+use Symfony\Component\HttpKernel\Event\RequestEvent;
+
+/**
+ * A base class for listeners that can tell whether they should authenticate incoming requests.
+ *
+ * @author Nicolas Grekas <p@tchwork.com>
+ */
+abstract class AbstractListener
```
Comment (chalasr) [inline src/Symfony/Component/Security/Http/Firewall/AbstractListener.php]: Can it be replaced by an interface? That would be more decorator-friendly

Comment (nicolas-grekas) [reply src/Symfony/Component/Security/Http/Firewall/AbstractListener.php]: I don't think that's needed. Might be considered in 5.1, but would need a need first to me. This abstract class makes things simpler, thanks to the final __invoke method to me.

**Review by chalasr — APPROVED** [review]

**Review by aschempp — COMMENTED** [review]
If I understand correctly, the whole `lazy` firewall behavior is meant to prevent unnecessary session access? Why not just skip/lazy-load the `ContextListener` and always call all other listeners?

**Comment by nicolas-grekas** [comment]
> Why not just skip/lazy-load the ContextListener and always call all other listeners?

I don't understand what you mean sorry. The order is important so we cannot call one listener lazily. "just" here is missing the fact all this work is happening in the Security component, nothing is simple there :)

File: UPGRADE-4.3.md [hunk 2]
```diff
@@ -170,7 +170,7 @@ Security
    Role hierarchies must implement the `getReachableRoleNames()` method instead and return roles as strings.
  * The `getRoles()` method of the `TokenInterface` is deprecated. Tokens must implement the `getRoleNames()`
    method instead and return roles as strings.
- * The `ListenerInterface` is deprecated, turn your listeners into callables instead.
+ * The `ListenerInterface` is deprecated, extend `AbstractListener` instead.
```
Comment (fabpot) [inline UPGRADE-4.3.md]: You are in the 4.3 changelog but the PR targets 4.4.

File: src/Symfony/Bundle/SecurityBundle/Security/LazyFirewallContext.php [hunk 3]
```diff
@@ -28,17 +25,13 @@
  */
 class LazyFirewallContext extends FirewallContext
 {
-    private $accessListener;
     private $tokenStorage;
-    private $map;
 
-    public function __construct(iterable $listeners, ?ExceptionListener $exceptionListener, ?LogoutListener $logoutListener, ?FirewallConfig $config, AccessListener $accessListener, TokenStorage $tokenStorage, AccessMapInterface $map)
+    public function __construct(iterable $listeners, ?ExceptionListener $exceptionListener, ?LogoutListener $logoutListener, ?FirewallConfig $config, TokenStorage $tokenStorage)
```
Comment (fabpot) [inline src/Symfony/Bundle/SecurityBundle/Security/LazyFirewallContext.php]: Isn't it a BC break? This class is not marked as being internal.

**Review by fabpot — CHANGES_REQUESTED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.
