### PR TITLE
[Contracts] Fix setting $container before calling parent::setContainer in ServiceSubscriberTrait

### LINKED ISSUE #49382: Controller using ServiceSubscriberTrait has service locator overwritten by service container
### Symfony version(s) affected

6.2.5

### Description

A controller using `ServiceSubscriberTrait` is wired up correctly. However, when a request is served, its service locator is overwritten by the service container. This usually causes an error when a service is retrieved from the service container, since the service names are likely to be incompatible.

### How to reproduce

Repo demonstrating the issue here: https://github.com/edsrzf/symfony_reproducer

To reproduce:
* Start the local server with `symfony server:start`
* Navigate to http://127.0.0.1:8000
* See the error: `You have requested a non-existent service "App\Controller\Controller::getService". Did you mean this: "App\Controller\Controller"?`

### Possible Solution

The cause is this bit of code in `Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver`:

https://github.com/symfony/symfony/blob/e16aea4e88bfecec4986bf7a693f84a86c074109/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php#L32-L36

when combined with `setContainer` from `ServiceSubscriberTrait`:

https://github.com/symfony/symfony/blob/33377e7912e63be4620c8ac5e6e462972e9536e8/src/Symfony/Contracts/Service/ServiceSubscriberTrait.php#L66-L76

`setContainer` is called a total of 3 times in the process of serving a request:
* Once by the service container, passing in the service locator. It returns `null`.
* The first time by `ControllerResolver`, passing in the service container. The trait sets the `container` property, and then `AbstractController` returns the "previous" container property value, which is actually not the previous value. It's the service container.
* The second time by `ControllerResolver`, which passes the "previous" value back in. It _should_ be the service locator, but it's actually the service container.

It feels like the fix needs to be inside `ServiceSubscriberTrait`. Maybe `parent::setContainer` could be called before setting `$this->container`?

#### Workaround

The issue can be worked around by overriding `setContainer`, skipping the trait's method:

```php
#[Required]
public function setContainer(ContainerInterface $container): ?ContainerInterface
{
    return parent::setContainer($container);
}
```

### PR DESCRIPTION
**Pull request by edsrzf**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49382
| License       | MIT

This changes the `setContainer` method of `ServiceSubscriberTrait` so that it calls `parent::setContainer` first, before updating `$this->container`. This is so that the parent method can work correctly if it relies on the old container value.

This is particularly relevant for `AbstractController`, since it returns the old container value. When used with `ServiceSubscriberTrait`, it returned the _new_ container rather than the old one. This, in turn, caused incorrect behavior in framework bundle's `ControllerResolver`, as described in #49382.

### CODE REVIEW

File: src/Symfony/Contracts/Tests/Service/ServiceSubscriberTraitTest.php [hunk 1]
```diff
@@ -161,3 +173,21 @@ public static function __callStatic($method, $args)
...
+class ParentTestService2
+{
+    /** @var ContainerInterface */
+    protected $container;
+
+    public function setContainer(ContainerInterface $container)
+    {
+        $previous = $this->container;
+        $this->container = $container;
+        return $previous;
```
Comment (nicolas-grekas) [inline src/Symfony/Contracts/Tests/Service/ServiceSubscriberTraitTest.php:187]: please add a blank line before

**Review by nicolas-grekas — APPROVED** [review]
Makes sense to me.

**Comment by nicolas-grekas** [comment]
Thank you @edsrzf.
