### PR TITLE
[Validator] remove service if its class doesn't exist

### LINKED ISSUE #41468: Insufficient service configuration of "validator.expression", class "ExpressionLanguage" does not exist
**Symfony version(s) affected**: 5.3.0

**Description**
After updating to Symfony 5.3 the container linter outputs the following error.
```
[critical] Error thrown while running command "lint:container". Message: "Invalid service "validator.expression": class "Symfony\Component\ExpressionLanguage\ExpressionLanguage" does not exist."
```
I think it's caused by the changes of #39327.

**How to reproduce**
I will add a example project or from a new Symfony app ASAP. But I would say that it is sufficient to add the Validator component.

**Possible Solution**
Add service `validator.expression_language` only if `ExpressionLanguage` component is installed or add `ExpressionLanguage` component to composer.json of `Validator` component.

**Additional context**
grafik

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41468
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by malteschlueter — APPROVED** [review]

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -1450,6 +1450,10 @@ private function registerValidationConfiguration(array $config, ContainerBuilder
             ->setArgument(2, $config['not_compromised_password']['enabled'])
             ->setArgument(3, $config['not_compromised_password']['endpoint'])
         ;
+
+        if (!class_exists(ExpressionLanguage::class)) {
```
Comment (malteschlueter) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:1454]: I don't know how to use the new function at all but wouldn't something like this the better way now?
```suggestion
        if (!ContainerBuilder::willBeAvailable('symfony/expression-language', ExpressionLanguage::class, ['symfony/framework-bundle', 'symfony/validator'])) {
```

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:1454]: I think that's good as is, `validator.expression_language` should be loaded in dev or no-dev.

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.
