### PR TITLE
[Console] Support `ProgressBar::iterate()` on empty array

### LINKED ISSUE #47244: [ProgressBar] Empty iterable throws Exception on "maximum number of steps is not set"
### Symfony version(s) affected

latest

### Description

I stumbled upon an empty array that has been used with a progress bar. And my execution stopped. Turns out the ProgressBar checks if its max steps are set when "remaining" and "estimated" values are used in formatting. Nothing wrong so far.

However, in case there is an empty array supplied to the progress bar, code internals interpret a max value of 0 as the max value not being set:
```
                if (!$bar->getMaxSteps()) {
                    throw new LogicException('Unable to display the ... if the maximum number of steps is not set.');
                }
```
(https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Console/Helper/ProgressBar.php#L522 and https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Console/Helper/ProgressBar.php#L529)

That to me seems not entirely accurate. Because in this very case, the max value IS set and it IS 0. Yet, it is treated like it is NOT set.

Expected:
I would expect the progress bar not to fail if an empty Iterable is presented to it.

### How to reproduce

```
$progressBar = new ProgressBar(new ConsoleOutput(OutputInterface::VERBOSITY_DEBUG);
$progressBar->setFormat('debug');

// this very array sources somewhere in a bigger project and it just happens to be empty some times
$incoming = array();

foreach($progressBar->iterate($incoming) as $current) {
   var_dump($current);
}
```

### Possible Solution

Changing the line mentioned above:
```
                if (!$bar->getMaxSteps()) {
                    throw new LogicException('Unable to display the ... if the maximum number of steps is not set.');
                }
```
(https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Console/Helper/ProgressBar.php#L522 and https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Console/Helper/ProgressBar.php#L529)

to

```
                if (!isset($bar->max)) {
                    throw new LogicException('Unable to display the ... if the maximum number of steps is not set.');
                }
```

seem to be semantically more correct. And it makes the ProgressBar behave like I expected it to do. If you guys are ok with this approach, I can provider a PR.

### Additional Context

_No response_

Thanks!

### PR DESCRIPTION
**Pull request by GromNaN**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #47244
| License       | MIT

Alternative to #47259

Use `$max = null` to indicate that the value is unknown. This allows `0` to be displayed by directly setting the progress bar to 100%.

Zero is only supported for `iterate()`. When passed to the constructor or `setMaxSteps`, it means "unknown max".

### CODE REVIEW

File: src/Symfony/Component/Console/Helper/ProgressBar.php [hunk 1]
```diff
@@ -195,7 +195,7 @@ public function getStartTime(): int
 
     public function getMaxSteps(): int
     {
-        return $this->max;
+        return $this->max ?? 0;
```
Comment (GromNaN) [inline src/Symfony/Component/Console/Helper/ProgressBar.php:198]: `$this->max` can be `null`, but keep returning `0` for backward compatibility.

**Review by GromNaN — COMMENTED** [review]
We could deprecate passing `0` for unknown max, but that's not necessary to fix the reported issue.

I create a branch with the deprecation, that we can discuss for 7.1: https://github.com/symfony/symfony/compare/6.4...GromNaN:symfony:issue-47259-deprecate

**Review by maxbeckers — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Merging in 7.1 as this is a behavior change.

**Comment by fabpot** [comment]
Thank you @GromNaN.
