### PR TITLE
[DoctrineBridge] Fix form EntityType with filter on UID

### LINKED ISSUE #39207: [DoctrineBridge] ORMQueryBuilderLoader not compatible with binary UUID columns
**Symfony version(s) affected**: 5.2.0-RC2

**Description**  

After upgrading from 5.2.0-RC1 to 5.2.0-RC2, choice fields for entities using UUIDs as identifiers will fail validation with an error of "This choice does not exist or is not unique".

I believe this regression is a combination of #39113 changing the column type to `BINARY` and the query builder trying to use the string representation when querying for them (see https://github.com/symfony/symfony/issues/39135#issuecomment-733250597 for a similar issue).

Tracing through the code, `DoctrineChoiceLoader` calls `ORMQueryBuilderLoader::getEntitiesByIds()` which returns the matching entity on 5.2.0-RC1 but returns an empty result set on 5.2.0-RC2.

I have replicated this issue on MySQL 5.7 and MariaDB 10.3.

**How to reproduce**

Create an entity with a UUID ID like this:

```
class Foo
{
    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidV4Generator::class)
     */
    private Uuid $id;

    // ...
}
```

Create a form that exposes the list of these entities:

```
// NOTE: I'm using EasyAdminBundle for this, but I suspect you'd get the same result with a vanilla Symfony form

public function configureFields(string $pageName): iterable
{
    return [
        AssociationField::new('foo')->setRequired(true),
        // ...
    ];
}
```

Then attempt to select the entity from the list, submit the form, and get an error that the choice doesn't exist.

**Possible Solutions**  

Modify the `ORMQueryBuilderLoader` code to inform Doctrine of the proper field type or convert it to binary beforehand? (untested; based on https://github.com/symfony/symfony/issues/39135#issuecomment-733250597)  Or rollback #39113 (probably undesired)

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39207
| License       | MIT
| Doc PR        | -

Convert UUID and ULID to the right format in ORMQueryBuilder 

/cc @nicolas-grekas

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php [hunk 1]
```diff
@@ -82,13 +83,23 @@ public function getEntitiesByIds(string $identifier, array $values)
             $values = array_values(array_filter($values, function ($v) {
                 return (string) $v === (string) (int) $v || ctype_digit($v);
             }));
-        } elseif (\in_array($metadata->getTypeOfField($identifier), ['uuid', 'guid'])) {
+        } elseif (\in_array($type = $metadata->getTypeOfField($identifier), ['ulid', 'uuid', 'guid'])) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php]: `$type = ` could be moved L78 above

**Review by nicolas-grekas — COMMENTED** [review]
nice!
LGTM, once tests are green

File: src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php [hunk 2]
```diff
@@ -82,13 +83,23 @@ public function getEntitiesByIds(string $identifier, array $values)
...
 
             // Like above, but we just filter out empty strings.
             $values = array_values(array_filter($values, function ($v) {
                 return '' !== (string) $v;
             }));
+
+            // Convert values into right type
+            if (Type::hasType($type)) {
+                $doctrineType = Type::getType($type);
+                $plateform = $qb->getEntityManager()->getConnection()->getDatabasePlatform();
```
Comment (andrew-demb) [inline src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php]: Typo `plateform -> platform`

File: src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php (hunk 1 above)
Comment (jderusse) [reply src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php]: right!

File: src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php (hunk 2 above)
Comment (jderusse) [reply src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php]: thanks

**Review by nicolas-grekas — APPROVED** [review]
Thank you @jderusse

**Comment by colinodell** [comment]
Thanks for the quick fix!
