### PR TITLE
[FrameworkBundle] register only existing transport factories

### LINKED ISSUE #35866: Messenger[Async][Symfony5.1] - AmazonSqsTransportFactory not implemented
**Symfony version(s) affected**: 5.1

**Description**  
When we try to dispatch an event using MessageBus **async** (Doctrine) from Symfony 5.1 - it returns an exception:
Attempted to load class "AmazonSqsTransportFactory" from namespace "Symfony\Component\Messenger\Bridge\AmazonSqs\Transport".
Did you forget a "use" statement for another namespace?

**How to reproduce**  
Install symfony 5.1; Dispatch an async event; Get an exception

**Possible Solution**  
Integrate Symfony 5.1 with https://github.com/symfony/amazon-sqs-messenger

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35866
| License       | MIT
| Doc PR        | 

The parts from #35907 that also apply to the `4.4` branch.

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -1765,6 +1785,7 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
             $container->removeDefinition('messenger.transport.symfony_serializer');
             $container->removeDefinition('messenger.transport.amqp.factory');
             $container->removeDefinition('messenger.transport.redis.factory');
+            $container->removeDefinition('messenger.transport.sqs.factory');
```
Comment (fabpot) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: This line should not be part of 4.4, right?

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 1 above)
Comment (xabbuh) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: indeed, fixed

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.
