### PR TITLE
[FrameworkBundle] Only register PhpConfigReferenceDumpPass in dev env with debug flag enabled

### LINKED ISSUE #62630: config/reference.php changes with cache:clear
### Symfony version(s) affected

7.4.0

### Description

The generated file `config/reference.php` changes based on the environment your `cache:clear` runs with. While the earlier ordering issue has been fixed with #62436, the contents of the reference still change. One of the examples:

Image

### How to reproduce

```
symfony new reference_repro --version="7.4.x" --webapp
cd reference_repro
composer req symfony/framework-bundle:7.4.x-dev
git commit -a -m 'framework 7.4.x-dev'
bin/console cache:clear -e prod
git diff
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by bobvandevijver**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #62630
| License       | MIT

Solves an ever changing `config/reference.php` due to changing environment/debug kernel parameters by only registering the compiler pass when the environment is set to `dev` with `debug` enabled.

I wanted to add a test for this, but I believe the `FrameworkBundle` class isn't tested. Please correct me if I'm wrong! The test failures look unrelated.

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php [hunk 1]
```diff
@@ -149,7 +149,7 @@ public function build(ContainerBuilder $container): void
             ]);
         }
 
-        if ($container->hasParameter('.kernel.config_dir') && $container->hasParameter('.kernel.bundles_definition')) {
+        if ('dev' === $container->getParameter('kernel.environment') && $container->getParameter('kernel.debug') && $container->hasParameter('.kernel.config_dir') && $container->hasParameter('.kernel.bundles_definition')) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php]: we don't hardcode any env name in the codebase:
```suggestion
        if ($container->getParameter('kernel.debug') && $container->hasParameter('.kernel.config_dir') && $container->hasParameter('.kernel.bundles_definition')) {
```

**Comment by nicolas-grekas** [comment]
Thank you @bobvandevijver.
