### PR TITLE
[Finder] Fix SplFileInfo PHPDoc

### LINKED ISSUE #45672: Finder iterators declare wrong SplFileInfo iteration item type (using @extends)
### Symfony version(s) affected

5.4

### Description

symfony/finder iterators pretend to act on items of type \SplFileInfo when in fact (at least some of the iterators) act upon items of type `\Symfony\Component\Finder\SplFileInfo` which includes methods `getRelativePath` and `getRelativePathname`.

Example of affected iterator: PathFilterIterator

### How to reproduce

Example showing actual behavior and PHPStan type analysis (either execute script or pass it to PHPStan):
```
<?php

declare(strict_types=1);

use Symfony\Component\Finder\Iterator\PathFilterIterator;

require __DIR__ . '/vendor/autoload.php';

$it = new PathFilterIterator(new ArrayIterator([new \SplFileInfo(__FILE__)]), [], []);

if (class_exists(\PHPStan::class)) {
    \PHPStan\dumpType($it->current());
    $example = new \Symfony\Component\Finder\SplFileInfo(__FILE__, '', '');
    \PHPStan\dumpType($example);
}

// The following will throw 'Call to undefined method SplFileInfo::getRelativePathname()'
foreach ($it as $item) {
    var_dump($item);
}
```

### Possible Solution

Fix item type in @extends of all iterators that actually require the Symfony variant of SplFileInfo (or maybe all iterators?)

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by InvisibleSmiley**
| Q             | A
| ------------- | ---
| Branch?       | 6.1 (5.4 later)
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45672
| License       | MIT

Not sure how to test this, maybe you do.

### CODE REVIEW

File: src/Symfony/Component/Finder/Iterator/FileTypeFilterIterator.php [hunk 1]
```diff
@@ -26,8 +26,8 @@ class FileTypeFilterIterator extends \FilterIterator
     private int $mode;
 
     /**
-     * @param \Iterator $iterator The Iterator to filter
-     * @param int       $mode     The mode (self::ONLY_FILES or self::ONLY_DIRECTORIES)
+     * @param \Iterator<string, \SplFileInfo> $iterator The Iterator to filter
```
Comment (derrabus) [inline src/Symfony/Component/Finder/Iterator/FileTypeFilterIterator.php:29]: Should we also require our `SplFileInfo` implementation here?

Comment (InvisibleSmiley) [reply src/Symfony/Component/Finder/Iterator/FileTypeFilterIterator.php:29]: Well the question is what we want to achieve here. We have no real control over who is using these iterators besides the Finder implementation itself. Any changes we make here could be perceived as introducing new "bugs" by people who use the iterators in a legitimate/compatible way. Personally, I'm clearly aiming at bug fixes without such potentially controversial side-effects here.

More detailed explanation:

- RecursiveDirectoryIterator::current returns Symfony SplFileInfo, so that's its Iterator value type.
- RecursiveDirectoryIterator is the starting point base iterator in Finder::searchInDirectory, hence the whole Finder iterator chain iterates over Symfony SplFileInfo, too.

So from a strictly internal point of view, all of the iterators use the Symfony SplFileInfo.

To determine which type of SplFileInfo class each iterator *can* use we need to look at the current() method and its calls/usages. Basically there are three cases here:
1. If the current() method is implemented explicitly and returns the Symfony SplFileInfo, that's the Iterator value type. Example: RecursiveDirectoryIterator
2. Usages that access one of the relative path methods require a Symfony SplFileInfo so the corresponding iterator needs to provide that. Example: PathFilterIterator
3. Usages that only access methods of \SplFileInfo can work with any iterator that provides \SplFileInfo or any subclass of it. Example: FileTypeFilterIterator

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @InvisibleSmiley.
