### PR TITLE
[Console] Default hidden question to 1 attempt for non-tty session

### LINKED ISSUE #36565: [Console] Remaining regressions due to #33897
**Symfony version(s) affected**: 4.4.7 / 5.0.7

**Description**  
#33897 caused a regression, which I would call a BC break.

In general I agree with the changes made with the intention to allow
providing input to the application using STDIN.
There are however some edge cases demonstrated here that need some attention.

#### Test 1
Forcing detached terminal (no tty) and not providing any input via STDIN
`echo '' | php console.php hidden:input`
#### Expectation
Error message saying that two required arguments are missing
Output: 
```
Not enough arguments (missing: "password, action").
```
#### Actual
Infinite loop.
This definitely needs a fix in `AskHidden` handling to avoid the infinite loop.
Additionally it would be helpful to inform users that action argument is missing as well.
```
 Password:
 > stty: stdin isn't a terminal
stty: stdin isn't a terminal


                                                                                
 [ERROR] Password must not be empty.                                            
                                                                                

 Password:
 > stty: stdin isn't a terminal
stty: stdin isn't a terminal


                                                                                
 [ERROR] Password must not be empty.                                            
                                                                                
...

```

#### Test 2
Forcing detached terminal (no tty) and not providing any input via STDIN,
but providing password argument
`echo '' | php console.php hidden:input 123456`
#### Expectation
Password argument is set to "123456" and error message that action argument is missing
Output: 
```
Not enough arguments (missing: "action").
```
#### Actual
Works in general, but would be helpful to inform users that action argument is missing
```
 What do you want to do:
 > 

                                                                                
 [ERROR] Action must not be empty.                                              
                                                                                

 What do you want to do:
 > 
            
  Aborted.  
            

hidden:input <password> <action>
```

#### Test 3
Forcing detached terminal (no tty) and providing password argument via STDIN
`echo '123456' | php console.php hidden:input`
#### Expectation
Password argument is set to "123456" and error message that action argument is missing
Output: 
```
Not enough arguments (missing: "action").
```
#### Actual
Works in general, but would be helpful to inform users that action argument is missing.
```
 Password:
 > stty: stdin isn't a terminal
stty: stdin isn't a terminal


 What do you want to do:
 > 
            
  Aborted.  
            

hidden:input <password> <action>
```

**How to reproduce**  
Here is an [example application](https://github.com/helhum/sf-console-test)
to test out the issues I discovered.

**Possible Solution**  
1. The infinite loop is triggered, because the [hidden response](https://github.com/symfony/symfony/blob/83b37e8010b3686a5c6be35eb4a38d89b6342799/src/Symfony/Component/Console/Helper/QuestionHelper.php#L117) is empty, but it is checked for [false](https://github.com/symfony/symfony/blob/83b37e8010b3686a5c6be35eb4a38d89b6342799/src/Symfony/Component/Console/Helper/QuestionHelper.php#L125)

Probably checking whether the return value is an empty string and setting `$ret` to false in this case will fix it.

2. Calling `interact` even when no tty is available.
That is a tough one, as doing so is major part of the initial fix.
It could be mitigated, by wrapping the call in a try/catch, catching MissingInputException, setting to non iteractive in the catch and letting the application continue. This would in my case at least output the error message about the missing argument in the end.

3. Cluttered output
Since the output for the questions is already sent, the output will look much more cluttered than before. Depending on the type of the cli application, this might be acceptable, but as well might not.

This could be mitigated by an additional Application option/property whether to evaluate the existance of a tty and set interactive to false in this case or not.
If this would be accepted, it would be up for decision which the default behaviour should be.

### PR DESCRIPTION
**Pull request by ostrolucky**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36565
| License       | MIT
| Doc PR        | 

### Problem 1
`validateAttempts()` method repeats validation forever by default, until exception extending `RuntimeException` isn't thrown. This currently happens disregarding if user is in tty session where they can actually type input, or non-tty session. This presents a problem when user code throws custom exceptions for hidden questions -> loop doesn't stop. As far as I can tell this issue is in all Symfony versions, but it was uncovered only after we stopped marking interactive flag to false automatically ourselves. Actually, all 3 problems were already existing problems, just hidden until now.
### Problem 2
Infinite loop problem is related to hidden questions, but this one isn't. If validation fails, another attempt to read & validate happens. This means user will get two prompts: 2x same question with 2 different error messages. One error message coming from validator, second error message about inability to read input (because this loop repeats until this kind of error happens, so last output will always be this error). As an example, output in practice would look like following
```

 What do you want to do:
 > 

                                                                                
 [ERROR] Action must not be empty.                                              
                                                                                

 What do you want to do:
 > 
            
  Aborted.  
            

```

So even if loop stops, output is more than expected.

### Problem 3
This is purely cosmetic issue, but currently user gets `stty: stdin isn't a terminal` printed additionally when question helper tries to ask a hidden question without having tty. I have fixed this in same fashion as was already done for [getShell() method](https://github.com/symfony/symfony/blob/ee7fc5544ef6bf9f410f91ea0aeb45546a0db740/src/Symfony/Component/Console/Helper/QuestionHelper.php#L500).

### More details
Well root of the first problem is that `\Symfony\Component\Console\Helper\QuestionHelper::getHiddenResponse` is inconsistent. In some cases it does throw `MissingInputException` (which extends `RuntimeException`), in others doesn't. This is because in others, `shell_exec` is used, which won't return `false` even in non-tty sessions. Initially I attempted to fix this and make them consistent by checking for empty result + `isTty` call, but during my testing I found that at least last, `bash -c` method returns `\n` as output both when passing empty input and when passing newline as input. This means we cannot differentiate with this technique when input is really empty, or at least I can't currently tell how, maybe someone does. I had also idea to use proc_open and check if `STDERR` cotains message about stdin not being a terminal, but I realized these functions might not be available. In future we should modernize this method to use less hacky techniques. Other solutions, eg. Inquirer.js or [hoa/console](https://github.com/hoaproject/Console/blob/master/Source/Readline/Readline.php) have much more elegant solutions. Anyway, since I encountered this issue and additionally this doesn't solve Problem 2, I stopped trying to fix this on this level.

### Alternative solution
Alternative solution to problem 1 and 3 would be to fallback to default in case of hidden questions when tty is missing. But this still doesn't solve problem 2 and I can't think about solution right now which would fix problem 2 separately. We also didn't really reach consensus if reading passwords via stdin is desired. I tried this in `Inquirer.js` and this library *does read password from stdin*

### CODE REVIEW

File: src/Symfony/Component/Console/Helper/QuestionHelper.php [hunk 1]
```diff
@@ -461,6 +461,11 @@ private function validateAttempts(callable $interviewer, OutputInterface $output
     {
         $error = null;
         $attempts = $question->getMaxAttempts();
+
+        if (null === $attempts && !$this->isTty()) {
```
Comment (helhum) [inline src/Symfony/Component/Console/Helper/QuestionHelper.php:465]: What I don't understand is, why run stty at all if there is no tty? Running it will cause `stty: stdin isn't a terminal` error messages

Comment (ostrolucky) [reply src/Symfony/Component/Console/Helper/QuestionHelper.php:465]: I've silenced those messages in this patch, but indeed you are right. Why do we still attempt to read here? Because despite the message, it apparently still works and returns content in stdin.

Comment (helhum) [reply src/Symfony/Component/Console/Helper/QuestionHelper.php:465]: Ah, right! I somehow managed to forget about that. Then this change indeed fixes the infinite loop I ran into.

**Review by nicolas-grekas — APPROVED** [review]

**Review by helhum — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @ostrolucky.
