### PR TITLE
[Messenger] Allow setting retry delay by `RecoverableExceptionInterface`

### LINKED ISSUE #57756: [Messenger] Add option to set custom delay on RecoverableMessageHandlingException
### Description

Add an optional argument to the `RecoverableMessageHandlingException` that allows messenger to delay the retry for longer than the configured retry if the developer already knows that it'll take longer, but should be retried.

Useful in many scenarios, the code example uses the Retry-After header that is often accompanied by a 503. Some APIs with rate limits will also include headers when a rate limit is hit for when it can be retried.
Or simply to delay the retry of this 1 message, while all other messages should adhere to the configured retry timeouts.

### Example

Before:
```php
#[AsMessageHandler]
class ExampleMessageHandler
{
    public function __invoke(ExampleMessage $message): void
    {
        try {
            (new Client())->get('http://someapi');
        } catch (ServerException $ex) {
            $retryAfter = $this->parseResponseRetryAfter($ex->getResponse());
            $this->messageBus->dispatch(new ExampleMessage(), [new DelayStamp($retryAfter)]);
        } 
    }
}
```
Message is interpreted as a new message, previous retries, stamps,... are discarded.

After:
```php
#[AsMessageHandler]
class ExampleMessageHandler
{
    public function __invoke(ExampleMessage $message): void
    {
        try {
            (new Client())->get('http://someapi');
        } catch (ServerException $ex) {
            $retryAfter = $this->parseResponseRetryAfter($ex->getResponse());
            throw new RecoverableMessageHandlingException(retryAfter: $retryAfter);
        }
    }
}
```
Message retains all of its previous stamps etc, but a delay stamp is added when the message can be retried again that may be larger (or smaller) than the default retry time.

### PR DESCRIPTION
**Pull request by valtzu**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #57756
| License       | MIT

Allow overriding retry delay from the retry strategy by providing it in the exception. Example use case is retrying http request based on `Retry-After` header.

### CODE REVIEW

File: src/Symfony/Component/Messenger/Exception/RecoverableExceptionInterface.php [hunk 1]
```diff
@@ -18,6 +18,8 @@
  * and the message should be retried, a handler can throw such an exception.
  *
  * @author Jérémy Derussé <jeremy@derusse.com>
+ *
+ * @method int|null getRetryDelay()
```
Comment (94noni) [inline src/Symfony/Component/Messenger/Exception/RecoverableExceptionInterface.php]: Perhaps add which unit this delay is :)

File: src/Symfony/Component/Messenger/CHANGELOG.md [hunk 2]
```diff
@@ -7,6 +7,7 @@ CHANGELOG
  * `WrappedExceptionsInterface` now extends PHP's `Throwable` interface
  * Add `#[AsMessage]` attribute with `$transport` parameter for message routing
  * Add `--format` option to the `messenger:stats` command
+ * Add `getRetryDelay` method to `RecoverableExceptionInterface`
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/CHANGELOG.md]:
```suggestion
 * Add `getRetryDelay()` method to `RecoverableExceptionInterface`
```

File: src/Symfony/Component/Messenger/Exception/RecoverableExceptionInterface.php [hunk 3]
```diff
@@ -18,6 +18,8 @@
  * and the message should be retried, a handler can throw such an exception.
  *
  * @author Jérémy Derussé <jeremy@derusse.com>
+ *
+ * @method int|null getRetryDelay() The time to wait in milliseconds.
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Exception/RecoverableExceptionInterface.php]:
```suggestion
 * @method int|null getRetryDelay() The time to wait in milliseconds
```

File: src/Symfony/Component/Messenger/Exception/RecoverableMessageHandlingException.php [hunk 4]
```diff
@@ -18,4 +18,13 @@
  */
 class RecoverableMessageHandlingException extends RuntimeException implements RecoverableExceptionInterface
 {
+    public function __construct(string $message = "", int $code = 0, ?\Throwable $previous = null, private readonly ?int $retryDelay = null)
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Exception/RecoverableMessageHandlingException.php]:
```suggestion
    public function __construct(string $message = '', int $code = 0, ?\Throwable $previous = null, private readonly ?int $retryDelay = null)
```

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @valtzu.
