### PR TITLE
[PhpUnitBridge] fix handling the COMPOSER_BINARY env var when using simple-phpunit

### LINKED ISSUE #41774: [PhpunitBridge] Can't set the composer binary
**Symfony version(s) affected**: Since 3.4.0 it seems ?

**Description**
If you have let's say composer 1 and composer 2 both installed with different binary paths, you before had the possibility to tell phpunit-bridge what executable it should use.

This is not the case anymore, so it will always fallback (or try to find) a `composer` binary... which can be 1.0, when there can be another binary such as `composer2` available.

**How to reproduce**
Install both versions of composer, let's say `composer` and `composer2`. `composer` will always be used, even if you set the `COMPOSER_BINARY` variable as it should be.

**Possible Solution**
Reintroduce the `COMPOSER_BINARY` env var in the simple-phpunit bridge since 4.4.

### PR DESCRIPTION
**Pull request by Taluu**
| Q             | A
| ------------- | ---
| Branch?       | 4.4 and next
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no 
| Tickets       | Fix #41774
| License       | MIT

Since the renaming of the simple phpunit file (from the shebang to the php file) in #31364, it looks like the change made from #36566 was lost as it seems to have been merged after.

So this PR is an attempt to "restore" that functionnality, as it was considered a bug fix on 3.4 at the time.

poke @nicolas-grekas

### CODE REVIEW

**Review by stof — APPROVED** [review]

File: src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php [hunk 1]
```diff
@@ -150,12 +150,14 @@
     putenv('SYMFONY_DEPRECATIONS_HELPER=disabled');
 }
 
-$COMPOSER = file_exists($COMPOSER = $oldPwd.'/composer.phar')
-    || ($COMPOSER = rtrim((string) ('\\' === \DIRECTORY_SEPARATOR ? preg_replace('/[\r\n].*/', '', `where.exe composer.phar 2> NUL`) : `which composer.phar 2> /dev/null`)))
-    || ($COMPOSER = rtrim((string) ('\\' === \DIRECTORY_SEPARATOR ? preg_replace('/[\r\n].*/', '', `where.exe composer 2> NUL`) : `which composer 2> /dev/null`)))
-    || file_exists($COMPOSER = rtrim((string) ('\\' === \DIRECTORY_SEPARATOR ? `git rev-parse --show-toplevel 2> NUL` : `git rev-parse --show-toplevel 2> /dev/null`)).\DIRECTORY_SEPARATOR.'composer.phar')
-    ? ('#!/usr/bin/env php' === file_get_contents($COMPOSER, false, null, 0, 18) ? $PHP : '').' '.escapeshellarg($COMPOSER) // detect shell wrappers by looking at the shebang
-    : 'composer';
+if (false === $COMPOSER = \getenv('COMPOSER_BINARY')) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php]: let's remove the leading `\`, it's not needed

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php (hunk 1 above)
Comment (Taluu) [reply src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php]: done

**Comment by Taluu** [comment]
Note : Failures from fabbot are unrelated to the modification. Should I still apply them ?

**Comment by nicolas-grekas** [comment]
> Note : Failures from fabbot are unrelated to the modification. Should I still apply them ?

no need

**Comment by nicolas-grekas** [comment]
Thank you @Taluu.
