### PR TITLE
[Serializer] Ignore getter with required parameters (Fix #46592)

### LINKED ISSUE #46592: ObjectNormalizer can't normalize data if data class has annotation @Ignore and method "getSomething" with the required parameter
### Symfony version(s) affected

6.1.0

### Description

ObjectNormalizer can't normalize data if data class has annotation @Ignore and method "getSomething" with the required parameter.
If data class don't use `@Ignore ` annotation then methods with prefix get and required parameters are successfully ignored. But if any other method is annotated with `@Ignore` in this case ObjectNormalizer fails to ignore "get" methods with required parameters.

### How to reproduce

```
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Doctrine\Common\Annotations\AnnotationReader;
use Symfony\Component\Serializer\Annotation\Ignore;
use Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory;
use Symfony\Component\Serializer\Mapping\Loader\AnnotationLoader;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

class Person
{
    private $name;

    public function setName($name)
    {
        $this->name = $name;
    }

    public function getName()
    {
        return $this->name;
    }

    /**
     * @Ignore()
     */
    public function getLowerCaseName()
    {
        return strtolower($this->name);
    }

    public function getNameWithPrefix($prefix)
    {
        return sprintf('%s %s', $prefix, $this->name);
    }
}

$data = [
    'name' => 'Person name',
];

$metaFactory = new ClassMetadataFactory(new AnnotationLoader(new AnnotationReader()));
$serializer = new Serializer([new ObjectNormalizer($metaFactory)]);

$person = $serializer->denormalize($data, Person::class);

$personData = $serializer->normalize($person);
var_dump($personData);
```
expected response:
`array(2) {
  ["name"]=>
  string(11) "Person name"
}
`
got:
```
Fatal error: Uncaught Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: Can't get a way to read the property "nameWithPrefix" in class "Person". in /home/project/test/my_project/vendor/symfony/property-access/PropertyAccessor.php:449
Stack trace:
#0 /home/project/test/my_project/vendor/symfony/property-access/PropertyAccessor.php(115): Symfony\Component\PropertyAccess\PropertyAccessor->readProperty(Array, 'nameWithPrefix', false)
#1 /home/project/test/my_project/vendor/symfony/serializer/Normalizer/ObjectNormalizer.php(140): Symfony\Component\PropertyAccess\PropertyAccessor->getValue(Object(Person), 'nameWithPrefix')
#2 /home/project/test/my_project/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(183): Symfony\Component\Serializer\Normalizer\ObjectNormalizer->getAttributeValue(Object(Person), 'nameWithPrefix', NULL, Array)
#3 /home/project/test/my_project/vendor/symfony/serializer/Serializer.php(161): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize(Object(Person), NULL, Array)
#4 /home/project/test/my_project/rep.php(47): Symfony\Component\Serializer\Serializer->normalize(Object(Person))

```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by astepin**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no
| Tickets       | Fix #46592 
| License       | MIT
| Doc PR        | na

If no Ignore annotation is used, the attributes for serialization are obtained using `Symfony\Component\Serializer\Normalizer\ObjectNormalizer::extractAttributes`.
There it is checked if the method has required parameters and if yes, the method is ignored. 

However, if you use the Ignore annotation, the attributes are determined with a different method. Here I have adapted at least for get methods the behavior as it was before.

If someone serialized a class with Ignore annotations before, he got here `\Symfony\Component\PropertyAccess\PropertyAccessor::readProperty` an exception as written in ticket #46592. With this fix the methods are ignored and there is no exception anymore.

### CODE REVIEW

**Review by dunglas — APPROVED** [review]

File: src/Symfony/Component/Serializer/Tests/Fixtures/Annotations/IgnoreDummyAdditionalGetter.php [hunk 1]
```diff
@@ -0,0 +1,25 @@
+<?php
+
+declare(strict_types=1);
```
Comment (fabpot) [inline src/Symfony/Component/Serializer/Tests/Fixtures/Annotations/IgnoreDummyAdditionalGetter.php]: This should be removed in all classes as we're not using this in Symfony.

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Serializer/Tests/Fixtures/Annotations/IgnoreDummyAdditionalGetter.php (hunk 1 above)
Comment (astepin) [reply src/Symfony/Component/Serializer/Tests/Fixtures/Annotations/IgnoreDummyAdditionalGetter.php]: I was not aware of that. Is now corrected. I also removed it from two entities that I had added in my last bug fix with the same problem.

Comment (astepin) [reply src/Symfony/Component/Serializer/Tests/Fixtures/Annotations/IgnoreDummyAdditionalGetter.php]: Shouldn't this rule perhaps also be checked automatically? I couldn't find anything quickly but why don't you use strict_types?

**Review by mtarld — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @astepin.

File: src/Symfony/Component/Serializer/Mapping/Loader/AnnotationLoader.php [hunk 2]
```diff
@@ -100,6 +100,11 @@ public function loadClassMetadata(ClassMetadataInterface $classMetadata)
                 continue;
             }
 
+            $getAccessor = preg_match('/^(get|)(.+)$/i', $method->name);
```
Comment (guilliamxavier) [inline src/Symfony/Component/Serializer/Mapping/Loader/AnnotationLoader.php:103]: This regex looks "fishy": ignoring capturing groups (as matches are not used), it's equivalent to `/^(get)?.+$/i` i.e. just `/^.+$/` i.e. will match *any* method (not only getters)

Comment (jsor) [reply src/Symfony/Component/Serializer/Mapping/Loader/AnnotationLoader.php:103]: I've filed #47255 to fix this.

Comment (astepin) [reply src/Symfony/Component/Serializer/Mapping/Loader/AnnotationLoader.php:103]: I missed that. A copy paste error. Thanks @jsor for fixing
