### PR TITLE
[Messenger] Allow to skip message in `FailedMessagesRetryCommand`

### LINKED ISSUE #50936: [Messenger] Add 'skip' to options in interactive messenger:failed:retry command
### Description

It would be very convenient when, next to 'retry' and 'delete' a third option is available to skip the specific message from the failed queue. That way, we can run `bin/console messenger:failed:retry` and postpone the choice to retry of delete a specific message to a later moment, while processing other messages.

Now, I have to do a `messenger:failed:status` first, then copy all ID's as parameters for the `messenger:failed:retry` and confirm every retry. Of course I can add `--force`, but to prevent problems due to an incorrect copy-paste I don't dare to do that.

Creating a PR for this seems to be not very difficult, but I am not sure how to reflect this in the test cases.

### Example

_No response_

### PR DESCRIPTION
**Pull request by Kazadri**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #50936 
| License       | MIT

When retrying message with the command messenger:failed:retry, we have two options:
- Retry : (It will be consumed and re-added to failed queue if it re-fail)
- Delete

But sometimes we have no clue if we can retry it or not but I know that we don't want to delete it yet. In that case we need to stop the command and go id by id. The interactive command is lost. The command should provide a way to skip a message to continue with the rest of the failed message.

### CODE REVIEW

File: src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php [hunk 1]
```diff
@@ -213,6 +216,10 @@ private function runWorker(string $failureTransportName, ReceiverInterface $rece
                 return;
             }
 
+            if ('skip' === $choice) {
+                $this->eventDispatcher->dispatch(new WorkerMessageSkipEvent($envelope, $envelope->last(SentToFailureTransportStamp::class)->getOriginalReceiverName()));
```
Comment (94noni) [inline src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php:220]: shouldnt the code stop after that?
seeing the `$receiver->reject($envelope);` after seem weird 

or its more like the current is skipped and so cloned via the skip event ? so added back to the queue ?

Comment (94noni) [reply src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php:220]: also in the help() method above, you need to change the doc part of:

`The command will interactively ask if each message should be retried or discarded.`

`The command will interactively ask if each message should be retried, discarded or skipped.` :)

File: src/Symfony/Component/Messenger/CHANGELOG.md [hunk 2]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+7.2
+---
+
+* Add `skip` option to `messenger:failed:retry` command to neither ack nor reject message
```
Comment (94noni) [inline src/Symfony/Component/Messenger/CHANGELOG.md]:
```suggestion
* Add `skip` option to `messenger:failed:retry` command when run interactively to skip message and requeue it
```

wdyt?

Comment (Kazadri) [reply src/Symfony/Component/Messenger/CHANGELOG.md]: Sure !

File: src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php (hunk 1 above)
Comment (Kazadri) [reply src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php:220]: This is exactly that ! I dispatch an event to create a clone of the message and the end of the queue and I reject the current message to avoid duplication.
(Also I've edited the help method)

**Review by 94noni — APPROVED** [review]
I dont know deeply the internal of messenger, but if it is accepted as is its a simple solution 👌🏼

File: src/Symfony/Component/Messenger/CHANGELOG.md [hunk 3]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+7.2
+---
+
+* Add `skip` option to `messenger:failed:retry` command when run interactively to skip message and requeue it
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/CHANGELOG.md]:
```suggestion
 * Add `skip` option to `messenger:failed:retry` when running interactively to skip message and requeue it
```

**Review by nicolas-grekas — COMMENTED** [review]
Does this implementation mean that skipping will update the failure date? If yes, is there any way around?
Is there no way to just NACK the message and go to the next one?
Note that the answer might be just "no" by design, I don't remember this aspect :)
Anyone else can tell?

File: src/Symfony/Component/Messenger/CHANGELOG.md (hunk 3 above)
Comment (Kazadri) [reply src/Symfony/Component/Messenger/CHANGELOG.md]: There will be no change in display but for some transport (like doctrine) the created_at will actually be updated.
Before retry :
image
After retry :
image

I've tried to just ignore the message and go to the next one but for the DoctrineTransport the same message will be prompt immediately since message are retrieved one by one :
```php
if ($receiver instanceof ListableReceiverInterface) {
            // for listable receivers, find the messages one-by-one
            // this avoids using get(), which for some less-robust
            // transports (like Doctrine), will cause the message
            // to be temporarily "acked", even if the user aborts
            // handling the message
}

**Review by fabpot — APPROVED** [review]
@Kazadri Can you rebase on current 7.2 to get rid of the merge commit?

**Comment by Kazadri** [comment]
> @Kazadri Can you rebase on current 7.2 to get rid of the merge commit?

Sure, it's done ! :+1:

**Comment by fabpot** [comment]
Thank you @Kazadri.

File: src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php [hunk 4]
```diff
@@ -204,7 +206,8 @@ private function runWorker(string $failureTransportName, ReceiverInterface $rece
 
             $this->forceExit = true;
             try {
-                $shouldHandle = $shouldForce || 'retry' === $io->choice('Please select an action', ['retry', 'delete'], 'retry');
+                $choice = $io->choice('Please select an action', ['retry', 'delete', 'skip'], 'retry');
+                $shouldHandle = $shouldForce || 'retry' === $choice;
```
Comment (W0rma) [inline src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php:210]: With this change the user is always asked to select an option even if `--force` was used.

I'm going to prepare a fix
EDIT see https://github.com/symfony/symfony/pull/60293
