### PR TITLE
[ExpressionLanguage] Fix matching null against a regular expression

### LINKED ISSUE #45926: [ExpressionLanguage] Matches throws error for null values
### Symfony version(s) affected

5.4.7

### Description

In #45875 a behavior change was introduced.

### How to reproduce

Previously the following code worked as expected:

```php
(new ExpressionLanguage)->evaluate('foo matches "/bar/"', ['foo' => null]);
```

Since version 5.4.7 this now throws a `TypeError: Symfony\Component\ExpressionLanguage\Node\BinaryNode::evaluateMatches(): Argument #2 ($str) must be of type string, null given`

### Possible Solution

If this is considered a bug or a BC break I’m happy to create a pull request to fix this (including a deprecation notice for non-string values I’d assume).

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ausi**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45926
| License       | MIT
| Doc PR        | -

As discussed in https://github.com/symfony/symfony/issues/45926#issuecomment-1086842590

The bug was introduced by #45875

### CODE REVIEW

File: src/Symfony/Component/ExpressionLanguage/Node/BinaryNode.php [hunk 1]
```diff
@@ -173,13 +173,13 @@ public function toArray()
         return ['(', $this->nodes['left'], ' '.$this->attributes['operator'].' ', $this->nodes['right'], ')'];
     }
 
-    private function evaluateMatches(string $regexp, string $str): int
+    private function evaluateMatches(string $regexp, string $str = null): int
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ExpressionLanguage/Node/BinaryNode.php]: I'd prefer writing this as `?string $str` since the argument is not optional.
Also, we should do a similar cast to string on L55 I think.

Comment (ausi) [reply src/Symfony/Component/ExpressionLanguage/Node/BinaryNode.php]: I wasn’t sure if `?string` is already supported by the lowest PHP version for 4.4 ☺️

Updated in 30e2382cf17826e569b300064178e9021f7a02d8 and 399c3e3b45e9ff3c123801c0fd3d3a3679a3be52

**Review by nicolas-grekas — APPROVED** [review]

**Review by m-vo — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @ausi.
