### PR TITLE
[Yaml] Fix Yaml Parser with quote end in a new line

### LINKED ISSUE #33082: [YAML] Parser fails with empty new line
**Symfony version(s) affected**: 4.3.3

**Description**  
The `YAML::parse()` method fails on this string:

```
---
controller_organisation_membres_inc_mailer:
  alert:
    emailSent: 1 email a été envoyé.
    emailsSentInHour: "{nb} emails sont programmés pour être envoyés dans l'heure qui vient."
    error: Une erreur s'est produite.
    oneEmailSent: 1 email a été envoyé. Certains utilisateurs (sans adresse email) n'ont pas été ajoutés à cette liste d'envoi.
    scheduledEmailsSent: "{nb} emails sont programmés pour être envoyés dans l'heure qui vient. Certains utilisateurs (sans adresse email) n'ont pas été ajoutés à cette liste d'envoi."
    selectUser: Veuillez sélectionner au moins une personne.
    usersNoEmail: Les utilisateurs sélectionnés n'ont pas d'email.
  cancel: Annuler
  communicate: 'VOUS SAVEZ COMMUNIQUER !

'
  fillAdress: Veuillez indiquer une adresse de réponse.
  fillMessage: Veuillez indiquer le contenu de votre message.
  fillSubject: Veuillez indiquer le sujet de votre message.
  form:
    userMailer:
      usersMailerLightboxButtonSite: Afficher un bouton d'accès au site en bas du mail
      usersMailerLightboxDocumentIds: Joindre des fichiers
      usersMailerLightboxMessage:
        label: Votre message *
        placeholder: Votre message *
      usersMailerLightboxReplyTo:
        label: Répondre à
        placeholder: Répondre à
      usersMailerLightboxSubject:
        label: Sujet *
        placeholder: Sujet *
  h2:
    createCampagne: Créez une campagne d'emailing
    sendMessage: ou envoyez un message rapidement
  nbEmailSent: 'Déjà {nb} emails envoyés ce mois ! Changez de dimension, passez à un abonnement payant.

'
  pricing: Découvrir les tarifs
  submit: Envoyer
  template:
    button:
      emailing: Créer une nouvelle campagne
  trialMode: 'Vous êtes actuellement en période d''essai : 5 emails maximum seront envoyés.'
  warning: Attention, créez une campagne si vous souhaitez obtenir des statistiques sur cet envoi.

```

**How to reproduce**  
`YAML::parse($previousString);`
Throws this exception: `Malformed inline YAML string` in vendor/symfony/yaml/Inline.php on line 120

**Possible Solution**  
`controller_organisation_membres_inc_mailer.communicate` has empty new lines.
Same with `nbEmailSent`

**Additional context**  
https://yaml-online-parser.appspot.com/ successfully parses the string

### PR DESCRIPTION
**Pull request by maxbeckers**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #33082
| License       | MIT
| Doc PR        | N/A

This is a fix for issue #33082.

The bug described in the ticket breaks on a ending quote in a new line:
```
foo:
  bar: 'baz

'
  baz: 'Lorem'
```
Before the fix:
`Symfony\Component\Yaml\Exception\ParseException: Malformed inline YAML string: 'baz at line 4.`

There was already a PR #33119, which was closed because of problems.

### CODE REVIEW

File: src/Symfony/Component/Yaml/Tests/YamlTest.php [hunk 1]
```diff
@@ -24,6 +25,38 @@ public function testParseAndDump()
...
+'
+  baz: 'Lorem
+
+       ipsum'
+  foobar: 'foobar'
+YAML;
+
+        $this->assertSame(['foo' => ['bar' => "baz\n", 'baz' => "Lorem\nipsum", 'foobar' => 'foobar']], Yaml::parse($yaml));
+
+        $yamlInvalid = <<<YAML
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Tests/YamlTest.php]: let's move this into a separate test

File: src/Symfony/Component/Yaml/Parser.php [hunk 2]
```diff
@@ -654,6 +654,9 @@ private function getNextEmbedBlock(int $indentation = null, bool $inSequence = f
             if ($this->isCurrentLineBlank()) {
                 $data[] = substr($this->currentLine, $newIndent);
                 continue;
+            } elseif ($this->isCurrentLineQuoteEnd()) {
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Parser.php]: Won't this break cases where the current line does contain other characters before the terminating quotation character?

Comment (xabbuh) [reply src/Symfony/Component/Yaml/Parser.php]: And do we also need to take into account if the character matches the starting quotation character (and we are are actually parsing a quoted string at all here)?

Comment (maxbeckers) [reply src/Symfony/Component/Yaml/Parser.php]: Thanks for your comments.

The method `isCurrentLineQuoteEnd()` is only checking if there is only one quote (' or ") in the trimmed line.

I tried to show with the invalid testcase, that the parser will fail when there is sth wrong with the quotes.

Yes, it's just a simple fix for the problems described in the issue. Maybe too simple? If there are lines with text in the quoted string, this lines have to be correctly indented. There is a bit the Problem, how the yaml parser is working. The qutotes with the text between are interpreted later in the process.

Comment (xabbuh) [reply src/Symfony/Component/Yaml/Parser.php]: Oh indeed, when writing the comment I mistakenly assumed that the new method was only checking if the current line ended with the quotation character.

**Review by nicolas-grekas — APPROVED** [review]
LGTM but I'd like to ping @xabbuh also :)

File: src/Symfony/Component/Yaml/Tests/YamlTest.php [hunk 3]
```diff
@@ -24,6 +25,37 @@ public function testParseAndDump()
...
+  bar: 'baz
+
+'
+  baz: 'Lorem
+
+       ipsum'
+  foobar: 'foobar'
+YAML;
+
+        $this->assertSame(['foo' => ['bar' => "baz\n", 'baz' => "Lorem\nipsum", 'foobar' => 'foobar']], Yaml::parse($yaml));
```
Comment (javiereguiluz) [inline src/Symfony/Component/Yaml/Tests/YamlTest.php]: Maybe I'm misunderstanding something, but I'd expected the test to be:

```php
$this->assertSame(['foo' => ['bar' => "baz\n\n", 'baz' => "Lorem\n\nipsum", 'foobar' => 'foobar']], ...)
```

Comment (maxbeckers) [reply src/Symfony/Component/Yaml/Tests/YamlTest.php]: Hi @javiereguiluz, 
thanks for your comment. Please have a look at [this comment](https://github.com/symfony/symfony/pull/33119#issuecomment-520350652) , there you already mentioned the same and @nicolas-grekas added a yaml parser online tool screenshot, thos is the way yaml works in this cases.

File: src/Symfony/Component/Yaml/Tests/YamlTest.php [hunk 4]
```diff
@@ -24,6 +25,37 @@ public function testParseAndDump()
         $this->assertEquals($data, $parsed);
     }
 
+    public function testParseWithMultilineQuotes()
+    {
+        $yaml = <<<YAML
+foo:
+  bar: 'baz
+
+'
```
Comment (fabpot) [inline src/Symfony/Component/Yaml/Tests/YamlTest.php:35]: This is not valid YAML AFAIU. The quote must be indented.

**Review by fabpot — CHANGES_REQUESTED** [review]
I've tried many online parser, written in different languages, which all behave differently.
I would not change the current behavior if the spec is unclear on this, as this would be a BC break.

So, that's a :-1: from me for this change.

File: src/Symfony/Component/Yaml/Tests/YamlTest.php (hunk 4 above)
Comment (maxbeckers) [reply src/Symfony/Component/Yaml/Tests/YamlTest.php:35]: Then we should close this PR and the issue with "Won't fix", because this is exactly the case, what is requested to be fixed!

Comment (xabbuh) [reply src/Symfony/Component/Yaml/Tests/YamlTest.php:35]: If I am not mistaken, this is indeed valid YAML.

**Review by xabbuh — APPROVED** [review]

File: src/Symfony/Component/Yaml/Tests/YamlTest.php (hunk 4 above)
Comment (maxbeckers) [reply src/Symfony/Component/Yaml/Tests/YamlTest.php:35]: Hi @xabbuh and @fabpot,

I have taken some time to read up on this YAML topic. In the internet are two kinds of YAML parser for this topic. Either the content must be indented even if it is in quotes or everything in quotes can be indented free, because the part in quotes is simply considered as a text block.

What I want to say is that the PR should not be merged as it is and we should decide here how to proceed.

Solution A: everything should be how it is and we only support indented quotes, seems to be how it's described in the spec [https://yaml.org/spec/1.2.2/#8111-block-indentation-indicator](https://yaml.org/spec/1.2.2/#8111-block-indentation-indicator).
```
foo:
  bar: 'baz

       '
```

Solution B: be a bit more generous and allow what requested in the issue and how a lot of online parsers/validators see the quoted part as a string and allow stuff like that:
```
foo:
  bar: 'baz1
baz2
                baz3

'
```

Based on that I'd prefer solution A and keep it how it is as @fabpot mentioned. What do you think?

**Review by nicolas-grekas — CHANGES_REQUESTED** [review]
I think we should merge this since this is YAML compliant, isn't it?

But there's still an issue since this fails:

```patch
--- a/src/Symfony/Component/Yaml/Tests/YamlTest.php
+++ b/src/Symfony/Component/Yaml/Tests/YamlTest.php
@@ -30,6 +30,7 @@ class YamlTest extends TestCase
         $yaml = <<<YAML
 foo:
   bar: 'baz
+biz
 
 '
   baz: 'Lorem
@@ -38,7 +39,7 @@ foo:
   foobar: 'foobar'
 YAML;
 
-        $this->assertSame(['foo' => ['bar' => "baz\n", 'baz' => "Lorem\nipsum", 'foobar' => 'foobar']], Yaml::parse($yaml));
+        $this->assertSame(['foo' => ['bar' => "baz biz\n", 'baz' => "Lorem\nipsum", 'foobar' => 'foobar']], Yaml::parse($yaml));
     }
```

**Comment by maxbeckers** [comment]
@nicolas-grekas you're right ... this is solution b, I described [here](https://github.com/symfony/symfony/pull/48022#discussion_r1102430776) ... this is not possible with the current implementation  and this would be a bigger change of the yaml component. Because for that the component needs to understand the context (this is part of a quoted multiline string) ... for now it just reads the yaml line by line at this point of the yaml parser ... I'll have a look on that and see whats possible.

**Comment by maxbeckers** [comment]
@nicolas-grekas please have a look, now your case is also supported by the solution ... 

**UPDATE** Does not work as expected in special cases when the text contains a single quote (for example "Une erreur s'est produite.") ... I'll investigate into that next week.

**Comment by fabpot** [comment]
> I think we should merge this since this is YAML compliant, isn't it?

Just my 2cts here: the goal of the YAML component has never been to be 100% compliant, as YAML is a weird beast. The goal has always been to cover what we need for configuration. (I'm not saying that we should not merge this PR, but I just wanted to give some historical context).

**Comment by maxbeckers** [comment]
HI @fabpot,
thanks for the context. I'm fine with closing this PR and the related Issue with "Won't fix" (as I said already on your last comment) when we say we won't support that, because it's created to handle our configuration.
But @nicolas-grekas came up last friday and asked to fix his use-case. Now it seems all to be fixed and to work fine.

So Im fine with closing this PR, merging it into 5.4 or maybe because of BC breaks merge it to 6.4.

**Comment by fabpot** [comment]
Let's finish the work and merge it as the work has been done.
It's nice to support more YAML features.
Again, I just wanted to highlight the philosophy I had we I created the component two decades ago :exploding_head:

File: src/Symfony/Component/Yaml/Parser.php [hunk 5]
```diff
@@ -993,6 +1007,28 @@ private function isCurrentLineLastLineInDocument(): bool
...
+    /**
+     * Returns true if the current line is the beginning of a multiline quoted block.
+     */
+    private function isCurrentLineMultiLineQuoteStart(): bool
+    {
+        $trimmedLine = trim($this->currentLine);
+        $quoteCount = 0;
+        $value = '';
+        // check if the key is quoted
+        foreach (str_split($trimmedLine) as $i => $char) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Yaml/Parser.php]: better not use str_split, a "for" should do it

File: src/Symfony/Component/Yaml/Parser.php [hunk 6]
```diff
@@ -993,6 +1007,28 @@ private function isCurrentLineLastLineInDocument(): bool
...
+            if ("'" === $char) {
+                ++$quoteCount;
+            } elseif (':' === $char && 0 === $quoteCount % 2) {
+                // key and value are separated by the first colon after the (quoted) key
+                $value = trim(substr($trimmedLine, ++$i), ' ');
+                break;
+            }
+        }
+
+        return str_starts_with($value, "'") && !str_ends_with($this->currentLine, "'");
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Yaml/Parser.php]: what about this?
```yaml
'a''
b'
```

Comment (maxbeckers) [reply src/Symfony/Component/Yaml/Parser.php]: yes, you're right, could also happen.

**Comment by maxbeckers** [comment]
Added support for a colon in the unquoted key

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Yaml/Tests/YamlTest.php [hunk 7]
```diff
@@ -24,6 +25,56 @@ public function testParseAndDump()
...
+  a: 'b''
+c'
+  empty: ''
+  foo:bar: 'foobar'
+YAML;
+
+        $this->assertSame(['foo' => [
+            'bar' => "baz biz\n",
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Tests/YamlTest.php:52]:
```suggestion
            'bar' => 'baz biz ',
```

File: src/Symfony/Component/Yaml/Tests/YamlTest.php [hunk 8]
```diff
@@ -24,6 +25,56 @@ public function testParseAndDump()
...
+            'baz' => "Lorem\nipsum",
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Tests/YamlTest.php:53]:
```suggestion
            'baz' => 'Lorem ipsum',
```

File: src/Symfony/Component/Yaml/Tests/YamlTest.php [hunk 9]
```diff
@@ -24,6 +25,56 @@ public function testParseAndDump()
...
+            'error' => "Une erreur s'est produite.",
+            'trialMode' => "période d'essai",
+            'double_line' => "Les utilisateurs sélectionnés n'ont pas d'email.\n",
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Tests/YamlTest.php:56]:
```suggestion
            'double_line' => "Les utilisateurs sélectionnés n'ont pas d'email. ",
```

File: src/Symfony/Component/Yaml/Parser.php [hunk 10]
```diff
@@ -993,6 +1007,44 @@ private function isCurrentLineLastLineInDocument(): bool
...
+            if ("'" === $char) {
+                ++$quoteCount;
+            } elseif (':' === $char && 0 === $quoteCount % 2 && ($i === $trimmedLineLength - 1 || ' ' === $trimmedLine[$i + 1])) {
+                // key and value are separated by the first colon after the (quoted) key followed by a space or linebreak
+                $value = trim(substr($trimmedLine, ++$i), ' ');
+                break;
+            }
+        }
+
+        if (!str_starts_with($value, "'")) {
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Parser.php]:
```suggestion
        if (0 !== strpos($value, "'")) {
```

File: src/Symfony/Component/Yaml/Parser.php [hunk 11]
```diff
@@ -656,6 +660,16 @@ private function getNextEmbedBlock(int $indentation = null, bool $inSequence = f
             if ($this->isCurrentLineBlank()) {
                 $data[] = substr($this->currentLine, $newIndent);
                 continue;
+            } elseif (!$isInMultiLineQuote && $this->isCurrentLineMultiLineQuoteStart()) {
+                $isInMultiLineQuote = true;
+                $data[] = substr($this->currentLine, $newIndent);
+                continue;
+            } elseif ($isInMultiLineQuote) {
+                $data[] = $this->currentLine;
+                if (str_ends_with(rtrim($this->currentLine, ' '), "'")) {
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Parser.php]:
```suggestion
                if ("'" === (rtrim($this->currentLine)[-1] ?? '')) {
```

**Review by xabbuh — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Yaml/Tests/YamlTest.php (hunk 7 above)
Comment (maxbeckers) [reply src/Symfony/Component/Yaml/Tests/YamlTest.php:52]: Is this the behavior you expect @xabbuh? Currently with this input we get this result without your suggestion.

Comment (xabbuh) [reply src/Symfony/Component/Yaml/Tests/YamlTest.php:52]: Yes, as far as I know that should be the outcome.

Comment (maxbeckers) [reply src/Symfony/Component/Yaml/Tests/YamlTest.php:52]: In the YAML spec I didn't find sth. for this case so it might be a very special case. This is the ChatGPT answer for that:
> An empty line is treated as a line break (``\n``)

This is also the way it works in different online interpreters which are supporting this (like this one: http://www.yaml-online-parser.appspot.com/.
This one also interpretes
```
baz: 'Lorem

   ipsum'
```
As ``{"baz": "Lorem\nipsum"}``.
While other interpreters like https://codebeautify.org/yaml-parser-online interpret this as ``{"baz": "Lorem ipsum"}``.

So it seems to be not really clear how to deal with this and we should decide how to deal with it. My suggestion would be "keep it simple for this very special case" and keep it how it is atm in this PR with the ``\n``.  What do you think?

**Review by fabpot — APPROVED** [review]
Merging it as a new feature

**Comment by fabpot** [comment]
Thank you @maxbeckers.

**Comment by xabbuh** [comment]
I suggest to revert this for now as the changes to the parser break existing tests in the SecurityBundle (see #53747).
