### PR TITLE
[Security] Log notice when no entry point is configured

### LINKED ISSUE #37068: [Security] New LoginFormAuthenticator fails on InsufficientAuthenticationException with missing AuthenticationEntryPoint
**Symfony version(s) affected**: 5.1

**Description**  

I've replaced my guard login authenticator with a version based on the `AbstractLoginFormAuthenticator` and enabled the AuthenticationManager. Everyhing works fine except hitting a page which requires `IS_AUTHENTICATED_REMEMBERED` without actual being logged in.

This triggers an `AccessDeniedException` which gets caught by the firewall ExceptionListener. This creates an `InsufficientAuthenticationException` and tries to  `startAuthentication()` with it. That method then throws an HttpException because there's not AuthenticationEntryPoint defined:

~~~php
        if (null === $this->authenticationEntryPoint) {
            throw new HttpException(Response::HTTP_UNAUTHORIZED, $authException->getMessage(), $authException, [], $authException->getCode());
        }
~~~

The guard system correctly uses the configured entry point to redirect to my login page.

**How to reproduce**

1. Build a login form based on the new authenticator
2. Build a page requiring a authenticated user
3. Hit the page w/o authentication

**Possible Solution**  

Define an entry point for the authenticator?

Sorry if I missed some doc. I've checked the blog post and Wouter's additional article, but couldn't find help.

Kind regards
Matthias

### PR DESCRIPTION
**Pull request by wouterj**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37068
| License       | MIT
| Doc PR        | -

In the new security system, authenticators are not necessarily authentication entry points. This can cause unexpected behavior if no entry point is configured. It's not really an error, that's why I choose the "notice" level: "Normal but significant events".

### CODE REVIEW

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
@wouterj Can you check the tests (they are broken by this change)?

File: src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php [hunk 1]
```diff
@@ -195,6 +195,10 @@ private function handleLogoutException(ExceptionEvent $event, LogoutException $e
     private function startAuthentication(Request $request, AuthenticationException $authException): Response
     {
         if (null === $this->authenticationEntryPoint) {
+            if (null !== $this->logger) {
+                $this->logger->notice(sprintf('No Authentication entry point configured, returning a %s HTTP response. Configure "entry_point" on the firewall if you want to modify the response.', Response::HTTP_UNAUTHORIZED));
```
Comment (linaori) [inline src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php:199]: From a DX perspective, it would be nice to have a firewall name here. I think this is available through `$this->providerKey`? Could be added in either the message or the context.

Comment (wouterj) [reply src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php]: Good idea, added!

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @wouterj.
