### PR TITLE
[Mailer][Postmark] Handle alternate error payload shapes for Payload Too Large

### LINKED ISSUE #60297: Undefined array key Message symfony/postmark-mailer
### Symfony version(s) affected

^7

### Description

If an email contains attachments > postmark threshold, postmark will return an error with the following payload:

```
array (
  'message' => 'Request size limit exceeded',
  'request_id' => 'xxxx',
)  
```

Status Code = 413
However according to this line here:

https://github.com/symfony/postmark-mailer/blob/d11c8ce0ff5974a2ee4a9a3297ba89ecdf6d1952/Transport/PostmarkApiTransport.php#L86

The error message is expecting the key to be Capitalized, causing the error descibed above "Undefined array key 'Message'"

### How to reproduce

Add attachments > postmark threshold to an email
Attempt to send
error, Undefined array key 'Message'

### Possible Solution

It appears the symfony mailer is expecting API Error codes and the response to always be formatted with

["ErrorCode", "Message"]

However if the response is a Http error code, the payload may not be in this format.

A suggested approach here would be to create a block just for 413 HTTP errors, and return the response based on the output above with the 'message' key

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ousamabenyounes**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60297
| License       | MIT

## Problem

`PostmarkApiTransport::doSendApi()` assumed every non-200 response would come back shaped like Postmark's standard error envelope:

```json
{ "ErrorCode": 418, "Message": "I'm a teapot" }
```

But Postmark returns a different shape when the upload exceeds the service-wide size limit (HTTP 413):

```json
{ "message": "Request size limit exceeded", "request_id": "abc-123" }
```

No `ErrorCode`, and the message key is lowercased. As a result, sending an email with oversized attachments crashed with `Undefined array key 'ErrorCode'` / `'Message'` inside the transport — hiding the real 413 error from the caller.

## Fix

Read both keys defensively with sensible fallbacks:

```php
$errorCode    = $result['ErrorCode'] ?? 0;
$errorMessage = $result['Message'] ?? $result['message'] ?? '';
```

The standard envelope is unchanged; the size-limit shape now surfaces a correct `HttpTransportException('Unable to send an email: Request size limit exceeded (code 0).')`.

## Test coverage

Added `testSendThrowsForRequestSizeLimitExceededResponse` — feeds the exact 413 payload from the issue and asserts the thrown `HttpTransportException` carries the lowercased `message`.

Existing `testSendThrowsForErrorResponse` (standard envelope, 418) still passes unchanged. Full suite: 11 tests, 28 assertions, green.

### CODE REVIEW

**Review by GromNaN — APPROVED** [review]

**Comment by MatTheCat** [comment]
This `message` key isn't documented anywhere and no API client use it. I think a better option would be to make the error message the HTTP status code's when it's not 422. That would handle every possible error in a better way than an empty string.

File: src/Symfony/Component/Mailer/Bridge/Postmark/Transport/PostmarkApiTransport.php [hunk 1]
```diff
@@ -81,14 +81,21 @@ protected function doSendApi(SentMessage $sentMessage, Email $email, Envelope $e
         }
 
         if (200 !== $statusCode) {
+            // Postmark API errors respond with {"ErrorCode": N, "Message": "..."},
+            // but some edge cases (e.g. HTTP 413 Request Size Limit) return
+            // {"message": "...", "request_id": "..."} instead — fall back to
+            // either shape so we never raise "Undefined array key" ourselves.
+            $errorCode = $result['ErrorCode'] ?? 0;
+            $errorMessage = $result['Message'] ?? $result['message'] ?? '';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mailer/Bridge/Postmark/Transport/PostmarkApiTransport.php]: Following @HypeMC's comment:
```suggestion
            $errorMessage = $result['Message'] ?? $result['message'] ?? 'HTTP '.$statusCode;
```

**Comment by ousamabenyounes** [comment]
Thanks @nicolas-grekas, applied the suggestion in `405b808` — `$errorMessage` now falls back to `'HTTP '.$statusCode` when neither `Message` nor `message` is present in the Postmark payload, instead of the previous empty string. Also dropped the now-obsolete inline comment block.

Added `testSendThrowsWithStatusCodeFallbackWhenResponseHasNoMessage` to cover the new fallback path (502 response with `request_id` only) — it asserts `"Unable to send an email: HTTP 502 (code 0)."`. The two existing error-shape tests are unaffected since they still populate the `Message` / `message` keys.

Happy to tighten anything else.

**Comment by nicolas-grekas** [comment]
Thank you @ousamabenyounes.
