### PR TITLE
[Serializer] Ignore when using #[Ignore] on a non-accessor

### LINKED ISSUE #54477: [VarExporter] Mapping Expception - Ignore can only be added on methods beginning with "get", "is", "has" or "set".`
### Symfony version(s) affected

6.4.6

### Description

After upgrading symfony/var-exporter from 6.4.4 to 6.4.6 I get an error during my serialization process.

`Ignore on "Proxies\__CG__\App\Entity\Artist::__setInitialized()" cannot be added. Ignore can only be added on methods beginning with "get", "is", "has" or "set".`

vendor/symfony/serializer/Mapping/Loader/AttributeLoader.php:172

### How to reproduce

Use Serializer and serialize some objects with relations and setting the context.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54477
| License       | MIT

Because ignore means ignore so we know what to do with the attribute even when it's on something else than an accessor.

### CODE REVIEW

**Review by jderusse — APPROVED** [review]

**Comment by xabbuh** [comment]
looks like the check was added on purpose (see #45016)

File: src/Symfony/Component/Serializer/Mapping/Loader/AnnotationLoader.php [hunk 1]
```diff
@@ -138,10 +138,6 @@ public function loadClassMetadata(ClassMetadataInterface $classMetadata)
 
                     $attributeMetadata->setSerializedName($annotation->getSerializedName());
                 } elseif ($annotation instanceof Ignore) {
-                    if (!$accessorOrMutator) {
-                        throw new MappingException(sprintf('Ignore on "%s::%s()" cannot be added. Ignore can only be added on methods beginning with "get", "is", "has" or "set".', $className, $method->name));
-                    }
-
                     $attributeMetadata->setIgnore(true);
```
Comment (xabbuh) [inline src/Symfony/Component/Serializer/Mapping/Loader/AnnotationLoader.php]: maybe silently ignoring the attribute on non-accessor and non-mutator methods can help:

```php
if ($accessorOrMutator) {
    $attributeMetadata->setIgnore(true);
}
```

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Mapping/Loader/AnnotationLoader.php]: updated to your suggestion

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Mapping/Loader/AnnotationLoader.php]: @Jeroeny could you please check if this works with #45016 in mind?

**Review by stof — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by kl3sk** [comment]
Hello,

Does this PR will be added in `7` branch too ? (`7.0.6` actually)
I have the same issue that looks to be fixed with this PR

Thanks.

**Comment by stof** [comment]
@kl3sk it will be merged up to newer branch in the next merge up.

**Comment by kl3sk** [comment]
@stof thank you, I'll wait for the next one. My app is partially broken '-_-

**Comment by stof** [comment]
@kl3sk the workaround is to downgrade symfony/var-exporter to the previous version to avoid using the broken 7.0.6 version (as that's the only version of 7.0.x containing the regression).

**Comment by kl3sk** [comment]
Ho thanks @stof , I was looking for a workaround. I manage to do it.

**Comment by ValentinRgt** [comment]
Hello,

When will this PR be merged into the SF 6.4.*, 7.0.* and 7.1.* branches?
If possible have an approximate date

**Comment by xabbuh** [comment]
It's already present in all maintained branches. Patch releases do happen once a month (so probably at the end of April or the beginning of May).

**Comment by derrabus** [comment]
Locking to prevent further "why isn't this fixed yet?!" comments.

Please wait for the next release. If you want to check if the next release will actually fix your problem, you can do so by allowing Composer to install a dev snapshot.

#### Symfony 5.4

```JSON
"symfony/serializer": "~5.4.39@dev",
```

#### Symfony 6.4

```JSON
"symfony/serializer": "~6.4.7@dev",
```

#### Symfony 7.0

```JSON
"symfony/serializer": "~7.0.7@dev",
```
