### PR TITLE
[Console] allow cursor to be used even when STDIN is not defined

### LINKED ISSUE #37124: "Use of undefined constant STDIN - assumed 'STDIN'"
**Symfony version(s) affected**: `symfony/console v5.1.0`

**Description**  
I'm keep getting his error on Laravel, I don't know if this should be reported to them or if this is a Symfony issue?

**How to reproduce**  
Update to latest deps.

**Possible Solution**  
I don't think the constant exists when using it as a dep, shouldn't it be checked if it is?

**Additional context**  
Converting the constant works fine, but I don't think this is the solution:
```
public function __construct(OutputInterface $output, $input = 'STDIN')
    {
        $this->output = $output;
        $this->input = $input;
    }
```

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37124
| License       | MIT
| Doc PR        | 

This allows to use the `Cursor` class introduced in Symfony 5.1 even when the `STDIN` constant is not defined. We did a similar bugfix in the past in the `QuestionHelper` class in #10798.

### CODE REVIEW

File: src/Symfony/Component/Console/Cursor.php [hunk 1]
```diff
@@ -21,8 +21,16 @@ final class Cursor
     private $output;
     private $input;
 
-    public function __construct(OutputInterface $output, $input = STDIN)
+    public function __construct(OutputInterface $output, $input = null)
     {
+        if (null === $input && !\defined('STDIN')) {
+            throw new \TypeError(sprintf('The second argument of "%s()" must be a resource.', __METHOD__));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Cursor.php:27]: instead of the exception, what about this?:
`$input = $input ?? (\defined('STDIN') ? STDIN : fopen('php://input', 'r'));`

Comment (xabbuh) [reply src/Symfony/Component/Console/Cursor.php:27]: I thought about that to, but I wasn't sure if using `php://input` will always work or whether throwing would be more useful. What do you think?

Comment (nicolas-grekas) [reply src/Symfony/Component/Console/Cursor.php:27]: AFAIK, `php://input` always works.

Comment (xabbuh) [reply src/Symfony/Component/Console/Cursor.php]: let's use your suggestion then

**Review by nicolas-grekas — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.
