### PR TITLE
[SecurityBundle] Do not replace authenticators service by their traceable version

### LINKED ISSUE #59071: [Security] Cannot have a custom authenticator which implements `EventSubscriberInterface`
### Symfony version(s) affected

7.2.0

### Description

Hi,

When I try to update from Symfony `7.1` to `7.2`. I have an error on cache clear:
```
$ bin/console cache:clear

In RegisterListenersPass.php line 129:
                                                                                                                                             
  Service "debug.App\Security\MyCustomAuthenticator" must implement interface "Symfony\Component\EventDispatcher\EventSubscriberInterface".  
```

It seems to be related to:
- https://github.com/symfony/symfony/pull/57369

When I add this code on `vendor/symfony/security-bundle/DependencyInjection/SecurityExtension.php` line 646:
```php
        if ($container->hasDefinition('debug.security.firewall')) {
            foreach ($authenticationProviders as $authenticatorId) {
                if ($authenticatorId === MyCustomAuthenticator::class) {
                    continue;
                }

                $container->register('debug.'.$authenticatorId, TraceableAuthenticator::class)
                    ->setDecoratedService($authenticatorId)
                    ->setArguments([new Reference('debug.'.$authenticatorId.'.inner')])
                ;
            }
        }
```

It works.

Is it an issue? Why I can't implement `EventSubscriberInterface` anymore?

Thanks,

Mickaël

### How to reproduce

I created a repository: https://github.com/misaert/test-custom-authenticator/commits/main/.

The last commit is with Symfony `7.2`. Before this, we can launch `bin/console cache:clear` but with this commit, we have this error:
```
$ bin/console cache:clear

In RegisterListenersPass.php line 129:
                                                                                                                                             
  Service "debug.App\Security\MyCustomAuthenticator" must implement interface "Symfony\Component\EventDispatcher\EventSubscriberInterface".  
                                                                                                                                             
```

### Possible Solution

_No response_

### Additional Context

_No response_

### LINKED ISSUE #59091: [Security] Cannot autowire custom LoginFormAuthenticator in a controller action
### Symfony version(s) affected

7.2

### Description

This may be related to #59071.

I have a custom authenticator extending the builtin `AbstractLoginFormAuthenticator`. I autowire it into the register action of my `SecurityController`, so I can authenticate newly registered users, so they can continue the process they are currently in without the need to verify their data at this point:

```php
class SecurityController extends AbstractController {
    # ...
  
    public function register(
        App\Security\LoginFormAuthenticator $customAuthenticator,
        # ...
    ) {
        # ...
    }
```

After upgrading to `7.2`, this throws an exception:

```
App\Controller\SecurityController::register(): Argument #3 ($customAuthenticator) must be of type App\Security\LoginFormAuthenticator, Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticator given
```

A quick debug of the service shows, that the `dev` environment seems to wrap it automatically into the `TracableAuthenticator` class:

```
> symfony console debug:container App\Security\LoginFormAuthenticator


// This service is a private alias for the service debug.App\Security\LoginFormAuthenticator                           

Information for Service "debug.App\Security\LoginFormAuthenticator"
===================================================================

 Collects info about an authenticator for debugging purposes.

 ---------------- ----------------------------------------------------------------------------------------------------------------------- 
  Option           Value                                                                                                                  
 ---------------- ----------------------------------------------------------------------------------------------------------------------- 
  Service ID       debug.App\Security\LoginFormAuthenticator                                                                              
  Class            Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticator                                             
  Tags             container.decorator (id: App\Security\LoginFormAuthenticator, inner: debug.App\Security\LoginFormAuthenticator.inner)  
  Public           no                                                                                                                     
  Synthetic        no                                                                                                                     
  Lazy             no                                                                                                                     
  Shared           yes                                                                                                                    
  Abstract         no                                                                                                                     
  Autowired        no                                                                                                                     
  Autoconfigured   no                                                                                                                     
  Usages           App\Security\LoginFormAuthenticator                                                                                    
                   security.command.debug_firewall                                                                                        
                   security.authenticator.manager.main                                                                                    
                   security.exception_listener.main                                                                                       
                   .service_locator.vgziCoP                                                                                               
                   .service_locator.j9y68NC                                                                                               
 ---------------- ----------------------------------------------------------------------------------------------------------------------- 

 ! [NOTE] The "App\Security\LoginFormAuthenticator" service or alias has been removed or inlined when the container was 
 !        compiled.          
``` 

Switching to the `prod` environment seems to "fix" the problem.

### How to reproduce

Create a new class `App\Security\LoginFormAuthenticator` extending `Symfony\Component\Security\Http\Authenticator\AbstractLoginFormAuthenticator`. Define the abstract methods and configure it in your configurations:

```yaml
# config/packages/security.yaml

security:
    firewalls:
        main:
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
```

Now, create a new class `App\Controller\SecurityController` with an method `register` and try to autowire the newly created authenticator via a method parameter:

```php
class SecurityController extends AbstractController
{
    #[Route(path: '/register')]
    public function register(
        App\Security\LoginFormAuthenticator $customAuthenticator,
    ): Response {
        # ...
    }
}
```

Accessing the route (`https://127.0.0.1:8000/register`) throws the described exception.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59071, fix #59091
| License       | MIT

### CODE REVIEW

**Review by chalasr — APPROVED** [review]
Unfortunate but 👍 Thanks. Hope you checked everything keeps working as expected in the profiler 😇

**Comment by MatTheCat** [comment]
Hm there shouldn’t be anything unfortunate here; did I miss something? :sweat_smile: 

The `AuthenticatorManager` will still receive `TraceableAuthenticator`s, the only difference is that the original authenticators will still exist in the container.

**Comment by chalasr** [comment]
Just the fact we cannot stick with regular service decoration.

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 1]
```diff
@@ -643,11 +643,13 @@ private function createAuthenticationListeners(ContainerBuilder $container, stri
...
-                    ->setDecoratedService($authenticatorId)
-                    ->setArguments([new Reference('debug.'.$authenticatorId.'.inner')])
+            foreach ($authenticationProviders as &$authenticatorId) {
+                $traceableId = 'debug.'.$authenticatorId;
+                $container
+                    ->register($traceableId, TraceableAuthenticator::class)
+                    ->setArguments([new Reference($authenticatorId)])
                 ;
+                $authenticatorId = $traceableId;
             }
```
Comment (fabpot) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:653]: Is you code different from this simpler one (at least, your new test pass with my code as well)?

```suggestion
            foreach ($authenticationProviders as $authenticatorId) {
                $container
                    ->register('debug.'.$authenticatorId, TraceableAuthenticator::class)
                    ->setArguments([new Reference($authenticatorId)])
                ;
            }
```

Comment (MatTheCat) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:653]: Yes: `$authenticationProviders`’ IDs wouldn’t be replaced by traceable ones in that case.

Comment (chalasr) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:653]: Could you add an additional assertion that would fail with the suggested code? I guess something ensuring that the traceable service gets injected where it belongs

Comment (MatTheCat) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:653]: I’m not sure it is possible: to make security-http 7.2 work with security-bundle < 7.2 the `TraceableAuthenticatorManagerListener` still must be able to decorate authenticators itself :thinking:

Comment (MatTheCat) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:653]: Okay I thought this would fail with high or low-deps tests but it seems I’m still not grasping those :sweat_smile: 

Test case was refactored in https://github.com/symfony/symfony/pull/59278/commits/111913ed1507e89e6098f6bf82016570cdc5601a.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @MatTheCat.
