### PR TITLE
[Workflow] Mark registry as internal and deprecate the service

### LINKED ISSUE #45315: [Workflow] Allow fetching workflow (definition) by name from registry
### Description

The workflows are now private in the container, which means it's deprecated to perform `$container->get("<workflow>")`. To counter this the Registry allows retrieving a workflow based on an object you wish to manipulate. However, this is problematic in case you want to inspect a workflow without having an object to manipulate.

#31506 somewhat hinted at this by requesting fetching workflows by class names. Instead I want to be able to get the definition of a workflow by its name.

The `WorkflowDumpCommand` in `symfony/framework-bundle` is an example use-case. Though it implements a lot of code to provide all the workflows as `array $workflows` to the command. For alternative dumper implementations replicating the logic to create that argument isn't feasible and it'd be great if we could do `Registry::getByName` or even just `Registry::all()` without subject.

My use case is a documentation controller that dumps the definition similar to `WorkflowDumpCommand` and renders it in a Twig template using JavaScript. This allows visualising the various workflows on the platform which also makes it visible to users who may not have the Symfony site installed locally, or know how to use another visualisation tool. 

The controller uses the name as path argument to load the workflow. A potential workaround for my use-case would be to manually inject every defined workflow, but this requires updating the controller every time a new workflow is defined or a workflow is removed. Additionally this does not allow creating an overview of all available workflows on a page automatically.

### Example

```php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Workflow\Registry;

class DocumentationController extends AbstractController {

  /**
   * Visualise a workflow using vis.js.
   *
   * Documentation about vis.js can be found at:
   * https://visjs.github.io/vis-network/docs/network/
   *
   * Check the corresponding template for the options that are in use.
   *
   * @Route("/docs/workflows/{workflow}/visualise", name="documentation_workflow_visualise", methods={"GET"})
   *
   * @param string $workflow
   *   The name of the workflow to visualise in hyphenated-form.
   */
  public function visualiseWorkflowAction(string $workflow, Registry $registry): Response
  {
    // We use hyphens for our URL and templates but underscores for the workflow
    // machine names.
    $workflow = str_replace('-', '_', $workflow);

    if (!$registry->has($workflow))
    {
      throw new NotFoundHttpException(sprintf('Workflow "%1$s" does not exist.".', $workflow));
    }

    $workflow = $registry->getByName($workflow);

    $options = [
      'nodes' => [
        // Our places are boxes by default.
        'shape' => 'box',
      ],
      'edges' => [
        // Our workflows are directional so we show arrows to indicate where
        // they're going.
        'arrows' => 'to',
        'color' => [
          // The color of the transition matches where we're going to. This
          // ensures transitions to errors have the error color.
          'inherit' => 'to',
        ],
      ],
    ];

    $definition = $workflow->getDefinition();
    $nodes = [];
    foreach ($definition->getPlaces() as $place)
    {
      $node = ['id' => $place, 'label' => $place];
      // Make the initial place stand out.
      if (in_array($place, $definition->getInitialPlaces(), TRUE))
      {
        $node['shape'] = 'circle';
      }

      // Differentiate error states.
      if (substr($place, 0, 6) === 'error_')
      {
        $node['color'] = '#ffb5a7';
      }

      $nodes[] = $node;
    }

    $edges = [];
    foreach ($definition->getTransitions() as $transition)
    {
      // A transition may specify multiple origins and destinations which means
      // We need to plot all of them.
      foreach ($transition->getFroms() as $from)
      {
        foreach ($transition->getTos() as $to)
        {
          $edges[] = ['label' => $transition->getName(), 'from' => $from, 'to' => $to];
        }
      }
    }

    return $this->render(
      'documentation/workflows/visualise.html.twig',
      [
        'workflow_slug' => str_replace('_', '-', $workflow->getName()),
        'workflow_label' => ucwords(str_replace('_', ' ', $workflow->getName())),
        'nodes' => $nodes,
        'edges' => $edges,
        'options' => $options,
      ]
    );
  }
}
```

The following (shortened) template is used for visualisation.

```twig

{% block main %}
  <h1>Visualise</h1>

  <div id="visualisation-container">
    <div id="visualisation"></div>
  </div>
{% endblock %}

{% block stylesheets %}
  {{ parent() }}
  <style type="text/css">
    #main {
      display: flex;
      flex-direction: column;
    }

    #main h1 {
      flex: 0 0 auto;
    }

    #visualisation-container {
      flex: auto;
      position: relative;
    }

    {#
      The vis.js library doesn't handle dynamic full-height well so we require
      a bit of a trick to make it take up all space on the page.
    #}
    #visualisation {
      position: absolute;
      inset: 0;
    }
  </style>

{% endblock %}

{% block javascripts %}
  {{ parent() }}
  <script type="text/javascript" src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"></script>
  <script type="text/javascript">
    // For documentation check: https://visjs.github.io/vis-network/docs/network/
    const container = document.getElementById('visualisation');

    const nodes = new vis.DataSet({{ nodes|json_encode|raw }});
    const edges = new vis.DataSet({{ edges|json_encode|raw }});

    const data = {
      nodes: nodes,
      edges: edges
    };

    const options = {{ options|json_encode|raw }};
    const network = new vis.Network(container, data, options);
  </script>
{% endblock %}
```

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | yes
| Tickets       | Fix #45315
| License       | MIT
| Doc PR        | 

---

The Registry was added to be able to get a workflow easily from twig templates
without having to specify the workflow name.

Unfortunately, many people thought this was the only way to get a workflow and
we even add some flexibility to retrieve the workflow from the registry.

I think it's a bad idea to inject the registry, it has the same default as
injecting the Container: It's a black box, does not respect SOLID principle and
the demeter law, and make testing harder.

So I decided to mark the registry as internal. Instead people have to inject the
"right" workflow where they need it.

It can be legit to need all workflows, for documentation or for testing.
So, all workflow services are tagged and can be injected with the
following YAML syntax:

```yaml
!tagged_locator  { tag: workflow, index_by: name }
```

or PHP syntax:

```php
tagged_locator('workflow', 'name')
```

Also, two others tags exists for each workflow types
* `workflow.workflow`
* `workflow.state_machine`

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -1017,8 +1016,9 @@ private function registerWorkflowConfiguration(array $config, ContainerBuilder $
             }
         }
 
-        $commandDumpDefinition = $container->getDefinition('console.command.workflow_dump');
-        $commandDumpDefinition->setArgument(0, $workflows);
+        $workflowLocator = (string) ServiceLocatorTagPass::register($container, $workflowLocator);
+        $container->setAlias('workflows', $workflowLocator);
+        $container->registerAliasForArgument($workflowLocator, ServiceLocator::class, 'workflows');
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: what about `Psr\Container\ContainerInterface instead`? is there any reason to force `ServiceLocator`?

but more importantly: what about removing this alias altogether and let ppl use `tagged_locator('workflow')` after tagging all workflows with ... `workflow`?

**Review by nicolas-grekas — COMMENTED** [review]
Makes sense to me.
we should also deprecate the corresponding autowiring alias:
src/Symfony/Bundle/FrameworkBundle/Resources/config/workflow.php:        ->alias(Registry::class, 'workflow.registry')

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 1 above)
Comment (lyrixx) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: I chose a `ServiceLocator` because it is what it really is.

More over, on the `ContainerInterface`, we miss the method to get all Workflow (needed in the Command). And people might need it too.

---

> tagged_locator('workflow')

I **really love** this feature, but it it not so well know. I fear people will miss this part. The discoverability is a bit worst: You need to know all workflows are tagged with `workflow` + how `tagger_locator` works. But it's kind of better indeed, since we don't need to add a new hardcoded id in the container. and we could even have 3 tags `workflows` (all) `workflow.workflow` (just type=workflow) `workflows.state_machine` (type=state_machine)


What do you think?

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Good idea, let's do it. I very much prefer this over a named autowiring alias in this case. Let's document this properly and ppl will discover it.

File: src/Symfony/Bundle/FrameworkBundle/Command/WorkflowDumpCommand.php [hunk 2]
```diff
@@ -40,19 +42,28 @@ class WorkflowDumpCommand extends Command
...
-    public function __construct(array $workflows)
+    public function __construct($workflows)
     {
         parent::__construct();
 
-        $this->workflows = $workflows;
+        if (is_array($workflows)) {
+            $this->definitions = $workflows;
+            trigger_deprecation('symfony/framework-bundle', '6.2', 'Passing an array of definitions in "%s()" is deprecated. Inject a ServiceLocator filled with all workflows instead.', __METHOD__);
+        } elseif ($workflows instanceof ServiceLocator) {
```
Comment (94noni) [inline src/Symfony/Bundle/FrameworkBundle/Command/WorkflowDumpCommand.php]: why not this as first if, as it will be the "new code"

**Comment by fabpot** [comment]
@lyrixx Do you have time to finish this one?

**Comment by lyrixx** [comment]
Yes, I'll do that ASAP, But I'm on holidays for 2 weeks. I'll do that after!

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 1 above)
Comment (lyrixx) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Done 👍🏼

File: src/Symfony/Bundle/FrameworkBundle/Command/WorkflowDumpCommand.php (hunk 2 above)
Comment (lyrixx) [reply src/Symfony/Bundle/FrameworkBundle/Command/WorkflowDumpCommand.php]: Fixed

**Comment by lyrixx** [comment]
Hello,

I pushed a new version without the service locator. I also updated the PR description with the new usage

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Comment by tacman** [comment]
I'm in the category of programmers that injected the workflow registry in order to get a list of workflows in a helper bundle for workflow.

```php
// now deprecated, following https://symfony.com/doc/current/workflow.html#accessing-the-workflow-in-a-class

class WorkflowHelperService
{
    public function __construct(
        private Registry $workflowRegistry,

// in loadExtension of the bundle:
        $builder->autowire( WorkflowHelperService::class)
            ->setArgument('$workflowRegistry', new Reference('workflow.registry'));
       
      
```

```php

// better way
class WorkflowHelperService
{
    public function __construct(
        private ServiceLocator $locator,

// loadExtension()

        $builder->autowire( WorkflowHelperService::class)
            ->setArgument('$locator', tagged_locator(tag: 'workflow', indexAttribute: 'name' ))
            ->setAutoconfigured(true)
        ;

```

Using this, I'm not getting any services in the locator, $this->locator->count() is zero.

I imagine I'm not using tagger_locator correctly, or I'm doing this in the wrong spot (I'm doing this in loadExtension of my bundle, perhaps it needs to be done in the compiler pass?  If so, could you point me in the right direction on how to do that, I still find the bundle interactions a bit intimidating.

**Comment by tacman** [comment]
Also, is this the right spot for that question?  The issue itself is closed, should I open a new one?

**Comment by stof** [comment]
You should open a new discussion
