### PR TITLE
[Config] fix perf of glob discovery when GLOB_BRACE is not available

### LINKED ISSUE #35009: [performance] Symfony Kernel::boot() in dev mode on Alpine
This is a follow-up of [this discussion](https://github.com/symfony/recipes/pull/705#discussion_r358711700).

Alpine is the default docker linux base distribution. It's widely used. It's based on musl libc, and so, it's quite different of traditional linux distribution as Debian. One the difference is that glob does not handle `GLOB_BRACE`.

I knew about it from [an old issue on composer](https://github.com/composer/composer/pull/7444) that we already experienced. 

On a big project, we had quite castrophous boot time, and I finally checked on it. 

The first thing is that `Iterator/SortableIterator.php/44-46` cost an enormous amout of time and is called 22k time.

Searching why, It seems that we never enter is the optimized path here https://github.com/symfony/symfony/blob/8ffdef2958d4190994d7540013925b9580e03493/src/Symfony/Component/Config/Resource/GlobResource.php#L102.

I had that in `Kernel::configureContainer`:

```php
const CONFIG_EXTS = '.{php,xml,yaml,yml}';
// ... 
$loader->load($confDir . '/{packages}/*' . self::CONFIG_EXTS, 'glob'); 
$loader->load($confDir . '/{packages}/' . $this->environment . '/**/*' . self::CONFIG_EXTS, 'glob');
$loader->load($confDir . '/{services}' . self::CONFIG_EXTS, 'glob');
```

and in `services.yaml`:

```yaml
Lib\Core\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Translation,Tests,Kernel.php,PHPStan,Fixtures,Traits}'
```

As I don't have `GLOB_BRACE` and every pattern given contains a brace, it always fallback on the `symfony/finder` implementation which is wayyy slower.

By removing the `/**/*`, and only searching into `yaml` extension, I expect to be in the fast path. But the brackets on `{packages}` and `{services}` prevents it. By removing them it goes into the fast path. And gives a clear boost.

```php
$loader->load($confDir . '/packages/*' . self::CONFIG_EXTS, 'glob');

if (is_dir($confDir . '/packages/' . $this->environment)) {
	$loader->load($confDir . '/packages/' . $this->environment . '/*' . self::CONFIG_EXTS, 'glob');
}
$loader->load($confDir . '/services.yaml');
```

I didn't see any drwabacks (and I have a very extensive tests suites).

Rest the case with multiple option separated by comma in brackets, that stills cost a lot.

I'm absolutly thinks this is a serious issue, but I'm not sure of what todo with it, hance the absence of PR.

- brackets are they really necessary for packages and services? (**edit** answer: it ONLY ensure that the file / dir is optional. On an app that is older than one day, I'm sure of the structure that I use, and it should be totally recommended in perf reco to update that Kernel stuff to be exact and don't let it guess.)
- should we purpose a better implementation on that hot path than the `symfony/finder` one. @nicolas-grekas purpose to "we could have some logic that splits a single glob-with-braces into several of them" https://github.com/symfony/recipes/pull/705#discussion_r358748699

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35009
| License       | MIT
| Doc PR        | -

This PR implements a fast fallback implementation of GLOB_BRACE for musl-based libc, as found on Alpine. It is *not* a feature-complete fallback implementation. Implementing one would be [much more involving](https://github.com/zendframework/zend-stdlib/blob/master/src/Glob.php). But the provided implementation is good enough in practice IMHO, and the slow path is still used when not-covered glob patterns are used.

Here is the comparison:
image

image

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Here is the comparison:
image

image

File: src/Symfony/Component/Config/Tests/Resource/GlobResourceTest.php [hunk 1]
```diff
@@ -165,4 +165,21 @@ public function testIsFreshRecursiveDetectsNewFile()
...
+    {
+        $dir = \dirname(__DIR__).\DIRECTORY_SEPARATOR.'Fixtures';
+        $resource = new GlobResource($dir, '/*{/*/*.txt,.xml}', true);
+
+        $p = new \ReflectionProperty($resource, 'globBrace');
+        $p->setAccessible(true);
+        $p->setValue($resource, 0);
+
+        $expected = [
+            $dir.'/Exclude/ExcludeToo/AnotheExcludedFile.txt',
```
Comment (OskarStark) [inline src/Symfony/Component/Config/Tests/Resource/GlobResourceTest.php]: Typo in AnotheR

Comment (nicolas-grekas) [reply src/Symfony/Component/Config/Tests/Resource/GlobResourceTest.php]: Haha that's the name of the file, so be it :)

**Comment by stof** [comment]
I think we need more tests covering the fallback usage, especially given we don't run our testsuite on Alpine

**Comment by nicolas-grekas** [comment]
@stof can you please hint me about which kind of tests are missing to you?

**Comment by stof** [comment]
Well, exercising it with a bunch of different globs, including cases which are unsupported by the fallback, to be sure they get properly detected as needing Finder rather than trying to be handled by the fallback implementation.

I was hoping that we could get inspiration from the test cases of the zend-stdlib implementation, but they seem to test only 1 case in their provider.

**Comment by nicolas-grekas** [comment]
> including cases which are unsupported by the fallback

I've made the fallback support nested braces instead:)

**Comment by stof** [comment]
> I've made the fallback support nested braces instead :)

you still don't have tests which include nested braces actually needing expansion.

and you are also missing tests covering what happens when feeding it with invalid braces for the glob.

**Comment by nicolas-grekas** [comment]
Here you are.

File: src/Symfony/Component/Config/Tests/Resource/GlobResourceTest.php [hunk 2]
```diff
@@ -165,4 +165,33 @@ public function testIsFreshRecursiveDetectsNewFile()
...
+    public function testUnbalancedBraceFallback()
+    {
+        $dir = \dirname(__DIR__).\DIRECTORY_SEPARATOR.'Fixtures';
+        $resource = new GlobResource($dir, '/*{/*/*.txt,.x{m,nl}', true);
+
+        $p = new \ReflectionProperty($resource, 'globBrace');
+        $p->setAccessible(true);
+        $p->setValue($resource, 0);
+
+        $this->assertSame([], array_keys(iterator_to_array($resource)));
```
Comment (stof) [inline src/Symfony/Component/Config/Tests/Resource/GlobResourceTest.php]: is this actually what happens with `glob`, or does it report an error ?

Comment (nicolas-grekas) [reply src/Symfony/Component/Config/Tests/Resource/GlobResourceTest.php]: no error, just no matches
