### PR TITLE
[Form] Add support for submitting forms with unchecked checkboxes in request handlers

### LINKED ISSUE #20179: Cannot uncheck checkbox field mapped to the entity
I'm having issues submitting a form which contains checkbox field. When the mapped field in the entity is true, checkbox is checked and I want to uncheck it and submit the form it won't pass through form validation. I found some issues mentioned this and Im aware of if checkbox is unchecked, its value isn't present in the POST request, so it should be interpreted as null. I have other checkboxes in other forms on my site, but all of the others works. So I was thinking and realized that the form witch doesn't work contains only the checkbox field and nothing else:

``` php
<?php

namespace SomeCompany\SomeBundle\Form\Type\Person\Author;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AlertWhenWrittenType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('checkbox', CheckboxType::class, [
            'required' => false,
        ]);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(['csrf_protection' => false]);
    }
}
```

So I tried to add another field (hidden, not mapped and with empty_data set to true) just to see what happens:

``` php
<?php

namespace SomeCompany\SomeBundle\Form\Type\Person\Author;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AlertWhenWrittenType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('checkbox', CheckboxType::class, [
            'required' => false,
        ]);

        // if there is only a checkbox field in the form,
        // it can't be unchecked, if you uncheck it and submit the form
        // form validation won't pass
        // magically, if I add any another field,
        // you will be able to uncheck the checkbox and validation will pass
        // this is needed until it is fixed in symfony core
        $builder->add('uglyHack', HiddenType::class, [
            'required' => false,
            'mapped' => false,
            'empty_data' => true,
        ]);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(['csrf_protection' => false]);
    }
}
```

also needed to add that field to my twig template

``` twig
{{ form_widget(form.checkbox) }}
{{ form_widget(form.uglyHack) }}
```

and now, miraculously, Im able to uncheck the checkbox and submit the form. Validation now passes and entity field value is now set to false.
I think that its happening because there is only the checkbox field in the form. If checkbox is not checked, its value is not send through POST, but there are no other fields so $_POST is empty
and I think that might cause the problem to appear. Maybe empty $_POST is handled wrong?

I'm using symfony 3.0.9

### PR DESCRIPTION
**Pull request by filiplikavcan**
| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | yes
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #20179, #14938
| License       | MIT

When a form contains only checkboxes (or a collection of checkboxes), there is no way to distinguish between:

- A user visiting a page that contains the form (not a submission)
- A user submitting the form with all checkboxes unchecked

This is because unchecked checkboxes are omitted entirely from the HTTP request. When the form's name is absent from the request, the current handlers bail out early and don't submit the form - so unchecked checkboxes can never reset a true default value.

This PR introduces `MissingDataHandler`, which walks the form's children recursively at request-handling time to detect whether the form would have appeared in the request had any checkbox been checked. Concretely:

- If a form (or any of its children) has a `false_values` option (the marker used by `CheckboxType`), it means the form contains a checkbox. When that checkbox key is absent from the submitted data, `MissingDataHandler` injects the first false value (i.e. `'0'` for a standard checkbox) so the form is submitted and data is set to `false`.
- An `stdClass` sentinel object is used to distinguish "key was absent" from `null`, making the logic explicit and identity-safe.
- `PATCH` requests are excluded intentionally, since PATCH is meant for partial updates and omitted fields should be left untouched.

Before/after

```php
// Form with a single checkbox, default data = true
$form = $factory->createNamed('agree', CheckboxType::class, true);

// POST request with no body (all checkboxes unchecked)
$handler->handleRequest($form, $request);

// Before: form is never submitted, data stays true
// After:  form is submitted, data is false ✓
```

### CODE REVIEW

**Comment by SHTIKOV** [comment]
Sorry to be off topic, but where is Fabien?) I would like to get approval in my MR)
[#44787](https://github.com/symfony/symfony/pull/44787)

**Comment by nicolas-grekas** [comment]
@SHTIKOV please don't spam PRs with unrelated comments!

**Review by nicolas-grekas — COMMENTED** [review]
Sorry for the delay reviewing this, it's definitely interesting!

I force-pushed on your fork to turn the trait into a class. Please fetch + reset --hard before reopening the branch. There are some tests failing that need to be addressed.

I'm just wondering if this shouldn't go on 6.2: yes, this can be seen as a bug fix, but it's also a new behavior to me.

/cc @symfony/mergers WDYT?

**Comment by yceruto** [comment]
Agree for 6.2

**Comment by filiplikavcan** [comment]
Tests for php >=8.1 are all green.

**Comment by nicolas-grekas** [comment]
Great thanks. OK to rebase+retarget for 6.2?

**Comment by filiplikavcan** [comment]
Yes.

**Review by nicolas-grekas — DISMISSED** [review]
LGTM thanks!

**Comment by xabbuh** [comment]
the test failures look related

**Comment by filiplikavcan** [comment]
Hm, I'm still not sure how to fix this. The problem is caused by this line in MissingDataHandler:

```php
if ($form->getConfig()->getType() instanceof ResolvedFormTypeInterface && $form->getConfig()->getType()->getInnerType() instanceof CheckboxType) {
```

I have taken it for granted that the type is always resolved at the time the request is handled. It seems that either something has changed and there is now a valid case where a form configuration may not have a resolved type OR the way tests (builder/forms) are initialized has changed and the type is not properly resolved.

File: .gitignore [hunk 1]
```diff
@@ -8,3 +8,4 @@ composer.phar
 package.tar
 /packages.json
 /.phpunit
+
```
Comment (xabbuh) [inline .gitignore]: should be reverted

File: src/Symfony/Component/Form/MissingDataHandler.php [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+
+                if ($data === $this->missingData) {
+                    return $falseValues[0];
+                }
+
+                if (\in_array($data, $falseValues)) {
+                    return $data;
+                }
+            }
+        } catch (\Error $error) {
```
Comment (xabbuh) [inline src/Symfony/Component/Form/MissingDataHandler.php]: Catching type errors here doesn't look like the right solution to me. We should investigate instead why the `$type` property in `FormConfigBuilder` isn't initialized at this point and fix that root issue instead.

Comment (filiplikavcan) [reply src/Symfony/Component/Form/MissingDataHandler.php]: I don't like it either. 

Another solution could be to make FormConfigBuilderInterface::getType() nullable. Then null state would have to be handled in these methods where getType() is called:

ValidatorDataCollector#getCasters
FormDataExtractor#extractConfiguration
FormDataCollector#getCasters
FormTypeCsrfExtension#finishView
FormTypeCsrfExtension#buildForm
BaseType#buildView
Button#createView

I don't know if null/undefined type is a valid case or not.

File: .gitignore (hunk 1 above)
Comment (filiplikavcan) [reply .gitignore]: Reverted.

File: src/Symfony/Component/Form/MissingDataHandler.php (hunk 2 above)
Comment (xabbuh) [reply src/Symfony/Component/Form/MissingDataHandler.php]: I can look into why we run into this error here. But that will probably not happen before the weekend.

Comment (filiplikavcan) [reply src/Symfony/Component/Form/MissingDataHandler.php]: Thank you. When I created this PR on Jan 19 it worked. These commits look related: https://github.com/symfony/symfony/commit/a53b450d https://github.com/symfony/symfony/commit/488a262a

**Comment by nicolas-grekas** [comment]
Status: needs work

**Comment by nicolas-grekas** [comment]
Can you please rebase @filiplikavcan?

File: src/Symfony/Component/Form/Tests/AbstractRequestHandlerTest.php [hunk 3]
```diff
@@ -65,6 +68,93 @@ public function getNormalizedIniPostMaxSize(): string
...
+     */
+    public function testSubmitCheckboxInCollectionFormWithEmptyData($method)
+    {
+        $form = $this->factory->create(CollectionType::class, [true, false, true], [
+            'entry_type' => CheckboxType::class,
+            'method' => $method,
+        ]);
+
+        $this->setRequestData($method, [
+        ]);
```
Comment (OskarStark) [inline src/Symfony/Component/Form/Tests/AbstractRequestHandlerTest.php]: can be on one line

**Comment by mpdude** [comment]
A form that consists of unchecked checkboxes only will not be recognized as being submitted with the standard `$form->handleRequest(...); if ($form->isSubmitted() ...) { ... }` pattern. Does this PR intend to address this, or does it cover other edge cases I am not aware of?

If yes, you might want to mention #20210 in the list of tickets as well.

Update: I have been looking at this code for over 10 minutes now and I am unable to figure out how it would be able to tell whether we're `GET`-requesting a page that contains a checkbox-only form, or if this form has been submitted with `method="GET"` and no checkbox was checked.

File: src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php [hunk 4]
```diff
@@ -57,13 +60,13 @@ public function handleRequest(FormInterface $form, mixed $request = null)
             if ('' === $name) {
                 $data = $request->query->all();
             } else {
-                // Don't submit GET requests if the form's name does not exist
-                // in the request
-                if (!$request->query->has($name)) {
+                $missingData = $this->missingDataHandler->missingData;
+
+                if ($missingData === $data = $this->missingDataHandler->handle($form, $request->query->all()[$name] ?? $missingData)) {
```
Comment (mpdude) [inline src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php]: I cannot follow this code and would love if we could break this down into smaller chunks, maybe using expressive variable names.

File: src/Symfony/Component/Form/Tests/AbstractRequestHandlerTest.php (hunk 3 above)
Comment (filiplikavcan) [reply src/Symfony/Component/Form/Tests/AbstractRequestHandlerTest.php]: Done

File: src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php (hunk 4 above)
Comment (filiplikavcan) [reply src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php]: Done. Is it easier to follow?

https://github.com/symfony/symfony/blob/4dcd5a4c2badb1a6597d4e90eebe38779273d6a7/src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php#L60-L69

**Comment by filiplikavcan** [comment]
> Update: I have been looking at this code for over 10 minutes now and I am unable to figure out how it would be able to tell whether we're `GET`-requesting a page that contains a checkbox-only form, or if this form has been submitted with `method="GET"` and no checkbox was checked.

I think it would not be possible to tell the two situations apart. Look at this test: https://github.com/symfony/symfony/blob/4dcd5a4c2badb1a6597d4e90eebe38779273d6a7/src/Symfony/Component/Form/Tests/AbstractRequestHandlerTest.php#L134-L145

**Comment by filiplikavcan** [comment]
I tweaked the code a bit and rebased to 8.1. Is this PR still potentially mergeable?

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @filiplikavcan.
