### PR TITLE
[RateLimiter][Security] Improve performance of login/request rate limiter

### LINKED ISSUE #40371: [RateLimiter][Security] Login rate limiting does not work for APIs/stateless firewalls
**Symfony version(s) affected**: 5.2.x

**Description**
The login rate limiting does not work for APIs/stateless firewalls as it considers every login attempt as consuming a rate limiting token, but stateless firewalls do login/authentication on every request. This essentially turns the login rate limiter into an API request rate limiter, which is not ideal.

The issue was introduced in https://github.com/symfony/symfony/pull/38308/files#diff-18e6fd84c34ab4a56b269deb50428549e18be52c7597d281752971e696f4bd4bL56-L63 by the removal of the rate limit reset() on login. However, re-introducing this is also not a great solution IMO as it leads to many writes.

**Possible Solution**

I see two possible solutions here:

- Rate limit every login attempt, then reset the limiter (or deduct one attempt at least) on successful login. This leads to writing to the rate limiter backend twice for every login, so twice per API request, which is not optimal I find.
- Check the rate limit on every login attempt, but only consume a rate limit token on authentication failure. This would mean for correctly-authenticated requests we only get one readonly call on the rate limiter backend, which seems more efficient.

### PR DESCRIPTION
**Pull request by Seldaek**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Tickets       | Fix #40371 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

The login rate limiter currently works this way:

- consume 1 token on auth start (this READ + WRITES to cache backend / rate limiter storage), if this fails we fail the request as it exceeds the rate limit
- if auth succeeded, clear the rate limit (this WRITES again)]
- if auth failed, nothing further happens as we already consumed

So the happy path which is the most common (login succeeds) looks something like that on redis, as there are two rate limiter (global per IP and local per username+IP combo):

```
step1

1650362918.653657 [3 127.0.0.1:41584] "MGET" "lIoZODSNyI:921c2aa99364ab8bbb0e4525c4297aa71c61d2c6"
1650362918.654027 [3 127.0.0.1:41584] "MGET" "lIoZODSNyI:921c2aa99364ab8bbb0e4525c4297aa71c61d2c6"
1650362918.654294 [3 127.0.0.1:41584] "SETEX" "lIoZODSNyI:921c2aa99364ab8bbb0e4525c4297aa71c61d2c6" "119" "\x00\x00\x00\x02\x172Symfony\\Component\\RateLimiter\\Policy\\SlidingWindow\x14\x01\x11\"\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00<login_per_ip-127.0.0.1\x0cA\xd8\x97\xa2\x98\xa9\xd8\xcf"
1650362918.654651 [3 127.0.0.1:41584] "MGET" "lIoZODSNyI:d97b05c8178d81ea0e2009445cb6465d5fcffa39"
1650362918.654877 [3 127.0.0.1:41584] "MGET" "lIoZODSNyI:d97b05c8178d81ea0e2009445cb6465d5fcffa39"
1650362918.655146 [3 127.0.0.1:41584] "SETEX" "lIoZODSNyI:d97b05c8178d81ea0e2009445cb6465d5fcffa39" "119" "\x00\x00\x00\x02\x172Symfony\\Component\\RateLimiter\\Policy\\SlidingWindow\x14\x01\x11\xcc\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00<login_per_ip_username-bd9913b290c5ecb5ebc0b925f736c15043ed9f214aa0bd9d980db7b9573b1a5f49943dc9a9fcccd22c9c0a630176ba7163df6cd32073cbe495fe94f7569c307a4b187e4917613982efbbe7ad2c3df785-127.0.0.1\x0cA\xd8\x97\xa2\x98\xa9\xe7\xb4"

step 2

1650362918.691968 [3 127.0.0.1:41584] "UNLINK" "lIoZODSNyI:921c2aa99364ab8bbb0e4525c4297aa71c61d2c6"
1650362918.692171 [3 127.0.0.1:41584] "UNLINK" "lIoZODSNyI:d97b05c8178d81ea0e2009445cb6465d5fcffa39"
```

This workflow is fine for form logins, but when rate limiting an API authenticator which works with a token, you end up doing a login on every request, so in that case it's less than optimal. This PR aims to improve that by changing the workflow to the following:

- peek at token storage by consuming 0 tokens (https://github.com/symfony/symfony/commit/4c2d67087d46ccbe10ec73adcc95e2d256375ede allows doing this without writing to the cache to keep it to a simple READ from cache backend), if there are no tokens left available we fail the request as it is exceeding the rate limit
- if auth success, nothing further happens
- if auth fails, we then consume 1 token (which READ + WRITES to the cache)

Thanks to this, the happy path is much leaner on the cache backend:

```
1650374176.991495 [3 127.0.0.1:41926] "MGET" "lIoZODSNyI:921c2aa99364ab8bbb0e4525c4297aa71c61d2c6"
1650374176.991774 [3 127.0.0.1:41926] "MGET" "lIoZODSNyI:d97b05c8178d81ea0e2009445cb6465d5fcffa39"
```

And the login failed path consumes a token still of course so it looks a lot like the previous step1 but with an additional READ (that's the only trade-off this PR makes perf wise as far as I can tell).

```
1650373275.322053 [3 127.0.0.1:41906] "MGET" "lIoZODSNyI:921c2aa99364ab8bbb0e4525c4297aa71c61d2c6"
1650373275.322431 [3 127.0.0.1:41906] "MGET" "lIoZODSNyI:a4df4a2604acb8d5003ba9789f3af4727f50fee5"
1650373275.344146 [3 127.0.0.1:41906] "MGET" "lIoZODSNyI:921c2aa99364ab8bbb0e4525c4297aa71c61d2c6"
1650373275.344402 [3 127.0.0.1:41906] "MGET" "lIoZODSNyI:921c2aa99364ab8bbb0e4525c4297aa71c61d2c6"
1650373275.344666 [3 127.0.0.1:41906] "SETEX" "lIoZODSNyI:921c2aa99364ab8bbb0e4525c4297aa71c61d2c6" "62" "\x00\x00\x00\x02\x172Symfony\\Component\\RateLimiter\\Policy\\SlidingWindow\x14\x01\x11\"\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00<login_per_ip-127.0.0.1\x0cA\xd8\x97\xac\xa7l1<"
1650373275.344966 [3 127.0.0.1:41906] "MGET" "lIoZODSNyI:a4df4a2604acb8d5003ba9789f3af4727f50fee5"
1650373275.345157 [3 127.0.0.1:41906] "MGET" "lIoZODSNyI:a4df4a2604acb8d5003ba9789f3af4727f50fee5"
1650373275.345378 [3 127.0.0.1:41906] "SETEX" "lIoZODSNyI:a4df4a2604acb8d5003ba9789f3af4727f50fee5" "62" "\x00\x00\x00\x02\x172Symfony\\Component\\RateLimiter\\Policy\\SlidingWindow\x14\x01\x11\xcd\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00<login_per_ip_username-bd9913b290c5ecb5ebc0b925f736c15043ed9f214aa0bd9d980db7b9573b1a5f49943dc9a9fcccd22c9c0a630176ba7163df6cd32073cbe495fe94f7569c307a4b187e4917613982efbbe7ad2c3df785z-127.0.0.1\x0cA\xd8\x97\xac\xa7l>\xc0"
```

### CODE REVIEW

File: src/Symfony/Component/RateLimiter/Policy/TokenBucketLimiter.php [hunk 1]
```diff
@@ -92,7 +92,9 @@ public function reserve(int $tokens = 1, float $maxTime = null): Reservation
                 $reservation = new Reservation($now + $waitDuration, new RateLimit(0, \DateTimeImmutable::createFromFormat('U', floor($now + $waitDuration)), false, $this->maxBurst));
             }
 
-            $this->storage->save($bucket);
+            if (0 < $tokens) {
+                $this->storage->save($bucket);
+            }
```
Comment (Seldaek) [inline src/Symfony/Component/RateLimiter/Policy/TokenBucketLimiter.php:98]: @wouterj I'd be especially happy for your feedback here, because while I could verify my changes seem fine on the window limiters, I am not familiar enough with the TokenBucket one to say if the `$bucket->setTimer($now);` also needs to be persisted every time we do `->consume(0);` or not.

File: src/Symfony/Component/HttpFoundation/RateLimiter/AbstractRequestRateLimiter.php [hunk 2]
```diff
@@ -17,14 +17,24 @@
...
+    {
+        return $this->doConsume($request, 1);
+    }
+
+    public function peek(Request $request): RateLimit
+    {
+        return $this->doConsume($request, 0);
+    }
+
+    private function doConsume(Request $request, int $tokens)
```
Comment (wouterj) [inline src/Symfony/Component/HttpFoundation/RateLimiter/AbstractRequestRateLimiter.php]:
```suggestion
    private function doConsume(Request $request, int $tokens): RateLimit
```

**Review by wouterj — COMMENTED** [review]
Hi! I had a quick look at the changes and read the PR description. Definitely sounds like a good way forward, and without any BC break/deprecations.

However, this really is a new feature and not a bugfix. That means that unfortunately, it won't be included in 6.1 (feature freeze was a month and a few days ago).

I'll have a deeper look when the development phase of 6.2 begins (especially for the TokenBucket implementation). I need to dig into the workings of the rate limiters again, and I prefer to focus on stabilizing 6.1 for the next 4 weeks.

**Comment by Seldaek** [comment]
Alright thanks for having a look :)

**Comment by fabpot** [comment]
@wouterj Can you have a look at this one? I'd love to be able to merge it for 6.2.

**Comment by wouterj** [comment]
I've checked the changes and added a test for all policies to make sure we don't break peeking behavior.

@Seldaek I've basically reverted the changes you did in f9229e62f38e7f0d364c346dbc9ebcddc7e6e481. Do you maybe know why you made these changes? If `$availableTokens >= $consumedTokens`, this means the token can be consumed immediately without waiting. I can't follow the reasoning to add wait time in this case.

**Comment by Seldaek** [comment]
I don't recall exactly sorry, mentally quite far away from this PR at this point.. But I think your change makes sense. I will for sure check in real life conditions whenever it is merged that the original intent is still achieved.

**Comment by fabpot** [comment]
Thank you @Seldaek.
