### PR TITLE
stop using the deprecated at() PHPUnit matcher

### LINKED ISSUE #37780: PHPUnit deprecates the at() matcher for mock objects
**Symfony version(s) affected**: 3.4, 4.4, 5.1, 5.2

**Description**  
See sebastianbergmann/phpunit#4297.

The Symfony testsuite makes heavy use of the `at()` matcher to model multiple expected calls to a test double. The PHPUnit project plans to remove that functionality with PHPUnit 10.

**How to reproduce**  
Run the testsuite with PHPUnit 9.3.

**Possible Solution**  
* @greg0ire has worked on a PR for Doctrine Annotations: doctrine/annotations#345. Maybe we can apply similar changes.
* Work with the PHPUnit project on a proper replacement for that feature.
* Switch to a different mocking framework. 🙈 

**Additional context**  
When running the 3.4 testsuite with PHPUnit 9.3, about 170 deprecation warnings are logged regarding the planned removal of that functionality: https://travis-ci.org/github/symfony/symfony/jobs/716119378

Related to #37564

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37780
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by stof** [comment]
should be rebased as the first commit (taken from #37771) is now merged

File: src/Symfony/Bundle/FrameworkBundle/Tests/Controller/TemplateControllerTest.php [hunk 1]
```diff
@@ -48,10 +49,8 @@ public function testLegacyTwig()
         $twig = $this->getMockBuilder('Twig\Environment')->disableOriginalConstructor()->getMock();
         $twig->expects($this->once())->method('render')->willReturn('bar');
 
-        $container = $this->getMockBuilder('Symfony\Component\DependencyInjection\ContainerInterface')->getMock();
-        $container->expects($this->at(0))->method('has')->willReturn(false);
-        $container->expects($this->at(1))->method('has')->willReturn(true);
-        $container->expects($this->at(2))->method('get')->willReturn($twig);
+        $container = new ContainerBuilder();
```
Comment (derrabus) [inline src/Symfony/Bundle/FrameworkBundle/Tests/Controller/TemplateControllerTest.php:52]: You can use `Container` instead of `ContainerBuilder`. Btw, good catch! We shouldn't mock the container. 😃

File: src/Symfony/Bundle/FrameworkBundle/Tests/Templating/DelegatingEngineTest.php [hunk 2]
```diff
@@ -108,14 +109,10 @@ private function getFrameworkEngineMock($template, $supports)
 
     private function getContainerMock($services)
     {
-        $container = $this->getMockBuilder('Symfony\Component\DependencyInjection\ContainerInterface')->getMock();
+        $container = new ContainerBuilder();
```
Comment (derrabus) [inline src/Symfony/Bundle/FrameworkBundle/Tests/Templating/DelegatingEngineTest.php:112]: Same here.

File: src/Symfony/Component/EventDispatcher/Tests/Debug/TraceableEventDispatcherTest.php [hunk 3]
```diff
@@ -174,8 +174,12 @@ public function testLogger()
...
         $tdispatcher->addListener('foo', $listener2 = function () {});
 
-        $logger->expects($this->at(0))->method('debug')->with('Notified event "{event}" to listener "{listener}".', ['event' => 'foo', 'listener' => 'closure']);
-        $logger->expects($this->at(1))->method('debug')->with('Notified event "{event}" to listener "{listener}".', ['event' => 'foo', 'listener' => 'closure']);
+        $logger->expects($this->exactly(2))
+            ->method('debug')
+            ->withConsecutive(
+                ['Notified event "{event}" to listener "{listener}".', ['event' => 'foo', 'listener' => 'closure']],
+                ['Notified event "{event}" to listener "{listener}".', ['event' => 'foo', 'listener' => 'closure']]
+            );
```
Comment (derrabus) [inline src/Symfony/Component/EventDispatcher/Tests/Debug/TraceableEventDispatcherTest.php:182]: I wonder if we should just use `BufferingLogger` instead of mocking the logger.

**Review by ogizanagi — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.
