### PR TITLE
[DependencyInjection] Fix checking for interfaces in ContainerBuilder::getReflectionClass()

### LINKED ISSUE #58821: [DependencyInjection] ContainerBuilder::getReflectionClass() does not support interfaces, if symfony/config package not present
### Symfony version(s) affected

7.2.0

### Description

The ContainerBuilder::getReflectionClass() method does not support interfaces when 'symfony/config' package not present.

Given an interface `MyInterface`..
With symfony/config package present, `$builder->getReflectionClass(MyInterface::class)` will return a `\ReflectionClass` object for that interface.
With symfony/config package missing, `$builder->getReflectionClass(MyInterface::class)` will return `false`.

This has an impact on `AutowirePass`, if the class on a service definition is an interface.

### How to reproduce

This problem manifests in two levels.

### Low-level manifestation
```php
<?php

use Symfony\Component\DependencyInjection\ContainerBuilder;

require_once __DIR__ . '/vendor/autoload.php';

interface I {}

$rc = (new ContainerBuilder())->getReflectionClass(I::class);

// With symfony/config: ReflectionClass.
// Without symfony/config: NULL
print get_debug_type($rc) . "\n";
```

### Higher level manifestation in autowire

```php
<?php

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Definition;

require_once __DIR__ . '/vendor/autoload.php';

class Dependency {}
interface ServiceInterface {}
class Service implements ServiceInterface {}
class Factories {
  public static function createService(
    Dependency $dependency,
  ): ServiceInterface {
    return new Service();
  }
}

$builder = new ContainerBuilder();

$definition = new Definition(Dependency::class);
$builder->setDefinition(Dependency::class, $definition);

$definition = new Definition(ServiceInterface::class);
$definition->setAutowired(true);
$definition->setFactory([Factories::class, 'createService']);
$definition->setPublic(true);
$builder->setDefinition('service', $definition);

$builder->compile();

$service = $builder->get('service');

print get_debug_type($service) . "\n";
```

### Possible Solution

In `ContainerBuilder::getReflectionClass(), add a ` || interface_exists($class)`.

```php
        try {
            if (isset($this->classReflectors[$class])) {
                $classReflector = $this->classReflectors[$class];
            } elseif (false && class_exists(ClassExistenceResource::class)) {
                $resource = new ClassExistenceResource($class, false);
                $classReflector = $resource->isFresh(0) ? false : new \ReflectionClass($class);
            } else {
                $classReflector = (class_exists($class) || interface_exists($class)) ? new \ReflectionClass($class) : false;
            }
        } catch (\ReflectionException $e) {
            if ($throw) {
                throw $e;
            }
        }
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by donquixote**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58821.
| License       | MIT

Currently, `ContainerBuilder::getReflectionClass()` supports interfaces only if `symfony/config` package is present.
With this fix, it will do so without `symfony/config`.

> Always add tests and ensure they pass.

Not sure how to do this.
All tests run in the monorepo, with all packages present, so `class_exists(ClassExistenceResource::class)` will always be TRUE.
To make this testable, we should make the condition dependent on resource tracking.

> Never break backward compatibility (see https://symfony.com/bc).

This is TBD.
This change would enable autowire for some services where this was previously not the case.

### CODE REVIEW

**Comment by derrabus** [comment]
This looks like a bugfix to me. Please target 5.4.

**Comment by donquixote** [comment]
> This looks like a bugfix to me. Please target 5.4.

Let's see if there is consensus that this is a bug fix.

File: src/Symfony/Component/DependencyInjection/ContainerBuilder.php [hunk 1]
```diff
@@ -369,7 +369,7 @@ public function getReflectionClass(?string $class, bool $throw = true): ?\Reflec
                 $resource = new ClassExistenceResource($class, false);
                 $classReflector = $resource->isFresh(0) ? false : new \ReflectionClass($class);
             } else {
-                $classReflector = class_exists($class) ? new \ReflectionClass($class) : false;
+                $classReflector = (class_exists($class) || interface_exists($class)) ? new \ReflectionClass($class) : false;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/ContainerBuilder.php]:
```suggestion
                $classReflector = class_exists($class) || interface_exists($class, false) ? new \ReflectionClass($class) : false;
```

**Review by nicolas-grekas — COMMENTED** [review]
LGTM after some minor changes

**Comment by nicolas-grekas** [comment]
Thank you @donquixote.
