### PR TITLE
[DI] allow "." and "-" in env processor lines

### LINKED ISSUE #34864: [Dependency Injection] - Invalid env(p-redis-osb) name: only "word" characters are allowed.
**Description**  
This subject is already discussed in #33806, this is a limitation when working on some cloud services like [CloudFoundry](https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#VCAP-SERVICES) to get a service credentials, all services have a name format like (`p-redis-osb`), the simple way to fetch the target variable by `env()` is doing something like : `%env(key:host:key:credentials:key:p-redis-osb:json:VCAP_SERVICES)`, thanks to `json` and `key` processors.

`VCAP_SERVICES`  respect the naming convention, but getting a key from json doesn't respect the `/^(?:\w*+:)*+\w++$/` and generate an exception [here](https://github.com/symfony/symfony/blob/0d2f4111d3a0a8d50800dc12316f9e3faa470cb4/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php#L47)

**Suggestion** : Accepting a `-` make since if the value is not the root in `env()` syntax !

Modify regex [here](https://github.com/symfony/symfony/blob/0d2f4111d3a0a8d50800dc12316f9e3faa470cb4/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php#L47) to do : 
```php
-- if (!preg_match('/^(?:\w*+:)*+\w++$/', $env)) {
++ if (!preg_match('/^(?:[\w-]*+:)*+\w++$/', $env)) {
```

**Regex test** : https://regex101.com/r/fhdJys/2

**Example**  
```yaml
# services.yaml
 redis_session.host: '%env(key:host:key:credentials:key:p-redis-osb:json:VCAP_SERVICES)%'
```

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #34864
| License       | MIT
| Doc PR        | -

As explained in the linked issue, this is especially usefull with the `key` processor.

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php [hunk 1]
```diff
@@ -44,15 +44,15 @@ public function get(string $name)
...
+            if (!preg_match('/^(?:[-.\w]*+:)*+\w++$/', $env)) {
                 throw new InvalidArgumentException(sprintf('Invalid %s name: only "word" characters are allowed.', $name));
             }
             if ($this->has($name) && null !== ($defaultValue = parent::get($name)) && !\is_string($defaultValue)) {
                 throw new RuntimeException(sprintf('The default value of an env() parameter must be a string or null, but "%s" given to "%s".', \gettype($defaultValue), $name));
             }
 
             $uniqueName = md5($name.'_'.self::$counter++);
-            $placeholder = sprintf('%s_%s_%s', $this->getEnvPlaceholderUniquePrefix(), str_replace(':', '_', $env), $uniqueName);
+            $placeholder = sprintf('%s_%s_%s', $this->getEnvPlaceholderUniquePrefix(), strtr($env, ':-.', '___'), $uniqueName);
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php]: replacing the 3 chars with the same replacement will be an issue: we can have multiple env lines producing the same placeholder, which will go wrong when reverting them.

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php]: There is an md5 on the line before that will prevent any collisions from happening.

Comment (stof) [reply src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php]: ah indeed. I missed that.

**Review by stof — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.
