### PR TITLE
[DependencyInjection] Fix autowire attribute with nullable parameters

### LINKED ISSUE #49370: [DependencyInjection] Autowire attribute does not work for nullable parameters
### Symfony version(s) affected

6.2.6

### Description

If I try to autowire a parameter value into a service using the `#[Autowire]` attribute, autowiring fails if that parameter is `null`. The exception tells me to configure that constructor parameter explicitly. Changing the parameter to a value other than `null` makes the exception disappear.

### How to reproduce

```yaml
# services.yaml

parameters:
    my_parameter: null
```

```php
final class MyService
{
    public function __construct(
        #[Autowire('%my_parameter%')]
        private ?string $myParameter,
    ) {
    }
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alamirault**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49370
| License       | MIT
| Doc PR        | N/A

This PR fix throwing exception `Cannot autowire service "%s": argument "$%s" of method "%s()" %s, you should configure its value explicitly.` when parameter is nullable with null value. 

(sorry for pinging reviewers, switching branch trigger that)

### CODE REVIEW

**Comment by derrabus** [comment]
Wow, that was fast. Your fix looks correct. I'll test it on my codebase tomorrow to see if it fixes my issue there.

Can you please look into the "Coding Standard" failure reported by fabbot? The "Exception Messages Formatting" error however is a false positive and can be ignored.

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 1]
```diff
@@ -293,7 +293,7 @@ private function autowireMethod(\ReflectionFunctionAbstract $reflectionMethod, a
             }
 
             if (!$type) {
-                if (isset($arguments[$index])) {
+                if (\array_key_exists($index, $arguments)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: This cannot be the correct patch: there is no reason why the concern applies only when there is no (non-native) type.

Instead, I cannot recall why I added the "if" on L290 just above. This "if" means that `''` and `null` are considered as wildcard for letting autowiring process even when an attribute is used. Removing it looks like the right fix to me.

```diff
--- a/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php
+++ b/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php
@@ -276,23 +276,17 @@ class AutowirePass extends AbstractRecursivePass
                 continue;
             }
 
-            $type = ProxyHelper::exportType($parameter, true);
-
             if ($checkAttributes) {
                 foreach ($parameter->getAttributes() as $attribute) {
                     if (\in_array($attribute->getName(), [TaggedIterator::class, TaggedLocator::class, Autowire::class, MapDecorated::class], true)) {
                         $arguments[$index] = $this->processAttribute($attribute->newInstance(), $parameter->allowsNull());
 
-                        break;
+                        continue 2;
                     }
                 }
-
-                if ('' !== ($arguments[$index] ?? '')) {
-                    continue;
-                }
             }
 
-            if (!$type) {
+            if (!$type = ProxyHelper::exportType($parameter, true)) {
                 if (isset($arguments[$index])) {
                     continue;
                 }
```

Comment (alamirault) [reply src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: I applied your diff, thanks for explanations

**Comment by nicolas-grekas** [comment]
Thank you @alamirault.
