### PR TITLE
[Console] #47809 remove exit() call in last SignalHandler

### LINKED ISSUE #47809: [Console] Commands aren't able to fully gracefully exit by themselves
### Symfony version(s) affected

5.2.0+

### Description

Since https://github.com/symfony/symfony/commit/df57119884f62c2c29e8a9232b56a287196dad32 symfony/console is reacting to signals, dispatching events, and exiting right away.

My main issue here is the `exit()` inside of the signal handler, as it imposes a specific application design for graceful shutdowns and prevents the dispatch of `console.terminate` event.

### How to reproduce

A command like this should suffice:

```php
<?php

declare(strict_types=1);

namespace MyApp;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Command\SignalableCommandInterface;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

use function sleep;
use const SIGINT;
use const SIGTERM;

#[AsCommand('testing')]
final class Testing extends Command implements SignalableCommandInterface
{
    private bool $shouldContinue = true;

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        while ($this->shouldContinue) {
            $output->writeln('Still processing...');
            sleep(1);
        }

        $output->writeln('Wrapping up, wait a sec...'); // this message is never shown (unless we remove the `exit()` call)

        return self::SUCCESS;
    }

    public function getSubscribedSignals(): array
    {
        return [SIGINT, SIGTERM];
    }

    public function handleSignal(int $signal): void
    {
        $this->shouldContinue = false;
    }
}
```

### Possible Solution

I believe Symfony should not auto exit on that situation or at least provide a way to skip it.

### Additional Context

Execution of the sample command with the `exit()`:

```sh
$ bin/console testing
{"message":"Notified event \"console.command\" to listener \"Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::configure\".","context":{"event":"console.command","listener":"Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::configure"},"channel":"event","severity":"DEBUG","timestamp":"2022-10-07T10:12:24.056+00:00"}
{"message":"Notified event \"console.command\" to listener \"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onCommand\".","context":{"event":"console.command","listener":"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onCommand"},"channel":"event","severity":"DEBUG","timestamp":"2022-10-07T10:12:24.056+00:00"}
Still processing...
Still processing...
Still processing...
Still processing...
^C $ 
```

Execution of the sample command without the `exit()`:

```sh
$ bin/console testing
{"message":"Notified event \"console.command\" to listener \"Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::configure\".","context":{"event":"console.command","listener":"Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::configure"},"channel":"event","severity":"DEBUG","timestamp":"2022-10-07T10:13:39.000+00:00"}
{"message":"Notified event \"console.command\" to listener \"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onCommand\".","context":{"event":"console.command","listener":"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onCommand"},"channel":"event","severity":"DEBUG","timestamp":"2022-10-07T10:13:39.000+00:00"}
Still processing...
Still processing...
Still processing...
^CWrapping up, wait a sec...
{"message":"Notified event \"console.terminate\" to listener \"Symfony\\Component\\Console\\EventListener\\ErrorListener::onConsoleTerminate\".","context":{"event":"console.terminate","listener":"Symfony\\Component\\Console\\EventListener\\ErrorListener::onConsoleTerminate"},"channel":"event","severity":"DEBUG","timestamp":"2022-10-07T10:13:41.554+00:00"}
{"message":"Notified event \"console.terminate\" to listener \"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onTerminate\".","context":{"event":"console.terminate","listener":"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onTerminate"},"channel":"event","severity":"DEBUG","timestamp":"2022-10-07T10:13:41.554+00:00"}
$
```

### PR DESCRIPTION
**Pull request by akuzia**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| BC? | yes 
| New feature?  | no
| Deprecations? | not sure
| Tickets       | Fix #47809
| License       | MIT

This PR possibly introduces some breaking changes.

Remove last SignalHandler `exit()` call in `Application:doRunCommand` introduced in df57119884f62c2c29e8a9232b56a287196dad32.

For more context see #47809

### CODE REVIEW

**Review by chalasr — APPROVED** [review]
Works for me as a bugfix.

**Comment by akuzia** [comment]
> Works for me as a bugfix.

It is possibly a breaking change, as some of the users may or may not introduce own handlers to bypass this. Not sure if chanelog or doc changes needed

File: src/Symfony/Component/Console/Tests/ApplicationTest.php [hunk 1]
```diff
@@ -2091,28 +2104,33 @@ public function isEnabled(): bool
...
     private $emitsSignal;
 
     protected static $defaultName = 'signal';
 
-    public function __construct(bool $emitsSignal = true)
-    {
+    public function __construct(
+        bool $emitsSignal = true,
+        int $signal = \SIGUSR1
+    ) {
```
Comment (lyrixx) [inline src/Symfony/Component/Console/Tests/ApplicationTest.php]: Should be on one line

File: src/Symfony/Component/Console/Tests/ApplicationTest.php [hunk 2]
```diff
@@ -2091,28 +2104,33 @@ public function isEnabled(): bool
 class BaseSignableCommand extends Command
 {
     public $signaled = false;
+    public $exitCode = 1;
     public $signalHandlers = [];
     public $loop = 1000;
+    private $signal;
     private $emitsSignal;
```
Comment (lyrixx) [inline src/Symfony/Component/Console/Tests/ApplicationTest.php]:
```suggestion
    private $emitsSignal;
    private $signal;
```

**Review by lyrixx — COMMENTED** [review]
Except two little comments, I'm 👍🏼

**Comment by fabpot** [comment]
That's a behavior change, so it cannot be merged in 5.4. It needs to target 6.3.
A changelog is also needed to explain the changes.

**Comment by akuzia** [comment]
@fabpot I've rebased to 6.3 and added changelog entry. Phrasing may be a bit to complex, I've opened to suggestions

**Review by maxbeckers — APPROVED** [review]

File: src/Symfony/Component/Console/CHANGELOG.md [hunk 3]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+6.3
+---
+
+ * Remove 'exit` call in `Application` signal handlers. Commands will no longer be interrupted after receiving signal other than `SIGUSR1` or `SIGUSR2`
```
Comment (chalasr) [inline src/Symfony/Component/Console/CHANGELOG.md]:
```suggestion
 * Remove `exit` call in `Application` signal handlers. Commands will no longer be automatically interrupted after receiving signal other than `SIGUSR1` or `SIGUSR2`
```

**Review by chalasr — APPROVED** [review]
with minor suggestion

**Comment by fabpot** [comment]
Thank you @akuzia.

**Comment by lyrixx** [comment]
1. Hmm, this PR broke something 😬 

With the following code (only):
```php
#[AsCommand(
    name: 'loop',
)]
class LoopCommand extends Command
{
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        while (true) {
            echo "hello\n";
            usleep(100_000);
        }

        return Command::SUCCESS;
    }
}
```

when I hit CTRL+C, it does not stop anymore. this is legit since we remove the `exit()` call!

---

I'll work on it ASAP
