### PR TITLE
[HttpFoundation] Deprecate passing invalid URI to Request::create

### LINKED ISSUE #47084: Request::create can trigger deprecated array conversion in 8.1 with bad values
### Symfony version(s) affected

<=6.2

### Description

If you provide a bad value to Request::create, its possible parse_url will fail to parse it settings $components to false. Later code doesn't handle the false condition which "works" because the last bit assigns a value to the variable converting it to an array. In PHP 8.1+ however this conversion behavior is deprecated.

### How to reproduce

Request::create('/foo:123');

Outputs something like:
```
Deprecated function: Automatic conversion of false to array is deprecated in Symfony\Component\HttpFoundation\Request::create() (line 372 of /app/vendor/symfony/http-foundation/Request.php).
Symfony\Component\HttpFoundation\Request::create('/foo:123') ....
```

### Possible Solution

The url isn't valid so it would probably be good to provide developer feedback but throwing an exception would be pretty disruptive. 

Seems like the best approach might be:
1) Explicitly handle the false condition preserving the current behavior. Include deprecation.
2) Throw a InvalidArgument exception or similar in some future version.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by neclimdul**
Fixes: #47084

Passing an invalid URI to Request::create triggers an undefined code path. In PHP7 the false value returned by parse_url would quietly be treated as a an array through type coercion leading to unexpected results. In PHP8 this triggers a deprecation exposing the bug.

| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | yes
| Tickets       | Fix #47084
| License       | MIT

### CODE REVIEW

**Comment by neclimdul** [comment]
Wasn't quite sure how the Changelog/Deprecation documentation was suppose to work so that is missing but should otherwise be good to go.

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 1]
```diff
@@ -342,6 +342,10 @@ public static function create(string $uri, string $method = 'GET', array $parame
         $server['REQUEST_METHOD'] = strtoupper($method);
 
         $components = parse_url($uri);
+        if ($components === FALSE) {
+            trigger_deprecation('symfony/http-foundation', '6.3', 'Calling "%s()" without an invalid URI is deprecated.', __METHOD__ );
```
Comment (stof) [inline src/Symfony/Component/HttpFoundation/Request.php]: typo in the message. Calling it **with** an invalid URI is what is deprecated.

**Review by stof — CHANGES_REQUESTED** [review]
Please also fix the coding standards as reported by fabbot.

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 1 above)
Comment (neclimdul) [reply src/Symfony/Component/HttpFoundation/Request.php]: thanks, fixed.

**Comment by neclimdul** [comment]
@stof Fixed the relevant fabbot changes. 

```
@@ -1463,6 +1463,7 @@
      * @param bool $asResource If true, a resource will be returned
      *
      * @return string|resource
+     *
      * @psalm-return ($asResource is true ? resource : string)
      */
     public function getContent(bool $asResource = false)
```
Didn't touch this code so maybe should be handled else where?

**Comment by derrabus** [comment]
> Didn't touch this code so maybe should be handled else where?

Yes, that one you can ignore. But the `trigger_deprecation()` line fabbot complains about is your code. 🙂

**Comment by derrabus** [comment]
Also, the failing tests appear to be related.

**Comment by stof** [comment]
the test failure is because you forogt to update the assertion in the test when fixing the text of the deprecation message.

**Comment by neclimdul** [comment]
Fixed the test and that stray space that snuck in.

Somehow the tests are worse... There's a ton of fatal errors and failures that seem unrelated so hoping something changed elsewhere...

**Review by GromNaN — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @neclimdul.
