### PR TITLE
[JsonStreamer] Rebuild cache on class update

### LINKED ISSUE #62030: [JsonStreamer] Stream reader not updated when object change
### Symfony version(s) affected

7.3.0

### Description

Generated stream readers filename depend on the type name: https://github.com/symfony/symfony/blob/05409da8721245d468d8040c58d18957e716687f/src/Symfony/Component/JsonStreamer/Read/StreamReaderGenerator.php#L87-L90

That means adding or removing a property from an object won’t result in another stream reader being generated, and trying to decode such an object will fail.

This is only an issue in dev env when you will change files without refreshing caches.

### How to reproduce

Given a `Test` class

```php
class Test
{
    public int $id;
}
```
```php
$test = $reader->read('{"id": 1, "foo": "bar"}', Type::object(Test::class));
dump($test->id);
```
will correctly display `1`.

Now adding a `public string $foo` property to `Test`, displaying `$test->foo` would result in

> Typed property Test::$foo must not be accessed before initialization

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62030
| License       | MIT

Having outdated stream PHP files can lead to unexpected results.

Therefore, this PR leverages the use of `ConfigCache` to regenerate streamers on resource (ie: class) change.

### CODE REVIEW

**Comment by MatTheCat** [comment]
Thanks for looking into this! Unfortunately this didn’t solve the issue, maybe because the target object is not necessarily a resource?

**Comment by mtarld** [comment]
Indeed, I registered objects as `ReflectionClassResource` so that objects are tracked no matter where they come from, let me know if it solves the issue :slightly_smiling_face:

**Comment by mtarld** [comment]
But to work, the object needs, of course, to be marked with `#[JsonStreamable]` (which is what's written in the documentation).

**Comment by MatTheCat** [comment]
The documentation says it’s optional?

I’m still not seeing any difference though.

**Comment by stof** [comment]
see my comment on the issue. Making the cache warmer required *and* invalidating the whole *container* cache when the streamable class gets edited is overkill IMO.
In dev, we should rather keep generating the streamable classes on demand (there will be tons of cases where you will edit something in your project without running code for all your streamable classes, where a required class warmer would slow down your dev env for nothing), but with proper cache invalidation.

**Comment by mtarld** [comment]
@stof, the PR has been updated to leverage config cache factories (like in translator and router). 

Let me know if it's the right approach (I'm not used to that).

**Comment by MatTheCat** [comment]
This is better but it seems the cache won’t be refreshed if a nested class changes.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -2127,6 +2127,21 @@ private function registerJsonStreamerConfiguration(array $config, ContainerBuild
         if (\PHP_VERSION_ID >= 80400) {
             $container->removeDefinition('.json_streamer.cache_warmer.lazy_ghost');
         }
+
+        $streamWriterDefinition = $container->getDefinition('json_streamer.stream_writer');
+        if (!method_exists($streamWriterDefinition->getClass() ?? '', 'setConfigCacheFactory')) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: why would the class be null??

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: and why use getClass class when the value is already known BTW?

File: src/Symfony/Component/JsonStreamer/JsonStreamReader.php [hunk 2]
```diff
@@ -103,4 +105,9 @@ public function get(string $id): ValueTransformerInterface
 
         return new self($valueTransformersContainer, $propertyMetadataLoader, $streamReadersDir, $lazyGhostsDir);
     }
+
+    public function setConfigCacheFactory(ConfigCacheFactoryInterface $configCacheFactory): void
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonStreamer/JsonStreamReader.php]: why adding setter vs constructor arg also?

Comment (mtarld) [reply src/Symfony/Component/JsonStreamer/JsonStreamReader.php]: Indeed, it is way easier that way!

**Comment by mtarld** [comment]
Low deps tests should be fixed once merged.

**Comment by nicolas-grekas** [comment]
> Low deps tests should be fixed once merged.

let me doubt about this: merging up won't change anything to lowest deps

**Comment by mtarld** [comment]
My thought was:
- `FrameworkBundle` is failing with a too low version on `JsonStreamer` (`<=7.3.4` which is without config cache)
- If `FrameworkBundle` is requiring `JsonStreamer` at the next version (`^7.3.5`), it should work again

Thinking to this again, I'm indeed wrong, because `FrameworkBundle:^7.3.5` can still require `JsonStreamer:^7.3.2` for example. Therefore:
- maybe we need to add something like a conflict to `symfony/json-streamer: <7.3.5`?
- or maybe I update the test with a `class_exists` on `StreamerDumper` in the test to make it dependent of that fix?

WDYT?

**Comment by nicolas-grekas** [comment]
Thank you @mtarld.
