### PR TITLE
[FrameworkBundle] Split loggers debug compiler pass

### LINKED ISSUE #48040: [FrameworkBundle][HttpKernel] Logger debug mode disabled
### Symfony version(s) affected

6.2-beta

### Description

In #47483 I made `Symfony\Component\HttpKernel\Log\Logger` implement `Symfony\Component\HttpKernel\Log\DebugLoggerInterface`. But after testing against v6.2.0-BETA2 it appears logs are not collected. (It worked on my testing app because I had set the `logger` service myself.)

### How to reproduce

Do not install Monolog and send some logs while the profiler is enabled. These logs won’t appear in the profiler.

### Possible Solution

The issue stems from `AddDebugLogProcessorPass` (priority 2) being processed before the `LoggerPass` (priority -32).

Given https://github.com/symfony/symfony/pull/31509 I guess there are two ways to solve this:
- create a distinct compiler pass for enabling HttpKernel’s logger debug mode
- increase `LoggerPass` priority to at least `3`

Not sure which one would be the best. https://github.com/symfony/symfony/pull/24300#discussion_r141752800 does not help :grin: 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #48040
| License       | MIT
| Doc PR        | N/A

As the Monolog and HttpKernel’s loggers have nothing to do with each other I feel like giving each one its own compiler pass is best.

### CODE REVIEW

**Comment by maxbeckers** [comment]
This would be a BC break or am I wrong?

**Comment by MatTheCat** [comment]
@maxbeckers how? Are compiler passes configurators part of Symfony’s public API?

**Comment by maxbeckers** [comment]
My two thoughts were renaming the class and changing the priorities. It's only debug compiler passes, but wanted to at least note it. That's why I'm not sure if it's a BC break or not.

**Comment by MatTheCat** [comment]
@fabpot I see you changed the milestone to 6.3 but this PR is supposed to be a fix for a feature introduced in 6.2. Is that alright?

**Comment by fabpot** [comment]
In that case, 6.2 is indeed the right target.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/EnableLoggerDebugModePass.php [hunk 1]
```diff
@@ -13,45 +13,27 @@
 
 use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
 use Symfony\Component\DependencyInjection\ContainerBuilder;
-use Symfony\Component\DependencyInjection\Reference;
 use Symfony\Component\HttpKernel\Log\Logger;
 
-class AddDebugLogProcessorPass implements CompilerPassInterface
+class EnableLoggerDebugModePass implements CompilerPassInterface
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/EnableLoggerDebugModePass.php]: we cannot rename this pass, that'd be a BC break
+ it should continue to do what it does in 6.1

Comment (MatTheCat) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/EnableLoggerDebugModePass.php]: Okay, do I add a deprecation or isn’t it significant enough?

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/EnableLoggerDebugModePass.php]: no remaining would be best

Comment (stof) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/EnableLoggerDebugModePass.php]: `AddDebugLogProcessorPass` is actually an accurate name for the Monolog pass as that's what it does (and was doing in 6.1). So there is no need for a deprecation.

Comment (MatTheCat) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/EnableLoggerDebugModePass.php]: Yes the diff is weird I actually renamed `AddDebugLogProcessorPass` to `AddMonologDebugLogProcessorPass`. Will rollback.

Comment (stof) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/EnableLoggerDebugModePass.php]: Well, git does not have a concept of renaming. `git diff` detects renamings by file similarity.

**Review by stof — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @MatTheCat.
