### PR TITLE
[HttpKernel] Add session cookie handling in cli context

### LINKED ISSUE #42890: Sessions are not saved when using runtime + bref/swoole/roadrunner
Im not sure if this is a bug report or a missing feature. But I do need some help. 

**Symfony version(s) affected**: 5.4

**Description**
Using the Runtime component and non-standard HTTP server, ie Bref, Swoole or RoadRunner seams to have an issue with sessions. I know @alexander-schranz have done some great work on that already. He also added #41390. 

The sessions are not saved. I am not sure why. I assume it is because the PHP process handles multiple requests and Symfony does not really know when one session/request ends and the other start. 

**How to reproduce**

I did spend some time to create a reproducer: https://github.com/Nyholm/sf-bref-session-issue
I also deployed it here: https://hb74khn5fk.execute-api.eu-central-1.amazonaws.com/
(it will be open for a few days)

You will see the issue as you cannot login. 

**Possible Solution**
Not sure. I need some help finding the solution. 

**Additional context**

This might be an issue in runtime/bref, or in a Symfony component. It might also require some changes in Symfony to make sure runtime/bref works perfectly.

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q             | A
| ------------- | ---
| Branch?       | 5.4 
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #42890
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Currently the session cookie is never set on the `request` object. In a normal webserver setup this is not needed as a session is in php-fpm or apache fastcgi written by php itself when the response is outputted in: https://github.com/symfony/symfony/blob/744b901750c1cc09e85bcb2ebdf0505449a1158f/src/Symfony/Component/HttpFoundation/Response.php#L393

When use a runner like `Roadrunner` the `session` cookie is never set on the `Request` object, as this kind of appserver never really outputs something and is running in the `cli` context.

Actually there is no way from outside to know if `$session->save()` was called or not because when the code in `Roadrunner` executes the session is actually written and so closed here: https://github.com/symfony/symfony/blob/744b901750c1cc09e85bcb2ebdf0505449a1158f/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L279.

The best way so to fix this issue is that in CLI context symfony writes the session cookie on the `Response` object when the session is really saved.

This fixes issues which we have in the current roadrunner implementation of php runtime:
  - [x] https://github.com/php-runtime/roadrunner-symfony-nyholm/blob/58665237ef2bff08a1ebf269e64abbf8cd09fbd7/src/Runner.php#L89
  - [x] https://github.com/php-runtime/roadrunner-symfony-nyholm/blob/58665237ef2bff08a1ebf269e64abbf8cd09fbd7/src/Runner.php#L81

Beside Roadrunner there is also Swoole implementation which would require the same here: https://github.com/php-runtime/runtime/issues/60

With this changes the Runners can be simplified a lot: https://github.com/php-runtime/runtime/pull/62/files#

## TODO

Reset session variables after successfully response. The following code currently lives also in the runtime implementation but is requires also by all runners and so we should find a place where we put it:

```
                if (PHP_SESSION_ACTIVE === session_status()) {
                    session_abort();
                }
                // reset all session variables to initialize state
                $_SESSION = [];
session_id(''); // in this case session_start() will generate us a new session_id()
```

EDIT: Added this now to the `AbstractSessionListener` service via `ResetInterface`.

### CODE REVIEW

File: src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php [hunk 1]
```diff
@@ -115,6 +116,34 @@ public function onKernelResponse(FilterResponseEvent $event)
              * it is saved will just restart it.
              */
             $session->save();
+
+            /*
+             * Write cookie to request object for cli context based runner like roadrunner,
+             * where php can not write the cookie.
+             */
+            if (\PHP_SAPI === 'cli') {
+                $cookieParams = session_get_cookie_params();
```
Comment (alexander-schranz) [inline src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]: Maybe we should inject this framework session config, instead of build on top that the storage is setting this here per `ini_set`: https://github.com/symfony/symfony/blob/744b901750c1cc09e85bcb2ebdf0505449a1158f/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L395

File: src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php [hunk 2]
```diff
@@ -115,6 +116,34 @@ public function onKernelResponse(FilterResponseEvent $event)
              * it is saved will just restart it.
              */
             $session->save();
+
+            /*
+             * Write cookie to request object for cli context based runner like roadrunner,
+             * where php can not write the cookie.
+             */
+            if (\PHP_SAPI === 'cli') {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]: Maybe we should make this unconditional?

File: src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]: that'd be worth a try yes, instead of relying on global state

File: src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php (hunk 2 above)
Comment (alexander-schranz) [reply src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]: Would that not end that in the normal mode (apache php mod, nginx, php-fpm) php itself would write a cookie and symfony would write a cookie with the same name?

Comment (alexander-schranz) [reply src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]: But maybe we could avoid that at https://github.com/symfony/symfony/blob/9ccd0ad387f0aacf2a1f5673fdcf31dbbef22e35/src/Symfony/Component/HttpFoundation/Response.php#L365 but need to test how it behaves in the normal mode.

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/session.xml [hunk 3]
```diff
@@ -70,6 +70,8 @@
                 <argument key="session" type="service" id="session" on-invalid="ignore" />
                 <argument key="initialized_session" type="service" id="session" on-invalid="ignore_uninitialized" />
             </argument>
+            <argument>%kernel.debug%</argument>
```
Comment (alexander-schranz) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/session.xml]: Is just here to avoid BC Break in Symfony 5 which has optional second debug parameter.

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 4]
```diff
@@ -720,6 +720,14 @@ public function getSession()
         $session = $this->session;
         if (!$session instanceof SessionInterface && null !== $session) {
             $this->setSession($session = $session());
+            /*
```
Comment (Nyholm) [inline src/Symfony/Component/HttpFoundation/Request.php]: Why shouldn't this be running if `$session instanceof SessionInterface`?

Should we move this new block outside of the current if-statement and into a new one with: 

```php
if ($session instanceof SessionInterface) {
    if (!$session->isStarted()) {
      $sessionId = $this->cookies->get($session->getName(), '');
      $session->setId($sessionId);
    }
}
```

**Review by Nyholm — COMMENTED** [review]
Thank you. 

I like this. Is it ready for a review (ie, not draft)?
If so, I would be happy if @jderusse gave his opinion on this solution.

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 4 above)
Comment (alexander-schranz) [reply src/Symfony/Component/HttpFoundation/Request.php]: Its only required to set once when the Session is beinged created by the SessionFactory is being created and the `$session()` creating the Session here. Another place could be doing it directly in the SessionFactory.

File: src/Symfony/Component/HttpKernel/EventListener/SessionListener.php [hunk 5]
```diff
@@ -29,9 +29,12 @@
...
 class SessionListener extends AbstractSessionListener
 {
-    public function __construct(ContainerInterface $container)
+    /**
+     * @param array<string, mixed> $sessionOptions
+     */
+    public function __construct(ContainerInterface $container, bool $debug = false, array $sessionOptions = [])
     {
-        $this->container = $container;
+        parent::__construct($container, $debug, $sessionOptions);
```
Comment (jderusse) [inline src/Symfony/Component/HttpKernel/EventListener/SessionListener.php]: This function does nothing but passiong the same arguments to the parent. Couldn't it be removed?

**Comment by alexander-schranz** [comment]
@Nyholm Yes the PR itself is ready for review, I want still provide some tests for the Listener logic.

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 6]
```diff
@@ -720,6 +720,14 @@ public function getSession()
...
+             * For supporting sessions in php runtime with runners like roadrunner or swoole the session
+             * cookie need read from the cookie bag and set on the session storage.
+             */
+            if (!$session->isStarted()) {
+                $sessionId = $this->cookies->get($session->getName(), '');
```
Comment (jderusse) [inline src/Symfony/Component/HttpFoundation/Request.php]: Shouldn't it be done by the AbstractSessionHandler?

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 7]
```diff
@@ -720,6 +720,14 @@ public function getSession()
...
+                $session->setId($sessionId);
```
Comment (jderusse) [inline src/Symfony/Component/HttpFoundation/Request.php]: I wonder how this behave when app ask for regenerating the sessionId and a cookie already exists

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 4 above)
Comment (Nyholm) [reply src/Symfony/Component/HttpFoundation/Request.php]: Hm.. Is that cleaner? 
To modify the callable in `AbstractSessionListener::onKernelRequest()`?

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 8]
```diff
@@ -720,6 +720,14 @@ public function getSession()
         $session = $this->session;
         if (!$session instanceof SessionInterface && null !== $session) {
             $this->setSession($session = $session());
+            /*
+             * For supporting sessions in php runtime with runners like roadrunner or swoole the session
+             * cookie need read from the cookie bag and set on the session storage.
+             */
+            if (!$session->isStarted()) {
```
Comment (jderusse) [inline src/Symfony/Component/HttpFoundation/Request.php]: Any particular reason to call this code only when the injected session is a factory? This sounds "fragile" to me.

File: src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php [hunk 9]
```diff
@@ -115,6 +126,54 @@ public function onKernelResponse(FilterResponseEvent $event)
              * it is saved will just restart it.
              */
             $session->save();
+
+            /*
+             * For supporting sessions in php runtime with runners like roadrunner or swoole the session
```
Comment (jderusse) [inline src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php:138]: Shouldn't it be done by swoole (or roadrunner)'s middleware then?

**Review by jderusse — COMMENTED** [review]
IMHO adding supports for cookies in CLI SAPI is a new feature and should target 5.4

I also believe this things goes beyond Symfony and should be handled by Runtimes (RoadRunner, Swoole...). If I'm not wrong, php-pm already does this.

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 7 above)
Comment (alexander-schranz) [reply src/Symfony/Component/HttpFoundation/Request.php]: @jderusse It seems like this can not happend, it can only regenerate a session when its already started else PHP will throw a warning:

```bash
php -r 'session_regenerate_id();'
```
Will output:

```
PHP Warning:  session_regenerate_id(): Session ID cannot be regenerated when there is no active session in Command line code on line 1

Warning: session_regenerate_id(): Session ID cannot be regenerated when there is no active session in Command line code on line 1
```

Comment (alexander-schranz) [reply src/Symfony/Component/HttpFoundation/Request.php]: I could also check if there is no sessionId already set? What do you think about this?

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 8 above)
Comment (alexander-schranz) [reply src/Symfony/Component/HttpFoundation/Request.php]: Wanted to avoid that it is called every time `getSession()` is triggered. Maybe I should just check if already a session id was set else read it from the cookie, what do you think?

File: src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php (hunk 9 above)
Comment (alexander-schranz) [reply src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php:138]: The problem is that swoole and roadrunner doesn't no anything about the symfony framework session configuration and so can not handle this correctly based on that configuration. To avoid that we need to duplicate also the logic in the php-runtime swoole symfony and roadrunner implementation I thought it would be great if Symfony Sessions just work out of the box running in CLI context.

Comment (alexander-schranz) [reply src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php:138]: Also we are not knowing in the middlewares if a session was started and saved which is important for correct handling in all cases.

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 6 above)
Comment (alexander-schranz) [reply src/Symfony/Component/HttpFoundation/Request.php]: Not sure how this can be handled there as there is no Request available to read the cookie there?

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 4 above)
Comment (alexander-schranz) [reply src/Symfony/Component/HttpFoundation/Request.php]: Sounds like a good idea so also the handling is done all in the HttpKernel component.

File: src/Symfony/Component/HttpKernel/EventListener/SessionListener.php (hunk 5 above)
Comment (alexander-schranz) [reply src/Symfony/Component/HttpKernel/EventListener/SessionListener.php]: you are correct did remove it.

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 7 above)
Comment (alexander-schranz) [reply src/Symfony/Component/HttpFoundation/Request.php]: Method was like suggested above moved to the AbstractSessionListener which I think is great so all logic about this lives in the HttpKernel component now.

File: src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php (hunk 9 above)
Comment (alexander-schranz) [reply src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php:138]: Did rebase the PR and target the 5.4 branch now.

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 10]
```diff
@@ -430,6 +430,8 @@ public static function create(string $uri, string $method = 'GET', array $parame
      * This is mainly useful when you need to override the Request class
      * to keep BC with an existing system. It should not be used for any
      * other purpose.
+     *
+     * @param callable():SessionInterface|null $callable A PHP callable
```
Comment (Nyholm) [inline src/Symfony/Component/HttpFoundation/Request.php]:
```suggestion
     * @param callable():SessionInterface|null $callable
```

I like the clear parameter, but the "A PHP callable" did not bring any added value.

**Review by Nyholm — COMMENTED** [review]
Thank you. 

Im happy with this PR. 

------

Where would we add the reset session variables after successfully response? (Ie, your TODO)

**Review by jderusse — COMMENTED** [review]
If we now handle cookie in the "default flow", what's about deprecating the `AbstractTestSessionListener`? :thinking:

**Comment by alexander-schranz** [comment]
@Nyholm As it is now handled all in the `AbstractSessionListener` I added there the ResetInterface to handle it there. **EDIT**: Need to have a deeper look at this as currently some tests fails now.
@jderusse Sounds good for me did add a deprecation message to the class.

**Comment by alexander-schranz** [comment]
@jderusse I added a deprecation message but the CI is failing now because of that. Not sure if we can just remove https://github.com/symfony/symfony/blob/e2d1cb1d3ca5cc57315626f3e8c24a582ca460b6/src/Symfony/Bundle/FrameworkBundle/Resources/config/test.php#L38-L44  or if we should keep the test listener. What do you think?

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 11]
```diff
@@ -325,7 +325,7 @@ public function load(array $configs, ContainerBuilder $container)
             $this->sessionConfigEnabled = true;
             $this->registerSessionConfiguration($config['session'], $container, $loader);
             if (!empty($config['test'])) {
-                $container->getDefinition('test.session.listener')->setArgument(1, '%session.storage.options%');
+                $container->getDefinition('test.session.listener')->setArgument(2, '%session.storage.options%');
```
Comment (Nyholm) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:328]: This is because we switched from `TestSessionListener` to `SessionListener`

**Review by Nyholm — COMMENTED** [review]
I hope you don't mind that I pushed [a small commit](https://github.com/symfony/symfony/pull/41390/commits/69c02df4d7bdfa38b10ced824ba4539ab9d2eaf0) to fix the tests.

File: src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php [hunk 12]
```diff
@@ -142,7 +142,7 @@ public function onKernelResponse(ResponseEvent $event)
             $sessionId = $session->getId();
             $sessionCookiePath = $this->sessionOptions['cookie_path'] ?? '/';
             $sessionCookieDomain = $this->sessionOptions['cookie_domain'] ?? null;
-            $sessionCookieSecure = $this->sessionOptions['cookie_secure'] ?? null;
+            $sessionCookieSecure = $this->sessionOptions['cookie_secure'] ?? false;
```
Comment (Nyholm) [inline src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php:145]: FYI @alexander-schranz

File: src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php [hunk 13]
```diff
@@ -109,6 +133,54 @@ public function onKernelResponse(ResponseEvent $event)
...
+            if ($requestSessionCookieId && $session->isEmpty()) {
+                $response->headers->clearCookie(
+                    $sessionName,
+                    $sessionCookiePath,
+                    $sessionCookieDomain,
+                    $sessionCookieSecure,
+                    $sessionCookieHttpOnly,
+                    $sessionCookieSameSite
+                );
+            } elseif ($sessionId !== $requestSessionCookieId) {
```
Comment (Nyholm) [inline src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php:163]: I have one silly question. Im asking because I'm ignorant. 

The if-statement on line 154 checks "if there is an existing cookie and the session is empty". 

This if-statement checks "if we have a new session".
What if we updated a value in the existing session, then we nee to store it in a cookie too, right? Or am I missing something?

Comment (Nyholm) [reply src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php:163]: So, I found the answer to my own question. 

It is only the sessionId that needs to be stored in the cookie. The actual data is stored on file (default for PHP), in Redis or whatever session handler you have. 

So there is only need to add or remove the cookie, which is what this code does.

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 14]
```diff
@@ -430,6 +430,8 @@ public static function create(string $uri, string $method = 'GET', array $parame
      * This is mainly useful when you need to override the Request class
      * to keep BC with an existing system. It should not be used for any
      * other purpose.
+     *
+     * @param callable():SessionInterface|null $callable
```
Comment (jderusse) [inline src/Symfony/Component/HttpFoundation/Request.php]: :thinking: This method is about `requestFactory`. I think you confuse with the `setSessionFactory` method

**Review by jderusse — APPROVED** [review]

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 14 above)
Comment (Nyholm) [reply src/Symfony/Component/HttpFoundation/Request.php]: I remove this. 

`setSessionFactory()` already has this annotation.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @alexander-schranz.

**Comment by Nyholm** [comment]
Awesome. 
Thank you all.

**Comment by alexander-schranz** [comment]
Nice to see this merged. Thank you all!

**Comment by GrahamCampbell** [comment]
🎉
