### PR TITLE
[ObjectMapper] Preserve non-promoted constructor parameters

### LINKED ISSUE #61348: [ObjectMapper] ObjectMapper::map calling constructor without any arguments
### Symfony version(s) affected

7.3.2

### Description

There seems to be an issue introduced by [https://github.com/symfony/symfony/pull/61036](https://github.com/symfony/symfony/pull/61036). 

When calling map with a FQDN as target the mapping fails because the constructor is called without any arguments. Prior to the change the constructor was not called at all because `$ctorArguments` is empty.

The issue does not occur when property promotion is being used because:

```
if (!$parameter->isPromoted()) {
    continue;
}
```

does not lead to the filling of `$ctorArguments` being skipped.

### How to reproduce

```
<?php

namespace App;

class Foo {
    public string $bar;

    public function __construct(string $bar) {
        $this->bar = $bar;
    }
}
```
```
<?php

namespace App\Controller;

use App\Foo;
use stdClass;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\ObjectMapper\ObjectMapperInterface;

#[AsCommand(name: 'test')]
class TestCommand extends Command
{
    public function __construct(
        private readonly ObjectMapperInterface $mapper,
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $object = new stdClass();
        $object->bar = 'bar';

        $foo = $this->mapper->map($object, Foo::class);

        return Command::SUCCESS;
    }
}
```
`Too few arguments to function App\Foo::__construct(), 0 passed in /var/www/html/vendor/symfony/object-mapper/ObjectMapper.php on line 159 and exactly 1 expected`

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rvanlaak**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #61348 
| License       | MIT

The object mapper does already call the constructor, but its argument values were not determined / collected correctly as non-promoted parameters were skipped. Can not find or think of a valid reason for that. This PR fixes that the non-promoted constructor parameter values will get resolved and thereafter get mapped.

### CODE REVIEW

**Comment by frozenbrain** [comment]
If non-promoted constructor parameters are now valid mapping targets, should we also support putting the `Map` attribute on those as well? Promoted parameters already support it, therefore I believe this should be also possible for non-promoted ones.

Also, one thing I noticed is that with this change a property with the same name as the constructor parameter has to exist, is that intentional? For example, the following code throws an exception, because `Target::$name` does not exist:
```php
class Target {
    #[Map(if: false)]
    private string $nameUpper;

    public function __construct(string $name)
    {
        $this->nameUpper = strtoupper($name);
    }
}

$mapper = new ObjectMapper();

$source = new stdClass();
$source->name = 'John';

$target = $mapper->map($source, Target::class);
```

**Comment by rvanlaak** [comment]
@frozenbrain nice catch, the PR now covers that case as well. See commit e6009b3653a3168ad4741cf9bb63ec3f290f1c87 for details on the fix. 

The issue related to [the following comment](https://github.com/symfony/symfony/blob/9c99c367eae55ea30e888ac2f53cab5589b0b2be/src/Symfony/Component/ObjectMapper/ObjectMapper.php#L107):

```php
// this may be filled later on see storeValue
```

When the property name differs from the constructor argument name, the constructor argument's value did actually not get filled in at a later time. It are the properties that get iterated over later on, which isn't aware of the constructor argument name anymore (as property field had a different name).

**Comment by rvanlaak** [comment]
Failing check is unrelated.

@soyuka can you help with reviewing this PR?

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php [hunk 1]
```diff
@@ -92,21 +92,28 @@ public function map(object $source, object|string|null $target = null): object
...
+
+                if ($property->isReadOnly() && $property->isInitialized($mappedTarget)) {
+                    continue;
+                }
             }
 
-            // this may be filled later on see storeValue
-            $ctorArguments[$parameterName] = $parameter->isDefaultValueAvailable() ? $parameter->getDefaultValue() : null;
+            try {
+                $ctorArguments[$parameterName] = $this->getRawValue($source, $parameterName);
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/ObjectMapper.php:108]: Instead of using try/catch we could create a new method like this: 

```php
    private function isReadable(object $source, string $propertyName): mixed
    {
        if ($this->propertyAccessor) {
            return $this->propertyAccessor->isReadable($source, $propertyName);
        }

        if (!property_exists($source, $propertyName) && !isset($source->{$propertyName})) {
           return false;
        }

        return true;
    }
```

I'm not sure its better what do you think?

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php [hunk 2]
```diff
@@ -92,21 +92,28 @@ public function map(object $source, object|string|null $target = null): object
...
+            } catch (NoSuchPropertyException) {
+                /*
+                 * When source has no value for the constructor arguments, then fallback to default. Constructor stays
+                 * responsible for delivering a valid object or throwing exceptions, so rely on PHP runtime exceptions
+                 * for further handling.
+                 */
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/ObjectMapper.php]: I don't think that this comment is very useful its quite straightforward.

**Review by soyuka — APPROVED** [review]
indeed good catch

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php (hunk 2 above)
Comment (rvanlaak) [reply src/Symfony/Component/ObjectMapper/ObjectMapper.php]: Agreed, removed it. Wrote this while trying to understand the mapper's internals, as the `map` method is quite lengthy.

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php (hunk 1 above)
Comment (rvanlaak) [reply src/Symfony/Component/ObjectMapper/ObjectMapper.php:108]: Agree, fixed. It puts us more in control of being able to read a value.

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php (hunk 2 above)
Comment (rvanlaak) [reply src/Symfony/Component/ObjectMapper/ObjectMapper.php]: Agreed, removed it. Wrote this while trying to understand the mapper's internals, as the map method is quite lengthy.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @rvanlaak.
