### PR TITLE
[Translation] Add intl-icu fallback for MessageCatalogue metadata

### LINKED ISSUE #60523: [Translation] Metadata is being lost when +intl-icu is used
### Symfony version(s) affected

7.2.6

### Description

If you fetch messages using `MessageCatalogue::all()` from a MessageCatalogue, it automatically merges `domain` and `domain+intl-icu` messages. However, `MessageCatalogue::getMetadata` does NOT do this, causing messages to exist but metadata missing.

This gets more serious as `->getDomains()` returns the plain domains (without +intl-icu), causing metadata being dropped in most things that loops over messages (such as `\Symfony\Component\Translation\Bridge\Crowdin\CrowdinProvider`)

### How to reproduce

```php
<?php
require_once './vendor/autoload.php';

$catalog = new \Symfony\Component\Translation\MessageCatalogue("en");
$catalog->add(["key" => "The text"], domain: "messages+intl-icu");

$catalog->setMetadata("key", ['notes' => [['content' => "This will disappear"]]], domain: "messages+intl-icu");

foreach ($catalog->getDomains() as $domain) {
    foreach ($catalog->all($domain) as $key => $value) {
        // Shouldn't be null here!
        if($catalog->getMetadata($key, $domain) == null) {
            echo "Woe and despair, my metadata is hiding from me!\n";
        }
    }
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by pontus-mp**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60523 
| License       | MIT

Added domain fallback for metadata, which should match the behavior used for fetching messages.

### CODE REVIEW

File: src/Symfony/Component/Translation/Tests/Catalogue/MetadataTest.php [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\Translation\Tests\Catalogue;
+
+use PHPUnit\Framework\TestCase;
+use Symfony\Component\Translation\MessageCatalogue;
+
+class MetadataTest extends TestCase
```
Comment (OskarStark) [inline src/Symfony/Component/Translation/Tests/Catalogue/MetadataTest.php]:
```suggestion
class MessageCatalogueTest extends TestCase
```
?

**Comment by welcoMattic** [comment]
Congrats @pontus-mp on your 1st contribution here! 

In order to propagate properply the fix, could you update your PR to target the 6.4 branch?
Therefore, the fix will be propagated by up-merge of 6.4 into 7.2 and 7.3.

Thank you

**Comment by pontus-mp** [comment]
> In order to propagate properply the fix, could you update your PR to target the 6.4 branch? 

Sure! Does everything look correct now?

**Review by welcoMattic — APPROVED** [review]

File: src/Symfony/Component/Translation/MessageCatalogue.php [hunk 2]
```diff
@@ -237,6 +237,16 @@ public function getMetadata(string $key = '', string $domain = 'messages'): mixe
             return $this->metadata;
         }
 
+        if (isset($this->metadata[$domain.self::INTL_DOMAIN_SUFFIX])) {
+            if ('' == $key) {
```
Comment (yceruto) [inline src/Symfony/Component/Translation/MessageCatalogue.php]:
```suggestion
            if ('' === $key) {
```

Comment (pontus-mp) [reply src/Symfony/Component/Translation/MessageCatalogue.php]: There are a few more loose comparisons in the method in rows that weren't touched by this PR. Should I fix those as well?

Comment (yceruto) [reply src/Symfony/Component/Translation/MessageCatalogue.php]: At least not in this branch, CS improvements should go in the latest branch (e.g. 7.4) but let's fix the one introduced here.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @pontus-mp.
