### PR TITLE
[HttpKernel] Handle previously converted `DateTime` arguments

### LINKED ISSUE #770: Bug when convert datetime param on symfony 6.1
Hello here,

I have migrate one of my project on Symfony 6.1 version, and I have a bug on one controller function :
```
  /**
     * @Route("/print-{p_dateStart}_{p_dateEnd}", name="print_stat", methods={"GET"})
     */
    public function printAction(\Datetime $p_dateStart, \Datetime $p_dateEnd): Response
    {
        dump($p_dateStart);
        dump($p_dateEnd);
    }
```

On Symfony 6.0 version, my param has been converted into Datetime.

And when i have made the migration, i have an error like this :
DateTime::__construct(): Argument #1 ($datetime) must be of type string, DateTime given

The Stack Trace :
> TypeError
> --
> TypeError: DateTime::__construct(): Argument #1 ($datetime) must be of type string, DateTime given    at vendor/symfony/http-kernel/Controller/ArgumentResolver/DateTimeValueResolver.php:70   at DateTime->__construct(object(DateTime))      (vendor/symfony/http-kernel/Controller/ArgumentResolver/DateTimeValueResolver.php:70)   at Symfony\Component\HttpKernel\Controller\ArgumentResolver\DateTimeValueResolver->resolve(object(Request), object(ArgumentMetadata))      (vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php:58)   at Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver->resolve(object(Request), object(ArgumentMetadata))      (vendor/symfony/http-kernel/Controller/ArgumentResolver.php:58)   at Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(object(Request), array(object(LogController), 'logStatisticsAction'))      (vendor/symfony/http-kernel/Controller/TraceableArgumentResolver.php:38)   at Symfony\Component\HttpKernel\Controller\TraceableArgumentResolver->getArguments(object(Request), array(object(LogController), 'logStatisticsAction'))      (vendor/symfony/http-kernel/HttpKernel.php:144)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)      (vendor/symfony/http-kernel/HttpKernel.php:74)   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)      (vendor/symfony/http-kernel/Kernel.php:202)   at Symfony\Component\HttpKernel\Kernel->handle(object(Request))      (public/index.php:17)
>

### PR DESCRIPTION
**Pull request by mbabker**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix sensiolabs/SensioFrameworkExtraBundle#770
| License       | MIT
| Doc PR        | N/A

I'm not sure I like this fix, but given the order of operations between the param converters in SensioFrameworkExtraBundle and the controller argument resolvers in the HttpKernel component, this is probably going to cause the least number of headaches for users when upgrading.  And in some ways, this is the same problem as #40333 but in reverse.

Because the param converters are triggered on the `kernel.controller` event, they will handle converting values before the controller argument resolvers are fired.  This means that a typehinted `DateTimeInterface` will potentially be handled twice (once by the param converter, once by the argument resolver).  To avoid the `TypeError` noted in the issue, a practical fix is to gracefully handle a previously converted value in this resolver.  As the other options aren't great (removing services from the container or turning off the param converters in full, which has other side effects), this is probably the most practical fix.

### CODE REVIEW

File: src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/DateTimeValueResolver.php [hunk 1]
```diff
@@ -40,6 +40,13 @@ public function resolve(Request $request, ArgumentMetadata $argument): iterable
     {
         $value = $request->attributes->get($argument->getName());
 
+        // If the value is already a DateTimeInterface (i.e. from the framework extra bundle's param converters), yield it as is
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/DateTimeValueResolver.php]: can be removed imho

**Review by nicolas-grekas — APPROVED** [review]

**Comment by chalasr** [comment]
>  or turning off the param converters in full, which has other side effects),

Can you elaborate on the side effects? I'm really not fond of patching Symfony to support a mix of param converters and argument value resolvers

**Comment by mbabker** [comment]
> > or turning off the param converters in full, which has other side effects),
> 
> Can you elaborate on the side effects? I'm really not fond of patching Symfony to support a mix of param converters and argument value resolvers

If your app already relies on them, then turning off the param converters (especially with #43854 not making it into 6.1) ends up being a much bigger refactoring.  As much as I don't like the patch either, being a pragmatist here, I do think it solves the upgrade issue in a way that causes the least frustration for end-users (as otherwise you really either have to turn off the param converters and rewrite all controllers relying on those or mess with the container to remove one of the services to avoid the double-conversion issue), and this one condition can be re-evaluated or removed once we're at a version where both of the `SensioFrameworkExtraBundle` converters have replacements.

**Comment by chalasr** [comment]
> especially with https://github.com/symfony/symfony/pull/43854 not making it into 6.1

I thought it was in, thanks.

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @mbabker.
