### PR TITLE
[FrameworkBundle] Check for console package before register `CommandDataCollector`

### LINKED ISSUE #63041: symfony/framework-bundle register service even when the console component is not available.
### Symfony version(s) affected

8.0.3

### Description

I try to update the `freshcells/soap-client-bundle` to symfony 8.

see https://github.com/freshcells/soap-client-bundle/pull/35 it fails
```
Failed asserting that exception of type "Error" matches expected exception "Exception". Message was: "Class "Symfony\Component\Console\DataCollector\CommandDataCollector" not found" at
```

It seams that the `symfony/framework-bundle (v8.0.3)` registers the CommandDataCollector service even when the console component is not available.

see also slack discussion 
https://symfony-devs.slack.com/archives/C3EQ7S3MJ/p1767777168150859

### How to reproduce

see  https://github.com/freshcells/soap-client-bundle/pull/35

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by gimler**
fix #63041

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63041
| License       | MIT

Only register `.data_collector.command` when `symfony/console` is available.

~Question: The name has a `.` prefix it seams wrong?~

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/collectors.php [hunk 1]
```diff
@@ -75,8 +75,13 @@
         ->set('data_collector.router', RouterDataCollector::class)
             ->tag('kernel.event_listener', ['event' => KernelEvents::CONTROLLER, 'method' => 'onKernelController'])
             ->tag('data_collector', ['template' => '@WebProfiler/Collector/router.html.twig', 'id' => 'router', 'priority' => 285])
+    ;
 
-        ->set('.data_collector.command', CommandDataCollector::class)
+    // only if symfony/console package is installed
+    if (class_exists(CommandDataCollector::class)) {
```
Comment (chalasr) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/collectors.php]: This config file must not define services conditionally, definition needs to be removed from FrameworkExtension instead which has an `hasConsole()` method for this purpose.

**Review by chalasr — CHANGES_REQUESTED** [review]
Thanks for the PR! Please add a test case for this if possible e.g. in FrameworkExtension

**Comment by chalasr** [comment]
> Question: The name has a . prefix it seams wrong?

It's on purpose: the dot prefix makes it a hidden service. From https://symfony.com/doc/current/bundles/best_practices.html#services:

> If there is no intention for the service id to be used by the end user, you can mark it as hidden by prefixing it with a dot (e.g. .acme_blog.logger). This prevents the service from being listed in the default debug:container command output.

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/collectors.php (hunk 1 above)
Comment (gimler) [reply src/Symfony/Bundle/FrameworkBundle/Resources/config/collectors.php]: i change the code

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
> Please add a test case for this if possible e.g. in FrameworkExtension

Still welcome

**Comment by nicolas-grekas** [comment]
Thank you @gimler.

**Comment by nicolas-grekas** [comment]
Thank you @gimler.
