### PR TITLE
[ObjectMapper] Fix #[Map] attribute breaking auto-mapping of other properties

### LINKED ISSUE #63641: Using #[Map] on a single property disables auto-mapping for other properties
### Symfony version(s) affected

8.1.x-dev

### Description

When mapping a Resource to an Entity, properties are auto-mapped when having the same name. However, if one of theses props has the Map attribute, auto-mapping of other props does not work anymore.

It seems that the problem lies with symfony/object-mapper/Metadata/ReverseClassObjectMapperMetadataFactory.php, in the create method : 

            foreach ($attributes as $attribute) {
                $map = $attribute->newInstance();
                // We're forcing the target on a reverse mapping to the property name, doesn't make sense without a source
                if ($map->source) {
                    $mappings[] = new Mapping($reflProperty->getName(), $map->source, $map->if, $map->transform);
                }

### How to reproduce

I made a demo project to reproduce this issue (and some other for which I'll post later) : https://github.com/olinox14/symfony-objectmapper-issues

Clone the repo, then checkout the branch `issue-63641`

Everything to setup the docker project should be in the readme.

Once the project is up and the db created and populated, you should be able to get a Store item with : 

```
curl --location --request GET 'https://local.api.objectmapper.net/api/stores/1' \
--header 'Content-Type: application/ld+json' \
--data-raw ''
```

Everything is ok for now.

Then modify Api/Resource/Store.php like this : 

    #[Map(source: 'published')]
    public ?bool $published = null;

And send the get request again, you should get this error : 

    The property \"App\\Api\\Resource\\Store::$id\" is not readable because it is typed \"int\". You should initialize it or declare a default value instead.

Same error if you uncomment the $email property in the same Store resource.

In fact, the mapper now only set the published property, ignoring the others. 

### Possible Solution

I made up some workaround that seems to do the job, but I'm not sure if it could have any undesired side effect : 

            foreach ($attributes as $attribute) {
                $map = $attribute->newInstance();

                if (!$map->source) {
                    continue;
                }

                // Extract root property from expressions like "contact?.email" or "contact.email"
                $sourceRoot = explode('.', str_replace('?.', '.', $map->source))[0];

                if ($sourceRoot !== $property) {
                    continue;
                }

                $mappings[] = new Mapping($reflProperty->getName(), $map->source, $map->if, $map->transform);
            }

I can propose a PR if the fix seems ok to you?

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Amoifr**
| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63641
| License       | MIT

## Summary

When a target class has one property with `#[Map(source: '...')]`, the `ReverseClassObjectMapperMetadataFactory` was returning that mapping for ALL properties, preventing auto-mapping of properties with the same name.

**Before (bug):**
```php
#[Map(source: SourceEntity::class)]
class TargetResource {
    public ?int $id = null;           // ❌ Not auto-mapped (stays null)
    public ?string $name = null;       // ❌ Not auto-mapped (stays null)
    
    #[Map(source: 'published')]
    public ?bool $isPublished = null;  // ✓ Works
}
```

**After (fix):**
All three properties are correctly mapped.

## Changes

- Filter mappings in `ReverseClassObjectMapperMetadataFactory::create()` to only return those where the source matches the requested property name
- Support for nested property expressions like `contact.email` or `contact?.email`
- Added test case `testClassMapWithSourceAttributeDoesNotBreakAutoMapping`

### CODE REVIEW

**Review by Spomky — APPROVED** [review]
Many thanks.
Looks good to me.

**Review by welcoMattic — APPROVED** [review]

File: src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php [hunk 1]
```diff
@@ -825,6 +826,26 @@ public function testClassMapWithSourceAttribute()
...
+        ];
+
+        $cost = new Cost(10, 20, 'bar');
+
+        $mapper = new ObjectMapper(new ReverseClassObjectMapperMetadataFactory(new ReflectionObjectMapperMetadataFactory(), $classMap));
+
+        $costRequestView = $mapper->map($cost);
+
+        $this->assertInstanceOf(CostRequestWithSourceAndAutoMappedView::class, $costRequestView);
+        // Explicit mapping should work
```
Comment (alexandre-daubois) [inline src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php]: I'd rather have this kind of comment in the assertion message, if really necessary

File: src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php [hunk 2]
```diff
@@ -825,6 +826,26 @@ public function testClassMapWithSourceAttribute()
...
+        $this->assertEquals('bar', $costRequestView->foo);
+        // Auto-mapping should also work for properties with the same name
```
Comment (alexandre-daubois) [inline src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php]: Same here

File: src/Symfony/Component/ObjectMapper/Tests/Fixtures/ClassMap/CostRequestWithSourceAndAutoMappedView.php [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+ */
+#[Map(source: Cost::class)]
+final class CostRequestWithSourceAndAutoMappedView
+{
+    public ?int $amount = null;  // Should be auto-mapped (same name as source)
+    public ?int $tax = null;     // Should be auto-mapped (same name as source)
+
+    #[Map(source: 'bar')]
+    public ?string $foo = null;  // Explicit mapping from 'bar' to 'foo'
+}
```
Comment (alexandre-daubois) [inline src/Symfony/Component/ObjectMapper/Tests/Fixtures/ClassMap/CostRequestWithSourceAndAutoMappedView.php]: Please add a blank line at the end of this file. Thanks!

File: src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php (hunk 1 above)
Comment (Amoifr) [reply src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php]: Done! Moved to assertion message.

File: src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php (hunk 2 above)
Comment (Amoifr) [reply src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php]: Done!

File: src/Symfony/Component/ObjectMapper/Tests/Fixtures/ClassMap/CostRequestWithSourceAndAutoMappedView.php (hunk 3 above)
Comment (Amoifr) [reply src/Symfony/Component/ObjectMapper/Tests/Fixtures/ClassMap/CostRequestWithSourceAndAutoMappedView.php]: Done! Added trailing newline.

**Comment by Amoifr** [comment]
Thanks @alexandre-daubois for the review! 🙏

Fixed all three points:
- Moved comments to assertion messages
- Added trailing newline

Ready for another look when you have a moment!

File: src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php [hunk 4]
```diff
@@ -62,9 +62,19 @@ public function create(object $object, ?string $property = null, array $context
...
                 $map = $attribute->newInstance();
                 // We're forcing the target on a reverse mapping to the property name, doesn't make sense without a source
-                if ($map->source) {
-                    $mappings[] = new Mapping($reflProperty->getName(), $map->source, $map->if, $map->transform);
+                if (!$map->source) {
+                    continue;
                 }
+
+                // Extract root property from expressions like "contact?.email" or "contact.email"
+                $sourceRoot = explode('.', str_replace('?.', '.', $map->source))[0];
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php]: do we really need to explode on `.`? It looks like this is a bit ouside of our scope here, and I don't see any tests reflecting this behavior.

**Review by soyuka — APPROVED** [review]
The bug fix is real, just a small concern about the `.` handling.

File: src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php (hunk 4 above)
Comment (Amoifr) [reply src/Symfony/Component/ObjectMapper/Metadata/ReverseClassObjectMapperMetadataFactory.php]: Good catch — you're right, the `.`/`?.` handling extends the scope beyond #63641 and isn't covered by any test in this PR. Simplified to a straight `$map->source !== $property` comparison in c9f94cf872e. If we ever want to support nested-path mappings here (matching what `PropertyAccessor` already resolves on read), it can come in a dedicated PR with its own tests. Thanks for the review!

**Comment by nicolas-grekas** [comment]
Thank you @Amoifr.
