### PR TITLE
[Routing] Deal with hosts per locale

### LINKED ISSUE #30617: [Routing] Implement host per locale
**Description**  
Be able to configure host per locale in the same way that we can configure prefix per locale.
Thus we will be able to indicate that the 
- url beginning with www.website.es matches the locale **es** (spanish)
- url beginning with www.website.be/nl/ matches the locale is **nl_BE** (dutch of BELGIUM)

**History**  
[Prefix/path per locale is possibe from Symfony 4.1](https://symfony.com/blog/new-in-symfony-4-1-internationalized-routing). Development has been done in that [PR](https://github.com/symfony/symfony/pull/26143).

**Vocabulary used**
In www.website.be/nl/offers/index.html :
- host:  `www.website.be`
- path-prefix: `/nl` (can be also named path/folder/directory/prefix)
- full-prefix: www.website.be/nl (host + path-prefix = full-prefix)

**Configuration**
Below are 2 examples of how to configure that, can we agree with one and how it will work ?

1. **Host + path-prefix in same configuration**
Set both the host and path-prefix (full-prefix) : 
```yaml
site:
    resource: '../src/Controller/'
    prefix:
        en: '/site'
        es: '://www.website.es'
        nl_BE: '://www.website.be/nl/'
    type: annotation
```
That above code without `es: '://www.website.es'` row and `://www.website.be` is working in Symfony 4.1

Note that we are using **://** to be able to detect later that the configuration is using a full-prefix and not only a prefix-path.

Questions:

- Must it begin with :// or //  ?
- Extract host from configuration :
  - starts with ":// => it's a full-prefix (host + path-prefix)
  - otherwise => it's only a path prefix
  - in the really specific case that we want to have the following url possible  www.website.com/://www.website.com/site/index.html only specifying the path-prefix the conf will be
```yaml
[...]
    prefix:
        en: '/://www.website.com/site'
```
  - Others solutions to detect that the conf starts with a host ?
    - regex?
    - the conf can only starts with
      - "/" for a path-prefix
      - "://" for a host or full-prefix
      - otherwise, it throws a configuration error
- What happens when the host is also on the non locale level ? (Eg: `@Route(host="www.website.com")` or `host: www.website.com`)
- Should we rename `prefix:`?
- In the above configuration what happens if url starts with `www.website.es/site` ? Throws a configuration error ? Thus mixing configurations will be possible if there is no "host" only configuration.

2. **Host in separate configuration**
```yaml
site:
    resource: '../src/Controller/'
    prefix:
        en: '/site'
        es: '/sitio'
    host:
        es: 'www.website.es'
    type: annotation
```
Questions:
- What happens when both the locale host and non locale host are set  ? Use the 1. locale host - 2. non locale host - 3. Throws an exception

Quick code to implement the feature with 1) conf :
YAMLFileLoader:197
```php
const URL_KEY = '://';
//if the it starts with ://
if (substr($localePrefix, 0, strlen(self::URL_KEY)) === self::URL_KEY) {
  $posFirstSlash = strpos($localePrefix, '/', strlen(self::URL_KEY));
  $localeHost = substr($localePrefix, strlen(self::URL_KEY), $posFirstSlash-strlen(self::URL_KEY));
  $localePrefix = substr($localePrefix, $posFirstSlash);
  $localizedRoute->setHost($localeHost);
}
```

Related with : 
- https://github.com/symfony/symfony/pull/26143
- https://symfony.com/doc/current/routing/hostname_pattern.html
- https://github.com/remmel/JMSI18nRoutingBundle

### PR DESCRIPTION
**Pull request by odolbeau**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #30617
| License       | MIT
| Doc PR        | TODO

Allow to define a different host for each locale in routing.

It's now possible to define this kind of configuration:
```yaml
controllers:
    resource: ../../src/Controller/
    type: annotation
    host:
        fr: www.example.fr
        en: www.example.com
```

It's still possible to define an unique host (`host: wwww.example.com`) and if a host is defined for a given route directly, it's not overridden.

To be done:
- [x] YamlLoader
- [x] XmlLoader
- [x] PhpLoader?
- [x] Documentation
- [x] Changelog

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
What happens when the route defines both localized paths and localized hosts?

> It's still possible to define an unique host (host: wwww.example.com) and if a host is defined for a given route directly, it's not overridden.

I'm not sure this is correct: other attributes (defaults, condition, etc) give precedence to the importing side, isn't it ?

**Comment by odolbeau** [comment]
> What happens when the route defines both localized paths and localized hosts?

Both will be used. I didn't add any test for this case cause TBH I don't know what's the expected behavior.

> I'm not sure this is correct: other attributes (defaults, condition, etc) give precedence to the importing side, isn't it?

You tell me. :) I can remove this behavior ([here](https://github.com/symfony/symfony/pull/36187/files#diff-1116f019010409bff1cd19e3a31e768cR38-R40)) if you think it makes sense.
I added cause someone may want to define a totally different domain for a given route.
It's doable by adding another rule in configuration so giving precedence to the importing side is not a problem.

**Comment by nicolas-grekas** [comment]
> I didn't add any test for this case cause TBH I don't know what's the expected behavior.

can you please add one? the behavior should be that we synchronize both path and host to create only one route for the locale, that matches host *and* path, both at the same time.

> I can remove this behavior (here) if you think it makes sense.

I confirm, see [this line](https://github.com/symfony/symfony/pull/36187/files#diff-1116f019010409bff1cd19e3a31e768cR28) that already has the correct precedence. It would make no sense to have precedence vary by type of declaration I think.

**Comment by odolbeau** [comment]
Tests updated.
@nicolas-grekas tell me if they're OK for you, if it's the case, I'll implement them for xml & php aswell and we'll focus on the implementation once done if you're OK (I need to take a look more closely to the prefixes implementation to know how to deal with hosts properly). :)

File: src/Symfony/Component/Routing/Loader/Configurator/Traits/LocalizedRouteTrait.php [hunk 1]
```diff
@@ -26,13 +26,13 @@ trait LocalizedRouteTrait
      * Creates one or many routes.
      *
      * @param string|array $path the path, or the localized paths of the route
-     *
-     * @return Route|RouteCollection
      */
-    final protected function createLocalizedRoute(RouteCollection $collection, string $name, $path, string $namePrefix = '', array $prefixes = null)
+    final protected function createLocalizedRoute(RouteCollection $collection, string $name, $path, string $namePrefix = '', array $prefixes = null): RouteCollection
```
Comment (odolbeau) [inline src/Symfony/Component/Routing/Loader/Configurator/Traits/LocalizedRouteTrait.php:30]: As this trait is marked as external, is it ok to add a strict return type or should I only update the PHPDoc?

File: src/Symfony/Component/Routing/Loader/schema/routing/routing-1.0.xsd [hunk 2]
```diff
@@ -45,6 +45,7 @@
     <xsd:sequence>
       <xsd:group ref="configs" minOccurs="0" maxOccurs="unbounded" />
       <xsd:element name="path" type="localized-path" minOccurs="0" maxOccurs="unbounded" />
+      <xsd:element name="host" type="localized-path" minOccurs="0" maxOccurs="unbounded" />
```
Comment (odolbeau) [inline src/Symfony/Component/Routing/Loader/schema/routing/routing-1.0.xsd:48]: Should I create a `localized-route` type or is it OK to reuse this one?

File: src/Symfony/Component/Routing/composer.json [hunk 3]
```diff
@@ -18,6 +18,7 @@
     "require": {
         "php": "^7.2.5",
         "symfony/deprecation-contracts": "^2.1",
+        "symfony/polyfill-php73": "^1.9",
```
Comment (odolbeau) [inline src/Symfony/Component/Routing/composer.json:21]: Needed to use `array_key_first` in `XmlFileLoader`: https://github.com/symfony/symfony/pull/36187/files#diff-d759b630af7ee68956cf54745e871ee5R317

**Comment by odolbeau** [comment]
Looks like all implementations (xml, yaml & php) are working now. :)
For tests, I use a route file container 3 routes: 1 without host nor path, 1 with a single host, 1 with 2 hosts & 2 paths.
This file is imported 4 times: without any host, with only 1 host, with several hosts & with both hosts & locales (prefixes)
I tried to be as exhaustive as possible for those tests, tell me if I forget something.

Now waiting for your reviews! :)

**Comment by welcoMattic** [comment]
Thanks @odolbeau for your work!
I tested it [here](https://github.com/welcoMattic/test-hosts) with a replication of a real-life case based on a client project, and it works like a charm :ok_hand:

File: src/Symfony/Component/Routing/Loader/Configurator/ImportConfigurator.php [hunk 4]
```diff
@@ -59,4 +60,18 @@ public function __destruct()
...
+    /**
+     * Sets the host to add to use for all child routes.
+     *
+     * @param string|array $host the host, or the localized hosts
+     *
+     * @return $this
+     */
+    final public function host($host): self
+    {
+        $this->addHost($this->route, $host);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Routing/Loader/Configurator/ImportConfigurator.php:73]: will this work correctly if ppl call `host()` before `prefix()`?

**Review by nicolas-grekas — COMMENTED** [review]
Looks nice. Here are some questions + suggestions.

File: src/Symfony/Component/Routing/Loader/Configurator/ImportConfigurator.php (hunk 4 above)
Comment (odolbeau) [reply src/Symfony/Component/Routing/Loader/Configurator/ImportConfigurator.php:73]: Yes, this is what is done in tests.

File: src/Symfony/Component/Routing/Loader/Configurator/Traits/HostTrait.php [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+
+            return;
+        }
+
+        if (0 === \count($host)) {
+            return;
+        }
+
+        foreach ($host as $locale => $localeHost) {
+            $host[$locale] = trim(trim($localeHost), '/');
```
[the remark this answers is not in the document]
Comment (odolbeau) [reply src/Symfony/Component/Routing/Loader/Configurator/Traits/HostTrait.php]: Removed (I copy / pasted the `PrefixTrait`)

File: src/Symfony/Component/Routing/Loader/schema/routing/routing-1.0.xsd [hunk 6]
```diff
@@ -32,6 +32,14 @@
     </xsd:simpleContent>
   </xsd:complexType>
 
+  <xsd:complexType name="faculative-localized-path">
```
[the remark this answers is not in the document]
Comment (odolbeau) [reply src/Symfony/Component/Routing/Loader/schema/routing/routing-1.0.xsd]: definitively right! :+1:

**Review by welcoMattic — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]
sweet thanks

**Comment by nicolas-grekas** [comment]
Just one thing: can you please rebase and update the changelog of the component?

**Comment by odolbeau** [comment]
> Just one thing: can you please rebase and update the changelog of the component?

Done! :+1:

File: src/Symfony/Component/Routing/CHANGELOG.md [hunk 7]
```diff
@@ -11,6 +11,7 @@ CHANGELOG
  * deprecated the `RouteCompiler::REGEX_DELIMITER` constant
  * added `ExpressionLanguageProvider` to expose extra functions to route conditions
  * added support for a `stateless` keyword for configuring route stateless in PHP, YAML and XML configurations.
+ * added "hosts" option to configure the host per locales.
```
Comment (fabpot) [inline src/Symfony/Component/Routing/CHANGELOG.md:14]: added the "hosts" option to be able to configure the host per locale.

**Review by fabpot — CHANGES_REQUESTED** [review]
LGTM, made a minor comment on the CHANGELOG entry.

**Comment by odolbeau** [comment]
Documentation available here: https://github.com/symfony/symfony-docs/pull/13571

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @odolbeau.

**Comment by seb-jean** [comment]
Hello @odolbeau ,

Could it work with the subdomain system?

With the files below, will it be possible to have
- www.example.fr/blog
- admin.example.fr

Thanks :)

Here are my different files:

```yaml
# config/routes/annotations.yaml
controllers:
     resource: ../../src/Controller/
     type: annotation
     host:
         fr: www.example.fr
         en: www.example.com
```

```php
// src/Controller/BlogController.php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class BlogController extends AbstractController
{
    /**
     * @Route("/blog", name="blog_list")
     */
    public function list()
    {
        // ...
    }
}
```

```php
// src/Controller/Admin/BlogController.php
namespace App\Controller\Admin;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class BlogController extends AbstractController
{
    /**
     * @Route("/", name="admin_index", host="admin")
     */
    public function index()
    {
        // ...
    }
}
```
