### PR TITLE
[PropertyInfo] Fix breaking change with has*(arguments...) methods

### LINKED ISSUE #39885: [PropertyInfo] BC break in ReflectionExtractor::isReadable introduced in Symfony 5.1
**Symfony version(s) affected**: 5.1.0+

**Description**
There's a class with method `hasProvince(Province $province): bool` which checks whether a given province exists in a list.

Calling `ReflectionExtractor::isReadable($class, 'province')` returns different results:
 - in Symfony 4.4 and 5.0: `false` - there's a check that requires this has* method to require 0 arguments
 - in Symfony 5.1 and higher: `true` - that check is missing

**How to reproduce**  
I've created a reproduced in this repository: https://github.com/pamil/SymfonyPropertyInfoReproducer
There's a `test.php` file that performs a few assertions and GitHub Actions set up which show that the BC break exists:
https://github.com/pamil/SymfonyPropertyInfoReproducer/actions/runs/494310508

**Possible Solution**  
I guess bringing back that check to `isReadable` - but I'm not sure what that 5.0 -> 5.1 refactor was for so I don't understand how it works yet.

### PR DESCRIPTION
**Pull request by YaFou**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39885
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Until 5.0:
```php
class Dummy
{
    private $elements;

    public function hasElement($element): bool
    {
        // ...
    }
}

$extractor = new ReflectionExtractor();
$extractor->isReadable('Dummy', 'element'); // false
```

After 5.0:
```php
class Dummy
{
    private $elements;

    public function hasElement($element): bool
    {
        // ...
    }
}

$extractor = new ReflectionExtractor();
$extractor->isReadable('Dummy', 'element'); // true => BREAKING CHANGE
```

### CODE REVIEW

File: src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php [hunk 1]
```diff
@@ -239,10 +239,12 @@ public function getReadInfo(string $class, string $property, array $context = []
         foreach ($this->accessorPrefixes as $prefix) {
             $methodName = $prefix.$camelProp;
 
-            if ($reflClass->hasMethod($methodName) && ($reflClass->getMethod($methodName)->getModifiers() & $this->methodReflectionFlags)) {
+            if ($reflClass->hasMethod($methodName)) {
```
Comment (dunglas) [inline src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php]: Couldn't you add the check for existing parameters directly in this `if`?

Comment (YaFou) [reply src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php]: If I inline all conditions on a single line, the line is really long. But if you want, no problem!

Comment (OskarStark) [reply src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php]: Yes please 👍🏻

Comment (YaFou) [reply src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php]: Done

**Comment by pamil** [comment]
It solves the issue for me (#39885), thanks! Travis CI build for PHP 8.0 is failing due to some networking issues, could it be restarted? Same for AppVeyor, it seems like an unrelated failure.

**Comment by xabbuh** [comment]
@pamil CI restarted and green

**Review by xabbuh — APPROVED** [review]

**Review by dunglas — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you @YaFou.
