### PR TITLE
[Translation] [Bridge] [Lokalise] Fix push keys to lokalise. Closes #…

### LINKED ISSUE #44444: [Translations] Lokalise adapter is working incorrect
### Symfony version(s) affected

At least ^5.3

### Description

I have a large file with translations (about 130 messages) and when I trying to push or pull translations I fail with error:

```
13:21:09 ERROR     [app] Unable to get keys ids from Lokalise: "<html>
<head><title>414 Request-URI Too Large</title></head>
<body>
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
".
```

Due to request is too long as said lokalise server:

```
13:21:08 INFO      [http_client] Request: "GET https://api.lokalise.com/api2/projects/{project_id}/keys?filter_keys=This%20value%20should%20be%20false.%2CThis%20value%20should%20be%20true.%2CThis%20value%20should%20be%20of%20type%20%7B%7B%20type%20%7D%7D.%2CThis%20value%20should%20be%20blank.%2CThe%20value%20you%20selected%20is%20not%20a%20valid%20choice.%2CYou%20must%20select%20at%20least%20%7B%7B {truncated}
```

Because of the adapter is trying to send all keys to lokalise in https://github.com/symfony/symfony/blob/5.3/src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php#L273

### How to reproduce

1. Register lokalise app
2. Register a lot of translations
3. Register translation domain in lokalise config
3. Do `./bin/console t:pull lokalise --force -vvv`
4. Fail

### Possible Solution

Remove lokalise filtering step and filter keys locally.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by olegmifle**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #44444 
| License       | MIT
| Doc PR        | N/A

Fixed issue in #44444 within fix some other problems e.g. 
* localise GET method "keys" return only 100 keys per request by default, max 5000. Fixed it and get all the available keys.
* localise recommend update\create only 500 keys per request but service refuse another chank with error "Your token is currently used to process another request. We do not support concurrent requests.". So I send all keys in one request and it works fine.
* add return types to some methods

### CODE REVIEW

File: src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php [hunk 1]
```diff
@@ -250,43 +250,57 @@ private function updateTranslations(array $keysByDomain, TranslatorBagInterface
...
-            if (200 !== $response->getStatusCode()) {
-                $this->logger->error(sprintf('Unable to create/update translations to Lokalise: "%s".', $response->getContent(false)));
-            }
+        if (200 !== $response->getStatusCode()) {
+            $this->logger->error(sprintf('Unable to create/update translations to Lokalise: "%s".', $response->getContent(false)));
         }
     }
 
-    private function getKeysIds(array $keys, string $domain): array
+    private function getKeysIds(array $keys, string $domain, int $page = 1, int $limit = 5000): array
```
Comment (stof) [inline src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php]: no need to add an argument for the limit, as you never use it with a different value than the default

Comment (olegmifle) [reply src/Symfony/Component/Translation/Bridge/Lokalise/LokaliseProvider.php]: Thank u. I wanted to use it somehow, but now it's actually can be removed. I fixed it.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @olegmifle.
