### PR TITLE
[Yaml] fix lexing strings containing escaped quotation characters

### LINKED ISSUE #37037: Yaml::parse() error on double single quote - malformed inline string
**Symfony version(s) affected**:   "symfony/yaml": "^5.0"

**Description**  
I get an error when trying to parse a Yaml file with the function Yaml::parse()
My file contains this text:

 ```
entries:
  - message: 'No emails received before timeout - Address: ''test@testemail.company.com''
        Keyword: ''Your Order confirmation'' ttl: 50'
    outcome: failed
```

And this is the error message:

```
Malformed inline YAML string: "'No emails received before timeout - Address: ''test@testemail.company.com''" at line 149 (near "message: 'No emails received before timeout - Address: ''test@testemail.company.com''")..
```

Does anyone has any ideas of how to solve this? 
Thank you

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37037
| License       | MIT
| Doc PR        |

### CODE REVIEW

File: src/Symfony/Component/Yaml/Parser.php [hunk 1]
```diff
@@ -750,54 +750,54 @@ private function parseValue(string $value, int $flags, string $context)
                 return Inline::parse($this->lexInlineSequence($cursor), $flags, $this->refs);
             }
 
-            $quotation = '' !== $value && ('"' === $value[0] || "'" === $value[0]) ? $value[0] : null;
-
-            // do not take following lines into account when the current line is a quoted single line value
-            if (null !== $quotation && self::preg_match('/^'.$quotation.'.*'.$quotation.'(\s*#.*)?$/', $value)) {
-                return Inline::parse($value, $flags, $this->refs);
-            }
+            switch ($value[0]) {
```
Comment (stof) [inline src/Symfony/Component/Yaml/Parser.php]: what if `$value` is the empty string ?

Comment (xabbuh) [reply src/Symfony/Component/Yaml/Parser.php]: good point, fixed

File: src/Symfony/Component/Yaml/Parser.php [hunk 2]
```diff
@@ -750,54 +750,54 @@ private function parseValue(string $value, int $flags, string $context)
                 return Inline::parse($this->lexInlineSequence($cursor), $flags, $this->refs);
             }
 
-            $quotation = '' !== $value && ('"' === $value[0] || "'" === $value[0]) ? $value[0] : null;
-
-            // do not take following lines into account when the current line is a quoted single line value
-            if (null !== $quotation && self::preg_match('/^'.$quotation.'.*'.$quotation.'(\s*#.*)?$/', $value)) {
-                return Inline::parse($value, $flags, $this->refs);
-            }
+            switch ($value[0] ?? null) {
```
Comment (stof) [inline src/Symfony/Component/Yaml/Parser.php]: IIRC, PHP 7.+ has optimizations for switch when the cases are all integers or all strings and the type matches. So using `?? ''` instead of `?? null` might be better to avoid a type mismatch in the switch.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.
