### PR TITLE
[FrameworkBundle] preserve dots in query-string when redirecting

### LINKED ISSUE #29664: Query string dot is replaced with underscore by trailing slash URL redirection
**Symfony version(s) affected**: 4.1.9, 4.2.1

**Description**  

Having defined a route without trailing slash in the path,
accessing the URL with a trailing slash automatically redirects to the URL without the trailing slash, but also replaces dots with underscores in the query string parameters names (if any).

**How to reproduce**  

Given the following controller (note: no trailing slash after "foos"):

<details>
<summary>src/Controller/FooController.php</summary>

```php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FooController
{
    /**
     * @Route("/foos", methods={"GET"})
     */
    public function getFoos(Request $request)
    {
        /* Disclaimer: this is quick-and-dirty code. */

        $html = '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body>';
        $html .= '<table border="1">';
        $html .= '<tr><th>expression</th><th>value</th></tr>';
        foreach ([
            '$request->getUri()',
            '$request->getSchemeAndHttpHost().$request->getRequestUri()',
            '$request->getQueryString()',
            '$request->server->get("QUERY_STRING")',
        ] as $expression) {
            $value = eval("return $expression;");
            [$expression, $value] = array_map('htmlspecialchars', [$expression, $value]);
            $html .= "<tr><td><code>$expression</code></td><td><code>$value</code></td></tr>";
        }
        $html .= '</table>';
        $html .= '</body></html>';

        return new Response($html);
    }
}
```

</details>

Then

- http://localhost/foos?nested.prop=bar displays:

  expression | value
  -- | --
  `$request->getUri()` | `http://localhost/foos?nested_prop=bar`
  `$request->getSchemeAndHttpHost().$request->getRequestUri()` | `http://localhost/foos?nested.prop=bar`
  `$request->getQueryString()` | `nested_prop=bar`
  `$request->server->get("QUERY_STRING")` | `nested.prop=bar`

  (i.e. `nested.prop` is transformed to `nested_prop` but there are ways to get the original query string).

- http://localhost/foos/?nested.prop=bar (note: trailing slash after "foos") redirects (301) to http://localhost/foos?nested_prop=bar with trailing slash removed *but also dot replaced with underscore*, which thus displays:

  expression | value
  -- | --
  `$request->getUri()` | `http://localhost/foos?nested_prop=bar`
  `$request->getSchemeAndHttpHost().$request->getRequestUri()` | `http://localhost/foos?nested_prop=bar`
  `$request->getQueryString()` | `nested_prop=bar`
  `$request->server->get("QUERY_STRING")` | `nested_prop=bar`

  i.e. we only have `nested_prop`, the original query string has been lost.

**Additional context**

With 3.4.20,

- http://localhost/foos?nested.prop=bar displays:

  expression | value
  -- | --
  `$request->getUri()` | `http://localhost/foos?nested.prop=bar`
  `$request->getSchemeAndHttpHost().$request->getRequestUri()` | `http://localhost/foos?nested.prop=bar`
  `$request->getQueryString()` | `nested.prop=bar`
  `$request->server->get("QUERY_STRING")` | `nested.prop=bar`

  (i.e. `nested.prop` was preserved).

- http://localhost/foos/?nested.prop=bar (note: trailing slash after "foos") gives a 404 error `No route found for "GET /foos/"` (no automatic redirect).

In all cases, `$request->query->get("nested.prop")` is `null` (not defined) (with 4.1, 4.2 and even 3.4), and we have to use `$request->query->get("nested_prop")` (or parse the original query string) to get `"bar"`.

The real project uses API Platform, which auto-generates resource routes (without trailing slash) and parses the original query string to get nested filters (with dots). The calls with trailing slash are from automated REST clients.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #29664
| License       | MIT
| Doc PR        | -

Requires #37270 to pass.

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/Controller/RedirectController.php [hunk 1]
```diff
@@ -176,4 +186,49 @@ public function __invoke(Request $request): Response
 
         throw new \RuntimeException(sprintf('The parameter "path" or "route" is required to configure the redirect action in "%s" routing configuration.', $request->attributes->get('_route')));
     }
+
+    private static function parseQueryString(string $qs)
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Controller/RedirectController.php:190]: this implementation should be replaced by #37272 when merging up to master (it's exactly the same)

**Review by dunglas — APPROVED** [review]

**Review by gmponos — APPROVED** [review]

**Comment by guilliamxavier** [comment]
Thank you @nicolas-grekas!
