### PR TITLE
[Console] fix profiler with overridden `run()` method

### LINKED ISSUE #61134: Using --profile on a command with run() overriden
### Symfony version(s) affected

Seen in 7.1, still there in 7.4

### Description

Hi there ! 

I have a particular use case for several commands in my project where I want to run the same command multiple times based on different contexts (i.e. switching databases).

In order to do so, I've added an `AbstractLoopCommand` layer where I've overriden the `run()` function to loop through contexts and then execute the command.

The problem is that when I want to use `--profiler` for debugging, the `TraceableCommand` interferes and does not call my overriden `run()` function.

### How to reproduce

I haven't tested it but it's mostly copy/pasted from my project, so it should reproduce my issue.
If needed, I'll try to make a full reproducer project later on.

```php

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

abstract class AbstractLoopCommand extends Command
{
    public function run(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        $contexts = [1, 2, 3];

        $io->progressStart(count($contexts));

        $results = [];
        $code = self::SUCCESS;
        foreach ($contexts as $context) {
            $io->progressAdvance();

            //$this->switchContext($context);

            try {
                $results[] = [$context, parent::run($input, $output)];
            } catch (\Throwable $e) {
                $code = self::FAILURE;
                $results[] = [$context, $e->getMessage() . PHP_EOL . $e->getTraceAsString()];
            }
        }
        $io->progressFinish();
        // print the result
        return $code;
    }
}
```

```php
namespace App\Command;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

#[AsCommand('app:loop:example')]
class LoopExampleCommand extends AbstractLoopCommand
{
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $io->text('Hello world');
        return Command::SUCCESS;
    }
}
```

Then try to run `symfony console app:loop:example --profile`. The command will not execute the `AbstractLoopCommand::run()` so no progressBar will be shown, and a single HelloWorld will be output.

### Possible Solution

To resolve my issue locally, I've changed the following line : 

https://github.com/symfony/symfony/blob/cabe552312ee8b54db95e3882e98624d31ab9f7e/src/Symfony/Component/Console/Command/TraceableCommand.php#L295
to :
```php
            $this->exitCode = $this->command->run($input, $output);
```

TBH, I have no idea if it breaks something elsewhere, but it fixes my issue and I can now have a profile of my looping command.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by vinceAmstoutz**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #61134
| License       | MIT

When a command overrides the `run()` method, using the `--profile` option would bypass this custom logic. This was caused by `TraceableCommand` calling `parent::run()` instead of delegating the call to the decorated command.

This change ensures `$this->command->run()` is called, preserving the overridden logic and allowing the profiler to work as expected.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
The test files are missing the license header.
Did you check branch 6.4? Is it not affected?

**Comment by vinceAmstoutz** [comment]
> The test files are missing the license header. Did you check branch 6.4? Is it not affected?

The missing license headers have been added and yes, version 6.4 is affected, so I changed the target from version 7.2 to version 6.4.

File: src/Symfony/Component/Console/Tests/Command/TraceableCommandTest.php [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+ *
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\Console\Tests\Command;
+
+use Symfony\Bundle\FrameworkBundle\Tests\TestCase;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Tests/Command/TraceableCommandTest.php]: wrong use I think

File: src/Symfony/Component/Console/Tests/Fixtures/AbstractLoopCommand.php [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+            $io->progressAdvance();
+            try {
+                parent::run($input, $output);
+            } catch (\Throwable) {
+                $code = self::FAILURE;
+            }
+        }
+        $io->progressFinish();
+        $output->writeln("\nLoop finished.");
+        return $code;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Tests/Fixtures/AbstractLoopCommand.php]:
```suggestion
        $output->writeln("\nLoop finished.");

        return $code;
```

File: src/Symfony/Component/Console/Tests/Fixtures/LoopExampleCommand.php [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+use Symfony\Component\Console\Input\InputInterface;
+use Symfony\Component\Console\Output\OutputInterface;
+
+#[AsCommand('app:loop:example')]
+class LoopExampleCommand extends AbstractLoopCommand
+{
+    protected function execute(InputInterface $input, OutputInterface $output): int
+    {
+        $output->writeln(' Hello world');
+        return Command::SUCCESS;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Tests/Fixtures/LoopExampleCommand.php]:
```suggestion
        $output->writeln(' Hello world');

        return Command::SUCCESS;
```

File: src/Symfony/Component/Console/Tests/Command/TraceableCommandTest.php (hunk 1 above)
Comment (vinceAmstoutz) [reply src/Symfony/Component/Console/Tests/Command/TraceableCommandTest.php]: Done

File: src/Symfony/Component/Console/Tests/Fixtures/AbstractLoopCommand.php (hunk 2 above)
Comment (vinceAmstoutz) [reply src/Symfony/Component/Console/Tests/Fixtures/AbstractLoopCommand.php]: Done

File: src/Symfony/Component/Console/Tests/Fixtures/LoopExampleCommand.php (hunk 3 above)
Comment (vinceAmstoutz) [reply src/Symfony/Component/Console/Tests/Fixtures/LoopExampleCommand.php]: Done

**Review by chalasr — APPROVED** [review]
Looks good

**Comment by nicolas-grekas** [comment]
Thank you @vinceAmstoutz.

**Comment by HeahDude** [comment]
This breaks the protected functions decoration. We need to either delete some (now useless) code or find another way to fix this.
