### PR TITLE
[Form] Fix precision loss when rounding large integers in `NumberToLocalizedStringTransformer`

### LINKED ISSUE #60947: `NumberToLocalizedStringTransformer` alters big integers
### Symfony version(s) affected

7.3

### Description

**Description**
When a big int (still < PHP_INT_MAX) is processed by `round(int|float $number)` in NumberToLocalizedStringTransformer, its value is altered (loss of precision).

I.e.: round(7609342542501717**57**) --> 7609342542501717**76**

Affects Symfony 7.3 and before

### How to reproduce

Details here : https://github.com/EasyCorp/EasyAdminBundle/issues/6934

### Possible Solution

Add a type check at the beginning of the method. Integers don't need to be rounded.
```php
private function round(int|float $number): int|float
{
    if (is_int($number)) {
        return $number;
    }
    
    // ...
}
```

[fix-bigint-rounding.patch](https://github.com/user-attachments/files/20968998/fix-bigint-rounding.patch)

### Additional Context

- PHP_INT_MAX = 9223372036854775807 (on my servers).
- More details about the issue I face https://github.com/EasyCorp/EasyAdminBundle/issues/6934

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60947
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/NumberToLocalizedStringTransformerTest.php [hunk 1]
```diff
@@ -726,4 +726,16 @@ public static function eNotationProvider(): array
             [1232.0, '1.232e3'],
         ];
     }
+
+    public function testReverseTransformDoesNotCauseIntegerPrecisionLoss()
+    {
+        $transformer = new NumberToLocalizedStringTransformer();
+
+        // Test a large integer that was causing precision loss in the round() method
+        $largeInt = 7609342542501717757; // Use a number that actually loses precision when cast to float
```
Comment (mhbailly) [inline src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/NumberToLocalizedStringTransformerTest.php]: @OskarStark 
wouldn't it be more robust to use a largeInt calculated based on PHP_INT_MAX?
i.e.: $largeInt = PHP_INT_MAX - 1;

Comment (OskarStark) [reply src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/NumberToLocalizedStringTransformerTest.php]: Makes sense

**Comment by OskarStark** [comment]
Failure looks unrelated

**Comment by nicolas-grekas** [comment]
Thank you @OskarStark.

**Comment by nicolas-grekas** [comment]
Sorry I missed that before merge: this breaks on x86, see the windows build.

**Comment by OskarStark** [comment]
I think https://github.com/symfony/symfony/pull/61055 should fix it @nicolas-grekas
