### PR TITLE
[DependencyInjection] Fix `ServiceLocatorTagPass` indexes handling

### LINKED ISSUE #60651: `default_index_method` no longer works with contiguous integers since 7.0
### Symfony version(s) affected

7.2.7

### Description

Worked fine in 6.4, but now it seems to be completely ignored in 7.x. The tagged locator just uses the class name as the key now, ignoring the value returned by `default_index_method`, despite the fact that the method is still called at container compile time. In case it matters, my index method returns in `int`.

### How to reproduce

Tag some services.

```yaml
services:
  _instanceof:
    Org\AbstractUnpacker:
      tags:
        - unpacker
```

Inject services.

```yaml
services:
  Org\Unpacker:
    arguments:
      $unpackers: !tagged_locator
        tag: unpacker
        default_index_method: getVersion
```

```php
namespace Org;

abstract class AbstractUnpacker
{
    abstract public static function getVersion(): int;
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60651 
| License       | MIT

#50578 changed the `ServiceLocatorTagPass`’ behavior so that if the map is a list, its indexes always are replaced by the corresponding reference ID, even if they come from the `PriorityTaggedServiceTrait`. That means if your service map ends up as a list because e.g. your `default_index_method` returned contiguous integers, its indexes will be replaced.

This PR reverts this change so that it works the same than v6.

### CODE REVIEW

**Comment by stof** [comment]
Can you add a test covering the case that broke, to prevent regressions ?

**Comment by MatTheCat** [comment]
Added `testServicesKeysAreKept`.

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/ServiceLocatorTagPassTest.php [hunk 1]
```diff
@@ -201,15 +201,31 @@ public function testIndexedByServiceIdWithDecoration()
...
+    public function testServicesKeysAreKept()
     {
         $container = new ContainerBuilder();
         $container->register('service-1');
         $container->register('service-2');
 
         $locator = ServiceLocatorTagPass::register($container, [
-            new Reference('service-2'),
             new Reference('service-1'),
+            'service-2' => new Reference('service-2'),
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Tests/Compiler/ServiceLocatorTagPassTest.php:254]: I would add a third one that uses a string key with a reference to a different id, to cover more cases

Comment (MatTheCat) [reply src/Symfony/Component/DependencyInjection/Tests/Compiler/ServiceLocatorTagPassTest.php:254]: :+1:  test updated

**Comment by MatTheCat** [comment]
I’m a bit skeptical about the loop replacing indexes with references ID; e.g. `testInheritedKeyOverwritesPreviousServiceWithKey` only passes because of the specific order of the map.

**Comment by nicolas-grekas** [comment]
I think I figured out a better fix. Can you please have a look and update the PR + tests potentially?

<details>

```patch
diff --git a/src/Symfony/Component/DependencyInjection/Attribute/AsTaggedItem.php b/src/Symfony/Component/DependencyInjection/Attribute/AsTaggedItem.php
index 2e649bdeaa..e0a1fd3610 100644
--- a/src/Symfony/Component/DependencyInjection/Attribute/AsTaggedItem.php
+++ b/src/Symfony/Component/DependencyInjection/Attribute/AsTaggedItem.php
@@ -21,7 +21,7 @@ class AsTaggedItem
 {
     /**
      * @param string|null $index    The property or method to use to index the item in the locator
-     * @param int|null    $priority The priority of the item; the higher the number, the earlier the tagged service will be located in the locator
+     * @param int|null    $priority The priority of the item; the higher the number, the earlier the tagged service will be located in the iterator/locator
      */
     public function __construct(
         public ?string $index = null,
diff --git a/src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php b/src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php
index 77a1d7ef8f..e3a4eba275 100644
--- a/src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php
+++ b/src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php
@@ -87,8 +87,7 @@ trait PriorityTaggedServiceTrait
                 if (null === $index && null === $defaultIndex && $defaultPriorityMethod && $class) {
                     $defaultIndex = PriorityTaggedServiceUtil::getDefault($container, $serviceId, $class, $defaultIndexMethod ?? 'getDefaultName', $tagName, $indexAttribute, $checkTaggedItem);
                 }
-                $decorated = $definition->getTag('container.decorator')[0]['id'] ?? null;
-                $index = $index ?? $defaultIndex ?? $defaultIndex = $decorated ?? $serviceId;
+                $index ??= $defaultIndex ??= $definition->getTag('container.decorator')[0]['id'] ?? $serviceId;
 
                 $services[] = [$priority, ++$i, $index, $serviceId, $class];
             }
diff --git a/src/Symfony/Component/DependencyInjection/Compiler/ServiceLocatorTagPass.php b/src/Symfony/Component/DependencyInjection/Compiler/ServiceLocatorTagPass.php
index 81c14ac5cc..6de3e5ed4d 100644
--- a/src/Symfony/Component/DependencyInjection/Compiler/ServiceLocatorTagPass.php
+++ b/src/Symfony/Component/DependencyInjection/Compiler/ServiceLocatorTagPass.php
@@ -54,17 +54,41 @@ final class ServiceLocatorTagPass extends AbstractRecursivePass
             $value->setClass(ServiceLocator::class);
         }
 
-        $services = $value->getArguments()[0] ?? null;
+        $values = $value->getArguments()[0] ?? null;
+        $services = [];
 
-        if ($services instanceof TaggedIteratorArgument) {
-            $services = $this->findAndSortTaggedServices($services, $this->container);
-        }
-
-        if (!\is_array($services)) {
+        if ($values instanceof TaggedIteratorArgument) {
+            foreach ($this->findAndSortTaggedServices($values, $this->container) as $k => $v) {
+                $services[$k] = new ServiceClosureArgument($v);
+            }
+        } elseif (!\is_array($values)) {
             throw new InvalidArgumentException(\sprintf('Invalid definition for service "%s": an array of references is expected as first argument when the "container.service_locator" tag is set.', $this->currentId));
+        } else {
+            $i = 0;
+
+            foreach ($values as $k => $v) {
+                if ($v instanceof ServiceClosureArgument) {
+                    $services[$k] = $v;
+                    continue;
+                }
+
+                if ($i === $k) {
+                    if ($v instanceof Reference) {
+                        $k = (string) $v;
+                    }
+                    ++$i;
+                } elseif (\is_int($k)) {
+                    $i = null;
+                }
+
+                $services[$k] = new ServiceClosureArgument($v);
+            }
+            if (0 === $i) {
+                ksort($services);
+            }
         }
 
-        $value->setArgument(0, self::map($services));
+        $value->setArgument(0, $services);
 
         $id = '.service_locator.'.ContainerBuilder::hash($value);
 
@@ -83,8 +107,12 @@ final class ServiceLocatorTagPass extends AbstractRecursivePass
 
     public static function register(ContainerBuilder $container, array $map, ?string $callerId = null): Reference
     {
+        foreach ($map as $k => $v) {
+            $map[$k] = new ServiceClosureArgument($v);
+        }
+
         $locator = (new Definition(ServiceLocator::class))
-            ->addArgument(self::map($map))
+            ->addArgument($map)
             ->addTag('container.service_locator');
 
         if (null !== $callerId && $container->hasDefinition($callerId)) {
@@ -109,29 +137,4 @@ final class ServiceLocatorTagPass extends AbstractRecursivePass
 
         return new Reference($id);
     }
-
-    public static function map(array $services): array
-    {
-        $i = 0;
-
-        foreach ($services as $k => $v) {
-            if ($v instanceof ServiceClosureArgument) {
-                continue;
-            }
-
-            if ($i === $k) {
-                if ($v instanceof Reference) {
-                    unset($services[$k]);
-                    $k = (string) $v;
-                }
-                ++$i;
-            } elseif (\is_int($k)) {
-                $i = null;
-            }
-
-            $services[$k] = new ServiceClosureArgument($v);
-        }
-
-        return $services;
-    }
 }
```

</details>

**Comment by MatTheCat** [comment]
It seems the only change is the

```php
if (0 === $i) {
    ksort($services);
}
```
bit? It doesn’t affect the tests though.

**Comment by nicolas-grekas** [comment]
There's also the foreach ($this->findAndSortTaggedServices being unprocessed in case the args are TaggedIteratorArgument (which means we respect the order managed by this call)
Not sure that's covered actually.
The ksort is present on 6.4 and it allows aggregating locators that have the same services in when when they're declared as a list.

**Comment by MatTheCat** [comment]
> Not sure that's covered actually.

Will add tests if needed.

Not sure what “aggregating locators” means however?

**Comment by nicolas-grekas** [comment]
> Not sure what “aggregating locators” means however?

if one service defines it needs foo and bar, and another needs bar and foo

**Comment by MatTheCat** [comment]
The reindexing loop impacts more than lists though; that’s what `testInheritedKeyOverwritesPreviousServiceWithKey` tests e.g. If you simply move the `16` reference on top of the map it will fail; is that expected?

**Comment by MatTheCat** [comment]
Just noticed `0 === $i` doesn’t mean the services are declared as a list; shouldn’t this line be `count($services) === $i`? Or `0 !== $i`?

**Comment by nicolas-grekas** [comment]
`count($services) === $i` works for me

**Comment by nicolas-grekas** [comment]
Thank you @MatTheCat.

**Comment by MatTheCat** [comment]
What about `testInheritedKeyOverwritesPreviousServiceWithKey`? If you simply move the `16` reference on top of the map it will fail; is that expected?

**Comment by nicolas-grekas** [comment]
It'd say yes. Such lists of services are weird anyway...
