### PR TITLE
[Validator] : Fix "PHP Warning: Undefined array key 1" in NotCompromisedPasswordValidator

### LINKED ISSUE #46935: NotCompromisedPassword: PHP Warning: Undefined array key 1
### Symfony version(s) affected

5.4.10

### Description

In the NotCompromisedPassword validator a PHP warning will be thrown if a received line from `https://api.pwnedpasswords.com` is empty.

This can be seen on this URL: https://api.pwnedpasswords.com/range/072CB (there is an additional line at the end if the source is viewed in the browser - technically there is an additional `\r\n` at the end of the last result).
This causes a PHP warning (in PHP 8.1) on this line in the `NotCompromisedPasswordValidator`:
https://github.com/symfony/symfony/blob/e1134422d0b036aff4990027c7ee2ed3d9efe5cb/src/Symfony/Component/Validator/Constraints/NotCompromisedPasswordValidator.php#L94

```
Warning: Undefined array key 1
```

It does not appear to be a general problem with the API, because other hashes have no empty line at the bottom, f.e. https://api.pwnedpasswords.com/range/7F965

### How to reproduce

1.  Use the NotCompromisedPassword as a constraint in a form
2. Hardcode the `$url` to https://api.pwnedpasswords.com/range/072CB
3. PHP warning `Undefined array key 1` is shown

### Possible Solution

Possible solutions that I've found:

1: 
Check for an empty line and skip it in the loop like:

```php
if (empty($line)) {
    continue;
}
```

2:
Trim `\r\n` from `$result` before the loop.

3:
Check for the presence of `:` before the `explode` used on the line and skip if it doesn't contain it.

### Additional Context

While I think this should also be fixed by pwnedpasswords.com, I think adding this simple check would make the implementation a little bit more robust against changes or errors in the API like this in the future.

### PR DESCRIPTION
**Pull request by KevinVanSonsbeek**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #46935
| License       | MIT

This PR is made based on #46935.
With this approach the validator will still work if it ends up on a line that does not contain the exploding operator `:`. So other cases than just an empty string are caught with this.

### CODE REVIEW

File: src/Symfony/Component/Validator/Constraints/NotCompromisedPasswordValidator.php [hunk 1]
```diff
@@ -91,6 +91,10 @@ public function validate($value, Constraint $constraint)
         }
 
         foreach (explode("\r\n", $result) as $line) {
+            if (false === strpos($line, ':')) {
```
Comment (derrabus) [inline src/Symfony/Component/Validator/Constraints/NotCompromisedPasswordValidator.php]:
```suggestion
            if (!str_contains($line, ':')) {
```

File: src/Symfony/Component/Validator/Tests/Constraints/NotCompromisedPasswordValidatorTest.php [hunk 2]
```diff
@@ -165,6 +165,30 @@ public function testInvalidPasswordCustomEndpoint()
...
 
+    public function testEndpointWithInvalidValueInReturn()
+    {
+        $returnValue = implode(
+            "\r\n",
+            [
+                '36039744C253F9B2A4E90CBEDB02EBFB82D:5',
+                'This should not break the validator',
+                '3686792BBC66A72D40D928ED15621124CFE:7',
+                "36EEC709091B810AA240179A44317ED415C:2\r\n",
```
Comment (derrabus) [inline src/Symfony/Component/Validator/Tests/Constraints/NotCompromisedPasswordValidatorTest.php]:
```suggestion
                '36EEC709091B810AA240179A44317ED415C:2',
                '',
```
That should make it a bit more obvious which issue we're covering.

File: src/Symfony/Component/Validator/Constraints/NotCompromisedPasswordValidator.php (hunk 1 above)
Comment (codegain) [reply src/Symfony/Component/Validator/Constraints/NotCompromisedPasswordValidator.php]: Doesn't this break compatibility with PHP < 8 as `str_contains` is only available in PHP >= 8?

Comment (KevinVanSonsbeek) [reply src/Symfony/Component/Validator/Constraints/NotCompromisedPasswordValidator.php]: The validator component for 5.4 has a dependency on polyfill-php80, so this is usable.

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @KevinVanSonsbeek.

**Comment by chalasr** [comment]
And congrats on your first contribution to Symfony core 🎉
