### PR TITLE
[WebProfiler] Fix Javascript error when using custom stopwatch categories

### LINKED ISSUE #30745: [BUG][Profiler][Timeline] JS error with custom events/sections
**Symfony version(s) affected**: 4.3-DEV

**Description**  

Looks like #30450 broke the Timeline panel in profiler with sections other than standard symfony ones. I have a custom caching bundle that uses the Stopwatch to measure (and also display in profiler) cache call duration. When the Timeline page loads, it throws JS error because the category `ovrflo_cache` does not exist (as it is not one of the hardcoded ones).

**How to reproduce**  
This controller will reproduce the problem:
```
    public function index(Stopwatch $stopwatch)
    {
        $stopwatch->start('some_name', 'some_category');
        sleep(1);
        $stopwatch->stop('some_name');

        return new Response('</body>');
    }
```
Click on the debug toolbar, go to Timeline, open Dev Tools and you'll see the error.

**Possible Solution**  
I fiddled with the JS in `@WebProfiler/Collector/time.js` and I got it to work. I am ready to submit a PR with my code, but I'm not proud of it. I'm a bit rusty with JS/ES6. If you want me to submit a PR with my fix, let me know. If someone else wants to take a stab at it, the issues I found are with 2 calls
- `Legend.add` cannot find the category in `this.categories`
- `Legend.getClassname` cannot find the category in `this.classnames`
My fix detects those undefined values and adds the category in both places with default values.

**Edit**: I just pushed my fix if anyone wants to take a look at it: https://github.com/ovrflo/symfony/commit/17be20a38614ebdd06238d00726a58d182d035cd

This probably affects any third party bundle that uses the Stopwatch. We should fix this ASAP.

### PR DESCRIPTION
**Pull request by curry684**
Fixes #30745

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #30745
| License       | MIT

Made the getter do lazy creation so it can dynamically adapt to whatever it's given.

### CODE REVIEW

File: src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/time.js [hunk 1]
```diff
@@ -252,7 +252,7 @@ class Legend {
     }
 
     get(category) {
-        return this.categories.find(element => element.value === category);
+        return this.categories.find(element => element.value === category) || this.createCategory(category);
```
Comment (stof) [inline src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/time.js]: wouldn't `this.getClassname(category)` inside `createCategory` also be an issue for unknown categories ? I think it will return `undefined`, which will do weird things when casting it to string to put it in the DOM.

Comment (curry684) [reply src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/time.js]: Well no it's actually fine - it's only used for the class name, which will then be `timeline-category undefined active`, and as such results in the unknown category being rendered in the `undefined` style, so light gray. It serves the purpose and the result is correct.

Comment (stof) [reply src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/time.js]: I suggest updating the method to `return this.classnames[category] || ''` to avoid the weird `undefined` class.

Comment (curry684) [reply src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/time.js]: Fair enough, it's cleaner like that.

**Review by stof — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @curry684.
