### PR TITLE
[Validator] fall back to legacy options handling if configured named arguments do not match

### LINKED ISSUE #61612: [Validator] BC break in Length or Count constraint XML configuration
### Symfony version(s) affected

7.3

### Description

| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tickets       | -
| License       | MIT

Description
-----------

The `Length` or `Count` constraint in XML configuration has a backward compatibility break when using the `value` instead of `exactly` option in Symfony 7.3+.

When using named parameters with `#[HasNamedArguments]` in the Length constraint constructor, the XML loader attempts to pass the value option as a named parameter.

Since `$value` is not a constructor argument, this results in an `"Unknown named parameter $value"` error.

### How to reproduce

Legacy XML configuration (Symfony 7.2):

```xml
<constraint name="Length">
    <option name="value">6</option>
    <option name="group">Foo</option>
</constraint>
```

Current XML configuration (Symfony 7.3+):

```xml
<constraint name="Length">
    <option name="exactly">6</option>
    <option name="group">Foo</option>
</constraint>
```

### Possible Solution

The AbstractLoader now automatically maps the value option to exactly for the `Length` or `Count` constraint.
This ensures backward compatibility with legacy XML configuration while triggering a deprecation notice.

A more abstract solution would be to inspect the constructor of the constraint using reflection.
If the constructor has an `$exactly` parameter but no `$value` parameter, the loader can automatically map the passed value option to exactly:

```php
$constructor = new \ReflectionMethod($className, '__construct');
$params = array_map(fn($p) => $p->getName(), $constructor->getParameters());

if (isset($options['value']) && in_array('exactly', $params, true) && !in_array('value', $params, true)) {
    $options['exactly'] = $options['value'];
    unset($options['value']);
}
```

### Additional Context

Additionally, the current condition only applies when the XML config provides more than one option.

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #61612
| License       | MIT

generalized alternative to #61613

### CODE REVIEW

File: src/Symfony/Component/Validator/Mapping/Loader/AbstractLoader.php [hunk 1]
```diff
@@ -97,7 +97,7 @@ protected function newConstraint(string $name, mixed $options = null): Constrain
                 return new $className($options['value']);
             }
 
-            if (array_is_list($options)) {
+            if (array_is_list($options) || isset($options['value'])) {
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/Mapping/Loader/AbstractLoader.php]: This might be a bit risky if the constraint has a constructor argument named `$value`.

An alternative solution would be wrapping the call further down in a `try` `catch` block like this:

```php
try {
    return new $className(...$options);
} catch (\Error $e) {
    if (str_starts_with($e->getMessage(), 'Unknown named parameter')) {
        return new $className($options);
    }

    throw $e;
}
```

Comment (xabbuh) [reply src/Symfony/Component/Validator/Mapping/Loader/AbstractLoader.php]: in any case, we should deprecate this in 7.4 after merging up

Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/Mapping/Loader/AbstractLoader.php]: let's do it the safest way?

Comment (xabbuh) [reply src/Symfony/Component/Validator/Mapping/Loader/AbstractLoader.php]: done

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Comment by nicolas-grekas** [comment]
Thanks! Follow up welcome on 7.4 :pray:

**Comment by xabbuh** [comment]
the follow-up PR for the deprecation is here: #61791
