### PR TITLE
[HttpKernel] Fix `#[MapUploadedFile]` handling for optional file uploads

### LINKED ISSUE #58590: Cannot use `#[MapUploadedFile]` with optional file
### Symfony version(s) affected

7.1.x

### Description

I'm trying to use `#[MapUploadedFile]` for a POST route with `multipart/form-data`.
When I pass a file it's working as expected, but when I try to make it optional, the test fails because it receives an array while waiting for `null | UploadedFile`.

Is it expected? Maybe I'm just wrongly using the browser client to make a request without files?

### How to reproduce

**Controller**

```php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\MapUploadedFile;
use Symfony\Component\Routing\Annotation\Route;

class UpdateController extends AbstractController
{
    #[Route('/', name: 'update', methods: ['POST'])]
    public function index(
        #[MapUploadedFile]
        ?UploadedFile $file,
    ): JsonResponse {
        dump($file);
        return $this->json('', Response::HTTP_OK);
    }
}
```

**Test**

```php
<?php

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class UpdateControllerTest extends WebTestCase
{
    public function testPictureIsOptionnal(
    ): void {
        $client = static::createClient();
        $crawler = $client->request('POST', '/', [], [], ['CONTENT_TYPE' => 'multipart/form-data']);
        self::assertResponseIsSuccessful();
    }
}
```

**Error**
```
ErrorException: App\Controller\UpdateController::index(): Argument #1 ($uploadedPicture) must be of type ?Symfony\Component\HttpFoundation\File\UploadedFile, array given, called in /var/www/html/vendor/symfony/http-kernel/HttpKernel.php on line 183 in /var/www/html/src/Controller/UpdateController.php:1
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by santysisi**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58590 
| License       | MIT

This PR fixes a bug with the `#[MapUploadedFile]` attribute in routes, where an optional ?UploadedFile parameter does not behave as expected when no file is provided.

### CODE REVIEW

File: src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/UploadedFileValueResolverTest.php [hunk 1]
```diff
@@ -85,7 +85,7 @@ static function () {},
         $resolver->onKernelControllerArguments($event);
         $data = $event->getArguments()[0];
 
-        $this->assertEmpty($data);
```
Comment (santysisi) [inline src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/UploadedFileValueResolverTest.php]: Replaced `assertEmpty` with `assertNull` as Symfony discourages the use of `empty`.

**Comment by santysisi** [comment]
It seems that the error reported by Psalm was resolved in version [7.3](https://github.com/symfony/symfony/commit/f328d6ab3ad10b76ca5e5ce3faaf9f28a0189656). What should I do in cases like this? 🤔

**Comment by OskarStark** [comment]
You can ignore the psalm error for now

**Comment by santysisi** [comment]
Hi 👋 Just checking in, Are there any issues or changes needed for this PR? 🙂
I'm happy to make any updates if required.

Also, the pipeline errors seem unrelated to the changes in this PR.

Thanks!

**Comment by nicolas-grekas** [comment]
Thank you @santysisi.
