### PR TITLE
[ExpressionLanguage] Add support for null coalescing syntax

### LINKED ISSUE #45411: Expression Language package: doesn't handle the absence of the property and an error displays
### Symfony version(s) affected

^6.0

### Description

I'm using [Expression Language Package](https://github.com/symfony/expression-language) with [Laravel Framework](https://laravel.com/docs/8.x)
and I'm sending the rules object and data object to the package as mentioned in the [documentation](https://symfony.com/doc/current/components/expression_language.html#expression-syntax).

The issue is if the rules object checks property which does not exist in the data object the package displays an error.
` 
"message": "Undefined property: App\\RulesEngine\\Conditions\\DataConditions::$scores", 
"exception": "ErrorException",
 `
The idea is that I'm receiving the data object from an API and the object has different properties which not of it is required but I need to evaluate the properties in case of its existence.

I checked the package's code and I found that the code is calling the property directly without checking the existence of the property.

As example,
Rules object => 
`
data.scores = 20 || data.name = "abeer"
`
data object 
`
data['name'] = "abeer";
`
and error will appear `" Undefined property data.scores"`

### How to reproduce

**My rules engine class**
`

        class RulesEngine implements RulesEngineInterface
        {
            /** @var array<string> */
            private array $rules = [];

            public function __construct(public ExpressionLanguage $expressionLanguage)
            {
            }

            /**
            * @inheritdoc
            */
            public function addRules(array $expressions, bool $reset = false): void
            {
                $this->rules = $reset ?  [...$expressions] : [...$this->rules, ...$expressions];
            }

            /**
            * @inheritdoc
            */
            public function validateData(array $data): mixed
            {
                foreach ($this->rules as $rule) {
                    $evaluated = $this->expressionLanguage->evaluate($rule, $data);
                    if (! $evaluated) {
                        return false;
                    }
                }

                return true;
            }
        }
`
**Calling the class to handle rules evaluation**

`

        public function evaluateRules(RulesEngineInterface $rulesEngine, Game $game, array $data): bool
        {
            $rulesEngine->addRules([$game->conditions], true);

            return $rulesEngine->validateData($data);
        }
`

### Possible Solution

instead of return direct access to the property in the object [return line in Evaluate function in call GetAttrNode](https://github.com/symfony/expression-language/blob/7adc90f7f09659606996f78de22830b5a2db5be4/Node/GetAttrNode.php#L78)
check the existence of the property `object_get($obj, $property) !== null` and return false to drop only one rules without stoping the code and keep evaluating the rest of the rules.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mytuny**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #45411, #21691
| License       | MIT
| Doc PR        | symfony/symfony-docs#16743

This is another waited feature for the syntax of the expression-language component. The [null-coalescing](https://wiki.php.net/rfc/isset_ternary) operator ``??`` becomes a need for variant programming needs these days. 

Following my previous PR introducing the null-safe operator (#45795). I'm hereby introducing yet another essential operator to make the syntax even more complete.

The null-coalescing operator is a syntactic sugar for a common use of ternary in conjunction with ``isset()`` (in PHP) or equivalent in other languages. This is such a common use-case to the point that almost all majors programming syntax nowadays support a sort of a short-hand for that operation namely coalescing operator. Now it's time for the syntax of Expression-Language to do so!

Expressions like:

* ``foo.bar ?? 'default'``
* ``foo[3] ?? 'default'``
* ``foo.bar ?? foo['bar'] ?? 'default'``

will default to the expression in the right-hand-side of the ``??`` operator whenever the expression in the left-hand-side of it does not exist or it's ``null``. Note that this coalescing behavior can be chained and the validation logic takes decreasing priority from left to right.

### CODE REVIEW

File: src/Symfony/Component/ExpressionLanguage/Node/CoalescingNode.php [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+namespace Symfony\Component\ExpressionLanguage\Node;
+
+use Symfony\Component\ExpressionLanguage\Compiler;
+
+/**
+ * @author Fabien Potencier <fabien@symfony.com>
+ *
+ * @internal
+ */
+class CoalescingNode extends Node
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ExpressionLanguage/Node/CoalescingNode.php]: NullCoalesceNode to borrow from twig?

File: src/Symfony/Component/ExpressionLanguage/Node/CoalescingNode.php [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+{
+    public function __construct(Node $expr1, Node $expr2)
+    {
+        parent::__construct(
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ExpressionLanguage/Node/CoalescingNode.php]: let's put everything on one line

File: src/Symfony/Component/ExpressionLanguage/Node/CoalescingNode.php [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+
+            return $expr1;
+        } catch (\RuntimeException $e) {
+            return $this->nodes['expr2']->evaluate($functions, $values);
+        }
+    }
+
+    public function toArray()
+    {
+        return ['(', $this->nodes['expr1'], ' ?? ', $this->nodes['expr2']];
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ExpressionLanguage/Node/CoalescingNode.php]: if we put brackets on compile, shouldn't we also put them here, eg `') ?? ('`?

File: src/Symfony/Component/ExpressionLanguage/Node/CoalescingNode.php [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+            ->raw(') ?? (')
+            ->compile($this->nodes['expr2'])
+            ->raw('))')
+        ;
+    }
+
+    public function evaluate(array $functions, array $values)
+    {
+        try {
+            $expr1 = @$this->nodes['expr1']->evaluate($functions, $values);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ExpressionLanguage/Node/CoalescingNode.php]: we should find a way to not have to use the `@` operator, especially because future versions of PHP are turning many such warnings into real `Error`

File: src/Symfony/Component/ExpressionLanguage/Parser.php [hunk 5]
```diff
@@ -178,21 +178,29 @@ protected function parseConditionalExpression(Node\Node $expr)
     {
         while ($this->stream->current->test(Token::PUNCTUATION_TYPE, '?')) {
             $this->stream->next();
-            if (!$this->stream->current->test(Token::PUNCTUATION_TYPE, ':')) {
+            if ($this->stream->current->test(Token::PUNCTUATION_TYPE, '?')) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ExpressionLanguage/Parser.php]: Won't this way of doing it allow a space between both `?`? Can you please have a look? If yes, then we'll need to patch the lexer.

**Review by nicolas-grekas — COMMENTED** [review]
Thanks for working on this!

File: src/Symfony/Component/ExpressionLanguage/Node/CoalescingNode.php (hunk 4 above)
Comment (mytuny) [reply src/Symfony/Component/ExpressionLanguage/Node/CoalescingNode.php]: This is the most challenging part!

File: src/Symfony/Component/ExpressionLanguage/Parser.php (hunk 5 above)
Comment (mytuny) [reply src/Symfony/Component/ExpressionLanguage/Parser.php]: I just verified it!! I think you have a point.. with space in between the tokenizer still interpret it as ``??`` !!
Let's use the Lexer instead.. I'll do the required change (y)

File: src/Symfony/Component/ExpressionLanguage/Node/CoalescingNode.php (hunk 1 above)
Comment (mytuny) [reply src/Symfony/Component/ExpressionLanguage/Node/CoalescingNode.php]: Of course! let's stay consistent with Twig.

File: src/Symfony/Component/ExpressionLanguage/Node/NullCoalesceNode.php [hunk 6]
```diff
@@ -0,0 +1,68 @@
...
+            ->raw(') ?? (')
+            ->compile($this->nodes['expr2'])
+            ->raw('))')
+        ;
+    }
+
+    public function evaluate(array $functions, array $values)
+    {
+        set_error_handler(function ($errno, $errstr) {
+            if (\E_WARNING === $errno) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ExpressionLanguage/Node/NullCoalesceNode.php]: it would be really better if we could remove this error handler and rely on explicit logic instead.
This warning could come from something else, and checking the error message would look like a hack to me.
I suppose we need some cooperation between NullCoalesceNode and GetAttrNode...

File: src/Symfony/Component/ExpressionLanguage/Node/NullCoalesceNode.php [hunk 7]
```diff
@@ -0,0 +1,55 @@
...
+            ->raw(') ?? (')
+            ->compile($this->nodes['expr2'])
+            ->raw('))')
+        ;
+    }
+
+    public function evaluate(array $functions, array $values)
+    {
+        if ($this->nodes['expr1'] instanceof GetAttrNode) {
+            $this->nodes['expr1']->isNullCoalesce = true;
```
Comment (stof) [inline src/Symfony/Component/ExpressionLanguage/Node/NullCoalesceNode.php:42]: what about chained GetAttrNode ?

File: src/Symfony/Component/ExpressionLanguage/Node/NullCoalesceNode.php [hunk 8]
```diff
@@ -0,0 +1,55 @@
...
+        }
+        
+        $expr1 = $this->nodes['expr1']->evaluate($functions, $values);
+        $expr2 = $this->nodes['expr2']->evaluate($functions, $values);
```
Comment (stof) [inline src/Symfony/Component/ExpressionLanguage/Node/NullCoalesceNode.php]: the second expression should not be evaluated if the first one does not evaluate to `null`, to match the behavior of the `??` operator in PHP (and in the compiled mode)

File: src/Symfony/Component/ExpressionLanguage/Node/NullCoalesceNode.php (hunk 7 above)
Comment (mytuny) [reply src/Symfony/Component/ExpressionLanguage/Node/NullCoalesceNode.php:42]: It's already covered by a testcase and it works

File: src/Symfony/Component/ExpressionLanguage/Node/NullCoalesceNode.php (hunk 8 above)
Comment (mytuny) [reply src/Symfony/Component/ExpressionLanguage/Node/NullCoalesceNode.php]: Just did the required update.. there will be no need for the intermediary variables to evaluate both expressions at the same time. Instead, we can place them directly in both-sides of the PHP's `??` native operator.

File: src/Symfony/Component/ExpressionLanguage/Node/NullCoalesceNode.php (hunk 6 above)
Comment (mytuny) [reply src/Symfony/Component/ExpressionLanguage/Node/NullCoalesceNode.php]: @nicolas-grekas I've just pushed a solution to this!

File: src/Symfony/Component/ExpressionLanguage/Node/GetAttrNode.php [hunk 9]
```diff
@@ -97,10 +103,14 @@ public function evaluate(array $functions, array $values)
 
             case self::ARRAY_CALL:
                 $array = $this->nodes['node']->evaluate($functions, $values);
-                if (!\is_array($array) && !$array instanceof \ArrayAccess) {
+                if (!\is_array($array) && !$array instanceof \ArrayAccess && !(null === $array && $this->isNullCoalesce)) {
                     throw new \RuntimeException(sprintf('Unable to get an item of non-array "%s".', $this->nodes['node']->dump()));
                 }
 
+                if ($this->isNullCoalesce) {
+                    return $array[$this->nodes['attribute']->evaluate($functions, $values)] ?? null;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ExpressionLanguage/Node/GetAttrNode.php:130]: This is going to evaluate the key even if $array is null, isn't it?

Comment (mytuny) [reply src/Symfony/Component/ExpressionLanguage/Node/GetAttrNode.php:130]: Technically, YES!
The expression used to evaluate the key is going to be fired. However, I verified with the native syntax that PHP also evaluate the key even when `$array` is null.

For example dumping this expression in native PHP:
`null['key'] ?? 'default';`
will output 'default'.

When the key is retrieved using a dynamic syntax:
```
function evalKey() {return 'key';}
null[evalKey()] ?? 'default';
```
same output will be dumped.

Any exception thrown during key evaluation, will propagate up to the main evaluation level:
 ```
function evalKey() {throw new Exception();}
null[evalKey()] ?? 'default';
```
will throw an Exception.
That's why we should **allow** the key evaluation when `$array` is null to imitate this native behavior.

Comment (nicolas-grekas) [reply src/Symfony/Component/ExpressionLanguage/Node/GetAttrNode.php:130]: That is unexpected! Can you please open an issue on php-src about this? I'd be happy to see what others think about this behavior there!

Comment (mytuny) [reply src/Symfony/Component/ExpressionLanguage/Node/GetAttrNode.php:130]: Done!
=> [Issue #8520](https://github.com/php/php-src/issues/8520)
Let's see what others think..

Comment (nicolas-grekas) [reply src/Symfony/Component/ExpressionLanguage/Node/GetAttrNode.php:130]: Great thanks. Can you please add a test case that ensures tests will break if the behavior changes, either when compiling or when evaluating?

**Review by nicolas-grekas — APPROVED** [review]
~(please apply fabbot's path)~

**Comment by nicolas-grekas** [comment]
Can you please rebase? This conflicts after #46454
Please also double check that the issue fixed in #46454 didn't happen here just in case.

**Comment by kvailas** [comment]
Hello @nicolas-grekas , many many many thanks for working on this one!
Is there a plan to release the new feature within the month or so?
It would be great to know!

**Comment by fabpot** [comment]
@kvailas See https://symfony.com/doc/current/contributing/community/releases.html for more information about our release process.
If this PR is merged in the next couple of months, it will be part of 6.2.

**Comment by kvailas** [comment]
@fabpot actually i am using the expression language library as part of a **non-symfony** based project. Just loading the library in order to use the expression language from its respective repo.

Thanks for your input, appreciated.

**Comment by stof** [comment]
@kvailas this does not change *when* the releases of the components happen (btw, Symfony-based projects also download components from the subtree-split repos)

**Comment by fabpot** [comment]
Can you rebase on current 6.2?

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @mytuny.

**Comment by fabpot** [comment]
FYI, follow-up PR here: #47058

File: src/Symfony/Component/ExpressionLanguage/Tests/ExpressionLanguageTest.php [hunk 10]
```diff
@@ -315,6 +315,44 @@ public function provideInvalidNullSafe()
...
+    public function provideNullCoalescing()
+    {
+        $foo = new class() extends \stdClass {
+            public function bar()
+            {
+                return null;
+            }
+        };
+
+        yield ['foo.bar ?? "default"', null];
```
Comment (syntaxerro) [inline src/Symfony/Component/ExpressionLanguage/Tests/ExpressionLanguageTest.php:345]: yield foo ?? 'default' <- will be red
