### PR TITLE
[PhpUnitBridge] Use triggering class to generate baseline for deprecation messages from DebugClassLoader

### LINKED ISSUE #45943: [PHPUnitBridge] Baseline does not work together with deprecation notices at autoloading time and random execution order of tests
### Symfony version(s) affected

6.0

### Description

We run our tests in random order (`vendor/bin/phpunit --order-by=random`) to detect tests that depend on previous tests. 

This leads to a problem when [deprecations notices are triggered while autoloading](https://symfony.com/doc/current/components/phpunit_bridge.html#deprecation-notices-at-autoloading-time) classes.

For example:
```
  1x: Method "ArrayAccess::offsetUnset()" might add "void" as a native return type declaration in the future. Do the same in implementation "GuzzleHttp\Ring\Future\FutureArray" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in ElasticsearchAnalyzersTest::it_should_analyze_input from Functional\Core\SearchBundle
```

This error is only reported once. 

If you use this together with a baseline, the error is written like this:
```json
{
    "location": "Functional\\Core\\SearchBundle\\ElasticsearchAnalyzersTest::it_should_analyze_input",
    "message": "Method \"ArrayAccess::offsetUnset()\" might add \"void\" as a native return type declaration in the future. Do the same in implementation \"GuzzleHttp\\Ring\\Future\\CompletedFutureArray\" now to avoid errors or add an explicit @return annotation to suppress this message.",
    "count": 1
}
```

The next time this test suit runs, it's not the `ElasticsearchAnalyzersTest` that triggers the first autoload, but another test.

Therefore, the location no longer matches.

### How to reproduce

* Run tests with `vendor/bin/phpunit --order-by=random`
* Make sure your test autoload files that trigger a deprecation
* Use `SYMFONY_DEPRECATIONS_HELPER=generateBaseline=true&amp;baselineFile=./tests/baseline.json&amp;max[total]=0&amp;max[direct]=0&amp;max[self]=0` and run the tests
* Check that the `location` in the baseline is the first that that did the autoload
* Now set `generateBaseline=false` and re-run the test a few times, it will error as soon as your order changes

### Possible Solution

Deprecations that are triggered during autoloading should never specify the `location` key in the baseline.

### Additional Context

- https://github.com/symfony/symfony/issues/34496
- https://github.com/symfony/symfony/pull/37733

### PR DESCRIPTION
**Pull request by leongersen**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45943
| License       | MIT
| Doc PR        | N/A

Fixes #45943 by using the triggering class to generate the baseline for messages from `DebugClassLoader`. 

This would break currently generated baselines, but as #45943 describes, those are broken already when running tests in another order, or when running a sub-/superset of tests.

I'll finish this PR by adding/updating tests if this approach is acceptable.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
That'd work for me, please add tests :)

**Comment by ruudk** [comment]
@leongersen Thanks for working on fixing this problem. Would you be able to add the failing test? It would be super if this problem could be patched. 

You can send me a [Tikkie](https://dutchreview.com/expat/tikkie-netherlands/) for a nice beer / coffee / whatever once this is merged 😉 🙏

**Comment by leongersen** [comment]
I'll try to finish this up next week :)

**Comment by leongersen** [comment]
Alright, I've added tests showing the new behavior and rebased against 5.4. I think I've tricked the pipeline into running the tests using the patched PhpUnit bridge for this PR, but I'm not sure if this is the correct way to do this. It took me a while to figure out how to get the tests to run using the changed bridge locally, too.

**Comment by leongersen** [comment]
@nicolas-grekas / @ruudk  Sorry, I don't mean to nudge, but I'm not sure what the procedure is to report that this is ready for review. I don't think the remaining CI failure is caused by the changes in this PR.

File: src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Deprecation.php [hunk 1]
```diff
@@ -59,6 +60,10 @@ class Deprecation
      */
     public function __construct($message, array $trace, $file)
     {
+        if (isset($trace[2]['class']) && DebugClassLoader::class === $trace[2]['class']) {
```
Comment (fancyweb) [inline src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Deprecation.php]: Shouldn't we do it for `LegacyDebugClassLoader` (old class from symfony/debug) too?

Comment (leongersen) [reply src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Deprecation.php]: Yes, I think so.

**Comment by ruudk** [comment]
> @nicolas-grekas / @ruudk Sorry, I don't mean to nudge, but I'm not sure what the procedure is to report that this is ready for review. I don't think the remaining CI failure is caused by the changes in this PR.

I don't know either, but maybe @xabbuh or @ogizanagi can help getting this reviewed? 🙏

**Comment by ruudk** [comment]
@leongersen could you rebase this PR so that we can get this merged?

**Comment by leongersen** [comment]
Yes, done.

**Comment by ruudk** [comment]
The failure in appveyor is related to `RedisExtIntegrationTest` and not caused by this PR.

**Comment by ruudk** [comment]
@leongersen Oke, the Psalm errors need to be fixed. Are you able to do it? Or do you rather let me fix it on your branch?

**Comment by stof** [comment]
Regarding the reported Psalm error, the one about `LegacyDebugClassLoader` not being defined is OK (as this is about supporting older Symfony version).
For DeprecationGroup not being defined, this look really weird.

**Comment by leongersen** [comment]
I don't know what causes the Psalm error on `DeprecationGroup`. It was already `use`d in all classes before this PR.

**Comment by ruudk** [comment]
I tried to run Psalm locally, but that is extremely tedious to do. There is no `psalm.phar` nor an installer instruction. The baseline seems to be generated on the fly in the CI, before running the code from the branch. Why was this done like this? Wouldn't it be easier if the baseline was part of the repository, and that there was a `psalm` script that can be invoked locally?

**Comment by ruudk** [comment]
@nicolas-grekas Could you review this PR? Do you have an idea what could cause the Psalm error?

**Comment by stof** [comment]
@ruudk generating the baseline on the fly is because we want each PR to report only the new things. The codebase is too far from using Psalm for everything to bother about maintaining a committed baseline (we don't always fix all things reported by psalm, depending on what it reports). This CI job is here as an helper, not as a requirement.

**Comment by ruudk** [comment]
It would be really great if we could proceed with this PR. @leongersen sorry to ask, but could you update this PR one more time?

**Comment by leongersen** [comment]
@ruudk, I've rebased on 5.4. Based on the comments by @stof, I'm not taking action on the Psalm failures.

**Comment by nicolas-grekas** [comment]
Thank you @leongersen.

**Comment by ruudk** [comment]
@leongersen @nicolas-grekas just tested 6.3.2 and it works! I'm so happy to finally to be able to hide the indirect Monolog deprecation 🥳🥳🥳 thanks for your work on this
