### PR TITLE
[HttpFoundation] Rename Request::getContentType to getContentTypeFormat

### LINKED ISSUE #39750: Request::getContentType() method name is confusing
While working on a project where we do *not* use the symfony/serializer directly, I wrote this kind of code in a controller:

```php
            if ('application/json' !== $request->getContentType()) {
                throw new UnsupportedMediaTypeHttpException('Unsupported Media Type');
            }
```

This sample code is simple and stupid, but reading it, it's explicit and understandable.

It took me a few minutes and step debugging to understand why it wasn't working, this method isn't actually returning the content type, (e.g. `application/json` for example), but `symfony/serializer` own `format` value instead (here simply `json`).

My conclusion here is that the serializer component internals is leaking over the request logic, and it should not. Symfony request object is used by many frameworks, as a standalone component. And some Symfony-driven applications don't use the serializer component.

I think that most users will assume while reading the above code that `getContentType()` actually return the `Content-Type` header value, and not a reduction of it that is suitable to only `symfony/serializer`. In my opinion method should be renamed to something such as `getContentFormat()` or `getContentSerializerFormat()`.

### PR DESCRIPTION
**Pull request by MarkPedron**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | yes
| Tickets       | Fix #39750
| License       | MIT
| Doc PR        | TODO

### CODE REVIEW

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 1]
```diff
@@ -1324,8 +1324,19 @@ public function setRequestFormat(?string $format)
 
     /**
      * Gets the format associated with the request.
+     * @deprecated since Symfony 6.1, use getContentTypeFormat instead
      */
     public function getContentType(): ?string
+    {
+        trigger_deprecation('symfony/http-foundation', '6.1', 'The method %s is deprecated, use "getContentTypeFormat" instead.', __METHOD__);
+
+        return $this->getFormat($this->headers->get('CONTENT_TYPE', ''));
```
Comment (wouterj) [inline src/Symfony/Component/HttpFoundation/Request.php]:
```suggestion
        return $this->getContentTypeFormat();
```

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 2]
```diff
@@ -1324,8 +1324,19 @@ public function setRequestFormat(?string $format)
 
     /**
      * Gets the format associated with the request.
+     * @deprecated since Symfony 6.1, use getContentTypeFormat instead
      */
     public function getContentType(): ?string
+    {
+        trigger_deprecation('symfony/http-foundation', '6.1', 'The method %s is deprecated, use "getContentTypeFormat" instead.', __METHOD__);
```
Comment (wouterj) [inline src/Symfony/Component/HttpFoundation/Request.php]:
```suggestion
        trigger_deprecation('symfony/http-foundation', '6.1', 'The method "%s" is deprecated, use "getContentTypeFormat" instead.', __METHOD__);
```

**Review by wouterj — COMMENTED** [review]
Looks good from my point of view :+1:

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 1 above)
Comment (MarkPedron) [reply src/Symfony/Component/HttpFoundation/Request.php]: Fixed (ammended commit)

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 2 above)
Comment (MarkPedron) [reply src/Symfony/Component/HttpFoundation/Request.php]: Fixed, including necessary test changes

**Comment by MarkPedron** [comment]
@wouterj Thank you for your kind feedback.

Sorry for all the updates, I completely forgot to add tests and the necessary deprecation infos.

Should be ready now. The CI failure is very mysterious to me.

**Comment by wouterj** [comment]
No problem! For a first contribution, this is in perfect shape (especially considering changes like this need BC and deprecations and stuff).

**Comment by MarkPedron** [comment]
I made an attempt to make appveyor happy (I think i understood the subsequent deprecation emitted in security/http).
The errors in the php8.0/php8.1 job also seem understandable (the return type patch does not apply, because the code changed). However, they seem unrelated to this PR/issue.

File: src/Symfony/Component/HttpFoundation/Tests/RequestTest.php [hunk 3]
```diff
@@ -78,14 +81,27 @@ public function testIsNoCache()
...
 
         $this->assertNull($contentType);
     }
 
+    public function testGetContentTypeFormat()
+    {
+        $request = new Request();
+        $contentType = $request->getContentTypeFormat();
+
+        $this->assertNull($contentType);
```
Comment (stof) [inline src/Symfony/Component/HttpFoundation/Tests/RequestTest.php]: Would be great to add more tests covering cases where that method returns a non-null value. Otherwise, we don't really have tests for the feature.

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 4]
```diff
@@ -1324,8 +1324,20 @@ public function setRequestFormat(?string $format)
...
+    {
+        trigger_deprecation('symfony/http-foundation', '6.1', 'The method "%s" is deprecated, use "getContentTypeFormat" instead.', __METHOD__);
+
+        return $this->getContentTypeFormat();
+    }
+
+    /**
+     * Gets the format associated with the request.
+     */
+    public function getContentTypeFormat(): ?string
```
Comment (chalasr) [inline src/Symfony/Component/HttpFoundation/Request.php:1350]: I agree with what this aims to fix, but the difference between `getRequestFormat()` and `getFormat()` was already not obvious before this PR. Adding `getContentTypeFormat` makes the API even more confusing. We should probably make the difference clear with PHPDoc at least

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 5]
```diff
@@ -1324,8 +1324,20 @@ public function setRequestFormat(?string $format)
...
      */
     public function getContentType(): ?string
+    {
+        trigger_deprecation('symfony/http-foundation', '6.1', 'The method "%s" is deprecated, use "getContentTypeFormat" instead.', __METHOD__);
+
+        return $this->getContentTypeFormat();
+    }
+
+    /**
+     * Gets the format associated with the request.
```
Comment (ogizanagi) [inline src/Symfony/Component/HttpFoundation/Request.php]:
```suggestion
     * Gets the usual name of the format associated with the request Content-Type mime type.
     *
     * @see Request::$formats
```

?

**Comment by nicolas-grekas** [comment]
Friendly ping @MarkPedron, up to finish this PR? See pending comments + rebase needed.

File: src/Symfony/Component/HttpFoundation/Tests/RequestTest.php (hunk 3 above)
Comment (MarkPedron) [reply src/Symfony/Component/HttpFoundation/Tests/RequestTest.php]: Thank you for the suggestion. I added tests to cover the mime types `application/json` and `text/html`

**Comment by MarkPedron** [comment]
@nicolas-grekas Thanks for the reminder. I added non-null tests as suggested, accepted the suggestion expanding the comment, and rebased. If there is anything else to be done, please let me know. I am hesitating to expand the comments further, as to me the meaning of getContentTypeFormat seems quite clear, and confusion arises from the methods setRequestFormat/getRequestFormat, which (to my understanding) refer to the negotiated format of the _Response_.

File: UPGRADE-6.1.md [hunk 6]
```diff
@@ -27,6 +27,11 @@ FrameworkBundle
    To prevent services resetting after each message the "--no-reset" option in "messenger:consume" command can be set
  * Deprecate not setting the `http_method_override` config option. The default value will change to `false` in 7.0.
 
+HttpFoundation
+--------------
+
+ * Deprecate `Request::getContentType()`, use `Request::getContentTypeFormat()` instead`
```
Comment (ihmels) [inline UPGRADE-6.1.md]: There is a trailing backtick that needs to be removed.

Comment (ihmels) [reply UPGRADE-6.1.md]: And this point needs to be moved to UPGRADE-6.2.md.

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 7]
```diff
@@ -1326,8 +1326,22 @@ public function setRequestFormat(?string $format)
...
      */
     public function getContentType(): ?string
+    {
+        trigger_deprecation('symfony/http-foundation', '6.1', 'The method "%s" is deprecated, use "getContentTypeFormat" instead.', __METHOD__);
+
+        return $this->getContentTypeFormat();
+    }
+
+    /**
+     * Gets the usual name of the format associated with the request Content-Type mime type.
```
Comment (ihmels) [inline src/Symfony/Component/HttpFoundation/Request.php]:
```suggestion
     * Gets the usual name of the format associated with the request's media type (provided in the Content-Type header).
```

**Comment by fabpot** [comment]
Honestly, I don't think this is worth it. Maybe adding copious docblocks to explain what the method does (and a few others like explained in this [comment](https://github.com/symfony/symfony/issues/39750#issuecomment-757207375) would be more efficient).

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @MarkPedron.
