### PR TITLE
[Console] Fix signal handlers not being cleared after command termination

### LINKED ISSUE #61388: SignalRegistry should deregister handlers after command termination
### Symfony version(s) affected

latest

### Description

1) It does not make sense to dispatch a ConsoleSignalEvent after there was a ConsoleTerminateEvent.
2) In case if command ran multiple times, multiple Signal events will be dispatched to the same command.

### How to reproduce

Using Scheduler component, as it utilizes `RunCommandMessage` to subsequently run other commands.
```php
#[AsCommand('app:test:signal')]
#[AsPeriodicTask('1 seconds')]
class SignalTestCommand extends Command implements SignalableCommandInterface
{
    protected int $runCount = 0;

    public function getSubscribedSignals(): array
    {
        return [ \SIGINT ];
    }

    public function handleSignal(int $signal, false|int $previousExitCode = 0): int|false
    {
        printf("Got signal: %d\n", $signal);
        return false;
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        printf("Press Ctrl-C and you will see %d signal events\n", ++$this->runCount);
        return self::SUCCESS;
    }
}
```

```shell
$ bin/console mes:consume -q scheduler_default
Press Ctrl-C and you will see 1 signal events
Press Ctrl-C and you will see 2 signal events
Press Ctrl-C and you will see 3 signal events
Press Ctrl-C and you will see 4 signal events
^CGot signal: 2
Got signal: 2
Got signal: 2
Got signal: 2
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by yoeunes**
| Q | A
|---|---
| Branch? | 6.4
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Issues | Fixes #61388
| License | MIT

This PR fixes a bug where signal handlers would leak in long-running processes (e.g., Scheduler). When the same command was run multiple times, handlers would accumulate, causing a single OS signal to be handled repeatedly.

### CODE REVIEW

File: src/Symfony/Component/Console/SignalRegistry/SignalRegistry.php [hunk 1]
```diff
@@ -24,17 +37,21 @@ public function __construct()
...
+        $previous = pcntl_signal_get_handler($signal);
+
+        if (!isset($this->originalHandlers[$signal])) {
+            $this->originalHandlers[$signal] = $previous;
+        }
 
-            if (\is_callable($previousCallback)) {
-                $this->signalHandlers[$signal][] = $previousCallback;
+        if (!isset($this->signalHandlers[$signal])) {
+            if (\is_callable($previous) && $previous !== [$this, 'handle']) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/SignalRegistry/SignalRegistry.php]:
```suggestion
            if (\is_callable($previous) && [$this, 'handle'] !== $previous) {
```

File: src/Symfony/Component/Console/SignalRegistry/SignalRegistry.php [hunk 2]
```diff
@@ -55,6 +72,40 @@ public function handle(int $signal): void
...
+     * @internal
+     */
+    public function popPreviousHandlers(): void
+    {
+        $popped = $this->signalHandlers;
+        $this->signalHandlers = array_pop($this->stack) ?? [];
+
+        // Restore OS handler if no more Symfony handlers for this signal
+        foreach (array_keys($popped) as $signal) {
+            if (empty($this->signalHandlers[$signal]) && isset($this->originalHandlers[$signal])) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/SignalRegistry/SignalRegistry.php]:
```suggestion
        foreach ($popped as $signal => $handlers) {
            if (!($this->signalHandlers[$signal] ?? false) && isset($this->originalHandlers[$signal])) {
```

**Review by nicolas-grekas — COMMENTED** [review]
Please rebase/retarget for 6.4 since that's a bugfix that applies there.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @yoeunes.
