### PR TITLE
[Messenger] Fix messenger:failed:remove can not remove single message

### LINKED ISSUE #36659: [Messenger] messenger:failed:remove can not remove single message
**Symfony version(s) affected**: 5.1-dev

**Description**  
If we pass single id to messenger:failed:remove command, this error happen:
```
In FailedMessagesRemoveCommand.php line 65:

  count(): Parameter must be an array or an object that implements Countable 

messenger:failed:remove [--force] [--show-messages] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <id>...
```

**How to reproduce**  

```
$application = new Application($this->kernel);
$application->setAutoExit(false);

$output = new BufferedOutput();
$code = $application->run(new ArrayInput([
    'command' => 'messenger:failed:remove',
    'id' => $id,
    '--force' => true,
]), $output);

dump($output->fetch());
```

**Possible Solution**  
Cast id argument to array:
```
$ids = (array) $input->getArgument('id');
```

**Additional context**  

This error happen with CommandTester also:
```
$command = new FailedMessagesRemoveCommand(
    'failure_receiver',
    $receiver
);

$tester = new CommandTester($command);
$tester->execute(['id' => 20, '--force' => true]);
```

But this error does not happen if I run command from command line:
```
tests/app/bin/console messenger:failed:remove 1 --force
```

### PR DESCRIPTION
**Pull request by tienvx**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36659
| License       | MIT
| Doc PR        | -

Fix this error:
```
count(): Parameter must be an array or an object that implements Countable
```
When calling `messenger:failed:remove` command from other code with single id

### CODE REVIEW

**Comment by tienvx** [comment]
Related to #34980

File: src/Symfony/Component/Messenger/Tests/Command/FailedMessagesRemoveCommandTest.php [hunk 1]
```diff
@@ -19,6 +19,23 @@
...
+        $receiver = $this->createMock(ListableReceiverInterface::class);
+        $receiver->expects($this->once())->method('find')->with(20)->willReturn(new Envelope(new \stdClass()));
+
+        $command = new FailedMessagesRemoveCommand(
+            'failure_receiver',
+            $receiver
+        );
+
+        $tester = new CommandTester($command);
+        $tester->execute(['id' => 20, '--force' => true]);
```
Comment (xabbuh) [inline src/Symfony/Component/Messenger/Tests/Command/FailedMessagesRemoveCommandTest.php:33]: This looks like a wrong execution of the command to me as the argument is declared as an array argument. Does this error only occur when you execute the command programmatically?

**Review by xabbuh — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Messenger/Tests/Command/FailedMessagesRemoveCommandTest.php (hunk 1 above)
Comment (tienvx) [reply src/Symfony/Component/Messenger/Tests/Command/FailedMessagesRemoveCommandTest.php:33]: Yes, it does. But these are reasons why I think it is a bug:
* I worked for me before, at least at versions 5.0.x
* The name `id` and description `Specific message id(s) to remove` of the input argument suggest that I can use single id, but I have to use multiple (array) of ids
* There is a test case for it in 5.0.x (what I am adding in, again)

**Comment by fabpot** [comment]
I agree with @xabbuh that the fix is not correct. The `id` argument is declared as being an array, so an array must be passed. We could fix the validation of the arguments passed to the command when using an ArrayInput instead, that would be better.

**Comment by xabbuh** [comment]
I think I understand the issue now. We changed the type of the argument for 5.1. So the PR that introduced the possibility to specify more than one id broke BC.

**Review by Nyholm — APPROVED** [review]
I think this PR is correct. 

PR https://github.com/symfony/symfony/pull/34980 introduced a BC break to change the type from int to array. It was fine as long as you called the command from the CLI. 

This PR is needed to avoid us releasing this BC break.

**Review by xabbuh — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @tienvx.
