### PR TITLE
[Serializer] Fix unexpected allowed attributes

### LINKED ISSUE #52673: [Serializer] All fields are not included by default, but upon adding any attribute, all fields are then required
### Symfony version(s) affected

6.3.8

### Description

According to https://symfony.com/doc/current/components/serializer.html#ignoring-attributes all properties are included by default, which makes sense. However, this doesn't seem to be the case at least for traits and abstract classes.

When we don't add the `#[Ignore]` attribute in the `TestTrait` in the reproducer, everything works fine. However, adding that attribute causes all of the other properties to now be seen by the serializer and then fail because there is no public access to them via getters or via public properties.

### How to reproduce

https://github.com/nesl247/symfony-serialization-ignore-bug

1) git clone https://github.com/nesl247/symfony-serialization-ignore-bug.git
2) composer install
3) bin/console test:command

### Possible Solution

_No response_

### Additional Context

```[critical] Error thrown while running command "test:command". Message: "Can't get a way to read the property "testProperty2" in class "App\TestMessage"."

In PropertyAccessor.php line 456:
                                                                                    
  Can't get a way to read the property "testProperty2" in class "App\TestMessage".  
                                                                                    
```

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #52673 #49710
| License       | MIT

A more accurate approach than #52680

### CODE REVIEW

**Comment by mtarld** [comment]
fabbot errors aren't related to that PR.

File: src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php [hunk 1]
```diff
@@ -63,21 +64,30 @@ public function hasCacheableSupportsMethod(): bool
...
         if (null !== $this->classDiscriminatorResolver && $this->classDiscriminatorResolver->getMappingForClass($class)) {
             return true;
         }
 
-        $class = new \ReflectionClass($class);
-        $methods = $class->getMethods(\ReflectionMethod::IS_PUBLIC);
-        foreach ($methods as $method) {
-            if ($this->isGetMethod($method)) {
-                return true;
+        $reflection = new \ReflectionClass($class);
```
Comment (chalasr) [inline src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php]: any specific reason not to cache it?

File: src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php [hunk 2]
```diff
@@ -63,21 +64,30 @@ public function hasCacheableSupportsMethod(): bool
...
+
+        // fallback to "read" to ensure backward compatibility
```
Comment (chalasr) [inline src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php]: Talking about BC while there is no deprecated code path feels weird. Do you plan to deprecate not setting that option explicitly in another PR on the dev branch? If not, I'd say better remove the comment or explain the reasoning otherwise if that fallback is going to be the default forever.

File: src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php [hunk 3]
```diff
@@ -160,4 +181,53 @@ protected function setAttributeValue(object $object, string $attribute, $value,
...
+
+                if ($constructor && $constructor->isPublic()) {
+                    foreach ($constructor->getParameters() as $parameter) {
+                        if ($parameter->getName() === $attribute) {
+                            return true;
+                        }
+                    }
+                }
+            } else {
+                // ensure backward compatibility when no attribute access has been defined
```
Comment (chalasr) [inline src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php]: same

File: src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php [hunk 4]
```diff
@@ -36,22 +36,23 @@
...
 class GetSetMethodNormalizer extends AbstractObjectNormalizer
 {
+    private static $reflectionCache = [];
     private static $setterAccessibleCache = [];
 
     /**
      * {@inheritdoc}
      */
-    public function supportsNormalization($data, string $format = null)
+    public function supportsNormalization($data, string $format = null, array $context = [])
```
Comment (chalasr) [inline src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php]: we took care of introducing the very same parameter smoothly in upper branches (see https://github.com/symfony/serializer/blob/6.3/Normalizer/GetSetMethodNormalizer.php) so I'm not sure we can do it this way

**Review by chalasr — CHANGES_REQUESTED** [review]
As discussed at SymfonyCon, the information (access type) would better transit through a method parameter than a context option since the need is specific to the abstract method at hand

**Comment by mtarld** [comment]
Once this PR will be upmerged to 7.1, I'll create a new one to trigger the proper deprecations.

**Review by chalasr — APPROVED** [review]

**Review by nicolas-grekas — COMMENTED** [review]
The implementation fits the definition of a new feature to me: adding an argument on a constructor, and adding an argument on public/protected methods.
This should come with an `@param` annotation for methods, and this will yield a new deprecation.
Maybe another approach is possible? I don't know at all :)

**Comment by chalasr** [comment]
That read/write mode do need to be passed throughout method calls to fix the bug at hand, so the plan here is to make it a parameter that's hidden at first on 5.4, then make it virtual on 7.1 and finally make it real on 8.0.
The only alternative I can think of is to put the info in `$context` instead. 

@mtarld would that work conceptually and technically?

**Comment by mtarld** [comment]
It appears that it works indeed, and it is much better thanks!

I'm wondering if we should make that read/write information explicit in 7.1, maybe a context value like here is enough (but it is less secure).

**Comment by nesl247** [comment]
Is there a chance this merges soon? We're actually stuck on an older version of api platform that accidentally stopped this bug from happening but the newer version removed that code.

If not we may move forward with applying the changes via a patch in our project. Just trying to figure out the right path for us.

Thanks!

File: src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php [hunk 5]
```diff
@@ -63,22 +64,28 @@ public function hasCacheableSupportsMethod(): bool
...
 
+        $reflection = self::$reflectionCache[$class];
+
+        do {
+            foreach ($reflection->getMethods(\ReflectionMethod::IS_PUBLIC) as $reflectionMethod) {
+                if ($readAttributes && $this->isGetMethod($reflectionMethod) || !$readAttributes && $this->isSetMethod($reflectionMethod)) {
+                    return true;
+                }
+            }
+        } while ($reflection = $reflection->getParentClass());
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php]: this loop is not needed if we scan only public methods

File: src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php [hunk 6]
```diff
@@ -63,22 +64,28 @@ public function hasCacheableSupportsMethod(): bool
...
-            }
+        if (!isset(self::$reflectionCache[$class])) {
+            self::$reflectionCache[$class] = new \ReflectionClass($class);
         }
 
+        $reflection = self::$reflectionCache[$class];
+
+        do {
+            foreach ($reflection->getMethods(\ReflectionMethod::IS_PUBLIC) as $reflectionMethod) {
+                if ($readAttributes && $this->isGetMethod($reflectionMethod) || !$readAttributes && $this->isSetMethod($reflectionMethod)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php]:
```suggestion
                if ($readAttributes ? $this->isGetMethod($reflectionMethod) : $this->isSetMethod($reflectionMethod)) {
```

File: src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php [hunk 7]
```diff
@@ -160,4 +178,49 @@ protected function setAttributeValue(object $object, string $attribute, $value,
...
+            if ($context['_read_attributes'] ?? true) {
+                foreach (['get', 'is', 'has'] as $getterPrefix) {
+                    $getter = $getterPrefix.ucfirst($attribute);
+                    $reflectionMethod = $reflection->hasMethod($getter) ? $reflection->getMethod($getter) : null;
+                    if ($reflectionMethod && $this->isGetMethod($reflectionMethod)) {
+                        return true;
+                    }
+                }
+            } else {
+                $setter = 'set'.ucfirst($attribute);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php]:
```suggestion
                $setter = 'set'.$attribute;
```

File: src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php [hunk 8]
```diff
@@ -160,4 +178,49 @@ protected function setAttributeValue(object $object, string $attribute, $value,
...
+                $reflectionMethod = $reflection->hasMethod($setter) ? $reflection->getMethod($setter) : null;
+                if ($reflectionMethod && $this->isSetMethod($reflectionMethod)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php]:
```suggestion
                if ($reflection->hasMethod($setter) && $this->isSetMethod($reflection->getMethod($setter))) {
```

File: src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php [hunk 9]
```diff
@@ -160,4 +178,49 @@ protected function setAttributeValue(object $object, string $attribute, $value,
...
+
+                if ($constructor && $constructor->isPublic()) {
+                    foreach ($constructor->getParameters() as $parameter) {
+                        if ($parameter->getName() === $attribute) {
+                            return true;
+                        }
+                    }
+                }
+            }
+        } while ($reflection = $reflection->getParentClass());
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php]: do we deal only with public methods? if yes, we don't need this loop (please confirm that aspect is tested)

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php [hunk 10]
```diff
@@ -174,4 +180,19 @@ protected function getAllowedAttributes($classOrObject, array $context, bool $at
...
+            return false;
+        }
+        $class = \is_object($classOrObject) ? \get_class($classOrObject) : $classOrObject;
+
+        if ($context['_read_attributes'] ?? true) {
+            return $this->propertyInfoExtractor->isReadable($class, $attribute);
+        }
+
+        return $this->propertyInfoExtractor->isWritable($class, $attribute)
+            || null !== ($writeInfo = $this->propertyInfoExtractor->getWriteInfo($class, $attribute)) && PropertyWriteInfo::TYPE_NONE !== $writeInfo->getType();
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]:
```suggestion
            || ($writeInfo = $this->propertyInfoExtractor->getWriteInfo($class, $attribute)) && PropertyWriteInfo::TYPE_NONE !== $writeInfo->getType();
```

File: src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php (hunk 9 above)
Comment (mtarld) [reply src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php]: Yes it is actually tested. `GetSetDummyChild` stands for that purpose

**Review by maxhelias — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @mtarld.

**Comment by stloyd** [comment]
Those changes generate a big performance drop in one of the projects I work with where we extensively use attributes on DTOs.

Comparing Serializer in version `7.0.6` vs `7.0.7`:
Zrzut ekranu 2024-05-6 o 16 27 33
Zrzut ekranu 2024-05-6 o 16 27 17

**Comment by nicolas-grekas** [comment]
Please open a dedicated issue if you want any follow up.
