### PR TITLE
[VarDumper] Fix test suite with PHP 8.4

### LINKED ISSUE #54180: Enable PHP 8.4 in the CI and make tests green
### Description

Looks like we can run our CI with PHP 8.4, so let's do it immediately, starting with branch 5.4.
Then let's fix tests :)

### Example

https://github.com/symfony/symfony/actions/runs/8176054351/job/22354611125

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54180
| License       | MIT

Lately, attribute name has been added to `ReflectionAttribute`, which makes messed up with the CI a bit with PHP 8.4. Here is the PR: https://github.com/php/php-src/pull/12917

We can change the current virtual dump property to some "real" one by adding `name` in the caster when it doesn't exist yet. If it already exists, we're running PHP 8.4 or later. This way we avoid having different tests with the different PHP versions.

Should we add something in `ReflectionCaster` to remember to remove this part when the minimal PHP version Symfony requires is >= 8.4 ? If yes, what would be the best "syntax"?

### CODE REVIEW

File: src/Symfony/Component/VarDumper/Caster/ReflectionCaster.php [hunk 1]
```diff
@@ -116,8 +116,11 @@ public static function castType(\ReflectionType $c, array $a, Stub $stub, bool $
 
     public static function castAttribute(\ReflectionAttribute $c, array $a, Stub $stub, bool $isNested)
     {
+        if (!isset($a['name'])) {
+            $a['name'] = $c->getName();
```
Comment (nicolas-grekas) [inline src/Symfony/Component/VarDumper/Caster/ReflectionCaster.php]: but actually this would be lying on PHP < 8.4, this property doesn't exist before, isn't it?

Comment (alexandre-daubois) [reply src/Symfony/Component/VarDumper/Caster/ReflectionCaster.php]: Yes, this is true. I'm sure how to deal with this: either make it non-virtual for on 8.3 and lower (which indeed is a "lie"), or doing some logic for some PHP versions and tweaking expected output of tests to accept both virtual and real property. 🤔

Comment (nicolas-grekas) [reply src/Symfony/Component/VarDumper/Caster/ReflectionCaster.php]: So, on double check, this needs a tweak: on < 8.4, we need to keep the same logic as before, so that the `name`property is displayed as a virtual one.
And on 8.4+, we can keep the public property of course.

File: src/Symfony/Component/VarDumper/Caster/ReflectionCaster.php [hunk 2]
```diff
@@ -116,10 +116,16 @@ public static function castType(\ReflectionType $c, array $a, Stub $stub, bool $
...
-        self::addMap($a, $c, [
+        $map = [
             'name' => 'getName',
             'arguments' => 'getArguments',
-        ]);
+        ];
+
+        if (\PHP_VERSION_ID >= 80400) {
+            unset($map['name']);
+        }
```
Comment (alexandre-daubois) [inline src/Symfony/Component/VarDumper/Caster/ReflectionCaster.php:126]: Unsetting _after_ is needed to keep `name` in first position of the array if it's used

**Comment by nicolas-grekas** [comment]
Thank you @alexandre-daubois.
