### PR TITLE
[Messenger] Added StopWorkerException

### LINKED ISSUE #39491: [RFC][Messenger] allow to shutdown worker "consume" with a particular Exception
**Description**  
Actually, the worker `messenger:consume` catches **all** exceptions and redirects the message to `failure` transport. 
It is problematic, for example, when the worker loses the connection to Redis DB hence the messages on retry flow are failed as the initial message.   
It will be nice to have an exception that will be not catched and will trigger the worker's shutdown.

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #39491
| License       | MIT
| Doc PR        |

### CODE REVIEW

File: src/Symfony/Component/Messenger/Exception/StopWorkerException.php [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+ */
+
+namespace Symfony\Component\Messenger\Exception;
+
+/**
+ * @author Grégoire Pineau <lyrixx@lyrixx.info>
+ */
+class StopWorkerException extends RuntimeException
+{
+    public function __construct($message = 'Worker should stop', ?\Throwable $previous = null)
```
Comment (OskarStark) [inline src/Symfony/Component/Messenger/Exception/StopWorkerException.php]:
```suggestion
    public function __construct(string $message = 'Worker should stop', ?\Throwable $previous = null)
```

**Review by jderusse — COMMENTED** [review]
I'd rather use an interface to let people add behavior on existing Exception (like we do with 
UnrecoverableExceptionInterface)

We already have a mechanism to stop the worker using eventDispatcher. 
This can be used at userland to achieve the same behavior.

```php
class StopWorkerOnCustomLogicListener implements EventSubscriberInterface
{
    private $run = true;
    public function onMessageFailed(WorkerMessageFailedEvent $event): void
    {
        if ($event->getThrowable() instanceof Whatever) {
            $this->run = false;
        }
    }

    public function onWorkerRunning(WorkerRunningEvent $event): void
    {
        if (!$event->isWorkerIdle() && !$this->run) {
            $this->run = true;
            $event->getWorker()->stop();
        }
    }

    public static function getSubscribedEvents(): array
    {
        return [
            WorkerMessageFailedEvent::class => 'onMessageFailed',
            WorkerRunningEvent::class => 'onWorkerRunning',
        ];
    }
}
```

**Comment by lyrixx** [comment]
> I'd rather use an interface to let people add behavior on existing Exception (like we do with
> UnrecoverableExceptionInterface)

I dont follow you, I could create an interface, and implementing it, but what could you add to the Exception? I'll not used anyway

> We already have a mechanism to stop the worker using eventDispatcher.

Yes I know, but this is more complex IMHO. Having something native is way more efficient 
And BTW, 2 people already asked me how do to that :) And the issue receive a good feedback.

**Comment by jderusse** [comment]
> but what could you add to the Exception?

hmm.. nothing, It's just a Marker interface

```php
interface StopWorkerExceptionInterface extends \Throwable
{
}
class StopWorkerException extends RuntimeException implements StopWorkerExceptionInterface
{
}

if ($throwable instanceof StopWorkerExceptionInterface) {
    $this->stop();
}
```

That would allow people use
```php
class MyBusinessException implements StopWorkerExceptionInterface 
{
}
```

Instead of

```php
try {
} catch (MyBusinessException $e) {
    throw new StopWorkerExceptionInterface(??, ??, $e);
}
```

File: src/Symfony/Component/Messenger/Worker.php [hunk 2]
```diff
@@ -113,6 +114,18 @@ private function handleMessage(Envelope $envelope, ReceiverInterface $receiver,
         try {
             $envelope = $this->bus->dispatch($envelope->with(new ReceivedStamp($transportName), new ConsumedByWorkerStamp()));
         } catch (\Throwable $throwable) {
+            if ($throwable instanceof StopWorkerException) {
```
Comment (jderusse) [inline src/Symfony/Component/Messenger/Worker.php]: I already express my opinion about users who **can** use eventListerner to achieve the same behavior.

But I think, if we want providing an easy way to for end-user, we **should ** use eventListener here to avoid adding complexity in the worker

**Comment by chalasr** [comment]
I see how much this can be handy and simple, but throwing such an exception from e.g. a message handler feels weird to me. Stopping the worker is a consequence of an error, not an error on its own.
I agree that hooking into worker lifecycle events sounds better from a design pov. 
Adding a sample listener to the docs like the one showed by @jderusse may be enough to fix this issue and could avoid having several paths for the same goal.

**Comment by lyrixx** [comment]
I agree this PR could leverage the Event Dispatcher System. But messenger could work without messenger, so the exception would become useless... But I think we don't care.

But IMHO this should not be a doc cookbook. The proposed system is really hackish. Many (good) developers did not find it by them-self.

Let's add a native / simple behavior here.

**Comment by lyrixx** [comment]
* I added an interface
* the system uses the Event Dispatch

File: src/Symfony/Component/Messenger/EventListener/StopWorkerOnCustomStopExceptionListener.php [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+    public function onMessageFailed(WorkerMessageFailedEvent $event): void
+    {
+        $th = $event->getThrowable();
+        if ($th instanceof StopWorkerExceptionInterface) {
+            $this->stop = true;
+        }
+        if ($th instanceof HandlerFailedException) {
+            foreach ($th->getNestedExceptions() as $e) {
+                if ($e instanceof StopWorkerExceptionInterface) {
+                    $this->stop = true;
```
Comment (ottaviano) [inline src/Symfony/Component/Messenger/EventListener/StopWorkerOnCustomStopExceptionListener.php:36]: we can `break;` the loop after this action, no?

**Review by ottaviano — COMMENTED** [review]
~~should not we change `HandleMessageMiddleware` instead and avoid to add one listener:~~

up: ok, I saw that it was the previous version 👌 

```php
} catch (\Throwable $e) {
  if ($e instanceof StopWorkerExceptionInterface) {
    throw $e;
  }
  
  $exceptions[] = $e;
}
```

File: src/Symfony/Component/Messenger/EventListener/StopWorkerOnCustomStopExceptionListener.php (hunk 3 above)
Comment (lyrixx) [reply src/Symfony/Component/Messenger/EventListener/StopWorkerOnCustomStopExceptionListener.php:36]: Fixed Thanks

**Review by ottaviano — APPROVED** [review]

**Comment by lyrixx** [comment]
I have rebased this PR and added some tests. There are 9 👍🏼 on the issue, so I do think we should consider to merge this PR

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @lyrixx.
