### PR TITLE
[HttpClient] Fix CurlHttpClient memory leak

### LINKED ISSUE #38492: [HttpClient] Memory leak in CurlHttpClient
**Symfony version(s) affected**: 4.4

**Description**  
The `CurlHttpClient` has a memory leak which seems to have been caused by this PR #35674 .
When an exception occurs the `CurlResponse::close` method never gets called from `__destruct` cause of the PR & the handler never gets unset from the `CurlClientState::$openHandles` & `CurlClientState::$handlesActivity` arrays. Over time this leads to a lot of handlers piling up in the memory, causing a memory leak. I've notice this while using the HttpClient in a Messenger handler.

**How to reproduce**  
```php
class MyMessageHandler implements MessageHandlerInterface
{
    //...

    public function doSomething(MyMessage $myMessage): void
    {
        //...
        try {
            $this->httpClient->request(/*...*/);
        } catch (HttpExceptionInterface $e) {
            //...
        }
    }
}
```

**Additional context**  
image

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38492 
| License       | MIT
| Doc PR        | -

### CODE REVIEW

File: src/Symfony/Contracts/HttpClient/Test/Fixtures/web/index.php [hunk 1]
```diff
@@ -29,7 +29,7 @@
     }
 }
 
-$json = json_encode($vars, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
+$json = json_encode($vars, \JSON_PRETTY_PRINT | \JSON_UNESCAPED_SLASHES | \JSON_UNESCAPED_UNICODE);
```
Comment (stof) [inline src/Symfony/Contracts/HttpClient/Test/Fixtures/web/index.php]: should be reverted

Comment (HypeMC) [reply src/Symfony/Contracts/HttpClient/Test/Fixtures/web/index.php]: Done

File: src/Symfony/Contracts/HttpClient/Test/HttpClientTestCase.php [hunk 2]
```diff
@@ -823,6 +824,28 @@ public function testDestruct()
...
+
+        try {
+            $client->request('GET', 'http://localhost:8057/404/not-json');
+            $this->fail(ClientExceptionInterface::class.' expected');
+        } catch (ClientExceptionInterface $e) {
+            // The response content-type mustn't be json as that calls getContent
+            // @see src/Symfony/Component/HttpClient/Exception/HttpExceptionTrait.php:58
+            $this->assertStringNotContainsString('json', $e->getResponse()->getHeaders(false)['content-type'][0]);
+
+            $r = new \ReflectionProperty($client, 'multi');
```
Comment (nicolas-grekas) [inline src/Symfony/Contracts/HttpClient/Test/HttpClientTestCase.php]: This test case should be moved to the component: contracts contain only tests that are independent of the implementation.

But I would prefer not testing internal implementation details actually. They don't prevent regressions.

Comment (nicolas-grekas) [reply src/Symfony/Contracts/HttpClient/Test/HttpClientTestCase.php]: I don't have a better idea, so let's keep as is. Just move the test please.

**Comment by Nyholm** [comment]
FYI: I tested this PR, it does fix the memory leak.

File: src/Symfony/Contracts/HttpClient/Test/HttpClientTestCase.php (hunk 2 above)
Comment (HypeMC) [reply src/Symfony/Contracts/HttpClient/Test/HttpClientTestCase.php]: Done

File: src/Symfony/Contracts/HttpClient/Test/Fixtures/web/index.php [hunk 3]
```diff
@@ -63,6 +63,10 @@
         header('Content-Type: application/json', true, 404);
         break;
 
+    case '/404/not-json':
```
Comment (nicolas-grekas) [inline src/Symfony/Contracts/HttpClient/Test/Fixtures/web/index.php]: Can we reuse an existing endpoint instead? Because we now have a cross package dependency: the new version of contracts is needed to run the new test case. But I'd prefer not bumping deps in here.

Comment (HypeMC) [reply src/Symfony/Contracts/HttpClient/Test/Fixtures/web/index.php]: @nicolas-grekas Like I mentioned in the test, if the content-type is json `getContent` gets called and the test doesn't fail when it should.

Comment (Nyholm) [reply src/Symfony/Contracts/HttpClient/Test/Fixtures/web/index.php]: Sorry for asking. Could we successfully test this in any other way without modifying `src/Symfony/contracts/HttpClient/*`?

Comment (HypeMC) [reply src/Symfony/Contracts/HttpClient/Test/Fixtures/web/index.php]: @Nyholm I'll take another look later, maybe there's something I've missed.

Comment (HypeMC) [reply src/Symfony/Contracts/HttpClient/Test/Fixtures/web/index.php]: Done, 304 works as well.

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Contracts/HttpClient/Test/Fixtures/web/index.php (hunk 3 above)
Comment (Nyholm) [reply src/Symfony/Contracts/HttpClient/Test/Fixtures/web/index.php]: Awesome. Thank you

**Review by stof — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @HypeMC.
