### PR TITLE
[HttpKernel] Fix passing `null` to `\trim()` method in LoggerDataCollector

### LINKED ISSUE #47235: [HttpKernel] Deprecation of using `null` on `trim()` method in LoggerDataCollector
### Symfony version(s) affected

">= 5.4"

### Description

The bug is a deprecation that is triggered because the usage of a `null` argument to `\trim()` method in `\Symfony\Component\HttpKernel\DataCollector\LoggerDataCollector`. (L147)

This bug appears in dev environment because I added a monolog handler that logs every deprecation in a file.

### How to reproduce

I created a [reproducer](https://github.com/SVillette/SymfonyTrimDeprecationReproducer) that explain step by step how to reproduce this bug and what is the cause.

### Possible Solution

This bug can be fixed in `vendor/symfony/http-kernel/DataCollector/LoggerDataCollector.php:147` by checking if `$log['channel']` is not null before using the `\trim()` method.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by SVillette**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #47235
| License       | MIT
| Doc PR        | -

The full explanation of the bug context is described in the [reproducer](https://github.com/SVillette/SymfonyTrimDeprecationReproducer) repository

To be short, the fact of logging deprecations in dev environment and accessing the deprecations panel in the profiler triggered a PHP deprecation because the `\trim()` method was called with `null`.

### CODE REVIEW

File: src/Symfony/Component/HttpKernel/DataCollector/LoggerDataCollector.php [hunk 1]
```diff
@@ -144,7 +144,7 @@ public function getFilters()
 
         $allChannels = [];
         foreach ($this->getProcessedLogs() as $log) {
-            if ('' === trim($log['channel'])) {
+            if (null === $log['channel'] || '' === trim($log['channel'])) {
```
Comment (xabbuh) [inline src/Symfony/Component/HttpKernel/DataCollector/LoggerDataCollector.php]:
```suggestion
            if ('' === trim($log['channel'] ?? '')) {
```

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @SVillette.
