### PR TITLE
[Mailer][Mailjet] Fix inline attachments with custom Content-ID

### LINKED ISSUE #63514: [Mailer][Mailjet] Inline attachments with custom Content-ID do not work via API
### Symfony version(s) affected

^7.1

### Description

The Content-ID header is not set correctly when using a custom Content ID. As a result, the attachments are not embedded.

### How to reproduce

1. Use the MailjetApiTransport
2. Send an email with a custom Content-ID as in the following example from the docs:

```
$part = new DataPart(new File('/path/to/images/signature.gif'));
// according to the spec, the Content-ID value must include at least one '@' character
$part->setContentId('footer-signature@my-app');

$email = (new Email())
    // ...
    ->addPart($part->asInline())
    ->html('... <img src="cid:footer-signature@my-app"> ...')
;
// send mail
```
3. Note that the raw email contains cid:footer-signature@my-app, while the Content-ID is the filename. Due to this discrepancy, the attachment is not rendered.

### Possible Solution

Replace
```
$formattedAttachment['ContentID'] = $headers->getHeaderParameter('Content-Disposition', 'name');
```
with
```
$formattedAttachment['ContentID'] = $attachment->hasContentId() ? $attachment->getContentId() : $filename;
```
in `MailjetApiTransport` `prepareAttachments`.

This is similar to the API Transport implementations from Mailtrap, Postmark, Sendgrid and Sweego.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by 99Vicky**
Fixes #63514.

| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63514 
| License       | MIT

 Without this fix, custom Content-IDs are not set properly. See the issue for details.

### CODE REVIEW

File: src/Symfony/Component/Mailer/Bridge/Mailjet/Transport/MailjetApiTransport.php [hunk 1]
```diff
@@ -185,7 +185,7 @@ private function prepareAttachments(Email $email, ?string $html): array
                 'Base64Content' => $attachment->bodyToString(),
             ];
             if ('inline' === $headers->getHeaderBody('Content-Disposition')) {
-                $formattedAttachment['ContentID'] = $headers->getHeaderParameter('Content-Disposition', 'name');
+                $formattedAttachment['ContentID'] = $attachment->hasContentId() ? $attachment->getContentId() : $filename;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mailer/Bridge/Mailjet/Transport/MailjetApiTransport.php:188]: Would it be wrong to expect this instead?
```suggestion
                $formattedAttachment['ContentID'] = $attachment->hasContentId() ? $attachment->getContentId() : $headers->getHeaderParameter('Content-Disposition', 'name');
```

**Review by nicolas-grekas — COMMENTED** [review]
Please add a test case.

File: src/Symfony/Component/Mailer/Bridge/Mailjet/Transport/MailjetApiTransport.php (hunk 1 above)
Comment (99Vicky) [reply src/Symfony/Component/Mailer/Bridge/Mailjet/Transport/MailjetApiTransport.php:188]: That should also work. As far as I have investigated, `filename` and `name` always have the same value, because when a `DataPart` is created, `name` is set to `filename` and there is no method to change `filename` afterwards. However, there is a public method `setName` in `TextPart` to change `name` and only if this method is explicitly used, these two values can differ (which, in my opinion, is not done in practice because there is no reason to do so). I based my implementation on the API Transport implementations from Mailtrap, Postmark, Sendgrid, and Sweego, which also use `filename` here. I can change this to `name` if there is a concern that this could break existing usages.

**Comment by 99Vicky** [comment]
> Please add a test case.

I added two test cases, that check whether the content ID in the generated JSON payload sent to the API contains the expected value (with and without custom content ID).

File: src/Symfony/Component/Mailer/Bridge/Mailjet/Transport/MailjetApiTransport.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Mailer/Bridge/Mailjet/Transport/MailjetApiTransport.php:188]: makes sense, thanks

**Comment by nicolas-grekas** [comment]
Thank you @99Vicky.
