### PR TITLE
[Messenger] Fix JSON deserialization of ErrorDetailsStamp and normalization of FlattenException::$statusText

### LINKED ISSUE #39003: [Messenger | ErrorHandler] JSON serialization + ErrorDetailsStamp doesn't seem to deserialize correctly
**Symfony version(s) affected**: 5.2.x (just updated, so dc0d45d)

**Description**  
Follow-up from #38792. I'm using the messenger with the JSON serializer, and in case of errors the deserialization of the errored message fails:

```
In Serializer.php line 122:      
                                                                                                    
  [Symfony\Component\Messenger\Exception\MessageDecodingFailedException]                                                                                                                                   
  Could not decode stamp: Cannot create an instance of "Symfony\Component\Messenger\Stamp\ErrorDetailsStamp" 
  from serialized data because its constructor requires parameter "throwable" to be present.                                                                                             

Exception trace:
 at vendor/symfony/messenger/Transport/Serialization/Serializer.php:122
 Symfony\Component\Messenger\Transport\Serialization\Serializer->decodeStamps() at vendor/symfony/messenger/Transport/Serialization/Serializer.php:73
 Symfony\Component\Messenger\Transport\Serialization\Serializer->decode() at vendor/symfony/amazon-sqs-messenger/Transport/AmazonSqsReceiver.php:55
 Symfony\Component\Messenger\Bridge\AmazonSqs\Transport\AmazonSqsReceiver->get() at vendor/symfony/messenger/Worker.php:74
 Symfony\Component\Messenger\Worker->run() at vendor/symfony/messenger/Command/ConsumeMessagesCommand.php:198
 Symfony\Component\Messenger\Command\ConsumeMessagesCommand->execute() at vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at vendor/symfony/console/Application.php:989
 Symfony\Component\Console\Application->doRunCommand() at vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at bin/console:42

In AbstractNormalizer.php line 394:

  [Symfony\Component\Serializer\Exception\MissingConstructorArgumentsException]                     
  Cannot create an instance of "Symfony\Component\Messenger\Stamp\ErrorDetailsStamp" from serialized
  data because its constructor requires parameter "throwable" to be present.

Exception trace:
  at vendor/symfony/serializer/Normalizer/AbstractNormalizer.php:394
 Symfony\Component\Serializer\Normalizer\AbstractNormalizer->instantiateObject() at vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:233
 Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->instantiateObject() at vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:311
 Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denormalize() at vendor/symfony/serializer/Serializer.php:205
 Symfony\Component\Serializer\Serializer->denormalize() at vendor/symfony/serializer/Normalizer/ArrayDenormalizer.php:60
 Symfony\Component\Serializer\Normalizer\ArrayDenormalizer->denormalize() at vendor/symfony/serializer/Serializer.php:205
 Symfony\Component\Serializer\Serializer->denormalize() at vendor/symfony/serializer/Serializer.php:144
 Symfony\Component\Serializer\Serializer->deserialize() at vendor/symfony/messenger/Transport/Serialization/Serializer.php:120
 Symfony\Component\Messenger\Transport\Serialization\Serializer->decodeStamps() at vendor/symfony/messenger/Transport/Serialization/Serializer.php:73
 Symfony\Component\Messenger\Transport\Serialization\Serializer->decode() at vendor/symfony/amazon-sqs-messenger/Transport/AmazonSqsReceiver.php:55
 Symfony\Component\Messenger\Bridge\AmazonSqs\Transport\AmazonSqsReceiver->get() at vendor/symfony/messenger/Worker.php:74
 Symfony\Component\Messenger\Worker->run() at vendor/symfony/messenger/Command/ConsumeMessagesCommand.php:198
 Symfony\Component\Messenger\Command\ConsumeMessagesCommand->execute() at vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at vendor/symfony/console/Application.php:989
 Symfony\Component\Console\Application->doRunCommand() at vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at bin/console:42
```

**How to reproduce**  
 * Configure the transport with `serializer: Symfony\Component\Messenger\Transport\Serialization\Serializer`
 * Dispatch any message
 * make the message fail (a simple `throw new \Exception();` will suffice)
 * try to handle the failed message, either with a simple retry or from the failed transport

**Possible Solution**  
Use a named constructor to create the stamp, and make the constructor without any arguments?

**Additional context**  
Follow-up from #38792; I updated to 5.2.x as a workaround and I got this failure.

### PR DESCRIPTION
**Pull request by Jean85**
| Q             | A
| ------------- | ---
| Branch?       | 5.x (bugfix of a 5.x-only feature)
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39003
| License       | MIT

~WIP~ This is now complete and, thanks to @yceruto, I've fixed two bugs in this PR:
 * `ErrorDetailsStamp` couldn't be (de)serialized properly with that constructor argument
 * `FlattenException::$statusText` wasn't (de)normalized

### CODE REVIEW

**Comment by Jean85** [comment]
@Nyholm you said in https://github.com/symfony/symfony/issues/38792#issuecomment-716221129 that we don't use `FlattenException` anymore, but it's still present inside the `ErrorDetailsStamp`, and it still doesn't deserialize well, as the current test failure highlights: 
```) Symfony\Component\Messenger\Tests\Stamp\ErrorDetailsStampTest::testDeserialization
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
         'message' => 'exception message'
         'code' => 0
         'previous' => null
-        'trace' => Array (...)
-        'traceAsString' => '#0 /home/alai/workspace/OSS/s...{main}'
+        'trace' => null
+        'traceAsString' => null
         'class' => 'Exception'
         'statusCode' => 500
         'statusText' => 'Internal Server Error'
@@ @@
         'headers' => Array ()
         'file' => '/home/alai/workspace/OSS/symf...st.php'
         'line' => 52
-        'asString' => null
+        'asString' => 'Exception: exception message ...{main}'
     )
 )
```
What should I do?

**Comment by Nyholm** [comment]
@yceruto could you have a look at this PR please?

**Comment by yceruto** [comment]
There is a `FlattenExceptionNormalizer` to serialize/deserialize it correctly, and alternatively you could use `PropertyNormalizer` too.

Did you find a new problem after this fix https://github.com/symfony/symfony/pull/38941?

File: src/Symfony/Component/Messenger/Tests/Stamp/ErrorDetailsStampTest.php [hunk 1]
```diff
@@ -38,11 +39,24 @@ public function testUnwrappingHandlerFailedException(): void
...
         $this->assertSame('I am inside', $stamp->getExceptionMessage());
         $this->assertSame(123, $stamp->getExceptionCode());
         $this->assertEquals($flattenException, $stamp->getFlattenException());
     }
+
+    public function testDeserialization(): void
+    {
+        $exception = new \Exception('exception message');
+        $stamp = ErrorDetailsStamp::create($exception);
+        $serializer = new Serializer();
```
Comment (yceruto) [inline src/Symfony/Component/Messenger/Tests/Stamp/ErrorDetailsStampTest.php]: The Messenger component registers a [normalizer](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Messenger/Transport/Serialization/Normalizer/FlattenExceptionNormalizer.php) to do it right.

Test ref: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Messenger/Tests/Transport/Serialization/Normalizer/FlattenExceptionNormalizerTest.php

Comment (Jean85) [reply src/Symfony/Component/Messenger/Tests/Stamp/ErrorDetailsStampTest.php]: So I should change the test adding the normalizer? Or should I just ignore those differences?

Comment (yceruto) [reply src/Symfony/Component/Messenger/Tests/Stamp/ErrorDetailsStampTest.php]: Yes, you should change the test accordingly to use the normalizer and the context needed.

Comment (Jean85) [reply src/Symfony/Component/Messenger/Tests/Stamp/ErrorDetailsStampTest.php]: I've added the normalizers, but now the `statusText` property is still missing from the normalization.. what am I missing now?

Comment (yceruto) [reply src/Symfony/Component/Messenger/Tests/Stamp/ErrorDetailsStampTest.php]: It's missing the context:
https://github.com/symfony/symfony/blob/77c82cfa18fc70bf3d57f244d8338be04fea3774/src/Symfony/Component/Messenger/Transport/Serialization/Normalizer/FlattenExceptionNormalizer.php#L98

Comment (Jean85) [reply src/Symfony/Component/Messenger/Tests/Stamp/ErrorDetailsStampTest.php]: @yceruto that's already the default: https://github.com/symfony/symfony/blob/78fbd0ac77a571afc332938a5ec836e986de5214/src/Symfony/Component/Messenger/Transport/Serialization/Serializer.php#L44

Comment (yceruto) [reply src/Symfony/Component/Messenger/Tests/Stamp/ErrorDetailsStampTest.php]: Ok, that means the normalizer needs to be updated accordingly. Could you have a look?

Comment (Jean85) [reply src/Symfony/Component/Messenger/Tests/Stamp/ErrorDetailsStampTest.php]: Fixed!

Comment (Jean85) [reply src/Symfony/Component/Messenger/Tests/Stamp/ErrorDetailsStampTest.php]: Fixed!

File: src/Symfony/Component/Messenger/Tests/Command/FailedMessagesShowCommandTest.php [hunk 2]
```diff
@@ -51,14 +51,14 @@ public function testBasicRun()
...
-  Error Class   Exception            
-  Transport     async                
+ ------------- ---------------------
+  Class         stdClass
+  Message Id    15
+  Failed at     %s
+  Error         Things are bad!
+  Error Code    123
+  Error Class   Exception
+  Transport     async
```
Comment (yceruto) [inline src/Symfony/Component/Messenger/Tests/Command/FailedMessagesShowCommandTest.php]: These changes should be reverted.

File: src/Symfony/Component/Messenger/Tests/Command/FailedMessagesShowCommandTest.php [hunk 3]
```diff
@@ -87,14 +87,14 @@ public function testMultipleRedeliveryFails()
...
```
Comment (yceruto) [inline src/Symfony/Component/Messenger/Tests/Command/FailedMessagesShowCommandTest.php]: revert it, please.

File: src/Symfony/Component/Messenger/Tests/Command/FailedMessagesShowCommandTest.php [hunk 4]
```diff
@@ -122,14 +122,14 @@ public function testLegacyFallback()
...
-  Error Class   (unknown)            
-  Transport     async                
+ ------------- ---------------------
+  Class         stdClass
+  Message Id    15
+  Failed at     %s
+  Error         Things are bad!
+  Error Code
+  Error Class   (unknown)
+  Transport     async
```
Comment (yceruto) [inline src/Symfony/Component/Messenger/Tests/Command/FailedMessagesShowCommandTest.php]: same here.

File: src/Symfony/Component/Messenger/Stamp/ErrorDetailsStamp.php [hunk 5]
```diff
@@ -32,19 +32,38 @@ final class ErrorDetailsStamp implements StampInterface
     /** @var FlattenException|null */
     private $flattenException;
 
-    public function __construct(Throwable $throwable)
+    /**
+     * @param int|mixed $exceptionCode
+     */
+    public function __construct(
```
Comment (yceruto) [inline src/Symfony/Component/Messenger/Stamp/ErrorDetailsStamp.php]: one line, please

File: src/Symfony/Component/Messenger/Stamp/ErrorDetailsStamp.php [hunk 6]
```diff
@@ -32,19 +32,38 @@ final class ErrorDetailsStamp implements StampInterface
...
+        string $exceptionClass,
+        $exceptionCode,
```
Comment (yceruto) [inline src/Symfony/Component/Messenger/Stamp/ErrorDetailsStamp.php]: `int`?

File: src/Symfony/Component/Messenger/Stamp/ErrorDetailsStamp.php [hunk 7]
```diff
@@ -32,19 +32,38 @@ final class ErrorDetailsStamp implements StampInterface
...
+        string $exceptionMessage,
+        ?FlattenException $flattenException = null
```
Comment (yceruto) [inline src/Symfony/Component/Messenger/Stamp/ErrorDetailsStamp.php]: please remove `?`, nullability is already represented by `= null` in this case.

File: src/Symfony/Component/Messenger/Stamp/ErrorDetailsStamp.php [hunk 8]
```diff
@@ -32,19 +32,38 @@ final class ErrorDetailsStamp implements StampInterface
...
-        $this->exceptionCode = $throwable->getCode();
-        $this->exceptionMessage = $throwable->getMessage();
-
+        $flattenException = null;
         if (class_exists(FlattenException::class)) {
-            $this->flattenException = FlattenException::createFromThrowable($throwable);
+            $flattenException = FlattenException::createFromThrowable($throwable);
         }
+
+        return new self(
```
Comment (yceruto) [inline src/Symfony/Component/Messenger/Stamp/ErrorDetailsStamp.php]: one line :)

**Review by yceruto — CHANGES_REQUESTED** [review]
Tests are still failing, please take a look. Thanks!

File: src/Symfony/Component/Messenger/Stamp/ErrorDetailsStamp.php (hunk 6 above)
Comment (Jean85) [reply src/Symfony/Component/Messenger/Stamp/ErrorDetailsStamp.php]: It was documented as `int|mixed`, probably for the same reason as https://github.com/vimeo/psalm/pull/3175

File: src/Symfony/Component/Messenger/Stamp/ErrorDetailsStamp.php [hunk 9]
```diff
@@ -32,19 +32,29 @@ final class ErrorDetailsStamp implements StampInterface
     /** @var FlattenException|null */
     private $flattenException;
 
-    public function __construct(Throwable $throwable)
+    /**
+     * @param int|mixed $exceptionCode
+     */
+    public function __construct(string $exceptionClass, $exceptionCode, string $exceptionMessage, FlattenException $flattenException = null)
```
Comment (Nyholm) [inline src/Symfony/Component/Messenger/Stamp/ErrorDetailsStamp.php:38]: Isn't this a BC break when you change the constructor on a non-internal class?

Could we make sure that you still can use `new ErrorDetailsStamp($exception)`?

Comment (Jean85) [reply src/Symfony/Component/Messenger/Stamp/ErrorDetailsStamp.php:38]: @Nyholm IIRC this class is introduced in 5.2, so we should be just in time to change this.

Comment (Jean85) [reply src/Symfony/Component/Messenger/Stamp/ErrorDetailsStamp.php:38]: Also, the fix relies on the constructor signature, so changing that would invalidate this approach.

**Review by yceruto — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Jean85.
