### PR TITLE
[Form] Mark FormFlow as finished if the last step is skipped

### LINKED ISSUE #62445: [Form] Form is not marked 'finished' when last step is skipped
### Symfony version(s) affected

7.4.0-RC2

### Description

I am testing with a form flow containing four steps. In step 1, an event is selected, or the user chooses to create a new event. When a new event is created in step 2, step 3 and 4 are skipped. When an existing event is selected in step 1, step 2 is skipped.

When I choose to create a new event in step 1, enter the details in step 2, the form should be finished, but the `$flow->isFinished()` is still false`.

### How to reproduce

```php
<?php

namespace App\Website\Controller\Event\Form\Link;

use App\Website\Controller\Event\Form\Link\Step\AvailabilityModel;
use App\Website\Controller\Event\Form\Link\Step\CreateEventModel;
use App\Website\Controller\Event\Form\Link\Step\EventModel;
use App\Website\Controller\Event\Form\Link\Step\RolesModel;
use App\Website\Entity\Event;
use Symfony\Component\Validator\Constraints as Assert;

class LinkModel
{
    public string $currentStep = 'event';

    #[Assert\Valid(groups: ['event'])]
    public EventModel $event;

    #[Assert\Valid(groups: ['createEvent'])]
    public CreateEventModel $createEvent;

    #[Assert\Valid(groups: ['roles'])]
    public RolesModel $roles;

    #[Assert\Valid(groups: ['availability'])]
    public AvailabilityModel $availability;

    public function __construct() {
        $this->event = new EventModel();
        $this->createEvent = new CreateEventModel();
        $this->roles = new RolesModel();
        $this->availability = new AvailabilityModel();
    }
}
```

```php
<?php

namespace App\Website\Controller\Event\Form\Link;

use App\Website\Controller\Event\Form\Link\Step\AvailabilityForm;
use App\Website\Controller\Event\Form\Link\Step\CreateEventForm;
use App\Website\Controller\Event\Form\Link\Step\EventForm;
use App\Website\Controller\Event\Form\Link\Step\RolesForm;
use Symfony\Component\Form\Flow\AbstractFlowType;
use Symfony\Component\Form\Flow\FormFlowBuilderInterface;
use Symfony\Component\Form\Flow\Type\NavigatorFlowType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LinkFlow extends AbstractFlowType
{
    public function buildFormFlow(FormFlowBuilderInterface $builder, array $options): void
    {
        $builder->addStep('event', EventForm::class);
        $builder->addStep(
            'createEvent',
            CreateEventForm::class,
            skip: fn (LinkModel $model) => null !== $model->event->event,
        );
        $builder->addStep(
            'roles',
            RolesForm::class,
            skip: fn(LinkModel $model) => null === $model->event->event,
        );
        $builder->addStep(
            'availability',
            AvailabilityForm::class,
            skip: fn(LinkModel $model) => null === $model->event->event,
        );

        $builder->add('navigator', NavigatorFlowType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => LinkModel::class,
            'step_property_path' => 'currentStep',
        ]);
    }
}
```

```php
<?php

declare(strict_types=1);

namespace App\Website\Controller\Event;

use App\Hub\Voter\EventVoter;
use App\Website\Controller\Event\Form\Link\LinkModel;
use App\Website\Entity\Event;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/website/events/{websiteEvent}/link')]
class Link extends AbstractController
{
    public function __invoke(
        Event $websiteEvent,
        Request $request,
    ): Response {
        $model = new LinkModel($websiteEvent);
        $flow = $this->createForm(Form\Link\LinkFlow::class, $model, [
            'action' => $this->generateUrl(self::class, [$websiteEvent]),
        ]);
        $flow->handleRequest($request);

        if ($flow->isSubmitted() && $flow->isValid() && $flow->isFinished()) {
            // do something with $form->getData()

            return $this->redirectToRoute('linked_success');
        }

        dump($flow->isFinished());

        return $this->render(
            'website/event/link.html.twig',
            [
                'websiteEvent' => $websiteEvent,
                'form' => $flow->getStepForm(),
            ]
        );
    }
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by yceruto**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62445
| License       | MIT

This fixes cases where the last step can't be reached because it's currently skipped, which should mark the end of the process instead of throwing a runtime exception: `"Cannot determine next step."`

Then `$flow->isFinished()` will return true, but you must call the handler of the clicked button manually before checking `$flow->isFinished()` so this escenario will be covered:
```php
if ($flow->isSubmitted() && $flow->isValid()) {
    // ensure the flow button is handled before checking whether it's finished
    $flow->getClickedButton()->handle();

    if ($flow->isFinished()) {
        // do something with $form->getData()

        return $this->redirectToRoute('some_route');
    }
}
```
For other cases, you can continue using the simplified version of this controller.

### CODE REVIEW

File: src/Symfony/Component/Form/Tests/Fixtures/Flow/LastStepSkippedType.php [hunk 1]
```diff
@@ -0,0 +1,30 @@
+<?php
+
+declare(strict_types=1);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Tests/Fixtures/Flow/LastStepSkippedType.php]: nope

Comment (yceruto) [reply src/Symfony/Component/Form/Tests/Fixtures/Flow/LastStepSkippedType.php]: opps, fixed :)

**Comment by nicolas-grekas** [comment]
Thank you @yceruto.
