### PR TITLE
[FrameworkBundle] Dump all registered extensions’ configuration reference

### LINKED ISSUE #62428: [FrameworkBundle] `SecurityConfig` array shape missing configurations
### Symfony version(s) affected

7.4/8

### Description

When trying to update a project to Symfony 7.4 I noticed that the `SecurityExtension` the `PhpConfigReferenceDumpPass` gets has no  authenticator nor user provider factories. As a result the corresponding configurations are missing from `reference.php` `SecurityConfig` array shape.

### How to reproduce

Build a container with the `PhpConfigReferenceDumpPass`.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62428
| License       | MIT

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/PhpConfigReferenceDumpPass.php [hunk 1]
```diff
@@ -102,6 +102,9 @@ public function process(ContainerBuilder $container): void
             if (!$extension = (new $bundle())->getContainerExtension()) {
                 continue;
             }
+            if ($container->hasExtension($extension->getAlias())) {
+                $extension = $container->getExtension($extension->getAlias());
```
Comment (yceruto) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/PhpConfigReferenceDumpPass.php]: [just a note] this highlights that extensions can exist outside bundles, in practice, someone could register an extension in the kernel via `$container->registerExtension()` for custom app config, so we might be missing those configs currently.

it could deserve another iteration outside this foreach block, for `$container->getExtensions()` (excluding extensions already processed).

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/PhpConfigReferenceDumpPass.php [hunk 2]
```diff
@@ -105,15 +114,21 @@ public function process(ContainerBuilder $container): void
...
                 continue;
             }
-            $anyEnvExtensions[$bundle] = $extension;
-            $type = $this->camelCase($extension->getAlias()).'Config';
-            $appTypes .= \sprintf("\n * @psalm-type %s = %s", $type, ArrayShapeGenerator::generate($configuration->getConfigTreeBuilder()->buildTree()));
+
+            $extensionAlias = $extension->getAlias();
+            if (isset($anyEnvExtensions[$extensionAlias])) {
+                $extension = $anyEnvExtensions[$extensionAlias];
+            } else {
```
Comment (yceruto) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/PhpConfigReferenceDumpPass.php:121]: this `else` block should never be true because the first foreach processes all registered extensions (including the bundle extensions)

I think you should process per env bundle/extensions first, then any other extensions

Comment (MatTheCat) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/PhpConfigReferenceDumpPass.php:121]: This may happen if the reference is created on an environment the bundle isn’t registered for?

Comment (yceruto) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/PhpConfigReferenceDumpPass.php:121]: cause that the first iteration will catch all extensions no matter the env, so `isset($anyEnvExtensions[$extensionAlias])` should always be true in this foreach

Comment (yceruto) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/PhpConfigReferenceDumpPass.php:121]: hum, nevermind I missed the fact that $container->getExtension() will return those extensions registered for the current env only, so yes, this is fine.

**Review by yceruto — APPROVED** [review]

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/PhpConfigReferenceDumpPass.php (hunk 2 above)
Comment (MatTheCat) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/PhpConfigReferenceDumpPass.php:121]: But this means if the `SecurityBundle` was only registered for the `test` environment e.g. we wouldn’t get its full configuration when building the `dev` container :confused:

Comment (yceruto) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/PhpConfigReferenceDumpPass.php:121]: that's what `$extensionsPerEnv` is collecting for, right?

Comment (MatTheCat) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/PhpConfigReferenceDumpPass.php:121]: Sort of, but the `SecurityExtension` is updated by other bundles after being registered when the container is built to add user providers and authenticators’ configuration.

If the `SecurityBundle` is not loaded though, the `PhpConfigReferenceDumpPass` will create a new extension which won’t be updated by other bundles, so the corresponding configuration won’t appear in the `reference.php` file.

Comment (yceruto) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/PhpConfigReferenceDumpPass.php:121]: that's true, and the reference config file will then change when the cache is cleared in the test env, which is undesirable if this file is committed to the repo

Comment (yceruto) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/PhpConfigReferenceDumpPass.php:121]: although this is a special case for SecurityBundle, allowing other extensions to modify its config tree definition dynamically is not so common, and I think people facing this issue will opt to gitignore the reference.php file

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @MatTheCat.
