### PR TITLE
[TypeInfo] Handle `key-of` and `value-of` types

### LINKED ISSUE #60643: [TypeInfo] Fails to parse value-of<T>
### Symfony version(s) affected

7.3.0

### Description

I am getting `DomainException: Unhandled "value-of" identifier.` when trying to parse a type with phpstan's value-of type.

https://phpstan.org/writing-php-code/phpdoc-types#key-and-value-types-of-arrays-and-iterables

### How to reproduce

`* @var value-of<FooEnum>`

### Possible Solution

I believe we need to add a case for value-of in the StringTypeResolver.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60643
| License       | MIT

Add missing support for `key-of` and `value-of` type.

### CODE REVIEW

**Comment by stof** [comment]
Be careful, there is 2 different `value-of` supported cases in phpstan and psalm:

- `value-of<T>` with `T` being a BackedEnum type returns the union of all backing values of that enum (which we can generalize to the backing type as done in this PR)
- `value-of<T>` with `T` being an array type returns the type of values in that array (there is also `key-of<T>` for the equivalent for the key type)

**Comment by mtarld** [comment]
Oh, didn't know about that, I'll update the PR accordingly, thanks!

**Comment by mtarld** [comment]
Done.

File: src/Symfony/Component/TypeInfo/TypeResolver/StringTypeResolver.php [hunk 1]
```diff
@@ -182,6 +183,19 @@ private function getTypeFromNode(TypeNode $node, ?TypeContext $typeContext): Typ
...
 
         if ($node instanceof GenericTypeNode) {
+            if ($node->type instanceof IdentifierTypeNode && 'value-of' === $node->type->name) {
+                $type = $this->getTypeFromNode($node->genericTypes[0], $typeContext);
+                if ($type instanceof BackedEnumType) {
+                    return $type->getBackingType();
+                }
+
+                if ($type instanceof CollectionType) {
+                    return $type->getCollectionKeyType();
```
Comment (stof) [inline src/Symfony/Component/TypeInfo/TypeResolver/StringTypeResolver.php]:
```suggestion
                    return $type->getCollectionValueType();
```

Comment (mtarld) [reply src/Symfony/Component/TypeInfo/TypeResolver/StringTypeResolver.php]: My bad, I updated to handle both `key-of` and `value-of` types at once.

**Review by stof — APPROVED** [review]

**Comment by OskarStark** [comment]
Looks like a feature to me

**Comment by jack-worman** [comment]
> Looks like a feature to me

I consider this a bug because when I upgraded to Symfony 7.3 the TypeInfo component started throwing an exception. This is because 7.3 introduced handling type aliases, and my code had a `value-of<T>` in it.

So, until this is fixed I have to not use `value-of<T>` (and have worse static analysis) or not use TypeInfo (and do something 🤷 )

**Comment by nicolas-grekas** [comment]
Thank you @mtarld.
