### PR TITLE
[Messenger] [Amqp] Handle AMQPConnectionException when publishing a message.

### LINKED ISSUE #36538: [Messenger] Reconnect after connection was closed
Hi, i'm getting a lot of 'Library error: connection closed unexpectedly' errors when using RabbitMQ cluster with HAProxy in front.
The problem appears when handler is dispatching messages to another handler. The handler opens connection to dispatch a message, but if it stays iddle for
50 sec., this connection is automatically closed.
Is it possible to renew the connection every time the  handler is dispatching a message?

### LINKED ISSUE #48241: [Messenger] Issues after migrating to AWS RabbitMQ
### Symfony version(s) affected

6.0

### Description

We are switching from normal RabbitMQ server, to [AWS-managed cluster](https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/working-with-rabbitmq.html).

After that periodically we have this error in log:
```
(AMQPException): Library error: a SSL error occurred
```
It happens on line `$exchange->publish(...)` in `\Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection::publishOnExchange`

The problem is that after some time, the connection becomes "dead", but method `Connection::clearWhenDisconnected` doesn't detect is as disconnected.

It happened after 350 seconds, because they have some [idle timeout](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html#connection-idle-timeout).

I've provided a small script, that reproduces the issue: https://gist.github.com/xorik/24065aab0db094c99e746b277466fcba

Here's output:
```
Channel is connected!
Published!
Now wait for 360 seconds....
Channel is connected!
Exception (AMQPException): Library error: a SSL error occurred
#0 /tmp/1.php(37): AMQPExchange->publish('howdy-do', 'hello')
#1 {main}
```

I can give you credentials to a test server, if you want (PM https://twitter.com/xorik_dev/ or give me your contact).

I've tried to make persistent connection, adding heartbeat, but it won't help.

This is probably connected with https://github.com/symfony/symfony/issues/36538, but suggested fix doesn't help.

### How to reproduce

- Connect to a AWS RabbitMQ
- publish a message
- wait 350+ seconds
- publish a message

### Possible Solution

- Actually the connection isn't 100% dead, so reconnect is not required and this code actually fixes the issue:
 
```php
try {
    $exchange->publish($message, $routing_key);
} catch (\AMQPException) {
    $exchange->publish($message, $routing_key);
}
```

- Alternative solution is perform some kind of ping or heartbeat, before publishing a message (improve method `clearWhenDisconnected`)

### Additional Context

This is clearly not a Symfony issue, but I think Messenger should handle this issue, since this AWS RabbitMQ is quite popular, and there is no easy way to workaround it by developers, except creating a new transport and copy+pasting or extending bunch of Symfony classes.

### PR DESCRIPTION
**Pull request by jwage**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #36538 Fix #48241
| License       | MIT

If you have a message handler that dispatches messages to another queue, you can encounter `AMQPConnectionException` with the message "Library error: a SSL error occurred" or "a socket error occurred"  depending on if you are using tls or not or if you are running behind a load balancer or not.

You can manually reproduce this issue by dispatching a message where the handler then dispatches another message to a different queue, then go to rabbitmq admin and close the connection manually, then dispatch another message and when the message handler goes to dispatch the other message, you will get this exception:

```
a socket error occurred
#0 /vagrant/vendor/symfony/amqp-messenger/Transport/AmqpTransport.php(60): Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpSender->send()
#1 /vagrant/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(62): Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpTransport->send()
#2 /vagrant/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\Component\Messenger\Middleware\SendMessageMiddleware->handle()
#3 /vagrant/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(61): Symfony\Component\Messenger\Middleware\FailedMessageProcessingMiddleware->handle()
#4 /vagrant/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\Component\Messenger\Middleware\DispatchAfterCurrentBusMiddleware->handle()
#5 /vagrant/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware->handle()
#6 /vagrant/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware->handle()
#7 /vagrant/vendor/symfony/messenger/MessageBus.php(70): Symfony\Component\Messenger\Middleware\TraceableMiddleware->handle()
#8 /vagrant/vendor/symfony/messenger/TraceableMessageBus.php(38): Symfony\Component\Messenger\MessageBus->dispatch()
#9 /vagrant/src/Messenger/MessageBus.php(37): Symfony\Component\Messenger\TraceableMessageBus->dispatch()
#10 /vagrant/vendor/symfony/mailer/Mailer.php(66): App\Messenger\MessageBus->dispatch()
#11 /vagrant/src/Mailer/Mailer.php(83): Symfony\Component\Mailer\Mailer->send()
#12 /vagrant/src/Mailer/Mailer.php(96): App\Mailer\Mailer->send()
#13 /vagrant/src/MessageHandler/Trading/StrategySubscriptionMessageHandler.php(118): App\Mailer\Mailer->sendEmail()
#14 /vagrant/src/MessageHandler/Trading/StrategySubscriptionMessageHandler.php(72): App\MessageHandler\Trading\StrategySubscriptionMessageHandler->handle()
#15 /vagrant/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php(152): App\MessageHandler\Trading\StrategySubscriptionMessageHandler->__invoke()
#16 /vagrant/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php(91): Symfony\Component\Messenger\Middleware\HandleMessageMiddleware->callHandler()
#17 /vagrant/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(71): Symfony\Component\Messenger\Middleware\HandleMessageMiddleware->handle()
#18 /vagrant/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\Component\Messenger\Middleware\SendMessageMiddleware->handle()
#19 /vagrant/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\Component\Messenger\Middleware\FailedMessageProcessingMiddleware->handle()
#20 /vagrant/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\Component\Messenger\Middleware\DispatchAfterCurrentBusMiddleware->handle()
#21 /vagrant/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware->handle()
#22 /vagrant/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware->handle()
#23 /vagrant/vendor/symfony/messenger/MessageBus.php(70): Symfony\Component\Messenger\Middleware\TraceableMiddleware->handle()
#24 /vagrant/vendor/symfony/messenger/TraceableMessageBus.php(38): Symfony\Component\Messenger\MessageBus->dispatch()
#25 /vagrant/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\Component\Messenger\TraceableMessageBus->dispatch()
#26 /vagrant/vendor/symfony/messenger/Worker.php(162): Symfony\Component\Messenger\RoutableMessageBus->dispatch()
#27 /vagrant/vendor/symfony/messenger/Worker.php(109): Symfony\Component\Messenger\Worker->handleMessage()
#28 /vagrant/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(238): Symfony\Component\Messenger\Worker->run()
#29 /vagrant/vendor/symfony/console/Command/Command.php(326): Symfony\Component\Messenger\Command\ConsumeMessagesCommand->execute()
#30 /vagrant/vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run()
#31 /vagrant/vendor/symfony/framework-bundle/Console/Application.php(126): Symfony\Component\Console\Application->doRunCommand()
#32 /vagrant/vendor/symfony/console/Application.php(324): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()
#33 /vagrant/vendor/symfony/framework-bundle/Console/Application.php(80): Symfony\Component\Console\Application->doRun()
#34 /vagrant/vendor/symfony/console/Application.php(175): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
#35 /vagrant/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php(49): Symfony\Component\Console\Application->run()
#36 /vagrant/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run()
#37 /vagrant/bin/console(11): require_once('...')
#38 {main}
```

TODO:

- [x] Add test for retry logic when publishing messages

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php [hunk 1]
```diff
@@ -566,4 +573,23 @@ private function getRoutingKeyForMessage(?AmqpStamp $amqpStamp): ?string
...
+        $retries = 0;
+
+        retry:
+        try {
+            $callable();
+        } catch (\AMQPConnectionException $e) {
+            if (++$retries <= $maxRetries) {
+                $this->clear();
+
+                goto retry;
```
Comment (chalasr) [inline src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:589]: This will cost years of public bashing, but I guess we can afford it 🥲

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @jwage.

File: src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:589]: :cupid: goto, no shame :)

Comment (jwage) [reply src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:589]: hehehe I like it too. I feel like imo it reads better than a loop specifically for retry logic.

**Comment by Nyholm** [comment]
Lovely. Thank you

**Comment by jwage** [comment]
@nicolas-grekas @chalasr @Nyholm thinking more about this. Does this retry open up the possibility for a double publish? What if the write succeeds on the server but the client loses the connection and exception is thrown before getting the response to the write? Then we retry and double publish. Since this isn't idempotent and we have no guarantees, I don't think we can generically retry.

@dunglas see the above. This is related to our discussion about not being able to safely retry non idempotent queries automatically in Doctrine.

Asked here as well https://github.com/php-amqp/php-amqp/discussions/548

**Comment by nnikolay** [comment]
@chalasr @nicolas-grekas is there a way to add this fix into the LTS 5.4 Version?

Many thanks!

**Comment by xabbuh** [comment]
@nnikolay see #57112

**Comment by nnikolay** [comment]
Hey @xabbuh thank you very much!! 🍻
