### PR TITLE
[Security] Automatically register custom authenticator as entry_point (if supported)

### LINKED ISSUE #37068: [Security] New LoginFormAuthenticator fails on InsufficientAuthenticationException with missing AuthenticationEntryPoint
**Symfony version(s) affected**: 5.1

**Description**  

I've replaced my guard login authenticator with a version based on the `AbstractLoginFormAuthenticator` and enabled the AuthenticationManager. Everyhing works fine except hitting a page which requires `IS_AUTHENTICATED_REMEMBERED` without actual being logged in.

This triggers an `AccessDeniedException` which gets caught by the firewall ExceptionListener. This creates an `InsufficientAuthenticationException` and tries to  `startAuthentication()` with it. That method then throws an HttpException because there's not AuthenticationEntryPoint defined:

~~~php
        if (null === $this->authenticationEntryPoint) {
            throw new HttpException(Response::HTTP_UNAUTHORIZED, $authException->getMessage(), $authException, [], $authException->getCode());
        }
~~~

The guard system correctly uses the configured entry point to redirect to my login page.

**How to reproduce**

1. Build a login form based on the new authenticator
2. Build a page requiring a authenticated user
3. Hit the page w/o authentication

**Possible Solution**  

Define an entry point for the authenticator?

Sorry if I missed some doc. I've checked the blog post and Wouter's additional article, but couldn't find help.

Kind regards
Matthias

### PR DESCRIPTION
**Pull request by wouterj**
| Q             | A
| ------------- | ---
| Branch?       | 5.2 (hopefully?)
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #37068
| License       | MIT
| Doc PR        | -

@weaverryan came up with exactly the same issue as proposed by a contributor before (see referenced ticket). Back then, it was decided impossible to fix: see https://github.com/symfony/symfony/pull/37075. However, after some thinking we came up with a way to fix the issue and improve the DX for custom authenticators.

The new authenticators are no longer required to implement `AuthenticationEntryPointInterface` (required for internal authenticators like the `RememberMeAuthenticator` and pre authenticated ones). This PR uses a compiler pass to check if a custom authenticator is supported:

```yaml
security:
  firewalls:
    main:
      # in any case, if an entry_point is already configured it'll not be overriden
      # (http_basic remains the entry point here)
      http_basic: ~
      custom_authenticator: App\Security\CustomAuthenticator
      entry_point: http_basic

      # if only one custom authenticator implements AuthenticationEntryPointInterface,
      # it's automatically configured as the entry point
      custom_authenticator: App\Security\CustomAuthenticator
      custom_authenticators: [App\Security\CustomAuthenticator, App\Security\NoEntryPointAuthenticator]

      # if no custom authenticator implements AuthenticationEntryPointInterface,
      # an error is thrown
      custom_authenticator: App\Security\NoEntryPointAuthenticator

      # if more than one authenticator implements AuthenticationEntryPointInterface,
      # the entry point must be configured explicitly (or an error is thrown)
      custom_authenticators: [App\Security\CustomAuthenticator, App\Security\AnotherCustomAuthenticator]
      entry_point: App\Security\CustomAuthenticator
```

---

I know this is very late for Symfony 5.2. It would be good to decide whether this can be included in the release, in order to smooth out the biggest struggle for people using custom authenticators for the first time.

### CODE REVIEW

**Review by chalasr — APPROVED** [review]
👍 For 5.2

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/CustomAuthenticatorEntryPointPass.php [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+
+            if (!$possibleEntryPoints) {
+                throw new \LogicException(sprintf('No of the configured custom authenticators on "security.firewall.%s.custom_authenticators" implement "%s". Either implement this interface in one of your custom authenticators or configure "security.firewall.%1$s.entry_point" with the entry point service ID.', $firewallName, AuthenticationEntryPointInterface::class));
+            }
+
+            if (\count($possibleEntryPoints) > 1) {
+                throw new \LogicException(sprintf('More than 1 custom authenticator can be used as entry point. Set "security.firewall.%s.entry_point" with to the entry point that should be used. Possible authenticators: "%s".', $firewallName, implode('", "', $possibleEntryPoints)));
+            }
+
+            $exceptionListener->replaceArgument(4, $possibleEntryPoints[0]);
```
Comment (weaverryan) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/CustomAuthenticatorEntryPointPass.php]:
```suggestion
            $exceptionListener->replaceArgument(4, new Reference($possibleEntryPoints[0]));
```

**Review by weaverryan — COMMENTED** [review]
HUGE thanks Wouter for spending your time with this last-second change. My apologies for not catching it sooner. I do think it's important, as the error if you don't have any entrypoints (but you have some custom authenticators) is poor as is trying to debug *why* one entrypoint is being used (e.g. from `form_login`) but your custom authenticator's `start()` method is being ignored.

There is one case that the PR doesn't address yet:

```
security:
  firewalls:
    main:
      http_basic: ~
      custom_authenticator: App\Security\CustomAuthenticatorWithEntrypointInterface
```

What should happen in this case (where no specific `entry_point` has been chosen)? Right now, the new compiler pass is written to just use `http_basic`. I think it should throw an exception. I don't think this should be treated any differently than 2 `custom_authenticators` that both have the entrypoint interface. To say it differently, we should collect the entire collection of "potential entry points" (from built-in authenticators and custom authenticators) and if that collection > 1, we throw an exception and tell the user which options they can choose from.

WDYT? I think it's not too difficult - I think we would need to:

A) Do not throw this Exception inside of `SecurityExtension` - https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L606

B) In `SecurityExtension`, we would probably return the entrypoint from `-> configuredEntryPoint()` as a Reference to some fake service - e.g. `security.FIREWALLNAME.entrypoint` (this is maybe important the entrypoint is also passed to the security config object - https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L501 ). Then, later in the compiler pass, we'll figure out the *real* entrypoint, and set an alias for that fake service that points to the real entrypoint.

C) Also in SecurityExtension, in addition to the `'security.'.$firewallName.'_custom_authenticators'` parameter, we would set another parameter that held a key->value of all entrypoints for that firewall - e.g. `['form_login' => 'SERVICE ID FOR THIS ENTRYPOINT', 'http_basic' => 'SERVICE ID FOR THIS ENTRYPONT']`.

D) Finally, this would give us everything we need in the compiler pass to get a full list of the entrypoints and, if there were more than 1, throw a really nice exception with all the possible keys :).

Let me know if you'd like to chat with this or need any helping pushing it through!

Thank you!

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/CustomAuthenticatorEntryPointPass.php [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+                }
+
+                $customAuthenticator = $container->findDefinition($customAuthenticatorId);
+                if (is_a($customAuthenticator->getClass(), AuthenticationEntryPointInterface::class, true)) {
+                    $possibleEntryPoints[] = $customAuthenticatorId;
+                }
+            }
+
+            if (!$possibleEntryPoints) {
+                throw new \LogicException(sprintf('No of the configured custom authenticators on "security.firewall.%s.custom_authenticators" implement "%s". Either implement this interface in one of your custom authenticators or configure "security.firewall.%1$s.entry_point" with the entry point service ID.', $firewallName, AuthenticationEntryPointInterface::class));
```
Comment (stof) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/CustomAuthenticatorEntryPointPass.php]: typo `None of`

**Comment by wouterj** [comment]
I've completely changed the implementation of this PR to simply the implementation suggested by @weaverryan. If you want entry point to be configured by default, you should now implement `AuthenticationEntryPointInterface` on the authenticator. This already used to be a requirement with Guard and also the core authenticators were almost all supporting this already. If only one entry point is found, it's registered automatically. If you need another class to be the entry point, you would need to configure `entry_point` explicitly.

I'll add some tests for the new compiler pass tomorrow evening.

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/EntryPointFactoryInterface.php [hunk 3]
```diff
@@ -1,30 +0,0 @@
-<?php
```
Comment (wouterj) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/EntryPointFactoryInterface.php]: @fabpot I wasn't very sure about deleting this class after RC2 (class was introduced in 5.1). But as it's experimental, I think this is the correct way? Or should I add a BC layer for this interface?

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/FormLoginFactory.php [hunk 4]
```diff
@@ -118,13 +113,17 @@ public function createAuthenticator(ContainerBuilder $container, string $firewal
...
+        $authenticator = $container
             ->setDefinition($authenticatorId, new ChildDefinition('security.authenticator.form_login'))
             ->replaceArgument(1, new Reference($userProviderId))
             ->replaceArgument(2, new Reference($this->createAuthenticationSuccessHandler($container, $firewallName, $config)))
             ->replaceArgument(3, new Reference($this->createAuthenticationFailureHandler($container, $firewallName, $config)))
             ->replaceArgument(4, $options);
 
+        if ($options['use_forward'] ?? false) {
+            $authenticator->addMethodCall('setHttpKernel', [new Reference('http_kernel')]);
+        }
```
Comment (wouterj) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/FormLoginFactory.php:125]: `http_kernel` sounds like a heavy service to me, so I didn't want to always inject it (honestly, I think we should consider deprecating using subrequests here in 5.3)

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 5]
```diff
@@ -565,17 +564,14 @@ private function createAuthenticationListeners(ContainerBuilder $container, stri
...
+                        $authenticators = (array) $factory->createAuthenticator($container, $id, $firewall[$key], $userProvider);
+                        foreach ($authenticators as $authenticator) {
+                            $authenticationProviders[] = $authenticator;
                         }
 
-                        if ($factory instanceof EntryPointFactoryInterface && ($entryPoint = $factory->registerEntryPoint($container, $id, $firewall[$key]))) {
-                            $entryPoints[$key] = $entryPoint;
+                        // allow entry point to be set to the authenticator key (e.g. "http_basic" or "form_login")
+                        if ($key === $defaultEntryPoint && \count($authenticators) === 1) {
+                            $defaultEntryPoint = $authenticators[0];
```
Comment (wouterj) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]: todo: add a comment here to indicate that the new system uses a compiler pass to set the default entry point

File: src/Symfony/Component/Security/Http/Authenticator/FormLoginAuthenticator.php [hunk 6]
```diff
@@ -146,4 +148,24 @@ private function getCredentials(Request $request): array
...
+    {
+        $this->httpKernel = $httpKernel;
+    }
+
+    public function start(Request $request, AuthenticationException $authException = null): Response
+    {
+        if (!$this->options['use_forward']) {
+            return parent::start($request, $authException);
+        }
+
```
Comment (weaverryan) [inline src/Symfony/Component/Security/Http/Authenticator/FormLoginAuthenticator.php:162]: We probably need a sanity check here - check of `$this->httpKernel` is set and throw an exception if it is not.

Or... another option is to not support `use_forward` in the new system to avoid this messiness...

Comment (wouterj) [reply src/Symfony/Component/Security/Http/Authenticator/FormLoginAuthenticator.php:162]: I would vote to leave it like this: when using the Symfony framework, there is no way to end up here without `$this->httpKernel` being set.

I plan to deprecate this feature in Symfony 5.3, so we don't need to be too strictly nice here imho.

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/RegisterEntryPointPass.php [hunk 7]
```diff
@@ -0,0 +1,77 @@
...
+
+            if (null !== $configuredEntryPoint) {
+                // allow entry points to be configured by authenticator key (e.g. "http_basic")
+                $entryPoint = $entryPoints[$configuredEntryPoint] ?? $configuredEntryPoint;
+            } elseif (\count($entryPoints) === 1) {
+                $entryPoint = array_shift($entryPoints);
+            } else {
+                $entryPointNames = [];
+                foreach ($entryPoints as $key => $class) {
+                    $entryPointNames[] = is_numeric($key) ? $class : $key;
```
Comment (weaverryan) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/RegisterEntryPointPass.php]: Nit-pick - `$class` here is really `$serviceId`.

**Review by weaverryan — APPROVED** [review]
I just tested this extensively - it works perfectly. The internals to get this working are a bit complex, but I'm super happy with the end result: if more than 1 authentication mechanism supplies an "entry point", then you get a clear error instructed you to choose one.

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/EntryPointFactoryInterface.php (hunk 3 above)
Comment (fabpot) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/EntryPointFactoryInterface.php]: That's fine.

**Review by chalasr — COMMENTED** [review]
Some tests are failing

**Comment by fabpot** [comment]
@wouterj Can you have a look at the failing tests and apply fabbot's patch which seems relevant?

**Comment by wouterj** [comment]
> @wouterj Can you have a look at the failing tests and apply fabbot's patch which seems relevant?

Fixed. The remaining failing test seems to be due to outdated dependencies for some reason. If I apply the patches in this PR to `FormLoginAuthenticator` and `GuardBridgeAuthenticator` in the `vendor/` of SecurityBundle, the tests pass. However, I do require `^5.2` in the `composer.json`. So I think (hope) these will be fixed automatically after this PR is merged.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @wouterj.
