### PR TITLE
[RateLimiter] Fix cache storage (use namespaced pool + remove \Serializable)

### LINKED ISSUE #38338: [RateLimiter] LimiterStateInterface should not extend Serializable
`Serializable` is a broken interface. We worked hard to remove it as much as possible from the codebase. New code should never use it.

See https://wiki.php.net/rfc/custom_object_serialization for background.

### LINKED ISSUE #38365: [RateLimiter] Create & use a custom cache pool
See https://github.com/symfony/symfony/pull/38177#discussion_r496320655 :

> this should indeed be a pool based on `cache.app` rather than using `cache.app` directly, to avoid key conflicts (keys must be unique inside the pool, so sharing the same pool between multiple places is a bad idea as they need to cooperate on their naming of keys)
> see https://github.com/symfony/symfony/blob/f06f2f018eb82532c5e6337f2af1926a47dc3de4/src/Symfony/Bundle/FrameworkBundle/Resources/config/cache.php#L68-L71 for the service definition of an existing one

In the rate limiter config, we're also using `cache.app` directly. This should be changed to using a custom cache pool:

https://github.com/symfony/symfony/blob/e8dd14ac9ec9bc08218f1f4d0f1f2cdf6c230413/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L1809-L1812

### PR DESCRIPTION
**Pull request by wouterj**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38365, fix #38338 
| License       | MIT
| Doc PR        | -

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -2261,7 +2261,12 @@ public static function registerRateLimiter(ContainerBuilder $container, string $
 
         $storageId = $limiterConfig['storage_service'] ?? null;
         if (null === $storageId) {
-            $container->register($storageId = 'limiter.storage.'.$name, CacheStorage::class)->addArgument(new Reference($limiterConfig['cache_pool']));
+            $cachePoolId = $limiterConfig['cache_pool'];
+            if ('cache.app' === $cachePoolId) {
+                $container->setDefinition($cachePoolId = 'cache.rate_limiter.'.$name, new ChildDefinition('cache.app'))->addTag('cache.pool');
+            }
```
Comment (wouterj) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:2267]: I'm not completely sure about this:

* Should we always create a namespaced cache pool? (also when a user overrides the `cache_pool` option with a custom one?)
* Should we create 1 rate limiter cache pool, or 1 for each rate limiter (like done here)?

File: src/Symfony/Component/RateLimiter/Window.php [hunk 2]
```diff
@@ -16,7 +16,7 @@
  *
  * @experimental in 5.2
  */
-final class Window implements LimiterStateInterface
+final class Window implements LimiterStateInterface, \Serializable
```
Comment (nicolas-grekas) [inline src/Symfony/Component/RateLimiter/Window.php:19]: same

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:2267]: I think it'd be better to have one single `cache.rate_limiter` pool, that'd be defined in service configuration (and removed in the extension when not used by any limiter maybe?)

This might require prefixing keys so that different limiters don't conflict. Is that the case already? Otherwise, this is a good reason for using several cache pool. If using several cache pools, this should be done by having an abstract `cache.rate_limiter` pool service, and having ChildDefinition for each limiter (tagged as cache.pool)

File: src/Symfony/Component/RateLimiter/LimiterStateInterface.php [hunk 3]
```diff
@@ -16,9 +16,13 @@
...
  * @experimental in 5.2
  */
-interface LimiterStateInterface extends \Serializable
+interface LimiterStateInterface
 {
     public function getId(): string;
 
     public function getExpirationTime(): ?int;
+
+    public function __serialize(): array;
```
[the remark this answers is not in the document]
Comment (wouterj) [reply src/Symfony/Component/RateLimiter/LimiterStateInterface.php:25]: Yes, that would be the best. But how do we define such a contract? Do you think that just stating that in the PHPdoc is enough?

[the remark this answers is not in the document]
Comment (nicolas-grekas) [reply src/Symfony/Component/RateLimiter/LimiterStateInterface.php:25]: yes, that's enough

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 1 above)
Comment (wouterj) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Thanks for the guidelines. I've updated the PR to use a single cache pool (cache keys are prefixed by the limiter ID - which is unique).

I think (hope) making the service private should be enough to remove it when it's not used?

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/rate_limiter.php [hunk 4]
```diff
@@ -15,6 +15,11 @@
 
 return static function (ContainerConfigurator $container) {
     $container->services()
+        ->set('cache.rate_limiter')
+            ->parent('cache.app')
+            ->private()
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/rate_limiter.php:20]: already the default

File: src/Symfony/Component/RateLimiter/TokenBucket.php [hunk 5]
```diff
@@ -70,15 +70,39 @@ public function getExpirationTime(): int
         return $this->rate->calculateTimeForTokens($this->burstSize);
     }
 
-    public function serialize(): string
+    /**
+     * @internal
+     */
+    public function __serialize(): array
```
Comment (nicolas-grekas) [inline src/Symfony/Component/RateLimiter/TokenBucket.php:76]: not needed since __wakeup/__sleep do the job, isn't it? (same for __unser)

File: src/Symfony/Component/RateLimiter/TokenBucket.php [hunk 6]
```diff
@@ -70,15 +70,39 @@ public function getExpirationTime(): int
...
 
         $this->rate = Rate::fromString($rate);
     }
+
+    /**
+     * @internal
+     */
+    public function __sleep(): array
+    {
+        $this->rate = (string) $this->rate;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/RateLimiter/TokenBucket.php:96]: it might be better to use a separate property for this, in case one wants to use the object after __sleep has been called?

Comment (nicolas-grekas) [reply src/Symfony/Component/RateLimiter/TokenBucket.php:96]: no need to declare the extra property btw, this is PHP :)

File: src/Symfony/Component/RateLimiter/TokenBucket.php (hunk 5 above)
Comment (wouterj) [reply src/Symfony/Component/RateLimiter/TokenBucket.php]: Sorry, I misunderstood then (thought you wanted wakeup/sleep as a forward-compatibility). Removed the serialize magic methods.

File: src/Symfony/Component/RateLimiter/TokenBucket.php [hunk 7]
```diff
@@ -70,15 +70,21 @@ public function getExpirationTime(): int
...
-    public function unserialize($serialized): void
+    /**
+     * @internal
+     */
+    public function __wakeup(): void
     {
-        [$this->id, $this->tokens, $this->timer, $this->burstSize, $rate] = unserialize($serialized);
-
-        $this->rate = Rate::fromString($rate);
+        $this->rate = Rate::fromString($this->stringRate);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/RateLimiter/TokenBucket.php:88]: then `unset($this->stringRate)`

**Review by nicolas-grekas — APPROVED** [review]
(with one minor comment)

**Review by stof — COMMENTED** [review]
shouldn't we even have a separate cache pool *per limiter* to avoid cache key conflicts ?

**Comment by wouterj** [comment]
> shouldn't we even have a separate cache pool per limiter to avoid cache key conflicts ?

The cache keys are prefixed by the limiter ID - which is unique for each limiter. So key conflicts should not be possible.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @wouterj.
