### PR TITLE
[Messenger] Fix graceful exit

### LINKED ISSUE #52077: Behavior changed with messenger:consume and signals
### Symfony version(s) affected

6.3.5 and 6.3-dev

### Description

Since version 6.3.5, there is a compatibility break with the `messenger:consume` command and signals.

* After : If  `SIGINT` or `SIGTERM` signals were sent, the worker stopped AFTER processing the current message
* Now (6.3.5 and 6.3-dev) : If  `SIGINT` or `SIGTERM` signals are sent, the worker stops immediately even if a message is being processed (hard stop)

Here are some issues with this change :
* If Supervisor is used, the `supervisorctl stop xxx` command can stop the worker before the processing of the current message is completed (hard stop).
* I'm using the `Symfony\Component\Messenger\Event\WorkerMessageFailedEvent` event to catch an error. If an error is encountered, the listener stops the task group with Supervisor (with its API and  `SIGTERM`) and sends an email. Now when the event calls the Supervisor API to stop, all actions performed after its call are no longer performed:
  * The email is no longer sent
  * Retry strategy does not work 
  * Message processing was stopped abruptly

Link with #50787 ?

### How to reproduce

Repository : 
* Works with < 6.3.5 : https://github.com/hlecorche/symfony-messenger-signal-issue
* Doesn't work with 6.3.5 and 6.3-dev : https://github.com/hlecorche/symfony-messenger-signal-issue/tree/6.3-dev

Commands :
* Execute the command `php bin/console doctrine:database:create && php bin/console doctrine:schema:update --force`
* Execute the command `php bin/console  app:create-message && php bin/console messenger:consume async -vvv`
* Send SIGTERM signal

After (< 6.3.5) :
```
php bin/console  app:create-message && php bin/console messenger:consume async -vvv

                                                                                                                        
 [OK] Consuming messages from transport "async".                                                                        
                                                                                                                        

 // The worker will automatically exit once it has received a stop signal via the messenger:stop-workers command.       

 // Quit the worker with CONTROL-C.                                                                                     

[info] Received message App\Messenger\Message\MessageSuccess
[info] Received signal 15.
[info] Stopping worker.
^ "The worker will stop correctly"
[info] Message App\Messenger\Message\MessageSuccess handled by App\Messenger\MessageHandler\MessageSuccessHandler::__invoke
[info] App\Messenger\Message\MessageSuccess was handled successfully (acknowledging to transport).
```

Now (6.3.5 and 6.3-dev) :
```

php bin/console  app:create-message && php bin/console messenger:consume async -vvv

                                                                                                                        
 [OK] Consuming messages from transport "async".                                                                        
                                                                                                                        

 // The worker will automatically exit once it has received a stop signal via the messenger:stop-workers command.       

 // Quit the worker with CONTROL-C.                                                                                     

[info] Received message App\Messenger\Message\MessageSuccess
[info] Received signal 15.
[info] Stopping worker.
```

### Possible Solution

_No response_

### Additional Context

When I did my tests, pcntl was enabled (`echo \SIGINT;` returns `2`)

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #52077
| License       | MIT

My previous PR #50787 accidentally broke the behavior of the `messenger:consume` command. It no longer waits for the handler to finish, instead it exists immediately.

### CODE REVIEW

File: src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php [hunk 1]
```diff
@@ -271,7 +271,7 @@ public function handleSignal(int $signal, int|false $previousExitCode = 0): int|
 
         $this->worker->stop();
 
-        return 0;
+        return false;
```
Comment (HypeMC) [inline src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php:274]: There's no need to exit here, we just have to call `$this->worker->stop()` and the command will finish gracefully once the handler is done.

File: src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php [hunk 2]
```diff
@@ -198,7 +205,12 @@ private function runWorker(string $failureTransportName, ReceiverInterface $rece
                 throw new \RuntimeException(sprintf('The message with id "%s" could not decoded, it can only be shown or removed.', $this->getMessageId($envelope) ?? '?'));
             }
 
-            $shouldHandle = $shouldForce || 'retry' === $io->choice('Please select an action', ['retry', 'delete'], 'retry');
+            $this->forceExit = true;
+            try {
+                $shouldHandle = $shouldForce || 'retry' === $io->choice('Please select an action', ['retry', 'delete'], 'retry');
+            } finally {
+                $this->forceExit = false;
+            }
```
Comment (HypeMC) [inline src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php:213]: With the `messenger:failed:retry` it's a little different, the `$io->choice()` method has an infinitive loop, so we need to exit if the command is waiting for an answer, otherwise we're stuck in the loop, which is the original issue that I tried to fix in #50787.

File: src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php [hunk 3]
```diff
@@ -156,6 +159,10 @@ private function runInteractive(string $failureTransportName, SymfonyStyle $io,
             // to be temporarily "acked", even if the user aborts
             // handling the message
             while (true) {
+                if ($this->shouldStop) {
+                    break;
+                }
```
Comment (HypeMC) [inline src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php:164]: This is required because the worker is instantiated in loops as well.

File: src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php [hunk 4]
```diff
@@ -180,7 +187,7 @@ private function runInteractive(string $failureTransportName, SymfonyStyle $io,
         }
 
         // avoid success message if nothing was processed
-        if (1 <= $count) {
+        if (1 <= $count && !$this->shouldStop) {
```
Comment (HypeMC) [inline src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php:190]: To avoid printing the message if the command has been terminated.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @HypeMC.
