### PR TITLE
[Dotenv] FIX missing getenv

### LINKED ISSUE #34598: [DotEnv]: Environment variables in .env are evaluated as empty strings
**Symfony DotEnv version(s) affected**: v4.3.6 up until at least v4.3.8

**Description**  
Using environment variables in `.env` files fails.

**How to reproduce**  
* Create `.env` file with the following content:
```
MY_HOSTNAME=${HOSTNAME}
```
where `HOSTNAME` is an existing environment variable.

* Expected result: `MY_HOSTNAME` will have the value of the `HOSTNAME` environment variable.
* Actual result : `MY_HOSTNAME` has no value.

**Additional context**  
I ran into this problem in the context of TYPO3 9LTS with dependency [*dotenv-connector:v2.1.2*](https://github.com/helhum/dotenv-connector) which has a dependency on *symfony/dotenv:^4.0*

### PR DESCRIPTION
**Pull request by mccullagh**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no>
| Tickets       | Fix #34598
| License       | MIT
| Doc PR        |  -

Revert one line to use getenv because not all environment variables are populated in $_ENV[]

### CODE REVIEW

File: src/Symfony/Component/Dotenv/Tests/DotenvTest.php [hunk 1]
```diff
@@ -314,4 +314,13 @@ public function testGetVariablesValueFromEnvFirst()
...
         }
     }
+
+    public function testGetVariablesValueFromGetenv()
+    {
+        putenv('Foo=Bar');
+
+        $dotenv = new Dotenv(true);
+        $values = $dotenv->parse('Foo=${Foo}');
+        $this->assertSame('Bar', $values['Foo']);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Dotenv/Tests/DotenvTest.php]: please add a `putenv('Foo');` after this line to remove the env var after

**Review by nicolas-grekas — COMMENTED** [review]
Did you actually encounter the issue?
If yes, what's your variables_order setting like?
Do you know why `$_SERVER` doesn't contain the env vars on your setup?

**Comment by mccullagh** [comment]
> Did you actually encounter the issue?
yes, on Apache. Command line and Unit tests work.
> If yes, what's your variables_order setting like?
variables_order => GPCS => GPCS
> Do you know why `$_SERVER` doesn't contain the env vars on your setup?
Yes, on the Apache vHost I would need to set the missing  env vars with `PassEnv Foo` to use them.

**Review by nicolas-grekas — APPROVED** [review]
OK, thanks for the explanations.
This variable_order option makes things really hard for portability :(

**Comment by nicolas-grekas** [comment]
Thank you @mccullagh.

File: src/Symfony/Component/Dotenv/Tests/DotenvTest.php (hunk 1 above)
Comment (GrahamCampbell) [reply src/Symfony/Component/Dotenv/Tests/DotenvTest.php]: Should have been in a try-finally.
