### PR TITLE
[PhpUnitBridge] Allow relative path to composer cache

### LINKED ISSUE #37652: [PhpUnitBridge] Composer-cache is not used
**Description**
We are using docker images for running tests where the downloaded composer-packages are cached between
the docker images to reduce download time. However, the composer packages for PHP-Unit are not cached
and downloaded every time which increases the start-time over 30 seconds.

**How to reproduce**
```
mkdir test && cd test
export COMPOSER_CACHE_DIR=composer_cache/
composer require symfony/phpunit-bridge
vendor/bin/simple-phpunit --help

rm -rf vendor
composer require symfony/phpunit-bridge
vendor/bin/simple-phpunit --help
```

**Possible Solution**
Cache vendor/bin/.phpunit, but this is the final installation directory.

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | fix #37652
| License       | MIT
| Doc PR        | -

When users defines a relative path in the `COMPOSER_CACHE_DIR` env variable, 
The `simple-phpunit` code, by changing the directory (with `chdir`), give to composer a different context. At the end, composer stores its cache inside the `vendor/bin/.phpunit` folder, and inside the `vendor/bin/.phpunit/phpunit-X.Y.Z` folder. 

This PR convert the relative path provided by the user into Absolute path.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Why not as a bugfix? It looks like one to me.

File: src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php [hunk 1]
```diff
@@ -239,6 +244,7 @@
     // --no-suggest is not in the list to keep compat with composer 1.0, which is shipped with Ubuntu 16.04LTS
     $exit = proc_close(proc_open("$q$COMPOSER install --no-dev --prefer-dist --no-progress $q", [], $p, getcwd()));
     putenv('COMPOSER_ROOT_VERSION'.(false !== $prevRoot ? '='.$prevRoot : ''));
+    putenv("COMPOSER_CACHE_DIR=$prevCacheDir");
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php]: only if it's set, isn't it?

File: src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php [hunk 2]
```diff
@@ -157,6 +157,11 @@
     ? ('#!/usr/bin/env php' === file_get_contents($COMPOSER, false, null, 0, 18) ? $PHP : '').' '.escapeshellarg($COMPOSER) // detect shell wrappers by looking at the shebang
     : 'composer';
 
+$prevCacheDir = getenv('COMPOSER_CACHE_DIR');
+if ($prevCacheDir && !(0 === strpos($prevCacheDir, '/') || ':' === substr($prevCacheDir, 1, 1) || 0 === strpos($prevCacheDir, '\\\\'))) {
+    $absoluteCacheDir = $oldPwd.'/'.$prevCacheDir;
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php]: why not use realpath?

Comment (jderusse) [reply src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php]: Good catch. It also handle path like `~/.cache/`

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @jderusse.
