### PR TITLE
[FrameworkBundler] Fix cache:clear with buildDir

### LINKED ISSUE #39232: Second invocation of cache:clear removes cache folders created with first invocation
**Symfony version(s) affected**: 5.2.0

**Description**  

A second invocation of `bin/console cache:clear` removes directories from the cache directory that have been created by the first invocation. For certain vendors (such as [JMS Serializer](https://github.com/schmittjoh/JMSSerializerBundle) and [Vich Uploader](https://github.com/dustin10/VichUploaderBundle)), this results in a full application breakdown, as they require the directory to exist.

This also means that a third invocation of the `cache:clear` results in an exception for my application, as the JMS serializer checks for the directory existence during container startup. 

The files I'm "missing" after the second invocation are:

- `annotation.php`
- `App_KernelDevDebugContainer.xml`
- `App_KernelDevDebugContainer.xml.meta`
- `doctrine`
- `jms_serializer`
- `pools`
- `serialization.php`
- `translations`
- `twig`
- `validation.php`
- `vich_uploader`
- `webpack_encore.cache.php`

**How to reproduce**  
You should be able to investigate the behavior with a standard Symfony installation with Twig, as that is also one of the removed folders. However, it won't throw an error in that scenario, as Twig just recreates the required folders.

It looks like the second invocation doesn't execute the warmup stage, but running the `cache:warmup` command doesn't help here due to the vendor missing the required folder.

**Possible Solution**  

I'm not sure whether this is something that is broken within Symfony, or that the vendors should be making adjustments to be more robust for missing cache folders/missing warmup. However, IMO this is a massive difference between 5.1 and 5.2, so I believe that if this was intentional, it should be postponed to 6.0.

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39232
| License       | MIT
| Doc PR        | 

Since #36515 there are 2 caches dir `cacheDir` and `buildDir`. For BC reason both points to the same folders, but when app don't use the same folder, many thing are broken:
This PR fixes several issues introduces by the above PR:
- some files are persisted in the wrong folder (`App_KernelDevDebugContainerDeprecations.log`, `App_KernelDevDebugContainer.xml`)
- LoggerDataCollector looks into cache_dir, while `Compiler.log` is written in build_dir and `Deprecations.log` were written in cache_dir before this PR
- the logic that mirror cacheDir into buildDir at the end of CacheClearCommand does not make sens when `cache_dir` and `build_dir` are not identical.
- Files generated in cacheDir are trashed at the end of CacheWarming (initial issue)

### CODE REVIEW

**Comment by jderusse** [comment]
FYI test in red because test in FWB requires fix Kernel form this same PR (that's why in changed composer.json to 5.2.1)

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
(the tests on Windows might need some love.)

**Comment by jderusse** [comment]
> (the tests on Windows might need some love.)

Fixed with my must favorite trick. Doing nothing... ^^

In fact, previous failure were very strange: I guess appveyor had FS issue 
`Failed to remove non-empty directory: Fixtures/var`
`Permission denied: Fixtures/var/cache`
`Failed to create dir: var/cache/resetting`

**Comment by nicolas-grekas** [comment]
(rebase needed)

File: src/Symfony/Bundle/FrameworkBundle/Tests/Command/CacheClearCommand/CacheClearCommandTest.php [hunk 1]
```diff
@@ -41,65 +41,96 @@ protected function tearDown(): void
...
+        $_SERVER['REQUEST_TIME'] = time() + 1;
+        $application = new Application(clone $this->kernel);
+        $application->setCatchExceptions(false);
+        $application->doRun($input, new NullOutput());
+
+        $this->assertTrue(is_file($this->kernel->getCacheDir().'/annotations.php'));
     }
-}
 
-class NoBuildDirKernel extends TestAppKernel
```
Comment (jderusse) [inline src/Symfony/Bundle/FrameworkBundle/Tests/Command/CacheClearCommand/CacheClearCommandTest.php:96]: Could you have a look @chalasr ? Previous code can't work, because `kernel.build_dir` is now needed to build the container (and now needed to initialize the `cache:clear` command).
I refactored the code t build a container and then remove the parameter from the dumped container.

**Comment by alongosz** [comment]
Hey Guys, just wanted to let you know that this PR resolves our [blocker in Ibexa DXP](https://github.com/ezsystems/ezplatform/pull/624) preventing us from upgrading to Symfony 5.2. Thanks :+1:

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thanks for fixing this bug @jderusse.

**Comment by Kocal** [comment]
Thanks @jderusse :heart: :heart:

**Comment by alongosz** [comment]
Thanks @jderusse :tada: 
When can we expect a patch release / tag? :-)

**Comment by derrabus** [comment]
By the end of the month, usually.

**Comment by lserwatka** [comment]
@derrabus we are launching new Ibexa DXP 3.3.0 on December 30th. We are eager to use Symfony 5.2 as all our tests are passing with this fix. 

Could you make a Symfony 5.2.1 release before December 30th?

**Comment by derrabus** [comment]
> Could you make a Symfony 5.2.1 release before December 30th?

I'm pretty confident that 5.2.1 happens before Dec 30th. 😃 But please test against 5.2-dev in the meantime to make sure the changes work for you.

**Comment by mnapoli** [comment]
Thank you @jderusse!

**Comment by Wirone** [comment]
First of all, thanks for the fix - I've encountered this problems in the project created with CLI binary few days ago and had to downgrade to 5.1 to continue working on it.

Personally I think that fixes like this one should be considered as hotfixes and **released as soon as possible**. Symfony 5.2.0 was released 16 days ago and is really unstable because of problems with cache (at least in `dev` environment for development purposes). And now we hear that new version will be released at the end of the month which means for ~30 days straight really broken version will be installed by default by [`symfony new ...`](https://symfony.com/download) and possibly upgraded to in already existing apps. That's... quite interesting :thinking:

**Comment by jderusse** [comment]
keep calm and run `rm -rf var/cache/*`

**Comment by Wirone** [comment]
Thank you @fabpot for earlier release :+1:
