### PR TITLE
[HttpClient] Fix decorating progress info in AsyncResponse

### LINKED ISSUE #38631: [HttpClient] Missing response content in profiler after adding retryable http client
**Symfony version(s) affected**: 5.2.0-BETA2

**Description**  
Before
```
Request
[▼
  "query" => [▶]
]

Response
[▼
  "info" => [▶]
  "url" => "..."
  "response_headers" => [▶]
  "response_json" => [▶]
]
```
After
```
Response
[▼
  "buffer" => false
  "query" => [▶]
]

Response
[▼
  "info" => [▶]
  "url" => "..."
  "response_headers" => [▶]
]
```

Is this a bug or expected behaviour?

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38631
| License       | MIT
| Doc PR        | /

This PR reverts #38413, and send AsyncContext to onProgress callback.

### CODE REVIEW

**Comment by derrabus** [comment]
Can you write a test for this issue?

**Comment by BoShurik** [comment]
With this PR I have `response_content` instead of `response_json`. Is it possible to get `response_json`?

File: src/Symfony/Component/HttpClient/Response/TraceableResponse.php [hunk 1]
```diff
@@ -132,6 +132,9 @@ public static function stream(HttpClientInterface $client, iterable $responses,
         }
 
         foreach ($client->stream($wrappedResponses, $timeout) as $r => $chunk) {
+            if (null === $chunk->getError()) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/Response/TraceableResponse.php]: `&& false !== $traceableMap[$r]->content`

Comment (jderusse) [reply src/Symfony/Component/HttpClient/Response/TraceableResponse.php]: thanks

**Comment by jderusse** [comment]
> Can you write a test for this issue?

Done.

> With this PR I have response_content instead of response_json. Is it possible to get response_json?

We don't know how the response has been fetched (via `getContent` or `toArray`), thus we can't use `response_json`.
I've 2 solutions:
- revert #38413 and make TracableClient decorating RetryClient
- use `response_json` when response's `content-type` contains `json` /cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
> revert #38413 and make TracableClient decorating RetryClient

that's an option.
We could then improve `RetryableClient` to make it report the retries in details (I'm thinking about merging the `response_header` and `debug` info of all retries in one)

**Comment by nicolas-grekas** [comment]
For the record, I skipped collecting the content consciously back then: to prevent collecting streamed responses (aka potentially long or even infinite content, think SSE).

**Comment by jderusse** [comment]
Ready for review.
Changed the implementation to revert Client decoraton and collect retries metadata

This is how it likes:
Screenshot from 2020-10-19 22-38-26

File: src/Symfony/Component/HttpClient/Response/AsyncContext.php [hunk 2]
```diff
@@ -151,6 +151,11 @@ public function getResponse(): ResponseInterface
     public function replaceRequest(string $method, string $url, array $options = []): ResponseInterface
     {
         $this->info['previous_info'][] = $this->response->getInfo();
+        if (null !== $onProgress = $options['on_progress'] ?? null) {
+            $options['on_progress'] = function (int $dlNow, int $dlSize, array $info) use ($onProgress) {
+                $onProgress($dlNow, $dlSize, $info + $this->info);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/Response/AsyncContext.php]: it should be `$this->info + $info` as in `AsyncResponse::getInfo()`
I think this non-static closure might create a circular ref. We should use a reference to &$this->info to prevent it.

File: src/Symfony/Component/HttpClient/Response/AsyncResponse.php [hunk 3]
```diff
@@ -43,6 +43,12 @@ public function __construct(HttpClientInterface $client, string $method, string
     {
         $this->client = $client;
         $this->shouldBuffer = $options['buffer'] ?? true;
+
+        if (null !== $onProgress = $options['on_progress'] ?? null) {
+            $options['on_progress'] = function (int $dlNow, int $dlSize, array $info) use ($onProgress) {
+                $onProgress($dlNow, $dlSize, $info + $this->info);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/Response/AsyncResponse.php]: same note as above

File: src/Symfony/Component/HttpClient/RetryableHttpClient.php [hunk 4]
```diff
@@ -120,6 +120,7 @@ public function request(string $method, string $url, array $options = []): Respo
             ]);
 
             $context->replaceRequest($method, $url, $options);
+            $context->setInfo('retry_count', $retryCount);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/RetryableHttpClient.php:138]: why this line? isn't the increased value already updated on the next hop with the same lines above? if needed, shouldn't it be set only when `$retryCount < $this->maxRetries`?

Comment (jderusse) [reply src/Symfony/Component/HttpClient/RetryableHttpClient.php:138]: Indeed, the value will be set on the next hop, 

I moved it into the `if ($retryCount >= $this->maxRetries) {` bloc. Issue is there is no hop for last retry.

File: src/Symfony/Component/HttpClient/Response/AsyncContext.php (hunk 2 above)
Comment (jderusse) [reply src/Symfony/Component/HttpClient/Response/AsyncContext.php]: fixed

**Review by nicolas-grekas — APPROVED** [review]

**Review by BoShurik — APPROVED** [review]

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 5]
```diff
@@ -2097,7 +2097,7 @@ private function registerRetryableHttpClient(array $options, string $name, Conta
 
         $container
             ->register($name.'.retryable', RetryableHttpClient::class)
-            ->setDecoratedService($name, null, -10) // lower priority than TraceableHttpClient
+            ->setDecoratedService($name)
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: to ensure proper order of decoration, we would need to guarantee that it has a higher priority

File: src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php [hunk 6]
```diff
@@ -98,6 +98,7 @@ private function collectOnClient(TraceableHttpClient $client): array
         $errorCount = 0;
         $baseInfo = [
             'response_headers' => 1,
+            'retry_count' => 1,
```
Comment (stof) [inline src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php:101]: This looks confusing to me. `retry_count: 1` would tell me that this request was retried once, and so that 2 HTTP queries were performed.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 5 above)
Comment (jderusse) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: switched to `10`

File: src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php (hunk 6 above)
Comment (jderusse) [reply src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php:101]: hmm.. You're right `retry_count: 1` means request has been retried once.

here, `1` is a "never used" value: The `$baseInfo` is used at line 161 to extract "debug infos" with `array_diff_key($info, $baseInfo)`.

**Review by fabpot — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jderusse.
