### PR TITLE
Pass `validator.translation_domain` to `RequestPayloadValueResolver`

### LINKED ISSUE #58170: [HttpKernel] Hardcoded validation translation domain on RequestPayloadValueResolver
### Symfony version(s) affected

6.3

### Description

In \Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestPayloadValueResolver::140 during the payload denormalization we map PartialDenormalizationException's errors into ConstraintViolations and we translate the messages with an hardcoded `validators` domain.

So it does not take into account the possible [override in framework.validation](https://symfony.com/doc/current/reference/configuration/framework.html#translation-domain).

PS : I'll be glad to make the PR once the way to correct this is decided

### How to reproduce

Override the translation_domain in framework.validation with a custom one and override the translations:
- This value was of an unexpected type
- This value should be of type {{ type }}

Create a controller with a MapRequestPayload Dto parameter and send a request with a wrongly typed property (send a string to a bool property for example). The violation message will not take your override message template into account. 

### Possible Solution

Do we really need to translate the message here ?
Can we pass the `validator.translation_domain` param into this service (Not the same component) ?

### Additional Context

```
$trans = $this->translator ? $this->translator->trans(...) : fn ($m, $p) => strtr($m, $p);
 [...]
$message = $trans($template, $parameters, 'validators');
$violations->add(new ConstraintViolation($message, $template, $parameters, null, $error->getPath(), null));
```

### PR DESCRIPTION
**Pull request by raphael-geffroy**
| Q             | A
| ------------- | ---
| Branch?       | 7.2 
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no
| Issues        | Fix #58170
| License       | MIT

Replaces hardcoded validation translation domain by container param `validator.translation_domain`.
Used [UploadValidatorExtension](https://github.com/symfony/symfony/blob/7f15676de99eae53b5b818a038b1bf070577b341/src/Symfony/Component/Form/Extension/Validator/Type/UploadValidatorExtension.php#L24) as inspiration.

### CODE REVIEW

**Comment by OskarStark** [comment]
Milestone 7.2 again per @xabbuh [comment](https://github.com/symfony/symfony/issues/58170#issuecomment-2330929694)

**Review by nicolas-grekas — APPROVED** [review]

**Review by mtarld — APPROVED** [review]

File: src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php [hunk 1]
```diff
@@ -137,7 +138,7 @@ public function onKernelControllerArguments(ControllerArgumentsEvent $event): vo
                         if ($error->canUseMessageForUser()) {
                             $parameters['hint'] = $error->getMessage();
                         }
-                        $message = $trans($template, $parameters, 'validators');
+                        $message = $trans($template, $parameters, $this->translationDomain);
```
Comment (xabbuh) [inline src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php:141]:
```suggestion
                        $message = $trans($template, $parameters, $this->translationDomain ?? 'validators');
```

File: src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php [hunk 2]
```diff
@@ -65,6 +65,7 @@ public function __construct(
         private readonly SerializerInterface&DenormalizerInterface $serializer,
         private readonly ?ValidatorInterface $validator = null,
         private readonly ?TranslatorInterface $translator = null,
+        private ?string $translationDomain = null,
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php]: updated to 
```suggestion
        private string $translationDomain = 'validators',
```

**Comment by nicolas-grekas** [comment]
Thank you @raphael-geffroy.

**Comment by kbond** [comment]
If `symfony/form` isn't installed/available, you get the following exception:

> Symfony\Component\DependencyInjection\Exception\RuntimeException: You have requested a non-existent parameter "validator.translation_domain".
