### PR TITLE
[String] throw when Alpine is used and translit fails

### LINKED ISSUE #37213: [String] AsciiSlugger : iconv(): Wrong charset, conversion from `UTF-8' to `ASCII//IGNORE//TRANSLIT' is not allowed
**Symfony version(s) affected**: 5.0.7

**Description**  
Passing extended UTF-8 characters into `AsciSlugger->slug()` throws an error : 

```
iconv(): Wrong charset, conversion from `UTF-8' to `ASCII//IGNORE//TRANSLIT' is not allowed
```

Stacktrace: image

**How to reproduce**  
```php
<?php
use Symfony\Component\String\Slugger\AsciiSlugger;

(new AsciiSlugger())->slug('😋');
```

I tried with an emoji `😋` and a braille character `⠚`, but probably that other characters have the same fate.

**Possible Solutions**  
1. Remove the characters that would trigger this error (preemptively or by catching it)
2. Delegate the decision to the user by providing a callable to the slug method that would receive the "faulty" character as input : 

```php
use Symfony\Component\String\Slugger\AsciiSlugger;

$slug = (new AsciiSlugger())->slug('😋', '-', null, fn(string $c) => '');

var_dump($slug->toString()); // outputs ""
```

**Additional context**  
Here's a list of characters to play with : https://www.utf8-chartable.de/unicode-utf8-table.pl

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.0
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37213
| License       | MIT
| Doc PR        | -

### CODE REVIEW

File: src/Symfony/Component/String/AbstractUnicodeString.php [hunk 1]
```diff
@@ -142,8 +142,10 @@ public function ascii(array $rules = []): self
             } elseif (ICONV_IMPL === 'glibc') {
                 $s = iconv('UTF-8', 'ASCII//TRANSLIT', $s);
             } else {
-                $s = preg_replace_callback('/[^\x00-\x7F]/u', static function ($c) {
-                    $c = iconv('UTF-8', 'ASCII//IGNORE//TRANSLIT', $c[0]);
+                $s = @preg_replace_callback('/[^\x00-\x7F]/u', static function ($c) {
+                    if ('' === $c = (string) iconv('UTF-8', 'ASCII//IGNORE//TRANSLIT', $c[0])) {
+                        throw new \LogicException(sprintf('"%s" requires a translit-able iconv implementation, try installing "gnu-libiconv" if you\'re using Alpine.', static::class));
```
Comment (glensc) [inline src/Symfony/Component/String/AbstractUnicodeString.php:147]: pell out Alpine: Alpine Linux, otherwise what is Alpine?

File: src/Symfony/Component/String/AbstractUnicodeString.php [hunk 2]
```diff
@@ -142,8 +142,10 @@ public function ascii(array $rules = []): self
             } elseif (ICONV_IMPL === 'glibc') {
                 $s = iconv('UTF-8', 'ASCII//TRANSLIT', $s);
             } else {
-                $s = preg_replace_callback('/[^\x00-\x7F]/u', static function ($c) {
-                    $c = iconv('UTF-8', 'ASCII//IGNORE//TRANSLIT', $c[0]);
+                $s = @preg_replace_callback('/[^\x00-\x7F]/u', static function ($c) {
```
Comment (stof) [inline src/Symfony/Component/String/AbstractUnicodeString.php:145]: why silencing the whole `preg_replace_callback` call ? shouldn't we silence the `iconv` call only ?

Comment (nicolas-grekas) [reply src/Symfony/Component/String/AbstractUnicodeString.php:145]: This makes toggling the error reporting mode only once while doing it in the callback toggles one per match.
