### PR TITLE
[Security] Adjust deprecated messages in `SameOriginCsrfTokenManager`

### LINKED ISSUE #62881: Failed to replace CsrfTokenManagerInterface service in test
### Symfony version(s) affected

7.2

### Description

Hello, 

I'm working on an application that uses CSRF tokens through the form component, but also without it (manual generation). 

I need to re-define the `security.csrf.token_manager` service globally for the `test` environment (with a Stub) to fake its behavior. This is necessary due to the use of  manually generated CSRF tokens that need the service to be defined. 

In some tests I replace this dependency to mock its behavior. 

That's working fine without stateless CSRF tokens. 

But from the moment I wanted to use stateless tokens I encounter the following error when running those tests: 

`Error: Call to undefined method App\Security\Csrf\StubTokenManager::onKernelResponse()`


This is due to the fact that the `security.csrf.token_manager` is decorated by the `security.csrf.same_origin_token_manager` .
The `security.csrf.same_origin_token_manager` service is attached to the `Symfony\Component\Security\Csrf\SameOriginCsrfTokenManager` class which implements the  `Symfony\Component\Security\Csrf\CsrfTokenManagerInterface` interface but, it is also provide an `onKernelResponse()` method that act as a listener (because the service is listening to the `kernel.response` event). 


### How to reproduce

A controller checking a manually generated token:

```php
class FooController extends AbstractController
{
    public function __invoke(Request $request): Response {
        if (!$this->isCsrfTokenValid('foo', $request->request->getString('_token')) {
            // ...
        }

        // ...
    }
}
```

A stub Token manager:

```php
class StubTokenManager implements CsrfTokenManagerInterface
{
    public function __construct(private bool $isValid = true)
    {
    }

    public function getToken(string $tokenId): CsrfToken
    {
        return new CsrfToken($tokenId, null);
    }

    public function refreshToken(string $tokenId): CsrfToken
    {
        return new CsrfToken($tokenId, null);
    }

    public function removeToken(string $tokenId): ?string
    {
        return null;
    }

    public function isTokenValid(CsrfToken $token): bool
    {
        return $this->isValid;
    }
}
```

Some configuration: 

```yaml
# config/packages/csrf.yaml
when@test:
  framework:
    form:
      csrf_protection:
        enabled: false # We don't want to send CSRF token when submitting forms in tests
```


```yaml
# config/services.yaml

when@test:
    'security.csrf.token_manager': '@App\Security\Csrf\StubTokenManager'
```


A dedicated test case:

```php
class FooTest extends WebTestCase
{
    public function testSuccess(): void
    {
        $client = self::createClient();
        $client->request('POST', '/foo');

        $this->assertResponseStatusCodeSame(200);
    }

    public function testInvalidCsrfToken(): void
    {
        $client = self::createClient();
        
        self::getContainer()->set('security.csrf.token_manager', new StubTokenManager(false));

        $client->request('POST', '/foo');

        $this->assertResponseStatusCodeSame(400);
    }
}
```

**-> When running these tests, everything is green.**  


Adding the lines below in the `config/packages/csrf.yaml` 

```yaml
framework:
  csrf_protection:
    stateless_token_ids:
      - 'foo'

# ...
```

**-> and the following error occurred while running the tests:** 

```console
...
Error: Call to undefined method App\Security\Csrf\StubTokenManager::onKernelResponse()
...
``` 


### Possible Solution

A possible solution could be to move the code related of the `onKernelResponse()` method in a dedicated class. This should decouple responsibility between the listener and the manager.

### Additional Context

**Here is the result of the `debug:container` command with no stateless CSRF token enabled:**

```console
/var/www/project $ APP_ENV=test bin/console debug:container security.csrf.token_manager

 // This service is a private alias for the service App\Security\Csrf\StubTokenManager                                  

Information for Service "App\Security\Csrf\StubTokenManager"
============================================================

 ---------------- --------------------------------------------------------------------------------------------- 
  Option           Value                                                                                        
 ---------------- --------------------------------------------------------------------------------------------- 
  Service ID       App\Security\Csrf\StubTokenManager                                                           
  Class            App\Security\Csrf\StubTokenManager                                                           
  Tags             -                                                                                            
  Public           no                                                                                           
  Synthetic        no                                                                                           
  Lazy             no                                                                                           
  Shared           yes                                                                                          
  Abstract         no                                                                                           
  Autowired        yes                                                                                          
  Autoconfigured   yes                                                                                          
  Usages           Symfony\Component\Security\Csrf\CsrfTokenManagerInterface                                    
                   security.csrf.token_manager 

```

**Here is the result of the `debug:container` command with a stateless CSRF token enabled:**

```console
/var/www/project $ APP_ENV=test bin/console debug:container security.csrf.token_manager

 // This service is a private alias for the service security.csrf.same_origin_token_manager                             

Information for Service "security.csrf.same_origin_token_manager"
=================================================================

 This CSRF token manager uses a combination of cookie and headers to validate non-persistent tokens.

 ---------------- --------------------------------------------------------------------------------------------- 
  Option           Value                                                                                        
 ---------------- --------------------------------------------------------------------------------------------- 
  Service ID       security.csrf.same_origin_token_manager                                                      
  Class            Symfony\Component\Security\Csrf\SameOriginCsrfTokenManager                                   
  Tags             monolog.logger (channel: request)                                                            
                   kernel.event_listener (event: kernel.response, method: onKernelResponse)                     
                   container.hot_path                                                                           
  Public           no                                                                                           
  Synthetic        no                                                                                           
  Lazy             no                                                                                           
  Shared           yes                                                                                          
  Abstract         no                                                                                           
  Autowired        no                                                                                           
  Autoconfigured   no                                                                                           
  Arguments        Service(request_stack)                                                                       
                   Service(monolog.logger.request)                                                              
                   Service(App\Security\Csrf\StubTokenManager)                                                  
                   Array (1 element(s))                                                                         
                                                                                                                
                   csrf-token                                                                                   
  Usages           Symfony\Component\Security\Csrf\CsrfTokenManagerInterface                                    
                   security.csrf.token_manager                                                                  
```

### PR DESCRIPTION
**Pull request by jprivet-dev**
| Q             | A          
|---------------|------------
| Branch?       | 8.1        
| Bug fix?      | yes        
| New feature?  | no         
| Deprecations? | yes        
| Issues        | Fix #62881 
| License       | MIT        

New PR after @Spomky  feedbacks on the already merged PR https://github.com/symfony/symfony/pull/63097.

### CODE REVIEW

File: src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php [hunk 1]
```diff
@@ -191,11 +191,11 @@ public function isTokenValid(CsrfToken $token): bool
     }
 
     /**
-     * @deprecated since Symfony 8.1, logic is handled by SameOriginCsrfListener.
+     * @deprecated since Symfony 8.1 and will be removed in 9.0. The logic is handled by SameOriginCsrfListener.
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php]:
```suggestion
     * @deprecated since Symfony 8.1, use SameOriginCsrfListener instead
```

File: src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php [hunk 2]
```diff
@@ -191,11 +191,11 @@ public function isTokenValid(CsrfToken $token): bool
...
      */
     public function clearCookies(Request $request, Response $response): void
     {
-        trigger_deprecation('symfony/security-csrf', '8.1', 'The "%s()" method is deprecated and will be removed in 9.0, use "%s::clearCookies()" instead.', __METHOD__, SameOriginCsrfListener::class);
+        trigger_deprecation('symfony/security-csrf', '8.1', 'The "%s()" method is deprecated and will be removed in 9.0.', __METHOD__);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php]:
```suggestion
        trigger_deprecation('symfony/security-csrf', '8.1', 'The "%s()" method is deprecated, use "%s" instead.', __METHOD__, SameOriginCsrfListener::class);
```

**Review by nicolas-grekas — COMMENTED** [review]
please update all messages as suggested

**Comment by jprivet-dev** [comment]
My apologies for the misunderstanding @nicolas-grekas .

For the public methods `clearCookies()`, `persistStrategy()` and `onKernelResponse()` of the `SameOriginCsrfTokenManager` class:

* They are duplicated in the `SameOriginCsrfListener` class and are all private.
* They are no longer intended for use and may be removed in version `9.0`.

In version `8.1`, the method `SameOriginCsrfTokenManager::onKernelResponse()` is no longer tagged in the file `security_csrf.php` and is no longer used automatically. It remains available only to developers who have used it directly in their implementations.

Are we in agreement on this approach?

**Comment by nicolas-grekas** [comment]
We are :)

File: src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php (hunk 1 above)
Comment (jprivet-dev) [reply src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php]: Done!

File: src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php (hunk 2 above)
Comment (jprivet-dev) [reply src/Symfony/Component/Security/Csrf/SameOriginCsrfTokenManager.php]: Done!

**Comment by jprivet-dev** [comment]
Thank you @nicolas-grekas  for your patience 😊

**Comment by nicolas-grekas** [comment]
Thank you @jprivet-dev.
