### PR TITLE
[Mailer][Postmark] Set CID for attachments when it exists

### LINKED ISSUE #59819: [Mailer][Postmark][Transport] Support Attachment CID
### Symfony version(s) affected

7.2

### Description

Hello,

Symfony Mailer DataPart has supported `setContentId()` since https://github.com/symfony/symfony/pull/46962

I don't believe the Postmark mailer bridge is correctly supporting this. The `cid:` header is hard-coded to the attachment filename.
https://github.com/symfony/postmark-mailer/blob/3a43a9dee2f474ebf7c0328d3cd55d8c17b5df6f/Transport/PostmarkApiTransport.php#L169

Sorry I don't often report issues on Github so please let me know if there's any more information I can provide that would help.

### How to reproduce

`MAILER_DSN=postmark://ID@default`

```php
$sm = new Email();
$sm -> from('company@test.com');
$sm -> subject('Your Order');

$part = new DataPart(fopen('/path/to/images/logo.png', 'r'), 'test.png','image/png`);
$part -> setContentId('MyCustomCidString@my.app');
$sm -> addPart($part -> asInline());

$sm -> html('<img src="cid:MyCustomCidString@my.app" />');

$sm -> addTo('customer@test.com');

$Mailer -> send($sm);

```

### Possible Solution

Suggest `->getContentId()` however I don't have a huge amount of experience with Symfony Mailer's code so there may be a better solution

```
            if ('inline' === $disposition) {
                $att['ContentID'] = 'cid:'.$attachment->getContentId();
            }
```

### Additional Context

Postmark API payload

```
["Attachments"]=>
    array(1) {
      [0]=>
      array(4) {
        ["Name"]=>
        string(59) "test.png"
        ["Content"]=>
        string(2438) "xxxxxxxx"
        ["ContentType"]=>
        string(9) "image/png"
        ["ContentID"]=>
        string(63) "cid:test.png"
      }
    }
```

Expected API payload

```
["Attachments"]=>
    array(1) {
      [0]=>
      array(4) {
        ["Name"]=>
        string(59) "test.png"
        ["Content"]=>
        string(2438) "xxxxxxxx"
        ["ContentType"]=>
        string(9) "image/png"
        ["ContentID"]=>
        string(63) "cid:MyCustomCidString@my.app"
      }
    }
```

### PR DESCRIPTION
**Pull request by IssamRaouf**
| Q             | A
| ------------- | ---
| Branch?       | 6.4  
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #59819 
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/Mailer/Bridge/Postmark/Transport/PostmarkApiTransport.php [hunk 1]
```diff
@@ -147,7 +147,8 @@ private function getAttachments(Email $email): array
             ];
 
             if ('inline' === $disposition) {
-                $att['ContentID'] = 'cid:'.$filename;
+                $contentId = $attachment->hasContentId() ? $attachment->getContentId() : $filename;
+                $att['ContentID'] = 'cid:'.$contentId;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mailer/Bridge/Postmark/Transport/PostmarkApiTransport.php]:
```suggestion
                $att['ContentID'] = 'cid:'.($attachment->hasContentId() ? $attachment->getContentId() : $filename);
```

**Review by nicolas-grekas — APPROVED** [review]

**Review by welcoMattic — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @IssamRaouf.
