### PR TITLE
[Serializer] Readd AdvancedNameConverterInterface to MetadataAwareNameConverter

### LINKED ISSUE #58294: [Serializer] BC break introduced in MetadataAwareNameConverter
### Symfony version(s) affected

7.1

### Description

We were trying to update the Symfony version to 7.1 and noticed that name converting isn't working correctly for us.
We found out that the issue was caused by the removal of the interface `AdvancedNameConverterInterface` in `MetadataAwareNameConverter` [here](https://github.com/symfony/symfony/commit/d088047dfa7d417a25348aee961fc96ff00201d8).
As I understand, removing interface implementation from a class is a breaking change and shouldn't be introduced in a minor version.
image

Generally, it wouldn't cause problems, but for us it did because we are decorating `NameConverterInterface` and we were explicitly checking `$this->decoratedNameConverter instanceof AdvancedNameConverterInterface`

### How to reproduce

N/A

### Possible Solution

Add `AdvancedNameConverterInterface` back to `MetadataAwareNameConverter`

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aurimasrim**
[Serializer] Readd AdvancedNameConverterInterface to MetadataAwareNameConverter

| Q             | A
| ------------- | ---
| Branch?       | 7.1 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #58294  
| License       | MIT

Fixes BC break introduced in a minor version 7.1

### CODE REVIEW

File: src/Symfony/Component/Serializer/NameConverter/MetadataAwareNameConverter.php [hunk 1]
```diff
@@ -18,7 +18,7 @@
 /**
  * @author Fabien Bourigault <bourigaultfabien@gmail.com>
  */
-final class MetadataAwareNameConverter implements NameConverterInterface
+final class MetadataAwareNameConverter implements NameConverterInterface, AdvancedNameConverterInterface
```
Comment (xabbuh) [inline src/Symfony/Component/Serializer/NameConverter/MetadataAwareNameConverter.php]:
```suggestion
final class MetadataAwareNameConverter implements AdvancedNameConverterInterface
```

`AdvancedNameConverterInterface` extends `NameConverterInterface`

**Comment by xabbuh** [comment]
The change looks good to me. I shouldn't have changed that in #54531.

**Review by xabbuh — APPROVED** [review]

**Review by alexandre-daubois — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @aurimasrim.
