### PR TITLE
[Validator] propagate the object being validated to nested constraints

### LINKED ISSUE #39145: [Validator] cannot use "this" in an Expression constraint when embeded in AtLeastOneOf
**Symfony version(s) affected**: 5.1

**Description**  

An exception 'Unable to call method of a non-object.' is thrown by `Symfony\Component\ExpressionLanguage\Node\GetAttrNode`  when using `this` keyword in an Expression constraint when embeded in AtLeastOneOf

**How to reproduce**  

When validating an entity with this kind of constraint:
````php
    /**
     * @Assert\AtLeastOneOf({
     *    @Assert\Expression("this.getCategory() in ['php', 'symfony']"),
     *    @Assert\IdenticalTo("Baz")
     * })
     */
    private $foo;
````
Since the AtLeastOneOfValidator validates the sub-constraint without context,   ``$variables['this'] = $this->context->getObject();`` in `Symfony\Component\Validator\Constraints\ExpressionValidator` results in a null value

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39145
| License       | MIT
| Doc PR        |

### CODE REVIEW

File: src/Symfony/Component/Validator/Constraints/AtLeastOneOfValidator.php [hunk 1]
```diff
@@ -58,4 +65,20 @@ public function validate($value, Constraint $constraint)
             ->addViolation()
         ;
     }
+
+    private function createExecutionContext(): ExecutionContextInterface
+    {
+        return new ExecutionContext($this->context->getValidator(), $this->context->getRoot(), $this->getTranslator());
+    }
+
+    private function getTranslator(): TranslatorInterface
```
Comment (sstok) [inline src/Symfony/Component/Validator/Constraints/AtLeastOneOfValidator.php]: This will create a new translator for every validator. Should we use a property to prevent creating a new instance every time?

Comment (xabbuh) [reply src/Symfony/Component/Validator/Constraints/AtLeastOneOfValidator.php]: I reworked the patch. This is no longer needed.

**Comment by xabbuh** [comment]
Status: Needs Review

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.
