### PR TITLE
[Serializer] Add support for serializing empty array as object

### LINKED ISSUE #42282: [Serializer] preserving empty object breaks current array lists
**Symfony version(s) affected**: 5.4

**Description**
PR #42240 silently breaks BC.

**How to reproduce**
```
class Foo {
    public ArrayObject $object;

    public array $list = [];

    public function __construct()
    {
        $this->object = new ArrayObject();
    }
}
$serializer = new Serializer([new ObjectNormalizer()], ['json' => new JsonEncoder()]);
$serializer->serialize(new Foo(), 'json', [AbstractObjectNormalizer::PRESERVE_EMPTY_OBJECTS => true]);
```
**At 5.3**  
`{"object":{},"list":[]}
`
**At 5.4**  
`{"object":{},"list":{}}
`

**Possible Solution**
Create a new context option like `ARRAY_FORCE_OBJECT`. This option should apply only for current property and do not propagate deeper. This option also should transform plain array to ArrayObject always.

**Additional context**
Current solution produces many complications with empty array normalization too (described here https://github.com/symfony/symfony/pull/42240#issuecomment-887064245)

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes (fix a new feature)
| New feature?  | yes (fix a new feature)
| Deprecations? | no
| Tickets       | Fix #42282
| License       | MIT
| Doc PR        | https://github.com/symfony/symfony-docs/issues/15554

---

New usage:

```php
    public function __construct(
        #[Context([Serializer::EMPTY_ARRAY_AS_OBJECT => true ])]
        public array $mapWithOption = [],
        #[Context([Serializer::EMPTY_ARRAY_AS_OBJECT => true ])]
        public array $mapWithOptionAndData = ['foo' => 'bar'],
        public array $mapWithoutOption = [],
        public array $mapWithoutOptionAndData = ['foo' => 'bar'],
    ) {
    }
```
=>
```
{"mapWithOption":{},"mapWithOptionAndData":{"foo":"bar"},"mapWithoutOption":[],"mapWithoutOptionAndData":{"foo":"bar"}}
```

### CODE REVIEW

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 1]
```diff
@@ -207,7 +211,7 @@ public function normalize($object, string $format = null, array $context = [])
             $data = $this->updateData($data, $attribute, $this->serializer->normalize($attributeValue, $format, $childContext), $class, $format, $attributeContext);
         }
 
-        if (isset($context[self::PRESERVE_EMPTY_OBJECTS]) && !\count($data)) {
+        if ((isset($context[self::PRESERVE_EMPTY_OBJECTS])) && !\count($data)) {
```
Comment (Foxprodev) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: Is it on purpose or not?

Comment (lyrixx) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: oups, this is an artefact of some test, I'll remove it :)

File: src/Symfony/Component/Serializer/Serializer.php [hunk 2]
```diff
@@ -163,6 +169,10 @@ public function normalize($data, string $format = null, array $context = [])
                 return $data;
             }
 
+            if (($context[self::EMPTY_ITERABLE_AS_OBJECT] ?? false) === true && is_countable($data) && 0 === \count($data)) {
```
Comment (Foxprodev) [inline src/Symfony/Component/Serializer/Serializer.php]: EMPTY_ITERABLE_AS_OBJECT currently absorbs PRESERVE_EMPTY_OBJECTS functionality

image
It is less flexible for me. It might be better to apply new option for plain arrays only

Comment (lyrixx) [reply src/Symfony/Component/Serializer/Serializer.php]: I don't think so. See the tests

Comment (Foxprodev) [reply src/Symfony/Component/Serializer/Serializer.php]: Yes, 2nd test case is the same except plain arrays. So for countable objects new option behaves the same.
```
class Foo
{
    public UserList $list; // implements countable interface
    
    public array $settings; // Array setting => value
}
```
If you want to serialize empty settings as JSON object you will use new option, but at the same time your empty `UserList` will be encoded as object. 
So it's less controllable now.

Comment (lyrixx) [reply src/Symfony/Component/Serializer/Serializer.php]: What do you propose?
But anyway, you can put the option only where you need it and not globally.

Comment (Foxprodev) [reply src/Symfony/Component/Serializer/Serializer.php]: > But anyway, you can put the option only where you need it and not globally.

But as I mentioned before it propagates deeper.


> What do you propose?

```
if (is_countable($data) && \count($data) === 0) {
    switch (true) {
        case ($context[AbstractObjectNormalizer::PRESERVE_EMPTY_OBJECTS] ?? false) && is_object($data):
            return $data;
        case ($context[AbstractObjectNormalizer::EMPTY_ARRAYS_AS_OBJECT] ?? false) && is_array($data):
            return new \ArrayObject();
    }
}
```
In this case you can save your current `testNormalizeEmptyIterableAsObject` test case for PRESERVE_EMPTY_OBJECTS + EMPTY_ARRAYS_AS_OBJECT. 
So the test cases 

1. PRESERVE_EMPTY_OBJECTS
2. EMPTY_ARRAYS_AS_OBJECT
3. PRESERVE_EMPTY_OBJECTS + EMPTY_ARRAYS_AS_OBJECT

Comment (lyrixx) [reply src/Symfony/Component/Serializer/Serializer.php]: Thanks, I'm gonna to test it asap

Comment (lyrixx) [reply src/Symfony/Component/Serializer/Serializer.php]: Thanks for taking time to help with this issue.

I have pushed another implementation.

I also added more tests. And I also run the current tests suite with the old implementation (even before my previous) PR and tests pass (exception the one that use `EMPTY_ARRAYS_AS_OBJECT` obviously).

I hope it's now fine for your :)

File: src/Symfony/Component/Serializer/Tests/SerializerTest.php [hunk 3]
```diff
@@ -714,6 +779,38 @@ public function __construct($value)
...
+
+    public $settings = [];
+
+    public function __construct(array $list)
+    {
+        $this->list = new UserList($list);
+    }
+}
+
+class UserList implements \Countable, \IteratorAggregate
```
Comment (Foxprodev) [inline src/Symfony/Component/Serializer/Tests/SerializerTest.php]: `DummyList` or smth to avoid confusion :smile:

File: src/Symfony/Component/Serializer/Tests/SerializerTest.php [hunk 4]
```diff
@@ -531,14 +533,77 @@ public function testNormalizePreserveEmptyArrayObject()
...
+        $data['g2'] = new Baz(['greg']);
+
+        yield [$serializer, $data];
+    }
+
+    /** @dataProvider provideObjectOrCollectionTests */
+    public function testNormalizeWithCollection(Serializer $serializer, array $data)
+    {
+        $expected = '{"a1":[],"a2":{"k":"v"},"b1":[],"b2":{"k":"v"},"c1":{"nested":[]},"c2":{"nested":{"k":"v"}},"d1":{"nested":[]},"d2":{"nested":{"k":"v"}},"e1":{"map":[]},"e2":{"map":{"k":"v"}},"f1":{"map":[]},"f2":{"map":{"k":"v"}},"g1":{"list":[],"settings":[]},"g2":{"list":["greg"],"settings":[]}}';
+        $this->assertEquals($expected, $serializer->serialize($data, 'json'));
```
Comment (Foxprodev) [inline src/Symfony/Component/Serializer/Tests/SerializerTest.php]: assertSame would be better

**Review by Foxprodev — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Serializer/Tests/SerializerTest.php (hunk 3 above)
Comment (lyrixx) [reply src/Symfony/Component/Serializer/Tests/SerializerTest.php]: I'm not sure why it's better, but I updated it

File: src/Symfony/Component/Serializer/Serializer.php [hunk 5]
```diff
@@ -47,6 +47,12 @@
  */
 class Serializer implements SerializerInterface, ContextAwareNormalizerInterface, ContextAwareDenormalizerInterface, ContextAwareEncoderInterface, ContextAwareDecoderInterface
 {
+    /**
+     * Flag to control whether an empty array should be transformed to an
+     * object (in JSON: {}) or to a map (in JSON: []).
```
Comment (Foxprodev) [inline src/Symfony/Component/Serializer/Serializer.php:52]: I guess I'm too meticulous, but map usually means a [key-value data structure](https://en.wikipedia.org/wiki/Associative_array)

Comment (chalasr) [reply src/Symfony/Component/Serializer/Serializer.php:52]: agree :)

```suggestion
     * object (in JSON: {}) or to an array (in JSON: []).
```

Comment (lyrixx) [reply src/Symfony/Component/Serializer/Serializer.php:52]: yes, this is a typo :) thanks

**Review by Foxprodev — APPROVED** [review]
Great! Looks reasonable and correct for me now. Thanks for the time!

**Review by chalasr — APPROVED** [review]

**Comment by derrabus** [comment]
Please make fabbot happy.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @lyrixx.
