### PR TITLE
[Security] Fixed TOCTOU in RememberMe cache token verifier

### LINKED ISSUE #42637: TOCTOU in CacheTokenVerifier
**Symfony version(s) affected**: 5.4

**Description**
At the moment cache is used this way:

https://github.com/symfony/symfony/blob/cd12afee3684b58c4e88ee73ecd3e2884f129db4/src/Symfony/Component/Security/Core/Authentication/RememberMe/CacheTokenVerifier.php#L47-L55

It's a classical example of https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use

Nothing guarantees the cache that is valid in line 48 is not valid anymore in line 52

If it happens you'd get `Warning: hash_equals(): Expected known_string to be a string, null given`

**How to reproduce**
For obvious reasons it's super hard to reproduce it without touching code, but simply make a `getItem` return nothing (as if it didn't find the value). Alternatively - with a debugger just step on the line 52 and wait til it expires.

**Possible Solution**
Just using `$this->cache->getItem($cacheKey);` is sufficient, without extra `hasItem` check.

### PR DESCRIPTION
**Pull request by zerkms**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #42637
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by zerkms** [comment]
UPD: failed tests are unrelated to the changed code

File: src/Symfony/Component/Security/Core/Authentication/RememberMe/CacheTokenVerifier.php [hunk 1]
```diff
@@ -45,12 +45,12 @@ public function verifyToken(PersistentTokenInterface $token, string $tokenValue)
...
 
         $cacheKey = $this->getCacheKey($token);
-        if (!$this->cache->hasItem($cacheKey)) {
-            return false;
-        }
-
         $item = $this->cache->getItem($cacheKey);
+
         $outdatedToken = $item->get();
+        if (!\is_string($outdatedToken)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Core/Authentication/RememberMe/CacheTokenVerifier.php]: this should be moved one line above and be like this:
```php
if (!$item->isHit()) {
    return false;
}
```

Comment (zerkms) [reply src/Symfony/Component/Security/Core/Authentication/RememberMe/CacheTokenVerifier.php]: @nicolas-grekas why is it better? `is_string` narrows down the type of `$outdatedToken` to a string, while `!$item->isHit()` would leave it as `mixed`.

Comment (nicolas-grekas) [reply src/Symfony/Component/Security/Core/Authentication/RememberMe/CacheTokenVerifier.php]: Just because it makes more sense when reading the code. I don't think the responsibility of these lines should be to guard against the case you describe.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @zerkms.
