### PR TITLE
[HttpFoundation] allow savePath of NativeFileSessionHandler to be null

### LINKED ISSUE #41669: [HttpFoundation] SessionHandlerFactory doesn't support session.save_path setting of php.ini on NativeFileSessionHandler
**Symfony version(s) affected**: >=4.4

**Description**
By [introducing the great Symfony\Component\HttpFoundation\Session\Storage\Handler\SessionHandlerFactory](https://github.com/symfony/symfony/commit/de9c61f423b52e022ffa8caa344a83029e7e60a5) it is possible to configure session handler via DSN. But if I want to use the NativeFileSessionHandler to use configured session.save_path of php.ini, it doesn't work as expected because the $savePath constructor param is an empty string (and not NULL) by using "file://" as DSN.

**How to reproduce**
SessionHandlerFactory::createHandler('file://');

$savePath will be an empty string
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php#L33

**Possible Solution**
- check if substr($connection, 7) is an empty string
- if yes use null instead 
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/SessionHandlerFactory.php#L51

something like
```php
$savePath = substr('file://', 7);
return new StrictSessionHandler(new NativeFileSessionHandler($savePath === '' ? null: $savePath));
```
instead of 
```php
return new StrictSessionHandler(new NativeFileSessionHandler(substr($connection, 7)));
```

**Additional context**

### PR DESCRIPTION
**Pull request by simonchrz**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no 
| Tickets       | Fix #41669
| License       | MIT

By introducing the great Symfony\Component\HttpFoundation\Session\Storage\Handler\SessionHandlerFactory it is possible to configure session handler via DSN. But if I want to use the NativeFileSessionHandler to use configured session.save_path of php.ini, it doesn't work as expected because the $savePath constructor param is an empty string (and not NULL) by using "file://" as DSN.

### CODE REVIEW

File: src/Symfony/Component/HttpFoundation/Session/Storage/Handler/SessionHandlerFactory.php [hunk 1]
```diff
@@ -48,7 +48,9 @@ public static function createHandler($connection): AbstractSessionHandler
             case !\is_string($connection):
                 throw new \InvalidArgumentException(sprintf('Unsupported Connection: "%s".', \get_class($connection)));
             case 0 === strpos($connection, 'file://'):
-                return new StrictSessionHandler(new NativeFileSessionHandler(substr($connection, 7)));
+                $savePath = substr('file://', 7);
```
Comment (dbrumann) [inline src/Symfony/Component/HttpFoundation/Session/Storage/Handler/SessionHandlerFactory.php]: This looks like a typo to me, shouldn't it be the same as before?
```suggestion
                $savePath = substr($connection, 7);
```

Comment (simonchrz) [reply src/Symfony/Component/HttpFoundation/Session/Storage/Handler/SessionHandlerFactory.php]: true, thanks for eagle eye 😉

**Comment by nicolas-grekas** [comment]
Hi, thanks for the PR!
Could you please add a test case and squash the commits?

**Comment by simonchrz** [comment]
> Hi, thanks for the PR!
> Could you please add a test case and squash the commits?

sure, could you please give me a hint where i can find tests for Symfony\Component\HttpFoundation\Session\Storage\Handler\SessionHandlerFactory so i could simple extend them ?

haven't found them here...
https://github.com/symfony/symfony/tree/4.4/src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Handler

**Comment by nicolas-grekas** [comment]
It looks like there are no tests for it yet. That's a good opportunity to add some :)

**Comment by simonchrz** [comment]
@nicolas-grekas added a test and everything seems "green". :-) 

There still exist issues with other components using traits that doesn't exist anymore... but i think we could ignore this concerning this PR ?

**Review by nicolas-grekas — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you @simonchrz.
