### PR TITLE
[Security] Fix `AuthenticationUtils::getLastUsername()` returning null

### LINKED ISSUE #53503: AuthenticationUtils::getLastUsername(): Return value must be of type string, null returned
### Symfony version(s) affected

6.4.1

### Description

In production environment i get regularly this exception in logs : 

Uncaught PHP Exception TypeError: "Symfony\Component\Security\Http\Authentication\AuthenticationUtils::getLastUsername(): Return value must be of type string, null returned" at AuthenticationUtils.php

### How to reproduce

I don't know exactly what trigger this exception

### Possible Solution

Changing the return type of the method : 

public function getLastUsername(): ?string
    {
        $request = $this->getRequest();

        if ($request->attributes->has(SecurityRequestAttributes::LAST_USERNAME)) {
            return $request->attributes->get(SecurityRequestAttributes::LAST_USERNAME, '');
        }

        return $request->hasSession() ? $request->getSession()->get(SecurityRequestAttributes::LAST_USERNAME, '') : '';
    }

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #53503
| License       | MIT

This can happen when the attribute is actually set with `null`.

Covered the class while at it.

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

File: src/Symfony/Component/Security/Http/Tests/Authentication/AuthenticationUtilsTest.php [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+
+        $requestStack = new RequestStack();
+        $requestStack->push($request);
+
+        $utils = new AuthenticationUtils($requestStack);
+        $this->assertSame('my error', $utils->getLastAuthenticationError());
+    }
+
+    /**
+     * @runInSeparateProcess
```
Comment (xabbuh) [inline src/Symfony/Component/Security/Http/Tests/Authentication/AuthenticationUtilsTest.php]: Is this here (and in the other tests) really needed?

Comment (alexandre-daubois) [reply src/Symfony/Component/Security/Http/Tests/Authentication/AuthenticationUtilsTest.php]: Yes, because we're dealing with sessions. If we don't add these, sessions overlap and it's a bit of a mess 😄

**Review by xabbuh — APPROVED** [review]

**Comment by chalasr** [comment]
déjà vu 🤔 https://github.com/symfony/symfony/pull/23409

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @alexandre-daubois.
