### PR TITLE
[Messenger] Allow any `ServiceResetterInterface` implementation in `ResetServicesListener`

### LINKED ISSUE #60991: [Messenger][Translation] Final classes cause test failures
### Symfony version(s) affected

8.0.0

### Description

https://github.com/symfony/symfony/pull/60962 and https://github.com/symfony/symfony/pull/60973 made two classes, `DataCollectorTranslator` and `ServicesResetter`, final that cannot be doubled anymore in tests resulting in failed tests.

### How to reproduce

See https://github.com/symfony/symfony/actions/runs/15980198054/job/45072578797?pr=60987

```
1) Symfony\Component\Translation\Tests\DataCollector\TranslationDataCollectorTest::testCollectEmptyMessages
PHPUnit\Framework\MockObject\ClassIsFinalException: Class "Symfony\Component\Translation\DataCollectorTranslator" is declared "final" and cannot be doubled

1) Symfony\Component\Messenger\Tests\EventListener\ResetServicesListenerTest::testResetServices with data set #0 (true)
PHPUnit\Framework\MockObject\ClassIsFinalException: Class "Symfony\Component\HttpKernel\DependencyInjection\ServicesResetter" is declared "final" and cannot be doubled
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by santysisi**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | no 
| License       | MIT

### Summary

This PR updates the `ResetServicesListener` to depend on the `ServicesResetterInterface` instead of the concrete `ServicesResetter` class.

### CODE REVIEW

**Comment by santysisi** [comment]
Hi 👋 I hope you're all doing well!

I think this kind of change is acceptable in a new major version (like now), but if I'm mistaken, I'm happy to update the PR.

**Comment by xabbuh** [comment]
The change itself looks reasonable to me, but that's a new feature and we should merge it into the `7.4` branch (to fix the failing tests on the `8.0` branch I opened #61003.

File: src/Symfony/Component/Messenger/Tests/EventListener/ResetServicesListenerTest.php [hunk 1]
```diff
@@ -31,7 +32,8 @@ public static function provideResetServices(): iterable
      */
     public function testResetServices(bool $shouldReset)
     {
-        $servicesResetter = $this->createMock(ServicesResetter::class);
+        /** @var ServicesResetterInterface&MockObject $servicesResetter */
```
Comment (stof) [inline src/Symfony/Component/Messenger/Tests/EventListener/ResetServicesListenerTest.php]: this `@var` is not necessary. `$this->createMock` already has this as return type.

**Comment by santysisi** [comment]
Hi 👋 I hope you're all doing well!
I've updated the PR with your suggestions, please let me know if there's anything else I should change. ❤️

**Review by stof — APPROVED** [review]

**Review by alexandre-daubois — APPROVED** [review]

File: src/Symfony/Component/Messenger/CHANGELOG.md [hunk 2]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+8.0
+---
+
+ * Use `ServicesResetterInterface` instead of concrete `ServicesResetter` in `ResetServicesListener`
```
Comment (xabbuh) [inline src/Symfony/Component/Messenger/CHANGELOG.md]:
```suggestion
 * Allow any `ServiceResetterInterface` implementation in `ResetServicesListener`
```

Comment (OskarStark) [reply src/Symfony/Component/Messenger/CHANGELOG.md]: I updated the PR header to your suggestion @xabbuh

Comment (ssanmartin00) [reply src/Symfony/Component/Messenger/CHANGELOG.md]: Hi 👋 I hope both of you are doing well ❤️
Thank you so much for the suggestion and the update to the PR header, i really appreciate it! ❤️

Comment (santysisi) [reply src/Symfony/Component/Messenger/CHANGELOG.md]: Hi 👋 I hope both of you are doing well ❤️
Thank you so much for the suggestion and the update to the PR header, i really appreciate it! ❤️

**Comment by santysisi** [comment]
Hey! 👋

The pipeline failure in the `8.2-low-deps` job is due to the fact that the current minor version is `6.4`, while the `ServicesResetterInterface` was  introduced in `7.3`.

I see a few options we could take here:

1. **Bump the minor version requirement** to `^7.3` (this would solve the issue directly, but increases the minimum supported version).
2. **Use a conditional implementation** like this, checking if the interface exists:
```php
if (interface_exists(ServicesResetterInterface::class)) {
    // version using ServicesResetterInterface
} else {
    // fallback using ServicesResetter
}
```
This would keep compatibility with both versions and avoid raising the minimum requirement.
3. **Close this PR** and revisit the implementation once `^7.3` becomes the minimum supported version.


Let me know which path you'd prefer, or if there's another alternative I haven't considered. Happy to adjust the PR accordingly! 🙏❤️

Edit: some resources
https://github.com/symfony/symfony/blob/7.4/src/Symfony/Component/Messenger/composer.json#L29
https://github.com/symfony/symfony/blob/7.4/src/Symfony/Component/HttpKernel/CHANGELOG.md#73

**Comment by xabbuh** [comment]
bumping the require for the HttpKernel component makes sense to me

**Comment by santysisi** [comment]
Hi 👋
The change is now complete.
I believe the error showing up isn’t relevant to the context of this PR.

File: src/Symfony/Component/Messenger/composer.json [hunk 3]
```diff
@@ -26,7 +26,7 @@
         "symfony/console": "^7.2|^8.0",
         "symfony/dependency-injection": "^6.4|^7.0|^8.0",
         "symfony/event-dispatcher": "^6.4|^7.0|^8.0",
-        "symfony/http-kernel": "^6.4|^7.0|^8.0",
+        "symfony/http-kernel": "^7.3|^8.0",
```
Comment (xabbuh) [inline src/Symfony/Component/Messenger/composer.json:29]: There is an entry in `conflict` that also needs to be updated.

Comment (santysisi) [reply src/Symfony/Component/Messenger/composer.json:29]: Totally my fault
I missed that. Thanks a lot for pointing it out! ❤️

**Review by mtarld — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @santysisi.
