### PR TITLE
[Translator] Make sure a null locale is handled properly

### LINKED ISSUE #38124: [Translation] Nullable locale inside tests
**Symfony version(s) affected**: 4.4.11

**Description**  

When a form triggers some error, the code flow goes that way:
https://github.com/symfony/symfony/blob/v4.4.11/src/Symfony/Component/Validator/Violation/ConstraintViolationBuilder.php#L161-L165
https://github.com/symfony/symfony/blob/v4.4.11/src/Symfony/Component/Translation/DataCollectorTranslator.php#L54-L60
https://github.com/symfony/symfony/blob/v4.4.11/src/Symfony/Component/Translation/Translator.php#L224
https://github.com/symfony/symfony/blob/v4.4.11/src/Symfony/Component/Translation/Translator.php#L284-L297

**How to reproduce**  

Inside my tests there are errors like that:

> TypeError: Argument 1 passed to Symfony\Component\Translation\Translator::initializeCacheCatalogue() must be of the type string, null given, called in vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php on line 317
> 
> vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php:338
> vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php:317
> vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php:293
> vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php:224
> vendor/symfony/symfony/src/Symfony/Component/Translation/DataCollectorTranslator.php:56
> vendor/symfony/symfony/src/Symfony/Component/Validator/Violation/ConstraintViolationBuilder.php:164
> vendor/symfony/symfony/src/Symfony/Component/Validator/Constraints/NotBlankValidator.php:45
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:767
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:609
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:520
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:315
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:138
> vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php:104
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:767
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:492
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:315
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:138
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveValidator.php:93
> vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/TraceableValidator.php:66
> vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Validator/EventListener/ValidationListener.php:50
> vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:264
> vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:239
> vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:73
> vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ImmutableEventDispatcher.php:44
> vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:671
> vendor/symfony/symfony/src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php:109
> vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:493

**Possible Solution**  
Allow nullable locale? Or manual how to properly set a locale in tests/CLI/whatever?

**Additional context**  
With Symfony 3.4.35 there are no errors like these.

I also tried to add `\Locale::setDefault('en');` inside `setUpBeforeClass()` method, but didn't work.

### PR DESCRIPTION
**Pull request by jschaedl**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #38124  
| License       | MIT
| Doc PR        | -

### CODE REVIEW

File: src/Symfony/Component/Translation/Translator.php [hunk 1]
```diff
@@ -171,7 +171,11 @@ public function setLocale($locale)
      */
     public function getLocale()
     {
-        return $this->locale;
+        if (null === $this->locale) {
+            @trigger_error(sprintf('Using a "null" $locale is deprecated since Symfony 4.4. You should set it via %s::setLocale($locale) explicitly.', static::class, \E_USER_DEPRECATED));
```
Comment (ro0NL) [inline src/Symfony/Component/Translation/Translator.php:175]: not sure this is needed, you should have gotten a deprecaiton in the first place for setting null.

File: src/Symfony/Component/Translation/Translator.php [hunk 2]
```diff
@@ -171,7 +171,11 @@ public function setLocale($locale)
...
+        }
+
+        return $this->locale ?? 'en';
```
Comment (ro0NL) [inline src/Symfony/Component/Translation/Translator.php:178]: btw TranslatorTrait does `return $this->locale ?: \Locale::getDefault();`, seems reasonable to keep it consistent :/

**Review by ro0NL — APPROVED** [review]

File: src/Symfony/Component/Translation/Translator.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Translation/Translator.php:175]: also we don't add new deprecations in bugfix-only branches

File: src/Symfony/Component/Translation/Translator.php (hunk 2 above)
Comment (jschaedl) [reply src/Symfony/Component/Translation/Translator.php]: But this means an empty locale (`$locale = ''`) is valid as well. Not sure this is the case? Tests are failing if I use `return $this->locale ?: \Locale::getDefault();`.

File: src/Symfony/Component/Translation/Translator.php (hunk 1 above)
Comment (jschaedl) [reply src/Symfony/Component/Translation/Translator.php]: I removed the deprecation.

File: src/Symfony/Component/Translation/Translator.php (hunk 2 above)
Comment (ro0NL) [reply src/Symfony/Component/Translation/Translator.php]: binding resources to an empty locale seems valid:

https://github.com/symfony/symfony/blob/516fa40c34fcbc38faea1b9993e5e0981eb5c991/src/Symfony/Component/Translation/Tests/TranslatorTest.php#L622-L625

so `??` is the right approach i figure, which raises questions why the trait uses `?:`, but that's out of scope here i guess :sweat_smile:

**Review by ro0NL — APPROVED** [review]

**Comment by fabpot** [comment]
Tests seems broken by this change.

**Comment by ro0NL** [comment]
@jschaedl we need to ensure a fixed default locale still, see e.g. https://github.com/symfony/symfony/commit/7fce86f1dba28a172b3b113c330078875fb1dda5#diff-59203b25094d9f89c0a4abd9864d8a9c

**Comment by Aliance** [comment]
@jschaedl any news on this? This bug prevents us from updating to Symfony 4.4

**Comment by jschaedl** [comment]
@ro0NL Thanks for the hint :-)

File: src/Symfony/Component/Translation/Translator.php [hunk 3]
```diff
@@ -171,7 +171,7 @@ public function setLocale($locale)
      */
     public function getLocale()
     {
-        return $this->locale;
+        return $this->locale ?: \Locale::getDefault();
```
Comment (jschaedl) [inline src/Symfony/Component/Translation/Translator.php:174]: Borrowed from https://github.com/symfony/contracts/blob/master/Translation/TranslatorTrait.php#L38 which implies that an empty locale is not a valid locale.

File: src/Symfony/Component/Translation/Tests/TranslatorTest.php [hunk 4]
```diff
@@ -622,7 +650,6 @@ public function getInvalidLocalesTests()
     public function getValidLocalesTests()
     {
         return [
-            [''],
```
Comment (ro0NL) [inline src/Symfony/Component/Translation/Tests/TranslatorTest.php:625]: not sure we should change this behavior in a patch release :/
the previous `?? \Locale::getDefault()` approach was fine no?

File: src/Symfony/Component/Translation/Translator.php (hunk 3 above)
Comment (ro0NL) [reply src/Symfony/Component/Translation/Translator.php:174]: if we want to take this route, i would preserve the empty string (as given by the user)

and validate as such in assertValidLocale, rather than silently ignoring it.

I think it's worth a discussion on master.

File: src/Symfony/Component/Translation/Tests/TranslatorTest.php (hunk 4 above)
Comment (jschaedl) [reply src/Symfony/Component/Translation/Tests/TranslatorTest.php:625]: Actually I am not sure too, but good point. 

I thought it would be good have both `Translator` and `TranslatorTrait` work the same way.

File: src/Symfony/Component/Translation/Translator.php (hunk 3 above)
Comment (jschaedl) [reply src/Symfony/Component/Translation/Translator.php:174]: I think we could do this:
For now we deprecate the possibility to set en empty locale in 4.4 and then we add a proper validation in `assertValidLocale` on master.

WDYT?

File: src/Symfony/Component/Translation/Tests/TranslatorTest.php (hunk 4 above)
Comment (ro0NL) [reply src/Symfony/Component/Translation/Tests/TranslatorTest.php:625]: > I thought it would be good have both Translator and TranslatorTrait work the same way.

i think that's worth pursuing yes ... on master, then we wait for @nicolas-grekas's review also :)

File: src/Symfony/Component/Translation/Translator.php (hunk 3 above)
Comment (ro0NL) [reply src/Symfony/Component/Translation/Translator.php:174]: we cannot add new deprecations in a patch release neither :)

Comment (jschaedl) [reply src/Symfony/Component/Translation/Translator.php:174]: ah true 🙈

**Comment by jschaedl** [comment]
@ro0NL I reverted things as discussed.

**Review by ro0NL — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jschaedl.

**Comment by Aliance** [comment]
@fabpot are you planning to release a new version with this fix?

**Comment by jschaedl** [comment]
@Aliance A new patch version comes out at the end of every month. 
See: https://symfony.com/doc/current/contributing/community/releases.html

> A new Symfony patch version (e.g. 4.4.9, 5.0.9, 5.1.1) comes out roughly every month. It only contains bug fixes, so you can safely upgrade your applications;

You can subscribe for release notifications on this site: https://symfony.com/account/notifications
