### PR TITLE
[Mailer] Fix invalid encoding of custom headers in SES API

### LINKED ISSUE #63146: [Mailer] [Amazon] Invalid encoding of custom headers
### Symfony version(s) affected

Since 7.3.0

### Description

This [PR](https://github.com/symfony/symfony/pull/58761) added support for sending custom headers when using `ses+api` which uses [SendEmail](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendEmail.html) with the Simple message type. The headers are encoded with `HeaderInterface::getBodyAsString()` which returns a string that can contain line return chars (`\r\n`, see `AbstractHeader::getTokenAsEncodedWord()`). The issue is that the [headers in Simple messages](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_MessageHeader.html#SES-Type-MessageHeader-Value) can only contain printable chars, checked using the regex `[ -~]*` (char code 32 to 126) which does not allow `\r\n` (code 10 and 13).

### How to reproduce

Sending a mail with the transport `ses+api` (to use the transport `SesApiAsyncAwsTransport`) with a custom header containing enough non ascii chars to trigger the encoding with the line return chars.

```php
$email = new Email();
$email->subject('Subject');
$email->to('test@test.test');
$email->html('<p>test</p>');
$email->getHeaders()->addTextHeader('custom-header', 'éééééééé');

$this->mailer->send($email);
```

This will try to send a mail with the value `"éééééééé"` encoded as `"=?utf-8?Q?=C3=A9=C3=A9=C3=A9=C3=A9?=\r\n=?utf-8?Q?=C3=A9=C3=A9=C3=A9=C3=A9?="`.

This will produce an error like this:
```
Erreur: Unable to send an email: 1 validation error detected: Value at 'content.simple.headers.1.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [ -~]* (code BadRequestException).
```

Sadly this requires having valid credentials to actually hit aws ses.

### Possible Solution

`SesApiAsyncAwsTransport::getCustomHeaders()` could use a different encoding like base64:
```php
'?UTF-8?B?' . \base64_encode($header->getBody()) . '?='
```
instead of
```php
$header->getBodyAsString()
```

It seems aws includes these headers as is in the final mail so I guess the header content should be encoded in accordance to mail specifications. From what I've found it should be [RFC2822](https://en.wikipedia.org/wiki/MIME#Encoded-Word) which allows this base64 approach. I'm not too familiar with this topic so I'm not sure if my proposed solution is valid.

I'll gladly make a PR if this solution is ok.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lacatoire**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #63146
| License       | MIT

When sending emails via `ses+api` with custom headers containing non-ASCII characters (e.g. accented letters), `HeaderInterface::getBodyAsString()` produces encoded words with `\r\n` line folding. However, AWS SES Simple message headers only accept printable ASCII characters (char codes 32-126), causing a `BadRequestException`.

This PR detects non-printable ASCII characters in header values and re-encodes them using RFC 2047 base64 encoding (`=?UTF-8?B?...?=`), which only produces printable ASCII output. This is consistent with the existing `stringifyAddress()` method which already uses the same approach for non-ASCII address names.

### CODE REVIEW

File: src/Symfony/Component/Mailer/Bridge/Amazon/Tests/Transport/SesApiAsyncAwsTransportTest.php [hunk 1]
```diff
@@ -124,9 +124,45 @@ public function testSend()
...
+        $client = new MockHttpClient(static function (string $method, string $url, array $options): ResponseInterface {
+            $content = json_decode($options['body'], true);
+
+            $headers = [];
+            foreach ($content['Content']['Simple']['Headers'] as $header) {
+                $headers[$header['Name']] = $header['Value'];
+            }
+
+            // ASCII header should be sent as-is
+            \PHPUnit\Framework\Assert::assertSame('foobar', $headers['X-Ascii-Header']);
```
Comment (stof) [inline src/Symfony/Component/Mailer/Bridge/Amazon/Tests/Transport/SesApiAsyncAwsTransportTest.php]: please add a use statement instead of using the FQCN inline.

**Comment by nicolas-grekas** [comment]
Thank you @lacatoire.
