### PR TITLE
[Security] Refresh original user in SwitchUserListener

### LINKED ISSUE #39991: [Security] SwitchUserListener doesn't refresh user in original token
**Symfony version(s) affected**: 5.2.1

**Description**  
SwitchUserListener doesn't automatically refresh the user in the original token. This means anything that uses that user on switch user requests won't be able to assume that it has been refreshed, and it can cause problems with things like Doctrine relations which only work correctly after the user has been refreshed.

**How to reproduce**
- Clone https://github.com/AndrolGenhald/symfony_bug_39991.
- `composer install`
- `bin/console doctrine:migrations:migrate -q`
- Run preferred web server, such as `php -S localhost:8000 -t public`
- Login with "user_1", "password"
- Impersonate user_2_*
- Impersonate user_3_*
- Exception is thrown in CanImpersonateVoter

### PR DESCRIPTION
**Pull request by AndrolGenhald**
Fixes #39991

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39991
| License       | MIT
| Doc PR        | NA

Fix SwitchUserListener to update original token with refreshed user. This prevents a non-refreshed user from causing problems elsewhere, such as in Voters.

### CODE REVIEW

File: src/Symfony/Component/Security/Http/Tests/Firewall/SwitchUserListenerTest.php [hunk 1]
```diff
@@ -406,4 +406,34 @@ public function testSwitchUserStateless()
         $this->assertInstanceOf(UsernamePasswordToken::class, $this->tokenStorage->getToken());
         $this->assertFalse($this->event->hasResponse());
     }
+
+    public function testSwitchUserRefreshesOriginalToken()
+    {
+        $originalUser = $this->getMockBuilder(\Symfony\Component\Security\Core\User\UserInterface::class)->getMock();
```
Comment (OskarStark) [inline src/Symfony/Component/Security/Http/Tests/Firewall/SwitchUserListenerTest.php]: Please use createMock and no FQCN, thanks

Comment (AndrolGenhald) [reply src/Symfony/Component/Security/Http/Tests/Firewall/SwitchUserListenerTest.php]: I matched the style to the rest of the tests in the file, is it ok to use a different style from the file?

Comment (maxhelias) [reply src/Symfony/Component/Security/Http/Tests/Firewall/SwitchUserListenerTest.php]: This is the syntax applied since 5.1.

**Comment by chalasr** [comment]
@AndrolGenhald Could you address the remaining review comment so that we can move this PR forward?

File: src/Symfony/Component/Security/Http/Tests/Firewall/SwitchUserListenerTest.php (hunk 1 above)
Comment (AndrolGenhald) [reply src/Symfony/Component/Security/Http/Tests/Firewall/SwitchUserListenerTest.php]: Oh, I see this change was made to 4.4 the day after I opened the pull request, I hadn't noticed that. I've rebased on top of the latest 4.4 and fixed the issue.

**Review by derrabus — APPROVED** [review]

File: src/Symfony/Component/Security/Http/Tests/Firewall/SwitchUserListenerTest.php (hunk 1 above)
Comment (AndrolGenhald) [reply src/Symfony/Component/Security/Http/Tests/Firewall/SwitchUserListenerTest.php]: Correction, _now_ I've fixed the issue. Silly me I rebased and fixed it but forgot to commit the changes I made...

**Review by OskarStark — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @AndrolGenhald.
