### PR TITLE
[Routing] Fix route URL generation in CLI context

### LINKED ISSUE #30996: default_locale not passed to UrlGenerator
**Symfony version(s) affected**: >=4.1

**Description**  
Symfony 4.1 introduced [Internationalized routing](https://symfony.com/blog/new-in-symfony-4-1-internationalized-routing).
After defining a route with multiple locale I tried to generate a url with a command and got the following error:

```
Unable to generate a URL for the named route "locale" as such route does not exist.
```

The route:

```php
    /**
     * @Route({
     *    "en": "/locale",
     *    "hr": "/lokalno"
     * }, name="locale")
     */
```

The code that generates the url:

```php
$this->router->generate('locale');
```

After some playing around I realized that I need to explicitly set the locale in order for the url to be generated, which was strange since I had the `framework.default_locale` set to `hr`.

```php
// This works
$this->router->generate('locale.hr');
```

I did a little digging and noticed that the [UrlGenerator](https://github.com/symfony/routing/blob/4.2/Generator/UrlGenerator.php#L70) class has a `$defaultLocale` parameter and [the following code](https://github.com/symfony/routing/blob/4.2/Generator/UrlGenerator.php#L116):

```php
$locale = $parameters['_locale']
    ?? $this->context->getParameter('_locale')
    ?: $this->defaultLocale;
```

The problem is that the `$defaultLocale` parameter is [never set](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Router.php#L348) when the class is instantiated. I would expect the `framework.default_locale` parameter to be passed here.

**How to reproduce**  

```yaml
# framework.yaml
framework:
    default_locale: hr
```

```php
// Controller
class LocaleController extends AbstractController
{
    /**
     * @Route({
     *    "en": "/locale",
     *    "hr": "/lokalno"
     * }, name="locale")
     */
    public function index()
    {
        // ...
    }
}
```

```php
// Command
class LocaleCommand extends Command
{
    protected static $defaultName = 'app:locale';

    // ...

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $output->writeln($this->router->generate('locale'));
    }
}
```

**Possible Solution**  

A possible solution would be to override the way the `UrlGenerator` class is instantiated in the [FrameworkBundle Router](https://github.com/symfony/framework-bundle/blob/4.2/Routing/Router.php) class and pass the `framework.default_locale` as the `$defaultLocale` parameter.

### PR DESCRIPTION
**Pull request by X-Coder264**
| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #30996
| License       | MIT
| Doc PR        | -

This fixes #30996 and makes URL generation in the CLI context behave the same as it does in the web context where the `LocaleListener` sets the default locale (to the router context).

The Travis CI failure is related to the fact that the constraint for `symfony/routing` should be bumped to `^4.2.6` in the composer.json of the FrameworkBundle (when it gets tagged).

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/Routing/Router.php [hunk 1]
```diff
@@ -36,14 +36,15 @@ class Router extends BaseRouter implements WarmableInterface, ServiceSubscriberI
...
-     * @param array                   $options    An array of options
-     * @param RequestContext          $context    The context
-     * @param ContainerInterface|null $parameters A ContainerInterface instance allowing to fetch parameters
+     * @param ContainerInterface      $container     A ContainerInterface instance
+     * @param mixed                   $resource      The main resource to load
+     * @param array                   $options       An array of options
+     * @param RequestContext          $context       The context
+     * @param ContainerInterface|null $parameters    A ContainerInterface instance allowing to fetch parameters
      * @param LoggerInterface|null    $logger
+     * @param string|null             $defaultLocale The default locale
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Routing/Router.php]: We prefer not adding annotations when the signature is explicit enough. Looks like that the case in this PR. That's good news as removing these lines will withdraw the need to update all other lines :)

File: src/Symfony/Component/Routing/Router.php [hunk 2]
```diff
@@ -84,19 +89,21 @@ class Router implements RouterInterface, RequestMatcherInterface
...
-     * @param mixed           $resource The main resource to load
-     * @param array           $options  An array of options
-     * @param RequestContext  $context  The context
-     * @param LoggerInterface $logger   A logger instance
+     * @param LoaderInterface $loader        A LoaderInterface instance
+     * @param mixed           $resource      The main resource to load
+     * @param array           $options       An array of options
+     * @param RequestContext  $context       The context
+     * @param LoggerInterface $logger        A logger instance
+     * @param string|null     $defaultLocale The default locale
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Routing/Router.php]: please remove all added lines (see previous comments)

**Comment by nicolas-grekas** [comment]
> the constraint for symfony/routing should be bumped to ^4.2.6 in the composer.json 

please do it in this PR

File: src/Symfony/Component/Routing/Tests/Generator/UrlGeneratorTest.php [hunk 3]
```diff
@@ -720,15 +819,15 @@ public function provideLookAroundRequirementsInPath()
         yield ['/app.php/bar/a/b/bam/c/d/e', '/bar/{foo}/bam/{baz}', '(?<!^).+'];
     }
 
-    protected function getGenerator(RouteCollection $routes, array $parameters = [], $logger = null)
+    protected function getGenerator(RouteCollection $routes, array $parameters = [], $logger = null, ?string $defaultLocale = null)
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Routing/Tests/Generator/UrlGeneratorTest.php]: please remove the `?`, the default is enough

File: src/Symfony/Bundle/FrameworkBundle/Routing/Router.php (hunk 1 above)
Comment (X-Coder264) [reply src/Symfony/Bundle/FrameworkBundle/Routing/Router.php]: Done :)

File: src/Symfony/Component/Routing/Router.php (hunk 2 above)
Comment (X-Coder264) [reply src/Symfony/Component/Routing/Router.php]: Done.

File: src/Symfony/Component/Routing/Tests/Generator/UrlGeneratorTest.php (hunk 3 above)
Comment (X-Coder264) [reply src/Symfony/Component/Routing/Tests/Generator/UrlGeneratorTest.php]: Done.

File: src/Symfony/Bundle/FrameworkBundle/Routing/Router.php [hunk 4]
```diff
@@ -43,7 +43,7 @@ class Router extends BaseRouter implements WarmableInterface, ServiceSubscriberI
      * @param ContainerInterface|null $parameters A ContainerInterface instance allowing to fetch parameters
      * @param LoggerInterface|null    $logger
      */
-    public function __construct(ContainerInterface $container, $resource, array $options = [], RequestContext $context = null, ContainerInterface $parameters = null, LoggerInterface $logger = null)
+    public function __construct(ContainerInterface $container, $resource, array $options = [], RequestContext $context = null, ContainerInterface $parameters = null, LoggerInterface $logger = null, ?string $defaultLocale = null)
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Routing/Router.php]: extra `?`

File: src/Symfony/Bundle/FrameworkBundle/Tests/Routing/RouterTest.php [hunk 5]
```diff
@@ -82,6 +82,32 @@ public function testGenerateWithServiceParamWithSfContainer()
         $this->assertSame('"bar" == "bar"', $router->getRouteCollection()->get('foo')->getCondition());
     }
 
+    public function testGenerateWithDefaultLocale(): void
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Tests/Routing/RouterTest.php]: `void` should be removed, we don't use it on tests

File: src/Symfony/Component/Routing/Router.php [hunk 6]
```diff
@@ -90,13 +95,14 @@ class Router implements RouterInterface, RequestMatcherInterface
      * @param RequestContext  $context  The context
      * @param LoggerInterface $logger   A logger instance
      */
-    public function __construct(LoaderInterface $loader, $resource, array $options = [], RequestContext $context = null, LoggerInterface $logger = null)
+    public function __construct(LoaderInterface $loader, $resource, array $options = [], RequestContext $context = null, LoggerInterface $logger = null, ?string $defaultLocale = null)
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Routing/Router.php]: extra `?`

**Review by nicolas-grekas — APPROVED** [review]
with minor comments

File: src/Symfony/Bundle/FrameworkBundle/Routing/Router.php (hunk 4 above)
Comment (X-Coder264) [reply src/Symfony/Bundle/FrameworkBundle/Routing/Router.php]: Removed.

File: src/Symfony/Bundle/FrameworkBundle/Tests/Routing/RouterTest.php (hunk 5 above)
Comment (X-Coder264) [reply src/Symfony/Bundle/FrameworkBundle/Tests/Routing/RouterTest.php]: Removed.

File: src/Symfony/Component/Routing/Router.php (hunk 6 above)
Comment (X-Coder264) [reply src/Symfony/Component/Routing/Router.php]: Removed.

**Comment by nicolas-grekas** [comment]
Tests will be green once the patch is merged up to master.

**Comment by fancyweb** [comment]
I just tested the case I described in the linked ticket, and it does behave like I wrote it so this change could technically break someone workflow.

**Review by maxhelias — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
@fancyweb the scenario you describe would apply to the cli but not to the web, right? Having a consistent behavior looks more important to me that preserving a non-consistent one to me. Makes sense?

**Comment by fancyweb** [comment]
It also applies to the web context but I guess it's very unlikely that someone relies on this behavior.

**Review by fabpot — APPROVED** [review]

**Comment by X-Coder264** [comment]
Thank for the merge. The `symfony/routing` constraint for `FrameworkBundle` should be bumped now from `^4.2.6` to `^4.2.8` since 4.2.6 and 4.2.7 were already released since this PR was opened.

**Comment by fabpot** [comment]
@X-Coder264 Thanks for the followup, fixed in e479b6902e2f3be2c802f846f220eeb119a82aa0
