### PR TITLE
[HttpClient] Encode and decode curly brackets {}

### LINKED ISSUE #49582: Breaking change in 5.4.21 because of query parameter characters not being escaped anymore in `HttpClientTrait::mergeQueryString`
### Symfony version(s) affected

5.4.21

### Description

This issue is related to https://github.com/symfony/symfony/issues/49579

In symfony 5.4.21 a breaking change has been introduced causing some characters in the query part of urls to not be escaped anymore. https://github.com/symfony/http-client/compare/v5.4.20...v5.4.21 -> `HttpClientTrait::mergeQueryString`

To give some context, we're calling a third party service with a query parameters like this: 
```php
['query' => ['filter' => '{"publicationId":' . self::PUBLICATION_ID_TO_IMPORT . '}']]
```

Originally, the query would be escaped to this: `%7B%publicationId%22:1%7D`, but since the `{` and `}` are not escaped anymore, the query stays like this: `{%22publicationId%22:1}`

Which the third party doesn't handle very well and returns with a 500 status code.

An obvious fix on our side would be to escape `{` and `}` ourselves. But then the http client escapes `%`, which causes `%7B%publicationId%22:1%7D` to become `%257B%22publicationId%22:1%257D`

So what I'm left at is either not escaping, or to much escaping

### How to reproduce

Make `HttpClientTrait::mergeQueryString` public for easier access.

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\HttpClient\CurlHttpClient;

$q = CurlHttpClient::mergeQueryString(null, ['filter' => '{"publicationId":1}'], true);
var_dump($q);
```

Result:
Pre 5.4.21: `filter=%7B%22publicationId%22%3A1%7D`
5.4.21: `filter={%22publicationId%22:1}`

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by pbowyer**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49582 
| License       | MIT

HttpClient wasn't encoding `{` and `}` which meant passing JSON in the query string wasn't working.

### CODE REVIEW

File: src/Symfony/Component/HttpClient/HttpClientTrait.php [hunk 1]
```diff
@@ -547,7 +547,7 @@ private static function parseUrl(string $url, array $query = [], array $allowedS
             }
 
             // https://tools.ietf.org/html/rfc3986#section-3.3
-            $parts[$part] = preg_replace_callback("#[^-A-Za-z0-9._~!$&/'()[\]*+,;=:@\\\\^`{|}%]++#", function ($m) { return rawurlencode($m[0]); }, $parts[$part]);
+            $parts[$part] = preg_replace_callback("#[^-A-Za-z0-9._~!$&/'()[\]*+,;=:@\\\\^`|%]++#", function ($m) { return rawurlencode($m[0]); }, $parts[$part]);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/HttpClientTrait.php]: I'd keep this as is

File: src/Symfony/Component/HttpClient/Tests/HttpClientTraitTest.php [hunk 2]
```diff
@@ -70,6 +70,8 @@ public static function provideResolveUrl(): array
             [self::RFC3986_BASE, '/g',            'http://a/g'],
             [self::RFC3986_BASE, '//g',           'http://g/'],
             [self::RFC3986_BASE, '?y',            'http://a/b/c/d;p?y'],
+            [self::RFC3986_BASE, '?y={"f":1}',  'http://a/b/c/d;p?y=%7B%22f%22:1%7D'],
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/Tests/HttpClientTraitTest.php]: please align

File: src/Symfony/Component/HttpClient/HttpClientTrait.php (hunk 1 above)
Comment (pbowyer) [reply src/Symfony/Component/HttpClient/HttpClientTrait.php]: If I do, we're deviate from the RFC and the tests I've added to `Symfony\Component\HttpClient\Tests\HttpClientTraitTest::testResolveUrl` break. 

I think the `+` in this regular expression needed to be removed in #49580 too but haven't tested that.

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpClient/HttpClientTrait.php]: This regexp is to keep characters that are allowed in URLs unencoded. + is one of them. Encoding it would actually break URLs.

**Comment by nicolas-grekas** [comment]
Thank you @pbowyer.
