### PR TITLE
[Cache] Fix CacheCollectorPass with decorated cache pools

### LINKED ISSUE #38055: CacheCollectorPass does not work anymore when the cache is decorated
**Symfony version(s) affected**: 4.4.13 (introduced with 4.4.8)

**Description**  
We have defined in the framework.yaml an own cache pool. We are also decorating that cache.pool. After this the 
`\Symfony\Component\Cache\DependencyInjection\CacheCollectorPass` is throwing an `ServiceNotFoundException`. It seems so that the definition name changes while decorating.

**How to reproduce**  

* Create a new cache pool in `framework.yaml`
* Decorate it
* Container cannot be created anymore due missing definition

**Possible Solution**  
Check in `addToCollector` is it an alias or an actual definition

**Additional context**

### PR DESCRIPTION
**Pull request by shyim**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38055 
| License       | MIT
| Doc PR        | 

The `getDefinition` call in `addToCollector` does not work when the service is decorated. Also instances will be added with the decoration name. This looks weird in the profiler. I have changed it to prefer the attribute name.

Before:
image

After: (`\Shopware\Storefront\Framework\Cache\CacheDecorator` did go into `cache.object`)
image

### CODE REVIEW

File: src/Symfony/Component/Cache/Tests/DependencyInjection/CacheCollectorPassTest.php [hunk 1]
```diff
@@ -48,16 +50,51 @@ public function testProcess()
...
         $this->assertSame(TraceableTagAwareAdapter::class, $container->getDefinition('tagged_fs')->getClass());
 
         $this->assertSame(TraceableAdapter::class, $container->findDefinition('.php.inner')->getClass());
-        $this->assertSame(TraceableTagAwareAdapter::class, $container->getDefinition('php')->getClass());
+        $this->assertSame(TagAwareAdapter::class, $container->getDefinition('php')->getClass());
 
         $this->assertFalse($collector->isPublic(), 'The "data_collector.cache" should be private after processing');
     }
+
+    public function testProcessCacheObjectsAreDecorated(): void
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Cache/Tests/DependencyInjection/CacheCollectorPassTest.php:65]: please remove `: void`

**Review by nicolas-grekas — APPROVED** [review]
Thanks, I just have one minor comment, and good to go on my side.

File: src/Symfony/Component/Cache/Tests/DependencyInjection/CacheCollectorPassTest.php (hunk 1 above)
Comment (shyim) [reply src/Symfony/Component/Cache/Tests/DependencyInjection/CacheCollectorPassTest.php:65]: Removed :blush:

**Comment by fabpot** [comment]
Thank you @shyim.
