### PR TITLE
[DependencyInjection] Escape parameters before resolving env placeholders

### LINKED ISSUE #59594: [DI] `ContainerBuilder` can throw when resolving unescaped parameters
### Symfony version(s) affected

≥ 3.3.7

### Description

When `ContainerBuilder::compile` is called with `$resolveEnvPlaceholders`, it will end up creating a new `ParameterBag` from the old one: https://github.com/symfony/symfony/blob/05d5bb3b6a887c55b65d1247472d23e5dcbaa4f3/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L825-L827

With `true` as its second parameter, `resolveEnvPlaceholders` will start by calling the bag’s `resolveValue` method: https://github.com/symfony/symfony/blob/05d5bb3b6a887c55b65d1247472d23e5dcbaa4f3/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L1480-L1482

Problem is, at this point the parameter bag already has been resolved by the `ResolveParameterPlaceHoldersPass`, which means parameters’ value have been unescaped: https://github.com/symfony/symfony/blob/05d5bb3b6a887c55b65d1247472d23e5dcbaa4f3/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php#L161

Since unescaped parameters can appear as if they contain a placeholder, those will trigger a `ParameterNotFoundException`.

### How to reproduce

```php
$builder = new ContainerBuilder();
$builder->setParameter('foo', '%%bar%%');
$builder->compile(true);
```

> Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "bar".

### Possible Solution

I guess an easy fix would be to ignore `ParameterNotFoundException`s when creating the new `ParameterBag`? It feels like addressing a symptom rather than a cause though.

### Additional Context

Spotted while investigating #59028.

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59594
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/ContainerBuilder.php [hunk 1]
```diff
@@ -1728,4 +1728,20 @@ private function inVendors(string $path): bool
 
         return $this->pathsInVendor[$path] = false;
     }
+
+    private function escapeParameters(array $parameters): array
+    {
+        $params = [];
+        foreach ($parameters as $k => $v) {
+            if (\is_array($v)) {
+                $params[$k] = $this->escapeParameters($v);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: a match would be nice instead

Comment (MatTheCat) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: This was copied from the `XmlDumper`; will update

Comment (MatTheCat) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: Should I also replace the loop by a call to `array_map`?

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: not sure

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @MatTheCat.
