### PR TITLE
[Config] Deprecate setting a default value to a node that is required

### LINKED ISSUE #62076: [Config] The config builder should reject required parameter with a default value
### Description

`isRequired()` is not compatible with a default value, as the default value is ignored. And exception should be thrown when a config tree node has both.

This can be deprecated in 7.4 and fail in 8.0.

### Example

The following config tree should fail before processing a configuration.
```
$definition->rootNode()->children()
    ->scalarNode('api_key')
    ->defaultValue('%env(OPENAI_API_KEY)%')
    ->info('OpenAI API Key used to authenticate with the OpenAI API');
```

Found with https://github.com/openai-php/symfony/issues/36, fixed by https://github.com/openai-php/symfony/pull/37/commits/2e6d30a4370ec7f0bbdaaa35315989509d91607a

### PR DESCRIPTION
**Pull request by GromNaN**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Issues        | Fix #62076
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/Config/Tests/Definition/Builder/NodeDefinitionTest.php [hunk 1]
```diff
@@ -60,10 +68,50 @@ public function testDocUrlWithoutPackage()
 
     public function testUnknownPackageThrowsException()
     {
+        $node = new ArrayNodeDefinition('node');
```
Comment (GromNaN) [inline src/Symfony/Component/Config/Tests/Definition/Builder/NodeDefinitionTest.php:71]: Moving `expectException` just before the call that produces it to be more specific.

File: src/Symfony/Component/Config/Tests/Definition/Builder/NodeDefinitionTest.php [hunk 2]
```diff
@@ -60,10 +68,50 @@ public function testDocUrlWithoutPackage()
...
+        $node->isRequired()->defaultValue($defaultValue);
+    }
+
+    public static function provideDefinitionClassesAndDefaultValues()
+    {
+        yield [ArrayNodeDefinition::class, []];
+        yield [ScalarNodeDefinition::class, null];
+        yield [BooleanNodeDefinition::class, false];
+        yield [StringNodeDefinition::class, 'default'];
+        yield [VariableNodeDefinition::class, 'default'];
```
Comment (GromNaN) [inline src/Symfony/Component/Config/Tests/Definition/Builder/NodeDefinitionTest.php:115]: Testing various child classes as they could have different behaviors.

**Review by stof — APPROVED** [review]

File: src/Symfony/Component/Config/Definition/Builder/NodeDefinition.php [hunk 3]
```diff
@@ -178,6 +178,11 @@ public function getNode(bool $forceRootNode = false): NodeInterface
      */
     public function defaultValue(mixed $value): static
     {
+        if ($this->required) {
+            // throw new InvalidDefinitionException(sprintf('You cannot set a default value to the node "%s" as it is required.', $this->name));
+            trigger_deprecation('symfony/config', '7.4', 'Setting a default value to the node "%s" is deprecated when it is required.', $this->name);
```
Comment (derrabus) [inline src/Symfony/Component/Config/Definition/Builder/NodeDefinition.php]: "it" is a bit ambigous in this context.

```suggestion
            trigger_deprecation('symfony/config', '7.4', 'Setting a default value to a required node is deprecated. Remove the default from node "%s" or make it optional.', $this->name);
```

File: src/Symfony/Component/Config/Definition/Builder/NodeDefinition.php [hunk 4]
```diff
@@ -191,6 +196,11 @@ public function defaultValue(mixed $value): static
      */
     public function isRequired(): static
     {
+        if ($this->default) {
+            // throw new InvalidDefinitionException(sprintf('You cannot set the node "%s" as required as it has a default value.', $this->name));
+            trigger_deprecation('symfony/config', '7.4', 'Setting the node "%s" as required is deprecated when it has a default value.', $this->name);
```
Comment (derrabus) [inline src/Symfony/Component/Config/Definition/Builder/NodeDefinition.php]:
```suggestion
            trigger_deprecation('symfony/config', '7.4', 'Flagging a node with a default value as required is deprecated. Remove the default from node "%s" or make it optional.', $this->name);
```

**Comment by GromNaN** [comment]
I updated the messages of the deprecation and the future exceptions.

**Review by xabbuh — APPROVED** [review]

File: UPGRADE-7.4.md [hunk 5]
```diff
@@ -22,6 +22,7 @@ Config
 ------
 
  * Deprecate accessing the internal scope of the loader in PHP config files, use only its public API instead
+ * Deprecate setting a default value to a node that is required, and vice versa
```
Comment (alexandre-daubois) [inline UPGRADE-7.4.md:25]:
```suggestion
 * Deprecate setting a default value to a node that is required
```

I think it's understandable like this?

**Review by alexandre-daubois — APPROVED** [review]

File: UPGRADE-7.4.md (hunk 5 above)
Comment (GromNaN) [reply UPGRADE-7.4.md:25]: Sorry I missed your comment and merged.
I used a different wording for the 8.0 branch: https://github.com/symfony/symfony/pull/62109
