### PR TITLE
[ErrorHandler] Add debug argument to decide whether debug page is shown or not

### LINKED ISSUE #35448: ErrorHandler: Exception with full stack trace is dumped in prod when it occurs before the kernel.request event
**Symfony version(s) affected**: 4.4, 5.0

**Description**  
When an exception occurs before the `kernel.request` event (for example during `Kernel::boot`), then the exception is dumped with full stack trace, also in prod.

**How to reproduce**  
Set `APP_ENV=prod` and throw an exception in `Kernel::boot`.

**Possible Solution**  
Initialize `Symfony\Component\ErrorHandler\ErrorHandler::$scopedErrors` to `0` instead of `0x1FFF`.

Or alter the construction of `Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer` not to rely on `$this->scopedErrors` being `0` to determine if the `$debug` parameter should be true.
Currently it's initialized as follows: `new HtmlErrorRenderer(0 !== $this->scopedErrors)`
(`Symfony\Component\ErrorHandler\ErrorHandler` line 700)

`$scopedErrors` is currently set to `0` (when `kernel.debug` is `false`) by calling the `Symfony\Component\ErrorHandler\ErrorHandler::scopeAt` method in `Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure` on line 96, which is trigged in the `kernel.request` event.

### PR DESCRIPTION
**Pull request by yceruto**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35448
| License       | MIT
| Doc PR        | -

This ensures that the debug page (with stack trace) won't be (by default) displayed in non-CLI context when an early error occurs (after FB::boot()) in non-debug mode (prod). And `Debug::enable()` will enable it explicitly.

### CODE REVIEW

File: src/Symfony/Component/ErrorHandler/ErrorHandler.php [hunk 1]
```diff
@@ -367,6 +370,11 @@ public function screamAt(int $levels, bool $replace = false): int
         return $prev;
     }
 
+    public function setDebug(bool $debug): void
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ErrorHandler/ErrorHandler.php]: not sure we need the method, I'd suggest removing it since we don't use it.

**Comment by yceruto** [comment]
@nicolas-grekas I've simplied it a bit more. 
It should be ready now.

**Review by nicolas-grekas — APPROVED** [review]
Nice!

**Comment by nicolas-grekas** [comment]
Thank you @yceruto.
