### PR TITLE
[Serializer] Add `AbstractNormalizerContextBuilder::defaultConstructorArguments()`method

### LINKED ISSUE #54616: [Serializer] Typo in name of AbstractNormalizerContextBuilder::withDefaultContructorArguments() method
### Symfony version(s) affected

6.4

### Description

In the name of `\Symfony\Component\Serializer\Context\Normalizer\AbstractNormalizerContextBuilder::withDefaultContructorArguments()`, `Contructor` (no `s`) is used instead of `Constructor`.

(Same issue for the parameter name)

### How to reproduce

Read method signature of

https://github.com/symfony/symfony/blob/05a8fcc9a9932a2dc36c846c844b4b96b210b4ca/src/Symfony/Component/Serializer/Context/Normalizer/AbstractNormalizerContextBuilder.php#L115

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ghost**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Closes #54616 
| License       | MIT

cherry-picked from https://github.com/symfony/symfony/pull/54643 with deprecation line removed.

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Serializer/Context/Normalizer/AbstractNormalizerContextBuilder.php [hunk 1]
```diff
@@ -104,17 +104,25 @@ public function withAllowExtraAttributes(?bool $allowExtraAttributes): static
     }
 
     /**
-     * Configures an hashmap of classes containing hashmaps of constructor argument => default value.
+     * @param array<class-string, array<string, mixed>>|null $defaultContructorArguments
+     */
+    public function withDefaultContructorArguments(?array $defaultContructorArguments): static
```
Comment (OskarStark) [inline src/Symfony/Component/Serializer/Context/Normalizer/AbstractNormalizerContextBuilder.php:109]:
```suggestion
    public function withDefaultConstructorArguments(?array $defaultConstructorArguments): static
```

File: src/Symfony/Component/Serializer/Context/Normalizer/AbstractNormalizerContextBuilder.php [hunk 2]
```diff
@@ -104,17 +104,25 @@ public function withAllowExtraAttributes(?bool $allowExtraAttributes): static
...
+    {
+        return self::withDefaultConstructorArguments($defaultContructorArguments);
```
Comment (OskarStark) [inline src/Symfony/Component/Serializer/Context/Normalizer/AbstractNormalizerContextBuilder.php:111]:
```suggestion
        return self::withDefaultConstructorArguments($defaultConstructorArguments);
```

**Review by OskarStark — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @javaDeveloperKid.
