### PR TITLE
Extract no type `@param` annotation with `PhpStanExtractor`

### LINKED ISSUE #59923: [PropertyInfo] Extract no type param annotation with `PhpStanExtractor`
### Symfony version(s) affected

7.2

### Description

An `Undefined property` error is issued when a `@param` annotation has a name without typing (PhpStanExtractor context).

Undefined property: PHPStan\PhpDocParser\Ast\PhpDoc\TypelessParamTagValueNode::$type
src/Symfony/Component/PropertyInfo/Extractor/PhpStanExtractor.php:219

### How to reproduce

```php
class InvalidDummy
{
    /**
     * @param $data
     */
    public function setData($data)
    {
    }
}
```

Variable `$extractor` is an instance of `Symfony\Component\PropertyInfo\Extractor\PhpStanExtractor`
```php
$extractor->getType(InvalidDummy::class, 'data');
```

### Possible Solution

Update method `getType` in `PhpStanExtractor` to add a check on `TypelessParamTagValueNode`

```php
if ($tagDocNode->value instanceof InvalidTagValueNode || $tagDocNode->value instanceof TypelessParamTagValueNode) {
    continue;
}

if ($tagDocNode->value instanceof ParamTagValueNode && null === $prefix && $tagDocNode->value->parameterName !== '$'.$property) {
    continue;
}

try {
    $types[] = $this->stringTypeResolver->resolve((string) $tagDocNode->value->type, $typeContext);
} catch (UnsupportedException) {
}
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by thomasdubuffet**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59923
| License       | MIT

### CODE REVIEW

**Comment by mtarld** [comment]
Hey @thomasdubuffet, thanks for taking care of this! The issue seems to be there as well in 6.4, could you instead target the 6.4 branch please?

**Comment by thomasdubuffet** [comment]
@mtarld 

> Hey @thomasdubuffet, thanks for taking care of this! The issue seems to be there as well in 6.4, could you instead target the 6.4 branch please?

Unless I am mistaken, there is no `getType` method on this extractor in symfony 6.4. And, the `getTypes` method of this extractor uses the `getTypes` method of the helper `PhpStanTypeHelper`which checks the node (`ParamTagValueNode|ReturnTagValueNode|VarTagValueNode`).

**Comment by mtarld** [comment]
My bad, didn't notice that `if` in `PhpStanTypeHelper` the first time.

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Component/PropertyInfo/Extractor/PhpStanExtractor.php [hunk 1]
```diff
@@ -206,7 +207,7 @@ public function getType(string $class, string $property, array $context = []): ?
         $types = [];
 
         foreach ($docNode->getTagsByName($tag) as $tagDocNode) {
-            if ($tagDocNode->value instanceof InvalidTagValueNode) {
+            if ($tagDocNode->value instanceof InvalidTagValueNode || $tagDocNode->value instanceof TypelessParamTagValueNode) {
```
Comment (mtarld) [inline src/Symfony/Component/PropertyInfo/Extractor/PhpStanExtractor.php]: Maybe we can make it explicit instead?
```suggestion
            if (!$tagDocNode->value instanceof ParamTagValueNode && !$tagDocNode->value instanceof ReturnTagValueNode && !$tagDocNode->value instanceof VarTagValueNode) {
```

Comment (thomasdubuffet) [reply src/Symfony/Component/PropertyInfo/Extractor/PhpStanExtractor.php]: I have updated it to be more explicit.

**Review by mtarld — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @thomasdubuffet.
