### PR TITLE
[Mime] Escape commas in address names

### LINKED ISSUE #39416: [Mailer] Postmark Transport doesn't escape commas in name of Address
This is my first bug report / contribution to Symfony (or any other open source project), so I hope I did it correctly. Otherwise, just let me know.

**Symfony version(s) affected**: 4.4 - 5.2

**Description**  
The Postmark API expects multiple addresses to be split by a comma. When the name of an Address contains a comma, this comma is not escaped. So the Postmark API thinks it's getting multiple addresses, while it's actually one address with a comma in the name.

**How to reproduce**
See https://github.com/scvandenbraak/symfony-postmark-mailer-comma-bug for example code and README.

When you run the simple example without a Postmark Server token, you'll see the output below, showing the comma has not been escaped.
```
string(24) "My, Name <me@domain.tld>"
```

You will get the error if you run a real example with Postmark:
```
In PostmarkApiTransport.php line 59:
Unable to send an email: Error parsing 'To': Illegal email address 'My'. It must contain the '@' symbol. (code 300).
```

**Possible Solution**  
Use quotes around the name. This can be fixed in several places:
1. Method `getPayload` in `Transport/PostmarkApiTransport.php` of `symfony/postmark-mailer`.
2. Method `stringifyAddresses` in `Transport/AbstractTransport.php` of `symfony/mailer`.
3. Method `toString` in `Address.php` of `symfony/mime`.

I would guess option 3 is the best, but that depends on which other components rely on this method and it the extra quotes could brake anything. I can also make a PR when I know where it should be fixed.

**Additional context**  
See API description "Multiple addresses are comma separated." at "To" on https://postmarkapp.com/developer/api/email-api#send-a-single-email.

### PR DESCRIPTION
**Pull request by YaFou**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39416
| License       | MIT
| Doc PR        | --

Before:
```php
$address = new Address('fabien@symfony.com', 'Fabien, Potencier');
$address->toString(); // Fabien, Potencier <fabien@symfony.com> -> Interpreted like two emails
```

After:
```php
$address = new Address('fabien@symfony.com', 'Fabien, Potencier');
$address->toString(); // "Fabien, Potencier" <fabien@symfony.com>
```

### CODE REVIEW

File: src/Symfony/Component/Mime/Address.php [hunk 1]
```diff
@@ -77,7 +77,19 @@ public function getEncodedAddress(): string
...
+    }
+
+    public function getEncodedName(): string
+    {
+        $name = $this->getName();
+
+        if (preg_match('/,/u', $name)) {
+            $name = preg_replace('/"/u', '\"', $name);
+            $name = sprintf('"%s"', $name);
+        }
```
Comment (fbourigault) [inline src/Symfony/Component/Mime/Address.php:87]: Is it possible to detect an already encoded name to avoid double escaping?

Comment (YaFou) [reply src/Symfony/Component/Mime/Address.php:87]: You mean that the developer will instanciate the Address like this:
```php
new Address('fabien@symfony.com', '"Fabien, Potencier"');
```

Comment (fbourigault) [reply src/Symfony/Component/Mime/Address.php:87]: Yes, but is this something wanted?

Comment (sstok) [reply src/Symfony/Component/Mime/Address.php:87]: Wouldn't it be easier and (in general terms) better to always quote the name?

Comment (Cartman34) [reply src/Symfony/Component/Mime/Address.php:87]: This would be better if the name is quoted every time because, an issue may occur with some other cases, like @ < >...
Or is there any restriction with quoting ?

Comment (YaFou) [reply src/Symfony/Component/Mime/Address.php:87]: I will change it to make the encoded address always quoted.

Comment (YaFou) [reply src/Symfony/Component/Mime/Address.php:87]: Done

File: src/Symfony/Component/Mime/Address.php [hunk 2]
```diff
@@ -77,7 +77,12 @@ public function getEncodedAddress(): string
 
     public function toString(): string
     {
-        return ($n = $this->getName()) ? $n.' <'.$this->getEncodedAddress().'>' : $this->getEncodedAddress();
+        return ($n = $this->getEncodedName()) ? $n.' <'.$this->getEncodedAddress().'>' : $this->getEncodedAddress();
+    }
+
+    public function getEncodedName(): string
+    {
+        return sprintf('"%s"', str_replace('/"/u', '\"', $this->getName()));
```
Comment (sstok) [inline src/Symfony/Component/Mime/Address.php]: This was `preg_replace`, `str_replace` doesn't use modifiers 😊 

FYI. https://www.php.net/addcslashes as the current implementation doesn't protect against double escaping.

Comment (YaFou) [reply src/Symfony/Component/Mime/Address.php]: Yes of course I think I was tired 😅

Comment (YaFou) [reply src/Symfony/Component/Mime/Address.php]: Done

**Review by maxhelias — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @YaFou.
