### PR TITLE
[Messenger] fix retry of messages losing the routing key and properties

### LINKED ISSUE #32994: [Messenger] Messages with AmqpStamp($routingKey) and direct RabbitMQ exchange are not retry-able
**Symfony version(s) affected**: 4.3.3
**RabbitMQ version(s) affected**: 3.7.17

**Description**  
Symfony Messenger by default creates **fanout** exchange `Messages` and all queues are receiving any messages published to the bus. In our project this is not acceptable. We thought that Messenger routing would be enough to place particular messages into corresponding queues. It was not.

To route some particular message into (and only to) configured queue, you need to configure Messenger to create a **direct** exchange, bind queues with routing key and finally to dispatch message with `AmqpStamp()` with said routing key:

```yaml
framework:
    messenger:
        transports:
            auth_signup:
                dsn: '%rabbitmq_connection%'
                options:
                    exchange: { type: direct }
                    queues:
                        auth_signup:
                            binding_keys: [!php/const App\RoutingKeysDirect::AUTH_SIGNUP]
            emails_transactional:
                dsn: '%rabbitmq_connection%'
                options:
                    exchange: { type: direct }
                    queues:
                        emails_transactional:
                            binding_keys: [!php/const App\RoutingKeysDirect::EMAILS_TRANSACTIONAL]

        routing:
            App\RegistrationFinishedMessage: auth_signup
            App\EmailMessage: emails_transactional
```

With this setup we defined two queues bound to **direct** default exchange with routing key. We can inspect setup via management:

exchanges

queues

We can inspect binding of the queue in detail, we see it is really bound to exchange with our routing-key:

sm_qas

Now we dispatch message with routing-key like this:

```php
$message = new App\RegistrationFinishedMessage('bla bla');
$messageRoutingKey = App\RoutingKeysDirect::AUTH_SIGNUP;

$bus->dispatch($message, [new AmqpStamp($messageRoutingKey)]);
```

Problem is, this setup will not correctly handle message retrying with selected *retryPolicy*. I step-debugged code today and found that for correct enqueue to *delayed retry* queue [there must by routing-key present](https://github.com/symfony/messenger/blob/ea2a2f12841403b357f4740978b04cf2bba84859/Transport/AmqpExt/Connection.php#L460) in form of `AmqpStamp` in Envelope object.

This Stamp is however not serialized into message because [it is implementing `NonSendableStampInterface`](https://github.com/symfony/messenger/blob/ea2a2f12841403b357f4740978b04cf2bba84859/Transport/AmqpExt/AmqpStamp.php#L20). I don't know exact reasons behind this, but changing interface to `StampInterface` will solve this problem!

However a new problem will now emerge - shoveling the message into failed transport after message reaches configured retryCount in retryPolicy (default is 3).
After that, message should be enqueued to *"failed"* transport if configured. In our setup (see above) it will fail with error

```
Server channel error: 406, message: PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'm
  essages' in vhost '/': received 'fanout' but current is 'direct'
```

This is solvable pretty easily, again by defining exchange type for failed transport to **direct**

```yaml
framework:
    messenger:
        failure_transport: failed
        transports:
            failed:
                dsn: '%rabbitmq_connection%'
                options:
                    exchange: { type: direct }
                    queues:
                        failed: ~

            ... other transports
```

However our message will still not be enqueued to failed transport after reaching retryCount. Thats because our previous fix (changing interface of `AmqpStamp`) is now doing bad things when enqueuing failed message - message have routing-key attached to the Envelope which is not wanted!

To solve this second problem we must strip this Stamp from Envelope [in `SendFailedMessageToFailureTransportListener`](https://github.com/symfony/messenger/blob/ea2a2f12841403b357f4740978b04cf2bba84859/EventListener/SendFailedMessageToFailureTransportListener.php#L63). Code should look like this:

```php
        $envelope = $envelope->withoutAll(ReceivedStamp::class)
            ->withoutAll(TransportMessageIdStamp::class)
            ->withoutAll(AmqpStamp::class)  // THIS LINE ADDED
            ->with(new SentToFailureTransportStamp($event->getReceiverName()))
            ->with(new DelayStamp(0))
            ->with(new RedeliveryStamp(0, $this->failureSenderAlias, $throwable->getMessage(), $flattenedException));
```

Now everything is working as expected!

**To sumarize**  
- Symfony Messenger creates by default `fanout` exchange
- that eliminates routing to specified queues
- to achieve above we must configure `direct` default exchange
- now we need to attach `AmqpStamp($routingKey)` with message when dispatching
- for messages in this setup retrying is not working
- it can be solved by changing interface of `AmpqStamp` from `NonSendableStampInterface` to `StampInterface`
- second problem will emerge with this setup - failed transport is not working when configured
- we must define `direct` exchange for failed transport as well
- we must strip `AmqpStamp` from envelope in listener from message to be correctly enqueued to failed transport

Hope this bug report is explaining our problems in understable way.
Wish all the best.

### PR DESCRIPTION
**Pull request by Tobion**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #32994 
| License       | MIT
| Doc PR        |

Messages sent for retry in rabbitmq lost the routing key and properties like the priority. Now we read those original properties and sent the retry message with the same properties (unless those properties have already been set manually before).

### CODE REVIEW

File: src/Symfony/Component/Messenger/Transport/AmqpExt/Connection.php [hunk 1]
```diff
@@ -225,7 +225,7 @@ private function publishWithDelay(string $body, array $headers, int $delay, Amqp
     private function publishOnExchange(\AMQPExchange $exchange, string $body, string $routingKey = null, array $headers = [], AmqpStamp $amqpStamp = null)
     {
         $attributes = $amqpStamp ? $amqpStamp->getAttributes() : [];
-        $attributes['headers'] = array_merge($headers, $attributes['headers'] ?? []);
+        $attributes['headers'] = array_merge($attributes['headers'] ?? [], $headers);
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Transport/AmqpExt/Connection.php]: This looks subjective either way (or am I missing something)? The `$headers` comes ultimately from the serializer. So, should headers from the `AmqpStamp` win or headers from the serialization of the message. I dunno :). But I was curious what motivated the change.

File: src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpSender.php [hunk 2]
```diff
@@ -47,20 +47,22 @@ public function send(Envelope $envelope): Envelope
...
             $contentType = $encodedMessage['headers']['Content-Type'];
             unset($encodedMessage['headers']['Content-Type']);
 
-            $attributes = $amqpStamp ? $amqpStamp->getAttributes() : [];
-
-            if (!isset($attributes['content_type'])) {
-                $attributes['content_type'] = $contentType;
-
-                $amqpStamp = new AmqpStamp($amqpStamp ? $amqpStamp->getRoutingKey() : null, $amqpStamp ? $amqpStamp->getFlags() : AMQP_NOPARAM, $attributes);
+            if (!$amqpStamp || !isset($amqpStamp->getAttributes()['content_type'])) {
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpSender.php]: This feels like the opposite of the merging logic in `Connection::publishOnExchnage()`. In that method, `headers` from the serializer win over headers from the `AmqpStamp`. But here, we're saying: "only use the `Content-Type` from the serializer if it is NOT already set on `AmqpStamp` (i.e. `AmqpStamp` wins)

File: src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpSender.php [hunk 3]
```diff
@@ -47,20 +47,22 @@ public function send(Envelope $envelope): Envelope
...
+                $amqpStamp = AmqpStamp::createWithAttributes(['content_type' => $contentType], $amqpStamp);
             }
         }
 
+        $amqpReceivedStamp = $envelope->last(AmqpReceivedStamp::class);
+        if ($amqpReceivedStamp instanceof AmqpReceivedStamp) {
+            $amqpStamp = AmqpStamp::createFromAmqpEnvelope($amqpReceivedStamp->getAmqpEnvelope(), $amqpStamp);
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpSender.php]: Will this work when it's being sent to the failure transport... and the failure transport is a direct AMQP exchange that relies on the `default_publish_routing_key` config to route to some "failure" queue?

I think flow would be:

A) Message is received for last retry
B) Message fails again and so is sent to the failure transport.
C) This code will see the routingKey from the original message (e.g. `foo`) and set it on the `AmqpStamp`
D) When this code is forwarded into `Connection::publish()` below, the routing key (`foo`) in `AmqpStamp` will be used instead of the `default_publish_routing_key` from the "failure transport".
E) Message will be sent once again with the `foo` routing key, instead of the one from the failure transport.

If I'm correct, on a high level, it *seems* like we want to do this trick *unless* we detect that the message is being sent through a *different* transport than it was originally sent through.... or maybe the "failure transport" is added as an edge-case.

File: src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpSender.php (hunk 2 above)
Comment (Tobion) [reply src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpSender.php]: If people set the content-type manually on the envelope, we don't want to overwrite this. THis is how it has been before already.

File: src/Symfony/Component/Messenger/Transport/AmqpExt/Connection.php (hunk 1 above)
Comment (Tobion) [reply src/Symfony/Component/Messenger/Transport/AmqpExt/Connection.php]: This just gives headers from the serialization more prio than headers from the stamp. As the headers from the stamp are copied for retry, this just makes more sense now (in case re-serialization returns different headers).

File: src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpSender.php (hunk 3 above)
Comment (Tobion) [reply src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpSender.php]: What you described is also what is described in #32994 but the problem is that the failed transport should not need to be direct. I'll answer there.

Comment (weaverryan) [reply src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpSender.php]: Documenting that a failure transport should not be direct is a valid solution I think. But:

> So retrying from the failure transport might not work if the routing key is different suddenly.

I don't think I understand what you're saying here. Assuming we successfully deliver a message to the routing transport (by setting the routing key correctly for the situation), what problem would the routing key being different cause? At that point, the routing key isn't used anymore: the `messenger:failed:retry` command consumes from the failure transport and dispatches into the bus. If it failed *again*, then re-using the "last routing key" (what this PR does) would correctly send it back to the failure transport, right?

Comment (Tobion) [reply src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpSender.php]: People could use the routing key using the AmqpReceivedStamp in their handler to make decisions. But again all these things are edge cases I would not worry about unless you have a certain change request in mind?

Comment (weaverryan) [reply src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpSender.php]: Well, the options are:

1) document not to use a direct transport as your failure transport.

2) somehow add code here for the failure transport situation: like look for the RedeliveredToFailureTransportStamp... or something cleaner (not sure what). If there’s no reasonable way to do this, then option 1 becomes the only option.

Comment (Tobion) [reply src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpSender.php]: Honestly there is nothing to document or fix here. Your case is just one of endless configuration possibilities. I can also configure the failure transport with the appropriate binding keys and voila it still works with the original routing keys. We shouldn't enforce or document a random edge case here that does not apply always.

Comment (Tobion) [reply src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpSender.php]: What this PR is about is publishing retry/failure with the same routing key and priority etc as the original message. And this is absolutely the right and logical thing to do because retry message should be the same as the original ones.

Comment (Tobion) [reply src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpSender.php]: The default is a fanout exchange. So we're covering 99% of all cases. If someone changes it to a direct exchange for failure, it's not the messenger job to interfere with this and make certain assumptions.

**Review by weaverryan — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Tobion.

File: src/Symfony/Component/Messenger/Transport/AmqpExt/Connection.php (hunk 1 above)
Comment (mleczakm) [reply src/Symfony/Component/Messenger/Transport/AmqpExt/Connection.php]: This was huge BC break, it broke our app and make overriding `type` header impossible.
