### PR TITLE
[Messenger] remove several messages with command messenger:failed:remove

### LINKED ISSUE #34940: Allow to pass in multiple ids to remove message command
**Description**  
[Messenger component]
I have many failed messages that I want to get rid off but I have to run `bin/console messenger:failed:remove {id}` per each. It would be nice if the command allows a list of ids to be passed in

**Example**  
`bin/console messenger:failed:remove 10 11 12 13 [...]`

### PR DESCRIPTION
**Pull request by nikophil**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #34940
| License       | MIT

command `messenger:failed:remove` now accepts an array of ids. If several provided, they are not displayed unless option `--show-messages` is passed

### CODE REVIEW

File: src/Symfony/Component/Messenger/Command/FailedMessagesRemoveCommand.php [hunk 1]
```diff
@@ -35,16 +35,17 @@ protected function configure(): void
...
-                new InputArgument('id', InputArgument::REQUIRED, 'Specific message id to remove'),
+                new InputArgument('ids', InputArgument::REQUIRED | InputArgument::IS_ARRAY, 'Specific message ids to remove'),
                 new InputOption('force', null, InputOption::VALUE_NONE, 'Force the operation without confirmation'),
+                new InputOption('show-messages', null, InputOption::VALUE_NONE, 'Display messages before removing it (if multiple ids are given)'),
             ])
-            ->setDescription('Remove a message from the failure transport.')
+            ->setDescription('Remove given messages from the failure transport.')
             ->setHelp(<<<'EOF'
-The <info>%command.name%</info> removes a message that is pending in the failure transport.
+The <info>%command.name%</info> removes given message that are pending in the failure transport.
```
Comment (jschaedl) [inline src/Symfony/Component/Messenger/Command/FailedMessagesRemoveCommand.php]: `s/message/messages`

File: src/Symfony/Component/Messenger/Command/FailedMessagesRemoveCommand.php [hunk 2]
```diff
@@ -35,16 +35,17 @@ protected function configure(): void
     {
         $this
             ->setDefinition([
-                new InputArgument('id', InputArgument::REQUIRED, 'Specific message id to remove'),
+                new InputArgument('ids', InputArgument::REQUIRED | InputArgument::IS_ARRAY, 'Specific message ids to remove'),
```
Comment (jschaedl) [inline src/Symfony/Component/Messenger/Command/FailedMessagesRemoveCommand.php]: To be consistent with the `messenger:failed:retry` I suggest to use `id` instead of `ids`. See: https://github.com/symfony/symfony/blob/e60a876201b5b306d0c81a24d9a3db997192079c/src/Symfony/Component/Messenger/Command/FailedMessagesRetryCommand.php#L59

Comment (fancyweb) [reply src/Symfony/Component/Messenger/Command/FailedMessagesRemoveCommand.php]: And changing to "ids" is also not backward compatible.

Comment (nikophil) [reply src/Symfony/Component/Messenger/Command/FailedMessagesRemoveCommand.php]: you're right, i've changed the argument name

File: src/Symfony/Component/Messenger/Command/FailedMessagesRemoveCommand.php [hunk 3]
```diff
@@ -60,29 +61,37 @@ protected function execute(InputInterface $input, OutputInterface $output)
...
-        $this->removeSingleMessage($input->getArgument('id'), $receiver, $io, $shouldForce);
+        $ids = $input->getArgument('id');
+        $shouldDisplayMessages = $input->getOption('show-messages') || 1 === \count($ids);
+        $this->removeSingleMessage($ids, $receiver, $io, $shouldForce, $shouldDisplayMessages);
 
         return 0;
     }
 
-    private function removeSingleMessage(string $id, ReceiverInterface $receiver, SymfonyStyle $io, bool $shouldForce)
+    private function removeSingleMessage(array $ids, ReceiverInterface $receiver, SymfonyStyle $io, bool $shouldForce, bool $shouldDisplayMessages): void
```
Comment (jschaedl) [inline src/Symfony/Component/Messenger/Command/FailedMessagesRemoveCommand.php]: I think the method name is now misleading as it gets an array of ids as argument. What about `removeMessages(...)`?

Comment (nikophil) [reply src/Symfony/Component/Messenger/Command/FailedMessagesRemoveCommand.php]: :+1:

**Comment by nikophil** [comment]
i don't understand why some tests are failing, in another component :thinking:

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nikophil.
