### PR TITLE
[HttpFoundation] Fix invalid ID not regenerated with native PHP file sessions

### LINKED ISSUE #46993: [HttpFoundation] [Session] Invalid ID not regenerated with native PHP file sessions
### Symfony version(s) affected

6.1.2 and others

### Description

I use native PHP file configuration for my session management and I want that invalid session ID be replaced by new one in order to avoid error #45755.

The solution was given by PR #46249 but the newer PR #46678 limits too far its application with the condition `'files' === $this->saveHandler->getSaveHandlerName()`.

Indeed, since #24523 the service `session.handler.native_file`  wraps `NativeFileSessionHandler`  into `StrictSessionHandler` which do not extend `\SessionHandler`. So [`NativeSessionStorage` wraps the handler](https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L419) in `SessionHandlerProxy` and this one sets `$this->saveHandlerName = 'user'`.

### How to reproduce

```
# php.ini
session.save_handler = files
```

Both
```yaml
# framework.yml
framework:
    session:
        handler_id: session.handler.native_file
        storage_factory_id: session.storage.factory.native
```
and 
```yaml
# framework.yml
framework:
    session:
        handler_id: null
        storage_factory_id: session.storage.factory.native
```
produces a strict handler wrapped into a proxy handler which has `saveHandlerName = user` whereas sessions are managed by files.

### Possible Solution

To get the wanted behaviour in my project, I create a custom handler which extends `SessionHandlerProxy` and wraps the chained `NativeFileSessionHandler`  and `StrictSessionHandler`. The difference I make is to set `saveHandlerName = 'files'` in the proxy constructor.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ghost**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #46993, #47126
| License       | MIT

Inside the [`SessionHandlerProxy`](https://github.com/symfony/symfony/blob/818d4dda7de778726123bc6bd49488959d4186e7/src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php) class, the code defines `$this->saveHandlerName` to `\ini_get('session.save_handler')` when `$handler` is an instance of [`\SessionHandler`](https://www.php.net/manual/en/class.sessionhandler.php).
https://github.com/symfony/symfony/blob/818d4dda7de778726123bc6bd49488959d4186e7/src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php#L24-L25

But inside the [`NativeSessionStorage`](https://github.com/symfony/symfony/blob/818d4dda7de778726123bc6bd49488959d4186e7/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php) class, the code create an instance of [`StrictSessionHandler`](https://github.com/symfony/symfony/blob/818d4dda7de778726123bc6bd49488959d4186e7/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php) that doesn't inherit from [`\SessionHandler`](https://www.php.net/manual/en/class.sessionhandler.php) and is passed to the [`SessionHandlerProxy`](https://github.com/symfony/symfony/blob/818d4dda7de778726123bc6bd49488959d4186e7/src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php) constructor.
https://github.com/symfony/symfony/blob/818d4dda7de778726123bc6bd49488959d4186e7/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L422-L424

Therefore, we could create a `isWrapper()` method inside the [`StrictSessionHandler`](https://github.com/symfony/symfony/blob/818d4dda7de778726123bc6bd49488959d4186e7/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php) class to check if the wrapped handler is an internal PHP session handler ([`\SessionHandler`](https://www.php.net/manual/en/class.sessionhandler.php)), just like [`AbstractProxy::isWrapper()`](https://github.com/symfony/symfony/blob/818d4dda7de778726123bc6bd49488959d4186e7/src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/AbstractProxy.php#L50).

That's the only solution I have in mind right now.

### CODE REVIEW

File: src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php [hunk 1]
```diff
@@ -28,6 +34,15 @@ public function __construct(\SessionHandlerInterface $handler)
...
         $this->handler = $handler;
+        $this->wrapper = $handler instanceof \SessionHandler;
+    }
+
+    /**
+     * Returns true if this handler wraps an internal PHP session save handler using \SessionHandler.
+     */
+    public function isWrapper(): bool
+    {
+        return $this->wrapper;
```
Comment (derrabus) [inline src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php]:
```suggestion
        return $this->handler instanceof \SessionHandler;
```

We don't need that additional property, do we?

File: src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php [hunk 2]
```diff
@@ -28,6 +34,15 @@ public function __construct(\SessionHandlerInterface $handler)
         }
 
         $this->handler = $handler;
+        $this->wrapper = $handler instanceof \SessionHandler;
+    }
+
+    /**
+     * Returns true if this handler wraps an internal PHP session save handler using \SessionHandler.
+     */
+    public function isWrapper(): bool
```
Comment (derrabus) [inline src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php:38]: We usually try to avoid adding new public methods in bugfix releases, but I see why this might be necessary here. But can we please make this method `final` and flag it as `@internal`?

**Review by derrabus — COMMENTED** [review]
Thank you for your PR. Would it be possible to add a test that reproduces the bug you're attempting to fix? I'd like to make sure we don't reintroduce it in the future.

File: src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php (hunk 2 above)
Comment (ghost) [reply src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php:38]: Done here https://github.com/symfony/symfony/pull/47130/commits/78b875473812afbc062181c8f2f64338b236b432

File: src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php (hunk 1 above)
Comment (ghost) [reply src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php]: You're right, my bad. Done here https://github.com/symfony/symfony/pull/47130/commits/1367a64c8f4ef1f9ec161d18fda61836fee74095

**Comment by ghost** [comment]
> Thank you for your PR. Would it be possible to add a test that reproduces the bug you're attempting to fix? I'd like to make sure we don't reintroduce it in the future.

@derrabus Unit test done here: https://github.com/symfony/symfony/pull/47130/commits/657f020a82901078d00c604a42e6306d3adc911e

File: src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php [hunk 3]
```diff
@@ -30,6 +30,16 @@ public function __construct(\SessionHandlerInterface $handler)
         $this->handler = $handler;
     }
 
+    /**
+     * Returns true if this handler wraps an internal PHP session save handler using \SessionHandler.
+     *
+     * @internal This method is public to avoid a bug inside the `SessionHandlerProxy` class. It should not be used in user code.
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php]: Let's remove the note after `@internal`, it doesn't bring anything to me.
Let's also remove the `final` keyword, `@internal` is enough.

File: src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php [hunk 4]
```diff
@@ -22,7 +24,7 @@ public function __construct(\SessionHandlerInterface $handler)
     {
         $this->handler = $handler;
         $this->wrapper = $handler instanceof \SessionHandler;
-        $this->saveHandlerName = $this->wrapper ? \ini_get('session.save_handler') : 'user';
+        $this->saveHandlerName = $this->wrapper || ($handler instanceof StrictSessionHandler && $handler->isWrapper()) ? \ini_get('session.save_handler') : 'user';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php:27]: shouldn't the previous line be patched instead?
`$this->wrapper = $handler instanceof StrictSessionHandler ? $handler->isWrapper() : $handler instanceof \SessionHandler;`

File: src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Proxy/SessionHandlerProxyTest.php [hunk 5]
```diff
@@ -159,6 +161,25 @@ public function testUpdateTimestamp()
 
         $this->proxy->updateTimestamp('id', 'data');
     }
+
+    /**
+     * @dataProvider provideNativeSessionStorageHandler
+     *
+     * @see https://github.com/symfony/symfony/pull/47130.
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Proxy/SessionHandlerProxyTest.php]: should be removed, we don't do such backlinks in the source

File: src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Proxy/SessionHandlerProxyTest.php [hunk 6]
```diff
@@ -159,6 +161,25 @@ public function testUpdateTimestamp()
...
+     */
+    public function testNativeSessionStorageSaveHandlerName($handler)
+    {
+        $this->assertEquals('files', (new NativeSessionStorage([], $handler))->getSaveHandler()->getSaveHandlerName());
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Proxy/SessionHandlerProxyTest.php]: assertSame

**Review by nicolas-grekas — COMMENTED** [review]
LGTM, here are some final notes

File: src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php (hunk 4 above)
Comment (ghost) [reply src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php:27]: I don't think so, because with your code the `$wrapper` property of the `SessionHandlerProxy` class will be `true` even if the `$handler` is not an instance of `\SessionHandler` (when `$handler instanceof StrictSessionHandler && $handler->isWrapper()`). 

It's not intended to work like that if you look at the comment:
https://github.com/symfony/symfony/blob/09f0222e05fa14a054a814c4529e62512ef1f2b4/src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/AbstractProxy.php#L19-L24

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php:27]: Apparently isWrapper is never used, we should deprecate it IMHO. (in a follow up)

Comment (ghost) [reply src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php:27]: What would you like me to do then?

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php:27]: You can ignore my original comment on this line :)

File: src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Proxy/SessionHandlerProxyTest.php (hunk 6 above)
Comment (ghost) [reply src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Proxy/SessionHandlerProxyTest.php]: Done https://github.com/symfony/symfony/pull/47130/commits/5c1c9856e03f1e785eed9e10faba5039b84a332c

File: src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Proxy/SessionHandlerProxyTest.php (hunk 5 above)
Comment (ghost) [reply src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Proxy/SessionHandlerProxyTest.php]: Done https://github.com/symfony/symfony/pull/47130/commits/5c1c9856e03f1e785eed9e10faba5039b84a332c

File: src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php (hunk 3 above)
Comment (ghost) [reply src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php]: Done https://github.com/symfony/symfony/pull/47130/commits/5c1c9856e03f1e785eed9e10faba5039b84a332c

**Review by ghost — COMMENTED** [review]
Maybe we should use a more intuitive name for the method? Like `isInternalWrapper`, `wrapsInternalHandler`, `hasInternalHandler`. What do you think @nicolas-grekas? In my opinion, this makes the method more understandable.

```diff
    /**
     * Returns true if this handler wraps an internal PHP session save handler using \SessionHandler.
     *
     * @internal
     */
-   public function isWrapper(): bool
+   public function isInternalWrapper(): bool
    {
        return $this->handler instanceof \SessionHandler;
    }
```

```diff
    /**
     * Returns true if this handler wraps an internal PHP session save handler using \SessionHandler.
     *
     * @internal
     */
-   public function isWrapper(): bool
+   public function wrapsInternalHandler(): bool
    {
        return $this->handler instanceof \SessionHandler;
    }
```

```diff
    /**
     * Returns true if this handler wraps an internal PHP session save handler using \SessionHandler.
     *
     * @internal
     */
-   public function isWrapper(): bool
+   public function hasInternalHandler(): bool
    {
        return $this->handler instanceof \SessionHandler;
    }
```

**Review by nicolas-grekas — APPROVED** [review]
I'm fine with isWrapper: this is what AbstractProxy uses already for the same thing

**Comment by nicolas-grekas** [comment]
Thank you @BrokenSourceCode.
