### PR TITLE
[DoctrineBridge] Allow `EntityValueResolver` to return a list of entities

### LINKED ISSUE #53236: [DoctrineBridge] MapEntity with multiple results
### Symfony version(s) affected

7.0.1

### Description

I use the following code but I meet an error

```php
#[Route('/product/{id}/comments')]
public function show(
    Product $product,
    #[MapEntity(expr: 'repository.findBy(["product_id" => id], null, request.query.get("limit", 10)')]
    iterable $comments
): Response {
}
```

Error is:
`Controller "App\Controller\ProductController" requires that you provide a value for the "$comments" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or there is a non-optional argument after this one.`

### How to reproduce

```php
#[Route('/product/{id}/comments')]
public function show(
    Product $product,
    #[MapEntity(expr: 'repository.findBy(["product_id" => id], null, request.query.get("limit", 10)')]
    iterable $comments
): Response {
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #53236 (sort of)
| License       | MIT

Makes the following possible:
```php
#[Route('/{author_id}', name: 'app_test')]
public function index(
    #[MapEntity(class: Post::class, expr: 'repository.findBy({"author": author_id}, {}, 10)')]
    iterable $posts
): Response {
// ...
}
```

This is actually something that used to be possible with the SensioFrameworkExtraBundle.

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/Tests/ArgumentResolver/EntityValueResolverTest.php [hunk 1]
```diff
@@ -342,6 +344,48 @@ public function testExpressionMapsToArgument()
         $this->assertSame([$object], $resolver->resolve($request, $argument));
     }
 
+    public function testExpressionMapsToIterableArgument()
+    {
+        $manager = $this->getMockBuilder(ObjectManager::class)->getMock();
+        $registry = $this->createRegistry($manager);
+        $language = $this->getMockBuilder(ExpressionLanguage::class)->getMock();
```
Comment (OskarStark) [inline src/Symfony/Bridge/Doctrine/Tests/ArgumentResolver/EntityValueResolverTest.php]:
```suggestion
        $manager = $this->createMock(ObjectManager::class);
        $registry = $this->createRegistry($manager);
        $language = $this->createMock(ExpressionLanguage::class);
```

File: src/Symfony/Bridge/Doctrine/Tests/ArgumentResolver/EntityValueResolverTest.php [hunk 2]
```diff
@@ -342,6 +344,48 @@ public function testExpressionMapsToArgument()
...
+        $argument = $this->createArgument(
+            'iterable',
+            new MapEntity(
+                class: \stdClass::class,
+                expr: $expr = 'repository.findBy({"author": id}, {"createdAt": request.query.get("sort", "DESC")}, request.query.getInt("limit", 10))',
+            ),
+            'arg1',
+        );
+
+        $repository = $this->getMockBuilder(ObjectRepository::class)->getMock();
```
Comment (OskarStark) [inline src/Symfony/Bridge/Doctrine/Tests/ArgumentResolver/EntityValueResolverTest.php]:
```suggestion
        $repository = $this->createMock(ObjectRepository::class);
```

**Review by nicolas-grekas — APPROVED** [review]

**Review by welcoMattic — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @HypeMC.
