### PR TITLE
[Sendgrid-Mailer] Fixed envelope recipients on sendgridApiTransport

### LINKED ISSUE #37870: [Sendgrid-mailer] SendgridApiTransport Mailer doesn't respect envelope recipients
I'm trying to use the EnvelopeListener to override the email used for sending in dev mode. 

Unfortunately the SendgridApiTransport uses the original email and not the envelope to get the recipients, meaning it still send emails to the original recipient. 

In https://github.com/symfony/sendgrid-mailer/blob/master/Transport/SendgridApiTransport.php#L86
the getPayload function uses

```
$personalization = [
            'to' => array_map($addressStringifier, $email->getTo()),
            'subject' => $email->getSubject(),
        ];
```

instead of something like the MandrillSmtpApi which uses a getRecipients function that uses the $envelope
https://github.com/symfony/mailchimp-mailer/blob/master/Transport/MandrillApiTransport.php#L82

### PR DESCRIPTION
**Pull request by arendjantetteroo**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37870 
| License       | MIT
| Doc PR        | no

Fixes #37870

The SendgridApiTransport was not using the envelope to get the
recipients, so overriding the recipients with the EnvelopeListener was
not working.

### CODE REVIEW

File: src/Symfony/Component/Mailer/Bridge/Sendgrid/Tests/Transport/SendgridApiTransportTest.php [hunk 1]
```diff
@@ -192,4 +192,31 @@ public function testReplyTo()
...
+
+    public function testEnvelopeSenderAndRecipients()
+    {
+        $from = 'from@example.com';
+        $to = 'to@example.com';
+        $envelopeFrom = 'envelopefrom@example.com';
+        $envelopeTo = 'envelopeto@example.com';
+        $email = new Email();
+        $email->from($from)
+            ->to($to)
```
Comment (fabpot) [inline src/Symfony/Component/Mailer/Bridge/Sendgrid/Tests/Transport/SendgridApiTransportTest.php:204]: Can you also add some cc and bcc to be sure they don't end up in to?

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Mailer/Bridge/Sendgrid/Tests/Transport/SendgridApiTransportTest.php (hunk 1 above)
Comment (arendjantetteroo) [reply src/Symfony/Component/Mailer/Bridge/Sendgrid/Tests/Transport/SendgridApiTransportTest.php:204]: Added cc + bcc, + a count on the to items

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @arendjantetteroo.
