### PR TITLE
[Uid] Add `MockUuidFactory` for deterministic UUID generation in tests

### LINKED ISSUE #60978: [Uid] Add `MockUuid`/`UuidFactory` for deterministic UUID generation in tests
## Description

Similar to the Clock component's `ClockInterface` and `MockClock`, it would be beneficial to have a way to mock UUID generation for testing purposes.

## Problem

Currently, when testing code that generates UUIDs, developers face challenges:
- UUIDs are non-deterministic by design
- Tests cannot assert exact UUID values
- Snapshot testing becomes difficult
- Tests rely on regex patterns rather than exact matches

## Proposed Solution

Introduce a mockable UUID generation mechanism, similar to the Clock component:

```php
interface UuidFactoryInterface
{
    public function v4(): UuidV4;
    public function v7(): UuidV7;
    // ... other versions
}

class MockUuidFactory implements UuidFactoryInterface
{
    private array $sequence = [];
    private int $index = 0;
    
    public function setSequence(array $uuids): void
    {
        $this->sequence = $uuids;
        $this->index = 0;
    }
    
    public function v4(): UuidV4
    {
        if (!isset($this->sequence[$this->index])) {
            throw new \RuntimeException('No more UUIDs in sequence');
        }
        
        return UuidV4::fromString($this->sequence[$this->index++]);
    }
}
```

## Use Case Example

```php
class UserService
{
    public function __construct(
        private UuidFactoryInterface $uuidFactory = new UuidFactory()
    ) {}
    
    public function createUser(string $email): User
    {
        return new User(
            id: $this->uuidFactory->v4(),
            email: $email
        );
    }
}

// In tests:
$mockFactory = new MockUuidFactory();
$mockFactory->setSequence([
    '550e8400-e29b-41d4-a716-446655440000',
    '6ba7b810-9dad-11d1-80b4-00c04fd430c8'
]);

$service = new UserService($mockFactory);
$user = $service->createUser('test@example.com');

$this->assertSame('550e8400-e29b-41d4-a716-446655440000', (string) $user->getId());
```

## Benefits

1. **Deterministic tests** - Know exactly what UUIDs will be generated
2. **Better assertions** - Test exact values instead of patterns
3. **Consistency with Clock component** - Follows established patterns
4. **Easier debugging** - Predictable UUIDs in test scenarios

## Questions for Discussion

1. Should this be part of the Uid component or a separate testing utility?
2. Should we support all UUID versions or just commonly used ones (v4, v7)?
3. Should we provide a global static setter like `Uuid::setFactory()` similar to how some libraries handle it?
4. How should we handle edge cases (running out of mocked UUIDs)?

## Scope and Limitations

**Important:** This RFC specifically addresses UUID generation that happens through a public API (dependency injection, factories, etc.). It does **not** intend to cover:
- UUIDs created directly via static methods (e.g., `Uuid::v4()`) without using the factory
- Private/internal UUID instantiation within third-party libraries
- Legacy code that directly instantiates UUID objects

For such cases, developers would need to refactor their code to use the factory pattern to benefit from this mocking capability.

## Additional Context

This pattern is already established in Symfony with:
- `ClockInterface` and `MockClock` in the Clock component
- Similar patterns exist in other frameworks/libraries

Looking forward to community feedback on this proposal.

### PR DESCRIPTION
**Pull request by momito69**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #60978
| License       | MIT

Similar to the Clock component's ClockInterface and MockClock, I've made a MockUuidFactory and implemented an UuidFactoryInterface to have a way to mock UUID generation for testing purposes.

cc @OskarStark , @alexandre-daubois

### CODE REVIEW

**Review by nicolas-grekas — CHANGES_REQUESTED** [review]
I think we shouldn't extend the current API of factories. Let's inherit from UuidFactory instead, and let's remove all the added methods, they're breaking the design of the factory API: v3+5 don't make sense mocking, v1/6/7 are all time-based and the abstraction can be kept, v4 is already what the `randomBased` method returns so we don't need new methods, etc.

File: src/Symfony/Component/Uid/Factory/MockUuidFactory.php [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+    }
+
+    public function v5(Uuid $namespace, string $name): UuidV5
+    {
+        return UuidV5::fromString($this->getNextUuid());
+    }
+
+    public function v6(): UuidV6
+    {
+        return UuidV6::fromString($this->getNextUuid());
```
Comment (stof) [inline src/Symfony/Component/Uid/Factory/MockUuidFactory.php]: Wouldn't this break if the next uuid is not a v6 one ? Same for other methods

Comment (nicolas-grekas) [reply src/Symfony/Component/Uid/Factory/MockUuidFactory.php]: I think that's on purpose, you can see it as a filter to validate that the next UUID is of the expected/planned type.

Comment (stof) [reply src/Symfony/Component/Uid/Factory/MockUuidFactory.php]: but it fails with a non-understandable DX as far as I can tell

File: src/Symfony/Component/Uid/CHANGELOG.md [hunk 2]
```diff
@@ -57,3 +58,4 @@ CHANGELOG
  * added support for UUID
  * added support for ULID
  * added the component
+
```
Comment (OskarStark) [inline src/Symfony/Component/Uid/CHANGELOG.md]:
```suggestion
```

File: src/Symfony/Component/Uid/Factory/MockUuidFactory.php [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+
+        return $this->defaultClass::fromString($uuid);
+    }
+
+    private function validateDefaultClass(string $class): void
+    {
+        if (!is_subclass_of($class, Uuid::class)) {
+            throw new \InvalidArgumentException(\sprintf('The class "%s" must be a subclass of "%s".', $class, Uuid::class));
+        }
+    }
```
Comment (alexandre-daubois) [inline src/Symfony/Component/Uid/Factory/MockUuidFactory.php]: I would inline this function

File: src/Symfony/Component/Uid/CHANGELOG.md [hunk 4]
```diff
@@ -5,6 +5,7 @@ CHANGELOG
 ---
 
  * Add microsecond precision to UUIDv7
+ * Add `MockUuidFactory` and `UuidFactoryInterface` to allow deterministic and mockable UUID generation for testing purposes
```
Comment (alexandre-daubois) [inline src/Symfony/Component/Uid/CHANGELOG.md]: `UuidFactoryInterface` doesn't exist anymore, its mention should be removed

File: src/Symfony/Component/Uid/Factory/MockUuidFactory.php (hunk 3 above)
Comment (momito69) [reply src/Symfony/Component/Uid/Factory/MockUuidFactory.php]: Alright !

File: src/Symfony/Component/Uid/CHANGELOG.md (hunk 4 above)
Comment (momito69) [reply src/Symfony/Component/Uid/CHANGELOG.md]: My bad !

**Review by nicolas-grekas — COMMENTED** [review]
Instead of a review, I thought it would be quicker to write the factory, so here is how I see this could be. If you could give it a try and add tests that'd be awesome!

<details>

```php
<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\Component\Uid\Factory;

use Symfony\Component\Uid\TimeBasedUidInterface;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Uid\UuidV3;
use Symfony\Component\Uid\UuidV4;
use Symfony\Component\Uid\UuidV5;
use Symfony\Component\Uid\UuidV7;

class MockUuidFactory extends UuidFactory
{
    private \Iterator $sequence;

    /**
     * @param iterable<string|Uuid> $uuids
     */
    public function __construct(
        iterable $uuids,
        private Uuid|string|null $timeBasedNode = null,
        private Uuid|string|null $nameBasedNamespace = null,
    ) {
        $this->sequence = match (true) {
            \is_array($uuids) => new \ArrayIterator($uuids),
            $uuids instanceof \Iterator => $uuids,
            $uuids instanceof \Traversable => new \IteratorIterator($uuids),
        };
    }

    public function create(): Uuid
    {
        if (!$this->sequence->valid()) {
            throw new \RuntimeException('No more UUIDs in sequence.');
        }
        $uuid = $this->sequence->current();
        $this->sequence->next();

        return $uuid instanceof Uuid ? $uuid : Uuid::fromString($uuid);
    }

    public function randomBased(): RandomBasedUuidFactory
    {
        if (!($uuid = $this->create()) instanceof UuidV4) {
            throw new \RuntimeException(\sprintf('Next UUID in sequence is not a UuidV4: "%s".', get_debug_type($uuid)));
        }

        return new class($uuid) extends RandomBasedUuidFactory {
            public function __construct(
                private UuidV4 $uuid,
            ) {
            }

            public function create(): UuidV4
            {
                return $this->uuid;
            }
        };
    }

    public function timeBased(Uuid|string|null $node = null): TimeBasedUuidFactory
    {
        if (!($uuid = $this->create()) instanceof TimeBasedUidInterface) {
            throw new \RuntimeException(\sprintf('Next UUID in sequence is not a TimeBasedUidInterface: "%s".', get_debug_type($uuid)));
        }

        if (\is_string($node ??= $this->timeBasedNode)) {
            $node = Uuid::fromString($node);
        }

        return new class($uuid, $node) extends TimeBasedUuidFactory {
            public function __construct(
                private TimeBasedUidInterface $uuid,
                private ?Uuid $node = null,
            ) {
                if ($uuid instanceof UuidV7) {
                    $this->node = null;
                }
            }

            public function create(?\DateTimeInterface $time = null): Uuid&TimeBasedUidInterface
            {
                if (null !== $time && $this->uuid->getDateTime() != $time) {
                    throw new \RuntimeException(\sprintf('Next UUID in sequence does not match the expected time: "%s" != "%s".', $this->uuid->getDateTime()->format('@U.uT'), $time->format('@U.uT')));
                }

                if (null !== $this->node && $this->uuid->getNode() !== substr($this->node->toRfc4122(), -12)) {
                    throw new \RuntimeException(\sprintf('Next UUID in sequence does not match the expected node: "%s" != "%s".', $this->uuid->getNode(), substr($this->node->toRfc4122(), -12)));
                }

                return $this->uuid;
            }
        };
    }

    public function nameBased(Uuid|string|null $namespace = null): NameBasedUuidFactory
    {
        if (!($uuid = $this->create()) instanceof UuidV5 && !$uuid instanceof UuidV3) {
            throw new \RuntimeException(\sprintf('Next UUID in sequence is not a UuidV5 or UuidV3: "%s".', get_debug_type($uuid)));
        }

        $factory = parent::nameBased($namespace);

        return new class ($uuid, $factory) extends NameBasedUuidFactory {
            public function __construct(
                private UuidV5|UuidV3 $uuid,
                private NameBasedUuidFactory $factory,
            ) {
            }

            public function create(string $name): UuidV5|UuidV3
            {
                if ($this->uuid->toRfc4122() !== $this->factory->create($name)->toRfc4122()) {
                    throw new \RuntimeException(\sprintf('Next UUID in sequence does not match the expected named UUID: "%s" != "%s".', $this->uuid->toRfc4122(), $this->factory->create($name)->toRfc4122()));
                }

                return $this->uuid;
            }
        };
    }
}
```

</details>

**Comment by nicolas-grekas** [comment]
Ah, I can already tell you I made a mistake: the sequence should be consumed in child factories, not in the main one !

**Comment by momito69** [comment]
@nicolas-grekas looks good I'll try you suggestion. And about  the sequence  I'll take care of it.

**Comment by nicolas-grekas** [comment]
I pushed commit https://github.com/symfony/symfony/pull/61807/commits/ea77e069ea9a821a243ef9fed34125aeb8491d53 on your fork, please fetch before working on this again.
A quick rebase is needed (I can take care of it before merging also)
Some more tests would be nice, ensuring exceptions are tested.

File: src/Symfony/Component/Uid/Factory/MockUuidFactory.php [hunk 5]
```diff
@@ -0,0 +1,143 @@
...
+            public function __construct(
+                private \Closure $create,
+                private ?Uuid $node = null,
+            ) {
+            }
+
+            public function create(?\DateTimeInterface $time = null): Uuid&TimeBasedUidInterface
+            {
+                if (!($uuid = ($this->create)()) instanceof TimeBasedUidInterface) {
+                    throw new InvalidArgumentException(\sprintf('Next UUID in sequence is not a TimeBasedUidInterface: "%s" given.', get_debug_type($uuid)));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Uid/Factory/MockUuidFactory.php]: to help static analyzers:
```suggestion
                if (!($uuid = ($this->create)()) instanceof TimeBasedUidInterface || !$uuid instanceof Uuid) {
                    throw new InvalidArgumentException(\sprintf('Next UUID in sequence is not a TimeBasedUidInterface nor a Uuid: "%s" given.', get_debug_type($uuid)));
```

File: src/Symfony/Component/Uid/Factory/MockUuidFactory.php [hunk 6]
```diff
@@ -0,0 +1,143 @@
...
+                }
+
+                if (null !== $time && $uuid->getDateTime() !== $time) {
+                    throw new InvalidArgumentException(\sprintf('Next UUID in sequence does not match the expected time: "%s" != "%s".', $uuid->getDateTime()->format('@U.uT'), $time->format('@U.uT')));
+                }
+
+                if (!$uuid instanceof UuidV1 && !$uuid instanceof UuidV6 && !$uuid instanceof UuidV7) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Uid/Factory/MockUuidFactory.php]: then the check below can be simplified:
```suggestion
                if (!$uuid instanceof UuidV1 && !$uuid instanceof UuidV6) {
```

File: src/Symfony/Component/Uid/Factory/MockUuidFactory.php [hunk 7]
```diff
@@ -0,0 +1,143 @@
...
+
+            public function create(string $name): UuidV5|UuidV3
+            {
+                if (!($uuid = ($this->create)()) instanceof UuidV5 && !$uuid instanceof UuidV3) {
+                    throw new InvalidArgumentException(\sprintf('Next UUID in sequence is not a UuidV5 or UuidV3: "%s".', get_debug_type($uuid)));
+                }
+
+                $factory = new UuidFactory(nameBasedClass: $uuid::class, nameBasedNamespace: $this->namespace);
+
+                if ($uuid->toRfc4122() !== $factory->nameBased()->create($name)->toRfc4122()) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Uid/Factory/MockUuidFactory.php]:
```suggestion
                if ($uuid->toRfc4122() !== $expectedUuid = $factory->nameBased()->create($name)->toRfc4122()) {
```

File: src/Symfony/Component/Uid/Factory/MockUuidFactory.php [hunk 8]
```diff
@@ -0,0 +1,143 @@
...
+                    throw new InvalidArgumentException(\sprintf('Next UUID in sequence does not match the expected named UUID: "%s" != "%s".', $uuid->toRfc4122(), $factory->nameBased($this->namespace)->create($name)->toRfc4122()));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Uid/Factory/MockUuidFactory.php]:
```suggestion
                    throw new InvalidArgumentException(\sprintf('Next UUID in sequence does not match the expected named UUID: "%s" != "%s".', $uuid->toRfc4122(), $expectedUuid));
```

**Review by nicolas-grekas — COMMENTED** [review]
thanks for the new tests!
here are some more tweaks for the code and then we should be good to go!

**Review by nicolas-grekas — APPROVED** [review]

**Review by alexandre-daubois — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]
Many thanks 🚀

**Comment by nicolas-grekas** [comment]
Thank you @momito69.

**Comment by VincentLanglet** [comment]
`new Uuid()` can be used in doctrine entity in which it's not possible to use dependency injection.

In order to enjoy fully the MockUuidFactory, should we expose something similar to `Clock::get()` ? @nicolas-grekas @OskarStark

**Comment by Hanmac** [comment]
i don't know if it would be needed, but looking at the UuidFactory classes, i would suspect them to use Interfaces instead

Like should MockUuidFactory extend from UuidFactory if none of the functions and properties are used?
Or should there be a UuidFactoryInterface instead?

Same with `RandomBasedUuidFactoryInterface` and the others?

**Comment by nicolas-grekas** [comment]
We'd rather figure out a way to have Doctrine use a factory instead.

**Comment by stof** [comment]
if you use a custom id generator in the ORM, it can use any dependency it wants. And `symfony/doctrine-bridge` already implements the `UuidGenerator` and the `UlidGenerator`.

If you want to generate the id yourselves in the constructor of your entities, you cannot use dependency injection at all (as the instantiation is not managed by the DI component). But I don't think that's a reason to introduce a global state for accessing the configured factory.

**Comment by VincentLanglet** [comment]
> If you want to generate the id yourselves in the constructor of your entities, you cannot use dependency injection at all (as the instantiation is not managed by the DI component). But I don't think that's a reason to introduce a global state for accessing the configured factory.

Indeed, I was doing in my entity
```
    public function __construct()
    {
        $this->uuid = Uuid::v7();
        $this->createdAt = Clock::get()->now();
    }
```
