### PR TITLE
[Mime] Fix boundary header

### LINKED ISSUE #35443: HTTPClient multipart/form-data request issues
**Symfony version(s) affected**: 4.4.3

**Description**  
I'm communicating with an API and ran in some problems when I tried to upload files with the HTTPClient. 

**How to reproduce**  
Unfortunately it's not a public API so i can't provide the exact examples but i'm basically doing what's described in the docs:

```php
$fields = [
    'file' => new DataPart($csv, 'test.csv', 'text/csv'),
];

$formData = new FormDataPart($fields);

$httpClient->request('POST', '/', ['body' => $formData->bodyToString()]);
```

**Possible Solution**  
The problem is because in the data part the content-type has an additional token `name=file` (see below). At least if i remove it from the request everything works fine. I was looking in the rfc7233 and rfc7578 spec but couldn't really find anything about this, but not sure if i'm just missing it or looking in the wrong spec.

```
--_=_symfony_1579722514_dac69a39ca05c454f2a6375249ce7614_=_
Content-Type: text/csv; name=file
Content-Transfer-Encoding: 8bit
Content-Disposition: form-data; name=file; filename=test.csv

.... data ...

--_=_symfony_1579722514_dac69a39ca05c454f2a6375249ce7614_=_--
```

The second issue I ran into was that the boundary in the request headers is enclosed in quotes, which also causes propblems. Again, couldn't really find something about that but it's not in the request when i'm just using curl in the terminal.

Doesn't work:
```
Content-Type: multipart/form-data; boundary="_=_symfony_1579723754_2b148207ef318a96c271a8e5bd56b206_=_"
```

Works:
```
Content-Type: multipart/form-data; boundary=_=_symfony_1579723754_2b148207ef318a96c271a8e5bd56b206_=_
```

Are these problems in the symfony mime client or in the API i'm working with?

### PR DESCRIPTION
**Pull request by guillbdx**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35443 (fixes the second problem described in this ticket)
| License       | MIT

The boundary value of Content-Type header was enclosed in quotes, cause of the "=" symbol.

### CODE REVIEW

**Comment by fabpot** [comment]
What does it fix?

**Comment by guillbdx** [comment]
Sorry, i had closed/recreated the PR and forgot to fill the description.
Description is updated now.

**Comment by fabpot** [comment]
As far as I know, the current chars used in the boundary are correct, so I would prefer that we fix the root cause instead.

**Comment by guillbdx** [comment]
Yes, after checking, the chars are correct, and the quotes should not cause any problem at all, that's even a recommandation:

> The grammar for parameters on the Content-type field is such that it is often necessary to enclose the boundary parameter values in quotes on the Content-type line.  This is not always necessary, but never hurts.
https://tools.ietf.org/html/rfc2046#section-5.1.1

So I assume the root cause is API side in the ticket #35443 and there's not much we can do.

File: src/Symfony/Component/Mime/Part/AbstractMultipartPart.php [hunk 1]
```diff
@@ -91,7 +91,7 @@ public function asDebugString(): string
     private function getBoundary(): string
     {
         if (null === $this->boundary) {
-            $this->boundary = '_=_symfony_'.time().'_'.bin2hex(random_bytes(16)).'_=_';
+            $this->boundary = '_symfony_'.time().'_'.bin2hex(random_bytes(16)).'_';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mime/Part/AbstractMultipartPart.php]: I'd suggest generating the boundary using:
`$this->boundary = strtr(base64_encode(random_bytes(16)), '+/', '-_'));`
This would prevent leaking "symfony" (someone mentioned the idea elsewhere)
and that would prevent using special characters that must be quoted (as using them reduces interoperability with some servers apparently).

Comment (javiereguiluz) [reply src/Symfony/Component/Mime/Part/AbstractMultipartPart.php]: For reference purposes, I looked how others generate this boundary value:

* Rust for example uses 6 random alphanumeric ASCII characters: https://docs.rs/multipart-rfc7578/0.7.0/src/multipart_rfc7578/boundary_generator.rs.html#44-49
* Apache uses the object hashcode + some timestamp (https://github.com/apache/camel/blob/abe804645029df960b7299e05546597196aea7a1/components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/EntityUtils.java#L63) e.g. `boundary="----=_Part_0_14180567.1447658227051"`

**Comment by n3o77** [comment]
I think the actual problem here is that the boundary is only put in quotes in the header but not the parts in the message (as described here: https://github.com/symfony/symfony/issues/35443#issuecomment-581433914 )

File: src/Symfony/Component/Mime/Part/AbstractMultipartPart.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Mime/Part/AbstractMultipartPart.php]: Let's use 6 instead of 16 then? 16 is 128b = good for world-wide uniqueness.
6 = 48b = good for single message uniqueness, as Rust hints us.

Comment (guillbdx) [reply src/Symfony/Component/Mime/Part/AbstractMultipartPart.php]: Updated.

File: src/Symfony/Component/Mime/Tests/Part/Multipart/FormDataPartTest.php [hunk 2]
```diff
@@ -91,4 +91,16 @@ public function testContentLineLength()
...
     }
+
+    public function testBoundaryContentTypeHeader()
+    {
+        $f = new FormDataPart([
+            'file' => new DataPart('data.csv', 'data.csv', 'text/csv'),
+        ]);
+        $headers = $f->getPreparedHeaders()->toArray();
+        $this->assertRegExp(
+            '/^Content-Type: multipart\/form-data; boundary=[a-zA-Z0-9\-_]{6,}$/',
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mime/Tests/Part/Multipart/FormDataPartTest.php]: `s/6,/8`

**Review by nicolas-grekas — APPROVED** [review]

**Comment by guillbdx** [comment]
@n3o77 Yes, quotes are only for the parameter value in the header: https://tools.ietf.org/html/rfc2046#section-5.1.1

Anyway, this PR should fix this interoperability issue.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @guillbdx.
