### PR TITLE
[DependencyInjection] Fix lazy proxy creation for interfaces aliased to final classes

### LINKED ISSUE #62291: [DependencyInjection] BC break in 7.3.4 breaks lazy proxies of some interfaces (php 8.3)
### Symfony version(s) affected

7.3.4

### Description

I have a service class with a dependency of `TokenStorageInterface` marked as lazy. This worked in the past. But after the update from v7.3.3 to v7.3.4 this breaks.

Here's my simplified class:

```php
<?php 
namespace App\Extension\Serializer\Normalizer;

use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class ProfileNormalizer
{
    public function __construct(
        #[Autowire(lazy: true)]
        private readonly TokenStorageInterface $tokenStorage,
    ) {}
}
```

The responsible commit is https://github.com/symfony/symfony/commit/002d73572ea7672cbb3e76c553bb33dd6e87d89d with ththe change in `src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php`

This results in the `LazyServiceDumper` trying to create a lazy proxy for `Symfony\Component\Security\Core\Authentication\Token\Storage\UsageTrackingTokenStorage`. This fails because is is final.

Previously the container definition was created for the interface and not the service which is aliased by the interface. So this is a bc issue.

### How to reproduce

Checkout this reproduce project: https://github.com/stollr/symfony-lazy-proxy-bug-reproducer
and execute `php8.3 /usr/local/bin/composer install`.

This issue is **not** reproducable with PHP 8.4. So you need to verify it with PHP 8.3.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by yoeunes**
| Q | A
|---|---
| Branch? | 7.3
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Issues | Fixes #62291
| License | MIT

This PR fixes a bug where autowiring a lazy dependency for an interface (e.g., `#[Autowire(lazy: true)] TestInterface`) would fail if that interface was aliased to a `final` class.

The `AutowirePass` was attempting to resolve the alias to the concrete `final` class, which causes a fatal error on PHP < 8.4 as `final` classes cannot be proxied.

This fix updates the logic to:
1.  Always resolve aliases to concrete classes when possible (for non-final classes).
2.  **Only** on PHP < 8.4, if the resolved class is `final`, fall back to proxying the original type-hint (the interface) to avoid the fatal error.

Tests have been updated to cover these scenarios and now pass on all PHP versions without restrictions.

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php [hunk 1]
```diff
@@ -1411,4 +1411,51 @@ public function testAutowireAttributeWithEnvVar()
         $this->assertSame('%env(bool:ENABLED)%', $container->resolveEnvPlaceholders($definition->getArguments()[0]));
         $this->assertSame('%env(default::OPTIONAL)%', $container->resolveEnvPlaceholders($definition->getArguments()[1]));
     }
+
+    /**
+     * @requires PHP < 8.4
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php]: Why would this require PHP < 8.4 ? We want this behavior to work on all supported PHP versions.

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php [hunk 2]
```diff
@@ -1411,4 +1411,51 @@ public function testAutowireAttributeWithEnvVar()
...
+        $service = $container->get(LazyProxyInterfaceConsumer::class);
+        $this->assertInstanceOf(LazyProxyInterfaceConsumer::class, $service);
+
+        // Trigger lazy load
+        $dep = $service->getDep()->getSelf();
+        $this->assertInstanceOf(FinalLazyProxyImplementation::class, $dep);
+    }
+
+    /**
+     * @requires PHP >= 8.4
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php]: Why isn't this supported on older PHP versions ?

**Comment by yoeunes** [comment]
Hi @stof, thanks for the review! 

I've updated the PR to always resolve aliases for lazy proxies when possible, but fallback to the original type (e.g., interface) for final classes on PHP < 8.4 to avoid proxy errors. 

Tests now pass on PHP 8.2 and 8.4 without restrictions. (cc @nicolas-grekas)

**Comment by yoeunes** [comment]
I've just pushed an update to refactor the logic to simplify the `processValue` method by extracting the proxy resolution into `resolveProxyType`. It should be cleaner and ready for review now.

**Comment by nicolas-grekas** [comment]
Thank you @yoeunes.
