### PR TITLE
[HttpFoundation] fix redis multi host dsn not recognized

### LINKED ISSUE #34477: Redis Session Handler - Multiple Host DSN
Hello everyone!

https://github.com/symfony/symfony/pull/34177 says we can now use DSNs for configuring the session handler. For me, it works fine when using a single Redis server. But what if i try to use multiple servers ? I copied a example dsn from the cache component which looks like this :

` 'redis:?host[localhost]&host[localhost:6379]&host[/var/run/redis.sock:]&auth=my-password&redis_cluster=1'`

or in the yaml

`  handler_id:  'redis:?host[localhost]&host[localhost:6379]&host[/var/run/redis.sock:]&auth=my-password&redis_cluster=1'`

This causes an error because "redis:?" is not proccessed as a redis dsn. 

Is my configuration wrong or is this a bug in the implementation ?

Thanks in advance !

### PR DESCRIPTION
**Pull request by BeyerJC**
| Q             | A
| ------------- | ---
| Branch?       |  4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no
| Tickets       | Fix #34477
| License       | MIT

#34177 added support configurating session handlers with DSNs. It was no possible to pass a redis-DSN like
`redis:?host[localhost]&host[localhost:6379]&host[/var/run/redis.sock:]&auth=my-password&redis_cluster=1'`

since the check was 
`case 0 === strpos($connection, 'redis://'):`

### CODE REVIEW

File: src/Symfony/Component/HttpFoundation/Session/Storage/Handler/SessionHandlerFactory.php [hunk 1]
```diff
@@ -50,7 +50,7 @@ public static function createHandler($connection): AbstractSessionHandler
             case 0 === strpos($connection, 'file://'):
                 return new StrictSessionHandler(new NativeFileSessionHandler(substr($connection, 7)));
 
-            case 0 === strpos($connection, 'redis://'):
+            case 0 === strpos($connection, 'redis:'):
             case 0 === strpos($connection, 'rediss://'):
             case 0 === strpos($connection, 'memcached://'):
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Session/Storage/Handler/SessionHandlerFactory.php]: this line and the one above also should get the same change

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/Session/Storage/Handler/SessionHandlerFactory.php]: (and L59 too)

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @WhiteRabbitDE.
