### PR TITLE
[DI] dump OS-indepent paths in the compiled container

### LINKED ISSUE #38123: New Preloader related issues causing "Failed opening required '/var/www\vendor/autoload.php'"
**Symfony version(s) affected**: 5.1.6

**Description**  

Path resolution does not work with the newly integrated cache handler `cache/Xxx_KernelProdDebugContainer.preload.php`

`require dirname(__DIR__, 3).'\\vendor/autoload.php';`

The two backslashes are resolved to this square character: `.\endor/autoload.php` (see picture) since \v is an escape secquence for vertical jumps, as far as I remember.

The screenshot below show the debug output. 

**How to reproduce** 

- `$ composer dump-env prod`
- Open web page
- 💣 

**Possible Solution** 
Also, `dirname(__DIR__,3)` doesnt resolve correctly (might be a configuration issue from my side/app).
The only temp solution is to change to this weird non-scalable path settings:
```
require __DIR__.'/../../../vendor/autoload.php'; <-- changed
require __DIR__.'/ContainerU2aLZw8/Vince_KernelProdDebugContainer.php';
```
**Additional context**  
image

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38123
| License       | MIT
| Doc PR        | -

This allows compiling on Windows and running on Linux (Docker).

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

File: src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php [hunk 1]
```diff
@@ -233,7 +233,7 @@ public function testDumpAsFiles()
         $dumper = new PhpDumper($container);
         $dump = print_r($dumper->dump(['as_files' => true, 'file' => __DIR__, 'hot_path_tag' => 'hot']), true);
         if ('\\' === \DIRECTORY_SEPARATOR) {
-            $dump = str_replace('\\\\Fixtures\\\\includes\\\\foo.php', '/Fixtures/includes/foo.php', $dump);
+            $dump = str_replace("'.\\DIRECTORY_SEPARATOR.'", '/', $dump);
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php:236]: why this replacement here rather than updating the fixture to contain the OS-independent output (which would allow to see that it is actually generated) ?

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php:236]: Well, the output is not OS-independent: the paths are.
On Windows, `\` are turned into `DIRECTORY_SEPARATOR`
On Linux, `/` are kept as is (and they work on Windows as you know)
