### PR TITLE
[HttpKernel] #[MapUploadedFile] throws http exception on empty files array if argument not nullable nor has default value

### LINKED ISSUE #61376: [HttpKernel] #[MapUploadedFile] does not throw HttpException when no file is provided in request
### Symfony version(s) affected

7.2 and 7.3 (possibly also 7.1)

### Description

According to the Symfony documentation, the associated argument resolver of `#[MapUploadedFile]` should throw an `HttpException` when no file is submitted and the argument is neither nullable nor has a default value. Currently, however, an empty array is returned which causes a PHP error when the action argument is of type `UploadedFile`.

### How to reproduce

Create a controller action which accepts an uploaded file:

```
#[Route('/upload', name: 'file_upload', methods: ['POST'])]
public function upload(
    #[MapUploadedFile] UploadedFile $file
): JsonResponse {
    return new JsonResponse(['status' => 'ok']);
}
```

then upload a file with a different name:

`curl -i -F 'different_name=@/path/to/file' http://localhost/upload`

Symfony then produces the error `App\Controller\TestController::upload(): Argument #1 ($file) must be of type Symfony\Component\HttpFoundation\File\UploadedFile, array given, called in /app/vendor/symfony/http-kernel/HttpKernel.php on line 183` and handles it accordingly.

### Possible Solution

Instead of an empty array, `RequestPayloadValueResolver::mapUploadedFile` should return `null` when no file is submitted and the argument is neither nullable nor has a default value, and subsequently an `HttpException` gets thrown in `RequestPayloadValueResolver::onKernelControllerArguments`.

```
diff --git a/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php b/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php
index 0ca965db4b..11a16b4de5 100644
--- a/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php
+++ b/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php
@@ -232,7 +232,7 @@ class RequestPayloadValueResolver implements ValueResolverInterface, EventSubscr
 
     private function mapUploadedFile(Request $request, ArgumentMetadata $argument, MapUploadedFile $attribute): UploadedFile|array|null
     {
-        if (!($files = $request->files->get($attribute->name ?? $argument->getName(), [])) && ($argument->isNullable() || $argument->hasDefaultValue())) {
+        if (!($files = $request->files->get($attribute->name ?? $argument->getName())) && !($argument->isNullable() || $argument->hasDefaultValue())) {
             return null;
         }
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by hwawshy**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #61376 
| License       | MIT

Fixes #61376

### CODE REVIEW

File: src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php [hunk 1]
```diff
@@ -232,7 +232,7 @@ private function mapRequestPayload(Request $request, ArgumentMetadata $argument,
 
     private function mapUploadedFile(Request $request, ArgumentMetadata $argument, MapUploadedFile $attribute): UploadedFile|array|null
     {
-        if (!($files = $request->files->get($attribute->name ?? $argument->getName(), [])) && ($argument->isNullable() || $argument->hasDefaultValue())) {
+        if (!($files = $request->files->get($attribute->name ?? $argument->getName())) && !($argument->isNullable() || $argument->hasDefaultValue())) {
             return null;
         }
```
Comment (santysisi) [inline src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php]:
```suggestion
return $request->files->get($attribute->name ?? $argument->getName());
```

**Review by santysisi — APPROVED** [review]

**Review by Jean-Beru — APPROVED** [review]

**Review by fabpot — APPROVED** [review]
I understand that this is a bug fix, but also a behavior change, so I'm not sure we should do it in 7.3.
@symfony/mergers Thoughts?

**Comment by Spomky** [comment]
Indeed. Previously it returned an empty array or `null` (if the argument was nullable). Now it always returns `null` and may cause errors for non-nullable array arguments. An argument like `#[MapUploadedFile] array $files` should return `[]` and not `null`.

File: src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php [hunk 2]
```diff
@@ -232,10 +232,6 @@ private function mapRequestPayload(Request $request, ArgumentMetadata $argument,
 
     private function mapUploadedFile(Request $request, ArgumentMetadata $argument, MapUploadedFile $attribute): UploadedFile|array|null
     {
-        if (!($files = $request->files->get($attribute->name ?? $argument->getName(), [])) && ($argument->isNullable() || $argument->hasDefaultValue())) {
-            return null;
-        }
-
-        return $files;
+        return $request->files->get($attribute->name ?? $argument->getName());
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php]: What looks strange to me in the previous code is defaulting to an array without caring about the accepted type. To reduce the behavioral diff, we should continue to default to an array when arrays are accepted - and when not, then we should fix the behavior.

This would need a new test case for the array-case.

```suggestion
        if (!($files = $request->files->get($attribute->name ?? $argument->getName())) && ($argument->isNullable() || $argument->hasDefaultValue())) {
            return null;
        }

        return $files ?? ('array' === $argument->getType() ? [] : null);
```

Comment (Spomky) [reply src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php]: I see at least 4 test cases that should be verified when no file is provided:
* `#[MapUploadedFile] array $files` => should return an empty array
* `#[MapUploadedFile] ?array $files` => should return `null`
* `#[MapUploadedFile] UploadedFile $file` => should return `null` and an exception will be thrown
* `#[MapUploadedFile] UploadedFile ?$file` => should return `null`

Comment (hwawshy) [reply src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php]: I understand returning an empty array for the sake of BC, but IMO an absence of value should be denoted by `null` and not an empty array. The user indicates the value is optional by making the argument nullable (that's also what the docs currently say), otherwise an `HttpException` should be thrown.

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php]: That's not how this works for arrays for the other value resolvers. We have to be consistent.

Comment (hwawshy) [reply src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php]: Alright, I applied your suggestion and added the missing test cases. I am not sure if the failed pipelines are related to my changes.

**Comment by nicolas-grekas** [comment]
Thank you @hwawshy.
