### PR TITLE
[HttpClient] Always set CURLOPT_CUSTOMREQUEST to the correct HTTP method in CurlHttpClient

### LINKED ISSUE #59043: [HttpClient] HEAD request turns into PUT request since 7.2.0
### Symfony version(s) affected

7.2.0

### Description

Just upgraded one project to Symfony 7.2.0 and noticed an error with a `Psr18Client` wrapping a `CurlHttpClient`

The `HEAD` request actually turns into a `PUT` request.

### How to reproduce

```php
$response = (new Psr18Client(new CurlHttpClient()))
    ->sendRequest(new Request('HEAD', 'https://www.postb.in/1732890887317-...'));
``` 

image

### Possible Solution

_No response_

### Additional Context

This seems to be caused by https://github.com/symfony/symfony/pull/58856

Now the `CurlHttpClient` is sending a body as it seems: https://github.com/symfony/symfony/blob/4ed9d032c7b61ae49d526565bbc8fdbcf76d74c3/src/Symfony/Component/HttpClient/CurlHttpClient.php#L239

cc @KurtThiemann

### PR DESCRIPTION
**Pull request by KurtThiemann**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59043
| License       | MIT

Currently, when sending a `HEAD` request and using a closure as the request body using `CurlHttpClient`, a `PUT` request instead of a HEAD request will be sent. This is because `CURLOPT_NOBODY` is set to make a `HEAD` request, but is overwritten by `CURLOPT_UPLOAD`, which is necessary to make curl call `CURLOPT_READFUNCTION`, but also sets the HTTP method to `PUT`.
The solution I am suggesting is to just always set `CURLOPT_CUSTOMREQUEST`, so the correct HTTP method will be used, no matter what other options are added.

This is mainly an issue in the PSR-18 wrapper, since PSR requests always have a request body stream, even if the body is empty. Since #58856, `Psr18Client` always passes a closure as the request body to the underlying HTTP client instead of just reading the entire request body stream into a string, as that made it impossible to upload large files. 

While it would be possible to add an exception to `Psr18Client` to only add the request body if the method used commonly has a body, I think the better solution is to ensure that  `CurlHttpClient` always actually sends the type of request that it is asked to send.

### CODE REVIEW

**Comment by xabbuh** [comment]
The fix looks good to me. But can we also add a test to prevent regressions?

**Comment by KurtThiemann** [comment]
I added a `X-Request-Vars` response header to the TestHttpServer, since I can't get that info from the response body when using a HEAD request.  This works locally, but seems to fail in GitHub actions.
Any ideas?

File: src/Symfony/Contracts/HttpClient/Test/Fixtures/web/index.php [hunk 1]
```diff
@@ -42,6 +42,7 @@
         exit;
 
     case '/head':
+        header('X-Request-Vars: '.json_encode($vars, \JSON_UNESCAPED_SLASHES | \JSON_UNESCAPED_UNICODE));
```
Comment (xabbuh) [inline src/Symfony/Contracts/HttpClient/Test/Fixtures/web/index.php:45]: This change requires that you also bump the version for `symfony/http-client-contracts` in the dependencies (see the failures of the low deps job).

Comment (KurtThiemann) [reply src/Symfony/Contracts/HttpClient/Test/Fixtures/web/index.php:45]: Does this require a new release of `symfony/http-client-contracts` first? If so, should I maybe just find a way to test this without having to change the test server?

Sorry, this is only my second contribution to symfony, so not sure how everything works here.

Comment (xabbuh) [reply src/Symfony/Contracts/HttpClient/Test/Fixtures/web/index.php:45]: No, you don't have to wait for the next release. You can simply use the version of the patch release to be published next. Our CI will take care of using the code from this PR then.

File: src/Symfony/Component/HttpClient/composer.json [hunk 2]
```diff
@@ -25,7 +25,7 @@
         "php": ">=8.2",
         "psr/log": "^1|^2|^3",
         "symfony/deprecation-contracts": "^2.5|^3",
-        "symfony/http-client-contracts": "~3.4.3|^3.5.1",
+        "symfony/http-client-contracts": "~3.4.3|^3.5.2",
```
Comment (xabbuh) [inline src/Symfony/Component/HttpClient/composer.json]:
```suggestion
        "symfony/http-client-contracts": "~3.4.4|^3.5.2",
```

Comment (KurtThiemann) [reply src/Symfony/Component/HttpClient/composer.json]: Thanks!

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @KurtThiemann.

File: src/Symfony/Component/HttpClient/CurlHttpClient.php [hunk 3]
```diff
@@ -197,13 +197,12 @@ public function request(string $method, string $url, array $options = []): Respo
             $curlopts[\CURLOPT_RESOLVE] = $resolve;
         }
 
+        $curlopts[\CURLOPT_CUSTOMREQUEST] = $method;
         if ('POST' === $method) {
             // Use CURLOPT_POST to have browser-like POST-to-GET redirects for 301, 302 and 303
```
Comment (stof) [inline src/Symfony/Component/HttpClient/CurlHttpClient.php:202]: @nicolas-grekas wouldn't the usage of `CURLOPT_CUSTOMREQUEST` defeat this comment ?

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpClient/CurlHttpClient.php:202]: I think it's fine because it's set after.

Comment (KurtThiemann) [reply src/Symfony/Component/HttpClient/CurlHttpClient.php:202]: I, too, thought that, but after testing it just now it seems like it might not be fine...

Comment (KurtThiemann) [reply src/Symfony/Component/HttpClient/CurlHttpClient.php:202]: I looked into this, and it seems like this would be an issue in plain cURL, but actually works correctly in Symfony because redirects are handled in `CurlResponse::parseHeaderLine` instead of being handled by cURL itself.
I might still make a PR to add a test for this.
