### PR TITLE
[Cache] fix dbindex Redis

### LINKED ISSUE #43359: Invalid dbindex silently ignored in Redis DSN
**Symfony version(s) affected**: 5.3.7, 5.3.8

**Description**
When the Cache component is configured with a Redis DSN with non-numeric dbindex (eg. `redis://redis/foo` rather than `redis://redis/1`), the dbindex is silently ignored.

**How to reproduce**
```php
<?php
// config/packages/cache.php

use Symfony\Config\FrameworkConfig;

return static function (FrameworkConfig $framework) {
    $cache = $framework->cache();

    $cache->app('cache.adapter.redis')
        ->defaultRedisProvider('redis://redis/foo');

    $cache->pool('my_pool.cache')->adapters(['cache.app']);
};
```
Then start using the cache. Default dbindex `0` will be used.

**Possible Solution**
Fail or at least log if the DSN contains a dbindex which is not numeric.

**Additional context**
[This line](https://github.com/symfony/symfony/blob/842ecc50f04ea0067ac300e2396a391dff687498/src/Symfony/Component/Cache/Traits/RedisTrait.php#L150) seems to be related:
```php
if (!isset($params['dbindex']) && isset($params['path']) && preg_match('#/(\d+)$#', $params['path'], $m)) {
    …
```
This condition checks if the dbindex is present (`isset($params['path'])`) and numeric (`preg_match(…)`). There's no handling for a present but invalid dbindex.

### PR DESCRIPTION
**Pull request by a1812**
| Q             | A
| ------------- | ---
| Branch?       | 4.4 
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #43359
| License       | MIT
| Doc PR        | 

Invalid dbindex silently not ignored in Redis DSN

### CODE REVIEW

File: src/Symfony/Component/Cache/Traits/RedisTrait.php [hunk 1]
```diff
@@ -147,9 +147,13 @@ public static function createConnection($dsn, array $options = [])
...
         if (isset($params['host']) || isset($params['path'])) {
-            if (!isset($params['dbindex']) && isset($params['path']) && preg_match('#/(\d+)$#', $params['path'], $m)) {
-                $params['dbindex'] = $m[1];
-                $params['path'] = substr($params['path'], 0, -\strlen($m[0]));
+            if (!isset($params['dbindex']) && isset($params['path'])) {
+                if (preg_match('#/(\d+)$#', $params['path'], $m)) {
+                    $params['dbindex'] = $m[1];
+                    $params['path'] = substr($params['path'], 0, -\strlen($m[0]));
+                } else {
+                    throw new InvalidArgumentException(sprintf('Invalid Redis DSN: "%s".', $dsn));
```
Comment (chalasr) [inline src/Symfony/Component/Cache/Traits/RedisTrait.php]: Could it give an hint about what is actually wrong with the given DSN? Just asking, really

Comment (a1812) [reply src/Symfony/Component/Cache/Traits/RedisTrait.php]: Good point. What do you think of this?
 throw new InvalidArgumentException(sprintf('Invalid Redis DSN: "%s", database index  should be number.', $dsn));

Comment (chalasr) [reply src/Symfony/Component/Cache/Traits/RedisTrait.php]: looks good, here is a proposal that is consistent with what we do elsewhere
```suggestion
                    throw new InvalidArgumentException(sprintf('Invalid Redis DSN: "%s", The "dbindex" parameter must be 
 a number.', $dsn));
```

File: src/Symfony/Component/Cache/Traits/RedisTrait.php [hunk 2]
```diff
@@ -147,9 +147,13 @@ public static function createConnection($dsn, array $options = [])
...
         if (isset($params['host']) || isset($params['path'])) {
-            if (!isset($params['dbindex']) && isset($params['path']) && preg_match('#/(\d+)$#', $params['path'], $m)) {
-                $params['dbindex'] = $m[1];
-                $params['path'] = substr($params['path'], 0, -\strlen($m[0]));
+            if (!isset($params['dbindex']) && isset($params['path'])) {
+                if (preg_match('#/(\d+)$#', $params['path'], $m)) {
+                    $params['dbindex'] = $m[1];
+                    $params['path'] = substr($params['path'], 0, -\strlen($m[0]));
+                } else {
+                    throw new InvalidArgumentException(sprintf('Invalid Redis DSN: "%s", The "dbindex" parameter must be a number.', $dsn));
```
Comment (chalasr) [inline src/Symfony/Component/Cache/Traits/RedisTrait.php]:
```suggestion
                    throw new InvalidArgumentException(sprintf('Invalid Redis DSN: "%s", the "dbindex" parameter must be a number.', $dsn));
```

my bad! sorry

**Review by chalasr — APPROVED** [review]
I didn't check the code, but the same issue may exist elsewhere in the codebase where we deal with redis connections (redis-messenger, lock). Might be worth having a look if you can

**Comment by fabpot** [comment]
Thank you @a1812.
