### PR TITLE
[ObjectMapper] Throw exception for invalid transform callable

### LINKED ISSUE #62938: [ObjectMapper] no error when invalid callable in `transform`
### Description

When we use `Map` attribute in a Dto property, a bad `transform` value is totally ignored: it's a silent error due to [ObjectMapper.php:333](https://github.com/symfony/symfony/blob/9eb3243dd3c2b40347ed54c80e64d23eda1ac7d8/src/Symfony/Component/ObjectMapper/ObjectMapper.php#L333-L335) where `getCallable()` return null if the value is not callable.

```#[Map(target:'someTargetField', transform: ClassThatDoesNotImplementTransformCallableInterface::class]```

```
            if ($fn = $this->getCallable($transform, $this->transformCallableLocator)) {
                $value = $this->call($fn, $value, $source, $target);
            }
```

It's not really a bug, but more a dx improvement : I think we should raise an exception when `transform` contains something invalid.

I can make a PR for this, but maybe there is a reason about not raising exception, so I post this issue :) 

### Example

The `bar` transformation will raise no error 
```
class FooEntity {
        public ?Bar $bar;
}

#[Map(
    target: FooEntity::class,
    transform: FooTransformer::class
)]
class FooInput {
    #[Map(target: 'bar', transform: BarTransformer::class)]
    public ?BarInput $barInput = null;
}

$fooInput = new FooInput();

$entity = $objectMapper->map($fooInput, FooEntity::class);
// no error raised, and `bar` property not initialized
```

### PR DESCRIPTION
**Pull request by calm329**
| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #62938
| License       | MIT

This PR improves DX by throwing a `MappingTransformException` when a `transform` value in the `#[Map]` attribute is not a valid callable.

Previously, invalid transforms (e.g., a class that doesn't implement `TransformCallableInterface`) were silently ignored, making debugging difficult.

**Before:**
```php
#[Map(target: 'bar', transform: ClassNotImplementingTransformCallableInterface::class)]
public ?Bar $bar;

// No error raised, property silently not transformed
```

After:
```php
#[Map(target: 'bar', transform: ClassNotImplementingTransformCallableInterface::class)]
public ?Bar $bar;

// Throws: MappingTransformException: Transform "ClassNotImplementingTransformCallableInterface" is not a valid callable.
```

This applies to both class-level and property-level transforms.

---

Contribution by Gittensor, see my contribution statistics at https://gittensor.io/miners/details?githubId=148254234

### CODE REVIEW

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php [hunk 1]
```diff
@@ -332,6 +332,8 @@ private function applyTransforms(Mapping $map, mixed $value, object $source, ?ob
         foreach ($transforms as $transform) {
             if ($fn = $this->getCallable($transform, $this->transformCallableLocator)) {
                 $value = $this->call($fn, $value, $source, $target);
+            } else {
+                throw new MappingTransformException(\sprintf('Transform "%s" is not a valid callable.', \is_string($transform) ? $transform : get_debug_type($transform)));
```
Comment (OskarStark) [inline src/Symfony/Component/ObjectMapper/ObjectMapper.php]: lets mention in the exception, that this class is invalid because it does not implement `TransformCallableInterface`? this is more actionable for the user

Comment (calm329) [reply src/Symfony/Component/ObjectMapper/ObjectMapper.php]: I've fixed it, please take another look

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php [hunk 2]
```diff
@@ -351,7 +352,7 @@ private function getCallable(string|callable $fn, ?ContainerInterface $locator =
             return $locator->get($fn);
         }
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/ObjectMapper.php:367]: in the locator case we can check that the callable does implement the expected interface
in the `is_callable` check we could check if its a class (hereby not a native php `function`) then it should implement the expected interface

**Review by soyuka — APPROVED** [review]
great improvement thanks!

**Comment by soyuka** [comment]
could you cherry-pick https://github.com/symfony/symfony/pull/62975 to credit the author?

**Comment by calm329** [comment]
> could you cherry-pick #62975 to credit the author?

Yes, I did. Please review it again

**Review by soyuka — APPROVED** [review]
awesome!

**Comment by nicolas-grekas** [comment]
Thank you @calm329.

**Comment by nicolas-grekas** [comment]
And thank you @Asenar also!

**Comment by Asenar** [comment]
Thanks you !
