### PR TITLE
[DI] Add check around class_alias for generated proxy classes

### LINKED ISSUE #37059: Cannot declare class EntityManager_*, because the name is already in use
**Symfony version(s) affected**: 5.1

**Description**  

After upgrading Symfony to 5.1 my CI started to fail with this error. It also occasionally happens on localhost. I'm not exactly sure why it happens yet and I'm not able to reproduce it reliably at this point. Is this bug known / resolved already?

Why is new Symfony generating a proxy for EntityManager anyway? In master branch EntityManager is in fact [final](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/EntityManager.php#L66) so whatever is the reason this won't work with doctrine 3.0.

### PR DESCRIPTION
**Pull request by enumag**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | nofiles -->
| Tickets       | Fix #37059
| License       | MIT
| Doc PR        |

Here is the [requested](https://github.com/symfony/symfony/issues/37059#issuecomment-638633262) fix.

I'd like to note that I consider this kind of a workaround. I don't know why the issue only started to appear with Symfony 5.1 and not before. There might be some other problem hidden somewhere else.

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php [hunk 1]
```diff
@@ -590,7 +590,7 @@ private function addServiceInclude(string $cId, Definition $definition): string
                 }
             }
 
-            foreach ($this->serviceCalls as $id => list($callCount, $behavior)) {
+            foreach ($this->serviceCalls as $id => [$callCount, $behavior]) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:593]: please revert the CS changes, they might create merge conflicts and are unrelated

**Review by nicolas-grekas — COMMENTED** [review]
Thanks, this looks good to me.
Can you please fix tests? There is a fixture that needs an update.

File: src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php (hunk 1 above)
Comment (enumag) [reply src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:593]: huh? how did that happen... I didn't change it on purpose 🤔

**Comment by enumag** [comment]
@nicolas-grekas Fixed. Travis is still failing but it doesn't seem related.

**Comment by jeremyFreeAgent** [comment]
Thanks @enumag ♥️

**Comment by nicolas-grekas** [comment]
Thank you @enumag.

**Comment by lugosium** [comment]
Thank you @enumag

**Comment by CarpentierMartin** [comment]
Thank you @enumag

**Comment by PedroTroller** [comment]
Perfect, thank you @enumag !
