### PR TITLE
[TwigBridge] Render email once

### LINKED ISSUE #39718: TemplatedEmail are rendered two times
**Symfony version(s) affected**: 4.4.18

**Description**  

TemplatedEmail are rendered two times: both the `Mailer` and the `AbstractTransport` class dispatch a MessageEvent.
The renderer (generally the `BodyRenderer` from TwigBridge) do not check if the email is already rendered and override the email contents (re-rendering the twig template).

**How to reproduce**  
Send an email and check the event dispatcher logs, you can use a twig extension with a filter called inside the twig template to easily catch it.
image

**Possible Solution**  
The render should check if the templated email is already rendered? Or maybe dispatch the email only one time?

**Additional context**

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39718
| License       | MIT
| Doc PR        | -

When `\Symfony\Component\Mailer\Mailer` send an email via the Bus (async) it dispatches an `MessageEvent`, then the consumer call the `\Symfony\Component\Mailer\Transport\AbstractTransport::send` method which also dispatches an `MessageEvent`.

This event is listened by `\Symfony\Bridge\Twig\Mime\BodyRenderer::render` which rendered twice an email.

I'm not sure why the event is send twice, and if we could safely remove one of them (or maybe deprecating the `MessageEvent`, in favor of `SendMessageEvent` + `AsyncMessageEvent`)

This PR store a flag in the Message to avoid rendering it twice.

### CODE REVIEW

**Comment by Nyholm** [comment]
@carsonbot do you know who could review this?

**Comment by Nyholm** [comment]
@carsonbot please find me a reviewer

File: src/Symfony/Bridge/Twig/Mime/BodyRenderer.php [hunk 1]
```diff
@@ -46,6 +46,14 @@ public function render(Message $message): void
         }
 
         $messageContext = $message->getContext();
+
+        $previousRenderingKey = $messageContext[__CLASS__] ?? null;
+        unset($messageContext[__CLASS__]);
+        $currentRenderingKey = md5(serialize([$messageContext, $message->getTextTemplate(), $message->getHtmlTemplate()]));
```
Comment (Nyholm) [inline src/Symfony/Bridge/Twig/Mime/BodyRenderer.php:52]: I was sure `sha1` was faster... I guess I was wrong

https://3v4l.org/emQVY

**Review by Nyholm — APPROVED** [review]
Thank you

**Comment by ajgarlag** [comment]
I think that this PR is not a feature, but a bug fix and that it should be merged into the 4.4 branch.

My problem is that when my app sends a templated email to the async transport, it is rerenderd in an HTTP context and stored with the URLs pointing to the correct hostname, but when the message is consumed from the console `message:consume` command it is rendered again in a CLI context, and the URL finally points to `localhost`.

I know that it can be fixed by setting the `router.request_context.host` parameter, but it is not so easy in a multitenant environment, and it's annoying to see that the email body in the profiler differs from the email body really sent to my address.

**Comment by jderusse** [comment]
> I know that it can be fixed by setting the `router.request_context.host` parameter, but it is not so easy in a multitenant environment, and it's annoying to see that the email body in the profiler differs from the email body really sent to my address.

This issue is addressed by another of my PR 😛 https://github.com/symfony/symfony/pull/39688

**Comment by ajgarlag** [comment]
> This issue is addressed by another of my PR stuck_out_tongue #39688

That is a great new feature.

But IMO this PR is a bug fix and shoud be merged into v4.4 to fix #39718.

**Comment by jderusse** [comment]
rebased on 4.4

**Review by javiereguiluz — APPROVED** [review]

**Comment by ajgarlag** [comment]
I though this PR would be merged before releasing version [4.4.20](https://github.com/symfony/symfony/releases/tag/v4.4.20). Can I help to get it merged soon?

Thanks

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you Jérémy.

**Comment by PhilETaylor** [comment]
This has caused a b/c break :-( details incoming...

**Comment by PhilETaylor** [comment]
Serialization of 'Closure' is not allowed  https://github.com/symfony/symfony/issues/40445
