### PR TITLE
[Form] Fix ChoiceType to effectively set and use translator

### LINKED ISSUE #41497: ChoiceType doesn't translate it's error messages
**Symfony version(s) affected**: 5.2.9

**Description**

**ChoiceType constructor early return prevents $translator from being set and used**

The constructor of ChoiceType (`Symfony\Component\Form\Extension\Core\Type\ChoiceType`) uses a conditional check
```
        if ($this->choiceListFactory instanceof CachingFactoryDecorator) {
            return;
        }
```
which causes an early return from the costructor if $choiceListFactory is an instance of CachingFactoryDecorator - which is the default case in symfony (also a default value), so this condition is met in a lot of cases.

Later on the constructor would set the $translator property passed in the constructor argument, but it won't do that, as it  returned early.

```
    public function __construct(ChoiceListFactoryInterface $choiceListFactory = null, $translator = null)
    {
        $this->choiceListFactory = $choiceListFactory ?? new CachingFactoryDecorator(
            new PropertyAccessDecorator(
                new DefaultChoiceListFactory()
            )
        );

        // BC, to be removed in 6.0
        if ($this->choiceListFactory instanceof CachingFactoryDecorator) {
            return; // <----------------------------- leaving too early
        }

       // [...] some other code here, not relevant

        $this->translator = $translator; // <------------------- this translator is not set, as constructor leaved already
    }
```
Obviously the $translator is used by the ChoiceType class, e.g. to translate an error message when some unknown values are found in the submitted form element. It would translate if it was set, but instead it uses the original message:

```
if ($options['multiple']) {
            $messageTemplate = $options['invalid_message'] ?? 'The value {{ value }} is not valid.';

            $builder->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) use (&$unknownValues, $messageTemplate) {
                // Throw exception if unknown values were submitted
                if (\count($unknownValues) > 0) {
                    $form = $event->getForm();

                    $clientDataAsString = is_scalar($form->getViewData()) ? (string) $form->getViewData() : (\is_array($form->getViewData()) ? implode('", "', array_keys($unknownValues)) : \gettype($form->getViewData()));

                    if (null !== $this->translator) {
                        $message = $this->translator->trans($messageTemplate, ['{{ value }}' => $clientDataAsString], 'validators');
                    } else { // <-------------------------- no translator has been set, so untranslated error message is used
                        $message = strtr($messageTemplate, ['{{ value }}' => $clientDataAsString]);
                    }

                    $form->addError(new FormError($message, $messageTemplate, ['{{ value }}' => $clientDataAsString], null, new TransformationFailedException(sprintf('The choices "%s" do not exist in the choice list.', $clientDataAsString))));
                }
            });

            // <select> tag with "multiple" option or list of checkbox inputs
            $builder->addViewTransformer(new ChoicesToValuesTransformer($choiceList));
        }
```
**How to reproduce**
The easiest way to understand the issue it probably to analyze the constructor and the code above. This seems to be an obvious mistake. Other way to reproduce would be to submit a choice form element with unknown value (e.g. use browser to change a value of the element to one that was not defined by the original form, then select it and submit it).

**Possible Solution**
Change the order of lines in the constructor so that $translator is set before the early return.
Or do not early return in this constructor at all, as it doesn't seem to make much of sense there anyway.

**Additional context**
This is maybe a rare bug, it will occur when someone is manually tampering with form values before submitting the form. Yet, if you want your application to handle it in a clean way and you use translations everywhere else, you'd like to translate this error message as well. Having a class depend on a $translator, and not set that dependency or not use that $translator because of some unrelated condition doesn't seem to be justified.

### PR DESCRIPTION
**Pull request by marek-binkowski-sim**
[Component][Form][ChoiceType] constructor line order changed to set translator before early return; 

[Component][Form][CoreExtension] a second argument $translator has been added for instantiation of [Component][Form][ChoiceType] 

| Q             | A
| ------------- | ---
| Branch?       |  5.2 
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41497
| License       | MIT
| Doc PR        | -

[Component][Form][ChoiceType] The bug probably came to life after a merge of two commits from different branches: 5.1 and 4.4. The commit in branch 5.1 contained a conditional early return related with the choiceListFactory:
```php
if ($this->choiceListFactory instanceof CachingFactoryDecorator) {
    return;
}
```
The code from the branch 4.4 was there to set the translator, but it wasn't effective when the constructor early returned in the line above. 
```php
$this->translator = $translator;
```

The fix was to switch [Component][Form][ChoiceType] constructor lines related with the translator above the early return related with choiceListFactory.

As a second parameter $translator has been added to the [Component][Form][ChoiceType] constructor, the translator needs to be injected by the CoreExtension so that ChoiceType could set and use it. This is why a second argument is added now in [Component][Form][CoreExtension] loadTypes for Type\ChoiceType:
```php
new Type\ChoiceType($this->choiceListFactory, $this->translator),
```

### CODE REVIEW

File: src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php [hunk 1]
```diff
@@ -62,6 +62,11 @@ public function __construct(ChoiceListFactoryInterface $choiceListFactory = null
             )
         );
 
+        if (null !== $translator && !$translator instanceof TranslatorInterface) {
+            throw new \TypeError(sprintf('Argument 2 passed to "%s()" must be han instance of "%s", "%s" given.', __METHOD__, TranslatorInterface::class, \is_object($translator) ? \get_class($translator) : \gettype($translator)));
```
Comment (Kocal) [inline src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php:66]:
```suggestion
            throw new \TypeError(sprintf('Argument 2 passed to "%s()" must be an instance of "%s", "%s" given.', __METHOD__, TranslatorInterface::class, \get_debug_type($translator)));
```

Since the Form component requires [symfony/polyfill-php80](https://github.com/symfony/polyfill-php80), we can change this logic to `get_debug_type` instead I guess.

File: src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php [hunk 2]
```diff
@@ -62,6 +62,11 @@ public function __construct(ChoiceListFactoryInterface $choiceListFactory = null
             )
         );
 
+        if (null !== $translator && !$translator instanceof TranslatorInterface) {
```
Comment (xabbuh) [inline src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php:65]: What about adding an argument type hint instead?

File: src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php (hunk 1 above)
Comment (marek-binkowski-sim) [reply src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php:66]: Thanks for the suggestion. The parameter type hint suggested by @xabbuh in the next comment feels to be a cleaner solution, I will go for it.

File: src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php (hunk 2 above)
Comment (marek-binkowski-sim) [reply src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php:65]: Good idea, I applied that change.

File: src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php [hunk 3]
```diff
@@ -72,11 +71,6 @@ public function __construct(ChoiceListFactoryInterface $choiceListFactory = null
         if ($ref->getNumberOfParameters() < 3) {
             trigger_deprecation('symfony/form', '5.1', 'Not defining a third parameter "callable|null $filter" in "%s::%s()" is deprecated.', $ref->class, $ref->name);
         }
-
-        if (null !== $translator && !$translator instanceof TranslatorInterface) {
```
Comment (fabpot) [inline src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php:76]: This check should be moved as well instead of removed and the type hint on the constructor reverted.

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php (hunk 2 above)
Comment (marek-binkowski-sim) [reply src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php:65]: Turned out not to be that good, Fabien requested to get back to old fashioned, backwards compatible type check

File: src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php (hunk 3 above)
Comment (marek-binkowski-sim) [reply src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php:76]: Requested change has been applied

**Review by xabbuh — APPROVED** [review]

**Comment by stof** [comment]
@fabpot why have you asked to revert the constructor typehint ? I don't see the reason to throw a TypeError ourselves instead of letting PHP doing it.

**Comment by fabpot** [comment]
@stof Because we are trying to limit the changes done in already released branches.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @marek-binkowski-sim.
