### PR TITLE
[OptionsResolver] add `ignoreUndefined()` method to allow skip not interesting options

### LINKED ISSUE #45370: Allow extra options in OptionsResolver
### Symfony version(s) affected

master

### Description

I have an array of options that has a subset that needs resolving, the rest of it is not important. 
There is no possibility to ignore other options only define them and that leads to expose all options for all components that not interested in them or prepare options for each component but this makes no sense to use OptionsResolver after options were prepared.

### How to reproduce

Example: email and phone are required, everything else just doesn't matter.

```php
$options = [
    'email' => 'email',
    'phone' => 'phone',
    //many other keys
];

$resolver = new \Symfony\Component\OptionsResolver\OptionsResolver();
$resolver->setRequired(['email', 'phone']);
$resolver->resolve($options);
```

This yields UndefinedOptionsException

### Possible Solution

Add possibility to ignore not configured options
and resolve only options that are configured 

```php
$options = [
    'email' => 'email',
    'phone' => 'phone',
    //many other keys
];

$resolver = new \Symfony\Component\OptionsResolver\OptionsResolver();
$resolver->setRequired(['email', 'phone']);
$resolver->ignoreNotDefined();

$resolver->resolve($options); //should produce
$options = [
    'email' => 'email',
    'phone' => 'phone',
];
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by kshtompel**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #45370
| License       | MIT
| Doc PR        | NOT ADDED

Allow to ignore not defined options to allow skip not interesting options when working with big set of shared configuration or just not to describe all the options provided by third party provider

### CODE REVIEW

File: src/Symfony/Component/OptionsResolver/OptionsResolver.php [hunk 1]
```diff
@@ -140,6 +140,11 @@ class OptionsResolver implements Options
      */
     private $prototypeIndex;
 
+    /**
+     * @var bool
```
Comment (nicolas-grekas) [inline src/Symfony/Component/OptionsResolver/OptionsResolver.php]: should be replaced by a native type

File: src/Symfony/Component/OptionsResolver/OptionsResolver.php [hunk 2]
```diff
@@ -862,7 +867,7 @@ public function resolve(array $options = []): array
         $clone = clone $this;
 
         // Make sure that no unknown options are passed
-        $diff = array_diff_key($options, $clone->defined);
+        $diff = true === $this->ignoreUndefined ? [] : array_diff_key($options, $clone->defined);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/OptionsResolver/OptionsResolver.php]: no need to compare to true/false anywhere

File: src/Symfony/Component/OptionsResolver/OptionsResolver.php [hunk 3]
```diff
@@ -1210,6 +1219,13 @@ public function count(): int
         return \count($this->defaults);
     }
 
+    public function ignoreUndefined(): static
```
Comment (nicolas-grekas) [inline src/Symfony/Component/OptionsResolver/OptionsResolver.php]: please add `@return $this` annotation

File: src/Symfony/Component/OptionsResolver/Tests/OptionsResolverTest.php [hunk 4]
```diff
@@ -36,6 +36,35 @@ protected function setUp(): void
         $this->resolver = new OptionsResolver();
     }
 
+    public function provideResolveWithIgnoreUndefined()
```
Comment (nicolas-grekas) [inline src/Symfony/Component/OptionsResolver/Tests/OptionsResolverTest.php]: should be made static + be put after the test case

**Review by nicolas-grekas — COMMENTED** [review]
Thanks for the PR, here are some minor comments.

**Comment by nicolas-grekas** [comment]
Please add a changelog entry indeed.

**Comment by OskarStark** [comment]
It looks like your committer email is not associated with your Github account.

File: src/Symfony/Component/OptionsResolver/OptionsResolver.php (hunk 1 above)
Comment (kshtompel) [reply src/Symfony/Component/OptionsResolver/OptionsResolver.php]: do you mean make like this?
private bool $ignoreUndefined = false;

if yes, there is no any other property with native type declaration in the class.
is it ok to do so?

**Comment by kshtompel** [comment]
Do I need recreate PR with new email configured or can leave it as is and commit changes with update email associated with the account

**Comment by kshtompel** [comment]
@nicolas-grekas 
Please advise where to put CHANGELOG update.
PR is made for version 6.3
but I see only 6.2 CHANGELOG file latest

File: src/Symfony/Component/OptionsResolver/OptionsResolver.php (hunk 1 above)
Comment (OskarStark) [reply src/Symfony/Component/OptionsResolver/OptionsResolver.php]: Yes it is ok 👍

File: src/Symfony/Component/OptionsResolver/Tests/OptionsResolverTest.php (hunk 4 above)
Comment (OskarStark) [reply src/Symfony/Component/OptionsResolver/Tests/OptionsResolverTest.php]: Please add a return type

File: src/Symfony/Component/OptionsResolver/OptionsResolver.php (hunk 3 above)
Comment (kshtompel) [reply src/Symfony/Component/OptionsResolver/OptionsResolver.php]: done

File: src/Symfony/Component/OptionsResolver/Tests/OptionsResolverTest.php (hunk 4 above)
Comment (kshtompel) [reply src/Symfony/Component/OptionsResolver/Tests/OptionsResolverTest.php]: done

File: src/Symfony/Component/OptionsResolver/OptionsResolver.php (hunk 2 above)
Comment (kshtompel) [reply src/Symfony/Component/OptionsResolver/OptionsResolver.php]: done

File: src/Symfony/Component/OptionsResolver/OptionsResolver.php (hunk 1 above)
Comment (kshtompel) [reply src/Symfony/Component/OptionsResolver/OptionsResolver.php]: done

**Comment by kshtompel** [comment]
please advise how to change changelog file for the new feature

**Comment by yceruto** [comment]
@kshtompel you can update the changelog in this file `src/Symfony/Component/OptionsResolver/CHANGELOG.md`

File: src/Symfony/Component/OptionsResolver/OptionsResolver.php [hunk 5]
```diff
@@ -1210,6 +1219,18 @@ public function count(): int
         return \count($this->defaults);
     }
 
+    /**
+     * Sets ignore undefined options.
+     *
+     * @return $this
+     */
+    public function ignoreUndefined(): static
```
Comment (yceruto) [inline src/Symfony/Component/OptionsResolver/OptionsResolver.php]: To maintain consistency in the design of this component, this method (as is) should be relocated to the fluent interface within `OptionConfigurator`. And here, it should be transformed into a traditional setter: `setIgnoreUndefined(bool $value): static`.

File: src/Symfony/Component/OptionsResolver/Tests/OptionsResolverTest.php [hunk 6]
```diff
@@ -36,6 +36,35 @@ protected function setUp(): void
...
+            'no defaults options, undefined resolves empty' => [[], ['c' => 4, 'd' => 5], []],
+            'empty options resolves defaults' => [['a' => '1', 'b' => '2'], [], ['a' => '1', 'b' => '2']],
+            'undefined options resolves defaults' => [['a' => '1', 'b' => '2'], ['c' => 3, 'd' => 4], ['a' => '1', 'b' => '2']],
+            'resolves defined' => [['a' => '1', 'b' => '2'], ['a' => '10', 'c' => '3'], ['b' => '2', 'a' => '10']],
+        ];
+    }
+
+    public function testIgnoreUndefinedReturnsThis()
+    {
+        $this->assertSame($this->resolver, $this->resolver->ignoreUndefined());
```
Comment (yceruto) [inline src/Symfony/Component/OptionsResolver/Tests/OptionsResolverTest.php]: This test doesn't hurt, but it's not really necessary. It will always be the case by definition, thanks to the return type.

**Review by yceruto — CHANGES_REQUESTED** [review]
Thanks for the PR! It's almost ready for me. I've left you some minor changes.

File: src/Symfony/Component/OptionsResolver/OptionsResolver.php (hunk 5 above)
Comment (kshtompel) [reply src/Symfony/Component/OptionsResolver/OptionsResolver.php]: I didn't get the thing about moving method to the OptionConfigurator.
This method sets the behaviour of whole OptionResolver instance not particular option inside of it.
please explain me the idea of it to be able do what you are asking

File: src/Symfony/Component/OptionsResolver/Tests/OptionsResolverTest.php (hunk 6 above)
Comment (kshtompel) [reply src/Symfony/Component/OptionsResolver/Tests/OptionsResolverTest.php]: done

**Comment by kshtompel** [comment]
Added CHANGELOG note for version 6.2

File: src/Symfony/Component/OptionsResolver/OptionsResolver.php (hunk 5 above)
Comment (GromNaN) [reply src/Symfony/Component/OptionsResolver/OptionsResolver.php]: The goal of the `OptionConfigurator` is to be able to write this code:
```php
        $resolver
            ->define('a')
                ->required()
                ->allowedTypes('string')
            ->define('b')
                ->default(10)
                ->allowedTypes('int')
            ->ignoreUndefined();
```

Currently, the call the `ignoreUndefined()` have to be first.

```php
        $resolver
            ->ignoreUndefined()
            ->define('a')
                ->required()
                ->allowedTypes('string')
            ->define('b')
                ->default(10)
                ->allowedTypes('int');
```

But @yceruto I would no name the method differently in `OptionResolver` and `OptionConfigurator`, so that the order of method calls does not matter. `ignoreUndefined` is a valid function name for a boolean setter.

Also, I've not found if it was discussed, the method could accept an argument if someone needs to reset the behavior: `function ignoreUndefined(bool $ignoreUndefined = true)`

File: src/Symfony/Component/OptionsResolver/CHANGELOG.md [hunk 7]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+6.2
```
Comment (GromNaN) [inline src/Symfony/Component/OptionsResolver/CHANGELOG.md]: This is for the next minor release.

```suggestion
6.3
```

File: src/Symfony/Component/OptionsResolver/OptionsResolver.php (hunk 5 above)
Comment (kshtompel) [reply src/Symfony/Component/OptionsResolver/OptionsResolver.php]: thanks for the advise.
i did changes

**Review by GromNaN — APPROVED** [review]

File: src/Symfony/Component/OptionsResolver/OptionConfigurator.php [hunk 8]
```diff
@@ -134,4 +134,16 @@ public function info(string $info): static
...
+    /**
+     * Sets whether ignore undefined options.
+     *
+     * @return $this
+     */
+    public function ignoreUndefined(bool $ignore = true): static
+    {
+        $this->resolver->ignoreUndefined($ignore);
+
+        return $this;
```
Comment (GromNaN) [inline src/Symfony/Component/OptionsResolver/OptionConfigurator.php:147]: It should return the resolver, no?

File: src/Symfony/Component/OptionsResolver/OptionsResolver.php (hunk 5 above)
Comment (yceruto) [reply src/Symfony/Component/OptionsResolver/OptionsResolver.php]: I'm mostly okay with the method name, and I personally prefer the `ignoreUndefined` version, but I'm more worried about having two different ways to name boolean methods in the same class. Right now, we have `setPrototype(bool $prototype)` in `OptionResolver` class, so I will go for consistency here.

Yes, this new method isn't related to a specific option, but it can help make the `OptionConfigurator` API easier to use as explained by @GromNaN.

File: src/Symfony/Component/OptionsResolver/OptionConfigurator.php (hunk 8 above)
Comment (kshtompel) [reply src/Symfony/Component/OptionsResolver/OptionConfigurator.php:147]: this is at least weird on my opinion to have optionResolver to be returned at this point.
I as a user would not expect such behaviour.
please make this decision without me and i'll update the PR

File: src/Symfony/Component/OptionsResolver/OptionsResolver.php (hunk 5 above)
Comment (kshtompel) [reply src/Symfony/Component/OptionsResolver/OptionsResolver.php]: so what here next?

**Comment by kshtompel** [comment]
any updates so far?

**Comment by kshtompel** [comment]
@nicolas-grekas 
@yceruto 
do i need change something?

File: src/Symfony/Component/OptionsResolver/OptionsResolver.php [hunk 9]
```diff
@@ -1210,6 +1219,18 @@ public function count(): int
         return \count($this->defaults);
     }
 
+    /**
+     * Sets whether ignore undefined options.
+     *
+     * @return $this
+     */
+    public function ignoreUndefined(bool $ignore = true): static
```
Comment (yceruto) [inline src/Symfony/Component/OptionsResolver/OptionsResolver.php]: As we discussed previously, we should keep the `set` prefix here for consistency with all setter methods in this class.

**Review by yceruto — CHANGES_REQUESTED** [review]

**Comment by kshtompel** [comment]
@yceruto something else here?

File: src/Symfony/Component/OptionsResolver/OptionConfigurator.php [hunk 10]
```diff
@@ -134,4 +134,16 @@ public function info(string $info): static
 
         return $this;
     }
+
+    /**
+     * Sets whether ignore undefined options.
+     *
+     * @return $this
+     */
+    public function setIgnoreUndefined(bool $ignore = true): static
```
Comment (yceruto) [inline src/Symfony/Component/OptionsResolver/OptionConfigurator.php]: Here is okay `ignoreUndefined` name, because this is the fluent configurator. My previous/last feedback was about the OptionResolver class only. Sorry if it wasn't clear enough.

**Review by yceruto — CHANGES_REQUESTED** [review]
One move left and LGTM. Thank you!

**Review by yceruto — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @kshtompel.

File: src/Symfony/Component/OptionsResolver/CHANGELOG.md [hunk 11]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+6.3
+---
+
+ * Add `OptionsResolver::ignoreUndefined()` to ignore not defined options while resolving
```
Comment (yceruto) [inline src/Symfony/Component/OptionsResolver/CHANGELOG.md:7]: It should be `setIgnoreUndefined` after the last changes, and we should add a log for the `OptionConfigurator` too

Comment (nicolas-grekas) [reply src/Symfony/Component/OptionsResolver/CHANGELOG.md:7]: up for a PR @yceruto ?

Comment (yceruto) [reply src/Symfony/Component/OptionsResolver/CHANGELOG.md:7]: yes, I was on it.

Comment (yceruto) [reply src/Symfony/Component/OptionsResolver/CHANGELOG.md:7]: https://github.com/symfony/symfony/pull/50305

**Comment by kshtompel** [comment]
@yceruto 
I didn't change method definition in the CHANGELOG.md to OptionsResolver::setIgnoreUndefined()
it is still has OptionsResolver::ignoreUndefined()


6.3
---

 * Add OptionsResolver::ignoreUndefined() to ignore not defined options while resolving


Do I need create another PR to make this changes??

**Comment by yceruto** [comment]
Don't worry, I already updated it here https://github.com/symfony/symfony/pull/50305
