### PR TITLE
Fix return types for PHP 8.1

### LINKED ISSUE #42199: [Console] PHP 8.1 deprecation notice for HelperSet::getIterator()
From https://github.com/sebastianbergmann/phpunit/runs/3111696987:

```
PHP Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator()
should either be compatible with IteratorAggregate::getIterator(): Traversable,
or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
in phar:///home/runner/work/phpunit/phpunit/tools/composer/vendor/symfony/console/Helper/HelperSet.php on line 112
```

### LINKED ISSUE #42231: [Finder] PHP 8.1 deprecation notices
From https://github.com/humbug/php-scoper/issues/530#issue-950358406:

```
Deprecation Notice: Return type of Symfony\Component\Finder\Finder::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Finder.php:675
Deprecation Notice: Return type of Symfony\Component\Finder\Finder::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Finder.php:732
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::getChildren() should either be compatible with RecursiveDirectoryIterator::getChildren(): RecursiveDirectoryIterator, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:85
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::rewind() should either be compatible with FilesystemIterator::rewind(): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:113
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::current() should either be compatible with FilesystemIterator::current(): SplFileInfo|FilesystemIterator|string, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:65
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with FilterIterator::rewind(): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/FilterIterator.php:30
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\DepthRangeFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/DepthRangeFilterIterator.php:41
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FileTypeFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/FileTypeFilterIterator.php:42
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php:55
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::hasChildren() should either be compatible with RecursiveIterator::hasChildren(): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php:71
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::getChildren() should either be compatible with RecursiveIterator::getChildren(): ?RecursiveIterator, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php:76
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php:30
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\PathFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/PathFilterIterator.php:27
```

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #42199, Fix #42231, Part of #41552
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/Tests/Validator/Constraints/UniqueEntityValidatorTest.php [hunk 1]
```diff
@@ -827,6 +827,7 @@ public function resultWithEmptyIterator(): array
 
         return [
             [$entity, new class() implements \Iterator {
+                #[\ReturnTypeWillChange]
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Tests/Validator/Constraints/UniqueEntityValidatorTest.php:833]: I think we should always add the corresponding phpdoc to make things crystal clear.

**Review by nicolas-grekas — COMMENTED** [review]
Did you use some tool to generate this? It'd be cool to document how we did so that others can do the same I their libs.

File: src/Symfony/Bridge/Doctrine/Tests/Validator/Constraints/UniqueEntityValidatorTest.php (hunk 1 above)
Comment (derrabus) [reply src/Symfony/Bridge/Doctrine/Tests/Validator/Constraints/UniqueEntityValidatorTest.php:833]: Even to an anonymous test dummy like in this case? I've merely added the attribute here because I don't have a `mixed` type on PHP 7.1.

**Comment by derrabus** [comment]
> Did you use some tool to generate this? It'd be cool to document how we did so that others can do the same I their libs.

No, this was manual work. I used PhpStorm to find all implementations of `Countable`, `IteratorAggregate` and friends. For each case I checked individually whether I can add a return type directly or need to add the attribute. I also checked for each occurrence if the `@return` annotation is equivalent or covariant to the return type in PHP 8.1.

**Comment by sebastianbergmann** [comment]
> No, this was manual work.

Would be nice if that did not have to be the case. CC @TomasVotruba

**Comment by TomasVotruba** [comment]
@sebastianbergmann Depends how much time it took to do. If its < 30 minutes, than automation would take longer.

**Comment by derrabus** [comment]
> @sebastianbergmann Depends how much time it took to do. If its < 30 minutes, than automation would take longer.

I was definitely faster than 30 min. 😎

**Comment by sebastianbergmann** [comment]
> > @sebastianbergmann Depends how much time it took to do. If its < 30 minutes, than automation would take longer.
> I was definitely faster than 30 min. 😎

Sorry for the noise.

**Comment by TomasVotruba** [comment]
@sebastianbergmann Thanks for the ping. If this would be something that every Symfony user has to change in their projects too, saved times is enourmous.

**Comment by wouterj** [comment]
Seems like we should also do this change for `__wakeUp()`:

`PHP Fatal error:  During inheritance of Exception: Uncaught RuntimeException: PHP Error: Return type of Symfony\Component\Security\Core\Exception\AuthenticationException::__wakeup() should either be compatible with Exception::__wakeup(): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/WouterJEloquentBundle/WouterJEloquentBundle/vendor/symfony/security-core/Exception/AuthenticationException.php:115 in /home/runner/work/WouterJEloquentBundle/WouterJEloquentBundle/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:66`
https://github.com/wouterj/WouterJEloquentBundle/runs/3211636106?check_suite_focus=true#step:9:8

**Comment by derrabus** [comment]
@wouterj This PR already includes that change. Code reviews welcome. 🙂

File: src/Symfony/Component/Intl/Data/Util/ArrayAccessibleResourceBundle.php [hunk 2]
```diff
@@ -47,23 +47,18 @@ public function offsetExists($offset): bool
     /**
      * @return mixed
```
Comment (wouterj) [inline src/Symfony/Component/Intl/Data/Util/ArrayAccessibleResourceBundle.php:49]:
```suggestion
     * @param mixed $offset
     * @return mixed
```

**Review by wouterj — APPROVED** [review]
Oh, missed that. Looks good!

**Review by kylekatarnls — APPROVED** [review]

**Comment by derrabus** [comment]
@symfony/mergers Merging this PR would remove some noise from our CI. Any objections against it?

**Review by Nyholm — APPROVED** [review]
Im happy with this PR. 

I dont know if this is complete or not. But if we missed some iterator we can fix them in a follow up PR.

**Review by OskarStark — APPROVED** [review]

**Comment by derrabus** [comment]
Thanks everyone. ❤️

**Comment by derrabus** [comment]
Follow-up for the 5.3 branch: #42379
