### PR TITLE
[AssetMapper] Ignore comment lines in JavaScriptImportPathCompiler

### LINKED ISSUE #53849: JS import module fails
### Symfony version(s) affected

6.4.3

### Description

When importing a module from a js file the import fails:

```javascript
import ThemeSwitcher from './js/themeSwitcher.js'
```

I get an error 404 and the file is missing from the importmap.

When I change the line to just import the file e.g. 
```javascript 
import './js/themeSwitcher.js'
```

it works, but then of course the source code doesn't work anymore.

### How to reproduce

In an entrypoint js file try to import a module from a different js file 

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by smnandre**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #53849
| License       | MIT

The following code was wrongly treated as _one_ line of comment

```js
// import
import "foo.js"
```

This PR updates the regexp to ignore comment lines (and fix #53849)

Also added a comment explaining how the regexp works for future maintenance.

### CODE REVIEW

**Review by weaverryan — APPROVED** [review]
Very complex regex, as expected :). We’re living by the tests on this by necessity. Thanks for fixing this!

**Review by fabpot — APPROVED** [review]

File: src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php [hunk 1]
```diff
@@ -27,8 +27,18 @@
...
+     * - Lines that start with comments //
+     * - Strings enclosed in single quotes
+     * - Strings enclosed in double quotes
+     * - Import statements
+     *
+     * Only the import statements are captured.
+     *
+     * @see https://regex101.com/r/1iBAIb/1
+     */
+    private const IMPORT_PATTERN = '/^(?:\/\/.*)|(?:\'(?:[^\'\\\\]|\\\\.)*\'|"(?:[^"\\\\]|\\\\.)*")|(?:import\s*(?:(?:\*\s*as\s+\w+|\s+[\w\s{},*]+)\s*from\s*)?|\bimport\()\s*[\'"`](\.\/[^\'"`]+|(\.\.\/)*[^\'"`]+)[\'"`]\s*[;\)]?/m';
```
Comment (fabpot) [inline src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php]: We can probably inline the comments directly in the regex (and add some spaces/new lines) to make the regex more easily understandable by using `/ms`.

Comment (smnandre) [reply src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php]: Is that better... or a bit too much ? 

```php
private const IMPORT_PATTERN = '/
    ^
        (?:\/\/.*)                     # Lines that start with comments
    |
        (?:
            \'(?:[^\'\\\\]|\\\\.)*\'   # Strings enclosed in single quotes
        |
            "(?:[^"\\\\]|\\\\.)*"      # Strings enclosed in double quotes
        )
    |
        (?:                            # Import statements (script captured)
            import\s*
                (?:
                    (?:\*\s*as\s+\w+|\s+[\w\s{},*]+)
                    \s*from\s*
                )?
        |
            \bimport\(
        )
        \s*[\'"`](\.\/[^\'"`]+|(\.\.\/)*[^\'"`]+)[\'"`]\s*[;\)]
    ?
/mx';
```

Comment (AurelienPillevesse) [reply src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php]: Another solution can be : 

```php
private const PATTERN_LINES_START_WITH_COMMENTS = '(?:\/\/.*)';
private const PATTERN_STRINGS_ENCLOSED_SINGLE_OR_DOUBLE_QUOTES = '(?:
            \'(?:[^\'\\\\]|\\\\.)*\'   # Strings enclosed in single quotes
        |
            "(?:[^"\\\\]|\\\\.)*"      # Strings enclosed in double quotes
        )
';
// ...
```

And you concat everything in the ```IMPORT_PATTERN```. What do you think about it ?

Comment (smnandre) [reply src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php]: I genuinely have no opinion here, just happy if the next person to work with this pattern does not lose time to understand why and how we made this regexp :) So you guys tell me

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @smnandre.
