### PR TITLE
[DI] Add ability to choose behavior of decorations on non existent decorated services

### LINKED ISSUE #33522: [DI] Handling decorations on non existent services
**Description**  
It would be nice to handle decorations on non existent services by either throwing the service not found exception or just silently ignoring the service all together, similar to how missing services as parameters are handles.

**Example**  
Imagine having an `OptionalBundle` with a service `OptionalBundle\Services\OptionalService` and another Bundle `DecoratorBundle` that has to decorate the `OptionalService` if present:
```xml
<service id="OptionalBundle\Services\OptionalService" class="OptionalBundle\Services\OptionalService" />
<!-- ... -->
<service id="DecoratorBundle\Service\Decorator\OptionalServiceDecorator" decorates="OptionalBundle\Services\OptionalService" class="DecoratorBundle\Service\Decorator\OptionalServiceDecorator" on-invalid="ignore" />
```

Now in my example I don't have `OptionalBundle` installed and the `DecoratorBundle` would be broken. With the new attribute `on-invalid` with values `exception`, `ignore`, `null` you can control the handling:
- `exception`: default, throw exception
- `ignore`: don't create decoration service at all
- `null`: create decoration service but if `service.inner` gets passed as a parameter it will be null -> might need explicit `on-invalid` attribute on parameter itself.

For YAML declaration I would suggest using the `@?` syntax as for arguments.

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | #33522
| License       | MIT
| Doc PR        | https://github.com/symfony/symfony-docs/pull/12442

# Handling decorations on non existent decorated services 
Handle decorations on non existent decorated services by either throwing the service not found exception, silently ignoring services (decorator & decorated) all together or leave the decorated service to null (current behavior)

Something almost similar to how missing services as parameters are handles.

## Yaml configuration
```yaml
decorator:
    decorates: decorated
    decoration_on_invalid: ignore
```
Available values: `exception`, `ignore`, `null`. `exception` if nothing is specified.

## Xml configuration
```xml
<service id="decorator" decorates="decorated" decoration-on-invalid="ignore" />
```
Available values: `exception`, `ignore`, `null`. `exception` if nothing is specified.

## Behavior
- `exception`: Throws a `ServiceNotFoundException` telling that the decorator's dependency is missing
- `ignore`: Remove decorator definition. Decorator and decorated will not be available at all.
- `null`: Keep decorator but set decorated to null. Therefore, decorator `__construct` should be written with a nullable decorated dependency (`public function __contruct(?DecoratedInterface $decorated) {}`) and check should be done in other methods

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php [hunk 1]
```diff
@@ -117,8 +117,13 @@ private function addService(Definition $definition, ?string $id, \DOMElement $pa
             $service->setAttribute('lazy', 'true');
         }
         if (null !== $decorated = $definition->getDecoratedService()) {
-            list($decorated, $renamedId, $priority) = $decorated;
+            list($decorated, $renamedId, $priority, $onDecoratedInvalid) = $decorated;
             $service->setAttribute('decorates', $decorated);
+
+            if (\in_array($onDecoratedInvalid, [ContainerInterface::NULL_ON_INVALID_REFERENCE, ContainerInterface::IGNORE_ON_INVALID_REFERENCE])) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php]: !== EXCEPTION_ON_INVALID_REFERENCE?

File: src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php [hunk 2]
```diff
@@ -117,8 +117,13 @@ private function addService(Definition $definition, ?string $id, \DOMElement $pa
...
+                $invalidBehavior = ContainerInterface::NULL_ON_INVALID_REFERENCE === $onDecoratedInvalid ? 'nulled' : 'ignored';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php]: "null" / "ignore" ("nulled" / "ignored" wouldn't be consistent with existing "on-invalid" attributes)

File: src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php [hunk 3]
```diff
@@ -117,8 +117,13 @@ private function addService(Definition $definition, ?string $id, \DOMElement $pa
...
+                $service->setAttribute('decoration-on-decorated-invalid', $invalidBehavior);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php]: decoration-on-invalid

File: src/Symfony/Component/DependencyInjection/Dumper/YamlDumper.php [hunk 4]
```diff
@@ -132,14 +132,18 @@ private function addService(string $id, Definition $definition): string
...
             $code .= sprintf("        decorates: %s\n", $decorated);
             if (null !== $renamedId) {
                 $code .= sprintf("        decoration_inner_name: %s\n", $renamedId);
             }
             if (0 !== $priority) {
                 $code .= sprintf("        decoration_priority: %s\n", $priority);
             }
+            if (\in_array($onDecoratedInvalid, [ContainerInterface::NULL_ON_INVALID_REFERENCE, ContainerInterface::IGNORE_ON_INVALID_REFERENCE])) {
+                $invalidBehavior = ContainerInterface::NULL_ON_INVALID_REFERENCE === $onDecoratedInvalid ? 'nulled' : 'ignored';
+                $code .= sprintf("        decoration_on_decorated_invalid: %s\n", $invalidBehavior);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Dumper/YamlDumper.php]: same comments as for the xml dumper

File: src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php (hunk 2 above)
Comment (mtarld) [reply src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php]: Yes but how to deal with the "yaml problem" ?
As I written in the description, `null` without quotes with be interpreted as null value by YamlLoader.

File: src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php [hunk 5]
```diff
@@ -362,10 +362,28 @@ private function parseDefinition(\DOMElement $service, string $file, array $defa
...
+            $onDecoratedInvalid = $service->getAttribute('decoration-on-decorated-invalid') ?: 'exception';
+            if (!\in_array($onDecoratedInvalid, ['exception', 'ignored', 'nulled'])) {
+                throw new InvalidArgumentException(sprintf('Invalid attribute "decoration-on-decorated-invalid" defined for "%s" in "%s"', (string) $service->getAttribute('id'), $file));
+            }
+
             $renameId = $service->hasAttribute('decoration-inner-name') ? $service->getAttribute('decoration-inner-name') : null;
             $priority = $service->hasAttribute('decoration-priority') ? $service->getAttribute('decoration-priority') : 0;
-            $definition->setDecoratedService($value, $renameId, $priority);
+
+            switch ($onDecoratedInvalid) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php]: the switch is missing a "default" case where we would throw - btw, should the switch be replaced by if/elseif/else?

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php]: oh, there is a check before. better move the check in the "else" case, that's ease understanding the code.
Also, the exception message should tell about the possible values, and the wrong one.

File: src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php (hunk 2 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php]: `null`should throw an exception as it would be an invalid value to me

File: src/Symfony/Component/DependencyInjection/Tests/DefinitionTest.php [hunk 6]
```diff
@@ -21,7 +22,8 @@ class DefinitionTest extends TestCase
     public function testConstructor()
     {
         $def = new Definition('stdClass');
-        $this->assertEquals('stdClass', $def->getClass(), '__construct() takes the class name as its first argument');
+        $this->assertEquals('stdClass', $def->getClass(), '__construct() takes the class name as its fiuse Symfony\Component\DependencyInjection\ContainerInterface;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/DefinitionTest.php]: ?

File: src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php (hunk 2 above)
Comment (mtarld) [reply src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php]: Ok, so the end user should write something like `decoration_on_invalid: 'null'`.
If he writes: `decoration_on_invalid: null`, this will throw an exception.
I think that the exception have to be explicit. A lot of users will do the error to write `null` instead of `'null'`

File: src/Symfony/Component/DependencyInjection/Tests/DefinitionTest.php (hunk 6 above)
Comment (mtarld) [reply src/Symfony/Component/DependencyInjection/Tests/DefinitionTest.php]: Sorry about that...

File: src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php (hunk 2 above)
Comment (mtarld) [reply src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php]: What do you think about : `The configuration key "decoration_on_invalid" is unsupported for the service "%s" in "%s". Allowed configuration keys are "exception", "ignore" and "null". If you written "null", ensure that it is surrounded with quotes.` ?

File: src/Symfony/Component/DependencyInjection/Definition.php [hunk 7]
```diff
@@ -127,26 +127,32 @@ public function getFactory()
...
+            throw new InvalidArgumentException(sprintf('Invalid invalidBehavior value for "%s" decorated service. Allowed values are ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE, ContainerInterface::IGNORE_ON_INVALID_REFERENCE and ContainerInterface::NULL_ON_INVALID_REFERENCE.', $id));
+        }
+
         $this->changes['decorated_service'] = true;
 
         if (null === $id) {
             $this->decoratedService = null;
         } else {
-            $this->decoratedService = [$id, $renamedId, (int) $priority];
+            $this->decoratedService = [$id, $renamedId, (int) $priority, $invalidBehavior];
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Definition.php]: $invalidBehavior should be appended only when it is different from EXCEPTION_ON_INVALID_REFERENCE: that will allow reverting all changes to existing tests, which would be a nice proof there is no BC break here.

Comment (mtarld) [reply src/Symfony/Component/DependencyInjection/Definition.php]: Got it, thanks !

File: src/Symfony/Component/DependencyInjection/Compiler/DecoratorServicePass.php [hunk 8]
```diff
@@ -37,7 +40,8 @@ public function process(ContainerBuilder $container)
         $decoratingDefinitions = [];
 
         foreach ($definitions as list($id, $definition)) {
-            list($inner, $renamedId) = $definition->getDecoratedService();
+            $decoratedDefinition = $definition->getDecoratedService();
+            list($inner, $renamedId) = $decoratedDefinition;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/DecoratorServicePass.php]: this change should be reverted

File: src/Symfony/Component/DependencyInjection/Definition.php [hunk 9]
```diff
@@ -127,26 +127,35 @@ public function getFactory()
...
      */
-    public function setDecoratedService($id, $renamedId = null, $priority = 0)
+    public function setDecoratedService($id, $renamedId = null, $priority = 0/*, int $invalidBehavior = ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE*/)
     {
         if ($renamedId && $id === $renamedId) {
             throw new InvalidArgumentException(sprintf('The decorated service inner name for "%s" must be different than the service name itself.', $id));
         }
 
+        $invalidBehavior = (3 < \func_num_args()) ? (int) func_get_arg(3) : ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE;
+        if (!\in_array($invalidBehavior, [ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE, ContainerInterface::IGNORE_ON_INVALID_REFERENCE, ContainerInterface::NULL_ON_INVALID_REFERENCE])) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Definition.php]: I don't think we need this check - we don't have in in `Reference`

File: src/Symfony/Component/DependencyInjection/Compiler/DecoratorServicePass.php [hunk 10]
```diff
@@ -46,6 +50,26 @@ public function process(ContainerBuilder $container)
             }
             $definition->innerServiceId = $renamedId;
 
+            if (!$container->has($inner)) {
+                $invalidBehavior = $decorated[3] ?? ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE;
+
+                if (ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE === $invalidBehavior) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/DecoratorServicePass.php]: this should be the "default" case, when $invalidBehavior is neither "ignore" nor "null" - defensive programming rulez.

File: src/Symfony/Component/DependencyInjection/Definition.php [hunk 11]
```diff
@@ -127,26 +127,35 @@ public function getFactory()
...
+            throw new InvalidArgumentException(sprintf('Invalid invalidBehavior value for "%s" decorated service. Allowed values are ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE, ContainerInterface::IGNORE_ON_INVALID_REFERENCE and ContainerInterface::NULL_ON_INVALID_REFERENCE.', $id));
+        }
+
         $this->changes['decorated_service'] = true;
 
         if (null === $id) {
             $this->decoratedService = null;
         } else {
             $this->decoratedService = [$id, $renamedId, (int) $priority];
+            if (ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE !== $invalidBehavior) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Definition.php]: let's add a blank line before

File: src/Symfony/Component/DependencyInjection/Definition.php [hunk 12]
```diff
@@ -127,26 +127,35 @@ public function getFactory()
...
      * @throws InvalidArgumentException in case the decorated service id and the new decorated service id are equals
      */
-    public function setDecoratedService($id, $renamedId = null, $priority = 0)
+    public function setDecoratedService($id, $renamedId = null, $priority = 0/*, int $invalidBehavior = ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE*/)
     {
         if ($renamedId && $id === $renamedId) {
             throw new InvalidArgumentException(sprintf('The decorated service inner name for "%s" must be different than the service name itself.', $id));
         }
 
+        $invalidBehavior = (3 < \func_num_args()) ? (int) func_get_arg(3) : ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Definition.php]: the extra brackets should be removed

File: src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php [hunk 13]
```diff
@@ -116,9 +116,14 @@ private function addService(Definition $definition, ?string $id, \DOMElement $pa
...
             $service->setAttribute('lazy', 'true');
         }
-        if (null !== $decorated = $definition->getDecoratedService()) {
-            list($decorated, $renamedId, $priority) = $decorated;
+        if (null !== $decoratedService = $definition->getDecoratedService()) {
+            list($decorated, $renamedId, $priority) = $decoratedService;
             $service->setAttribute('decorates', $decorated);
+            $onDecoratedInvalid = $decoratedService[3] ?? ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE;
+            if (ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE !== $onDecoratedInvalid) {
+                $invalidBehavior = ContainerInterface::NULL_ON_INVALID_REFERENCE === $onDecoratedInvalid ? 'null' : 'ignore';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Dumper/XmlDumper.php]: defensive programming here too: null / ignore should be dumped only when the match is confirmed, and any other value should not generate any dump

File: src/Symfony/Component/DependencyInjection/Dumper/YamlDumper.php [hunk 14]
```diff
@@ -131,15 +131,20 @@ private function addService(string $id, Definition $definition): string
...
             $code .= sprintf("        decorates: %s\n", $decorated);
             if (null !== $renamedId) {
                 $code .= sprintf("        decoration_inner_name: %s\n", $renamedId);
             }
             if (0 !== $priority) {
                 $code .= sprintf("        decoration_priority: %s\n", $priority);
             }
+            $onDecoratedInvalid = $decoratedService[3] ?? ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE;
+            if (ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE !== $onDecoratedInvalid) {
+                $invalidBehavior = ContainerInterface::NULL_ON_INVALID_REFERENCE === $onDecoratedInvalid ? 'null' : 'ignore';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Dumper/YamlDumper.php]: see above

File: src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php [hunk 15]
```diff
@@ -362,10 +362,22 @@ private function parseDefinition(\DOMElement $service, string $file, array $defa
...
+        if ($decorates = $service->getAttribute('decorates')) {
+            $onDecoratedInvalid = $service->getAttribute('decoration-on-invalid') ?: 'exception';
+            if ('exception' === $onDecoratedInvalid) {
+                $invalidBehavior = ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE;
+            } elseif ('ignore' === $onDecoratedInvalid) {
+                $invalidBehavior = ContainerInterface::IGNORE_ON_INVALID_REFERENCE;
+            } elseif ('null' === $onDecoratedInvalid) {
+                $invalidBehavior = ContainerInterface::NULL_ON_INVALID_REFERENCE;
+            } else {
+                throw new InvalidArgumentException(sprintf('Invalid attribute "decoration-on-invalid" defined for "%s" in "%s". Allowed values are "exception", "ignore" and "null".', (string) $service->getAttribute('id'), $file));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php]: `'Invalid value "%s" for attribute "decoration-on-invalid" on service "%s". Did you mean "exception", "ignore" or "null" in "%s"?'`

(similar in YamlFileLoader)

File: src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php [hunk 16]
```diff
@@ -538,14 +539,26 @@ private function parseDefinition(string $id, $service, string $file, array $defa
             $definition->addTag($name, $tag);
         }
 
-        if (isset($service['decorates'])) {
-            if ('' !== $service['decorates'] && '@' === $service['decorates'][0]) {
-                throw new InvalidArgumentException(sprintf('The value of the "decorates" option for the "%s" service must be the id of the service without the "@" prefix (replace "%s" with "%s").', $id, $service['decorates'], substr($service['decorates'], 1)));
+        if ($decorates = $service['decorates'] ?? null) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php]: `if (null !== ...`

File: src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php [hunk 17]
```diff
@@ -538,14 +539,26 @@ private function parseDefinition(string $id, $service, string $file, array $defa
...
+            if ('' !== $decorates && '@' === $decorates[0]) {
+                throw new InvalidArgumentException(sprintf('The value of the "decorates" option for the "%s" service must be the id of the service without the "@" prefix (replace "%s" with "%s").', $id, $service['decorates'], substr($decorates, 1)));
+            }
+
+            $onDecoratedInvalid = array_key_exists('decoration_on_invalid', $service) ? $service['decoration_on_invalid'] : 'exception';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php]: `\array_key_exists`

File: src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php [hunk 18]
```diff
@@ -538,14 +539,26 @@ private function parseDefinition(string $id, $service, string $file, array $defa
...
+            if ('exception' === $onDecoratedInvalid) {
+                $invalidBehavior = ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE;
+            } elseif ('ignore' === $onDecoratedInvalid) {
+                $invalidBehavior = ContainerInterface::IGNORE_ON_INVALID_REFERENCE;
+            } elseif (null === $onDecoratedInvalid) {
+                $invalidBehavior = ContainerInterface::NULL_ON_INVALID_REFERENCE;
+            } else {
+                throw new InvalidArgumentException(sprintf('The configuration key "decoration_on_invalid" is unsupported for the service "%s" in "%s". Allowed values are "exception", "ignore" and "null".', $id, $file));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php]: `'Invalid value "%s" for attribute "decoration_on_invalid" on service "%s". Did you mean "exception", "ignore" or null in "%s"?'`

we could also have a dedicated exception message when `'null' === $onDecoratedInvalid`

File: src/Symfony/Component/DependencyInjection/Compiler/DecoratorServicePass.php [hunk 19]
```diff
@@ -46,6 +50,26 @@ public function process(ContainerBuilder $container)
...
+                    throw new ServiceNotFoundException($inner, $id);
+                }
+
+                if (ContainerInterface::IGNORE_ON_INVALID_REFERENCE === $invalidBehavior) {
+                    $container->removeDefinition($id);
+                }
+
+                if (ContainerInterface::NULL_ON_INVALID_REFERENCE === $invalidBehavior) {
+                    $innerReferenceId = array_search($renamedId, array_map('strval', $definition->getArguments()));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/DecoratorServicePass.php]: this doesn't work
actually, this might invalidate the entire implementation :)
what about relying on the type of reference instead of using a new attribute?

File: src/Symfony/Component/DependencyInjection/Definition.php (hunk 9 above)
Comment (mtarld) [reply src/Symfony/Component/DependencyInjection/Definition.php]: Ok, then when a call is done with an out of bounds value (`setDecoratedService('unknown_decorated', null, 0, 12)` for example), it will silently fall back to the exception behavior

**Review by nicolas-grekas — APPROVED** [review]
(FYI, I made some tweaks, esp. in `ResolveInvalidReferencesPass`)

File: src/Symfony/Component/DependencyInjection/Compiler/ResolveInvalidReferencesPass.php [hunk 20]
```diff
@@ -101,6 +103,12 @@ private function processValue($value, int $rootLevel = 0, int $level = 0)
             if ($this->container->has($id = (string) $value)) {
                 return $value;
             }
+
+            // resolve decorated service behavior depending on decorator service
+            if (ContainerInterface::NULL_ON_INVALID_REFERENCE === $this->currentDefinition->onDecoratedInvalid) {
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Compiler/ResolveInvalidReferencesPass.php]: this looks wrong to me, as the decoration setting should apply only to the reference to the inner service, not to all references of the decorator service

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/DependencyInjection/Compiler/ResolveInvalidReferencesPass.php (hunk 20 above)
Comment (mtarld) [reply src/Symfony/Component/DependencyInjection/Compiler/ResolveInvalidReferencesPass.php]: You're perfectly right !
I fixed it and added related test, thanks.

File: src/Symfony/Component/DependencyInjection/Compiler/ResolveInvalidReferencesPass.php [hunk 21]
```diff
@@ -101,6 +103,12 @@ private function processValue($value, int $rootLevel = 0, int $level = 0)
             if ($this->container->has($id = (string) $value)) {
                 return $value;
             }
+
+            // resolve decorated service behavior depending on decorator service
+            if ($this->currentDefinition->innerServiceId === $id && ContainerInterface::NULL_ON_INVALID_REFERENCE === $this->currentDefinition->onDecoratedInvalid) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/ResolveInvalidReferencesPass.php]: Let's make a single property from these two and turn this check into, the 2nd check is not needed: let's just not populate the property when it should not be checked.
`if ($this->currentDefinition->innerNullableServiceId === $id) {`

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Compiler/ResolveInvalidReferencesPass.php]: Hum, I forgot `innerServiceId` already exists, nevermind.

File: src/Symfony/Component/DependencyInjection/Definition.php [hunk 22]
```diff
@@ -56,6 +56,13 @@ class Definition
      */
     public $innerServiceId;
 
+    /**
+     * @internal
+     *
+     * Used to store the behavior to follow when using service decoration and when decorated service is invalid
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Definition.php]: when *the* decorated

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Definition.php]: and the decorated service is not found

File: src/Symfony/Component/DependencyInjection/Compiler/ResolveInvalidReferencesPass.php (hunk 21 above)
Comment (mtarld) [reply src/Symfony/Component/DependencyInjection/Compiler/ResolveInvalidReferencesPass.php]: `innerServiceId` is already used by `src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php:149`

I can replace `onDecoratedInvalid` by `innerNullableServiceId` but I'm not sure it's that useful

**Review by stof — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
There is a force-push collision here, the changes from https://github.com/symfony/symfony/compare/8bee11a60198ecb0729b451165f3e6036911d7db..33098d2ba8f5fbea8229ff4fc64a6215e138ea5c are lost. Please recover them :)

**Comment by OskarStark** [comment]
Good to go @nicolas-grekas ❓

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @mtarld.
