### PR TITLE
[FrameworkBundle] Command cache:pool:clear warns and fails when one of the pools fails to clear

### LINKED ISSUE #39890: cache:pool:clear never fails on permission errors
**Symfony version(s) affected**: 5.2.0

**Description**  
`cache:pool:clear` does not report an error when it fails to clear cache. Specifically, if the current user does not have permission to modify a cache file on disk, it still reports success. However, the same is not true of `cache:pool:delete`. 

**How to reproduce**  
>bin/console cache:pool:delete cache.app foo

```
11:11:37 WARNING   [cache] Failed to delete key "foo". ["key" => "foo","exception" => null,"cache-adapter" => "Symfony\Component\Cache\Adapter\PhpFilesAdapter"]
11:11:37 ERROR     [console] Error thrown while running command "cache:pool:delete 'cache.app' 'foo'". Message: "Cache item "foo" could not be deleted." ["exception" => Exception { …},"command" => "cache:pool:delete 'cache.app' 'foo'","message" => "Cache item "foo" could not be deleted."]

In CachePoolDeleteCommand.php line 76:

  Cache item "foo" could not be deleted.

```

✔️ Error reported

>bin/console cache:pool:clear cache.app

```

 // Clearing cache pool: cache.app


 [OK] Cache was successfully cleared.
```

❌ Despite reporting success, cache is not actually cleared or modified in any way when the current user does not have permission to write to the cache files.

**Possible Solution**  
Report failure if one or more items could not be deleted.

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | fix #39890
| License       | MIT
| Doc PR        | -

Throw an exception when clear cache fails

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/Tests/Functional/CachePoolClearCommandTest.php [hunk 1]
```diff
@@ -73,6 +74,32 @@ public function testClearUnexistingPool()
             ->execute(['pools' => ['unknown_pool']], ['decorated' => false]);
     }
 
+    public function testClearFailed()
+    {
+        $tester = $this->createCommandTester();
+        /** @var FilesystemAdapter $a */
```
Comment (OskarStark) [inline src/Symfony/Bundle/FrameworkBundle/Tests/Functional/CachePoolClearCommandTest.php]: $a ? 🧐

Comment (jderusse) [reply src/Symfony/Bundle/FrameworkBundle/Tests/Functional/CachePoolClearCommandTest.php]: :facepalm:

**Comment by nicolas-grekas** [comment]
(failure on Windows)

**Comment by jderusse** [comment]
> (failure on Windows)

test refactored to be compatible with windows

File: src/Symfony/Bundle/FrameworkBundle/Command/CachePoolClearCommand.php [hunk 2]
```diff
@@ -89,16 +89,25 @@ protected function execute(InputInterface $input, OutputInterface $output): int
...
             } else {
-                $this->poolClearer->clearPool($id);
+                if (false === $this->poolClearer->clearPool($id)) {
+                    $failures[] = $id;
+                }
             }
         }
 
+        if ($failures) {
+            throw new \Exception(sprintf('Cache pool "%s" could not be cleared.', implode('", "', $failures)));
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Command/CachePoolClearCommand.php]: I think a warning + return 1 would be more appropriate to me

Comment (jderusse) [reply src/Symfony/Bundle/FrameworkBundle/Command/CachePoolClearCommand.php]: done

File: src/Symfony/Bundle/FrameworkBundle/Tests/Functional/CachePoolClearCommandTest.php [hunk 3]
```diff
@@ -73,6 +75,33 @@ public function testClearUnexistingPool()
...
+        /** @var SplFileInfo $entry */
+        foreach (new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($poolDir)) as $entry) {
+            // converts files into dir to make adapter fail
+            if ($entry->isFile()) {
+                unlink($entry->getPathname());
+                mkdir($entry->getPathname());
+            }
+        }
+
+        $this->expectExceptionMessage('Cache pool "cache.public_pool" could not be cleared.');
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Tests/Functional/CachePoolClearCommandTest.php]: needs to be updated :)

Comment (jderusse) [reply src/Symfony/Bundle/FrameworkBundle/Tests/Functional/CachePoolClearCommandTest.php]: :facepalm: fixed

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @jderusse.
