### PR TITLE
[Cache] use copy() instead of rename() on Windows

### LINKED ISSUE #50326: [Cache] FilesystemCommonTrait - rename fails on windows
### Symfony version(s) affected

4.x > 6.x

### Description

The rename function can fail on windows for some php versions

https://github.com/symfony/cache/blob/1ce7ed8e7ca6948892b6a3a52bb60cf2b04f7c94/Traits/FilesystemCommonTrait.php#LL107C17-L107C17

This is a current php issue here
https://github.com/php/php-src/issues/7910

For context, I've found the issue while working with SilverStripe cache adapter (it's using cache version 4, but since it's an issue with the rename function, I suspect it's going to be the same for 5.x and 6.x)
https://github.com/silverstripe/silverstripe-framework/issues/10634

I've also found that it has been an issue in composer that needed platform specific fix here
https://github.com/composer/composer/pull/10446

### How to reproduce

here is a demo here showing the issue

https://github.com/johnstevenson/php-rename-bug/actions/runs/1669358275

### Possible Solution

Don't use rename function

replace with (for all, or only for windows using platform check)

```php
$didCopy = copy($oldName, $newName, $context);

if (!$didCopy) {
    return false;
}

@unlink($oldName, $context);

return true;
```

### Additional Context

Example error log
...\\silverstripe-cache\\...\configcache\\U\\F\\QAdjY48zDlbAQWHpYUrw): Access is denied (code: 5) at ...\\vendor\\symfony\\cache\\Traits\\FilesystemCommonTrait.php:115)"} []

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #50326
| License       | MIT

On Windows depending on the PHP version `rename()` can fail if the target file is being executed. Since the source file is not used by another process using `copy()` instead should be safe to be used.

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php [hunk 1]
```diff
@@ -114,7 +114,12 @@ private function write(string $file, string $data, ?int $expiresAt = null)
...
             }
 
-            $success = rename($this->tmp, $file);
+            if ('\\' === \DIRECTORY_SEPARATOR) {
+                $success = copy($this->tmp, $file);
+            } else {
+                $success = rename($this->tmp, $file);
+            }
+
             $unlink = !$success;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php]:
```suggestion
            if ('\\' === \DIRECTORY_SEPARATOR) {
                $success = copy($this->tmp, $file);
                $unlink = true;
            } else {
                $success = rename($this->tmp, $file);
                $unlink = !$success;
            }
```

Comment (xabbuh) [reply src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php]: done

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Comment by gggeek** [comment]
I am curious:
- is `copy` an atomic operation on windows? If not, using it is not a very good idea - cache readers might get a half-written version of the file
- does `copy` actually allow to overwrite a file which is being executed?
- under which scenario would someone be executing a file straight out of the Sf cache? I would think that the cache storage is kind of 'private access'...

**Comment by gggeek** [comment]
ps: further thoughts
- it seems the OP is conflating issues in different systems which have differenr fixes, eg. composer is running `copy` vs `unlink` as external shell processes
- the proposed fix for php-src seems at 1st sight better than this. It would not work for all cases where the target file is executed, but at least cover the common scenario of the target file being a php script...
