### PR TITLE
[Yaml] fix lexing nested sequences/mappings

### LINKED ISSUE #34805: [YAML] Regression in parsing inline objects since version 4.4
**Symfony version(s) affected**: 4.4.x (it works in 3.x as well as 4.x up to 4.3, [4.4 or greater is failing](https://travis-ci.org/cebe/php-openapi/builds/620519083))

**Description**  

Parsing inline Objects in YAML is broken since 4.4, see example script below.

**How to reproduce**  

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$yaml = \Symfony\Component\Yaml\Yaml::parse(<<<YAML
data:
  example:
    {
      "total": 2,
      "apis": [
        {
          "apiKey": "oa_citations",
          "apiVersionNumber": "v1",
        },
        {
          "apiKey": "cancer_moonshot",
          "apiVersionNumber": "v1",
        }
      ]
    }
YAML
);

print_r($yaml);
```

On yaml versions <4.4, it shows the correct parsing:

```
Array
(
    [data] => Array
        (
            [example] => Array
                (
                    [total] => 2
                    [apis] => Array
                        (
                            [0] => Array
                                (
                                    [apiKey] => oa_citations
                                    [apiVersionNumber] => v1
                                )
                            [1] => Array
                                (
                                    [apiKey] => cancer_moonshot
                                    [apiVersionNumber] => v1
                                )
                        )
                )
        )
)
```

since 4.4 I get the following error:

```php
Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: Malformed inline YAML string: {
  "total": 2,
  "apis": [
    {
      "apiKey": "oa_citations",
      "apiVersionNumber": "v1",
    },
    {
      "apiKey": "cancer_moonshot",
      "apiVersionNumber": "v1",
    }
  ]
} at line 15 (near "}"). in /home/cebe/dev/layer5/layer5-ng/vendor-dev/cebe/php-openapi/vendor/symfony/yaml/Inline.php on line 300

Symfony\Component\Yaml\Exception\ParseException: Malformed inline YAML string: {
  "total": 2,
  "apis": [
    {
      "apiKey": "oa_citations",
      "apiVersionNumber": "v1",
    },
    {
      "apiKey": "cancer_moonshot",
      "apiVersionNumber": "v1",
    }
  ]
} at line 15 (near "}"). in /home/cebe/dev/layer5/layer5-ng/vendor-dev/cebe/php-openapi/vendor/symfony/yaml/Inline.php on line 300
```

**Additional info**

could be related to https://github.com/symfony/yaml/commit/110e3e9eaa7827def84cb1cfee95a6cfde4bf608 (https://github.com/symfony/symfony/pull/33658)

### LINKED ISSUE #37788: Unexpected characters using YAML compact syntax
**Symfony version(s) affected**: 5.1.3

**Description**  
I am reading the following YAML file, but I get a parser exception.

**How to reproduce**  

This is the code:

            $config = Yaml::parseFile($ps_filepath, Yaml::PARSE_CONSTANT);

I am reading the following YAML file:

```yaml
macro_scalar : /usr/local/fish
macro_list : [flounder, lobster, haddock]
macro_assoc : { 
  fish : [flounder, cod, haddock],
  shellfish : [scallop, crab, clam],
  other : [chicken, pig, cow]
}

override_value: "global"

```

This is the error:

```
Unexpected characters near "

override_value: "global"" at line 10.
```

If I move line `override_value: "global"` to the begining of the file, the problem dissapears:

```yaml
override_value: "global"
macro_scalar : /usr/local/fish
macro_list : [flounder, lobster, haddock]
macro_assoc : { 
  fish : [flounder, cod, haddock],
  shellfish : [scallop, crab, clam],
  other : [chicken, pig, cow]
}
```

### LINKED ISSUE #39011: YAML parsing error on perfectly valid JSON
**Symfony version(s) affected**: symfony/yaml:3.4.35, symfony/yaml:5.1.8
The issue affects the latest version at time of writing.

**Description**  
YAML fails to parse perfectly valid JSON, even though YAML is a superset of JSON:
```json
[
  ["entry1", {}],
  ["entry2", {"entry3": "entryvalue"}]
]
```
The YAML/JSON passes when ran on http://www.yamllint.com and https://yaml-online-parser.appspot.com.

**How to reproduce**  
```json5
// composer.json
{
    "name": "demo/yaml-bug",
    "require": {
        "symfony/yaml": "^5.1"
    }
}
```
```php
<?php
require_once 'vendor/autoload.php';
use Symfony\Component\Yaml\Parser;

$yaml = new Parser();
$yaml_content = <<<YAML
[
  ["entry1", {}],
  ["entry2", {"entry3": "entryvalue"}]
]
YAML;
$yaml->parse($yaml_content);
```

throws the following:
```
PHP Fatal error:  Uncaught Symfony\Component\Yaml\Exception\ParseException:
  Malformed inline YAML string: "[["entry1", {}]," at line 2 (near "  ["entry1", {}],").
```

**Possible Solution** 
To avoid issues like this continuously happening, I believe the library should be capable of parsing every single YAML in the https://github.com/yaml/yaml-test-suite repo.
Or at the bare minimum other valid JSON.

e.g. the first [test file](https://github.com/yaml/yaml-test-suite/blob/master/test/229Q.tml) I picked up from that repository isn't currently parseable either.

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | #34805, #37788, #37876, #39011, #39013, #39064
| License       | MIT
| Doc PR        |

### CODE REVIEW

File: src/Symfony/Component/Yaml/Parser.php [hunk 1]
```diff
@@ -1207,10 +1207,17 @@ private function lexInlineMapping(string $yaml): string
             throw new \InvalidArgumentException(sprintf('"%s" is not a sequence.', $yaml));
         }
 
-        for ($i = 1; isset($yaml[$i]) && '}' !== $yaml[$i]; ++$i) {
+        $openParentheses = 1;
+
+        for ($i = 1; $i < strlen($yaml); ++$i) {
+            if ('{' === $yaml[$i]) {
```
Comment (stof) [inline src/Symfony/Component/Yaml/Parser.php]: be careful. You can have such chars appearing inside quoted strings, in which case it should not be counted in the balancing of parentheses.

Comment (stof) [reply src/Symfony/Component/Yaml/Parser.php]: same for arrays below.

Comment (xabbuh) [reply src/Symfony/Component/Yaml/Parser.php]: Yes, I have pending changes locally for fix the string parsing. They will be part of a different PR as I am not fully done yet.

**Comment by fabpot** [comment]
@xabbuh Is it something you're still willing to work on?

File: src/Symfony/Component/Yaml/Parser.php (hunk 1 above)
Comment (simonberger) [reply src/Symfony/Component/Yaml/Parser.php]: The issue exists in 4.4 already and is just (very) slightly increased. Could be handled in a separate PR before or after as well.
A simple example is:
```yaml
[
"]"
]
```

Comment (simonberger) [reply src/Symfony/Component/Yaml/Parser.php]: Nitpicking but imo it is even less possible to break with this patch. The brackets are more likely to come in pairs and those break in 4.4 while they are working in this change.
Still a bug surely...

File: src/Symfony/Component/Yaml/Parser.php [hunk 2]
```diff
@@ -1204,60 +1208,138 @@ private function parseQuotedString(string $yaml): ?string
...
-        }
-
-        for ($i = 1; isset($yaml[$i]) && '}' !== $yaml[$i]; ++$i) {
-        }
-
-        if (isset($yaml[$i]) && '}' === $yaml[$i]) {
-            return $yaml;
-        }
+        $quotedStringOffset = $cursor;
+        $cursor += strcspn($this->currentLine, $this->currentLine[$cursor], $cursor + 1) + 2;
```
Comment (simonberger) [inline src/Symfony/Component/Yaml/Parser.php]: A comment would be really helpful here or the function. This line is not self explaining within the context of this function.

**Review by simonberger — COMMENTED** [review]
Nicely done.

I just missed a test with strings in mappings/sequences containing brackets which has been fixed in this PR as well.
As a possible test the following part of `inlineNotationSpanningMultipleLinesProvider` passed successfully.

```
            'nested collections containing strings with bracket chars' => [
                [['ba[r'], ['[ba]r'], ['bar]'], ['foo' => 'bar{'], ['foo' => 'b{ar}'], ['foo' => 'bar}']],
                <<<YAML
[
    [
        "ba[r"
    ],
    [
        '[ba]r'
    ],
    [
        "bar]"
    ],
    {
        foo: "bar{"
    },
    {
        foo: "b{ar}"
    },
    {
        foo: 'bar}'
    }
]
```

**Comment by xabbuh** [comment]
Many thanks to @RevZer0, @simonberger and @Matth--. I have added the tests you added in #37876, #39013, and #39064 here.

File: src/Symfony/Component/Yaml/Parser.php (hunk 1 above)
Comment (xabbuh) [reply src/Symfony/Component/Yaml/Parser.php]: @simonberger I have added this one and your other suggestion from below here.

**Comment by xabbuh** [comment]
This is ready to be reviewed.

File: src/Symfony/Component/Yaml/Parser.php [hunk 3]
```diff
@@ -1183,60 +1187,99 @@ private function parseQuotedString(string $yaml): ?string
...
+    private function lexInlineQuotedString(int &$cursor): string
     {
-        if ('' === $yaml || '{' !== $yaml[0]) {
-            throw new \InvalidArgumentException(sprintf('"%s" is not a sequence.', $yaml));
-        }
-
-        for ($i = 1; isset($yaml[$i]) && '}' !== $yaml[$i]; ++$i) {
-        }
+        $quotedStringOffset = $cursor;
+        $cursor += strcspn($this->currentLine, $this->currentLine[$cursor], $cursor + 1) + 2;
```
Comment (jderusse) [inline src/Symfony/Component/Yaml/Parser.php]: what's about escaping the delimiter ? `foo: "quote \"me\"..."`

**Review by simonberger — APPROVED** [review]

File: src/Symfony/Component/Yaml/Parser.php (hunk 3 above)
Comment (simonberger) [reply src/Symfony/Component/Yaml/Parser.php]: Not sure if you meant that, but escaped quotes are not yet handled here and are leading to problems for example in this yaml test:
```
[
    ["te\"st"],["test"]
]
```

A test case like `["te\"st"]` would still pass because the function just reads the inline sequence to the end of the document without finding the end of its assumed second quote. It doesn't report a problem though.
Another simple error case is:

``` 
[
    ["te\"st]"]
]
```

**Review by simonberger — CHANGES_REQUESTED** [review]
Escaped quotes are not yet skipped in `lexInlineQuotedString` and are leading to problems for example in this yaml test:

```
[
    ["te\"st"],["test"]
]
```

Another simple error case is:

```
[
    ["te\"st]"]
]
```

File: src/Symfony/Component/Yaml/Parser.php (hunk 3 above)
Comment (xabbuh) [reply src/Symfony/Component/Yaml/Parser.php]: Thank you both @jderusse and @simonberger for your careful review. I have updated the lexing of quoted strings to take your considerations into account.

**Comment by simonberger** [comment]
There is (now) another small issue with escaped backslashes in quotes treated as the escape for the quote.

```
'escaped backslash in mapping' => [
                [['"']],
                <<<YAML
[
    ["\\"]
]
YAML
            ]
```

I got a segmentation error writing the yam like this: `[["\\"]]`. l didn't look further in. Should be related to the problem but maybe a boundary check isn't robust enough.

**Comment by xabbuh** [comment]
Did you mean `[["\\\\"]]`? `[["\\"]]` isn't valid YAML and runs into a parsing error for me locally.

**Comment by simonberger** [comment]
Depends how it is declared. In HEREDOC `[["\\"]]`in quotes `'[["\\\\"]]'`. 
There is also for me a parser error when using new lines, but there shouldn't.

`Malformed inline YAML string: ""\"] ]]]" at line 3 (near "]")`

**Comment by xabbuh** [comment]
@simonberger I don't see a difference here (see also https://3v4l.org/iOVjl). Could you please send a PR with a test case that you have in mind to my branch if you still think that something isn't working as expected?

**Comment by simonberger** [comment]
@xabbuh I am sorry. This was indeed my wrong test.

File: src/Symfony/Component/Yaml/Parser.php [hunk 4]
```diff
@@ -1137,106 +1141,148 @@ private function getLineTag(string $value, int $flags, bool $nextLineCheck = tru
...
+            } elseif ('\\' === $this->currentLine[-1]) {
                 $previousLineWasNewline = false;
                 $previousLineWasTerminatedWithBackslash = true;
             } else {
                 $previousLineWasNewline = false;
                 $previousLineWasTerminatedWithBackslash = false;
             }
-        }
+
+            $cursor = 0;
```
Comment (simonberger) [inline src/Symfony/Component/Yaml/Parser.php]: @xabbuh Regarding my segmentation fault. In a case with no ending quote like `[["\\"]]` the code runs into an infinite loop caused by this line. As this yaml had just one line the situation was just worse compared to the multiline formatting.

There should be no parseable result if we end the while loop without returning before, right?
Either the cursor needs to keep its value at the end or better directly throw an exception?!

File: src/Symfony/Component/Yaml/Parser.php [hunk 5]
```diff
@@ -1137,106 +1141,148 @@ private function getLineTag(string $value, int $flags, bool $nextLineCheck = tru
...
 
-            if (isset($this->currentLine[$i]) && ']' === $this->currentLine[$i]) {
-                break;
+            if (isset($this->currentLine[$cursor])) {
+                return 0 < $whitespacesConsumed;
             }
-        }
 
-        return $value;
+            $cursor = 0;
```
Comment (simonberger) [inline src/Symfony/Component/Yaml/Parser.php]: Here a problem for wrong invalid yaml documents as well (reproduced it if you need). Might be relevant in valid cases as well.

The last one is in `lexInlineMapping`. I didn't check if this can cause harm but at least it shouldn't set the cursor back there as well imo.

File: src/Symfony/Component/Yaml/Parser.php (hunk 4 above)
Comment (xabbuh) [reply src/Symfony/Component/Yaml/Parser.php]: Wow, thanks for testing the patch so carefully @simonberger. That's really appreciated. I have fixed this issue as well and now throw a `ParseException` as soon as possible.

**Review by simonberger — APPROVED** [review]
My pleasure. LGTM now.

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by derrabus** [comment]
@xabbuh Can I ask you to merge 4.4 into 5.1? This PR gives me a headache.

**Comment by xabbuh** [comment]
@derrabus done 👍
