### PR TITLE
[FrameworkBundle] Improve UX ConfigDebugCommand has not yaml component

### LINKED ISSUE #48429: `debug:config` command uses `Yaml` without checking for it's presence
### Symfony version(s) affected

x

### Description

running `debug:config framework` throws exception when `symfony/yaml` package is not installed

`Yaml` is used for output formatting:
https://github.com/symfony/symfony/blob/13059f6d13a595cf83424a4a8d847e3ec67a2098/src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php#L115

```bash
$ php bin/console debug:config framework

Current configuration for extension with alias "framework"
==========================================================

[critical] Error thrown while running command "debug:config framework". Message: "Class "Symfony\Component\Yaml\Yaml" not found"

In ConfigDebugCommand.php line 100:
                                                                           
  Attempted to load class "Yaml" from namespace "Symfony\Component\Yaml".  
  Did you forget a "use" statement for another namespace?                  
                                                                           

debug:config [--resolve-env] [--] [<name> [<path>]]

2022-12-01T14:06:28+00:00 [critical] Uncaught Error: Class "Symfony\Component\Yaml\Yaml" not found
``` 

### How to reproduce

create empty symfony project
change config format from `yaml` to `php`
remove `symfony/yaml` from composer dependencies
run `debug:config framework`

### Possible Solution

use backoff formatting helper (e.g. `var_export`, `print_r`, `json_serialize`, ...) for output

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alamirault**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Tickets       | Fix #48429
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Throw exception in order to improve UX when Yaml component is missing 

Message is inspired by https://github.com/symfony/symfony/blob/043257f6fc1fceb28bc0c37c59f2bea4d9c8d79d/src/Symfony/Component/Serializer/Encoder/YamlEncoder.php#L56

### CODE REVIEW

**Comment by GromNaN** [comment]
The command could fallback to json when the Yaml class is not available, the format is very similar (a little more verbose). You can add an option `format` to make the switch, like we did in `config:dump-reference`.

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php [hunk 1]
```diff
@@ -38,6 +38,15 @@
 #[AsCommand(name: 'debug:config', description: 'Dump the current configuration for an extension')]
 class ConfigDebugCommand extends AbstractConfigCommand
 {
+    public function __construct(string $name = null)
+    {
+        if (!class_exists(Yaml::class)) {
+            throw new \RuntimeException('The ConfigDebugCommand class requires the "Yaml" component. Install "symfony/yaml" to use it.');
```
Comment (OskarStark) [inline src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: "Install "symfony/yaml" to use it."

In other code parts we use something like:

"Try composer require symfony/yaml...."

**Comment by alamirault** [comment]
> and could fallback to json when the Yaml class is not available, the format is very similar (a little more verbose). You can add an option `format` to make the switch, like we did in `config:dump-reference`.

Indeed it's better to have option like other comment ! I will rework PR to add it

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php [hunk 2]
```diff
@@ -55,13 +57,18 @@ protected function configure()
   <info>php %command.full_name% framework</info>
   <info>php %command.full_name% FrameworkBundle</info>
 
-For dumping a specific option, add its path as second argument:
+With the <info>--format</info> option specifies the format of the configuration,
```
Comment (OskarStark) [inline src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: This sentence sounds weird 🤔

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php [hunk 3]
```diff
@@ -112,11 +133,20 @@ protected function execute(InputInterface $input, OutputInterface $output): int
...
 
         return 0;
     }
 
+    private function convertToFormat(mixed $config, string $format): string
+    {
+        return match ($format) {
+            'yaml' => Yaml::dump($config, 10),
+            'json' => json_encode($config, \JSON_PRETTY_PRINT),
+            default => throw new InvalidArgumentException('Only the yaml and json formats are supported.'),
```
Comment (OskarStark) [inline src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]:
```suggestion
            default => throw new InvalidArgumentException('Only "yaml" and "json" formats are supported.'),
```

Comment (OskarStark) [reply src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: Or use `implode` and the `getAvailableFormatOptions()` method here?

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php [hunk 4]
```diff
@@ -92,16 +99,30 @@ protected function execute(InputInterface $input, OutputInterface $output): int
...
             );
 
-            $io->writeln(Yaml::dump([$extensionAlias => $config], 10));
+            $io->writeln($this->convertToFormat([$extensionAlias => $config], $format));
 
             return 0;
         }
 
+        if ('yaml' !== $format) {
+            $errorIo->error('The "path" option is only available for the "yaml" format.');
```
Comment (GromNaN) [inline src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: Why? I don't see the issue to render a subsection of the data in JSON, is there?

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php [hunk 5]
```diff
@@ -92,16 +99,30 @@ protected function execute(InputInterface $input, OutputInterface $output): int
 
         $config = $this->getConfig($extension, $container, $input->getOption('resolve-env'));
 
+        $format = $input->getOption('format');
+
+        if ('yaml' === $format && !class_exists(Yaml::class)) {
+            $errorIo->error('Setting the "format" option to "yaml" requires the Symfony Yaml component. Try running "composer install symfony/yaml" or use "--format=json" instead.');
```
Comment (GromNaN) [inline src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php:108]: This is `composer require`

```suggestion
            $errorIo->error('The "yaml" format requires the installation of the Yaml component. Install it with "composer require symfony/yaml", or choose another format by specifying "--format=json".');
```

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php [hunk 6]
```diff
@@ -45,6 +46,7 @@ protected function configure()
                 new InputArgument('name', InputArgument::OPTIONAL, 'The bundle name or the extension alias'),
                 new InputArgument('path', InputArgument::OPTIONAL, 'The configuration option path'),
                 new InputOption('resolve-env', null, InputOption::VALUE_NONE, 'Display resolved environment variable values instead of placeholders'),
+                new InputOption('format', null, InputOption::VALUE_REQUIRED, 'The output format (yaml or json)', 'yaml'),
```
Comment (GromNaN) [inline src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: We could switch the default value by checking if yaml is available, that would improve the experience for projects without Yaml.

`default: class_exists(Yaml::class) ? 'yaml' : 'json'`.

**Review by GromNaN — COMMENTED** [review]
Much better, thank you for following the suggestion.

The text can be improved, we need some help for that.

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php [hunk 7]
```diff
@@ -112,11 +133,20 @@ protected function execute(InputInterface $input, OutputInterface $output): int
...
+        $io->writeln($this->convertToFormat($config, $format));
 
         return 0;
     }
 
+    private function convertToFormat(mixed $config, string $format): string
+    {
+        return match ($format) {
+            'yaml' => Yaml::dump($config, 10),
+            'json' => json_encode($config, \JSON_PRETTY_PRINT),
```
Comment (GromNaN) [inline src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: Add more options for good looking JSON.
```suggestion
            'json' => json_encode($config, \JSON_PRETTY_PRINT|\ JSON_UNESCAPED_SLASHES|\JSON_UNESCAPED_UNICODE),
```

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php (hunk 4 above)
Comment (alamirault) [reply src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: Condition took from another command, but indeed it's not a problem here

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php [hunk 8]
```diff
@@ -55,13 +57,17 @@ protected function configure()
...
+  <info>php %command.full_name% FrameworkBundle --format=json</info>
+
 For dumping a specific option, add its path as second argument:
 
   <info>php %command.full_name% framework serializer.enabled</info>
 
 EOF
-            )
-        ;
+            );
```
Comment (kaznovac) [inline src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: no need to change this

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php [hunk 9]
```diff
@@ -55,13 +57,17 @@ protected function configure()
   <info>php %command.full_name% framework</info>
   <info>php %command.full_name% FrameworkBundle</info>
 
+The <info>--format</info> option specifies the format of the configuration,
+this is either <comment>yaml</comment> or <comment>json</comment>.
+
+  <info>php %command.full_name% FrameworkBundle --format=json</info>
```
Comment (kaznovac) [inline src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]:
```suggestion
  <info>php %command.full_name% framework --format=json</info>
```

nitpick:
the command example bellow uses the bundle config name... looks more consistent to me that this example remains in the same manner

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php [hunk 10]
```diff
@@ -55,13 +57,17 @@ protected function configure()
   <info>php %command.full_name% framework</info>
   <info>php %command.full_name% FrameworkBundle</info>
 
+The <info>--format</info> option specifies the format of the configuration,
+this is either <comment>yaml</comment> or <comment>json</comment>.
```
Comment (kaznovac) [inline src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]:
```suggestion
The <info>--format</info> option specifies the output format of the configuration,
this is either <comment>yaml</comment> or <comment>json</comment>.
When the option is not provided, <comment>yaml</comment> is used when the <comment>symfony/yaml</comment> component is available,
otherwise the <comment>json</comment> will be used.
```

maybe use the same dynamic `getAvailableFormatOptions` approach to generate available format options?

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php [hunk 11]
```diff
@@ -228,4 +255,9 @@ private static function buildPathsCompletion(array $paths, string $prefix = ''):
 
         return $completionPaths;
     }
+
+    private function getAvailableFormatOptions(): array
+    {
+        return ['yaml', 'json'];
```
Comment (kaznovac) [inline src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php:265]: nitpick:
consider using enums, symfony ~6.1 targets php >=8.1

Comment (kaznovac) [reply src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php:265]: also this method might be the nice place to check for the availability of `yaml` formatter

**Review by kaznovac — COMMENTED** [review]
great work @alamirault

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php (hunk 11 above)
Comment (stof) [reply src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php:265]: Using an enum does not make sense. The option completion need an array of strings, and the value of the option will be a string. Enums won't bring any benefit here.

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php (hunk 10 above)
Comment (alamirault) [reply src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: I now use `getAvailableFormatOptions`, but don"t know a really adapt sentence.

> When the option is not provided, <comment>yaml</comment> is used when the <comment>symfony/yaml</comment> component is available,

Not sure if this detail is needed in help

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php [hunk 12]
```diff
@@ -92,12 +102,20 @@ protected function execute(InputInterface $input, OutputInterface $output): int
 
         $config = $this->getConfig($extension, $container, $input->getOption('resolve-env'));
 
+        $format = $input->getOption('format');
+
+        if ('yaml' === $format && !class_exists(Yaml::class)) {
+            $errorIo->error('The "yaml" format requires the installation of the Yaml component. Install it with "composer require symfony/yaml", or choose another format by specifying "--format=json".');
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: `Setting the "format" option to "yaml" requires the Symfony Yaml component. Try running "composer install symfony/yaml" or use "--format=json" instead.`
borrowed from ConfigDumpReferenceCommand

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php (hunk 12 above)
Comment (alamirault) [reply src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: Updated and rebased

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @alamirault.

**Comment by chalasr** [comment]
I didn't open a documentation issue as I believe those commands are not documented there, but it would be nice if you could double-check 🙏

**Comment by Toflar** [comment]
We have some inconsistency here. If you use `--format=json` on `debug:config` now, you do not actually get machine readable JSON as there's still the headline:

```
bin/console debug:config framework --format=json

Current configuration for extension with alias "framework"
==========================================================

{
    "framework": {
        "router": {
            "resource": "kernel::loadRoutes",
            "type": "service",
            "enabled": true,
            "utf8": true,
...
```

Is this desired? Should we probably skip the headline when `--format=json`? Or is it meant to be there as fallback only? Also, if you run `bin/console list --format=json` you do not get pretty printed JSON. It's actually meant to be machine readable. /cc @aschempp
