### PR TITLE
 [DependencyInjection] Optimize circular collection by removing flattening

### LINKED ISSUE #39015: Dependency Injection inifinite loop handling circular references consuming memory
**Symfony version(s) affected**: 5.2.x

**Description**  
Clearing the cache with latest symfony breaks on `api-platform/core`

**How to reproduce**  

```bash
git clone git@github.com:api-platform/core
cd core
# If you have moreutils, or just add the minimum-stability dev to the composer.json
jq '. + {"minimum-stability": "dev"}' composer.json | sponge composer.json
composer install
php tests/Fixtures/app/console cache:warmup -vv
```

This will lead to an out of memory error (be sure you don't use `memory_limit=-1`)

**Possible Solution**  

Revert the code changed in PhpDumper (see https://github.com/symfony/symfony/pull/38980/files#diff-82d7ebdd6477cecb404b0d3f100a9026e950529edb9a665460ae0330dfad7080L454)

```diff
        foreach ($edges as $edge) {
            $node = $edge->getDestNode();
            $id = $node->getId();
+            if (!$node->getValue() instanceof Definition || $sourceId === $id || $edge->isLazy() || $edge->isWeak()) {
-            if (!$node->getValue() instanceof Definition || $sourceId === $id || $edge->isWeak()) {
                continue;
            }
```

If you reproduced and want to try the fix, just `rm -rf tests/Fixtures/app/var/cache/` and use the command again.

ref: #38980

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39015
| License       | MIT
| Doc PR        | -

Alternative to #39019

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_almost_circular_private.php [hunk 1]
```diff
@@ -349,15 +349,13 @@ protected function getManager2Service()
...
-            return $this->services['manager3'];
-        }
-        $b = new \stdClass();
-        $b->listener = [0 => $a];
+        $this->services['manager3'] = $instance = new \stdClass($a);
 
-        return $this->services['manager3'] = new \stdClass($b);
+        $a->listener = [0 => ($this->services['listener3'] ?? $this->getListener3Service())];
+
+        return $instance;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_almost_circular_private.php]: The order of injection in this test case has changed:
manager3 is given a dependency that is missing its listener3 dep.

This is an issue to me, since these test cases are precisely about the order of the steps.

Comment (jderusse) [reply src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_almost_circular_private.php]: I'm not sure to get the issue. Here are the 2 methods. 

```php
    protected function getManager3Service($lazyLoad = true)
    {
        $a = new \stdClass();

        $this->services['manager3'] = $instance = new \stdClass($a);

        $a->listener = [0 => ($this->services['listener3'] ?? $this->getListener3Service())];

        return $instance;
    }

    protected function getListener3Service()
    {
        $this->services['listener3'] = $instance = new \stdClass();

        $instance->manager = ($this->services['manager3'] ?? $this->getManager3Service());

        return $instance;
    }
```

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_almost_circular_private.php]: Before the change, getManager3 returned `$this->services['manager3'] = new \stdClass($b);`, with $b being already configured (aka `$b->listener` set)
In the new method, the listener propery is set *after* manager3 got its dep.

Comment (jderusse) [reply src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_almost_circular_private.php]: hmmm ok, I get the issue: The object (`$a`) were not fully built at the time it were injected in Manager's constructor.

Comment (jderusse) [reply src/Symfony/Component/DependencyInjection/Tests/Fixtures/php/services_almost_circular_private.php]: Fixed by https://github.com/symfony/symfony/compare/d077e62d0d56325e67835353b9bd500418705668..de7ff0f3096c7a23d9936f1da4e645f68cf5c586#diff-82d7ebdd6477cecb404b0d3f100a9026e950529edb9a665460ae0330dfad7080R434

And also fix the second change (because I didn't collect ALL circular references for the same node).

Fixtures are identical to previous version. I tested with the projects I used for the 2 previous issues on this.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jderusse.
