### PR TITLE
[Yaml Parser] fixed Parser to skip comments when inlining sequences

### LINKED ISSUE #37972: !iterator tag does not support comments
**Symfony version(s) affected**: 4.4.10

**Description**  
When using the `!iterator` tag in yaml service definition files it does not support comments between the array initializer brackes. The bug occurs in constructor arguments as well when using the `calls` defintion.

**How to reproduce**  
Create a services.yaml and paste the following contents:

```yaml
    Foo\BarInterface:
        class: Foo\Bar
        arguments:
            - [!iterator [
                  '@service_a',
#                '@service_b',
            ]]
```

You will get an exception:  Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: "!iterator" tag only accepts arrays of "@service" references in "<config file>yaml".

### PR DESCRIPTION
**Pull request by korve**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37972
| License       | MIT

The parser didn't skip comments when parsing values in a sequence. This resulted in the YamlFileLoader trying to
parse a comment as a IteratorArgument which resulted in a InvalidArgumentException.

Consider the following valid yaml:

```yaml
- !foo [
    bar,
    #baz
  ]
```

The parser would generate the following array:
```php
['bar', '#baz']
```

After this fix the parser will generate the following array:
```php
['bar']
```

This  bug only appeared for me in 4.4

### CODE REVIEW

File: src/Symfony/Component/Yaml/Parser.php [hunk 1]
```diff
@@ -183,7 +183,7 @@ private function doParse(string $value, int $flags)
                             || self::preg_match('#^(?P<key>'.Inline::REGEX_QUOTED_STRING.'|[^ \'"\{\[].*?) *\:(\s+(?P<value>.+?))?\s*$#u', $this->trimTag($values['value']), $matches)
                         )
                     ) {
-                        // this is a compact notation element, add to next block and parse
+                        //  this is a compact notation element, add to next block and parse
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Yaml/Parser.php:186]: please revert

File: src/Symfony/Component/Yaml/Parser.php [hunk 2]
```diff
@@ -217,7 +217,7 @@ private function doParse(string $value, int $flags)
                 }
 
                 if (!\is_string($key) && !\is_int($key)) {
-                    throw new ParseException(sprintf('%s keys are not supported. Quote your evaluable mapping keys instead.', is_numeric($key) ? 'Numeric' : 'Non-string'), $this->getRealCurrentLineNb() + 1, $this->currentLine);
+                    throw new ParseException(sprintf('"%s" keys are not supported. Quote your evaluable mapping keys instead.', is_numeric($key) ? 'Numeric' : 'Non-string'), $this->getRealCurrentLineNb() + 1, $this->currentLine);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Yaml/Parser.php:220]: please revert (that's a fabbot's false positive)

File: src/Symfony/Component/Yaml/Parser.php [hunk 3]
```diff
@@ -232,7 +232,7 @@ private function doParse(string $value, int $flags)
                         $refName = substr(rtrim($values['value']), 1);
                         if (!\array_key_exists($refName, $this->refs)) {
                             if (false !== $pos = array_search($refName, $this->refsBeingParsed, true)) {
-                                throw new ParseException(sprintf('Circular reference [%s, %s] detected for reference "%s".', implode(', ', \array_slice($this->refsBeingParsed, $pos)), $refName, $refName), $this->currentLineNb + 1, $this->currentLine, $this->filename);
+                                throw new ParseException(sprintf('Circular reference [%s, "%s"] detected for reference "%s".', implode(', ', \array_slice($this->refsBeingParsed, $pos)), $refName, $refName), $this->currentLineNb + 1, $this->currentLine, $this->filename);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Yaml/Parser.php:235]: please revert (that's a fabbot's false positive)

File: src/Symfony/Component/Yaml/Parser.php [hunk 4]
```diff
@@ -708,7 +708,7 @@ private function parseValue(string $value, int $flags, string $context)
 
             if (!\array_key_exists($value, $this->refs)) {
                 if (false !== $pos = array_search($value, $this->refsBeingParsed, true)) {
-                    throw new ParseException(sprintf('Circular reference [%s, %s] detected for reference "%s".', implode(', ', \array_slice($this->refsBeingParsed, $pos)), $value, $value), $this->currentLineNb + 1, $this->currentLine, $this->filename);
+                    throw new ParseException(sprintf('Circular reference [%s, "%s"] detected for reference "%s".', implode(', ', \array_slice($this->refsBeingParsed, $pos)), $value, $value), $this->currentLineNb + 1, $this->currentLine, $this->filename);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Yaml/Parser.php:711]: please revert (that's a fabbot's false positive)

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/yaml/services9.yml [hunk 5]
```diff
@@ -177,3 +177,10 @@ services:
         public: true
     errored_definition:
         class: stdClass
+    foo_bar_with_iterator_comment:
+        class: Bar\FooClass
+        arguments:
+            - [!iterator [
+                '@service_a',
+                 # '@service_b',
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/yaml/services9.yml:185]: no need for this test, that's an issue with Yaml, not with DI

**Review by nicolas-grekas — COMMENTED** [review]
Thanks for having a look and submitting.

File: src/Symfony/Component/Yaml/Tests/ParserTest.php [hunk 6]
```diff
@@ -1898,6 +1898,30 @@ public function taggedValuesProvider()
...
+                ],
+                <<<YAML
+- [!foo [
+    foo,
+    baz,
+    #bar
+  ]]
+YAML
+            ],
+            'with-comments-trailing-comma' => [
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Tests/ParserTest.php:1913]: I fail to see how this test case differs from the previous one.

Comment (korve) [reply src/Symfony/Component/Yaml/Tests/ParserTest.php:1913]: Oops you're right. The 'with-comments' was meant to be without a comma after the 2nd array element.

**Review by xabbuh — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @korve.
