### PR TITLE
[HttpKernel] AbstractSessionListener should not override the cache lifetime for private responses

### LINKED ISSUE #47660: AbstractSessionListener should not override the cache lifetime for private responses
### Symfony version(s) affected

5.4, 6.x

### Description

When a response is marked as cacheable by a private cache, `AbstractSessionListener` will still override it with a max-age of 0 in case the session is used. This makes it impossible to have private cache when using stateful authentication (except by disabling the auto cache control).
Forcing the response to be private makes sense in AbstractSessionListener (as the response depends on the session), but it should respect an existing private cache control

### How to reproduce

Create a controller using authentication and returning a Response with `->setPrivate()` and `setMaxAge(180)`. Look at the headers in the devtool (not in the Symfony profiler as it collects headers before AbstractSessionListener runs).

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rodmen**
Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #47660 AbstractSessionListener should not override the cache lifetime
| License       | MIT

https://github.com/symfony/symfony/issues/47660 is opened as a bug
This PR fix that AbstractSessionListener override the max-age and the expires cache headers if cache control is private and these values are explicit defined

### CODE REVIEW

File: src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php [hunk 1]
```diff
@@ -200,10 +200,14 @@ public function onKernelResponse(ResponseEvent $event)
         }
 
         if ($autoCacheControl) {
+            $maxAge = 0;
+            if (!$response->headers->hasCacheControlDirective('public') && (bool) $response->getMaxAge()) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]: I'd suggest this CS instead:
```diff
         if ($autoCacheControl) {
+            $maxAge = $response->headers->hasCacheControlDirective('public') ? 0 : (int) $response->getMaxAge();
             $response
-                ->setExpires(new \DateTime())
+                ->setExpires(new \DateTimeImmutable('+'.$maxAge.' seconds'))
```

But LGTM otherwise thanks!

(please allow edits from maintainers, that makes it easier to deal with contributions on our side)

Comment (rodmen) [reply src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php]: Hi @nicolas-grekas ,
   I have applied the suggested CS, looks better now.
I can't allow edits for maintainers... I think it's because I opened the PR from an organization repository and that option is not available in that case (please correct me if I'm wrong).

**Comment by nicolas-grekas** [comment]
Thank you @rodmen.

**Comment by pkruithof** [comment]
I'm not sure whether this is the appropriate place, but I think I found a bug regarding this change (I'll open an actual issue if I'm correct about this).

In our case, we have the following situation: 
- a secured url is being requested, at which point an `AuthenticationEntryPoint` returns a redirect response to an external auth provider
- this response is marked with `cache-control: private, no-cache`
- following this, the response sets the `expires` to `-1` (see https://github.com/symfony/http-foundation/blob/9d081ead9d3432e2e8002178d14c4c9dd4b8ffbf/Response.php#L312) 
- the listener in this PR now sets the max-age to the value of `$response->getMaxAge()`, basically overwriting it with the same value. 

At least, this is the intention (I think). What actually happens now is this:

- `getMaxAge()` calculates the value when not explicitly set by subtracting the response date from the expires date
- `getExpires()` can't form a `DateTimeImmutable` from its `-1` value and falls back on [a default date in the past](https://github.com/symfony/http-foundation/blob/9d081ead9d3432e2e8002178d14c4c9dd4b8ffbf/Response.php#L708)
- this way `getMaxAge()` eventually does `{date in the past} - {current date}`, which in my particular case (at this moment) yields `-172800`
- `new \DateTimeImmutable('+'.$maxAge.' seconds')` is now tomorrow: 
  ```
  php > var_dump((new DateTimeImmutable('+-172800 seconds'))->format('c'));
  string(25) "2023-01-06T15:28:04+00:00"
  # (it's currently Jan. 5th)
  ``` 

So now we have a 302 response that has `private, no-cache` and `max-age=0`, but with an `Expires` header in the future. And apparently Firefox treats this as cacheable, so even after logging in, when visiting the original url I still get redirected to the auth provider because it serves the original 302 response from cache.

Sorry for the long description, but do you agree this is a bug? If so I'll file an issue or just a PR right away. I think the intended behaviour should be to only overwrite `max-age=0` when the response is public.

**Comment by stof** [comment]
this indeed looks like a bug
