### PR TITLE
[EventDispatcher] Better error reporting when arguments to dispatch() are swapped

### LINKED ISSUE #34676: [EventDispatcher] Incorrect error reported when arguments to dispatch() are swapped
**Symfony version(s) affected**: 4.4.0

**Description**  
The `EventDispatcherInterface` currently allows dispatching event by its name only (`dispatch($eventName)`) or by supplying the event and its name (`dispatch($event, $eventName)`).
In the second case, when the arguments are swapped, an incorrect error will be returned in some cases. Specifically, it will be incorrect when the event will be a subclass of `Symfony\Contracts\EventDispatcher\Event` as opposed to a subclass of `Symfony\Component\EventDispatcher\Event` (the latter has been deprecated since 4.3).

**How to reproduce**  
Attempt to dispatch an event that is a subclass of `Symfony\Contracts\EventDispatcher\Event` and swap the arguments (provide event name first, its object second).

**Possible Solution**  
The line in https://github.com/symfony/symfony/blob/ed22c856353a41f86c92fbf810cffb97fa542529/src/Symfony/Component/EventDispatcher/EventDispatcher.php#L57 should be updated to match both event types.

**Additional context**  
This issue is only valid for the 4.4 branch (and maybe 4.3?). In 5.0, `EventDispatcher` doesn't contain the code in question.

### PR DESCRIPTION
**Pull request by rimas-kudelis**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34676
| License       | MIT

Incorrect error is currently being reported when the second argument is an instance of `Symfony\Contracts\EventDispatcher\Event`.

### CODE REVIEW

File: src/Symfony/Component/EventDispatcher/EventDispatcher.php [hunk 1]
```diff
@@ -54,7 +54,7 @@ public function dispatch($event/*, string $eventName = null*/)
 
         if (\is_object($event)) {
             $eventName = $eventName ?? \get_class($event);
-        } elseif (\is_string($event) && (null === $eventName || $eventName instanceof Event)) {
+        } elseif (\is_string($event) && (null === $eventName || $event instanceof ContractsEvent || $eventName instanceof Event)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/EventDispatcher/EventDispatcher.php]: you mentioned using `\is_object($eventName)`, let's do it, no?

**Review by nicolas-grekas — COMMENTED** [review]
`LegacyEventDispatcherProxy` also needs a similar patch

**Review by nicolas-grekas — DISMISSED** [review]

File: src/Symfony/Component/EventDispatcher/EventDispatcher.php (hunk 1 above)
Comment (rimas-kudelis) [reply src/Symfony/Component/EventDispatcher/EventDispatcher.php]: I wasn't sure if you wanted people to pass random objects as events. :)

**Comment by nicolas-grekas** [comment]
It looks like we broken a test case sorry.

**Comment by rimas-kudelis** [comment]
Should I revert to checking for actual classes then, or change tests instead?

**Comment by nicolas-grekas** [comment]
> revert to checking for actual classes

yes please

File: src/Symfony/Component/EventDispatcher/EventDispatcher.php [hunk 2]
```diff
@@ -54,7 +54,7 @@ public function dispatch($event/*, string $eventName = null*/)
 
         if (\is_object($event)) {
             $eventName = $eventName ?? \get_class($event);
-        } elseif (\is_string($event) && (null === $eventName || \is_object($eventName))) {
+        } elseif (\is_string($event) && (null === $eventName || $event instanceof ContractsEvent || $eventName instanceof Event)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/EventDispatcher/EventDispatcher.php]: should be $eventName instead of $event, isn't it?

File: src/Symfony/Component/EventDispatcher/LegacyEventDispatcherProxy.php [hunk 3]
```diff
@@ -59,7 +59,7 @@ public function dispatch($event/*, string $eventName = null*/)
 
         if (\is_object($event)) {
             $eventName = $eventName ?? \get_class($event);
-        } elseif (\is_string($event) && (null === $eventName || \is_object($eventName))) {
+        } elseif (\is_string($event) && (null === $eventName || $event instanceof ContractsEvent || $eventName instanceof Event)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/EventDispatcher/LegacyEventDispatcherProxy.php]: $eventName

Comment (rimas-kudelis) [reply src/Symfony/Component/EventDispatcher/LegacyEventDispatcherProxy.php]: daaarn, sorry

**Review by nicolas-grekas — APPROVED** [review]

**Comment by rimas-kudelis** [comment]
Thanks for bearing with me! I can squash the commits if you like.

**Comment by nicolas-grekas** [comment]
Thank you @rimas-kudelis.
