### PR TITLE
[Form] Fix UUID exception

### LINKED ISSUE #39407: [Form] [Uid] Error on invalid uid submitted
**Symfony version(s) affected**: 5.2 (symfony/uid + symfony/form)

**Description**  
Hello,

I am using the newly shipped uid component :rocket: (great work btw) and implementing tests.

I have :
* a Product with a uuid as a primary key
* a form type having a product field which is an EntityType

When I submit the form with an invalid uid, it throws an exception causing a 500 which is not really friendly.

**How to reproduce**  

**Possible Solution**  
Would it be possible to have the same behaviour as any other choicetype so that we can have a 400 with an invalid error message ?

**Additional context**  
sf-uid-500

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39407
| License       | MIT
| Doc PR        | -

When submitting an invalid UUID, the exception thrown by `Form\ChoiceList\ORMQueryBuilderLoader` should be a `TransformationFailedException` in order to be properly intercepted by the `Form\Form` class

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php [hunk 1]
```diff
@@ -96,7 +98,11 @@ public function getEntitiesByIds(string $identifier, array $values)
                 $doctrineType = Type::getType($type);
                 $platform = $qb->getEntityManager()->getConnection()->getDatabasePlatform();
                 foreach ($values as &$value) {
-                    $value = $doctrineType->convertToDatabaseValue($value, $platform);
+                    try {
+                        $value = $doctrineType->convertToDatabaseValue($value, $platform);
+                    } catch (ConversionException $e) {
+                        throw new TransformationFailedException(sprintf('Failed to transform "%s" into %s".', $value, $type), 0, $e);
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php]: `s/ %s"/" "%s"`

**Review by nicolas-grekas — COMMENTED** [review]
Don't miss adding a test :)

**Review by bykclk — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Review by yceruto — APPROVED** [review]

**Comment by pluk77** [comment]
Is there some way that the hard-coded type-check `(\in_array($type, ['ulid', 'uuid', 'guid']))` can be removed so that it relies (more)  on the `Type::hasType($type)` check?

Reason for asking is that besides the normal uuid, there are other custom doctrine types that require conversion (like uuid_binary) and current we need to overwrite the whole class and create an extended EntityType in order to add uuid_binary to the hard-coded if statement.
