### PR TITLE
[HttpKernel] fix how configuring log-level and status-code by exception works

### LINKED ISSUE #44433: [HttpKernel] Wrong template is rendered when configuring an exception status code
### Symfony version(s) affected

5.4.0

### Description

@lyrixx added a way to configure the status code of an exception (in #42244). When configuring the status code of an exception, the HTTP status code of the response is set as expected. However, the rendered HTML template does not seem to take the configured status code in account and Symfony will render the template as if the status code was not set.

### How to reproduce

Use the config:
```
framework:
    exceptions:
        Doctrine\ORM\EntityNotFoundException:
            status_code: 404
```

Then throw an `EntityNotFoundException`. The HTTP status code will be 404, but the rendered template (both in the debug exception template and the production template) will show 500 Internal Server Error.

### Possible Solution

Maybe the exceptions Mapping should also be used in the `Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer`?

### Additional Context

The status code of `Symfony\Component\ErrorHandler\Exception\FlattenException::createFromThrowable` is used.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44433
| License       | MIT
| Doc PR        | -

This PR replaces #44456, and essentially fixes the way configuring log-level/status-code by exception works: instead of hacking them in the listener, the original exception should be wrapped in an `HttpExceptionInterface`, so that the rest of the code can seamlessly know about the configuration.

### CODE REVIEW

File: src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php [hunk 1]
```diff
@@ -46,9 +47,19 @@ public function logKernelException(ExceptionEvent $event)
...
+                continue;
+            }
+            if ($config['log_level'] && null === $logLevel) {
                 $logLevel = $config['log_level'];
+            }
+            if ($config['status_code'] && $event->getThrowable() === $throwable) {
+                $throwable = new HttpException($config['status_code'], $throwable->getMessage(), $throwable);
+                $event->setThrowable($throwable);
+            }
+            if (null !== $logLevel && $event->getThrowable() !== $throwable) {
```
Comment (stof) [inline src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php]: The condition `$event->getThrowable() !== $throwable` won't ever catch the case where you override the exception, because line 59 overrides the `$throwable` variable.

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php]: oops, fixed

**Review by lyrixx — APPROVED** [review]

File: src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php [hunk 2]
```diff
@@ -46,13 +47,23 @@ public function logKernelException(ExceptionEvent $event)
...
         foreach ($this->exceptionsMapping as $class => $config) {
-            if ($throwable instanceof $class && $config['log_level']) {
+            if (!$throwable instanceof $class) {
+                continue;
+            }
+            if ($config['log_level'] && null === $logLevel) {
                 $logLevel = $config['log_level'];
+            }
+            if ($config['status_code'] && $event->getThrowable() === $throwable) {
+                $throwable = new HttpException($config['status_code'], $throwable->getMessage(), $throwable);
```
Comment (yceruto) [inline src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php]: I would also pass the headers argument when provided. I mean, if `$throwable` is originally an instance of `HttpExceptionInterface` and a custom header is set then it should be taken into account during the error rendering response, right?

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php]: Maybe we should just skip decorating instances of of HttpExceptionInterface? I don't see the point of reconfiguring those.

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php]: I updated the PR this way. Feedback welcome.

File: src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php [hunk 3]
```diff
@@ -46,13 +47,25 @@ public function logKernelException(ExceptionEvent $event)
     {
         $throwable = $event->getThrowable();
         $logLevel = null;
-        foreach ($this->exceptionsMapping as $class => $config) {
-            if ($throwable instanceof $class && $config['log_level']) {
-                $logLevel = $config['log_level'];
-                break;
+
+        if (!$throwable instanceof HttpExceptionInterface) {
```
Comment (yceruto) [inline src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php]: We could still want a different log-level for known HTTP exceptions, no?

File: src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php (hunk 2 above)
Comment (yceruto) [reply src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php]: I don't think we should exclude any exception, regardless of the headers edge-case, we might want to change the status code of an HTTP exception that we do not control on the app side.

Comment (yceruto) [reply src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php]: In my opinion, the previous code was correct, it was just missing setting the headers when provided.

**Comment by nicolas-grekas** [comment]
Thanks for the feedback @yceruto. PR updated.

**Review by yceruto — APPROVED** [review]
Thanks to you @nicolas-grekas !

**Review by stof — APPROVED** [review]
