### PR TITLE
[HttpKernel] Nullable and default value arguments in RequestPayloadValueResolver

### LINKED ISSUE #50690: [HttpKernel] #[MapQueryString] with an empty query string always returns null
### Symfony version(s) affected

6.3.0

### Description

`RequestPayloadValueResolver` always [returns null](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php#L152-L154) when mapping query strings and query string is empty.

This is problematic when using a DTO where all arguments have default values, e.g.

```php
class MyDto {
    public function __construct(public string $foo = "bar")
    {}
}
```

### How to reproduce

Controller:

```php
class MyDto {
    public function __construct(public string $foo = "bar")
    {}
}

class FooController extends AbstractController
{
    #[Route("/foo", name: "foo", methods: ["GET"])]
    public function getPaginated(
        #[MapQueryString] MyDto $myDto,
    ): JsonResponse
    {
        return $this->json($myDto);
    }
}
```

`GET /foo` -> `404 HttpException`
`GET /foo?foo=baz` -> `200 {"foo": "baz"}`

### Possible Solution

Remove [this](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php#L152-L154) early return and let the serializer decide what to do with an empty query string.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mdeboer**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #50690
| License       | MIT

This PR adds support to RequestPayloadValueResolver for nullable arguments and arguments with a default value set. See https://github.com/symfony/symfony/issues/50690#issuecomment-1601142333

Credits go to @nicolas-grekas for the implentation 👍🏻

### CODE REVIEW

**Review by alamirault — APPROVED** [review]

File: src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php [hunk 1]
```diff
@@ -57,6 +57,154 @@ public function testNotTypedArgument()
         $resolver->onKernelControllerArguments($event);
     }
 
+    public function testDefaultValueArgument()
+    {
+        $payload = new RequestPayload(50);
+
+        $validator = $this->createMock(ValidatorInterface::class);
+        $validator->expects($this->never())
+                  ->method('validate');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php]:
```suggestion
           ->method('validate');
```

File: src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php [hunk 2]
```diff
@@ -57,6 +57,154 @@ public function testNotTypedArgument()
...
+
+        $argument = new ArgumentMetadata('valid', RequestPayload::class, false, true, $payload, false, [
+            MapRequestPayload::class => new MapRequestPayload(),
+        ]);
+        $request = Request::create('/', 'POST', server: ['CONTENT_TYPE' => 'application/json']);
+
+        $kernel = $this->createMock(HttpKernelInterface::class);
+        $arguments = $resolver->resolve($request, $argument);
+        $event = new ControllerArgumentsEvent($kernel, function () {
+        }, $arguments, $request, HttpKernelInterface::MAIN_REQUEST);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php]:
```suggestion
        $event = new ControllerArgumentsEvent($kernel, fn () => null, $arguments, $request, HttpKernelInterface::MAIN_REQUEST);
```

File: src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php [hunk 3]
```diff
@@ -57,6 +57,154 @@ public function testNotTypedArgument()
...
+        $this->assertEquals([$payload], $event->getArguments());
+    }
+
+    public function testQueryDefaultValueArgument()
+    {
+        $payload = new RequestPayload(50);
+
+        $validator = $this->createMock(ValidatorInterface::class);
+        $validator->expects($this->never())
+                  ->method('validate');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php]:
```suggestion
            ->method('validate');
```

File: src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php [hunk 4]
```diff
@@ -57,6 +57,154 @@ public function testNotTypedArgument()
...
+
+        $argument = new ArgumentMetadata('valid', RequestPayload::class, false, true, $payload, false, [
+            MapQueryString::class => new MapQueryString(),
+        ]);
+        $request = Request::create('/', 'GET');
+
+        $kernel = $this->createMock(HttpKernelInterface::class);
+        $arguments = $resolver->resolve($request, $argument);
+        $event = new ControllerArgumentsEvent($kernel, function () {
+        }, $arguments, $request, HttpKernelInterface::MAIN_REQUEST);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php]:
```suggestion
        $event = new ControllerArgumentsEvent($kernel, fn () => null, $arguments, $request, HttpKernelInterface::MAIN_REQUEST);
```

File: src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php [hunk 5]
```diff
@@ -57,6 +57,154 @@ public function testNotTypedArgument()
...
+
+        $resolver->onKernelControllerArguments($event);
+
+        $this->assertEquals([null], $event->getArguments());
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php]:
```suggestion
        $this->assertSame([null], $event->getArguments());
```

File: src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php [hunk 6]
```diff
@@ -57,6 +57,154 @@ public function testNotTypedArgument()
...
+
+        $argument = new ArgumentMetadata('valid', RequestPayload::class, false, false, null, true, [
+            MapQueryString::class => new MapQueryString(),
+        ]);
+        $request = Request::create('/', 'GET');
+
+        $kernel = $this->createMock(HttpKernelInterface::class);
+        $arguments = $resolver->resolve($request, $argument);
+        $event = new ControllerArgumentsEvent($kernel, function () {
+        }, $arguments, $request, HttpKernelInterface::MAIN_REQUEST);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php]:
```suggestion
        $event = new ControllerArgumentsEvent($kernel, fn () => null, $arguments, $request, HttpKernelInterface::MAIN_REQUEST);
```

File: src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php [hunk 7]
```diff
@@ -57,6 +57,154 @@ public function testNotTypedArgument()
...
+        $resolver->onKernelControllerArguments($event);
+
+        $this->assertEquals([null], $event->getArguments());
+    }
+
+    public function testQueryNullableValueArgument()
+    {
+        $validator = $this->createMock(ValidatorInterface::class);
+        $validator->expects($this->never())
+                  ->method('validate');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php]:
```suggestion
            ->method('validate');
```

File: src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php [hunk 8]
```diff
@@ -57,6 +57,154 @@ public function testNotTypedArgument()
...
+
+        $argument = new ArgumentMetadata('valid', RequestPayload::class, false, false, null, false, [
+            MapQueryString::class => new MapQueryString(),
+        ]);
+        $request = Request::create('/', 'GET');
+
+        $kernel = $this->createMock(HttpKernelInterface::class);
+        $arguments = $resolver->resolve($request, $argument);
+        $event = new ControllerArgumentsEvent($kernel, function () {
+        }, $arguments, $request, HttpKernelInterface::MAIN_REQUEST);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php]:
```suggestion
        $event = new ControllerArgumentsEvent($kernel, fn () => null, $arguments, $request, HttpKernelInterface::MAIN_REQUEST);
```

File: src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php [hunk 9]
```diff
@@ -57,6 +57,154 @@ public function testNotTypedArgument()
...
+        } catch (HttpException $e) {
+            $this->assertSame(422, $e->getStatusCode());
+        }
+    }
+
+    public function testQueryNullPayloadAndNotDefaultOrNullableArgument()
+    {
+        $validator = $this->createMock(ValidatorInterface::class);
+        $validator->expects($this->never())
+                  ->method('validate');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php]:
```suggestion
            ->method('validate');
```

File: src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php [hunk 10]
```diff
@@ -57,6 +57,154 @@ public function testNotTypedArgument()
...
+
+        $argument = new ArgumentMetadata('valid', RequestPayload::class, false, false, null, false, [
+            MapRequestPayload::class => new MapRequestPayload(),
+        ]);
+        $request = Request::create('/', 'POST', server: ['CONTENT_TYPE' => 'application/json']);
+
+        $kernel = $this->createMock(HttpKernelInterface::class);
+        $arguments = $resolver->resolve($request, $argument);
+        $event = new ControllerArgumentsEvent($kernel, function () {
+        }, $arguments, $request, HttpKernelInterface::MAIN_REQUEST);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php]:
```suggestion
        $event = new ControllerArgumentsEvent($kernel, fn () => null, $arguments, $request, HttpKernelInterface::MAIN_REQUEST);
```

File: src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php [hunk 11]
```diff
@@ -57,6 +57,154 @@ public function testNotTypedArgument()
...
+        $resolver->onKernelControllerArguments($event);
+
+        $this->assertEquals([null], $event->getArguments());
+    }
+
+    public function testNullPayloadAndNotDefaultOrNullableArgument()
+    {
+        $validator = $this->createMock(ValidatorInterface::class);
+        $validator->expects($this->never())
+                  ->method('validate');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php]:
```suggestion
            ->method('validate');
```

File: src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php [hunk 12]
```diff
@@ -57,6 +57,154 @@ public function testNotTypedArgument()
...
+
+        $argument = new ArgumentMetadata('valid', RequestPayload::class, false, false, null, true, [
+            MapRequestPayload::class => new MapRequestPayload(),
+        ]);
+        $request = Request::create('/', 'POST', server: ['CONTENT_TYPE' => 'application/json']);
+
+        $kernel = $this->createMock(HttpKernelInterface::class);
+        $arguments = $resolver->resolve($request, $argument);
+        $event = new ControllerArgumentsEvent($kernel, function () {
+        }, $arguments, $request, HttpKernelInterface::MAIN_REQUEST);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php]:
```suggestion
        $event = new ControllerArgumentsEvent($kernel, fn () => null, $arguments, $request, HttpKernelInterface::MAIN_REQUEST);
```

File: src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php [hunk 13]
```diff
@@ -57,6 +57,154 @@ public function testNotTypedArgument()
...
+        $resolver->onKernelControllerArguments($event);
+
+        $this->assertEquals([$payload], $event->getArguments());
+    }
+
+    public function testNullableValueArgument()
+    {
+        $validator = $this->createMock(ValidatorInterface::class);
+        $validator->expects($this->never())
+                  ->method('validate');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/Controller/ArgumentResolver/RequestPayloadValueResolverTest.php]:
```suggestion
            ->method('validate');
```

**Review by nicolas-grekas — APPROVED** [review]
Nice, thanks! Here are some CS fixes and GTM!

**Comment by mdeboer** [comment]
Wow, just turned off my pc so figured I'd approve these changes on my phone. But apparently it creates a commit for every change, if you want I can squash them tomorrow 😂

Wasn't sure about the formatting. Not too happy with how it looked but thought that'd be something for a different PR.

Got lots of questions like why the serializer context keys are mentioned in the docblock but not used etc. But yeah, for a new PR I suppose 😅

**Review by maxbeckers — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
> why the serializer context keys are mentioned in the docblock but not used etc

For BC, that's how we deal with adding new arguments without breaking anything until the next major.

**Comment by nicolas-grekas** [comment]
Thank you @mdeboer.
