### PR TITLE
[Form] Add new way of mapping data using callback functions

### LINKED ISSUE #37597: [RFC] [Form] Improve handling of domain objects in forms
# Description

This issue originated as a discussion thread in the Symfony Slack. To preserve the conversation and get more input from maintainers and the community, I'm creating this RFC.

People have been arguing for working with domain transfer objects (DTOs) in the form documentation, as there are a few problem to directly bind the form to a managed object (e.g. a Doctrine entity):
* Data is written to the entity without checking for validity first
* Subsequent validation may flag the form as invalid, but doesn't restore original data
* Subsequently flushing the managed object in the manager (e.g. EntityManager when using Doctrine) may write invalid data to the database and potentially affect unrelated managed objects
* The PropertyAccess only supports accessing properties through accessor methods that are rather hardcoded.
* Using separate methods for write and read operations (e.g. `Category::getName()` and `Category::rename($name)` is not possible

To solve this, users can create a DTO to hold the data and apply it to the managed object after it has been validated. However, this potentially adds a bunch of boilerplate code (e.g. a class with public properties and a `apply` method to apply changed data to the form). In many instances, this can be avoided.

There is a bundle that adds `read_property_path` and `write_property_path` to the form component ([Example](https://github.com/sensiolabs-de/rich-model-forms-bundle/blob/main/docs/mapping.md)). However, @linaori was quick to point out that using strings can cause issues with IDE integration, e.g. by a refactoring not catching the usage in a form as it's not a code reference. @javiereguiluz then suggested the following:

# Example

```php
$builder->add('name', TextType::class, [
    'get' => function (?Category $category): ?string { return $category !== null ? $category->getName() : null; },
    'set' => function (Category $category, $value): void { $category->rename($value); },
]);
```

Note that the getter in this case could be omitted since it replicates the default behaviour.

With short closures, the example gets even more concise:
```php
$builder->add('name', TextType::class, [
    'get' => fn (?Category $category): ?string =>  $category !== null ? $category->getName() : null,
    'set' => fn (Category $category, $value): void => $category->rename($value),
]);
```

This does not solve the problem of validation only being run after modifying the object, but it gives people more freedom when designing the public API for their domain objects, and may avoid the need for a DTO in some instances.

# Future scope

## Exception handling

Exceptions while calling any of the closures will lead to a 500 error. This could be avoided by expanding the closure to catch the exception, but then the question is how this can be communicated to the user. The bundle mentioned above introduces a `expected_exception` form option. If an exception of the given type is thrown, the exception is caught and it is added as a form error. While this may offer more flexibility, I think it introduces yet another form option that people have to understand. An alternative would be to always catch a `ValidationExceptionInterface` interface provided by the form component. The `ValidationException` class would provide a generic exception for people to use. This allows doing the following:

* Users can implement the interface in their domain exceptions:
```php
// Exception class
class NameNotAllowedException extends \RuntimeException implements ValidationExceptionInterface
{
    // ...
}

// Domain object
class Category
{
    public function rename(string $name): void
    {
        if (...) {
            throw NameNotAllowedException::notAllowed($name);
        }

        ...
    }
}
```
* Alternatively, users can handle a specific exception in the closure:
```php
$builder->add('name', TextType::class, [
    'set' => function (Category $category, $value): void {
        try {
            $category->rename($value);
        } catch (DomainException $e) {
            throw ValidationException::fromPrevious($e);
        }
    },
]);
```
* The functionality above could also be provided by a closure:
```php
// DomainValidationHandler.php
public function wrap(string $exceptionClass, Closure $closure): Closure
{
    $code = <<<'CODE'
        return function (object $object, $value): void {
            try {
                $closure($object, $value);
            } catch (%s $e) {
                throw ValidationException::fromPrevious($e);
            }
        };
        CODE;

    return eval(sprintf($code, $exceptionClass));
}

// In form
$builder->add('name', TextType::class, [
    'set' => DomainValidationHandler::wrap(
        DomainException::class,
        fn (Category $category, $value): void => $category->rename($value)
    ),
]);
```

## Change form validation rules

When binding a form, form data is sent through the data transformers, then applied to the object, and last but not least validated by the validation component. This reads constraints from the form as well as from the object and validates all constraints. It may be sensible to change the order when binding:
* Take data from form and run through data transformers. Store transformed data
* Run constraints defined on form fields on model data. Any validation errors are added to the form. If errors are found, binding the form is aborted without changing the object (or creating one if none was passed)
* Apply data to the object. This ensures that any early constraints (e.g. invalid types in the form) can be caught beforehand. Exception handling as described above is optional here.
* Run validation constraints defined on the object. Again, errors are added to the form.

The order above would allow people to keep form-specific validation logic in the form (which would otherwise be put in a DTO) while doing other, potentially more complex validation after data is applied to the object:
```php
$builder->add('name', TextType::class, [
    'set' => DomainValidationHandler::wrap(
        DomainException::class,
        fn (Category $category, $value): void => $category->rename($value)
    ),
    'constraints' => [
        new UniqueEntity([
            'entityClass' => Category::class,
            'fields' => ['name'],
            'id' => // ID of entity being edited will have to be passed from options
    ],
]);
```

# Next steps

For now, I'm looking for feedback from people that have previously created DTOs for their form <-> entity mappings, as well as from users using the bundle mentioned above. I've used the bundle myself, but my last work with Symfony Forms was almost 2 years ago, so I'm a bit outdated when it comes to form. After that, I could offer to build a prototype for the functionality outlined above.

### PR DESCRIPTION
**Pull request by yceruto**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | yes
| Tickets       | Fix #37597 (partially)
| License       | MIT
| Doc PR        | https://github.com/symfony/symfony-docs/pull/14241

Replaces https://github.com/symfony/symfony/pull/37614

## What this solves

Objects and Forms have different mechanisms for structuring data. When you build an object model with a lot of business logic it's valuable to use these mechanisms to better collect the data and the behavior that goes with it. Doing so leads to variant schemas; that is, the object model schema and the form schema don't match up.

You still need to transfer data between the two schemas, and this data transfer becomes a complexity in its own right. If the objects know about the form structure, changes in one tend to ripple to the other.

Currently, the Data Mapper layer separates the objects from the form, transfering data between the two and also isolating them from each other. That's fine, but at present the default data mapper has a limitation: _it's very tied to one property path_ (see [`PropertyPathMapper`](https://github.com/symfony/symfony/blob/5.1/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php)). 

That said, you'll have to write your own data mapper in the following situations:
 * When the property path differs for reading and writing
 * When several form fields are mapped to a single method
 * When you need to read data based on the model's state
 * When the mapping of the model depends on the submitted form data
 * ...

Also, when we create a new data mapper, we usually forget about checking the status of the given data and forms. Whether the data is empty or not; throw an exception if the given data is not an object/array and whether the form field is submitted/synchronized/disabled or not. Not doing that could lead to unwanted behavior.

## What this proposes

Create a new way to write and read values to/from an object/array using callback functions. This feature would be tied to each form field and would also mean a new way of mapping data, but a very convenient one, in which it won't be necessary to define a new data mapper and take into account all what it would imply when you only need to map one field in a different manner or perhaps in only one direction (writing or reading the value).

This PR adds two new options for each form type: `getter` and `setter`, allowed to be `null` or `callable`:
```php
$builder->add('name', TextType::class, [
    'getter' => function (Person $person, FormInterface $form): string {
        return $person->firstName().' '.$person->lastName();
    },
    'setter' => function (Person &$person, ?string $name, FormInterface $form): void {
        $person->rename($name);
    },
]);
```
This would give us the same possibilities as data mappers, but within the form field scope, where:
 * `$person` is the view data, basically the underlying data to the form.
 * `$form` is the current child form that is being mapped.
 * `$name` is the submitted data that belongs to that field.

These two callbacks will be executed following the same rules as for property paths before read and write any value (e.i. early return if empty data, skip mapping if the form field is not mapped or it's disabled, etc).

## What this also proposes

I based the implementation on solving this problem first:

> https://github.com/symfony/symfony/pull/37614#issuecomment-662957865
> [...] the property_path option defines the rules on how it's accessed. From there, the actual way it is accessed (direct property access, accessors, reflection, whatever) are hidden from view. All that matters is the property path (which is deduced from the name if not explicitly set). [...]

Thus, splitting the default data mapper `PropertyPathMapper` into two artifacts: "[DataMapper](https://github.com/yceruto/symfony/blob/data_accessor/src/Symfony/Component/Form/Extension/Core/DataMapper/DataMapper.php)" and "[DataAccessor](https://github.com/yceruto/symfony/blob/data_accessor/src/Symfony/Component/Form/DataAccessorInterface.php)" would allow us to add multiple data accessors without having to constantly reinvent the wheel (the data mapper code). This way, we can focus on varying the code that handles data access.

You can also think about a new `ReflectionAccessor` for instance? or use this `CallbackAccessor` to map your form partially from an external API? yes, you could do it :)

Here is a view of the proposed changes:

data_accessor

DataMapper will take care of common checks, iterating through the given child forms, managing the form data, and all the tasks necessary for mapping a standard form. Meanwhile, DataAccessor will handle how to read and write values to/from the underlying object or array.

## BC

The `PropertyPathMapper` is being deprecated in favor of `DataMapper` class, which uses the `PropertyPathAccessor` by default.

Although `DataMapper` is now the default for each compound form, the behavior must remain the same (tests prove it). Therefore, if the `getter` or `setter` option is null (they are by default), `CallbackAccessor` will fall back to `PropertyPathAccessor` for reading or writing values.

---

Sorry for the long description, but I think it is sometimes necessary for complex issues and big changes. Additionally, now you have a better understanding of what these changes are about.

/cc @xabbuh as creator of [rich-model-forms-bundle](https://github.com/sensiolabs-de/rich-model-forms-bundle) and @alcaeus as you had worked on this issue.

WDYT?

### CODE REVIEW

**Comment by maxhelias** [comment]
I am not very familiar with the Form component but your explanations are very clear and the concept looks very interesting 👏

File: src/Symfony/Component/Form/Extension/Core/DataAccessor/PropertyPathAccessor.php [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+    /**
+     * {@inheritdoc}
+     */
+    public function getValue($data, FormInterface $form)
+    {
+        if (null !== $propertyPath = $form->getPropertyPath()) {
+            return $this->getPropertyValue($data, $propertyPath);
+        }
+
+        return $this->fallbackAccessor->getValue($data, $form);
```
Comment (alcaeus) [inline src/Symfony/Component/Form/Extension/Core/DataAccessor/PropertyPathAccessor.php:47]: (Does not apply if we remove fallback accessors completely).
Since it's possible to create an instance without a fallbackAccessor present, this line will produce a fatal error.

File: src/Symfony/Component/Form/Extension/Core/DataMapper/DataMapper.php [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+/**
+ * Maps arrays/objects to/from forms using data accessors.
+ *
+ * @author Bernhard Schussek <bschussek@gmail.com>
+ */
+class DataMapper implements DataMapperInterface
+{
+    private $dataAccessor;
+
+    public function __construct(DataAccessorInterface $dataAccessor = null)
```
Comment (alcaeus) [inline src/Symfony/Component/Form/Extension/Core/DataMapper/DataMapper.php:29]:
```suggestion
    public function __construct(?DataAccessorInterface $dataAccessor = null)
```

**Review by alcaeus — COMMENTED** [review]
I really like how you solved the problem. Splitting data mapping and data accessors makes this more maintainable.

I've left a couple of comments regarding fallback accessors. I'm not sure if we should be nesting data accessors as you've suggested in this PR; I think using some form of chain accessors that iterates over a list of accessors may be better, but I defer to the judgment of the core devs.

File: src/Symfony/Component/Form/Extension/Core/DataAccessor/CallbackAccessor.php [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+/**
+ * Writes and reads values to/from an object or array using callback functions.
+ *
+ * @author Yonel Ceruto <yonelceruto@gmail.com>
+ */
+class CallbackAccessor implements DataAccessorInterface
+{
+    private $fallbackAccessor;
+
+    public function __construct(DataAccessorInterface $fallbackAccessor)
```
[the remark this answers is not in the document]
Comment (yceruto) [reply src/Symfony/Component/Form/Extension/Core/DataAccessor/CallbackAccessor.php]: Yeah, that pattern should be better, thanks!

[the remark this answers is not in the document]
Comment (yceruto) [reply src/Symfony/Component/Form/Extension/Core/DataAccessor/CallbackAccessor.php]: Done.

File: src/Symfony/Component/Form/Extension/Core/DataAccessor/PropertyPathAccessor.php [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+ *
+ * @author Yonel Ceruto <yonelceruto@gmail.com>
+ * @author Bernhard Schussek <bschussek@gmail.com>
+ */
+class PropertyPathAccessor implements DataAccessorInterface
+{
+    private $propertyAccessor;
+    private $fallbackAccessor;
+
+    public function __construct(PropertyAccessorInterface $propertyAccessor = null, DataAccessorInterface $fallbackAccessor = null)
```
[the remark this answers is not in the document]
Comment (yceruto) [reply src/Symfony/Component/Form/Extension/Core/DataAccessor/PropertyPathAccessor.php]: Done.

File: src/Symfony/Component/Form/Extension/Core/DataAccessor/PropertyPathAccessor.php (hunk 1 above)
Comment (yceruto) [reply src/Symfony/Component/Form/Extension/Core/DataAccessor/PropertyPathAccessor.php]: NVM, moved to Chain pattern.

File: src/Symfony/Component/Form/Extension/Core/DataAccessor/PropertyPathAccessor.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (yceruto) [reply src/Symfony/Component/Form/Extension/Core/DataAccessor/PropertyPathAccessor.php]: I recall some discussion about it, but I don't remember the reason why we don't do it in core, maybe it's related to the fact that `= null` denotes nullability too.

File: src/Symfony/Component/Form/Extension/Core/DataMapper/DataMapper.php (hunk 2 above)
Comment (yceruto) [reply src/Symfony/Component/Form/Extension/Core/DataMapper/DataMapper.php:30]: same as https://github.com/symfony/symfony/pull/37968#discussion_r482230653

File: src/Symfony/Component/Form/Extension/Core/DataAccessor/PropertyPathAccessor.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (alcaeus) [reply src/Symfony/Component/Form/Extension/Core/DataAccessor/PropertyPathAccessor.php]: It does, but it's to support legacy behaviour from when PHP didn't have nullable types yet. Consider the following snippet: https://3v4l.org/Wo6iC. You can see that even though they look compatible, the two method signatures are no longer compatible. To make this more explicit, `?string` should be used in that case.

With all that said, if it's policy in core to not use nullable types in such instances, then this is the wrong place to argue this and should be left alone.

File: src/Symfony/Component/Form/Extension/Core/DataAccessor/CallbackAccessor.php [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+    /**
+     * {@inheritdoc}
+     */
+    public function getValue($data, FormInterface $form)
+    {
+        if (null !== $getter = $form->getConfig()->getOption('get')) {
+            return ($getter)($data, $form);
+        }
+
+        throw new RuntimeException('Unable to read the given form data.');
```
Comment (alcaeus) [inline src/Symfony/Component/Form/Extension/Core/DataAccessor/CallbackAccessor.php:34]: Maybe we could introduce a new `AccessException` to make this a little more specific? Not sure what the policy is on specific exception classes.

Comment (yceruto) [reply src/Symfony/Component/Form/Extension/Core/DataAccessor/CallbackAccessor.php:34]: Good idea! I will create the new exception class and update the interface. Thanks!

File: src/Symfony/Component/Form/Extension/Core/DataAccessor/PropertyPathAccessor.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (yceruto) [reply src/Symfony/Component/Form/Extension/Core/DataAccessor/PropertyPathAccessor.php]: Yes, I agree with that, but in this case the default value cannot be other than `null`, right?

**Review by alcaeus — APPROVED** [review]
LGTM

File: src/Symfony/Component/Form/Extension/Core/Type/FormType.php [hunk 6]
```diff
@@ -202,6 +208,8 @@ public function configureOptions(OptionsResolver $resolver)
             'invalid_message' => 'This value is not valid.',
             'invalid_message_parameters' => [],
             'is_empty_callback' => null,
+            'get' => null,
+            'set' => null,
```
Comment (fabpot) [inline src/Symfony/Component/Form/Extension/Core/Type/FormType.php:212]: Wouldn't it be "better" to call them "getter" and "setter"?

**Review by fabpot — APPROVED** [review]
Looks great to me! I'd love to get some feedback from @xabbuh and @weaverryan if possible.

File: src/Symfony/Component/Form/Extension/Core/Type/FormType.php (hunk 6 above)
Comment (yceruto) [reply src/Symfony/Component/Form/Extension/Core/Type/FormType.php:212]: Works for me too. 

Indeed, it also matches the variables in the `CallbackAccessor`. I will make the changes soon, thanks!

Comment (yceruto) [reply src/Symfony/Component/Form/Extension/Core/Type/FormType.php]: Done.

File: src/Symfony/Component/Form/DataAccessorInterface.php [hunk 7]
```diff
@@ -0,0 +1,69 @@
...
+    /**
+     * Sets the value at the end of the property of the object graph.
+     *
+     * @param object|array  $objectOrArray The object or array to modify
+     * @param mixed         $value         The value to set at the end of the object graph
+     * @param FormInterface $form          The {@link FormInterface()} instance to check
+     *
+     * @throws Exception\AccessException If unable to write the given value
+     */
+    public function setValue(&$objectOrArray, $value, FormInterface $form): void;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/DataAccessorInterface.php:42]: can't the method return the modified value instead of using a ref?

File: src/Symfony/Component/Form/Extension/Core/DataAccessor/CallbackAccessor.php [hunk 8]
```diff
@@ -0,0 +1,64 @@
...
+ */
+class CallbackAccessor implements DataAccessorInterface
+{
+    /**
+     * {@inheritdoc}
+     */
+    public function getValue($data, FormInterface $form)
+    {
+        if (null === $getter = $form->getConfig()->getOption('getter')) {
+            throw new AccessException('Unable to read from the given form data.');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Extension/Core/DataAccessor/CallbackAccessor.php:31]: "as no getter is defined"?

File: src/Symfony/Component/Form/Extension/Core/DataAccessor/CallbackAccessor.php [hunk 9]
```diff
@@ -0,0 +1,64 @@
...
+        return ($getter)($data, $form);
+    }
+
+    /**
+     * {@inheritdoc}
+     */
+    public function setValue(&$data, $value, FormInterface $form): void
+    {
+        if (null === $setter = $form->getConfig()->getOption('setter')) {
+            throw new AccessException('Unable to write the given value.');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Extension/Core/DataAccessor/CallbackAccessor.php:43]: "as no setter is defined"?

File: src/Symfony/Component/Form/Extension/Core/DataAccessor/ChainAccessor.php [hunk 10]
```diff
@@ -0,0 +1,90 @@
...
+     */
+    public function getValue($data, FormInterface $form)
+    {
+        foreach ($this->accessors as $accessor) {
+            if ($accessor->isReadable($data, $form)) {
+                return $accessor->getValue($data, $form);
+            }
+        }
+
+        throw new AccessException('Unable to read from the given form data.');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Extension/Core/DataAccessor/ChainAccessor.php:44]: "as no accessor in the chain is able to read the data"?

File: src/Symfony/Component/Form/Extension/Core/DataAccessor/ChainAccessor.php [hunk 11]
```diff
@@ -0,0 +1,90 @@
...
+    {
+        foreach ($this->accessors as $accessor) {
+            if ($accessor->isWritable($data, $form)) {
+                $accessor->setValue($data, $value, $form);
+
+                return;
+            }
+        }
+
+        throw new AccessException('Unable to write the given value.');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Extension/Core/DataAccessor/ChainAccessor.php:60]: "as no accessor in the chain is able to set the data"?

File: src/Symfony/Component/Form/Extension/Core/DataAccessor/PropertyPathAccessor.php [hunk 12]
```diff
@@ -0,0 +1,102 @@
...
+        $this->propertyAccessor = $propertyAccessor ?? PropertyAccess::createPropertyAccessor();
+    }
+
+    /**
+     * {@inheritdoc}
+     */
+    public function getValue($data, FormInterface $form)
+    {
+        if (null === $propertyPath = $form->getPropertyPath()) {
+            throw new AccessException('Unable to read from the given form data.');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Extension/Core/DataAccessor/PropertyPathAccessor.php:43]: as ...

File: src/Symfony/Component/Form/Extension/Core/DataAccessor/PropertyPathAccessor.php [hunk 13]
```diff
@@ -0,0 +1,102 @@
...
+        return $this->getPropertyValue($data, $propertyPath);
+    }
+
+    /**
+     * {@inheritdoc}
+     */
+    public function setValue(&$data, $propertyValue, FormInterface $form): void
+    {
+        if (null === $propertyPath = $form->getPropertyPath()) {
+            throw new AccessException('Unable to write the given value.');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Extension/Core/DataAccessor/PropertyPathAccessor.php:55]: as ...

File: UPGRADE-5.2.md [hunk 14]
```diff
@@ -16,6 +16,28 @@ FrameworkBundle
...
+ $builder->setDataMapper(new PropertyPathMapper());
+ ```
+
+ After:
+
+ ```php
+ use Symfony\Component\Form\Extension\Core\DataAccessor\PropertyPathAccessor;
+ use Symfony\Component\Form\Extension\Core\DataMapper\DataMapper;
+
+ $builder->setDataMapper(new DataMapper(new PropertyPathAccessor()));
```
Comment (nicolas-grekas) [inline UPGRADE-5.2.md:38]: could be just `$builder->setDataMapper(new DataMapper());`, isn't it? since the default is to use a `PropertyPathAccessor` when no argumetn is provided

File: src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php [hunk 15]
```diff
@@ -18,10 +18,14 @@
 use Symfony\Component\PropertyAccess\PropertyAccess;
 use Symfony\Component\PropertyAccess\PropertyAccessorInterface;
 
+trigger_deprecation('symfony/form', '5.2', 'The "%s" class is deprecated.', PropertyPathMapper::class);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php:21]: we should tell about the alternative in the message and in the annotation:
use `DataMatter` instead

File: src/Symfony/Component/Form/DataAccessorInterface.php (hunk 7 above)
Comment (yceruto) [reply src/Symfony/Component/Form/DataAccessorInterface.php:42]: Yes, it can. But it is not mandatory to return a new value here and I would like to keep this signature quite similar to the current `DataMapperInterface::mapFormsToData()` method for consistency.

File: UPGRADE-5.2.md (hunk 14 above)
Comment (yceruto) [reply UPGRADE-5.2.md:38]: You're right, technically it is not necessary, but visually it is consistent with the depreciation message and self-explanatory, otherwise we would have to explain it.

File: src/Symfony/Component/Form/Extension/Core/DataAccessor/CallbackAccessor.php (hunk 8 above)
Comment (yceruto) [reply src/Symfony/Component/Form/Extension/Core/DataAccessor/CallbackAccessor.php]: added, thanks!

File: src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php (hunk 15 above)
Comment (yceruto) [reply src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php]: done, thanks!

File: src/Symfony/Component/Form/DataAccessorInterface.php [hunk 16]
```diff
@@ -0,0 +1,69 @@
...
+    /**
+     * Sets the value at the end of the property of the object graph.
+     *
+     * @param object|array  $viewData The view data of the compound form
+     * @param mixed         $value    The value to set at the end of the object graph
+     * @param FormInterface $form     The {@link FormInterface()} instance to check
+     *
+     * @throws Exception\AccessException If unable to write the given value
+     */
+    public function setValue(&$viewData, $value, FormInterface $form): void;
```
Comment (xabbuh) [inline src/Symfony/Component/Form/DataAccessorInterface.php:42]: Is it really necessary to pass the view data by reference?

**Review by xabbuh — APPROVED** [review]
Great work! 🎉 Apart from a minor comment this looks ready to me.

File: src/Symfony/Component/Form/DataAccessorInterface.php (hunk 16 above)
Comment (fabpot) [reply src/Symfony/Component/Form/DataAccessorInterface.php:42]: Nicolas asked the same question already and Yonel answered: Yes, it can. But it is not mandatory to return a new value here and I would like to keep this signature quite similar to the current DataMapperInterface::mapFormsToData(iterable $forms, &$viewData) method for consistency.

I think I agree with him.

Comment (xabbuh) [reply src/Symfony/Component/Form/DataAccessorInterface.php:42]: Fair enough, let's keep it as is then.

**Comment by fabpot** [comment]
Thank you @yceruto.

**Comment by zmitic** [comment]
Question about setter:

```php
($setter)($data, $form->getData(), $form);
```

If the settter is 

```php
'setter' => fn(Person &$person, ?string $name) => $person->rename($name),
```

but ``rename(string $newName)`` doesn't accept null, this would throw TypeError. Is this correct or I simply can't find how it is solved?

**Comment by curry684** [comment]
@yceruto thanks for the very useful feature, but you might want to take a look at #48167
