### PR TITLE
[DependencyInjection] Reset env vars with `kernel.reset`

### LINKED ISSUE #59128: [DependencyInjection] env vars are not reset upon kernel.reset
### Symfony version(s) affected

7.1.0

### Description

#54666 was supposed to reset env vars upon kernel.reset but seems it doesn't work as intended, it probably works for web environments with booted kernels like php-pm or frankenphp worker mode as container is reset for them on each kernel boot but not for messenger workers. Currently there are two issues with it.

1. EnvVarProcessor is not tagged with kernel.reset
2. Env vars are cached higher up in stack in Container (service_container) and they are never reset.

See https://github.com/symfony/symfony/pull/54666#issuecomment-2483122814
            

### How to reproduce

Reproducer isn't needed, the description is enough to explain the issue. 

### Possible Solution

First issue can be fixed by adding  `->tag('kernel.reset', ['method' => 'reset'])` [here](https://github.com/symfony/symfony/blob/75da5aaa8254fb9b09cdaaea996d922bd0b89874/src/Symfony/Bundle/FrameworkBundle/Resources/config/services.php#L193)

Second issue, I'm not sure, ~~maybe we should get rid of services resetter altogether and just reboot kernel~~ (edit: bad idea as pointed out by @stof in following comment). Alternatively, add `service_container` to services_resetter but just reset envCache (and not other services). It would require another public method other than reset in container class and tagging it with `kernel.reset` and use that method as "resetMethod". Instead of tagging service_container with kernel.reset, we could simply call that public method from `EnvVarProcessor::reset()`

### Additional Context

Resetting env vars is necessary to be able to run symfony messenger workers for a multi tenant application (single web server multiple databases) where each message is identified with a tenant stamp and depending upon the tenant id, its env var needs are loaded like database_url, filesystem path etc. Also it is similar to web model that way, each message is handled without causing side effects (in isolation).

### PR DESCRIPTION
**Pull request by faizanakram99**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59128
| License       | MIT

As mentioned in #59128 and https://github.com/symfony/symfony/pull/54666#issuecomment-2479860954 (and proceeding comments), EnvVarProcessor isn't tagged with kernel.reset, hence its reset method is never called in ServicesResetter.

Another issue was that env vars are cached high up in stack (in Container class) and even if EnvVarProcessor's cached env vars are cleared, env var loaders still won't be called as env var loaders are called only for missing env keys.

This PR fixes #59128 by adding the missing tag and also clears "env cache" of Container in `EnvVarProcessor::reset()` method (i.e. whenever env vars of EnvVarProcessor are cleared). This is a safe change and won't break existing apps using symfony messenger.

cc @bendavies

### CODE REVIEW

**Comment by faizanakram99** [comment]
@fabpot errors are unrelated.

**Comment by faizanakram99** [comment]
Test failures seem unrelated too

**Comment by faizanakram99** [comment]
@OskarStark this PR is still missing DependencyInjection label

**Comment by faizanakram99** [comment]
@nicolas-grekas Sorry for the ping, could you please have a look at this PR since you merged the original PR too. Thank you.

File: src/Symfony/Component/DependencyInjection/Container.php [hunk 1]
```diff
@@ -290,6 +290,14 @@ public function reset(): void
         $this->envCache = $this->services = $this->factories = $this->privates = [];
     }
 
+    /**
+     * @internal
+     */
+    public function resetEnvCache(): void
+    {
+        $this->envCache = [];
```
Comment (GromNaN) [inline src/Symfony/Component/DependencyInjection/Container.php:298]: I don't know exactly, but it looks like it could be reset in `Container::reset()`, so we can avoid adding this method.

Comment (faizanakram99) [reply src/Symfony/Component/DependencyInjection/Container.php:298]: It is already reset in `Container::reset()`, however `service_container` isn't part of ServicesResetter (and never called in messenger workers)

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
~Can you please rebase? This should help get tests green.~ I did it.

**Review by mtarld — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @faizanakram99.

**Comment by nicolas-grekas** [comment]
See #63988
