### PR TITLE
[Serializer] Make document type nodes ignorable

### LINKED ISSUE #44363: [Serializer] Make document type nodes ignorable when decoding XML
### Symfony version(s) affected

4.4, 5.3, 5.4, 6.0

### Description

When decoding XML using the `XmlEncoder`, ignoring the document type node with the `decoder_ignored_node_types` option is not possible.

### How to reproduce

Using the `XmlEncoder` with the document type node included in the ignore nodes

```php
$xmlEncoder = new XmlEncoder();
$xml = '<?xml version="1.0"?><!DOCTYPE foobar SYSTEM "http://foo.bar"><foo>bar</foo>';
$xmlEncoder->decode($xml, 'xml', [XmlEncoder::DECODER_IGNORED_NODE_TYPES => [XML_DOCUMENT_TYPE_NODE]])
```

throws a `NotEncodableValueException` because `Document types are not allowed`. 

### Possible Solution

Consider the ignored node types before checking the current node in the `decode` function:

```php
$rootNode = null;
$decoderIgnoredNodeTypes = $context[self::DECODER_IGNORED_NODE_TYPES] ?? $this->defaultContext[self::DECODER_IGNORED_NODE_TYPES];
foreach ($dom->childNodes as $child) {
    if (\in_array($child->nodeType, $decoderIgnoredNodeTypes, true)) {
        continue;
    }
    if (\XML_DOCUMENT_TYPE_NODE === $child->nodeType) {
        throw new NotEncodableValueException('Document types are not allowed.');
    }
    if (!$rootNode) {
        $rootNode = $child;
    }
}
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by boenner**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44363 
| License       | MIT
| Doc PR        | -

As described in #44363: while looping over all nodes, the current node is checked against the list of ignored node types before throwing the `NotEncodableValueException` if it's a document type node.

### CODE REVIEW

**Comment by glauberm** [comment]
Any news on this?

File: src/Symfony/Component/Serializer/Encoder/XmlEncoder.php [hunk 1]
```diff
@@ -477,7 +480,7 @@ private function buildXml(\DOMNode $parentNode, $data, string $xmlRootNodeName =
             return $this->appendNode($parentNode, $data, 'data');
         }
 
-        throw new NotEncodableValueException('An unexpected value could not be serialized: '.(!\is_resource($data) ? var_export($data, true) : sprintf('%s resource', get_resource_type($data))));
+        throw new NotEncodableValueException('An unexpected value could not be serialized: '.(!\is_resource($data) ? var_export($data, true) : sprintf('"%s" resource', get_resource_type($data))));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Encoder/XmlEncoder.php]: let's revert this as it's unrelated, fabbot is not always right

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @boenner.
