### PR TITLE
[Notifier] Check Discord embed limitations

### LINKED ISSUE #47688: [Notifier] [Discord] 400 HTTP response due to embed length
### Symfony version(s) affected

6.1.4

### Description

Currently the Discord chatter only checks length of message based on the [subject length](https://github.com/symfony/discord-notifier/blob/0410309979e9fa2bcdd711c9a67acfc9d70c06ab/DiscordTransport.php#L70). This not completely correct, as it is valid to provide an empty string as subject and instead use embeds.

Currently if one would use embeds, and does not take into consideration the (vague) limits of Discords message lengths, you will get a 400 status code, with very unclear exception:

```
Handling "Symfony\Component\Notifier\Message\ChatMessage" failed: Unable to post the Discord message: "" (embeds: 0).
```

### How to reproduce

Example error transport.

```php
/**
 * @param string $transport
 * @param DiscordFieldEmbedObject $discordFieldEmbedObject
 * @param Exception|null $exception
 * @return void
 * @throws TransportExceptionInterface
 */
protected function errorTransport(string $transport, DiscordFieldEmbedObject $discordFieldEmbedObject, ?Exception $exception = null): void
{
    $chatMessage = new ChatMessage('');
    $discordOptions = (new DiscordOptions())
        ->addEmbed(
            (new DiscordEmbed())
                ->color(hexdec('f44336'))
                ->title(sprintf('Transport error on `%s`', $transport))
                ->addField(
                    $discordFieldEmbedObject
                        ->name(ucfirst('error'))
                )
                ->addField(
                    (new DiscordFieldEmbedObject())
                        ->name('Exception')
                        ->value(
                            $exception !== null ? $exception->getMessage() : 'No error message available.'
                        )
                )
                ->addField(
                    (new DiscordFieldEmbedObject())
                        ->name('Trace')
                        ->value(
                            $exception !== null ? $exception->getTraceAsString() : 'No trace available.'
                        )
                )
                ->timestamp(new DateTime())
        );


    $chatMessage->options($discordOptions)->transport(self::EXCEPTION_TRANSPORT);
    $this->chatter->send($chatMessage);
}
```

Where `$exception->getMessage()` has well over 1024 characters.

### Possible Solution

1. This [documentation](https://www.pythondiscord.com/pages/guides/python-guides/discord-embed-limits/) shows the limits for the embed fields:

* Embed title is limited to 256 characters
* Embed description is limited to 4096 characters
* An embed can contain a maximum of 25 fields
* A field name/title is limited to 256 character and the value of the field is limited to 1024 characters
* Embed footer is limited to 2048 characters
* Embed author name is limited to 256 characters
* The total of characters allowed in an embed is 6000

Validation for character length on embeds should be added. An exception should be thrown if a specific field of the embed is too long.

2. There also should be an option or flag to cut-off the text to `X` characters instead of throwing an exception. This makes sure that the message is always delivered.
3. Update the documentation for [symfony/discord-notifier](https://github.com/symfony/discord-notifier), clearly stating the character limits.

### Additional Context

A current workaround for me at the moment is adding a truncate method and use that on every field value.

```php
private function truncate(string $text, int $cutoff = 1024)
{
    return mb_strimwidth($text, 0, $cutoff, "...");
}
```

### PR DESCRIPTION
**Pull request by alamirault**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no 
| Tickets       | Fix #47688 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Add missing check on Discord Embeds (length and number).

See #47688 for description

Official embed limits: https://discord.com/developers/docs/resources/channel#embed-object-embed-limits

(unrelated phpunit failure)

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@alamirault thanks for this contribution.

I said the following before and folks didn't think it was an issue, but let me tell you again in case we can reconsider this:

(1) I think it's a mistake to add Discord (or any other third-party) validation logic in Symfony code. The reason is that Discord can change these rules at any time, making Symfony code outdated. (e.g. in this PR we validate that `25` is the max number of fields passed ... what if tomorrow or next week Discord increases or decreases that number?)

(2) We should fix/report obvious errors (e.g. you pass a string where a boolean is required) but we should not try to over-validate things. For example, if today's Discord field limit is `25` and developer sends `50` fields, let Discord fail and pass the API error message to the developer.

File: src/Symfony/Component/Notifier/Bridge/Discord/Embeds/DiscordEmbed.php [hunk 1]
```diff
@@ -111,6 +125,10 @@ public function author(DiscordAuthorEmbedObject $author): static
      */
     public function addField(DiscordFieldEmbedObject $field): static
     {
+        if (self::FIELDS_LIMIT === \count($this->options['fields'] ?? [])) {
+            throw new LengthException(sprintf('Maximum number of fields should not exceed %d.', self::FIELDS_LIMIT));
```
Comment (OskarStark) [inline src/Symfony/Component/Notifier/Bridge/Discord/Embeds/DiscordEmbed.php:129]:
```suggestion
            throw new LengthException(sprintf('Maximum number of fields must not exceed %d.', self::FIELDS_LIMIT));
```

**Review by OskarStark — APPROVED** [review]

**Comment by fabpot** [comment]
I agree with @javiereguiluz and I think we should instead make the error message better if possible (the current one is indeed not helpful: `Handling "Unable to post the Discord message: "" (embeds: 0).`. Notice the empty error message from the server, that's probably a bug in how we parse the response from Discord.

**Comment by alamirault** [comment]
@javiereguiluz I understand, it's logic !

However, what do you think about adding a warning that checks are not all covered by  Symfony on component's README ? And add link to official API docs ?

**Comment by fabpot** [comment]
I don't think there is a need for additional docs or links; the error messages coming from the API should be enough.

**Comment by fabpot** [comment]
Thank you @alamirault.

**Comment by ToshY** [comment]
I'm glad the issue got resolved one way or another, thanks @alamirault 👍

However, I'm still saddened that there's no useful documentation regarding these notifiers besides the [generic documentation](https://symfony.com/doc/current/notifier.html). I reckon adding just 1 complete example for each notifier in its own repo would already be a huge improvement, especially for those who have no idea how to customise the chat messages.

**Comment by OskarStark** [comment]
I would appreciate a sub-section per notifier with some in-depth examples 👍
