### PR TITLE
[Lock] Prevent store exception break combined store

### LINKED ISSUE #39470: [Lock] CombinedStore do not handle store exceptions on exists call
**Symfony version(s) affected**: 5.2.0

**Description**  
CombinedStore do not handle store exceptions on exists method call.

**How to reproduce**  
```
$lockFactory = new \Symfony\Component\Lock\LockFactory(
    new \Symfony\Component\Lock\Store\CombinedStore([
        new \Symfony\Component\Lock\Store\RedisStore(
            new \Predis\Client(['host' => 'unexisting-or-unreachable-localhost'])
        ),
        new \Symfony\Component\Lock\Store\InMemoryStore(),
        new \Symfony\Component\Lock\Store\FlockStore(),
    ],
        new \Symfony\Component\Lock\Strategy\ConsensusStrategy()
    ));


$key = uniqid(true);

$lock = $lockFactory->createLock($key, 30, false);
$lock->acquire();

$lock->release();
```

**Possible Solution**  

**Additional context**

### PR DESCRIPTION
**Pull request by dzubchik**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? |no 
| Tickets       | Fix #39470 
| License       | MIT

Handle exception to preserve expected behavior - one or multiple stores could be unreachable in a moment and combined store will handle this according to strategy.

### CODE REVIEW

File: src/Symfony/Component/Lock/Tests/Store/CombinedStoreTest.php [hunk 1]
```diff
@@ -351,4 +351,29 @@ public function testDeleteDontStopOnFailure()
...
+            ->expects($this->once())
+            ->method('exists')
+            ->willThrowException(new \Exception());
+        $this->store2
+            ->expects($this->once())
+            ->method('exists')
+            ->with($key)
+            ->willReturn(false);
+
+        $this->store->exists($key);
```
Comment (jderusse) [inline src/Symfony/Component/Lock/Tests/Store/CombinedStoreTest.php]: `$this->assertFalse($this->store->exists($key));`

**Review by jderusse — APPROVED** [review]
small nitpicking

**Review by jderusse — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @dzubchik.
