### PR TITLE
[VarDumper] Fix blank strings display

### LINKED ISSUE #57980: [VarDumper] Strings consisting of just spaces are trimmed
### Symfony version(s) affected

6.4

### Description

`VarDumper::dump(' ');` shows an empty string with nothing in it.

``VarDumper::dump('       ');`` also shows as an empty string.

I experienced this trying to debug a larger object, where one of the values was a string with a single space in it. But the method showed it as an empty string, thus confusing my debugging.

### How to reproduce

Run the following:

```php
<?php
use Symfony\Component\VarDumper\VarDumper;
VarDumper::dump(' ');
```

This should show up as an empty string.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #57980
| License       | MIT

Because `sf-dump-ellipsis` `span`s needed a `text-ellipsis`, their overflowing content was cut using `overflow: hidden`. As it required their inner display type to be `block`, this broke the alignment with the ellipsis’ “tail”. This was fixed by #53147 by making every dump’s `span`s `inline-flex`.

This change made `sf-dump-ellipsis`’ `display`, `max-width` and `vertical-align` properties useless so this PR removes them, as well as a duplicated `overflow` one.

Now, `inline-flex` elements’ content becomes flex items, which caused #57980 because 

> if the entire sequence of [a flex item’s] text runs contains only white space […] it is […] not rendered
>
> https://www.w3.org/TR/css-flexbox-1/#flex-items

Instead of making every dump’s `span`s `inline-flex`, this PR targets a new `sf-dump-ellipsization` class added to `sf-dump-ellipsis`’ parents.

It also wraps ellipsis tails with elements bearing the `sf-dump-ellipsis-tail` class so that we can prevent them to shrink:

**Before**:

**After**:

### CODE REVIEW

File: src/Symfony/Bridge/Twig/Tests/Extension/DumpExtensionTest.php [hunk 1]
```diff
@@ -96,14 +96,14 @@ public static function getDumpArgs()
             [
                 [],
                 [123, 456],
-                "<pre class=sf-dump id=sf-dump data-indent-pad=\"  \"><span class=sf-dump-num>123</span>\n</pre><script>Sfdump(\"sf-dump\")</script>\n"
-                ."<pre class=sf-dump id=sf-dump data-indent-pad=\"  \"><span class=sf-dump-num>456</span>\n</pre><script>Sfdump(\"sf-dump\")</script>\n",
+                "<pre class=sf-dump id=sf-dump data-indent-pad=\"  \"><span class=\"sf-dump-num\">123</span>\n</pre><script>Sfdump(\"sf-dump\")</script>\n"
+                ."<pre class=sf-dump id=sf-dump data-indent-pad=\"  \"><span class=\"sf-dump-num\">456</span>\n</pre><script>Sfdump(\"sf-dump\")</script>\n",
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Twig/Tests/Extension/DumpExtensionTest.php]: this change breaks low-deps
better preserve the previous output when possible to not have to change version constraints
doable?

File: src/Symfony/Component/HttpKernel/composer.json [hunk 2]
```diff
@@ -44,7 +44,7 @@
         "symfony/translation-contracts": "^2.5|^3",
         "symfony/uid": "^5.4|^6.0|^7.0",
         "symfony/validator": "^6.4|^7.0",
-        "symfony/var-dumper": "^5.4|^6.4|^7.0",
+        "symfony/var-dumper": "^6.4|^7.0",
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/composer.json]: this should be ^6.4.18 I guess, but can't we do without?

Comment (MatTheCat) [reply src/Symfony/Component/HttpKernel/composer.json]: I’m not sure :thinking: this is only needed for tests to pass.

File: src/Symfony/Bridge/Twig/Tests/Extension/DumpExtensionTest.php (hunk 1 above)
Comment (MatTheCat) [reply src/Symfony/Bridge/Twig/Tests/Extension/DumpExtensionTest.php]: I think I could quote the `class` attribute only if there are two indeed (would feel weird though :sweat_smile:)

Comment (nicolas-grekas) [reply src/Symfony/Bridge/Twig/Tests/Extension/DumpExtensionTest.php]: that'd help fix tests (they're still red :) )

Comment (MatTheCat) [reply src/Symfony/Bridge/Twig/Tests/Extension/DumpExtensionTest.php]: Wouldn’t high and low-deps tests eventually pass when the code is released?

Anyways, I limited the changes to ellipsization so that other components’ tests are not impacted :green_circle:

**Comment by nicolas-grekas** [comment]
Thank you @MatTheCat.
