### PR TITLE
[WebLink] fix types on Link::withAttribute()

### LINKED ISSUE #40126: Inconsistent docblock in web-link / Link.php
**Symfony version(s) affected**: 4.4.* | 5.*

**Description**  
Link.php implements EvolvableLinkInterface and override withAttribute(string $attribute, string $value) by withAttribute($attribute, $value), $value can by mixed now, but in docblock still string.
Child can extend parent param types and all work ok, but phpstan report error when I use withAttribute('crossorigin', true).

[HttpHeaderSerializer](https://github.com/symfony/web-link/blob/5.x/HttpHeaderSerializer.php#L40) support not only string.
[twig-bridge](https://github.com/symfony/twig-bridge/blob/5.x/Extension/WebLinkExtension.php#L53) docblock contain info about supporting true and real values.

We need update docblock to actual.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40126
| License       | MIT
| Doc PR        | -

Related to https://github.com/php-fig/link-util/commit/10e52348a2e9ad4581f2bf3e16458f0861a88c6a

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Review by dunglas — APPROVED** [review]

File: src/Symfony/Component/WebLink/Link.php [hunk 1]
```diff
@@ -132,6 +132,8 @@ public function withoutRel($rel)
     /**
      * {@inheritdoc}
      *
+     * @param $value string|bool|string[]
```
Comment (norkunas) [inline src/Symfony/Component/WebLink/Link.php]:
```suggestion
     * @param string|bool|string[] $value
```
?

Comment (nicolas-grekas) [reply src/Symfony/Component/WebLink/Link.php]: indeed, thanks!

File: src/Symfony/Component/WebLink/Link.php [hunk 2]
```diff
@@ -46,7 +46,7 @@ class Link implements EvolvableLinkInterface
     private $rel = [];
 
     /**
-     * @var string[]
+     * @var array<string, string|bool|string[]>
```
Comment (derrabus) [inline src/Symfony/Component/WebLink/Link.php:49]: Note: On 6.0, this change collided with #41507. I've picked the version from this PR, to make the type consistent across the branches.
