### PR TITLE
[JsonPath] Always use brackets notation with `JsonPath::key()`

### LINKED ISSUE #60664: The JsonPath path builder produces an invalid JsonPath expressions for keys that are not valid identifiers
### Symfony version(s) affected

7.3.0

### Description

In JsonPath, the compact dot notation for segments is a shortcut making it easier to access keys that can be written as an identifier. The canonical form is to use the bracket notation with the property name as a (quoted) string: https://www.rfc-editor.org/rfc/rfc9535#name-segments

However, our `JsonPath` class building an expression is *always* using the dot notation, without checking that the provided keys is a valid identifier.

https://github.com/symfony/symfony/blob/v7.3.0/src/Symfony/Component/JsonPath/JsonPath.php#L33

### How to reproduce

```php

use Symfony\Component\JsonPath\JsonCrawler;
use Symfony\Component\JsonPath\JsonPath;

$jsonPathExpression = (string) (new JsonPath)->key('some-prop');

dump((new JsonCrawler('{"some-prop": "example value"}'))->find($jsonPathExpression));
```

### Possible Solution

We should either always use the bracket notation or select the notation based on the key.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60664
| License       | MIT

As explained in the issue, the dot notation can lead to invalid paths when used with some identifiers (for example, when it contains a `-`). The issue gives the following example:

```php
use Symfony\Component\JsonPath\JsonCrawler;
use Symfony\Component\JsonPath\JsonPath;

$jsonPathExpression = (string) (new JsonPath)->key('some-prop');

dump((new JsonCrawler('{"some-prop": "example value"}'))->find($jsonPathExpression));
```

Let's always use the brackets notation in `JsonPath::key()`. Dot notation is only a shorthand to the verbose brackets version and this solves the problem without having to do further analysis on the key.

Added a few tests to ensure the brackets notation works well too.

### CODE REVIEW

File: src/Symfony/Component/JsonPath/JsonPath.php [hunk 1]
```diff
@@ -30,7 +30,7 @@ public function __construct(
 
     public function key(string $key): static
     {
-        return new self($this->path.(str_ends_with($this->path, '..') ? '' : '.').$key);
+        return new self($this->path.'["'.$key.'"]');
```
Comment (stof) [inline src/Symfony/Component/JsonPath/JsonPath.php]: you need to escape any double quote in the key (and probably also Unicode chars that cannot be included unescaped)

**Review by stof — COMMENTED** [review]
I suggest also adding a test covering the usage of `$["*"]` to access the `*` key (instead of all keys), as you increase test coverage.

File: src/Symfony/Component/JsonPath/JsonPath.php (hunk 1 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/JsonPath/JsonPath.php]: Indeed, changed the logic and added many test cases

**Review by stof — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @alexandre-daubois.
