### PR TITLE
[Serializer] Fix `ObjectNormalizer` with property path

### LINKED ISSUE #54983: [Serializer] regression with attribute serialization
### Symfony version(s) affected

6.4.7

### Description

There appears to be a regression in v6.4.7 with serializing "nested" attributes with a property path.

### How to reproduce

Given a serialization config like:

```yaml
App\Entity\Foo:
  attributes:
    bar.id:
      serialized_name: bar_id
      groups: ['read']
```

where `Bar` is a relation on `Foo`, `bar_id` is not serialized in in v6.4.7, but was in v6.4.6.
### Possible Solution

_No response_

### Additional Context

https://github.com/symfony/symfony/pull/52917 seems suspect to me.

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54983
| License       | MIT

Caused by #52917.

The `ObjectNormalizer::isAllowedAttribute()` method doesn't work with property paths, this is an attempt to fix the problem.

### CODE REVIEW

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php [hunk 1]
```diff
@@ -194,7 +194,12 @@ protected function isAllowedAttribute($classOrObject, string $attribute, ?string
         $class = \is_object($classOrObject) ? \get_class($classOrObject) : $classOrObject;
 
         if ($context['_read_attributes'] ?? true) {
-            return $this->propertyInfoExtractor->isReadable($class, $attribute) || $this->hasAttributeAccessorMethod($class, $attribute);
+            return (\is_object($classOrObject) && $this->propertyAccessor->isReadable($classOrObject, $attribute))
+                || $this->propertyInfoExtractor->isReadable($class, $attribute) || $this->hasAttributeAccessorMethod($class, $attribute);
+        }
+
+        if (str_contains($attribute, '.')) {
```
Comment (HypeMC) [inline src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php:200]: I don't know a better way to fix this. The `$this->propertyAccessor->isWritable()` method expects an object, but the `isAllowedAttribute()` method is called before the object is instantiated.

Perhaps the `$this->propertyAccessor->isReadable()` check should be removed as well, and the method should simply return `true` if the attribute contains a `.`?

**Comment by bendavies** [comment]
thanks for taking a look at this.
@mtarld can you take a look?

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php (hunk 1 above)
Comment (mtarld) [reply src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php:200]: Indeed, I think that when can only rely on the `.` in the first place, as it'll stick a bit more with the legacy behavior.

But later on I do think that it can be great to be able to know if `foo.bar.baz` is readable/writable only based on reflection, so we have a more accurate behavior.

**Review by chalasr — APPROVED** [review]
Works for me as-is on 5.4.

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php [hunk 2]
```diff
@@ -194,7 +194,12 @@ protected function isAllowedAttribute($classOrObject, string $attribute, ?string
         $class = \is_object($classOrObject) ? \get_class($classOrObject) : $classOrObject;
 
         if ($context['_read_attributes'] ?? true) {
-            return $this->propertyInfoExtractor->isReadable($class, $attribute) || $this->hasAttributeAccessorMethod($class, $attribute);
+            return (\is_object($classOrObject) && $this->propertyAccessor->isReadable($classOrObject, $attribute))
+                || $this->propertyInfoExtractor->isReadable($class, $attribute) || $this->hasAttributeAccessorMethod($class, $attribute);
```
Comment (xabbuh) [inline src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]:
```php
return (\is_object($classOrObject) && $this->propertyAccessor->isReadable($classOrObject, $attribute)) || $this->propertyInfoExtractor->isReadable($class, $attribute) || $this->hasAttributeAccessorMethod($class, $attribute);
```

**Review by xabbuh — APPROVED** [review]

**Comment by xabbuh** [comment]
works for me as well with a minor code style change

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php (hunk 2 above)
Comment (HypeMC) [reply src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]: Done

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @HypeMC.
