### PR TITLE
[DependencyInjection] Add AsAlias attribute

### LINKED ISSUE #49361: Add `#[AsAlias]` to allow defining service aliases using attributes
This has already been asked for in #41188 and #47323, and tentatively implemented in #41207 then #49198. We also have #48523 on the topic, which tries the reverse side approach of adding the attribute on the source side of the alias (the interface).

I realize that the intuitive side is to add the attribute on the target side of the alias (the service implementation).

Both implementations in #41207 and #49198 try so solve this with a compiler pass. I think this is not the correct approach, therefor this issue to describe what could be an acceptable approach.

Using compiler passes to create the aliases opens the possibility of collision, with little control over them. This would trivially happen if two services define a tag (possibly derived from an attribute) for the same alias.

To work around this issue, I think we should register such aliases during auto-discovery. That is, in `FileLoader::registerClasses()`. This method already auto-registers aliases for singly-implemented interfaces. Looking for `#[AsAlias]` there would resolve the conflicts in two steps:
- if conflicting aliases are discovered in the same call to `FileLoader::registerClasses()`, a LogicException should be thrown
- otherwise, regular service registration order would apply: the latest loaded config wins over the previous

As a side effect, this would mean that if a service is explicitly registered, then its `AsAlias` attribute would be ignored. I think this wouldn't be an issue since when you write a service explicitly, it's quite natural to also register it as an alias when needed. This would also give the most flexibility since this would make `AsAlias` easy to ignore if needed.

Help Wanted.

### PR DESCRIPTION
**Pull request by alanpoulain**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #49361
| License       | MIT
| Doc PR        | TODO symfony/symfony-docs#...

Add the `AsAlias` attribute for defining an alias on a service:
```php
use Symfony\Component\DependencyInjection\Attribute\AsAlias;
use App\MyInterface;

#[AsAlias(id: 'my-alias', public: true)]
#[AsAlias(id: MyInterface::class)]
class MyService
{}
```
If no parameter is used in the attribute and if there is only one implemented interface, it takes this interface for the alias:
```php
use Symfony\Component\DependencyInjection\Attribute\AsAlias;
use App\MyInterface;

#[AsAlias]
class MyService implements MyInterface
{}
```
is equivalent to:
```php
$services->alias(MyInterface::class, MyService::class);
```

This implementation follows @nicolas-grekas suggestion in #49361: doing it in `FileLoader::registerClasses()` allows to check if there is no collision.

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Loader/FileLoader.php [hunk 1]
```diff
@@ -140,15 +145,37 @@ public function registerClasses(Definition $prototype, string $namespace, string
 
                     continue;
                 }
+                $interfaces = [];
                 foreach (class_implements($class, false) as $interface) {
                     $this->singlyImplemented[$interface] = ($this->singlyImplemented[$interface] ?? $class) !== $class ? false : $class;
+                    $interfaces[] = $interface;
+                }
+
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Loader/FileLoader.php:153]: before processing the potential attributes, we should do 
```php
if (!$autoconfigureAttributes) {
    continue;
}
```

to skip them when autoconfiguration is disabled

File: src/Symfony/Component/DependencyInjection/Attribute/AsAlias.php [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\DependencyInjection\Attribute;
+
+/**
+ * An attribute to tell under which alias a service should be registered or to use the implemented interface if no parameter is given.
+ */
+#[\Attribute(\Attribute::TARGET_CLASS | \Attribute::IS_REPEATABLE)]
+class AsAlias
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Attribute/AsAlias.php]: let's make it final since we don't use "instanceof" matching when accessing this attribute

File: src/Symfony/Component/DependencyInjection/Loader/FileLoader.php [hunk 3]
```diff
@@ -140,15 +145,37 @@ public function registerClasses(Definition $prototype, string $namespace, string
...
+                    $attribute = $attr->newInstance();
+                    $alias = $attribute->id ?? $defaultAlias;
+                    $public = $attribute->public;
+                    if (null === $alias) {
+                        throw new LogicException(sprintf('Alias cannot be automatically determined for class "%s". If you have used the #[AsAlias] attribute with a class implementing multiple interfaces, add the interface you want to alias to the first parameter of #[AsAlias].', $class));
+                    }
+                    if (isset($this->aliases[$alias])) {
+                        throw new LogicException(sprintf('The "%s" alias has already been defined with the #[AsAlias] attribute in "%s".', $alias, $this->aliases[$alias][0]));
+                    }
+                    $this->aliases[$alias] = [$class, $public];
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Loader/FileLoader.php]: `$this->aliases[$alias] = new Alias($class, $public);` and adapt the rest

File: src/Symfony/Component/DependencyInjection/Loader/FileLoader.php [hunk 4]
```diff
@@ -157,7 +184,7 @@ public function registerClasses(Definition $prototype, string $namespace, string
     public function registerAliasesForSinglyImplementedInterfaces()
     {
         foreach ($this->interfaces as $interface) {
-            if (!empty($this->singlyImplemented[$interface]) && !$this->container->has($interface)) {
+            if (!empty($this->singlyImplemented[$interface]) && !isset($this->aliases[$interface]) && !$this->container->has($interface)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Loader/FileLoader.php:190]: at the end of this method, we should empty `$this->aliases`:
```php
$this->interfaces = $this->singlyImplemented = $this->aliases = [];
```

**Review by nicolas-grekas — COMMENTED** [review]
Really nice thank you!

**Comment by alanpoulain** [comment]
Changes done, thanks for the review :slightly_smiling_face:

File: src/Symfony/Component/DependencyInjection/Tests/Loader/FileLoaderTest.php [hunk 5]
```diff
@@ -274,6 +282,73 @@ public function testRegisterClassesWithWhenEnv(?string $env, bool $expected)
...
+        $loader->registerClasses(
+            (new Definition())->setAutoconfigured(true),
+            'Symfony\Component\DependencyInjection\Tests\Fixtures\PrototypeAsAlias\\',
+            $resource
+        );
+
+        $this->assertEquals($expectedAliases, $container->getAliases());
+    }
+
+    public function provideResourcesWithAsAliasAttributes(): iterable
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Loader/FileLoaderTest.php]: all providers should be static now

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/DependencyInjection/Tests/Loader/FileLoaderTest.php (hunk 5 above)
Comment (alanpoulain) [reply src/Symfony/Component/DependencyInjection/Tests/Loader/FileLoaderTest.php]: Right!

**Review by kbond — APPROVED** [review]
🎉

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Component/DependencyInjection/Attribute/AsAlias.php [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\DependencyInjection\Attribute;
+
+/**
+ * An attribute to tell under which alias a service should be registered or to use the implemented interface if no parameter is given.
```
Comment (chalasr) [inline src/Symfony/Component/DependencyInjection/Attribute/AsAlias.php:15]:
```suggestion
 * An attribute to tell under which alias a service should be registered or to use the implemented interface if no parameter is given.
 * @author Alan Poulain <contact@alanpoulain.eu>
```

**Comment by chalasr** [comment]
Thank you @alanpoulain.

File: src/Symfony/Component/DependencyInjection/Tests/Loader/FileLoaderTest.php [hunk 7]
```diff
@@ -274,6 +282,73 @@ public function testRegisterClassesWithWhenEnv(?string $env, bool $expected)
...
+    {
+        yield 'Private' => ['PrototypeAsAlias/{WithAsAlias,AliasFooInterface}.php', [AliasFooInterface::class => new Alias(WithAsAlias::class)]];
+        yield 'Interface' => ['PrototypeAsAlias/{WithAsAliasInterface,AliasFooInterface}.php', [AliasFooInterface::class => new Alias(WithAsAliasInterface::class)]];
+        yield 'Multiple' => ['PrototypeAsAlias/{WithAsAliasMultiple,AliasFooInterface}.php', [
+            AliasFooInterface::class => new Alias(WithAsAliasMultiple::class, true),
+            'some-alias' => new Alias(WithAsAliasMultiple::class),
+        ]];
+        yield 'Multiple with id' => ['PrototypeAsAlias/{WithAsAliasIdMultipleInterface,AliasBarInterface,AliasFooInterface}.php', [
+            AliasBarInterface::class => new Alias(WithAsAliasIdMultipleInterface::class),
+            AliasFooInterface::class => new Alias(WithAsAliasIdMultipleInterface::class),
```
Comment (xabbuh) [inline src/Symfony/Component/DependencyInjection/Tests/Loader/FileLoaderTest.php:312]: Why is the `AliasFooInterface` being registered? Is it because of the `WithAsAliasIdMultipleInterface` class being the only one implementing this interface?

Comment (alanpoulain) [reply src/Symfony/Component/DependencyInjection/Tests/Loader/FileLoaderTest.php:312]: Yes. I think it's the right behavior, don't you think so? The other possibility would be to prevent the singly implemented interface registration if there is an `AsAlias` attribute on the class.
