### PR TITLE
[HttpClient] Fix promise behavior in HttplugClient

### LINKED ISSUE #37488: [HttpClient] HttplugClient::sendAsyncRequest doesn't always return full promise implementation
**Symfony version(s) affected**: 4.x, 5.x

**Description**  

https://github.com/symfony/symfony/blob/b3df84c857f41084720f58aef91fe35e272bc3b6/src/Symfony/Component/HttpClient/HttplugClient.php#L117
`RejectedPromise` returned here is `Http\Promise\RejectedPromise`, but not the full implementation like `Symfony\Component\HttpClient\Response\HttplugPromise` (as in docblock `@return`)
This can cause problem. For example, promises returned by then functions will be treated as plain value.

The code:
https://github.com/php-http/promise/blob/02ee67f2346b4eec3861afec741c656f5ff717ab/src/RejectedPromise.php

How Guzzle promise settle promises:
https://github.com/guzzle/promises/blob/bbf3b200bc83c1e9298580a9f99b9be248543467/src/RejectedPromise.php#L40
https://github.com/guzzle/promises/blob/bbf3b200bc83c1e9298580a9f99b9be248543467/src/Promise.php#L108

**How to reproduce**  

https://github.com/brentybh/symfony-37488
Sorry, it's not finished yet.
Because I have to bring in a retry middleware.
The Httplug simple promise CAN cover most simple use cases. But the retry middleware implementation is different...
**Possible Solution**  

emm.. Maybe it's not strictly an issue of Symfony but a problem of Httplug....
**Additional context**

### PR DESCRIPTION
**Pull request by bohanwood**
| Q             | A
| ------------- | ---
| Branch?       | 4.4 & up 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #37488 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

## The Problem
Promises have 2 important methods: `then` and `wait`.
To implement Httplug's promise interface, we built `HttplugPromise` on top of Guzzle promise.
However, when an error occurred (Httplug `NetworkException` thrown) while init the request/before actually sending the request,
`HttplugClient::sendAsyncRequest` will return a `Http\Promise\RejectedPromise`, which is a dummy implementation.

If the `then` callable returns a promise-like object, `Http\Promise\RejectedPromise` will treat it as plain value.
Guzzle promise will try to resolve the promise-like value, which is an object that has `then` method on it.

https://github.com/guzzle/promises/blob/bbf3b200bc83c1e9298580a9f99b9be248543467/src/Promise.php#L116

To fix this, I edited `src/Symfony/Component/HttpClient/HttplugClient.php`.

Next, let me explain why to edit `src/Symfony/Component/HttpClient/Response/HttplugPromise.php`.
After the previous fix, when a Guzzle promise returned by the `then` callable, things will work.
However, If I return a `HttplugPromiseInterface`, it doesn't work, because Guzzle promise `wait` the return value (result)
only if it's a Guzzle promise.

https://github.com/guzzle/promises/blob/bbf3b200bc83c1e9298580a9f99b9be248543467/src/Promise.php#L63

To fix this, I referenced the `wait` code of Guzzle promise and edited our `HttplugPromise`.

## How this fix make sense

So, why to return a promise from the `then` callable?
This let us change the promise chain according to current promise's result (fulfilled/rejected).

For example, we can retry an HTTP request if it failed.
Please take a look at my test code.

### CODE REVIEW

File: src/Symfony/Component/HttpClient/Response/HttplugPromise.php [hunk 1]
```diff
@@ -54,6 +54,12 @@ public function getState(): string
      */
     public function wait($unwrap = true)
     {
-        return $this->promise->wait($unwrap);
+        $result = $this->promise->wait($unwrap);
+
+        if ($result instanceof HttplugPromiseInterface) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/Response/HttplugPromise.php:59]: Should this be a while loop?

**Review by nicolas-grekas — COMMENTED** [review]
Nice thanks. I suppose this should sorry arbitrary levels of needed promises?

File: src/Symfony/Component/HttpClient/Response/HttplugPromise.php (hunk 1 above)
Comment (brentybh) [reply src/Symfony/Component/HttpClient/Response/HttplugPromise.php:59]: while $result is HttplugPromiseInterface? emm... maybe yes!

Comment (brentybh) [reply src/Symfony/Component/HttpClient/Response/HttplugPromise.php]: Fixed and added test to ensure arbitrary levels of promises work.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @brentybh.
