### PR TITLE
[Console] Improve `#[Argument]`/`#[Option]` exception messages

### LINKED ISSUE #60412: [Console] 7.3 Add source filename to `#[Option]` error messages
### Description

Although the underlying issue about nullable strings in options will likely change in beta3, I think this request is still valid -- I'd like to see the filename with the error message.

```
In Option.php line 88:
                                                                      
  [Symfony\Component\Console\Exception\LogicException]                
  The option parameter "$routeName" must not have a default of null.  
                                                                      

Exception trace:
  at /home/tac/g/sites/pgsc/vendor/symfony/console/Attribute/Option.php:88
 Symfony\Component\Console\Attribute\Option::tryFrom() at /home/tac/g/sites/pgsc/vendor/symfony/console/Command/InvokableCommand.php:78
 Symfony\Component\Console\Command\InvokableCommand->configure() at /home/tac/g/sites/pgsc/vendor/symfony/console/Command/Command.php:421
```

Since I do a lot of bundle development, I'd like to know exactly which file is causing the problem.  @kbond  Can the error message simply append the Command class that caused the problem?  

### Example

_No response_

### PR DESCRIPTION
**Pull request by kbond**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60412
| License       | MIT

Includes the class/method in `#[Argument]`/`#[Option]` exception messages.

### CODE REVIEW

**Comment by yceruto** [comment]
@kbond it seems [tests failures](https://github.com/symfony/symfony/actions/runs/15090184873/job/42417607959?pr=60447) are related

**Comment by kbond** [comment]
Ak, indeed, I'll get them fixed

File: src/Symfony/Component/Console/Attribute/Option.php [hunk 1]
```diff
@@ -57,11 +58,17 @@ public static function tryFrom(\ReflectionParameter $parameter): ?self
...
+        } else {
+            $self->function = $function->name;
+        }
+
         $name = $parameter->getName();
         $type = $parameter->getType();
 
         if (!$parameter->isDefaultValueAvailable()) {
-            throw new LogicException(\sprintf('The option parameter "$%s" must declare a default value.', $name));
+            throw new LogicException(\sprintf('The option parameter "$%s" of "%s()" must declare a default value.', $name, $self->function));
```
Comment (OskarStark) [inline src/Symfony/Component/Console/Attribute/Option.php:71]:
```suggestion
            throw new LogicException(\sprintf('The optional parameter "$%s" of "%s()" must declare a default value.', $name, $self->function));
```
?

Comment (chalasr) [reply src/Symfony/Component/Console/Attribute/Option.php:71]: It's about an input option

File: src/Symfony/Component/Console/Tests/Command/InvokableCommandTest.php [hunk 2]
```diff
@@ -27,6 +27,8 @@
 
 class InvokableCommandTest extends TestCase
 {
+    private const FUNCTION_NAME = 'Symfony\Component\Console\Tests\Command\InvokableCommandTest::Symfony\Component\Console\Tests\Command\{closure}()';
```
Comment (GromNaN) [inline src/Symfony/Component/Console/Tests/Command/InvokableCommandTest.php]: I don't understand the 2 namespaces? It should be `Symfony\Component\Console\Tests\Command\InvokableCommandTest\{closure}()`

Comment (kbond) [reply src/Symfony/Component/Console/Tests/Command/InvokableCommandTest.php]: I copied the code to extract the function name from https://github.com/symfony/symfony/blob/cb084808343a10152d4ec69c658f75878d41d3d3/src/Symfony/Component/DependencyInjection/Attribute/Target.php#L55. With closures it's a little wonky I admin - plus it changes in 8.4 to include more context (hence the current failures).

For invokable classes, which most of these new commands will be in practice, the name looks like you expect: `App\Command\SendSalesReportsCommand::__invoke()`

**Comment by kbond** [comment]
I opted to remove the exception message assertion rather than dig into crazy regex. If someone has a better method, let me know!

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @kbond.
