### PR TITLE
[DependencyInjection] Add ContainerBuilder::willBeAvailable() to help with conditional configuration

### LINKED ISSUE #39356: [Serializer] Can't deserialize array of objects with composer install --no-dev
**Symfony version(s) affected**: 5.1.9

**Description**  
I don't know how to describe this bug without code, so here only the tl;dr. The results of the symfony serializer differ between `composer install` and `composer install --no-dev`.

**How to reproduce**  
Consider the following code:

```php
class Entry 
{
  public DateTimeInterface $dateTime;
}

class EntryData
{
  /**
   * @var Entry[]
   */
  public array $entries;
}

$entryDataJson = '{"entries": [ { "dateTime": "2020-12-07T06:30:14.666Z" } ] }';

$result = $serializer->deserialize($entryDataJson, EntryData::class, 'json');
```

When having everything installed running `composer install` then a var_dump on $result will look like this:

```
object(App\Model\EntryData)[685]
  public array 'entries' => 
    array (size=1)
      0 => 
        object(App\Model\Entry)[719]
          public DateTimeInterface 'dateTime' => 
            object(DateTimeImmutable)[721]
              ...
```

Now run `composer install --no-dev` and run the code again. The result will now look like this:
```
object(App\Model\EntryData)[685]
  public array 'entries' => 
    array (size=1)
      0 => 
        array (size=1)
          'dateTime' => string '2020-12-07T06:30:14.666Z' (length=24)
```

As you can see using the Serializer with `composer install` will correctly deserialize the array of `Entry`-objects. When using `composer install --no-dev` you'll get a simple key-value based array instead. That is because in the symfony serializer the package `phpdocumentor/reflection-docblock` is listed in `require-dev`, not in `require`. That leads to the PhpDocExtrator not being used with `--no-dev`.
There is no Exception or anything, because in the `FrameworkExtension` in `registerPropertyInfoConfiguration` the PhpDocExtrator is simply not registered, if the `phpDocumentor\Reflection\DocBlockFactoryInterface` doesn't exist.

**Possible Solution**  
Either move `phpdocumentor/reflection-docblock` from `require-dev` to `require` in composer.json. Or throw an exception (or at least a warning) if it's not installed along the symfony serializer.
IMO the dependency should be moved to `require`, because it actually affects the results.

### LINKED ISSUE #40136: [PropertyInfo] Optional dependency phpdocumenter/reflection-docblock is a risk when already installed as dev-dependency
**Symfony version(s) affected**: 3.4.47 & 4.4.19 & 5.2.3

**Description**  
`phpdocumenter/reflection-docblock` is an optional dependency of `symfony/property-info`, but a required dependency when the `PhpDocExtractor` is used. If someone wants to use the `PhpDocExtractor` and did not install `phpdocumenter/reflection-docblock`, then a  clear exception is shown:

```
Unable to use the "PhpDocExtractor" class as the "phpdocumentor/reflection-docblock" package is not installed.
```

So far, so good. Install the dependency and continue.

The problemen arises when `phpdocumentor/reflection-docblock` is already installed as a require-dev dependency, which is probably true in many projects: `phpdocumentor/reflection-docblock` is a dependency of `phpunit/phpunit`. In those cases, you don't get the exception and things work fine while developing and testing. However, after deploying the application to production, it breaks. Require-dev dependencies are not installed, and therefore `phpdocumentor/reflection-docblock` is not installed, and thus the exception is only shown in production.

I think this is a big risk. There is no automated way to test this kind of things, because automated test tools also usually run with development dependencies. The underlying problem is that in composer, dev en production dependencies are mixed. Therefore, production code can (accidentally) depend on dev-dependencies.

This is of course a problem with all optional dependencies that could break the application when not present. But this use case is probably more common than others, and therefore a bigger risk.

**How to reproduce**  
Create a project with `symfony/property-info` as dependency and `phpunit/phpunit` as dev-dependency and make use of the `PhpDocExtractor`. This works, until installling the application without dev-dependencies.

**Possible Solution**  
The ultimate solution is to not rely on optional dependencies, because they could be available during development, but not in production. Instead, either require the dependency or extract the piece of code that requires the dependency to a separate composer package.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #40136, fix #39356
| License       | MIT
| Doc PR        | no need to

Leverages https://github.com/composer/composer/pull/9682 to ignore dev-packages when configuring the container.

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/ContainerBuilder.php [hunk 1]
```diff
@@ -407,6 +408,27 @@ public function fileExists(string $path, $trackContents = true): bool
         return $exists;
     }
 
+    final public function isInstalled(string $package, string $class, string $method = null): bool
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: the method name is weird, as this is not only about checking whether the package is installed but also whether a specific API is available.

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: Any other idea? I thought of `symbolExists` or `featureExists`. Better?

Comment (OskarStark) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: isSpecified?

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: I updated all the codebase to use the new method. `isInstalled()` LGTM...

Comment (stof) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: maybe `isAvailable`

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: `isAvailable()` works for me, updated, thanks.

File: src/Symfony/Bundle/TwigBundle/DependencyInjection/Compiler/ExtensionPass.php [hunk 2]
```diff
@@ -103,15 +103,15 @@ public function process(ContainerBuilder $container)
             $container->getDefinition('twig.extension.yaml')->addTag('twig.extension');
         }
 
-        if (class_exists(\Symfony\Component\Stopwatch\Stopwatch::class)) {
+        if ($container->isAvailable('symfony/stopwatch', \Symfony\Component\Stopwatch\Stopwatch::class)) {
```
Comment (stof) [inline src/Symfony/Bundle/TwigBundle/DependencyInjection/Compiler/ExtensionPass.php]: this one looks wrong to me. stopwatch is regularly enabled only in dev setups

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 3]
```diff
@@ -211,19 +211,19 @@ public function load(array $configs, ContainerBuilder $container)
...
-        if (class_exists(Application::class)) {
+        if ($container->isAvailable('symfony/console', Application::class)) {
             $loader->load('console.php');
 
-            if (!class_exists(BaseXliffLintCommand::class)) {
+            if (!$container->isAvailable('symfony/translation', BaseXliffLintCommand::class)) {
                 $container->removeDefinition('console.command.xliff_lint');
             }
-            if (!class_exists(BaseYamlLintCommand::class)) {
+            if (!$container->isAvailable('symfony/yaml', BaseYamlLintCommand::class)) {
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: to me, the commands should be registered if installed so that they are usable (especially for such developer-focused commands

File: src/Symfony/Bundle/DebugBundle/DependencyInjection/DebugExtension.php [hunk 4]
```diff
@@ -45,12 +45,12 @@ public function load(array $configs, ContainerBuilder $container)
             ->addMethodCall('setMinDepth', [$config['min_depth']])
             ->addMethodCall('setMaxString', [$config['max_string_length']]);
 
-        if (method_exists(ReflectionCaster::class, 'unsetClosureFileInfo')) {
+        if ($container->isAvailable('symfony/var-dumper', ReflectionCaster::class, 'unsetClosureFileInfo')) {
```
Comment (stof) [inline src/Symfony/Bundle/DebugBundle/DependencyInjection/DebugExtension.php]: We clearly want to configure VarDumper even if it is a dev dependency.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 5]
```diff
@@ -299,7 +299,7 @@ public function load(array $configs, ContainerBuilder $container)
         if (!empty($config['test'])) {
             $loader->load('test.php');
 
-            if (!class_exists(AbstractBrowser::class)) {
+            if (!$container->isAvailable('symfony/browser-kit', AbstractBrowser::class)) {
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: this is likely a dev dependency too as it is about tests

File: src/Symfony/Component/HttpKernel/DependencyInjection/ControllerArgumentValueResolverPass.php [hunk 6]
```diff
@@ -47,7 +47,7 @@ public function process(ContainerBuilder $container)
 
         $resolvers = $this->findAndSortTaggedServices($this->argumentValueResolverTag, $container);
 
-        if ($container->getParameter('kernel.debug') && class_exists(Stopwatch::class) && $container->has($this->traceableResolverStopwatch)) {
+        if ($container->getParameter('kernel.debug') && $container->isAvailable('symfony/stopwatch', Stopwatch::class) && $container->has($this->traceableResolverStopwatch)) {
```
Comment (stof) [inline src/Symfony/Component/HttpKernel/DependencyInjection/ControllerArgumentValueResolverPass.php]: this is a dev feature

File: src/Symfony/Component/DependencyInjection/Compiler/ValidateEnvPlaceholdersPass.php [hunk 7]
```diff
@@ -37,7 +37,7 @@ public function process(ContainerBuilder $container)
     {
         $this->extensionConfig = [];
 
-        if (!class_exists(BaseNode::class) || !$extensions = $container->getExtensions()) {
+        if (!$container->isAvailable('symfony/config', BaseNode::class) || !$extensions = $container->getExtensions()) {
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Compiler/ValidateEnvPlaceholdersPass.php]: this one should be reverted IMO as it is not about enabling a feature that affect later usages but about validating the placeholders

File: src/Symfony/Bundle/TwigBundle/DependencyInjection/Compiler/ExtensionPass.php (hunk 2 above)
Comment (nicolas-grekas) [reply src/Symfony/Bundle/TwigBundle/DependencyInjection/Compiler/ExtensionPass.php]: all fixed, thanks

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 8]
```diff
@@ -433,15 +433,15 @@ public function load(array $configs, ContainerBuilder $container)
...
+            if (!$container->isAvailable('symfony/rate-limiter', LimiterInterface::class)) {
                 throw new LogicException('Rate limiter support cannot be enabled as the RateLimiter component is not installed. Try running "composer require symfony/rate-limiter".');
             }
 
             $this->registerRateLimiterConfiguration($config['rate_limiter'], $container, $loader);
         }
 
         if ($this->isConfigEnabled($container, $config['web_link'])) {
-            if (!class_exists(HttpHeaderSerializer::class)) {
+            if (!$container->isAvailable('symfony/weblink', HttpHeaderSerializer::class)) {
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: IMO, the checks around such exceptions inside a `isConfigEnabled` should keep the old logic. Maybe some projects are indeed enabling some config only in dev environments on purpose (in which case is is OK if it is a dev dependency). The current change forbids enabling the feature at all.

What should be changed instead is the smart default for enabling the config (which is in `Configuration`

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 9]
```diff
@@ -902,7 +902,7 @@ private function registerDebugConfiguration(array $config, ContainerBuilder $con
     {
         $loader->load('debug_prod.php');
 
-        if (class_exists(Stopwatch::class)) {
+        if ($container->isAvailable('symfony/stopwatch', Stopwatch::class)) {
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: we definitely want to register `debug.stopwatch` even if it is a dev dependency. that's a debugging tool.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 10]
```diff
@@ -915,7 +915,7 @@ private function registerDebugConfiguration(array $config, ContainerBuilder $con
             $container->setParameter('debug.container.dump', '%kernel.build_dir%/%kernel.container_class%.xml');
         }
 
-        if ($debug && class_exists(Stopwatch::class)) {
+        if ($debug && $container->isAvailable('symfony/stopwatch', Stopwatch::class)) {
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: same here

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 11]
```diff
@@ -931,7 +931,7 @@ private function registerDebugConfiguration(array $config, ContainerBuilder $con
             $container->setParameter('debug.error_handler.throw_at', 0);
         }
 
-        if ($debug && class_exists(DebugProcessor::class)) {
+        if ($debug && $container->isAvailable('symfony/monolog-bridge', DebugProcessor::class)) {
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: DebugProcessor is a dev tool as well

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 12]
```diff
@@ -1792,7 +1792,7 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
                 }
             }
 
-            if ($container->getParameter('kernel.debug') && class_exists(Stopwatch::class)) {
+            if ($container->getParameter('kernel.debug') && $container->isAvailable('symfony/stopwatch', Stopwatch::class)) {
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: this is a debug tool too

File: src/Symfony/Bundle/TwigBundle/DependencyInjection/TwigExtension.php [hunk 13]
```diff
@@ -37,19 +37,19 @@ public function load(array $configs, ContainerBuilder $container)
         $loader = new PhpFileLoader($container, new FileLocator(__DIR__.'/../Resources/config'));
         $loader->load('twig.php');
 
-        if (class_exists(\Symfony\Component\Form\Form::class)) {
+        if ($container->isAvailable('symfony/form', \Symfony\Component\Form\Form::class)) {
             $loader->load('form.php');
         }
 
-        if (class_exists(Application::class)) {
+        if ($container->isAvailable('symfony/console', Application::class)) {
```
Comment (stof) [inline src/Symfony/Bundle/TwigBundle/DependencyInjection/TwigExtension.php]: the Twig commands should be registered as soon as the symfony/console is installed, even if only a dev requirement. the commands are dev tools only anyway

**Comment by nicolas-grekas** [comment]
I renamed the method `willBeAvailable()` to hint that this is for checking the availability of symbols at runtime, not compile time.

**Comment by stof** [comment]
that's indeed a good idea. But then, please check my review even if it is on an outdated diff due to the renaming.

File: src/Symfony/Component/DependencyInjection/ContainerBuilder.php [hunk 14]
```diff
@@ -407,6 +408,27 @@ public function fileExists(string $path, $trackContents = true): bool
         return $exists;
     }
 
+    final public function willBeAvailable(string $package, string $class, string $method = null): bool
```
Comment (ro0NL) [inline src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: the $method arg seems unused. IMHO `willBeAvailable('x/y', y::class) && method_exists(y::class, 'new')` is more clear, by letting the user own the extra condition.

Comment (ro0NL) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: even the $class check is debatable, if we'd check the package for a certain version (`willBeAvailable('x/y', '1.0')`), as it implies the actual state

perhaps at this point we prefer a crash, rather than a silent skip

Comment (stof) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: checking a class is better than checking a version:

- checking version is not compatible with replaced packages (such packages are returning true for `InstalledVersions::isInstalled($package)` but don't return a version for `InstalledVersions::getVersion()`)
- feature detection is more flexible than detecting package version (the frontend ecosystem learned a lot from that, by moving to feature detection rather than sniffing the browser version and assuming the related support). Also, it works even for dev versions

Comment (ro0NL) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: i generally agree. I also missed `!class_exists(InstalledVersions::class)` which explains why we need both a package check and a feature check.

Compared to the frontend ecosystem. im not sure checking N browsers for 1 feature vs. 1 package for 1 feature compares well, or justifies not checking for packages in our case.

Comment (stof) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: Due to `replace` rules in composer, you could have any package actually be responsible for shipping the class. And so you cannot get the version number introducing it.
We do have one *main* package owning the class (which is why we can have a package name here), and composer is handling replacement for us in this case. But not for versions.

Comment (ro0NL) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: `replace` rules take a version constraint though :/

ive no experience with eg. `"replace": { "x/y": ">=2"}`, only `* / self.version`, however conceptually id say we know the replaced versions for a package

no intention to push this direction :) current solution is OK.

from a maintainer pov i pick `is x/y 2.0 minimally available` any day compared to awkward feature checking hoping it pinpoints to the right version.

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: Good idea, I removed the `$method` argument.

Versions checks are no-go on my side: feature checks are much more maintainable than cryptic version numbers. Thanks for proposing.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 15]
```diff
@@ -107,8 +108,20 @@ public function getConfigTreeBuilder()
             ->end()
         ;
 
+        $container = new ContainerBuilder();
+        $willBeAvailable = static function (string $package, string $class, string $parentPackage = null) use ($container) {
+            $parentPackages = (array) $parentPackage;
```
Comment (ro0NL) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:114]: `static $container; $container ??= new ContainerBuilder();` wdyt?

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:114]: `Parse error: syntax error, unexpected '='` on PHP 7.2...

Comment (stof) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:114]: maybe the container a static variable would also be a totally different behavior

**Comment by nicolas-grekas** [comment]
@stof comments addressed. The method now takes a new argument that defines the parent dep of a dep, so that we can consider that a package installed to satisfy a dev-mode dep is available even if it is in dev-mode.

File: src/Symfony/Component/DependencyInjection/ContainerBuilder.php [hunk 16]
```diff
@@ -407,6 +409,28 @@ public function fileExists(string $path, $trackContents = true): bool
         return $exists;
     }
 
+    final public function willBeAvailable(string $package, string $class, array $parentPackages): bool
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: this deserves some phpdoc explaining the goal of the method IMO

File: src/Symfony/Component/DependencyInjection/ContainerBuilder.php [hunk 17]
```diff
@@ -407,6 +409,28 @@ public function fileExists(string $path, $trackContents = true): bool
...
+    {
+        if (!class_exists($class) && !interface_exists($class, false) && !trait_exists($class, false)) {
+            return false;
+        }
+
+        if (class_exists(FullStack::class) || !class_exists(InstalledVersions::class) || !InstalledVersions::isInstalled($package) || InstalledVersions::isInstalled($package, true)) {
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: this looks weird to me to return `true` in case of `!InstalledVersions::isInstalled($package)`

Comment (stof) [inline src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: Regarding `FullStack::class`, this should not be done in that class. Otherwise, this API has to become an internal one usable only for packages belonging to the fullstack repo instead of making it usable by other bundles too.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 18]
```diff
@@ -107,8 +108,20 @@ public function getConfigTreeBuilder()
...
+            $parentPackages[] = 'symfony/framework-bundle';
+
+            return $container->willBeAvailable($package, $class, $parentPackages);
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: should the `willBeAvailable` method really be defined in `ContainerBuilder` as an instance method ? This leads to such weird cases where we have to create a ContainerBundle just to use it. And AFAICT, it does not really depend on other parts of the ContainerBuilder.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 19]
```diff
@@ -1475,7 +1479,7 @@ private function registerAnnotationsConfiguration(array $config, ContainerBuilde
 
     private function registerPropertyAccessConfiguration(array $config, ContainerBuilder $container, PhpFileLoader $loader)
     {
-        if (!class_exists(PropertyAccessor::class)) {
+        if (!$container->willBeAvailable('symfony/property-access', PropertyAccessor::class, ['symfony/framework-bundle'])) {
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: this prevents enabling `property-access` access at all for dev-only features. Shouldn't this be changed to be a configurable enabling instead (with a smart default using this logic, but still allowing an explicit choice to force it if needed) as done for other components ?

File: src/Symfony/Component/DependencyInjection/ContainerBuilder.php (hunk 17 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: I needed it in a previous iteration, not anymore. Removed.

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: I think that's desired to account for weird situations when the class is here but not the package.
There is no reason why this can happen. Yet, if it happens, we should consider that the class is available IMHO.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php (hunk 18 above)
Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: I thought the same, and I think it's important to discourage using the method outside of any compilation steps. By making it a non-static method on ContainerBuilder, we kinda achieve this IMHO.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 19 above)
Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: agreed, added

File: src/Symfony/Component/DependencyInjection/ContainerBuilder.php (hunk 16 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: docblock added

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php (hunk 18 above)
Comment (ro0NL) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: `Compiler::isAvailable` could work

File: src/Symfony/Component/DependencyInjection/ContainerBuilder.php [hunk 20]
```diff
@@ -407,6 +408,34 @@ public function fileExists(string $path, $trackContents = true): bool
         return $exists;
     }
 
+    /**
+     * Checks whether a class is available and will remain available in the "no-dev" mode of Composer.
+     *
+     * When parent packages are provided and if any of them is in dev-only mode,
```
Comment (jderusse) [inline src/Symfony/Component/DependencyInjection/ContainerBuilder.php:414]:
```suggestion
     * When parent packages are provided and if any of them is not in dev-only mode,
```

?

File: src/Symfony/Component/DependencyInjection/ContainerBuilder.php [hunk 21]
```diff
@@ -407,6 +408,34 @@ public function fileExists(string $path, $trackContents = true): bool
...
+
+        if (!class_exists(InstalledVersions::class) || !InstalledVersions::isInstalled($package) || InstalledVersions::isInstalled($package, true)) {
+            return true;
+        }
+
+        // the package is installed but in dev-mode only, check if this applies to one of the parent packages too
+
+        $rootPackage = InstalledVersions::getRootPackage()['name'] ?? '';
+        foreach ($parentPackages as $package) {
+            if ($rootPackage === $package || (InstalledVersions::isInstalled($package) && !InstalledVersions::isInstalled($package, true))) {
```
Comment (jderusse) [inline src/Symfony/Component/DependencyInjection/ContainerBuilder.php:431]: shouldn't it be the opposite?. At least one parent package should be available in prod mode?

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php (hunk 18 above)
Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: I made the method static instead.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 22]
```diff
@@ -215,7 +220,7 @@ public function load(array $configs, ContainerBuilder $container)
         $loader->load('fragment_renderer.php');
         $loader->load('error_renderer.php');
 
-        if (interface_exists(PsrEventDispatcherInterface::class)) {
+        if ($container::willBeAvailable('psr/event-dispatcher', PsrEventDispatcherInterface::class, ['symfony/framework-bundle'])) {
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: As this is a static method, I'd rather use `ContainerBuilder::willBeAvailable` to make the usage more clear

File: src/Symfony/Component/DependencyInjection/ContainerBuilder.php [hunk 23]
```diff
@@ -1436,6 +1437,34 @@ public function log(CompilerPassInterface $pass, string $message)
...
+        }
+
+        if (!class_exists(InstalledVersions::class) || !InstalledVersions::isInstalled($package) || InstalledVersions::isInstalled($package, true)) {
+            return true;
+        }
+
+        // the package is installed but in dev-mode only, check if this applies to one of the parent packages too
+
+        $rootPackage = InstalledVersions::getRootPackage()['name'] ?? '';
+        foreach ($parentPackages as $package) {
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: I would avoid overriding the `$package` variable passed as argument here. This will reduce confusion when reading the code (and reduce the risk of bugs if we later add more code after this loop expecting to use the argument). I suggest using `foreach ($parentPackages as $parentPackage) {`

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 22 above)
Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: thanks for the review, updated!

File: src/Symfony/Component/DependencyInjection/ContainerBuilder.php (hunk 23 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/ContainerBuilder.php]: updated

**Review by stof — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Rebase needed
