### PR TITLE
[ObjectMapper] handle non existing property errors

### LINKED ISSUE #60848: [ObjectMapper] if 'isset' and default values not working
### Symfony version(s) affected

7.3.0

### Description

It appears that default values don't work with the ObjectMapper.

OptionsResolver has a method to ignore missing properties, but it seems like it shouldn't need a way to ignore properties if they have a default value.

### How to reproduce

```php
$mapper = new ObjectMapper();
$target = 'App\Dto\MyClass';
$obj = (object) ['id'=>'abc'];
$entity = $mapper->map($obj, $target);
```

```php
namespace App\Dto\;

class MyClass
{
    public function __construct(
        public string  $id,

        #[Map(source: 'optional', if: 'isset')]
        public ?string $optional = null,
    {

    }
}
```

[PixieImportService.php](myide://open?url=file:///home/tac/sites/survos/packages/pixie-bundle/src/Service/PixieImportService.php&line=755) on line 755:
ErrorException {#10250 ▼
  #message: "Warning: Undefined property: stdClass::$optional"
  #code: 0
  #file: "
/home/tac/sites/mus/vendor
/symfony/object-mapper/
ObjectMapper.php
"
  #line: 170
  #severity: E_WARNING
  trace: {▶}

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #60848
| License       | MIT

The property accessor allows to ignore exceptions when a property does not exist. Without the property accessor we now throw a proper exception when the property does not exist (as opposed to the PHP Warning it'd trigger otherwise). I think its better to thrown then to hide the error in that particular case. 

This fixes #60848 providing a working solution and a better DX, especially that in PHP the behavior of dynamic properties is to avoid them as much as possible.

### CODE REVIEW

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php [hunk 1]
```diff
@@ -167,7 +168,15 @@ public function map(object $source, object|string|null $target = null): object
 
     private function getRawValue(object $source, string $propertyName): mixed
     {
-        return $this->propertyAccessor ? $this->propertyAccessor->getValue($source, $propertyName) : $source->{$propertyName};
+        if ($this->propertyAccessor) {
+            return $this->propertyAccessor->getValue($source, $propertyName);
+        }
+
+        if (!property_exists($source, $propertyName) && !(method_exists($source, '__isset') && true === $source->__isset($propertyName))) {
```
Comment (soyuka) [inline src/Symfony/Component/ObjectMapper/ObjectMapper.php]: I'm not a huge fan of testing for the `__isset` magic method but if we don't add this its hard to support magic getters properly, maybe we should not support them in the first place? 

Comments welcome.

**Comment by tacman** [comment]
Hmm.  I'm not sure why this is a non-existing property error.

The DTO has the property $extra, with a default of null (or something else).

The source object is a simple StdClass that doesn't have the property.  It's not setting a non-existing property of the target object, but rather set a default on the target object when the source object is missing the field.

I think it's a pretty common case -- the source and target have some common fields, create the target object and map with the property name is the same or the property has a #[Map()] attribute.

**Comment by tacman** [comment]
the "isset" was just something I tried because it seemed like logic that would work, but didn't.  Could be a different issue.

**Comment by soyuka** [comment]
> The source object is a simple StdClass that doesn't have the property. It's not setting a non-existing property of the target object, but rather set a default on the target object when the source object is missing the field.

In your example: 

```php
$mapper = new ObjectMapper();
$target = 'App\Dto\MyClass';
$obj = (object) ['id'=>'abc'];
$entity = $mapper->map($obj, $target);
```

The `stdClass` does not have any information about how it should be mapped, therefore we use the data from the `$target` (here `App\Dto\MyClass`. `App\Dto\MyClass` has a `default` but when we read that property on the `stdClass` it does not exists. So it's not "setting a non-existing property" but "reading a non-existing property" which leads to a `NoSuchPropertyException`. Looks fine to me.
The default value works fine when using the PropertyAccessor with the proper option see my assertions in the tests:

```php
        $this->assertEquals('abc', $b->id);
        $this->assertEquals(null, $b->optional);
```

> I think it's a pretty common case -- the source and target have some common fields, create the target object and map with the property name is the same or the property has a #[Map()] attribute.

`stdClass` is quite specific, use DTOs on both ends of the mapping and you probably won't have any issues. 

> the "isset" was just something I tried because it seemed like logic that would work, but didn't. Could be a different issue.

Isset would be a weird use case but NotNull would be quite useful.

**Comment by tacman** [comment]
Thanks.  My use case is that I'm getting data from csv and JSON, and I want to map the data to a DTO.  But the field names and often type are wrong.

So
```csv
First Name,Last Name,Country,Language Spoken At Home
Bob,Roberts,USA,English
```

And I want a DTO of a class with properties $firstName, $lastName,$countryCode,$langCode

So I want to import from $row['First Name'] to $dto->firstName and transform the country and language names to codes them with a service.  ObjectMapper seems like the perfect tool for that.  So this step is to go from the stdClass to a DTO.  What approach do you suggest?  I've been using league/csv-reader for some parts, (which will map to a DTO), but the problem is that I don't have a DTO yet.

File: src/Symfony/Component/ObjectMapper/ObjectMapper.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/ObjectMapper/ObjectMapper.php]: I'm fine not supporting them personally, especially since magic methods don't allow checking for the existence of a property that holds a null value

```suggestion
        if (!property_exists($source, $propertyName) && !isset($source->{$propertyName}))) {
```

File: src/Symfony/Component/ObjectMapper/Tests/Fixtures/DefaultValueStdClass/TargetDto.php [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+{
+    public function __construct(
+        public string  $id,
+        #[Map(source: 'optional', if: [self::class, 'isDefined'])]
+        public ?string $optional = null,
+    )
+    {
+    }
+
+    public static function isDefined($source): bool {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/Tests/Fixtures/DefaultValueStdClass/TargetDto.php]:
```suggestion
    public static function isDefined($source): bool
    {
```

File: src/Symfony/Component/ObjectMapper/Tests/Fixtures/DefaultValueStdClass/TargetDto.php [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+use Symfony\Component\ObjectMapper\Attribute\Map;
+
+class TargetDto
+{
+    public function __construct(
+        public string  $id,
+        #[Map(source: 'optional', if: [self::class, 'isDefined'])]
+        public ?string $optional = null,
+    )
+    {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/Tests/Fixtures/DefaultValueStdClass/TargetDto.php]:
```suggestion
    ) {
```

File: src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php [hunk 4]
```diff
@@ -236,8 +238,16 @@ public function testSourceOnly()
         $mapped = $mapper->map($a, SourceOnly::class);
         $this->assertInstanceOf(SourceOnly::class, $mapped);
         $this->assertSame('test', $mapped->mappedName);
+    }
 
+    public function testSourceOnlyWithMagicMethods()
+    {
+        $mapper = new ObjectMapper();
         $a = new class {
+            public function __isset(string $key): bool {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php]:
```suggestion
            public function __isset($key): bool
            {
```

File: src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php [hunk 5]
```diff
@@ -236,8 +238,16 @@ public function testSourceOnly()
...
+                return $key === 'name';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php]:
```suggestion
                return 'name' === $key;
```

File: src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php [hunk 6]
```diff
@@ -303,4 +313,27 @@ public function testMultipleTargetMapProperty()
...
+
+    public function testDefaultValueStdClassWithPropertyInfo()
+    {
+        $u = new \stdClass();
+        $u->id = 'abc';
+        $mapper = new ObjectMapper(propertyAccessor: PropertyAccess::createPropertyAccessorBuilder()->disableExceptionOnInvalidPropertyPath()->getPropertyAccessor());
+        $b = $mapper->map($u, TargetDto::class);
+        $this->assertInstanceOf(TargetDto::class, $b);
+        $this->assertEquals('abc', $b->id);
+        $this->assertEquals(null, $b->optional);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php]:
```suggestion
        $this->assertSame('abc', $b->id);
        $this->assertNull($b->optional);
```

File: src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php [hunk 7]
```diff
@@ -303,4 +313,27 @@ public function testMultipleTargetMapProperty()
...
+    public function testDefaultValueStdClass()
+    {
+        $this->expectException(NoSuchPropertyException::class);
+        $u = new \stdClass();
+        $u->id = 'abc';
+        $mapper = new ObjectMapper();
+        $b = $mapper->map($u, TargetDto::class);
+        $this->assertInstanceOf(TargetDto::class, $b);
+        $this->assertEquals('abc', $b->id);
+        $this->assertEquals(null, $b->optional);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php]:
```suggestion
        $this->assertSame('abc', $b->id);
        $this->assertNull($b->optional);
```

File: src/Symfony/Component/ObjectMapper/Exception/NoSuchPropertyException.php [hunk 8]
```diff
@@ -0,0 +1,21 @@
...
+ */
+
+namespace Symfony\Component\ObjectMapper\Exception;
+
+/**
+ * Thrown when a property cannot be found.
+ *
+ * @author Antoine Bluchet <soyuka@gmail.com>
+ */
+class NoSuchPropertyException extends MappingException
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/Exception/NoSuchPropertyException.php:19]: worth an entry on the interface?

File: src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php [hunk 9]
```diff
@@ -303,4 +314,27 @@ public function testMultipleTargetMapProperty()
         $this->assertEquals('donotmap', $c->foo);
         $this->assertEquals('foo', $c->doesNotExistInTargetB);
     }
+
+    public function testDefaultValueStdClass()
```
Comment (OskarStark) [inline src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php:318]: This test expects an exception and asserts sth. This looks weird

Comment (soyuka) [reply src/Symfony/Component/ObjectMapper/Tests/ObjectMapperTest.php:318]: nice catch thanks!

**Comment by nicolas-grekas** [comment]
Thank you @soyuka.
