### PR TITLE
[Messenger] Fix re-sending failed messages to a different failure transport

### LINKED ISSUE #51815: [Messenger] Requeue failed retries
### Description

Given `messenger:failed:retry`, it seems sane if a retry failure is put back on the failure queue, till either manually deleted or the retry succeeds.

I tried using a recursive failure transport:

```yaml
failed:
  dsn: ...
  failure_transport: failed
```

but it didnt make any changes.

### Example

_No response_

### PR DESCRIPTION
**Pull request by bartholdbos**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #51815 #53216
| License       | MIT

As explained in issue #51815 I expect messages to succeed, retry or be deleted manually. This was fixed in PR #51848 but this PR has been reverted in PR #54050 because it caused infinite re-sending as described in #53216.
I added a check to prevent re-sending a failed retry to the same transport it already came from. When a different failure transport is configured it will now be sent there.

### CODE REVIEW

**Comment by alexisLefebvre** [comment]
Since it’s a bug fix, shouldn’t this PR target an older branch like `7.4` or `8.0`?

File: src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php [hunk 1]
```diff
@@ -29,6 +29,7 @@ class SendFailedMessageToFailureTransportListener implements EventSubscriberInte
 {
     public function __construct(
         private ContainerInterface $failureSenders,
+        private array $failureTransportsByName = [],
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php]: this must be added last - currently it's a BC break

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/messenger.php [hunk 2]
```diff
@@ -219,6 +219,7 @@ class_exists(LazyString::class, false) ? service_closure('.messenger.signing_ser
         ->set('messenger.failure.send_failed_message_to_failure_transport_listener', SendFailedMessageToFailureTransportListener::class)
             ->args([
                 abstract_arg('failure transports'),
+                abstract_arg('failure transports by name'),
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/messenger.php]: where is that value computed/injected?

**Review by nicolas-grekas — CHANGES_REQUESTED** [review]
this looks unfinished and untested, isn't it?

**Review by nicolas-grekas — APPROVED** [review]
I completed the PR

**Comment by nicolas-grekas** [comment]
Thank you @bartholdbos.

**Comment by bartholdbos** [comment]
Didn't get to finishing the PR yet, thank you for that @nicolas-grekas :)
