### PR TITLE
[HttpClient] Disable HTTP/2 PUSH by default when using curl

### LINKED ISSUE #57681: [HttpClient] CURLMOPT_PUSHFUNCTION breaks on CLI
### Symfony version(s) affected

6.4

### Description

This weekend I was seeing quite a few crashes in an app processing URLs in messenger.

```
segfault at 20 ip 00007f96350cc937 sp 00007fffa3b202e8 error 6 in libc.so.6[7f9634fa0000+155000] likely on CPU 2 (core 1, socket 0)
```

Trying to reproduce the bug locally I started to see warnings on the console I've never encountered before. Apparently there was a change in an upstream service where they now push content in the `Link:` header since Friday.

```
Warning: PHP Request Shutdown: Cannot call the CURLOPT_PROGRESSFUNCTION in Unknown on line 0
PHP Warning:  PHP Request Shutdown: Cannot call the CURLOPT_PROGRESSFUNCTION in Unknown on line 0
```

### How to reproduce

- Inject `HttpClientInterface` into a command.
- Request a URL where the server sends a `Link:` header.
- Execute the command.

### Possible Solution

As I don't need the resources at all (I'm only requesting the URL because I want to determine the content type, and sometimes the app gets an URL to HTML instead of e.g. images) my first idea was setting `$maxPendingPushes` to 0 which seems to be passed-through all the way from `HttpClient` to `CurlClientState`.

I couldn't find any documented option for that parameter (like, e.g. `max_pending_pushes`) so the only way I could come up with was to use a compiler pass.

```php
<?php

declare(strict_types = 1);

namespace App\DependencyInjection;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class MaxPushesCompilerPass implements CompilerPassInterface
{
    #[\Override]
    public function process(ContainerBuilder $container): void
    {
        $container
            ->getDefinition('http_client.transport')
            ->setArgument('maxPendingPushes', 0);
    }
}
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #57681
| License       | MIT

I propose to disable HTTP/2 PUSH by default when using curl. Amp still supports it out of the box, but support in curl is too fragile (it segfaults, see linked issue).

We have to balance:
- seeing a perf downgrade for apps that might benefit from pushes
- vs putting every users at risk with a possible segfault when a server sends PUSH frames

Preventing this possible segfault is the most important here IMHO. Apps that leverage PUSH should be rare, and can re-enable if they really want to.

### CODE REVIEW

**Review by chalasr — APPROVED** [review]
👍 for disabling push by default (https://developer.chrome.com/blog/removing-push). No strong opinion about targeting 5.4 vs 7.2 but if it's broken then fine merging this as a bugfix.

**Review by stof — APPROVED** [review]

File: src/Symfony/Component/HttpClient/Tests/CurlHttpClientTest.php [hunk 1]
```diff
@@ -32,6 +32,10 @@ protected function getHttpClient(string $testCase): HttpClientInterface
             }
         }
 
+        if (str_contains($testCase, 'Push')) {
```
Comment (derrabus) [inline src/Symfony/Component/HttpClient/Tests/CurlHttpClientTest.php]: Isn't this the same condition as the one of the previous `if` block?

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpClient/Tests/CurlHttpClientTest.php]: ah indeed :)

**Review by derrabus — APPROVED** [review]
