### PR TITLE
[Console] Fix exit status on uncaught exception with negative code

### LINKED ISSUE #45850: [Console] Application can exit 0 following an uncaught exception with specific negative `code` values
### Symfony version(s) affected

At least v2+ through to HEAD

### Description

A symfony console application can unexpectedly exit with an exit status of `0` if:

* a command throws an uncaught exception
* the `code` property of that exception has been populated with a negative integer that is an exact multiple of 256.

Additionally, commands exit with a potentially unexpected status for any other negative code - for example an exception code of -2 produces an exit status of 254. However, these are still nonzero so do not fundamentally change the shell's understanding of whether the command failed. They may just make it harder to understand e.g. logging output unless the developer is familiar with the internal implementation & behaviour of POSIX exit codes.

This happens because in Application::run if `$e->getCode()` returns any numeric, nonzero, value then it will attempt to use this as an exit status: https://github.com/symfony/symfony/blob/56b428f1f89894b6c1163105e60c134d5f8d45ba/src/Symfony/Component/Console/Application.php#L157-L163

Later in that class, the exit code is clamped to a maximum value of 255, but there is no minimum constraint: https://github.com/symfony/symfony/blob/56b428f1f89894b6c1163105e60c134d5f8d45ba/src/Symfony/Component/Console/Application.php#L182-L188

Therefore any negative values will be passed directly to the php `exit()` function.

In POSIX, [only the least significant 8 bits of an exit status are made available when waiting for a child process](https://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html). Therefore:

| decimal exit | full binary | 8 LSB as decimal |
|-----------------|---------------|-------------------------|
| -1|1111 1111 **1111 1111** | 255|
| -2 | 1111 1111 **1111 1110** | 254|
| ...|...|...|
| -255 | 1111 1111 **0000 0001** | 1 |
| -256 | 1111 1111 **0000 0000** | **0** |
| -257 | 1111 1110 **1111 1111** | 255 |
|...|...|...|
|512| 1111 1110 **0000 0000** | **0**|
| ... |...etc ad infinitum... | ...|

Although PHP error codes are usually positive, it's relatively common in c-based software for them to be negative. 

We discovered the problem when trying to identify why our behat runs were occasionally "passing" despite a Chromium error causing the build to crash. It turned out when the driver threw an Exception, it was attaching the error code reported by Chrome, which happened to be `-32000` (a multiple of 256). PHP simply documents `Exception::$code` as an `int` - it does not specify positive/negative, so it appears this is a valid value as far as the exception is concerned, but not as an exit status.

### How to reproduce

Define a simple application:

```php
<?php
// invalid-exit.php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

require_once __DIR__.'/vendor/autoload.php';
$app = new Application();

class ThrowExceptionCommand extends Command
{
    protected static $defaultName = 'throw-exception';

    protected function configure()
    {
        $this->addOption('exitcode', NULL, InputOption::VALUE_REQUIRED);
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $code = (int) $input->getOption('exitcode');
        throw new \RuntimeException('Quitting with exit code '.$code, $code);
    }

}

$app->add(new ThrowExceptionCommand);

$app->run();
```

And a simple wrapper script
```bash
#!/bin/bash

for throw_code in {1..-300}
do
  php ./invalid-exit.php throw-exception --exitcode=$throw_code >/dev/null 2>&1
  actual_code=$?
  echo "Exception code $throw_code => exited $actual_code"
done
```

Then run the script. Observe the output will be:
```
Exception code 1 => exited 1
Exception code 0 => exited 1
Exception code -1 => exited 255
Exception code -2 => exited 254
... continues descending
Exception code -255 => exited 1
Exception code -256 => exited 0
Exception code -257 => exited 255
Exception code -258 => exited 254
... continues descending
```

### Possible Solution

There are two possible solutions.

IMO the best option would be to *only* use the code from the exception if it is a positive integer. However this may raise some BC concerns - although only for usecases that are likely to be extremely unusual. I will put together a PR based on this.

If that is unacceptable for compatibility then clamping values to `-255` in the same way as they are clamped to `255` would solve the success/failure status which is the biggest part of the issue.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by acoulton**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45850
| License       | MIT
| Doc PR        | N/A

As described in #45850, if an application threw an exception with the `code` property set to a negative number this could in some cases cause the process to appear to exit 'successfully' with a zero exit status. Exiting with any negative number produces potentially unexpected results - the reported exit status will not appear to match the value that was set. This is due to the binary handling / truncation of exit codes.

**This PR may theoretically break BC for applications that were intentionally throwing exceptions with negative codes and
performing some action based on that status.** However, given they would have had to implement an algorithm to map e.g. `-10` in PHP to `246` as the actual exit status, it seems unlikely this is a common usage.

IMO therefore applications using negative statuses are relying on an undocumented / incorrect implementation, and this is not a formal BC break.

I believe it is essentially safe to assume that exceptions with negative codes are e.g. being thrown by lower-level components, and are not intended to set a shell exit status.

Coalescing all negative numbers to 1 matches the existing behaviour with other 'invalid' exception codes e.g. empty / zero / non-numeric.

This therefore feels the most robust fix and eliminates any potential for confusion.

### CODE REVIEW

**Comment by acoulton** [comment]
It looks like appveyor failed on a network issue - I'm not sure how to make that retry - and the coding standards report is for existing content in the testcase that is not modified here.

File: src/Symfony/Component/Console/Tests/ApplicationTest.php [hunk 1]
```diff
@@ -1175,6 +1175,25 @@ public function testRunDispatchesExitCodeOneForExceptionCodeZero()
         $this->assertTrue($passedRightValue, '-> exit code 1 was passed in the console.terminate event');
     }
 
+    /**
+     * @testWith [-1]
+     *           [-32000]
+     */
+    public function testRunReturnsExitCodeOneForNegativeExceptionCode($exception_code)
```
Comment (fabpot) [inline src/Symfony/Component/Console/Tests/ApplicationTest.php]:
```suggestion
    public function testRunReturnsExitCodeOneForNegativeExceptionCode($exceptionCode)
```

**Review by fabpot — CHANGES_REQUESTED** [review]
Small CS issue but it looks good to me.

**Comment by fabpot** [comment]
As there is a potential behavior change (even if theoretical only), I would do the change on 6.1 instead and add a note in the CHANGELOG file to document the change.

**Comment by acoulton** [comment]
@fabpot the only issue with targeting 6.1 is we're currently still tied to 4.4 due to third-party dependencies.

As it stands our CI occasionally false-positives when in fact the process has crashed. We've now had two branches (that we know of) where code has been merged with failing tests that have not shown up till a later run. And more times it has occurred during work on a branch. Essentially we can't trust our green tick now, and have to check the output of every build. There may well be other users who have cron/CI/etc processes that are failing undetected. 

That feels like quite a significant bug. It is definitely higher impact than the possibility someone starts to see failures due to an unexpected but still nonzero exit code.

So it should really be fixed in the first supported version IMO.

If you're not happy to change all negative values in 4.4 then I think at least we should change anything `< -255`. Values lower than that are very clearly not valid exit codes, so changing them seems reasonable even in the older versions.

Then I could do a separate PR for 6.1 to apply this broader change to get rid of all negative values, which I think is best long-term.

What do you think?

**Comment by acoulton** [comment]
PS thank you for the quick weekend review!

**Comment by fabpot** [comment]
As you said, someone might rely on the current behavior. From my past experience, whenever we said that it was ok to merge something because there is 0 chance someone would have used the bad behavior, we had to revert because someone somewhere did rely on the behavior.

So, we have decided quite a while ago to not play this game anymore and always only merge bug fixes.

I know that this is frustrating, but we want to be on the safe side and try to minimize BC breaks as much as possible.

I hope you will understand our position.

**Comment by acoulton** [comment]
@fabpot ok fair enough for the general negative number case.

But surely nobody can be relying on `throw new Exception ('not really', -256)` (or -512 etc), allowing that to bubble out of their app and expecting that to terminate the app with an exit code of zero?

That is 100% a bug IMO - and a nasty one - and I can't see any valid reason not to fix it.

If you wanted to limit the behaviour change to the bare minimum then I suppose the fix could only change the specific -256,-512,... values that result in a zero. But that is very inconsistent with how you handle positive numbers >= 256.

**Comment by fabpot** [comment]
I must admit that you have a point here :)

Can you fix the CS issue so that I can merge it in 4.4.

**Comment by acoulton** [comment]
@fabpot thanks very much. Of course, I'll sort that when I'm back at my machine later on.

**Comment by kaznovac** [comment]
Negative error codes have unspecified (implementation/environment specific - in most cases it's modulo 256) behavior, only codes 0-255 are defined.

https://tldp.org/LDP/abs/html/exitcodes.html

So this is rather a bug fix rather than a BC.

**Comment by acoulton** [comment]
@fabpot thanks for spotting the CS issue I've corrected that now.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @acoulton.

**Comment by acoulton** [comment]
Thanks very much @fabpot
