### PR TITLE
[FrameworkBundle] not registered definitions must not be modified

### LINKED ISSUE #57294: Issue with "symfony/serializer" component on a clean Symfony installation
### Symfony version(s) affected

7.1, 7.0, 6.4

### Description

I have encountered an issue with the "symfony/serializer" component on a clean Symfony installation. After installing the component via Composer, an error is generated when clearing the cache. The error message is "You have requested a non-existent service "serializer.normalizer.object"."  

Interestingly, this error does not occur when the "symfony/security-bundle" package is installed.  

I am currently working on WSL with Ubuntu and Docker php:8.2-fpm.

### How to reproduce

I just installed Symfony using Composer and then the serializer component:

`composer create-project symfony/skeleton:"7.1.*" my_project_directory`

Followed by:

`composer require symfony/serializer`

### Possible Solution

_No response_

### Additional Context

image

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #57294
| License       | MIT

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -1854,19 +1854,21 @@ private function registerSerializerConfiguration(array $config, ContainerBuilder
             $container->setParameter('serializer.default_context', $defaultContext);
         }
 
-        $arguments = $container->getDefinition('serializer.normalizer.object')->getArguments();
-        $context = [];
+        if ($container->hasDefinition('serializer.normalizer.object')) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: `if (!` [...] return?

Comment (xabbuh) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: done

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.
