### PR TITLE
[FrameworkBundle] also deprecate the internal rate limiter factory alias

### LINKED ISSUE #60783: RateLimiterFactoryInterface alias - invalid deprecation
### Symfony version(s) affected

7.3.x

### Description

Hello!

It looks like this change https://github.com/symfony/symfony/pull/60171 has caused a trigger_deprecation when using RateLimiterFactoryInterface correctly with an alias.

### How to reproduce

Image

```php
public function test(RateLimiterFactoryInterface $testLimiter): Response
{
    return new Response('<html><body></body></html>');
}
```

result:

Image

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60783
| License       | MIT

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -3301,7 +3301,12 @@ private function registerRateLimiterConfiguration(array $config, ContainerBuilde
 
             if (interface_exists(RateLimiterFactoryInterface::class)) {
                 $container->registerAliasForArgument($limiterId, RateLimiterFactoryInterface::class, $name.'.limiter');
-                $factoryAlias->setDeprecated('symfony/dependency-injection', '7.3', 'The "%alias_id%" autowiring alias is deprecated and will be removed in 8.0, use "RateLimiterFactoryInterface" instead.');
+                $factoryAlias->setDeprecated('symfony/dependency-injection', '7.3', \sprintf('The "%%alias_id%%" autowiring alias is deprecated and will be removed in 8.0, use "%s $%s" instead.', RateLimiterFactoryInterface::class, (new Target($name.'.limiter'))->getParsedName()));
+                $internalAliasId = \sprintf('.%s $%s.limiter', RateLimiterFactory::class, $name);
+
+                if ($container->hasAlias($internalAliasId)) {
```
Comment (xabbuh) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:3308]: `registerAliasForArgument()` can register a second alias (that's what I call "internal alias" here): https://github.com/symfony/symfony/blob/ae30d7c04d249fd07758582d67fc5ea014363f9a/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L1475-L1477

**Comment by UtechtDustin** [comment]
I searched for a long time why that deprecation message was shown although i already used the RateLimiterFactoryInterface for autowiring.    
This PR seems fixing it, thanks @xabbuh.

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.
