### PR TITLE
[JsonPath] Better handling of unicode chars in expressions

### LINKED ISSUE #60665: [JsonPath] the JsonCrawler does not handle unicode escape sequences in JsonPath strings
### Symfony version(s) affected

7.3.0

### Description

JsonCrawler currently uses `stripcslashes` to resolve the escaping of keys in strings to get the actual string content: https://github.com/symfony/symfony/blob/v7.3.0/src/Symfony/Component/JsonPath/JsonCrawler.php#L233

However, the RFC9535 defines escape sequences for Unicode characters, inherited from the JSON syntax: https://www.rfc-editor.org/rfc/rfc9535#name-semantics-3

### How to reproduce

Write a JsonPath expression using unicode escape sequences.

### Possible Solution

For double-quoted strings, maybe relying on `json_decode` could work. But as we need to support single-quoted strings that are not supported in JSON, this might not be worth it.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60665
| License       | MIT

Handle all types of Unicode characters in expressions: control chars, surrogate, etc.

### CODE REVIEW

**Review by stof — APPROVED** [review]

File: src/Symfony/Component/JsonPath/JsonPathUtils.php [hunk 1]
```diff
@@ -85,4 +85,96 @@ public static function findSmallestDeserializableStringAndPath(array $tokens, mi
...
+                    case 'u':
+                        if ($i + 5 < $length) {
+                            $hex = substr($str, $i + 2, 4);
+                            if (ctype_xdigit($hex)) {
+                                $codepoint = hexdec($hex);
+
+                                if ($codepoint >= 0xD800 && $codepoint <= 0xDBFF && $i + 11 < $length) {
+                                    if ('\\' === $str[$i + 6] && 'u' === $str[$i + 7]) {
+                                        $lowHex = substr($str, $i + 8, 4);
+                                        if (ctype_xdigit($lowHex)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonPath/JsonPathUtils.php]: missing ctype polyfill in composer.json

File: src/Symfony/Component/JsonPath/JsonPathUtils.php [hunk 2]
```diff
@@ -85,4 +85,96 @@ public static function findSmallestDeserializableStringAndPath(array $tokens, mi
...
+                                            $lowSurrogate = hexdec($lowHex);
+                                            if ($lowSurrogate >= 0xDC00 && $lowSurrogate <= 0xDFFF) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonPath/JsonPathUtils.php]:
```suggestion
                                            if (0xDC00 <= $lowSurrogate && $lowSurrogate <= 0xDFFF) {
```

File: src/Symfony/Component/JsonPath/JsonPathUtils.php [hunk 3]
```diff
@@ -85,4 +85,96 @@ public static function findSmallestDeserializableStringAndPath(array $tokens, mi
             'tokens' => $remainingTokens,
         ];
     }
+
+    public static function unescapeString(string $str): string
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonPath/JsonPathUtils.php]: just wondering: would there be a way to use json_decode instead of having this method?

File: src/Symfony/Component/JsonPath/JsonPathUtils.php [hunk 4]
```diff
@@ -85,4 +85,96 @@ public static function findSmallestDeserializableStringAndPath(array $tokens, mi
...
+                    case 'r':
+                        $result .= "\r";
+                        $i++;
+                        break;
+                    case 't':
+                        $result .= "\t";
+                        $i++;
+                        break;
+                    case 'u':
+                        if ($i + 5 < $length) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonPath/JsonPathUtils.php]: nesting is deep here, I'm wondering if we couldn't use a match instead of a switch, and the `u` case, call a method instead, which would use early returns? `$i` passed by ref of course.

File: src/Symfony/Component/JsonPath/JsonPathUtils.php (hunk 3 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/JsonPath/JsonPathUtils.php]: maybe just for the "u" case?

Comment (stof) [reply src/Symfony/Component/JsonPath/JsonPathUtils.php]: JsonPath supports single-quoted strings, which are not supported in JSON.

Comment (stof) [reply src/Symfony/Component/JsonPath/JsonPathUtils.php]: JsonCrawler already tries to use `json_decode` for double-quoted strings before using that utility.

Comment (alexandre-daubois) [reply src/Symfony/Component/JsonPath/JsonPathUtils.php]: > JsonCrawler already tries to use json_decode for double-quoted strings before using that utility.

Maybe I should move this part also in JsonPathUtils so we have the whole unescaping logic at one place instead of trying something with `json_decode` somewhere then try manual unescape elsewhere

File: src/Symfony/Component/JsonPath/JsonPathUtils.php (hunk 4 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/JsonPath/JsonPathUtils.php]: Good idea, looks way better now

File: src/Symfony/Component/JsonPath/JsonPathUtils.php [hunk 5]
```diff
@@ -85,4 +85,82 @@ public static function findSmallestDeserializableStringAndPath(array $tokens, mi
...
+
+        $result = '';
+        $length = strlen($str);
+
+        for ($i = 0; $i < $length; $i++) {
+            if ('\\' === $str[$i] && $i + 1 < $length) {
+                $nextChar = $str[$i + 1];
+
+                match ($nextChar) {
+                    '"' => $result .= '"',
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonPath/JsonPathUtils.php]:
```suggestion
                $result .= match ($nextChar) {
                    '"' => '"',
```

File: src/Symfony/Component/JsonPath/JsonPathUtils.php [hunk 6]
```diff
@@ -85,4 +85,82 @@ public static function findSmallestDeserializableStringAndPath(array $tokens, mi
...
+
+        $hex = substr($str, $i + 2, 4);
+        if (!ctype_xdigit($hex)) {
+            // invalid hex, treat as literal
+            return $str[$i];
+        }
+
+        $codepoint = hexdec($hex);
+        // looks like a valid Unicode codepoint, string length is sufficient and it starts with \u
+        if (0xD800 <= $codepoint && 0xDBFF >= $codepoint && $i + 11 < $length && '\\' === $str[$i + 6] && 'u' === $str[$i + 7]) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonPath/JsonPathUtils.php]:
```suggestion
        if (0xD800 <= $codepoint && $codepoint <= 0xDBFF && $i + 11 < $length && '\\' === $str[$i + 6] && 'u' === $str[$i + 7]) {
```

Comment (alexandre-daubois) [reply src/Symfony/Component/JsonPath/JsonPathUtils.php]: Why don't we use Yoda style in this precise case? To emphasize we check a range?

Comment (nicolas-grekas) [reply src/Symfony/Component/JsonPath/JsonPathUtils.php]: yoda style is only about assignations

File: src/Symfony/Component/JsonPath/JsonPathUtils.php [hunk 7]
```diff
@@ -85,4 +85,82 @@ public static function findSmallestDeserializableStringAndPath(array $tokens, mi
...
+            $lowHex = substr($str, $i + 8, 4);
+            if (ctype_xdigit($lowHex)) {
+                $lowSurrogate = hexdec($lowHex);
+                if (0xDC00 <= $lowSurrogate && 0xDFFF >= $lowSurrogate) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonPath/JsonPathUtils.php]: improves reading :)
```suggestion
                if (0xDC00 <= $lowSurrogate && $lowSurrogate <= 0xDFFF) {
```

File: src/Symfony/Component/JsonPath/JsonPathUtils.php [hunk 8]
```diff
@@ -85,4 +85,82 @@ public static function findSmallestDeserializableStringAndPath(array $tokens, mi
...
+                    'f' => "\f",
+                    'n' => "\n",
+                    'r' => "\r",
+                    't' => "\t",
+                    'u' => self::unescapeUnicodeSequence($str, $length, $i),
+                    default => $str[$i], // keep the backslash
+                };
+
+                if ('u' !== $nextChar) {
+                    ++$i;
```
Comment (stof) [inline src/Symfony/Component/JsonPath/JsonPathUtils.php]: won't we be dropping the next char in the `default` branch due to advancing here ? Maybe we need `'\\' . $nextChar` in the `default` branch of the match.

File: src/Symfony/Component/JsonPath/JsonPathUtils.php [hunk 9]
```diff
@@ -85,4 +85,82 @@ public static function findSmallestDeserializableStringAndPath(array $tokens, mi
...
+                }
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonPath/JsonPathUtils.php]: the u case will need to increment one less
```suggestion
                ++$i;
```

File: src/Symfony/Component/JsonPath/Tests/JsonCrawlerTest.php [hunk 10]
```diff
@@ -404,6 +404,228 @@ public function testAcceptsJsonPath()
...
+                '$["new\nline"]',
+                ['with newline'],
+            ],
+            [
+                '$["quote\"here"]',
+                ['with quote'],
+            ],
+            [
+                '$["backslash\\\\here"]',
+                ['with backslash'],
```
Comment (stof) [inline src/Symfony/Component/JsonPath/Tests/JsonCrawlerTest.php:509]: All those cases should be added in the single-quote provider, so that our own logic is tested (as the double quotes will use `json_decode` now)

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/JsonPath/Tests/JsonCrawlerTest.php (hunk 10 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/JsonPath/Tests/JsonCrawlerTest.php:509]: Added to the data provider, thanks!

File: src/Symfony/Component/JsonPath/JsonPathUtils.php [hunk 11]
```diff
@@ -85,4 +85,80 @@ public static function findSmallestDeserializableStringAndPath(array $tokens, mi
             'tokens' => $remainingTokens,
         ];
     }
+
+    public static function unescapeString(string $str, string $quoteChar): string
+    {
+        if ('"' === $quoteChar) {
+            // try JSON decoding first for unicode sequences
+            $jsonStr = '"' . $str . '"';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonPath/JsonPathUtils.php]: looks like fabbot has an issue these days, it misses many small things like this one:
```suggestion
            $jsonStr = '"'.$str.'"';
```

File: src/Symfony/Component/JsonPath/JsonPathUtils.php [hunk 12]
```diff
@@ -85,4 +85,80 @@ public static function findSmallestDeserializableStringAndPath(array $tokens, mi
...
+            $decoded = json_decode($jsonStr, true);
+
+            if (null !== $decoded) {
+                return $decoded;
+            }
+        }
+
+        $result = '';
+        $length = strlen($str);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonPath/JsonPathUtils.php]: can you run php-cs-fixer on your side please, since fabbot is on holidays?
```suggestion
        $length = \strlen($str);
```

File: src/Symfony/Component/JsonPath/JsonPathUtils.php [hunk 13]
```diff
@@ -85,4 +85,80 @@ public static function findSmallestDeserializableStringAndPath(array $tokens, mi
...
+
+        for ($i = 0; $i < $length; $i++) {
+            if ('\\' === $str[$i] && $i + 1 < $length) {
+                $nextChar = $str[$i + 1];
+
+                $result .= match ($nextChar) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonPath/JsonPathUtils.php]:
```suggestion
                $result .= match ($str[$i + 1]) {
```

File: src/Symfony/Component/JsonPath/Tests/JsonCrawlerTest.php [hunk 14]
```diff
@@ -404,6 +404,260 @@ public function testAcceptsJsonPath()
...
+            ],
+            [
+                '$["\u65e5\u672c"]',
+                ['Japan'],
+            ],
+            [
+                '$["M\u00fcller"]',
+                [],
+            ],
+
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonPath/Tests/JsonCrawlerTest.php]:
```suggestion
```

File: src/Symfony/Component/JsonPath/Tests/JsonCrawlerTest.php [hunk 15]
```diff
@@ -404,6 +404,260 @@ public function testAcceptsJsonPath()
...
+            [
+                '$["apostrophe\'here"]',
+                ['with apostrophe'],
+            ],
+
+            [
+                '$["control\u0001char"]',
+                ['with control char'],
+            ],
+
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonPath/Tests/JsonCrawlerTest.php]: please review the CS :)
```suggestion
```

File: src/Symfony/Component/JsonPath/composer.json [hunk 16]
```diff
@@ -17,6 +17,7 @@
     ],
     "require": {
         "php": ">=8.2",
+        "symfony/polyfill-ctype": "~1.8",
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonPath/composer.json]:
```suggestion
        "symfony/polyfill-ctype": "^1.8",
```

**Comment by alexandre-daubois** [comment]
Ah yes, I relied a bit too much on fabbot and missed checks on CS. Sorry for the manual lint!

**Comment by nicolas-grekas** [comment]
Thank you @alexandre-daubois.
