### PR TITLE
[HttpKernel] Add support for configuring log level, and status code by exception class

### LINKED ISSUE #38901: Let's talk about Exception and Log
This issue is a bit long, and cover **two topics**, to please read it all before
commenting.

## 1️⃣ Do not log anymore 4XX exceptions

With a fresh Symfony (5.1) but it's the same for older version, all exceptions
are logged. It could be are at `error` level or at `critical` level.

I created a simple controller:

<details>

```php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Exception\BadRequestException;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Routing\Annotation\Route;

class HomepageController extends AbstractController
{
    /** @Route("/", name="homepage") */
    public function index(): Response
    {
        throw new BadRequestException();
    }

    /** @Route("/2", name="homepage_2") */
    public function index2(): Response
    {
        throw new BadRequestHttpException();
    }
}
```

</details>

And when I hit the application, I got the following log (prod env)

```
[2020-10-30T15:52:01.636868+01:00] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_route":"homepage","_controller":"App\\Controller\\HomepageController::index"},"request_uri":"https://127.0.0.1:8000/","method":"GET"} []
[2020-10-30T15:52:01.637921+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "" at /tmp/tmp/vendor/symfony/http-kernel/HttpKernel.php line 82 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0):  at /tmp/tmp/vendor/symfony/http-kernel/HttpKernel.php:82)\n[previous exception] [object] (Symfony\\Component\\HttpFoundation\\Exception\\BadRequestException(code: 0):  at /tmp/tmp/src/Controller/HomepageController.php:16)"} []

[2020-10-30T15:52:04.005203+01:00] request.INFO: Matched route "homepage_2". {"route":"homepage_2","route_parameters":{"_route":"homepage_2","_controller":"App\\Controller\\HomepageController::index2"},"request_uri":"https://127.0.0.1:8000/2","method":"GET"} []
[2020-10-30T15:52:04.009468+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "" at /tmp/tmp/src/Controller/HomepageController.php line 22 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0):  at /tmp/tmp/src/Controller/HomepageController.php:22)"} []
```

For recall, from the [monolog
documentation](https://github.com/Seldaek/monolog/blob/master/doc/01-usage.md#log-levels)

> ERROR (400): Runtime errors that do not require immediate action but should typically be logged and monitored.

So there is two things here:

* Symfony logged at the `error` level, meaning I should monitor this, and of
  course, *fix it*.
* My application decided to throw a 400. And 4XX are for **user errors**. This
  means my code is good, the request is not. => *There is nothing I can do to
  fix it*

**This is mismatch to me.**

This is even more obvious with 404's. This is why, in the past we introduced in
monolog the options `excluded_404s`.

And then we also add `excluded_http_codes` because, well, almost no one want
logs for 405, 403, 401, etc.

And there is also `activation_strategy` to have full control. This is what I use
in my application for ages. And I copy this code from projets to projects. Boring

So my proposable it to **not log at `error` level HTTP exceptions < 500**. We could
make it opt-in, but IMHO, this is a good default.

## 2️⃣ HttpException in the "model layer".

When we create controller, we have the power to manage exceptions handling, and
forge the response the use the status code we want.

But when we use third party code, like easy-admin, api-platform, etc, usually we
don't write the controller by ourself. So we can not really convert an exception
to a status code easily.

Api-platform offer us an option to convert exception instance to status code,
but I would like to go a bit further here.

First I'm not very confortable to throw `*HttpException` from
[symfony/http-kernel](https://github.com/symfony/symfony/tree/5.x/src/Symfony/Component/HttpKernel/Exception)
in my model layer. It does not sens when I use theses service in my commands, or
workers.

I would feel more natural to have "raw" exception, without a binding to the SAPI.
Something like:

* `NotFoundException`
* `ForbidenException`
* `InvalidInputException`
* etc

Symfony would, of course, convert a `NotFoundException` to a 404 when needed.

And now, we have a nice new error handlers (with serializer), so we could
easily throw raw exceptions, and have a nice handling. APIP could even remove
it's own handling from its codebase. Like:

* https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Validator/EventListener/ValidationExceptionListener.php
* https://github.com/api-platform/core/blob/master/src/EventListener/ExceptionListener.php
* etc

And we could also have a map of custom exception to status code (and a way to
enable log or not for such exception, see 1️⃣)

---

WDYT ?

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #38901
| License       | MIT
| Doc PR        |

Usage:

```yaml
# config/packages/framework.yaml
framework:
    exceptions:
        Symfony\Component\HttpKernel\Exception\BadRequestHttpException:
            log_level: debug
            status_code: 422
```

### CODE REVIEW

File: src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php [hunk 1]
```diff
@@ -32,19 +32,30 @@ class ErrorListener implements EventSubscriberInterface
...
         $this->debug = $debug;
+        $this->exceptionsMapping = $exceptionsMapping;
     }
 
     public function logKernelException(ExceptionEvent $event)
     {
-        $e = FlattenException::createFromThrowable($event->getThrowable());
+        $throwable = $event->getThrowable();
+        $logLevel = null;
+        foreach ($this->exceptionsMapping  as $exception => $config) {
```
Comment (Nyholm) [inline src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php]: Double space

```suggestion
        foreach ($this->exceptionsMapping as $exception => $config) {
```

Comment (Nyholm) [reply src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php]: Maybe even rename `$exception` to `$class`... But that is just a matter of taste.

I think it would be more readable that way.

File: src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php [hunk 2]
```diff
@@ -65,18 +76,25 @@ public function onKernelException(ExceptionEvent $event)
...
 
             $prev = new \ReflectionProperty($wrapper instanceof \Exception ? \Exception::class : \Error::class, 'previous');
             $prev->setAccessible(true);
-            $prev->setValue($wrapper, $exception);
+            $prev->setValue($wrapper, $throwable);
 
             throw $e;
         }
 
+        foreach ($this->exceptionsMapping  as $exception => $config) {
```
Comment (Nyholm) [inline src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php]: Same as above.

File: src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php [hunk 3]
```diff
@@ -65,18 +76,25 @@ public function onKernelException(ExceptionEvent $event)
...
+            if ($throwable instanceof $exception && $config['status_code']) {
+                $response->setStatusCode($config['status_code']);
+                break;
```
Comment (Nyholm) [inline src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php:94]: This means that the order you define the exceptions in your config is important. I don't mind, but this should be documented.

**Review by Nyholm — COMMENTED** [review]
Thank you for this PR. 

I think @derrabus made some really good arguments in https://github.com/symfony/symfony/issues/38901#issuecomment-719931014

I agree that updating logging level should be simpler.
I recognise that this is highly dependent on your app. (Think website vs API vs internal API)
Im not sure this is the best way forward. I appriciate the work and I realise it is not like me to ask for more discussion before merging a PR, but this time I would like to do that anyways. 

On the top of my head (not sure if it is good or bad, I just want to start thinking on alternative solutions). What if made some better integration with an "exception handler"? Ie create an `AbstractErrorListener` base class and let the default `ErrorHandler` extend from it. Now we can add config for "default error listener" and use normal PHP logic to decide what do do when an exception is called. 

hm..

**Comment by lyrixx** [comment]
@Nyholm yeah, I agree with @derrabus comment. That's why I did not change the current Symfony behavior. 

But now, everything is configurable, that's what many people want. 

About a solution in pure PHP to decide or not... I'm not really convinced. The solution I propose fit my needs and is simple to use. Do you have real use case where it does not fit and you would need PHP to configure it?

**Comment by lyrixx** [comment]
@Nyholm I have fixed your comments, thanks.

I think the PR is ready now

**Comment by lyrixx** [comment]
Hello @symfony/mergers 

The initial issue got 8 👍🏼, 4 ❤️  and, this PR got 5 ❤️ and @dunglas commented "A big +1 on my side." on the issue.

So without feedback, I'm planning to merge this PR by the end of the month, before the feature freeze.
If you are against it, it's time to raise your voice :)

**Review by fabpot — APPROVED** [review]
Can you start documenting this in docs?

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Comment by lyrixx** [comment]
> Can you start documenting this in docs?

I'll do that ASAP :)

**Comment by apfelbox** [comment]
It would have been nice to have system in place, to convert these exceptions in code, instead of just config. This way it might be possible to log for example a request to `/missing/url` as `error`, while `/favicon.ico` is not logged at all.

This way it's all or nothing.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 4]
```diff
@@ -1163,6 +1165,64 @@ private function addPhpErrorsSection(ArrayNodeDefinition $rootNode)
...
+                                    ->ifTrue(function ($v) use ($logLevels) { return !\in_array($v, $logLevels); })
+                                    ->thenInvalid(sprintf('The log level is not valid. Pick one among "%s".', implode('", "', $logLevels)))
+                                ->end()
+                                ->defaultNull()
+                            ->end()
+                            ->scalarNode('status_code')
+                                ->info('The status code of the response. Null to let Symfony decide.')
+                                ->validate()
+                                    ->ifTrue(function ($v) { return !\in_array($v, range(100, 499)); })
+                                    ->thenInvalid('The log level is not valid. Pick one among between 100 et 599.')
```
Comment (JohJohan) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:1215]: I think the invalid message is inconsistent with the check `range(100, 499)` while invalid message contains text like ` 100 et 599`

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:1215]: Can you please send a PR? Let's also replace this range() by two comparisons.

Comment (JohJohan) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:1215]: Check see: https://github.com/symfony/symfony/pull/43399

File: src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php [hunk 5]
```diff
@@ -65,18 +76,25 @@ public function onKernelException(ExceptionEvent $event)
...
             $prev->setAccessible(true);
-            $prev->setValue($wrapper, $exception);
+            $prev->setValue($wrapper, $throwable);
 
             throw $e;
         }
 
+        foreach ($this->exceptionsMapping as $exception => $config) {
+            if ($throwable instanceof $exception && $config['status_code']) {
+                $response->setStatusCode($config['status_code']);
```
Comment (theofidry) [inline src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php:93]: does this work? The response is rendered L71 before this happens so whilst the response will have the correct status code the page rendered may not be matching. For example the ErrorController will render a page for a 500 although the status code will be altered here

Comment (lyrixx) [reply src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php:93]: I don't undestant. The status code you write in the configuration is the one you want. 
It is not used to "match" something. It overrides the current value.

Comment (theofidry) [reply src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php:93]: >It overrides the current value

Of the created response.

In the case you are dealing with an API, you probably do not care. However, if you are dealing with an HTML response, then you probably have a different template if it's a 400 or a 500. From what I see here although you override the status code from a 500 to a 400 for example, the rendered page would still look like you had a 500 (and with the default template it shows the status code, i.e. 500).

Comment (yceruto) [reply src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php:93]: We might need to update `HtmlErrorRenderer` to take this new exceptions mapping into account.

**Comment by gnutix** [comment]
@lyrixx Is there any plan for this feature to cover errors handled in ErrorHandler ? In our app, because of huge exports of data, we may have either OutOfMemoryError or FatalError (with a message containing "Maximum execution", that represents timeouts) that we don't want to see logged with a "critical" level and have dedicated HTTP status codes (507 for OutOfMemory and 504 for timeouts). But using this mapping in the configuration for OutOfMemoryError doesn't change the criticality of the logged Fatal Error and I don't see how I could filter the FatalError only with the custom message.

**Comment by theofidry** [comment]
For what it's worth I did try to fix the issue found in https://github.com/symfony/symfony/pull/42244#discussion_r744841825 but could not. I can't say I'm too happy about it because it means the feature really doesn't work as advertised. But given the lack of solution the best that may be done at this point is to document it.

**Comment by yceruto** [comment]
@theofidry FYI this feature was adjusted here https://github.com/symfony/symfony/pull/44649, so your previous comment about the status code for HTML response/page should be ok now

**Comment by theofidry** [comment]
wow cool, thanks for the notif

**Comment by razvanalin** [comment]
I'm testing a feature to log the `Cars\Exceptions\CarsNotFoundException` exception as an **info** message with a 404 status code, but it's not working as expected.

This is my framework exception configuration:

```yaml
framework:
    exceptions:
        Cars\Exceptions\CarsNotFoundException:
            log_level: info
            status_code: 404
```

However, the logger is marking it as CRITICAL:

```php
[2024-01-05T11:51:44.155556+01:00] php.CRITICAL: Uncaught Exception: Not found car with id 9991057X1 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\HttpException(code: 0): Not found car with id 9991057X1 at /var/www/code/Cars/vendor/symfony/http-kernel/EventListener/ErrorListener.php:70)\n[previous exception] [object] (Cars\\Exceptions\\CarsNotFoundException(code: 404): Not found cars with id 9991057X1"} []
```

I want to configure the exception to log as **info** with a 404 status code. Currently, my code throws `Cars\Exceptions\CarsNotFoundException`, and the `kernel.exception` listener changes it to `Symfony\Component\HttpKernel\Exception\HttpException`. I don't want to log all `HttpException` instances as info, only the `CarsNotFoundException`

```yaml
framework:
    exceptions:
        Cars\Exceptions\CarsNotFoundException:
            log_level: info
            status_code: 404
        Symfony\Component\HttpKernel\Exception\HttpException:
            log_level: info
            status_code: 404
```

Can I achieve this without changing `HttpException` ?

Thank you.

**Comment by OskarStark** [comment]
Please open a new issue with the problem and add a reference to this PR, thanks
