### PR TITLE
[Validator] Make ConstraintValidatorTestCase compatible with PHPUnit 10

### LINKED ISSUE #49218: ConstraintValidatorTestCase and PHPUnit 10
### Symfony version(s) affected

all

### Description

When validating custom Constraints `Symfony\Component\Validator\Test\ConstraintValidatorTestCase` is used. 

During setup ConstraintValidatorTestCase is setting context by calling `MockBuilder::setMethods()` that was removed in PHPUnit 10 (see https://github.com/sebastianbergmann/phpunit/issues/3769 ).

### How to reproduce

Install PHPUnit 10 and write a custom validator test as explained in the [documentation](https://symfony.com/doc/current/validation/custom_constraint.html#testing-custom-constraints).

### Possible Solution

Check version of PHPUnit being used and replace a call to `MockBuilder::setMethods()` with `MockBuilder::onlyMethods()` if PHPUnit >= 10.0 is detected.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by gjuric**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49218
| License       | MIT

As explained in #49218 `MockBuilder::setMethods()` has been removed from PHPUnit 10 and replaced with `MockBuilder::onlyMethods()`. This change checks if `onlyMethods()` is defined and if not falls back to old version that uses `setMethods()`.

### CODE REVIEW

File: src/Symfony/Component/Validator/Test/ConstraintValidatorTestCase.php [hunk 1]
```diff
@@ -130,16 +130,22 @@ protected function createContext()
...
+        $contextualValidatorMockBuilder = $this->getMockBuilder(AssertingContextualValidator::class)
+            ->setConstructorArgs([$context]);
+        $contextualValidatorMethods = [
+            'atPath',
+            'validate',
+            'validateProperty',
+            'validatePropertyValue',
+            'getViolations',
+        ];
+        // PHPUnit 10 deprecated MockBuild::setMethods()
```
Comment (derrabus) [inline src/Symfony/Component/Validator/Test/ConstraintValidatorTestCase.php]:
```suggestion
        // PHPUnit 10 removed MockBuild::setMethods()
```

The deprecation happened in 9.something already.

**Review by derrabus — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @gjuric.
