### PR TITLE
[Cache] Fix support for Redis Sentinel using php-redis 6.0.0

### LINKED ISSUE #51678: RedisTrait is incompatible with PhpRedis 6.0 when using RedisSentinel and a DSN
### Symfony version(s) affected

6.3.x

### Description

[Version 6.0 of PhpRedis](https://github.com/phpredis/phpredis/blob/develop/CHANGELOG.md#600---2023-09-09-github-pecl) (ext-redis) got released a little over a week ago, and unfortunately the API of RedisSentinel changed such that it's no longer compatible with the way it's being constructed from `Symfony\Component\Cache\Traits\RedisTrait` when using a DSN. 
This will throw errors like:
```
{
 "class": "ArgumentCountError",
 "message": "RedisSentinel::__construct() expects at most 1 argument, 6 given",
 "code": 0,
 "file": "/var/www/html/vendor/symfony/cache/Traits/RedisTrait.php:228",
 "trace": [
  "/var/www/html/vendor/symfony/cache/Traits/RedisTrait.php:228",
  "/var/www/html/vendor/symfony/cache/Traits/Redis6Proxy.php:656",
  "/var/www/html/vendor/symfony/cache/Traits/RedisTrait.php:400",
  "/var/www/html/vendor/symfony/cache/Traits/AbstractAdapterTrait.php:195",
  "/var/www/html/vendor/symfony/cache-contracts/CacheTrait.php:44",
  "/var/www/html/vendor/symfony/cache/Traits/ContractsTrait.php:85",
  "/var/www/html/vendor/symfony/cache-contracts/CacheTrait.php:30",
  "/var/www/html/src/Momo/Application/Health/Controller/HealthController.php:28",
  "/var/www/html/vendor/symfony/http-kernel/HttpKernel.php:182",
  "/var/www/html/vendor/symfony/http-kernel/HttpKernel.php:76",
  "/var/www/html/vendor/symfony/http-kernel/Kernel.php:197",
  "/var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35",
  "/var/www/html/vendor/autoload_runtime.php:29",
  "/var/www/html/public/index.php:5"
 ]
}
```

The constructor of `RedisSentinel` is now synchronised with the one used in the `Redis` class:
https://github.com/phpredis/phpredis/commit/ebb2386e

Perhaps there are more compatibility issues, but we haven't run into them with just a single Redis Node, without sentinel on our dev environment.

### How to reproduce

Using a DSN like this causes problems:
```
parameters:
    redis_service: 'my-redis-service'
    redis_domain:  '%redis_service%-headless.redis.svc.cluster.local'
    redis_port:    26379
    redis_db:      0
    redis_dsn: >-
        redis:?
        host[%redis_service%-node-0.%redis_domain%:%redis_port%]&
        host[%redis_service%-node-1.%redis_domain%:%redis_port%]&
        host[%redis_service%-node-2.%redis_domain%:%redis_port%]&
        redis_sentinel=mymaster&
        dbindex=%redis_db%

framework:
    cache:
        default_redis_provider: '%redis_dsn%'
```

### Possible Solution

Support the new single parameter constructor for at least `RedisSentinel`, which is now synchronised with the `Redis` class implementation.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Qonstrukt**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #51678 
| License       | MIT

Added support for [php-redis 6.0.0](https://github.com/phpredis/phpredis/blob/develop/CHANGELOG.md#600---2023-09-09-github-pecl) to `Symfony/Component/Cache/Traits/RedisTrait`.

Made changes to how `RedisSentinel` is constructed, which now uses [the same constructor](https://github.com/phpredis/phpredis/commit/ebb2386e) as the main `Redis` class. Didn't find any other changes that might be relevant yet, but it's why I mention Redis Sentinel explicitly.

### CODE REVIEW

File: src/Symfony/Component/Cache/Traits/RedisTrait.php [hunk 1]
```diff
@@ -211,11 +212,28 @@ public static function createConnection(string $dsn, array $options = [])
...
-                    $extra = [];
-                    if (\defined('Redis::OPT_NULL_MULTIBULK_AS_NULL') && isset($params['auth'])) {
-                        $extra = [$params['auth']];
+
+                    if (version_compare(phpversion('redis'), '6.0.0') >= 0) {
+                        $options = [
+                            'host' => $host,
+                            'port' => $port,
+                            'connectTimeout' => $params['timeout'],
+                            'persistent' => $params['persistent_id'],
```
Comment (Qonstrukt) [inline src/Symfony/Component/Cache/Traits/RedisTrait.php:221]: There is no `connect` or `pconnect` call using `RedisSentinel`. So the decision of being persistent or not is being take by this value being `null` or set to a `string`. Not sure why it was converted to `string` before, but this works perfectly fine on my environment (without persistence) at least.

File: src/Symfony/Component/Cache/Traits/RedisTrait.php [hunk 2]
```diff
@@ -211,11 +212,27 @@ public static function createConnection(string $dsn, array $options = [])
                     if (!isset($params['redis_sentinel'])) {
                         break;
                     }
-                    $extra = [];
-                    if (\defined('Redis::OPT_NULL_MULTIBULK_AS_NULL') && isset($params['auth'])) {
-                        $extra = [$params['auth']];
+
+                    if (version_compare(phpversion('redis'), '6.0.0') >= 0) {
```
Comment (stof) [inline src/Symfony/Component/Cache/Traits/RedisTrait.php]: We generally use the signature of version_compare using 3 arguments (which passes an operator and returns a bool) as it makes the code easier to read (not having to remember which case returns 1 and which case returns -1)

**Comment by nicolas-grekas** [comment]
Thank you @Qonstrukt.
