### PR TITLE
[JsonStreamer] Fix missing generator for shared types in self-referencing objects

### LINKED ISSUE #63499: [JsonStreamer] Crash when serializing a class pointing to itself
### Symfony version(s) affected

7.4, 8.0

### Description

When generating PHP code to serialize an object that has a property of the same class, the generated code may contain calls to generators of other classes that have been removed from the final output. 

For example:
```php
return static function (mixed $data, \Psr\Container\ContainerInterface $valueTransformers, array $options): \Traversable {
    $generators['Loop'] = static function ($data, $depth) use ($valueTransformers, $options, &$generators) {
        /** Removed for clarity */
        yield from $generators['Leaf']($data->leaf, $depth + 1);
        /** Removed for clarity */
    };
    try {
        /** Removed for clarity */
        if (null !== $data->loop) {
            yield "{$prefix1}\"loop\":";
            yield from $generators['Loop']($data->loop, 1);
        }
        /** Removed for clarity */
    } catch (\JsonException $e) {
        /** Removed for clarity */
    }
};
```

The call on line 4 to `$generators['Leaf']` causes a `PHP Fatal error:  Uncaught Error: Value of type null is not callable `

### How to reproduce

```php
<?php
// First, run "composer require symfony/dependency-injection symfony/json-streamer"
// Then, execute this file

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\JsonStreamer\StreamWriterInterface;
use Symfony\Component\TypeInfo\Type;

class Leaf
{
    public float $a = 1;
    public float $b = 2;
}

class Loop
{
    public Leaf $leaf;
    public ?Loop $loop = null;

    public function __construct() {
        $this->leaf = new Leaf();
    }
}

class Wrapper
{
    public Leaf $leaf;
    public ?Loop $loop;

    public function __construct() {
        $this->leaf = new Leaf();
    }
}

$wrapper = new Wrapper();
$wrapper->loop = new Loop();
$wrapper->loop->loop = new Loop();

$container = new \Symfony\Component\DependencyInjection\Container();
$jsonStreamWriter = new \Symfony\Component\JsonStreamer\JsonStreamWriter(
    $container,
    new \Symfony\Component\JsonStreamer\Mapping\PropertyMetadataLoader(
        \Symfony\Component\TypeInfo\TypeResolver\TypeResolver::create()
    ),
    __DIR__."/generated/"
);

$json = $jsonStreamWriter->write($wrapper, Type::object(Wrapper::class));

foreach ($json as $chunk) {
    echo $chunk;
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63499
| License       | MIT

When a self-referencing type shares a property type with a sibling, the generated stream writer references an undefined generator (`Undefined array key` error at runtime).

The `$context` in `createDataModel()` is passed by value, so `generated_classes` isn't shared across sibling properties, which causing duplicate nodes instead of mocks. Additionally, `generateObjectGenerators()` skips mock registration for nodes already in `generated_generators`.

This is fixed by passing `$context` by reference and checking for mocks before the `generated_generators` early-return.

### CODE REVIEW

File: src/Symfony/Component/JsonStreamer/Write/StreamWriterGenerator.php [hunk 1]
```diff
@@ -151,13 +151,13 @@ private function createDataModel(Type $type, string $accessor, array $options =
         }
 
         if ($type instanceof CollectionType) {
-            ++$context['depth'];
+            $depth = ++$context['depth'];
```
Comment (stof) [inline src/Symfony/Component/JsonStreamer/Write/StreamWriterGenerator.php]: with the context passed by reference, this depth increment will also impact the caller after this method was called. Is this expected ? Or should we revert the depth in the context before returning ?

**Comment by nicolas-grekas** [comment]
Thank you @mtarld.
