### PR TITLE
[Workflow] Add support for weighted transitions

### LINKED ISSUE #60107: [Workflow] Unexpected marking with a complex workflow after transition
### Symfony version(s) affected

7.2

### Description

With a workflow that has simultaneous states that merge into a single state, the floowing transition produces an unexpected state.
```mermaid
graph LR;
    A-->|t1|B;
    A-->|t1|C;
    B-->|t2|D;
    C-->|t3|D;
    D-->|t4|E;
```
When t4 is applied, the subject has D and E in marking store.

### How to reproduce

Using the same subject class as the workflow tests
```php
<?php

declare(strict_types=1);

namespace App\Tests;

use PHPUnit\Framework\TestCase;
use Symfony\Component\Workflow\Definition;
use Symfony\Component\Workflow\MarkingStore\MethodMarkingStore;
use Symfony\Component\Workflow\Transition;
use Symfony\Component\Workflow\Workflow;

class MarkingTest extends TestCase
{
    public function testUnmarkWithComplexWorkflow(): void
    {
        $definition = $this->createComplexWorkflowDefinition();
        $subject = new Subject();
        $subject->setMarking(['a' => 1]);
        $workflow = new Workflow($definition, new MethodMarkingStore());

        $workflow->apply($subject, 't1');
        $workflow->apply($subject, 't2');
        $workflow->apply($subject, 't3');
        $workflow->apply($subject, 't4');
        $marking = $workflow->getMarking($subject);
        $this->assertTrue($marking->has('e'));
        $this->assertFalse($marking->has('d'));
    }

    private function createComplexWorkflowDefinition(): Definition
    {
        $places = range('a', 'e');

        $transitions = [];
        $transitions[] = new Transition('t1', 'a', ['b', 'c']);
        $transitions[] = new Transition('t2', 'b', 'd');
        $transitions[] = new Transition('t3', 'c', 'd');
        $transitions[] = new Transition('t4', 'd', 'e');

        return new Definition($places, $transitions);
    }
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | yes
| Issues        | Fix #60107
| License       | MIT

Allow to handle complex workflow like:

```yaml
make_table:
    transitions:
        start:
            from: init
            to:
                -   place: prepare_leg
                    weight: 4
                -   place: prepare_top
                    weight: 1
                -   place: stopwatch_running
                    weight: 1
        build_leg:
            from: prepare_leg
            to: leg_created
        build_top:
            from: prepare_top
            to: top_created
        join:
            from:
                - place: leg_created
                  weight: 4
                - top_created
                - stopwatch_running
            to: finished
```

```php
$definition = new Definition(
    [],
    [
        new Transition('start', 'init', [new Arc('prepare_leg', 4), 'prepare_top', 'stopwatch_running']),
        new Transition('build_leg', 'prepare_leg', 'leg_created'),
        new Transition('build_top', 'prepare_top', 'top_created'),
        new Transition('join', [new Arc('leg_created', 4), 'top_created', 'stopwatch_running'], 'finished'),
    ]
);

$subject = new Subject();
$workflow = new Workflow($definition);

$workflow->apply($subject, 'start');

$workflow->apply($subject, 'build_leg');
$workflow->apply($subject, 'build_top');
$workflow->apply($subject, 'build_leg');
$workflow->apply($subject, 'build_leg');
$workflow->apply($subject, 'build_leg');
$workflow->apply($subject, 'join');
```

---

Another example, based on https://demo-symfony-workflow.cleverapps.io/articles/show/1
[workflow.webm](https://github.com/user-attachments/assets/fe5a2fca-cfef-4621-94f9-98b7d9bb9a01)

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 1]
```diff
@@ -394,6 +394,8 @@ private function addWorkflowSection(ArrayNodeDefinition $rootNode): void
                                 ];
                             }
 
+                            // dd($v);
+
```
Comment (bkosun) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:398]:
```suggestion
```

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 2]
```diff
@@ -546,27 +548,80 @@ private function addWorkflowSection(ArrayNodeDefinition $rootNode): void
...
+                                                            ->integerNode('weight')
+                                                                ->isRequired()
+                                                            ->end()
+                                                        ->end()
+                                                    ->end()
+                                                ->end()
+                                                ->integerNode('weight')
+                                                    ->defaultValue(1)
+                                                    ->validate()
+                                                        ->ifTrue(fn ($v) => $v < 1)
```
Comment (bkosun) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]:
```suggestion
                                                        ->ifTrue(static fn ($v) => $v < 1)
```

File: src/Symfony/Component/Workflow/Transition.php [hunk 3]
```diff
@@ -39,18 +46,56 @@ public function getName(): string
...
+     * @deprecated since Symfony 7.3, use getFromArcs() instead
+     *
      * @return string[]
      */
     public function getFroms(): array
     {
-        return $this->froms;
+        trigger_deprecation('symfony/workflow', '7.3', 'Method "%s()" is deprecated, use "getFromArcs()" instead.', __METHOD__);
+
+        return array_map(fn (Arc $arc) => $arc->place, $this->fromArcs);
```
Comment (bkosun) [inline src/Symfony/Component/Workflow/Transition.php]:
```suggestion
        return array_map(static fn (Arc $arc) => $arc->place, $this->fromArcs);
```

File: src/Symfony/Component/Workflow/Transition.php [hunk 4]
```diff
@@ -39,18 +46,56 @@ public function getName(): string
...
+     * @deprecated since Symfony 7.3, use getFromArcs() instead
+     *
      * @return string[]
      */
     public function getTos(): array
     {
-        return $this->tos;
+        trigger_deprecation('symfony/workflow', '7.3', 'Method "%s()" is deprecated, use "getToArcs()" instead.', __METHOD__);
+
+        return array_map(fn (Arc $arc) => $arc->place, $this->toArcs);
```
Comment (bkosun) [inline src/Symfony/Component/Workflow/Transition.php]:
```suggestion
        return array_map(static fn (Arc $arc) => $arc->place, $this->toArcs);
```

File: src/Symfony/Component/Workflow/Tests/WorkflowTest.php [hunk 5]
```diff
@@ -12,8 +12,11 @@
 namespace Symfony\Component\Workflow\Tests;
 
 use PHPUnit\Framework\TestCase;
+use Symfony\Component\DependencyInjection\Tests\Compiler\D;
 use Symfony\Component\EventDispatcher\EventDispatcher;
+use Symfony\Component\Workflow\Arc;
 use Symfony\Component\Workflow\Definition;
+use Symfony\Component\Workflow\Dumper\GraphvizDumper;
```
Comment (bkosun) [inline src/Symfony/Component/Workflow/Tests/WorkflowTest.php]:
```suggestion

```

File: src/Symfony/Component/Workflow/Workflow.php [hunk 6]
```diff
@@ -11,6 +11,7 @@
 
 namespace Symfony\Component\Workflow;
 
+use Symfony\Component\DependencyInjection\Tests\Compiler\D;
```
Comment (bkosun) [inline src/Symfony/Component/Workflow/Workflow.php]:
```suggestion

```

File: src/Symfony/Component/Workflow/Tests/WorkflowTest.php [hunk 7]
```diff
@@ -12,8 +12,11 @@
 namespace Symfony\Component\Workflow\Tests;
 
 use PHPUnit\Framework\TestCase;
+use Symfony\Component\DependencyInjection\Tests\Compiler\D;
```
Comment (bkosun) [inline src/Symfony/Component/Workflow/Tests/WorkflowTest.php]:
```suggestion

```

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php (hunk 1 above)
Comment (bkosun) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]:
```suggestion

```

**Review by bkosun — CHANGES_REQUESTED** [review]

File: src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md [hunk 8]
```diff
@@ -25,7 +25,8 @@ CHANGELOG
  * Set `framework.rate_limiter.limiters.*.lock_factory` to `auto` by default
  * Deprecate `RateLimiterFactory` autowiring aliases, use `RateLimiterFactoryInterface` instead
  * Allow configuring compound rate limiters
-
+ * Add support for weighted transitions in workflows
+ *
```
Comment (bkosun) [inline src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md]:
```suggestion

```

**Review by bkosun — CHANGES_REQUESTED** [review]

**Comment by lyrixx** [comment]
@bkosun Thanks for the review. I addressed your comments

File: src/Symfony/Component/Workflow/Validator/StateMachineValidator.php [hunk 9]
```diff
@@ -24,18 +24,29 @@ public function validate(Definition $definition, string $name): void
...
             // Make sure that each transition has exactly one FROM
-            $froms = $transition->getFroms();
-            if (1 !== \count($froms)) {
-                throw new InvalidDefinitionException(\sprintf('A transition in StateMachine can only have one input. But the transition "%s" in StateMachine "%s" has %d inputs.', $transition->getName(), $name, \count($froms)));
+            $fromArcs = $transition->getFromArcs();
+            if (1 !== \count($fromArcs)) {
+                throw new InvalidDefinitionException(\sprintf('A transition in StateMachine can only have one input. But the transition "%s" in StateMachine "%s" has %d inputs.', $transition->getName(), $name, \count($fromArcs)));
+            }
+            foreach ($transition->getToArcs() as $arc) {
+                if (1 < $arc->weight) {
```
Comment (94noni) [inline src/Symfony/Component/Workflow/Validator/StateMachineValidator.php]: According to the ex message, should you compare with !== and not < ?

File: src/Symfony/Component/Workflow/Marking.php [hunk 10]
```diff
@@ -83,6 +83,11 @@ public function has(string $place): bool
         return isset($this->places[$place]);
     }
 
+    public function getTokenCount(string $place): int
+    {
+        return $this->places[$place] ?? 0;
```
Comment (94noni) [inline src/Symfony/Component/Workflow/Marking.php:92]: Perhaps add php doc for the « places » array shape ?

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/schema/symfony-1.0.xsd [hunk 11]
```diff
@@ -502,14 +502,22 @@
...
             <xsd:element name="metadata" type="metadata" minOccurs="0" maxOccurs="unbounded" />
             <xsd:element name="guard" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
         </xsd:sequence>
         <xsd:attribute name="name" type="xsd:string" use="required" />
     </xsd:complexType>
 
+    <xsd:complexType name="arc">
+        <xsd:simpleContent>
+            <xsd:extension base="xsd:string">
+                <xsd:attribute name="weight" type="xsd:integer" use="optional" />
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/schema/symfony-1.0.xsd]: `use="optional"` is the default and we generally don't put it explicitly in our schemas

File: src/Symfony/Component/Workflow/Transition.php [hunk 12]
```diff
@@ -39,18 +46,56 @@ public function getName(): string
...
+    {
+        if ($arc instanceof Arc) {
+            return $arc;
+        }
+
+        if (is_string($arc)) {
+            return new Arc($arc, 1);
+        }
+
+        throw new \InvalidArgumentException(sprintf('The type of arc is invalid. Expected string or Arc, got "%s".', get_debug_type($arc)));
```
Comment (stof) [inline src/Symfony/Component/Workflow/Transition.php]: I suggest using `TypeError` so that we get the same error type than if we use a parameter type `Arc|string` in the future

**Comment by lyrixx** [comment]
Thanks for the review, I addressed your comments, and also rebased.

**Comment by lyrixx** [comment]
I don't get why the tests are broken:
```
4) Symfony\Bundle\FrameworkBundle\Tests\DependencyInjection\YamlFrameworkExtensionTest::testWorkflowAreValidated
Failed asserting that exception of type "ReflectionException" matches expected exception "Symfony\Component\Workflow\Exception\InvalidDefinitionException". Message was: "Class "Symfony\Component\Workflow\Arc" does not exist" at
```

since I put
```json
  "require-dev": {
      "symfony/workflow": "^7.4|^8.0",
```
in `src/Symfony/Bundle/FrameworkBundle/composer.json`

File: src/Symfony/Component/Workflow/Marking.php [hunk 13]
```diff
@@ -18,7 +18,11 @@
  */
 class Marking
 {
+    /**
+     * @var array<string, int> Keys are the place names and values are the number of tokens in that place
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Workflow/Marking.php]:
```suggestion
     * @var array<string, int<0,max>> Keys are the place names and values are the number of tokens in that place
```

File: src/Symfony/Component/Workflow/Transition.php [hunk 14]
```diff
@@ -39,18 +46,56 @@ public function getName(): string
     }
 
     /**
+     * @deprecated since Symfony 7.4, use getFromArcs() instead
+     *
      * @return string[]
      */
     public function getFroms(): array
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Workflow/Transition.php]: I'm not a big fan of deprecating `getFroms()`. This feels like a new and more advanced concern leaking into simple use cases.
Instead, what about doing this?

```suggestion
    public function getFroms(/* bool $weighted = false*/): array
```

When `$weighted` is true, we return the places as keys and their weight as values.
Would that work? If yes, we could even remove the `Arc` class and do this with arrays only, for simplicity.

**Review by nicolas-grekas — COMMENTED** [review]
Rebase needed + some thoughts.

File: src/Symfony/Component/Workflow/Transition.php (hunk 14 above)
Comment (lyrixx) [reply src/Symfony/Component/Workflow/Transition.php]: Arc class is important to me. Class are much better than array:
* consume less memory
* better property (key) discoverabiliy
* doesn't need extra PHPDoc
* better handling by static analysis.

**Comment by lyrixx** [comment]
Comment addressed, an PR rebased

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 15]
```diff
@@ -578,9 +578,45 @@ private function addWorkflowSection(ArrayNodeDefinition $rootNode): void
                                                         ->ifArray()
                                                         ->then(static fn ($from) => array_map(static fn ($v) => $v instanceof \BackedEnum ? $v->value : $v, $from))
                                                     ->end()
+                                                    ->beforeNormalization()
+                                                        ->always()
+                                                        ->then($workflowNormalizeArcs = static function ($arcs) {
+                                                            $arcs = (array) $arcs;
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: acceptAndWrap() above already did the cast:
```suggestion
                                                        ->ifArray()
                                                        ->then($workflowNormalizeArcs = static function ($arcs) {
```

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 16]
```diff
@@ -578,9 +578,45 @@ private function addWorkflowSection(ArrayNodeDefinition $rootNode): void
...
+
+                                                            // Fix XML parsing, when only one arc is defined
+                                                            if (array_key_exists('weight', $arcs) && array_key_exists('value', $arcs)) {
+                                                                $arcs = [$arcs];
+                                                            }
+
+                                                            foreach ($arcs as $k => $arc) {
+                                                                if (is_int($k) && is_string($arc)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: what if $k is a string?

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 17]
```diff
@@ -578,9 +578,45 @@ private function addWorkflowSection(ArrayNodeDefinition $rootNode): void
...
+                                                                    $arcs[$k] = [
+                                                                        'place' => $arc,
+                                                                        'weight' => 1,
+                                                                    ];
+                                                                } else if (array_key_exists('weight', $arc) && array_key_exists('value', $arc)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: what if $arc is not an array?

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 18]
```diff
@@ -578,9 +578,45 @@ private function addWorkflowSection(ArrayNodeDefinition $rootNode): void
...
+                                                                    // Fix XML parsing
+                                                                    $arcs[$k] = [
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: instead of patching $arcs in place, would it be more readable to populate a new $normalizedArcs?
we did so for places and transitions recently and that lead to better code (and fixed cases)

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 19]
```diff
@@ -590,9 +626,28 @@ private function addWorkflowSection(ArrayNodeDefinition $rootNode): void
                                                         ->ifArray()
                                                         ->then(static fn ($to) => array_map(static fn ($v) => $v instanceof \BackedEnum ? $v->value : $v, $to))
                                                     ->end()
+                                                    ->beforeNormalization()
+                                                        ->always()
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: new best practice: be more specific, so that the normalization can fail on its own when an unexpected type is met (together with acceptAndWrap() to accept some types:
```suggestion
                                                        ->ifArray()
```

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 20]
```diff
@@ -590,9 +626,28 @@ private function addWorkflowSection(ArrayNodeDefinition $rootNode): void
...
+                                                            ->integerNode('weight')
+                                                                ->isRequired()
+                                                            ->end()
+                                                        ->end()
+                                                    ->end()
+                                                ->end()
+                                                ->integerNode('weight')
+                                                    ->defaultValue(1)
+                                                    ->validate()
+                                                        ->ifTrue(static fn (int $v): bool => $v < 1)
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]:
```suggestion
                                                        ->ifTrue(static fn ($v) =>$v < 1)
```

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 21]
```diff
@@ -1114,6 +1115,14 @@ private function registerWorkflowConfiguration(array $config, ContainerBuilder $
             // Global transition counter per workflow
             $transitionCounter = 0;
             foreach ($workflow['transitions'] as $transition) {
+                foreach (['from', 'to'] as $direction) {
+                    foreach ($transition[$direction] as $k => $arc) {
+                        $transition[$direction][$k] = new Definition(Arc::class, [
+                            '$place' => $arc['place'],
+                            '$weight' => $arc['weight'] ?? 1,
+                        ]);
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: let's save on reflection:
```suggestion
                        $transition[$direction][$k] = new Definition(Arc::class, [$arc['place'], $arc['weight'] ?? 1]);
```

File: src/Symfony/Component/Workflow/Dumper/MermaidDumper.php [hunk 22]
```diff
@@ -122,12 +123,15 @@ public function dump(Definition $definition, ?Marking $marking = null, array $op
...
     }
 
-    private function preparePlace(int $placeId, string $placeName, array $meta, bool $isInitial, bool $hasMarking): array
+    private function preparePlace(int $placeId, string $placeName, array $meta, bool $isInitial, bool $hasMarking, int $tokenCount): array
     {
         $placeLabel = $placeName;
         if (\array_key_exists('label', $meta)) {
             $placeLabel = $meta['label'];
         }
+        if ($tokenCount > 1) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Workflow/Dumper/MermaidDumper.php]:
```suggestion
        if (1 < $tokenCount) {
```

File: src/Symfony/Component/Workflow/Tests/TransitionTest.php [hunk 23]
```diff
@@ -11,16 +11,50 @@
...
+    public static function provideConstructorTests(): iterable
     {
-        $transition = new Transition('name', 'a', 'b');
+        yield 'plain strings' => ['a', 'b'];
+        yield 'array of strings' => [['a'], ['b']];
+        yield 'array of arcs' => [[new Arc('a', 1)], [new Arc('b', 1)]];
+    }
+
+    /**
+     * @dataProvider provideConstructorTests
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Workflow/Tests/TransitionTest.php]: should be removed

File: src/Symfony/Component/Workflow/Tests/TransitionTest.php [hunk 24]
```diff
@@ -11,16 +11,50 @@
 
 namespace Symfony\Component\Workflow\Tests;
 
+use PHPUnit\Framework\Attributes\DataProvider;
 use PHPUnit\Framework\TestCase;
+use Symfony\Component\Workflow\Arc;
 use Symfony\Component\Workflow\Transition;
 
+
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Workflow/Tests/TransitionTest.php]: 👻

File: src/Symfony/Component/Workflow/Arc.php [hunk 25]
```diff
@@ -0,0 +1,30 @@
...
+ * @author Grégoire Pineau <lyrixx@lyrixx.info>
+ */
+final readonly class Arc
+{
+    public function __construct(
+        public string $place,
+        public int $weight,
+    ) {
+        if ($weight < 1) {
+            throw new \InvalidArgumentException(\sprintf('The weight must be greater than 0, "%s" given.', $weight));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Workflow/Arc.php]:
```suggestion
            throw new \InvalidArgumentException(\sprintf('The weight must be greater than 0, %d given.', $weight));
```

File: src/Symfony/Component/Workflow/Transition.php [hunk 26]
```diff
@@ -39,18 +46,40 @@ public function getName(): string
     }
 
     /**
-     * @return string[]
+     * @return $asArc is false ? array<Arc> : array<string>
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Workflow/Transition.php]:
```suggestion
     * @return $asArc is true ? array<Arc> : array<string>
```

File: src/Symfony/Component/Workflow/Transition.php [hunk 27]
```diff
@@ -39,18 +46,40 @@ public function getName(): string
...
      */
-    public function getFroms(): array
+    public function getFroms(/* bool $asArc = false*/): array
     {
-        return $this->froms;
+        if (1 <= \func_num_args() && func_get_arg(0)) {
+            return $this->fromArcs;
+        }
+
+        return array_map(static fn (Arc $arc): string => $arc->place, $this->fromArcs);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Workflow/Transition.php]:
```suggestion
        return array_column($this->fromArcs, 'place');
```

File: src/Symfony/Component/Workflow/Transition.php [hunk 28]
```diff
@@ -39,18 +46,40 @@ public function getName(): string
...
     }
 
     /**
-     * @return string[]
+     * @return $asArc is false ? array<Arc> : array<string>
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Workflow/Transition.php]:
```suggestion
     * @return $asArc is true ? array<Arc> : array<string>
```

File: src/Symfony/Component/Workflow/Transition.php [hunk 29]
```diff
@@ -39,18 +46,40 @@ public function getName(): string
...
      */
-    public function getTos(): array
+    public function getTos(/* bool $asArc = false*/): array
     {
-        return $this->tos;
+        if (1 <= \func_num_args() && func_get_arg(0)) {
+            return $this->toArcs;
+        }
+
+        return array_map(static fn (Arc $arc): string => $arc->place, $this->toArcs);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Workflow/Transition.php]:
```suggestion
        return array_column($this->toArcs, 'place');
```

File: src/Symfony/Component/Workflow/Transition.php [hunk 30]
```diff
@@ -39,18 +46,40 @@ public function getName(): string
...
+    }
+
+    // No type hint for $arc to avoid implicit cast
+    private function normalize(mixed $arc): Arc
+    {
+        if ($arc instanceof Arc) {
+            return $arc;
+        }
+
+        if (is_string($arc)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Workflow/Transition.php]:
```suggestion
        if (\is_string($arc)) {
```

File: src/Symfony/Component/Workflow/Transition.php [hunk 31]
```diff
@@ -39,18 +46,40 @@ public function getName(): string
...
+            return new Arc($arc, 1);
+        }
+
+        throw new \TypeError(sprintf('The type of arc is invalid. Expected string or Arc, got "%s".', get_debug_type($arc)));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Workflow/Transition.php]:
```suggestion
        throw new \TypeError(\sprintf('The type of arc is invalid. Expected string or Arc, got "%s".', get_debug_type($arc)));
```

File: src/Symfony/Component/Workflow/Workflow.php [hunk 32]
```diff
@@ -387,7 +387,7 @@ private function entered(object $subject, ?Transition $transition, Marking $mark
 
         $placeNames = [];
         if ($transition) {
-            $placeNames = $transition->getTos();
+            $placeNames = array_map(static fn (Arc $arc): string => $arc->place, $transition->getTos(true));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Workflow/Workflow.php]:
```suggestion
            $placeNames = array_column($transition->getTos(true), 'place');
```

**Review by nicolas-grekas — APPROVED** [review]
LGTM after some CS fixes

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php (hunk 16 above)
Comment (lyrixx) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: People are searching for troubles 😅 
I added add a check, and throw an exception if it's the case.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php (hunk 17 above)
Comment (lyrixx) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: same, the code throw an exception now

**Comment by nicolas-grekas** [comment]
Thank you @lyrixx.

**Comment by xabbuh** [comment]
@lyrixx Looking at how we use `getFroms()`/`getTos()` I wonder if the idea was to deprecate the argument in 8.1+ and let both methods only return list of `Arc` instances in 9.0?

**Comment by lyrixx** [comment]
🤔 I don't remember why I did that! I guess I wanted to deprecate things at some point.

Now, I don't think it worth a deprecated. I would open a PR to add real args. What do you think ?

**Comment by xabbuh** [comment]
I was basically wondering because there are now different places where call these methods with `true` and afterwards only extract the place so we could as well have left those places untouched.
