### PR TITLE
Fix SessionTokenStorage reuse with Request

### LINKED ISSUE #41757: [Security] Validating a CSRF token in the test environment doesn't work
**Symfony version(s) affected**: 5.3

**Description**

Generating a CSRF token in a test and check if it is valid doesn't work.
> Test
```php
$client = self::createClient();
$token = self::getContainer()->get('security.csrf.token_manager')->getToken('id')->getValue();
$client->request('POST', '/test', ['token' => $token]);
self::assertSame('valid', $client->getResponse()->getContent());
```
> Controller
```php
/**
 * @Route("/test")
 */
public function __invoke(Request $request): Response
{
    $tokenValid = $this->isCsrfTokenValid('id', $request->request->get('token'));

    return new Response($tokenValid ? 'valid' : 'invalid');
}
```

**How to reproduce**

[Reproducer](https://github.com/YaFou/symfony-csrf-test)

**Possible Solution**

I will search one and open a PR if needed

**Additional context**

Is related to #41046

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41757
| License       | MIT
| Doc PR        | -

When the CsrfTokenManager is used BEFORE a request is sent, the `SessionTokenStorage` creates a fake session to stores the token.
But if the Storage is, then, called with a real request, the fake session is not used anymore. This is an issue for people using CSRF tests in tests. Asm they are not able to use the `security.csrf.token_manager` service.

### CODE REVIEW

File: src/Symfony/Component/Security/Csrf/TokenStorage/SessionTokenStorage.php [hunk 1]
```diff
@@ -34,7 +34,7 @@ class SessionTokenStorage implements ClearableTokenStorageInterface
     private $requestStack;
     private $namespace;
     /**
-     * Tp be remove in Symfony 6.0
+     * Tp be remove in Symfony 6.0.
```
Comment (chalasr) [inline src/Symfony/Component/Security/Csrf/TokenStorage/SessionTokenStorage.php]:
```suggestion
     * To be remove in Symfony 6.0.
```

Comment (nicolas-grekas) [reply src/Symfony/Component/Security/Csrf/TokenStorage/SessionTokenStorage.php]: s/remove/removed also

**Review by chalasr — APPROVED** [review]
A test case would be nice though.

**Comment by jderusse** [comment]
tests added

**Comment by jderusse** [comment]
tests added

**Review by derrabus — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jderusse.
