### PR TITLE
[Mailer] [Amazon] Add support for custom headers in ses+api

### LINKED ISSUE #45168: [Mailer/AWS] Custom headers aren't transmitted
### Symfony version(s) affected

5.4.2

### Description

When trying to send a custom header towards AWS using the AsyncAws implementation custom headers aren't included.
This seems to be due to the usage of the `Simple` message format that doesn't seem to allow for custom headers:
https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendEmail.html

Upon printing the Api request the headers are nowhere to be found either. 

### How to reproduce

Add a header to the mail via:
`$message->getHeaders()->addTextHeader('x-test', 'test'));`
and send it using the `ses+api` DSN

### Possible Solution

There seems to be a `Raw` message format you can send that allows for custom headers so the package should probably use that.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by StudioMaX**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Issues        | Fix #45168 
| License       | MIT

Until recently it was not possible to add custom headers when using AWS SES API with `Simple` mode, see #45168.
This problem is also mentioned in Mailer's docs:
> If you send custom headers when using the [Amazon SES](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Mailer/Bridge/Amazon/README.md) transport (to receive them later via a webhook), make sure to use the ses+https provider because it's the only one that supports them.

However, changes have been made to the SendEmail API and now this will be possible from approximately 2024/03/05.
References:
https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendEmail.html
https://awsapichanges.com/archive/changes/539fb6-email.html

In this change I add all custom headers to the request, excluding the standard ones, similar to other transports.

Example:
```php
$mail->getHeaders()->addTextHeader('X-Custom-Header', 'foobar');
```

### CODE REVIEW

File: src/Symfony/Component/Mailer/Bridge/Amazon/Transport/SesApiAsyncAwsTransport.php [hunk 1]
```diff
@@ -107,6 +108,14 @@ protected function getRequest(SentMessage $message): SendEmailRequest
             $request['FeedbackForwardingEmailAddress'] = $email->getReturnPath()->toString();
         }
 
+        if ($customHeaders = $this->getCustomHeaders($email->getHeaders())) {
+            if (\count($customHeaders) > 15) {
```
Comment (fabpot) [inline src/Symfony/Component/Mailer/Bridge/Amazon/Transport/SesApiAsyncAwsTransport.php]: I think we're doing such validation anywhere else as the provider will throw an error anyway.
Also, if the count changes to something else in the future, having the limit hardcoded here would be problematic (and we don't want to monitor such third-party changes).

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Mailer/Bridge/Amazon/Transport/SesApiAsyncAwsTransport.php (hunk 1 above)
Comment (StudioMaX) [reply src/Symfony/Component/Mailer/Bridge/Amazon/Transport/SesApiAsyncAwsTransport.php]: Done, removed this validation.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @StudioMaX.
