### PR TITLE
[Validator] Add Validation::createIsValidCallable() that returns a boolean instead of exception

### LINKED ISSUE #36820: [RFC][OptionsResolver] Constraints
**Description**  
OptionConfigurator would have new method `checkConstraints(Constraint[] $constraints)`. User can set validation constraints that will be checked by OptionResolver. 
Similar like form fields can have constraints.
In OptionsResolver would be new method `addConstraints(string $option, Constraint[] $constraints)` and resolve() would be created Validator a validate all options.

**Example**  

```php
$resolver = new OptionsResolver();
$resolver->define('email')
    ->required()
    ->allowedTypes('string')
    ->checkConstraints([
        new Assert\NotBlank(),
        new Assert\Email(),
    ]);

$resolver->resolve(['email' => 'invalidEmail']);
// resolve would throw InvalidOptionsException with ConstraintViolationListInterface
```

### PR DESCRIPTION
**Pull request by wouterj**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #36820
| License       | MIT
| Doc PR        | tbd

This adds a `Validator::createValidCallable()` (I'm very open for other name suggestions) that returns a boolean instead of exceptions. This allows usingit in places where booleans are expected, for instance in the referenced OptionsResolver case:

```php
$resolver->setAllowedValues('name', Validation::createValidCallable(
    new Assert\Length(['min' => 10 ])
));
```

### CODE REVIEW

File: src/Symfony/Component/OptionsResolver/OptionsResolver.php [hunk 1]
```diff
@@ -1038,13 +1039,18 @@ public function offsetGet($option, bool $triggerDeprecation = true)
...
+                    try {
+                        if (!$allowedValue($value)) {
+                            // Don't include closures in the exception message
+                            continue;
+                        }
+
                         $success = true;
                         break;
+                    } catch (ValidationFailedException $e) {
+                        // Don't include closures in the exception message
```
Comment (stof) [inline src/Symfony/Component/OptionsResolver/OptionsResolver.php]: If you keep the `if (!$allowedValue($value)) {` condition, you could avoid duplicating the comment and the `continue`, by keeping it after the try/catch.

**Comment by jvasseur** [comment]
I'm not fond of creation a special case in the option resolver component like this.

Maybe we could instead create a new `Validation::createValidCallable` (or another name) method that returns a boolean instead of throwing which could be useful for more cases that just passing it to the option resolver

**Comment by stof** [comment]
I tend to agree with @jvasseur here. That sounds like a better approach

**Comment by yceruto** [comment]
I agree with @jvasseur too.

**Comment by wouterj** [comment]
I agree, I'll update the PR later today.

**Comment by wouterj** [comment]
PR updated. Thanks @jvasseur for the great suggestion!

File: src/Symfony/Component/Validator/CHANGELOG.md [hunk 2]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+5.3
+---
+
+ * add `Validator::createValidClosure()` that returns true/false instead of throwing exceptions
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/CHANGELOG.md]: Add :)

File: src/Symfony/Component/Validator/Validation.php [hunk 3]
```diff
@@ -49,6 +49,26 @@ public static function createCallable($constraintOrValidator = null, Constraint
...
+    /**
+     * Creates a callable that returns true/false instead of throwing validation exceptions.
+     *
+     * @param Constraint|ValidatorInterface|null $constraintOrValidator
+     */
+    public static function createValidCallable($constraintOrValidator = null, Constraint ...$constraints): callable
+    {
+        $validator = self::createCallable(...func_get_args());
+
+        return static function ($value) use ($validator) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Validation.php]: shouldn't we accept `&$e = null` as extra argument, to allow getting the error?

Comment (ro0NL) [reply src/Symfony/Component/Validator/Validation.php]: i think this allows reverse logic as well,

`createValidatorCallable => bool`
`createCallable => throw`

the latter can obtain the exception then (the _validation_ callable uses the _validator_ callable IMHO)

Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/Validation.php]: Maybe we could even add `&$violations` instead, and then we wouldn't have to rely on signaling by exception here: `createCallable` would call `createValidCallable`. Makes sense?

Comment (stof) [reply src/Symfony/Component/Validator/Validation.php]: to me, if you need the details, you should not be using the one returning a boolean. this callable is meant to provide an easy integrations with places like the OptionsResolver expecting a boolean anyway, which won't care about the exception returned by reference in an argument.
Btw, reference-based returned values in an argument are harder to discover.

File: src/Symfony/Component/Validator/Validation.php [hunk 4]
```diff
@@ -49,6 +49,26 @@ public static function createCallable($constraintOrValidator = null, Constraint
...
     }
 
+    /**
+     * Creates a callable that returns true/false instead of throwing validation exceptions.
+     *
+     * @param Constraint|ValidatorInterface|null $constraintOrValidator
+     */
+    public static function createValidCallable($constraintOrValidator = null, Constraint ...$constraints): callable
+    {
+        $validator = self::createCallable(...func_get_args());
```
Comment (stof) [inline src/Symfony/Component/Validator/Validation.php]: I suggest using `self::createCallable($constraintOrValidator, ...$constraints)`

File: src/Symfony/Component/Validator/Validation.php (hunk 3 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/Validation.php]: I'd still prefer removing signaling by exception...

Comment (stof) [reply src/Symfony/Component/Validator/Validation.php]: well, then maybe we should not build one of the callables on top of the other one, but make both callables (the one triggering an exception and the one returning a boolean) call the validator API for their need.

Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/Validation.php]: the reference isn't bad per se :)

Comment (stof) [reply src/Symfony/Component/Validator/Validation.php]: well, in internal code, we can do what we want. But the returned callables are a public API

Comment (ro0NL) [reply src/Symfony/Component/Validator/Validation.php]: or we just dup the bit of logic :)

Comment (ro0NL) [reply src/Symfony/Component/Validator/Validation.php]: what's important to me is; a validator vs. the validation. A "valid callable" isnt a thing IMHO,

Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/Validation.php]: I mean: having the reference as part if the public API would be useful to me (and also for internal needs if course, that's the proof of usefulness :))

Comment (stof) [reply src/Symfony/Component/Validator/Validation.php]: To me, if you need access to the violations, you should be using `$validator->validate()` directly instead of wrapping it in such callable.

Comment (ro0NL) [reply src/Symfony/Component/Validator/Validation.php]: i tend to agree with @stof

```
try { createCallablle()('x') } 
catch (ValidationFailedException $e) { $e->getViolations() }
```

already works

Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/Validation.php]: I understand that you both have a preference, but I don't see why we shouldn't add the reference.
It makes the API more useful, with no downside.

**Comment by javiereguiluz** [comment]
@wouterj since you asked for other naming proposals, here's my proposal 🙈 

Before:

```php
final class Validation
{
    public static function createCallable($constraintOrValidator = null, Constraint ...$constraints): callable

    public static function createValidCallable($constraintOrValidator = null, Constraint ...$constraints): callable

    // ...    
}
```

After:

```php
final class Validation
{
    public static function isValidOrThrow($constraintOrValidator = null, Constraint ...$constraints): callable

    public static function isValid($constraintOrValidator = null, Constraint ...$constraints): callable

    // ...    
}
```

**Comment by jvasseur** [comment]
@javiereguiluz I would expect a function named `isValid` to directly do the validation and return a `bool` instead of creating a `callable`.

**Comment by javiereguiluz** [comment]
@jvasseur you are right! I mixed things up ... as usually happens to me with the validator. Sorry! I deleted the original comment.

File: src/Symfony/Component/Validator/CHANGELOG.md (hunk 2 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/CHANGELOG.md]: s/createValidClosure/createValidCallable

File: src/Symfony/Component/Validator/Validation.php [hunk 5]
```diff
@@ -49,6 +49,26 @@ public static function createCallable($constraintOrValidator = null, Constraint
         };
     }
 
+    /**
+     * Creates a callable that returns true/false instead of throwing validation exceptions.
+     *
+     * @param Constraint|ValidatorInterface|null $constraintOrValidator
+     */
+    public static function createValidCallable($constraintOrValidator = null, Constraint ...$constraints): callable
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Validation.php]: `createIsValidCallable`?

Comment (wouterj) [reply src/Symfony/Component/Validator/Validation.php]: Maybe `createBooleanCallable()`? I'm surprised there is no "official" term for this type of function, validation using return vs exception seems quite a common pattern/decision.

Comment (ro0NL) [reply src/Symfony/Component/Validator/Validation.php]: we obtain a validator function: Validation::createValidatorCallable
we obtain a validation function: Validation::createCallable

ie.

$isValid = $validator($value);
$validiation($value);

edit: actually i agree `createIsValidCallable` fits better. It conveys the boolean return explicitly

File: src/Symfony/Component/Validator/Validation.php (hunk 3 above)
Comment (wouterj) [reply src/Symfony/Component/Validator/Validation.php]: Added `$violations`

**Review by yceruto — APPROVED** [review]

File: src/Symfony/Component/Validator/Validation.php [hunk 6]
```diff
@@ -39,13 +61,14 @@ public static function createCallable($constraintOrValidator = null, Constraint
 
         $validator = $validator ?? self::createValidator();
 
-        return static function ($value) use ($constraints, $validator) {
-            $violations = $validator->validate($value, $constraints);
-            if (0 !== $violations->count()) {
-                throw new ValidationFailedException($value, $violations);
+        return static function ($value, ConstraintViolationListInterface $violations = null) use ($constraints, $validator) {
+            $valueViolations = $validator->validate($value, $constraints);
```
Comment (ro0NL) [inline src/Symfony/Component/Validator/Validation.php]: why not set $violations by ref?

Comment (wouterj) [reply src/Symfony/Component/Validator/Validation.php]: Fixed, I've almost never used by ref arguments, so didn't know this was possible

Comment (ro0NL) [reply src/Symfony/Component/Validator/Validation.php]: psalm fixed it :} https://psalm.dev/docs/annotating_code/supported_annotations/#param-out-psalm-param-out

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @wouterj.
