### PR TITLE
[Security/Http] Fix compat of persistent remember-me with legacy tokens

### LINKED ISSUE #49100: [security-http]  Cookie invalid Data exception  Since commit 889d7393
### Symfony version(s) affected

6.2.5

### Description

Since we've migrated from 6.2.3 to 6.2.5 we've seen a raised of the following exception

Symfony\Component\Security\Core\Exception\AuthenticationException , whch cause a massive de-logged  / need to re-login for our users 

with the following stack trace 

```
Symfony\Component\Security\Core\Exception\AuthenticationException: The cookie contains invalid data.
#26 /vendor/symfony/security-http/RememberMe/RememberMeDetails.php(41): Symfony\Component\Security\Http\RememberMe\RememberMeDetails::fromRawCookie
#25 /vendor/symfony/security-http/RememberMe/PersistentRememberMeHandler.php(115): Symfony\Component\Security\Http\RememberMe\PersistentRememberMeHandler::clearRememberMeCookie
#24 /vendor/symfony/security-http/EventListener/RememberMeListener.php(73): Symfony\Component\Security\Http\EventListener\RememberMeListener::clearCookie
#23 /vendor/symfony/event-dispatcher/EventDispatcher.php(246): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}
#22 /vendor/symfony/event-dispatcher/EventDispatcher.php(206): Symfony\Component\EventDispatcher\EventDispatcher::callListeners
#21 /vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher::dispatch
#20 /vendor/symfony/security-http/Authentication/AuthenticatorManager.php(259): Symfony\Component\Security\Http\Authentication\AuthenticatorManager::handleAuthenticationFailure
#19 /vendor/symfony/security-http/Authentication/AuthenticatorManager.php(207): Symfony\Component\Security\Http\Authentication\AuthenticatorManager::executeAuthenticator
#18 /vendor/symfony/security-http/Authentication/AuthenticatorManager.php(154): Symfony\Component\Security\Http\Authentication\AuthenticatorManager::executeAuthenticators
#17 /vendor/symfony/security-http/Authentication/AuthenticatorManager.php(136): Symfony\Component\Security\Http\Authentication\AuthenticatorManager::authenticateRequest
#16 /vendor/symfony/security-http/Firewall/AuthenticatorManagerListener.php(40): Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener::authenticate
#15 /vendor/symfony/security-bundle/Security/LazyFirewallContext.php(73): Symfony\Bundle\SecurityBundle\Security\LazyFirewallContext::Symfony\Bundle\SecurityBundle\Security\{closure}
#14 /vendor/symfony/security-core/Authentication/Token/Storage/TokenStorage.php(34): Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage::getToken
#13 /vendor/symfony/security-core/Authentication/Token/Storage/UsageTrackingTokenStorage.php(44): Symfony\Component\Security\Core\Authentication\Token\Storage\UsageTrackingTokenStorage::getToken
#12 /vendor/symfony/security-core/Security.php(78): Symfony\Component\Security\Core\Security::getToken
```

it seems to have been introduce by specifically this commit at this line

https://github.com/symfony/symfony/commit/889d73939bd4651ed4264c9f0596a44b37bef543#diff-3a1049f354b63f2306a7a0007466f777c659b1f8c070f0d9310a8486c47d0b54L39

i.e  as the raw remember cookie is  a base64 , the "explode" can't work on it, and so it triggers the exception 

### How to reproduce

1.  Have a project on 6.2.3  with remember cookie activated
2.  Login with remember cookie
3.  have a low session expiration (so that the remember cookie trigger) and wait for that time
4.  upgrade to 6.2.5 
5.  now return to your website
6. => you have been unlogged  (the user do not see the exception as it caught by the firewall ) 

### Possible Solution

Provide  a way to detect "old" remember cookie and migrate them ? 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49100
| License       | MIT
| Doc PR        | -

In #49078, we changed the format of remember-me tokens, effectively invalidating them all.
While the invalidation is intentional for signature-based remember-me handlers, persistent remember-me handlers could accept both legacy and updated tokens.
This PR fixes compat with legacy tokens for persistent remember-me handlers.

### CODE REVIEW

File: src/Symfony/Component/Security/Http/RememberMe/PersistentRememberMeHandler.php [hunk 1]
```diff
@@ -45,7 +44,6 @@ public function __construct(TokenProviderInterface $tokenProvider, string $secre
         }
         $this->tokenProvider = $tokenProvider;
         $this->tokenVerifier = $tokenVerifier;
-        $this->secret = $secret;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Http/RememberMe/PersistentRememberMeHandler.php:48]: unused property after #49078

Comment (stof) [reply src/Symfony/Component/Security/Http/RememberMe/PersistentRememberMeHandler.php:48]: should we deprecate the constructor argument ?

Comment (nicolas-grekas) [reply src/Symfony/Component/Security/Http/RememberMe/PersistentRememberMeHandler.php:48]: we could but not in 5.4

**Review by stof — APPROVED** [review]

**Review by chalasr — APPROVED** [review]
How long should they be supported?

**Comment by nicolas-grekas** [comment]
We can keep that logic forever, we don't really care IMHO.

**Comment by eexit** [comment]
Hi @nicolas-grekas,

Thanks for the quick fix.
I'm struggling with testing your PR. I use Symfony Flex and after adding this into my `composer.json`, it looks like I still can't install the forked bundled:

```json
"repositories": [
    {
        "_comment": "Testing: https://github.com/symfony/symfony/pull/49103",
        "type": "git",
        "url": "https://github.com/nicolas-grekas/symfony.git"
    }
]
```

Doing this command does not work: `composer require -W "symfony/security-bundle:dev-sec-http-legacy-persistent-token" --prefer-source`.

```
composer require -W "symfony/security-bundle:dev-sec-http-legacy-persistent-token" --prefer-source
./composer.json has been updated
Running composer update symfony/security-bundle --with-all-dependencies
Loading composer repositories with package information
Info from https://repo.packagist.org/: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires symfony/security-bundle dev-sec-http-legacy-persistent-token, found symfony/security-bundle[2.0.7, ..., 2.8.x-dev, v3.0.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev, v6.0.0-BETA1, ..., 6.3.x-dev] but it does not match the constraint.
  Problem 2
    - easycorp/easyadmin-bundle is locked to version v*** and an update of this package was not requested.
    - easycorp/easyadmin-bundle v*** requires symfony/security-bundle ^5.4|^6.0 -> found symfony/security-bundle[v5.4.0-BETA1, ..., 5.4.x-dev, v6.0.0-BETA1, ..., 6.3.x-dev] but it conflicts with your root composer.json require (dev-sec-http-legacy-persistent-token).


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
``` 

It looks like composer is ignoring your repo and I have no idea why.
Would you mind giving some insights on how to test this?

Thanks!
