### PR TITLE
[Mailer] Add support of ping_threshold to SesTransportFactory

### LINKED ISSUE #39044: [Mailer] SMTP transport with AWS SES: "Timeout waiting for data from client"
**Symfony version(s) affected**: 4.4.16, 5.2

**Description**  
Our system sends e-mails asynchronously using the Messenger component. Two messenger consumers are running in the background with Supervisor. We use Doctrine for our message transport and AWS SES over SMTP for e-mails. On our production system we are seeing the following error occur. This issue was already described here: https://github.com/symfony/symfony/issues/36301. A PR was merged, but we are still seeing this problem.

```
Symfony\Component\Mailer\Exception\TransportException

Expected response code "250" but got code "451", with message "451 4.4.2 Timeout waiting for data from client.".
```

After the messages fail for the first time, they will get retried. Eventually after one or two retries they do get send successfully.

**How to reproduce**  
See https://github.com/symfony/symfony/issues/36301

### PR DESCRIPTION
**Pull request by Tyraelqp**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | Yes
| Deprecations? | no
| Tickets       | Fix #39044
| License       | MIT
| Doc PR        | https://github.com/symfony/symfony-docs/pull/15557

Added support of ping_threshold option to `SesTransportFactory` for `ses+smtp` and `ses+smtps` schemes. Needed because SES closes SMTP connection after 10 seconds of inactivity and `TransportException` will be thrown on next send: `Expected response code "250" but got code "451", with message "451 4.4.2 Timeout waiting for data from client.".`

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by Nyholm** [comment]
Hm.. I would argue that this is a new feature. It should target 5.4.

**Comment by Tyraelqp** [comment]
> Hm.. I would argue that this is a new feature. It should target 5.4.

We have `ping_threshold` for a long time - it is part of `SmtpTransport`. But it was not implemented in Ses factory, and this looks more like a bug, because without this prop you can't use ses+smtp in background (messenger) without issues

**Comment by Nyholm** [comment]
Adding a new config option is a feature. It is currently not unusable in a background process. But I do understand it is painful and I agree that we should improve. 

If I remember correctly, there is not a lot of changes in mailer between 4.4 and 5.4. The component is fairly stable. (I’m on my phone, cannot check now… I might be wrong). 

It would not be an issue for you to keep using version 4.4 for other components and 5.4 for just mailer.

**Comment by Tyraelqp** [comment]
@Nyholm I'm not using 4.4 and the target is 4.4 now because Oskar said in prev PR what target should be 4.4. I can open new PR to 5.4, it's not a problem. But i have several questions:
* May/should i add `restart_threshold` too?
* What if i'll set default value for `ping_threshold` to 8 or 9 (because SES closes SMTP connection after 10 seconds of inactivity) for SesSmtpTransport with possibility to override this value as in this PR?
* What about documentation? Should i add something in docs repo?

**Comment by OskarStark** [comment]
I would argue that the current implementation is not usable right now, that's why I would vote for a bugfix, ofc I am aware of the ne option new code -> new feature.

@nicolas-grekas WDYT?

File: src/Symfony/Component/Mailer/Bridge/Amazon/Transport/SesTransportFactory.php [hunk 1]
```diff
@@ -44,7 +44,13 @@ public function create(Dsn $dsn): TransportInterface
         }
 
         if ('ses+smtp' === $scheme || 'ses+smtps' === $scheme) {
-            return new SesSmtpTransport($user, $password, $region, $this->dispatcher, $this->logger);
+            $transport = new SesSmtpTransport($user, $password, $region, $this->dispatcher, $this->logger);
+
+            if (null !== ($pingThreshold = $dsn->getOption('ping_threshold'))) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mailer/Bridge/Amazon/Transport/SesTransportFactory.php]: the brackets after `!==` should be removed

**Review by nicolas-grekas — COMMENTED** [review]
That's edgy. This may be annoying enough to pass as a bugfix...

**Comment by Tyraelqp** [comment]
@OskarStark @nicolas-grekas  What do you think about default value? (second question from this comment https://github.com/symfony/symfony/pull/42219#issuecomment-884716804)

File: src/Symfony/Component/Mailer/Bridge/Amazon/Transport/SesTransportFactory.php (hunk 1 above)
Comment (Tyraelqp) [reply src/Symfony/Component/Mailer/Bridge/Amazon/Transport/SesTransportFactory.php]: Removed, ty

**Comment by OskarStark** [comment]
I would fix this as a bugfix, and as a feature against 5.4 setting the default value to 8

**Comment by Tyraelqp** [comment]
> I would fix this as a bugfix, and as a feature against 5.4 setting the default value to 8

Sorry, but i did not quite understand: leave this PR as is for 4.4, and open new one in 5.4 with default value?
I think it will be more correct to do vice versa: in 4.4 set default value to 8 (bugfix)[this is better fix than possibility to change value because works out of the box and does not requires any action from user/configuration], and in 5.4 add possibility to change value (feature)

**Comment by OskarStark** [comment]
I agree, but the problem is, it would change the current behaviour, while just adding the possibility to set a value, can introduce new bugs, but will not break the current behaviour. Not sure I am to picky here.

@nicolas-grekas please decide 😄

**Comment by Tyraelqp** [comment]
> please decide

Option 1: default value in 4.4 and support of `ping_threshold` in 5.4
Option 2: default value in 5.4 and support of `ping_threshold` in 4.4

**Comment by Nyholm** [comment]
> I'm not using 4.4 and the target is 4.4 now because Oskar said in prev PR what target should be 4.4. I can open new PR to 5.4, it's not a problem. 

I see. Thank you. Since both Oskar and Nicolas think this can be merged in 4.4 that is okey. 

> May/should i add restart_threshold too?

Could you elaborate why that is needed?

> What if i'll set default value for ping_threshold to 8 or 9 (because SES closes SMTP connection after 10 seconds of inactivity) for SesSmtpTransport with possibility to override this value as in this PR?

I prefer no default value. Just add the option to be able to set `ping_threshold`. We don't want to modify existing behavior. 

> What about documentation? Should i add something in docs repo?

Yes please. When the PR is merged, I would appriciate that you sent a PR to https://github.com/symfony/symfony-docs
Remember to target the correct branch.

**Comment by fabpot** [comment]
Sorry to be the one to do this, but adding a new config is a new feature, no matter what. So, that's for 5.4.

**Comment by Tyraelqp** [comment]
It is possible to reparse PR with @carsonbot to change tags and milestone?

**Comment by fabpot** [comment]
Thank you @Tyraelqp.
