### PR TITLE
[TwigBridge] export concatenated translations

### LINKED ISSUE #39351: Update translations with concatenated strings
**Symfony version(s) affected**: 4.4

**Description**  
Extraction translations from Twig fail to extract concatenated strings

**How to reproduce**  
use the translation:update command on a template like this:
```{{ ('aa' ~ 'bb')|trans }}```

**Possible Solution**  
change the TranslationNodeVisitor so it gets the concatenated strings

### PR DESCRIPTION
**Pull request by galatea-nl**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39351
| License       | MIT
| Doc PR        | 

This PR will fix that concatenated strings are ignored by the translation:update command. Suppose you have a twig file like this:
```
{{ ('aa' ~ 'bb') | trans }}
```
This is not exported when using the command. This PR will fix that.

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

File: src/Symfony/Bridge/Twig/Tests/Translation/TwigExtractorTest.php [hunk 1]
```diff
@@ -76,6 +76,12 @@ public function getExtractData()
 
             // make sure this works with twig's named arguments
             ['{{ "new key" | trans(domain="domain") }}', ['new key' => 'domain']],
+
+            //concat translations
```
Comment (fabpot) [inline src/Symfony/Bridge/Twig/Tests/Translation/TwigExtractorTest.php]: missing space after `//`

File: src/Symfony/Bridge/Twig/NodeVisitor/TranslationNodeVisitor.php [hunk 2]
```diff
@@ -92,6 +93,13 @@ protected function doEnterNode(Node $node, Environment $env)
                 $node->getNode('body')->getAttribute('data'),
                 $node->hasNode('domain') ? $this->getReadDomainFromNode($node->getNode('domain')) : null,
             ];
+        } elseif ($node instanceof FilterExpression &&
+            'trans' === $node->getNode('filter')->getAttribute('value') &&
+            $node->getNode('node') instanceof ConcatBinary) {
```
Comment (fabpot) [inline src/Symfony/Bridge/Twig/NodeVisitor/TranslationNodeVisitor.php]: Can you format the test like done on line 79-84?

Comment (fabpot) [reply src/Symfony/Bridge/Twig/NodeVisitor/TranslationNodeVisitor.php]: What if one part of the concat is not a string but a variable?

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Bridge/Twig/NodeVisitor/TranslationNodeVisitor.php (hunk 2 above)
Comment (galatea-nl) [reply src/Symfony/Bridge/Twig/NodeVisitor/TranslationNodeVisitor.php]: @fabpot If it's not a string, we cannot extract it, but it's still better that it's now. Changed the code and added new tests.

Not sure if I should fix the failing Travis CI build

**Comment by stof** [comment]
I changed the milestone to 5.x, as that's not a bugfix to me.

File: src/Symfony/Bridge/Twig/NodeVisitor/TranslationNodeVisitor.php [hunk 3]
```diff
@@ -138,4 +149,28 @@ private function getReadDomainFromNode(Node $node): ?string
 
         return self::UNDEFINED_DOMAIN;
     }
+
+    private function getConcatValueFromNode(Node $node, ?string $value): ?string
+    {
+        if ($node instanceof ConcatBinary) {
+            foreach ($node->getIterator() as $nextNode) {
```
Comment (stof) [inline src/Symfony/Bridge/Twig/NodeVisitor/TranslationNodeVisitor.php]: `foreach ($node as $nextNode)` is enough

**Comment by galatea-nl** [comment]
If I read the documentation I would expect that these translations were exported and if it doesn't it's a bug to me. 4.4 is supported for another 2 years so it would be nice (at least for me) if it could be merged in there as well.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @galatea-nl.
