### PR TITLE
[HttpFoundation] Removed "Content-Type" from the preferred format guessing mechanism

### LINKED ISSUE #34857: [httpFoundation] Request::getPreferredFormat() - Submit form, force to download render page with IE7 or IE 11 (with strategy GPO to emulate IE7)
**Symfony version(s) affected**: 4.4.1
php 7.2.25 or 7.2.9

**Description**  
If you try to submit form with bad value, like a empty value with the Assert\NotBlank when you submit the form, **only** on IE 11 (with strategy GPO to emulate IE7) or IE 7 the render page is forced to download.

On chrome , EDGE, Firefox the render is correct with the message "This value should not be blank."

**The same code and apache config with symfony 4.3.x work correctly**

**How to reproduce**  

You can try  https://github.com/thewalkingcoder/symf44.git

Is a fresh symfony 4.4.1 --full install, with very very simple Entity, form and template.

**Additional context** 

ex IE 11
image

ex : chrome
image 

I try multiple tests

**linux apache/php 7.2.25** 

with alias http://symf44.local
chrome, firefox, edge -> ok
IE 7 -> fail

no alias like http://localhost/myapp/public
chrome, firefox, edge -> ok
IE 7 -> ok

**symfony server**
 with alias http://symf44.local with reverse proxy
chrome, firefox, edge -> ok
IE 7 -> fail

no alias like http://localhost:8080
chrome, firefox, edge -> ok
IE 7 -> ok

**windows xp with Uwamp beurk !!  **
 with alias
chrome, firefox -> ok
IE 7 -> fail

no alias like http://localhost/myapp/public
chrome, firefox -> ok
IE 7 -> fail

I try to change or remove .htaccess (provide to apache-pack) same result
I try to change Constraint NotBlank annotation to php style or YAML same result

### LINKED ISSUE #34906: [BC Break] Form POSTs w/o Accept return application/x-www-form-urlencoded response Content-Type
**Symfony version(s) affected**: 4.4.0

**Description**  
Hi! Due to #32344, if you POST a form submit but do *not* send any `Accept` headers, the response `Content-Type` will be the invalid `application/x-www-form-urlencoded`.

This doesn't happen in practice in a browser (which sends an `Accept` header), but DOES happen in functional tests - and is very difficult to debug.

The problem is that, in `$response->prepare()`, `$request->getPreferredFormat()` is called to try to figure out the correct `Content-Type`. If there is no `Accept` header, it eventually falls back to to using the request `Content-Type` as the default value:

https://github.com/symfony/symfony/blob/5e75edf57898e4464cd0f7a8d7c4e966d126cd97/src/Symfony/Component/HttpFoundation/Request.php#L1600

But in 4.3, it used "html".

**How to reproduce**  
Set up or find any deployed 4.4 form submit. Submit in your browser, then use the "Copy as Curl" tool in your browser network tools. Paste that into your terminal, but remove the `-H Accept` header.

That's it! Check out the `Content-Type` header on the response.

**Possible Solution**  
The last 2 lines of Request::getPreferredFormat() should maybe be:

```diff
- $this->preferredFormat = $this->getRequestFormat($preferredFormat ?: $this->getContentType());
+ $this->preferredFormat = $this->getRequestFormat($preferredFormat ?: $default);
```

Ping @yceruto :)

### PR DESCRIPTION
**Pull request by yceruto**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34906, Fix #34857
| License       | MIT
| Doc PR        | -

Confirmed, inferring the `Content-Type` of the response using the `Content-Type` provided for the request body is NOT a good idea. The HTTP RFC explicitly states that `Accept` must be used to hint a preferred response format (`Content-Type` on the request indicates the type of associated its the body). 

Use `Accept` if provided (a best practice anyway), and fallback to the default value (HTML by default) otherwise.

### CODE REVIEW

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 1]
```diff
@@ -1586,20 +1586,17 @@ public function isNoCache()
...
             return $this->preferredFormat;
         }
 
-        $preferredFormat = null;
-        foreach ($this->getAcceptableContentTypes() as $contentType) {
-            if ($preferredFormat = $this->getFormat($contentType)) {
-                break;
+        foreach ($this->getAcceptableContentTypes() as $mimeType) {
+            if ($this->preferredFormat = $this->getFormat($mimeType)) {
+                return $this->preferredFormat;
```
Comment (stof) [inline src/Symfony/Component/HttpFoundation/Request.php]: this is not going through `getRequestFormat` anymore. Is it expected ?

Comment (yceruto) [reply src/Symfony/Component/HttpFoundation/Request.php]: See the first diff, it's calling to `getRequestFormat`.

Comment (stof) [reply src/Symfony/Component/HttpFoundation/Request.php]: ah indeed. The argument passed to `getRequestFormat` is the fallback value when there is no `_format` attribute.

**Review by stof — APPROVED** [review]

**Review by weaverryan — APPROVED** [review]
Thank you for the PR :)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @yceruto.

**Review by dresh — APPROVED** [review]
