### PR TITLE
[DoctrineBridge] Improve exception message when `EntityValueResolver` gets no mapping information

### LINKED ISSUE #60111: Make failed entity argument resolving display a usefull error message
### Description

Current, using the default recipe coming with Symfony 7.2, when one has a controller like that:

```php
    #[Route('/conference/{slug}', name: 'conference')]
    public function show(Conference $conference) {
```

One will get this message:

Image

When you know the solution, the fix is trivial:
```diff
-    #[Route('/conference/{slug}', name: 'conference')]
+    #[Route('/conference/{slug:conference}', name: 'conference')]
```

But when you don't, you're SOL.

The thing is, we do have the reporting infrastructure to improve this: `NearMissValueResolverException` as introduced in #54107.
It'd be great to leverage it for similar cases.

Help wanted.

### Example

_No response_

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #60111
| License       | MIT

Message based on https://github.com/symfony/symfony/blob/1a8b82e5dfd43f18b6f9e280a9468296d1f5bffe/src/Symfony/Bridge/Doctrine/ArgumentResolver/EntityValueResolver.php#L188

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/ArgumentResolver/EntityValueResolver.php [hunk 1]
```diff
@@ -68,7 +69,7 @@ public function resolve(Request $request, ArgumentMetadata $argument): array
         } elseif (false === $object = $this->find($manager, $request, $options, $argument)) {
             // find by criteria
             if (!$criteria = $this->getCriteria($request, $options, $manager, $argument)) {
-                return [];
+                throw new NearMissValueResolverException(sprintf('Cannot find mapping for "%s": declare the identifier using either the #[MapEntity] attribute or mapped route parameters.', $options->class));
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/ArgumentResolver/EntityValueResolver.php]: not only identifiers, right? (this applies to the deprecation also, isn't it?)
```suggestion
                throw new NearMissValueResolverException(sprintf('Cannot find mapping for "%s": declare it using either the #[MapEntity] attribute or mapped route parameters.', $options->class));
```

Comment (MatTheCat) [reply src/Symfony/Bridge/Doctrine/ArgumentResolver/EntityValueResolver.php]: I assumed ”identifier” meant “whatever data identifying an entity” in this context ¯\\_(ツ)\_/¯

Updating.

File: src/Symfony/Bridge/Doctrine/composer.json [hunk 2]
```diff
@@ -31,7 +31,7 @@
         "symfony/doctrine-messenger": "^6.4|^7.0",
         "symfony/expression-language": "^6.4|^7.0",
         "symfony/form": "^6.4.6|^7.0.6",
-        "symfony/http-kernel": "^6.4|^7.0",
+        "symfony/http-kernel": "^7.1",
```
Comment (MatTheCat) [inline src/Symfony/Bridge/Doctrine/composer.json]: Should we rather keep the old behavior if `NearMissValueResolverException` doesn’t exist?

Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/composer.json]: that'd be fine to me indeed

File: src/Symfony/Bridge/Doctrine/ArgumentResolver/EntityValueResolver.php [hunk 3]
```diff
@@ -185,7 +186,7 @@ private function getCriteria(Request $request, MapEntity $options, ObjectManager
 
             return $criteria;
         } elseif (null === $mapping) {
-            trigger_deprecation('symfony/doctrine-bridge', '7.1', 'Relying on auto-mapping for Doctrine entities is deprecated for argument $%s of "%s": declare the identifier using either the #[MapEntity] attribute or mapped route parameters.', $argument->getName(), method_exists($argument, 'getControllerName') ? $argument->getControllerName() : 'n/a');
+            trigger_deprecation('symfony/doctrine-bridge', '7.1', 'Relying on auto-mapping for Doctrine entities is deprecated for argument $%s of "%s": declare it using either the #[MapEntity] attribute or mapped route parameters.', $argument->getName(), method_exists($argument, 'getControllerName') ? $argument->getControllerName() : 'n/a');
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/ArgumentResolver/EntityValueResolver.php:189]: maybe "one" instead of "it" :thinking:  (on both messages)
this looks better to me now that I read the message again

File: src/Symfony/Bridge/Doctrine/ArgumentResolver/EntityValueResolver.php [hunk 4]
```diff
@@ -68,7 +69,7 @@ public function resolve(Request $request, ArgumentMetadata $argument): array
         } elseif (false === $object = $this->find($manager, $request, $options, $argument)) {
             // find by criteria
             if (!$criteria = $this->getCriteria($request, $options, $manager, $argument)) {
-                return [];
+                throw new NearMissValueResolverException(sprintf('Cannot find mapping for "%s": declare it using either the #[MapEntity] attribute or mapped route parameters.', $options->class));
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/ArgumentResolver/EntityValueResolver.php]: maybe "one" instead of "it" :thinking:  (on both messages)
this looks better to me now that I read the message again

File: src/Symfony/Bridge/Doctrine/ArgumentResolver/EntityValueResolver.php (hunk 3 above)
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/ArgumentResolver/EntityValueResolver.php]: sorry I should have read more carefully, the 'it' doesn't work here
```suggestion
            trigger_deprecation('symfony/doctrine-bridge', '7.1', 'Relying on auto-mapping for Doctrine entities is deprecated for argument $%s of "%s": declare the mapping using either the #[MapEntity] attribute or mapped route parameters.', $argument->getName(), method_exists($argument, 'getControllerName') ? $argument->getControllerName() : 'n/a');
```

Comment (MatTheCat) [reply src/Symfony/Bridge/Doctrine/ArgumentResolver/EntityValueResolver.php]: Updated

File: src/Symfony/Bridge/Doctrine/composer.json (hunk 2 above)
Comment (MatTheCat) [reply src/Symfony/Bridge/Doctrine/composer.json]: Okay added conditions on `NearMissValueResolverException` existence

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @MatTheCat.
