### PR TITLE
[Form] Throw error if the number is too high on moneyTransformer

### LINKED ISSUE #53929: MoneyType field and bad conversion to int
### Symfony version(s) affected

7.1

### Description

Hello, and thank you for your work on Symfony ! 
I just stumbled upon what seems to be a bug with the MoneyType form type incoming option `'model_type' => 'integer` (cf https://github.com/symfony/symfony-docs/pull/19359) while trying to do kind of the same thing. 

It seems that when inputing large numbers (probably because of the scientific notation introduced when a conversion to float happens - [in rounding maybe ?](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Form/Extension/Core/DataTransformer/NumberToLocalizedStringTransformer.php#L183), the cast back to an integer presents some issues: 

Inputing for instance `111111111111111110,00` gets cast back to `9223372036854775807`.  (cf my reproducer)

I realise that this is probably very niche (such large numbers for MoneyType fields), but I felt this might need to get looked at

### How to reproduce

Here is a short reproducer: 
https://github.com/JacquesDurand/money_type_reproducer
(see readme for description on how to reproduce)

### Possible Solution

I feel I do not know enough about large number treatments and conversions in PHP, but if you feel that there is a simple fix, I'd be happy to contribute it !

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Fan2Shrek**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #53929 
| License       | MIT

The `MoneyType` does not handle high numbers when using `'model_type' => 'integer` this leads to unexpected results :

Inputing for instance `111111111111111110,00` gets cast back to `9223372036854775807`.

I have added a verification with `\PHP_INT_MAX` to throw an error in such case
I'm not sure if this is the best approach.

### CODE REVIEW

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformer.php [hunk 1]
```diff
@@ -69,7 +69,17 @@ public function reverseTransform(mixed $value): int|float|null
         $value = parent::reverseTransform($value);
         if (null !== $value && 1 !== $this->divisor) {
             $value = (string) ($value * $this->divisor);
-            $value = 'integer' === $this->modelType ? (int) $value : (float) $value;
+
+            if ('float' === $this->modelType) {
+                return (float) $value;
+            }
+
+            $value = (int) $value;
```
Comment (xabbuh) [inline src/Symfony/Component/Form/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformer.php]: We need to do the comparison before doing the cast (see https://3v4l.org/4uaZL).

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformer.php [hunk 2]
```diff
@@ -69,7 +69,16 @@ public function reverseTransform(mixed $value): int|float|null
...
             $value = (string) ($value * $this->divisor);
-            $value = 'integer' === $this->modelType ? (int) $value : (float) $value;
+
+            if ('float' === $this->modelType) {
+                return (float) $value;
+            }
+
+            if ($value >= \PHP_INT_MAX || $value <= -\PHP_INT_MAX) {
+                throw new TransformationFailedException(sprintf("The value '%d' is too large you should pass the 'model_type' to 'float'.", $value));
+            }
```
Comment (asispts) [inline src/Symfony/Component/Form/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformer.php]: Shouldn't it be
```suggestion
            if ($value > \PHP_INT_MAX || $value < -\PHP_INT_MAX) {
                throw new TransformationFailedException(sprintf("The value '%d' is too large you should pass the 'model_type' to 'float'.", $value));
            }
```

Comment (Fan2Shrek) [reply src/Symfony/Component/Form/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformer.php]: Yes, you're right, thanks :)

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformer.php [hunk 3]
```diff
@@ -69,7 +69,16 @@ public function reverseTransform(mixed $value): int|float|null
         $value = parent::reverseTransform($value);
         if (null !== $value && 1 !== $this->divisor) {
             $value = (string) ($value * $this->divisor);
-            $value = 'integer' === $this->modelType ? (int) $value : (float) $value;
+
+            if ('float' === $this->modelType) {
+                return (float) $value;
+            }
+
+            if ($value > \PHP_INT_MAX || $value < -\PHP_INT_MAX) {
```
Comment (xabbuh) [inline src/Symfony/Component/Form/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformer.php]:
```suggestion
            if ($value > \PHP_INT_MAX || $value < \PHP_INT_MIN) {
```

**Review by xabbuh — APPROVED** [review]

**Review by welcoMattic — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Fan2Shrek.
