### PR TITLE
[ObjectMapper] Fix Map attribute PHPDoc for $if param

### LINKED ISSUE #63273: [ObjectMapper] Map attribute PHPDoc does not match TargetClass for $if param
### Symfony version(s) affected

8.0.5

### Description

PHPdoc annotation in \Symfony\Component\ObjectMapper\Attribute\Map constructor for $if parameter does not include \Symfony\Component\ObjectMapper\Condition\TargetClass as allowed type.

PHPStan error:
`Parameter $if of attribute class Symfony\Component\ObjectMapper\Attribute\Map constructor expects bool|(callable(mixed, object): bool)|string|null, Symfony\Component\ObjectMapper\Condition\TargetClass<App\ExampleClass> given.`

### How to reproduce

Using if with `TargetClass` in `Map` attribute.

Example:

#[Map(if: new TargetClass(ExampleClass::class))]

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lacatoire**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #63273
| License       | MIT

The callable signature for the `$if` parameter in the `Map` attribute PHPDoc was `callable(mixed, object): bool`, but the actual `ConditionCallableInterface::__invoke` signature takes 3 parameters: `(mixed, object, ?object)`.

This mismatch caused PHPStan to report errors when using built-in conditions like `TargetClass`.

This PR fixes the callable signature to `callable(mixed, object, ?object): bool` to match the actual interface.

### CODE REVIEW

File: src/Symfony/Component/ObjectMapper/Attribute/Map.php [hunk 1]
```diff
@@ -20,9 +22,9 @@
 class Map
 {
     /**
-     * @param string|class-string|null                                                                                 $source    The property or the class to map from
-     * @param string|class-string|null                                                                                 $target    The property or the class to map to
-     * @param string|bool|callable(mixed, object): bool|null                                                           $if        A boolean, a service id or a callable that instructs whether to map
+     * @param string|class-string|null                                                                                                          $source    The property or the class to map from
+     * @param string|class-string|null                                                                                                          $target    The property or the class to map to
+     * @param string|bool|ConditionCallableInterface|callable(mixed, object, ?object): bool|null                                                $if        A boolean, a service id or a callable that instructs whether to map
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ObjectMapper/Attribute/Map.php]: too many spaces :)

Comment (nicolas-grekas) [reply src/Symfony/Component/ObjectMapper/Attribute/Map.php]: ConditionCallableInterface is already covered by the callable description

**Comment by nicolas-grekas** [comment]
Thank you @lacatoire.
