### PR TITLE
[DI] Fix Xdebug 3.0 detection

### LINKED ISSUE #39195: Xdebug 3.0 leads to exception during DI container compile
**Symfony version(s) affected**: 5.1.8

**Description** 
Duplicates #30571 in a certain way (but that's closed)
Exception:

> PHP Fatal error:  Method class@anonymous::__toString() must not throw an exception

When the Exception AutowiringFailedException is constructed with a callback as message and xdebug is installed in version >= 3.0 the condition which resolves the message callback to the actual message string does not work.
Xdebug 3.0 does not provide the function `xdebug_is_enabled` anymore. See https://xdebug.org/docs/upgrade_guide#Changes-to-Functions

**How to reproduce**  
You can use the reproducer from #30571. Please ensure your environment has Xdebug 3.0 installed.

**Possible Solution**  
Replace `\function_exists('xdebug_is_enabled') && xdebug_is_enabled()` in AutowiringFailedException.php:26 with a condition which is true for xdebug 2.x **and** 3.x.

**Additional context**  

Exception call stack:
(Hint: The mentioned `class@anonymous::__toString()` is defined in symfony/dependency-injection/Exception/AutowiringFailedException.php:39 and following)
```
PHP Fatal error:  Method class@anonymous::__toString() must not throw an exception, caught Symfony\Component\DependencyInjection\Exception\AutowiringFailedException:  in /app/app/vendor/symfony/dependency-injection/Compiler/AutowirePass.php on line 236
PHP Stack trace:
PHP   1. {main}() /app/app/bin/console:0
PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /app/app/bin/console:42
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /app/app/vendor/symfony/console/Application.php:142
PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() /app/app/vendor/symfony/framework-bundle/Console/Application.php:74
PHP   5. App\Kernel->boot() /app/app/vendor/symfony/framework-bundle/Console/Application.php:168
PHP   6. App\Kernel->initializeContainer() /app/app/vendor/symfony/http-kernel/Kernel.php:131
PHP   7. Symfony\Component\DependencyInjection\ContainerBuilder->compile() /app/app/vendor/symfony/http-kernel/Kernel.php:533
PHP   8. Symfony\Component\DependencyInjection\Compiler\Compiler->compile() /app/app/vendor/symfony/dependency-injection/ContainerBuilder.php:736
PHP   9. Symfony\Component\DependencyInjection\Compiler\AutowirePass->process() /app/app/vendor/symfony/dependency-injection/Compiler/Compiler.php:91
PHP  10. Symfony\Component\DependencyInjection\Compiler\AutowirePass->process() /app/app/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:54
PHP  11. Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue() /app/app/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:46
PHP  12. Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue() /app/app/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:72
PHP  13. Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue() /app/app/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:103
PHP  14. Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue() /app/app/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:81
PHP  15. Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue() /app/app/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:72
PHP  16. Symfony\Component\DependencyInjection\Compiler\AutowirePass->autowireCalls() /app/app/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:126
PHP  17. Symfony\Component\DependencyInjection\Compiler\AutowirePass->autowireMethod() /app/app/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:171
PHP  18. Symfony\Component\DependencyInjection\Compiler\AutowirePass->Symfony\Component\DependencyInjection\Compiler\{closure:/app/app/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:229-241}() /app/app/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:261
```

### PR DESCRIPTION
**Pull request by vertexvaar**
| Q             | A
| ------------- | ---
| Branch?       | 4.4 (for bug fixes)
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39195
| License       | MIT
| Doc PR        | n/a

Xdebug 3.0 removed the function `xdebug_is_enabled()`. To detect if Xdebug 3.0 is installed (it doesn't even need to be enabled to reproduce the bug) i added `function_exists('xdebug_info')`. AFAIS `xdebug_info()` is available in Xdebug >= 3.0 only.

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Exception/AutowiringFailedException.php [hunk 1]
```diff
@@ -23,7 +23,10 @@ public function __construct(string $serviceId, $message = '', int $code = 0, \Th
     {
         $this->serviceId = $serviceId;
 
-        if ($message instanceof \Closure && \function_exists('xdebug_is_enabled') && xdebug_is_enabled()) {
+        if (
+            $message instanceof \Closure
+            && (\function_exists('xdebug_is_enabled') && xdebug_is_enabled() || \function_exists('xdebug_info'))
+        ) {
             $message = $message();
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Exception/AutowiringFailedException.php:30]: @derickr FYI we have this check here because xdebug changes the behavior of PHP in a way that prevents us from doing a lazy evaluation here: native PHP allows one to set the $message property of throwables to a stringable. We use this below.
It would be great if xdebug could preserve this behavior, if possible.

Comment (vertexvaar) [reply src/Symfony/Component/DependencyInjection/Exception/AutowiringFailedException.php:30]: I think i came up with a better solution. Please check the second commit, which replaces all xdebug-related stuff with resolving the messageCallback when the __toString method is called.
This will also eliminate performance drawbacks when xdebug is installed.

Comment (vertexvaar) [reply src/Symfony/Component/DependencyInjection/Exception/AutowiringFailedException.php:30]: > I think i came up with a better solution. Please check the second commit, which replaces all xdebug-related stuff with resolving the messageCallback when the __toString method is called.
> This will also eliminate performance drawbacks when xdebug is installed.

I take this back. `getMessage()` does not return the actual message.

**Review by jderusse — APPROVED** [review]

**Comment by derickr** [comment]
On Fri, 27 Nov 2020, Nicolas Grekas wrote:

> @derickr FYI we have this check here because xdebug changes the 
> behavior of PHP in a way that prevents us from doing a lazy evaluation 
> here: native PHP allows one to set the $message property of throwables 
> to a stringable. We use this below. It would be great if debug could 
> preserve this behavior, if possible.

Xdebug shouldn't be changing behaviour, can you file a bug report at 
https://bugs.xdebug.org ?

cheers,
Derick

-- 
PHP 7.4 Release Manager
Host of PHP Internals News: https://phpinternals.news
Like Xdebug? Consider supporting me: https://xdebug.org/support
https://derickrethans.nl | https://xdebug.org | https://dram.io
twitter: @derickr and @xdebug

**Comment by nicolas-grekas** [comment]
I submitted an issue at https://bugs.xdebug.org/view.php?id=1907

**Review by nicolas-grekas — APPROVED** [review]
I'm going to merge this, but this also means that when xdebug is installed, autowiring exceptions are always computed. This makes the process slower.
It'd be great if the underlying issue in xdebug could be addressed somehow.

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @vertexvaar.
