### PR TITLE
[Translation] Fix for translation:update command updating ICU messages

### LINKED ISSUE #36459: translation:update command not generating/updating ICU variant
**Symfony version(s) affected**: 5.0.3 - 5.0.7

**Description**  
As per my comment on #34713:

Even though I have the PHP intl extension installed, the command refuses to output the messages in the ICU format.

**How to reproduce**  
Using the tools listed below, start a project and add translation keys (e.g. in a form or directly in a template) and run the `translation:update` command.

**Additional context**  
Here's what I'm currently using:
* Windows 10
* PHP 7.4.2
* symfony/intl 5.0.7
* symfony/translation 5.0.7

### PR DESCRIPTION
**Pull request by art6f**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36459
| License       | MIT

If `translation:update` command executed with option `--domain=messages`  – it  ignore `messages-intl-icu` file and just create new `messages`

Method `TranslationUpdateCommand::filterCatalogue()` on `MessageCatalogue::all()` method to get all messages for domain
But `MessageCatalogue::all()` method disredard `intl-icu` domains and simply merge all.

[Translation] added $strict parameter for MessageCatalogueInterface::all() to be able to get only defined domain messages
[FrameworkBundle] modified translation:update command to respect intl-icu domain

### CODE REVIEW

File: src/Symfony/Component/Translation/MessageCatalogue.php [hunk 1]
```diff
@@ -65,10 +65,14 @@ public function getDomains()
     /**
      * {@inheritdoc}
      */
-    public function all(string $domain = null)
+    public function all(string $domain = null, $strict = false)
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/MessageCatalogue.php:68]: adding an argument would break BC, we need to find another idea

Comment (artemoliynyk) [reply src/Symfony/Component/Translation/MessageCatalogue.php]: Right, I forget BC, sorry.

Better idea, I can come with at the moment, is to return intl-icu domain if requested and then do diff for all and intl-icu messages.

Please review new version

**Comment by artemoliynyk** [comment]
Travis build fails on `Symfony\Bundle\FrameworkBundle\Tests\Functional\MailerTest::testMailerAssertions()` test, but it's OK for me on local setup.
I believe this is unrelated erro to this PR

File: src/Symfony/Component/Translation/Tests/MessageCatalogueTest.php [hunk 2]
```diff
@@ -39,9 +39,9 @@ public function testAll()
         $this->assertEquals($messages, $catalogue->all());
 
         $messages = ['domain1+intl-icu' => ['foo' => 'bar']] + $messages + [
-            'domain2+intl-icu' => ['bar' => 'foo'],
-            'domain3+intl-icu' => ['biz' => 'biz'],
-        ];
+                'domain2+intl-icu' => ['bar' => 'foo'],
+                'domain3+intl-icu' => ['biz' => 'biz'],
+            ];
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Tests/MessageCatalogueTest.php:44]: please revert these changes

File: src/Symfony/Component/Translation/Tests/MessageCatalogueTest.php [hunk 3]
```diff
@@ -56,6 +56,33 @@ public function testAll()
         $this->assertEquals($messages, $catalogue->all());
     }
 
+    /**
+     * @depends testAll
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Tests/MessageCatalogueTest.php:60]: what does this mean? can it be removed?

File: src/Symfony/Component/Translation/Tests/MessageCatalogueTest.php [hunk 4]
```diff
@@ -56,6 +56,33 @@ public function testAll()
...
+
+        // merged, intl-icu ignored
+        $this->assertEquals(['bar' => 'foo', 'biz' => 'biz'], $catalogue->all('domain2'));
+
+        // intl-icu ignored
+        $messagesExpected = [
+            'domain1' => ['foo' => 'bar'],
+            'domain2' => ['bar' => 'foo', 'biz' => 'biz'],
+        ];
+        $this->assertEquals($messagesExpected, $catalogue->all());
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Tests/MessageCatalogueTest.php:83]: can you use `assertSame()` everywhere?

**Review by nicolas-grekas — COMMENTED** [review]
Thanks, here are some remaining minor comments.

File: src/Symfony/Component/Translation/Tests/MessageCatalogueTest.php (hunk 3 above)
Comment (artemoliynyk) [reply src/Symfony/Component/Translation/Tests/MessageCatalogueTest.php]: sure, removed.

**Review by nicolas-grekas — APPROVED** [review]

**Review by yceruto — APPROVED** [review]
Thanks !

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @artemoliynyk.
