### PR TITLE
[Console] Use a partial buffer in SymfonyStyle

### LINKED ISSUE #39156: Component/Console/Output/BufferedOutput buffer memory overflow
https://github.com/symfony/symfony/blob/49eafee03323253328d76ec9cb4c515f94d2f202/src/Symfony/Component/Console/Output/BufferedOutput.php#L37

see laravel issue: https://github.com/laravel/framework/issues/35340

Steps To Reproduce:

```
use Symfony\Component\Console\Input\StringInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Style\SymfonyStyle;

include __DIR__ . "/../vendor/autoload.php";

$input = new StringInput('test');
$output = new ConsoleOutput();

$style = new SymfonyStyle($input, $output);

$str = 'teststr';
$num = 26843546;//(128 << 20) / 5; "tstr\r\n"  php memory 128M

for ($i =0;$i<$num;$i++) {
    $style->writeln($str);
}

echo 'success';
```

PR: https://github.com/symfony/symfony/pull/26863

Need to call bufferedOutput->fetch

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39156
| License       | MIT
| Doc PR        | -

Symfony style needs to buffer output in order to get the last 2 chars in order to prepend Block.

By using a `BufferedOutput` symfony bufferize everything while it not needed.

This PR adds a new `TrimmedBufferOutput` that keep only the N last chars.

### CODE REVIEW

File: src/Symfony/Component/Console/Output/TrimmedBufferOutput.php [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\Console\Output;
+
+use Symfony\Component\Console\Exception\InvalidArgumentException;
+use Symfony\Component\Console\Formatter\OutputFormatterInterface;
+
+/**
+ * A BufferedOutput that keep only the last N chars
```
Comment (chalasr) [inline src/Symfony/Component/Console/Output/TrimmedBufferOutput.php]:
```suggestion
 * A BufferedOutput that keeps only the last N chars.
```

**Review by chalasr — COMMENTED** [review]
The bug exists on lower branches, isn't it? 
Can we mark the new class as internal to make this target 4.4?

**Comment by jderusse** [comment]
> The bug exists on lower branches, isn't it?
> Can we mark the new class as internal to make this target 4.4?

Thanks, I picked the wrong base branch when creating the PR

File: src/Symfony/Component/Console/Output/TrimmedBufferOutput.php (hunk 1 above)
Comment (jderusse) [reply src/Symfony/Component/Console/Output/TrimmedBufferOutput.php]: fixed

File: src/Symfony/Component/Console/Style/SymfonyStyle.php [hunk 2]
```diff
@@ -46,7 +47,7 @@ class SymfonyStyle extends OutputStyle
     public function __construct(InputInterface $input, OutputInterface $output)
     {
         $this->input = $input;
-        $this->bufferedOutput = new BufferedOutput($output->getVerbosity(), false, clone $output->getFormatter());
+        $this->bufferedOutput = new TrimmedBufferOutput($output->getVerbosity(), false, unserialize(serialize($output->getFormatter())), \DIRECTORY_SEPARATOR === '\\' ? 4 : 2);
```
Comment (jderusse) [inline src/Symfony/Component/Console/Style/SymfonyStyle.php]: somebody knows how to perform a deep clone?

Issue is, Output and BufferOutput share the same formatter's styles, which has a state and count the number of closing tags. This does not works well when the same line is sent several time.

Note: previous implementation may suffer the same bug when the message contains less than 4 chars (ie. `</>X`)

**Comment by javiereguiluz** [comment]
I'm not sure we need to fix this "issue". In the original issue report, the reproducer in #39156 is a code that writes a string 26 millions of times. How is that realistic?

**Comment by stof** [comment]
@javiereguiluz the original laravel issue was abotu a long-running command outputting lots of different things. The minimal reproducer is not meant to be a realistic case, but a minimal case.

**Comment by javiereguiluz** [comment]
The original Laravel issue report says that this problem occurs _"After running it for a long time"_. How long is "long" considered here? Hours? Days? Weeks? I wouldn't try to fix this because for now it looks like a "non issue". (In PHP you must restart long-running processes from time to time to avoid these "memory leaks" or other issues, right?)

**Comment by jderusse** [comment]
The script leaks. The fix is not that complexe...
I don't understand why we shouldn't fix it...

> In PHP you must restart long-running processes from time to time to avoid these "memory leaks" or other issues, right?)

NOooo!!!! Why people believe that having a memory leak is the normal behavior? 

I hope I won't offend you @javiereguiluz , but I'm really tired of people saying PHP sucks and have a bad memory management.
Running a PHP script for days is perfectly fine!

File: src/Symfony/Component/Console/Style/SymfonyStyle.php (hunk 2 above)
Comment (jderusse) [reply src/Symfony/Component/Console/Style/SymfonyStyle.php]: This specific bug is adressed by #39168

**Comment by z5864703** [comment]
> The original Laravel issue report says that this problem occurs _"After running it for a long time"_. How long is "long" considered here? Hours? Days? Weeks? I wouldn't try to fix this because for now it looks like a "non issue". (In PHP you must restart long-running processes from time to time to avoid these "memory leaks" or other issues, right?)

If this is not the problem, our script can run forever without memory leaks.

This has nothing to do with the length of time the problem occurred. If the business needs it, the trigger point can be reached in a day. If this function is not used, it will never be triggered. What is the significance of this function? Knowing that there is a problem that can be solved, but through a method that is not a solution?

File: src/Symfony/Component/Console/Style/SymfonyStyle.php (hunk 2 above)
Comment (stof) [inline src/Symfony/Component/Console/Style/SymfonyStyle.php]: Can this be reverted to use `clone $output->getFormatter()` now that the bug is fixed ?

File: src/Symfony/Component/Console/Style/SymfonyStyle.php [hunk 3]
```diff
@@ -449,9 +450,7 @@ private function autoPrependText(): void
 
     private function writeBuffer(string $message, bool $newLine, int $type): void
     {
-        // We need to know if the two last chars are PHP_EOL
-        // Preserve the last 4 chars inserted (PHP_EOL on windows is two chars) in the history buffer
```
Comment (stof) [inline src/Symfony/Component/Console/Style/SymfonyStyle.php:453]: maybe this comment needs to be preserved somewhere, to explain why we have this buffer

File: src/Symfony/Component/Console/Tests/Style/SymfonyStyleTest.php [hunk 4]
```diff
@@ -115,4 +117,17 @@ public function testGetErrorStyleUsesTheCurrentOutputIfNoErrorOutputIsAvailable(
 
         $this->assertInstanceOf(SymfonyStyle::class, $style->getErrorStyle());
     }
+
+    public function testMemoryConsumation()
```
Comment (stof) [inline src/Symfony/Component/Console/Tests/Style/SymfonyStyleTest.php]: `Consumption`

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Console/Style/SymfonyStyle.php [hunk 5]
```diff
@@ -21,12 +21,13 @@
...
 use Symfony\Component\Console\Helper\TableSeparator;
 use Symfony\Component\Console\Input\InputInterface;
-use Symfony\Component\Console\Output\BufferedOutput;
 use Symfony\Component\Console\Output\OutputInterface;
+use Symfony\Component\Console\Output\TrimmedBufferOutput;
 use Symfony\Component\Console\Question\ChoiceQuestion;
 use Symfony\Component\Console\Question\ConfirmationQuestion;
 use Symfony\Component\Console\Question\Question;
 use Symfony\Component\Console\Terminal;
+use Symfony\Component\VarDumper\Cloner\VarCloner;
```
Comment (derrabus) [inline src/Symfony/Component/Console/Style/SymfonyStyle.php]:
```suggestion
```

**Review by derrabus — CHANGES_REQUESTED** [review]

**Review by derrabus — APPROVED** [review]

File: src/Symfony/Component/Console/Style/SymfonyStyle.php (hunk 2 above)
Comment (jderusse) [reply src/Symfony/Component/Console/Style/SymfonyStyle.php]: done

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @jderusse.

**Comment by derrabus** [comment]
@jderusse: Can you please have a look at b047064842c534d5d417d22294b89825c1753967? When merging your changes to 5.1, I had to add an extra line to the test to make it pass again.

**Comment by jderusse** [comment]
> @jderusse: Can you please have a look at [b047064](https://github.com/symfony/symfony/commit/b047064842c534d5d417d22294b89825c1753967)? When merging your changes to 5.1, I had to add an extra line to the test to make it pass again.

Thanks for pinging. Yes, you fix is OK. 
I'm not sure why it broke, but the idea of the tests remains the same: 
1. warm the buffer
2. memorize the size of the memory
3. run the script several times
4. assert the size didn't changed

**Comment by derrabus** [comment]
Yes, the test still proves that the leak is stopped. 👍🏻
