### PR TITLE
fix: clarify parameter name to comply with deprecations from #34074

### LINKED ISSUE #37824: denyAccessUnlessGranted still allows $attributes although it was deprecated since Symfony 4.4
**Symfony version(s) affected**: > 5.0

**Description**  
In the AbstractController the Method Signature for `denyAccessUnlessGranted` accepts still an array of attributes as the parameter name implicates $attributes... using still an array breaks further implementations without having the deprecation notice removed lately in the `AuthorizationChecker`.
So this is not breaking the system, but resulting in a nested array with all attributes passed to the Voter->supports-Method.

**How to reproduce**  
passing an array to the `denyAccessUnlessGranted` Method -> 
`$this->denyAccessUnlessGranted(['foo', 'bar'], $bazz);`

### PR DESCRIPTION
**Pull request by Nijusan**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37824 
| License       | MIT
| Doc PR        | 

[FrameworkBundle] Clarify parameter name from `$attributes` to `$attribute` in `AbstractController:denyUnlessGranted`

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php [hunk 1]
```diff
@@ -67,6 +67,7 @@ public function setContainer(ContainerInterface $container): ?ContainerInterface
     {
         $previous = $this->container;
         $this->container = $container;
+        $this->container = $container;
```
Comment (fabpot) [inline src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php:70]: Should be reverted

**Review by fabpot — CHANGES_REQUESTED** [review]
Can you also fix `AuthorizationCheckerInterface::isGranted()` description? It mentions attributes instead of attribute.

**Review by chalasr — APPROVED** [review]
For 4.4

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Nijusan.
