### PR TITLE
[Form] keep labels from configured choices

### LINKED ISSUE #61927: [Form] `EnumType`: The array keys of the `choices` array are not used as labels
### Symfony version(s) affected

7.3.4

### Description

As requested by @xabbuh at https://github.com/symfony/symfony-docs/pull/21003#discussion_r2398311716

When passing an array with keys as `choices` like this:
```php
$builder->add('alignment', EnumType::class, [
    'choices' => [
       'foo' =>  TextAlign::Left,
       'bar' => TextAlign::Right,
    ],
]);
```
Then the labels in the form should be "foo" and "bar". However, I'm just getting the enum cases' names, so the array keys are effectively ignored.

### How to reproduce

See above.

### Possible Solution

Same as with `ChoiceType`: If present, use array keys as labels

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #61927
| License       | MIT

### CODE REVIEW

**Review by alexandre-daubois — APPROVED** [review]

**Comment by ThomasLandauer** [comment]
Works for me :-)

One minor note: If just *one* array element has a key, like this:
```php
[
   'foo' =>  MyEnum::Open,
    MyEnum::Closed,
]
```
Then the outcome is:
> * foo
> * 0

I haven't tried this with `ChoiceType`, and I guess it's the intended behavior anyway - so that's fine for me :-)

**Comment by ThomasLandauer** [comment]
I've created a docs PR: https://github.com/symfony/symfony-docs/pull/21457

**Review by yceruto — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Comment by alcohol** [comment]
This seems to break our autocomplete which uses [grouping](https://symfony.com/doc/current/reference/forms/types/choice.html#grouping-options) and is setup as follows:

```php
            'choices' => [
                (string) t('label.paymentmethod.active', [], 'admin.form') => array_filter(
                    PaymentMethod::cases(),
                    static fn (PaymentMethod $method): bool => ! \in_array($method, PaymentMethod::internal, true) && ! \in_array($method, PaymentMethod::legacy, true)
                ),
                (string) t('label.paymentmethod.internal', [], 'admin.form') => PaymentMethod::internal, // internal here is an array of enum values
                (string) t('label.paymentmethod.legacy', [], 'admin.form') => PaymentMethod::legacy, // same goes for legacy
            ],
```

Are we doing something obscure or unsupported? It was working fine until this release..

**Comment by xabbuh** [comment]
@alcohol Your use case seems valid to me. I didn't think of the possibility to group choices with the `choices` option. Can you open a new issue please so this regression doesn't get lost?

File: src/Symfony/Component/Form/Extension/Core/Type/EnumType.php [hunk 1]
```diff
@@ -30,7 +30,13 @@ public function configureOptions(OptionsResolver $resolver): void
...
             ->setAllowedValues('class', enum_exists(...))
             ->setDefault('choices', static fn (Options $options): array => $options['class']::cases())
-            ->setDefault('choice_label', static fn (\UnitEnum $choice) => $choice instanceof TranslatableInterface ? $choice : $choice->name)
+            ->setDefault('choice_label', static function (Options $options) {
+                if (\is_array($options['choices']) && !array_is_list($options['choices'])) {
+                    return null;
+                }
+
+                return static fn (\UnitEnum $choice) => $choice instanceof TranslatableInterface ? $choice : $choice->name;
+            })
```
Comment (Seb33300) [inline src/Symfony/Component/Form/Extension/Core/Type/EnumType.php:39]: @xabbuh That change seems to break `BackedEnum` implementing `TranslatableInterface`?
See https://github.com/EasyCorp/EasyAdminBundle/pull/7243
