### PR TITLE
Hide definitions bearing the `container.excluded` tag

### LINKED ISSUE #50417: Service Container no working "exclude"
### Symfony version(s) affected

6.2.8

### Description

In version `6.2.8` I get a Service Container error. Files and folders are not excluded. Instead, folders are added to the container as `Service ID`: [folder/filename] and `Class name`: [folder/filename]. At the same time, it works on version `6.1.*`

Example: https://drive.google.com/file/d/1AfmbLkxpFGtixKnATdKToJUa5x_inl8v/view?usp=share_link
For example, `Command`, `Query`, `Entity` are folders, but they are specified as services in the container. 

### How to reproduce

Configuration:

**src/Kernel.php**
```php
<?php

declare(strict_types=1);

namespace App;

use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;

final class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    private function configureContainer(ContainerConfigurator $container): void
    {
        $configDir = $this->getConfigDir();
        $container->import($configDir . '/{packages}/*.{php,yaml}');
        $container->import($configDir . '/{services}/*.{php,yaml}');
        $container->import('./**/config.{php,yaml}');// import config from module
    }
}
```

**src/Auth/config.php**
```php
<?php

declare(strict_types=1);

namespace App\Auth;

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

use function Symfony\Component\DependencyInjection\Loader\Configurator\service;

return static function (ContainerConfigurator $configurator): void {
    $services = $configurator
        ->services()
        ->defaults()
        ->autowire()
        ->autoconfigure();

    $services->load('App\\Auth\\', '.')->exclude([
        './config.php',
        './Command',
        './Entity',
        './Query',
        './Test',
        './Validator/Constraint',
    ]);

    $services->load('App\\Auth\\Command\\', './Command/**/Handler.php');
    $services->load('App\\Auth\\Entity\\', './Entity/**/*Repository.php');
    $services->load('App\\Auth\\Query\\', './Query/**/Handler.php');
};
```
**config**
Global file `services.yaml` not used.

Example App: https://github.com/Myks92/symfony-service-container/tree/master

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Myks92**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | yes
| New feature?  | no
| | Depreciation? | no
| Tickets       | Fix #50417
| License       | MIT
| Doc PR        | -

Normally I test whether the exclusion rules from the service container of my bundles work correctly by just using the `debug:container` command and looking whether my excluded services occur in the last.
However, due to the latest changes in #46279 all folders and subfulders (excluded or not) are always in this list.

You need to open the definition to see if it was excluded:
Service Container

For example, `Command`, `Query`, `Entity` are folders, but they are specified as services in the container. 

This PR fixes this problem to ignore definitions bearing the container.excluded tag if those are to be hidden for Descriptors: `JsonDescriptor`,  `MarkdownDescriptor`, `TextDescriptor` and `XmlDescriptor`. 

After fixes problem:
Снимок экрана 2023-05-27 в 17 03 19

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Can you please check if this issue happens on 6.3? We might have fixed this as an improvement already.

File: src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php [hunk 1]
```diff
@@ -103,6 +103,10 @@ protected function describeContainerServices(ContainerBuilder $builder, array $o
                 continue;
             }
 
+            if (!$showHidden && $builder->hasDefinition($serviceId) && $builder->getDefinition($serviceId)->hasTag('container.excluded')) {
```
Comment (chalasr) [inline src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php]: This won’t work if the service is an alias (see hasDefinition() vs has())

**Comment by MatTheCat** [comment]
@nicolas-grekas I can confirm this still happens with Symfony 6.3.0 RC2

File: src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php (hunk 1 above)
Comment (MatTheCat) [inline src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php]: Use the existing `$service` variable instead of calling `$builder->getDefinition($serviceId)` (this is the case for all descriptors).

Comment (Myks92) [reply src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php]: Thank you for your help! Fixed it.

Comment (Myks92) [reply src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php]: Thanks. I’m fixed with help use existing variable `$service`. Do you have any other comments?

**Review by MatTheCat — APPROVED** [review]
LGTM, maybe just make line breaks consistent 👍

File: src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php [hunk 2]
```diff
@@ -106,6 +106,9 @@ protected function describeContainerServices(ContainerBuilder $builder, array $o
             if ($service instanceof Alias) {
                 $data['aliases'][$serviceId] = $this->getContainerAliasData($service);
             } elseif ($service instanceof Definition) {
+                if (!$showHidden && $service->hasTag('container.excluded')) {
```
Comment (chalasr) [inline src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php]: Hidden services are true services. Mixing them with excluded services would give a false impression that those are available for use. Let's just skip them in all cases

**Review by chalasr — CHANGES_REQUESTED** [review]

File: src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php (hunk 2 above)
Comment (Myks92) [reply src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php]: I agree. Rule for hidden services already exists in [102](https://github.com/symfony/symfony/blob/48a333caf283e005fd49a7824a90533f430121e3/src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php#L102) line, so I deleted this. Is that better or did I misunderstand you?

Comment (chalasr) [reply src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php]: 👍

**Comment by chalasr** [comment]
Looks good, thank you for contributing.
Can you have a look ContainerDebugCommandTest and see if you can add a test to prevent future regressions?

**Comment by Myks92** [comment]
@chalasr, I added tests for `Descriptor` and `ContainerDebugCommand`. Is that what you need?

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @Myks92.

File: src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/TextDescriptor.php [hunk 3]
```diff
@@ -198,6 +198,10 @@ protected function describeContainerServices(ContainerBuilder $builder, array $o
             }
 
             if ($definition instanceof Definition) {
+                if ($definition->hasTag('container.excluded')) {
+                    unset($serviceIds[$key]);
```
Comment (xabbuh) [inline src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/TextDescriptor.php:202]: Don't we have to do this in the other descriptors as well?

Comment (MatTheCat) [reply src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/TextDescriptor.php:202]: `TextDescriptor` does this because it loops twice on `$serviceIds` but this is not the other descriptors’ case, so I’d say this is not needed :thinking:
