### PR TITLE
Fix table header seperator wrapping

### LINKED ISSUE #45520: [Console] setColumnMaxWidth does not wrap header cells nicely
### Symfony version(s) affected

5.4.3, 6.x possibly too

### Description

I'd like setColumnMaxWidth to also wrap headers nicely. Currently it adds an extra border between the header lines.

This is how the output currently looks like:

```
------ ------------------------------------------------------------
  Line   src/Type/JustNullableTypeTrait.php (in context of class
 ------ ------------------------------------------------------------
         PHPStan\Type\StringType)
 ------ ------------------------------------------------------------
  81     Method PHPStan\Type\StringType::doFoo() has no return type
         specified.
 ------ ------------------------------------------------------------
```

This is how I'd like it to look like:

```
------ ------------------------------------------------------------
  Line   src/Type/JustNullableTypeTrait.php (in context of class
         PHPStan\Type\StringType)
 ------ ------------------------------------------------------------
  81     Method PHPStan\Type\StringType::doFoo() has no return type
         specified.
 ------ ------------------------------------------------------------
```

### How to reproduce

In context of SymfonyStyle child class:

```php
		$table = $this->createTable();
		$table->setHeaders($headers);
		$table->setRows($rows);
		$table->setColumnMaxWidth(1, 60);

		$table->render();
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alamirault**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45520
| License       | MIT
| Doc PR        | 

Before PR, a new seperator is added foreach split line in header

```php
        $table = new Table();
        $table
            ->setHeaders([
                [
                    'Publication',
                    'Very long header with a lot of information',
                ],
            ])
            ->setRows([
                [
                    '1954',
                    'The Lord of the Rings, by J.R.R. Tolkien',
                ],
            ])
            ->setColumnMaxWidth(1, 30);
```
Before PR:

image

After PR
image

(Fabbot cannot be green (break unit tests))

### CODE REVIEW

**Comment by alamirault** [comment]
Any feedback on this PR will be appreciated. Thanks

File: src/Symfony/Component/Console/Helper/Table.php [hunk 1]
```diff
@@ -624,13 +642,16 @@ private function buildTableRows(array $rows): TableRows
 
         return new TableRows(function () use ($rows, $unmergedRows): \Traversable {
             foreach ($rows as $rowKey => $row) {
-                yield $row instanceof TableSeparator ? $row : $this->fillCells($row);
+                $rowGroup = [
+                    $row instanceof TableSeparator ? $row : $this->fillCells($row),
+                ];
```
Comment (chalasr) [inline src/Symfony/Component/Console/Helper/Table.php]: as per our coding standards
```suggestion
        $rowGroup = [$row instanceof TableSeparator ? $row : $this->fillCells($row)];
```

File: src/Symfony/Component/Console/Helper/Table.php [hunk 2]
```diff
@@ -659,7 +680,7 @@ private function fillNextRows(array $rows, int $line): array
     {
         $unmergedRows = [];
         foreach ($rows[$line] as $column => $cell) {
-            if (null !== $cell && !$cell instanceof TableCell && !is_scalar($cell) && !(\is_object($cell) && method_exists($cell, '__toString'))) {
+            if (null !== $cell && !$cell instanceof TableCell && !\is_scalar($cell) && !(\is_object($cell) && method_exists($cell, '__toString'))) {
```
Comment (chalasr) [inline src/Symfony/Component/Console/Helper/Table.php]: this change should be reverted as (it's useful for some functions only, `is_scalar` is not in the list).

**Review by chalasr — CHANGES_REQUESTED** [review]
Looks good to me, just some minor comments.
I think the bug exists on 4.4 as well, can you confirm and rebase if it's the case?

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @alamirault.
