### PR TITLE
[PropertyInfo] Update DoctrineExtractor for new DBAL 4 BIGINT type

### LINKED ISSUE #54418: [PropertyInfo] DoctrineExtractor incompatible type resolution with DBAL 4 or ORM 2.19
### Symfony version(s) affected

7.0.3

### Description

Preface
-------

With the recent release of Doctrine ORM 3 and DBAL 4 there has been a major change in at least one column type.

[bigint](https://www.doctrine-project.org/projects/doctrine-dbal/en/4.0/reference/types.html#bigint) now reads: 

> Maps and converts 8-byte integer values. 
> ...
> 
> Values retrieved from the database are always converted to PHP's `integer` type if they are within PHP's integer range 
> or `string` if they aren't.

Additionally, if you did not yet make the jump to ORM 3/DBAL 4 and are using ORM 2.19 which acts like Sf `.4` and the
next major `.0` you can use `int` typehints in your PHP code with a `bigint` column type if you go for a `string|int` 
union. You can read more about it in this [issue: Invalid field error reported for bigint DBAL type](https://github.com/doctrine/orm/issues/11073). 

Another case would be if you know that your project's tech will always rely on `int` within your `PHP_INT_MAX` you could
also override the default `bigint` type and bind it to `int`.

This is also dependent of your DB engine too, but generally speaking, all of the above are true for _pgsql_. How one goes about handling this Doctrine _hiccup_ is up to developer's choice and from my POV any of the solutions that can be used for Doctrine is fine. 

Symfony
-------

Let's assume that you are using one of the methods to have Doctrine _happy_ but without jeopardising your project. If your project is in any capacity in need of denormalizing request data into PHP objects this is the next step that breaks. 

At one point, for objects, the `AbstractObjectNormalizer::getTypes()` is called, which in turn makes use of 
`PropertyInfoExtractor` to resolve the `Type` of a `bigint` property that is **in some way** type-hinted as `int` and request data will use `int` values too. 

`DoctrineExtractor::getTypes()` will internally try to get the PHP type of `bigint` which for now is always going to map
it to `string`. 

```php
// at about line ~250
return match ($doctrineType) {
    Types::SMALLINT,
    Types::INTEGER => Type::BUILTIN_TYPE_INT,
    Types::FLOAT => Type::BUILTIN_TYPE_FLOAT,
    Types::BIGINT, // <- here
    Types::STRING,
    Types::TEXT,
    Types::GUID,
    Types::DECIMAL => Type::BUILTIN_TYPE_STRING, // <- mapped to string
    // ...
```

This causes a gate-keeping effect with the following exception message: 

`The type of the "bigint" attribute for class "IHaveNumbers" must be one of "string" ("int" given).`

For this there are some possible ways to go about it. 

A) You can use `DISABLE_TYPE_ENFORCEMENT` on your context and the value is used as is, letting it be handled on code level
which may result in `\Error` issues. 
B) Switch your property to `string` only and add more cast juggling.
C) Switch your property to `string` and also reflect this in your general API so that request data is now only `string`.
D) Update / Decorate `DoctrineExtractor` with the following _hack solution_: 

```php
// new block
if (Types::BIGINT === $typeOfField) {
    return [
        new Type(Type::BUILTIN_TYPE_INT, $nullable),
        new Type(Type::BUILTIN_TYPE_STRING, $nullable),
    ];
}
// continue how it used to be
if (!$builtinType = $this->getPhpType($typeOfField)) {
    return null;
}
```

I went for option D because I really want to have `bigint` typed to `int` and not to `string` as I have a project that
only delivers an API with API Platform. So keeping my JSON Schema consistent is top priority. 

It works, but I am not sure if it is _a)_ a solution and _b)_ a preferred solution.

### How to reproduce

I can create a simple project if the description above is not enough. The easiest way would be to:

- use API Platform with one resource and pgsql for storage. 
- use orm 3 and dbal 4
- add 1 property with bigint
- send a JSON body with int values in your property 
- The type of the "bigint" attribute for class "IHaveNumbers" must be one of "string" ("int" given).

### Possible Solution

In case `DoctrineExtractor` cannot be updated one can also play around with attributes. Below I have my example in my project: 

```php
#[ORM\Column(type: Types::BIGINT)]
#[ApiProperty(
    jsonSchemaContext: ['type' => 'integer'],
    extraProperties: [SchemaPropertyMetadataFactory::JSON_SCHEMA_USER_DEFINED => true]
)]
#[Context(denormalizationContext: [AbstractObjectNormalizer::DISABLE_TYPE_ENFORCEMENT => true])]
#[Assert\Type(type: 'int')]
#[Assert\Positive]
#[Assert\Range(max: 12_345_678_901)]
private $bigInt;
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by llupa**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | not sure
| Deprecations? | no
| Issues        | Fix #54418 
| License       | MIT

## Additional Considerations

This issue looks pretty straight forward, but it has had me running in circles not being sure how to exactly interpret it. The new return type to make it work with DBAL 4 is _fine_, but it is neither an intersection nor a union type, which **will** cause trouble for other libs if they do not explicitly check each. 

There is not easy way to get which DBAL version is the extractor is running against, so trying to optimize the flow is _tricky_. I am opening this PR to have a starting point in the hopes that maintainers of this package have more historical context than me. 

I have tried to document as much as possible about this in the issue linked above. 🍻

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php [hunk 1]
```diff
@@ -165,7 +165,7 @@ public static function typesProvider(): array
         return [
             ['id', [new Type(Type::BUILTIN_TYPE_INT)]],
             ['guid', [new Type(Type::BUILTIN_TYPE_STRING)]],
-            ['bigint', [new Type(Type::BUILTIN_TYPE_STRING)]],
+            ['bigint', [new Type(Type::BUILTIN_TYPE_STRING)]], // change? separate for DBAL 3 vs 4?
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php]: I suppose yes

**Review by nicolas-grekas — COMMENTED** [review]
Thanks for the PR.
Did you check if this applies to branch 5.4 maybe?

File: src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php (hunk 1 above)
Comment (llupa) [reply src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php]: Yes, Sf 5.4 can be paired with ORM3/DBAL4 but IDK if the team wants a separate test for this? I noticed another test had `@requires PHP 8.1`, I assumed that it would be better to have one with DBAL3 and one with DBAL4.

Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php]: either separate tests, or just an expectation that changes depending on which version is installed - that'd be fine also

Comment (llupa) [reply src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php]: Hey Nicolas, 

as Alexander [hinted](https://github.com/doctrine/dbal/issues/6365), you can use composer to [get installed versions](https://getcomposer.org/doc/07-runtime.md#knowing-whether-package-x-is-installed-in-version-y). Do you think this is worth it? Or should I just update the test with a new return expected value?

Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php]: Let's rather go with a feature test. There must be some class that's unique to one or the other version.

Comment (wouterj) [reply src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php]: For instance, check if the `\Doctrine\DBAL\Tools\Console\ConsoleRunner` class exists. If it is, we're on DBAL <4.

Comment (derrabus) [reply src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php]: You can check if the `BigIntType` has a `getName()` method. That should not be the case on DBAL 4.

Comment (llupa) [reply src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php]: ~Ok, I actually even thought about having 2 extractors, one per DBAL major, and then in the compiler pass to set the respective class with the class exists check~. 

I will do ~class~method exists as it is simple and straightforward, composer checks are fine, but, it implies composer is there to begin with 🤷

Comment (derrabus) [reply src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php]: > it implies composer is there to begin with 🤷

That does not sound like a strong requirement. 😄 

That being said, on this repository, we rather do feature detection than relying on Composer's runtime API, so `method_exists()` is the way to go here.

Comment (llupa) [reply src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php]: @nicolas-grekas I updated the PR with Alexander's hint/tip/?order. If there are still changes I'd need to apply let me know :+1:

File: src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php [hunk 2]
```diff
@@ -162,10 +163,17 @@ public function testExtractEnum()
 
     public static function typesProvider(): array
     {
+        // DBAL 4 has a special fallback strategy for BINGINT (int -> string)
+        if (!method_exists(BigIntType::class, 'getName')) {
+            $expectedBingIntType = [new Type(Type::BUILTIN_TYPE_INT), new Type(Type::BUILTIN_TYPE_STRING),];
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Tests/PropertyInfo/DoctrineExtractorTest.php]:
```suggestion
            $expectedBingIntType = [new Type(Type::BUILTIN_TYPE_INT), new Type(Type::BUILTIN_TYPE_STRING)];
```

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @llupa.
