### PR TITLE
[String] Fix plural of word ending by pus

### LINKED ISSUE #53685: Pluralization of "Campus" is incorrect
### Symfony version(s) affected

All

### Description

When using the method pluralize of the class Symfony\Component\String\Inflector\EnglishInflector on the word "Campus" you end up with "Campi" when you should get "Campuses"

### How to reproduce

Execute pluralize('campus') you'll get 'campi'

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Fan2Shrek**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #53685
| License       | MIT

Fix the pluralization of words ending by 'pus' like campus.
Previously was campi instead of campuses

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/String/Inflector/EnglishInflector.php [hunk 1]
```diff
@@ -291,6 +291,9 @@ final class EnglishInflector implements InflectorInterface
         // circuses (circus)
         ['suc', 3, true, true, 'cuses'],
 
+        // campus (campuses)
```
Comment (lyrixx) [inline src/Symfony/Component/String/Inflector/EnglishInflector.php]: I'm not sure, but previous lines are in this way
```suggestion
        // campuses (campus)
```

Comment (Fan2Shrek) [reply src/Symfony/Component/String/Inflector/EnglishInflector.php]: Done ty :)

File: src/Symfony/Component/String/Tests/Inflector/EnglishInflectorTest.php [hunk 2]
```diff
@@ -298,6 +298,7 @@ public static function pluralizeProvider()
             ['waltz', 'waltzes'],
             ['wife', 'wives'],
             ['icon', 'icons'],
+            ['hippocampus', 'hippocampuses'],
```
Comment (derrabus) [inline src/Symfony/Component/String/Tests/Inflector/EnglishInflectorTest.php]: Strange that you've picked this example because the plural of "hippocampus" is actually "hippocampi".

https://www.merriam-webster.com/dictionary/hippocampus

**Review by derrabus — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/String/Tests/Inflector/EnglishInflectorTest.php (hunk 2 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/String/Tests/Inflector/EnglishInflectorTest.php]: well, both are accepted apparently :)
latin roots...

Comment (Fan2Shrek) [reply src/Symfony/Component/String/Tests/Inflector/EnglishInflectorTest.php]: Should I change it anyways ?

Comment (derrabus) [reply src/Symfony/Component/String/Tests/Inflector/EnglishInflectorTest.php]: > well, both are accepted apparently :) latin roots...

Is that so? I could only find sources that list "hippocampi" that the only plural. Also, "hippocampuses" causes pain in my hippocampus. 😬 Sorry. 😓 

Anyway, "hippocampus" is currently pluralized to "hippocampi" which is correct and I think we should not change it. Regarding the your initial issue, "campus" should be pluralized to "campuses". Can you fix that and leave "hippocampus" intact?

**Review by derrabus — APPROVED** [review]

**Review by javiereguiluz — APPROVED** [review]

**Review by maxbeckers — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @Fan2Shrek.

File: src/Symfony/Component/String/Inflector/EnglishInflector.php [hunk 3]
```diff
@@ -291,6 +291,12 @@ final class EnglishInflector implements InflectorInterface
         // circuses (circus)
         ['suc', 3, true, true, 'cuses'],
 
+        // hippocampi (hippocampus)
+        ['supmacoppih', 11, false, false, 'hippocampi'],
+
+        // campuses (campus)
+        ['sup', 3, true, true, 'puses'],
```
Comment (stof) [inline src/Symfony/Component/String/Inflector/EnglishInflector.php:298]: What about other words ending in `pus` besides `campus` and `hippocampus` ? If we don't have a generic rule, maybe we should actually return the 2 options for the `pus` ending.

Comment (Fan2Shrek) [reply src/Symfony/Component/String/Inflector/EnglishInflector.php:298]: After some research its seems that only `hippocampus` is irregular
Words like `opus` or `octopus` are plurialized with `puses`

I'm a non-native english speaker if someone can confirm :eyes:
