### PR TITLE
Keeping backward compatibility with legacy FlattenException usage

### LINKED ISSUE #33929: New ErrorRenderer FlattenException not compatible with old one Debug FlattenException
**Symfony version(s) affected**: 4.4-dev

### Description

Want to move discussion from  #33918 and #33916 to this issue. 

The new ErrorRenderer FlattenException is not compatible with the old Debug FlattenException. And in some places you now get the new FlattenException which crashes current project codes.

### How to reproduce

**1. Case: Create a custom ExceptionController::showAction**

Has `symfony/debug` installed:

```php
use Symfony\Component\Debug\Exception\FlattenException;

public function showAction(Request $request, FlattenException $exception, DebugLoggerInterface $logger = null);
```

This works as expected in 4.3 and in 4.4 you will get an error `Symfony\Component\ErrorRenderer\Exception\FlattenException` given but expected `Symfony\Component\Debug\Exception\FlattenException` 

**2. Case: FlattenException without Debug installed**

In 4.4-dev if a dependency has not debug actually installed the Debug class still exists because of a class_alias in the ErrorRenderer 

```php
use Symfony\Component\Debug\Exception\FlattenException;

FlattenException::create(new \Exception(), 200);
```

This will fail as the new FlattenException doesn't implement create function. If we rename to new from createFromThrowable to create this will the following would fail which is also possible currently:

```php
use Symfony\Component\Debug\Exception\FlattenException;

FlattenException::createFromThrowable(new \Exception(), 200);
````

So both create and createFromThrowable should be available in 4.4.

### Possible Solution

The `Symfony\Component\ErrorRenderer\Exception\FlattenException` should extend from the `Symfony\Component\Debug\Exception\FlattenException` to keep BC Compatibility in 4.x this can then be removed in 5.0.

### Additional Context

I think its a similiar issue we had with the KernelBrowser and the Client here:

#31762 which was then later fixed in: #31881

### PR DESCRIPTION
**Pull request by yceruto**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | yes
| Tickets       | Fix #33929
| License       | MIT
| Doc PR        | -

### CODE REVIEW

File: src/Symfony/Component/ErrorRenderer/Exception/FlattenException.php [hunk 1]
```diff
@@ -37,6 +39,11 @@ class FlattenException
     private $file;
     private $line;
 
+    public static function create(\Exception $exception, int $statusCode = null, array $headers = []): self
```
Comment (yceruto) [inline src/Symfony/Component/ErrorRenderer/Exception/FlattenException.php]: Restoring for a smooth migration, it can be deprecated in 5.1.

File: src/Symfony/Component/ErrorRenderer/composer.json [hunk 2]
```diff
@@ -33,6 +33,7 @@
     },
     "autoload": {
         "psr-4": { "Symfony\\Component\\ErrorRenderer\\": "" },
+        "classmap": [ "Resources/stubs/Exception/FlattenException.php" ],
```
Comment (yceruto) [inline src/Symfony/Component/ErrorRenderer/composer.json]: this would fix the compiler error mentioned here https://github.com/symfony/symfony/issues/33929#issuecomment-539985732

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @yceruto.

**Comment by luchaninov** [comment]
ugly quickfix. put to `config/bundles.php` before `return ...`

    // TODO: remove after merge https://github.com/symfony/symfony/pull/33941
    if (!class_exists(\Symfony\Component\Debug\Exception\FlattenException::class, false)) {
        class_alias(\Symfony\Component\ErrorRenderer\Exception\FlattenException::class, \Symfony\Component\Debug\Exception\FlattenException::class);
    }
