### PR TITLE
[Mailer] Fix usage of stream_set_timeout in case of microseconds

### LINKED ISSUE #53705: [Mailer] Socket stream: Implict conversion from float 0.1 to int loses precision
### Symfony version(s) affected

6.4.2

### Description

Wrong parameter type for stream_set_timeout() [here](https://github.com/symfony/mailer/blob/7.0/Transport/Smtp/Stream/SocketStream.php#L163C9-L163C27).

[PHP docs](https://www.php.net/manual/en/function.stream-set-timeout.php)
`stream_set_timeout(resource $stream, int $seconds, int $microseconds = 0): bool`

### How to reproduce

Run `$mailer->getTransporter()->setTimeout(0.1);` with smtp configuration.

### Possible Solution

```
stream_set_timeout($this->stream, (int) $timeout, (int) ((float) $timeout - (int) $timeout) * 1000000);
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aleksejs1**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #53705
| License       | MIT

Fix usage of stream_set_timeout() in case if stream timeout consist of second decimals.

### CODE REVIEW

File: src/Symfony/Component/Mailer/Transport/Smtp/Stream/SocketStream.php [hunk 1]
```diff
@@ -190,4 +190,18 @@ protected function getReadConnectionDescription(): string
     {
         return $this->url;
     }
+
+    protected function getTimeoutSeconds(): int
+    {
+        return (int) $this->getTimeout();
+    }
+
+    protected function getTimeoutMicroseconds(): int
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mailer/Transport/Smtp/Stream/SocketStream.php]: These two methods should be removed, they serve no purpose as we don't want people to be able to change the related logic. Let's inline everything.

Comment (aleksejs1) [reply src/Symfony/Component/Mailer/Transport/Smtp/Stream/SocketStream.php]: Changed. Inline looks better.

**Comment by nicolas-grekas** [comment]
Thank you @aleksejs1.
