### PR TITLE
[Serializer] Fix discriminator class mapping with allow_extra_attributes=false

### LINKED ISSUE #61887: [Serializer] Cannot use discriminator class mapping with allow_extra_attributes=false
### Symfony version(s) affected

6.4.x

### Description

When using discriminator class mapping, if the `AbstractNormalizer::ALLOW_EXTRA_ATTRIBUTES` context option is set to `false`, the type property is not considered a valid attribute and an `ExtraAttributesException` is thrown.

### How to reproduce

Run `composer require symfony/serializer symfony/property-access` and run the following script

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Serializer\Attribute\DiscriminatorMap;
use Symfony\Component\Serializer\Mapping\ClassDiscriminatorFromClassMetadata;
use Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory;
use Symfony\Component\Serializer\Mapping\Loader\AttributeLoader;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

#[DiscriminatorMap(
    typeProperty: 'type',
    mapping: [
        'type_a' => TypeA::class,
        'type_b' => TypeB::class,
    ]
)]
interface TestInterface
{

}

class TypeA implements TestInterface
{
}

class TypeB implements TestInterface
{
}


$classMetadataFactory = new ClassMetadataFactory(new AttributeLoader());
$discriminator = new ClassDiscriminatorFromClassMetadata($classMetadataFactory);
$normalizers = [
    new ObjectNormalizer($classMetadataFactory, null, null, null, $discriminator),
];
$serializer = new Serializer($normalizers, []);

$obj = $serializer->denormalize(
    ['type' => 'type_a'],
    TestInterface::class,
    null,
    [AbstractNormalizer::ALLOW_EXTRA_ATTRIBUTES => false]
);

var_dump($obj);
```

### Possible Solution

Add a check in `ObjectNormalizer::isAllowedAttribute` for the type property if a mapping is present.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by chris54721**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #61887
| License       | MIT

Make sure that the discriminator mapping type property is considered an allowed attribute when the `AbstractNormalizer::ALLOW_EXTRA_ATTRIBUTES` context option is set to `false`.

### CODE REVIEW

**Comment by xabbuh** [comment]
Don't we also have to patch the `GetSetMethodNormalizer` and the `PropertyNormalizer`?

**Comment by chris54721** [comment]
@xabbuh you're right, I have patched those as well, thanks.

File: src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php [hunk 1]
```diff
@@ -190,6 +190,12 @@ protected function isAllowedAttribute($classOrObject, string $attribute, ?string
 
         $class = \is_object($classOrObject) ? $classOrObject::class : $classOrObject;
 
+        if (null !== $discriminatorMapping = $this->classDiscriminatorResolver?->getMappingForMappedObject($classOrObject)) {
+            if ($attribute === $discriminatorMapping->getTypeProperty()) {
+                return true;
+            }
+        }
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php]: everywhere:
```suggestion
        if ($this->classDiscriminatorResolver?->getMappingForMappedObject($classOrObject)?->getTypeProperty() === $attribute) {
            return true;
        }
```

Comment (chris54721) [reply src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php]: done

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @chris54721.
