### PR TITLE
[Serializer] Fix constructor parameter type override when property type extractor returns a different type

### LINKED ISSUE #59353: [HttpKernel] Conversion of type in #[MapQueryString] constructor is no longer accepted since Symfony 7.1.10
### Symfony version(s) affected

7.1.10

### Description

Since https://github.com/symfony/symfony/pull/59134, DTO that changes type in a constructor is no longer accepted. 

Trigger of this seem to be that in a given PR, `disable_type_enforcement` no longer defaults to true. However, this might be a deeper issue, as thanks to type juggling in constructor there should not be any type mismatch in the first place. Notice that in reproducer, although (private) property is declared to be an array, constructor accepts string. Hence, denormalization should accept string.

I bet this is another issue of a kind in https://github.com/symfony/symfony/issues/46918, since serializer has no way to distinguish class property named same way as constructor parameter

### How to reproduce

Query DTO:
```php
readonly class ScimQueryInput
{
    /** @var list<string> */
    private array $attributes;

    public function __construct(string $attributes = '') {
        $this->attributes = $attributes ? explode(',', $attributes) : [];
    }

    public function isAttributeAllowed(string $attribute): bool
    {
        return !\in_array($attribute, $this->attributes, true);
    }
}
```

Controller:
```php
class GetUsersController
{
    #[Route('/api/datasync/scim/{connectorId}/Users')]
    public function __invoke(#[MapQueryString] ScimQueryInput $queryInput = new ScimQueryInput()): Response 
    {
        return new Response();
    }
}
```

Call: `/api/datasync/scim/Users?attributes=displayName,userName`

Response:
```
      Current response status code is 404, but 200 expected. (Behat\Mink\Exception\ExpectationException)
    │
    │  {
    │      "type": "https://symfony.com/errors/validation",
    │      "title": "Validation Failed",
    │      "detail": "attributes: This value should be of type array.",
    │      "violations": [
    │          {
    │              "propertyPath": "attributes",
    │              "title": "This value should be of type array.",
    │              "template": "This value should be of type {{ type }}.",
    │              "parameters": {
    │                  "{{ type }}": "array"
    │              }
    │          },
    │      ]
    │  }
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59353
| License       | MIT

After the property-type extractor returns a type, the new block checks whether the constructor parameter's reflection type is compatible with it. If not, it overrides $type with the constructor parameter's actual type.
This compatibility check doesn't handle union/intersection types, unless the TypeInfo component is installed.

### CODE REVIEW

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 1]
```diff
@@ -973,11 +973,56 @@ protected function denormalizeParameter(\ReflectionClass $class, \ReflectionPara
...
             $parameterData = $this->validateAndDenormalizeLegacy($type, $class->getName(), $parameterName, $parameterData, $format, $context);
-        } else {
-            $parameterData = $this->validateAndDenormalize($type, $class->getName(), $parameterName, $parameterData, $format, $context);
+            $parameterData = $this->applyCallbacks($parameterData, $class->getName(), $parameterName, $format, $context);
+
+            return $this->applyFilterBool($parameter, $parameterData, $context);
+        }
+
+        if (($parameterType = $parameter->getType()) instanceof \ReflectionNamedType) {
+            if ($parameterType->isBuiltin()) {
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php:1024]: This is exaclty what `ReflectionTypeResolver` does.
Maybe we can check if `symfony/type-info` is available and then use that class to be more precise (handle unions, intersections, etc)?

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php:1024]: like that?

Comment (mtarld) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php:1024]: I think you can leverage `Type::isSatisfiedBy` to avoid iterate over the type tree yourself.

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php:1024]: good call, updated thanks!

**Review by mtarld — APPROVED** [review]

**Comment by derrabus** [comment]
This change caused a regression for us: #63513
