### PR TITLE
[DoctrineBridge] Add username to UserNameNotFoundException

### LINKED ISSUE #39878: [doctrine-bridge] UserEntityProvider does not set username field on UsernameNotFoundException
**Symfony version(s) affected**: 5.2.1

**Description**  

When logging in with a username which does not exist using `EntityUserProvider` in `doctrine-bridge` the Exception thrown does not contain a username. This causes problems with translating the exception.

**How to reproduce**  

Create a login form with `UserEntityProvider` from `doctrine-bridge` and try to login with a username which does not exist.

**Possible Solution**  

Similar to `InMemoryUserProvider` call `setUsername` to set the username in the exception.

https://github.com/symfony/symfony/blob/4a053e5fed4422a834596da6a643978b603db18e/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php#L102

### PR DESCRIPTION
**Pull request by qurben**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #39878  
| License       | MIT
| Doc PR        | 

Adds username to UserNameNotFoundException when thrown from EntityUserProvider.

In other places there are no tests for this and I am not sure if the current setup even allows asserting if exceptions contain fields, besides the default ones.

### CODE REVIEW

**Comment by xabbuh** [comment]
This exception is thrown in other places as well. Can you update them too?

**Comment by qurben** [comment]
@xabbuh I updated all other cases. There are some cases where the username is set on this exception after the fact such as in the following line:
https://github.com/symfony/symfony/blob/494ef421c554a78b38c6779c4b7deb9a20d89923/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php#L69

I am not sure if these are still needed (they probably are)

File: src/Symfony/Component/Ldap/Security/LdapUserProvider.php [hunk 1]
```diff
@@ -73,14 +73,20 @@ public function loadUserByUsername($username)
...
 
         if (!$count) {
-            throw new UsernameNotFoundException(sprintf('User "%s" not found.', $username));
+            $ex = new UsernameNotFoundException(sprintf('User "%s" not found.', $username));
+            $ex->setUsername($username);
+
+            throw $ex;
         }
 
         if ($count > 1) {
```
Comment (xabbuh) [inline src/Symfony/Component/Ldap/Security/LdapUserProvider.php:92]: here is one more usage

**Comment by xabbuh** [comment]
Looks like we could update the `Symfony\Component\Security\Guard\Provider\GuardAuthenticationProvider` class as well.

**Comment by qurben** [comment]
I added the other two cases

**Review by xabbuh — APPROVED** [review]

File: src/Symfony/Bridge/Doctrine/Security/User/EntityUserProvider.php [hunk 2]
```diff
@@ -92,7 +95,10 @@ public function refreshUser(UserInterface $user)
 
             $refreshedUser = $repository->find($id);
             if (null === $refreshedUser) {
-                throw new UsernameNotFoundException('User with id '.json_encode($id).' not found.');
+                $ex = new UsernameNotFoundException('User with id '.json_encode($id).' not found.');
+                $ex->setUsername(json_encode($id));
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Security/User/EntityUserProvider.php]: why json_encoding here?

File: src/Symfony/Bridge/Doctrine/Security/User/EntityUserProvider.php [hunk 3]
```diff
@@ -92,7 +95,10 @@ public function refreshUser(UserInterface $user)
 
             $refreshedUser = $repository->find($id);
             if (null === $refreshedUser) {
-                throw new UsernameNotFoundException('User with id '.json_encode($id).' not found.');
+                $ex = new UsernameNotFoundException('User with id '.json_encode($id).' not found.');
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Security/User/EntityUserProvider.php]: I'd suggest naming this variable just `$e`, as we do in `catch` blocks.

File: src/Symfony/Bridge/Doctrine/Security/User/EntityUserProvider.php (hunk 2 above)
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Security/User/EntityUserProvider.php]: why json_encoding here?

Comment (qurben) [reply src/Symfony/Bridge/Doctrine/Security/User/EntityUserProvider.php]: See for example

https://github.com/symfony/symfony/blob/91d8bebfaca159bcbd0ab9bde78ca1790474f73b/src/Symfony/Bridge/Doctrine/Tests/Security/User/EntityUserProviderTest.php#L129

Here `$id` is not a string or even string like, while the username field is documented to be a string. I guess `UsernameNotFoundException` does not convey what the exact error is, because `$id` is not a username.

**Review by nicolas-grekas — APPROVED** [review]

**Review by wouterj — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you @qurben.
