### PR TITLE
[DoctrineBridge]  indexBy could reference to association columns

### LINKED ISSUE #37982: [DoctrineBridge][DoctrineExtractor] Exception in form validation for field with indexBy
**Symfony version(s) affected**: 4.4.11

**Description**  
Form validation throws an exception on relation field which contains indexBy definition:
`No mapping found for field 'foo_id' on class 'App\Entity\Foo'.`

**How to reproduce**  
```php
    /**
     * @var Collection|Foo[]
     * @ORM\OneToMany(targetEntity="App\Entity\Foo", mappedBy="bar", indexBy="foo_id", cascade={"persist", "remove"}, orphanRemoval=true)
     * @Assert\Valid()
     */
    private $foos;
```

**Possible Solution**  
When I change indexBy from "foo_id" to "foo" no exception is thrown. However indexBy will stop working as it suppose to.

**Additional context**  
I have updated project from Symfony v.4.3.4 where it was working.

### PR DESCRIPTION
**Pull request by juanmiguelbesada**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #37982 
| License       | MIT
| Doc PR        | -

This is my approach to solve #37982. It partials reverts @xabbuh PR #38604 

This is my first Symfony contribution, so please, tell me if I need to do something more or something is wrong.

Also, this bug affects 4.x and 5.x versions. I think merging in this branches is done automatically. If not, please tell me.

Thanks you

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/PropertyInfo/DoctrineExtractor.php [hunk 1]
```diff
@@ -110,10 +110,20 @@ public function getTypes($class, $property, array $context = [])
...
-                    $typeOfField = $subMetadata->getTypeOfField($subMetadata->getFieldForColumn($indexColumn));
+                    $fieldName = $subMetadata->getFieldForColumn($associationMapping['indexBy']);
+                    $typeOfField = $subMetadata->getTypeOfField($fieldName);
+
+                    // Maybe $fieldName is an association
+                    if (null === $typeOfField) {
+                        $associationMapping = $subMetadata->getAssociationMapping($fieldName);
+
+                        /** @var ClassMetadataInfo $subMetadata */
+                        $indexProperty = $subMetadata->getSingleAssociationReferencedJoinColumnName($fieldName);
```
Comment (xabbuh) [inline src/Symfony/Bridge/Doctrine/PropertyInfo/DoctrineExtractor.php]: Shouldn't we add some kind of check that the column name used here is in fact the join column?

**Comment by nicolas-grekas** [comment]
Please check #38861 also.

**Comment by juanmiguelbesada** [comment]
I will take a look

**Review by jderusse — COMMENTED** [review]
People at Doctrine says it could/shoud be a property (https://github.com/doctrine/orm/issues/8018#issuecomment-586008227)
Which leads to issue in Symfony:  #38861 

Given this is not clear, I suggest to supports both cases:
- IndexBy point to a property
- IndexBy point to a column_name

**Comment by bwach** [comment]
> People at Doctrine says it could/shoud be a property ([doctrine/orm#8018 (comment)](https://github.com/doctrine/orm/issues/8018#issuecomment-586008227))
> Which leads to issue in Symfony: #38861
> 
> Given this is not clear, I suggest to supports both cases:
> 
>     * IndexBy point to a property
> 
>     * IndexBy point to a column_name

This is also reflected in description for ClassMetadataInfo which we use here (depending on how you understand the whole paragraph)

https://github.com/doctrine/orm/blob/c1943624ab1260c629316bab104dc5130c060154/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php#L516

describing "indexBy" as:

`Specification of a field on target-entity that is used to index the collection by.`

So it should be one of the fields on the entity, not a column.
I guess  the problem in the long run is that doctrine doesn't validate this, so you can type anything into the "indexBy" annotation and it will still work.

**Comment by xabbuh** [comment]
How does Doctrine behave for one or the other? Does it ignore the attribute? Does it try to map the column to a property or vice versa?

**Comment by juanmiguelbesada** [comment]
PR updated fixing #38861 (I hope) and adding tests

**Review by xabbuh — APPROVED** [review]
LGTM

**Comment by nicolas-grekas** [comment]
Thank you @juanmiguelbesada.
