### PR TITLE
[Serializer] Fix AbstractObjectNormalizer not considering pseudo type false

### LINKED ISSUE #45151: [Serializer] AbstractObjectNormalizer does not consider pseudo type false
### Symfony version(s) affected

5.4

### Description

When you have a PHP 8.0 object where an attribute uses the pseudo type `false` (in a union type) you can't denormalize an array to that object.

### How to reproduce

```
    public function testDenormalizeFalsePseudoType(): void
    {
        if (version_compare(PHP_VERSION, '8.0.0') < 0) {
            $this->markTestSkipped('This feature requires PHP 8.0');
        }

        // given a serializer that extracts the attribute types of an object via ReflectionExtractor
        $propertyTypeExtractor = new PropertyInfoExtractor(
            [],
            [new ReflectionExtractor()],
            [],
            [],
            []
        );
        $objectNormalizer = new ObjectNormalizer(null, null, null, $propertyTypeExtractor);

        $serializer = new Serializer([$objectNormalizer]);

        // when denormalizing some data into an object where an attribute uses the false pseudo type
        /** @var Php80Dummy $object */
        $object = $serializer->denormalize(
            [
                'canBeFalseOrString' => false,
            ],
            Php80Dummy::class
        );

        // then the attribute that declared false was filled correctly
        $this->assertFalse($object->canBeFalseOrString);
    }
```

### Possible Solution

Pull request follows

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ThomasNunninger**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no
| Tickets       | Fix #45151
| License       | MIT
| Doc PR        | 

AbstractObjectNormalizer does not consider pseudo type false (bug #45151)

When you have a PHP 8.0 object where an attribute uses the pseudo type false (in a union type) you can't denormalize an array to that object.

### CODE REVIEW

**Comment by ThomasNunninger** [comment]
Sorry, I have no clue how to fix the failing tests for PHP 7.2 & PHP 7.4 and the appveyor build.

The issue probably is because of https://github.com/symfony/symfony/pull/45154/files#diff-748599238ed60d6c9394adf834ea5b2dcbb1af524b9583600dce1eed23e47ab8 line 18 where I declare a property as `false|string` what is not allowed before PHP 8.0. (I skipped the test itself that uses that class. But I assume, some tools try to include the PHP 8.0 class and fail due to new attribute declaration.)

Any idea how to fix that?

File: src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php [hunk 1]
```diff
@@ -699,6 +700,37 @@ public function testExtractAttributesRespectsContext()
         $this->assertSame(['foo' => 'bar', 'bar' => 'foo'], $normalizer->normalize($data, null, ['include_foo_and_bar' => true]));
     }
 
+    public function testDenormalizeFalsePseudoType()
+    {
+        if (version_compare(\PHP_VERSION, '8.0.0') < 0) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php]: should use `@requires PHP 8` annotation instead

File: src/Symfony/Component/Serializer/Tests/Php80Dummy.php [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+/*
+ * This file is part of the Symfony package.
+ *
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+declare(strict_types=1);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Tests/Php80Dummy.php:12]: should be removed

**Comment by nicolas-grekas** [comment]
Thank you @ThomasNunninger.
