### PR TITLE
[Uid] Add `@return non-empty-string` annotations to `AbstractUid` and relevant functions

### LINKED ISSUE #59076: Add @return non-empty-string annotation to AbstractUid methods for better user identifier support
### Symfony version(s) affected

7.2

### Description

In Symfony 7.2, the UserInterface was updated to include a `@return non-empty-string` annotation for the getUserIdentifier() method. To maintain consistency and improve support for UUIDs as user identifiers, it would be beneficial to add similar return type annotations to relevant methods in the AbstractUid class.

### How to reproduce

add this to any entity you want that implements UserInterface

    #[ORM\Column(type: 'uuid', unique: true, nullable: false)]
    private Uuid $apiPublicKey;
    
    
    public function getUserIdentifier(): string
    {
        return $this->apiPublicKey->toString();
    }
    
if you are using code quality tools like psalm, then you will surely get below error

**the declared return type 'non-empty-string' for App\Entity\YOUR_CLASS::getUserIdentifier is more specific than the inferred return type 'string' (see https://psalm.dev/070)
    public function getUserIdentifier(): string**

**the type 'string' is more general than the declared return type 'non-empty-string' for App\Entity\YOUR_CLASS::getUserIdentifier (see https://psalm.dev/129)
        return $this->apiPublicKey->toString();**

    

### Possible Solution

adding the `@return non-empty-string` annotation to the following methods in the AbstractUid class:

- toBinary()
- toBase58()
- toBase32()
- toRfc4122()
- toHex()
- hash()
- toString()
- jsonSerialize()

By adding these annotations, we align the AbstractUid class with the new expectations in Symfony 7.2 and ensure consistency when using UUIDs as user identifiers.

### Additional Context

In Symfony 7.2, the UserInterface was updated to include a `@return non-empty-string` annotation for the getUserIdentifier() method. Since UUIDs are frequently used as user identifiers, adding the same level of type safety to the methods in AbstractUid (which are used to generate various representations of UUIDs) is important for several reasons:

1. **Consistency:** Aligning with the new Symfony 7.2 update ensures that the handling of user identifiers is consistent across the framework, especially when UUIDs are used.

2. **Improved Static Analysis:** The `@return non-empty-string` annotation improves static analysis tools like Psalm and PHPStan, making the return type explicit and allowing for better detection of potential issues.

3. **Better Tooling and IDE Support:** Adding specific return type annotations improves IDE autocomplete suggestions, refactoring support, and error detection.

### PR DESCRIPTION
**Pull request by niravpateljoin**
| Q             | A
| ------------- | ---
| Branch?       | 7.3 
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no 
| Issue | Fix #59076
| License       | MIT

This Merge Request introduces `@return non-empty-string` annotations to the AbstractUid class and other relevant functions in the Symfony UID component. By explicitly defining the return type as non-empty-string, this change improves type safety and ensures stricter static analysis when working with UIDs.

### Rationale
- Symfony 7.3 has adopted stricter type safety guidelines, including support for non-empty-string in interfaces like UserInterface::getUserIdentifier. Aligning the UID component with these standards improves consistency across the framework.
- Adding these annotations benefits developers by providing enhanced autocompletion and error detection in IDEs and tools like Psalm and PHPStan.

### Changes Made

- Updated PHPDoc comments in AbstractUid and related classes to specify `@return non-empty-string` for methods where applicable.
- Verified all usages of these methods to ensure compatibility with the stricter return type.

### Backward Compatibility

- This change does not affect backward compatibility, as it only updates PHPDoc annotations. The runtime behavior of the methods remains the same.

### CODE REVIEW

File: src/Symfony/Component/Uid/Tests/UuidReturnTypeTest.php [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+ * @psalm-type NonEmptyString = non-empty-string
+ */
+class UuidReturnTypeTest extends TestCase
+{
+    private const A_UUID_V4 = 'd6b3345b-8857-9074-a83c-b5988e765d98';
+
+    /**
+     * @psalm-return NonEmptyString
+     */
+    public function testToBinaryReturnsNonEmptyString(): void
```
Comment (derrabus) [inline src/Symfony/Component/Uid/Tests/UuidReturnTypeTest.php]: The annotation is wrong. This method does not return anything.

File: src/Symfony/Component/Uid/Tests/UuidReturnTypeTest.php [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+
+namespace Symfony\Component\Uid\Tests;
+
+use PHPUnit\Framework\TestCase;
+use Symfony\Component\Uid\Uuid;
+
+/**
+ * @psalm-type NonEmptyString = non-empty-string
+ */
+class UuidReturnTypeTest extends TestCase
```
Comment (derrabus) [inline src/Symfony/Component/Uid/Tests/UuidReturnTypeTest.php]: I don't see much value in this test, tbh.

**Review by derrabus — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Uid/Tests/UuidReturnTypeTest.php (hunk 1 above)
Comment (niravpateljoin) [reply src/Symfony/Component/Uid/Tests/UuidReturnTypeTest.php]: @derrabus yes this return type does not make any sense here, I have removed it, thank you.

File: src/Symfony/Component/Uid/Tests/UuidReturnTypeTest.php (hunk 2 above)
Comment (niravpateljoin) [reply src/Symfony/Component/Uid/Tests/UuidReturnTypeTest.php]: @derrabus yes this return type does not make any sense here, I have removed it, thank you.

Comment (derrabus) [reply src/Symfony/Component/Uid/Tests/UuidReturnTypeTest.php]: No. The whole test ist pointless. Please remove it.

Comment (niravpateljoin) [reply src/Symfony/Component/Uid/Tests/UuidReturnTypeTest.php]: @derrabus i have removed the test case, thank you

**Review by derrabus — APPROVED** [review]

File: src/Symfony/Component/Uid/CHANGELOG.md [hunk 3]
```diff
@@ -1,6 +1,10 @@
 CHANGELOG
 =========
 
+7.3
+---
+* Added `@return non-empty-string` annotations to methods in the `Uuid` class (e.g., `toBinary()`, `toBase58()`, `toBase32()`, `toRfc4122()`, etc.) to improve type safety and code clarity.
```
Comment (xabbuh) [inline src/Symfony/Component/Uid/CHANGELOG.md]:
```markdown
7.3
---

 * Add `@return non-empty-string` annotations to methods in the `Uuid` class (e.g., `toBinary()`, `toBase58()`, `toBase32()`, `toRfc4122()`, etc.) to improve type safety and code clarity
```

Comment (nicolas-grekas) [reply src/Symfony/Component/Uid/CHANGELOG.md]: Actually this should be removed as we list only new features in this file

Comment (niravpateljoin) [reply src/Symfony/Component/Uid/CHANGELOG.md]: sure, i have removed it

File: src/Symfony/Component/Uid/CHANGELOG.md [hunk 4]
```diff
@@ -1,6 +1,5 @@
 CHANGELOG
 =========
-
```
Comment (xabbuh) [inline src/Symfony/Component/Uid/CHANGELOG.md]: Please add back this line

Comment (niravpateljoin) [reply src/Symfony/Component/Uid/CHANGELOG.md]: i have added it

File: src/Symfony/Component/Uid/CHANGELOG.md [hunk 5]
```diff
@@ -1,9 +1,9 @@
...
 7.2
 ---
 
+
```
Comment (alexandre-daubois) [inline src/Symfony/Component/Uid/CHANGELOG.md]: This line should be reverted

File: src/Symfony/Component/Uid/CHANGELOG.md (hunk 4 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/Uid/CHANGELOG.md]: It is still present and should be reverted, like the other line in this file

**Review by xabbuh — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
the error looks related:
CleanShot 2024-12-07 at 11 49 20@2x

any clue @derrabus ?

**Comment by alexandre-daubois** [comment]
The diff patch file located in `github/expected-missing-return-types.diff` should be updated as well because the newly added annotation should appear in it I guess?

The command to generate the diff again should be at the top of the file

**Comment by OskarStark** [comment]
Needs
* https://github.com/symfony/symfony/pull/59114

**Comment by derrabus** [comment]
Thank you @niravpateljoin.
