### PR TITLE
[Serializer] Respect default context in DateTimeNormalizer::denormalize

### LINKED ISSUE #29030: DateTimeNormalizer ignores format when denormalize
**Symfony version(s) affected**: 4.1.6

**Description**  
If I'm not mistaken, DateTimeNormalizer ignores format when denormalize

**How to reproduce**  

```php
<?php
require_once __DIR__.'/vendor/autoload.php';
use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;

$format = 'd/m/Y';
$string = '01/10/2018';
$dateTimeNormalizer = new DateTimeNormalizer($format);
$date = \DateTime::createFromFormat($format, $string);

// Normalize OK, shows '01/10/2018'
var_dump($dateTimeNormalizer->normalize($date)); 

$date2 = $dateTimeNormalizer->denormalize($date->format($format),\DateTime::class);
// Denormalize KO, shows '10/01/2018' instead of '01/10/2018'
// when day is gretter than 12, this throw an PHP Fatal error
var_dump($date2->format($format)); 
```

**Possible Solution**  
Use the format attribute  of class DateTimeNormalizer in the denormalize method (line 79)

**Additional context**

### PR DESCRIPTION
**Pull request by hultberg**
| Q             | A
| ------------- | ---
| Branch?       | 4.4 
| Bug fix?      | yes
| New feature?  |no 
| Deprecations? | no 
| Tickets       | Fix #29030 
| License       | MIT
| Doc PR        | 

Hey there. :wave: 

I'm bringing my first code patch to symfony today and it's for fixing a bug I encountered today while working with DateTimeNormalizer. In my project I have set a default date format in the service container and I noticed that the denormalized date did not follow my set date format (I enforce time but the serialized date did not contain the time stamp which should have failed when using DateTime::createFromDate). After some debugging I discovered the issue described in issue #29030 

`DateTimeNormalizer::normalize` respects the date time format in context or default context while `DateTimeNormalizer::denormalize` only respects the former. This patch adds logic to denormalize too attempt create a DateTime object from the default context format (by default set to `\DateTime::RFC3339`) with createFromFormat and then if that fails continue on with the current behaviour. In my opinion this patch does not break the symfony BC promise as it simply adds another way to denormalize the date time.

**One issue:** There are no error handling when creating the date time from default context as the logic just continues on which might give the impression to the developer that the denormalization with the specific format worked correctly. I was not able to find a way to handle any error and keeping BC.
**Future tough:** At some point the `new DateTime` call in denormalize should be deprecated since creating a date time with createFromFormat is considered "safer" in my eyes as it's very explicit while the call to `new DateTime` is implicit about the date format and must perform parsing and guessing of the intended format (explained over at https://www.php.net/manual/en/datetime.formats.php). Another thing about `new DateTime` is the terriable error handling as you must catch a `\Exception` which means you catch "what ever" exception that can exist, even `\ErrorException` since `\ErrorException extends \Exception`.

Fixes #29030
Alternative PR (closed) #33813

### CODE REVIEW

**Comment by hultberg** [comment]
I targeted the wrong branch so the milestone is now wrong.

**Comment by ro0NL** [comment]
> There are no error handling when creating the date time from default context as the logic just continues on which might give the impression to the developer that the denormalization with the specific format worked correctly. I was not able to find a way to handle any error and keeping BC.

We could preserve $defaultDateTimeErrors, and hint about it when the constructor fallback fails too.

> At some point the new DateTime call in denormalize should be deprecated since creating a date time with createFromFormat is considered "safer" in my eyes as it's very explicit while the call to new DateTime is implicit about the date format 

We could argue the formatted value in a raw payload is already validated, before being passed to a deserializer :)

That said, i think the datetime-constructor-as-fallback is a generally fine approach, for what is an implementation detail. If you get a DateTime, your value is denormalized.

edit: it also enables robustness-principle by default :)

**Comment by hultberg** [comment]
@ro0NL 
> We could argue the formatted value in a raw payload is already validated, before being passed to a deserializer :)

Can you elaborate on that the _raw payload is already validated_? Are there a "normal apporch" to use a validator with the raw payload? In my real world example I deserialize some JSON payload into a object then I validate it with symfony validator. I have had to override DateTimeNormalizer to catch any errors which are later cough by a custom date validator I made.

> We could preserve $defaultDateTimeErrors, and hint about it when the constructor fallback fails too.

That seems like a good solution to at the least provide some hints about the default context format failing.

**Comment by ro0NL** [comment]
> Are there a "normal apporch" to use a validator with the raw payload?

Im still on a mission to shift the paradigm :) https://github.com/symfony/symfony/pull/43047#issuecomment-922485772

"validation before hydration" benefits object design IMHO.

File: src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php [hunk 1]
```diff
@@ -113,6 +113,16 @@ public function denormalize($data, $type, $format = null, array $context = [])
             throw new NotNormalizableValueException(sprintf('Parsing datetime string "%s" using format "%s" resulted in %d errors: ', $data, $dateTimeFormat, $dateTimeErrors['error_count'])."\n".implode("\n", $this->formatDateTimeErrors($dateTimeErrors['errors'])));
         }
 
+        $defaultDateTimeFormat = $this->defaultContext[self::FORMAT_KEY] ?? null;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php:116]: why don't you patch L97 to this instead?
`$dateTimeFormat = $context[self::FORMAT_KEY] ?? $this->defaultContext[self::FORMAT_KEY] ?? null;`

Comment (ro0NL) [reply src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php:116]: we allow createFromFormat from defaultContext[FORMAT_KEY] to fail due BC, but generally we can't assume the default format fits all payloads

Comment (ogizanagi) [reply src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php:116]: Should we trigger a deprecation in case the fallback path is triggered, so we can remove it in Symfony 7+ to enforce the `defaultContext[FORMAT_KEY]` is honored?

**Review by ogizanagi — APPROVED** [review]
With additional deprecation as mentioned in https://github.com/symfony/symfony/pull/43329/files#r812202044

**Comment by fabpot** [comment]
@hultberg Are you still interested in finishing this PR? It looks like we are almost there.

**Comment by ogizanagi** [comment]
Well, this targets 4.4 as a bug fix, so we cannot add the deprecation I suggested. So this should be ready to merge as is.

**Comment by ogizanagi** [comment]
I added the deprecation and opened the discussion in #47095

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @hultberg.

File: src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php (hunk 1 above)
Comment (misaert) [reply src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php:116]: Symfony 7 is released. Is it planned to remove it?

Comment (xabbuh) [reply src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php:116]: Not yet as far as I can see. The first step to remove something in the next major release would be to deprecate it in a minor release before.
