### PR TITLE
[PropertyInfo] Make PhpDocExtractor compatible with phpDocumentor v5

### LINKED ISSUE #36049: [PropertyInfo] Not compatible with phpDocumentor v5
**Symfony version(s) affected**: v5.0.5 (all?)

**Description**  
Using the property-info component in combination with phpDocumentor v5 (phpdocumentor/reflection-docblock  5.1.0) results in exceptions being thrown when unknown/invald tags are parsed. Looks like in the latest version og phpDocumentor these tags are not skipped, but an instance of `InvalidTag` is returned.

```
Error: Call to undefined method phpDocumentor\Reflection\DocBlock\Tags\InvalidTag::getType()

.../vendor/symfony/property-info/Extractor/PhpDocExtractor.php:145
```

**How to reproduce**  
```
<?php

include 'vendor/autoload.php';

use Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor;

class SomeClass {
    /** @var  */
    public $foo;
}

$phpDocExtractor = new PhpDocExtractor();
$phpDocExtractor->getTypes(\SomeClass::class, 'foo');
```
**Possible Solution**  
Check for the value type of all values returned by `$docBlock->getTagsByName($tag)`

### PR DESCRIPTION
**Pull request by DerManoMann**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36049
| License       | MIT
| Doc PR        | N/A

Version 5 of phpDocumentor introduced some changes to the `getTagsByName()` method that break the `PhpDocExtractor`.

More specific, it now returns an instance of `InvalidTag` instead of `null` when parsing an invalid tag.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Can you please check if this change applies to branch 3.4, and rebase+retarget if yes?

**Review by stof — APPROVED** [review]

**Comment by DerManoMann** [comment]
> Can you please check if this change applies to branch 3.4, and rebase+retarget if yes?

@nicolas-grekas I think it does.

I also just found #36850 which makes this a duplicate - is it worth progressing this one too?

One major problem both PRs are facing is the lowest/highest dep testing as it means we end up with different behaviour depending on used version of phpDocumentor. 

Is there a recipe for how to deal with that? Conditional tests sounds a bit ugly to me, although detecting the new `InvalidTag` class as conditional would make sense...

**Comment by nicolas-grekas** [comment]
Conditional testing is the way to go yes.
Can you please compare with #36850 and decide which PR should be moved forward if there are significant differences?

**Comment by DerManoMann** [comment]
@nicolas-grekas I know I said this applies to the 3.4 branch too, but I think things are more complicated.

On 3.4 tests fails straight off due to BC breaking changes, for [example detection of `nullable`](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php#L69). That is unrelated this issue and I will require bigger changes, IMHO.

As far as this PR against 4.4 is concerned - I've made the tests conditional but struggle to find the right way to test for the new code. For some reason the PHP 7.1 tests on travis use phpdocumentor 5.0.0-alpha5. However, the new InvalidTag class was only introduced in alpha8...

Finally, there doesn't seem to be any progress on #36850, so I am happy to continue work on this PR if I could get some advice/guidance on the issues described above.

**Comment by DerManoMann** [comment]
@nicolas-grekas @stof not sure what the etiquette rules are here, but this needs a re-review and a call on whether 4.4 is the right place for it (it is, IMHO, as outlined in the previous comment)

File: src/Symfony/Component/PropertyInfo/Tests/Extractor/PhpDocExtractorTest.php [hunk 1]
```diff
@@ -46,6 +47,36 @@ public function testParamTagTypeIsOmitted()
         $this->assertNull($this->extractor->getTypes(OmittedParamTagTypeDocBlock::class, 'omittedType'));
     }
 
+    protected function isPhpDocumentorV5()
```
Comment (nicolas-grekas) [inline src/Symfony/Component/PropertyInfo/Tests/Extractor/PhpDocExtractorTest.php:50]: can you please move this method after all public ones?

File: src/Symfony/Component/PropertyInfo/Tests/Extractor/PhpDocExtractorTest.php [hunk 2]
```diff
@@ -46,6 +47,36 @@ public function testParamTagTypeIsOmitted()
...
+    {
+        if (class_exists('\phpDocumentor\Reflection\DocBlock\Tags\InvalidTag')) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/PropertyInfo/Tests/Extractor/PhpDocExtractorTest.php:52]: should use a "use" statement

**Review by nicolas-grekas — APPROVED** [review]
(with minor comments)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @DerManoMann.
