### PR TITLE
[Mailer] Use recipients in sendmail transport

### LINKED ISSUE #41149: [Symfony/Mailer] mailer.envelope.recipients configuration does not work with sendmail
**Symfony version(s) affected**: 5.2.7 / 6.0.1

**Description**
Symfony/Mailer : The recipients feature ("Always Send to the same Address") does not work with sendmail 

**How to reproduce**
```php
<?php
ini_set('display_errors', true);

use Symfony\Component\Mailer\Envelope;
use Symfony\Component\Mailer\Mailer;
use Symfony\Component\Mailer\Transport\SendmailTransport;
use Symfony\Component\Mime\Address;
use Symfony\Component\Mime\Email;

require_once __DIR__ . './vendor/autoload.php';

// Configure your email
$sender    = new Address('from@mail.com');
$to        = new Address('to+fail@mail.com');
$recipient = new Address('to+success@mail.com');

// Use sendmail Transport
$mailer = new Mailer(new SendmailTransport());

// Force recipients to always override recipients
// https://symfony.com/doc/current/mailer.html#always-send-to-the-same-address
$enveloppe = new Envelope($sender, [$recipient]);

$email = new Email();
$email->text('content');
$email->from($sender);
$email->to($to);

$mailer->send($email, $enveloppe);
```

The email is sent to "to" instead of "recipient"

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41149
| License       | MIT
| Doc PR        | -

Supersedes #41150

### CODE REVIEW

File: src/Symfony/Component/Mailer/Transport/SendmailTransport.php [hunk 1]
```diff
@@ -86,6 +86,11 @@ protected function doSend(SentMessage $message): void
         $this->getLogger()->debug(sprintf('Email transport "%s" starting', __CLASS__));
 
         $command = $this->command;
+
+        if (!empty($recipients = $message->getEnvelope()->getRecipients())) {
```
Comment (fabpot) [inline src/Symfony/Component/Mailer/Transport/SendmailTransport.php:90]:
```suggestion
        if ($recipients = $message->getEnvelope()->getRecipients()) {
```

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @HypeMC.
