### PR TITLE
[HttpKernel] Change limit argument from string to integer for Profiler

### LINKED ISSUE #49656: [HttpKernel] Incorrect limit argument type: string instead of integer
### Symfony version(s) affected

All maintained, from 5.4 and above

### Description

Look on a third argument in a `\Symfony\Component\HttpKernel\Profiler\Profiler::find` method:
https://github.com/symfony/symfony/blob/v5.4.0/src/Symfony/Component/HttpKernel/Profiler/Profiler.php#L127

It is `?string`, but then it passed to `\Symfony\Component\HttpKernel\Profiler\ProfilerStorageInterface::find` it is awaited as `?int`:
https://github.com/symfony/symfony/blob/v5.4.0/src/Symfony/Component/HttpKernel/Profiler/ProfilerStorageInterface.php#L36

And it is passed in three places:

- https://github.com/symfony/symfony/blob/v5.4.0/src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php#L81 where we pass integer `1`
- https://github.com/symfony/symfony/blob/v5.4.0/src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php#L245
- https://github.com/symfony/symfony/blob/v5.4.0/src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php#L292

In cases 2 and 3 we assume to pass integer too, but due to it's a request payload, it should be casted from string.

### How to reproduce

If we use a strict type with file, which used `\Symfony\Component\HttpKernel\Profiler\Profiler::find` and pass an integer as a third argument, the IDE will highlight this line as an error.

ide

### Possible Solution

Change the limit argument from string to integer and cast it in case of passing from a request payload.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Aliance**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49656 
| License       | MIT

### CODE REVIEW

File: src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php [hunk 1]
```diff
@@ -289,7 +289,7 @@ public function searchAction(Request $request): Response
             return new RedirectResponse($this->generator->generate('_profiler', ['token' => $token]), 302, ['Content-Type' => 'text/html']);
         }
 
-        $tokens = $this->profiler->find($ip, $url, $limit, $method, $start, $end, $statusCode);
+        $tokens = $this->profiler->find($ip, $url, (int) $limit, $method, $start, $end, $statusCode);
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php]: changes on this file are not needed IMHO

Comment (Aliance) [reply src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php]: Why not? This variable now got from the request, so it should be a string, am I right?
https://github.com/symfony/symfony/blob/ca088d47cb4662335dde91914a82497091a2279d/src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php#L239

Comment (nicolas-grekas) [reply src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php]: because type casts are weaker than auto-casts performed by php so they're a dangerous practice
this would cast null to 0, which we do not want

Comment (Aliance) [reply src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php]: So looks like the validation should go before calling `find` method and after getting the payload from the request in that case. But afaiu, this is the WebProfiler bundle, for me, it looks safe enough for that type of cast. I am wrong?

Comment (nicolas-grekas) [reply src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php]: Anyway, this is unrelated the linked issue so I'm not sure why we're discussing this here.

**Comment by GromNaN** [comment]
The class is not final, are we sure we want to change the type here as a bugfix? I think it should target 6.3.

File: src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php (hunk 1 above)
Comment (Aliance) [reply src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php]: Okay, reverted these changes and rebased them.

**Comment by nicolas-grekas** [comment]
I think this is fine for 5.4: this is an obvious mistake, let's prevent ppl from building on it (I doubt anyone overrides this method anyway).

**Comment by Aliance** [comment]
Do you know the reason why CI fails for 8.1, high-deps? Do I need to change smth?

**Comment by nicolas-grekas** [comment]
No need, it's unrelated.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Aliance.
