### PR TITLE
[Form] IntegerType: Always use en for IntegerToLocalizedStringTransformer

### LINKED ISSUE #40456: [Form] IntegerType, IntegerToLocalizedStringTransformer
**Symfony version(s) affected**: 4.4.20 but I guess all versions.

**Description**
When having arabian language, `IntegerType` converts numbers to their language form (am I expressing myself correctly?)
so we have ٣٤٤٣ which is 3443. 
This is ok in Firefox, but not ok in Chrome. Chrome expects `value` in `input type="number` to be `3443` and it does the conversion to `٣٤٤٣`.

**How to reproduce**
In Chrome: Create simple IntegerType form in Arabian language, persist 3443, then reload form - it will disappear. 

**Possible Solution**
remove `IntegerToLocalizedStringTransformer` from `IntegerType` ?

**Additional context**

This is the actual error from Chrome: 

`<input type="number"  value="١٢٣٤٩">`

results in 

`The specified value "\u0661\u0662\u0663\u0664\u0669" cannot be parsed, or is out of range.`
and rendered input is empty, so it submits empty value.
image

if we have 
`<input type="number" value="12349">`
It works as expected:

image

### PR DESCRIPTION
**Pull request by Warxcell**
Fixes #40456

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40456
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/IntegerToLocalizedStringTransformer.php [hunk 1]
```diff
@@ -24,19 +24,23 @@ class IntegerToLocalizedStringTransformer extends NumberToLocalizedStringTransfo
...
      */
-    public function __construct($grouping = false, $roundingMode = self::ROUND_DOWN)
+    public function __construct($grouping = false, $roundingMode = self::ROUND_DOWN, $locale = null)
     {
         if (\is_int($grouping) || \is_bool($roundingMode) || 2 < \func_num_args()) {
             @trigger_error(sprintf('Passing a precision as the first value to %s::__construct() is deprecated since Symfony 4.2 and support for it will be dropped in 5.0.', __CLASS__), \E_USER_DEPRECATED);
 
             $grouping = $roundingMode;
             $roundingMode = 2 < \func_num_args() ? func_get_arg(2) : self::ROUND_DOWN;
         }
```
Comment (derrabus) [inline src/Symfony/Component/Form/Extension/Core/DataTransformer/IntegerToLocalizedStringTransformer.php]: I think, this deprecation layer needs some adjustments now that you've added a third parameter.

**Review by derrabus — CHANGES_REQUESTED** [review]
Thank you for your contribution. Can you please add a test for your changes?

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/IntegerToLocalizedStringTransformer.php (hunk 1 above)
Comment (Warxcell) [reply src/Symfony/Component/Form/Extension/Core/DataTransformer/IntegerToLocalizedStringTransformer.php]: What's the previous signature of __construct? I don't see it explicitly written somewhere.

**Comment by Warxcell** [comment]
> Thank you for your contribution. Can you please add a test for your changes?

Where are tests for this FormType and Transformer? I don't see them.

Nvm, found them.

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/IntegerToLocalizedStringTransformer.php (hunk 1 above)
Comment (Warxcell) [reply src/Symfony/Component/Form/Extension/Core/DataTransformer/IntegerToLocalizedStringTransformer.php]: Found it in branch 4.1.

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/IntegerToLocalizedStringTransformer.php [hunk 2]
```diff
@@ -24,19 +24,24 @@ class IntegerToLocalizedStringTransformer extends NumberToLocalizedStringTransfo
...
-        if (\is_int($grouping) || \is_bool($roundingMode) || 2 < \func_num_args()) {
+        if (\is_int($grouping) || \is_bool($roundingMode) || \is_int($locale)) {
             @trigger_error(sprintf('Passing a precision as the first value to %s::__construct() is deprecated since Symfony 4.2 and support for it will be dropped in 5.0.', __CLASS__), \E_USER_DEPRECATED);
 
             $grouping = $roundingMode;
-            $roundingMode = 2 < \func_num_args() ? func_get_arg(2) : self::ROUND_DOWN;
+            $roundingMode = null !== $locale ? $locale : self::ROUND_DOWN;
+            $locale = null;
+        }
+        if (null === $locale) {
```
Comment (xabbuh) [inline src/Symfony/Component/Form/Extension/Core/DataTransformer/IntegerToLocalizedStringTransformer.php]: No need for the `if` here. The default value of the `$locale` argument in `NumberToLocalizedStringTransformer` is `null` to so we can always use the second call.

File: src/Symfony/Component/Form/Extension/Core/Type/IntegerType.php [hunk 3]
```diff
@@ -25,7 +25,10 @@ class IntegerType extends AbstractType
      */
     public function buildForm(FormBuilderInterface $builder, array $options)
     {
-        $builder->addViewTransformer(new IntegerToLocalizedStringTransformer($options['grouping'], $options['rounding_mode']));
+        $locale = $options['grouping'] ? \Locale::getDefault() : 'en';
+        $builder->addViewTransformer(
+            new IntegerToLocalizedStringTransformer($options['grouping'], $options['rounding_mode'], $locale)
+        );
```
Comment (xabbuh) [inline src/Symfony/Component/Form/Extension/Core/Type/IntegerType.php]:
```php
$builder->addViewTransformer(new IntegerToLocalizedStringTransformer($options['grouping'], $options['rounding_mode'], !$options['grouping']) ? 'en' : null);
```

File: src/Symfony/Component/Form/Tests/Extension/Core/Type/IntegerTypeTest.php [hunk 4]
```diff
@@ -24,6 +24,34 @@ protected function setUp(): void
         parent::setUp();
     }
 
+    public function testArabicLocale()
+    {
+        $default = \Locale::getDefault();
```
Comment (xabbuh) [inline src/Symfony/Component/Form/Tests/Extension/Core/Type/IntegerTypeTest.php]: This (and restoring the locale) should be done in `setUp()` and `tearDown()` respectively to make sure that this also happens when a test fails (currently in such a case the `\Locale::setDefault($default)` call would not be reached).

File: src/Symfony/Component/Form/Extension/Core/DataTransformer/IntegerToLocalizedStringTransformer.php (hunk 2 above)
Comment (Warxcell) [reply src/Symfony/Component/Form/Extension/Core/DataTransformer/IntegerToLocalizedStringTransformer.php]: I'm doing that check because of parent constructor.
It's `string $locale = null` - So if I pass variable, it must be non-null. Otherwise error will occur.
That's why I'm not passing it if `NULL`

Comment (xabbuh) [reply src/Symfony/Component/Form/Extension/Core/DataTransformer/IntegerToLocalizedStringTransformer.php]: But the parent constructor accepts `null`.

Comment (Warxcell) [reply src/Symfony/Component/Form/Extension/Core/DataTransformer/IntegerToLocalizedStringTransformer.php]: I see... I thought that `string $locale = null`
means:
$locale = null; => results in error, because it's not nullable.

File: src/Symfony/Component/Form/Tests/Extension/Core/Type/IntegerTypeTest.php (hunk 4 above)
Comment (Warxcell) [reply src/Symfony/Component/Form/Tests/Extension/Core/Type/IntegerTypeTest.php]: But we need that only for this test case, and not all tests?

Comment (xabbuh) [reply src/Symfony/Component/Form/Tests/Extension/Core/Type/IntegerTypeTest.php]: To clarify: The `\Locale::setDefault('ar')` should still be part of the test case itself. So it should finally look like this:

```php
private $previousLocale;

protected function setUp(): void
{
    $this->previousLocale = \Locale::getDefault();

    // ..
}

protected function tearDown(): void
{
    \Locale::setDefault($this->previousLocale);

    // ...
}

public function testArabicLocale()
{
    \Locale::setDefault('ar');

    // ...
}
```

File: src/Symfony/Component/Form/Extension/Core/Type/IntegerType.php [hunk 5]
```diff
@@ -25,7 +25,13 @@ class IntegerType extends AbstractType
      */
     public function buildForm(FormBuilderInterface $builder, array $options)
     {
-        $builder->addViewTransformer(new IntegerToLocalizedStringTransformer($options['grouping'], $options['rounding_mode']));
+        $builder->addViewTransformer(
+            new IntegerToLocalizedStringTransformer(
```
Comment (xabbuh) [inline src/Symfony/Component/Form/Extension/Core/Type/IntegerType.php]: please keep this on one line

Comment (Warxcell) [reply src/Symfony/Component/Form/Extension/Core/Type/IntegerType.php]: Sorry, PHPStorm transfers it to new line when reformat code. :( It's too long.

Comment (Warxcell) [reply src/Symfony/Component/Form/Extension/Core/Type/IntegerType.php]: What's the issue with multi lines anyway? It's according to the standards. Now it's very hard to read because I have to scroll horizontally. :(

**Review by xabbuh — APPROVED** [review]

**Review by yceruto — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you @Warxcell.
