### PR TITLE
[FrameworkBundle] skip messenger deduplication middleware registration when no "default" lock is configured

### LINKED ISSUE #60329: The service "messenger.middleware.deduplicate_middleware" has a dependency on a non-existent service "lock.factory"
### Symfony version(s) affected

7.3.0

### Description

I just updated my application, cleared the cache, and now when the kernel boot, I got the following error:

```
I have no name! /app/server/backend bin/console 

In CheckExceptionOnInvalidReferenceBehaviorPass.php line 116:
                                                                                                                                                                                           
  The service "messenger.middleware.deduplicate_middleware" has a dependency on a non-existent service "lock.factory". Did you mean one of these: "ulid.factory", "uuid.factory", "form.factory"?                                                                                                                                                                                 
```

The very strange thing, is we don't use the `messenger.middleware.deduplicate_middleware` messenger middleware

**edit**: see https://github.com/symfony/symfony/blob/25e04aefad04e89cbfaa60c4ba9e64835bce937f/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L2358-L2362

=> IMHO, this middleware should be optin! But it's another story

### How to reproduce

I **guess** it occurs with a fresh symfony + mesenger + lock + all lock have a name different from `default`

### Possible Solution

https://github.com/symfony/symfony/pull/60330

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60329
| License       | MIT

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -569,9 +569,9 @@ public function load(array $configs, ContainerBuilder $container): void
             $container->removeDefinition('console.command.scheduler_debug');
         }
 
-        // messenger depends on validation being registered
+        // messenger depends on validation, and lock being registered
         if ($messengerEnabled) {
-            $this->registerMessengerConfiguration($config['messenger'], $container, $loader, $this->readConfigEnabled('validation', $container, $config['validation']), $this->readConfigEnabled('lock', $container, $config['lock']));
+            $this->registerMessengerConfiguration($config['messenger'], $container, $loader, $this->readConfigEnabled('validation', $container, $config['validation']), $this->readConfigEnabled('lock', $container, $config['lock']) && (bool) ($config['lock']['resources']['default'] ?? false));
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]:
```suggestion
            $this->registerMessengerConfiguration($config['messenger'], $container, $loader, $this->readConfigEnabled('validation', $container, $config['validation']), $this->readConfigEnabled('lock', $container, $config['lock']) && ($config['lock']['resources']['default'] ?? false));
```

**Review by nicolas-grekas — COMMENTED** [review]
I don't understand the title of the PR :grimacing: 
The code skips registering messenger when no "default" lock is configured, isn't it?

**Comment by lyrixx** [comment]
> I don't understand the title of the PR 😬 The code skips registering messenger when no "default" lock is configured, isn't it?

yes

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 1 above)
Comment (lyrixx) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: updated

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 2]
```diff
@@ -569,9 +569,9 @@ public function load(array $configs, ContainerBuilder $container): void
             $container->removeDefinition('console.command.scheduler_debug');
         }
 
-        // messenger depends on validation being registered
+        // messenger depends on validation, and lock being registered
         if ($messengerEnabled) {
-            $this->registerMessengerConfiguration($config['messenger'], $container, $loader, $this->readConfigEnabled('validation', $container, $config['validation']), $this->readConfigEnabled('lock', $container, $config['lock']));
+            $this->registerMessengerConfiguration($config['messenger'], $container, $loader, $this->readConfigEnabled('validation', $container, $config['validation']), $this->readConfigEnabled('lock', $container, $config['lock']) && ($config['lock']['resources']['default'] ?? false));
```
Comment (HypeMC) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:574]: I don't think this is the correct solution, you should be able to define a different lock factory, e.g.:

```yaml
framework:
    lock:
        deduplicate: '%env(LOCK_DEDUPLICATE_DSN)%'

    messenger:
        buses:
            messenger.bus.default:
                middleware:
                    - deduplicate_middleware: [ lock.deduplicate.factory ]
```

However, this doesn't seem to work either:

> Invalid middleware factory "deduplicate_middleware": a middleware factory must be an abstract definition.  

In any case, this seems like a different bug that needs fixing. I can look into it later today. Once that's fixed, this solution won't make much sense anymore, since the lock name won't need to be `default`.

Comment (HypeMC) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:574]: Ok, I went over the feature more closely. The middleware is enabled by default, so you don't need to add it manually. It would still make sense to me if the lock factory was configurable, but that would be a new feature.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @lyrixx.
