### PR TITLE
[Translation] Add `PhpAstExtractor`

### LINKED ISSUE #44899: Translations: incorrect domain using "t" function and named domain argument
### Symfony version(s) affected

5.4.2

### Description

Using `Symfony\Component\Translation\t` function and using named `domain` argument "translation:extract" and "debug:translations" use incorrect domain (default one `messages` is used).

### How to reproduce

```
class DAMFileNameTemplate extends Constraint
{
    public function getMessage()
    {
        return t('error.dam_file_name_template_evaluation', domain: 'validators');
    }
}
```

Calling `debug:translation` reports incorrect domain:
obraz

Workaround:
```
class DAMFileNameTemplate extends Constraint
{
    public function getMessage()
    {
        return t('error.dam_file_name_template_evaluation', [], 'validators');
    }
}
```
Calling `debug:translation` reports correctly:
obraz

### Possible Solution

_No response_

### Additional Context

_No response_

### LINKED ISSUE #45039: [Translation] Entity constraints are not taken into account in the translation:extract
### Description

In the current symfony documentation ( [https://symfony.com/doc/current/validation/translations.html](url) ), it says that we can translate validation constraints by simply adding a translation key in "message" property, then adding this key in a "validators" catalog file.

Nice. But it would be soooo much better, easier and safer it we could generate this file by using the `translation:extract` command like for any other translation. 

However, according to the translator documentation: https://symfony.com/doc/current/translation.html#extracting-translation-contents-and-updating-catalogs-automatically

```
The translation:extract command looks for missing translations in:

Templates stored in the templates/ directory (or any other directory defined in the twig.default_path and twig.paths config options);
Any PHP file/class that injects or autowires the translator service and makes calls to the trans() method.
Any PHP file/class stored in the src/ directory that creates Translations using the constructor or the t() method or calls the trans() method.
```

Therefore, since validator in entities 
- are not in `/templates/`
- do not inject translator service
- do not call trans() or t()

then these keys are never extracted by the `translation:extract` command. And indeed, after trying it in my project, I can confirm they are not.

Could we get a fix for that?

### Example

_No response_

### PR DESCRIPTION
**Pull request by welcoMattic**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #44899, #42285, #45972, #45039
| License       | MIT
| Doc PR        | https://github.com/symfony/symfony-docs/pull/17369

After discussions with @stof and @nicolas-grekas at SymfonyLive Paris 2022, it appears clear that we need a brand new PhpExtractor in Translation to support various syntax, especially PHP8 new syntax (named arguments for example).

In order to make this new extractor sustainable, performant and maintainable, it must be based on AST. That's why this PR adds a new optional dependency on [nikic/php-parser](https://github.com/nikic/PHP-Parser).

The tests suite is the same as PhpExtractorTest, in addition to new cases for newly supported syntax.

NB: I was inspired by https://github.com/php-translation/extractor design, with adaptations for Symfony.

To-do:

- [x] As suggested by @Nyholm, take a look at https://github.com/php-translation/extractor
- [x] Fix #45039 (could be achieved easily with AST tree)

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -1311,6 +1312,12 @@ private function registerTranslatorConfiguration(array $config, ContainerBuilder
             $container->removeDefinition('translation.locale_switcher');
         }
 
+        if (ContainerBuilder::willBeAvailable('nikic/php-parser', Parser::class, ['symfony/translation'])) {
```
Comment (OskarStark) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: If available then AST parser right?

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/translation.php [hunk 2]
```diff
@@ -151,6 +152,9 @@
         ->set('translation.extractor.php', PhpExtractor::class)
             ->tag('translation.extractor', ['alias' => 'php'])
 
+        ->set('translation.extractor.php_ast', PhpAstExtractor::class)
+            ->tag('translation.extractor', ['alias' => 'php_ast'])
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/translation.php]: this should use the `php` alias as well, it is is meant to replace the PhpExtractor to extract translations from `php` files

File: src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php [hunk 3]
```diff
@@ -0,0 +1,138 @@
...
+        ];
+    }
+
+    private function extractValue(Node\Arg $arg): ?string
+    {
+        $result = '';
+
+        if ($arg->value instanceof Node\Expr\BinaryOp\Concat) {
+            $left = $arg->value;
+            while (!$left instanceof Node\Scalar\String_) {
```
Comment (stof) [inline src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php]: this looks weird to me. It seems to assume that the left of a Concat operator can either be a string literal or another Concat operator, which is clearly wrong.

File: src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php [hunk 4]
```diff
@@ -0,0 +1,138 @@
...
+                $result = $left->right->value . $result;
+                $left = $left->left;
+            }
+            $result = $left->value . $result;
+        } elseif ($arg->value instanceof Node\Expr\Assign) {
+            $result = $arg->value->expr->value;
```
Comment (stof) [inline src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php]: this needs to support different kind of nodes in the assigned expression.

**Comment by welcoMattic** [comment]
I've rewrite the first draft by inspiring from https://github.com/php-translation/extractor.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 1 above)
Comment (welcoMattic) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Yes

Comment (OskarStark) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Ah it removes the definition! all good

File: src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+            new TransMethodVisitor(),
+            new TranslatableMessageVisitor(),
+            new ConstraintVisitor(),
+        ];
+    }
+
+    public function extract(iterable|string $resource, MessageCatalogue $catalogue)
+    {
+        $files = $this->extractFiles($resource);
+        foreach ($files as $file) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php]: no need for the $files variable

File: src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+    }
+
+    public function setPrefix(string $prefix)
+    {
+        $this->prefix = $prefix;
+    }
+
+    protected function canBeExtracted(string $file): bool
+    {
+        return $this->isFile($file) && 'php' === pathinfo($file, \PATHINFO_EXTENSION);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php]: we should swap operands for perf I suppose

File: src/Symfony/Component/Translation/Extractor/Visitor/AbstractVisitor.php [hunk 7]
```diff
@@ -0,0 +1,115 @@
...
+    {
+        $this->catalogue = $catalogue;
+        $this->file = $file;
+        $this->messagePrefix = $messagePrefix;
+    }
+
+    protected function addMessageToCatalogue(string $message, ?string $domain, int $line): void
+    {
+        if (null === $domain) {
+            $domain = 'messages';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/Visitor/AbstractVisitor.php]: `$domain ??= 'messages';`

File: src/Symfony/Component/Translation/Extractor/Visitor/AbstractVisitor.php [hunk 8]
```diff
@@ -0,0 +1,115 @@
...
+            return $this->getStringNamedArgument($node, $index);
+        }
+
+        if (!\array_key_exists($index, $node->args)) {
+            return null;
+        }
+
+        $result = $this->getStringValue($node->args[$index]->value);
+
+        if ('' === $result) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/Visitor/AbstractVisitor.php]: should be merged with the previous line:
`if ('' === $result = ...`

File: src/Symfony/Component/Translation/Extractor/Visitor/AbstractVisitor.php [hunk 9]
```diff
@@ -0,0 +1,115 @@
...
+
+    private function getStringValue(Node $node): ?string
+    {
+        if ($node instanceof Node\Scalar\String_) {
+            return $node->value;
+        }
+
+        if ($node instanceof Node\Expr\BinaryOp\Concat) {
+            $left = $this->getStringValue($node->left);
+            if (null === $left) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/Visitor/AbstractVisitor.php]: to be merged with the previous line

File: src/Symfony/Component/Translation/Extractor/Visitor/AbstractVisitor.php [hunk 10]
```diff
@@ -0,0 +1,115 @@
...
+                return null;
+            }
+
+            $right = $this->getStringValue($node->right);
+            if (null === $right) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/Visitor/AbstractVisitor.php]: merge :)

File: src/Symfony/Component/Translation/Extractor/Visitor/AbstractVisitor.php [hunk 11]
```diff
@@ -0,0 +1,115 @@
...
+                return null;
+            }
+
+            return $left.$right;
+        }
+
+        if ($node instanceof Node\Expr\Assign) {
+            if ($node->expr instanceof Node\Scalar\String_) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/Visitor/AbstractVisitor.php]: both "if"s should be merged in one

File: src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php [hunk 12]
```diff
@@ -0,0 +1,206 @@
...
+        $className = $node instanceof Node\Attribute ? $node->name : $node->class;
+        if (!$className instanceof Node\Name) {
+            return null;
+        }
+
+        $parts = $className->parts;
+        $isConstraintClass = false;
+
+        foreach ($parts as $part) {
+            if (\in_array($part, self::CONSTRAINT_CLASS_NAMES)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php]: `, true`

File: src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php [hunk 13]
```diff
@@ -0,0 +1,206 @@
...
+    }
+
+    private function extractFromConstraintClassInstantiation(Node\Expr\New_ $node): ?Node
+    {
+        $args = $node->args;
+        if (0 === \count($args)) {
+            return null;
+        }
+
+        $arg = $args[0];
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php]: `$arg = $node->args[0] ?? null;` and you can remove the previous "if"

File: src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php [hunk 14]
```diff
@@ -0,0 +1,206 @@
...
+                continue;
+            }
+
+            $message = $item->value->value;
+            $messageNode = $item;
+
+            break;
+        }
+
+        if (!empty($message) && null !== $messageNode) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php]: better not use `empty` if possible

File: src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php [hunk 15]
```diff
@@ -0,0 +1,206 @@
...
+    private function extractFromConstraintAttribute(Node\Attribute $node): ?Node
+    {
+        $args = $node->args;
+        if (0 === \count($args)) {
+            return null;
+        }
+
+        $nodeHasNamedArguments = $this->hasNodeNamedArguments($node);
+        $message = $this->getStringArgument($node, $nodeHasNamedArguments ? 'message' : 0);
+        if (null === $message) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php]: merge with previous line

File: src/Symfony/Component/Translation/Extractor/Visitor/TranslatableMessageVisitor.php [hunk 16]
```diff
@@ -0,0 +1,69 @@
...
+        if (!$className instanceof Node\Name) {
+            return null;
+        }
+
+        if (false === array_search('TranslatableMessage', $className->parts)) {
+            return null;
+        }
+
+        $args = $node->args;
+        if (0 === \count($args)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/Visitor/TranslatableMessageVisitor.php]: `if (!$node->args) {`
but why this check if args are not used?

File: src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php [hunk 17]
```diff
@@ -0,0 +1,206 @@
...
+            $this->addMessageToCatalogue($message, 'validators', $node->getStartLine());
+        }
+
+        return null;
+    }
+
+    private function extractFromConstraintAttribute(Node\Attribute $node): ?Node
+    {
+        $args = $node->args;
+        if (0 === \count($args)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php]: `if (!$node->args) {`
but why this check if args are not used?

File: src/Symfony/Component/Translation/Extractor/Visitor/TranslatableMessageVisitor.php [hunk 18]
```diff
@@ -0,0 +1,69 @@
...
+        if (!$node instanceof Node\Expr\New_) {
+            return null;
+        }
+
+        $className = $node->class;
+        if (!$className instanceof Node\Name) {
+            return null;
+        }
+
+        if (false === array_search('TranslatableMessage', $className->parts)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/Visitor/TranslatableMessageVisitor.php]: `, true`

File: src/Symfony/Component/Translation/Extractor/Visitor/TranslatableMessageVisitor.php [hunk 19]
```diff
@@ -0,0 +1,69 @@
...
+        }
+
+        $args = $node->args;
+        if (0 === \count($args)) {
+            return null;
+        }
+
+        $nodeHasNamedArguments = $this->hasNodeNamedArguments($node);
+        $message = $this->getStringArgument($node, $nodeHasNamedArguments ? 'message' : 0);
+        if (null === $message) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/Visitor/TranslatableMessageVisitor.php]: merge

File: src/Symfony/Component/Translation/composer.json [hunk 20]
```diff
@@ -32,7 +32,8 @@
         "symfony/service-contracts": "^1.1.2|^2|^3",
         "symfony/yaml": "^5.4|^6.0",
         "symfony/finder": "^5.4|^6.0",
-        "psr/log": "^1|^2|^3"
+        "psr/log": "^1|^2|^3",
+        "nikic/php-parser": "^4.13"
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/composer.json]: alpha order

**Review by nicolas-grekas — COMMENTED** [review]
here are some random nodes :)

File: src/Symfony/Component/Translation/CHANGELOG.md [hunk 21]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+6.2
+---
+
+* Add `PhpAstExtractor`
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/CHANGELOG.md]: missing space at start of line

File: src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php [hunk 22]
```diff
@@ -0,0 +1,81 @@
...
+    private Parser $parser;
+    /**
+     * @var array<Visitor&NodeVisitor>
+     */
+    private array $visitors;
+
+    public function __construct()
+    {
+        $this->parser = (new ParserFactory())->create(ParserFactory::PREFER_PHP7);
+        $this->visitors = [
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php]: no DI for those two props: on purpose as this shouldn't be extensible?

File: src/Symfony/Component/Translation/Extractor/Visitor/TransMethodVisitor.php [hunk 23]
```diff
@@ -0,0 +1,62 @@
...
+
+        if (!\is_string($node->name) && !$node->name instanceof Node\Identifier && !$node->name instanceof Node\Name) {
+            return null;
+        }
+        $name = (string) $node->name;
+
+        if ('trans' === $name || 't' === $name) {
+            $nodeHasNamedArguments = $this->hasNodeNamedArguments($node);
+            $message = $this->getStringArgument($node, $nodeHasNamedArguments ? 'message' : 0);
+            if (null === $message) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/Visitor/TransMethodVisitor.php]: merge :)

File: src/Symfony/Component/Translation/Extractor/Visitor/Visitor.php [hunk 24]
```diff
@@ -0,0 +1,22 @@
...
+namespace Symfony\Component\Translation\Extractor\Visitor;
+
+use Symfony\Component\Translation\MessageCatalogue;
+
+/**
+ * @author Mathieu Santostefano <msantostefano@protonmail.com>
+ */
+interface Visitor
+{
+    public function initialize(MessageCatalogue $catalogue, \SplFileInfo $file, string $messagePrefix);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/Visitor/Visitor.php]: `: void`?

File: src/Symfony/Component/Translation/Tests/Extractor/PhpAstExtractorTest.php [hunk 25]
```diff
@@ -0,0 +1,186 @@
...
+use PHPUnit\Framework\TestCase;
+use Symfony\Component\Translation\Extractor\PhpAstExtractor;
+use Symfony\Component\Translation\MessageCatalogue;
+
+class PhpAstExtractorTest extends TestCase
+{
+    /**
+     * @dataProvider resourcesProvider
+     *
+     * @param array|string $resource
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Tests/Extractor/PhpAstExtractorTest.php]: native?

File: src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php (hunk 22 above)
Comment (welcoMattic) [reply src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php]: It's part of questions I have about this feature. IMHO, it's better to not allow extension for the parser (I see no reason for a user to create a parser for PHP5 code, as 6.2 is PHP8.1+ compatible).

For the visitors, it could happen for a user to need a special visitor that we don't have in the core. So, yes I can inject a service locator here.

File: src/Symfony/Component/Translation/Tests/Extractor/PhpAstExtractorTest.php (hunk 25 above)
Comment (welcoMattic) [reply src/Symfony/Component/Translation/Tests/Extractor/PhpAstExtractorTest.php]: `$resource` is passed to `PhpAstExtractor::extract` which accept `iterable|string`. I replace `array|` with `iterable|` here.

File: src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php (hunk 22 above)
Comment (stof) [reply src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php]: I would keep them as an implementation detail for now.

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/translation.php (hunk 2 above)
Comment (welcoMattic) [reply src/Symfony/Bundle/FrameworkBundle/Resources/config/translation.php]: it means we will deprecate `PhpExtractor` in 6.2 and remove it in 7.0, so making `niki/php-parser` mandatory to use PHP file extraction for translation in 7.0?

Comment (stof) [reply src/Symfony/Bundle/FrameworkBundle/Resources/config/translation.php]: no. But the DI extension already removes one of these 2 services all the time. And with a `php_ast` alias, it would apply only on files with a `.php_ast` extension.

File: src/Symfony/Component/Translation/composer.json [hunk 26]
```diff
@@ -21,6 +21,7 @@
         "symfony/translation-contracts": "^2.3|^3.0"
     },
     "require-dev": {
+        "nikic/php-parser": "^4.13",
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/composer.json:24]: maybe also list this in suggest for discoverability? and mention that this is needed in the CHANGELOG?

**Review by nicolas-grekas — COMMENTED** [review]
Is this PR ready @welcoMattic ?
Anyone up to review/try it in depth?

**Comment by welcoMattic** [comment]
@nicolas-grekas It's quite ready for me. Just two questions:

- When will we deprecate `PhpExtractor` in favor of `PhpAstExtractor`?
- `PhpAstExtractor` is actually registered as service only if nikic/php-parser is installed, should we let it as it is?

(failures in CI are unrelated, including fabbot)

File: src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php [hunk 27]
```diff
@@ -0,0 +1,81 @@
...
+    private string $prefix = '';
+    private Parser $parser;
+    /**
+     * @var array<Visitor&NodeVisitor>
+     */
+    private array $visitors;
+
+    public function __construct()
+    {
+        $this->parser = (new ParserFactory())->create(ParserFactory::PREFER_PHP7);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php:42]: since the dep is optional, we should throw a logic exception when it's missing, see L76 for inspiration

File: src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php [hunk 28]
```diff
@@ -0,0 +1,81 @@
...
+use Symfony\Component\Translation\Extractor\Visitor\TransMethodVisitor;
+use Symfony\Component\Translation\Extractor\Visitor\Visitor;
+use Symfony\Component\Translation\MessageCatalogue;
+
+/**
+ * PhpAstExtractor extracts translation messages from a PHP AST.
+ *
+ * @author Mathieu Santostefano <msantostefano@protonmail.com>
+ */
+class PhpAstExtractor extends AbstractFileExtractor implements ExtractorInterface
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php]: let's make the class final and add return types to its methods?

File: src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php [hunk 29]
```diff
@@ -0,0 +1,194 @@
...
+        }
+
+        if (null !== $message && null !== $messageNode) {
+            $this->addMessageToCatalogue($message, 'validators', $node->getStartLine());
+        }
+
+        return null;
+    }
+
+    private function extractFromConstraintAttribute(Node\Attribute $node): ?Node
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php]: let's use `void` as return type since we never return anything useful? or inline the logic altogether?
(same for the previous method)

File: src/Symfony/Component/Translation/Tests/Extractor/PhpAstExtractorTest.php [hunk 30]
```diff
@@ -0,0 +1,183 @@
...
+use PHPUnit\Framework\TestCase;
+use Symfony\Component\Translation\Extractor\PhpAstExtractor;
+use Symfony\Component\Translation\MessageCatalogue;
+
+class PhpAstExtractorTest extends TestCase
+{
+    /**
+     * @dataProvider resourcesProvider
+     *
+     * @param iterable|string $resource
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Tests/Extractor/PhpAstExtractorTest.php]: can't we turn this into a real type?

**Review by nicolas-grekas — COMMENTED** [review]
> When will we deprecate PhpExtractor in favor of PhpAstExtractor?

We could in 6.2 - even in this PR if we want.

> PhpAstExtractor is actually registered as service only if nikic/php-parser is installed, should we let it as it is?

Yes, that's needed as a BC layer to me.

File: src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php (hunk 22 above)
Comment (alamirault) [reply src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php]: Service locator for visitors could be nice.

If we use another `TranslatableInterface` than `TranslatableMessage` we may want implements cutsom Visitor

Comment (welcoMattic) [reply src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php]: It's done

File: src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php [hunk 31]
```diff
@@ -0,0 +1,188 @@
...
+        'Required',
+        'Time',
+        'Timezone',
+        'Traverse',
+        'Type',
+        'Unique',
+        'Url',
+        'Uuid',
+        'Valid',
+    ];
```
Comment (welcoMattic) [inline src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php]: Is there any more sustainable solution to have (automatically?) the whole list of constraints here?

Comment (nicolas-grekas) [reply src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php]: Pass the list as constructor argument and compute it in a compiler pass?

Comment (welcoMattic) [reply src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php]: Done. But I'm not 100% sure about how I did it

File: src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php [hunk 32]
```diff
@@ -0,0 +1,75 @@
...
+ * PhpAstExtractor extracts translation messages from a PHP AST.
+ *
+ * @author Mathieu Santostefano <msantostefano@protonmail.com>
+ */
+final class PhpAstExtractor extends AbstractFileExtractor implements ExtractorInterface
+{
+    private Parser $parser;
+
+    public function __construct(
+        private readonly iterable $visitors,
```
Comment (stof) [inline src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php:35]: We need some phpdoc to document the type accepted in this iterable.

File: src/Symfony/Component/Translation/Extractor/Visitor/AbstractVisitor.php [hunk 33]
```diff
@@ -0,0 +1,112 @@
...
+use Symfony\Component\Translation\MessageCatalogue;
+
+/**
+ * @author Mathieu Santostefano <msantostefano@protonmail.com>
+ */
+abstract class AbstractVisitor
+{
+    protected MessageCatalogue $catalogue;
+    protected \SplFileInfo $file;
+    protected string $messagePrefix;
```
Comment (stof) [inline src/Symfony/Component/Translation/Extractor/Visitor/AbstractVisitor.php]: should those be protected ? Do we actually want child classes to access them directly ?

File: src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php [hunk 34]
```diff
@@ -0,0 +1,125 @@
...
+    {
+        return null;
+    }
+
+    public function afterTraverse(array $nodes): ?Node
+    {
+        return null;
+    }
+
+    private function extractFromConstraintClassInstantiation(Node\Expr\New_ $node): void
```
Comment (stof) [inline src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php]: This currently only supports extracting from the option array. We also need to support extracting from named constructor arguments IMO.

File: src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php [hunk 35]
```diff
@@ -0,0 +1,75 @@
...
+        }
+
+        $this->parser = (new ParserFactory())->create(ParserFactory::PREFER_PHP7);
+    }
+
+    public function extract(iterable|string $resource, MessageCatalogue $catalogue): void
+    {
+        foreach ($this->extractFiles($resource) as $file) {
+            $traverser = new NodeTraverser();
+            /** @var Visitor&NodeVisitor $visitor */
```
Comment (stof) [inline src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php]: `Visitor` does not exist. It is `AbstractVisitor`

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php (hunk 34 above)
Comment (welcoMattic) [reply src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php]: Indeed, I take care of it.

Comment (welcoMattic) [reply src/Symfony/Component/Translation/Extractor/Visitor/ConstraintVisitor.php]: Good catch, I just noticed that I miss some major cases here (i.e if options are passed traditionally, not in an array).

**Comment by welcoMattic** [comment]
I rework the ConstraintVistor to cover more case (and I discover some that can not be covered, [see comment](https://github.com/symfony/symfony/pull/46161/files#diff-0a9cc926e96f229280529914957f004a1337a054a51e26349294ce91fe428c26R71)).

Let me know if I miss something about those not covered cases.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 36]
```diff
@@ -1335,6 +1337,13 @@ private function registerTranslatorConfiguration(array $config, ContainerBuilder
             $container->removeDefinition('translation.locale_switcher');
         }
 
+        if (ContainerBuilder::willBeAvailable('nikic/php-parser', Parser::class, ['symfony/translation'])
+            && ContainerBuilder::willBeAvailable('symfony/translation', PhpAstExtractor::class, ['symfony/framework-bundle'])) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: tail `) {` should be on their own line :)

File: src/Symfony/Component/Translation/DependencyInjection/TranslatorPass.php [hunk 37]
```diff
@@ -70,5 +70,16 @@ public function process(ContainerBuilder $container)
                 $definition->replaceArgument(7, $paths);
             }
         }
+
+        if ($container->hasDefinition('validator') && $container->hasDefinition('translation.extractor.visitor.constraint')) {
+            $definition = $container->findDefinition('translation.extractor.visitor.constraint');
+            $constraintClassNames = [];
+
+            foreach (array_keys($container->findTaggedServiceIds('validator.constraint_validator', true)) as $serviceId) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/DependencyInjection/TranslatorPass.php]: no need for array_keys, that's needlessly creating a temporary array

File: src/Symfony/Component/Translation/Extractor/Visitor/AbstractVisitor.php [hunk 38]
```diff
@@ -0,0 +1,118 @@
...
+            return [];
+        }
+
+        /** @var Node\Arg $arg */
+        $arg = $args[$index];
+        if (!$result = $this->getStringValue($arg->value)) {
+            return [];
+        }
+
+        return [$result] ?? [];
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/Extractor/Visitor/AbstractVisitor.php]: the `??` doesn't make sense

File: src/Symfony/Component/Translation/DependencyInjection/TranslatorPass.php [hunk 39]
```diff
@@ -70,5 +70,16 @@ public function process(ContainerBuilder $container)
...
+                $constraintClassNames[] = str_replace('Validator', '', $serviceId);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Translation/DependencyInjection/TranslatorPass.php]: I don't get this line

**Review by nicolas-grekas — COMMENTED** [review]
Missing update to UPGRADE-6.2.md ;)

File: src/Symfony/Component/Translation/DependencyInjection/TranslatorPass.php (hunk 39 above)
Comment (welcoMattic) [reply src/Symfony/Component/Translation/DependencyInjection/TranslatorPass.php]: Fixed [here](https://github.com/symfony/symfony/pull/46161/files#diff-7db625a100dc62a26326cffbd587e93d4a67195e0d894dea32aa238193e9a763R59), I was wrong about retrieving constraints class names.

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @welcoMattic.
