### PR TITLE
[Validator] handle union and intersection types for cascaded validations

### LINKED ISSUE #49629: Validator failing with #[Cascade] and a union type
### Symfony version(s) affected

6.2.7

### Description

Hey.

I'm using `symfony/validator` as a standalone package to validate DTOs that come from frontend. To handle optional values (i.e. those that can be missing from the payload), I use a special `MissingValue` type in a union with the type I want (see reproduction).

I then use a custom `ConstraintValidatorFactory` to skip validation of `MissingValue` values. It all plays out very nicely, but there's one place where `symfony/validator` is not expecting a union: https://github.com/symfony/validator/blob/6.2/Mapping/ClassMetadata.php#L197

Here `$property->getType()` returns a `ReflectionUnionType`, while `ReflectionNamedType` is expected, so it throws an error for a missing `->getName()` method.

### How to reproduce

```php
enum MissingValue
{
    case INSTANCE;
}

#[Cascade]
class InputDTO {
    #[Length(min: 1, max: 500)]
    public readonly string|null|MissingValue $optionalField = MissingValue::INSTANCE;
}

$validator->validate(new InputDTO());
```

### Possible Solution

I'm aware my use case is not directly supported by `symfony/validator`, but this could be an easy fix: remove this check altogether, adding a `#[Valid]` attribute to every field regardless of it's type.

### Additional Context

_No response_

### LINKED ISSUE #53735: [Validator] Error in ClassMetadata when using cascade constraint on class with union types.
### Symfony version(s) affected

6.4.2

### Description

When using the cascade constraint on a class with a union typed property, the ClassMetadata will give an error:
`Attempted to call an undefined method named 'getName' of class 'ReflectionUnionType'.`

This is caused by [ClassMetadata#L201](https://github.com/symfony/validator/blob/03b0c75d7d3df1ef9a0fd9fb8db1e86f83ffa2bb/Mapping/ClassMetadata.php#L201) since `$property->getType()` returns an `ReflectionUnionType`.

### How to reproduce

```php
<?php

namespace Acme;

use Symfony\Component\Validator\Constraints as Assert;

#[Assert\Cascade]
class AnotherClass 
{
     private null|FirstClass|SecondClass $value = null;
}
```

```php
<?php

namespace Acme;

use Symfony\Component\Validator\Constraints as Assert;

class FirstClass 
{
     #[Assert\NotBlank]
     private ?string $value = null;
}
```

```php
<?php

namespace Acme;

use Symfony\Component\Validator\Constraints as Assert;

class SecondClass 
{
     #[Assert\NotBlank]
     private ?string $value = null;
}
```

### Possible Solution

I think we can check if the property type is instance of `ReflectionUnionType` and if one of the types is an `array` or the defined `class_exists` the constraint could be added.

I am busy until end of next week, i can work on a PR.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #49629, Fix #53735
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/Validator/Mapping/ClassMetadata.php [hunk 1]
```diff
@@ -511,4 +511,23 @@ private function checkConstraint(Constraint $constraint)
...
+    private function canCascade(?\ReflectionType $type = null): bool
+    {
+        if (null === $type) {
+            return false;
+        }
+
+        if ($type instanceof \ReflectionIntersectionType || $type instanceof \ReflectionUnionType) {
+            foreach ($type->getTypes() as $nestedType) {
+                if (!$this->canCascade($nestedType)) {
+                    return false;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Mapping/ClassMetadata.php:534]: for intersections, shouldn't we return true if at least one can cascade ?

Comment (xabbuh) [reply src/Symfony/Component/Validator/Mapping/ClassMetadata.php:534]: makes sense

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.
