### PR TITLE
[Uid] Add support for binary, base-32 and base-58 representations in `Uuid::isValid()`

### LINKED ISSUE #57398: [Uid] isValid fails when passing non Rfc4122 IDs
### Symfony version(s) affected

7.1.1

### Description

When trying to validate UUIDs in a format that's not Rfc4122 it'll always fail.

### How to reproduce

```php
Uuid::isValid("1CCD2w4mK2m455S2BAXFht"); //should be true since it's a valid UUIDv7 in base58 format.
```

### Possible Solution

The `isValid` seems to contain a regex that checks for the Rfc4122 structure, probably should be expanded to check the other representations as well.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #57398
| License       | MIT

Allows to use a bitfield in `Uuid::isValid()` to accept one or many formats:

```php
Uuid::isValid('...', Uuid::FORMAT_BASE_32 | Uuid::FORMAT_RFC_4122);
Uuid::isValid('...', Uuid::FORMAT_ALL);
UUid::isValid('...'); // by default, FORMAT_RFC_4122 is used to match the current behavior
```

### CODE REVIEW

File: src/Symfony/Component/Uid/Uuid.php [hunk 1]
```diff
@@ -182,4 +179,34 @@ private static function format(string $uuid, string $version): string
 
         return substr_replace($uuid, '-', 23, 0);
     }
+
+    /**
+     * Transforms a binary string, a base-32 string or a base-58 string to a RFC4122 string.
+     *
+     * @return non-empty-string
+     */
+    private static function transformAnyToRfc4122(string $uuid, int $format = self::FORMAT_RFC_4122): string
```
Comment (OskarStark) [inline src/Symfony/Component/Uid/Uuid.php]:
```suggestion
    private static function transformToRfc4122(string $uuid, int $format = self::FORMAT_RFC_4122): string
```
?

Comment (alexandre-daubois) [reply src/Symfony/Component/Uid/Uuid.php]: Updated :+1:

File: src/Symfony/Component/Uid/Uuid.php [hunk 2]
```diff
@@ -130,8 +121,14 @@ final public static function v8(string $uuid): UuidV8
         return new UuidV8($uuid);
     }
 
-    public static function isValid(string $uuid): bool
+    public static function isValid(string $uuid, int $format = self::FORMAT_RFC_4122): bool
```
Comment (javiereguiluz) [inline src/Symfony/Component/Uid/Uuid.php]: I'm not a big fan of bitfields in options (e.g. `Uuid::FORMAT_BASE_32 | Uuid::FORMAT_RFC_4122`). So, I wonder if we could replace this `int` by a `string|array` (maybe renamed the option too to `$allowedFormats`).

This would be similar to:

* The [formats option](https://symfony.com/doc/current/reference/constraints/CssColor.html#formats) in Css constraint
* The [schemes option](https://symfony.com/doc/current/reference/constraints/CardScheme.html#schemes) in CardScheme constraint

Comment (alexandre-daubois) [reply src/Symfony/Component/Uid/Uuid.php]: I like bit-fields because it reads well, it is quick and easy to test a flag, but also because it offers nice auto-completion and static analysis thanks to `@param int-mask-of`.

Those seems a bit more difficult with a `string|array`. I'm curious to understand why you're not a big fan of bit-field and why'd you prefer an array of options? :slightly_smiling_face:

File: src/Symfony/Component/Uid/Uuid.php [hunk 3]
```diff
@@ -27,6 +27,12 @@ class Uuid extends AbstractUid
     protected const NIL = '00000000-0000-0000-0000-000000000000';
     protected const MAX = 'ffffffff-ffff-ffff-ffff-ffffffffffff';
 
+    public const FORMAT_BINARY = 1;
+    public const FORMAT_BASE_32 = 1 << 1;
+    public const FORMAT_BASE_58 = 1 << 2;
+    public const FORMAT_RFC_4122 = 1 << 3;
+    public const FORMAT_ALL = self::FORMAT_BINARY | self::FORMAT_BASE_32 | self::FORMAT_BASE_58 | self::FORMAT_RFC_4122;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Uid/Uuid.php]: public consts should be grouped together, before protected ones
```suggestion
    public const FORMAT_ALL = -1;
```

File: src/Symfony/Component/Uid/Uuid.php [hunk 4]
```diff
@@ -182,4 +182,36 @@ private static function format(string $uuid, string $version): string
...
     }
+
+    /**
+     * Transforms a binary string, a base-32 string or a base-58 string to a RFC4122 string.
+     *
+     * @param int-mask-of<Uuid::FORMAT_*> $format
+     *
+     * @return non-empty-string
+     */
+    private static function transformToRfc4122(string $uuid, int $format = self::FORMAT_RFC_4122): string
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Uid/Uuid.php]:
```suggestion
    private static function toRfc4122(string $uuid, int $format): string
```

File: src/Symfony/Component/Uid/Uuid.php (hunk 2 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Uid/Uuid.php]: A bit-field is more appropriate to me also.

Note that adding an argument is a BC break, we should comment it and use func_get_arg instead

File: src/Symfony/Component/Uid/Uuid.php (hunk 4 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/Uid/Uuid.php]: A method with this name already exists in this class

File: src/Symfony/Component/Uid/Uuid.php (hunk 3 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/Uid/Uuid.php]: Oh smart, thanks!

File: src/Symfony/Component/Uid/Uuid.php (hunk 2 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/Uid/Uuid.php]: Oh yes, I got confused with private methods. It's updated now

File: src/Symfony/Component/Uid/Uuid.php [hunk 5]
```diff
@@ -27,6 +27,12 @@ class Uuid extends AbstractUid
     protected const NIL = '00000000-0000-0000-0000-000000000000';
     protected const MAX = 'ffffffff-ffff-ffff-ffff-ffffffffffff';
 
+    public const FORMAT_BINARY = 1;
+    public const FORMAT_BASE_32 = 1 << 1;
+    public const FORMAT_BASE_58 = 1 << 2;
+    public const FORMAT_RFC_4122 = 1 << 3;
+    public const FORMAT_ALL = -1;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Uid/Uuid.php:30]: should still be moved before protected consts :)

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @alexandre-daubois.

File: src/Symfony/Component/Uid/Uuid.php [hunk 6]
```diff
@@ -130,8 +121,19 @@ final public static function v8(string $uuid): UuidV8
...
+    public static function isValid(string $uuid /*, int $format = self::FORMAT_RFC_4122 */): bool
     {
+        $format = 1 < \func_num_args() ? func_get_arg(1) : self::FORMAT_RFC_4122;
+
+        if (36 === \strlen($uuid) && !($format & self::FORMAT_RFC_4122)) {
+            return false;
+        }
+
+        $uuid = self::transformToRfc4122($uuid, $format);
+
```
Comment (smnandre) [inline src/Symfony/Component/Uid/Uuid.php:136]: Hi @alexandre-daubois  sorry to dig this up, but while 7.2 is not release.. 

I find this early condition non "optimal", as default case will be in fact $format = FORMAT_RFC_4122.. 

What if we did something like this here (before? instead?),  avoiding the regexp if the string is not 36 chars long ? 

```php
    if (($format & self::FORMAT_RFC_4122) && 36 !== \strlen($uuid)) {
        return false;
    }
```

What do you think ?

Comment (smnandre) [reply src/Symfony/Component/Uid/Uuid.php:136]: (before line 131, i messed up my selection 😅 )

File: src/Symfony/Component/Uid/Uuid.php [hunk 7]
```diff
@@ -182,4 +184,36 @@ private static function format(string $uuid, string $version): string
 
         return substr_replace($uuid, '-', 23, 0);
     }
+
+    /**
+     * Transforms a binary string, a base-32 string or a base-58 string to a RFC4122 string.
+     *
+     * @param int-mask-of<Uuid::FORMAT_*> $format
+     *
+     * @return non-empty-string
```
Comment (smnandre) [inline src/Symfony/Component/Uid/Uuid.php:193]: @alexandre-daubois this is currently not true, afaik ... should we enforce it (or remove it) ?

File: src/Symfony/Component/Uid/Uuid.php (hunk 6 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/Uid/Uuid.php:136]: I did try a few things but it would require some refactoring because of how the control flow is currently. I'm not sure it would worth it and if performances would greatly improve :thinking:

File: src/Symfony/Component/Uid/Uuid.php (hunk 7 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/Uid/Uuid.php:193]: Indeed, but more than that, it's a bit confusing. I proposed this update: https://github.com/symfony/symfony/pull/58089

File: src/Symfony/Component/Uid/Uuid.php (hunk 6 above)
Comment (smnandre) [reply src/Symfony/Component/Uid/Uuid.php:136]: Yep that is very true!
