### PR TITLE
[Validator] Fix traverse option on Valid constraint when used as Attribute

### LINKED ISSUE #46243: [Validator] `Valid` constraint `traverse` option not working when using as Attribute
### Symfony version(s) affected

5.4

### Description

The `traverse` option doesn't work when using a `Valid` constraint as Attribute.

### How to reproduce

```php
use Symfony\Component\Validator\Constraints as Assert;

// var will not be traversed
class SomeAnnotationClass {
  /** @Assert\Valid(traverse=false) */
  private $someVar;
}

// var WILL be traversed
class SomeAttributeClass {
  #[Assert\Valid(traverse: false)]
  private $someVar;
}
```

### Possible Solution

The constructor of `Symfony\Component\Validator\Constraints\Valid` isn't overridden (like many other constraints) to add the `traverse` named option.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by tobias-93**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #46243
| License       | MIT
| Doc PR        | n.a.

Fix Valid constraint when using as Attribute.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Can you please add a test case? Note also that we cannot use mixed as 5.4 should support PHP 7.2

**Comment by tobias-93** [comment]
@nicolas-grekas Thanks for the feedback. I have removed the `mixed` parameter, and added a test. The remaining failing tests are parts of Symfony I didn't touch, so that's hopefully not my fault...

File: src/Symfony/Component/Validator/Tests/Constraints/ValidTest.php [hunk 1]
```diff
@@ -32,4 +34,34 @@ public function testGroupsAreNullByDefault()
...
+        self::assertSame('some attached data', $cConstraint->payload);
+    }
+}
+
+class ValidDummy
+{
+    #[Valid]
+    private $a;
+
+    #[Valid(groups: ['traverse_group'], traverse: false)] // Needs a group to work at all for this test
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/Tests/Constraints/ValidTest.php:62]: Why is the group needed?

Comment (tobias-93) [reply src/Symfony/Component/Validator/Tests/Constraints/ValidTest.php:62]: See https://github.com/symfony/symfony/blob/2d44f229ff9cb169c4c90f2c05e60069350eb119/src/Symfony/Component/Validator/Mapping/GenericMetadata.php#L145, if `$constraint->groups === null` the constraint itself is not added but the traversalstrategy is changed. Since we want to check if the argument properly propagates to the constraint (and not the traversalstrategy or other functional behavior) I added a group to demonstrate.

**Review by xabbuh — DISMISSED** [review]

File: src/Symfony/Component/Validator/Constraints/Valid.php [hunk 2]
```diff
@@ -43,4 +43,11 @@ public function addImplicitGroupName(string $group)
             parent::addImplicitGroupName($group);
         }
     }
+
+    public function __construct(array $options = null, bool $traverse = null, array $groups = null, $payload = null)
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraints/Valid.php]: shouldn't $traverse be the last argument to not break BC when creating an instance?

File: src/Symfony/Component/Validator/Constraints/Valid.php [hunk 3]
```diff
@@ -43,4 +43,11 @@ public function addImplicitGroupName(string $group)
...
+    {
+        parent::__construct($options ?? [], $groups, $payload);
+
+        $this->traverse = $traverse ?? $this->traverse ?? true;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraints/Valid.php]: > `$this->traverse ?? true`

can `$this->traverse` really be null?

Comment (HeahDude) [reply src/Symfony/Component/Validator/Constraints/Valid.php]: What about `bool $traverse = true` in the constructor instead? or using `?bool` there

File: src/Symfony/Component/Validator/Constraints/Valid.php (hunk 2 above)
Comment (tobias-93) [reply src/Symfony/Component/Validator/Constraints/Valid.php]: I did it similarly to the constraints that were fixed in https://github.com/symfony/symfony/commit/fb99eb2052523cfa2a9ba36006d020796548aaa6, in those argument order wasn't honored either. Why would that be an issue for this constraint?

File: src/Symfony/Component/Validator/Constraints/Valid.php (hunk 3 above)
Comment (tobias-93) [reply src/Symfony/Component/Validator/Constraints/Valid.php]: Fallback to true removed to bring it in line with https://github.com/symfony/symfony/commit/fb99eb2052523cfa2a9ba36006d020796548aaa6

File: src/Symfony/Component/Validator/Constraints/Valid.php (hunk 2 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Validator/Constraints/Valid.php]: /cc @derrabus I may miss something here

**Comment by tobias-93** [comment]
@nicolas-grekas @derrabus Any progress here?

**Review by xabbuh — APPROVED** [review]

File: src/Symfony/Component/Validator/Constraints/Valid.php (hunk 2 above)
Comment (fabpot) [reply src/Symfony/Component/Validator/Constraints/Valid.php]: I think it does not hurt to not break BC anyway, right? Let's reorder.
Also, the `__construct` method should be moved as the first method of the class.

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Validator/Constraints/Valid.php [hunk 4]
```diff
@@ -43,4 +43,11 @@ public function addImplicitGroupName(string $group)
             parent::addImplicitGroupName($group);
         }
     }
+
+    public function __construct(array $options = null, bool $traverse = null, array $groups = null, $payload = null)
+    {
+        parent::__construct($options ?? [], $groups, $payload);
+
+        $this->traverse = $traverse ?? $this->traverse;
```
Comment (HeahDude) [inline src/Symfony/Component/Validator/Constraints/Valid.php]: I don't see the point of such check, what about `bool $traverse = true` and a simple assignation here?

Comment (stof) [reply src/Symfony/Component/Validator/Constraints/Valid.php]: `traverse` might be assigned through `$options` too

File: src/Symfony/Component/Validator/Constraints/Valid.php (hunk 2 above)
Comment (tobias-93) [reply src/Symfony/Component/Validator/Constraints/Valid.php]: @fabpot reordered, thanks for the remark. I actually just ran into an issue where the argument order was not honored (the `Callback` constraint) so I think keeping the BC is the right decision 👍🏼

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @tobias-93.
