### PR TITLE
[HttpClient] Let curl handle transfer encoding

### LINKED ISSUE #54491: Unable to send an email: to parameter is missing (code 400).
### Symfony version(s) affected

v6.4.4

### Description

Sending emails no longer works without any adjustments. I retrieve the error Unable to send an email: to parameter is missing (code 400). Other having this problem?

### How to reproduce

Sending e-mails via Laravel:

`Mail::to('test@example.com')
->send(new OrderCreated($order));`

### Possible Solution

_No response_

### Additional Context

_No response_

### LINKED ISSUE #54516: [HttpClient] CurlHttpClient forces unsupported chunked transfer encoding for HTTP/2 requests
### Symfony version(s) affected

7.0

### Description

When sending a `FormData` request (and possibly other chunkable body types), `CurlHttpClient` will set a `Transfer-Encoding: chunked` header:

https://github.com/symfony/symfony/blob/524c7038065b65b91cce043e7eff31df901b71c8/src/Symfony/Component/HttpClient/CurlHttpClient.php#L254-L256

- The HTTP/2 protocol does not support chunked transfer encoding.
- Normally _curl_ would handle the correct format itself based on the HTTP protocol version of the server.
- But when the `Transfer-Encoding` header is set to `chunked` explicitly, _curl_ always uses chunked transfer encoding for the body.
- This results in requests to HTTP/2 server with invalid content.

---

For example, given a request with `FormData` `['foo' => 'bar']`, an HTTP/1 server receives this:

```js
Headers {
  accept: "*/*",
  "accept-encoding": "gzip",
  "content-type": "multipart/form-data; boundary=1It362u0",
  host: "localhost:8000",
  "transfer-encoding": "chunked",
  "user-agent": "Symfony HttpClient (Curl)"
}
FormData { foo: "bar" }
```

While an HTTP/2 server sees this:

```js
Headers {
  accept: "*/*",
  "accept-encoding": "gzip",
  "content-type": "multipart/form-data; boundary=Mm4P-FZG",
  "user-agent": "Symfony HttpClient (Curl)"
}
FormData { foo: "2\r\n\r\n\r\n3\r\nbar\r\n2\r\n\r\n\r\ne" }
```

> _curl_  does omit the `transfer-encoding` header, but keeps the encoding for the body.

### How to reproduce

Repo for reproducing the issue:
https://github.com/michaelhue/symfony-curl-http2-chunked-issue

The test source code can be found here:
https://github.com/michaelhue/symfony-curl-http2-chunked-issue/blob/main/test.php

### Possible Solution

It seems to me that the following lines can be removed completely, which will fix the issue:
https://github.com/symfony/symfony/blob/524c7038065b65b91cce043e7eff31df901b71c8/src/Symfony/Component/HttpClient/CurlHttpClient.php#L254-L256

However my understanding of `curl` and the `Symfony` internals is limited and I can't anticipate the potential fallout from this change.

I'd be happy to create a pull request with this solution, if deemed appropriate.

### Additional Context

This problem was discovered while trying to debug this issue: https://github.com/symfony/symfony/issues/54491

### PR DESCRIPTION
**Pull request by michaelhue**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54516, Fix #54491
| License       | MIT

Removes the `Transfer-Encoding: chunked` header that is added for chunked request bodies. This will allow curl to handle the transfer encoding and set appropriate headers based on the HTTP protocol version it negotiated with the server, since HTTP/2 does not support chunked transfer encoding.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thanks for investigating and for the reproducer.
When I run the code you shared, I have everything green:
✅ HTTP/1 default behavior
✅ HTTP/2 default behavior
✅ HTTP/1 suppressed header
✅ HTTP/2 suppressed header

Could this be related to some curl bug? Which exact version of curl and php do you have ? (`php --ri curl && php -v`)

Mine:
 - curl 7.81.0
 - php 8.3.4

**Comment by michaelhue** [comment]
Hey Nicolas, that's interesting!

- curl: `8.7.1`
- PHP: `8.3.4`

I checked the `curl` issues and found some posts that may be related:

- https://github.com/curl/curl/issues/13229
- https://github.com/curl/curl/pull/13257

While I'm not sure this is the bug I'm experiencing, there is a relevant quote:
> Applications are encouraged to not force "chunked", but rather set length information for a POST. By setting -1, curl will auto-select chunked on HTTP/1.1 and work properly on other HTTP versions.

That is the behavior this pull request would address.

---

I just checked the servers where I first experienced https://github.com/symfony/symfony/issues/54491 and they are also on curl `8.7.1`.

File: src/Symfony/Component/HttpClient/CurlHttpClient.php [hunk 1]
```diff
@@ -247,9 +247,6 @@ public function request(string $method, string $url, array $options = []): Respo
             if (isset($options['normalized_headers']['content-length'][0])) {
                 $curlopts[\CURLOPT_INFILESIZE] = (int) substr($options['normalized_headers']['content-length'][0], \strlen('Content-Length: '));
             }
-            if (!isset($options['normalized_headers']['transfer-encoding'])) {
-                $curlopts[\CURLOPT_HTTPHEADER][] = 'Transfer-Encoding:'.(isset($curlopts[\CURLOPT_INFILESIZE]) ? '' : ' chunked');
-            }
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CurlHttpClient.php]: Let's do what curl did in its client:
```php
            } elseif (!isset($options['normalized_headers']['transfer-encoding'])) {
                $curlopts[\CURLOPT_INFILESIZE] = -1;
            }
```

**Comment by nicolas-grekas** [comment]
Thank you @michaelhue.

**Comment by joelwurtz** [comment]
Since this patch, our HTTP client does not add transfer-encoding: chunked header when specifying the body as a callable

We have to force the header to make it work, is this a problem between curl version and this patch ?

FYI :

php version : 8.3.6
curl: 7.64.0

**Comment by ddegasperi** [comment]
I've to apply also the "Transfer-encoding: chunked" header to make my request (see code snipped) work again after this patch:

```php

$formData = new FormDataPart([
    'degree' => '90',
    'file' => new DataPart(
        $fileResource, // a resource not a string
        'image.jpg',
        'image/jpeg'
    )
]);

$response = $client->request('POST', '/api/image/rotate/', [
    'headers' => [
        ...$formData->getPreparedHeaders()->toArray(),
        'Transfer-encoding: chunked' // with this header the patch works, without it does not send the data
    ],
    'body' => $formData->bodyToIterable(),
]);

```

PHP Version: 7.4.33
Curl: 7.61.1

Do we know from which Curl version we should apply the following behavior?

> Applications are encouraged to not force "chunked", but rather set length information for a POST. By setting -1, curl will auto-select chunked on HTTP/1.1 and work properly on other HTTP versions.

Since Symfony 5.4 is supported also for PHP >=7.2.5, which often runs on systems where these dependencies are not necessarily updatable, I wonder if it was right to backport this patch to this version?

**Comment by nicolas-grekas** [comment]
Closed issues cannot be tracked so please open one to describe the bug

**Comment by nicolas-grekas** [comment]
@ddegasperi this solution might break once we fix the bug

**Comment by devon-seitz** [comment]
FYI updating to curl 8.8 fixed this issue for me

**Comment by nicolas-grekas** [comment]
FYI I think we should revert this, see #57569
