### PR TITLE
[Serializer] Added scalar denormalization

### LINKED ISSUE #33784: [Serializer] deserializing array of integers
**Symfony version(s) affected**: 4.3.4

**Description**  
Hello, I am trying to deserialize an array of integers but I am getting this exception: `Could not denormalize object of type int[], no supporting normalizer found.`  Previously I was using JMS serializer so it was possible to define type `array<int>` but I get the same error with symfony serializer.

**How to reproduce**  
```php
<?php
$serializer = new Serializer(
    [new GetSetMethodNormalizer(), new PropertyNormalizer(), new ObjectNormalizer(), new ArrayDenormalizer()],
    [new JsonEncoder()]
);
$numbers  = $serializer->deserialize('["15"]', 'int[]', 'json');
```

### PR DESCRIPTION
**Pull request by a-menshchikov**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #33784
| License       | MIT

Was added an ability to deserialize scalar data (single or array).

### CODE REVIEW

File: src/Symfony/Component/Serializer/Serializer.php [hunk 1]
```diff
@@ -297,6 +306,11 @@ private function getDenormalizer($data, string $class, ?string $format, array $c
         return null;
     }
 
+    private function scalarDenormalization($type)
+    {
+        return \in_array($type, ['int', 'integer', 'bool', 'boolean', 'float', 'string'], true);
```
Comment (dunglas) [inline src/Symfony/Component/Serializer/Serializer.php]: This code is performance sensitive (it will be called recursively on the hot path) so I suggest to:

* move the list of type in a `const`
* transform this array in map (`const TYPES = ['int' => true, 'integer' => true/*...*/]`
* call `isset(self::TYPES[$type])` directly to remove an extra function call

Comment (dunglas) [reply src/Symfony/Component/Serializer/Serializer.php]: And isn't `double` missing?

**Review by dunglas — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Serializer/Serializer.php (hunk 1 above)
Comment (a-menshchikov) [reply src/Symfony/Component/Serializer/Serializer.php]: > And isn't `double` missing?

I thought that `double` is outdated version of `float`, but `gettype()` returning `double` for float values, so I think that `double` should be presented in types map.

File: src/Symfony/Component/Serializer/Serializer.php [hunk 2]
```diff
@@ -297,6 +316,11 @@ private function getDenormalizer($data, string $class, ?string $format, array $c
         return null;
     }
 
+    private function scalarDenormalization($type)
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Serializer.php]: no need for an extra method call when an inline "isset" does the job to me.

File: src/Symfony/Component/Serializer/Serializer.php [hunk 3]
```diff
@@ -45,6 +45,16 @@
  */
 class Serializer implements SerializerInterface, ContextAwareNormalizerInterface, ContextAwareDenormalizerInterface, ContextAwareEncoderInterface, ContextAwareDecoderInterface
 {
+    const SCALAR_TYPES = [
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Serializer.php]: should be private I suppose

File: src/Symfony/Component/Serializer/Serializer.php [hunk 4]
```diff
@@ -45,6 +45,16 @@
  */
 class Serializer implements SerializerInterface, ContextAwareNormalizerInterface, ContextAwareDenormalizerInterface, ContextAwareEncoderInterface, ContextAwareDecoderInterface
 {
+    private const SCALAR_TYPES = [
+        'int' => true,
+        'integer' => true,
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Serializer.php]: this is not a native scalar type, no need to support it, same for boolean and double

File: src/Symfony/Component/Serializer/Serializer.php [hunk 5]
```diff
@@ -183,6 +193,14 @@ public function normalize($data, $format = null, array $context = [])
      */
     public function denormalize($data, $type, $format = null, array $context = [])
     {
+        if (isset(self::SCALAR_TYPES[$type])) {
+            if (false === @settype($data, $type)) {
+                throw new LogicException(sprintf('"%s" cannot be denormalized to %s', (string) $data, $type));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Serializer.php]: the cast to string can fail - why no using gettype+get_class?

File: src/Symfony/Component/Serializer/Serializer.php (hunk 4 above)
Comment (a-menshchikov) [reply src/Symfony/Component/Serializer/Serializer.php]: I don't think so because `gettype()` returns exactly this strings for int, bool and float values.

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Serializer.php]: I'm pretty sure we don't want to support types that PHP itself doesn't support.

Comment (a-menshchikov) [reply src/Symfony/Component/Serializer/Serializer.php]: Probably I misunderstand you: why do you think that PHP doesn't support `integer`, `boolean` and `double` types? Or what do you mean under `doesn't support`?

When I wrote this code I was guided by the documentation for the `settype()`, in particular the description of `type` parameter and it possible values.

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Serializer.php]:
```php
$f  = function (double $a) {};
$f(1.0);
```
> Uncaught TypeError: Argument 1 passed to {closure}() must be an instance of double, float given

File: src/Symfony/Component/Serializer/Serializer.php (hunk 5 above)
Comment (a-menshchikov) [reply src/Symfony/Component/Serializer/Serializer.php]: Could you write an example of exception message? This will afford me to better understand what you mean.

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Serializer.php]: sure:
`throw new LogicException(sprintf('Value of type "%s" cannot be denormalized to "%s".', \gettype($data), $type)); `

File: src/Symfony/Component/Serializer/Serializer.php (hunk 4 above)
Comment (a-menshchikov) [reply src/Symfony/Component/Serializer/Serializer.php]: In terms of native type hinting you are right. But here we deal with type casting and do it by `settype()` that works well both with `int` and with `integer`.
Therefore, I find no reason to exclude support of `integer`, `boolean` and `double`.

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Serializer.php]: With this reasoning, PHP should have supported `function (double $a) {};`.
The `double` here is also an annotation - one that the engine understands.
I find it quite nice that PHP internal decide to provide one single alternative.
That helps consistency, everyone is forced to use one single syntax.
I wish we'd do the same and I see zero reason to support more.

Comment (a-menshchikov) [reply src/Symfony/Component/Serializer/Serializer.php]: I have changed this, but I think that this thing should be noted in docs.

File: src/Symfony/Component/Serializer/Tests/SerializerTest.php [hunk 6]
```diff
@@ -477,6 +478,37 @@ public function testNotNormalizableValueExceptionMessageForAResource()
...
+    public function testDeserializeScalarArray()
+    {
+        $serializer = new Serializer([new ArrayDenormalizer()], ['json' => new JsonEncoder()]);
+
+        $this->assertEquals([42], $serializer->deserialize('[42]', 'int[]', 'json'));
+
+        $this->assertEquals([true, false], $serializer->deserialize('[true, false]', 'bool[]', 'json'));
+
+        $this->assertEquals([3.14, 3.24], $serializer->deserialize('[3.14, 32.4e-1]', 'float[]', 'json'));
+
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Tests/SerializerTest.php]: let's remove the blank lines between assertions

File: src/Symfony/Component/Serializer/Tests/SerializerTest.php [hunk 7]
```diff
@@ -477,6 +478,37 @@ public function testNotNormalizableValueExceptionMessageForAResource()
...
+        $this->assertEquals(['  spaces  ', '@Ca$e%'], $serializer->deserialize('["  spaces  ", "@Ca$e%"]', 'string[]', 'json'));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Tests/SerializerTest.php]: please use assertSame everywhere instead of assertEquals

**Review by dunglas — APPROVED** [review]

File: src/Symfony/Component/Serializer/CHANGELOG.md [hunk 8]
```diff
@@ -7,6 +7,7 @@ CHANGELOG
  * added the list of constraint violations' parameters in `ConstraintViolationListNormalizer`
  * added support for serializing `DateTimeZone` objects
  * added a `deep_object_to_populate` context option to recursive denormalize on `object_to_populate` object.
+ * added support for denormalizing scalar values
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/CHANGELOG.md]: if this is a bug fix, this line should be removed
shouldn't the PR target 3.4 btw, for the same reason?

File: src/Symfony/Component/Serializer/Serializer.php [hunk 9]
```diff
@@ -207,7 +223,8 @@ public function supportsNormalization($data, $format = null, array $context = []
      */
     public function supportsDenormalization($data, $type, $format = null, array $context = [])
     {
-        return null !== $this->getDenormalizer($data, $type, $format, $context);
+        return isset(self::SCALAR_TYPES[$type])
+            || null !== $this->getDenormalizer($data, $type, $format, $context);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Serializer.php]: on one line please

**Review by nicolas-grekas — COMMENTED** [review]
a last comment :)

File: src/Symfony/Component/Serializer/Serializer.php [hunk 10]
```diff
@@ -223,8 +223,7 @@ public function supportsNormalization($data, $format = null, array $context = []
      */
     public function supportsDenormalization($data, $type, $format = null, array $context = [])
     {
-        return isset(self::SCALAR_TYPES[$type])
-            || null !== $this->getDenormalizer($data, $type, $format, $context);
+        return isset(self::SCALAR_TYPES[$type]) || null !== $this->getDenormalizer($data, $type, $format, $context);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Serializer.php]: shouldn't this be `(isset(self::SCALAR_TYPES[$type]) && is_scalar($data)) || ...`?
worth a test case maybe?

File: src/Symfony/Component/Serializer/CHANGELOG.md (hunk 8 above)
Comment (a-menshchikov) [reply src/Symfony/Component/Serializer/CHANGELOG.md]: When I was begin work on this PR I was guided on version from original issue. I don't mind rebase to 3.4, but don't know how to do that correctly. 3.4 requires support of PHP 5.5 that doesn't support array constants and constant visibility, so I will need to change this logic. And this changed logic will not be consistent with 4.3.
Сould you describe the correct procedure for me (so that I wouldn't make a mistake)?

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/CHANGELOG.md]: yes, it's quite common for an issue to be reported for an upper branch, it's our maintainer's job to figure out the lowest applicable branch...
we should use a `private static $scalarType` on 3.4, and I think that's all, isn't it?

File: src/Symfony/Component/Serializer/Serializer.php (hunk 10 above)
Comment (a-menshchikov) [reply src/Symfony/Component/Serializer/Serializer.php]: When we are deserializing int array with ArrayDenormalizer `$data` is array and `$type = 'int'`, so check for scalar data in that place not possible. But I added this check to `denormalize()` and removed throw because all possible scalar values (as I know) can be casted to int/float/bool/string.

**Comment by ogizanagi** [comment]
Just asking: does it really make sense for the Serializer and is it consistent to blindly cast the values?
AFAIK, the object normalizer:
- returns the value if it matches `is_*` functions: https://github.com/symfony/symfony/blob/b1bee601197e2a07ef3fd3274e46231b26e28824/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L436-L438
- throws on non-matching types: https://github.com/symfony/symfony/blob/b1bee601197e2a07ef3fd3274e46231b26e28824/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L445
- unless the `DISABLE_TYPE_ENFORCEMENT` flag is set: https://github.com/symfony/symfony/blob/b1bee601197e2a07ef3fd3274e46231b26e28824/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L441-L443 then, it returns the original data and let the validation occur after deserialization.

**Comment by a-menshchikov** [comment]
@ogizanagi object normalizer doesn't work with scalar values. Data that passed into `denormalize` method should be an object.

**Comment by ogizanagi** [comment]
It does, for scalar values of the object properties. The point is it'll do it inconsistently between objects (no cast, exception if type enforcement is not disabled) and raw arrays of scalars and scalars (implicit cast).

Such assertions would pass with current code:

```php
$this->assertSame([42], $serializer->deserialize('["42"]', 'int[]', 'json'));
$this->assertSame([0, 2], $serializer->deserialize('["test", "2test"]', 'int[]', 'json'));
$this->assertSame([true, false], $serializer->deserialize('["test", ""]', 'bool[]', 'json'));
```

which wouldn't in case of denormalizing object properties with the object normalizer, and would either throw or won't transform the original value depending of the type enforcement flag.

**Comment by a-menshchikov** [comment]
@ogizanagi maybe I'm misunderstanding you, but what class of Normalizers should I use to get assertations passed (or how should I instantiate `$serializer` from your code snippet)?

**Comment by ogizanagi** [comment]
I meant adding these lines in your `SerializerTest::testDeserializeScalarArray` test case would pass with this PR.

**Comment by a-menshchikov** [comment]
@ogizanagi now I'm understood you, thanks for explanation!

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
@ogizanagi I'll let you do the final review + merge if you don't mind.

**Comment by ogizanagi** [comment]
Just to double-check: do you really think this qualifies as a bug fix? Looks like only an unsupported usage of the Serializer 'til now.

**Comment by a-menshchikov** [comment]
I think @xabbuh can answer this question, because I qualified this as a bug fix according to related issue [#33784](https://github.com/symfony/symfony/issues/33784).

**Comment by a-menshchikov** [comment]
We briefly discussed with @xabbuh this question and he expressed his point of view that this is rather a feature than a bug.
But I have a bit different view. To explain it I added test for normalizing scalar values. As you can see, historically normalizing of scalars was worked and return strings are valid json values. But if we have trying to deserialize this value (in current 3.4) it leads to error. And I find here a serializer interface inconsistence, because in my mind any result of serialization should be able to be deserialized into origin value. From this point of view it seems like a bug.

@ogizanagi if you insist I'm ready to rebase PR to 5.0 as a new feature implementation.

**Comment by ogizanagi** [comment]
>  As you can see, historically normalizing of scalars was worked and return strings are valid json values.

But scalar "normalization" in such case is simply "encoding". If you simply need decoding a scalar value, perhaps you should use `decode` instead?

Actually I'm not certain where we're going here: if the aim is to get a bijective behavior between serialize & deserialize, then we also need to handle `null` and arbitrary arrays, so such assertions would pass:

```php
$this->assertSame([2, 'foo'], $serializer->deserialize('[2, 'foo']', 'array', 'json'));
$this->assertSame(null, $serializer->deserialize('null', 'null', 'json'));
```

right? (but that wouldn't even be enough to make it truly bijective)

In any case, I'd still argue this is a new usage of the Serializer, hence a feature for 5.1.

**Comment by fabpot** [comment]
By our standards, this is a new feature.

File: src/Symfony/Component/Serializer/Serializer.php [hunk 11]
```diff
@@ -177,6 +184,10 @@ public function normalize($data, string $format = null, array $context = [])
      */
     public function denormalize($data, string $type, string $format = null, array $context = [])
     {
+        if (isset(self::SCALAR_TYPES[$type]) && \call_user_func('is_'.$type, $data)) {
```
Comment (ogizanagi) [inline src/Symfony/Component/Serializer/Serializer.php]: What about throwing a nicer exception in case `$type` is once of the reference scalar types but `\call_user_func('is_'.$type, $data)` is `false` ? That would make more sense than getting an exception about adding a normalizer for an object.

**Review by ogizanagi — APPROVED** [review]

File: src/Symfony/Component/Serializer/Serializer.php [hunk 12]
```diff
@@ -177,6 +184,14 @@ public function normalize($data, string $format = null, array $context = [])
      */
     public function denormalize($data, string $type, string $format = null, array $context = [])
     {
+        if (isset(self::SCALAR_TYPES[$type])) {
+            if (false === \call_user_func('is_'.$type, $data)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Serializer.php]: `if (!('is_'.$type)($data)) {`

**Review by nicolas-grekas — APPROVED** [review]
With a minor cs change

**Comment by ogizanagi** [comment]
Thx for your patience @a-menshchikov
