### PR TITLE
[PropertyAccess] Fix compatibility with PHP 8.4 asymmetric visibility

### LINKED ISSUE #59183: [PropertyAccess] PropertyAccess is not compatible with PHP 8.4 property hooks
### Symfony version(s) affected

7.2.0

### Description

In PHP 8.4 we have virtual properties and asymmetric visibility.

PropertyAccess considers the following properties writable, although they are not:

```php
final class Foo
{
    public private(set) bool $public_private_set;
    public protected(set) bool $public_protected_set;
    public bool $virtual_no_set_hook { get => true; }
}
```

The issue has already been fixed for the PropertyInfo component in #58556 via https://github.com/symfony/symfony/commit/520e31b5c3cc0ff66bd4b130eb8c1bfa45f7b66d. However, PropertyAccess is still not working correctly, see my reproducer (I've updated it to 7.2.x).

### How to reproduce

https://github.com/vudaltsov/symfony-property-access-php84

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Florian-Merle**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59183
| License       | MIT

Fix compatibility with PHP 8.4 asymmetric visibility by looking if the setter hook is public.

### CODE REVIEW

File: src/Symfony/Component/PropertyAccess/Tests/PropertyAccessorTest.php [hunk 1]
```diff
@@ -1023,4 +1024,74 @@ private function createUninitializedObjectPropertyGhost(): UninitializedObjectPr
...
+        try {
+            $this->propertyAccessor->setValue($object, 'privatePrivate', true);
+            $this->fail('Property with private set should not be writable.');
+        } catch (NoSuchPropertyException) {
+            $this->addToAssertionCount(1);
+        }
+
+        try {
+            $this->propertyAccessor->setValue($object, 'virtualNoSetHook', true);
+            $this->fail('Property with no set should not be writable.');
```
Comment (mtarld) [inline src/Symfony/Component/PropertyAccess/Tests/PropertyAccessorTest.php]:
```suggestion
            $this->fail('Property with no set hook should not be writable.');
```

**Review by mtarld — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Component/PropertyAccess/Tests/PropertyAccessorTest.php [hunk 2]
```diff
@@ -1023,4 +1024,74 @@ private function createUninitializedObjectPropertyGhost(): UninitializedObjectPr
...
+    public function testSetValueWithAsymmetricVisibility()
+    {
+        $object = new AsymmetricVisibility();
+
+        $this->propertyAccessor->setValue($object, 'publicPublic', true);
+        $this->assertTrue($object->publicPublic);
+
+        try {
+            $this->propertyAccessor->setValue($object, 'publicProtected', true);
+            $this->fail('Property with protected set should not be writable.');
```
Comment (stof) [inline src/Symfony/Component/PropertyAccess/Tests/PropertyAccessorTest.php]: Instead of a single test performing such try/catch with explicit failures if there is no exception, please use the `expectException` API of PHPUnit, which provides a much better experience when dealing with test failure.
This will require separating each tested case in a separate test instead of a single test covering all cases. But this is actually a good thing as it will make the intent of tests easier to understand as well.

**Review by stof — CHANGES_REQUESTED** [review]

**Review by maxbeckers — APPROVED** [review]

**Review by mtarld — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Florian-Merle.
