### PR TITLE
[Finder] Use a lazyIterator to close files descriptors when no longer used

### LINKED ISSUE #35508: [Finder] Using wildcard in `in()` leads to exceeding opened file descriptors limit
**Symfony version(s) affected**: 5.0.3, 4.3.0

**Description**  
Using Symfony Finder with a wildcard as a documented feature of `in` method throws a fatal error if a number of directories that match the wildcard bigger than open file descriptors limit.

The current implementation resolves a wildcard to the list of directories regardless of their number and creates an iterator for each of them bringing the risk to exceed the limit in the system.

**How to reproduce**  

```
composer init
composer require symfony/finder
touch find.php
```

```php
<?php

include 'vendor/autoload.php';

use Symfony\Component\Finder\Finder;

mkdir('pool');
for ($i = 0; $i < 100; ++$i) {
    $folder = 'pool/dir' . $i;
    mkdir($folder);
    file_put_contents($folder . '/target.txt', '');
}

$finder = new Finder();

$finder
    ->files('target.txt')
    ->in('pool/*')
    ->depth('== 0');

$cc = 0;
foreach ($finder as $file) {
    $cc++;
}

echo 'Found: ' . $cc;

```
```bash
bash -c "ulimit -n 50 && php find.php"
```
Actual result: fatal error
```
Fatal error: Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(pool/dir50): failed to open dir: Too many open files in /private/tmp/finder/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:48
Stack trace:
#0 /private/tmp/finder/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php(48): RecursiveDirectoryIterator->__construct('pool/dir50', 4096)
#1 /private/tmp/finder/vendor/symfony/finder/Finder.php(730): Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator->__construct('pool/dir50', 4096, false)
#2 /private/tmp/finder/vendor/symfony/finder/Finder.php(619): Symfony\Component\Finder\Finder->searchInDirectory('pool/dir50')
#3 /private/tmp/finder/find.php(22): Symfony\Component\Finder\Finder->getIterator()
#4 {main}
  thrown in /private/tmp/finder/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php on line 48
```
Expected result: No error. Low open file descriptors usage.

**Possible Solution**  
Avoiding creating X iterators.
Wildcard can bring millions of directories, so setting `ulimit` would not help.

**Additional context**  
```php
$dir = 'pool';
$directories = [];
foreach ($spryker as $dir) {
    $directories[] = new \RecursiveDirectoryIterator($dir);
}
var_dump($directories);
```
Running the code above within low `ulimit -n` leads to the same error.
It seems RecursiveDirectoryIterator opens a file descriptor on a creation and keeps it until destroyed.

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | fix #35508
| License       | MIT
| Doc PR        | -

The `RecursiveDirectoryIterator` class open the file on `__construct`. 
Because we Inject an instance of `RecursiveDirectoryIterator` inside the \AppendIterator` class, php opens a lot of file even before iterating on it.

This PR adds a new `LazyIterator` class that instantiate the decorated class only when something starts iterating on it.
When the iteration is over, it unset the variable to close let the decorated class clean things (ie. close the files)

### CODE REVIEW

File: src/Symfony/Component/Finder/Iterator/LazyIterator.php [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+    private $iterator;
+
+    public function __construct(callable $iteratorFactory)
+    {
+        $this->iteratorFactory = $iteratorFactory;
+    }
+
+    public function current()
+    {
+        return ($this->iterator ?? $this->iterator = ($this->iteratorFactory)())->current();
```
Comment (stof) [inline src/Symfony/Component/Finder/Iterator/LazyIterator.php]: if you call `current()` after the iterator has been unset (due to reaching the end), this would restart the iteration (same for all other methods btw)

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Finder/Iterator/LazyIterator.php (hunk 1 above)
Comment (jderusse) [reply src/Symfony/Component/Finder/Iterator/LazyIterator.php]: good catch!!!! thanks a lot.

Fixed and Test added

File: src/Symfony/Component/Finder/Iterator/LazyIterator.php [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+/**
+ * @author Jérémy Derussé <jeremy@derusse.com>
+ */
+class LazyIterator implements \Iterator
+{
+    /** @var callable */
+    private $iteratorFactory;
+    /** @var \Iterator */
+    private $iterator;
+    private $initialize = false;
```
Comment (ro0NL) [inline src/Symfony/Component/Finder/Iterator/LazyIterator.php]: `initialized`

**Comment by ro0NL** [comment]
im wondering if `IteratorAggregate` would be more simple to implement

eg. `append(LazyIterator::create($callable))`

```
class LazyIterator implements IteratorAggregate {
   getIterator() {
     yield from ($this->callback)();
   }
  static create($callback) {
     return new IteratorIterator(new self($callback));
  }
}
```

roughly :)

File: src/Symfony/Component/Finder/Iterator/LazyIterator.php (hunk 2 above)
Comment (jderusse) [reply src/Symfony/Component/Finder/Iterator/LazyIterator.php]: thanks

**Comment by jderusse** [comment]
> im wondering if `IteratorAggregate` would be more simple to implement

That's not possible, `AppendIterator::append` expect a instance of `Iterator` (in fact, everything in Finder is based on `Iterator`)

edit: I missed the trick with `IteratorIterator`... let me give a try

**Comment by jderusse** [comment]
Refactored to use IteratorAggregate .
Thank you for the good idea @ro0NL

**Review by ro0NL — APPROVED** [review]
👍🏻 for LazyIterator as feature also, given Finder::append() supports aggregates, eg. `Finder::append(new LazyIterator($callable))` works.

File: src/Symfony/Component/Finder/Iterator/LazyIterator.php [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+    private $iteratorFactory;
+
+    public function __construct(callable $iteratorFactory)
+    {
+        $this->iteratorFactory = $iteratorFactory;
+    }
+
+    public function getIterator()
+    {
+        yield from ($this->iteratorFactory)();
```
Comment (ro0NL) [inline src/Symfony/Component/Finder/Iterator/LazyIterator.php:28]: actually, im trying to reason when we'd benefit from yielding the factorized iterator. Does it make sense?

`return ($this->iteratorFactory)();` seems as lazy

Comment (ro0NL) [reply src/Symfony/Component/Finder/Iterator/LazyIterator.php:28]: ok. it does when doing `Finder::append(new LazyIt($c))`

https://3v4l.org/r7tjI

Comment (jderusse) [reply src/Symfony/Component/Finder/Iterator/LazyIterator.php:28]: This wouldn't fix the issue, as the instance of the factorized iterator will be passed to the caller and wont be destruct.

note: the original issue is because \AppendIterator keep a reference to the $iterators, and the `RecursiveDirectoryIterator` keep the file opened until destruct.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jderusse.

File: src/Symfony/Component/Finder/Iterator/LazyIterator.php [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\Finder\Iterator;
+
+/**
+ * @author Jérémy Derussé <jeremy@derusse.com>
+ */
+class LazyIterator implements \IteratorAggregate
```
Comment (stof) [inline src/Symfony/Component/Finder/Iterator/LazyIterator.php:17]: should we mark it as `@internal` ?

File: src/Symfony/Component/Finder/Iterator/LazyIterator.php (hunk 3 above)
Comment (stof) [reply src/Symfony/Component/Finder/Iterator/LazyIterator.php:28]: @jderusse I think this would deserve a comment in the code explaining this need, so that it is not lost in the future.

File: src/Symfony/Component/Finder/Iterator/LazyIterator.php (hunk 4 above)
Comment (xabbuh) [reply src/Symfony/Component/Finder/Iterator/LazyIterator.php:17]: I agree, see #40163
