### PR TITLE
[Serializer] Add option to skip uninitialized typed properties

### LINKED ISSUE #40578: [Serializer] Error when normalizing object with uninitialized typed properties when normalizer is loaded with class metadata factory.
**Symfony version(s) affected**: 5.2.4

**Description**
When using simple normalization - the fix introduced with this pull request: https://github.com/symfony/symfony/pull/38900 is working correctly. This is because the property metadata is read with reflection during the process and if the property is not initialized the above PR does not include it.

But when we're using groups to perform normalization, then we have to supply a class metadata factory that reads those. After using the factory, however, the typed properties are not checked whether they are initialized or not and are directly included.
This results in the same error that the above PR is trying to fix, namely: 

```
PHP Fatal error:  Uncaught Error: Typed property DataClass::$unInitialized must not be accessed before initialization in /path/to/vendor/symfony/property-access/PropertyAccessor.php:438
```

**How to reproduce**

```
class DataClass
{
    #[Groups(['foo'])]
    public string $unInitialized;

    #[Groups(['foo'])]
    public string $initialized = 'value';

    #[Groups(['bar'])]
    public string $initialized2 = 'value';
}

$object = new DataClass();

$classMetadataFactory = new ClassMetadataFactory(new AnnotationLoader(new AnnotationReader()));
$normalizer = new ObjectNormalizer($classMetadataFactory);
$normalizer->normalize($object, context: ['groups' => 'foo']);
```

**Possible Solution**

May be include whether the property is initialized in the metadata? But that would result in an issue when it's cached.
May be when the property accessor tries to read it and it founds that it's not initialized it can be silently excluded from the result?

**Additional context**
I'm using PHP8, found that bug when I was using API Platform, but it ultimately goes down to how the normalizer work in Symfony.

### PR DESCRIPTION
**Pull request by vuryss**
| Q             | A
| ------------- | ---
| Branch?       | 5.4 
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #40578
| License       | MIT

Adds the ability to skip uninitialized values from Serializer. This is useful when using typed properties in 7.4 and those without default values should not be included in the result.
This works correctly when we're not using serializer groups, but when using the groups - it breaks badly, so it's also kind of a fix in addition to feature.

### CODE REVIEW

File: src/Symfony/Component/Serializer/Tests/Normalizer/Features/SkipUninitializedValuesTestTrait.php [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+
+namespace Symfony\Component\Serializer\Tests\Normalizer\Features;
+
+use Symfony\Component\PropertyAccess\Exception\UninitializedPropertyException;
+use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
+
+/**
+ * Test AbstractObjectNormalizer::SKIP_UNINITIALIZED_VALUES.
+ *
+ * @requires PHP 7.4
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Tests/Normalizer/Features/SkipUninitializedValuesTestTrait.php]: should be removed

File: src/Symfony/Component/Serializer/Tests/Normalizer/Features/TypedPropertiesObject.php [hunk 2]
```diff
@@ -0,0 +1,25 @@
+<?php
+
+declare(strict_types=1);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Tests/Normalizer/Features/TypedPropertiesObject.php]: should be removed

**Review by nicolas-grekas — COMMENTED** [review]
Can you please rebase to trigger the CI again while fixing the review?

**Comment by vuryss** [comment]
> Can you please rebase to trigger the CI again while fixing the review?

Done. Thanks for the help with low deps issue. The failing test now does not seem to have anything in common with my changes.

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 3]
```diff
@@ -180,7 +187,16 @@ public function normalize($object, string $format = null, array $context = [])
             }
 
             $attributeContext = $this->getAttributeNormalizationContext($object, $attribute, $context);
-            $attributeValue = $this->getAttributeValue($object, $attribute, $format, $attributeContext);
+
+            try {
+                $attributeValue = $this->getAttributeValue($object, $attribute, $format, $attributeContext);
+            } catch (UninitializedPropertyException $exception) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: let's rename this to `$e` for consistency

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php (hunk 3 above)
Comment (vuryss) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: Done

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you @vuryss.
