### PR TITLE
[Console] Fix type of InputOption::$default

### LINKED ISSUE #40427: Console: InputInterface::getOption is missing the "int" return type
**Symfony version(s) affected**: 5.2.4, 4.4.20, 

**Description**
Console's `InputOption::getDefault` will return the following types:
```php
/**
 * Returns the default value.
 *
 * @return string|string[]|int|bool|null The default value
 */
public function getDefault()
{
    return $this->default;
}
```

`Input::getOption` (with `Input` implementing `InputInterface`falls back to the default value:
```php
    public function getOption($name)
    {
        if (!$this->definition->hasOption($name)) {
            throw new InvalidArgumentException(sprintf('The "%s" option does not exist.', $name));
        }

        return \array_key_exists($name, $this->options) ? $this->options[$name] : $this->definition->getOption($name)->getDefault();
    }
```

So `InputInterface::getOption` should provide all these types as well, but is it missing the `int` type:
```php
    /**
     * Returns the option value for a given option name.
     *
     * @param string $name The option name
     *
     * @return string|string[]|bool|null The option value
     *
     * @throws InvalidArgumentException When option given doesn't exist
     */
    public function getOption($name);
```
This will confuse static type checkers like PHPStan when an int is handled.

**Possible Solution**
Add the `int` type the the return type annotation of the interface.

### PR DESCRIPTION
**Pull request by oliverklee**
Options can also be `int`s. So add this type to the PHPDoc parameter
type annotation of `InputInterface::setOption` and the return type
annotation of `InputInterface::getOption`.

| Q             | A
| ------------- | ---
| Branch?       | 4.4 or 5.2 for bug fixes
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40427
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/Console/Input/InputInterface.php [hunk 1]
```diff
@@ -122,7 +122,7 @@ public function getOptions();
      *
      * @param string $name The option name
      *
-     * @return string|string[]|bool|null The option value
+     * @return string|string[]|int|bool|null The option value
```
Comment (jderusse) [inline src/Symfony/Component/Console/Input/InputInterface.php]: Thank for this PR, but this change looks wrong,  The options can be:
- `string`: `--option=foo`
- `string[]`: `--option=foo --option=bar`
- `bool`:  `--option` + `VALUE_NONE`
- `null`:  `--option` + `VALUE_OPTIONAL`

But there is no case where the value can be an integer.

Note: `--option=123` returns the string `"123"`.

Comment (chalasr) [reply src/Symfony/Component/Console/Input/InputInterface.php]: Indeed, see also https://github.com/symfony/symfony/pull/28374#issuecomment-419815248.

Comment (chalasr) [reply src/Symfony/Component/Console/Input/InputInterface.php]: We should rather remove `int` from the `getDefault()` doc block.

Comment (derrabus) [reply src/Symfony/Component/Console/Input/InputInterface.php]: `InputOption` declares `int` as a valid type for the default value: in the constructor signature as well as for `getDefault()` and `setDefault()`. This looks like a mistake to me because you can never produce an integer on the command line. But it means that it is possible, when following the documented public API, to receive an integer from `getOption()`.

Comment (dmaicher) [reply src/Symfony/Component/Console/Input/InputInterface.php]: Indeed when the default value is used then it can be the case that `getOption` returns an integer. I just tested it quickly.

```php
public function configure(): void
{
    $this->addOption('foo', null, InputOption::VALUE_REQUIRED, '', 123);
}

protected function execute(InputInterface $input, OutputInterface $output): int
{
    var_dump($input->getOption('foo'));die;
}
```

And then executed without passing any option at all:
==> `int(123)`

Edit: It actually seems one can pass anything as a default currently. This also works:

```php
->addOption('foo', null, InputOption::VALUE_REQUIRED, '', new \stdClass())
```

Comment (jderusse) [reply src/Symfony/Component/Console/Input/InputInterface.php]: Would you mind to change this PR to fix the `default` signature? @oliverklee

**Comment by oliverklee** [comment]
> Would you mind to change this PR to fix the default signature?

Will do.

**Comment by oliverklee** [comment]
I have updated the PR accordingly and repushed.

File: src/Symfony/Component/Console/Input/InputOption.php [hunk 2]
```diff
@@ -29,15 +29,16 @@ class InputOption
     private $name;
     private $shortcut;
     private $mode;
+    /** @var string|string[]|bool|null */
```
Comment (derrabus) [inline src/Symfony/Component/Console/Input/InputOption.php]: We usually don't add doc blocks for types that can be inferred from the constructor, to reduce the visual noise.

**Review by derrabus — COMMENTED** [review]
I think we also need to adjust `Command::addOption()`.

File: src/Symfony/Component/Console/Input/InputOption.php (hunk 2 above)
Comment (oliverklee) [reply src/Symfony/Component/Console/Input/InputOption.php]: Done.

**Comment by oliverklee** [comment]
> I think we also need to adjust `Command::addOption()`.

Thanks! Done and repushed.

**Review by derrabus — APPROVED** [review]

**Comment by oliverklee** [comment]
The test failures do not look like they could be related to my change.

**Review by chalasr — APPROVED** [review]

**Review by jderusse — APPROVED** [review]

**Comment by jderusse** [comment]
Thank you @oliverklee.

**Comment by mvorisek** [comment]
Hi guys, is this related with https://github.com/doctrine/dbal/issues/4557 and is there any immediate workaround?

**Comment by chalasr** [comment]
(reply to a comment that has been deleted meanwhile)

An immediate solution would be to ignore that failure in your static analyser configuration.
A long term solution would be to submit a PR to doctrine/dbal that casts the option' default value to string (`'7'` instead of 7), and cast it back to int when accessing the option value (which is probably already done, as when the value is not the default one it's always been a string).
