### PR TITLE
[HttpClient] Prevent "Fatal error" in data collector

### LINKED ISSUE #46604: Issue when sending email via HTTPClient (sendinblue+api transport) escapeshellarg(): Argument exceeds the allowed length
### Symfony version(s) affected

6.1.0

### Description

I'm experiencing a strange behavior when trying to send transactionnal e-mails.

I use `symfony/mailer 6.1.*` & `symfony/sendinblue-mailer 6.1.*`, I configured `sendinblue+api` transport.

Some of my transationnal e-mails throw this fatal error:

`Fatal error: escapeshellarg(): Argument exceeds the allowed length of 8192 bytes in C:\www\deposit\vendor\symfony\http-client\DataCollector\HttpClientDataCollector.php on line 194`

When using another transport (e.g. smtp, sendmail), I don't have this error. It seems normal as HTTPClient are not involved in these cases.

My email is 28.7KB weight.

It's look like it's a BC break of Symfony 6.1 as https://github.com/symfony/http-client/blob/6.1/DataCollector/HttpClientDataCollector.php changed to introduce usage of `escapeshellarg`. I understand it's more secure, but it introduces limitation to send e-mails through API.

### How to reproduce

Send a large e-mail with an API transport, e.g. sendinblue.

### Possible Solution

As workarround, it's possible to use `3rd-party-provider+smtp` instead of `3rd-party-provider+api` transport (but with loss of functionnalities, for instance tags).

### Additional Context

Found out that

`php -r "escapeshellarg(str_repeat('a', 8000));"` does not throw the error.

`php -r "escapeshellarg(str_repeat('a', 9000));"` throws the error.

### PR DESCRIPTION
**Pull request by fmata**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #46604
| License       | MIT

Since "copy as cURL" has been added in Profiler for HttpClient usage, when payloads exceed the size allowed by escapeshellarg() we have a Fatal error :disappointed:

The right allowed size depends on OS and is not leaked in PHP land so I prefer to be conservative and allow the lower usual value as explained in PHP source code https://github.com/php/php-src/blob/9458f5f2c8a8e3d6c65cc181747a5a75654b7c6e/ext/standard/exec.c#L77

I only added check where I think it's relevant.

### CODE REVIEW

File: src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php [hunk 1]
```diff
@@ -194,9 +205,15 @@ private function getCurlCommand(array $trace): ?string
         $dataArg = [];
 
         if ($json = $trace['options']['json'] ?? null) {
-            $dataArg[] = '--data '.escapeshellarg(json_encode($json, \JSON_PRETTY_PRINT));
+            if (!$this->argMaxLengthIsSafe($payload = json_encode($json, \JSON_PRETTY_PRINT))) {
```
Comment (stof) [inline src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php]: I would assign the variable before the condition to make the code more clear.

File: src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php [hunk 2]
```diff
@@ -95,6 +95,17 @@ public function reset()
...
 
+    /**
+     * Let's be defensive : we authorize only size of 4Mo for escapeshellarg() argument to avoid a fatal error
+     *
+     * @see https://github.com/php/php-src/blob/9458f5f2c8a8e3d6c65cc181747a5a75654b7c6e/ext/standard/exec.c#L397
+     * @see https://github.com/php/php-src/blob/9458f5f2c8a8e3d6c65cc181747a5a75654b7c6e/ext/standard/exec.c#77
+     */
+    private function argMaxLengthIsSafe(string $payload): bool
+    {
+        return strlen($payload) <= 4096;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php]: 4096 bytes is super small, this must be a mistake since you mention 4Mo in the comment
please also move the method at the bottom of the class and add a leading slash to `\strlen`

File: src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php [hunk 3]
```diff
@@ -95,6 +95,17 @@ public function reset()
         ];
     }
 
+    /**
+     * Let's be defensive : we authorize only size of 4Mo for escapeshellarg() argument to avoid a fatal error
+     *
+     * @see https://github.com/php/php-src/blob/9458f5f2c8a8e3d6c65cc181747a5a75654b7c6e/ext/standard/exec.c#L397
+     * @see https://github.com/php/php-src/blob/9458f5f2c8a8e3d6c65cc181747a5a75654b7c6e/ext/standard/exec.c#77
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php]: one link is enough

File: src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php (hunk 2 above)
Comment (stof) [reply src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php]: Looking at the PHP codebase, the size seems to be in bytes.

File: src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php (hunk 3 above)
Comment (fmata) [reply src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php]: done

File: src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php (hunk 2 above)
Comment (fmata) [reply src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php]: > please also move the method at the bottom of the class and add a leading slash to \strlen

yes sir :+1:, I thought php-cs-fixer would have pointed this out to me

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php]: fabbot (aka php-cs-fixer) is on vacation I think these days, it doesn't show up in the CI reports since a few weeks :P

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php]: > Looking at the PHP codebase, the size seems to be in bytes.

OK but then we cannot go by this limit, it's way too low I think.

Comment (fmata) [reply src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php]: It's difficult to be precise when the value is not accessible with PHP functions. What value do you think is enough ? Maybe 8 Mo to follow PHP algo :man_shrugging:

Comment (stof) [reply src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php]: @fmata where are you taking this 8Mo ? I don't see that in the PHP code. The hardcoded values I see in your links are 8KB on Windows and 4KB as fallback value. I don't see 8MB anywhere.

@nicolas-grekas if this size limit is too small, then we need to stop using `escapeshellargs`, because it is the one having a limit.

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php]: On my machine, I can go up to `escapeshellarg(str_repeat('-', 2097149));`.
What about others?

Comment (stof) [reply src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php]: Well, as seen in the PHP source code, the value of `cmd_max_len` can be set in a bunch of different ways during compilation. So it can indeed be higher on some systems. But this is not exposed to userland.

anyway, disabling the copy as curl feature in the profile is better than doing a fatal error when running the HTTP request

Comment (fmata) [reply src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php]: @stof because I messed up :facepalm: 

@nicolas-grekas on my Ubuntu 22.04 (same on Debian 11)

```
$ getconf ARG_MAX
2097152
```

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php]: So apparently on Windows we can't go above 8kio, and on linux we need to set a reasonably portable limit. Here is a suggestion, going a bit below the limit to account for escaping if that matters?
`return  \strlen($payload) < ('\\' === \DIRECTORY_SEPARATOR ? 8100 : 256000);`

Comment (fmata) [reply src/Symfony/Component/HttpClient/DataCollector/HttpClientDataCollector.php]: I like it ty, done.

**Comment by fmata** [comment]
@nicolas-grekas what is missing in this PR to be merged & released ? Last 6.1 patch was released 2 days ago :disappointed: We are facing fatal errors in dev environment on each request using HttpClient (we use it to upload PDF files).

**Review by nicolas-grekas — APPROVED** [review]
It felt off my radar before the release sorry.

**Comment by nicolas-grekas** [comment]
Thank you @fmata.

**Comment by DavidBadura** [comment]
FYI: Unfortunately, `ARG_MAX` varies from system to system and the hardcoded limit would have to be lowered even further for `alpine`. I created a follow-up ticket for it with more insides: https://github.com/symfony/symfony/issues/49693
