### PR TITLE
[HttpFoundation] Allow array style callable setting for Request setFactory method

### LINKED ISSUE #54321: [HttpFoundation] Type mismatch between Request::$requestFactory and Request::setFactory()
### Symfony version(s) affected

7.0.0

### Description

`Request` declares `$requestFactory` as a closure:
```
    protected static ?\Closure $requestFactory = null;
```

`::setFactory()` declares its argument as a callable:

```
    public static function setFactory(?callable $callable): void
    {
        self::$requestFactory = $callable;
    }
```

### How to reproduce

Drupal calls `::setFactory()` with a callable that isn't a closure:
```
$request_factory = new TrustedHostsRequestFactory('localhost');
Request::setFactory([$request_factory, 'createRequest']);
```

In Symfony 7 this results in
```
PHP Fatal error:  Uncaught TypeError: Cannot assign array to property Symfony\Component\HttpFoundation\Request::$requestFactory of type ?Closure
```

### Possible Solution

Either convert the callable to a closure internally with `Closure::fromCallable()` or change the typehint of the `setFactory()` argument to `\Closure`, unsure which is the preferred solution here.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jan-simbera**
| Q             | A
| ------------- | ---
| Branch? | 7.0
| Bug fix? | yes
| New feature? | no
| Deprecations? | no
| Issues | Fix #54321
| License | MIT

Allowing to use the array notation for callback for the setFactory static method of the request.

Unit test added to confirm bug/fixing the bug.

### CODE REVIEW

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 1]
```diff
@@ -382,7 +382,12 @@ public static function create(string $uri, string $method = 'GET', array $parame
      */
     public static function setFactory(?callable $callable): void
     {
-        self::$requestFactory = $callable;
+        if(null === $callable) {
+            self::$requestFactory = null;
+            return;
+        }
+
+        self::$requestFactory = $callable(...);
```
Comment (derrabus) [inline src/Symfony/Component/HttpFoundation/Request.php]: We usually use a ternary expression when resolving this kind of union.

```suggestion
        if(null === $callable) {
            self::$requestFactory = null;
            return;
        }

        self::$requestFactory = null === $callable ? null : $callable(...);
```

File: src/Symfony/Component/HttpFoundation/Tests/RequestTest.php [hunk 2]
```diff
@@ -2197,6 +2197,23 @@ public function testFactory()
         Request::setFactory(null);
     }
 
+    public function testFactoryCallable()
+    {
+        $request_factory = new class {
```
Comment (derrabus) [inline src/Symfony/Component/HttpFoundation/Tests/RequestTest.php]: CS: camel case for variable names

File: src/Symfony/Component/HttpFoundation/Tests/RequestTest.php [hunk 3]
```diff
@@ -2197,6 +2197,23 @@ public function testFactory()
...
+            public function createRequest(array $query = [], array $request = [], array $attributes = [], array $cookies = [], array $files = [], array $server = [], $content = null): Request
```
Comment (derrabus) [inline src/Symfony/Component/HttpFoundation/Tests/RequestTest.php]: You don't use any of those parameters.

```suggestion
            public function createRequest(): Request
```

File: src/Symfony/Component/HttpFoundation/Tests/RequestTest.php [hunk 4]
```diff
@@ -2197,6 +2197,23 @@ public function testFactory()
...
+            {
+                return new NewRequest();
```
Comment (derrabus) [inline src/Symfony/Component/HttpFoundation/Tests/RequestTest.php:2205]: Does this class exist?

**Review by derrabus — CHANGES_REQUESTED** [review]
Thank you. Please find a meaningful title for your PR. We compose our changelog out of those titles.

File: src/Symfony/Component/HttpFoundation/Tests/RequestTest.php (hunk 3 above)
Comment (jan-simbera) [reply src/Symfony/Component/HttpFoundation/Tests/RequestTest.php]: Changed.

File: src/Symfony/Component/HttpFoundation/Tests/RequestTest.php (hunk 2 above)
Comment (jan-simbera) [reply src/Symfony/Component/HttpFoundation/Tests/RequestTest.php]: Fixed.

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 1 above)
Comment (jan-simbera) [reply src/Symfony/Component/HttpFoundation/Request.php]: Fixed.

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Good catch, thanks @jan-simbera.
