### PR TITLE
[Serializer] fix denormalization of basic property-types in XML and CSV

### LINKED ISSUE #33849: Serializer does not map basic non-string types correctly in XML and CSV
**Symfony version(s) affected**: 3.4, 4.4

**Description**  
In XML and CSV, all values are represented the same way, it is not possible to determine if a value is intended to be a string, int, float or boolean. 

If something with non string properties (int, float, bool) is deserialized, an error is thrown:

```
PHP Fatal error:  Uncaught Symfony\Component\Serializer\Exception\NotNormalizableValueException: The type of the "width" attribute for class "App\Entities\Building" must be one of "float" ("string" given). in ./symfony-collection-serializer-bug/Normalizer/AbstractObjectNormalizer.php:298
Stack trace:
#0 ./symfony-collection-serializer-bug/Normalizer/AbstractObjectNormalizer.php(202): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->validateAndDenormalize('App\\Entities\\Bu...', 'width', '10.1', 'xml', Array)
#1 ./symfony-collection-serializer-bug/Serializer.php(172): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denormalize(Array, 'App\\Entities\\Bu...', 'xml', Array)
#2 ./symfony-collection-serializer-bug/Serializer.php(123): Symfony\Component\Serializer\Serializer->denormalize(Array, 'App\\Entities\\Bu...', 'xml', Array)
...
```
**How to reproduce**  
I'll submit a PR with a failing test

**Possible Solution**  
The values need to be converted cast to the expected type. 

**Additional context**  
Tested with php 7.2

### PR DESCRIPTION
**Pull request by mkrauser**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #33849
| License       | MIT
| Doc PR        | 

Like I explained in the Issue, the serializer cannot de-serialize non-string basic properties (int, float, bool). This PR add's some logic to cast to the expected types.

Similar logic is already present in the [XmlUtils](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Config/Util/XmlUtils.php#L215)-Class of the Config-Component

### CODE REVIEW

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php [hunk 1]
```diff
@@ -26,7 +26,7 @@
 
 class AbstractObjectNormalizerTest extends TestCase
 {
-    public function testDenormalize()
+    public function _testDenormalize()
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: please don't do this

Comment (mkrauser) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: Sorry, I forgot to undo that

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 2]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
...
 
+            // In XML and CSV all basic datatypes are represented as strings, it is e.g. not possible to determine,
+            // if a value is meant to be a string, float, int or a boolean value from the serialized representation.
+            // That's why we have to transform the values, if one of these non-string basic datatypes is epxected.
+            //
+            // This is special to xml and csv format
+            if (
+                (XmlEncoder::FORMAT === $format || CsvEncoder::FORMAT === $format) &&
+                \in_array($type->getBuiltinType(), [Type::BUILTIN_TYPE_BOOL, Type::BUILTIN_TYPE_INT, Type::BUILTIN_TYPE_FLOAT]) &&
+                \is_string($data)
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: this one should be tested first

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 3]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
...
             }
 
+            // In XML and CSV all basic datatypes are represented as strings, it is e.g. not possible to determine,
+            // if a value is meant to be a string, float, int or a boolean value from the serialized representation.
+            // That's why we have to transform the values, if one of these non-string basic datatypes is epxected.
+            //
+            // This is special to xml and csv format
+            if (
+                (XmlEncoder::FORMAT === $format || CsvEncoder::FORMAT === $format) &&
+                \in_array($type->getBuiltinType(), [Type::BUILTIN_TYPE_BOOL, Type::BUILTIN_TYPE_INT, Type::BUILTIN_TYPE_FLOAT]) &&
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: please add `true` as last argument

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 4]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
...
+                \is_string($data)
+            ) {
+                switch ($type->getBuiltinType()) {
+                    case Type::BUILTIN_TYPE_BOOL:
+                        // according to https://www.w3.org/TR/xmlschema-2/#boolean, valid representations are "false", "true", "0" and "1"
+                        if ('false' === $data || '0' === $data) {
+                            $data = false;
+                        } elseif ('true' === $data || '1' === $data) {
+                            $data = true;
+                        }
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: what should happen in the remaining implicit else case?

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 5]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
...
+                        break;
+                    case Type::BUILTIN_TYPE_INT:
+
+                        if (
+                            true === ctype_digit($data) ||
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: please remove comparisons to `true` in the PR

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 6]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
...
+                            '-' == $data[0] && true === ctype_digit(substr($data, 1))
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: `===` - but can the empty string happen here? if yes it should be handled

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 7]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
...
+                        ) {
+                            $data = (int) $data;
+                        }
+                        break;
+                    case Type::BUILTIN_TYPE_FLOAT:
+                        if (is_numeric($data)) {
+                            return '0x' === $data[0].$data[1] ? hexdec($data) : (float) $data;
+                        } elseif (
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: When the previous "if" returns, we prefer not using "elseif" when it's not needed, so this one (and the following) should be an "if" instead.

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 8]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
...
+                            true === ctype_digit($data) ||
+                            '-' == $data[0] && true === ctype_digit(substr($data, 1))
+                        ) {
+                            $data = (int) $data;
+                        } elseif ('NaN' === $data) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: NAN too?

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 9]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
...
+                            return NAN;
+                        } elseif ('INF') {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: `Inf` too?

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 10]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
...
+                            return INF;
+                        } elseif ('-INF') {
+                            return -INF;
+                        }
+
+                        break;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: so, we silently ignore other values, is this correct? (same for the "int" case btw)

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 11]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
...
+            // This is special to xml and csv format
+            if (
+                \is_string($data) &&
+                (XmlEncoder::FORMAT === $format || CsvEncoder::FORMAT === $format) &&
+                \in_array($type->getBuiltinType(), [Type::BUILTIN_TYPE_BOOL, Type::BUILTIN_TYPE_INT, Type::BUILTIN_TYPE_FLOAT], true)
+            ) {
+                switch ($type->getBuiltinType()) {
+                    case Type::BUILTIN_TYPE_BOOL:
+                        // according to https://www.w3.org/TR/xmlschema-2/#boolean, valid representations are "false", "true", "0" and "1"
+                        if ('false' === $data || '0' === $data) {
```
Comment (warslett) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: what about other values conventionally used in XML web services eg. 'False', 'F', 'f'. Can I suggest condition becomes:
`in_array($value, ['false', 'False', 'F', 'f', "0"], true)`

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 12]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
...
+                            $data = false;
+                        } elseif ('true' === $data || '1' === $data) {
```
Comment (warslett) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: `in_array($value, ['true', 'True', 'T', 't', "1"], true)`

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php (hunk 4 above)
Comment (warslett) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: throw validation exception. An exception will probably be thrown anyway so if the property is boolean and the value in the data is "cat" might as well throw a helpful exception here.

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 13]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
...
+                            $data = true;
+                        }
+                        break;
+                    case Type::BUILTIN_TYPE_INT:
+                        if (
+                            ctype_digit($data) ||
+                            '-' == $data[0] && ctype_digit(substr($data, 1))
+                        ) {
+                            $data = (int) $data;
+                        }
```
Comment (warslett) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: else throw Exception?

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 14]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
...
+                        break;
+                    case Type::BUILTIN_TYPE_FLOAT:
+                        if (is_numeric($data)) {
+                            return '0x' === $data[0].$data[1] ? hexdec($data) : (float) $data;
+                        }
+                        if (
+                            ctype_digit($data) ||
+                            '-' == $data[0] && ctype_digit(substr($data, 1))
+                        ) {
+                            $data = (int) $data;
```
Comment (warslett) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: I don't understand why we are casting as int here. Surely the first is_numeric condition block is enough. When would a number pass this condition but not the is_numeric condition?

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php (hunk 8 above)
Comment (warslett) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: doesn't hurt

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php (hunk 10 above)
Comment (warslett) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: better to throw Exception

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php (hunk 9 above)
Comment (warslett) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: also doesn't hurt

**Review by warslett — COMMENTED** [review]
This solution will not solve the problem in the API Platform because API Platform detects types differently. If we can extract this logic into a protected function something like `protected function castStringToBuiltInType(string $builtInType, string $value)` it will make this easier to fix in API Platform without further duplication.

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 15]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
                 $data = [$data];
             }
 
+            // In XML and CSV all basic datatypes are represented as strings, it is e.g. not possible to determine,
+            // if a value is meant to be a string, float, int or a boolean value from the serialized representation.
+            // That's why we have to transform the values, if one of these non-string basic datatypes is epxected.
```
Comment (teohhanhui) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: typo: epxected -> expected

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php (hunk 11 above)
Comment (teohhanhui) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: We should respect the definition of `xsd:boolean`, not PHP's handling of boolean conversions, or worse, special values used in web apps.

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 16]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
...
+            //
+            // This is special to xml and csv format
+            if (
+                \is_string($data) &&
+                (XmlEncoder::FORMAT === $format || CsvEncoder::FORMAT === $format) &&
+                \in_array($type->getBuiltinType(), [Type::BUILTIN_TYPE_BOOL, Type::BUILTIN_TYPE_INT, Type::BUILTIN_TYPE_FLOAT], true)
```
Comment (teohhanhui) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: This final condition is redundant since it's already checked in the switch case.

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php (hunk 4 above)
Comment (teohhanhui) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: Type enforcement will do its thing later on (if it's enabled). Otherwise, if you're using strict types, you'd get an error; if not, nothing happens.

Comment (teohhanhui) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: If type enforcement is enabled, a `NotNormalizableValueException` will be thrown below. Otherwise: if using strict types, you might get an error; if not, nothing special (just as before).

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 17]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
...
+                        if (
+                            ctype_digit($data) ||
+                            '-' == $data[0] && ctype_digit(substr($data, 1))
+                        ) {
+                            $data = (int) $data;
+                        }
+                        break;
+                    case Type::BUILTIN_TYPE_FLOAT:
+                        if (is_numeric($data)) {
+                            return '0x' === $data[0].$data[1] ? hexdec($data) : (float) $data;
```
Comment (teohhanhui) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: The `0x` case is not possible:

> Hexadecimal (e.g. 0xf4c3b00c) and binary (e.g. 0b10100111001) notation is not allowed.

https://www.php.net/manual/en/function.is-numeric.php

Comment (teohhanhui) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: Also, `xsd:float` does not allow using hexadecimal representation anyway:

https://www.w3.org/TR/xmlschema-2/#float

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 18]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
                 $data = [$data];
             }
 
+            // In XML and CSV all basic datatypes are represented as strings, it is e.g. not possible to determine,
```
Comment (teohhanhui) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: For XML, isn't it better to do XSD validation in the encoder instead?

For CSV, all bets are off. We can't reasonably know how to convert anything here.

Comment (warslett) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: Would that mean that developers would need to create an XSD document for each and every entity they want to deserialize in order to work with XML (having already defined type information separately in the Entity)? Is that practical? XSD would be a nice feature for validation but at the moment XML deserialization is essentially unusable for any data that includes floats and integers and there aught to be a way of dealing with that. XML APIs will typically interpret values set on boolean properties as booleans. Validation is a separate concern to that.

**Review by mkrauser — COMMENTED** [review]
> This solution will not solve the problem in the API Platform because API Platform detects types differently. If we can extract this logic into a protected function something like `protected function castStringToBuiltInType(string $builtInType, string $value)` it will make this easier to fix in API Platform without further duplication.

@nicolas-grekas Would that be ok?

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 19]
```diff
@@ -252,6 +254,54 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
...
+                        if (
+                            true === ctype_digit($data) ||
+                            '-' == $data[0] && true === ctype_digit(substr($data, 1))
+                        ) {
+                            $data = (int) $data;
+                        }
+                        break;
+                    case Type::BUILTIN_TYPE_FLOAT:
+                        if (is_numeric($data)) {
+                            return '0x' === $data[0].$data[1] ? hexdec($data) : (float) $data;
```
[the remark this answers is not in the document]
Comment (teohhanhui) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: > XSD does allow hex for numeric types

Source? I can't find anything about that in the XML Schema spec: https://www.w3.org/TR/xmlschema-2

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 20]
```diff
@@ -252,6 +254,63 @@ private function validateAndDenormalize($currentClass, $attribute, $data, $forma
...
 
+            // In XML and CSV all basic datatypes are represented as strings, it is e.g. not possible to determine,
+            // if a value is meant to be a string, float, int or a boolean value from the serialized representation.
+            // That's why we have to transform the values, if one of these non-string basic datatypes is expected.
+            //
+            // This is special to xml and csv format
+            if (
+                \is_string($data) &&
+                (XmlEncoder::FORMAT === $format || CsvEncoder::FORMAT === $format)
+            ) {
```
[the remark this answers is not in the document]
Comment (dunglas) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: It could be useful for other formats as well. IMHO this logic should be extracted in another class for re-usability, and because this class is already way too big.

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php (hunk 9 above)
Comment (dunglas) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: The test is broken (should be `'INF' === $data`). Also, a switch will perform better than a succession of is/else.

**Review by dunglas — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php (hunk 9 above)
Comment (mkrauser) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: Thank you, this is implemented using switch now

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php (hunk 20 above)
[the remark this answers is not in the document]
Comment (mkrauser) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: > It could be useful for other formats as well. IMHO this logic should be extracted in another class for re-usability, and because this class is already way too big.

I agree, the AbstractObjectNormalizer is getting too big and it needs a bit of refactoring. I can extract this into another class. Any ideas how to name it?

[the remark this answers is not in the document]
Comment (mkrauser) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: I thought about this, sure we can put that functionality in another class. But like @dunglas already said [here](https://github.com/symfony/symfony/issues/19330#issuecomment-235606760), most of the code of the Normalizers should be extracted and used via composition rather then inheritance. 
If this is the way to go. I would rather do that in a separate PR and leave this one as it is.

**Comment by fabpot** [comment]
@teohhanhui @dunglas @nicolas-grekas Can you review again this PR?

**Review by dunglas — APPROVED** [review]
I still think that this logic should be extracted in a dedicated class but it's not a blocker.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Merging as new feature though.

**Comment by fabpot** [comment]
Thank you @mkrauser.
