### PR TITLE
[Validator] Fix using known option names as field names

### LINKED ISSUE #52993: Constraints Collection fields with key fields
### Symfony version(s) affected

6.4

### Description

With this assert
```php
#[Assert\Collection(
    fields: [
        'fields' => [new Assert\Type(type: 'array')],
        'properties' => [new Assert\Type(type: 'array')],
        'catalog' => [new Assert\Type(type: 'array')],
    ],
)]
private array $configuration;
```

i got 

```
The options "properties", "catalog" do not exist in constraint "Symfony\Component\Validator\Constraints\Collection".
Symfony\Component\Validator\Exception\InvalidOptionsException: The options "properties", "catalog" do not exist in constraint "Symfony\Component\Validator\Constraints\Collection". in /srv/exmo/book24/vendor/symfony/validator/Constraint.php:182
```

but if i rename 'fields' in 'fileds2', the problem will disappear.

### How to reproduce
```php
<?php
require_once __DIR__.'/vendor/autoload.php';
use Symfony\Component\Validator\Constraints;
use Symfony\Component\Validator\Constraints as Assert;


$constraint = new Constraints\Collection(
    fields: [
        'fields' => [new Assert\Type(type: 'array')],
        'properties' => [new Assert\Type(type: 'array')],
        'catalog' => [new Assert\Type(type: 'array')],
    ]
);
$validator = new Assert\CollectionValidator();

var_dump(
    $validator->validate(
        [
            'fields' => [],
            'properties' => [],
            'catalog' => [],
        ],
        $constraint
    )
);
```
### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #52993
| License       | MIT

Instead of assuming `$fields` is not the fields array when any of the keys is a known option, let's assume it is the fields array if all keys are known options. Of course, this approach won't work if someone names all their fields after known options, but I don't believe that will actually happen.

### CODE REVIEW

File: src/Symfony/Component/Validator/Constraints/Collection.php [hunk 1]
```diff
@@ -41,9 +41,12 @@ class Collection extends Composite
      */
     public function __construct($fields = null, array $groups = null, $payload = null, bool $allowExtraFields = null, bool $allowMissingFields = null, string $extraFieldsMessage = null, string $missingFieldsMessage = null)
     {
-        // no known options set? $fields is the fields array
-        if (\is_array($fields)
-            && !array_intersect(array_keys($fields), ['groups', 'fields', 'allowExtraFields', 'allowMissingFields', 'extraFieldsMessage', 'missingFieldsMessage'])) {
```
Comment (HypeMC) [inline src/Symfony/Component/Validator/Constraints/Collection.php:46]: I'm pretty sure `payload` was missing in the array of known options. Switching to a dynamic approach using reflection should solve this and any similar issues that may occur in the future.

File: src/Symfony/Component/Validator/Constraints/Collection.php [hunk 2]
```diff
@@ -41,9 +41,12 @@ class Collection extends Composite
...
+        $knowOptions = array_map(function (\ReflectionParameter $parameter) {
+            return $parameter->name;
+        }, (new \ReflectionMethod(__METHOD__))->getParameters());
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraints/Collection.php]:
```suggestion
        static $knowOptions;
        $knownOptions ??= array_column((new \ReflectionMethod(__METHOD__))->getParameters(), 'name');
```

File: src/Symfony/Component/Validator/Constraints/Collection.php (hunk 1 above)
Comment (xabbuh) [reply src/Symfony/Component/Validator/Constraints/Collection.php:46]: What about picking the first item of `$fields` instead and check if it is a `Constraint` instance (or an array of)?

Comment (HypeMC) [reply src/Symfony/Component/Validator/Constraints/Collection.php:46]: Won't work cause of https://github.com/symfony/symfony/blob/ddf3bcbbb2ec1b4110b9998b2414dee2091def36/src/Symfony/Component/Validator/Constraints/Collection.php#L69-L74

File: src/Symfony/Component/Validator/Constraints/Collection.php (hunk 2 above)
Comment (HypeMC) [reply src/Symfony/Component/Validator/Constraints/Collection.php]: Done, I had to adjust the code for PHP 7.2. I'm wondering, is the static variable necessary since this all happens in the constructor?

File: src/Symfony/Component/Validator/Constraints/Collection.php (hunk 1 above)
Comment (xabbuh) [reply src/Symfony/Component/Validator/Constraints/Collection.php:46]: I am not sure I understand. Checking for instances of `Constraint` would still yield `true`, wouldn't it?

Comment (HypeMC) [reply src/Symfony/Component/Validator/Constraints/Collection.php:46]: Yes, I don't recall why I initially discarded the suggestion, but it works. I did have to modify one test because a different exception is thrown now. I'm not sure if that qualifies as a BC break.

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @HypeMC.

**Comment by tscni** [comment]
Fyi, this breaks code where `$fields` is an empty array

**Comment by xabbuh** [comment]
@tscni Can you please try #53383?

**Comment by dresslerdemos** [comment]
I tried this (https://github.com/symfony/symfony/pull/53383) fix and it still breaks for an empty list of constraints, which I confirmed was working in `v5.4.29`:

```
    public function testEmptyConstraintList()
    {
        // Symfony\Component\Validator\Exception\InvalidOptionsException : The options "foo" do not exist in constraint "Symfony\Component\Validator\Constraints\Collection".
        new Collection(
            [
                'foo' => []
            ],
            null,
            null,
            true,
            false
        );

        self::assertTrue(true);
    }
```

For my use case I can mitigate this by using `fields`, but I wanted to give a heads up regarding backward compatibility.

```
    public function testEmptyConstraintList2()
    {
        new Collection(
            ['fields' => [
                'foo' => []
            ]],
            null,
            null,
            true,
            false
        );

        self::assertTrue(true);
    }
```

**Comment by nerones** [comment]
just had the same problem as @dresslerdemos

**Comment by xabbuh** [comment]
I have a fix pending locally. I’ll keep you posted.

**Comment by xabbuh** [comment]
@dresslerdemos @nerones Can you check if #53443 fixes it for you?
