### PR TITLE
[HttpKernel] Support typehint to deprecated FlattenException in controller

### LINKED ISSUE #34661: [HttpKernel] ErrorListener doesnt convert throwable to legacy FlattenException for controller argument
**Symfony version(s) affected**: 4.4.0

**Description**  

ErrorListener doesnt convert throwable to legacy FlattenException for controller argument and it leads to exception:
```
Argument 1 passed to ExceptionController::__invoke() must be an instance of Symfony\Component\Debug\Exception\FlattenException, instance of TypeError given, called in /.../vendor/symfony/http-kernel/HttpKernel.php on line 146
```

**How to reproduce**  

Declare controller with `Symfony\Component\Debug\Exception\FlattenException` argument,
use `Symfony\Component\HttpKernel\EventListener\ErrorListener` with configured reference to controller.

**Possible Solution**  

Check `Symfony\Component\Debug\Exception\FlattenException` here https://github.com/symfony/symfony/blob/1b4ab8108542daddd6ca96caf38b464ff3cc459a/src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php#L101

**Additional context**  

DI config:
```yaml
services:
  exception_error.listener:
  class: Symfony\Component\HttpKernel\EventListener\ExceptionListener
  tags:
    - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -1 }
  arguments:
    - 'ExceptionController'
    - '@?logger'
```

Controller example:
```php
use Symfony\Component\Debug\Exception\FlattenException;
use Symfony\Component\HttpFoundation\JsonResponse;

class ExceptionController
{
    public function __invoke(FlattenException $exception): JsonResponse
    {
        return new JsonResponse(['message' => $exception->getMessage(), 'failed' => true]);
    }
}
```

### PR DESCRIPTION
**Pull request by andrew-demb**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34661 
| License       | MIT
| Doc PR        | 

We should support converting throwable to `FlattenException` with typehint to deprecated class also

### CODE REVIEW

**Comment by andrew-demb** [comment]
Temporary workaround for me (in case, that I should preserve BC with `^3.4|^4.0` versions) - drop typehint in controller argument.

**Review by chalasr — APPROVED** [review]

**Review by yceruto — COMMENTED** [review]
Isn't the current `ExceptionListener` intended to preserve that compatibility?

Could you please elaborate a bit more on the actual use case?

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php [hunk 1]
```diff
@@ -98,7 +99,7 @@ public function onControllerArguments(ControllerArgumentsEvent $event)
         $r = new \ReflectionFunction(\Closure::fromCallable($event->getController()));
         $r = $r->getParameters()[$k] ?? null;
 
-        if ($r && (!$r->hasType() || FlattenException::class === $r->getType()->getName())) {
+        if ($r && (!$r->hasType() || FlattenException::class === $r->getType()->getName() || LegacyFlattenException::class === $r->getType()->getName())) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php]: `if ($r && (!$r->hasType() || \in_array($r->getType()->getName(), [FlattenException::class, LegacyFlattenException::class, true])) {`

**Comment by andrew-demb** [comment]
My use case:
I replaced `ExceptionListener` usage in favor `ErrorListener` (as deprecation message describes) and I expect, that my (not updated - with used old-namespaced exception class) controller will work.

File: src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php (hunk 1 above)
Comment (andrew-demb) [reply src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php]: Addressed. Thank you.

**Comment by nicolas-grekas** [comment]
Thank you @andrew-demb.
