### PR TITLE
[Notifier] Fix `SweegoTransport` by allowing bool values

### LINKED ISSUE #63521: [Notifier][Sweego] false values removed from body payload
### Symfony version(s) affected

7.2.0

### Description

👋🏼 
When using SweegoTransport the json payload sent can contains false values:

```json
{
    "channel": "sms",
    "provider": "sweego",
    "recipients": [
        { "num": "YOUR_NUMBER", "region": "FR" }
    ],
    "message-txt": "SMS body",
    "campaign-type": "transac",
    "bat": false, // <--
    "campaign-id": "random-campaign-id",
    "sender-id": "YOUR_SENDER_ID",
    "shorten_urls": false, // <--
}
```

But `array_filter` is used on the body and these values are removed.

Payload sent:

```json
{
    "channel": "sms",
    "provider": "sweego",
    "recipients": [
        { "num": "YOUR_NUMBER", "region": "FR" }
    ],
    "message-txt": "SMS body",
    "campaign-type": "transac",
    "campaign-id": "random-campaign-id",
    "sender-id": "YOUR_SENDER_ID"
}
```
### How to reproduce

Use SweegoTransport with `shorten_urls` option to false

### Possible Solution

Remove usage of `array_filter` or remove only null values.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by qdequippe**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  |no
| Deprecations? |no
| Issues        | Fix #63521
| License       | MIT

Allow boolean values in body payload, remove null values.

### CODE REVIEW

File: src/Symfony/Component/Notifier/Bridge/Sweego/Tests/SweegoTransportTest.php [hunk 1]
```diff
@@ -87,4 +88,30 @@ public function testSendSmsMessage()
...
+            $this->assertFalse($body['shorten_urls']);
+            $this->assertFalse($body['shorten_with_protocol']);
+
+            return new JsonMockResponse(['swg_uids' => ['123']]);
+        });
+
+        $transport = self::createTransport($client);
+        $options = new SweegoOptions([
+            'shorten_urls' => false,
+            'shorten_with_protocol' => false,
```
Comment (alexandre-daubois) [inline src/Symfony/Component/Notifier/Bridge/Sweego/Tests/SweegoTransportTest.php:121]: Could `true` be used for the second option? This way we are sure that we cover both case and that the code doesn't do some strange coercion

File: src/Symfony/Component/Notifier/Bridge/Sweego/SweegoTransport.php [hunk 2]
```diff
@@ -86,12 +86,14 @@ protected function doSend(MessageInterface $message): SentMessage
         $body = $this->setShortenUrls($body, $options);
         $body = $this->setShortenWithProtocol($body, $options);
 
+        $body = array_filter($body, static fn ($value) => null !== $value);
```
Comment (alexandre-daubois) [inline src/Symfony/Component/Notifier/Bridge/Sweego/SweegoTransport.php]: You can inline this variable

File: src/Symfony/Component/Notifier/Bridge/Sweego/Tests/SweegoTransportTest.php (hunk 1 above)
Comment (qdequippe) [reply src/Symfony/Component/Notifier/Bridge/Sweego/Tests/SweegoTransportTest.php:121]: yes (even if it will not be processed by the provider).

You suggest to set a option to `true` to cover every both `false` and `true`?

File: src/Symfony/Component/Notifier/Bridge/Sweego/SweegoTransport.php (hunk 2 above)
Comment (qdequippe) [reply src/Symfony/Component/Notifier/Bridge/Sweego/SweegoTransport.php]:
```php
        $response = $this->client->request('POST', $endpoint, [
            'headers' => [
                'Api-Key' => $this->apiKey,
            ],
            'json' => array_filter($body, static fn ($value) => null !== $value),
        ]);
```

?

File: src/Symfony/Component/Notifier/Bridge/Sweego/Tests/SweegoTransportTest.php (hunk 1 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/Notifier/Bridge/Sweego/Tests/SweegoTransportTest.php:121]: Yes

**Review by alexandre-daubois — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @qdequippe.
