### PR TITLE
[HttpClient] Fix Content-Length header when possible

### LINKED ISSUE #45260: [HttpClient] Calculate request content-length
### Description

See https://github.com/phpro/soap-client/issues/416 for background.

It would be nice if HttpClient calculates a default request content-length header.

I think generally the more http details we provide, the better.

Another option/behavior could be to force re-calculate an existing content-length header as httplug does: https://github.com/php-http/curl-client/blob/2ed4245a817d859dd0c1d51c7078cdb343cf5233/src/Client.php#L346

But perhaps we should produce a log once we change the user value.

### Example

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45260
| License       | MIT
| Doc PR        | -

When userland fails to compute the correct Content-Length header and we can fix it, as is the case in the linked issue.

### CODE REVIEW

**Review by ro0NL — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Component/HttpClient/HttpClientTrait.php [hunk 1]
```diff
@@ -86,6 +86,14 @@ private static function prepareRequest(?string $method, ?string $url, array $opt
 
         if (isset($options['body'])) {
             $options['body'] = self::normalizeBody($options['body']);
+
+            if (\is_string($options['body'])
+                && (string) \strlen($options['body']) !== substr($h = $options['normalized_headers']['content-length'][0] ?? '', 16)
+                && ('' !== $h || ('' !== $options['body'] && !isset($options['normalized_headers']['transfer-encoding'])))
+            ) {
+                $options['normalized_headers']['content-length'] = [substr_replace($h ?: 'Content-Length: ', \strlen($options['body']), 16)];
```
Comment (fancyweb) [inline src/Symfony/Component/HttpClient/HttpClientTrait.php:94]: Can't we do `'Content-Length: '.\strlen($options['body'])` directly?

File: src/Symfony/Component/HttpClient/HttpClientTrait.php [hunk 2]
```diff
@@ -86,6 +86,14 @@ private static function prepareRequest(?string $method, ?string $url, array $opt
...
+                $options['headers'] = array_merge(...array_values($options['normalized_headers']) ?: [[]]);
```
Comment (fancyweb) [inline src/Symfony/Component/HttpClient/HttpClientTrait.php]: Can `array_values($options['normalized_headers'])` be falsy while we just set `'content-length'` above?

File: src/Symfony/Component/HttpClient/HttpClientTrait.php [hunk 3]
```diff
@@ -86,6 +86,14 @@ private static function prepareRequest(?string $method, ?string $url, array $opt
...
+            }
```
Comment (kaznovac) [inline src/Symfony/Component/HttpClient/HttpClientTrait.php]: readability is questionable, feels like obfuscated js code...

File: src/Symfony/Component/HttpClient/HttpClientTrait.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/HttpClient/HttpClientTrait.php:94]: We always try to preserve the case of the submitted headers, that's why.

File: src/Symfony/Component/HttpClient/HttpClientTrait.php (hunk 2 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/HttpClient/HttpClientTrait.php]: 'headers' is a list, we need to remove the previous content-length and set the new one. This does it.

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpClient/HttpClientTrait.php]: got it, updated

**Review by fancyweb — APPROVED** [review]

**Comment by fancyweb** [comment]
Thank you @nicolas-grekas.
