### PR TITLE
[HttpClient] Fix Failed to open stream: Too many open files

### LINKED ISSUE #44900: [HttpClient] Failed to open stream: Too many open files
### Symfony version(s) affected

4.5.2 / 5.3.13

### Description

When launching PHPUnit test suite, I have this error: 
```
PHPUnit 9.5.11 by Sebastian Bergmann and contributors.

Testing 
.............................................................   61 / 4733 (  1%)
.............................................................  122 / 4733 (  2%)
.............................................................  183 / 4733 (  3%)
.............................................................  244 / 4733 (  5%)
.............................................................  305 / 4733 (  6%)
.............................................................  366 / 4733 (  7%)
.............................................................  427 / 4733 (  9%)
.............................................................  488 / 4733 ( 10%)
.............................................................  549 / 4733 ( 11%)
.............................................................  610 / 4733 ( 12%)
.............................................................  671 / 4733 ( 14%)
.............................................................  732 / 4733 ( 15%)
................PHP Warning:  include(/var/www/project/symfony/vendor/phpunit/phpunit/src/Framework/Error/Warning.php): failed to open stream: Too many open files in /var/www/project/symfony/vendor/symfony/error-handler/DebugClassLoader.php on line 349
PHP Warning:  include(): Failed opening '/var/www/project/symfony/vendor/composer/../phpunit/phpunit/src/Framework/Error/Warning.php' for inclusion (include_path='.:/usr/share/php:/var/www/project/symfony/vendor/deployer/recipes') in /var/www/project/symfony/vendor/symfony/error-handler/DebugClassLoader.php on line 349
PHP Warning:  include(/var/www/project/symfony/vendor/phpunit/phpunit/src/Framework/Error/Warning.php): failed to open stream: Too many open files in /var/www/project/symfony/vendor/composer/ClassLoader.php on line 571
PHP Warning:  include(): Failed opening '/var/www/project/symfony/vendor/composer/../phpunit/phpunit/src/Framework/Error/Warning.php' for inclusion (include_path='.:/usr/share/php:/var/www/project/symfony/vendor/deployer/recipes') in /var/www/project/symfony/vendor/composer/ClassLoader.php on line 571
Class 'PHPUnit\Framework\Error\Warning' not found
```
The issue is related to `symfony/http-client`, no more issue when reverting these 3 files to v5.3.12 :
- https://github.com/symfony/symfony/blob/v5.3.12/src/Symfony/Component/HttpClient/CurlHttpClient.php
- https://github.com/symfony/symfony/blob/v5.3.12/src/Symfony/Component/HttpClient/Internal/CurlClientState.php
- https://github.com/symfony/symfony/blob/v5.3.12/src/Symfony/Component/HttpClient/Response/CurlResponse.php

I tried to set up a reproducer but it seems the issue occurs only with projects having thousands of tests (4733 tests, 31650 assertions for my project).

### How to reproduce

Upgrade to Symfony 5.3.13 and launch a large PHPUnit test suite with `symfony/http-client` use.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by adrienfr**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no
| Tickets       | Fix #44900
| License       | MIT

With a large PHPUnit tests suite, I receive this error "Failed to open stream: Too many open files".
I found the original code from @nicolas-grekas [here](https://github.com/symfony/symfony/pull/30413/files#diff-bbfff9335ca4f0716566920d7f427036c2d6f9ac2a9cb33e2c83514423ab4b14R77) and with small adjustments, it resolves my issue.

Warning: tests for HttpClient are OK but would someone try with a real HTTP/2 client push? I was not able to test it.

### CODE REVIEW

File: src/Symfony/Component/HttpClient/Internal/CurlClientState.php [hunk 1]
```diff
@@ -65,8 +65,9 @@ public function __construct(int $maxHostConnections, int $maxPendingPushes)
             return;
         }
 
-        curl_multi_setopt($this->handle, \CURLMOPT_PUSHFUNCTION, function ($parent, $pushed, array $requestHeaders) use ($maxPendingPushes) {
-            return $this->handlePush($parent, $pushed, $requestHeaders, $maxPendingPushes);
+        // Keep a dummy "onPush" reference to work around a refcount bug in PHP
+        curl_multi_setopt($this->handle, \CURLMOPT_PUSHFUNCTION, $this->onPush = static function ($parent, $pushed, array $requestHeaders) use ($maxPendingPushes) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/Internal/CurlClientState.php]: the closure and the method cannot be made static, since the method still references `$this`

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpClient/Internal/CurlClientState.php]: oh, please also add a `private $onPush` property

**Comment by adrienfr** [comment]
@nicolas-grekas I think the issue is related to `$this->handle`.
If I keep the `static` way and create this :
```php
$multi = (object) [
      //'handle' => $this->handle,
      //'handle' => &$this->handle,
      'logger' => &$this->logger,
      'pushedResponses' => &$this->pushedResponses,
      'dnsCache' => &$this->dnsCache,
      'handlesActivity' => &$this->handlesActivity,
      'openHandles' => &$this->openHandles,
      'execCounter' => &$this->execCounter,
      'pauseExpiries' => &$this->pauseExpiries,
      'lastTimeout' => &$this->lastTimeout,
  ];

  // Keep a dummy "onPush" reference to work around a refcount bug in PHP
  curl_multi_setopt($this->handle, \CURLMOPT_PUSHFUNCTION, $this->onPush = static function ($parent, $pushed, array $requestHeaders) use ($multi, $maxPendingPushes) {
      return self::handlePush($parent, $pushed, $requestHeaders, $multi, $maxPendingPushes);
  });
```
It works. But I soon as I uncomment one of the `handle` key in my `$multi` object, I have the "failed to open stream: Too many open files" error, as if this `$this->handle` is not properly "reset".

One other thing I noticed, a lot more `CurlMultiHandle` usage in newer version:
- SF 5.3.7 :
CurlHttpClient just before `curl_multi_setopt($this->multi->handle, \CURLMOPT_PUSHFUNCTION, ...`
```php
var_dump($this->multi->handle);
```
=> 
```bash
.  854 / 4775 ( 17%)
resource(15232) of type (curl_multi)
.resource(15342) of type (curl_multi)
.resource(15383) of type (curl_multi)
```
- SF 5.3-dev :
CurlClientState juste before `curl_multi_setopt($this->handle, \CURLMOPT_PUSHFUNCTION, $this->onPush, ...`
```php
var_dump($this->handle);
```
=> 
```bash
.  854 / 4775 ( 17%)
resource(26271) of type (curl_multi)
.resource(26500) of type (curl_multi)
.resource(26569) of type (curl_multi)
```

**Comment by adrienfr** [comment]
@nicolas-grekas might have found a "leak" in `CurlClientState::reset()` this block has been removed in recent PRs:
```php
if (\is_resource($this->handle) || $this->handle instanceof \CurlMultiHandle) {
    if (\defined('CURLMOPT_PUSHFUNCTION')) {
        curl_multi_setopt($this->handle, \CURLMOPT_PUSHFUNCTION, null);
    }

    $active = 0;
    while (\CURLM_CALL_MULTI_PERFORM === curl_multi_exec($this->handle, $active));
}

foreach ($this->openHandles as [$ch]) {
    if (\is_resource($ch) || $ch instanceof \CurlHandle) {
        curl_setopt($ch, \CURLOPT_VERBOSE, false);
    }
}
```
If I add these 2 blocks (especially the one with the `curl_multi_setopt($this->handle, \CURLMOPT_PUSHFUNCTION, null);` call), no more issue. Do you want me to update the PR by re-adding these 2 blocks?

**Comment by adrienfr** [comment]
Regarding this part added in your last PR, I don't really understand the goal but shouldn't we have a call to `curl_share_close()` somewhere? This block also seems responsible for having a lot more open streams than before (5.3.7)
```php
$this->share = curl_share_init();

curl_share_setopt($this->share, \CURLSHOPT_SHARE, \CURL_LOCK_DATA_DNS);
curl_share_setopt($this->share, \CURLSHOPT_SHARE, \CURL_LOCK_DATA_SSL_SESSION);

if (\defined('CURL_LOCK_DATA_CONNECT')) {
    curl_share_setopt($this->share, \CURLSHOPT_SHARE, \CURL_LOCK_DATA_CONNECT);
}
```

**Comment by nicolas-grekas** [comment]
I wish I could reproduce locally. If you can share the code privately with me, you can reach me on Symfony's Slack.

**Comment by nicolas-grekas** [comment]
Can you please try this patch instead?
```diff
--- a/src/Symfony/Component/HttpClient/Internal/CurlClientState.php
+++ b/src/Symfony/Component/HttpClient/Internal/CurlClientState.php
@@ -23,9 +23,9 @@ use Symfony\Component\HttpClient\Response\CurlResponse;
  */
 final class CurlClientState extends ClientState
 {
-    /** @var \CurlMultiHandle|resource */
+    /** @var \CurlMultiHandle|resource|null */
     public $handle;
-    /** @var \CurlShareHandle|resource */
+    /** @var \CurlShareHandle|resource|null */
     public $share;
     /** @var PushedResponse[] */
     public $pushedResponses = [];
@@ -65,8 +65,17 @@ final class CurlClientState extends ClientState
             return;
         }
 
-        curl_multi_setopt($this->handle, \CURLMOPT_PUSHFUNCTION, function ($parent, $pushed, array $requestHeaders) use ($maxPendingPushes) {
-            return $this->handlePush($parent, $pushed, $requestHeaders, $maxPendingPushes);
+        // Clone to prevent a circular reference
+        $multi = clone $this;
+        $multi->handle = null;
+        $multi->share = null;
+        $multi->pushedResponses = &$this->pushedResponses;
+        $multi->logger = &$this->logger;
+        $multi->handlesActivity = &$this->handlesActivity;
+        $multi->openHandles = &$this->openHandles;
+
+        curl_multi_setopt($this->handle, \CURLMOPT_PUSHFUNCTION, static function ($parent, $pushed, array $requestHeaders) use ($multi, $maxPendingPushes) {
+            return $multi->handlePush($parent, $pushed, $requestHeaders, $maxPendingPushes);
         });
     }
```

**Comment by adrienfr** [comment]
Thanks @nicolas-grekas for the patch, it works perfectly, no more issues! 🚀

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @adrienfr.
