### PR TITLE
[DependencyInjection] Add `SubscribedService` attribute, deprecate current `ServiceSubscriberTrait` usage

### LINKED ISSUE #42217: [DependencyInjection] `ServiceSubscriberTrait` does not allow non-service "getter" methods
**Symfony version(s) affected**: 4.2+

**Description**
When using the `ServiceSubscriberTrait`, you cannot have methods with no arguments and a class return type that cannot be created as a service. Memoization of a value object/model is a common use-case that would create this problem.

This issue was brought to my attention by @weaverryan who had this issue in a _real app_.

**How to reproduce**
https://github.com/kbond/subscriber-trait-bug-reproducer is a reproducer. Clone and run `composer install && bin/console lint:container` to see the exception. [This](https://github.com/kbond/subscriber-trait-bug-reproducer/blob/dc8ed379f90739c1029ba729018f7216906817c6/src/ServiceWithSubscriberTrait.php#L23) is the method that causes the problem.

**Possible Solution**
My [initial proposal](https://github.com/symfony/symfony/issues/23898#issuecomment-345007281) for [this feature](https://github.com/symfony/symfony/pull/27077) required users tag methods they want as services with a `@service` docblock tag. This was ultimately rejected but perhaps we could bring this idea back with attributes?

```php
#[SubscribedService]
private function service1(): Service1
{
    return $this->container->get(__METHOD__);
}

#[SubscribedService('custom_name')]
private function service2(): Service2
{
    return $this->container->get('custom_name');
}
```

I'd suggest deprecating the current usage (no attribute) in 5.4 and requiring attributes in 6.0. I don't know how/if this would work with Symfony's BC policy seeing as attributes are PHP8+ and Symfony 5 requires 7.2...

Any other ideas?

### PR DESCRIPTION
**Pull request by kbond**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | yes
| Deprecations? | yes
| Tickets       | Fix #42217
| License       | MIT
| Doc PR        | TODO

This is a fix for #42217 using what I proposed there (adding `SubscribedService` attribute). The current usage is deprecated in 5.4 only when using PHP 8+. I suggest removing the current usage entirely in Symfony 6.0 - this will _fully fix_ the bug.

**Deprecation Layer:**
1. Symfony 5.4 with PHP < 8, everything works as it does currently (no deprecation warnings).
2. Symfony 5.4 with PHP > 8 and using the trait on a class w/o any methods marked with the `SubscribedService` attribute, works as it does currently but a deprecation warning is triggered.
3. Symfony 5.4 with PHP > 8 and using the trait on a class with at least one method marked with the `SubscribedService` attribute, you've opted-into the new functionality (methods w/o the attribute are ignored).

### CODE REVIEW

**Review by weaverryan — COMMENTED** [review]
I like this approach - we have decided not to use `ServiceSubscriberTrait` in our site because, when trying to introduce it, one dev spent a long time trying to figure out a sudden autowiring error (it was because it was trying to wire a model class due to an unrelated method on the service that we did not want to be considered for the locator).

File: src/Symfony/Contracts/Service/ServiceSubscriberTrait.php [hunk 1]
```diff
@@ -42,8 +43,60 @@ public static function getSubscribedServices(): array
...
+                    // todo, what exception to throw?
+                    throw new \RuntimeException(sprintf('Cannot use "%s" on methods with a union return type in "%s::%s()".', SubscribedService::class, $method->name, self::class));
+                }
+
+                if ($returnType->isBuiltin()) {
+                    // todo, what exception to throw?
+                    throw new \RuntimeException(sprintf('Cannot use "%s" on methods with a native return type in "%s::%s()".', SubscribedService::class, $method->name, self::class));
+                }
+
+                $services[$attribute->newInstance()->key ?? self::class.'::'.$method->name] = '?'.$returnType->getName();
```
Comment (stof) [inline src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: do we actually need to assign this here in a separate loop ? couldn't we do it in the previous loop already ?

File: src/Symfony/Contracts/Service/ServiceSubscriberTrait.php [hunk 2]
```diff
@@ -42,8 +43,60 @@ public static function getSubscribedServices(): array
...
+                }
+
+                if (!$returnType = $method->getReturnType()) {
+                    // todo, what exception to throw?
+                    throw new \RuntimeException(sprintf('Cannot use "%s" on methods without a return type in "%s::%s()".', SubscribedService::class, $method->name, self::class));
+                }
+
+                if (!$returnType instanceof \ReflectionNamedType) {
+                    // todo, what exception to throw?
+                    throw new \RuntimeException(sprintf('Cannot use "%s" on methods with a union return type in "%s::%s()".', SubscribedService::class, $method->name, self::class));
```
Comment (stof) [inline src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: Why ? the previous loop does not have this restriction.

**Comment by stof** [comment]
To make the trait usable in 5.4 without WTF, we would need a way to opt-in for the new behavior (here, there is nothing that will stop registering other private methods, with no way to avoid the deprecation warning if they are not meant to be subscribed)

File: src/Symfony/Contracts/Service/ServiceSubscriberTrait.php (hunk 1 above)
Comment (kbond) [reply src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: I did this only for readability (for myself anyways). First loop = old, Second loop = new. My plan was to kill the first loop entirely in 6.0. I can adjust if desired.

File: src/Symfony/Contracts/Service/ServiceSubscriberTrait.php (hunk 2 above)
Comment (kbond) [reply src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: I treated this as a bug. If the return type is `Service1|Service2`, what should be used for the service locator?

**Comment by nicolas-grekas** [comment]
What about deprecating the trait instead?

**Comment by kbond** [comment]
> To make the trait usable in 5.4 without WTF, we would need a way to opt-in for the new behavior

What about, if using the attribute on any method, you've opted into the new way and methods without the attribute are ignored?

**Comment by kbond** [comment]
> What about deprecating the trait instead?

And creating a new trait entirely? Suggestions on a new name? `SubscribedServiceTrait`?

**Comment by stof** [comment]
Well, providing an easy implemention of the `getSubscribedServices` method to provide better DX might make sense.
but maybe it should be a new trait entirely instead (and deprecating the existing one)

**Comment by nicolas-grekas** [comment]
I was considering deprecating the trait and not replacing it, but if you think we should keep it, no need to create a new one if we can make a nice deprecation layer.

**Comment by kbond** [comment]
> I was considering deprecating the trait and not replacing it, but if you think we should keep it...

I personally like this feature so I think we should keep it but I understand it's a bit... controversial (and could be easily abused).

If you're ok keeping it, I'll add the nice deprecation layer and finish this PR. Alternatively, if you want to deprecate/remove, I can easily maintain this feature in a 3rd party package.

**Comment by nicolas-grekas** [comment]
I'm fine keeping it now that we have it.

**Comment by kbond** [comment]
I've updated/added tests and improved the deprecation layer:

1. Symfony 5.4 with PHP < 8, everything works as it does currently (no deprecation warnings).
2. Symfony 5.4 with PHP > 8 and using the trait on a class w/o any methods marked with the `SubscribedService` attribute, works as it does currently but a deprecation warning is triggered.
2. Symfony 5.4 with PHP > 8 and using the trait on a class with at least one method marked with the `SubscribedService` attribute, you've opted-into the new functionality (methods w/o the attribute are ignored).

**Comment by kbond** [comment]
I could use some direction on fixing the remaining CI errors.

File: src/Symfony/Contracts/Service/ServiceSubscriberTrait.php [hunk 3]
```diff
@@ -36,13 +37,65 @@ public static function getSubscribedServices(): array
...
+                if (!$returnType = $method->getReturnType()) {
+                    continue;
+                }
+
+                if ($returnType->isBuiltin()) {
+                    continue;
+                }
+
+                if (\PHP_VERSION_ID >= 80000) {
+                    trigger_deprecation('symfony/service-contracts', '5.4', 'Using the "%s" trait in "%s" without subscribed service methods marked with the "%s" attribute is deprecated and will not be allowed in Symfony 6.0.', ServiceSubscriberTrait::class, self::class, SubscribedService::class);
```
Comment (OskarStark) [inline src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: Is `5.4` correct here, as the contracts does not follow the Symfony version numbers.
Current stable one is `2.4.0`

Comment (kbond) [reply src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: Good point, what exactly triggers a new major contracts version? Will 3.0 be released with Symfony 6?

Comment (nicolas-grekas) [reply src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: Yes, contracts 3.0 will be released with Symfony 6.0

**Comment by kbond** [comment]
Assuming this is still wanted for 5.4, once merged, I'll work on a PR to drop the deprecation layer in 6.0.

Still need a bit of direction for fixing the tests. I believe it's a dependency issue, `symfony/dependency-injection` is requiring the wrong version of `symfony/service-contracts`.

File: src/Symfony/Contracts/Service/ServiceSubscriberTrait.php [hunk 4]
```diff
@@ -36,13 +37,65 @@ public static function getSubscribedServices(): array
...
+                if (self::class !== $method->getDeclaringClass()->name) {
+                    continue;
+                }
+
+                if (!$attribute = $method->getAttributes(SubscribedService::class)[0] ?? null) {
+                    continue;
+                }
+
+                if ($method->isStatic() || $method->isAbstract() || $method->isGenerator() || $method->isInternal() || $method->getNumberOfRequiredParameters()) {
+                    // todo, what exception to throw?
```
Comment (nicolas-grekas) [inline src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: LogicException is correct

File: src/Symfony/Contracts/Service/ServiceSubscriberTrait.php [hunk 5]
```diff
@@ -36,13 +37,65 @@ public static function getSubscribedServices(): array
...
+                    throw new \LogicException(sprintf('Cannot use "%s" on method "%s::%s()" (can only be used on non-static, non-abstract methods with no parameters).', SubscribedService::class, self::class, $method->name));
+                }
+
+                if (!$returnType = $method->getReturnType()) {
+                    // todo, what exception to throw?
+                    throw new \LogicException(sprintf('Cannot use "%s" on methods without a return type in "%s::%s()".', SubscribedService::class, $method->name, self::class));
+                }
+
+                if (!$returnType instanceof \ReflectionNamedType) {
```
Comment (nicolas-grekas) [inline src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: can be removed, esp since we now support autowiring unions+intersections

File: src/Symfony/Contracts/Service/ServiceSubscriberTrait.php [hunk 6]
```diff
@@ -36,13 +37,65 @@ public static function getSubscribedServices(): array
...
+                    // todo, what exception to throw?
+                    throw new \LogicException(sprintf('Cannot use "%s" on methods with a union return type in "%s::%s()".', SubscribedService::class, $method->name, self::class));
+                }
+
+                if ($returnType->isBuiltin()) {
```
Comment (nicolas-grekas) [inline src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: let's remove also, another part will fail if not supported

File: src/Symfony/Contracts/Service/ServiceSubscriberTrait.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: the best cs here would be the one that reduces merge conflicts. Eg if we can prevent changing indentation, that's best

**Review by nicolas-grekas — COMMENTED** [review]
ideally tests on DI should work on all versions of contracts, or be skipped on non-supported ones

File: src/Symfony/Contracts/Service/Attribute/SubscribedService.php [hunk 7]
```diff
@@ -0,0 +1,35 @@
...
+#[\Attribute(\Attribute::TARGET_METHOD)]
+final class SubscribedService
+{
+    public ?string $key;
+
+    /**
+     * @param string|null $key The key to use for the service
+     *                         If null, use "ClassName::methodName"
+     */
+    public function __construct(string $key = null)
```
Comment (nicolas-grekas) [inline src/Symfony/Contracts/Service/Attribute/SubscribedService.php]: let's use property promotion

**Comment by kbond** [comment]
I believe all related tests are now passing. I fixed some pslam issues but don't understand the remaining ones.

File: src/Symfony/Contracts/Service/Attribute/SubscribedService.php [hunk 8]
```diff
@@ -0,0 +1,34 @@
...
+final class SubscribedService
+{
+    /**
+     * @param string|null $key The key to use for the service
+     *                         If null, use "ClassName::methodName"
+     */
+    public function __construct(
+        public ?string $key = null
+    ) {
+        $this->key = $key;
```
Comment (nicolas-grekas) [inline src/Symfony/Contracts/Service/Attribute/SubscribedService.php]: can be removed

File: src/Symfony/Contracts/Service/ServiceSubscriberTrait.php [hunk 9]
```diff
@@ -36,13 +37,53 @@ public static function getSubscribedServices(): array
...
+
+                if ($method->isStatic() || $method->isAbstract() || $method->isGenerator() || $method->isInternal() || $method->getNumberOfRequiredParameters()) {
+                    throw new \LogicException(sprintf('Cannot use "%s" on method "%s::%s()" (can only be used on non-static, non-abstract methods with no parameters).', SubscribedService::class, self::class, $method->name));
+                }
+
+                if (!$returnType = $method->getReturnType()) {
+                    throw new \LogicException(sprintf('Cannot use "%s" on methods without a return type in "%s::%s()".', SubscribedService::class, $method->name, self::class));
+                }
+
+                $services[$attribute->newInstance()->key ?? self::class.'::'.$method->name] = '?'.$returnType->getName();
```
Comment (nicolas-grekas) [inline src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: this should likely do `$returnType instanceof \ReflectionNamedType ? ->getName() : (string)` for the last part.

also, when the attribute is used, I'm not sure about the `?` prefix. Shouldn't we add it only when the type is nullable? (and remove `|null` from the string representation of the union)

File: src/Symfony/Contracts/Service/ServiceSubscriberTrait.php [hunk 10]
```diff
@@ -36,13 +37,53 @@ public static function getSubscribedServices(): array
...
+                if (!$returnType = $method->getReturnType()) {
+                    continue;
+                }
+
+                if ($returnType->isBuiltin()) {
+                    continue;
+                }
+
+                if (\PHP_VERSION_ID >= 80000) {
+                    trigger_deprecation('symfony/service-contracts', '2.5', 'Using the "%s" trait in "%s" without subscribed service methods marked with the "%s" attribute is deprecated and will not be allowed in 3.0.', ServiceSubscriberTrait::class, self::class, SubscribedService::class);
```
Comment (nicolas-grekas) [inline src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: `Using "%s" in "%s" without using the "%s" attribute on any method is deprecated.`

**Review by nicolas-grekas — COMMENTED** [review]
one last non-trivial note :)

File: src/Symfony/Contracts/Service/ServiceSubscriberTrait.php (hunk 9 above)
Comment (kbond) [reply src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: > this should likely do $returnType instanceof \ReflectionNamedType ? ->getName() : (string) for the last part.

Like this?

```php
$services[$attribute->newInstance()->key ?? self::class.'::'.$method->name] = '?'.($returnType instanceof \ReflectionNamedType ? $returnType->getName() : $returnType);
```

I just realized `ReflectionType::__toString` is [deprecated](https://www.php.net/manual/en/reflectiontype.tostring.php).. Should we be relying on this?

> also, when the attribute is used, I'm not sure about the ? prefix. Shouldn't we add it only when the type is nullable? (and remove |null from the string representation of the union)

Good call, I'll make this change. Should I leave the BC layer as is?

File: src/Symfony/Contracts/Service/ServiceSubscriberTrait.php (hunk 2 above)
Comment (derrabus) [reply src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: @kbond Does #43479 help to answer that question?

Comment (kbond) [reply src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: Yes :). Is there an example of using union/intersection types with `ServiceSubscriberInterface`?

Comment (derrabus) [reply src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: The example from the PR was an intersection of two serializer interfaces that would yield the `serializer` service, e.g. `NormalizerInterface&DenormalizerInterface`, so let's explore that:

```php
class MyService implements ServiceSubscriberInterface
{
    use ServiceSubscriberTrait;

    private function getSerializer(): NormalizerInterface&DenormalizerInterface
    {
        return $this->container->get(__METHOD__);
    }
}
```

Comment (kbond) [reply src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: Yep, I'll try to make that work. I'm looking for what the array returned from `ServiceSubscriberInterface::getSubscribedServices()` looks like when using union/intersection.

Comment (derrabus) [reply src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: I see. We need to come up with a new convention for that, I guess.

File: src/Symfony/Contracts/Service/ServiceSubscriberTrait.php (hunk 9 above)
Comment (kbond) [reply src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: I've made these changes (let me know if you'd like me to backport this to the BC layer).

I'm not sure how to handle union/intersection types. See https://github.com/symfony/symfony/pull/42238#discussion_r732978902.

File: src/Symfony/Contracts/Service/ServiceSubscriberTrait.php [hunk 11]
```diff
@@ -36,13 +37,59 @@ public static function getSubscribedServices(): array
...
+
+                if ($method->isStatic() || $method->isAbstract() || $method->isGenerator() || $method->isInternal() || $method->getNumberOfRequiredParameters()) {
+                    throw new \LogicException(sprintf('Cannot use "%s" on method "%s::%s()" (can only be used on non-static, non-abstract methods with no parameters).', SubscribedService::class, self::class, $method->name));
+                }
+
+                if (!$returnType = $method->getReturnType()) {
+                    throw new \LogicException(sprintf('Cannot use "%s" on methods without a return type in "%s::%s()".', SubscribedService::class, $method->name, self::class));
+                }
+
+                $serviceId = $returnType instanceof \ReflectionNamedType ? $returnType->getName() : $returnType;
```
Comment (nicolas-grekas) [inline src/Symfony/Contracts/Service/ServiceSubscriberTrait.php]: missing cast to string: `(string) $returnType`

File: src/Symfony/Contracts/Service/ServiceSubscriberTrait.php [hunk 12]
```diff
@@ -36,13 +37,59 @@ public static function getSubscribedServices(): array
...
+                if (!$returnType = $method->getReturnType()) {
+                    continue;
+                }
+
+                if ($returnType->isBuiltin()) {
+                    continue;
+                }
+
+                if (\PHP_VERSION_ID >= 80000) {
+                    trigger_deprecation('symfony/service-contracts', '2.5', 'Using "%s" in "%s" without using the "%s" attribute on any method is deprecated.', ServiceSubscriberTrait::class, self::class, SubscribedService::class);
```
Comment (nicolas-grekas) [inline src/Symfony/Contracts/Service/ServiceSubscriberTrait.php:90]: composer.json needs to require the related contracts

**Review by nicolas-grekas — APPROVED** [review]
(with minor comments)

File: src/Symfony/Contracts/Service/ServiceSubscriberTrait.php (hunk 12 above)
Comment (kbond) [reply src/Symfony/Contracts/Service/ServiceSubscriberTrait.php:90]: Sorry, can you elaborate? Which composer.json?

Comment (nicolas-grekas) [reply src/Symfony/Contracts/Service/ServiceSubscriberTrait.php:90]: symfony/deprecation-contracts, which defines trigger_deprecation()

Comment (kbond) [reply src/Symfony/Contracts/Service/ServiceSubscriberTrait.php:90]: Of course. Done.

**Comment by nicolas-grekas** [comment]
Thank you @kbond.

**Comment by kbond** [comment]
Great, once this makes its way into the 6.0 branch, I'll remove the deprecation layer.

**Comment by nicolas-grekas** [comment]
now merged up to 6.0
