### PR TITLE
[Mime] Use shell_exec() instead of passthru() in FileBinaryMimeTypeGuesser

### LINKED ISSUE #63459: FileBinaryMimeTypeGuesser requires passthru() even when proc_open() and file are available
### Symfony version(s) affected

7.4.5 (symfony/mime)

### Description

`FileBinaryMimeTypeGuesser` is considered "not supported" when `passthru()` is disabled via `disable_functions`, even if:

- `/usr/bin/file` is installed and accessible
- `proc_open()` is available
- `exec()` and `shell_exec()` are available
- `open_basedir` is not restricted
- `ext-fileinfo` is enabled

In this scenario, calling `guessMimeType()` throws:

> The "Symfony\Component\Mime\FileBinaryMimeTypeGuesser" guesser is not supported.

This happens in shared hosting environments where `passthru()` is commonly disabled for security reasons, while other process-related functions remain available.

From a system capability perspective, the `file` binary can still be executed (via `proc_open()` / Symfony Process), yet the guesser refuses to operate because `passthru()` is unavailable.

### Expected behavior

If `proc_open()` and the `file` binary are available, the guesser could still be considered supported.

Alternatively, the component could:

- fallback to a `Process`-based execution,
- relax the strict `passthru()` requirement,
- or document explicitly that `passthru()` is a hard requirement.

### Why this matters

Many hosting providers disable `passthru()` while keeping `proc_open()` enabled.

In such environments:

- The system `file` binary works
- Symfony Process works
- MIME detection via `FileBinaryMimeTypeGuesser` fails

This creates unexpected failures in real-world deployments even though the system is technically capable of running the required command.

### Environment

PHP 8.2 (FPM)

disable_functions=mail,passthru,system

System configuration:

- `/usr/bin/file` exists and is executable
- `proc_open()` returns true
- `exec()` returns true
- `shell_exec()` returns true
- `ext-fileinfo` is enabled
- `open_basedir` is not restricted

### Reproducer

```php
use Symfony\Component\Mime\FileBinaryMimeTypeGuesser;

require __DIR__.'/vendor/autoload.php';

$guesser = new FileBinaryMimeTypeGuesser();

var_dump(function_exists('proc_open'));   // true
var_dump(function_exists('passthru'));    // false
var_dump($guesser->isGuesserSupported()); // false

$guesser->guessMimeType(__FILE__);
```

Result

The following exception is thrown:

The "Symfony\Component\Mime\FileBinaryMimeTypeGuesser" guesser is not supported.

Even though:

/usr/bin/file works

proc_open() works

Symfony Process works

The guesser is considered unsupported solely because passthru() is disabled.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63459
| License       | MIT

Using `passthru()` is needlessly convoluted and creates portability issues.
The rest of the code uses shell_exec/exec/proc_open, that's the only place where we use passthru.

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

File: src/Symfony/Component/Mime/FileBinaryMimeTypeGuesser.php [hunk 1]
```diff
@@ -65,17 +61,9 @@ public function guessMimeType(string $path): ?string
...
         // need to use --mime instead of -i. see #6641
-        passthru(\sprintf($this->cmd, escapeshellarg((str_starts_with($path, '-') ? './' : '').$path)), $return);
-        if ($return > 0) {
-            ob_end_clean();
-
-            return null;
-        }
-
-        $type = trim(ob_get_clean());
+        $type = \sprintf($this->cmd, escapeshellarg((str_starts_with($path, '-') ? './' : '').$path));
```
Comment (stof) [inline src/Symfony/Component/Mime/FileBinaryMimeTypeGuesser.php]: This variable should be named `$command`, not `$type`. It is not the type at all.

Comment (nicolas-grekas) [reply src/Symfony/Component/Mime/FileBinaryMimeTypeGuesser.php]: well, it's just a tmp state to split a long line

Comment (stof) [reply src/Symfony/Component/Mime/FileBinaryMimeTypeGuesser.php]: yeah, but naming those state is important for the future maintainer reading that code again and having to understand it. Naming a variant `$type` when it is *not* the type makes the code less readable.

Comment (nicolas-grekas) [reply src/Symfony/Component/Mime/FileBinaryMimeTypeGuesser.php]: alright, I merged both lines
