### PR TITLE
[Security] Add a method in the security helper to ease programmatic logout

### LINKED ISSUE #40663: [Security][DX] RFC: A simple way to do programmatic logout
**Description**
There are various reasons why an app may need to logout a user without the user having to be redirected to the logout page, and currently there is no easy way to do this without copying some code from core which is subject to change and thus may leave one with outdated logic.

**Example**
Related to #40662, IMO a great API to have would be [`Security`](https://github.com/symfony/symfony/blob/f963ae476a6534b29b638f47d19dc076a0afebd5/src/Symfony/Component/Security/Core/Security.php)`::programmaticLogout(Request $request)`

This would figure out which firewall is relevant for the given $request, and trigger a logout event on that firewall's event dispatcher.

**Why?**
By digging through internals, it appears the best way to do this is the following:

```php
        $logoutEvent = new LogoutEvent($request, $this->tokenStorage->getToken());
        $this->eventDispatcher->dispatch($logoutEvent);

        $response = $logoutEvent->getResponse();
        if (!$response instanceof Response) {
            throw new \RuntimeException('No logout listener set the Response, make sure at least the DefaultLogoutListener is registered.');
        }

        $this->tokenStorage->setToken(null);

        return $response;
```

This is copied from https://github.com/symfony/symfony/blob/f963ae476a6534b29b638f47d19dc076a0afebd5/src/Symfony/Component/Security/Http/Firewall/LogoutListener.php#L121-L131 I did not invent anything, but I had to find out, and now I have to copy paste this in my app to be able to call it.

On top of that, some added complexity one has to figure out is that the event dispatcher here isn't just any event dispatcher, but you have to inject the correct event dispatcher for the firewall you want to do the logout on, and so you have to define that in the service yourself.. Firewall-specific event dispatchers are mentioned in passing in the docs but it's not exactly a common concept so this is all overall not great DX, and having an easy and more visible place to do this would be nice I think.

### PR DESCRIPTION
**Pull request by johnkrovitch**
| Q             | A
| ------------- | ---
| Branch?       | 6.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #40663
| License       | MIT
| Doc PR        | 

This PR aims to ease the programmatic login using the Security helper, to fix (#40663).

A simple method has been added to the Security helper. 

Thanks !

### CODE REVIEW

File: src/Symfony/Component/Security/Core/Tests/SecurityTest.php [hunk 1]
```diff
@@ -85,6 +89,52 @@ public function testIsGranted()
...
+            ->method('get')
+            ->willReturnMap([
+                ['request_stack', $requestStack],
+                ['security.token_storage', $tokenStorage],
+                ['event_dispatcher', $eventDispatcher],
+            ])
+        ;
+
+
+
```
Comment (Kocal) [inline src/Symfony/Component/Security/Core/Tests/SecurityTest.php]:
```suggestion

```

Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Tests/SecurityTest.php]: Fixed

File: src/Symfony/Component/Security/Core/Security.php [hunk 2]
```diff
@@ -69,4 +70,15 @@ public function getToken(): ?TokenInterface
...
     }
+
+    /**
+     * Logout the current user automatically. Dispatch the logout event.
+     */
+    public function autoLogout(): void
+    {
+        $request = $this->container->get('request_stack')->getCurrentRequest();
+        $logoutEvent = new LogoutEvent($request, $this->container->get('security.token_storage')->getToken());
+        $this->container->get('event_dispatcher')->dispatch($logoutEvent);
```
Comment (Seldaek) [inline src/Symfony/Component/Security/Core/Security.php]: As the regular logout listeners are expected to return a response as in: https://github.com/symfony/symfony/blob/f963ae476a6534b29b638f47d19dc076a0afebd5/src/Symfony/Component/Security/Http/Firewall/LogoutListener.php#L121-L131

I wonder if it wouldn't be better to have this helper function also return the event's response? That way the caller can simply return that as response and be sure that the user is sent to the correct address without having to duplicate any URL/logic.

File: src/Symfony/Bundle/SecurityBundle/Resources/config/security.php [hunk 3]
```diff
@@ -90,6 +90,8 @@
             ->args([service_locator([
                 'security.token_storage' => service('security.token_storage'),
                 'security.authorization_checker' => service('security.authorization_checker'),
+                'request_stack' => service('request_stack'),
+                'event_dispatcher' => service('event_dispatcher'),
```
Comment (Seldaek) [inline src/Symfony/Bundle/SecurityBundle/Resources/config/security.php]: As far as I know the event dispatcher of the firewall responsible for the current request has to be used, not just the default event dispatcher. Otherwise logout listeners for the wrong firewalls may be triggered.

I am not entirely sure how this can be done at runtime though, probably all security event dispatchers would have to be wired in here.

File: src/Symfony/Component/Security/Core/Security.php [hunk 4]
```diff
@@ -69,4 +70,15 @@ public function getToken(): ?TokenInterface
     {
         return $this->container->get('security.token_storage')->getToken();
     }
+
+    /**
+     * Logout the current user automatically. Dispatch the logout event.
+     */
+    public function autoLogout(): void
```
Comment (Seldaek) [inline src/Symfony/Component/Security/Core/Security.php]: I'm not sure if `auto` is the best wording here, I suggested programmaticLogout in #40663 so I am biased perhaps, but it sounds to me like this isn't automatic if one has to call it :)

Not sure what other options there may be that make this clear enough to everyone.

**Review by Seldaek — COMMENTED** [review]
Thanks for working on this! There are a few points which IMO need some work still

File: src/Symfony/Bundle/SecurityBundle/Resources/config/security.php (hunk 3 above)
Comment (wouterj) [reply src/Symfony/Bundle/SecurityBundle/Resources/config/security.php]: Yes, the firewall's event dispatcher has to be used indeed.

For this to work, we need to create a lazy map of `firewall name => firewall event dispatcher` in the `SecurityExtension`. Possibly, we have to add this map to `Symfony\Bundle\SecurityBundle\Security\FirewallMap` and use the firewall map in the helper function to get the correct event dispatcher.

File: src/Symfony/Component/Security/Core/Security.php (hunk 4 above)
Comment (wouterj) [reply src/Symfony/Component/Security/Core/Security.php]: What about just `logout()`?

**Comment by johnkrovitch** [comment]
Thanks for your returns, I'm working on it.

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 5]
```diff
@@ -297,6 +297,17 @@ private function createFirewalls(array $config, ContainerBuilder $container)
...
+            // add authentication providers to authentication manager
+            $authenticationProviders = array_map(function ($id) {
+                return new Reference($id);
+            }, array_values(array_unique($authenticationProviders)));
+
+            $container
+                ->getDefinition('security.authentication.manager')
+                ->replaceArgument(0, new IteratorArgument($authenticationProviders));
+        }
+
```
Comment (wouterj) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]:
```suggestion
```

Since Symfony 6.0, we only have the authenticator manager

File: src/Symfony/Component/Security/Core/Security.php [hunk 6]
```diff
@@ -57,4 +58,23 @@ public function getToken(): ?TokenInterface
     {
         return $this->container->get('security.token_storage')->getToken();
     }
+
+    /**
+     * Logout the current user automatically. Dispatch the logout event.
+     */
+    public function logout(): void
+    {
+        $request = $this->container->get('request_stack')->getCurrentRequest();
```
Comment (wouterj) [inline src/Symfony/Component/Security/Core/Security.php]:
```suggestion
        $request = $this->container->get('request_stack')->getMainRequest();
```

I believe we always want to logout from the main request, and not the sub-requests.

File: src/Symfony/Component/Security/Core/Security.php [hunk 7]
```diff
@@ -57,4 +58,23 @@ public function getToken(): ?TokenInterface
...
+        $logoutEvent = new LogoutEvent($request, $this->container->get('security.token_storage')->getToken());
+
+        $firewallName = $this
+            ->container
+            ->get('security.firewall.map')
+            ->getFirewallConfig($request)
+            ->getName()
+        ;
```
Comment (wouterj) [inline src/Symfony/Component/Security/Core/Security.php]: Please use a single line for these chained methods (we generally don't wrap long lines in Symfony).

Also, I think `getFirewallConfig()` may return `null`. We should check it before calling `getName()`.

File: src/Symfony/Component/Security/Core/Security.php [hunk 8]
```diff
@@ -57,4 +58,23 @@ public function getToken(): ?TokenInterface
...
+
+        $this->container->get('security.firewall.event_dispatcher_map')->getEventDispatcher($firewallName)->dispatch($logoutEvent);
+        $this->container->get('security.token_storage')->setToken();
```
Comment (wouterj) [inline src/Symfony/Component/Security/Core/Security.php]: As [suggested by Jordi](https://github.com/symfony/symfony/pull/41406#discussion_r741705363), I would prefer if we change this method's return type to `?Response` and return `$logoutEvent->getResponse()`.

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 9]
```diff
@@ -353,6 +353,12 @@ private function createFirewall(ContainerBuilder $container, string $id, array $
         $container->register($firewallEventDispatcherId, EventDispatcher::class)
             ->addTag('event_dispatcher.dispatcher', ['name' => $firewallEventDispatcherId]);
 
+        $container
+            ->getDefinition('security.firewall.event_dispatcher_map')
+            ->setLazy(true)
+            ->addMethodCall('addEventDispatcher', [$id, new Reference($firewallEventDispatcherId)])
+        ;
```
Comment (wouterj) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]: This gets a bit tricky, but I would prefer if we used the [`ServiceLocator`](Symfony\Component\DependencyInjection\ServiceLocator) here instead of a lazy definition (which only works if a third party library is installed IIRC). We can then also remove the `FirewallEventDispatcherMapInterface` and `FirewallEventDispatcherMap` classes.

We use this strategy also for the `security.authenticator.managers_locator` service. Relevant code snippets are: https://github.com/symfony/symfony/blob/8bdbd3473ae3d51384a20cc3781971a833a4a5d1/src/Symfony/Bundle/SecurityBundle/Resources/config/security_authenticator.php#L50-L51 https://github.com/symfony/symfony/blob/8bdbd3473ae3d51384a20cc3781971a833a4a5d1/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L453-L454

**Review by wouterj — COMMENTED** [review]
Hi there! Thanks for updating this PR :)

I've left some final improvements. Some of them a bit tricky, so feel free to leave a comment asking for help if you don't understand how to apply them :)

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php (hunk 5 above)
Comment (johnkrovitch) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]: Thanks for your quick response :D It is fixed, sorry the false positive, it was a rebasing error.

File: src/Symfony/Component/Security/Core/Security.php (hunk 7 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Security.php]: Ok thanks. What do we do if `getFirewallConfig()` returns null ? Exit the method and so doing nothing, or throw an exception ?

Comment (wouterj) [reply src/Symfony/Component/Security/Core/Security.php]: If null is returned, the request is not behind a firewall as far as I can see. So I would say it makes sense to throw an exception like "It is not possible to logout, as the request is not behind a firewall."

File: src/Symfony/Component/Security/Core/Security.php (hunk 6 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Security.php]: Thanks, fixed.

File: src/Symfony/Component/Security/Core/Security.php (hunk 8 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Security.php]: Thanks, fixed.

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php (hunk 9 above)
Comment (johnkrovitch) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]: Thanks, fixed.

File: src/Symfony/Component/Security/Core/Security.php (hunk 2 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Security.php]: Thanks, it is fixed.

File: src/Symfony/Component/Security/Core/Security.php (hunk 7 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Security.php]: Fixed

File: src/Symfony/Component/Security/Core/Security.php (hunk 4 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Security.php]: Method name change to `logout()`.

File: src/Symfony/Bundle/SecurityBundle/Resources/config/security.php (hunk 3 above)
Comment (johnkrovitch) [reply src/Symfony/Bundle/SecurityBundle/Resources/config/security.php]: A service locator has been used. Thanks

File: src/Symfony/Component/Security/Core/Security.php [hunk 10]
```diff
@@ -57,4 +60,25 @@ public function getToken(): ?TokenInterface
     {
         return $this->container->get('security.token_storage')->getToken();
     }
+
+    /**
+     * Logout the current user automatically. Dispatch the logout event.
```
Comment (chalasr) [inline src/Symfony/Component/Security/Core/Security.php]:
```suggestion
     * Logouts the current user automatically. Dispatch the logout event.
```

**Review by chalasr — CHANGES_REQUESTED** [review]
Nice. ~One minor comment~. Also The Security Core's CHANGELOG file should be updated to mention this feature.

File: src/Symfony/Component/Security/Core/Security.php (hunk 10 above)
Comment (GwendolenLynch) [reply src/Symfony/Component/Security/Core/Security.php]: "Logout" is the correct English

**Comment by johnkrovitch** [comment]
The right security change log has been updated.

File: src/Symfony/Component/Security/Core/Security.php (hunk 10 above)
Comment (chalasr) [inline src/Symfony/Component/Security/Core/Security.php]:
```suggestion
     * Logout the current user by dispatching the LogoutEvent.
     *
     * @return Response|null The LogoutEvent's Response if any
```

File: src/Symfony/Component/Security/Core/Security.php [hunk 11]
```diff
@@ -57,4 +60,25 @@ public function getToken(): ?TokenInterface
...
+     */
+    public function logout(): ?Response
+    {
+        $request = $this->container->get('request_stack')->getMainRequest();
+        $logoutEvent = new LogoutEvent($request, $this->container->get('security.token_storage')->getToken());
+
+        $firewallConfig = $this->container->get('security.firewall.map')->getFirewallConfig($request);
+
+        if (null === $firewallConfig) {
```
Comment (chalasr) [inline src/Symfony/Component/Security/Core/Security.php]:
```suggestion
        if (!$firewallConfig) {
```

File: src/Symfony/Component/Security/Core/Security.php [hunk 12]
```diff
@@ -57,4 +60,25 @@ public function getToken(): ?TokenInterface
...
         return $this->container->get('security.token_storage')->getToken();
     }
+
+    /**
+     * Logout the current user automatically. Dispatch the logout event.
+     */
+    public function logout(): ?Response
+    {
+        $request = $this->container->get('request_stack')->getMainRequest();
+        $logoutEvent = new LogoutEvent($request, $this->container->get('security.token_storage')->getToken());
```
Comment (chalasr) [inline src/Symfony/Component/Security/Core/Security.php]: We need a guard condition that checks if the LogoutEvent exists and throw an exception otherwise, because Security\Core does not depend on Security\Http. 
Btw we need to add `"symfony/security-http": "^5.4|^6.0"` as a dev requirement in security-core's composer.json in order to make tests pass.

**Review by chalasr — COMMENTED** [review]
Almost good.

File: src/Symfony/Component/Security/Core/Security.php (hunk 12 above)
Comment (chalasr) [reply src/Symfony/Component/Security/Core/Security.php]:
```php
throw new \LogicException('Security HTTP is missing. Try running "composer require symfony/security-http".');
```

File: src/Symfony/Component/Security/Core/Security.php (hunk 10 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Security.php]: Thanks for your return. Changes done

File: src/Symfony/Component/Security/Core/Security.php (hunk 12 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Security.php]: Done

File: src/Symfony/Component/Security/Core/Security.php (hunk 11 above)
Comment (johnkrovitch) [reply src/Symfony/Component/Security/Core/Security.php]: Done

**Comment by wouterj** [comment]
To know why this PR is not merged yet (and potentially help with fixing my concerns), see https://github.com/symfony/symfony/pull/41274#issuecomment-1046967394

On top of the 2 points mentioned there, this PR forgot the logout CSRF protection. This is a great example of why these PRs add 2 great features: it's very easy to forget logout CSRF. By having a bulletproof programmatic logout, all applications get safer :)

**Comment by fabpot** [comment]
@johnkrovitch Can you update this PR now that the other one has been merged? cc @chalasr

**Comment by chalasr** [comment]
Something to clarify before we can move forward:

>  this PR forgot the logout CSRF protection

@wouterj Can you please elaborate? The method dispatches the LogoutEvent whose both `RememberMeListener` and `CsrfTokenClearingLogoutListener` are listening on. Is there something else missing?

**Comment by stof** [comment]
The logout feature can be protected with CSRF, forcing to have a valid CSRF token to log out.

**Comment by chalasr** [comment]
Got it, thanks

**Comment by chalasr** [comment]
CSRF validation added. 
If CSRF protection is enabled and logout is configured on the firewall for which `logout()` is called, then the method checks that the logout csrf token is there and valid. 
Otherwise, in case `logout()` is called for a firewall that don't have `logout` configured, the responsibility of validating a CSRF token is left up to the developer.

Reviews welcome.

**Comment by Seldaek** [comment]
I wonder if there should be a way to bypass CSRF? One of the use cases where I've needed programmatic logout is when handling user invitations.. There if you click the invite email and you are already logged in we show "accept invite" or "create new account". If you click that we log you out and send you back to the invite page which then shows a registration form.

In this case, we authenticate the request has the token from the email anyway, and we absolutely do not need a CSRF token.. Of course we could add one on the "create new account" button I guess if needed, just doesn't seem necessary.

**Comment by chalasr** [comment]
I think most use cases for this method are in similar situations. I'll think of a way to bypass it, will probably end up with a bool parameter. Thanks!

**Comment by Seldaek** [comment]
@chalasr thanks, LGTM now I think - haven't reviewed the whole code in depth though, but on the surface the API makes sense to me.

**Comment by wouterj** [comment]
I'm not 100% sure, but I'm leaning towards *not* allowing to bypass CSRF. If an application enabled logout CSRF as a way to prevent login csrf, I would expect all ways of logging out to be protected by CSRF. With this boolean, I no longer can be sure.

Of course, @Seldaek understands login CSRF and knows that CSRF would only be "added noise" in this specific scenario, but I think the framework has a duty to protect those unaware of login CSRF to be as safe as possible.

**Comment by chalasr** [comment]
CSRF protection is pointless if logout happens on a GET request, or as a side effect of a state change of another resource which might itself already be CSRF protected using a different token, or Jordi's use case. 
I strongly think such cases are the ones for which this method makes the most sense instead of requesting a regular logout endpoint, I would find it too bad to force dealing with it while it's not needed

**Comment by Seldaek** [comment]
Yeah IMO there's a clear need for the bypass.. But I could live with csrf being enabled by default instead of bypassed by default.

**Comment by fabpot** [comment]
I think that having the default value (for CSRF validation) set to `true` by default is enough for me as it forces a conscious decision from the developer.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @johnkrovitch.

**Comment by johnkrovitch** [comment]
You're welcome. Thank you all
