### PR TITLE
[Messenger] Fix support for Redis Sentinel using php-redis 6.0.0

### LINKED ISSUE #52487: [Messenger] RedisSentinel for messeger needs the same fix cache got in #51683
### Symfony version(s) affected

6.3.5

### Description

Same problem as in #51683.

### How to reproduce

Use `redis-messenger` with Sentinel, you get
```
RedisSentinel::__construct() expects at most 1 argument, 6 given
```

### Possible Solution

Same type as #51683.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by pepeh**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #52487
| License       | MIT

Added support for [php-redis 6.0.0](https://github.com/phpredis/phpredis/blob/develop/CHANGELOG.md#600---2023-09-09-github-pecl) to Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.
A similar fix was done for RedisTrait before: https://github.com/symfony/symfony/pull/51683

### CODE REVIEW

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php [hunk 1]
```diff
@@ -94,7 +94,21 @@ public function __construct(array $options, \Redis|Relay|\RedisCluster $redis =
         } else {
             if (null !== $sentinelMaster) {
                 $sentinelClass = \extension_loaded('redis') ? \RedisSentinel::class : Sentinel::class;
-                $sentinelClient = new $sentinelClass($host, $port, $options['timeout'], $options['persistent_id'], $options['retry_interval'], $options['read_timeout']);
+
+                if (version_compare(phpversion('redis'), '6.0.0', '>=')) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]:
```suggestion
                if (\extension_loaded('redis') && version_compare(phpversion('redis'), '6.0.0', '>=')) {
```

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: is there a something similar to do for Relay? /cc @tillkruss @michael-grunder.

Comment (tillkruss) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: Good question. As of Relay [v0.6.8](https://github.com/cachewerk/relay/releases/tag/v0.6.8) we support both (PhpRedis 5.x and 6.x) constructors.

So you could do the same check for Relay, simply to future proof it. I don't think we'll drop support for the 5.x-style constructor anytime soon, tho.

Comment (tillkruss) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: @nicolas-grekas: There was another breaking change in PhpRedis 6.0 that I discovered randomly last week that can easily slip through the cracks and is hard to test for regarding `flushdb()` and `flushall()`.

In PhpRedis 5.x `flushdb(true)` will trigger `FLUSHDB ASYNC`, while in PhpRedis 6.x `flushdb(false)` will trigger `FLUSHDB ASYNC`.

- https://github.com/phpredis/phpredis/commit/750b6cf3
- https://github.com/phpredis/phpredis/commit/54a084e5

Comment (stof) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: Reversing the meaning of a boolean parameter is quite bad as BC break as it is not discoverable at all :cry:

Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: That's bad for end users indeed...

Comment (tillkruss) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: Yeah, and not even marking it as a BC in the release notes. I've complained to Michael and Pavlo about this. I discovered this by pure luck.
