### PR TITLE
[Notifier][Twilio] WhatsApp number validation

### LINKED ISSUE #61776: [Notifier][Twilio] WhatsApp number validation fails due to missing `whatsapp:` prefix in regex
### Symfony version(s) affected

6.4

### Description

The current implementation of `TwilioTransport.php` fails to validate numbers for use with Twilio's WhatsApp API. The regex used to validate the From number does not account for the required `whatsapp:` prefix, causing a InvalidArgumentException to be thrown for all valid WhatsApp sender IDs.

This prevents the library from being used to send messages via Twilio's WhatsApp service.

### How to reproduce

1. Attempt to send a message using a From number formatted for WhatsApp (e.g., whatsapp:+14155238886).

2. The application will throw an InvalidArgumentException.

```php
<?php
require_once __DIR__.'/.vendor/autoload.php';
use Symfony\Component\Notifier\Exception\InvalidArgumentException;

$from = 'whatsapp:+14155238886';

if (!preg_match('/^[a-zA-Z0-9\s]{2,11}$/', $from) && !preg_match('/^\+[1-9]\d{1,14}$/', $from)) {
    throw new InvalidArgumentException(\sprintf('The "From" number "%s" is not a valid phone number, shortcode, or alphanumeric sender ID.', $from));
}
```

### Possible Solution

Modify the regex in TwilioTransport.php to allow for the optional whatsapp: prefix.

```patch
@@  -61,67 +61,67 @@
$from = $message->getFrom() ?: $this->from;

- -> if (!preg_match('/^[a-zA-Z0-9\s]{2,11}$/', $from) && !preg_match('/^\+[1-9]\d{1,14}$/', $from)) {
+ -> if (!preg_match('/^[a-zA-Z0-9\s]{2,11}$/', $from) && !preg_match('/^(?:whatsapp:)?\+[1-9]\d{1,14}$/', $from)) {
            throw new InvalidArgumentException(\sprintf('The "From" number "%s" is not a valid phone number, shortcode, or alphanumeric sender ID.', $from));
}
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by OvidiuGi**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #61776 
| License       | MIT

This commit modifies the validation regex to handle 'whatsapp:' prefixes. The regex now correctly validates WhatsApp numbers without breaking existing functionality for standard phone numbers.

See 
- [https://github.com/symfony/symfony/issues/61776](url)

### CODE REVIEW

**Comment by OskarStark** [comment]
This is a new feature and must target 7.4 branch

**Comment by xabbuh** [comment]
Please also add an entry to the changelog file of the Twilio bridge to mention the added support for the WhatsApp API.

File: src/Symfony/Component/Notifier/Bridge/Twilio/TwilioTransport.php [hunk 1]
```diff
@@ -88,7 +88,7 @@ protected function doSend(MessageInterface $message): SentMessage
         if (201 !== $statusCode) {
             $error = $response->toArray(false);
 
-            throw new TransportException('Unable to send the SMS: '.$error['message'].\sprintf(' (see %s).', $error['more_info']), $response);
+            throw new TransportException('Unable to send the SMS: '.$error['message'].\sprintf(' (see "%s").', $error['more_info']), $response);
```
Comment (stof) [inline src/Symfony/Component/Notifier/Bridge/Twilio/TwilioTransport.php]: this should should be reverted. That's a case where the fabbot rule has a false positive.

File: src/Symfony/Component/Notifier/Bridge/Twilio/CHANGELOG.md [hunk 2]
```diff
@@ -1,5 +1,9 @@
 CHANGELOG
 =========
+7.4
```
Comment (xabbuh) [inline src/Symfony/Component/Notifier/Bridge/Twilio/CHANGELOG.md:4]:
```suggestion

7.4
```

File: src/Symfony/Component/Notifier/Bridge/Twilio/CHANGELOG.md [hunk 3]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+7.4
+---
+
+ * Support WhatsApp integration, allowing `From` numbers the `whatsapp:` prefix
```
Comment (xabbuh) [inline src/Symfony/Component/Notifier/Bridge/Twilio/CHANGELOG.md]: I wonder if the same about the `whatsapp:` prefix also isn't true for the receiver

Comment (OvidiuGi) [reply src/Symfony/Component/Notifier/Bridge/Twilio/CHANGELOG.md]: From what I can see, the receiver is not validated. `Unable to send the SMS: Invalid From and To pair. From and To should be of the same channel`, if I don't specify the prefix to the receiver

Comment (OvidiuGi) [reply src/Symfony/Component/Notifier/Bridge/Twilio/CHANGELOG.md]: The error is pretty straight forward though. I am not sure if we should validate the receiver.

Comment (xabbuh) [reply src/Symfony/Component/Notifier/Bridge/Twilio/CHANGELOG.md]: I think I would reword the changelog a bit then:

```
 * Add support for the WhatsApp integration if phone numbers are prefixed with `whatsapp:`
```

**Review by xabbuh — APPROVED** [review]

File: src/Symfony/Component/Notifier/Bridge/Twilio/CHANGELOG.md [hunk 4]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+7.4
+---
+
+* Add support for the WhatsApp integration if phone numbers are prefixed with `whatsapp:`
```
Comment (alexandre-daubois) [inline src/Symfony/Component/Notifier/Bridge/Twilio/CHANGELOG.md]:
```suggestion
 * Add support for the WhatsApp integration if phone numbers are prefixed with `whatsapp:`
```

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @OvidiuGi.
