### PR TITLE
[Messenger] prevent infinite redelivery loops and blocked queues

### LINKED ISSUE #32055: [Messenger] error in receiver results in message staying in queue forever
When an error in the worker happens before the message is dispatched on the bus (deserialization error of a message for example), the message is neither ack, nor nack, the exception not caught and the worker quit. 
The result is that the message stays in the queue (at the front). So the next worker will try to receive the same message again and likely fail again. This continues forever and you can't consume any good messages anymore.

A similar situation can happen when the handling of a message takes longer than the rabbitmq connection heartbeat or timeout. Ref. #31707 and https://github.com/php-enqueue/enqueue-dev/pull/658#issuecomment-442989563

Rabbitmq puts the messages back into the queue with a Redelivered header. How we solved it in our apps using https://github.com/M6Web/AmqpBundle is to ack the message directly when it has the Redelivered header and then trigger a retry.

I think it's important that SF messenger can handle those cases as well using it's retry logic and failed messages transport.

### PR DESCRIPTION
**Pull request by Tobion**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #32055
| License       | MIT
| Doc PR        |

This PR solves a very common fitfall of amqp redeliveries. It's for example explained in https://blog.forma-pro.com/rabbitmq-redelivery-pitfalls-440e0347f4e0
Newer RabbitMQ versions provide a solution for this by itself but only for quorum queues and not the classic ones, see https://github.com/rabbitmq/rabbitmq-server/pull/1889

This PR adds a middleware that throws a RejectRedeliveredMessageException when a message is detected that has been redelivered by AMQP.

The middleware runs before the HandleMessageMiddleware and prevents redelivered messages from being handled directly. The thrown exception is caught by the worker and will trigger the retry logic according to the retry strategy.

AMQP redelivers messages when they do not get acknowledged or rejected. This can happen when the connection times out or an exception is thrown before acknowledging or rejecting. When such errors happen again while handling the redelivered message, the message would get redelivered again and again. The purpose of this middleware is to prevent infinite redelivery loops and to unblock the queue by republishing the redelivered messages as retries with a retry limit and potential delay.

### CODE REVIEW

File: src/Symfony/Component/Messenger/Worker.php [hunk 1]
```diff
@@ -156,15 +164,15 @@ private function handleMessage(Envelope $envelope, ReceiverInterface $receiver,
                     ->with(new RedeliveryStamp($retryCount, $transportName))
                     ->withoutAll(ReceivedStamp::class);
 
-                // re-send the message
+                // re-send the message for retry
                 $this->bus->dispatch($retryEnvelope);
-                // acknowledge the previous message has received
-                $receiver->ack($envelope);
```
Comment (Tobion) [inline src/Symfony/Component/Messenger/Worker.php]: I changed this to `reject` and moved it outside the `if else`. Reject is more appropriate. Technically ack and reject are the same. There is only a semantical difference. Here we are handling a failure case and whether we retry or not does not change this.

Comment (weaverryan) [reply src/Symfony/Component/Messenger/Worker.php]: that seems reasonable.

File: src/Symfony/Component/Messenger/Worker.php [hunk 2]
```diff
@@ -135,6 +136,13 @@ private function handleMessage(Envelope $envelope, ReceiverInterface $receiver,
         try {
             $envelope = $this->bus->dispatch($envelope->with(new ReceivedStamp($transportName)));
         } catch (\Throwable $throwable) {
+            $rejectFirst = $throwable instanceof RejectRedeliveredMessageException;
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Worker.php]: It seems to me that the BIG important thing here is: if a message is redelivered, don't *actually* try to handle it again (because it'll probably timeout again). Instead, *skip* handling and have it be redelivered.

Question then: to fix this bug, is it actually important to reject this message *before* sending the redelivery? If we manage to skip the AMQP-redelivered message from being handled, isn't it ok if we follow the normal messenger-redelivery logic (redeliver the message and *then* reject it)? Or am I missing something?

If rejecting it *first* is *not* actually important, we could simplify this patch considerably.

thx :)

Comment (Tobion) [reply src/Symfony/Component/Messenger/Worker.php]: Rejecting redelivered messages first is important. As I described in https://github.com/symfony/symfony/issues/32055#issuecomment-529630654 and #34082, the repeating errors can happen inside the listeners or the retry publishing (anywhere inside the catch block). In this case, the message never gets rejected (as the exception happens before) and would be redelivered forever.

Comment (Tobion) [reply src/Symfony/Component/Messenger/Worker.php]: See also comment two lines below

Comment (weaverryan) [reply src/Symfony/Component/Messenger/Worker.php]: Hmm, ok. To make it feel like less of a one-off solution, wdyt about a RejectMessageImmediatelyExceptionInterface that we actually look for (then the class implements this)?

File: src/Symfony/Component/Messenger/Middleware/RejectRedeliveredMessageMiddleware.php [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+        if (null !== $envelope->last(ReceivedStamp::class)) {
+            $amqpReceivedStamp = $envelope->last(AmqpReceivedStamp::class);
+
+            if ($amqpReceivedStamp instanceof AmqpReceivedStamp && $amqpReceivedStamp->getAmqpEnvelope()->isRedelivery()) {
+                throw new RejectRedeliveredMessageException('Redelivered message from AMQP detected that will be rejected and trigger the retry logic.');
+            }
+        }
+
+        return $stack->next()->handle($envelope, $stack);
+    }
```
Comment (weaverryan) [inline src/Symfony/Component/Messenger/Middleware/RejectRedeliveredMessageMiddleware.php]: I wish there were a way to only run this if at least one Amqp transport were configured, but I know that’s not possible (so not a blocker or real feedback). It makes me wish each transport was actually its own package...

**Review by weaverryan — COMMENTED** [review]
I’m happy with this. I mean, the exact way we need to implement it bothers me a bit - which might be better with that exception interface idea. I’m open to any other suggestions :p. But that’s not a blocker: it fixes a bug with clear code.

File: src/Symfony/Component/Messenger/Worker.php (hunk 2 above)
Comment (Tobion) [reply src/Symfony/Component/Messenger/Worker.php]: We only want to reject redelivered messages first and not others to prevent potential loss of messages. So the interface would suggest something we don't want to promote. Also the `RejectRedeliveredMessageException` is not specific to amqp (hence the generic name) and we could use it also for doctrine and other transports. But for doctrine it's not that important as it has a timer in https://github.com/symfony/symfony/blob/c5024bdbd08550307321ed67a658c8442f65a536/src/Symfony/Component/Messenger/Transport/Doctrine/Connection.php#L36 that prevents the queue-blocking (but it does not prevent the potential redelivery loop)

File: src/Symfony/Component/Messenger/Middleware/RejectRedeliveredMessageMiddleware.php (hunk 3 above)
Comment (Tobion) [reply src/Symfony/Component/Messenger/Middleware/RejectRedeliveredMessageMiddleware.php]: As I said in https://github.com/symfony/symfony/pull/34107#discussion_r338783978, we might want to enhance the middleware later to handle other transports like doctrine.

**Review by weaverryan — APPROVED** [review]

**Comment by pkruithof** [comment]
Would it be possible to make this behaviour opt-in (or opt-out)? This is causing problems when you are relying on message order. I don't know about other queues, and there are some gotchas, but RabbitMQ states that messages are queued and consumed [in the FIFO manner](https://www.rabbitmq.com/queues.html#message-ordering). When you have a process that consumes messages and expects them to be in order (as we do), this could mess that up because a message which was in the front of the queue is now placed at the back of the queue.

**Comment by Tobion** [comment]
You can opt-out by not using the `reject_redelivered_message_middleware` middleware. So you configure the bus to not use the default middlewares and then add the ones you want.

But relying on message order has quite a few drawbacks. E.g. you also need to disable retry because it the message back to the end of the queue (optionally with delay).

**Comment by pkruithof** [comment]
> You can opt-out by not using the `reject_redelivered_message_middleware` middleware. So you configure the bus to not use the default middlewares and then add the ones you want.

This is what we did today to work around this. However when the original definition changes, we have to copy the configuration to keep up-to-date. It's not really a forwards compatible situation.

> But relying on message order has quite a few drawbacks. E.g. you also need to disable retry because it the message back to the end of the queue (optionally with delay).

We also did this: we exit the consumer once this happens, fix the message handling, and resume consuming. Which is why we are very happy with the [events PR](https://github.com/symfony/symfony/pull/34217), which makes this much easier to do.

**Comment by fabpot** [comment]
I would really not recommend to rely on message ordering. There are many things that can make the order non predictable. Like having more than one consumer when you scale. But there are many others. So, I think we should not do anything that makes developers think they can rely on any order.
