### PR TITLE
[Config][FrameworkBundle] Allow using ParamConfigurator with every configurable value

### LINKED ISSUE #62780: [Config] Typing does not handle ParamConfigurator and EnvConfigurator
### Symfony version(s) affected

>7.4.0

### Description

Static analysis tools (i.e. PHPStan) give errors when trying to use a parameter (i.e. `%kernel.debug%`) on a field with a non-string type.

### How to reproduce

```php
return App::config([
    'jms_serializer' => [
        'visitors' => [
            'xml_serialization' => [
                /*
                 * This field is typed as:
                 * 
                 * format_output?: bool, // Default: false
                 */
                'format_output' => param('kernel.debug'),
            ],
        ],
    ],
]);
```

### Possible Solution

All fields that can take a parameter, should also allow `ParamConfigurator` as one of their types.

So in my example above, the fields type should be: `format_output?: bool|ParamConfigurator, // Default: false`.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jack-worman**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62780
| License       | MIT

Updates generated typing to allow ParamConfigurator

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/PhpConfigReferenceDumpPass.php [hunk 1]
```diff
@@ -34,6 +34,8 @@ class PhpConfigReferenceDumpPass implements CompilerPassInterface
 
         namespace Symfony\Component\DependencyInjection\Loader\Configurator;
 
+        use Symfony\Component\Config\Loader\ParamConfigurator;
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/PhpConfigReferenceDumpPass.php]: whats about aliasing to make the rest shorter?

```suggestion
        use Symfony\Component\Config\Loader\ParamConfigurator as param;
```

**Review by nicolas-grekas — COMMENTED** [review]
that's a bit annoying but that makes sense also 🤷

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/PhpConfigReferenceDumpPass.php (hunk 1 above)
Comment (jack-worman) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/PhpConfigReferenceDumpPass.php]: Sure, done.

**Comment by nicolas-grekas** [comment]
The deps=low failure need a bump of di to ^7.4.3|^8.0.3 in fwb.

**Comment by jack-worman** [comment]
> The deps=low failure need a bump of di to ^7.4.3|^8.0.3 in fwb.

Thanks for the tip. It was actually `symfony/config` needing the bump.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @jack-worman.

**Comment by anatoly-pashin-axon21** [comment]
NB: For anyone who updated symfony/config to 7.4.3 and sees an error "Undefined class 'Param'" in their CI, you also need to update the framework bundle: https://github.com/symfony/framework-bundle/releases/tag/v7.4.3

I believe this is a breaking change, but whatever, it's released already.
