### PR TITLE
[DependencyInjection] fix dump xml with array/object/enum default value

### LINKED ISSUE #48178: [DependencyInjection] Unable to dump a service container when autowiring with enum default value
### Symfony version(s) affected

v6.2.0-BETA2

### Description

When trying to autowire a service which contains an enum default value, the container build fails with the following error:

```
Error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Unable to dump a service container if a parameter is an object or a resource. in [...]/vendor/symfony/dependency-injection/Dumper/XmlDumper.php:417
Stack trace:
#0 [...]/vendor/symfony/dependency-injection/Dumper/XmlDumper.php(372): Symfony\Component\DependencyInjection\Dumper\XmlDumper::phpToXml(Object(class@anonymous))
#1 [...]/vendor/symfony/dependency-injection/Dumper/XmlDumper.php(160): Symfony\Component\DependencyInjection\Dumper\XmlDumper->convertParameters(Array, 'argument', Object(DOMElement))
#2 [...]/vendor/symfony/dependency-injection/Dumper/XmlDumper.php(257): Symfony\Component\DependencyInjection\Dumper\XmlDumper->addService(Object(Symfony\Component\DependencyInjection\Definition), 'test', Object(DOMElement))
#3 [...]/vendor/symfony/dependency-injection/Dumper/XmlDumper.php(50): Symfony\Component\DependencyInjection\Dumper\XmlDumper->addServices(Object(DOMElement))
#4 [...]/vendor/symfony/framework-bundle/DependencyInjection/Compiler/ContainerBuilderDebugDumpPass.php(32): Symfony\Component\DependencyInjection\Dumper\XmlDumper->dump()
#5 [...]/vendor/symfony/dependency-injection/Compiler/Compiler.php(73): Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\ContainerBuilderDebugDumpPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#6 [...]/vendor/symfony/dependency-injection/ContainerBuilder.php(721): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#7 [...]/vendor/symfony/http-kernel/Kernel.php(487): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#8 [...]/vendor/symfony/http-kernel/Kernel.php(709): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#9 [...]/vendor/symfony/http-kernel/Kernel.php(172): Symfony\Component\HttpKernel\Kernel->preBoot()
#10 [...]/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#11 [...]/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#12 [...]/public/index.php(5): require_once('[...]/vendo...')
#13 {main}
thrown
```

### How to reproduce

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    test:
        class: App\Service\TestService
        arguments:
            $bubble: false
```

```php
<?php

namespace App\Service;

use Monolog\Level;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

class TestService
{
    public function __construct(
        ParameterBagInterface $parameterBag,
        int|string|Level $level = Level::Debug,
        bool $test = true,
        bool $bubble = true
    ) {
    }
}
```

once you change `$level = Level::Debug` to `$level = 100`, the error disappear and the container build is successful

also interesting is that removing the `bool $test = true,` also compiles without error, so it's more complex than just "enum default values do not work"

### Possible Solution

_No response_

### Additional Context

I experience this issue when trying to migrate a logging handler from monolog v2 to v3, where the best practice is to express default levels with enums.

workaround is to add the default value in the arguments as well:

```
    test:
        class: App\Service\TestService
        arguments:
            $level: 100 # or !php/enum Monolog\Level:Debug
            $bubble: false
```

### PR DESCRIPTION
**Pull request by Jean-Beru**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #48178
| License       | MIT
| Doc PR        |

This PR fixes #48178 when attempting to dump the container in these conditions:
* The constructor has in its arguments a non-empty array, an object or an enum with a default value
* A second argument is placed after
* A third argument is placed after and is using configuration

Example (might be more explicit):
```php
class Foo
{
    public function __construct(
        array $array = ['a', 'b', 'c'],
        bool $firstOptional = false,
        bool $secondOptional = false
    ) {}
}
```

```yaml
services:
    Foo:
        arguments:
            secondOptional: true
```

:warning: This PR might cause Git conflicts in 6.3 and 6.4 versions. Do I have to create a dedicated PR for these versions ?

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 1]
```diff
@@ -295,7 +298,7 @@ private function autowireMethod(\ReflectionFunctionAbstract $reflectionMethod, a
                     $type = ProxyHelper::getTypeHint($reflectionMethod, $parameter, false);
                     $type = $type ? sprintf('is type-hinted "%s"', ltrim($type, '\\')) : 'has no type-hint';
 
-                    throw new AutowiringFailedException($this->currentId, sprintf('Cannot autowire service "%s": argument "$%s" of method "%s()" %s, you should configure its value explicitly.', $this->currentId, $parameter->name, $class !== $this->currentId ? $class.'::'.$method : $method, $type));
+                    throw new AutowiringFailedException($this->currentId, sprintf('Cannot autowire service "%s": argument "$%s" of method "%s()" "%s", you should configure its value explicitly.', $this->currentId, $parameter->name, $class !== $this->currentId ? $class.'::'.$method : $method, $type));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: fabbot has many false positives, this is one of them (see what the %s is about: we don't what quotes around that)

File: src/Symfony/Component/DependencyInjection/Tests/Dumper/XmlDumperTest.php [hunk 2]
```diff
@@ -287,6 +291,34 @@ public function testDumpHandlesEnumeration()
         $this->assertEquals(file_get_contents(self::$fixturesPath.'/xml/services_with_enumeration.xml'), $dumper->dump());
     }
 
+    // https://github.com/symfony/symfony/issues/48178
+    /**
+     * @requires PHP 8.1
+     * @dataProvider provideDefaultClasses
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Dumper/XmlDumperTest.php]: we don't reference github in the source (and fabbot is right on this one)
```suggestion
    /**
     * @requires PHP 8.1
     *
     * @dataProvider provideDefaultClasses
```

File: src/Symfony/Component/DependencyInjection/Tests/Dumper/XmlDumperTest.php [hunk 3]
```diff
@@ -287,6 +291,34 @@ public function testDumpHandlesEnumeration()
...
+            ->setArguments([2 => true]);
+
+        (new AutowirePass())->process($container);
+
+        $dumper = new XmlDumper($container);
+
+        $this->assertSame(file_get_contents(self::$fixturesPath.'/xml/'.$expectedFile), $dumper->dump());
+    }
+
+    public function provideDefaultClasses()
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Dumper/XmlDumperTest.php]: data providers must be static in recent phpunit versions
```suggestion
    public static function provideDefaultClasses()
```

**Review by nicolas-grekas — COMMENTED** [review]
I guess this issue also exists with yaml? Can you please add a test case for it also?

File: src/Symfony/Component/DependencyInjection/Tests/Dumper/XmlDumperTest.php (hunk 2 above)
Comment (Jean-Beru) [reply src/Symfony/Component/DependencyInjection/Tests/Dumper/XmlDumperTest.php]: Okay. Do we have to remove all GitHub issues references in tests ? ex: https://github.com/symfony/symfony/tree/6.4/src/Symfony/Component/Form/Tests/ChoiceList/Factory/PropertyAccessDecoratorTest.php#L97

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Tests/Dumper/XmlDumperTest.php]: we could indeed

**Comment by nicolas-grekas** [comment]
Thank you @Jean-Beru.
