### PR TITLE
[FrameworkBundle] Fix UrlGenerator::generate to return an empty string instead of null

### LINKED ISSUE #30306: Controller::generateUrl() must be of the type string, null returned
**Symfony version(s) affected**: 4.2.2

**Description**  
method `\Symfony\Bundle\FrameworkBundle\Controller\ControllerTrait::generateUrl` has return value `: string`. This method delegates call to 
`\Symfony\Component\Routing\Generator\UrlGenerator::generate()`, then to `\Symfony\Component\Routing\Generator\UrlGenerator::doGenerate()` and method `doGenerate` can return `null`  on lines `170` and `224`

**How to reproduce**  
create route with regexp requirements and try to generate url with invalid data with `\Symfony\Bundle\FrameworkBundle\Controller\ControllerTrait::generateUrl`

**Possible Solution**  

- return empty string in `\Symfony\Component\Routing\Generator\UrlGenerator::doGenerate()`
- typecast result of `router::generate` in `ControllerTrait::generateUrl`

**Additional context**  
log message
```
{
    "level": "CRITICAL",
    "context_exception": {
      "files": [
        "/usr/local/www/citilink.ru_new/vendor/symfony/framework-bundle/Controller/ControllerTrait.php:78"
      ],
      "traces": [
        [
          "/usr/local/www/citilink.ru_new/App/Configurator/Controller/ItemController.php:333",
          "/usr/local/www/citilink.ru_new/vendor/symfony/http-kernel/HttpKernel.php:150",
          "/usr/local/www/citilink.ru_new/vendor/symfony/http-kernel/HttpKernel.php:67",
          "/usr/local/www/citilink.ru_new/vendor/symfony/http-kernel/Kernel.php:198",
          "/usr/local/www/citilink.ru_new/htdocs/app_prod.php:21"
        ]
      ],
      "messages": [
        "Return value of Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller::generateUrl() must be of the type string, null returned"
      ],
      "codes": [
        0
      ],
      "classes": [
        "Symfony\\Component\\Debug\\Exception\\FatalThrowableError"
      ]
    },
    "@timestamp": "2019-02-18T15:10:00.337Z",
    "input": {
      "type": "log"
    },
    "message": "Uncaught PHP Exception TypeError: \"Return value of Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller::generateUrl() must be of the type string, null returned\" at /usr/local/www/citilink.ru_new/vendor/symfony/framework-bundle/Controller/ControllerTrait.php line 78",
    "channel": "request"
    }
  }
}
```

code
```
    public function getActualConfigurationId(): Response
    {
        $session = $this->getSession();
        $user = $session->getUser();
        /** @var ConfigurationService $configurationService */
        $configurationService = $this->get('configurator.service.configuration.item');
        /** @var SimpleStorageInterface $guestUserConfigurationStorage */
        $guestUserConfigurationStorage = $this->get('configurator.service.guest_user_configuration_storage');

        $actualConfigurationId = $user !== null
            ? $configurationService->getActualConfigurationId($user, $session->getSpaceId())
            : $actualConfigurationId = $guestUserConfigurationStorage->get($session->getSessionId(), __METHOD__);

        $url = $actualConfigurationId
            ? $this->generateUrl(
                'configuratorInfo',
                ['itemId' => $actualConfigurationId],
                UrlGeneratorInterface::ABSOLUTE_URL
            )
            : null;

        return $this->ajaxSuccess(['id' => $actualConfigurationId, 'url' => $url]);
    }
```

### PR DESCRIPTION
**Pull request by eborges78**
| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #30306
| License       | MIT

Fix #30306 : Controller::generateUrl() must be of the type string, null returned

### CODE REVIEW

**Comment by xabbuh** [comment]
We would also need to update the docblock of the `ConfigurableRequirementsInterface` where `null` is explicitly documented.

File: src/Symfony/Component/Routing/Tests/Generator/UrlGeneratorTest.php [hunk 1]
```diff
@@ -203,7 +203,7 @@ public function testGenerateForRouteWithInvalidOptionalParameterNonStrict()
         $routes = $this->getRoutes('test', new Route('/testing/{foo}', ['foo' => '1'], ['foo' => 'd+']));
         $generator = $this->getGenerator($routes);
         $generator->setStrictRequirements(false);
-        $this->assertNull($generator->generate('test', ['foo' => 'bar'], UrlGeneratorInterface::ABSOLUTE_URL));
+        $this->assertEmpty($generator->generate('test', ['foo' => 'bar'], UrlGeneratorInterface::ABSOLUTE_URL));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Routing/Tests/Generator/UrlGeneratorTest.php]: `assertSame('',...`?

**Review by HeahDude — APPROVED** [review]
:+1:

**Comment by fabpot** [comment]
This should be merged in 3.4 if we consider it as a bug fix.

**Comment by fabpot** [comment]
After thinking about it a bit more, I would rather merge it in master and add a note in the changelogs about the change.

**Comment by fabpot** [comment]
@eborges78 Can you rebase on current master instead of merging? Merge commits forbids us from merging the PR. Thank you.

File: UPGRADE-4.3.md [hunk 2]
```diff
@@ -37,6 +37,7 @@ FrameworkBundle
  * Not passing the project directory to the constructor of the `AssetsInstallCommand` is deprecated. This argument will
    be mandatory in 5.0.
  * Deprecated the "Psr\SimpleCache\CacheInterface" / "cache.app.simple" service, use "Symfony\Contracts\Cache\CacheInterface" / "cache.app" instead.
+ * The `generate()` method of the `UrlGenerator` class return empty string instead of null
```
Comment (nicolas-grekas) [inline UPGRADE-4.3.md]: can return an empty string

**Review by nicolas-grekas — APPROVED** [review]
lgtm, with minor comment

File: UPGRADE-4.3.md (hunk 2 above)
Comment (eborges1978) [reply UPGRADE-4.3.md]: fixed

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @eborges78.
