### PR TITLE
[DebugBundle][HttpKernel] Collect dumps when console profiling is enabled

### LINKED ISSUE #61971: [Console][WebProfiler] Profiled commands don't contain `dump` data
### Symfony version(s) affected

7.3

### Description

When using `--profile`, `debug` section is always empty.

Image

Reason for this is that `debug.dump_listener` is not aware that `data_collector.dump` exists, and that `DataCollector` is not called. If I replace `DataDumperInterface $dumper` argument from `debug.dump_listener` with `data_collector.dump` instead, collected data is registered in the profiler as expected. 

### How to reproduce

 * Create a new Symfony project
 * Install profiler and debug dependencies (`composer require --dev debug profiler`)
 * Create any command with `dump('foo')` in `execute` method
 * Call created command with `--profiler` option

### Possible Solution

Simply adding `data_collector.dump` as an additional dependency to `debug.dump_listener` seems to work, although it's possible that it should only be called if `--profile` was actually passed. Not sure about other side effects this might have.

Here is the result I got once I swapped dumper in `debug.dump_listener` with `data_collector.dump` (which removed the dump output from console, of course).

```php
# vendor/symfony/debug-bundle/Resources/config/services.php
    $services
        ->set('debug.dump_listener', DumpListener::class)
            ->args([
                service('var_dumper.cloner'),
                # Replaced:
                # service('var_dumper.cli_dumper'),
                service('data_collector.dump'),
                null,
            ])
            ->tag('kernel.event_subscriber');
```

Image

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #61971
| License       | MIT

Currently, when profiling a console command, calls to `dump()` aren't collected.
With this PR, they'll be collected when profiling is enabled, or output directly when it's not.

Not entirely sure whether this should be considered a bug or simply a missing feature.

### CODE REVIEW

File: src/Symfony/Component/HttpKernel/EventListener/DumpListener.php [hunk 1]
```diff
@@ -28,21 +29,26 @@ class DumpListener implements EventSubscriberInterface
...
         $this->dumper = $dumper;
         $this->connection = $connection;
+        $this->profilerDumper = $profilerDumper;
     }
 
     /**
      * @return void
      */
-    public function configure()
+    public function configure(/* ?ConsoleCommandEvent $event = null */)
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/EventListener/DumpListener.php]: missing `@param`

**Review by nicolas-grekas — COMMENTED** [review]
Can't this be dealt with outside of the class? Inside the injected dumper?
I'm asking because this makes the constructor a bit weird.
Some explanations could be helpful.

**Comment by HypeMC** [comment]
> Can't this be dealt with outside of the class? Inside the injected dumper? I'm asking because this makes the constructor a bit weird. Some explanations could be helpful.

@nicolas-grekas I've considered several approaches. The main obstacle I came across was having access to the `Input` object to check for the `--profile` option, while also avoiding unnecessary instantiation of the `DumpDataCollector` when profiling isn't enabled.

I also thought about creating a new implementation of `DataDumperInterface`, injecting both the CLI and collector dumpers into it, and turning it into a console event listener so it could access the `Input` object. Maybe that would be a better approach?

File: src/Symfony/Component/HttpKernel/EventListener/DumpListener.php (hunk 1 above)
Comment (HypeMC) [reply src/Symfony/Component/HttpKernel/EventListener/DumpListener.php]: Done

**Comment by nicolas-grekas** [comment]
I wonder if not-instantiating the dump-collector is really a concern? Would it make things simpler if not?

Otherwise, let's add some explanation about the argument in an `@param` then?
Also some notes in the changelog/upgrade files.

**Comment by HypeMC** [comment]
> I wonder if not-instantiating the dump-collector is really a concern? Would it make things simpler if not?

@nicolas-grekas It might not be a real concern, but it doesn't simplify things either. I could always inject the `DumpDataCollector`, but I'd still need access to the `Input` object, which would require making it a listener. Also, I'd need to add a new constructor argument to inject the CLI dumper, since the current dumper might be a `Connection`.

> Otherwise, let's add some explanation about the argument in an `@param` then? Also some notes in the changelog/upgrade files.

Regarding the changelog/upgrade part, should I retarget 7.4 and mark it as a feature?

**Comment by nicolas-grekas** [comment]
Yes, let's target 7.4.
Thanks for the chat 🙂

**Comment by HypeMC** [comment]
> Yes, let's target 7.4. Thanks for the chat 🙂

@nicolas-grekas Done. Thanks for the feedback.

**Comment by MatTheCat** [comment]
I thought the logic was that if the dump had somewhere to be displayed on it wouldn’t appear in the profiler: that matched Twig’s `dump` function’s behavior. Should this one be updated too?

**Comment by HypeMC** [comment]
@MatTheCat With this PR, the `dump()` function works in the CLI the same way it does in the web context. When the profiler is not enabled, it outputs directly, otherwise, it sends the data to the profiler.

The Twig `dump()` function, on the other hand, renders the dump as part of the template in both contexts.

File: src/Symfony/Bundle/DebugBundle/CHANGELOG.md [hunk 2]
```diff
@@ -1,6 +1,11 @@
 CHANGELOG
 =========
 
+7.4
+---
+
+ * Wire the `$profilerDumper` argument in `DumpListener`
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/DebugBundle/CHANGELOG.md:7]: what's the outcome of this change? is this related to the console profiling? if not, is that a bugfix for another branch? Sorry I forgot how this works :)

Comment (HypeMC) [reply src/Symfony/Bundle/DebugBundle/CHANGELOG.md:7]: @nicolas-grekas It wires the newly added second dumper argument so that the `DumpListener` can "choose" which dumper to use based on whether the `--profile` option is set. The listener is only triggered for console commands. Like I mentioned earlier, it feels more like a missing feature to me than a bug fix.

**Comment by nicolas-grekas** [comment]
Thank you @HypeMC.

**Comment by Steveb-p** [comment]
Thanks for solving it @HypeMC :bow:
