### PR TITLE
[Mailer] Fix Sendmail memory leak

### LINKED ISSUE #50486: Sendmail transport runs out of memory
### Symfony version(s) affected

6.2 and other 6.*

### Description

Trying to send a lot of Laravel 10 email notifications in loop, Sendmail transport runs out of memory:
Allowed memory size of 5242880000 bytes exhausted (tried to allocate 2673869000 bytes)

  at vendor/symfony/mailer/Transport/Smtp/Stream/AbstractStream.php:37
     33▕     public function write(string $bytes, bool $debug = true): void
     34▕     {
     35▕         if ($debug) {
     36▕             foreach (explode("\n", trim($bytes)) as $line) {
  ➜  37▕                 $this->debug .= sprintf("> %s\n", $line);
     38▕             }
     39▕         }
     40▕
     41▕         $bytesToWrite = \strlen($bytes);

It seems the issue comes from vendor/symfony/mailer/Transport/SendmailTransport.php attempting to store in memory whole mail bodies as debugging information and not even clearing it when called in loop. E.g. SmtpTransport.php doesn't store the whole mail body in memory. I don't think production framework should do either by default.

### How to reproduce

Call $user->notify($notification); in loop where notification uses MailMessage with /usr/sbin/sendmail -t -i -odq mailer.

### Possible Solution

```diff
vendor/symfony/mailer/Transport/SendmailTransport.php
@@ -113,7 +113,7 @@
         $this->stream->setCommand($command);
         $this->stream->initialize();
         foreach ($chunks as $chunk) {
-            $this->stream->write($chunk);
+            $this->stream->write($chunk, false);
         }
         $this->stream->flush();
         $this->stream->terminate();
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rch7**
| Q             | A
| ------------- | ---
| Branch?       | 6.4 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? |no 
| Issues        | Fix #50486 
| License       | MIT

Previous PR: https://github.com/symfony/symfony/pull/59239

Fixes issue #50486 (Sendmail transport runs out of memory).
- I have removed unrelated changes that somehow got in the previous attempt of pull request because of wrong base version.
- As for the "metrics about the memory leak itself" - it is in the issue 50486. When write(), which is defined in vendor/symfony/mailer/Transport/Smtp/Stream/AbstractStream.php, is called without $debug parameter, it's true by default, and $this->debug gets appended all the email body data incrementally.
  So for example if you have loop sending personalized emails to 200,000 subscribers 20 kB each, $this->debug becomes 4 GB, plus overhead, and the script runs out of resources.
  The fix eliminates the problem.

### CODE REVIEW

**Comment by alexisLefebvre** [comment]
Please replace `Fix 50486` with `Fix #50486` in the description of this issue. It will create a link to the issue, and probably enable auto-close of the related issue.

Related:

- #50486

File: src/Symfony/Component/Mailer/Transport/SendmailTransport.php [hunk 1]
```diff
@@ -114,7 +114,7 @@ protected function doSend(SentMessage $message): void
         $this->stream->setCommand($command);
         $this->stream->initialize();
         foreach ($chunks as $chunk) {
-            $this->stream->write($chunk);
+            $this->stream->write($chunk, false);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mailer/Transport/SendmailTransport.php:117]: For next reviewers: this sets the debug flag, so that the stream instance doesn't keep a string copy of what was written. ~This debug info is not accessible anywhere anyway.~
That's similar to:
https://github.com/rch7/symfony/blob/c74e2a3d7e1df817b2bea7d8f6a8fc3373c445bb/src/Symfony/Component/Mailer/Transport/Smtp/SmtpTransport.php#L222

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @rch7.
