### PR TITLE
[Security] remove return type definition in order to avoid type juggling

### LINKED ISSUE #39205: Voters - different behavior on dev/test and production enviroment
**Symfony version(s) affected**: tested on 5.0.10  (but from what I see in a code, 

**Description**  

Basically each voter in dev/test env is wrapped in `\Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter` proxy.  In [that commit](https://github.com/symfony/symfony/commit/65d942010c25914ff32f2514649f9bfcec5f644e) @nicolas-grekas added return type `int`. Because there is no "strict types" in file...all return results are type juggled to int. 
In prod env, there is no such proxy so the result is not juggled into an int.

Voter Result is used in \Symfony\Component\Security\Core\Authorization\AccessDecisionManager where it is strictly compared.

**How to reproduce**  

There are several possible solutions, and I would be happy to implement it. However, I do not know properly the "Symfony way" to contribute. So I am going to be more than happy by pointing to the correct solution: 

- Option nr . 1 Use strict types in TraceableVoter -> It will throw an error if someone's voter will return different type than boolean.
       disadventages: backward-incompatible, some projects may not handle such error + I did not see using strict_types in Symfony(surprised tbh).

- Option nr . 2 Cast return from Voter in AccessDecisionManager into "int". I think it is an ugly version, but most likely to be correct here

- Option nr. 3 remove return type declaration from vote method (after allis cause the problem). There is no such declaration in VoterInterface

- Option nr. 4 - most elegant imho. Adding the return type declaration in VoterInterface. however in breaks backward compatibility so that solution can be introduced in 6.0 framework.

**Additional context**

### PR DESCRIPTION
**Pull request by adeptofvoltron**
| Q             | A
| ------------- | ---
| Branch?       |4.4 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #39205  
| License       | MIT
| Doc PR        | 

Everything described with details inrelated ticket

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

File: src/Symfony/Component/Security/Core/Authorization/Voter/TraceableVoter.php [hunk 1]
```diff
@@ -39,7 +39,7 @@ public function __construct(VoterInterface $voter, EventDispatcherInterface $eve
         }
     }
 
-    public function vote(TokenInterface $token, $subject, array $attributes): int
+    public function vote(TokenInterface $token, $subject, array $attributes)
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Core/Authorization/Voter/TraceableVoter.php:42]: can you add an `@return` annotation please?
Note that in Symfony 6, returning an `int` will be enforced, so that you should also fix any code that doesn't return an `int` already.

Comment (wouterj) [reply src/Symfony/Component/Security/Core/Authorization/Voter/TraceableVoter.php:42]: Is it needed, given that this is already part of `VoterInterface::vote()`?

Comment (adeptofvoltron) [reply src/Symfony/Component/Security/Core/Authorization/Voter/TraceableVoter.php:42]: @nicolas-grekas as mention above. It is already in the interface.

Note taken. Actually, it is already well discussed in the related issue.

Comment (nicolas-grekas) [reply src/Symfony/Component/Security/Core/Authorization/Voter/TraceableVoter.php:42]: OK, indeed.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @adeptofvoltron.
