### PR TITLE
[Form] Fix "prototype_data" option creating duplicates instead of new lines

### LINKED ISSUE #49961: [Form] CollectionType: prototype_data option creates duplicates instead of new lines
### Symfony version(s) affected

6.2.8

### Description

I'm using CollectionType to embed a collection of forms and when I'm using `prototype_data` option and there is a bug when I add new lines in my form. It creates duplicates instead of create x new lines.

FYI, i'm using DTO's to populate my entities, idk if it changes something but it was working before the package upgrade.
I don't have the issue when I removed the `prototype_data` option but i need it to initialize data in new fields

### How to reproduce

**My parent form** 

```
$builder
    ->add('name', TextType::class)
    ->add('steps', CollectionType::class, [
        'entry_type' => StepForm::class,
        'allow_add' => true,
        'allow_delete' => true,
        'by_reference' => false,
        'prototype' => true,
        'prototype_name' => '__steps__',
        'prototype_data' => new StepData()
    ]);
```

**My child form** 

```
$builder
    ->add('name', TextType::class)
    ->add('probability', ChoiceType::class, [
        'choice_loader' => new CallbackChoiceLoader(function () {
            $probabilities = [];

            for ($i = 0; $i <= 10; $i++) {
                $value = $i * 10;
                $probabilities["{$value}%"] = $value;
            }

            return $probabilities;
        }),
    ])
    ->add('position', HiddenType::class, [
        'attr' => ['class' => 'position']
    ]);
```

**My form in front** _only the last 3 lines are added and new_
Capture d’écran 2023-04-06 à 16 20 10

**After form submission** _you can see that the last 3 lines are the same with the same id (2112)_
Capture d’écran 2023-04-06 à 16 20 31

 

### Possible Solution

I have downgraded the package `symfony/form` to the version `6.2.7` to solve this issue 

### Additional Context

I created a Symfony project to reproduce the bug. You can solve it to downgrade `symfony/form` package
https://github.com/jkgroupe/symfony-bug-form

### PR DESCRIPTION
**Pull request by Thorry84**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49961 
| License       | MIT

Fix for issue 49961.

Changed the prototype options passed to the ResizeFormListener to prevent prototype_data from being passed to new fields.

### CODE REVIEW

File: src/Symfony/Component/Form/Extension/Core/Type/CollectionType.php [hunk 1]
```diff
@@ -36,6 +36,8 @@ public function buildForm(FormBuilderInterface $builder, array $options)
 
             $prototype = $builder->create($options['prototype_name'], $options['entry_type'], $prototypeOptions);
             $builder->setAttribute('prototype', $prototype->getForm());
+
+            $resizeFormListenerPrototypeOptions = array_replace($options['entry_options'], $options['prototype_options']);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Form/Extension/Core/Type/CollectionType.php]: What about the options set on L29-30, do we want them in this array?
Sorry I'm not much into this domain so this might be a dumb question.

Comment (Thorry84) [reply src/Symfony/Component/Form/Extension/Core/Type/CollectionType.php]: Very good question, I was wondering about that as well.

Those provide some default values in case they aren't provided via the `entry_options` and `prototype_options` array. Since required defaults to true, a collection with required set to false would have the entries set to required. (See issue #15544)

However since the `entry_options` and later the `prototype_options` have been introduced, this behavior is kind of redundant.

Same for the label, this is because otherwise the label isn't rendered as a replaceable string when using `prototype_name` as a label. Since the prototype is normally used to add new fields to a form using JS, it's important to have them be replaceable (see issue #3738). For the new fields rendered server-side, the `prototype_name` isn't used, so the label for the prototype shouldn't be used.
I'm not sure of the use case for falling back to the `prototype_name` as a label, but it's being kept the same for BC reasons.

So I think we don't want those values in the array and only use `entry_options` and `prototype_options` for the `ResizeFormListener`.

**Comment by nicolas-grekas** [comment]
Thank you @Thorry84.
