### PR TITLE
[TwigBridge] Fix "Serialization of 'Closure'" error when rendering an TemplatedEmail

### LINKED ISSUE #40445: 5.2.5 regression on sending email Serialization of 'Closure' is not allowed
**Symfony version(s) affected**: 5.2.5

**Description**
On a normally working Symfony project, we send an email on user login
After upgrading to Symfony 5.2.5 this now creates an error

Screenshot 2021-03-11 at 12 46 44

**How to reproduce**

I think the cause is passing in Entities and Objects to the context, which might have closures in them.

Im passing into the context the User object and the LoginSuccessEvent event in my live app. 

You can replicate this by changing the UnitTest to have a closure in the context of the templated email as follows, this will result in the broken unit test with the same error Im experiencing. 

```
// changing the testRenderedOnce test you can replicate this 

 $closure = function ($name){
            return $name;
        };

        $email = (new TemplatedEmail())
            ->to('fabien@symfony.com')
            ->from('helene@symfony.com')
            ->context(['event'=>$closure])
        ;
```

Screenshot 2021-03-11 at 13 12 15

**Possible Solution**
re-review of https://github.com/symfony/symfony/pull/39733/ which was added in 5.2.5 and the error message relates to.

**Additional context**
Transport is a standard SMTP.

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40445
| License       | MIT
| Doc PR        | 

When context contains a closure, it can't be serialized. In that case, we now assume that fingerprint is always different, and in that case, email will always be re-rendered

### CODE REVIEW

**Review by fabpot — APPROVED** [review]

File: src/Symfony/Bridge/Twig/Mime/BodyRenderer.php [hunk 1]
```diff
@@ -77,6 +77,23 @@ public function render(Message $message): void
...
+        $messageContext = $message->getContext();
+        unset($messageContext[__CLASS__]);
+
+        $payload = [$messageContext, $message->getTextTemplate(), $message->getHtmlTemplate()];
+        try {
+            $serialized = serialize($payload);
+        } catch (\Exception $e) {
+            // Serialization of 'Closure' is not allowed
+            // Happens when context contain a closure, in that case, we assume that context always change.
+            $serialized = uniqid('', true);
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Twig/Mime/BodyRenderer.php]: `random_bytes(8)` would be better (8 or anything else) :)

Comment (jderusse) [reply src/Symfony/Bridge/Twig/Mime/BodyRenderer.php]: done

**Comment by stof** [comment]
The title of the PR should clearly be updated, to have a proper message in changelogs

**Review by derrabus — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jderusse.

**Comment by PhilETaylor** [comment]
Thank you @jderusse hope the report helped identify the issue easy enough for you.
