### PR TITLE
[DoctrineBridge] Idle connection listener for long running runtime

### LINKED ISSUE #51661: Doctrine left in non-operable state when used with Swoole/FrankenPHP
### Symfony version(s) affected

*

### Description

Running Symfony with a long-running runtime that leaves worker threads alive, such as swoole, roadrunner and frankenphp regularly leads to exceptions being thrown when fetching many entities (~100) with doctrine, every few requests.

The roadrunner bundle addresses this with a doctrine orm/odm middleware: https://github.com/Baldinof/roadrunner-bundle/blob/3.x/src/Integration/Doctrine/DoctrineORMMiddleware.php#L22

and there's also a bundle specifically for this issue here: https://github.com/pixelfederation/doctrine-resettable-em-bundle (which doesn't appear to work for FrankenPHP).

I've brought this up in the [FrankenPHP repository](https://github.com/dunglas/frankenphp/issues/207#issuecomment-1720739553) but since Symfony tries to officially support these runtimes, it should probably be fixed here.

### How to reproduce

Unfortunately I do not have a minimal example to reproduce this issue yet, but it is well known about and a way to fix it has been linked above.

If necessary, I can create a reproducer next week.

### Possible Solution

https://github.com/Baldinof/roadrunner-bundle/blob/3.x/src/Integration/Doctrine/DoctrineORMMiddleware.php#L22

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alli83**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix https://github.com/symfony/symfony/issues/51661
| License       | MIT

This pull request introduces a solution based on the RoadRunner bundle's Doctrine ORM/ODM middleware https://github.com/Baldinof/roadrunner-bundle/blob/3.x/src/Integration/Doctrine/DoctrineORMMiddleware.php#L22.
It checks the status of Doctrine connection, then if the connection is initialized and connected, it performs a 'ping' to check its viability. If the ping fails, it closes the connection.

linked to https://github.com/doctrine/DoctrineBundle/pull/1739

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+use Symfony\Component\EventDispatcher\EventDispatcherInterface;
+use Symfony\Component\EventDispatcher\EventSubscriberInterface;
+use Symfony\Component\HttpKernel\Event\RequestEvent;
+use Symfony\Component\HttpKernel\KernelEvents;
+use Symfony\Component\VarExporter\LazyObjectInterface;
+
+/**
+ * Based on https://github.com/Baldinof/roadrunner-bundle/blob/3.x/src/Integration/Doctrine/DoctrineORMMiddleware.php.
+ */
+class DoctrineConnectionListener implements EventSubscriberInterface
```
Comment (alexandre-daubois) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]:
```suggestion
class DoctrineConnectionSubscriber implements EventSubscriberInterface
```

As it implements a EventSubsciberInterface :slightly_smiling_face:

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+
+        foreach ($connectionServices as $connectionServiceName) {
+            if (!$this->container->initialized($connectionServiceName)) {
+                continue;
+            }
+
+            $connection = $this->container->get($connectionServiceName);
+
+            if (!$connection instanceof Connection) {
+                throw new \RuntimeException(sprintf('Is not an instance of "%s".', Connection::class));
```
Comment (alexandre-daubois) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: I think this doesn't match usual messages format. I think the codebase tends to have something more like "Connection is not an instance of...", same for the others

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+                    throw new \RuntimeException(sprintf('Is not an instance of "%s".', EntityManagerInterface::class));
+                }
+
+                if ($manager instanceof LazyLoadingInterface) {
+                    continue; // Doctrine bundle will handle manager reset on next request
+                }
+
+                if ($manager instanceof LazyObjectInterface) {
+                    continue; // Doctrine bundle will handle manager reset on next request
+                }
```
Comment (alexandre-daubois) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: These two can be merged. It will avoid the comment duplication also

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+
+                if (!$manager->isOpen()) {
+                    $this->eventDispatcher->dispatch(new ForceKernelRebootEvent(
+                        "entity manager '$managerName' is closed and the package `symfony/proxy-manager-bridge` is not installed so kernel reset will not re-open it"
```
Comment (alexandre-daubois) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]:
```suggestion
                        "Entity manager '$managerName' is closed and the package `symfony/proxy-manager-bridge` is not installed so kernel reset will not re-open it."
```

Maybe `sprintf` should be used in order to use double quotes around the manager name. This is what's used in other messages of the framework

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 5]
```diff
@@ -0,0 +1,104 @@
...
+                continue;
+            }
+
+            $connection = $this->container->get($connectionServiceName);
+
+            if (!$connection instanceof Connection) {
+                throw new \RuntimeException(sprintf('Is not an instance of "%s".', Connection::class));
+            }
+
+            if ($connection->isConnected() && false === $this->ping($connection)) {
```
Comment (alexandre-daubois) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]:
```suggestion
            if ($connection->isConnected() && !$this->ping($connection)) {
```

**Review by alexandre-daubois — COMMENTED** [review]
A few suggestions :slightly_smiling_face:

**Comment by nicolas-grekas** [comment]
Hi, thanks for working on this topic.
Would there be a way to put that concern in Doctrine itself, by decorating the Connection object?
I'm concerned that the current approach will trigger one DB call per HTTP request while not all HTTP entpoints might use Doctrine, and also by the fact this only works for HTTP while recovering from stalled DB connections is also a concern for CLI workers.

**Comment by OskarStark** [comment]
Just reading the code, it adds a lot new stuff which looks like a new feature instead of a bugfix to me

**Comment by dunglas** [comment]
I agree that a decorator would be better. Also, would it be possible to catch errors and reconnect only in this case instead of triggering a ping? This would remove the performance hit in most cases.

@OskarStark the code probably needs to be simplified, but the underlying bug is annoying because it makes Symfony apps unstable when using FrankenPHP, RoadRunner (without the bundle), Swoole etc. The fix should be made at least in the current stable version.

**Comment by alli83** [comment]
@nicolas-grekas @dunglas ok I'll update it and try to decorate the Connection object

**Comment by OskarStark** [comment]
> @OskarStark the code probably needs to be simplified, but the underlying bug is annoying because it makes Symfony apps unstable when using FrankenPHP, RoadRunner (without the bundle), Swoole etc. The fix should be made at least in the current stable version.

Thanks for the explanation Kevin 👍

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionSubscriber.php [hunk 6]
```diff
@@ -0,0 +1,100 @@
...
+
+        foreach ($connectionServices as $connectionServiceName) {
+            if (!$this->container->initialized($connectionServiceName)) {
+                continue;
+            }
+
+            $connection = $this->container->get($connectionServiceName);
+
+            if (!$connection instanceof Connection) {
+                throw new \RuntimeException(sprintf('The value "%s" is not an instance of "%s".', $connection ? $connection::class : 'null', Connection::class));
```
Comment (ostrolucky) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionSubscriber.php]: Why making the connection being non-connection illegal? We should just skip if we don't recognize it.

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionSubscriber.php [hunk 7]
```diff
@@ -0,0 +1,100 @@
...
+
+            foreach ($managerNames as $managerName) {
+                if (!$this->container->initialized($managerName)) {
+                    continue;
+                }
+
+                $manager = $this->container->get($managerName);
+
+                if (!$manager instanceof EntityManagerInterface) {
+                    throw new \RuntimeException(sprintf('The value "%s" is not an instance of "%s".', $manager ? $manager::class : 'null', EntityManagerInterface::class));
```
Comment (ostrolucky) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionSubscriber.php]: Again, you should not make it illegal to use different instances of OM. For example, this will break everything for ODM users.

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionSubscriber.php [hunk 8]
```diff
@@ -0,0 +1,100 @@
...
+                }
+
+                if ($manager instanceof LazyLoadingInterface || $manager instanceof LazyObjectInterface) {
+                    continue; // Doctrine bundle will handle manager reset on next request
+                }
+
+                if (!$manager->isOpen()) {
+                    $this->eventDispatcher->dispatch(new ForceKernelRebootEvent(
+                        sprintf('Entity manager "%s" is closed and the package `symfony/proxy-manager-bridge` is not installed so kernel reset will not re-open it', $managerName)
+                    ));
```
Comment (ostrolucky) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionSubscriber.php]: What's the use case for this event?

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionSubscriber.php [hunk 9]
```diff
@@ -0,0 +1,100 @@
...
+
+    private function ping(Connection $con): bool
+    {
+        try {
+            $con->executeQuery($con->getDatabasePlatform()->getDummySelectSQL());
+
+            return true;
+        } catch (DBALException $e) {
+            return false;
+        }
```
Comment (ostrolucky) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionSubscriber.php]:
```suggestion
        } catch (DBALException) {
            return false;
        }
```

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionSubscriber.php [hunk 10]
```diff
@@ -0,0 +1,100 @@
...
+    }
+
+    public static function getSubscribedEvents(): array
+    {
+        return [
+            KernelEvents::REQUEST => 'onKernelRequest',
+        ];
+    }
```
Comment (ostrolucky) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionSubscriber.php]: Why should this class be an event subscriber instead of event listener?

**Review by ostrolucky — CHANGES_REQUESTED** [review]
I don't like the approach, because as @nicolas-grekas mentioned, this will keep pinging the DB every request, even if normally request wouldn't need connection. Can't we make this DBAL middleware instead? Middleware would check if any query fails with "DB went away..." error, if so, reset everything and retry.

Also, bear in mind counterpart for messenger is at https://github.com/symfony/symfony/blob/412ea7afcb533b8a7a95e248d741b70fea505350/src/Symfony/Bridge/Doctrine/Messenger/DoctrinePingConnectionMiddleware.php, so this would be a good opportunity to extract common parts into bridge

**Comment by alli83** [comment]
> https://github.com/symfony/symfony/blob/412ea7afcb533b8a7a95e248d741b70fea505350/src/Symfony/Bridge/Doctrine/Messenger/DoctrinePingConnectionMiddleware.php

Ok, I'll update then

**Comment by alli83** [comment]
> I don't like the approach, because as @nicolas-grekas mentioned, this will keep pinging the DB every request, even if normally request wouldn't need connection. Can't we make this DBAL middleware instead? Middleware would check if any query fails with "DB went away..." error, if so, reset everything and retry.
> 
> Also, bear in mind counterpart for messenger is at https://github.com/symfony/symfony/blob/412ea7afcb533b8a7a95e248d741b70fea505350/src/Symfony/Bridge/Doctrine/Messenger/DoctrinePingConnectionMiddleware.php, so this would be a good opportunity to extract common parts into bridge

Ok, I'll update then

**Comment by alli83** [comment]
@ostrolucky 
Before refactoring (taking into account `DoctrinePingConnectionMiddleware`), I'm not entirely sure I grasp the specific middleware you're referring to. Are you referring to those related to `Doctrine\DBAL\Driver`
`Doctrine\DBAL\Driver\Connection`

**Comment by ostrolucky** [comment]
I was referring to middlewares that implement `Doctrine\DBAL\Driver\Middleware`. This is how Symfony does stuff like logging

**Comment by KDederichs** [comment]
Any news on this/what's preventing it from being merged?

File: src/Symfony/Bridge/Doctrine/CheckConnection.php [hunk 11]
```diff
@@ -0,0 +1,29 @@
...
+class CheckConnection
+{
+    public static function checkConnection(Connection $connection)
+    {
+        try {
+            $connection->executeQuery($connection->getDatabasePlatform()->getDummySelectSQL());
+        } catch (DBALException) {
+            $connection->close();
+            // Attempt to reestablish the lazy connection by sending another query.
+            $connection->executeQuery($connection->getDatabasePlatform()->getDummySelectSQL());
```
Comment (ostrolucky) [inline src/Symfony/Bridge/Doctrine/CheckConnection.php]: It needs to look like this to be compatible with DBAL 4
```suggestion
            $connection->executeQuery($connection->getDatabasePlatform($connection)->getDummySelectSQL());
        } catch (DBALException) {
            $connection->close();
            // Attempt to reestablish the lazy connection by sending another query.
            $connection->executeQuery($connection->getDatabasePlatform($connection)->getDummySelectSQL());
```

File: src/Symfony/Bridge/Doctrine/CheckConnection.php [hunk 12]
```diff
@@ -0,0 +1,29 @@
...
+ */
+
+namespace Symfony\Bridge\Doctrine;
+
+use Doctrine\DBAL\Connection;
+use Doctrine\DBAL\Exception as DBALException;
+
+class CheckConnection
+{
+    public static function checkConnection(Connection $connection)
```
Comment (ostrolucky) [inline src/Symfony/Bridge/Doctrine/CheckConnection.php]:
```suggestion
/** @internal */
class ConnectionLossAwareHandler
{
    public static function reconnectOnFailure(Connection $connection)
```

File: src/Symfony/Bridge/Doctrine/Middleware/DoctrineConnectionMiddleware.php [hunk 13]
```diff
@@ -0,0 +1,32 @@
...
+ */
+class DoctrineConnectionMiddleware implements Middleware
+{
+    public function __construct(private ManagerRegistry $managerRegistry, private ContainerInterface $container)
+    {
+    }
+
+    public function wrap(Driver $driver): Driver
+    {
+        return new DoctrineConnectionDriver($driver, $this->managerRegistry, $this->container);
```
Comment (ostrolucky) [inline src/Symfony/Bridge/Doctrine/Middleware/DoctrineConnectionMiddleware.php]: Let's embed driver here as anonymous class, saves us a headache naming it and this is how traditional dbal middlewares are done (see `\Doctrine\DBAL\Driver\AbstractSQLiteDriver\Middleware\EnableForeignKeys`, `\Doctrine\DBAL\Driver\OCI8\Middleware\InitializeSession`...)

File: src/Symfony/Bridge/Doctrine/Middleware/DoctrineConnectionMiddleware.php [hunk 14]
```diff
@@ -0,0 +1,32 @@
...
+
+use Doctrine\DBAL\Driver;
+use Doctrine\DBAL\Driver\Middleware;
+use Doctrine\Persistence\ManagerRegistry;
+use Symfony\Component\DependencyInjection\ContainerInterface;
+
+/**
+ * Based on https://github.com/Baldinof/roadrunner-bundle/blob/3.x/src/Integration/Doctrine/DoctrineORMMiddleware.php.
+ */
+class DoctrineConnectionMiddleware implements Middleware
```
Comment (ostrolucky) [inline src/Symfony/Bridge/Doctrine/Middleware/DoctrineConnectionMiddleware.php]:
```suggestion
class ConnectionKeepAlive implements Middleware
```

**Review by ostrolucky — CHANGES_REQUESTED** [review]
Are you planning to add some tests?

**Comment by alli83** [comment]
> Are you planning to add some tests?

in https://github.com/doctrine/DoctrineBundle/pull/1739 PR

File: src/Symfony/Bridge/Doctrine/CheckConnection.php [hunk 15]
```diff
@@ -0,0 +1,29 @@
...
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Bridge\Doctrine;
+
+use Doctrine\DBAL\Connection;
+use Doctrine\DBAL\Exception as DBALException;
+
+class CheckConnection
```
Comment (ostrolucky) [inline src/Symfony/Bridge/Doctrine/CheckConnection.php]:
```suggestion
/** @internal */
class ConnectionLossAwareHandler
```

**Review by ostrolucky — APPROVED** [review]

**Comment by dunglas** [comment]
We discussed this privately with @jwage. It seems that this patch can cause very rare problems that are difficult to reproduce. For example, if the connection fails for some reason (not a scheduled timeout) just after a transaction commit, a duplicate write could occur.

Laravel uses a similar strategy to the one implemented in this patch, but tries to mitigate duplicate write problems by sniffing the exception message: laravel/framework@11.x/src/Illuminate/Database/DetectsLostConnections.php#L20-L74

I'm not sure this method is 100% reliable: what happens if a network error occurs after validation but before the client has received the ACK? Is the error message always different in this case? Perhaps @taylorotwell or @nunomaduro have more information on this?

I thought of another way to solve the specific problem of timeouts in long-running processes:

* store the timestamp of the last successful request
* before sending a new request, test whether the last successful request was before a configurable timeout (MySQL's default timeout is 28800 seconds - 8 hours, and Postgres doesn't have a default timeout, but we can use something shorter, like 30 seconds because many hosting providers use shorter timeouts)
* if it's been too long since the last request, ping the server and reconnect if necessary before sending the actual request.

This approach has several advantages:

* it focuses on long-running processes
* it mimics the behavior of processes that haven't been running for long (by default)
* it never replicates automatically





We discussed this privately with @jwage. It seems that this may cause very rare and hard-to-reproduce problems. For instance, if the connection fails for some reason (not an expected timeout) just after a transaction commit, a duplicate write could occur.

Laravel uses a similar strategy to the one implemented in this patch but tries to mitigate duplicate write issues by sniffing the exception message: https://github.com/laravel/framework/blob/11.x/src/Illuminate/Database/DetectsLostConnections.php#L20-L74

I'm not sure if it's 100% reliable: what happens if a network error occurs after the commit but before the ACK has been received by the client? Is the error message always different in this case? Maybe @taylorotwell or @nunomaduro have more insights about this?

I thought about another way to fix the specific issue of timeouts in long-running processes:

1. store the timestamp of the last successful query
2. before sending a new query, test if the last successful query was before a configurable amount of time (the default MySQL timeout is 28800 seconds - 8 hours and Postgres has no timeout by default, but we can use something shorter, like 30 seconds because many hosters use shorter timeouts)
3. if the last query was too long ago, ping the server, and reconnect if necessary before sending the actual query

This approach has several benefits:

* it is being focused on long-running processes
* it mimics the behavior of non-long-running processes (the default)
* it never automatically replays requests

Perhaps we could add such middleware to Doctrine itself so that it benefits all projects using Doctrine with other frameworks or without frameworks at all?

File: src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAlive.php [hunk 16]
```diff
@@ -0,0 +1,83 @@
...
+            public function __construct(private Driver $driver, private readonly ManagerRegistry $managerRegistry, private readonly ContainerInterface $container)
+            {
+                parent::__construct($driver);
+            }
+
+            public function connect(array $params): DriverConnection
+            {
+                $connectionServices = $this->managerRegistry->getConnectionNames();
+
+                foreach ($connectionServices as $connectionServiceName) {
```
Comment (stof) [inline src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAlive.php]: having a middleware for one connection that reconnects all connections is a no-go for me. It does not make any sense. A middleware should apply only to the connection it is applied on.

File: src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAlive.php [hunk 17]
```diff
@@ -0,0 +1,83 @@
...
+                        }
+
+                        $manager = $this->container->get($managerName);
+
+                        if (!$manager instanceof EntityManagerInterface) {
+                            continue;
+                        }
+
+                        if (!$manager->isOpen()) {
+                            $this->managerRegistry->resetManager($managerName);
```
Comment (stof) [inline src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAlive.php]: having a DBAL middleware resetting the entity manager is even more a no-go for me. This might reset the entity manager at times where the application is not ready at all to handle them (remember that resetting an entity manager means that all entity instances you have become unmanaged and cannot be used anymore as managed entities)

File: src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAlive.php (hunk 16 above)
Comment (stof) [reply src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAlive.php]: Btw, this listener will actually apply on all connections **except** the one being wrapped by the middleware (because by the time the `->connect()` middleware is called, the current connection is not connected yet). And it would be called after the connection has been established earlier and lost (so it won't solve the case of long running runtime AFAICT)

**Comment by stof** [comment]
Please share more details about the kind of use cases you have for that.

I see 3 different kinds of long running runtimes here:

- the messenger consumer. For that case, we already have a solution for it with the messenger middleware which checks the state of the DBAL connection between the handling of messenger messages (which is a moment where we know it is safe to disconnect and reconnect as we are not in the middle of the handling of a task, and the handling of each message is meant to be independent)
- application servers like roadrunner. A similar implementation should be done by checking the state of the connection between requests (and also the state of the ORM entity manager to reset it if it is closed, but that should be separate from the DBAL logic to allow using DBAL without the ORM)
- a single command that takes a long time to run to execute its single task (note that this does not include commands corresponding to alternative queue consumers implementations than messenger. Those should be solved in the same way than messenger). For this one, I don't have a solution, and I don't think we can have a generic solution (imagine the case where the command decides to wrap its logic in a single long-running transaction: there is no way to recover from connection loss in such case as you would not return in the previous transaction)

File: src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAlive.php (hunk 16 above)
Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAlive.php]: Thank you for your feedback.
I'm a bit confused. How could I be aware of the currently used connection for the requested operation? Also, Are you suggesting that it's not through this type of middleware that the result can be achieved in terms of when it will be called?

I appreciate your explanations in advance 🙏

Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAlive.php]: actually, as discussed, this middleware already wraps the connection so maybe, it would be more appropriate to consider a different approach

**Comment by alli83** [comment]
closing the PR : see https://github.com/doctrine/dbal/pull/6351 and https://github.com/doctrine/DoctrineBundle/pull/1739

**Comment by alli83** [comment]
Would it be preferable to define a timing for each connection in case multiple connections are set in the configuration? If so, in the listener, it would be necessary to be able to identify the connection and avoid looping over all defined connections. Otherwise, we can define a timing globally

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 18]
```diff
@@ -0,0 +1,48 @@
...
+{
+    private int $lastChecked = 0;
+
+    public function __construct(private ContainerInterface $container, private int $checkTiming)
+    {
+    }
+
+    public function onKernelRequest(RequestEvent $event): void
+    {
+        $connection = $this->container->get('database_connection');
```
Comment (greg0ire) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: This is a good first step. If it works great, I think something should be contributed to the bundle to tag all connection services so that they can be more easily injected. To be honest, I'm a bit surprised that such a tag doesn't already exist… I hope introducing it won't be an issue.

**Comment by alli83** [comment]
I pushed a second commit to implement timing per connection type defined in the config file. However, I believe I could further improve it by ensuring that this check is only done if the request contains an SQL query. I'm working on it.

**Comment by nicolas-grekas** [comment]
> further improve it by ensuring that this check is only done if the request contains an SQL query

This might complicate things a lot, isn't it?
Personally, I'd be fine with pinging the connection without caring if the response needs access to the DB, provided:
- we skip errors silently
- we lazy-load everything in the listener so that we don't load anything from Doctrine if not needed.

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 19]
```diff
@@ -0,0 +1,55 @@
...
+    {
+        foreach($this->timingByConnection as $params) {
+            $this->lastChecked[$params['name'] = 0];
+        }
+    }
+
+    public function onKernelRequest(RequestEvent $event): void
+    {
+        foreach ($this->timingByConnection as $params) {
+            $connection = $this->container->get($params['name']);
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: I think we need to decouple the time check from the connection objects, so that we can skip loading anything from Doctrine if no ping is needed.
This means the listener should be able to know if the timeout arrived without using connection objects.
This means connection objects should populate a time registry when they do anything successful on the network.

Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: I'm not sure I understand. I need to associate a timing with each connection, right? Or perhaps I'm having difficulty understanding what you're suggesting

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 20]
```diff
@@ -0,0 +1,55 @@
...
+use Symfony\Component\HttpKernel\KernelEvents;
+
+class DoctrineConnectionListener implements EventSubscriberInterface
+{
+    private array $lastChecked = [];
+
+    public function __construct(private readonly ContainerInterface $container, private readonly array $timingByConnection)
+    {
+        foreach($this->timingByConnection as $params) {
+            $this->lastChecked[$params['name'] = 0];
```
Comment (DavidBadura) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: Shouldn't the line look like this?

```suggestion
            $this->lastChecked[$params['name']] = 0;
```

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php (hunk 19 above)
Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: Okay, I think I've got it, and I'm going to add a middleware. I'll work on it and push a commit. Thanks for your feedback!

Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: a WeakMap for example
we should be able to make a middleware that puts the current connection in the WeakMap at each network call, with the timestamp
and in the listener, we do a foreach on this map to know if you're closing (and unsetting) or not

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php (hunk 20 above)
Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: oh indeed, thanks!

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php (hunk 19 above)
Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: I'm not sure if I need a WeakMap. I could just have a simple array. The retrieved Connection is a decorator of Doctrine Dbal/Connection, and if I'm not mistaken, it closes on Dbal\Connection, right? https://github.com/doctrine/DoctrineBundle/pull/1739

File: src/Symfony/Bridge/Doctrine/ConnectionTimingWeakMap.php [hunk 21]
```diff
@@ -0,0 +1,33 @@
...
+
+namespace Symfony\Bridge\Doctrine;
+
+class ConnectionTimingWeakMap
+{
+    private ?\WeakMap $connectionWeakMap = null;
+
+    public function __construct()
+    {
+        $this->connectionWeakMap = $this->connectionWeakMap ?? new \WeakMap();
```
Comment (DavidBadura) [inline src/Symfony/Bridge/Doctrine/ConnectionTimingWeakMap.php]: `$this->connectionWeakMap` should not be nullable, because you put it right here. And checking beforehand whether the property is set is not necessary in a constructor. You can also use phpdocs to specify the data type of the WeapMap: `WeakMap<Connection, array{timing: int, name: string}>`

File: src/Symfony/Bridge/Doctrine/ConnectionTimingWeakMap.php [hunk 22]
```diff
@@ -0,0 +1,33 @@
...
+    }
+
+    public function setTimingPerConnection($connection, $connectionName): void
+    {
+        $timestamp = time();
+        $this->connectionWeakMap[$connection] = ['timing' => $timestamp, 'name' => $connectionName];
+    }
+
+    public function getTimingsPerConnection(): ?\WeakMap
```
Comment (DavidBadura) [inline src/Symfony/Bridge/Doctrine/ConnectionTimingWeakMap.php]: Using a WeakMap should be an implementation detail and not be given to the outside. It would be better to offer methods like `remove` and `all` etc. This also prevents someone from doing anything wrong with the WeakMap.

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 23]
```diff
@@ -0,0 +1,61 @@
...
+use Doctrine\DBAL\Connection;
+use Symfony\Bridge\Doctrine\ConnectionTimingWeakMap;
+use Symfony\Component\DependencyInjection\ContainerInterface;
+use Symfony\Component\EventDispatcher\EventSubscriberInterface;
+use Symfony\Component\HttpKernel\Event\RequestEvent;
+use Symfony\Component\HttpKernel\KernelEvents;
+
+class DoctrineConnectionListener implements EventSubscriberInterface
+{
+    public function __construct(private ConnectionTimingWeakMap $connectionTimingWeakMap, private readonly ContainerInterface $container, private readonly array $timingByConnection)
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: I think we can do with just this:
```suggestion
    public function __construct(
        private \WeakMap $connectionTimingRegistry,
    )
```

File: src/Symfony/Bridge/Doctrine/ConnectionTimingWeakMap.php (hunk 22 above)
Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/ConnectionTimingWeakMap.php]: Not sure about this: a WeakMap makes it clear that the design is made to break circular references. A class with a dedicated API doesn't make sense to me because this is only about wiring stuff, not providing an API.

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php (hunk 23 above)
Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php:23]: Yes indeed

Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: But I do need to retrieve the various timings that were defined in the configuration, right?

Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: OK, after reviewing https://github.com/doctrine/DoctrineBundle/pull/1739, I now get that the easiest way to wire things together is to identify connection objects by name (they're public services already).
So indeed, we don't need a WeakMap anymore (an ArrayObject is enough), and we do need the $container.
That's two arguments, so we can remove one :)

File: src/Symfony/Bridge/Doctrine/ConnectionTiming.php [hunk 24]
```diff
@@ -0,0 +1,16 @@
...
+ *
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Bridge\Doctrine;
+
+class ConnectionTiming extends \ArrayObject
```
Comment (OskarStark) [inline src/Symfony/Bridge/Doctrine/ConnectionTiming.php]: this class is unused

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 25]
```diff
@@ -0,0 +1,51 @@
...
+namespace Symfony\Bridge\Doctrine\Listener;
+
+use Symfony\Component\DependencyInjection\ContainerInterface;
+use Symfony\Component\EventDispatcher\EventSubscriberInterface;
+use Symfony\Component\HttpKernel\Event\RequestEvent;
+use Symfony\Component\HttpKernel\KernelEvents;
+
+class DoctrineConnectionListener implements EventSubscriberInterface
+{
+    public function __construct(private readonly \ArrayObject $connectionTiming, private ContainerInterface $container, private readonly array $timingbyConnection)
```
Comment (OskarStark) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: please linebreak the parameters

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 26]
```diff
@@ -0,0 +1,50 @@
...
+ */
+
+namespace Symfony\Bridge\Doctrine\Listener;
+
+use Symfony\Component\DependencyInjection\ContainerInterface;
+use Symfony\Component\EventDispatcher\EventSubscriberInterface;
+use Symfony\Component\HttpKernel\Event\RequestEvent;
+use Symfony\Component\HttpKernel\KernelEvents;
+
+class DoctrineConnectionListener implements EventSubscriberInterface
```
Comment (stof) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: the class should be final (or at least `@final`) to avoid having to maintain BC for people trying to extend it (which has no use case IMO)

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 27]
```diff
@@ -0,0 +1,50 @@
...
+{
+    public function __construct(private readonly \ArrayObject $connectionTiming, private ContainerInterface $container, private readonly array $timingbyConnection)
+    {
+    }
+
+    public function onKernelRequest(RequestEvent $event): void
+    {
+        $connectionTiming = $this->connectionTiming->getIterator();
+
+        if (!$connectionTiming) {
```
Comment (stof) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: when is this falsy ?

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 28]
```diff
@@ -0,0 +1,50 @@
...
+namespace Symfony\Bridge\Doctrine\Listener;
+
+use Symfony\Component\DependencyInjection\ContainerInterface;
+use Symfony\Component\EventDispatcher\EventSubscriberInterface;
+use Symfony\Component\HttpKernel\Event\RequestEvent;
+use Symfony\Component\HttpKernel\KernelEvents;
+
+class DoctrineConnectionListener implements EventSubscriberInterface
+{
+    public function __construct(private readonly \ArrayObject $connectionTiming, private ContainerInterface $container, private readonly array $timingbyConnection)
```
Comment (stof) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: please add phpdoc describing the expected types for the array and for the ArrayObject generic types.

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 29]
```diff
@@ -0,0 +1,50 @@
...
+
+        if (!$connectionTiming) {
+            return;
+        }
+
+        foreach ($connectionTiming as $key => $value) {
+            $connectionName = sprintf('doctrine.dbal.%s_connection', $value['name']);
+
+            if (time() - $value['timing'] >= $this->timingbyConnection[$connectionName]) {
+                $connection = $this->container->get(sprintf('doctrine.dbal.%s_connection', $value['name']));
```
Comment (stof) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: I suggest injecting the ConnectionRegistry (which allows getting connections by name) or a service locator indexed by connection name instead of hardcoding the service naming convention of DoctrineBundle in this bridge class.

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 30]
```diff
@@ -0,0 +1,50 @@
...
+    public function onKernelRequest(RequestEvent $event): void
+    {
+        $connectionTiming = $this->connectionTiming->getIterator();
+
+        if (!$connectionTiming) {
+            return;
+        }
+
+        foreach ($connectionTiming as $key => $value) {
+            $connectionName = sprintf('doctrine.dbal.%s_connection', $value['name']);
```
Comment (stof) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: this is not the connection name. It looks like it is the service id.

I would suggest keeping `timingbyConnection` indexed by name

File: src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php [hunk 31]
```diff
@@ -0,0 +1,23 @@
...
+
+namespace Symfony\Bridge\Doctrine\Middleware;
+
+use Doctrine\DBAL\Driver;
+use Doctrine\DBAL\Driver\Connection as DriverConnection;
+use Doctrine\DBAL\Driver\Middleware\AbstractDriverMiddleware;
+
+class ConnectionKeepAliveDriver extends AbstractDriverMiddleware
+{
+    public function __construct(private Driver $driver, private \ArrayObject $connectionTimings, private string $connectionName = 'default')
```
Comment (stof) [inline src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php]: I would make the connection name a mandatory argument here

Comment (stof) [inline src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php]: `$driver` must not be a promoted property, as we should not have a property declared in that class (the property is in the parent class)

File: src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php [hunk 32]
```diff
@@ -0,0 +1,23 @@
+<?php
+
+namespace Symfony\Bridge\Doctrine\Middleware;
+
+use Doctrine\DBAL\Driver;
+use Doctrine\DBAL\Driver\Connection as DriverConnection;
+use Doctrine\DBAL\Driver\Middleware\AbstractDriverMiddleware;
+
+class ConnectionKeepAliveDriver extends AbstractDriverMiddleware
```
Comment (stof) [inline src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php]: this class should be final or `@final`

**Review by stof — CHANGES_REQUESTED** [review]

**Comment by greg0ire** [comment]
Is "timing" the right word here? This is IMO more like a time to live / an expiration time.

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php (hunk 27 above)
Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: no indeed, it can't be. I remove it.

File: src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php (hunk 31 above)
Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php]: oups indeed

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php (hunk 23 above)
Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: Updated, and ContainerInterface has been replaced with ConnectionRegistry.

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 33]
```diff
@@ -0,0 +1,55 @@
...
+    )
+    {
+    }
+
+    public function onKernelRequest(RequestEvent $event): void
+    {
+        $connectionTiming = $this->connectionTiming->getIterator();
+
+        foreach ($connectionTiming as $key => $value) {
+
```
Comment (OskarStark) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]:
```suggestion
```

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 34]
```diff
@@ -0,0 +1,55 @@
...
+     * @param \ArrayObject<int, array{name: string, timing: int}> $connectionTiming
+     * @param ConnectionRegistry                                  $connectionRegistry
+     * @param array                                               $timingByConnection
+     */
+    public function __construct(
+        private readonly \ArrayObject $connectionTiming,
+        private ConnectionRegistry $connectionRegistry,
+        private readonly array $timingByConnection
+    )
+    {
```
Comment (OskarStark) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]:
```suggestion
    ) {
```

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 35]
```diff
@@ -0,0 +1,55 @@
...
+{
+    /**
+     * @param \ArrayObject<int, array{name: string, timing: int}> $connectionTiming
+     * @param ConnectionRegistry                                  $connectionRegistry
+     * @param array                                               $timingByConnection
+     */
+    public function __construct(
+        private readonly \ArrayObject $connectionTiming,
+        private ConnectionRegistry $connectionRegistry,
+        private readonly array $timingByConnection
```
Comment (OskarStark) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]:
```suggestion
        private readonly array $timingByConnection,
```

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 36]
```diff
@@ -0,0 +1,50 @@
...
+
+final class DoctrineConnectionListener implements EventSubscriberInterface
+{
+    /**
+     * @param \ArrayObject<int, array{name: string, timing: int}> $connectionTiming
+     */
+    public function __construct(
+        private readonly \ArrayObject $connectionTiming,
+        private ConnectionRegistry $connectionRegistry,
+        private readonly array $timingByConnection
```
Comment (OskarStark) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: Can you add an explicit array type for this property please? thanks

File: src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php [hunk 37]
```diff
@@ -0,0 +1,32 @@
...
+
+namespace Symfony\Bridge\Doctrine\Middleware;
+
+use Doctrine\DBAL\Driver;
+use Doctrine\DBAL\Driver\Connection as DriverConnection;
+use Doctrine\DBAL\Driver\Middleware\AbstractDriverMiddleware;
+
+final class ConnectionKeepAliveDriver extends AbstractDriverMiddleware
+{
+    public function __construct(Driver $driver, private \ArrayObject $connectionTimings, private string $connectionName)
```
Comment (OskarStark) [inline src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php]:
```suggestion
    public function __construct(
        Driver $driver,
        private \ArrayObject $connectionTimings,
        private string $connectionName,
    )
```

File: src/Symfony/Bridge/Doctrine/ConnectionTiming.php (hunk 24 above)
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/ConnectionTiming.php]: let's remove this class, we don't need it

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 38]
```diff
@@ -0,0 +1,51 @@
...
+
+final class DoctrineConnectionListener implements EventSubscriberInterface
+{
+    /**
+     * @param \ArrayObject<int, array{name: string, timing: int}> $connectionTiming
+     * @param array<string, int>                                  $timeToLiveByConnection
+     */
+    public function __construct(
+        private readonly \ArrayObject $connectionTiming,
+        private ConnectionRegistry $connectionRegistry,
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: This object is too heavy to instantiate.
I was more comfortable with the previous implementation that relied on the string identifier.
Can we find a way that'd use the service ids instead?

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 39]
```diff
@@ -0,0 +1,51 @@
...
+        private readonly array $timeToLiveByConnection,
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: I think this concern (the by-connection aspect) should live in the driver or the middleware.
We can remove this map if we use $connectionExpiries instead of $connectionTiming (aka the timestamp when the object is EOLed.)

**Review by nicolas-grekas — COMMENTED** [review]
much simpler :)

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php (hunk 38 above)
Comment (stof) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: Why is it heavy ? The ConnectionRegistry used in DoctrineBundle is a wrapper around a ServiceLocator.

Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: Hum, right. Still, that's a bunch of interfaces and classes to load for 100% of requests, vs doing nothing, which is unbeatable, perf-wise.

File: src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php [hunk 40]
```diff
@@ -0,0 +1,35 @@
...
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Bridge\Doctrine\Middleware;
+
+use Doctrine\DBAL\Driver;
+use Doctrine\DBAL\Driver\Connection as DriverConnection;
+use Doctrine\DBAL\Driver\Middleware\AbstractDriverMiddleware;
+
+final class ConnectionKeepAliveDriver extends AbstractDriverMiddleware
```
Comment (greg0ire) [inline src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php:18]: I think the naming is off here as well… this driver does not keep connections alive, it works with another class to close them, by recording when the underlying connection was last used.

```suggestion
final class UsageRecordingDriver extends AbstractDriverMiddleware
```

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php (hunk 39 above)
Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: But I'm not sure I understand: don't we need a reference point to compare timings and decide whether to close or not?

Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: I think I understand what you mean.

File: src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php [hunk 41]
```diff
@@ -0,0 +1,36 @@
...
+        private readonly array $timeToLiveByConnection,
+        private readonly string $connectionName
+    ) {
+        parent::__construct($driver);
+    }
+
+    public function connect(array $params): DriverConnection
+    {
+        $connection = parent::connect($params);
+        $this->connectionTimings->append(['expiry' => time() + $this->timeToLiveByConnection[$this->connectionName], 'name' => $this->connectionName]);
```
Comment (greg0ire) [inline src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php]:
```suggestion
        $this->connectionEols[$this->connectionName] = time() + $this->timeToLiveByConnection[$this->connectionName]);
```

I think this is the wrong data structure: you will have as many lines in there as SQL queries. I think you should use the connection name as a key, and overwrite the limit every time a query happens. Let me know what I'm missing

File: src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php [hunk 42]
```diff
@@ -0,0 +1,36 @@
...
+
+use Doctrine\DBAL\Driver;
+use Doctrine\DBAL\Driver\Connection as DriverConnection;
+use Doctrine\DBAL\Driver\Middleware\AbstractDriverMiddleware;
+
+final class ConnectionKeepAliveDriver extends AbstractDriverMiddleware
+{
+    public function __construct(
+        Driver $driver,
+        private readonly \ArrayObject $connectionTimings,
```
Comment (greg0ire) [inline src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php]:
```suggestion
        private readonly \ArrayObject $connectionEols,
```

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 43]
```diff
@@ -0,0 +1,49 @@
...
+
+use Symfony\Component\DependencyInjection\ContainerInterface;
+use Symfony\Component\EventDispatcher\EventSubscriberInterface;
+use Symfony\Component\HttpKernel\Event\RequestEvent;
+use Symfony\Component\HttpKernel\KernelEvents;
+
+final class DoctrineConnectionListener implements EventSubscriberInterface
+{
+    /**
+     * @param \ArrayObject<int, array{name: string, timing: int}> $connectionTiming
```
Comment (greg0ire) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]:
```suggestion
     * @param \ArrayObject<name, int> $connectionEols
```

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 44]
```diff
@@ -0,0 +1,49 @@
...
+     */
+    public function __construct(
+        private readonly \ArrayObject $connectionTiming,
```
Comment (greg0ire) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]:
```suggestion
        private readonly \ArrayObject $connectionEols,
```

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 45]
```diff
@@ -0,0 +1,49 @@
...
+/*
+ * This file is part of the Symfony package.
+ *
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Bridge\Doctrine\Listener;
```
Comment (greg0ire) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: Both classes are highly coupled together, they should IMO live in the same namespace

File: src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php [hunk 46]
```diff
@@ -0,0 +1,36 @@
...
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Bridge\Doctrine\Middleware;
+
+use Doctrine\DBAL\Driver;
+use Doctrine\DBAL\Driver\Connection as DriverConnection;
+use Doctrine\DBAL\Driver\Middleware\AbstractDriverMiddleware;
+
+final class ConnectionKeepAliveDriver extends AbstractDriverMiddleware
```
Comment (greg0ire) [inline src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php]: This name is a bit misleading because this class does not keep connections alive, it works with another class to close them.

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php (hunk 45 above)
Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: Maybe we can put everything in the Middleware\AutoClose subnamespace, like we did for Middleware\Debug?

File: src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php [hunk 47]
```diff
@@ -0,0 +1,36 @@
...
+        private readonly array $timeToLiveByConnection,
+        private readonly string $connectionName
+    ) {
+        parent::__construct($driver);
+    }
+
+    public function connect(array $params): DriverConnection
+    {
+        $connection = parent::connect($params);
+        $this->connectionExpiries->append(['expiry' => time() + $this->timeToLiveByConnection[$this->connectionName], 'name' => $this->connectionName]);
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Middleware/ConnectionKeepAliveDriver.php]:
```suggestion
        $this->connectionExpiries[$this->connectionName] = time() + $this->timeToLiveByConnection[$this->connectionName];
```

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php (hunk 43 above)
Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: you mean `\ArrayObject<string, int> $connectionExpiries` :)

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php (hunk 29 above)
Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: (note for other reviewers: this suggestion has been objected - using public service ids will provide the best performance)

Comment (stof) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: Even if we inject a ServiceLocator, we could still index it by connection name rather than service ids (it makes no difference in the performance of a ServiceLocator)

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 48]
```diff
@@ -0,0 +1,51 @@
...
+    ) {
+    }
+
+    public function onKernelRequest(RequestEvent $event): void
+    {
+        $connectionTiming = $this->connectionEols->getIterator();
+
+        $timestamp = time();
+
+        foreach ($connectionTiming as $key => $value) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]:
```suggestion
        foreach ($connectionTiming as $name => $value) {
```

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php [hunk 49]
```diff
@@ -0,0 +1,51 @@
...
+     */
+    public function __construct(
+        private readonly \ArrayObject $connectionEols,
+        private ContainerInterface $container,
+    ) {
+    }
+
+    public function onKernelRequest(RequestEvent $event): void
+    {
+        $connectionTiming = $this->connectionEols->getIterator();
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]:
```suggestion
        $connectionExpiries = $this->connectionEols->getIterator();
```

File: src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php (hunk 29 above)
Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/Listener/DoctrineConnectionListener.php]: We could, but there is zero benefit doing so: since connections are public services, we can skip building any tailored locator.

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php [hunk 50]
```diff
@@ -0,0 +1,36 @@
...
+
+use Doctrine\DBAL\Driver;
+use Doctrine\DBAL\Driver\Connection as DriverConnection;
+use Doctrine\DBAL\Driver\Middleware\AbstractDriverMiddleware;
+
+final class AutoCloseDriver extends AbstractDriverMiddleware
+{
+    public function __construct(
+        Driver $driver,
+        private \ArrayObject $connectionExpiries,
```
Comment (dunglas) [inline src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php]:
```suggestion
        private \ArrayObject $connectionExpires,
```

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php [hunk 51]
```diff
@@ -0,0 +1,36 @@
...
+        private readonly array $timeToLiveByConnection,
+        private readonly string $connectionName
+    ) {
+        parent::__construct($driver);
+    }
+
+    public function connect(array $params): DriverConnection
+    {
+        $connection = parent::connect($params);
+        $this->connectionExpiries[$this->connectionName] = time() + $this->timeToLiveByConnection[$this->connectionName];
```
Comment (dunglas) [inline src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php]:
```suggestion
        $timestamp = time();
        $connection = parent::connect($params);
        $this->connectionExpires[$this->connectionName] = $timestamp + $this->timeToLiveByConnection[$this->connectionName];
```

Storing the current time before the connection will prevent weird race conditions (we will be sure that the expiration will be the TTL max. Currently, depending on the time it takes to do post-connect things, it can exceed the TTL.

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php [hunk 52]
```diff
@@ -0,0 +1,36 @@
...
+use Doctrine\DBAL\Driver\Connection as DriverConnection;
+use Doctrine\DBAL\Driver\Middleware\AbstractDriverMiddleware;
+
+final class AutoCloseDriver extends AbstractDriverMiddleware
+{
+    public function __construct(
+        Driver $driver,
+        private \ArrayObject $connectionExpiries,
+        private readonly array $timeToLiveByConnection,
+        private readonly string $connectionName
```
Comment (dunglas) [inline src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php]:
```suggestion
        private readonly string $connectionName,
```

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/Listener/DoctrineConnectionListener.php [hunk 53]
```diff
@@ -0,0 +1,51 @@
...
+
+use Symfony\Component\DependencyInjection\ContainerInterface;
+use Symfony\Component\EventDispatcher\EventSubscriberInterface;
+use Symfony\Component\HttpKernel\Event\RequestEvent;
+use Symfony\Component\HttpKernel\KernelEvents;
+
+final class DoctrineConnectionListener implements EventSubscriberInterface
+{
+    /**
+     * @param \ArrayObject<string, int> $connectionExpiries
```
Comment (dunglas) [inline src/Symfony/Bridge/Doctrine/Middleware/AutoClose/Listener/DoctrineConnectionListener.php]:
```suggestion
     * @param \ArrayObject<string, int> $connectionExpires
```

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/Listener/DoctrineConnectionListener.php [hunk 54]
```diff
@@ -0,0 +1,51 @@
...
+     */
+    public function __construct(
+        private readonly \ArrayObject $connectionExpiries,
```
Comment (dunglas) [inline src/Symfony/Bridge/Doctrine/Middleware/AutoClose/Listener/DoctrineConnectionListener.php]:
```suggestion
        private readonly \ArrayObject $connectionExpires,
```

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/Listener/DoctrineConnectionListener.php [hunk 55]
```diff
@@ -0,0 +1,51 @@
...
+    ) {
+    }
+
+    public function onKernelRequest(RequestEvent $event): void
+    {
+        $connectionExpiries = $this->connectionExpiries->getIterator();
+
+        $timestamp = time();
+
+        foreach ($connectionExpiries as $name => $expiry) {
```
Comment (dunglas) [inline src/Symfony/Bridge/Doctrine/Middleware/AutoClose/Listener/DoctrineConnectionListener.php]:
```suggestion
        foreach ($connectionExpires as $name => $expiry) {
```

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/Listener/DoctrineConnectionListener.php [hunk 56]
```diff
@@ -0,0 +1,51 @@
...
+            if ($timestamp >= $expiry) {
+                $connection = $this->container->get(sprintf('doctrine.dbal.%s_connection', $name));
```
Comment (dunglas) [inline src/Symfony/Bridge/Doctrine/Middleware/AutoClose/Listener/DoctrineConnectionListener.php]:
```suggestion
                $connection = $this->container->get("doctrine.dbal.{$name}_connection");
```

Feel free to discard this micro-optimization if you want :)

**Review by dunglas — CHANGES_REQUESTED** [review]
Almost good, thank you very much for your abnegation in solving this problem :)

**Comment by alli83** [comment]
So should I move the middleware to the bridge rather than the bundle

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/Listener/DoctrineConnectionListener.php (hunk 56 above)
Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Middleware/AutoClose/Listener/DoctrineConnectionListener.php]: nah, I'm good with these optimisations! :)

**Comment by alli83** [comment]
@nicolas-grekas rebase 7.1?

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php [hunk 57]
```diff
@@ -0,0 +1,37 @@
...
+use Doctrine\DBAL\Driver;
+use Doctrine\DBAL\Driver\Connection as DriverConnection;
+use Doctrine\DBAL\Driver\Middleware\AbstractDriverMiddleware;
+
+final class AutoCloseDriver extends AbstractDriverMiddleware
+{
+    public function __construct(
+        Driver $driver,
+        private \ArrayObject $connexionExpire,
+        private readonly array $timeToLiveByConnection,
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php]:
```suggestion
        private readonly int $ttl,
```

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php [hunk 58]
```diff
@@ -0,0 +1,37 @@
...
+
+use Doctrine\DBAL\Driver;
+use Doctrine\DBAL\Driver\Connection as DriverConnection;
+use Doctrine\DBAL\Driver\Middleware\AbstractDriverMiddleware;
+
+final class AutoCloseDriver extends AbstractDriverMiddleware
+{
+    public function __construct(
+        Driver $driver,
+        private \ArrayObject $connexionExpire,
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php]: sorry @dunglas, using "expiry" was on purpose, that's the correct word here :)
```suggestion
        private \ArrayObject $connexionExpiries,
```

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php [hunk 59]
```diff
@@ -0,0 +1,37 @@
...
+        private readonly string $connectionName,
+    ) {
+        parent::__construct($driver);
+    }
+
+    public function connect(array $params): DriverConnection
+    {
+        $timestamp = time();
+        $connection = parent::connect($params);
+        $this->connexionExpire[$this->connectionName] = $timestamp + $this->timeToLiveByConnection[$this->connectionName];
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php]:
```suggestion
        $this->connexionExpire[$this->connectionName] = $timestamp + $this->ttl;
```

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/Listener/DoctrineConnectionListener.php [hunk 60]
```diff
@@ -0,0 +1,51 @@
...
+use Symfony\Component\HttpKernel\Event\RequestEvent;
+use Symfony\Component\HttpKernel\KernelEvents;
+
+final class DoctrineConnectionListener implements EventSubscriberInterface
+{
+    /**
+     * @param \ArrayObject<string, int> $connexionExpire
+     */
+    public function __construct(
+        private readonly \ArrayObject $connexionExpire,
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Middleware/AutoClose/Listener/DoctrineConnectionListener.php]:
```suggestion
        private readonly \ArrayObject $connexionExpiries,
```

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php [hunk 61]
```diff
@@ -0,0 +1,37 @@
...
+/*
+ * This file is part of the Symfony package.
+ *
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Bridge\Doctrine\Middleware\AutoClose;
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php]: What about "IdleConnection" instead of "AutoClose" everywhere? (sorry, naming things :) )

**Comment by nicolas-grekas** [comment]
> So should I move the middleware to the bridge rather than the bundle

That's not possible without first moving ConnectionNameAwareInterface to the bridge, but I'm not sure it's worth it. Good as is to me.

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/Listener/DoctrineConnectionListener.php (hunk 60 above)
Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Middleware/AutoClose/Listener/DoctrineConnectionListener.php]: 😂

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php (hunk 58 above)
Comment (dunglas) [reply src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php]: oops :)

Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php]: 😂

**Review by dunglas — APPROVED** [review]
LGTM!

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php (hunk 61 above)
Comment (dunglas) [reply src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php]: "GoneConnection", "LostConnection"?

The problem isn't that the connection is idle, but that the server closes the connection without notifying the client.
By the way, we'll have some docs to write because theoretically, this shouldn't happen if the client timeout is configured to a shorter value than the server timeout (unfortunately, this is rarely the case so this PR is definitely needed).

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php (hunk 57 above)
Comment (dunglas) [reply src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php]: Is it a good idea? In theory, the server timeout can be different depending on the connection (two different servers can have two different timeouts).

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php (hunk 61 above)
Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php]: the only thing we monitor is the idle time, so "idle" looks appropriate to me

File: src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php (hunk 57 above)
Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/Middleware/AutoClose/AutoCloseDriver.php]: drivers are instantiated per connection already ;)

**Review by greg0ire — APPROVED** [review]
:ok_hand:

File: src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Driver.php [hunk 62]
```diff
@@ -0,0 +1,37 @@
...
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Bridge\Doctrine\Middleware\IdleConnection;
+
+use Doctrine\DBAL\Driver as DbalDriver;
+use Doctrine\DBAL\Driver\Connection as DriverConnection;
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Driver.php]: :zipper_mouth_face: 
```suggestion
use Doctrine\DBAL\Driver as DriverInterface;
use Doctrine\DBAL\Driver\Connection as ConnectionInterface;
```

File: src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Driver.php [hunk 63]
```diff
@@ -0,0 +1,37 @@
...
+use Doctrine\DBAL\Driver\Middleware\AbstractDriverMiddleware;
+
+final class Driver extends AbstractDriverMiddleware
+{
+    public function __construct(
+        DbalDriver $driver,
+        private \ArrayObject $connexionExpire,
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Driver.php]:
```suggestion
        private \ArrayObject $connectionExpiries,
```

File: src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Driver.php [hunk 64]
```diff
@@ -0,0 +1,37 @@
...
+        private readonly string $connectionName,
+    ) {
+        parent::__construct($driver);
+    }
+
+    public function connect(array $params): DriverConnection
+    {
+        $timestamp = time();
+        $connection = parent::connect($params);
+        $this->connexionExpire[$this->connectionName] = $timestamp + $this->ttl;
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Driver.php]:
```suggestion
        $this->connectionExpiries[$this->connectionName] = $timestamp + $this->ttl;
```

File: src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Driver.php [hunk 65]
```diff
@@ -0,0 +1,37 @@
...
+    public function __construct(
+        DbalDriver $driver,
+        private \ArrayObject $connexionExpire,
+        private readonly int $ttl,
+        private readonly string $connectionName,
+    ) {
+        parent::__construct($driver);
+    }
+
+    public function connect(array $params): DriverConnection
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Driver.php]:
```suggestion
    public function connect(array $params): ConnectionInterface
```

File: src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Driver.php [hunk 66]
```diff
@@ -0,0 +1,37 @@
...
+namespace Symfony\Bridge\Doctrine\Middleware\IdleConnection;
+
+use Doctrine\DBAL\Driver as DbalDriver;
+use Doctrine\DBAL\Driver\Connection as DriverConnection;
+use Doctrine\DBAL\Driver\Middleware\AbstractDriverMiddleware;
+
+final class Driver extends AbstractDriverMiddleware
+{
+    public function __construct(
+        DbalDriver $driver,
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Driver.php]:
```suggestion
        DriverInterface $driver,
```

File: src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Listener.php [hunk 67]
```diff
@@ -0,0 +1,51 @@
...
+use Symfony\Component\HttpKernel\Event\RequestEvent;
+use Symfony\Component\HttpKernel\KernelEvents;
+
+final class Listener implements EventSubscriberInterface
+{
+    /**
+     * @param \ArrayObject<string, int> $connexionExpiries
+     */
+    public function __construct(
+        private readonly \ArrayObject $connexionExpiries,
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Listener.php]:
```suggestion
     * @param \ArrayObject<string, int> $connectionExpiries
     */
    public function __construct(
        private readonly \ArrayObject $connectionExpiries,
```

File: src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Listener.php [hunk 68]
```diff
@@ -0,0 +1,51 @@
...
+    {
+        $connexionExpiries = $this->connexionExpiries->getIterator();
+
+        $timestamp = time();
+
+        foreach ($connexionExpiries as $name => $expiry) {
+            if ($timestamp >= $expiry) {
+                $connection = $this->container->get("doctrine.dbal.{$name}_connection");
+                $connection->close();
+                $connexionExpiries->offsetUnset($name);
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Listener.php]:
```suggestion
        $connexionExpiries = $this->connexionExpiries->getIterator();

        $timestamp = time();

        foreach ($connectionExpiries as $name => $expiry) {
            if ($timestamp >= $expiry) {
                try {
                    $connection = $this->container->get("doctrine.dbal.{$name}_connection");
                    $connection->close();
                } catch (\Exception) {
                    // ignore exceptions to remain fail-safe
                }
                $connectionExpiries->offsetUnset($name);
```

File: src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Listener.php (hunk 67 above)
Comment (alli83) [reply src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Listener.php]: Where is the difference?

Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Listener.php]: "x" vs "ct"

**Review by nicolas-grekas — COMMENTED** [review]
Nice and clean now :)
Will be perfect with a few test cases :)

**Comment by alli83** [comment]
I'm working on the tests :)

File: src/Symfony/Bridge/Doctrine/Tests/Middleware/IdleConnection/DriverTest.php [hunk 69]
```diff
@@ -0,0 +1,39 @@
...
+        $driverMock->expects($this->once())
+            ->method('connect')
+            ->willReturn($connectionMock);
+
+        $connectionExpiries = new \ArrayObject();
+
+        $driver = new Driver($driverMock, $connectionExpiries, 60, 'default');
+        $connection = $driver->connect([]);
+
+        $this->assertInstanceOf(ConnectionInterface::class, $connection);
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Tests/Middleware/IdleConnection/DriverTest.php]:
```suggestion
        $this->assertSame($connectionMock, $connection);
```

File: src/Symfony/Bridge/Doctrine/Tests/Middleware/IdleConnection/DriverTest.php [hunk 70]
```diff
@@ -0,0 +1,39 @@
...
+            ->willReturn($connectionMock);
+
+        $connectionExpiries = new \ArrayObject();
+
+        $driver = new Driver($driverMock, $connectionExpiries, 60, 'default');
+        $connection = $driver->connect([]);
+
+        $this->assertSame($connectionMock, $connection);
+        $this->assertArrayHasKey('default', $connectionExpiries);
+        $this->assertEquals(time() + 60, $connectionExpiries['default']);
```
Comment (OskarStark) [inline src/Symfony/Bridge/Doctrine/Tests/Middleware/IdleConnection/DriverTest.php]:
```suggestion
        $this->assertSame(time() + 60, $connectionExpiries['default']);
```

File: src/Symfony/Bridge/Doctrine/Tests/Middleware/IdleConnection/DriverTest.php [hunk 71]
```diff
@@ -0,0 +1,39 @@
...
+namespace Symfony\Bridge\Doctrine\Tests\Middleware\IdleConnection;
+
+use Doctrine\DBAL\Driver as DriverInterface;
+use Doctrine\DBAL\Driver\Connection as ConnectionInterface;
+use PHPUnit\Framework\TestCase;
+use Symfony\Bridge\Doctrine\Middleware\IdleConnection\Driver;
+
+class DriverTest extends TestCase
+{
+    public function testConnect()
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Tests/Middleware/IdleConnection/DriverTest.php:24]:
```suggestion
    /**
     * @group time-sensitive
     */
    public function testConnect()
```

and also list the namespace in src/Symfony/Bridge/Doctrine/phpunit.xml.dist and in the root phpunit.xml.dist

File: src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Listener.php [hunk 72]
```diff
@@ -0,0 +1,54 @@
...
+        foreach ($this->connectionExpiries as $name => $expiry) {
+            if ($timestamp >= $expiry) {
+                try {
+                    $connection = $this->container->get("doctrine.dbal.{$name}_connection");
+                    $connection->close();
+                } catch (\Exception) {
+                    // ignore exceptions to remain fail-safe
+                }
+
+                $this->connectionExpiries->offsetUnset($name);
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/Middleware/IdleConnection/Listener.php]: let's move this one before the try/catch to be consistent with the fail-safe strategy

**Review by nicolas-grekas — APPROVED** [review]
I force-pushed to fix my last comments :)

**Review by dunglas — APPROVED** [review]
🎉

**Comment by nicolas-grekas** [comment]
Thank you @alli83.

File: src/Symfony/Bridge/Doctrine/phpunit.xml.dist [hunk 73]
```diff
@@ -33,7 +33,12 @@
         <listener class="Symfony\Bridge\PhpUnit\SymfonyTestsListener">
             <arguments>
                 <array>
-                    <element key="time-sensitive"><string>Symfony\Bridge\Doctrine\Middleware\Debug</string></element>
+                    <element key="time-sensitive">
+                        <array>
+                            <element key="0"><string>Symfony\Bridge\Doctrine\Middleware\Debug</string></element>
+                            <element key="1"><string>Symfony\Bridge\Doctrine\Middleware\Debug</string></element>
```
Comment (andersonamuller) [inline src/Symfony/Bridge/Doctrine/phpunit.xml.dist:39]: @nicolas-grekas Isn't `Symfony\Bridge\Doctrine\Middleware\IdleConnection`?

Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/phpunit.xml.dist:39]: Oops, PR welcome

Comment (xabbuh) [reply src/Symfony/Bridge/Doctrine/phpunit.xml.dist:39]: fixed in 65ccca0758

File: src/Symfony/Bridge/Doctrine/Tests/Middleware/IdleConnection/ListenerTest.php [hunk 74]
```diff
@@ -0,0 +1,43 @@
...
+use Symfony\Component\HttpKernel\Event\RequestEvent;
+
+class ListenerTest extends TestCase
+{
+    public function testOnKernelRequest()
+    {
+        $containerMock = $this->createMock(ContainerInterface::class);
+        $connectionExpiries = new \ArrayObject(['connectionone' => time() - 30, 'connectiontwo' => time() + 40]);
+
+        $connectionOneMock = $this->getMockBuilder(ConnectionInterface::class)
```
Comment (calinblaga) [inline src/Symfony/Bridge/Doctrine/Tests/Middleware/IdleConnection/ListenerTest.php:27]: You can just do ```$this->createMock(ConnectionInterface::class)``` to spare two lines of code.

Comment (greg0ire) [reply src/Symfony/Bridge/Doctrine/Tests/Middleware/IdleConnection/ListenerTest.php:27]: Please don't comment on old, already merged PRs. If you feel strongly about this, send a PR instead.

Comment (calinblaga) [reply src/Symfony/Bridge/Doctrine/Tests/Middleware/IdleConnection/ListenerTest.php:27]: Sure, was just a general suggestion, though.

**Comment by jsamouh** [comment]
possible to backport that into 6.X ? cc @fabpot

**Comment by derrabus** [comment]
No, we don't backport features.

**Comment by jsamouh** [comment]
well, does not seem to be a feature to me as it fix the error connection for long running runtime whis is our case right now in production with frankenPHP worker mode, cc @dunglas

**Comment by greg0ire** [comment]
We understand you are having an issue you would love to solve, but this listener is a new Symfony feature improving your experience with other software (Doctrine + frankenPHP). There was no issue with Symfony, so it's not a bugfix, and it really shows in the diff, which consists in new classes. It also shows in the changelog: "Add support for auto-closing idle connections"

Please stop pinging busy people that have bigger fish to fry and start work on upgrading to Symfony 7.1. If that's too much work, you can always copy paste the classes in this PR in your project, and wire them up.

**Comment by jsamouh** [comment]
I dont agree but if you say so
thks for the response !
Good luck
