### PR TITLE
[TypeInfo] Fix PHPDoc resolving of union with mixed

### LINKED ISSUE #59223: Compatibility issue with Symfony 7.2.1: Symfony\Component\TypeInfo\Type::union(): Return value must be of type ... error
### Symfony version(s) affected

7.2.1

### Description

After upgrading Symfony to version 7.2.1, my project stopped working with the following error:
Symfony\Component\TypeInfo\Type::union(): Return value must be of type Symfony\Component\TypeInfo\Type\UnionType, Symfony\Component\TypeInfo\Type\BuiltinType returned

The issue seems to be related to changes introduced in Symfony 7.2, specifically in the redesigned TypeInfo component, as explained in this blog post: [New in Symfony 7.2: Redesigned TypeInfo Component](https://symfony.com/blog/new-in-symfony-7-2-redesigned-typeinfo-component).

### How to reproduce

Steps to Reproduce:

Use Symfony 7.2.1.
Open any application page.
Expected Behavior:
The application page should be processed normally without any errors.

Actual Behavior:
The error mentioned above is thrown, and the application fails to start.
http://prntscr.com/Q8XV-Y0k2tzy

Steps Taken:
Updated all dependencies to their latest versions.
Cleared the Symfony cache (php bin/console cache:clear).
Verified that the error disappears when downgrading Symfony to version 7.2.1.

Please let me know if further details or logs are needed.

### Possible Solution

_No response_

### Additional Context

_No response_

### LINKED ISSUE #59258: [TypeInfo] Cannot create union with "mixed" standalone type.
### Symfony version(s) affected

7.2.1

### Description

When (indirectly) upgrading `symfony/type-info` from `7.1.8` to `7.2.1` (due to `symfony/type-info: "^7.1" `in `symfony/property-info`), it gives an error regarding `UnionType`:

```php
In UnionType.php line 54:

  [Symfony\Component\TypeInfo\Exception\InvalidArgumentException]
  Cannot create union with "mixed" standalone type.

Exception trace:
  at /app/vendor/symfony/type-info/Type/UnionType.php:54
 Symfony\Component\TypeInfo\Type\UnionType->__construct() at /app/vendor/symfony/type-info/TypeFactoryTrait.php:296
 Symfony\Component\TypeInfo\Type::union() at /app/vendor/symfony/type-info/TypeResolver/StringTypeResolver.php:226
 Symfony\Component\TypeInfo\TypeResolver\StringTypeResolver->getTypeFromNode() at /app/vendor/symfony/type-info/TypeResolver/StringTypeResolver.php:192
 Symfony\Component\TypeInfo\TypeResolver\StringTypeResolver->Symfony\Component\TypeInfo\TypeResolver\{closure}() at n/a:n/a
 array_map() at /app/vendor/symfony/type-info/TypeResolver/StringTypeResolver.php:192
 Symfony\Component\TypeInfo\TypeResolver\StringTypeResolver->getTypeFromNode() at /app/vendor/symfony/type-info/TypeResolver/StringTypeResolver.php:86
 Symfony\Component\TypeInfo\TypeResolver\StringTypeResolver->resolve() at /app/vendor/symfony/property-info/Extractor/PhpStanExtractor.php:217
 Symfony\Component\PropertyInfo\Extractor\PhpStanExtractor->getType() at /app/vendor/symfony/property-info/PropertyInfoExtractor.php:96
 Symfony\Component\PropertyInfo\PropertyInfoExtractor->extract() at /app/vendor/symfony/property-info/PropertyInfoExtractor.php:62
 Symfony\Component\PropertyInfo\PropertyInfoExtractor->getType() at /app/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:992
 Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->getPropertyType() at /app/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:962
 Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->getType() at /app/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:929
 Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denormalizeParameter() at /app/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php:374
 Symfony\Component\Serializer\Normalizer\AbstractNormalizer->instantiateObject() at /app/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:243
 Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->instantiateObject() at /app/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:339
 Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denormalize() at /app/vendor/guikingone/scheduler-bundle/src/Serializer/TaskNormalizer.php:289
 SchedulerBundle\Serializer\TaskNormalizer->denormalize() at /app/vendor/symfony/serializer/Serializer.php:238
 Symfony\Component\Serializer\Serializer->denormalize() at /app/vendor/symfony/serializer/Serializer.php:143
 Symfony\Component\Serializer\Serializer->deserialize() at /app/vendor/guikingone/scheduler-bundle/src/Transport/CacheTransport.php:70
 SchedulerBundle\Transport\CacheTransport->get() at /app/vendor/guikingone/scheduler-bundle/src/Scheduler.php:76
 SchedulerBundle\Scheduler->schedule() at /app/var/cache/dev/ContainerSU4h0yA/App_KernelDevDebugContainer.php:24286
 ContainerSU4h0yA\App_KernelDevDebugContainer::getSchedulerService() at /app/var/cache/dev/ContainerSU4h0yA/App_KernelDevDebugContainer.php:13641
 ContainerSU4h0yA\App_KernelDevDebugContainer::getConsumeTasksCommandService() at /app/var/cache/dev/ContainerSU4h0yA/App_KernelDevDebugContainer.php:5245
 ContainerSU4h0yA\App_KernelDevDebugContainer::ContainerSU4h0yA\{closure}() at /app/vendor/symfony/console/Command/LazyCommand.php:189
 Symfony\Component\Console\Command\LazyCommand->getCommand() at /app/vendor/symfony/console/Application.php:338
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/framework-bundle/Console/Application.php:77
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->run() at /app/bin/console:43
```

### How to reproduce

I'm using [`guikingone/scheduler-bundle`](https://github.com/Guikingone/SchedulerBundle), and after debugging in the `PropertyInfoExtractor`, I've found that it might be related to the annotation for the `$options` there:

```php
    /**
     * @var array<string, mixed|bool|string|float|int|DateTimeImmutable|DateTimeZone|DateInterval|NotificationTaskBag|null>
     */
    protected array $options = [];
```
https://github.com/Guikingone/SchedulerBundle/blob/b247c1630c365600cfd4916cf16b1452ce00ad84/src/Task/AbstractTask.php#L39-L41

### Possible Solution

_No response_

### Additional Context

Related: https://github.com/symfony/type-info/commit/f8ee4b94c3d0169e14eed12391d0c5ef08362225
Workaround: use `7.1.8`; `composer require symfony/type-info:7.1.*`

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59258, Fix #59223
| License       | MIT

Resolve "invalid" union PHPDoc with `mixed` standalone type as `mixed` type.

### CODE REVIEW

**Comment by xabbuh** [comment]
@mtarld FYI, I have added #59223 to the list of issues this PR is supposed to fix

**Review by xabbuh — APPROVED** [review]

File: src/Symfony/Component/TypeInfo/TypeResolver/StringTypeResolver.php [hunk 1]
```diff
@@ -223,7 +223,17 @@ private function getTypeFromNode(TypeNode $node, ?TypeContext $typeContext): Typ
...
         if ($node instanceof UnionTypeNode) {
-            return Type::union(...array_map(fn (TypeNode $t): Type => $this->getTypeFromNode($t, $typeContext), $node->types));
+            $types = [];
+
+            foreach ($node->types as $nodeType) {
+                $types[] = $type = $this->getTypeFromNode($nodeType, $typeContext);
+
+                if ($type instanceof BuiltinType && TypeIdentifier::MIXED === $type->getTypeIdentifier()) {
+                    return Type::mixed();
+                }
```
Comment (Kocal) [inline src/Symfony/Component/TypeInfo/TypeResolver/StringTypeResolver.php]: You can early return no?
```suggestion
                if ($type instanceof BuiltinType && TypeIdentifier::MIXED === $type->getTypeIdentifier()) {
                    return Type::mixed();
                }
                
                $types[] = $type = $this->getTypeFromNode($nodeType, $typeContext);
```

Comment (mtarld) [reply src/Symfony/Component/TypeInfo/TypeResolver/StringTypeResolver.php]: The `$type` must be computed (thanks to `getTypeFromNode`) before the `if`. Otherwise, it won't return a mixed if the last type is the mixed one.

File: src/Symfony/Component/TypeInfo/TypeResolver/StringTypeResolver.php [hunk 2]
```diff
@@ -223,7 +223,17 @@ private function getTypeFromNode(TypeNode $node, ?TypeContext $typeContext): Typ
         }
 
         if ($node instanceof UnionTypeNode) {
-            return Type::union(...array_map(fn (TypeNode $t): Type => $this->getTypeFromNode($t, $typeContext), $node->types));
+            $types = [];
+
+            foreach ($node->types as $nodeType) {
+                $types[] = $type = $this->getTypeFromNode($nodeType, $typeContext);
```
Comment (stof) [inline src/Symfony/Component/TypeInfo/TypeResolver/StringTypeResolver.php]: I suggest moving `$types[] = $type;` after the `if`, to make the code easier to understand (not putting `mixed` at all in the list of types)

File: src/Symfony/Component/TypeInfo/Tests/TypeResolver/StringTypeResolverTest.php [hunk 3]
```diff
@@ -155,6 +155,7 @@ public static function resolveDataProvider(): iterable
 
         // union
         yield [Type::union(Type::int(), Type::string()), 'int|string'];
+        yield [Type::mixed(), 'int|mixed'];
```
Comment (stof) [inline src/Symfony/Component/TypeInfo/Tests/TypeResolver/StringTypeResolverTest.php:158]: maybe test both `int|mixed` and `mixed|int`, to avoid issues where the first or last type would not work (see the discussion comment)

File: src/Symfony/Component/TypeInfo/TypeResolver/StringTypeResolver.php (hunk 1 above)
Comment (Kocal) [reply src/Symfony/Component/TypeInfo/TypeResolver/StringTypeResolver.php]: Ah, didn't see this subtil `= $type =`

**Review by derrabus — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you @mtarld.
