### PR TITLE
[Config] Fix using null values with config builders

### LINKED ISSUE #45782: FrameworkConfig::router()::strictRequirements(null): final value is true
### Symfony version(s) affected

6.0.5

### Description

When i change yaml configuration file format to PHP in `config/packages` directory, i have this code for `routing.php`:

```
return static function (FrameworkConfig $config): void {
    $config
        ->router()
        ->strictRequirements(null);
};
```

But when i see `var/cache/devSymfony/Framework/RouterConfig.php`, i have this code in `toArray()`:
```
        if (null !== $this->strictRequirements) {
            $output['strict_requirements'] = $this->strictRequirements;
        }
```

Problem: final value will not be `null` as configured and expected, but `true`, because it's the default value.
I can configure it in yaml, it works, and it's the default configuration when we create a project:

```
framework:
    router:
        strict_requirements: null
```

### How to reproduce

Create a new project, then add in `src/Kernel.php` to read PHP configuration files:

```
    private function configureContainer(
        ContainerConfigurator $container,
        LoaderInterface $loader,
        ContainerBuilder $builder
    ): void {
        $configDir = $this->getConfigDir();

        $container->import($configDir.'/{packages}/*.yaml');
        $container->import($configDir.'/{packages}/'.$this->environment.'/*.yaml');

        $container->import($configDir.'/{packages}/*.php');
        $container->import($configDir.'/{packages}/'.$this->environment.'/*.php');

        if (is_file($configDir.'/services.yaml')) {
            $container->import($configDir.'/services.yaml');
            $container->import($configDir.'/{services}_'.$this->environment.'.yaml');
        } else {
            $container->import($configDir.'/{services}.php');
        }
    }
```

Another little problem: in the documentation (https://symfony.com/doc/current/configuration.html#using-php-configbuilders) we may think PHP configuration files are always readed, but that's not the case, we need to modify the Kernel to take this files into account.

### Possible Solution

Allow passing `null` when configuration allow this value?

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45782
| License       | MIT
| Doc PR        | -

The generated config builders will no longer discard `null` values.

### CODE REVIEW

File: src/Symfony/Component/Config/Tests/Builder/Fixtures/AddToList/Symfony/Config/AddToList/Messenger/ReceivingConfig.php [hunk 1]
```diff
@@ -8,12 +8,13 @@
...
 
 /**
- * This class is automatically generated to help creating config.
+ * This class is automatically generated to help in creating a config.
  */
 class ReceivingConfig 
 {
     private $priority;
     private $color;
+    private $_usedProperties = [];
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Config/Tests/Builder/Fixtures/AddToList/Symfony/Config/AddToList/Messenger/ReceivingConfig.php:17]: we don't use underscores in property names

Comment (HypeMC) [reply src/Symfony/Component/Config/Tests/Builder/Fixtures/AddToList/Symfony/Config/AddToList/Messenger/ReceivingConfig.php:17]: @nicolas-grekas This is to avoid collision with configuration proprieties (`->scalarNode('used_properties')`), same as with `_extraKeys`.

Sorry, I accidentally resolved this.

Comment (nicolas-grekas) [reply src/Symfony/Component/Config/Tests/Builder/Fixtures/AddToList/Symfony/Config/AddToList/Messenger/ReceivingConfig.php:17]: Got it, thanks for the explanation.

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Config/Tests/Builder/Fixtures/PrimitiveTypes/Symfony/Config/PrimitiveTypesConfig.php [hunk 2]
```diff
@@ -87,30 +107,41 @@ public function __construct(array $value = [])
...
             unset($value['integer_node']);
         }
     
         if (isset($value['scalar_node'])) {
+            $this->_usedProperties['scalarNode'] = true;
             $this->scalarNode = $value['scalar_node'];
             unset($value['scalar_node']);
         }
     
+        if (isset($value['scalar_node_with_default'])) {
```
Comment (stof) [inline src/Symfony/Component/Config/Tests/Builder/Fixtures/PrimitiveTypes/Symfony/Config/PrimitiveTypesConfig.php]: shouldn't this use `array_key_exists` to allow passing `null` ?

Comment (HypeMC) [reply src/Symfony/Component/Config/Tests/Builder/Fixtures/PrimitiveTypes/Symfony/Config/PrimitiveTypesConfig.php]: @stof Yep, missed that one, tnx. Fixed https://github.com/symfony/symfony/compare/e214761c573ecc980b5d1b5e3c4dff12f8a6933d..1264225f4ebc535deec491737b70d9bc1d84dc98

**Comment by nicolas-grekas** [comment]
Thank you @HypeMC.
