### PR TITLE
[HttpClient] Fix `ScopingHttpClient` to always pass `base_uri` as `string` instead of parsed `array`

### LINKED ISSUE #62697: [HttpClient] Broken base_uri when using scoping & retryable client together
### Symfony version(s) affected

7.4.1

### Description

I am having this scoped client configured:
```yaml
framework:
    http_client:
        default_options:
            retry_failed:
                http_codes: [0, 429, 404, 500, 502, 503, 504]
                max_retries: 3
                # ...

        scoped_clients:
            foo.client:
                base_uri: 'https://foo.example.com/app'
```

(Please note the `/app` suffix, I cannot reproduce the issue without.)

Since version 7.4.1, when I would do something like `$client->request('GET', '/foo')` and the endpoint returns e.g. status 503 (and the `RetryableHttpClient` jumps in), I get:
```
PHP Fatal error:  Uncaught Symfony\Component\HttpClient\Exception\InvalidArgumentException: Invalid "base_uri" option: host or scheme is missing in "/app". in /Users/niklas/code/my_project/vendor/symfony/http-client/HttpClientTrait.php:577
```

<details>
  <summary>Stack trace</summary>
  
```
#0 /Users/niklas/code/my_project/vendor/symfony/http-client/HttpClientTrait.php(178): Symfony\Component\HttpClient\CurlHttpClient::resolveUrl(Array, Array, Array)
#1 /Users/niklas/code/my_project/vendor/symfony/http-client/CurlHttpClient.php(91): Symfony\Component\HttpClient\CurlHttpClient::prepareRequest('GET', Array, Array, Array)
#2 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/AsyncContext.php(173): Symfony\Component\HttpClient\CurlHttpClient->request('GET', 'https://foo.exa...', Array)
#3 /Users/niklas/code/my_project/vendor/symfony/http-client/RetryableHttpClient.php(157): Symfony\Component\HttpClient\Response\AsyncContext->replaceRequest('GET', 'https://foo.exa...', Array)
#4 [internal function]: Symfony\Component\HttpClient\RetryableHttpClient->{closure:Symfony\Component\HttpClient\RetryableHttpClient::request():83}(Object(Symfony\Component\HttpClient\Chunk\FirstChunk), Object(Symfony\Component\HttpClient\Response\AsyncContext))
#5 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/AsyncResponse.php(357): Generator->valid()
#6 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/AsyncResponse.php(343): Symfony\Component\HttpClient\Response\AsyncResponse::passthruStream(Object(Symfony\Component\HttpClient\Response\CurlResponse), Object(Symfony\Component\HttpClient\Response\AsyncResponse), Object(SplObjectStorage))
#7 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/AsyncResponse.php(292): Symfony\Component\HttpClient\Response\AsyncResponse::passthru(Object(Symfony\Component\HttpClient\CurlHttpClient), Object(Symfony\Component\HttpClient\Response\AsyncResponse), Object(Symfony\Component\HttpClient\Chunk\FirstChunk), Object(SplObjectStorage))
#8 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/AsyncResponse.php(66): Symfony\Component\HttpClient\Response\AsyncResponse::stream(Array, -0.0)
#9 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/CommonResponseTrait.php(144): Symfony\Component\HttpClient\Response\AsyncResponse::{closure:Symfony\Component\HttpClient\Response\AsyncResponse::__construct():60}(Object(Symfony\Component\HttpClient\Response\AsyncResponse), -0.0)
#10 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/AsyncResponse.php(97): Symfony\Component\HttpClient\Response\AsyncResponse::initialize(Object(Symfony\Component\HttpClient\Response\AsyncResponse))
#11 /Users/niklas/code/my_project/demo.php(46): Symfony\Component\HttpClient\Response\AsyncResponse->getStatusCode()
#12 {main}

Next Symfony\Component\HttpClient\Exception\TransportException: Invalid "base_uri" option: host or scheme is missing in "/app". in /Users/niklas/code/my_project/vendor/symfony/http-client/Chunk/ErrorChunk.php:46
Stack trace:
#0 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/AsyncResponse.php(67): Symfony\Component\HttpClient\Chunk\ErrorChunk->isTimeout()
#1 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/CommonResponseTrait.php(144): Symfony\Component\HttpClient\Response\AsyncResponse::{closure:Symfony\Component\HttpClient\Response\AsyncResponse::__construct():60}(Object(Symfony\Component\HttpClient\Response\AsyncResponse), -0.0)
#2 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/AsyncResponse.php(97): Symfony\Component\HttpClient\Response\AsyncResponse::initialize(Object(Symfony\Component\HttpClient\Response\AsyncResponse))
#3 /Users/niklas/code/my_project/demo.php(46): Symfony\Component\HttpClient\Response\AsyncResponse->getStatusCode()
#4 {main}
  thrown in /Users/niklas/code/my_project/vendor/symfony/http-client/Chunk/ErrorChunk.php on line 46

Fatal error: Uncaught Symfony\Component\HttpClient\Exception\InvalidArgumentException: Invalid "base_uri" option: host or scheme is missing in "/app". in /Users/niklas/code/my_project/vendor/symfony/http-client/HttpClientTrait.php:577
Stack trace:
#0 /Users/niklas/code/my_project/vendor/symfony/http-client/HttpClientTrait.php(178): Symfony\Component\HttpClient\CurlHttpClient::resolveUrl(Array, Array, Array)
#1 /Users/niklas/code/my_project/vendor/symfony/http-client/CurlHttpClient.php(91): Symfony\Component\HttpClient\CurlHttpClient::prepareRequest('GET', Array, Array, Array)
#2 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/AsyncContext.php(173): Symfony\Component\HttpClient\CurlHttpClient->request('GET', 'https://foo.exa...', Array)
#3 /Users/niklas/code/my_project/vendor/symfony/http-client/RetryableHttpClient.php(157): Symfony\Component\HttpClient\Response\AsyncContext->replaceRequest('GET', 'https://foo.exa...', Array)
#4 [internal function]: Symfony\Component\HttpClient\RetryableHttpClient->{closure:Symfony\Component\HttpClient\RetryableHttpClient::request():83}(Object(Symfony\Component\HttpClient\Chunk\FirstChunk), Object(Symfony\Component\HttpClient\Response\AsyncContext))
#5 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/AsyncResponse.php(357): Generator->valid()
#6 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/AsyncResponse.php(343): Symfony\Component\HttpClient\Response\AsyncResponse::passthruStream(Object(Symfony\Component\HttpClient\Response\CurlResponse), Object(Symfony\Component\HttpClient\Response\AsyncResponse), Object(SplObjectStorage))
#7 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/AsyncResponse.php(292): Symfony\Component\HttpClient\Response\AsyncResponse::passthru(Object(Symfony\Component\HttpClient\CurlHttpClient), Object(Symfony\Component\HttpClient\Response\AsyncResponse), Object(Symfony\Component\HttpClient\Chunk\FirstChunk), Object(SplObjectStorage))
#8 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/AsyncResponse.php(66): Symfony\Component\HttpClient\Response\AsyncResponse::stream(Array, -0.0)
#9 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/CommonResponseTrait.php(144): Symfony\Component\HttpClient\Response\AsyncResponse::{closure:Symfony\Component\HttpClient\Response\AsyncResponse::__construct():60}(Object(Symfony\Component\HttpClient\Response\AsyncResponse), -0.0)
#10 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/AsyncResponse.php(97): Symfony\Component\HttpClient\Response\AsyncResponse::initialize(Object(Symfony\Component\HttpClient\Response\AsyncResponse))
#11 /Users/niklas/code/my_project/demo.php(46): Symfony\Component\HttpClient\Response\AsyncResponse->getStatusCode()
#12 {main}

Next Symfony\Component\HttpClient\Exception\TransportException: Invalid "base_uri" option: host or scheme is missing in "/app". in /Users/niklas/code/my_project/vendor/symfony/http-client/Chunk/ErrorChunk.php:46
Stack trace:
#0 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/AsyncResponse.php(67): Symfony\Component\HttpClient\Chunk\ErrorChunk->isTimeout()
#1 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/CommonResponseTrait.php(144): Symfony\Component\HttpClient\Response\AsyncResponse::{closure:Symfony\Component\HttpClient\Response\AsyncResponse::__construct():60}(Object(Symfony\Component\HttpClient\Response\AsyncResponse), -0.0)
#2 /Users/niklas/code/my_project/vendor/symfony/http-client/Response/AsyncResponse.php(97): Symfony\Component\HttpClient\Response\AsyncResponse::initialize(Object(Symfony\Component\HttpClient\Response\AsyncResponse))
#3 /Users/niklas/code/my_project/demo.php(46): Symfony\Component\HttpClient\Response\AsyncResponse->getStatusCode()
#4 {main}
  thrown in /Users/niklas/code/my_project/vendor/symfony/http-client/Chunk/ErrorChunk.php on line 46
```
  
</details>

### How to reproduce

```php
<?php
// First, run "composer require symfony/http-client"
// Then, execute this file:

declare(strict_types=1);

use Symfony\Component\HttpClient\HttpClient;
use Symfony\Component\HttpClient\Retry\GenericRetryStrategy;
use Symfony\Component\HttpClient\RetryableHttpClient;
use Symfony\Component\HttpClient\ScopingHttpClient;
use Symfony\Component\HttpClient\UriTemplateHttpClient;

require_once __DIR__.'/vendor/autoload.php';

$client = new UriTemplateHttpClient(
    ScopingHttpClient::forBaseUri(
        new RetryableHttpClient(
            HttpClient::create(),
            new GenericRetryStrategy([0, 429, 500, 502, 503, 504], 1000, 3, 5000, 0.3),
            3,
        ),
        'https://foo.example.com/app',
    ),
);

echo $client->request('GET', '/foo')->getStatusCode();
echo "\n";
```

### Possible Solution

_No response_

### Additional Context

Prior to #62652, this is how my HTTP client has been composed (simplified):
```php
$client = new RetryableHttpClient(
    ScopingHttpClient::forBaseUri(
        new UriTemplateHttpClient(HttpClient::create()),
        'https://foo.example.com/app',
    ),
    new GenericRetryStrategy([0, 429, 500, 502, 503, 504], 1000, 3, 5000, 0.3),
    3,
);
```

Now, it looks like this:
```php
$client = new UriTemplateHttpClient(
    ScopingHttpClient::forBaseUri(
        new RetryableHttpClient(
            HttpClient::create(),
            new GenericRetryStrategy([0, 429, 500, 502, 503, 504], 1000, 3, 5000, 0.3),
            3,
        ),
        'https://foo.example.com/app',
    ),
);
```

### PR DESCRIPTION
**Pull request by santysisi**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62697
| License       | MIT

### Problem
* `ScopingHttpClient` parsed the `base_uri` into an `array` (scheme, path, query, etc.).
* When passing this parsed value to a decorated client such as `RetryableHttpClient`, it caused errors.
* According to the `HttpClientInterface` in Symfony Contracts, `base_uri` [must be a string](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Contracts/HttpClient/HttpClientInterface.php#L45)

### Solution
* Updated `ScopingHttpClient` so it always forwards `base_uri` as a `string`, not as a parsed array.
* The change is applied for all decorated clients, not only `RetryableHttpClient`, since sending an `array` was not compliant with the `HttpClientInterface` comment.

### Additional Notes
Originally, the idea was to apply this fix only when the decorated client was `RetryableHttpClient` and later add full support for parsed `base_uri` for `RetryableHttpClient` in version 8.1.
However, after reviewing the `HttpClientInterface`, it became clear that sending a parsed `array` for `base_uri` was incorrect.
Therefore, the behavior is now corrected universally.

### CODE REVIEW

File: src/Symfony/Component/HttpClient/ScopingHttpClient.php [hunk 1]
```diff
@@ -85,6 +85,10 @@ public function request(string $method, string $url, array $options = []): Respo
             }
         }
 
+        if (\is_array($options['base_uri'] ?? null)) {
+            $options['base_uri'] = $this->unparseUrl($options['base_uri']);
+        }
```
Comment (santysisi) [inline src/Symfony/Component/HttpClient/ScopingHttpClient.php]: I’m converting the URL back to a `string` because we currently allow passing `base_uri` as either a `string` or an `array`.  
Ideally ( i think ), we should stop accepting `arrays` for `base_uri`, but removing that support in a patch or minor version would be a breaking change.

**Comment by santysisi** [comment]
status: needs work
I think there are some issues
I will see it again today in the night

**Comment by santysisi** [comment]
status: needs review

**Review by nicolas-grekas — APPROVED** [review]
I went a little bit further and I'm now unsetting the option when resolving URLs.
The code was able to cope with a parsed array instead of a string, but this conflicted with RetryableHttpClient's expectation and was also not documented as a valid type for the option.

**Comment by nicolas-grekas** [comment]
Thank you @santysisi.

**Comment by ngrie** [comment]
Thanks to both of you for fixing this 🙏
