### PR TITLE
[Console] Table counts wrong number of padding symbols in `renderCell()` method when cell contain unicode variant selector

### LINKED ISSUE #60038: Symfony\Component\Console\Helper\Table counts wrong number of padding symbols in method renderCell(..)
### Symfony version(s) affected

7.2

### Description

When rendering a table in console and use emojis then width of columns could be wrong calculated.

### How to reproduce

Use any emoji with variant selector (U+FE0F, U+FE0E) in cell output. For example ❄️

### Possible Solution

Don't count number of variant selector symbols when counting padding for multi-byte strings.
```php
private function renderCell(/* .. */): string  {
// ...
        if (false !== $encoding = mb_detect_encoding($cell, null, true)) {
            $width += \strlen($cell) - mb_strwidth(str_replace(["\xef\xb8\x8f", "\xef\xb8\x8e", ], "", $cell), $encoding);
        }
```

### Additional Context

Image

### PR DESCRIPTION
**Pull request by vladimir-vv**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? |no
| Issues        | Fix #60038
| License       | MIT

When rendering a table in console and use emojis then width of columns could be wrong calculated.

### CODE REVIEW

**Comment by fabpot** [comment]
@vladimir-vv Can you add some unit tests that would cover this fix?

**Comment by vladimir-vv** [comment]
> @vladimir-vv Can you add some unit tests that would cover this fix?

Ok.
The testcase has been added.

**Comment by xabbuh** [comment]
@vladimir-vv Can you please rebase here to re-trigger the CI?

File: src/Symfony/Component/Console/Helper/Table.php [hunk 1]
```diff
@@ -565,7 +565,7 @@ private function renderCell(array $row, int $column, string $cellFormat): string
 
         // str_pad won't work properly with multi-byte strings, we need to fix the padding
         if (false !== $encoding = mb_detect_encoding($cell, null, true)) {
-            $width += \strlen($cell) - mb_strwidth($cell, $encoding);
+            $width += \strlen($cell) - mb_strwidth($cell, $encoding) + substr_count($cell, "\xef\xb8\x8f") + substr_count($cell, "\xef\xb8\x8e");
```
Comment (xabbuh) [inline src/Symfony/Component/Console/Helper/Table.php]: What exactly does the unicode sequence `\xef\xb8\x8e` refer to?

Comment (vladimir-vv) [reply src/Symfony/Component/Console/Helper/Table.php]: These U+FE0F, U+FE0E selectors are used to display emoji with color or monochrome. As I can see usually the U+FE0E selector is skipped.
Example with snowflake:
U+2744	❄	e2 9d 84
U+2744	❄	e2 9d 84 ef b8 8e
U+2744	❄️	e2 9d 84 ef b8 8f

**Comment by nicolas-grekas** [comment]
Thank you @vladimir-vv.

**Comment by AlexSkrypnyk** [comment]
@nicolas-grekas @fabpot 
Maybe I misunderstanding the goal here, but the expectation from using unicode characters in the rows is to have borders align. The accepted unit test case have them [misaligned](https://github.com/symfony/symfony/pull/60042/files#diff-41f750edb03765692ca969f1112995919a510cf260246a705cb345ca7ade1640R2099):

image

Was this an oversight when this PR was merged? Or was this intentional? If so - there is no clear explanation on why this is acceptable in the codebase.

Could you please shed some light on the intended behaviour of borders/paddings alignment.

Thank you

**Comment by nicolas-grekas** [comment]
That's a rendering issue in the browser. What matters is how terminals display this. On mine, things are aligned.

**Comment by AlexSkrypnyk** [comment]
@nicolas-grekas 
Could you please double-check.

**PHPStorm 2025.1.3 - code editor**

image

**iTerm2 3.5.14**

image

**Terminal (Mac) 2.14 (455.1)**

image
