### PR TITLE
[Yaml] Fixed infinite loop when parser goes through an additional and invalid closing tag

### LINKED ISSUE #40706: YAML parser stuck in seemingly infinite loop
**Symfony version(s) affected**: 5.x-dev ([latest master](https://github.com/symfony/yaml/tree/e61bcd0d1665da9f6f5ffbd449a1c00f5b3de46a))

**Description**
When trying to parse a certain invalid YAML file, the parser can get stuck in what seems to be an infinite loop, with the worker at 100% CPU utilization. I've let it work for a few minutes to no avail.

**How to reproduce**
Pass the following string to `Yaml::parse()`:
```json
{
    "object": {
            "array": [
                "a",
                "b",
                "c"
            ]
        ],
    }
}
```
Notice the extra `],`. When you remove this line (which may be there due to some simple mistake), the parser handles the document fine.

**Possible Solution**
No idea what exactly went wrong here, but IMO the parser should implement some sort of short-circuit for infinite loops. That would be especially useful when parsing user-provided content. Maybe add an option to limit the number of iterations?

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 4.4 and above
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #40706 
| License       | MIT
| Doc PR        | 

Instead of letting the parser goes in an infinite loop because it can't get the right closing tag, throw an exception when the additional and invalid closing tag is found

### CODE REVIEW

File: src/Symfony/Component/Yaml/Parser.php [hunk 1]
```diff
@@ -1225,6 +1225,10 @@ private function lexUnquotedString(int &$cursor): string
         $offset = $cursor;
         $cursor += strcspn($this->currentLine, '[]{},: ', $cursor);
 
+        if ($cursor === $offset) {
+            throw new ParseException('Malformed unquoted YAML string');
```
Comment (Nyholm) [inline src/Symfony/Component/Yaml/Parser.php]: I know that most other exceptions in this file does not end with a period. But all new exceptions should. 

```suggestion
            throw new ParseException('Malformed unquoted YAML string.');
```

**Review by Nyholm — COMMENTED** [review]
Thank you for this PR.

File: src/Symfony/Component/Yaml/Parser.php (hunk 1 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/Yaml/Parser.php]: Alright! Wasn't sure what to do with the period fabbot proposed when I first created the PR. Will know for the future, fixed!

**Review by xabbuh — APPROVED** [review]

**Comment by Nyholm** [comment]
Great work Alexandre. I appreciate all your PRs. Keep up the good work!
