### PR TITLE
[Lock] Avoid aborting outer PostgreSQL transaction on lock contention

### LINKED ISSUE #63967: [Lock] DoctrineDbalStore::save() aborts the surrounding PostgreSQL transaction on lock contention
### Symfony version(s) affected

7.x/8.x

### Description

`Symfony\Component\Lock\Store\DoctrineDbalStore::save()` issues a plain `INSERT` and traps the resulting `DBALException` to fall back to `putOffExpiration()` when the key already exists. 

On **PostgreSQL**, any constraint violation inside a transaction aborts the *entire* transaction (`SQLSTATE[25P02]`). 

The fallback `UPDATE` and every subsequent query in the same transaction, then fails with:

> `An exception occurred while executing a query: SQLSTATE[25P02]: In failed sql transaction: current transaction is aborted, commands ignored until end of transaction block`

MySQL is unaffected because it does statement-level rollback on constraint violations; the surrounding transaction survives. PostgreSQL does not.

This breaks any caller that holds a PostgreSQL transaction open while acquiring a potentially contested lock. Two common setups are affected:

1. **Messenger with the `doctrine_transaction` middleware.** Every handler runs inside a DB transaction. If two workers contend on the same `LockFactory` lock (for example the lock backing `RateLimiterFactory`), the losing worker's entire handler transaction is aborted, and the handler throws `25P02` rather than the caller receiving a `LockConflictedException` it could retry on.
2. **Functional tests wrapped in a transaction** (e.g. via `DAMADoctrineTestBundle`). A test that pre-acquires a lock and then drives a controller which tries to acquire the same lock crashes with `25P02` instead of the controller observing the conflict.

### How to reproduce

```php
<?php

declare(strict_types=1);

require __DIR__.'/vendor/autoload.php';

use Doctrine\DBAL\DriverManager;
use Doctrine\DBAL\Tools\DsnParser;
use Symfony\Component\Lock\Key;
use Symfony\Component\Lock\LockFactory;
use Symfony\Component\Lock\Store\DoctrineDbalStore;

$params = (new DsnParser(['postgresql' => 'pdo_pgsql']))->parse('postgresql://user:pass@127.0.0.1:5432/postgres');
$conn = DriverManager::getConnection($params);

// Isolate from anything else.
$conn->executeStatement('DROP TABLE IF EXISTS lock_keys');

$store = new DoctrineDbalStore($conn);
$store->createTable();

$factory = new LockFactory($store);

// Owner A acquires the lock (different Key identity, so caller below is a different owner).
$ownerA = new Key('contended-resource');
$store->save($ownerA);

// Simulate the caller being in a transaction (messenger doctrine_transaction / test bundle).
$conn->beginTransaction();

try {
    $factory->createLock('contended-resource')->acquire();
    echo "UNEXPECTED: acquire returned without throwing\n";
} catch (\Symfony\Component\Lock\Exception\LockConflictedException $e) {
    echo "OK: LockConflictedException (expected)\n";
} catch (\Throwable $e) {
    echo 'BUG: '.$e::class.': '.$e->getMessage()."\n";
}

// Check outer tx state
try {
    $conn->executeStatement('SELECT 1');
    echo "Outer tx still usable\n";
} catch (\Throwable $e) {
    echo 'Outer tx aborted: '.$e->getMessage()."\n";
}
```

Expected: `LockConflictedException` is thrown and the outer transaction is still usable.
Actual: a `DriverException`/`25P02` is thrown and the outer transaction is aborted.

### Possible Solution

Use `INSERT ... ON CONFLICT` on PostgreSQL so the conflict is resolved in a single statement and no exception reaches PHP. The `WHERE` clause on the `DO UPDATE` branch preserves the existing "refresh-if-ours / takeover-if-expired / otherwise conflict" semantics of `save()` + `putOffExpiration()`:

```sql
INSERT INTO lock_keys (key_id, key_token, key_expiration)
VALUES (?, ?, <now> + <ttl>)
ON CONFLICT (key_id) DO UPDATE
  SET key_token = EXCLUDED.key_token,
      key_expiration = EXCLUDED.key_expiration
  WHERE lock_keys.key_token = EXCLUDED.key_token         -- same Key re-acquiring (refresh)
     OR lock_keys.key_expiration <= <now>                -- existing lock expired (takeover)
```

`executeStatement()` returns the affected-row count; when it is `0`, throw `LockConflictedException`. Because no `23505` is ever raised, the surrounding transaction is never aborted.

Non-PostgreSQL platforms retain the current code path.

I'm happy to open a PR with the patch and a regression test (functional test hitting a real Postgres inside an open transaction) if this seems like a suitable fix.

### Additional Context

- The same issue exists, for the same reason, in `Symfony\Component\Lock\Store\PdoStore`

### PR DESCRIPTION
**Pull request by lacatoire**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63967
| License       | MIT

DoctrineDbalStore and PdoStore caught the duplicate-key exception raised by the INSERT and fell back to UPDATE. On PostgreSQL a constraint violation aborts the surrounding transaction (SQLSTATE 25P02), turning a benign lock contention into a fatal error for any caller wrapped in a transaction (Messenger doctrine_transaction middleware, functional tests using DAMADoctrineTestBundle).

Use INSERT ... ON CONFLICT DO UPDATE WHERE on PostgreSQL so the conflict is resolved server-side without raising. The WHERE clause preserves the existing refresh-if-ours / takeover-if-expired / otherwise conflict semantics; an empty rowCount maps to LockConflictedException, the surrounding transaction stays usable. Other platforms keep the existing code path.

### CODE REVIEW

File: src/Symfony/Component/Lock/Store/DoctrineDbalStore.php [hunk 1]
```diff
@@ -103,39 +103,78 @@ public function save(Key $key)
     {
         $key->reduceLifetime($this->initialTtl);
 
+        $platform = $this->conn->getDatabasePlatform();
+        if ($platform instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform
+            || $platform instanceof \Doctrine\DBAL\Platforms\PostgreSQL94Platform
```
Comment (stof) [inline src/Symfony/Component/Lock/Store/DoctrineDbalStore.php]: why this check ? PostgreSQL94Platform extends PostgreSQLPlatform

File: src/Symfony/Component/Lock/Store/DoctrineDbalStore.php [hunk 2]
```diff
@@ -103,39 +103,78 @@ public function save(Key $key)
...
+            $this->createTable();
+            $rows = $this->executeSaveStatement($sql, $key);
+        }
+
+        if (0 === $rows) {
+            throw new LockConflictedException();
+        }
+    }
+
+    private function executeSaveStatement(string $sql, Key $key): int
```
Comment (stof) [inline src/Symfony/Component/Lock/Store/DoctrineDbalStore.php]: -1 for this method. It is the wrong abstraction IMO, as the list of parameters is strongly tied to the SQL query. Different SQL queries might need different parameters.

File: src/Symfony/Component/Lock/Store/PdoStore.php [hunk 3]
```diff
@@ -120,9 +132,50 @@ public function save(Key $key)
...
+        $now = $this->getCurrentTimestampStatement();
+        $sql = "INSERT INTO $this->table ($this->idCol, $this->tokenCol, $this->expirationCol) VALUES (:id, :token, $now + $this->initialTtl)"
+            ." ON CONFLICT ($this->idCol) DO UPDATE SET $this->tokenCol = EXCLUDED.$this->tokenCol, $this->expirationCol = EXCLUDED.$this->expirationCol"
+            ." WHERE $this->table.$this->tokenCol = EXCLUDED.$this->tokenCol OR $this->table.$this->expirationCol <= $now";
+
+        $conn = $this->getConnection();
+
+        try {
+            $stmt = $this->prepareSavePostgres($conn, $sql, $key);
+            $stmt->execute();
```
Comment (stof) [inline src/Symfony/Component/Lock/Store/PdoStore.php]: Why not matching the behavior of the existing method, where only the statement preparation is wrapped in the try/catch to detect missing tables ?

File: src/Symfony/Component/Lock/Store/DoctrineDbalStore.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Lock/Store/DoctrineDbalStore.php]: let me unresolve

File: src/Symfony/Component/Lock/Store/DoctrineDbalStore.php [hunk 4]
```diff
@@ -219,7 +268,7 @@ public function createTable(): void
      */
     public function configureSchema(Schema $schema/* , \Closure $isSameDatabase */): void
     {
-        if ($schema->hasTable($this->table)) {
+        if ($schema->hasTable($this->table)) { // codespell:ignore
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Lock/Store/DoctrineDbalStore.php]: lets remove all these, dealing with fabbot errors is fine - we could instead ignore this in the fabbot job directly

**Comment by nicolas-grekas** [comment]
Thank you @lacatoire.
