### PR TITLE
[FrameworkBundle][HttpFoundation] reduce response constraints verbosity

### LINKED ISSUE #42948: [HttpFoundation] Make test constraints less verbose
**Description**

I have been wondering about a behaviour present when running a PHPUnit functional test in a command line.

Current behaviour: when using the [off the shelf test assertions](https://symfony.com/doc/current/testing.html#testing-the-response-assertions), such as `assertResponseIsSuccessful()`, each constraint [includes the entire response body via `additionalFailureDescription()` method](https://github.com/symfony/http-foundation/blob/5.3/Test/Constraint/ResponseIsSuccessful.php#L54).

This makes the PHPUnit output quite verbose, thanks to the beautiful error page generated by Symfony, which is great via the browser, but when it comes out as a plaintext, it's not so handy. 

There is a good chance I'm doing something wrong - maybe I'm trying to solve a wrong problem, maybe there is a way to turn the error page off when accessing the page with the testing client. If so, please point me somewhere I can learn about it and read no more, and I apologise for wasting everyone's time. 

If I'm right about the behaviour, then I'd like to propose changing it, because a single failed assertion generates so much clutter that it is difficult to navigate/read the test results. 

I'm happy to create a PR for this, but before I jump into it, I'd like to collect some feedback. 

**My proposal**:

1. Let the developer say whether or not the constraint is verbose. Sometimes we might want to how the response exactly looks like, but most of the time the exception message might be just enough to give us a hint.
2. Add a boolean argument to constraints living in `Symfony\Component\HttpFoundation\Test\Constraint`, say `$verbose = true`
3. Support for this argument be added to all methods in `\Symfony\Bundle\FrameworkBundle\Test\BrowserKitAssertionsTrait`
4. Optionally, the `BrowserKitAssertionsTrait` could define a default $verbose value, which could be overridden by individual test classes using the trait.

All this can be done without affecting any existing functionality, providing the tests would be verbose by default.

What do you think? 

Thanks for reading.

---

**Example: Failed test in the current state, with the complete response body attached**:

```
PHPUnit 9.5.9 by Sebastian Bergmann and contributors.

Testing ControllerSmokeTest
F                                                                  1 / 1 (100%)

Time: 00:03.920, Memory: 68.50 MB

There was 1 failure:

1) App\Tests\ControllerSmokeTest::testNoSmoke with data set "test" (Closure Object (...), array('test'))
Failed asserting that the Response is successful.
HTTP/1.1 404 Not Found
Cache-Control:             max-age=0, must-revalidate, private
Content-Type:              text/html; charset=UTF-8
Date:                      Thu, 09 Sep 2021 01:08:53 GMT
Expires:                   Thu, 09 Sep 2021 01:08:53 GMT
Referrer-Policy:           no-referrer, strict-origin-when-cross-origin
Set-Cookie:                MOCKSESSID=375c8950a650cc3698c4603766660b93b590317cf18bc3b2ba3eed6b911b4709; path=/; secure; httponly; samesite=lax
X-Content-Type-Options:    nosniff
X-Debug-Exception:         No%20route%20found%20for%20%22GET%20http%3A%2F%2Flocalhost%2Ftest
X-Debug-Exception-File:    %2Fapp%2Fvendor%2Fsymfony%2Fhttp-kernel%2FEventListener%2FRouterListener.php:136
X-Frame-Options:           DENY
X-Robots-Tag:              noindex
X-Xss-Protection:          1; mode=block

<!-- No route found for &quot;GET http://localhost/test&quot; (404 Not Found) -->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="robots" content="noindex,nofollow" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <title>No route found for &quot;GET http://localhost/test&quot; (404 Not Found)</title>
        <style>/* This file is based on WebProfilerBundle/Resources/views/Profiler/profiler.css.twig.
   If you make any change in this file, verify the same change is needed in the other file. */
:root {
    --font-sans-serif: Helvetica, Arial, sans-serif;
    --page-background: #f9f9f9;
    --color-text: #222;
    /* when updating any of these colors, do the same in toolbar.css.twig */
    --color-success: #4f805d;
    --color-warning: #a46a1f;
    --color-error: #b0413e;
    --color-muted: #999;
    --tab-background: #fff;
    --tab-color: #444;







[... thousands of lines of HTML and CSS - you get the point ...]







app/vendor/symfony/framework-bundle/Test/BrowserKitAssertionsTrait.php:137
app/vendor/symfony/framework-bundle/Test/BrowserKitAssertionsTrait.php:33
app/tests/BaseTestCase.php:125
app/tests/BaseTestCase.php:66
app/tests/ControllerSmokeTest.php:31

Caused by
ErrorException: No route found for "GET http://localhost/path" in app/vendor/symfony/http-kernel/EventListener/RouterListener.php:136
Stack trace:
#0 app/vendor/symfony/framework-bundle/Test/BrowserKitAssertionsTrait.php(33): Symfony\Bundle\FrameworkBundle\Test\WebTestCase::assertThatForResponse(Object(Symfony\Component\HttpFoundation\Test\Constraint\ResponseIsSuccessful), '')
#1 app/tests/BaseTestCase.php(125): Symfony\Bundle\FrameworkBundle\Test\WebTestCase::assertResponseIsSuccessful()

[... stack trace not important...]

#13 app/bin/phpunit(11): PHPUnit\TextUI\Command::main()
#14 {main}
FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

**Example: without the response body, the error is still perfectly legible**

```
PHPUnit 9.5.9 by Sebastian Bergmann and contributors.

Testing ControllerSmokeTest
F                                                                  1 / 1 (100%)

Time: 00:03.920, Memory: 68.50 MB

There was 1 failure:

1) App\Tests\ControllerSmokeTest::testNoSmoke with data set "test" (Closure Object (...), array('test'))
Failed asserting that the Response is successful.

app/vendor/symfony/framework-bundle/Test/BrowserKitAssertionsTrait.php:137
app/vendor/symfony/framework-bundle/Test/BrowserKitAssertionsTrait.php:33
app/tests/BaseTestCase.php:125
app/tests/BaseTestCase.php:66
app/tests/ControllerSmokeTest.php:31

Caused by
ErrorException: No route found for "GET http://localhost/path" in app/vendor/symfony/http-kernel/EventListener/RouterListener.php:136
Stack trace:
#0 app/vendor/symfony/framework-bundle/Test/BrowserKitAssertionsTrait.php(33): Symfony\Bundle\FrameworkBundle\Test\WebTestCase::assertThatForResponse(Object(Symfony\Component\HttpFoundation\Test\Constraint\ResponseIsSuccessful), '')
#1 app/tests/BaseTestCase.php(125): Symfony\Bundle\FrameworkBundle\Test\WebTestCase::assertResponseIsSuccessful()

[... stack trace not important...]

#13 app/bin/phpunit(11): PHPUnit\TextUI\Command::main()
#14 {main}
FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

### PR DESCRIPTION
**Pull request by Nicals**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #42948
| License       | MIT
| Doc PR        | https://github.com/symfony/symfony-docs/pull/17848

Adds a `verbose` argument to HttpFoundation response test constraints.
If set to false, only the HTTP response command and headers will be displayed in case of test failure.

This argument is `true` by default to keep backward compatibility, but I think it would make more sense to be `false`.

<details>
  <summary>Before</summary>

```php
$this->assertResponseIsSuccessful();
```

```
-- PHPUnit output:
Testing App\Controller\AppControllerTest
F                                                                   1 / 1 (100%)

Time: 00:00.299, Memory: 42.50 MB

There was 1 failure:

1) App\Controller\AppControllerTest::testSuccessfulResponse
Failed asserting that the Response is successful.
HTTP/1.1 404 Not Found
Cache-Control:          max-age=0, must-revalidate, private
Content-Type:           text/html; charset=UTF-8
Date:                   Fri, 03 Feb 2023 10:54:05 GMT
Expires:                Fri, 03 Feb 2023 10:54:05 GMT
X-Debug-Exception:
X-Debug-Exception-File: ...
X-Robots-Tag:           noindex

<!--  (404 Not Found) -->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="robots" content="noindex,nofollow" />
    <!-- undred of lines later -->
        Sfjs.createToggles();
        Sfjs.createFilters();
    });
}
/*]]>*/        </script>
    </body>
</html>
<!--  (404 Not Found) -->

/home/user/project/vendor/symfony/framework-bundle/Test/BrowserKitAssertionsTrait.php:142
/home/user/project/vendor/symfony/framework-bundle/Test/BrowserKitAssertionsTrait.php:33
/home/user/project/tests/Controller/AppControllerTest.php:35
```
</details>

<details>
  <summary>After</summary>

```php
$this->assertResponseIsSuccessful(verbose: false);
```

```
-- PHPUnit output:
Testing App\Controller\AppControllerTest
F                                                                   1 / 1 (100%)

Time: 00:00.300, Memory: 42.50 MB

There was 1 failure:

1) App\Controller\AppControllerTest::testSuccessfulResponse
Failed asserting that the Response is successful.
HTTP/1.1 404 Not Found
Cache-Control:          max-age=0, must-revalidate, private
Content-Type:           text/html; charset=UTF-8
Date:                   Fri, 03 Feb 2023 10:53:03 GMT
Expires:                Fri, 03 Feb 2023 10:53:03 GMT
X-Debug-Exception:
X-Debug-Exception-File: ...
X-Robots-Tag:           noindex

/home/user/project/vendor/symfony/framework-bundle/Test/BrowserKitAssertionsTrait.php:142
/home/user/project/vendor/symfony/framework-bundle/Test/BrowserKitAssertionsTrait.php:33
/home/user/project/tests/Controller/AppControllerTest.php:35
```

</details>

I added a method `Symfony\Component\HttpFoundation\Response::getCommandString()` that builds the first line of an HTTP response to avoid code duplication in constraints classes.
I thought of other solutions:

  +  Build the HTTP command line in each `Constraint`. This seems that too much code duplication.
  + Add an `AbstractResponseConstraint` with a utility method to build a less verbose response string. I wasn't sure we needed to add an extend layer here.
  + Add a `ResponseConstraintTrait` with an exposed method to build the less verbose response string. This did not *feel* right.

Overall, I think the `Response` class is the more appropriate to build this string.

I also had some issue with psalm complaining about the documented $response argument type of `additionalFailureDescription`:

```
ERROR: MoreSpecificImplementedParamType - src/Symfony/Component/HttpFoundation/Test/Constraint/ResponseStatusCodeSame.php:50:53 - Argument 1 of Symfony\Component\HttpFoundation\Test\Constraint\ResponseStatusCodeSame::additionalFailureDescription has the more specific type 'Symfony\Component\HttpFoundation\Response', expecting 'mixed' as defined by PHPUnit\Framework\Constraint\Constraint::additionalFailureDescription (see https://psalm.dev/140)
    protected function additionalFailureDescription($other): string
```

I needed to delete the phpdoc comment to comply with this. I only changed the lines were Psalm was giving me errors, but there are still some mismatch between HttpFoundation constraints signatures and PHPUnit ones.

### CODE REVIEW

**Comment by GromNaN** [comment]
Hi Nicolas! Thank you for submitting this pull request and for all the hard work you put into it. I appreciate your effort and dedication to improving this project.

However, after reviewing your changes, I'm not entirely sure if your solution is necessary or if using [`$client->catchExceptions(false);`](https://symfony.com/doc/6.3/testing.html#reporting-exceptions) might already achieve the same result.

**Comment by Nicals** [comment]
Catching exception effectively reduces the verbosity.

This PR intends to reduces the verbosity of test logs in all cases.

For example, a failed assertion about response status code will dump the entire response, including body.
When debugging such assertion I want to see the actual response status code, but this information is in the response header, hundreds of lines above the tail of the unit test logs.
Exception catching is not the issue in this case.

File: src/Symfony/Component/HttpFoundation/Response.php [hunk 1]
```diff
@@ -249,6 +249,14 @@ public function __clone()
         $this->headers = clone $this->headers;
     }
 
+    /**
+     * @return string The first line of the actual HTTP request
+     */
+    public function getCommandString(): string
```
Comment (fabpot) [inline src/Symfony/Component/HttpFoundation/Response.php]: I don't think this is something we want to expose in the public API.

**Review by fabpot — CHANGES_REQUESTED** [review]

**Comment by fabpot** [comment]
@Nicals Are you still interested in finishing this PR?

**Comment by Nicals** [comment]
@fabpot I totally forgot about this MR. I don't work with php/symfony anymore so I did not keep track of it.

I quickly rebased this branch on up to date 7.1 and built the response headers manually.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Nicals.
