### PR TITLE
[DI] Fix container lint command when a synthetic service is used in an expression

### LINKED ISSUE #35691: Container lint command fails with synthetic service+expression language combo
**Symfony version(s) affected**: 4.4

**Description**  
The container lint command fails when using a combination of synthetic services & the expression language. I've created an [example application ](https://github.com/HypeMC/sf-container-lint-bug)to demonstrate the problem, all the code needed to reproduce the bug is in this commit: https://github.com/HypeMC/sf-container-lint-bug/commit/bb342d5b68892609fa86a048ce61f1750d0be6ab.

Basically the problem is that when using the `service` function from the expression language with a service which it self requires a synthetic service, the lint command fails, even though the service definitions are valid. The following error message is outputed:

```
In ContainerBuilder.php line 1091:
                                                                                                           
  You have requested a synthetic service ("kernel"). The DIC does not know how to construct this service.
```

**How to reproduce**  
```yaml
# config/services.yaml

    App\Controller\TestController:
        arguments:
            - '@=service("App\\Service\\Test").getSomething()'
```

```php
class TestController extends AbstractController
{
    private $string;

    public function __construct(string $string)
    {
        $this->string = $string;
    }

    /**
     * @Route("/", name="test")
     */
    public function index(): Response
    {
        return new Response($this->string);
    }
}

class Test
{
    private $kernel;

    public function __construct(KernelInterface $kernel)
    {
        $this->kernel = $kernel;
    }

    public function getSomething(): string
    {
        return 'some-string';
    }
}
```

**Additional context**  
image

### PR DESCRIPTION
**Pull request by HypeMC**
Fix container lint command when a synthetic service is used in combination with the expression language.

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35691
| License       | MIT
| Doc PR        | -

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php [hunk 1]
```diff
@@ -191,7 +191,12 @@ private function checkType(Definition $checkedDefinition, $value, \ReflectionPar
         } elseif ($value instanceof Parameter) {
             $value = $this->container->getParameter($value);
         } elseif ($value instanceof Expression) {
-            $value = $this->getExpressionLanguage()->evaluate($value, ['container' => $this->container]);
+            try {
+                $value = $this->getExpressionLanguage()->evaluate($value, ['container' => $this->container]);
+            } catch (RuntimeException $e) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php]: `\Exception`

Comment (HypeMC) [reply src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php]: @nicolas-grekas Hm, not sure about that one tbh, what if it's a `ServiceNotFoundException`, I don't think the container lint command should just ignore an expression that references a non-existent service.

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php]: Evaluating expression at compile time is already quite edgy. We could skip completely Expression objects IMHO.

Comment (HypeMC) [reply src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php]: @nicolas-grekas Done, switched to `\Exception`.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @HypeMC.
