### PR TITLE
[AssetMapper] Fix URL pattern when importing es-module-shims

### LINKED ISSUE #52783: [AssetMapper] Import-Polyfill throws error in JS-Console.
### Symfony version(s) affected

6.4.0

### Description

Relates to https://github.com/symfony/symfony/issues/52547

I could not find a way to make the polyfill for importmap work.

I am aware that the behaviour changed between 6.3 and 6.4.
https://symfony.com/doc/6.4/frontend/asset_mapper.html#framework-asset-mapper-importmap-polyfill

In 6.3 i used the files from here.
// https://ga.jspm.io/npm:es-module-shims@1.8.0/dist/es-module-shims.js
// https://ga.jspm.io/npm:es-module-shims@1.8.0/dist/es-module-shims.js.map

These files do not have the problematic last line from the lastest shim.
`export{t as default};`
Is this because of the `/+esm`

a) No shim: Works

```
framework:
    asset_mapper:
        importmap_polyfill: false 
```

b) Per Default (not setting `importmap_polyfill`) the shim is the 1.8.2 (or actual version) from CDN.
https://cdn.jsdelivr.net/npm/es-module-shims@1.8.2/+esm

```
framework:
    asset_mapper:
        ...
```

But with this i get this error in the browser js console.
`es-module-shims.index-e76dd15dae6b25cfe767df2e7fe0ec9e.js:7 Uncaught SyntaxError: Unexpected token 'export' (at es-module-shims.index-e76dd15dae6b25cfe767df2e7fe0ec9e.js:7:33789)`

c) Default suggested installation (same result as b) )
`php bin/console importmap:require es-module-shims`

```
framework:
    asset_mapper:
        importmap_polyfill: 'es-module-shims'
```

d) WORKS: Use my local files from Symfony 6.3 and copy them into `/assets/lib/es-module-shims/`
// https://ga.jspm.io/npm:es-module-shims@1.8.0/dist/es-module-shims.js
// https://ga.jspm.io/npm:es-module-shims@1.8.0/dist/es-module-shims.js.map

Run:
`php bin/console importmap:require "es-module-shims" --path=./assets/lib/es-module-shims/es-module-shims.js`

```
framework:
    asset_mapper:
        importmap_polyfill: 'es-module-shims'
```

importmap.php
```
'es-module-shims' => [
        'path' => './assets/lib/es-module-shims/es-module-shims.js',
    ],```


### How to reproduce

See above

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by hashbanged**
This fixes a JS console syntax error when importing the `es-module-shims` polyfills package

| Q             | A
| ------------- | ---
| Branch?       | 6.4 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #52783  
| License       | MIT

Requiring `es-module-shims` using AssetMapper causes a trailing `export {t as default};` in the downloaded file. The recommendation in #52783 is to be explicit about checking if the package is the shims/polyfill, and, if so, to use the CSS URL pattern when building the HTTP request for the package. This PR adds a new method for handling this case, and it centralizes the logic for determining if the URL pattern should be `URL_PATTERN_DIST`|`URL_PATTERN_DIST_CSS`

### CODE REVIEW

**Comment by broadcoder** [comment]
Looks like we had similar ideas: https://github.com/symfony/symfony/compare/6.4...broadcoder:symfony:fix_wrong_esm_loading_for_es_modules_shim_package_in_asset_mapper?diff=unified&w=

I wanted to leave it here, since I also started to work on it until i realised I would need to spend quite some time setting up a proper environment, but maybe you like my idea of having a list of excludes instead of a single case special handling, but very likely your solution to pass also the $entry->type is better than mine, tho :) Thanks for taking care 🙏

File: src/Symfony/Component/AssetMapper/ImportMap/Resolver/JsDelivrEsmResolver.php [hunk 1]
```diff
@@ -326,4 +332,22 @@ private function makeImportsBare(string $content, array &$dependencies, array &$
...
+     */
+    private function resolveUrlPattern(string $packageName, string $path, ImportMapType $type = null): string
+    {
+        // The URL for the es-module-shims polyfill package uses the CSS pattern to
+        // prevent a syntax error in the browser console.
+        if (self::ES_MODULE_SHIMS === $packageName) {
+            return self::URL_PATTERN_DIST_CSS;
+        }
+
+        if (str_ends_with($path, '.css') || ($type && ImportMapType::CSS === $type)) {
```
Comment (stof) [inline src/Symfony/Component/AssetMapper/ImportMap/Resolver/JsDelivrEsmResolver.php]: `$type && ` is useless as `null` won't be equal to `ImportMapType::CSS` anyway

Comment (hashbanged) [reply src/Symfony/Component/AssetMapper/ImportMap/Resolver/JsDelivrEsmResolver.php]: Hi, @broadcoder! If there's a future need for more `URL_PATTERN_DIST_CSS` exclusions based on package name, I think that approach makes total sense. I wonder if this is really just a single edge case? @weaverryan or others? If so, it might make sense for me to drop this PR and for you to submit yours. I *don't* want to hijack your effort. 

Sidenote: pretty sure I spent most of this PR trying to get that method name right, so props to thinking too alike. :)

Comment (hashbanged) [reply src/Symfony/Component/AssetMapper/ImportMap/Resolver/JsDelivrEsmResolver.php]: Thanks, @stof. I removed that null check.

File: src/Symfony/Component/AssetMapper/ImportMap/Resolver/JsDelivrEsmResolver.php [hunk 2]
```diff
@@ -30,6 +30,8 @@ final class JsDelivrEsmResolver implements PackageResolverInterface
 
     public const IMPORT_REGEX = '#(?:import\s*(?:\w+,)?(?:(?:\{[^}]*\}|\w+|\*\s*as\s+\w+)\s*\bfrom\s*)?|export\s*(?:\{[^}]*\}|\*)\s*from\s*)("/npm/((?:@[^/]+/)?[^@]+?)(?:@([^/]+))?((?:/[^/]+)*?)/\+esm")#';
 
+    public const ES_MODULE_SHIMS = 'es-module-shims';
```
Comment (weaverryan) [inline src/Symfony/Component/AssetMapper/ImportMap/Resolver/JsDelivrEsmResolver.php]: `private`?

**Review by weaverryan — APPROVED** [review]
Minor thing - but looks good. Thank you for this!

File: src/Symfony/Component/AssetMapper/ImportMap/Resolver/JsDelivrEsmResolver.php [hunk 3]
```diff
@@ -169,7 +171,11 @@ public function downloadPackages(array $importMapEntries, callable $progressCall
                 throw new \InvalidArgumentException(sprintf('The entry "%s" is not a remote package.', $entry->importName));
             }
 
-            $pattern = ImportMapType::CSS === $entry->type ? self::URL_PATTERN_DIST_CSS : self::URL_PATTERN_DIST;
+            $pattern = $this->resolveUrlPattern(
+                $entry->getPackageName(),
+                $entry->getPackagePathString(),
+                $entry->type
```
Comment (fabpot) [inline src/Symfony/Component/AssetMapper/ImportMap/Resolver/JsDelivrEsmResolver.php]:
```suggestion
                $entry->type,
```

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @hashbanged.

**Comment by hashbanged** [comment]
Thank you, everyone, for the guidance on this.
