### PR TITLE
[DependencyInjection] Update `ResolveClassPass` to check class existence

### LINKED ISSUE #54095: Confusing error message: 'must define the "event" attribute on "kernel.event_listener" tags' when the problem was nonexistent class
### Symfony version(s) affected

5.4

### Description

I followed this guide:
https://symfony.com/doc/5.x/event_dispatcher.html

and I created a class `App\Listeners\ExceptionListener.php`

but in `services.yaml` I mistyped the class name as:

```
services:
    App\Listener\ExceptionListener:
        tags: [kernel.event_listener]
```
Note the namespace `Listener` without the `s`.

I got this confusing error:
```
Service "App\Listener\ExceptionListener" must define the "event" attribute on "kernel.event_listener" tags.
```
which didn't help much, because I was becoming stupid trying to figure out why it complained about a missing attribute that should be optional.

Until I figured out I had misspelled the namespace. To the error message's credit, it does repeat the name of the class, so that gives an opportunity to catch it (which I missed), but still, the error message is unnecessarily misleading. It's specifically directing my attention to a place where the issue is not.

The error should have said something like: **"Service `App\Listener\ExceptionListener` does not exist."** (and if it can add a "Did you mean one of the following...?" that would be great).

### How to reproduce

In `services.yaml`, add:
```
services:
    App\Some\NonExistentListener:
        tags: [kernel.event_listener]
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by GaryPEGEOT**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54095
| License       | MIT

~~Currently doesn't check for incorrect factories, but I'm not sure what would be the best approach~~

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/CheckServiceClassExistsPassTest.php [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+        $container->register('bar', 'App\Servoces\MyService')->setSynthetic(true);
+        $container->register('baz', 'App\Servoces\MyService');
+
+        (new CheckServiceClassExistsPass())->process($container);
+    }
+
+    public function testProcessParameterClass()
+    {
+        $this->expectException(IncorrectServiceClassException::class);
+        $this->expectExceptionMessage('class "App\Servoces\MyService" defined for service "foo" does not exist.');
```
Comment (OskarStark) [inline src/Symfony/Component/DependencyInjection/Tests/Compiler/CheckServiceClassExistsPassTest.php]:
```suggestion
        $this->expectExceptionMessage('class "App\Services\MyService" defined for service "foo" does not exist.');
```
or expected ?

Comment (GaryPEGEOT) [reply src/Symfony/Component/DependencyInjection/Tests/Compiler/CheckServiceClassExistsPassTest.php]: > or expected ?

Yeah I wanted to use some kind of "common typo", but in the end both would work cause neither exists :smiley:. Although, if in the future that class is added as a fixture, it would breaak the test

File: src/Symfony/Component/DependencyInjection/Compiler/CheckServiceClassExistsPass.php [hunk 2]
```diff
@@ -0,0 +1,63 @@
+<?php
+
+declare(strict_types=1);
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Compiler/CheckServiceClassExistsPass.php]: We don't use strict types in Symfony

File: src/Symfony/Component/DependencyInjection/Compiler/CheckServiceClassExistsPass.php [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+            if ($definition->isSynthetic()) {
+                continue;
+            }
+
+            if ($factory = $definition->getFactory()) {
+                $this->checkFactory($container, $factory, $id);
+                continue;
+            }
+
+            $class = $container->getParameterBag()->resolveValue($definition->getClass());
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Compiler/CheckServiceClassExistsPass.php]: not needed. In the èTYPE_AFTER_REMOVING` stage, classes have already been resolved in definitions in a persistent way.

File: src/Symfony/Component/DependencyInjection/Compiler/CheckServiceClassExistsPass.php [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\DependencyInjection\Compiler;
+
+use Symfony\Component\DependencyInjection\ContainerBuilder;
+use Symfony\Component\DependencyInjection\Exception\IncorrectServiceClassException;
+use Symfony\Component\DependencyInjection\Reference;
+
+class CheckServiceClassExistsPass implements CompilerPassInterface
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Compiler/CheckServiceClassExistsPass.php]: This should probably be implemented as a recursive pass, so that all definitions that got inlined during the optimization phase are also checked (otherwise, you would have to run it earlier, but it is harder to avoid issues for unused services that gets removed, which is often a valid usage of non-existent classes (related to optional dependencies of bundles for instance)

File: src/Symfony/Component/DependencyInjection/Compiler/CheckServiceClassExistsPass.php [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+        }
+    }
+
+    private function checkFactory(ContainerBuilder $container, array|string $factory, string $id): void
+    {
+        if (\is_array($factory) && $factory[0] instanceof Reference && $container->hasDefinition((string) $factory[0])) {
+            return;
+        }
+
+        $factory = \is_array($factory) ? array_map('strval', $factory) : $container->getParameterBag()->resolveValue($factory);
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Compiler/CheckServiceClassExistsPass.php]: this breaks for the case where `$factory[0]` is a Definition (quite common for the case of a factory service used only once, which gets inlined during optimizations)

**Comment by nicolas-grekas** [comment]
This approach is too broad IMHO. There are cases where the class is eg `string` for some internal services.

In https://github.com/symfony/symfony/issues/54095#issuecomment-2922831094, I wrote:

> I'm wondering if we shouldn't add the check when the class is not defined for a service (and thus when the id becomes the class).

Can't we patch the existing compiler pass that copies the id to the class when no class is set, and make it throw when id is not a class?

**Comment by GaryPEGEOT** [comment]
> Can't we patch the existing compiler pass that copies the id to the class when no class is set, and make it throw when id is not a class?

But then it would not work if you define a manual id and make a typo in the class (although more of a niche case)

**Comment by GaryPEGEOT** [comment]
> There are cases where the class is eg `string` for some internal services.

So we could have something like `['mailer.transport', 'createFromDsn']` at this point? (Not a reference but the service ID as is?

**Comment by nicolas-grekas** [comment]
There are many ways one can mess up with their DI config. Validating everything adds to the compilation time. That's something we always considered outside of the scope of the compilation step.

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/includes/foo.php [hunk 6]
```diff
@@ -48,3 +48,12 @@ public function setOtherInstances($otherInstances)
         $this->otherInstances = $otherInstances;
     }
 }
+
+
+namespace Acme;
+
+class Foo
+{}
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/includes/foo.php]:
```suggestion
{
}
```

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/includes/foo.php [hunk 7]
```diff
@@ -48,3 +48,12 @@ public function setOtherInstances($otherInstances)
         $this->otherInstances = $otherInstances;
     }
 }
+
+
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/includes/foo.php]:
```suggestion
```

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/includes/foo.php [hunk 8]
```diff
@@ -48,3 +48,12 @@ public function setOtherInstances($otherInstances)
...
+namespace Acme;
+
+class Foo
+{}
+
+class WithShortCutArgs
+{}
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/includes/foo.php]:
```suggestion
{
}
```

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/includes/fixture_app_services.php [hunk 9]
```diff
@@ -0,0 +1,64 @@
...
+    {
+    }
+}
+
+class Handler1
+{
+    public function __construct(
+        public Db $db,
+        public Schema $schema,
+        public Processor $processor
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/includes/fixture_app_services.php]:
```suggestion
        public Processor $processor,
```

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/includes/fixture_app_services.php [hunk 10]
```diff
@@ -0,0 +1,64 @@
...
+    ) {
+    }
+}
+
+class Handler2
+{
+    public function __construct(
+        public Db $db,
+        public Schema $schema,
+        public Processor $processor
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/includes/fixture_app_services.php]:
```suggestion
        public Processor $processor,
```

File: src/Symfony/Component/DependencyInjection/Tests/Fixtures/includes/fixture_app_services.php [hunk 11]
```diff
@@ -0,0 +1,64 @@
...
+    ) {
+    }
+}
+
+class Processor
+{
+    public function __construct(
+        public Registry $registry,
+        public Db $db
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Fixtures/includes/fixture_app_services.php]:
```suggestion
        public Db $db,
```

**Review by nicolas-grekas — COMMENTED** [review]
LGTM, test cases changes look consistent with the updated behavior.

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/DependencyInjection/Compiler/ResolveClassPass.php [hunk 12]
```diff
@@ -27,9 +27,14 @@ public function process(ContainerBuilder $container): void
                 continue;
             }
             if (preg_match('/^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*+(?:\\\\[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*+)++$/', $id)) {
-                if ($definition instanceof ChildDefinition && !class_exists($id)) {
-                    throw new InvalidArgumentException(\sprintf('Service definition "%s" has a parent but no class, and its name looks like an FQCN. Either the class is missing or you want to inherit it from the parent service. To resolve this ambiguity, please rename this service to a non-FQCN (e.g. using dots), or create the missing class.', $id));
+                if (!class_exists($id) && !interface_exists($id)) {
+                    $error = $definition instanceof ChildDefinition ?
+                        'has a parent but no class, and its name looks like an FQCN. Either the class is missing or you want to inherit it from the parent service' :
+                        'name looks like an FQCN but the class does not exists';
```
Comment (fabpot) [inline src/Symfony/Component/DependencyInjection/Compiler/ResolveClassPass.php]:
```suggestion
                        'name looks like a FQCN but the class does not exist';
```

File: src/Symfony/Component/DependencyInjection/Compiler/ResolveClassPass.php [hunk 13]
```diff
@@ -27,9 +27,14 @@ public function process(ContainerBuilder $container): void
                 continue;
             }
             if (preg_match('/^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*+(?:\\\\[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*+)++$/', $id)) {
-                if ($definition instanceof ChildDefinition && !class_exists($id)) {
-                    throw new InvalidArgumentException(\sprintf('Service definition "%s" has a parent but no class, and its name looks like an FQCN. Either the class is missing or you want to inherit it from the parent service. To resolve this ambiguity, please rename this service to a non-FQCN (e.g. using dots), or create the missing class.', $id));
+                if (!class_exists($id) && !interface_exists($id)) {
+                    $error = $definition instanceof ChildDefinition ?
+                        'has a parent but no class, and its name looks like an FQCN. Either the class is missing or you want to inherit it from the parent service' :
```
Comment (fabpot) [inline src/Symfony/Component/DependencyInjection/Compiler/ResolveClassPass.php]:
```suggestion
                        'has a parent but no class, and its name looks like a FQCN. Either the class is missing or you want to inherit it from the parent service' :
```

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/DependencyInjection/Compiler/ResolveClassPass.php (hunk 13 above)
Comment (GaryPEGEOT) [reply src/Symfony/Component/DependencyInjection/Compiler/ResolveClassPass.php]: Fixed!

**Comment by nicolas-grekas** [comment]
Thank you @GaryPEGEOT.
