### PR TITLE
[PhpUnitBridge] Use trait instead of extending deprecated class

### LINKED ISSUE #32086: Symfony\Bridge\PhpUnit\Legacy\CoverageListenerForV6 deprecation
**Symfony version(s) affected**: 4.3.x

**Description**  
```  
1x: The "Symfony\Bridge\PhpUnit\Legacy\CoverageListenerForV6" class extends 
"PHPUnit\Framework\BaseTestListener" that is deprecated Use 
TestListenerDefaultImplementation trait instead.
    1x in DebugClassLoader::loadClass from Symfony\Component\Debug
```

**How to reproduce**  
Run a test with ```Symfony\Bridge\PhpUnit\CoverageListener``` on PhpUnit V6

**Possible Solution**  
Use the Trait instead of extending the Class

### PR DESCRIPTION
**Pull request by marcello-moenkemeyer**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #32086
| License       | MIT
| Doc PR        |

Use `TestListenerDefaultImplementation` instead of deprecated `BaseTestListener` for `CoverageListenerForV6`

As this is my very first pull request for this project, I'd be very glad for hints and suggestions in case I missed something.

### CODE REVIEW

File: src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerForV6.php [hunk 1]
```diff
@@ -22,8 +23,10 @@
  *
  * @internal
  */
-class CoverageListenerForV6 extends BaseTestListener
+class CoverageListenerForV6 implements TestListener
 {
+    use TestListenerDefaultImplementation;
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerForV6.php]: the trait has been added to v6.5, isn't it?

Comment (marcello-moenkemeyer) [reply src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerForV6.php]: The trait was added in v6.4.

Initial commit:
https://github.com/sebastianbergmann/phpunit/commit/9d5924f4bf4d4f41529da5e2c98c1d8ed9495e00#diff-f014f0750e1e6f18c6598f8c01d788a5

Parent commit:
https://github.com/sebastianbergmann/phpunit/commit/169bb8351039018b315438d7661606ed5e8609f3

Should I update the `composer.json` for v6?

Comment (nicolas-grekas) [reply src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerForV6.php]: yes, would make sense to me.

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerForV6.php (hunk 1 above)
Comment (marcello-moenkemeyer) [reply src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerForV6.php]: Added the conflicting versions for v6.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @marcello-moenkemeyer.
