### PR TITLE
[Mime] Forbid messages that are generators to be used more than once

### LINKED ISSUE #51764: Memory Leak in Symfony Mailer when sending many attachments of >5MB
### Symfony version(s) affected

5.4.22

### Description

Hi , 
I have encountered an issue where attaching several files each of size 5MB , sends Out Of Memory exception 
` Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\OutOfMemoryError: "Error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 23079128 bytes)" at vendor/symfony/mime/RawMessage.php line 53 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\OutOfMemoryError(code: 0): Error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 23079128 bytes) at vendor/symfony/mime/RawMessage.php:53)"} [`

Is that a known issue. or am I missing something ? 

I have already tried using attachPart, attach , but it produces the same results.

### How to reproduce

Attach numerous Files from form to be sent in email each of size 5MB . 

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by fabpot**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #51764, Fix #51874
| License       | MIT

This is a continuation of #51874, when someone tries to send the same message more than once.
@chalasr @stof

### CODE REVIEW

File: src/Symfony/Component/Mime/RawMessage.php [hunk 1]
```diff
@@ -47,6 +47,22 @@ public function toIterable(): iterable
             return;
         }
 
+        if ($this->message instanceof \Generator) {
+            if (!$this->message->valid()) {
+                trigger_deprecation('symfony/mime', '6.4', 'Sending an email with a closed generator is deprecated and will throw in 7.0.');
```
Comment (stof) [inline src/Symfony/Component/Mime/RawMessage.php]: This deprecation won't be effective: on the first iteration, it is not closed yet (otherwise we already get an exception anyway) and for next iterations, we will have the string assigned on line 61, not the generator.

File: src/Symfony/Component/Mime/Tests/RawMessageTest.php [hunk 2]
```diff
@@ -46,6 +46,21 @@ public function testSerialization(mixed $messageParameter, bool $supportReuse)
...
 
+    /**
+     * @dataProvider provideMessages
+     */
+    public function testToIterable(mixed $messageParameter, bool $supportReuse)
+    {
+        $message = new RawMessage($messageParameter);
+        $this->assertEquals('some string', implode('', iterator_to_array($message->toIterable())));
+
+        // in 7.0, the test with a generator will throw an exception
```
Comment (stof) [inline src/Symfony/Component/Mime/Tests/RawMessageTest.php]: you should be asserting the deprecation for cases not supporting reuse. This would prove you that it currently does not get triggered.

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Mime/RawMessage.php (hunk 1 above)
Comment (fabpot) [reply src/Symfony/Component/Mime/RawMessage.php]: Oops :) Good catch, should be better now.
