### PR TITLE
[Messenger] Add a \Throwable argument in RetryStrategyInterface methods

### LINKED ISSUE #36182: [Messenger] Infinite retries depending on exceptions
**Description**  
In some cases you know that it is useless to retry again and you can use the `UnrecoverableMessageHandlingException`.
However, you have no way to do the opposite: retry indefinitely until your message is successfully handled. 

**For example**
My handlers can fail due to various exceptions but for a specific one (let's call it `RetryLaterException`) I want to retry until the message is successfully handled.
I can try to implement a `RetryStrategy` which looks like this
- the message needs to be "re-delivered" due to a `RetryLaterException`: always retry with a constant delay
- else: use the `MultiplierRetryStrategy`
but this is not possible because you don't have access to the exceptions inside the `RetryStrategyInterface`.

**Some ideas**
- add an event listener to handle this case before the `SendFailedMessageForRetryListener`. This requires the `WorkerMessageFailedEvent` to support the `stopPropagation` method.
- add a stamp that you can look for in your custom `RetryStrategy`. Currently, there is now way to add a stamp when an exception is thrown. When an exception is thrown in the `HandleMessageMiddleware`, it is directly caught by the `Worker`.
- send the message to a different transport with a different `RetryStrategy` for some specific exceptions

### PR DESCRIPTION
**Pull request by Braxilior**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #36182 
| License       | MIT

This allows to define new retry strategies based on the exceptions thrown during the last handling.

### CODE REVIEW

File: src/Symfony/Component/Messenger/Retry/RetryStrategyInterface.php [hunk 1]
```diff
@@ -20,10 +20,10 @@
  */
 interface RetryStrategyInterface
 {
-    public function isRetryable(Envelope $message): bool;
+    public function isRetryable(Envelope $message, ?\Throwable $throwable = null): bool;
```
Comment (chalasr) [inline src/Symfony/Component/Messenger/Retry/RetryStrategyInterface.php]: This is a BC break forbidden by our [BC promise](https://symfony.com/doc/current/contributing/code/bc.html#changing-interfaces):
Screenshot 2020-03-24 at 11 35 55

We can either add a new method (using `@method` phpdoc annotation until 6.0) or introduce a child interface redefining `isRetryable` with the new optional arg.

**Review by chalasr — CHANGES_REQUESTED** [review]

**Review by Tobion — APPROVED** [review]
Please add a changelog note to https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/CHANGELOG.md

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Why didn't we go with the option of adding the argument to the existing interface, with a proper BC layer? It would make sense to me, don't you think so?

**Comment by chalasr** [comment]
Replacing the concrete method by a virtual one until 6.0? Our BC promise needs a patch :)

**Comment by nicolas-grekas** [comment]
@chalasr no need: just adding an `@param` annotation is enough, alongside with:
- a commented argument on the signature,
- all implementations updated accordingly (in a similar way for non-final/internal classes)
- notes in UPGRADE-5.1/6.0.md + CHANGELOG

@Braxilior up to do it ?

**Comment by Braxilior** [comment]
yes 👍

File: UPGRADE-5.1.md [hunk 2]
```diff
@@ -73,6 +73,8 @@ Messenger
  * Deprecated Doctrine transport. It has moved to a separate package. Run `composer require symfony/doctrine-messenger` to use the new classes.
  * Deprecated RedisExt transport. It has moved to a separate package. Run `composer require symfony/redis-messenger` to use the new classes.
  * Deprecated use of invalid options in Redis and AMQP connections.
+ * Deprecated *not* passing a `\Throwable` to `RetryStrategyInterface::isRetryable()`
+ * Deprecated *not* passing a `\Throwable` to `RetryStrategyInterface::getWaitingTime()`
```
Comment (nicolas-grekas) [inline UPGRADE-5.1.md:77]: declaring instead of passing, since the argument is optional

File: src/Symfony/Component/Messenger/Retry/MultiplierRetryStrategy.php [hunk 3]
```diff
@@ -63,15 +63,23 @@ public function __construct(int $maxRetries = 3, int $delayMilliseconds = 1000,
         $this->maxDelayMilliseconds = $maxDelayMilliseconds;
     }
 
-    public function isRetryable(Envelope $message): bool
+    public function isRetryable(Envelope $message/*, \Throwable $throwable*/): bool
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Retry/MultiplierRetryStrategy.php:66]: the new argument should default to null, this is required to not break BC hardly in v6
also, all implementation must add the `@param` annotation, even if it duplicates the parent.
This tells "I did add the argument, don't throw a deprecation about this"

File: src/Symfony/Component/Messenger/Retry/RetryStrategyInterface.php [hunk 4]
```diff
@@ -20,10 +20,15 @@
...
+     */
+    public function isRetryable(Envelope $message/*, \Throwable $throwable*/): bool;
 
     /**
+     * @param \Throwable $throwable The cause of the failed handling
+     *
      * @return int The time to delay/wait in milliseconds
      */
-    public function getWaitingTime(Envelope $message): int;
+    public function getWaitingTime(Envelope $message/*, \Throwable $throwable*/): int;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Retry/RetryStrategyInterface.php:33]: see previous comments

File: src/Symfony/Component/Messenger/Retry/MultiplierRetryStrategy.php (hunk 3 above)
Comment (Braxilior) [reply src/Symfony/Component/Messenger/Retry/MultiplierRetryStrategy.php:66]: Does that mean that with the `@param` in the implementation the `trigger_deprecation` I added is now useless ?

Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Retry/MultiplierRetryStrategy.php:66]: actually, since the class is final, we can the argument for real on this one!

File: UPGRADE-6.0.md [hunk 5]
```diff
@@ -65,6 +65,8 @@ Messenger
  * Removed Doctrine transport. Run `composer require symfony/doctrine-messenger` to keep the transport in your application.
  * Removed RedisExt transport. Run `composer require symfony/redis-messenger` to keep the transport in your application.
  * Use of invalid options in Redis and AMQP connections now throws an error.
+ * The signature of method `RetryStrategyInterface::isRetryable()` has been updated to `RetryStrategyInterface::isRetryable(Envelope $message, ?\Throwable $throwable)`.
```
Comment (nicolas-grekas) [inline UPGRADE-6.0.md:68]: `\Throwable $ = null` we don't add the `?` when the default is `null` (same below and in the code)

**Review by nicolas-grekas — APPROVED** [review]

**Comment by ro0NL** [comment]
@chalasr i do think the BC promise needs a patch in general. See https://github.com/symfony/symfony-docs/issues/10504 for reference :)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Braxilior.
