### PR TITLE
[Cache] Fix invalidating tags on Redis <5

### LINKED ISSUE #42126: [Cache] invalidating tags breaks after updating to symfony/cache 5.3.3 with Redis versions below 5.x
symfony/cache: 5.3.3

**Description**
We are using a Redis version prior to Redis 5.x, Redis 3.2 to be precise. After upgrading the symfony/cache package to 5.3.3 we are experiencing a problem with flushing tags.

> RedisException
> ERR Error running script (call to f_cea3ea3b59f1b3411febbbeb5f94de8a695cec73): @user_script:19: @user_script: 19: Write commands not allowed after non deterministic commands. Call redis.replicate_commands() at the start of your script in order to switch to single commands replication mode.

**How to reproduce**
 - Upgrade symfony/cache to 5.3.3
 - Execute:

```php
$redis = new \Redis();
$redis->connect($_ENV['REDIS_SERVER'], $_ENV['REDIS_PORT']);
$redis->select((int) $_ENV['REDIS_DATABASE']);

$cachePool = new RedisTagAwareAdapter($redis, 'cacheable');
$cachePool->invalidateTags($tags);
```

This will trigger an error. 
> Cannot use object of type RedisException as array

To reveal the real exception, add to `symfony/cache/Adapter/RedisTagAwareAdapter.php:244` (after `EOLUA;`):
```php
foreach ($results as $id => $values) {
  if ($values instanceof \RedisException) {
      throw $values;
  }
}
```
**Possible Solution**

In order to enable script effects replication, you need to issue the following Lua command before any write operated by the script:
redis.replicate_commands()
The function returns true if the script effects replication was enabled, otherwise if the function was called after the script already called some write command, it returns false, and normal whole script replication is used

Another possible solution is to update ext-redis requirements to 5.x. Though this will be a BC break

**Additional context**
https://redis.io/commands/eval#replicating-commands-instead-of-scripts

### PR DESCRIPTION
**Pull request by wouterj**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #42126
| License       | MIT
| Doc PR        | -

https://redis.io/commands/eval#replicating-commands-instead-of-scripts

> Note: starting with Redis 5, the replication method described in this section (scripts effects replication) is the default and does not need to be explicitly enabled.
> 
> Starting with Redis 3.2, it is possible to select an alternative replication method. Instead of replicating whole scripts, we can just replicate single write commands generated by the script. We call this script effects replication.
>
> To enable script effects replication you need to issue the following Lua command before the script performs a write:
>
> ```
> redis.replicate_commands()
> ```

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
<5 instead of <3? What about doDeleteYieldTags()?

**Comment by wouterj** [comment]
> What about doDeleteYieldTags()?

This new replication method is only required when the commands are non deterministic. It seems like the `doDeleteYieldTags()` script is deterministic. For completeness, I've started a redis:3 container locally and ran the `RedisTagAwareAdapterTest` integration tests with this container. They all passed with the changes in this PR.

I've also updated the PR to handle any exception better. Currently, users get a PHP Error: "Cannot use object of type RedisException as array". After this PR, they'll get the actual redis exception.

**Comment by nicolas-grekas** [comment]
For my understanding, when did you encounter `RedisException` being returned? Is that a dev-time only issue or can this happen in regular operations? I'm asking because the cache adapters are not supposed to fail when there is an issue.

**Comment by wouterj** [comment]
We had this occur when invalidating caches in production.

I'm not sure what would be the best way forward. If there is an error, nothing is invalidated. So simply logging the exception and retuning would probably not be correct either.

**Comment by nicolas-grekas** [comment]
Do you know what the `RedisException` was about?

File: src/Symfony/Component/Cache/Adapter/RedisTagAwareAdapter.php [hunk 1]
```diff
@@ -159,6 +159,10 @@ protected function doDeleteYieldTags(array $ids): iterable
         });
 
         foreach ($results as $id => $result) {
+            if ($result instanceof \RedisException) {
+                throw $result;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Cache/Adapter/RedisTagAwareAdapter.php]: I think we'd better throw the exception after the foreach is over

File: src/Symfony/Component/Cache/Adapter/RedisTagAwareAdapter.php [hunk 2]
```diff
@@ -234,14 +240,22 @@ protected function doInvalidate(array $tagIds): bool
...
             local cursor = table.remove(ARGV)
             redis.call('SREM', '{'..id..'}'..id, unpack(ARGV))
 
             return redis.call('SSCAN', '{'..id..'}'..id, cursor, 'COUNT', 5000)
 EOLUA;
 
-        foreach ($results as $id => [$cursor, $ids]) {
+        foreach ($results as $id => $values) {
+            if ($values instanceof \RedisException) {
+                throw $values;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Cache/Adapter/RedisTagAwareAdapter.php]: here also: better finish the foreach and return false when there is an exception

**Comment by wouterj** [comment]
> Do you know what the RedisException was about?

Yeah, it was about the error in the lua script that is fixed in this PR:

> ERR Error running script (call to f_cea3ea3b59f1b3411febbbeb5f94de8a695cec73): @user_script:19: @user_script: 19: Write commands not allowed after non deterministic commands. Call redis.replicate_commands() at the start of your script in order to switch to single commands replication mode.

So in theory, you will not get this exception. But I don't know anything about Redis, so I guess maybe there is something else in this script that breaks for e.g. Redis 4 or Redis 6 in the future?

**Comment by nicolas-grekas** [comment]
Can we call `CacheItem::log` when we have the exception somehow?

**Comment by jderusse** [comment]
> So in theory, you will not get this exception. But I don't know anything about Redis, so I guess maybe there is something else in this script that breaks for e.g. Redis 4 or Redis 6 in the future?

method `SSCAN` is not deterministic (because `SETs` are unordered), that's why, in Redis 4, you have to tell Redis to replicate commands.

more info https://redis.io/commands/eval#replicating-commands-instead-of-scripts and https://redis.io/commands/EVAL#scripts-with-deterministic-writes

**Comment by wouterj** [comment]
> Can we call `CacheItem::log` when we have the exception somehow?

Oh, didn't know about this helper method. I've updated the PR with your suggestions: any exception is now logged and not thrown, and `doInvalidateTags()` nows returns `false` when there was an exception.

**Review by nicolas-grekas — APPROVED** [review]
(once psalm failure is fixed)

**Review by chalasr — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @wouterj.
