### PR TITLE
Fix exceptions (PDOException) error code type

### LINKED ISSUE #33704: [Messenger] HandlerFailedException does not handle PDOException with string error code
**Symfony version(s) affected**: 4.3

**Description**  
Pdo throws exception with error code 'HY000', and Symfony Messenger component generates exception because of that in:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/Exception/HandlerFailedException.php#L32

```
Error(code: 0): Wrong parameters for Symfony\\Component\\Messenger\\Exception\\HandlerFailedException([string $message [, long $code [, Throwable $previous = NULL]]]) at /var/www/html/vendor/symfony/messenger/Exception/HandlerFailedException.php:29)
[stacktrace]
#0 /var/www/html/vendor/symfony/messenger/Exception/HandlerFailedException.php(29): Exception->__construct('SQLSTATE[HY000]...', 'HY000', Object(Doctrine\\DBAL\\Driver\\PDOException))
```

as described in: https://www.php.net/manual/en/exception.getcode.php
getCode could return mixed, which is not handled in code:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/Exception/HandlerFailedException.php#L32

and passed to constructor that requires int:
https://www.php.net/manual/en/exception.construct.php

**How to reproduce**  
throw exception inside Messenger handler:
```
throw new \PDOException('test', 'HY000');
```

**Possible Solution**  
cast it to int or set zero in case of string here:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/Exception/HandlerFailedException.php#L32

### PR DESCRIPTION
**Pull request by ed-fruty**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #33704
| License       | MIT

From the [php.net docs](https://www.php.net/manual/en/exception.getcode.php) `Exception::getCode()` description:

> Returns the exception code as integer in Exception but possibly as other type in Exception descendants (for example as **string** in PDOException).

So if can be string, we convert it to the int in the `HandlerFailedException` but it still string in `nestedExceptiions`.

### CODE REVIEW

File: src/Symfony/Component/Messenger/Tests/Exception/HandlerFailedExceptionTest.php [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+        };
+
+        $exceptions = [$pdoException];
+
+        $handlerException = new HandlerFailedException($envelope, $exceptions);
+
+        $this->assertIsInt(
+            $handlerException->getCode(),
+            'All exception codes must converts to int'
+        );
```
Comment (fabpot) [inline src/Symfony/Component/Messenger/Tests/Exception/HandlerFailedExceptionTest.php]: Small nitpick: can be on one line (same for the next one)

**Review by fabpot — CHANGES_REQUESTED** [review]
If the code can be a string, maybe we can change the type hint and allow a string everywhere? Casting to a string means that strings will always be converted to 0, right? Not sure if this is a problem though.

**Comment by ed-fruty** [comment]
We can't allow `string` type.
```bash
php -a
php > $e = new Exception('message', 'string');

PHP Warning:  Uncaught Error: Wrong parameters for Exception([string $message [, long $code [, Throwable $previous = NULL]]]) in php shell code:1
Stack trace:
#0 php shell code(1): Exception->__construct('message', 'string')
#1 {main}
  thrown in php shell code on line 1
```

PHP does not allow it.

File: src/Symfony/Component/Messenger/Tests/Exception/HandlerFailedExceptionTest.php (hunk 1 above)
Comment (ed-fruty) [reply src/Symfony/Component/Messenger/Tests/Exception/HandlerFailedExceptionTest.php]: done

Comment (fabpot) [reply src/Symfony/Component/Messenger/Tests/Exception/HandlerFailedExceptionTest.php]: forgot to push?

Comment (ed-fruty) [reply src/Symfony/Component/Messenger/Tests/Exception/HandlerFailedExceptionTest.php]: [Done for all asserts](https://github.com/symfony/symfony/pull/33713/files#diff-7a30e63fcf1a036cde8c651fb3fd664cR27)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @ed-fruty.
