### PR TITLE
[Validator] validate nested constraints only if they are in the same group

### LINKED ISSUE #46638: [Validator] AtLeastOneOf wrong behavior with groups
### Symfony version(s) affected

5.4

### Description

If you have several validation groups, you get unexpected behavior, validation not working 

```php
class AtLeastOneOfValidator extends ConstraintValidator
{
    public function validate($value, Constraint $constraint)
    {

        ...

        foreach ($constraint->constraints as $key => $item) {

            // validator will be skipped, because group is different, violations will be empty, and validation will be passed without check 
            $violations = $validator->inContext($executionContext)->validate($value, $item, $this->context->getGroup())->getViolations();

            if (\count($this->context->getViolations()) === \count($violations)) {
                return;
            }

           ...

        }
    }
}
```

### How to reproduce

First, run "composer require symfony/validator"
Then, execute this file:
```php

<?php
require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Validation;

$age = 60;
$constraints = [
    new Assert\AtLeastOneOf([
        new Assert\Blank(),
        new Assert\Range(
            min: 18,
            max: 55,
            groups: ['adult']
        ),
    ]),
];

$validator = Validation::createValidator();
$violations = $validator->validate($age, $constraints, groups: ['Default', 'adult']);

echo(sprintf('count: %d, violations: %s',count($violations), $violations));
```

**Expected**: Failed violation, because 60 > 55, but validation is passed

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #46638
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by welcoMattic — APPROVED** [review]

**Review by ogizanagi — APPROVED** [review]

File: src/Symfony/Component/Validator/Constraints/AtLeastOneOfValidator.php [hunk 1]
```diff
@@ -34,6 +34,10 @@ public function validate($value, Constraint $constraint)
         $messages = [$constraint->message];
 
         foreach ($constraint->constraints as $key => $item) {
+            if (!in_array($this->context->getGroup(), $item->groups, true)) {
```
Comment (ogizanagi) [inline src/Symfony/Component/Validator/Constraints/AtLeastOneOfValidator.php]: Is there is similar issue somehow with the [`SequentiallyValidator`](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Validator/Constraints/SequentiallyValidator.php), or is this only necessary because of the [clone](https://github.com/symfony/symfony/pull/39872/files#diff-ffba2bed571e18a91782556cc0ca76152bcb556bd1a83590e733f4784e7c88f4R368-R371) method which does only copy violation now?

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Are the test broken by this PR?

**Comment by xabbuh** [comment]
I'm gonna check.

**Comment by fabpot** [comment]
fabbot issue should be fixed IMO.

File: src/Symfony/Component/Validator/Constraints/AtLeastOneOfValidator.php (hunk 1 above)
Comment (xabbuh) [reply src/Symfony/Component/Validator/Constraints/AtLeastOneOfValidator.php]: The code works as expected if I don't miss anything (I am going to investigate what's the actual difference). But I took the chance and added another test case to the `SequentiallyValidatorTest` class to make sure that we not break it there in the future.

**Comment by xabbuh** [comment]
> Are the test broken by this PR?

I rebased, the tests were actually already fixed before by #47203

**Comment by fabpot** [comment]
Thank you @xabbuh.

File: src/Symfony/Component/Validator/Constraints/AtLeastOneOfValidator.php (hunk 1 above)
Comment (xabbuh) [reply src/Symfony/Component/Validator/Constraints/AtLeastOneOfValidator.php]: Got it, the explanation is that the exit condition is different. In `AtLeastOneOfValidator` we abort as soon as we have a constraint that does not add any additional violation (which is always the case if the constraint is not part of the current group).

Comment (ogizanagi) [reply src/Symfony/Component/Validator/Constraints/AtLeastOneOfValidator.php]: Alright, thx for the double-check
