### PR TITLE
[Dotenv] Fix preloading warning by replacing anonymous exception class

### LINKED ISSUE #63764: PHP warning when preloading Dotenv.php
### Symfony version(s) affected

7.4.7

### Description

When preloading our project with
```ini
opcache.preload=/path-to-my-project/var/build/prod/App_KernelProdContainer.preload.php
```
we get the following warning:
```txt
PHP Warning:  Can't preload unlinked class LogicException@anonymous: Unknown interface Symfony\Component\Dotenv\Exception\ExceptionInterface in /path-to-my-project/vendor/symfony/dotenv/Dotenv.php on line 642
```

Line 642 is this:
```php
            throw new class('Too many levels of variable indirection in env vars: '.implode(', ', array_keys($resolved)).'.') extends \LogicException implements ExceptionInterface {};
```

### How to reproduce

Preload a symfony project

### Possible Solution

_No response_

### Additional Context

We are using PHP 8.3.2

### PR DESCRIPTION
**Pull request by Amoifr**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63764
| License       | MIT

## Summary

When opcache preloading is enabled, PHP emits a warning:
```
PHP Warning: Can't preload unlinked class LogicException@anonymous: Unknown interface Symfony\Component\Dotenv\Exception\ExceptionInterface
```

This happens because the anonymous exception class at line 765 implements `ExceptionInterface`, but PHP can't resolve this interface during preloading.

## Solution

Replace the anonymous exception class with a named `VariableCircularReferenceException` class, following the same pattern as other exceptions in the component (`PathException`, `FormatException`).

### CODE REVIEW

File: src/Symfony/Component/Dotenv/Exception/VariableCircularReferenceException.php [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+ * @author Fabien Potencier <fabien@symfony.com>
+ */
+final class VariableCircularReferenceException extends \LogicException implements ExceptionInterface
+{
+    /**
+     * @param string[] $unresolvedVars
+     */
+    public function __construct(array $unresolvedVars)
+    {
+        parent::__construct('Too many levels of variable indirection in env vars: '.implode(', ', $unresolvedVars).'.');
```
Comment (stof) [inline src/Symfony/Component/Dotenv/Exception/VariableCircularReferenceException.php]: I would keep the message in the place throwing the exception (as done before) instead of hardcoding it inside the constructor.

**Comment by derrabus** [comment]
According to the bug report, the 7.4 branch is affected by this bug. Please rebase your changes onto 7.4 and target that branch. If 6.4 is also affected (haven't checked), please target 6.4 instead.

see https://symfony.com/doc/current/contributing/code/pull_requests.html#choose-the-right-branch

File: src/Symfony/Component/Dotenv/Exception/VariableCircularReferenceException.php (hunk 1 above)
Comment (Amoifr) [reply src/Symfony/Component/Dotenv/Exception/VariableCircularReferenceException.php]: @stof 
 Thanks for catching that! You're right, I went a bit too fast on this one. Fixed — the message is now built at the throw site as it was before. 👍

**Comment by Amoifr** [comment]
@derrabus 

Thanks for the heads up! I've rebased the changes onto 6.4 since the bug is indeed present there as well. The PR now targets the correct branch. 👍

**Comment by derrabus** [comment]
We could adjust the test to expect your new exception class instead of the generic `LogicException`.

https://github.com/symfony/symfony/blob/bc616d48cbe2aaf8318df34e1b585d32deb3010b/src/Symfony/Component/Dotenv/Tests/DotenvTest.php#L649-L650

**Comment by Amoifr** [comment]
Thanks @derrabus for the suggestion! 👍

You're absolutely right — I went a bit too fast and missed updating the test to use the new `VariableCircularReferenceException` class instead of the generic `LogicException`.

I've just pushed a fix for that. Thanks for catching it!

**Review by derrabus — APPROVED** [review]

**Comment by xabbuh** [comment]
@Amoifr Did you forget pushing the test update?

**Comment by Amoifr** [comment]
@xabbuh You're right, I had pushed to the wrong branch by mistake. It's fixed now — the test update is there. Sorry for the confusion!

**Review by xabbuh — APPROVED** [review]

**Review by stof — APPROVED** [review]

File: src/Symfony/Component/Dotenv/Exception/VariableCircularReferenceException.php [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\Dotenv\Exception;
+
+/**
+ * Thrown when there are too many levels of variable indirection in env vars.
+ *
+ * @author Fabien Potencier <fabien@symfony.com>
```
Comment (alexandre-daubois) [inline src/Symfony/Component/Dotenv/Exception/VariableCircularReferenceException.php]: I think this should be changed/removed before merging (apart if Fabien wrote this code somewhere else and you picked it in this PR?)

Comment (Amoifr) [reply src/Symfony/Component/Dotenv/Exception/VariableCircularReferenceException.php]: Good catch! I copied the standard header and forgot to update the `@author` tag. Fixed! 😅

**Comment by Amoifr** [comment]
Thanks @alexandre-daubois for the review! Fixed the `@author` tag. Ready for another look! 🙏

**Review by alexandre-daubois — APPROVED** [review]

**Review by GromNaN — APPROVED** [review]

**Comment by alexandre-daubois** [comment]
Thank you @Amoifr.
