### PR TITLE
[Validator] Fix AbstractComparison deprecation triggered for array values

### LINKED ISSUE #62358: [Validator] AbstractComparison cannot recognize an array due to deprecation check
### Symfony version(s) affected

7.3

### Description

When using `AbstractComparison` constraint to compare a value to an array, e.g.

```
new Assert\NotIdenticalTo(value: []),
```

The deprecation is still emmited because the code checks if the value is an array or not.

### How to reproduce

Just use a constraint extending from `AbstractComparison`  class and check for an array value:

```
new Assert\NotIdenticalTo(value: []),
```

### PR DESCRIPTION
**Pull request by lacatoire**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #62358
| License       | MIT

When passing an array as the comparison value using named arguments (e.g. `new NotIdenticalTo(value: [])`), the deprecation for the old options-array constructor style was incorrectly triggered.

The root cause is that `is_array($value)` cannot distinguish between the legacy options array format (`new NotIdenticalTo(['value' => 5, 'message' => '...'])`) and a legitimate array value passed via named arguments (`new NotIdenticalTo(value: [])`).

This PR adds an `array_is_list()` check: list arrays (empty `[]` or sequential `[1,2,3]`) are treated as actual comparison values, while associative arrays are treated as the deprecated options format.

### CODE REVIEW

**Comment by stof** [comment]
The 7.3 branch only receives security fixes now. We will merge this in 7.4 (we can rebase it with our merge tool if you don't do it yourselves)

**Comment by lacatoire** [comment]
Sorry for the ping maintainers, i missed up

File: src/Symfony/Component/Validator/Tests/Constraints/NotIdenticalToTest.php [hunk 1]
```diff
@@ -20,6 +20,24 @@
...
+    {
+        $constraint = new NotIdenticalTo(value: []);
+        self::assertSame([], $constraint->value);
+
+        $constraint = new NotIdenticalTo(value: [1, 2, 3]);
+        self::assertSame([1, 2, 3], $constraint->value);
+    }
+
+    /**
+     * @group legacy
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Tests/Constraints/NotIdenticalToTest.php]: needs to be an attribute now, see existing legacy tests

**Review by nicolas-grekas — COMMENTED** [review]
please always add the table from the template to the PR description

**Comment by nicolas-grekas** [comment]
Thank you @lacatoire.
