### PR TITLE
[DependencyInjection] fixes validation of non-scalar attribute values

### LINKED ISSUE #48956: [DependencyInjection] incomplete support for arrays in tag attribute values
### Symfony version(s) affected

6.2

### Description

PR #47364 introduced support for using arrays in tag attribute values.

However the feature is not currently usable because such values are rejected by the `CheckDefinitionValidityPass`.  

### How to reproduce

The following service configuration:
```php
$configurator->services()
  ->set(Foo::class)
  ->tag('foo', ['bar' => ['baz' => 42]);
```
throws:
```
[Symfony\Component\DependencyInjection\Exception\RuntimeException]
at symfony/dependency-injection/Compiler/CheckDefinitionValidityPass.php line 67:
A "tags" attribute must be of a scalar-type for service "App\Foo", tag "foo", attribute "bar".
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ju1ius**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #48956
| License       | MIT
| Doc PR        | None

As a follow-up to #47364, this PR updates the `CheckDefinitionValidityPass` to allow (possibly nested) arrays of scalars in service tags attribute values.
Please see #48956 for context.

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Compiler/CheckDefinitionValidityPass.php [hunk 1]
```diff
@@ -87,4 +83,16 @@ public function process(ContainerBuilder $container)
...
     }
+
+    private function validateTagAttributes(string $id, string $tag, array $attributes, array $path = []): void
+    {
+        foreach ($attributes as $name => $value) {
+            if (\is_array($value)) {
+                $this->validateTagAttributes($id, $tag, $value, [...$path, $name]);
+            } elseif (!\is_scalar($value) && null !== $value) {
+                $name = implode('.', [...$path, $name]);
+                throw new RuntimeException(sprintf('A "tags" attribute must be of a scalar-type for service "%s", tag "%s", attribute "%s".', $id, $tag, $name));
```
Comment (ju1ius) [inline src/Symfony/Component/DependencyInjection/Compiler/CheckDefinitionValidityPass.php:94]: I chose to report  the path to the offending value here because that's what's been done in #47364.
I find this confusing however. For example in that case:
```php
$services->set('example', Example::class)
  ->tag('a', ['foo.bar.baz' => new class{}])
  ->tag('a', ['foo' => ['bar' => ['baz' => new class{}]]);
```
The error message would be:
```
A "tags" attribute must be of a scalar-type for service "example", tag "a", attribute "foo.bar.baz".
```

IMO it would be better to just report the real (top-level) attribute name instead.

WDYT?

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Compiler/CheckDefinitionValidityPass.php:94]: let's be consistent, it's understandable enough to me

Code wise, let's  use a string instead of an array for the path, like done in #47364.

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/CheckDefinitionValidityPassTest.php [hunk 2]
```diff
@@ -80,21 +80,46 @@ public function testValidTags()
...
         $this->expectException(RuntimeException::class);
+        $this->expectExceptionMessage($message);
         $container = new ContainerBuilder();
-        $container->register('a', 'class')->addTag('foo', ['bar' => ['baz' => 'baz']]);
-
+        $container->register('a', 'class')->addTag($name, $attributes);
         $this->process($container);
     }
 
+    public function provideInvalidTags(): iterable
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Compiler/CheckDefinitionValidityPassTest.php]: should be static (will be asked by phpunit 10 for providers)

Comment (ju1ius) [reply src/Symfony/Component/DependencyInjection/Tests/Compiler/CheckDefinitionValidityPassTest.php]: OK, I didn't know about that 👍🏻

File: src/Symfony/Component/DependencyInjection/Compiler/CheckDefinitionValidityPass.php (hunk 1 above)
Comment (ju1ius) [reply src/Symfony/Component/DependencyInjection/Compiler/CheckDefinitionValidityPass.php:94]: > Code wise, let's use a string instead of an array for the path

Well, the code in the #47364. is actually incorrect...
For the previous example, it reports `bar.baz` instead of `foo.bar.baz`.
IMO using a stack is both clearer (intent) and simpler (less conditionals), but I won't die for this idea.

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Compiler/CheckDefinitionValidityPass.php:94]: Can you fix the code in this PR also please? not sure what you mean about the complexity of using string, I see none :)
Can you give it a try?

Comment (ju1ius) [reply src/Symfony/Component/DependencyInjection/Compiler/CheckDefinitionValidityPass.php:94]: The alternative would look like this:
```php
$this->validateTagAttributes($id, $tag, $value, '' === $path ? $name : "{$path}.{$name}");
```
Which is longer, less declarative and less readable to me.
Do you confirm you want this?

Comment (ju1ius) [reply src/Symfony/Component/DependencyInjection/Compiler/CheckDefinitionValidityPass.php:94]: > not sure what you mean about the complexity of using string

Well, implementing this using a string actually took me two attempts to get it right (vs just one using a stack).
And I believe it to be the reason why #47364 got it wrong in the first place.

> Can you fix the code in this PR also please?

Sure can.  Before I can proceed, I just need a confirmation on this style-related point.

Comment (ju1ius) [reply src/Symfony/Component/DependencyInjection/Compiler/CheckDefinitionValidityPass.php:94]: > Can you fix the code in this PR also please?

Also, if I'm going to fix this issue, there's no need to keep consistency with a buggy behaviour, so we might as well just report the top-level attribute instead of the full path to the value.

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Compiler/CheckDefinitionValidityPass.php:94]: got it, let's go with the stack everywhere!

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @ju1ius.
