### PR TITLE
[Asset] Allows to download asset manifest over HTTP

### LINKED ISSUE #33001: Symfony Asset JsonManifestVersionStrategy doesn't work with UrlPackage.
**Symfony version(s) affected**: 4.3 Symfony Asset component

**Description**  

Symfony Asset JsonManifestVersionStrategy doesn't work with UrlPackage. 

**How to reproduce**  

I'm creating a MediaWiki Skin and the CSS is generated from https://invent.kde.org/websites/aether-sass using Symfony Encore. The code is:

```php

$urlPackage = new UrlPackage(
    'https://cdn.kde.org/',
    new JsonManifestVersionStrategy('https://cdn.kde.org/aether-devel/version/manifest.json')
);

$out->addStyle( $urlPackage->getUrl('aether-devel/version/bootstrap.css'), 'all' );
 ```

**Possible Solution**  

I created a potential patch: https://invent.kde.org/websites/aether-mediawiki/blob/master/JsonManifestNetworkStrategy.php that remove the check that the file exist and instead check if `file_get_contents($this->manifestPath)` returned something. If this solution is good enough to be accepted, I will create a pull request :)

PS: I hope it's the right place to report a bug in Symfony component

### LINKED ISSUE #35761: [Asset][RFC] Support remote manifest.json
**Description**
The `JsonManifestVersionStrategy` requires the `manifest.json` to be a local file. That is checked with [`file_exists`](https://github.com/symfony/symfony/blob/v5.0.4/src/Symfony/Component/Asset/VersionStrategy/JsonManifestVersionStrategy.php#L56).

I would like to download a manifest over HTTP from a remote service that exposes assets.
- The case is a set of js libraries (mainly ads & partners related) shared with multiple websites.
- This libraries can be updated anytime in a backward-compatible way. I don't want to deploy a new configuration of my application to get updates.
- Assets are served with very long TTL (or `Cache-Control: immutable`) to get the best browser performances (i.e. a high score in Google Page Speed).

**Example**

[Existing](https://symfony.com/doc/current/frontend/encore/versioning.html#loading-assets-from-entrypoints-json-manifest-json):
```yaml
framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
```

Expected:
```yaml
framework:
    assets:
        json_manifest_url: 'https://cdn.example.com/manifest.json'
```

Implementation:
- The HttpClient component should be used and injected in the new `**VersionStrategy`.
- Cache policy can be configured on HttpClient level. Directives like `stale-while-revalidate` and `stale-if-error` will be recommended.

### PR DESCRIPTION
**Pull request by GromNaN**
| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #35761 Fix #33001
| License       | MIT
| Doc PR        | symfony/symfony-docs#13255

```yaml
framework:
    assets:
        json_manifest_path: 'https://cdn.example.com/manifest.json'
```

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 1]
```diff
@@ -576,6 +576,7 @@ private function addAssetsSection(ArrayNodeDefinition $rootNode)
                         ->scalarNode('version')->defaultNull()->end()
                         ->scalarNode('version_format')->defaultValue('%%s?%%s')->end()
                         ->scalarNode('json_manifest_path')->defaultNull()->end()
+                        ->scalarNode('json_manifest_url')->defaultNull()->end()
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: can't we allow passing a URL to `json_manifest_path` instead?

**Review by nicolas-grekas — COMMENTED** [review]
Please mind the CI.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php (hunk 1 above)
Comment (OskarStark) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: But in this case rename the option (+deprecation) to json_manifest too?

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: the less deprecation the better to me...

Comment (OskarStark) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: Same opinion on this, but the DX would be worse. We can fix this issue in the docs, sure

Comment (GromNaN) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: Sure, http(s) urls can be detected like this:
https://github.com/symfony/symfony/pull/35762/files#diff-0e793081ceb720201745c982a568903fR1049
`'http' === substr(parse_url($jsonManifestPath, \PHP_URL_SCHEME), 0, 4)`

**Comment by GromNaN** [comment]
PR updated, tests fixed (error related to time-sensible test `Symfony\Component\Cache\Tests\Adapter\MemcachedAdapterTest::testGetMetadata`)

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 2]
```diff
@@ -1045,7 +1045,12 @@ private function createVersion(ContainerBuilder $container, ?string $version, ?s
         }
 
         if (null !== $jsonManifestPath) {
-            $def = new ChildDefinition('assets.json_manifest_version_strategy');
+            $definitionName = 'assets.json_manifest_version_strategy';
+            if ('http' === substr(parse_url($jsonManifestPath, \PHP_URL_SCHEME), 0, 4)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: the `\` should be removed + we prefer `0 === strpos` usually

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/assets.xml [hunk 3]
```diff
@@ -50,5 +50,10 @@
         <service id="assets.json_manifest_version_strategy" class="Symfony\Component\Asset\VersionStrategy\JsonManifestVersionStrategy" abstract="true">
             <argument /> <!-- manifest path -->
         </service>
+
+        <service id="assets.remote_json_manifest_version_strategy" class="Symfony\Component\Asset\VersionStrategy\RemoteJsonManifestVersionStrategy" abstract="true">
+            <argument /> <!-- manifest url -->
+            <argument type="service" id="http_client"/>
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/assets.xml]: missing space before `/`

File: src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/FrameworkExtensionTest.php [hunk 4]
```diff
@@ -556,6 +556,11 @@ public function testAssets()
         $versionStrategy = $container->getDefinition((string) $package->getArgument(1));
         $this->assertEquals('assets.json_manifest_version_strategy', $versionStrategy->getParent());
         $this->assertEquals('/path/to/manifest.json', $versionStrategy->getArgument(0));
+
+        $package = $container->getDefinition((string) $packages['remote_manifest']);
+        $versionStrategy = $container->getDefinition((string) $package->getArgument(1));
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/FrameworkExtensionTest.php]: the casts to string should be removed

File: src/Symfony/Bundle/FrameworkBundle/composer.json [hunk 5]
```diff
@@ -32,7 +32,7 @@
     "require-dev": {
         "doctrine/annotations": "~1.7",
         "doctrine/cache": "~1.0",
-        "symfony/asset": "^4.4|^5.0",
+        "symfony/asset": "^5.1",
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/composer.json]: the conflict rule should be updated accordingly

File: src/Symfony/Component/Asset/Tests/VersionStrategy/RemoteJsonManifestVersionStrategyTest.php [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+use Symfony\Component\HttpClient\MockHttpClient;
+use Symfony\Component\HttpClient\Response\MockResponse;
+
+class RemoteJsonManifestVersionStrategyTest extends TestCase
+{
+    public function testGetVersion()
+    {
+        $strategy = $this->createStrategy('https://cdn.example.com/manifest-valid.json');
+
+        $this->assertEquals('main.123abc.js', $strategy->getVersion('main.js'));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Asset/Tests/VersionStrategy/RemoteJsonManifestVersionStrategyTest.php]: assertSame everywhere

File: src/Symfony/Component/Asset/Tests/VersionStrategy/RemoteJsonManifestVersionStrategyTest.php [hunk 7]
```diff
@@ -0,0 +1,71 @@
...
+    {
+        $this->expectException('RuntimeException');
+        $this->expectExceptionMessage('Error parsing JSON');
+        $strategy = $this->createStrategy('https://cdn.example.com/manifest-invalid.json');
+        $strategy->getVersion('main.js');
+    }
+
+    private function createStrategy($manifestUrl)
+    {
+        $this->httpClient = new MockHttpClient(function ($method, $url, $options) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Asset/Tests/VersionStrategy/RemoteJsonManifestVersionStrategyTest.php]: no need for a property here, isn't it?

File: src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php [hunk 8]
```diff
@@ -0,0 +1,66 @@
...
+{
+    private $manifestData;
+    private $httpResponse;
+
+    /**
+     * @param string $manifestUrl Absolute url to the manifest file
+     */
+    public function __construct(string $manifestUrl, HttpClientInterface $httpClient)
+    {
+        $this->httpResponse = $httpClient->request('GET', $manifestUrl);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php]: clever, async = lazy :)
I'd suggest adding `['buffer' => true]` as option

File: src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php [hunk 9]
```diff
@@ -0,0 +1,66 @@
...
+
+    public function applyVersion(string $path)
+    {
+        return $this->getManifestPath($path) ?: $path;
+    }
+
+    private function getManifestPath(string $path): ?string
+    {
+        if (null === $this->manifestData) {
+            $this->manifestData = json_decode($this->httpResponse->getContent(), true);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php]: better use `->toArray()` and catching the DecodingExceptionInterface, don't you think?

File: src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php [hunk 10]
```diff
@@ -0,0 +1,66 @@
...
+            if (0 < json_last_error()) {
+                throw new \RuntimeException(sprintf('Error parsing JSON from asset manifest file "%s" - %s', $this->httpResponse->getInfo()['url'], json_last_error_msg()));
+            }
+        }
+
+        return isset($this->manifestData[$path]) ? $this->manifestData[$path] : null;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php]: `??` to the rescue

File: src/Symfony/Component/Asset/composer.json [hunk 11]
```diff
@@ -23,7 +23,8 @@
     },
     "require-dev": {
         "symfony/http-foundation": "^4.4|^5.0",
-        "symfony/http-kernel": "^4.4|^5.0"
+        "symfony/http-kernel": "^4.4|^5.0",
+        "symfony/http-client": "^4.4|^5.0"
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Asset/composer.json]: alpha order

**Review by nicolas-grekas — COMMENTED** [review]
LGTM, here are some nitpicking.

File: src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php (hunk 8 above)
Comment (GromNaN) [reply src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php]: - 👍 for buffering.
- I need to check that an HTTP request is not fired on pages that don't use the asset package.
- I'll add the `accept: application/json` header, because that's what we expect.

File: src/Symfony/Component/Asset/Tests/VersionStrategy/RemoteJsonManifestVersionStrategyTest.php (hunk 7 above)
Comment (GromNaN) [reply src/Symfony/Component/Asset/Tests/VersionStrategy/RemoteJsonManifestVersionStrategyTest.php]: Indeed.

File: src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php (hunk 9 above)
Comment (GromNaN) [reply src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php]: Is there any way to serve the cache if the response is not a valid JSON ?

File: src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/FrameworkExtensionTest.php (hunk 4 above)
Comment (GromNaN) [reply src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/FrameworkExtensionTest.php]: Fixed on all this test class.

File: src/Symfony/Component/Asset/Tests/VersionStrategy/RemoteJsonManifestVersionStrategyTest.php (hunk 6 above)
Comment (GromNaN) [reply src/Symfony/Component/Asset/Tests/VersionStrategy/RemoteJsonManifestVersionStrategyTest.php]: Fixed on all tests under `Symfony\Component\Asset\Tests\VersionStrategy`.

File: src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php (hunk 10 above)
Comment (GromNaN) [reply src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php]: Fixed in `JsonManifestVersionStrategy` too.

File: src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php (hunk 8 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php]: > I need to check that an HTTP request is not fired on pages that don't use the asset package.

one will be issued when this class is instantiated for sure.

File: src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php (hunk 9 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php]: what does "serve the cache" mean here?

File: src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php [hunk 12]
```diff
@@ -0,0 +1,76 @@
...
+        return $this->getManifestPath($path) ?: $path;
+    }
+
+    private function getManifestPath(string $path): ?string
+    {
+        if (null === $this->manifestData) {
+            try {
+                $this->manifestData = $this->httpResponse->toArray();
+            } catch (ExceptionInterface $e) {
+                throw new \RuntimeException(sprintf('Error loading asset manifest from url "%s"', $this->httpResponse->getInfo()['url']), 0, $e);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php]: why not let the original exception bubble down?

File: src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php [hunk 13]
```diff
@@ -0,0 +1,76 @@
...
+{
+    private $manifestData;
+
+    /**
+     * @var ResponseInterface
+     */
+    private $httpResponse;
+
+    /**
+     * @param string $manifestUrl Absolute url to the manifest file
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php]: URL

File: src/Symfony/Component/Asset/VersionStrategy/JsonManifestVersionStrategy.php [hunk 14]
```diff
@@ -63,6 +63,6 @@ private function getManifestPath(string $path): ?string
             }
         }
 
-        return isset($this->manifestData[$path]) ? $this->manifestData[$path] : null;
+        return $this->manifestData[$path] ?? null;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Asset/VersionStrategy/JsonManifestVersionStrategy.php]: Please revert all changes that are not needed for the PR to be complete.
Please submit them as a separate PR on a lower branch if you're up to (this one on 4.4, the other on 3.4 I suppose?)

Comment (GromNaN) [reply src/Symfony/Component/Asset/VersionStrategy/JsonManifestVersionStrategy.php]: Of course, I didn't think to the maintainability issues implies by this change on master.

Comment (GromNaN) [reply src/Symfony/Component/Asset/VersionStrategy/JsonManifestVersionStrategy.php]: Reverted.

PR done for assertions in 3.4 (https://github.com/symfony/symfony/pull/35793).
Regarding your comment https://github.com/symfony/symfony/pull/33225#issuecomment-522338660, I'm not sure if I should submit a PR to convert `isset` to null coalescing.

File: src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php (hunk 9 above)
Comment (GromNaN) [reply src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php]: I mean, using `stale-if-error` cache directive, if the http request fails (timeout, 500 ...) the cached response should be returned by the http client. But if the clients returns an invalid response with status code 200 (not a JSON response). I wonder if the stale cache could be used. I the current use-case, this is a valuable behavior.

File: src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php (hunk 12 above)
Comment (GromNaN) [reply src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php]: That gives some added context, isn't it ?

File: src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php (hunk 8 above)
Comment (GromNaN) [reply src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php]: The HTTP request is issued even when using the command. That would be an issue.

I'm moving the request to the first call to `getManifestPath`.
If one needs to preload the manifest, it might be possible to make the request earlier with an other mecanism (a listener on `kernel.request`).

File: src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php (hunk 12 above)
Comment (GromNaN) [reply src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php]: When the `toArray` is called on an invalid response, [`JsonException` message](https://github.com/symfony/symfony/blob/v5.0.4/src/Symfony/Component/HttpClient/Response/ResponseTrait.php#L156) is only `Syntax error`. That doesn't give any context on the URL that failed.

**Comment by nicolas-grekas** [comment]
Let's improve the HttpClient component then!

File: src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php [hunk 15]
```diff
@@ -0,0 +1,68 @@
...
+    {
+        return $this->getManifestPath($path) ?: $path;
+    }
+
+    private function getManifestPath(string $path): ?string
+    {
+        if (null === $this->manifestData) {
+            $this->manifestData = $this->httpClient->request('GET', $this->manifestUrl, [
+                'headers' => ['accept' => 'application/json'],
+                'buffer' => true,
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php]: not needed anymore since you read it only once now.

File: src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php [hunk 16]
```diff
@@ -0,0 +1,68 @@
...
+    {
+        return $this->applyVersion($path);
+    }
+
+    public function applyVersion(string $path)
+    {
+        return $this->getManifestPath($path) ?: $path;
+    }
+
+    private function getManifestPath(string $path): ?string
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php]: I'd suggest merging this with the previous method.

**Review by nicolas-grekas — COMMENTED** [review]
Would it make sense to wrap the call behind a CacheInterface or is this already cached elsewhere? Won't this download again and again the same file while we could avoid that?

**Comment by GromNaN** [comment]
Absolutely, it needs to be cached. And the cache needs to be served in case of error. IMO this is the responsability of the HttpClient to handle this behavior.
It's a good job that the [CachingHttpClient](https://github.com/symfony/symfony/blob/5.0/src/Symfony/Component/HttpClient/CachingHttpClient.php) already handles `stale-while-revalidate` and `stale-if-error`.

I'm trying to use create a demo app to show the feature, but I don't find the correct config for `http_client`.

File: src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php [hunk 17]
```diff
@@ -0,0 +1,86 @@
...
+    {
+        $this->manifestUrl = $manifestUrl;
+        $this->httpClient = $httpClient;
+    }
+
+    /**
+     * Makes an async HTTP request to load the manifest so
+     * it will be available as soon as it is required later on.
+     */
+    public function preload()
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Asset/VersionStrategy/RemoteJsonManifestVersionStrategy.php]: I'm not sure about this method - it feels complex to use in real life, and I'm not sure if will have the expected benefit: while this schedules the request, there are many steps to do to actually send it. I think we should remove it.

**Review by nicolas-grekas — COMMENTED** [review]
> IMO this is the responsibility of the HttpClient to handle this behavior.

I'm not sure about that: there are many benefits in using `CacheInterface` that won't be achieved by a `CachingHttpClient` (sharing of the cache, lock while fetching, probabilistic expiration, etc).

But this could be handled in a separate PR that adds a generic `CachedManifestVersionStrategy`, so that both ways are possible in the end.

Which means I'm good here, whith one last comment.

**Review by GromNaN — COMMENTED** [review]
I simplified the code to the simplest form. The `CachedManifestVersionStrategy` is a clever idea that would solve performance and high availability issues. I can work on it once this PR gets merged.

Commits has been squashed & rebased.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Anyone else @symfony/mergers?

**Review by javiereguiluz — APPROVED** [review]

**Comment by weaverryan** [comment]
I like this. Practical question: how could/should someone add caching? Decorate the service? Something else? There just needs to be a reasonable way and it's ok if it's simply covered in the docs.

**Comment by nicolas-grekas** [comment]
@weaverryan check https://github.com/symfony/symfony/pull/35762#pullrequestreview-364785825

**Comment by nicolas-grekas** [comment]
Thank you @GromNaN.

**Comment by nicolas-grekas** [comment]
@GromNaN would you like to give `CachedManifestVersionStrategy` a try?

**Comment by GromNaN** [comment]
I'll open a PR today.
