### PR TITLE
[Messenger] Move container resetting after receiver acknowledging

### LINKED ISSUE #43114: Too early resetting services in messenger
**Symfony version(s) affected**: 5.4.x

**Description**
I use a new feature added in #41163 with `UidProcessor` from Monolog. Recently I've realized the last INFO log from the messenger ("{class} was handled successfully (acknowledging to transport)") has a uid from the **following** message in a queue. It happens because that log message writes after the `WorkerMessageHandledEvent` that triggers resetting. It sounds silly, but I've spent hours trying to understand why a wrong message has a positive acknowledgment.

**How to reproduce**
Register service:
```yaml
services:
    Monolog\Processor\UidProcessor:
        tags: [ 'monolog.processor' ]
```

Configure messenger:
```yaml
framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                reset_on_message: true
        routing:
            App\Message: async
```

Consume some message:
```
bin/console messenger:consume async -vv
```

Example output:
```
19:50:03 INFO [messenger] Received message App\Message ["class" => "App\Message"] ["uid" => "4f9fa66"]
19:50:03 INFO [messenger] Message App\Message handled by App\Handler::__invoke ["class" => "App\Message","handler" => "App\Handler::__invoke"] ["uid" => "4f9fa66"]
19:50:03 INFO [messenger] App\Message was handled successfully (acknowledging to transport). ["class" => "App\Message"] ["uid" => "17280ae"]
19:50:04 INFO [messenger] Received message App\Message ["class" => "App\Message"] ["uid" => "17280ae"]
19:50:04 INFO [messenger] Message App\Message handled by App\Handler::__invoke ["class" => "App\Message","handler" => "App\Handler::__invoke"] ["uid" => "17280ae"]
19:50:04 INFO [messenger] App\Message was handled successfully (acknowledging to transport). ["class" => "App\Message"] ["uid" => "b3d9ee5"]
```

**Possible Solution**
I think the service resetting should be the last thing in a handling loop: after logging, after acknowledging. The actual event for that is `WorkerRunningEvent`. The event doesn't have a transport name, but it's trivial to fix. Nevertheless, I have doubts about all of this.

### PR DESCRIPTION
**Pull request by upyx**
| Q             | A
| ------------- | ---
| Branch?       | 5.4 
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #43114 
| License       | MIT
| Doc PR        | nope

It fixes the #43114 issue and similar potential bugs. The `ResetServicesListener` lean on events sequence: the `AbstractWorkerMessageEvent` to save the actual receiver name, then the `WorkerRunningEvent` to check that name and reset the container. It may look fragile, so let's discuss it in the issue.

### CODE REVIEW

**Comment by okwinza** [comment]
Waiting until the worker is completely done handling a message before actually resetting services sounds good to me. :+1: 

Things to keep in mind:
- Services should only be reset after the worker is done with a message.
- Services should not be reset more once between each message.

As for the implementation part, this could also benefit from #42335 to easily check the worker transport name.
So you could just do something like this:
```php
$event->getWorker()->getWorkerMetadata()->getTransportName() === $this->transportName;
```

**Comment by lyrixx** [comment]
I just merged #42335. Can you rebase to use the new feature? Thanks

And please, fix fabpot issue :)

**Comment by upyx** [comment]
> ```
> $event->getWorker()->getWorkerMetadata()->getTransportName() === $this->transportName;
> ```

@okwinza 
It won't work as expected because the `WorkerMetadata` has an array of transport names. The part of transports can be not resettable. We can either restrict using resettable and not resettable transports in the same worker or rely on the event's sequence. I'd prefer to use new metadata, and I think it will be good to restrict resetting services on a receiver when the different one doesn't expect that behavior.

So it'll take a while to implement.

**Comment by lyrixx** [comment]
What about moving the ack before the dispatch ?

Edit: this is a bad idea. But I think the best solution is to create a new event (same for nack)

**Comment by upyx** [comment]
@lyrixx:
> What about moving the ack before the dispatch ?
> 
> Edit: this is a bad idea. But I think the best solution is to create a new event (same for nack)

We have the event already. We have metadata, transport names, and other things.

I've been investigating the topic more. I've realized that resetting services is a worker's job rather than a transport's because service leak is a consumer problem and isn't dependent on transport. And there aren't any consumers on the "sync" transport.

In my opinion, the best alternative is resetting services after every message. The only drawback is decreasing performance, so we can provide an option to disable it. It also will break compatibility, so we should enable that option by default and add an inversed one. 

I consider removing the `reset_on_message` parameter from a configuration and adding two options to the `messenger:consume` command: `--reset-services-on-message` and `--no-reset-services-on-message`. It's also good to deprecate running the command without explicitly indicating which one to use and change defaults in 6.0.

**Comment by upyx** [comment]
I've made a working draft as an example. If it's OK, I'll continue.

File: src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php [hunk 1]
```diff
@@ -43,14 +45,22 @@ class ConsumeMessagesCommand extends Command
...
+    private $servicesResetter;
+
+    public function __construct(
+        RoutableMessageBus $routableBus,
+        ContainerInterface $receiverLocator,
+        EventDispatcherInterface $eventDispatcher,
+        LoggerInterface $logger = null,
+        array $receiverNames = [],
+        $servicesResetter = null
+    ) {
```
Comment (lyrixx) [inline src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php]: Please, use only one line, we don't do that in symfony

**Review by lyrixx — COMMENTED** [review]
I like it. But I realize we can simplify the work for end user.
We can move the command configuration to the bundle:
Like that, user don't have to update all consumer recipies (ansible,  helm, etc). Only the code needs to be updated.

```yaml
framework:
    messenger:
        reset_on_message: true # add a deprecation if not set
        transports: ....
```

WDYT?

I agree with you on the fact that is should be the default, and I don't see a use case where a transport should be reset but not another one. 

And BTW Fab wanted to reset the container all the time too: https://github.com/symfony/symfony/pull/41163#discussion_r663772639

**Comment by okwinza** [comment]
> ```yaml
> framework:
>     messenger:
>         reset_on_message: true # add a deprecation if not set
>         transports: ....
> ```
Can't we just set it to `false` by default for BC and then change it to `true` and make it mandatory in 6.0?
Also it might be useful to add a runtime `--no-reset` option to `messenger:consume` as well.
WDYT?

**Comment by lyrixx** [comment]
> Can't we just set it to `false` by default for BC and then change it to `true` and make it mandatory in 6.0?

it's not the best way to handle migration path.
5.4: deprecation if not set, telling it'll be true in 6.0, default to false for BC
6.0: default to true, no deprecation, optin

> Also it might be useful to add a runtime `--no-reset` option to `messenger:consume` as well.

do you have a use case for overriding the value? (less code == less bug)

**Comment by okwinza** [comment]
> 5.4: deprecation if not set, telling it'll be true in 6.0, default to false for BC
> 6.0: default to true, no deprecation, optin

:+1: Agreed.


> > Also it might be useful to add a runtime `--no-reset` option to `messenger:consume` as well.
> 
> do you have a use case for overriding the value? (less code == less bug)

Since container resetting affects conformance, it **might** make sense to be able to override it for additional performance gain in some particular consumers. 

But this is just an idea and it's totally out of scope of this PR and should be added later down the road, if at all.

**Comment by lyrixx** [comment]
Okay let's go 👍 do you wanna to finish the pr ?

Thanks for discussion 😊

**Comment by upyx** [comment]
@lyrixx
The only use case for disabling service resetting is to gain performance for specific consumers; therefore, the option should be in a consumer but not in configuration.

> less code == less bug

Absolutely! So we do not need a configuration option (in prospect). What we need are backward compatibility and migration strategy. Some users may use "service leak" as a side effect for their scenarios; however, it's a poor solution. So the decision we should make: how to migrate it.

I think you are right about a deployment. A new plan:
5.4:
 - add the `messenger.reset_on_message` config with default `false`
 - deprecate empty `messenger.reset_on_message` with hint about defaults
 - add `--no-reset` (or `--no-reset-services` or `--no-reset-services-on-message` ?) option to `messenger:consume` command.
 
6.0:
 - change default of `messenger.reset_on_message` to `true`
 - deprecate `messenger.reset_on_message` to remove it in 7.0

@lyrixx @okwinza do you agree?

File: src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php (hunk 1 above)
Comment (upyx) [reply src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php]: ok :)

**Comment by upyx** [comment]
I've realized that services **must not** be reset on idle. It's not optional because of counters and sequences that can be used. Possible memory leaks in transports should be fixed in transports.

**Comment by lyrixx** [comment]
> I've realized that services **must not** be reset on idle. It's not optional because of counters and sequences that can be used.

What are you refering to?

I think something is not clear here. you (@upyx and @okwinza) talks about performance penalty. Even if this **could** be true, this is not always the case. I'm not sure, but it looks like you think **all** symfony (and app) services will be **unset**. This is not the case. Service will be **reset**, it means the `ServicesResetter` service will take all services tagged `kernel.reset` and call `reset()` method on it. On the current application I'm working one (SF 5.3, APIP, Doctrine). There are 41 services impacted in dev.

For reference:
```
 ---------------------------------------------------------- ---------------------- ----------------------------------------------------------------------------------------
  Service ID                                                 method                 Class name                                                                             
 ---------------------------------------------------------- ---------------------- ----------------------------------------------------------------------------------------
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        reset                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        reset                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        reset                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        reset                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        reset                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        reset                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        reset                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        reset                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  Symfony\Bridge\Monolog\Processor\ConsoleCommandProcessor   reset                  Symfony\Bridge\Monolog\Processor\ConsoleCommandProcessor
  Symfony\Component\Cache\Psr16Cache                         reset                  Symfony\Component\Cache\Psr16Cache
  cache.app                                                  reset                  Symfony\Component\Cache\Adapter\FilesystemAdapter
  cache.system                                               reset                  Symfony\Component\Cache\Adapter\AdapterInterface
  cache.validator                                            reset                  Symfony\Component\Cache\Adapter\AdapterInterface
  cache.serializer                                           reset                  Symfony\Component\Cache\Adapter\AdapterInterface
  cache.annotations                                          reset                  Symfony\Component\Cache\Adapter\AdapterInterface
  cache.property_info                                        reset                  Symfony\Component\Cache\Adapter\AdapterInterface
  cache.messenger.restart_workers_signal                     reset                  Symfony\Component\Cache\Adapter\FilesystemAdapter
  agent_rules.cache                                          reset                  Symfony\Component\Cache\Adapter\RedisAdapter
  cache.array                                                reset                  Symfony\Component\Cache\Adapter\ArrayAdapter
  doctrine.result_cache_pool                                 reset                  Symfony\Component\Cache\Adapter\FilesystemAdapter
  doctrine.system_cache_pool                                 reset                  Symfony\Component\Cache\Adapter\AdapterInterface
  form.choice_list_factory.cached                            reset                  Symfony\Component\Form\ChoiceList\Factory\CachingFactoryDecorator
  messenger.transport.in_memory.factory                      reset                  Symfony\Component\Messenger\Transport\InMemoryTransportFactory
  cache.validator_expression_language                        reset                  Symfony\Component\Cache\Adapter\AdapterInterface
  debug.stopwatch                                            reset                  Symfony\Component\Stopwatch\Stopwatch
  security.token_storage                                     disableUsageTracking   Symfony\Component\Security\Core\Authentication\Token\Storage\UsageTrackingTokenStorage
   (same service as previous, another tag)                   setToken
  cache.security_expression_language                         reset                  Symfony\Component\Cache\Adapter\AdapterInterface
  monolog.handler.main                                       reset                  Monolog\Handler\FingersCrossedHandler
  monolog.handler.console                                    reset                  Symfony\Bridge\Monolog\Handler\ConsoleHandler
  webpack_encore.tag_renderer                                reset                  Symfony\WebpackEncoreBundle\Asset\TagRenderer
  cache.webpack_encore                                       reset                  Symfony\Component\Cache\Adapter\AdapterInterface
  webpack_encore.entrypoint_lookup[_default]                 reset                  Symfony\WebpackEncoreBundle\Asset\EntrypointLookup
  doctrine                                                   reset                  Doctrine\Bundle\DoctrineBundle\Registry
  form.type.entity                                           reset                  Symfony\Bridge\Doctrine\Form\Type\EntityType
  cache.easyadmin                                            reset                  Symfony\Component\Cache\Adapter\AdapterInterface
  api_platform.cache.route_name_resolver                     reset                  Symfony\Component\Cache\Adapter\AdapterInterface
  api_platform.cache.identifiers_extractor                   reset                  Symfony\Component\Cache\Adapter\AdapterInterface
  api_platform.cache.subresource_operation_factory           reset                  Symfony\Component\Cache\Adapter\AdapterInterface
  api_platform.cache.metadata.resource                       reset                  Symfony\Component\Cache\Adapter\AdapterInterface
  api_platform.cache.metadata.property                       reset                  Symfony\Component\Cache\Adapter\AdapterInterface
 ---------------------------------------------------------- ---------------------- ----------------------------------------------------------------------------------------

**Comment by upyx** [comment]
@lyrixx
I meant that what services do on reset. It can be a custom service that increases some counter on every message. For example, Monolog's `UidProcessor` generates random UID on every reset. I'm not too fond of randoms (because of collisions), so I'd like to store a sequence in APCu or Redis. It isn't a hot queue (5 messages per day), and I'd like to make numbers as short as possible, and the sequence is short. So forwarding sequence on idle would quickly lead to sequence overflow. It's a simplified example just for clarity. Performance isn't an issue when the queue is idle. We mustn't reset services on idle not because of the cost but because of side effects.

I think it would be good to add documentation that describes what the "services resetting" is and what it is for, how to use the `kernel.reset` tag and the `ResetInterface`, where to enable `autoconfigure`, and where don't.

**Comment by lyrixx** [comment]
> so I'd like to store a sequence in APCu or Redis

if the sequence is in APCu or Redis, it's safe. 

IMHO, store a state between 2 messages in PHP memory (so in a service) is a bad idea. It does not work when a worker restart or when there are many worker. 

So this is not a valid use case since it's harmful.

The plan you propose in [this comment](https://github.com/symfony/symfony/pull/43133#issuecomment-927140162) is really good. Let's stick to it.

**Review by lyrixx — APPROVED** [review]
Very good work. Thanks 👍🏼

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @upyx.

**Comment by upyx** [comment]
@lyrixx  @fabpot you are welcome :handshake: :handshake:
 
Should I make another PR to the 6.0 branch in which deprecations are removed?

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 2]
```diff
@@ -2089,6 +2076,17 @@ private function registerMessengerConfiguration(array $config, ContainerBuilder
...
         }
+
+        if (false === $config['reset_on_message']) {
+            throw new LogicException('The "framework.messenger.reset_on_message" configuration option can be set to "true" only. To prevent services resetting after each message you can set the "--no-reset" option in "messenger:consume" command.');
+        }
+
+        if (null === $config['reset_on_message']) {
+            trigger_deprecation('symfony/framework-bundle', '5.4', 'Not setting the "framework.messenger.reset_on_message" configuration option is deprecated, it will default to "true" in version 6.0.');
+
+            $container->getDefinition('console.command.messenger_consume_messages')->replaceArgument(5, null);
```
Comment (kbond) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:2087]: I will debug further and create a proper issue/PR later but this service may not exist:

```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "console.command.messenger_consume_messages".
```

Comment (upyx) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:2087]: Yep, I've found where it is. It's possible when `messenger` is installed without `console`. I will fix it, but I don't know how to test that fix because of `class_exists(Application::class)` expression.

**Comment by lyrixx** [comment]
> Should I make another PR to the 6.0 branch in which deprecations are removed?

yes, and a PR on the doc too :)

**Comment by upyx** [comment]
> > Should I make another PR to the 6.0 branch in which deprecations are removed?
> 
> yes, and a PR on the doc too :)

#43202 has some fixes
#43203 is a draft for 6.0
