### PR TITLE
[Serializer] Take unnamed variadic parameters into account when denormalizing

### LINKED ISSUE #53354: [Serializer] Error when trying to deserialize an object with a constructor using a variadic parameter
### Symfony version(s) affected

6.4.2 (Other versions most likely as well)

### Description

For some reason the serializer doesn't seem to like variadic arguments in the constructor

### How to reproduce

When deserializing a json object like this
```json
{
    "requiredParameter": "required",
    "optionalParameter": "optional",
    "variadicParameter": [
        {"param": 1},
        {"param": 2}
    ]
}
```

into a PHP class like this
```php
class ChildExample {
    public function __construct(
        private int $param,
    ) {}
}

class Example {
    private array $variadicProperty;

    public function __construct(
        private string $requiredParameter,
        private string $optionalParameter = '',
        SomeClass ...$variadicParameter,
    ) {
        $this->variadicProperty = $variadicParameter;
    }
}
```
I get the PHP error `Error : Cannot use positional argument after named argument` on line 429 of `AbstractNormalizer.php`.

### Possible Solution

When I wrap the `$params` variable in an `array_values()` call the problem goes away. I'll try to create a pull request with my fix later.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by thijsBreker**
We shouldn't break when a constructor has variadic parameters without named keys in the array.

| Q             | A
| ------------- | ---
| Branch?       |  5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #53354
| License       | MIT

### CODE REVIEW

**Comment by HypeMC** [comment]
This was caused by #53115, sorry about that. IMO, the best solution would be to avoid using named arguments when the function is variadic:

```diff
index 1a7c314b84..27224f5b3d 100644
--- a/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php
+++ b/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php
@@ -372,7 +372,7 @@ abstract class AbstractNormalizer implements NormalizerInterface, DenormalizerIn
                             $variadicParameters[$parameterKey] = $this->denormalizeParameter($reflectionClass, $constructorParameter, $paramName, $parameterData, $context, $format);
                         }
 
-                        $params = array_merge($params, $variadicParameters);
+                        $params = array_merge(array_values($params), $variadicParameters);
                         $unsetKeys[] = $key;
                     }
                 } elseif ($allowed && !$ignored && (isset($data[$key]) || \array_key_exists($key, $data))) {
```

**Comment by thijsBreker** [comment]
No worries! This gave me the chance to contribute for the first time :)

**Comment by thijsBreker** [comment]
I don't understand where the code standard errors are coming from. The patch provided changes things that have been there since 2018?

**Comment by HypeMC** [comment]
> I don't understand where the code standard errors are coming from. The patch provided changes things that have been there since 2018?

Don't worry about it, most are false positives. Just revert the coding standard changes on lines you didn't modify.

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractNormalizerTest.php [hunk 1]
```diff
@@ -247,6 +248,19 @@ public static function getNormalizer()
...
+    {
+        $data = '{"foo":"woo","baz":[{"foo":null,"bar":null,"baz":null,"qux":null},{"foo":null,"bar":null,"baz":null,"qux":null}]}';
+        $expected = new DummyWithWithVariadicParameterConstructor('woo', 1, new Dummy(), new Dummy());
+
+        $normalizer = new ObjectNormalizer();
+        $serializer = new Serializer([$normalizer], [new JsonEncoder()]);
+        $normalizer->setSerializer($serializer);
+
+        $actual = $normalizer->denormalize(json_decode($data, true), DummyWithWithVariadicParameterConstructor::class);
+        $this->assertEquals($expected, $actual);
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Tests/Normalizer/AbstractNormalizerTest.php]: Your test can be simplified a bit by:
- not using JSON string but a normalized array
- not instantiating a `JsonEncoder` for nothing

Eg:
```php
$data = [
    'foo' => 'woo',
    'baz' => [
        ['foo' => null, 'bar' => null, 'baz' => null, 'qux' => null],
        ['foo' => null, 'bar' => null, 'baz' => null, 'qux' => null],
    ],
];

$normalizer = new ObjectNormalizer();
$normalizer->setSerializer(new Serializer([$normalizer]));

$expected = new DummyWithWithVariadicParameterConstructor('woo', 1, new Dummy(), new Dummy());
$actual = $normalizer->denormalize($data, DummyWithWithVariadicParameterConstructor::class);

$this->assertEquals($expected, $actual);
```

File: src/Symfony/Component/Serializer/Tests/Fixtures/DummyWithWithVariadicParameterConstructor.php [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+
+    public function __construct(string $foo, int $bar = 1, Dummy ...$baz)
+    {
+        $this->foo = $foo;
+        $this->bar = $bar;
+        $this->baz = $baz;
+    }
+
+    /** @return string */
+    public function getFoo()
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Tests/Fixtures/DummyWithWithVariadicParameterConstructor.php]:
```suggestion
    public function getFoo(): string
```

File: src/Symfony/Component/Serializer/Tests/Fixtures/DummyWithWithVariadicParameterConstructor.php [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+    {
+        return $this->foo;
+    }
+
+    /** @return int */
+    public function getBar()
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Tests/Fixtures/DummyWithWithVariadicParameterConstructor.php]:
```suggestion
    public function getBar(): int
```

File: src/Symfony/Component/Serializer/Tests/Fixtures/DummyWithWithVariadicParameterConstructor.php [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+    {
+        return $this->bar;
+    }
+
+    /** @return Dummy[] */
+    public function getBaz()
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Tests/Fixtures/DummyWithWithVariadicParameterConstructor.php]:
```suggestion
    /** @return Dummy[] */
    public function getBaz(): array
```

**Comment by HypeMC** [comment]
@thijsBreker It would be good to remove WIP from the title.

File: src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php [hunk 5]
```diff
@@ -150,9 +150,6 @@ public function __construct(ClassMetadataFactoryInterface $classMetadataFactory
         }
     }
 
-    /**
-     * {@inheritdoc}
-     */
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php]: These changes must not belong to that patch. You should ignore theses fabbot errors for that PR as it doesn't belong 
 to your work :slightly_smiling_face:

Comment (thijsBreker) [reply src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php]: Alright. I'll drop the code changes commit then.

**Review by mtarld — APPROVED** [review]

**Review by HypeMC — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @thijsBreker.
