### PR TITLE
[Messenger] Add TLS option to Redis transport's DSN

### LINKED ISSUE #33025: [Messenger] TLS/SSL support for Redis Transport
**Description**  
New redis transport for messages works great, unfortunately it appears it has no TLS/SSL support. 

**Example**  
If we would pass DNS string `rediss://xxxx/messages` we would get an error: `"No transport supports the given Messenger DSN "rediss://xxxx/messages"`. 

I propose implementing TLS/SSL support similar to [predis ](https://github.com/nrk/predis), where `rediss` would be an alias for `tls` protocol.

### PR DESCRIPTION
**Pull request by Nyholm**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #33025
| License       | MIT
| Doc PR        | 

As suggested by @matas-valuzis, this will enable TLS support for Redis transport. 

Configure it with the following DSN

```
redis://127.0.0.1?tls=1
```

The implementation just prefix the host with `tls://` as described here: https://github.com/phpredis/phpredis#connect-open

It is already possible to use TLS with the Redis transport, but there are not support in the DSN until now.

### CODE REVIEW

**Review by dunglas — APPROVED** [review]

File: src/Symfony/Component/Messenger/Bridge/Redis/Tests/Transport/ConnectionTest.php [hunk 1]
```diff
@@ -73,6 +73,18 @@ public function testFromDsnWithOptions()
         );
     }
 
+    public function testFromDsnWithTls()
+    {
+        $redis = $this->createMock(\Redis::class);
+        $redis->expects($this->exactly(2))
```
Comment (stof) [inline src/Symfony/Component/Messenger/Bridge/Redis/Tests/Transport/ConnectionTest.php]: I'd rather create 2 separate tests. It would be more readable than mixing the 2 cases on the same mock.

Comment (Nyholm) [reply src/Symfony/Component/Messenger/Bridge/Redis/Tests/Transport/ConnectionTest.php]: That makes sense. 

Thank you. I've updated the PR

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Nyholm.

**Comment by Nyholm** [comment]
Thank you for merging.
