### PR TITLE
[Notifier] Inject Mailer instead of service locator for FakeSms and FakeChat

### LINKED ISSUE #40731: Broken FakeSmsTransportFactory
**Symfony version(s) affected**: 5.x

**Description**
Broken constructor
Argument 1 passed to Symfony\Component\Notifier\Bridge\FakeSms\FakeSmsTransportFactory::__construct() must implement interface Symfony\Contracts\Service\ServiceProviderInterface, instance of Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher given, called in /var/www/project/var/cache/dev/Container5Ymhxuy/App_KernelDevDebugContainer.php on line 5578

**How to reproduce**
git clone https://github.com/symfony/symfony
Enable texter - sms notifier. Try to use and get this error.

**Possible Solution**
Not found.

**Additional context**

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fixes #40731
| License       | MIT
| Doc PR        | https://github.com/symfony/symfony-docs/pull/15206
| Recipe PR        | https://github.com/symfony/recipes/pull/930

Until now the locator was not injected and therefore not working.

We decided to make the transport name configurable instead of the service_id.

[How is it working?](https://github.com/symfony/symfony/pull/40739#issuecomment-816609850)

### Todos
* [x] add tests
* [x] test in a real project

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -2417,6 +2419,16 @@ private function registerNotifierConfiguration(array $config, ContainerBuilder $
             $container->removeDefinition($classToServices[MercureTransportFactory::class]);
         }
 
+        if (ContainerBuilder::willBeAvailable('symfony/fake-chat-notifier', FakeChatTransportFactory::class, ['symfony/mailer'])) {
```
Comment (OskarStark) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:2422]: Not sure this line is correct 🤔

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 2]
```diff
@@ -2417,6 +2419,16 @@ private function registerNotifierConfiguration(array $config, ContainerBuilder $
...
+            $container->getDefinition($classToServices[FakeChatTransportFactory::class])
+                ->replaceArgument('$mailerLocator', new ServiceLocatorArgument(new TaggedIteratorArgument('mailer', null, null, true)));
```
Comment (OskarStark) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: I found out, that we did not tag our mailer's 🤔 

CleanShot 2021-04-08 at 13 32 55

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 1 above)
Comment (OskarStark) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php:2422]: Friendly ping @stof

File: src/Symfony/Component/Notifier/Bridge/FakeChat/FakeChatEmailTransport.php [hunk 3]
```diff
@@ -27,6 +27,8 @@
  */
 final class FakeChatEmailTransport extends AbstractTransport
 {
+    protected const HOST = 'default';
```
Comment (chalasr) [inline src/Symfony/Component/Notifier/Bridge/FakeChat/FakeChatEmailTransport.php:30]:
```suggestion
    protected const DEFAULT_HOST = 'default';
```

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 4]
```diff
@@ -2417,6 +2417,16 @@ private function registerNotifierConfiguration(array $config, ContainerBuilder $
             $container->removeDefinition($classToServices[MercureTransportFactory::class]);
         }
 
+        if (ContainerBuilder::willBeAvailable('symfony/fake-chat-notifier', FakeChatTransportFactory::class, array_merge($parentPackages, ['symfony/mailer']))) {
```
Comment (OskarStark) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Not sure this line is correct 🤔 

I only want to run this code if `fake-chat-notifier` with `FakeChatTransportFactory::class` and `symfony/mailer` is installed. Am I using `willBeAvailable` method correct?

Friendly ping @stof

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 5]
```diff
@@ -2421,12 +2421,12 @@ private function registerNotifierConfiguration(array $config, ContainerBuilder $
 
         if (ContainerBuilder::willBeAvailable('symfony/fake-chat-notifier', FakeChatTransportFactory::class, ['symfony/mailer'])) {
```
Comment (chalasr) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: The factory definition may have been removed earlier if any of `$parentPackages` is missing
```suggestion
        if (ContainerBuilder::willBeAvailable('symfony/fake-chat-notifier', FakeChatTransportFactory::class, array_merge($parentPackages, ['symfony/mailer']))) {
```

File: src/Symfony/Component/Notifier/Bridge/FakeChat/FakeChatEmailTransport.php (hunk 3 above)
Comment (OskarStark) [reply src/Symfony/Component/Notifier/Bridge/FakeChat/FakeChatEmailTransport.php:30]: 👎 this is defined in `AbstractTransport` and should be overridden

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 5 above)
Comment (OskarStark) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Already done before your comment :-)

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 4 above)
Comment (stof) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: The part I'm not sure is the `array_merge`. I don't remember whether passing multiple parent packages requires all of them or at least one of them. /cc @nicolas-grekas

Comment (OskarStark) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Regarding this code:
https://github.com/symfony/symfony/blob/ddb48bb39123b18b0f73f1e19fb0747aed8590b0/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L1469-L1495

I would say it just checks if at least one of them is available 🤔

Comment (stof) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: meaning that if you want to ensure that several parent packages are all installed, you should do that as `ContainerBuilder::willBeAvailable(..., $parent1) && ContainerBuilder::willBeAvailable(..., $parent2)` :smile:

Comment (OskarStark) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Yes, but in this case I am wondering if the previous used one by mercure is working as expected and needs to do the call twice too 🤔 

cc @mtarld

**Comment by OskarStark** [comment]
@Nyholm any idea what's wrong here?
CleanShot 2021-04-09 at 09 47 24

**Comment by OskarStark** [comment]
I tested this in my project with the following command:
```php
<?php

declare(strict_types=1);

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Notifier\ChatterInterface;
use Symfony\Component\Notifier\Message\ChatMessage;
use Symfony\Component\Notifier\Message\SmsMessage;
use Symfony\Component\Notifier\Tests\Fixtures\TestOptions;
use Symfony\Component\Notifier\TexterInterface;

final class TestFakeBridgesCommand extends Command
{
    protected static $defaultName = 'test:fake-bridges';

    public function __construct(
        private ChatterInterface $chatter,
        private TexterInterface $texter,
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->setDescription('Test FakeSms and FakeChat bridge');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        // SMS
        $message = new SmsMessage('1234567', 'Hi Symfony');
        $this->texter->send($message);

        // ChatMessage without recipient
        $message = new ChatMessage('Hi Symfony!');
        $this->chatter->send($message);

        // Chat Message with recipient
        $message = new ChatMessage('Hi Symfony!', new TestOptions(['recipient_id' => 'Oskar']));
        $this->chatter->send($message);

        return Command::SUCCESS;
    }
}
```

### Results 👍 
CleanShot 2021-04-09 at 13 11 27
CleanShot 2021-04-09 at 13 11 54
CleanShot 2021-04-09 at 13 12 23

File: src/Symfony/Component/Notifier/Tests/Fixtures/TestOptions.php [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+/*
+ * This file is part of the Symfony package.
+ *
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\Notifier\Tests\Fixtures;
```
Comment (OskarStark) [inline src/Symfony/Component/Notifier/Tests/Fixtures/TestOptions.php:12]: Namespace correct?

File: src/Symfony/Component/Notifier/Tests/Mailer/DummyMailer.php [hunk 7]
```diff
@@ -0,0 +1,34 @@
...
+namespace Symfony\Component\Notifier\Tests\Mailer;
+
+use Symfony\Component\Mailer\Envelope;
+use Symfony\Component\Mailer\MailerInterface;
+use Symfony\Component\Mime\RawMessage;
+
+/**
+ * @author Oskar Stark <oskarstark@googlemail.com>
+ */
+class DummyMailer implements MailerInterface
```
Comment (OskarStark) [inline src/Symfony/Component/Notifier/Tests/Mailer/DummyMailer.php:21]: Or is there sth similar available? 🤔 

Do you have a proposal for a better name?

**Comment by Nyholm** [comment]
Yes, you are missing `.gitignore`


Screenshot 2021-04-09 at 13 24 32

**Comment by OskarStark** [comment]
Oh I overlooked this, thanks `.gitignore` added

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 4 above)
Comment (mtarld) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Yes indeed, the call is done twice for mercure

Comment (OskarStark) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: Yes but you are using `$parentPackages`, but I think you need to achieve, that both, notifier and framework-bundle need to be available, right? But this would not work.

To be more clear, I think we need to change your code to:
```diff
diff --git a/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php b/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
index 4d4749a2f1..f36702d254 100644
--- a/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
+++ b/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
@@ -2410,10 +2410,16 @@ class FrameworkExtension extends Extension
             }
         }

-        if (ContainerBuilder::willBeAvailable('symfony/mercure-notifier', MercureTransportFactory::class, $parentPackages) && ContainerBuilder::willBeAvailable('symfony/mercure-bundle', MercureBundle::class, $parentPackages)) {
+        if (ContainerBuilder::willBeAvailable('symfony/mercure-notifier', MercureTransportFactory::class, ['symfony/framework-bundle'])
+            && ContainerBuilder::willBeAvailable('symfony/mercure-notifier', MercureTransportFactory::class, ['symfony/notifier'])
+            && ContainerBuilder::willBeAvailable('symfony/mercure-bundle', MercureBundle::class, ['symfony/framework-bundle'])
+            && ContainerBuilder::willBeAvailable('symfony/mercure-bundle', MercureBundle::class, ['symfony/notifier'])
+        ) {
             $container->getDefinition($classToServices[MercureTransportFactory::class])
                 ->replaceArgument('$registry', new Reference(HubRegistry::class));
-        } elseif (ContainerBuilder::willBeAvailable('symfony/mercure-notifier', MercureTransportFactory::class, $parentPackages)) {
+        } elseif (ContainerBuilder::willBeAvailable('symfony/mercure-notifier', MercureTransportFactory::class, ['symfony/framework-bundle'])
+            && ContainerBuilder::willBeAvailable('symfony/mercure-notifier', MercureTransportFactory::class, ['symfony/notifier'])
+        ) {
             $container->removeDefinition($classToServices[MercureTransportFactory::class]);
:
```

if **yes** maybe it makes sense to either extend the `willBeAvailable` method to a 4th parameter `bool $all = false` or create a `allWillBeAvailable` and deprecated `$parentPackages` to be an array in `willBeAvailable` method.

cc @nicolas-grekas 

PS: I am unsure because I use this method the first time 😸

**Review by stof — APPROVED** [review]

**Review by chalasr — APPROVED** [review]
Thanks
