### PR TITLE
[Form] check parent types for label_format and translation_domain

### LINKED ISSUE #39874: {{ label }} translation in validation messages
**Symfony version(s) affected**: 5.2.x
This feature was added Symfony 5.2 https://github.com/symfony/symfony/pull/35338

**Description**  
Having label_format and translation_domain added in configureOptions doesn't have effect and the label in the message didn't get translated.

**How to reproduce**  
```yaml
# project.hu.yaml
form.title: cím
```

```yaml
# validators.hu.yaml
"This value should not be blank.": "A {{ label }} megadása kötelező!"
```

```php
// this way it's NOT working
class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('title', TextType::class ['validators' => new NotBlank()]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'label_format' => 'form.%name%',
            'translation_domain' => 'project',
        ]);
    }
}

// this way it IS working
class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('title', TextType::class, [
            'label_format' => 'form.%name%',
            'translation_domain' => 'project',
            'validators' => new NotBlank()
        ]);
    }
}
```

Expected: "A cím megadása kötelező!"
Got: "A Title megadása kötelező!" + missing translation of 'title' fom 'messages' domain

**Possible Solution**  
Check the form options not just the field options when translating the label for validation messages

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39874
| License       | MIT
| Doc PR        |

### CODE REVIEW

File: src/Symfony/Component/Form/Extension/Validator/ViolationMapper/ViolationMapper.php [hunk 1]
```diff
@@ -180,10 +184,16 @@ public function mapViolation(ConstraintViolation $violation, FormInterface $form
                     }
 
                     if (null !== $this->translator) {
+                        $form = $scope;
+
+                        do {
+                            $translationDomain = $form->getConfig()->getOption('translation_domain');
+                        } while (null === $translationDomain && null !== $form = $form->getParent());
```
Comment (rheh) [inline src/Symfony/Component/Form/Extension/Validator/ViolationMapper/ViolationMapper.php:191]: nit-pick:  The loop is a duplicate of the above one.  Introduce a private function?
```
private function getOption($form, $optionLabel) {
  do {
    $option = $form->getConfig()->getOption($optionLabel);
  } while (null === $option && null !== $form = $form->getParent());

  return $option;
}

```

**Review by nicolas-grekas — APPROVED** [review]

**Review by yceruto — APPROVED** [review]
