### PR TITLE
[JsonStreamer] Fix decoding iterable lists

### LINKED ISSUE #61559: [JsonStreamer] High Memory Usage
### Symfony version(s) affected

7.x

### Description

I'd like to use the JsonStreamer component to work with an API that returns a large dataset in json (~200k items) where the array of items is a nested property. Attempting to do so results is very high memory usage. After some digging, it also appears to happen even if it's a flat array.

I've created a minimal repo to reproduce the issue for both a 1D array, as well as a nested array: https://github.com/natewiebe13/symfony-json-streamer-memory

In my tests, I'm getting about 200MB of memory usage if I load the entire JSON structure into memory and iterating. If I use `halaxa/json-machine` it uses about 25MB of memory, and using the JsonStreamer component, it uses 2.1GB

At this point, I'm not sure if my usage is incorrect, or if there's something that can be improved in the component/documentation.

### How to reproduce

Reproducer: https://github.com/natewiebe13/symfony-json-streamer-memory

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #61559 
| License       | MIT

Because a `list<T>` is a subtype of `array<T>`, an `iterable<T>` cannot be a list.

This means that, as said [here](https://github.com/symfony/symfony/pull/59308#discussion_r1903884508):
> There is no way to be sure that keys of an iterable are successive (even if they are integers).
> And if keys are not successive, the resulting JSON structure is an object and not an array.
> According, to the [JSON specification](https://datatracker.ietf.org/doc/html/rfc8259#section-4), object' keys must be strings, and not integers.

This imply that it is right now impossible to "yield" items from `[{"itemId": 1, "modificationDate": "2025-10-10"}]` - it can only be yielded from `{"0": {"itemId": 1, "modificationDate": "2025-10-10"}}`.

I think that in the real world, a lot of people want to be able to yield items from `[...]`, even though it does not stick with the JSON specification.

This PR is doing the trade-off of considering `iterable<int, Anything>` as an "iterable list" (like `list<Anything>` but not cast to array).

### CODE REVIEW

File: src/Symfony/Component/JsonStreamer/Read/PhpAstBuilder.php [hunk 1]
```diff
@@ -382,7 +382,7 @@ private function buildCollectionNodeStatements(CollectionNode $node, bool $decod
         $prepareDataStmts = $decodeFromStream ? [
             new Expression(new Assign($this->builder->var('data'), $this->builder->staticCall(
                 new FullyQualified(Splitter::class),
-                $node->getType()->isList() ? 'splitList' : 'splitDict',
+                !$node->getType()->getCollectionKeyType()->isIdentifiedBy(TypeIdentifier::STRING) ? 'splitList' : 'splitDict',
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonStreamer/Read/PhpAstBuilder.php]: why not this? what about `iterable<Foo, Bar>` (eg from SplObjectStorage)?

```suggestion
                $node->getType()->getCollectionKeyType()->isIdentifiedBy(TypeIdentifier::INT) ? 'splitList' : 'splitDict',
```

Comment (mtarld) [reply src/Symfony/Component/JsonStreamer/Read/PhpAstBuilder.php]: By doing this, `iterable<int|string, Foo>` will be encoded with `splitList`, which is not the intended behavior.
But I didn't think about `SplObjectStorage`, thanks! Updated consequently.

**Comment by nicolas-grekas** [comment]
Thank you @mtarld.
