### PR TITLE
[Messenger] Add option to prevent Redis from deleting messages on rejection

### LINKED ISSUE #36619: [Messenger] Redis Transport removes message from stream on rejection
**Symfony version(s) affected**: 5.0.7

**Description**  
Redis Messenger transport deletes messages when rejecting, causing other consumers / applications to be unable to reach that message.

This is specifically because of the line:
https://github.com/symfony/symfony/blob/3945a5c80e149168f405ea948def2542162a7d24/src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php#L237
which causes messages to be removed from the stream, instead of being acknowledged only by a particular consumer group.

This affects primarily cases where Messenger component is used to read/write with other, third party applications.

**How to reproduce**  
1. Create two transports with different consumer groups.
2. Dispatch a message that cannot be handled properly, for example due to failing deserialization.
3. Start consuming from both transports. Only one of consumers will pick up this message.

**Possible Solution**  
Removing the delete command should suffice, but I'm not sure if it doesn't affect some other use cases.

**Additional context**

---

### PR DESCRIPTION
**Pull request by Steveb-p**
~Unless `delete_after_ack` configuration is set to `true`.~

Introduces `delete_after_reject` configuration property.

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | ~no~ yes (introduces config property)
| Deprecations? | no
| Tickets       | Fix #36619
| License       | MIT

> Redis Messenger transport deletes messages when rejecting, causing other consumers / applications to be unable to reach that message.

> This affects primarily cases where Messenger component is used to read/write with other, third party applications.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Then there is going to be zero different between calling reject() and calling ack(). This looks suspicious to me.

**Comment by soyuka** [comment]
Maybe that introducing a new `delete_after_reject` option would make more sense. As a reminder, this option is here to cover memory usage (https://github.com/symfony/symfony/commit/7c416a7173e73156588e13cc0d22da989f54ea23) although #36619 is an issue where rejected (not acknowledged) messages would not be available to other consumers.

**Comment by Steveb-p** [comment]
> Then there is going to be zero different between calling reject() and calling ack(). This looks suspicious to me.

Whoops, missed the comment.

Pretty much yes, rejection and acknowledgement becomes undistinguishable. From my point of view, acknowledgement means "Yup, I've seen this message and I've handled it". Whether it was rejected or handled ok is not possible to pass to Redis as there is no `XREJ`ect command anyway.

This is similar to how Kafka handles messages, which is what Redis streams are based on. It is simply a structured log that you go through, acknowledging messages as they come (meaning, "I've read it").

https://redis.io/topics/streams-intro
> Consumer groups were initially introduced by the popular messaging system called Kafka (TM). Redis reimplements a similar idea in completely different terms, but the goal is the same: to allow a group of clients to cooperate consuming a different portion of the same stream of messages.

As you can see in the original, `XACK` was sent to Redis just before `XDEL` anyway. Deleting the message causes other consumer groups to be unable to handle that message, despite potentially being able to.
In my case, other consumer group is simply another application. Errors during deserialization caused Worker to reject the message and delete, even though another app was perfectly able to work with it.

> As a reminder, this option is here to cover memory usage

(`delete_after_ack`) I would like to some sort of warning/note to documentation of this feature. I can see where it comes from, but it's "only" reasonable to delete messages if only one consumer group is assumed (that is, Messenger component is treated as internal application queue, not as a method of different application parts / applications to speak to one another).
In cases where another consumer group shows up, it breaks consumer group functionality in Redis.

**Comment by Steveb-p** [comment]
@sroze could you give your opinion on this if you have some spare time? I'd like to adjust the PR to match.

Does this need some tests to be added, or will it be good as-is, even with new configuration property `delete_after_reject`?

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php [hunk 1]
```diff
@@ -84,6 +86,7 @@ public function __construct(array $configuration, array $connectionCredentials =
         $this->autoSetup = $configuration['auto_setup'] ?? self::DEFAULT_OPTIONS['auto_setup'];
         $this->maxEntries = $configuration['stream_max_entries'] ?? self::DEFAULT_OPTIONS['stream_max_entries'];
         $this->deleteAfterAck = $configuration['delete_after_ack'] ?? self::DEFAULT_OPTIONS['delete_after_ack'];
+        $this->deleteAfterReject = $configuration['delete_after_reject'] ?? $configuration['delete_after_ack'] ?? self::DEFAULT_OPTIONS['delete_after_reject'];
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php:89]: I'm not sure binding delete_after_reject to delete_after_ack is expected.
It would be less surprising to both options independent to me:
`$configuration['delete_after_reject'] ?? self::DEFAULT_OPTIONS['delete_after_reject'];`

Comment (Steveb-p) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php:89]: My reasoning for this is:  
If someone is already using `delete_after_ack` for reducing memory usage of Redis, then they would expect rejection to work similarly.

But maybe I'm just overthinking this :smile:

Comment (nicolas-grekas) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php:89]: I think we should let ppl be able to decide, there will be an option anyway. Their choice.

Comment (chalasr) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php:89]: I agree with @nicolas-grekas here

**Review by chalasr — CHANGES_REQUESTED** [review]
See https://github.com/symfony/symfony/pull/36727#pullrequestreview-428822797

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php (hunk 1 above)
Comment (Steveb-p) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: @chalasr @nicolas-grekas changes applied as suggested.

**Review by soyuka — APPROVED** [review]

**Comment by chalasr** [comment]
Looks good to me, but I'm not sure this qualifies as a bugfix given it introduces a new option (and thus requires code changes).

**Comment by fabpot** [comment]
I agree with @chalasr, this should target 5.2 (aka master).

**Comment by Steveb-p** [comment]
@fabpot @chalasr I'll rebase and adjust the PR accordingly.

Hopefully I won't pull half of the community into it this time :see_no_evil:

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php [hunk 2]
```diff
@@ -33,6 +33,7 @@ class Connection
         'consumer' => 'consumer',
         'auto_setup' => true,
         'delete_after_ack' => false,
+        'delete_after_reject' => false,
```
Comment (chalasr) [inline src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php:36]: this changes the current behavior, right? 
Should it be `true` to keep the same behavior as before unless explicitly set?

Comment (Steveb-p) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php:36]: Originally it was intended to prevent message loss due, since the default behavior of `ack` is to **not** delete the message.  
It depends how you look at it. From my perspective it's a "bug" because it was an unintended behavior and for this reason should not remove messages by default.

Comment (chalasr) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php:36]: Given we are addressing a design issue by introducing a new option, we consider it a new feature hence it targets 5.2. If the feature changes the default behavior, then we consider it a BC break, which is not good :).
Let's keep `true` as default value, if someone comes later on asking for a different default value then we can still consider changing it with some deprecation notices and a smooth upgrade path.

Comment (chalasr) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php:36]: btw, we will need a CHANGELOG entry for this feature

Comment (Steveb-p) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: @chalasr Added a changelog entry and set default value for `delete_after_reject` to `true` as is current behavior.

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Steveb-p.
