### PR TITLE
[Translation] Fix constant domain resolution in PhpAstExtractor

### LINKED ISSUE #53356: [Translation] Translation Debug command doesn't work correctly with domain as constant
### Symfony version(s) affected

all

### Description

Currently both
```php
use App\Const\Domain;
$this->translator->trans('foo', Domain::CUSTOM);
```
in php and
```twig
{{ 'foo'|trans({}, constant('App\\Constant\\Domain::CUSTOM')) }};
```
in twig is misunderstood by translation extractor.

The first one thinks the domain is `'messages'`, the second one `'_undefined'`.

It would be nice to correctly support the domain.
If it's really not possible, it seems better to me to have `'_undefined'` in both case.

### How to reproduce

Running
```bash
bin/console debug:translation
```
with the previous code.

### Possible Solution

For the AbstractVisitor, I tried doing something with
```php
if ($node instanceof Node\Expr\ClassConstFetch) {
            try {
                $reflection = new \ReflectionClass($node->class->toString());
                $constant = $reflection->getReflectionConstant($node->name->toString());
                if (false !== $constant && \is_string($constant->getValue())) {
                    return $constant->getValue();
                }
            } catch (\ReflectionException) {}
        }
```
but this works only with full FQCN, and not when it's imported/aliased at the start of the file...

For twig, I tried https://github.com/symfony/symfony/pull/53357

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by VincentLanglet**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #53356
| License       | MIT

Similar to https://github.com/symfony/symfony/pull/53357

Closes https://github.com/symfony/symfony/issues/53356

### CODE REVIEW

File: src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php [hunk 1]
```diff
@@ -46,13 +46,20 @@ public function extract(iterable|string $resource, MessageCatalogue $catalogue):
...
+            $nodes = $this->parser->parse(file_get_contents($file));
+
+            // First run is needed to resolve namespaces in class methods/constants.
+            $traverser->addVisitor(new NodeVisitor\NameResolver());
+            $traverser->traverse($nodes);
+
             /** @var AbstractVisitor&NodeVisitor $visitor */
             foreach ($this->visitors as $visitor) {
                 $visitor->initialize($catalogue, $file, $this->prefix);
                 $traverser->addVisitor($visitor);
```
Comment (welcoMattic) [inline src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php]: The previous `NameResolver` visitor is still present in Visitors. Shouldn't we remove it before the second run?

Comment (VincentLanglet) [reply src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php]: I changed to
```
$nameResolver = new NodeVisitor\NameResolver();
$traverser->addVisitor($nameResolver);
$traverser->traverse($nodes);
$traverser->removeVisitor($nameResolver);
```

And it still works indeed, thanks.

File: src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php [hunk 2]
```diff
@@ -46,13 +46,22 @@ public function extract(iterable|string $resource, MessageCatalogue $catalogue):
     {
         foreach ($this->extractFiles($resource) as $file) {
             $traverser = new NodeTraverser();
+
+            $nodes = $this->parser->parse(file_get_contents($file));
+
+            // First run is needed to resolve namespaces in class methods/constants.
```
Comment (stof) [inline src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php]: Could we visit this as a single run instead of 2 ?

Comment (VincentLanglet) [reply src/Symfony/Component/Translation/Extractor/PhpAstExtractor.php]: I didn't think so.

With The following code
```
            $nameResolver = new NodeVisitor\NameResolver();
            $traverser->addVisitor($nameResolver);

            /** @var AbstractVisitor&NodeVisitor $visitor */
            foreach ($this->visitors as $visitor) {
                $visitor->initialize($catalogue, $file, $this->prefix);
                $traverser->addVisitor($visitor);
            }

            $traverser->traverse($nodes);
```
tests are failing.

but starting thinking about it I would say it's because in the call
```
trans('message', [], App::DOMAIN);
```
We enter the `trans` NODE before the `APP::DOMAIN` so when we're resolving the name is too late.

So I think I found a solution => The TransVisitor (and other symfony visitors) should process translation when LEAVING a node, and not entering in it.
https://github.com/symfony/symfony/pull/53624/commits/8498b80f21e3e001647afc8f1ec59aaa23a42bb3

**Comment by nicolas-grekas** [comment]
Thank you @VincentLanglet.
