### PR TITLE
[HttpKernel] fix triggering deprecation in file locator

### LINKED ISSUE #34556: [FrameworkBundle] Unable to remove deprecation notice in FileLocator?
**Symfony version(s) affected**: 4.4.0
**Description**  
When running our test suite we saw this deprecation notice:

`
2x: Loading the file "../src/UI/Http/Web/Controller/" from the global resource directory "/app/src" is deprecated since Symfony 4.4 and will be removed in 5.0.
`

...that we can't really remove, the FrameworkBundle is injecting the `$paths` parameter to the `FileLocator` service and our routes.yaml resource, configured this way according to the docs:

```
web_controllers:
    resource: '../src/UI/Http/Web/Controller/'
    type: annotation
```

...is the one triggering this notification. AFAIK, this way of configuring the routes with relative paths is still the recommended way, but the deprecation notice seems to trigger whenever there's a non-absolute path being loaded, even though it doesn't use the deprecated `$paths` variable in order to be located, which I believe is a little bit too extreme?

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34556
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by acasademont** [comment]
@xabbuh I can confirm the fix works and the deprecation is not triggered anymore! Nice :D

File: src/Symfony/Component/HttpKernel/Config/FileLocator.php [hunk 1]
```diff
@@ -65,20 +65,30 @@ public function locate($file, $currentPath = null, $first = true)
             || (\strlen($file) > 3 && ctype_alpha($file[0]) && ':' === $file[1] && ('\\' === $file[2] || '/' === $file[2]))
             || null !== parse_url($file, PHP_URL_SCHEME)
         )) {
+            $triggerDeprecation = false;
+
             // no need to trigger deprecations when the loaded file is given as absolute path
             foreach ($this->paths as $deprecatedPath) {
                 if (\is_array($locations)) {
                     foreach ($locations as $location) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Config/FileLocator.php]: what about writing this as `foreach ((array) $locations as $location) {` and remove the is_array check just before?

File: src/Symfony/Component/HttpKernel/Config/FileLocator.php [hunk 2]
```diff
@@ -65,20 +65,30 @@ public function locate($file, $currentPath = null, $first = true)
...
+                        if (null !== $currentPath && 0 === strpos($location, $currentPath)) {
+                            return $locations;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Config/FileLocator.php]: Basically, when there are several paths and one of them is not deprecated, we don't know anymore if a deprecated path is going to be used or not, so we skip the deprecation to prevent a false-positive. This means we might miss a deprecation, but that's the best we can do, isn't it?

Comment (xabbuh) [reply src/Symfony/Component/HttpKernel/Config/FileLocator.php]: Yes, I am afraid there isn't anything we can do about this. Either we trigger deprecations where we shouldn't or we miss some where they would be appropriate.

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.
