### PR TITLE
[HttpFoundation] use InputBag for Request::$request only if data is coming from a form

### LINKED ISSUE #37100: [HttpFoundation] Deprecation error null not allowed InputBag::set()
**Symfony version(s) affected**: 5.1.0

**Description**  
Calling `InputBag::set()`with the second argument set to `null` triggers deprecation error: 
```
Since symfony/http-foundation 5.1: Passing "null" as a 2nd Argument to "Symfony\Component\HttpFoundation\InputBag::set()" is deprecated, pass a string or an array instead.
```

This behaviour causes issues when replacing JSON request body with the JSON decoded value as JSON supports null values.

**How to reproduce**  
```php
/** @var Symfony\Component\HttpFoundation\Request $request */
$request->request->set('key', null);
```

**Possible Solution**  
Allow null values by adding `is_null()`, since the currently used `is_scalar(null)` returns `false`: https://www.php.net/manual/en/function.is-scalar.php

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37100
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by gmponos** [comment]
Wont this make static analysis go crazy.. ???

**Comment by nicolas-grekas** [comment]
@gmponos you made me realize I missed updating the `@var` annotation. Fixed.

**Comment by gmponos** [comment]
Always positive :) at least something good came out from my comment.. check my comment on the [related issue](https://github.com/symfony/symfony/issues/37100#issuecomment-643733532)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

File: src/Symfony/Component/HttpFoundation/Request.php [hunk 1]
```diff
@@ -298,7 +298,9 @@ public static function createFromGlobals()
     {
         $request = self::createRequestFromFactory($_GET, $_POST, [], $_COOKIE, $_FILES, $_SERVER);
 
-        if (0 === strpos($request->headers->get('CONTENT_TYPE'), 'application/x-www-form-urlencoded')
+        if ($_POST) {
+            $request->request = new InputBag($_POST);
```
Comment (gmponos) [inline src/Symfony/Component/HttpFoundation/Request.php:302]: Most of the developers using symfony that will create a form using `form` component, let's say a login form, will get the data back as 

```
`login` => [
    `username` => `user`,
    `password` =>  `password`,
];
```

So I don't see this InputBag here serving the majority..

File: src/Symfony/Component/HttpFoundation/InputBag.php [hunk 2]
```diff
@@ -36,29 +36,18 @@ public function get(string $key, $default = null)
...
-            return $this->parameters;
-        }
-
-        $value = $this->parameters[$key] ?? [];
-        if (!\is_array($value)) {
-            throw new BadRequestException(sprintf('Unexpected value for "%s" input, expecting "array", got "%s".', $key, get_debug_type($value)));
-        }
-
-        return $value;
+        return parent::all($key);
```
Comment (gmponos) [inline src/Symfony/Component/HttpFoundation/InputBag.php:50]: I see that you tried making the behavior between the two bags more similar.. nice.. not sure if you were driven by my comment... but this is indeed nice..

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/InputBag.php:50]: I don't remember exactly my flow of thoughts, but it might be :)

File: src/Symfony/Component/HttpFoundation/Request.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/Request.php:302]: The form component is already strict about strings vs arrays in values and knows how to deal with InputBag.

Comment (gmponos) [reply src/Symfony/Component/HttpFoundation/Request.php:302]: Yes the form component, as a component knows how to deal with the InputBag.. my point is that users that will build a form with the component... they will never use this:

`$request->request->get('login');`

What use cases/bugs are you trying to cover by using for the `request` attribute the InputBag?

> This means many apps just fail with a 500 when adding [] in the query string.

All this started with the scenario that someone access a query parameter and thinking that it is string etc etc.. ok.. although I disagree with the notion of it.. it is a UseCase. I don't see how developers will be protected here... 

All I see is that I have to do this:

```php
        $login = $request->request->get('login');
        return \is_array($login) && isset($login['username']) && isset($login['password']) && isset($login['_token']);
```

to:

```php
        $request = $request->request->all();
        if (!isset($request['login'])) {
            return false;
        }

        $login = $request['login'];
        return \is_array($login) && isset($login['username']) && isset($login['password']) && isset($login['_token']);
```

it's not the code that I have to write.. it's that `ParameterBag::get` is totally useless.. 

Hope I am explaining in the best way.. if not.. maybe we should move on.. there might be more important things to care..

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/Request.php:302]: Your "to" should be:
```php
$request = $request->request->all('login');
return isset($login['username']) && isset($login['password']) && isset($login['_token']);
```

Then you'll let a `BadRequestException` bubble down and become a 400 as it should if you expect `login` to be an array. This "after" is much better than the "before" actually, with a richer behavior and more semantic code.

Comment (gmponos) [reply src/Symfony/Component/HttpFoundation/Request.php:302]: > Then you'll let a BadRequestException bubble down and become a 400 as it should if you expect login to be an array.

I can't.. various technical reasons that are out of the topic of this discussion...

Still this remains:

> it's not the code that I have to write.. it's that ParameterBag::get is totally useless..

**Comment by acasademont** [comment]
Hi @nicolas-grekas , after merging #37327 should this be reverted? The InputBag|ParameterBag hint is making our phpstan analysis a bit useless due to the `mixed` return type of the `ParameterBag::get()` method. Now that null is allowed on `InputBag` this is not that relevant imho.

Not sure if I should open a PR, happy to do it, thx!

**Comment by nicolas-grekas** [comment]
I think using InputBag for accessing form payloads is the correct to provide type-safety *at runtime*.
The fact that static analyzers don't understand how this works should not be a reason to weaken the runtime checks.

**Comment by acasademont** [comment]
Sure! What I mean is that InputBag could be used again for all types of requests, not only POST ones, no? With #37327 merged, the original bug #37100 is fixed too and then we can tighten the typehints again on the `Request`.

**Comment by nicolas-grekas** [comment]
Possibly yes. InputBag is more restrictive than ParameterBag, but maybe that's still fine in practice even when the content is json. Feel free to give it a try :)
