### PR TITLE
[Mailer] Allow manually stop() of SmtpTransport

### LINKED ISSUE #43237: Ability to start & stop SMTP connection when needed
**Description**
I am using Mailer in Messenger worker long lived process with AWS SES SMTP interface and it keep throwing error:
> Expected response code "250" but got code "451", with message "451 4.4.2 Timeout waiting for data from client.

I know i can get rid of this error by setting `ping_threshold: 0`  but it is not efficient since the transport have to ping server on every email sending out. It is better to manually stop transport connection when Messenger message get handled (with all emails are sent out) and it will auto start on next message handling. But the problem is SmtpTransport `start` & `stop` methods are private and i have no way to access them.

### PR DESCRIPTION
**Pull request by dvaeversted**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #43237
| License       | MIT
| Doc PR        | 

Mark the `stop()` method on SmtpTransport as public, to allow greater control in long running jobs and similar.

### CODE REVIEW

File: src/Symfony/Component/Mailer/Transport/Smtp/SmtpTransport.php [hunk 1]
```diff
@@ -240,7 +240,12 @@ private function doRcptToCommand(string $address): void
         $this->executeCommand(sprintf("RCPT TO:<%s>\r\n", $address), [250, 251, 252]);
     }
 
-    private function start(): void
+    /**
+     * Manually connect to the SMTP server, will happen automatically when sending mails.
```
Comment (fabpot) [inline src/Symfony/Component/Mailer/Transport/Smtp/SmtpTransport.php]: I would also add a note (same for the stop method) about when this is useful. We should make it clear that this should be not called manually most of the time, except for some very specific use cases that we should describe.

Comment (dvaeversted) [reply src/Symfony/Component/Mailer/Transport/Smtp/SmtpTransport.php]: I am actually unsure about the use case for the having access to manually start the transport, so i think the right option here is to keep it as private.
Will add additional text to the stop() method tho.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @dvaeversted.

**Comment by dvaeversted** [comment]
What is the chance of getting this merged into the 5.4 branch as well ?

https://symfony.com/blog/the-end-of-swiftmailer

According to this, Swiftmailer was disconitnued as 5.4 was released, which now puts users of the LTS releases in a limbo state if this feature is a requirement to successfully get rid of the Swiftmailer dependency.
