### PR TITLE
[Validator] Fixed default group for nested composite constraints

### LINKED ISSUE #33986: ConstraintValidator allows extra fields if all children are optional
**Symfony version(s) affected**: 4.3.3

**Description**  
When running a validator on a collection that only has optional fields it does not give violations on extra fields. It does work however if I make one of the fields required.

**How to reproduce**  
```php
        $toValidate = ['a' => 'b'];

        $constraints = new Assert\Collection([
            'firstName' => new Assert\Optional(),
            'lastName' => new Assert\Optional(),
            'username' => new Assert\Optional(),
        ]);

        $validator = Validation::createValidator();
        $violations = $validator->validate($toValidate, $constraints, new Assert\GroupSequence(['Default', 'custom']));
        // $violations is empty
```
If I change firstName to `new Assert\Positive()` as example, then it does work.
```
{"errors":["[firstName]: This field is missing.","[a]: This field was not expected."]}
```

### PR DESCRIPTION
**Pull request by HeahDude**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #33986
| License       | MIT
| Doc PR        | ~

Take a breath: when composite constraints are nested in a parent composite constraint without having non composite nested constraints (i.e empty), then the default group is not added, making the validator failing to validate in any group (including default), because there is no group at all, which should never happen.

### CODE REVIEW

**Review by jannes-io — APPROVED** [review]

File: src/Symfony/Component/Validator/Constraints/Composite.php [hunk 1]
```diff
@@ -83,6 +83,13 @@ public function __construct($options = null)
             $mergedGroups = [];
 
             foreach ($nestedConstraints as $constraint) {
+                if ($constraint instanceof self && !$constraint->groups) {
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/Constraints/Composite.php:86]: Why doing this here and not below?

I mean something like this:

```php
$this->groups = array_keys($mergedGroups);

if (!$this->groups) {
    $this->groups = [self::DEFAULT_GROUP];
}
```

Comment (HeahDude) [reply src/Symfony/Component/Validator/Constraints/Composite.php]: I guess this is equivalent, I've updated for a ternary because it's simpler indeed.

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @HeahDude.
