### PR TITLE
[PhpUnitBridge] CoverageListenerTrait update for PHPUnit 8.5/9.x

### LINKED ISSUE #37637: [PhpUnitBridge] CoverageListenerTrait is incompatible with PHPUnit 8.5
**Symfony version(s) affected**: 3.4

**Description**  

When running the testsuite of PhpUnitBridge with PHPUnit 8.5, it fails with the following exception:

```
ReflectionException: Property PHPUnit\Util\Test::$annotationCache does not exist in /path/to/symfony/src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php:73
```

**How to reproduce**  

Run the test suite of Symfony's 3.4 branch with PHPUnit 8.5.

**Additional context**  

Apparently, PhpUnitBridge tries to fiddle with a private property `PHPUnit\Util\Test::$annotationCache`.

https://github.com/symfony/symfony/blob/a397c490b018095a6a4bee3b107c80d109293976/src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php#L73

That property has been removed in PHPUnit 8.4 and replaced by a new class `PHPUnit\Util\Annotation\Registry`.

### PR DESCRIPTION
**Pull request by sanmai**
Updated to use `PHPUnit\Util\Annotation\Registry` and related classes.

Fixes #37637

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | yes
| Deprecations? | no 
| Tickets       | Fix #37637
| License       | MIT
| Doc PR        | n/a

- [x] Fixes the issue under PHPUnit 8.5+
- [x] Tests TBD

If this is a sensible approach, I will try to add a test for this addition.

### CODE REVIEW

File: src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php [hunk 1]
```diff
@@ -13,7 +13,7 @@
 
 use PHPUnit\Framework\TestCase;
 use PHPUnit\Framework\Warning;
-use PHPUnit\Util\Test;
```
Comment (derrabus) [inline src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php:16]: We can keep the import.

Comment (sanmai) [reply src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php:16]: That was CS Fixer doings. Should I get it back in spite of it?

Comment (sanmai) [reply src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php:16]: OK, I got it back

File: src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php [hunk 2]
```diff
@@ -78,13 +75,45 @@ public function startTest($test)
...
+
+        $this->addCoversForClassToAnnotationCache($test, $covers);
+    }
+
+    private function addCoversForClassToAnnotationCache($test, $covers)
+    {
+        $testClass = \PHPUnit\Util\Test::class;
+        if (!class_exists($testClass, false)) {
+            $testClass = \PHPUnit\Util\Test::class;
+        }
```
Comment (derrabus) [inline src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php:93]: That doesn't make sense. You're setting `$testClass` to the same value in both cases.

File: src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php (hunk 1 above)
Comment (sanmai) [reply src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php:16]: OK, I got it back

￼

File: src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php (hunk 2 above)
Comment (sanmai) [reply src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php]: You're absolutely right. Getting this back.

File: src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php (hunk 1 above)
Comment (derrabus) [reply src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php:16]: Yes, the CS Fixer removes it because you've replaced `Test` with its FQCN throughout this file. If you revert this as well, the CS Fixer won't complain anymore.

File: src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php [hunk 3]
```diff
@@ -78,13 +76,45 @@ public function startTest($test)
...
+
+            return;
+        }
+
+        $this->addCoversForClassToAnnotationCache($test, $covers);
+    }
+
+    private function addCoversForClassToAnnotationCache($test, $covers)
+    {
+        $testClass = \PHPUnit\Util\Test::class;
```
Comment (derrabus) [inline src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php:90]:
```suggestion
        $testClass = Test::class;
```

Comment (sanmai) [reply src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php]: Thank you. I removed everything I happen [to inherit from 3.4](https://github.com/symfony/symfony/blob/4351a70637105102f832216e4b6f6cbe1cb9ab0f/src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php#L68-L71).

**Comment by sanmai** [comment]
I think I addressed all comments. How should I test this change?

**Review by nicolas-grekas — APPROVED** [review]
> I see there's a test, but it assumes a currently used version of PHPUnit. Should this be enough?

Yes, we're not going to test with multiple versions of phpunit.

**Comment by fabpot** [comment]
Thank you @sanmai.

**Comment by derrabus** [comment]
Thank you for working on this issue, @sanmai! 🚀
