### PR TITLE
[AssetMapper] Detect import with a sequence parser

### LINKED ISSUE #58928: api platform no longer installs seamlessly with Symfony
### Symfony version(s) affected

7.1

### Description

**API Platform version(s) affected**: 4.0

A simple install with a Symfony webapp used to work but now throws an error.

### How to reproduce

```bash
symfony new MyApp  --webapp && cd MyApp
composer req api
bin/console make:entity -a Task -n
symfony server:start -d
symfony open:local --path=/api
```

image

The files themselves, e.g. 
https://127.0.0.1:8029/assets/bundles/apiplatform/swagger-ui/swagger-ui-standalone-preset-4fec96b52efef25338c0ee2a2c2619e4.js

image

I've reported this in api-platform as well: https://github.com/api-platform/api-platform/issues/2801

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by smnandre**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58928  and #58944  (maybe)
| License       | MIT

Third attempt after #54134 and #58999.. this is the good one 👍 

I initially started this PR to learn / try things, but it really behaves well.. and _may_ stop (or help stopping) what seems to be a never-ending suite of special cases.

Open to any feedback

### CODE REVIEW

**Comment by smnandre** [comment]
Dear Carson....  you're doing a bad ChatGpt impression right now 😅

File: src/Symfony/Component/AssetMapper/Compiler/Parser/JavascriptParser.php [hunk 1]
```diff
@@ -0,0 +1,186 @@
...
+
+/**
+ * Parses JavaScript content to identify sequences of strings, comments, etc.
+ *
+ * @author Simon André <smn.andre@gmail.com>
+ *
+ * @internal
+ */
+class JavascriptParser
+{
```
Comment (dunglas) [inline src/Symfony/Component/AssetMapper/Compiler/Parser/JavascriptParser.php]: Nit: maybe should we use an enum?

File: src/Symfony/Component/AssetMapper/Compiler/Parser/JavascriptParser.php [hunk 2]
```diff
@@ -0,0 +1,186 @@
...
+     * @var CodeSequence[]
+     */
+    private array $sequences = [];
+
+    private function __construct(
+        private string $content,
+    ) {
+        $this->contentEnd = \strlen($content);
+
+        $chars = [
```
Comment (dunglas) [inline src/Symfony/Component/AssetMapper/Compiler/Parser/JavascriptParser.php]: Move the list to a constant?

**Review by dunglas — COMMENTED** [review]
Thank you for working on this. This looks good to me overall, but my review was very very quick and I didn't compared with mainstream JS parsers so I may have missed things.

**Comment by smnandre** [comment]
> Thank you for working on this. This looks good to me overall, but my review was very very quick and I didn't compared with mainstream JS parsers so I may have missed things.

No worry.. and thank you for taking the time :)

My main question is currently: how internal can/should we make this ?  Maintaining for AssetMapper is already something, but probably not something we want to publish with BC promise, documentation, etc?

(will address your feedback later tonight!)

**Comment by dunglas** [comment]
I would make it entirely internal

File: src/Symfony/Component/AssetMapper/Compiler/Parser/CodeSequence.php [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+class CodeSequence implements \Stringable
+{
+    public function __construct(
+        private readonly string $type,
+        private readonly int $start,
+        private readonly int $end,
+    ) {
+    }
+
+    public function getType(): string
```
Comment (OskarStark) [inline src/Symfony/Component/AssetMapper/Compiler/Parser/CodeSequence.php]: If internal  I think we can use public properties as we don't need to maintain BC

**Comment by smnandre** [comment]
@dunglas @OskarStark if we use it only in this specific use case, we don't need the value object, because we don't need to keep the previously matched sequences.

That's why i simplified the code here to focus only on the current sequence.

File: src/Symfony/Component/AssetMapper/Compiler/Parser/CodeSequence.php (hunk 3 above)
Comment (smnandre) [reply src/Symfony/Component/AssetMapper/Compiler/Parser/CodeSequence.php]: Remove the VO entirely 😅

**Review by dunglas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @smnandre.

**Comment by marsaldev** [comment]
@smnandre thank you!
do you think you could fix this also on the 6.4?
