### PR TITLE
[DependencyInjection] Fix binding tagged services to containers

### LINKED ISSUE #34913: Named argument binding doesn't support !tagged_locator
**Symfony version(s) affected**: 4.4.0

**Description**  
Named argument binding doesn't support `!tagged_locator`.

**How to reproduce**  
```yaml
services:
    _defaults:
        bind:
            Psr\Container\ContainerInterface $foo: !tagged_locator my.locator
```

>Invalid value for binding key "Psr\Container\ContainerInterface $foo" for service "Some\Unrelated\Service\That\Doesn't\Even\Have\$foo\Argument": expected null, an instance of Symfony\Component\DependencyInjection\Reference or an instance of Symfony\Component\DependencyInjection\Definition or an instance of Symfony\Component\DependencyInjection\Argument\TaggedIteratorArgument, object given.

**Possible Solution**  
Works fine if type is omitted, e.g. `$foo: !tagged_locator my.locator`. Breaks as soon as `Psr\Container\ContainerInterface` is specified as a type prefix, by attempting to inject into every service instead of just those with matching parameters.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34913
| License       | MIT
| Doc PR        | -

We missed this part in #33623

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php [hunk 1]
```diff
@@ -126,8 +127,8 @@ protected function processValue($value, $isRoot = false)
                 continue;
             }
 
-            if (null !== $bindingValue && !$bindingValue instanceof Reference && !$bindingValue instanceof Definition && !$bindingValue instanceof TaggedIteratorArgument) {
-                throw new InvalidArgumentException(sprintf('Invalid value for binding key "%s" for service "%s": expected null, an instance of %s or an instance of %s or an instance of %s, %s given.', $key, $this->currentId, Reference::class, Definition::class, TaggedIteratorArgument::class, \gettype($bindingValue)));
+            if (null !== $bindingValue && !$bindingValue instanceof Reference && !$bindingValue instanceof Definition && !$bindingValue instanceof TaggedIteratorArgument && !$bindingValue instanceof ServiceLocatorArgument)  {
+                throw new InvalidArgumentException(sprintf('Invalid value for binding key "%s" for service "%s": expected null, %s, %s, %s or ServiceLocatorArgument, %s given.', $key, $this->currentId, Reference::class, Definition::class, TaggedIteratorArgument::class, \gettype($bindingValue)));
```
Comment (stof) [inline src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php]: why using the full class name for other classes but not for ServiceLocatorArgument in the message ?

Comment (nicolas-grekas) [reply src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php]: I think repeating the full namespace twice would not make the message easier to understand, quite the contrary to me.
