### PR TITLE
[HttpFoundation] [Session] Regenerate invalid session id

### LINKED ISSUE #45755: The session id is too long or contains illegal characters
### Symfony version(s) affected

5.4.6

### Description

Hi, have a problem in my project. Sometimes in log i see such messages:
```bash

[2022-03-16T03:49:44.259705+03:00] php.WARNING: Warning: SessionHandler::read(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' {"exception":"[object] (ErrorException(code: 0): Warning: SessionHandler::read(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' at /var/www/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php:49)"} []
[2022-03-16T03:49:44.259791+03:00] php.WARNING: Warning: session_start(): Failed to read session data: user (path: /var/www/var/sessions/prod) {"exception":"[object] (ErrorException(code: 0): Warning: session_start(): Failed to read session data: user (path: /var/www/var/sessions/prod) at /var/www/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:149)"} []
[2022-03-16T03:49:44.266919+03:00] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session." at /var/www/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php line 150 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session. at /var/www/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:150)"} []
```

Framework config:
```yaml
framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: 1814400
        gc_maxlifetime: 1814400
        name: LIFESESSID
        cookie_secure: 'auto'
        cookie_samesite: 'strict'
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true
```

How can i fix it ? I`ve read that it`s bug of php, but maybe you know about fixing this problem in symfony ?

### How to reproduce

I can`t reproduce this error, but i think, could manually set session_id and get error

### Possible Solution

I think about writing a simple wrapper around `NativeSessionStorage` that will check the validity of the session ID before calling the handler.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by peter17**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45755
| License       | MIT
| Doc PR        | no

Currently, having a PHPSESSID which does not match `/^[a-zA-Z0-9,\-]{1,123}$/` (see https://www.php.net/manual/fr/function.session-start.php) will produce a php.WARNING and then a RuntimeException (please read #45755).

I don't think there is a nice way to handle this so I propose to simply ignore invalid values.

With this PR, a value for PHPSESSID that does not match the regex will be ignored and a new session id will be generated. Then, the behavior will be the same as if no session existed, so a new session will be started and a new PHPSESSID will be defined.

It looks like Session storage is currently untested so I don't know how to test this...

Best regards

### CODE REVIEW

**Comment by peter17** [comment]
Link bug #45755

**Comment by peter17** [comment]
@nicolas-grekas Any idea about this? Thanks a lot in advance. Best regards

**Comment by nicolas-grekas** [comment]
I don't think changing a superglobal to accommodate some code is the correct approach. 
Can you figure out another way that doesn't involve mutating `$_COOKIE`?

**Comment by peter17** [comment]
Thanks for your feedback. I understand your concern. I will try to find a better way!

**Comment by peter17** [comment]
@nicolas-grekas I propose a new way that does not involve mutating a superglobal: I use the native PHP functions to generate a new session ID. Therefore, session_start will work normally.

Best regards

**Comment by peter17** [comment]
NB: the Appveyor build failed with "Build execution time has reached the maximum allowed time for your plan (20 minutes)."

I don't think this failure is relevant. I could not find how to retry the build.

File: src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php [hunk 1]
```diff
@@ -152,6 +152,14 @@ public function start()
             throw new \RuntimeException(sprintf('Failed to start the session because headers have already been sent by "%s" at line %d.', $file, $line));
         }
 
+        $sessionName = session_name();
+        $sessionId = $_COOKIE[$sessionName] ?? null;
+        // validate according to https://www.php.net/manual/fr/function.session-start.php
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php]: let's remove this one

File: src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php [hunk 2]
```diff
@@ -152,6 +152,14 @@ public function start()
             throw new \RuntimeException(sprintf('Failed to start the session because headers have already been sent by "%s" at line %d.', $file, $line));
         }
 
+        $sessionName = session_name();
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php]: we don't need this variable, let's inline the call

File: src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php [hunk 3]
```diff
@@ -152,6 +152,14 @@ public function start()
...
+        $sessionId = $_COOKIE[$sessionName] ?? null;
+        // validate according to https://www.php.net/manual/fr/function.session-start.php
+        if ($sessionId && !preg_match('/^[a-zA-Z0-9,\-]{1,123}$/', $sessionId)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php]: according to https://stackoverflow.com/questions/12240922/what-is-the-length-of-a-php-session-id-string, we'd rather go with `'/^[a-zA-Z0-9,-]{22,}$/'` for the regexp.

**Review by nicolas-grekas — COMMENTED** [review]
Can this be tested somehow?

**Comment by peter17** [comment]
@nicolas-grekas thanks for your review, I applied the requested changes.

I will attempt to write a test.

Best regards

**Comment by peter17** [comment]
@nicolas-grekas I added a test. It fails without my patch and passes with it.

Best regards

**Review by nicolas-grekas — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @peter17.

**Comment by Flo-JB** [comment]
After that update we got a problem in one of our projects regenerating the session on each page view. The new implemented regex fails each time because the newly created value in the session cookie is "wrong" too.

The basic problem comes from the nelmio security plugin (signed_cookie feature). This feature extends the session cookie with a "." and an additional hash value. Especially the "." causes the regex to fail.

I will create a ticket in the nelmio project - but leave this comment for others with similar problems

**Comment by peter17** [comment]
@Flo-JB thanks for reporting this and for opening the issue in NelmioSecurityBundle

What I don't understand is that the current issue was about avoiding an exception when `session_start()` is called with an invalid session id. Does this mean that previously, with NelmioSecurityBundle, the exception was thrown by Symfony and catched by NelmioSecurityBundle?

**Comment by Flo-JB** [comment]
I personally didn't notice any Symfony exception before.

With the signd_cookie-feature enabled our session cookies get modified to s.th. like that:
4snfl14u0ooups9ifmhd9cjsk9.1ffb65204121792f16e1a5f3cc3f2cb6e5806157a508dc6df9c07a3d4c181b45

I didn't delve deeper in Nelmios code but I think they just append this verification hash after the session was started (In our case with a valid session_id) and put the modified value in the session cookie.

Your check fails right now because you take the whole cookie contents (sessionid + separator + hash) without separating the session id out from that mixed value.

**Comment by alexpott** [comment]
This also causes issues for Drupal fwiw - https://www.drupal.org/project/drupal/issues/3285696

I'm not sure that the premise of this issue about which characters are allowed in a session ID or indeed used in a session ID is correct. See https://www.php.net/manual/en/function.session-id.php it says:

> Depending on the session handler, not all characters are allowed within the session id. For example, the file session handler only allows characters in the range a-z A-Z 0-9 , (comma) and - (minus)!

So we've limited the characters to the file session handler but we might not be using that.

**Comment by alexpott** [comment]
This gets even more interesting when the session ID as a cookie value - the legal characters there are, according to https://curl.se/rfc/cookie_spec.html, do not include a comma!
