### PR TITLE
[Cache] Send Predis SSL options in the $hosts parameter

### LINKED ISSUE #46465: [Symfony/Cache] Redis TLS Skip Peer Verification Ignored (Predis)
### Symfony version(s) affected

5.4

### Description

Hi all,

I'm trying to use Heroku's Redis v6 TLS for caching with predis/predis v1.1. Heroku self signs certificates and instructs to skip peer verification by adding `?ssl[verify_peer_name]=0&ssl[verify_peer]=0` to redis dsn string when using Predis.

The connection fails due to failed certificate verification.

### How to reproduce

The project is configured to use free Heroku Redis v6 TLS with predis/predis v1.1 and symfony/cache 5.4.

Clone repo: https://github.com/pavleocom/bug-symfony-cache-predis

cd into root directory

composer install

Run in console: `php -S localhost:8081 -t public/`

Go to `http://localhost:8081/test-cache` in your browser, refresh a few times

Return to console to find errors similar to these:

```bash
[Thu May 26 19:21:54 2022] [warning] Failed to fetch key "test": Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

[Thu May 26 19:21:54 2022] [info] Lock acquired, now computing item "test"

[Thu May 26 19:21:54 2022] [warning] Failed to save key "test" of type array: Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:

```

### Possible Solution

It seems ssl configurations need to be passed as part of the first parameter of Predis/Client:
```php
// Named array of connection parameters:
$client = new Predis\Client([
  'scheme' => 'tls',
  'ssl'    => ['cafile' => 'private.pem', 'verify_peer' => true],
]);

// Same set of parameters, but using an URI string:
$client = new Predis\Client('tls://127.0.0.1?ssl[cafile]=private.pem&ssl[verify_peer]=1');
```
Source: https://github.com/predis/predis (Connecting to Redis)

But ssl configurations are being passed as part of the second parameter of Predis/Client only:

https://github.com/symfony/cache/blob/5.4/Traits/RedisTrait.php#L326

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by magnusnordlander**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #46465
| License       | MIT

Predis accepts SSL options in the `$hosts` parameter, not in the `$params` parameter. From my perspective, this is really only applicable when using `rediss://host:port` style DSNs, where you might want to add `?ssl[verify_peer]=0` or something similar. 

I'm unsure how to write a good test for this, since there doesn't seem to be any standard Redis host with TLS that requires additional options in the test runner. Happy to take suggestions on how to approach a test, if that's deemed necessary.

### CODE REVIEW

File: src/Symfony/Component/Cache/Traits/RedisTrait.php [hunk 1]
```diff
@@ -334,6 +334,10 @@ public static function createConnection(string $dsn, array $options = [])
             }
             if (1 === \count($hosts) && !($params['redis_cluster'] || $params['redis_sentinel'])) {
                 $hosts = $hosts[0];
+
+                if (isset($params['ssl'])) {
+                    $hosts['ssl'] = $params['ssl'];
```
Comment (stof) [inline src/Symfony/Component/Cache/Traits/RedisTrait.php]: what about self-signed certificates on a redis cluster or a redis sentinel ?

Comment (magnusnordlander) [reply src/Symfony/Component/Cache/Traits/RedisTrait.php]: I did consider this, and I'm open to handle clusters/sentinel, but in that case, I would guess that most people would define ssl parameters per host, not globally? But I suppose that I could add the parameters to each host if they haven't already been defined as a part of each host.

**Review by nicolas-grekas — COMMENTED** [review]
Can you confirm that this change would still work?

<details>

```diff
diff --git a/src/Symfony/Component/Cache/Tests/Adapter/PredisAdapterTest.php b/src/Symfony/Component/Cache/Tests/Adapter/PredisAdapterTest.php
index e326dba76b..a35859d2b6 100644
--- a/src/Symfony/Component/Cache/Tests/Adapter/PredisAdapterTest.php
+++ b/src/Symfony/Component/Cache/Tests/Adapter/PredisAdapterTest.php
@@ -48,4 +48,29 @@ class PredisAdapterTest extends AbstractRedisAdapterTestCase
         ];
         $this->assertSame($params, $connection->getParameters()->toArray());
     }
+
+    public function testCreateSslConnection()
+    {
+        $redisHost = getenv('REDIS_HOST');
+
+        $redis = RedisAdapter::createConnection('rediss://'.$redisHost.'/1?ssl[verify_peer]=0', ['class' => \Predis\Client::class, 'timeout' => 3]);
+        $this->assertInstanceOf(\Predis\Client::class, $redis);
+
+        $connection = $redis->getConnection();
+        $this->assertInstanceOf(StreamConnection::class, $connection);
+
+        $redisHost = explode(':', $redisHost);
+        $params = [
+            'scheme' => 'tls',
+            'host' => $redisHost[0],
+            'port' => (int) ($redisHost[1] ?? 6379),
+            'ssl' => ['verify_peer' => '0'],
+            'persistent' => 0,
+            'timeout' => 3,
+            'read_write_timeout' => 0,
+            'tcp_nodelay' => true,
+            'database' => '1',
+        ];
+        $this->assertSame($params, $connection->getParameters()->toArray());
+    }
 }
diff --git a/src/Symfony/Component/Cache/Traits/RedisTrait.php b/src/Symfony/Component/Cache/Traits/RedisTrait.php
index 07633a9d3f..67d8663169 100644
--- a/src/Symfony/Component/Cache/Traits/RedisTrait.php
+++ b/src/Symfony/Component/Cache/Traits/RedisTrait.php
@@ -349,7 +349,7 @@ trait RedisTrait
             }
             $params['exceptions'] = false;
 
-            $redis = new $class($hosts, array_diff_key($params, array_diff_key(self::$defaultConnectionOptions, ['ssl' => null])));
+            $redis = new $class($hosts, array_diff_key($params, self::$defaultConnectionOptions));
             if (isset($params['redis_sentinel'])) {
                 $redis->getConnection()->setSentinelTimeout($params['timeout']);
             }
```

</details>

**Review by nicolas-grekas — APPROVED** [review]
I applied my patch, please report back if there's an issue with it.

**Comment by nicolas-grekas** [comment]
Thank you @magnusnordlander.
