### PR TITLE
[Serializer] Fixing PHP warning in the ObjectNormalizer with MaxDepth enabled

### LINKED ISSUE #54378: [Serializer] PHP Warning - undefined array key in AbstractObjectNormalizer::isMaxDepthReached
### Symfony version(s) affected

6.4.5

### Description

A bundle we use (rompetompe/inertia-bundle) calls the Symfony serializer on any data that's passed to it (that will be converted to JSON for use by Inertia.js), after upgrading to Symfony 6 we're seeing PHP warnings in some situations. It seems to only happen when there is a stdClass object in the data that's passed to the serializer (from a `json_decode` call somewhere else in the app). 

The line that causes the warning is this one:

```
if (!($enableMaxDepth = $context[self::ENABLE_MAX_DEPTH] ?? $this->defaultContext[self::ENABLE_MAX_DEPTH] ?? false)
            || null === $maxDepth = $attributesMetadata[$attribute]?->getMaxDepth()
        ) {
            return false;
        }
```

It happens because `$attributesMetadata` is an empty array in this context and `$attribute` is a string (which is one of the properties of the stdClass object it's trying to normalize).  Earlier in the normalizer there is this chunk of code:

```
$class = ($this->objectClassResolver)($object);
$classMetadata = $this->classMetadataFactory?->getMetadataFor($class);
$attributesMetadata = $this->classMetadataFactory?->getMetadataFor($class)->getAttributesMetadata();
```

I mention this, because there is a check a little bit below this to see if `$attributesMetadata` is `null` and then it bypasses the `isMaxDepthReached` call:

```
foreach ($attributes as $attribute) {
            $maxDepthReached = false;
            if (null !== $attributesMetadata && ($maxDepthReached = $this->isMaxDepthReached($attributesMetadata, $class, $attribute, $context)) && !$maxDepthHandler) {
                continue;
            }
```

In the application `$attributesMetadata` is an empty array, but in an isolated test case that I've tried to put together, `$attributesMetadata` ends up being `null` so I can't reproduce the warning in an isolated test case.

Perhaps there's something else to this (why does `stdClass` have attributes?) in the context of the app, but it does seem like there should be a check if the `$attribute` is set on `$attributesMetadata` in the `isMaxDepthReached` method to avoid this warning.

Aside from the Warning being thrown, the serialization/normalization works as expected.

### How to reproduce

I put this test case together to try to reproduce in the simplest way possible but it doesn't throw the warning as mentioned above:

```
<?php

ini_set('display_errors', 1);
ini_set('error_reporting', E_ALL);

use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer;

include_once 'vendor/autoload.php';

$object = new stdClass();
$object->string = 'yes';

$serializer = new Symfony\Component\Serializer\Serializer([
    new Symfony\Component\Serializer\Normalizer\UnwrappingDenormalizer(),
    new Symfony\Component\Serializer\Normalizer\ProblemNormalizer(),
    new Symfony\Component\Serializer\Normalizer\UidNormalizer(),
    new Symfony\Component\Serializer\Normalizer\DateTimeNormalizer(),
    new Symfony\Component\Serializer\Normalizer\DateTimeZoneNormalizer(),
    new Symfony\Component\Serializer\Normalizer\DateIntervalNormalizer(),
    new Symfony\Component\Serializer\Normalizer\FormErrorNormalizer(),
    new Symfony\Component\Serializer\Normalizer\BackedEnumNormalizer(),
    new Symfony\Component\Serializer\Normalizer\DataUriNormalizer(),
    new Symfony\Component\Serializer\Normalizer\JsonSerializableNormalizer(),
    new Symfony\Component\Serializer\Normalizer\ArrayDenormalizer(),
    new Symfony\Component\Serializer\Normalizer\ObjectNormalizer(),
], [
    new Symfony\Component\Serializer\Encoder\XmlEncoder(),
    new Symfony\Component\Serializer\Encoder\JsonEncoder(),
    new Symfony\Component\Serializer\Encoder\YamlEncoder(),
    new Symfony\Component\Serializer\Encoder\CsvEncoder(),
]);

$page = [
    'props' => [
        'string' => 'yes',
        'array' => ['string' => 'yes'],
        'object' => $object,
        'nested_object' => [
            'string' => 'yes',
            'array' => ['string' => 'yes'],
            'object' => $object,
        ],
    ]
];

$context = [];

$json = $serializer->serialize($page, 'json', array_merge([
    'json_encode_options' => JsonResponse::DEFAULT_ENCODING_OPTIONS,
    AbstractNormalizer::CIRCULAR_REFERENCE_HANDLER => function () { return null; },
    AbstractObjectNormalizer::PRESERVE_EMPTY_OBJECTS => true,
    AbstractObjectNormalizer::ENABLE_MAX_DEPTH => true,
], $context));

var_dump($json);
```

I don't know how to make this test case set attributes on the `stdClass` class like it's doing in the app, but I've tried to replicate how the serializer is configured as best as possible (as far as I can tell, the inertia-bundle just uses `@serializer` for the serializer dependency, which we're not modifying at all, so should be the Symfony default Serializer config).

### Possible Solution

This could probably be fixed in a couple of ways, first, if `$attributesMetadata` is an empty array, it seems like it should probably be treated the same as if it were `null`.

In the `normalize` method of `AbstractObjectNormalizer` this check:

```
foreach ($attributes as $attribute) {
            $maxDepthReached = false;
            if (null !== $attributesMetadata && ($maxDepthReached = $this->isMaxDepthReached($attributesMetadata, $class, $attribute, $context)) && !$maxDepthHandler) {
                continue;
            }
```

could be changed to also check the count of the metadata variable so that the `isMaxDepthReached` method isn't called with an empty array:

```
foreach ($attributes as $attribute) {
            $maxDepthReached = false;
            if (null !== $attributesMetadata && count($attributesMetadata) > 0 && ($maxDepthReached = $this->isMaxDepthReached($attributesMetadata, $class, $attribute, $context)) && !$maxDepthHandler) {
                continue;
            }
```

This does fix it in our application.

Alternatively, the `isMaxDepthReached` method could be modified in a similar way to check if the `$attribute` is a key on the passed in `$attributesMetadata`.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jaydiablo**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54378
| License       | MIT

This fixes a specific issue I ran into when testing an application in Symfony 6 that uses the rompetompe/inertia-bundle to serialize PHP data to JSON for use by Inertia.js.

Added a test that is as minimal as necessary for the Warning to be thrown. I tested against Symfony 5.4 as well, but the issue doesn't seem to be present there (could have something to do with 5.4 not having the AttributeLoader).

### CODE REVIEW

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php [hunk 1]
```diff
@@ -1025,6 +1027,45 @@ protected function createChildContext(array $parentContext, string $attribute, ?
 
         $this->assertFalse($normalizer->childContextCacheKey);
     }
+
+    /**
+     * @see https://github.com/symfony/symfony/issues/54378
```
Comment (OskarStark) [inline src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: We usually do not add GitHub links in the code

Comment (jaydiablo) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: Thanks @OskarStark, removed.

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 2]
```diff
@@ -287,8 +287,6 @@ abstract protected function extractAttributes(object $object, ?string $format =
 
     /**
      * Gets the attribute value.
-     *
-     * @return mixed
```
Comment (derrabus) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: Please revert (and ignore fabbot).

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 3]
```diff
@@ -302,9 +300,6 @@ public function supportsDenormalization(mixed $data, string $type, ?string $form
         return class_exists($type) || (interface_exists($type, false) && null !== $this->classDiscriminatorResolver?->getMappingForClass($type));
     }
 
-    /**
-     * @return mixed
-     */
```
Comment (derrabus) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: Revert

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php [hunk 4]
```diff
@@ -1025,6 +1027,42 @@ protected function createChildContext(array $parentContext, string $attribute, ?
...
+                    'object' => $object,
+                ],
+            ],
+        ];
+
+        $context = [];
+
+        $json = $serializer->serialize($page, 'json', array_merge([
+            'json_encode_options' => 15, // JsonResponse::DEFAULT_ENCODING_OPTIONS
+            AbstractNormalizer::CIRCULAR_REFERENCE_HANDLER => function () { return null; },
```
Comment (derrabus) [inline src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]:
```suggestion
            AbstractNormalizer::CIRCULAR_REFERENCE_HANDLER => static fn () => null,
```

**Review by derrabus — COMMENTED** [review]
Can you elaborate a bit on how your fix works? I don't understand it. 😓

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php [hunk 5]
```diff
@@ -1025,6 +1027,42 @@ protected function createChildContext(array $parentContext, string $attribute, ?
...
+
+    public function testNormalizationWithMaxDepthOnStdclassObjectDoesNotThrowWarning()
+    {
+        $object = new \stdClass();
+        $object->string = 'yes';
+
+        $loader = new LoaderChain([
+            new AttributeLoader(),
+        ]);
+        $classMetadataFactory = new ClassMetadataFactory($loader);
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]:
```suggestion
        $classMetadataFactory = new ClassMetadataFactory(new AttributeLoader());
```

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php [hunk 6]
```diff
@@ -1025,6 +1027,42 @@ protected function createChildContext(array $parentContext, string $attribute, ?
...
+
+        $serializer = new Serializer([
+            new ObjectNormalizer($classMetadataFactory),
+        ], [
+            new JsonEncoder(),
+        ]);
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]:
```suggestion
        $normalizer = new ObjectNormalizer($classMetadataFactory);
```
You're only interacting with the normalization stage, therefore you can use directly the normalizer

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php [hunk 7]
```diff
@@ -1025,6 +1027,42 @@ protected function createChildContext(array $parentContext, string $attribute, ?
...
+            'props' => [
+                'property' => [
+                    'object' => $object,
+                ],
+            ],
+        ];
+
+        $context = [];
+
+        $json = $serializer->serialize($page, 'json', array_merge([
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: As context is empty, this `array_merge` is not needed

**Review by mtarld — CHANGES_REQUESTED** [review]

**Comment by stof** [comment]
What happens if `attributesMetadata` has an entry only for a different attribute ? `null === $maxDepth = $attributesMetadata[$attribute]?->getMaxDepth()` would still trigger a warning in such case.

To me, the right fix would be handle properly the case where there is no `$attribute` key in the array.

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php (hunk 2 above)
Comment (jaydiablo) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: reverted

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php (hunk 3 above)
Comment (jaydiablo) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: reverted

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php (hunk 4 above)
Comment (jaydiablo) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: thanks, changed this

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php (hunk 5 above)
Comment (jaydiablo) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: thanks, changed

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php (hunk 6 above)
Comment (jaydiablo) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: thanks, reduced to just calling the normalizer

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php (hunk 7 above)
Comment (jaydiablo) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: removed

**Comment by jaydiablo** [comment]
Regarding the test failure, I'm not sure why that Redis test is failing now, perhaps something in the dependencies updated?

I removed my fix and ran just that test, fails with or without my fix in place, so don't believe it's a result of the change to this PR.

**Comment by jaydiablo** [comment]
Status: Needs Review

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 8]
```diff
@@ -703,7 +703,7 @@ private function updateData(array $data, string $attribute, mixed $attributeValu
     private function isMaxDepthReached(array $attributesMetadata, string $class, string $attribute, array &$context): bool
     {
         if (!($enableMaxDepth = $context[self::ENABLE_MAX_DEPTH] ?? $this->defaultContext[self::ENABLE_MAX_DEPTH] ?? false)
-            || null === $maxDepth = $attributesMetadata[$attribute]?->getMaxDepth()
+            || !isset($attributesMetadata[$attribute]) || null === $maxDepth = $attributesMetadata[$attribute]?->getMaxDepth()
```
Comment (dunglas) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php:710]: Could be:

```suggestion
            || null === $maxDepth = ($attributesMetadata[$attribute]?->getMaxDepth() ?? null)
```

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php [hunk 9]
```diff
@@ -1025,6 +1025,23 @@ protected function createChildContext(array $parentContext, string $attribute, ?
...
+    {
+        $object = new \stdClass();
+        $object->string = 'yes';
+
+        $classMetadataFactory = new ClassMetadataFactory(new AttributeLoader());
+        $normalizer = new ObjectNormalizer($classMetadataFactory);
+        $normalized = $normalizer->normalize($object, 'json', [
+            'json_encode_options' => 15, // JsonResponse::DEFAULT_ENCODING_OPTIONS
+            AbstractNormalizer::CIRCULAR_REFERENCE_HANDLER => static fn () => null,
+            AbstractObjectNormalizer::PRESERVE_EMPTY_OBJECTS => true,
```
Comment (dunglas) [inline src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: These options are unrelated to the issue and could be removed for the sake of simplicity, right?

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php (hunk 8 above)
Comment (jaydiablo) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php:710]: The warning is still thrown in that case as `$attributesMetadata[$attribute]` is still trying to be accessed.

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php (hunk 9 above)
Comment (jaydiablo) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: I'll test removing them and see if the warning is still thrown.

Comment (jaydiablo) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: I was able to remove those, thanks!

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php [hunk 10]
```diff
@@ -1026,6 +1026,20 @@ protected function createChildContext(array $parentContext, string $attribute, ?
...
     }
 
+    public function testNormalizationWithMaxDepthOnStdclassObjectDoesNotThrowWarning()
+    {
+        $object = new \stdClass();
+        $object->string = 'yes';
+
+        $classMetadataFactory = new ClassMetadataFactory(new AttributeLoader());
+        $normalizer = new ObjectNormalizer($classMetadataFactory);
+        $normalized = $normalizer->normalize($object, 'json', [
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]:
```suggestion
        $normalized = $normalizer->normalize($object, context: [
```

**Review by mtarld — APPROVED** [review]

**Comment by fabpot** [comment]
@jaydiablo  This PR must be rebased to get rid of the merge commits.

**Comment by jaydiablo** [comment]
@fabpot rebased

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php (hunk 10 above)
Comment (jaydiablo) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: thanks, updated.

**Comment by nicolas-grekas** [comment]
Thank you @jaydiablo.
