### PR TITLE
[Console] Fallback to default answers when unable to read input

### LINKED ISSUE #35988: Doctrine migrations immediately aborted in 5.0.5 and 4.4.5
**Symfony version(s) affected**: 5.0.5 and 4.4.5

**Description**  
Yesterday I updated some of my projects to the newest versions of Symfony. I noticed that both in Github Actions and Bitbucket Pipelines my CI/CD process failed (with no other code changes made). After downgrading back to 4.4.4 and 5.0.4 everything went fine.

**How to reproduce**  
Create Symfony project in the newest version in Bitbucket or Github with enabled CI/CD and mysql + sample migration. I've created sample repository with minimal code possible to show how it looks like.
 
Master branch (5.0.5): https://github.com/jacekpl/symfony-migrations-issue
Failed pipeline for master: https://github.com/jacekpl/symfony-migrations-issue/runs/490266168?check_suite_focus=true

Delevop branch (5.0.4): https://github.com/jacekpl/symfony-migrations-issue/tree/develop
Ok pipeline for develop: https://github.com/jacekpl/symfony-migrations-issue/runs/490130516?check_suite_focus=true

**Additional context**  
Expected bahaviour:
```
                    Application Migrations                    
                                                              

Migrating up to 20200306090544 from 0

  ++ migrating 20200306090544

     -> CREATE TABLE test (id INT AUTO_INCREMENT NOT NULL, message VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB

  ++ migrated (took 32.8ms, used 28M memory)

  ------------------------

  ++ finished in 34.5ms
  ++ used 28M memory
  ++ 1 migrations executed
  ++ 1 sql queries
```

Actual behaviour in 5.0.5:
```
                    Application Migrations                    
                                                              

WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)
            
  Aborted.  
```

### PR DESCRIPTION
**Pull request by ostrolucky**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36027, Fix #35988
| License       | MIT
| Doc PR        |

Alternative to https://github.com/symfony/symfony/pull/36027.

This fixes linked issues without having to revert fix for #30726. Successfully tested with composer script, `docker run` and `docker run -it`.

### CODE REVIEW

File: src/Symfony/Component/Console/Exception/MissingInputException.php [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+/*
+ * This file is part of the Symfony package.
+ *
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+declare(strict_types=1);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Exception/MissingInputException.php]: not in use in this repo

**Review by nicolas-grekas — APPROVED** [review]

**Comment by bendavies** [comment]
what about the fact that there is lots of code out there making decisions on `$input->isInteractive();` without using the question helper at all?

**Comment by ostrolucky** [comment]
Valid point. Can you link some?

**Comment by teohhanhui** [comment]
Same argument I made in https://github.com/symfony/symfony/pull/36027#issuecomment-598416428

**Comment by bendavies** [comment]
> Valid point. Can you link some?

There are quite a few.
https://github.com/symfony/symfony/search?q=isInteractive&type=

I was just greping my vendor folder and there will obviously be third party instances of this too.

**Comment by ostrolucky** [comment]
> There are quite a few.
symfony/symfony/search?q=isInteractive&type=

Thanks for the list. I checked it and none of those commands should break:
- password encoder: Interactive check is run only when not providing password via argument. Running command in non-interactive shell without providing password doesn't make sense in the first place, but even if you do, result is error, similarly as before.
- debug:container: it uses question helper as fallback
- messenger:failed:retry: Again fallback. It doesn't make sense to run this command in non-interactive shell without providing id
- debug:form : it uses question helper as fallback

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @ostrolucky.

**Comment by danepowell** [comment]
Just attaching a patch for folks wanting to test this via a composer patch to v4.4.5.
[symfony-console-36031.txt](https://github.com/symfony/symfony/files/4356765/symfony-console-36031.txt)

**Comment by ostrolucky** [comment]
No need, you may just suffix PR url with .patch https://github.com/symfony/symfony/pull/36031.patch

**Comment by danepowell** [comment]
I tried that but it doesn't apply cleanly due to conflicting changes in the 4.4.x branch.

**Comment by danepowell** [comment]
I've confirmed that this PR fixes the regression on my project, thanks.
