### PR TITLE
[Console] Don't register signal handlers if pcntl is disabled

### LINKED ISSUE #38496: [Console] "pcntl_signal_get_handler() has been disabled for security reasons" during installation
**Symfony version(s) affected**: 5.2-dev (0000dfe)

**Description**  
When running the Symfony CLI to install the 5.2 dev, I get this error:

```
Symfony operations: 3 recipes (41e56f6eef7707ea357a0a4dd6d9d3b8)
  - Configuring symfony/framework-bundle (>=5.2): From github.com/symfony/recipes:master
  - Configuring symfony/console (>=5.1): From github.com/symfony/recipes:master
  - Configuring symfony/routing (>=5.1): From github.com/symfony/recipes:master
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In SignalRegistry.php line 28:
!!
!!    Warning: pcntl_signal_get_handler() has been disabled for security reasons
!!
!!
!!
Script @auto-scripts was called via post-update-cmd

  unable to run /usr/local/bin/composer create-project symfony/skeleton /home/wouter/projects/local/symfony/sf-52 5.2.x@dev: exit status 1
```

I never explicitly disabled any functions, so it seems like it ships as default settings on some distributions (for reference, I'm using Debian with Sury's PHP repository). Googling online, it seems like the `pcntl_*()` functions are one of the functions that are more frequently disabled.

Even more, when commenting this line in my php.ini, it seems like Symfony CLI (4.19.2) explicitly disables these functions:
```
§ php -r "var_dump(ini_get('disable_functions'));"
Command line code:1:
string(0) ""

§ symfony php -r "var_dump(ini_get('disable_functions'));"
Command line code:1:
string(384) "pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,"
```

**How to reproduce**  

```
symfony new --version=next
```

**Possible Solution**  

* Should we add a friendlier error message if this function is disabled? (or maybe just skipping the new signal features if this function is disabled?)
* Or should we add this to the Symfony installation requirements (in the docs and in the requirement checker)?

**Additional context**  
-

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38496 
| License       | MIT
| Doc PR        | todo

This PR skips the default signal registration when pcntl is not installed or disabled via the `disable_functions` INI directive (which is common for prod infrastructures).
When registering a `SignalableCommand`, a clear exception is thrown. 

Best reviewed [without whitespaces](https://github.com/symfony/symfony/pull/38589/files?w=1)

### CODE REVIEW

**Review by lyrixx — APPROVED** [review]
I like it 👍🏼

File: src/Symfony/Component/Console/Application.php [hunk 1]
```diff
@@ -282,19 +284,25 @@ public function doRun(InputInterface $input, OutputInterface $output)
         }
 
         if ($this->dispatcher) {
-            foreach ($this->signalsToDispatchEvent as $signal) {
-                $event = new ConsoleSignalEvent($command, $input, $output, $signal);
+            if (!SignalRegistry::isSupported()) {
+                if ($this->dispatcher instanceof ComponentEventDispatcherInterface && $this->dispatcher->hasListeners(ConsoleEvents::SIGNAL)) {
```
Comment (jderusse) [inline src/Symfony/Component/Console/Application.php]: What'as about checking that `count($this->signalsToDispatchEvent) > 0` to let people use the application without pcntl. Even if something (like a 3rd party bundle) listen to `ConsoleEvents::SIGNAL`

File: src/Symfony/Component/Console/SignalRegistry/SignalRegistry.php [hunk 2]
```diff
@@ -49,4 +49,20 @@ public function handle(int $signal): void
             $signalHandler($signal, $hasNext);
         }
     }
+
+    /**
+     * @internal
```
Comment (derrabus) [inline src/Symfony/Component/Console/SignalRegistry/SignalRegistry.php]: Do we need to make this function internal? Checking if signal handling is generally available is probably something userland code might want to do as well.

File: src/Symfony/Component/Console/Application.php (hunk 1 above)
Comment (chalasr) [reply src/Symfony/Component/Console/Application.php]: 👍  Updated to just not set `signalsToDispatchEvent` if pcntl is not available

File: src/Symfony/Component/Console/SignalRegistry/SignalRegistry.php (hunk 2 above)
Comment (chalasr) [reply src/Symfony/Component/Console/SignalRegistry/SignalRegistry.php]: Works for me :) flag removed

**Review by jderusse — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @chalasr.

File: src/Symfony/Component/Console/Application.php [hunk 3]
```diff
@@ -88,8 +89,8 @@ public function __construct(string $name = 'UNKNOWN', string $version = 'UNKNOWN
         $this->version = $version;
         $this->terminal = new Terminal();
         $this->defaultCommand = 'list';
-        $this->signalRegistry = new SignalRegistry();
-        if (\defined('SIGINT')) {
+        if (\defined('SIGINT') && SignalRegistry::isSupported()) {
+            $this->signalRegistry = new SignalRegistry();
```
Comment (lyrixx) [inline src/Symfony/Component/Console/Application.php:93]: Sorry for the late review, but the PR has changed before my review.
So here we go:

This change is wrong. See `getSignalRegistry()` method:
https://github.com/chalasr/symfony/blob/8fe876341e860ea3fa13bec3c2bdf77a66ead424/src/Symfony/Component/Console/Application.php#L111-L114

Then, a lot of fatal error could occurs since the registry might not be defined

Comment (chalasr) [reply src/Symfony/Component/Console/Application.php:93]: Oops, thank you; #38602 makes it nullable
