### PR TITLE
[Serializer] Fix ObjectNormalizer default context with named serializers

### LINKED ISSUE #59639: Named serializer get default context from the default serializer
### Symfony version(s) affected

7.2.x

### Description

Hi! It looks like the default context is not used for some normalizers, instead the "default context" of the default serializer is used.

### How to reproduce

```yaml
    serializer:
        default_context:
            preserve_empty_objects: true

        named_serializers:
            my:
                default_context:
                    datetime_format: U
                    datetime_cast: int
                    yaml_indent: 1
```

The resulting container sets the `preserve_empty_objects` setting on the `my` version of the `serializer.normalizer.object` service. I'd expect it to use `datetime_format` etc. instead.

`var/cache/dev/App_KernelDevDebugContainer.xml`
```diff
+    <service id="serializer.normalizer.object.my" class="Symfony\Component\Serializer\Normalizer\ObjectNormalizer">
      <argument type="service" id="serializer.mapping.class_metadata_factory"/>
      <argument type="service" id="serializer.name_converter.metadata_aware"/>
      <argument type="service" id="property_accessor"/>
      <argument type="service" id="property_info" on-invalid="ignore"/>
      <argument type="service" id="serializer.mapping.class_discriminator_resolver" on-invalid="ignore"/>
      <argument>null</argument>
      <argument type="collection">
+        <argument key="preserve_empty_objects">true</argument>
      </argument>
      <argument type="service" id="property_info" on-invalid="ignore"/>
    </service>
```

### Possible Solution

_No response_

### Additional Context

`SerializerPass` seems to correctly set the binding in `bindDefaultContext`. But something must change/overwrite it later.
Image

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59639
| License       | MIT

As mentioned in #59639, the main problem is that arguments have precedence over bindings, and children inherit arguments from their parents.

This PR moves the logic for setting the default context of `ObjectNormalizer` from the extension to the `SerializerPass`, where only bindings are used.

### CODE REVIEW

File: src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php [hunk 1]
```diff
@@ -98,11 +108,24 @@ private function createNamedSerializerTags(ContainerBuilder $container, string $
...
 
-    private function bindDefaultContext(ContainerBuilder $container, array $services, array $defaultContext): void
+    private function bindDefaultContext(ContainerBuilder $container, array $services, array $defaultContext, ?string $circularReferenceHandler, ?string $maxDepthHandler): void
     {
         foreach ($services as $id) {
             $definition = $container->getDefinition((string) $id);
-            $definition->setBindings(['array $defaultContext' => new BoundArgument($defaultContext, false)] + $definition->getBindings());
+
+            $context = $defaultContext;
+            if (str_starts_with((string) $id, 'serializer.normalizer.object')) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php]: ?
```suggestion
            if (str_starts_with((string) $id, 'serializer.normalizer.object.')) {
```

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php (hunk 1 above)
Comment (HypeMC) [reply src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php]: It needs to work for the main service (`serializer.normalizer.object`) as well.

Comment (mtarld) [inline src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php]: Shouldn't we test instead the FQCN of the service?
I mean, here it sounds like we introduce a convention between the service ID and the class inheritance.

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.php [hunk 2]
```diff
@@ -129,8 +129,7 @@
                 service('property_info')->ignoreOnInvalid(),
                 service('serializer.mapping.class_discriminator_resolver')->ignoreOnInvalid(),
                 null,
-                null,
-                service('property_info')->ignoreOnInvalid(),
+                '$propertyInfoExtractor' => service('property_info')->ignoreOnInvalid(),
```
Comment (HypeMC) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.php]: Just realized, maybe using an abstract arg with a message mentioning the SerializerPass would've been a better option?

File: src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php (hunk 1 above)
Comment (HypeMC) [reply src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php]: The class for the child services is not set at this moment. What I could do is set it manually when the child services are registered.

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.php (hunk 2 above)
Comment (HypeMC) [reply src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.php]: Done, https://github.com/symfony/symfony/compare/6dde31530339c5f092abbe3997816db8bc49f966..80d993ff11bc20c800f5094d2d4dab8731f771b5

File: src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php (hunk 1 above)
Comment (HypeMC) [reply src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php]: Proposed changes: https://github.com/symfony/symfony/compare/6dde31530339c5f092abbe3997816db8bc49f966..80d993ff11bc20c800f5094d2d4dab8731f771b5

File: src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php [hunk 3]
```diff
@@ -98,11 +109,22 @@ private function createNamedSerializerTags(ContainerBuilder $container, string $
...
 
-    private function bindDefaultContext(ContainerBuilder $container, array $services, array $defaultContext): void
+    private function bindDefaultContext(ContainerBuilder $container, array $services, array $defaultContext, ?string $circularReferenceHandler, ?string $maxDepthHandler): void
     {
         foreach ($services as $id) {
             $definition = $container->getDefinition((string) $id);
-            $definition->setBindings(['array $defaultContext' => new BoundArgument($defaultContext, false)] + $definition->getBindings());
+
+            $context = $defaultContext;
+            if (is_a($definition->getClass(), ObjectNormalizer::class, true)) {
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php:118]:
```suggestion
            if (is_a($definition->getClass(), AbstractObjectNormalizer::class, true)) {
```
maybe?

Comment (HypeMC) [reply src/Symfony/Component/Serializer/DependencyInjection/SerializerPass.php:118]: Currently `circular_reference_handler` & `max_depth_handler` are only added to the `ObjectNormalizer`, I don't think changing this behavior qualifies as a bug fix.

**Review by fabpot — APPROVED** [review]

**Review by mtarld — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @HypeMC.
