### PR TITLE
[SecurityBundle] configuration for the storage service for the login throttling rate limiter

### LINKED ISSUE #60744: [Security] Impossible to configure the storage service for login_throttling
### Symfony version(s) affected

7.3

### Description

The configuration of login_throttling do not allow to configure `storage_service`:

https://github.com/symfony/symfony/blob/cd87bdea0633e0a1fa82c07e2fc36ac280cd632a/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/LoginThrottlingFactory.php#L66-L71

Besides it's supposed to be supported:

https://github.com/symfony/symfony/blob/cd87bdea0633e0a1fa82c07e2fc36ac280cd632a/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/LoginThrottlingFactory.php#L108

### How to reproduce

Configure a `login_throttling`: it's impossible to specify the storage service

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #60744
| License       | MIT

### CODE REVIEW

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/LoginThrottlingFactory.php [hunk 1]
```diff
@@ -55,6 +55,8 @@ public function addConfiguration(NodeDefinition $builder): void
                 ->integerNode('max_attempts')->defaultValue(5)->end()
                 ->scalarNode('interval')->defaultValue('1 minute')->end()
                 ->scalarNode('lock_factory')->info('The service ID of the lock factory used by the login rate limiter (or null to disable locking).')->defaultNull()->end()
+                ->scalarNode('cache_pool')->info('The cache pool to use for storing the limiter state')->defaultValue('cache.rate_limiter')->end()
+                ->scalarNode('storage_service')->info('The service ID of a custom storage implementation, this precedes any configured "cache_pool"')->defaultNull()->end()
```
Comment (alexandre-daubois) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/LoginThrottlingFactory.php:59]: Should we use the recently added `stringNode()` instead?

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/LoginThrottlingFactory.php (hunk 1 above)
Comment (xabbuh) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/LoginThrottlingFactory.php:59]: added in #61502
