### PR TITLE
[DoctrineBridge] Fix automapping

### LINKED ISSUE #44355: [symfony/doctrine-bridge] 5.4 : auto mapping not working at all
### Symfony version(s) affected

5.4

### Description

Auto mapping of vendor entity not working anymore.

### How to reproduce

My doctrine config :
```yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```

With symfony/doctrine-bridge 5.3.11, Entity living on directory `vendor/foolib/foobundle/src/Entity` was registered.
With symfony/doctrine-bridge 5.4.0, Entity got error : 
`The class 'Foo\FooBundle\Entity\BarEntity' was not found in the chain configured namespaces App\Entity`

### Possible Solution

_No response_

### Additional Context

I am not sure bug is from `symfony/doctrine-bridge`, but add `"symfony/doctrine-bridge": "5.3.*",` on composer.json solve the problem

### PR DESCRIPTION
**Pull request by mbabker**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44355
| License       | MIT
| Doc PR        | N/A

This should fix the broken automapping configuration for bundles that use annotations and attributes, see #44355 for additional details.

When using the newer bundle directory structure conventions, especially with the `Bundle::getPath()` method overridden to point the bundle root path to the Bundle class' parent directory, the issue comes up because the bundle filesystem root path does not match the root path for the actual bundle code (effectively the PSR-4 root path).

To fix automapping, the `AbstractDoctrineExtension::detectMetadataDriver()` method will be called a second time with the Bundle classpath if the first call (which is effectively the same as `Bundle::getPath()`)  can't resolve the appropriate mapping type.  This will also update setting `$bundleConfig['dir']` for drivers that are based on PHP classes so that the root path is based on the bundle classpath (AKA the PSR-4 root path) instead of the bundle path.

The bulk of this patch is mainly from adding test fixture bundles to be able to test the `AbstractDoctrineExtension::getMappingDriverBundleConfigDefaults()` method in this repo and ensuring that the metadata driver detection works right for all of the supported drivers.

### CODE REVIEW

**Comment by SimonVanacco** [comment]
This fixes the issue in my codebase !

File: src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php [hunk 1]
```diff
@@ -148,10 +148,15 @@ protected function getMappingDriverBundleConfigDefaults(array $bundleConfig, \Re
...
         }
 
-        $bundleDir ?? $bundleDir = \dirname($bundle->getFileName());
+        $bundleClassDir = \dirname($bundle->getFileName());
+        $bundleDir ?? $bundleDir = $bundleClassDir;
 
         if (!$bundleConfig['type']) {
             $bundleConfig['type'] = $this->detectMetadataDriver($bundleDir, $container);
+
+            if (!$bundleConfig['type'] && $bundleDir !== $bundleClassDir) {
```
Comment (tperunsky) [inline src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php:157]: Isn't `!$bundleConfig['type']` in this condition redundant? It's already checked in line 154.

Comment (mbabker) [reply src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php:157]: Nope, that’s the fix here.  The call to try and give it a value in line 155 might kick back null, so we only want to make a second call to `detectMetadataDriver()` if the first one doesn’t give a result and the paths are different.

Comment (tperunsky) [reply src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php:157]: ah of course :) I misread the code

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @mbabker.
