### PR TITLE
[DependencyInjection] Fix handling of repeated `#[Autoconfigure]` attributes

### LINKED ISSUE #56841: [DependencyInjection] Multiple `Autoconfigure` attributes are accepted, but the default values of the last one are applied
### Symfony version(s) affected

5.4 - 7.1.0-rc1

### Description

When the attribute `Autoconfigure` is used multiple times on the same class, only the last instance is used, other seems to be ignored.

### How to reproduce

```php
use Symfony\Component\DependencyInjection\Attribute\Autoconfigure;

#[Autoconfigure(lazy: true)]
#[Autoconfigure(shared: false)]
interface MyInterface {}
```

```php
class MyClass implements MyInterface {}
```

```console
$ bin/console debug:container MyClass

Information for Service "App\MyClass"
=====================================

 ---------------- ----------------- 
  Option           Value            
 ---------------- ----------------- 
  Service ID       App\MyClass      
  Class            App\MyClass      
  Tags             -  
  Public           no               
  Synthetic        no               
  Lazy             no               <- Default value from the 2nd attribute, ignoring the value set in the 1st attribute
  Shared           no               <- Value set in the 2nd attribute
  Abstract         no               
  Autowired        yes              
  Autoconfigured   yes              
  Usages           App\MyInterface  
 ---------------- ----------------- 
```

If the order of the attribute is modified:

```php
use Symfony\Component\DependencyInjection\Attribute\Autoconfigure;

#[Autoconfigure(shared: false)]
#[Autoconfigure(lazy: true)]
interface MyInterface {}
```

```console
❯ bin/console debug:container MyClass

Information for Service "App\MyClass"
=====================================

 ---------------- ----------------- 
  Option           Value            
 ---------------- ----------------- 
  Service ID       App\MyClass      
  Class            App\MyClass      
  Tags             -                
  Public           no               
  Synthetic        no               
  Lazy             yes              <- Value set in the 2nd attribute
  Shared           yes              <- Default value from the 2nd attribute, ignoring the value set in the 1st attribute
  Abstract         no               
  Autowired        yes              
  Autoconfigured   yes              
  Usages           App\MyInterface  
 ---------------- ----------------- 
```

### Possible Solution

Remove `null` values when the attribute is loaded:
https://github.com/symfony/symfony/blob/b8b3c399128ba137096e13442bdb30abaac1abbc/src/Symfony/Component/DependencyInjection/Compiler/RegisterAutoconfigureAttributesPass.php#L86

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #56841
| License       | MIT

When repeating `#[Autoconfigure]`, arguments from all attributes are now used. If an option is defined multiple times in repeated attributes, the last attribute defined will sets value.

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Compiler/RegisterAutoconfigureAttributesPass.php [hunk 1]
```diff
@@ -49,36 +49,41 @@ public function accept(Definition $definition): bool
...
+        $combinedAttributesArgs = null;
         foreach ($class->getAttributes(Autoconfigure::class, \ReflectionAttribute::IS_INSTANCEOF) as $attribute) {
-            self::registerForAutoconfiguration($container, $class, $attribute);
+            $args = array_filter((array) $attribute->newInstance(), static function ($v): bool { return null !== $v; });
+
+            foreach ($args['tags'] ?? [] as $i => $tag) {
+                if (\is_array($tag) && [0] === array_keys($tag)) {
+                    $args['tags'][$i] = [$class->name => $tag[0]];
+                }
+            }
```
Comment (GromNaN) [inline src/Symfony/Component/DependencyInjection/Compiler/RegisterAutoconfigureAttributesPass.php]: Note that with your PR, only the last tag is configured, whereas all the tags were previously added for this attribute:

```php
#[AutoconfigureTag('foo', ['priority' => 2])]
#[AutoconfigureTag('bar')]
```

**Review by GromNaN — COMMENTED** [review]
I think there is a regression for tags, before they were all added and now only the last are configured.

File: src/Symfony/Component/DependencyInjection/Compiler/RegisterAutoconfigureAttributesPass.php (hunk 1 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/DependencyInjection/Compiler/RegisterAutoconfigureAttributesPass.php]: Thank you for spotting the issue! I'll have a look and add a test for this

Comment (alexandre-daubois) [reply src/Symfony/Component/DependencyInjection/Compiler/RegisterAutoconfigureAttributesPass.php]: Alright, better now. I deliberately chose to only support merging tags and calls, because these are the only things in the `ChildDefinition` that have adder methods (`addTag()` and `addMethodCall()`). Other properties, like bindings, does not have an adder, but only `setBindings()`.

But I'm open to discussion on this point, and it would make sense to also merge bindings and properties?

Comment (GromNaN) [reply src/Symfony/Component/DependencyInjection/Compiler/RegisterAutoconfigureAttributesPass.php]: Seems correct. That matches the current behavior. We could add tests on these properties too.

**Review by GromNaN — APPROVED** [review]
SGTM

**Review by nicolas-grekas — APPROVED** [review]
The fix was much simpler ;)
I pushed it and kept your test cases.

**Comment by nicolas-grekas** [comment]
Thank you @alexandre-daubois.

**Comment by alexandre-daubois** [comment]
> I pushed it and kept your test cases.

I'll have a look at your solution. Thank you for taking care of this!
