### PR TITLE
[VarExporter] Fix serialization of objects with __serialize/__unserialize

### LINKED ISSUE #63699: [Cache][VarExporter] Invalid serialization data for DateTimeImmutable object
### Symfony version(s) affected

8.1-dev

### Description

In my application, we store cache items with a date like this:

```php
final readonly class MyCacheItem
{
    public function __construct(
        public MyRecord $record,
        public \DateTimeImmutable $storedAt,
    ) {
    }
}
```

Throwing an instance of this class into a cache and unserializing it afterwards works fine on Symfony 8.0. On the 8.1-dev branch however, fetching the items crashes with the error message, "Invalid serialization data for DateTimeImmutable object".

### How to reproduce

```php
namespace App;

use Symfony\Component\Cache\Adapter\ArrayAdapter;

require __DIR__.'/vendor/autoload.php';

final readonly class MyCacheItem
{
    public function __construct(
        public MyRecord $record,
        public \DateTimeImmutable $storedAt,
    ) {
    }
}

final readonly class MyRecord
{
    public function __construct(
        public string $myField,
    ) {
    }
}

$cache = new ArrayAdapter();
$item = $cache->getItem('foo');
$item->set(new MyCacheItem(
    new MyRecord('a'),
    new \DateTimeImmutable('2013-01-26T12:34:56+01:00'),
));
$cache->save($item);

dump($cache->getItem('foo')->get());
```

#### Output with Symfony 8.0:

```
App\MyCacheItem {#9
  +record: App\MyRecord {#10
    +myField: "a"
  }
  +storedAt: DateTimeImmutable @1359200096 {#11
    date: 2013-01-26 12:34:56.0 +01:00
  }
}
```

#### Output with Symfony 8.1:

```
PHP Warning:  foreach() argument must be of type array|object, string given in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 116

Warning: foreach() argument must be of type array|object, string given in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 116
PHP Warning:  foreach() argument must be of type array|object, int given in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 116

Warning: foreach() argument must be of type array|object, int given in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 116
PHP Warning:  foreach() argument must be of type array|object, string given in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 116

Warning: foreach() argument must be of type array|object, string given in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 116
PHP Deprecated:  Method DateTimeImmutable::__wakeup() is deprecated since 8.5, this method is obsolete, as serialization hooks are provided by __unserialize() and __serialize() in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 387

Deprecated: Method DateTimeImmutable::__wakeup() is deprecated since 8.5, this method is obsolete, as serialization hooks are provided by __unserialize() and __serialize() in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 387
PHP Fatal error:  Uncaught Error: Invalid serialization data for DateTimeImmutable object in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php:387
Stack trace:
#0 /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php(387): DateTimeImmutable->__wakeup()
#1 /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php(173): Symfony\Component\VarExporter\DeepCloner::reconstruct(0, Array, Array, Array, Array, Array, Array)
#2 /path/to/symfony/src/Symfony/Component/Cache/Adapter/ArrayAdapter.php(367): Symfony\Component\VarExporter\DeepCloner->clone()
#3 /path/to/symfony/src/Symfony/Component/Cache/Adapter/ArrayAdapter.php(131): Symfony\Component\Cache\Adapter\ArrayAdapter->unfreeze('foo', true)
#4 /path/to/symfony/test.php(36): Symfony\Component\Cache\Adapter\ArrayAdapter->getItem('foo')
#5 {main}
  thrown in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 387

Fatal error: Uncaught Error: Invalid serialization data for DateTimeImmutable object in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php:387
Stack trace:
#0 /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php(387): DateTimeImmutable->__wakeup()
#1 /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php(173): Symfony\Component\VarExporter\DeepCloner::reconstruct(0, Array, Array, Array, Array, Array, Array)
#2 /path/to/symfony/src/Symfony/Component/Cache/Adapter/ArrayAdapter.php(367): Symfony\Component\VarExporter\DeepCloner->clone()
#3 /path/to/symfony/src/Symfony/Component/Cache/Adapter/ArrayAdapter.php(131): Symfony\Component\Cache\Adapter\ArrayAdapter->unfreeze('foo', true)
#4 /path/to/symfony/test.php(36): Symfony\Component\Cache\Adapter\ArrayAdapter->getItem('foo')
#5 {main}
  thrown in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 387
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Amoifr**
| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63699
| License       | MIT

## Summary

When processing multiple objects in the same loop iteration of `Exporter::prepare()`, the `$hasUnserialize` variable was not reset between iterations. This caused objects with `__serialize`/`__unserialize` (like `DateTimeImmutable`) to incorrectly use `__wakeup()` when they appeared after objects without these methods in the properties list.

## The Problem

When storing an object containing both:
1. A simple object without `__serialize`/`__unserialize` (e.g., a simple DTO)
2. A `DateTimeImmutable` (which has `__serialize`/`__unserialize`)

The `DateTimeImmutable` was incorrectly flagged to use `__wakeup()` instead of `__unserialize()`, causing:
- `foreach()` warnings on non-array values
- Fatal error: "Invalid serialization data for DateTimeImmutable object"

## The Fix

Added `unset($hasUnserialize)` at the start of each object's processing to ensure the variable is properly reset for each iteration.

### CODE REVIEW

**Review by derrabus — APPROVED** [review]
Scary `goto` stuff is scary. 🙈 

Thank you for the fix.

File: src/Symfony/Component/VarExporter/Internal/Exporter.php [hunk 1]
```diff
@@ -44,7 +44,7 @@ public static function prepare($values, $objectsPool, &$refsPool, &$objectsCount
         $refs = $values;
         foreach ($values as $k => $value) {
             if (\is_resource($value)) {
-                throw new NotInstantiableTypeException(get_resource_type($value).' resource');
+                throw new NotInstantiableTypeException(get_resource_type($value).' resource.');
```
Comment (stof) [inline src/Symfony/Component/VarExporter/Internal/Exporter.php]: should be reverted. This is a fabbot false positive due to the fact that this NotInstantiableTypeException constructor does not take a full message as its argument.

Comment (Amoifr) [reply src/Symfony/Component/VarExporter/Internal/Exporter.php]: It"s done. Sorry.

**Comment by nicolas-grekas** [comment]
Thank you @Amoifr.
