### PR TITLE
[Messenger] Fix merging PrototypedArrayNode associative values

### LINKED ISSUE #36874: [Messenger] Wrong transport options in container dump
**Symfony version(s) affected**: 5.0.8, up to 5.2.3

**Description**  
While trying to implement a Messenger transport, I'm having an issue with the local container dump, because I'm getting a mangled array of options, with strange values.

**How to reproduce**  
The reproducer is this commit: https://github.com/Jean85/symfony-config-bug-repro/commit/6bcb2dc1c675c88c5a4fa758faabc7bc0120ed42

To reproduce:
 * Clone https://github.com/Jean85/symfony-config-bug-repro
 * `composer install`
 * `bin/console messenger:consume --env=test`

It will die with a dump of the received options, which are:
```php
[
  "queues" => [
    "q-receiver" => null
  ]
  0 => "something"
  "transport_name" => "receiver"
]
```
Instead of the expected:
```php
[
  "queue_name" => "something"
  "transport_name" => "receiver"
]
```

I'm not sure if this is a bug localized to the Messenger and how it's configuration is handled in the FrameworkBundle, or it's somewhere else.

### LINKED ISSUE #39846: [Messenger] Messenger transport options are merged with numbers as keys
**Symfony version(s) affected: 4.4**

**Description**
Messenger config `options` array merged wrong. Values inside specific environment config of `options` array are merged to common config with numbers as keys.

**How to reproduce**

1. Create `messenger.yaml` in `config/packages/` with following contents:

```yaml
framework:
    messenger:
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"
            options:
                auto_setup: false
```

2. Then, create another, for example, for the test environment `config/packages/test/` and add options there:
```yaml
framework:
    messenger:
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"
            options:
                wait_time: 60
```

3. Run console debug:config:
```bash
console debug:config framework
```

```bash
#...
messenger:
    transports:
        async:
            dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            options:
                auto_setup: true
#...
```

4. Run console debug:config for test-environment:
```bash
APP_ENV=test console debug:config framework
```
Output for test-environment:
```bash
#...
messenger:
    transports:
        async:
            dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            options:
                auto_setup: true
                0: 60
#...
```

**Additional context**

That's happened because in ConfigTree options are defined as `arrayNode` and has a `prototype('variable')`. So for combining config together `PrototypedArrayNode::mergeValues()` would be called. And there is an issue. For those `PrototypedArrayNode` that have not `$keyAttribute` `$rightSide` values added without keys:
```php
foreach ($rightSide as $k => $v) {
    // prototype, and key is irrelevant, append the element
    if (null === $this->keyAttribute) {
        $leftSide[] = $v;
        continue;
    }
```

**Possible soultion**
So the solution is to add `useAttributeAsKey` inside ConfigTree for arrayNode('options'). PR will be submitted soon

### PR DESCRIPTION
**Pull request by svitiashchuk**
Now keys will not be considered as irrelevant.

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39846, fix #36874
| License       | MIT
| Doc PR        | 

The problem was because in ConfigTree `options` are defined as `arrayNode` and has a `prototype('variable')`. So for combining config together `PrototypedArrayNode::mergeValues()` was called. And there was a trouble - for that `PrototypedArrayNode` `$rightSide` values were added without keys:

`\Symfony\Component\Config\Definition\PrototypedArrayNode::mergeValues`
```php
foreach ($rightSide as $k => $v) {
    // prototype, and key is irrelevant, append the element
    if (null === $this->keyAttribute) {
        $leftSide[] = $v;
        continue;
    }
```

### CODE REVIEW

**Review by jderusse — COMMENTED** [review]
could you please add a test?

see https://github.com/symfony/symfony/pull/39686/files for similar PR

**Comment by svitiashchuk** [comment]
Test added

**Comment by jderusse** [comment]
looks like the failed tests is related to your change

**Comment by svitiashchuk** [comment]
Yes, it was. Now, I've changed the argument `$name` value of method `ArrayNodeDefinition::useAttributeAsKey` to `'option'`. Because in fixture config `messenger_transports.php` there was a piece:
```
'options' => ['queue' => ['name' => 'Queue']],
```
for which `'name' => 'Queue'` was considered as key for option, and therefore, rewritten the original key `'queue'` with `'Queue'`. Now that problem solved.



P.S. I'm not sure about that, but is that a normal behaviour that original key replaced when `attributeAsKey` is set and original key is present in config simultaneously. Should I create another one issue?

**Comment by jderusse** [comment]
Indeed, the attributeAsKey should not be an expected subkey of the array.

**Review by jderusse — APPROVED** [review]

**Review by jderusse — APPROVED** [review]

**Review by jderusse — APPROVED** [review]

File: src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/ConfigurationTest.php [hunk 1]
```diff
@@ -278,6 +278,45 @@ public function testLockMergeConfigs()
...
+                            'options' => [
+                                'wait_time' => 20,
+                            ],
+                        ],
+                    ],
+                ],
+            ],
+        ]);
+
+        $this->assertEquals(
```
Comment (OskarStark) [inline src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/ConfigurationTest.php]:
```suggestion
        $this->assertSame(
```
?

**Comment by OskarStark** [comment]
CleanShot 2021-01-15 at 15 49 24

It looks like your committer email is not associated with your Github account 🤔

**Comment by svitiashchuk** [comment]
@OskarStark yes, thanks for pointing. Did it in different environment, but now fixed it.

**Review by xabbuh — CHANGES_REQUESTED** [review]
I am not convinced that this will always work. What if there is a queue where one option is named `option`?

**Review by svitiashchuk — COMMENTED** [review]
@xabbuh I've added an `option` key inside test config options array to prove that this will work.

**Comment by xabbuh** [comment]
@svityashchuk If you change your example to something like this, you will experience the same behavior:

```php
'options' => [
    'auto_setup' => true,
    'queue' => [
        'name' => 'Queue',
        'option' => 'foo',
    ],
],
```

**Comment by svitiashchuk** [comment]
@xabbuh thank you for providing an example. I've got that behaviour. So, in the circumstances I see the only possibility to use another keyword as keyAttribute. Otherwise, I won't be able to pass this check at `\Symfony\Component\Config\Definition\PrototypedArrayNode::mergeValues`:

```php
foreach ($rightSide as $k => $v) {
    // prototype, and key is irrelevant, append the element
    if (null === $this->keyAttribute) {
        $leftSide[] = $v;
        continue;
    }
```

Moreover, now it seems for me like this condition `null === $this->keyAttribute` is not enough to decide to append value as plain array item (I mean, not an associative array element). Therefore, I think we need to add an additional condition, like it is done in `\Symfony\Component\Config\Definition\PrototypedArrayNode::normalizeValue`. There we can see the next lines:
```php
protected function normalizeValue($value)
{
//...
$isAssoc = array_keys($value) !== range(0, \count($value) - 1);
//...
foreach ($value as $k => $v) {
    //...
    if (null !== $this->keyAttribute || $isAssoc) {
        $normalized[$k] = $prototype->normalize($v);
    } else {
        $normalized[] = $prototype->normalize($v);
    }
```

Pay attention that `$isAssoc` variable affects the way normalized value is added to resulting `$normalized` array.
If you wouldn't mind, I will provide corresponding changes.

**Comment by xabbuh** [comment]
This sounds like a solution that could work. Let's give that a try. For `5.x` I have pending changes locally that allow to configure list and map nodes explicitly which would allow an easier solution. But that's of course not something we can use here for the bugfix.

**Comment by svitiashchuk** [comment]
Now it seems like everything is ok :)
Thanks to my colleague I realized that I had written test in different bundle. Therefore, on Travis CI check it was impossible to test changes that I had provided. So I've removed that test and wrote another one in relevant directory.

I would be very happy if this is merged.
@xabbuh could you please take a look at it?

File: src/Symfony/Component/Config/Definition/PrototypedArrayNode.php [hunk 2]
```diff
@@ -304,9 +304,10 @@ protected function mergeValues($leftSide, $rightSide)
             return $rightSide;
         }
 
+        $isAssoc = array_keys($rightSide) !== range(0, \count($rightSide) - 1);
```
Comment (jderusse) [inline src/Symfony/Component/Config/Definition/PrototypedArrayNode.php]: What's about using `array_is_list` and requiring the `php81` polyfill?

Comment (svitiashchuk) [reply src/Symfony/Component/Config/Definition/PrototypedArrayNode.php]: Updated PR with this polyfill.

File: src/Symfony/Component/Config/Definition/PrototypedArrayNode.php [hunk 3]
```diff
@@ -225,7 +225,7 @@ protected function normalizeValue($value)
 
         $value = $this->remapXml($value);
 
-        $isAssoc = array_keys($value) !== range(0, \count($value) - 1);
+        $isAssoc = !array_is_list($value);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Config/Definition/PrototypedArrayNode.php]: maybe `$isList = array_is_list($value);` to prevent the double negation? (same in the other method)

**Review by nicolas-grekas — COMMENTED** [review]
Please update the PR title - it's not about Messenger :)

**Comment by Sscorpion9991** [comment]
Hi! Is this PR going to be merged? I have the same issue.

**Review by nicolas-grekas — APPROVED** [review]

**Review by maxhelias — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you @svityashchuk.
