### PR TITLE
[Lock] Fixed reading locks from replica set secondary nodes

### LINKED ISSUE #37139: [Lock] MongoDbStore reports a failure to release
**Symfony version(s) affected**: 5.1.0

**Description**  
When using `MongoDbStore` against a `replicaSet` with a connection `readPreference` other than `primary` (the default), the store falsely reports locks don't release. This is because `Symfony\Component\Lock\Lock::release()` deletes the key then immediately reads from the store in order to check if the lock was successfully released. The key eviction may not have propagated the replica set at this time and return false.

**How to reproduce**  
Set up a mongo replicaSet and connect to it from your application with: `readPreference=secondary` in your Mongo connection URI. Then try to acquire and release a lock. You should get a: `Symfony\Component\Lock\Exception\LockReleasingException`

**Possible Solution**  
We should always use `readPreference=primary` for all semephore queries (there's only 1: `MongoDbStore::exists`).

**Additional context**  
https://docs.mongodb.com/manual/core/read-preference/

### PR DESCRIPTION
**Pull request by kralos**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37139 
| License       | MIT
| Doc PR        | https://github.com/symfony/symfony-docs/pull/13775

Force lock existence query to use `readPreference=primary` in case the given mongo connection is using any of the following `readPreference`s:

* primaryPreferred
* secondary
* secondaryPreferred
* nearest

Any of the above would fail if a secondary node is queried during a lock release.

### CODE REVIEW

**Comment by kralos** [comment]
In order to add a CI test for this we would need a replicaSet in CI. Not sure this is worth doing?

**Review by nicolas-grekas — APPROVED** [review]
> In order to add a CI test for this we would need a replicaSet in CI. Not sure this is worth doing?

Unless there is a docker image that would allow doing that easily by using GitHub Actions, I agree.

**Comment by kralos** [comment]
I can't find anything that appears maintained. There's https://github.com/marketplace/actions/mongodb-in-github-actions#with-a-replica-set however their replica set is single instance (there is no secondary so we therefore can't test against it). I don't really want to create and maintain our own github action for this but might make sense in the future if we want to also test `Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler` which i suspect has the same issue. I will be testing this in more depth over the coming months

File: src/Symfony/Component/Lock/Store/MongoDbStore.php [hunk 1]
```diff
@@ -315,23 +317,15 @@ private function isDuplicateKeyException(WriteException $e): bool
...
-        $command = new Command([
-            'buildinfo' => 1,
-        ]);
-        $cursor = $this->getCollection()->getManager()->executeReadCommand(
-            $this->getCollection()->getDatabaseName(),
-            $command
-        );
-        $buildInfo = $cursor->toArray()[0];
-        $this->databaseVersion = $buildInfo->version;
+        $this->readPreference = new ReadPreference(ReadPreference::RP_PRIMARY);
```
Comment (jmikola) [inline src/Symfony/Component/Lock/Store/MongoDbStore.php:326]: Note: `ReadPreference` can be [constructed with a string](https://www.php.net/manual/en/mongodb-driver-readpreference.construct.php) since driver version [1.3.0](https://github.com/mongodb/mongo-php-driver/releases/tag/1.3.0) (September 2017). I didn't find any reference to the `mongodb` extension or PHP library in `composer.json` so perhaps there's no minimum requirement and that's the reason for preferring the deprecated numeric constants (we hope to remove these in 2.0, per [PHPC-1021](https://jira.mongodb.org/browse/PHPC-1021)).

File: src/Symfony/Component/Lock/Store/MongoDbStore.php [hunk 2]
```diff
@@ -315,23 +317,15 @@ private function isDuplicateKeyException(WriteException $e): bool
         return 11000 === $code;
     }
 
-    private function getDatabaseVersion(): string
+    private function getReadPreference(): ReadPreference
```
Comment (jmikola) [inline src/Symfony/Component/Lock/Store/MongoDbStore.php:320]: This appears to be called exactly once in `exists()`. ReadPreference is a very light value object, so I'd propose just removing this method (and cached class property) in favor of constructing it inline.

**Review by jmikola — COMMENTED** [review]
Just sharing a few comments after I was pinged in https://github.com/symfony/symfony/issues/37139. Feel free to take or leave my suggestions as you wish.

**Comment by jmikola** [comment]
Side note: while looking at https://github.com/symfony/symfony/blob/6d6d989dbe96ef95fb7e5da34d7c1001e161d4c9/src/Symfony/Component/Lock/Tests/Store/MongoDbStoreTest.php#L119, I noticed that the tests pass a custom `collection` option in the MongoDB connection string. Likewise, this adapter parses a default `database` name from the authentication database. I realize this likely needs to remain in 5.x for BC at this point, but I'd argue against having this behavior for two reasons:

 * The extension uses the connection string to cache internal libmongoc client objects (for socket persistence), so overloading the string to hold extra options not used by the driver will defeat any chance of being able to efficiently re-use existing sockets.
 * The database name in the connection string is documented as the [`defaultAuthDb`](https://www.php.net/manual/en/mongodb-driver-manager.construct.php) and fallback for the `authSource` URI option. Suggestion folks use it to denote a default database could lead to it inadvertently being used for authentication (over the default "admin" database) if credentials were also provided.

IMO, both `collection` and `database` should be solicited as explicit options to the storage class and not pulled from the connection string, `uriOptions`, or `driverOptions`.

File: src/Symfony/Component/Lock/Store/MongoDbStore.php (hunk 1 above)
Comment (kralos) [reply src/Symfony/Component/Lock/Store/MongoDbStore.php]: symfony doesn't require `ext-mongodb`, the closest it comes is `"require-dev": { "mongodb/mongodb": "~1.1" }`

since `"mongodb/mongodb": "1.1.0"` requires `ext-mongodb: ^1.2.0` i think we should probably support pre `ext-mongodb: 1.3.0` (needs to support ints).

I've added detection for string const vs int const to allow both forwards and backwards compatibility with the shift from `int` to `string` constructed `ReadPreference`

I'm assuming in https://jira.mongodb.org/browse/PHPC-1021 you're planning to just remove `ReadPreference::RP_PRIMARY` and `ReadPreference::PRIMARY` will remain in `ext-mongodb: 2.0`?

File: src/Symfony/Component/Lock/Store/MongoDbStore.php (hunk 2 above)
Comment (kralos) [reply src/Symfony/Component/Lock/Store/MongoDbStore.php]: removed

**Comment by kralos** [comment]
> Side note: while looking at
> 
> https://github.com/symfony/symfony/blob/6d6d989dbe96ef95fb7e5da34d7c1001e161d4c9/src/Symfony/Component/Lock/Tests/Store/MongoDbStoreTest.php#L119
> , I noticed that the tests pass a custom `collection` option in the MongoDB connection string. Likewise, this adapter parses a default `database` name from the authentication database. I realize this likely needs to remain in 5.x for BC at this point, but I'd argue against having this behavior for two reasons:
> 
>     * The extension uses the connection string to cache internal libmongoc client objects (for socket persistence), so overloading the string to hold extra options not used by the driver will defeat any chance of being able to efficiently re-use existing sockets.
> 
>     * The database name in the connection string is documented as the [`defaultAuthDb`](https://www.php.net/manual/en/mongodb-driver-manager.construct.php) and fallback for the `authSource` URI option. Suggestion folks use it to denote a default database could lead to it inadvertently being used for authentication (over the default "admin" database) if credentials were also provided.
> 
> 
> IMO, both `collection` and `database` should be solicited as explicit options to the storage class and not pulled from the connection string, `uriOptions`, or `driverOptions`.

#### regarding the use of `collection` in the connection URI

I absolutely agree we should not introduce non-standard querystring params. The reason this was added at the time was to allow `Symfony\Component\Lock\Store\StoreFactory` to construct a `MongoDbStore` from a uri alone. I think we should deprecate `collection` from the uri in `MongoDbStore` as well as uri construction via `StoreFactory`. Since `StoreFactory` doesn't support `$options` the only way to construct a `MongoDbStore` would be to pass it a `\MongoDB\Collection`.

#### regarding the use of `database` in the connection URI's path

I did a fair bit of testing with mongo cli client before implementing the current behavior. As far as i can tell I have mirrored what mongo cli does:

* `mongodb://user:pass@server/db1` means defaultDb = db1 and authDb = db1
* `mongodb://user:pass@server/db1?authSource=db2` means defaultDb = db1 and authDb = db2

File: src/Symfony/Component/Lock/Store/MongoDbStore.php (hunk 1 above)
Comment (jmikola) [reply src/Symfony/Component/Lock/Store/MongoDbStore.php]: > symfony doesn't require ext-mongodb, the closest it comes is "require-dev": { "mongodb/mongodb": "~1.1" }

Where is this? I didn't find any reference to `mongodb` in https://github.com/symfony/symfony/blob/5.1/composer.json

> I'm assuming in https://jira.mongodb.org/browse/PHPC-1021 you're planning to just remove ReadPreference::RP_PRIMARY and ReadPreference::PRIMARY will remain in ext-mongodb: 2.0?

Correct. The new constants would stay. The old, integer constants happen to be tied to internal libmongoc constants, which is why we want to remove them (and why the values seemingly make no sense, since they're bitmasks IIRC).

In any event, I think the ternary you have in the current diff is future-proof. :+1:

Comment (kralos) [reply src/Symfony/Component/Lock/Store/MongoDbStore.php]: > Where is this? I didn't find any reference to mongodb in https://github.com/symfony/symfony/blob/5.1/composer.json

in the `Component\Lock` - `src/Symfony/Component/Lock/composer.json`

**Comment by jmikola** [comment]
> regarding the use of database in the connection URI's path
> I did a fair bit of testing with mongo cli client before implementing the current behavior. As far as i can tell I have mirrored what mongo cli does:

Indeed, the MongoDB shell does use this as its default database since its REPL always has a `db` context. You can chalk this up to legacy behavior. FWIW, the connection strings provided by MongoDB Atlas also include the database component (I believe they use "admin"?).

From the driver's perspective, the root context is always the client object and applications explicitly select a database or collection. The [connection string spec](https://github.com/mongodb/specifications/blob/master/source/connection-string/connection-string-spec.rst#auth-database-optional) for drivers only defines this as a default auth database and makes no mention of it having any other purpose. Given that `authSource` exists, I'd encourage everyone to consider the database component obsolete (unless you're working with the shell).

Some libraries built atop drivers also use the database component as _their_ default database (e.g. default DB for storing models in the Mongoose ODM for Node.js); however, I have the same objections about that since it could also clash with authentication.

Having said all that, I imagine none of this can be changed in 5.x. If you'd like to preemptively open a ticket to address this in 6.0, I would still suggest addressing both `database` and `collection` and perhaps expanding the scope of that TODO ticket to cover any other MongoDB adapters that might exist in Symfony. It's been some time since I contributed, but I believe similar code may exist in the session adapter.

**Comment by kralos** [comment]
@jmikola Thanks heaps for your insight to the usage of `collection` / `database` in mongodb connection URIs. In the interest of allowing this bugfix to proceed, I've opened a separate ticket to deprecate the behavior you've raised concerns with https://github.com/symfony/symfony/issues/37180.

I'll make sure all of this also filters down to `Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler`

**Review by jmikola — APPROVED** [review]
