### PR TITLE
[Serializer] Fix denormalizing scalar with UnwrappingDenormalizer

### LINKED ISSUE #38983: [Serializer] Impossible to use UnwrappingDenormalizer with scalar denormalization
**Symfony version(s) affected**: 5.1.8

**Description**
It's impossible to denormalize into a scalar value when using the unwrap path feature, because the scalar value check is done before applying the UnwrappingDenormalizer.

**How to reproduce**
```php
use Symfony\Component\Serializer\Normalizer\UnwrappingDenormalizer;

$result = $serializer->deserialize(
    '{"baz": "test"}',
    'string',
    'json',
    [UnwrappingDenormalizer::UNWRAP_PATH => '[baz]']
);

// expected result
// $result === "test"

// actual result
// Symfony\Component\Serializer\Exception\NotNormalizableValueException: Data expected to be of type "string" ("array" given).
```

**Possible fix**
Introduce a ScalarDenormalizer instead of checking the target type inside the Serializer class.

### PR DESCRIPTION
**Pull request by camilledejoye**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38983 
| License       | MIT
| Doc PR        | none

In order to work the `UnwrappingDenormlizer` needs to be called first to unwrap the data so that it can be handled by other denormalizers.
To not introduce any BC break this PR does not move the logic into it's own class, instead it checks if a denormalizer supports the data and only denormalize scalar values if there is none.

### CODE REVIEW

File: src/Symfony/Component/Serializer/Serializer.php [hunk 1]
```diff
@@ -179,7 +179,7 @@ public function normalize($data, string $format = null, array $context = [])
             throw new NotNormalizableValueException(sprintf('Could not normalize object of type "%s", no supporting normalizer found.', get_debug_type($data)));
         }
 
-        throw new NotNormalizableValueException('An unexpected value could not be normalized: '.(!\is_resource($data) ? var_export($data, true) : sprintf('%s resource', get_resource_type($data))));
+        throw new NotNormalizableValueException('An unexpected value could not be normalized: '.(!\is_resource($data) ? var_export($data, true) : sprintf('"%s" resource', get_resource_type($data))));
```
Comment (derrabus) [inline src/Symfony/Component/Serializer/Serializer.php]: This is an unrelated change and should be reverted. You can ignore fabbot here.

**Review by derrabus — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @camilledejoye.
