### PR TITLE
[Config] Fix GeneratedConfigTest not being able to generate snapshots anymore

### LINKED ISSUE #61139: GeneratedConfigTest cannot regenerate snapshot files
### Symfony version(s) affected

7.2

### Description

Through https://github.com/symfony/symfony/pull/57614 multiple uses of the `uniqid` have been removed.

This seems to however have broken the generating of "snapshot files" from within the [GeneratedConfigTest](https://github.com/symfony/symfony/blob/cfe62c5d1da2c834eca31cc76f77a42b51cec1dd/src/Symfony/Component/Config/Tests/Builder/GeneratedConfigTest.php#L86)

When uncommenting the lines on a version prior to the PR the files are regenerated without problems. Uncommenting on a version after the PR was merged however only deletes the snapshot files, and does not generate new ones.

### How to reproduce

1. Checkout the symfony repository.
2. Open the GeneratedConfigTest.
3. Uncomment lines to regenerate a snapshot file (should be lines 87 up to, including line 89)
4. Run the test

A bunch of the snapshot configs are now gone.

5. Re-comment the above mentioned lines
6. Re-run the test

The test should now fail with the "The system cannot find the file" exception messages.

### Possible Solution

~Revert the changes from #57614 in the GeneratedConfigTest~
It was removed as part of #57588, so just reverting the changes would not be preferable. And another fix should be implemented.

### Additional Context

OS: Windows 11
PHP version: 8.3

### PR DESCRIPTION
**Pull request by KevinVanSonsbeek**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #61139
| License       | MIT

PR #57614 Removed multiple uses of `uniqid`. In the specific PR changes were made to the GeneratedConfigTest, to change how the directory was built for the config.

This inadvertedly broke the generating of snapshot files, due to the outputDir being changed to a by reference argument, and always overwriting the value to a temp dir. (While the snapshot files should not be written to a temp dir)

### CODE REVIEW

**Comment by KevinVanSonsbeek** [comment]
Psalm errors seem unrelated to my changes

File: src/Symfony/Component/Config/Tests/Builder/GeneratedConfigTest.php [hunk 1]
```diff
@@ -159,10 +159,12 @@ public function testSetExtraKeyMethodIsNotGeneratedWhenAllowExtraKeysIsFalse()
      */
     private function generateConfigBuilder(string $configurationClass, ?string &$outputDir = null)
     {
-        $outputDir = tempnam(sys_get_temp_dir(), 'sf_config_builder_');
-        unlink($outputDir);
-        mkdir($outputDir);
-        $this->tempDir[] = $outputDir;
+        if (null === $outputDir) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Config/Tests/Builder/GeneratedConfigTest.php:162]: $outputDir is going to be always null
what we need is probably

```suggestion
        if (1 < \func_num_args()) {
```

Comment (KevinVanSonsbeek) [reply src/Symfony/Component/Config/Tests/Builder/GeneratedConfigTest.php:162]: Lines 87 -> 89 of the test contain commented code, that when uncommented try to regenerate the snapshot files.
On line 88 it specifically passes the directory of the expected code, so the new snapshots are generated in the given location. Resulting in the outputDir not being null.

Comment (nicolas-grekas) [reply src/Symfony/Component/Config/Tests/Builder/GeneratedConfigTest.php:162]: got it thanks

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @KevinVanSonsbeek.
