### PR TITLE
[Serializer] Correct all implementations of the `NormalizerInterface` to have the correct method signature

### LINKED ISSUE #59495: [Serializer] Discrepancy between NormalizerInterface and it's implementation
### The "Problem"
Right now there is a discrepancy between the `Symfony\Component\Serializer\Normalizer\NormalizerInterface` and it's implementations within the Symfony codebase.

If you look at the signature of the NormalizerInterface.normalize method it looks as follows:
`public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null;`

Whereas most implementing classes are implemented like this:

**AbstractObjectNormalizer:**
`public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null`

**DateIntervalNormalizer:**
`public function normalize(mixed $object, ?string $format = null, array $context = []): string`

And the list goes on..

Whilst PHP allows this behavior to exists and doesn't raise any errors for it, with the introduction of named parameters in PHP 8.0 this discrepancy now has the possibility to throw PHP errors such as:
`Error: Unknown named parameter $data`.

### Acknowledgement
Whilst reading through the existing issues I came upon https://github.com/symfony/symfony/pull/54880 where it was discussed that the BC does not cover this change or would increase the risk of merging changes back into branches. 

However, in it's current implementation it is simply impossible to use named parameters when type hinting the `NormalizerInterface` and not running the risk of unexpected PHP errors.

### Conclusion
Therefore I would like to submit this as a feature ("not a bug") type of change to the 7.3/7.4 branch to solve this discrepancy and reducing the risk of unintentional errors for developers using Symfony.

Linked to this issue is a PR that changes all instances where the NormalizerInterface is implemented but does not follow the Interfaces' signature. 

### Example

The following is a change to the ObjectNormalizerTest that shows that using named parameters on the interface with an implementation of the ObjectNormalizer PHP will throw an error

```php
<?php

namespace Symfony\Component\Serializer\Tests\Normalizer;

class ObjectNormalizerTest extends TestCase
{
    private ObjectNormalizer $normalizer;
    private NormalizerInterface $normalizerInterface;
    private SerializerInterface&NormalizerInterface&MockObject $serializer;

    protected function setUp(): void
    {
        $this->createNormalizer();

        $this->normalizerInterface = $this->normalizer;
    }

    private function createNormalizer(array $defaultContext = [], ?ClassMetadataFactoryInterface $classMetadataFactory = null): void
    {
        $this->serializer = $this->createMock(ObjectSerializerNormalizer::class);
        $this->normalizer = new ObjectNormalizer($classMetadataFactory, null, null, null, null, null, $defaultContext);
        $this->normalizer->setSerializer($this->serializer);
    }

    // In the current releases this throws an error
    public function testNamedArgumentsOnInterfaceWillThrowError(): void
    {
        $this->normalizerInterface->normalize(
            data: new ObjectDummy(),
            format: 'json',
            context: []
        );
    }
}
```

```bash
php ./phpunit src/Symfony/Component/Serializer
...
Time: 00:00.302, Memory: 39.02 MB

There was 1 error:

1) Symfony\Component\Serializer\Tests\Normalizer\ObjectNormalizerTest::testNamedArgumentsOnInterfaceWillThrowError
Error: Unknown named parameter $data
```

And after changing all implementations:

```bash
php ./phpunit src/Symfony/Component/Serializer

............................................................. 1098 / 1167 ( 94%)
............................................................. 1159 / 1167 ( 99%)
........                                                      1167 / 1167 (100%)

Time: 00:00.365, Memory: 39.02 MB

OK, but incomplete, skipped, or risky tests!
Tests: 1167, Assertions: 2258, Skipped: 11.

Legacy deprecation notices (2)
```

### PR DESCRIPTION
**Pull request by Kefisu**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59495
| License       | MIT

This PR corrects the signatures of all normalizers implementing the NormalizerInterface of the Serializer component effectively changing: `function normalize($object, ... )` to `function normalize(mixed $data, ...)` as is in line with the interface.

Whilst Named Arguments is against the BC promise of Symfony, with the current implementation of the normalizers it is impossible to use named arguments with the Strategy Pattern using the Serializer component, with this change it is possible.

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]
Works for me, but as you mentioned, there is no BC guarantee that named arguments work nor will keep working. If you rely on them for the strategy pattern, you're on your own.

**Comment by Kefisu** [comment]
Any further idea's on this PR?

File: src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php [hunk 1]
```diff
@@ -99,6 +102,15 @@ private function createNormalizer(array $defaultContext = [], ?ClassMetadataFact
         $this->normalizer->setSerializer($this->serializer);
     }
 
+    public function testNamedArgumentsOnInterfaceWillNotThrowError()
```
Comment (xabbuh) [inline src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php]: this test should be removed IMO as it gives the false impression that we guarantee backwards compatibility on named arguments (which we don't)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Kefisu.
