### PR TITLE
[Mailer] Fix Azure bridge double encoding attachments' content

### LINKED ISSUE #53132: [Mailer] Azure API Transport - attachments are encoded twice
### Symfony version(s) affected

7.1

### Description

[`AzureApiTransport.php` Line 163:](https://github.com/symfony/azure-mailer/blob/041dbf111c18610296a9d4e07e2dd9ff30653ffa/Transport/AzureApiTransport.php#L163C51)

```php
$attachment->bodyToString();
```

returns `aGVsbG8gd29ybGQ=`, which is already base64 encoded. This results in an attachment containing `YUdWc2JHOGdkMjl5YkdRPQ==` (see context), which is `hello world` encoded twice. Also affects other mime types like `image/png`.

### How to reproduce

Example code:

```php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Mime\Part\DataPart;
use Symfony\Component\Routing\Annotation\Route;

class MailerController extends AbstractController
{
    #[Route('/email')]
    public function sendEmail(MailerInterface $mailer): Response
    {
        $email = (new Email())
            ->from('hello@example.com')
            ->to('you@example.com')
            ->addPart(new DataPart('hello world', 'test.txt', 'text/plain'));

        $mailer->send($email);
    }
}

```

### Possible Solution

Removing `base64_encode()` from line 163 allows attachments to be sent correctly, not sure what the implications are for other encoding schemes like quoted-printable or 8bit.
```php
'contentInBase64' => base64_encode(str_replace("\r\n", '', $attachment->bodyToString())),
```

Might be better to base64 encode the string from `getBody()` instead:

```php
'contentInBase64' => base64_encode($attachment->getBody()),
```

(I usually work with Laravel, not very familiar with how Symfony works).

### Additional Context

Raw message:

```
--=-RKMiR41T+m0J1Vs36aWDPA==
Content-Type: multipart/alternative; boundary="=-RTeuOYJLs2Fl6qsDDGsPrg=="

--=-RTeuOYJLs2Fl6qsDDGsPrg==
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

=C2=A9 2023. All rights reserved.
--=-RTeuOYJLs2Fl6qsDDGsPrg==--
--=-RKMiR41T+m0J1Vs36aWDPA==
Content-Type: text/plain; name=test.txt
Content-Disposition: attachment
Content-Transfer-Encoding: base64
Content-Id: <adbe2c0b-3174-400a-b47a-78090cb7ee7b>

YUdWc2JHOGdkMjl5YkdRPQ==
--=-RKMiR41T+m0J1Vs36aWDPA==--
```

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #53132
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/Mailer/Bridge/Azure/Transport/AzureApiTransport.php [hunk 1]
```diff
@@ -160,7 +160,7 @@ private function getMessageAttachments(Email $email): array
 
             $att = [
                 'name' => $filename,
-                'contentInBase64' => base64_encode(str_replace("\r\n", '', $attachment->bodyToString())),
+                'contentInBase64' => base64_encode(str_replace("\r\n", '', $attachment->getBody())),
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mailer/Bridge/Azure/Transport/AzureApiTransport.php]: I'm doubtful about the str_replace, can you double-check?

Comment (alexandre-daubois) [reply src/Symfony/Component/Mailer/Bridge/Azure/Transport/AzureApiTransport.php]: It doesn't make sense to me either, removed

**Review by javiereguiluz — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @alexandre-daubois.
