### PR TITLE
[DoctrineBridge] Bugfix - Allow to remove LazyLoaded listeners by object

### LINKED ISSUE #51057: [DoctrineBridge] Cannot remove Lazy-loaded listeners by object
### Symfony version(s) affected

6.3.x, but maybe lower

### Description

Let's say I the following code 
```
foreach ($this->em->getEventManager()->getAllListeners() as $event => $listeners) {
     foreach ($listeners as $listener) {
         $this->em->getEventManager()->removeEventListener($event, $listener);
    }
}
```

To me this is suppose to remove all the existing event listener.
Seems like with the `ContainerAwareEventManager` it does nothing.

If I dump the `listeners`, I get:
```
[
    'postPersist' => [
        '_service_App\EventListener\MyListener' => the object(App\EventListener\MyListener),
    ],
]
```

Which means that, when I call `removeEventListener($event, $listener)`, I pass the event and the object but in the remove method, the hash computed is the spl_object_hash and not the one with `_service` prefix.
https://github.com/symfony/symfony/blob/bd04cdaf6fc479a6f5602b862c190940b38a633e/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php#L128-L146

I would say something is wrong with the `initializeListeners` method
https://github.com/symfony/symfony/blob/bd04cdaf6fc479a6f5602b862c190940b38a633e/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php#L166-L176
because it transform the `$listener` as string to the object instance, but without changing the hash.

the $lister property is modified from 
```
[
    'postPersist' => [
        '_service_App\EventListener\MyListener' => "App\EventListener\MyListener",
    ],
]
```
to
```
[
    'postPersist' => [
        '_service_App\EventListener\MyListener' => the object(App\EventListener\MyListener),
    ],
]
```
when it should be
```
[
    'postPersist' => [
        'someHash' => the object(App\EventListener\MyListener),
    ],
]
```

### Possible Solution

First I thought of something like
Maybe the method should be
```
    private function initializeListeners(string $eventName): void
    {
        $this->initialized[$eventName] = true;
        foreach ($this->listeners[$eventName] as $hash => $listener) {
            if (\is_string($listener)) {
                $listener = $this->container->get($listener);
                $newHash = $this->getHash($listener);
                unset($this->listeners[$eventName][$hash]);
                
                $this->listeners[$eventName][$newHash] = $listener;
                $this->methods[$eventName][$newHash] = $this->getMethod($listener, $eventName);
            }
        }
    }
```

But it require listeners to be initialized then.
Which means that:
```
$listener = new MyListener();
$this->container->set('lazy', $listener);
$this->evm->addEventListener('foo', 'lazy');
$this->evm->removeEventListener('foo', $listener);
```
won't do nothing when 
```
$listener = new MyListener();
$this->container->set('lazy', $listener);
$this->evm->addEventListener('foo', 'lazy');
$this->evm->getAllListeners(); // Just to initialized
$this->evm->removeEventListener('foo', $listener);
```
will remove the lazy (now loaded) listener. Which would be weird.

### Reproducer

This is a reproducer in the Symfony Tests:
```
public function testRemoveAllEventListener()
    {
        $this->container->set('lazy', new MyListener());
        $this->evm->addEventListener('foo', 'lazy');
        $this->evm->addEventListener('foo', new MyListener());

        foreach ($this->evm->getAllListeners() as $event => $listeners) {
            foreach ($listeners as $listener) {
                $this->evm->removeEventListener($event, $listener);
            }
        }

        $this->assertSame([], $this->evm->getListeners('foo'));
    }
```

### Additional context

This seems cause by the PR https://github.com/symfony/symfony/pull/31335 and reported here https://github.com/symfony/symfony/pull/31335#issuecomment-562576326
@Koc @nicolas-grekas @dmaicher

### PR DESCRIPTION
**Pull request by VincentLanglet**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #51057
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

cc @dmaicher

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php [hunk 1]
```diff
@@ -190,13 +201,25 @@ public function removeEventSubscriber(EventSubscriber $subscriber): void
     private function initializeListeners(string $eventName)
     {
         $this->initialized[$eventName] = true;
+
+        // We'll refill the whole array in order to keep the same order
+        $listeners = [];
```
Comment (VincentLanglet) [inline src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php:202]: If I just do
```
$this->listeners[$eventName][$newHash] = $listener;
```
the order of the listeners change.

I'm not sure if there is a better solution to keep the order

File: src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php [hunk 2]
```diff
@@ -158,6 +160,15 @@ public function removeEventListener($events, $listener)
         $hash = $this->getHash($listener);
 
         foreach ((array) $events as $event) {
+            if (!isset($this->initialized[$event])) {
+                $this->initializeListeners($event);
```
Comment (VincentLanglet) [inline src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php]: Only solution found so far for the `testRemoveLazyListenerInitialized`

File: src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php (hunk 1 above)
Comment (dmaicher) [reply src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php:202]: seems ok to me to just re-create it :man_shrugging: 

But maybe it would be good to add a test that makes sure we keep the order?

Comment (VincentLanglet) [reply src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php:202]: The test already exist. If I don't keep the same order, multiple tests are failing because of the `assertSame` checks

**Review by dmaicher — APPROVED** [review]

File: src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php (hunk 2 above)
Comment (nicolas-grekas) [reply src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php]: I wouldn't support this use case personally. Let's remove this part.

Comment (VincentLanglet) [reply src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php]: I removed it then @nicolas-grekas

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @VincentLanglet.
