### PR TITLE
[ErrorHandler] fix html W3C compliance

### LINKED ISSUE #38471: [ErrorHandler] Error page isn't w3 valid
**Symfony version(s) affected**: 5.0.*

**Description**  
The page that is shown when you get a php error is not [w3 valid ](https://validator.w3.org/) it is even mentioning errors that there are stray `span` tags: `Error: Stray end tag span.` and `h3` tags that are in `span` and `th` which isn't allowed.

**How to reproduce**
1. Force a php error.
2. Open page source and copy it.
3. Past it in https://validator.w3.org/#validate_by_input and see the results

**Possible Solution**  
We should probably fix some errors like stray tags

**Additional context**  
w3

### PR DESCRIPTION
**Pull request by awoimbee**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes but not really
| New feature?  | no
| Deprecations? | no
| Tickets       | Fixes #38471
| License       | MIT

Fixes:
- `<h3>` inside `<span></span>`
- `name` attribute on `<a>` is deprecated
- stray `</span>`
- `nowrap` attribute is deprecated
- `<h3>` inside `<th>` (heading content in a table header)

### CODE REVIEW

File: src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php [hunk 1]
```diff
@@ -283,7 +283,7 @@ private function fileExcerpt(string $file, int $line, int $srcContext = 3): stri
             }
 
             for ($i = max($line - $srcContext, 1), $max = min($line + $srcContext, \count($content)); $i <= $max; ++$i) {
-                $lines[] = '<li'.($i == $line ? ' class="selected"' : '').'><a class="anchor" name="line'.$i.'"></a><code>'.$this->fixCodeMarkup($content[$i - 1]).'</code></li>';
+                $lines[] = '<li'.($i == $line ? ' class="selected"' : '').'><a class="anchor" id="line'.$i.'"></a><code>'.$this->fixCodeMarkup($content[$i - 1]).'</code></li>';
```
Comment (stof) [inline src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php]: generating an id using the line number alone is wrong. That's not ensuring uniqueness as multiple file excerpt might have similar line numbers in different files (or even in the same file)

File: src/Symfony/Component/ErrorHandler/Resources/views/logs.html.php [hunk 2]
```diff
@@ -23,7 +23,7 @@
             $status = \E_DEPRECATED === $severity || \E_USER_DEPRECATED === $severity ? 'warning' : 'normal';
         } ?>
         <tr class="status-<?= $status; ?>" data-filter-level="<?= strtolower($this->escape($log['priorityName'])); ?>"<?php if ($channelIsDefined) { ?> data-filter-channel="<?= $this->escape($log['channel']); ?>"<?php } ?>>
-            <td class="text-small" nowrap>
+            <td class="text-small" style="white-space:nowrap">
```
Comment (stof) [inline src/Symfony/Component/ErrorHandler/Resources/views/logs.html.php]: should be replaced by a class, with styles defined in the CSS of the component instead.

File: src/Symfony/Component/ErrorHandler/Resources/views/traces.html.php [hunk 3]
```diff
@@ -1,21 +1,21 @@
...
                     </span>
                     <?= ($parts = explode('\\', $exception['class'])) ? end($parts) : ''; ?>
-                </h3>
 
-                <?php if ($exception['message'] && $index > 1) { ?>
-                    <p class="break-long-words trace-message"><?= $this->escape($exception['message']); ?></p>
-                <?php } ?>
-            </span>
+                    <?php if ($exception['message'] && $index > 1) { ?>
+                        <p class="break-long-words trace-message"><?= $this->escape($exception['message']); ?></p>
```
Comment (stof) [inline src/Symfony/Component/ErrorHandler/Resources/views/traces.html.php]: a `<p>` instead a `<h3>` is not valid either.

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php (hunk 1 above)
Comment (awoimbee) [reply src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php]: I was scared to modify the code too much.
I just now put on my big boy pants and removed them since they could not be not functional anyways (`name` tags on anchors should be unique, just like ids).

Another way of doing things would be to add the file name **and** the file "id" (`(...)/Kernel.php:line_30`, `(...)/Kernel.php-1:line_30`) but at this point we should just remove them.

File: src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php [hunk 4]
```diff
@@ -276,14 +276,13 @@ private function fileExcerpt(string $file, int $line, int $srcContext = 3): stri
...
             $content = explode('<br />', $code);
-
             $lines = [];
             if (0 > $srcContext) {
                 $srcContext = \count($content);
             }
 
             for ($i = max($line - $srcContext, 1), $max = min($line + $srcContext, \count($content)); $i <= $max; ++$i) {
-                $lines[] = '<li'.($i == $line ? ' class="selected"' : '').'><a class="anchor" name="line'.$i.'"></a><code>'.$this->fixCodeMarkup($content[$i - 1]).'</code></li>';
+                $lines[] = '<li'.($i == $line ? ' class="selected"' : '').'><code>'.$this->fixCodeMarkup($content[$i - 1]).'</code></li>';
```
Comment (ro0NL) [inline src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php:286]: the FileLinkFormatter relies on the anchor link :)

https://github.com/symfony/symfony/blob/494ef421c554a78b38c6779c4b7deb9a20d89923/src/Symfony/Bundle/WebProfilerBundle/Resources/config/profiler.php#L72

Comment (stof) [reply src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php:286]: then we might need an option to put the ids on that page only (where there is a single file excerpt)

Comment (awoimbee) [reply src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php:286]: It relies on anchors generated by another Class :D
The page at address `http://localhost:8000/public/index.php/_profiler/open?file=src/Controller/HelloController.php&line=17#line17` for exemple, isn't affected by this change [check it out](https://www.meerodrop.com/en/drop/09d26e10-4cac-475f-9dac-3ab57255b5b0).
I'm gonna switch name tags to id tags on this page too.

Comment (ro0NL) [reply src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php:286]: try a longer line no. ;) the missing anchor here will break the url, in terms of the anchor wont be scrolled to.

File: src/Symfony/Bridge/Twig/Extension/CodeExtension.php [hunk 5]
```diff
@@ -137,7 +137,7 @@ public function fileExcerpt(string $file, int $line, int $srcContext = 3): ?stri
             }
 
             for ($i = max($line - $srcContext, 1), $max = min($line + $srcContext, \count($content)); $i <= $max; ++$i) {
-                $lines[] = '<li'.($i == $line ? ' class="selected"' : '').'><a class="anchor" name="line'.$i.'"></a><code>'.self::fixCodeMarkup($content[$i - 1]).'</code></li>';
+                $lines[] = '<li'.($i == $line ? ' class="selected"' : '').'><a class="anchor" id="line'.$i.'"></a><code>'.self::fixCodeMarkup($content[$i - 1]).'</code></li>';
```
Comment (ro0NL) [inline src/Symfony/Bridge/Twig/Extension/CodeExtension.php:140]: to avoid duplicate IDs we could use a static uniquely prefixed counter perhaps

File: src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php (hunk 4 above)
Comment (stof) [reply src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php:286]: @ro0NL I think `/_profiler/open` does not use the ErrorRenderer to render file excerpt

File: src/Symfony/Bridge/Twig/Extension/CodeExtension.php (hunk 5 above)
Comment (ro0NL) [reply src/Symfony/Bridge/Twig/Extension/CodeExtension.php:140]: well no, because we dont know the ID upfront for linking. Not sure what's best :P

File: src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php (hunk 4 above)
Comment (ro0NL) [reply src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php:286]: im looking at the same file twice -.-

the impact on the twig bridge's code extension is maybe even more severe :)

File: src/Symfony/Bridge/Twig/Extension/CodeExtension.php (hunk 5 above)
Comment (ro0NL) [reply src/Symfony/Bridge/Twig/Extension/CodeExtension.php:140]: another "oh well", currently multiple code blocks on the same probably cant be linked to already.

But this only introduces more errors then.

Perhaps keep the name attr./deprecation in this case, given the HTML is exposed in public domain.

Comment (ro0NL) [reply src/Symfony/Bridge/Twig/Extension/CodeExtension.php:140]: `filename|file_excerpt(line, -1, line_anchors=true)` explicitly on the 'profiler open page' will also do it, then using id attribute is ok.

Comment (awoimbee) [reply src/Symfony/Bridge/Twig/Extension/CodeExtension.php:140]: This code change is only for good measures honestly, it doesn't change anything about the behavior.
Duplicate `name`attributes are equally as bad as duplicate `id` attributes, not better nor worse.

Also, I don't think this is a big issue as `CodeExtension` is used for viewing single files.
Anyways, this is a pre-existing problem and is outside the scope of this PR.

PS: (if you reaaaaly want it I can just remove that commit, it's so minor I really don't care)

Comment (ro0NL) [reply src/Symfony/Bridge/Twig/Extension/CodeExtension.php:140]: >  not better nor worse

works for me :+1:

**Comment by awoimbee** [comment]
Bump
All the feedback has been answered, everything seems good to merge.
It's not an issue if I need to rebase to make the tests pass (it's obviously not my PR that broke them).

File: src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php [hunk 6]
```diff
@@ -276,14 +276,13 @@ private function fileExcerpt(string $file, int $line, int $srcContext = 3): stri
                 return "<span $m[1]>".str_replace('<br />', "</span><br /><span $m[1]>", $m[2]).'</span>';
             }, $code);
             $content = explode('<br />', $code);
-
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php]: let's keep this line

**Review by nicolas-grekas — APPROVED** [review]
Looks good to me. Does this change anything visually?

**Comment by awoimbee** [comment]
@nicolas-grekas 
I just checked all the profiler pages, the dump, ...
I only found that the toggle button on the exception page is now a bit lower (centered instead of top left)
To me this isn't an issue, if you agree then this is 100% OK to merge.
Here are screenshots: https://www.meerodrop.com/fr/drop/9a407d4e-c42e-42a5-9c4b-ee6d86598ceb

File: src/Symfony/Component/ErrorHandler/Resources/views/traces.html.php [hunk 7]
```diff
@@ -1,21 +1,17 @@
...
-                    <span class="trace-namespace">
-                        <?= implode('\\', array_slice(explode('\\', $exception['class']), 0, -1)); ?><?= count(explode('\\', $exception['class'])) > 1 ? '\\' : ''; ?>
-                    </span>
-                    <?= ($parts = explode('\\', $exception['class'])) ? end($parts) : ''; ?>
-                </h3>
-
+            <div class="sf-toggle" data-toggle-selector="#trace-html-<?= $index; ?>" data-toggle-initial="<?= $expand ? 'display' : ''; ?>">
+                <span class="icon icon-close"><?= $this->include('assets/images/icon-minus-square-o.svg'); ?></span>
+                <span class="icon icon-open"><?= $this->include('assets/images/icon-plus-square-o.svg'); ?></span>
+                <h4 class="trace-namespace">
```
Comment (stof) [inline src/Symfony/Component/ErrorHandler/Resources/views/traces.html.php]: This creates a `h4` being a header without any content. I don't think that's good.

IMO, the trace namespace and the trace class should both stay in the `<h3>`, so that the heading text is the FQCN.

File: src/Symfony/Component/ErrorHandler/Resources/views/traces.html.php [hunk 8]
```diff
@@ -1,21 +1,17 @@
...
+                    <?= implode('\\', array_slice(explode('\\', $exception['class']), 0, -1)); ?><?= count(explode('\\', $exception['class'])) > 1 ? '\\' : ''; ?>
+                </h4>
+                <h3 class="trace-class"><?= ($parts = explode('\\', $exception['class'])) ? end($parts) : ''; ?></h3>
                 <?php if ($exception['message'] && $index > 1) { ?>
-                    <p class="break-long-words trace-message"><?= $this->escape($exception['message']); ?></p>
+                    <h4 class="break-long-words trace-message"><?= $this->escape($exception['message']); ?></h4>
```
Comment (stof) [inline src/Symfony/Component/ErrorHandler/Resources/views/traces.html.php]: Should the exception message really become a heading ?

**Comment by Nyholm** [comment]
Thank you @awoimbee for your work.

Could you finish this PR so it is included in the next release?

File: src/Symfony/Component/ErrorHandler/Resources/views/traces.html.php (hunk 7 above)
Comment (awoimbee) [reply src/Symfony/Component/ErrorHandler/Resources/views/traces.html.php]: Fixed

File: src/Symfony/Component/ErrorHandler/Resources/views/traces.html.php (hunk 8 above)
Comment (awoimbee) [reply src/Symfony/Component/ErrorHandler/Resources/views/traces.html.php]: Yes, it's in the same header-box/div/gray-box-thing as the FQCN and is definitely not a paragraph

**Comment by awoimbee** [comment]
Hope it's good now!
If there is a small thing that bothers you before merging, feel free to commit to this PR.
It should be faster that requesting changes and re-reviewing later at this point

File: src/Symfony/Component/ErrorHandler/Resources/views/traces.html.php (hunk 8 above)
Comment (stof) [reply src/Symfony/Component/ErrorHandler/Resources/views/traces.html.php]: From an accessibility point of view, the message is definitely not a heading. The choice between `<h4>` and `<p>` should not be done based on styling but on semantic.

File: src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php (hunk 4 above)
Comment (Nyholm) [reply src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php:286]: How was this resolved? @ro0NL

Comment (awoimbee) [reply src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php:286]: As written above, `FileLinkFormatter` relies on anchor links from `CodeExtension`, not `ErrorRenderer`.
Another feedback was made about `CodeExtension`.

On my side I searched for every occurrence of the line id / name and did not find anywhere were the ones from `ErrorRenderer` were used, and seeing that they were mostly unusable and could break at any time, I deduced that removing them was for the best.

Comment (ro0NL) [reply src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php:286]: @Nyholm the ID anchor is preserved in `CodeExtension.php` :)  it's not needed in `HtmlErrorRenderer.php`

Comment (Nyholm) [reply src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php:286]: Thank you for your explanations. I didnt understand it at first. 

👍

File: src/Symfony/Component/ErrorHandler/Resources/views/traces.html.php (hunk 8 above)
Comment (Nyholm) [reply src/Symfony/Component/ErrorHandler/Resources/views/traces.html.php]: > From an accessibility point of view, the message is definitely not a heading.

Sorry for asking. But could you elaborate on this?

Comment (stof) [reply src/Symfony/Component/ErrorHandler/Resources/views/traces.html.php]: if you make both the class name and the message be heading, you end up with a content being only headings, and these headings have no content that they are heading.
Btw, you also end up with a single h4-level subsection in each h3-level section, which tends to also indicate that this is not proper subsections of the content (even when forgetting the fact that the content is empty).

See https://hiddedevries.nl/en/blog/2020-09-05-when-there-is-no-content-between-headings talking about this.

Comment (Nyholm) [reply src/Symfony/Component/ErrorHandler/Resources/views/traces.html.php]: Thank you for the clarification.

@awoimbee, could you change it back to `p`?

Comment (awoimbee) [reply src/Symfony/Component/ErrorHandler/Resources/views/traces.html.php]: Done !

**Comment by nicolas-grekas** [comment]
Thank you @awoimbee.
