### PR TITLE
[FrameworkBundle] Remove project dir from Translator cache vary scanned directories

### LINKED ISSUE #34395: Translation cache warming ineffective since #34129
**Symfony version(s) affected**: 4.3.7/4.3.8

**Description**  
Since 4.3.7, warming translation caches then deploying to a different path results in the warmed cached being ignored and regenerated. I believe this is caused by the change in #34129, which effectively adds the full project path to the cache key for the translator.

**How to reproduce**  
* Warm the translation cache.
* Rename the project directory.
* Warm the translation cache again. At this point, the translation cache file names will change.

For example, `var/cache/prod/translations/catalogue.en_GB.FOO.php` will be replaced with `var/cache/prod/translations/catalogue.en_GB.BAR.php`.

**Possible Solution**  
Could the project directory be removed from the paths in "scanned_directories"?

### PR DESCRIPTION
**Pull request by fancyweb**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Closes #34395
| License       | MIT
| Doc PR        | -

Weird cases such as having different paths for directories found through reflection (cf https://github.com/symfony/symfony/blob/8522a88185a7e283ad342b3539cd088d76968df9/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1105) or using different values on warmup and run for another parameter than `kernel.project_dir` are still unconvered. Unfortunately there is nothing we can do, do we care? If yes, then we might just wanna enable https://github.com/symfony/symfony/pull/34129 when the `debug` option is on.

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -1184,11 +1184,22 @@ private function registerTranslatorConfiguration(array $config, ContainerBuilder
...
+
             $options = array_merge(
                 $translator->getArgument(4),
                 [
                     'resource_files' => $files,
-                    'scanned_directories' => array_merge($dirs, $nonExistingDirs),
+                    'scanned_directories' => $scannedDirectories = array_merge($dirs, $nonExistingDirs),
+                    'cache_vary' => [
+                        'scanned_directories' => array_map(static function (string $dir) use ($projectDir, $projectDirLength): string {
+                            if (0 === strncmp($dir, $projectDir, $projectDirLength)) {
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: does this work fine on Windows in all cases, or could we have path separator mismatches.

File: src/Symfony/Bundle/FrameworkBundle/Tests/Translation/TranslatorTest.php [hunk 2]
```diff
@@ -255,8 +255,10 @@ public function testCachedCatalogueIsReDumpedWhenScannedDirectoriesChange()
                     __DIR__.'/../Fixtures/Resources/translations/messages.fr.yml',
                 ],
             ],
-            'scanned_directories' => [
-                __DIR__.'/../Fixtures/Resources/translations/',
+            'cache_vary' => [
+                'scanned_directories' => [
+                    '/Fixtures/Resources/translations/',
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/Tests/Translation/TranslatorTest.php]: I think we need to remove the leading `/` too, to avoid ambiguity between `/projectRoot/Fixtures/Resources/translations/` and `/Fixtures/Resources/translations/` (outside project root, left unchanged). Paths starting with a `/` here will look the same than absolute paths

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php (hunk 1 above)
Comment (fancyweb) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: https://github.com/symfony/symfony/pull/34397/files#diff-b0c828e732d3d31f0b2bfb2378bd1011R828 normally asserts that it works. The project dir needs to be correctly removed for the assertion to pass.

File: src/Symfony/Bundle/FrameworkBundle/Tests/Translation/TranslatorTest.php (hunk 2 above)
Comment (fancyweb) [reply src/Symfony/Bundle/FrameworkBundle/Tests/Translation/TranslatorTest.php]: I added a ltrim.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 3]
```diff
@@ -1184,11 +1184,22 @@ private function registerTranslatorConfiguration(array $config, ContainerBuilder
...
+                                return ltrim(substr($dir, $projectDirLength), '/');
+                            }
+
+                            return $dir;
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: looks like this would be enough and a bit stricter:
`return 0 === strpos($dir, $projectDir.'/') ? substr($dir, 1 + \strlen($projectDir) : $dir;`

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @fancyweb.
