### PR TITLE
[Yaml] support YAML 1.2 octal notation, deprecate YAML 1.1 one

### LINKED ISSUE #34807: [YAML] Parsing octal numbers: unexpected value conversion and PHP 7.4 notice
**Symfony version(s) affected**: probably all (tried 4.3 and 4.4)

**Description**  

Parsing YAML values that start with 0 may result in a deprecation warning in PHP 7.4:

 > Invalid characters passed for attempted conversion, these have been ignored

Related note in PHP 7.4 migration guide: https://www.php.net/manual/en/migration74.deprecated.php#migration74.deprecated.core.invalid-base-characters

Also unsure if the parsing happens correctly according to the YAML spec.

Having something like `OwnerId: 0123456789` in YAML, it is being interpreted as an octal number and results in `[OwnerId] => 342391` when parsed.

**How to reproduce**  

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$yaml = \Symfony\Component\Yaml\Yaml::parse(<<<YAML
OwnerId: 0123456789
YAML
);

print_r($yaml);
```

results in:

```
Array
(
    [OwnerId] => 342391
)
```

`342391` decimal, when converted back to ocal however is `1234567` in octal, not `0123456789`, which is obvious, because `0123456789` is not a valid octal number. 

**Possible Solution**  

As far as I see, [the yaml spec](https://yaml.org/spec/1.2/spec.html) is not clear about how to handle this case. Many users might be unaware of this conversion and actually expect a string '0123456789' as the parseing result. So we should probably add a check and only convert octal numbers that are valid.

I also found that YAML 1.1 is showing octal number examples like `013` but YAML 1.2 they are `0o14`...

**Additional context**  

related code:
https://github.com/symfony/symfony/blob/c732122b574ecfb083d44324ac18f9508e95471d/src/Symfony/Component/Yaml/Inline.php#L625-L634

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | yes
| Tickets       | Fix #34807
| License       | MIT
| Doc PR        |

### CODE REVIEW

File: src/Symfony/Component/Yaml/Inline.php [hunk 1]
```diff
@@ -617,21 +617,29 @@ private static function evaluateScalar(string $scalar, int $flags, array $refere
...
-                    case Parser::preg_match('{^[+-]?[0-9][0-9_]*$}', $scalar):
-                        $scalar = str_replace('_', '', (string) $scalar);
-                        // omitting the break / return as integers are handled in the next case
-                        // no break
                     case ctype_digit($scalar):
                         $raw = $scalar;
                         $cast = (int) $scalar;
 
+                        if ('0' === $scalar[0] && !Parser::preg_match('/^[0-7]*$/', $scalar)) {
+                            @trigger_error(sprintf('Support for parsing the invalid octal number %s is deprecated since Symfony 5.1.', $scalar), E_USER_DEPRECATED);
```
Comment (stof) [inline src/Symfony/Component/Yaml/Inline.php]: should we mention it will be parsed as a string in 6+ ?

File: src/Symfony/Component/Yaml/Inline.php [hunk 2]
```diff
@@ -617,21 +617,29 @@ private static function evaluateScalar(string $scalar, int $flags, array $refere
...
                     case '-' === $scalar[0] && ctype_digit(substr($scalar, 1)):
                         $raw = $scalar;
                         $cast = (int) $scalar;
 
-                        return '0' == $scalar[1] ? octdec($scalar) : (((string) $raw === (string) $cast) ? $cast : $raw);
+                        if ('0' === $scalar[1] && !Parser::preg_match('/^[0-7]*$/', $octal = substr($scalar, 1))) {
+                            @trigger_error(sprintf('Support for parsing the invalid octal number %s is deprecated since Symfony 5.1.', $scalar), E_USER_DEPRECATED);
+                        }
+
+                        return '0' == $scalar[1] ? -octdec($octal) : (($raw === (string) $cast) ? $cast : $raw);
```
Comment (stof) [inline src/Symfony/Component/Yaml/Inline.php]: should be a string comparison

**Review by stof — COMMENTED** [review]
should we also add support for parsing YAML 1.2 octal notation with `0o` ?

File: src/Symfony/Component/Yaml/Inline.php (hunk 1 above)
Comment (cebe) [reply src/Symfony/Component/Yaml/Inline.php]: At this point, to avoid the deprecation notice in PHP 7.4, how about removing the invalid characters before passing the scalar to octdec()?

File: src/Symfony/Component/Yaml/Inline.php [hunk 3]
```diff
@@ -617,21 +617,29 @@ private static function evaluateScalar(string $scalar, int $flags, array $refere
...
+                            @trigger_error(sprintf('Support for parsing the invalid octal number %s is deprecated since Symfony 5.1.', $scalar), E_USER_DEPRECATED);
+                        }
+
                         return '0' == $scalar[0] ? octdec($scalar) : (((string) $raw == (string) $cast) ? $cast : $raw);
                     case '-' === $scalar[0] && ctype_digit(substr($scalar, 1)):
                         $raw = $scalar;
                         $cast = (int) $scalar;
 
-                        return '0' == $scalar[1] ? octdec($scalar) : (((string) $raw === (string) $cast) ? $cast : $raw);
+                        if ('0' === $scalar[1] && !Parser::preg_match('/^[0-7]*$/', $octal = substr($scalar, 1))) {
```
Comment (cebe) [inline src/Symfony/Component/Yaml/Inline.php]: `$octal = substr($scalar, 1)` assignment could go up to line 634

**Comment by Nyholm** [comment]
@xabbuh Friendly ping

File: src/Symfony/Component/Yaml/Inline.php (hunk 1 above)
Comment (xabbuh) [reply src/Symfony/Component/Yaml/Inline.php:648]: @cebe I moved the PHP 7.4 compat fix to #36690

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.
