### PR TITLE
[HttpFoundation] Fix consistency in sessions not found exceptions

### LINKED ISSUE #40112: [HttpFoundation] Sync session not found exception
Since #38616 there's exception type variance in `getSession()` between `RequestStack` and `Request`, when the session is not found 

https://github.com/symfony/symfony/blob/a12db94a06fbfc6077c2613d479f9de559c9af03/src/Symfony/Component/HttpFoundation/RequestStack.php#L110-L112

vs.

https://github.com/symfony/symfony/blob/a12db94a06fbfc6077c2613d479f9de559c9af03/src/Symfony/Component/HttpFoundation/Request.php#L737-L738

for simplicity, i think we should throw the same exception type in Request::getSession(), and let RequestStack simply forward the call.

the `catch(BadMethodCallException)` as "cheap hasSession" will break, but we explicitly mentioned to use hasSession instead already

https://github.com/symfony/symfony/blob/f1a7dcafe0ca490fd018b54a6c99221cc0d144c2/src/Symfony/Component/HttpFoundation/Request.php#L726-L727

ppl doing it as of 5.x rely on implementation details (the `@throws BadMethodCallException` isnt documented)

so, given both are LogicException it seems reasonable :) 

cc @jderusse

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40112
| License       | MIT
| Doc PR        | -

Make `Request::getSession` thrown a `SessionNotFoundException` and make `SessionNotFoundException` extends `\BadMethodCallException` for backward compatibility and

### CODE REVIEW

File: src/Symfony/Component/HttpFoundation/Exception/SessionNotFoundException.php [hunk 1]
```diff
@@ -18,7 +18,7 @@
  *
  * @author Jérémy Derussé <jeremy@derusse.com>
  */
-class SessionNotFoundException extends \LogicException implements RequestExceptionInterface
+class SessionNotFoundException extends \BadMethodCallException implements RequestExceptionInterface
```
Comment (Nyholm) [inline src/Symfony/Component/HttpFoundation/Exception/SessionNotFoundException.php]: `BadMethodCallException` extends `BadFunctionCallException` which extends `LogicException`, so this change is OK. 

However, I don't like the fat that `SessionNotFoundException` extends `BadMethodCallException`, could we do it in another way? One that will make sure that `SessionNotFoundException` extends `LogicException` in Symfony 6?

**Review by Nyholm — CHANGES_REQUESTED** [review]
Thank you. Just one question.

File: src/Symfony/Component/HttpFoundation/Exception/SessionNotFoundException.php (hunk 1 above)
Comment (jderusse) [reply src/Symfony/Component/HttpFoundation/Exception/SessionNotFoundException.php]: note: `SessionNotFoundException` has been added in 5.3, we can change the signature without taking care of BC.

I agree, `BadMethodCallException` is not the best choice, But I don't see what to do else for solving the original issue #40112 without breaking the BC.

I'm not sure we have tools to provide migration path on exceptions. ping @nicolas-grekas

Comment (ro0NL) [reply src/Symfony/Component/HttpFoundation/Exception/SessionNotFoundException.php]: logic, bad method call .. in a way both work currently :)

strictly spoken i prefer extends Logic as well, esp. since the @throws BadMethodCallException isnt documented. So the BC issue is hypothetical to me.

Comment (jderusse) [reply src/Symfony/Component/HttpFoundation/Exception/SessionNotFoundException.php]: done

**Review by derrabus — APPROVED** [review]

File: src/Symfony/Component/HttpFoundation/CHANGELOG.md [hunk 2]
```diff
@@ -4,6 +4,7 @@ CHANGELOG
 5.3
 ---
 
+ * Calling `Request::getSession` when there is not available session throws an `SessionNotFoundException`.
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/CHANGELOG.md]: `Calling Request::getSession() when there is no available session throws a SessionNotFoundException`

Comment (jderusse) [reply src/Symfony/Component/HttpFoundation/CHANGELOG.md]: done

File: src/Symfony/Component/HttpFoundation/CHANGELOG.md [hunk 3]
```diff
@@ -4,6 +4,7 @@ CHANGELOG
 5.3
 ---
 
+ * Calling `Request::getSession()` when there is no available session throws a `SessionNotFoundException`.
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/CHANGELOG.md]: and not final dot :)

Comment (jderusse) [reply src/Symfony/Component/HttpFoundation/CHANGELOG.md]: :+1:

**Review by nicolas-grekas — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you Jérémy.
