### PR TITLE
[Validator] fix access to uninitialized property when getting value

### LINKED ISSUE #35454: [Validator] Typed property must not be accessed before initialization
**Related**: https://github.com/doctrine/orm/issues/7944

**Description**:
This is the same issue when ReflectionProperty::getValue() uses an uninitialized argument.

**How to reproduce**:
Validate an object that has an uninitialized property with type hint:
```php
    /**
     * @Assert\NotBlank()
     */
    public int $id;
```
**Possible Solution**:
Something similar to [TypedNoDefaultReflectionProperty.php](https://github.com/doctrine/reflection/blob/master/lib/Doctrine/Common/Reflection/TypedNoDefaultReflectionProperty.php)
Symfony\Component\Validator\Mapping\PropertyMetadata::getPropertyValue:
```php
    /**
     * {@inheritdoc}
     */
    public function getPropertyValue($object)
    {
        $reflectionProperty = $this->getReflectionMember($object);

        return $object !== null && $reflectionProperty->isInitialized($object) ? $reflectionProperty->getValue($object) : null;
    }
```

### PR DESCRIPTION
**Pull request by greedyivan**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35454
| License       | MIT
| Doc PR        | 

In PHP 7.4, the type-hinted property is [uninitialized](https://wiki.php.net/rfc/typed_properties_v2#uninitialized_and_unset_properties) by default. So it needs to be checked before use.

### CODE REVIEW

File: src/Symfony/Component/Validator/Mapping/PropertyMetadata.php [hunk 1]
```diff
@@ -48,7 +48,15 @@ public function __construct($class, $name)
      */
     public function getPropertyValue($object)
     {
-        return $this->getReflectionMember($object)->getValue($object);
+        $reflProperty = $this->getReflectionMember($object);
+
+        $checkPropertyInitialization = \PHP_VERSION_ID >= 70400;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Mapping/PropertyMetadata.php]: No need for the variable, should be done inline.

**Review by nicolas-grekas — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

File: src/Symfony/Component/Validator/Mapping/PropertyMetadata.php (hunk 1 above)
Comment (greedyivan) [reply src/Symfony/Component/Validator/Mapping/PropertyMetadata.php]: Done

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @greedyivan.

**Comment by realjjaveweb** [comment]
@nicolas-grekas Hi, would you mind please documenting this also here:
https://symfony.com/doc/current/reference/constraints/NotNull.html or maybe on some generic constraints/validator level?

Because there's not name of Constraint that would imply check for uninitialized property, so people often times just use
`#[Assert\NotNull]`  (`Assert` = `\Symfony\Component\Validator\Constraints`).

Which is completely fine since this commit/MR merged but it's not documented anywhere - or at least I didn't find it anywhere in the docs.
