### PR TITLE
[Messenger] Fix commands writing to `STDERR` instead of `STDOUT`

### LINKED ISSUE #60822: [Messenger] Failed messages command writes to STDERR
### Symfony version(s) affected

6.4.21

### Description

Whilst trying to investigate why we have 1000+ failed messages I tried to pipe the output from `messenger:failed:show` into a pager so I could scroll through the output, but the output is written to STDERR instead of STDOUT. Obviously I can workaround this by redirecting the output but this is not normal behaviour.

### How to reproduce

```sh
bin/console messenger:failed:show --max 10000 | less
```

Observe output is written straight out and the pager is empty.

### Possible Solution

Write the useful output to STDOUT.

### Additional Context

Seems to be a problem with other messenger commands as well:

```
web@eb.0:~$ bin/console cache:pool:list | wc -l
21
web@eb.0:~$ bin/console messenger:stats | wc -l
 ----------------------- ------- 
  Transport               Count  
 ----------------------- ------- 
  high                    0      
  low                     0      
  failed                  1583   
 ----------------------- ------- 

0
```

### PR DESCRIPTION
**Pull request by wazum**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60822
| License       | MIT

Fixes Messenger commands incorrectly routing all output to STDERR, preventing proper piping and redirection of structured data.

Updated commands to follow the established Symfony pattern (e.g., `TranslationUpdateCommand`, `ContainerLintCommand`):
- Create `$io = new SymfonyStyle($input, $output)` for primary output → **STDOUT**
- Create `$errorIo = $io->getErrorStyle()` for diagnostics → **STDERR**

**STDOUT** (parseable data):
- Tables (message lists, statistics)
- Counts ("There are X messages pending")
- Success messages
- Structured output

**STDERR** (supplementary info):
- Errors and warnings
- Informational comments/hints
- Interactive prompts and confirmations

### CODE REVIEW

File: src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php [hunk 1]
```diff
@@ -72,8 +72,10 @@ protected function getMessageId(Envelope $envelope): mixed
         return $stamp?->getId();
     }
 
-    protected function displaySingleMessage(Envelope $envelope, SymfonyStyle $io): void
+    protected function displaySingleMessage(Envelope $envelope, SymfonyStyle $io, ?SymfonyStyle $errorIo = null): void
     {
+        $errorIo ??= $io->getErrorStyle();
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php:77]: since `$errorIo` is always derived from `$io->getErrorStyle()`, I'd rather remove all the extra arguments added to method. That'd work, isn't it?

Comment (wazum) [reply src/Symfony/Component/Messenger/Command/AbstractFailedMessagesCommand.php:77]: @nicolas-grekas that would work, but creates new instances. Just tell me what you prefer, and I'll adjust the code accordingly. Thanks for the feedback.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @wazum.
