### PR TITLE
[Console] Fix EofShortcut instruction when using a modern terminal on Windows

### LINKED ISSUE #62514: [Console] SymfonyQuestionHelper gives incorrect EofShortcut instruction when using a modern terminal on Windows
### Symfony version(s) affected

5.2.0

### Description

In SymfonyQuestionHelper, if the OS is `Windows`, it always append the hint `'<comment>Ctrl+Z</comment> then <comment>Enter</comment>'`.
But in reality, unless user is running CMD or PowerShell, it should keep the `'<comment>Ctrl+D</comment>'` hint.

### How to reproduce

Using xterm / CmdEr or even the newer Windows Terminal, the following code will provide an invalid hint for the shortcut to use.

```php
$question = new Question('?');
$question->setMultiline(true);

$io = new SymfonyStyle(new ArrayInput([]), new ConsoleOutput());
$io->ask($question);
```

Nb. Only the shortcut hint is wrong, sending the actual EOF does end the multiline capture properly.

### Possible Solution

I'm not confident about the best way to detect the current term being used.
But something like this ?

```php
private function getEofShortcut(): string
{
    if ('Windows' === \PHP_OS_FAMILY) {
        // FIXME: Most likely not the right way to look at the input
        if (stream_isatty(STDIN)) {
            // Unsure how reliable this env var really is.
            $term = getenv('TERM');
            
            if ($term !== false && preg_match('/xterm|vt|linux|cygwin|msys|konsole/i', $term)) {
                return '<comment>Ctrl+D</comment>';
            }
        }
        // By default, assume CMD/PowerShell
        return '<comment>Ctrl+Z</comment> then <comment>Enter</comment>';
    }

    return '<comment>Ctrl+D</comment>';
}
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by fperxas**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62514
| License       | MIT

On `SymfonyQuestionHelper` use the `isDecoratedFlag` instead of the PHP_OS_FAMILY. @nicolas-grekas suggested to use `StreamOutput::hasColorSupport()`. As it is a protected method i thought we could use the `OutputInterface::isDecorated` flag which is constructed from `StreamOutput` like this: `$decorated ??= $this->hasColorSupport();`

Please review if it is a correct decision :)

### CODE REVIEW

File: src/Symfony/Component/Console/Helper/SymfonyQuestionHelper.php [hunk 1]
```diff
@@ -98,9 +98,9 @@ protected function writeError(OutputInterface $output, \Exception $error)
         parent::writeError($output, $error);
     }
 
-    private function getEofShortcut(): string
+    private function getEofShortcut(OutputInterface $output): string
     {
-        if ('Windows' === \PHP_OS_FAMILY) {
+        if (!$output->isDecorated()) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Helper/SymfonyQuestionHelper.php]: we still need the check for windows (see test failures):
```suggestion
        if ('\\' === \DIRECTORY_SEPARATOR && !$output->isDecorated()) {
```

**Review by nicolas-grekas — COMMENTED** [review]
did you try it locally? does it fix your issue?

**Comment by fperxas** [comment]
I have just commited the corrections.

Yes, I tested it locally but all my terminals, windows ones and linux ones have colors and their accepted eof shortcut is Ctrl+D (I have tested it with power shell, cmd, git bash, and a common linux terminal). I think that the person that opened the issue on the first place should test if the PR solves their issues.

**Comment by nicolas-grekas** [comment]
Thank you @fperxas
