### PR TITLE
[RateLimiter] Add support for long intervals (months and years)

### LINKED ISSUE #42784: [RateLimiter] It does not work with long intervals (1 month, 1 year)
**Symfony version(s) affected**: 5.3, but seems that it does not work in any newer version (5.4, 6.0).

**Description**
Rate limit does not work with long intervals (1 month, 1 year). 1 year is transformed to 0 seconds so it basically does not limit anything.

**How to reproduce**
Set rate limit 1 and interval 1 year. Send multiple requests - none of them is stopped.

```yaml
framework:
    rate_limiter:
        anonymous_api:
            policy: 'fixed_window'
            limit: 1
            interval: '1 year'
```

```php
// src/Controller/ApiController.php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\TooManyRequestsHttpException;
use Symfony\Component\RateLimiter\RateLimiterFactory;

class ApiController extends AbstractController
{
    public function index(Request $request, RateLimiterFactory $anonymousApiLimiter)
    {
        $limiter = $anonymousApiLimiter->create($request->getClientIp());
        if (false === $limiter->consume(1)->isAccepted()) {
            throw new TooManyRequestsHttpException();
        }
    }
}
```

**Possible Solution**

It is caused by https://github.com/symfony/rate-limiter/blob/d00d756e2c9f9c8cc7964c19e619bfe19702559a/Util/TimeUtil.php#L21-L28 because it uses only seconds, minutes, hours and days to compute number of seconds from DateInterval. It ignores months and years.

I suggest to deduct timestamps to compute number of seconds:
```php
public static function dateIntervalToSeconds(\DateInterval $interval): int
{
    $now = new DateTimeImmutable();

    return $now->add($interval)->getTimestamp() - $now->getTimestamp();
}
```

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #42784
| License       | MIT
| Doc PR        | _NA_

As mentioned in the issue and as found on Stackoverflow, we may use timestamps instead of converting `DateInterval` properties to seconds.

### CODE REVIEW

**Comment by derrabus** [comment]
Tests please. 🙂

**Comment by alexandre-daubois** [comment]
@derrabus indeed! Wasn't sure which tests to add though. But I'll definitely try to find some! 😄

**Comment by derrabus** [comment]
Well, you should be able to come up with a test that fails on 5.4 and passes after your changes. After all, you're fixing a problem here. 😎

**Comment by alexandre-daubois** [comment]
Oh yeah of course you're right! Just added them. If you see anything else, please tell me!

Speaking of that, should this be rebased to 5.3 as a bug fix or is it considered as a feature and 5.4 is fine?

**Comment by fabpot** [comment]
That’s a new feature

File: src/Symfony/Component/RateLimiter/Tests/Util/TimeUtilTest.php [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+{
+    public function provideTimeUtilData(): \Generator
+    {
+        yield ['PT5S', 5];
+
+        yield ['PT1M5S', 65];
+
+        yield ['PT2H4M', 2 * 3600 + 4 * 60];
+
+        yield ['P1Y', 24 * 3600 * 365];
```
Comment (derrabus) [inline src/Symfony/Component/RateLimiter/Tests/Util/TimeUtilTest.php]: I would expect that this test will start to fail on March 1st, 2023. 🤓

Comment (alexandre-daubois) [reply src/Symfony/Component/RateLimiter/Tests/Util/TimeUtilTest.php]: I'm struggling a bit with these tests, as months and years, of course, may have different number of days. Any advice welcome about this one!

Comment (derrabus) [reply src/Symfony/Component/RateLimiter/Tests/Util/TimeUtilTest.php]: Is the variable length of the limit desired? So far, the rate limiter worked with fixed lengths, IIRC. We would change that now.

Comment (alexandre-daubois) [reply src/Symfony/Component/RateLimiter/Tests/Util/TimeUtilTest.php]: I'm wondering if it's worth testing this method doing a simple timestamp operation. What I mean is if it changes, `FixedWindowLimiter` tests and similar will break, as I updated `FixedWindowLimiterTest` with long intervals too.

The lack of tests on `TimeUtil` currently makes me wonder even more.

File: src/Symfony/Component/RateLimiter/CHANGELOG.md [hunk 2]
```diff
@@ -5,6 +5,7 @@ CHANGELOG
 ---
 
  * The component is not experimental anymore
+ * Add support of long intervals (months and years)
```
Comment (OskarStark) [inline src/Symfony/Component/RateLimiter/CHANGELOG.md]:
```suggestion
 * Add support for long intervals (months and years)
```

Comment (alexandre-daubois) [reply src/Symfony/Component/RateLimiter/CHANGELOG.md]: Of course, fixed. Thanks, Oskar!

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @alexandre-daubois.
