### PR TITLE
[Debug] Display more details in the simple error page of Debug

### LINKED ISSUE #29891: Improve the way exceptions are listed in the error page
**Description**  
The order in which multiple exceptions are displayed in the error page is sometimes confusing.

**Example**  
If you make a mistake in the `config/services.yaml` file of the Symfony Demo app, you see this:

exception

There is a perfect exception message that tells you exactly what happened ... but it's "buried" so low, that you probably won't see it.

If we reverse the order of exceptions in this case, the error page would be much better.

The above has happened to me several times with different errors ... but the opposite too: sometimes the current order is the best order. So:

* Should we reverse the order of exceptions in the error page in all cases?
* Is this a matter of tweaking some but not all exceptions?

Thanks!

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #29891
| License       | MIT
| Doc PR        | -

Note: this only changes the simple error page of Debug component, which is different from the full-featured error page of WebProfilerBundle.

-----

#29891 shows a confusing error page. In #29928 we improved the first error message displayed to the user. In this PR we implement @nicolas-grekas' idea to replace the generic error page title by a better error message. So, this PR + #29928 would fix #29891 to me.

### Before

error-before

### After

error-after

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
But much more prominent

File: src/Symfony/Component/Debug/ExceptionHandler.php [hunk 1]
```diff
@@ -207,7 +207,7 @@ public function getContent(FlattenException $exception)
                 $title = 'Sorry, the page you are looking for could not be found.';
                 break;
             default:
-                $title = 'Whoops, looks like something went wrong.';
+                $title = $this->debug ? $exception->getMessage() : 'Whoops, looks like something went wrong.';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Debug/ExceptionHandler.php]: XSS my love :)

File: src/Symfony/Component/Debug/ExceptionHandler.php [hunk 2]
```diff
@@ -207,7 +207,7 @@ public function getContent(FlattenException $exception)
                 $title = 'Sorry, the page you are looking for could not be found.';
                 break;
             default:
-                $title = $this->debug ? $exception->getMessage() : 'Whoops, looks like something went wrong.';
+                $title = $this->debug ? htmlspecialchars($exception->getMessage(), ENT_QUOTES, 'UTF-8') : 'Whoops, looks like something went wrong.';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Debug/ExceptionHandler.php]: we should use `$this->escapeHtml` instead, it deals with charsets properly

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @javiereguiluz.
