### PR TITLE
[Cache] Add server-commands support for Predis Replication Environments

### LINKED ISSUE #35867: The Redis INFO command called in RedisTrait::doClear can fail: "The command 'INFO' is not allowed in replication mode."
**Symfony version(s) affected**: 4.4, 5.0

**Description**  
In `\Symfony\Component\Cache\Traits\RedisTrait::doClear` there's a method call `$host->info('Server')` which executes the Redis `INFO` command.

Currently there's no exception handling on this call, but I think there should as this command can throw an exception, at least the following:

> The command 'INFO' is not allowed in replication mode.

**How to reproduce**  
I'm not sure how to easily reproduce this issue. I see the logs in production, but only occasionally, so it only occurs when the Redis instance(s) are in replication mode, which is not all the time, since the error doesn't usually happen.

**Possible Solution**  
Add a `try catch` statement to defend against the possible failing of this call and to not interfere with clearing the cache.

**Additional context**  
The full log message I currenly get is the following (I use the Predis client):

> The command 'INFO' is not allowed in replication mode. {"exception":"[object] (Predis\\NotSupportedException(code: 0): The command 'INFO' is not allowed in replication mode.

### PR DESCRIPTION
**Pull request by DemigodCode**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35867
| License       | MIT
| Doc PR        | 

This fix is for predis MasterSlaveConnections which don't allow to run server commands.
Due to that it's not possible to e.g. clear a cache with cache:pool:clear.

PhpRedis and Predis do not have the same interface, so have to check which implementation is used.
Furthermore, the getClientFor('master') works only for replicated redis instances.

### CODE REVIEW

File: src/Symfony/Component/Cache/Traits/RedisTrait.php [hunk 1]
```diff
@@ -368,6 +370,12 @@ protected function doClear($namespace)
         }
 
         foreach ($this->getHosts() as $host) {
+            if ($host instanceof ClientInterface && $host->getConnection() instanceof ReplicationInterface && method_exists($host, 'getClientFor')) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Cache/Traits/RedisTrait.php]: this would be cleaner I think:
`if ($host instanceof Client && $host->getConnection() instanceof ReplicationInterface) {`

I'm wondering: when we hit the master, there is no need anymore to loop on the other hosts, isn't it?
can we do this check outside of the foreach then, and replace `$this->getHosts()` with `$hosts = [$master]` when this happens?

File: src/Symfony/Component/Cache/Adapter/RedisTagAwareAdapter.php [hunk 2]
```diff
@@ -279,6 +281,11 @@ private function getRedisEvictionPolicy(): string
         }
 
         foreach ($this->getHosts() as $host) {
+            if ($host instanceof ClientInterface && $host->getConnection() instanceof ReplicationInterface && method_exists($host, 'getClientFor')) {
+                // As discussed (https://github.com/predis/predis/issues/598#issuecomment-671876712) predis won't allow any
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Cache/Adapter/RedisTagAwareAdapter.php]: please remove the link to github (same below), we don't track this in the source (git[hub] history FTW)

File: src/Symfony/Component/Cache/Traits/RedisTrait.php (hunk 1 above)
Comment (DemigodCode) [reply src/Symfony/Component/Cache/Traits/RedisTrait.php]: > I'm wondering: when we hit the master, there is no need anymore to loop on the other hosts, isn't it?

Sounds good to me. Thought about multi-master replication, but they are converged asynchronously anyway.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @DemigodCode.
