### PR TITLE
[TypeInfo] use an EOL-agnostic approach to parse class uses

### LINKED ISSUE #60906: [TypeInfo] `TypeContextFactory::collectUses` returns values with `;`
### Symfony version(s) affected

7.3.0

### Description

I'm trying to upgrade from Symfony 6.4 to 7.3, but the Serializer is failing to recognize nested Types. Upon deeper inspection it turned out that the `TypeContextFactory::collectUses` is gathering values with `;`. 

Im running on WSL with PHP 8.4.8. I've cloned the Property Info Component and uppon running 
```
 php vendor/bin/phpunit --filter testCollectUses Tests/TypeContext/TypeContextFactoryTest.php
```

I'm getting the following failure:

```
1) Symfony\Component\TypeInfo\Tests\TypeContext\TypeContextFactoryTest::testCollectUses
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
 Array &0 [
-    'Type' => 'Symfony\Component\TypeInfo\Type',
-    'DateTimeInterface' => '\DateTimeInterface',
-    'DateTime' => '\DateTimeImmutable',
+    'Type;' => 'Symfony\Component\TypeInfo\Type;',
+    'DateTimeInterface;' => '\DateTimeInterface;',
+    'DateTime;' => '\DateTimeImmutable',
 ]

/home/exsio/dev/type-info/Tests/TypeContext/TypeContextFactoryTest.php:83

FAILURES!
Tests: 1, Assertions: 2, Failures: 1, PHPUnit Deprecations: 1.
```

This is a complete migration blocker for me.

### How to reproduce

1. Install PHP 8.4.8
2. Run `php vendor/bin/phpunit --filter testCollectUses Tests/TypeContext/TypeContextFactoryTest.php`

This may be failing only on WSL, not sure about native distro.

### Possible Solution

Modify `TypeContextFactory` on line `139` and replace

```
$uses[$alias] = $use[0];
```

with

```
$uses[str_replace(";","", $alias)] = str_replace(";","", $use[0]);
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60906
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/TypeInfo/Tests/TypeContext/TypeContextFactoryTest.php [hunk 1]
```diff
@@ -82,6 +83,22 @@ public function testCollectUses()
         $this->assertEquals($uses, $this->typeContextFactory->createFromReflection(new \ReflectionParameter([DummyWithUses::class, 'setCreatedAt'], 'createdAt'))->uses);
     }
 
+    public function testCollectUsesWindowsLineEndings()
+    {
```
Comment (stof) [inline src/Symfony/Component/TypeInfo/Tests/TypeContext/TypeContextFactoryTest.php:87]: I suggest adding an assertion that the `DummyWithUsesWindowsLineEndings.php` file contains `\r\n`, to avoid having someone changing the line endings (by mistake or intentionally) and making this test useless.
This could happen for instance for contributors on Windows using git's newline conversion features (maybe we could even avoid that specific case with a `.gitattributes` telling git we want Windows line endings in this specific file)

Comment (xabbuh) [reply src/Symfony/Component/TypeInfo/Tests/TypeContext/TypeContextFactoryTest.php:87]: I added both the assertion inside the test as well as entries to the relevant `.gitattributes` files

File: .gitattributes [hunk 2]
```diff
@@ -7,5 +7,6 @@
 /src/Symfony/Component/Translation/Bridge export-ignore
 /src/Symfony/Component/Emoji/Resources/data/* linguist-generated=true
 /src/Symfony/Component/Intl/Resources/data/*/* linguist-generated=true
+/src/Symfony/Component/TypeInfo/Tests/Fixtures/DummyWithUsesWindowsLineEndings.php text eol=crlf
```
Comment (stof) [inline .gitattributes]: I don't think we need this if `src/Symfony/Component/TypeInfo/.gitattributes` already defines it

Comment (xabbuh) [reply .gitattributes]: Are you sure that `src/Symfony/Component/TypeInfo/.gitattributes` is evaluated when the mono-repo is checked out?

Comment (stof) [reply .gitattributes]: yes. git respects all `.gitattributes` files, not just the file at the root of the repo (same for `.gitignore` files)

Comment (xabbuh) [reply .gitattributes]: alright 👍 I reverted this change

**Review by mtarld — APPROVED** [review]

**Review by stof — APPROVED** [review]

**Comment by stof** [comment]
Thank you @xabbuh.
