### PR TITLE
[DoctrineBridge] Fix the `LockStoreSchemaListener`

### LINKED ISSUE #54406: [DoctrineBridge] LockStoreSchemaListener not working properly
### Symfony version(s) affected

6.4.4

### Description

After installing `symfony/lock` and configuring it with `DoctrineDbalStore`, I noticed that invoking `doctrine:migrations:diff` command would generate a migration issuing a `DROP` of the autogenerated `lock_keys` table.

After investigating, I found out the issue is [line 33 of the listener](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bridge/Doctrine/SchemaListener/LockStoreSchemaListener.php#L33). The `$stores` property receives a `RewindableGenerator`, which is then passed directly to an `ArrayIterator`. This produces an invalid iterator, skipping the whole following `while` loop.

### How to reproduce

1. Configure `symfony/lock` with a `DoctrineDbalStore`.
2. Generate the `lock_keys` table, either by using the `LockFactory` or by any other means mentioned in the [docs](https://symfony.com/doc/current/components/lock.html#doctrinedbalstore).
3. Run the `doctrine:migrations:diff` command.
4. See that the the schema for the table is not properly configured, resulting in a migration instead of the expected `No changes detected in your mapping information.` message.

### Possible Solution

Since the `$stores` property is already typed as `iterable`, it would seem replacing the loop with a `foreach` iterating directly on the property would be the best solution.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54406 
| License       | MIT

#54407 got sidetracked ~and @barton-webwings seems no longer active on GitHub~ so this PR takes over.

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/Tests/SchemaListener/LockStoreSchemaListenerTest.php [hunk 1]
```diff
@@ -40,20 +39,4 @@ public function testPostGenerateSchemaLockPdo()
         $subscriber = new LockStoreSchemaListener([$lockStore]);
         $subscriber->postGenerateSchema($event);
     }
-
-    public function testPostGenerateSchemaWithInvalidLockStore()
```
Comment (derrabus) [inline src/Symfony/Bridge/Doctrine/Tests/SchemaListener/LockStoreSchemaListenerTest.php:44]: Maybe I'm a bit late to the party and missed an important part of the discussion of the previous PR. But… could you recap why we _delete_ a test for a bugfix? I would've expected a _new_ test instead that covers the bug that we want to fix.

Comment (xabbuh) [reply src/Symfony/Bridge/Doctrine/Tests/SchemaListener/LockStoreSchemaListenerTest.php:44]: @MatTheCat wrote done his reasoning here: https://github.com/symfony/symfony/pull/54407#issuecomment-2269032034

Comment (MatTheCat) [reply src/Symfony/Bridge/Doctrine/Tests/SchemaListener/LockStoreSchemaListenerTest.php:44]: (I updated the `testPostGenerateSchemaLockPdo` so that it would fail.)

Comment (MatTheCat) [reply src/Symfony/Bridge/Doctrine/Tests/SchemaListener/LockStoreSchemaListenerTest.php:44]: You can see `testPostGenerateSchemaWithInvalidLockStore` is wrong because the function creating the generator is `static`, but its body is using `$this`. That means it only passes because the generator is not started and the `LockStoreSchemaListener` does not get any store.

**Review by nicolas-grekas — APPROVED** [review]
/cc @alexandre-daubois FYI

**Comment by nicolas-grekas** [comment]
Thank you @MatTheCat.
