### PR TITLE
[Messenger] Allow using user's serializer for message do not fit the expected JSON structure

### LINKED ISSUE #42072: [Messenger] [Redis] Can not consume messages published by third party in Redis
**Symfony version(s) affected**: 5.2

**Description**
I try to consume messages from a Redis Stream which are published by a third party, but messages do not follow the expected structure from the Redis Bridge.

Accordingly to the code https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php#L398-L408

Messages have to be structured like: 
```json
{
    "message": {
        "body": {},
        "headers": []
    }
}
```

However, my messages doesn't look like this, but more like:

```json
{
    "field1": "value1",
    "field2": "value2"
}
```

**How to reproduce**
Use Redis Insight to push a message like 
```json
{
    "field1": "value1",
    "field2": "value2"
}
```

into a Stream, then consume this stream with symfony/redis-messenger.

Catch this error:

```
messenger:consume [-l|--limit LIMIT] [-f|--failure-limit FAILURE-LIMIT] [-m|--memory-limit MEMORY-LIMIT] [-t|--time-limit TIME-LIMIT] [--sleep SLEEP] [-b|--bus BUS] [--] [<receivers>...]


 [OK] Consuming messages from transports "catalog_import".

 // The worker will automatically exit once it has exceeded 128M of memory or
 // received a stop signal via the messenger:stop-workers command.

 // Quit the worker with CONTROL-C.

 // Re-run the command with a -vv option to see logs about consumed messages.


In Connection.php line 399:

  Notice: Undefined index: message


messenger:consume [-l|--limit LIMIT] [-f|--failure-limit FAILURE-LIMIT] [-m|--memory-limit MEMORY-LIMIT] [-t|--time-limit TIME-LIMIT] [--sleep SLEEP] [-b|--bus BUS] [--] [<receivers>...]
```

**Possible Solution**
A possible solution could be to determine the existence of the key `message` in `$message` array, and if not exists, return the raw message, which could be decoded by a custom serializer.

cc @lyrixx @sroze

### PR DESCRIPTION
**Pull request by welcoMattic**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix https://github.com/symfony/symfony/issues/42072
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

It allows user to use their own serializer to decode messages that do not fit the expected JSON structure (`{ "message": { "body": "", "headers": {} } }`).

Once this PR will be ok, I'll report the fix in Beanstalkd, SQS, and Doctrine Transports

### CODE REVIEW

File: src/Symfony/Component/Messenger/Transport/Serialization/PhpSerializer.php [hunk 1]
```diff
@@ -25,6 +25,10 @@ class PhpSerializer implements SerializerInterface
      */
     public function decode(array $encodedEnvelope): Envelope
     {
+        if (!\array_key_exists('body', $encodedEnvelope)) {
+            throw new MessageDecodingFailedException(__CLASS__.' only supports envelope with "body" index. Maybe you should implement your own serializer?');
+        }
```
Comment (chalasr) [inline src/Symfony/Component/Messenger/Transport/Serialization/PhpSerializer.php]: Given that the `empty()` check below already covers the case where the key does not exist, could we just change the message of the exception thrown there instead of adding another one?

**Comment by welcoMattic** [comment]
Status: Needs review

**Comment by welcoMattic** [comment]
@carsonbot find me a reviewer please (I'm discovering that Carson can do more things than automate status in reaction to git actions :smile: )

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/RedisReceiver.php [hunk 2]
```diff
@@ -38,24 +38,34 @@ public function __construct(Connection $connection, SerializerInterface $seriali
...
+
+        if (\array_key_exists('message', $message)) {
+            $redisEnvelope = json_decode($message['message'], true);
+        } else {
+            $redisEnvelope = $message;
+        }
 
         if (null === $redisEnvelope) {
             return [];
         }
```
Comment (alexander-schranz) [inline src/Symfony/Component/Messenger/Bridge/Redis/Transport/RedisReceiver.php]: For me it looks like the `get` returns now `null` or `array{id: string, message: string}` so I think the check for `message` is unnecessary as it always exists if the return value is not null:

```suggestion
        $message = $this->connection->get();
        
        if (null === $message) {
            return [];
        }

        $redisEnvelope = \json_decode($message['message'], true);
```

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php [hunk 3]
```diff
@@ -397,12 +397,9 @@ public function get(): ?array
         }
 
         foreach ($messages[$this->stream] ?? [] as $key => $message) {
-            $redisEnvelope = json_decode($message['message'], true);
-
             return [
                 'id' => $key,
-                'body' => $redisEnvelope['body'],
-                'headers' => $redisEnvelope['headers'],
+                'message' => $message,
```
Comment (alexander-schranz) [inline src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: Not sure, but I personally would use here another word then `message`. I would go then here with `content` or `envelope` to avoid the `$message['message']['message']` now its a little bit confusing inside the tests.

**Review by alexander-schranz — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php (hunk 3 above)
Comment (welcoMattic) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: I agree, it's a bit messy. I've just replaced with `data`

Comment (alexander-schranz) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php]: Is also fine for me :)

**Comment by welcoMattic** [comment]
Status: Needs review

**Comment by welcoMattic** [comment]
This PR is ready to be reviewed

**Review by lyrixx — APPROVED** [review]
Looks good to me but I didn't test it

**Review by alexander-schranz — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Merging in 5.4 as this is a new feature.

**Comment by fabpot** [comment]
Thank you @welcoMattic.

**Comment by alexander-schranz** [comment]
@welcoMattic Good work 👍
