### PR TITLE
[PropertyAccess] Improve message of unitialized property in php 7.4

### LINKED ISSUE #36277: Unclear exception message in Symfony\Component\PropertyAccess\Exception\AccessException;
**Symfony version(s) affected**: >= 3.4

**Description**  
When PHP 7.4 typed property is accessed in form before initialization Symfony throws an exception with a message `The property "App\Form\Model\ContactFormModel::$firstName" is not readable because it is typed "string". You should either initialize it or make it nullable using "?string" instead.` which is entirely not true.

If I have this in my model:
```php
/**
 * @Assert\NotBlank
 */
public string $firstname;
```

And will make it this according to the message:
```php
/**
 * @Assert\NotBlank
 */
public ?string $firstname;
```

The error is still there since I need to make it this
```php
/**
 * @Assert\NotBlank
 */
public ?string $firstname = null;
```

**How to reproduce**  
Create a model with below code, use it in a form, render the form and try to fix the error by the exception message instructions.

```php
/**
 * @Assert\NotBlank
 */
public string $firstname;
```

**Possible Solution**  
Improve the error message, I will provide the PR. What do you think about `The property "App\Form\Model\ContactFormModel::$firstName" is not readable because it is typed "string". You should either initialize it or make it nullable using "?string" **and initialize it to null** instead.`?

### PR DESCRIPTION
**Pull request by lmasforne**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36277 
| License       | MIT

Improve message of unitialized property in php 7.4 ; 
Before 
You should either initialize it or make it nullable using "?string" instead.
After 
You should either initialize it or make it nullable using "?string $var = null" instead.

### CODE REVIEW

**Comment by ro0NL** [comment]
the message could be simply `You should initialize it or declare a default value`. Welcome to php74 :grin: 

advertising to make it nullable is not a Symfony concern IMHO, but rather a business one.

**Comment by lmasforne** [comment]
@ro0NL i'm ok with you but if that could help people to debug quickly their codes, i'm ok to improve message of the exception ;)

File: src/Symfony/Component/PropertyAccess/PropertyAccessor.php [hunk 1]
```diff
@@ -505,7 +505,7 @@ private function readProperty($zval, $property)
             if (\PHP_VERSION_ID >= 70400 && preg_match('/^Typed property ([\w\\\]+)::\$(\w+) must not be accessed before initialization$/', $e->getMessage(), $matches)) {
                 $r = new \ReflectionProperty($matches[1], $matches[2]);
 
-                throw new AccessException(sprintf('The property "%s::$%s" is not readable because it is typed "%3$s". You should either initialize it or make it nullable using "?%3$s" instead.', $r->getDeclaringClass()->getName(), $r->getName(), $r->getType()->getName()), 0, $e);
+                throw new AccessException(sprintf('The property "%s::$%s" is not readable because it is typed "%3$s". You should either initialize it or make it nullable using "?%3$s $var = null" instead.', $r->getDeclaringClass()->getName(), $r->getName(), $r->getType()->getName()), 0, $e);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/PropertyAccess/PropertyAccessor.php:508]: `You should either initialize it or make it default to null using "?%3$s $%2$s = null instead.`

Comment (lmasforne) [reply src/Symfony/Component/PropertyAccess/PropertyAccessor.php]: Yes it's better ;) PR feedback ok for me, thanks.

**Comment by dunglas** [comment]
I agree with @ro0NL, we shouldn't encourage people to make the property nullable (it defects the new typed properties feature). Could you update the message as suggested by Roland?

**Comment by lmasforne** [comment]
Yep no problem ;) it's done @dunglas

**Review by HeahDude — APPROVED** [review]
LGTM thanks!

**Review by azjezz — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @lmasforne.
