### PR TITLE
[Messenger] choose the proper array element to decode the message

### LINKED ISSUE #43618: json_decode issue on RedisReceiver
**Symfony version(s) affected**: 5.4

**Description**
Not sure if it's a bug, but when I consume a message, I get the error "Warning: json_decode() expects parameter 1 to be string, array given", because https://github.com/symfony/redis-messenger/blob/5.4/Transport/RedisReceiver.php#L47 is getting $message['data'] instead $message['data']['message'].

This is the $message value at this point:

```
Array
(
    [id] => 1634746225533-0
    [data] => Array
        (
            [message] => {"body":"O:36:\\\"Symfony\\\\Component\\\\Messenger\\\\Envelope\\\":2:{s:44:\\\"\\0Symfony\\\\Component\\\\Messenger\\\\Envelope\\0stamps\\\";a:1:{s:46:\\\"Symfony\\\\Component\\\\Messenger\\\\Stamp\\\\BusNameStamp\\\";a:1:{i:0;O:46:\\\"Symfony\\\\Component\\\\Messenger\\\\Stamp\\\\BusNameStamp\\\":1:{s:55:\\\"\\0Symfony\\\\Component\\\\Messenger\\\\Stamp\\\\BusNameStamp\\0busName\\\";s:21:\\\"messenger.bus.default\\\";}}}s:45:\\\"\\0Symfony\\\\Component\\\\Messenger\\\\Envelope\\0message\\\";O:58:\\\"Ekt\\\\NotificationBundle\\\\Messenger\\\\Messages\\\\PushNotification\\\":0:{}}","headers":[]}
        )
)
```

**How to reproduce**

**Possible Solution**
Using $message['data']['message'] solves the issue in my case.

**Additional context**

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #43618
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
ping @welcoMattic as you wrote the initial implementation in #42257

File: src/Symfony/Component/Messenger/Bridge/Redis/Transport/RedisReceiver.php [hunk 1]
```diff
@@ -44,7 +44,7 @@ public function get(): iterable
             return [];
         }
 
-        $redisEnvelope = json_decode($message['data'], true);
+        $redisEnvelope = json_decode($message['data']['message'] ?? '', true);
```
Comment (chalasr) [inline src/Symfony/Component/Messenger/Bridge/Redis/Transport/RedisReceiver.php:47]: What about
```suggestion
        $redisEnvelope = json_decode($message['data']['message'] ?? $message['data'] ?? '', true);
```
instead?

Comment (welcoMattic) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/RedisReceiver.php:47]: It can be a solution, indeed :+1:

Comment (xabbuh) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/RedisReceiver.php:47]: How can a message end up in the queue that doesn't have this `message` key?

Comment (welcoMattic) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/RedisReceiver.php:47]: ~Because a message can be posted by any other system than a Symfony app, and not follow the rule to have a `message` key. The only thing that we are sure, is that a data in `$message['data']` is JSON encoded. Then, we can' be sure that it contains `body` or `headers` or something else.~

Ok, my bad, I miss something. You are right, Redis gives us mandatory a `message` key, which can contains anything (not necessarily `body` and `headers`). So your fix is good :+1:

Comment (chalasr) [reply src/Symfony/Component/Messenger/Bridge/Redis/Transport/RedisReceiver.php:47]: got it

**Review by chalasr — APPROVED** [review]

**Review by welcoMattic — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.
