### PR TITLE
[Serializer] [ObjectNormalizer] Use bool filter when FILTER_BOOL is set

### LINKED ISSUE #57540: MapQueryString mapped wrong on boolean values
### Symfony version(s) affected

7.1

### Description

Recently, with #54153 , support for boolean values on DTOs have been added within the `#[MapQueryString]`.

I recently ran into an issue, where the paramter value `false` was mistakenly interpreted as `true`.

### How to reproduce

While this works:

```php

final readonly class SearchDto
{
    public function __construct(public ?bool $restricted = null)
    {
    }
}

final class MyController
{
    #[Route(name: 'search', path: '/search')]
    public function __invoke(#[MapQueryString] SearchDto $search): Response
    {
        // /search?restricted=
        // "false" would be converted to false
    }
}
```

This doesn't work:
```php

final readonly class SearchDto
{
    public ?bool $restricted = null;
}

final class MyController
{
    #[Route(name: 'search', path: '/search')]
    public function __invoke(#[MapQueryString] SearchDto $search): Response
    {
        // /search?restricted=
        // "false" would be converted to true
    }
}
```

Other conversions work.

Applying a serialization context with the `FILTER_BOOL` flag aren't working too.
This also might be related to #57487.

### Possible Solution

Looks like the `applyFilterBool` function is not called within `AbstractNormalizer`, if no constructor is given. Other assertions / convertions seems to work in DTOs, even if no constructor given. 

### Additional Context

Not using constructor works for all other use cases I've tested. With constructor we had issues with enums, why we used the solution like here

### PR DESCRIPTION
**Pull request by mazumba-nx**
| Q             | A
| ------------- | ---
| Branch?       | 7.1 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #57540 
| License       | MIT

With 7.1 it is possible to map query booleans to php bool parameters (https://symfony.com/blog/new-in-symfony-7-1-misc-improvements-part-3#mapping-boolean-query-string-parameters). But as we found out, this only works when the DTO is initialized via `construct`. Otherwise the `FILTER_BOOL` flag will be ignored and e.g. "false" will be deserialized as `true`.

To fix this, I suggest to look for the `FILTER_BOOL` in the context and apply the filter, when the type is `bool` and the data is `string`.

### CODE REVIEW

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php [hunk 1]
```diff
@@ -1195,6 +1195,34 @@ public function provideBooleanTypesData()
...
+    public function testDenormalizeBooleanTypeWithFilterBool(array $data, ?bool $expectedFoo)
+    {
+        $normalizer = new AbstractObjectNormalizerWithMetadataAndPropertyTypeExtractors();
+
+        $dummy = $normalizer->denormalize($data, BoolPropertyDummy::class, null, [AbstractNormalizer::FILTER_BOOL => true]);
+
+        $this->assertSame($expectedFoo, $dummy->foo);
+    }
+
+    public function provideDenormalizeWithFilterBoolData()
```
Comment (OskarStark) [inline src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]:
```suggestion
    public function provideDenormalizeWithFilterBoolData(): array
```

**Review by xabbuh — APPROVED** [review]
LGTM

**Comment by nicolas-grekas** [comment]
Thank you @mazumba-nx.

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php (hunk 1 above)
Comment (mazumba-nx) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: I wanted to be downwards compatible regarding the php versions, thats why I didn't add the `: array`
