### PR TITLE
[DI] Fix not working if only "default_index_method" used

### LINKED ISSUE #35349: default_index_method mishandles "numeric" strings
**Symfony version(s) affected**: 4.4.0

**Description**  
Creating a tagged locator with `default_index_method` set to a method name returning numbers encoded as strings (e.g. `"123"`), does not work. It reindexes each entry as a numerical list starting from 0 instead of using the values supplied by the index method.

**How to reproduce**  
```yaml
services:
    _instanceof:
        My\Service:
            tags: [foo]

    My\ServiceAggregator:
        arguments:
            $foos: !tagged_locator { tag: foo, default_index_method: getId }
```

**Additional context**  
Debugging shows `My\Service::getId` is actually called at container creation time, and it receives the correct value, but ends up discarding it at some point. That point is exactly [here](https://github.com/symfony/symfony/blob/b350c80fc3572c9affa998f26ebcd1635b7ad32b/src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php#L133), where it does an `array_merge`, which according to the docs:

> Values in the input arrays with numeric keys will be renumbered with incrementing keys starting from zero in the result array. 

This is the beaviour I'm seeing.

### PR DESCRIPTION
**Pull request by malteschlueter**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35349
| License       | MIT

The default index method wasn't used if the "index_by" attribute is missing. The documentation is showing an example, see https://symfony.com/doc/current/service_container/tags.html#tagged-services-with-index.

This problem also appears in symfony 5.

I created two example projects, the first in the current behaviour and the second with my bugfix branch.

Current 4.4: https://github.com/malteschlueter/symfony-reproducers/blob/bugfix/dependency-injection-default-index-method-not-working--not-fixed/tests/HandlerCollectionTest.php

This bugfix branch: https://github.com/malteschlueter/symfony-reproducers/blob/bugfix/dependency-injection-default-index-method-not-working--with-fix/tests/HandlerCollectionTest.php

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php [hunk 1]
```diff
@@ -116,24 +116,29 @@ class PriorityTaggedServiceUtil
...
         }
 
+        $messageAttributeMissing = '';
+        if (null !== $indexAttribute) {
+            $messageAttributeMissing = sprintf(' or tag "%s" on service "%s" is missing attribute "%s"', $tagName, $serviceId, $indexAttribute);
+        }
+
         if (!($rm = $r->getMethod($defaultIndexMethod))->isStatic()) {
-            throw new InvalidArgumentException(sprintf('Either method "%s::%s()" should be static or tag "%s" on service "%s" is missing attribute "%s".', $class, $defaultIndexMethod, $tagName, $serviceId, $indexAttribute));
+            throw new InvalidArgumentException(sprintf('Either method "%s::%s()" should be static%s.', $class, $defaultIndexMethod, $messageAttributeMissing));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php]: better add the final dot in $messageAttributeMissing and concat $messageAttributeMissing to the sprintf instead of using `%s`, that will help fix fabbot failures.

Comment (malteschlueter) [reply src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php]: Do you mean like this?
```suggestion
            throw new InvalidArgumentException(sprintf('Either method "%s::%s()" should be static', $class, $defaultIndexMethod).$messageAttributeMissing);
```
And of course i will add the final dot to `$messageAttributeMissing`

Comment (malteschlueter) [reply src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php]: I updated it now like this :)

But now the fabbot is failing :/ My first version failed not i think. 

Should i revert it or add the additional information as an independent sentence?

File: src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php [hunk 2]
```diff
@@ -116,24 +116,29 @@ class PriorityTaggedServiceUtil
...
         }
 
+        $messageAttributeMissing = '.';
+        if (null !== $indexAttribute) {
+            $messageAttributeMissing = sprintf(' or tag "%s" on service "%s" is missing attribute "%s".', $tagName, $serviceId, $indexAttribute);
+        }
+
         if (!($rm = $r->getMethod($defaultIndexMethod))->isStatic()) {
-            throw new InvalidArgumentException(sprintf('Either method "%s::%s()" should be static or tag "%s" on service "%s" is missing attribute "%s".', $class, $defaultIndexMethod, $tagName, $serviceId, $indexAttribute));
+            throw new InvalidArgumentException(sprintf('Either method "%s::%s()" should be static', $class, $defaultIndexMethod).$messageAttributeMissing);
```
Comment (jderusse) [inline src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php]: Would be great to have a test that check errors messages with and without attributes

File: src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php (hunk 1 above)
Comment (malteschlueter) [reply src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php]: Fabbot changed it then to the following:
```suggestion
            throw new InvalidArgumentException(sprintf('Either method "%s::%s()" should be static.', $class, $defaultIndexMethod).$messageAttributeMissing);
```
So the `.` would be double.

File: src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php (hunk 2 above)
Comment (malteschlueter) [reply src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php]: I added some :)

**Review by nicolas-grekas — APPROVED** [review]
I updated the implementation to improve the error messages and fix the behavior specifically when an index method is defined.
Tests are now green.

**Comment by malteschlueter** [comment]
Thank you very much for your support @nicolas-grekas!

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @malteschlueter.
