### PR TITLE
[PropertyInfo] Fix phpDocExtractor nullable array value type

### LINKED ISSUE #49555: [PropertyInfo] Nullable array value types and multiple key/value types not returned with PhpDocExtractor
### Symfony version(s) affected

5.3 - 6.3

### Description

PhpDocExtractor is not able to return nullable array value types and throws exception with invalid class name/invalid type. Example phpDoc:

```
/**
 * @var array<?\DateTime>
 */
public array $arrayOfNullableDateTimes;

/**
 * @var array<\DateTime|null>
 */
public array $arrayOfNullableDateTimes2;
```

PhpDocExtractor is also unable to return mutliple value/key data types in array/collection. Example phpDoc:

```
/**
 * @var array<int|string>
 */
public $arrayOfMultipleValueTypes;
```

### How to reproduce

To reproduce use PropertyInfo component with PhpDocExtractor. Error will be shown, when extracting type from property with nullable array value type. Also when extracting type from property with multiple array key/value type, empty arrry will be returned.

### Possible Solution

To fix the problem, use getType instead of createType in PhpDocTypeHelper. To add multiple array value/key types return all extracted types (remove count check). I will also make a PR with solution.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MudrakIvan**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49555
| License       | MIT
| Doc PR        |

Bug fix for nullable array value types + for multiple array key/value types.
Two existing tests changed:
- property 'i' - change ?string|int comment to string|int|null (in newer versions (5.4+) already fixed)
- property 'iteratorCollection' - change key types from null to string/int (default key values from phpDoc)

Added new tests:
- property 'nonNullableCollectionOfNullableElements' - array<null|int> (nullable array value type)
- property 'nullableCollectionOfMultipleNonNullableElementTypes' - null|array<int|string> (nullable array of int and string value types)

### CODE REVIEW

File: src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php [hunk 1]
```diff
@@ -115,43 +115,29 @@ private function createType(DocType $type, bool $nullable, string $docType = nul
...
-            $key = $this->getTypes($type->getKeyType());
-            $value = $this->getTypes($type->getValueType());
-
-            // More than 1 type returned means it is a Compound type, which is
-            // not handled by Type, so better use a null value.
-            $key = 1 === \count($key) ? $key[0] : null;
-            $value = 1 === \count($value) ? $value[0] : null;
-
-            return new Type($phpType, $nullable, $class, true, $key, $value);
+            $keys = $this->getTypes($type->getKeyType());
```
Comment (stof) [inline src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php:118]: if this returns an empty array, we should still use `null` to mark collection keys as unknown

Comment (MudrakIvan) [reply src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php:118]: Should i change it, even though it will be converted to empty array in `Type::__constructor`?

Comment (stof) [reply src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php:118]: ah, I forgot that Type makes no difference there. So this is indeed not needed

**Review by nicolas-grekas — APPROVED** [review]
(I rebased the PR)

**Comment by fabpot** [comment]
Thank you @MudrakIvan.
