### PR TITLE
[Cache] fix cache data collector on late collect

### LINKED ISSUE #59838: Missing cache data in profiler
### Symfony version(s) affected

5.4.x

### Description

When we stream response (`Symfony\Component\HttpFoundation\StreamedResponse`) and use cache in streamed response callback, we don't see this cache used in profiler

### How to reproduce

Demo run on this project https://github.com/dcmbrs/cache-stream-profiler and follow up readme on master branch 

### Possible Solution

Fix Data method `lateCollect` in `Symfony\Component\Cache\DataCollector`

### Additional Context

In general, the problem seems to occur with everything that happens once the 'kernel.response' event has passed.

### PR DESCRIPTION
**Pull request by dcmbrs**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59838
| License       | MIT

### CODE REVIEW

**Review by keradus — COMMENTED** [review]
Can you add a test case that is showing the issue the change in code is fixing?

**Comment by dcmbrs** [comment]
@keradus I added a test

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
@dcmbrs Can you rebase tour PR to get rid of the merge commit? Thank you?

File: src/Symfony/Component/Cache/Tests/DataCollector/CacheDataCollectorTest.php [hunk 1]
```diff
@@ -104,6 +104,26 @@ public function testCollectBeforeEnd()
...
 
+    public function testLateCollect()
+    {
+        $adapter = new TraceableAdapter(new NullAdapter());
+
+        $collector = new CacheDataCollector();
+        $collector->addInstance(self::INSTANCE_NAME, $adapter);
+
+        $adapter->get('foo', function () use ($collector) {
+            $collector->latecollect();
```
Comment (keradus) [inline src/Symfony/Component/Cache/Tests/DataCollector/CacheDataCollectorTest.php]:
```suggestion
            $collector->lateCollect();
```

**Comment by dcmbrs** [comment]
I'm sorry I couldn't clean up the merge request commit and I don't know what's going on. I see many commits and changes, I have the impression that 7.3 has been merged onto this branch but yet I haven't pushed anything on my side. Could I get some help? I'm not used to working with forks and rebase

Or I do antoher PR et close this ?

**Comment by nicolas-grekas** [comment]
(I fixed the rebase)

**Comment by fabpot** [comment]
Thank you @dcmbrs.
