### PR TITLE
[PropertyInfo] fix attribute namespace with recursive traits

### LINKED ISSUE #36997: PropertyInfoExtractor gives incorrect type for properties defined in a Trait
**Symfony version(s) affected**: 4.4.7

**Description**  

If a class uses a trait which defines a property with a PHPDoc type hint, the property will have an incorrect namespace when extracted with `$extractor->getTypes()`

**How to reproduce**  

```php
/*
 * A/SomeTrait.php
 */
namespace A;

use A\B\TypedClass;

trait SomeTrait
{
    /** @var TypedClass */
    public $typedClass;
}
```

```php
/*
 * A/SomeClass.php
 */
namespace A;

final class SomeClass
{
    use SomeTrait;
}
```

```php
/*
 * A/B/TypedClass.php
 */
namespace A\B;

final class TypedClass
{
}
```

```php
/*
 * Usage
 */

$extractor = new PropertyInfoExtractor([], [new PhpDocExtractor()]);
$types = $extractor->getTypes(SomeClass::class, 'typedClass');

/*
 * This will output 'A\TypedClass' but no such class exists.
 * It should be     'A\B\TypedClass'.
 */
echo $types[0]->getClassName();
```

**Possible Solution**  

Looks like the property name is simply appended to the namespace of the class where the trait is used, instead of taking into account the `use` statement inside the trait.

**Additional context**  

A workaround for this is typehinting the property in the trait using FQCN instead of relying on `use`.

The same problem also happens with the following setup:
```
A/
  B/
    SomeTrait.php
    TypedClass.php
  SomeClass.php
```

As long as the namespace of `SomeClass` is different than `TypedClass`.

### PR DESCRIPTION
**Pull request by soullivaneuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #36997 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

The targeted issue is closed because considered as solved by https://github.com/symfony/symfony/pull/40175.

However, the fix is not enough and is not working with recursive trait inclusion. (see https://github.com/symfony/symfony/issues/36997#issuecomment-822572640).

This pull request is completing the first fix of @xabbuh, trying to follow the same coding style. :wink:

### CODE REVIEW

File: src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php [hunk 1]
```diff
@@ -220,17 +220,15 @@ private function getDocBlockFromProperty(string $class, string $property): ?DocB
...
 
-                    break;
-                }
+        foreach ($reflector->getTraits() as $trait) {
+            if ($trait->hasProperty($property)) {
+                return $this->getDocBlockFromProperty($trait->getName(), $property);
             }
+        }
 
+        try {
```
Comment (soullivaneuh) [inline src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php:231]: Note: I moved the login out the `try/catch` block because as far as I know, this statement is for the `$this->docBlockFactory->create` line below, not for the recursive resolution.

Please tell me if I'm wrong. :+1:

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/PropertyInfo/Tests/Fixtures/TraitUsage/DummyTrait.php [hunk 2]
```diff
@@ -11,46 +11,9 @@
 
 namespace Symfony\Component\PropertyInfo\Tests\Fixtures\TraitUsage;
 
-use Symfony\Component\PropertyInfo\Tests\Fixtures\Dummy;
+use Symfony\Component\PropertyInfo\Tests\Fixtures\DummyTraitExternal;
 
 trait DummyTrait
 {
-    /**
```
Comment (fabpot) [inline src/Symfony/Component/PropertyInfo/Tests/Fixtures/TraitUsage/DummyTrait.php:18]: Instead of moving everywhere to another trait, maybe we can keep a few here to cover more cases?

Comment (soullivaneuh) [reply src/Symfony/Component/PropertyInfo/Tests/Fixtures/TraitUsage/DummyTrait.php:18]: I am not sure to follow what you would like.

I had to move the trait to an another namespace for proof testing.

Also this structure cover more than before without losing anything to me, as the code and test logic are the same, only the recursive fact was missing.

I may create an another trait for the recursive case to let the actual untouched, but I think I will have to double the test suite with not much more reliability value.

Comment (nicolas-grekas) [reply src/Symfony/Component/PropertyInfo/Tests/Fixtures/TraitUsage/DummyTrait.php:18]: I think what Fabien means is that some methods should remain in this trait, while others are moved to the recursive one.

Comment (soullivaneuh) [reply src/Symfony/Component/PropertyInfo/Tests/Fixtures/TraitUsage/DummyTrait.php:18]: I didn't get the point about partial moving, however, I put an another commit making the global test diff clearer.

Tell me if this version is OK to you. :+1:

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @soullivaneuh.
