### PR TITLE
[Serializer] Adjust ObjectNormalizerTest for the accessor method changes from #61097

### LINKED ISSUE #61096: [ObjectSerializer] invalid normalization when getter-like method (`isser`, `hasser`, `canner`) and property have the same name
### Symfony version(s) affected

Since the introduction of Serializer up until 7.4+

### Description

When we create a class property where the name starts with `is` (followed by an uppercase letter) and we create a getter method of the same name, the serializer will remove the `is` prefix in the normalized array.

E.g. having the following class:
```php
class MyClass {
  private bool $isOwner = true;

  public function isOwner(): bool {
    return $this->isOwner;
  }

  public function setIsOwner(bool $isOwner): void {
    $this->isOwner = $isOwner;
  }
}
```

Doing a serialization to JSON results in
```json
{
  "owner": true
}
```

If we try to denormalize it again, the property will be ignored. It works if the key in the JSON object is named `isOwner`, though.

This means normalization and denormalization are inconsistent.

Sidenote: When using the JetBrains IDE [Generate Getter](https://www.jetbrains.com/help/idea/generating-code.html#generate-getters-setters) feature on a boolean property called like `$isX`, it will automatically create an `isser` method with the same name like the property. This is how I ran into this.

### How to reproduce

Use `MyClass` from the description and run
```php
$classMetadataFactory = new ClassMetadataFactory(new AttributeLoader());
$normalizer = new ObjectNormalizer($classMetadataFactory);

$object = new MyClass();
$normalized = $normalizer->normalize($object);

/*
inspecting $normalized in the debugger:

$normalized = [
  'owner' => true
]
*/
```

### Possible Solution

I propose to keep the `is` prefix in the resulting attribute, if there is a property exactly named like this. I will create a PR for that.

### Additional Context

Edit: Also see PR #61097 for further getter-like methods where this happens: `getters`, `issers`, `hassers`, `canners`.

### PR DESCRIPTION
**Pull request by RafaelKr**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #61096
| License       | MIT

This is a follow-up PR to #61097
CC @nicolas-grekas

### CODE REVIEW

File: src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php [hunk 1]
```diff
@@ -956,19 +959,110 @@ public function testNormalizeWithMethodNamesSimilarToAccessors()
...
+        $object = new ObjectWithPropertyAndAccessorSameName(
+            'foo',
+            'getFoo',
+            'canFoo',
+            'hasFoo',
+            'isFoo'
+        );
+        $normalized = $normalizer->normalize($object);
+
+        // Previously, only the 'foo' property was extracted, all other properties starting with accessor verbs were
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php]: "Previously" won't mean anything once merged, this should be reformulated to not refer to something that won't last

File: src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php [hunk 2]
```diff
@@ -938,6 +939,8 @@ public function testObjectNormalizerWithAttributeLoaderAndObjectHasStaticPropert
         $this->assertSame([], $normalizer->normalize($class));
     }
 
+    // accessors
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php:942]: should be removed

Comment (RafaelKr) [reply src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php:942]: It's used to group some other tests in the ObjectNormalizerTest too. 
"skip uninitialized", "type enforcement", etc.

Should it still be removed?

File: src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php (hunk 1 above)
Comment (RafaelKr) [reply src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php]: Of course, you're right. Fixed.

**Comment by RafaelKr** [comment]
@nicolas-grekas it's ready for another review. I also created `protected function getNormalizerForAccessors($accessorPrefixes = null): ObjectNormalizer`, as it's done for some other test groups.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by RafaelKr** [comment]
Thanks for the approval. Did you see my comment on the `// accessors` comment? Can we resolve the conversation?

File: src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php (hunk 2 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php:942]: let's keep it then!

**Comment by nicolas-grekas** [comment]
Thank you @RafaelKr.
