### PR TITLE
[TwigBridge] suggest to install the Twig bundle when the required component is already installed

### LINKED ISSUE #43560: [Security] is_granted twig helper is not registered
**Symfony version(s) affected**: 5.3.8

**Description**
After composer update and updating all recipes the "is_granted" twig function is not available anymore. When accessing a page i get 
```
Did you forget to run &quot;composer require symfony/security-core&quot;? Unknown function &quot;is_granted&quot; in &quot;_Base/_navigation.html.twig&quot;. (500 Internal Server Error)
``` 

I have  "symfony/security-bundle": "5.3.*" in my composer.json and all libs are installed in vendor/. When i debug the cache warmup, the config "templating_twig.php" does not trigger my breakpoint, other configs in the security-bundle\config do.

Login does work normally.

It worked as expected before the composer update and my application was already on 5.3.1.

**How to reproduce**
Not sure.

**Possible Solution**

**Additional context**
```
name     : symfony/security-bundle
descrip. : Provides a tight integration of the Security component into the Symfony full-stack framework
keywords :
versions : * v5.3.8
type     : symfony-bundle
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://symfony.com
source   : []
dist     : [zip] https://*****/symfony/security-bundle/v5.3.8/symfony-security-bundle-v5.3.8.zip b755ed5d11685ba9aaa27b060250e5a57371f37f
path     : C:\Development\***\vendor\symfony\security-bundle
names    : symfony/security-bundle
 
```

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #43560
| License       | MIT
| Doc PR        |

### CODE REVIEW

File: src/Symfony/Bridge/Twig/UndefinedCallableHandler.php [hunk 1]
```diff
@@ -93,6 +94,12 @@ private static function onUndefined(string $name, string $type, string $componen
             throw new SyntaxError(sprintf('Did you forget to %s? Unknown %s "%s".', self::FULL_STACK_ENABLE[$component], $type, $name));
         }
 
-        throw new SyntaxError(sprintf('Did you forget to run "composer require symfony/%s"? Unknown %s "%s".', $component, $type, $name));
+        $missingPackage = 'symfony/'.$component;
+
+        if (class_exists(InstalledVersions::class) && InstalledVersions::isInstalled($missingPackage)) {
+            $missingPackage = 'symfony/twig-bridge';
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Twig/UndefinedCallableHandler.php]: should be twig-bundle or?

Comment (xabbuh) [reply src/Symfony/Bridge/Twig/UndefinedCallableHandler.php]: fixed

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.
