### PR TITLE
[VarExporter] Fix DeepCloner crash with objects using __serialize()

### LINKED ISSUE #63699: [Cache][VarExporter] Invalid serialization data for DateTimeImmutable object
### Symfony version(s) affected

8.1-dev

### Description

In my application, we store cache items with a date like this:

```php
final readonly class MyCacheItem
{
    public function __construct(
        public MyRecord $record,
        public \DateTimeImmutable $storedAt,
    ) {
    }
}
```

Throwing an instance of this class into a cache and unserializing it afterwards works fine on Symfony 8.0. On the 8.1-dev branch however, fetching the items crashes with the error message, "Invalid serialization data for DateTimeImmutable object".

### How to reproduce

```php
namespace App;

use Symfony\Component\Cache\Adapter\ArrayAdapter;

require __DIR__.'/vendor/autoload.php';

final readonly class MyCacheItem
{
    public function __construct(
        public MyRecord $record,
        public \DateTimeImmutable $storedAt,
    ) {
    }
}

final readonly class MyRecord
{
    public function __construct(
        public string $myField,
    ) {
    }
}

$cache = new ArrayAdapter();
$item = $cache->getItem('foo');
$item->set(new MyCacheItem(
    new MyRecord('a'),
    new \DateTimeImmutable('2013-01-26T12:34:56+01:00'),
));
$cache->save($item);

dump($cache->getItem('foo')->get());
```

#### Output with Symfony 8.0:

```
App\MyCacheItem {#9
  +record: App\MyRecord {#10
    +myField: "a"
  }
  +storedAt: DateTimeImmutable @1359200096 {#11
    date: 2013-01-26 12:34:56.0 +01:00
  }
}
```

#### Output with Symfony 8.1:

```
PHP Warning:  foreach() argument must be of type array|object, string given in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 116

Warning: foreach() argument must be of type array|object, string given in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 116
PHP Warning:  foreach() argument must be of type array|object, int given in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 116

Warning: foreach() argument must be of type array|object, int given in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 116
PHP Warning:  foreach() argument must be of type array|object, string given in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 116

Warning: foreach() argument must be of type array|object, string given in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 116
PHP Deprecated:  Method DateTimeImmutable::__wakeup() is deprecated since 8.5, this method is obsolete, as serialization hooks are provided by __unserialize() and __serialize() in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 387

Deprecated: Method DateTimeImmutable::__wakeup() is deprecated since 8.5, this method is obsolete, as serialization hooks are provided by __unserialize() and __serialize() in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 387
PHP Fatal error:  Uncaught Error: Invalid serialization data for DateTimeImmutable object in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php:387
Stack trace:
#0 /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php(387): DateTimeImmutable->__wakeup()
#1 /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php(173): Symfony\Component\VarExporter\DeepCloner::reconstruct(0, Array, Array, Array, Array, Array, Array)
#2 /path/to/symfony/src/Symfony/Component/Cache/Adapter/ArrayAdapter.php(367): Symfony\Component\VarExporter\DeepCloner->clone()
#3 /path/to/symfony/src/Symfony/Component/Cache/Adapter/ArrayAdapter.php(131): Symfony\Component\Cache\Adapter\ArrayAdapter->unfreeze('foo', true)
#4 /path/to/symfony/test.php(36): Symfony\Component\Cache\Adapter\ArrayAdapter->getItem('foo')
#5 {main}
  thrown in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 387

Fatal error: Uncaught Error: Invalid serialization data for DateTimeImmutable object in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php:387
Stack trace:
#0 /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php(387): DateTimeImmutable->__wakeup()
#1 /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php(173): Symfony\Component\VarExporter\DeepCloner::reconstruct(0, Array, Array, Array, Array, Array, Array)
#2 /path/to/symfony/src/Symfony/Component/Cache/Adapter/ArrayAdapter.php(367): Symfony\Component\VarExporter\DeepCloner->clone()
#3 /path/to/symfony/src/Symfony/Component/Cache/Adapter/ArrayAdapter.php(131): Symfony\Component\Cache\Adapter\ArrayAdapter->unfreeze('foo', true)
#4 /path/to/symfony/test.php(36): Symfony\Component\Cache\Adapter\ArrayAdapter->getItem('foo')
#5 {main}
  thrown in /path/to/symfony/src/Symfony/Component/VarExporter/DeepCloner.php on line 387
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Amoifr**
| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63699
| License       | MIT

## Summary

Fixes a crash when cloning objects that use `__serialize()/__unserialize()` (like `DateTimeImmutable`), particularly affecting PHP 8.5 where `__wakeup()` is deprecated.

## Problem

When cloning objects with `__serialize()/__unserialize()`:
1. The property data format is flat (`['date' => '...']`) rather than scoped (`['Scope' => ['name' => value]]`)
2. In some cases, `__unserialize()` detection via `method_exists()` could fail for internal classes
3. This caused the flat data to reach the property iteration loop, triggering: "foreach() argument must be of type array|object, string given"

### Commit 1: Defensive fix in `DeepCloner.php`
- Adds a type check to skip non-array values in the property loop
- Prevents the crash even if flat `__serialize()` data reaches the loop
- Adds tests for `DateTimeImmutable` cloning scenarios

### Commit 2: Root cause fix in `Exporter.php`
- When `__serialize()` is called, ensures `__unserialize()` is properly detected
- Uses both `method_exists()` AND `ReflectionClass::hasMethod()` for robustness
- Properly updates the cache when `__unserialize()` is detected via reflection

## Test plan

- [ ] Run existing VarExporter tests
- [ ] Test with PHP 8.5 to validate DateTimeImmutable handling
- [ ] Verify the reproduction case from #63699 is fixed

### CODE REVIEW

**Comment by stof** [comment]
Why is this PR doing a change in the Serializer component as well ? Do you have unrelated commits in your branch ?

File: src/Symfony/Component/VarExporter/Internal/Exporter.php [hunk 1]
```diff
@@ -100,7 +100,11 @@ public static function prepare($values, $objectsPool, &$refsPool, &$objectsCount
                     throw new \TypeError($class.'::__serialize() must return an array');
                 }
 
-                if (self::$classInfo[$class][0] ??= method_exists($class, '__unserialize')) {
+                // When __serialize() exists, always check for __unserialize() using both methods
+                // to handle internal classes like DateTimeImmutable where detection may vary
+                $hasUnserialize = self::$classInfo[$class][0] ??= method_exists($class, '__unserialize');
+                if ($hasUnserialize || $reflector->hasMethod('__unserialize')) {
```
Comment (stof) [inline src/Symfony/Component/VarExporter/Internal/Exporter.php]: This `||` should be done in the computation of the cached value IMO, not for all usages in case the cached value is `false`

**Comment by Amoifr** [comment]
> Why is this PR doing a change in the Serializer component as well ? Do you have unrelated commits in your branch ?

@stof 
You're absolutely right, thanks for catching this! I had an unrelated commit in my branch. I've rebased to remove it. Sorry for the confusion, and thank you for taking the time to review!

File: src/Symfony/Component/VarExporter/Internal/Exporter.php (hunk 1 above)
Comment (Amoifr) [reply src/Symfony/Component/VarExporter/Internal/Exporter.php]: Great catch, thank you! You're absolutely right — it makes much more sense to include both checks directly in the cached value computation. I've updated the code accordingly. Really appreciate your thoughtful review and the clear feedback!

**Review by nicolas-grekas — APPROVED** [review]
I reverted the code to pre-https://github.com/symfony/symfony/pull/63612 state

**Comment by nicolas-grekas** [comment]
Thank you @Amoifr.
