### PR TITLE
[PhpUnitBridge] fix compatibility with phpunit 9

### LINKED ISSUE #36499: phpunit-bridge breaks with phpunit 9.1.2
Hi,

Since phpunit 9.1.2, the bridge fails with this error:

```
PHP Fatal error:  Uncaught Error: Access to undeclared static property: PHPUnit\Util\Blacklist::$blacklistedClassNames in /dir/bin/.phpunit/phpunit-9.1-0/phpunit:13
Stack trace:
#0 /dir/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php(343): include()
#1 /dir/bin/phpunit(13): require('/home/jmsche/Si...')
#2 {main}
  thrown in /dir/bin/.phpunit/phpunit-9.1-0/phpunit on line 13
```

After a little research, I found the commit that breaks it: https://github.com/sebastianbergmann/phpunit/commit/2b4d7b8bb3fd052095e64999990cc36b63aa0771

So phpunit switches from a public static var to a private constant.

### PR DESCRIPTION
**Pull request by garak**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36499
| License       | MIT
| Doc PR        | none

See related issue

### CODE REVIEW

File: src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php [hunk 1]
```diff
@@ -47,6 +47,8 @@ public function __construct(array $mockedNamespaces = array())
     {
         if (class_exists('PHPUnit_Util_Blacklist')) {
             \PHPUnit_Util_Blacklist::$blacklistedClassNames['\Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait'] = 2;
+        } elseif (method_exists(Blacklist::class, 'addDirectory') {
```
Comment (localheinz) [inline src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php:50]:
```suggestion
        } elseif (method_exists(Blacklist::class, 'addDirectory')) {
```

File: src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php [hunk 2]
```diff
@@ -47,6 +47,8 @@ public function __construct(array $mockedNamespaces = array())
...
+            Blacklist::addDirectory('\Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait');
         } else {
             Blacklist::$blacklistedClassNames['\Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait'] = 2;
         }
```
Comment (localheinz) [inline src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php:54]:
```suggestion
        $className = '\Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait';
        
        if (class_exists('PHPUnit_Util_Blacklist')) {
            \PHPUnit_Util_Blacklist::$blacklistedClassNames[$className] = 2;
        } elseif (class_exists(Blacklist::class)) {
            if (method_exists(Blacklist::class, 'addDirectory')) {
                Blacklist::addDirectory($className);
            } else {
                Blacklist::$blacklistedClassNames[$className] = 2;
            }
        }
```

File: src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php [hunk 3]
```diff
@@ -47,8 +47,14 @@ public function __construct(array $mockedNamespaces = array())
     {
         if (class_exists('PHPUnit_Util_Blacklist')) {
             \PHPUnit_Util_Blacklist::$blacklistedClassNames['\Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait'] = 2;
-        } else {
-            Blacklist::$blacklistedClassNames['\Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait'] = 2;
+        } elseif (method_exists(Blacklist::class, 'addDirectory')) {
+            Blacklist::addDirectory('\Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait');
+        } elseif (class_exists(Blacklist::class)) {
+            if (method_exists(Blacklist::class, 'addDirectory')) {
+                Blacklist::addDirectory($className);
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php:54]: $className is undefined now

**Comment by nicolas-grekas** [comment]
Looks like `src/Symfony/Bridge/PhpUnit/bin/simple-phpunit` also uses the blacklist.

File: src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php [hunk 4]
```diff
@@ -47,8 +47,14 @@ public function __construct(array $mockedNamespaces = array())
     {
         if (class_exists('PHPUnit_Util_Blacklist')) {
             \PHPUnit_Util_Blacklist::$blacklistedClassNames['\Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait'] = 2;
-        } else {
-            Blacklist::$blacklistedClassNames['\Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait'] = 2;
+        } elseif (method_exists(Blacklist::class, 'addDirectory')) {
+            Blacklist::addDirectory('\Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait');
+        } elseif (class_exists(Blacklist::class)) {
```
Comment (Jean85) [inline src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php:52]: Wouldn't this check go above?

**Comment by garak** [comment]
Added check in simple-phpunit too

**Review by Jean85 — APPROVED** [review]

File: src/Symfony/Bridge/PhpUnit/bin/simple-phpunit [hunk 5]
```diff
@@ -126,9 +126,14 @@ if (!class_exists('SymfonyBlacklistPhpunit', false)) {
 if (class_exists('PHPUnit_Util_Blacklist')) {
     PHPUnit_Util_Blacklist::$blacklistedClassNames['SymfonyBlacklistPhpunit'] = 1;
     PHPUnit_Util_Blacklist::$blacklistedClassNames['SymfonyBlacklistSimplePhpunit'] = 1;
-} else {
-    PHPUnit\Util\Blacklist::$blacklistedClassNames['SymfonyBlacklistPhpunit'] = 1;
-    PHPUnit\Util\Blacklist::$blacklistedClassNames['SymfonyBlacklistSimplePhpunit'] = 1;
+} elseif (class_exists(\PHPUnit\Util\Blacklist::class)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/PhpUnit/bin/simple-phpunit:129]: we need this check, better remove it and remove one indentation level (same in the other file - no need for the $className variable then)

Comment (localheinz) [reply src/Symfony/Bridge/PhpUnit/bin/simple-phpunit:129]: @nicolas-grekas 

Why not? The class is marked as `@internal` and can be removed or renamed at any time.

Comment (martinssipenko) [reply src/Symfony/Bridge/PhpUnit/bin/simple-phpunit:129]: It's not internal since [9.1.3](https://github.com/sebastianbergmann/phpunit/blob/b3c4b198184ac76710efe1258598c559dff6e401/ChangeLog-9.1.md#913---2020-04-23)

Comment (garak) [reply src/Symfony/Bridge/PhpUnit/bin/simple-phpunit:129]: So, what should I do? Keep it as is or change it?

Comment (nicolas-grekas) [reply src/Symfony/Bridge/PhpUnit/bin/simple-phpunit:129]: change it please

File: src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php [hunk 6]
```diff
@@ -47,6 +47,8 @@ public function __construct(array $mockedNamespaces = array())
     {
         if (class_exists('PHPUnit_Util_Blacklist')) {
             \PHPUnit_Util_Blacklist::$blacklistedClassNames['\Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait'] = 2;
+        } elseif (method_exists(Blacklist::class, 'addDirectory')) {
+            Blacklist::addDirectory('\Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait');
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php:51]: oh, wait, this needs a directory, not a class name!
also, we need to be sure that `Blacklist::initialize()` ran before (eg by calling it)
same in the bootstrap file

Comment (nicolas-grekas) [reply src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php:51]: if phpunit 9.1.3 is not yet released, maybe changing addDirectory to addClass($class, $level) is an idea? (and ensure it does the initialization also?)

Comment (garak) [reply src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php:51]: it is, see https://packagist.org/packages/phpunit/phpunit#9.1.3

Comment (nicolas-grekas) [reply src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php:51]: oops - could be worth adding still for 9.1.4 if Sebatian is OK

Comment (garak) [reply src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php:51]: and, anyway, `initialize` method is private :disappointed:

Comment (nicolas-grekas) [reply src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php:51]: `getBlacklistedDirectories()` is public and calls it without any other side effect

Comment (garak) [reply src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php:51]: Good. So, the only question left is how to add directory instead of class name. Should we use the same strategy used in `initialize` method (using `ReflectionClass`)?

Comment (nicolas-grekas) [reply src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php:51]: yep, inline I suppose, e.g.
`dirname(dirname((new \ReflectionClass(...))->getFileName())`

Comment (garak) [reply src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php:51]: Still, it's not clear to me how we can call non-static method `getBlacklistedDirectories` before calling static method `addDirectory`

Comment (nicolas-grekas) [reply src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php:51]: `(new BlackList())->getBlacklistedDirectories()` would do it, this is static state in the end

Comment (garak) [reply src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php]: Thank you Nicolas. Let me know if it's good for you now.

File: src/Symfony/Bridge/PhpUnit/bin/simple-phpunit [hunk 7]
```diff
@@ -126,6 +126,10 @@ if (!class_exists('SymfonyBlacklistPhpunit', false)) {
 if (class_exists('PHPUnit_Util_Blacklist')) {
     PHPUnit_Util_Blacklist::$blacklistedClassNames['SymfonyBlacklistPhpunit'] = 1;
     PHPUnit_Util_Blacklist::$blacklistedClassNames['SymfonyBlacklistSimplePhpunit'] = 1;
+} elseif (method_exists('PHPUnit\Util\Blacklist', 'addDirectory')) {
+    (new PHPUnit\Util\BlackList())->getBlacklistedDirectories();
+    PHPUnit\Util\Blacklist::addDirectory(\dirname(\dirname((new \ReflectionClass('SymfonyBlacklistPhpunit'))->getFileName())));
+    PHPUnit\Util\Blacklist::addDirectory(\dirname(\dirname((new \ReflectionClass('SymfonyBlacklistSimplePhpunit'))->getFileName())));
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/PhpUnit/bin/simple-phpunit:132]: one "dirname" for both here (see the value: `['SymfonyBlacklistPhpunit'] = 1;`, vs `2` in the other file)

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @garak.
