### PR TITLE
[Messenger] Remove indices in messenger table on MySQL to prevent deadlocks while removing messages when running multiple consumers

### LINKED ISSUE #41541: Deadlock when deleting messages from queue
**Symfony version(s) affected**: 5.3 (possibly earlier)

**Description**
We use `symfony-messenger` with multiple workers handling messages from the same queue using `DoctrineTransport` with a mysql database. When the workers are being utilized fully, a deadlock occasionally occurs when removing a message from the queue.

**How to reproduce**
Define a simple queue:
```yml
# config/packages/messenger.yaml
framework:
    messenger:
        transports:
            default:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                retry_strategy:
                    max_retries: 10
                    delay: 60000
                    multiplier: 1
```

Run multiple workers (3 in our case) handling the same queue:

```bash
bin/console messenger:consume default --limit=200 --time-limit=3600 --memory-limit=64M
```

If a lot of messages are handled causing the workers to run full-time, sometimes the exception in the stacktrace below is thrown.

**Additional context**
Stacktrace:
```
Symfony\Component\Messenger\Exception\TransportException: An exception occurred while executing 'DELETE FROM messenger_messages WHERE id = ?' with params ["26628"]:

SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
#12 /vendor/symfony/doctrine-messenger/Transport/Connection.php(238): Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection::reject
#11 /vendor/symfony/doctrine-messenger/Transport/DoctrineReceiver.php(91): Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineReceiver::reject
#10 /vendor/symfony/doctrine-messenger/Transport/DoctrineTransport.php(61): Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport::reject
#9 /vendor/symfony/messenger/Worker.php(132): Symfony\Component\Messenger\Worker::handleMessage
#8 /vendor/symfony/messenger/Worker.php(77): Symfony\Component\Messenger\Worker::run
#7 /vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(198): Symfony\Component\Messenger\Command\ConsumeMessagesCommand::execute
#6 /vendor/symfony/console/Command/Command.php(256): Symfony\Component\Console\Command\Command::run
#5 /vendor/symfony/console/Application.php(989): Symfony\Component\Console\Application::doRunCommand
#4 /vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Bundle\FrameworkBundle\Console\Application::doRunCommand
#3 /vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application::doRun
#2 /vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Bundle\FrameworkBundle\Console\Application::doRun
#1 /vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application::run
#0 /bin/console(43): null
```

This could be related to https://github.com/symfony/symfony/issues/39041.

### PR DESCRIPTION
**Pull request by jeroennoten**
SELECT ... FOR UPDATE locks rows but also relevant indices. Since locking rows and indices is not one atomic operation,
this might cause deadlocks when running multiple workers. Removing indices on queue_name and available_at
resolves this problem.

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41541 #39041
| License       | MIT

Using Doctrine transport with multiple consumers occasionally results in MySQL deadlocks while removing a message from the messages database table.

This can be reproduced consistently by setting up a default `async` queue with the Doctrine transport and creating an empty `TestMessage` and `TestMessageHandler`. Create a command that dispatches 10000 of these messages in a for loop en start 4 message consumers. After a while, several consumers report a deadlock:

```
In Connection.php line 227:
                                                                                                                   
  [Symfony\Component\Messenger\Exception\TransportException]                                                       
  An exception occurred while executing 'DELETE FROM messenger_messages WHERE id = ?' with params ["32903"]:       
                                                                                                                   
  SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction  
                                                                                                                   

Exception trace:
  at /var/www/vendor/symfony/messenger/Transport/Doctrine/Connection.php:227
 Symfony\Component\Messenger\Transport\Doctrine\Connection->ack() at /var/www/vendor/symfony/messenger/Transport/Doctrine/DoctrineReceiver.php:79
 Symfony\Component\Messenger\Transport\Doctrine\DoctrineReceiver->ack() at /var/www/vendor/symfony/messenger/Transport/Doctrine/DoctrineTransport.php:50
 Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransport->ack() at /var/www/vendor/symfony/messenger/Worker.php:150
 Symfony\Component\Messenger\Worker->handleMessage() at /var/www/vendor/symfony/messenger/Worker.php:81
 Symfony\Component\Messenger\Worker->run() at /var/www/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php:202
 Symfony\Component\Messenger\Command\ConsumeMessagesCommand->execute() at /var/www/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/vendor/symfony/console/Application.php:1027
 Symfony\Component\Console\Application->doRunCommand() at /var/www/vendor/symfony/framework-bundle/Console/Application.php:97
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /var/www/vendor/symfony/framework-bundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /var/www/bin/console:42
```

A similar problem with Laravel's queue worker (and a solution) is reported here: https://github.com/laravel/framework/issues/31660

The solution is to remove indices on the `queue_name` and `available_at` columns. After removing these indices, I could not reproduce the issue anymore. Also, I did not notice any performance degradations.

### CODE REVIEW

**Comment by fabpot** [comment]
IIUC, this issue only exists on MySQL. It this is the case, the change should only be done for MySQL and not for all database engines.

**Comment by jeroennoten** [comment]
@fabpot, you are right. To be sure, I tested with PostgreSQL and I could not reproduce the issues there.

So I changed this to only apply to MySQL. I also added a unit test for these changes.

File: src/Symfony/Component/Messenger/Transport/Doctrine/Connection.php [hunk 1]
```diff
@@ -386,7 +387,6 @@ private function getSchema(): Schema
         $table->addColumn('headers', self::$useDeprecatedConstants ? Type::TEXT : Types::TEXT)
             ->setNotnull(true);
         $table->addColumn('queue_name', self::$useDeprecatedConstants ? Type::STRING : Types::STRING)
-            ->setLength(190) // MySQL 5.6 only supports 191 characters on an indexed column in utf8mb4 mode
```
Comment (fabpot) [inline src/Symfony/Component/Messenger/Transport/Doctrine/Connection.php:389]: This should be reverted as we are not creating an index on MySQL for that column anymore, right?

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Messenger/Transport/Doctrine/Connection.php (hunk 1 above)
Comment (jeroennoten) [reply src/Symfony/Component/Messenger/Transport/Doctrine/Connection.php:389]: Right, so that is exactly why I removed that line.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jeroennoten.

**Comment by bobvandevijver** [comment]
Thank you @jeroennoten, I just saw this exact error in production for the very first time this weekend. Very nice to see it has already been resolved!

**Comment by jeroennoten** [comment]
@bobvandevijver, you're welcome!

Don't forget to run `bin/console messenger:setup-transports` after updating Symfony to the latest version to apply these changes to the database. The command will update the existing table or create a new one if it does not exist.

**Comment by bobvandevijver** [comment]
We're using migrations to define the table, but thanks for the tip!

**Comment by palttamas** [comment]
@jeroennoten removing the indexes fixes the lock issue but caused us significant performance issues. I was searching the issues and it seems to me that multiple consumers are not working very well for others either, be it redis or doctrine transport, no matter.

**Comment by nicolas-grekas** [comment]
I'm proposing to revert this PR and replace it by another approach in #45888
