### PR TITLE
Avoid duplicated session listener registration in tests

### LINKED ISSUE #44345: 5.4.0: `SessionListener::onKernelResponse` listener is registered twice in test env
### Symfony version(s) affected

5.4.0

### Description

`Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelResponse()` listener is registered twice in `test` environment.

Our tests for controllers where we set `NO_AUTO_CACHE_CONTROL_HEADER` flag started failing, because the flag is reset on the first call of `onKernelResponse` and the subsequent call overwrites the previously set headers.

### How to reproduce

It works fine on 5.3:

```bash
$ symfony new symfonysessionlistenertest53 --version="5.3.x@dev" --full
$ cd symfonysessionlistenertest53 
$ symfony console debug:event --env=test

"kernel.response" event
-----------------------
....
  #11     Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelResponse()            -1000
...
``` 

But is registered twice on 5.4:

```bash
$ symfony new symfonysessionlistenertest54 --version="5.4.x@dev" --full
$ cd symfonysessionlistenertest54 
$ symfony console debug:event --env=test

"kernel.response" event
-----------------------
...
  #10     Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelResponse()            -1000
  #11     Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelResponse()            -1000
...
```

### Possible Solution

_No response_

### Additional Context

Note: The listener is set only once in `dev` and `prod` envs.

I guess that the issue may be related to #41390.

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44345
| License       | MIT
| Doc PR        | -

Avoid duplicated session listener registration in tests.

### CODE REVIEW

**Review by jderusse — APPROVED** [review]

**Comment by mhujer** [comment]
@alexander-schranz I can confirm that this patch fixes #44345 for both the empty Symfony app and my real world app. 👏 👍

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -350,6 +350,11 @@ public function load(array $configs, ContainerBuilder $container)
 
             $this->sessionConfigEnabled = true;
             $this->registerSessionConfiguration($config['session'], $container, $loader);
+            if (!empty($config['test'])) {
+                // test listener will replace the exist session listener
```
Comment (OskarStark) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]:
```suggestion
                // test listener will replace the existing session listener
```

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 2]
```diff
@@ -350,6 +350,11 @@ public function load(array $configs, ContainerBuilder $container)
...
+                // we are aliasing to avoid duplicated registered events
```
Comment (OskarStark) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]:
```suggestion
                // as we are aliasing to avoid duplicated registered events
```

**Comment by alexander-schranz** [comment]
@mhujer Thank you for testing!

**Review by chalasr — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @alexander-schranz.
