### PR TITLE
[Serializer] Fix deserializing nested arrays of objects with mixed keys

### LINKED ISSUE #50675: Version v5.4.24 of symfony/property-info broke ArrayDenormalizer
### Symfony version(s) affected

v5.4.24

### Description

I have an array with numeric keys to denormalize, and the property the data will be assigned to is a [Doctrine ArrayCollection](https://github.com/doctrine/collections/blob/2.1.x/src/ArrayCollection.php). Previous to this release denormalization worked fine, but now this denormalization exception is collected:

```
Symfony\Component\Serializer\Exception\NotNormalizableValueException object
 currentType => string "int" (3)
 expectedTypes => array(1)
   integer 0 => string "string" (6)
 path => string "[0].answerOptions[0]" (20)
 useMessageForUser => true
 message => string "The type of the key "0" must be "string" ("int" given)." (55)
 code => integer 0
 file => string "path/to/symfony/serializer/Exception/NotNormalizableValueException.php" (98)
 line => integer 31
```

The exception is thrown in the ArrayDenormalizer class in line 58.

### How to reproduce

I can see that the [ArrayDenormalizerTest](https://github.com/symfony/symfony/blob/v5.4.24/src/Symfony/Component/Serializer/Tests/Normalizer/ArrayDenormalizerTest.php) class doesn't test arrays with numeric keys or no specified keys at all, so that might be the place to start.

The PhpDocExtractor does seem to extract both int and string correctly from the property but because they are passed individually to the ArrayDenormalizer, it fails when $context['key_type'] is 'string'.

### Possible Solution

The right solution is probably to update the type check in the ArrayDenormalizer class to check all possible types rather than just the key_type value.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #50675
| License       | MIT
| Doc PR        | -

Currently an error is thrown when trying to deserialize the following nested array of objects:

```php
use Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ArrayDenormalizer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

$serializer = new Serializer([
    new ObjectNormalizer(null, null, null, new PhpDocExtractor()),
    new ArrayDenormalizer(),
], ['json' => new JsonEncoder()]);

class Outer
{
    /**
     * @var array<int|string, Inner>
     */
    public array $inners;
}

class Inner
{
    public string $name;
}

$serializer->deserialize('{"inners": {"1": {"name": "One"}, "two": {"name": "Two"}}}', Outer::class, 'json');
```

```
Fatal error: Uncaught Symfony\Component\Serializer\Exception\NotNormalizableValueException:
The type of the key "two" must be "int" ("string" given).
```

The same happens when using generics, e.g. `ArrayCollection<Inner>`.

### CODE REVIEW

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 1]
```diff
@@ -533,6 +533,7 @@ private function validateAndDenormalize(array $types, string $currentClass, stri
 
                     if (\count($collectionKeyType = $type->getCollectionKeyTypes()) > 0) {
                         [$context['key_type']] = $collectionKeyType;
```
Comment (HypeMC) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: Not sure what to do about the `key_type` option, should it be deprecated in 6.4?

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: Can't we reuse key_type? When there's only one, we keep as is, and when there are more, we go with an array?

Comment (HypeMC) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: Yes, we could, but wouldn't that be BC break since we would be changing the expected type? Or does that not count for internal parameters like this one?

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: from what I understand, this was broken already for union types so :shrug:

Comment (HypeMC) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: Done

**Review by nicolas-grekas — COMMENTED** [review]
Can you check the follow patch please?

<details>

```diff
diff --git a/src/Symfony/Component/Serializer/Normalizer/ArrayDenormalizer.php b/src/Symfony/Component/Serializer/Normalizer/ArrayDenormalizer.php
index 05d8b79d1a..dfd023a437 100644
--- a/src/Symfony/Component/Serializer/Normalizer/ArrayDenormalizer.php
+++ b/src/Symfony/Component/Serializer/Normalizer/ArrayDenormalizer.php
@@ -49,9 +49,7 @@ class ArrayDenormalizer implements ContextAwareDenormalizerInterface, Denormaliz
 
         $type = substr($type, 0, -2);
 
-        $builtinTypes = array_map(static function (Type $keyType) {
-            return $keyType->getBuiltinType();
-        }, \is_array($keyType = $context['key_type'] ?? []) ? $keyType : [$keyType]);
+        $builtinTypes = array_map(static function ($keyType) { return $keyType->getBuiltinType(); }, (array) ($context['key_type'] ?? []));
 
         foreach ($data as $key => $value) {
             $subContext = $context;
@@ -109,20 +107,12 @@ class ArrayDenormalizer implements ContextAwareDenormalizerInterface, Denormaliz
      */
     private function validateKeyType(array $builtinTypes, $key, string $path): void
     {
         if (!$builtinTypes) {
             return;
         }
 
-        $unexpectedDataType = true;
         foreach ($builtinTypes as $builtinType) {
             if (('is_'.$builtinType)($key)) {
-                $unexpectedDataType = false;
-                break;
+                return;
             }
         }
 
-        if ($unexpectedDataType) {
-            throw NotNormalizableValueException::createForUnexpectedDataType(sprintf('The type of the key "%s" must be "%s" ("%s" given).', $key, implode('", "', $builtinTypes), get_debug_type($key)), $key, $builtinTypes, $path, true);
-        }
+        throw NotNormalizableValueException::createForUnexpectedDataType(sprintf('The type of the key "%s" must be "%s" ("%s" given).', $key, implode('", "', $builtinTypes), get_debug_type($key)), $key, $builtinTypes, $path, true);
     }
 }
diff --git a/src/Symfony/Component/Serializer/composer.json b/src/Symfony/Component/Serializer/composer.json
index 1b9537f8f8..11e67a8a7e 100644
--- a/src/Symfony/Component/Serializer/composer.json
+++ b/src/Symfony/Component/Serializer/composer.json
@@ -34,7 +34,7 @@
         "symfony/http-kernel": "^4.4|^5.0|^6.0",
         "symfony/mime": "^4.4|^5.0|^6.0",
         "symfony/property-access": "^5.4|^6.0",
-        "symfony/property-info": "^5.4.24|^6.0",
+        "symfony/property-info": "^5.4.24|^6.2.11",
         "symfony/uid": "^5.3|^6.0",
         "symfony/validator": "^4.4|^5.0|^6.0",
         "symfony/var-dumper": "^4.4|^5.0|^6.0",
@@ -47,7 +47,7 @@
         "phpdocumentor/type-resolver": "<1.4.0",
         "symfony/dependency-injection": "<4.4",
         "symfony/property-access": "<5.4",
-        "symfony/property-info": "<5.4.24",
+        "symfony/property-info": "<5.4.24|>=6,<6.2.11",
         "symfony/uid": "<5.3",
         "symfony/yaml": "<4.4"
     },
```

</details>

File: src/Symfony/Component/Serializer/composer.json [hunk 2]
```diff
@@ -34,7 +34,7 @@
         "symfony/http-kernel": "^4.4|^5.0|^6.0",
         "symfony/mime": "^4.4|^5.0|^6.0",
         "symfony/property-access": "^5.4|^6.0",
-        "symfony/property-info": "^5.3.13|^6.0",
+        "symfony/property-info": "^5.4.24|^6.0",
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/composer.json]: "^5.4.24|^6.2.11" I guess, but can you confirm that 6.3.0 contains the fix we're needing here?

Comment (HypeMC) [reply src/Symfony/Component/Serializer/composer.json]: @nicolas-grekas Did you mean "^5.4.26|^6.2.13"? Also, 6.3.0 does not have this fix, so I'm guessing it should be "^5.4.26|^6.2.13|^6.3.2".

Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/composer.json]: I'm wondering why this change is needed at all: this PR patches only Serializer, not PropertyInfo.
Do you remember?

**Comment by HypeMC** [comment]
> Can you check the follow patch please?

@nicolas-grekas The following part won't work:

```diff
-        $builtinTypes = array_map(static function (Type $keyType) {
-            return $keyType->getBuiltinType();
-        }, \is_array($keyType = $context['key_type'] ?? []) ? $keyType : [$keyType]);
+        $builtinTypes = array_map(static function ($keyType) { return $keyType->getBuiltinType(); }, (array) ($context['key_type'] ?? []));
 ```

`$context['key_type']` is not a scalar but an instance of `\Symfony\Component\PropertyInfo\Type`.

File: src/Symfony/Component/Serializer/composer.json (hunk 2 above)
Comment (HypeMC) [reply src/Symfony/Component/Serializer/composer.json]: Yes, this fix requires #49557 to work. Without it the tests fail with lowest deps.

Comment (HypeMC) [reply src/Symfony/Component/Serializer/composer.json]: But yeah, you were right, it's "^5.4.24|^6.2.11", got a little confused for a second.

Comment (HypeMC) [reply src/Symfony/Component/Serializer/composer.json]: Done

**Comment by nicolas-grekas** [comment]
Thank you @HypeMC.
