### PR TITLE
[Serializer] Fix `ObjectNormalizer` gives warnings on normalizing with public static property

### LINKED ISSUE #58221: [Serializer] ObjectNormalizer gives warnings on normalizing object with static array property
### Symfony version(s) affected

7.1.4

### Description

Calling the ->normalize() on an object with a static array property causes a warning:
Undefined property: App\Tests\Unit\TestClass::$foo

This used to work on 7.1.1. This is  caused by:

https://github.com/symfony/symfony/blob/v7.1.4/src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php#L180

Working code:

https://github.com/symfony/symfony/blob/v7.1.1/src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php#L180

### How to reproduce

````
class ObjectNormalizerTest extends \PHPUnit\Framework\TestCase
{
    public function testNormalizing(): void
    {
        $normalizer = new ObjectNormalizer(new ClassMetadataFactory(new AttributeLoader()));
        $test = new TestClass;
        $normalizer->normalize($test);
    }
}

class TestClass
{
    public static array $foo = ['bar'];
}
`
```

### Possible Solution

_No response_

### Additional Context

A stack trace showing how we  get to the issue in PropertyAccessor:

```
#0 /opt/projects/zumba//vendor/symfony/property-access/PropertyAccessor.php(323): Symfony\Component\PropertyAccess\PropertyAccessor->readProperty()
#1 /opt/projects/zumba//vendor/symfony/property-access/PropertyAccessor.php(222): Symfony\Component\PropertyAccess\PropertyAccessor->readPropertiesUntil()
#2 /opt/projects/zumba//vendor/symfony/serializer/Normalizer/ObjectNormalizer.php(181): Symfony\Component\PropertyAccess\PropertyAccessor->isReadable()
#3 /opt/projects/zumba//vendor/symfony/serializer/Normalizer/AbstractNormalizer.php(245): Symfony\Component\Serializer\Normalizer\ObjectNormalizer->isAllowedAttribute()
#4 /opt/projects/zumba//vendor/symfony/serializer/Normalizer/ObjectNormalizer.php(148): Symfony\Component\Serializer\Normalizer\AbstractNormalizer->getAllowedAttributes()
#5 /opt/projects/zumba//vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(257): Symfony\Component\Serializer\Normalizer\ObjectNormalizer->getAllowedAttributes()
#6 /opt/projects/zumba//vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(170): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->getAttributes()
#7 /opt/projects/zumba//tests/Unit/ObjectNormalizerTest.php(17): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize()
#8 /opt/projects/zumba//vendor/phpunit/phpunit/src/Framework/TestCase.php(1188): App\Tests\Unit\ObjectNormalizerTest->testNormalizing()
```

### PR DESCRIPTION
**Pull request by alaugks**
| Q             | A           |
|---------------|-------------|
| Branch?       | 6.4 |
| Bug fix?      | yes         |
| New feature?  | no          |
| Deprecations? | no          |
| Issues        | Fix #58221  |
| License       | MIT         |

The error message has been occurring since version 6.4.11/7.1.2. If the condition is changed to version >=7.1.2, the error message no longer occurs.

The error is thrown with the following ObjectNormalizer configuration:

```php
$class = new class {
    public static string $foo = "hallo";
};

$normalizer = new ObjectNormalizer(new ClassMetadataFactory(new AttributeLoader()));
$normalizer->normalize($class);
```

`(\is_object($classOrObject) && $this->propertyAccessor->isReadable($classOrObject, $attribute))` is true and therefore the entire condition is true.

I moved the condition into a method to improve readability and reduce complexity.

All serializer tests are successful.

### Condition

For better readability here with breaks.

**7.1.1**
https://github.com/symfony/symfony/blob/v7.1.1/src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php#L180
```php
if (!isset(self::$isReadableCache[$class.$attribute])) {
    self::$isReadableCache[$class.$attribute] =
    $this->propertyInfoExtractor->isReadable($class, $attribute)
    || $this->hasAttributeAccessorMethod($class, $attribute);
}
```

**>=7.2.2**
https://github.com/symfony/symfony/blob/v7.1.2/src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php#L180
```php
if (!isset(self::$isReadableCache[$class.$attribute])) {
    self::$isReadableCache[$class.$attribute] =
    (\is_object($classOrObject) && $this->propertyAccessor->isReadable($classOrObject, $attribute))
    || $this->propertyInfoExtractor->isReadable($class, $attribute)
    || $this->hasAttributeAccessorMethod($class, $attribute);
}
```

**Fixed condition**
```php
if (!isset(self::$isReadableCache[$class.$attribute])) {
    self::$isReadableCache[$class.$attribute] =
    $this->propertyInfoExtractor->isReadable($class, $attribute)
    || $this->hasAttributeAccessorMethod($class, $attribute)
    || (\is_object($classOrObject) && $this->propertyAccessor->isReadable($classOrObject, $attribute));
}
```

### CODE REVIEW

**Comment by xabbuh** [comment]
Does this also affect 6.4?

File: src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php [hunk 1]
```diff
@@ -953,6 +953,21 @@ public function testDenormalizeWithPropertyPath()
...
+            public static string $foo;
+        };
+
+        try {
+            $normalizer = new ObjectNormalizer(new ClassMetadataFactory(new AttributeLoader()));
+            $normalizer->normalize($class);
+            $this->expectNotToPerformAssertions();
+        } catch (\Exception $e) {
+            $this->fail($e->getMessage());
+        }
```
Comment (alexandre-daubois) [inline src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php]: You can remove the try-catch, the test will fail no matter what if an exception is raised somewhere

**Comment by alaugks** [comment]
@xabbuh It also affects 6.4. I have tested it with v6.4.11.

**Comment by alaugks** [comment]
@alexandre-daubois try-catch is removed. However, I have left `expectNotToPerformAssertions()` in the test so that the test is not marked with "This test did not perform any assertions".

**Comment by alexandre-daubois** [comment]
> @xabbuh It also affects 6.4. I have tested it with v6.4.11.

You may rebase your PR onto 6.4 and change the target branch of the PR. This way, the fix is available on all (still supported) affected branches

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php [hunk 2]
```diff
@@ -213,4 +213,21 @@ private function hasAttributeAccessorMethod(string $class, string $attribute): b
             && !$method->getAttributes(Ignore::class)
             && !$method->getNumberOfRequiredParameters();
     }
+
+    private function isReadableCache(object|string  $class, object|string $classOrObject, string $attribute): bool
```
Comment (stof) [inline src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]: having `Cache` in the name does not make sense to me. This method should be name `isReadable` according to what it does. This method is not about caching at all.

Comment (stof) [inline src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]: can `$class` actually be an object ? AFAICT, the caller always pass a string there

Comment (alaugks) [reply src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]: Yes, `$class` can be a string. So `object|string` is not correct.

I created a branch as I had it first, before I had committed the PR. Here the [Example](https://github.com/symfony/symfony/commit/719e49655d277639ccf6f6ec54da64d8b2294f9c).

But I think it iss more important that when there are too much adjustments, the condition is no longer on one line, but with line breaks. This is clearer and helps to avoid possible merge conflicts.

```php
if (!isset(self::$isReadableCache[$class.$attribute])) {
    self::$isReadableCache[$class.$attribute] = $this->propertyInfoExtractor->isReadable($class, $attribute)
        || $this->hasAttributeAccessorMethod($class, $attribute)
        || (\is_object($classOrObject) && $this->propertyAccessor->isReadable($classOrObject, $attribute));
}
```

Comment (alaugks) [reply src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php:217]: `isReadable is better`. I could not decide.

Comment (alaugks) [reply src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]: I named the method `isReadableCache()` because the condition referred to `$isReadableCache`. But it is actually an `isReadable`.

File: src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php [hunk 3]
```diff
@@ -953,6 +953,17 @@ public function testDenormalizeWithPropertyPath()
...
+
+    public function testObjectNormalizerWithAttributeLoaderAndObjectHasStaticProperty()
+    {
+        $class = new class {
+            public static string $foo;
+        };
+
+        $normalizer = new ObjectNormalizer(new ClassMetadataFactory(new AttributeLoader()));
+        $normalizer->normalize($class);
+        $this->expectNotToPerformAssertions();
```
Comment (xabbuh) [inline src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php]: There should be some assertion on what we expect as the result instead.

Comment (alaugks) [reply src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php]: Good point. I looked again and found `expectNotToPerformAssertions()`. I only had the methods `expectException*()` in mind, which assert when an exception is thrown. This is clearer.

```php
public function testObjectNormalizerWithAttributeLoaderAndObjectHasPublicStaticProperty()
{
    $this->expectNotToPerformAssertions();

    $class = new class {
        public static string $foo;
    };

    $normalizer = new ObjectNormalizer(new ClassMetadataFactory(new AttributeLoader()));
    $normalizer->normalize($class);
}
```

Comment (xabbuh) [reply src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php]: What I mean is passing the normalizer result to `assertSame()`. This will document how static properties are treated during normalisation.

Comment (alaugks) [reply src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php:965]: I have adjusted the title and description of the PR. If the property is **public** and static, an exception is thrown. So nothing can be checked. Therefore, the result of normalise() cannot be tested.

Comment (xabbuh) [reply src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php]: Then the test is missing a call of `expectException()`.

Comment (alaugks) [reply src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php:965]: _// I had deleted my comment._
I have adjusted the title and description of the PR. If the property is **public** and static, an exception is thrown. So nothing can be checked. Therefore the test that no exception is thrown.

> Then the test is missing a call of `expectException()`.

I have to correct myself. The result of `normalizer()` is an empty array if the exception is not thrown. For whatever reason. I have not checked this yet. 

No exception must be thrown. Due to the current state, the exception is thrown because `$foo` is considered cachable. This cache is being accessed, causing the exception. 

The question is whether the exception should be thrown at all? Is this the desired behaviour? I am not sure at the moment.

The condition was included in v6.4.9. In v7.0.0 the ObjectNormalizer was rebuilt/adapted. In v7.1.12 the condition was reintroduced as is.

Comment (alaugks) [reply src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php:965]: One more hint. The error occurs with the following ObjectNormalizer configuration:

```php
new ObjectNormalizer(new ClassMetadataFactory(new AttributeLoader()))
```

Comment (alaugks) [reply src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php]: > Then the test is missing a call of `expectException()`.

I misunderstood your comment. I thought I should test for an exception, but you wrote "missing a call of". 

The approach in PHPUnit would be to use try-catch, but I should remove that. I can reverse it.

`normalise()` returns an empty array, regardless of the type of the static property. Therefore, an `assertSame()` does not make an are, because it is not relevant either, but rather that the exception is not thrown. 

```php
try {
    $class = new class {
        public static string $foo;
    };
    
    $normalizer = new ObjectNormalizer(new ClassMetadataFactory(new AttributeLoader()));
    $normalizer->normalize($class);

    $this->assertTrue(true);
} catch (\Exception $e) {
    $this->fail($e->getMessage());
}
```

Comment (xabbuh) [reply src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php]:
```php
$this->assertSame([], $normalizer->normalize($class));
```

IMO having such an assertion is useful since we will ensure this way that static properties are not part of the normalised result.

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php (hunk 2 above)
Comment (alaugks) [reply src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php:217]: @stof Can you please give me some feedback?

File: src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php (hunk 3 above)
Comment (alaugks) [reply src/Symfony/Component/Serializer/Tests/Normalizer/ObjectNormalizerTest.php]: I still have the title of the ticket in my head that it comes with an array the error message. But yes, static properties are not processed at all. So the array is always empty during the test.

The structure of the test should now be as follows?

```php
public function testObjectNormalizerWithAttributeLoaderAndObjectHasStaticProperty()
{
    $class = new class {
        public static string $foo;
    };

    $normalizer = new ObjectNormalizer(new ClassMetadataFactory(new AttributeLoader()));
    $this->assertSame([], $normalizer->normalize($class));
}
```

File: src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php (hunk 2 above)
Comment (dunglas) [inline src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]: Could we remove this function and keep the check inlined? It's on the hot path, an extra function call can have significant effects on performance.

Comment (alaugks) [reply src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php]: I have revert the check to inline. I have also adjusted the [Test](https://github.com/symfony/symfony/pull/58255#discussion_r1780058718).

**Review by xabbuh — APPROVED** [review]
LGTM

**Comment by nicolas-grekas** [comment]
Thank you @alaugks.
