### PR TITLE
[Config] Improve GlobResource performance

### LINKED ISSUE #46046: [Config] GlobResource causes out of memory errors
### Symfony version(s) affected

^5 || ^6

### Description

There are multiple ways to cause out of memory error while iterating over enough files through a `GlobResource`.

### How to reproduce

Using one of them (assuming there is enough files under `/`).

`$resource = new GlobResource('/', '**');`
`$resource = new GlobResource('/', '/**/');`

`foreach ($resource as $_);`

### PR DESCRIPTION
**Pull request by Jean-Beru**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no
| Tickets       | Fix #46046
| License       | MIT
| Doc PR        | 

This PR improves performance when `GlobResource` uses the `Finder` component to retrieve files (for example when using `/**/` pattern) and not all files are returned.

See Blackfire profiles with a structure with 100k files: 
```
1/
  10/
    100/ => 1000 files
    101/ => 1000 files
    ...
    109/ => 1000 files
  11/
    ...
  ...
  19/
    ...
```

With `/**/*` pattern (100% matches): https://blackfire.io/profiles/compare/42c7d5ab-4dd8-4f48-8ef0-51f18ec268e0/graph
With `/1/{10,12,14,16,18}/**/*` pattern (50% matches): https://blackfire.io/profiles/compare/ed905c14-6e93-445e-bfb7-81841e3242e9/graph
With `/1/**/*1.txt` pattern (10% matches): https://blackfire.io/profiles/compare/1530e17e-e051-4846-881a-f5461f82cd2a/graph

### CODE REVIEW

File: src/Symfony/Component/Config/Resource/GlobResource.php [hunk 1]
```diff
@@ -167,28 +167,31 @@ function (\SplFileInfo $file, $path) {
...
-                } while ($prefix !== $dirPath && $dirPath !== $normalizedPath = \dirname($dirPath));
-            }
 
-            yield $path => $info;
-        }
+        yield from (new Finder())
+            ->followLinks()
+            ->filter(function (\SplFileInfo $info) use ($regex, $prefixLen, $prefix) {
+                $normalizedPath = str_replace('\\', '/', $info->getPathname());
+                if (!$info->isFile() || !preg_match($regex, substr($normalizedPath, $prefixLen))) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Config/Resource/GlobResource.php]: Did you swap the operands on purpose? isn't preg_match faster than isFile?

Comment (Jean-Beru) [reply src/Symfony/Component/Config/Resource/GlobResource.php]: Good catch! I made some tests and It seems that `preg_match` + `substr` is faster than `isFile`.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @Jean-Beru.
