### PR TITLE
[WebProfilerBundle] Fix error with custom function and web profiler routing tab

### LINKED ISSUE #36985: Custom functions in route condition cause error in WebProfiler
**Symfony version(s) affected**: 5.0.8

**Description**  
Adding custom function (via tag `routing.expression_language_provider`) causes fatal error in the routing tab of the profiler: the function does not exist.
If the route does not match, no errors

**How to reproduce**  
https://github.com/JakeFr/function-in-routing
query GET:/api?foo[bar]=baz
and go to the routing tab in profiler

**Possible Solution**  
Related to the AddExpressionLanguageProvidersPass, UrlMatcher and TraceableUrlMatcher but i cant find how to fix

### PR DESCRIPTION
**Pull request by JakeFr**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36985
| License       | MIT
| Doc PR        | no

Here is a simple solution for #36985 as it only concerns WebProfilerBundle.

Due to the limitation in the routing tab as explained in the footnote, the route in my repo did not match in profiler (no query string in the new context) but there is no more syntax error.

### CODE REVIEW

File: src/Symfony/Bundle/WebProfilerBundle/Controller/RouterController.php [hunk 1]
```diff
@@ -36,11 +37,17 @@ class RouterController
     private $matcher;
     private $routes;
 
-    public function __construct(Profiler $profiler = null, Environment $twig, UrlMatcherInterface $matcher = null, RouteCollection $routes = null)
+    /**
+     * @var ExpressionFunctionProviderInterface[]
+     */
+    private $expressionLanguageProviders = [];
+
+    public function __construct(Profiler $profiler = null, Environment $twig, UrlMatcherInterface $matcher = null, iterable $expressionLanguageProviders = [], RouteCollection $routes = null)
```
Comment (JakeFr) [inline src/Symfony/Bundle/WebProfilerBundle/Controller/RouterController.php:45]: I can find where/when the $routes argument is set. So i add the new one just befrore

Comment (nicolas-grekas) [reply src/Symfony/Bundle/WebProfilerBundle/Controller/RouterController.php:45]: please add it last, that's a BC break otherwise

Comment (JakeFr) [reply src/Symfony/Bundle/WebProfilerBundle/Controller/RouterController.php:45]: How do I define argument "$routes" in profiler.xml ?

Comment (JakeFr) [reply src/Symfony/Bundle/WebProfilerBundle/Controller/RouterController.php]: I declare routes explicitly to null

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @JakeFr.
