### PR TITLE
[Form] Fix EnumType choice_label logic for grouped choices

### LINKED ISSUE #62234: symfony/form regression
### Symfony version(s) affected

7.3.5 (possibly also 6.4.27)

### Description

See https://github.com/symfony/symfony/pull/61928#issuecomment-3468482629

### How to reproduce

Group options don't work properly with release 7.3.5 of symfony/form

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by yoeunes**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62234
| License       | MIT

This PR fixes a regression in the `EnumType`'s default `choice_label` logic.

The previous logic checked `!array_is_list($options['choices'])` to determine if custom labels were provided. If so, it would `return null` to disable the default enum labeler (i.e., `$choice->name`).

However, this check incorrectly matched **grouped choices** (e.g., `['Group 1' => [Answer::Yes]]`), which are also associative arrays. This caused the default labels for enums within groups to break (they became empty).

This fix adds a check to see if the associative array is actually for grouping (by detecting if any value `is_array`) before returning `null`.

Tests are added to cover both:
1.  Grouped choices (verifying the fix).
2.  Custom-labeled choices (verifying no new regression).

### CODE REVIEW

File: src/Symfony/Component/Form/Extension/Core/Type/EnumType.php [hunk 1]
```diff
@@ -31,8 +31,21 @@ public function configureOptions(OptionsResolver $resolver): void
...
+                    // Check for grouped choices
+                    $isGrouped = false;
+                    foreach ($choices as $value) {
+                        if (\is_array($value)) {
+                            $isGrouped = true;
+                            break;
+                        }
+                    }
+                    if (!$isGrouped) {
+                        // Associative array = custom labels
```
Comment (stof) [inline src/Symfony/Component/Form/Extension/Core/Type/EnumType.php]: for grouped cases, should it depend on whether the grouped choices are a list or no ?

Comment (yoeunes) [reply src/Symfony/Component/Form/Extension/Core/Type/EnumType.php]: Hi @stof, I've updated the logic with `array_is_list()`

I also added a new test case, `testGroupedEnumChoicesWithCustomLabels`, which passes and confirms that custom labels within groups are correctly preserved

File: src/Symfony/Component/Form/Tests/Extension/Core/Type/EnumTypeTest.php [hunk 2]
```diff
@@ -311,6 +311,69 @@ public function testChoicesWithLabels()
...
+        ]);
+        $view = $form->createView();
+        $this->assertCount(2, $view->vars['choices']['Group 1']->choices);
+        $this->assertSame('Yes', $view->vars['choices']['Group 1']->choices[0]->label);
+        $this->assertSame('No', $view->vars['choices']['Group 1']->choices[1]->label);
+        $this->assertCount(1, $view->vars['choices']['Group 2']->choices);
+        $this->assertSame('FourtyTwo', $view->vars['choices']['Group 2']->choices[2]->label);
+    }
+
+    public function testEnumChoicesWithCustomLabels()
```
Comment (HypeMC) [inline src/Symfony/Component/Form/Tests/Extension/Core/Type/EnumTypeTest.php]: Isn't this the same as `testChoicesWithLabels()` ?

File: src/Symfony/Component/Form/Extension/Core/Type/EnumType.php [hunk 3]
```diff
@@ -31,8 +31,21 @@ public function configureOptions(OptionsResolver $resolver): void
             ->setAllowedValues('class', enum_exists(...))
             ->setDefault('choices', static fn (Options $options): array => $options['class']::cases())
             ->setDefault('choice_label', static function (Options $options) {
-                if (\is_array($options['choices']) && !array_is_list($options['choices'])) {
-                    return null;
+                $choices = $options['choices'];
+
+                if (\is_array($choices) && !array_is_list($choices)) {
```
Comment (HypeMC) [inline src/Symfony/Component/Form/Extension/Core/Type/EnumType.php]: What happens if you have a mix of grouped and non-grouped choices, for example:

```php
'choices' => [
    'Group 1' => [
        'Custom Yes' => Answer::Yes,
        'Custom No' => Answer::No,
    ],
    'Custom 42' => Answer::FortyTwo,
],
```

Also, what if you have a mix of labeled and unlabeled choices:

```php
'choices' => [
    Answer::Yes,
    Answer::No,
    'Custom 42' => Answer::FortyTwo,
],
```

Comment (yoeunes) [reply src/Symfony/Component/Form/Extension/Core/Type/EnumType.php]: hi @HypeMC, thank you for your feedback!

I have improved the logic and added tests for grouped and custom-labeled Enum choices.

For hybrid cases (mixing grouped, non-grouped, labeled, and non-labeled choices), the expected behavior isn’t so clear.

Should we make it flexible and auto-detect labels, or do you prefer a strict approach (numeric indexes for non-labeled, labels only if set)?
What do you think is best for EnumType in Symfony?

**Review by HypeMC — APPROVED** [review]

File: src/Symfony/Component/Form/Extension/Core/Type/EnumType.php (hunk 3 above)
Comment (HypeMC) [reply src/Symfony/Component/Form/Extension/Core/Type/EnumType.php]: This approach makes sense to me. Let's see what others think.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @yoeunes.
