### PR TITLE
[PropertyInfo] fail with a meaningful error when a needed package is missing

### LINKED ISSUE #49123: [PropertyInfo] PhpStanExtractor does not check for dependency package
### Symfony version(s) affected

6.2.5

### Description

The `\Symfony\Component\PropertyInfo\PhpStan\NameScopeFactory` has a dependency on `\phpDocumentor\Reflection\Types\ContextFactory` but that is very clear when using the `\Symfony\Component\PropertyInfo\Extractor\PhpStanExtractor` and it will throw an error when doing it. 

The `\Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor` fails with a more clear exception. 

### How to reproduce

```php
// First, run "composer require symfony/property-info"
// and "composer require phpstan/phpdoc-parser"
// Then, execute this file:
<?php

require 'vendor/autoload.php';

class Role
{
    public function __construct(
        public readonly string $name,
    ) {
    }
}

class User
{
    /**
     * @param list<Role> $roles
     */
    public function __construct(
        public readonly array $roles,
    ) {
    }
}

$extractor = new \Symfony\Component\PropertyInfo\Extractor\PhpStanExtractor();
$types = $extractor->getTypes(User::class, 'roles');

// It will throw an error about an hidden dependency on \phpDocumentor\Reflection\Types\ContextFactory::class
```

### Possible Solution

Add to the constructor of the PhpStanExtractor a check like in the PhpDocExtractor

```php
final class PhpStanExtractor implements PropertyTypeExtractorInterface, ConstructorArgumentTypeExtractorInterface 
{
...        
    public function __construct(array $mutatorPrefixes = null, array $accessorPrefixes = null, array $arrayMutatorPrefixes = null)
    {
        if (!class_exists(\phpDocumentor\Reflection\Types\ContextFactory::class)) {
            throw new \LogicException(sprintf('Unable to use the "%s" class as the "phpdocumentor/reflection-docblock" package is not installed.', __CLASS__));
        }
...
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49123
| License       | MIT
| Doc PR        |

### CODE REVIEW

File: src/Symfony/Component/PropertyInfo/Extractor/PhpStanExtractor.php [hunk 1]
```diff
@@ -59,6 +60,10 @@ final class PhpStanExtractor implements PropertyTypeExtractorInterface, Construc
      */
     public function __construct(array $mutatorPrefixes = null, array $accessorPrefixes = null, array $arrayMutatorPrefixes = null)
     {
+        if (!class_exists(ContextFactory::class)) {
+            throw new \LogicException(sprintf('Unable to use the "%s" class as the "phpdocumentor/type-resolver" package is not installed.', __CLASS__));
```
Comment (derrabus) [inline src/Symfony/Component/PropertyInfo/Extractor/PhpStanExtractor.php]: In exceptions like this one, we usually suggest a Composer command to run to fix the problem, don't we?

**Review by dunglas — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.
