### PR TITLE
[Console] Remove ``exec`` and replace it by ``shell_exec``

### LINKED ISSUE #49646: [Console] Terminal::hasSttyAvailable() checks availability of exec but then all calls are made via shell_exec
### Symfony version(s) affected

6.2.7

### Description

Error message:
- `Error: Call to undefined function Symfony\Component\Console\shell_exec() in /{path_to_project}/vendor/symfony/console/Application.php:989 `
- https://github.com/symfony/console/blob/cbad09eb8925b6ad4fb721c7a179344dc4a19d45/Application.php#L989

`Terminal:hasSttyAvailable()` checks for availability of `exec`
- https://github.com/symfony/console/blob/cbad09eb8925b6ad4fb721c7a179344dc4a19d45/Terminal.php#L120-L134

However, all calls inside the condition are then run using `shell_exec` and that fails when it is disabled.
- https://github.com/symfony/console/blob/cbad09eb8925b6ad4fb721c7a179344dc4a19d45/Application.php#L988-L996

One might argue that it does not make much sense to have one function enabled and the other disabled, but apparently it can happen and then it fails.

Or am I missing something? :)

### How to reproduce

Have a system, that has:
- exec enabled
- shell_exec disabled
- symfony/console installed
- symfony/events installed (otherwise checks for dispatcher fail and a different route in the code is taken that will not manifest the problem)

Then try to run the symfony console from command line. 

### Possible Solution

Either check availability of `shell_exec` in `Terminal::hasSttyAvailable()` or change all calls to use `exec`.

### Additional Context

The check has been introduced here:
- https://github.com/symfony/symfony/pull/37466

### PR DESCRIPTION
**Pull request by maxbeckers**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49646
| License       | MIT
| Doc PR        | n/a

It could happen an error like `Error: Call to undefined function Symfony\Component\Console\shell_exec() in /{path_to_project}/vendor/symfony/console/Application.php:989 ` when `exec` is available but `shell_exec` not. There is very often used the check `Terminal::hasSttyAvailable()` in the symfony codebase and then `shell_exec` used.

More Details see in the issue #49646.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Can't we use `exec` everywhere instead?

**Comment by maxbeckers** [comment]
I could try this ... give me a bit of time for that, could become a bigger PR :)

File: src/Symfony/Component/Console/Helper/QuestionHelper.php [hunk 1]
```diff
@@ -417,8 +417,8 @@ private function getHiddenResponse(OutputInterface $output, $inputStream, bool $
                 $exe = $tmpExe;
             }
 
-            $sExec = shell_exec('"'.$exe.'"');
-            $value = $trimmable ? rtrim($sExec) : $sExec;
+            $sExec = exec('"'.$exe.'"');
+            $value = $trimmable ? rtrim($sExec) : $sExec . PHP_EOL; // add PHP_EOL to keep the same result as shell_exec
```
Comment (maxbeckers) [inline src/Symfony/Component/Console/Helper/QuestionHelper.php]: Do we need this or can this be ignored @nicolas-grekas ?

Comment (chalasr) [reply src/Symfony/Component/Console/Helper/QuestionHelper.php]: I don't think so: `rtrim()` would have removed it before this patch

File: src/Symfony/Component/Console/Tests/Helper/QuestionHelperTest.php [hunk 2]
```diff
@@ -430,7 +430,7 @@ public function testAskHiddenResponse()
         $this->assertEquals('8AM', $dialog->ask($this->createStreamableInputInterfaceMock($this->getInputStream("8AM\n")), $this->createOutputInterface(), $question));
     }
 
-    public function testAskHiddenResponseTrimmed()
+    public function testAskHiddenResponseNotTrimmed()
```
Comment (chalasr) [inline src/Symfony/Component/Console/Tests/Helper/QuestionHelperTest.php:433]: this test was valid before the patch, it should keep passing as-is with it

File: src/Symfony/Component/Console/Helper/QuestionHelper.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Console/Helper/QuestionHelper.php]: I played a bit with exec vs shell_exec and what the php doc says is correct: lines are trimmed when using exec.
That means using it would break answers with trailing spaces.
The only way is using shell_exec indeed.
What about doing the reverse and always using shell_exec everywhere, including in the function_exists check?

Comment (chalasr) [reply src/Symfony/Component/Console/Helper/QuestionHelper.php]: 👍 exec would break multiline answers as well since it only returns the last line

File: src/Symfony/Component/Console/Tests/Helper/QuestionHelperTest.php (hunk 2 above)
Comment (maxbeckers) [reply src/Symfony/Component/Console/Tests/Helper/QuestionHelperTest.php:433]: @chalasr yes it did pass. I just optimized the test, because it was called `testAskHiddenResponseTrimmed` and `$question->setTrimmable(false);` was set so it's more a not trimmed. And I added the EOL to see that the end is also not trimmed.

But I'll make it parameterized with a DataProvider to keep the old test also.

Comment (chalasr) [reply src/Symfony/Component/Console/Tests/Helper/QuestionHelperTest.php:433]: 🤦 thanks

File: src/Symfony/Component/Console/Helper/QuestionHelper.php (hunk 1 above)
Comment (maxbeckers) [reply src/Symfony/Component/Console/Helper/QuestionHelper.php]: @nicolas-grekas in `QuestionHelper::isInteractiveInput` for example we use `exec` to also get the result code.

Multiline answers would be possibe using the $output array, I indeed forgot to check this.

Comment (nicolas-grekas) [reply src/Symfony/Component/Console/Helper/QuestionHelper.php]: I think we can use $output instead: it's going to be empty if stty fails:
`'' === trim(shell_exec(...))`

File: src/Symfony/Component/Console/Helper/QuestionHelper.php [hunk 3]
```diff
@@ -500,13 +500,11 @@ private function isInteractiveInput($inputStream): bool
...
 
-        if (!\function_exists('exec')) {
+        if (!\function_exists('shell_exec')) {
             return self::$stdinIsInteractive = true;
         }
 
-        exec('stty 2> /dev/null', $output, $status);
-
-        return self::$stdinIsInteractive = 1 !== $status;
+        return self::$stdinIsInteractive = is_string(shell_exec('stty 2> /dev/null'));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Helper/QuestionHelper.php]:
```suggestion
        return self::$stdinIsInteractive = (bool) shell_exec('stty 2> /dev/null');
```

File: src/Symfony/Component/Console/Terminal.php [hunk 4]
```diff
@@ -64,14 +64,12 @@ public static function hasSttyAvailable(): bool
...
-        if (!\function_exists('exec')) {
+        // skip check if shell_exec function is disabled
+        if (!\function_exists('shell_exec')) {
             return false;
         }
 
-        exec('stty 2>&1', $output, $exitcode);
-
-        return self::$stty = 0 === $exitcode;
+        return self::$stty = (bool) shell_exec('stty 2>&1');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Terminal.php]: should be `stty 2> /dev/null` I think now

File: src/Symfony/Component/Console/Tests/TerminalTest.php [hunk 5]
```diff
@@ -77,8 +77,8 @@ public function testSttyOnWindows()
             $this->markTestSkipped('Must be on windows');
         }
 
-        $sttyString = exec('(stty -a | grep columns) 2>&1', $output, $exitcode);
-        if (0 !== $exitcode) {
+        $sttyString = shell_exec('(stty -a | grep columns) 2>&1');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Tests/TerminalTest.php]:
```suggestion
        $sttyString = shell_exec('(stty -a | grep columns) 2> /dev/null');
```

File: src/Symfony/Component/Console/Terminal.php (hunk 4 above)
Comment (maxbeckers) [reply src/Symfony/Component/Console/Terminal.php]: This would change a bit the behavior, at least on windows (using GitBash):

Example code:
```
        exec('stty 2>&1', $output, $exitcode);
        var_dump(0 === $exitcode);
        var_dump((bool) shell_exec('stty 2> /dev/null'));
```

Result:
```
bool(true)
The System Cannot Find The Path Specified.
bool(false)
```

Comment (nicolas-grekas) [reply src/Symfony/Component/Console/Terminal.php]: what a mess!
Can you try this instead?
`command -v stty >/dev/null 2>&1 && stty 2> /dev/null`

File: src/Symfony/Component/Console/Tests/TerminalTest.php (hunk 5 above)
Comment (maxbeckers) [reply src/Symfony/Component/Console/Tests/TerminalTest.php]: This is only for windows so i changes to `NUL`

File: src/Symfony/Component/Console/Terminal.php (hunk 4 above)
Comment (maxbeckers) [reply src/Symfony/Component/Console/Terminal.php]: I found a way, working on windows. Please have a look if it's fine for you.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @maxbeckers.
