### PR TITLE
[Lock] Release Locks from Internal Store on Postgres waitAndSave*

### LINKED ISSUE #45505: DoctrineDbalPostgreSqlStore Does Not Release Internal Store Lock if waitAndSave Fails
### Symfony version(s) affected

5.4

### Description

If a call to `$lock->acquire(true)` errors, DoctrineDbalPostgreSqlStore doesn't relase it's internal store lock and prevents further locks from being acquired by the same process.

There's another ticket that fixes the same issue in `save` and `saveRead` here: https://github.com/symfony/symfony/pull/44828

### How to reproduce

```php
use Doctrine\DBAL\DriverManager;
use Symfony\Component\Lock\LockFactory;
use Symfony\Component\Lock\Store\DoctrineDbalPostgreSqlStore;


$connection = DriverManager::getConnection(['url' => getenv('DATABASE_URL')]);
$lockFactory = new LockFactory(new DoctrineDbalPostgreSqlStore($connection));

// set a very low statement time out so the lock acquisition fails
// this could be any reason for failure like a disconnect and reconnect, etc
// because the connection intance doesn't change and `spl_object_hash` doesn't
// change the underlying internal store won't change
$connection->executeStatement('SET statement_timeout = 1');
$lock1 = $lockFactory->createLock('test');

try {
    $locked = $lock1->acquire(true);
} catch (Exception $e) {
    echo 'error acquring lock: ', get_class($e), PHP_EOL;
}

// no timeout anymore, connection is "fixed" or reconnected, etc
$connection->executeStatement('SET statement_timeout = 0');

$lock2 = $lockFactory->createLock('test');
// this should work, but throws
$lock2->acquire(true);
```

### Possible Solution

Implement the same fix from https://github.com/symfony/symfony/pull/44828 in `waitAnd*` methods.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by chrisguitarguy**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45505 
| License       | MIT
| Doc PR        | n/a

if something goes wrong talking with the database connection (like a
disconnect or timeout) the parent `Lock` object will catch and simply
say that there was an error acquring the lock. However, waitAndSave and
waitAndSaveRead both store the lock in an internal store so trying to
re-acquire the lock with the same connection would result in a lock
confliected exception even though the lock was never acquired in the
first place.

This takes the fix from https://github.com/symfony/symfony/pull/44828
and applies it to the waitAndSave and waitAndSaveRead methods on both
DoctrineDbalPostgreSqlStore and PostgreSqlStore.

### CODE REVIEW

File: src/Symfony/Component/Lock/Tests/Store/PostgreSqlStoreTest.php [hunk 1]
```diff
@@ -78,4 +86,86 @@ public function testSaveAfterConflict()
...
+        } catch (LockConflictedException $lockConflictedException) {
+            $lockConflicted = true;
+        }
+
+        $this->assertFalse($lockConflicted, 'lock should be available now that its been remove from $store1');
+        $this->assertTrue($store2->exists($store2Key));
+    }
+
+    /**
+     * @ticket https://github.com/symfony/symfony/issues/45505
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Lock/Tests/Store/PostgreSqlStoreTest.php]: please remove all similar annotation, we rely on git blame for that instead

File: src/Symfony/Component/Lock/Tests/Store/PostgreSqlStoreTest.php [hunk 2]
```diff
@@ -28,16 +28,24 @@ class PostgreSqlStoreTest extends AbstractStoreTest
     use BlockingStoreTestTrait;
     use SharedLockStoreTestTrait;
 
+    public function getPostgresHost(): string
+    {
+        $host = getenv('POSTGRES_HOST');
+        if (!$host) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Lock/Tests/Store/PostgreSqlStoreTest.php]: `if (!$host = getenv('POSTGRES_HOST')) {`

**Review by nicolas-grekas — APPROVED** [review]
LGTM thanks! I just have two minors CS notes.

**Comment by chrisguitarguy** [comment]
Do I need to worry about that 8.1 low-deps check? Looks like something in the form component failed a git checkout?

**Comment by nicolas-grekas** [comment]
No need to.

**Comment by nicolas-grekas** [comment]
Thank you @chrisguitarguy.
