### PR TITLE
[RateLimiter] Keep token bucket alive while reservation debt is unpaid

### LINKED ISSUE #62688: [RateLimiter] Reserving tokens in token bucket policy is not accounted for after token refill when configured to behave like fixed window policy
### Symfony version(s) affected

First tested at 7.3.2, now retested at 8.0. Possibly dates back to the component's release.

### Description

Rate Limiter component is basically token counter, that includes usage limit. The tokens are refilled every interval accordingly. Once the limit is reached, developer can either stop the action (ie: by throwing an exception), or **reserve** a token and wait for upcoming reset before proceeding. The latter is confirmed by both the documentation and the code description:

> The reserve() method is able to reserve a token in the future.

Source: https://symfony.com/doc/current/rate_limiter.html#wait-until-a-token-is-available

> The reserved tokens will be taken into account when calculating future token consumptions.

Source: https://github.com/symfony/rate-limiter/blob/7e855541d302ba752f86fb0e97932e7969fe9c04/LimiterInterface.php#L25

---

When using `reserve()` with [**Token Bucket** Rate Limiter](https://symfony.com/doc/current/rate_limiter.html#token-bucket-rate-limiter) (`token_bucket`), the token counter doesn't go below zero, as opposed to [fixed window](https://github.com/symfony/symfony/issues/61668). However, when the policy is configured to effectively behave like fixed window, it suffers from the same problem: **The reserved tokens are not accounted for after refill, counting again from full limit. In my finding it's caused by removing the cache, therefore forgetting about the debt.**

### How to reproduce

A fresh Symfony app with the component installed, then just these 2 files:

`config/packages/rate_limiter.yaml`
```yaml
framework:
    rate_limiter:
        reproducer_token_bucket:
            policy: 'token_bucket'
            limit: 10
            rate: { interval: '10 seconds', amount: 10 }
```

`src/TokenBucketReproducerCommand.php`
```php
<?php

declare(strict_types=1);

namespace App;

use Symfony\Component\Console\Attribute\Argument;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\DependencyInjection\Attribute\Target;
use Symfony\Component\RateLimiter\LimiterInterface;
use Symfony\Component\RateLimiter\RateLimiterFactoryInterface;

#[AsCommand(name: 'reproducer:token_bucket')]
final readonly class TokenBucketReproducerCommand
{
    private LimiterInterface $tokenBucketLimiter;

    public function __construct(
        #[Target('reproducer_token_bucket.limiter')]
        RateLimiterFactoryInterface $limiterFactory,
    ) {
        $this->tokenBucketLimiter = $limiterFactory->create();
    }

    public function __invoke(
        #[Argument('Process name')]
        string $name,
        OutputInterface $output,
    ): int {
        $i = 0;
        while (true) {
            $i++;
            $reservation = $this->tokenBucketLimiter->reserve();

            $output->writeln(sprintf(
                '[%s][%s-%d] Waiting... (remaining tokens %s, wait %s',
                (new \DateTimeImmutable())->format('H:i:s.u'),
                $name,
                $i,
                $reservation->getRateLimit()->getRemainingTokens(), $reservation->getWaitDuration(),
            ));
            $reservation->wait();
            $output->writeln(sprintf(
                '[%s][%s-%d] Done.',
                (new \DateTimeImmutable())->format('H:i:s.u'),
                $name,
                $i,
            ));
            usleep(250_000);
        }

        return Command::SUCCESS;
    }
}

```

You can run the command in multiple terminals to increase the token debt, then dump the logs into single file and sort them. The required param is supposed to help distinguish between the processes after mixing the logs.

### Possible Solution

Visual fix to allow available tokens below zero - https://github.com/symfony/rate-limiter/blob/1d4e173cafccecf3fdc167536c33d599f6c1c9e0/Policy/TokenBucketLimiter.php#L103 (reformatted for readibility):

```diff
                $reservation = new Reservation(
                    $now + $waitDuration,
                    new RateLimit(
-                        0,
+                        $availableTokens - $tokens,
                        \DateTimeImmutable::createFromFormat('U', floor($now + $waitDuration)),
                        false,
                        $this->maxBurst
                    )
                );
```

Increase time in cache to remember the debt - https://github.com/symfony/rate-limiter/blob/1d4e173cafccecf3fdc167536c33d599f6c1c9e0/Policy/TokenBucket.php#L83 :

```diff
    public function getExpirationTime(): int
    {
-        return $this->rate->calculateTimeForTokens($this->burstSize);
+        return $this->rate->calculateTimeForTokens($this->burstSize * 2);
    }
```

### Additional Context

Ran the reproducer in 3 terminals at once.

Before fix:
```
[13:42:34.277411][A-1] Waiting... (remaining tokens 9, wait 0
[13:42:34.277644][A-1] Done.
[13:42:34.528351][A-2] Waiting... (remaining tokens 8, wait 0
[13:42:34.528502][A-2] Done.
[13:42:34.543811][B-1] Waiting... (remaining tokens 7, wait 0
[13:42:34.544083][B-1] Done.
[13:42:34.779320][A-3] Waiting... (remaining tokens 6, wait 0
[13:42:34.779465][A-3] Done.
[13:42:34.794795][B-2] Waiting... (remaining tokens 5, wait 0
[13:42:34.794927][B-2] Done.
[13:42:34.829701][C-1] Waiting... (remaining tokens 4, wait 0
[13:42:34.829950][C-1] Done.
[13:42:35.030359][A-4] Waiting... (remaining tokens 3, wait 0
[13:42:35.030522][A-4] Done.
[13:42:35.045490][B-3] Waiting... (remaining tokens 2, wait 0
[13:42:35.045618][B-3] Done.
[13:42:35.080576][C-2] Waiting... (remaining tokens 1, wait 0
[13:42:35.080722][C-2] Done.
[13:42:35.281246][A-5] Waiting... (remaining tokens 0, wait 0
[13:42:35.281366][A-5] Done.
[13:42:35.296276][B-4] Waiting... (remaining tokens 0, wait 9.9996190071106 // -1
[13:42:35.331579][C-3] Waiting... (remaining tokens 0, wait 9.9995100498199 // -2
[13:42:35.532473][A-6] Waiting... (remaining tokens 0, wait 9.9992949962616 // -3
[13:42:45.295998][B-4] Done.
[13:42:45.331173][C-3] Done.
[13:42:45.531867][A-6] Done.
[13:42:45.546880][B-5] Waiting... (remaining tokens 9, wait 0 // Should be 6: 10 (refilled tokens) - 3 (reserved tokens) - 1 (this call) = 6
[13:42:45.547036][B-5] Done.
[13:42:45.582074][C-4] Waiting... (remaining tokens 8, wait 0
[13:42:45.582224][C-4] Done.
[13:42:45.782601][A-7] Waiting... (remaining tokens 7, wait 0
[13:42:45.782732][A-7] Done.
[13:42:45.797649][B-6] Waiting... (remaining tokens 6, wait 0
[13:42:45.797775][B-6] Done.
[13:42:45.832693][C-5] Waiting... (remaining tokens 5, wait 0
[13:42:45.832802][C-5] Done.
[13:42:46.033280][A-8] Waiting... (remaining tokens 4, wait 0
[13:42:46.033393][A-8] Done.
[13:42:46.048405][B-7] Waiting... (remaining tokens 3, wait 0
[13:42:46.048529][B-7] Done.
[13:42:46.083375][C-6] Waiting... (remaining tokens 2, wait 0
[13:42:46.083499][C-6] Done.
[13:42:46.284006][A-9] Waiting... (remaining tokens 1, wait 0
[13:42:46.284134][A-9] Done.
[13:42:46.299278][B-8] Waiting... (remaining tokens 0, wait 0
[13:42:46.299415][B-8] Done.
[13:42:46.334187][C-7] Waiting... (remaining tokens 0, wait 9.9995319843292
[13:42:46.535019][A-10] Waiting... (remaining tokens 0, wait 9.9995231628418
[13:42:46.550177][B-9] Waiting... (remaining tokens 0, wait 9.9995369911194
```

After fix:
```
[13:44:31.424519][A-1] Waiting... (remaining tokens 9, wait 0
[13:44:31.424787][A-1] Done.
[13:44:31.675478][A-2] Waiting... (remaining tokens 8, wait 0
[13:44:31.675613][A-2] Done.
[13:44:31.728025][B-1] Waiting... (remaining tokens 7, wait 0
[13:44:31.728287][B-1] Done.
[13:44:31.926266][A-3] Waiting... (remaining tokens 6, wait 0
[13:44:31.926393][A-3] Done.
[13:44:31.978813][B-2] Waiting... (remaining tokens 5, wait 0
[13:44:31.978932][B-2] Done.
[13:44:32.052379][C-1] Waiting... (remaining tokens 4, wait 0
[13:44:32.052579][C-1] Done.
[13:44:32.177300][A-4] Waiting... (remaining tokens 3, wait 0
[13:44:32.177429][A-4] Done.
[13:44:32.229624][B-3] Waiting... (remaining tokens 2, wait 0
[13:44:32.229764][B-3] Done.
[13:44:32.303104][C-2] Waiting... (remaining tokens 1, wait 0
[13:44:32.303223][C-2] Done.
[13:44:32.428153][A-5] Waiting... (remaining tokens 0, wait 0
[13:44:32.428266][A-5] Done.
[13:44:32.480274][B-4] Waiting... (remaining tokens -1, wait 9.9997317790985
[13:44:32.553742][C-3] Waiting... (remaining tokens -2, wait 9.999715089798
[13:44:32.678953][A-6] Waiting... (remaining tokens -3, wait 9.9996068477631
[13:44:42.480171][B-4] Done.
[13:44:42.553548][C-3] Done.
[13:44:42.678669][A-6] Done.
[13:44:42.731282][B-5] Waiting... (remaining tokens 6, wait 0
[13:44:42.731451][B-5] Done.
[13:44:42.804274][C-4] Waiting... (remaining tokens 5, wait 0
[13:44:42.804403][C-4] Done.
[13:44:42.929413][A-7] Waiting... (remaining tokens 4, wait 0
[13:44:42.929560][A-7] Done.
[13:44:42.982300][B-6] Waiting... (remaining tokens 3, wait 0
[13:44:42.982465][B-6] Done.
[13:44:43.055138][C-5] Waiting... (remaining tokens 2, wait 0
[13:44:43.055285][C-5] Done.
[13:44:43.180354][A-8] Waiting... (remaining tokens 1, wait 0
[13:44:43.180483][A-8] Done.
[13:44:43.233106][B-7] Waiting... (remaining tokens 0, wait 0
[13:44:43.233237][B-7] Done.
[13:44:43.305869][C-6] Waiting... (remaining tokens -1, wait 9.9997019767761
[13:44:43.431234][A-9] Waiting... (remaining tokens -2, wait 9.999547958374
[13:44:43.484102][B-8] Waiting... (remaining tokens -3, wait 9.9995830059052
```

### PR DESCRIPTION
**Pull request by ousamabenyounes**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62688
| License       | MIT

`TokenBucket::getExpirationTime()` returned `calculateTimeForTokens(burstSize)` — the time it takes to refill an empty bucket. When `reserve()` drives the token count below zero (for a reservation that has to wait for the next refill), the bucket still gets saved back to storage with that same short TTL. If the cache evicts the bucket before the debt is paid off, the next `fetch()` returns `null`, a fresh full bucket is created, and the pending reservation silently vanishes — letting the client claim tokens that were already promised elsewhere.

This PR makes the TTL track the outstanding debt: `max(burstSize, burstSize - tokens)`. For non-negative `tokens` the expression equals the old value, so behavior is unchanged on the happy path. Added a regression test that consumes the bucket, reserves a token against the next window, sleeps past the previous TTL, and confirms that the debt survives the round-trip.

This fixes the **TokenBucket** half of the reporter's analysis. #61668 tracks the analogous FixedWindow case; I kept that one out of scope since the state shape differs and the fix there is not the same mechanical change.

---
_Vibe Coded by Ousama Ben Younes_
_Developed With Ora Studio (Claude Code)_

### CODE REVIEW

File: src/Symfony/Component/RateLimiter/Tests/Policy/TokenBucketLimiterTest.php [hunk 1]
```diff
@@ -240,6 +240,35 @@ public function testBucketRefilledWithStrictFrequency()
         }
     }
 
+    public function testReservationDebtSurvivesCacheExpiration()
+    {
+        // limit=10, rate=10 every 10s: bucket refills in one burst per interval.
+        // With this shape the bucket's previous TTL equaled one refill interval
+        // (10s), so reservation debt (negative tokens) was evicted from cache
+        // before being paid off — see issue #62688.
```
Comment (nicolas-grekas) [inline src/Symfony/Component/RateLimiter/Tests/Policy/TokenBucketLimiterTest.php]: we don't reference github issues in the code
and we don't add so many comments in the codebase nor in tests either

**Comment by ousamabenyounes** [comment]
Thanks for the review @nicolas-grekas — noted on both points.

Pushed `2f0fc27`: stripped the issue reference and every inline comment from `testReservationDebtSurvivesCacheExpiration`. The test name and the four `reserve()` / `consume()` assertions carry the intent on their own, no prose needed.

The production change in `TokenBucketLimiter::getExpirationTime()` is untouched. Let me know if you'd like anything tightened further.

**Comment by nicolas-grekas** [comment]
Thank you @ousamabenyounes.
