### PR TITLE
[Intl] fix Locale::getFallback() throwing exception on long $locale

### LINKED ISSUE #39100: [Intl] `Locale::getFallback()` throws an exception when the `$locale` length is greater than `INTL_MAX_LOCALE_LEN`
**Symfony version(s) affected**: 5.1.8

**Description**  
`Symfony\Component\Intl\Locale::getFallback()` throws an `ErrorException` when the length of specified `$locale` is greater than `INTL_MAX_LOCALE_LEN`.

**How to reproduce**  
```php
Locale::getFallback("LC_CTYPE=fr_FR.UTF-8;LC_NUMERIC=C;LC_TIME=fr_FR.UTF-8;LC_COLLATE=fr_FR.UTF-8;LC_MONETARY=fr_FR.UTF-8;LC_MESSAGES=fr_FR.UTF-8;LC_PAPER=fr_FR.UTF-8;LC_NAME=fr_FR.UTF-8;LC_ADDRESS=fr_FR.UTF-8;LC_TELEPHONE=fr_FR.UTF-8;LC_MEASUREMENT=fr_FR.UTF-8;LC_IDENTIFICATION=fr_FR.UTF-8");
// Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /home/www/grossiste/vendor/symfony/intl/Locale.php:70
```

**Possible Solution**  
[`locale_parse()`](https://www.php.net/manual/fr/locale.parselocale.php) returns `null` instead of an array when the specified locale is greater than `INTL_MAX_LOCALE_LEN`. So a check should be made to test whether the return value is an array. ~~Or, the locale could be shortened by only extracting the meaningful part (i.e. just keep `LC_MESSAGES=fr_FR.UTF-8`?).~~

**Additional context** 
Length of the system locale: **270** (i.e. the one in the given code sample).
Value of the `INTL_MAX_LOCALE_LEN` constant: **156**.

PHP:  7.4.9 (x64) on CentOS 7.
Intl extension:
- Internationalization support => enabled
- ICU version => 65.1
- ICU Data version => 65.1
- ICU TZData version => 2019c
- ICU Unicode version => 12.1

### PR DESCRIPTION
**Pull request by AmirHo3ein13**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39100 
| License       | MIT
| Doc PR        | 

`Locale::getFallback()` throws an exception when the `$locale` length is greater than `INTL_MAX_LOCALE_LEN` so I added a condition to check if locale_parse return null, the `Locale::getFallback()` don't call `\count` function and just return null instead.

### CODE REVIEW

**Comment by OskarStark** [comment]
Thanks for your contribution, could you please add a testcase to avails a regression in the future?

Also it looks like your commit/email is not associated with your github account 🧐

**Comment by OskarStark** [comment]
Friendly ping @ro0NL

File: src/Symfony/Component/Intl/Locale.php [hunk 1]
```diff
@@ -69,6 +69,11 @@ public static function getFallback(string $locale): ?string
     {
         if (\function_exists('locale_parse')) {
             $localeSubTags = locale_parse($locale);
+
+            if (null === $localeSubTags) {
```
Comment (ro0NL) [inline src/Symfony/Component/Intl/Locale.php]: > Returns null when the length of locale exceeds INTL_MAX_LOCALE_LEN.

however the actual return type is documented to be array, so i think this is an error case actually. Thus a throw.

returning null might imply eg. `root` which has no parent

**Comment by AmirHo3ein13** [comment]
> Thanks for your contribution, could you please add a testcase to avails a regression in the future?
> 
> Also it looks like your commit/email is not associated with your GitHub account

@OskarStark thanks for your review. At first, I added a test case for my change but seems like in CI (appveyor) the `\function_exists('locale_parse')` returns false and it does not reach my change. As you can see, it is in my first commit, can you help me?

Also thank you for informing me about the email. I'll fix it and commit with the right email.

File: src/Symfony/Component/Intl/Locale.php (hunk 1 above)
Comment (AmirHo3ein13) [reply src/Symfony/Component/Intl/Locale.php]: @ro0NL thanks for your review. Sorry but I'm a little confused. What is your recommendation for this issue?

Comment (ro0NL) [reply src/Symfony/Component/Intl/Locale.php]: something like

```
if (null === $localeSubTags = locale_parse($locale)) {
   throw new InvalidLocaleException();
}
```

Not sure we have such exception, otherwise generic \LogicException or \InvalidArgumentException fits as well.

getFallback('root') // null
getFallbck(str_repeat('x', 1000)) // throw

**Comment by AmirHo3ein13** [comment]
@OskarStark @ro0NL seems like there is a problem with Doctrine, you can see it [here](https://travis-ci.com/github/symfony/symfony/jobs/482844823). Please check it, thanks in advance.

**Comment by xabbuh** [comment]
The Doctrine failure isn't related. We can ignore it here.

File: src/Symfony/Component/Intl/Locale.php [hunk 2]
```diff
@@ -68,7 +68,14 @@ public static function getDefaultFallback(): ?string
     public static function getFallback(string $locale): ?string
     {
         if (\function_exists('locale_parse')) {
-            $localeSubTags = locale_parse($locale);
+            if (null === $localeSubTags = locale_parse($locale)) {
+                if (\defined('INTL_MAX_LOCALE_LEN')) {
+                    $message = sprintf('The length of $locale must be less than %s', \INTL_MAX_LOCALE_LEN);
+                }
+
+                throw new \InvalidArgumentException($message ?? '');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Intl/Locale.php]: Why throw and not return null instead? this would make more sense to me.

**Review by nicolas-grekas — COMMENTED** [review]
Can you please add a test case?

File: src/Symfony/Component/Intl/Locale.php (hunk 2 above)
Comment (AmirHo3ein13) [reply src/Symfony/Component/Intl/Locale.php]: This is @ro0NL recommendation for this issue.

Comment (nicolas-grekas) [reply src/Symfony/Component/Intl/Locale.php]: The description says: `The ICU locale code of the fallback locale, or null if no fallback exists`
`null` looks expected to me...

**Comment by AmirHo3ein13** [comment]
> Can you please add a test case?

@nicolas-grekas as I wrote here, I have a problem testing my change and I need some help. Can you help me?

> > Thanks for your contribution, could you please add a testcase to avails a regression in the future?
> > Also it looks like your commit/email is not associated with your GitHub account
> 
> @OskarStark thanks for your review. At first, I added a test case for my change but seems like in CI (appveyor) the `\function_exists('locale_parse')` returns false and it does not reach my change. Can you help me?
>

**Comment by nicolas-grekas** [comment]
Can you add the test to the PR?
The test case should have the `@requires function locale_parse` annotation on it.

File: src/Symfony/Component/Intl/Locale.php (hunk 2 above)
Comment (ro0NL) [reply src/Symfony/Component/Intl/Locale.php]: we shouldnt hide errors IMHO

Comment (nicolas-grekas) [reply src/Symfony/Component/Intl/Locale.php]: why would this be an error? it's not, even for locale_parse

Comment (ro0NL) [reply src/Symfony/Component/Intl/Locale.php]: id say  a valid locale can be parsed: https://3v4l.org/Q4RUV

otherwise i'd say the parent of a "too long" locale is still `root`

Comment (nicolas-grekas) [reply src/Symfony/Component/Intl/Locale.php]: Looking at the logic below, this might be the most expected:
`return 'root' !== self::$defaultFallback && self::$defaultFallback === $locale ? 'root' : null;`

**Comment by AmirHo3ein13** [comment]
> Can you add the test to the PR?
> The test case should have the `@requires function locale_parse` annotation on it.

@nicolas-grekas thank you very much. I added the test successfully.

File: src/Symfony/Component/Intl/Locale.php (hunk 2 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Intl/Locale.php]: I'm doubling on this. @ro0NL OK for you?
@AmirHo3ein13 can you please update?

Comment (ro0NL) [reply src/Symfony/Component/Intl/Locale.php]: currently an error already bubbles up. The null check just polishes that.

But i think we can aim for consistency yes, accounting for `return self::$defaultFallback;` as well:

```php
if (null === $localeSubTags = locale_parse($locale)) {
    $localeSubTags = ['language' => $locale];
}

// aka
$localeSubTags =  locale_parse($locale) ?? ['language' => $locale];
```

and let it go from there.

File: src/Symfony/Component/Intl/Tests/LocaleTest.php [hunk 3]
```diff
@@ -70,4 +70,16 @@ public function testDefaultRootFallback()
...
+    /**
+     * @requires function locale_parse
+     */
+    public function testLongLocaleFallback()
+    {
+        $locale = 'LC_TYPE=fr_FR.UTF-8;LC_NUMERIC=C;LC_TIME=fr_FR.UTF-8;LC_COLLATE=fr_FR.UTF-8;'.
+            'LC_MONETARY=fr_FR.UTF-8;LC_MESSAGES=fr_FR.UTF-8;LC_PAPER=fr_FR.UTF-8;LC_NAME=fr_FR.UTF-8;'.
+            'LC_ADDRESS=fr_FR.UTF-8;LC_TELEPHONE=fr_FR.UTF-8;LC_MEASUREMENT=fr_FR.UTF-8;LC_IDENTIFICATION=fr_FR.UTF-8';
+
+        $this->assertNull(Locale::getFallback($locale));
```
Comment (ro0NL) [inline src/Symfony/Component/Intl/Tests/LocaleTest.php:83]: do we agree `root` is the fallback then?

compared to above test `$this->assertSame('root', Locale::getFallback('nl'));`

Comment (ro0NL) [reply src/Symfony/Component/Intl/Tests/LocaleTest.php:83]: actually $defaultFallback / `en` is expected

Comment (AmirHo3ein13) [reply src/Symfony/Component/Intl/Tests/LocaleTest.php:83]: @ro0NL the function is returning `null` on long $locale by this change:
`$localeSubTags =  locale_parse($locale) ?? ['language' => $locale];`

Comment (nicolas-grekas) [reply src/Symfony/Component/Intl/Tests/LocaleTest.php:83]: I think `null` is correct also.

**Review by nicolas-grekas — APPROVED** [review]

**Review by ro0NL — APPROVED** [review]
no strong opinion behavior-wise, `null` is reasonable

**Comment by nicolas-grekas** [comment]
Thank you @AmirHo3ein13.
