### PR TITLE
[Yaml] fix inline notation with inline comment

### LINKED ISSUE #59378: Inline yaml comments broken after recent commit
### Symfony version(s) affected

6.4

### Description

The yaml parser errors on inline comments after https://github.com/symfony/symfony/commit/8a3a57dc49aef8688bb0aa14ec7a5f772f091618

### How to reproduce

Parse the following yaml before and after https://github.com/symfony/symfony/commit/8a3a57dc49aef8688bb0aa14ec7a5f772f091618

```yaml
calls:
  # This is a temporary measure. JSON:API should not need to be aware of the Content Moderation module.
  - [setLatestRevisionCheck, ['@?access_check.latest_revision']] # This is only injected when the service is available.
```

using the following code:

```php
use Symfony\Component\Yaml\Yaml;

$a = <<<YML
calls:
  # This is a temporary measure. JSON:API should not need to be aware of the Content Moderation module.
  - [setLatestRevisionCheck, ['@?access_check.latest_revision']] # This is only injected when the service is available.
YML;

dump(Yaml::parse($a));
```

before this will output:
```
^ array:1 [
  "calls" => array:1 [
    0 => array:2 [
      0 => "setLatestRevisionCheck"
      1 => array:1 [
        0 => "@?access_check.latest_revision"
      ]
    ]
  ]
]
```

after this will output
```
PHP Fatal error:  Uncaught Symfony\Component\Yaml\Exception\ParseException: Unexpected token "# This is only injected when the service is available." at line 3 (near "- [setLatestRevisionCheck, ['@?access_check.latest_revision']] # This is only injected when the service is available."). in /Volumes/dev/symfony/src/Symfony/Component/Yaml/Parser.php:1210
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexpott**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59378 
| License       | MIT

Recent commit broke parsing yam like:
```yaml
calls:
  # This is a temporary measure. JSON:API should not need to be aware of the Content Moderation module.
  - [setLatestRevisionCheck, ['@?access_check.latest_revision']] # This is only injected when the service is available.
```

This MR adds a test and fixes this.

### CODE REVIEW

**Review by maxbeckers — APPROVED** [review]

File: src/Symfony/Component/Yaml/Parser.php [hunk 1]
```diff
@@ -1207,7 +1207,10 @@ private function lexInlineStructure(int &$cursor, string $closingTag, bool $cons
                         ++$cursor;
 
                         if ($consumeUntilEol && isset($this->currentLine[$cursor]) && (strspn($this->currentLine, ' ', $cursor) + $cursor) < strlen($this->currentLine)) {
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Parser.php]: I would rewrite the condition like this instead:

```suggestion
                        if ($consumeUntilEol && isset($this->currentLine[$cursor]) && ($whitespaces = strspn($this->currentLine, ' ', $cursor) + $cursor) < strlen($this->currentLine) && '#' !== $this->currentLine[$whitespaces]) {
```

File: src/Symfony/Component/Yaml/Parser.php [hunk 2]
```diff
@@ -1207,7 +1207,10 @@ private function lexInlineStructure(int &$cursor, string $closingTag, bool $cons
...
-                            throw new ParseException(sprintf('Unexpected token "%s".', trim(substr($this->currentLine, $cursor))));
+                            $remain = trim(substr($this->currentLine, $cursor));
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Parser.php]: we can then revert these changes

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @alexpott.
