### PR TITLE
[SecurityBundle] Use Composer `InstalledVersions` to check if flex is installed

### LINKED ISSUE #58624: [SecurityBundle] Class not found error when checking for existence of flex InstallRecipesCommand
### Symfony version(s) affected

7.1

### Description

When the security bundle config is not present, it tries to be helpful and suggest running `composer symfony:recipes:install` as long as the `InstallRecipesCommand` class from the flex package exists:

https://github.com/symfony/symfony/blob/ce3990dce0c62d5f2a29a3dbc56e28617123c094/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L94-L98

The problem with this is that `InstallRecipesCommand` extends `Composer\Command\BaseCommand` which does not exist when running under the context of Symfony (unless the composer/composer package is installed) so the following error is thrown:

```
!!  Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#4786
!!    #message: """
!!      Attempted to load class "BaseCommand" from namespace "Composer\Command".\n
!!      Did you forget a "use" statement for another namespace?
!!      """
!!    #code: 0
!!    #file: "./vendor/symfony/flex/src/Command/InstallRecipesCommand.php"
!!    #line: 25
!!    trace: {
!!      ./vendor/symfony/flex/src/Command/InstallRecipesCommand.php:25 { …}
!!      ./vendor/symfony/error-handler/DebugClassLoader.php:300 { …}
!!      Symfony\Component\ErrorHandler\DebugClassLoader->loadClass() {}
!!      ./vendor/symfony/security-bundle/DependencyInjection/SecurityExtension.php:94 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:81 { …}
!!      ./vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:40 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/Compiler.php:73 { …}
!!      ./vendor/symfony/dependency-injection/ContainerBuilder.php:752 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:495 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:740 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:120 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:177 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:69 { …}
!!      ./vendor/symfony/console/Application.php:167 { …}
!!      ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49 { …}
!!      ./vendor/autoload_runtime.php:34 { …}
!!      ./bin/console:13 {
!!        › 
!!        › require_once dirname(__DIR__).'/vendor/autoload_runtime.php';
!!        › 
!!        arguments: {
!!          "/var/www/app/vendor/autoload_runtime.php"
!!        }
!!      }
!!    }
!!  }
!!  2024-10-22T09:38:17+01:00 [critical] Uncaught Error: Class "Composer\Command\BaseCommand" not found
!!  
```

### How to reproduce

Run the following commands to create a new Symfony project with missing security bundle config:

```console
symfony new my_project_directory --version="7.1.*" --webapp
cd my_project_directory
rm -f config/packages/security.yaml
symfony server:start
```

Open the browser window and see the following error:

Screenshot from 2024-10-22 09-58-42

### Possible Solution

Could possibly call `Composer\InstalledVersions::isInstalled('symfony/flex')` instead of `class_exists`

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by andyexeter**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #58624  
| License       | MIT

As discussed in #58624, this fixes a class not found error which is thrown when security bundle config is missing.

### CODE REVIEW

**Comment by andyexeter** [comment]
Appveyor build failure appears unrelated

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 1]
```diff
@@ -91,7 +91,7 @@ public function prepend(ContainerBuilder $container): void
     public function load(array $configs, ContainerBuilder $container): void
     {
         if (!array_filter($configs)) {
-            $hint = class_exists(InstallRecipesCommand::class) ? 'Try running "composer symfony:recipes:install symfony/security-bundle".' : 'Please define your settings for the "security" config section.';
+            $hint = class_exists(InstalledVersions::class) && InstalledVersions::isInstalled('symfony/flex') ? 'Try running "composer symfony:recipes:install symfony/security-bundle".' : 'Please define your settings for the "security" config section.';
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:95]: can you try using `$container->getReflectionClass(InstallRecipesCommand::class, false)` instead? does it behave as expected then?

Comment (andyexeter) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:95]: @nicolas-grekas just tried it, `$container->getReflectionClass(InstallRecipesCommand::class, false)` returns null so it falls back to the "Please define your settings..." message. 

The `ClassExistenceResource::isFresh` method appears to be throwing the same error about the BaseCommand class not being found.

Comment (nicolas-grekas) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:95]: sorry, it returns or it throws? if it returns, that's what we want, no?

Comment (andyexeter) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:95]: @nicolas-grekas sorry, updated my comment to make it clearer. It returns null even when the class exists. We want it to return true so that we get the nicer message about running `composer symfony:recipes:install symfony/security-bundle`

Comment (nicolas-grekas) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:95]: The behavior I'm expecting is:
- return a ReflectionClass when the class *and its parent* exist
- return null when the class OR its parent does not exist

but then we'd need another check to see if flex is installed, so let's go this way

**Review by nicolas-grekas — APPROVED** [review]

**Comment by stof** [comment]
In other places, we perform the `class_exists` check on the `Recipe` class of flex (which has no extra dependency through a parent class) to detect the fact that Flex is installed.

**Comment by andyexeter** [comment]
> In other places, we perform the `class_exists` check on the `Recipe` class of flex (which has no extra dependency through a parent class) to detect the fact that Flex is installed.

@stof could you point me in the direction of where that is done? I can't find any reference to the `Recipe` class in the Symfony monorepo.

@nicolas-grekas is anything blocking this being merged?

**Review by Spomky — APPROVED** [review]

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 2]
```diff
@@ -60,7 +61,6 @@
 use Symfony\Component\Security\Core\User\UserProviderInterface;
 use Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticatorManagerListener;
 use Symfony\Component\Security\Http\Event\CheckPassportEvent;
-use Symfony\Flex\Command\InstallRecipesCommand;
 
 /**
  * SecurityExtension.
```
Comment (OskarStark) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:67]: Can be removed IMHO

Comment (andyexeter) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:67]: @OskarStark are you referring to the "SecurityExtension." comment? That wasn't added by this PR. It seems to have been present since the file was created in https://github.com/symfony/symfony/commit/f216f313e8909015fe9961a5604d179f64c35a90 15 years ago.

It's present in other bundle extension classes too, e.g:

https://github.com/symfony/symfony/blob/79fa5f2911946c739d80d4a89d8cdebbfe80c2dd/src/Symfony/Bundle/WebProfilerBundle/DependencyInjection/WebProfilerExtension.php#L23
https://github.com/symfony/symfony/blob/79fa5f2911946c739d80d4a89d8cdebbfe80c2dd/src/Symfony/Bundle/TwigBundle/DependencyInjection/TwigExtension.php#L39

So I think it's beyond the scope of this PR to remove it.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @andyexeter.
