### PR TITLE
[DependencyInjection] Fix circular reference with Factory + Lazy Iterrator

### LINKED ISSUE #38970: Maximum function nesting level of '256' reached with retryable http client and mailer handler
**Symfony version(s) affected**: 5.2.0-BETA3

**Description**  
```
monolog:
    handlers:
        mail:
            type: fingers_crossed
            action_level: error
            excluded_http_codes: [ 400, 403, 404 ]
            handler: deduplicated
        deduplicated:
            type: deduplication
            handler: mailer
        mailer:
            type: symfony_mailer
            from_email: '%env(resolve:EMAIL_SENDER)%'
            to_email: '%env(EMERGENCY_EMAIL)%'
            subject: 'An Error Occurred! %%message%%'
```
and
```
framework:
    http_client:
        default_options:
            retry_failed:
                http_codes: [ 429 ]

```

leads to 
```
 Maximum function nesting level of '256' reached, aborting!
```
on
```bash
bin/console cache:clear --env=prod
```
**How to reproduce**  
https://github.com/BoShurik/retriyable-http-client-issue

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38970
| License       | MIT
| Doc PR        | -

The issue, occurs when a `factory` iterates over services (think tagged iterator) that also need the `factory`.
The PhpDumper is not able to detect the loop because the TaggedService iterator is flaged as "lazy" which is ignored in the loop detection. https://github.com/symfony/symfony/blob/2d7e0b02c6dd8d652fe3732d0dd29f24bda1bddc/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php#L474-L476

See test case for a reproduce case.

This PR takes into account lazy services when computing loops.

I'm not sure this is the right thing to do /cc @nicolas-grekas . 
A better solution could be to do this ONLY when the service is used as a factory?

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php [hunk 1]
```diff
@@ -1054,6 +1054,9 @@ public function testAlmostCircular($visibility)
 
         $container = new $container();
 
+        $logger = $container->get('monolog.logger');
+        $this->assertEquals(new \stdClass(), $logger->handler);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php:1058]: ContainerBuilderTest also has testAlmostCircular method that should be synced with this one

Comment (jderusse) [reply src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php:1058]: Fixed

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @jderusse.
