### PR TITLE
[Security] Deprecate using UsageTrackingTokenStorage outside the request-response cycle

### LINKED ISSUE #40778: [HttpFoundation] Regression in using the session in kernel.terminate
**Symfony version(s) affected**: 5.x

**Description**

I was testing one of our main apps in 5.x and discovered a regression with the new session logic when using the token storage, causing "There is currently no session available." (related change: https://github.com/symfony/symfony/pull/38616)

We use a listener on `kernel.terminate` to log some information (including the current username). However, `RequestStack::getSession()` only works when there is a main request (which is not the case in the `kernel.terminate` event). Before 5.3, the `session` service was usable outside a main request.
The fix on our side was quite easy: use the `security.untracked_token_storage` service. Yet, I do believe there should be no hard breaks

**How to reproduce**

1. Create a listener on `kernel.terminate`
2. Try to use the session

**Possible Solution**

Maybe store the main `$request->getSession()` (in `RequestStack::push()`) in a variable and use it when there is no main request anymore? (and immediately deprecate this behavior) This way, there is no hard break between the version upgrade and there is a way to direct the user into the right debugging path.

### PR DESCRIPTION
**Pull request by wouterj**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | yes
| Tickets       | Fix #40778
| License       | MIT
| Doc PR        | -

Currently, you get an "There is currently no session available" exception when using the `security.token_storage` service outside the main request-response cycle (e.g. in a `kernel.terminate` listener). This PR deprecates such usage and requires developers to update their definitions to explicitly use `security.untracked_token_storage` instead.

A different solution would be to silently disable tracking in these cases, but I think that might create some unnecessary technical debt.

### CODE REVIEW

File: src/Symfony/Component/Security/Core/Authentication/Token/Storage/UsageTrackingTokenStorage.php [hunk 1]
```diff
@@ -88,4 +88,19 @@ private function getSession(): SessionInterface
...
         return $this->container->get('request_stack')->getSession();
     }
+
+    private function shouldTrackUsage(): bool
+    {
+        if (!$this->enableUsageTracking) {
+            return false;
+        }
+
+        if (!$this->container->get('request_stack')->getMainRequest()) {
```
Comment (jderusse) [inline src/Symfony/Component/Security/Core/Authentication/Token/Storage/UsageTrackingTokenStorage.php:103]: We should also check if people inject the deprecated `session` service.
This check will also asserts the `request_stack` service exists.
```php
if ($this->container->has('session')) {
    return true;
}
```

Comment (wouterj) [reply src/Symfony/Component/Security/Core/Authentication/Token/Storage/UsageTrackingTokenStorage.php:103]: Thanks, added this snippet :)

**Review by jderusse — APPROVED** [review]

File: UPGRADE-5.3.md [hunk 2]
```diff
@@ -102,6 +102,9 @@ Routing
 Security
 --------
 
+ * Deprecate using `UsageTrackingTokenStorage` with tracking enabled without a main request. Use the untracking token
```
Comment (derrabus) [inline UPGRADE-5.3.md]:
```suggestion
 * Deprecate using `UsageTrackingTokenStorage` with tracking enabled without a main request. Use the untracked token
```

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @wouterj.
