### PR TITLE
[AssetMapper] Using ?specifier=* does not match unstable packages on jsdelivr

### LINKED ISSUE #52106: [AssetMapper] Failing installs, add verbose error messages, custom url
### Description

I'm trying to install what appears to be a normal package from jsdeliver, it won't install but I have no idea why.
    
     bin/console importmap:require @tabler/core

https://www.jsdelivr.com/package/npm/@tabler/core

On a related note, I think importmap:require needs the option to define an endpoint, so that esms can be served outside of jsdeliver.

### Example

```bash
symfony new tabler --webapp --version=next && cd tabler 
composer config minimum-stability dev
composer config extra.symfony.allow-contrib true
export SYMFONY_ENDPOINT=https://raw.githubusercontent.com/symfony/recipes/flex/pull-1245/index.json
composer req symfony/asset-mapper
bin/console importmap:require @tabler/core
```

I image it has something to do with entrypoints and the package not being configured correctly, but since it appears to work with yarn, package developers may need more guidance is something isn't correct.

```bash
yarn add @tabler/core
yarn add v1.22.19
warning package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
warning No license field
success Saved 4 new dependencies.
info Direct dependencies
└─ @tabler/core@1.0.0-beta20
info All dependencies
├─ @popperjs/core@2.11.8
├─ @tabler/core@1.0.0-beta20
├─ @tabler/icons@2.39.0
└─ bootstrap@5.3.1
Done in 10.03s.
```

FWIW, @tabler/icons work.  Is it because core is in beta?

```
bin/console importmap:require @tabler/icons

                                                                                                                     
 [OK] Package "@tabler/icons" added to importmap.php.                                                                   
                                                                                                                        
      Use the new package normally by importing "@tabler/icons".                                                        
                                                                  
```

### PR DESCRIPTION
**Pull request by weaverryan**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #52106
| License       | MIT

To find which version of a package to grab, we use this API endpoint - https://data.jsdelivr.com/v1/packages/npm/@tabler/core/resolved. If a version constraint is specified (e.g. `importmap:require 'bootstrap@^5'`), we add a `?specifier=5`. If no version is specified, previously we added `?specifier=*`. However, this seems to ignore beta releases (returning `null` for `@table/core`, whose only has a 1.0 beta). Omitting `?specifier` seems to grab the latest, no matter what it is.

Also, if for some reason, we still can't find a `version`, we know blow up with a much clearer exception.

Cheers!

### CODE REVIEW

File: src/Symfony/Component/AssetMapper/ImportMap/Resolver/JsDelivrEsmResolver.php [hunk 1]
```diff
@@ -32,9 +32,6 @@ final class JsDelivrEsmResolver implements PackageResolverInterface
 
     public function __construct(
         HttpClientInterface $httpClient = null,
-        private readonly string $versionUrlPattern = self::URL_PATTERN_VERSION,
-        private readonly string $distUrlPattern = self::URL_PATTERN_DIST,
-        private readonly string $distUrlCssPattern = self::URL_PATTERN_DIST_CSS
```
Comment (weaverryan) [inline src/Symfony/Component/AssetMapper/ImportMap/Resolver/JsDelivrEsmResolver.php:37]: Unrelated: but it really doesn't make sense to have these URLs configurable. We are hitting very exact URLs.

Comment (tacman) [reply src/Symfony/Component/AssetMapper/ImportMap/Resolver/JsDelivrEsmResolver.php:37]: typo, should be @tabler/core https://www.jsdelivr.com/package/npm/@tabler/core

**Review by stof — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @weaverryan.

**Comment by tacman** [comment]
I put this in the PR, but it probably belongs here in the issue instead.

Installing the [bootstrap styling of datatables.net](https://www.jsdelivr.com/package/npm/datatables.net-bs5) is failing for me.


```bash
symfony new assetmapper-bug  --webapp --version=next --php=8.2 && cd assetmapper-bug
composer config extra.symfony.allow-contrib true
composer req symfony/asset-mapper:^6.4
bin/console importmap:require datatables.net-bs5
```

**Comment by weaverryan** [comment]
> I put this in the PR, but it probably belongs here in the issue instead.

I'm on it - thanks :)
