### PR TITLE
[Serializer] Throw InvalidArgumentException if the data needed in the constructor doesn't belong to a backedEnum 

### LINKED ISSUE #46977: [Serializer] Collect deserialization errors on enum cause TypeError
### Symfony version(s) affected

6.1

### Description

When i want to collect denomalization errors i got and a TypeError instead

### How to reproduce

```php
class SerializerIssueReport extends TestCase
{
    public function testCollectErrorsOnEnum()
    {
        $serializer = new Serializer(
            [
                new BackedEnumNormalizer(),
                new ObjectNormalizer(),
            ],
            ['json' => new JsonEncoder()]
        );

        $serializer->deserialize('{"test": "invalid"}', DummyObject::class, 'json', [
            DenormalizerInterface::COLLECT_DENORMALIZATION_ERRORS => true
        ]);
        
        $this->expectException(PartialDenormalizationException::class);
    }
}


class DummyObject {
    public function __construct(
        public TestEnum $test,
    )
    {
    }
}

enum TestEnum: String
{
    case Test = "test";
}
```

Result: `TypeError: DummyObject::__construct(): Argument #1 ($test) must be of type TestEnum, string given`

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alli83**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? |no
| Tickets       | Fix #46977 [Serializer] Collect deserialization errors on enum cause TypeError 
| License       | MIT
| Doc PR        | 

Targeted case: Deserialization with "collect_denormalization_errors" set but the data to be serialized does not correspond to the scalar value of the targeted enum instance in the object's constructor.
updated in last commit : Keep "from "(in the previous commits I had switched to "tryFrom") to map the data submitted to an enum instance targeted.

Imho, even if the "collect_denormalization_errors" is specified, this type of error seems to have to be caught upstream. By just trying to collect the error we do not prevent the object from being instantiated. But this action is bound to fail because we already know that the data is not valid (checked by the BackedEnumNormalizer). This instantiation 'failure' leads to a confusing/misleading error (i.e. _Argument # 1 ($test) must be of type TestEnum, string given_) which is not the original error.

### CODE REVIEW

File: src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php [hunk 1]
```diff
@@ -61,11 +61,12 @@ public function denormalize($data, $type, $format = null, array $context = [])
             throw NotNormalizableValueException::createForUnexpectedDataType('The data is neither an integer nor a string, you should pass an integer or a string that can be parsed as an enumeration case of type '.$type.'.', $data, [Type::BUILTIN_TYPE_INT, Type::BUILTIN_TYPE_STRING], $context['deserialization_path'] ?? null, true);
         }
 
-        try {
-            return $type::from($data);
-        } catch (\ValueError $e) {
-            throw NotNormalizableValueException::createForUnexpectedDataType($e->getMessage(), $data, [Type::BUILTIN_TYPE_INT, Type::BUILTIN_TYPE_STRING], $context['deserialization_path'] ?? null, true, $e->getCode(), $e);
+        $matched = $type::tryfrom($data);
+        if (!$matched) {
```
Comment (chalasr) [inline src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php]:
```suggestion
        if (!$matched = $type::tryFrom($data)) {
```
Per our CS, assignments should be inlined in the if statements. Also makes use of the correct case for `tryFrom()`

File: src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php [hunk 2]
```diff
@@ -61,11 +61,12 @@ public function denormalize($data, $type, $format = null, array $context = [])
...
+            throw new InvalidArgumentException('The data must belong to a backed enumeration.');
```
Comment (chalasr) [inline src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php]: The exception message could probably give more hints about what is happening, starting with which backed enum?

File: src/Symfony/Component/Serializer/Tests/SerializerTest.php [hunk 3]
```diff
@@ -1165,6 +1167,46 @@ public function testCollectDenormalizationErrorsWithConstructor(?ClassMetadataFa
...
+                'useMessageForUser' => $e->canUseMessageForUser(),
+                'message' => $e->getMessage(),
+            ];
+        }, $th->getErrors());
+
+        $expected = [
+            [
+                'currentType' => 'array',
+                'useMessageForUser' => true,
+                'message' => 'Failed to create object because the object miss the "get" property.',
```
Comment (chalasr) [inline src/Symfony/Component/Serializer/Tests/SerializerTest.php]: The message looks misleading as the class does have a `get` property, isn't it? Shouldn't it rather say that we are not able to create an object of the expected type X from the given value X?

File: src/Symfony/Component/Serializer/Tests/Fixtures/DummyObjectWithEnumConstructor.php [hunk 4]
```diff
@@ -0,0 +1,12 @@
...
+namespace Symfony\Component\Serializer\Tests\Fixtures;
+
+use Symfony\Component\Serializer\Tests\Fixtures\StringBackedEnumDummy;
+
+class DummyObjectWithEnumConstructor
+{
+    public function __construct(public StringBackedEnumDummy $get) 
+    {
+    }
+}
```
Comment (chalasr) [inline src/Symfony/Component/Serializer/Tests/Fixtures/DummyObjectWithEnumConstructor.php]: missing newline at EOF (this can probably be fixed globally by configuring your favorite editor)

**Review by chalasr — CHANGES_REQUESTED** [review]
Thanks for the PR! I'm not totally sure about the current patch though

File: src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php (hunk 2 above)
Comment (derrabus) [reply src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php]: The `ValueError` that was caught previously contained all that information. Switching to `tryForm()` does not look like a good idea, tbh.

Comment (alli83) [reply src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php]: Thanks for your feedback! 

it seems it was not possible to collect a correct  PartialDenormalizationException. The error message received was TypeError: DummyObject::__construct(): Argument # 1 ($test) must be of type TestEnum, string given, which seemed not very consistent compared to what was really the error. 

It appears that it cannot be created because there is no matching (property or value)

Comment (alli83) [reply src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php]: This proposal is mainly to avoid the TypeError when DenormalizerInterface::COLLECT_DENORMALIZATION_ERRORS => true

File: src/Symfony/Component/Serializer/Tests/SerializerTest.php (hunk 3 above)
Comment (alli83) [reply src/Symfony/Component/Serializer/Tests/SerializerTest.php]: indeed! 
(sorry previous message with an error)
won't work with
`public function __construct(public StringBackedEnumDummy $get)` and `'{"invalid": "get"}'`

but will work with `public function __construct(public StringBackedEnumDummy $invalid)` and `'{"invalid": "GET"}'`
or `'{"invalid": "get"}'` if we add `enum StringBackedEnumDummy: string { case GET = 'GET';  case INVALID = 'get'; }`

please correct me if I'm wrong, the message seems quite right?

File: src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php (hunk 2 above)
Comment (derrabus) [reply src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php]: Yeah, I got that. But as far as I understood – please correct me if I got that wrong – you're attempting to fix the bug by changing the exception that we raise when the enum cannot be hydrated. But you are also changing the way we detect that the enum cannot be hydrated. Those are two independent changes and I don't see why the latter is necessary.

Comment (alli83) [reply src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php]: In fact I think it's the test that is quite misleading ( Serializer::testCollectDenormalizationErrorsWithEnumConstructor()
) because it does not change the behavior whether it's used with 'from' or 'tryFrom' (the result is the same). 
=> '{"invalid": "get"}'  with `public function __construct(public StringBackedEnumDummy $get)`. It's more about the param constructor than the backedEnum itself and it's scalar equivalent.

it's more about the BackedEnumNormalizerTest::testDenormalizeBadBackingValueThrowsException => with a different exception raised  for '{"get": "invalid"}' and avoid a TypeError. I could in the message error add some details

File: src/Symfony/Component/Serializer/Tests/SerializerTest.php (hunk 3 above)
Comment (alli83) [reply src/Symfony/Component/Serializer/Tests/SerializerTest.php]: About the test mentioned above, it's not link to the BackedEnumNormalizer. Maybe I should remove it because misleading.

File: src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php (hunk 2 above)
Comment (derrabus) [reply src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php]: > it does not change the behavior whether it's used with 'from' or 'tryFrom' (the result is the same).

So, we can revert back to `from()`?

Comment (alli83) [reply src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php]: Maybe I'm wrong, but what seems annoying is the TypeError in some cases with Argument #1 ($get) must be of type Symfony\Component\Serializer\Tests\Fixtures\StringBackedEnumDummy, string given" message

`try {`
           ` $serializer->deserialize('{"get": "invalid"}', DummyObject::class, 'json', [`
               ` DenormalizerInterface::COLLECT_DENORMALIZATION_ERRORS => true`
            `]);`
       ` } catch (\Throwable $th) {`
          `$this->assertInstanceOf(TypeError::class, $th);`
        `}`

if we use tryFrom we catch an InvalidArgumentException with "The data must belong to a backed enumeration of type StringBackedEnumDummy" as message

Comment (derrabus) [reply src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php]: I'm not sure we speak the same language here.

Comment (alli83) [reply src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php]: I'm sorry then. 

If I may, 
if we add an other backedEnum with TEST="invalid" (e.g  StringBackedEnumDummy2) . but in the constructor of DummyObject it still aims for StringBackedEnumDummy, the test will fail but not because it's a string, but because the data doesn't belong to a backed enumeration of type StringBackedEnumDummy (belongs to StringBackedEnumDummy2)

thanks again for your feedback 🙏

Comment (derrabus) [reply src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php]: Okay, let's try again. Please try to focus on my question and try to answer that question only.

Why did you change the `from()` call to `tryFrom()`? Why is this change necessary to achieve your goal?

Comment (alli83) [reply src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php]: Ok, I try an other approach. And don't worry I'm focus on your question :)

With "from" and how ValueError is handled: 

even if we know that the value doesn't match (BackedEnumNormalizer throw ValueError $type::from($data)), AbstractNormalizer continue and call (line 419) `$reflectionClass->newInstanceArgs($params)`. So it will try to create a new instance with an argument we know doesn't match.  And then we receive a TypeError with "__construct(): Argument #1 ($get) must be of type ......., string given" => which is quite normal but not really the original error

With "tryFrom" : handle null (in case of failure) and throw directly an InvalidArgumentException. 

But, it's true we could do the same thing with "from" if we throw an InvalidArgumentException instead of  throwing NotNormalizableValueException::createForUnexpectedDataType(.....)

so in the end it's more about how the error is handled and less about from or tryFrom.

Comment (alli83) [reply src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php]: The problem explained above is when DenormalizerInterface::COLLECT_DENORMALIZATION_ERRORS => true is set

so when "tryFrom" or "from" fails ( I chose "tryFrom" but it seems more a choice than an obligation), my goal is to avoid to go any further and in particular try to create an instance at the risk of getting a misleading error when DenormalizerInterface::COLLECT_DENORMALIZATION_ERRORS => true is set by throwing an InvalidArgumentException instead of throwing NotNormalizableValueException::createForUnexpectedDataType(.....) and without modifying too much the existing code.

I hope this answers your question.

Comment (chalasr) [reply src/Symfony/Component/Serializer/Normalizer/BackedEnumNormalizer.php]: Seems like the change was reverted.

**Review by chalasr — APPROVED** [review]
This looks good to me as it seems to fix the buggy case at hand as proven by the added tests.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @alli83.

**Comment by issei-m** [comment]
This pull-request doesn't seem to fix the targeted issue.
AFAIK, the issue author (@elliotbruneel) would've wanted `BackedEnumNormalizer` to throw the `PartialDenormalizationException` in case a value not corresponding to the enum is attempted to be de-normalized.

While I understood the following argument of @alli83,

> By just trying to collect the error we do not prevent the object from being instantiated. But this action is bound to fail because we already know that the data is not valid (checked by the BackedEnumNormalizer).

`BackedEnumNormalizer` can throw the `PartialDenormalizationException` as long as the DTO doesn't have the constructor but only state their properties like:

```php
<?php

class SerializerIssueReport extends \PHPUnit\Framework\TestCase
{
    public function testCollectErrorsOnEnum()
    {
        $serializer = new Symfony\Component\Serializer\Serializer(
            [
                new \Symfony\Component\Serializer\Normalizer\BackedEnumNormalizer(),
                new \Symfony\Component\Serializer\Normalizer\ObjectNormalizer(),
            ],
            ['json' => new \Symfony\Component\Serializer\Encoder\JsonEncoder()]
        );

        $this->expectException(\Symfony\Component\Serializer\Exception\PartialDenormalizationException::class);

        $serializer->deserialize('{"test": "invalid"}', DummyObject2::class, 'json', [
            \Symfony\Component\Serializer\Normalizer\DenormalizerInterface::COLLECT_DENORMALIZATION_ERRORS => true
        ]);
    }
}

// Original one, for this class the pull-req is legit.
class DummyObject {
    public function __construct(public TestEnum $test) {}
}

// For this, PartialDenormalizationException can be thrown.
class DummyObject2 {
    public TestEnum $test;
}

enum TestEnum: String
{
    case Test = "test";
}
```

`PartialDenormalizationException` is preferred to `InvalidArgumentException` under the situation we can use it.

**Comment by alli83** [comment]
Indeed, we could distinguish the type of exception thrown depending on whether there is a constructor or not.

- if constructor invalid, the object being not possible to instantiate we could still throw the InvalidArgumentException 
- but throw a NotNormalizableValueException in the case you present above and would be collected as a PartialDenormalizationException. 

maybe when calling the instantiateObject from the AbstractNormalizer class we could easily add to the context to identify the presence of a constructor and direct the type of exception to throw ? 

thanks for your feedback 🙏

**Comment by issei-m** [comment]
@alli83 Thank you for clarification. Could you kindly open a pull-req for it?

**Comment by alli83** [comment]
@issei-m  for sure. I will also take into account this PR https://github.com/symfony/symfony/pull/48821

**Comment by TerjeBr** [comment]
Hi @alli83 Are you going to make a new PR to correct this? As it is now, we cannot have enums in our Dto's because we get InvalidArgumentException instead of PartialDenormalizationException that is expected when we specify collect_denormalization_errors

**Comment by alli83** [comment]
@TerjeBr PR https://github.com/symfony/symfony/pull/48821 doesn't solve your issue ?  I can have a look at it :) sorry for the late reply

**Comment by TerjeBr** [comment]
No. My project is locked to symfony 5.4 and PR https://github.com/symfony/symfony/pull/48821 is a symfony 6.3 thing.

The thing is that this PR undid the feature done by https://github.com/symfony/symfony/pull/42502

**Comment by alli83** [comment]
indeed. I'm glad to have a look at it then for 5.4 !

**Comment by TerjeBr** [comment]
Thanks

**Comment by TerjeBr** [comment]
To provide some context where I come from, I first viewed https://github.com/symfony/symfony/pull/43047#issuecomment-921077295
Then I was happy that may be https://github.com/symfony/symfony/pull/40830 + https://github.com/symfony/symfony/pull/42502 would be a solution to my problem. But then I discovered that it was not working any more because of this change.

(Just to give you the background.)

**Comment by alli83** [comment]
Would the added test case correspond to your case in https://github.com/symfony/symfony/pull/50192 ?
