### PR TITLE
[VarDumper] Fix error with uninitialized XMLReader

### LINKED ISSUE #42581: [VarDumper] XMLReader::getParserProperty(): Argument #1 ($property) must be a valid parser property
**Symfony version(s) affected**: 4.4 and 5.3

**Description**

When dumping an object obtained using the box/spout library, the VarDumper fails with a fatal error:

```
PHP Fatal error:  Uncaught ValueError: XMLReader::getParserProperty(): Argument #1 ($property) must be a valid parser property in /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/Caster/XmlReaderCaster.php:61
Stack trace:
#0 /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/Caster/XmlReaderCaster.php(61): XMLReader->getParserProperty()
#1 /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/Cloner/AbstractCloner.php(339): Symfony\Component\VarDumper\Caster\XmlReaderCaster::castXmlReader()
#2 /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/Cloner/VarCloner.php(194): Symfony\Component\VarDumper\Cloner\AbstractCloner->castObject()
#3 /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/Cloner/AbstractCloner.php(272): Symfony\Component\VarDumper\Cloner\VarCloner->doClone()
#4 /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/VarDumper.php(46): Symfony\Component\VarDumper\Cloner\AbstractCloner->cloneVar()
#5 /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/VarDumper.php(50): Symfony\Component\VarDumper\VarDumper::Symfony\Component\VarDumper\{closure}()
#6 /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/Resources/functions/dump.php(20): Symfony\Component\VarDumper\VarDumper::dump()
#7 /home/tgalopin/Projects/symfony/xml-reader-reproducer/reproducer.php(8): dump()
#8 {main}
  thrown in /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/Caster/XmlReaderCaster.php on line 61
```

**How to reproduce**

All details about the environment and how to reproduce on https://github.com/tgalopin/xml-reader-reproducer

**Possible Solution**

I don't know the VarDumper component enough to propose a solution.

### PR DESCRIPTION
**Pull request by villfa**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #42581
| License       | MIT
| Doc PR        | n/a

When XMLReader is not initialized,  getParserProperty() throws an error (or emits a warning, depending on the PHP version).
Now the error is caught and the properties are set to false.

### CODE REVIEW

**Comment by villfa** [comment]
Hi @fabpot,
The error from *fabbot.io* is a false positive, so I'm wondering if the code of this bot is open in order to fix it.
Or maybe it relies on open tools?

File: src/Symfony/Component/VarDumper/Caster/XmlReaderCaster.php [hunk 1]
```diff
@@ -10,6 +10,7 @@
 
 namespace Symfony\Component\VarDumper\Caster;
 
+use Error;
```
Comment (derrabus) [inline src/Symfony/Component/VarDumper/Caster/XmlReaderCaster.php]: CS: We don't import classes from the global scope.

File: src/Symfony/Component/VarDumper/Caster/XmlReaderCaster.php [hunk 2]
```diff
@@ -44,6 +45,22 @@ class XmlReaderCaster
...
     public static function castXmlReader(\XMLReader $reader, array $a, Stub $stub, $isNested)
     {
+        try {
+            $properties = [
+                'LOADDTD' => @$reader->getParserProperty(\XMLReader::LOADDTD),
+                'DEFAULTATTRS' => @$reader->getParserProperty(\XMLReader::DEFAULTATTRS),
+                'VALIDATE' => @$reader->getParserProperty(\XMLReader::VALIDATE),
+                'SUBST_ENTITIES' => @$reader->getParserProperty(\XMLReader::SUBST_ENTITIES),
+            ];
+        } catch (Error $e) {
```
Comment (derrabus) [inline src/Symfony/Component/VarDumper/Caster/XmlReaderCaster.php]:
```suggestion
        } catch (\ValueError $e) {
```

**Review by derrabus — CHANGES_REQUESTED** [review]

**Comment by derrabus** [comment]
Thank you for your PR, @villfa. The open source tool that fabbot relies on is PHP CS Fixer. Since the failure is a false positive as you already discovered, you can simply ignore it. 🙂

File: src/Symfony/Component/VarDumper/Caster/XmlReaderCaster.php (hunk 2 above)
Comment (villfa) [reply src/Symfony/Component/VarDumper/Caster/XmlReaderCaster.php]: I've used `Error` instead of `ValueError` on purpose because of this fix in PHP: https://github.com/php/php-src/commit/53f89219abdea49099805562d5020d4e21785d55

File: src/Symfony/Component/VarDumper/Caster/XmlReaderCaster.php (hunk 1 above)
Comment (villfa) [reply src/Symfony/Component/VarDumper/Caster/XmlReaderCaster.php]: It's fixed.

File: src/Symfony/Component/VarDumper/Caster/XmlReaderCaster.php (hunk 2 above)
Comment (derrabus) [reply src/Symfony/Component/VarDumper/Caster/XmlReaderCaster.php]: That makes total sense. I can confirm that an `Error` is triggered on the latest PHP snapshot.

That makes me wonder: Is there a better way to detect an uninitialized `XMLReader` than to catch a generic `Error`?

Comment (villfa) [reply src/Symfony/Component/VarDumper/Caster/XmlReaderCaster.php]: I've double-checked the XMLReader [documentation](https://www.php.net/manual/en/class.xmlreader.php) and [source code](https://github.com/php/php-src/blob/master/ext/xmlreader/php_xmlreader.c), and I couldn't find another way to check if an instance is not yet initialized :(

**Review by derrabus — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @villfa.
