### PR TITLE
[ExpressionLanguage] Support non-existent names when followed by null coalescing

### LINKED ISSUE #54359: [Expression Language] Null coalescing operator doesn't work?
### Symfony version(s) affected

7.0

### Description

According to docs, we can use null-coalescing operator to provide fallback to potentially empty or even nonexistent variables. However I can't make it work, even in a simple file with nothing but Expression Language.

### How to reproduce

```php
$lang = new ExpressionLanguage();

$data = [
    'exists' => true,
];

$expression1 = 'notexists ?? "nope,"';
$expression2 = '(notexists ?? "nope,")';
$expression3 = '(notexists ?? false) ? "yes" : "no"';

foreach ([$expression1, $expression2, $expression3] as $exp) {
    try {
        var_dump($lang->evaluate($exp, $data));
    } catch (\Throwable $th) {
        echo('!');
    }
}
// expected: nope,nope,no
// actual: !!!
```

(In the reproduction I have suppressed the throws, but every evaluate fails with `Fatal error: Uncaught Symfony\Component\ExpressionLanguage\SyntaxError: Variable "notexists" is not valid around position …`

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by adamkiss**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Issues        | Fix #54359
| License       | MIT

This PR allows for null coalescing nonexistent names (`nonexistent ?? 123`) in expressions by introducing new type of node `NullCoalescedNameNode`, which compiles to `$nonexistent ?? null`, so it subsequently evaluates to null and the null coalescing takes over then.

Edit: feature/bug is questionable, because I half-consider it a bug, since it's _one of the examples in the docs_, despite my original issue being closed as "expected", and the docs issue marked resolved despite this use case throwing while existing names resolving to null pass.

### CODE REVIEW

File: src/Symfony/Component/ExpressionLanguage/Node/NullCoalescedNameNode.php [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\ExpressionLanguage\Node;
+
+use Symfony\Component\ExpressionLanguage\Compiler;
+
+/**
+ * @author Fabien Potencier <fabien@symfony.com>
```
Comment (OskarStark) [inline src/Symfony/Component/ExpressionLanguage/Node/NullCoalescedNameNode.php]: You are the author

Comment (adamkiss) [reply src/Symfony/Component/ExpressionLanguage/Node/NullCoalescedNameNode.php]: @OskarStark Yeah I wasn't sure what the customs around the author stuff were, and every file I opened had as author Fabien

**Comment by OskarStark** [comment]
To me this a new feature, please add an entry in the changeling for 7.2 section, as we are in feature freeze for 7.1, thanks

File: src/Symfony/Component/ExpressionLanguage/Node/NullCoalescedNameNode.php [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+    {
+        parent::__construct(
+            [],
+            ['name' => $name]
+        );
+    }
+
+    public function compile(Compiler $compiler): void
+    {
+        $compiler->raw('$'.$this->attributes['name'].' ?? null');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ExpressionLanguage/Node/NullCoalescedNameNode.php:33]: don't we need brackets around?

Comment (adamkiss) [reply src/Symfony/Component/ExpressionLanguage/Node/NullCoalescedNameNode.php:33]: We don't

we know it's followed by actual null coalescing, and if brackets should be anywhere, it's around the whole expression coalescing to value

```
(nonexististent ?? 'fallback')
($nonexistent ?? null ?? 'fallback')
```

**Comment by adamkiss** [comment]
> To me this a new feature, please add an entry in the changeling for 7.2 section, as we are in feature freeze for 7.1, thanks

Shame about the feature freeze. will do.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @adamkiss.
