### PR TITLE
[Security] Fix valid remember-me token exposure to the second consequent request

### LINKED ISSUE #42343: PersistentRememberMeHandler - race condition in returned cookies
**Symfony version(s) affected**: 5.3.6

**Description**

This bug was originally raised at https://github.com/symfony/symfony/issues/28314 and (almost) fixed in https://github.com/symfony/symfony/pull/41175

The current implementation creates the cookie in this line

https://github.com/symfony/symfony/blob/48769674fddb95a4a7881783f4bd0d687c04313a/src/Symfony/Component/Security/Http/RememberMe/PersistentRememberMeHandler.php#L100

The problem with that line is that it creates a race condition between 2 concurrent requests (which #28314 was originally about):

So the chronology is:

1. Browser emits 2 concurrent requests with identical remember-me cookie 
1. One request wins this race, authenticates a user with remember-me token, regenerates token, stores old in the cache, stores new in database, returns new token in the `Set-Cookie`
1. Now the second request is to be handled, because it's within 60 seconds and because the old value is still in the cache - it passes validation. But now we create a cookie in that line 100 and put the **old value** into it.

Now the browser looks fine, but it contains the remember-me token with not actual value, because the second request, which has lost the race - re-set the cookie value to the old one.

**How to reproduce**

1. Authenticate with remember me
1. Write down the remember me cookie somewhere
1. Wait for at least a minute
1. Delete session cookie
1. Refresh the page - now you should reauthenticate with remember me
1. Restore remember me cookie with the value from the step 2
1. Wait for another minute and if you're using a cache with `appendOnly` - ensure you clear it.
1. Delete session cookie again
1. Refresh the page

Now the session is lost and in the logs you can read `This token was already used. The account is possibly compromised`.

**Possible Solution**

The cookie should only be returned if the new token value has been generated.

eg:

```php
        // if a token was regenerated less than a minute ago, there is no need to regenerate it
        // if multiple concurrent requests reauthenticate a user we do not want to update the token several times
        if ($persistentToken->getLastUsed()->getTimestamp() + 60 < time()) {
            $tokenValue = $this->generateHash(base64_encode(random_bytes(64)));
            $tokenLastUsed = new \DateTime();
            if ($this->tokenVerifier) {
                $this->tokenVerifier->updateExistingToken($persistentToken, $tokenValue, $tokenLastUsed);
            }
            $this->tokenProvider->updateToken($series, $tokenValue, $tokenLastUsed);

            $this->createCookie($rememberMeDetails->withValue($series.':'.$tokenValue)); // moved inside condition body
        }
```

**Additional context**

/cc @Seldaek

### PR DESCRIPTION
**Pull request by zerkms**
Close https://github.com/symfony/symfony/issues/42343
Fix https://github.com/symfony/symfony/pull/46760

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #42343, Fix #46760 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

https://github.com/symfony/symfony/pull/46760 PR together with a fix produces a security vulnerability when a malicious actor may get a **new and valid** remember me token if makes a request right after the legit user.

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]
This change looks correct to me.

2 requests come by at the same time with tokenA:
- the one that wins the race persists and sends back tokenB
- the other one accepts tokenA but doesn't send any cookie back, aka tokenB from req 1 stays in the cookie jar.

Unless I missed something, this still fixes the situation that @heiglandreas describes in #46760 while preventing a needless disclosure of the currently valid token to the 2nd request.

/cc @Seldaek in case you want to have a look.

I'm just worried that although this causes a possible security threat, [the security disclosure process](https://symfony.com/security) hasn't been followed appropriately. Please be more careful in the future.

File: src/Symfony/Component/Security/Http/Tests/RememberMe/PersistentRememberMeHandlerTest.php [hunk 1]
```diff
@@ -126,17 +126,7 @@ public function testConsumeRememberMeCookieValidByValidatorWithoutUpdate()
         $handler->consumeRememberMeCookie($rememberMeDetails);
 
         // assert that the cookie has been updated with a new base64 encoded token value
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Security/Http/Tests/RememberMe/PersistentRememberMeHandlerTest.php]: can you please update this comment? (or remove it)

Comment (zerkms) [reply src/Symfony/Component/Security/Http/Tests/RememberMe/PersistentRememberMeHandlerTest.php]: Totally, I seen it but totally forgot to remove, apologies.

**Comment by nicolas-grekas** [comment]
Thank you @zerkms.

**Comment by heiglandreas** [comment]
Throughout the last days I debugged some odd occurrences and was able to track them down to this PR.

I will create a new issue for that so that we can track that accordingly.
