### PR TITLE
[DI] deferred exceptions in ResolveParameterPlaceHoldersPass

### LINKED ISSUE #30428: [DependencyInjection] Anonymous services are not removed along with the parent service
**Description**  
When a definition is removed, I expect nested anonymous services to be removed as well:

**How to reproduce**  
```xml
<service id="foo_service" class="Foo">
    <argument type="service">
        <service class="Bar">
            <argument>%bar.parameter%</argument>
        </service>
    </argument>
</service>
```

Extension:
```php
if (!isset($config['option'])) {
    $container->removeDefinition('foo_service');

    return;
}

$container->setParameter('bar.parameter', $config['option']);
```

Compiling the container without `option` results in:

```
The service ".3_Bar~hJYmG7r" has a dependency on a non-existent parameter "bar.parameter".
```

### PR DESCRIPTION
**Pull request by fu22ybear**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #30428 
| License       | MIT
| Doc PR        | n/a

fixes case #30428 
implemented as in AutowiringPass

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Compiler/ResolveParameterPlaceHoldersPass.php [hunk 1]
```diff
@@ -61,7 +63,16 @@ public function process(ContainerBuilder $container)
...
         if (\is_string($value)) {
-            $v = $this->bag->resolveValue($value);
+            try {
+                $v = $this->bag->resolveValue($value);
+            } catch (ParameterNotFoundException $e) {
+                if ($this->throwOnResolveException) {
+                    throw $e;
+                }
+
+                $v = null;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/ResolveParameterPlaceHoldersPass.php]: I think we should use the empty string here, to preserve the type.

**Review by nicolas-grekas — APPROVED** [review]
(for 3.4)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
@Islam93 Can you rebase on 3.4 and change the target of this PR accordingly?

**Comment by Islam93** [comment]
@fabpot, should travis-ci and appveyor builds be restarted?

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Islam93.
