### PR TITLE
[DI] Fix support for multiple tags for locators and iterators

### LINKED ISSUE #34462: [DependencyInjection] Use "!tagged" with "index_by" collect service only once when used multiple tags
**Symfony version(s) affected**: 4.3.8

**Description**  
Use "!tagged" with "index_by" collect service only once when used multiple tags.

Expected: service will be added to argument for every tag with different indexes.
Actual: only first entry used.

**How to reproduce**  
```php
<?php

require 'vendor/autoload.php';

$container = new \Symfony\Component\DependencyInjection\ContainerBuilder();

$registryDefinition = (new \Symfony\Component\DependencyInjection\Definition())
    ->setClass(IteratorIterator::class)
    ->setPublic(true)
    ->addArgument(
        new \Symfony\Component\DependencyInjection\Argument\TaggedIteratorArgument(
            'bug',
            'type'
        )
    );
$entryDefinition = (new \Symfony\Component\DependencyInjection\Definition())
    ->setClass(stdClass::class)
    ->addTag('bug', ['type' => 'first'])
    ->addTag('bug', ['type' => 'second']);

$container->setDefinition('registry', $registryDefinition);
$container->setDefinition('entry', $entryDefinition);

$container->compile();

/** @var IteratorIterator $registry */
$registry = $container->get('registry');

$received = [];
foreach ($registry as $index => $entry) {
    $received[] = $index;
}

if (['first', 'second'] !== $received) {
    // $received is ['first']
    echo 'Failed' . PHP_EOL . PHP_EOL . 'Received:' . PHP_EOL . print_r($received, true);

    exit(1);
}

echo 'Success';
```

**Possible Solution**  
Iterate over attributes here, instead picking first https://github.com/symfony/symfony/blob/e60a876201b5b306d0c81a24d9a3db997192079c/src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php#L92-L96

**Additional context**

### LINKED ISSUE #35326: [DependencyInjection] Support multiple tags for ServiceLocator
It would be interesting to have the option of tagging multiple time a service added to a locator indexed by some key.

```
my_service:
  tags:
    - { name: tag, alias: 'key-1' }
    - { name: tag, alias: 'key-2' }

my_consumer:
  arguments: [!tagged_locator { tag: 'tag', index_by: 'key' }]
```

And one could get both `key-1` and `key-2` referring to the same service.

### PR DESCRIPTION
**Pull request by alex-dev**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34462, Fix #35326
| License       | MIT
| Doc PR        | none

Fix PriorityTaggedServiceTrait::findAndSortTaggedServices to work with multiple explicitely tagged services as would be expected by !tagged_locator. Also reorganize PriorityTaggedServiceTrait::findAndSortTaggedServices to be simpler and easier to understand.

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php [hunk 1]
```diff
@@ -50,82 +52,68 @@ private function findAndSortTaggedServices($tagName, ContainerBuilder $container
...
-            }
-
-            if (!($rm = $r->getMethod($defaultIndexMethod))->isStatic()) {
-                throw new InvalidArgumentException(sprintf('Method "%s::%s()" should be static: tag "%s" on service "%s" is missing "%s" attribute.', $class, $defaultIndexMethod, $tagName, $serviceId, $indexAttribute));
-            }
-
-            if (!$rm->isPublic()) {
-                throw new InvalidArgumentException(sprintf('Method "%s::%s()" should be public: tag "%s" on service "%s" is missing "%s" attribute.', $class, $defaultIndexMethod, $tagName, $serviceId, $indexAttribute));
-            }
+                $reference = $r && 'stdClass' !== $class ? new TypedReference($serviceId, $class, $behavior, $name) : new Reference($serviceId, $behavior);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php]: why is stdClass a special case? what's the relation with the fix?

**Review by nicolas-grekas — CHANGES_REQUESTED** [review]
Hello, thank you for working on this!
I didn't review the logic in details but I think there are some flaws in the current patch that need to be addressed:
- the diff in the PR contains unneeded changes - eg variable declaration reordering. As any unneeded diff is a potential merge conflict when we'll merge changes from 3.4/4.3, we try to avoid them as much as possible.
- because the patch is so big, reviewing is extremely difficult. A PR should do one and only one change. Here, there are two of them: refacto + bug fix. This increases the risk of introducing bugs and the risk of missing the regressions during the review. I'd kindly ask you to rewrite your patch to stick to fixing the logic only.
- Technically, I found a regression and stopped there my review: `$container->getReflectionClass()` is now *always* called inside the foreach loop. The previous logic avoided doing so on purpose when not needed. This behavior should be kept.

Thanks again, I'm looking forward to the next iteration :)

File: src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php (hunk 1 above)
Comment (alex-dev) [reply src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php]: stdClass should not be TypedReference as they are not actual defined types.

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/IntegrationTest.php [hunk 2]
```diff
@@ -314,6 +314,32 @@ public function testTaggedServiceWithIndexAttributeAndDefaultMethod()
         $this->assertSame(['bar_tab_class_with_defaultmethod' => $container->get(BarTagClass::class), 'foo' => $container->get(FooTagClass::class)], $param);
     }
 
+    public function testTaggedServiceWithMultipleIndexAttribute()
```
[the remark this answers is not in the document]
Comment (alex-dev) [reply src/Symfony/Component/DependencyInjection/Tests/Compiler/IntegrationTest.php]: Other iterator tests use TaggedService... Why change the pattern?

**Review by alex-dev — COMMENTED** [review]
> * Technically, I found a regression and stopped there my review: `$container->getReflectionClass()` is now _always_ called inside the foreach loop. The previous logic avoided doing so on purpose when not needed. This behavior should be kept.

Why should it? It is during container compilation, not a critical path. And the code end up being much easier to follow. Rather than being a mess, everything related to default happens before tag processing, which then becomes repeatable easily.

I'm gonna work a slimmer changeset, but the logic is so tied around the declarations I fear it would complicate the flow even more. Would it be better to split the refacto in a PR to merge and review before this one?

**Comment by nicolas-grekas** [comment]
> It is during container compilation, not a critical path

Actually, it is: the developer experience is directly affected by the compilation time, and making it faster improves the DX. That's why we strive to have the most performant code here also.

**Comment by alex-dev** [comment]
> Actually, it is: the developer experience is directly affected by the compilation time, and making it faster improves the DX. That's why we strive to have the most performant code here also.

The only applicable ways I know to delay computation are:
1. Proxy the computation in a callable or an object;
2. Too many if statements to handle the branching;

Simplest way is likely to be an anonymous class.
It is likely to become a bigger merge nightmare than the previous refactorisation.

**Comment by alex-dev** [comment]
Restarting from nothing; Only the tests are left.

**Comment by alex-dev** [comment]
array_key_last... Should I force symfony/dependency-injection to depend of symfony/polyfill-php73 or implement an internal polyfill?

**Comment by nicolas-grekas** [comment]
use `end($array); return key($array);`

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @alex-dev.
