### PR TITLE
[FrameworkBundle] Add comment about design decision

### LINKED ISSUE #43941: [Secrets] Renaming a secret doesn't work
### Symfony version(s) affected

5.4.0

### Description

I have some secrets in my codebase.
When I rename a file let's say `dev.ALGOLIA_API_KEY.b46f8f` to `dev.ALGOLIA_API_KEY_ADMIN.b46f8f` then the file is not loaded anymore by the SodiumVault.

The issue is because of the MD5 hash at the end of the filename `b46f8f`.

This hash comes from the secret's name `ALGOLIA_API_KEY` so if the name changes then the hash must change too.

### How to reproduce

Rename an existing secret

### Possible Solution

I can't figure out why this hash is needed.

So I identify these solutions as potential fixes:
1. Comment in SodiumVault.php why there is a hash & Update the doc to state that secrets can't be renamed
2. Remove the use of the hash (with a deprecation notice & co to preserve BC)

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by sylfabre**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes/no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #43941
| License       | MIT
| Doc PR        | N/A

Adds a comment about a design as per https://github.com/symfony/symfony/issues/43941#issuecomment-964469635

This PR also removes a very tiny bit of code duplication

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/Secrets/SodiumVault.php [hunk 1]
```diff
@@ -100,7 +101,8 @@ public function reveal(string $name): ?string
         $this->lastMessage = null;
         $this->validateName($name);
 
-        if (!is_file($file = $this->pathPrefix.$name.'.'.substr_replace(md5($name), '.php', -26))) {
+        $filename = $this->getFilename($name);
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Secrets/SodiumVault.php:104]: let's use $file everywhere as it was the case, this will prevent needles cs diff and fix L123/125 below

Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Secrets/SodiumVault.php:104]: let's use `$file` everywhere as it was the case, this will prevent needless cs diff and fix L123/125 below

Comment (sylfabre) [reply src/Symfony/Bundle/FrameworkBundle/Secrets/SodiumVault.php:104]: @nicolas-grekas I haven't changed `$file`:
* `$file` is still the full path to the file
* `$filename` is the name of the file without the extension (as per https://www.php.net/manual/en/function.pathinfo.php)

The new method `getFilename()` defines in a single spot this filename to prevent duplication. Before, there were 2 different definitions:
- 2x `$name.'.'.substr_replace(md5($name), '.php', -26)`
- 1x `$name.'.'.substr(md5($name), 0, 6)`

=> Now it's `$this->pathPrefix.$filename.'.php'` everywhere and there is a single definition of `$filename`.

I don't understand your comment about L123/125 🤔

Comment (nicolas-grekas) [reply src/Symfony/Bundle/FrameworkBundle/Secrets/SodiumVault.php:104]: I missread the code, LGTM.

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @sylfabre.
