### PR TITLE
[DoctrineBridge] Fix auto mapping for bundles that contain only embeddables

### LINKED ISSUE #47791: [Doctrine Bridge] Class "%s" is not a valid entity or mapped super class - BC Break
### Symfony version(s) affected

5.4.x

### Description

Hello

The upgrade from Symfony 5.3.x to Symfony 5.4.x led to multiple `MappingException` in one of my project.

From what I could investigate, I think that [this commit](https://github.com/symfony/symfony/pull/43754/commits/98454f8b44f5a2fdd1dc5b73b935435fe636b30e) could be at the origin of - what I consider being a - BC Break as it changes the default value of mapping type from "annotation" to "attribute" in the following use case.

What I describe below is working properly in Symfony 5.3.x.

### How to reproduce

I'm on a legacy project separated into bundles.

One of that bundle provides an embeddable class in an `Entity` folder.

```php
namespace App\FooBundle\Entity;

/**
 * @ORM\Embeddable
 */
class Foo
{
}
```

⚠️ It's important to ensure that there's no entity in the `App\FooBundle\Entity`, only the embeddable.

Then Another bundle contains an entity using that embeddable

```php
namespace App\BarBundle\Entity;

/**
 * @ORM\Entity
 */
class Bar
{
    /**
     * @ORM\Embedded(class="App\FooBundle\Entity\Foo")
     *
     * @var Foo
     */
    protected $foo;
}
```

and the doctrine configuration is the following:

```yaml
# config/packages/doctrine.yaml

orm:
    auto_mapping: true
    # "mappings" key is not defined
```

### Possible Solution

The solution I found is to explicitly define the mapping type in doctrine configuration

```yaml 
# config/packages/doctrine.yaml

orm:
  mappings:
    AppFooBundle:
      is_bundle: true
      type: annotation
```

I don't know if any change has to be done regarding the code itself, maybe it requires an additional row[ in this part of the upgrade documentation](https://github.com/symfony/symfony/blob/5.4/UPGRADE-5.4.md#doctrinebridge).

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jorissae**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #47791
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php [hunk 1]
```diff
@@ -307,14 +307,18 @@ private function detectMappingType(string $directory, ContainerBuilder $containe
         $container->addResource($glob);
 
         $quotedMappingObjectName = preg_quote($this->getMappingObjectDefaultName(), '/');
+        $quotedMappingEmbeddableObjectName = preg_quote('Embeddable', '/');
```
Comment (stof) [inline src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php]: As this is not dynamic, I would remove the variable and inline it in the regex

File: src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php [hunk 2]
```diff
@@ -307,14 +307,18 @@ private function detectMappingType(string $directory, ContainerBuilder $containe
...
 
         foreach ($glob as $file) {
             $content = file_get_contents($file);
 
             if (preg_match('/^#\[.*'.$quotedMappingObjectName.'\b/m', $content)) {
```
Comment (stof) [inline src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php]: Shouldn't this also support embeddable ?

File: src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php [hunk 3]
```diff
@@ -311,10 +311,16 @@ private function detectMappingType(string $directory, ContainerBuilder $containe
         foreach ($glob as $file) {
             $content = file_get_contents($file);
 
-            if (preg_match('/^#\[.*'.$quotedMappingObjectName.'\b/m', $content)) {
+            if (
+                preg_match('/^#\[.*'.$quotedMappingObjectName.'\b/m', $content) ||
+                preg_match('/^#\[.*'.preg_quote('Embeddable', '/').'\b/m', $content)
```
Comment (stof) [inline src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php]: Remove the preg_quote call entirely here (thus, for this particular case, it is a no-op as there is no special characters). And even if there were some, it would still be a good idea to apply the necessary escaping in the source code to keep a literal regexp when it does not need to be dynamic.

**Comment by derrabus** [comment]
Would it be possible to cover this change with a test?

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you @jorissae.
