### PR TITLE
[Notifier] [OvhCloud] “Invalid signature” for message with slashes

### LINKED ISSUE #39836: [Notifier] [OvhCloud] “Invalid signature” for message with slashes
**Symfony version(s) affected**: 5.1.

**Description**  
"Invalid signature error" when i try to send a sms with ovh cloud which contain an url.

**How to reproduce**  
```
$message = "https://symfony.com/doc/current/index.html"
$notification = (new Notification($message))
    ->content('foo')
    ->importance(Notification::IMPORTANCE_HIGH);

$recipient = new AdminRecipient('insert email', 'insert phonenumber');

$this->notifier->send($notification, $recipient);
```

**Possible Solution** 
The json used as a signature is different from the json send by HTTPClient, resulting in an invalid signature

OvhCloudTransport.php (Line 79) 
Remove \JSON_UNESCAPED_SLASHES

` $toSign = $this->applicationSecret.'+'.$this->consumerKey.'+POST+'.$endpoint.'+'.json_encode($content, \JSON_UNESCAPED_SLASHES).'+'.$now;`

to

` $toSign = $this->applicationSecret.'+'.$this->consumerKey.'+POST+'.$endpoint.'+'.json_encode($content).'+'.$now;`

**Additional context**  
image

### PR DESCRIPTION
**Pull request by OneT0uch**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no 
| Tickets       | Fix #39836 
| License       | MIT

Test to show issue of invalid signature when message contains slash.

### CODE REVIEW

File: src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php [hunk 1]
```diff
@@ -44,4 +48,42 @@ public function unsupportedMessagesProvider(): iterable
         yield [new ChatMessage('Hello!')];
         yield [$this->createMock(MessageInterface::class)];
     }
+
+    public function messagesProvider(): iterable
+    {
+        yield ['hello'];
+        yield ['hel/lo'];
```
Comment (OskarStark) [inline src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php]:
```suggestion
        yield 'without a slash' => ['hello'];
        yield 'including a slash' => ['hel/lo'];
```

File: src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php [hunk 2]
```diff
@@ -44,4 +48,42 @@ public function unsupportedMessagesProvider(): iterable
...
+    }
+
+    /**
+     * @dataProvider messagesProvider
+     */
+    public function testSendWithNotification(string $message): void
```
Comment (OskarStark) [inline src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php]: @derrabus shall we mark this test timesensitive?

**Comment by OskarStark** [comment]
CleanShot 2021-01-18 at 20 46 33

It looks like your Committer email is not associated with your Github account.

Could it be so easy to check if a `/` is present in the message and decide upon that how to create the signature? 🤔

File: src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php (hunk 2 above)
Comment (derrabus) [reply src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php]: I think so, yes.

File: src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php [hunk 3]
```diff
@@ -44,4 +48,42 @@ public function unsupportedMessagesProvider(): iterable
...
+
+    public function messagesProvider(): iterable
+    {
+        yield 'without a slash' => ['hello'];
+        yield 'including a slash' => ['hel/lo'];
+    }
+
+    /**
+     * @dataProvider messagesProvider
+     */
```
Comment (OskarStark) [inline src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php]:
```suggestion
    /**
     * @group time-sensitive
     *
     * @dataProvider messagesProvider
     */
```

**Comment by fabpot** [comment]
@OneT0uch Are you working on a fix?

**Comment by OneT0uch** [comment]
> @OneT0uch Are you working on a fix?

@fabpot I opened the PR just to show the issue as asked but i don't know how to fix.

**Comment by fabpot** [comment]
Then I think we are going to close as the core team is not able to fix provider issues. The only to get a fix is by users of the providers. You can also ping the various contributors (especially the one who submitted the provider in the first place) if they can help.

**Comment by OskarStark** [comment]
I will have a detailed look 👍

**Comment by OneT0uch** [comment]
@OskarStark Can't we just remove the unescaped slashes flag? Do you know why we need it?

**Comment by OskarStark** [comment]
I think not, based on their official PHP client they use it too:
https://github.com/ovh/php-ovh/blob/c473b3d67e5757c188b10e3048aba1ec43133653/src/Api.php#L267-L303

It would be maybe you can open an issue in their repo how they handle your case or if they have a recommendation 🤔 

Can you ping me on the symfony slack ?

**Comment by OskarStark** [comment]
Can you please try to apply the following diff in this PR and see if the tests pass?
```diff
diff --git a/src/Symfony/Component/Notifier/Bridge/OvhCloud/OvhCloudTransport.php b/src/Symfony/Component/Notifier/Bridge/OvhCloud/OvhCloudTransport.php
index 4d737019c3..a6f41bc6b3 100644
--- a/src/Symfony/Component/Notifier/Bridge/OvhCloud/OvhCloudTransport.php
+++ b/src/Symfony/Component/Notifier/Bridge/OvhCloud/OvhCloudTransport.php
@@ -76,7 +76,13 @@ final class OvhCloudTransport extends AbstractTransport
         $headers['X-Ovh-Application'] = $this->applicationKey;
         $headers['X-Ovh-Timestamp'] = $now;

-        $toSign = $this->applicationSecret.'+'.$this->consumerKey.'+POST+'.$endpoint.'+'.json_encode($content, \JSON_UNESCAPED_SLASHES).'+'.$now;
+        if (false !== strpos($message->getSubject(), '/')) {
+            $body = json_encode($content);
+        } else {
+            $body = json_encode($content, \JSON_UNESCAPED_SLASHES);
+        }
+
+        $toSign = $this->applicationSecret.'+'.$this->consumerKey.'+POST+'.$endpoint.'+'.$body.'+'.$now;
         $headers['X-Ovh-Consumer'] = $this->consumerKey;
         $headers['X-Ovh-Signature'] = '$1$'.sha1($toSign);
```

File: src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php [hunk 4]
```diff
@@ -44,4 +48,44 @@ public function unsupportedMessagesProvider(): iterable
...
+        yield 'without a slash' => ['hello'];
+        yield 'including a slash' => ['hel/lo'];
+    }
+
+    /**
+     * @group time-sensitive
+     *
+     * @dataProvider messagesProvider
+     */
+    public function testSendWithNotification(string $message): void
```
Comment (OskarStark) [inline src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php]:
```suggestion
    public function testSendWithNotification(string $message)
```

File: src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php [hunk 5]
```diff
@@ -44,4 +48,44 @@ public function unsupportedMessagesProvider(): iterable
...
+        $adminRecipient = new AdminRecipient('foo@bar', '0611223344');
+
+        $smsMessage = SmsMessage::fromNotification($notification, $adminRecipient);
+
+        $time = time();
+
+        $lastResponse = new MockResponse();
+        $responses = [
+            new MockResponse((string) $time),
+            $lastResponse
```
Comment (OskarStark) [inline src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php]:
```suggestion
            $lastResponse,
```

**Comment by OneT0uch** [comment]
> Can you please try to apply the following diff in this PR and see if the tests pass?
> 
> ```diff
> diff --git a/src/Symfony/Component/Notifier/Bridge/OvhCloud/OvhCloudTransport.php b/src/Symfony/Component/Notifier/Bridge/OvhCloud/OvhCloudTransport.php
> index 4d737019c3..a6f41bc6b3 100644
> --- a/src/Symfony/Component/Notifier/Bridge/OvhCloud/OvhCloudTransport.php
> +++ b/src/Symfony/Component/Notifier/Bridge/OvhCloud/OvhCloudTransport.php
> @@ -76,7 +76,13 @@ final class OvhCloudTransport extends AbstractTransport
>          $headers['X-Ovh-Application'] = $this->applicationKey;
>          $headers['X-Ovh-Timestamp'] = $now;
> 
> -        $toSign = $this->applicationSecret.'+'.$this->consumerKey.'+POST+'.$endpoint.'+'.json_encode($content, \JSON_UNESCAPED_SLASHES).'+'.$now;
> +        if (false !== strpos($message->getSubject(), '/')) {
> +            $body = json_encode($content);
> +        } else {
> +            $body = json_encode($content, \JSON_UNESCAPED_SLASHES);
> +        }
> +
> +        $toSign = $this->applicationSecret.'+'.$this->consumerKey.'+POST+'.$endpoint.'+'.$body.'+'.$now;
>          $headers['X-Ovh-Consumer'] = $this->consumerKey;
>          $headers['X-Ovh-Signature'] = '$1$'.sha1($toSign);
> ```

Your solution is working but i think it will be better to follow official sdk :
They apply flag on the body too (https://github.com/ovh/php-ovh/blob/c473b3d67e5757c188b10e3048aba1ec43133653/src/Api.php#L273)

```php
// Add Content type
$headers['Content-Type'] = 'application/json';

// Store json encode content 
$body = json_encode($content, \JSON_UNESCAPED_SLASHES);

$toSign = $this->applicationSecret.'+'.$this->consumerKey.'+POST+'.$endpoint.'+'.$body.'+'.$now;
$response = $this->client->request('POST', $endpoint, [
           'headers' => $headers,
           'body' => $body, // Use it here
       ]);
```

**Comment by OskarStark** [comment]
That makes sense, can you please change the code accordingly?

File: src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php [hunk 6]
```diff
@@ -60,7 +60,7 @@ public function messagesProvider(): iterable
      *
      * @dataProvider messagesProvider
```
Comment (OskarStark) [inline src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php]:
```suggestion
     * @dataProvider validMessagesProvider
```

File: src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php [hunk 7]
```diff
@@ -44,4 +48,44 @@ public function unsupportedMessagesProvider(): iterable
         yield [new ChatMessage('Hello!')];
         yield [$this->createMock(MessageInterface::class)];
     }
+
+    public function messagesProvider(): iterable
```
Comment (OskarStark) [inline src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php]:
```suggestion
    public function validMessagesProvider(): iterable
```

File: src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php [hunk 8]
```diff
@@ -44,4 +48,44 @@ public function unsupportedMessagesProvider(): iterable
...
+
+        $lastResponse = new MockResponse();
+        $responses = [
+            new MockResponse((string) $time),
+            $lastResponse,
+        ];
+
+        $client = new MockHttpClient($responses);
+
+        $transport = $this->createTransport($client);
```
Comment (OskarStark) [inline src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php]:
```suggestion
        $transport = $this->createTransport($new MockHttpClient($responses));
```

File: src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php [hunk 9]
```diff
@@ -44,4 +48,44 @@ public function unsupportedMessagesProvider(): iterable
...
+     * @group time-sensitive
+     *
+     * @dataProvider messagesProvider
+     */
+    public function testValidSignature(string $message)
+    {
+        $notification = new Notification($message);
+        $adminRecipient = new AdminRecipient('foo@bar', '0611223344');
+
+        $smsMessage = SmsMessage::fromNotification($notification, $adminRecipient);
```
Comment (OskarStark) [inline src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php]:
```suggestion
        $smsMessage = new SmsMessage(.....);
```

This should be enough, no need to deal with a `Notification` object.

**Review by OskarStark — APPROVED** [review]

File: src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php [hunk 10]
```diff
@@ -44,4 +46,39 @@ public function unsupportedMessagesProvider(): iterable
...
+        ];
+
+        $transport = $this->createTransport(new MockHttpClient($responses));
+        $transport->send($smsMessage);
+
+        $body = $lastResponse->getRequestOptions()['body'];
+        $headers = $lastResponse->getRequestOptions()['headers'];
+        $signature = explode(': ', $headers[4])[1];
+
+        $endpoint = sprintf('https://%s/1.0/sms/%s/jobs', 'eu.api.ovh.com', 'serviceName');
```
Comment (stof) [inline src/Symfony/Component/Notifier/Bridge/OvhCloud/Tests/OvhCloudTransportTest.php]: why using sprintf for static parts ?

**Review by OskarStark — APPROVED** [review]

File: src/Symfony/Component/Notifier/Bridge/OvhCloud/OvhCloudTransport.php [hunk 11]
```diff
@@ -75,20 +75,22 @@ protected function doSend(MessageInterface $message): void
...
             'headers' => $headers,
-            'json' => $content,
+            'body' => $body,
         ]);
 
         if (200 !== $response->getStatusCode()) {
             $error = $response->toArray(false);
 
-            throw new TransportException(sprintf('Unable to send the SMS: %s.', $error['message']), $response);
+            throw new TransportException(sprintf('Unable to send the SMS: "%s".', $error['message']), $response);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Notifier/Bridge/OvhCloud/OvhCloudTransport.php]: this should be reverted, even if fabbot says it should be updated, that's a false-positive

**Review by nicolas-grekas — APPROVED** [review]

**Comment by OskarStark** [comment]
Thanks for fixing this bug @OneT0uch.

File: src/Symfony/Component/Notifier/Bridge/OvhCloud/OvhCloudTransport.php (hunk 11 above)
Comment (stof) [reply src/Symfony/Component/Notifier/Bridge/OvhCloud/OvhCloudTransport.php]: this could be switched to using concatenation rather than `sprintf` as done elsewhere to avoid the false positive.
