### PR TITLE
[Process] fixed uppercase ARGC and ARGV should also be skipped

### LINKED ISSUE #44534: [Process] ARGV array in env resulting in "Array to string conversion" error
### Symfony version(s) affected

5.4.0

### Description

See https://github.com/symfony/symfony/issues/44197 

Only difference is that ARGV is coming in with capital letters and therefore not caught by the if statement on Process.php line 343

```
if (false !== $v && 'argc' !== $k && 'argv' !== $k) {
```

### How to reproduce

We are following the standard approach for liuggio/fastest bundle, executing our tests with this command:

```
docker-compose exec php bash -c "find tests/ -name \"*Test.php\" | vendor/liuggio/fastest/fastest \"XDEBUG_MODE=coverage bin/phpunit {} --coverage-php cov/fastest/{n}.cov;\""
```

A simple debug of the `$env` at this point shows:

```
...
  "ARGV" => array:2 [
    0 => "vendor/liuggio/fastest/fastest"
    1 => "XDEBUG_MODE=coverage bin/phpunit {} --coverage-php cov/fastest/{n}.cov;"
  ]
  "ARGC" => 2
```

### Possible Solution

```
# Process.php:343
if (false !== $v && false === \in_array(strtolower($k), ['argc', 'argv'], true)) {
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rbaarsma**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44534
| License       | MIT
| Doc PR        | no

uppercase env ARGC and ARGV were showing a warning:
```
[09-Dec-2021 17:17:05 Europe/Amsterdam] PHP Warning:  Array to string conversion in /var/www/app/vendor/symfony/process/Process.php on line 344
```

This PR fixes that by adding upon the existing functionality blocking argv and argc env vars to become part of the eventual env vars.

### CODE REVIEW

File: src/Symfony/Component/Process/Process.php [hunk 1]
```diff
@@ -340,7 +340,7 @@ public function start(callable $callback = null, array $env = [])
 
         $envPairs = [];
         foreach ($env as $k => $v) {
-            if (false !== $v && 'argc' !== $k && 'argv' !== $k) {
+            if (false !== $v && false === \in_array(strtolower($k), ['argc', 'argv'], true)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Process/Process.php]: I'd prefer not calling strtolower for that. Let's use this instead if you don't mind:
`if (false !== $v && false === \in_array($k, ['argc', 'argv', 'ARGC', 'ARGV'], true)) {`

**Review by nicolas-grekas — COMMENTED** [review]
Can you figure out where this uppercase ARGV comes from in your case? It looks like a buggy code. Yes, we were allowing it before, but this was not legit to me.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @rbaarsma.

**Comment by rbaarsma** [comment]
> Can you figure out where this uppercase ARGV comes from in your case? It looks like a buggy code. Yes, we were allowing it before, but this was not legit to me.

@nicolas-grekas I haven't fully debugged how, but it was coming from liuggio/fastest, which executes unit tests in parallel processes. I can dive in deeper that maybe they are doing it wrong and shouldn't do it, but still that should not break Symfony I guess ;)

Also see the related issue on how to reproduce
