### PR TITLE
[Messenger] Catch TableNotFoundException in MySQL delete

### LINKED ISSUE #54120: TableNotFound exception not handled in MySQL handling in Connection::get with autoSetup enabled
### Symfony version(s) affected

7.0

### Description

When using a MySQL based DB, if the database table doesn't exist when calling Connection::get - it will result in an exception even when auto setup is enabled.

### How to reproduce

Call Connection::get on a MySQL based DB when autosetup is enabled and the database table doesn't yet exist

### Possible Solution

Catch a TableNotFoundException inside the if statement at the top of ::get

```
catch (TableNotFoundException) {
 if ($this->autoSetup) {
   $this->setup();
 }
}
```

### Additional Context

This bug was found when implementing a Symfony Messenger based app on a Drupal site using https://www.drupal.org/project/sm - when attempting to consume messages before a message had been created (and therefore the table didn't exist) an exception was thrown.

### PR DESCRIPTION
**Pull request by acbramley**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54120
| License       | MIT

When using a MySQL based DB, if the database table doesn't exist when calling Connection::get - it will result in an exception even when auto setup is enabled.

I still need to look into how/where tests would go.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I suppose 5.4 is also affected? Could you please rebase+retarget for the lowest affected (and maintained) branch?

**Comment by acbramley** [comment]
Thanks @nicolas-grekas - rebased against 5.4

File: src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php [hunk 1]
```diff
@@ -161,6 +161,10 @@ public function get(): ?array
                 $this->driverConnection->delete($this->configuration['table_name'], ['delivered_at' => '9999-12-31 23:59:59']);
             } catch (DriverException $e) {
                 // Ignore the exception
+            } catch (TableNotFoundException) {
```
Comment (fabpot) [inline src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/Connection.php]:
```suggestion
            } catch (TableNotFoundException $e) {
```

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @acbramley.

**Comment by acbramley** [comment]
Thanks @fabpot! What's the process of forward-porting this up to 7.1?

**Comment by fabpot** [comment]
We’re merging branches up regularly, so nothing needed on your side.
