### PR TITLE
[HttpFoundation] allow additinal characters in not raw cookies

### LINKED ISSUE #33619: Cannot create cookie with name containing some characters
**Symfony version(s) affected**: All

**Description**  
When creating a non-raw Cookie, it is impossible to provide a name that contains characters matching the regex class `[=,; \t\r\n\013\014]` even though `__toString` later performs a urlencode to sanitise this field for output.

**How to reproduce**  
```$cookie = new Cookie('yes=please');```

**Possible Solution**  
I would expect for it to be permissible to supply any value for the name in the same way that you can for the value in non-raw mode by performing the [character validation](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Cookie.php#L89) only in raw mode:
```
if ($raw && preg_match("/[=,; \t\r\n\013\014]/", $name)) {
    throw new \InvalidArgumentException(sprintf('The cookie name "%s" contains invalid characters.', $name));
}
```

**Additional context**  
It is possible to work around this issue by creating a Cookie in raw mode, but this places additional burden on the implementing application to take care of encoding both the name and value at all times. In my particular use case I am also making use of the [Illuminate Cookie Jar forget method](https://laravel.com/api/5.5/Illuminate/Cookie/CookieJar.html#method_forget) which does not expose the ability to operate in raw mode.

### PR DESCRIPTION
**Pull request by marie**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| Tickets       | Fix #33619
| License     | MIT 

> **Description**
> When creating a non-raw Cookie, it is impossible to provide a name that contains characters matching the regex class [=,; \t\r\n\013\014]

**Solution**: Check with this regex only raw cookie

### CODE REVIEW

File: src/Symfony/Component/HttpFoundation/Cookie.php [hunk 1]
```diff
@@ -93,7 +93,7 @@ public function __construct(string $name, string $value = null, $expire = 0, ?st
         }
 
         // from PHP source code
-        if (preg_match("/[=,; \t\r\n\013\014]/", $name)) {
+        if ($raw && preg_match("/[=,; \t\r\n\013\014]/", $name)) {
```
Comment (terjebraten-certua) [inline src/Symfony/Component/HttpFoundation/Cookie.php]: I think you got this test wrong. Now you only check the regex if `$raw` is `true` and ignore the regex if `$raw` is `false`. I guess it should be the other way around.

Just replace `&&` with `||` and it will be fine.

**Review by terjebraten-certua — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/HttpFoundation/Cookie.php (hunk 1 above)
Comment (trvrnrth) [reply src/Symfony/Component/HttpFoundation/Cookie.php]: I had this wrong in my original bug report as well (edited now). I'd expect this to be:
```
if (!$raw && preg_match("/[=,; \t\r\n\013\014]/", $name)) {
```
Changing it to || would always throw the exception in raw mode rather than skipping the check.

Comment (trvrnrth) [reply src/Symfony/Component/HttpFoundation/Cookie.php]: This looks correct to me. The regex only needs checking in raw mode. In non-raw mode the output is later sanitised (urlencoded) in __toString so the check here isn't necessary.

It does look like the test suite also needs updating to only test for this exception when operating in raw mode though.

(Please ignore my previous comment on this, I was reading this backwards myself too!)

**Review by terjebraten-certua — APPROVED** [review]

**Review by terjebraten-certua — CHANGES_REQUESTED** [review]
Failing tests need to be changed

File: src/Symfony/Component/HttpFoundation/Cookie.php (hunk 1 above)
Comment (terjebraten-certua) [reply src/Symfony/Component/HttpFoundation/Cookie.php]: ok, just ignore my comment too then.

Comment (marie) [reply src/Symfony/Component/HttpFoundation/Cookie.php]: If I replace the condition with || the exception will be throw for any value if raw=true. 
The issue that we don't need to check the regex if cookie is not raw, because we encode the name and value anyway.

**Comment by marie** [comment]
Hello! 
I have a question. In the fixtures expected values for sent cookies are: 
```
    [3] => Set-Cookie: %3F%2A%28%29%3A%40%26%2B%24%2F%25%23%5B%5D=%3F%2A%28%29%3A%40%26%2B%24%2F%25%23%5B%5D; path=/
    [4] => Set-Cookie: ?*():@&+$/%#[]=%3F%2A%28%29%3A%40%26%2B%24%2F%25%23%5B%5D; path=/
```
number 3 is for Symfony's function `$response->sendHeaders` and number 4 is for php's native function setcookie. Thus the symfony's function have different behaviour from setcookie function. Do you think this is alright?

**Comment by trvrnrth** [comment]
That looks like it could be problematic so I think it would be best to maintain full compatibility.

@marie I've PR'ed to your branch at https://github.com/marie/symfony/pull/1/files with a proposed solution to only encode the required characters. The general approach is borrowed from the Guzzle PSR-7 Uri implementation.

**Review by terjebraten-certua — APPROVED** [review]

**Review by trvrnrth — APPROVED** [review]

**Comment by marie** [comment]
Does anybody know how to rebuild failed because of timeout pipeline? Probably I don't have rights

**Comment by fabpot** [comment]
@marie I've just restarted the job for you.

**Comment by marie** [comment]
@fabpot thank you!

File: src/Symfony/Component/HttpFoundation/Cookie.php [hunk 2]
```diff
@@ -29,6 +29,8 @@ class Cookie
     private $sameSite;
     private $secureDefault = false;
 
+    private static $charNameReserved = "=,; \t\r\n\013\014";
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Cookie.php]: this should be a `private const`

File: src/Symfony/Component/HttpFoundation/Cookie.php [hunk 3]
```diff
@@ -93,7 +95,7 @@ public function __construct(string $name, string $value = null, $expire = 0, ?st
         }
 
         // from PHP source code
-        if (preg_match("/[=,; \t\r\n\013\014]/", $name)) {
+        if ($raw && preg_match('/['.self::$charNameReserved.']/', $name)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Cookie.php]: let's replace the preg_match by `false !== strpbrk($name, self::RESERVED_CHARS)`

File: src/Symfony/Component/HttpFoundation/Cookie.php [hunk 4]
```diff
@@ -141,7 +143,13 @@ public function __construct(string $name, string $value = null, $expire = 0, ?st
      */
     public function __toString()
     {
-        $str = ($this->isRaw() ? $this->getName() : urlencode($this->getName())).'=';
+        if ($this->isRaw()) {
+            $str = $this->getName();
+        } else {
+            $str = preg_replace_callback('/['.self::$charNameReserved.']/', [$this, 'rawurlencodeMatchZero'], $this->getName());
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Cookie.php]: I'd suggest using a str_replace instead of the PCRE+callback infrastructure

File: src/Symfony/Component/HttpFoundation/Cookie.php [hunk 5]
```diff
@@ -93,7 +95,7 @@ public function __construct(string $name, string $value = null, $expire = 0, ?st
         }
 
         // from PHP source code
-        if (preg_match("/[=,; \t\r\n\013\014]/", $name)) {
+        if ($raw && (false !== strpbrk($name, self::RESERVED_CHARS))) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Cookie.php]: the extra brackets should be removed

File: src/Symfony/Component/HttpFoundation/Cookie.php [hunk 6]
```diff
@@ -141,7 +143,15 @@ public function __construct(string $name, string $value = null, $expire = 0, ?st
      */
     public function __toString()
     {
-        $str = ($this->isRaw() ? $this->getName() : urlencode($this->getName())).'=';
+        if ($this->isRaw()) {
+            $str = $this->getName();
+        } else {
+            $reservedChar = str_split(self::RESERVED_CHARS);
+            $reservedCharsEncoded = array_map('rawurlencode', $reservedChar);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Cookie.php]: let's make these a local `static` property to save dong the computation too often?

**Review by nicolas-grekas — COMMENTED** [review]
some more nitpicking :)

File: src/Symfony/Component/HttpFoundation/Cookie.php (hunk 6 above)
Comment (marie) [reply src/Symfony/Component/HttpFoundation/Cookie.php]: I've fixed. Is it ok now?

Thank you for your review! Your comments are very helpful.

File: src/Symfony/Component/HttpFoundation/Cookie.php [hunk 7]
```diff
@@ -132,6 +136,11 @@ public function __construct(string $name, string $value = null, $expire = 0, ?st
         }
 
         $this->sameSite = $sameSite;
+
+        if (empty(static::$reservedChars) && empty(static::$reservedCharsEncoded)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Cookie.php]: let's just do: `if (!self::$reservedChars) {`

File: src/Symfony/Component/HttpFoundation/Cookie.php [hunk 8]
```diff
@@ -132,6 +136,11 @@ public function __construct(string $name, string $value = null, $expire = 0, ?st
...
+            static::$reservedChars = str_split(self::RESERVED_CHARS);
+            static::$reservedCharsEncoded = array_map('rawurlencode', static::$reservedChars);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpFoundation/Cookie.php]: we should use self:: here and above

File: src/Symfony/Component/HttpFoundation/Cookie.php (hunk 7 above)
Comment (marie) [reply src/Symfony/Component/HttpFoundation/Cookie.php]: This is an array, why it's better to treat it like boolean?

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpFoundation/Cookie.php]: `if` is not a function, it's a language construct. This argument doesn't make sense.

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
@marie To help me merge this PR, can you squash the commits? Also, is it for 4.3 only, don't we have the same issue on 3.4?

**Comment by marie** [comment]
@fabpot yes, we have to merge it to 3.4 too. Should I create a new PR instead of this one?

Do you know why one of builds failed with error -1073741819?

**Comment by nicolas-grekas** [comment]
No worries, I'm going to take care of the rebase.

**Comment by nicolas-grekas** [comment]
Thank you @marie.
