### PR TITLE
[SecurityBundle] Make user lazy loading working without user provider

### LINKED ISSUE #38429: [Security] providers become mandatory without any warning when using new authenticator system
**Symfony version(s) affected**: 5.2.0-beta1

**Description**  

I just try to update to latest beta and it seems that `providers` config in `security.yaml` became mandatory when enabling new authenticator manager.

Without any providers i get the following error :
image

But in Symfony 5.1.7, it was not a big deal to not having a user provider.

**How to reproduce**  

Remove any providers and using `enable_authenticator_manager: true`

**Possible Solution**  

I would check if we have really one provider here:
https://github.com/symfony/symfony/blob/5f1c3a797247a6d54992384df00bb22741fc1c34/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L256

If not throw an exception saying, you must provide a user_provider.

I'm ready to make a PR you are fine with this solution.

**Additional context**  

I don't have any provider as I use aws cognito JWT system where user identity is in the token.

### PR DESCRIPTION
**Pull request by tyx**
| Q             | A
| ------------- | ---
| Branch?       | 5.x 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #38429  
| License       | MIT

Make user lazy loading in security working again without user provider.

### CODE REVIEW

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 1]
```diff
@@ -249,10 +249,13 @@ private function createFirewalls(array $config, ContainerBuilder $container)
         }
         $arguments[1] = $userProviderIteratorsArgument = new IteratorArgument($userProviders);
         $contextListenerDefinition->setArguments($arguments);
+        $nbUserProviders = \count($userProviders);
 
-        if (\count($userProviders) > 1) {
+        if ($nbUserProviders > 1) {
             $container->setDefinition('security.user_providers', new Definition(ChainUserProvider::class, [$userProviderIteratorsArgument]))
                 ->setPublic(false);
+        } elseif (0 == $nbUserProviders) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php]: `===`

File: src/Symfony/Bundle/SecurityBundle/Tests/Functional/Bundle/AuthenticatorBundle/ApiAuthenticator.php [hunk 2]
```diff
@@ -36,7 +44,12 @@ public function authenticate(Request $request): PassportInterface
             throw new BadCredentialsException('Email is not a valid email address.');
         }
 
-        return new SelfValidatingPassport(new UserBadge($email));
+        $userLoader = null;
+        if (true === $this->selfLoadingUser) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/SecurityBundle/Tests/Functional/Bundle/AuthenticatorBundle/ApiAuthenticator.php]: `if ($this->selfLoadingUser) {`

**Review by wouterj — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @tyx.
