### PR TITLE
[Cache] Throw ValueError in debug mode when serialization fails

### LINKED ISSUE #41685: In debug mode, the cache component could throw when save() fails
In debug mode, the cache component could throw when save() fails

This would not be compliant with PSR-6, but in debug mode, that's fine really.

This might help spot situations where eg a Closure is (not) cached.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | -
| Tickets       | Fix #41685
| License       | MIT
| Doc PR        | -

This feature allows spotting mistakes at the dev stage when trying to store unserializable objects (typically a closure) into a cache.

This PR replaces #42241 with a simpler and more focused approach: here we fail via a simple `ValueError`, which won't get caught by any try/catch into the Cache component, and we fail only when serialization fails - not on any failures of cache pool methods.

### CODE REVIEW

File: src/Symfony/Component/Cache/Marshaller/DefaultMarshaller.php [hunk 1]
```diff
@@ -21,15 +21,17 @@
 class DefaultMarshaller implements MarshallerInterface
 {
     private $useIgbinarySerialize = true;
+    private $debug;
 
-    public function __construct(bool $useIgbinarySerialize = null)
+    public function __construct(bool $useIgbinarySerialize = null, bool $debug = false)
```
Comment (stof) [inline src/Symfony/Component/Cache/Marshaller/DefaultMarshaller.php]: I'd rather name it `$throwOnSerializationFailure` than `$debug`, to make it more clear what it's effect is (which does not prevent using `%kernel.debug%` as the value injected in it)

Comment (nicolas-grekas) [reply src/Symfony/Component/Cache/Marshaller/DefaultMarshaller.php]: works for me, updated

**Review by stof — APPROVED** [review]
