### PR TITLE
[RFC][HttpKernel][Security] Allowed adding attributes on controller arguments that will be passed to argument resolvers.

### LINKED ISSUE #29692: [RFC][HttpKernel] Configurable argument value resolvers
Hi everyone!

Recently got interested in `@ParamConverter`s as a convenient extension point in Symfony. Some time ago in https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/436 @fabpot proposed an idea on how to implement configurable argument resolvers. Let me explain the idea:
- A single annotation `@Arg(string $name, array options = [])` is proposed as a replacement for `@ParamConverter`.
- A new interface `ArgumentValueOptionsInterface extends ArgumentValueResolverInterface` adds `configure(OptionsResolver $resolver)` method.
- A new subscriber `ControllerArgumentOptionsListener` listens to the `KernelEvents::CONTROLLER` event and looks for `@Arg` mappings for the current controller callable. Then it iterates over the `ArgumentValueOptionsInterface[]` instances to find a resolver based on `supports(Request $request, ArgumentMetadata $argument)`. Once the resolver is found, `@Arg.options` are resolved and saved to `$request->attributes->set($name.'_options', $resolvedOptions)`.
- Later in `SomeArgumentValueResolver::resolve(Request $request, ArgumentMetadata $argument)` we receive resolved options by calling `$request->attributes->get($name.'_options', [])` and use them to yield the value.

While I think that this is a nice solution (especially when looking from the perspective of the `FrameworkExtraBundle`), it has one important drawback. `@ParamConverter` has a possibility to specify converter explicitly by leveraging the `converter` argument. It allows to resolve arguments which by themselves do not provide enough information to find a resolver. A great example is `@ParamConverter("name", converter="fos_rest.request_body")` from [FOSRestBundle](https://symfony.com/doc/master/bundles/FOSRestBundle/request_body_converter_listener.html). This converter allows to deserialize `$request->getContent()` into a DTO based on the argument type hint. Unlike `SomeEntityClass` which we can check with `ManagerRegistry::getManagerForClass()`, `SomeDTOClass` does not give any hint that it should be processed by a `RequestBodyParamConverter`. So, the `@Arg` concept without a possibility to be explicit about the resolver seems to be not suitable for this case.

I have a different idea. It think, it fits the `HttpKernel` much better than the bundle, that's why I am creating an issue here. 

_Btw, the idea to move `@ParamConverters` configuration to the core was already discussed in https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/436#issuecomment-249283532._

### Design

1. Let's agree that once the argument is explicitly configured (for example by an annotation), we already know what resolver it should be processed by. It's like with validator constraints. So I propose to create the following interface:

    ```php
    interface ArgumentConfigInterface
    {
        /**
         * Returns the FQCN of the argument value resolver that resolves the argument with this config.
         */
        public function resolvedBy(): string;
    }
    ```

1. I think that within the `HttpKernel` component this config might be a part of argument's metadata. Later it will allow us to cache everything together easily. Thus let's add another property to the `ArgumentMetadata`:

    ```php
    namespace Symfony\Component\HttpKernel\ControllerMetadata;

    class ArgumentMetadata
    {
        // ...

        private $config;

        public function __construct(
            string $name,
            ?string $type,
            bool $isVariadic,
            bool $hasDefaultValue,
            $defaultValue,
            bool $isNullable = false,
            ?ArgumentConfigInterface $config = null
        ) {
           // ...

           $this->config = $config;
        }

        // ...

        public function getConfig(): ?ArgumentConfigInterface
        {
            return $this->config;
        }
    }
    ```

1. Should we stick to the annotation mapping? No, let's create an extension point!

    ```php
    interface ArgumentConfigLoaderInterface
    {
        public function getArgumentConfig(callable $controller, string $name): ?ArgumentConfigInterface;
    }

    final class AnnotationArgumentConfigLoader implements ArgumentConfigLoaderInterface
    {
        public function __construct(Doctrine\Common\Annotations\Reader $reader)
        {
            // ...
        }
    }
    ```

    Now we can inject `ArgumentConfigLoaderInterface` into `ArgumentMetadataFactory` and produce config aware `ArgumentMetadata` instances.

1. Next, let's adjust `ArgumentResolver`. Previously we retrieved converters only by iteration, now we want to get them by FQCN as well.

    ```php
    namespace Symfony\Component\HttpKernel\Controller;

    final class ArgumentResolver implements ArgumentResolverInterface
    {
        // ...

        private $argumentValueResolversByClass;

        public function __construct(
            // ...
            ?ContainerInterface $argumentValueResolversByClass = null
        ) {
            // ...
            $this->argumentValueResolversByClass = $argumentValueResolversByClass ?: self::getDefaultArgumentValueResolversByClass();
        }

        // ...

        private function getResolver(Request $request, ArgumentMetadata $metadata): ArgumentValueResolverInterface
        {
            if (null !== $config = $metadata->getConfig()) {
                return $this->argumentValueResolversByClass->get($config->resolvedBy());
            }

            foreach ($this->argumentValueResolvers as $resolver) {
                if ($resolver->supports($request, $metadata)) {
                    return $resolver;
                }
            }

            throw new \RuntimeException();
        }
    }
    ```

1. I think we should also cache all argument metadata. That can be easily done with a decorator `CachingArgumentMetadataFactory implements ArgumentMetadataFactoryInterface`.

After all these non-breaking BC steps we'll be able to create configs like `@Entity`, `@BodyConverter`, `@GetParam` with ease.

### Benefits

- Custom configs for argument value resolvers.
- Faster argument value resolver resolution for configured arguments.
- One point to cache everything.
- Out-of-the-box improved `@ParamConverters` with no need to require `sensio/framework-extra-bundle`.

Ready to discuss!
ping @fabpot, @iltar.

### PR DESCRIPTION
**Pull request by jvasseur**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #29692
| License       | MIT
| Doc PR        | Not yet, will do it it this PR is accepted.

This PR allow to configure argument resolvers using PHP8 attributes.

This is basically a fix for #29692 but using a different strategy that the one proposed in the issue:
 - it uses PHP attributes instead of doctrine annotation since they can be added directly on method arguments.
 - it uses a simpler design by just adding the attribute to the `ArgumentMetadata` and let the individual resolvers decide if they want to react to the presence of the attribute.
 - it uses an attributes classe per use-case instead of an unique `Arg` annotation.

As an example, I've added (in the second commit) a `CurrentUser` attribute that allows the `UserValueResolver` to always inject the current user even if the argument is not typed with the `UserInterface` (to allow typing your actual class instead for example).

This would allow to do things like this:
```php
class MyController
{
    public function indexAction(#[CurentUser] MyUser $user)
    {
    }
}
```

### CODE REVIEW

File: src/Symfony/Component/HttpKernel/Tests/Fixtures/Controller/AttributeController.php [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+namespace Symfony\Component\HttpKernel\Tests\Fixtures\Controller;
+
+use Symfony\Component\HttpKernel\Tests\Fixtures\Attribute\Foo;
+
+class AttributeController
+{
+    public function action(
+        #[Foo('bar')]
+        string $baz
+    ) {
```
Comment (fabpot) [inline src/Symfony/Component/HttpKernel/Tests/Fixtures/Controller/AttributeController.php:21]: Can you move everything on one line? (same below)

**Review by fabpot — APPROVED** [review]
I'm going to play with it a little but the code LGTM.

**Comment by fabpot** [comment]
Thank you @jvasseur.

File: src/Symfony/Component/HttpKernel/ControllerMetadata/ArgumentMetadataFactory.php [hunk 2]
```diff
@@ -34,7 +37,28 @@ public function createArgumentMetadata($controller): array
         }
 
         foreach ($reflection->getParameters() as $param) {
-            $arguments[] = new ArgumentMetadata($param->getName(), $this->getType($param, $reflection), $param->isVariadic(), $param->isDefaultValueAvailable(), $param->isDefaultValueAvailable() ? $param->getDefaultValue() : null, $param->allowsNull());
+            $attribute = null;
+            if (method_exists($param, 'getAttributes')) {
```
Comment (derrabus) [inline src/Symfony/Component/HttpKernel/ControllerMetadata/ArgumentMetadataFactory.php:41]: We've use `\PHP_VERSION_ID >= 80000` in other attribute-related code instead.

File: src/Symfony/Component/HttpKernel/Tests/Fixtures/Controller/AttributeController.php (hunk 1 above)
Comment (jvasseur) [reply src/Symfony/Component/HttpKernel/Tests/Fixtures/Controller/AttributeController.php]: I have use this style so that the code was parsable on a lower PHP version but since it's a fixture file that should be read only on PHP 8 it's not really important.

File: src/Symfony/Component/HttpKernel/ControllerMetadata/ArgumentMetadataFactory.php (hunk 2 above)
Comment (fabpot) [reply src/Symfony/Component/HttpKernel/ControllerMetadata/ArgumentMetadataFactory.php:41]: indeed, fixed in f1f37a899c

**Comment by derrabus** [comment]
Great addition, thanks @jvasseur!
