### PR TITLE
[HttpClient] throw clearer error when no scheme is provided

### LINKED ISSUE #39285: Httpclient produces difficult to debug message when no scheme is present
**Symfony version(s) affected**: 5.1.7

**Description**  
When no base uri is set, and the url does not have a scheme, then you get a rather difficult to debug warning:
`Trying to access array offset on value of type null`.
When the code continues after the waring (in production for example), an error is thrown with the following message:
```
Symfony\Component\HttpClient\Exception\TransportException: URL using bad/illegal format or missing URL for "//localhost:8080/".
```

**How to reproduce**  

The following code should reproduce the error:
```php
HttpClient::create()->request('GET', 'localhost:8080');
```

**Possible Solution**  
Right now there is no check to see if the scheme is present, the code just assumes there is. A more detailed error
should be thrown, to let the user know.

The fix for the user is to change the url to `http://localhost:8080`, but this may not be obvious right away (at least it wasn't for me).

### PR DESCRIPTION
**Pull request by BackEndTea**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #39285 
| License       | MIT
| Doc PR        | N/A

This could be considred a BC break, as previously this would've  a `TransportExcepiton`, instead of an `InvalidArgumentException`. But i see no reason to catch this specific error, as it would generally be a configuration error.

### CODE REVIEW

**Comment by derrabus** [comment]
Looks reasonable to me. Let's see what @nicolas-grekas thinks about this.

File: src/Symfony/Component/HttpClient/HttpClientTrait.php [hunk 1]
```diff
@@ -377,6 +377,10 @@ private static function resolveUrl(array $url, ?array $base, array $queryDefault
             throw new InvalidArgumentException(sprintf('Invalid "base_uri" option: host or scheme is missing in "%s".', implode('', $base)));
         }
 
+        if (null === $url['scheme'] && (null === $base || null === $base['scheme'])) {
+            throw new InvalidArgumentException('Invalid URL: scheme is missing. Did you forget to add "http(s)://"? ');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/HttpClientTrait.php]: extra space at the end, + this should mention the faulty URL, see message below

File: src/Symfony/Component/HttpClient/Tests/HttpClientTraitTest.php [hunk 2]
```diff
@@ -120,6 +120,13 @@ public function provideResolveUrl(): array
         ];
     }
 
+    public function testResolveUrlWithoutScheme(): void
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/Tests/HttpClientTraitTest.php]: ~`: void`~

File: src/Symfony/Component/HttpClient/Tests/HttpClientTraitTest.php [hunk 3]
```diff
@@ -120,6 +120,13 @@ public function provideResolveUrl(): array
...
+    {
+        $this->expectException('Symfony\Component\HttpClient\Exception\InvalidArgumentException');
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/Tests/HttpClientTraitTest.php]: `InvalidArgumentException::class`

**Review by nicolas-grekas — COMMENTED** [review]
Works for me, here are some comments.

File: src/Symfony/Component/HttpClient/HttpClientTrait.php (hunk 1 above)
Comment (BackEndTea) [reply src/Symfony/Component/HttpClient/HttpClientTrait.php]: I've updated the message to contain the url

File: src/Symfony/Component/HttpClient/Tests/HttpClientTraitTest.php (hunk 3 above)
Comment (BackEndTea) [reply src/Symfony/Component/HttpClient/Tests/HttpClientTraitTest.php]: Other tests in this class the the string notation, should i update those as well?

File: src/Symfony/Component/HttpClient/HttpClientTrait.php [hunk 4]
```diff
@@ -377,6 +377,14 @@ private static function resolveUrl(array $url, ?array $base, array $queryDefault
             throw new InvalidArgumentException(sprintf('Invalid "base_uri" option: host or scheme is missing in "%s".', implode('', $base)));
         }
 
+        if (null === $url['scheme'] && (null === $base || null === $base['scheme'])) {
+            $message = 'Invalid URL: scheme is missing in "%s". Did you forget to add "http(s)://"?';
+            if (null === $base) {
+                throw new InvalidArgumentException(sprintf($message, implode('', $url)));
+            }
+            throw new InvalidArgumentException(sprintf($message, implode('', $base)));
```
Comment (derrabus) [inline src/Symfony/Component/HttpClient/HttpClientTrait.php]:
```suggestion
            throw new InvalidArgumentException(sprintf('Invalid URL: scheme is missing in "%s". Did you forget to add "http(s)://"?', implode('', $base ?? $url)));
```

**Review by derrabus — APPROVED** [review]

**Review by jderusse — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @BackEndTea.

**Comment by BackEndTea** [comment]
Thank you @derrabus , @nicolas-grekas & @fabpot
