### PR TITLE
[Runtime] Make project_dir configurable

### LINKED ISSUE #59954: [Runtime] project_dir option in composer.json always overwritten in autoload_runtime.php
### Symfony version(s) affected

6.4

### Description

the runtime documentation suggests one can [override the project_dir](https://symfony.com/doc/current/components/runtime.html#using-options) in the composer.json, however the generated autoload file will contain an option array with a duplicate key overriding that option when doing so.

### How to reproduce

execute the following commands and inspect the `vendor/autoload_runtime.php` file:

`composer config extra.runtime.project_dir '/foo/bar/' && composer dump-autoload`

### Possible Solution

offending line
https://github.com/symfony/runtime/blob/8e8d09bd69b7f6c0260dd3d58f37bd4fbdeab5ad/Internal/ComposerPlugin.php#L99

could be changed to:
`'%runtime_options%' => '['. substr(var_export(array_merge(['project_dir' => $projectDir], $extra), true), 7, -1)."]",`

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by wickedOne**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #59954
| License       | MIT

this would allow a `composer.json` file at `/alternative/location/composer.json` be configured with

```json
  "extra": {
    "runtime": {
      "project_dir": "/../../"
    }
  }
```
while using

```shell
COMPOSER=/alternative/location/composer.json composer update
```

generate a `autoload_runtime.php` with the following `project_dir`

```php
$runtime = new $runtime(($_SERVER['APP_RUNTIME_OPTIONS'] ?? $_ENV['APP_RUNTIME_OPTIONS'] ?? []) + [
  'project_dir' => dirname(__DIR__, 1),
]);
```

i did not meddle with the autoload template discovery as that's currently already configurable and would introduce a bc break. also it makes sense in a way that every config value is relative to the composer.json file itself

### CODE REVIEW

File: src/Symfony/Component/Runtime/Internal/ComposerPlugin.php [hunk 1]
```diff
@@ -74,7 +74,7 @@ public function updateAutoloadFile(): void
             }
         }
 
-        $projectDir = $fs->makePathRelative($projectDir, $vendorDir);
+        $projectDir = $fs->makePathRelative(realpath($projectDir.($extra['project_dir'] ?? '')), $vendorDir);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Runtime/Internal/ComposerPlugin.php]: doesn't this miss a `/`?
```suggestion
        $projectDir = $fs->makePathRelative(realpath($projectDir.'/'.($extra['project_dir'] ?? '')), $vendorDir);
```

**Review by nicolas-grekas — COMMENTED** [review]
Can this be tested?
Note that this should target 7.3 as it's an improvement, not a butfix

File: src/Symfony/Component/Runtime/Internal/ComposerPlugin.php (hunk 1 above)
Comment (wickedOne) [reply src/Symfony/Component/Runtime/Internal/ComposerPlugin.php]: yes, that makes sense

**Comment by wickedOne** [comment]
> Can this be tested? 

i'm not entirely sure as the plugin uses a lot of built in functions with regards to directory / file locations and a static method to retrieve a composer config.... would you guys even be open to have a dev depdency like vfsStream?

> Note that this should target 7.3 as it's an improvement, not a bugfix

check

File: src/Symfony/Component/Runtime/Internal/ComposerPlugin.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Runtime/Internal/ComposerPlugin.php]: did you forgot this comment?

Comment (wickedOne) [reply src/Symfony/Component/Runtime/Internal/ComposerPlugin.php]: oops, my bad: done

**Comment by nicolas-grekas** [comment]
Thank you @wickedOne.
