### PR TITLE
[JsonStreamer] Fix exponential resource class memory growth

### LINKED ISSUE #63057: [JsonStreamer] Memory exhaustion in StreamerDumper::getResourceClassNames() due to array doubling with spread operator
### Symfony version(s) affected

7.3.x, 7.4.x, 8.0.x, 8.1.x (all current versions)

### Description

The `StreamerDumper::getResourceClassNames()` method causes **exponential memory growth** when processing DTOs with multiple nullable object properties of the same type. Each additional property approximately **doubles memory usage**.

**Root Cause** - In `StreamerDumper.php` lines 93 and 99:

```php
<?php
if (\in_array($t->getClassName(), $classNames, true)) {
    return $classNames;  // Returns the SAME array that was passed in
}

// ... later ...

foreach ($this->propertyMetadataLoader->load($t->getClassName(), [], $context) as $property) {
    $classNames = [...$classNames, ...$this->getResourceClassNames($property->getType(), $classNames)];
}
```

**The Problem:**

1. `$classNames` is passed to the recursive call
2. When an already-seen class is encountered, it returns early with `return $classNames` (the same array)
3. The spread operator then does: `[...$classNames, ...$classNames]` = **DOUBLES the array**
4. Memory grows exponentially: each additional property of an already-seen type doubles memory

**Concrete Evidence:**

```
# With N properties:
Peak memory: 92 MB
Unique classes: 8

# With N+1 properties (added just 1 by 1 more ?Option property):
Peak memory: 180 MB  ← Nearly doubled!
Unique classes: 8    ← Same number of classes

# With N+2 properties: Would exceed 256MB → CRASH
```

### How to reproduce

```php
<?php

require 'vendor/autoload.php';

use Symfony\Component\TypeInfo\Type;
use Symfony\Component\TypeInfo\TypeResolver\TypeResolver;
use Symfony\Component\JsonStreamer\Mapping\PropertyMetadataLoader;

class Option {
    public ?int $id = null;
    public ?string $fi = null;
    public ?string $en = null;
}

class OptionWithName {
    public ?int $id = null;
    public ?string $name = null;
}

class TestDto {
    // Each additional ?Option property DOUBLES memory usage
    public ?Option $option1 = null;
    public ?Option $option2 = null;
    public ?Option $option3 = null;
    public ?Option $option4 = null;
    public ?Option $option5 = null;
    public ?Option $option6 = null;
    public ?Option $option7 = null;
    public ?Option $option8 = null;
    public ?Option $option9 = null;
    public ?Option $option10 = null;

    public ?OptionWithName $named1 = null;
    public ?OptionWithName $named2 = null;
    public ?OptionWithName $named3 = null;
    public ?OptionWithName $named4 = null;
    public ?OptionWithName $named5 = null;
    public ?OptionWithName $named6 = null;
    public ?OptionWithName $named7 = null;
    public ?OptionWithName $named8 = null;
    public ?OptionWithName $named9 = null;
    public ?OptionWithName $named10 = null;

    // Add one by one more to see memory double:
    // public ?Option $option11 = null;
    // public ?Option $option12 = null;
    // public ?Option $option13 = null;
}

$propertyMetadataLoader = new PropertyMetadataLoader(TypeResolver::create());
$type = Type::object(TestDto::class);

// Simulates StreamerDumper::getResourceClassNames() - exact copy of buggy code
function getResourceClassNamesBuggy($type, $loader, array $classNames = [], array $context = []): array {
    $context['original_type'] ??= $type;

    foreach ($type->traverse() as $t) {
        if ($t instanceof \Symfony\Component\TypeInfo\Type\ObjectType) {
            if (in_array($t->getClassName(), $classNames, true)) {
                return $classNames;  // BUG: Returns SAME array
            }

            $classNames[] = $t->getClassName();

            foreach ($loader->load($t->getClassName(), [], $context) as $property) {
                // BUG: Spread operator causes [...$classNames, ...$classNames] = DOUBLE
                $classNames = [...$classNames, ...getResourceClassNamesBuggy($property->getType(), $loader, $classNames, $context)];
            }
        }

        if ($t instanceof \Symfony\Component\TypeInfo\Type\GenericType) {
            foreach ($t->getVariableTypes() as $variableType) {
                $classNames = [...$classNames, ...getResourceClassNamesBuggy($variableType, $loader, $classNames, $context)];
            }
        }
    }

    return array_values(array_unique($classNames));
}

echo "Memory limit: " . ini_get('memory_limit') . "\n";
echo "Starting memory: " . (memory_get_usage(true) / 1024 / 1024) . " MB\n";

$result = getResourceClassNamesBuggy($type, $propertyMetadataLoader);

echo "Final memory: " . (memory_get_usage(true) / 1024 / 1024) . " MB\n";
echo "Peak memory: " . (memory_get_peak_usage(true) / 1024 / 1024) . " MB\n";
echo "Unique classes: " . count($result) . "\n";
```

**Run script output after added 1 by 1 property:**

```sh
$ php -d memory_limit=256M src/Command/test_memory_bug.php 
Memory limit: 256M
Starting memory: 2 MB
Final memory: 4 MB
Peak memory: 60.00390625 MB
Unique classes: 3

$ php -d memory_limit=256M src/Command/test_memory_bug.php 
Memory limit: 256M
Starting memory: 2 MB
Final memory: 4 MB
Peak memory: 116.00390625 MB
Unique classes: 3

$ php -d memory_limit=256M src/Command/test_memory_bug.php 
Memory limit: 256M
Starting memory: 2 MB
Final memory: 4 MB
Peak memory: 228.00390625 MB
Unique classes: 3

$ php -d memory_limit=256M src/Command/test_memory_bug.php 
Memory limit: 256M
Starting memory: 2 MB
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 134217736 bytes) in /json-streamer-test/src/Command/test_memory_bug.php on line 67
```

**Compare Buggy & Fix version script:**

```php
<?php

require 'vendor/autoload.php';

use Symfony\Component\TypeInfo\Type;
use Symfony\Component\TypeInfo\TypeResolver\TypeResolver;
use Symfony\Component\JsonStreamer\Mapping\PropertyMetadataLoader;

class Option {
    public ?int $id = null;
    public ?string $fi = null;
    public ?string $en = null;
}

class OptionWithName {
    public ?int $id = null;
    public ?string $name = null;
}

class TestDto {
    // Each additional ?Option property DOUBLES memory usage
    public ?Option $option1 = null;
    public ?Option $option2 = null;
    public ?Option $option3 = null;
    public ?Option $option4 = null;
    public ?Option $option5 = null;
    public ?Option $option6 = null;
    public ?Option $option7 = null;
    public ?Option $option8 = null;
    public ?Option $option9 = null;
    public ?Option $option10 = null;

    public ?OptionWithName $named1 = null;
    public ?OptionWithName $named2 = null;
    public ?OptionWithName $named3 = null;
    public ?OptionWithName $named4 = null;
    public ?OptionWithName $named5 = null;
    public ?OptionWithName $named6 = null;
    public ?OptionWithName $named7 = null;
    public ?OptionWithName $named8 = null;
    public ?OptionWithName $named9 = null;
    public ?OptionWithName $named10 = null;

    // Uncommented to show memory explosion:
    public ?Option $option11 = null;
    public ?Option $option12 = null;
    public ?Option $option13 = null;
}

$propertyMetadataLoader = new PropertyMetadataLoader(TypeResolver::create());
$type = Type::object(TestDto::class);

// ==================== BUGGY VERSION ====================
// Simulates StreamerDumper::getResourceClassNames() - exact copy of buggy code
function getResourceClassNamesBuggy($type, $loader, array $classNames = [], array $context = []): array {
    $context['original_type'] ??= $type;

    foreach ($type->traverse() as $t) {
        if ($t instanceof \Symfony\Component\TypeInfo\Type\ObjectType) {
            if (in_array($t->getClassName(), $classNames, true)) {
                return $classNames;  // BUG: Returns SAME array
            }

            $classNames[] = $t->getClassName();

            foreach ($loader->load($t->getClassName(), [], $context) as $property) {
                // BUG: Spread operator causes [...$classNames, ...$classNames] = DOUBLE
                $classNames = [...$classNames, ...getResourceClassNamesBuggy($property->getType(), $loader, $classNames, $context)];
            }
        }

        if ($t instanceof \Symfony\Component\TypeInfo\Type\GenericType) {
            foreach ($t->getVariableTypes() as $variableType) {
                $classNames = [...$classNames, ...getResourceClassNamesBuggy($variableType, $loader, $classNames, $context)];
            }
        }
    }

    return array_values(array_unique($classNames));
}

// ==================== FIXED VERSION ====================
// Uses array_merge + array_diff to prevent array doubling
function getResourceClassNamesFixed($type, $loader, array $classNames = [], array $context = []): array {
    $context['original_type'] ??= $type;

    foreach ($type->traverse() as $t) {
        if ($t instanceof \Symfony\Component\TypeInfo\Type\ObjectType) {
            if (in_array($t->getClassName(), $classNames, true)) {
                return $classNames;
            }

            $classNames[] = $t->getClassName();

            foreach ($loader->load($t->getClassName(), [], $context) as $property) {
                // FIXED: Only add NEW classes, prevents doubling
                $recursiveClassNames = getResourceClassNamesFixed($property->getType(), $loader, $classNames, $context);
                $classNames = array_merge($classNames, array_diff($recursiveClassNames, $classNames));
            }
        }

        if ($t instanceof \Symfony\Component\TypeInfo\Type\GenericType) {
            foreach ($t->getVariableTypes() as $variableType) {
                // FIXED: Only add NEW classes, prevents doubling
                $recursiveClassNames = getResourceClassNamesFixed($variableType, $loader, $classNames, $context);
                $classNames = array_merge($classNames, array_diff($recursiveClassNames, $classNames));
            }
        }
    }

    return array_values(array_unique($classNames));
}

echo "Memory limit: " . ini_get('memory_limit') . "\n";
echo "=".str_repeat("=", 50)."\n";

// Test BUGGY version
echo "\n[BUGGY VERSION - Spread Operator]\n";
echo "Starting memory: " . (memory_get_usage(true) / 1024 / 1024) . " MB\n";
$mem1 = memory_get_usage(true);
gc_collect_cycles();

$result1 = getResourceClassNamesBuggy($type, $propertyMetadataLoader);

$mem2 = memory_get_usage(true);
echo "Final memory: " . ($mem2 / 1024 / 1024) . " MB\n";
echo "Peak memory: " . (memory_get_peak_usage(true) / 1024 / 1024) . " MB\n";
echo "Unique classes: " . count($result1) . "\n";

// Reset peak memory for fair comparison
gc_collect_cycles();
$peakBuggy = memory_get_peak_usage(true);

// Test FIXED version
echo "\n[FIXED VERSION - array_merge + array_diff]\n";
echo "Starting memory: " . (memory_get_usage(true) / 1024 / 1024) . " MB\n";

// Reset for fixed test
memory_reset_peak_usage();
$result2 = getResourceClassNamesFixed($type, $propertyMetadataLoader);

echo "Final memory: " . (memory_get_usage(true) / 1024 / 1024) . " MB\n";
echo "Peak memory: " . (memory_get_peak_usage(true) / 1024 / 1024) . " MB\n";
echo "Unique classes: " . count($result2) . "\n";

echo "\n=".str_repeat("=", 50)."\n";
echo "COMPARISON:\n";
echo "Buggy peak:  " . ($peakBuggy / 1024 / 1024) . " MB\n";
echo "Fixed peak:  " . (memory_get_peak_usage(true) / 1024 / 1024) . " MB\n";
echo "Classes match: " . ($result1 === $result2 ? "YES ✓" : "NO ✗") . "\n";
```

### Possible Solution

Replace the spread operators with `array_merge()` + `array_diff()` to only add new classes:

```php
<?php
// BEFORE (buggy - lines 93 and 99)
$classNames = [...$classNames, ...$this->getResourceClassNames($property->getType(), $classNames)];

// AFTER (fixed)
$recursiveClassNames = $this->getResourceClassNames($property->getType(), $classNames, $context);
$classNames = array_merge($classNames, array_diff($recursiveClassNames, $classNames));
```

**Why this works:**

- `array_diff($recursiveClassNames, $classNames)` returns only NEW classes
- When recursion returns early (already-seen class), diff returns empty array
- No doubling, memory stays O(n) instead of O(2^n)

### Additional Context

- This is a different issue from #62952 / PR #63000 (which fixed runtime memory leak by caching `require $path`). That fix is in 7.3.5+, but this spread operator bug persists.
- Real-world DTOs (API responses with 20+ Option-type properties) fail to generate cache.
- Workaround: Increase `memory_limit` to 1G+ during cache warmup, or reduce nullable object properties.

**Environment:**

PHP 8.3 / 8.4
Symfony 7.3.x / 7.4.x / 8.0.x
symfony/json-streamer (all versions)

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63057
| License       | MIT

The spread operator caused array doubling when recursive calls returned early with the same array for already-seen classes. This was leading to `O(2^n)` memory usage with repeated nullable object properties.

### CODE REVIEW

File: src/Symfony/Component/JsonStreamer/StreamerDumper.php [hunk 1]
```diff
@@ -90,13 +90,15 @@ private function getResourceClassNames(Type $type, array $classNames = [], array
                 $classNames[] = $t->getClassName();
 
                 foreach ($this->propertyMetadataLoader->load($t->getClassName(), [], $context) as $property) {
-                    $classNames = [...$classNames, ...$this->getResourceClassNames($property->getType(), $classNames)];
+                    $recursiveClassNames = $this->getResourceClassNames($property->getType(), $classNames, $context);
+                    $classNames = array_merge($classNames, array_diff($recursiveClassNames, $classNames));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonStreamer/StreamerDumper.php]: can't we have class names as keys? that'd be way more efficient
also, the array_unique wouldn't be needed below anymore, isn't it?

Comment (mtarld) [reply src/Symfony/Component/JsonStreamer/StreamerDumper.php]: Indeed, that'll be much more efficient that way :slightly_smiling_face:

File: src/Symfony/Component/JsonStreamer/StreamerDumper.php [hunk 2]
```diff
@@ -70,37 +70,37 @@ function (ConfigCacheInterface $cache) use ($generateContent, $type) {
...
      */
     private function getResourceClassNames(Type $type, array $classNames = [], array $context = []): array
     {
         $context['original_type'] ??= $type;
 
         foreach ($type->traverse() as $t) {
             if ($t instanceof ObjectType) {
-                if (\in_array($t->getClassName(), $classNames, true)) {
-                    return $classNames;
+                if (isset($classNames[$t->getClassName()])) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonStreamer/StreamerDumper.php]:
```suggestion
                if (isset($classNames[$c = $t->getClassName()])) {
```

File: src/Symfony/Component/JsonStreamer/StreamerDumper.php [hunk 3]
```diff
@@ -70,37 +70,37 @@ function (ConfigCacheInterface $cache) use ($generateContent, $type) {
...
+                    continue;
                 }
 
-                $classNames[] = $t->getClassName();
+                $classNames[$t->getClassName()] = true;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonStreamer/StreamerDumper.php]:
```suggestion
                $classNames[$c] = $c;
```

File: src/Symfony/Component/JsonStreamer/StreamerDumper.php [hunk 4]
```diff
@@ -70,37 +70,37 @@ function (ConfigCacheInterface $cache) use ($generateContent, $type) {
     }
 
     /**
-     * Retrieves resources class names required for caching based on the provided type.
+     * Retrieves resource class names (as keys) required for caching based on the provided type.
      *
-     * @param list<class-string>   $classNames
-     * @param array<string, mixed> $context
+     * @param array<class-string, true> $classNames
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonStreamer/StreamerDumper.php]:
```suggestion
     * @param array<class-string, class-string> $classNames
```

File: src/Symfony/Component/JsonStreamer/StreamerDumper.php [hunk 5]
```diff
@@ -70,37 +70,37 @@ function (ConfigCacheInterface $cache) use ($generateContent, $type) {
...
+     * @param array<string, mixed>      $context
      *
-     * @return list<class-string>
+     * @return array<class-string, true>
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonStreamer/StreamerDumper.php]:
```suggestion
     * @return array<class-string, class-string>
```

File: src/Symfony/Component/JsonStreamer/StreamerDumper.php [hunk 6]
```diff
@@ -70,37 +70,37 @@ function (ConfigCacheInterface $cache) use ($generateContent, $type) {
     }
 
     /**
-     * Retrieves resources class names required for caching based on the provided type.
+     * Retrieves resource class names (as keys) required for caching based on the provided type.
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonStreamer/StreamerDumper.php]:
```suggestion
     * Retrieves resource class names required for caching based on the provided type.
```

File: src/Symfony/Component/JsonStreamer/StreamerDumper.php [hunk 7]
```diff
@@ -47,7 +47,7 @@ public function dump(Type $type, string $path, callable $generateContent): void
             $this->cacheFactory->cache(
                 $path,
                 function (ConfigCacheInterface $cache) use ($generateContent, $type) {
-                    $resourceClasses = $this->getResourceClassNames($type);
+                    $resourceClasses = array_keys($this->getResourceClassNames($type));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonStreamer/StreamerDumper.php]:
```suggestion
                    $resourceClasses = $this->getResourceClassNames($type);
```

**Review by nicolas-grekas — APPROVED** [review]
one more uoptim

**Comment by nicolas-grekas** [comment]
Thank you @mtarld.
