### PR TITLE
[BrowserKit] Allowing body content from GET with a content-type

### LINKED ISSUE #37609: [BrowserKit] HttpBrowser ignores GET-request body
**Symfony version(s) affected**: >=4.3

**Description**  
When using the BrowserKit to do functional tests, I've been trying to use the [HttpBrowser](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/BrowserKit/HttpBrowser.php#L64) to perform requests. Our API uses the request body to send data as JSON. The [KernelBrowser](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/KernelBrowser.php#L142) doesn't seem to mind this and passes on the request to the kernel without modification. However, the HttpBrowser 'extracts' the body and does an early-return when the method is GET. This doesn't seem to comply with [the RFC](https://tools.ietf.org/html/rfc7230#section-3.3). And makes the use for [HttpBrowser](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/BrowserKit/HttpBrowser.php#L64) not possible for us. 

**How to reproduce**  
This is where it's filtered out: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/BrowserKit/HttpBrowser.php#L64

**Possible Solution**  
Remove `GET` from the `in_array` check to allow bodies for GET-requests.

If that's agreed upon I'd gladly make a PR.

### PR DESCRIPTION
**Pull request by thiagomp**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #37609 
| License       | MIT
| Doc PR        | N/A

This allows a GET request to sent a payload if it specifies a content-type in the HTTP header as per our conversation in the ticket.

### CODE REVIEW

**Comment by thiagomp** [comment]
I tried to make sense of Appveyor details but couldn't determine why it failed.
Would anyone be kind enough to let me know the issue so I can fix it?

File: src/Symfony/Component/BrowserKit/HttpBrowser.php [hunk 1]
```diff
@@ -61,7 +61,7 @@ protected function doRequest($request): Response
      */
     private function getBodyAndExtraHeaders(Request $request, array $headers): array
     {
-        if (\in_array($request->getMethod(), ['GET', 'HEAD'])) {
+        if (('GET' == $request->getMethod() && !isset($headers['content-type'])) || 'HEAD' == $request->getMethod()) {
```
Comment (stloyd) [inline src/Symfony/Component/BrowserKit/HttpBrowser.php]:
```suggestion
        if (('GET' === $request->getMethod() && !isset($headers['content-type'])) || 'HEAD' === $request->getMethod()) {
```

**Review by nicolas-grekas — APPROVED** [review]
I don't know what others think, but this would be fine as a bugfix on 4.4 to me.
(appveyor failure unrelated)

**Comment by Nyholm** [comment]
Im happy with this PR after @stloyd's change.

**Comment by fabpot** [comment]
@nicolas-grekas  That's for 5.x :)

**Comment by thiagomp** [comment]
Thanks @stloyd for your suggestion! I've committed the changes you've suggested.

File: src/Symfony/Component/BrowserKit/HttpBrowser.php [hunk 2]
```diff
@@ -61,7 +61,7 @@ protected function doRequest($request): Response
      */
     private function getBodyAndExtraHeaders(Request $request, array $headers): array
     {
-        if (\in_array($request->getMethod(), ['GET', 'HEAD'])) {
+        if (('GET' === $request->getMethod() && !isset($headers['content-type'])) || 'HEAD' === $request->getMethod()) {
```
Comment (jderusse) [inline src/Symfony/Component/BrowserKit/HttpBrowser.php]: why only the `GET` method?
Head is about receiving headers in response, not the request.

IMHO, everything I can do with GET should be possible with HEAD (except reading response body)

Comment (thiagomp) [reply src/Symfony/Component/BrowserKit/HttpBrowser.php]: You made me think! So I took a look at the [RFC7231 - 4.3.2](https://tools.ietf.org/html/rfc7231#section-4.3.2) and I believe it fits to what you've said @jderusse .
At the end, a HEAD request only instructs the server to not send a message body in response.
I'll think on a change + tests and come back here with it.

Comment (Nyholm) [reply src/Symfony/Component/BrowserKit/HttpBrowser.php]: Awesome. 
I'll be happy to merge when this is resolved.

Comment (thiagomp) [reply src/Symfony/Component/BrowserKit/HttpBrowser.php]: Code updated and another test added to cover for that

**Comment by thiagomp** [comment]
Please, let me know if this is failing because of my changes. From what I saw, I don't think it was.

**Comment by nicolas-grekas** [comment]
Thank you @thiagomp.
