### PR TITLE
BicValidator add strict mode to validate bics in strict mode

### LINKED ISSUE #54822: BicValidator/IbanValidator value normalization
### Symfony version(s) affected

6.4.2

### Description

We use BicValidator and IbanValidator for validating IBAN/SWIFT and some times people enter everything in lower case and validation fails. because `fr != FR`

### How to reproduce

Just enter everything in lower-case

### Possible Solution

Normalize value with `strtoupper`

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by maxbeckers**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #54822
| License       | MIT

Add a strict mode for bic validation (default strict, behavior before the pr is strict). But it is possible to set strict to `false` to allow lowercase input.

I'll add it to the docs when this PR is merged.

### CODE REVIEW

**Comment by xabbuh** [comment]
What about adding a `normalizer` option like in e.g. the `Email` or `Ip` constraints?

File: src/Symfony/Component/Validator/Constraints/BicValidator.php [hunk 1]
```diff
@@ -109,8 +112,8 @@ public function validate(mixed $value, Constraint $constraint): void
             return;
         }
 
-        // should contain uppercase characters only
-        if (strtoupper($canonicalize) !== $canonicalize) {
+        // should contain uppercase characters only in strict mode
+        if (Bic::VALIDATION_MODE_STRICT === $constraint->mode && strtoupper($canonicalize) !== $canonicalize) {
```
Comment (maxbeckers) [inline src/Symfony/Component/Validator/Constraints/BicValidator.php:116]: @xabbuh I changed it now to mode, the way that was also done in the email validator, because i need id here for the check. With the normalizer way i wouldn't know to check this or not.

**Comment by fabpot** [comment]
Another way would be to always uppercase the value, right?

**Comment by maxbeckers** [comment]
@fabpot exactly. But this could break other applications when the application trusts,that the input is always validated to be upper case. Or do you mean to always manipulate the input to go ahead with upper case? I would not recommend to change/manipulate the input in a validator at least without having a solution to change the behavior as a developer.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @maxbeckers.
