### PR TITLE
[Scheduler] Fix array to string conversion in `#[AsCronTask]` arguments

### LINKED ISSUE #62986: [Scheduler] Array to string conversion when using AsCronTask with array args
### Symfony version(s) affected

\>7.4.0

### Description

Passing an array to the `arguments` parameter of `AsCronTask` is not supported. It gives a warning when setting up the dependency injection.

### How to reproduce

```php
#[AsCommand('my_command')]
#[AsCronTask(expression: '* * * * *', arguments: ['arg1', 'arg2'])]
final class MyCommand extends Command
```

```
❯ bin/console -vvv

In AddScheduleMessengerPass.php line 68:
                                       
  [ErrorException]                     
  Warning: Array to string conversion  
                                       

Exception trace:
  at /Users/jworman/PhpstormProjects/gtx/vendor/symfony/scheduler/DependencyInjection/AddScheduleMessengerPass.php:68
 Symfony\Component\Scheduler\DependencyInjection\AddScheduleMessengerPass->process() at /Users/jworman/PhpstormProjects/gtx/vendor/symfony/dependency-injection/Compiler/Compiler.php:73
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /Users/jworman/PhpstormProjects/gtx/vendor/symfony/dependency-injection/ContainerBuilder.php:820
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /Users/jworman/PhpstormProjects/gtx/vendor/symfony/http-kernel/Kernel.php:516
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /Users/jworman/PhpstormProjects/gtx/vendor/symfony/http-kernel/Kernel.php:762
 Symfony\Component\HttpKernel\Kernel->preBoot() at /Users/jworman/PhpstormProjects/gtx/vendor/symfony/http-kernel/Kernel.php:122
 Symfony\Component\HttpKernel\Kernel->boot() at /Users/jworman/PhpstormProjects/gtx/app/Kernel.php:35
 App\Kernel->boot() at /Users/jworman/PhpstormProjects/gtx/vendor/symfony/framework-bundle/Console/Application.php:195
 Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at /Users/jworman/PhpstormProjects/gtx/vendor/symfony/framework-bundle/Console/Application.php:69
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/jworman/PhpstormProjects/gtx/vendor/symfony/console/Application.php:195
 Symfony\Component\Console\Application->run() at /Users/jworman/PhpstormProjects/gtx/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /Users/jworman/PhpstormProjects/gtx/vendor/autoload_runtime.php:33
 require_once() at /Users/jworman/PhpstormProjects/gtx/bin/console:15
```

### Possible Solution

Detect when `arguments` is an array and handle it with: `implode(' ', array_map(escapeshellarg(...), $arguments))`

### Additional Context

The current workaround I am using is:
```php
#[AsCommand('my_command')]
#[AsCronTask(expression: '* * * * *', arguments: 'arg1 arg2')]
final class MyCommand extends Command
```

### PR DESCRIPTION
**Pull request by serhiilabs**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62986
| License       | MIT

The `AsCronTask` attribute accepts `array|string|null` for the `arguments` parameter, but passing an array throws "Array to string conversion" because the compiler pass interpolates it directly into a string.

```php
#[AsCronTask('* * * * *', arguments: ['arg1', 'arg2'])]
final class MyCommand extends Command { ... }
```

```
Warning: Array to string conversion in AddScheduleMessengerPass.php
```

The fix converts array arguments to a properly escaped string using the same logic as `Input::escapeToken()`.

```php
#[AsCronTask('* * * * *', arguments: ['arg1', 'arg2'])]
// my:command arg1 arg2

#[AsCronTask('* * * * *', arguments: ['hello world', 'foo'])]
// my:command 'hello world' foo
```

### CODE REVIEW

File: src/Symfony/Component/Scheduler/Tests/DependencyInjection/AddScheduleMessengerPassTest.php [hunk 1]
```diff
@@ -9,7 +9,7 @@
  * file that was distributed with this source code.
  */
 
-namespace Symfony\Component\Console\Tests\DependencyInjection;
+namespace Symfony\Component\Scheduler\Tests\DependencyInjection;
```
Comment (OskarStark) [inline src/Symfony/Component/Scheduler/Tests/DependencyInjection/AddScheduleMessengerPassTest.php:12]: nice catch

File: src/Symfony/Component/Scheduler/DependencyInjection/AddScheduleMessengerPass.php [hunk 2]
```diff
@@ -60,7 +60,14 @@ public function process(ContainerBuilder $container): void
...
                     $commandName = $attribute?->name ?? $serviceDefinition->getClass()::getDefaultName();
 
-                    $message = new Definition(RunCommandMessage::class, [$commandName.(($tagAttributes['arguments'] ?? null) ? " {$tagAttributes['arguments']}" : '')]);
+                    $arguments = $tagAttributes['arguments'] ?? null;
+                    if (\is_array($arguments)) {
+                        $arguments = implode(' ', array_map(
+                            static fn ($token) => preg_match('{^[\w-]+$}', $token = (string) $token) ? $token : escapeshellarg($token),
+                            $arguments
+                        ));
+                    }
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Scheduler/DependencyInjection/AddScheduleMessengerPass.php]:
```
                    if (\is_array($arguments = $tagAttributes['arguments'] ?? null)) {
                        $arguments = implode(' ', array_map(static fn (string $token) => preg_match('{^[\w-]+$}', $token) ? $token : escapeshellarg($token), $arguments));
                    }
```

Comment (serhiilabs) [reply src/Symfony/Component/Scheduler/DependencyInjection/AddScheduleMessengerPass.php]: Done, thanks!

File: src/Symfony/Component/Scheduler/DependencyInjection/AddScheduleMessengerPass.php [hunk 3]
```diff
@@ -60,7 +60,10 @@ public function process(ContainerBuilder $container): void
                     $attribute = ($container->getReflectionClass($serviceDefinition->getClass())->getAttributes(AsCommand::class)[0] ?? null)?->newInstance();
                     $commandName = $attribute?->name ?? $serviceDefinition->getClass()::getDefaultName();
 
-                    $message = new Definition(RunCommandMessage::class, [$commandName.(($tagAttributes['arguments'] ?? null) ? " {$tagAttributes['arguments']}" : '')]);
+                    if (\is_array($arguments = $tagAttributes['arguments'] ?? null)) {
+                        $arguments = implode(' ', array_map(static fn (string $token) => preg_match('{^[\w-]+$}', $token) ? $token : escapeshellarg($token), $arguments));
+                    }
+                    $message = new Definition(RunCommandMessage::class, [$commandName.($arguments ? " $arguments" : '')]);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Scheduler/DependencyInjection/AddScheduleMessengerPass.php]:
```suggestion
                    $message = new Definition(RunCommandMessage::class, [$commandName.('' !== $arguments ? " $arguments" : '')]);
```

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @serhiilabs.
