### PR TITLE
[Cache] Fixed incorrect usage of UNLINK with PHPRedis with Redis < 4.0

### LINKED ISSUE #39280: RedisCache delete/clear not working anymore
**Symfony version(s) affected**: 5.2.0

**Description**  
Since updating to Symfony 5.2.0 the redis cache delete command seems to be not working anymore.
Also the command `bin/console cache:pool:clear [pool]` is not working for RedisCache-pools.

**How to reproduce**  
Redis Version 3.2.12
```php
namespace App\Cache;

use Symfony\Component\Cache\Adapter\AdapterInterface;

class TestCache
{
    /**
     * @var AdapterInterface
     */
    private $cache;
    
    public function __construct(AdapterInterface $adapter)
    {
        $this->cache = $adapter;
    }
    
    public function testCache():void
    {
        try {
            $cacheItem = $this->cache->getItem('testKey');
            $cacheItem->set(['testData']);
            $this->cache->save($cacheItem);
                
            dump($this->cache->hasItem('testKey')); // true

            $this->cache->deleteItem('testKey');

            dump($this->cache->hasItem('testKey')); // true
        } catch (\Psr\Cache\InvalidArgumentException $e) {
        }
   }
}
```

**Additional context**  
We found that there was the following change:
https://github.com/symfony/cache/commit/2cb6631f397ecbc16175e28f91710c598afa9d50

Because of CentOS 7 we are fixed to Redis Version 3.2.12-2.el7. The UNLINK Command is not available in this redis version and the following if-statement seems not to match.

### PR DESCRIPTION
**Pull request by colinpieper**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39280
| License       | MIT

Currently, deleting cache keys is broken for users using PhpRedis with Redis-server < 4.0.0. The current implementation expects PhpRedis to throw an exception if the 'unlink'-function is used but unavailable, after which it's supposed to switch to using the 'del'-function. Using the 'unlink'-function on lower Redis-server versions seems to not throw an exception, but instead it appears to silently fail.

This pull request changes this behavior and checks the Redis-server version instead. If the version is 4.0 or higher, it uses the unlink function. If not, it uses the del-function.

Also see https://redis.io/commands/unlink > "Available since 4.0.0".

(Footnote: this is one of my first times contributing to an open-source project and my first time contributing to Symfony. I've tried following the guidelines, but please let me know if I missed anything. I'm unsure how I would go about unit testing this specific bugfix due to it being dependent on the Redis version, so I omitted it. Please let me know if a unit test is indeed required for this and if so, let me know if you have any suggestions on how to go about that.)

### CODE REVIEW

File: src/Symfony/Component/Cache/Traits/RedisTrait.php [hunk 1]
```diff
@@ -404,19 +404,13 @@ protected function doDelete(array $ids)
                 }
             })->rewind();
         } else {
-            static $unlink = true;
+            $info = $this->redis->info('Server');
+            $info = $info['Server'] ?? $info;
```
Comment (derrabus) [inline src/Symfony/Component/Cache/Traits/RedisTrait.php]: Can we cache this so we won't execute that code on every delete operation?

**Comment by derrabus** [comment]
Thank you very much for working on this issue. Because the 5.2 branch is affected by this bug, please base your PR on the 5.2 branch.

**Review by jderusse — COMMENTED** [review]
From the Redis documentation this is available since Redis 4.0 https://redis.io/commands/unlink

I believe the fix should also be applied to Predis. Right?

Looks like the `Predis\Command\Redis\UNLINK` does not exists. /cc @jonashrem

**Comment by colinpieper** [comment]
Here's the pull request that introduced these changes: https://github.com/symfony/symfony/pull/37993.

The UNLINK command is a pending pull request to Predis (see https://github.com/predis/predis/pull/666) and not yet available, but might be in the future if/when it's approved. There's a check to see if that class exists or it will fall back to the DELETE-command, so there currently aren't any negative side effects in keeping it as far as I can see.

These changes will also need to be applied to the following two files:
- src/Symfony/Component/HttpFoundation/Session/Storage/Handler/RedisSessionHandler.php
- src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php

I'll implement those corrections soon.

**Comment by nicolas-grekas** [comment]
Which version of phpredis are you using?
On my machine, using v5.3.2, I do get an exception.

**Review by nicolas-grekas — CHANGES_REQUESTED** [review]
Looking at @jderusse's comment at https://github.com/symfony/symfony/issues/39280#issuecomment-740082057, we should handle the case where the call returns `false` instead.

**Comment by nicolas-grekas** [comment]
Thank you @wickex.
