### PR TITLE
[AssetMapper] Fix JavaScript compiler load imports from JS strings

### LINKED ISSUE #53608: [AssetMapper] Wrong javascript import detection
### Symfony version(s) affected

6.3

### Description

Asset mapper unexpectedly detects some JavaScript imports. Indeed, let's say we have the following `vanilla.js` JS file:
```js
console.warn("[DEPRECATED] Default export is deprecated. Instead use import { createStore } from 'zustand/vanilla'.");
```
Then it'll end in an infinite loop as the file is requiring itself.

### How to reproduce

Start a fresh project, require `zustand@4.5.0`, then run `bin/console asset-map:compile`, you should end in an infinite loop.

### Possible Solution

Update the `Symfony\Component\AssetMapper\Compiler\JavaScriptImportPathCompiler::IMPORT_PATTERN` so that it detects imports better.

As a quickfix, I updated it like the following (but I'm sure there is a better way):
```diff
- /(?:import\s*(?:(?:\*\s*as\s+\w+|[\w\s{},*]+)\s*from\s*)?|\bimport\()\s*[\'"`](\.\/[^\'"`]+|(\.\.\/)*[^\'"`]+)[\'"`]\s*[;\)]?/m
+ /(?:[^ ]import\s*(?:(?:\*\s*as\s+\w+|[\w\s{},*]+)\s*from\s*)?|\bimport\()\s*[\'"`](\.\/[^\'"`]+|(\.\.\/)*[^\'"`]+)[\'"`]\s*[;\)]?/m
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by smnandre**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #53608 
| License       | MIT

Add a check to ensure the import is not parsed from a JS string (e.g. `console.log(...)` in the issue)

### CODE REVIEW

File: src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php [hunk 1]
```diff
@@ -141,6 +141,16 @@ private function isCommentedOut(mixed $offsetStart, string $fullContent): bool
         return false;
     }
 
+    private function isEnclosedInQuotes(mixed $offsetStart, string $fullContent): bool
+    {
+        $lineStart = strrpos($fullContent, "\n", $offsetStart - \strlen($fullContent));
+        // Remove enclosed strings before the import
+        $lineContentBeforeImport = substr($fullContent, $lineStart, $offsetStart - $lineStart);
+        $lineWithoutStrings = preg_replace('/\'(?:[^\'\\\\]|\\\\.)*\'|"(?:[^"\\\\]|\\\\.)*"/', '', $lineContentBeforeImport);
```
Comment (kaznovac) [inline src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php]: [template literals (`)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) are quite common in modern js, and this syntax allows multiline strings making this check quite a challenge

Comment (smnandre) [reply src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php]: @kaznovac this PR fixes a bug with console log / deprecation / help messages (cf the original issue)

Handling multi-line strings/comments can reveal itself really complex, and probably  would need there some concrete JS parser. 

I must admit i doubt any library would use multi-line template comments in source code containing import instructions.. but if/when that happen we could handle it in a later PR ?

WDYT ?

Comment (nicolas-grekas) [reply src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php]: alternative implementation idea: we merge this regexp with the one that checks for imports.
Since regexp are greedy, this will make the filter in one go, with just a quick check at the start of the closure

Comment (smnandre) [reply src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php]: @nicolas-grekas 

Tried your idea but..  that goes beyond my regexp competences.... :) 

--> https://regex101.com/r/zug2ot/2

In the following case, we need to ignore foo.js import.. but want to extract the bar.js import

```
console.log('import {myFunction} from "foo.js"'); import {myFunction} from "bar.js";
```

Comment (smnandre) [reply src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php]: @nicolas-grekas got it, and it seems to work perfectly ! Thank you :) 

See https://regex101.com/r/qFoeoR/1

Comment (kaznovac) [reply src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php]: @smnandre great work && sorry for the late answer

p.s. please note that this method can now be removed

File: src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php [hunk 2]
```diff
@@ -27,8 +27,8 @@
  */
 final class JavaScriptImportPathCompiler implements AssetCompilerInterface
 {
-    // https://regex101.com/r/fquriB/1
-    private const IMPORT_PATTERN = '/(?:import\s*(?:(?:\*\s*as\s+\w+|[\w\s{},*]+)\s*from\s*)?|\bimport\()\s*[\'"`](\.\/[^\'"`]+|(\.\.\/)*[^\'"`]+)[\'"`]\s*[;\)]?/m';
+    // https://regex101.com/r/qFoeoR/1
+    private const IMPORT_PATTERN = '/(?:\'(?:[^\'\\\\]|\\\\.)*\'|"(?:[^"\\\\]|\\\\.)*")|(?:import\s*(?:(?:\*\s*as\s+\w+|[\w\s{},*]+)\s*from\s*)?|\bimport\()\s*[\'"`](\.\/[^\'"`]+|(\.\.\/)*[^\'"`]+)[\'"`]\s*[;\)]?/m';
```
Comment (weaverryan) [inline src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php:31]: Can you add a test case that the `\\\\` is needed for (which is the `\` escape character inside a string)?

**Review by weaverryan — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @smnandre.
