### PR TITLE
[Lock] Make sure RedisStore will also support Valkey

### LINKED ISSUE #59387: [Lock] Lock::acquire will always return false when using RedisStore
### Symfony version(s) affected

7.2, also tested 7.3.x-dev 9169931

### Description

We're using Valkey 7.2.4 (more less Redis fork) and it works perfectly fine on Sf 6.4.
On 7.2 (tested dev branches and main) we got issue with `Lock->acquire`. It uses under the hood `RedisStore->save` and the `$this->evaluate` (https://github.com/symfony/symfony/blob/7.3/src/Symfony/Component/Lock/Store/RedisStore.php#L86) .

The redis tab output:
Zrzut ekranu z 2025-01-07 09-23-57

### How to reproduce

I believe the difference is between `eval` and `evalSha`, so if you please try to create lock and acquire it using Redis.
We're actually using Valkey (valkey/valkey:8 docker image, https://hub.docker.com/r/valkey/valkey/).

### Possible Solution

_No response_

### Additional Context

Might be similar to https://github.com/symfony/symfony/issues/58660

### PR DESCRIPTION
**Pull request by PatNowak**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #59387
| License       | MIT

As the change happened on Valkey (https://github.com/valkey-io/valkey/pull/617/files#diff-1abc5651133d108c0c420d9411925373c711133e7748d9e4f4c97d5fb543fdd9L1819-R1819), ~it's hard to consider this a bug when `RedisStore` was meant only to support Redis ;)~

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thanks for digging this. Let's merge it as a bugfix still. :+1: for 7.2 on my side.

File: src/Symfony/Component/Lock/Store/RedisStore.php [hunk 1]
```diff
@@ -284,8 +287,18 @@ private function evaluate(string $script, string $resource, array $args): mixed
 
         \assert($this->redis instanceof \Predis\ClientInterface);
 
-        $result = $this->redis->evalSha($scriptSha, 1, $resource, ...$args);
-        if ($result instanceof Error && self::NO_SCRIPT_ERROR_MESSAGE === $result->getMessage()) {
+        try {
+            $result = $this->redis->evalSha($scriptSha, 1, $resource, ...$args);
+        } catch (ServerException $exception) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Lock/Store/RedisStore.php]: I don't think this "catch" makes sense: the predis factory always disables exceptions.
It's true nothing prevents another factory to be used, but this would still remain an unrelated change.

Comment (PatNowak) [reply src/Symfony/Component/Lock/Store/RedisStore.php]: Well, I dumped there to check what's happening and I got exactly `ServerException` for the Valkey. Most likely some other stuff makes `predis` work like that under the hood... I tested it using small repo for that purpose: https://github.com/PatNowak/symfony-valkey-poc

Comment (nicolas-grekas) [reply src/Symfony/Component/Lock/Store/RedisStore.php]: how did you create the connection object?

Comment (PatNowak) [reply src/Symfony/Component/Lock/Store/RedisStore.php]:
```php
// $this->redis is just $redis: '@snc_redis.default' from services.yml
$store = new RedisStore($this->redis);
```

I don't mind to drop this, as we don't use `predis` at all. We rely on the `phpredis` on prod in our real app.

Comment (PatNowak) [reply src/Symfony/Component/Lock/Store/RedisStore.php]: Ok, I made it smaller then. Hope it will work correctly for phpredis and predis :)

File: src/Symfony/Component/Lock/Store/RedisStore.php [hunk 2]
```diff
@@ -29,7 +29,9 @@ class RedisStore implements SharedLockStoreInterface
 {
     use ExpiringStoreTrait;
 
-    private const NO_SCRIPT_ERROR_MESSAGE = 'NOSCRIPT No matching script. Please use EVAL.';
+    // To support also Valkey (redis open-source fork), let's use it only as a prefix
+    // https://github.com/valkey-io/valkey/pull/617/files#diff-1abc5651133d108c0c420d9411925373c711133e7748d9e4f4c97d5fb543fdd9R1819
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Lock/Store/RedisStore.php]: let's remove this comment, I don't think it's needed
```suggestion
```

File: src/Symfony/Component/Lock/Store/RedisStore.php [hunk 3]
```diff
@@ -234,7 +236,7 @@ private function evaluate(string $script, string $resource, array $args): mixed
             $this->redis->clearLastError();
 
             $result = $this->redis->evalSha($scriptSha, array_merge([$resource], $args), 1);
-            if (self::NO_SCRIPT_ERROR_MESSAGE === $err = $this->redis->getLastError()) {
+            if ($this->redis->getLastError() !== null && str_starts_with($this->redis->getLastError(), self::NO_SCRIPT_ERROR_MESSAGE)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Lock/Store/RedisStore.php]: same below:
```suggestion
            if (null !== ($err = $this->redis->getLastError()) && str_starts_with($err, self::NO_SCRIPT_ERROR_MESSAGE)) {
```

**Review by nicolas-grekas — COMMENTED** [review]
> // $this->redis is just $redis: '@snc_redis.default' from services.yml

OK, so you'd need to fix your connection service in "no exceptions" mode to be compatible with the implementation.

The patch LGTM now, just minor things.

File: src/Symfony/Component/Lock/Store/RedisStore.php (hunk 3 above)
Comment (PatNowak) [reply src/Symfony/Component/Lock/Store/RedisStore.php]: Thanks, done

File: src/Symfony/Component/Lock/Store/RedisStore.php [hunk 4]
```diff
@@ -29,7 +29,7 @@ class RedisStore implements SharedLockStoreInterface
 {
     use ExpiringStoreTrait;
 
-    private const NO_SCRIPT_ERROR_MESSAGE = 'NOSCRIPT No matching script. Please use EVAL.';
+    private const NO_SCRIPT_ERROR_MESSAGE = 'NOSCRIPT No matching script.';
```
Comment (xabbuh) [inline src/Symfony/Component/Lock/Store/RedisStore.php]: Maybe rename the constant to `NO_SCRIPT_ERROR_MESSAGE_PREFIX` now?

Comment (PatNowak) [reply src/Symfony/Component/Lock/Store/RedisStore.php]: Perfect suggestion :+1:

**Review by fabpot — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @PatNowak.

**Comment by stof** [comment]
If we want to be reliable regarding changes to the wording of error messages, shouldn't we use only `NOSCRIPT ` as prefix in the check, i.e. checking only [the error type](https://redis.io/docs/latest/develop/reference/protocol-spec/#simple-errors) ?

**Comment by johanwilfer** [comment]
Yeah, we should check the prefix to be `NOSCRIPT ` instead probably. See here: https://github.com/valkey-io/valkey/issues/1537#issuecomment-2582916365

And they link to the documentation saying only the first word should be matched if possible. So while this fixes the issue with Valkey it can probably be a bit more robust.

File: src/Symfony/Component/Lock/Store/RedisStore.php (hunk 1 above)
Comment (simPod) [reply src/Symfony/Component/Lock/Store/RedisStore.php]: @nicolas-grekas snc_redis bundle by default throws exceptions

https://github.com/snc/SncRedisBundle/blob/1577b80bda8b488c45ebe14fdb72e42273c3aa8b/src/DependencyInjection/Configuration/Configuration.php#L131C52-L131C64

Comment (simPod) [reply src/Symfony/Component/Lock/Store/RedisStore.php]: The evalSha call here

https://github.com/symfony/symfony/blob/5876c48757182da02cbea275a40059b5bfc83854/src/Symfony/Component/Lock/Store/RedisStore.php#L287

throws ServerError to snc redis users with default config.

I had to add option settings:

```yaml
snc_redis:
  clients:
    locks:
      type: predis
      alias: locks
      dsn: '%redis.dsn%/0'
      logging: '%kernel.debug%'
      options:
        throw_errors: false
```
