### PR TITLE
[DoctrineBridge] Respect `schema_filter` in schema listeners

### LINKED ISSUE #38398: dbal.schema_filter is ignored for specific table 'messenger_messages'
**Symfony version(s) affected**: 5.1.x

**Description**  

Since symfony 5.1 the table `messenger_messages `is no longer exclude by the `schema_filter`'s setting : 
`schema_filter: ~^(?!messenger_messages)~` <= is ignored

Since symfony 5.1 i got:
php bin/console doctrine:schema:update --dump-sql
ALTER TABLE messenger_messages CHANGE body body LONGTEXT NOT NULL;

**How to reproduce**  
Modify manually the table messenger_messages : `ALTER TABLE messenger_messages CHANGE body body LONGBLOB NOT NULL;`
Add `~^(?!messenger_messages)~` in `doctrine.dbal.schema_filter` config 
Execute : `php bin/console doctrine:schema:update --dump-sql`
Output: `ALTER TABLE messenger_messages CHANGE body body LONGTEXT NOT NULL;`
Should have empty output because of the rule `schema_filter `wich exclude `messenger_messages `table

**Possible Solution**  

**Additional context**  

`MessengerTransportDoctrineSchemaSubscriber.onSchemaCreateTable` inject SQL code for table `messenger_messages` on the event `ToolEvents::postGenerateSchema`

I created an issue on DoctrineBundle github but seems like its a symfony problem : [https://github.com/doctrine/DoctrineBundle/issues/1225](https://github.com/doctrine/DoctrineBundle/issues/1225)

### PR DESCRIPTION
**Pull request by wazum**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #38398
| License       | MIT

All 5 schema listeners in `DoctrineBridge` unconditionally add tables (and sequences) to the schema during `postGenerateSchema`, bypassing `doctrine.dbal.schema_filter`. This causes `doctrine:schema:update --dump-sql` to always include these tables in its diff, even when the user explicitly excludes them via `schema_filter`.

This PR adds a `filterSchemaChanges()` helper to `AbstractSchemaListener` that:

1. Snapshots table and sequence names before the `configureSchema()` call
2. Executes the configurator
3. Checks newly added tables and sequences against the configured `schemaAssetsFilter`
4. Removes those that the filter excludes

All 5 listeners are updated to use this helper:
- `MessengerTransportDoctrineSchemaListener`
- `DoctrineDbalCacheAdapterSchemaListener`
- `LockStoreSchemaListener`
- `PdoSessionHandlerSchemaListener`
- `RememberMeTokenProviderDoctrineSchemaListener`

### CODE REVIEW

File: src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php [hunk 1]
```diff
@@ -21,6 +23,35 @@ abstract class AbstractSchemaListener
...
+    {
+        $filter = $connection->getConfiguration()->getSchemaAssetsFilter();
+
+        if (null === $filter) {
+            $configurator();
+
+            return;
+        }
+
+        $getTableNames = static fn (Schema $schema): array => array_map(static fn (Table $table) => $table->getName(), $schema->getTables());
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php]: we might reuse the closure more by dropping the types, WDYT?
```suggestion
        $getNames = static fn ($array) => array_map(static fn ($object) => $object->getName(), $array);
```

Comment (wazum) [reply src/Symfony/Bridge/Doctrine/SchemaListener/AbstractSchemaListener.php]: Nice catch, makes sense — applied.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @wazum.
