### PR TITLE
[DependencyInjection] Add message to install symfony/config for additional debugging information

### LINKED ISSUE #48905: [Dependency Injection] AutowirePass depends on symfony/config
### Symfony version(s) affected

6.2.2

### Description

This line of code in AutowirePass

https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L14

makes so that in case a service cannot be determine in autowiring, a fatal error is thrown for missing class.

True it's a fatal anyway, but if symfony/config is installed, the error description is much more accurate.

See https://www.drupal.org/project/drupal/issues/3331324.

### How to reproduce

See https://www.drupal.org/project/drupal/issues/3331324

### Possible Solution

Make symfony/config a dependency in composer.json?

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no 
| Tickets       | Fix https://github.com/symfony/symfony/issues/48905
| License       | MIT
| Doc PR        | _NA_

As stated in the ticket, `symfony/config` is a dev dependency for DI component. This PR aims to improve a bit the DX when an error occurred during autowiring and when `ClassExistenceResource` is not available.

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 1]
```diff
@@ -540,15 +540,19 @@ private function createTypeNotFoundMessage(TypedReference $reference, string $la
...
-                // isFresh() will explode ONLY if a parent class/trait does not exist
-                $resource->isFresh(0);
-                $parentMsg = false;
+                if (class_exists(ClassExistenceResource::class)) {
+                    $resource = new ClassExistenceResource($type, false);
+                    // isFresh() will explode ONLY if a parent class/trait does not exist
+                    $resource->isFresh(0);
+                    $parentMsg = false;
+                } else {
+                    $parentMsg = "couldn't be loaded, installing symfony/config package could help with additional details";
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: `couldn't be loaded. Either it was not found or it is missing a parent class or a trait.`?

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php [hunk 2]
```diff
@@ -504,6 +511,30 @@ public function testParentClassNotFoundThrowsException()
...
+        $aDefinition->setAutowired(true);
+
+        $container->register(Dunglas::class, Dunglas::class);
+
+        $pass = new AutowirePass();
+        try {
+            $pass->process($container);
+            $this->fail('AutowirePass should have thrown an exception');
+        } catch (AutowiringFailedException $e) {
+            $this->assertMatchesRegularExpression('{^Cannot autowire service "a": argument "\$r" of method "(Symfony\\\\Component\\\\DependencyInjection\\\\Tests\\\\Compiler\\\\)BadParentTypeHintedArgument::__construct\(\)" has type "\1OptionalServiceClass" but this class couldn\'t be loaded, installing symfony/config package could help with additional details}', $e->getMessage());
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php]: No need for a regexp here, isn't it?

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php (hunk 1 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: I like this, updated!

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php (hunk 2 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php]: That's right!

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @alexandre-daubois.

**Comment by mondrake** [comment]
can this be backported to 6.2?
