### PR TITLE
[PropertyInfo] strip only leading `\` when unknown docType

### LINKED ISSUE #44455: [PropertyInfo] Incorrect handling of pseudo-types
### Symfony version(s) affected

4.x, 5.x, 6.0

### Description

Since static-analysis tools like PHPStan or Psalm became more popular, it is not uncommon to see usage of pseudo-type like:
```php
/** @var non-empty-string */
public $foo;
```
Some pseudo-types are currently supported (see #43916 introducing `list` type) but others are not. We can add support for popular custom types used by PHPStan or phpDocumentor (see #44451) but there will always be less common pseudo-types which we are not aware of. 

Handling of these cases is inconsistent between extractors and `PhpDocExtractor` has a bug where the first character of the pseudo-type is trimmed. That one bug is quite easy to fix, but I believe handling of custom, unknown types is overall broken and we should decide how we want to handle them.

### How to reproduce

Tested on `v6.0.0` tag:

```php
class TestClass {
    /** @var non-empty-string */
    public $foo;

    /** @var some-other-custom-type */
    public $bar;
}

$extractor = new \Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor();
$fooType = $extractor->getTypes(TestClass::class, 'foo'); // $builtinType: object, $class: on-empty-string (first character trimmed)
$barType = $extractor->getTypes(TestClass::class, 'bar'); // NULL

$extractor = new \Symfony\Component\PropertyInfo\Extractor\PhpStanExtractor();
$fooType = $extractor->getTypes(TestClass::class, 'foo'); // $builtinType: object, $class: \non-empty-string (backslash prepended)
$barType = $extractor->getTypes(TestClass::class, 'bar'); // $builtinType: object, $class: \some-other-custom-type
```

## Expected result
* pseudo-types shouldn't be automatically treated as objects
* if the type cannot be correctly mapped to built-in type, `getType()` should return `null` or throw an exception
* **or** the developer should be informed it is a pseudo-type and decide what to do with doctype
* the doctype shouldn't be modified and returned as-is (i.e. `some-other-custom-type` and not `\some-other-custom-type`)
* it would be perfect if the results were consistent between both extractors

### Additional Context

The first character is trimmed due to bug in [`\Symfony\Component\PropertyInfo\Util\PhpDocTypeHelper`](https://github.com/symfony/symfony/blob/aa4e97099b5a67bdc9f2387fe8d099f5c712f81c/src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php#L190). I believe there's assumption that the `$docType` is FQCN with backslash prefix but in case of `/** @var non-empty-string */` it is passed as-is to the function.

```php
// src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php

  // $docType: non-empty-string

    private function getPhpTypeAndClass(string $docType): array
    {
        // ...

        return ['object', substr($docType, 1)]; // substr to strip the namespace's `\`-prefix
    }
```

### PR DESCRIPTION
**Pull request by EmilMassey**
| Q             | A
| ------------- | ---
| Branch?       | 4.4, 5.4, 6.0
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44455 (partially)
| License       | MIT
| Doc PR        | -

Fixes issue in `PhpDocExtractor` when dealing with some pseudo-types (`non-empty-string`, `positive-int`, etc.):
```php
class TestClass {
    /** @var non-empty-string */
    public $foo;

    /** @var positive-int */
    public $bar;
}

$extractor = new \Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor();
$fooType = $extractor->getTypes(TestClass::class, 'foo'); // $builtinType: object, $class: on-empty-string (first character trimmed)
$barType = $extractor->getTypes(TestClass::class, 'bar'); // $builtinType: object, $class: ositive-int (first character trimmed)
```

The bug exists in 4.4, 5.4 and 6.0. It may exist in 6.1 as the invalid line is still there, but due to changes made in #44451, above snippet will no longer produce the bug. I was not able to reproduce the error in 6.1, but I suspect there may exist some pseudo-type that is still affected by the bug.

I'm not sure if the test I wrote is OK, but it is the only way I could think of to validate my fix. In my opinion (see #44455), unknown pseudo-type should not be mapped to an object, so after the fix handling of pseudo-types is still broken but at least the results are consistent between `PhpStanExtractor` and `PhpDocExtractor`. But I agree with @derrabus (https://github.com/symfony/symfony/issues/44455#issuecomment-1065195055) that until there is no way to detect if we are dealing with a pseudo-type, assuming it is a reference to an object is the sanest thing to do.

### CODE REVIEW

File: src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php [hunk 1]
```diff
@@ -164,6 +164,6 @@ private function getPhpTypeAndClass(string $docType): array
             return ['object', $docType];
         }
 
-        return ['object', substr($docType, 1)];
+        return ['object', ltrim($docType, '\\')]; // strip the namespace's `\`-prefix
```
Comment (DannyMeyer) [inline src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php]: With this "fix" pseudo types will be considered as an object. That's wrong.
```php
object(Symfony\Component\PropertyInfo\Type)#15949 (6) {
  ["builtinType":"Symfony\Component\PropertyInfo\Type":private]=>
  string(6) "object"
  ["nullable":"Symfony\Component\PropertyInfo\Type":private]=>
  bool(false)
  ["class":"Symfony\Component\PropertyInfo\Type":private]=>
  string(14) "numeric-string"
  ["collection":"Symfony\Component\PropertyInfo\Type":private]=>
  bool(false)
  ["collectionKeyType":"Symfony\Component\PropertyInfo\Type":private]=>
  array(0) {
  }
  ["collectionValueType":"Symfony\Component\PropertyInfo\Type":private]=>
  array(0) {
  }
}
```

Comment (EmilMassey) [reply src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php]: > pseudo types will be considered as an object

My fix doesn't change that. Before the fix it is an object too (but the `$class` property value has the first character trimmed, and this bug is the subject of my fix):
```PHP
class Symfony\Component\PropertyInfo\Type#1168 (6) {
    private $builtinType =>
    string(6) "object"
    private $nullable =>
    bool(false)
    private $class =>
    string(13) "umeric-string"
    private $collection =>
    bool(false)
    private $collectionKeyType =>
    NULL
    private $collectionValueType =>
    NULL
  }
```
Although it may be `NULL` in [some cases](https://github.com/symfony/symfony/runs/5514991447?check_suite_focus=true#step:8:1497). I think it depends on phpdocumentor version, but I'm not sure yet. Can you confirm?

By the way, if you expected `numeric-string` pseudo-type to be mapped to `string` built-in type, it will be done so in Symfony 6.1 thanks to #44451

Comment (DannyMeyer) [reply src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php]: Yes, currently it will be mapped to object (and the first character got removed).
But think about your fix. Is numeric-string really an object? No.

And in some software there will be done additional checks/procedures when it's an object. So this commit isn't really an fix.

**Comment by derrabus** [comment]
The test failure looks realted:

```
There was 1 failure:

1) Symfony\Component\PropertyInfo\Tests\Extractor\PhpDocExtractorTest::testUnknownPseudoType
null does not match expected type "array".

/home/runner/work/symfony/symfony/src/Symfony/Component/PropertyInfo/Tests/Extractor/PhpDocExtractorTest.php:356
```

File: src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php (hunk 1 above)
Comment (EmilMassey) [reply src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php]: I'm not trying here to fix the issue with psuedo-types being treated as object. It still is a big issue and I believe this behavior cannot be changed in older branches as this will be a BC break. It is undocumented feature - the documentation does not promise that the component handles pseudo-types and before `v6.1`  it only handles a few of them. In my opinion we should implement it in major version and that's why I created #44455. But it's a hard problem to solve.

At the moment the least I can do without causing BC break is to merely fix the very issue with the first character being removed. If we fix it, I can work around the problem somehow (e.g. by checking if `class_exists` or by comparing it to predefined pseudo-types strings) in my project, what I can't do without the fix because the original phpdoc is in fact lost due to this bug.

>  Is numeric-string really an object? No.

Due to `string` being a reserved keyword in PHP and `-` which is not allowed in a class name  it never is. But consider this example:
```PHP
class SomeClass
{
    /**
     * @var scalar
     */
    public $scalarProperty;
}

class scalar {}
```
`scalar` is a pseudo-type handled by PHPStan. But if the `scalar` class is defined, it may as well be an object. Before the fix, extractor gives me an object with `calar` className and I expect `scalar` - that my fix resolves.

Comment (nicolas-grekas) [inline src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php]: please remove the comment at the end of the line

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php (hunk 1 above)
Comment (EmilMassey) [reply src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php]: Done. For me it's obvious, but [someone added the comment in later branches](https://github.com/symfony/symfony/blob/5b46cb9f0fb5f654f48eb3830e3bda2509bf0eb9/src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php#L190) so I just repeated it.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @EmilMassey.

**Comment by gnutix** [comment]
I'm using NelmioApiDocBundle, and the following code started breaking with : `get_parent_class(): Argument #1 ($object_or_class) must be an object or a valid class name, string given`

```php
    public function supports(Model $model): bool
    {
        return Enum::class === get_parent_class((string) $model->getType()->getClassName());
    }
```

The problem being that now sometimes `$model->getType()->getClassName()` returns `?\Some\Namespaced\ClassName` with a leading `?` for the "nullable". Which leads the bundle to not properly recognize classes that it used to describe automatically. :(

**Comment by EmilMassey** [comment]
@gnutix Thanks for noticing the bug. Is the code snippet from the bundle or it is a fragment of your project? If it’s from the bundle, could you please link the source?

Maybe it’s a good idea to create a new issue so it can be seen by more people as this PR is already closed?

**Comment by gnutix** [comment]
@EmilMassey I've finally had the time to look at it again, and fixed it. It was a bad typing on our part in a constructor : 

```php
/** @var array<?ExtraHoursReportCell> */
public array $weeks,
```

The `?` was triggering the issue, and was not necessary anymore because the code had evolved and it never received a `null` there anymore... :smile:

**Comment by EmilMassey** [comment]
@gnutix 

I'm glad you've managed to solve the problem, and thanks for the response :)
