### PR TITLE
[String] Fix some spellings in `EnglishInflector`

### LINKED ISSUE #58797: symfony/string EnglishInflector spelling mistakes in a coupla plurals
### Symfony version(s) affected

7.1

### Description

See https://github.com/symfony/string/blob/7.1/Inflector/EnglishInflector.php#L361

There is no such word "matricies", as per "appendix", it should be "appendices" ("es", not "ies").

Same just above with "indicies"... it should be "indices".

Refs:
- https://en.wiktionary.org/wiki/matrix#English
- https://en.wiktionary.org/wiki/index#English

Great lib though, thanks for yer hard work!

### How to reproduce

```
public function testPluraliseNonStandardPlural()
{
    $inflector = new EnglishInflector();
    $plurals = $inflector->pluralize('matrix');

    $this->assertEquals('matrices', $plurals[0]);
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58797
| License       | MIT

Fixing the issue highlighted a spelling error for "fax" as well (https://en.wiktionary.org/wiki/fax#English)

### CODE REVIEW

File: src/Symfony/Component/String/Inflector/EnglishInflector.php [hunk 1]
```diff
@@ -348,11 +348,14 @@ final class EnglishInflector implements InflectorInterface
...
+
         // boxes (box)
         ['xo', 2, false, true, 'oxes'],
 
         // indexes (index), matrixes (matrix)
-        ['x', 1, true, false, ['cies', 'xes']],
+        ['x', 1, true, false, ['ces', 'xes']],
 
         // appendices (appendix)
         ['xi', 2, false, true, 'ices'],
```
Comment (fabpot) [inline src/Symfony/Component/String/Inflector/EnglishInflector.php]: Shouldn't this one be moved before `x`?

Comment (alexandre-daubois) [reply src/Symfony/Component/String/Inflector/EnglishInflector.php]: We can actually merge both, I updated the PR

**Review by xabbuh — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @alexandre-daubois.
