### PR TITLE
[Serializer] Fix denormalizing XML array with empty body (5.x)

### LINKED ISSUE #43193: [Serializer] Problem when serializing/deserializing empty arrays in xml
**Symfony version(s) affected**: all? actually testing on `5.3.4`

**Description**
When serializing an object with an empty array in xml and then deserializing this array into the same class, I encounter an error.

**How to reproduce**
```php
class Test
{
     public function __construct(private SerializerInterface $serializer)
    {
    }

    public function test() {
        $object = new class(){
            public array $array = [];
        };
        
        $data = $this->serializer->serialize($object, 'xml');

        /**
         * $data is:
         * <?xml version="1.0"?>
         * <response>
         *  <array/>
         * </response>
         */

        $this->serializer->deserialize($data, get_class($object), 'xml');

        // :boom: 
        //  [Symfony\Component\Serializer\Exception\NotNormalizableValueException]                                  
        //  The type of the "array" attribute for class "class@anonymous" must be one of "array" ("string" given). 
    }
```

(NB: the error is not due to the anonymous class)

### PR DESCRIPTION
**Pull request by alexandre-daubois**
This happens for example with XML empty tags denormalizing to an object array attribute.

| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #43193 on Symfony 5.x
| License       | MIT
| Doc PR        | _NA_

Fix for 4.4 can be found in #43205

### CODE REVIEW

**Review by dunglas — DISMISSED** [review]
~~LGTM~~

**Review by lyrixx — APPROVED** [review]

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 1]
```diff
@@ -426,6 +426,10 @@ private function validateAndDenormalize(string $currentClass, string $attribute,
                     return null;
                 }
 
+                if ('' === $data && Type::BUILTIN_TYPE_ARRAY === $type->getBuiltinType()) {
```
Comment (dunglas) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]:
```
                if ('' === $data) {
                  if (Type::BUILTIN_TYPE_ARRAY === $builtinType = $type->getBuiltinType()) {
                      return [];
                  }
                  if (($builtinType === Type::BUILTIN_TYPE_BOOL || $builtinType === Type::BUILTIN_TYPE_INT || === Type::BUILTIN_TYPE_FLOAT) && $type->isNullable()) {
                    return null;
                  }
                }
```

To prevent an extra function call and an extra check, it is probably worth it to avoid repeating what is done in the previous condition. This may matter as we are on the hot path.

**Review by dunglas — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php (hunk 1 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: Good idea, it really makes sense! Just pushed, thank you for the suggestion, Kévin. :+1:

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php [hunk 2]
```diff
@@ -422,8 +422,14 @@ private function validateAndDenormalize(string $currentClass, string $attribute,
...
+                    if (Type::BUILTIN_TYPE_ARRAY === $builtinType = $type->getBuiltinType()) {
+                        return [];
+                    }
+
+                    if ($type->isNullable() && \in_array($builtinType, [Type::BUILTIN_TYPE_BOOL, Type::BUILTIN_TYPE_INT, Type::BUILTIN_TYPE_FLOAT], true)) {
+                        return null;
+                    }
                 }
 
                 switch ($type->getBuiltinType()) {
```
Comment (dunglas) [inline src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: We can even do this then:

```suggestion
                switch ($builtinType ?? $type->getBuiltinType()) {
```

**Review by dunglas — APPROVED** [review]

File: src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php (hunk 2 above)
Comment (alexandre-daubois) [reply src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php]: Saw you also added it in #43240 for 5.4, just pushed it for 5.3. Thanks for the approval!

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @alexandre-daubois.
