### PR TITLE
[Serializer] Fix mixed-typed constructor parameters overriding getter-inferred type

### LINKED ISSUE #63779: [Serializer] Regression in 7.4.6: mixed-typed constructor parameters override getter-inferred type, breaking custom denormalizers
### Symfony version(s) affected

7.4.6 / 7.4.7

### Description

PR #63401, merged in 7.4.6, introduced a regression: when a constructor parameter is typed mixed, the isSatisfiedBy condition in `AbstractObjectNormalizer::denormalizeParameter()` incorrectly overrides the richer type inferred by the property type extractor with `Type::mixed()`.

This breaks any setup where:

The constructor parameter uses `mixed` (or is untyped), and
A property type extractor returns a more specific type for that property (e.g. from a getter return type via `ReflectionExtractor`).

### How to reproduce

```php
class MyDTO
{
    public function __construct(
        private mixed $entity = null  // mixed-typed constructor param
    ) {}

    public function getEntity(): ?MyEntity  // getter has a specific return type
    {
        return $this->entity;
    }
}
```

With a custom denormalizer registered for `MyEntity` (e.g. one that resolves an integer ID to a Doctrine entity), `denormalize(['entity' => 42], MyDTO::class)` will **no longer invoke the custom denormalizer** in 7.4.6+. The raw integer `42` is passed to the constructor instead of a `MyEntity` instance.

This worked correctly in 7.4.5.

### Root cause

In `denormalizeParameter()`, the code introduced by #63401:

```php
if ($resolvedParameterType->isSatisfiedBy(static fn (Type $t) => match (true) {
    $t instanceof BuiltinType && TypeIdentifier::NULL !== $t->getTypeIdentifier()
        => !$type->isIdentifiedBy($t->getTypeIdentifier()),
    $t instanceof ObjectType => !$type->isIdentifiedBy($t->getClassName()),
    default => false,
})) {
    $type = $resolvedParameterType;
}
```

When the constructor parameter is `mixed`, `ReflectionTypeResolver` resolves it to `Type::mixed()` (a `BuiltinType` with `TypeIdentifier::MIXED`). The condition `TypeIdentifier::NULL !== MIXED` evaluates to `true`, and `!$type->isIdentifiedBy(MIXED)` is also `true` (since `$type` is e.g. `nullable(MyEntity::class)`), so `$type` is overridden with `Type::mixed()` — discarding the useful extractor-inferred type entirely.

`NULL` was already excluded from the override for the same reason: it carries no useful type information. `MIXED` should be treated identically.

### Possible Solution

```diff
-$t instanceof BuiltinType && TypeIdentifier::NULL !== $t->getTypeIdentifier()
+$t instanceof BuiltinType && TypeIdentifier::NULL !== $t->getTypeIdentifier() && TypeIdentifier::MIXED !== $t->getTypeIdentifier()
```

This ensures that a `mixed`-typed constructor parameter is treated as "no type constraint", leaving the extractor-inferred type intact — which is the correct behaviour when a getter provides more specific type information.

### Additional Context

The PR #63401 fix is correct for the case it targets (e.g. constructor typed `string`, extractor returns `list<string>` — the constructor type wins). The gap is only the `mixed` / untyped case, where the constructor type carries no information and should never win over the extractor.

### PR DESCRIPTION
**Pull request by Amoifr**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63779
| License       | MIT

This PR fixes a regression introduced in #63401 (7.4.6) where `mixed`-typed constructor parameters incorrectly override the richer type inferred by the property type extractor.

When a DTO has a constructor parameter typed `mixed` but a getter that returns a specific type (e.g., `?MyEntity`), the property type extractor correctly identifies the type from the getter. However, the condition introduced in #63401 was treating `mixed` as a meaningful type constraint and overriding the extractor's type with `Type::mixed()`.

```php
class MyDTO
{
    public function __construct(
        private mixed $entity = null,
    ) {}

    public function getEntity(): ?MyEntity
    {
        return $this->entity;
    }
}
```

With a custom denormalizer registered for `MyEntity`, `denormalize(['entity' => 42], MyDTO::class)` would **no longer invoke the custom denormalizer** in 7.4.6+. The raw integer `42` was passed to the constructor instead of a `MyEntity` instance.

The fix treats `mixed` as carrying no useful type constraint (same as `null`) across all three code paths in `denormalizeParameter()`:

- **`ReflectionTypeResolver` path**: exclude `TypeIdentifier::MIXED` in `isSatisfiedBy()`
- **`ReflectionNamedType` fallback path**: skip override when `TypeIdentifier::MIXED`
- **Legacy `getTypes()` BC path**: skip the whole override block when the parameter type is `mixed`

### CODE REVIEW

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php [hunk 1]
```diff
@@ -999,6 +1001,123 @@ public function getTypes(string $class, string $property, array $context = []):
...
+        $this->assertInstanceOf(DummyWithMixedConstructorParamAndEntityGetter::class, $result);
+        $this->assertInstanceOf(DummyEntity::class, $result->getEntity());
+        $this->assertSame(42, $result->getEntity()->id);
+    }
+
+    #[Group('legacy')]
+    #[IgnoreDeprecations]
+    public function testDenormalizeMixedConstructorParameterUsesExtractorTypeLegacy()
+    {
+        if (method_exists(ReflectionTypeResolver::class, 'resolve')) {
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: `ReflectionTypeResolver::resolve` always exists on 7.4, maybe this can be removed?

**Review by nicolas-grekas — APPROVED** [review]
There were 2 more code paths missing a similar fix, updated with tests.
I also fixed the PR description, "Symfony style".

File: src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php (hunk 1 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php]: let's see if the CI agrees :)

**Comment by Amoifr** [comment]
Thanks a lot @nicolas-grekas for the additional fixes! 🙏

My original patch was way too simplistic—seeing how you covered all three code paths (including the legacy BC layer) really takes it to another level. It's been instructive reading through your changes.

Much appreciated!
