### PR TITLE
[FrameworkBundle][HttpKernel] Move IDE file link formats from FrameworkExtension to FileLinkFormatter

### LINKED ISSUE #40901: `framework.ide` does not resolve known link format when using `env()`
**Symfony version(s) affected**: 5.x

**Description**
The [documentation for the `framework.ide` configuration](https://symfony.com/doc/current/reference/configuration/framework.html#ide) says:
> [...] If you prefer to open those files in your favorite IDE or text editor, set this option to any of the following values: `phpstorm`, `sublime`, `textmate`, `macvim`, `emacs`, `atom` and `vscode`.

Setting one of these values will automatically resolve them to the respective `xdebug.file_link_format`, i.e. `atom` will be expanded to `atom://core/open/file?filename=%f&line=%l`.
But when using environment variables for this configuration the value is not expanded automatically.

**How to reproduce**
The following two configurations work as expected, i.e. file links in the profiler are rendered as `atom://core/open/file?...`:
~~~yml
# config/packages/framework.yaml
framework:
    ide: 'atom' # set short version directly
~~~
~~~yml
# config/packages/framework.yaml
parameters:
    file_link_format: 'atom'

framework:
    ide: '%file_link_format%' # set short version via parameter expansion
~~~

While the following does not work as expected:

~~~yml
# config/packages/framework.yaml
framework:
    ide: '%env(FILE_LINK_FORMAT)%' # take value from environment
~~~
~~~
# .env
FILE_LINK_FORMAT=atom
~~~

Here the value is used literally and all file links in the profiler are rendered as `<a href="atom">...</a>`

**Possible Solution**
The automatic expansion of the known link formats is [done in `Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension::load()`](https://github.com/symfony/framework-bundle/blob/5dbd68b24fce31a3d5834962f994cf8b6985bd57/DependencyInjection/FrameworkExtension.php#L297-L310).

But this seems to be executed only once when configuration was changed and the result is cached (i.e. at "parse-time"?). Since the value of the environment is only known at run-rime it is evaluated after this.

1. Solution in code: refactor such that the expansion of known link formats is done after expansion of all environment variables in the configuration - i.e. at run-time with every call.

2. Solution in docs: document that expansion of the known formats does not work with environment variables.

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40901
| License       | MIT
| Doc PR        | N/A

I made `FileLinkFormatter` aware of IDEs file link formats so that you can set `framework.ide` as an env var containing a name (like `atom`).

Not sure how to test it from the `FrameworkExtension` POV though :thinking:

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 1]
```diff
@@ -213,20 +213,11 @@ public function load(array $configs, ContainerBuilder $container)
...
-                    'macvim' => 'mvim://open?url=file://%%f&line=%%l',
-                    'emacs' => 'emacs://open?url=file://%%f&line=%%l',
-                    'sublime' => 'subl://open?url=file://%%f&line=%%l',
-                    'phpstorm' => 'phpstorm://open?file=%%f&line=%%l',
-                    'atom' => 'atom://core/open/file?filename=%%f&line=%%l',
-                    'vscode' => 'vscode://file/%%f:%%l',
-                ];
                 $ide = $config['ide'];
                 // mark any env vars found in the ide setting as used
                 $container->resolveEnvPlaceholders($ide);
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: then we should remove this line

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 2]
```diff
@@ -213,20 +213,11 @@ public function load(array $configs, ContainerBuilder $container)
...
-                $links = [
-                    'textmate' => 'txmt://open?url=file://%%f&line=%%l',
-                    'macvim' => 'mvim://open?url=file://%%f&line=%%l',
-                    'emacs' => 'emacs://open?url=file://%%f&line=%%l',
-                    'sublime' => 'subl://open?url=file://%%f&line=%%l',
-                    'phpstorm' => 'phpstorm://open?file=%%f&line=%%l',
-                    'atom' => 'atom://core/open/file?filename=%%f&line=%%l',
-                    'vscode' => 'vscode://file/%%f:%%l',
-                ];
                 $ide = $config['ide'];
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: no need for this variable anymore

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php [hunk 3]
```diff
@@ -213,20 +213,11 @@ public function load(array $configs, ContainerBuilder $container)
...
                 // mark any env vars found in the ide setting as used
                 $container->resolveEnvPlaceholders($ide);
 
-                $container->setParameter('templating.helper.code.file_link_format', str_replace('%', '%%', ini_get('xdebug.file_link_format') ?: get_cfg_var('xdebug.file_link_format')) ?: ($links[$ide] ?? $ide));
+                $container->setParameter('templating.helper.code.file_link_format', str_replace('%', '%%', ini_get('xdebug.file_link_format') ?: get_cfg_var('xdebug.file_link_format')) ?: $ide);
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php]: would be even better:
`$container->setParameter('templating.helper.code.file_link_format', $config['ide']);`

**Review by nicolas-grekas — COMMENTED** [review]
Good idea.
That's an improvement, thus for 5.x

**Comment by MatTheCat** [comment]
@nicolas-grekas I applied your suggestions on the 5.x branch where the `templating.helper.code.file_link_format` parameter no longer exists.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by MatTheCat** [comment]
I take it from the approval I don’t have to add a case to `FrameworkExtensionTest`? :grin:

File: src/Symfony/Component/HttpKernel/Debug/FileLinkFormatter.php [hunk 4]
```diff
@@ -34,7 +44,7 @@ class FileLinkFormatter
      */
     public function __construct($fileLinkFormat = null, RequestStack $requestStack = null, string $baseDir = null, $urlFormat = null)
     {
-        $fileLinkFormat = $fileLinkFormat ?: ini_get('xdebug.file_link_format') ?: get_cfg_var('xdebug.file_link_format');
+        $fileLinkFormat = (self::FORMATS[$fileLinkFormat] ?? $fileLinkFormat) ?: ini_get('xdebug.file_link_format') ?: get_cfg_var('xdebug.file_link_format');
```
Comment (stof) [inline src/Symfony/Component/HttpKernel/Debug/FileLinkFormatter.php:47]: passing `null` as an array key won't work

Comment (MatTheCat) [reply src/Symfony/Component/HttpKernel/Debug/FileLinkFormatter.php:47]: Are you sure about that? From https://www.php.net/manual/en/language.types.array.php#example-58

> Null will be cast to the empty string, i.e. the key null will actually be stored under "".

Comment (stof) [reply src/Symfony/Component/HttpKernel/Debug/FileLinkFormatter.php:47]: hmm, indeed. It happily casts it without triggered a notice.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @MatTheCat.
