### PR TITLE
[Notifier] Fix Esendex messages serialization

### LINKED ISSUE #50892: Cannot send messages since esendex-notifier v6.3
### Symfony version(s) affected

6.3

### Description

Since I upgraded from esendex-notifier 6.2 to 6.3 I get an error message from esendex : "400 - No messages were supplied"
Untitled(4)

Profiler with 6.2 =>
Untitled(1)

Profiler with 6.3 =>
Untitled(3)

### How to reproduce

- upgrade the symfony/esendex-notifier in the composer.json to 6.3
- run `composer update symfony/notifier`

Untitled
Untitled(2)

### Possible Solution

As you can see in the profiler the "messages" is missing a dimension so it's serialized as an object instead of an array of objects.
So updating this =>
Untitled(5)
To this =>
Untitled(6)
Seems to do the trick :
Untitled(7)

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by raphael-geffroy**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no
| Tickets       | Fix #50892 
| License       | MIT

It seems that the "messages" is missing a dimension since 6.3 and its serialized as an object instead of an array of objects.

### CODE REVIEW

**Comment by derrabus** [comment]
Thank you. Can we add a test that covers your change?

**Comment by raphael-geffroy** [comment]
Sure I will try :)

**Comment by raphael-geffroy** [comment]
I added a test but feel free to modify it to comply to your level of requirement.

File: src/Symfony/Component/Notifier/Bridge/Esendex/Tests/EsendexTransportTest.php [hunk 1]
```diff
@@ -102,4 +102,31 @@ public function testSendWithSuccessfulResponseDispatchesMessageEvent()
...
+            return $response;
+        });
+
+        $transport = self::createTransport($client);
+
+        $transport->send(new SmsMessage('phone', 'testMessage'));
+
+        $body = json_decode($requestOptions['body'] ?? '');
+
+        $this->assertIsArray($body->messages);
```
Comment (fabpot) [inline src/Symfony/Component/Notifier/Bridge/Esendex/Tests/EsendexTransportTest.php]: Let's test the content of the array.

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Notifier/Bridge/Esendex/Tests/EsendexTransportTest.php (hunk 1 above)
Comment (raphael-geffroy) [reply src/Symfony/Component/Notifier/Bridge/Esendex/Tests/EsendexTransportTest.php]: Done :white_check_mark: Does it suit ?

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @raphael-geffroy.
