### PR TITLE
[Mime] Fix embed logic for background attributes

### LINKED ISSUE #42921: Mime: Email::embed doesn't work for background images
**Symfony version(s) affected**: 5.3.4

**Description**

I have an email template which sets a background image on a `td` element like this:

```html
<td background="bgimage.png">
```
This used to work fine in Swiftmailer with more or less the following code:

```php
$cid = $message->embed(Swift_Image::fromPath($path));
$html_body = str_replace($path, $cid, $html_body);
```

**How to reproduce**

In Symfony Mailer, I have the code from the documentation:

```php
$name = basename($path);
$message->embed(fopen($path, 'r'), $name);
$html_body = str_replace($path, 'cid:' . $name, $html_body);
```

Which works fine for `img` tags and `src` attributes, but it completely ignores the `background` attribute, because the regex is only looking at `img` tags:

https://github.com/symfony/symfony/blob/5ccf5ad00f9d5095ca842240e0cf26c060e4afb4/src/Symfony/Component/Mime/Email.php#L469

The HTML in the email looks like this in the end:

```html
<td background="cid:bgimage.png">
```

The image gets attached, but is missing a Content-ID:

```
Content-Type: application/octet-stream; name=bgimage.png
Content-Transfer-Encoding: base64
Content-Disposition: inline; name=bgimage.png; filename=bgimage.png
```

**Possible Solution**

I'm not a 100% sure, but one thing that could help is if Symfony could make sure that each (inline) attachment always gets a Content-ID, then I could work around the regex problem on my end.

An alternative would be to make the regex a bit more loose, basically to have it find anything that looks like `"cid:xxxx"`. Not sure if that would be a 100% safe, but there's still a matching of found CIDs to attachment names, so it should work, no?

**Additional context**

I know that the `background` attribute has probably been deprecated for well over a decade now, and in the normal web context I wouldn't bother trying to support it, but this is email we're talking about, and to this day Outlook (on Windows) uses an HTML rendering engine from 2007, so you have to get pretty old school to get decent looking mails. I guess if you look long and hard enough, there will be some other way to get background images on Outlook, but I also really don't want to re-do (and re-test) all the email templates I have, just because Swiftmailer is EOL.

### PR DESCRIPTION
**Pull request by flack**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #42921
| License       | MIT
| Doc PR        | 

As suggested by @fabpot here https://github.com/symfony/symfony/pull/43255#issuecomment-1030025526, this is the most minimal fix for the linked issue. I guess the same problem can happen if you use e.g.

```html
<div style="background-image:url(cid:test.gif)"></div>
```

I have changed it so that there is now an array of regexes to look for embedded images, so at least code for the `background-image` case (or others that might be found later on) can easily be added.

### CODE REVIEW

File: src/Symfony/Component/Mime/Tests/EmailTest.php [hunk 1]
```diff
@@ -343,7 +343,7 @@ public function testGenerateBody()
         $this->assertInstanceOf(RelatedPart::class, $body);
         // 2 parts only, not 3 (text + embedded image once)
         $this->assertCount(2, $parts = $body->getParts());
-        $this->assertStringMatchesFormat('html content <img src=3D"cid:%s@symfony">', $parts[0]->bodyToString());
+        $this->assertStringMatchesFormat('<div background=3D"cid:%s@symfony"></div>', $parts[0]->bodyToString());
```
Comment (fabpot) [inline src/Symfony/Component/Mime/Tests/EmailTest.php:361]: Same here

File: src/Symfony/Component/Mime/Tests/EmailTest.php [hunk 2]
```diff
@@ -329,7 +329,7 @@ public function testGenerateBody()
         $generatedHtml = $parts[0]->getParts()[1];
         $this->assertStringContainsString('cid:'.$parts[1]->getContentId(), $generatedHtml->getBody());
 
-        $content = 'html content <img src="cid:test.gif">';
+        $content = '<div background="cid:test.gif"></div>';
```
Comment (fabpot) [inline src/Symfony/Component/Mime/Tests/EmailTest.php]: Can you add new tests instead of modifying existing ones?

**Review by fabpot — CHANGES_REQUESTED** [review]

**Comment by flack** [comment]
There's a coding style violation that wants me to add a trailing comma in the regex array. AFAIK that is only supported on PHP 7.3+, so it'll probably cause CI to fail. Should I still do it?

**Comment by flack** [comment]
also, what is your policy with implementing review comments, should I make new commits or squash immediately?

**Comment by flack** [comment]
implemented review comments (except for the trailing comma one, see above)

**Comment by derrabus** [comment]
> There's a coding style violation that wants me to add a trailing comma in the regex array. AFAIK that is only supported on PHP 7.3+, so it'll probably cause CI to fail. Should I still do it?

Trailing commas in array constructors are allowed in PHP 7.1 already, no worries.

**Comment by derrabus** [comment]
> also, what is your policy with implementing review comments, should I make new commits or squash immediately?

As you wish, we can squash while merging.

**Comment by flack** [comment]
alright, thx. All suggestions should be implemented now

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
I'm merging it in 6.1 as this is a new feature (this was not supported before).

**Comment by flack** [comment]
well, it worked with Swiftmailer, so from the point of view of the user it's still a regression

**Comment by fabpot** [comment]
Thank you @flack.

**Comment by fabpot** [comment]
We've been more and more strict about what we consider a bug. Stability is the most important thing for already released versions.

**Comment by flack** [comment]
Yeah, makes sense I guess. Unfortunately, for me it means I have to continue using the abandoned Switfmailer package (with composer shouting at me every time I update something) until I can migrate to php 8+ and sf 6

**Comment by veto221** [comment]
Hi. 
Can I please for merge this for LTS version too?
