### PR TITLE
[Console] Fix save correct name in setDefaultCommand() for PHP8

### LINKED ISSUE #41942: [Console] Hidden option using PHP 8 AsCommand attribute
**Symfony version(s) affected**: 5.3.0 to current latest 5.3.3

**Description**
I always get a different behavior between hidden option in php 8 attribute (#[AsCommand]) and the `setHidden()` method in configure method even with the fix #41686. Also with `cache:clear`.

**How to reproduce**
I've created a project (see below) to simplify the tests, but :
- Declare the DefaultCommand class in `src/Command`:
```php
<?php

namespace App\Command;

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class DefaultCommand extends Command
{
    protected static $defaultName = 'app:default';

    protected function configure(): void
    {
        $this
            ->setDescription('wrapper')
            ->setHidden(true)
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output): ?int
    {
        /** @var Application $application */
        $application = $this->getApplication();

        $command = $application->find('list');
        $arguments = ['namespace' => 'app'];

        $listInput = new ArrayInput($arguments);

        return $command->run($listInput, $output);
    }
}
```

- Declare a new `Application.php` class in `src` folder and use it in `bin/console` instead of the default Application class (just need to change the namespace):

**src/Application.php**
```php
<?php

declare(strict_types=1);

namespace App;

use App\Command\DefaultCommand;
use Symfony\Bundle\FrameworkBundle\Console\Application as SymfonyApplication;
use Symfony\Component\HttpKernel\KernelInterface;

class Application extends SymfonyApplication
{
    public function __construct(KernelInterface $kernel)
    {
        parent::__construct($kernel);

        if ($defaultName = DefaultCommand::getDefaultName()) {
            $this->setDefaultCommand($defaultName);
        }
    }
}
```
**bin/console**
```php
#!/usr/bin/env php
<?php

use App\Kernel;
use App\Application;

if (!is_file(dirname(__DIR__).'/vendor/autoload_runtime.php')) {
    throw new LogicException('Symfony Runtime is missing. Try running "composer require symfony/runtime".');
}

require_once dirname(__DIR__).'/vendor/autoload_runtime.php';

return function (array $context) {
    $kernel = new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);

    return new Application($kernel);
};
```
- Make a random command, for exemple `app:hello` with or without PHP 8 attributes.
- See the output of `bin/console`. Update DefaultCommand with PHP 8 #[AsCommand] attribute and observe the difference.

**OR** use the following project as exemple
[https://github.com/duboiss/sfcommand](https://github.com/duboiss/sfcommand)
```sh
git clone https://github.com/duboiss/sfcommand
cd sfcommand
composer install
bin/console

git switch php8
bin/console
```
**Additional context**
Without attribute
image

With attribute
image

This is probably due to the fact that it has become lazy. Is there any way to keep the PHP 8 attribute and disable lazy (if that is the cause)?

### PR DESCRIPTION
**Pull request by a1812**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #41942 | License       | MIT
| Doc PR        | 

Fix save correct name in setDefaultCommand() for PHP8

### CODE REVIEW

**Comment by duboiss** [comment]
I don't feel that this is fixing #41942 after testing on my local project ([duboiss/sfcommand](https://github.com/duboiss/sfcommand), php8 branch) your modifications.

**Comment by a1812** [comment]
> I don't feel that this is fixing #41942 after testing on my local project ([duboiss/sfcommand](https://github.com/duboiss/sfcommand), php8 branch) your modifications.

and nevertheless my test shows that everything is in order :)
image

**Comment by duboiss** [comment]
My bad, I think I made a mistake between two `git clone`. It's ok from my side too, nice job!

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Component/Console/Application.php [hunk 1]
```diff
@@ -1147,6 +1147,9 @@ private function findAlternatives(string $name, iterable $collection): array
      */
     public function setDefaultCommand(string $commandName, bool $isSingleCommand = false)
     {
+        $commandName = ltrim($commandName, '|');
+        $commandName = explode('|', $commandName)[0];
+
```
Comment (fabpot) [inline src/Symfony/Component/Console/Application.php]: Could we inline everything below:

```php
$this->defaultCommand = explode('|', ltrim($commandName, '|'))[0];
```

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Console/Application.php (hunk 1 above)
Comment (a1812) [reply src/Symfony/Component/Console/Application.php]: ok

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @a1812.
