### PR TITLE
[HttpClient] Make `CachingHttpClient` compatible with RFC 9111

### LINKED ISSUE #36858: [HttpKernel][HttpClient] `CachingHttpClient` should be configurable as a `private` cache
The `CachingHttpClient` internally uses `HttpCache`. That class, however, has been designed as a `public` (shared; surrogate) cache.

In this "downstream" caching use case, however, it would be valuable if we 

* could make the cache store `private` responses, possibly even by default,
* enforce a "greedy" caching strategy, i. e. a minimum TTL to apply regardless of what the upstream server sent
* support `stale-while-revalidate` behavior 🆒

Client-side caching in the `HttpClient` is useful in µService architectures where you possibly hit a lot of backend APIs; `stale-while-revalidate` and `stale-if-error` may further improve performance or even save the day when a backend service goes down.

### LINKED ISSUE #41843: [HttpClient] Add support for configuring cache at framework bundle level
**Description**
ATM, when we want to use cache with the HTTP Client we need to configure it manually like states [in the doc](https://symfony.com/doc/current/http_client.html#caching-requests-and-responses).

We can also use the DIC to do so, but I guess this not really easy for new comers
```yaml
    Symfony\Component\HttpKernel\HttpCache\Store:
        arguments:
            $root: '%kernel.cache_dir%/http-cache'

    opaClientWithCache:
        class: Symfony\Component\HttpClient\CachingHttpClient
        decorates: opaClient
        arguments:
            $client: '@opaClientWithCache.inner'
            $store: '@Symfony\Component\HttpKernel\HttpCache\Store'
            $defaultOptions:
                base_uri: '%env(OPA_ENDPOINT)%'
```

More over, something is not really DX Friendly: I had to duplication the `base_uri` as you can see :/ 

Anyway, having something native in the framework would be much better I think

**Example**

```yaml
framework:
    http_client:
        scoped_clients:
            opaClient:
                base_uri: "%env(OPA_ENDPOINT)%"
                headers:
                    Authorization: "Bearer %env(OPA_TOKEN)%"
                cache:
                    enabled: true # This is new, and this add a basic cache in the `cache` dir
                    path: 'foo/bar' # Optional, a location
                    store: @serviceId # Optional, a service for a full control. path and store can not be used at the same time
```

WDYT?

### LINKED ISSUE #49937: CachingHttpClient does not cache responses with missing "public" cache-control header
### Symfony version(s) affected

6.2.8

### Description

I was writing a crawler for an API on Drupal.org and I tried to be nice for the provider by caching responses locally. I have followed [the official documentation](https://symfony.com/doc/current/http_client.html#caching-requests-and-responses) for enabling response caching on the HTTP client. I was surprised to see that the responses are not being cached. I dig deeper and deeper and I spotted that `private` Cache-Control header appears in responses, however the API backend definitely does not send that header.

I think the root cause is related to the implementation in the HTTP.

1.  ˙\Symfony\Component\HttpKernel\HttpClientKernel::handle()` builds a new response in https://github.com/symfony/symfony/blob/93fbfe0a20a3e967a7051b6b01ded8970d5bab43/src/Symfony/Component/HttpKernel/HttpClientKernel.php#L58
2. Which calls `\Symfony\Component\HttpFoundation\ResponseHeaderBag::computeCacheControlValue()` marks the response are `private` due to the lack of explicitly specified `public` header value. This bubbles up the following calls...
https://github.com/symfony/symfony/blob/v6.2.8/src/Symfony/Component/HttpFoundation/ResponseHeaderBag.php#L255-L259
3.  ...even if there is a workaround (I suppose) here for ignoring calculated headers https://github.com/symfony/symfony/blob/93fbfe0a20a3e967a7051b6b01ded8970d5bab43/src/Symfony/Component/HttpKernel/HttpClientKernel.php#L64-L69

Stack trace:

image
image

### How to reproduce

**POC**

```sh
$ php guzzle.php 
Array
(
    [0] => store, no-cache, must-revalidate, post-check=0, pre-check=0
)
$ php symfony.php 
Array
(
    [0] => store, no-cache, must-revalidate, post-check=0, pre-check=0
)
$ php symfony_with_cache.php 
Array
(
    [0] => must-revalidate, no-cache, post-check=0, pre-check=0, private, store
)
```

symfony.php
```php
use Symfony\Component\HttpClient\HttpClient;

$client = HttpClient::create();

$response = $client->request('GET', 'https://updates.drupal.org/release-history/drupal/current?version=10.0.0',  [
  'headers' => [
    'Accept' => 'text/xml',
  ],
]);
print_r($response->getHeaders()['cache-control']);
```

symfony-with-cache.php
```
use Symfony\Component\HttpClient\CachingHttpClient;
use Symfony\Component\HttpClient\HttpClient;
use Symfony\Component\HttpKernel\HttpCache\Store;

$client = HttpClient::create();
$client = new CachingHttpClient($client, new Store(__DIR__ . '/cache'));

$response = $client->request('GET', 'https://updates.drupal.org/release-history/drupal/current?version=10.0.0',  [
  'headers' => [
    'Accept' => 'text/xml',
  ],
]);
print_r($response->getHeaders()['cache-control']);
```

### Possible Solution

_No response_

### Additional Context

The root cause of the issue can be the interpretation of https://www.rfc-editor.org/rfc/rfc7234#section-3.

Only one of these is required, so `s-maxage` should not be required on a GET request with HTTP 200 response.

> the response either:
> 
>       *  contains an Expires header field (see [Section 5.3](https://www.rfc-editor.org/rfc/rfc7234#section-5.3)), or
> 
>       *  contains a max-age response directive (see [Section 5.2.2.8](https://www.rfc-editor.org/rfc/rfc7234#section-5.2.2.8)), or
> 
>       *  contains a s-maxage response directive (see [Section 5.2.2.9](https://www.rfc-editor.org/rfc/rfc7234#section-5.2.2.9))
>          and the cache is shared, or
> 
>       *  contains a Cache Control Extension (see [Section 5.2.3](https://www.rfc-editor.org/rfc/rfc7234#section-5.2.3)) that
>          allows it to be cached, or
> 
>       *  has a status code that is defined as cacheable by default (see
>          [Section 4.2.2](https://www.rfc-editor.org/rfc/rfc7234#section-4.2.2)), or

### LINKED ISSUE #61588: [HttpClient] Allow use Redis storage on CachingHttpClient
### Description

The current CachingHttpClient store cache on file. 

Nowadays, an application can be duplicated on multiple servers, which complicates the use of a file cache. Adding the ability to use a Redis cache would facilitate the use of client caching.

### Example

_No response_

### PR DESCRIPTION
**Pull request by Lctrs**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | yes
| Issues        | Fix #36858 Fix #49937 Fix #41843 Fix #61588
| License       | MIT

This PR brings [RFC9111](https://www.rfc-editor.org/rfc/rfc9111.html) support to `CachingHttpClient` by leveraging `symfony/cache`. It provides caching for `GET` and `HEAD` requests, and cache invalidation for `POST`, `PUT`, `DELETE`, `PATCH`.

The implementation is **asynchronous**, so the response **must be consumed** (e.g., via getContent() or streaming) for caching to occur.

### Basic usage

```php
// Create the base HTTP client
$baseClient = HttpClient::create();

// Create a cache backend (e.g., Filesystem cache)
$cache = new FilesystemAdapter();

// Instantiate the CachingHttpClient
$client = new CachingHttpClient(
    client: $baseClient,
    cache: $cache,
    defaultOptions: [], // Optional default options
    sharedCache: true,  // Use a shared cache (default)
    maxTtl: 86400      // Maximum cache TTL in seconds (optional)
);

// Make a request
$response = $client->request('GET', 'https://api.example.com/data');

// Get the response content
$content = $response->getContent();
```

### Constructor parameters

- `$client`: The underlying HTTP client.
- `$cache`: A cache backend implementing `TagAwareCacheInterface`.
- `$defaultOptions`: An optional array of default request options.
- `$sharedCache`: `true` to indicate the cache is [shared](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Caching#shared_cache), `false` for [private](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Caching#private_caches). Defaults to true.
- `$maxTtl`: Optional maximum time-to-live (in seconds) for cached responses. If set, server-provided TTLs are capped to this value.

### Omissions from RFC9111
- The following cache-control directives are not supported and thus ignored : `stale-while-revalidate`, `min-fresh`, `max-stale`, and `only-if-cached`. In the case of `stale-while-revalidate`, a stale response will always be revalidated.
- Range requests and partial content (206 status, Range/Content-Range headers) are not supported; requests with Range headers bypass caching.

### Integration with FrameworkBundle

```yaml
framework:
    http_client:
        caching:
            cache_pool: my_taggable_pool
            shared: true
            max_ttl: 86400
        scoped_clients:
            caching_client:
                base_uri: 'https://symfony.com'
                caching:
                    cache_pool: my_taggable_pool
```

It is also **highly recommended** to configure a retry strategy to automatically retry the request in case of cache inconsistency.

### CODE REVIEW

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php [hunk 1]
```diff
@@ -0,0 +1,605 @@
...
+    public function __construct(
+        HttpClientInterface $client,
+        private readonly TagAwareAdapterInterface $cache,
+        array $defaultOptions = [],
+        private readonly bool $sharedCache = true,
+        private readonly ?int $ttl = null,
+        private readonly array $defaultCachableStatusCodes = [200, 203, 204, 206, 300, 301, 404, 405, 410, 414, 501],
+        private readonly array $conditionallyCachableCodes = [302, 303, 307, 308],
+        private readonly array $cacheableMethods = ['GET', 'HEAD'],
+        private readonly array $unsafeMethods = ['POST', 'PUT', 'DELETE', 'PATCH'],
```
Comment (OskarStark) [inline src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: Do we need this, or can we say "all methods which are not cacheable, are considered unsafe?"

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php [hunk 2]
```diff
@@ -0,0 +1,605 @@
...
+
+    private array $defaultOptions = self::OPTIONS_DEFAULTS;
+
+    public function __construct(
+        HttpClientInterface $client,
+        private readonly TagAwareAdapterInterface $cache,
+        array $defaultOptions = [],
+        private readonly bool $sharedCache = true,
+        private readonly ?int $ttl = null,
+        private readonly array $defaultCachableStatusCodes = [200, 203, 204, 206, 300, 301, 404, 405, 410, 414, 501],
```
Comment (OskarStark) [inline src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]:
```suggestion
        private readonly array $cachableStatusCodes = [200, 203, 204, 206, 300, 301, 404, 405, 410, 414, 501],
```

not sure about the `default` prefix

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php [hunk 3]
```diff
@@ -0,0 +1,605 @@
...
+        private readonly array $conditionallyCachableCodes = [302, 303, 307, 308],
```
Comment (OskarStark) [inline src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]:
```suggestion
        private readonly array $conditionallyCachableStatusCodes = [302, 303, 307, 308],
```
to be consistent

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php [hunk 4]
```diff
@@ -0,0 +1,605 @@
...
+    }
+    use HttpClientTrait;
+
+    private array $defaultOptions = self::OPTIONS_DEFAULTS;
+
+    public function __construct(
+        HttpClientInterface $client,
+        private readonly TagAwareAdapterInterface $cache,
+        array $defaultOptions = [],
+        private readonly bool $sharedCache = true,
```
Comment (OskarStark) [inline src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: This and all properties should be described properly

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php (hunk 1 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: No. Unsafe methods are methods that can change the server's state or data. Per RFC 9111, they should trigger a cache invalidation when called (which the current implementation do).

So, if eg. `HEAD` is not configured as a cacheable method by the user, it's still not an unsafe method and shouldn't trigger a cache invalidation when called.

Comment (Lctrs) [reply src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: We could put as a class const, but I've came across APIs that proposed `POST` endpoints to let their users express complex search queries that wouldn't fit in a regular `GET` endpoint with url parameters, so I wanted to let the users be able to configure that.

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php (hunk 4 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: Is it good enough for you now ?

**Comment by stof** [comment]
Can we bring this to CachingHttpClient (with a BC layer) instead of introducing a new class that is the good implementation of caching but with a name that is much less clear ?
Also, having the RFC id in the class name is a bad idea to me, as it would be a pain if a new RFC gets released to replace the current one (which happened multiple times for RFCs related to HTTP)

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/schema/symfony-1.0.xsd [hunk 5]
```diff
@@ -745,6 +747,35 @@
...
+                </xsd:simpleType>
+            </xsd:element>
+            <xsd:element name="conditionally-cacheable-status-code" minOccurs="0" maxOccurs="unbounded">
+                <xsd:simpleType>
+                    <xsd:list itemType="xsd:integer"/>
+                </xsd:simpleType>
+            </xsd:element>
+            <xsd:element name="cacheable-method" minOccurs="0" maxOccurs="unbounded">
+                <xsd:simpleType>
+                    <xsd:list itemType="xsd:string"/>
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/Resources/config/schema/symfony-1.0.xsd]: Why an `xsd:list` ? This does not make sense to me. The `cacheable-method` method element should *be* as `xsd:string` directly (see the `transition` type for the workflow configuration line 478 of this file for an example)

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php [hunk 6]
```diff
@@ -0,0 +1,616 @@
...
+    }
+    use HttpClientTrait;
+
+    private array $defaultOptions = self::OPTIONS_DEFAULTS;
+
+    /**
+     * @param HttpClientInterface      $client                           The decorated client
+     * @param TagAwareAdapterInterface $cache                            The cache to store responses
+     * @param array                    $defaultOptions                   The default options for the client
+     * @param bool                     $sharedCache                      Whether to share the cache between all instances of this client
```
Comment (stof) [inline src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: what is the actual behavior of this setting ?

If this is about configuring as a shared cache with the meaning of HTTP shared cache (that must not cache private responses), the description of the argument is not clear at all. And otherwise, I have no idea what it could mean at all (as whether the storage is shared between multiple instances of this client depends on whether they use the same cache instance or no)

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php [hunk 7]
```diff
@@ -0,0 +1,616 @@
...
+    public function __construct(
+        HttpClientInterface $client,
+        private readonly TagAwareAdapterInterface $cache,
+        array $defaultOptions = [],
+        private readonly bool $sharedCache = true,
+        private readonly ?int $ttl = null,
+        private readonly array $cachableStatusCodes = [200, 203, 204, 206, 300, 301, 404, 405, 410, 414, 501],
+        private readonly array $conditionallyCachableStatusCodes = [302, 303, 307, 308],
+        private readonly array $cacheableMethods = ['GET', 'HEAD'],
+        private readonly array $unsafeMethods = ['POST', 'PUT', 'DELETE', 'PATCH'],
```
Comment (stof) [inline src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: why do we need to make those unsafe methods configurable ? The spec is the one defining which methods are unsafe. I don't see the value of increasing the complexity of the configuration by making them configurable (and making it possible to have a Rfc9111HttpClient that behaves in a way incompatible with the RFC 9111)

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php [hunk 8]
```diff
@@ -0,0 +1,616 @@
...
+        if ($responses instanceof ResponseInterface) {
+            $responses = [$responses];
+        }
+
+        $mockResponses = [];
+        $asyncResponses = [];
+        $clientResponses = [];
+
+        foreach ($responses as $response) {
+            if ($response instanceof MockResponse) {
```
Comment (stof) [inline src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: Why do we need a special case for MockResponse ? We should be delegating to the inner client and let it handle its responses

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php [hunk 9]
```diff
@@ -0,0 +1,616 @@
...
+        return "metadata_{$requestHash}_{$variantKey}";
+    }
+
+    /**
+     * Build a variant key for caching, given an array of normalized headers and the vary fields.
+     *
+     * The key is a pipe-separated string of "header=value" pairs, with the special case of "header=" for headers that are not present.
+     *
+     * @param array $normalizedHeaders normalized headers
+     * @param array $varyFields        vary fields
```
Comment (stof) [inline src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: the parameter description is useless here. It only repeats parameter names with words separated by spaces instead of being camel cased.

However, we should have a precise type for both arrays:

```
@param array<string, string|string[]> $normalizedHeaders
@param string[] $varyFields
```

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php [hunk 10]
```diff
@@ -0,0 +1,616 @@
...
+     *
+     * @return string the variant key
```
Comment (stof) [inline src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: the description is useless here. It brings no additional value compared to the method name or the method description (and then the whole `@return` becomes useless because the native type is already precise enough)

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php [hunk 11]
```diff
@@ -0,0 +1,616 @@
...
+                $parts[] = $field.'=';
+            } else {
+                $joined = \is_array($normalizedHeaders[$lower])
+                    ? implode(',', $normalizedHeaders[$lower])
+                    : (string) $normalizedHeaders[$lower];
+                $parts[] = $field.'='.$joined;
+            }
+        }
+
+        return implode('|', $parts);
```
Comment (stof) [inline src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: what if we have header values containing a `|` ? Currently, this would allow matching a different key.

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php [hunk 12]
```diff
@@ -0,0 +1,616 @@
...
+        }
+
+        $mockResponses = [];
+        $asyncResponses = [];
+        $clientResponses = [];
+
+        foreach ($responses as $response) {
+            if ($response instanceof MockResponse) {
+                $mockResponses[] = $response;
+            } elseif ($response instanceof AsyncResponse) {
```
Comment (stof) [inline src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: What happens if the inner client also uses an AsyncResponse, and we are in the case where the `request` method returns the inner response directly ?

Conditional return of a forwarded response or an owned response makes it hard to implement streaming reliably.

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php (hunk 8 above)
Comment (stof) [reply src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: OK, apparently, this class is also creating its own MockResponse instances. But wouldn't this cause issues if the inner client also uses some mock responses ?

Comment (stof) [reply src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: And we clearly need some tests covering the streaming implementation. this is the most tricky part of this HTTP client, and it is currently totally untested.

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php (hunk 7 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: https://github.com/symfony/symfony/pull/59576#discussion_r1925262705

> We could put as a class const, but I've came across APIs that proposed POST endpoints to let their users express complex search queries that wouldn't fit in a regular GET endpoint with url parameters, so I wanted to let the users be able to configure that.

Comment (Lctrs) [reply src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: The default values are inline with what RFC 9111 defines, but I wanted to let the users be able to tweak them to match their odd cases (because if that's not the case, you can be sure they'll open issues for this here).

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php (hunk 9 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: Oh you accept precise types now ? Cool ! What about `list<string>` kind of types ?

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php (hunk 7 above)
Comment (stof) [reply src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: the issue with that is that configurable `<cacheable-method>PUT</cacheable-method>` does not only make `PUT` cacheable. It also makes all RFC-cacheable methods uncacheable because the default value of a prototyped array node is not merged with the provided configuration in the Config component (and the default value of a PHP array argument is not merged either with the provided value).

I would suggest that the first version of this client does not have such configuration. Our existing CachingHttpClient does not expose such configuration either and I'm not aware of any request to add support for it. If we start without this feature, we can introduce it later. However, if we make it configurable now, it is very hard to _remove_ the feature later.

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php (hunk 9 above)
Comment (stof) [reply src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: We do use `list<string>` for cases where this is the right type.
However, for parameters, we avoid _requiring_ a list when our usage does not care about keys, as it puts unnecessary burden on the caller to provide a valid list. This means that most of our usages of the `list` type will be in return types (where using a more precise type brings _benefits_ to the caller by telling them they don't need to use `array_values` in case they really need a list). We'll have `list` in parameters only when passing something else would break the behavior of the code.
For instance, `$varyFields` does not need a list here. It iterates over array values without caring about the keys at all.

File: src/Symfony/Bundle/FrameworkBundle/Resources/config/schema/symfony-1.0.xsd (hunk 5 above)
Comment (Lctrs) [reply src/Symfony/Bundle/FrameworkBundle/Resources/config/schema/symfony-1.0.xsd]: Removed.

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php (hunk 6 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: Adressed.

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php (hunk 7 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: I've removed all configuration related to status codes and http methods.

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php (hunk 9 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: Adressed.

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php (hunk 10 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: Adressed.

File: src/Symfony/Component/HttpClient/Rfc9111HttpClient.php (hunk 11 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/Rfc9111HttpClient.php]: Adressed.

File: src/Symfony/Component/HttpClient/Tests/LegacyCachingHttpClientTest.php [hunk 13]
```diff
@@ -0,0 +1,128 @@
...
+use Symfony\Contracts\HttpClient\ResponseInterface;
+
+/**
+ * @group legacy
+ */
+class LegacyCachingHttpClientTest extends TestCase
+{
+    /**
+     * @expectedDeprecation Since symfony/http-client 7.3: Passing a "Symfony\Component\HttpKernel\HttpCache\StoreInterface" as constructor's 2nd argument of "Symfony\Component\HttpClient\CachingHttpClient" is deprecated, "Symfony\Component\Cache\Adapter\TagAwareAdapterInterface" expected.
+     */
```
Comment (alexandre-daubois) [inline src/Symfony/Component/HttpClient/Tests/LegacyCachingHttpClientTest.php]: If I remember correctly, `@expect...` annotation are deprecated. Instead, you should `use ExpectDeprecationTrait` in your test class, then call `$this->expectDeprecation('Since symfony/http-client 7.3: ...')` in each test case.

Comment (Lctrs) [reply src/Symfony/Component/HttpClient/Tests/LegacyCachingHttpClientTest.php]: Adressed

**Comment by Lctrs** [comment]
UPDATE:
- CI failure on PHP 8.5 is unrelated
- Psalm failure seems to be a false positive to me
- Tests pass locally on low deps, but not on github actions. I need to look at it.
- I don't know how to please fabbot. Should I not make any change to the upgrade file ?

Otherwise, PR is ready on my side. Ready for another reviews.

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 14]
```diff
@@ -2130,6 +2132,32 @@ private function addHttpClientSection(ArrayNodeDefinition $rootNode, callable $e
...
+
+        return $root
+            ->arrayNode('caching')
+                ->info('Caching configuration.')
+                ->canBeEnabled()
+                ->addDefaultsIfNotSet()
+                ->children()
+                    ->stringNode('cache')
+                        ->info("The taggable cache's service ID.")
+                        ->defaultValue('cache.app.taggable')
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: the default should probably be a dedicated cache pool instead of using `cache.app` directly, to avoid key conflicts (and when configuring scoped clients, they should probably use their own cache pool to avoid sharing cache keys between different configured clients)

File: src/Symfony/Component/HttpClient/CHANGELOG.md [hunk 15]
```diff
@@ -6,6 +6,7 @@ CHANGELOG
 
  * Add IPv6 support to `NativeHttpClient`
  * Allow using HTTP/3 with the `CurlHttpClient`
+ * Added RFC 9111–based caching support to `CachingHttpClient` (though some features remain partially supported)
```
Comment (stof) [inline src/Symfony/Component/HttpClient/CHANGELOG.md]:
```suggestion
 * Add RFC 9111–based caching support to `CachingHttpClient` (though some features remain partially supported)
```

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 16]
```diff
@@ -11,62 +11,346 @@
...
+     *                              may be skipped from caching in presence of certain headers
+     *                              (e.g. Authorization) unless explicitly marked as public.
+     * @param int|null $maxTtl      The maximum time-to-live (in seconds) for cached responses.
+     *                              If a server-provided TTL exceeds this value, it will be capped
+     *                              to this maximum.
+     */
     public function __construct(
         private HttpClientInterface $client,
-        StoreInterface $store,
+        TagAwareAdapterInterface|StoreInterface $store,
```
Comment (stof) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]: I suggest rename the argument to `$cache` so that the name matches the new API rather than the old one

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 17]
```diff
@@ -11,62 +11,346 @@
...
+
+        $fullUrl = implode('', $fullUrl);
+        $fullUrlTag = hash('xxh3', $fullUrl);
+
+        if (\in_array($method, self::UNSAFE_METHODS, true)) {
+            $this->cache->invalidateTags([$fullUrlTag]);
+        }
+
+        if (!empty($options['body']) || isset($options['normalized_headers']['range']) || !\in_array($method, self::CACHEABLE_METHODS, true)) {
+            return $this->client->request($method, $url, $options);
```
Comment (stof) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]: you are still directly returning the inner response here in some cases, while the `stream` method assumes that any AsyncResponse is owned by this CachingHttpClient, which will break things if the inner client is also an async decorator.
and this might also cause issues if the inner client is a MockClient as `stream` also takes ownership of the mock responses.

You might need to create a pass-through response instead, so that you also return a response owned by this client.

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 18]
```diff
@@ -106,41 +390,313 @@ public function request(string $method, string $url, array $options = []): Respo
...
+
+    /**
+     * Evaluates the freshness of a cached response based on its headers and expiration time.
+     *
+     * This method determines the state of the cached response by analyzing the Cache-Control
+     * directives and the expiration timestamp. It returns one of the following states:
+     * - 'fresh': if the cached response is still valid or has no expiration.
+     * - 'must-revalidate': if the response must be revalidated before use.
+     * - 'stale-but-usable': if the response is stale but can be used in case of errors.
+     * - 'stale': if the cached response is no longer valid or usable.
```
Comment (stof) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]: I suggest creating private constants for those states, which will avoid having magic strings in multiple places (and will allow documenting this as `@return self::STATE_*`)

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 19]
```diff
@@ -106,41 +390,313 @@ public function request(string $method, string $url, array $options = []): Respo
...
+     *
+     * @param array $data the cached response data, including headers and expiration time
```
Comment (stof) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]:
```suggestion
     * @param array{headers: array<string, string[]>, expires: int|null} $data the cached response data, including headers and expiration time
```

Comment (stof) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: The type for headers should be checked. My proposal assumes they are normalize to have arrays as values, but maybe the value type should be `string|string[]` instead

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 20]
```diff
@@ -106,41 +390,313 @@ public function request(string $method, string $url, array $options = []): Respo
...
+    /**
+     * Creates a MockResponse object from cached data.
+     *
+     * This function constructs a MockResponse from the cached data, including
+     * the original request method, URL, and options, as well as the cached
+     * response headers and content. The constructed MockResponse is then
+     * returned.
+     *
+     * @param string $key        the cache key for the response
+     * @param array  $cachedData the cached data for the response
```
Comment (stof) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]: this should describe the precise type for the array shape. It will benefit future contributors and maintainers reading the code, and will also make the static analysis more useful by catching potential mistakes.

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 21]
```diff
@@ -106,41 +390,313 @@ public function request(string $method, string $url, array $options = []): Respo
...
+     * @param string $method     the original request method
+     * @param string $url        the original request URL
+     * @param array  $options    the original request options
+     *
+     * @return MockResponse the constructed MockResponse object
```
Comment (stof) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]: the descriptions for the return value and the parameters is useless IMO as names are already clear enough (and then, the tags themselves become unnecessary for most of them thanks to the native signature)

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 22]
```diff
@@ -106,41 +390,313 @@ public function request(string $method, string $url, array $options = []): Respo
...
+     * Checks if the response has an explicit expiration.
+     *
+     * This function will return true if the response has an explicit expiration
+     * time specified in the headers or in the Cache-Control directives,
+     * false otherwise.
+     *
+     * @param array<string, string|string[]> $headers      the HTTP response headers
+     * @param array<string, string|true>     $cacheControl an array of parsed Cache-Control directives
+     *
+     * @return bool true if the response has an explicit expiration, false otherwise
```
Comment (stof) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]: useless return value description as the method description already describes it (and then, the whole `@return` becomes redundant

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 23]
```diff
@@ -106,41 +390,313 @@ public function request(string $method, string $url, array $options = []): Respo
...
+
+    /**
+     * Checks if the response has an explicit expiration.
+     *
+     * This function will return true if the response has an explicit expiration
+     * time specified in the headers or in the Cache-Control directives,
+     * false otherwise.
+     *
+     * @param array<string, string|string[]> $headers      the HTTP response headers
+     * @param array<string, string|true>     $cacheControl an array of parsed Cache-Control directives
```
Comment (stof) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]: I suggest removing the description part of those tags. The argument names are already clear enough IMO.

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 24]
```diff
@@ -106,41 +390,313 @@ public function request(string $method, string $url, array $options = []): Respo
...
+     *
+     * This function will return true if the server response can be cached,
+     * false otherwise.
+     *
+     * @param int                            $statusCode      the HTTP status code of the response
+     * @param array<string, string|string[]> $requestHeaders  the HTTP request headers
+     * @param array<string, string|string[]> $responseHeaders the HTTP response headers
+     * @param array<string, string|true>     $cacheControl    an array of parsed Cache-Control directives
+     *
+     * @return bool true if the response is cacheable, false otherwise
```
Comment (stof) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]: Descriptions for `@param` and `@return` are useless here. the parameter names are already clear enough and the method description already describes the return value (and even that part could be considered useless because the method name is clear about the meaning of the returned boolean)

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 25]
```diff
@@ -11,62 +11,346 @@
...
+        }
+
+        return new ResponseStream((function () use ($mockResponses, $asyncResponses, $clientResponses, $timeout) {
+            yield from MockResponse::stream($mockResponses, $timeout);
+            yield $this->client->stream($clientResponses, $timeout);
+            yield $this->asyncStream($asyncResponses, $timeout);
+        })());
+    }
+
+    public function legacyRequest(string $method, string $url, array $options = []): ResponseInterface
```
Comment (stof) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]: should be private. there is no reason to introduce it as a public method (especially one that is not usable whne the object is constructed in a non-deprecated way)

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php (hunk 14 above)
Comment (Lctrs) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php]: Adressed in https://github.com/symfony/symfony/pull/59576/commits/ec272b9975e8276382ad997e5ba22830ec359773

File: src/Symfony/Component/HttpClient/CHANGELOG.md (hunk 15 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CHANGELOG.md]: Adressed in https://github.com/symfony/symfony/pull/59576/commits/8a0b0340efdc9cae3357bd70c75f1448146cafeb

File: src/Symfony/Component/HttpClient/CachingHttpClient.php (hunk 16 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: Adressed in https://github.com/symfony/symfony/pull/59576/commits/bac8c68cfb863328a36ccd4f70cd2147d7fab26e

File: src/Symfony/Component/HttpClient/CachingHttpClient.php (hunk 17 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: adressed in https://github.com/symfony/symfony/pull/59576/commits/33fb4eaed827cb9521333d165c1399668826807a

File: src/Symfony/Component/HttpClient/CachingHttpClient.php (hunk 18 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: adressed in https://github.com/symfony/symfony/pull/59576/commits/05970b866ae30596e43ab75ca433bbe0bb86044a

File: src/Symfony/Component/HttpClient/CachingHttpClient.php (hunk 25 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: adressed in https://github.com/symfony/symfony/pull/59576/commits/806ddf90397d90569d5fe9e4d6fd5477969cbae7

File: src/Symfony/Component/HttpClient/CachingHttpClient.php (hunk 24 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: adressed in https://github.com/symfony/symfony/pull/59576/commits/b3154e1c1ecf2ad2b1c7b33e95549af3c79e3f4b

File: src/Symfony/Component/HttpClient/CachingHttpClient.php (hunk 23 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php:627]: adressed in https://github.com/symfony/symfony/pull/59576/commits/b3154e1c1ecf2ad2b1c7b33e95549af3c79e3f4b

Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: adressed in https://github.com/symfony/symfony/pull/59576/commits/04d24d392fb6669061e7c01f9f9b270e5e15bdac

File: src/Symfony/Component/HttpClient/CachingHttpClient.php (hunk 22 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: adressed in https://github.com/symfony/symfony/pull/59576/commits/04d24d392fb6669061e7c01f9f9b270e5e15bdac

File: src/Symfony/Component/HttpClient/CachingHttpClient.php (hunk 21 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: adressed in https://github.com/symfony/symfony/commit/b3154e1c1ecf2ad2b1c7b33e95549af3c79e3f4b

File: src/Symfony/Component/HttpClient/CachingHttpClient.php (hunk 20 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: adressed in https://github.com/symfony/symfony/commit/b3154e1c1ecf2ad2b1c7b33e95549af3c79e3f4b

File: src/Symfony/Component/HttpClient/CachingHttpClient.php (hunk 19 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: adressed in https://github.com/symfony/symfony/commit/b3154e1c1ecf2ad2b1c7b33e95549af3c79e3f4b

File: UPGRADE-7.3.md [hunk 26]
```diff
@@ -189,3 +189,8 @@ VarDumper
 
  * Deprecate `ResourceCaster::castCurl()`, `ResourceCaster::castGd()` and `ResourceCaster::castOpensslX509()`
  * Mark all casters as `@internal`
+
+HttpClient
+----------
+
+* Deprecate passing an instance of `StoreInterface` as `$cache` argument to `CachingHttpClient` constructor
```
Comment (alexandre-daubois) [inline UPGRADE-7.3.md]:
```suggestion
 * Deprecate passing an instance of `StoreInterface` as `$cache` argument to `CachingHttpClient` constructor
```

Also please add the `HttpClient` entry in the alphabetical order with other components 🙂

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php [hunk 27]
```diff
@@ -2133,6 +2135,32 @@ private function addHttpClientSection(ArrayNodeDefinition $rootNode, callable $e
...
+                    ->stringNode('cache_pool')
+                        ->info('The taggable cache pool to use for storing the responses.')
+                        ->defaultValue('cache.http_client')
+                        ->cannotBeEmpty()
+                    ->end()
+                    ->booleanNode('shared')
+                        ->info('Indicates whether the cache is shared (public) or private.')
+                        ->defaultTrue()
+                    ->end()
+                    ->integerNode('max_ttl')
```
Comment (alexandre-daubois) [inline src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:2172]: This node should be validated to ensure a positive integer is given, if any

File: src/Symfony/Component/HttpClient/CHANGELOG.md [hunk 28]
```diff
@@ -6,6 +6,7 @@ CHANGELOG
 
  * Add IPv6 support to `NativeHttpClient`
  * Allow using HTTP/3 with the `CurlHttpClient`
+ * Add RFC 9111–based caching support to `CachingHttpClient` (though some features remain partially supported)
```
Comment (alexandre-daubois) [inline src/Symfony/Component/HttpClient/CHANGELOG.md]: > (though some features remain partially supported)

This is something that may be added to the class itself to me, not in the changelog. Or by rephrasing it like "Add RFC 9111–based caching partial support to `CachingHttpClient`"

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 29]
```diff
@@ -11,68 +11,345 @@
...
+        [$fullUrl, $options] = self::prepareRequest($method, $url, $options, $this->defaultOptions);
+
+        $fullUrl = implode('', $fullUrl);
+        $fullUrlTag = hash('xxh3', $fullUrl);
+
+        if (\in_array($method, self::UNSAFE_METHODS, true)) {
+            $this->cache->invalidateTags([$fullUrlTag]);
+        }
+
+        if (!empty($options['body']) || isset($options['normalized_headers']['range']) || !\in_array($method, self::CACHEABLE_METHODS, true)) {
```
Comment (alexandre-daubois) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]:
```suggestion
        if ($options['body'] || isset($options['normalized_headers']['range']) || !\in_array($method, self::CACHEABLE_METHODS, true)) {
```

`empty()` is kind of banned from the codebase, `$options['body']` should be sufficient?

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 30]
```diff
@@ -106,41 +383,298 @@ public function request(string $method, string $url, array $options = []): Respo
...
+
+    /**
+     * Evaluates the freshness of a cached response based on its headers and expiration time.
+     *
+     * This method determines the state of the cached response by analyzing the Cache-Control
+     * directives and the expiration timestamp.
+     *
+     * @param array{headers: array<string, string[]>, expires_at: int|null} $data the cached response data, including headers and expiration time
+     */
+    private function evaluateCachedFreshness(array $data): Freshness
```
Comment (alexandre-daubois) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]:
```suggestion
    private function evaluateCacheFreshness(array $data): Freshness
```

Seems more correct to me

File: UPGRADE-7.3.md (hunk 26 above)
Comment (Lctrs) [reply UPGRADE-7.3.md]: adressed in https://github.com/symfony/symfony/pull/59576/commits/23141cbc8bbc7196d4ca4cac6d18599984459d21

File: src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php (hunk 27 above)
Comment (Lctrs) [reply src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php:2172]: adressed in https://github.com/symfony/symfony/pull/59576/commits/46ce9cb19d25e78acec3a8aa5197236954164dec

File: src/Symfony/Component/HttpClient/CHANGELOG.md (hunk 28 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CHANGELOG.md]: adressed in https://github.com/symfony/symfony/pull/59576/commits/dd9c6cb31a9bf2d458715ce19d9ec6a95971d2de

File: src/Symfony/Component/HttpClient/CachingHttpClient.php (hunk 29 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: adressed in https://github.com/symfony/symfony/pull/59576/commits/ee173e8a09a358467ee302c9443259d047f551e8

File: src/Symfony/Component/HttpClient/CachingHttpClient.php (hunk 30 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: adressed in https://github.com/symfony/symfony/pull/59576/commits/3f0074bba58a4136a14eb1e0c53f76efcbef8731

File: src/Symfony/Component/HttpClient/composer.json [hunk 31]
```diff
@@ -37,7 +37,9 @@
         "php-http/httplug": "^1.0|^2.0",
         "psr/http-client": "^1.0",
         "symfony/amphp-http-client-meta": "^1.0|^2.0",
+        "symfony/cache": "^6.4|^7.0",
         "symfony/dependency-injection": "^6.4|^7.0",
+        "symfony/filesystem": "^6.4|^7.0",
```
Comment (maxhelias) [inline src/Symfony/Component/HttpClient/composer.json]: I don't see any new direct dependency on the filesystem component in this code. Is this an indirect dependency for the cache in tests?

Comment (Lctrs) [reply src/Symfony/Component/HttpClient/composer.json]: It was. I thought I removed it. Adressed in https://github.com/symfony/symfony/pull/59576/commits/18408cfcb50c6568cf693168711fb31772ce6502

**Review by stof — APPROVED** [review]
This looks good to me, but I would appreciate a review from @nicolas-grekas as he's the one knowing this component best.

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 32]
```diff
@@ -11,68 +11,366 @@
...
+    }
     use HttpClientTrait;
 
-    private HttpCache $cache;
+    /**
+     * The status codes that are always cacheable.
+     */
+    private const CACHEABLE_STATUS_CODES = [200, 203, 204, 300, 301, 404, 410];
+    /**
+     * The status codes that are cacheable if the response carry explicit cache directives.
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]:
```suggestion
     * The status codes that are cacheable if the response carries explicit cache directives.
```

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 33]
```diff
@@ -11,68 +11,366 @@
...
     public function request(string $method, string $url, array $options = []): ResponseInterface
+    {
+        if ($this->cache instanceof HttpCache) {
+            return $this->legacyRequest($method, $url, $options);
+        }
+
+        [$fullUrl, $options] = self::prepareRequest($method, $url, $options, $this->defaultOptions);
+
+        $fullUrl = implode('', $fullUrl);
+        $fullUrlTag = hash('xxh3', $fullUrl);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]: two questions here:
- is xxh3 safe enough? eg if the URL comes from a JSON hypermedia document, the URL should be considered user-provided, so we might need a crypto-safe algo here. WDYT?
- let's encode hashes using base64_encode(hash('also', $value, true)) to reduce the length? We could use a more binary-scheme, that'd encode just the PSR6-excluded chars also :thinking:

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 34]
```diff
@@ -11,68 +11,366 @@
...
+
+        if (\in_array($method, self::UNSAFE_METHODS, true)) {
+            $this->cache->invalidateTags([$fullUrlTag]);
+        }
+
+        if ($options['body'] !== '' || isset($options['normalized_headers']['range']) || !\in_array($method, self::CACHEABLE_METHODS, true)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]:
```suggestion
        if ('' !== $options['body'] || isset($options['normalized_headers']['range']) || !\in_array($method, self::CACHEABLE_METHODS, true)) {
```

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 35]
```diff
@@ -11,68 +11,366 @@
...
+        'proxy-authenticate' => true,
+        'proxy-authentication-info' => true,
+        'proxy-authorization' => true,
+    ];
+    /**
+     * Maximum heuristic freshness lifetime in seconds (24 hours).
+     */
+    private const MAX_HEURISTIC_FRESHNESS_TTL = 86400;
+
+    private TagAwareAdapterInterface|HttpCache $cache;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]: Did you consider using TagAwareCacheInterface instead? That could allow merging/locking concurrent requests, possibly?

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 36]
```diff
@@ -11,68 +11,366 @@
...
+            if (isset($cachedData['headers']['last-modified'][0])) {
+                $options['headers']['If-Modified-Since'] = $cachedData['headers']['last-modified'][0];
+            }
+        }
+
+        $chunkIndex = -1;
+        // consistent expiration time for all items
+        $expiresAt = null === $this->maxTtl
+            ? null
+            : \DateTimeImmutable::createFromFormat('U', time() + $this->maxTtl);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]:
```suggestion
        $expiresAt = null === $this->maxTtl ? null : \DateTimeImmutable::createFromFormat('U', time() + $this->maxTtl);
```

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 37]
```diff
@@ -106,41 +404,319 @@ public function request(string $method, string $url, array $options = []): Respo
...
+     * @return string the metadata key composed of the request hash and variant key
+     */
+    private function getMetadataKey(string $requestHash, array $normalizedHeaders, array $varyFields): string
+    {
+        $variantKey = hash(
+            'xxh3',
+            [] === $varyFields
+                ? 'NO-VARY'
+                : $this->buildVariantKey($normalizedHeaders, $varyFields)
+        );
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]: not sure we need a special case for the empty-vary state:
```suggestion
        $variantKey = hash('xxh3', $this->buildVariantKey($normalizedHeaders, $varyFields));
```

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 38]
```diff
@@ -106,41 +404,319 @@ public function request(string $method, string $url, array $options = []): Respo
...
+    private function createResponseFromCache(string $key, array $cachedData, string $method, string $url, array $options, string $fullUrlTag): MockResponse
+    {
+        return MockResponse::fromRequest(
+            $method,
+            $url,
+            $options,
+            new MockResponse(
+                (function () use ($key, $cachedData, $fullUrlTag): \Generator {
+                    for ($i = 0; $i <= $cachedData['chunks_count']; ++$i) {
+                        $chunkItem = $this->cache->getItem("{$key}_chunk_{$i}");
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]: maybe make the closure static and "use" `$cache`?

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 39]
```diff
@@ -11,68 +11,366 @@
...
+            ? null
+            : \DateTimeImmutable::createFromFormat('U', time() + $this->maxTtl);
+
+        return new AsyncResponse(
+            $this->client,
+            $method,
+            $url,
+            $options,
+            function (ChunkInterface $chunk, AsyncContext $context) use (
+                &$chunkIndex,
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]: I think some vars used by reference can be turned into static variables inside the closure. That might be a bit cleaner to me.

**Review by nicolas-grekas — COMMENTED** [review]
Looks nice thanks! Here are some comments.

File: src/Symfony/Component/HttpClient/CachingHttpClient.php (hunk 38 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: `$cache` is a property of the class so we can't use "use" it in a closure. Do you mean you want to introduce a temp variable (eg. `$cache = $this->cache`) for it that I can then use in the closure ? I frankly don't understand why but if that's what you meant, I'll do it.

File: src/Symfony/Component/HttpClient/CachingHttpClient.php (hunk 33 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: I haven't considered this. I'll switch to `sha256`, that should be enough to avoid any risk of collisions.

Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: Adressed

File: src/Symfony/Component/HttpClient/CachingHttpClient.php (hunk 35 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: Adressed

File: src/Symfony/Component/HttpClient/CachingHttpClient.php (hunk 39 above)
Comment (Lctrs) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: Adressed

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 40]
```diff
@@ -11,68 +11,365 @@
...
+        if ('' !== $options['body'] || isset($options['normalized_headers']['range']) || !\in_array($method, self::CACHEABLE_METHODS, true)) {
+            return new AsyncResponse($this->client, $method, $url, $options);
+        }
+
+        $requestHash = self::hash($method.$fullUrl);
+        $varyKey = "vary_{$requestHash}";
+        $varyFields = $this->cache->get($varyKey, static fn (): array => []);
+
+        $metadataKey = self::getMetadataKey($requestHash, $options['normalized_headers'], $varyFields);
+        $cachedData = $this->cache->get($metadataKey, static fn (): null => null);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]: do we want to save the null value in the backed on a miss?
if not, we should use the $save argument passed by ref to the closure:
```suggestion
        $cachedData = $this->cache->get($metadataKey, fn ($item, &$save) => $save = false;)
```

Comment (nicolas-grekas) [reply src/Symfony/Component/HttpClient/CachingHttpClient.php]: (the same concern should be consider everywhere get() is used)

**Review by fabpot — COMMENTED** [review]
How does the code behave when there is 2 concurrent requests for the same URL where one request is creating the cache while the other tries to get the cache? At the bare minimum, maybe we should lock the key? 
Also, maybe the implementation should take into account the fact that we could implement `stale-while-revalidate` support later on.

**Comment by nicolas-grekas** [comment]
Not sure about locking as a first step, maybe just some pointer would be enough: while writing, we use some random key name, and once the cache is populated, we update some other pointer key, this one predictably derived from the request. When the cache is stale or empty, that'd mean writing many concurrent streams to the cache backend for the same request, until one finished and wins of the others. No ideal, but at least correct from a behavioral perspective.
The next step would be to wrap everything in one may $cache->get() callback, which would the act as the lock unit, possibly capable of serving something while revalidating and/or waiting/streaming while the concurrent write thread is doing its job. I'd be fine doing this next step in a follow up PR if that's too involving for this one.

**Comment by nicolas-grekas** [comment]
@Lctrs WDYT of our comments? Difficult topic :)

**Review by stof — APPROVED** [review]
Looks good to me, but I'd like a review from @nicolas-grekas as he is the one knowing symfony/http-client best.

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 41]
```diff
@@ -11,55 +11,131 @@
...
+        TagAwareCacheInterface|StoreInterface $cache,
         array $defaultOptions = [],
+        private readonly bool $sharedCache = true,
+        private readonly ?int $maxTtl = null,
     ) {
-        if (!class_exists(HttpClientKernel::class)) {
-            throw new \LogicException(\sprintf('Using "%s" requires the HttpKernel component, try running "composer require symfony/http-kernel".', __CLASS__));
-        }
+        if ($cache instanceof StoreInterface) {
+            trigger_deprecation('symfony/http-client', '7.3', 'Passing a "%s" as constructor\'s 2nd argument of "%s" is deprecated, "%s" expected.', StoreInterface::class, __CLASS__, TagAwareCacheInterface::class);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]:
```suggestion
            trigger_deprecation('symfony/http-client', '7.4', 'Passing a "%s" as constructor\'s 2nd argument of "%s" is deprecated, "%s" expected.', StoreInterface::class, __CLASS__, TagAwareCacheInterface::class);
```

File: src/Symfony/Component/HttpClient/CHANGELOG.md [hunk 42]
```diff
@@ -5,6 +5,7 @@ CHANGELOG
 ---
 
  * Deprecate using amphp/http-client < 5
+ * Add RFC 9111–based caching support to `CachingHttpClient`
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CHANGELOG.md:8]: let's mention the deprecation also
```
 * Deprecate passing an instance of `StoreInterface` as `$cache` argument to `CachingHttpClient` constructor
```

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 43]
```diff
@@ -68,11 +144,253 @@ public function __construct(
...
+
+        if (\in_array($method, self::UNSAFE_METHODS, true)) {
+            $this->cache->invalidateTags([$fullUrlTag]);
+        }
+
+        if ('' !== $options['body'] || ($options['extra']['no_cache'] ?? false) || !\in_array($method, self::CACHEABLE_METHODS, true)) {
+            return new AsyncResponse($this->client, $method, $url, $options);
+        }
+
+        $requestHash = self::hash($method.$fullUrl.json_encode(array_intersect_key($options['normalized_headers'], self::RESPONSE_INFLUENCING_HEADERS), \JSON_THROW_ON_ERROR));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]: serialize instead of json_encode to work with non-utf8 chars?

**Review by nicolas-grekas — APPROVED** [review]
I didn't get into all details but still LGTM thanks!

**Comment by nicolas-grekas** [comment]
Can you please maybe expand in the PR description? Think about a blog post we could derive from it :)

**Comment by Lctrs** [comment]
I'm currently on holiday. I'll get back to it next week. Including my thoughts on possible race conditions discussed earlier. 

> Can you please maybe expand in the PR description? Think about a blog post we could derive from it :)

May you be more specific ? You want me to explain the code ?

**Comment by nicolas-grekas** [comment]
What we could put in the doc about it yes (thus not internal details of course)

**Comment by Lctrs** [comment]
@nicolas-grekas Done. Hope it's what you had in mind.

About concurrent requests, due to the async nature of the implementation - and unless I'm missing something -, wrapping everything in a `$cache->get()` call won't do the trick. We may have to bring `symfony/lock` to the party to implement request coalescing.

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 44]
```diff
@@ -68,11 +145,253 @@ public function __construct(
...
+
+                            return;
+                        }
+                    }
+
+                    // recomputing vary fields in case it changed or for first request
+                    $varyFields = [];
+                    foreach ($headers['vary'] ?? [] as $vary) {
+                        foreach (explode(',', $vary) as $field) {
+                            $varyFields[] = trim($field);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]:
```suggestion
                            $field = strtolower(trim($field));
                            if ('cookie' === $field ? $this->sharedCache : !preg_match('^[!#$%&\'*+\-.^_`|~0-9A-Za-z]+$D', $field)) {
                                $field = '*';
                            }
                            $varyFields[] = $field;
```

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 45]
```diff
@@ -106,41 +425,307 @@ public function request(string $method, string $url, array $options = []): Respo
...
+                $joined = \is_array($normalizedHeaders[$lower])
+                    ? implode(',', $normalizedHeaders[$lower])
+                    : $normalizedHeaders[$lower];
+                $parts[] = $field.'='.rawurlencode($joined);
             }
         }
 
-        if (!$mockResponses) {
-            return $this->client->stream($clientResponses, $timeout);
+        return implode('|', $parts);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]:
```suggestion
            if (!isset($normalizedHeaders[$lower])) {
                $parts[$lower] = $lower.'=';
            } else {
                $parts[$lower] = $lower.'='.implode(',', array_map('rawurlencode', (array) $normalizedHeaders[$lower]));
            }
        }
        ksort($parts);

        return implode('&', $parts);
```

**Review by nicolas-grekas — COMMENTED** [review]
I'm proposing to be a bit stricter about vary computation, see comments.

About concurrent requests, I understand that the cached response will become available only after the last chunk has been received. This means the concurrency model is: duplicate requests until one completes. That's totally fine to me.
There's just one issue I think: during this warmup phase, two concurrent requests can corrupt the chunks of the other one.
We could fix this by adding a random value in the chunk cache, stored also in the final item, so that we can be sure we're dealing with the correct chain of chunks.
Does this make sense?

<details>

<summary>Here are some CS improvements as a patch.</summary>

```diff
diff --git a/src/Symfony/Component/HttpClient/CachingHttpClient.php b/src/Symfony/Component/HttpClient/CachingHttpClient.php
index 87fae82c95a..8127e4ac205 100644
--- a/src/Symfony/Component/HttpClient/CachingHttpClient.php
+++ b/src/Symfony/Component/HttpClient/CachingHttpClient.php
@@ -164,21 +164,13 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
 
         $requestHash = self::hash($method.$fullUrl.serialize(array_intersect_key($options['normalized_headers'], self::RESPONSE_INFLUENCING_HEADERS)));
         $varyKey = "vary_{$requestHash}";
-        $varyFields = $this->cache->get($varyKey, static function (ItemInterface $item, bool &$save): array {
-            $save = false;
-
-            return [];
-        }, 0);
+        $varyFields = $this->cache->get($varyKey, static fn ($item, &$save): array => ($save = false) ?: [], 0);
 
         $metadataKey = self::getMetadataKey($requestHash, $options['normalized_headers'], $varyFields);
-        $cachedData = $this->cache->get($metadataKey, static function (ItemInterface $item, bool &$save): null {
-            $save = false;
-
-            return null;
-        });
+        $cachedData = $this->cache->get($metadataKey, static fn ($item, &$save): array => ($save = false) ?: [], 0);
 
         $freshness = null;
-        if (\is_array($cachedData)) {
+        if ($cachedData) {
             $freshness = $this->evaluateCacheFreshness($cachedData);
 
             if (Freshness::Fresh === $freshness) {
 
@@ -433,11 +429,11 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
     /**
      * Generates a unique metadata key based on the request hash and varying headers.
      *
-     * @param string                         $requestHash       a hash representing the request details
-     * @param array<string, string|string[]> $normalizedHeaders normalized headers of the request
-     * @param string[]                       $varyFields        headers to consider for building the variant key
+     * @param string                         $requestHash       A hash representing the request details
+     * @param array<string, string|string[]> $normalizedHeaders Normalized headers of the request
+     * @param string[]                       $varyFields        Headers to consider for building the variant key
      *
-     * @return string the metadata key composed of the request hash and variant key
+     * @return string The metadata key composed of the request hash and variant key
      */
     private static function getMetadataKey(string $requestHash, array $normalizedHeaders, array $varyFields): string
     {
@@ -449,7 +445,8 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
     /**
      * Build a variant key for caching, given an array of normalized headers and the vary fields.
      *
-     * The key is a pipe-separated string of "header=value" pairs, with the special case of "header=" for headers that are not present.
+     * The key is a pipe-separated string of "header=value" pairs, with
+     * the special case of "header=" for headers that are not present.
      *
      * @param array<string, string|string[]> $normalizedHeaders
      * @param string[]                       $varyFields
@@ -460,25 +457,23 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
     /**
      * Parse the Cache-Control header and return an array of directive names as keys
      * and their values as values, or true if the directive has no value.
      *
-     * @param array<string, string|string[]> $header the Cache-Control header as an array of strings
+     * @param array<string, string|string[]> $header The Cache-Control header as an array of strings
      *
-     * @return array<string, string|true> the parsed Cache-Control directives
+     * @return array<string, string|true> The parsed Cache-Control directives
      */
     private static function parseCacheControlHeader(array $header): array
     {
@@ -503,7 +498,7 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
      * This method determines the state of the cached response by analyzing the Cache-Control
      * directives and the expiration timestamp.
      *
-     * @param array{headers: array<string, string[]>, expires_at: int|null} $data the cached response data, including headers and expiration time
+     * @param array{headers: array<string, string[]>, expires_at: int|null} $data The cached response data, including headers and expiration time
      */
     private function evaluateCacheFreshness(array $data): Freshness
     {
@@ -547,14 +542,12 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
      * the Expires header for a valid timestamp, and if present, returns the
      * difference between the timestamp and the current time minus the current age.
      *
-     * If none of the above directives or headers are present, the method returns
-     * null.
+     * If none of the above directives or headers are present, the method returns null.
      *
-     * @param array<string, string|string[]> $headers      an array of HTTP headers
-     * @param array<string, string|true>     $cacheControl an array of parsed Cache-Control directives
+     * @param array<string, string|string[]> $headers      An array of HTTP headers
+     * @param array<string, string|true>     $cacheControl An array of parsed Cache-Control directives
      *
-     * @return int|null the maximum age of the response, or null if it cannot be
-     *                  determined
+     * @return int|null The maximum age of the response, or null if it cannot be determined
      */
     private function determineMaxAge(array $headers, array $cacheControl): ?int
     {
@@ -608,9 +601,9 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
     /**
      * Retrieves the current age of the response from the headers.
      *
-     * @param array<string, string|string[]> $headers an array of HTTP headers
+     * @param array<string, string|string[]> $headers An array of HTTP headers
      *
-     * @return int The age of the response in seconds. Defaults to 0 if not present.
+     * @return int The age of the response in seconds, defaults to 0 if not present
      */
     private static function getCurrentAge(array $headers): int
     {
@@ -620,9 +613,9 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
     /**
      * Calculates the expiration time of the response given the maximum age.
      *
-     * @param int|null $maxAge the maximum age of the response in seconds, or null if it cannot be determined
+     * @param int|null $maxAge The maximum age of the response in seconds, or null if it cannot be determined
      *
-     * @return int|null the expiration time of the response as a Unix timestamp, or null if the maximum age is null
+     * @return int|null The expiration time of the response as a Unix timestamp, or null if the maximum age is null
      */
     private static function calculateExpiresAt(?int $maxAge): ?int
     {
@@ -646,7 +639,6 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
      */
     private function isServerResponseCacheable(int $statusCode, array $requestHeaders, array $responseHeaders, array $cacheControl): bool
     {
-        // no-store => skip caching
         if (isset($cacheControl['no-store'])) {
             return false;
         }
@@ -700,32 +692,28 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
      */
     private function createResponseFromCache(string $key, array $cachedData, string $method, string $url, array $options, string $fullUrlTag): MockResponse
     {
-        return MockResponse::fromRequest(
-            $method,
-            $url,
-            $options,
-            new MockResponse(
-                (function () use ($key, $cachedData, $fullUrlTag): \Generator {
-                    for ($i = 0; $i <= $cachedData['chunks_count']; ++$i) {
-                        yield $this->cache->get("{$key}_chunk_{$i}", function (ItemInterface $item) use ($fullUrlTag): never {
-                            $this->cache->invalidateTags([$fullUrlTag]);
-
-                            throw new ChunkCacheItemNotFoundException(\sprintf('Missing cache item for chunk with key "%s". This indicates an internal cache inconsistency.', $item->getKey()));
-                        }, 0);
-                    }
-                })(),
-                ['http_code' => $cachedData['status_code'], 'response_headers' => ['age' => $cachedData['initial_age'] + (time() - $cachedData['stored_at'])] + $cachedData['headers']]
-            )
-        );
+        $cache = $this->cache;
+        $callback = static function (ItemInterface $item) use ($cache, $fullUrlTag): never {
+            $cache->invalidateTags([$fullUrlTag]);
+
+            throw new ChunkCacheItemNotFoundException(\sprintf('Missing cache item for chunk with key "%s". This indicates an internal cache inconsistency.', $item->getKey()));
+        };
+        $body = static function () use ($cache, $key, $cachedData, $callback): \Generator {
+            for ($i = 0; $i <= $cachedData['chunks_count']; ++$i) {
+                yield $cache->get("{$key}_chunk_{$i}", $callback, 0);
+            }
+        };
+
+        return MockResponse::fromRequest($method, $url, $options, new MockResponse($body(), [
+            'http_code' => $cachedData['status_code'],
+            'response_headers' => [
+                'age' => $cachedData['initial_age'] + (time() - $cachedData['stored_at']),
+            ] + $cachedData['headers'],
+        ]));
     }
 
     private static function createGatewayTimeoutResponse(string $method, string $url, array $options): MockResponse
     {
-        return MockResponse::fromRequest(
-            $method,
-            $url,
-            $options,
-            new MockResponse('', ['http_code' => 504])
-        );
+        return MockResponse::fromRequest($method, $url, $options, new MockResponse('', ['http_code' => 504]));
     }
 }
```

</details>

**Comment by Lctrs** [comment]
> About concurrent requests, I understand that the cached response will become available only after the last chunk has been received. This means the concurrency model is: duplicate requests until one completes. That's totally fine to me.
There's just one issue I think: during this warmup phase, two concurrent requests can corrupt the chunks of the other one.
We could fix this by adding a random value in the chunk cache, stored also in the final item, so that we can be sure we're dealing with the correct chain of chunks.
Does this make sense?

I don't think the probability of having different responses for doing the 2 same requests in a very short time span is very high but who knows ?

That being said, the only reason the cached response is made available at the last chunk is because of the chunks count. If we change the logic of the reconstitution of cached responses' content by turning the chunks' cache entry as a linked list (ie. `array{content: string, next_chunk: string|null}`, we could make it work by generating a random id or using chunks' offsets), we could write status code, headers, etc. of the response in the cache in the first chunk (`chunks_count` would be replaced by `first_chunk` pointing to the key of the first chunk in the cache). I believe this would make it easier to implement request coalescing.

**Comment by nicolas-grekas** [comment]
Linked list works for me too. I'd just not use offsets as it's always possible for two concurrent requests to yield different chunks.

**Comment by Lctrs** [comment]
@nicolas-grekas done.

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 46]
```diff
@@ -106,41 +432,308 @@ public function request(string $method, string $url, array $options = []): Respo
...
+                if (false !== $lastModifiedTimestamp) {
+                    $secondsSinceLastModified = time() - $lastModifiedTimestamp;
+                    if ($secondsSinceLastModified > 0) {
+                        // Heuristic: 10% of time since last modified, capped at max heuristic freshness
+                        $heuristicFreshnessSeconds = (int) ($secondsSinceLastModified * 0.1);
+                        $cappedHeuristicFreshness = min($heuristicFreshnessSeconds, self::MAX_HEURISTIC_FRESHNESS_TTL);
+
+                        return max(0, $cappedHeuristicFreshness - $age);
+                    }
+                }
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]:
```suggestion
                if (false === $lastModifiedTimestamp = strtotime($lastModified)) {
                    continue;
                }
                if (0 < $secondsSinceLastModified = time() - $lastModifiedTimestamp) {
                    // Heuristic: 10% of time since last modified, capped at max heuristic freshness
                    $heuristicFreshnessSeconds = (int) ($secondsSinceLastModified * 0.1);
                    $cappedHeuristicFreshness = min($heuristicFreshnessSeconds, self::MAX_HEURISTIC_FRESHNESS_TTL);

                    return max(0, $cappedHeuristicFreshness - $age);
                }
```

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 47]
```diff
@@ -106,41 +432,308 @@ public function request(string $method, string $url, array $options = []): Respo
...
+
+        if (isset($cacheControl['max-age'])) {
+            $maxAge = (int) $cacheControl['max-age'];
+
+            return max(0, $maxAge - $age);
+        }
+
+        foreach ($headers['expires'] ?? [] as $expire) {
+            $expirationTimestamp = strtotime($expire);
+            if (false !== $expirationTimestamp) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]:
```suggestion
            if (false !== $expirationTimestamp = strtotime($expire)) {
```

File: src/Symfony/Component/HttpClient/CachingHttpClient.php [hunk 48]
```diff
@@ -106,41 +432,308 @@ public function request(string $method, string $url, array $options = []): Respo
...
+        if (
+            isset($parseCacheControlHeader['must-revalidate'])
+            || ($this->sharedCache && isset($parseCacheControlHeader['proxy-revalidate']))
+        ) {
+            return Freshness::MustRevalidate;
+        }
+
+        if (isset($parseCacheControlHeader['stale-if-error'])) {
+            $staleWindow = (int) $parseCacheControlHeader['stale-if-error'];
+            if (($now - $expires) <= $staleWindow) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpClient/CachingHttpClient.php]:
```suggestion
            if (($now - $expires) <= $staleWindow = (int) $parseCacheControlHeader['stale-if-error']) {
```

**Review by nicolas-grekas — COMMENTED** [review]
<details>

<summary>We can reduce the storage requirements a bit this way.</summary>

```diff
diff --git a/src/Symfony/Component/HttpClient/CachingHttpClient.php b/src/Symfony/Component/HttpClient/CachingHttpClient.php
index 7e021c1b3cd..714ee889cb9 100644
--- a/src/Symfony/Component/HttpClient/CachingHttpClient.php
+++ b/src/Symfony/Component/HttpClient/CachingHttpClient.php
@@ -174,7 +174,7 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
             $freshness = $this->evaluateCacheFreshness($cachedData);
 
             if (Freshness::Fresh === $freshness) {
-                return $this->createResponseFromCache($cachedData, $method, $url, $options, $fullUrlTag);
+                return $this->createResponseFromCache($metadataKey, $cachedData, $method, $url, $options, $fullUrlTag);
             }
 
             if (isset($cachedData['headers']['etag'])) {
@@ -213,7 +213,7 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
                         // avoid throwing exception in ErrorChunk#__destruct()
                         $chunk instanceof ErrorChunk && $chunk->didThrow(true);
                         $context->passthru();
-                        $context->replaceResponse($this->createResponseFromCache($cachedData, $method, $url, $options, $fullUrlTag));
+                        $context->replaceResponse($this->createResponseFromCache($metadataKey, $cachedData, $method, $url, $options, $fullUrlTag));
 
                         return;
                     }
@@ -253,7 +253,7 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
                         }, \INF);
 
                         $context->passthru();
-                        $context->replaceResponse($this->createResponseFromCache($cachedData, $method, $url, $options, $fullUrlTag));
+                        $context->replaceResponse($this->createResponseFromCache($metadataKey, $cachedData, $method, $url, $options, $fullUrlTag));
 
                         return;
                     }
@@ -261,7 +261,7 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
                     if ($statusCode >= 500 && $statusCode < 600) {
                         if (Freshness::StaleButUsable === $freshness) {
                             $context->passthru();
-                            $context->replaceResponse($this->createResponseFromCache($cachedData, $method, $url, $options, $fullUrlTag));
+                            $context->replaceResponse($this->createResponseFromCache($metadataKey, $cachedData, $method, $url, $options, $fullUrlTag));
 
                             return;
                         }
@@ -310,7 +310,7 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
 
                     $metadataKey = self::getMetadataKey($requestHash, $options['normalized_headers'], $varyFields);
                     $maxAge = $this->determineMaxAge($headers, $cacheControl);
-                    $chunkKey = "{$metadataKey}_chunk_".bin2hex(random_bytes(8));
+                    $chunkKey = str_replace('/', '_', base64_encode(random_bytes(6)));
 
                     $this->cache->get($metadataKey, static function (ItemInterface $item) use ($context, $headers, $maxAge, $expiresAt, $fullUrlTag, $chunkKey): array {
                         $item->tag($fullUrlTag)->expiresAt($expiresAt);
@@ -321,7 +321,7 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
                             'initial_age' => (int) ($headers['age'][0] ?? 0),
                             'stored_at' => time(),
                             'expires_at' => self::calculateExpiresAt($maxAge),
-                            'first_chunk' => $chunkKey,
+                            'next_chunk' => $chunkKey,
                         ];
                     }, \INF);
 
@@ -330,8 +330,15 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
                     return;
                 }
 
+                if (null === $chunkKey) {
+                    // informational chunks
+                    yield $chunk;
+
+                    return;
+                }
+
                 if ($chunk->isLast()) {
-                    $this->cache->get($chunkKey, static function (ItemInterface $item) use ($expiresAt, $fullUrlTag, $chunk): array {
+                    $this->cache->get($metadataKey.'_'.$chunkKey, static function (ItemInterface $item) use ($expiresAt, $fullUrlTag, $chunk): array {
                         $item->tag($fullUrlTag)->expiresAt($expiresAt);
 
                         return [
@@ -345,8 +352,8 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
                     return;
                 }
 
-                $nextChunkKey = "{$metadataKey}_chunk_".bin2hex(random_bytes(8));
-                $this->cache->get($chunkKey, static function (ItemInterface $item) use ($expiresAt, $fullUrlTag, $chunk, $nextChunkKey): array {
+                $nextChunkKey = str_replace('/', '_', base64_encode(random_bytes(6)));
+                $this->cache->get($metadataKey.'_'.$chunkKey, static function (ItemInterface $item) use ($expiresAt, $fullUrlTag, $chunk, $nextChunkKey): array {
                     $item->tag($fullUrlTag)->expiresAt($expiresAt);
 
                     return [
@@ -700,9 +707,9 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
      * response headers and content. The constructed MockResponse is then
      * returned.
      *
-     * @param array{first_chunk: string, status_code: int, initial_age: int, headers: array<string, string|string[]>, stored_at: int} $cachedData
+     * @param array{next_chunk: string, status_code: int, initial_age: int, headers: array<string, string|string[]>, stored_at: int} $cachedData
      */
-    private function createResponseFromCache(array $cachedData, string $method, string $url, array $options, string $fullUrlTag): MockResponse
+    private function createResponseFromCache(string $metadataKey, array $cachedData, string $method, string $url, array $options, string $fullUrlTag): MockResponse
     {
         $cache = $this->cache;
         $callback = static function (ItemInterface $item) use ($cache, $fullUrlTag): never {
@@ -710,13 +717,13 @@ class CachingHttpClient implements HttpClientInterface, ResetInterface
 
             throw new ChunkCacheItemNotFoundException(\sprintf('Missing cache item for chunk with key "%s". This indicates an internal cache inconsistency.', $item->getKey()));
         };
-        $body = static function () use ($cache, $cachedData, $callback): \Generator {
-            $chunk = $cache->get($cachedData['first_chunk'], $callback, 0);
+        $body = static function () use ($cache, $cachedData, $metadataKey, $callback): \Generator {
+            $chunk = $cache->get($metadataKey.'_'.$cachedData['next_chunk'], $callback, 0);
 
             yield $chunk['content'];
 
             while (null !== $chunk['next_chunk']) {
-                $chunk = $cache->get($chunk['next_chunk'], $callback, 0);
+                $chunk = $cache->get($metadataKey.'_'.$chunk['next_chunk'], $callback, 0);
 
                 if ('' !== $chunk['content']) {
                     yield $chunk['content'];
```

</details>

BUT, the latest iteration changed the concurrency model: now, 2nd concurrent requests will hit the cache, and will inevitably fail, because consuming from the cache should be much faster than populating it from the 1st request.

I was more comfortable with the previous model that committed to the cache only when the last chunk was reached. Also because that plays better with canceled requests.

BTW, this makes me realize that if an error happens in the middle of populating the chunks, we should invalidate them all I suppose.

**Comment by Lctrs** [comment]
@nicolas-grekas I reverted to commit the cache on last chunk. I also tweaked the cases when we want to clear the cache.

**Review by fabpot — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @Lctrs.

**Comment by nicolas-grekas** [comment]
Months of work, congrats for the achievement!
