### PR TITLE
[Loco] Fix Loco Provider ID and pull & push local messages reading

### LINKED ISSUE #42395: [Translation] With Loco provider, push command replaces dots with hyphens
**Symfony version(s) affected**: 5.3.6

**Description**
When uploading to Loco by using `push` command, it appears (in Loco dashboard) dots have been replaced by hyphens, as `push` command seems to do this replacement and then fails once `pull` is done

**How to reproduce**
1. Create a project and install: `composer require symfony/translation` and Loco package by `composer require symfony/loco-translation-provider` and add configuration for _locales_ and _domains_ in `translations.yaml`. Also create a project in Loco (localise.biz) and configure its `API_KEY` for **read and write permissions** and place it in `.env` file (`LOCO_DSN`)
2. Create one controller and use `TranslatorInterface` to have at least one translatable keystring (with dots)
3. In the console: `debug/translation` to confirm there are missing strings (one in this case)
4. In the console: `symfony console translation:update en --force` to generate the local file under `translations` folder
5. In the console: `translation:push` to upload to Loco
6. Check in Loco that it was uploaded and appears incorrectly with hyphens and not with dots

**Additional context**
In the controller we have this line: `$translated = $translator->trans('index.home.msg');`

In the generated translations file under `/translations` folder we have these lines:
```
      <trans-unit id="FNdkzeB" resname="index.home.msg">
        <source>index.home.msg</source>
        <target>__index.home.msg</target>
      </trans-unit>
```

And in Loco we have this capture:
Captura de pantalla 2021-08-05 a las 21 00 26

### PR DESCRIPTION
**Pull request by welcoMattic**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix https://github.com/symfony/symfony/issues/42395 & https://github.com/symfony/symfony/issues/43954
| License       | MIT
| Doc PR        | 

It fixes Loco push new messages and avoiding Loco auto-generation of ID for each new messages (which use dash notation instead of dot notation IIRC).

And it fixes also the Translation push & pull commands when they read local messages for multiple domains.

### CODE REVIEW

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @welcoMattic.

**Comment by welcoMattic** [comment]
@fabpot I just realized that I opened this PR on 5.4 instead of 5.3, since it is a bugfix. Sorry

File: src/Symfony/Component/Translation/Bridge/Loco/LocoProvider.php [hunk 1]
```diff
@@ -171,6 +171,7 @@ private function createAssets(array $keys): array
         foreach ($keys as $key) {
             $responses[$key] = $this->client->request('POST', 'assets', [
                 'body' => [
+                    'id' => $key,
```
Comment (stof) [inline src/Symfony/Component/Translation/Bridge/Loco/LocoProvider.php:174]: be careful. Translation keys are only unique per domain, not globally. so they might note be suitable as loco ids.

Comment (welcoMattic) [reply src/Symfony/Component/Translation/Bridge/Loco/LocoProvider.php:174]: You are right, so may be we can concatenate the domain as prefix or suffix to the key?
