### PR TITLE
[AssetMapper] Fix `JavaScriptImportPathCompiler` regex for non-latin characters

### LINKED ISSUE #58657: [AssetMapper] JavaScriptImportPathCompiler regex breaks on non-latin characters
### Symfony version(s) affected

all

### Description

I was trying to serve the assets of a compiled Angular application thanks to the AssetMapper in order to have small units of Angular on my pages without having a full Angular application.

Things were working pretty well until I got one of my imported chunks not compiled into the importmap, resulting in a 404 when the chunk was imported.

After a few investigations, I found out that it was because Angular have some functions with a name like `ɵɵdefineComponent`, with Greek letters, and that these letters are preventing the regex from doing a proper job.

### How to reproduce

1. Follow the installation of AssetMapper as explained in Symfony documentation
2. Create a new file `assets/dependency.js` with a method name `ɵmyMethod`
3. At the top of `app.js` add `import { ɵmyMethod } from './dependency.js'`

=> Look at the importmap generated in the DOM, the file `dependency.js` was not added to it

### Possible Solution

Just adding the unicode character matcher `\p{L}` along with the already existing `\w\s{},*` seems to work pretty well as shown in these two regex :  

**Existing regex (link available in the JavaScriptImportPathCompiler code) where I added a `ɵ` in the imported function name :** https://regex101.com/r/oqY4Ck/1

**Fixed regex with `\p{L}` :** https://regex101.com/r/dxEXjq/2

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by GregRbs92**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58657
| License       | MIT

Update the regex in `JavaScriptImportPathCompiler` so that imported functions having non-latin characters still match the regex.

### Example

```
import { ɵmyFunction } from './others.js'
```

The code above was not working prio to this fix, because of the `ɵ`

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Review by mtarld — APPROVED** [review]

File: src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php [hunk 1]
```diff
@@ -42,7 +42,7 @@ final class JavaScriptImportPathCompiler implements AssetCompilerInterface
             (?:                            # Import statements (script captured)
                 import\s*
                     (?:
-                        (?:\*\s*as\s+\w+|\s+[\w\s{},*]+)
+                        (?:\*\s*as\s+\w+|\s+[\p{L}\w\s{},*]+)
```
Comment (nicolas-grekas) [inline src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php]: I don't know which encoding PCRE uses when the `u` modifier isn't set, but this doesn't work with e.g. character `é`.
I think the correct patch is to add the `u` modifier when the input is UTF-8 and contains non-ascii chars:
`self::IMPORT_PATTERN.(preg_match('{[^\\x00-\\x7F]}u') ? 'u' : '')`
then this change here should be reverted

File: src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php [hunk 2]
```diff
@@ -50,7 +50,7 @@ final class JavaScriptImportPathCompiler implements AssetCompilerInterface
             )
             \s*[\'"`](\.\/[^\'"`\n]++|(\.\.\/)*+[^\'"`\n]++)[\'"`]\s*[;\)]
         ?
-    /mx';
+    /mxu';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/AssetMapper/Compiler/JavaScriptImportPathCompiler.php:53]: This will break parsing non UTF8 files. My previous suggestion was made to handle such cases.
We can merge as is and wait for someone to fill in a bug, maybe UTF-8 is the only encoding found in practice?
:shrug:

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @GregRbs92.
