### PR TITLE
[Mime] allow non-ASCII characters in local part of email

### LINKED ISSUE #34932: [Mime] Email address with non-ascii characters not supported
**Symfony version(s) affected**: 4.3.8

**Description**  
With the component Symfony/Mime, it seems not possible to use email address with non ascii characters.

For example, if try to send an email for the address `stöff@yopmail.com` or `ßert@yopmail.com` the error `Non-ASCII characters not supported in local-part os "<email>"` occurs.

**How to reproduce**  
The bug is simple to reproduce. Install with composer the component Symfony/Mailer in your project and copy/paste this code below : 

```php
<?php 

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Mime\Email;
use Symfony\Component\Mailer\Mailer;
use Symfony\Component\Mailer\Transport\Smtp\EsmtpTransport;

$email = (new Email())
    ->from('hello@example.com')
    ->to('Stöff@yopmail.com')
    ->subject('Time for Symfony Mailer!')
    ->text('Sending emails is fun again!');

$transport = new EsmtpTransport('localhost');
$mailer = new Mailer($transport);
$mailer->send($email);
```

**Possible Solution**  
In the class `Symfony\Component\Mime\Encoder\IdnAddressEncoder` there are references to the class `Utf8AddressEncoder` and the class `SmtpUtf8Handler`.
But these classes does not exist into the project `Symfony/Mime` but exist into the project `Swiftmailer`.

I think we can use some elements of this pull request to fix this problem : https://github.com/swiftmailer/swiftmailer/pull/1056/files

**Additional context**  
None

### PR DESCRIPTION
**Pull request by dmaicher**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | https://github.com/symfony/symfony/issues/34932
| License       | MIT
| Doc PR        | -

This fixes https://github.com/symfony/symfony/issues/34932 by allowing non-ASCII characters in the local part of emails.

I tried this using 3 different smtp servers (gmail, mailgun and local postfix) and for me this just works in case there are non-ASCII characters in the local part of emails. Emails are correctly delivered.

PHPMailer does this in the same way: https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L1411

This is also in line with the behavior of Swiftmailer (< 6.1) **before** this commit that introduced the `IdnAddressEncoder`: https://github.com/swiftmailer/swiftmailer/commit/6a87efd39bb3d950d85b69f807e3852f485cbe30#diff-e5f85d26733017e183b2633ae3c433f0R31

I'm not an expert when it comes to SMTP and all the different RFCs out there :confused: But for me this exception seems not needed.

Maybe @c960657 can help here?

### CODE REVIEW

File: src/Symfony/Component/Mime/Encoder/IdnAddressEncoder.php [hunk 1]
```diff
@@ -11,25 +11,21 @@
 
 namespace Symfony\Component\Mime\Encoder;
 
-use Symfony\Component\Mime\Exception\AddressEncoderException;
```
Comment (dmaicher) [inline src/Symfony/Component/Mime/Encoder/IdnAddressEncoder.php]: `AddressEncoderException` is now not used anywhere anymore. But we cannot remove it due to BC?

**Comment by dmaicher** [comment]
@fabpot seeing that you wrote this component: Any idea from your side about this issue?

**Comment by dmaicher** [comment]
@symfony/mergers anyone able to help with this one?

**Comment by javiereguiluz** [comment]
@dmaicher Python [supports this too](https://docs.python.org/3/library/smtplib.htm) via the `SMTPUTF8` extension.

Go [supports it too](https://golang.org/src/net/mail/message.go):

> // String formats the address as a valid RFC 5322 address.
> // If the address's name contains non-ASCII characters
> // the name will be rendered according to RFC 2047.

And that's the RFC that describes this: https://www.ietf.org/rfc/rfc2047.txt

**Comment by dmaicher** [comment]
@javiereguiluz as far as I understand rfc 2047 does not apply for email addresses?

>    `+ An 'encoded-word' MUST NOT appear in any portion of an 'addr-spec'.`

It would only apply for the "name" part of some recipient address header. But not the address itself.

**Comment by javiereguiluz** [comment]
@dmaicher I read too fast then. Sorry 😞

**Comment by dmaicher** [comment]
@javiereguiluz any idea how to move this forward? This issue keeps me from using the `symfony/mailer` unfortunately :cry:

**Comment by nicolas-grekas** [comment]
I think we can do this change, but only if we also forbid non-ASCII chars in the local part of the envelope *sender*. The reason is that there always must be a path to receive bounces, and the envelope-sender is their destination.

**Comment by dmaicher** [comment]
@nicolas-grekas first of all thank you for taking to time to look into this! :blush: 

> I think we can do this change, but only if we also forbid non-ASCII chars in the local part of the envelope sender. The reason is that there always must be a path to receive bounces, and the envelope-sender is their destination.

Not sure I follow this comment. So currently this change should impact the envelope sender as well, right?

Seeing that the envelope sender is also an `address` and thus will use the encoder internally: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mime/Address.php#L72

So you mean we should change this behavior for the envelope sender?

**Comment by nicolas-grekas** [comment]
We shouldn't necessarily change the behavior of going through the encoder, but we should add a check, in Mailer, to reject any local part with non-ASCII characters. This will ensure that any bounce message will be able to come back to the sender independently of whether SMTP hops are able to deal with UTF-8 or not. This looks like a critical property to me.

**Comment by dmaicher** [comment]
> We shouldn't necessarily change the behavior of going through the encoder, but we should add a check, in Mailer, to reject any local part with non-ASCII characters. This will ensure that any bounce message will be able to come back to the sender independently of whether SMTP hops are able to deal with UTF-8 or not. This looks like a critical property to me.

Ok fair enough. That seems good to me :+1: 

How should we do this? Inside `Mailer` or inside `Envelope`? Should it throw `Symfony\Component\Mime\Exception\AddressEncoderException`?

**Comment by nicolas-grekas** [comment]
Inside Envelope? this would allow reusing `AddressEncoderException` isn't it?

File: src/Symfony/Component/Mailer/Envelope.php [hunk 2]
```diff
@@ -44,6 +45,9 @@ public static function create(RawMessage $message): self
 
     public function setSender(Address $sender): void
     {
+        if (preg_match('/.*[^\x00-\x7F]+.*@/', $sender->getAddress())) {
+            throw new AddressEncoderException(sprintf('Non-ASCII characters not supported in local-part os "%s".', $sender->getAddress()));
```
Comment (dmaicher) [inline src/Symfony/Component/Mailer/Envelope.php:49]: @nicolas-grekas not sure if this exception makes sense semantically here? We are not really encoding anything yet, or?

Comment (nicolas-grekas) [reply src/Symfony/Component/Mailer/Envelope.php:49]: `InvalidArgumentException` then?

Comment (dmaicher) [reply src/Symfony/Component/Mailer/Envelope.php]: Yes I think it makes more sense :+1:

File: src/Symfony/Component/Mailer/Envelope.php [hunk 3]
```diff
@@ -44,6 +44,9 @@ public static function create(RawMessage $message): self
 
     public function setSender(Address $sender): void
     {
+        if (preg_match('/.*[^\x00-\x7F]+.*@/', $sender->getAddress())) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mailer/Envelope.php:47]: maybe this?
`if (!preg_match('/^[^@\x80-\xFF]++@/', $sender->getAddress())) {`

Comment (dmaicher) [reply src/Symfony/Component/Mailer/Envelope.php]: yes tested it a bit and seems to work nicely :+1:

File: src/Symfony/Component/Mailer/Envelope.php [hunk 4]
```diff
@@ -44,6 +44,10 @@ public static function create(RawMessage $message): self
 
     public function setSender(Address $sender): void
     {
+        // to ensure deliverability of bounce emails independent of UTF-8 capabilities of SMTP servers
+        if (!preg_match('/^[^@\x80-\xFF]++@/', $sender->getAddress())) {
+            throw new InvalidArgumentException(sprintf('Non-ASCII characters not supported in local-part of "%s".', $sender->getAddress()));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Mailer/Envelope.php:49]: Invalid sender address "%s": non-ASCII are not...

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Mailer/Envelope.php [hunk 5]
```diff
@@ -44,6 +44,10 @@ public static function create(RawMessage $message): self
 
     public function setSender(Address $sender): void
     {
+        // to ensure deliverability of bounce emails independent of UTF-8 capabilities of SMTP servers
+        if (!preg_match('/^[^@\x80-\xFF]++@/', $sender->getAddress())) {
+            throw new InvalidArgumentException(sprintf('Invalid sender "%s": non-ASCII characters not supported in local-part of email.', $sender->getAddress()));
+        }
```
Comment (fabpot) [inline src/Symfony/Component/Mailer/Envelope.php:50]: I think we should also change `DelayedEnvelope::getSender()` like this:

```
    public function getSender(): Address
    {
        if (!$this->senderSet) {
            parent::setSender(self::getSenderFromHeaders($this->message->getHeaders()));
        }

        return parent::getSender();
    }
```

So that we also get the exception when the sender in the envelope is not set explicitly but comes from the email headers.

**Review by fabpot — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Mailer/Envelope.php (hunk 5 above)
Comment (dmaicher) [reply src/Symfony/Component/Mailer/Envelope.php:50]: @fabpot done but 2 test fails seem a bit odd:

```
There were 2 failures:

1) Symfony\Component\Mailer\Tests\EnvelopeTest::testSenderFromHeaders
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 Symfony\Component\Mime\Address Object (
     'address' => 'return@symfony.com'
-    'name' => 'return'
+    'name' => ''
 )

/var/www/symfony/src/Symfony/Component/Mailer/Tests/EnvelopeTest.php:71

2) Symfony\Component\Mailer\Tests\EnvelopeTest::testSenderFromHeadersWithoutFrom
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 Symfony\Component\Mime\Address Object (
     'address' => 'from@symfony.com'
-    'name' => 'from'
+    'name' => ''
 )
``` 

So the name of the address is lost now. This seems due to 

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mailer/Envelope.php#L47

where the name is ignored. Is that correct?

Comment (fabpot) [reply src/Symfony/Component/Mailer/Envelope.php:50]: Yes, it is correct. The sender can only be an email address.

File: src/Symfony/Component/Mailer/Tests/EnvelopeTest.php [hunk 6]
```diff
@@ -57,19 +66,27 @@ public function testSenderFromHeaders()
         $headers->addPathHeader('Return-Path', new Address('return@symfony.com', 'return'));
         $headers->addMailboxListHeader('To', ['from@symfony.com']);
         $e = Envelope::create(new Message($headers));
-        $this->assertEquals(new Address('return@symfony.com', 'return'), $e->getSender());
```
Comment (dmaicher) [inline src/Symfony/Component/Mailer/Tests/EnvelopeTest.php:60]: @fabpot here is a slight change in behavior now since we use `parent::setAddress` and it will strip away the name of the address

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
This is a new feature, so it must be rebased on master before merging.

**Comment by dmaicher** [comment]
> This is a new feature, so it must be rebased on master before merging.

@fabpot would have been great to see this change in 4.4 LTS... but ok. Why do you think this cannot be treated as a bugfix?

Anyway I rebased it :wink:

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @dmaicher.

**Comment by nicolas-grekas** [comment]
It looks like this broke some tests for bridges, could you please have a look @dmaicher?

**Comment by dmaicher** [comment]
@nicolas-grekas ah sorry I missed those test fails.

@fabpot I could simply fix those test fails but not sure the change in behavior is really correct :confused: 

For example the test fail in `MandrillApiTransportTest`:

```php
        $transport = new MandrillApiTransport('KEY', $client);

        $mail = new Email();
        $mail->subject('Hello!')
            ->to(new Address('saif.gmati@symfony.com', 'Saif Eddin'))
            ->from(new Address('fabpot@symfony.com', 'Fabien'))
            ->text('Hello There!');

        $message = $transport->send($mail);
``` 

Now with my changes the name "Fabien" is dropped from the sender address and before it was passed on to Mandrill as `from_name`.

**Comment by nicolas-grekas** [comment]
Dunno if it helps decide, but this affects deps=high on 4.4 also.

**Comment by xabbuh** [comment]
How does Mandrill use the `from_email` field? Is it used like the `Sender` or like the `From` header? If it's the latter, using the sender as the input for this attribute looks indeed wrong to me (same would apply to other APIs).

**Comment by dmaicher** [comment]
@xabbuh not sure how Mandrill is handling that but Mailgun seems to use it for the `From` header.

See https://documentation.mailgun.com/en/latest/api-sending.html#sending


Parameter | Description
-- | --
from | Email address for From header

And there we also use the envelope sender: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mailer/Bridge/Mailgun/Transport/MailgunApiTransport.php#L94

But that means the "Sender customization feature" using [EnvelopeListener](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mailer/EventListener/EnvelopeListener.php#L46) would then not work anymore if we change that? :confused:

**Comment by fabpot** [comment]
@dmaicher see #37580

**Comment by MaSpeng** [comment]
I'am sorry but i have to ask, will this "feature" be part of the 5.2 release or will it be an addition to 5.1.4?

**Comment by javiereguiluz** [comment]
@MaSpeng this was merged as a feature in `master` branch (see https://github.com/symfony/symfony/commit/63f8827cf042adc966d0392598399309f4c16f4b) which corresponds to the upcoming 5.2 version.

According to the [Symfony Release Process](https://symfony.com/doc/current/contributing/community/releases.html) minor versions (e.g. 5.1.4) only contains bug fixes and never new features. So, this will be included only in 5.2 and higher versions, but not in 5.1.*. The good news is that [Symfony 5.2 release](https://symfony.com/releases/5.2) is just a few months ago (feature freeze starts in just 6 weeks!) and you can upgrade your app from 5.1 to 5.2 without breaking changes.

**Comment by MaSpeng** [comment]
@javiereguiluz Many thanks for the explanations.
