### PR TITLE
[Mailer] Fix typo

### LINKED ISSUE #34006: [Mailer] Amazon SES error when message id is empty
**Symfony version(s) affected**: 4.4.0-DEV

**Description**  
Sending an email with Amazon SES is resulting in an error:
>Argument 1 passed to Symfony\Component\Mailer\SentMessage::setMessageId() must be of the type string, null given, called in /myproject/vendor/symfony/amazon-mailer/Transport/SesHttpTransport.php on line 71

**How to reproduce**  
Just send an email with Amazon SES

**Additional context**  
Problem was introduced in b42c269760b1f1c5735631e103eb0ddf9504000e

### PR DESCRIPTION
**Pull request by fabpot**
| Q             | A
| ------------- | ---
| Branch?       | 4.4 for features / 3.4 or 4.3 for bug fixes 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #34006
| License       | MIT
| Doc PR        | n/a

The XML is different depending on the way we are sending email. So, it's `SendEmailResult` when using the API and `SendRawEmailResult` when using the HTTP class (we are then sending the raw email).

### CODE REVIEW

**Review by chalasr — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

File: src/Symfony/Component/Mailer/Bridge/Amazon/Transport/SesHttpTransport.php [hunk 1]
```diff
@@ -68,7 +68,7 @@ protected function doSendHttp(SentMessage $message): ResponseInterface
             throw new HttpTransportException(sprintf('Unable to send an email: %s (code %s).', $result->Error->Message, $result->Error->Code), $response);
         }
 
-        $message->setMessageId($result->SendEmailResult->MessageId);
+        $message->setMessageId($result->SendRawEmailResult->MessageId);
```
Comment (dmaicher) [inline src/Symfony/Component/Mailer/Bridge/Amazon/Transport/SesHttpTransport.php]: shouldn't this be covered by a test?
