### PR TITLE
[HtmlSanitizer] Fix node renderer handling of self-closing (void) elements

### LINKED ISSUE #46258: [HtmlSanitizer] Node renderer does not account for HTML5 void elements
### Symfony version(s) affected

6.1.0-beta2

### Description

The `render()` method in the HtmlSanitizer's Visitor\Node\Node.php file incorrectly assumes that all elements with no content are self-closing (or void) elements. This can produce invalid HTML in the result.

### How to reproduce

I discovered this because I was testing and found that strings containing Font Awesome icons were getting mangled. For example it may look something like: `<i class="fas fa-thumbs-up"></i>` where you can see that the `i` element has no content (it gets replaced later with the icon). What HtmlSanitizer is doing is treating it as a void element and returning `<i class="fas fa-thumbs-up" />` which is both invalid HTML and something that Font Awesome cannot recognize.

### Possible Solution

The problem is here: https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/HtmlSanitizer/Visitor/Node/Node.php#L60

This needs some sort of logic to check for HTML elements which are allowed to be void. In HTML5 these are:
`['area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'keygen', 'link', 'meta', 'param', 'source', 'track', 'wbr']`
Everything else that has no children should get a closing tag instead.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by omniError**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #46258 
| License       | MIT
| Doc PR        | n/a

When sanitizing an HTML string, the node renderer previously interpreted all empty (no children) nodes as being self-closing or void tags. This would result in invalid HTML being rendered in the result. This patch adds the list of valid void HTML5 elements and checks when a no-children node is encountered to see if the tag that is generated should be rendered as self-closing or not.

### CODE REVIEW

File: src/Symfony/Component/HtmlSanitizer/Visitor/Node/Node.php [hunk 1]
```diff
@@ -57,7 +60,11 @@ public function addChild(NodeInterface $node): void
     public function render(): string
     {
         if (!$this->children) {
-            return '<'.$this->tagName.$this->renderAttributes().' />';
+            if (\in_array($this->$tagName, self::VOID_ELEMENTS)) {
+                return '<'.$this->tagName.$this->renderAttributes().' />';
+            }
+
+            return '<'.$this->tagName.$this->renderAttributes().'></'.$this->tagName.'>';
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HtmlSanitizer/Visitor/Node/Node.php]: we could drop this line and merge both ifs above as:
`if (!$this->children && \in_array($this->$tagName, self::VOID_ELEMENTS, true)) {`

Comment (omniError) [reply src/Symfony/Component/HtmlSanitizer/Visitor/Node/Node.php]: added some comments, the returns are different for each if. unless i misunderstand what you mean

**Review by nicolas-grekas — APPROVED** [review]
(I updated the PR a bit)

**Review by stof — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @omniError.
