### PR TITLE
[Validator] fix mapping properties using property hooks

### LINKED ISSUE #64010: Validator doesn't support property hooks
### Symfony version(s) affected

8.*

### Description

Currently if you have a validation constraint on a property that isn't initialized but has a valid get hook, the validation will be called with null as a value instead of calling the hook.

### How to reproduce

I stumbled upon this while trying to lazy load certain properties : 
```php
    #[Assert\NotBlank()]
    public SomeClass $someProperty {
        get {
            $prop = new ReflectionProperty(self::class, 'someProperty');
            if (!$prop->isInitialized($this)) {
                $this->someProperty = $this->fetchThatValue();
            }
            return $this->someProperty;
        }
    }
```

### Possible Solution

In Symfony\Component\Validator\Mapping\PropertyMetadata, the getPropertyValue already checks for __get() functions, this could be added just before ( around https://github.com/symfony/symfony/blob/8.1/src/Symfony/Component/Validator/Mapping/PropertyMetadata.php#L54 ): 
```php
            // If there's a Get hook, use it to get the value
            if(null !== $reflProperty->getHook(\PropertyHookType::Get)){
                return $reflProperty->getHook(\PropertyHookType::Get)->invoke($object);
            }

```
There might be other places where it's needed / some subtleties to take into account, i'm not expert enough on this to tell.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mrossard**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #64010 
| License       | MIT

This adds the missing support for php 8.4's property hooks on validator mapping, adding to the already supported __get methods.

### CODE REVIEW

File: src/Symfony/Component/Validator/Mapping/PropertyMetadata.php [hunk 1]
```diff
@@ -53,7 +53,8 @@ public function getPropertyValue(mixed $object): mixed
 
             // If __get method is not present, no fallback is possible
             // Otherwise we need to catch an Error in case we are trying to access an uninitialized but set property.
-            if (!method_exists($object, '__get')) {
+            if (!method_exists($object, '__get') &&
+                (\PHP_VERSION_ID <= 80400 || !$reflProperty->hasHook(\PropertyHookType::Get))) {
```
Comment (stof) [inline src/Symfony/Component/Validator/Mapping/PropertyMetadata.php]: Please keep the condition on one line

File: src/Symfony/Component/Validator/Mapping/PropertyMetadata.php [hunk 2]
```diff
@@ -53,7 +53,8 @@ public function getPropertyValue(mixed $object): mixed
 
             // If __get method is not present, no fallback is possible
```
Comment (stof) [inline src/Symfony/Component/Validator/Mapping/PropertyMetadata.php]: This comment should be updated

File: src/Symfony/Component/Validator/Tests/Mapping/PropertyMetadataTest.php [hunk 3]
```diff
@@ -77,4 +79,14 @@ public function testGetPropertyValueFromUninitializedPropertyShouldNotReturnNull
         $this->assertNull($notUnsetMetadata->getPropertyValue($entity));
         $this->assertEquals(42, $metadata->getPropertyValue($entity));
     }
+
+    #[RequiresPhp('>=8.4.0')]
+    public function testGetPropertyValueFromUninitializedPropertyShouldUseHookIfPresent()
```
Comment (stof) [inline src/Symfony/Component/Validator/Tests/Mapping/PropertyMetadataTest.php:85]: Please also add another test with a property where the hook transforms the backing value but still fails if it is unitialized (i.e. a `get` hook doing `return strtolower($this->property)` for instance).

this way, we will prevent regressions on that behavior as well (i.e. not allowing going back to the previous implementation of the PR that was not handling this case)

File: src/Symfony/Component/Validator/Mapping/PropertyMetadata.php (hunk 2 above)
Comment (mrossard) [reply src/Symfony/Component/Validator/Mapping/PropertyMetadata.php]: done!

File: src/Symfony/Component/Validator/Tests/Mapping/PropertyMetadataTest.php (hunk 3 above)
Comment (mrossard) [reply src/Symfony/Component/Validator/Tests/Mapping/PropertyMetadataTest.php:85]: done!

File: src/Symfony/Component/Validator/Tests/Mapping/PropertyMetadataTest.php [hunk 4]
```diff
@@ -77,4 +79,26 @@ public function testGetPropertyValueFromUninitializedPropertyShouldNotReturnNull
...
+        $metadata = new PropertyMetadata(EntityWithHook::class, 'withHook');
+
+        $this->assertEquals('foobar', $metadata->getPropertyValue($entity));
+    }
+
+    #[RequiresPhp('>=8.4.0')]
+    public function testGetPropertyValueFromUninitializedPropertyShouldReturnNullIfHookFails()
+    {
+        $entity = new EntityWithHook();
+        //$withHook uses $entity->name but it's not initialized
```
Comment (stof) [inline src/Symfony/Component/Validator/Tests/Mapping/PropertyMetadataTest.php]: this is **not** the test I requested. Here, you test an initialization hook that accesses another uninitialized property.
What I asked for is a test for a case where the hook is accessing its *own* backing value (the one that is known as uninitialized by the PropertyMetadata).

However, your test might still bring value to cover a different kind of failures.

Comment (mrossard) [reply src/Symfony/Component/Validator/Tests/Mapping/PropertyMetadataTest.php]: Sorry, I misunderstood what you requested. It's similar but not quite the same, i'll add it.

Comment (mrossard) [reply src/Symfony/Component/Validator/Tests/Mapping/PropertyMetadataTest.php]: It's added, hope that's what you expected this time!

File: src/Symfony/Component/Validator/Tests/Mapping/PropertyMetadataTest.php [hunk 5]
```diff
@@ -77,4 +79,35 @@ public function testGetPropertyValueFromUninitializedPropertyShouldNotReturnNull
         $this->assertNull($notUnsetMetadata->getPropertyValue($entity));
         $this->assertEquals(42, $metadata->getPropertyValue($entity));
     }
+
+    #[RequiresPhp('>=8.4.0')]
```
Comment (xabbuh) [inline src/Symfony/Component/Validator/Tests/Mapping/PropertyMetadataTest.php]: PHPUnit 9.6 doesn't know the `#[RequiresPhp]` attribute. You have to use the equivalent annotation instead like this:

```php
/**
 * @requires PHP 8.4
 */
```

Comment (mrossard) [reply src/Symfony/Component/Validator/Tests/Mapping/PropertyMetadataTest.php]: Thanks for the heads up, i was looking at what existed in the 6.4 code and  wondering whether I should just add the annotation or replace the attribute.

**Comment by mrossard** [comment]
I'm not sure how to handle the psalm errors. Should I just add something along those lines to suppress the error or is there a better way to do this?
```php
/** @psalm-suppress UndefinedClass */
/** @psalm-suppress UndefinedMethod */
```

**Comment by stof** [comment]
@mrossard just ignore them if they are not relevant. We use the CI job as an helper for review, but we don't require it to be green (we review the kind of things it reports instead). And that CI job reports only *new* violations introduced in the PR.

**Comment by mrossard** [comment]
> @mrossard just ignore them if they are not relevant. We use the CI job as an helper for review, but we don't require it to be green (we review the kind of things it reports instead). And that CI job reports only _new_ violations introduced in the PR.

Thanks for the feedback - and generally guiding me through this !

**Review by stof — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @mrossard.
