### PR TITLE
[Validator] treat uninitialized properties referenced by property paths as null

### LINKED ISSUE #46347: [Validator] Cannot use `propertyPath` with uninitialized properties
### Symfony version(s) affected

<= 6.1

### Description

When a constraint uses the PropertyAccess component to get a `propertyPath` referencing an uninitialized property, an `Symfony\Component\PropertyAccess\Exception\UninitializedPropertyException` is thrown. I think unintialized properties should be ignored and considered like `null` values in most constraints.

It happens in:
- All [`AbstractComparisonValidator`](https://github.com/symfony/symfony/blob/a39ddaa21b264d12a695edb6b29e680f9d5fcdb8/src/Symfony/Component/Validator/Constraints/AbstractComparisonValidator.php#L56)
- [`BicValidator`](https://github.com/symfony/symfony/blob/a39ddaa21b264d12a695edb6b29e680f9d5fcdb8/src/Symfony/Component/Validator/Constraints/BicValidator.php#L131)
- [`RangeValidator`](https://github.com/symfony/symfony/blob/a39ddaa21b264d12a695edb6b29e680f9d5fcdb8/src/Symfony/Component/Validator/Constraints/RangeValidator.php#L168)

### How to reproduce

```php
class MyObject
{
    #[GreaterThan(propertyPath: 'b')]
    public int $a;

    public int $b;
}

$myObject = new MyObject();
$myObject->a = 12;

$validator->validate($myObject); // throws UninitializedPropertyException
```

### Possible Solution

I propose to catch `Symfony\Component\PropertyAccess\Exception\UninitializedPropertyException` when getting `propertyPath` values and stop the validation.

See this example from [`AbstractComparisonValidator`](https://github.com/symfony/symfony/blob/a39ddaa21b264d12a695edb6b29e680f9d5fcdb8/src/Symfony/Component/Validator/Constraints/AbstractComparisonValidator.php#L56):
```diff
  try {
      $comparedValue = $this->getPropertyAccessor()->getValue($object, $path);
  } catch (NoSuchPropertyException $e) {
      throw new ConstraintDefinitionException(sprintf('Invalid property path "%s" provided to "%s" constraint: ', $path, get_debug_type($constraint)).$e->getMessage(), 0, $e);
+ } catch (UninitializedPropertyException $e) {
+    return;
  }
```

I can work on a PR 😀

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #46347
| License       | MIT

### CODE REVIEW

File: src/Symfony/Component/Validator/Tests/Constraints/BicValidatorTest.php [hunk 1]
```diff
@@ -92,6 +92,15 @@ public function testInvalidComparisonToPropertyPathFromAttribute()
             ->assertRaised();
     }
 
+    public function testPropertyPathReferencingUninitializedProperty()
+    {
+        $this->setObject(new BicTypedDummy());
+
+        $this->validator->validate('UNCRIT2B912', new Bic(ibanPropertyPath: 'iban'));
```
Comment (alexandre-daubois) [inline src/Symfony/Component/Validator/Tests/Constraints/BicValidatorTest.php]: Named arguments cannot be used when targeting 5.4

File: src/Symfony/Component/Validator/Tests/Constraints/RangeValidatorTest.php [hunk 2]
```diff
@@ -1042,6 +1042,28 @@ public function testInvalidDatesCombinedMinPropertyPath($value, $dateTimeAsStrin
...
+        $this->assertNoViolation();
+    }
+
+    public function testMaxPropertyPathReferencingUninitializedProperty()
+    {
+        $object = new MinMaxTyped();
+        $object->min = 5;
+        $this->setObject($object);
+
+        $this->validator->validate(5, new Range(minPropertyPath: 'min', maxPropertyPath: 'max'));
```
Comment (alexandre-daubois) [inline src/Symfony/Component/Validator/Tests/Constraints/RangeValidatorTest.php]: Same on those 2 new tests

**Review by alexandre-daubois — APPROVED** [review]

**Review by yceruto — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.
