### PR TITLE
[Security] fix unserializing session payloads from v4

### LINKED ISSUE #44676: Upgrading from Symfony 4.x to Symfony 5.x logouts all users
### Symfony version(s) affected

5.x

### Description

The `Symfony\Component\Security\Core\Role\Role` and `Symfony\Component\Security\Core\Role\SwitchUserRole` classes were [deprecated](https://github.com/symfony/symfony/pull/22048) in Symfony 4.3 and [removed](https://github.com/symfony/symfony/pull/31723) in Symfony 5.0.

But if you are using PHP sessions to keep users logged in and you are using any authentication token that extends the given `AbstractToken`, the authenticated token is being serialized with references to old role classes in your Symfony 4 app.

When you upgrade your app to Symfony 5, and the `ContextListener` tries to unserialize the token, the old role classes no longer exist, causing an exception. The exception is caught by Symfony and your users will only see their sessions closed without any reason.

### How to reproduce

Execute: 

```bash
git clone git@github.com:ajgarlag/sf4-to-sf5-bug.git
cd sf4-to-sf5-bug
git checkout origin/4.x
composer install
symfony serve -d
```

Now visit http://localhost:8000/profile and fill the login form with:
* Username: `user`
* Password: `foobar`

You will be logged in. Keep this browser window open.

Execute:
```bash
git checkout origin/5.x
composer install
```

Refresh the browser window. You will be logged out. If you explore the profile from redirect response you will see:

Screenshot_20211216_193000

### Possible Solution

I'm not sure how to fix it in Symfony code, so I've created a little package that will provide the missing classes: [ajgl/sf4-to-sf5-role-unserialization](https://github.com/ajgarlag/AjglSf4ToSf5RoleUnserialization)

To see it in action try the following reproducer:

Execute: 

```bash
git clone git@github.com:ajgarlag/sf4-to-sf5-bug.git
cd sf4-to-sf5-bug
git checkout origin/4.x
composer install
symfony serve -d
```

Now visit http://localhost:8000/profile and fill the login form with:
* Username: `user`
* Password: `foobar`

You will be logged in. Keep this browser window open.

Execute:
```bash
git checkout origin/main
composer install
```

Refresh the browser window. You will be logged in, and your the serialized token stored in session has been successfully upgraded to be Symfony 5 compatible.

Finally you can safely remove my package:
```bash
composer remove ajgl/sf4-to-sf5-role-unserialization
```

If you refresh the browser window, you will be logged in.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44676
| License       | MIT
| Doc PR        | -

Replaces #44801

I propose to reintroduce these classes to ease transitioning to v5, ~then removing them in v6.~

### CODE REVIEW

File: src/Symfony/Component/Security/Core/Role/SwitchUserRole.php [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
+
+/**
+ * Allows migrating session payloads from v4 to v5.
+ *
+ * @internal to be removed in Symfony 6.0
+ */
+class SwitchUserRole extends Role
+{
+    private $deprecationTriggered;
```
Comment (fancyweb) [inline src/Symfony/Component/Security/Core/Role/SwitchUserRole.php:21]: Is this property needed?

Comment (nicolas-grekas) [reply src/Symfony/Component/Security/Core/Role/SwitchUserRole.php:21]: It exists on v4. Not declaring it would make unserialization add it as a dynamic property. Better not.

**Comment by ajgarlag** [comment]
IMO these classes should exist only to allow unserialization, so in my [package](https://packagist.org/packages/ajgl/sf4-to-sf5-role-unserialization), every method throws a `LogicException`. WDYT?

**Comment by nicolas-grekas** [comment]
I think there is no need for such detailed care. I made the constructor private and the class `@internal`, that's enough a warning to me.

**Comment by ajgarlag** [comment]
> I think there is no need for such detailed care. I made the constructor private and the class `@internal`, that's enough a warning to me.

Ok, I see, then I would remove any public method. These classes only exist for BC and IMO should not have any behavior.

**Comment by derrabus** [comment]
We should add a test that deserializes a token serialized with 4.4 and checks if that token is usable. For instance, I would expect to run into new problems if the tokens returned arrays of `Role` objects again.

**Comment by nicolas-grekas** [comment]
I removed all methods but `__toString()`.
@derrabus would you mind sending a PR to my fork with the test you have in mind? :pray:

**Review by wouterj — APPROVED** [review]
Thanks, this looks OK to me.

I agree with @derrabus. We should at least add a test with a payload like:

```php
// serialized string created on Symfony 4.4 using the following command:
//     php -r 'require_once __DIR__."/vendor/autoload.php"; echo serialize(new \\Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken("sf", null, "main", [new Symfony\\Component\\Security\\Core\\Role\\Role("ROLE_USER")]));'
$serialized = 'O:74:"Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken":3:{i:0;N;i:1;s:4:"main";i:2;a:5:{i:0;s:2:"sf";i:1;b:1;i:2;a:1:{i:0;O:41:"Symfony\Component\Security\Core\Role\Role":1:{s:47:"Symfony\Component\Security\Core\Role\Rolerole";s:9:"ROLE_USER";}}i:3;a:0:{}i:4;a:1:{i:0;s:9:"ROLE_USER";}}}';
```

**Comment by nicolas-grekas** [comment]
Thanks for the hint, test added.

**Review by chalasr — APPROVED** [review]

**Comment by derrabus** [comment]
nicolas-grekas/symfony#40 🙂

**Review by derrabus — APPROVED** [review]
