### PR TITLE
[Ldap] Bypass the use of `ldap_control_paged_result` on PHP >= 7.3

### LINKED ISSUE #38352: [LDAP] Deprecated functions will be removed in PHP 8.0
**Symfony version(s) affected**: since 4.3.x

**Description**  
Deprecated functions since PHP 7.4:
```
ldap_control_paged_result()
ldap_control_paged_result_response()
```
used in LDAP component 
https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php#L100
https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php#L136

will be not available in PHP 8.0
See https://github.com/php/php-src/pull/6235 or https://github.com/php/php-src/commit/550a4f2fa89c3d3bc858aa81c62dbfa0f59f0e7c

**How to reproduce**  

**Possible Solution**  
Checking PHP Version or if method exist ?

**Additional context**

### PR DESCRIPTION
**Pull request by lucasaba**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38352 
| License       | MIT
| Doc PR        | 

As stated on #38352 [ldap_control_paged_result](https://www.php.net/manual/en/function.ldap-control-paged-result.php) and [ldap_control_paged_result_response](https://www.php.net/manual/en/function.ldap-control-paged-result-response.php) have been deprecated since PHP 7.4 and will be removed on PHP 8.0.

With this fix, Query uses serverctrls to handle LDAP results pagination.

Since `serverctrls` where introduced in PHP 7.3 and they are the only way to circumvent the usage of `ldap_control_paged_result`, I've added a new Query class implementation which uses `serverctrls` to control pagination.

To do so I've also had to update the LDAP Adapter in order to use the new class if PHP version 7.3 or greater are found

### CODE REVIEW

**Comment by lucasaba** [comment]
Side note: to test the component I've created an OpenLDAP instance on docker using latest osixia/openldap. TO make test working, I had to add `ldap_set_option($h, LDAP_OPT_PROTOCOL_VERSION, 3);` in `LdapTestCase`.

Even with this configuration, some test fails with message `Failed asserting that actual size 2 matches expected size 1.`. This happens both in my version and in 4.4 version of Symfony.

It would be a good idea to have a docker environment prepared to test those methods....at least in order to have a common environment.

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Adapter.php [hunk 1]
```diff
@@ -61,6 +61,10 @@ public function getEntryManager()
      */
     public function createQuery($dn, $query, array $options = [])
     {
+        if (version_compare(\PHP_VERSION, '7.3.0', 'ge')) {
```
Comment (derrabus) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Adapter.php]:
```suggestion
        if (\PHP_VERSION_ID >= 70300) {
```

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php [hunk 2]
```diff
@@ -18,6 +18,8 @@
 /**
  * @author Charles Sarrazin <charles@sarraz.in>
  * @author Bob van de Vijver <bobvandevijver@hotmail.com>
+ *
+ * @deprecated Use PaginableQuery instead if using PHP 7.3 or greater
```
Comment (derrabus) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: Is it really necessary to deprecate this class and create a new one? To me, the new code looks like it could be merged into the existing class.

Comment (lucasaba) [reply src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: Unfortunately it is not that easy. In a first [attempt](https://github.com/symfony/symfony/pull/38392/commits/357ddcb03871f29c3183186a16c4bc3db6a014a9) I've tried this solution but, in order to let the two way to handle pagination to cohesist, I was using the [serverctrls](https://github.com/symfony/symfony/pull/38392/commits/357ddcb03871f29c3183186a16c4bc3db6a014a9#diff-c0e22b9cfa83e41d100fd47a035b44adR250) parameter. But that parameter, which is the only alternative to clear the pagination, is only available in PHP 7.3 (https://www.php.net/manual/en/function.ldap-parse-result.php)

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/PaginableQuery.php [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+ * Uses serverctrls to support pagination and removes
+ * the usage of the following deprecated methods:
+ * - ldap_control_paged_result: https://www.php.net/manual/en/function.ldap-control-paged-result.php
+ * - ldap_control_paged_result_response: https://www.php.net/manual/en/function.ldap-control-paged-result-response.php.
+ *
+ * Requires PHP 7.3 or greater
+ *
+ * @author Luca Saba <lucasaba@gmail.com>
+ */
+class PaginableQuery extends Query
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/PaginableQuery.php]: I'd prefer not adding a new class here, and merge the code in the existing Query class (undeprecating it): not using the deprecated functions should remain an "internal detail" concern, no need to make it leak to any public API (eg changing a class name)

Comment (lucasaba) [reply src/Symfony/Component/Ldap/Adapter/ExtLdap/PaginableQuery.php]: If all the logic of selecting the correct PHP version is placed in the Query class, the code looks... not very elegant.

I'll give it a check.

Comment (nicolas-grekas) [reply src/Symfony/Component/Ldap/Adapter/ExtLdap/PaginableQuery.php]: Leaking internal concerns is worse :)
`if (\PHP_VERSION_ID >= 70300) {` is fine, it will be optimized by opcache and will be easy to remove once the minimum supported version is bumped.

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php [hunk 4]
```diff
@@ -177,10 +168,10 @@ public function getResources(): array
     /**
      * Resets pagination on the current connection.
      */
-    private function resetPagination()
+    protected function resetPagination()
```
Comment (stof) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: why making it protected ?

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php [hunk 5]
```diff
@@ -203,4 +194,67 @@ private function resetPagination()
...
+                'isCritical' => $isCritical,
+                'value' => [
+                    'size' => $pageSize,
+                    'cookie' => $cookie,
+                ],
+            ],
+        ];
+    }
+
+    protected function controlPagedResultResponse($con, $search, &$cookie = null)
```
Comment (stof) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: methods should be private. It does not make sense to make them extension points

Comment (stof) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: rather than creating an API using references, I suggest returning the cookie instead. That would better match the way we write code in Symfony.

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php [hunk 6]
```diff
@@ -203,4 +194,67 @@ private function resetPagination()
             ldap_set_option($con, \LDAP_OPT_SERVER_CONTROLS, $ctl);
         }
     }
+
+    protected function controlPagedResult($con, $pageSize, $isCritical = false, $cookie = '')
+    {
+        if (\PHP_VERSION_ID < 70300) {
+            return ldap_control_paged_result($con, $pageSize, $isCritical, $cookie);
+        }
+        $this->options['serverctrls'] = [
```
Comment (stof) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: IMO, we should avoid changing the state of `$this->options`. This might have unintended side effects as it changes the state of the class. This `serverctrls` should rather be handled using local state (return it from this method and store it in a local variable in the main query, or maybe inline that logic directly with the code calling the function by passing it the cookie

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php (hunk 4 above)
Comment (lucasaba) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: @nicolas-grekas do you think I should mark it private again ? Same for `controlPagedResult`, `controlPagedResultResponse` and `callSearchFunction` ?

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php [hunk 7]
```diff
@@ -203,4 +194,67 @@ private function resetPagination()
...
+        return @$func(
+            $con,
+            $this->dn,
+            $this->query,
+            $this->options['filter'],
+            $this->options['attrsOnly'],
+            $sizeLimit,
+            $this->options['timeout'],
+            $this->options['deref'],
+            $this->options['serverctrls']
```
Comment (stof) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: this will break if `$this->options['serverctrls']` is not set (because page control is not enabled)

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php (hunk 4 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: all methods should be private yes

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php [hunk 8]
```diff
@@ -203,4 +194,67 @@ private function resetPagination()
...
+    protected function controlPagedResultResponse($con, $search, &$cookie = null)
+    {
+        if (\PHP_VERSION_ID < 70300) {
+            return ldap_control_paged_result_response($con, $search, $cookie);
+        }
+        $controls = [];
+        $errcode = 0;
+        $matcheddn = null;
+        $errmsg = null;
+        $referral = [];
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: no need to init those vars

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php [hunk 9]
```diff
@@ -203,4 +194,67 @@ private function resetPagination()
...
+        ldap_parse_result($con, $search, $errcode, $matcheddn, $errmsg, $referral, $controls);
+        if (isset($controls[\LDAP_CONTROL_PAGEDRESULTS]['value']['cookie'])) {
+            $cookie = $controls[\LDAP_CONTROL_PAGEDRESULTS]['value']['cookie'];
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: `return $controls[\LDAP_CONTROL_PAGEDRESULTS]['value']['cookie'] ?? '';`

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php (hunk 4 above)
Comment (lucasaba) [reply src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: I was wondering if, instead of having all those phpversion check, it would be better to extend the Query class with clearer methods. I don't like very much all those `if (\PHP_VERSION_ID < 70300) {`

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php [hunk 10]
```diff
@@ -203,4 +194,67 @@ private function resetPagination()
...
+        } else {
+            $cookie = '';
+        }
+    }
+
+    protected function callSearchFunction($con, $func, $sizeLimit)
+    {
+        if (\PHP_VERSION_ID < 70300) {
+            return @$func(
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: please put this call on one line (same below)

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php [hunk 11]
```diff
@@ -203,4 +194,67 @@ private function resetPagination()
             ldap_set_option($con, \LDAP_OPT_SERVER_CONTROLS, $ctl);
         }
     }
+
+    protected function controlPagedResult($con, $pageSize, $isCritical = false, $cookie = '')
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: `$isCritical` argument should be removed, and $cookie made required

**Review by nicolas-grekas — COMMENTED** [review]
Please add types (arguments+return) on methods when possible.

**Comment by nicolas-grekas** [comment]
> It would be a good idea to have a docker environment prepared to test those methods....at least in order to have a common environment.

I agree. We run such tests in [`.github/workflows/tests.yml`](https://github.com/symfony/symfony/blob/master/.github/workflows/tests.yml) if you'd like to have a look (could be done in a separate PR).

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php (hunk 8 above)
Comment (lucasaba) [reply src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: You're right. Just `$errocode` and `$controls`

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php (hunk 10 above)
Comment (lucasaba) [reply src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: Do you mean the call to `$func` ? That would be a 244 characters long string...

```php
return @$func($con, $this->dn, $this->query, $this->options['filter'], $this->options['attrsOnly'], $sizeLimit, $this->options['timeout'], $this->options['deref'], $this->options['serverctrls']);
```

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php [hunk 12]
```diff
@@ -203,4 +198,87 @@ private function resetPagination()
             ldap_set_option($con, \LDAP_OPT_SERVER_CONTROLS, $ctl);
         }
     }
+
+    /**
+     * Sets LDAP pagination controls.
+     *
+     * @param resource $con
+     *
+     * @return bool
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: why don't you use a real return type? (same in the other methods)

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php [hunk 13]
```diff
@@ -203,4 +198,87 @@ private function resetPagination()
...
+    private function controlPagedResultResponse($con, $result, string $cookie = '')
+    {
+        if (\PHP_VERSION_ID < 70300) {
+            ldap_control_paged_result_response($con, $result, $cookie);
+
+            return $cookie;
+        }
+        $controls = [];
+        $errcode = 0;
+        ldap_parse_result($con, $result, $errcode, null, null, [], $controls);
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: vars are passed by reference, this means that:
- there is no need to init any of them
- putting an inline value (`null, null, []`) is illegal AFAIK

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php (hunk 10 above)
Comment (nicolas-grekas) [reply src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: yes that's what I mean, long lines are prefered in the codebase, they ease with grepping

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php (hunk 13 above)
Comment (lucasaba) [reply src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: Not sure what you mean by `there is no need to init any of them`.
But that's what I've done:

```php
$controls = $errcode = $matcheddn = $errmsg = $referrals = null;
ldap_parse_result($con, $result, $errcode, $matcheddn, $errmsg, $referrals, $controls);
```

File: src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php [hunk 14]
```diff
@@ -230,19 +228,16 @@ private function controlPagedResult($con, int $pageSize, string $cookie)
...
     {
         if (\PHP_VERSION_ID < 70300) {
             ldap_control_paged_result_response($con, $result, $cookie);
 
             return $cookie;
         }
-        $controls = [];
-        $errcode = 0;
-        ldap_parse_result($con, $result, $errcode, null, null, [], $controls);
+        $controls = $errcode = $matcheddn = $errmsg = $referrals = null;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php]: I mean that you can remove this line, it's not needed

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @lucasaba.

**Comment by lucasaba** [comment]
Thanks to you all! Has been a pleasure and a precious lesson!
Now I'll see .github/workflows/tests.yml and try to create the LDAP service.
