### PR TITLE
[Console] fix QuestionHelper::getHiddenResponse() not working with space in project directory name

### LINKED ISSUE #40190: [Console] QuestionHelper::getHiddenResponse() not working with space in project directory name
(This is my first ever GitHub issue, so let me know if I'm doing anything wrong!)

**Symfony version(s) affected**: symfony/console ^5.2.3 (latest)

**Description**  
When using the getHiddenResponse method of the QuestionHelper class (which is called when running askQuestion with a hidden question) in a project of which the location has a space in it, it will error out and try to execute the first part of the project location, eg.:
My project is located in 'D:\My Projects\My Cool Project', it will try to execute 'D:\My'.

**How to reproduce**  
Create a php application with the Symfony console component inside of a folder with a space in the name (see example above).  Then run askQuestion with a Question object that has hidden set to true.

**Possible Solution**  
Changing this line: `$exe = __DIR__.'/../Resources/bin/hiddeninput.exe';` to this: `$exe = '"' . __DIR__ . '/../Resources/bin/hiddeninput.exe' . '"';` in Helper\QuestionHelper.php line 405.
This should fix the problem stated above.

**Additional context**  
I found this 'bug' in Laravel 8 on Windows whilst trying to create a console command with a secret input.

### PR DESCRIPTION
**Pull request by Yendric**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #40190 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Fixes #40190 to allow spaces in project directory name.

### CODE REVIEW

**Comment by Yendric** [comment]
#40190

File: src/Symfony/Component/Console/Helper/QuestionHelper.php [hunk 1]
```diff
@@ -402,7 +402,7 @@ private function mostRecentlyEnteredValue(string $entered): string
     private function getHiddenResponse(OutputInterface $output, $inputStream, bool $trimmable = true): string
     {
         if ('\\' === \DIRECTORY_SEPARATOR) {
-            $exe = __DIR__.'/../Resources/bin/hiddeninput.exe';
+            $exe = '"'.__DIR__.'/../Resources/bin/hiddeninput.exe'.'"';
```
Comment (Seb33300) [inline src/Symfony/Component/Console/Helper/QuestionHelper.php]: Maybe better to add the doubles quotes inside the `shell_exec('"'.$exe.'"')`?

Because you also have the `sys_get_temp_dir().'/hiddeninput.exe'` just after.

Comment (Yendric) [reply src/Symfony/Component/Console/Helper/QuestionHelper.php]: Good remark! I changed it and tested it locally.

**Comment by Nyholm** [comment]
Do you think it is possible to add a test for this feature? That would make sure we never reintroduce this bug again.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
@Nyholm Adding a test case is going to be tricky as this means installing the package in a directory with a space before launching the tests. We cannot isolate this in a simple test case...

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @Yendric.

**Comment by Nyholm** [comment]
I understand that writing a test for this is tricky (I don't know how). I was hoping for someone to come up with a genius idea =)

Thank you @Yendric for this PR and congratulations for your first contribution.
