### PR TITLE
[DependencyInjection] copy synthetic status when resolving child definitions

### LINKED ISSUE #44972: [DependencyInjection] `lint:container` fails if kernel implements interface registered for autoconfiguration
### Symfony version(s) affected

5.4+

### Description

When your Kernel implements an interface that is registered for auto-configuration, the following error occurs when running `lint:container`:

```
[ERROR] Invalid definition for service "kernel": Symfony\Component\HttpKernel\Kernel::__construct()" requires 2 arguments, 0 passed.
```

This only appears to be a problem for the lint command. The kernel is auto-configured correctly and behaves as expected.

### How to reproduce

```
git clone git@github.com:kbond/lint-container-reproducer.git
cd lint-container-reproducer
composer install
bin/console lint:container # throws exception
```

### Possible Solution

#44972.

### Additional Context

Seems similar to #40868.

Commit on my reproducer that causes the failure: https://github.com/kbond/lint-container-reproducer/commit/8676d5f93bbbf0a952aef01ae327b676efb41ceb

### PR DESCRIPTION
**Pull request by kbond**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44972
| License       | MIT
| Doc PR        | n/a

Appears to be the simplest fix for #44972. The only place this appears to be a problem is when using the `lint:container` command with an auto-configured kernel in 5.3+.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I'd prefer doing that in ResolveInstanceofConditionalsPass. Doable?

**Comment by kbond** [comment]
I'll need some direction for where to do this in `ResolveInstanceofConditionalsPass`. I tried a few different places but no luck.

**Comment by nicolas-grekas** [comment]
just after `$definition->setParent($parent);`?

**Comment by kbond** [comment]
The definition is still synthetic at this point - this is being copied when converting to `ChildDefinition`. It's not being _copied back_ in `ResolveChildDefinitionsPass`.

File: src/Symfony/Component/DependencyInjection/Compiler/ResolveChildDefinitionsPass.php [hunk 1]
```diff
@@ -111,6 +111,7 @@ private function doResolveDefinition(ChildDefinition $definition): Definition
         $def->setLazy($parentDef->isLazy());
         $def->setAutowired($parentDef->isAutowired());
         $def->setChanges($parentDef->getChanges());
+        $def->setSynthetic($parentDef->isSynthetic());
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/ResolveChildDefinitionsPass.php]: the flag should not be borrowed from $parentDef, but from $definition instead

Comment (kbond) [reply src/Symfony/Component/DependencyInjection/Compiler/ResolveChildDefinitionsPass.php]: Ok, updated.

**Comment by nicolas-grekas** [comment]
Thank you @kbond.
