### PR TITLE
[Workflow] Add `getEnabledTransition()` to TraceableWorkflow

### LINKED ISSUE #52812: Twig function workflow_transition is broken when using TraceableWorkflow
### Symfony version(s) affected

6.4.0

### Description

In dev environment, when using the `workflow_transition()` (not to be confused with `workflow_transactions()`) in a twig template to get a specific workflow transition, the following error occurs:
```
An exception has been thrown during the rendering of a template ("Call to undefined method Symfony\Component\Workflow\Debug\TraceableWorkflow::getEnabledTransition()").
```

This is due to the `TraceableWorkflow`, introduced in Symfony 6.4.0 not having the `getEnabledTransition` method implemented, which _is_ implemented in the 'normal' `Workflow` class. This method is called from the `symfony/twig-bridge/Extension/WorkflowExtension.php` file.

The `WorkflowInterface`, which is implemented by both the `Workflow` and `TraceableWorkflow` classes does not contain the `getEnabledTransaction` method as well.

Note that this isn't an issue in the prod environment, as the `TraceableWorkflow` isn't used there.

### How to reproduce

Have a Symfony application with the workflow component set up, running in dev environment.
Then, call the `workflow_transition()` function in a twig template and render the page.

### Possible Solution

The best solution would be to add the `getEnabledTransition` method to the `WorkflowInterface` and implement it in `TraceableWorkflow`.

However, since `workflow_transitions()` (plural) does work, a temporary workaround can be instead of:
```twig
{% set myTransition = workflow_transition(myWorkflow, 'myTransition') %}
```

Doing it like this:
```twig
{% set myTransition = null %}
{% for transition in workflow_transitions(myWorkflow) %}
    {% if transition.name == 'myTransition' %}
        {% set myTransition = transition %}
    {% endif %}
{% endfor %}
```
It's not an elegant solution, but it works.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #52812
| License       | MIT

I added an annotation to `WorkflowInterface` to not break BC. I think it could deserve an additional `not implementing this method is deprecated since Symfony 7.1` while upmerging (I guess ?).

Added the tests while at it.

### CODE REVIEW

**Review by lyrixx — APPROVED** [review]
Good catch, thanks 👍🏼

File: src/Symfony/Component/Workflow/WorkflowInterface.php [hunk 1]
```diff
@@ -19,6 +19,8 @@
  * Describes a workflow instance.
  *
  * @author Amrouche Hamza <hamza.simperfit@gmail.com>
+ *
+ * @method Transition|null getEnabledTransition(object $subject, string $name)
```
Comment (xabbuh) [inline src/Symfony/Component/Workflow/WorkflowInterface.php]: This should be reverted. We can do this change in 7.1.

Comment (alexandre-daubois) [reply src/Symfony/Component/Workflow/WorkflowInterface.php]: Alright, I'll add it if it isn't done during upmerge :)

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @alexandre-daubois.
