### PR TITLE
[SecurityBundle] Fix UserCheckerListener registration with custom user checker

### LINKED ISSUE #37365: Custom UserChecker dependency on "non existing service" error
**Symfony version(s) affected**: 5.1

**Description**  
Created a custom UserChecker and get the following error
`The service "security.listener.user_checker" has a dependency on a non-existent service "Symfony\Component\Security\Core\User\UserCheckerInterface".`

**How to reproduce**  
Follow the provided documentation. https://symfony.com/doc/current/security/user_checkers.html .

Since the autowire and autoconfigure are on I didn't declare anything else in the services.yaml like it says at the bottom of the article.

When I add
`pattern: ^/`
`user_checker: App\Security\UserChecker`
to the security.yaml file I get the error as mentioned above.

**Possible Solution**  
Don't know. Either there's something wrong/outdated with the documentation or there's something wrong with the autowire/autoconfigure I assume.

### PR DESCRIPTION
**Pull request by wouterj**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37365 
| License       | MIT
| Doc PR        | -

The user checker listener was wrongly registered on the global event dispatcher, as it can be customized per firewall. This PR fixes that + correctly uses the configured user checker instead of always trying to use `UserCheckerInterface`.

### CODE REVIEW

File: src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php [hunk 1]
```diff
@@ -478,6 +478,12 @@ private function createFirewall(ContainerBuilder $container, string $id, array $
                 ->replaceArgument(0, new Reference($managerId))
             ;
 
+            // user checker listener
+            $container
+                ->setDefinition('security.listener.user_checker.'.$id, new ChildDefinition('security.listener.user_checker'))
+                ->replaceArgument(0, new Reference($firewall['user_checker']))
```
Comment (chalasr) [inline src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:484]: Should se inject the generated alias instead?
https://github.com/symfony/symfony/blob/72a192c84f14070846ecd992237d38b4d4b82b05/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L509

Comment (wouterj) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:484]: I don't see an alias being generated somewhere. What would the benefit be of using an alias here?

Comment (chalasr) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:484]: I mean:
```suggestion
                ->replaceArgument(0, new Reference('security.user_checker.'.$id))
```

This alias is created at https://github.com/symfony/symfony/blob/5.1/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php#L503

Comment (wouterj) [reply src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php:484]: Oh sorry, I mis-understood your previous message. PR updated

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thanks for fixing this bug so quickly Wouter!
