### PR TITLE
[Serializer] Capture constructor TypeError when collecting denormalization errors

### LINKED ISSUE #62720: [Serializer] `AbstractNormalizer::instantiateObject()` can fail in unexpected ways
### Symfony version(s) affected

all?

### Description

While `AbstractNormalizer::instantiateObject()` catches `TypeError`s when calling `ReflectionClass::newInstanceArgs()`, it does not update the context’s `not_normalizable_value_exceptions` if it exists: https://github.com/symfony/symfony/blob/7ed2070823d95bf86b9d88306cc9a470b6c70327/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php#L437-L452

That means when denormalizing an object with `collect_denormalization_errors`, the object is returned without its constructor being called and no error ever appears.

### How to reproduce

After requiring `symfony/serializer` and `symfony/property-access`, run the following code:

```php
<?php

require 'vendor/autoload.php';

use Symfony\Component\Serializer\Exception\PartialDenormalizationException;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

class Foo {
    public function __construct(public readonly Bar $bar) {}
}
class Bar {}
class Baz {}

class FooDenormalizer implements DenormalizerInterface
{
    public function __construct(private ObjectNormalizer $objectNormalizer) {}

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): object
    {
        return $this->objectNormalizer->denormalize($data, $type, $format, $context);
    }

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return 'Foo' === $type;
    }

    public function getSupportedTypes(?string $format): array
    {
        return ['*' => true];
    }
}

class ClassStringDenormalizer implements DenormalizerInterface
{
    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): object
    {
        return new $data();
    }

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return is_string($data) && class_exists($data);
    }

    public function getSupportedTypes(?string $format): array
    {
        return ['*' => false];
    }
}

$objectNormalizer = new ObjectNormalizer();

$serializer = new Serializer([new FooDenormalizer($objectNormalizer), new ClassStringDenormalizer(), $objectNormalizer]);

var_dump($serializer->denormalize(
    ['bar' => 'Baz'],
    Foo::class,
    context: [DenormalizerInterface::COLLECT_DENORMALIZATION_ERRORS => true]
));
```

It will display

```
class Foo#76 (1) {
  public readonly Bar $bar =>
  *uninitialized*
}
```

Now, if you make `Foo::$bar` not `readonly` the `AbstractObjectNormalizer` would then try to hydrate it from the string `Baz`, which I find unexpected (that would lead to a `PartialDenormalizationException` though).

### Possible Solution

I guess the first point could be solved by building a `NotNormalizableValueException` from the `TypeError` and append it to `$context['not_normalizable_value_exceptions']`.

Maybe the second point could be fixed by aborting properties hydration if a `NotNormalizableValueException` has been collected while instantiating.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lacatoire**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62720
| License       | MIT

AbstractNormalizer::instantiateObject() caught the TypeError thrown by newInstanceArgs() when COLLECT_DENORMALIZATION_ERRORS was set but never added any entry to not_normalizable_value_exceptions. The caller got an object without its constructor being called and no error ever surfaced.

The catch now builds a NotNormalizableValueException from the TypeError and appends it to the context, keeping the pre-existing newInstanceWithoutConstructor() fallback. A snapshot of the error count before the constructor-parameter loop prevents duplicating the report when the loop already collected errors that caused the TypeError downstream.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Please add back the PR table on top of the PR template (on all you existing and future PRs 🙏 )

File: src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php [hunk 1]
```diff
@@ -346,6 +346,7 @@ protected function instantiateObject(array &$data, string $class, array &$contex
             $missingConstructorArguments = [];
             $params = [];
             $unsetKeys = [];
+            $collectedErrorCountBeforeConstructor = isset($context['not_normalizable_value_exceptions']) ? \count($context['not_normalizable_value_exceptions']) : 0;
```
Comment (mtarld) [inline src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php]:
```suggestion
            $collectedErrorCountBeforeConstructor = \count($context['not_normalizable_value_exceptions'] ?? []);
```

**Comment by nicolas-grekas** [comment]
Thank you @lacatoire.
