### PR TITLE
[FrameworkBundle] Do not throw when describing a factory definition

### LINKED ISSUE #47309: Factory is not describable
### Symfony version(s) affected

5.4.11, 6.1.3

### Description

We cannot currently use `bin/console debug:container` with `--format=json` because we get this error:

> In JsonDescriptor.php line 248:
>                                
> [InvalidArgumentException]   
> Factory is not describable.  
                               
The culprit in our case is `Sentry\Client`, and because of this only service, we cannot describe our whole container.

Would it be possible, instead of throwing an exception, to just output a `null` value, an error string, or anything that wouldn't make the whole thing fail?

Same issue with `xml` and `md`.

### How to reproduce

```
composer create-project symfony/skeleton:"6.1.*" tmp
cd tmp
composer require sentry/sentry-symfony
bin/console debug:container --format=json --env=prod
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #47309
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

File: src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php [hunk 1]
```diff
@@ -218,10 +218,10 @@ private function getContainerDefinitionData(Definition $definition, bool $omitTa
             if (\is_array($factory)) {
                 if ($factory[0] instanceof Reference) {
                     $data['factory_service'] = (string) $factory[0];
-                } elseif ($factory[0] instanceof Definition) {
-                    throw new \InvalidArgumentException('Factory is not describable.');
-                } else {
+                } elseif (!$factory[0] instanceof Definition) {
                     $data['factory_class'] = $factory[0];
+                } elseif ($factoryClass = $factory[0]->getClass()) {
+                    $data['factory_class'] = $factoryClass;
```
Comment (xabbuh) [inline src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php]:
```php
if ($factory[0] instanceof Reference) {
    $data['factory_service'] = (string) $factory[0];
} elseif ($factory[0] instanceof Definition) {
    $data['factory_class']->getClass();
} else {
    $data['factory_class'] = $factory[0];
}
```

Maybe like this instead?

Comment (MatTheCat) [reply src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php]: I originally did it like you suggest but changed because a definition class could be null. Don't know how we should handle it or if it can happen at all 🤔

Comment (xabbuh) [reply src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php]: But changing the order we check each condition in the code wouldn't change the produced result for these cases, would it?

Comment (MatTheCat) [reply src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php]: Yep but there’s one more change here: checking if the definition class is null or not. I was under the impression we don’t want the `factory_class` key if its value is `null`, that’s why I wrote the condition like this.

Comment (xabbuh) [reply src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php]: Hm, you are right indeed. But maybe we should display something different when that the case?

Maybe like this:

```php
if ($factory[0] instanceof Reference) {
    $data['factory_service'] = (string) $factory[0];
} elseif ($factory[0] instanceof Definition) {
    $data['factory_class'] = $definition->getClass() ?: 'not configured';
} else {
    $data['factory_class'] = $factory[0];
}
```

Comment (MatTheCat) [reply src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php]: Doesn’t matter to me; I don’t even know if it can happen :sweat_smile: 

I’ll update the PR!

**Comment by nicolas-grekas** [comment]
Thank you @MatTheCat.

File: src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php [hunk 2]
```diff
@@ -219,7 +219,7 @@ private function getContainerDefinitionData(Definition $definition, bool $omitTa
                 if ($factory[0] instanceof Reference) {
                     $data['factory_service'] = (string) $factory[0];
                 } elseif ($factory[0] instanceof Definition) {
-                    throw new \InvalidArgumentException('Factory is not describable.');
+                    $data['factory_class'] = $factory[0]->getClass() ?? 'not configured';
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php:222]: this might be better describe using `factory_service: inline service ($class)` instead, making it clear that this is not doing a static call to the method (which is what happens for other cases using `factory_class`)

Comment (MatTheCat) [reply src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php:222]: Should I submit another PR?

Comment (MatTheCat) [reply src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php:222]: Woops just saw https://github.com/symfony/symfony/pull/47469
