### PR TITLE
[Console] Add deprecation message for non-int statusCode

### LINKED ISSUE #33747: Command::execute() should always return int - deprecate returning null
Right now, `Command::execute()` returns `int|void`.

I'd suggest we should deprecate returning void (or null) by throwing a deprecation when the method returns a non-int, in `Application`.

We would need to update all core commands to `return 0;` where they `return;` right now.

And in 5.0, we would make returning a non-int throw an exception, in preparation for adding a real return type in 6.0.

Help wanted.

### PR DESCRIPTION
**Pull request by jschaedl**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | yes 
| Tickets       | Fix #33747 
| License       | MIT
| Doc PR        | -

### What was done:

- [x] added deprecation message for non-int return value in Command::execute()
- [x] fixed all core commands to return proper int values
- [x] added proper return type-hint to Command::execute() method in all core Commands

### CODE REVIEW

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
We need to fix the deprecations in this PR (as tests won't pass).

File: src/Symfony/Component/Console/Command/Command.php [hunk 1]
```diff
@@ -253,6 +253,10 @@ public function run(InputInterface $input, OutputInterface $output)
             $statusCode = ($this->code)($input, $output);
         } else {
             $statusCode = $this->execute($input, $output);
+
+            if (!is_numeric($statusCode) || null === $statusCode) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Console/Command/Command.php]: `if (!\is_int(...)) {` + corresponding error message.

**Review by nicolas-grekas — CHANGES_REQUESTED** [review]

**Comment by nicolas-grekas** [comment]
Don't miss updating the corresponding `@return` docblock also.

File: src/Symfony/Bundle/FrameworkBundle/Command/ContainerDebugCommand.php [hunk 2]
```diff
@@ -114,7 +114,7 @@ protected function configure()
     /**
      * {@inheritdoc}
      */
-    protected function execute(InputInterface $input, OutputInterface $output)
+    protected function execute(InputInterface $input, OutputInterface $output): int
```
Comment (jschaedl) [inline src/Symfony/Bundle/FrameworkBundle/Command/ContainerDebugCommand.php]: The `ContainerDebugCommand` is marked as `@internal` and all subclasses already introduced an `int` return type-hint for `execute()`. So I think it is save to add a return type here as well.

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php [hunk 3]
```diff
@@ -73,7 +73,7 @@ protected function execute(InputInterface $input, OutputInterface $output)
             $errorIo->comment('Provide the name of a bundle as the first argument of this command to dump its configuration. (e.g. <comment>debug:config FrameworkBundle</comment>)');
             $errorIo->comment('For dumping a specific option, add its path as the second argument of this command. (e.g. <comment>debug:config FrameworkBundle serializer</comment> to dump the <comment>framework.serializer</comment> configuration)');
 
-            return;
+            return 0;
```
Comment (ihmels) [inline src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: Doesn't `1` have to be returned here?

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php [hunk 4]
```diff
@@ -101,20 +101,22 @@ protected function execute(InputInterface $input, OutputInterface $output)
...
         }
 
         try {
             $config = $this->getConfigForPath($config, $path, $extensionAlias);
         } catch (LogicException $e) {
             $errorIo->error($e->getMessage());
 
-            return;
+            return 1;
```
Comment (stof) [inline src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: that one should be done in older branches too, as it fixes a bug (as a success exit code was used)

Comment (jschaedl) [reply src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: The lowest branch this needs to be fixed in is 3.4, right?

Comment (fabpot) [reply src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php]: That's correct.

**Comment by nicolas-grekas** [comment]
Thank you @jschaedl.
