### PR TITLE
[Cache] Use correct expiry in ChainAdapter

### LINKED ISSUE #38632: [ChainCacheAdapter] TTL not correctly set
**Symfony version(s) affected**: 5.1.7 (not tested on other version)

**Description**  

I will only talk about TTL in this issue because it's more easy to show problem, but it can be with all properties who can be set in ItemInterface. I work with [CacheContracts](https://symfony.com/doc/current/components/cache.html#cache-component-contracts)  
When we set manually TTL for an item (like in documentation), only the last adapter configured is correctly set with the good TTL

**How to reproduce**  

Cache config with **default TTL to 2000**
```yaml
cache:
        default_redis_provider: redis://%env(REDIS_HOST)%:%env(int:REDIS_PORT)%
        pools:
            chain_cache:
                default_lifetime: 2000
                adapters:
                    - cache.adapter.apcu
                    - cache.adapter.redis
```
Demo controller to add value in cache with a **TTL value to 5000**
```php
     /**
     * @Route("/", methods={"GET"})
     */
    public function index(CacheInterface $chainCache) {
        $chainCache->get('chain', function (ItemInterface $item) {
            $item->expiresAfter(5000);
            return 'chain';
        });
    }
```
And to see problem we need to add breakpoint, see **Additional context** for example

**Possible Solution**  

Don't know for the moment 
But callback function (defined in my controller) are executed only for the last adapter because the [callback](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Cache/Adapter/ChainAdapter.php#L97) are replaced to chain other adapters configured

**Additional context**  

_The value set in controller not to be cached, clear cache if you're not sure_
Add breakpoint [here](https://github.com/symfony/cache-contracts/blob/main/CacheTrait.php#L71) and add variable in debugger `$metadata['expiry']-time()` to see ttl
I screen result below in order : 
 - First 'loop' it's `RedisAdapter` called with a TTL to 5000 (redis is the last adapter configured in my config)
image
 - Next (and last beacause I have configured only 2 adapters), it's `ApcuAdapter` with a TTL to 2000 (default value) and not 5000
image

I also check in redis (with redis-cli + redis library php) and apcu (with [apcu_cache_info](https://www.php.net/manual/fr/function.apcu-cache-info.php)) and values are set like in my screenshot

I hope you understand problem, else I can try to explain again, or in french it's will be easy for me...

Thanks

### PR DESCRIPTION
**Pull request by Nyholm**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38632
| License       | MIT
| Doc PR        | n/a

When we are syncing the chain, Let's use expiry if we have it. If not, fallback to defaultLifetime.  

TODO: 
- [x] Add tests

### CODE REVIEW

File: src/Symfony/Component/Cache/Adapter/ChainAdapter.php [hunk 1]
```diff
@@ -73,7 +73,9 @@ static function ($sourceItem, $item, $sourceMetadata = null) use ($defaultLifeti
                 $item->isHit = $sourceItem->isHit;
                 $item->metadata = $item->newMetadata = $sourceItem->metadata = $sourceMetadata;
 
-                if (0 < $defaultLifetime) {
+                if (isset($item->metadata[CacheItem::METADATA_EXPIRY])) {
+                    $item->expiresAfter((int) (0.1 + $item->metadata[CacheItem::METADATA_EXPIRY] - time()));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Cache/Adapter/ChainAdapter.php]: what about `\DateTime::createFromFormat('U.u', $item->metadata[CacheItem::METADATA_EXPIRY])` ?

**Review by nicolas-grekas — COMMENTED** [review]
Thanks, this looks good to me. Now waiting for a test case :)

File: src/Symfony/Component/Cache/Adapter/ChainAdapter.php (hunk 1 above)
Comment (Nyholm) [reply src/Symfony/Component/Cache/Adapter/ChainAdapter.php]: Thank you. 

I thought about that. I decided not to (without measuring) because I didnt want to create a DateTime object that would just be created back to a int.

Comment (nicolas-grekas) [reply src/Symfony/Component/Cache/Adapter/ChainAdapter.php]: I understand. I think I'd still suggest using the object because of the increased precision it allows (the component handles the sub-second part of the expiry, as supported by DateTime).

Comment (Nyholm) [reply src/Symfony/Component/Cache/Adapter/ChainAdapter.php]: Sure. Thank you for your input.

**Comment by Nyholm** [comment]
I added a test. I needed to use an adapter that extends AbstractAdapter.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @Nyholm.

**Comment by Nyholm** [comment]
Thank you for merging.

File: src/Symfony/Component/Cache/Adapter/ChainAdapter.php [hunk 2]
```diff
@@ -73,7 +73,9 @@ static function ($sourceItem, $item, $sourceMetadata = null) use ($defaultLifeti
                 $item->isHit = $sourceItem->isHit;
                 $item->metadata = $item->newMetadata = $sourceItem->metadata = $sourceMetadata;
 
-                if (0 < $defaultLifetime) {
+                if (isset($item->metadata[CacheItem::METADATA_EXPIRY])) {
+                    $item->expiresAt(\DateTime::createFromFormat('U.u', $item->metadata[CacheItem::METADATA_EXPIRY]));
```
Comment (phamviet) [inline src/Symfony/Component/Cache/Adapter/ChainAdapter.php:77]: Just update to latest release with this change and it broke my site. As i know the expiry value is always a float number without precision (microsecond part). Uses `U.u` causing problem here. The format should be `U`. Can you advice?

Comment (Nyholm) [reply src/Symfony/Component/Cache/Adapter/ChainAdapter.php:77]: Can you elaborate why `U.u` casing a problem?

It seams to work: https://3v4l.org/pdadj

Comment (nicolas-grekas) [reply src/Symfony/Component/Cache/Adapter/ChainAdapter.php:77]: please open an issue with the error message you see and a reproducer or a failing test case ideally

Comment (nicolas-grekas) [reply src/Symfony/Component/Cache/Adapter/ChainAdapter.php:77]: I suppose we should use `sprintf('%.3F', ...)`
the issue happens when the expiry is an int

Comment (phamviet) [reply src/Symfony/Component/Cache/Adapter/ChainAdapter.php:77]: Yes, in my case expiry was int, not float.
```
simple.cache:
        default_lifetime: 86400
        adapters:
          - cache.adapter.apcu
          - cache.adapter.redis
```

```
public function isPartner(User $user): bool
    {
        return $this->simpleCache->get(md5((string)$user->getId() . __METHOD__), function (ItemInterface $item) use ($user) {
            $item->expiresAfter(86400 * 7); // 1 week
            $item->tag(md5((string)$user->getId()));
            
           // compute
            return false;
        });
    }
```

Comment (nicolas-grekas) [reply src/Symfony/Component/Cache/Adapter/ChainAdapter.php:77]: thanks, @phamviet would you mind sending a PR with the fix and a test case, please?
for branch 4.4

Comment (phamviet) [reply src/Symfony/Component/Cache/Adapter/ChainAdapter.php:77]: It is middle-night my time and I would do it tomorrow if it is convenient.

Comment (phamviet) [reply src/Symfony/Component/Cache/Adapter/ChainAdapter.php:77]: It is hard to me to reproduce myself today and finally i found down the problem could happen with ArrayAdapter in a race condition making expiry to be int. I'm not sure how could it happen like that. BTW, the PR is at #38879.
