### PR TITLE
[DependencyInjection][FrameworkBundle] Fix using PHP 8.1 enum as parameters

### LINKED ISSUE #44834: [DependencyInjection] Enums doesn't works when they are binded
### Symfony version(s) affected

Any version from 4.4 and PHP 8.1

### Description

Use syntax `!php/const` with an enum as parameter doesn't work properly when you want to bind the parameter.

### How to reproduce

```php
<?php
namespace App;

enum Status: string {
    case Draft =  'draft';
    case Deleted =  'deleted';
    case Published = 'published';
}
```

```yaml
# services.yaml
parameters:
    my_param: !php/const App\Status::Deleted
services:
    _defaults:
        autowire: true     
        autoconfigure: true
        bind:
            $myParam: '%my_param%'
```
```php
dd($container->getParameter('my_param')); // is OK output the enum
```
but
```php
    /**
     * @Route("/foo", name="foo")
     */
    public function index(EntityManagerInterface $entityManager, $myParam): Response
``` 
output
image

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | 4.4 
| Bug fix?      | yesish
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #44834  
| License       | MIT
| Doc PR        | N/A

While #40857 allowed using enums in DI, it does not allow using these in parameters.

This would be the actual fix for #44834, which shows the error you'll get trying to use enum as DI parameters (appart from the binding issue fixed in #44838):

image

given:

```php
namespace App;

enum Status {
    case Draft;
    case Deleted;
    case Published;
}
```

```yaml
# services.yaml
parameters:
    default_status: !php/const App\Status::Draft
```

The exception happens because the `PhpDumper` misses the leading slash:

```diff

    protected function getDefaultParameters(): array
    {
        return [
-            'default_status' => App\Status::Draft,
+            'default_status' => \App\Status::Draft,
        ];
    }
```

While this would fix using enums as DI parameters as of Symfony < 6, 
the `ParameterBagInterface::get/set` and `ContainerInterface::setParameter/getParameter` are not allowing `\UnitEnum` and adding these in phpdoc is an issue since actual typehints and return types were added as of Symfony 6.
=> So this PR is a BC break, but hopefully nobody will be hit by it 🤞🏻 

(poke @ismail1432 - 
https://twitter.com/SmaineDev/status/1476237072826613763?s=20)

### CODE REVIEW

**Comment by derrabus** [comment]
Either way, allowing enums in parameters would be a new feature. I don't think we should add that functionality to 4.4.

**Comment by ogizanagi** [comment]
I kind of agree, despite https://github.com/symfony/symfony/pull/40857 being on 4.4. But the difference is parameters never supported objects.
So let's make that clear by throwing in 4.4 and see what we can do/if we want to support enum in parameters later?

**Comment by derrabus** [comment]
Sounds good. 🙂

**Comment by nicolas-grekas** [comment]
How do we move forward on this one?

**Comment by ogizanagi** [comment]
Sorry, didn't have time to go further. The plan was to throw either in the `ParameterBag` or the `PhpDumper` so that's explicit enum types are not supported as parameters ; since it even goes against the `ParameterBagInterface::get/set` contract.

**Comment by ogizanagi** [comment]
Updated the PR so that we simply throw on attempting to set an enum or array containing an enum as a DI parameter : this should be enough for our goal: explicit the fact enums aren't supported as such.
Of course, the phpdoc already tells this, and we won't check for any other infringement to it ; but since the DI loaders allow such a thing indirectly:

```yml
# services.yaml
parameters:
    default_status: !php/const App\Status::Draft
    statuses: 
        - !php/const App\Status::Draft
        - !php/const App\Status::Deleted
        - !php/const App\Status::Published
```

we might want to handle this specific case here so the user notices it.

**Comment by nicolas-grekas** [comment]
I'm sorry I'm not super convinced by this. It would be strange to me to allow direct references to enums in service arguments, but to disallow indirect references via DI parameters:

```yaml
parameters:
    foo: !php/const Some\Enum::Case

services:
    bar: ['%foo%']
```

I'd prefer to fix supporting them when dumping, and widen the types on 6.0. I don't think anybody is going to be hit by the BC break.

**Comment by ogizanagi** [comment]
Honestly, I'd be way more satisfied this way too :)
I'll revert to the previous state of this PR.

**Comment by ogizanagi** [comment]
Alright, PR updated. Hopefully I haven't missed anything.

**Review by chalasr — APPROVED** [review]

File: src/Symfony/Bundle/FrameworkBundle/Tests/Console/Descriptor/ObjectsProvider.php [hunk 1]
```diff
@@ -61,14 +63,24 @@ public static function getRoutes()
...
-            ]),
-        ];
+        yield 'parameters_1' => new ParameterBag([
+            'integer' => 12,
+            'string' => 'Hello world!',
+            'boolean' => true,
+            'array' => [12, 'Hello world!', true],
+        ]);
+
+        if (\PHP_VERSION_ID >= 80100) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bundle/FrameworkBundle/Tests/Console/Descriptor/ObjectsProvider.php]: let's return early and unindent the rest to reduce merge conflicts

File: src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php [hunk 2]
```diff
@@ -1217,16 +1218,37 @@ public function testDumpHandlesEnumeration()
...
+        $this->assertSame(FooUnitEnum::BAR, $container->getParameter('unit_enum'));
+        $this->assertSame([FooUnitEnum::BAR, FooUnitEnum::FOO], $container->getParameter('enum_array'));
+        $this->assertStringMatchesFormat(<<<PHP
+%A
+    protected function getDefaultParameters(): array
+    {
+        return [
+            'unit_enum' => \Symfony\Component\DependencyInjection\Tests\Fixtures\FooUnitEnum::BAR,
+            'enum_array' => [
+                0 => \Symfony\Component\DependencyInjection\Tests\Fixtures\FooUnitEnum::BAR,
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php]: I think these should be part of `getDynamicParameter` instead, so that `getDefaultParameters` keeps returning a static array with no side effects (not even class loading)

Comment (ogizanagi) [reply src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php]: Done in f0acb77663bf3613877e7ad707a788bffadb5b81

File: src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php [hunk 3]
```diff
@@ -1545,12 +1546,12 @@ protected function getDefaultParameters(): array
     /**
      * @throws InvalidArgumentException
      */
-    private function exportParameters(array $parameters, string $path = '', int $indent = 12): string
+    private function exportParameters(array $parameters, string $path = '', int $indent = 12, &$hasEnum = false): string
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php]: `bool` type hint?

Comment (ogizanagi) [reply src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php]: Oops. Added

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
We stopped adding new features for supporting newer PHP versions a while ago, so this is a new feature that should go into 6.1.

**Comment by nicolas-grekas** [comment]
This is edgy, but after a private chat with @fabpot, I've got a go for merging. Now doing it.

**Review by derrabus — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @ogizanagi.
