### PR TITLE
[JsonStreamer] Fix DateTime handling in union types

### LINKED ISSUE #63268: [JsonStreamer] Nullable \DateTimeInterface is not decoded
### Symfony version(s) affected

7.4

### Description

Trying to decode a valid JSON object into a DTO fails for nullable \DateTimeInterface properties (also concrete implementations) with:

```
Unexpected "string" value for "DateTimeInterface|null".
```

The generated code seems to check for array data:

```php
$providers['DateTimeInterface|null'] = static function ($stream, $offset, $length) use ($options, $valueTransformers, $instantiator, &$providers) {
    $data = \Symfony\Component\JsonStreamer\Read\Decoder::decodeStream($stream, $offset, $length);
    if (\is_array($data)) {
        return $providers['DateTimeInterface']($data);
    }
    if (null === $data) {
        return null;
    }
    throw new \Symfony\Component\JsonStreamer\Exception\UnexpectedValueException(\sprintf('Unexpected "%s" value for "%s".', \get_debug_type($data), 'DateTimeInterface|null'));
};
return $providers['App\TestDto']($stream, 0, null);
```

### How to reproduce

```php
<?php

declare(strict_types = 1);

namespace App;

use Symfony\Component\JsonStreamer\Attribute\JsonStreamable;

#[JsonStreamable]
class TestDto
{
    public int $id;
    public \DateTimeInterface $date;
    public ?\DateTimeInterface $nullable = null;
}
```

```php
<?php

declare(strict_types = 1);

namespace App;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\JsonStreamer\StreamReaderInterface;
use Symfony\Component\TypeInfo\Type;
use Symfony\Contracts\HttpClient\HttpClientInterface;

#[AsCommand(
    name       : 'app:test',
    description: 'Test command',
)]
readonly class TestCommand
{
    public function __construct(
        private HttpClientInterface $httpClient,
        private StreamReaderInterface $jsonStreamReader,
    ) {
    }

    public function __invoke(): int
    {
        $response = $this->httpClient->request('GET', 'https://fify.website/__object.json');

        /** @var TestDto $dto */
        $dto = $this->jsonStreamReader->read($response->toStream(), Type::object(TestDto::class));

        dump($dto->id);
        dump($dto->date);
        dump($dto->nullable);

        return Command::SUCCESS;
    }
}
```

```json
{
  "id": 100,
  "date": "2026-02-03T08:38:26+01:00",
  "nullable": "2026-02-03T08:38:26+00:00"
}
```

### Possible Solution

Maybe this check isn't working correctly?

https://github.com/symfony/symfony/blob/386a8cc1c0b2809586a962b6f940063a58833792/src/Symfony/Component/JsonStreamer/Read/PhpGenerator.php#L289-L291

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | 7.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #63268
| License       | MIT

When a property has a union type involving `DateTimeInterface` (e.g. `DateTimeImmutable|int|null`), the current approach of converting the type and adding a property-level value transformer in `DateTimeTypePropertyMetadataLoader` does not work.

This is because the transformer is applied unconditionally to all values, regardless of their actual type at runtime.

This PR fixes the issue by moving `DateTimeInterface` handling from the metadata loader layer to the data model layer, introducing a `DateTimeNode` on both *read* and *write* sides (like how `BackedEnumNode` already works).
The transformation now lives inside the composite node dispatch, so it is only applied to the matching branch.

This makes `DateTimeTypePropertyMetadataLoader` unnecessary on both sides, so it is removed entirely.

In 8.1, this fix will become unnecessary thanks to an upcoming PR that will handle value objects in a more general way (and therefore will handle date times properly).

Contains #63291 to make CI pass.

### CODE REVIEW

File: src/Symfony/Component/JsonStreamer/Mapping/Read/DateTimeTypePropertyMetadataLoader.php [hunk 1]
```diff
@@ -1,53 +0,0 @@
...
-use Symfony\Component\TypeInfo\Type\ObjectType;
-
-/**
- * Transforms string to DateTimeInterface for properties with DateTimeInterface type.
- *
- * @author Mathias Arlaud <mathias.arlaud@gmail.com>
- *
- * @internal
- */
-final class DateTimeTypePropertyMetadataLoader implements PropertyMetadataLoaderInterface
```
Comment (stof) [inline src/Symfony/Component/JsonStreamer/Mapping/Read/DateTimeTypePropertyMetadataLoader.php:26]: Removing the class is a BC break that will impact existing FrameworkBundle releases (I already reported in the past that marking the class as `@internal` was flawed because that class was meant to be instantiated outside the component). You need to deprecate the class instead.

Comment (mtarld) [reply src/Symfony/Component/JsonStreamer/Mapping/Read/DateTimeTypePropertyMetadataLoader.php:26]: Oops, you're right thanks. I gonna make them no-op instead.

File: src/Symfony/Component/JsonStreamer/Mapping/Read/DateTimeTypePropertyMetadataLoader.php [hunk 2]
```diff
@@ -11,17 +11,14 @@
...
-use Symfony\Component\TypeInfo\Type\ObjectType;
 
 /**
- * Transforms string to DateTimeInterface for properties with DateTimeInterface type.
- *
  * @author Mathias Arlaud <mathias.arlaud@gmail.com>
  *
  * @internal
+ *
+ * TODO: deprecate in 8.1, DateTime handling is now done at the data model level
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonStreamer/Mapping/Read/DateTimeTypePropertyMetadataLoader.php]: better remove, and send the PR right away (same below)

File: src/Symfony/Component/JsonStreamer/Read/PhpGenerator.php [hunk 3]
```diff
@@ -116,7 +126,7 @@ private function generateProviders(DataModelNodeInterface $node, bool $decodeFro
             $php .= $decodeFromStream ? $this->line('$data = \\'.Decoder::class.'::decodeStream($stream, $offset, $length);', $context) : '';
 
             foreach ($node->getNodes() as $n) {
-                $value = $this->canBeDecodedWithJsonDecode($n, $decodeFromStream) ? $this->generateValueFormat($n, '$data') : '$providers['.$this->quote($n->getIdentifier()).']($data)';
+                $value = $this->canBeDecodedWithJsonDecode($n, $decodeFromStream) ? $this->generateValueFormat($n, '$data') : '$providers['.$this->quote($n->getIdentifier())."]($arguments)";
```
Comment (nicolas-grekas) [inline src/Symfony/Component/JsonStreamer/Read/PhpGenerator.php:129]: rebase needed?

**Comment by nicolas-grekas** [comment]
Thank you @mtarld.
