### PR TITLE
[Cache] Throw exception if incompatible version of psr/simple-cache is used

### LINKED ISSUE #44738: [Cache] Psr16Cache not compatible with psr/simple-cache 3.0 in older Symfony versions
### Symfony version(s) affected

<6.0.0

### Description

On older, supported versions of Symfony (4.4, 5.3, and 5.4) the `Psr16Cache` class is not compatible with `psr/simple-cache:3.0.0`. Trying to use those versions together results in this error:

> PHP Fatal error:  Declaration of Symfony\Component\Cache\Psr16Cache::get($key, $default = null) must be compatible with Psr\SimpleCache\CacheInterface::get(string $key, mixed $default = null): mixed

Users must either upgrade to Symfony 6.0 or downgrade `psr/simple-cache` to 1.x or 2.x.

Composer does not currently prevent users from installing these conflicting versions.  This causes application errors for users who aren't fixing transitive dependencies like `psr/simple-cache` to a specific version and use tools like `composer update` or Dependabot to upgrade those transitive dependencies.

### How to reproduce

Create a `composer.json` file like this:

```json
{
    "require": {
        "psr/simple-cache": "^3.0",
        "symfony/cache": "5.4.*"
    }
}
```

And then try running this simple PHP script:

```php
<?php

use Symfony\Component\Cache\Adapter\ArrayAdapter;
use Symfony\Component\Cache\Psr16Cache;

require_once 'vendor/autoload.php';

$cache = new Psr16Cache(new ArrayAdapter());
```

The issue also occurs with `symfony/cache` constraints of `5.3.*` and `4.4.*`.

### Possible Solution

I see two possible solutions:

1. Add `psr/simple-cache` as a non-dev dependency containing the supported version ranges; or
2. Add `psr/simple-cache` to the `conflict` section for versions >=3.0.0

Either approach would ensure that users aren't able to install incompatible versions.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by colinodell**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44738
| License       | MIT
| Doc PR        | n/a

Addresses #44738 by throwing an explanatory exception when an incompatible version of psr/simple-log is used.

❗ **Important:** This change should not be included in 6.0+, as those newer versions do not have this compatibility issue!  This commit should instead be reverted during that merge.

### CODE REVIEW

File: src/Symfony/Component/Cache/Psr16Cache.php [hunk 1]
```diff
@@ -19,6 +20,12 @@
 use Symfony\Component\Cache\Exception\InvalidArgumentException;
 use Symfony\Component\Cache\Traits\ProxyTrait;
 
+if (class_exists(InstalledVersions::class) && InstalledVersions::isInstalled('psr/simple-cache')) {
+    if (version_compare(InstalledVersions::getVersion('psr/simple-cache'), '3.0.0', '>=')) {
```
Comment (derrabus) [inline src/Symfony/Component/Cache/Psr16Cache.php]: There's `InstalledVersions::satisfies()` for this kind of query: https://getcomposer.org/doc/07-runtime.md#knowing-whether-package-x-is-installed-in-version-y

**Review by derrabus — COMMENTED** [review]
I wonder if we should check the return type of a method of the `CacheInterface` instead.

File: src/Symfony/Component/Cache/Psr16Cache.php (hunk 1 above)
Comment (colinodell) [reply src/Symfony/Component/Cache/Psr16Cache.php]: That would require adding `"composer/semver": "^3.0"` as a dependency of `symfony/cache`.  Is that acceptable?

File: src/Symfony/Component/Cache/Psr16Cache.php [hunk 2]
```diff
@@ -19,6 +20,12 @@
 use Symfony\Component\Cache\Exception\InvalidArgumentException;
 use Symfony\Component\Cache\Traits\ProxyTrait;
 
+if (class_exists(InstalledVersions::class) && InstalledVersions::isInstalled('psr/simple-cache')) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Cache/Psr16Cache.php]: We should use a feature test instead, based on reflection I suppose

File: src/Symfony/Component/Cache/Psr16Cache.php [hunk 3]
```diff
@@ -19,6 +20,12 @@
...
+    if (version_compare(InstalledVersions::getVersion('psr/simple-cache'), '3.0.0', '>=')) {
+        throw new \RuntimeException(sprintf('psr/simple-cache "%s" is not compatible with this version of symfony/cache. Please upgrade symfony/cache to 6.0+ or downgrade psr/simple-cache to v1.x or 2.x.', InstalledVersions::getPrettyVersion('psr/simple-cache')));
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Cache/Psr16Cache.php]: Please throw a Logo exception instead

File: src/Symfony/Component/Cache/Psr16Cache.php (hunk 2 above)
Comment (colinodell) [reply src/Symfony/Component/Cache/Psr16Cache.php]: I've force-pushed 9a729120ba which checks for a return type and throws an exception if one is defined

File: src/Symfony/Component/Cache/Psr16Cache.php (hunk 3 above)
Comment (colinodell) [reply src/Symfony/Component/Cache/Psr16Cache.php]: I've force-pushed 9a729120ba which throws a `LogicException` instead

File: src/Symfony/Component/Cache/Psr16Cache.php [hunk 4]
```diff
@@ -11,6 +11,7 @@
 
 namespace Symfony\Component\Cache;
 
+use Composer\InstalledVersions;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Cache/Psr16Cache.php]: Let's use 3.0+ as version number and drop using this class

File: src/Symfony/Component/Cache/Psr16Cache.php (hunk 1 above)
Comment (derrabus) [reply src/Symfony/Component/Cache/Psr16Cache.php]: I wasn't aware of that. No, we should not do that.

File: src/Symfony/Component/Cache/Psr16Cache.php (hunk 4 above)
Comment (colinodell) [reply src/Symfony/Component/Cache/Psr16Cache.php]: Sounds good! Fixed and force-pushed :)

**Review by nicolas-grekas — APPROVED** [review]
LGTM.
Can you please confirm that this effectively improves the situation by giving the patch a try on the case you had?

**Comment by colinodell** [comment]
> Can you please confirm that this effectively improves the situation by giving the patch a try on the case you had?

Performing a quick test directly within the component's source directory shows that the exception is indeed only thrown when psr/simple-cache 3.0 is installed:

image

This does not prevent the installation of the conflicting version as I originally hoped (and thus the oddly-named feature branch here), but it at least provides a clear explanation of what's wrong and how to correct it, which is good enough for me and my library's users :)

**Review by derrabus — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @colinodell.

**Comment by fabpot** [comment]
Code reverted on 6.0+
