### PR TITLE
[Messenger] Fix BC layer for stamps moved into separate packages

### LINKED ISSUE #37616: [Messenger] BC break in SF 5.0 for stamps due to changes stamp classes
**Symfony version(s) affected**: >=5.0

**Description**  
Moving the transports to separate packages in #35422 broke BC for the stamps.

**How to reproduce**  
Using the deprecated classes to fetch stamps does not work anymore since the stamps are now added to the envelope using the new classes. So this code `$envelope->last(\Symfony\Component\Messenger\Transport\AmqpExt\AmqpReceivedStamp::class);` does not find the stamp anymore.

**Possible Solution**  
Duplicate the stamps in the evelope with the new class and deprecated classes. Or add some logic in the retrieving methods to know about new and old class names.

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | 5.1 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #37616 
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

File: src/Symfony/Component/Messenger/Tests/EnvelopeTest.php [hunk 1]
```diff
@@ -114,6 +118,40 @@ public function testWrapWithEnvelope()
...
+        $envelope = new Envelope(new \stdClass(), [
+            $s1 = new LegacyDoctrineReceivedStamp(1),
+            $s2 = new LegacyRedisReceivedStamp(2),
+            $s3 = new LegacyDoctrineReceivedStamp(3),
+        ]);
+
+        self::assertSame([
+            DoctrineReceivedStamp::class => [$s1, $s3],
+            RedisReceivedStamp::class => [$s2],
+        ], $envelope->all());
```
Comment (ogizanagi) [inline src/Symfony/Component/Messenger/Tests/EnvelopeTest.php:138]: Unfortunately, I think we cannot do much for the case someone is using `Envelope::all()` with no type argument and still using the alias instead of the new fqcn to do their things.

File: src/Symfony/Component/Messenger/Tests/EnvelopeTest.php [hunk 2]
```diff
@@ -114,6 +118,40 @@ public function testWrapWithEnvelope()
...
+
+    /**
+     * To be removed in 6.0.
+     *
+     * @group legacy
+     */
+    public function testWithAliases()
+    {
+        $envelope = new Envelope(new \stdClass(), [
+            $s1 = new LegacyDoctrineReceivedStamp(1),
```
Comment (Tobion) [inline src/Symfony/Component/Messenger/Tests/EnvelopeTest.php:130]: could you add another test where the new class stamps are added to the envelope but fetching happens with the old aliases.

Comment (ogizanagi) [reply src/Symfony/Component/Messenger/Tests/EnvelopeTest.php:130]: Like this ? https://github.com/symfony/symfony/compare/abc4944bedb3bb27d9f586fd165a10ebc0ff4fa8..6f4e4ca1c4249c76abe97a6423209ae8751c292b

Comment (Tobion) [reply src/Symfony/Component/Messenger/Tests/EnvelopeTest.php:130]: it's not so much about `all` but the other tests like 
```
self::assertSame([$s1, $s3], $envelope->all(LegacyDoctrineReceivedStamp::class));
self::assertSame([$s2], $envelope->all(LegacyRedisReceivedStamp::class));
```

Comment (ogizanagi) [reply src/Symfony/Component/Messenger/Tests/EnvelopeTest.php:130]: But `new LegacyDoctrineReceivedStamp(1)` or `new DoctrineReceivedStamp(1)` is strictly the same thing; `LegacyDoctrineReceivedStamp` just being an alias to the `DoctrineReceivedStamp` class, instantiating the envelope with it or with the new fqcn would actually be instantiating the exact same objects. 
Only the alias or fqcn as strings matters here. Instantiating an object with the alias or fqcn doesn't for the php engine.

I'd rather change to instantiating with the new fqcns only if it brings confusion.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @ogizanagi.
