### PR TITLE
[Yaml] Fix for #36624; Allow PHP constant as first key in block

### LINKED ISSUE #36624: Using a PHP class constant for a key in a YAML hash as a method argument produces a ParseException
**Symfony version(s) affected**: 4.4.7

**Description**  
Virtually the same as https://github.com/symfony/symfony/issues/35179 but with different exceptions.

When trying to use a PHP class constant as a YAML key for a hash (as a method argument), I receive one of the following.
* a `\Symfony\Component\Yaml\Exception\ParseException` with the message `The constant "\VENDOR\PRODUCT\Example" is not defined at line 7 (near "!php/const \VENDOR\PRODUCT\Example").` if I use **YAML Variant A** below.
* a `\Symfony\Component\Yaml\Exception\ParseException` with the message `Malformed inline YAML string: ""\VENDOR\PRODUCT\Example" at line 7 (near ""\VENDOR\PRODUCT\Example").` if I use **YAML Variant B** below. I observe the same behavior when using single quotes.

**How to reproduce**
Using the following class and Symfony YAML DI files produces the above.
```php
<?php
declare(strict_types=1);

namespace VENDOR\PRODUCT;

class Example
{
    public const CONSTANT_1 = 'constant_1';
    public const CONSTANT_2 = 'constant_2';

    private $Options;

    public function addOptions(array $options): Example
    {
        $this->Options[] = $options;

        return $this;
    }
}
```
```yml
# YAML Variant A
services:
  VENDOR\PRODUCT\Example:
    class: VENDOR\PRODUCT\Example
    public: false # probably unrelated
    shared: true # probably unrelated
    calls:
      - [addOptions, [{
          !php/const \VENDOR\PRODUCT\Example::CONSTANT_1: 'value_0',
          key_1: "value_1",
          key_2: "value_2"
        }]]
```
```yml
# YAML Variant B
services:
  VENDOR\PRODUCT\Example:
    class: VENDOR\PRODUCT\Example
    public: false # probably unrelated
    shared: true # probably unrelated
    calls:
      - [addOptions, [{
          !php/const "\VENDOR\PRODUCT\Example::CONSTANT_1": 'value_0',
          key_1: "value_1",
          key_2: "value_2"
        }]]
```

Also, the control case and global PHP constants (in both variants) work as expected, i.e:
```yml
# YAML Variant A
services:
  VENDOR\PRODUCT\Example:
    class: VENDOR\PRODUCT\Example
    public: false # probably unrelated
    shared: true # probably unrelated
    calls:
      - [addOptions, [{
          !php/const PHP_INT_MAX: "value_0",
          key_1: "value_1",
          key_2: "value_2"
        }]]
```
```yml
# YAML Variant B
services:
  VENDOR\PRODUCT\Example:
    class: VENDOR\PRODUCT\Example
    public: false # probably unrelated
    shared: true # probably unrelated
    calls:
      - [addOptions, [{
          !php/const "PHP_INT_MAX": "value_0",
          key_1: "value_1",
          key_2: "value_2"
        }]]
```

### PR DESCRIPTION
**Pull request by jnye**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36624 
| License       | MIT
| Doc PR        | 

When using a PHP constant in the first key of a mapping the parser would throw an exception. However if you used a PHP constant in any other key but the first it was allowed. This fix allows PHP constant as the first key.

I've included a test for this parser error along with the fix.

### CODE REVIEW

File: src/Symfony/Component/Yaml/Tests/ParserTest.php [hunk 1]
```diff
@@ -2171,7 +2187,7 @@ public function testEvalRefException()
     public function testDetectCircularReferences($yaml)
     {
         $this->expectException('Symfony\Component\Yaml\Exception\ParseException');
-        $this->expectExceptionMessage('Circular reference [foo, bar, foo] detected');
+        $this->expectExceptionMessage('Circular reference [foo, bar, "foo"] detected');
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Tests/ParserTest.php:2190]: This should be reverted IMO.

Comment (jnye) [reply src/Symfony/Component/Yaml/Tests/ParserTest.php]: Reverted.

File: src/Symfony/Component/Yaml/Parser.php [hunk 2]
```diff
@@ -230,8 +230,12 @@ private function doParse($value, $flags)
                         $this->parseBlock($this->getRealCurrentLineNb() + 1, $this->getNextEmbedBlock(null, true), $flags)
                     );
                 } else {
-                    if (isset($values['leadspaces'])
-                        && self::preg_match('#^(?P<key>'.Inline::REGEX_QUOTED_STRING.'|[^ \'"\{\[].*?) *\:(\s+(?P<value>.+?))?\s*$#u', $this->trimTag($values['value']), $matches)
+                    if (
+                        isset($values['leadspaces'])
+                        && (
+                            0 === strpos($values['value'], '!php/const')
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Parser.php:236]: I wonder if we should consider other tags (like `!!float`) too.

Comment (jnye) [reply src/Symfony/Component/Yaml/Parser.php:236]: Test still pass if the statement here just checks for a starting '!' instead of  '!php/const'. That should allow other tags in addition to PHP constants as keys.

File: src/Symfony/Component/Yaml/Parser.php [hunk 3]
```diff
@@ -230,8 +230,12 @@ private function doParse($value, $flags)
                         $this->parseBlock($this->getRealCurrentLineNb() + 1, $this->getNextEmbedBlock(null, true), $flags)
                     );
                 } else {
-                    if (isset($values['leadspaces'])
-                        && self::preg_match('#^(?P<key>'.Inline::REGEX_QUOTED_STRING.'|[^ \'"\{\[].*?) *\:(\s+(?P<value>.+?))?\s*$#u', $this->trimTag($values['value']), $matches)
+                    if (
+                        isset($values['leadspaces'])
+                        && (
+                            '!' === substr($values['value'], 0, 1)
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Parser.php:236]: `isset($values['value']) && '!' === $values['value']][0]`?

**Review by xabbuh — COMMENTED** [review]
Maybe we could expand the test to check for more tags using a data provider.

File: src/Symfony/Component/Yaml/Parser.php [hunk 4]
```diff
@@ -230,8 +230,12 @@ private function doParse($value, $flags)
                         $this->parseBlock($this->getRealCurrentLineNb() + 1, $this->getNextEmbedBlock(null, true), $flags)
                     );
                 } else {
-                    if (isset($values['leadspaces'])
-                        && self::preg_match('#^(?P<key>'.Inline::REGEX_QUOTED_STRING.'|[^ \'"\{\[].*?) *\:(\s+(?P<value>.+?))?\s*$#u', $this->trimTag($values['value']), $matches)
+                    if (
+                        isset($values['leadspaces'])
+                        && (
+                            '!' === $values['value'][0]
```
Comment (xabbuh) [inline src/Symfony/Component/Yaml/Parser.php:236]: Are we sure that `$values['value'][0]` is always set here?

Comment (jnye) [reply src/Symfony/Component/Yaml/Parser.php:236]: Yes, it's checked in the first part of the if statement above.

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jnye.
