### PR TITLE
Profiler respect stateless attribute

### LINKED ISSUE #50037: [WebProfilerBundle] Profiler is not stateless
### Symfony version(s) affected

`5.4.21` `6.2.8`

### Description

I have a SPA and I'm importing all routes in stateless mode

I'm having the error `Session was used while the request was declared stateless` beacause Profier is not stateless

### How to reproduce

Edit Kernel.php to be stateless
```php
        $routes->import($confDir.'/{routes}/*'.self::CONFIG_EXTS, 'glob')->prefix('/api/')->stateless();
        $routes->import($confDir.'/{routes}/'.$this->environment.'/**/*'.self::CONFIG_EXTS, 'glob')->prefix('/api/')->stateless();
        $routes->import($confDir.'/{routes}'.self::CONFIG_EXTS, 'glob')->prefix('/api/')->stateless();
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alamirault**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #50037
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Now that https://github.com/symfony/symfony/pull/50198 forward `_stateless` attribute in fragments, this PR check this attribute and make profiler stateless when is required.

I don't know which tests I have to add because session is not checked. (I checked on reproducer and it's ok)

### CODE REVIEW

**Comment by MatTheCat** [comment]
#50198 was a new feature so it is only available on the 6.3 branch :sweat_smile: 

I looked for a way to test this and it seems we have to update `WebProfilerBundleKernel` to allow configuring the debug mode.

File: src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php [hunk 1]
```diff
@@ -176,7 +176,7 @@ public function searchBarAction(Request $request): Response
             $this->cspHandler->disableCsp();
         }
 
-        if (!$request->hasSession()) {
+        if (true === $request->attributes->getBoolean('_stateless') || !$request->hasSession()) {
```
Comment (stof) [inline src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php]: `true === ` should be removed. There is no need to turn a boolean into another (same) boolean

Comment (stof) [inline src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php]: Actually, this code looks broken to me. When we don't have a session, we should still support reading the query string.

File: src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php [hunk 2]
```diff
@@ -272,7 +272,7 @@ public function searchAction(Request $request): Response
         $limit = $request->query->get('limit');
         $token = $request->query->get('token');
 
-        if ($request->hasSession()) {
+        if (false === $request->attributes->getBoolean('_stateless') && $request->hasSession()) {
```
Comment (stof) [inline src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php]:
```suggestion
        if (!$request->attributes->getBoolean('_stateless') && $request->hasSession()) {
```

**Review by stof — COMMENTED** [review]
This should be done in 6.3 IMO as it relies on the previous PR that is merged in 6.3

**Review by stof — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @alamirault.

**Comment by bigfoot90** [comment]
Didn't work if firewall is stateless.

**security.yaml**
```yml
security:
  ---
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt))/
      security: false

    api:
      pattern:    ^/api
#      stateless:  true
      http_basic: ~
```

File: src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php [hunk 3]
```diff
@@ -172,7 +174,11 @@ public function searchBarAction(Request $request): Response
 
         $this->cspHandler?->disableCsp();
 
-        $session = $request->hasSession() ? $request->getSession() : null;
+
+        $session = null;
+        if ($request->attributes->getBoolean('_stateless') && $request->hasSession()) {
```
Comment (themasch) [inline src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php:179]: I know I am late, but I thought posting it here was less interruptive then creating a new issue or discussion for this question: 

The PR touches 3 placed where it gets the session and adds checks for the `_stateless` request attribute. 
Two checks check for `!stateless && hasSession` while one of them (in `searchBarAction`)  checks for `stateless && hasSession` (without the `!`). 

I found this while debugging for what starts `Session was used while the request was declared stateless.` when calling the profiler. As far as I can tell, the only place using the session there is the this spot. 

This line looks incorret to me, I think its missing the `!` in front.  But since I'm probably wrong (since this is like this for a year now, with no one noticing) I'd like to learn why I am wrong!

Comment (MatTheCat) [reply src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php:179]: Just tested and you’re not wrong. Maybe you really are the first to notice :sweat_smile:

Comment (themasch) [reply src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php:179]: If I understand the implications of this correct, then that means that for users that have `stateless: false`, restoring the search bar state from session should not work, as it would not use the session in those cases. It would only use the session if `stateless: true`  (e.g. when there should be no session). Correct?

Comment (MatTheCat) [reply src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php:179]: > for users that have `stateless: false`, restoring the search bar state from session should not work

Yes, that also includes users who did not set `_stateless`. Are you up for a PR? Looks like you already know the fix!

Comment (themasch) [reply src/Symfony/Bundle/WebProfilerBundle/Controller/ProfilerController.php:179]: I can give it a try: https://github.com/symfony/symfony/pull/57679 
Hope thats correct so far.
