### PR TITLE
[PropertyInfo] Fix calling same-named method with required args instead of reading public property

### LINKED ISSUE #62733: PropertyAccessor treats methods as properties and invokes them during serialization
### Symfony version(s) affected

7.x.x

### Description

When serializing an object with symfony/serializer, the PropertyAccess component incorrectly decides whether to read a public property or call a method with the same name.

If a class contains public readonly properties and also defines methods with identical names, the PropertyAccessor attempts to invoke the method instead of reading the property, which leads to a runtime error.

### How to reproduce

Repository: https://github.com/root-aza/symfony-issue-62733

### Possible Solution

_No response_

### Additional Context

<details>
  <summary>StackTrace</summary>
  
```log

PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function DocumentState::loaded(), 0 passed in /Users/aza/PhpstormProjects/symfony-issue-61552/vendor/symfony/property-access/PropertyAccessor.php on line 401 and exactly 1 expected in /Users/aza/PhpstormProjects/symfony-issue-61552/app.php:72
Stack trace:
#0 /Users/aza/PhpstormProjects/symfony-issue-61552/vendor/symfony/property-access/PropertyAccessor.php(401): DocumentState::loaded()
#1 /Users/aza/PhpstormProjects/symfony-issue-61552/vendor/symfony/property-access/PropertyAccessor.php(102): Symfony\Component\PropertyAccess\PropertyAccessor->readProperty(Array, 'loaded', false)
#2 /Users/aza/PhpstormProjects/symfony-issue-61552/vendor/symfony/serializer/Normalizer/ObjectNormalizer.php(149): Symfony\Component\PropertyAccess\PropertyAccessor->getValue(Object(DocumentState), 'loaded')
#3 /Users/aza/PhpstormProjects/symfony-issue-61552/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(198): Symfony\Component\Serializer\Normalizer\ObjectNormalizer->getAttributeValue(Object(DocumentState), 'loaded', 'json', Array)
#4 /Users/aza/PhpstormProjects/symfony-issue-61552/vendor/symfony/serializer/Serializer.php(152): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize(Object(DocumentState), 'json', Array)
#5 /Users/aza/PhpstormProjects/symfony-issue-61552/vendor/symfony/serializer/Serializer.php(131): Symfony\Component\Serializer\Serializer->normalize(Object(DocumentState), 'json', Array)
#6 /Users/aza/PhpstormProjects/symfony-issue-61552/app.php(80): Symfony\Component\Serializer\Serializer->serialize(Object(DocumentState), 'json')
#7 {main}
  thrown in /Users/aza/PhpstormProjects/symfony-issue-61552/app.php on line 72

Fatal error: Uncaught ArgumentCountError: Too few arguments to function DocumentState::loaded(), 0 passed in /Users/aza/PhpstormProjects/symfony-issue-61552/vendor/symfony/property-access/PropertyAccessor.php on line 401 and exactly 1 expected in /Users/aza/PhpstormProjects/symfony-issue-61552/app.php on line 72

ArgumentCountError: Too few arguments to function DocumentState::loaded(), 0 passed in /Users/aza/PhpstormProjects/symfony-issue-61552/vendor/symfony/property-access/PropertyAccessor.php on line 401 and exactly 1 expected in /Users/aza/PhpstormProjects/symfony-issue-61552/app.php on line 72

Call Stack:
    0.0001     407192   1. {main}() /Users/aza/PhpstormProjects/symfony-issue-61552/app.php:0
    0.0086    2476064   2. Symfony\Component\Serializer\Serializer->serialize() /Users/aza/PhpstormProjects/symfony-issue-61552/app.php:80
    0.0086    2476440   3. Symfony\Component\Serializer\Serializer->normalize() /Users/aza/PhpstormProjects/symfony-issue-61552/vendor/symfony/serializer/Serializer.php:131
    0.0086    2477408   4. Symfony\Component\Serializer\Normalizer\ObjectNormalizer->normalize() /Users/aza/PhpstormProjects/symfony-issue-61552/vendor/symfony/serializer/Serializer.php:152
    0.0090    2518784   5. Symfony\Component\Serializer\Normalizer\ObjectNormalizer->getAttributeValue() /Users/aza/PhpstormProjects/symfony-issue-61552/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:198
    0.0091    2518784   6. Symfony\Component\PropertyAccess\PropertyAccessor->getValue() /Users/aza/PhpstormProjects/symfony-issue-61552/vendor/symfony/serializer/Normalizer/ObjectNormalizer.php:149
    0.0091    2519000   7. Symfony\Component\PropertyAccess\PropertyAccessor->readProperty() /Users/aza/PhpstormProjects/symfony-issue-61552/vendor/symfony/property-access/PropertyAccessor.php:102
    0.0091    2524440   8. DocumentState::loaded() /Users/aza/PhpstormProjects/symfony-issue-61552/vendor/symfony/property-access/PropertyAccessor.php:401

```
</details>

### PR DESCRIPTION
**Pull request by makraz**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #62733 
| License       | MIT

- Fixes PropertyAccess choosing a same‑named method over a public property when the method requires parameters.
- Ensures jQuery‑style accessors (methods named exactly like the property) are only considered if they have zero required parameters.
- Prevents `ArgumentCountError` during serialization and aligns behavior with standard getter rules (`getX()/isX()/hasX()/canX()`), which already require zero required parameters.

### CODE REVIEW

File: src/Symfony/Component/PropertyAccess/Tests/PropertyAccessorTest.php [hunk 1]
```diff
@@ -52,6 +52,26 @@ protected function setUp(): void
...
 
+    public function testPrefersPropertyOverMethodWithSameNameAndRequiredArgs()
+    {
+        $obj = new class {
+            public readonly bool $loaded;
+
+            public function __construct()
+            {
+                $this->loaded = true;
+            }
```
Comment (nicolas-grekas) [inline src/Symfony/Component/PropertyAccess/Tests/PropertyAccessorTest.php]: I suppose we don't need this boilerplate?
```suggestion
            public bool $loaded = true;
```

File: src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php [hunk 2]
```diff
@@ -388,8 +388,10 @@ public function getReadInfo(string $class, string $property, array $context = []
 
         if ($allowGetterSetter && $reflClass->hasMethod($getsetter) && ($reflClass->getMethod($getsetter)->getModifiers() & $this->methodReflectionFlags)) {
             $method = $reflClass->getMethod($getsetter);
-
-            return new PropertyReadInfo(PropertyReadInfo::TYPE_METHOD, $getsetter, $this->getReadVisibilityForMethod($method), $method->isStatic(), false);
+            // Only consider jQuery-style accessors when they don't require parameters
+            if (0 === $method->getNumberOfRequiredParameters()) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php]:
```suggestion
            if (!$method->getNumberOfRequiredParameters()) {
```

**Review by nicolas-grekas — APPROVED** [review]

**Comment by makraz** [comment]
@nicolas-grekas thanks for the suggestion all resolved

**Comment by nicolas-grekas** [comment]
Thank you @makraz !
