### PR TITLE
[DependencyInjection] Fix ignore invalid_reference behavior param for the some services

### LINKED ISSUE #57560: [DI] The "kernel" service is synthetic ServiceNotFoundException on console terminate listener
### Symfony version(s) affected

6.4.8

### Description

I got an error on `ConsoleTerminateEvent`. See STR below 

```
In Container.php line 246:
                                                                                             
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                 
  The "kernel" service is synthetic, it needs to be set at boot time before it can be used.  
                                                                                             

Exception trace:
  at /var/www/packeton/vendor/symfony/dependency-injection/Container.php:246
 Symfony\Component\DependencyInjection\Container::make() at /var/www/packeton/vendor/symfony/dependency-injection/Container.php:211
 Symfony\Component\DependencyInjection\Container->get() at /var/www/packeton/var/cache/dev/ContainerHH4zglt/Packeton_KernelDevDebugContainer.php:576
 ContainerHH4zglt\Packeton_KernelDevDebugContainer::get_Container_Private_ProfilerService() at /var/www/packeton/var/cache/dev/ContainerHH4zglt/getConsoleProfilerListenerService.php:23
 ContainerHH4zglt\getConsoleProfilerListenerService::do() at /var/www/packeton/var/cache/dev/ContainerHH4zglt/Packeton_KernelDevDebugContainer.php:541
 ContainerHH4zglt\Packeton_KernelDevDebugContainer->load() at /var/www/packeton/var/cache/dev/ContainerHH4zglt/Packeton_KernelDevDebugContainer.php:922
 ContainerHH4zglt\Packeton_KernelDevDebugContainer::ContainerHH4zglt\{closure}() at /var/www/packeton/vendor/symfony/event-dispatcher/EventDispatcher.php:235
 Symfony\Component\EventDispatcher\EventDispatcher->sortListeners() at /var/www/packeton/vendor/symfony/event-dispatcher/EventDispatcher.php:70
 Symfony\Component\EventDispatcher\EventDispatcher->getListeners() at /var/www/packeton/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:276
 Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->preProcess() at /var/www/packeton/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:133
 Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch() at /var/www/packeton/vendor/symfony/console/Application.php:1111
 Symfony\Component\Console\Application->doRunCommand() at /var/www/packeton/vendor/symfony/framework-bundle/Console/Application.php:126
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/packeton/vendor/symfony/console/Application.php:324
 Symfony\Component\Console\Application->doRun() at /var/www/packeton/vendor/symfony/framework-bundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/packeton/vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at /var/www/packeton/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /var/www/packeton/vendor/autoload_runtime.php:29
 require_once() at /var/www/packeton/bin/console:11
```

### How to reproduce

1) Create the command 

```php
<?php

namespace Packeton\Command;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\DependencyInjection\ContainerInterface;

#[AsCommand('okvpn:test')]
class TestCommand extends Command
{
    public function __construct(
        #[Autowire(service: 'service_container')]
        private readonly ContainerInterface $container
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $this->container->reset();

        return 0;
    }
}
```

2) launch the command  `okvpn:test` 

### Possible Solution

See PR 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by vtsykun**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes 
| New feature?  | -
| Deprecations? | -
| Issues        | Fix #57560 
| License       | MIT

This bug has more than 5 years old, but it make possible to reproduce after introducing a new console command profiler. 

PHP DI dumper may ignore invalid reference behavior in the some cases. See example.

```php
    $container->services()
        ->set('data_collector.config', ConfigDataCollector::class)
            ->call('setKernel', [service('kernel')->ignoreOnInvalid()])
            ->tag('data_collector', ['template' => '@WebProfiler/Collector/config.html.twig', 'id' => 'config', 'priority' => -255])
```

As you can see `ignoreOnInvalid` option is dropped on this line 

```php 
$container->get('kernel')
```

```php
    protected static function get_Container_Private_ProfilerService($container)
    {
        $a = new \Symfony\Bridge\Monolog\Logger('profiler');
        $a->pushProcessor(($container->privates['oro_logger.processor.log_message'] ??= new \Monolog\Processor\PsrLogMessageProcessor()));
        $a->pushProcessor(($container->privates['oro_message_queue.log.processor.add_consumer_state'] ?? self::getOroMessageQueue_Log_Processor_AddConsumerStateService($container)));
        $a->pushHandler(($container->privates['monolog.handler.main'] ?? self::getMonolog_Handler_MainService($container)));
        $a->pushHandler(($container->privates['oro_message_queue.log.handler.console'] ?? self::getOroMessageQueue_Log_Handler_ConsoleService($container)));
        ($container->privates['debug.debug_logger_configurator'] ?? self::getDebug_DebugLoggerConfiguratorService($container))->pushDebugLogger($a);

        $container->services['.container.private.profiler'] = $instance = new \Oro\Bundle\PlatformBundle\Profiler\ConfigurableProfiler(new \Oro\Bundle\PlatformBundle\Profiler\RepeatableFileProfilerStorage(('file:'.$container->targetDir.''.'/profiler')), $a, true);

        $b = ($container->services['kernel'] ?? $container->get('kernel'));
        $c = ($container->services['.virtual_request_stack'] ?? self::get_VirtualRequestStackService($container));
        $d = new \Symfony\Component\HttpClient\DataCollector\HttpClientDataCollector();
        $d->registerClient('http_client', ($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
        $d->registerClient('hwi_oauth.http_client', ($container->privates['.debug.hwi_oauth.http_client'] ?? self::get_Debug_HwiOauth_HttpClientService($container)));
        $e = new \Doctrine\Bundle\DoctrineBundle\DataCollector\DoctrineDataCollector(($container->services['doctrine'] ?? self::getDoctrineService($container)), true, NULL);

        $f = ($container->privates['doctrine.dbal.logger.profiling.default'] ??= new \Doctrine\DBAL\Logging\DebugStack());
        $g = ($container->privates['doctrine.dbal.logger.profiling.sql_validator'] ??= new \Doctrine\DBAL\Logging\DebugStack());
        $h = ($container->privates['doctrine.dbal.logger.profiling.system'] ??= new \Doctrine\DBAL\Logging\DebugStack());

        $e->addLogger('default', $f);
        $e->addLogger('sql_validator', $g);
        $e->addLogger('system', $h);
        $i = new \Oro\Bundle\EntityBundle\DataCollector\DuplicateQueriesDataCollector();
        $i->addLogger('default', $f);
        $i->addLogger('sql_validator', $g);
        $i->addLogger('system', $h);
        $j = new \Symfony\Component\HttpKernel\DataCollector\ConfigDataCollector();
        if ($container->has('kernel')) {
            $j->setKernel($b);
        }
```

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php [hunk 1]
```diff
@@ -1009,7 +1009,7 @@ private function addInlineReference(string $id, Definition $definition, string $
         $name = $this->getNextVariableName();
         $this->referenceVariables[$targetId] = new Variable($name);
 
-        $reference = ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE >= $behavior ? new Reference($targetId, $behavior) : null;
+        $reference = ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE !== $behavior ? new Reference($targetId, $behavior) : null;
```
Comment (vtsykun) [inline src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php:1036]: Perhaps, there was just a typo here and the author meant `$behavior >= ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE`. 

The bug was hidden for a long time because it can only be reproduced for "synthetic" services like `kernel` and in specific cases. But the other services replaced by null on optimization step before

**Comment by nicolas-grekas** [comment]
So, this line:
`        $b = ($container->services['kernel'] ?? $container->get('kernel'));`
should be actually
`        $b = ($container->services['kernel'] ?? $container->get('kernel', ContainerInterface::NULL_ON_INVALID_REFERENCE));`

That's what you mean?

I think this comparison in PhpDumper is on purpose but it's quite possible that we forgot about synthetic services.
Can you please add a test case?

**Comment by nicolas-grekas** [comment]
@vtsykun did you check my comment? WDYT?

**Comment by vtsykun** [comment]
> So, this line  `$b = ($container->services['kernel'] ?? $container->get('kernel'));` should be actually `$b = ($container->services['kernel'] ?? $container->get('kernel', ContainerInterface::NULL_ON_INVALID_REFERENCE));` 

Yes, exactly.

Ok I'll create a test case

**Review by nicolas-grekas — APPROVED** [review]
The `>=` made the supposition that services where all known at compile time, which is not the case when we account for synthetic services.
Test case added, thanks Claude.

**Comment by nicolas-grekas** [comment]
Thank you @vtsykun.
