### PR TITLE
[Validator] Fix fields without constraints in `Collection`

### LINKED ISSUE #53455: [Validator] Breaking changes in Collection
### Symfony version(s) affected

5.4

### Description

Before this https://github.com/symfony/validator/commit/b12535757ba38676de6294e787533bbf087a396b
```
$violations = $this->validator->validate(
            $input,
            new Assert\Collection([
                'channelName' => null,
                'reportType' => null,
                'period' => new Assert\Choice(
                    choices: (new CreateReportScheduleSpecification())->getPeriodAllowableValues(),
                ),
            ]),
        );
```

After this https://github.com/symfony/validator/commit/b12535757ba38676de6294e787533bbf087a396b
```
$violations = $this->validator->validate(
            $input,
            new Assert\Collection([
                'fields' => [
                    'channelName' => null,
                    'reportType' => null,
                    'period' => new Assert\Choice(
                        choices: (new CreateReportScheduleSpecification())->getPeriodAllowableValues(),
                    ),
                ],
            ]),
        );
```

@nicolas-grekas My application stopped working as before after this commit.

### How to reproduce

```
$input = [
            'channelName' => $input->getArgument('channelName'),
            'reportType' => $input->getArgument('reportType'),
            'period' => $input->getArgument('period'),
        ];

$violations = $this->validator->validate(
            $input,
            new Assert\Collection([
                'channelName' => null,
                'reportType' => null,
                'period' => new Assert\Choice(
                    choices: (new CreateReportScheduleSpecification())->getPeriodAllowableValues(),
                ),
            ]),
        );
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix https://github.com/symfony/symfony/pull/53133#issuecomment-1878479736, Fix #53455
| License       | MIT

Continuation of #53443.

### CODE REVIEW

File: src/Symfony/Component/Validator/Tests/Constraints/CollectionTest.php [hunk 1]
```diff
@@ -170,6 +170,49 @@ public function testEmptyFieldsInOptions()
...
+    }
+
+    /**
+     * @testWith [[]]
+     *           [null]
+     */
+    public function testEmptyConstraintListForField(?array $fieldConstraint)
+    {
+        $constraint = new Collection([
+                'foo' => $fieldConstraint,
```
Comment (OskarStark) [inline src/Symfony/Component/Validator/Tests/Constraints/CollectionTest.php]:
```suggestion
        $constraint = new Collection(
            [
                'foo' => $fieldConstraint,
```

Comment (HypeMC) [reply src/Symfony/Component/Validator/Tests/Constraints/CollectionTest.php]: Done

File: src/Symfony/Component/Validator/Constraints/Collection.php [hunk 2]
```diff
@@ -87,4 +87,35 @@ protected function getCompositeOption()
...
         return 'fields';
     }
+
+    private static function isFieldsOption($options): bool
+    {
+        if (!\is_array($options)) {
+            return false;
+        }
+
+        if ([] === $options) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraints/Collection.php]:
```suggestion
        if (!$options) {
```

File: src/Symfony/Component/Validator/Constraints/Collection.php [hunk 3]
```diff
@@ -87,4 +87,35 @@ protected function getCompositeOption()
...
+            return true;
+        }
+
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraints/Collection.php]:
```suggestion
```

File: src/Symfony/Component/Validator/Constraints/Collection.php [hunk 4]
```diff
@@ -87,4 +87,35 @@ protected function getCompositeOption()
...
+            if (null === $optionOrField) {
+                return true;
+            }
+
+            if (!\is_array($optionOrField)) {
+                return false;
+            }
+
+            if ([] !== $optionOrField && !($optionOrField[0] ?? null) instanceof Constraint) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Validator/Constraints/Collection.php]:
```suggestion
            if ($optionOrField && !($optionOrField[0] ?? null) instanceof Constraint) {
```

File: src/Symfony/Component/Validator/Constraints/Collection.php (hunk 3 above)
Comment (HypeMC) [reply src/Symfony/Component/Validator/Constraints/Collection.php]: Done

File: src/Symfony/Component/Validator/Constraints/Collection.php (hunk 4 above)
Comment (HypeMC) [reply src/Symfony/Component/Validator/Constraints/Collection.php]: Done

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/Validator/Constraints/Collection.php [hunk 5]
```diff
@@ -87,4 +87,31 @@ protected function getCompositeOption()
...
+            return false;
+        }
+
+        foreach ($options as $optionOrField) {
+            if ($optionOrField instanceof Constraint) {
+                return true;
+            }
+
+            if (null === $optionOrField) {
+                return true;
```
Comment (stof) [inline src/Symfony/Component/Validator/Constraints/Collection.php]: I think `null` could be both describing a field without constraints in the `fields` option or another option (`payload` is nullable for instance). So I would rather use `continue` here, to abstain on such value and check other ones instead of considering `null` as a positive decision (if nothing else decides, we will still end with a positive decision at the end of the loop)

Comment (HypeMC) [reply src/Symfony/Component/Validator/Constraints/Collection.php]: Yes, that makes sense, done.

**Comment by nicolas-grekas** [comment]
Thank you @HypeMC.
