### PR TITLE
[ErrorHandler] Do not call xdebug_get_function_stack() with xdebug >= 3.0 when not in develop mode

### LINKED ISSUE #40677: [ErrorHandler] FatalError raise warning if Xdebug 3 is not in develop mode
**Symfony version(s) affected**: at least since 4.4.0

**Description**
When using Xdebug 3 with `develop` mode disabled (i.e. for coverage in CI), a warning is triggered inside `Symfony\Component\ErrorHandler\Error\FatalError` due to this like of code: https://github.com/symfony/symfony/blob/ad8cc120ca9a333805fd9ac1fdb6b1548c2d2e25/src/Symfony/Component/ErrorHandler/Error/FatalError.php#L36

**How to reproduce**
 * install Xdebug 3 and enable it WITHOUT `develop` mode
 * install the Error Handler and enable it
 * throw an exception and do NOT catch it

```
Warning: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop'
```
Example of failure: https://github.com/getsentry/sentry-symfony/pull/475/checks?check_run_id=2247826488#step:9:25

So, `function_exists` is no longer good enough for safeguarding such usage. Also, it seems that checking for `xdebug.mode` from the ini is not good enough too: https://xdebug.org/docs/develop#mode
> You can also set the mode by setting the `XDEBUG_MODE` environment variable on the command-line; this will take precedence over the `xdebug.mode` setting, but will no change the value of the `xdebug.mode` setting.

### PR DESCRIPTION
**Pull request by fmata**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #40677
| License       | MIT

The PR #40787 was rejected because of env var handling in xdebug_mode. https://github.com/xdebug/xdebug/pull/737 allow us to get xdebug_mode in all cases so I think we can merge this PR safely.

Tested on my setup successfully, I have no more warning.

Thanks @ralphschindler :)

### CODE REVIEW

File: src/Symfony/Component/ErrorHandler/Error/FatalError.php [hunk 1]
```diff
@@ -33,7 +33,8 @@ public function __construct(string $message, int $code, array $error, ?int $trac
                 }
             }
         } elseif (null !== $traceOffset) {
-            if (\function_exists('xdebug_get_function_stack') && $trace = @xdebug_get_function_stack()) {
+            if (\function_exists('xdebug_get_function_stack') && \in_array(\ini_get('xdebug.mode'), ['develop', false], true)) {
+                $trace = xdebug_get_function_stack();
```
Comment (nicolas-grekas) [inline src/Symfony/Component/ErrorHandler/Error/FatalError.php]: let's do it this way to be extra sure, esp with older versions?
```suggestion
            if (\function_exists('xdebug_get_function_stack') && \in_array(\ini_get('xdebug.mode'), ['develop', false], true) && $trace = @xdebug_get_function_stack();
```

Comment (fmata) [reply src/Symfony/Component/ErrorHandler/Error/FatalError.php]: Done

**Comment by nicolas-grekas** [comment]
Thank you @fmata.
