### PR TITLE
[HttpKernel] Add support for bundles as compiler passes

### LINKED ISSUE #62470: [HttpKernel] [DI] `AbstractBundle` as `CompilerPassInterface` are not automatically registered
### Symfony version(s) affected

\>= 6.4

### Description

According to [documentation](https://symfony.com/doc/6.4/service_container/compiler_passes.html), a bundle implementing a `CompilerPassInterface` should be registered by the framework.
It is not.

### How to reproduce

Add a bundle implemented like the following to a skeleton app.

```php
class Bundle extends AbstractBundle implements CompilerPassInterface {
  public function process(ContainerBuilder $container): void { dump(__METHOD__); }
}
```

### PR DESCRIPTION
**Pull request by yceruto**
| Q             | A
| ------------- | ---
| Branch?       | 8.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #62470
| License       | MIT

Adds a bundle-level compiler pass to hook into the container compilation phase:
```php
class MyBundle extends AbstractBundle implements CompilerPassInterface
{
    public function process(ContainerBuilder $container): void
    {
        // ...
    }
}
```

### CODE REVIEW

File: src/Symfony/Component/HttpKernel/Tests/Fixtures/BundleCompilerPass/BundleAsCompilerPassBundle.php [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+ *
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\Component\HttpKernel\Tests\Fixtures\BundleCompilerPass;
+
+use stdClass;
```
Comment (nicolas-grekas) [inline src/Symfony/Component/HttpKernel/Tests/Fixtures/BundleCompilerPass/BundleAsCompilerPassBundle.php]: nope :)

**Review by nicolas-grekas — APPROVED** [review]

File: src/Symfony/Component/HttpKernel/Tests/Fixtures/BundleCompilerPass/BundleAsCompilerPassBundle.php (hunk 1 above)
Comment (yceruto) [reply src/Symfony/Component/HttpKernel/Tests/Fixtures/BundleCompilerPass/BundleAsCompilerPassBundle.php]: oops! fixed.

**Comment by nicolas-grekas** [comment]
Thank you @yceruto.
