### PR TITLE
[PhpUnitBridge] Fix ignoreFile comments

### LINKED ISSUE #45918: [PHPUnitBridge] ignoreFile does not allow comments
### Symfony version(s) affected

6.1.0

### Description

The newly introduced ignoreFile does not accept lines starting with '#' as comments.

### How to reproduce

Use an ignoreFile like

```
# PHPUnit 9.
/"PHPUnit\\Framework\\TestListener".*is deprecated/
/"PHPUnit\\Framework\\TestListenerDefaultImplementation".*is deprecated/
/xx"PHPUnit\\TextUI\\DefaultResultPrinter".*is considered internal/

```

you get an error like

```
Invalid pattern found in "/var/www/d10/core/deprecation-ignore.txt" on line "1": No ending delimiter '#' found
PHP Fatal error:  Uncaught RuntimeException: Invalid pattern found in "/var/www/d10/core/deprecation-ignore.txt" on line "1": No ending delimiter '#' found in /var/www/d10/vendor/symfony/phpunit-bridge/DeprecationErrorHandler/Configuration.php:124
Stack trace:
#0 [internal function]: Symfony\Bridge\PhpUnit\DeprecationErrorHandler\Configuration::Symfony\Bridge\PhpUnit\DeprecationErrorHandler\{closure}()
#1 /var/www/d10/vendor/symfony/phpunit-bridge/DeprecationErrorHandler/Configuration.php(129): preg_match()
#2 /var/www/d10/vendor/symfony/phpunit-bridge/DeprecationErrorHandler/Configuration.php(345): Symfony\Bridge\PhpUnit\DeprecationErrorHandler\Configuration->__construct()
#3 /var/www/d10/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php(272): Symfony\Bridge\PhpUnit\DeprecationErrorHandler\Configuration::fromUrlEncodedString()
#4 /var/www/d10/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php(185): Symfony\Bridge\PhpUnit\DeprecationErrorHandler->getConfiguration()
#5 [internal function]: Symfony\Bridge\PhpUnit\DeprecationErrorHandler->shutdown()
#6 {main}
  thrown in /var/www/d10/vendor/symfony/phpunit-bridge/DeprecationErrorHandler/Configuration.php on line 124

```

Apparently, parsing of the ignoreFile for patterns to be ignored does not consider lines starting with '#' as a comment.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mondrake**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45918
| License       | MIT

### CODE REVIEW

File: src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Configuration.php [hunk 1]
```diff
@@ -124,8 +124,8 @@ private function __construct(array $thresholds = [], $regex = '', $verboseOutput
                 throw new \RuntimeException(sprintf('Invalid pattern found in "%s" on line "%d"', $ignoreFile, 1 + $line).substr($m, 12));
             });
             try {
-                foreach (file($ignoreFile) as $line => $pattern) {
-                    if ('#' !== trim($line)[0] ?? '#') {
+                foreach (file($ignoreFile, FILE_IGNORE_NEW_LINES) as $pattern) {
```
Comment (nicolas-grekas) [inline src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Configuration.php]: The flag should be removed and $line be kept: it's used by reference in the closure above

Comment (mondrake) [reply src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Configuration.php]: Thanks, done

**Comment by nicolas-grekas** [comment]
Thank you @mondrake.
