### PR TITLE
[Serializer] Fix `readonly` property initialization from incorrect scope

### LINKED ISSUE #60846: Cannot initialize readonly property from scope
### Description

Cannot initialize readonly property from scope

Could we improve the Symfony Serializer component by implementing something similar to this:
https://github.com/doctrine/orm/pull/10059/commits/229de42fe608b74332257b6077fa53e6a3015733 ?

For php versions less then (not including) 8.4.0. Starting from 8.4.0 ReflectionProperty::setValue behavior is different

### Example

```
readonly class ParentClass {
    public string $parentProp;
}
readonly class ChildClass extends ParentClass {
    public string $childProp;
}
$serializer = new Serializer();
$data = [
    'parent_prop' => 'parentValue',
    'child_prop' => 'childValue'
];
$dto = $serializer->denormalize($data, ChildClass::class);
```

### PR DESCRIPTION
**Pull request by santysisi**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #60846 
| License       | MIT

Readonly properties couldn't be initialized during denormalization due to scope restrictions. This change checks if a property is `readonly` and uninitialized, if so, it sets the value using the declaring class's scope.

Also added a safety check to throw a `LogicException` if a `readonly` property is already initialized, to avoid accidental mutation.

### CODE REVIEW

File: src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php [hunk 1]
```diff
@@ -202,7 +203,22 @@ protected function setAttributeValue(object $object, string $attribute, mixed $v
             return;
         }
 
-        $reflectionProperty->setValue($object, $value);
+        if (!$reflectionProperty->isReadOnly()) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php:206]: I suppose we should deal with asymmetric visibility also?

Comment (santysisi) [reply src/Symfony/Component/Serializer/Normalizer/PropertyNormalizer.php:206]: Thanks for pointing that out!

I tested the current implementation using properties with asymmetric visibility in PHP 8.4 and everything works as expected. The values are correctly set using `ReflectionProperty::setValue()` without throwing errors.

I believe this is because, starting from PHP 8.4.0, `ReflectionProperty::setValue()` still bypasses visibility restrictions (including asymmetric ones)

To make this explicit, I’ve added some tests that cover this behavior specifically for PHP 8.4.

Let me know if you'd prefer a stricter approach that checks write visibility explicitly.

**Review by nicolas-grekas — APPROVED** [review]

**Review by dunglas — APPROVED** [review]

**Review by mtarld — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @santysisi.
