### PR TITLE
[DependencyInjection] Fix circular reference in autowired decorators

### LINKED ISSUE #42791: [DI] Circular reference in autowired decorators
**Symfony version(s) affected**: 5.3.7

**Description**
Autowired decorators try to inject themselves and throw
```
Circular reference detected for service "App\ServiceDecorator",
path: "App\ServiceDecorator -> App\ServiceDecorator".
```

**How to reproduce**
https://github.com/vudaltsov/symfony-di-537-decorator-circular
Clone and install — you will see the error when clearing the cache during the composer installation.

**Possible Solution**
Revert https://github.com/symfony/symfony/pull/42347

### PR DESCRIPTION
**Pull request by shyim**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #42791 
| License       | MIT
| Doc PR        | 

As the Decorator pass runs after the Autowire, the `innerServiceId` was always empty. I have changed that to `getDecoratedService` and added a test with the given example in the issue.

### CODE REVIEW

File: src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php [hunk 1]
```diff
@@ -1044,12 +1044,11 @@ public function testDoNotAutowireDecoratorWhenSeveralArgumentOfTheType()
...
         } catch (AutowiringFailedException $e) {
-            $this->assertSame('Cannot autowire service "Symfony\Component\DependencyInjection\Tests\Compiler\NonAutowirableDecorator": argument "$decorated1" of method "__construct()" references interface "Symfony\Component\DependencyInjection\Tests\Compiler\DecoratorInterface" but no such service exists. You should maybe alias this interface to one of these existing services: "Symfony\Component\DependencyInjection\Tests\Compiler\NonAutowirableDecorator", "Symfony\Component\DependencyInjection\Tests\Compiler\NonAutowirableDecorator.inner".', (string) $e->getMessage());
+            $this->assertSame('Cannot autowire service "Symfony\Component\DependencyInjection\Tests\Compiler\NonAutowirableDecorator": argument "$decorated1" of method "__construct()" references interface "Symfony\Component\DependencyInjection\Tests\Compiler\DecoratorInterface" but no such service exists. You should maybe alias this interface to one of these existing services: "Symfony\Component\DependencyInjection\Tests\Compiler\Decorated", "Symfony\Component\DependencyInjection\Tests\Compiler\NonAutowirableDecorator".', (string) $e->getMessage());
```
Comment (shyim) [inline src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php:1051]: Is that so okay? As the DecoratorPass did not run until this point the `.inner` does not exists yet 😅

**Comment by shyim** [comment]
The fabbot wants unreleated change which looks wrong :sweat_smile: 
https://fabbot.io/report/symfony/symfony/42815/b21e709d250e7eb22f9a900cf6dc9d93ab13a6de

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 2]
```diff
@@ -153,8 +153,17 @@ private function autowireCalls(\ReflectionClass $reflectionClass, bool $isRoot,
         $this->decoratedClass = null;
         $this->getPreviousValue = null;
 
-        if ($isRoot && ($definition = $this->container->getDefinition($this->currentId)) && null !== ($this->decoratedId = $definition->innerServiceId) && $this->container->has($this->decoratedId)) {
-            $this->decoratedClass = $this->container->findDefinition($this->decoratedId)->getClass();
+        if ($isRoot && ($definition = $this->container->getDefinition($this->currentId)) && $definition->getDecoratedService() && null !== ($innerId = $definition->getDecoratedService()[0]) && $this->container->has($innerId)) {
+            // If the class references to him self and is decorated, provide the inner service id and class to not get a circular reference
```
Comment (derrabus) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]:
```suggestion
            // If the class references itself and is decorated, provide the inner service id and class to not get a circular reference
```

**Review by derrabus — APPROVED** [review]

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php (hunk 2 above)
Comment (shyim) [reply src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: Is fixed 😅

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php [hunk 3]
```diff
@@ -153,8 +153,17 @@ private function autowireCalls(\ReflectionClass $reflectionClass, bool $isRoot,
...
+            // If the class references to itself and is decorated, provide the inner service id and class to not get a circular reference
+            $this->decoratedClass = $this->container->findDefinition($innerId)->getClass();
+            $decoratedDefinition = $this->container->getDefinition($this->currentId);
+            [$_, $innerId] = $decoratedDefinition->getDecoratedService();
+
+            if (null === $innerId) {
+                $innerId = $this->currentId.'.inner';
+            }
+
+            $this->decoratedId = $innerId;
```
Comment (jderusse) [inline src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]:
```suggestion
            $this->decoratedId = $decoratedDefinition[1] ?? $this->currentId.'.inner';
```

and move `$decoratedDefinition` in the if block 
```diff
- if ($isRoot && ($definition = $this->container->getDefinition($this->currentId)) && $definition->getDecoratedService() && null !== ($innerId = $definition->getDecoratedService()[0]) && $this->container->has($innerId)) {
+ if ($isRoot && ($definition = $this->container->getDefinition($this->currentId)) && ($decoratedDefinition = $definition->getDecoratedService()) && null !== ($innerId = $definition->getDecoratedService()[0]) && $this->container->has($innerId)) {

**Review by jderusse — COMMENTED** [review]
Fix the issue on my side

File: src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php (hunk 3 above)
Comment (shyim) [reply src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php]: Fixed

**Review by dunglas — APPROVED** [review]

**Review by jderusse — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @shyim.

**Comment by mbrodala** [comment]
Just to be sure: will there be a version 5.3.8 with this fix before 5.4? ATM we are unable to update to 5.3.7 due to this error.

**Comment by derrabus** [comment]
yes
