### PR TITLE
[DependencyInjection] `#[Autowire]` attribute should have precedence over bindings

### LINKED ISSUE #49082: TaggedLocator attribute does not work in controller constructor
### Symfony version(s) affected

6.2.* (and maybe other)

### Description

A wrong Container is injected when using `#[TaggedLocator('XXX')]` in an argument of a controller constructor 

### How to reproduce

add this controller

```php
class AController extends AbstractController
{
    public function __construct(
        #[TaggedLocator('foobar')]
        private readonly ContainerInterface $foo,
    ) {
    }

    #[Route('/', name: 'app_a')]
    public function index(
    ): JsonResponse
    {
        dd($this->foo);
        return $this->json([
            'message' => 'Welcome to your new controller!',
            'path' => 'src/Controller/AController.php',
        ]);
    }
}
```

### Possible Solution

We can work-arround this issue with the following constructor:

```diff
     public function __construct(
         #[TaggedLocator('foobar')]
-        private readonly ContainerInterface $foo,
+        private readonly ServiceLocator $foo,
     ) {
     }
```

but ...

### Additional Context

I guess - there is a conflict with the "ServiceSubscriberInterface"

image

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49082
| License       | MIT
| Doc PR        | -

It seems logical (I think) that the `#[Autowire]` attribute has precedence over any bindings.

### CODE REVIEW

**Comment by ruudk** [comment]
Thanks for fixing this 🙏 . Could you rebase this?

**Comment by stof** [comment]
@nicolas-grekas is it right to have to make ResolveBindingPass aware of the Autowire attribute ? Shouldn't this be handled by the AutowirePass ?

**Comment by nicolas-grekas** [comment]
I agree, the bindings pass has no reasons to know about autowiring stuff.
Can't we fix this by changing the order of the two passes?

**Comment by HypeMC** [comment]
@nicolas-grekas @stof My initial approach was to fix it in `AutowirePass`. I don't remember the exact reason, but I couldn't do it like that so I went with this instead.

I can try to change the order of the passes, but I'm worried that might break other stuff. I'll try it sometime today or tomorrow.

**Comment by nicolas-grekas** [comment]
It's also not obvious to me what we want here.

What this PR achieves is this precedence, isn't it?

1. autowiring by attribute
2. binding by type+name of argument
3. binding by type only
4. autowiring by type+name of argument
5. autowiring by type only

Dunno if we should account for that but bindings can also be defined by explicit configuration and/or by autoconfiguration.

Dunno how we can make AutowirePass achieve this ordering (or another) given that once bindings are resolved, we don't know if some argument's values came through bindings or via another path (explicit/auto config).

Maybe this approach is the most pragmatic.

WDYT?

File: src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php [hunk 1]
```diff
@@ -185,6 +186,9 @@ protected function processValue(mixed $value, bool $isRoot = false): mixed
                 if (\array_key_exists($parameter->name, $arguments) && '' !== $arguments[$parameter->name]) {
                     continue;
                 }
+                if ($parameter->getAttributes(Autowire::class, \ReflectionAttribute::IS_INSTANCEOF)) {
```
Comment (nicolas-grekas) [inline src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php]: we should at least check the `'container.ignore_attributes'` tag here
and also if the class is autowired

Comment (HypeMC) [reply src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php]: Done

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Any other opinion here? @stof?

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @HypeMC.
