### PR TITLE
[Console] Fix negated options not accessible

### LINKED ISSUE #41531: symfony/console --no-ansi option removed but present in the logic
**Symfony version(s) affected**: 5.3

**Description**
In the 5.3 version of the symfony/console we do not have the declaration of `--no-ansi` parameter anymore
https://github.com/symfony/console/blob/5.3/Application.php#L1039

BUT we have the logic with the check
https://github.com/symfony/console/blob/5.3/Application.php#L885
And in several places of this file as well.
Seems to be a bug or the code needs to be cleaned up.

**How to reproduce**
Execute the code similar to below with getting this option value
`$userOptions['colors'] = $this->options['no-colors'] || $input->getOption('no-ansi') ? false : $config['settings']['colors'];`

**Possible Solution**
To return back the definition of ` --no-ansi` parameter to the 
`Application:: getDefaultInputDefinition()`

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41531
| License       | MIT
| Doc PR        | -

Removing the `--no-ansi` option to only let the negatable option `--ansi` breaks applications that expects calling `$input->getOption('no-ansi')`

This PR provides a fallback to return the negative value of the negatable options

### CODE REVIEW

**Review by chalasr — APPROVED** [review]
Looks good to me 👍 Thanks

File: src/Symfony/Component/Console/Input/Input.php [hunk 1]
```diff
@@ -146,10 +146,17 @@ public function getOptions()
...
+                return $value;
+            }
+
+            return !$value;
+        }
+
         if (!$this->definition->hasOption($name)) {
             throw new InvalidArgumentException(sprintf('The "%s" option does not exist.', $name));
         }
-
```
Comment (fabpot) [inline src/Symfony/Component/Console/Input/Input.php]: to be reverted

**Review by fabpot — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you Jérémy.

**Comment by dereuromark** [comment]
I see a release for symfony/symfony 5.3.1 that seems to include the fix, but https://packagist.org/packages/symfony/console shows no such split package for console.
We do need it to resolve our BC breaking issues, though. Is that stilled planned or did the release go wrong?
Thank you.
