### PR TITLE
Make Symfony\Component\Debug\ExceptionHandler::setFileLinkFormat accept Null as a return type

### LINKED ISSUE #32150: Return value of Symfony\Component\Debug\ExceptionHandler::setFileLinkFormat() must be of the type string, null returned
**Symfony version(s) affected**: master

**Description**  

The variable `fileLinkFormat` is initialized everywhere in the class `Symfony\Component\Debug\ExceptionHandler` to null but here it is asking for a string
```
public function setFileLinkFormat($fileLinkFormat): string
{
    $old = $this->fileLinkFormat;
    $this->fileLinkFormat = $fileLinkFormat;
    return $old;
}
```

**How to reproduce**  

- `git clone git@github.com:symfony/website-skeleton.git .`
- `composer install`

**Additional context**  

The return type was added in PR #31996

### PR DESCRIPTION
**Pull request by jlslew**
fixes #32150 

| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #32150    
| License       | MIT
| Doc PR        | - 

Make `Symfony\Component\Debug\ExceptionHandler::setFileLinkFormat` accept null as a return type. 
Since Symfony requires PHP 7.2+ and that PHP feature was introduced in 7.1, I use that feature instead of changing the default value of the variable.

### CODE REVIEW

File: src/Symfony/Component/Debug/ExceptionHandler.php [hunk 1]
```diff
@@ -99,7 +99,7 @@ public function setHandler(callable $handler = null): ?callable
      *
      * @return string The previous file link format
```
Comment (fancyweb) [inline src/Symfony/Component/Debug/ExceptionHandler.php]: I think you could update the comment too.

File: src/Symfony/Component/Debug/ExceptionHandler.php [hunk 2]
```diff
@@ -99,7 +99,7 @@ public function setHandler(callable $handler = null): ?callable
...
      */
-    public function setFileLinkFormat($fileLinkFormat): string
+    public function setFileLinkFormat($fileLinkFormat): ?string
```
Comment (Tobion) [inline src/Symfony/Component/Debug/ExceptionHandler.php]: please remove the return type because it can also be a `FileLinkFormatter` (see `@param`) and adjust the annotation to be `@return string|FileLinkFormatter|null`

**Review by Tobion — CHANGES_REQUESTED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jlslew.
